### ISSUE TITLE
Button icon 

### ISSUE THREAD

**Issue by Masquetina** [angular/material2#1000]
Hi,
Today I created a new angular 2 app, using material, with all the latest versions: ang2 RC5 (with this new NgModule) and material components alpha.7-2, and I have this strange behavior... Everything works but, when I click the button on my navbar, this wierd, almost transparent area around that button appears, and it gets larger with every new click, and it is also clickable, like it is a part of the button. I can not understand what this is, and why it appears after click. Before I click the button, it is not there. ... And there is no Plunker for this, because it only implements RC4, and I'm using RC5.

Here is the navbar html:
```
<md-sidenav-layout fullscreen>
  <md-sidenav #sidenav>
    <md-toolbar color="primary">
      <button md-icon-button (click)="sidenav.close()">
        <md-icon>chevron_left</md-icon>
      </button>
      <h3 class="title">Menu</h3>
    </md-toolbar>
    <md-list>
      <a md-list-item *ngFor="let view of views"
         (click)="sidenav.close()">
        <md-icon md-list-icon>{{view.icon}}</md-icon>
        <span md-line>{{view.name}}</span>
        <span md-line>{{view.description}}</span>
      </a>
    </md-list>
  </md-sidenav>
  <md-toolbar color="primary" fullscreen>
    <button md-icon-button (click)="sidenav.open()">
      <md-icon>menu</md-icon>
    </button>
    <h3 class="title">My App</h3>
  </md-toolbar>
  <router-outlet></router-outlet>
</md-sidenav-layout>
```
And here is how I see the page and that strange something:
![01](https://cloud.githubusercontent.com/assets/1745197/17592661/69033c22-5fe3-11e6-93d4-5c7528b5ed9c.png)

Tnx

**Comment by fxck** [comment]
see https://github.com/angular/material2/issues/972 + https://github.com/angular/material2/commit/61027e9a694393d7170ce0ebeb3ca38f54a40aa0

**Comment by Masquetina** [comment]
... Adding core.css and/or overlay.css did not solve the problem for me.

**Comment by Masquetina** [comment]
My bad, core.css did solve it. ... I made typo in `<link... core.css" >`
It's OK now.
Tnx @fxck

**Comment by trainerbill** [comment]
I am having a similar issue.  Is there a plunker template for alpha7 that I can try and reproduce?  I have a button/icon in a toolbar:
```js
<md-toolbar color="primary">
  <button md-mini-fab (click)="leftNavToggle()">
    <md-icon>menu</md-icon>
  </button>
  <span>{{header}}</span>
</md-toolbar>
```

Everything is good on render:
![image](https://cloud.githubusercontent.com/assets/3578259/17602320/bf7800fe-5fd1-11e6-8f82-b5b4a141fd09.png)

After clicking the button I get an overlay that stays and is clickable:

![image](https://cloud.githubusercontent.com/assets/3578259/17602334/d5e4bd46-5fd1-11e6-83e3-2e869617d3aa.png)

I have included core.css and overlay.css

![image](https://cloud.githubusercontent.com/assets/3578259/17602395/10ab8d06-5fd2-11e6-8195-3cb4cbe5d197.png)
![image](https://cloud.githubusercontent.com/assets/3578259/17602414/1fa740de-5fd2-11e6-8714-fd48c6c69f74.png)
