### ISSUE TITLE
two selections available for the autocomplete

### ISSUE THREAD

**Issue by um-oscar** [angular/material2#10018]
#### Bug, feature request, or proposal:
Only one selected item from the autocomplete result list

#### What is the expected behavior?
when selecting a value or hover over the item only one from the list should be highlighted 

#### What is the current behavior?
two item can be highlighted concurrently, one with the mouse hover and one with the keyboard

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by josephperrott** [comment]
Closing as both elements should highlight as one is active and one is hovered.
