### ISSUE TITLE
Autocomplete replaces the value manually entered for the selected from autocomplete result list

### ISSUE THREAD

**Issue by oscarlagatta** [angular/material2#10017]
#### Bug, feature request, or proposal:
Autocomplete when selecting a value from the autocomplete list 

#### What is the expected behavior?
it should keep the text manually entered and have the option to ignore the selected to not modify what was typed within the input box

#### What is the current behavior?
It overrides what was in the input box by the selected value in the autocomplete result list

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
When searching people want to know what is the actual text they been using, and not to lose that value by the selection 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "^5.0.0-rc0",
Windows 8,
Chrome

#### Is there anything else we should know?
No, thank you

**Comment by julianobrasil** [comment]
Could you give more details of the behavior you extected? Based on what I understood from your request, the autocomplete should not replace the typed text by what you've selected. 

It's strange. Why would you select something if you don't want it do be the actual value in the input?

**Comment by oscarlagatta** [comment]
Thanks Juliano

Because you loose what you’ve written ? And perhaps you’d like to keep that
text for further searching ?

**Comment by julianobrasil** [comment]
Well... you can control what is shown in the input by the `displayWith` input. Then you can, for example save what was typed in another property to use in the `displayWith`.

**Comment by crisbeto** [comment]
I don't see the point of having an autocomplete if you want to maintain what the user has written. In that case why not use a regular `input`?

**Comment by oscarlagatta** [comment]
Perhaps it’s because there’s another use case where you don’t want to have
the autocomplete full behaviour just having the suggestions displayed and
use the results differently  will suffice

**Comment by crisbeto** [comment]
I see what you mean, but it goes against all of the assumptions made when building the autocomplete, not to mention the uncertainty about how accessibility would be handled.
