### ISSUE TITLE
Dense lists avatar size doesn't follow the guidelines

### ISSUE THREAD

**Issue by Philip-Sultanescu** [angular/material2#10019]
#### Bug, feature request, or proposal:
Dense lists avatar size doesn't follow the [guidelines](https://material.io/guidelines/components/lists.html#lists-specs), it should be 36px in height and width.

![components-lists-keylines-two10-dense](https://user-images.githubusercontent.com/30979663/36380549-f8e36a32-1582-11e8-9f35-220a54bf514f.png)
![components-lists-keylines-two10](https://user-images.githubusercontent.com/30979663/36380550-f9005bb0-1582-11e8-8198-5a449dec293e.png)

#### What is the expected behavior?
Dense list avatar size should be 36px;

#### What is the current behavior?
In material2/src/lib/list/list.scss
$mat-list-avatar-size = 40; For both normal and dense lists.

#### What are the steps to reproduce?
Dense list to the right should have smaller avatars.
https://tina-material-tree.firebaseapp.com/list

#### What is the use-case or motivation for changing an existing behavior?
Avatar size should follow the guidelines.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^5.2.5",
"@angular/material": "^5.2.1",

**Comment by philip-firstorder** [comment]
@crisbeto Now because of the mat-list-item-with-avatar it gets set to 56px, which is wrong.
https://angular-gqqput.stackblitz.io

The height should remain 48px when using mat-nav-list with mat-list-icon.
https://material.io/design/components/navigation-drawer.html#specs
