### ISSUE TITLE
md-selected-text

### ISSUE THREAD

**Issue by ArulArikrishnan** [angular/material2#10014]
This is what we wanted to achieve using md-select-label

![image](https://user-images.githubusercontent.com/36615399/36363646-aa78e4c6-1564-11e8-9f54-8b016f7be690.png)

**Comment by ZiruZanrgeiff** [comment]
Hey @ArulArikrishnan the md prefix is very very old. Did you saw the Material's documentation?

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
