### ISSUE TITLE
Dynamical Sidenav RTL doesn't work

### ISSUE THREAD

**Issue by Philip-Sultanescu** [angular/material2#10027]
#### Bug, feature request, or proposal:
Changing RTL dynamically doesn't work on sidenav, it pushes/resizes the center content wrong on 'side' and 'push'.

![ltr](https://user-images.githubusercontent.com/30979663/36394214-7ce7a75a-15b3-11e8-8229-b0cd8b8382f3.png)
![rtl](https://user-images.githubusercontent.com/30979663/36394215-7cffd12c-15b3-11e8-8277-cce263afb6ab.png)

#### What is the expected behavior?
To work when changing the dir="rtl" dynamically.

#### What is the current behavior?
Is doesn't recalculate correctly when changing the dir dynamically. 
But it does work correctly if we set the dir="rtl" at page load.

#### What are the steps to reproduce?
Open and click on RTL toggle button:
https://stackblitz.com/edit/angular-dyx1un?file=app%2Fsidenav-mode-example.html

#### What is the use-case or motivation for changing an existing behavior?
To implement dynamic Bidirectionally in applications where the sidenav is used.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "^5.2.1",

#### Is there anything else we should know?
Related to #646

**Comment by Philip-Sultanescu** [comment]
It actually works but I should have set the dir on an app control.

Maybe explain this also in the documentation on how to set the dir value:
https://material.angular.io/cdk/bidi/overview

**Comment by geelus** [comment]
Hi Philip
I'm having the exact problem but wasn't able to understand how you fixed it. Can you please explain more?
Thanks

**Comment by philip-firstorder-io** [comment]
In app.component.html I wrote on my **most root element** the [dir] attribute, like this in my case:
`<mat-sidenav-container [dir]="dir">`

Then the dir variable is defined in app.component.ts and subscribed to.
```
import { Direction } from '@angular/cdk/bidi';
// this is a service where I update the dir when selecting another language in the drop-down, you can create your own here
import { UiLanguageService } from './services/ui-language.service'; 

export class AppComponent implements OnDestroy, OnInit {
  dir: Direction;

  constructor(
    private uiLanguageService: UiLanguageService
  ) {
    // when the language is changed I update the dir in my language service, and here I subscribe to that change to be passed to the dir variable in app.component
    this.uiLanguageService.dir.subscribe(dir => {
      this.dir = dir;
    });
  }

  ngOnDestroy(): void {
    // prevent memory leak when component destroyed
    this.uiLanguageService.dir.unsubscribe();
  }
```

**Comment by geelus** [comment]
Thank you very much Philip. It's all working perfectly now.

**Comment by geelus** [comment]
By the way, this is a copy of my service if anyone looking for the service implementation as well:

import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import { Direction } from '@angular/cdk/bidi';

@Injectable()
export class UiDirectionService {
    dir: BehaviorSubject<Direction>;
    direction: Direction;
    constructor() {
        this.direction = "ltr";
        this.dir = new BehaviorSubject(this.direction);
    }
    toggleDirection() {
        this.direction = this.direction == "ltr" ? "rtl" : "ltr";
        this.dir.next(this.direction);
    }
}
