### ISSUE TITLE
Multiselect checkboxes not aligning to the right in RTL

### ISSUE THREAD

**Issue by Philip-Sultanescu** [angular/material2#10023]
#### Bug, feature request, or proposal:
Multiselect checkboxes not aligning to the right in RTL

![screen shot 2018-02-19 at 18 20 34](https://user-images.githubusercontent.com/30979663/36390187-6cb9e106-15a2-11e8-8eed-bba43b45879d.png)

#### What is the expected behavior?
Checkboxes should align to the right

#### What is the current behavior?
Checkboxes are aligned to the left.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-5lqd6r?file=index.html

#### What is the use-case or motivation for changing an existing behavior?
Conform to the [guidelines on bidirectionally](https://material.io/guidelines/usability/bidirectionality.html#bidirectionality-ui-mirroring-overview).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 "@angular/material": "^5.2.1",

**Comment by crisbeto** [comment]
The select does pick up the direction, but you need to set it either on the `html`, the `body` or an element inside the Angular app. In your example the `dir` is on an element outside of the app. That being said, there appears to be a weird visual glitch when it's in RTL on Chrome (the options shift around on click).

**Comment by Philip-Sultanescu** [comment]
@crisbeto Solution worked, thanks. 

Maybe explain this also in the documentation on how to set the dir value:
https://material.angular.io/cdk/bidi/overview
