### ISSUE TITLE
cdk-experimental dialog build not working

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/material2#10032]
I don't know whether  this bug report is valid, as cdk-dialog component is experimental

#### Bug
cdk-experimental dialog build not working

#### What is the expected behavior?
exprimental dialog should work

#### What is the current behavior?
exported build has botched imports

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-ugzp1g

#### Is there anything else we should know?

in exported build file `node_modules\@angular\cdk-experimental\esm5\dialog.es5.js:22`
`Overlay` is imported as 
`import { Overlay as Overlay$1, OverlayConfig, OverlayModule } from '@angular/cdk/overlay';`

but used as 

```
    Dialog.ctorParameters = function () { return [
        { type: Overlay, }, // here
        { type: Injector, }, // injector has never been imported
        { type: undefined, decorators: [{ type: Inject, args: [DIALOG_REF,] },] },
        { type: undefined, decorators: [{ type: Inject, args: [DIALOG_SCROLL_STRATEGY,] },] },
        { type: Dialog, decorators: [{ type: Optional }, { type: SkipSelf },] },
        { type: Location, decorators: [{ type: Optional },] },
    ]; };
```

and `Injector` has never been imported

After Manually fixing imports in node_modules, everything works

**Comment by josephperrott** [comment]
Closing as #10052 is merged.
