### ISSUE TITLE
removing module.id does not  resolve issues in Webpack builds

### ISSUE THREAD

**Issue by gregbown** [angular/material2#1003]
I believe the fix that resolved all errors stemming from module.id  with Angular 2 rc5 in webpack builds is this fix to metadata_resolver
https://github.com/angular/angular/pull/10595/commits/f54f9efc0e70eb1c71ac8eb6a8ed690f1e7f09f9

Removing moduleId from md-input breaks functionality for all material 2 components in webpack (unsure about other build processes) when using attributes like formControlName and placholder.
The error:
zone.js:461 Unhandled Promise rejection: Template parse errors:
Can't bind to 'placeholder' since it isn't a known property of 'md-input'.
If 'md-input' is an Angular component and it has 'placeholder' input, then verify that it is part of this module.
If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.

If I add schemas: [CUSTOM_ELEMENTS_SCHEMA] to @NgModule I get the error.
“No value accessor for form control” even though control is named.

Additionally, removal of module.id seems to cause display and positioning errors.

Adding back module.id into all material components restores all functionality provided the fix to metadata_resolver is in place and ther are no errors or display issues.

Versions: Angular 2 rc5, Material 2 alpha 7-2, Windows 10, Chrome

Thank you

**Comment by DevVersion** [comment]
The fix definitely is the correct one. The issue isn't coming from Angular Material 2.

We were adding the fix, to remove all `module.id` references to our distributed files, because it doesn't make sense to have the `module.id` definition on the component metadata, when the `template` and `styleUrls` are already inlined.

I personally use `alpha.7-2` with Webpack and the fix worked for me.


> In general, removing the `module.id` should not introduce any "positioning" issues. 
> You probably have a real error in your template.

Would be good to share some code, if so.

**Comment by gregbown** [comment]
I do not think Webpack is possible in a plunkr so here is what I believe is the relevant code.
Thank you for your prompt response, Paul.

**MainModule**
`import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { BrowserModule } from '@angular/platform-browser';
import { ReactiveFormsModule, FormsModule  } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { NgModule, provide, ANALYZE_FOR_ENTRY_COMPONENTS } from '@angular/core';
/* Used to set application base. */
import { APP_BASE_HREF } from '@angular/common';
/* Material 2 modules */
import { MdButtonModule } from '@angular2-material/button';
import { MdInputModule } from '@angular2-material/input';
import { MdListModule } from '@angular2-material/list';
import { MdToolbarModule } from '@angular2-material/toolbar';
/* Entry component */
import { App } from './op.app';
import { routes } from './op.routes';

@NgModule({
  bootstrap: [
    App
  ],
  declarations: [
    App
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    RouterModule.forRoot(
      routes, {useHash:false}),
    // vendors
    MdButtonModule,
    MdInputModule,
    MdListModule,
    MdToolbarModule
  ],
  providers: [
    { provide: APP_BASE_HREF, useValue: '/test/organized-play-tools/' },
    { provide: ANALYZE_FOR_ENTRY_COMPONENTS, useValue: routes, multi: true }
  ]
})
export class MainModule {

}

export function main() {
  return platformBrowserDynamic().bootstrapModule(MainModule);
}

export function bootstrapDomReady() {
  console.log("boot");
  // bootstrap after document is ready
  document.addEventListener('DOMContentLoaded', main);
}

if (document.readyState === 'complete') {
  main();
} else {
  bootstrapDomReady();
}`
**App component**
`import { Component, ViewEncapsulation } from '@angular/core';
import { RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app',
  encapsulation: ViewEncapsulation.None,
  styleUrls: [
    './op.app.scss'
  ],
  template:
  `<md-content>
      <md-toolbar class="brandbar">
          <md-brand>
            <img class="brand-image" src="/images/global/wrapper/snipe.png"/>
          </md-brand>
          <span class="title fill">ORGANIZED PLAY TOOLS</span>
          <md-nav-list>
            <md-list-item>
              <a md-button routerLinkActive="active" [routerLink]=" ['./simulations'] ">Simulations</a>
            </md-list-item>
            <md-list-item>
              <a md-button routerLinkActive="active" [routerLink]=" ['./live-events'] ">Live Events</a>
            </md-list-item>
            <md-list-item>
              <a md-button href="/test">Other Tools</a>
            </md-list-item>
          </md-nav-list>
      </md-toolbar>
      <main>
        <router-outlet></router-outlet>
      </main>
      <footer></footer>
    </md-content>
  `
})
export class App {
  private name: string = 'PLAT-TOOLS';
  constructor() {}
}`
**Simulations component**
`import { Component, ViewEncapsulation, ChangeDetectionStrategy } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators, AbstractControl, NgForm } from '@angular/forms';
import { RestServices } from '../../../apps/common/services/restservices';
import { IEventSettings, IResponseError, ISetting, ISettings, IUpdate, ICurrencies } from '../../../apps/common/interfaces';
import { Observable, Subscription } from 'rxjs/Rx';

@Component({
  selector: 'simulations',
  providers: [RestServices],
  directives: [NgForm],
  encapsulation: ViewEncapsulation.None,
  styleUrls: [ './op.simulations.scss' ],
  templateUrl: './op.simulations.html'
})

export class Simulations {

  public selectedValue: string|number = "Curent Value";
  public updateSettingForm: FormGroup;
  private submittedRMT: boolean = false;
  private submittedFRMT: boolean = false;
  private _settingsSub: Subscription;
  private _updateSub: Subscription;
  private _rewardsSub: Subscription;
  private _freeRewardsSub: Subscription;
  private settings: [ISetting];
  private currencies: ICurrencies;
  private rewardData: string;
  private freeRewardData: string;

  constructor( private _fb: FormBuilder, private _http: RestServices ) {

    this.settings = [{name:"", value:""}];
    this._settingsSub = this._http.getEventSettings("TEST").map(res => {
      /* Handle server error */
      if(typeof res["error"] !== "undefined") {

        console.log(res["error"]);

      } else {
        // ToDo set currencies here.
        for(var i = 0;i < res.Values.length; i++){
          this.settings[i] = {name: res.Values[i].Key, value: res.Values[i].Value};
        }
      }
      this.updateSettingForm.reset({ "newValue": "", "settingName": this.settings[0].name, "environment": "TEST" });
      this.selectedValue = this.settings[0].value;
      this._settingsSub.unsubscribe();
    }).subscribe();
  }
  ngOnInit() {
    /* Set up form controls and validation */
    this.updateSettingForm = this._fb.group({
      'newValue': ['', [Validators.required]],
      'settingName': ['', [Validators.required]],
      'environment': ['TEST']
    });
  }
  onUpdateSelection( key:string ) {
    for(var i = 0; i < this.settings.length; i++) {
      if(this.settings[i].name == key) {
        this.selectedValue = this.settings[i].value;
        this.updateSettingForm.reset({ "newValue": "", "settingName": this.settings[i].name, "environment": "TEST" });
      }
    }
  }
  updateSetting( formData: IUpdate ) {
    this._updateSub = this._http.updateEventSetting(formData).map(res => {
      /* Handle server error */
      if(typeof res["error"] !== "undefined") {
        console.log(res["error"]);
      } else {
        for(var i = 0;i < res.Values.length; i++){
          this.settings[i] = {name: res.Values[i].Key, value: res.Values[i].Value};
        }
        this.updateSettingForm.reset({ "newValue": "", "settingName": this.settings[0].name, "environment": "TEST" });
        this.selectedValue = this.settings[0].value;
      }
      this._updateSub.unsubscribe();
    }).subscribe();
  }
}`
**simulations template**
`<fieldset>
	<legend>Update Setting</legend>
	<form [formGroup]="updateSettingForm" id="updateSettingForm" novalidate (ngSubmit)="updateSetting(updateSettingForm.value)" autocomplete="off">
		<div class="form-group">
			<input type="hidden" formControlName="environment" name="environment"/>
			<select (change)="onUpdateSelection($event.target.value)" formControlName="settingName">
				<option *ngFor="let setting of settings" [value]="setting.name">{{setting.name}}</option>
			</select>
			<md-input
				id="newValue"
				placeholder="Current value {{selectedValue}}"
				formControlName="newValue"
				[class.has-error]="updateSettingForm.controls.newValue.touched && !updateSettingForm.controls.newValue.valid"
			></md-input>		
		</div>
	    <div class="form-footer">
			<button md-raised-button type="submit" [disabled]="!updateSettingForm.valid">Submit</button>
		</div>
	</form>
	<div class="current-settings">
		<ul>
			<li class="setting-header"><span class="setting-name">SETTINGS</span><span class="setting-value">VALUES</span></li>
			<li *ngFor="let setting of settings" ><span class="setting-name">{{setting.name}}</span><span class="setting-value">{{setting.value}}</span></li>
		</ul>
	</div>
	<p class="debug">Debug: {{ updateSettingForm.value | json }}</p>
</fieldset>`

**Comment by DevVersion** [comment]
It definitely isn't - You are right, I just asked for some code snippets to take a closer look for _common_ issues.

Would be good if you transform your code snippets into an external snippet.
> e.g http://hastebin.com

**Comment by gregbown** [comment]
Thanks for the tip, I'm a bit of a git rookie, we have our own version control internally.
Here is the snippet [https://gist.github.com/gregbown/f1545665a35fdf8b2b7f8e0aaaaa6197](url)

**Comment by DevVersion** [comment]
@gregbown At first look I couldn't really find anything wrong in your shared code. But I have to say I don't had really much time to look into it.

I'm still assuming this doe relates to something else, and not to the `module.id` removal. 

If the `module.id` removal introduced some issues, then there would be probably more issues (than one)

> Also I'm running alpha.7-2 personally as well and it seems to work like a charm.

**Comment by gregbown** [comment]
Update:
I just added MdTabsModule to my project and the tabs don't event render.  As soon as I added the moduleId: module.id, to the MdTabGroup the tabs render with full functionality.  I have tried changing loaders and I have verified my ts config matches  the starter projects out there, however; none of the starter projects seem to have updated to Angular 2 rc5 & material 7-2.  Could you recommend a project that is up to date? or possibly share your setup?

**Comment by DevVersion** [comment]
I just tested it again to be sure that I don't miss anything. 

> The Tabs component seems to work fine.

Here is some basic setup to share
- https://gist.github.com/DevVersion/17eeeb2e5d717c20baf70abc762e58df

Just to repeat my self, it doesn't even make sense that it works with the `module.id` and without the `module.id` not..

**Comment by gregbown** [comment]
Thank you Paul.  I believe the issue was in my webpack configuration, I may never know exactly where.  I scrapped my hacked together webpack.config and started with the bare minimum.  I used https://github.com/preboot/angular2-webpack/webpack.config.js as a starting point, modifying the loaders and paths as needed.

Thanks again for your time.
