### ISSUE TITLE
Scroll smooth issue in dialog on close

### ISSUE THREAD

**Issue by amaneer94** [angular/material2#10033]
#### Bug, feature request, or proposal:
scroll is not fluent when dialog is closed.

#### What is the expected behavior?
on closing dialog, application scroll should be smooth

#### What is the current behavior?
when dialog is closed, scroll is rough

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome/Chromium are affected but working good in opera
"@angular/core": "^5.2.0",
"@angular/material": "^5.2.1",
"typescript": "~2.5.3"

#### Is there anything else we should know?
`<div class="cdk-overlay-container"></div>` introduces when dialog is opened with 
`.cdk-overlay-container {
    position: fixed;
    z-index: 1000;
}`
after dialog is closed, I tried to remove both properties, scroll seemed smooth.

**Comment by crisbeto** [comment]
Spent some time looking into it, some things to keep in mind:

- We need to rework the `ConnectedPositionStrategy` tests to go through the `Overlay` service.
- We need to rework a bit in the menu and select components so they detach after their animation is finished, otherwise it'll be cut off.
