### ISSUE TITLE
input chip wrong placeholder position

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#10041]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Documentation screenshot

![image](https://user-images.githubusercontent.com/8130692/36426416-ef082d12-165a-11e8-9ed4-081ab16fb3e7.png)

#### What is the current behavior?

The placeholder of the input is taking place after the chips but it should be fixed

Stackblitz screenshot

![image](https://user-images.githubusercontent.com/8130692/36426428-fa56316e-165a-11e8-93a4-26298410cb01.png)

#### What are the steps to reproduce?

Follow the documentation for the [chip-input](https://material.angular.io/components/chips/overview#chip-input)

Here is a [stackblitz](https://stackblitz.com/edit/angular-material2-issue-fpgm9p)

**Comment by julianobrasil** [comment]
It's working fine for me. Maybe its specific to your OS/Browser.

I tested it with Windows 10/Chrome 64.0.3282.167

**Comment by MurhafSousli** [comment]
I have this issue with all browsers, I tested it on
Chrome 64.0.3282.167 (64-bit)
Firefox 58.0.2 (64-bit)
Microsoft Edge 41.16299.248.0

**Comment by surfer19** [comment]
You have wrong closing tags, check image.. + Remove matPrefix you achieve documentation behavior. 

<img width="1276" alt="snimka obrazovky 2018-02-20 o 16 29 42" src="https://user-images.githubusercontent.com/10733034/36432907-9cd8c21c-165b-11e8-8247-eca989b83e48.png">

**Comment by josephperrott** [comment]
Closing, as noted above, you will need to place the input within the `mat-chip-list` element for the styling to work as expected.

**Comment by MurhafSousli** [comment]
Great! Thanks a lot
