### ISSUE TITLE
inherited abstract class not declared

### ISSUE THREAD

**Issue by alexpj17** [angular/material2#10043]
#### Bug, feature request, or proposal:
declare in line 5, fromIso8601(iso8601String: string); within moment-date-adapter.d.ts
#### What is the expected behavior?
error fix
#### What is the current behavior?
it does not run
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
declare in line 5, fromIso8601(iso8601String: string); within moment-date-adapter.d.ts

#### What is the use-case or motivation for changing an existing behavior?
error fix

**Comment by josephperrott** [comment]
It appears that `fromIso8601` is not an abstract method defined on the abstract `DateAdapter` class.

**Comment by mmalerba** [comment]
`fromIso8601` is a method that used to exist on `DateAdapter` but has since been removed, you probably need to update your dependencies
