### ISSUE TITLE
MatMenu - First Button Focus but don't change when hover other button.

### ISSUE THREAD

**Issue by Spawnrad** [angular/material2#10040]
Bug, feature request, or proposal:

Bug

What is the expected behavior?
When we are hover a button, the button should be focus.

What is the current behavior?
I use MatMenu with different button item.
When i click on my menu, the first element is focused => ok
When i hover an other item button on my menu the element is not focus.

So we have always the first element focus. The focus work when we use keyboard.

Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material 5.2.1
Angular 5.2.5
Chrome 61.0.3163.100

Thank you.

**Comment by crisbeto** [comment]
I don't see the issue. Actual focus (as in changing the `document.activeElement`) shouldn't change when hovering and we already highlight the item being hovered.

**Comment by josephperrott** [comment]
Closing as both elements should highlight as one is active and one is hovered.

**Comment by Spawnrad** [comment]
hi @josephperrott and thank you for your answer. But for you its not wierd to have in a menu 2 thing highlight at the same time?

**Comment by Spawnrad** [comment]
Sorry that was a bug with bootstrap since the update idk why. Thanks.
