### ISSUE TITLE
publish @angular/material-schematics

### ISSUE THREAD

**Issue by amitport** [angular/material2#10058]
`6.0.0-beta.2` added a material schematics shell feature. How can I use it? it doesn't seem to be published

**Comment by josephperrott** [comment]
This feature is not yet ready for release.  Stay tuned to our changelog/announcements to see when it is released.

**Comment by Hotell** [comment]
I dunno what your workflow is, bu I guess standard thing to do is to close an issue once it is resolved ( in this case schematics published to npm ), WDYT ? :)

**Comment by amitport** [comment]
or just, next time please don't write it in the changelog so people don't waste time looking for it
