### ISSUE TITLE
expansion-panel doesn't scroll to content on expanding

### ISSUE THREAD

**Issue by joeherwig** [angular/material2#10059]
Proposal:

As a website-user i expect that on uncollapsing a expannsion-panel where the header-bar is shown on the bottom of my viewport the page is scrolled so that i can view the content of the expansion-panel without the need of scrolling manually to the appropriate position.

#### What is the current behavior?
The component fires an event, but doesn't scroll to the panel and its content remains invisible.

#### What is the use-case or motivation for changing an existing behavior?
Remove the neccesity for each developer to catch the `opened`-Event and implement an own `scrollTo`-feature in each site.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular material 5.2.0

**Comment by josephperrott** [comment]
Closing as this is working as intended.  The expansion panel does not manage the layout of the page and because of this does not manage the scroll location.

**Comment by joeherwig** [comment]
OK. Sounds logic. So we'll catch the event and handle ourselves...
