### ISSUE TITLE
Stackblitz examples not working

### ISSUE THREAD

**Issue by barni2000** [angular/material2#10063]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
This works https://material.angular.io/components/menu/overview.

#### What is the current behavior?
Stackblitz variant is not. https://stackblitz.com/angular/emekjleyejm?file=app%2Fmenu-overview-example.ts

#### What are the steps to reproduce?
Open the stackblitz example.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Browser: Chromium Version 64.0.3282.167 (Developer Build) (64-bit)
OS: Archlinux

**Comment by donroyco** [comment]
@barni2000 I _assume_ you're mentioning Google Chrome. It's working okay for me on macOS latest version of High Sierra. Do you see any errors in the console?

**Comment by barni2000** [comment]
Yes:
![image](https://user-images.githubusercontent.com/9256038/36478762-547c4d4e-1706-11e8-82bd-ee936b909852.png)

If I export also not working.

**Comment by barni2000** [comment]
Firs i got this after npm install:
````
> angular-template@0.0.0 start /home/work/emekjleyejm.angular
> ng serve

module.js:557
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/work/emekjleyejm.angular/node_modules/@angular-devkit/schematics/src/tree/virtual.js:10:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-template@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-template@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/work/.npm/_logs/2018-02-21T11_56_22_632Z-debug.log
````

**Comment by barni2000** [comment]
Afer I install @angula-devkit/core i got this with npm start:
````

> angular-template@0.0.0 start /home/work/emekjleyejm.angular
> ng serve

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-02-21T11:58:05.453Z                                                       
Hash: 7d8137d0a69c57926f5f
Time: 2024ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.93 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 636 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 150 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 853 kB [initial] [rendered]

ERROR in Error: Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
    at Object.resolveEntryModuleFromMain (/home/work/emekjleyejm.angular/node_modules/@ngtools/webpack/src/entry_resolver.js:131:11)
    at Promise.resolve.then.then (/home/work/emekjleyejm.angular/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:239:54)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

webpack: Failed to compile.
````

**Comment by barni2000** [comment]
If I split AppModule to app/app.module.ts from main.ts its works.

**Comment by josephperrott** [comment]
Can you provide your own reproduction case as the example you linked to seems to be working as expected.

**Comment by barni2000** [comment]
![image](https://user-images.githubusercontent.com/9256038/36515687-e8ac7cb8-177a-11e8-863f-102e4f09d275.png)

**Comment by barni2000** [comment]
I create some changes it works after export in local but in stackblitz also not  loading.
- npm install
- npm start

https://angular-hlrhkp.stackblitz.io

**Comment by barni2000** [comment]
I've done some testing on other web browsers. The original examples works with Firefox, i think this issue Chromium related.

**Comment by barni2000** [comment]
I have installed Google-Chrome instead of Chromium and its working, but the examples still not exportable.
