### ISSUE TITLE
mat-radio-group data binding does not work when parent component is repeated

### ISSUE THREAD

**Issue by kwall2004** [angular/material2#10065]
#### What are the steps to reproduce?
See that both mat-radio-group and the standard html radio inputs are bound to the same property, yet the mat-radio-group data binding only works in the 3rd instance of the parent component.

https://stackblitz.com/edit/angular-gt2qqc

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
