### ISSUE TITLE
Mat-nav-list not update after adding class via renderer2

### ISSUE THREAD

**Issue by scandinave** [angular/material2#10066]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When adding class to a mat-list-item, the DOM representation should be update as the render.

#### What is the current behavior?
Class is add on the element, but DOM representation is not sync. a QueryList that contains the list of update item, does not see anything. Querying DOM via document.querySelectorAll return the same things. No classes are  added. I was first think of a problem with QueryList that not update it model. But after trying the same things with an array, problem remain the same.

P:S : i know i can achieve this behavior with routerLinkActive directive. But i can't use it in my case.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://angular-xigdge.stackblitz.io
Just click on link2 and click back to link1. All stay activated. Class list does not update.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.6.6
Angular: 5.2.2
@angular/material: 5.1.0

**Comment by josephperrott** [comment]
Closing as this is working as expected.  In your example you provide, you are adding the `active-link` class content div of the `mat-list-item` (`.mat-list-item-content`).  The styling should be applied to the anchor with `mat-list-item`


```
<a mat-list-item>  <-- The class should be added here
  <div class="mat-list-item-content"> <-- The class is being added here
   ....
```

**Comment by scandinave** [comment]
ohh shit. How i could miss it. Thank you
