### ISSUE TITLE
mat-radio-group data binding does not work when parent component is repeated

### ISSUE THREAD

**Issue by kwall2004** [angular/material2#10067]
#### Bug, feature request, or proposal:
Fix mat-radio-group data binding so it works when parent component is repeated.

#### What is the expected behavior?
mat-radio-group data binding should work when parent component is repeated.

#### What is the current behavior?
mat-radio-group data binding does not work when parent component is repeated.

#### What are the steps to reproduce?
See that both mat-radio-group and the standard html radio inputs are bound to the same property, yet the mat-radio-group data binding only works in the 3rd instance of the parent component.

https://stackblitz.com/edit/angular-gt2qqc

#### What is the use-case or motivation for changing an existing behavior?
I need to be able to repeat the parent component of mat-radio-group.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.5
Material 5.2.1
Windows 10 Pro
TypeScript 2.6.2
Chrome 64.0.3282.167

**Comment by julianobrasil** [comment]
@josephperrott, the other issues about this were closed (the second one because of wrong formatting), but it appears he has an important point. Regardless the fact he is using separate form tags (the `<form>` tags are inside a custom component), something weird is happening - ngModel seems to become confused.

**Comment by BrianCerasuolo** [comment]
I have also run into this same issue

**Comment by kwall2004** [comment]
FWIW, the workaround is to ensure that the mat-radio-group name is unique across all instances of the custom component.

**Comment by josephperrott** [comment]
I think I misunderstood the previously opened issue about it.

**Comment by tinayuangao** [comment]
This is working as intended. `mat-radio-button` will uncheck all radio buttons with the same name when a radio button is clicked. 
Each radio group should have its own unique name. If you remove the `name="radioTypeA"` on `mat-radio-group`, radio group will automatically generate a unique name.

**Comment by kwall2004** [comment]
Seems like a weird decision to make it less functional than a standard html radio input, but ok I guess.

**Comment by julianobrasil** [comment]
@kwall2004, @tinayuangao, there's another issue tracking this behavior. It looks like it's not normal the uniquenessential of the name bleed outside a form.

The other issue: #5983

**Comment by kwall2004** [comment]
I think we can definitively say it's not normal.
