### ISSUE TITLE
What will be the future of this lib now that @material components are out?

### ISSUE THREAD

**Issue by odahcam** [angular/material2#10071]
That's a question.

Material components for web were released and they look awesome, really, there are lots of components there, so what will be the future of @angular/material2 now that this components are out?

Yes, I think that the fact they are from Google matters, but in fact I just want to learn.

Will @angular/material support any of @material's components?

Thanks, you can see more about here: https://material.io/components/web/.

**Comment by josephperrott** [comment]
MDC components have actually been out for a while at this point.  See [this comment](https://github.com/angular/material2/issues/4154#issuecomment-295508021) for details
