### ISSUE TITLE
Mouse Selection by Column for Mat-table

### ISSUE THREAD

**Issue by svsgdev** [angular/material2#10072]
feature request: In Mat-Table - it would be nice to be able to copy data column vice . I think it is a very important feature.

What is the expected behavior?
 Copy data column wise - maybe on ctrl key+selection like what firefox supports.

What is the current behavior?
Copies all rows data

**Comment by mariohmol** [comment]
Hi there, is any ideas how is able to implement that manually?

**Comment by andrewseguin** [comment]
Here's a quick example of adding a button yourself: https://stackblitz.com/edit/angular-dyqrhh?file=app/table-basic-example.ts

I don't see us adding this natively in the table since there is no where in the spec that defines how/where this should be.

**Comment by mariohmol** [comment]
Well.. i dont think that this is the selection behaviour that , at least me, was looking for.

Anyways, i know that is not on docs.. but shouldnt it be as future features?

**Comment by andrewseguin** [comment]
I'm not sure of your request if my solution wasn't it

**Comment by mariohmol** [comment]
Check it out https://handsontable.com/examples.html?headers , see how columns/rows are selected

**Comment by andrewseguin** [comment]
The material design spec does not provide guidance on tables that have column selection, but this should be straightforward to implement on your own by adding a click event on the header cell and applying a custom class to the appropriate cells. This would also directly conflict with the sort component which also wants to use the header click event.
