### ISSUE TITLE
Select & Autocomplete Panel causes lag and choppy animation

### ISSUE THREAD

**Issue by skyfremen** [angular/material2#10080]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Smooth animation when entering into input by holding down a key.

#### What is the current behavior?
The animation is choppy

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-33e4nh

1) Select the 1st AutoComplete to open panel.
2) While Panel is open hold down the tab key (It will scroll through till the last Autocomplete)
3) Repeat step 1 and 2 for a few times.
4) Go to the last input and hold down a key. (The animation will be choppy) 

#### What is the use-case or motivation for changing an existing behavior?
The animation should not be choppy

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome OS
Angular 5.2.3
Material 5.2 & 5.2.1 & 5.2.2

#### Is there anything else we should know?
Not happening on 5.1.1 and below 
Suspect is due to the opening of panels
Suspect is due to #7721

**Comment by skyfremen** [comment]
Hi, any updates on this issue, it is preventing our team to upgrade beyond 5.1.1

**Comment by crisbeto** [comment]
I can definitely reproduce it in your example, but I wasn't able to in our local dev app. It looks like there's a `keydown` event leak somewhere. My hunch is that it was fixed in master by https://github.com/angular/material2/pull/10160.

**Comment by skyfremen** [comment]
Hi, @crisbeto wanted to double check if #10160 is released for 6.0.0 vibranium-vivarium.

**Comment by skyfremen** [comment]
Seems to be resolved in 6.0.0
