### ISSUE TITLE
Form field prefix and suffix icons not aligned properly

### ISSUE THREAD

**Issue by gtranter** [angular/material2#10089]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Material design guidelines for text fields specify icons to have 8px vertical spacing between itself and the input line, and 16px horizontally between icon and input text/placeholder (prefix specification only).

#### What is the current behavior?
Icons as prefix or suffix are currently raised about 14px above input line, and have almost no horizontal spacing from the input text/placeholder.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-jzfsl9

![image](https://user-images.githubusercontent.com/15054224/36546967-adf45fd8-17ba-11e8-8ae3-ba2839ed1bd0.png)

#### What is the use-case or motivation for changing an existing behavior?
Current appearance is poor and material guidelines are not being followed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.6
Angular Material 5.2.1

**Comment by mmalerba** [comment]
The actually shows both 8px and 16px versions: https://material.io/guidelines/components/text-fields.html#input-types-figure-caption-5

For the newer outline and fill variants in the spec it is clear that the 16px version is intended: https://material.io/guidelines/components/text-fields.html#text-field-boxes-figure-caption-11 we have chosen to go with this style by default for consistency between the different variants.

For the horizontal spacing we have decided to let the user specify. You can achieve the look you want by adding some simple CSS: https://stackblitz.com/edit/angular-jzfsl9-ev53fr?file=app/form-field-prefix-suffix-example.css

**Comment by gtranter** [comment]
Those specs are for text field boxes - are you not supporting ordinary (non-box) text fields?

**Comment by mmalerba** [comment]
https://material.io/guidelines/components/text-fields.html#text-fields-input-types

**Comment by gtranter** [comment]
@mmalerba I've seen that link already - what are you trying to say?

**Comment by mmalerba** [comment]
That is for a normal text field, as you can see the icon alignment is the same. Anyways we're not not supporting aligning them differently, this is just the default and you'll need to add some CSS if you want a different alignment

**Comment by gtranter** [comment]
That link doesn't show any fields with icons FYI (until I scroll down quite a bit) - it would be helpful if you could communicate better what specifically you are talking about to avoid confusion.

**Comment by mmalerba** [comment]
The link takes me right to the page scrolled right to this image: https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B5ZSepuCX1xOdEc4cHZWV3ZzTzg/password1.png
