### ISSUE TITLE
mat-select view don't reflect programatically changed model in 2-way data binding.

### ISSUE THREAD

**Issue by shavipathania** [angular/material2#10085]
#### Bug:
mat-select view (ie. checked options) doesn't get updated if its model has been changed.

#### What is the expected behavior?
When model has been changed then it should update checked options.

#### What is the current behavior?
When model is changed, checked options remain unchanged.

#### What are the steps to reproduce?
StackBlitz reproduction: <br/>
https://stackblitz.com/edit/angular-91ayo4?embed=1&file=app/select-value-binding-example.html<br/>

1. Unselect Green option by clicking (X) button in (Selections Section)
2. Check Model is being updated (Model Section).
3. But Checked options remain unchanged. (mat-select Section)

#### What is the use-case or motivation for changing an existing behavior?
The mat-select view must reflect changes in model

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.6
Material: 5.2.1
OS: Ubuntu
TypeScript: 2.6.2
Browser: Chrome

#### Is there anything else we should know?
Somewhat related to [ issue #9038 ]

**Comment by crisbeto** [comment]
The explanation here is similar to https://github.com/angular/material2/issues/10044. When you splice the array, the Angular change detection won't pick it up which means that the select won't be notified of the change.
