### ISSUE TITLE
Alignments of select field dropdown icon and date field calendar icon don't match prefix icon alignment.

### ISSUE THREAD

**Issue by gtranter** [angular/material2#10098]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Icons as prefixes and suffixes should be consistently aligned.

#### What is the current behavior?
The prefix icon on a select or date field is vertically higher than the dropdown or calendar open suffix icon.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ec1h7cStackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Looks bad and does not implement guidelines consistently.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.6
Angular Material 5.2.1

#### Is there anything else we should know?
According to https://github.com/angular/material2/issues/10089#issuecomment-367735643, you have chosen the 16px spacing for prefix and suffix icons according to the spec for text field boxes. It looks like select and date fields are following the 8px spacing spec for ordinary (non-box) fields. There should be consistency across all inputs or the ability to choose either, or at least special handling of the spacing for selects and dates.

**Comment by mmalerba** [comment]
These are both centered to match the prefix/suffix in the `appearance="standard"` version of the form-field that will be released with 6.0.0

![datepicker](https://user-images.githubusercontent.com/14793288/36572712-30ee1e42-17f2-11e8-8894-0dc240ca0a6a.png)
![select](https://user-images.githubusercontent.com/14793288/36572715-32b0ece6-17f2-11e8-95b0-cd374aa45090.png)
