### ISSUE TITLE
Cannot find control with name: 'language'

### ISSUE THREAD

**Issue by Raza92** [angular/material2#10103]
<form class="container" [formGroup]="form" (ngSubmit)="onSubmit(form.value)">
     <div>
    <input type="text" name="firstname" placeholder="First Name" formControlName="firstName">
    
      <input type="submit" disabled="!form.valid" value="Submit">
     </div>
     </form>

 ngOnInit() {
    this.form = new FormGroup({
      firstName: new FormControl("", Validators.compose([
        Validators.required,
        Validators.minLength(3)
      ]))
    })
  }

  onSubmit = function (user) {
    console.log(user)
  }

**Comment by Raza92** [comment]
<form class="container" [formGroup]="form" (ngSubmit)="onSubmit(form.value)">
  <div>
    <input type="text" name="firstname" placeholder="First Name" formControlName="firstName">
    <br>
    <select name="language" formControlName="language">
      <option value="C++">C++</option>
      <option value="C#">C#</option>
      <option value="Angular">Angular</option>
    </select>

    <br>
    <input type="submit" disabled="!form.valid" value="Submit">
  </div>
</form>

**Comment by crisbeto** [comment]
This looks like an issue somewhere else in your code.
