### ISSUE TITLE
mat-select crashes the browser

### ISSUE THREAD

**Issue by qpi** [angular/material2#10107]
#### Bug, feature request, or proposal:
in my project when I try to give class/array based data for the mat-select to populate the dropdown the browser crashes :(

#### What is the expected behavior?
This is what I wanna do, but here I used JSON object to populate the dropdown:
https://stackblitz.com/edit/angular-pgxiir

#### What is the current behavior?
If I try with my classes the browser tab freezes fully.

#### What are the steps to reproduce?
To reproduce, just remove the comment from the app.component.ts in line (15):
// get poiCategories() { return this._poiCategories; }
and after the browser frezees
https://stackblitz.com/edit/angular-tcm4jv?file=app%2Fapp.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I tried only with Chrome Version 64.0.3282.167 and Angular 5.0.0 with Material 5.2.2

**Comment by julianobrasil** [comment]
It seems every time angular change detection runs (and it runs when you try to open selection panel) you try to execute getIds(), which returns a new array which force the select to update it self, which in turn initiate another change detection cycle which executes getIds() again and this goes on forever.

You shouldn't call a function in the template that returns a new array each time it's executed. It leads you to this kind of issue.

**Comment by crisbeto** [comment]
@julianobrasil is correct, this is something that should be resolved in your code.

**Comment by qpi** [comment]
Thanks Guys, You're right after I changed my code it works well.
