### ISSUE TITLE
(matTree) Inconsistent level 1 (one) padding width

### ISSUE THREAD

**Issue by TishchenkoAlex** [angular/material2#10104]
from **checklist-tree-demo.html**
![image](https://user-images.githubusercontent.com/22451433/36584954-874f1a4c-1884-11e8-8700-f075b34fe245.png)

**Comment by djleonskennedy** [comment]
@TishchenkoAlex is tree released ?

**Comment by benb7760** [comment]
@djleonskennedy It's in master

**Comment by TishchenkoAlex** [comment]
@djleonskennedy yes, tree branch was merged to master by #9796

**Comment by julianobrasil** [comment]
As tree view isn't in design docs directory (https://github.com/angular/material2/wiki/Design-doc-directory), I'm not sure which spacing is the correct one. But less space looks more elegant.

**Comment by TishchenkoAlex** [comment]
@julianobrasil agree! less space looks better

**Comment by djleonskennedy** [comment]
@TishchenkoAlex thank you
