### ISSUE TITLE
virtual-scroll: add docs

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#10123]
Add documentation for virtual scrolling

**Comment by raygervais** [comment]
I'd be happy to help with documentation for the virtual-scroll, but can you point me in the right direction towards getting it set up? Is the next version going to introduce a change to any APIs going forward ex, renaming an attribute?

**Comment by mmalerba** [comment]
@raygervais I'm working on implementing the virtual scroll right now. It's not done yet so there's nothing to document for now. You can follow the progress on the virtual-scroll branch though: https://github.com/angular/material2/tree/virtual-scroll/src/cdk-experimental/scrolling

**Comment by darkbasic** [comment]
Hi @mmalerba 
I'm writing a "Whatsapp Clone" Angular tutorial using Material (https://github.com/Urigo/whatsapp-textrepo-angularcli-express) and I would like to also implement virtual scrolling with server-side pagination.
What's the status of your work? Will it work for my use case?
Infinite scrolling will have to be mainly in the opposite direction (we pre-load the most recent messages while the older ones will be on the top).
But in general the user will have two different infinite scrolling directions: up for older messages and down for newer ones (in fact we want to open each chat exactly at the first unread message, not down to the latest one).

**Comment by mmalerba** [comment]
@darkbasic I believe it should work for your use case. You can follow the progress here: https://github.com/angular/material2/projects/20

I'm planning to merge it into master under cdk-experimental soon.

**Comment by darkbasic** [comment]
Thanks. Do you have an usage example to share?

**Comment by mmalerba** [comment]
I added some examples to the demo app on the branch I'm developing on: https://github.com/angular/material2/tree/virtual-scroll/src/demo-app/virtual-scroll

**Comment by darkbasic** [comment]
I didn't understand one thing from the previous examples: how do I notify the backend that I need to fetch more pages when the scroller approaches the end?

Also, can I scroll to the top instead of to the bottom?

**Comment by mmalerba** [comment]
@darkbasic similar to how `mat-table` works, you would create a `DataSource` subclass and in the `connect` method you would subscribe to the `CollectionViewer` and fetch more data when the `CollectionViewer` says that the current view is close to the end

**Comment by cyberbeast** [comment]
@mmalerba Just wondering, is/are there any instructions/documentation/tutorial of some sort that I can refer to for this? I am trying to mirror the demo app, but since the demo app does not import from an npm version of cdk/cdk-experimental I don't believe the exports are the same. :)

**Comment by mmalerba** [comment]
You can take a look at the docs here: https://beta-angular-material-io.firebaseapp.com/cdk/scrolling/overview

**Comment by cyberbeast** [comment]
@mmalerba Thank you so much for sharing this. Really appreciate it :)

**Comment by cyberbeast** [comment]
@mmalerba The stackblitz demo for the virtual scroll demo at the link you shared with me the other day seems to throw an error, but it looks more like a warning that can be suppressed. Thought I'd make you aware of that.
