### ISSUE TITLE
Slide-toggle is not working

### ISSUE THREAD

**Issue by ashokacharya** [angular/material2#1013]
#### Bug, feature request, or proposal:
This is the error showing on console of browser (google chrome latest)
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./MdSlideToggle class MdSlideToggle - inline template:0:783
ORIGINAL EXCEPTION: Hammer.js is not loaded, can not bind slidestart event
ORIGINAL STACKTRACE:
Error: Hammer.js is not loaded, can not bind slidestart event
    at new BaseException$1 

#### What is the expected behavior?
Hammer.js should be automatically loaded

#### What is the current behavior?
hammer.js is not loading so slide-toggle is not working

#### What are the steps to reproduce?

All package of angular material are working except this
I have use in this way .
 <md-slide-toggle  [color]="'primary'" ></md-slide-toggle>

#### Which versions of Angular, Material, OS, browsers are affected?
angular version :RC 5
angular material :+1:  2.0.0-alpha.7-2

#### Is there anything else we should know?
Also buttons are increasing on scroll height on click

**Comment by m0t0r** [comment]
@ashokacharya did you do [additional setup for md-slide-toggle](https://github.com/angular/material2/blob/master/GETTING_STARTED.md#additional-setup-for-md-slide-toggle-and-md-slider) ?

**Comment by ashokacharya** [comment]
Thank you for info

**Comment by lizardd** [comment]
how to deal it，I still can not work

**Comment by vapits** [comment]
@lizardd go to your main component and `import 'hammerjs'`.
This solved it for me.
Check also here: #977

**Comment by lizardd** [comment]
very thank you。 @vapits

**Comment by NaijaProgrammer** [comment]
@vapits, thank you so much. That did it for me; and I've been searching for answers for weeks.

**Comment by mahmoudmahdi24** [comment]
import 'hammerjs' in my main main component solved the problem for me too.
Thanks @vapits !

**Comment by gkernen** [comment]
THANKS! @vapits !!!

**Comment by kuncevic** [comment]
I thing `polyfills.ts` is the right place to place `polyfills.ts`

**Comment by Rajasree37** [comment]
checkbox is appearing along with slider toggel.and css also not applying.


![ngmaterialui](https://user-images.githubusercontent.com/29772419/27681470-0429eb96-5cdd-11e7-9b36-628f4aa421f4.PNG)

**Comment by felipedamiani** [comment]
> checkbox is appearing along with slider toggel.and css also not applying.For this I followed https://github.com/angular/material2/blob/master/guides/getting-started.md
> see the Image this is the problem.
> ![ngmaterialui](https://user-images.githubusercontent.com/29772419/27681470-0429eb96-5cdd-11e7-9b36-628f4aa421f4.PNG)
> 
> Thanks In advance
> Rajasree

I had the same issue, to fix that just add the follow import in your style.css/scss:
`@import "../node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css";`
