### ISSUE TITLE
Reactive forms within a tab

### ISSUE THREAD

**Issue by Swoox** [angular/material2#10155]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The animationDone will be fired when the tab is done with switching.
![image](https://user-images.githubusercontent.com/22318636/36675289-cf16706a-1b08-11e8-8d4d-bc94a49e570c.png)

#### What is the current behavior?
When hit enter I switch to the next tab. On the next tab it select the first form of my reactive form category (from the form array). If the from field has a dropdown panel, the panel shown on a different position. 
I tried to fix this with "animationDone". This seems to be triggered before the selectedTabChange, where I set the index. So I can never switch to my other category (array).
![image](https://user-images.githubusercontent.com/22318636/36675194-a0618a70-1b08-11e8-920b-59b8237e8f17.png)

I now fixed it with with a timeout of 200 ms. But this is not a wanted behaviour.

#### What are the steps to reproduce?
https://angular-zb8nct.stackblitz.io
```
private tabChanged(_index: any) {
  this.selectedTab = _index;
  // do something to focus the form field with a dropdown or autocomplete.
  document.getElementById(this.form.controls['array']['controls'][_index]['controls']['array']['controls'][0]['controls']['fieldID']['value']).focus();
}
```

#### What is the use-case or motivation for changing an existing behavior?
I would like the **animationDone** to be triggered when the **animation** is really **done**. And I would like it to be **triggered after** the **selectedTabChange**

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "^5.1.1"
 "@angular/core": "^5.0.5"
"typescript": "~2.4.2"

**Comment by tinayuangao** [comment]
@Swoox Could you please provide a StackBlitz reproduction? 

starter: https://goo.gl/wwnhMV

**Comment by Swoox** [comment]
Gave a working reproduction. Took me some time.

**Comment by Swoox** [comment]
I made a reproduction you can see the beaviour but not sure why the dropdown not align under the matinput.. 
https://angular-zb8nct.stackblitz.io/

**Comment by Swoox** [comment]
Hmm upgrade materials and it works good now.

**Comment by Swoox** [comment]
I gues I spoke to soon. I check all my forms and with some forms it's to early.
![image](https://user-images.githubusercontent.com/22318636/36851556-c462a9dc-1d69-11e8-9207-81f3a21289ac.png)

Then in console the element is available.
![image](https://user-images.githubusercontent.com/22318636/36851440-7f2d05a6-1d69-11e8-9ea6-744b10d998ec.png)
