### ISSUE TITLE
sort mat table by dd/mm/yyyy date format

### ISSUE THREAD

**Issue by dufrain** [angular/material2#10150]
#### Bug, feature request, or proposal:
Sorts mat-table the date in dd/mm/yyyy format as a string

#### What is the expected behavior?
Sort mat-table by the date in dd/mm/yyyy format as a date

#### What is the current behavior?
Sorts mat-table by the date in dd/mm/yyyy format as a string

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 5.2.6, Material 5.2.2, Windows 7, Typescript 2.7.2, Chrome

**Comment by willshowell** [comment]
Assuming you are using `MatTableDataSource` (please link a reproduction in your issue reports), 
 you should provide a custom `sortingDataAccessor` that parses the date format into either milliseconds since Epoch or ISO-8601 string.

**Comment by jelbourn** [comment]
What @willshowell said.

**Comment by cdskill** [comment]
@dufrain did you find a solution ? because I've the same issue ... although I parse my data with momentjs... with DD/MM/YYYY...
