### ISSUE TITLE
mat-tooltip i18n

### ISSUE THREAD

**Issue by zverbeta** [angular/material2#10165]
#### Bug, feature request, or proposal:
feature

#### What is the expected behavior?
MatTooltip should be able to show title from title attribute

#### What is the current behavior?
Only specify your own value

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
To need for i18n

**Comment by msc117** [comment]
Having the `title` attribute set will cause the browser tooltip to be shown. Passing a translated string should be handled by you.
You can do something like this
```
<span class="cdk-visually-hidden" #translatedTooltipMessage i18n="@@myTranslation">Will be translated</span>
...
<button [matTooltip]="translatedTooltipMessage.innerHTML">I have a translated tooltip</button>
```

**Comment by zverbeta** [comment]
@msc117 Wow, it's a nice trick, but will be a cool having this method inside directive.

**Comment by msc117** [comment]
I haven't tried something like this before, but would this work?
```html
<button i18n-matTooltip matTooltip="To be translated"></button>
```

**Comment by zverbeta** [comment]
Maybe i trying wrong, but string above doesn't work

**Comment by andrewseguin** [comment]
Closing since we don't want to overload the `title` attribute and change default behavior of it

**Comment by jeandera** [comment]
it works ..
<button         i18n-matTooltip="@@MY_MESS_ID"
                      matTooltip="The Tooltip Message to display"></button>
