### ISSUE TITLE
[Table] Negative numbers not sorted correctly

### ISSUE THREAD

**Issue by rscottfree** [angular/material2#10162]
#### Bug, feature request, or proposal:
A number field, if it's negative, gets sorted after 0 when sorting ascending.

#### What is the expected behavior?
Negative numbers come before 0 when sorting ascending.

#### What is the current behavior?
When sorting ascending, negative numbers come after 0 and before positive numbers.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-yfw5ia-uaqsrh?file=app%2Ftable-sorting-example.ts
Click on the weight column header one time to sort ascending.

#### What is the use-case or motivation for changing an existing behavior?
It makes sense that -1 < 0 < 1 and I think the default sort comparison should follow that rule.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.2.2

#### Anything else
This is using the default sort with MatSort on a MatTable using MatTableDataSource.

**Comment by aleksanderhan** [comment]
I also have this problem. Any fixes?

**Comment by rscottfree** [comment]
@aleksanderhan A workaround is to use `MatTableDataSource.sortData` to override the sort mechanism.

**Comment by andrewseguin** [comment]
Should be fixed in https://github.com/angular/material2/pull/10561
