### ISSUE TITLE
mat-expansion -  fix 9134 overwrites this fix 9313

### ISSUE THREAD

**Issue by iprins** [angular/material2#10169]
This fix [9134](https://github.com/angular/material2/pull/9134) overwrites this fix [9313](https://github.com/angular/material2/pull/9313)

Fix 9313 should not be overwritten
Fix 9313 is not working anymore

Affected version: 
Material 5.2.2

**Comment by josephperrott** [comment]
Closing as #9313 was reverted intentionally by #9580
