### ISSUE TITLE
mat-expansion-panel slight slight vertical offset of the title, the description and the icon

### ISSUE THREAD

**Issue by psalom** [angular/material2#10168]
#### Bug, feature request, or proposal:
slight vertical offset of the title, the description and the icon between expand and collapse mode.

#### What is the expected behavior?
You must have no offset between expanding and collapsing

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
The animation attract user attention on the changes for bad reasons

#### Is there anything else we should know?
Thx a lot

**Comment by tinayuangao** [comment]
@psalom Could you please provide a SdtackBlitz reproduction, or a screenshot? Thanks

**Comment by psalom** [comment]
![expansionoffsetissue](https://user-images.githubusercontent.com/20325703/36776151-112a0cd4-1c65-11e8-9d88-96b54eb1ee15.png)

Please find a screenshot to see the offset (same issue with cursor)

Thx

**Comment by josephperrott** [comment]
Closing as this occurs based on the [Expansion Panel definition of the Material Spec](https://material.io/guidelines/components/expansion-panels.html#expansion-panels-specs).  The size of the text does not change, however the height of the header for an expanded panel moves from `48px` to `64px`.

You should be able to prevent this change in height by setting the `collapsedHeight` and/or `expandedHeight` inputs on the `mat-expansion-panel-header`
