### ISSUE TITLE
bug[matPrefix]: mat-icon as prefix not aligned

### ISSUE THREAD

**Issue by merlosy** [angular/material2#10172]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-icon and placeholder should be on the same line when field is empty

#### What is the current behavior?
mat-icon element is too high, support mat-icon with matPrefix directive?

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/angular-macdjt?file=app/input-prefix-suffix-example.html

#### What is the use-case or motivation for changing an existing behavior?
consistency

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.2.1, 
Angular 5.2.5
OS: windows 10
Chrome

#### Is there anything else we should know?
thanks

**Comment by donroyco** [comment]
Have you checked this issue while using `6.0.0.`? See @mmalerba's [comment](https://github.com/angular/material2/issues/10093#issuecomment-367874851) in #10093

**Comment by mmalerba** [comment]
Yep, I think the spec seems to be moving toward icons that are centered in the input/label box. I believe this is for consistency with the newer outline and fill appearances.

These two images from the spec illustrate what I'm talking about:
![underline style datepicker](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B5ZSepuCX1xOX3RQUEJ6ajVMb1E/picker.png)
![fill style datepicker](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B5ZSepuCX1xORGJSaXhsX1c5Y0k/discoverable-picker.png)

Notice how in both versions the datepicker dropdown arrow is centered. Also notice that the calendar icon actually lives outside the form field and is aligned with the text for the underline style, but centered with the fill style. So as far as I can tell the spec is suggesting to put the icon outside the form-field if you want to align it like that.

Of course this is all just our default styling, you can also add CSS to align your prefix / suffix icons with the text if you like.

**Comment by merlosy** [comment]
@donroyco thnaks for the link, i didn't see that one.
IMO, there is still something that doesn't feel right about the style of this element.

The new [layout for text fields](https://material.io/guidelines/components/text-fields.html#text-fields-layout) seems better, but when is it planned for?

**Comment by mmalerba** [comment]
The new styles are available in the 6.0.0 betas. The feature isn't documented yet, but you just need to set the `appearance` input on the form-field

**Comment by KayHS** [comment]
This is still an issue in version 6
