### ISSUE TITLE
feature request? expansion panels: remove inline styles that resize header panels

### ISSUE THREAD

**Issue by adventmedia** [angular/material2#10173]
This is a feature request as the behaviour request is clearly intentional.

For Expansion Panels (used for an accordion) the mat-expansion-panel-header is set with inline styles through scripting for closed and open states (48px for closed, 64px for open).

It's not evident that this is necessary - allowing the panel to expand to accommodate content seems to work (if the inline styles are disabled), and it's a real restriction esp. for responsive design when going to mobile (smartphone) view. I would like to suggest that: 

1. If possible the inline styling be removed altogether (and the height of the panel header set to 100%)
2. Otherwise provide means for changing these values, either through options or by applying styles dynamically (e.g. panel-open vs panel-closed) instead of inline styles

**Comment by josephperrott** [comment]
Closing as this is working as expected/intended.  You can control the size of the `mat-panel-header`  through the [`expandedHeight` and `collapsedHeight` inputs](https://github.com/angular/material2/blob/master/src/lib/expansion/expansion-panel-header.ts#L88).

**Comment by odahcam** [comment]
@josephperrott isn't there an auto-height option?
