### ISSUE TITLE
Bug[MatDialog]: disableClose=false not working with hasBackdrop=false

### ISSUE THREAD

**Issue by th3n3wguy** [angular/material2#10174]
#### Bug, feature request, or proposal:
- Bug

#### What is the expected behavior?
- The `disableClose` property, when set to `false`, should allow the user to click outside of the modal to close it whenever the `hasBackdrop` property is also set to `false`.

#### What is the current behavior?
- If both the `disableClose` and `hasBackdrop` properties are set to `false`, the user should still be able to click outside of the modal to close it.

#### What are the steps to reproduce?
- Demo => [https://angular-macdjt-y1ebqh.stackblitz.io](https://angular-macdjt-y1ebqh.stackblitz.io)
- Code for Demo => [https://stackblitz.com/edit/angular-macdjt-y1ebqh](https://stackblitz.com/edit/angular-macdjt-y1ebqh)

#### What is the use-case or motivation for changing an existing behavior?
- N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Angular => 5
- Material => 5.2.2 & 5.2.3
- OS => Windows 10
- TypeScript => 2.4.x
- Browser(s) => Chrome (Version 64.0.3282.167 (Official Build) (64-bit))

**Comment by julianobrasil** [comment]
I'm not sure, but I think in this case, the backdrop is used to detect a click on the outside of the dialog. So, if you disable the backdrop, you cannot expect it to close with outside clicks. It works with ESC though.

**Comment by th3n3wguy** [comment]
@julianobrasil => I just realized that it does, in fact, work with the ESC key, but clicking out does not and it is stated in the documentation that it should. I will update my issue notes now.

I am okay with the fact that these two properties might not work together (probably because they are binding the click even to the backdrop / overlay), but then the documentation should be updated to reflect that functionality.

**Comment by crisbeto** [comment]
The backdrop is used to handle the clicks outside the dialog. When you set `hasBackdrop` to false, the element won't be rendered at all. If you don't want the darkened backdrop, but still want clicking outside to work, you can set the `backdropClass` to `cdk-overlay-transparent-backdrop`.

**Comment by th3n3wguy** [comment]
@crisbeto => I updated the Stackblitz based on your suggestion and it still doesn't fix the issue of clicking outside the dialog. Do you have any other suggestions?

**Comment by crisbeto** [comment]
It seems to work here: https://stackblitz.com/edit/angular-macdjt-cfkdpg

**Comment by th3n3wguy** [comment]
@crisbeto => .............I...am not sure what the heck I did wrong there.

Thank you for the provided workaround, but I do still believe that this should be done automatically by the library, rather than having to remember to do this by setting another property. What do you think @crisbeto?

**Comment by crisbeto** [comment]
I'd say that the config options are explicit enough. I don't think that we can handle this automatically without making some assumptions which could break existing usages.
