### ISSUE TITLE
flex attribute is not supported in material2 alpha7.2 version

### ISSUE THREAD

**Issue by Muthu2020** [angular/material2#1017]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by DevVersion** [comment]
The issue template is not fulfilled, but from the title, I'm assuming you are trying to use the Angular Material 1.x Flexbox layout.

```html
<div flex=""
```

If so, this is currently not even available in Material 2 and will be tracked with #45

**Comment by jelbourn** [comment]
Closing into #75

**Comment by jelbourn** [comment]
Whoops, meant #45
