### ISSUE TITLE
mat-select doesn't inherit the color from parent  

### ISSUE THREAD

**Issue by lokeshdaiya** [angular/material2#10184]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-select doesn't inherit the color from parent. It should inherit from the parent as other components are inheriting as shown in attached pic and stackblitz.

#### What is the current behavior?
If we put mat-select in mat-toolbar and provide color to mat-toolbar then mat-select does not change its color.
You can see color difference between other components and mat select

![mat-select](https://user-images.githubusercontent.com/7831299/36770979-90e23524-1c73-11e8-9d45-99cd18dfdc4d.PNG)

#### What are the steps to reproduce?
Have a look on this 
https://stackblitz.com/edit/angular-3anjwe

#### What is the use-case or motivation for changing an existing behavior?
Better use interface and accessibility.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material  >=5.1
OS: Windows 7
Angular >=5.1
BrowserL Chrome

#### Is there anything else we should know?

If line https://github.com/angular/material2/blob/master/src/lib/select/_select-theme.scss#L18

modified as below then it works

```
.mat-select-value {
      color: currentColor;
    }
```

**Comment by crisbeto** [comment]
We can't do this, because it can end up breaking people in a lot of subtle ways. Closing since it's trivial to work around.

**Comment by lokeshdaiya** [comment]
Then how you gonna handle this issue if you see from the accessibility point of view mat select text should be visible properly?

**Comment by crisbeto** [comment]
You can handle it on your end by setting the color explicitly the same way as your example, but we can't do it automatically through Material without breaking a lot of people making it hard to maintain.
