### ISSUE TITLE
MatSort tables have broken sort icons in non-active tabs

### ISSUE THREAD

**Issue by rfuhrer** [angular/material2#10182]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Sort icons should be invisible until you mouse over or select a column

#### What is the current behavior?
It works fine on the current tab, however any non-active tabs will have this broken "T" shape on each column until you mouse over

#### What are the steps to reproduce?
Click Tab 2:
https://stackblitz.com/edit/angular-19yihc

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 1.7.1
Node: 9.5.0
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.2.3
@angular/cli: 1.7.1
@angular/flex-layout: 5.0.0-beta.13
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0
```

**Comment by julianobrasil** [comment]
The new `<ng-template matTabContent></ng-template>` surrounding `<mat-tab>` content solve it.

Demo: https://stackblitz.com/edit/angular-19yihc-xbntvx

**Comment by rfuhrer** [comment]
Interesting. I thought I've been keeping up on everything in https://github.com/angular/material2/blob/master/CHANGELOG.md but I guess I missed the ng-template stuff.  Can you point me in the direction of where you learned that?

**Comment by julianobrasil** [comment]
It's been around since 6.0.0-beta.0 (not so long). You can read about it at https://github.com/angular/material2/blob/master/src/lib/tabs/tabs.md

**Comment by rfuhrer** [comment]
Awesome, thanks!  I've been ignoring the 6.0.0 changelog since I'm still on version 5 so I must have missed this.

**Comment by ChristophWieske** [comment]
Is there a workaround for @angular/material@5.x (I´m on 5.2.5)

I don´t really want to switch major version unplannend within the development of a new increment.
