### ISSUE TITLE
Error on prebuilt themes

### ISSUE THREAD

**Issue by qmarquez** [angular/material2#10189]
#### Bug, feature request, or proposal:
All deeppurple, indigo, pink an purple themes are the same theme

#### What is the expected behavior?
that all themes are distincts

#### What is the current behavior?
are all the same

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
a

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

#### Is there anything else we should know?
nop

**Comment by jelbourn** [comment]
They seem to be different:
https://unpkg.com/@angular/material@5.2.3/prebuilt-themes/indigo-pink.css
https://unpkg.com/@angular/material@5.2.3/prebuilt-themes/deeppurple-amber.css
https://unpkg.com/@angular/material@5.2.3/prebuilt-themes/pink-bluegrey.css
https://unpkg.com/@angular/material@5.2.3/prebuilt-themes/purple-green.css

Feel free to open a new issue if you can point to a specific problem.
