### ISSUE TITLE
mat-list-option does not select mat-list-avatar

### ISSUE THREAD

**Issue by Barbiero** [angular/material2#10192]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When adding a `matListAvatar` image to a `mat-list-option`, the image should be positioned to the left of the option in same way as it does with `mat-list-item`

#### What is the current behavior?
`matListAvatar` is ignored altogether.

#### What are the steps to reproduce?
This stackblitz illustrates what I mean:
https://stackblitz.com/edit/angular-material2-issue-cgszmk

#### What is the use-case or motivation for changing an existing behavior?
Having lists with selection boxes and avatars. My use-case, specifically, is a "quiz"-type system; Other would be selecting users for sharing content, for instance.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.6 Material 5.2.3

**Comment by Alberz** [comment]
> 

> 

> [sefsd](url)
