### ISSUE TITLE
'value' > 100 not work for 'bufferValue' for 'progress-bar'

### ISSUE THREAD

**Issue by muxi2015** [angular/material2#10197]
#### Bug, feature request, or proposal:

Bug  Or feature request ?

#### What is the expected behavior?

Automatic generation of percentages based on value and bufferValue

#### What is the current behavior?

must set the `value` to 100 to work properly

#### What are the steps to reproduce?

set `value` > 100

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/material": "^5.2.0"
"@angular/core": "^5.2.0"
"typescript": "~2.5.3"
Mac OS 10.13

### My solution
see [88-96 line](https://github.com/muxi2015/music-md-angular/blob/master/src/app/services/Player.service.ts)

[4-9line](https://github.com/muxi2015/music-md-angular/blob/master/src/app/core/player/player.component.html)

**Comment by crisbeto** [comment]
I'm not sure I understand the issue. Can you elaborate?

**Comment by muxi2015** [comment]
@crisbeto Please close issues,I'm very sorry because I used translation
