### ISSUE TITLE
Example about mat-optgroup inside mat-autocomplete

### ISSUE THREAD

**Issue by WizardPC** [angular/material2#10196]
#### Bug, feature request, or proposal:

Documentation request

#### What is the expected behavior?

Having an working example of this code :
 [https://material.angular.io/components/autocomplete/overview#option-groups](https://material.angular.io/components/autocomplete/overview#option-groups)

#### What is the current behavior?

No stackblitz or demo. And it's not easy to understand... because for the "mat-optgroup" you need (implicitly ?) to go to the "Select" component section, and with a group structure (eg: pokemonGroups) the autocomplete filter (eg: filteredOptions: Observable<string[]>;) doesn't work anymore.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-nwdj9u

#### What is the use-case or motivation for changing an existing behavior?

Having a autocomplete input with group.

Like this for example 

Input : "d" <---------- autocomplete 
[**D** <------------------- group
     Dog <------------- option1
     Dragon <---------- option2
     ...
]

**Comment by WizardPC** [comment]
Thanks @jelbourn for the tags.

Indeed the "help wanted" is welcome, because i can't actually find myself how to adapt the Observable type to work with a group...

If someone know how to do it, I will really appreciate !!

**Comment by WizardPC** [comment]
Comment updated with a stackblitz demo.

**Comment by WizardPC** [comment]
No one ? No more luck on stackoverflow... :zipper_mouth_face:

**Comment by raygervais** [comment]
I'd like to take a crack at this if @mmalerba thinks it's a feature worth adding 👍

**Comment by mmalerba** [comment]
@raygervais sounds good to me. @crisbeto should probably be the one to review it, I'm not too familiar with the autocomplete

**Comment by raygervais** [comment]
@WizardPC, I forked and completed your `mat-optgroup` example. Can be found here: https://stackblitz.com/edit/angular-smg2xm?file=app/app.component.ts, from there I'm updating the documentation to reflect (based on the original example which is there). @crisbeto is this how the autocomplete function should behave? or should it filter as well the options so that if I put `Dr` from the example above, `Dog` would be removed from the panel?

**Comment by crisbeto** [comment]
I'd say that it should only filter the options @raygervais, the groups are only used for grouping similar results together. Here's an example from our demo app that does the same: https://github.com/angular/material2/blob/master/src/demo-app/autocomplete/autocomplete-demo.ts#L131

**Comment by raygervais** [comment]
Thanks for the pointer @crisbeto, will correct in my StackBlitz update and from there work on the PR.

**Comment by WizardPC** [comment]
@raygervais thanks for your time ! Works as expected ;)

**Comment by WizardPC** [comment]
Thanks @raygervais :wink:

**Comment by meyer20** [comment]
Hi @raygervais 

Is possible to do something like this: https://i.stack.imgur.com/tvAp5.png using the autocomplete, i say, multiple colums in a line.

Thanks
