### ISSUE TITLE
(mat-table) + mat-tab = ugly sort arrow in second tab

### ISSUE THREAD

**Issue by TishchenkoAlex** [angular/material2#10193]
https://stackblitz.com/edit/angular-k7ujry
![image](https://user-images.githubusercontent.com/22451433/36794419-f44c64ce-1ca8-11e8-8c95-bce993a7f3c4.png)

**Comment by donroyco** [comment]
Please use [the issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md) to prevent your issue getting closed.

**Comment by andrewseguin** [comment]
Dupe of #7291
