### ISSUE TITLE
Decouple backdrop click and ESC press on mat-dialog

### ISSUE THREAD

**Issue by salemdar** [angular/material2#10190]
#### Feature request:

Both <kbd>ESC</kbd> and **backdrop click** closes an active dialog. This can be disabled at the moment, but only all together. These two behaviours should be decoupled.

#### What is the expected behavior?

`MatDialogConfig` should have 2 extra properties:
```typescript
// ...
disableCloseOnEscape: boolean,
disableCloseOnBackdropClick: boolean
```

#### What is the use-case or motivation for changing an existing behavior?

So we can disable closing on backdrop click, but keep close on <kbd>ESC</kbd> press. It would be very helpful for inaccurate mouse users :).

**Comment by willshowell** [comment]
The suggested approach for this is to set `disableClose` and then use `keydownEvents` or `backdropClick` to re-enable the desired behavior.

See https://github.com/angular/material2/pull/3460 and linked threads for more context.

**Comment by salemdar** [comment]
@willshowell thanks for your comment. I am aware that there are possible workarounds. For example, I wrote something like this:

```typescript
const dialogRef = this.dialog.open(MyDialogComponent, {
  disableClose: true
});
dialogRef.keydownEvents()
  .filter((e: KeyboardEvent) => e.code === 'Escape')
  .take(1)
  .subscribe((e: KeyboardEvent) => {
    dialogRef.close();
  });
```

But wouldn't it be a nice to have it out of box? I believe it could be useful for many people.

**Comment by willshowell** [comment]
@salemdar the team (at least in the past) has held pretty strong to this. See https://github.com/angular/material2/pull/3460#issuecomment-319420262 for a better explanation than I can give.

**Comment by jelbourn** [comment]
Yep, as per Will's comment, we don't really want to decouple these behaviors.
