### ISSUE TITLE
Mat Sidenav RTL Scrollbar padding

### ISSUE THREAD

**Issue by AmirTugi** [angular/material2#10199]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Scrollbar addition should not interfere with content width/ should be handled in Chrome (Windows)

#### What is the current behavior?
A scrollbar addition is pushing some content beyond its original container, rendering the content partially cut.

#### What are the steps to reproduce?
Watch how the 'Placeholder' of the input field is cropped
https://stackblitz.com/edit/angular-material2-issue-gyia8v

#### What is the use-case or motivation for changing an existing behavior?
Obviously the scrollbar should not break the flow of the page, and of course, since it works seamlessly in Firefox (windows) and Chrome (MacOS), I don't understand why it won't work on Chrome (Windows)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 5.2.6
TypeScript - 2.5.3
Angular CLI - 1.7.1
Material - 5.2.2
Chrome Version 64.0.3282.186 (Official Build) (64-bit) - Windows

**Comment by AmirTugi** [comment]
I have figured that this is caused because of the `z-index` of the `mat-sidenav-content`.
So a workaround could be to just remove this.

However, there was a reason I guess for the existence of the `z-index`, and it causes troubles with RTLing.
Hope you'll find a fix for this without disabling the z.

**Comment by crisbeto** [comment]
The `backface-visibility` has been removed in https://github.com/angular/material2/pull/10026.
