### ISSUE TITLE
[Feature Request] Slide-Toggle Interface Change

### ISSUE THREAD

**Issue by Daeluse** [angular/material2#1019]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
As they were in Release 6, labels of slide-toggles should be clickable to instantly toggle the switch.

Alternatively, this could be done by specifying which type of slide toggle you would like, whether it should be draggable or clickable.

#### What is the current behavior?
All slide-toggles require the seeker to be dragged towards the desired setting.

#### What is the use-case or motivation for changing an existing behavior?
On Desktop applications, it seems tedious to have to find the thumb with a cursor and then drag it to change. While on mobile this feature is desired, on desktop forms which have multiple switches this becomes a bit cumbersome to the user.

#### Which versions of Angular, Material, OS, browsers are affected?
Material Design Release 7

**Comment by Daeluse** [comment]
This was actually an issue with local styles making an aspect of the toggle hidden.

Sorry for the noise.

**Comment by DevVersion** [comment]
@Daeluse Thanks for the update, I was wondering how I could miss that bug.

Since this issue is not valid, you could close it :)
