### ISSUE TITLE
[website] Navigation from component doc to CDK category page doesn't work properly

### ISSUE THREAD

**Issue by takamori** [angular/material2#10202]
#### Bug, feature request, or proposal:
The Material website's header navigation doesn't work to go from component to CDK.

If one starts at a component page such as  https://material.angular.io/components/autocomplete/overview
and clicks on "CDK" at the top of the page, the UI seems stuck on https://material.angular.io/components/categories unless the user reloads the page.

#### What is the expected behavior?
The page should go to https://material.angular.io/cdk/categories 

#### What is the current behavior?
It keeps redirecting from https://material.angular.io/cdk to https://material.angular.io/components/categories

If the page is reloaded while viewing https://material.angular.io/components/categories then it will redirect properly.

#### What are the steps to reproduce?
1) Load https://material.angular.io/components/autocomplete/overview
2) click on "CDK" in the header at the top of the page.

#### What is the use-case or motivation for changing an existing behavior?
To make the website navigate properly.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
At least Chrome 64, altho I suspect all browsers are affected.

**Comment by mtrdp642** [comment]
See [angular/material.angular.io#327](https://github.com/angular/material.angular.io/issues/327)

**Comment by takamori** [comment]
Thanks, subscribed to that.
