### ISSUE TITLE
ng build error: Cannot find name 'HammerManager'

### ISSUE THREAD

**Issue by RedFour** [angular/material2#1020]
#### Bug, feature request, or proposal:

ERROR in [default] c:\test-app\node_modules\@angular2-material\core\gestures\MdGestureConfig.d.ts:4:39
ng build error: Cannot find name 'HammerManager'

#### What are the steps to reproduce?

1. create new project using angular-cli@webpack
2. npm install latest material components
3. modify app.module.ts:

`import { MdCoreModule } from '@angular2-material/core';

@NgModule({
  declarations: [
        AppComponent
  ],
  imports: [
    // Angular 2
    BrowserModule,
    CommonModule,
    FormsModule,
    HttpModule,
    // Material Design
    MdCoreModule,
  ],
  providers: [],
  entryComponents: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule {
}`

  4 ng build

#### Which versions of Angular, Material, OS, browsers are affected?
angular rc5, material 7.2, angular-cli@webpack

**Comment by m0t0r** [comment]
@RedFour I am not sure you should actually load `MdCoreModule ` module, check [getting started](https://github.com/angular/material2/blob/master/GETTING_STARTED.md) on how to load [modules of a specific components](https://github.com/angular/material2/blob/master/GETTING_STARTED.md#import-and-use-the-components). If you want to use `md-slide-toggle` or `md-slider` you need to make sure you are loading HammerJS as it's described [here].(https://github.com/angular/material2/blob/master/GETTING_STARTED.md#additional-setup-for-md-slide-toggle-and-md-slider)

**Comment by jkyoutsey** [comment]
I find that, with hammerjs@2.0.8, I get the following error (with multiple components)
```
EXCEPTION: Error in ./MdSlideToggle class MdSlideToggle - inline template:0:783
ORIGINAL EXCEPTION: Hammer.js is not loaded, can not bind slidestart event
```

**Comment by RedFour** [comment]
@m0t0r you are right I don't need to import MdCoreModule. Thank you!
