### ISSUE TITLE
Empty form field placeholder text not properly aligned vertically

### ISSUE THREAD

**Issue by gtranter** [angular/material2#10203]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
As per the Material design guidelines (https://material.io/guidelines/components/text-fields.html#text-fields-text-field-boxes under the section "States" the Idle & Empty or Hover specs), the placeholder text should be vertically centered in the field area (just like prefix and suffix icons) when the field is empty and the placeholder is not floating.

#### What is the current behavior?
The placeholder text in an empty field is vertically aligned at the same position as input text.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-hlm3xm

#### What is the use-case or motivation for changing an existing behavior?
Doesn't look good and doesn't meet specifications.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.0-beta.5, Angular Material 6.0.0-beta.3.

**Comment by mmalerba** [comment]
The image you liked to is the filled style form-field, you need to add `appearance="fill"` to get this. Also the placeholder and label are different things now. The label is the one that should be center aligned. You add it by specifying a `<mat-label>`: https://stackblitz.com/edit/angular-hlm3xm-av8mxs?file=app/form-field-prefix-suffix-example.html
