### ISSUE TITLE
Paginator content is empty when datasource.data is refreshed with a smaller set

### ISSUE THREAD

**Issue by skonx** [angular/material2#10227]
#### Bug, feature request, or proposal:
The paginator content is empty when the datasource.data is updated with a smaller set.

Let's take an exemple...
We have 50 elements, pageIndex is 0 and pageSize is 5 and length is 50 (as expected).
If you change the pageSize to 10 and want to see the range 20-30, no problem.
But if the datasource.data is updated with a smaller set (with a smaller length I mean for exemple only 6 elements) than the range, the pageSize is not changed (as expected), the displayed pageIndex is changed (as expected) but the pageIndex in MatPaginator is preserved and the length is also changed (as expected).

I've tried to fix the pageIndex to 0, as recommanded by @andrewseguin in #5812 before and after the datasource.data update but it doesn't work.
```
@ViewChild(MatPaginator) paginator: MatPaginator;
this.paginator.pageIndex = 0;
```

The only way to display the Paginator content is to select a new pageSize value...

#### What is the expected behavior?
Paginator should be refreshed and moved to the first page

#### What is the current behavior?
Paginator content is cleared

**Comment by skonx** [comment]
I've checked and datasource.data is updated as expected. It's not an issue or a mistake with a datasource set with an empty list ;)

**Comment by julianobrasil** [comment]
Even knowing this is referring to another issue... could you provide a minimum working stackblitz demo reproducing the described behavior? It helps the investigation process and gives a better understanding of your point.

**Comment by skonx** [comment]
Hi @julianobrasil, I've solved it fixing this.paginator.pageIndex = 0; at the first start of ngChanges().
Is it a requirement to move the index before setting a new datasource.data ? 
Setting the index after the update of datasource.data seems to have no effect.

**Comment by julianobrasil** [comment]
I'd have to take a look at the code to help you. Maybe @andrewseguin can answer your question properly.

**Comment by andrewseguin** [comment]
Feel free to post a stackblitz example of what you are experiencing and we can dive into it to see the optimal path to solve it
