### ISSUE TITLE
include mat-prefix in width of mat-input for the purposes of mat-autocomplete

### ISSUE THREAD

**Issue by heppe** [angular/material2#10225]
#### Bug, feature request, or proposal:

I don't know if the solution is to make autocomplete look at the form, or if there should be some other way of integrating the prefix icon into the mat-input

#### What is the expected behavior?

autocomplete should match the full width with prefix

#### What is the current behavior?

autocomplete matches only the width of the input

#### What are the steps to reproduce?

create a mat-input with mat-prefix and attach a mat-autocomplete to it.

#### What is the use-case or motivation for changing an existing behavior?

search boxes with magnifying glasses to indicate what they're intended for.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I only tested with ng2, ts2.6, but I suspect that anything ng2+ would be affected.

**Comment by julianobrasil** [comment]
It seems correct to me: https://stackblitz.com/edit/angular-kch6xy

![image](https://user-images.githubusercontent.com/25405143/36873102-3acedaf2-1d86-11e8-8863-29c57ec566d7.png)
