### ISSUE TITLE
ERROR in Metadata version mismatch for module /usr/src/app/node_modules/@angular/cdk/platform/typings/index.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by MarianLaris** [angular/material2#10228]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by MarianLaris** [comment]
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/usr/src/app/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

npm info lifecycle washington-tractor-tr-webapp@0.0.1~build: Failed to exec build script
npm ERR! Linux 4.4.0-1049-aws
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! washington-tractor-tr-webapp@0.0.1 build: `ng build --prod --aot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the washington-tractor-tr-webapp@0.0.1 build script 'ng build --prod --aot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the washington-tractor-tr-webapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --prod --aot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs washington-tractor-tr-webapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls washington-tractor-tr-webapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-03-01T20_34_46_856Z-debug.log

**Comment by crisbeto** [comment]
This usually happens if you're using a newer version of Material with an older version of Angular. Please check the version requirements for your Material version.
