### ISSUE TITLE
Simulate click on elementRef doesn't update ngModel (e.g. mat-checkbox, mat-slide-toggle)

### ISSUE THREAD

**Issue by JakobSegerslatt** [angular/material2#10236]
#### Bug, feature request, or proposal:
Proposal
Simulate click on form-controls should update value. More specifically triggering the click() method on an elementRef shouldn't be different than when user clicked the element.

This might be intended but it's the only way i can get a workaround for clicking elements behind an overlay backdrop.

#### What is the expected behavior?
Calling element.click() on a mat-checkbox/mat-slider should update ngModel

#### What is the current behavior?
(click)-event is fired but not ngModel

#### What are the steps to reproduce?
See some exampels and clarification
StackBlitz: https://stackblitz.com/edit/angular-material2-issue-xfwbji

#### What is the use-case or motivation for changing an existing behavior?
Used for building TapTargetDirective (related to #8884).
Since I can't append an arbitrary element into a portal (in this case overlay), but i got the elementRef inside the directive i can trigger the click on the element, but not how it would be if the user clicked on the element manually.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.6
Material: 5.2.2
TS: 2.6.2
Chrome, 
Windows 10

**Comment by tinayuangao** [comment]
The `input` elements inside mat-checkbox/mat-slide-toggle are responsible for the click event.

Here's example to trigger input element inside the component:
https://stackblitz.com/edit/angular-material2-issue-8qmsep?file=app/click-trigger/click-trigger.component.ts

**Comment by JakobSegerslatt** [comment]
Thanks, that works as expected, as well as trigger ngModelChange event on the mat-checkbox!
