### ISSUE TITLE
[Tabs][IE 11] Content of tab doesn't wrap in IE 11

### ISSUE THREAD

**Issue by chalexIAC** [angular/material2#10237]
version is 5.2.3
You can check it on official example here:
https://material.angular.io/components/tabs/examples

**Comment by saulotoledo** [comment]
Hi @andrewseguin. I think the above PR is a solution for this problem. Let me know if I can help with that. :)

**Comment by chalexIAC** [comment]
for me this works
.mat-tab-body{
  flex: 0 0;
}
