### ISSUE TITLE
Please fix this ui issue

### ISSUE THREAD

**Issue by awesomesince96** [angular/material2#10230]
#### Bug, feature request, or proposal:
Content overlapping  at this url--> https://material.angular.io/components/sidenav/overview

#### What is the expected behavior?
It should be responsive and should not overlap regardless of  screensize

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material.angular.io/pull/395.
