### ISSUE TITLE
Sorting matCellDef using index of cdkTable in *matCellDef="let row; let i = index;"> {{i+1}}

### ISSUE THREAD

**Issue by bydavido16** [angular/material2#10241]
#### Bug, feature request, or proposal:
I'm using the next code
<ng-container matColumnDef="id" >
        <mat-header-cell fxFlex="8" *matHeaderCellDef mat-sort-header> Id </mat-header-cell>
        <mat-cell fxFlex="8" *matCellDef="let row; let i = index;"> {{i+1}} </mat-cell>
</ng-container>

but when i'm sorting, i'm using the id of the table like that.
doSorter(sorterActive:string, a:Permiso, b:Permiso):SorterCompare{
    let sorterCompare : SorterCompare = new SorterCompare('', '');
    switch (sorterActive) {
      case 'id': sorterCompare = new SorterCompare(a.id, b.id); break;      
    }
    return sorterCompare;
  }

#### What is the expected behavior?
I expect the sorting work with all the colums

#### What is the current behavior?
The table does the sorting but the column with the id doesn't

**Comment by andrewseguin** [comment]
Please re-open with a reproduction on StackBlitz so we can investigate
