### ISSUE TITLE
Paginator not rendered correctly in IE 11

### ISSUE THREAD

**Issue by wimbou** [angular/material2#10258]
#### Bug:
The paginator layout is broken on Internet Explorer 11

#### What is the expected behavior?
De paginator should be correctly aligned on one row

#### What is the current behavior?
De paginator is split on several rows

#### What are the steps to reproduce?
Visit the table examples with the paginator in IE 11 https://material.angular.io/components/table/examples

#### What is the use-case or motivation for changing an existing behavior?
Make IE 11 users have the same user experience

**Comment by donroyco** [comment]
Do you have a screenshot of the behaviour?

**Comment by wimbou** [comment]
![img_20180304_212041](https://user-images.githubusercontent.com/139106/36950172-6556af2a-1ff2-11e8-9bba-766624f0039e.jpg)

**Comment by julianobrasil** [comment]
In fact, material.angular.io layout is also broken in IE11:

![image](https://user-images.githubusercontent.com/25405143/36954532-89690908-2001-11e8-9fad-030939a1d50e.png)

But that's already being tracked in https://github.com/angular/material.angular.io/issues/391

The vertical positioning is wrong in both cases. It can be just a coincidence, but IE11 is always breaking layouts when you're counting on vertical alignment without fixing the container height. When using flex-layout with `fxLayout="column"` I always use `fxFlex="noshrink"` to avoid trouble with IE11.

**Comment by crisbeto** [comment]
Closing as fixed in https://github.com/angular/material2/pull/9776.

**Comment by karlmnz** [comment]
Why are these issues being closed when the material.angular.io site is not working?  Seem you have created cyclic ref. to other closed issues all of which haven't resolved initial issues as per original current behaviour screen shot.  I have just viewed and get the same error.  Then in my angular app getting a whole lot worse.

Surely you can't close something until the fix is actually applied.

**Comment by andrewseguin** [comment]
Our process is to close issues once the fix has been merged into the master branch, not necessarily when the release occurs or the docs site is updated with the latest version.

**Comment by mradyuk** [comment]
how to fix it paginator (material 5.2.1) for IE 11 ?
