### ISSUE TITLE
"GETTING_STARTED.md" mismatch with the angular-cli@webpack

### ISSUE THREAD

**Issue by lewgun** [angular/material2#1026]
#### Bug, feature request, or proposal:
bug
#### What is the current behavior?
there is no "angular-cli-build.js" file in a latest angular-cli new project. so please update this file to  match it . it seems the pr #1002  does not working too 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
angular:  rc5
angular-cli: 1.0.0-beta.11-webpack.2
node: 5.12.0
os: darwin x64
material: ^2.0.0-alpha.7-2

**Comment by Kosmonaft** [comment]
You can skip: **Add components to vendor bundle** and**Configure SystemJS** from "GETTING_STARTED.md"
The only thing which I noticed is not working is **Additional setup for `md-menu` and `md-tooltip`**

Angular-cli webpack is just not creating a vendor for this. I don't have any idea how to fix this

**Comment by jelbourn** [comment]
@hansl can you make sure the getting started guide is good to go for alpha.8 + RC6 + webpack cli?

**Comment by jelbourn** [comment]
AFAIK the getting started should be totally up to date with angular-cli at this point.
