### ISSUE TITLE
Multi pagination on generated datatables

### ISSUE THREAD

**Issue by cdskill** [angular/material2#10269]
#### Bug, feature request, or proposal:

Cannot apply dynamically the paginator on multiple datatables
#### What is the expected behavior?
Apply paginator on all datables

#### What is the current behavior?
Chrome crashing

#### What are the steps to reproduce?
Hi I'm litle bit stuck because I want to assign multiple paginator on multiple datatable generated...
For exemple the server send me 4 tables, each one with their pageSize and their pagination...

How can I perform that ?

I can actually generate multiple datatable but not appliying the pagination on each one.

This is how my datatable are generated (mat-paginator is not working): 

					<div *ngIf="subcategory.completed && subcategory.total > 0">
						<mat-table #table [dataSource]="castMatatableDataSource(subcategory.content.rows)">
							<ng-container *ngFor="let column of subcategory.content.columns" [matColumnDef]="column.prop">
								<mat-header-cell *matHeaderCellDef>{{column.name}}</mat-header-cell>
								<mat-cell *matCellDef="let row" [innerHtml] ="row[column.prop]">{{row[column.prop]}}</mat-cell>
							</ng-container>

							<mat-header-row *matHeaderRowDef="subcategory.content.props()"></mat-header-row>
							<mat-row *matRowDef="let row; columns: subcategory.content.props()"></mat-row>
						</mat-table>
						<mat-paginator #paginator
									[pageSize]="subcategory.content.per_page"
									[pageSizeOptions]="[subcategory.content.per_page]">
						</mat-paginator>
					</div>

I've done to many researchs and tested some things but none working. I've seen some issues with nearly the same problem than me but the solution is not for my case because they all hard code their paginator like this : 
	@ViewChildren('paginator1') paginator1: MatPaginator;
	@ViewChildren('paginator2') paginator2: MatPaginator;
but it's absolutly not my case :-/ I really need to apply dynamically a paginator for each tables that I renders... 

Thank you in advance!

**Comment by cdskill** [comment]
SOLVED !

**Comment by morca** [comment]
how did you solved your problem?

thanks

**Comment by cdskill** [comment]
wrapping the data table with his pagination in one component.
Declare a Input() in this component for the datasource.
That's it.

**Comment by badrinath389** [comment]
`<table mat-table [dataSource]="commodity.tariffAtCommodity">

                                            
                                            <ng-container matColumnDef="start">
                                                <th mat-header-cell *matHeaderCellDef> Cycle Start </th>
                                                <td mat-cell *matCellDef="let element"> {{element.start}} {{element.no}} </td>
                                            </ng-container>

                                            
                                            <ng-container matColumnDef="end">
                                                <th mat-header-cell *matHeaderCellDef> Cycle End </th>
                                                <td mat-cell *matCellDef="let element"> {{element.end}} </td>
                                            </ng-container>

                                            
                                            <ng-container matColumnDef="greenButton">
                                                <th mat-header-cell *matHeaderCellDef> greenbutton </th>
                                                <td mat-cell *matCellDef="let element"> {{element.greenButton.name}} </td>
                                            </ng-container>

                                            
                                            <ng-container matColumnDef="utility">
                                                <th mat-header-cell *matHeaderCellDef> Utility </th>
                                                <td mat-cell *matCellDef="let element"> {{element.utility.name}} </td>
                                            </ng-container>

                                            
                                            <ng-container matColumnDef="openEITariff">
                                                <th mat-header-cell *matHeaderCellDef> Tariff </th>
                                                <td mat-cell *matCellDef="let element"> {{element.openEI.name}} </td>
                                            </ng-container>

                                            
                                            <ng-container matColumnDef="openEIUrl">
                                                <th mat-header-cell *matHeaderCellDef> Url </th>
                                                <td mat-cell *matCellDef="let element"> {{element.openEI.refId}} </td>
                                            </ng-container>

                                            <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
                                            <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
                                        </table>
                                        <mat-paginator #paginator [pageSizeOptions]="[5, 10, 20]"></mat-paginator>`

Added dynamic data to each angular material table.

Trying to write like this from typescript file as per your comment. 

`@Input() dataSource;`

But the pagination not working can you help me.

@cdskill 

Thanks,
In advance.

**Comment by badrinath389** [comment]
SOLVED!

**Comment by mygoodkab** [comment]
> SOLVED!

Can i see what you solved ? 

thank.

**Comment by badrinath389** [comment]
Considering each table as a single record as pagination.

Take map in json array each item has pagination and passing angular table pagination for each item instead of considering with **#paginator**

So saperate paginator for each item in the Array.

**Comment by jaykhatriwebdesigner** [comment]
Some one please share the running example?

Thank you

**Comment by badrinath389** [comment]
@jaykhatriwebdesigner 
Sample code to understand.

```
import { Component, OnInit, ViewChildren, QueryList } from '@angular/core';
@ViewChildren(MatPaginator) paginator = new QueryList<MatPaginator>();
//Send Array Data to MatTableDataSource to get the details like pagination, sorting in the dataSource key
commodity.dataSource = new MatTableDataSource(Array);
// assign each pagingation to each array item
// put some time out to complete the above code
array[index].dataSource.paginator = self.paginator.toArray()[index];
```
```
<table mat-table matSort  #dataSource [dataSource]="commodity.dataSource">
<ng-container matColumnDef="columnName">
</ng-container>
<tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let element; columns: displayedColumns;">
</tr>
<mat-paginator #paginator [pageSizeOptions]="[12,24,36,48,60]" showFirstLastButtons></mat-paginator>
</table>
```

**Comment by jaykhatriwebdesigner** [comment]
Hello @badrinath389 

I have tried all cases which is possible from my side but not able to solve issue,

I have tables in accordions which is added dynamically.  

It will be good if you can create full example for me. 

Thank you in advance.
