### ISSUE TITLE
ListKeyManager - Active item out of the view doesn't come into view automatically when navigating

### ISSUE THREAD

**Issue by AhsanAyaz** [angular/material2#10271]
#### Bug, feature request, or proposal:
Bug & potential enhancement

#### What is the expected behavior?
When navigating through list items (in auto-complete or mat-list), the activeItem should bring the item into view if outside of the view. (so we don't have to scroll)

#### What is the current behavior?
Currently, if I'm pressing down arrow key to navigate through items and the next item is out of the view (I have to scroll), it is not brought into the view automatically.

#### What are the steps to reproduce?
[Reproduced the issue on StackBlitz](https://stackblitz.com/edit/angular-material2-issue-dzm22o?file=app/app.component.ts)

#### What is the use-case or motivation for changing an existing behavior?
There may be many cases where we would have a really long list of results returning from a remote server. I actually am implementing this use case right now. And since we have a `max-height` set to limit the results on the viewport, when navigating through `ListKeyManager` (which I just explored and implemented), the active item out of the viewport doesn't come into view.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cdk v5.1.1
@angular/core (others) v5.2.2

#### Is there anything else we should know?

![mar-05-2018 19-49-23](https://user-images.githubusercontent.com/9844254/36981223-63608c42-20ae-11e8-91b2-cb78cd2c8aff.gif)

**Comment by crisbeto** [comment]
The issue comes from you overriding the `max-height`. The autocomplete is set up to work with a particular `max-height` at the moment.

**Comment by AhsanAyaz** [comment]
@crisbeto . I understand that :) 
But if I have 20 results coming from the server. Or a custom list that I built using `ListKeyManager` on a component (not autocomplete), I would surely need to limit the `max-height` to allow scrolling at some point.

 I already mentioned this in `What is the use-case or motivation for changing an existing behavior?` section.

**Comment by AhsanAyaz** [comment]
@crisbeto I just checked, you are right.
This works fine if I remove the `max-height` and add a lot of items.
Since I'm using `ListKeyManager` on my own component. I have to see how `autocomplete` is handling it with the particular `max-height` set for it.

**Comment by crisbeto** [comment]
The `ListKeyManager` doesn't have anything to do with the scroll handling which is all up to the consuming component.

**Comment by AhsanAyaz** [comment]
Yep. You're right. Just peeked into the autocomplete's . [source code](https://github.com/angular/material2/blob/master/src/lib/autocomplete/autocomplete-trigger.ts#L385).

Closing the issue.
