### ISSUE TITLE
Data table multiple filters

### ISSUE THREAD

**Issue by lukejoliat** [angular/material2#10286]
I'm aware of the ability to create a custom filter with the **.filterPredicate** method. But I'm not aware of any way to have multiple filters on the same table that all interact with one another.

For instance, I want to filter just title down to a certain number of options, and then filter among those remaining options by date. 

Currently, when I filter by title, that looks for matches among all the data, and then when I search for date it essentially clears title and searches for matches among all the data again, and not the recently filtered set.

Does anyone know of a way to accomplish this?

**Comment by willshowell** [comment]
That use case sounds a little more specific than `MatTableDataSource` could be. Have you tried implementing your own `DataSource`? You'll have full control of any filtering mechanism you want.

**Comment by andrewseguin** [comment]
Alternatively avoid using the `MatTableDataSource` filter entirely and just manually filter the data you provide to the data source. 

Closing since there's no issue, but feel free to continue the discussion if you'd like to bounce ideas around.

**Comment by lukejoliat** [comment]
Thank you for your prompt replies!
