### ISSUE TITLE
Media assets are not hashed

### ISSUE THREAD

**Issue by mbn18** [angular/material2#10285]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
When the app is build all media assets are hashed ( for example: swirl.2c32b42e30b9cefbba4b.svg )
Beside those that are used with `addSvgIcon` and `addSvgIconSet`

#### What is the current behavior?

Currently mat-icon assets are not served as hashed and this harm the caching strategy.

#### What are the steps to reproduce?

Add lines
```
iconRegistry.addSvgIconSet(sanitizer.bypassSecurityTrustResourceUrl('assets/images/sprite.svg'));
iconRegistry.addSvgIcon('spaceship', sanitizer.bypassSecurityTrustResourceUrl('assets/images/image.svg'));
```
Run `ng serve --host 0.0.0.0`

Load in browser and note that only assets used by material are not hashed.

#### What is the use-case or motivation for changing an existing behavior?

Hashed assets can be safely set to be expired in X time.
New build will create new names. And those will have a new expiry

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 1.6.5
Node: 8.9.4
OS: linux x64
Angular: 5.2.7
@angular/cdk: 5.2.3
@angular/cli: 1.6.5
@angular/flex-layout: 5.0.0-beta.13
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

**Comment by jelbourn** [comment]
@mbn18 is there a specific problem manifesting? Those icons aren't ever really going to change since they're just examples.

**Comment by mbn18** [comment]
@jelbourn , not really sure what do you mean by *example*?

In my web site I have an SVG that I might update in the future. Maybe I will add an icon to the sprite.

**Comment by jelbourn** [comment]
Closing since it's unclear there's any issue here.
