### ISSUE TITLE
Stepper : Overriding icons errors

### ISSUE THREAD

**Issue by WizardPC** [angular/material2#10283]
#### Bug, feature request, or proposal:

Documentation and Bug ?

#### What is the expected behavior?

Sample code from the documentation need to work out of the box.

#### What is the current behavior?

< custom-icon > is used over < mat-icon >.

#### What are the steps to reproduce?

Copy paste the code :
https://material.angular.io/components/stepper/overview#overriding-icons

#### What is the use-case or motivation for changing an existing behavior?

Why not ? :)

#### Is there anything else we should know?

Stackblitz with fix : [https://stackblitz.com/edit/angular-uv3pzp](https://stackblitz.com/edit/angular-uv3pzp)

I figured out that i need to add editable="false" on the step 3 if i want to have the "done" icon. Expected behavior ?

Moreover, stepper 1 and 2 don't have their icons changed before conditions was met (eg : required input), so i assumed the last step 3 has the same behavior, but no... the icon change after go and back without meeting requirements (eg : step 1 true AND step 2 true). Expected behavior too ?

**Comment by crisbeto** [comment]
The idea with `custom-icon` was to illustrate that you aren't limited to using `mat-icon` when overriding the icons, but I can see the confusion if somebody is copying the example verbatim. As for the other behavior, it's working as expected.

**Comment by WizardPC** [comment]
Ok i understand the "custom-icon".

But for me, there is a difference between, editable, not editable, and final step.  
Can i have an icon for editable (eg : input form), non editable (eg : hints to the user between steps), and last step (eg: done) ?

If it's possible, how ? If not, why ? ^^

**Comment by crisbeto** [comment]
Currently we only support overriding the `edit` and `done` state icons. For the editable state it's a little trickier to provide a good API, because they default to being numbers which means that you'd either have to remember to override it for all of the steps, or you'd end up with some steps that have a number and others that have an icon.

**Comment by WizardPC** [comment]
Clearly indicate that "done" icon is used when editable="false" would be more understandable.

Thank you for your time !
