### ISSUE TITLE
Using [class] attribute on mat-card overrides card styling

### ISSUE THREAD

**Issue by ibuchan72390** [angular/material2#10298]
#### Bug, feature request, or proposal:
Bug - verified on StackBlitz

#### What is the expected behavior?
Using the [class] attribute on a mat-card should add the calculated class to the existing Material card styles so that we can augment the existing Material card style.

#### What is the current behavior?
Using the [class] attribute on a mat-card is completely overriding the Material styles and simply placing the calculated class on the mat-card instead of any of the standard Material card stylings.

#### What are the steps to reproduce?
Simply put a [class] attribute on a mat card and ensure that it's being calculated through a function on your controller. 
https://stackblitz.com/edit/angular-57jidz

#### What is the use-case or motivation for changing an existing behavior?
I'm attempting to dynamically style cards based on an object condition in an *ngFor loop.  I need to use a class so that I can integrate the background-color with the predefined styles from the Material SCSS and am using mixins to achieve this.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
TypeScript 2.4.2
Angular: 5.0.5
Angular Material: 5.2.4

**Comment by julianobrasil** [comment]
You can use `[ngClass]` or `[class.your-class]` instead of `[class]`. This is `@angular` behavior, not material.
