### ISSUE TITLE
MatDatePicker not working with Momentjs

### ISSUE THREAD

**Issue by willwsharp** [angular/material2#10299]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The input field the MatDatePicker is attached to should display the value of its formControl when using momentjs as the backing Date object.
#### What is the current behavior?
The input field the MatDatePicker is attached to does not display the value of its formControl when using momentjs as the backing Date object.

#### What are the steps to reproduce?
The issue can be found at this stackblitz.
https://stackblitz.com/edit/material-date-picker-not-working

#### What is the use-case or motivation for changing an existing behavior?
This was just working a week ago...

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular/cdk 5.2.1
Angular/core 5.2.7
Angular/material 5.2.1

**Comment by julianobrasil** [comment]
Related to https://github.com/angular/material2/issues/9780

**Comment by willwsharp** [comment]
I have resolved this; it was due to some developer error with incorrect import order.  The fact that it doesn't work on Stackblitz is actually just a coincidence.  Closing this.
