### ISSUE TITLE
Angular Material website / extra gap

### ISSUE THREAD

**Issue by javid-abd** [angular/material2#10303]
#### Bug, feature request, or proposal:

there is an annoying extra gap in the right side of the page.

https://material.angular.io/components/tabs/examples

**Comment by mtrdp642** [comment]
File issues relating to the docs website in the [angular/material.angular.io repo](https://github.com/angular/material.angular.io). You'll want to include a screenshot as well as what browser you're using.

**Comment by javid-abd** [comment]
so, I'm closing the issue here,as you said I provided more detail in that repo 
https://github.com/angular/material.angular.io/issues/405
