### ISSUE TITLE
Update Plunker Template

### ISSUE THREAD

**Issue by DevVersion** [angular/material2#1031]
This is just an issue to keep track of it.

Since #913 is not in yet and the Plunker doesn't use Angular RC.5 yet, we need to update the Plunker to use the `NgModules` concept and use the `alpha.7-2` version of Angular Material.

> The bundle can be manually generated in meanwhile

#913 is actually blocked right now, because I still need some feedback how we want to proceed with that.

**Comment by m0t0r** [comment]
@jelbourn, @DevVersion I've got a new working plunker with Angular R5 and Material alpha.7-2.

Here is [the link](http://plnkr.co/edit/SgyuIR?p=preview). Let me know if that's fine so I can create  a PR to update `ISSUE_TEMPLATE.md`. 

**_Note:_** SystemJS config uses `https://npmcdn.com` to get angular and material2 so it will load latest published versions. May be it could help with #913 somehow.

**Comment by DevVersion** [comment]
@m0t0r Thanks for your help.

The reason why we don't use any CDN's is, that the Plunker will make _tons_ of requests to resolve the given JS files.

> Our bundling concept reduces the amount of requests and it will be still possible to checkout older versions

Also the Plunker Template is now uploaded and uses the `NgModule` concept.
- http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview
