### ISSUE TITLE
mat-radio-group

### ISSUE THREAD

**Issue by andreyan-andreev** [angular/material2#10310]
```typescript
<mat-radio-group formControlName='gender'>
    <mat-radio-button value='1'>Male</mat-radio-button>
    <mat-radio-button value='2'>Female</mat-radio-button>
</mat-radio-group>
```

This will not work with value of gender being `1`, but will work with `'1'`, no need to explain the difference between two, right?

Is this how you design it to be??

**Comment by truginis** [comment]
Do you mean writing ```value=1``` instead of ```value='1'``` ?

**Comment by roeba** [comment]
And what does "not work" mean exactly for you? Why didn't you use the issue template?

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by andreyan-andreev** [comment]
@jelbourn great work, show them all how to resolve an issue :)
