### ISSUE TITLE
MatBadgeModule missing in 6.0.0-beta.4 ?

### ISSUE THREAD

**Issue by xmlking** [angular/material2#10323]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
