### ISSUE TITLE
Textarea not resizable on IE11

### ISSUE THREAD

**Issue by ruibasecone** [angular/material2#10328]
#### Bug, feature request, or proposal:
Bug: Textarea not resizable on IE11

#### What is the expected behavior?
Textareas to be resizable in IE11. A resize button in bottom right corner of textarea is shown.

#### What is the current behavior?
Textareas are not resizable in IE11. Resize button in bottom right corner of textarea does not show.

#### What are the steps to reproduce?

Open this in IE11, second input should be a resizable textarea:
https://material.angular.io/components/input/overview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.2
@angular/material: 5.2.3
browser: IE11

#### Is there anything else we should know?
Is IE11 tested? Because as one can see from material page, not only textarea's are broken:

<img width="1420" alt="screen shot 2018-03-08 at 15 33 17" src="https://user-images.githubusercontent.com/30622443/37160540-5fb9298c-22e8-11e8-9c48-0d24fe1cf3e6.png">

**Comment by donroyco** [comment]
The `resize` property is not supported by IE11, as seen [here on Can I Use](https://caniuse.com/#feat=css-resize). You could use the `matTextareaAutosize` property inside of your `textarea` element. See the [docs](https://material.angular.io/components/input/overview#auto-resizing-code-lt-textarea-gt-code-elements).

**Comment by jelbourn** [comment]
This isn't something that Angular Material adds, it's something that comes from the browser.
