### ISSUE TITLE
Material v5.2.4 on NPM is not consistent with the 5.2.4 release on GitHub

### ISSUE THREAD

**Issue by Mdevlin4** [angular/material2#10331]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The NPM package for Material 5.2.4 should be consistent with the GitHub 5.2.4 release.

#### What is the current behavior?
Currently, v5.2.4 on NPM is missing functionality that is in the 5.2.4 release tag on GitHub.

For example, we were depending on the ability to disable backdrops for menus, which was introduced in this commit (which is tagged with releases 6.0.0-beta-4 and 5.2.4). 

https://github.com/angular/material2/commit/e42f0bcead7cf05610195cc7ababddfe3952bdda#diff-863c4e6ab704390217dec7361906bec8

It looks like the version from NPM is missing changes that were supposed to be part of the 5.2.4 release.
Here is the menu implementation: https://unpkg.com/@angular/material@5.2.4/esm2015/menu.js (Note that it is missing changes from the commit I linked above).

Here is the typings: https://unpkg.com/@angular/material@5.2.4/menu/typings/menu-directive.d.ts (Which is also missing the "hasBackdrop" property)

#### What are the steps to reproduce?

Small Demo showing [hasBackdrop] is not available as an Input, even when using Material 5.2.4: https://stackblitz.com/edit/angular-material2-issue-cdminu?file=app%2Fapp.component.html

#### What is the use-case or motivation for changing an existing behavior?
Consistent behavior between NPM package and GitHub release tags.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.2.4

**Comment by jelbourn** [comment]
The 5.2.4 github tag might be pointing to the wrong thing, since new features aren't added for patch releases...

**Comment by Mdevlin4** [comment]
Oh I see, thanks for clearing that up, I appreciate it!
