### ISSUE TITLE
property top not working when i scroll in modal bootstrap

### ISSUE THREAD

**Issue by Tronghoang** [angular/material2#10338]
![image](https://user-images.githubusercontent.com/26815143/37196216-9719cf9c-23a8-11e8-88cb-3d6f7ca65557.png)
style in firt run :    
    width: 248.391px;
    pointer-events: auto;
    top: 241.5px;
    left: 74px;

But when i scroll down property top not change( If i use mat-autocomplete with out modal bootstrap, top changed).
This issue:
![image](https://user-images.githubusercontent.com/26815143/37196387-2d62b13a-23a9-11e8-8afe-1963a1203819.png)

**Comment by Chan4077** [comment]
@Tronghoang Can you provide a demo on Stackblitz?

**Comment by Tronghoang** [comment]
@Chan4077  yep, this is demo 
https://stackblitz.com/edit/angular-ub3ggv-bpssxk?file=app%2Fautocomplete-overview-example.html

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
