### ISSUE TITLE
mat-sidenav-container does not support ngClass

### ISSUE THREAD

**Issue by damoncasale** [angular/material2#10366]
#### Bug, feature request, or proposal:
<mat-sidenav-container *ngClass="{'some-class': true}">
does not render a sidenav container.

ERROR TypeError: Cannot read property 'add' of undefined
    at EmulatedEncapsulationDomRenderer2.webpackJsonp.../../../platform-browser/esm5/platform-browser.js.DefaultDomRenderer2.addClass

#### What is the expected behavior?
<mat-sidenav-container *ngClass="{'some-class': true}">
should render the sidenav container

#### What is the current behavior?
<mat-sidenav-container *ngClass="{'some-class': true}">
produces a console error and no rendered output:

#### What are the steps to reproduce?
See above.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 5.2.4, Angular 5.2, TypeScript 2.7.1, Chrome Version 64.0.3282.186 (Official Build) (64-bit), OSX

**Comment by crisbeto** [comment]
That's not the correct way to use `ngClass`. You're supposed to use it with the square brackets:

```
<mat-sidenav-container [ngClass]="{'some-class': true}">
```
