### ISSUE TITLE
I need my custom panel to open onfocus in the autocomplete then work as it is

### ISSUE THREAD

**Issue by alnvny** [angular/material2#10360]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by amorenew** [comment]
Add
`  @ViewChild(MatAutocompleteTrigger) trigger: MatAutocompleteTrigger;`
then on your focus run this method
 ```
opensearch(){
    this.trigger.openPanel();
  }
```
