### ISSUE TITLE
SideNav no longer working

### ISSUE THREAD

**Issue by deanchalk** [angular/material2#10371]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Material SideNav should work - completely broken

#### What is the current behavior?
https://material.angular.io/components/sidenav/examples

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

https://stackblitz.com/angular/nnvavxrkben?file=index.html

#### Is there anything else we should know?

The official material site and stackblitz no longer have a working sidenav component. I am trying to use it in a new project

**Comment by donroyco** [comment]
It's working for me. Have you cleared your cache? Can you provide a reproduction of your issue? What's the error in the console that you see?

**Comment by deanchalk** [comment]
Well this url show's it broken

[https://stackblitz.com/angular/nnvavxrkben?file=app%2Fsidenav-overview-example.html](https://stackblitz.com/angular/nnvavxrkben?file=app%2Fsidenav-overview-example.html

Ive tried it on several different computers and browsers. None of them have loaded a material design site before, so perhaps the issue is something in your cache giving a false positive - no?

Thanks

**Comment by donroyco** [comment]
<img width="658" alt="screen shot 2018-03-12 at 13 52 44" src="https://user-images.githubusercontent.com/1763537/37284655-b49a82cc-25fc-11e8-8949-51ffe023be92.png">

@deanchalk No problem at all, Chrome's latest version.

**Comment by deanchalk** [comment]
OK  thanks  - this must mean that my employers network systems must be blocking something because I see nothing. Will take a look here - thanks for your help

**Comment by crisbeto** [comment]
Closing for now. It can be reopened if there's a reproduction example.

**Comment by 1jibber** [comment]
![image](https://user-images.githubusercontent.com/1741577/37500270-70e6081a-292d-11e8-9e74-7978223d310d.png)
Most of the sidenav examples aren't rendering property on the material.angular.io website. Instead of rendering the example it is displaying 'Please open on Stackblitz to see result'. Looking at other control example pages they are all rendering fine.

**Comment by donroyco** [comment]
@1jibber That is afaik expected behaviour.

**Comment by desmati** [comment]
![image](https://user-images.githubusercontent.com/571283/43991041-91293456-9d79-11e8-993b-7196b43d326e.png)
SideNav examples aren't rendering.
