### ISSUE TITLE
Textarea with matTextareaAutosize has spinner arrows

### ISSUE THREAD

**Issue by EamonKavanagh** [angular/material2#10376]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
textarea element with matTextareaAutosize should not have spinner arrows

#### What is the current behavior?
textarea element with matTextareaAutosize has spinner arrows that go away after entering the first character

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-talhyo

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome Version 65.0.3325.146

**Comment by donroyco** [comment]
What do you mean with 'spinner arrows'? Do you have a screenshot?

**Comment by EamonKavanagh** [comment]
![textarea](https://user-images.githubusercontent.com/6708490/37309936-dadbd6fe-2618-11e8-8ab3-1307bf0f2721.png)

**Comment by WizardPC** [comment]
Personally, I don't reproduce with your stackblitz on Chrome & Firefox.

**Comment by EamonKavanagh** [comment]
Weird, I definitely see exactly the screenshot I posted from the link I provided.

I was able to create it by taking the example [here](https://material.angular.io/components/input/overview#auto-resizing-code-lt-textarea-gt-code-elements) and removing matAutosizeMinRows="2" andmatAutosizeMAxRows="5".

**Comment by donroyco** [comment]
@EamonKavanagh Not showing up here, Google Chrome, latest version.

**Comment by EamonKavanagh** [comment]
Interesting. Confirming I don't see it in Firefox but in Chrome Version 65.0.3325.146 I do see it.

**Comment by oskardudycz** [comment]
I have same issue. It might be related with placing that on flex layout or combination with input values. My markup:

``<div class="section-container">
    <mat-form-field class="full-width">
          <textarea
            id="item-description"
            matTextareaAutosize 
            matInput
            [placeholder]="'DESCRIPTION_PLACEHOLDER' | translate | uppercase"
            [formControl]="descriptionControl"
          >
          </textarea>
    </mat-form-field>
</div>``

As a temporary solution such css could be use:

``textarea.mat-autosize {
    resize: auto !important;
    overflow: hidden !important;
  }``

Ugly solution, but works as workoround

**Comment by EamonKavanagh** [comment]
I am able to reproduce without flex layout but it seems to be specific to the version of Chrome I'm on. See https://stackblitz.com/edit/angular-talhyo?file=app%2Finput-autosize-textarea-example.html for how I reproduced it.

**Comment by oskardudycz** [comment]
@mmalerba any update on that?

**Comment by jkruse** [comment]
The fix for this issue seems to be the cause of the exact same issue in Chrome 68, and possibly also the source of clipped characters in textareas in Mobile Safari. In Chrome 68, with Angular Material 6.4.5, I get a scrollbar in every autosized textarea. The scrollbar disappears if I either increase the height of the textarea by 4px (after calculation), or disable the padding and margin styles for textarea.mat-input-element (after calculation).

In both Chrome 68 and Mobile Safari, with this version of Angular Material, anything below the baseline on the last line of text in autosized textareas is clipped. Again, increasing height by 4px so the scrollbar disappears fixes this issue.

I have yet to figure out a workaround.

**Comment by mmalerba** [comment]
@jkruse I'm not seeing the issue on Chrome 68 on my Linux desktop with Angular Material 6.4.6. Are you still able to reproduce? If so, which OS are you using?

**Comment by HUU** [comment]
@mmalerba I can repro what @jkruse reported-- Angular Material 6.4.6 and Chrome 69 (Windows)

**Comment by jkruse** [comment]
As a workaround I came up with this added style:

```css
textarea.cdk-textarea-autosize-measuring {
  padding: 4px 0 !important;
}
```

**Comment by rtsdgim** [comment]
`extarea.mat-input-element {
    padding: 0;
    margin: 0;
}

.mat-form-field {
    line-height: normal;
}`
