### ISSUE TITLE
MatSelectModule not updating if connected MatChipsModule changes

### ISSUE THREAD

**Issue by djanesch** [angular/material2#10377]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If the user removes a element from the chip-list also the element should be deselected in the selection.
Also the first chip-list with [(ngModel)] is not recognizing selected and therefore all chips are grey.

#### What is the current behavior?
If the user removes a element from the chip-list the element in the selection stays selected.
Also the first chip-list with [(ngModel)] should recognizing selected chips and show them in the given color.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-myjbsc<br/>

#### What is the use-case or motivation for changing an existing behavior?
I have a Select-Box where you can choose Options and a chip-list where you see the selected options.
This two lists should be connected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
rxjs: 5.5.6
moment: 2.21.0
core-js: 2.5.3
zone.js: 0.8.20
hammerjs: 2.0.8
@angular/cdk: 5.2.4
@angular/platform-browser-dynamic: 5.2.8
@angular/core: 5.2.8
@angular/http: 5.2.8
@angular/forms: 5.2.8
@angular/common: 5.2.8
@angular/router: 5.2.8
@angular/compiler: 5.2.8
@angular/material: 5.2.4
web-animations-js: 2.3.1
@angular/animations: 5.2.8
@angular/platform-browser: 5.2.8
angular-in-memory-web-api: 0.5.4
@angular/material-moment-adapter: 5.2.4

**Comment by WizardPC** [comment]
Your link is broken

**Comment by djanesch** [comment]
@WizardPC thanks for telling me. insert wrong (mobile) code. corrected to the right one.

**Comment by djanesch** [comment]
After a few investigations I found a way to reach my expetecd behavior, but I think this solution is not the best.
For all users who are intrested in the solution I have created an other stackblitz: https://angular-myjbsc-himbtw.stackblitz.io
I made the following changes:

- added a template reference variable (https://angular.io/guide/template-syntax#ref-vars) for the select-box
- added this ref-var to function called in remove-event of chip
- changed the logic of removeNutzergruppenChip function, that now a new array of options is created which will be emited to the update-function of ngmodel (ref-var).

As I said before, I don't think that this is the best solution.
The best solution would be to change the way how the selected-option of mat-select works and also changes made afterwards will be emitted to the mat-select.

**Comment by tinayuangao** [comment]
@djanesch I think the two components are working as intended. 
The select's value does not change when the items inside the data array changes. So when chip-list removes an item from the list, select component is not notified. You will need to find a way to notify the select when the array data changes outside of select component.

A stackblitz without the ref-var is here: https://stackblitz.com/edit/angular-myjbsc-hit4tc?file=app%2Fchips-overview-example.ts

**Comment by djanesch** [comment]
@tinayuangao Thank's for the soulution without ref-var. My original version was also with splice but not with slice and assign the selected values with the result of slice.
Because my lack of knowledge in javascript the slice wasn't in my view.
Therefore I think you are right and it's the correct way those two components work and I close this issue.
