### ISSUE TITLE
overriding css in components globally 

### ISSUE THREAD

**Issue by mackelito** [angular/material2#10375]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
being able to set styling on component for whole app

#### What is the current behavior?
@include mat-button-theme($candy-app-theme);
allows for changing colors etc but more control is needed.
eg. to set box-shadow for all buttons

**Comment by josephperrott** [comment]
Closing, since Material components have the `ViewEncapsulation` set as `None`.  You can  include a global styling file in your application that targets your buttons to make any styling changes you would like to.

**Comment by mackelito** [comment]
So the only way is to override, ok.. was kind of hoping for a cleaner solution using variables but I'm great full for the framework.. really like it 👌😁👍
