### ISSUE TITLE
Allow FormField to query all MatErrors including descendants 

### ISSUE THREAD

**Issue by dobrevad** [angular/material2#10382]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
The proposal is to change MatFormField from:
@ContentChildren(MatError) _errorChildren: QueryList<MatError>;
to
@ContentChildren(MatError, {descendants: true}) _errorChildren: QueryList<MatError>;

We want to create a custom form field control.
The user should be able to add custom validators and error messages when wrapping the control in a mat-form-field.

However, there are some default validators and common error messages that should always be added. Currently, there isn't a way to add these within the custom form field control because the MatFormField is querying only the direct MatError content children.   

#### What is the current behavior?
A custom form field control cannot include a default mat-error.
Instead, every user needs to include the default validators and errors messages.

#### What are the steps to reproduce?
n/a

#### What is the use-case or motivation for changing an existing behavior?
To allow providing default validation and error messages in a custom form field control.

**Comment by crisbeto** [comment]
Adding the `descendants: true`, shouldn't be an issue, however Angular's content projection only works with direct children, which means that the errors won't be projected in the proper place inside the form field template. We should be able to work around it with portals though.

**Comment by dobrevad** [comment]
@crisbeto you're right. Just changing to `descendants: true` didn't do it.

Can you explain a little bit how would that look like with portals?

Here's my working (yet not ideal) solution using ngProjectAs:

```
 <mat-form-field>
    <input matInput required ngModel name="input"/>
    <my-form-error ngProjectAs="mat-error">Error</my-form-error>
 </mat-form-field>
```


```
@Component({
  selector: 'my-form-error',
  template: `
      <mat-error>
        <ng-content></ng-content>
      </mat-error>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{provide: MatError, useValue: FormError}],
})
export class FormError extends MatError {
}
```

Is there a way to add `ngProjectAs` to the host element from within the my-form-error component?
The point of wrapping in a custom component is to reduce boilerplate code like directive that in my code always needs to live on the mat-error element. Now requiring `ngProjectAs` defeats the purpose.

**Comment by dobrevad** [comment]
Here is what I tried in order to add ngProjectAs to the host element.
Not sure why that doesn't work.

```
@Component({
  selector: 'my-form-error',
  template: `...`
  host: {
    '[attr.ngProjectAs]': 'projectAs',
  },
  providers: [{provide: MatError, useValue: MyFormError}],
})
export class MyFormError extends MatError {
  projectAs = "mat-error";
}
```

**Comment by dobrevad** [comment]
@mmalerba  Do you have any suggestions here?

**Comment by mmalerba** [comment]
I can't think of a great way around it, we could add `[matError]` as an alternate selector, that way you could do:

```html
 <mat-form-field>
    <input matInput required ngModel name="input"/>
    <my-form-error matError>Error</my-form-error>
 </mat-form-field>
```

which is slightly cleaner

**Comment by mmalerba** [comment]
@crisbeto what was your idea for working around this with portals?

**Comment by crisbeto** [comment]
@mmalerba what I had in mind was a similar approach to what we did with the icons for the stepper, which use `ng-template` and `ngTemplateOutlet` (for some reason I remember it as using portals). We can have the `mat-error` expose itself as a template and then we can use `ngTemplateOutlet` to render it where we want.

**Comment by mmalerba** [comment]
@crisbeto so then adding an error would look like this?

```html
<mat-form-field>
  ...
  <div *matError>error</div>
</mat-form-field>
```

If we did do this, I would want to do it for the other pieces too for consistency (e.g. mat-hint, mat-label, mat-prefix, etc). I feel like this isn't as nice for users who are just using `mat-error` currently though, without wrapping it.

**Comment by crisbeto** [comment]
Yeah we'd have to change up the API a bit. Also I haven't looked into whether there are any performance drawbacks to doing it.

**Comment by dobrevad** [comment]
I agree that this isn't as nice if you don't need to wrap it.

Also Angular doesn't allow more than one structural directives on the same element so users would need to do:
```
<mat-form-field>
  ...
  <ng-container *ngIf="input.hasError('required')">
    <div *matError>error</div>
  </ng-container>
</mat-form-field>
```

which is kind of ugly.

**Comment by dobrevad** [comment]
Given that there isn't any good alternative I'm closing the request.
Thanks everyone!
