### ISSUE TITLE
md-input does not behave like input in a ngFor loop and it repeats the [(ngModel)] of the first item instead of showing the correct values

### ISSUE THREAD

**Issue by geelus** [angular/material2#1038]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

Check this plunker: 
http://plnkr.co/edit/UZtzQ0ulgRSJaCylB7QV?p=info
#### Which versions of Angular, Material, OS, browsers are affected? RC5 and Alpha 7-2

I'm using RC5 and Angular Material alpha 7-4
#### Is there anything else we should know? I believe this issue happens when I use a fixed name for the input form.

I tried to show you the issue by creating a template and I spent half an hour playing with it but it eventually didn't work but I hope it's showing you the issue.

**Comment by jelbourn** [comment]
@crisbeto can you reproduce on master?

**Comment by geelus** [comment]
Hi Jelbourn

This was because I was using input in a loop and allocated it a single name. I believe I fixed the issue by using a name + counter trick.

Should I get back to a single name?

**Comment by jelbourn** [comment]
Ah, that makes sense. Any form control needs a unique name.

**Comment by geelus** [comment]
Although it makes sense, but the original controls do work with one single name as well. May it's a good idea to somehow making it unique when it's inside a loop.
