### ISSUE TITLE
Does it support all mobile browser ? 

### ISSUE THREAD

**Issue by lakinmohapatra** [angular/material2#10392]
Hi 
Can anyone let me know the supported browsers (desktop & mobile) for angular 2 ? 

Thanks,
Lakin

**Comment by Chan4077** [comment]
@lakinmohapatra The supported browsers list is at the Angular docs available at <https://angular.io/guide/browser-support>.

---
Please take note that your issue may be closed as it doesn't follow the team's issue template.
