### ISSUE TITLE
<mat-grid-list> rowHeight="fit" crashes page

### ISSUE THREAD

**Issue by crooksey** [angular/material2#10395]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
I would expect when using rowHeight="fit" for the rowHeight to dynamically change depending on the contents of mat-grid-tile(s)

#### What is the current behavior?
mat-grid-list crashes

#### What are the steps to reproduce?
This stackblitz shows the working code, without using rowHeight but as you can see the mat-list is not rendering correctly.

https://stackblitz.com/edit/angular-cccnjp?file=app%2Fsidenav-responsive-example.html

Then if I use the same code and add rowHeight="fit" nothing renders (although the html is generated, if I inspect the element with dev tools)

https://stackblitz.com/edit/angular-cccnjp-ylmzf9?file=app/sidenav-responsive-example.html

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Currently using Angular5.2.6, Material 5.2.1, Linux & Windows tests TS 2.7.1, Firefox and Chrome tested

#### Is there anything else we should know?
N/A

**Comment by crisbeto** [comment]
[From the docs](https://material.angular.io/components/grid-list/overview):

> Fit: Setting rowHeight to fit This mode automatically divides the available height by the number of rows. Please note the height of the grid-list or its container must be set.

**Comment by crisbeto** [comment]
You have to set an exact height.

**Comment by crooksey** [comment]
If you have to set an exact height, how can I create a responsive page? Surely mine cannot be the only use case where you want the container/div/element to scale to the size of the content?

**Comment by crisbeto** [comment]
You might be able to stretch it using something like flexbox.

**Comment by crooksey** [comment]
So to get the above combination working correctly, I have had a bit of a hacky solution, see:

https://stackoverflow.com/questions/49234018/angular-material-mat-grid-list-not-expanding?noredirect=1#comment85535332_49234018

**Comment by VeeShostak** [comment]
@crooksey from Brian's great [blog post](http://brianflove.com/2017/05/03/responsive-angular/) on using Flex Layout to create a responsive mat-grid-list, you can use Angular Flex Layout's `ObservableMedia` service and set the `rowHeight` in the mat-grid-list dynamically as the number of columns change.

example:
```
<mat-grid-list [cols]="cols | async" gutterSize="16px" [rowHeight]="rowHeight + 'px'">
...
</mat-grid-list>
```

```
ngOnInit() {
    const grid = new Map([
      ['xs', 1],
      ['sm', 2],
      ['md', 4],
      ['lg', 4],
      ['xl', 4]
    ]);

    let start: number;

    grid.forEach((cols, mqAlias) => {
      if (this.observableMedia.isActive(mqAlias)) {
        start = cols;
      }
    });

    // on breakpoint, assign cols AND ROW HEIGHT appropriately
    this.cols = this.observableMedia.asObservable()
      .map(change => {

        this.rowHeight = this.heightToCols(grid.get(change.mqAlias));
        console.log(this.rowHeight);

        return grid.get(change.mqAlias);

      })
      .startWith(start);
  }

  heightToCols(cols: number): number {
    if (cols === 1) {
      return 250;
    } else if (cols === 2) {
      return 300;
    } else {
      return 350;
    }
  }
```

**Comment by crooksey** [comment]
Use Angular flex layout, it will solve all geometry issues. My EVA-L09. On O2.-------- Original Message --------Subject: Re: [angular/material2]  rowHeight="fit" crashes page (#10395)From: Meanstack Consulting <notifications@github.com>To: angular/material2 <material2@noreply.github.com>CC: Luke Crooks <luke@crooksey.org>,Mention <mention@noreply.github.com>I tried to use mat-grid-list within mat-dialog
grid-list would not even show up
it refused to take on the dimensions of the mat-dialog
and with three grid-list one for title,content,actions
not fun
the mat-dialog directives are not blendable with grid-list
grid-list wont take on any styles like 
and the rows get munged across different columns
seems we need to roll our own geometry mgt

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/angular/material2/issues/10395#issuecomment-390529147","url":"https://github.com/angular/material2/issues/10395#issuecomment-390529147","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/angular/material2","title":"angular/material2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/angular/material2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nhhockeyplayer in #10395: I tried to use mat-grid-list within mat-dialog\r\n\r\ngrid-list would not even show up\r\nit refused to take on the dimensions of the mat-dialog\r\nand with three grid-list one for title,content,actions\r\n\r\nnot fun\r\n\r\nthe mat-dialog directives are not blendable with grid-list\r\ngrid-list wont take on any styles like \u003cmat-grid-tile style=\"vertical-align: middle\"\u003e\r\nand the rows get munged across different columns\r\n\r\nseems we need to roll our own geometry mgt"}],"action":{"name":"View Issue","url":"https://github.com/angular/material2/issues/10395#issuecomment-390529147"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [angular/material2] \u003cmat-grid-list\u003e rowHeight=\"fit\" crashes page (#10395)",
"sections": [
{
"text": "",
"activityTitle": "**Meanstack Consulting**",
"activityImage": "https://avatars2.githubusercontent.com/u/6886551?s=160\u0026v=4",
"activitySubtitle": "@nhhockeyplayer",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"angular/material2\",\n\"issueId\": 10395,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/angular/material2/issues/10395#issuecomment-390529147"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 312612417\n}"
}
],
"themeColor": "26292E"
}Sent via Migadu.com, world's easiest email hosting>

**Comment by aWeinzierl** [comment]
so this bug is not going to be solved?

**Comment by crooksey** [comment]
@aWeinzierl you need to use angular material with flexbox to get the desired functionality I was initially after.

**Comment by vaesergio** [comment]
Angular material says on Grid List Documentation:

> Fit: Setting rowHeight to fit This mode automatically divides the available height by the number of rows. Please note the height of the grid-list or its container must be set.

So basically in here:
https://stackblitz.com/edit/angular-cccnjp-ylmzf9?file=app/sidenav-responsive-example.html

_Instead of_ <mat-grid-list cols="2"  rowHeight="fit">
**something like** <mat-grid-list cols="2"  rowHeight="fit" style="height: 400px">
And it works perfectly

**Comment by webia1** [comment]
Regrettably, Angular has the worst Google material implementation (in comparison to VueJS/Vuetify or React/MaterialUI) because nothing works really properly. Every solution above does not work as expected.  The only way out is: https://github.com/angular/flex-layout

**Comment by JdidouBrahim** [comment]
this problem can be solved using flexbox.
`.container {
  display: flex;
  flex-wrap: wrap;
}

.item {
  flex-grow: 1;
  flex-basis: 300px;
  margin: 10px;
}`

`  <div class="item">A</div>
  <div class="item">B</div>
  <div class="item">C</div>
  <div class="item">D</div>  
  <div class="item"></div>   
  <div class="item"></div>  
</div>`
you can  find more details here :
 https://www.vinta.com.br/blog/2017/responsive-layout-flexbox/
