### ISSUE TITLE
RadioButton checked does not work with value is a number

### ISSUE THREAD

**Issue by DevilHeS** [angular/material2#10399]
This is my test code:
  
**
 <mat-radio-button class="example-radio-button"  [checked]="true" [value]="12">
    Radio Test 
  </mat-radio-button>
**
![d 7z zl isl x8_i 1oijt](https://user-images.githubusercontent.com/7010685/37351278-ab8d3ef8-2715-11e8-8cda-bfc91ca3f2c7.png)
**
 <mat-radio-button class="example-radio-button"  [checked]="true" [value]="ThisIsAString">
    Radio Test 
  </mat-radio-button>
**
![hz 1e okf1ep9wl 6o2 d o](https://user-images.githubusercontent.com/7010685/37351394-eaece60c-2715-11e8-94b7-2c30ebfe5044.png)

_**version info:**_
 "@angular/core": "5.2.7",
 "@angular/forms": "5.2.7",
 "@angular/material": "^5.2.4",
  "@angular/cdk": "^5.2.4",
  "typescript": "2.6.2"

Please tell me what went wrong

**Comment by mtrdp642** [comment]
This is due to the radios having the same ```name``` property value. According to the [docs](https://material.angular.io/components/radio/overview):
```
All radio-buttons with the same name comprise a set from which only one may be selected at a time.
```
If you want both radios to be selected at the same time, add a ```name``` property to both radio elements with a different value.

[Demo](https://stackblitz.com/edit/angular-material2-issue-ymt1li)

**Comment by WizardPC** [comment]
I think it's two differents code, not two buttons on the same page with the same name.

**Comment by DevilHeS** [comment]
OK , Thanks

**Comment by SSTPIERRE2** [comment]
@DevilHeS I'm seeing the same thing using the doc's stackblitz example. `checked` seems to only work if it's passed a string.

**Comment by tienanhcntt2** [comment]
<mat-radio-group [(ngModel)]="selectzhan" (change)="onSelectionChange($event)">
              <mat-radio-button value="8" >8 {{'rainFall.station' | translate}}</mat-radio-button>
              <mat-radio-button [checked]="true" value="16">16 {{'rainFall.station' | translate}}</mat-radio-button>
            </mat-radio-group>
why don't
