### ISSUE TITLE
animate the new row added to the mat-table

### ISSUE THREAD

**Issue by oscarlagatta** [angular/material2#10417]
#### Bug, feature request, or proposal:
while adding a new row element to the mat-table, notify the user what row has been added new to the list of rows

#### What is the expected behaviour?
being able to notify the user where the new row has been added

#### What is the current behaviour?
no indication of when the data changed 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
allow the user to identify where the new row has been added

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2, Chrome

#### Is there anything else we should know?
no

**Comment by patrickqsos** [comment]
You can achieve that by creating a custom animation and apply it to the  `<mat-row>`

First you can create a file to contain all your animations. For example: template.animations.ts

```
import { trigger, sequence, state, animate, transition, style } from '@angular/animations';

export const rowsAnimation = 
    trigger('rowsAnimation', [
      transition('void => *', [
        style({ height: '*', opacity: '0', transform: 'translateX(-550px)', 'box-shadow': 'none' }),
        sequence([
          animate(".35s ease", style({ height: '*', opacity: '.2', transform: 'translateX(0)', 'box-shadow': 'none'  })),
          animate(".35s ease", style({ height: '*', opacity: 1, transform: 'translateX(0)' }))
        ])
      ])
    ]);
```
The animation is **rowsAnimation** and it has the transition void => *that applies when the element enters the view, regardless of what state it will have later.

More info about animations:
[https://angular.io/guide/animations](url)

In your html template, add the animation to the  `<mat-row>`

` <mat-row [@rowsAnimation]="" *matRowDef="let row; columns: displayedColumns;"></mat-row>`

In your ts file, import the animation from the previous file and provide it to the animation array in the component declaration:

```
import { rowsAnimation } from './animations/template.animations';

@Component({
  selector: 'material-app',
  templateUrl: 'app.component.html',
  animations: [rowsAnimation],
})
```
Now each time you add new data to the datasource the animation appears

I have created a StackBlitz with the full example:
https://stackblitz.com/edit/angular-material2-issue-mxouqy

**Comment by josephperrott** [comment]
Closing, as noted in the response above, you should be able to control the animation of rows using Angular's Animations API.

**Comment by oscarlagatta** [comment]
Thanks Joe and Patrick

**Comment by chethan1095** [comment]
Hi @patrickqsos can we add a manual data instead of pushing some random data into it

**Comment by patrickqsos** [comment]
@chethan1095 Yes. the stackblitz example has a function **createNewUser** that returns an instance of **UserData** with random data that is added to the datasource of the mat-table. Inside that function you can manually call your backend or retrieve info from some service to get data you need

**Comment by ppumkin** [comment]
All your links are dead. I have been searching for a while on how to do this and Material docs have changed. They demonstrate everything in the overview but there is no link for developers to find out how to do it. Luckily your code survived here and probably will try that.

Both angular and stackblitz, have been obliterated.

**Comment by ravidannani** [comment]
@patrickqsos 

I was actually looking the same thing. but unfortunately the link you shared is not working.
https://stackblitz.com/edit/angular-material2-issue-mxouqy
Could you please help us.

**Comment by patrickqsos** [comment]
Hi, here is the updated link:
https://stackblitz.com/edit/angular-material-addrow-example
