### ISSUE TITLE
ERROR in /var/www/html/DMARC360_code/src/app/main/content/ui/active-domains/active-domains.component.ts (4,32): Module '"/var/www/html/DMARC360_code/node_modules/@angular/material/material"' has no exported member 'MatTableDataSource'.

### ISSUE THREAD

**Issue by jainendrapal** [angular/material2#10411]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by donroyco** [comment]
Please complete the issue template to provide more information about your issue (and rename your title).

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by jainendrapal** [comment]
Finally  got solution...!!!
its working.. i did this in my service file
this.data = res.json()['results'];
