### ISSUE TITLE
mat-ink-bar don't resize on width change

### ISSUE THREAD

**Issue by MartinFreire** [angular/material2#10425]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I expect the mat-ink-bar to resize with the change on the width of the selected tab, or I could call a refresh method to re-calculate the width of the tab

#### What is the current behavior?
The mat-ink-bar stays the same size on changes to the width of the selected tab

#### What are the steps to reproduce?
StackBlitz reproduction https://angular-material2-issue-7kyuny.stackblitz.io

YouTube recording of the problem: [https://youtu.be/az6KJA-pvto](https://youtu.be/az6KJA-pvto)

#### What is the use-case or motivation for changing an existing behavior?
I have a page that shows a secondary (sometimes important) sidebar, and this is shown to the user and hidden 1.5 seconds later. And the mat-ink-bar stays the same size

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
W10, Angular 5
Edge 41
Chrome 65
Angular Versions
"@angular/animations": "5.2.8",
"@angular/cdk": "5.2.4",
"@angular/common": "5.2.8",
"@angular/compiler": "5.2.8",
"@angular/core": "5.2.8",
"@angular/flex-layout": "5.0.0-beta.13",
"@angular/forms": "5.2.8",
"@angular/http": "5.2.8",
"@angular/material": "5.2.4",
"@angular/material-moment-adapter": "5.2.4",
"@angular/platform-browser": "5.2.8",
"@angular/platform-browser-dynamic": "5.2.8",
"typescript": "2.6.2",

#### Is there anything else we should know?
I'm using the following template:
http://fuse-angular-material.withinpixels.com
But it doesn't have examples of this problem

**Comment by crisbeto** [comment]
Watching for width changes would be very expensive which is why we don't do it. There's https://github.com/angular/material2/pull/10343 that adds a method to allow you to re-align the ink bar yourself.

**Comment by MartinFreire** [comment]
Thanks for your quick reply.
For what I could understand this is not a merged property right?
Because I couldn't find a way to see hot it works
Thanks again!

**Comment by crisbeto** [comment]
The pull request for it hasn’t been merged yet.

**Comment by MartinFreire** [comment]
Perfect, I'll wait
Thanks again!
