### ISSUE TITLE
Autofocus on MatInput Suffix Button Click Should be able to be negated

### ISSUE THREAD

**Issue by pdaniel3** [angular/material2#10424]
#### Bug, feature request, or proposal:
When clicking on a suffix button in a MatInput, the input auto focuses. I would like to be able to disable this programatically or with some option. I essentially want to mirror the behavior of the MatDatePicker, where when the calendar icon is clicked, instead of the input focusing it just opens the date picker. So in my case I would like to click my suffix and have some other action perform on the page (specifically reorder a column descending/ascending right below the input), without focusing. In the case of my application, the cursor could be in some other input, and it would be annoying during normal use for a user to get distracted by this focus from where they were before. Is this possible without moving the suffix button outside of the input?

**Comment by julianobrasil** [comment]
You can add a `event.stopPropagation()` to avoid focusing the input:

```html
<mat-form-field>
  <input matInput type="text" value="test" #input>
  <button mat-button 
          *ngIf="input.value" 
          matSuffix
          mat-icon-button 
          (click)="_clearValue($event,input)">
    <mat-icon>close</mat-icon>
  </button>
</mat-form-field>
```

```ts
_clearValue(evt: MouseEvent, input: HTMLInputElement) {
  input.value = '';

  // avoids focusing the input
  evt.stopPropagation();
}
```

**Comment by josephperrott** [comment]
Closing, as noted above you should be able to `stopPropagation`
