### ISSUE TITLE
Tooltip on expansion panel

### ISSUE THREAD

**Issue by ashygk** [angular/material2#10422]
#### Bug, feature request, or proposal:
Question

#### What is the expected behavior?
To have tooltips on expansion panel title header

#### What is the current behavior?
Tooltips and Expansion panel work separately

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
As per a requirement, need to have tooltips on expansion panel headers

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular4
material 5.0.3
os windows
typescript 2.7.2
browsers chrome

**Comment by josephperrott** [comment]
Closing, as this can already be done as shown [here](https://stackblitz.com/edit/angular-material2-issue-uiotge?file=app/app.component.html)

**Comment by ashygk** [comment]
Doesn't work for me when added like below:
<mat-expansion-panel-header matTooltip="This is tooltip">
<mat-panel-title><h1>Hover me</h1></mat-panel-title>
</mat-expansion-panel-header>
Using "@angular/material": "^5.2.4"

**Comment by noamyg** [comment]
Doesn't work for me either. matTooltip doens't show up anywhere when placed inside mat-accordion.
