### ISSUE TITLE
Does Material 2 has highlight too?

### ISSUE THREAD

**Issue by m-kermani** [angular/material2#1042]
I would like to know, does Material 2 is going to support highlight? 

There were a directive in Angular Material 1 called highlight and it also was used in autocomplete, may I if it is exist not on Material 2, where are its sources? I would like to add something to it 

Thanks

**Comment by DevVersion** [comment]
I assume this will be part of the `autocomplete` as same as it is in Material 1.x and shouldn't be its own component / directive.

That's why I think this will / can be added once the actual `autocomplete` is available.
> See issue #117

**Comment by m-kermani** [comment]
I found a small problem in `highlight `(Which is `autocomplete`) in one of RTL languages and I would like to contribute, I wanted to add it to the Material 2 first

@DevVersion Thanks

**Comment by jelbourn** [comment]
It would be part of the autocomplete #117
