### ISSUE TITLE
Angular Material stepper: method for go to any step index programatically ?

### ISSUE THREAD

**Issue by amaneer94** [angular/material2#10421]
#### Bug, feature request, or proposal:
I want to jump at any step if non-linear stepper is being used. For example i have 3 steps and want to jump to direct step no 3 from step 1 using index by programming.

#### What is the expected behavior?

> @ViewChild('stepper') stepper: MatStepper;
> public proceed(index) {
> //cannot find any method i.e. this.stepper.goToStep(index);
> }

#### What is the current behavior?
> @ViewChild('stepper') stepper: MatStepper;
> public proceed() {
> this.stepper.next();
> }

**Comment by ciesielskico** [comment]
You can set selectedIndex directly.

**Comment by WizardPC** [comment]
Here a stackblitz [https://stackblitz.com/edit/angular-demo-matstepper-move](https://stackblitz.com/edit/angular-demo-matstepper-move)

credit to : [https://stackoverflow.com/a/48417905/9456169](https://stackoverflow.com/a/48417905/9456169)
