### ISSUE TITLE
Incomprehensible karma error when using mat-form-field

### ISSUE THREAD

**Issue by NazarKalytiuk** [angular/material2#10420]
#### Bug, feature request, or proposal:
Karma Disconnected, because no message in 10000 ms when we not imported BrowserAnimationModdule in testbed and use `mat-form-field` (or maybe something else too)

#### What is the expected behavior?
Must be error Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

#### What is the current behavior?
> Karma Disconnected, because no message in 10000 ms

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
1. Create a component with mat-form-field component
2. Run karma test without importing BrowserAnimationsModule in testbed

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.0
Material 5.2.0

**Comment by josephperrott** [comment]
Unfortunately, the error that is being seen is because Karma is timing out.  It is not possible for the code being tested to determine it is timing out and throw an error.  Because of this we are not able to provide different error messaging from Karma.
