### ISSUE TITLE
Universal rendered elements do not have classes applied

### ISSUE THREAD

**Issue by zakhenry** [angular/material2#10435]
#### Bug:
When attempting to render a material element (eg `a[mat-button]`) server side using universal, the `.mat-button` class is not added, causing the css rules not to be applied

#### What is the expected behavior?
Server side rendered material element should have the correct classes/styling applied to them
### Client side rendered output: 
```html
<a _ngcontent-c6="" class="ng-tns-c6-1 mat-button" mat-button="" routerlinkactive="active" ng-reflect-router-link="/,blog" ng-reflect-router-link-active="active" tabindex="0" aria-disabled="false" href="/blog">
  <span class="mat-button-wrapper">
    <span _ngcontent-c6="" class="ng-tns-c6-1">Blog</span>
  </span>
  <div class="mat-button-ripple mat-ripple" matripple="" ng-reflect-centered="false" ng-reflect-disabled="false"
       ng-reflect-trigger="http://localhost:4200/blog"></div>
  <div class="mat-button-focus-overlay"></div>
</a>


```

#### What is the current behavior?
No classes are added to `[mat-button]` (and other cases, e.g. `mat-sidenav` and others) when rendered with universal
### Server side rendered output: 
```html
<a _ngcontent-c6="" class="ng-tns-c6-1" mat-button="" routerlinkactive="active" tabindex="0" aria-disabled="false" href="http://localhost:3000/blog">
  <span class="mat-button-wrapper">
    <span _ngcontent-c6="" class="ng-tns-c6-1">Blog</span>
  </span>
  <div class="mat-button-ripple mat-ripple" matripple=""></div>
  <div class="mat-button-focus-overlay"></div>
</a>
```

#### What are the steps to reproduce?
(no online tool can do universal rendering that I know of)

1. Set up project with universal, 
1. add a mat-button, 
1. serve with ssr
1. inspect the dom - should see .mat-button class applied and corresponding styles

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
"@angular/animations": "5.2.8",
"@angular/cdk": "5.2.4",
"@angular/common": "5.2.8",
"@angular/compiler": "5.2.8",
"@angular/core": "5.2.8",
"@angular/flex-layout": "5.0.0-beta.13",
"@angular/forms": "5.2.8",
"@angular/http": "5.2.8",
"@angular/material": "5.2.4",
"@angular/platform-browser": "5.2.8",
"@angular/platform-browser-dynamic": "5.2.8",
"@angular/platform-server": "5.2.8",
"@angular/router": "5.2.8",
```

#### Is there anything else we should know?
This PR appears to have removed usages of renderer2 which would ordinarily be used to support server side rendered elements? https://github.com/angular/material2/pull/8235

**Comment by WizardPC** [comment]
Link to #9865 ? @DevVersion

**Comment by zakhenry** [comment]
@WizardPC ah yep that's a dupe, thanks for picking that up
