### ISSUE TITLE
Nested tree not load async nodes with AOT

### ISSUE THREAD

**Issue by DocLM** [angular/material2#10437]
#### Bug, feature request, or proposal:
Bug
#### What is the expected behavior?
Building the app with aot and click item icon, it will load children and update view with children of the node.

#### What is the current behavior?
Building the app with aot and click item icon, it will load children and not show children of the node.

#### What are the steps to reproduce?
- Clone the repo: https://github.com/DocLM/nested-tree-example
- Install dependencies
- Run with `ng serve --aot`
- Open the page and click on the `>` icon.

Live example (here it work): https://stackblitz.com/edit/angular-olseyg

#### What is the use-case or motivation for changing an existing behavior?
It work without aot and not work with aot

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Browsers: Chrome 65 on MacOS 10.13.3
Material: 6.0.0-beta.4
Angular: 6.0.0-beta.7 (also tested with 5)
Typescript: ~2.5.3

**Comment by DocLM** [comment]
I tested the fix with rc.0 version but nothing changed.
I tested it with ng serve --prod with @angular/cli 6.0.0-beta.8

https://github.com/DocLM/nested-tree-example

**Comment by tinayuangao** [comment]
@DocLM This could be a bug in angular. We will have a workaround #10635
