### ISSUE TITLE
ability to change the default color palette

### ISSUE THREAD

**Issue by daniele-zurico** [angular/material2#1043]
#### feature request:
Change the values of the default theme.

#### What is the expected behavior?
Able to configure the values of the palette changing the color that we prefer

#### What is the current behavior?
Only the green is allowed

#### Which versions of Angular, Material, OS, browsers are affected?
all

**Comment by AlexDede** [comment]
see https://github.com/angular/material2/issues/123

**Comment by TheCaptainDate** [comment]
Currently the only way you have is to clone this repository, change colors in `default-theme.scss` and then compile material2 by yourlself.
Example of changing colors - https://github.com/TheCaptainDate/ssp-material2/commit/81c906927544ec0dd3f00c92e7e351db625e9cfe

**Comment by jelbourn** [comment]
See #123
