### ISSUE TITLE
timepicker and datetimepicker component

### ISSUE THREAD

**Issue by NehalDamania** [angular/material2#10445]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Create Time Picker and Date Time Picker Component

#### What is the current behavior?
No Time Picker and Date Time Picker Component

#### What are the steps to reproduce?
New Feature

#### What is the use-case or motivation for changing an existing behavior?
Time Picker and Date Time Picker are commonly used components in many use cases. Without the same, users have to create not so optimal Date Time pickers in the app.

#### Is there anything else we should know?
https://material.io/guidelines/components/pickers.html#pickers-time-pickers

**Comment by jotatoledo** [comment]
`DatetimePicker` is already tracked in an issue. However there is no formal feature request for a `TimePicker` component

**Comment by fxck** [comment]
Don't worry, timepicker will be the base for datetimepicker.

**Comment by NehalDamania** [comment]
Thanks @fxck

**Comment by crisbeto** [comment]
Closing as a duplicate.

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
