### ISSUE TITLE
Feature request: Indivitual column filtering in mat-table

### ISSUE THREAD

**Issue by suvonkar** [angular/material2#10444]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Expecting a feature to add individual column filter like the following table.

https://saulis.github.io/iron-data-table/demo/filtering.html

#### What is the current behavior?
Currently full data objects are filtering by string.

**Comment by andrewseguin** [comment]
If you are using the `MatTableDataSource`, you have full control by providing your own `filterPredicate` function. Otherwise if you have a a custom data source, this should be fairly straightforward to implement.
