### ISSUE TITLE
Textarea with autosize doesn't have correct initial height if embedded in initially hidden DIV

### ISSUE THREAD

**Issue by Londovir** [angular/material2#10453]
#### Bug, feature request, or proposal:
If you place a textarea element with matTextareaAutosize and matAutosizeMinRows value set inside of a DIV which is initially hidden using a [hidden] binding and the component the textarea is contained within is conditioned with an *ngIf, when the hidden binding is removed later via code, the initial height of the textarea element is not set properly to the requested number of mininmum rows.

Clicking inside the textarea, or any other material input element for that matter, will immediately cause the textarea to expand in size to the proper height.

#### What is the expected behavior?
When made immediately visible, the textarea should have the correct height on first display.

#### What is the current behavior?
Upon first display, the textarea has reduced size (about 2 rows), rather than the requested minimum rows specified by the matAutosizeMinRows attribute.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/angular-t2tknw

Upon loading this StackBlitz, there are 4 instances of the same component on the page. The top 3 have some manner of "hiding" the component until a simulated 2 seconds delay takes place, to simulate waiting for an HTTP call pending. When that call ends, and the return data is set into a variable of the component, the hidden flag property is toggled, which makes the component contents (including the test component containing the textarea) become visible. However, the textarea height is not set correctly.

As shown in the StackBlitz, the combination of [hidden] and *ngIf on the component combine to cause issues with the height of the textarea being initially set properly; all other combinations do not exhibit the behavior.

Click on the input element below it. Observe that the textarea height "jumps" into the correct height of rows requested. Thus, some action causes a change in the components that makes the textarea height be recalculated.

#### What is the use-case or motivation for changing an existing behavior?
Visually this is jarring, especially if there are multiple such textareas on the page when it is first displayed. If the user clicks into one input element anywhere, the entire layout may jump into a different height configuration.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on Angular 5.2.4+, Material 5.2.1+, TypeScript 2.5.3, Chrome browser

**Comment by mmalerba** [comment]
This is because the component is still initialized and tries to measure itself even though the parent div is hidden. This causes it to get incorrect measurements. This is not a use case we plan to support, you should try to avoid doing this type of thing, instead preferring `*ngIf` over making it hidden.
