### ISSUE TITLE
Could the mat paginator support 'first' and 'last' nav buttons?

### ISSUE THREAD

**Issue by GWillits** [angular/material2#10477]
#### Bug, feature request, or proposal:

Feature request
#### What is the expected behavior?

We believe the user experience would be enhanced by being able to jump to first and last pages.
#### What is the current behavior?
You can only navigate one page at a time. So if there are a lot of records you can't jump to last without a lot of clicking.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?

We believe this would be a better user experience and is in line with other similar pagination components.
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All.

#### Is there anything else we should know?
Happy to do a pull request if this is the most appropriate way forward but not critical for us - if it's on a roadmap we can wait.

**Comment by WizardPC** [comment]
It's already available... [https://material.angular.io/components/paginator/api](https://material.angular.io/components/paginator/api)

Use `showFirstLastButtons="true"`

**Comment by GWillits** [comment]
Ah great sorry. We have been tracking this for a while. Must have missed the update - cheers.
