### ISSUE TITLE
Getting started: failure at "Install Angular Material 2 components"

### ISSUE THREAD

**Issue by MikaelCluseau** [angular/material2#1047]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
`npm install --save @angular2-material/core @angular2-material/button @angular2-material/card` should work.

#### What is the current behavior?
Install fails because referenced github repositories don't exist: 
```
$ git clone git@github.com:angular2-material/button
Cloning into 'button'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ git clone git@github.com:angular2-material/card
Cloning into 'card'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ git clone git@github.com:angular2-material/core
Cloning into 'core'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

#### What are the steps to reproduce?

```
$ npm install -g angular-cli
$ ng new my-project
$ cd my-project
$ npm install --save @angular2-material/core @angular2-material/button @angular2-material/card
```

#### What is the use-case or motivation for changing an existing behavior?
Have the getting started working.

#### Which versions of Angular, Material, OS, browsers are affected?
Debian 8, not yet in the browser.

#### Is there anything else we should know?
I think the issue is to have the github repositories exist or change the references npm uses to existing addresses.

**Comment by jelbourn** [comment]
This appears to be a problem on your environment, possibly that your shell treats `@` as a special character or is ignoring it. [The packages are definitely on npm](https://www.npmjs.com/~angular2-material).
