### ISSUE TITLE
MAT-TABLE too slow to load when the column definitions are specified dynamically

### ISSUE THREAD

**Issue by jayakrishna-v** [angular/material2#10475]
#### Bug, feature request, or proposal:
Slowness

#### What is the expected behavior?
Expecting to display mat-table with 500 records in a second

#### What is the current behavior?
Taking 6 seconds to load 500 records in the below scenario

#### What are the steps to reproduce?
I have a table (with 25 - 30 columns) in my application whose columns are dynamically formed. We have a json array which contains the column definiotions (i.e., columnNames).  Using this json array, columns are dynamically formed as mentioned below.

<.ng-container  *ngFor="let column of columnNames" matColumnDef={{column.ColumnName}}>
     <.mat-header-cell mat-sort-header >{{ column.ColumnHeader }}<./mat-header-cell>
     <.mat-cell *matCellDef="let row"> {{ row[column.ColumnName] }}<./mat-cell>
<./ng-container>

In this case, it is taking 5 to 6 seconds to display the data.

But when we mention the column definitions hard-coded (without ngfor) as mentioned below, it is not taking more than 1.5 seconds to load the same number of columns. But our requirement is to load the columns dynamically

<.ng-container  matColumnDef='column1'>
     <.mat-header-cell mat-sort-header >column1<./mat-header-cell>
     <.mat-cell *matCellDef="let row"> {{ row[column1] }}<./mat-cell>
<./ng-container>
..
..
upto
<.ng-container  matColumnDef='column25'>
     <.mat-header-cell mat-sort-header >column25<./mat-header-cell>
     <.mat-cell *matCellDef="let row"> {{ row[column25] }}<./mat-cell>
<./ng-container>

Note : We have only 500 records in the datasource

#### What is the use-case or motivation for changing an existing behavior?
As mentioned above, our requirement is to load the columns dynamically

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.7.3
Node: 8.9.4
OS: win32 x64
Angular: 5.2.9

@angular/material: 5.2.4

#### Is there anything else we should know?
It would be great if someone can suggest me the best way to load columns dynamically.

Thanks.

**Comment by jayakrishna-v** [comment]
/</mat-header-cell/>/ got disappeared in the above 'issue editor/viewer.'

**Comment by benneq** [comment]
Could you try angular material 6 beta? Maybe it got faster.

Else maybe some features from Angular**JS** Material should be ported to angular material. For example Virtual Repeat: https://material.angularjs.org/latest/demo/virtualRepeat

**Comment by willshowell** [comment]
Have you tried placing a `trackBy` on your `ngFor columnNames`?

**Comment by Eddygn** [comment]
I'm experiencing a similar issue, with the latest beta, 6.0.0-beta.6
Even with `trackBy` set. 

~230 rows, enabling additional 7 columns to 4 already rendered takes chrome about 120seconds. Firefox is much faster and does it in about tenth of the time (~15sec).
All columns have inputs.

**Comment by WizardPC** [comment]
Can you do an analysis of this loading ? Via the developper console or other tools ?

**Comment by willshowell** [comment]
Or even a stackblitz reproduction?

**Comment by jayakrishna-v** [comment]
@willshowell @Eddygn 
trackBy did not show any difference in the performance.

**Comment by jayakrishna-v** [comment]
@willshowell 
I will try to give you a stackblitz reproduction.

**Comment by jayakrishna-v** [comment]
Is there any change in the angular / material versions used in stackblitz this week? Mat table working faster than last week. If so, I would need to upgrade the same in my app also.

**Comment by andrewseguin** [comment]
Please re-open the issue with a reproduction in StackBlitz so we can dive into the issue and see what performance improvements are possible.

**Comment by jayakrishna-v** [comment]
@andrewseguin 

Here is the stackblitz reproduction - https://stackblitz.com/edit/angular-8wdr1m-q5qy7e

Just click a page number in the pagination and try to navigate among the pages. We can feel the delay up to 2 seconds. Actually in my application since I have 25 columns the delay is around 5 seconds. 
Although it is happening when the page size is higher like 100.

Please let us know your comments. 

I hope we can reopen this ticket now?

**Comment by benneq** [comment]
Have you tried using a custom Data Source? I'd guess that MatTableDataSource isn't the fastest choice.

**Comment by jayakrishna-v** [comment]
I'm not aware of custom data source. Can you please try to change it in the stackblitz.

**Comment by jayakrishna-v** [comment]
The same data is working blazing speed in jquery datatable (even when the page size is 100 and the number of columns is 35) in our old asp.net application.

**Comment by jayakrishna-v** [comment]
Do I need to create a new issue to reopen this?

**Comment by WizardPC** [comment]
Have you the same issue with a build prod ? Just to be sure.

**Comment by jayakrishna-v** [comment]
Yes. we are facing the issue in --prod build only.

**Comment by andrewseguin** [comment]
@jayakrishna-v I suspect that creating 800 tooltips for each render might be the reason ;)

Here's a speed comparison of using the table without tooltips on every cell: https://stackblitz.com/edit/angular-8wdr1m-6xjchu?file=app/table-pagination-example.html
