### ISSUE TITLE
Could we have the Mat-table support multiple paginators?

### ISSUE THREAD

**Issue by GWillits** [angular/material2#10476]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
You should be able to add mutiple paginators to your template to control the datatable view - likely scenario should be one at the top and one at the bottom.

#### What is the current behavior?
As far as I know the mat paginator will not support two instances.
So if you want to display a paginator at the top and bottom of the data table this can't be done using the out of the box behaviour of the mat paginator / data table. It looks like the data source class used by mat paginator and the mat table can only accept one paginator.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
I'll provide this if somebody deems it necessary. Let me know.

#### What is the use-case or motivation for changing an existing behavior?
This is a better user experience, especially if you have large data sets and want to display a large table view.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All.

#### Is there anything else we should know?

Happy to do a pull request if required but this is not urgent for us so if its on a roadmap we can wait.

**Comment by donroyco** [comment]
That's already possible. As @jelbourn stated in #8510:

>The paginator and the table don't know about each other at all. You can add however many paginators you'd like, so long as you handle the events coming out of them and update your datasource.

**Comment by GWillits** [comment]
Sorry I mustn't have explained myself properly - the issue is that the dataSource can only accept one paginator not the data table. So the dataSource (MatTableDataSource) is wired up to the paginator and the datSource gives the paginator its values. When the paginator is manipulated the dataSource presents the appropriate view of the underlying data to the table template. Only one can be wired up at any time.  
while it might be possible to add a second paginator but it would involve duplicating all this functionality.
It would be better if the dataSource could handle multiple paginators.

**Comment by jelbourn** [comment]
That data source is really intended to be a convenience / starting point. We expect people who want to to anything more complex than the basic client-side array sorting/pagination/search to imlpement their own.

**Comment by GWillits** [comment]
Ok. That's fine. I think the existing class could be refactored fairly easily. The thing is though once we do that we would have something other people might find useful. Would there be any scope then for treating it as a pull request or would it be a case of offering it up here as a third party resource?
Cheers, Garry.

**Comment by jelbourn** [comment]
It's not something we would want to built into the default data source since it's a bit out of the most common path.

**Comment by andrewseguin** [comment]
If you build out a good data source that handles multiple paginators, feel free to put it on this issue as a stackblitz so that others can find it and use it if they want. I'm sure there will be others that would love to use it. 

Otherwise if you want to really put it out there, you could publish it on npm.

Closing since we don't have any more action items here, but feel free to continue the discussion
