### ISSUE TITLE
Cannot animate custom overlay on destroy

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#10481]
Hi,
I have a custom overlay that displays a bunch of images, I use `:enter` and `:leave` animations on it but the exit animation does not play.

I use `overlay.dispose()` to close the overlay. even that `ngOnDestroy` of my custom component is logging, the animation is not playing.

I tried to search for the solution Material Dialog is using for this but I got lost, I couldn't find how it is working there.

#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

To play the exit animation

#### What is the current behavior?

The exit animation is not playing

#### What are the steps to reproduce?

Here is a [stackblitz](https://stackblitz.com/edit/angular-material2-issue-4ryix5?file=app%2Ftest%2Ftest.component.ts)

#### What is the use-case or motivation for changing an existing behavior?

Ability to animate a custom overlay

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: 5.2.0
Material: 5.2.4

#### Is there anything else we should know?

If I use `ngIf` to test enter and leave animation it works, but `overlay.dispose` does not animate

**Comment by crisbeto** [comment]
Disposing of the overlay will remove it immediately. If you want to animate it, you can use `detach` and then you can `dispose` once the animation is done. You can try looking at the Material source of some components which have exit animations:

* Dialog - https://github.com/angular/material2/tree/master/src/lib/dialog
* Menu - https://github.com/angular/material2/tree/master/src/lib/menu
* Select - https://github.com/angular/material2/tree/master/src/lib/select
* Snack bar - https://github.com/angular/material2/tree/master/src/lib/snack-bar

**Comment by MurhafSousli** [comment]
Thanks!
