### ISSUE TITLE
use md-button =>Template parse errors

### ISSUE THREAD

**Issue by lizardd** [angular/material2#1048]
# error
zone.js:461 Unhandled Promise rejection: Template parse errors:
Can't bind to 'md-ripple-trigger' since it isn't a known property of 'div'. ("*ngIf="isRippleEnabled()" class="md-button-ripple" [class.md-button-ripple-round]="isRoundButton()" [ERROR ->][md-ripple-trigger]="getHostElement()" [md-ripple-color]="isRoundButton() ? 'rgba(255, 255, 255, 0.2)"): MdButton@0:180
Can't bind to 'md-ripple-color' since it isn't a known property of 'div'. ("ton-ripple" [class.md-button-ripple-round]="isRoundButton()" [md-ripple-trigger]="getHostElement()" [ERROR ->][md-ripple-color]="isRoundButton() ? 'rgba(255, 255, 255, 0.2)' : ''" md-ripple-background-color="rgb"): MdButton@0:219 ; Zone: <root> ; Task: Promise.then ; Value: 
# additional
    the md-card no error,can use.
# component
import { Component } from '@angular/core';
import { MD_CARD_DIRECTIVES } from '@angular2-material/card'
import { MdButton } from '@angular2-material/button';
@Component({
  selector: 'my-app',
  template:`
<md-card>Basic card.</md-card><button md-raised-button color="primary">PRIMARY</button>
  `,
  directives:[MD_CARD_DIRECTIVES,MdButton],
})
export class AppComponent { }

# version
 "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-beta.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.5",
    "systemjs": "0.19.27",
    "core-js": "^2.4.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12",
    "angular2-in-memory-web-api": "0.0.15",
    "bootstrap": "^3.3.6",
    "@angular2-material/button":"v2.0.0-alpha.7-2", 
    "@angular2-material/button-toggle":"v2.0.0-alpha.7-2",
    "@angular2-material/card":"v2.0.0-alpha.7-2", 
    "@angular2-material/checkbox":"v2.0.0-alpha.7-2", 
    "@angular2-material/core":"v2.0.0-alpha.7-2",
    "@angular2-material/grid-list":"v2.0.0-alpha.7-2",
    "@angular2-material/icon":"v2.0.0-alpha.7-2",
    "@angular2-material/input":"v2.0.0-alpha.7-2", 
    "@angular2-material/list":"v2.0.0-alpha.7-2", 
    "@angular2-material/menu":"v2.0.0-alpha.7-2",
    "@angular2-material/progress-bar":"v2.0.0-alpha.7-2",
    "@angular2-material/progress-circle":"v2.0.0-alpha.7-2",
    "@angular2-material/radio":"v2.0.0-alpha.7-2", 
    "@angular2-material/sidenav":"v2.0.0-alpha.7-2",
    "@angular2-material/slider":"v2.0.0-alpha.7-2",
    "@angular2-material/slide-toggle":"v2.0.0-alpha.7-2",
    "@angular2-material/tabs":"v2.0.0-alpha.7-2",
    "@angular2-material/toolbar":"v2.0.0-alpha.7-2",
    "@angular2-material/tooltip":"v2.0.0-alpha.7-2"

**Comment by danielgek** [comment]
You need to switch to angular modules tha came with the rc5 and importante buttonModule
