### ISSUE TITLE
Why spacebar on checkbox and Enter key on select dropdown ?

### ISSUE THREAD

**Issue by WizardPC** [angular/material2#10485]
#### Bug, feature request, or proposal:

Proposal (having the same shortcut ?)

#### What is the expected behavior?

In a form i can easily navigate with keyboard :

1. Input : focus > write > tab
2. Select : arrows > enter > tab
3. Checkbox : enter > tab
4. ...

#### What is the current behavior?

1. Input : focus > write > tab
2. Select : arrows > enter > tab
3. Checkbox : enter > ... > enter > ... > ??? > roll on keyboard > **hit space** > OMG > tab
4. ...

#### What is the use-case or motivation for changing an existing behavior?

Having Enter key to select a value from dropdown and the Spacebar to check a checkbox, in the same form it's very disturbing ! In the begining i was thinking the checkbox haven't keyboard controls...

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest

#### Is there anything else we should know?

What is the reason behind this behavior ?

**Comment by PeS82** [comment]
My bet is:

- consistency with standard controls

&&

- Enter on checkbox would trigger form submit (in many cases) while Enter on select does not as it is "one level up" - it just selects option and closes list.

If you insist on Enter, I believe you are free to use `(keypress)` to catch Enter, cancel the event and toggle `checked` flag on checkbox. It would be confusing for many users though, IMHO.

**Comment by WizardPC** [comment]
It seems to be a standard : [https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_checkbox_role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_checkbox_role)

> The expected keyboard shortcut for activating a checkbox is the Space key.

**Comment by PeS82** [comment]
@WizardPC you could close the issue then, probably

**Comment by WizardPC** [comment]
@PeS82 yep

**Comment by benneq** [comment]
You could still implement your own checkbox and override the keydown behavior :)

**Comment by WizardPC** [comment]
Sure :) But from what i know now, it's seem to be the standard behavior, so i will stay with it.
