### ISSUE TITLE
set some dates as available (Enabled, these dates should be highlighted with different css) and rest of the dates should be in grey color css.

### ISSUE THREAD

**Issue by Purushothama-VS** [angular/material2#10490]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
set some dates as available (Enabled, these dates should be highlighted with different css) and rest of the dates should be in grey color css.

#### What is the current behavior?
Not able to set custom dates for selection. css changes are reflecting for all the dates

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
We need to have available dates for selection (which indicates the data)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0 , Material 5.0.0 , Windows, Typescript 2.4.2, All browsers

**Comment by julianobrasil** [comment]
Just to clarify: you want to call user attention to some of the displayed dates or just disable some of them?

**Comment by mmalerba** [comment]
You can disable dates with the `[matDaepickerFilter]` option. Here's an example that disables weekends: https://stackblitz.com/angular/vnnpxbkddny?file=app%2Fdatepicker-filter-example.html
