### ISSUE TITLE
CDK split screen

### ISSUE THREAD

**Issue by djleonskennedy** [angular/material2#10492]
#### Bug, feature request, or proposal:
[proposal]

#### What are the steps to reproduce?
https://plnkr.co/bxgcK29PNl9lexw6z6Ym

#### What is the use-case or motivation for changing an existing behavior?
Have several project that require split screen functionality, would be nice to see it in CDK.
example: https://github.com/wannabegeek/ng2-split-pane

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest

**Comment by djleonskennedy** [comment]
related: https://github.com/angular/material2/issues/7940

**Comment by josephperrott** [comment]
closing as duplicate of #7940

**Comment by djleonskennedy** [comment]
@josephperrott isn't duplicate, it's just related, i'm about CDK
