### ISSUE TITLE
form-field: outline gap calculated incorrectly with setTimeout

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#10498]
Repro courtesy of @fxck: https://stackblitz.com/edit/material2-textarea-outline-problem-in-dialog?file=app%2Fdialog.ts

Workaround is to call `updateOutlineGap` on the form field with the incorrect gap size. But ideally we could make it so the user doesn't have to do this

**Comment by fxck** [comment]
I have to hack around this in so many places, have you found out what could be causing it by any chance @mmalerba ?

**Comment by mmalerba** [comment]
Not yet, but I'll try to look into it sometime this week
