### ISSUE TITLE
What should we import in order to use `layout`?

### ISSUE THREAD

**Issue by sarbull** [angular/material2#10494]
#### Bug, feature request, or proposal:
Question: What should we import in order to use `layout`?

#### What is the expected behavior?
`import { MaterialModule } from @angular/material`

#### What is the current behavior?
Can't find what module contains the CSS/SCSS for layout attributes.

#### What is the use-case or motivation for changing an existing behavior?
I am very motivated to find the answer.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`@angular/cli@1.7.3, @angular5`

#### Is there anything else we should know?
I like material2.

![screen shot 2018-03-20 at 15 12 50](https://user-images.githubusercontent.com/1864112/37656611-36892f86-2c51-11e8-8c8a-5ee426f5cc47.png)

![screen shot 2018-03-20 at 15 14 33](https://user-images.githubusercontent.com/1864112/37656695-731a1fbe-2c51-11e8-8f9c-51232716c822.png)

**Comment by donroyco** [comment]
You should use Angular's Flex Layout to get started: https://github.com/angular/flex-layout

**Comment by sarbull** [comment]
Thanks.
