### ISSUE TITLE
Are we ready for use?

### ISSUE THREAD

**Issue by yellow1912** [angular/material2#105]
Hi all,

We are going to start re-coding our current website with material, and since we decide to start everything from scratch already we think we can also switch to angular2 but i wonder if material2 is ready for use at this point?

**Comment by benelliott** [comment]
From the first lines of the README:

"Build: failing"

"This is the home for the Angular team's Material Design components built on top of Angular 2. Things are in very early stages now- check back soon for more progress."

So probably not production ready...

**Comment by jelbourn** [comment]
We'll soon be publishing an alpha.0 to npm once a few more things are ready. The announcement will probably be on Twitter, so stay tuned!
