### ISSUE TITLE
mat-icon with svg does not work in MatDialog

### ISSUE THREAD

**Issue by crowmagnumb** [angular/material2#10505]
#### Bug, feature request, or proposal:
I switched to svg icons and now any mat-icons I have on dialogs do not read the svg from the registry.

#### What is the expected behavior?

svg icon should display in a dialog

#### What is the current behavior?

svg icon does not appear in dialog.

#### What are the steps to reproduce?
I created a repo here. https://github.com/crowmagnumb/svg-icon. Simply clone it, run ...

```
git clone git@github.com:crowmagnumb/svg-icon.git
cd svg-icon
yarn install
gulp pug
ng serve
```

**Comment by josephperrott** [comment]
Can you provide a reproduction in [stackblitz](https://goo.gl/wwnhMV)?

**Comment by crowmagnumb** [comment]
No. Because static assets do not work on [stackblitz](https://github.com/stackblitz/core/issues/72).

Please follow my simple instructions above. Thank you!

**Comment by crowmagnumb** [comment]
But here is the [stackblitz](https://stackblitz.com/edit/angular-material2-issue-gn2ubz) project I had tried to create if you want to see if you can make it work despite the known problem above. The date-picker in that blitz is just from an old issue that is now fixed. Just ignore it.

**Comment by josephperrott** [comment]
Closing as [this works as expected](https://stackblitz.com/edit/angular-material2-issue-nten8z?file=app/app.component.ts) as shown in this example.

**Comment by crowmagnumb** [comment]
Um, the least you could have done is tell me what you did to make it work which was to change the app component decorator from this
```
@Component({
  selector: 'material-app',
  templateUrl: 'app.component.html',
  viewProviders: [MatIconRegistry]
})
```
to
```
@Component({
  selector: 'material-app',
  templateUrl: 'app.component.html'
})
```
removing the ```viewProviders: [MatIconRegistry]``` direction. All examples and documentation says to do this.  If you add it back in you will see that the icon does not appear on the dialog.

So is it no longer required/suggested to set this as a viewProvider?
