### ISSUE TITLE
Menu context layout is located far from the more icon!

### ISSUE THREAD

**Issue by zbeedatm** [angular/material2#10512]
Please see this illustration:
![image](https://user-images.githubusercontent.com/26740851/37703767-6883cdda-2cff-11e8-8792-1f367f33cdcb.png)

**Sorry, adding style solved the problem:**
@import "~@angular/material/prebuilt-themes/indigo-pink.css";

![image](https://user-images.githubusercontent.com/26740851/37704414-593d75fe-2d01-11e8-8990-bdd14711c0f3.png)

But I still have some doubts:
how can I use a smaller icon (16x16)? where can I find the whole icons list to choose from?

Thanks.

**Comment by WizardPC** [comment]
You can find a list here : [https://material.io/icons/](https://material.io/icons/)

**Comment by jotatoledo** [comment]
This is neither a feature request or a bug report, please use gitter or SO for general support.

**Comment by crisbeto** [comment]
Please keep GitHub issues for bug rep...
