### ISSUE TITLE
"export 'inject' was not found

### ISSUE THREAD

**Issue by preslyel** [angular/material2#10511]
Hello, 
I have a problem with the last version angular/material.
After updating I've got this list of warnings 
```
WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1118:164-170 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1118:62-78 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1660:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1660:182-188 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1660:198-204 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1660:58-74 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1845:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1845:190-196 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1845:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
2274:140-146 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
2274:156-162 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
2274:54-70 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
270:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
270:168-174 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
270:58-74 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3175:170-176 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3175:193-199 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3175:64-80 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/bidi.es5.js
32:34-40 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3354:48-54 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3355:45-51 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3356:38-44 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
359:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
359:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/observers.es5.js
40:65-81 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/collections.es5.js
411:67-83 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
520:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
520:161-167 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
520:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
605:167-173 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
605:193-199 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
605:216-222 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
605:232-238 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
605:63-79 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/platform.es5.js
68:50-66 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/bidi.es5.js
70:146-152 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/bidi.es5.js
70:56-72 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
731:179-185 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
731:67-83 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
833:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
833:58-74 "export 'defineInjectable' was not found in '@angular/core'
```

and after that error in the console
```

Uncaught TypeError: Object(...) is not a function
    at main.dbf9396177fc4f9f28b0.bundle.js:1
    at Object.x35b (main.dbf9396177fc4f9f28b0.bundle.js:1)
    at t (inline.318b50c57b4eba3d437b.bundle.js:1)
    at Object.0 (main.dbf9396177fc4f9f28b0.bundle.js:1)
    at t (inline.318b50c57b4eba3d437b.bundle.js:1)
    at window.webpackJsonp (inline.318b50c57b4eba3d437b.bundle.js:1)
    at main.dbf9396177fc4f9f28b0.bundle.js:1
```
Monday 19.03 all was fine.

**Comment by briancvn** [comment]
Same issue

ng serve --hmr -e=hmr --sourcemaps --proxy-config proxy.config.json --host localhost

NOTICE Hot Module Replacement (HMR) is enabled for the dev server.
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
10% building modules 3/3 modules 0 active[HPM] Proxy created: /api -> http://localhost:9000/cms
[HPM] Subscribed to http-proxy events: [ 'error', 'close' ]
Date: 2018-03-21T12:54:13.778Z
Hash: 6496468f0573d28311b7
Time: 20485ms
chunk {Boot} Boot.chunk.js () 44.5 kB [rendered]
chunk {Boot.0} Boot.0.chunk.js () 16.5 kB [rendered]
chunk {inline} inline.bundle.js (inline) 31.1 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 774 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 3.88 MB [initial] [rendered]
chunk {scripts} scripts.bundle.js (scripts) 325 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 406 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 26.1 MB [initial] [rendered]

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1118:164-170 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1118:62-78 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1660:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1660:182-188 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1660:198-204 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1660:58-74 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1845:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1845:190-196 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1845:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
2274:140-146 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
2274:156-162 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
2274:54-70 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
270:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
270:168-174 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
270:58-74 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3175:170-176 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3175:193-199 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3175:64-80 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/bidi.es5.js
32:34-40 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3354:48-54 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3355:45-51 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3356:38-44 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
359:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
359:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/observers.es5.js
40:65-81 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/collections.es5.js
411:67-83 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
520:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
520:161-167 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
520:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
605:167-173 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
605:193-199 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
605:216-222 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
605:232-238 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
605:63-79 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/platform.es5.js
68:50-66 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/bidi.es5.js
70:146-152 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/bidi.es5.js
70:56-72 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
731:179-185 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
731:67-83 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
833:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
833:58-74 "export 'defineInjectable' was not found in '@angular/core'

webpack: Compiled with warnings.

**Comment by julianobrasil** [comment]
Could you post the `package.json`?

**Comment by preslyel** [comment]
"name": "settingscomponent",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "github:angular/material2-builds",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ncstate/sat-popover": "^1.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.2",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }

**Comment by julianobrasil** [comment]
Try to upgrade typescript: `"typescript": "2.7.2"`

**Comment by julianobrasil** [comment]
Try to upgrade typescript: `"typescript": "2.7.2"` and, after that, angular itself (which seems to be the problem as you're installing the latest builds of material). You'll need angular 6.0.0 beta.

**Comment by mibrito707** [comment]
@julianobrasil Thanks to your comment I realized the main issue (using the latest material's build). But even if your answer is more than valid, allow me to recommend to @preslyel not to upgrade angular core and/or typescript (since this can bring other problems) Instead, try to get lates estable release (v5.2.4) and reinstall the packages again. 
To get the latest stable version just change the package.json file from:
"@angular/cdk": "github:angular/cdk-builds"
"@angular/material": "github:angular/material2-builds"
to this:
"@angular/cdk": "^5.2.4"
"@angular/material": "^5.2.4"

and run npm install or yarn install

Hope this helps.

**Comment by preslyel** [comment]
Yes, it works, Thanks

**Comment by harishwordpress** [comment]
@mibrito707  Thank you so much saving my time.

**Comment by julianobrasil** [comment]
`@angular/material` 6 needs `@angular` 6.

**Comment by ashokmachineni** [comment]
I changed from "@angular/cdk": "^6.0.1" to "@angular/cdk": "^5.2.4",
and from "@angular/material": "^6.0.1", to "@angular/material": "^5.2.4" and restart my app it worked

**Comment by marmartins** [comment]
I changed the version from material like proposed by @ashokmachineni .

`npm install`

`ng build`

`npm start`

It worked. !

**Comment by vekkii** [comment]
npm i @angular/material@5.2.5 @angular/cdk@5.2.5 to revert back to the latest stable 5 version for angular material and angular cdk, and it will work

**Comment by Shripad03** [comment]
i am encountering same problem and tried with solution provided by @mibrito707 , still my app isnt working. I am getting compile with warning error.
[npm error.txt](https://github.com/angular/components/files/3156720/npm.error.txt)

**Comment by jagadishkt** [comment]
I am also faced same issue for me  it works **npm install @angular/cdk@7.0.0**

**Comment by Bktechmasala** [comment]
WARNING in ./node_modules/@angular/cdk/esm5/layout.es5.js 314:184-192 "export 'ɵɵinject' was not fou
solved in this video link https://youtu.be/mOjDoPpfTas
