### ISSUE TITLE
Slider toggle label position top and down

### ISSUE THREAD

**Issue by jothipandiyanjp** [angular/material2#10510]
https://material.angular.io/components/slide-toggle/api
https://material.angular.io/components/slide-toggle/overview

In the slide toggle, we have option to set label in front an back.
 ex: labelPosition: 'before' \| 'after' |  

Is there any way to set label position on top and bottom of the silder

**Comment by donroyco** [comment]
@jothipandiyanjp No, there's not. Also because that's a bad UX experience.

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
