### ISSUE TITLE
mat select can not choose option

### ISSUE THREAD

**Issue by minhquan2904** [angular/material2#10520]
#### Bug, feature request, or proposal:
TypeError: Cannot read property 'withHorizontalOrientation' of undefined
    at MatSelect.webpackJsonp.
I can not choose any options in mat select, and my browser's console shows this error

**Comment by donroyco** [comment]
Please check #9950

**Comment by crisbeto** [comment]
This is most likely due to a mismatch in your version of Material and the CDK. Make sure that you have the same version of `@angular/material` and `@angular/cdk`.
