### ISSUE TITLE
unable to use multiple select feature inside a popup

### ISSUE THREAD

**Issue by amirensit** [angular/material2#10525]
When i use multiple select outside the popup it works fine.
But when i inject it inside a popup, it does not work correctly.
Any idea ?
![image](https://user-images.githubusercontent.com/19771879/37763949-c4c0d9dc-2dc0-11e8-96ec-2d54891be5f7.png)

**Comment by narendrasinghrathore** [comment]
@amirensit Can you please share some code?

**Comment by willshowell** [comment]
This is probably z-index related. The mat-select is only compatible out of the box with mat-dialog.

See https://github.com/angular/material2/issues/8414

**Comment by crisbeto** [comment]
Check the `z-index` of your dialog. It should be below 1000 in order for it not to go above the Material overlays.
