### ISSUE TITLE
sidenav doesnt show until page animation completes

### ISSUE THREAD

**Issue by kevupton** [angular/material2#10527]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The sidenav is showing on as the page fades in

#### What is the current behavior?
When the page fades in the sidenav is transformed off to the side, but the content is still pushed.
This means there is an empty space where the nav should be. 
Only after the page fade in animation completes does the side nav suddenly get the style of transform 0, which causes it to instantly appear where it should be.

#### What are the steps to reproduce?
```html
<mat-sidenav-container class="vh100">

  <mat-sidenav class="sidenav" [opened]="true" align="start" [mode]="side" msIconSidenav #sidenav>
    <ms-sidenav></ms-sidenav>
  </mat-sidenav>

</mat-sidenav-container>
```

#### What is the use-case or motivation for changing an existing behavior?
Unuesable for animations

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.5
Material: 5.2.4
Typescript: 2.5.2
Chrome

#### Is there anything else we should know?
it is set to true, and if the animations are there it shows instantly. It is literally waiting for the animation to complete before it is displayed.

**Comment by kevupton** [comment]
As a fix I have added 
```html
<mat-sidenav class="sidenav" [opened]="sidenavOpen" align="start" [mode]="side" msIconSidenav #sidenav  [ngStyle]="{transform: sidenavOpen && 'translate3D(0, 0, 0)'}">
    <ms-sidenav></ms-sidenav>
  </mat-sidenav>

```

**Comment by josephperrott** [comment]
Can you provide a reproduction in [stackblitz](https://goo.gl/wwnhMV)?
