### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by shrutigramopadhye30** [angular/material2#10538]
#### What is the current behavior?: ngx-mask cannot be used with Angular Material.
I tried inserting '/' after date and month by calculating length.
But format is not getting inserted.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by tinayuangao** [comment]
See https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings for formatting

**Comment by shrutigramopadhye30** [comment]
My requirement is:

When user types a date in angular material date-picker, it should be auto formatted to MM/dd/yyyy.
For reference, https://jsdaddy.github.io/ngx-mask/ has a mask for date value.

But the same mask is not working with mat-datepicker.
Also I need to apply date validations after auto formatting.

Please guide me on this.
