### ISSUE TITLE
Bottom border on input fields often isn't displayed

### ISSUE THREAD

**Issue by drullo** [angular/material2#10532]
#### Bug, feature request, or proposal:
Inconsistent border behavior on input fields

#### What is the expected behavior?
Either all fields to have the bottom border all the time, or all fields to have no bottom border until focused.

#### What is the current behavior?
Input fields inside of mat-form-fields are often displayed without the expected bottom border and the behavior appears to be inconsistent.  If a single field is displayed, it seems to only have the bottom border when it gets focused.  If multiple fields are displayed (i.e. in a grid), some have the border and some do not.

The behavior *might* only happen in Chrome.  I have seen it on many of my apps.  But sometimes the behavior is different within the same app on different browsers.

#### What are the steps to reproduce?
Note: I am UNABLE to reproduce this in stackblitz.  But here's a (failed) attempt to reproduce it.
https://stackblitz.com/edit/angular-material2-issue-kgaa6e

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.8
Material 5.2.4
TypeScript 2.5.3
Windows 10
Chrome 64.0.3282.167

#### Is there anything else we should know?
I wish I had more useful information to provide at this time and it's unfortunate that I can't reproduce it in stackblitz.  Up until this point, I've just accepted the behavior, assuming that it was something that I'm doing wrong.  But I've now seen the problem often enough and have observed the inconsistencies on a repeated basis so I figured I'd submit an issue.

**Comment by julianobrasil** [comment]
Is it a cli project? If so, post the result of `ng -v` and your `package.json`

**Comment by Chan4077** [comment]
@drullo Could you update your Stackblitz link? Looks like you didn't fork the Stackblitz.

**Comment by drullo** [comment]
@Chan4077 you are correct, sorry.  I've updated my post to include an updated Stackblitz link.

**Comment by drullo** [comment]
@julianobrasil yes, all of my Angular projects are cli projects.  Package.json will differ for each one, however.

Here's is one that I'm working on right now, where I'm experiencing the issue:

**ng -v**
Angular CLI: 1.7.3
Node: 8.9.4
OS: win32 x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

**package.json**
{
  "name": "material-transfer",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.4",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@cleavelandprice/ngx-lib": "0.0.117",
    "angular2-jwt": "^0.2.3",
    "bootstrap": "^4.0.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "ng2-toastr": "^4.1.2",
    "ngx-barcode": "^0.2.4",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}

**Comment by julianobrasil** [comment]
Hum... I didn't notice anything strange with your `package.json`. You're mixing distinct libraries with lots of css (at least I noticed material and bootstrap), who knows.... try take bootstrap away if you can just to test for the bottom borders.

But as it's working fine at stackblitz, it doesn't look like a bug. In that case, a better place to get help is stackoverflow. If it's not a problem for you, share a GitHub repo link over there with your project.

**Comment by josephperrott** [comment]
Can you try to provide a reproduction?  As mentioned above, there is a few libs mixed here which could be playing a role.

**Comment by WizardPC** [comment]
i have encounter the same issue in my stackblitz yesterday, in put one, two, three inputs with `mat-form-field` and the 4th has no bottom border... But today is ok, on the same Stackblitz without modifying code. 

Perhaps it's a cache problem ?

**Comment by mmalerba** [comment]
@drullo are you sure that you're including a prebuilt theme or theme mixin? I think I've seen it look like that when I forget to include the theme CSS. (see https://material.angular.io/guide/theming)

**Comment by mmalerba** [comment]
If you are still able to reproduce this, feel free to open a new issue with a minimal reproduction repo for us to clone
