### ISSUE TITLE
mat-divider is not shown with align-items: center

### ISSUE THREAD

**Issue by darkbasic** [angular/material2#10546]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-divider should be shown, even with align-items: center

#### What is the current behavior?
mat-divider is not shown

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-enhzcm?file=app/app.component.html

Just remove center from fxLayoutAlign="flex-start center" and it will work.

**Comment by crisbeto** [comment]
The divider does work, but you need to define its height yourself. [Here's a working fork of your example](https://stackblitz.com/edit/angular-material2-issue-aautw4?file=app/app.component.html).
