### ISSUE TITLE
my-app-module.ts  does not exists.

### ISSUE THREAD

**Issue by onofremartins** [angular/material2#1054]
on get start, say to configure: my-app-module.ts with code:
```
@NgModule({
  imports: [MdButtonModule, MdCardModule],
  ...
})
```
but, this file does not exists on current ng cli new project.

where put this config please ?

**Comment by m0t0r** [comment]
@onofremartins `my-app-module.ts` is just an example. You should have `app.module.ts` file where you configure your app module. Make sure you run Angular RC5, if you don't see [migration guide](https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html).

**Comment by jelbourn** [comment]
What @m0t0r said.

**Comment by onofremartins** [comment]
ok, thanks.
