### ISSUE TITLE
Material CSS included after component style causes cascading problems

### ISSUE THREAD

**Issue by MatthiasKunnen** [angular/material2#10548]
#### Bug, feature request, or proposal:
Material CSS is loaded after the component's style which makes it more specific. This becomes an issue when using ng-deep to style child components.

#### What is the expected behavior?
The Material CSS should be loaded before the component's style.

#### What is the current behavior?
The Material CSS is loaded after the component's style.

#### What are the steps to reproduce?
Simple ng-deep example: https://stackblitz.com/edit/angular-material2-issue-mkwnum?file=app%2Fapp.component.ts

This behavior does not occur when a material 2 element is used before because this (sort of) preloads the style.

I encountered this in a scenario where depending on a user's login status, a mat-button would be present in a header component. If the user was logged in, the mat-button would make sure the style was loaded before my routed component's style. This made my routed component's style have higher specificity and be applied. When the user is not logged in, the material style is loaded after the component and stops the routed component's style from being applied.
Minimum reproduction of this: https://stackblitz.com/edit/angular-material2-issue-8rmpmc.

#### What is the use-case or motivation for changing an existing behavior?
To prevent issues with specificity of rules.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 1.7.2
Node: 9.2.0
OS: linux x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.2
@angular/flex-layout: 5.0.0-beta.13
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

**Comment by MatthiasKunnen** [comment]
A potential solution might be ordering the style according to their respective view encapsulation. If the style were to be included in the following order: none, native, emulated; then this problem would not occur.  This is not a material2 solution but I'm willing to take this to the respective repository if this seems like a good idea. Any thoughts?

**Comment by josephperrott** [comment]
Closing. As you noted, this is something that is handled at the platform level and Material does not have any control over.  You will need to open an issue in [angular/angular](https://github.com/angular/angular/issues/new) to have the conversation there.
