### ISSUE TITLE
MatDialog Animation Options

### ISSUE THREAD

**Issue by mswilson4040** [angular/material2#10544]
#### Bug, feature request, or proposal:

Feature Request / Documentation Request / Information

#### What is the expected behavior?

The MatDialog Component currently has built in animation. When opening the MatDialog, it flyes out from the bottom to the center of the screen (or where your position is). I am having a lot of trouble finding anything out there that shows me how to change the MatDialog Animation. For example, I want to dock my MatDialog to the right of the screen and have the animation fly the dialog out from the right rather than from the bottom of the screen.

I do not see any documentation/threads/options in the configuration that allow this behavior. It does seem like the MatSideNav has this functionality. However, MatSideNav is not preferred here since I would end up with a MatSideNav within a MatSideNav.

#### What is the current behavior?

The only option for animating the 'flyout position' of the MatDialog animation is from the bottom

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

Example stack blitz: https://stackblitz.com/edit/angular-wbuvsn?file=app/dialog-overview-example.ts

#### What is the use-case or motivation for changing an existing behavior?

Better UX/flexibility for MatDialog

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All

**Comment by josephperrott** [comment]
This control is possible by using the dialog from the cdk (currently in cdk-experimental).  Because this animation is not part of the Material spec, it is highly unlikely that we will create this animation in the Material Dialog.

**Comment by mswilson4040** [comment]
@josephperrott Do you have an issue I can follow? If so, this can probably be closed out and tracked in the other.

**Comment by lppedd** [comment]
This should be documented, indeed! Thank you guys!

**Comment by yinonov** [comment]
why is this closed? is there a way to customize the animation for dialogs? I would love to use dialogs and make them look & animate as drawers

**Comment by kousherAlam** [comment]
is there any improvement ???
