### ISSUE TITLE
sideNav: rename md-sidenav-layout 

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material2#1055]
#### Bug, feature request, or proposal:

Current implementation uses `md-sidenav-layout` as the smart container for content and md-sidenav components. The **`-layout`** suffix is ambiguous and conflicts with names and concepts for the Material Layouts API and features.
#### What is the expected behavior?

Please rename to `md-sidenav-container`
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
#### What is the use-case or motivation for changing an existing behavior?

The **`-layout`** suffix is ambiguous and conflicts with names and concepts for the Material Layouts API and features.

**Comment by jelbourn** [comment]
@hansl @kara any thoughts on this? I'm not convinced on the name change since we don't have any layout concepts in material2 for this to conflict with. I like the name now because I see it as more accurately capturing the intent of setting up a sidenav layout for your app (sidenav + main content area).

**Comment by hansl** [comment]
I'd rather have a proper layout engine in material2 and get rid of `md-sidenav-layout`. In the meantime, I agree with Thomas that `container` is more proper.

**Comment by ThomasBurleson** [comment]
@jelbourn - Also Angular Layouts is in active development and will be ready in the fall for Angular 2 apps and Angular Material 2.

**Comment by jelbourn** [comment]
@mmalerba I want to follow up on this with some more discussion

**Comment by mmalerba** [comment]
Agreed with Thomas & Hans that container > layout. I'd also like to switch sidenav to drawer. A sidenav is only one possible use of the drawer component, so I propose: `md-drawer-container` and `md-drawer`

**Comment by mmalerba** [comment]
renamed to md-sidenav-container in #2183
