### ISSUE TITLE
[Slide-toogle] Font size is different from others components (eg : checkbox)

### ISSUE THREAD

**Issue by WizardPC** [angular/material2#10552]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Slide-toggle label as the same font size of a checkbox label

#### What is the current behavior?

Slide-toggle label as a specific font size

#### What are the steps to reproduce?

[https://stackblitz.com/edit/angular-yllug9](https://stackblitz.com/edit/angular-yllug9)

#### What is the use-case or motivation for changing an existing behavior?

Labels of differents sizes are not pretty, especially when you have a mix of checkbox and slide-toggle next to each other...

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

See SB

**Comment by raygervais** [comment]
I'd like to correct this. I do agree that differing sizes of form elements text can be obtrusive when not used properly. It appears in the spec that the font is the same, so I'd say this is a bug: https://material.io/guidelines/components/selection-controls.html#selection-controls-radio-button

**Comment by raygervais** [comment]
After doing some research, it appears that the slider-toggle component makes it's text content follow the `body-1` style, which uses 14px. This means that either it is following proper conventions and the check / radio components are not, or it should not be following the `body-1` styling for it's content. 

Opinions? 

https://github.com/angular/material2/blob/master/src/lib/core/typography/_typography.scss#L33

My guess is that it's supposed to also use the `input` class instead.
