### ISSUE TITLE
Button-toggle is not clickable

### ISSUE THREAD

**Issue by theunreal** [angular/material2#10558]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Button toggle should be clickable all across the mat-button-toggle element

#### What is the current behavior?
it's clickable only inside the <label> attribute of the button.

#### What are the steps to reproduce?
1. Import bootstrap 4 in your app:

`<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"`>

2. Place `button-toggle-group `with the `vertical` flag
![image](https://user-images.githubusercontent.com/6171883/37872418-201bd77c-3010-11e8-95ea-a8b04fd87f33.png)

#### What is the use-case or motivation for changing an existing behavior?
Improved UX

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular material 5.2.3

**Comment by crisbeto** [comment]
How are you stacking the toggles? Are you using the `vertical` attribute or are you using your own custom styling. I wasn't able to [reproduce your issue here](https://stackblitz.com/edit/angular-kq916e?file=app/button-toggle-exclusive-example.html).

**Comment by theunreal** [comment]
@crisbeto I reproduced it by adding bootstrap to the application

in the index.html:
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">

It seems like this issue happens when using Bootstrap 4 with Angular Material.

**Comment by crisbeto** [comment]
In general we don't fix issues in Material that are introduced by conflicting styles from other libraries. In your case you can fix the issue by adding this to your CSS:

```css
.mat-button-toggle-label {
  display: inline;
}
```
