### ISSUE TITLE
Error upgrading StackBlitz app to 6.0.0-beta.5

### ISSUE THREAD

**Issue by MarkHerhold** [angular/material2#10553]
#### Bug, feature request, or proposal:
Bug. Material2's StackBlitz app does not work after upgrading dependencies to 6.0.0-beta.5.

Specifically, I updated:
- @angular/ctd@6.0.0-beta.5
- @angular/material@6.0.0-beta.5

#### What is the expected behavior?
Working sample app in StackBlitz.

#### What is the current behavior?

```
AppComponent.html:1 ERROR Error: StaticInjectorError(AppModule)[MatSlideToggle -> Platform]: 
  StaticInjectorError(Platform: core)[MatSlideToggle -> Platform]: 
    NullInjectorError: No provider for Platform!
    at _NullInjector.get (injector.js:39)
    at resolveToken (injector.js:413)
    at tryResolveToken (injector.js:355)
    at StaticInjector.get (injector.js:189)
    at resolveToken (injector.js:413)
    at tryResolveToken (injector.js:355)
    at StaticInjector.get (injector.js:189)
    at resolveNgModuleDep (ng_module.js:145)
    at NgModuleRef_.get (refs.js:1059)
    at resolveDep (provider.js:462)
```

#### What are the steps to reproduce?

Please see my fork: https://angular-material2-6beta5-injector.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?

I am experiencing a similar error updating my application to use @angular/ctd@6.0.0-beta.5, @angular/material@6.0.0-beta.5

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Whatever is running on StackBlitz, not sure how to check.

**Comment by jmcgoldrick** [comment]
This commit #10507 switch to using "scoped injectables" which is probably why you're having issues, make sure the core angular packages rc.0 or later

**Comment by MarkHerhold** [comment]
Thanks, rc.0 was the issue!
