### ISSUE TITLE
mat-form-field: no way to set to pristine and get rid of the red outline after focus and blur

### ISSUE THREAD

**Issue by fxck** [angular/material2#10569]
Feature request, bug possibly.

Use case: I have a stepper with a required input in the first step, but this first step that can be skipped.. when I open a dialog with this stepper, input gets automatically focused (or user focuses it, doesn't really matter), I then proceed to skip the step, then I decide to go back to the first step and the input already has the red outline, despite me setting the form control to pristine and untouched.

Ideally I'd want it to set back to pristine when switching steps.

cc @mmalerba

**Comment by fxck** [comment]
looks like it works (at least in repro https://stackblitz.com/edit/reset-form-m2?file=app/app.component.ts will investigate further

**Comment by nickwinger** [comment]
this is still not working...
