### ISSUE TITLE
[Select] Overlay position wrong while at bottom of screen

### ISSUE THREAD

**Issue by MarcHonegger** [angular/material2#10560]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The select-overlay (available options) should position itself correctly.

#### What is the current behavior?
The select-overlay sometimes goes out of screen or completely separates from the input field.

#### What are the steps to reproduce?
1. Have a select which is located near the bottom / end of the screen
2. Select the first value
3. Select the last value
4. Open the select again

StackBlitz: https://select-position-bottom.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
It looks out of place and happens during normal use. This happens in my case because I have a select at the end of a form.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
At least Firefox and Edge are affected

**Comment by crisbeto** [comment]
Should be fixed in 6.0.0-beta.5 by 1dd8a27.

**Comment by eBitzu** [comment]
I can say that I have 6.4.7 and it's still broken
