### ISSUE TITLE
Getting build error with web-pack 0.9.2

### ISSUE THREAD

**Issue by erjdriver** [angular/material2#10577]
I'm migrating my app from 3.3 to 3.4 and looks like I've got to use the new web-pack.

It's core Nativescript app.

Followed the steps in [Migrating to 0.9.0](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade)

Getting the following error:

`ERROR in NativeScriptSnapshot. Snapshot generation failed!
Target architecture: arm64-v8a
 Script run failed in <embedded>@36:36368
ReferenceError: com is not defined`

Getting this error in the beginning also - but gets past it

`UNMET PEER DEPENDENCY webpack@^2.0.0 || ^3.0.0`

These are the commands I issue to web-pack

npm install --save-dev nativescript-dev-webpack@0.9.2
npm install
./node_modules/.bin/update-ns-webpack --configs --deps
npm install
tns prepare android
tns build android --bundle --env.snapshot --env.uglify --release --key-store-path ../my-release-key-$1.keystore --key-store-password xxx --key-store-alias yyy --key-store-alias-password zzz

**Comment by josephperrott** [comment]
Closing as it looks like you are needing to file an issue with web-pack.
