### ISSUE TITLE
FEATURE REQUEST: styleUrls for dialog components

### ISSUE THREAD

**Issue by eltharynd** [angular/material2#10570]
Feature request: Styleable MatDialogs

@Component in a component used for MatDialogs should accept and apply styleUrls as any other component

Currently the StyleUrls get ignored.. 
The only way i found to style all instances of a dialog on a separate file is to add that style sheet to 
angular-cli.json (so to the whole project) and then apply a class when opening the dialog

This is not a big issue but just having the dialog apply that style sheet automatically like any otehr component would be much better imo...

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
