### ISSUE TITLE
tooltip: ComponentResolver is deprecated for dynamic compilation

### ISSUE THREAD

**Issue by rbaumi** [angular/material2#1057]
Using Angular 2.0.0-RC.5 and angular2-material alpha.7.2, when mouseover over the element build like this:

```
<md-icon md-tooltip="{{ 'EMAIL_EMPTY_WARNING' | translate }}"
   tooltip-position="before"
   *ngIf="loginForm.controls.email.touched && loginForm.controls.email.errors?.required"
   fontSet="fa"
   fontIcon="fa-exclamation-triangle">
</md-icon>
```

I get a warn in console:

> ComponentResolver is deprecated for dynamic compilation. Use ComponentFactoryResolver together with @NgModule/@Component.entryComponents or ANALYZE_FOR_ENTRY_COMPONENTS provider instead. For runtime compile only, you can also use Compiler.compileComponentSync/Async.

I guess this is related to the md-tooltip directive as it appears after mouseover. Can anyone explain me what is this message exacly about and why it appears?

Thanks!

**Comment by jelbourn** [comment]
Already removed on master (2411c24a37fb56ac28607b3611d38aead9229629).

**Comment by RAlfoeldi** [comment]
This still appears in alpha.7-3.

**Comment by jelbourn** [comment]
Yeah, alpha.7-3 only contained one additional commit from 7-2 so that material would stop erroring with the closure compiler.

**Comment by vapits** [comment]
This is still here in `alpa.7-4`
