### ISSUE TITLE
mat-form-field: label doesn't reset when reseting form with value selected with autocomplete

### ISSUE THREAD

**Issue by fxck** [angular/material2#10576]
#### Bug

![](https://media.giphy.com/media/26uauwT05K77Ojvy2g/giphy.gif)

repro: https://stackblitz.com/edit/potential-material2-outline-bug?file=app/app.component.ts

for some reason it behaves even worse in my app

![](https://media.giphy.com/media/5hgRSECmnbydS9ieOW/giphy.gif)

cc @mmalerba

**Comment by mmalerba** [comment]
It looks like you need to call `reset()` on the native element to reset Chrome's autofill state: https://stackblitz.com/edit/potential-material2-outline-bug-3oz5ub?file=app/app.component.ts

If anything it looks like potentially a bug in Angular forms, though they may have a good reason for not calling the native `reset`
