### ISSUE TITLE
SSR Error: inject() must be called from an injection context

### ISSUE THREAD

**Issue by patrickmichalina** [angular/material2#10586]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Render a mat-primary-button

#### What is the current behavior?
Fails to render on server, generating a ` Error: inject() must be called from an injection context` error

#### What are the steps to reproduce?
Add material module to this repo and add a button to a random page

https://github.com/patrickmichalina/fusing-angular

Works fine on client, not server.

#### What is the use-case or motivation for changing an existing behavior?
To work on the server

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "6.0.0-rc.0",
    "@angular/cdk": "^6.0.0-beta.5",
    "@angular/common": "6.0.0-rc.0",
    "@angular/compiler": "6.0.0-rc.0",
    "@angular/compiler-cli": "6.0.0-rc.0",
    "@angular/core": "6.0.0-rc.0",
    "@angular/forms": "6.0.0-rc.0",
    "@angular/http": "6.0.0-rc.0",
    "@angular/material": "^6.0.0-beta.5",
    "@angular/platform-browser": "6.0.0-rc.0",
    "@angular/platform-browser-dynamic": "6.0.0-rc.0",
    "@angular/platform-server": "6.0.0-rc.0",
    "@angular/router": "6.0.0-rc.0",
    "@angular/service-worker": "6.0.0-rc.0",

Node 9.9.0

**Comment by josephperrott** [comment]
This is likely an issue with your setup as we have a SSR test app which successfully builds and serves.  Additionally, `inject`/the `Injector` are both not directly used in `MatButton`. 

Without more context of the Error stack there is not much more I can reason about it at this point.

**Comment by patrickmichalina** [comment]
@josephperrott OK I can try to figure it out, but FYI, mat v5.1.1 works fine.

**Comment by julianobrasil** [comment]
@patrickmichalina, there are somethings you can check:

1. have you deleted `node_modules` folder and `package-lock.json` before `npm install`?
2. have you upgraded `rxjs` to `6.0.0-beta.1`?

**Comment by patrickmichalina** [comment]
Sorry for the poor formatting but I have the following error when running rc-0. Version 5.1.1 is the last version of material I can get to run well in universal.

```js
,"msg":"{ Error: inject() must be called from an injection context\n    at Object.inject (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/di/injector.js:373:15)\n    at Directionality_Factory (/Users/Patrick/Repos/fusing-angular/node_modules/@angular/cdk/bundles/cdk-bidi.umd.js:73:157)\n    at _callFactory (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/ng_module.js:162:20)\n    at _createProviderInstance$1 (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/ng_module.js:128:26)\n    at resolveNgModuleDep (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/ng_module.js:88:17)\n    at NgModuleRef_.get (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/refs.js:484:16)\n    at resolveDep (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/provider.js:353:45)\n    at createClass (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/provider.js:233:32)\n    at createDirectiveInstance (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/provider.js:110:20)\n    at createViewNodes (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/view.js:275:36)\n    at createEmbeddedView (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/view.js:183:5)\n    at callWithDebugContext (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/services.js:614:25)\n    at Object.debugCreateEmbeddedView [as createEmbeddedView] (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/services.js:115:12)\n    at TemplateRef_.createEmbeddedView (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/refs.js:321:38)\n    at ViewContainerRef_.createEmbeddedView (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/core/core.esm5/packages/core/src/view/refs.js:186:35)\n    at NgIf._updateView (/execroot/angular/bazel-out/darwin-fastbuild/bin/packages/common/common.esm5/packages/common/src/directives/ng_if.js:143:45)\n  ngDebugContext: \n   DebugContext_ {\n     view: \n      { def: [Object],\n        parent: [Object],\n        viewContainerParent: null,\n        parentNodeDef: [Object],\n        context: [NgIfContext],\n        component: [AppComponent],\n        nodes: [Array],\n        state: 13,\n        root: [Object],\n        renderer: [DebugRenderer2],\n        oldValues: [Array],\n        disposables: [Array],\n        initIndex: -1 },\n     nodeIndex: 1,\n     nodeDef: \n      { nodeIndex: 1,\n        parent: [Object],\n        renderParent: [Object],\n        bindingIndex: 1,\n        outputIndex: 0,\n        checkIndex: 1,\n        flags: 1490944,\n        childFlags: 872415232,\n        directChildFlags: 872415232,\n        childMatchedQueries: 0,\n        matchedQueries: {},\n        matchedQueryIds: 0,\n        references: {},\n        ngContentIndex: -1,\n        childCount: 2,\n        bindings: [],\n        bindingFlags: 0,\n        outputs: [],\n        element: null,\n        provider: [Object],\n        text: null,\n        query: null,\n        ngContent: null },\n     elDef: \n      { nodeIndex: 0,\n        parent: null,\n        renderParent: null,\n        bindingIndex: 0,\n        outputIndex: 0,\n        checkIndex: 0,\n        flags: 33554433,\n        childFlags: 926924803,\n        directChildFlags: 35045377,\n        childMatchedQueries: 10,\n        matchedQueries: {},\n        matchedQueryIds: 0,\n        references: {},\n        ngContentIndex: null,\n        childCount: 70,\n        bindings: [Array],\n        bindingFlags: 2,\n        outputs: [],\n        element: [Object],\n        provider: null,\n        text: null,\n        query: null,\n        ngContent: null },\n     elView: \n      { def: [Object],\n        parent: [Object],\n        viewContainerParent: null,\n        parentNodeDef: [Object],\n        context: [NgIfContext],\n        component: [AppComponent],\n        nodes: [Array],\n        state: 13,\n        root: [Object],\n        renderer: [DebugRenderer2],\n        oldValues: [Array],\n        disposables: [Array],\n        initIndex: -1 } },\n  ngErrorLogger: [Function: bound ] }","time":"2018-04-01T06:43:17.898Z","v":0}
```

**Comment by leo6104** [comment]
I got same error on SSR. 

```
@angular/cdk: 6.0.0-rc.0
@angular/cli: 6.0.0-beta.8
@angular/material: 6.0.0-rc.0
@angular-devkit/architect: 0.0.9
@angular-devkit/build-angular: 0.0.9
@angular-devkit/build-optimizer: 0.4.8
@angular-devkit/core: 0.4.8
@angular-devkit/schematics: 0.4.8
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.8
@schematics/angular: 0.4.8
@schematics/update: 0.4.8
typescript: 2.7.2
webpack-cli: 2.0.13
webpack: 4.1.0
```

**Comment by julianobrasil** [comment]
I had problems with angular/cli beta.8. I'm currently using beta.5.

**Comment by vikerman** [comment]
This somehow seems to happen on second SSR render call in an example app I'm working with. Debugging...

**Comment by vikerman** [comment]
This should be fixed with the next Angular 6 RC

**Comment by patrickmichalina** [comment]
@vikerman thank you!

**Comment by josephperrott** [comment]
Closing as it was fixed by https://github.com/angular/angular/pull/23148

**Comment by enyachoke** [comment]
Error: inject() must be called from an injection context Stack trace: inject@http://localhost:8000/vendor.js:47579:15 ViewportRuler_Factory@http://localhost:8000/vendor.js:187376:214 _callFactory@http://localhost:8000/vendor.js:19452:20 _createProviderInstance$1@http://localhost:8000/vendor.js:19410:26 resolveNgModuleDep@http://localhost:8000/vendor.js:19388:17 NgModuleRef_.prototype.get@http://localhost:8000/vendor.js:20084:16 resolveDep@http://localhost:8000/vendor.js:20449:12 createClass@http://localhost:8000/vendor.js:20329:32 createDirectiveInstance@http://localhost:8000/vendor.js:20206:20 createViewNodes@http://localhost:8000/vendor.js:21428:36 callViewAction@http://localhost:8000/vendor.js:21744:13 execComponentViewsAction@http://localhost:8000/vendor.js:21663:13 createViewNodes@http://localhost:8000/vendor.js:21456:5 createEmbeddedView@http://localhost:8000/vendor.js:21336:5 callWithDebugContext@http://localhost:8000/vendor.js:22377:22 debugCreateEmbeddedView@http://localhost:8000/vendor.js:21878:12 TemplateRef_.prototype.createEmbeddedView@http://localhost:8000/vendor.js:19921:29 ViewContainerRef_.prototype.createEmbeddedView@http://localhost:8000/vendor.js:19787:23 NgIf.prototype._updateView@http://localhost:8000/vendor.js:39846:25 set@http://localhost:8000/vendor.js:39814:13 updateProp@http://localhost:8000/vendor.js:20476:5 checkAndUpdateDirectiveInline@http://localhost:8000/vendor.js:20227:19 checkAndUpdateNodeInline@http://localhost:8000/vendor.js:21536:20 checkAndUpdateNode@http://localhost:8000/vendor.js:21498:16 debugCheckAndUpdateNode@http://localhost:8000/vendor.js:22135:19 debugCheckDirectivesFn@http://localhost:8000/vendor.js:22095:13 View_FormRendererComponent_0/<@ng:///FormEntryModule/FormRendererComponent.ngfactory.js:1289:5 debugUpdateDirectives@http://localhost:8000/vendor.js:22087:12 checkAndUpdateView@http://localhost:8000/vendor.js:21480:5 callViewAction@http://localhost:8000/vendor.js:21721:21 execComponentViewsAction@http://localhost:8000/vendor.js:21663:13 checkAndUpdateView@http://localhost:8000/vendor.js:21486:5 callViewAction@http://localhost:8000/vendor.js:21721:21 execEmbeddedViewsAction@http://localhost:8000/vendor.js:21684:17 checkAndUpdateView@http://localhost:8000/vendor.js:21481:5 callViewAction@http://localhost:8000/vendor.js:21721:21 execComponentViewsAction@http://localhost:8000/vendor.js:21663:13 checkAndUpdateView@http://localhost:8000/vendor.js:21486:5 callWithDebugContext@http://localhost:8000/vendor.js:22377:22 debugCheckAndUpdateView@http://localhost:8000/vendor.js:22055:12 ViewRef_.prototype.detectChanges@http://localhost:8000/vendor.js:19865:13 ApplicationRef.prototype.tick/<@http://localhost:8000/vendor.js:15259:58 ApplicationRef.prototype.tick@http://localhost:8000/vendor.js:15259:13 ApplicationRef.prototype._loadComponent@http://localhost:8000/vendor.js:15309:9 ApplicationRef.prototype.bootstrap@http://localhost:8000/vendor.js:15215:9 PlatformRef.prototype._moduleDoBootstrap/<@http://localhost:8000/vendor.js:14969:74 PlatformRef.prototype._moduleDoBootstrap@http://localhost:8000/vendor.js:14969:13 PlatformRef.prototype.bootstrapModuleFactory/</</<@http://localhost:8000/vendor.js:14906:21 ZoneDelegate.prototype.invoke@http://localhost:8000/polyfills.js:17499:17 onInvoke@http://localhost:8000/vendor.js:14235:24 ZoneDelegate.prototype.invoke@http://localhost:8000/polyfills.js:17498:17 Zone.prototype.run@http://localhost:8000/polyfills.js:17249:24 scheduleResolveOrReject/<@http://localhost:8000/polyfills.js:17939:52 ZoneDelegate.prototype.invokeTask@http://localhost:8000/polyfills.js:17532:17 onInvokeTask@http://localhost:8000/vendor.js:14226:24 ZoneDelegate.prototype.invokeTask@http://localhost:8000/polyfills.js:17531:17 Zone.prototype.runTask@http://localhost:8000/polyfills.js:17299:28 drainMicroTaskQueue@http://localhost:8000/polyfills.js:17703:25 
But my case this is clientside
