### ISSUE TITLE
[MatButtonToggle] allow property type to be an @Input

### ISSUE THREAD

**Issue by seedy** [angular/material2#10585]
#### Bug, feature request, or proposal:
Currently, mat-button-toggle requires a mat-button-toggle-group to define its behaviour between `checkbox`and `radio`.
It would be much easier to allow users to use an @Input() property for the same behaviour, without requiring a toggle group.

#### What is the expected behavior?
I got a very exotic use case where I am connecting a toggle group and its list of toggle buttons to a single toggle button which is not part of the group.
I sorted myself out pretty well without using two button groups.
Have a look at my stackblitz to understand.

#### What is the current behavior?
When looking at MatButtonToggle class, I found a public property `_type` which allows manual setup of this behaviour.
Therefore I can programatically setup my mat-button-toggle, without needing a group.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-1jptz2
PS : the example got a bug I can't reproduce in my own environment...

#### What is the use-case or motivation for changing an existing behavior?
Friendlier API.

**Comment by tinayuangao** [comment]
@seedy after recent refactor of button toggle #9191 you should be able to use two button toggle group without any workaround.

Following code works without modifying the type of button toggle:
```html
<mat-button-toggle-group [(ngModel)]="selected">
  <mat-button-toggle value="left" tabindex="-1">
    <mat-icon>format_align_left</mat-icon>
  </mat-button-toggle>
  <mat-button-toggle value="center" tabindex="-1">
    <mat-icon>format_align_center</mat-icon>
  </mat-button-toggle>
  <mat-button-toggle value="right" tabindex="-1">
    <mat-icon>format_align_right</mat-icon>
  </mat-button-toggle>
  <mat-button-toggle value="justify" disabled tabindex="-1">
    <mat-icon>format_align_justify</mat-icon>
  </mat-button-toggle>
</mat-button-toggle-group>
<mat-button-toggle-group [(ngModel)]="selected" >
  <mat-button-toggle value="None" tabindex="-1">
    <mat-icon>format_clear</mat-icon>
  </mat-button-toggle>
</mat-button-toggle-group>
```
```ts
  public selected = 'center';
```

**Comment by seedy** [comment]
Released : https://github.com/angular/material2/tree/6.0.0-beta-5
