### ISSUE TITLE
Material Stepper icon change

### ISSUE THREAD

**Issue by AnandMani1** [angular/material2#10584]
#### Bug, feature request, or proposal:

feature request
#### What is the expected behavior?
need to the stepper index number to alphabetic

#### What is the current behavior?
index is coming only in numbers.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
for sub-steps i need to change the numbers into alphabetics.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular 5,  material-5.2.4
#### Is there anything else we should know?
![step_issue](https://user-images.githubusercontent.com/29225413/37965383-8a416332-31e2-11e8-87d3-b71cd4dc67ec.png)

**Comment by crisbeto** [comment]
This will be possible once https://github.com/angular/material2/pull/10516 is released.
