### ISSUE TITLE
Can't set class of mat-sidenav

### ISSUE THREAD

**Issue by e11en** [angular/material2#10597]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To behave like it would without the use of `[class]`.
![image](https://user-images.githubusercontent.com/855939/38028371-0907c322-3293-11e8-9bae-b3c61958d980.png)

#### What is the current behavior?
As soon as the `[class]` attribute is used then the sidenav will no longer be on the side but above the sidenav-content.

![image](https://user-images.githubusercontent.com/855939/38028357-fc1539e2-3292-11e8-9229-1fe7302d8dde.png)

#### What are the steps to reproduce?
https://angular-material2-issue-yjhfbk.stackblitz.io
https://stackblitz.com/edit/angular-material2-issue-yjhfbk

#### What is the use-case or motivation for changing an existing behavior?
I would like to be able to set a class so I can change the width of the menu.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on:
Angular CLI: 1.6.5
Node: 8.9.1
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.3
@angular/cli: 1.6.5
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.7.1
webpack: 3.10.0

#### Is there anything else we should know?
Nope

**Comment by crisbeto** [comment]
When you bind something as `[class]`, it'll overwrite all of the class bindings from Material. To avoid it, you can rewrite your binding to `[class.mini]="menuIsMini"`.
