### ISSUE TITLE
MatAutocompleteTrigger return undefined

### ISSUE THREAD

**Issue by duyleduc** [angular/material2#10598]
Hello,

I tried to get the component matautocompletetrigger in my autocomplete but it always returns undefined

Here are my codes:
.hmtl 

`   <mat-form-field style="width: 500px;">
              <input matInput class="search-field" [formControl]="customerAutoCompleteCtrl" #autoCompleteInput
                     placeholder="Rechercher un client par code ou raison sociale" i18n-placeholder="@@report.label.searchCustomer" [matAutocomplete]="autocomplete">
              <mat-autocomplete #autocomplete="matAutocomplete" [displayWith]="displayCodeCompany" >
                <mat-option *ngFor="let customer of customers" [value]="customer">
                  {{ customer.code + ' ' + customer.companyName }}
                  <br/>
                  <span class="city">{{ customer.city }}</span>
                </mat-option>
              </mat-autocomplete>
            </mat-form-field>`

and in my component.
`@ViewChild(MatAutocompleteTrigger) trigger: MatAutocompleteTrigger`

Thanks for your help :)

**Comment by donroyco** [comment]
Please change your issue so that it does [follow the issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md). It gives the team the information needed to investigate.

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
