### ISSUE TITLE
Versioning on Angular-Material Documentation

### ISSUE THREAD

**Issue by wintersommer** [angular/material2#10599]
Hello Team,

we really need to read the documentation for angular material for angular 4.4.6.
https://material.angular.io/ only show the newest version wich is to date 5.2.4 and that is not LTS.

I think 4.4.6 had angular-material 2.0 beta* or something - we only use LTS not cutting Edge.

in angular its done like this: https://v4.angular.io/docs

**Comment by donroyco** [comment]
See #7031 and the comment there:

>Tracking at angular/material.angular.io#168

**Comment by crisbeto** [comment]
Closing as a duplicate.
