### ISSUE TITLE
mat-selection-list not selecting the items

### ISSUE THREAD

**Issue by sivahanuman** [angular/material2#10596]
Hi Mat-Selection-List not selecting the items, i am binding json array to selection and options.

**Bug**

**mat-list-option show as selected**

**mat-selection-list not selecting the items**

[Issue on stackblitz](https://stackblitz.com/edit/angular-material2-issue-plomrp?file=app/app.component.html)

I am using Angular 5, VSCode 1.20.1 and chrome version  65.0.3325.181

**Comment by donroyco** [comment]
Please change your issue so that it does [follow the issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md). It gives the team the information needed to investigate.

**Comment by sivahanuman** [comment]
Hi Donroyco i have updated the post

**Comment by josephperrott** [comment]
Closing as this is working as expected.  `MatSelectionList` does not implement `NgControl` to make `ngModel` work as you have attempted here.

You will need to use the `SelectionModel` that is available on the `MatSelectionList` to set the initial selected values of the list.

**Comment by sivahanuman** [comment]
Hi SelectionModel doesn't work 
<mat-selection-list #list  **(SelectionModel)="sar"** (ngModelChange)="onNgModelChange($event)">
