### ISSUE TITLE
Build aria-live announcer service / component

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#106]

**Comment by DevVersion** [comment]
How should that component look? Should it have the same functionality as in `$mdAria` for Material 1?

**Comment by jelbourn** [comment]
@DevVersion not quite. The idea here is that you have either a component or a service that makes `aria-live` announcements. It would be used by things like `md-toast`. At this point I'm leaning towards a component like 
```html
<md-a11y-announcer>
```
Other components can then simply inject it from higher up in the component tree.

I actually [started writing one for material1](https://github.com/jelbourn/material/blob/5852933e8638a17f56b769a13509f2a6946bdb7e/src/core/services/aria/aria-live.js) but never got around to finishing up the PR. You can find a lot more information in the [issue discussion](https://github.com/angular/material/issues/3174). 

Polymer also has something like this, [the iron-a11y-announcer](https://elements.polymer-project.org/elements/iron-a11y-announcer). My approach

The hardest part of this is actually _testing_ the announcer on all of the different platforms:
* JAWS (Windows) with IE11 / Edge / Chrome / Firefox
* NVDA (Windows) with IE11 / Edge / Chrome / Firefox
* VoiceOver (OSX) with Safari / Chrome
* VoiceOver (iOS) with Safari
* TalkBack (Android) with Chrome

Which is... tedious, so say the least. They can be wildly inconsistent. Unfortunately there not really a way (yet) to automate testing of what a screen-reader _says_.
