### ISSUE TITLE
Checkbox does not animate from checked to indeterminate on first change

### ISSUE THREAD

**Issue by david-j-lee** [angular/material2#10606]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If checkbox has a checked starting value true, when the indeterminate value is set to true it animates to the indeterminate state.

#### What is the current behavior?
The checkbox does not animate between checked to indeterminate on the first change.

#### What are the steps to reproduce?
I have taken the StackBlitz checkbox from docs and change the default value for checked to true. When the interminate checkbox is clicked for the first time it does not animate. All subsequent changes are okay.

https://stackblitz.com/edit/angular-3sax5p

**Comment by josephperrott** [comment]
Closing as obsolete as this appears to be working in the current release, if you find this issue to occur again please open up a new issue for us to take a look.
