### ISSUE TITLE
Autocomplete with free text option

### ISSUE THREAD

**Issue by um-oscar** [angular/material2#10600]
#### Bug, feature request, or proposal:
Autocomplete multiple with option to also enter free text

#### What is the expected behavior?
when using the autocomplete if there's no option that matches what I'm looking for;  I'd like to be able to enter free text as valid input

#### What is the current behavior?
Only option values from the list can be selected

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
enter free text as valid input even if there's no matching option

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5

#### Is there anything else we should know?
no

**Comment by julianobrasil** [comment]
Currently `mat-autocomplete`'s default behavior is to accept any text: https://material.angular.io/components/autocomplete/examples

There's an issue opened asking for a "forceSelection" directive: #3334

**Comment by WizardPC** [comment]
Or use : [https://github.com/bithost-gmbh/ngx-mat-select-search](https://github.com/bithost-gmbh/ngx-mat-select-search)

**Comment by WizardPC** [comment]
Why a feature @josephperrott ? It's already the behavior
