### ISSUE TITLE
sidenav with ngIf not loading in iphone devices. 

### ISSUE THREAD

**Issue by shabbir-dhangot** [angular/material2#10615]
#### Bug
sidenav with ngIf not loading in iphone devices. 

#### What is the expected behavior?
I am loading some content to show on sidenav from server. after loading on I am displaying data. Currently its not showing on iphone. rest it working fine.

#### What are the steps to reproduce?
add any div with ngIF. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, Material 5.2.2, Typescript 2.4.2

#### Is there anything else we should know?
no

**Comment by josephperrott** [comment]
Can you provide a reproduction case in [stackblitz](https://goo.gl/wwnhMV)?

**Comment by shabbir-dhangot** [comment]
Sorry. It was my silly mistake.
Closing issue as invalid
