### ISSUE TITLE
[MatTab] Tab Text overflow isn't worked 

### ISSUE THREAD

**Issue by helenasilkina** [angular/material2#10620]
#### Bug, feature request, or proposal:
Styles of text overflow don't work for tab because of inner div with css class "mat-tab-label-content"

#### What is the expected behavior?
When tab text is long than 160px should be appeared "..." 

#### What is the current behavior?
Tab text is overflow without "..."

#### What are the steps to reproduce?
https://prnt.sc/iy2gpe

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/material 5.0 and 5.2

**Comment by donroyco** [comment]
Please create a StackBlitz example to see the issue: https://goo.gl/wwnhMV

**Comment by helenasilkina** [comment]
I found that another library is caused this issue.
