### ISSUE TITLE
MatInput display issue when open a 2nd time the MatDialog contening it

### ISSUE THREAD

**Issue by Gruudu** [angular/material2#10628]
#### Bug, feature request, or proposal:

I've some display issues with a formular MatInput in a dialog box matDialog.

#### What is the expected behavior?

I want a component to open in a matDialog box with a formular in it. The data bind to the matInput come from a service.

#### What is the current behavior?

The first time I open the dialog the formular is pretty but if i close it and reopen it after the formular have some display issues i.e. when the dialog open or when i click on a input the formular slide to left side then come back 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular : 5.6.0
Material: 2.0.0-beta.12

**Comment by josephperrott** [comment]
Please provide a reproduction in a [stackblitz](https://goo.gl/wwnhMV).  Without a reproduction, we are unable to look into the issue you are seeing.

**Comment by mmalerba** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
