### ISSUE TITLE
Extract `mat-table` component in a separate project

### ISSUE THREAD

**Issue by sarbull** [angular/material2#10632]
#### Proposal:
Extract `mat-table` in a separate project.

#### What is the expected behavior?
import `mat-table` component from another project, outside of angular/material2

#### What is the current behavior?
All components within angular/material2 are inside a same project.

#### What is the use-case or motivation for changing an existing behavior?
More control on features and separate release tracks.

#### Is there anything else we should know?
No.

**Comment by josephperrott** [comment]
As this repository is the project to hold all of our Angular Material components, `MatTable` will continue to be contained within this project.

**Comment by andrewseguin** [comment]
Unfortunately putting the table in a different project won't meant we get more time to add features/fixes. We'd love it if that were the case though :)

**Comment by sarbull** [comment]
@josephperrott i raised this as a proposal, why do you think it should still remain?

I also like your approach.
> our Angular Material components

Cool.

**Comment by sarbull** [comment]
@andrewseguin for example i would be interested in adding some features but the whole project structure is overwhelming.

**Comment by andrewseguin** [comment]
I definitely get that, this is a large project. Here's some tips on getting started:

Clone the repo (`git clone`) and install its dependencies (`npm i`)

Once you are there, you've got a few `gulp` commands that you can run to do most of the heavy lifting for you:
`gulp serve:devapp` - Start a demo app that will refresh itself when you make changes
`gulp test` - Run all the tests in the library. Use `fdescribe` or `fit` to narrow it down
`gulp lint` - Run the linter to check the low-hanging fruit for syntax

If you want to get started with simple issues to get your feet wet, here's some issues marked for first-time contributors: https://github.com/angular/material2/labels/help%20wanted
