### ISSUE TITLE
Sidenav async content doesn't push main content aside

### ISSUE THREAD

**Issue by Tommatheussen** [angular/material2#10638]
#### Bug, feature request, or proposal:
When using the sidenav component, I wanted to show some async loaded content in the sidenav (a list of groups. The problem here is that the sidenav does not properly expand it's content. The view itself is expanded, but the main content is not being moved aside.

#### What is the expected behavior?
I want to load async items inside the sidenav and have the main content move over

#### What is the current behavior?
Currently the content does not shift the main content, the sidenav overlaps the main content after loading the items.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-reyjtg

Open up the stackblitz
Watch the main content
After async items are loaded, main content is overlapped

#### What is the use-case or motivation for changing an existing behavior?
Async loading of data inside of a sidenav

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.0-rc.0 (same behavious with latest 5.x versions)

#### Is there anything else we should know?
**EDIT:** I'm not sure if it's expected/wanted behaviour, but I just found that the `autosize` option actually works. It ensures the sidenav content gets properly moved

**Comment by crisbeto** [comment]
This is one of the use-cases for `autosize`, but you should keep in mind that it comes with a certain performance overhead.
