### ISSUE TITLE
md-tooltip - Type TooltipComponent is part of the declarations of 2 modules: MdTooltipModule and ExchModule!

### ISSUE THREAD

**Issue by RAlfoeldi** [angular/material2#1063]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
No error message

#### What is the current behavior?
Errormessage ***"Type TooltipComponent is part of the declarations of 2 modules: MdTooltipModule and ExchModule!"*** on mouseover.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0.0-rc.5
Material 2.0.0-alpha.7-3
Chrome
Mac OS X 10.11.6

VeEditComponent.template:
````
 <select
   [(ngModel)]="ve.lang"
   name="lang"
   required
==>>   md-tooltip="text" tooltip-position="after">
   <option *ngFor="let lang of langs" [value]="lang">{{lang}}</option>
   </select>
````

admin.module.ts:
````
@NgModule({
  imports: [
    // Angular2
    FormsModule,
    CommonModule,
    // Material Design 2
 ...
    MdTooltipModule,
    // Exchange
    ADMIN_ROUTES
  ],
declarations: [
   ...
==>>    VeEditComponent,
    ...
  ],
````

Tooltip is ONLY referenced in above admin.module.ts as an import. (Edit: screenshot shows search in subdirectory. Same result for src/)

![screen shot 2016-08-17 at 16 32 34](https://cloud.githubusercontent.com/assets/7020711/17740259/43e55b5a-6498-11e6-8521-d296c6a14caa.png)

exch.module.ts (which supposedly declares TooltipComponent):
````
@NgModule({
  imports: [
    // Angular2
    BrowserModule,
    FormsModule,
    HttpModule,
    // Material Design 2
    MdButtonModule,
    MdSidenavModule,
    MdIconModule,
    MdInputModule,
    MdToolbarModule,
    // Exchange
    EXCH_ROUTES,
==>>    AdminModule (defined above) <<==
  ],
  declarations: [
    ExchComponent,
    LoginComponent,
    CounterComponent
  ],
  bootstrap: [
    ExchComponent
  ],
````

I'm lost.

**Comment by jelbourn** [comment]
One one those components (ExchComponent, LoginComponent, CounterComponent) likely has `MD_TOOLTIP_DIRECTIVES` still in its directives list.

**Comment by RAlfoeldi** [comment]
Nope. _directives_ was removed from all components.
![screen shot 2016-08-17 at 18 13 19](https://cloud.githubusercontent.com/assets/7020711/17744056/5f3732c6-64a6-11e6-862b-6e0a7b2856c9.png)

The screenshot attached to the original issue shows that the expression _'tooltip'_ only occurs in two places: the import {MdTooltipModule} and in @NgModule.imports - nowhere else.

**Comment by jelbourn** [comment]
@RAlfoeldi I don't suppose you could share more of your source? As it stands I don't see how it could be happening (unless it's a bug in Angular itself).

**Comment by RAlfoeldi** [comment]
@jelbourn Thanks for offering to have a look.

I've posted all modules, components and templates - in some cases removing the implementation (sorry, I don't own the code) - but leaving the imports, @Component and @NgModule definitions. If you want to see anything else, I'll be glad to post.

http://plnkr.co/edit/O1vOOM4xy5QiYhgp69Jz

**Comment by jelbourn** [comment]
Further investigation has found that this _is_ a bug in Angular itself: https://github.com/angular/angular/issues/10904

As a temporary workaround, you can add `MdTooltipModule` directly to your `ExchModule` imports.

Going to close this issue since the problem doesn't actually live in material. Thanks!

**Comment by RAlfoeldi** [comment]
@jelbourn Thanks.

**Comment by vapits** [comment]
@jelbourn I guess in my case this is my `app.module` but it stills stays there.
