### ISSUE TITLE
###Bug in mat-select dropdown

### ISSUE THREAD

**Issue by svmgarg** [angular/material2#10639]
#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/13872405/38155877-d4afe544-3497-11e8-8ba6-a676579ff55f.png)
At least we should display that information what user is going to select in drop down

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/13872405/38155811-644374f6-3497-11e8-8dfc-004c06eb6a0e.png)
After clicking on "Select your Gender"
![image](https://user-images.githubusercontent.com/13872405/38155787-4120b920-3497-11e8-95a5-58b74175b842.png)

#### What is the use-case or motivation for changing an existing behavior?
At least we should display that information what user is going to select in drop down. Might be it will not be bug but till now i am not able to fix this

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, Material 2 , Windows, 2.7.2 Chrome**/All**

**Comment by crisbeto** [comment]
[This is the intended behavior based on the Material design spec.](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B6Okdz75tqQsbXpoZkNIcXgxc3M/components-dialogs-simplemenus3.png)

**Comment by svmgarg** [comment]
Didn't you think select option should come little below so that user can see what he is going to select.
