### ISSUE TITLE
NgSideNav on Angular 2 RC4

### ISSUE THREAD

**Issue by CelsoSantos** [angular/material2#1064]
I need to use the Sidenav component on a project I'm developing which is, at least for now, stuck at RC4 (other dependencies still at RC4).

What version of the sidenav can I use on Angular2 RC4? Beta.6 is at RC3 and beta.7-3 at RC5. Is there no middle-ground?

Best Regards,
Celso Santos

**Comment by danielgek** [comment]
I think you can use version 6

**Comment by Lavan** [comment]
As @danielgek said, alpha.6-3 works great.

**Comment by CelsoSantos** [comment]
Well I ended up making my own slider using just CSS.
I'm sure the sidenav offers a better navigation experience but in my case I
just want to use it to have a bunch of filters so it would probably be a
bit overkill.

However, I will take your replies in consideration for when I need to adapt
my application for mobile. Navbar will come in very handy at that point.

Thank you both for the replies.
