### ISSUE TITLE
matDatePicker could be more consistent between picking and typing dates

### ISSUE THREAD

**Issue by UltraMarco** [angular/material2#10645]
#### Bug, feature request, or proposal:
**feature request**

#### What is the expected behavior?
When leaving after directly typing a valid date in matDatePicker input, the date could be reformatted to reflect the control's value as if it was picked from the calendar.
E.g.:
speed typing "4 1 87" could automatically become "4/1/1987" (according to locale) when leaving the input

#### What is the current behavior?
Typed dates don't change after typing and leaving the input.

#### What is the use-case or motivation for changing an existing behavior?
This would make inserting dates more consistent with the global appearance of the control and less error-prone for the end users

**Comment by WizardPC** [comment]
Actually i do it with moment.js

**Comment by UltraMarco** [comment]
It's the same behavior even with momentjs, once input date is parsed and the control value is set, what was written remains there, it doesn't get refreshed with the same formatted date.

**Comment by mmalerba** [comment]
Sounds reasonable to me. I do find it reassures me that the system actually accepted my input when I see it reformat itself

**Comment by UltraMarco** [comment]
Exactly

Il lun 2 apr 2018, 18:34 mmalerba <notifications@github.com> ha scritto:

**Comment by tomwanzek** [comment]
Related to the same consideration. i.e. typing vs picking, there is a degree of fickleness:

If I type a date of `2018-06-24`, the picked date appears as `2018-06-25`. Whereas if I type `06/24/2018`, the picked date correctly appears as `2018-06-24`.

Angular Material: 5.2.6
with `MatNativeDateModule`

**Comment by mmalerba** [comment]
@tomwanzek that's the behavior of the native `Date.parse` which `NativeDateAdapter` delegates to. I recommend using `MomentDateAdapter` or a custom `DateAdapter` instead

**Comment by tomwanzek** [comment]
@mmalerba Oh well, thanks for the hint!
