### ISSUE TITLE
Module not found: Error: Can't resolve '@angular/cdk/rxjs'

### ISSUE THREAD

**Issue by raj61** [angular/material2#10647]
#### Bug, feature request, or proposal:
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in '/home/raj/Desktop/projects/resume-angular2-material2/node_modules/@angular/material/esm5'

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

name: '@angular/material',
  description: 'Angular Material',
  'dist-tags': { latest: '5.2.4', next: '6.0.0-rc.0' },

**Comment by CaerusKaru** [comment]
Can't reproduce with the given StackBlitz, and `@angular/cdk/rxjs` was removed in v5

**Comment by crisbeto** [comment]
`@angular/cdk/rxjs` was removed a while ago, make sure that your versions of `@angular/cdk` and `@angular/material` are the same.

**Comment by raj61** [comment]
My dependencies 
"dependencies": {
    "@angular/cli": "1.7.3",
    "@angular/animations": "^5.2.9",
    "@angular/cdk": "^6.0.0-beta.5",
    "@angular/common": "5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/material": "^6.0.0-beta.5",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@angular/router": "5.2.9",
    "@types/hammerjs": "^2.0.35",
    "ajv": "^6.4.0",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.5.8",
    "ts-helpers": "^1.1.2",
    "zone.js": "^0.8.22"
  },

versions of @angular/cdk and @angular/material are same!

**Comment by CaerusKaru** [comment]
Yes, but as @crisbeto and I have already said, that import is not available in v6. It was removed in v5.
