### ISSUE TITLE
MatDatePicker Invalid Date being changed automatically to valid date

### ISSUE THREAD

**Issue by devcheetah** [angular/material2#10678]
#### Bug, feature request, or proposal:
Input manually, 11/31/2018.   MatDatePicker is changing it to 12/01/2018

#### What is the expected behavior?
Date should be invalid.

If there is a quick workaround for this behavior, please let me know.

**Comment by julianobrasil** [comment]
You can extend the `NativeDateAdapter` and override the `parse()` method to output an invalid date in this case (like `new Date(null)`)

**Comment by crisbeto** [comment]
This is how the native `Date` object in JS handles it as well. E.g. `new Date(2018, 10, 31)` will create a date that is the 1st of December 2018.
