### ISSUE TITLE
Dialog opening with a blank page

### ISSUE THREAD

**Issue by duyleduc** [angular/material2#10677]
#### Bug, feature request, or proposal:
Bug
#### What is the expected behavior?
Page rendered correctly with passing data in parameter. 

#### What is the current behavior?
A blank page displaying, if I resize the windows in chrome debug console, it will be rendered. 
I don't have problem if passing null value in parameter, happen only if there is an object passing in parameter. 
This is the page when openned the dialog (unexpected behavior)
<img width="1092" alt="dialog openned" src="https://user-images.githubusercontent.com/6185711/38256462-9e8938ac-375e-11e8-88c9-6bca45fd21cb.png">

After resizing the windows in chrome debug tool (expected behavior)
<img width="1027" alt="after resized" src="https://user-images.githubusercontent.com/6185711/38256464-9ea953ee-375e-11e8-9c66-f86714663ad6.png">

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0, material 5.2.2, OS: windows, mac os
Browser: Chrome

**Comment by tmburnell** [comment]
I tried to repoduce your issue and i can seem to do it:
https://stackblitz.com/edit/angular-dialog-with-data

Can you see if you can modify this stackblitz to reproduce the issue?

**Comment by Chan4077** [comment]
@duyleduc Could you post the error log?

**Comment by duyleduc** [comment]
Hi,
I just discovered that this bug happened only when using with ngx-datatable scrolling (for infinite scroll). If anyone interests in this issue please view this: [https://github.com/swimlane/ngx-datatable/issues/1348](https://github.com/swimlane/ngx-datatable/issues/1348). So I could close this issue
