### ISSUE TITLE
Full-width Dialog

### ISSUE THREAD

**Issue by dirtyshiat** [angular/material2#10682]
#### feature request
allow full-width Dialog

#### What is the current behavior?
Dialog is limited to width:80vw

Is there any possibility to achieve full width Dialog with Angular Material 5.2.4?
I tried the approach from https://github.com/angular/material2/issues/5408, but unfortunately it doesn't work with Angular 5.2.4

**Comment by mtrdp642** [comment]
Related issue: #10094
