### ISSUE TITLE
How to disable mat-select keyboard interaction

### ISSUE THREAD

**Issue by Msimoneau** [angular/material2#10684]
#### Bug, feature request, or proposal:
mat-select has keyboard interaction: up arrow, down arrow to select previous or next option, space/enter to select option and letter to match list item. I need to disable this keyboard interaction. How to disable this?

I've added the following without success: <mat-option (keydown)="$event.stopPropagation()"...

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-6kcps1?file=app/select-multiple-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 Angular: 5.2.9, angular/material :5.2.2

**Comment by jelbourn** [comment]
There isn't a way to disable this.

**Comment by dreamid27** [comment]
@jelbourn can i make pull request for this ?

i need this !

**Comment by jelbourn** [comment]
I don't think this is a feature we would want to add since it effectively turns off a11y

**Comment by dreamid27** [comment]
hmm, 
i'm try to make custom select with search input in top (like use : panelClass ).  but when i try to type like : 

"search  some item" .  
this is not can't work , cause the SELECT lock KEYBOARD EVENT 'SPACE'.

Do you have an alternative for select with autocomplete?

because use just AutoComplete and add some trick method is so painful and hard for some programmer.

**Comment by clamarque** [comment]
like the example given by @dreamid27 . adding (keydown)="$event.stopPropagation()" with your input. Example with custom filter in mat-select:

        `<mat-select multiple placeholder="List of campaign" [(value)]="campaignsSelected"
            formControlName="excludeCampaigns">

         <input class="select-filter" type="text" (keyup)="filterList($event.target.value, 'campaigns')" 
           placeholder="Enter name or ID campaign" (keydown)="$event.stopPropagation()">

            <mat-option *ngFor="let campaign of campaigns" [value]="campaign">
              {{campaign.id}} - {{campaign.name}} - {{campaign.campaignDate}}
            </mat-option>
          </mat-select>`

Now, i can press space or enter without select a item in my list. enjoy :)
