### ISSUE TITLE
[Paginator] numberOfPages is off by one

### ISSUE THREAD

**Issue by haochi** [angular/material2#10699]
#### Bug, feature request, or proposal:
Bug: `numberOfPages` is off by one.

Right now [`numberOfPages()`](https://github.com/angular/material2/blob/c05005a688a1ff929af966835ae33ca85c106fc9/src/lib/paginator/paginator.ts#L179) is calculated as
```js
Math.ceil(this.length / this.pageSize) - 1;
```

Which would work nicely for zero-based calculations, but doesn't work so well for actual display or the mental model of what "number of pages" represent.

For example:

* `length=1`, `pageSize=5` => `numberOfPages()` returns `0` (there should be 1 page right?)

Consider the example of splitting an array into page chunks (i.e. `any[]` => `any[][]`), the resulting array be size of 1.

#### What is the expected behavior?
Should return the current page count.

#### What is the current behavior?
As described above.

#### What is the use-case or motivation for changing an existing behavior?
See above.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
since [v5.2.0](https://github.com/angular/material2/commit/04cdb136cf4bc2ac4f47ac5d8ea8f37708f7b67a), also in the v6.0.0-rc.0

#### Is there anything else we should know?
There doesn't seem to be any tests for `numberOfPages`, a public method.

**Comment by andrewseguin** [comment]
Huh...that does seem confusing. I'm surprised it is a public method since it really should be named something like `getMaxPageIndex`.
