### ISSUE TITLE
mat-menu hides behind fixed-top navbar

### ISSUE THREAD

**Issue by sivahanuman** [angular/material2#10695]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Show mat-menu on top of navbar

#### What is the current behavior?
mat-menu goes behind the navbar

#### What are the steps to reproduce?
i have tried to set max z-index value for mat-menu but still it's goes behind navbar

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I am using angular 5, vscode, chrome

**Comment by julianobrasil** [comment]
Could you reproduce it in stackblitz (just the minimum to show the issue)?

**Comment by crisbeto** [comment]
If your navbar has a `z-index` of over 1000, it'll go above all Material overlays. You can either reduce the `z-index` of the navbar or increase it for the `.cdk-overlay-container`.
