### ISSUE TITLE
Regression in MatButtonToggleGroup: Value not applied on buttons model update

### ISSUE THREAD

**Issue by dobrevad** [angular/material2#10690]
#### Bug, feature request, or proposal:
Regression bug

#### What is the expected behavior?
Updating the button toggles model and the group value results in the button toggle with this value being checked.

#### What is the current behavior?
When the buttons model and the group value are dynamically updated, no button toggle is selected. 

#### What are the steps to reproduce?
Not reproducible in @angular/material@5.2.4.
See the working example in https://stackblitz.com/edit/angular-bmrtvf-qubr3j?file=app%2Fbutton-toggle-exclusive-example.html.

Click "Switch Model". See that there is a selection with the new model.

Reproducible in @angular/material@6.0.0-beta.5
See repro in https://angular-material2-issue-xzuj4n.stackblitz.io.

To reproduce click "Switch Model". Expect to see the first option selected but nothing is selected.

The culprit is: a403bac#diff-0ab4e17fb83eadabf9c87d06e36e93d3

What changed:
When setting the group value it is not applied unless the current list of button toggles contains the input value.
Before:
The group value was always set. Then when button toggles were created, if their value matched the group value the button will be  checked.

#### What is the use-case or motivation for changing an existing behavior?
n/a

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: 6.0.0

**Comment by mmalerba** [comment]
@crisbeto looks like another regression related to #9191

Links to editable versions of both the stackblitzes above for convenience:
https://stackblitz.com/edit/angular-bmrtvf-qubr3j (working 5.2.4)
https://stackblitz.com/edit/angular-material2-issue-xzuj4n (broken 6.0.0-beta.5)
