### ISSUE TITLE
Open dialog does not include loaded modules

### ISSUE THREAD

**Issue by konsultaner** [angular/material2#10696]
#### Bug, feature request, or proposal:
This is probably a duplicate of #7898, but I use the latest 6.0.0.rc-0 and the issue was about 4.x. Thats why I opened a new issue. 

#### What is the expected behavior?
The dialog opens as expected an loads inner components. 

#### What is the current behavior?
The inner components are not loaded due to the following errors:

    Error: Converting circular structure to JSON
    Error: mat-form-field must contain a MatFormFieldControl.

#### What are the steps to reproduce?
https://angular-material2-issue-gz4qp7.stackblitz.io
https://stackblitz.com/edit/angular-material2-issue-gz4qp7

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I use both angular and angular-material 6.0.0-rc.0 but I also works on stackblitz.

#### Is there anything else we should know?
I'm very new to angular2+, so it is most probably not a bug, but a leak of understanding it. Maybe its just something missing in the docs?

**Comment by Chan4077** [comment]
@konsultaner `MatCheckbox` isn't meant to be used with `MatFormField`

**Comment by konsultaner** [comment]
@Chan4077  :bow: I knew I must have been something trivial. Thank you!
