### ISSUE TITLE
[md-slider @alpha 7-3] ngModel causes "no value accessor" error

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#1069]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
According to [the examples in the docs](https://github.com/angular/material2/blob/master/src/demo-app/slider/slider-demo.html), `ngModel` directive can be used with `<md-slider>`. I've verified that this directive works with the native `<input type="range">`.

#### What is the current behavior?
Using the `ngModel` directive with `<md-slider>` causes an error. For instance:
```
<md-slider [(ngModel)]="slider"></md-slider>
```

> Error: No value accessor for form control

#### What are the steps to reproduce?
 - [Open this plunker](http://plnkr.co/edit/5t0BClQpoSDcHCcXRdWF?p=preview)
 - Run it and read the console log. The app will not run until you remove the `ngModel` attribute.

#### What is the use-case or motivation for changing an existing behavior?
It's a bug

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2 rc.5, Material 2 alpha 7-2, 7-3

**Comment by mmalerba** [comment]
Working at alpha 8-2 http://plnkr.co/edit/w2dKSzVmoX2sbSK5PL4L?p=preview

**Comment by RoxKilly** [comment]
@mmalerba FYI, your example throws an exception in the console, though it's a different issue.

For whom it may concern: the docs still state that `ngModel` is [not yet implemented](https://github.com/angular/material2/blob/master/src/lib/slider/README.md) on MdSlider.
