### ISSUE TITLE
md-list

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#107]
[Material Design spec](https://www.google.com/design/spec/components/lists.html#)
[Angular 1 version](https://material.angularjs.org/latest/demo/list)

This should also be usable for the list of items in mdSelect and mdMenu.

**Alpha.2**
- [x] Add static list: #214 
- [x] Add README
- [x] Add subheader / divider support

**Alpha.3**
- [x] Nav list

**Upcoming**
- [ ] Action list
- [ ] Selection list

**Comment by kara** [comment]
- [x] Add V1
- [ ] Add README

**Comment by jelbourn** [comment]
Everything in alpha.2 milestone is done, moving forward to alpha.3 for more features.

**Comment by jelbourn** [comment]
Moving remaining work to alpha.6

**Comment by tarlepp** [comment]
Hmm, what is the correct way to override some md-list css definitions? It seems like I can't any overrides to work as I expected eg.

```
.container {
  md-list md-list-item.md-2-line .md-list-item,
  md-list a[md-list-item].md-2-line .md-list-item,
  md-nav-list md-list-item.md-2-line .md-list-item,
  md-nav-list a[md-list-item].md-2-line .md-list-item {
    background-color: red !important;
    height: auto !important;
  }
}
```

**Comment by ross-nordstrom** [comment]
[Have you tried the `/deep/` selector?](https://angular.io/docs/ts/latest/guide/component-styles.html#!#-deep-)

**Comment by tarlepp** [comment]
@ross-nordstrom hmm that seems to work, thanks a lot! I think there should be some mentioning of this.

**Comment by asaph26** [comment]
@jelbourn Any updates on when the remaining features will be added?

**Comment by riankol** [comment]
I miss the opportunity to add "Least distinguishing content", as mentioned [here](https://material.google.com/components/lists.html#lists-behavior) under the heading of "Content". When do you expect this functionality is likely to be completed?

**Comment by jelbourn** [comment]
@crisbeto for the `<md-action-list>`

**Comment by ajaysattikar** [comment]
Any updates on `<md-action-list>`?

**Comment by Dhinesh16** [comment]
clickable md-list-item any update ?

**Comment by sllethe** [comment]
I'm working on it~ :+1:

**Comment by otienoanyango** [comment]
Are we hoping to see this as promised in this quarter that ends today?

**Comment by Misiu** [comment]
Any updates?

**Comment by kenji-1996** [comment]
Popping in wondering progress but also what would anyone recommend as a temp workaround

**Comment by jelbourn** [comment]
Tracking remaining work in #9429
