### ISSUE TITLE
MatTooltipDisabled don't work if change on click button event

### ISSUE THREAD

**Issue by YoannBureau** [angular/material2#10700]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I have a disabled (disabled = true) tooltip on a button. When I click on the button, I change the disabled state to false and after a few seconds I change it back to true.
Expected: The tooltip should be showed for a few seconds, then disapear.

#### What is the current behavior?
The tooltip does not show. You have to leave the button with your mouse and hover it again to see the tooltip.

#### What are the steps to reproduce?
Here is a blitz that reproduces the problem:
https://stackblitz.com/edit/angular-material-copied-to-clipboard-tooltip?file=app%2Ftooltip-position-example.html

#### What is the use-case or motivation for changing an existing behavior?
For a copy to clipboard button, it is common to inform the user that the data has been copied to the clipboard.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.0
Angular Material 5.2.0

**Comment by julianobrasil** [comment]
You can do it with the `show` and `hide` api methods:

```ts
@ViewChild(MatTooltip) matTooltip: MatTooltip;

...

onCopyButtonClick() {
  this.copiedTooltipDisabled = false;
  setTimeout(() => this.matTooltip.show());
  setTimeout(() => {
    this.copiedTooltipDisabled = true;
    this.matTooltip.hide();
  }, 4000);
}
```

**Comment by josephperrott** [comment]
Closing as this is working as expected.  If you would like to show and hide the tooltip programatically you should use the `show`/`hide` methods.

**Comment by YoannBureau** [comment]
Sorry to ask @julianobrasil but I'm trying to find the way to define a Viewchild for my tooltip with a specific name (I have several tooltips in my page), can you give me a snippet?

**Comment by julianobrasil** [comment]
The `MatTooltip` directive has an `exportAs` attribute (it's exported as "matTooltip"). You can check it without looking for it at the code, just reading the doc site at the [API tab](https://material.angular.io/components/tooltip/api):

![image](https://user-images.githubusercontent.com/25405143/38360958-2a231ac4-38a2-11e8-941b-0bc7ba23ae20.png)

So, you can do something like this:
```ts
<button mat-button
        matTooltip="Look at this tip"
        #tp="matTooltip">
  Just click me
</button>
```

After that, you can get a reference to it by using the _template reference variable_ "tp".

```ts
@ViewChild('tp') _matTooltip: MatTooltip;
```
