### ISSUE TITLE
Autocomplete renders dropdown outside the app-root

### ISSUE THREAD

**Issue by ArtemBulat** [angular/material2#10716]
#### Bug, feature request, or proposal:
For some reason autocomplete renders drop down with suggestions outside the app-root, just at the end of body.
I have found the same issue description here : https://stackoverflow.com/questions/47567179/material-angular-select-dropdown-renders-totally-outside-app-root?answertab=votes#tab-top

#### What is the expected behavior?
It should render just below parent control

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

https://stackblitz.com/edit/angular-byq8u1?file=app%2Fapp.component.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, Material 5.2.4

**Comment by Chan4077** [comment]
@ArtemBulat That's because you're missing a theme.

You can either declare a theme, or add the following line to `styles.scss`:
```scss
@import '~@angular/material/prebuilt-themes/indigo-pink.css';
```

**Comment by ArtemBulat** [comment]
Thanks for the response!

**Comment by crisbeto** [comment]
Closing as a non-issue.
