### ISSUE TITLE
A lot of warning: export 'inject' was not found in '@angular/core'

### ISSUE THREAD

**Issue by tjliupeng** [angular/material2#10735]
#### Bug, feature request, or proposal:
I try to use angular/material and cdk 6.0.0-beta.5 and rxjs 5.5.8 in my angular project with Angular IDE 2017 CI.

#### What is the current behavior?
When the browse is opened, it's hang. And get a lot of warning message in the Angular IDE.
`
WARNING in ./node_modules/@angular/material/esm5/datepicker.es5.js
103:59-75 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1112:164-170 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1112:62-78 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/text-field.es5.js
120:149-155 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/text-field.es5.js
120:167-173 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/text-field.es5.js
120:57-73 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/core.es5.js
1327:59-75 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1659:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1659:182-188 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1659:198-204 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1659:58-74 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1844:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1844:190-196 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
1844:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/datepicker.es5.js
1855:39-45 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
2275:140-146 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
2275:156-162 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
2275:54-70 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/layout.es5.js
253:158-164 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/layout.es5.js
253:180-186 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/layout.es5.js
253:60-76 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
265:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
265:168-174 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
265:58-74 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/autocomplete.es5.js
272:39-45 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3222:170-176 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3222:193-199 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3222:64-80 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/bidi.es5.js
32:34-40 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3401:48-54 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3402:45-51 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
3403:38-44 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
353:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/a11y.es5.js
353:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/sort.es5.js
378:59-75 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/observers.es5.js
40:65-81 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/collections.es5.js
411:67-83 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/core.es5.js
510:34-40 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
515:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
515:161-167 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/scrolling.es5.js
515:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/dialog.es5.js
601:39-45 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
603:167-173 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
603:193-199 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
603:216-222 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
603:232-238 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
603:63-79 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/icon.es5.js
677:149-155 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/icon.es5.js
677:178-184 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/icon.es5.js
677:200-206 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/icon.es5.js
677:57-73 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/tooltip.es5.js
67:39-45 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/stepper.es5.js
67:56-72 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/platform.es5.js
68:50-66 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/bidi.es5.js
70:146-152 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/bidi.es5.js
70:56-72 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
729:179-185 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
729:67-83 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/paginator.es5.js
72:58-74 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
831:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/overlay.es5.js
831:58-74 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/material/esm5/menu.es5.js
834:39-45 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/layout.es5.js
84:140-146 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/cdk/esm5/layout.es5.js
84:54-70 "export 'defineInjectable' was not found in '@angular/core'

webpack: Compiled with warnings.

`

#### What are the steps to reproduce?
My package.json is as follow:

{
  "name": "algorithmplatform-web",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "concurrently --kill-others \"ng build --watch\" \"node server\" ",
    "build": "ng build",
    "test": "concurrently --kill-others \"ng build --watch\" \"node server -t\" ",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.6",
    "@angular/cdk": "^6.0.0-beta.5",
    "@angular/common": "^5.2.6",
    "@angular/compiler": "^5.2.6",
    "@angular/core": "^5.2.6",
    "@angular/flex-layout": "^5.0.0-beta.13",
    "@angular/forms": "^5.2.6",
    "@angular/http": "^5.2.6",
    "@angular/material": "^6.0.0-beta.5",
    "@angular/platform-browser": "^5.2.6",
    "@angular/platform-browser-dynamic": "^5.2.6",
    "@angular/router": "^5.2.6",
    "@mat-datetimepicker/core": "^1.0.2",
    "@mat-datetimepicker/moment": "^1.0.2",
    "@types/underscore": "^1.8.7",
    "ag-grid": "^15.0.0",
    "ag-grid-angular": "^15.0.0",
    "ajv": "^6.2.1",
    "ang-jsoneditor": "^1.5.12",
    "angular-in-memory-web-api": "^0.5.3",
    "angular2-json-schema-form": "^0.6.0-alpha.7",
    "async": "^2.6.0",
    "commander": "^2.14.1",
    "concurrently": "^3.5.1",
    "core-js": "^2.4.1",
    "express-http-proxy": "^1.1.0",
    "generate-schema": "^2.6.0",
    "hammerjs": "^2.0.8",
    "http-proxy": "^1.16.2",
    "jsoneditor": "^5.14.0",
    "material-design-icons": "^3.0.1",
    "moment": "^2.20.1",
    "multer": "^1.3.0",
    "ng-zorro-antd": "^0.6.15",
    "ng2-img-cropper": "^0.9.0",
    "ngx-json-viewer": "^2.2.0",
    "npm": "^5.6.0",
    "rxjs": "^5.5.8",
    "underscore": "^1.8.3",
    "url": "^0.11.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "^5.2.6",
    "@angular/language-service": "^5.2.6",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.101",
    "angular-ide": "^0.9.39",
    "codelyzer": "^4.1.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.6.2"
  }
}

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular CLI: 1.7.4
Node: 8.10.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 6.0.0-rc.1
@angular/cli: 1.7.4
@angular/flex-layout: 5.0.0-beta.14
@angular/material: 6.0.0-rc.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0

**Comment by julianobrasil** [comment]
Try updating your `@angular => 6.0.0-rc.2`/`rxjs => 6.0.0-rc.0`/`rxjs-compat => 6.0.0-rc.0` (`rxjs-compat` only if needed).

**Comment by tjliupeng** [comment]
@julianobrasil , 

Did you mean I need to update all the @angular/** module with 5.2.6 to 6.0.0-rc.2?

**Comment by julianobrasil** [comment]
That's right. Your package json would have this entries:

```ts
 "dependencies": {
    "@angular/animations": "6.0.0-rc.2",
    "@angular/cdk": "6.0.0-rc.1",
    "@angular/common": "6.0.0-rc.2",
    "@angular/compiler": "6.0.0-rc.2",
    "@angular/core": "6.0.0-rc.2",
    "@angular/flex-layout": "^5.0.0-beta.14",
    "@angular/forms": "6.0.0-rc.2",
    "@angular/http": "6.0.0-rc.2",
    "@angular/material": "6.0.0-rc.1",
    "@angular/material-moment-adapter": "6.0.0-rc.1",
    "@angular/platform-browser": "6.0.0-rc.2",
    "@angular/platform-browser-dynamic": "6.0.0-rc.2",
    "@angular/router": "6.0.0-rc.2",
    "rxjs": "^6.0.0-rc.0",
    "rxjs-compat": "^6.0.0-rc.0",

...
```

**Comment by tjliupeng** [comment]
@julianobrasil , That works. All the warnings are gone. 

Thanks.
