### ISSUE TITLE
[md-input] Impossible to use safe navigation operator?

### ISSUE THREAD

**Issue by vapits** [angular/material2#1073]
#### Bug, feature request, or proposal:
Bug (?)

#### What is the expected behavior?
`<md-input [(ngModel)]="activeApp?.name"></md-input>` should work.

`activeApp` is an observarbe in my code:
```
export class ProjectPropertiesComponent implements OnInit {

  sub: any;
  activeApp: Observable<any>;
  constructor(
    private route: ActivatedRoute,
    private appsService: AppsService) {
    this.route = route;
    this.appsService = appsService;
   }

  ngOnInit() {
    this.getProject();
  }

  getProject() {
    this.sub = this.route.parent.params.subscribe(params => {
      let id = params['id'];
      this.appsService.getApp(id)
        .subscribe(
          data => this.activeApp = data
        );
    });
  }

}
```

#### What is the current behavior?
Plunker: http://plnkr.co/edit/Ua7KKEOGCl0nyMzTTwkq?p=preview
(check console)
![image](https://cloud.githubusercontent.com/assets/8594758/17775084/fa0769a0-6556-11e6-9e6c-33f7969d6a57.png)

#### Which versions of Angular, Material, OS, browsers are affected?
Angular version: 2.0.0-rc.5
Angular material versions: 2.0.0-alpha.7-4

#### Is there anything else we should know?
If I don't use the safe operator it works as it should.

**Comment by vapits** [comment]
I find out that `?` safe-navigation operator can't be used as ng-model does the check but the thing is that this is not working when I'm getting data from a http request, so is this still a bug or not?

**Comment by vapits** [comment]
Workaround:

In my code I just initialise the property I wanted to display in the `md-input` in the constructor.

That solved my problem of course. So maybe this is a **feature** instead of bug.

Please choose and set labels or close the issue.

Thank you

**Comment by jelbourn** [comment]
This is the intended behavior of Angular itself (not specific to material). The two-way binding consists of both reading the value and _writing_ the value, where the `?.` operator doesn't make sense for assignments.
