### ISSUE TITLE
Mat-Expansion-Panel Items Remaining After Panel is Hidden

### ISSUE THREAD

**Issue by tridentmakarov** [angular/material2#10734]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The list items from the mat-expansion-panel should hide when the panel is hidden.

#### What is the current behavior?
The panel hides, while the list items, icons, and their links remain. Clicking on them takes the user to the respective page. As well, it is both visually and functionally obstructing items behind.

#### What are the steps to reproduce?
Creating a mat-expansion-panel with multiple items with children, and selecting a child item.

#### What is the use-case or motivation for changing an existing behavior?
Obstruction, both visually and functionally.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Mobile webpage and android, Angular 5.2.2

#### Is there anything else we should know?
<img width="317" alt="screen shot 2018-04-06 at 9 47 31 am" src="https://user-images.githubusercontent.com/3821507/38424755-0ad73338-3980-11e8-910c-454d4f6bbc25.png">

**Comment by josephperrott** [comment]
I was not able to reproduce this myself.  Can you provide a reproduction [stackblitz](https://goo.gl/wwnhMV) for us to look into?

**Comment by tridentmakarov** [comment]
I was able to find a solution, the problem seems likely specific to the code that I am using. If anyone runs into the same issue, set the following for when the navbar is shrunk, and it will hide any of the items.
display: none !important;
