### ISSUE TITLE
Can't use ngModel and formControl at the same time ( Mat-Input )

### ISSUE THREAD

**Issue by sivahanuman** [angular/material2#10730]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Form value with ngModel fields  on form submit

#### What is the current behavior?

Form value doesn't contain form ngModel field on form submit

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue?file=app%2Fapp.component.html

If i use #fieldname it can bind the value but the problem is i can't use [formControl] and #userCode="ngModel" at the same time.

`
#userCode="ngModel" [formControl]="userNameFormControl"
            [errorStateMatcher]="matcher"
`

**Comment by djabif** [comment]
@sivahanuman I did this guide [about forms and validations in angular 5 with material components ](https://angular-templates.io/tutorials/about/angular-forms-and-validations). 
There's also a code example you can use. Hope it helps :)

**Comment by mmalerba** [comment]
I don't think `ngModel` and `formControl` are meant to be used together on the same element.

**Comment by sivahanuman** [comment]
Thanks Dayana Jabif.
