### ISSUE TITLE
In material input asterisk is not displaying untill user points to the fild

### ISSUE THREAD

**Issue by murthymuddu** [angular/material2#10738]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I am disabling the form fields initially , When user click on the Edit form fields are enabled and the required fields should be shown with asterisk symbol.

#### What is the current behavior?
Asterisk asmbol shown when user put the cursor into the field only.

#### What are the steps to reproduce?
1. Disable form fields initially
2. On click of button enable the form fields with value.
3. click on input field observe the behavior of before and after click on input

#### What is the use-case or motivation for changing an existing behavior?

Angular Material ^5.1.0

**Comment by julianobrasil** [comment]
Works for me: https://stackblitz.com/edit/angular-material2-asterisk

What material versions have you tried? The sample is with `6.0.0-rc.2`.
