### ISSUE TITLE
Developer defined svg icon in mat-icon not centered properly

### ISSUE THREAD

**Issue by mmm2306** [angular/material2#10733]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I used a custom svg icon icon in a mat-icon tag and it is not centered properly. With the same CSS used for the custom I used it on a icon provided by Material Design (home) and it is centered correctly.

See image for the above scenario:
![mat-icon-issue](https://user-images.githubusercontent.com/9324329/38418301-7aadf1c8-39a4-11e8-806c-b761774b7a6b.jpg)

My css:
```
div.container {
    max-width: 512px;
    min-width: 256px;
    height: 50px;
    margin: auto;
    color: #000000;
    background-color: #ffffff;
    line-height: 50px;
    text-align: center;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    border-width: 1px;
    border-style: solid;
    border-color: #9e9e9e;
    padding-right: 20px;
    position: fixed;
    z-index: 1000;
    left: 0;
    right: 0;
    top: 30px;
  }

div.img {
    width: 50px;
    float: left;
    border-right-width: 1px;
    border-right-style: solid;
    border-right-color: #9e9e9e;
    background-color: #3f9c35;
}

div.img mat-icon {
    vertical-align: middle;
    background-color: aqua;
}
```
my html:

```
<div class="container">
  <div class="img">
    <mat-icon svgIcon="information">info</mat-icon>
  </div>
  <div class="img">
    <mat-icon>home</mat-icon>
  </div>
  Some text here!
</div>
```
#### What is the current behavior?
Custom defined svg icon on mat-icon is not centered correctly

#### What are the steps to reproduce?

[Here on StackBlitz](https://stackblitz.com/github/mmm2306/mat-icon-issue) is the issue reproduction.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5
Latest Material Design

#### Is there anything else we should know?
No

**Comment by mmm2306** [comment]
![mat-icon-issue](https://user-images.githubusercontent.com/9324329/38418301-7aadf1c8-39a4-11e8-806c-b761774b7a6b.jpg)

Adding the image with the issue again as the original did not  uploaded properly.

**Comment by donroyco** [comment]
Could you please make a StackBlitz reproduction of your issue?

**Comment by mmm2306** [comment]
@donroyco For what I know I cannot upload assets on StackBlitz. Can you guide me on how to add images to StackBlitz project because it is dependent on this.

**Comment by donroyco** [comment]
@mmm2306 You can fork your GitHub repo on StackBlitz... https://stackblitz.com/docs#import-from-github

**Comment by mmm2306** [comment]
@donroyco Thank you for your help. I added the code in StackBlitz . Edited the original post with the new link: 

> Here on StackBlitz the issue reproduction.

**Comment by mmm2306** [comment]
Don't know if this helps but after it is "compiled" and run, this tag is generated for the custom svg:
`<mat-icon _ngcontent-c0="" class="mat-icon" material-icons="" role="img" svgicon="migrate" aria-hidden="true" ng-reflect-svg-icon="migrate"`

And for the icon provided by Material Design this tag is generated:

`<mat-icon _ngcontent-c0="" class="mat-icon material-icons" role="img" aria-hidden="true"`

Now if I add `class="mat-icon material-icons"` to the custom svg it works, the icon is centered correctly. Like this:
`<mat-icon _ngcontent-c0="" class="mat-icon material-icons" material-icons="" role="img" svgicon="migrate" aria-hidden="true" ng-reflect-svg-icon="migrate"`

Any suggestions?

**Comment by julianobrasil** [comment]
@mmm2306, change the link to github to https://stackblitz.com/github/mmm2306/mat-icon-issue so it can be opened directly on stackblitz instead of redirecting to  github repo.

**Comment by mmm2306** [comment]
@julianobrasil thank you for your feedback. the stackblitz link was in the next sentence but I deleted the github link so it won't create a confusion.

**Comment by jelbourn** [comment]
It looks like it's actually your SVG that has the offset built in. Here's an example with a basic 24x24 rectangle SVG and it's placed as expected: https://stackblitz.com/edit/github-l3bcdf?file=src/main.ts
