### ISSUE TITLE
Feature request: Dialog config min-width, max-width option

### ISSUE THREAD

**Issue by netdjw** [angular/material2#10746]
When I open a dialog I want to define min-width and max-width in %. Now is only "width" parameter accepted:

```
openReminderDialog() {
    const dialogRef = this.dialog.open(ReminderContentDialogComponent, {
      width: '500px',
    });
}
```

Or is there any working solution for solve this problem?

**Comment by crisbeto** [comment]
The options for `minWidth`, `minHeight`, `maxWidth` and `maxHeight` are already in there. See https://github.com/angular/material2/blob/master/src/lib/dialog/dialog-config.ts#L63.
