### ISSUE TITLE
A drawer was already declared for 'position="start"'

### ISSUE THREAD

**Issue by mhosman** [angular/material2#10741]
After updating to 6.0rc1 I get an error: "A drawer was already declared for 'position="start"'". Any clue about this? Thank you!!

**Comment by WizardPC** [comment]
I assume it's come from here : [https://material.angular.io/components/sidenav/api](https://material.angular.io/components/sidenav/api)

You can only have one drawer at start (left of the page) and one drawer at end (right of the page).

**Comment by mhosman** [comment]
Sorry, my bad, I was using "align" and not "position" (now "align" is deprecated).
