### ISSUE TITLE
While Selecting between tabs, it recreates the component in md-content

### ISSUE THREAD

**Issue by RajeeNedunchezhian** [angular/material2#1075]
#### Bug, feature request, or proposal:
I have a component that shows a grid (wijmo). While embedding this component within the md-content, it renders the tab pretty nicely. However when i select between the tabs , the component gets recreated. Hence the grid is re-rendered and any filters or groups applied gets cleared.  

#### Which versions of Angular, Material, OS, browsers are affected?
Angular - RC5, Material - Alpha 7.2

**Comment by pkozlowski-opensource** [comment]
If I recall things properly this is by design. If you want to preserve state just keep your data model outside of tabset.

**Comment by jelbourn** [comment]
See #731
