### ISSUE TITLE
Icon - Text Alignment issue in menu :  <i class="material-icons"> vs   <mat-icon>  

### ISSUE THREAD

**Issue by moorthi07** [angular/material2#10754]
`Horizontal alignment  between icon and text is not the same for <i> and <mat-icon>.  This breaks a standard of using <i> and forcing to use <mat-icon>.  (unless you do style adjustments) `

Here is an example link: 

[https://stackblitz.com/edit/angular-maticons-vs-i](https://stackblitz.com/edit/angular-maticons-vs-i)

**Comment by moorthi07** [comment]
@Chan4077 Did you even try the 'Stackblitz' example link - which is the exact code link from https://material.angular.io/components/icon/overview. 
I'm really wondering how could you not  checking that!!!!

**Comment by moorthi07** [comment]
@Chan4077 Let me see...
"You can try to add the mat-icon class to <i class="material-icons">. "  - This difference  is clearly shown in the code in my example link. 

"P.S. Could you edit your comment to show the code? I think you should add two backticks to your code"
---- I really don't get it as, I didn't type any code in my comment. And the link I gave works and take you to the code. 

Pl. tell me what am I missing here?

**Comment by Chan4077** [comment]
@moorthi07 I meant `<i class="material-icons mat-icon">`

**Comment by moorthi07** [comment]
Yes. That works. But looks duplicate .  May be the component 'mat-icon '  vs  icon library 'material-icons'  seems two classes of  some thing same. But definitely confusing.  Do you agree?

**Comment by jelbourn** [comment]
I would say this is working as expected. Our philosophy is to only style elements that we own (e.g. "mat-icon") in order to avoid breaking things outside the library's purview.
