### ISSUE TITLE
mat-tab-link on click opens new page

### ISSUE THREAD

**Issue by kalkrishnan** [angular/material2#10767]
#### Bug, feature request, or proposal:
when I click on a tab(mat-tab-link) it opens a new page rather than opening the page inside the tab

#### What is the expected behavior?
I expected it to open the new page inside the tab rather than navigate away

#### What is the current behavior?
It navigates away from my tabbed page to the linked page

#### What are the steps to reproduce?
Below is my code:
`<div style="padding: 5px;">
    <h1>Angular Material 2 Tab Example using mat-tab-nav-bar and mat-tab-link.</h1>
    <nav mat-tab-nav-bar >
        <a mat-tab-link
     [routerLink]="['../experiment']"
     routerLinkActive #rla1="routerLinkActive"
     [active]="rla1.isActive">
    Page1
  </a>
  <a mat-tab-link
     [routerLink]="['../experiment']"
     routerLinkActive #rla2="routerLinkActive"
     [active]="rla2.isActive">
    Page
  </a>
    </nav>
<router-outlet></router-outlet>
</div>`

`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 2 with Angular Material

**Comment by jelbourn** [comment]
The tab links are just regular anchors. They will obey the `target` attribute and whatever browser preferences are set.

**Comment by kalkrishnan** [comment]
So is the tab behavior with different content only for static content? I thought I would be able to embed components in tabs:

https://material.angular.io/components/tabs/examples

**Comment by jelbourn** [comment]
If you're using `routerLink` it should just work. The tab links really are just anchors, so they work the same way as any other anchor with Angular routing.
