### ISSUE TITLE
Universal rendered sidenav showing box-shadow in closed state

### ISSUE THREAD

**Issue by chrisvfabio** [angular/material2#10760]
#### Bug:

When rendering `<mat-sidenav mode="over">` in the closed state via universal, the drawer's box-shadow is rendering.

#### What is the expected behavior?

Server side rendered `<mat-sidenav mode="over">` in closed state should not render the box-shadow. 

<img width="265" alt="screen shot 2018-04-08 at 8 18 00 pm" src="https://user-images.githubusercontent.com/5626828/38467978-49a1e434-3b72-11e8-8418-0226dfcc861c.png">

#### What is the current behavior?

<img width="265" alt="screen shot 2018-04-08 at 8 18 00 pm" src="https://user-images.githubusercontent.com/5626828/38468042-6472f324-3b73-11e8-820d-dd66a2caa9ce.png">

#### What are the steps to reproduce?

Here is my repro: https://github.com/chrisvfabio/material2-sidenav-shadow-bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
@angular/material 5.2.4
@angular/cdk 5.2.4
@typescript 2.4.2
```
OS: MacOS
Affected Browsers: Chrome, Firefox, Safari

#### Is there anything else we should know?
Adding `'box-shadow': 'none'` to the void animation state seems to solve the issue. When the sidenav is open, the correct box-shadow styles are applied.

Here is my fix: 
https://github.com/chrisvfabio/material2/blob/2908ddfc3fc2e8c975fe23fae133ddfb9fdf836c/src/lib/sidenav/drawer-animations.ts#L28

**Comment by mmalerba** [comment]
@chrisvfabio would you like to submit a PR with the fix?
