### ISSUE TITLE
Angiular 5 & MatAutocomplete - onSelectionChange is not always fired

### ISSUE THREAD

**Issue by Mtaraby** [angular/material2#10766]
I am trying to use MatAutocomplete with Angular 5, I implemented it exactly as they mentioned in material documentation, based on material documentation , I 
can use (onSelectionChange) to know when an option becomes selected, the problem is that I am not able to find a way to know when the option becomes unselected. 
when the user clears the search control for example, there is no event fired to update the model,  any help please.

here is a sample of my code 

    <mat-form-field class="example-full-width" >
      <input matInput placeholder="Select a item" [matAutocomplete]="auto" [formControl]="autoCompleteCtrl">
      <mat-autocomplete #auto="matAutocomplete"  ngDefaultControl  [displayWith]="getDisplayFn()" >
        <mat-option *ngFor="let item of filteredItems | async" [value]="item" (onSelectionChange)="selectionChange(item)">
          {{ item.name }}	
        </mat-option>
      </mat-autocomplete>
    </mat-form-field>

typescript Code
    
    selectedItem: any();

    public getDisplayFn() {
        return (val) => this.display(val);
    }
    public display(item: Item): string {
        if (item) {
          return item.name;
        }
    }
    public selectionChange(item) {
    //this is fired when an option becomes selected , 
    //I need a way to clear selecedItem if the user clear the control
     this.selecedItem = item;
    }

**Comment by julianobrasil** [comment]
One option it inspecting the input control:

```ts
this.autoCompleteCtrl.valueChanges((_) => {
  if(!this.autoCompleteCtrl.value) {
    this.selecedItem = null;
  }
});
```

This code is not tested, so it's likely to have issues. That being said, this is not the appropriate channel to get this kind of help. stackoverflow is a much better place to get help.

**Comment by Mtaraby** [comment]
Thank you @julianobrasil, yes `forceSelection ` solves the issue, Thanks for your reply
