### ISSUE TITLE
Tooltip with longer text is cut when displayed on control positioned next to browser window border

### ISSUE THREAD

**Issue by thiensk** [angular/material2#10769]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
The position of tooltip is adjusted, so it's completely displayed.

#### What is the current behavior?
Tooltip with longer text is cut off when displayed on controls positioned nearby window borders.
similar bug was reported here  #7126. (but was set to closed already)

#### What are the steps to reproduce?
Stackblitz
editor url: https://stackblitz.com/edit/angular-l463qp
app url: https://angular-l463qp.stackblitz.io

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 5.2.4

**Comment by benb7760** [comment]
@thiensk I had this issue but I can confirm it has been resolved in https://github.com/angular/material2/pull/9153

**Comment by tinayuangao** [comment]
@thiensk I think it's resolved in #9153. Version 5.2.4 doesn't include #9153. It will be fixed in 6.0.
Close this issue.
