### ISSUE TITLE
Proposal for collapsible List-items/Nav-list

### ISSUE THREAD

**Issue by MoxxNull** [angular/material2#1076]
#### Bug, feature request, or proposal:
Proposal

#### What is the use-case or motivation for changing an existing behavior?
I've not already mentioned: An option for <md-nav-list> / <md-list-item> for a collapsible "submenu" would be cool, like shown in this image i found: [http://i.stack.imgur.com/SNBAA.png](url)

I could not find anything related.. if already planned, please close :) .  And keep up your amazing work!

**Comment by jelbourn** [comment]
I think this falls into the category of an "accordion", which we don't have any plans for right now.

**Comment by michaeljota** [comment]
Even if you don't plan in short term, it is a control type, as @masaeedu said. You should keep this open just to track this feat development.

**Comment by michaeljota** [comment]
@jelbourn the #995 fits better in an accordion and it's being tracked. I don't know why this shouldn't. collapsible items in sidenavs are very commons.

**Comment by trainerbill** [comment]
@jelbourn Is accordion wanted in this project?  I don't think it would be super difficult to achieve using md-list as a basis.  If one was created would a PR be welcomed?
