### ISSUE TITLE
Progress precentage view

### ISSUE THREAD

**Issue by theunreal** [angular/material2#1077]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Show precentage % as label on progress bars

#### What is the current behavior?
No precentage is shown
#### What is the use-case or motivation for changing an existing behavior?
Let the user know more about the progress, like how many % completed, for example level system with precentage - the user must know what's the exact number of precentage.

Currently the progress bars are good solution for loading, but there are many other cases which progress is important.

#### Is there anything else we should know?
Check out progress bar of the Bootstrap framework 
1. http://getbootstrap.com/components/#progress
2. http://valor-software.com/ng2-bootstrap/#/progressbar

**Comment by jelbourn** [comment]
This isn't mart of the material design spec, and you can always just do something like
```html
<md-progress-bar [value]="percentLoaded"></md-progress-bar>
{{percentLoaded}}%
```
