### ISSUE TITLE
Can't import MAT_LABEL_GLOBAL_OPTIONS from @angular/material/core

### ISSUE THREAD

**Issue by bobKasbi** [angular/material2#10786]
#### Bug:
import import { MAT_LABEL_GLOBAL_OPTIONS} from '@angular/material/core';

#### What is the expected behavior?
Should import import { MAT_LABEL_GLOBAL_OPTIONS} from '@angular/material/core';

#### What is the current behavior?
Error: 
node_modules/@angular/material/core"' has no exported member 'MAT_LABEL_GLOBAL_OPTIONS'. Did you mean 'MAT_RIPPLE_GLOBAL_OPTIONS'?

#### What are the steps to reproduce?
import import { MAT_LABEL_GLOBAL_OPTIONS} from '@angular/material/core';

#### What is the use-case or motivation for changing an existing behavior?
I would like to use the following feature <Floating label>: regarding placeHolder:
https://material.angular.io/components/form-field/overview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.5.0
Node: 8.0.0
OS: darwin x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.5.0
@angular/material: 5.0.0-rc.2
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1

**Comment by tinayuangao** [comment]
@bobKasbi Please try to update your material version. 
Here's a working version
https://stackblitz.com/edit/angular-dqhtwx?file=app/form-field-overview-example.ts

**Comment by bobKasbi** [comment]
Thanks!
