### ISSUE TITLE
Checkbox [checked] binding working only if [disabled] binding is also set

### ISSUE THREAD

**Issue by Wisdomb33r** [angular/material2#10785]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Material checkbox for each of the app language.
Material checkbox has a `[checked]` binding to a boolean value (example : `"selectedlanguage === 'en'`). When clicking on an unchecked checkbox, the previously checked checkbox should uncheck and the clicked checkbox should check.

#### What is the current behavior?
The checked checkbox is correctly unchecked but the clicked checkbox is not checked.

#### What are the steps to reproduce?
[Stackblitz Example](https://angular-hjeezr-wcxytp.stackblitz.io/)
[Stackblitz code](https://stackblitz.com/edit/angular-hjeezr-wcxytp)

#### What is the use-case or motivation for changing an existing behavior?
Correcting a strange behavior.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.9, Material 5.2.4, Typescript 2.5.3, Windows 10, Chrome.

#### Is there anything else we should know?
It's very interesting to note that adding a `[disabled]` binding to the exact same value does correct the bug. The clicked checkbox is correctly checked and disabled.
[Stackblitz Example](https://angular-hjeezr-aaqwbu.stackblitz.io/)
[Stackblitz code](https://stackblitz.com/edit/angular-hjeezr-aaqwbu)

Please also note that my real implementation is using `(change)` instead of `(click)` for the case the user is switching the checkbox with a keyboard interaction instead of a mouse click. But the behavior is still strange enough to be reported.

**Comment by WizardPC** [comment]
Just for me but... why you use checkbox and not radio button to achieve this behavior ?

**Comment by WizardPC** [comment]
If it's just styling, use css to make your radio button square.. 
Angular Material follow design rules and accessibility pattern, it's their strength against other framework. 

So if you use checkbox for anything else than multiple selection, it's a very bad practice ! Your web designer guide you, but as a dev, you need to do the technical choice.

**Comment by Wisdomb33r** [comment]
Ha ! That's a very good point. I see rounded radios and squared checkboxes since so many years I even did not think to style one to look as the other. I'll dig this idea.

That being said, this discussion is out of the scope of this bug report.

**Comment by Wisdomb33r** [comment]
@kvetis Well, your explanation does not convince me 100% due to my second stackblitz example. When I added a `[disabled]` binding, the `[checked]` binding started to work as expected. I did not change anything to the rest of the code. The double effect you do explain should change the checked status twice in this case too.

I suppose you had a slightly different case, where you did bind the checkbox to a boolean and execute a `(click)` event. In this case, and if the function triggered by the click does switch the boolean, your explanation is completely understandable. Click on checkbox naturally change the state of the boolean, while click change the state again. In my case, the checkbox is NOT bound to a boolean value and even if the natural behavior of the checkbox does switch the `checked` attribute, the `(click)` function should override it with the same value (and not switch it).

Btw, I'm also using `(change)` because `(click)` does not cover the case of a user switching the value with keyboard instead of mouse. But the behavior is still strange enough to be reported.

**Comment by tinayuangao** [comment]
@Wisdomb33r 
In your StackBlitz, when user clicked on the checkbox, `selectedLanguage` is updated and set the target checkbox to be checked. Then the `input` inside the `mat-checkbox` is clicked, and because the checkbox is already checked, it's set to `unchecked` status.

This is working as intended. Please use radio buttons, or `(change)` to track the changes in `mat-checkbox`.
