### ISSUE TITLE
SelectionModel is not assigning initial value.

### ISSUE THREAD

**Issue by SalahudinMalik** [angular/material2#10780]
I'm using angular 5 material table with checkbox 

selection = new SelectionModel<Plot>(true, this.plot , true);

I have assign initial value to it but it is not working it not select the column

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Comment by patriciaespada** [comment]
Hello!

About the same subject, I'm trying to initialize SelectionModel with an array of items that should be checked. Any hint to what might I be doing wrong?

Here is the code I'm testing: https://stackblitz.com/edit/mat-tree-initial-selection

I'm setting the SelectionModel on the TreeChecklistExample line 147.
