### ISSUE TITLE
Looking for an angular2 material ribbon

### ISSUE THREAD

**Issue by legalbox** [angular/material2#10784]
#### Bug, feature request, or proposal:
This is a feature request. 

#### What is the expected behavior?
I am looking for a Angular Material2 Ribbon like this one https://dhtmlx.com/docs/products/dhtmlxRibbon/ but for now I did not found any example.

#### What is the current behavior?
No component exists for now. 
We are testing a combination of basic material components here https://stackblitz.com/edit/angular-mat2-ribbon 

#### What are the steps to reproduce?
not applicable

#### What is the use-case or motivation for changing an existing behavior?
I use for several years ExtJs framework and now I want to migrate to Angular Material, but I did'nt the correspondance for each components. For example is "Ext.Panel" the same as "mat-card" ?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular, Material

#### Is there anything else we should know?
no

**Comment by wellwind** [comment]
I think it's not hard to combine existing components to achieve this.

https://stackblitz.com/edit/angular-material-ribbon-demo?file=app%2Fapp.component.html

All you have to do is add more layout style.

**Comment by jelbourn** [comment]
This isn't something we would add to the library itself, as it's not something captured by the Material Design spec.
