### ISSUE TITLE
Angular Material does not work on Child component

### ISSUE THREAD

**Issue by smahu** [angular/material2#10783]
I do not know whether it is a bug or not but when i try to import Material Input box in my child component only html input box appears styling does not work.

#### What is the expected behavior?
It should have a look and feel of material

#### What is the current behavior?
No material stylings are applied

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by Chan4077** [comment]
Did you import a theme?

```scss
@import '~@angular/material/prebuilt-themes/indigo-pink.css';
```

**Comment by smahu** [comment]
yes in styles.css i have imported the above file.

**Comment by Chan4077** [comment]
@smahu Did you import `MatFormFieldModule` / `MatInputModule`? What's your code? Screenshot? Ideally, this should be posted on StackOverflow.

**Comment by smahu** [comment]
https://stackoverflow.com/questions/49749028/angular-material-styles-not-applying-on-child-component
Can you follow this link it has code in it.

**Comment by jelbourn** [comment]
Closing since this seems to be more a request for debugging help than an issue.
