### ISSUE TITLE
Getting the paginator with the renderer removes it from the DOM

### ISSUE THREAD

**Issue by trichetriche** [angular/material2#10797]
#### Bug, feature request, or proposal:

**Bug**

#### What is the expected behavior?

When I use `Renderer2.selectRootElement('mat-paginator')`, I expect to get the DOM element.

#### What is the current behavior?

The DOM element is fetched, but it is removed from the DOM

#### What are the steps to reproduce?

Stackblitz : https://stackblitz.com/edit/angular-vrovzv?file=app/table-pagination-example.ts

#### What is the use-case or motivation for changing an existing behavior?

In this particular case, I want to access the element to get its CSS properties (because I can't get the nativeElement) to create an action line on the left of the paginator. I would like to get its height and background color.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

````
@angular@5.2.6
@angular/cdk@5.2.3
@angular/cli@1.7.1
@angular/material@5.2.3
typescript@2.4.2

Windows 10 Pro edition
Chrome
````

#### Is there anything else we should know?

No.

**Comment by tinayuangao** [comment]
Use `ngAfterContentInit` to get paginator: https://stackblitz.com/edit/angular-vrovzv-qbbnqq?file=app/table-pagination-example.ts

**Comment by trichetriche** [comment]
@tinayuangao you have the same issue as I do, the paginator is deleted from the dom ...

**Comment by andrewseguin** [comment]
`selectRootElement` is not the right API to use to get the native element. 

https://stackoverflow.com/questions/36055585/renderer-multiple-selectrootelement-issue-with-plnkr-provided

You can use `@ViewChild` to get the element. See this example: https://stackblitz.com/edit/angular-vrovzv-kybko9?file=app/table-pagination-example.ts
