### ISSUE TITLE
BreakpointObserver doesn't work properly for the list of breakpoints

### ISSUE THREAD

**Issue by jbojcic1** [angular/material2#10791]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

`this.breakpointObserver.observe([Breakpoints.XSmall, Breakpoints.Small, Breakpoints.Medium])`

should return true for all sizes except Large and XLarge

#### What is the current behavior?

it returns false for medium. It seems like it sees only first two breakpoints from the array because if you switch places in the array above for medium and small, it will return false for small.

#### What are the steps to reproduce?

Copy the snippet from above, subscribe to it and start resizing the screen.

#### What is the use-case or motivation for changing an existing behavior?
-

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular 5.2.8, cdk 5.2.4, material 5.2.4

#### Is there anything else we should know?
-

**Comment by jbojcic1** [comment]
@josephperrott one more thing. If you put two neighbor breakpoints in the array, the observable unnecessarily gets triggered twice.

**Comment by bjorkegeek** [comment]
[The source code](https://github.com/angular/material2/blob/6a82c65e9e4bcc8891a1b62d7090398a46cf5174/src/cdk/layout/breakpoints-observer.ts#L61)  contains a call to combineLatest which is hardcoded to two arguments, causing to fail with three requests.

**Comment by emilio-martinez** [comment]
I'm experiencing the same double call as @jbojcic1 mentioned

**Comment by josephperrott** [comment]
Closing as this was fixed by #10866
