### ISSUE TITLE
md-list does not work in production build

### ISSUE THREAD

**Issue by mounikaseelam20** [angular/material2#1080]
#### Bug, feature request, or proposal: 
md-list does not work in production build

#### What is the expected behavior?
I am using 2.0.0-alpha.7-4 of @angular2-material and following is the code to render list of items

`<md-list class="side">
  <md-list-item class="active list-text" *ngFor="let item of list">
    <md-icon>{{item.icon}}</md-icon>
    {{item.name}}
  </md-list-item>
</md-list>`

and my component.ts file has

`list=[{
       name:"Dashboard",
       icon:"home"
        },{
       name:"Draft",
       icon:"person"
       },{
       name:"Account",
       icon:"lock"
 }]`

This code shows the output properly when I do  _ng serve_

but once I create a build using _ng build -prod_ the list items are not rendered.

#### What is the current behavior?
When i run the app after the  build the output is not same as when i run the app using ng-serve

#### What are the steps to reproduce?

![prodbuild](https://cloud.githubusercontent.com/assets/16240650/17799969/ecdf72ee-65fc-11e6-8eb4-2bd7e7e50d27.png)
 
even after build the output should be same as the output when we run app using ng serve

Please let me know what am I doing wrong?

**Comment by DzmitryShylovich** [comment]
might be related to https://github.com/angular/angular/issues/10618

**Comment by jelbourn** [comment]
I believe this is fixed in the latest version.
