### ISSUE TITLE
Separate component variables in own file to make them reusable

### ISSUE THREAD

**Issue by odahcam** [angular/material2#10808]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
I would like Material to expose the SCSS variables used to theme components, like the card paddings.
There could be a file, `card-metrics.scss` with the sizes, spacing, etc. so we could import the variables to make calculations/customizations.

#### What is the current behavior?
Variables are defined with the element style, making it too much SCSS to import in lots of components.

#### What is the use-case or motivation for changing an existing behavior?
I wanna make use of the `$mat-card-default-padding` in `card.scss` to position some element inside the card.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
^5

#### Is there anything else we should know?
It could be similar to `@import '../core/style/variables';`.

**Comment by jelbourn** [comment]
This isn't something we plan on making a public API because we can't commit to keeping them the same between released.

**Comment by odahcam** [comment]
Sad to hear that, it would be very usefull, as long as the values would be the same as the components I see no trouble on updating. But that's fine. Thanks for the reply.
