### ISSUE TITLE
docs(readme): update stuff for Q2 2018

### ISSUE THREAD

**Issue by donroyco** [angular/material2#10805]
#### Bug, feature request, or proposal:

Proposal

#### What is the expected behavior?
Up to date content in readme file.

#### What is the current behavior?
The current [README.md](https://github.com/angular/material2/blob/master/README.md) on `master` has the 'High level stuff planned for Q1 2018 (January - March)' and should be updated to Quarter 2 of 2018.

#### What are the steps to reproduce?
Just visit the https://github.com/angular/material2 and read the *Project status*.

#### What is the use-case or motivation for changing an existing behavior?
Since version 6 of Material2 is just around the corner with a lot of great stuff, it's good to keep people up to date with the plan(s) of adding or updating features. Related issue: #9192 (for Q1 2018).

**Comment by jelbourn** [comment]
Those quarter boundaries always sneak by me.
