### ISSUE TITLE
Lazy loaded mat-slider not draggable 

### ISSUE THREAD

**Issue by dexster** [angular/material2#10818]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The slider handle should move while being dragged along the slider 

#### What is the current behavior?
The handle does not move until the drag action is complete 

#### What are the steps to reproduce?
https://angular-mruw6r.stackblitz.io/
https://stackblitz.com/edit/angular-mruw6r

Click the slider link to lazy load the slider
Drag the handle

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.9
Material 5.2.4

#### Anything else we should know
Importing the slidermodule in example.component.ts resolves the issue

**Comment by petercartagena** [comment]
Hi, 
Although it's not an angular material issue. 
Try this: https://stackblitz.com/edit/angular-mruw6r-ooajhu?file=main.ts

**Comment by dexster** [comment]
That did it. Thanks

I see now this is a dup of #4278
