### ISSUE TITLE
unable to wire observable into MatTableDataSource

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/material2#10819]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
MatTable should be able to accept an observable

#### What is the current behavior?
I keep getting type error

#### What are the steps to reproduce?
no project as of yet I was wondering whsat best practice is for wiring ngrx state into mattabledatasource

#### What is the use-case or motivation for changing an existing behavior?
bug

```
Angular CLI: 1.7.3
Node: 9.3.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/flex-layout: 5.0.0-beta.13
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0

```
I have a material 2 table component that ran nicely with plain RxJS and typed Array.

So I took it to next level using NGRX

my redux ngrx state is working beautifully spreading my typed array thru the reducer into my ngrx state nicely

at the component level I have a container that propagates `users$` using `@Input()` as input to my table component and I construct an empty MatTableDataSource at construction

container component
`<app-table [users$]="usersState$ | async"></app-table>`

table component
```
@Input() users$: Observable<IUser[]>;
    displayedColumns = ['_id', 'emailAddress', 'password', 'createdAt', 'updatedAt'];
    dataSource = new MatTableDataSource();
```

I cannot get my ngrx state `users: <IUser[]>`
wired into MatTableDataSource properly

here is my RxJS logic
```
onChange(changes: SimpleChanges) {
        this.users$
            .map(users => this.dataSource.data = users);
}

```
action requested please

console error follows...
```
ERROR Error: Uncaught (in promise): TypeError: Cannot add property _resolvedData, object is not extensible
TypeError: Cannot add property _resolvedData, object is not extensible
    at MapSubscriber.eval [as project] (webpack-internal:///./node_modules/@angular/router/esm5/router.js:4038:34)
    at MapSubscriber._next (webpack-internal:///./node_modules/rxjs/_esm5/operators/map.js:82:35)
    at MapSubscriber.Subscriber.next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:97:18)
    at ScalarObservable._subscribe (webpack-internal:///./node_modules/rxjs/_esm5/observable/ScalarObservable.js:53:24)
    at ScalarObservable.Observable._trySubscribe (webpack-internal:///./node_modules/rxjs/_esm5/Observable.js:178:25)
    at ScalarObservable.Observable.subscribe (webpack-internal:///./node_modules/rxjs/_esm5/Observable.js:166:93)
    at MapOperator.call (webpack-internal:///./node_modules/rxjs/_esm5/operators/map.js:60:23)
```

I tried several attempts to get the typed array out of the observable
.switchMap causes `ERROR TypeError: this.users$.switchMap is not a function`
.subscribe causes `ERROR Error: Uncaught (in promise): TypeError: Cannot add property _resolvedData, object is not extensible`
.map causes `ERROR TypeError: this.users$.map is not a function`

I am also wondering is there is a an unseen peer dependency lapse with libraries under the hood with RxJS

**Comment by nhhockeyplayer** [comment]
well I have torn down the code to bare bones minimum

taking the input which resolves to a typed array

I stuff it into new datasource onChanges()

and the console is just running away in infinite loop with this error

ERROR Error: Uncaught (in promise): TypeError: Cannot add property _resolvedData, object is not extensible

```
    ngOnChanges(changes: SimpleChanges) {
        this.dataSource = new MatTableDataSource(this.users$)
        this.dataSource.paginator = this.paginator
        this.dataSource.sort = this.sort
        this.resultsLength = this.dataSource.data.length
    }
```

**Comment by nhhockeyplayer** [comment]
I am closing this out due to my findings

somewhere in the NGRX pipeline (which doesnt seem fair since I am using TYPES here) my typed ARRAY is being morphed into an Object of Objects (with idices ? too)

So I am confident the MatTable will operate when I fix this lapse in TYPE

not impressed though

**Comment by nhhockeyplayer** [comment]
This was my browser safe solution

```
        this.dataSource = new MatTableDataSource(Object.keys(this.users$)
            .map(key => {
                return this.users$[key];
            }))

```

but whats happening over the NGRX store is questionable I have seen other STORES resorting to padding their state properties with stuff

**Comment by nhhockeyplayer** [comment]
this turned out to be errant packaging of the payload within the reducer

mat-table is fine it accepts typed arrays and observables

**Comment by NAILUJSAMA** [comment]
Hey, i have the same problem, have you found a solution ?

**Comment by nhhockeyplayer** [comment]
Hi Friend

its been too long for me to recall

best i can do is show you my reducer
and handling the payload
with types

best
Ken

```
export function usersReducer(
    state: UsersState = initialUsersState,
    action: UsersActionsUnion
): UsersState {
    switch (action.type) {
        case EUsersActions.Reset:
            return initialUsersState

        // singular
        case EUsersActions.FindSuccess:
            return action.payload
        case EUsersActions.ChangedSuccess:
            return action.payload
        case EUsersActions.UsersError:
            return action.payload

        // plural
        case EUserActions.CreateSuccess:
            return [...state, action.payload]

        case EUserActions.UpdateSuccess:
            return [
                ..._.filter(state, (user: any) => user._id !== action.payload._id),
                ...action.payload
            ]
        case EUserActions.DeleteSuccess:
            return [
                ..._.filter(state, (user: any) => user._id !== action.payload._id)
            ]
        default:
            return state
    }
}

```

**Comment by nhhockeyplayer** [comment]
to give you my best answer

my reducer was tripping up the input to my mat-table component

I was operating an observable as an @Input to my table

which mat-table is designed to handle alongside other components such as forms observables
