### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by dominic198** [angular/material2#1081]
can you please a material carousel for angular 2

**Comment by jelbourn** [comment]
We have no plans to add any kind of carousel component.

**Comment by Splaktar** [comment]
I just wanted to leave a note that in the 2018 update to the spec, they have some guidance for carousels: https://material.io/design/communication/onboarding.html#top-user-benefits-model. There is still no detailed guidance with padding/margin/size specs, but it does look to be part of Material Design now.

**Comment by intellix** [comment]
Created my own image carousel and then was thinking I wanted to slide between different "carousel pages" containing grid-lists.

Was looking at Tabs and thinking maybe I could use it without the TabHeader and create my own dots and arrows for changing pages in a direction.

I think the sliding animations/functionality could be extracted from Tabs into CDK and allow you to create "carousels" or "slides" for different scenarios:

 - tabbed slides (Tabs)
 - images (your typical carousel)
 - swiping between grid lists

Thoughts?
