### ISSUE TITLE
Datatable Sort header showing T instead of arrow

### ISSUE THREAD

**Issue by isurendrasingh** [angular/material2#10817]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To show arrow (upwards or downwords)

#### What is the current behavior?

![screenshot 14](https://user-images.githubusercontent.com/7621607/38664328-d53ef324-3e56-11e8-97eb-f6a289e16e4b.png)

**Comment by isurendrasingh** [comment]
::ng-deep .mat-sort-header-arrow.ng-trigger.ng-trigger-arrowPosition {
    opacity: 0;
}

::ng-deep .mat-sort-header-pointer-left.ng-trigger.ng-trigger-leftPointer{
    transform: rotate(-45deg);
}
::ng-deep .mat-sort-header-pointer-right.ng-trigger.ng-trigger-rightPointer{
    transform: rotate(45deg);
}

**Comment by WizardPC** [comment]
Link to #8396 ? @andrewseguin

**Comment by tinayuangao** [comment]
I think this is a duplicate of #9758.
