### ISSUE TITLE
Template issue when creating dynamic 3-level nested menu

### ISSUE THREAD

**Issue by theunreal** [angular/material2#10815]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
the 3rd level of the menu should be rendered without an issue

#### What is the current behavior?
When hovering from one nested menu item to another, the last level of the menu is not rendered properly.
Demo added, to reproduce mouse hover from "c2" to "c3"

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-pushwh

#### What is the use-case or motivation for changing an existing behavior?
Bugfix (if this is an actual bug)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.2.4

**Comment by crisbeto** [comment]
Should be resolved by https://github.com/angular/material2/pull/10132.

**Comment by crisbeto** [comment]
Closing since #10132 has been merged for a while now.
