### ISSUE TITLE
[Chrome] md-input up/down arrows showing when input type is not set to number

### ISSUE THREAD

**Issue by easedev** [angular/material2#1082]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

In all browsers the md-input up/down buttons should be visible only when input type is set to "number".
#### What is the current behavior?

In Chrome the md-input up/down buttons show even when type="number" is not set and when "style='line-height: 1'" is set on body such as when using this reset.css : http://meyerweb.com/eric/tools/css/reset/
Firefox shows no issue there.

If normalize.css is used instead of reset.css then the issue disappears.
#### What are the steps to reproduce?

http://plnkr.co/edit/suhu6SElSc2GwEEXMKq2?p=preview

Removing "line-height" on body solves the problem. 
So does removing the surrounding md-card-content
#### Which versions of Angular, Material, OS, browsers are affected?

Chrome Version 52.0.2743.116 m
Chromium Version 51.0.2704.79 Ubuntu 16.04 (64-bit)
"@angular/core": "2.0.0-rc.5",
"@angular2-material/core": "^2.0.0-alpha.7-4",
"@angular2-material/input": "^2.0.0-alpha.7-4"

**Comment by artiz** [comment]
Quick workaround that works for me:
md-input {
line-height: 1.1;
}

**Comment by jelbourn** [comment]
@mmalerba can you produce this on master?

**Comment by mmalerba** [comment]
These aren't actually input up/down buttons, they're the scrollbar caps for the placeholder label. I can just set the line-height to normal.
