### ISSUE TITLE
Checkbox focus inconsistency when clicking it before animation finishes

### ISSUE THREAD

**Issue by alexw10** [angular/material2#10839]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Checkbox focus should always be consistent
#### What is the current behavior?
Currently it is not consistent when clicked in certain scenarios.

#### What are the steps to reproduce?
Using materia.angular.io can reproduce this:
1st scenario:
Click checkbox wait a few seconds and hit tab the focus will go to the next focusable item.
Gif:
![1st-scenario](https://user-images.githubusercontent.com/9453636/38742175-736da09a-3f01-11e8-8252-61443fee710d.gif)

2nd scenario:
Click checkbox, click it right away again, hit tab the focus then gets put on the checkbox.
![2nd-scenario](https://user-images.githubusercontent.com/9453636/38742245-a4740594-3f01-11e8-9368-605664c91a67.gif)

#### What is the use-case or motivation for changing an existing behavior?
Use case is I would assume the checkbox focus should be consistent no matter how it is clicked please let me know if this is an incorrect asssumption.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest on material.angular.io, Chrome/Firefox

**Comment by josephperrott** [comment]
Closing as obsolete, if you find this issue to occur again please open up a new issue for us to take a look.
