### ISSUE TITLE
[Mat-Select] Custom Font-family not get applied to mat-option

### ISSUE THREAD

**Issue by vjpc** [angular/material2#10835]
#### What are the steps to reproduce?
https://stackblitz.com/edit/select-dropdown-panel-font-family-issue?file=app%2Fapp.component.html

#### What is the use-case or motivation for changing an existing behavior?
This will help in customizing the fonts for mat-select.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - v5.x

**Comment by donroyco** [comment]
```
.mySelectedPanel .mat-option {
   font-family: 'Times New Roman';
   font-size: 15px;
}
```

See [this StackBlitz](https://stackblitz.com/edit/select-dropdown-panel-font-family-issue-eefbcg?file=app%2Fapp.css) for a working example.

**Comment by crisbeto** [comment]
Closing since it seems to be working as expected.

**Comment by vjpc** [comment]
Thanks @donroyco for the solution.

**Comment by jamilraichouni** [comment]
> ```
> .mySelectedPanel .mat-option {
>    font-family: 'Times New Roman';
>    font-size: 15px;
> }
> ```
> See [this StackBlitz](https://stackblitz.com/edit/select-dropdown-panel-font-family-issue-eefbcg?file=app%2Fapp.css) for a working example.

Well, changing the font-family works but a change of the font-size doesn't !?
