### ISSUE TITLE
form-field: update docs to reflect actual behavior of label/placeholder

### ISSUE THREAD

**Issue by yr2193** [angular/material2#10830]
#### Bug
I am following this closed bug https://github.com/angular/material2/pull/8223/commits/17ceb9a56cfe449f4978399faf90d947b59bc720
which said the label and placeholder are separated. 

#### What is the expected behavior?
I expect if I follow the example code then I should be able to have my label and placeholder separated.

#### What is the current behavior?
It does not work as it should be. Only the label is shown.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-qnzimy?file=app%2Finput-overview-example.ts<br/>

#### Is there anything else we should know?
https://material.angular.io/components/input/overview
This overview does not include any of these changes. I do not know what is the latest status of label vs placeholder. Is there another bug or something?

**Comment by LosD** [comment]
@mmalerba  That does not seem to follow the documentation, which does not put any significance on the difference between the placeholder attribute and the mat-placeholder element. If this isn't a bug in behavior, it's a bug in the documentation (and the documentation frankly makes much more sense than the behavior)

Furthermore, it doesn't seem to work for mat-select. I've tried to both use the placeholder attribute and mat-placeholder. As soon as a mat-label is specified, the placeholder is ignored completely.
