### ISSUE TITLE
[question / proposal] Toggle between nav list and selection list

### ISSUE THREAD

**Issue by mkurcius** [angular/material2#10836]
It is possible to toggle between NavList and SelectionList without re-rendering list with *ngIf?

In my project I am displaying user list with avatars and clicking on list item trigger navigation to details view. But there is also button "Bulk changes" which I would like to toggle NavList (default) to SelectionList. From user perceptive all that changes is now displaying checkbox for each list item and changed click behavior (selecting item will toggle checkbox instead of navigating to details view).

So far I could achieve described behavior with *ngIf like:
```html
<mat-nav-list *ngIf="!bulkChanges; else selectionList">
  <a mat-list-item href="#">
    <img matListAvatar src="...">
    <h3 matLine>User 1</h3>
  </a>
  <a mat-list-item href="#">
    <img matListAvatar src="...">
    <h3 matLine>User 2</h3>
  </a>
  <a mat-list-item href="#">
    <img matListAvatar src="...">
    <h3 matLine>User 3</h3>
  </a>
</mat-nav-list>

<ng-template #selectionList>
  <mat-selection-list>
    <mat-list-option>User 1</mat-list-option>
    <mat-list-option>User 2</mat-list-option>
    <mat-list-option>User 3</mat-list-option>
  </mat-selection-list>
</ng-template>

<button mat-button (click)="bulkChanges = !bulkChanges">Toggle</button>
```

But this approach forces re-reander of entire list, when expected behavior is to show / hide checkbox and change click behavior. This list can also have infinite scroll which can lead to removing a lot of nodes when re-rendering.

I would be nice to have one component MatList with all list features. It could be then looks like:
```html
<!--mode values: 'SIMPLE' | 'NAV' | 'SELECTABLE' -->
<mat-list [mode]="listMode">
  <mat-list-item (onNav)="handleNavigation()">
    <img matListAvatar src="...">
    <h3 matLine>User 1</h3>
  </mat-list-item>
</mat-list>
```
onNav would be trigger only when mode === 'NAV'.
When mode === 'SELECTABLE' checkboxes will appear.

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/edit/angular-keuhny

#### What is the use-case or motivation for changing an existing behavior?
Remove unnecessary re-renders which will boost performance.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.9
Material 5.2.4

**Comment by jelbourn** [comment]
The two are completely different components with different interaction patterns; toggling between them with something like `ngIf` is really the only way.

**Comment by mkurcius** [comment]
Sorry for late response. I was afraid you would say so :disappointed: 
Having 3 different components (MatList, MatNavList, and MatSelectionList) for just list component feels too verbose. I think it could be simplified to just one MatList component with inputs and / or content projection as options.

Ad hoc implementation build on top of current API: https://stackblitz.com/edit/angular-jxqwt2

If it is ok with you I could prepare PR (when I have some free time) with new MatList component which could potentially replace current 3 list components. One more benefit would be to hold projection content in one place, ex. right now MatSelectionList don't allow avatars.

**Comment by mkurcius** [comment]
ok, thank for explanation :smile:
