### ISSUE TITLE
MdTooltip doesn't work with pipe

### ISSUE THREAD

**Issue by theunreal** [angular/material2#1084]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

MdTooltip to work fine with pipe
#### What is the current behavior?

Tootlip doesn't work using the following expression:
`[md-tooltip]="activity.created_at | amTimeAgo"`

```
[browser_adapter.js:85 RangeError: Maximum call stack size exceeded
    at defaultParsingFlags (moment.js:80)
    at getParsingFlags (moment.js:100)
    at configFromISO (moment.js:1958)
    at configFromString (moment.js:2012)
    at configFromInput (moment.js:2375)
    at prepareConfig (moment.js:2358)
    at createFromConfig (moment.js:2325)
    at createLocalOrUTC (moment.js:2412)
    at local__createLocal (moment.js:2416)
    at utils_hooks__hooks (moment.js:16)
    at TimeAgoPipe.transform (TimeAgoPipe.ts:37)]
```
#### What are the steps to reproduce?

using angular2-moment with MdTooltip:
`[md-tooltip]="activity.created_at | amTimeAgo"`
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2 Rc.5 + Webpack = Angular 2 Material a7-2

**Comment by m0t0r** [comment]
@theunreal you are trying to use pipe on a binding, not on interpolation. I am not sure that is possible.

**Comment by theunreal** [comment]
@m0t0r It is possible

**Comment by m0t0r** [comment]
@theunreal can you create an example ? Look at this [plunker](http://plnkr.co/edit/9MiSUPvjmCE7pqjFKg8v?p=preview). The pipe applied to binding is not working, you likely have error not from `MdTooltip` but rather from `amTimeAgo` pipe

**Comment by theunreal** [comment]
@m0t0r your `hello` needs to be a variable and the text attributes need to have brackets `[text]`

**Comment by m0t0r** [comment]
@theunreal yes, sorry, my bad. It works now, interesting..

**Comment by PascalTemel** [comment]
Interestingly, it seems to be possible to use pipes with moustache tags now, like this:
`md-tooltip="{{value | pipe}}"`
however, using the following syntax still results in the maximum call stack exceeded error:
`[md-tooltip]="value | pipe"`

**Comment by alexlacasa86** [comment]
I just added a workaround in #1157

**Comment by andrewseguin** [comment]
The issue here was due to a detectChanges call in the tooltip positioning. This no longer exists in the logic and this issue is fixed.

See working example: http://plnkr.co/edit/5gkBSK4zgCjSRSTDGA15?p=preview
