### ISSUE TITLE
Snackbar issue

### ISSUE THREAD

**Issue by avechuche** [angular/material2#10854]
#### Bug, feature request, or proposal:
Maybe a bug

#### What are the steps to reproduce?

I have a google map which has a polygon. When you click on the polygon, a mark is created and if you want to drag it out of it, you can not, showing an error message inside a snackbar. The problem is that the snackbar is not working correctly. Is it my mistake? Snackbar error? Ghost error? Thx

https://stackblitz.com/edit/angular-fojeor

Other example (My PC, not https://stackblitz.com)
![code1](https://user-images.githubusercontent.com/11781418/38763817-1b71d5c2-3f7a-11e8-884b-3ac66d2905c7.png)

Stackblitz example (.gif)

![gm](https://user-images.githubusercontent.com/11781418/38769107-e14ec936-3fd3-11e8-969b-df1203bf6011.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.2.4

**Comment by crisbeto** [comment]
I'm having a hard time reproducing the issue @avechuche. At what point is the snack bar supposed to show up?

**Comment by avechuche** [comment]
Hello @crisbeto , thanks for the attention. The snackbar should appear in the lower and centered part of the screen, the default position. I do not know why it appears above on the left, it can not be closed either. Many instances open (see image). If you can not reproduce the error, expand the right panel of stackblitz. I added some marks when I started the map. I attach a .gif to show the problem.

**Comment by crisbeto** [comment]
Sorry, what I meant is in your example I'm not seeing any snack bars at all. None are in the DOM either.

**Comment by avechuche** [comment]
@crisbeto I see, a confusion. The snackbars appear in the DOM when I try to drag a mark out of the polygon. They are not in the DOM. The image shows how they accumulate in the DOM each time I drag a mark outside the polygon. I can not close them and they do not close alone with 'duration' property, as you can see in the .gif

**Comment by crisbeto** [comment]
Thanks, now I can reproduce it.

**Comment by crisbeto** [comment]
It looks like your issue comes from the fact that the Google Maps callbacks are being run outside of the `NgZone`. You can get it working by running the snack bar calls inside the zone. [Here's a working fork of your example](https://stackblitz.com/edit/angular-zyd37t?file=app/snackbar.service.ts).
