### ISSUE TITLE
Tooltip appeaers in the opposite side of the screen (RTL)

### ISSUE THREAD

**Issue by theunreal** [angular/material2#1085]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

Tooltip appeaers below / in right of / in left of the object
#### What is the current behavior?

Tooltip appears in the wrong position, hidden in screen corners. (RTL pages)

My app has 2 sidebars:
1. Right sidebar
2. Left sidebar

I have MdList in my Left sidebar, and [md-tooltip] on each item.
The tooltip appears in the right side of my screen, at the end of the right (not the left!) sidebar, in a total wrong position and the other side of the screen.

Tested also outside the md list, and it still showing in a wrong position.
#### What are the steps to reproduce?

Having 2 sidebars, left and right.
Put a link with md tooltip, and the tooltip will appears in the other side of the screen.

Might work with bugged position on any RTL website, not sure
#### What is the use-case or motivation for changing an existing behavior?

Md Tooltip supports RTL websites
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2 Rc.5, material v7-4

**Comment by jtc10005** [comment]
I'm having this same issue. Here is a plunk showing the issue.
[https://plnkr.co/edit/yuPzIJ?p=preview](https://plnkr.co/edit/yuPzIJ?p=preview)

**Comment by jelbourn** [comment]
@andrewseguin this should likely do the same thing Kara is doing in `md-menu` for RTL

**Comment by andrewseguin** [comment]
Talked with @EladBezalel and he came up with a suggestion to support RTL/LTR but also provide a way to enforce placement regardless of direction.

He suggested having the states Left, Right, Top, Bottom for hard-coding where the tooltip will appear. In addition, the states Start and End would respect left/right depending on RTL/LTR.

What do you guys think about this?

**Comment by jelbourn** [comment]
In which situations would you want `left` / `right` regardless of layout direction? I'm worries that people would prefer those settings and accidentally make it RTL-unfriendly.

**Comment by EladBezalel** [comment]
Having a fixed position element that is not related to the layout? 
Why to restrict users?

**Comment by jelbourn** [comment]
@EladBezalel do you have a specific example in mind?

**Comment by EladBezalel** [comment]
@jelbourn maybe something like [that](http://codepen.io/EladBezalel/pen/oYbVMd)?
