### ISSUE TITLE
unable to hide mat-select-underline and shows with weird padding

### ISSUE THREAD

**Issue by kalkrishnan** [angular/material2#10862]
#### Bug, feature request, or proposal:
I have been unable to hide mat-select-underline and it shows up with some padding that throws off my alignment. I used the below:

 <div class="form-group"  style="float: left; margin-top: -2em; margin-bottom: -1.25em ">
                    <mat-form-field style="margin-bottom: -1.25em">
                    <mat-select placeholder="ingredient" class="form-group" formControlName="name" name="food" >
                  <mat-option *ngFor="let ingredient of ingredientList" [value]="ingredient">
                    {{ingredient}}
                  </mat-option>
                </mat-select>
                </mat-form-field>

                </div>
CSS:
mat-select.mat-select-underline{
  display:none;
}
![image](https://user-images.githubusercontent.com/6913583/38774814-98faa8ec-4025-11e8-968b-534704494b50.png)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Using Angular 5 with Chrome

**Comment by crisbeto** [comment]
This isn't really something that we support. Our components are set up according to the Material design spec and any style changes that you do on top are at your own risk.

**Comment by kalkrishnan** [comment]
I did the CSS to hide the underline, but it didnt work and my underline by default shows up with weird padding.

**Comment by mucbits** [comment]
You might be missing a space before the underline selector:
```
mat-select .mat-select-underline{
    display:none;
}
```
Anyway, that padding problem might indicate some other CSS problem. Try to comment out all custom CSS to see if the invalid padding remains.

**Comment by kalkrishnan** [comment]
Thanks @mucbits , the underline display worked. Still can't get rid of the padding, even after removing all the CSS.

**Comment by kalkrishnan** [comment]
I added the below to look at the actual size of the container and saw that the size is larger than other input containers:

::ng-deep .mat-input-flex.mat-form-field-flex{
  border: 1px solid black;
}

![image](https://user-images.githubusercontent.com/6913583/38780221-03445f92-4088-11e8-9eea-fbd8ab329f19.png)
