### ISSUE TITLE
[Feature request] "mat-button-toggle-group" with "multiple=true/false"

### ISSUE THREAD

**Issue by WizardPC** [angular/material2#10867]
#### Bug, feature request, or proposal:

Feature request 

#### What is the expected behavior?

Having the possibiliy to use 
`<mat-button-toggle-group multiple="true">`
and 
`<mat-button-toggle-group multiple="false">`

#### What is the current behavior?

Today is limited to
`<mat-button-toggle-group multiple>`
and 
`<mat-button-toggle-group>`

#### What are the steps to reproduce?

[https://stackblitz.com/edit/sb-issue-10867](https://stackblitz.com/edit/sb-issue-10867)

#### What is the use-case or motivation for changing an existing behavior?
I try to make a rich text editor and want to use my toolbar configuration :

```
toolbar = [
    {
      name: 'style', option: 'true', items: [
        { icon: 'format_bold', command: 'bold', style: 'bold' },
        { icon: 'format_italic', command: 'italic', style: 'italic' },
        { icon: 'format_underline', command: 'underline', style: 'uderline' },
        { icon: 'format_strikethrough', command: 'strikeThrough', style: 'strike' }]
    },
    {
      name: 'list', option: 'false', items: [
        { icon: 'format_list_bulleted', command: 'insertUnorderedList', style: 'bulleted' },
        { icon: 'format_list_numbered', command: 'insertOrderedList', style: 'numbered' }
      ]
    },
    {
      ...
}
  ]
```

To group (or not) buttons with `multiple` attribute. But i can't just do something like that :

```
<mat-button-toggle-group *ngFor="let group of toolbar" [multiple]="group.option"  [name]="group.name">
    <mat-button-toggle *ngFor="let button of group.items" (click)="executeCommand(button.command)" [value]="button.style">
        <mat-icon>{{button.icon}}</mat-icon>
    </mat-button-toggle>
</mat-button-toggle-group>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

See SB

#### Is there anything else we should know?

Perhaps it's possible to use a condition for adding (or not) `multiple` in the HTML tag directly ? I don't find any solutions. Moreover, i already try to override `attr.role` with "group" or "radiogroup" but it's not working as expected...

**Comment by tinayuangao** [comment]
This will be supported in 6.0 version. 
Related pr: #9191

**Comment by WizardPC** [comment]
Oh so great!
