### ISSUE TITLE
Suggest add user-select: none to [button-toggle] 

### ISSUE THREAD

**Issue by colinfang** [angular/material2#1086]
Since button-toggle appears like buttons, I suggest `user-select` should be disabled. (Maybe in `.md-button-toggle-label-content`)

```
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
```

**Comment by fxck** [comment]
Is this really needed? The default value for actual button element is `user-select: text`, in desktop browser anyway, is it any different in mobile browsers? Also is this really needed, what action should it prevent?
