### ISSUE TITLE
On open SideBar focus on input field

### ISSUE THREAD

**Issue by DeveloperFromUkraine** [angular/material2#10874]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

When the sidenav is opened and the user move the cursor on one of inputs the first input is always focused automatically.

#### What is the current behavior?

Focus should be only if user click on one of input field.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
` "@angular/animations": "5.2.3",
    "@angular/cdk": "5.2.0",
    "@angular/common": "5.2.3",
    "@angular/compiler": "5.2.3",
    "@angular/core": "5.2.3",
    "@angular/forms": "5.2.3",
    "@angular/http": "5.2.3",
    "@angular/material": "5.2.0",
    "@angular/platform-browser": "5.2.3",
    "@angular/platform-browser-dynamic": "5.2.3",
    "@angular/router": "5.2.3",`

**Comment by DeveloperFromUkraine** [comment]
Hey, may be some one could answer on my questions????

**Comment by mmalerba** [comment]
It seems to work fine to me: https://stackblitz.com/edit/angular-vcubrd?file=app/sidenav-drawer-overview-example.html

Can you provide a stackblitz reproduction showing what's broken?

**Comment by mmalerba** [comment]
Ah, it traps focus in the sidenav when the backdrop is showing, for accessibility reasons. The input just happens to be the first focusable element in the sidenav. The focus still has to go _somewhere_. If there's a different element you want it to start on you can add `cdkFocusInitial` to it: https://stackblitz.com/edit/angular-b26whc-2zbsv7?file=app/sidenav-mode-example.html

If you want nothing to be focused initially, you could put a `tabindex="0"` on the sidenav itself so it will receive the focus: https://stackblitz.com/edit/angular-b26whc-9s2ypm?file=app/sidenav-mode-example.html (I'm not so sure about the accessibility of this though, I would focus a real element if possible)

**Comment by DeveloperFromUkraine** [comment]
Thank you for you answer, now it's clear for me. Have a good day !
