### ISSUE TITLE
[feature request] md-checkbox-group to make checkbox work with reactive forms

### ISSUE THREAD

**Issue by maciejsobala** [angular/material2#1087]
#### feature request:

Implement `<md-checkbox-group>` element, which would work same way as `<md-radio-group>`
#### What is the expected behavior?

Introducing this element, would be great way to deal with reactive forms, in same way as with radios:

```
<md-radio-group [formControl]="myForm.controls['radio']">
      <md-radio-button *ngFor="let option of radioOptions" [value]="option"></md-radio-button>
    </md-radio-group>
```

component:

```
export class MyComponent implements OnInit {

radioOptions: RadioInput[] = [
    new RadioInput("name1", "value1"),
    new RadioInput("name2", "value2"),
    new RadioInput("name3", "value3")
  ];

radioInput: RadioInput = this.radioOptions[1];

constructor(fb: FormBuilder) {
    this.myForm = fb.group({
      "radio": this.radioInput,
    });
  }
}
```

For checkbox, we would do something like that:

```
<md-checkbox-group [formControl]="myForm.controls['checkboxes']">
      <md-checkbox *ngFor="let option of checkboxOptions" [value]="option"></md-radio-button>
    </md-radio-group>
```

component:

```
export class MyComponent implements OnInit {

checkboxOptions: CheckboxInput[] = [
    new CheckboxInput("name1", "value1"),
    new CheckboxInput("name2", "value2"),
    new CheckboxInput("name3", "value3"),
  ];

checkboxInput: CheckboxInput[] = [this.checkboxOptions[0], this.checkboxOptions[2]];

constructor(fb: FormBuilder) {
    this.myForm = fb.group({
      "checkboxes": this.checkboxInput,
    });
  }
}
```
#### What is the use-case or motivation for changing an existing behavior?

At this moment it is impossible to with checkboxes using reactive forms
#### Which versions of Angular, Material, OS, browsers are affected?

@angular2-material: 2.0.0-alpha.7-3,
@angular: 2.0.0-rc.5
@angular/forms: 0.3.0

**Comment by jelbourn** [comment]
> At this moment it is impossible to with checkboxes using reactive forms

Why is this?

**Comment by tinayuangao** [comment]
The MdCheckbox is working perfectly with reactive forms. I don't think md-checkbox-group would be necessary.

**Comment by jainankit102** [comment]
+1

**Comment by halukkaramete** [comment]
The current mat-select with multiple does offer grouped check boxes ,well sort of. And that's what I use anyway. The results are nicely submitted as comma separated just like the good old HTML forms. Right now, a checkbox in material/angular sends a yes/no or true/false statements. So if you got a "favorite colors" as a form question, you will getting blue=true, red=true as opposed to much easier approach as favorite_colors=blue,red. 

Not sure whether the grouped-checkboxes will be implemented or not, So until then I will be using the mat-select. My question to you guys,  IS IT POSSIBLE to display mat-select vertical checkboxes in horizontal fashion through CSS? And is it possible to open the mat-select, like the good old <select multiple size=10> used to do it?

**Comment by albertvp** [comment]
Having a dynamic field with a group of options multi-selection would be really useful a `md-checkbox-group` like the radio one that works with a simple `ngModel` or `formControl` to managr this group and should work like a `select` multi-choice.
@maciejtreder is right, this is missing and expected.
