### ISSUE TITLE
MatSidenavContainer scroll events not working as documented

### ISSUE THREAD

**Issue by mackelito** [angular/material2#10884]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Able to react to scrolling inside the `<mat-sidenav-container>`

#### What is the current behavior?
Unhandled Promise rejection: Cannot read property 'scrollable' of undefined ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot read property 'scrollable' of undefined TypeError: Cannot read property 'scrollable' of undefined at new SidenavResponsiveExample

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-rgkuk8?file=app/sidenav-responsive-example.ts

**Comment by stevo-knievo** [comment]
it's still broken in 6.1.0.

Here the example:
https://stackblitz.com/edit/sidenavcontainer-scrollable-elementscrolled

**Comment by mmalerba** [comment]
It looks like the query listener is being added too soon in the example, it should be deferred until `ngOnInit`: https://stackblitz.com/edit/angular-rgkuk8-ssckuv?file=app/sidenav-responsive-example.ts

Would anyone like to send a PR updating the example?

**Comment by crisbeto** [comment]
Reopening the issue since the PR got in by accident and had to be reverted.
