### ISSUE TITLE
Menu not working in RTL

### ISSUE THREAD

**Issue by theunreal** [angular/material2#1088]
MdMenu don't trigger/open menu in RTL pages. Tooltip does not either.

Menu with any page with dir="rtl" will not show at all.

Angular 2 Rc.5 with latest Angular 2 Material (v8-1) 

Plunker:
https://plnkr.co/edit/5dJE21K2rqMHQupaAm3C?p=preview

**Comment by theunreal** [comment]
Same for tooltip

**Comment by jelbourn** [comment]
@kara you have this resolved in one of your open/recent PRs, right? If so, please close.

**Comment by kara** [comment]
Yes, menu should work fine in RTL, but the dir attribute needs to be set within the Angular app so we can see it and set the connection position properly. This is only temporary while we wait for a longer-term layout service.  

@theunreal For now, if you put your "dir" attribute within your Angular app (and remove it from the HTML tag), it should fix your issues. Ex: ttps://plnkr.co/edit/jjt9NydTQunjEhK8VgKj?p=preview 

Closing in favor of https://github.com/angular/material2/issues/1719. See that issue for tracking of a library-wide solution for this.
