### ISSUE TITLE
[bug] mat-form-field: Missing validation on change without blur

### ISSUE THREAD

**Issue by RKaczmarek** [angular/material2#10887]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When you enter (focus) a mat-form-field the validation errors should occur in the form field when changing the value.

#### What is the current behavior?
When you enter the form field the validation errors are not shown, until the form field loses the focus (on blur) the first time.

After that you can enter the form field again and the validation errors are shown correctly.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-kqgcii

#### What is the use-case or motivation for changing an existing behavior?
Every validation.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
newest versions.

#### Is there anything else we should know?
no

**Comment by johankvint** [comment]
This is the actually the desired behaviour.
https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown

You can change the behaviour by changing the `ErrorStateMatcher` as explained in the documentation

**Comment by RKaczmarek** [comment]
Hmm. Thnx alot.

Seems like I've somehow failed to see this in the documentation.
