### ISSUE TITLE
DatePicker not updating ngModel value

### ISSUE THREAD

**Issue by sarbull** [angular/material2#10890]
#### Bug?
I have this `Date Picker` example
```html
<mat-form-field>
  <input matInput [(ngModel)]="from" [matDatepicker]="from" (change)="onChangeEvent($event)" placeholder="From">

  <mat-datepicker-toggle matSuffix [for]="from"></mat-datepicker-toggle>
  <mat-datepicker #from></mat-datepicker>
</mat-form-field>
```

```ts
import {Component} from '@angular/core';

@Component({
  selector: 'date-filter',
  templateUrl: 'date.filter.html',
})
export class DateFilter {
  from: any;

  onChangeEvent(e): void {
    console.log(e.target.value);
    console.log('this.from = ', this.from);
  }
}
```

#### What is the expected behavior?
On date change i should have the value in `this.form`.

#### What is the current behavior?
It doesn't update the model and i get this error: `Uncaught Error: Cannot assign to a reference or variable!`.

**Comment by dhrn** [comment]
please ask this question in StackOverflow

**Comment by sarbull** [comment]
I just found the solution myself, thank you for your awesome support.

```html
<mat-form-field>
  <input matInput [(ngModel)]="fromDate" [matDatepicker]="from" (change)="onChangeEvent($event)" placeholder="From">

  <mat-datepicker-toggle matSuffix [for]="from"></mat-datepicker-toggle>
  <mat-datepicker #from></mat-datepicker>
</mat-form-field>
```

I had to update the `[(ngModel)]` to `[(ngModel)]="fromDate"` differently from `[matDatepicker]="from"`.

Completely unintuitive.

**Comment by dhrn** [comment]
please use (dateChange)="onValueChange($event) instead of change

**Comment by sarbull** [comment]
@dhrn it was just for debugging purposes
