### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by lokzzor** [angular/material2#10895]
Hello, could you help me, I'm stuck with data table .....
I would like mat-header-cell and mat-cell columns to do the width of the text.And Row file path give the rest of the space
![2018-04-17 21-45-29](https://user-images.githubusercontent.com/36513909/38890001-deb837d6-4288-11e8-96e5-40d1cac5fea3.png)

css

mat-row:nth-child(even){
  background: white;
  }
mat-row:nth-child(odd){
  background: rgba(0,0,0,0.10);
  }
  .paginator{
    background: rgba(0,0,0,0.30);
  }
  .mat-table {
    border: solid 1px rgba(0,0,0,0.16);
  }
.mat-header-row {
  position: sticky;
  top: 0;
  background: cornflowerblue;
  z-index: 9999;
}
.example-container {
  display: flex;
  flex-direction: column;
  min-width: 300px;
}

.example-header {
  min-height: 64px;
  display: flex;
  align-items: center;
  padding-left: 24px;
  font-size: 20px;
}

.example-table {
  overflow: auto;
  min-height: 300px;
}

.example-loading-shade {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 56px;
  right: 0;
  background: rgba(0, 0, 0, 0.15);
  z-index: 1;
  display: flex;
  align-items: center;
  justify-content: center;
}

**Comment by andrewseguin** [comment]
Wait until our next release which will support using the native `<table>` element. It will automatically resize columns based on content for you. Much easier than flex in my opinion.

If you need further help, please use Stackoverflow next time. Usually we try to keep issues focused on bugs and feature requests
