### ISSUE TITLE
EXCEPTION: Error: Uncaught (in promise): No value accessor for 'lstCountries'

### ISSUE THREAD

**Issue by rajkgoel** [angular/material2#1090]
#### Bug : I see this error, mentioned in title, with the following code - 
`      <ul ngControl="lstCountries" name="lstCountries" 
          (click)="setSelectedCountry(country)"
          *ngFor="let country of model.SelectedContinent?.Countries"
          [ngClass]="{selected: country.Id == model.SelectedCountry?.Id}">
          <li>
              <span class="country-col">{{country.Name}}</span>
              <span> 
                  <select (change)="country.ProxyCountry=$event.target.value">
                      <option *ngFor="let cntry of allCountries"
                          [value]="cntry"
                          [selected]="cntry === country.ProxyCountry">
                          {{cntry}}
                      </option>
                  </select>
              </span>
              <span>{{country.Status}}</span>
          </li>
      </ul>`

If I remove `ngControl="lstCountries"` from the above code, then it runs without any errors.

I am working on the project, base code for which was generated with [angular-cli](https://github.com/angular/angular-cli) version 1.0.0-beta.10.

**Comment by DzmitryShylovich** [comment]
ngControl is deprecated and will be removed in rc6.

**Comment by kara** [comment]
@rajkgoel  As @DzmitryShylovich mentioned, it looks like you're using the deprecated forms API, which is not supported in alpha.6 or later of Material.  You can downgrade to Material alpha.5, but the old API is going to be removed in the next release of angular, so I'd recommend upgrading.

**Comment by rajkgoel** [comment]
Thanks for notifying it Kara. Yes, I am currently using deprecated forms api, going to upgrade it with the next release.
