### ISSUE TITLE
Wrong import path for _a11y.scss in cdk's _overlay.scss breaks build

### ISSUE THREAD

**Issue by alexanderwende** [angular/material2#10908]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When importing @angular/cdk/_overlay.scss into my projects scss files, it should not throw an error.

#### What is the current behavior?
It throws the following error:
```
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed: 
@import '../a11y/a11y';
^
      File to import not found or unreadable: ../a11y/a11y.
      in /Users/alex/Repositories/ng6/node_modules/@angular/cdk/_overlay.scss (line 1, column 1)
```

#### What are the steps to reproduce?
@import "~@angular/cdk/overlay"; in one of your app's scss file.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 6.0.0-rc.5
cdk 6.0.0-rc.12

#### Is there anything else we should know?
The import path in _overlay.scss is wrong and should be './a11y' instead of '../a11y/a11y'

**Comment by AncelHernandez** [comment]
Also experiencing this.

Change source: https://github.com/angular/material2/pull/10252

**Comment by alexanderwende** [comment]
Thanks for fixing this guys! :)
