### ISSUE TITLE
How to change color on selected index change of dropdown inside angular material table

### ISSUE THREAD

**Issue by postmeback** [angular/material2#10911]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
It should change the color

#### What is the current behavior?
It is not changing.

###Approach
This is the below html code :-
`<ng-container matColumnDef="Eligible To Vote?"><mat-header-cell *matHeaderCellDef mat-sort-header> Eligible To Vote? </mat-header-cell><mat-cell *matCellDef="let element" ><mat-form-field [class.app-input-no-underline]="true"><mat-select id="eligind" placeholder="Select" (ngModelChange)="EligOnChange($event)" [(value)]="element?.detail.Elig_Indc" [(ngModel)]="element?.detail.Elig_Indc" name="elig-voting" class = "{{styleClass}}"> <mat-option>Select</mat-option><mat-option value="1">Yes</mat-option><mat-option value="0">No</mat-option></mat-select> </mat-form-field> </mat-cell></ng-container><ng-container matColumnDef="Voting?" > <mat-header-cell *matHeaderCellDef mat-sort-header> Voting? </mat-header-cell> <mat-cell *matCellDef="let row; let element" [ngClass]="{'mat-cell-no': element == 0}" > <mat-form-field [class.app-input-no-underline]="true"><mat-select id="voting" placeholder="Select" (ngModelChange)="VoteOnChange($event)" [(value)]="element?.detail.Voting_Indc " [(ngModel)]="element?.detail.Voting_Indc" name="voting" class = "{{styleClass}}"><mat-option>Select</mat-option><mat-option value="1" >Yes</mat-option><mat-option value="0" >No</mat-option> </mat-select> </mat-form-field> </mat-cell></ng-container>`

In both the dropdowns the ngModelChange is the listener. Below is the respective typescript:

`EligOnChange($event) { if ($event !== '0') { } else { alert('a'); this.EligibilityToVote = false; if (this.IsVoting === false) { this.styleClass = 'vote-same-red mat-select-text-value'; } else { alert('sdgf'); } } }`

`VoteOnChange($event, element) { if ($event !== '0') { } else { alert('a'); this.IsVoting = false; if (this.EligibilityToVote === false) { this.styleClass = 'vote-same-red mat-select-text-value'; } else { alert('sdgf'); } } }`

And below the CSS
`.vote-same-red .mat-select-text-value { color:red !important; }`

There are multiple problems i am facing -

1. I am having a hard time to detect the two statuses on ngModelChange for multiple values.
2. The class is not getting reflected, most of the cases the class is getting dynamically generated, so it is not possible to add the respective class.

Is there anything else we should know? Stack Traces, Screenshots, etc.

The last two columns is what i am concerned about. What i want is if both are NO, then both the selected index will be red.
The [Stackblitz Code](https://angular-yjnjta.stackblitz.io/)

**Comment by andrewseguin** [comment]
@postmeback Sorry but I'm not sure we'll be able to help out here. You may have more luck posting on StackOverflow. I recommend trying to clean up your example as much as possible to really show what you are trying to accomplish. I tried to look at the code but it isn't clear what you are trying to do, e.g. `this.styleClass` doesn't exist so I'm not sure where that fits into your goal.

**Comment by postmeback** [comment]
This is the [stackoverflow link](https://stackoverflow.com/questions/49894397/how-to-change-color-on-selected-index-change-of-dropdown-inside-angular-material)

**Comment by postmeback** [comment]
@andrewseguin I have given the respective stackoverflow link...Can you or anyone please help me on this ?
