### ISSUE TITLE
Display error on svgIcon not loaded

### ISSUE THREAD

**Issue by odahcam** [angular/material2#10913]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
When my icons have some trouble to load, I wanna know why, an error message could do that.

#### What is the current behavior?
Fails silently.

#### What are the steps to reproduce?
The docs example itself doesn't work on StackBlitz, there's not a thing easy to reproduce or not there.

#### What is the use-case or motivation for changing an existing behavior?
I can't fix my error because I don't know whats wrong!

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Ng 5.2, Material 5.2.4

#### Is there anything else we should know?
Not yet.

**Comment by odahcam** [comment]
It was not working because attribute `svgIcon` was in lowercase (`svgicon`). This case conversion was provided by Prettier, wich do some atrocities with HTML.

Having this in mind, I think some note/warn could be added to the docs when directives are used informing people to pay attention to the directive case.

**Comment by jelbourn** [comment]
This is really just the way Angular works, not something specific to the Angular Material components. Angular doesn't error on unrecognized attributes without bindings since they're still valid HTML and might be used by some other library.

**Comment by odahcam** [comment]
Yes, it was my fault and I chose to left it here just to register the case.
