### ISSUE TITLE
Sorting not Working using Custom DataSource

### ISSUE THREAD

**Issue by mixtou** [angular/material2#10918]
#### Bug, feature request, or proposal:
Sorting not Working using Custom DataSource it sort of shuffling the data

#### What is the expected behavior?
Sorting should work and data should be shown in ascending or descending order per column values

#### What is the current behavior?
It kinds of shuffling the data, but definitely not shorting

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

https://stackoverflow.com/questions/49924135/angular-5-material-datatable-sorting-is-not-sorting-just-shuffles-data-when-usi

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.7.4
Node: 9.5.0
OS: darwin x64
Angular: 5.2.2
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/animations: 5.2.3
@angular/cdk: 5.1.1
@angular/cli: 1.7.4
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.1.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.0.46
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
@schematics/schematics: 0.0.13
typescript: 2.6.2
webpack: 3.11.0

**Comment by andrewseguin** [comment]
If you re-open with a reproduction of the issue in StackBlitz, perhaps we can help. However, we have limited time for troubleshooting and want to focus issues on bugs and feature requests.
