### ISSUE TITLE
Generate material setup using ng add fails

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [angular/material2#10912]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
As @jelbourn was presenting yesterday on stage at ngconf, I've tried to install the typical material setup using `ng add`. This should have resulted in an updated angular.json file, index.html, etc.

#### What is the current behavior?
Running `ng add @angular/material` fails with the following 2 lines:
```
Installing packages for tooling via npm.
Cannot read property 'includes' of undefined
```

#### What are the steps to reproduce?
```
ng new myapp
cd myapp
npm i @angular/material@next @angular/cdk@next --save
ng add @angular/material
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.0-rc.5
@angular/cdk                      6.0.0-rc.12
@angular/material                 6.0.0-rc.12

#### Is there anything else we should know?
I like your stuff :)

**Comment by kamalkech** [comment]
some issue

**Comment by freelancersunil** [comment]
When i do:

`npm install --save @angular/material @angular/cdk `

it installs below:
+ @angular/material@6.3.2
+ @angular/cdk@6.3.2

Then, as per above solutions: 

I do:

`ng add @angular/material`

it throws as below:

Installing packages for tooling via npm.
Cannot read property 'startTag' of undefined


**NPM Version: 6.1.0**

**Comment by freelancersunil** [comment]
ng add @angular/material@6.3.2 <----------- This worked for me

**Comment by nagarwa93** [comment]
I am also facing the issue when I tried:
`ng add @progress/kendo-angular-dropdowns`

It installed below:
`"@progress/kendo-angular-dropdowns": "^3.4.2"`

But, at the end it throws as below:

> Installed packages for tooling via npm.
Cannot read property 'includes' of undefined

**Angular CLI: 7.3.0
Node: 10.11.0
OS: win32 x64
Angular: 7.2.3
NPM Version: 6.4.1**
