### ISSUE TITLE
Use the CLI application prefix for constructing component selectors

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [angular/material2#10927]
#### Bug, feature request, or proposal:
feature

#### What is the expected behavior?
Generating new material components should respect the application prefix for the component selector.

#### What is the current behavior?
Newly generated components ignore the application prefix (given by the angular.json configuration).

#### What are the steps to reproduce?
ng g @angular/material:materialNav --name=main-nav

#### What is the use-case or motivation for changing an existing behavior?
Alignment with CLI, meet developer expectations.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.0-rc.5
@angular/cdk                       6.0.0-rc.12
@angular/material                  6.0.0-rc.12

#### Is there anything else we should know?
The --prefix argument will still work.

**Comment by DevVersion** [comment]
Thanks for your issue. This has been fixed at some point: https://github.com/angular/material2/pull/11738
