### ISSUE TITLE
How to style md-tab?

### ISSUE THREAD

**Issue by RedFour** [angular/material2#1092]
How do I style the md-tab?

I've created a few test tabs using the documentation. But I can't figure out how to make the tab's width to be smaller. The default width is too large for mobile screens.

```html
<md-tab-group selectedIndex=0>
  <md-tab style="width:50px">
    <template md-tab-label>Tab1</template>
      <h1>Some more tab content</h1>
      <p>...</p>
    <template md-tab-content>
    </template>
  </md-tab>
  <md-tab>
    <template md-tab-label>Tab2</template>
    <template md-tab-content>
      <h1>Some more tab content</h1>
      <p>...</p>
    </template>
  </md-tab>
</md-tab-group>
```

**Comment by jelbourn** [comment]
This would fall under #123

**Comment by hstevensagain** [comment]
@jelbourn, @RedFour seems to specifically be talking about [this](https://github.com/angular/material2/blob/master/src/lib/tabs/tab-group.scss#L34), which doesn't look slated for theming at the moment. Dynamic changes to the width of the tabs probably aren't in the scope of app wide theming either.

Imo md-tab-labels shouldn't have a min-width. They should expand and contract to the width of the md-tab-group, keeping the tabs responsive after that is the developer's job.

I get that there is a lot more work to be done on md-tabs, for the mean time changing the `min-width: 160px;` to `width: 100%;` would make md-tabs a lot more usable and responsive.

**Comment by hstevensagain** [comment]
@RedFour Give this a go.
```
/deep/ .md-tab-label {
  min-width: 1px !important;
}
```

**Comment by RedFour** [comment]
@hstevensagain thx! the css code you gave worked!
```
/deep/ .md-tab-label {
  min-width: 1px !important;
}
```

**Comment by sebaswn** [comment]
@hstevensagain @RedFour I'm having the same problem, but the css code above isn't working... any other workarounds?

**Comment by ravinderpayal** [comment]
@RedFour where did you added this code

**Comment by luisfpg** [comment]
@RedFour @ravinderpayal Actually the class name is *mat-tab-label*.
Hence, the correct style is:
```css
.mat-tab-label {
  min-width: 1px !important;
}
```

**Comment by mist3r3** [comment]
Do you know how we can do the same on only one tab? tried pretty much everything without success.

**Comment by axhcypod** [comment]
can we open this? I can't get anyone of these examples working..

**Comment by krisklosterman** [comment]
I would like to be able to style the tabs also, or at least have them stretch the full length of the md-tab-group

**Comment by captain-melanie** [comment]
@mist3r3 you can specify the element number

```
/deep/ .mat-tab:nth-child(1) {
    min-width: 100px !important;
  }
```

**Comment by jdewell** [comment]
What if you need smaller tabs on only one page not the entire application.

**Comment by jdewell** [comment]
I found the answer. You use the ::ng-deep
        ::ng-deep.mat-tab-label, ::ng-deep.mat-tab-label-active{
            min-width: 0!important;
            padding: 3px!important;
            margin: 3px!important;
        }

**Comment by jdewell** [comment]
I got the page I wanted the smaller tabs like this:
        #groupTabGroup ::ng-deep.mat-tab-label, ::ng-deep.mat-tab-label-active{
            min-width: 0;
            padding: 3px;
            margin: 3px;
        }
I had to give the mat-tab-group an id and specify that id in the css.
