### ISSUE TITLE
mat-spinner don't show/hide inside when is a prefix or suffix of mat-form-field

### ISSUE THREAD

**Issue by carlospalacin** [angular/material2#10936]
#### Bug, feature request, or proposal:
When I try show or hide spinner like a prefix or suffix inside of mat-form-field, don't appear.

#### What is the expected behavior?
I should be able to control the state of the spinner from a variable
```
<mat-form-field>
    <input matInput placeholder="Slug" formControlName="slug">
    <mat-spinner matSuffix *ngIf="showSpinner" mode="indeterminate" diameter="17"></mat-spinner>
</mat-form-field>
```
#### What is the current behavior?
If I change the variable showSpinner by true or false, the spinner never appear.
But if the variable has true value initially don't appear again, but if I put the focus on input, appear the spinner.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 5.2.8
material 5.2.4

**Comment by rsfernandes** [comment]
I'm facing the same issue here. 

angular 5.2.11
material 5.2.4

**Comment by mmalerba** [comment]
It seems to be working for me: https://stackblitz.com/edit/angular-material2-issue-ra2yyl?file=app/app.component.html can you please post a stackblitz repro if it's still an issue for you
