### ISSUE TITLE
[MatSelect] trigger MatSelectChange when setting the value with "writeValue" or "value"

### ISSUE THREAD

**Issue by richardsengers** [angular/material2#10931]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Trigger the MatSelectChange  when setting the select value programmatically

#### What is the current behavior?
The value of the dropdown is set, but no event is triggered

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-lkuscv

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 5.2.5

**Comment by crisbeto** [comment]
The `selectionChange` event only fires when the value was changed by the user. From the docs:

> Event emitted when the selected **value has been changed by the user**

The `valueChange` event should fire for all value changes.

**Comment by CAspeling** [comment]
How would one then manually trigger that selectionChange to force the MatSelectChange to display desired text?

**Comment by tdhulster** [comment]
> How would one then manually trigger that selectionChange to force the MatSelectTrigger to display desired text?

Having the same issue here where a initial selection is not showing up 😞

**Comment by CAspeling** [comment]
@tdhulster I have not. I can't even get 

```javascript
    this.mySelect.selectionChange.emit(new MatSelectChange(this.mySelect, 'example text'));
```

to trigger the change if button of some kind got clicked.
