### ISSUE TITLE
md-icon-button in md-toolbar has icon displaced

### ISSUE THREAD

**Issue by Lavan** [angular/material2#1093]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

The icon should be centered in the button.
#### What is the current behavior?

The icon is displaced 8px upwards to be very close to outer edge of the button.
#### What are the steps to reproduce?

http://plnkr.co/edit/ljTlfhIkQeksCEGimtXM?p=preview
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.0.0-rc.5, angular2-material-alpha.7-4
Replicated on Windows 10 using Chrome, Firefox, Edge and IE 11.
#### Is there anything else we should know?

Changing the CSS style `line-height` from 24px to 40px (to correspond with the width and height of the button) seems to solve the issue.

**Comment by DzmitryShylovich** [comment]
I think the proper solution would be to add the following [here](https://github.com/angular/material2/blob/abcc6af54df6125075dc465715b246dfdbb5b364/src/lib/button/button.scss#L47)
```
.md-button-wrapper {
    min-height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
}
```
