### ISSUE TITLE
matTooltip on matMenuTriggerFor cannot be closed

### ISSUE THREAD

**Issue by pavel-agarkov** [angular/material2#10948]
#### Bug
If `matMenuTriggerFor` has a `matTooltip` then after menu is closed tooltip will be shown again.
But it won't be hidden until user clicks somewhere or hover trigger button again.
Manual call to `MatTooltip.hide()` does not work in this situation.

#### What is the expected behavior?
Not show tooltip after menu is closed as it was in previous version or make it closable.

#### What is the current behavior?
Tooltip is shown and cannot be closed.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-dozdbn

**Comment by pavel-agarkov** [comment]
Looks like tooltip is shown when element receives a focus by keyboard.
When menu closed `matMenuTriggerFor` receives focus and tooltip is shown.
Probably tooltip cannot be hidden until element has focus.

**Comment by pavel-agarkov** [comment]
Calling `HTMLElement.focus()` on `menuClosed` completely solves the problem.
https://stackblitz.com/edit/angular-material2-issue-m6e4un
It even continue to show tooltip if menu was closed by _Ecs_

**Comment by varunprakas** [comment]
In material 5.x.x we can use 

```
<button mat-icon-button class="actions" [matMenuTriggerFor]="menu"  #menuTrigger="matMenuTrigger"  matTooltip="tooltip here" (menuClosed)="menuTrigger.focus()">
        <mat-icon class="actions"></mat-icon>
</button>

 <mat-menu #menu="matMenu" [overlapTrigger]="false" class="related-doc-menu">
        <button mat-menu-item >
title goes here !
        </button>
       
    </mat-menu>   
  
```
