### ISSUE TITLE
Regression: Microsoft Edge: Angular material select component browser freezes after select change/ same for expansion panel on expand, opening a menu or a dialog

### ISSUE THREAD

**Issue by rurziceanu** [angular/material2#10955]
#### Bug, feature request, or proposal:
Bug. It was working fine on edge browser before 6.0.0-rc.12.
The browser freezes and stops responding. No error in console, nothing. Very hard to debug and see where is the issue
Works well with the rest of the browsers

#### What is the expected behavior?
To work normally. Not to freeze the browser.

#### What is the current behavior?
Microsoft Edge browser freezes and stops responding after select change event. Same for expansion panel on expand

#### What are the steps to reproduce?
Providing a StackBlitz: I did not have the time yet. I will provide soon
Add a select with change event. This is also reproducible with expansion panel on expand, opening a menu or a dialog

#### What is the use-case or motivation for changing an existing behavior?
Bug. Regression 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.0.0-rc.12

#### Is there anything else we should know?
No

**Comment by andrewseguin** [comment]
Sorry for the trouble, this is likely due to an Angular bug related to how the CLI optimizes the build for prod. https://github.com/angular/angular/issues/23401

Are you seeing this when you use `ng serve --prod`?

**Comment by rurziceanu** [comment]
Hi, 
Thank you for the answer. 
Yes, it is on build --prod
By the way,
I can't wait for version 6 release. Great job :)

**Comment by rurziceanu** [comment]
Is there a way to work around this with build --prod? Or I just have to wait until this is fixed?

**Comment by andrewseguin** [comment]
Unfortunately I don't know of a workaround. I have the same issues on a personal app that I'm wanting to upgrade as well. Closing since its tracked in Angular core and coming to a release soon
