### ISSUE TITLE
mat-dialog's data get's cut when window.print()

### ISSUE THREAD

**Issue by pawmel** [angular/material2#10957]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
window.print() should print all of the data in dialog

#### What is the current behavior?
window.print() only prints part of the data

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-y68uhq?file=app/dialog-content-example-dialog.html

#### What is the use-case or motivation for changing an existing behavior?
printing invoice for example

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 5.2.7, material 6.0.0 beta 4, firefox and chrome

**Comment by crisbeto** [comment]
I'd say that this is expected since the dialog can't be rendered off the page. Closing since we avoid dealing with print styles in general.

**Comment by ctolene** [comment]
I think this issue should be re-opened. This is really annoying. May have to digress back to bootstrap modals..

**Comment by pawmel** [comment]
> I think this issue should be re-opened. This is really annoying. May have to digress back to bootstrap modals..

I ended up moving the data to outside the dialog to defferent component

**Comment by ctolene** [comment]
I was able to counter this issue with the following function called by a print link within the dialog:

`public printWindow(): void {
    let virtualWindow: any = window.open('', 'PRINT', 'height=400,width=800');
    virtualWindow.document.write('<html><head><title>Print</title>');
    virtualWindow.document.write('</head><body>' + document.getElementById('dialog-print').innerHTML + '</body></html>');
    virtualWindow.document.close(); // necessary for IE >= 10
    virtualWindow.focus(); // necessary for IE >= 10
    setTimeout(t => {
      virtualWindow.print();
      virtualWindow.close();
    }, 1000); // Give the DOM time to render images before printing.
  }`

It's a bit hacky, but it works for now. Tested on desktop and mobile & all the latest browsers. The only issue lies in how many images are to be printed, where they wont display if virtualWindow.print() is hit before they load.

**Comment by rafaband** [comment]
I can't print documents with more than one page if the content inside a Material Dialog, the only way it works is sending the content to another window and duplicate all the dialog content to this new window. 

It's looks like some css rule of the Material blocking the content to paginate.
