### ISSUE TITLE
Standalone toggle not aligned with button 

### ISSUE THREAD

**Issue by WizardPC** [angular/material2#10958]
#### Bug, feature request, or proposal:

Bug ?

#### What is the expected behavior?

Standalone toggle and button with equivalent (?) CSS will look the same.

#### What is the current behavior?

A little default in alignement
![issue](https://user-images.githubusercontent.com/11718892/39122872-736c47e8-46f6-11e8-9294-899ea7d4180d.PNG)

#### What are the steps to reproduce?
Inside the group it's perflectly aligned.

[https://stackblitz.com/edit/toggle-stack](https://stackblitz.com/edit/toggle-stack)

#### What is the use-case or motivation for changing an existing behavior?

My use case is a text editor toolbar, some actions are toggle (like in the doc with align left, right, center...) but others are button (like select all, clear format, cut...). So i try to adapt button inside toggle-group with CSS.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

See SB

**Comment by josephperrott** [comment]
Closing as obsolete as the toggle button and button have been gone through a refresh, if you find this issue to occur again please open up a new issue for us to take a look.
