### ISSUE TITLE
md-fab creates and leaves md-ripple-fade-in inner div on click event

### ISSUE THREAD

**Issue by pgg** [angular/material2#1096]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

To not duplicate and leave the inner div
#### What is the current behavior?

Duplicates the md-ripple-fade-in inner div
#### What are the steps to reproduce?

Markup:

```
<button md-fab color="primary" (click)="smaller()">
    <md-icon>remove</md-icon>
  </button>
```

Run app, open button in chrome dev tools inspector, you should see something like this:

```
<div class="md-button-ripple md-button-ripple-round" md-ripple="" md-ripple-background-color="rgba(0, 0, 0, 0)" ng-reflect-trigger="[object HTMLButtonElement]" ng-reflect-color="rgba(255, 255, 255, 0.2)" ng-reflect-background-color="rgba(0, 0, 0, 0)">
  <div class="md-ripple-background"></div>
</div>
```

Click 4 times on button and you will see something like this:

```
<div class="md-button-ripple md-button-ripple-round" md-ripple="" md-ripple-background-color="rgba(0, 0, 0, 0)" ng-reflect-trigger="[object HTMLButtonElement]" ng-reflect-color="rgba(255, 255, 255, 0.2)" ng-reflect-background-color="rgba(0, 0, 0, 0)">
  <div class="md-ripple-background" style="background-color: rgba(0, 0, 0, 0);"></div>
  <div class="md-ripple-foreground md-ripple-fade-in" style="left: -11.3431px; top: -19.3431px; width: 90.6863px; height: 90.6863px; transition-duration: 0.1s; background-color: rgba(255, 255, 255, 0.2);"></div>
  <div class="md-ripple-foreground md-ripple-fade-in" style="left: -36.0088px; top: -12.0088px; width: 114.018px; height: 114.018px; transition-duration: 0.1s; background-color: rgba(255, 255, 255, 0.2);"></div>
  <div class="md-ripple-foreground md-ripple-fade-in" style="left: -34.4004px; top: -11.4004px; width: 112.801px; height: 112.801px; transition-duration: 0.1s; background-color: rgba(255, 255, 255, 0.2);"></div>
  <div class="md-ripple-foreground md-ripple-fade-in" style="left: -34.4004px; top: -11.4004px; width: 112.801px; height: 112.801px; transition-duration: 0.1s; background-color: rgba(255, 255, 255, 0.2);"></div>
</div>
```
#### Which versions of Angular, Material, OS, browsers are affected?

```
"@angular/common": "2.0.0-rc.5",
"@angular/compiler": "2.0.0-rc.5",
"@angular/core": "2.0.0-rc.5",
"@angular/forms": "0.3.0",
"@angular/http": "2.0.0-rc.5",
"@angular/platform-browser": "2.0.0-rc.5",
"@angular/platform-browser-dynamic": "2.0.0-rc.5",
"@angular/router": "3.0.0-rc.1",
"@angular2-material/button": "^2.0.0-alpha.7-2",
"@angular2-material/core": "^2.0.0-alpha.7-2",
"@angular2-material/icon": "^2.0.0-alpha.7-2",
"@angular2-material/progress-circle": "^2.0.0-alpha.7-2",
"@angular2-material/toolbar": "^2.0.0-alpha.7-2"
OSX, Chrome  52.0.2743.116 (64-bit)
```
#### Is there anything else we should know?

No

**Comment by tylermassey** [comment]
I'm experiencing the same issue with `<md-button>`.

**Comment by Ifegwu** [comment]
I have been seeing this attitude in my codes
`<button md-fab class="md-primary"></button>`
I think <button></button> is the cause of this strange behavior. Kindly give me a feedback when this bug is fixed. Thanks in advance.

**Comment by Ifegwu** [comment]
I have been seeing this attitude in my codes
`<button md-fab class="md-primary"></button>`
I think `<button></button>` is the cause of this strange behavior. Kindly give me a feedback when this bug is fixed. Thanks in advance.

**Comment by Ifegwu** [comment]
when one replaces `<button></button>` with `<md-button></md-button` as seen in this code: 
` <md-button md-fab class="md-primary" href="#"><i class="material-icons demo-toolbar-icon">settings</i></md-button><hr>` 
The bug issue is revolved, but the material icon failed to centralize.

**Comment by Ifegwu** [comment]
When one replaces `<button></button>` with `<md-button></md-button>` the bug issue is resolved as seen in the code below:
` <md-button md-fab class="md-primary" href="#"><i class="material-icons demo-toolbar-icon">settings</i></md-button><hr>`
But the material icon fails to centralize.

**Comment by lednhatkhanh** [comment]
This is exactly what happens to me right now.

**Comment by nikolasp** [comment]
@Ifegwu This is not a good solution because if you change `button` to `md-button` you can't use `disabled` attribute.

**Comment by vapits** [comment]
I have exactly the same thing:
Before click:
![image](https://cloud.githubusercontent.com/assets/8594758/18088340/73cd8924-6eba-11e6-83b2-7f2089556f60.png)
After click:
![image](https://cloud.githubusercontent.com/assets/8594758/18088346/7f61054a-6eba-11e6-8081-222eaac890ae.png)

**Comment by nikolasp** [comment]
Add temporary for button [disableRipple]="true" and it will resolve issue. After the fix, you can remove this.

**Comment by Ifegwu** [comment]
@nikolasp, this `[disableRipple]="true"` snippet did the miracle. Thanks a lot.

**Comment by ashleahhill** [comment]
@pgg Have you included the core styles? It's not documented (yet), but it fixed my issue and I got to keep the ripple effect.

 https://github.com/angular/material2/issues/1139

**Comment by vapits** [comment]
@ashleahhill how you did that?

**Comment by jelbourn** [comment]
@tinayuangao can you check that this is an issue? I suspect that this is obsolete as of alpha.9

**Comment by turbohappy** [comment]
I still have this issue on alpha 9.

**Comment by turbohappy** [comment]
Adding a theme fixed it for me on alpha.9

**Comment by tinayuangao** [comment]
This is obsolete on current master.

**Comment by narkissbv** [comment]
Just updated to alpha.10 and it still happens when not using any themes.
