### ISSUE TITLE
Datepicker not working if startView has property

### ISSUE THREAD

**Issue by hermanfransen** [angular/material2#10974]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It should work if `startView="property"`

#### What is the current behavior?
Error: Cannot read property 'focus' of null

#### What are the steps to reproduce?
Template:
```
<mat-form-field>
  <input matInput [matDatepicker]="picker" [min]="min" [max]="max" placeholder="Choose a date">
  <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
  <mat-datepicker #picker startView="startView" [startAt]="startAt"></mat-datepicker>
</mat-form-field>
```
Component:

```
export class AppComponent implements OnInit {

  min: Date = new Date(1900, 0, 1);
  max: Date = new Date(2007, 11, 31);
  startAt: Date = new Date(1987, 0, 1);
  startView: string = "multi-year"

  constructor() { }
  ngOnInit() { }
}
```

https://stackblitz.com/edit/angular-material-datepicker-startview-github-issue

#### What is the use-case or motivation for changing an existing behavior?
inapplicable

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0. Material 5.2.2. 

#### Is there anything else we should know?
if I change the template with `startView="multi-year"` there is no problem
Using a property value with `min`, `max` & `startAt` gives no problems at all. The same behaviour should also work with `startView`

**Comment by diicar** [comment]
<mat-datepicker #picker **[startView]**="startView" [startAt]="startAt"></mat-datepicker>

**Comment by crisbeto** [comment]
That's because you need to add square brackets around the `startView`. This will work:

```html
<mat-datepicker #picker [startView]="startView" [startAt]="startAt"></mat-datepicker>
```
