### ISSUE TITLE
Basic sidenav example in stackblitz does not work

### ISSUE THREAD

**Issue by brianpilati** [angular/material2#10979]
#### Bug, feature request, or proposal:
Bug:
The "Basic sidenav" example in stackblitz does not work.

#### What is the expected behavior?
When I see the example, it demonstrates how the sidenav should work. 

#### What is the current behavior?
A display with the text "SidenavcontentMain content".

#### What are the steps to reproduce?
1- Goto this page: https://material.angular.io/components/sidenav/overview
2- Click on the "Basic sidenav" example in stackblitz.
3- https://stackblitz.com/angular/qkkbgxrnxprd?file=app%2Fsidenav-overview-example.html

#### What is the use-case or motivation for changing an existing behavior?
I would like to see a correct working example.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I am on chrome

#### Is there anything else we should know?
Let me know how I can help

**Comment by andrewseguin** [comment]
The example is working correctly but maybe it's not easy to tell what's happening here. Prehaps we can add better colors or shadows that show off the sidenav better.

**Comment by brianpilati** [comment]
I added some more details before I realized that @mmalerba  had also created a request. I feel that both PRs improve the experience. In a way, I extended mmalerba' PR.

**Comment by mmalerba** [comment]
@brianpilati The basic example is just supposed to show off the very simplest usage of sidenav. An always open sidenav is something that some apps will want. The other examples highlight other features like toggling

**Comment by brianpilati** [comment]
@mmalerba thanks for the input. It was a great experience either way.
