### ISSUE TITLE
Supporting moment plugin in mat-datepicker

### ISSUE THREAD

**Issue by m-farahmand** [angular/material2#10972]
#### Bug, feature request, or proposal:
With change of Local-Id to fa-IR mat-datepicker showing wrong days of month and with selecting year or month name it jump to next of  them.

#### What is the expected behavior?
To accept moment plugin e.g. moment-jalaali.

#### What are the steps to reproduce?
[link](https://stackblitz.com/edit/angular-kvdteq)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
5.2.x

**Comment by mmalerba** [comment]
The `MomentDateAdapter` only supports the Gregorian Calendar. I've seen some users post about solutions they were working on for other calendars, including one who was working on support for the Jalaali Calendar (https://github.com/angular/material2/issues/5972 - https://github.com/peymanebrahimi/AngularMaterialJalaliDate) and one who was working on generic support for other calendars: (https://github.com/angular/material2/issues/2519 - https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter).

We consider this outside of the scope of Angular Material, but we hope the community will continue to share custom `DateAdapter` implementations they've worked on, so others can benefit too.

**Comment by m-farahmand** [comment]
@mmalerba  Tnx it working
