### ISSUE TITLE
bug(matPrefix): toggle mat-icon prefix with textarea

### ISSUE THREAD

**Issue by merlosy** [angular/material2#10977]
#### Bug, feature request, or proposal:

The prefix does not render properly when we toggle the display of the prefix.

#### What is the expected behavior?

It should render properly right away.

#### What is the current behavior?

I need to click on the textarea to trigger an update of the component

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/angular-mhjc4e?file=app/input-overview-example.html

Initial setup: prefix is hidden
- I click on "Toggle prefix" -> it should display but it is not
- click on the textarea field -> icon toggles!

This can be reproduced right after first rendering. Once it is successfully toggled, you can check/uncheck the box and it behaves fine.

#### What is the use-case or motivation for changing an existing behavior?
It's weird, and textarea seems to be the only form field with the issue.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest Angular and Material released
Can reproduce on Chrome 60, Firefox (recent), IE11 with basic recommended polyfills

**Comment by mmalerba** [comment]
Looks like some kind of change detection issue, weird that it only happens with textarea though. I'll investigate

**Comment by mmalerba** [comment]
It looks like this has been fixed in the 6.0 rc, here's a link to the plunker with deps changed to rc: https://stackblitz.com/edit/angular-mhjc4e-pdbf5d?file=app/input-overview-example.html

**Comment by merlosy** [comment]
Is there a chance this fix can be merged in a future 5.X.X release ?

**Comment by mmalerba** [comment]
I don't think we plan to do any more 5.x releases unless a critical bug comes up
