### ISSUE TITLE
<input readonly="boolean-variable"> is always true even the variable is false

### ISSUE THREAD

**Issue by jagabs** [angular/material2#10971]
#### Bug, feature request, or proposal:

readonly doesnt work with variables. 

#### What is the expected behavior?
The expected behavior if the boolean variable is true then its readonly if its false then its not readonly. 

#### What is the current behavior?
But in my case no matter what the value of the boolean variable, its always readonly.

#### What are the steps to reproduce?

Example:
https://stackblitz.com/edit/angular-qxpfsm
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/material": "~5.2.4",
 "@angular/cdk": "~5.2.4",
 "@angular/compiler": "~5.0.0",
    "@angular/core": "~5.0.0",
"typescript": "~2.4.2",

**Comment by eTallang** [comment]
You need to wrap the `readonly` attribute in square brackets in order to bind to your variable. In your case, you bind to the static string value "summary".

**Comment by jagabs** [comment]
my bad hahahahahaha
