### ISSUE TITLE
Question: Upgrading from 2.0.0-beta.10 to 5.2.4 version

### ISSUE THREAD

**Issue by petrovic-ivan** [angular/material2#10987]
I would like to confirm is there any risk huge risk to using 2.0.0-beta.10 for early production website? I saw that a lot of things happened between 2.0.0-beta.10  and 5.2.4 versions such as performance improvement, bug fixes and new features but also with a lot of breaking changes. Is that any risks to postpone upgrade in project for later?

**Comment by andrewseguin** [comment]
I would recommend using the latest version of Material/CDK possible. The more code you add, the more you will need to migrate later on. It's not trivial to update so many versions at once.
