### ISSUE TITLE
Material UI components position and size move/change from default

### ISSUE THREAD

**Issue by owlstack** [angular/material2#10983]
#### Bug, feature request, or proposal:
Modal Material UI components position and size moves/changes from default depending on last action they were used in. 

#### What is the expected behavior?
Material UI components size and position should not change depending on last action where material UI component was used in.

#### What is the current behavior?
Modal Material UI components position and size moves/changes from default depending on last action they were used in. 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

I don't have a stackBlitz but I'll see if I can create a basic one later. 

Steps

 Create a modal material dialog. Set a unique width and height for dialog on one page. Then navigate to another page and set the width and height differently for dialog on that page. Then go back to original page and modal dialog is now the previous width and height and not the original width and height for that modal material dialog.

Create a snackbar that appears from the bottom of the page. Navigate to another page that also uses a snackbar. Show snackbar on second page after hiding a big element, so that the snackbar accidentally moves up across the page. Then go back to original page, the snackbar is shown in the center/pushed up in the same position as the previous page even though it should appear from the bottom on this page (as there is no hidden big element). 

#### What is the use-case or motivation for changing an existing behavior?
Behavior should be consistent across pages and for each individual page. Currently, the modal components change based on last time they were on the page. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 5.2.1

**Comment by andrewseguin** [comment]
Thanks for the detailed issue. Providing a StackBlitz that demonstrates the problem would really help, do you mind creating one? Thanks!

**Comment by crisbeto** [comment]
Closing the issue since it's been a while and there's no example. It can be reopened if we get more info.
