### ISSUE TITLE
MatPaginator page select expands the wrong direction

### ISSUE THREAD

**Issue by YoannBureau** [angular/material2#10994]
#### Bug, feature request, or proposal:
When resizing the browser, the MatSelect in the MatPaginator can expand outside of the visible part of the page (expanding to the bottom)

#### What is the expected behavior?
The MatSelect should expand to the top instead

#### What is the current behavior?
It expands to the bottom and gets out of browser bounds

#### What are the steps to reproduce?
1. Open this blitz: https://stackblitz.com/angular/godjgllxvxr?file=app%2Ftable-pagination-example.ts
2. Ensure there is some blank space below the MatTable when loading the preview
3. Click a first time on the MatSelect in the MatPaginator
4. Resize the preview to set the browser limit just below the MatTable
5. Try to open the MatSelect again : it displays itself to the bottom instead of the top
![alt text](https://nsa39.casimages.com/img/2018/04/25/180425094743462563.png "")

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Running:
Windows 7 64bits
Chrome 65
@angular 5.2.10
@angular/material 5.2.4

**Comment by andrewseguin** [comment]
Thanks for reporting, it is an issue but has been fixed. See this issue for more details: #10560
