### ISSUE TITLE
md-button-toggle-group, can only set value through child

### ISSUE THREAD

**Issue by gregbown** [angular/material2#1100]
I'm not sure if this was intended, however I was trying to set the value of a md-button-toggle-group via a reference and discovered that a md-button-toggle-group will only be exposed as an ElementRef
and thus setting it's value is not possible.  The md-button-toggle, however; will be exposed as an MdButtonToggle, thus it allows access to its group and setting the group value.
@ViewChild('toggleButton') toggleButton: MdButtonToggle;
@ViewChild('toggleGroup') toggleGroup: MdButtonToggleGroup;
#### What is the expected behavior?

@ViewChild('toggleGroup') toggleGroup: MdButtonToggleGroup; should provide a reference to the MdButtonToggleGroup and allow its value to be set.
this.toggleGroup.value = 'swanky'; // <- does not work
#### What is the current behavior?

MdButtonToggleGroup is only accessible through a child MdButtonToggle.
this.toggleButton.buttonToggleGroup.value = 'swanky'; // <- this works
#### What is the use-case or motivation for changing an existing behavior?

If the UI is updated and the md-button-toggle-group value does not match.
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2 rc5, Material 2 alpha 7-4, Windows 10, chrome.

**Comment by jelbourn** [comment]
In your template you just have to put 
```html
<md-toggle-group #toggleGroup="mdButtonToggleGroup">
```

And the `@ViewChild` will give you the correct thing.

**Comment by doender** [comment]
I have a similar problem (Material 2.0.0-beta.1). Using ViewChild, the toggle group is always undefined (in the `AfterViewInit` hook):

```
<md-button-toggle-group #alignment="mdButtonToggleGroup" (change)="changeAlignment($event)">
   <md-button-toggle value="top">
      <md-icon>vertical_align_top</md-icon>
   </md-button-toggle>
   <md-button-toggle value="center">
      <md-icon>vertical_align_center</md-icon>
   </md-button-toggle>
   <md-button-toggle value="bottom">
      <md-icon>vertical_align_bottom</md-icon>
   </md-button-toggle>
</md-button-toggle-group>
```

and

```
 @ViewChild('alignment') alignment:MdButtonToggleGroup;
```
