### ISSUE TITLE
File dates of npm package are in the past (1985)

### ISSUE THREAD

**Issue by rhalff** [angular/material2#11009]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

(Build?) server has time configured correctly.

#### What is the current behavior?

Date is in the past  (1985)

#### What are the steps to reproduce?

```bash
mkdir test
cd test
npm init -y
npm add @angular/cdk
ls -hal node_modules/@angular/cdk | head
total 228K
drwxr-xr-x 20 rhalff rhalff 4.0K Apr 25 19:32 .
drwxr-xr-x  3 rhalff rhalff 4.0K Apr 25 19:32 ..
drwxr-xr-x  3 rhalff rhalff 4.0K Apr 25 19:32 a11y
-rw-r--r--  1 rhalff rhalff  232 Oct 26  1985 a11y.d.ts
-rw-r--r--  1 rhalff rhalff  193 Oct 26  1985 a11y.metadata.json
-rw-r--r--  1 rhalff rhalff  181 Oct 26  1985 a11y-prebuilt.css
-rw-r--r--  1 rhalff rhalff  761 Oct 26  1985 _a11y.scss
drwxr-xr-x  3 rhalff rhalff 4.0K Apr 25 19:32 accordion
-rw-r--r--  1 rhalff rhalff  237 Oct 26  1985 accordion.d.ts
```

Same seems to be the case for @angular/material

@angular/cli does show the correct date.

#### What is the use-case or motivation for changing an existing behavior?

It's confusing. Especially when hunting for a bug in the same area.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

At least 5.2.5 and 6.0.0-rc.12

**Comment by rhalff** [comment]
@LayZeeDK 
![b044mjaiqaa4kkj](https://user-images.githubusercontent.com/274358/39274680-a88f38c8-48da-11e8-9700-23a992f8c116.jpg)

**Comment by josephperrott** [comment]
Closing as this is working as expected as we now use `npm 6.0` see https://github.com/npm/npm/issues/20439 for npm's explanation.
