### ISSUE TITLE
ERROR in Metadata version mismatch for module found version 4 expected 3

### ISSUE THREAD

**Issue by sanjeevkumarthakur** [angular/material2#11019]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
