### ISSUE TITLE
getting warnings while installing material what should be the supporting version of material

### ISSUE THREAD

**Issue by msj4994** [angular/material2#11025]
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

 "@angular/animations": "^4.4.7",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",

#### Is there anything else we should know?
getting error as 

npm WARN @angular/cdk@5.2.5 requires a peer of @angular/core@>=5.0.0 <7.0.0 but none was installed.
npm WARN @angular/cdk@5.2.5 requires a peer of @angular/common@>=5.0.0 <7.0.0 but none was installed.
npm WARN @angular/material@5.2.5 requires a peer of @angular/core@>=5.0.0 <7.0.0 but none was installed.
npm WARN @angular/material@5.2.5 requires a peer of @angular/common@>=5.0.0 <7.0.0 but none was installed.

+-- @angular/cdk@5.2.5
+-- UNMET PEER DEPENDENCY @angular/common@4.4.7
+-- UNMET PEER DEPENDENCY @angular/core@4.4.7
`-- @angular/material@5.2.5

**Comment by crisbeto** [comment]
The warning says it all. The major version of all of the `@angular/*` dependencies has to match. In this case you should update everything to 5+.
