### ISSUE TITLE
About development specification

### ISSUE THREAD

**Issue by baihech** [angular/material2#11022]
feature request

Please see [Paginator examples](https://material.angular.io/components/paginator/examples)，
[git address](https://github.com/angular/material2/blame/20a23f16e8ac1ced29172709cc837fa500b6377b/src/material-examples/paginator-configurable/paginator-configurable-example.html#L20)，
 `(page)="pageEvent = $event"` code is not conforming to the development specification，here need a function，not an attribute。
You've changed the API again again again again.

**Comment by JohnnyRuiGe** [comment]
damn! it seem like a  plaything. do as one pleases！

**Comment by andrewseguin** [comment]
Please follow the issue template to help us understand your feature request. It's not clear to me what you are asking for
