### ISSUE TITLE
Number input fire 2 event on valueChanges

### ISSUE THREAD

**Issue by Typhon0** [angular/material2#11020]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Only fire 1 event when we click on the up arrow of an input number.

#### What is the current behavior?

When we click on the up arrow of the input number, valueChanges fire 2 events .

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-number-input-event

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.0-rc2

**Comment by crisbeto** [comment]
[The same happens when you have a plain `input`](https://stackblitz.com/edit/angular-material2-issue-number-input-event-qjkub4?file=app/app.component.html) which means that the issue is probably in core. Please file an issue in the main repo: https://github.com/angular/angular/issues.
