### ISSUE TITLE
Material Design V2

### ISSUE THREAD

**Issue by spock123** [angular/material2#11039]
Hey guys,
- very stubborn rumors have it that Google will introduce an update to the Material Design Spec (version 2) at Google I/O in a few weeks time.

How will this project address this? Any thoughts and ideas?

Thanks for a super great UX library I enjoy using every day.

**Comment by LoganDark** [comment]
Material 3, possibly? :P

**Comment by Chan4077** [comment]
@LoganDark Isn't the number just for the version? (Angular Material 2 -> Angular 2.x)

**Comment by LoganDark** [comment]
Yeah, it has been.

**Comment by RainingNight** [comment]
Very much looking forward to Material Design 2,  I enjoy using every day.

**Comment by jelbourn** [comment]
Nothing to report at this time.
