### ISSUE TITLE
MatStepper cuts off mat-card-actions partially

### ISSUE THREAD

**Issue by uahic** [angular/material2#11065]
#### Bug, feature request, or proposal:
Seems to be a bug

#### What is the expected behavior?
I would like to have the material cards to represent the form content, very much like google's register/login form. 

#### What is the current behavior?
It actually works but the width of the buttons in <mat-card-actions> seems to be cut-off on the borders (of the content area). Seems to be some CSS issue. 

The steps to reproduce:
Just build up some test component and use a structure like:

```
<mat-card>
  <mat-horizontal-stepper>
    <mat-step [stepControl]=...>
        <mat-card-title>...</mat-card-title>
        <mat-card-content>  ... here is s some form  </mat-card-conent>
        <mat-card-actions fxLayoutAlign="space-between">
               <button mat-raised-button matStepperPrevious>Back</button>
               <button mat-raised-button matStepperNext>Next</button>
   </mat-step>

    ... maybe some other step
  </mat-horizontal-stepper>
</mat-card>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cdk@5.2.5
@angular/material@5.2.5

**Comment by donroyco** [comment]
Please provide a StackBlitz reproduction of your issue. StackBlitz starter: https://goo.gl/wwnhMV

**Comment by josephperrott** [comment]
Closing as no reproduction has been provided.
