### ISSUE TITLE
[feature request] md-input blur method

### ISSUE THREAD

**Issue by gregbown** [angular/material2#1107]
#### feature request, or proposal:

md-input has a focus method, could a blur method be added?
#### What is the desired behavior?

The user hits the enter key while focused inside an md-input inside a form.
The form submits, the md-input focus can be moved to the submit button, next tab index or just blurred.

a directive placed on the md-input is able to call the blur method.
a directive placed on the md-input is able to tab to next tab index.
#### What is the current behavior?

The user hits the enter key while focused inside an md-input inside a form.
The form submits, the form handler resets the form so now the input is empty, the input still has focus and thus invalidates when the user changes focus.  There is no way to get a reference on the input inside the md-input with a directive because:
If you reference the MdInput, there is no blur method.
If you reference ElementRef you cannot get to the children... input to call blur()
#### What is the use-case or motivation for changing an existing behavior?

Being able to submit on enter when inside an MdInput and remove its focus.
#### Versions of Angular, Material, OS, browser?

Angular 2 rc5, Material 2 alpha 7-4, Windows 10, chrome

**Comment by jelbourn** [comment]
@gregbown we will be refactoring `md-input` soon such that you'll always have access to the full `<input>` API without the library having to manually pass-through everything.

**Comment by mmalerba** [comment]
`md-input-container` is now available which gives you access to the underlying `input` element

**Comment by parliament718** [comment]
@mmalerba  I don't see how md-input-container gives access the input; there are no public properties to access the underlying element. 
![screen shot 2016-12-29 at 8 55 09 am](https://cloud.githubusercontent.com/assets/3580270/21545280/58aea0d0-cda4-11e6-8cf0-c34e501cd8b6.png)

What is the purpose of adding a public focus() method, but directing to a private API for blur()? 

I'm using 2.0.0-beta.1

**Comment by mmalerba** [comment]
Since you now specify the native input in your template you should be able to do whatever you want with it:

```
<md-input-container>
  <input md-input #myInput>
</md-input-container>
```

you can then do `myInput.blur()`
