### ISSUE TITLE
How to dynamically hide and show material tab?

### ISSUE THREAD

**Issue by KrishnaAnanthi** [angular/material2#11077]
#### What is the current behavior?
enable disable tab functionality is available but i couldnt find hide/show features

**Comment by tmburnell** [comment]
Does putting an ngIf on the tab do what you want?

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Comment by mateuslopes** [comment]
This is just a feature request, so that we are able to show/hide mat-tab elements. Very useful and needed feature for sure. 
But, what kind of investigation is needed to understand this simple request? I think closing this is just a comfortable way to not solve the problem. :(
