### ISSUE TITLE
mat-slide-toggle blink with BrowserAnimationsModule

### ISSUE THREAD

**Issue by pacozevallos** [angular/material2#11075]
I am working with mat-slide-toggle in a table, when I activate or deactivate it a blink occurs. This happens to me when I include the BrowserAnimationsModule and in the browsers: Chrome, Opera. In Firefox and Safari it works without problems.

Here my stackblitz: https://stackblitz.com/edit/angular-hr7suh

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Comment by pacozevallos** [comment]
How can I follow the template? what template?
