### ISSUE TITLE
MatChipList's input is not styledi like MatInput while in disabled state

### ISSUE THREAD

**Issue by Antoniossss** [angular/material2#11089]
#### Bug, feature request, or proposal:
BUG/PROPOSAL

#### What is the expected behavior?
I would like to have ability to disable chip list like I do with any other input.

#### What is the current behavior?
Chip list is not styled when disabled. Styling is fine when input is the first element in mat-form-field but then chips are displayed incorectly (input is above chips)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-6v3y9r

**Comment by AmandaFoster** [comment]
The same issue applies to inputs marked readonly; the underline animation is triggered and the colors of the underline and label take on the primary theme color.

https://stackblitz.com/edit/angular-6v3y9r-rgggep

**Comment by tinayuangao** [comment]
@Antoniossss You should put `disabled` on `mat-chip-list` and do not use `matInput` on `matChipInputFor` because `matInput` does nothing here.

**Comment by Antoniossss** [comment]
I have added your proposal to stackblitz - input is still not styled like regular input on disabled state.

**Comment by tinayuangao** [comment]
@Antoniossss I found your updated stackblitz disabled state for chip list looks correct. Could you please explain where "it still not styled like regular input"? Thanks

**Comment by Antoniossss** [comment]
https://stackblitz.com/edit/angular-6v3y9r-pmgeet?file=app/chips-input-example.html

Chip list input is still focusable even on disabled state.
