### ISSUE TITLE
MatDialogClose shouldn't set aria-label if it has text

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#11084]
In cases where a button has both text and a `mat-dialog-close`, the aria-label should not be set because it trumps the text. We should only set the label if either: the text is empty, or, the only text is within a `mat-icon`.

It _would_ make sense to add something like `Closes the dialog` with `aria-describedby` (via `AriaDescriber`) if we add an API to customize the message for i18n.

**Comment by dgfranklin** [comment]
Any status updates on this? @crisbeto , is there anything blocking your pull request?

**Comment by stevenyxu** [comment]
Thanks for the fix. It looks like it'll achieve what we're looking for. Could this please be prioritized for merge?

**Comment by dgfranklin** [comment]
It looks like there is a bug in the #11093. It only works if a button's text content is set when the directive's ngOnInit is called. However, that text is not set during the directive's ngOnInit if it's done via a binding (for example, with string interpolation).

I created [a demo](https://angular-lhz5rc.stackblitz.io) showing this behavior. Observe that (after opening the dialog) the "Incorrect" button has an aria-label set on it while the "Correct" button does not. It is expected that both buttons would not have an aria-label on them as they both have text.

**Comment by stevenyxu** [comment]
Thanks @dgfranklin I noticed this too and reported https://github.com/angular/material2/issues/15542 PTAL.
