### ISSUE TITLE
Acordion inside tabs not rendered correctly in initial state (invalid height)

### ISSUE THREAD

**Issue by Antoniossss** [angular/material2#11088]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Acordion to be rendered correctly

#### What is the current behavior?
Closed panels have invalid height

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ywvft3

Second and third tabls are invalid. Once tabs are expanded and closed, they remain correct.

**Comment by donroyco** [comment]
Duplicate of #5269, see [specific comment in there](https://github.com/angular/material2/issues/5269#issuecomment-365343567).

**Comment by Antoniossss** [comment]
Closing as duplicate and working workaround here 
https://github.com/angular/material2/issues/5269#issuecomment-385676028
