### ISSUE TITLE
md-dialog

### ISSUE THREAD

**Issue by origin1tech** [angular/material2#1110]
#### Bug, feature request, or proposal:

When will the dialog be included on npm @angular2-material/dialog does not exist last I checked.

#### What is the expected behavior?

Installation from NPM

#### What is the current behavior?

Package doesn't exist on npm.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?

latest material 2 alpha.

#### Is there anything else we should know?

If there's something that needs to be done to get this pushed to NPM and I can help just let me know. Gladly help out!

**Comment by fxck** [comment]
It's not ready yet. It's still missing backdrop https://github.com/angular/material2/pull/1041 amongst other things.

You can see the published packages here https://www.npmjs.com/~angular2-material

**Comment by jelbourn** [comment]
See #114.

The two main things it's missing before it could be released are the backdrop support (#1041) and focus-trapping.
