### ISSUE TITLE
When using bound FormControl with date picker, `FormControl.registerOnChange()` never fires

### ISSUE THREAD

**Issue by deathgaze** [angular/material2#11110]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Please refer to this example code: 
https://stackblitz.com/edit/angular-v6jmxw?file=app%2Fdatepicker-value-example.ts

In the example, I have the `date` bound to a FormControl: 
```
<mat-form-field>
  <input matInput [matDatepicker]="picker1" placeholder="Angular forms" [formControl]="date">
  <mat-datepicker-toggle matSuffix [for]="picker1"></mat-datepicker-toggle>
  <mat-datepicker #picker1></mat-datepicker>
</mat-form-field>
```

in the constructor, I set a change handler so I can know when the date was changed:
```
  constructor() {
    this.date.registerOnChange(() => console.log('form changed'))
  }
```

When I make a change to either the form input directly or by interacting with the date picker control, I expect to receive a change event.

#### What is the current behavior?
Change events never fire.

#### What are the steps to reproduce?
Please see this example: 
https://stackblitz.com/edit/angular-v6jmxw?file=app%2Fdatepicker-value-example.ts

#### What is the use-case or motivation for changing an existing behavior?
When a user modifies a FormControl, I might need to know what changed or when.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.4
Material: 5.2.3
TypeScript: 2.5.3
Browser: Chrome 66.0.3359.139 (Official Build) (64-bit)
OS: OS X High Sierra 10.13.4 (17E199)

**Comment by josephperrott** [comment]
Closing as this is working as expected, this is actually something at the Angular Platform level and not effected by a Material implementation.  You will see the same behavior if you use native html inputs alone as well.

To be listening for changes to `FormControl`s you should actually be subscribing to changes on the [`valueChanges`](https://angular.io/api/forms/AbstractControl#valueChanges).  The `registerOnChange` method that you are attempting to use is actually for when the control updates the model, not for whenever the control, model or view are updated.

To properly be informed of anytime that the `FormControl`'s value is updated `valueChanges` should be subscribed to.
