### ISSUE TITLE
Electron, Form Animations are not working for compoenents inside router-outlet

### ISSUE THREAD

**Issue by ysfjwd** [angular/material2#11117]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
In electron inputs should animate as per spec.

#### What is the current behavior?
When the component is behind router-outlet, In electron, the animations stop working. Mysteriously, the animation work in browser. 

I looked at the DOM. In browser, when touched, The DOM shows the class ```mat-touched``` applied to the ```mat-form-field``` element, however, in electron, the class ```mat-touched``` is never applied. It can only mean one thing, the touch event is not being registered.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

The issue is very specific to electron. In browser the behaviour is alright. I have made the repo with code 

https://github.com/ysfjwd/electron-ng-material-form-bug

```
clone, yarn install and gulp
```

#### What is the use-case or motivation for changing an existing behavior?
Its a bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular material: 5.25
OS: OSX
Typescript: 2.6.2
browser: Electron

#### Is there anything else we should know?

Although already shared, to ease everybody else, I am repeating myself 

>I looked at the DOM. In browser, when touched, The DOM shows the class ```mat-touched``` applied to the ```mat-form-field``` element, however, in electron, the class ```mat-touched``` is never applied. It can only mean one thing, the touch event is not being registered. Interestingly, all other animations, like button animation is working fine.

Thankyou for help.

**Comment by ysfjwd** [comment]
I can confirm that change detection is broken here.

**Comment by ysfjwd** [comment]
Debugged the issue. It is a mix of ngrx/router and zones. tried running zone changing inside `NgZone` and it is solved.

**Comment by LeParadoxHD** [comment]
> Debugged the issue. It is a mix of ngrx/router and zones. tried running zone changing inside `NgZone` and it is solved.

Can you post some example code please? I have the same issue.
