### ISSUE TITLE
bug(md-tooltip): tooltip is not removed when parent is

### ISSUE THREAD

**Issue by ivoviz** [angular/material2#1111]
Consider a scenario where there's a button inside a container. The button has a tooltip and on click it should set a variable to another value. Based on that value the container element is added / removed with `ngIf`. Simple example:

``` html
<div *ngIf="!hidden">
  <button
    md-button
    md-tooltip="Hide this button"
    tooltip-position="after"
    (click)="hidden = true">HIDE ME!</button>
</div>
```

After clicking the button the container div is removed, however, the tooltip remains still, no way to remove it.

[Plunkr example](http://plnkr.co/edit/GX8CnKNQ8Zlzm5Zras7r?p=preview).

**Comment by lghinet** [comment]
hello 
any workarounds ?

**Comment by ivoviz** [comment]
It's a bit hacky, but what I'm doing now is adding

```
MdTooltip.prototype.ngOnDestroy = function () {
    this._overlayRef.dispose();
    this._overlayRef = null;
};
```

to `node_modules/@angular2-material/tooltip/tooltip.js` (just put it after the `ngOnInit` prototype).

**Comment by gucheen** [comment]
@ivoviz 's hack still works in alpha.9, after the changes of project structure.
However, now need to edit the `~/node_modules/@angular/material/material.umd.js`.

**Comment by tapas4java** [comment]
@jelbourn , Just wanted to know any plan to fix this issue soon?
