### ISSUE TITLE
<table mat-table #table [dataSource]="dataSource">

### ISSUE THREAD

**Issue by deveshgour** [angular/material2#11123]
When I use  [dataSource]="dataSource" in our table then geting this issue

core.js:1449 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'dataSource' since it isn't a known property of 'table'.

**Comment by donroyco** [comment]
Have you checked the [Material table example](https://stackblitz.com/edit/angular-kyrxto?file=app/table-pagination-example.ts)?

**Comment by deveshgour** [comment]
I am using simple table tag those who have used in "material2-master\src\material-examples\table-pagination"

then i am getting following error

Uncaught (in promise): Error: Template parse errors:
Can't bind to 'dataSource' since it isn't a known property of '**table**'.

**Comment by donroyco** [comment]
Please change your issue so that it does [follow the issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md). It gives the team the information needed to investigate.

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Comment by kiwikern** [comment]
The example is from version 6 and you are probably still using version 5. See [this Stackoverflow thread](https://stackoverflow.com/a/50177140/4694994).
