### ISSUE TITLE
Git tag 5.2.4 is placed on master branch instead of branch 5.2.x

### ISSUE THREAD

**Issue by danmana** [angular/material2#11125]
#### Bug:
The git tag 5.2.4 is placed on master branch and can cause confusion when trying to look at the source code.  
The build is done on branch 5.2.x (the module downloaded from npm contains only the commits from branch 5.2.x).

When looking in github at the code from [tag 5.2.4](https://github.com/angular/material2/commits/5.2.4) you can see commits that belong to 6.0.0, but which are not actually packaged in the 5.2.4 npm module.

#### What is the expected behavior?
Git tag 5.2.4 should be on branch 5.2.x (commit 7abb1db79a2cb5e7978d38c422fcb7622710be70)

See tag 5.2.5, which is placed correctly on branch 5.2.x

#### Is there anything else we should know?

There is nothing wrong with the version 5.2.4 deployed in npm, it is build correctly against the 5.2.x branch, just the git tag is placed on the wrong branch.

Running `git branch -a --contains tags/5.2.4` outputs:
```
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/IgorMinar-docs/guide-schematics-update
  remotes/origin/andrewseguin-patch-1
  remotes/origin/andrewseguin-patch-2
  remotes/origin/master
  remotes/origin/revert-10743-demo-examples
  remotes/origin/rxjs6
  remotes/origin/virtual-scroll
```

Running `git branch -a --contains tags/5.2.5` outputs:
```
  remotes/origin/5.2.x
```

**Comment by jelbourn** [comment]
Should be fixed now
