### ISSUE TITLE
Angular material webpage html-css error 

### ISSUE THREAD

**Issue by nani554** [angular/material2#11121]
>>  Bug
![image](https://user-images.githubusercontent.com/22760241/39569342-8d9216f4-4ee2-11e8-8ec6-383dcf60126a.png)

https://material.angular.io/components/sidenav/overview

on going through the above angular material's webpage , found that there is an overflow issue which can be solved by making the main div's display block from inline-flex

// previously 
.docs-component-overview {
    display: inline-flex;
}

// my solution
.docs-component-overview {
    display: block;
}

>> just go to below link to see the error
https://material.angular.io/components/sidenav/overview

**Comment by donroyco** [comment]
There's a seperate repository for the Material website, see https://github.com/angular/material.angular.io. You can report the issue there.

**Comment by josephperrott** [comment]
Closing, if you would like to open the issue in the [material.angular.io repo](https://github.com/angular/material.angular.io) it can be considered there.
