### ISSUE TITLE
Cannot build AOT - 'Illegal state: Could not load the summary for directive CdkTrapFocus'

### ISSUE THREAD

**Issue by Tyler-V** [angular/material2#11124]
ng build --prod

`ERROR in : Illegal state: Could not load the summary for directive CdkTrapFocus in C:/Users/Tyler/Documents/GitHub/@ngx-easy/projects/easy-grid/node_modules/@angular/cdk/a11y/typings/index.d.ts.`

**Comment by donroyco** [comment]
Have you checked [this comment](https://github.com/angular/material2/issues/8070#issuecomment-341312300)?

**Comment by josephperrott** [comment]
From looking at this a bit it looks like this might be an issues with your environment's setup.  Were you able to try adding a `rootDir` to your tsconfig?

**Comment by Tyler-V** [comment]
Hi @josephperrott, thanks for the reply.

The issue listed above looks like the suggestion is to remove that line, not to add it unless I misunderstood.

Regardless, adding `"rootDir": "."` or `"src"` still results in the same `ERROR in : Illegal state: Could not load the summary for directive CdkTrapFocus`

**Comment by Tyler-V** [comment]
This is still an issue in 6.0.0

`ERROR in : Illegal state: Could not load the summary for directive Dir in C:/Users/Tyler/Documents/GitHub/@ngx-easy/projects/easy-grid/node_modules/@angular/cdk/bidi/typings/index.d.ts.`

```
Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.0 (cli-only)
@angular-devkit/build-angular      0.6.0
@angular-devkit/build-ng-packagr   0.6.0
@angular-devkit/build-optimizer    0.6.0
@angular-devkit/core               0.6.0 (cli-only)
@angular-devkit/schematics         0.6.0 (cli-only)
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.0
@schematics/angular                0.6.0 (cli-only)
@schematics/update                 0.6.0 (cli-only)
ng-packagr                         2.4.2
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.6.0
```

**Comment by Tyler-V** [comment]
https://github.com/angular/angular-cli/issues/10615

**Comment by jelbourn** [comment]
Closing this since I believe it is obsolete
