### ISSUE TITLE
Property '_elementRef' is private and only accessible within class 'MatDialogContainer'

### ISSUE THREAD

**Issue by pranavneeraj** [angular/material2#11146]
#### What is the expected behavior?

Should not throw the error when trying to access __elementRef of dialogeRef.
#### What is the current behavior?
Can't access innerHTML of dialogue.
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Need to access innerHTML of dialogeRef.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5

**Comment by pranavneeraj** [comment]
Can anyone look into this?

**Comment by jelbourn** [comment]
The dialog doesn't offer an API to get the DOM element directly.

Note that any members prefixed with an underscore are private APIs

**Comment by simeyla** [comment]
Accessing `innerHTML` sounds like a terrible idea, but I myself did have a legitimate need to access the dialog container so I did some detective work.

My dialog needs to responsively change size when the screen changes, and I wanted to enable/disable an attribute on the dialog container - AFTER it had been created. The `panelClass` and `backdropClass` are just set once so these wouldn't be enough.

I found I can inject the container:

        public container: MatDialogContainer,

Then I just cast `this.container` to `<any>` which allows accessing the private `_elementRef`.

            data.mainMenuService.fullscreenMenuDialog.subscribe((fullscreen: boolean) => {

                this.renderer.setAttribute((<any>this.container)._elementRef.nativeElement, 'fullscreen', fullscreen.toString());
            });

Then I thought for a minute - hmm if I post this then @jelbourn is going to get mad at me! So I delved a little further and found that `OverlayContainer` contains a public interface to `getContainerElement()` :-)

So I just inject `overlay: OverlayContainer` and then I can set a class or attribute on it. Bear in mind that this is the container element to ALL overlays, but in my case this was ok.

If you really really needed to access InnerHTML you could do it via this same mechanism, but you'd be better off asking on Stackoverflow what you're actually trying to achieve before persuing this further.

There is also a class [`OverlayRef`](https://material.angular.io/cdk/overlay/api#OverlayRef) which gives access to `backdropElement`, `hostElement` and `overlayElement`. Unfortunately I couldn't find a way to access this for a MatDialog.
