### ISSUE TITLE
error TS2339: Property 'extraClasses' does not exist on type 'MatSnackBarConfig<any>'

### ISSUE THREAD

**Issue by kevincaradant** [angular/material2#11157]
#### Bug, feature request, or proposal:
Bug ? I guess

#### What is the expected behavior?
No error by Angular-CLI (TS).
it's seems the attribute 'extraClasses' is not available or does not exist anymore ? 

#### What is the current behavior?
 error TS2339: Property 'extraClasses' does not exist on type 'MatSnackBarConfig<any>'

#### What are the steps to reproduce?
Try to add extraclasses attribute to 'MatSnackBarConfig<any>' object

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0
Material 6.0
Flex 6.0.0-beta.15
OS: Windows 7 64 bits
TS: 2.7.2
Browser: Chrome
Package-Manager: Yarn 1.6
Node: 8.9.0
Ng-Update: YES

**Comment by josephperrott** [comment]
As of `6.0.0` `extraClasses` was renamed to `panelClass` as noted in the [`6.0.0-beta.5` list of breaking changes](https://github.com/josephperrott/material2/blob/v6/CHANGELOG.md#600-beta5-2018-03-23):
> **snack-bar**: `extraClasses` which was deprecated in 5.0.0 has been removed. Use `panelClass` instead.

**Comment by kevincaradant** [comment]
Oh sorry my bad, anyway thank you
