### ISSUE TITLE
Unable to use displayWith input on mat-slider

### ISSUE THREAD

**Issue by mlrv** [angular/material2#11155]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I should be able to format the appearance of the thump label of a slider by using the `displayWith` property of `mat-slider` (as documented [here](https://material.angular.io/components/slider/overview#formatting-the-thumb-label)).

#### What is the current behavior?
Angualr throws an error saying that `displayWith` is not a known property of the element

> Can't bind to 'displayWith' since it isn't a known property of 'mat-slider'. [...]

I'm correctly importing the `MatSliderModule` in the module where I'm using the `mat-slider` component.

#### What are the steps to reproduce?
The [stackblitz snippet](https://run.stackblitz.com/api/angular/v1?file=app%2Fslider-formatting-example.ts) provided in the official documentation seems to be working fine, but several other people have reported the same problem (see [here](https://github.com/angular/material.angular.io/issues/414)).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- "@angular/cli": "^1.6.6"
- "@angular/animations": "~5.1.1"
- "@angular/cdk": "~5.1.1"
- "@angular/common": "~5.1.1"
- "@angular/core": "~5.1.1"
- "@angular/material": "~5.1.1"

Tested on Chrome version 66.0.3359.139

**Comment by josephperrott** [comment]
Closing as `displayWith` is not a property of `MatSlider` before v `6.0.0`
