### ISSUE TITLE
`ng add @angular/material`

### ISSUE THREAD

**Issue by filipesilva** [angular/material2#11159]
Moved from https://github.com/angular/angular-cli/issues/10627

---

### Versions
```
Angular CLI: 6.0.0
Node: 8.9.3
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router
```

### Repro steps

* Step 1: `ng add @angular/material`
* Step 2 It will update multiple files and add `@angular/material` and `@angular/cdk` to `package.json`

### Observed behavior
```
It will install @angular/material but won't install @angular/cdk
```

### Desired behavior
```
It should either install both or none.
```

**Comment by filipesilva** [comment]
@clydin looked into it and it seems like the CDK is being added but the npm install task is not.

**Comment by dtomaszewski** [comment]
another problem with ng add @angular/material is here 
#https://github.com/angular/angular-cli/issues/10640
