### ISSUE TITLE
Badge not showing on mat-icon if using svgIcon

### ISSUE THREAD

**Issue by nazarkryp** [angular/material2#11151]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Badge should be shown

#### What is the current behavior?
Badge is not shown

#### What are the steps to reproduce?
```
export class AppModule {
  constructor(
    private mdIconRegistry: MatIconRegistry,
    private sanitizer: DomSanitizer) {
    mdIconRegistry.addSvgIcon('bell',
      sanitizer.bypassSecurityTrustResourceUrl('./assets/svg/bell.svg'));
  }
}
```
in app.component.html

`<mat-icon matBadge="15" matBadgeColor="primary" svgIcon="bell"></mat-icon>`

you can see code on stackblitz.com, but here it svg icons imports do not word at all
https://stackblitz.com/edit/angular-material2-issue-hjcqj2?embed=1&file=app/app.module.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.0.0

**Comment by tayambamwanza** [comment]
Any work around for this? I had custom badges but would like to use the official ones now

**Comment by Meremos** [comment]
same problem here :(

**Comment by egniteall** [comment]
Same problem badge is not working even if correctly implemented

**Comment by ZouZou** [comment]
I am working with Material 7.0.0 and I have the same problem, has this issue been fixed in later versions?

**Comment by blogcraft** [comment]
Same here :( Angular Material 7.2.0

**Comment by crisbeto** [comment]
Can you post an example of it breaking? This issue was closed because the initial bug was fixed.
