### ISSUE TITLE
md-menu wrong position

### ISSUE THREAD

**Issue by dreday966** [angular/material2#1116]
#### Bug, feature request, or proposal:
md-menu wrong position

#### What is the expected behavior?
md-menu postion on button

#### What is the current behavior?
md-menu showing on the bottom of page

![2016-08-25 14-49-36](https://cloud.githubusercontent.com/assets/9654172/17959792/23c9b1f2-6ad5-11e6-812c-93ece510d29b.png)

**Comment by dreday966** [comment]
when i click the button,the menu appear on bottom...

**Comment by bonaparte89** [comment]
same issue here...

**Comment by jmcgoldrick** [comment]
Hey all, check out the getting_started file, you'll be missing this, specifically this:

> For alpha.7, you need to include the overlay styles in your app via a link element. This will look something like:

`<link href="vendor/@angular2-material/core/overlay/overlay.css" rel="stylesheet">`

> In future releases, all of the core styles will be combined into a single distributed css file.

**Comment by theunreal** [comment]
Same problem. @jmcgoldrick, it has nothing to do with this css file. 

Reported already at https://github.com/angular/material2/issues/1085

**Comment by jelbourn** [comment]
Closing this into #1139

@theunreal if you can reproduce this in a setup that has the core styles loaded can you file a separate issue for this? AFAIK, this issue has been caused by missing the core styles.

**Comment by theunreal** [comment]
Hey @jelbourn, There is already a plunker for this in https://github.com/angular/material2/issues/1085#issuecomment-242399239. This is not about the core styles.

https://plnkr.co/edit/yuPzIJ?p=preview

The core styles are imported but the tooltip appears in a wrong position. same for menus.

**Comment by jelbourn** [comment]
@theunreal the missing styles is still the issue; the problem is that the overlay styles weren't included in `core.css` (which was wrong), so you also need `overlay.css` until it's fixed:
https://plnkr.co/edit/fXznny6aMl5cvajDDuOM?p=preview

**Comment by theunreal** [comment]
@jelbourn Well the plunker wasn't RTL as my issue
https://plnkr.co/edit/5dJE21K2rqMHQupaAm3C?p=preview

In RTL the positioning is all wrong, with or without the styles. I can't even see the tooltip/menu

**Comment by dreday966** [comment]
add css resolve the issue👌
