### ISSUE TITLE
Styling not applied

### ISSUE THREAD

**Issue by wolframm** [angular/material2#11173]
I set up a new project using

`ng new app`

`ng add @angular/material`

I included the following line in `styles.css`:

`@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';`

When I now place a  `<p>` element anywhere inside my app body, it comes out in Times New Roman, when it should be in Roboto. It seems the schematic fails to apply the actual material theme fonts to the app.

Could you please improve the @angular/material schematic so that it styles the entire app, as that would be the entire point of using such a schematic in the first place?

Also please advise what I need to do to apply scheme fonts to the entire app, not just material components.

Version: Angular 6.0.0

**Comment by BenjaminHofstetter** [comment]
From the docs: „By default, Angular Material doesn't apply any global CSS. To apply the library's typographic styles more broadly, you can take advantage of the mat-typography CSS class. This class will style all descendant native elements.“

**Comment by jelbourn** [comment]
See https://material.angular.io/guide/typography
