### ISSUE TITLE
Tooltip remains after parent element get removed

### ISSUE THREAD

**Issue by andreasonny83** [angular/material2#1117]
#### Bug, feature request, or proposal:
<br />This plunkr example http://plnkr.co/edit/WjzlmBYs7Yf2IgAXbERf?p=preview show how removing the parent buttons containing the md-tooltip directive doesn't remove the generated tooltip element from the view.
<br />
<br />#### What is the expected behavior?
<br />As the button get removed from the view, the related md-tooltip element should be removed as well
<br />
<br />#### What is the current behavior?
<br />The tooltip remain visible on the screen
<br />
<br />#### What are the steps to reproduce?
<br />1. using an ngFor for dynamically generates buttons containing a tooltip
<br />2. as the array of elements, linked to the ngFor, changes, the already displayed tooltip elements persist in the view.
<br />
<br />Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
<br />Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
<br />
<br />http://plnkr.co/edit/WjzlmBYs7Yf2IgAXbERf?p=preview
<br />
<br />#### What is the use-case or motivation for changing an existing behavior?
<br />
<br />
<br />#### Which versions of Angular, Material, OS, browsers are affected?
<br />
<br />
<br />#### Is there anything else we should know?
<br />

**Comment by ivoviz** [comment]
Already opened an issue about it (#1111).
