### ISSUE TITLE
Error HammerManager

### ISSUE THREAD

**Issue by maik10** [angular/material2#1118]
I have this error 
node_modules/@angular2-material/core/gestures/MdGestureConfig.d.ts(4,40): error TS2304: Cannot find name 'HammerManager'.

My version of core is 2.0.0-alpha.7-4

**Comment by maxime1992** [comment]
I'm also facing this error, could explain your fix ? Thanks

**Comment by JanStureNielsen** [comment]
@maxime1992 -- see http://stackoverflow.com/questions/39496267/module-not-found-error-cant-resolve-hammerjs/39496268#39496268.
