### ISSUE TITLE
Can't bind to 'checked' since it isn't a known property of 'md-checkbox'

### ISSUE THREAD

**Issue by ciesielskico** [angular/material2#1119]
Angular 2.0.0-rc.5
Angular Material 2.0.0-alpha.7-4
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.1
os: linux x64 

Occurs only when building for **production** with `ng serve -prod` 
Just `ng serve` works fine.

This line is highlighted in the error message:

```
<td class="text-center">
    <md-checkbox 
        [checked]="account.enabled" 
        [title]="account.enabled ? 'Active' : 'Inactive'" 
        (change)="toggleAccountEnabled(account)">
    </md-checkbox>
</td>
```

**Comment by ptsydzik** [comment]
workaround: set mangle property to false in webpack config;

**Comment by ciesielskico** [comment]
Thanks, applying these changes fixes it for me. 
https://github.com/angular/angular-cli/commit/9188ea2bf2b3bbbba2b3640d9c08916f29d8d3f2

**Comment by SoufianeFZ** [comment]
hi guys, i'm currently facing the same issue, @ptsydzik  said that we should edit the webpack config, how can achieve such thing in angular 2 project.
