### ISSUE TITLE
angular material issue.. with the versions...

### ISSUE THREAD

**Issue by royranadeep** [angular/material2#11196]
![image](https://user-images.githubusercontent.com/39003877/39685831-c1d146e4-51e2-11e8-98a4-b41e4955b253.png)

#### What is the expected behavior?
controls must be loaded properly.

#### What is the current behavior?
none of the controls are getting loaded.Getting an empty page.

all the libraries have been installed ...@angular/cdk @angular/material @angular/animations hammerjs

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by Chan4077** [comment]
What's your Angular version? Not just dependencies

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
