### ISSUE TITLE
bug(mat-menu): wrong position for right-to-left applications

### ISSUE THREAD

**Issue by m98** [angular/material2#11201]
#### Bug, feature request, or proposal:
mat-menu opens in a wrong direction when in (complicated) right-to-left mode applications.

#### What is the expected behavior?
Menu opens in correct direction.

#### What is the current behavior?
There are complicated right-to-left web applications that the menu opens in a wrong position, and I could reproduce the problem, and I found out that `cdk-overlay-connected-position-bounding-box` needs to have `direction:ltr`  CSS style. Here is the [demo](https://stackblitz.com/edit/angular-9hxdhn)

#### What are the steps to reproduce?
I got this problem when I updated Angular 5 to 6.
The problem happens when parent HTML container has the `dir="rtl"` attribute, and the `style.css` (the public style) has the `* { direction: rtl}`. 
Here is the [demo](https://stackblitz.com/edit/angular-9hxdhn)

#### What is the use-case or motivation for changing an existing behavior?
Better support for right-to-left application

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 6.0.0
Node: 8.9.3
OS: linux x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

**Comment by crisbeto** [comment]
Material and the CDK don't handle the `direction` being set through CSS, because it's very expensive to determine which direction is set. We only look at the `dir` attributes.

**Comment by m98** [comment]
so, does it mean we just need to use `dir` attribute if we have right-to-left applications?

**Comment by crisbeto** [comment]
Yes, whenever you're using Material or the CDK, you should only use the `dir` attribute. It doesn't necessarily have to be on the `html` or `body` tags, you can put it on any element. I understand that some frameworks may be setting the property, but I don't feel that setting the `dir` to `ltr` on the bounding box is the way to go and it's relatively easy to reset it on your side by setting `direction: unset`. Closing the issue since it works as expected, but we can keep the discussion going.
