### ISSUE TITLE
Conflict with Materialize

### ISSUE THREAD

**Issue by supertino7** [angular/material2#1120]
Hi guyz,

I currently work on an Angular2 project, for which I need some material styles but also components. I want to use directives when I can, but also write raw HTML when needed. 

When I first installed the material2 packages, I couldn't find the base css anywhere, even in the core package. So I thought I had to include it manually.

I included materializeCSS

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">`

But it seems that styles are broken this way, example MdInput 

![screenshot](http://i.imgur.com/L85DCak.png[/img)

The underline appears twice. When I remove materializeCSS, it appears ok.
Am I doing something wrong ? what should I do to use material2 components but also have accesss to grid, helpers classes, etc...
thx a lot

**Comment by m0t0r** [comment]
@supertino7 material2 and materialize are two different projects. You should not mix them together. Check [getting started](https://github.com/angular/material2/blob/master/GETTING_STARTED.md) o how to use material2.

**Comment by jelbourn** [comment]
What @m0t0r said

**Comment by supertino7** [comment]
Hi guyz,

Yes, I know that Material2 and Materialize are two different projects. 
Can you just tell me if Material2 provides a CSS file with all the base styles of the Material Design (grid, tables, etc...), just like Materialize or Bootstrap do ? Or only Materialize provides that ...
thx
