### ISSUE TITLE
Enter on mdInput triggers MouseEvent on associated form elements

### ISSUE THREAD

**Issue by fergusg** [angular/material2#11203]
#### Bug:

In the attached StackBlitz, pressing `Enter` in the input element triggers a `MouseEvent` on the associated button.

#### What is the expected behaviour?

Enter should not trigger events on associated elements. 

Workaround is to test for `MouseEvent.pageX` (say)

#### What is the current behaviour?

(see above)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-mkavs6-fzxrhj

#### Which versions of Angular, Material?
NG 6.0.0

**Comment by crisbeto** [comment]
This is the default way that native inputs behave. I don't think it's something Material should be messing with.

**Comment by fergusg** [comment]
OK `KeyboardEvent` triggering `MouseEvent` is not what I'd have expected.
