### ISSUE TITLE
Material dashboard schematics has broken styling of cards

### ISSUE THREAD

**Issue by Chan4077** [angular/material2#11200]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The cards of the material dashboard schematic should fill up the grid tiles.
![Expected behavior](https://user-images.githubusercontent.com/20047125/39698299-e5a0d370-5226-11e8-807b-bb1bde62a8fe.jpg)

#### What is the current behavior?
The cards of the material dashboard schematic do not fill up the grid tiles.
![Current behavior](https://user-images.githubusercontent.com/20047125/39698301-e866a44a-5226-11e8-8c9d-cdd38eebb11e.jpg)

#### What are the steps to reproduce?
1. Create a project.
2. Add Angular Material.
3. Run the command to generate an Angular Material dashboard:
   ```bash
   ng g @angular/material:material-dashboard my-dashboard
   ```
4. See the results.

#### What is the use-case or motivation for changing an existing behavior?
NIL

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Angular v6
- Angular Material v6
- All operating systems
- TypeScript `2.7.2`
- All browsers

#### Is there anything else we should know?
Seems that setting the card's `position` to be `!important` has fixed it due to the extra specification. The styles of `.mat-card` (`position: relative`) seem to override the `.dashboard-card` class (`position: absolute`), therefore making the card not span the grid tile's height and width.

**Comment by amcdnl** [comment]
I can not reproduce this - https://www.screencast.com/t/3i1CTh4pc

Is there anything special you did? Perhaps you can create a github repo example?

**Comment by josephperrott** [comment]
Closing as no reproduction has been provided.
