### ISSUE TITLE
mat-table: There can only be one default row without a when predicate function.

### ISSUE THREAD

**Issue by ewaschenko** [angular/material2#11208]
#### Bug, feature request, or proposal:
Bug: Following the `expandable-rows` example in the demo-app, the example fails in Stackblitz since the 
```
<tr mat-row *matRowDef="let row; columns: ['expandedDetail']"
        class="demo-detail-row"></tr>
```

[https://github.com/angular/material2/blob/master/src/demo-app/table/expandable-rows/expandable-rows.html#L23](https://github.com/angular/material2/blob/master/src/demo-app/table/expandable-rows/expandable-rows.html#L23)

is missing the `when` predicate.  However, when building and deploying the demo app locally, it works fine.

#### What is the expected behavior?
The table should behave the same as the `expandable-rows` component in the demo-app when deployed locally.

#### What is the current behavior?
The following error is produced:

ERROR
Error: There can only be one default row without a when predicate function.

#### What are the steps to reproduce?

[https://stackblitz.com/edit/expandable-rows-exp](https://stackblitz.com/edit/expandable-rows-exp)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.0.1
Angular 6.0.0

**Comment by pfeigl** [comment]
See this PR https://github.com/angular/material2/pull/11116

This added multiTemplateDataRows which actually allows to have multiple rows without when predicate, which the demo app already uses.

This is not yet included in 6.0.1.
