### ISSUE TITLE
Drop down shows some different behavior.

### ISSUE THREAD

**Issue by Muzammil-Bilwani** [angular/material2#11216]
#### Bug, feature request, or proposal:
It is observed that drop down shows some different behavior randomly.

Attaching image link 
![screenshot_3](https://user-images.githubusercontent.com/10519790/39740953-418ed062-52b1-11e8-8888-7a86dd85b0fe.png)

#### Is there anything else we should know?
The same bug is in autocomplete.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. In particular, steps to reproduce, version, number, etc.

(this is a canned response)
