### ISSUE TITLE
Center tiles in grid list

### ISSUE THREAD

**Issue by michaelb-01** [angular/material2#11217]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
An input to set how the tiles are justified within the list (left, center, right)

#### What is the current behavior?
They are left aligned

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.0
Node: 9.5.0
OS: darwin x64
Angular: 6.0.0

**Comment by jelbourn** [comment]
You should be able to use css to set whatever alignment / justification within the tiles you'd need.

**Comment by michaelb-01** [comment]
I don’t mean centering the content within the tiles, I mean centering the tiles themselves, as in centering the list. If you have a grid list with 4 columns but only three tiles you will see they are left aligned and I couldn’t figure out how to center them..

**Comment by jelbourn** [comment]
Ah, that's a feature the grid-list can't support due to it also supporting colspan/rowspan; if tiles were centered, there wouldn't be a consistent grid
