### ISSUE TITLE
mat-select change

### ISSUE THREAD

**Issue by lacu** [angular/material2#11212]
#### Bug, feature request, or proposal:
How I can replace the removed "change()" method in version 6 of mat-select. 
I will have to change all the events in my proyect. 

#### What is the expected behavior?
Run code in my component on user selection

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.0.0

**Comment by crisbeto** [comment]
You can replace `change` with `selectionChange` which does the same.
