### ISSUE TITLE
MatSideNav autosize runs into ngZone 100% CPU

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#11215]
#### Bug, feature request, or proposal:
Bug: regression
MatSideNav autosize runs into ngZone

#### What is the expected behavior?
autosize code should run outside ngZone

#### What is the current behavior?
autosize code runs inside ngZone

#### What are the steps to reproduce?
```
<mat-sidenav-container autosize>
  <mat-sidenav [opened]="isSidenavOpened" [mode]="'side'"></mat-sidenav>
</mat-sidenav-container>
```
https://stackblitz.com/edit/angular-material2-issue-fn9sts?file=app/app.component.html

#### What is the use-case or motivation for changing an existing behavior?
It pushes CPUs to their limit, 100% constant usage.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.0
Node: 8.9.4
OS: win32 x64
Angular: 6.0.0
Material: 6.0.1

#### Is there anything else we should know?
Does not happen unless this code is present
` [opened]="isSidenavOpened" [mode]="'side'"`

**Comment by Ploppy3** [comment]
@crisbeto please reopen. It's back, same exact problem. It hits ngZone continuously again.

**Comment by Ploppy3** [comment]
@jelbourn @crisbeto Should I open a new one?

**Comment by crisbeto** [comment]
I don't think much has changed in the sidenav since the fix got in. I'll take a look later today.

**Comment by Ploppy3** [comment]
@crisbeto I see the fix is already implemented, when will the next version be available?

**Comment by crisbeto** [comment]
I can't say since it depends on when the caretaker gets to merging the PR. The issue got introduced in 6.3.2 so you should be able to stick with 6.3.1 until the fix gets in.
