### ISSUE TITLE
mat-datepicker

### ISSUE THREAD

**Issue by drop039beats** [angular/material2#11219]
#### Bug, feature request, or proposal:
feature 

#### What is the expected behavior?
I want to handle each and every event i.e. clicking on the datepicker's month selection and selecting a month should triggering an event like (change) or (click) 

#### What is the current behavior?
Event that gets fired is after i select the day and i have a whole project running on ng --version @1.7.4 so i cannot upgrade it to @6.0.0 because for this version we can use (yearSelected) or (monthSelected) output bindings

#### What are the steps to reproduce?
Normal date picker with startView="year"

<mat-form-field>
                <input matInput [matDatepicker]="picker" [placeholder]="filter.placeholder" [(ngModel)]="filter.value" readonly>
                <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
                <mat-datepicker #picker startView="year">
                </mat-datepicker>
              </mat-form-field>

#### What is the use-case or motivation for changing an existing behavior?
I wanted a month and year only date-picker [NOTE: Cannot upgrade ng to latest version 6.0.0, using 1.7.4]

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5
CLI = 1.7.4
Material = 5.2.4
OS = Linux, UBUNTU 16.04
TypeScript = 2.8.1

#### Is there anything else we should know?
Cannot upgrade to angular 6.0.0 because my whole project has been setup in angular 5 CLI version = 1.7.4

**Comment by drop039beats** [comment]
Yeah i checked and Angular version: 5.2.9

**Comment by CDDelta** [comment]
Angular and all its official packages follow semvar so new features are only added to major releases. I doubt they will backpatch this feature for you so your best bet is to upgrade your cli version.

**Comment by Chan4077** [comment]
Can't you use `ng update @angular/cli`? This should create a new Angular CLI config file with all of your config options.

**Comment by jelbourn** [comment]
New features are only added in new minors / majors and aren't backported unless there's a major browser change or security fix necessary. 

Updating from 5 to 6 shouldn't be huge undertaking, check out https://update.angular.io/
