### ISSUE TITLE
Stackblitz examples are broken

### ISSUE THREAD

**Issue by CurtisDS** [angular/material2#11223]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The stackblitz examples to work

#### What is the current behavior?

> Error in 5.2.10/bundles/compiler.umd.js (529:34)
> Unexpected value 'undefined' exported by the module 'DemoMaterialModule'
> Evaluating main.ts
> Booting application

#### What are the steps to reproduce?
Go to any material example from the material.angular.io page. Here is [one](https://stackblitz.com/angular/qlrvpxqaorp?file=main.ts).

#### Is there anything else we should know?
It looks like it is trying to import modules from Material 6 but the dependencies are all set up for Material 5.2.4

**Comment by mzavaletavargas** [comment]
Please fix them :(

**Comment by CurtisDS** [comment]
@mzavaletavargas if you go into main.ts and remove `MatBadgeModule`, `MatBottomSheetModule`, and `MatTreeModule` from the import statement, and the `gModule` `exports` array it will start working again.

Or you can delete all the dependencies and re apply them.

If you need to get it working in the mean time.

**Comment by mzavaletavargas** [comment]
Thanks @CurtisDS  I made that change, but seems that is not working anyways at least for the table examples. 

I got a different error.

```Error in /turbo_modules/@angular/compiler@5.2.10/bundles/compiler.umd.js (529:34)
Template parse errors:
Can't bind to 'dataSource' since it isn't a known property of 'table'. ("<div class="example-container mat-elevation-z8">
<table mat-table #table [ERROR ->][dataSource]="dataSource">

<!-- Position Column -->
"): ng:///AppModule/TablePaginationExample.html@1:26
Evaluating main.ts
Booting application```

**Comment by CurtisDS** [comment]
@mzavaletavargas it looks like they have gone trough and updated all the dependencies to material 6.0.0.... so you should be able to go to the site and get the examples working.... but tables look messed up in material 6. :( ... that might be a separate bug.

**Comment by CurtisDS** [comment]
actually, simple fix. Just applied a width: 100% to the table. https://stackblitz.com/edit/angular-yxmpss?file=app/table-pagination-example.css

**Comment by jelbourn** [comment]
As far as I can tell, this is working fine and set up correctly. I suspect it's a client caching issue. Try clearing your browser cache?

**Comment by jelbourn** [comment]
Since it was time-based, I suspect it was caching on the part of our hosting provider that took some time to update. I believe there's already a PR out to fix the table examples.
