### ISSUE TITLE
Error: StaticInjectorError(AppModule)[MatDrawerContainer -> InjectionToken MAT_DRAWER_DEFAULT_AUTOSIZE]:

### ISSUE THREAD

**Issue by cyphercodes96** [angular/material2#11224]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Project running normally

#### What is the current behavior?
SidebarComponent.html:1 ERROR Error: StaticInjectorError(AppModule)[MatDrawerContainer -> InjectionToken MAT_DRAWER_DEFAULT_AUTOSIZE]: 
  StaticInjectorError(Platform: core)[MatDrawerContainer -> InjectionToken MAT_DRAWER_DEFAULT_AUTOSIZE]: 
    NullInjectorError: No provider for InjectionToken MAT_DRAWER_DEFAULT_AUTOSIZE!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:979)
    at resolveToken (core.js:1232)
    at tryResolveToken (core.js:1182)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1077)
    at resolveToken (core.js:1232)
    at tryResolveToken (core.js:1182)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1077)
    at resolveNgModuleDep (core.js:9238)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:9919)
    at resolveDep (core.js:10284)
View_SidebarComponent_0 @ SidebarComponent.html:1
proxyClass @ compiler.js:10061
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:12174
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:1650
(anonymous) @ core.js:4886
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:4030
(anonymous) @ core.js:4886
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4071
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4062
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:4800
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:81
0 @ main.ts:12
__webpack_require__ @ bootstrap:81
checkDeferredModules @ bootstrap:43
webpackJsonpCallback @ bootstrap:30
(anonymous) @ main.js:1
SidebarComponent.html:1 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 2, nodeDef: {…}, elDef: {…}, elView: {…}}
View_SidebarComponent_0 @ SidebarComponent.html:1
proxyClass @ compiler.js:10061
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:12174
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:1655
(anonymous) @ core.js:4886
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:4030
(anonymous) @ core.js:4886
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4071
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4062
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:4800
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:81
0 @ main.ts:12
__webpack_require__ @ bootstrap:81
checkDeferredModules @ bootstrap:43
webpackJsonpCallback @ bootstrap:30
(anonymous) @ main.js:1
main.ts:12 Error: StaticInjectorError(AppModule)[MatDrawerContainer -> InjectionToken MAT_DRAWER_DEFAULT_AUTOSIZE]: 
  StaticInjectorError(Platform: core)[MatDrawerContainer -> InjectionToken MAT_DRAWER_DEFAULT_AUTOSIZE]: 
    NullInjectorError: No provider for InjectionToken MAT_DRAWER_DEFAULT_AUTOSIZE!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:979)
    at resolveToken (core.js:1232)
    at tryResolveToken (core.js:1182)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1077)
    at resolveToken (core.js:1232)
    at tryResolveToken (core.js:1182)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1077)
    at resolveNgModuleDep (core.js:9238)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:9919)
    at resolveDep (core.js:10284)
client?719c:147 [WDS] Warnings while compiling.
warnings @ client?719c:147
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1188
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
client?719c:153 ./node_modules/@angular/material/esm5/progress-bar.es5.js
143:83-104 "export 'ANIMATION_MODULE_TYPE' was not found in '@angular/platform-browser/animations'
warnings @ client?719c:153
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1188
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
client?719c:153 ./node_modules/@angular/material/esm5/progress-spinner.es5.js
264:83-104 "export 'ANIMATION_MODULE_TYPE' was not found in '@angular/platform-browser/animations'
warnings @ client?719c:153
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1188
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
client?719c:153 ./node_modules/@angular/material/esm5/progress-spinner.es5.js
309:83-104 "export 'ANIMATION_MODULE_TYPE' was not found in '@angular/platform-browser/animations'

#### What are the steps to reproduce?
Upgrading to angular 6 while using mat-drawer-container

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Using Chrome

cyphercodes@Cypher:~/WebstormProjects/ccdesk-ng$ ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.0
Node: 10.0.0
OS: linux x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.6.0
@angular-devkit/build-angular       0.6.0
@angular-devkit/build-optimizer     0.6.0
@angular-devkit/core                0.6.0
@angular-devkit/schematics          0.6.0
@angular/cdk                        6.0.1-4bf3ceb
@angular/flex-layout                5.0.0-beta.14
@angular/forms                      5.2.10
@angular/http                       5.2.10
@angular/language-service           5.2.10
@angular/material                   6.0.1-4bf3ceb
@angular/platform-browser           5.2.10
@angular/platform-browser-dynamic   5.2.10
@angular/router                     5.2.10
@ngtools/webpack                    6.0.0
@schematics/angular                 0.6.0
@schematics/update                  0.6.0
rxjs                                6.1.0
typescript                          2.7.2
webpack                             4.6.0

#### Is there anything else we should know?
my sidebar component
<mat-drawer-container id="normalSide" #drawer fxLayout="row" fxFlex="1 1 auto"
                       color="primary">
  <mat-drawer #drawer mode="side" fxLayout="column"
              opened="true" fxFlex="auto"></mat-drawer>
  <mat-drawer-content fxLayout="column" fxFlex="auto">

    <a class="profileIcon" mat-list-item *ngIf="auth.isLoggedIn()"
       routerLink="/userProfile">
      <img *ngIf="this.auth.profilePictureURL"
           class="rounded-circle"
           src={{this.auth.profilePictureURL}}
           style="width: 25px;height: 25px">
      <img *ngIf="!this.auth.profilePictureURL"
           class="rounded-circle"
           src="../../assets/default-user.png"
           style="width: 25px;height: 25px">
      
    </a><br>

    <h1>Cloud Clinic</h1>
    <mat-nav-list fxLayout="column" color="accent">
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/"
         (click)="onAppointmentNotClicked()"><i class="fa fa-home"></i>
        <span fxFlex>Home</span></a>

      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/appointments"
         (click)="onAppointmentClicked()"><i
        class="fa fa-calendar"
      ></i><span>Appointments</span></a>

      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/patients"
         (click)="onAppointmentNotClicked()"><i
        class="fa fa-users"></i><span>Patients</span></a>
      <a mat-list-item class="nav-link"
         *ngIf="isPatientRouteActive()"
         routerLink="/patient/{{this.patientId}}/med"><i class="fa fa-user-md"></i>
        <span>Medical Info</span></a>
      <a mat-list-item class="nav-link"
         *ngIf="isPatientRouteActive()"
         routerLink="/patient/{{this.patientId}}/chart"><i class="fa fa-area-chart"></i>
        <span>Dental Charts</span></a>
      <a mat-list-item class="nav-link"
         role="button"
         *ngIf="isPatientRouteActive()"
         routerLink="/patient/{{this.patientId}}/plan"><i
        class="fa fa-columns"></i><span>Treatment Plans</span></a>
      <a mat-list-item class="nav-link"
         role="button"
         *ngIf="isPatientRouteActive()"
         routerLink="/patient/{{this.patientId}}/xray"><i
        class="fa fa-file"></i><span>Xrays</span></a>
      <a mat-list-item class="nav-link"
         role="button"
         *ngIf="isPatientRouteActive()"
         routerLink="/patient/{{this.patientId}}/image"><i class="fa fa-picture-o"></i>
        <span>Images</span></a>

      <a mat-list-item *ngIf="!auth.isLoggedIn()"
         routerLink="/login"><i class="fa fa-sign-in"></i>
        <span>Login</span></a>
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/accounting"
         (click)="onAppointmentNotClicked()">
        <i
          class="fa fa-credit-card"></i><span>Accounting</span></a>
      

      
      <a mat-list-item *ngIf="auth.isPrivilaged()"
         routerLink="/treatmentService"
         (click)="onAppointmentNotClicked()">
        <i class="fa fa-medkit" aria-hidden="true"></i><span>Treatment Service</span></a>
      <a mat-list-item *ngIf="auth.isPrivilaged()"
         routerLink="/userManagement"
         (click)="onAppointmentNotClicked()">
        <i
          class="fa fa-user-plus"></i><span>User Management</span></a>
      <a mat-list-item *ngIf="auth.isPrivilaged()"
         routerLink="/locationManagement"
         (click)="onAppointmentNotClicked()">
        <i
          class="fa fa-map-marker"></i><span>Location Management</span></a>
      
      
      
      
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         (click)="auth.logout()"
         routerLink="/login"><i
        class="fa fa-sign-out"></i><span>Logout</span></a>
    </mat-nav-list>
  </mat-drawer-content>

</mat-drawer-container>

<mat-drawer-container id="mobileSide" autosize>
  <mat-drawer #drawer mode="side">

    <h1 id="titleN">
      <a class="profileIcon" mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/userProfile">
        <img *ngIf="this.auth.profilePictureURL"
             class="rounded-circle"
             src={{this.auth.profilePictureURL}}
             style="width: 25px;height: 25px">
        <img *ngIf="!this.auth.profilePictureURL"
             class="rounded-circle"
             src="../../assets/default-user.png"
             style="width: 25px;height: 25px">
        </a><br><br>Cloud Clinic</h1>
    <mat-nav-list fxLayout="column" color="accent">
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/"><i class="fa fa-home"></i>
        <span fxFlex>Home</span></a>
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/appointments"><i
        class="fa fa-calendar"></i><span>Appointments</span></a>
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/patients"><i
        class="fa fa-users"></i><span>Patients</span></a>
      <a mat-list-item *ngIf="!auth.isLoggedIn()"
         routerLink="/login"><i class="fa fa-sign-in"></i>
        <span>Login</span></a>
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/accounting">
        <i
          class="fa fa-credit-card"></i><span>Accounting</span></a>
      <a mat-list-item *ngIf="!auth.isLoggedIn()"
         routerLink="/register"><i
        class="fa fa-user-plus"></i><span>Register</span></a>
      <a mat-list-item *ngIf="auth.isPrivilaged()"
         routerLink="/userManagement"
         (click)="onAppointmentNotClicked()">
        <i
          class="fa fa-user-plus"></i><span>User Management</span></a>
      <a mat-list-item *ngIf="auth.isPrivilaged()"
         routerLink="/locationManagement"
         (click)="onAppointmentNotClicked()">
        <i
          class="fa fa-map-marker"></i><span>Location Management</span></a>
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         (click)="auth.logout()"
         routerLink="/login"><i
        class="fa fa-sign-out"></i><span>Logout</span></a>
    </mat-nav-list>
  </mat-drawer>

  <mat-drawer-content>
    <button mat-icon-button (click)="drawer.toggle(); pressMenu()" id="hamToggle">
      <mat-icon aria-hidden="true">menu</mat-icon>
    </button>

    <h1 *ngIf="this.pressedMenu == false">
      <a class="profileIcon profileIcon-mobile" mat-list-item
         *ngIf="auth.isLoggedIn() && this.pressedMenu == false"
         routerLink="/userProfile">
        <img *ngIf="this.auth.profilePictureURL"
             class="rounded-circle"
             src={{this.auth.profilePictureURL}}
             style="width: 25px;height: 25px">
        <img *ngIf="!this.auth.profilePictureURL"
             class="rounded-circle"
             src="../../assets/default-user.png"
             style="width: 25px;height: 25px">
        </a><br><br>CC</h1>
    <mat-nav-list id="mobileMenu" *ngIf="this.pressedMenu == false" fxLayout="column" color="accent">
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/"><i class="fa fa-home"></i>
      </a>
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/appointments"><i
        class="fa fa-calendar"></i></a>
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/patients"><i
        class="fa fa-users"></i></a>

      <a mat-list-item class="nav-link"
         *ngIf="isPatientRouteActive()"
         routerLink="/patient/{{this.patientId}}/med">&#9679; &#160;<i class="fa fa-user-md"></i></a>
      <a mat-list-item class="nav-link"
         *ngIf="isPatientRouteActive()"
         routerLink="/patient/{{this.patientId}}/chart">&#9679; &#160;<i class="fa fa-area-chart"></i></a>
      <a mat-list-item class="nav-link"
         role="button"
         *ngIf="isPatientRouteActive()"
         routerLink="/patient/{{this.patientId}}/plan">&#9679; &#160;<i
        class="fa fa-columns"></i></a>
      <a mat-list-item class="nav-link"
         role="button"
         *ngIf="isPatientRouteActive()"
         routerLink="/patient/{{this.patientId}}/xray">&#9679; &#160;<i
        class="fa fa-file"></i></a>
      <a mat-list-item class="nav-link"
         role="button"
         *ngIf="isPatientRouteActive()"
         routerLink="/patient/{{this.patientId}}/image">&#9679; &#160;<i class="fa fa-picture-o"></i></a>

      <a mat-list-item *ngIf="!auth.isLoggedIn()"
         routerLink="/login"><i class="fa fa-sign-in"></i>
      </a>
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         routerLink="/accounting">
        <i
          class="fa fa-credit-card"></i></a>
      <a mat-list-item *ngIf="!auth.isLoggedIn()"
         (click)="logout()"
         routerLink="/register"><i
        class="fa fa-user-plus"></i></a>
      <a mat-list-item *ngIf="auth.isPrivilaged()"
         routerLink="/userManagement"
         (click)="onAppointmentNotClicked()">
        <i
          class="fa fa-user-plus"></i></a>
      <a mat-list-item *ngIf="auth.isPrivilaged()"
         routerLink="/locationManagement"
         (click)="onAppointmentNotClicked()">
        <i
          class="fa fa-map-marker"></i></a>
      <a mat-list-item *ngIf="auth.isLoggedIn()"
         (click)="auth.logout()"
         routerLink="/login"><i
        class="fa fa-sign-out"></i></a>
    </mat-nav-list>
  </mat-drawer-content>

</mat-drawer-container>

**Comment by crisbeto** [comment]
By the looks of it, you're using Material 6.0 with Angular 5.2 which causes it to break. Always make sure that the major versions of Material and Angular are the same.

**Comment by cyphercodes96** [comment]
@crisbeto have you not seen this? this is when running ng -v
cyphercodes@Cypher:~/WebstormProjects/ccdesk-ng$ ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.0
Node: 10.0.0
OS: linux x64
Angular: 6.0.0
 I am using material 6.0 with angular 6 and not 5.2 :/

**Comment by crisbeto** [comment]
The package versions that you posted above show a mix between Angular 5 and 6 packages.

**Comment by cyphercodes96** [comment]
@crisbeto Yeah true because ng update didn't manage to update my dependencies / packages. I had to update them manually using npm install, package by package, so i only did the main packages, core, cdk, material
