### ISSUE TITLE
Generate navigation schematic fails in 6.0.1

### ISSUE THREAD

**Issue by ray-kay** [angular/material2#11221]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
As seen on: https://material.angular.io/guide/schematics the command
`ng generate @angular/material:material-nav`
should run as expected

#### What is the current behavior?

`ng generate @angular/material:material-nav`
_Schematic input does not validate against the Schema: {"dryRun":false,"inlineStyle":false,"inlineTemplate":false,"changeDetection":"Default","styleext":"css","spec":true,"flat":false,"skipImport":false,"export":false}
Errors:
Data path "" should have required property 'name'._

#### What are the steps to reproduce?

- create a new project with angular-cli: 6.0.0
- ng add @angular/material 
- ng add @angular/cdk
- ng generate @angular/material:material-nav

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
npm: 5.8.0
 node: 8.9.4 
angular-cli: 6.0.0
angular: 6.0.0
@angular/cdk                      6.0.1
@angular/material                 6.0.1
typescript  2.7.2

**Comment by nicholas-davis** [comment]
ng generate @angular/material:material-nav --name <component-name>

**Comment by ray-kay** [comment]
Thanks @nicholas-davis totally my bad but maybe worth updating the documentation on https://material.angular.io/guide/schematics

**Comment by AmmarHasan** [comment]
#11283
