### ISSUE TITLE
Is there any way I can add multiline in Snackbar?

### ISSUE THREAD

**Issue by kgrvr** [angular/material2#11239]
#### Bug, feature request, or proposal:
Question / Feature request

#### What is the expected behavior?
String array can be used to display text on Snackbar in multiline

#### What is the current behavior?
Single string is displaying in a single line in Snackbar

#### What is the use-case or motivation for changing an existing behavior?
Multiline text in Snackbar

**Comment by willshowell** [comment]
Snackbars support passing in custom components instead of just strings: https://material.angular.io/components/snack-bar/examples

You can template that component however you wish

**Comment by jelbourn** [comment]
What @willshowell said

**Comment by thw0rted** [comment]
You could also use the stock component, pass a message with newlines, and set a custom `panelClass` option that applies `white-space: pre-wrap` or similar.  I tested this and it works for me.
