### ISSUE TITLE
Can't import overlay.scss

### ISSUE THREAD

**Issue by FabioAntunes** [angular/material2#1123]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Be able to import `@angular2-material/core/overlay/overlay`

#### What is the current behavior?
```
Module build failed: 
@import 'variables';
^
      File to import not found or unreadable: variables
Parent style sheet: /home/fabio/playground/angular2-scaffolding/node_modules/@angular2-material/core/overlay/overlay.scss
      in /home/fabio/playground/angular2-scaffolding/node_modules/@angular2-material/core/overlay/overlay.scss (line 3, column 1)
```

#### What are the steps to reproduce?
Just import overlay into your scss file:
```
@import '~@angular2-material/core/style/core';
@import '~@angular2-material/core/overlay/overlay';
```

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-alpha.7-4

**Comment by RoxKilly** [comment]
I think that core and overlay styles should not be imported into your components, but rather linked to in your `index.html`
```
<link rel="stylesheet" href="path/to/core.css">
<link rel="stylesheet" href="path/to/overlay.css">
```

See: https://github.com/angular/material2/issues/972#issuecomment-240760777

**Comment by FabioAntunes** [comment]
@RoxKilly I'm importing those to my index.scss, not my components and I fact you can import those css files, into your root component if you disable the ViewEncapsulation. The issue here is that the scss file is not valid, it's trying to import the variables file, when there's no file to import

**Comment by spock123** [comment]
@FabioAntunes  don't load the overlay.scss file, load the overlay.css file.....

**Comment by spock123** [comment]
Also, forget about importing the file.

Just include the two css rules in your own styles

**Comment by vapits** [comment]
Same here, Icannot imnport it nowhere, index.html or styleurls. I'm getting 404 even that the file is there

**Comment by jelbourn** [comment]
Obsolete by theming update.
