### ISSUE TITLE
Chips Autocomplete documentation example - remove chip not working

### ISSUE THREAD

**Issue by rafcioka** [angular/material2#11247]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should remove the chip if X clicked next to the chip.

#### What is the current behavior?
Chip is not removed if X cliked next to the chip.

#### What are the steps to reproduce?
Use the Chips Autocomplete example at https://material.angular.io/components/chips/overview

Stackblitz: https://xlyjpepaemb.angular.stackblitz.io

**Comment by jelbourn** [comment]
Should be fixed in #11175
