### ISSUE TITLE
Mat-Expansion-Panel in a Mat-Expansion-Panel closes parent on open.

### ISSUE THREAD

**Issue by javagaba** [angular/material2#11242]
#### Bug, feature request, or proposal:
With Material 6.0.1, I've noticed that when an expansion panel placed inside for another expansion-panel is opened, the parent expansion panel closes immediately. This was not the case with prior versions.

#### What is the expected behavior?
An expansion panel opening inside of another expansion panel should not make the parent panel close.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-i4n6ry

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.0, Material 6.0.1

**Comment by javagaba** [comment]
Please have a look at the code. The issue does not concern accordions, but instead expansion panels placed in the body of another expansion panel.

**Comment by bjines** [comment]
I honestly don't know how to use stackblitz, but I tried to fork it with multi="true" for you in the accordion. Does this not resolve your issue of it closing it's parent?

https://stackblitz.com/edit/angular-material2-issue-hjupgw?file=app/app.component.html

**Comment by javagaba** [comment]
It is true that adding "multi" to the parent makes the inner mat-expansion-panel work, but I'm not sure this is wanted behaviour. Shouldn't the child expansion-panel or child accordion operate by its own set of rules? I don't think the parent accordion should define the child accordion's behaviour.

**Comment by AshotAleqs** [comment]
Hello everyone. You need to put your child expansion panel into mat-accordion like this.
Please past this code into html in your stackblitz example, (sorry I don't know how I can share my changed stackblitz example).

`<mat-toolbar color="primary">
  Angular Material 2 App
</mat-toolbar>
<div class="basic-container">
  <mat-accordion>
    <mat-expansion-panel>
      <mat-expansion-panel-header>Test</mat-expansion-panel-header>
      <p>BODY</p>
      <div>
        <mat-accordion>
          <mat-expansion-panel>
            <mat-expansion-panel-header>Inner expansion panel</mat-expansion-panel-header>
          </mat-expansion-panel>
        </mat-accordion>
     
      </div>
    </mat-expansion-panel>
  </mat-accordion>
</div>`
