### ISSUE TITLE
datePicker custom header interaction

### ISSUE THREAD

**Issue by labyed** [angular/material2#11240]
#### feature request:
Hi Guys, it's will be great if we can communicate between datepickerComponent and the custom calendar header, be able to pass values, and emit events

#### What is the current behavior?
we pass a component as attribute, so we can't use the parent child relation, now im using localstorage to pass data, and if we have multiple calendar in the view they got the same instance of the customHeader

**Comment by mmalerba** [comment]
@labyed can you inject `MatDatepicker` in the header the same way the default header injects `MatCalendar`? https://github.com/angular/material2/blob/master/src/lib/datepicker/calendar.ts#L53

**Comment by labyed** [comment]
sorry for the late response, actually that's what i did, so it's possible

**Comment by mmalerba** [comment]
cool, in that case closing the issue
