### ISSUE TITLE
md-checkbox two-way binding fail

### ISSUE THREAD

**Issue by MAJLGC** [angular/material2#1124]
#### Bug, feature request, or proposal:
md-checkbox two-way binding fail

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by jelbourn** [comment]
@MAJLGC without more information we aren't able to investigate your issue.
