### ISSUE TITLE
Inconsistancy of triggering change event on the very first init across components.

### ISSUE THREAD

**Issue by colinfang** [angular/material2#1125]
For example, in `MdRadioGroup`, it only fires a change event if this isn't the first time the value is ever set. Same applies to `TabGroup`

However in `MdButtonToggleGroup`, it fires a change event even if it is the first time. Same applies to `SlideToggle`

**Comment by jelbourn** [comment]
If a component fires a change event upon initialization it is a bug.

**Comment by DevVersion** [comment]
I just took a look at it for the `md-slide-toggle` - I was not able to recognize any events at initialization.

Is it possible that you use an older version of Material 2?

**Comment by colinfang** [comment]
`change` is emitted before click on the `MdButtonToggle`

http://plnkr.co/edit/LiCpyMHS1Ok98ZVWvoXs?p=preview

**Comment by DevVersion** [comment]
@colinfang I did not reference that issue to be closed, because I thought there are also issues with the `TabGroup`?

**Comment by DevVersion** [comment]
Just tested the `selectChange` and `focusChange` output and everything seemed to work as expected.
