### ISSUE TITLE
[FR] Outlined Button

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#11253]
#### Bug, feature request, or proposal:
Feature Request: Outlined Button

#### What is the expected behavior?
https://material.io/design/assets/1rI63_05lNHyMtSwrnzXJ1Erg0TbkSDTY/buttons-types-all.png
![image](https://user-images.githubusercontent.com/7990765/39844171-f378f47c-53ee-11e8-9c65-4d5629fd0bce.png)

**Comment by jelbourn** [comment]
It already exists. It's `mat-stroked-button`

**Comment by Ploppy3** [comment]
@jelbourn Thx, it's not possible to learn about that alone yet because the attribute is missing in the doc at https://material.angular.io/components/button/overview

**Comment by jelbourn** [comment]
I already sent a PR adding it; it will be in the next docs push later today

**Comment by Ploppy3** [comment]
@jelbourn are they other undocumented changes?

**Comment by jelbourn** [comment]
Not that I know of
