### ISSUE TITLE
mat-error with MatChipInput is not displayed under the input

### ISSUE THREAD

**Issue by loremaps** [angular/material2#11260]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Be able to use [mat-error](https://material.angular.io/components/form-field/overview#error-messages) with [MatChipInput](https://material.angular.io/components/chips/overview#chip-input) in the same way that we can use `mat-hint`.

#### What is the current behavior?
The error message is not visible below the input.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>

https://stackblitz.com/edit/angular-ktsffr

#### What is the use-case or motivation for changing an existing behavior?
Example use case: show `<mat-error>` when more than 3 chips are in the chip list.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.0.0

#### Is there anything else we should know?
Placing `<mat-error>` inside `<mat-chip-list>` just below `<input>` shows the error message but it not in the correct location (i.e. below the input's line). Please see provided StackBlitz.

**Comment by CurtisDS** [comment]
This works as intended. Error text only appears when the form field is in an error state. If you look at the [documentation](https://material.angular.io/components/chips/api#MatChipList), `MatChipList` has an `errorState` property which you need to set to true when there is an error.

It works fine. Here is how to do it:

https://stackblitz.com/edit/angular-ktsffr-xsblwn?file=app/chips-input-example.ts

**Comment by loremaps** [comment]
Thank you @CurtisDS!

**Comment by Dymys** [comment]
thank you
