### ISSUE TITLE
[Button Toggle] Initial value of [0] does not work when values are indicies

### ISSUE THREAD

**Issue by andrewseguin** [angular/material2#11279]
https://stackblitz.com/edit/angular-ulbznt?file=app/button-toggle-exclusive-example.html

In the example, the first option should be selected.

**Comment by tinayuangao** [comment]
The problem is when using `[value]`, the value is set before the list of MatButtonToggles available to the button toggle group. Using `[ngModel]` will make it work.

This is a bug we should fix.
