### ISSUE TITLE
datepicker: Datepicker with custom formats not working in Stackblitz

### ISSUE THREAD

**Issue by ewaschenko** [angular/material2#11271]
#### Bug, feature request, or proposal:
Bug

Datepicker with custom formats does not behave the same in Stackblitz as it does on the doc site

#### What is the expected behavior?
Stackblitz example should work the same as the doc example

#### What is the current behavior?

When the Datepicker with custom formats example is opened in Stackblitz, the datepicker initially does not display a date, and when a date is chosen it resorts to the default 5/11/2018

#### What are the steps to reproduce?

[https://stackblitz.com/angular/koooogrpmjaj?file=app%2Fdatepicker-formats-example.ts](https://stackblitz.com/angular/koooogrpmjaj?file=app%2Fdatepicker-formats-example.ts)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.0
Material 6.0.1
Typescript

**Comment by mmalerba** [comment]
dup of #9780
