### ISSUE TITLE
Grid List documentation (MD spec link)

### ISSUE THREAD

**Issue by jedjebari** [angular/material2#11282]
The documentation for the Grid List component provides a link to Material Design spec, but the link has changed.
Today the link https://www.google.com/design/spec/components/grid-lists.html redirects to Image List component (https://material.io/design/components/image-lists.html) instead of Layout Grid (https://material.io/develop/web/components/layout-grid/).

I guess you might want to update this link.

**Comment by jelbourn** [comment]
Fixed in #11288
