### ISSUE TITLE
Cant remove chip with MatChipList Autocomplete Example

### ISSUE THREAD

**Issue by CurtisDS** [angular/material2#11290]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The chip should be removed when clicking the remove button.

#### What is the current behavior?
clicking remove does nothing

#### What are the steps to reproduce?
Using the autocomplete example on the [angular website](https://material.angular.io/components/chips/overview#chip-input)... try and remove a chip.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.0.1

**Comment by gabrieltbmaestro** [comment]
It's really only a mistake in the docs example. The correct event on the mat-chip component should be "removed" instead of "remove", as demonstrated by the example for Chip Inputs.

`(removed)="remove(fruit)"`

**Comment by CurtisDS** [comment]
this is fixed by PR #11175
