### ISSUE TITLE
Overlay service

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#113]
- [x] Portals and PortalHosts
- [x] DomPortalHost
- [x] Skeleton Overlay service
- [ ] Overlay sizing
- [x] Overlay global positioning
- [x] Overlay relative positioning
- [ ] Overlay scrolling
- [ ] Overlay animation

**Comment by zigzag95** [comment]
How can we help to close this issue and start interesting components

**Comment by ratscrew** [comment]
would it be possible to return the component from the promise after its attached:

line 14 from https://github.com/angular/material2/blob/master/src/core/overlay/overlay-ref.ts
```
  attach(portal: Portal<any>): Promise<any> {
    return this._portalHost.attach(portal).then(() => {
      this._updatePosition();
    });
  }
``` 

would there be any objection to making it:
```
  attach(portal: Portal<any>): Promise<any> {
    return this._portalHost.attach(portal).then((_comp) => {
      this._updatePosition();
      return _comp;
    });
  }
``` 

my current use case is for a right click context menu that I need to bind to after its attached.

**Comment by jelbourn** [comment]
@ratscrew I might be possible to play with the generics a bit to cut out some of the `any`; it's definitely something I want to explore before I consider the portal / overlay stuff to be mature enough to release on its own.

**Comment by DennisSmolek** [comment]
+1 for @ratscrew's issue.. I was also just tearing my hair out trying to figure out how to access the component ref of the resulting portal component when I used the ComponentPortal. 

I'm re-writing a set of components that use the dynamicComponentLoader and pass values from a directive to the resulting popup but I can't seem to access the ComponentRef any other way. For the time being I'm using the modded version..

**Comment by jelbourn** [comment]
Closing this issue for now, going to track remaining issues in smaller issues.
