### ISSUE TITLE
Unintentional autofocus when using cdkTextareaAutosize 

### ISSUE THREAD

**Issue by hettiger** [angular/material2#11308]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Textarea should not autofocus.

#### What is the current behavior?
Textarea get's autofocus when using cdkTextareaAutosize.

#### What are the steps to reproduce?
~~https://stackblitz.com/edit/angular-rtrc1b~~

__EDIT__ Please see https://github.com/angular/material2/issues/11308#issuecomment-389446082

Simple debug in an iOS Simulator or on a real device using Mobile Safari.
Add / Remove the `cdkTextareaAutosize` Directive, then reload to reproduce.

#### What is the use-case or motivation for changing an existing behavior?
Using `pristine` is no longer really an option because `cdkTextareaAutosize` breaks this for Mobile Safari. While the textarea is gaining autofocus the virtual keyboard does not pop up even thought there's visual feedback that the textarea is having focus. It's really a weird user experience and should get fixed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
* Angular: 6.0.0
* Material: 6.0.1
* OS: iOS 11.3.1
* TypeScript: ? (Stackblitz)
* Browsers: Mobile Safari

#### Is there anything else we should know?
I've attached screenshots of the expected behavior and the actual behavior.

| Expected Behavior | Actual Behavior
| --- | ---
| ![simulator screen shot - iphone x - 2018-05-13 at 19 43 54](https://user-images.githubusercontent.com/4583871/39970190-b33df348-56e7-11e8-9d52-42601689d076.png) | ![simulator screen shot - iphone x - 2018-05-13 at 19 44 06](https://user-images.githubusercontent.com/4583871/39970191-b35740f0-56e7-11e8-9cad-846580bcb99e.png)

**Comment by hettiger** [comment]
@pfeigl 

So this should now be working:

- https://stackblitz.com/edit/angular-ge466g
- https://angular-ge466g.stackblitz.io

Sorry for the inconvenience.

**Comment by pfeigl** [comment]
Thanks, just gave it a try and can reproduce with the following simple code:
```html
<textarea id="box"></textarea>

<script type="text/javascript">
    var textarea = document.getElementById("box");
    textarea.setSelectionRange(0, 0);
</script>
```
which is pretty much what is happening internally
