### ISSUE TITLE
Tooltip: Positioning does not work in Dialog

### ISSUE THREAD

**Issue by ilianiv** [angular/material2#11319]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Correct tooltip positioning

#### What is the current behavior?
If you set `[matTooltipPosition]="'right'"` to a tooltip located in material dialog the hint appears on the left.

![image](https://user-images.githubusercontent.com/3925630/40001904-e25c1faa-5797-11e8-8c29-881a68d6cf8c.png)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-lbnuwq

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
 @angular/core@6.0.0
 @angular/material@6.0.0
 typescript@2.7.2
```

- Windows 10
- Chrome 66 (not a browser related issue - same on Firefox)

**Comment by crisbeto** [comment]
Should be fixed by https://github.com/angular/material2/pull/11285. Until the fix gets in, you should be able to work around it by setting the `direction` to `ltr` explicitly. [Here's a fork if your example](https://stackblitz.com/edit/angular-lbnuwq-morcvw?file=app/dialog-overview-example.ts).
