### ISSUE TITLE
mat-selection-list selectionChange Property not working while moving from angular5 to angular6

### ISSUE THREAD

**Issue by anilarya** [angular/material2#11311]
Earlier in angular5 , this was working fine which is not working  in angular6 at all . Can anyone check this one  ?

https://stackblitz.com/edit/angular-ncxfwa?file=.angular-cli.json
https://angular-ncxfwa.stackblitz.io

**Comment by crisbeto** [comment]
That's because you're binding the `selectionChange` event on the `mat-list-option`, but it's actually the `mat-selection-list` that emits it. [Here's a fork of your example](https://stackblitz.com/edit/angular-ncxfwa-3i9fz9?file=app/list-selection-example.html).
