### ISSUE TITLE
Support focus method on checkbox and radio inputs

### ISSUE THREAD

**Issue by divyakumarjain** [angular/material2#1131]
#### Bug, feature request, or proposal:

Support focus method on checkbox and radio inputs
#### What is the expected behavior?

Calling focus method on MdCheckbox and MdRadioButton should change focus to these instance. Also other focusable items in browser should lose the focus.
#### What is the current behavior?

focus method does not exists on MdCheckbox and MdRadioButton thus get error such as `focus is not a function`
#### What are the steps to reproduce?

http://plnkr.co/edit/9RJ5DOuPMK8b3zPeR95J?p=preview
#### What is the use-case or motivation for changing an existing behavior?

Similar to MdInput there should be way to focus on elements. this can be used for focusing to element with validation error
#### Which versions of Angular, Material, OS, browsers are affected?

Was able to reproduce on both firefox and chrome.

**Comment by jelbourn** [comment]
This also would apply to slide-toggle and button-toggles.

**Comment by DevVersion** [comment]
One possible approach could be manually forwarding the dispatched DOM event, instead of creating outputs for the `focus` and `blur` manually.

See my draft: https://github.com/angular/material2/commit/0b062fa65aee988126c2ad32e2e16c6a7fd718cb

**Comment by jelbourn** [comment]
@tinayuangao this will apply to checkbox, radio buttons, button-toggle, and slide-toggle. 

@DevVersion this issue is about ` .focus()` method on the component rather than the fired event. We should probably handle that as well, though. File a separate issue?
