### ISSUE TITLE
[Bug] MatAutoComplete value not sticking to the input, when you select it from the dropdown. Material 6.0.1

### ISSUE THREAD

**Issue by ltoshev** [angular/material2#11312]
#### Bug, Material 6.0.1, Angular 6

I have the following code:

    <mat-form-field class="example-full-width">
      <input matInput placeholder="Product" aria-label="Product" [matAutocomplete]="auto" [formControl]="mealCtrl">
      <mat-autocomplete #auto="matAutocomplete" [displayWith]="displayFn">
        <mat-option *ngFor="let prod of filteredProducts | async" [value]="prod.product_id">
          
          <span>{{ prod.name }}</span> |
          <small>Kkal: {{prod.kkal}}, Protein: {{prod.protein}}, Carbs: {{prod.carbs}}, Fats: {{prod.fats}}</small>
        </mat-option>
      </mat-autocomplete>
    </mat-form-field>

-----

in TS: 
ngOnInit() {
    this.mealCtrl.valueChanges.subscribe(data => {
        this.filteredProducts = this.foodService.searchProduct(data);
    });
  }

  addMeal() {
    this.foodService.addMeal({ type: this.mealType,
        quantity: this.quantity,
        // recipe_id?: number;
        product_id: this.mealCtrl.value }).subscribe(() =>{
      this.dialogRef.close();
    });
  }

  displayFn(p?: IProduct): string | undefined {
    return p ? p.name : undefined;
  }

When I search for a product, the autocomplete dropdown shows - which is fine.

I have the following trouble:

1. When I try to select a product from the dropdown, the dropdown closes and the product does NOT show up in the field as selected.

Why is that?

As a result when I try to submit the data, this.mealCtrl.value is undefined. Basically valueChanges fires with undefined and removes the value from the input once I click to select the item.

What I do wrong? Also I cannot find how to delay the firing of the search function to the JSON api.

Please help. It would be welcome to have a bit more documentation on the material site, and a bit more end to end examples.

**Comment by ltoshev** [comment]
I see for people this works:

this.filteredProducts = this.mealCtrl.valueChanges.pipe(
      startWith(null),
      debounceTime(300),      
      map(val => this.filter(val))
    );

where filter() returns plain value like IProduct[]

but my API returns 

this.foodService.searchProduct(val) which is Observable<IProduct[]>

so I cannot figure out, how to transform this observable to the plain value so that it can be hooked.

I tried this:

filter(val: string): IProduct[] {
    if (val) {
      this.foodService.searchProduct(val).pipe(map((x) => {
        return x;
      })).subscribe();
    }
}

does not work.

also tried this:

this.filteredProducts = this.mealCtrl.valueChanges.pipe(
      startWith(null),
      debounceTime(300),      
      this.foodService.searchProduct(val)
    );

but then it complains for filteredProducts is not Observable<Observable<IProduct[]>> ??

**Comment by ltoshev** [comment]
I got it to work with this:

this.filteredProducts = this.mealCtrl.valueChanges.pipe(
      startWith(''),
      debounceTime(300),      
      flatMap(val => this.foodService.searchProduct(val))
    );

**Comment by ltoshev** [comment]
But I still get the problem when the drop down is shown, and I select something it does not stay in the input as selected.

**Comment by tinayuangao** [comment]
@ltoshev Could you please provide a StackBlitz reproduction? https://goo.gl/wwnhMV

**Comment by ltoshev** [comment]
I have resolved it. The problem was the value binding. I needed to bind the whole object as return value.
