### ISSUE TITLE
MatLabel not properly aligned on the new MatFormField outline appearance when using MatPrefix with icons

### ISSUE THREAD

**Issue by Marcio-RF** [angular/material2#11321]
#### Bug, feature request, or proposal:
The new outline appearance property introduced on Material 6 is great. After updating the package, I just added appearance="outline" to my templates and got beautifully rendered form fields, just the way I expected. However, on the fields that have a MatPrefix applied with an icon, the label generated by the MatLabel component does not align properly. This is even mentioned in the documentation, where is suggested that prefix should not be used with the new appearance. 

#### What is the expected behavior?
MatLabels on MatFormFields with appearance="outline" should align properly even when they contain MatPrefix with icons.

#### What is the current behavior?
MatLabels on regular fields align beautifully. When the MatField contains a MatPrefix with an icon on it, they MatLabel align with the actual input field instead of fitting on its proper place, which would be aligned with the icon/MatPrefix. It seems that the gap generated even match the label text size.

#### What are the steps to reproduce?
The code below renders the field with the label not properly aligned:

`<mat-form-field appearance="outline">`
    `     <mat-label>Outline form field</mat-label>`
    `<mat-icon matPrefix>sentiment_very_satisfied</mat-icon>`
    `<input matInput placeholder="Placeholder">`
`</mat-form-field>`

#### What is the use-case or motivation for changing an existing behavior?
The new appearance property is great. It would be a shame not to be able to use it properly with icons, that help improve the form look and feel. I wonder if there is a fix in mind for the future.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.1
Angular Material 6.0.1
Chrome

Congratulations to the Angular Material team for the great work achieved.

Regards,
Marcio

**Comment by mmalerba** [comment]
dup of #11513
