### ISSUE TITLE
CDK Overlay Flexible Reference API

### ISSUE THREAD

**Issue by amcdnl** [angular/material2#11320]
# Issue
The `flexibleConnectedTo` method on the `OverlayPositionBuilder` accepts a `ElementRef`. Ideally this would allow a `nativeElement` passed directly. If you pass `flexibleConnectedTo({ nativeElement: event.target })` everything works fine.

**Comment by amcdnl** [comment]
cc @crisbeto

**Comment by amcdnl** [comment]
@crisbeto - What about the `getAncestorScrollContainers()` API too?

**Comment by crisbeto** [comment]
Done.
