### ISSUE TITLE
Lazy rendering Mat-Menu, not correctly creating

### ISSUE THREAD

**Issue by olcayusta** [angular/material2#11331]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
matMenuContent should not be added again

#### What is the current behavior?
If you click the button quickly, the menu is re-added
![menubug](https://user-images.githubusercontent.com/24437654/40039095-ac2c0928-581d-11e8-8990-4d81b88b5170.gif)

#### What are the steps to reproduce?
[https://stackblitz.com/edit/angular-czk5cg](https://stackblitz.com/edit/angular-czk5cg)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0
Browsers: Chrome, Firefox.. All browsers.

**Comment by simeyla** [comment]
I'm been experiencing the same. I have a dynamic list of items and when it changed the previous list of items was still present. For now I'm having to take the performance hit of removing `<ng-template matMenuContent>` and just putting the content directly in the menu.
