### ISSUE TITLE
Custom animations in cdk components

### ISSUE THREAD

**Issue by jpzwarte** [angular/material2#11337]
#### Bug, feature request, or proposal:
If it is technically possible, can we add the ability to customize the enter/leave animations in Cdk components? (specifically CdkDialog)

#### What is the expected behavior?
Ability to customize animations when using CDK.

#### What is the current behavior?
Hardcoded animation opacity fade in/out.

#### What are the steps to reproduce?
Hardcoded animations here: https://github.com/angular/material2/blob/master/src/cdk-experimental/dialog/dialog-container.ts#L56

**Comment by jpzwarte** [comment]
Any ideas if this is possible @matsko ?

**Comment by josephperrott** [comment]
Closing as generalized support for this is something that would need to be addressed at the Angular platform level.

Specific to the `CdkDialog`, you should be able to use your own animation by using your own `DialogContainer` that extends the one from the CDK.  You can see an example of how this can work [here](https://github.com/josephperrott/material2/blob/cdk-dialog-example/src/demo-app/dialog/bootstrap-dialog.ts).

**Comment by jpzwarte** [comment]
Thanks!
