### ISSUE TITLE
Material Schematics missing external dependency

### ISSUE THREAD

**Issue by cgatian** [angular/material2#11341]
#### Bug, feature request, or proposal:
**parse5** is used within [schematics/utils/html.ts](https://github.com/angular/material2/blob/dec91ce08f6a4ceab19dbf3455003ad26c533436/src/lib/schematics/utils/html.ts#L2) but is never listed as a dependency in `package.json`. This prevents being able to extending the material schematics without library developers adding this dependency.

#### What is the expected behavior?
**parse5** should be listed as a dependency of material schematics.

#### What is the current behavior?
import/require statement fails when material schematic collection is used with `externalSchematic`
```
externalSchematic('@angular/material', 'material-shell', {}),  // Errors
```

#### What are the steps to reproduce?
Clone this repository and follow README

#### What is the use-case or motivation for changing an existing behavior?
Developers wishing to extend the existing Material schematics need to include **parse5** as a dependency.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.0+

**Comment by amcdnl** [comment]
@jelbourn - I don't see this anywhere in the packages? How is this even working LOL?

**Comment by jelbourn** [comment]
@amcdnl most people probably have it installed incidentally due to some other package (maybe CLI)
