### ISSUE TITLE
Mat-tree is broken on examples

### ISSUE THREAD

**Issue by dinohorvat** [angular/material2#11353]
#### Bug, feature request, or proposal:
**mat-tree** can be easily broken. Tested it on your demo
https://material.angular.io/components/tree/examples

#### What is the current behavior?

<img width="911" alt="screen shot 2018-05-16 at 00 12 52" src="https://user-images.githubusercontent.com/11750069/40086258-edc4cf70-589d-11e8-9a9c-d7aa72ca59cd.png">

#### What are the steps to reproduce?
1) Try opening parent node, and then open child node as well.
2) Close parent node.
3) Repeat

You will end up creating multiple child nodes, every time you do this procedure.

**Comment by tinayuangao** [comment]
Fixed by #11728
