### ISSUE TITLE
Mat-sheet can not update mat-field from promise

### ISSUE THREAD

**Issue by avechuche** [angular/material2#11351]
#### Bug, feature request, or proposal:
Bug

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ecw7ff?file=src%2Fapp%2Fapp.component.ts

If you open the dialog, after 1 second the input is updated, but if you open the same component from a mat-sheet-bottom, you need to click on the component to see the change.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.0.2
Angular 6.0.1

**Comment by tinayuangao** [comment]
@avechuche After you updated the text in input, you call `changeDetectorRef.markForCheck` to notify the change.

**Comment by crisbeto** [comment]
Closing since there's no way for us to know when to trigger change detection automatically.
