### ISSUE TITLE
IE 10 and eage(11) grid issue 

### ISSUE THREAD

**Issue by PyroFlaming** [angular/material2#11359]
#### Bug, feature request, or proposal:
BUG
![2018_05_16_08_13_55_](https://user-images.githubusercontent.com/39325320/40097855-2639621a-58e1-11e8-8404-088d59b8c448.jpg)

#### What is the expected behavior?
footer is bottom of the page 

#### What is the current behavior?
in middle of the page 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
on your site

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material.angular.io/pull/451.
