### ISSUE TITLE
Mat-Chip with Mat-Auto Complete

### ISSUE THREAD

**Issue by sivahanuman** [angular/material2#11358]
Bug

Mat-Chip with Mat-Auto Complete removable and auto complete shows option list while click on text box after select a item 

1. Can't remove Mat-Chip
2. Once select option from auto complete the list not appearing on next clicks.
3. if i select orange, on the next clicks it shows orange only .( to view all other options need to press delete button even though no text on the input  ) 

#### What are the steps to reproduce?
https://stackblitz.com/angular/gxpmvevdpqq?file=app%2Fchips-autocomplete-example.ts

**Comment by gwidonw** [comment]
@sivahanuman You have a typo in your template. Please change `(remove)` to `(removed)` in `chips-autocomplete-example.html` line 7

**Comment by crisbeto** [comment]
Closing as a non-issue. The typo was also fixed in the docs recently, but might not have been released yet.
