### ISSUE TITLE
[feature request] md-input focus class

### ISSUE THREAD

**Issue by sonderbazz** [angular/material2#1135]
#### Bug, feature request, or proposal:

Focus on md-input-element sets the md-focused class on md-input
#### What is the expected behavior?

I would like to be able to style on all sub elements within the md-input when the input has focus.
#### What is the current behavior?

Only ripple and placeholder gets a md-focused class added
#### What are the steps to reproduce?

Set focus on a md-input element check to see if its possible to style all subelements to md-input
#### What is the use-case or motivation for changing an existing behavior?

Would give more flexibility to modding the design

**Comment by hansl** [comment]
There's a perfectly correct version by doing something like this:

```html
<md-input #example [class.my-custom-focus]="example.focused">
```

We do not want to export special classes only for the purpose of styling like this. If you need styling for a component you should apply your own custom classes to it.

Thanks!

**Comment by sonderbazz** [comment]
Fair enough - and thanks for the simple solution. :)
