### ISSUE TITLE
Menu positioning going wrong on scroll

### ISSUE THREAD

**Issue by frmtlp** [angular/material2#11365]
**Bug, feature request, or proposal:**
Bug

**What is the expected behavior?**
Menu should stay where initiated

**What is the current behavior?**
Menu moves down, away from initiated position

**What are the steps to reproduce?**
https://stackblitz.com/edit/angular-gxkc8e

Click the menu and scroll down with displayed menu

**What is the use-case or motivation for changing an existing behavior?**

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**
"@angular/core": "^6.0.0", "@angular/cli": "~6.0.1", "@angular/material": "^6.0.2", "@angular/cdk": "^6.0.2"

**Comment by lacolaco** [comment]
Any workaround for this?

**Comment by crisbeto** [comment]
Reopening since we had to revert the fix.

**Comment by sollenne** [comment]
Looks like @crisbeto has a PR open for this but it's been open for almost a month. Who's on PR duty this week? MERGE IT!

**Comment by jsdream** [comment]
@crisbeto This is quite a serious bug. Any possibility this can be fixed in the next release?

**Comment by crisbeto** [comment]
The PR is marked as being important, but it does affect a lot of components which makes it harder to merge.

**Comment by crisbeto** [comment]
Reopening because we had to revert the fix again. Fix is resubmitted as #12624.

**Comment by snakone** [comment]
Im using "@angular/material": "^6.4.7" issue still there on a fixed bottom nav

**Comment by vapits** [comment]
Same issue here but on ALL other browsers except Chrome.
If you open the menu and scroll the menu moves even outside the viewport.

**Comment by vapits** [comment]
The problem exists also in docs page.
But it is always replicaable if you host the menu in a fixed positioned item.

In that case the solution is to set position fixed to `.mat-menu-panel` and set the offset etc to your preferences. This is the way I solved it for my app.

**Comment by peterhogg** [comment]
I've found closing on scroll somewhat fixes the issue: 
`@ViewChild(MatMenuTrigger) trigger: MatMenuTrigger;`
`window.addEventListener('scroll', this.scroll, true)`

`scroll = (): void => {
	             this.trigger.closeMenu();
		}
	};`

**Comment by rezabayesteh** [comment]
I still have this problem in 7.3.3!

**Comment by jkon** [comment]
I am having this issue too. the more annoying part is that the menu doesn't show in the viewport at all if the user is scrolled down at all. So, @peterhogg 's workaround won't work in that case. It's been 18 days since the last comment and we all need a fix

**Comment by sebastianlaag** [comment]
Same issue here. When scrolling down on a mobile device the closed mat-menu pops up. Really very annoying.

**Comment by harellevy** [comment]
using angular 7.2.6, angular material and cdk 7.2.0 works finally (i had to downgrade material and cdk to 7.2.0 to avoid the bug - in my case in MatTooltip positioning on the bottom part of the mobile screen.)

**Comment by AnshulMahajan10** [comment]
Upgraded to latest angular material and it worked
