### ISSUE TITLE
Bug mat-form-field mat-label

### ISSUE THREAD

**Issue by txdear** [angular/material2#11360]
When I try to use `mat-label` inside `mat-form-field` in the different `form` tag, my browser won't load the html. Is there something that I miss or is this a bug? please help.

**Comment by txdear** [comment]
I think the problem is exist when I try to use `mat-label` on different `mat-tab` tag. how i suppose to do this?

**Comment by AnthonyNahas** [comment]
@txdear Im facing exactly the same problem!! 

If I add a `mat-label` inside the `mat-form-field` the browser will not render anymore, but instead the web app will go in ANR (application not responding)!

It took me over 3 hours to find out the problem!

in my [ngx-auth-firebaseui](https://github.com/AnthonyNahas/ngx-auth-firebaseui)

i need to differentiate between register and confirm template!

That means the `mat-input-field` as well as `mat-label` are inside a 'ng-temlate' element!

If i remove the `ng-template`, everything works fine again!!

As workaround! I will eliminate now the ng-template element and I hope they will fix this bug soon !

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
