### ISSUE TITLE
Can't bind to 'active' since it isn't a known property of 'a'

### ISSUE THREAD

**Issue by a-sahel** [angular/material2#11372]
#### Bug, feature request, or proposal:
I'm using the `mat-tab-link` inside a `mat-tab-nav-bar` and I'm getting the error:

```
Error: Template parse errors:
Can't bind to 'active' since it isn't a known property of 'a'. ("gFor="let link of navLinks" [routerLink]="['/'+link.path]" routerLinkActive #rla="routerLinkActive" [ERROR ->][active]="rla.isActive">
      {{link.label}}
    </a>
```

#### What is the expected behavior?
Not getting the error

#### What is the current behavior?
Getting the error

#### What are the steps to reproduce?
```
<nav mat-tab-nav-bar>
    <a matTabLink *ngFor="let link of navLinks" [routerLink]="['/'+link.path]" routerLinkActive #rla="routerLinkActive" [active]="rla.isActive">
      {{link.label}}
    </a>
  </nav>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.2, Material 6.0.2, Safari and Chrome, Typescript 2.7.2.

**Comment by crisbeto** [comment]
Can you double-check that you've included the `MatTabsModule` in your app?

**Comment by AsantosCandor** [comment]
I am currently having the same problem. Other Material components are working. But when I try to use the same as @a-sahel gives me the same error.

**Comment by papiro** [comment]
Hmm, I'm having this same problem now, even with the `MatTabsModule`...

**Comment by MurWade** [comment]
Having this issue even though i have included `MatTabsModule` with trying to use tabs with active link  to do navs. but normal tabs work fine.

**Comment by pokmnx** [comment]
same issue here

**Comment by aparna999** [comment]
Hmm, I'm having this same problem now, even with the `MatTabsModule`. What's the solution for this?

**Comment by senthilpsg** [comment]
I am also facing the same problem.  Looking for the solution

**Comment by zbralex** [comment]
> Hmm, I'm having this same problem now, even with the `MatTabsModule`...

need import  `MatTabsModule` in `app.module`

`imports: [MatTabsModule]`


this reply for another users

**Comment by matheusdavidson** [comment]
This is still hapenning, i have ```MatTabsModule``` in the current module and app.module
