### ISSUE TITLE
auto focusable focusable elements 

### ISSUE THREAD

**Issue by blvckf0x** [angular/material2#11374]
#### Bug, feature request, or proposal:

**Bug**

#### What is the expected behavior?

not to focus first focusable element 

#### What is the current behavior?

focus  first focusable element 

#### What are the steps to reproduce?

auto focusing is this a normal behavior?<br/>
https://stackblitz.com/angular/dydpeoydrjl?file=app%2Fsidenav-disable-close-example.html<br/>

ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.0
Node: 9.11.1
OS: win32 x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/flex-layout              6.0.0-beta.15
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

**Comment by crisbeto** [comment]
[You can disable the behavior using the `autoFocus` property.](https://stackblitz.com/edit/angular-y39jec?file=app/sidenav-disable-close-example.html)
