### ISSUE TITLE
(feat) datepicker MatCalendar - navigate periods sequentially i.e. month to year to multi year

### ISSUE THREAD

**Issue by Benno007** [angular/material2#11376]
#### Bug, feature request, or proposal:
Navigate the calendar view from month > year > multi-year, rather than month > multi-year and back again. My suggestion is to add an Input to datepicker for currentPeriodClicked which can be passed down to the calendar header component, or have that method emit an event via an Output. 

Unless there is a way to use a custom calendar header component and JUST change that method?

#### What is the expected behavior?
When starting in month mode, clicking the calendar's period link should take you to year mode, clicking it again should take you to multi year mode.

#### What is the current behavior?
When starting at month mode, clicking the Period in calendar header goes to multi-year, instead of year mode.

#### What are the steps to reproduce?
https://angular-material2-issue-9c5wid.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
Most of our customers will be placing an order within the current year, but when we upgraded from angular material 2 to 5, we noticed it was going to multi-year which isn't particularly useful. It seems a bit odd that there isn't the ability to even choose to go from month > year i.e. disabling multi-year.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
We are currently using angular 5.2.9 and material 5.2.5 and typescript 2.6.2. However, the code that determines which view to display is still in master: 
https://github.com/angular/material2/blob/master/src/lib/datepicker/calendar.ts#L104

#### Is there anything else we should know?
If I change the code from this line to what I've got below, it works as I expect, although I suppose it won't be as simple as that to implement, considering everyone else's use cases.
https://github.com/angular/material2/blob/master/src/lib/datepicker/calendar.ts#L104
Would be nice to have this:
```   
_currentPeriodClicked() {
        this._currentView = this._currentView == 'month' ? 'year' : this._currentView == 'year' ? 'multi-year' : 'month';
    }
```

**Comment by mmalerba** [comment]
I recommend creating a custom header if you want to change this behavior. (https://material.angular.io/components/datepicker/overview - see section on "Customizing the calendar header"). If you want to reuse most of the logic you can extend `MatCalendarHeader` https://github.com/angular/material2/blob/master/src/lib/datepicker/calendar.ts#L51
