### ISSUE TITLE
MatAutoComplete to have a button to clear the input

### ISSUE THREAD

**Issue by weijyewang** [angular/material2#11384]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
To have a small button at the end of the input element (maybe a small 'x') that clears the input and show all the options in the dropdown panel again.

#### What is the use-case or motivation for changing an existing behavior?
To improve UX. Without a button to clean the input, a user have to focus on the input element and clear all the text manually. The feature requested could save the user effort in populating the full option list again after entering some filtered text.

**Comment by pfeigl** [comment]
Check the `Input with a clear button` example on https://material.angular.io/components/input/examples

**Comment by crisbeto** [comment]
Closing since this is already possible with the current APIs.

**Comment by weijyewang** [comment]
@pfeigl thanks. But then when ones click on the button to clear the input, the drop down list does not appear because my filter function was not triggered.

 I was using `userForm.controls['timeZone'].patchValue('', {emitEvent: true})` inside the button's `(click)` event

**Comment by weijyewang** [comment]
Sorry, I was suppose to set the value to null instead of empty string. Thanks again for the help :)

**Comment by Memphis335** [comment]
I am not sure why this is closed because it is not currently possible or it needs better explanation. 

I am using "@angular/material": "^7.1.0",
