### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by MhmdKorhani** [angular/material2#11385]
Bug Report.

Everything should run normally after importing a module from angular material.

An error in modules 
Example: "@angular/material/button-toggle/typings/button-toggle.d.ts(136,20): error TS2315: Type 'ElementRef' is not generic."
This error came from the module itself.

I am using V 6.01

**Comment by crisbeto** [comment]
It looks like your version of `@angular/core` is still on 5.x, while Material is at 6.x. You should update to Angular 6.x.
