### ISSUE TITLE
Table shows horizontal scrollbar since v6.0.0-beta-5

### ISSUE THREAD

**Issue by klinki** [angular/material2#11380]
#### Bug, feature request, or proposal:
After updating to version `6.0.0-beta-5` our tables started to show horizontal scrollbar.
It is either bug or undocumented behavior - I looked into changelog and it mentions table only here:

* table: move padding from rows to cells (#10499) (e0321db)

If there are any other changes in tables, please note them in changelog.

#### What is the expected behavior?
There shouldn't be horizontal scrollbar.

Old version - without scrollbar
![material-design-table-ok](https://user-images.githubusercontent.com/1476175/40165490-6cc04178-59bc-11e8-9748-8eba5781cf3f.png)

New version - with scrollbar
![material-design-table-scrollbar](https://user-images.githubusercontent.com/1476175/40165491-6cdc2686-59bc-11e8-9e47-d2dffc191c46.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Any version since `6.0.0-beta-5`

**Comment by pfeigl** [comment]
Looking at the screenshot, this doesn't look like a scrollbar in the table but actually within the tabs. Please provide a stackblitz of your markup in order to reproduce the problem and see what is actually going wrong.

**Comment by andrewseguin** [comment]
Would love to help; please re-open with a reproducible example on stackblitz so we can investigate a solution

**Comment by pfeigl** [comment]
Two points which should fix your problem:

* Your headers combined should not be more than 100% (they are right now)
* You did not allow your flex boxes to shrink, which is a problem now, as first and last cell have paddings.
  Use something like this to allow shrinking for your headers `flex: 0 1 14%;` instead of `flex: 0 0 14%;`
