### ISSUE TITLE
Feature Request/Proposal: Please add menuOpened EventEmitter to mat-menu

### ISSUE THREAD

**Issue by nazarkryp** [angular/material2#11391]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
menuOpened present on mat-menu component
<mat-menu (menuOpened)="myMethod()"></mat-menu>

#### What is the current behavior?
Currently menuOpened can be accessed only via MatMenuTrigger

#### What is the use-case or motivation for changing an existing behavior?
Annoying actions need to be performed to determine if trigger is not null. Insead of being concentrated on my business login i need to determine if trigger is null
```
@ViewChild(MatMenuTrigger) public trigger: MatMenuTrigger;
...
public ngAfterViewInit(): void {
    // this.trigger can be null and you will get an error
    this.trigger.menuOpened.subscribe(() => {
        // do some actions
    });
}
```

**Comment by crisbeto** [comment]
In general we try to avoid having multiple APIs that do more or less the same. In this case adding the same out put to `mat-menu` won't really help having to null-check the `ViewChild`, because the menu could be null as well.
