### ISSUE TITLE
material-buttons does not have default space between them in v6.0 as they have in v5.0 

### ISSUE THREAD

**Issue by sandeeppatidar30** [angular/material2#11397]
#### What is the expected behavior?
It should have space between them as they have in v5.0

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by pfeigl** [comment]
This has nothing to do with the buttons of angular material. The difference is, that Angular 6 changed `preserveWhitespaces` to false in the default. 

This changes your your generated HTML from something like this `<button></button> <button></button>` to `<button></button><button></button>` (observe the missing whitespace here)

For details read the Angular changelog found here: https://github.com/angular/angular/blob/master/CHANGELOG.md, specifically this point: 

> * **core:** set `preserveWhitespaces` to false by default ([#22046](https://github.com/angular/angular/issues/22046)) ([f1a0632](https://github.com/angular/angular/commit/f1a0632)), closes [#22027](https://github.com/angular/angular/issues/22027)

**Comment by Spawnrad** [comment]
But why when we add @Component{preserveWhitespaces: true} we don't have the space?
Since have update to 6.0 i have no space between buttons.

**Comment by Spawnrad** [comment]
Yes it looks like we need to add : 
@Component({preserveWhitespaces: true}) to have the space between buttons now.

**Comment by josephperrott** [comment]
Closing as this is likely the result of `preserveWhitespaces`

**Comment by tonysamperi** [comment]
The problem for me is that I also created a css rule to add margin.
Of course it gets overridden by default material styling (yes, my rules are loaded after the material theme, but still).
I had to wrap all buttons in divs. Horrible.
