### ISSUE TITLE
Documentation for including core styles is not clear

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#1139]
As of alpha.7, applications using the components need to include the core styles in addition to individual components. 

- [x] All core styles should be consolidated into a single theme file under `@angular/material/core`. 
- [ ] Our getting started guide should reflect this step. 

Missing these styles can manifest several odd effects, such as:
* Ripples look insane
* Overlays are not positioned correctly.

**Comment by artiz** [comment]
Workaround for webpack builds:
`import 'style!@angular2-material/core/style/core.css'; `
`import 'style!@angular2-material/core/overlay/overlay.css';`
works for me in https://github.com/AngularClass/angular2-webpack-starter

**Comment by elvirdolic** [comment]
In the latest version 2.0.0-alpha.9 this has changed. The result is the same as described here.

instead of including overlay and core.css I have included now

../node_modules/@angular/material/core/theming/prebuilt/purple-green.css

but it's not working because the buttons are weird.

**Comment by Salma7amed** [comment]
How can I include the theme in my application incase of using webpack v2.1.0 and material v2.0.0-alpha.9

**Comment by KKrisu** [comment]
@Salma7amed You need to add 
```
@import '../node_modules/@angular/material/core/theming/prebuilt/indigo-pink.css';
```
or other theme to your styles.css

**Comment by RoxKilly** [comment]
It seems that none of the prebuilt themes match the CSS styling of the previous release (`alpha 8`). That had a shade of green as primary, and a shade of pink as secondary I believe. 

Is this an oversight? Because it means that to maintain the previous look, we need to build a custom theme.

**Comment by Tim-Schwalbe** [comment]
I don't even see in the docu that I have to include the css.  I only make it work by searching the web.
Is this correct or did I watch in the wrong place?

**Comment by tommysella** [comment]
Even though it's described in the https://github.com/angular/material2/blob/master/GETTING_STARTED.md, it would be good to make it more clear that it's a requirement, and really need to be included.

**Comment by alexjoverm** [comment]
I must point out @tommysella comment, I've spent some precious time finding out why the components were not styling correctly, till I included a theme. It doesn't looks like required in the docs.

**Comment by kara** [comment]
Closed by https://github.com/angular/material2/pull/1447.

**Comment by peterpeterparker** [comment]
Ok I just gonna let that here because I had to modify a bit the solution of @artiz and @elvirdolic

First install `style-loader`

    npm install --save-dev style-loader

Then in your module import like following

   import 'style-loader!../../node_modules/@angular/material/prebuilt-themes/indigo-pink.css';

This tutorial about how to include material might also be useful

https://github.com/AngularClass/angular-starter/wiki/How-to-include-Material
