### ISSUE TITLE
mat-select within "boxed" form-field, wrong allignment of dropdown icon

### ISSUE THREAD

**Issue by richardsengers** [angular/material2#11399]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Better allignment of dropdown icon

#### What is the current behavior?
Dropdown icon is centered in the .mat-form-field-wrapper

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-z9ehue?file=app/select-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6
Chrome 66

#### Is there anything else we should know?
According to the material specs the dropdown icon should be centered based on the text

![dropdown](https://user-images.githubusercontent.com/810038/40236695-aacab604-5aae-11e8-8c42-18cad2e17a97.PNG)

Currently it looks like this
![dropdown-wronmg](https://user-images.githubusercontent.com/810038/40236850-18150eb2-5aaf-11e8-8e7e-fca157c1375d.PNG)

**Comment by richardsengers** [comment]
Another example of a dropdown from the docs
![dropdown2](https://user-images.githubusercontent.com/810038/40237318-6ba773d4-5ab0-11e8-9707-ba4fca647c77.PNG)

(resource: https://material.io/design/components/menus.html#exposed-dropdown-menu)

**Comment by crisbeto** [comment]
This seems more like an inconsistency between how the label is aligned when using the `placeholder` versus using the `mat-label` element. Here's a comparison between the two:

![angular-z9ehue_-_stackblitz_-_google_chrome_2018-05-19_09-32-38](https://user-images.githubusercontent.com/4450522/40266222-aaea0dc6-5b47-11e8-9675-827f3e3f2f49.png)

**Comment by crisbeto** [comment]
I'd say that it's the same issue. Both the placeholder and the value are rendered inside the same element.

**Comment by mmalerba** [comment]
We need to do a pass and make sure our form field styles are in line with the latest spec. We based our implementation off a non-final version of the spec before it was released. Tracking in #11513
