### ISSUE TITLE
Material 2.0

### ISSUE THREAD

**Issue by y3rt** [angular/material2#11401]
#### Bug, feature request, or proposal:
REQUEST

#### What is the expected behavior?
Material 2.0 Spec inclusion

#### What is the current behavior?
Material 1.0 spec

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
N/A

#### What is the use-case or motivation for changing an existing behavior?
Looking forward

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0

#### Is there anything else we should know?

Is there a timeline for the update to the Material 2.0 spec?

**Comment by mtrdp642** [comment]
Multiple issues have been created asking this question (#11222 and #11039). There is currently nothing to report.

**Comment by y3rt** [comment]
@mtrdp642 Thanks for the info!
