### ISSUE TITLE
autocompleteDisabled porperty of MatAutocompleteTrigger doesnt work.

### ISSUE THREAD

**Issue by CurtisDS** [angular/material2#11405]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I should be able to use this property to turn off an autocomplete.

as in here: https://stackblitz.com/edit/angular-3ebz9m-tx7tf8?file=app%2Fautocomplete-overview-example.html

(but without needing to use ngIf and duplicating code)

As per the [documentation](https://material.angular.io/components/autocomplete/api#MatAutocompleteTrigger) I should be able to user autocompleteDisabled to turn off the autocomplete

#### What is the current behavior?
An Error: `Can't bind to 'autocompleteDisabled' since it isn't a known property of 'input'`
https://stackblitz.com/edit/angular-3ebz9m-6qsqbf?file=app/autocomplete-overview-example.html

#### What is the use-case or motivation for changing an existing behavior?
being able to have flexible components that can be both autocomplete input fields, or other types of input fields like password fields.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.0.2

**Comment by crisbeto** [comment]
The docs aren't displaying the property correctly. The input is called `matAutocompleteDisabled`, not `autocompleteDisabled`. It should work if you rename your input binding to `matAutocompleteDisabled`.

**Comment by CurtisDS** [comment]
@crisbeto that still doesn't work https://stackblitz.com/edit/angular-3ebz9m-rbgurk?file=app/autocomplete-overview-example.html

**Comment by crisbeto** [comment]
It seems like the changes haven't been released yet, because https://github.com/angular/material2/pull/11142 is targeted for the next minor release @CurtisDS. I think the confusion comes from the fact that we build our docs from `master`, which doesn't necessarily reflect what is released.
