### ISSUE TITLE
Misspelling in ChipList documentation

### ISSUE THREAD

**Issue by sergey-morenets** [angular/material2#11402]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
There should be (removed)="remove(fruit)">

#### What is the current behavior?
When you open this page https://material.angular.io/components/chips/overview and view source for the Chips Autocomplete example(HTML) you can see the line: (remove)="remove(fruit)">.  

#### What is the use-case or motivation for changing an existing behavior?
Incorrect documentation

**Comment by crisbeto** [comment]
This has been fixed in https://github.com/angular/material2/pull/11175.
