### ISSUE TITLE
getting 'md-content' is not a known element: MdSidenavLayout@0:165 when using latest builds

### ISSUE THREAD

**Issue by qdouble** [angular/material2#1141]
I just updated to the latest builds and I'm getting this error when trying to load my project. I've tried it on 7-4 and 7-9, the same thing occurs. 

Here's the full error:

> zone.js:484 Unhandled Promise rejection: Template parse errors:
'md-content' is not a known element:
1. If 'md-content' is an Angular component, then verify that it is part of this module.
2. If 'md-content' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("class.md-sidenav-shown]="_isShowingBackdrop()"></div> <ng-content select="md-sidenav"></ng-content> [ERROR ->]<md-content [ngStyle]="_getStyles()"> <ng-content></ng-content> </md-content> "): MdSidenavLayout@0:165 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
'md-content' is not a known element:
1. If 'md-content' is an Angular component, then verify that it is part of this module.
2. If 'md-content' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("class.md-sidenav-shown]="_isShowingBackdrop()"></div> <ng-content select="md-sidenav"></ng-content> [ERROR ->]<md-content [ngStyle]="_getStyles()"> <ng-content></ng-content> </md-content> "): MdSidenavLayout@0:165
    at TemplateParser.parse (webpack:///./~/@angular/compiler/src/template_parser/template_parser.js?:128:19)
    at RuntimeCompiler._compileTemplate (webpack:///./~/@angular/compiler/src/runtime_compiler.js?:244:51)
    at eval (webpack:///./~/@angular/compiler/src/runtime_compiler.js?:167:83)
    at Set.forEach (native)
    at compile (webpack:///./~/@angular/compiler/src/runtime_compiler.js?:167:47)
    at ZoneDelegate.invoke (webpack:///./~/zone.js/dist/zone.js?:332:29)
    at Zone.run (webpack:///./~/zone.js/dist/zone.js?:225:44)
    at eval (webpack:///./~/zone.js/dist/zone.js?:591:58)
    at ZoneDelegate.invokeTask (webpack:///./~/zone.js/dist/zone.js?:365:38)
    at Zone.runTask (webpack:///./~/zone.js/dist/zone.js?:265:48)

**Comment by mateuszwitkowski** [comment]
You should do exactly what is said in error message:  import CUSTOM_ELEMENTS_SCHEMA in the main module (I assume that you use material elements all over your app) and add schema: [CUSTOM_ELEMENTS_SCHEMA] in ngModule metadata. According to Angular official documentation CUSTOM_ELEMENTS_SCHEMA "defines a schema that will allow any property on elements with a - in their name, which is the common rule for custom elements".

**Comment by qdouble** [comment]
@mateuszwitkowski that doesn't make any sense, you should only have to use that when using stuff like polymer. Any directives defined in angular shouldn't need custom element schema.

**Comment by qdouble** [comment]
Just checked alpha 7-10 and it works fine now. Closing.

**Comment by paceld** [comment]
I am having this problem with 8-1.
