### ISSUE TITLE
[Outlined Text Fields] label background not applied

### ISSUE THREAD

**Issue by aitboudad** [angular/material2#11437]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior? 
should apply a white background to field label

#### What is the current behavior?
I noticed when form-field is hidden during initialization, the form label doesn't appear as expected

![selection_134](https://user-images.githubusercontent.com/1753742/40325267-9e54b356-5d2a-11e8-934b-97ca36767512.png)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-1knm4t

**Comment by Dioude** [comment]
Hi,
got the same issue here. 
Not a background problem but a width on the "mat-form-field-outline-gap" element that remains at 10px.

**Comment by mmalerba** [comment]
I don't recommend toggling the `style.display` like that. `*ngIf="show"` will work the way you expect. If you can't use `*ngIf` you'll need to tell the form-field to recalculate the gap size after showing it: https://stackblitz.com/edit/angular-1knm4t-nfwh7q?file=app/form-field-overview-example.ts
