### ISSUE TITLE
Wrong color of underline for mat-form-field in error state

### ISSUE THREAD

**Issue by tofesath** [angular/material2#11436]
#### Bug, feature request, or proposal:
Wrong underline color when form field is focused and in error state.

#### What is the expected behavior?
When focus is invoked, *Form field* component is in error state and color is explicitly set by `color` attribute , underline doesn't display warn color.

#### What is the current behavior?
The accent color is not changed to warn color when focus is invoked and *Form field* component is in error state.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/angular-t85tgm

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 6.0.1, angular material 6.0.1, typescript 2.7.2

#### Is there anything else we should know?
No.

**Comment by mtrdp642** [comment]
The issue only happens when the `mat-form-field` has the `color` attribute set to `accent`. Setting it to `primary` has the underline colored as the warn color.
