### ISSUE TITLE
Material Select: poor markup rendering

### ISSUE THREAD

**Issue by atodd-geoplan** [angular/material2#11443]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
The material options for a material select should appear within the select tag

#### What is the current behavior?
The options are rendered under the body tag with an absolute position, but a zindex of only 1000.
This sent me on a wild goose chase because it appeared to me that the options were not being rendered, when in fact they were, but in an obscure place in the DOM. The options were subsequently being hidden by higher z-indexed components (the form is in an absolutely positioned overlay).

#### What are the steps to reproduce?
Create a mat select with *ngFor options in an absolutely positioned form and observe where the options are rendered.

#### What is the use-case or motivation for changing an existing behavior?
Debugging - this behaviour needs at least documenting, but really its a Web Component and should be rendered within the component's tag

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.7.3
Node: 8.10.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.5
@angular/cli: 1.7.3
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

**Comment by crisbeto** [comment]
The reason that the select panel (and all other CDK overlays) are rendered at the bottom of the body is because that's the only reliable way we can prevent them from being clipped by a parent that has `overflow: hidden`. Closing since it was working as expected.

**Comment by atodd-geoplan** [comment]
@crisbeto is this documented anywhere?

**Comment by crisbeto** [comment]
[Yes, it's under "The overlay container" in the CDK overlay docs](https://material.angular.io/cdk/overlay/overview#the-overlay-container):

> By default, the overlay container is appended directly to the document body so that an overlay is never clipped by an overflow: hidden parent.
