### ISSUE TITLE
Standard form field does not work correctly with datepicker toggle and select

### ISSUE THREAD

**Issue by CDDelta** [angular/material2#11449]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Standard form field works well with datepicker toggle and select, similar to the legacy form field.

#### What is the current behavior?
Datepicker toggle is weirdly large and the select drop-down icon is aligned incorrectly in a standard form field.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-eigucd?file=app/app.component.html

#### What is the use-case or motivation for changing an existing behavior?
-

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: 6.0.0

**Comment by gagandeepbal** [comment]
any update on this issue?

**Comment by mmalerba** [comment]
I believe this is working as intended. The latest version of the spec doesn't have the underline style at all. But the [previous version](https://material.io/archive/guidelines/components/text-fields.html) showed the dropdown arrow centered w.r.t. the label & value as a whole:

![dropdown arrow](https://material.io/archive/guidelines/assets/0B5ZSepuCX1xORDV6SjN6WEhHUlU/single1.png)

The larger calendar icon is again following the pattern shown in the previous version of the spec, which shows full-sized icons being used as the suffix:

![suffix icon](https://material.io/archive/guidelines/assets/0B5ZSepuCX1xOdEc4cHZWV3ZzTzg/password1.png)
