### ISSUE TITLE
Hacking CSS while they work on theming

### ISSUE THREAD

**Issue by ReneVallecillo** [angular/material2#1145]
Has anyone been able to hack the CSS to change color and stuff from the modules?

If so could you share some snippets?

I hope the team let this one live while they work on theming. I wan't to believe many as me want to embrace this framework, but need to change some basic styles for now.

**Comment by jelbourn** [comment]
Please use issues only for reporting bugs / feature requests. Discussions should be directed to the mailing list, gitter, etc.
