### ISSUE TITLE
Material Typography does not work if no Material component is included

### ISSUE THREAD

**Issue by ubarsaiyan** [angular/material2#11450]
#### Bug, feature request, or proposal:
Bug:
Material Typography classes like `mat-display-4` etc don't work if no Material component is imported in the app.module.ts file. There should be a material typography component to include if I just want to use Material Typography and not other components. Or if it is not possible then the Guides and Documentation should be updated regarding the same.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.3
Node: 8.11.2
OS: linux x64
Angular: 6.0.2
rxjs  6.1.0
typescript  2.7.2
webpack  4.8.3
Angular Material version 6

**Comment by crisbeto** [comment]
I don't think that we're going to create a dedicated component that only includes the typography styles. You can include the styles yourself by including the `mat-base-typography` mixin somewhere in your app.
