### ISSUE TITLE
Table: Style Not Applied To Native Table

### ISSUE THREAD

**Issue by ewaschenko** [angular/material2#11456]
#### Bug, feature request, or proposal:

Mat table styling is not applied to native table unless there exists a `mat-table` that loads the `mat-table` css

#### What is the expected behavior?

Style should be applied to table regardless if `mat-table` has been used.

#### What is the current behavior?

If `mat-table` is not used in the code, then the appropriate css is not loaded.  So, if you are styling a native table without using mat-table somewhere, then the css will not be loaded and applied.

Example:

If I have a page with a native table with the `mat-table` styling and I navigate to it, then the styling will not be applied.  But, if I then navigate to a page with a `mat-table` then navigate back, the styling will be applied to the native table since the css is loaded.

#### What are the steps to reproduce?

Open Native Table example in [Stackblitz](https://stackblitz.com/angular/empbjvyandp?file=app%2Ftable-native-only-example.ts)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6.0.1
Material 6.1.0

**Comment by ewaschenko** [comment]
See #11442

**Comment by rodrigjg** [comment]
A stupid workaround is to simply add 

`<table mat-table></table>`

Before your standard table. Since it has no elements it should not show up at all. However a better solution should be implemented for sure!
