### ISSUE TITLE
Attaching the autocomplete panel to a different element gives error

### ISSUE THREAD

**Issue by ubarsaiyan** [angular/material2#11463]
#### Bug
https://material.angular.io/components/autocomplete/overview#attaching-the-autocomplete-panel-to-a-different-element
This does not work. The following error appears
[Angular] Can't bind to 'matAutocompleteConnectedTo' since it isn't a known property of 'input'.
and [Angular] There is no directive with "exportAs" set to "matAutocompleteOrigin"

````
<mat-card class="search-box" fxLayout="row" matAutocompleteOrigin #origin="matAutocompleteOrigin">
    <input class="search-text" fxFlex type="text" placeholder="Search" autofocus [matAutocomplete]="auto" [matAutocompleteConnectedTo]="origin">
  </mat-card>

  <mat-autocomplete #auto="matAutocomplete">
    <mat-option *ngFor="let option of [0,1,2]" [value]="option">{{option}}</mat-option>
  </mat-autocomplete>
````
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.3
Node: 8.11.2
OS: linux x64
Angular: 6.0.2
Angular Material: 6.0.2

**Comment by pfeigl** [comment]
https://github.com/angular/material2/releases, see v6.1, first new feature

**Comment by crisbeto** [comment]
@pfeigl is correct. You have to update to Material 6.1 to get the new feature.
