### ISSUE TITLE
Min date later than Max date

### ISSUE THREAD

**Issue by victoriaaa234** [angular/material2#11467]
If the min date is later than the max date, then after selecting the earlier max date, the date should change to the min date and everything should be disabled in the result.

![28bkk6ffkj5](https://user-images.githubusercontent.com/15025941/40395029-f90babd2-5dda-11e8-974a-373007197722.png)

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
