### ISSUE TITLE
mat-select no detect mouse

### ISSUE THREAD

**Issue by hitokiri** [angular/material2#11469]
```
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.0
Node: 8.11.2
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0
@angular-devkit/core         0.6.0
@angular-devkit/schematics   0.6.0
@schematics/angular          0.6.0
@schematics/update           0.6.0
rxjs                         6.1.0
typescript                   2.7.2
```

`"dependencies": {
    "@angular/animations": "6.0.2",
    "@angular/cdk": "^6.0.2",
    "@angular/common": "6.0.2",
    "@angular/compiler": "6.0.2",
    "@angular/core": "6.0.2",
    "@angular/forms": "6.0.2",
    "@angular/http": "6.0.2",
    "@angular/material": "6.0.0",
    "@angular/platform-browser": "6.0.2",
    "@angular/platform-browser-dynamic": "6.0.2",
    "@angular/router": "6.0.2",`

== Bug
![no detect hover angularmaterial-recorte](https://user-images.githubusercontent.com/247528/40409844-4ff5c268-5e29-11e8-9b7d-36e9e8f4c04f.png)

the object does not respond when the mouse passes over the options
neither when clicking, but if it responds when writing and to the directionals of the keyboard

**Comment by crisbeto** [comment]
[Everything seems to work correctly in the docs](https://material.angular.io/components/select/examples). Based on your screenshot, it looks like you've made some customizations to the select. You should make sure that some of the overrides aren't messing with it.
