### ISSUE TITLE
Autocomplete class width override by '.mat-autocomplete-panel'

### ISSUE THREAD

**Issue by Smileydude** [angular/material2#11474]
Bug:
When you pass a class to the mat-autocomplete component it is placed on the injected overlay content. But the new styles added in material v6 to  '.mat-autocomplete-panel' prevent a width from being described on the autocomplete the same way as material v5.

I expect to be able to have
.custom-class {
    width: 500px;
}
change the width of the overlay, as it did in v5

Currently need to do
 .mat-autocomplete-panel.custom-class {
    width: 400px;
    min-width: 400px;
    max-width: 400px;
    overflow-x: visible;
    overflow-y: auto;
 }

**Comment by josephperrott** [comment]
This is working as intended with the inclusion of the flexible connected position strategy.  Our css styling is targeting with the least specificity possible, but will require that you use a target with higher specificity.
