### ISSUE TITLE
Toolbar elevation covered by sidenav when used together

### ISSUE THREAD

**Issue by IlCallo** [angular/material2#11488]
#### Bug, feature request, or proposal:
Toolbar elevation not show when used together with sidenav in "side" mode

#### What is the expected behavior?
Toolbar elevation should be visible even when used together with a sidenav container element, or at least over the "content" part.
It would be best if the decision to show the elevation also on the "sidenav" part is delegated to the user with a property (default to "not show").

#### What is the current behavior?
When using together a toolbar and the sidenav container element in "side" mode, the toolbar elevation is covered by the sidenav container which has a z-index greater than the toolbar has.
Currently setting sidenav-container z-index to "-1" let the elevation on the toolbar to be showed, but I guess that z-index is there for a reason and changing it will break something else.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-m4myhz

Changing z-index to "-1" on `example-container` let the toolbar elevation to be shown.

#### What is the use-case or motivation for changing an existing behavior?
In many images of Material Design guidelines, the toolbar elevarion is visible over the page content and over the sidenav in "side" mode.

https://material.io/design/components/navigation-drawer.html#standard-drawer

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Angular Material 6.1.0

**Comment by josephperrott** [comment]
The contents within the sidenav container are placed at a `z-index: 1`.  To give the appearance of the toolbar being elevated about the sidenav container you can apply a `z-index: 2` to whatever element you are using as a toolbar, in the case provided in your stackblitz `mat-toolbar`.

**Comment by IlCallo** [comment]
I searched for this info on the documentation but couldn't find it, is it possible to add a line or two to specify this requirement?
