### ISSUE TITLE
request: list of all material module imports available

### ISSUE THREAD

**Issue by AlpacasForever** [angular/material2#11480]
#### Bug, feature request, or proposal:
Please create a list of all material module imports in documentation so that we can easily create our own material modules that include all available imports.

#### What is the expected behavior?
A list of all available imports

#### What is the current behavior?
Documentation requires selection of individual components to discover API architecture.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Ease for using full set of angular material features

**Comment by josephperrott** [comment]
You should be able to see the modules that are available at our [documentation site](https://material.angular.io)
