### ISSUE TITLE
Mat Menu position 

### ISSUE THREAD

**Issue by Ashish142** [angular/material2#11491]
#### Bug, feature request, or proposal:

Bug : Mat Menu Position not working as expected 

#### What is the expected behavior?

xPosition is not working 

#### What is the current behavior?

not moving to right corner 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

https://stackblitz.com/edit/dynamic-nested-menus-6j4afw

**Comment by crisbeto** [comment]
In your example the menu won't open to the right, because there isn't enough space to fit the panel. [Here's an example](https://stackblitz.com/edit/dynamic-nested-menus-2ky78m?file=app/app.component.scss) with a bit more space on the left side which shows it working as intended.
