### ISSUE TITLE
mat-tooltip won't work ideally when attaching on a fixed element

### ISSUE THREAD

**Issue by donle** [angular/material2#11508]
#### Bug? Or feature request?:

When the page is scrolling, tooltip attaching on a fixed element will scroll down with the whole page, but the element stick to a static position.

#### What is the expected behavior?

The tooltip should be close to attached element.

#### What is the current behavior?

Tooltip scroll with the whole page.

#### What are the steps to reproduce?

1. Hover on the icon in demo page
2. Scroll down the window, then you will see the issue

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

-   Angular: 6.0.x
-   Material: 6+
-   OS: Windows 10
-   Browser: Chrome 

#### Is there anything else we should know?

[Demo page here](https://stackblitz.com/edit/angular-cweyea)

**Comment by crisbeto** [comment]
This is the same issue as https://github.com/angular/material2/issues/11365. Closing as a duplicate.
