### ISSUE TITLE
Agm map is not working

### ISSUE THREAD

**Issue by VelAnand** [angular/material2#11509]
ngOnInit() {
    return this.dashservice.getdashitem().subscribe(Response => {
      this.httpdata = Response;
      console.log(this.httpdata)
    })
  }

===============================

##<div class="row my-4">
  ##<div class="col-lg-8">
    ##
    ##<agm-map [latitude]="lat" [longitude]="lng" [zoom]="zoom" [zoomControl]="false" (mapClick)="mapClicked($event)">
      ##<agm-marker 
        *ngFor ="let map of httpdata; let i = index"
        (markerClick)="clickedMarker(map, i)"
        [latitude]="map.address.geo.lat" 
        [longitude]="map.address.geo.lng">
     ## </agm-marker>
    ##</agm-map>
 ## </div>
  
  <div class="col-lg-4">
    <app-bn-tagline></app-bn-tagline>
   <div *ngFor ="let map of httpdata; let i = index">
      <label>{{map.address.geo.lat}}</label>
      <label>{{map.address.geo.lng}}</label>
   </div>
  </div>
  <!-- /.col-md-4 -

**Comment by crisbeto** [comment]
Closing since `agm-map` isn't a component from this repo.
