### ISSUE TITLE
Guard MdIconModule if not called .forRoot()

### ISSUE THREAD

**Issue by mhevery** [angular/material2#1150]
Currently it is easy to forget to call `MdIconModule.forRoot()` Could we throw an error like we do in Router: https://github.com/angular/angular/blob/master/modules/@angular/router/src/router_module.ts#L123

**Comment by DevVersion** [comment]
This should be fixed with SHA https://github.com/angular/material2/commit/b49bfce5a9796441314bd2eed93e26e47a48e9ca
