### ISSUE TITLE
Help: How to remove extra space under matInput

### ISSUE THREAD

**Issue by iamimbohacker** [angular/material2#11515]
#### Bug, feature request, or proposal:
How to remove annoying space for errors in mat-input-field

#### What is the expected behavior?
Space for errors in mat-form-field removed

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/38751759/40553612-e5580ffe-604b-11e8-976e-bfb0c9d9de36.png)

**Comment by crisbeto** [comment]
This isn't something that we support. You should be able to remove it yourself with some CSS overrides, but at that point it's up to you to make sure that everything is still aligned.
