### ISSUE TITLE
Reduced reusability because of MatDialogRef's requriments?

### ISSUE THREAD

**Issue by FDN73** [angular/material2#11512]
Proposal.
Suppose I have a component I want to reuse in different other components to be opened as a dialog.
MatDialogRef's current requirement to pass the "opener" component's type does not allow such use case.
If not using MatDialogRef, it have to be the openers's responsibility to close the dialog, forcing some kind of communication between the two components.
**It would be nice to be able to instantiate a MatDialogRef derivative which requires no opener type, and just allows to close the dialog.**
This is useful in frameworks like NGRX: I just issue a new action from my dialog and I just want it to close itself, the dialog opener does not need to know anything, as it can watch the application's state.

**Comment by andresbm05** [comment]
I think youre wrong, to instantiate the dialog ref you dont need the opener component you should use the component itself, i mean if your dialog component is `DialogComponent` you should instantiate dialog ref like this: `public dialogRef: MatDialogRef<DialogComponent>` in the constructor. You can see an example [here](https://stackblitz.com/angular/apxpdjpdblx?file=app%2Fdialog-overview-example.ts).</br></br>
The only thing a bit anoying is that you need to add the dialog component as an entry component, but if you have a shared module you can add it there and thats it, you can use that dialog anywhere

**Comment by pfeigl** [comment]
I don't also understand the request:
* use `MatDialogClose` button component to close the dialog from within the dialog
* use `MatDialogRef.close()` to close the dialog from outside (i.e. the opener) or inside (the dialog itself)
* use `MatDialog.closeAll()` to close all dialogs without a MatDialogRef

Also for opnening a dialog, all you do is `MatDialog.open(YourDialog)` which does not require the opener at all and returns the `MatDialogRef`.

This should give you all possible options to close the dialog from either outside or inside the dialog without ever having a strict dependency between the opener and the dialog.

**Comment by pfeigl** [comment]
The overview: https://material.angular.io/components/dialog/overview#dialog-content
The API: https://material.angular.io/components/dialog/api#MatDialogClose

Anyways, you're welcome! Guess you can than close this ticket, when you have everything you need.
