### ISSUE TITLE
Angular 2 material strange core errors (gesture) when build

### ISSUE THREAD

**Issue by theunreal** [angular/material2#1151]
#### Bug, feature request, or proposal:

Bug

![image](https://cloud.githubusercontent.com/assets/6171883/18164825/adcc8e2c-704a-11e6-856c-c72e1bebcc53.png)

Everything is installed exactly as documented

**Comment by spock123** [comment]
ComponentResolver is deprecated in RC6
Use ComponentFactoryResolver instead.

I'm pretty sure we'll see a new Material2-build any time, fixing this...

**Comment by christiandreher** [comment]
I also encountered this error. Hope this gets fixed quickly, I really don't want to revert angular again :/

**Comment by spock123** [comment]
These are the errors I've found so far:
According to the Ng2 changelog (https://github.com/angular/angular/blob/master/CHANGELOG.md):

> Type is now Type<T> which means that in most cases you have to use Type<any> in place of Type.

`@angular2-material/button/button.d.ts:34:44 Generic type 'Type<T>' requires 1 type argument(s).
`

> core: deprecated ComponentResolver was removed. Please use ComponentFactoryResolver instead.

```
`@angular2-material/core/overlay/overlay.d.ts:1:10  Module '"/project/node_modules/@angular/core/index"' has no exported member 'ComponentResolver'.

@angular2-material/core/portal/dom-portal-host.d.ts:1:10 Module '"/project/node_modules/@angular/core/index"' has no exported member 'ComponentResolver'.

@angular2-material/core/portal/portal-directives.d.ts:1:37 
    Module '"/project/node_modules/@angular/core/index"' has no exported member 'ComponentResolver'.

`
```

**Comment by christiandreher** [comment]
Updating `@angular2-material/*` from `2.0.0-alpha.7-4` to `2.0.0-alpha.7-12` fixes *this* problem, but re-introduces the `moduleid` bug, because it was added again with !1101

**Comment by spock123** [comment]
@christiandreher Yeah, module.id breaks webpack builds.. 👎

**Comment by orangesoup** [comment]
Yeah, getting `moduleId` out makes it "work" until you get another error: `No provider for Overlay!`. I added `PortalModule` and `OverlayModule`, yet for some reason it doesn't work.

**Comment by fxck** [comment]
You can use named `NamedModulesPlugin` to get rid of that `module.id` errors. As for `No provider for Overlay!` I got rid of it as soon as I used `MdMenuModule.forRoot()` on my root module. [Here's](https://github.com/angular/material2/blob/9ff619669ae4e16409772b96e9f8d98f8477a3e0/src/lib/all/all.ts#L73) a list of components that needs to be included in your root module.

**Comment by spock123** [comment]
@fxck Thanks, couldn't remember the plugin name. Will give it a shot...

**Comment by christiandreher** [comment]
As a `angular-cli` user, I'm afraid that I can't configure webpack... Hope that this will be fixed very soon...

**Comment by jelbourn** [comment]
I believe this issue is obsolete now.

**Comment by christiandreher** [comment]
it is indeed

**Comment by gilad-vatbox** [comment]
Using angular 2.2.3 I'm still getting this error in build time.
Tried adding OVERLAY_PROVIDERS to the providers with no change.
