### ISSUE TITLE
Errors after update to angular 6

### ISSUE THREAD

**Issue by Gnorro** [angular/material2#11532]
### Do you want to request a *feature* or report a *bug*?
BUG

#### Bug Report
Followed this guide https://update.angular.io/ to update from 4.3 to 6 
When runnning ng serve i get lot of errors. For example:
error TS2305: Module '"D:/xxx/node_modules/@angular/material/material"' has no exported member 'MdIconRegistry'.

error TS2305: Module '"D:/xxx/node_modules/@angular/material/material"' has no exported member 'MaterialModule'.

and so on...

#### What is the expected behavior?
No errors

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Angular CLI: 6.0.5
Node: 8.11.2
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.5
@angular-devkit/build-angular     0.6.5
@angular-devkit/build-optimizer   0.6.5
@angular-devkit/core              0.6.5
@angular-devkit/schematics        0.6.5
@angular/cdk                      6.1.0
@angular/cli                      6.0.5
@angular/material                 6.1.0
@ngtools/webpack                  6.0.5
@schematics/angular               0.6.5
@schematics/update                0.6.5
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

##### Other information
My package.json:

`{
  "name": "xxxx",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.3",
    "@agm/js-marker-clusterer": "^1.0.0-beta.3",
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^6.1.0",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.1.0",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/platform-server": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@covalent/core": "^1.0.0",
    "@satispay/web-button-factory": "1.2.1",
    "@types/angular": "1.6.28",
    "@types/node": "6.0.88",
    "angular4-social-login": "1.1.1",
    "braintree-web": "3.22.2",
    "braintree-web-drop-in": "1.8.0",
    "classlist.js": "1.1.20150312",
    "core-js": "2.4.1",
    "enhanced-resolve": "3.3.0",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "intl": "1.2.5",
    "js-marker-clusterer": "1.0.0",
    "lory.js": "2.3.3",
    "md5": "2.2.1",
    "moment": "^2.22.1",
    "ng2-cookies": "1.0.12",
    "ng2-responsive": "0.8.4",
    "ng2-scroll-to-el": "1.0.0",
    "ngx-gallery": "4.1.2",
    "ngx-zendesk-webwidget": "0.1.2",
    "paypal-checkout": "4.0.133",
    "rxjs": "^6.2.0",
    "sass-loader": "6.0.6",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.5",
    "@angular/cli": "^6.0.5",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "6.0.3",
    "@types/jasmine": "2.5.45",
    "@types/node": "6.0.88",
    "codelyzer": "3.0.1",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "^2.0.2",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "ngx-swiper-wrapper": "4.6.0",
    "protractor": "^5.3.2",
    "ts-node": "3.0.6",
    "tslint": "5.3.2",
    "typescript": "^2.7.2",
    "webpack": "^4.8.3"
  }
}
`

**Comment by Chan4077** [comment]
Can you try running the update schematic?

```bash
ng update @angular/material
```

**Comment by Gnorro** [comment]
Thanks for your reply.

Done. But same error

**Comment by CDDelta** [comment]
`MaterialModule` was removed many versions ago and the MD prefix was dropped in favour of Mat. You will have to go through the chanelog for breaking changes and update your app manually.

**Comment by josephperrott** [comment]
The assisted upgrades you referenced, for Material, are only able to assist in upgrading from `5.x` -> `6`.  You will need to update to Material v`5` before using the tool.

**Comment by Gnorro** [comment]
thanks
