### ISSUE TITLE
Update to RC6

### ISSUE THREAD

**Issue by kgiroux** [angular/material2#1153]
#### Bug, feature request, or proposal:
Update to RC6
There is a lot of error with the new RC 6 of angular.  Concret type was merge with Type,  HammerManager is not found

#### What is the expected behavior?
Material2/Core

#### What are the steps to reproduce?
Just use Material 2 with a RC6 Application
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by fxck** [comment]
you can use `2.0.0-alpha.7-12` or want for https://github.com/angular/material2/pull/1149

**Comment by christiandreher** [comment]
Which, by the way, doesn't work when you're using `angular-cli@webpack`

**Comment by kara** [comment]
Closing, as this work is complete in master and will be released with alpha.8.

**Comment by antonyRoberts** [comment]
@kara Don't mean to be a bother, but is alpha.8 coming out today?

**Comment by kara** [comment]
@antonyRoberts Came out today!  :)

**Comment by nadavten** [comment]
still doesnt work

**Comment by kara** [comment]
@nadavten  Can you be a bit more specific? What problem are you having?

**Comment by nadavten** [comment]
rc6 alpha.8.1 ... unable to build with typescript in visual studio 2015.
lots of errors
![image](https://cloud.githubusercontent.com/assets/17804204/18290619/e055ed20-748c-11e6-8566-f1bd42cec1ba.png)

**Comment by gyscos** [comment]
@nadavten This looks like you need to update typescript to 2.0.0.
