### ISSUE TITLE
Excel like 

### ISSUE THREAD

**Issue by mmteyrek** [angular/material2#11553]
Hello,
I'm building a view using grid list material, this view should be closed to an Excel like.
So I want is to be able to change the width of my cells without changing the height and to be able to display a horizontal scroll.
currently if i have a lot of cells, the view adjust automatically the cells to fit in the page?
Any idea.
Exemple 
https://stackblitz.com/edit/angular-bcauqv?file=app%2Fgrid-list-dynamic-example.ts

**Comment by CDDelta** [comment]
I think you would get better results with tables instead of grid list, check it out, but please close this issue and ask questions on the Google group or Gitter.
