### ISSUE TITLE
Material 2 doesn't seem to be compatible with Angular 2 RC 6

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#1156]
I recently tried upgrading my project to Angular 2 RC 6 but it seems that Material 2 isn't compatible with RC 6.

When I try to compile my project with RC 6, I receive the below error:

`Error		Build:Module '"node_modules/@angular/core/index"' has no exported member 'ComponentResolver'.	node_modules\@angular2-material\core\portal\portal-directives.d.ts`

As per the change log (https://github.com/angular/angular/blob/master/CHANGELOG.md)
ComponentResolver has been depreciated. But since the portal directives uses ComponentResolver , the compiler throws the error.

As per the link https://github.com/angular/angular/commit/73a9ee4 we need to use ComponentFactoryResolver

**Comment by m0t0r** [comment]
@naveedahmed1 see #1153

**Comment by naveedahmed1** [comment]
@m0t0r I upgraded to 2.0.0-alpha.7-12 but now I am receiving below error:

`node_modules/@angular2-material/checkbox/checkbox.d.ts(48,14): error TS1005: '=' expected.`

**Comment by m0t0r** [comment]
@naveedahmed1 I think you need to wait for alpha.8. [portal-directives.ts](https://github.com/angular/material2/blob/master/src/lib/core/portal/portal-directives.ts) on master doesn't  use deprecated `ComponentResolver`. There is #1154 for the upcoming release.

**Comment by naveedahmed1** [comment]
I was actually able to compile and run the project after I upgraded Material 2.0.0-alpha.7-12 and upgraded TypeScript to version 2.0.2 Beta

**Comment by kara** [comment]
Using the latest release should resolve this issue, so closing :)
