### ISSUE TITLE
5.2.x is missing `@angular/cdk/testing`

### ISSUE THREAD

**Issue by dherges** [angular/material2#11575]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

```ts
import { dispatchTouchEvent } from '@angular/cdk/testing';
```

#### What is the current behavior?

https://github.com/angular/material2/tree/5.2.x/src/cdk/testing

#### What are the steps to reproduce?

see above

#### Is there anything else we should know?

I think the `BUILD.bazel` is missing. Would you release a bugfix 5.2.x version? I'll send you a PR!

**Comment by crisbeto** [comment]
`cdk/testing` isn't part of our public API, see https://github.com/angular/material2/issues/9531#issuecomment-359969115.
