### ISSUE TITLE
Menu below and above

### ISSUE THREAD

**Issue by teterovic** [angular/material2#11597]
#### Bug, feature request, or proposal:
The class names .mat-menu-below and .mat-menu-above are gone

#### What is the expected behavior?
The css names should be added to menus when positioned below/above

#### What is the current behavior?
Donesn't work anymore sine update to AM 6.1.0

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.0
Angular material 6.1.0

#### Is there anything else we should know?
See the previous working example how it works with .mat-menu-below and .mat-menu-above when the screen is too small the menu adds a class .mat-menu-above, but since the last version it's gone:

![image](https://user-images.githubusercontent.com/7413906/40776489-27721f5a-64cb-11e8-8403-f2a3ec2aebb4.png)

**Comment by crisbeto** [comment]
We used those classes to set the appropriate `transform-origin` depending on the menu's position, but we recently added an API to the CDK which does it automatically which is why we removed them. @jelbourn should we consider them a part of the public API now?

**Comment by jelbourn** [comment]
@teterovic what did you use the classes for?

**Comment by teterovic** [comment]
![image](https://user-images.githubusercontent.com/7413906/40803611-5635cd5c-6519-11e8-991e-68c962bfded1.png)


![image](https://user-images.githubusercontent.com/7413906/40803620-5e7a8dd6-6519-11e8-9961-d17494a6e50b.png)

**Comment by jelbourn** [comment]
@crisbeto I could see adding them back for people to do stuff like that

**Comment by teterovic** [comment]
Its also useful to add padding/margin based on the the trigger for the menu depending if the menu is below or above. 
A lot of devs forget this case when using the library - the element can be placed at the bottom when scrolling.
