### ISSUE TITLE
[cdk dialog] DialogConfig.containerClass is not used

### ISSUE THREAD

**Issue by jpzwarte** [angular/material2#11591]
The config option ```containerClass``` is unused in the code, resulting in the dialog continainer element *not* having the specified classes. Code along the lines below is required in the dialog-container.ts:

```
  @HostBinding('class')
  get _class() {
    const classes = this._config.containerClass;

    return Array.isArray(classes) ? classes.join(' ') : classes;
  }
```

**Comment by crisbeto** [comment]
Submitted #11593 to remove the property. If you want to add some custom styling based on a class, you can set the `panelClass` and target the child `cdk-dialog-container`:

```css
.custom-panel-class cdk-dialog-container {
  color: red;
}
```
