### ISSUE TITLE
Weird matTooltip behavior when assigned to a button inside a menu

### ISSUE THREAD

**Issue by divStar** [angular/material2#11600]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tooltip shows only when mouse is over the according button.

#### What is the current behavior?
Under certain circumstances the tooltip of a button shows at a more-or-less-random position.

![angular-material2-mattooltip-bug-screenshot](https://user-images.githubusercontent.com/138585/40780115-9c30c2c2-64d7-11e8-9a34-4b6c222c83b5.jpg)
The first tooltip only disappears when hovering the button it originally was intended to for. When hovering over it again, the tooltip shows at the correct position.

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/edit/angular-inhkax (I removed `mat-toolbar` and `mat-toolbar-row`, because they do not seem to matter in this bug)
StackBlitz for the workaround (from a SO-user): https://stackblitz.com/edit/angular-2bulfx

Basically following steps are necessary:
1. Create a button A
2. Create a menu, which opens when button A is clicked
3. Create another button B inside the menu with "mat-menu-item"
4. Set tooltip for button B
-> tooltip appears somewhere next to the button A on click

#### What is the use-case or motivation for changing an existing behavior?
A tooltip of a button should **only** appear when the mouse (or perhaps keyboard) is somewhere inside the bounding boxes of that button.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I am using one of the most recent versions of Angular 6 (please have a look at the dependencies inside the StackBlitz as I cannot copy from there).
Browser-wise I have tried Firefox 61.0b9 (64-Bit), Edge, Chrome (cannot find out the version). The bug happens on every browser.

#### Is there anything else we should know?
I thought I might be doing something wrong, which is why I first asked a question on SO: https://stackoverflow.com/questions/50594537/weird-mattooltip-behavior-with-toolbar-button-and-nested-button. Apparently it is a bug, but there is a workaround, which seems to work.

Also: this bug seems to not have anything to do with the button responsible for opening the menu. However: only buttons with the `mat-menu-item`-directive are affected, meaning that if you use buttons with `mat-button`-directive instead, there is no misplaced tooltip when opening the menu.

**Comment by crisbeto** [comment]
The tooltip opens, because the button receives focus once the menu is opened. Yesterday we merged in a fix for the tooltip (https://github.com/angular/material2/commit/74f4364979f25a22e9dafee9c5b514551fbcc4ef) which makes it open only for keyboard focus and which should resolve your issue.

**Comment by divStar** [comment]
Somehow I am not able to test it yet (perhaps I cannot find the correct version? I have updated to angular/cdk@6.2.0 and angular/material@6.2.0).

However: I would like the tooltip appear on mouse over, too, because that's default behavior for desktop applications (I agree with it not displaying on touch perhaps, but on mouse over? that's what tooltips were for in my opinion). Then again I can probably make them show / hide manually on trigger so it should not be a big deal, but it indeed would fix my problem from what I see. Not sure how to test it though...

**Comment by crisbeto** [comment]
The change was merged yesterday, it should be in the release.

**Comment by divStar** [comment]
Alright. Thanks. Guess I'll wait a bit longer, because https://www.npmjs.com/package/@angular/material says that the last push was 2 days ago, so it'll probably be in the next update there.

Thanks. Once I found out how, I'll test it, but you're most likely right.

**Comment by crisbeto** [comment]
I'll close the issue since I'm fairly certain it'll work and to avoid it getting too stale. Ping me here, if it's still there after the next release, and I'll reopen it.
