### ISSUE TITLE
disableOptionCentering on mat-select, simply doesn't work.

### ISSUE THREAD

**Issue by ananbetak** [angular/material2#11605]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by ananbetak** [comment]
Anybody Can Explain ?!?!?

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
