### ISSUE TITLE
MdCheckBox problem with ngModel and Json

### ISSUE THREAD

**Issue by maryamsoprano** [angular/material2#1160]
Hi,

I have implemented a custom checkbox by md-checkBox directive. I want to have possibility to pass an array of json or just one row json into this component. and my component would create specified checkbox with json values.I follow steps mentioned below:
a) defining input attributes, for identifying which field should be label and which field should be value, and also what can be true/false values,for example developer can define 'y' as true false and '0' as false value. 

```
@Input() labelKey: string = "name";
@Input() valueKey: string = "value";
@Input() trueValue: any = true;
@Input() falseValue: any = false;
```

b) This is my custom checkbox.html which used input values:

  <div [ngSwitch]="items.length > 0">
   <div *ngSwitchCase="true">
      <div *ngFor="let item of  items">
            <md-checkbox
                 [checked]= "item[valueKey] == trueValue"
                 [disabled]="disabled"
                 align="start"
                 (change)="onChange($event,item,valueKey)"
                 (onInputFocus)="onFocus()">
                 {{item[labelKey]}}
         </md-checkbox>
      </div>
   </div>
     <div *ngSwitchCase="false">

```
    <md-checkbox
             [checked]= "items[valueKey] == trueValue"
             [disabled]="disabled"
             align="start"
             (change)="onChange($event,items,valueKey)"
             (onInputFocus)="onFocus()">
      {{items[labelKey]}}
   </md-checkbox>
 </div>
```

 </div>

c) from my form I use this component:
     <sei-checkbox [(ngModel)]="selected.sex" [items]="chkItems" [disabled]="!editMode"    
                  labelKey="name" valueKey="isFemail" trueValue="10"
                  falseValue="20"  sid="Gender"></sei-checkbox>

which chkItems is a json:

  public chkItems =
    { 'name': 'FEMAIL', 'sex': 10 };

My question is how can bind Json's sex field to [(ngModel)]?

thanks

**Comment by maryamsoprano** [comment]
I need your urgent help. 
I found that md-checkBox works  with [(ngModel)] or [checked] property.(Not both of them)
In my sample I wanna have checked checkbox when data field value is 10 otherwise it should be unchecked,
So , When I bind it into database field by ngModel, md-checkbox would be  checked by both 10 and 20 values , and become unchecked by 0 value. 
in the other hand when I use checked property, it is not bind to database field.

please help me in this issue, is ther any way to solve it?
thanks in advance.

**Comment by jelbourn** [comment]
I can't quite follow what your issue is, but I think it may be the same root cause as #831.

If not, please open a new issue that follows the issue template.
