### ISSUE TITLE
(bug): Snackbar Not Rendering Change From interval

### ISSUE THREAD

**Issue by ewaschenko** [angular/material2#11606]
#### Bug, feature request, or proposal:

Change Detection Bug: Changes made to a component variable inside an `RxJS interval` function are not being updated in the template.  The console log shows the variable changing yet the template does not receive the new value.

#### What is the expected behavior?

Any changes made inside a `setInterval `or `interval` should initiate change detection to update the template.

#### What is the current behavior?

Changes made to component variables inside a `setInterval `or `interval` are not updated in the template.  If the same code is copied to a regular component, then it works fine.

#### What are the steps to reproduce?

[https://stackblitz.com/edit/angular-cym4xv](https://stackblitz.com/edit/angular-cym4xv)

Make sure the console is open.  
Click Show snack-bar then Click Run Interval **once**.  In the console you will see the value of name changing but the new value is not rendered to the snack-bar.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.0.3
Material: 6.2.0
RxJS: 6.2.0

**EDIT**: Running `ChangeDetectorRef.markForCheck()` fixes the issue, but why is it required in the snack-bar but not in a regular component? Is the change detector is detached from the view?  are we outside the Angular Zone?

**Comment by crisbeto** [comment]
It's probably because the `MatSnackBarContainer` has `OnPush` change detection.

**Comment by ewaschenko** [comment]
@crisbeto Ok thanks, but with `OnPush` doesn't Angular run change detection when an `Observable` fires an event?  So if I'm using the `Observable interval` shouldn't change detection run for each emit?
