### ISSUE TITLE
[mat-input] SSR crashes because of undefined functions

### ISSUE THREAD

**Issue by arturovt** [angular/material2#11603]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`monitor` and `stopMonitoring` methods should be defined

#### What is the current behavior?
Angular universal crashes with these errors 
`TypeError: this._autofillMonitor.monitor is not a function at MatInput.ngOnInit`
`TypeError: this._autofillMonitor.stopMonitoring is not a function at MatInput.ngOnDestroy`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3

#### Is there anything else we should know?
I opened `@angular/material/bundles/material-input.umd.js`, found `ngOnInit` hook and added `console.log(typeof this._autofillMonitor.monitor);`, same with `stopMonitoring`
It printed two values - `undefined` and `function`, because this directive is instantiated twice, once on the server and on the client.

**Comment by arturovt** [comment]
@anymos Yeah, I've seen, I think it should be documented somehow

**Comment by anymos** [comment]
Agreed, wondering if it is going to be tough to fix actually in material lib

**Comment by josephperrott** [comment]
It looks like a solution for this is blocked on https://github.com/angular/angular/issues/23715
