### ISSUE TITLE
MaterialTable - Possibility to have multiple rows of a row 

### ISSUE THREAD

**Issue by IswarKChettri** [angular/material2#11615]
#### What is the expected behavior?
Declare 5 column of a row for one datasource

#### What is the use-case or motivation for changing an existing behavior?
Table with first column for details of head and other four will have value. Table should look like 
![image](https://user-images.githubusercontent.com/30075071/40836381-2e8da590-65b4-11e8-910c-55dd2f7b2b5b.png)
 My json looks like
 ```
[
  {
    majorHeadNumber: '2403',
    majorHeadDescription: 'Animal Husbandry',
    subMajorHeadDetail: [{
        subMajorHeadNumber: '00',
        subMajorHeadDescription: '',
        minorHeadDetail: [{
            minorHeadNumber: '001',
            minorHeadDescription: 'Direction and Administration',
            subMinorHeadDetail: [{
                subMinorHeadNumber: '60',
                subMinorHeadDescription: 'Administration',
                detailedHeadDetail: [{
                    detailedHeadNumber: '44',
                    detailedHeadDescription: 'Head Office Establishment',
                    objectHeadDetails: [
                    { objectHeadNumber: '01', objectHeadDescription: 'Salaries', actuals: '7327', budgetEstimate: '25664', revisedEstimate: '256891', budgetEstimateCurrentYear: '256914' },
                    { objectHeadNumber: '11', objectHeadDescription: 'Travel Expenses', actuals: '7327', budgetEstimate: '25664', revisedEstimate: '256891', budgetEstimateCurrentYear: '256914' },
                    { objectHeadNumber: '13', objectHeadDescription: 'Office Expenses', actuals: '7327', budgetEstimate: '25664', revisedEstimate: '256891', budgetEstimateCurrentYear: '256914' },
                    { objectHeadNumber: '26', objectHeadDescription: 'Advertisement and Publisity', actuals: '7327', budgetEstimate: '25664', revisedEstimate: '256891', budgetEstimateCurrentYear: '256914' },
                    ]
                }]
            }]
        }]
    }]
}];
```

#### Is there anything else we should know?
Is this posible with the current implementation in mat-table

**Comment by andrewseguin** [comment]
Yes, you can define multiple rows per data object by adding the `multiTemplateDataRows` input to the table.

https://stackblitz.com/edit/angular-9chcgm?file=app/table-basic-example.html

**Comment by umutc** [comment]
@andrewseguin Hey, index not working with multiTemplateDataRows

**Comment by WaterBleu** [comment]
> Yes, you can define multiple rows per data object by adding the `multiTemplateDataRows` input to the table.
> 
> https://stackblitz.com/edit/angular-9chcgm?file=app/table-basic-example.html

hey @andrewseguin the link you provided only reversed the order of the column doesn't demonstrate nested objects
