### ISSUE TITLE
Scrolling Issue

### ISSUE THREAD

**Issue by verikinaboina** [angular/material2#11619]
When, I'm expanding my child from parents those are not able to scroll down. Even not appearing in the bottom
1. not able to scroll when i expand the last operation.
2. not able to scroll after expansion when I've 10 or more operations.

![cap](https://user-images.githubusercontent.com/38441232/40852916-bec61a16-6591-11e8-8fff-ce8a3c3b7b98.PNG)
![captur2](https://user-images.githubusercontent.com/38441232/40852917-bed73760-6591-11e8-973f-cfafd1c4d547.PNG)

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
