### ISSUE TITLE
(Bug) double or dual Mat-table sort only works on one

### ISSUE THREAD

**Issue by tatsujb** [angular/material2#11617]
#### Bug, feature request, or proposal:

(Bug)

#### What is the expected behavior?

for sort to work on any number of mat-tables

#### What is the current behavior?

sort loads for the first table it finds and does not load for those following.

#### What are the steps to reproduce?

StackBlitz : https://stackblitz.com/edit/angular-1vg9gn-q1back?file=app/table-basic-example.ts

#### What is the use-case or motivation for changing an existing behavior?

pinnable collumns : https://stackoverflow.com/questions/49315628/mat-table-lock-or-pin-to-start-column-material-2-angular-5/

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

windows pro 10 64bit
chrome

    {
      "name": "web.ui",
      "version": "0.0.0",
      "license": "MIT",
      "scripts": {
        "ng": "ng",
        "start": "ng serve --aot",
        "build": "ng b --prod",
        "test": "ng test",
        "lint": "ng lint"
      },
      "private": true,
      "dependencies": {
        "@angular/animations": "^6.0.3",
        "@angular/cdk": "^6.1.0",
        "@angular/common": "^6.0.3",
        "@angular/compiler": "^6.0.3",
        "@angular/core": "^6.0.3",
        "@angular/forms": "^6.0.3",
        "@angular/http": "^6.0.3",
        "@angular/material": "^6.1.0",
        "@angular/platform-browser": "^6.0.3",
        "@angular/platform-browser-dynamic": "^6.0.3",
        "@angular/router": "^6.0.3",
        "@types/underscore": "^1.8.7",
        "angular-font-awesome": "^3.1.2",
        "bootstrap": "^4.0.0",
        "classlist.js": "^1.1.20150312",
        "core-js": "^2.5.3",
        "file-saver": "^1.3.8",
        "font-awesome": "^4.7.0",
        "jquery": "^3.3.1",
        "lodash": "^4.17.5",
        "ng2-ion-range-slider": "^2.0.0",
        "ngx-bootstrap": "^3.0.0",
        "ngx-dropzone-wrapper": "^6.1.0",
        "rxjs": "^6.2.0",
        "rxjs-compat": "^6.0.0-rc.0",
        "typescript": "2.7.2",
        "underscore": "^1.8.3",
        "web-animations-js": "^2.3.1",
        "zone.js": "^0.8.20"
      },
      "devDependencies": {
        "@angular-devkit/build-angular": "~0.6.5",
        "@angular/cli": "^6.0.5",
        "@angular/compiler-cli": "^6.0.3",
        "@angular/language-service": "^6.0.3",
        "@types/jasmine": "^2.8.6",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~10.1.3",
        "codelyzer": "^4.2.1",
        "postcss-modules": "^1.1.0",
        "protractor": "~5.3.0",
        "ts-node": "~6.0.5",
        "tslint": "~5.10.0"
      }
    }

**Comment by andrewseguin** [comment]
This is not a bug, the second `MatSort` is unaware of the data source and first table. If you want to get something like this set up, please try asking on StackOverflow.
