### ISSUE TITLE
zone.js?1472795395718:101 GET http://localhost:5555/node_modules/@angular2-material/package.json 404 (Not Found)

### ISSUE THREAD

**Issue by clp334264003** [angular/material2#1161]
#### Bug, feature request, or proposal:

zone.js?1472795395718:101 GET http://localhost:5555/node_modules/@angular2-material/package.json 404 (Not Found)
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by jelbourn** [comment]
This is not enough information. Please follow the issue template.
