### ISSUE TITLE
Radio button, checkbox, and progress-bar issues in high contrast mode

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#11623]
* `mat-radio-button`: it looks like you can't see the selected state
* `mat-checkbox`: can't see the selected state in "High Contrast White"
* `mat-progress-bar` looks like it doesn't show the progress and is just a solid rectangle

**Comment by crisbeto** [comment]
@jelbourn when was the radio button issue reported? We merged in https://github.com/angular/material2/pull/10753 a while ago which still seems to work.
