### ISSUE TITLE
Inline bezier curves instead of using defined constant

### ISSUE THREAD

**Issue by talamaska** [angular/material2#11626]
https://github.com/angular/material2/blob/f826805650113dcbf519084216d24dac89583412/src/lib/tooltip/tooltip-animations.ts#L25
https://github.com/angular/material2/blob/f826805650113dcbf519084216d24dac89583412/src/lib/stepper/stepper-animations.ts#L35

the curves are defined here 
https://github.com/angular/material2/blob/master/src/lib/core/animation/animation.ts
Their usage is inconsistent. I noticed different values in some components. Curves that don't correspond to material.io spec.

**Comment by andrewseguin** [comment]
Please re-open the issue to report any animations that are not matching the spec and we can review and make fixes as needed. Thanks!

**Comment by talamaska** [comment]
@andrewseguin so it's not an issue that the beziers are inline strings instead of constants?

**Comment by talamaska** [comment]
@andrewseguin 
what about those 
```
$ease-in-out-curve-function: cubic-bezier(0.35, 0, 0.25, 1) !default;

$swift-ease-out-timing-function: cubic-bezier(0.25, 0.8, 0.25, 1) !default;

$swift-ease-in-timing-function: cubic-bezier(0.55, 0, 0.55, 0.2) !default;
```
I didn't saw any of those defined somewhere in Material guidelines
