### ISSUE TITLE
Misuse of inkBar show method

### ISSUE THREAD

**Issue by talamaska** [angular/material2#11625]
https://github.com/angular/material2/blob/9f6aa843cd2f68562d3f5290688bbe5bab957bcf/src/lib/tabs/tab-nav-bar/tab-nav-bar.ts#L152
https://github.com/angular/material2/blob/9f6aa843cd2f68562d3f5290688bbe5bab957bcf/src/lib/tabs/tab-nav-bar/tab-nav-bar.ts#L153

The method alignToElement already has cal for making the inkBar visible

https://github.com/angular/material2/blob/c9777631592d941926da9bae386ef4b07aaaca4a/src/lib/tabs/ink-bar.ts#L65
https://github.com/angular/material2/blob/c9777631592d941926da9bae386ef4b07aaaca4a/src/lib/tabs/ink-bar.ts#L66
Please review.

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Comment by talamaska** [comment]
@josephperrott, I'm sorry to read that. I took time to find and point out the exact lines of the misuse of the show method. Not sure if the template is suitable for such kind of report. Please assist.
