### ISSUE TITLE
mat-bottom-sheet binding data to template 

### ISSUE THREAD

**Issue by badpaybad** [angular/material2#11627]
#### Bug, feature request, or proposal:
I use sample in https://stackblitz.com/angular/nvppaoepjnel?file=app%2Fbottom-sheet-overview-example.ts
modify a bit code

mat-bottom-sheet component
export class BottomSheetOverviewExample {
...
title='init value must change after 3 seconds';
onOnInit(){ 
   setTimeout(() => {
      this.title = "val after 3 seconds";
      console.log(this.title);
    }, 3000);
}

#### What is the expected behavior?
{{title}} in html will change after 3 seconds

#### What is the current behavior?
{{title}} no change 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/angular/nvppaoepjnel?file=app%2Fbottom-sheet-overview-example.ts
I change a bit code as image attached

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version 6, Material 2, win 10, Typescript latest, Chrome latest

#### Is there anything else we should know?
<img width="844" alt="mat-bottom-sheet" src="https://user-images.githubusercontent.com/6204507/40870499-222f06f2-665b-11e8-8b03-bbc6ba665dd6.png">

**Comment by badpaybad** [comment]
sorry i miss typing ngOnInit

**Comment by Jass91** [comment]
I have the same problem. After a HTTP request, I wish stop my spin, but I can't put it to work.

**Comment by m-spyratos** [comment]
@badpaybad I'm facing the same issue. Did you find a solution?

**Comment by m-spyratos** [comment]
@Jass91, thanks for letting me know. Seems to be a bug then. I don’t see any open issue to fix this either.

**Comment by Jass91** [comment]
:) so we can open. good luck

**Comment by badpaybad** [comment]
Here is my trick 
https://angular.io/api/core/ChangeDetectorRef

ngOnInit() {
    this.categoryTitle = this.data.categoryTitle;

    this.homePageService.getProductsInMenu(this.data.categoryId).subscribe((products) => {
      this.products = products;
      this.changeDetectorRef.markForCheck();
    });
  }

**Comment by gizmodus** [comment]
Same issue here. @badpaybad's workaround works for me as well.

**Comment by AdrienCasta** [comment]
`this.changeDetectorRef.detectChanges();` as workaround worked for me.

**Comment by dfloresgonz** [comment]
@badpaybad thanks a lot!! your solution worked! I'd to know if they will fix this so we don't have to manually update de ui.
