### ISSUE TITLE
virtual scroll: sticky header/footer

### ISSUE THREAD

**Issue by amcdnl** [angular/material2#11621]
## Requirement
We need the ability to make things sticky within the virtual scroll area. This directly relates to sticky header/footer/rows in the table.

## API
An idea for the API would be to expose a new content projection area like:

```html
  <cdk-virtual-scroll-viewport [itemSize]="35">
    <cdk-virtual-scroll-sticky position="start">
      MY HEADER
    </cdk-virtual-scroll-sticky>
    <div *cdkVirtualFor="let row of rows$ | async">
    </div>
    <cdk-virtual-scroll-sticky position="end">
      MY FOOTER
    </cdk-virtual-scroll-sticky>
</cdk-virtual-scroll-viewport>
```

Then we could set position sticky to those sticky projections. One issue with this approach is how do we tell the `cdk-virtual-scroll-content-wrapper` to accommodate the offset of the header/footer?

**Comment by amcdnl** [comment]
//cc @mmalerba @andrewseguin

**Comment by amcdnl** [comment]
After thinking about this, I think we should go w/ a different approach for the table thus making this not applicable.

**Comment by rutsche** [comment]
any news on this?

**Comment by Hotalenw** [comment]
@amcdnl Same question as @ahmadakra above? The <thead> needs to remain sticky.

**Comment by gurshinder78** [comment]
Any update? This is must requirement for data with large data set as user lost focus while scrolling and difficult to identify column

**Comment by panthera** [comment]
apply virtual scroll to body gonna inject a div inside the tbody, which gonna make start a style battle

**Comment by rahulbhooteshwar** [comment]
@shashankinbab   I am facing the same issue . Is there any update on the same ?
