### ISSUE TITLE
ng build --prod ... Can't resolve ... index.ngfactory'

### ISSUE THREAD

**Issue by halcaponey** [angular/material2#11634]
#### What is the expected behavior?
'ng build --prod' build successfully

#### What is the current behavior?
'ng build --prod' output : 

ERROR in ./src/app/components/home/home.component.ngfactory.js

Module not found: Error: Can't resolve '../../../../node_modules/@angular/material/datepicker/typings/index.ngfactory' in 'C:\dev\repro-modulenotfound\src\app\components\home'

ERROR in ./src/app/app.module.ngfactory.js

Module not found: Error: Can't resolve '../../node_modules/@angular/material/datepicker/typings/index.ngfactory' in 'C:\dev\repro-modulenotfound\src\app'

ERROR in ./src/app/app.module.ngfactory.js

Module not found: Error: Can't resolve '../../node_modules/@angular/material/dialog/typings/index.ngfactory' in 'C:\dev\repro-modulenotfound\src\app'

#### What are the steps to reproduce?
[github repo](https://github.com/halcaponey/repro-modulenotfound)

npm install

npm run build

#### What is the use-case or motivation for changing an existing behavior?
...

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
see [package.json](https://github.com/halcaponey/repro-modulenotfound/blob/master/package.json)

#### Is there anything else we should know?
tested on :

windows 10

node -v v8.11.2

npm -v 6.1.0

debian

node -v v8.11.2

npm -v 6.1.0

**Comment by Chan4077** [comment]
For me, it seems that removing the `rootDir` property of `tsconfig.app.json` solved the issue.

See this commit for more info: https://github.com/Chan4077/ngx-ytd-api/commit/5b1970cb090fc097e6bf748981d5c650958155ad

**Comment by halcaponey** [comment]
Thanks a lot, that solved the issue.

**Comment by AlQuraian** [comment]
I get this issue on serve ever now and then. If I rerun the app it goes away!
