### ISSUE TITLE
Material Tabs - Component displayed differently 1st vs 2nd tab

### ISSUE THREAD

**Issue by patricknee** [angular/material2#11639]
#### Bug, feature request, or proposal:
Component embedding CodeMirror included in the first tab displays correctly. 

Same component included in second (or greater, I think) tab has code lines displayed incorrectly, shifting the text to the left and hiding some characters. Working example:

https://stackblitz.com/edit/angular-ry1cjx

Inclusion of *ngIf="selectedTabIndex == 1" in the second tab was necessary to correctly repaint upon activation. 

Looking for a workaround solution (I only need to display this on the second tab), but the difference in display is presumably a bug.

#### What is the expected behavior?

All components should have identical display regardless of tab number.

#### What is the current behavior?
Identical component is displaying differently on tab 1, vs. subsequent tabs.

In the provided example, CodeMirror text is shifted left on tab 2. 
Inside the CodeMirror text field on Tab 1, class "CodeMirror-sizer" has "margin-left: 45px;". 

On Tab 2 the same class has "margin-left:0px".

This may manifestiitself on few components, but it seems that it surfaces a bug.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>

https://stackblitz.com/edit/angular-ry1cjx

Note that the code on tabs 2&3 has zero left margin, resulting in code behind the line numbers.

#### What is the use-case or motivation for changing an existing behavior?

Trying to include CodeMirror component on Tab 2.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6, material 6, Mac 10.13.4, "typescript": "~2.7.2"
Seen in Chrome, Safari.

**Comment by julianobrasil** [comment]
As a workaround, you can try this aproach:

```html
<mat-tab label="Tab 2">
  <ng-template matTabContent>
    test tab 2
    <code-mirror></code-mirror>
  </ng-template>
</mat-tab>
```

The drawback is that if you need to keep state between tabs switch, you'll have to do it by yourself as Tab 2 will be created again every time you switch back and forth between it and the other tabs.

**Comment by josephperrott** [comment]
For components that requiring being in the DOM to define their initial state, you will need to lazy load the tabs as noted above.

[Here](https://stackblitz.com/edit/angular-cvn1g3?file=src/app/test-tabs/test-tabs.component.html) is a working fork of your stackblitz, though as noted above, you will need to manage the state as the tab is recreated for each usage.
