### ISSUE TITLE
Plunker examples don't work

### ISSUE THREAD

**Issue by beyondJohn** [angular/material2#11631]
#### Bug, feature request, or proposal:
For a while iv'e been frustrated when looking for solutions to issues and finding solutions with references to plnkr.com examples that didn't work, the examples in plnkr.com would just display "loading..." and would not load. I thought it was strange people would post examples for code that didn't work. But today when I went to view a solution I posted to my Plunker account I experienced the same "loading..." issue. Now my Plunks aren't working too. Now I'm thinking the solutions I have viewed in the past may have actually been valid solutions!!!

#### What is the expected behavior?
Plunks should work.

#### What is the current behavior?
Plunks don't work.

#### What are the steps to reproduce?
Go to https://plnkr.co/edit/GTH4Wu?p=preview
This is working code which, unedited, has stopped working on Plunker.

#### What is the use-case or motivation for changing an existing behavior?
I will no longer use Plunker as it doesn't work.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm guessing "latest' from reviewing the plunker config.js file.

#### Is there anything else we should know?
I think the config file may be breaking the app due to grabbing the latest version instead of setting the version to the actual version used when build/posting the app.

**Comment by andrewseguin** [comment]
We've moved on to using StackBlitz since it does a much better job of version stability so that examples do not break. Plunker always had this issue unfortunately and made it very difficult to recreate old examples. Not much we can do here, sorry
