### ISSUE TITLE
opened property on MdSideNav should be set to public for use with AOT?

### ISSUE THREAD

**Issue by qdouble** [angular/material2#1163]
I want the sidenav to be open by default, previously, I set it like this:
```
<md-sidenav #sidenav opened="true" mode="side">
```
However, if I try to set it like that while using AOT, I'll get the following compile error

>Error: Error at /Users/qdouble/Sites/Pending deletion/builds-test/src/compiled/src/a
pp/app.ngfactory.ts:404:27: Property '_opened' is private and only accessible within
 class 'MdSidenav'.  

If I try to use ViewChild to open with `this.sidenav.open()` AfterContentInit, If I don't use setTimeout to trigger the open, it will give me a promise error when I close it
> error_handler.js:52 Error: Uncaught (in promise): undefined
    at resolvePromise (zone.js:558)
    at MdSidenav.eval [as _openPromiseReject] (zone.js:535)
    at MdSidenav._onTransitionEnd (sidenav.js:154)
    at DebugAppView._View_App0._handle_transitionend_2_0 (App.ngfactory.js:389)
    at eval (view.js:425)
    at eval (dom_renderer.js:259)
    at eval (dom_events.js:30)
    at ZoneDelegate.invoke (zone.js:332)
    at Object.onInvoke (ng_zone_impl.js:41)
    at ZoneDelegate.invoke (zone.js:331)
 
Once you use setTimeout to open it, then you have to deal with the flicker of it opening when you first enter the page

**Comment by RoxKilly** [comment]
The `opened` property is set to public. It is `_opened` that is private. Don't know why AoT compiler `ngc` tries to access the latter.

**Comment by RoxKilly** [comment]
I suggest closing this because this bug doesn't apply to `alpha 9-3`

**Comment by omararturo** [comment]
Hi,
This is the temporal solution:
```
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { MeteorComponent } from 'angular2-meteor';
import { MdSidenav } from '@angular/material';

import template from './app.component.html';

@Component({
    selector: 'app',
    template
})
export class AppComponent extends MeteorComponent implements OnInit {

    @ViewChild('sidenavLeft') sidenavLeft: MdSidenav;
	
	constructor(
    ) {	
		super();
    }

    ngOnInit(): void {
		this.sidenavLeft._onTransitionEnd = function () {            
            this._openPromise = null;
            this._closePromise = null;
        }
	}
}
```

I hope it will be helpful to you.
