### ISSUE TITLE
https://material.angular.io/ is not accessible on Firefox and Chrome sometimes

### ISSUE THREAD

**Issue by anurag-arora** [angular/material2#11643]
This website is not accessible in Firefox developer or normal edition, it is showing a **blank page**. And in the network tab, there are too many requests are going on in an infinite loop.

**Comment by renatuzz** [comment]
Same to me.

**Comment by jhnoor** [comment]
cmd + shift + r worked for me, but I wonder if this is because of index.html containing outdated references to .js files? Pointing to wrong hashed filenames?

**Comment by jelbourn** [comment]
I sent https://github.com/angular/material.angular.io/pull/464 to add a cache expiration header to try to alleviate this.
