### ISSUE TITLE
mat-select's options do not align with mat-select when it is populated

### ISSUE THREAD

**Issue by armando1793** [angular/material2#11640]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
~~When there are changes to the component's template, mat-select's options should still be aligned with the parent mat-select~~

edit: When mat-select is populated, the options immediately become misaligned. I'm not sure if this is intended. Im expecting that the options are still where they were prior to selecting one even if you already picked one of the options

#### What is the current behavior?
the elements become misaligned

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-oc1ol7

#### What is the use-case or motivation for changing an existing behavior?
for UI purposes. The page looks buggy because of this

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

currently using typescript 2.7.2, material version 6.0.0 and angular 6.0.0. Tried updating to material 6.1.0 but still encountering the issue

#### Is there anything else we should know?

I think the cause of this is `transform` in the inline style of the div with id `cdk-overlay-n`. Please see snippet below that I pulled of my code

`min-width: 644px; pointer-events: auto; font-size: 16px; transform: translateX(-16px) translateY(-63px); top: 440px; left: 437.734px;`

removing `transform` realigned the options properly

~~This issue does not happen if mat-select is not populated while the page changed (as demonstrated in stackblitz link)~~

**Comment by crisbeto** [comment]
This is the intended behavior. According to the spec, the selected option in the dropdown has to align with the trigger, if there's enough space. You can disable this behavior by setting the `disableOptionCentering` attribute.

**Comment by armando1793** [comment]
@crisbeto thank you very much! Appreciate it

**Comment by anilgiri2010a** [comment]
@crisbeto disableOptionCentering is available in angular material after version 6. 
But, in our project we are still using Is there any way angular material 5.2.5. And we can't upgrade this right now. So do you have any idea how we can achieve this same behavior in older version of angular material which don't have attribute "disableOptionCentering".

**In Short, Is there any alternative to "disableOptionCentering"?**
