### ISSUE TITLE
md-tabs + md-inputs

### ISSUE THREAD

**Issue by BenevidesLecontes** [angular/material2#1164]
#### Bug, feature request, or proposal:

[X] Bug
#### What is the expected behavior?

when tab load i expect to see Inputs with their content
#### What is the current behavior?

I only see the inputs content when i click on input
[Imgur](http://i.imgur.com/dtjvulN.gifv)
#### Which versions of Angular, Material, OS, browsers are affected?

Angular RC5, material 7-12, MacOs, all browsers
#### Is there anything else we should know?

It was working on all previous versions of material, like version 7-9, today i updated to 7-12 and i'm facing this issue. 

In previous versions if when i use detectionStrategy.Onpush this issue occur too.
I asked earlier on gitter channel but no answers. Thanks

**Comment by hpop** [comment]
Same problem here. Until this geht fixed; instead of using ngModel this works for me:

`<md-input [value]="val" (change)="val=$event.target.value"></md-input>`

**Comment by andrewseguin** [comment]
I have not seen this problem in the current release. Will close because I cannot reproduce but feel free to reopen if it is still an issue for you.
