### ISSUE TITLE
Floating label conflicts with outline when appearance is dynamically set

### ISSUE THREAD

**Issue by hblieb** [angular/material2#11653]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
floating label doesn't conflict with outline when appearance is dynamically set to 'outline.'

#### What is the current behavior?
floating label conflicts with outline when a variable is used to set the appearance.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-cvq3kq?file=app/form-field-overview-example.html

#### What is the use-case or motivation for changing an existing behavior?
Documenting the appearance inputs with a dynamic component, allowing users to switch between different appearance values, is an effective way to communicate the choices and the results.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.2, Chrome or Edge, possibly other browsers.

**Comment by aitboudad** [comment]
the same issue appear when changing label dynamically

**Comment by maxime1992** [comment]
Noticed that behavior too.

When the page loads, if there's an asynchronous value used by a `mat-form-field` (input, mat-select, ...) then we end up with a view like that:

![image](https://user-images.githubusercontent.com/4950209/41713204-5b2edc6e-7544-11e8-86c8-7d696ff2c893.png)

As soon as you click into **one** of them, both get their styles right.

Here's a really simple repro: https://stackblitz.com/edit/angular-material2-issue-5bo8d6

**Comment by DeanWilliamMills** [comment]
Anyone know if this fix is on the live 7.1.1. version? I still get this issue on version 7.1.1.
