### ISSUE TITLE
Programatic method to set Focus on mat-checkbox

### ISSUE THREAD

**Issue by JKing-B16** [angular/material2#11655]
#### Bug, feature request, or proposal:

I am unable to set the focus to a mat-checkbox from within the component.

#### What is the expected behavior?

Using a ViewChild to get the element, and being able to call a "focus()" on the target `mat-checkbox.

`## In Component HTML
<mat-checkbox #myCheckbox></mat-checkbox>

## In Component TS file
@ViewChild('myCheckbox') myCheckbox;
setFocus() {
this.myChecxbox.focus()
}
`

#### What is the current behavior?

Currently setting the focus to the mat-checkboxes dynamically created internal <input> tag allows the the focus to be set on the <input> and the checkbox to be changed with the keyboard, but the focus is not visible to the user as it would be if the box was checked or tabbed to.

#### What is the use-case or motivation for changing an existing behavior?

Ability to change mat-checkbox focus() from code for advanced keyboard interactions. Our current project will have a wireless remote control that is connected to the PC as a USB keyboard. The control is limited to only 13 keys, requiring some creative thinking for interaction with the interface.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6

**Comment by sssalib42** [comment]
Possibly related to https://github.com/mui-org/material-ui/issues/9659

**Comment by josephperrott** [comment]
This has been fixed in the latest release as part of the Material 2018 spec updates.
