### ISSUE TITLE
Dialog's maxWidth is rather behaving as default/fixed width

### ISSUE THREAD

**Issue by jagomf** [angular/material2#11666]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`maxWidth` should set the maximum width of the dialog.

#### What is the current behavior?
It is setting the default (initial) width of the dialog

#### What are the steps to reproduce?
1. Instantiate a `MatDialog` with a `maxWidth` value
2. Instantiate a `MatDialog` without a `maxWidth` value
3. Notice the first one has actually a fixed width rather than just a constraint of a maximum width

Stackblitz included: [https://stackblitz.com/edit/angular-material2-issue-z92n39](https://stackblitz.com/edit/angular-material2-issue-z92n39)

#### What is the use-case or motivation for changing an existing behavior?
`maxWidth` should specify a maximum width, not a default (and fixed) width.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Material 6.2.0

**Comment by crisbeto** [comment]
I'm not sure I understand what the expected behavior is here. When you set the `maxWidth` your dialog starts off as 450px, because it would grow larger otherwise. If you had less content in it, it would be less than 450px.

**Comment by jagomf** [comment]
@crisbeto now go and resize it so that it goes smaller; the one without `maxWidth` will actually go smaller, but the one with `maxWidth` will not, showing that the `maxWidth` attribute is either somehow setting a `minWidth` or a `width` as well, or behaving like it.

**Comment by crisbeto** [comment]
The one without a set `maxWidth` defaults to `80vw`, which is why it keeps scaling down and you're reducing the viewport size. When you set the `maxWidth` to `450px`

**Comment by jagomf** [comment]
That was exactly my point. Instead of defaulting a `maxWidth: 80vw`, the default should be a `width: 80vw`, so that you are still getting the default "elastic" feeling of the dialog even when you don't specify a `maxWidth` or `minWidth` boundaries, so that you are free to specify them if you want.
