### ISSUE TITLE
Sidenav example is not working

### ISSUE THREAD

**Issue by Adrien98** [angular/material2#11676]
#### Bug, feature request, or proposal:
Bug : https://material.angular.io/components/sidenav/overview
This example is not working, the Stackblitz example either.

#### What is the expected behavior?
Like the sidemenu of Google Play Android version, a click on a button is making open a menu

#### What is the current behavior?
Nothing

#### What are the steps to reproduce?
https://stackblitz.com/angular/anqbjlvmdmk?file=app%2Fsidenav-overview-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6, Angular Material 6.2.1, Google Chrome

#### Is there anything else we should know?

**Comment by andrewseguin** [comment]
The example is not intended to show open/close interaction, rather it is just to show how to set up a basic sidenav. For an example of toggling the sidenav, check out https://stackblitz.com/angular/nkjeenxdjnj?file=app%2Fsidenav-open-close-example.ts
