### ISSUE TITLE
tree collapse not work will

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#11689]
#### Bug, feature request, or proposal:

bug
#### What is the expected behavior?
when child node is expand , collapse the root node the tree should hide all node.

#### What is the current behavior?
when child node is expand , collapse the root node the tree still show the item of child node
![err](https://user-images.githubusercontent.com/14286935/41045068-293396ca-69da-11e8-91b1-d3a17630af15.png)
.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

https://material.angular.io/components/tree/examples
#### What is the use-case or motivation for changing an existing behavior?

expand all node , then collapse the root node

**Comment by stevenmi** [comment]
the example https://material.angular.io/components/tree/examples    Tree with dynamic data
step 1. expand Vegetables
step 2. expand Onion
step 3.contraction  Vegetables then expand Vegetables and Onion
it will be
![err](https://user-images.githubusercontent.com/14286935/41045657-5a92481e-69db-11e8-82f0-69bc18a40266.png)

**Comment by tinayuangao** [comment]
Fixed by #11728
