### ISSUE TITLE
mat-slide-toggle Issue with ng build --aot  

### ISSUE THREAD

**Issue by spartha1995** [angular/material2#11698]
#### Bug, feature request, or proposal:
Bug: ng build --aot is not working

#### What is the current behavior?
If I run a command: ng build --aot , it is giving an error :
ERROR in Illegal State: referring to a type without a variable {"filePath":"Path/node_modules/@angular/material/slide-toggle/typings/index.d.ts","name":"MatSlideToggle","members":[]}

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I am using angular 6

**Comment by DevVersion** [comment]
I tried to reproduce that issue within a clean new Angular CLI project, but wasn't able to reproduce your issue.

Also our AOT checks that run for every commit that lands in `master` seem to pass. Please provide more information and maybe a repository that demonstrates the issue.
