### ISSUE TITLE
mat-checkbox frame view issue

### ISSUE THREAD

**Issue by genyklemberg** [angular/material2#11699]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
An expected layout should be normal with equal space like this: http://prntscr.com/js1lpe
Space between frame and background

#### What is the current behavior?
When made smaller looks like this: http://prntscr.com/js1vki

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6, Material ~6.0.0, Windows 10, All Browsers

#### Is there anything else we should know?
Flex layout used

what else should I provide?

**Comment by genyklemberg** [comment]
any news?

**Comment by genyklemberg** [comment]
Any response?

**Comment by josephperrott** [comment]
Closing as obsolete as the checkbox layout has been refreshed, if you find this issue to occur again please open up a new issue for us to take a look.
