### ISSUE TITLE
Docs site not reflowing content on certain devices

### ISSUE THREAD

**Issue by phibonacci85** [angular/material2#11693]
#### Bug, feature request, or proposal:
In portrait mode on a Pixel XL, the sentences are not wrapping and there is a huge horizontal scroll. When you scroll right the nav-bar gets cut off. I can not duplicate this on chrome, but it happens on a real device for both an app I developed, and for your main site. ex. (https://material.angular.io/cdk/layout/overview) has the same problem.

#### What is the expected behavior?
I expect no horizontal scrolling and the sentences to wrap. If there is horizontal scrolling, it should only affect the content, not the nav-bar.

#### What is the current behavior?
Horizontal scrolling with no word wrap. nav-bar cuts off when scrolling right.

#### What are the steps to reproduce?
Use an actual device on your own website.
https://material.angular.io/cdk/layout/overview
https://material.angular.io/cdk/ovservers/overview
both do it. Chrome devtools does not have the bug in device mode. Maybe it only happens on my phone which is a Pixel XL

#### What is the use-case or motivation for changing an existing behavior?
I noticed it on a website I was developing using material. While trying to find a solution to the problem, I noticed that your own site does it as well. It is very tacky looking and kind of ruins the whole experience of using angular material.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Whichever version your website uses on Chrome 66.0.3359.158... also...
My site uses
Angular CLI: 6.0.3
Material: 6.0.2
OS: Android 8.1.0
TypeScript: 2.7.2
Browser: Chrome 66.0.3359.158

#### Is there anything else we should know?
Several pages on your own site are showing the same problem.

**Comment by phibonacci85** [comment]
![left](https://user-images.githubusercontent.com/15526676/41060902-98c71172-6996-11e8-9be6-0610a2b9678e.png)
![right](https://user-images.githubusercontent.com/15526676/41060903-98d8ab6c-6996-11e8-9578-d646637ee0b6.png)

here is a couple screenshots to help understand the problem

**Comment by andrewseguin** [comment]
Thanks - this is due to our use of `<pre>` and an issue has been opened on the doc site's repo. I'll leave this open for visibility though since its more likely to be dealt with here.

https://github.com/angular/material.angular.io/issues/458

**Comment by amcdnl** [comment]
Fix PR'd - https://github.com/angular/material.angular.io/pull/471

**Comment by crisbeto** [comment]
Looks like this was resolved in the material.angular.io repo.
