### ISSUE TITLE
Material Date Picker in a reusable component

### ISSUE THREAD

**Issue by shanegilbert** [angular/material2#11691]
#### Bug, feature request, or proposal:
Setting up a material datepicker has many options. It is helpful to put this in a reusable component so that all developers implement the date picker in a consistent way and be able to customize or add additional features.

#### What is the expected behavior?
It should be a simple matter of creating a component that implements control value accessor and validator around the material date picker. An example of how to do this for the date picker and other controls would be helpful for BOTH reactive and template forms.

#### What is the current behavior?
It is not simple particularly for template forms. The write value and the validate are not in sync and you get inconsistent behavior with validation on the form. For example, the initial load of an existing value will have the validation behind and show the control to be invalid with a required error even though the value is there.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

https://stackblitz.com/edit/angular-vyzez1

#### What is the use-case or motivation for changing an existing behavior?
Wrapping setup of material components to speed up development and maintain implementation consistency across a development team.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6
Material 6.2.1

#### Is there anything else we should know?
 It is likely that I am just doing it wrong, but I have not been able to find an example of how to do it right on gitter or stackoverflow.

**Comment by julianobrasil** [comment]
Just taken a quick look at your code. Adding the following code seems to fix your issue:

```
  ngAfterViewInit() {
    this.aocDatePickerControl.valueChanges.subscribe(v => {
      this.onChange(v);
    });
  }
``` 

I absolutely did not check for any side effects, this is just an idea so you can try fixing the overall behavior.

**Comment by shanegilbert** [comment]
@julianobrasil That gets the validation to work correctly, however it does mark the form as dirty which it shouldn't be from the initial load. This causes problems with some other code that I have that checks if the form is dirty to prompt the user about saving changes.

**Comment by julianobrasil** [comment]
In that case it's easier to handle the states with a reactive control: https://stackblitz.com/edit/angular-datepicker-wrapper-reactive

**Comment by shanegilbert** [comment]
Going the reactive route works. I wanted to stick with a single development model in the project, but I can live with following the reactive model just for reusable control/components like this. Thanks for the help.
