### ISSUE TITLE
Dialog: backdrop does not overlap navbar

### ISSUE THREAD

**Issue by ngi32487** [angular/material2#11704]
#### Bug, feature request, or proposal:
I have an angular 6 application with basically a navbar on top and a content section below. The navbar links trigger different components which are then rendered in the router-outlet of the content-section.
When i open a dialog from a component (no matter whether inside the navbar or inside the router-outlet), the dialog does not overlap the navbar (Bootstrap class) on top of the page.
I have prepared a StackBlitz (see below) which reproduces this behaviour.

#### What is the expected behavior?
The Dialog (the backdrop) should overlap the navbar, so that users cannot press links/buttons inside the navbar.

#### What is the current behavior?
The backdrop overlaps all components, but not the navbar, which appears to be "on top" and therefore is still accessible by the user.

#### What are the steps to reproduce?
StackBlitz editor: [open](https://stackblitz.com/edit/angular-material2-issue-elshgk)
App in new window (necessary for the navbar to be displayed correctly, as this app does not support small devices): [open](https://angular-material2-issue-elshgk.stackblitz.io)

You can find the navbar and the router-outlet I mentioned above in the MainComponent.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I use angular v6.0.4 and material v6.2.1. Affected browsers: FF, IE11, Opera v51, Chrome (these are at least the ones I tested).

#### Is there anything else we should know?
I managed to fix this behaviour for the moment by adding the following class to my global styles.css:
`.cdk-overlay-container {
  z-index: 9999;
}`

**Comment by crisbeto** [comment]
Closing since everything is working as expected. When you have an element with such a high `z-index`, it's up to you to also bump the `z-index` of the `.cdk-overlay-container`.

**Comment by ngi32487** [comment]
ehmm... have you looked at the StackBlitz? There is no element with a z-index set.

**Comment by ngi32487** [comment]
Finally I found the problem, maybe this explanation helps others:
The bootstrap class `.navbar-fixed-top` has `z-index: 1030` (refer to bootstrap.css), therefore the `.cdk-overlay-container` (the parent element for the dialog-backdrop) needs to have a higher `z-index` in order to overlap.

**Comment by ramiatoui** [comment]
thank you , this help me
but i just change the z-index of navbar to 900 
and it's work fine 
so thx again
