### ISSUE TITLE
Need To Reset / Refresh Paginator For Reuse Of Mat Table

### ISSUE THREAD

**Issue by svstartuplab** [angular/material2#11709]
#### Bug, feature request, or proposal:

Feature request?  Maybe bug.

#### What is the expected behavior?

Start with a new paginator in the same component for each of multiple search types.

#### What is the current behavior?

1)  Do a query and populate the table.  Say the query searches for members with a skill_id of 2.

2)  Do another query, say get all members, and populate the same table.  All seems to be working.

3)  Click the forward button for the next page of results and it runs the first query, step 1, and then the second one, loading only the first page of the second one because it starts all over with step 2.

The paginator doesn't know to start all over when moving to step 2.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
Probably not necessary and complicated with the db.  I've done enough troubleshooting that I'm pretty sure of the solution.

This won't work in each search function.
@ViewChild(MatPaginator) paginator: MatPaginator;

I tried setting up a different paginator for each function but that didn't work.
  @ViewChild(MatPaginator) paginator1: MatPaginator;
  @ViewChild(MatPaginator) paginator2: MatPaginator;
  @ViewChild(MatPaginator) paginator3: MatPaginator;

#### What is the use-case or motivation for changing an existing behavior?

Multiple types of search / queries that use the same table.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Chrome browser Version 67.0.3396.79, the latest.

Angular CLI: 6.0.3
Node: 8.11.2
OS: darwin x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cdk                      6.1.0
@angular/cli                      6.0.3
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.1.0
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3

#### Is there anything else we should know?

No.

**Comment by andrewseguin** [comment]
I'm not sure I understand the issue or if this is a problem with the paginator. 

Please re-open with a reproduction of the issue in StackBlitz so we can dive in and see what's going on. If it's a general troubleshooing thing, I recommend asking on StackOverflow since we tend to not have the bandwidth to investigate troubleshooting cases
