### ISSUE TITLE
website is down! (https://material.angular.io/)

### ISSUE THREAD

**Issue by YonathanMeguira** [angular/material2#11708]
BUG

Website material.angular.io is down! (https://material.angular.io/)

here are the errors: 
material.angular.io/:19 GET https://material.angular.io/styles.34ce976a214ced57a590.css 404 ()
2material.angular.io/:42 GET https://material.angular.io/main.aac00e1d0efd15269264.js 404 ()

**Comment by svstartuplab** [comment]
I just checked and the site is up in the U.S.  You have other issues.
