### ISSUE TITLE
Documentation: not all options for Datepicker are listed

### ISSUE THREAD

**Issue by dansoper** [angular/material2#11700]
#### Bug, feature request, or proposal:
Inconsistent documentation for Datepicker

#### Description:
Datepicker Overview pages introduces the `multi-year` option for the `startView` property, but this option is not listed on the API page.

**Comment by Nevaan** [comment]
Hi,
I would like to start contributing. Can I take this one?

**Comment by mmalerba** [comment]
@Nevaan absolutely, just send a PR and mention me on it
