### ISSUE TITLE
MatDialog - hasBackdrop/disableClose conflict with each other

### ISSUE THREAD

**Issue by mswilson4040** [angular/material2#11713]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MatDialogConfig `disableClose` should function like the documentation states:

> disableClose: boolean | Whether the user can use escape or clicking outside to close a modal.

#### What is the current behavior?
When configuration the MatDialogConfig to include `hasBackdrop: false`, you lose the ability to close the modal when a user clicks outside of it. This is to also say that mentioning `disableClose` in the config does nothing if `hasBackdrop` is `false`

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

https://stackblitz.com/edit/angular-ev6jqa?file=app/dialog-overview-example.ts

#### What is the use-case or motivation for changing an existing behavior?

Quality

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5 and 6

**Comment by crisbeto** [comment]
The intended behavior of `disableBackdrop` is to remove it completely, which is what it's doing. If you want to make it transparent, you can set `config.backdropClass = 'cdk-overlay-transparent-backdrop'`.

**Comment by mswilson4040** [comment]
That is not the issue. The issue is that `disableClose` is dependent on `hasBackdrop` being true. `disableClose` does not function as documented.

**Comment by mswilson4040** [comment]
@crisbeto I don't believe the issue is being misunderstood. I have opened up a new ticket that explains the issue in a better way: https://github.com/angular/material2/issues/11750
