### ISSUE TITLE
Proposal: Main menu responsive

### ISSUE THREAD

**Issue by vladanPro** [angular/material2#11714]
#### Proposal:
There is only menu but not main menu like navbar, but i don't need burger menu on main menu. I used burger menu on list but i have like on image menu.
![screen shot 2018-06-08 at 13 40 38](https://user-images.githubusercontent.com/1330505/41156294-91c8ebe8-6b21-11e8-9194-67b5ff27f906.png)

I try to make this one like on image or web site below. I don't see how i can do it
https://v5.material.angular.io/

#### What is the expected behavior?
Expected behavior now is not to show two burger menus.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.9, Material 5.2.4, Angular CLI 1.7.0

**Comment by andrewseguin** [comment]
Will have to close this issue since it is neither a bug or feature request. Please refer questions to our community on places like StackOverflow or Gitter.
