### ISSUE TITLE
'align' attribute in md-hint does not working

### ISSUE THREAD

**Issue by alanpurple** [angular/material2#1172]
```
<md-input #desc type="text" [(ngModel)]="newPack.description"
                      name="description" maxlength="50"
                      placeholder="description">
                <md-hint align="end">{{desc.characterCount}} / 50</md-hint>
</md-input>

```

align is always at start

angular rc.6, material2 alpha 8-1

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/E15hpqHojz2Gy2mPKbmr?p=preview works as expected

**Comment by RoxKilly** [comment]
I have the same problem as the OP with `Angular 2 rc 6` and `Material 2 alpha 8.1`

http://plnkr.co/edit/66VDhUqLOwvlDqWMBjYb?p=preview

**Comment by ptsydzik** [comment]
@alanpurple and @RoxKilly looks like you forgot to include angular styles. for quick test try to add 
<link href="https://npmcdn.com/@angular2-material/core@latest/style/core.css">
to your index.html

**Comment by RoxKilly** [comment]
@ptsydzik  good thinking, but adding `core.css` makes no difference. See my updated plunker link above.

**Comment by colinfang** [comment]
I can reproduce it. Also note that the position of hint is a bit too high. (it exceeds the horizontal line.)

**Comment by colinfang** [comment]
Also note there is no ripple effect for `md-button` at all. It used to work in alpha 7.1  http://plnkr.co/edit/0qUqDezuENJ1fAJkecsW?p=preview

**Comment by jhyde** [comment]
I'm experiencing the same issue with md-hint as RoxKilly. The class styles for .md-hint are not being applied for some reason.  The styles from input.scss look like:
```
.md-hint {
    position: absolute;
    font-size: 75%;
    bottom: -0.5em;

    &.md-right {
      right: 0;
    }
  }
```

If you add those manually, somehow every looks fine.

**Comment by RoxKilly** [comment]
@jhyde  Try using a more specific CSS selector. You can do this by adding a custom attribute. For example:

**template**
```
<md-input #desc placeholder="description">
                <md-hint customcss align="end">{{desc.characterCount}} / 50</md-hint>
</md-input>
```
**CSS**
```
.md-hint[customcss]{
    ...
}
```

This should help the browser give priority to your CSS rules.  If that doesn't work, you can add the [`!important` flag](https://css-tricks.com/when-using-important-is-the-right-choice/) to rules you wan the browser to prioritize
```
.md-hint {
    position: absolute !important;
    font-size: 75% !important;
    bottom: -0.5em !important;

    &.md-right {
      right: 0 !important;
    }
  }
```

**Comment by rolandjitsu** [comment]
I am experiencing the same issue, `<md-hint>` si aligned to left and exceeds the input border.

**Comment by emoralesb05** [comment]
The problem is that angular is assigning a different emulated shadowdom id for md-hint than md-input, so its not actually using the `.md-hint` / `.md-right` classes.

![image](https://cloud.githubusercontent.com/assets/5846742/18770193/663a3f2e-80e8-11e6-8772-5043a3fb159b.png)

And since the classes are actually in the `md-input` component, they dont cascade into `md-hint`. (whole point of shadowdom).

**Comment by jelbourn** [comment]
@crisbeto can you determine if this is still an issue? It may have already been fixed.

**Comment by alanpurple** [comment]
@jelbourn  not anymore, seems solved
