### ISSUE TITLE
Datapicker on iOS browsers

### ISSUE THREAD

**Issue by bpasha7** [angular/material2#11730]
#### Bug, feature request, or proposal:
MAT_DATE_LOCALE not work for matDatepicker on iOS 9.x.x, 10.3.3 (Safari, Chrome)

#### What is the expected behavior?
matDatepicker should behave on iOS the same as others OS, such as Windows, Android

#### What is the current behavior?
MAT_DATE_LOCALE does not affect on matDatepicker on iOS, but date into p, h1, etc. are ok.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.0, Angular Material 6.0.0, TypeScript 2.8.3

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/15242275/41187388-36fa3e22-6bd2-11e8-8a5e-25d45aeb9ca0.png)

**Comment by mmalerba** [comment]
Are you using `NativeDateAdapter`? iOS Safari 9 does not support the `Intl` API used by the `NativeDateAdapter`. You should be able to use the `MomentDateAdapter` instead which uses Moment.js to parse and format dates.
