### ISSUE TITLE
update firebase@4 to 5 to support win+node 10

### ISSUE THREAD

**Issue by amitport** [angular/material2#11735]
Root `package.json` uses `firebase@4` which transitively uses `grpc@1.10.1` which fails to build on win+node 10. `firebase@5` does not have this issue.

See also:
https://github.com/grpc/grpc/issues/15403
https://github.com/angular/material2/issues/10401

**Comment by crisbeto** [comment]
The current setup works on Windows and Node 8. I don't think we can bump to None 9 or 10 since Angular core is set to Node `>=8.9.1 <9.0.0`.

**Comment by amitport** [comment]
@crisbeto. OK. I've reverted to Node 8 LTS. In any case, practically, only ` firebase@4` dependencies block the development of Material with Node@10. (I've manually overridden package-lock to require `grpc@1.12.2` and it works fine)

**Comment by jelbourn** [comment]
Closing this since it only affects node 10 which we haven't switched to yet.
