### ISSUE TITLE
Change in mat-select not working after upgrading to Angular 6 and material 6.201

### ISSUE THREAD

**Issue by santanageorge** [angular/material2#11744]
#### Bug, feature request, or proposal:

BUG

#### What is the expected behavior?

Need to alert when change the value in select

#### What is the current behavior?

Not working

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-dygv2i

**Comment by jymdman** [comment]
The  **change** event was deprecated in v6.0.0.
Use **selectionChange** instead.

**Comment by amcdnl** [comment]
See https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes for more information.

**Comment by santanageorge** [comment]
@jymdman @amcdnl  Thanls
