### ISSUE TITLE
form input freezes on focus - Safari ONLY

### ISSUE THREAD

**Issue by un33k** [angular/material2#11740]
#### Bug, feature request, or proposal:
[x] Possible Bug 

#### What is the expected behavior?
Form inputs should accept characters

#### What is the current behavior?
When clicking on any form input in Safari, the focus changes, however, it freezes so it won't take any input from the keyboard.

Works in:
Chrome Version 66.0.3359.181 (Official Build) (64-bit) an
Firefox 60.0.1 (64-bit)

Doesn't work in:
**Version 11.1 (13605.1.33.1.4)**

Identical code - works in Chrome and Firefox, but not Safari.

#### What are the steps to reproduce?
Try a form in Safari with the following version of material 2.
```html
<!-- login.component.html -->
<form [formGroup]="form">
  <mat-form-field>
    <input matInput formControlName="email" placeholder="Email">
  </mat-form-field>
</form>
```

```typescript
// login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  form: FormGroup;
  constructor(public formBuilder: FormBuilder) {}

  ngOnInit() {
    this.buildForm();
  }

  private buildForm() {
    this.form = this.formBuilder.group({
      email: ['', [Validators.required]]
    });
  }
}
```

```typescript
// ....
  {
    path: 'auth/login',
    component: LoginComponent,
  },
//...
```
Note: The above form is a simplified version for brevity. However, this bare-minimum form is not working in Safari. 

_Note:_ Was unable to recreate on stackblitz:
https://stackblitz.com/edit/angular-material2-issue-tir445

_Also:_ Was unable to recreated with ngCLI bare-bone created module.

_Thoughts:_ What else could this be that only affects Safari and not the other two browser?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 6.0.5
Node: 9.6.1
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.5
@angular-devkit/build-angular      0.6.5
@angular-devkit/build-ng-packagr   0.6.5
@angular-devkit/build-optimizer    0.6.5
@angular-devkit/core               0.6.5
@angular-devkit/schematics         0.6.5
@angular/cdk                       6.2.1
@angular/cli                       6.0.5
@angular/compiler-cli              6.0.4
@angular/flex-layout               6.0.0-beta.16
@angular/material                  6.2.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.5
@schematics/angular                0.6.5
@schematics/update                 0.6.5
ng-packagr                         2.4.2
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.8.3
```
#### Is there anything else we should know?
Clicking on `email` changes the focus, but keyboard inputs are ignored.
if I go really fast, I am able to enter one single char in the field, but that's about it. 
Placeholder works, it moves away on focus.
Validators work
Safari at this point runs at 1.1 % CPU. So no tight loop.
No exception errors
No other errors on the console.

**Form in Chrome:** (works as expacted)
![screen shot 2018-06-11 at 7 06 39 am](https://user-images.githubusercontent.com/407537/41228339-1180d262-6d46-11e8-8290-e972639e6efe.png)

**Form in Safari:** (unable to enter value)
![screen shot 2018-06-11 at 7 06 50 am](https://user-images.githubusercontent.com/407537/41228371-262cc676-6d46-11e8-9ae0-16d3af1b04ec.png)

**Comment by un33k** [comment]
After a lot of combinations and permutations, the culprit was the following.

* {
  -webkit-user-select: none;
  -moz-user-select: -moz-none;
  -o-user-select: none;
  user-select: none;
}

Safari was disabling the input field.

**Comment by un33k** [comment]
I leave this open for the core team to decide if it should be closed. Or if there is a way to warn the user.

**Comment by josephperrott** [comment]
Unfortunately there not a quality, efficient way for us to detect if there is a global rule like this applied.

Since this amounts to application specific CSS causing an issue and not something done by the Angular Material library, I am going to go ahead and close this issue out.

**Comment by kdawg1406** [comment]
@un33k you are a genius.  I spent hours trying to get angular material to work with Safari.  

Thank you for posting your solution!
