### ISSUE TITLE
mat-options generated by component inside mat-select not visible/selectable

### ISSUE THREAD

**Issue by tpsb** [angular/material2#11742]
#### Bug, feature request, or proposal:

bug

I'm trying to nest a custom component inside mat-select which would have some logic to generate a collection of mat-options that the user could choose from. The logic for getting the options is reusable in my case and it would be nice to have a way of enclosing it in a dedicated component.

#### What is the expected behavior?

mat-options ptions should be rendered and be selectable

#### What is the current behavior?

1. if only a component responsible for providing mat-options is used, then no option is rendered by mat-select at all,
2. if a component responsible for providing mat-options is used alongside a direct mat-option child the indirect options are rendered but are not selectable.

The use case would be as in point 1 - I wouldn't want to place extra options only for the options generated by the custom component to be visible. Point 2 is here to show that placing the direct mat-option child in mat-select influences the behavior of mat-select and makes it show the options from the custom options component.

#### What are the steps to reproduce?
app: https://angular-81aaem.stackblitz.io
editor: https://stackblitz.com/edit/angular-81aaem

#### What is the use-case or motivation for changing an existing behavior?

I'd like to have a custom and reusable component that would be responsible for providing mat-options dynamically - options potentially loaded from backend or redux store. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

The stackblitz example uses Angular 6.0.4 and Angular Material and CDK 6.2.1. 
The example behaves similarily on Angular 5.2.10 and Material 5.2.5 combination.

**Comment by crisbeto** [comment]
This is more of a side-effect of how Angular works, rather than `mat-select`. The select component uses `ContentChildren` to pick up all of the options, however `ContentChildren` won't pick up any of the options that are generated inside child components. Closing since this works as expected.

**Comment by rmedaer** [comment]
@crisbeto I understand there is no bug. However, how could we provide mat-option(s) from nested component ?

Here is my use case: I would like to manage my `mat-option`s from a component which knows about them:
```html
<mat-select>
    <app-my-options></app-my-options>
</mat-select>
```

**Comment by crisbeto** [comment]
There's no way for `mat-select` to know about the options in that case @rmedaer.

**Comment by pburkindine** [comment]
I raised a similar issues for the autocompleter here:

https://github.com/angular/material2/issues/15697

This is a common use case where complex and dynamic behavior is needed for these controls.
