### ISSUE TITLE
I see this when I theming my Angular Material app:Argument `$map` of `map-get($map, $key)` must be a map.

### ISSUE THREAD

**Issue by kinmy** [angular/material2#11746]
theme.scss:
@import '~@angular/material/theming';

@include mat-core();

$my-app-primary: mat-palette($mat-indigo);
$my-app-accent: mat-palette($mat-pink, A200, A100, A400);
$my-app-warn: mat-palette($mat-red);

$my-app-theme: mat-ligth-theme($my-app-primary, $my-app-accent, $my-app-warn);

@include angular-material-theme($my-app-theme);
-------------------------------------------------------------------
The terminal shows:
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss
Module build failed:
  $foreground: map_get($theme, foreground);
              ^
      Argument `$map` of `map-get($map, $key)` must be a map
      in /Volumes/work/imooc_angular4_taskmgr/taskmgr/node_modules/@angular/material/_theming.scss (line 1230, column 16)

webpack: Failed to compile.
---------------------------------------------------------------------
Can you help me solve this problem when I use "ng serve"?
Thanks a lot!

**Comment by shoff** [comment]
So what did you do to fix this issue?
