### ISSUE TITLE
Feature Request: mat-button [color] directive

### ISSUE THREAD

**Issue by yeager-j** [angular/material2#11748]
#### What is the expected behavior?

```html
<button mat-button [color]="colorVariable"></button>
```

This should work.

#### What is the current behavior?

Currently you can't set `color` to a variable. Only this is supported:

```html
<button mat-button color="primary"></button>
```

#### What is the use-case or motivation for changing an existing behavior?

I'd like to create a toggle. <mat-button-toggle-group> doesn't fit my use case.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Current

#### Is there anything else we should know?

If possible, I'd also like to add directives for [mat-button], [mat-raised-button], etc.

**Comment by crisbeto** [comment]
This is supported already. [Here's an example](https://stackblitz.com/edit/angular-t16wrs).
