### ISSUE TITLE
MD-AUTOCOMPLETE ISSUE 

### ISSUE THREAD

**Issue by Balvindersing** [angular/material2#11759]
Bug:
I am  facing problem with angular-martial-autocomplete control,
angular v-1.0.1
this control create virtual-container
when i am using only one  MD-autocomplete on page then design not effected but if i am put multiple MD-autocomplete then design will effected 
so please any one know what is problem.
how can i resolve this issue.
PFA:
![designau](https://user-images.githubusercontent.com/24611440/41275607-0cc69a8c-6e3f-11e8-9645-035d94bb8615.png)
![designau1](https://user-images.githubusercontent.com/24611440/41275615-162a69fa-6e3f-11e8-8286-0dd9fb4169d2.png)

**Comment by crisbeto** [comment]
This is the expected behavior. The autocomplete opens upwards, because there's not enough space for it to fit below.
