### ISSUE TITLE
Accessibility issue using mat-checkbox,mat-slide-toggle and mat-select

### ISSUE THREAD

**Issue by chetankumar45** [angular/material2#11757]
On running accessibility tool AMP, below issues are identified due to mat checkbox and select.
1. Provide alternative text for images - The svg added for check mark dose not have  alt text.

<svg xml:space="preserve" class="mat-checkbox-checkmark" focusable="false" version="1.1" viewBox="0 0 24 24"><path class="mat-checkbox-checkmark-path" d="M4.1,12.7 9,17.6 20.3,6.3" fill="none" stroke="white"></path></svg>
![capture](https://user-images.githubusercontent.com/28528343/41273109-a92725cc-6e35-11e8-8c46-dae83dc138aa.JPG)
![1](https://user-images.githubusercontent.com/28528343/41273112-aff01fd0-6e35-11e8-8f9c-195379d3f9ad.JPG)

2. Ensure ARIA roles, states, and properties are valid - Not able to added aria-checked, how can we added fix this issue.
<input class="mat-checkbox-input cdk-visually-hidden" type="checkbox" id="mat-checkbox-235-input" tabindex="0" aria-label="Select All" aria-checked="false">

If the same mat-checkbox is replaced by input type="checkbox" none of the issue will be reproduced.

Checkbox code - 
<mat-checkbox aria-label="Select" (click)="checkboxSelected($event,row)" (change)="$event ? selection.toggle(row) : null" [checked]="selection.isSelected(row)">
                    <span fxHide>Select</span>
                </mat-checkbox>
Toggle code -
<fieldset class='broadcast-fieldset'>
              <mat-slide-toggle color="primary" aria-label="Broadcast" (change)="changeBroadcastToggle($event)" name="broadcastMsgToggle" formControlName="broadcastMessageToggle">
                 <legend> {{broadcastMessageToggleValue}} </legend></mat-slide-toggle>
</fieldset>

Please validate and provide the solution.

Thanks,
Chetan

**Comment by crisbeto** [comment]
1. The SVG inside the checkbox is purely decorative so it doesn't need its own description. The description for the checkbox is provided through the label.
2. [The `mat-checkbox` is using an `input[type="checkbox"]` internally already](https://github.com/angular/material2/blob/master/src/lib/checkbox/checkbox.html#L4).

**Comment by josephperrott** [comment]
Closing, as noted above the SVG does not require alt text as it is decorative and its status is presented by the status of the checkbox, the `aria-checked` state is handled by the underlying native checkbox control.
