### ISSUE TITLE
Webpack 1 / rc 8-1 "Uncaught SyntaxError: Unexpected token import"

### ISSUE THREAD

**Issue by MoxxNull** [angular/material2#1176]
[x] BUG (?)

#### What is the expected behavior?

Material2 should work with webpack1 like angular2 rc6 does.

#### What is the current behavior?

Error "Uncaught SyntaxError: Unexpected token import" 

#### What are the steps to reproduce?
Any solution with angular2 rc6 / material alpha 8-1; bundles with webpack.

I'm just an amateur, but as far as I see angular2 exports umd modules by default and material should (does?!) aswell. The error comes from every material-component indicating that modules picked up by webpack are in es2015 format ... or am I missing something?

#### Which versions of Angular, Material, OS, browsers are affected?
angular2 rc6 / material 2 alpha 8-1 / win10 / typescript 2.0 beta

**Comment by mvukic** [comment]
I had the same problem and my solution was this.
Instead of :

```
import {MdCoreModule} from "@angular2-material/core"
import {RtlModule} from "@angular2-material/core/rtl/dir";
import {OverlayModule} from "@angular2-material/core/overlay/overlay-directives";
...
```
and other stuff from @angular2-material/core/..

Do this:
```
import {MdCoreModule,RtlModule, OverlayModule, ...} from '@angular2-material/core';
```

And in tsconfig.json:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "moduleResolution": "node",
    "noEmitHelpers": true
  },
  "compileOnSave": false,
  "buildOnSave": false
}
```

**Comment by MoxxNull** [comment]
Actually your solution fixed it :)     
And fixing some of  my wrong imports 

> import {MdButtonToggleModule} from '@angular2-material/button-toggle/button-toggle';

to

> import {MdButtonToggleModule} from '@angular2-material/button-toggle';

.. obvious but I totally missed that .. . .. Sorry. It's  working now :+1:

**Comment by LawzPopiel** [comment]
Thanks   @mvukic  !  Your solution fixed my issue also.  I was using the example file from https://github.com/jelbourn/material2-app/blob/master/src/app/app.module.ts.  The readme example worked ok, but the actual code in the repo did not.
