### ISSUE TITLE
Click event not fired in mat-menu-item sub mat-menu item generated with *ngFor

### ISSUE THREAD

**Issue by MikeAlexMartinez** [angular/material2#11766]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
A click should fire when the submenu item is clicked, on hover the styling should be darker.

#### What is the current behavior?
click isn't firing an event in the submenu, additionally, the hover styling isn't being consistently applied (it's flashing on hover)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-2nxcqq-other-vpw9gj

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3, Material 6.2.0

**Comment by MikeAlexMartinez** [comment]
The issue with this seems to be the function I'm using to retrieve an array of items.

When I change the demo to the following it works:
https://stackblitz.com/edit/angular-material2-issue-2nxcqq-other

But then I'm hard-coding the labels instead filtering an array.

**Comment by crisbeto** [comment]
@MikeAlexMartinez your first link seems to be broken.

**Comment by MikeAlexMartinez** [comment]
I think the issue is with the fetchLabels() function returning an array.

**Comment by crisbeto** [comment]
Yes, when you have a function in the `ngFor`, it'll end up re-rendering the list with a brand new set of button whenever change detection runs. This means that when you trigger a `mousedown` on your button, it'll be removed and recreated which will interrupt the click event. Closing since this works as expected.
