### ISSUE TITLE
[Tooltip] Wrong tooltip position while scrolling when the element position is fixed on the right

### ISSUE THREAD

**Issue by greg-md** [angular/material2#11761]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should auto align the tooltip near element.

#### What is the current behavior?
Tooltip position is going down when there is a scroll on the page.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-phje6f

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest versions. Any browser.

**Comment by crisbeto** [comment]
This is the same issue as https://github.com/angular/material2/issues/11365. Closing as a duplicate.
