### ISSUE TITLE
Bug in calculation margin-top mat-grid-tile inside mat-grid

### ISSUE THREAD

**Issue by LoganDupont** [angular/material2#11774]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The last 2 grid-tiles should be positioned correctly next to each other and not overlapping the other tiles.

#### What is the current behavior?
Something goes wrong when grid-tiles are positioned in grid.  Some grid-tiles are overlapping each other.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-jm4ztb

#### What is the use-case or motivation for changing an existing behavior?
The grid-tiles should be displayed correctly in grid.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Material 6.2.0
All browsers

#### Is there anything else we should know?
After some investigation I saw that the calculation for the margin-top is not set correctly.

**Comment by vivian-hu** [comment]
fixed with PR https://github.com/angular/material2/pull/12980
