### ISSUE TITLE
Override dropdown/overlay width in autocomplete, select and other components

### ISSUE THREAD

**Issue by pleerock** [angular/material2#11773]
Most of options in practice do not fit width of inputs, e.g.

![screenshot 2018-06-13 14 46 10](https://user-images.githubusercontent.com/1753397/41343661-9d1d557e-6f18-11e8-8678-5fd61709cc9a.png)

There are two options: 

The most simple is to provide option to make dropdown/overlay width to be able to set it to "fixed"|"dynamic" or maybe dynamic with max width, e.g.

![screenshot 2018-06-13 14 57 59](https://user-images.githubusercontent.com/1753397/41344301-3172daf4-6f1a-11e8-9145-15fd0c3cf84b.png)

Second option is to expand **hovered** option with extra div with padding and white background with full width, it will be kinda outset.

If there are even hacky solutions of first approach can someone point me how to resolve it. Thanks.

**Comment by dgsmith2** [comment]
My workaround

```
<input type="text" ... #trigger="matAutocompleteTrigger">
...
<mat-autocomplete ... [appAutocompleteWidthHack]="trigger">...</mat-autocomplete>
```
```
@Directive({
    selector: 'mat-autocomplete[appAutocompleteWidthHack]'
})
export class AutocompleteWidthHackDirective implements OnInit {
    @Input() appAutocompleteWidthHack: MatAutocompleteTrigger;

    ngOnInit() {
        (this.appAutocompleteWidthHack as any)._getHostWidth = () => 'auto';
    }
}
```

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Comment by dgsmith2** [comment]
Does this impact the PR?
