### ISSUE TITLE
Align mat-button-toggle with material spec

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#11789]
#### Bug, feature request, or proposal:
Align mat-button-toggle with material spec

#### What is the expected behavior?
https://material.io/design/components/buttons.html#toggle-button

#### What is the current behavior?
https://krorpxogjxl.angular.stackblitz.io/

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.2.1

**Comment by crisbeto** [comment]
See https://github.com/angular/material2/pull/12443.
