### ISSUE TITLE
Buttons have dark left top and bottom corners

### ISSUE THREAD

**Issue by Corsseir** [angular/material2#11785]
#### Bug, feature request, or proposal:
Buttons have dark left top and bottom corners.

#### What is the expected behavior?
To be like right ones.

#### What is the current behavior?
Dark left top and left bottom corners

#### What are the steps to reproduce?
Just test the newest stable version of Angular Material.

#### What is the use-case or motivation for changing an existing behavior?
Better look

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.0.4
Angular Material: ^6.2.1

#### Is there anything else we should know?
![screenshot from 2018-06-14 13-30-10](https://user-images.githubusercontent.com/11137173/41409815-c71682aa-6fd7-11e8-8663-91670a3c080c.png)

**Comment by crisbeto** [comment]
Can you show an example of where you're seeing the error? The buttons look good to me.

**Comment by Corsseir** [comment]
I have posted screenshot.

**Comment by crisbeto** [comment]
Can you also post your markup?

**Comment by Corsseir** [comment]
Ok, I can see now what is wrong. Left top and bottom corners are dark when I attach mat-elevation-z0 class to mat-button like so:
```
<button class="mat-elevation-z0" mat-button color="primary">Renew</button>
```
so it is my fault I guess?

**Comment by josephperrott** [comment]
It looks like you might have something else at play in your styling for you app.  You can see a reproduction [here](https://stackblitz.com/edit/angular-material2-issue-nlomkg?file=app/app.component.html) that does not seem to have the corner issues that you mentioned.
