### ISSUE TITLE
Feature Request: Configurable maximum number of displayed options in Select

### ISSUE THREAD

**Issue by zijianhuang** [angular/material2#11780]
#### feature request:
An input property for defining maximum number of options displayed in the dropdown.

#### What is the expected behavior?
Currently the maximum number is always 5. If I could define 10, maximum 10 items could be displayed, while total number could be 8 or 20.

#### What is the use-case or motivation for changing an existing behavior?

1. When the vertical real-estate is tall enough, displaying more options means less scrolling and quicker select.
2. In some devices, the vertical scrollbar is not displayed until finger touching. This had caused confusion to users who may not know there may be more options hidden. Having more options displayed could reduce such confusion.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
As per Material 6.2.1 and older releases.

**Comment by zijianhuang** [comment]
With HTML, I may use this:
```html
 <select onfocus='this.size=10;' 
onblur='this.size=1;' 
onchange='this.size=1; this.blur();'>
    <option>1</option>
    <option>2</option>
    <option>3</option>
    <option>4</option>
    <option>5</option>
    <option>6</option>
    <option>7</option>
    <option>8</option>
    <option>9</option>
    <option>10</option>
    <option>11</option>
     <option>12</option>
     <option>13</option>
<option>14</option>
<option>15</option>
      <option>16</option>
    <option>17</option>
    <option>18</option>
    <option>19</option>
    <option>20</option>
  </select>
```

However, I would prefer to use mat-select overall.

**Comment by josephperrott** [comment]
Closing as you can control the max number of items that are visible in the select by setting a `max-height` style value for the `mat-select-panel`.

For example

```css
.mat-select-panel {
  max-height: calc(48px * 10);
}
```

**Comment by zijianhuang** [comment]
I should had mentioned I had tried what you @josephperrott had suggested. But it changes nothing. I had also tried other mat-XXXX classes, but at best got fixed height of scrollable area, not more items to be displayed. Please do re-open the case.

**Comment by dubeg** [comment]
@josephperrott It would be an acceptable solution if the mat-select control didn't rely on the constant SELECT_PANEL_MAX_HEIGHT as well. If you override the max-height with a class, the overlay will show up misaligned to the control's clickable area. 

Could we make the constant a variable that we can set in templates?
