### ISSUE TITLE
mat-select change event stopped invoking after 6.2.1 upgrade

### ISSUE THREAD

**Issue by wania2016** [angular/material2#11786]
#### Bug, feature request, or proposal:
mat-select change event stopped invoking after 6.2.1 upgrade

#### What is the expected behavior?
Event handler attached to (change) event should be invoked

#### What is the current behavior?
The Event handler dosen't get invoked

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by crisbeto** [comment]
`mat-select` doesn't have a `change` event, try binding to `selectionChange`.

**Comment by wania2016** [comment]
This is the code which used to work fine before i upgraded to Material  6.2.1. I also tried to rename the event to **selectionChange** , still doesn't trigger the event.
`<mat-form-field>
  <mat-select name="periodFilter" [(value)]="selectedPeriod" (change)="onPeriodSelect($event)">
    <mat-option *ngFor="let period of periodList" [value]="period.id">
      {{period.text}}
    </mat-option>
  </mat-select>
  <mat-hint>
    Show Last
  </mat-hint>
</mat-form-field>`

**Comment by wania2016** [comment]
mat-select did had a **change** event, it's been renamed to **selectionChange** in 6.0.2. I renamed the event name and it started working again. Thanks for your help
