### ISSUE TITLE
mat-menu not scrolled to top on first open

### ISSUE THREAD

**Issue by diminutivesloop** [angular/material2#11790]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When opening a mat-menu with scrollable content the content should be scrolled to the top.

#### What is the current behavior?
When opening a mat-menu with scrollable content for the first time after it is created the content is scrolled down slightly.
![image](https://user-images.githubusercontent.com/667716/41423637-d85a9924-6fc9-11e8-85da-fdf04fdd0e1f.png)

#### What are the steps to reproduce?
https://stackblitz.com/edit/mat-menu-scroll-issue

#### What is the use-case or motivation for changing an existing behavior?
The top-most item in a menu should be fully visible after opening the menu.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 6.0.3
Node: 8.11.1
OS: win32 x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cdk                      6.1.0
@angular/cli                      6.0.3
@angular/material                 6.1.0
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by andrewseguin** [comment]
I'm running into this issue on v7.0.4, except its showing during animation. Looks like the fix resets scrollTop on animation done, but the scroll top is wrong during animation and looks janky

https://stackblitz.com/edit/angular-ej8quc?file=app/menu-overview-example.html

While the menu is animating open, the scroll top is set to 31px and then it resets to 0px once open. 

<img width="522" alt="screen shot 2018-11-17 at 9 53 45 pm" src="https://user-images.githubusercontent.com/22898577/48669198-05f8bb80-eab4-11e8-9233-46ef1a85778f.png">
