### ISSUE TITLE
"Table Sticky" package stops Material Design Examples repo from building

### ISSUE THREAD

**Issue by JGardn-Quest** [angular/material2#11793]
#### Bug, feature request, or proposal:
Once these two files
https://github.com/angular/material2/search?utf8=%E2%9C%93&q=%5Bsticky%5D%3D%22isSticky%28stickyColumns%2C+%27name%27%29%22&type=
were added to the Material Design Examples, ng build fails 

#### What is the expected behavior?
ng build should run, but can't because "table sticky" is missing an import, or can't be used on an ng-container

#### What is the current behavior?
build fails, and this error occurs (which doesn't point to a file)
https://user-images.githubusercontent.com/1308655/41268757-f8f34a58-6dbe-11e8-9491-95900cfdf74b.png

#### What are the steps to reproduce?
Pull from this repo: https://github.com/angular/material.angular.io
Do an npm install and ng build. Above error occurs. 

#### What is the use-case or motivation for changing an existing behavior?
Stops project builds

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6, Material 2

**Comment by josephperrott** [comment]
This issue should be resolved as we have successfully built and deloyed from the material.angular.io repo in the last few days.
