### ISSUE TITLE
Mat SnackBar position error and hide

### ISSUE THREAD

**Issue by pacozevallos** [angular/material2#11795]
I am handling errors with MatSnackBar and I have problems with the position in which the dialog is displayed and it is not hidden automatically.

<img width="1440" alt="captura de pantalla 2018-06-14 a la s 12 57 01" src="https://user-images.githubusercontent.com/21043102/41439733-88b343a8-6ff1-11e8-866d-e2c811c747db.png">

This is a known behavior?

**service.ts**

```
facebookLogin() {
const provider = new firebase.auth.FacebookAuthProvider();
return this.oAuthLogin(provider);
}

private oAuthLogin(provider) {
return this.afAuth.auth.signInWithPopup(provider)
  .then((credential) => {
    this.pushUserData(credential.user)
    this.router.navigate(['/userProfile'])
  })
  .catch(error => {
    this.handleError(error);

  });
}

private handleError(error: Error) {
  console.error(error);
  this.snackBar.open(error.message, this.action, { duration: 1000 });
}
```

**component.ts**

```
facebookLogin() {
  this.auth.facebookLogin()
}
```
When I test it from the same component, everything works normal:

```
openSnackBar() {
this.snackBar.open(this.message, this.action, {
  duration: 500,
});
}
```

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
