### ISSUE TITLE
Bug(mat-tab): Tab Content height snaps between tabs of different heights.

### ISSUE THREAD

**Issue by aflegel** [angular/material2#11797]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When changing tabs with different heights the content div should slide in or out with an animation.

#### What is the current behavior?
The content div snaps to the new height.

#### What are the steps to reproduce?
[StackBlitz ](https://angular-material2-issue-9mnmrd.stackblitz.io) example.

#### What is the use-case or motivation for changing an existing behavior?
Material design specifies elements should never snap to new positions.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.8

#### Is there anything else we should know?
[This](https://github.com/angular/material2/issues/8445) is a related issue, though it is requesting a different solution.

**Comment by josephperrott** [comment]
This can already be done using the `dynamicHeight` input on the tap group, see the docs site [here](https://material.angular.io/components/tabs/overview#dynamic-height)
