### ISSUE TITLE
Default value for Snackbar

### ISSUE THREAD

**Issue by stelone** [angular/material2#11802]
#### What is the expected behavior?
In the documentation of Snackbar it's possible to define default value with provider: 

`{provide: MAT_SNACK_BAR_DEFAULT_OPTIONS, useValue: {duration: 2500}}`

https://material.angular.io/components/snack-bar/overview#setting-the-global-configuration-defaults

#### What is the current behavior?
The value MAT_SNACK_BAR_DEFAULT_OPTIONS doesn't exist.

Maybe the documentation is not up to date and the feature doesn't exist

#### What are the steps to reproduce?
Try to add the default value for Snackbar. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.0, Material 5.2.4, OS WIN7, TypeScript 2.8.1, browser : Chrome

**Comment by crisbeto** [comment]
That injection token was added in Material 6.0.0-beta.4, but you're still on 5.2.0. You have to update 6.0 to be able to use it.
