### ISSUE TITLE
Mat-list-item-content does not receive an ngcontent attribute

### ISSUE THREAD

**Issue by Angelinsky7** [angular/material2#11805]
How can we customize mat-list-item-content (with css for example) ?

Angular + Material :
```
"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^6.2.1",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.2.1",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "rxjs": "^6.0.0",
    "smoothscroll-polyfill": "^0.4.3",
    "zone.js": "^0.8.26"
  },
```

**Comment by epelc** [comment]
For some reason it's not getting the `ngcontent` attributes added to it. You can temporarily work around this by using `ViewEncapsulation.None` on your component.

![image](https://user-images.githubusercontent.com/5204642/41737343-036e6260-755d-11e8-8171-0ca3b1fb0d88.png)

**Comment by Angelinsky7** [comment]
@epelc yes but then we loose everything else...
the workaround that i found was to surround my content with a span/div/etc... and then style that one... but it feels i little bit hackish... and it would seem normal to be able to customize the mat-list-item-content directly, no?

```
<mat-nav-list>
  <a mat-list-item routerLink="" (click)="scroll(page.link)" color="basic" *ngFor="let page of pages">
    <span class="centered" [class.active]="page.order == activeIndex">{{page.name}}</span>
  </a>
</mat-nav-list>
```

**Comment by epelc** [comment]
You scope the styles with an element selector. It’s not too bad but still not the best.

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
