### ISSUE TITLE
md-sidenav-layout hide all my content

### ISSUE THREAD

**Issue by istiti** [angular/material2#1181]
When I use <md-sidenav-layout> all my content is hidden, why ?!!

In this GIF you can check my litle strucutre od DOM (ide + chrome inspector)

![sidenav in root component](https://cloud.githubusercontent.com/assets/2789203/18264734/4fa6f7e4-7412-11e6-8cd3-ee7363fdb55b.gif)

**Comment by jelbourn** [comment]
Not enough information. Please follow the issue template.
