### ISSUE TITLE
cdk-describedby-message-container appears twice with SSR / Angular Universal

### ISSUE THREAD

**Issue by Trysor** [angular/material2#11817]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

For cdk-describedby-message-container to appear only once in DOM

#### What is the current behavior?

It appears twice; appears first in the SSR-rendered output by Angular Universal, and then again after the SPA has fully loaded.

#### What are the steps to reproduce?

1. Create an Angular Universal application with material / CDK
2. Create component which causes describedby messages to be created
3. Launch the Universal application

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular CLI: 6.1.0-rc.0
Node: 10.2.1
OS: win32 x64
Angular: 6.1.0-beta.1

angular-devkit 0.7.0-rc.0     
angular/cdk 6.2.1
angular/material 6.2.1
ngtools/webpack                  6.1.0-rc.0
schematics/angular               0.7.0-rc.0
schematics/update                0.7.0-rc.0
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.9.2

nguniversal/common 6.0.0
nguniversal/express-engine 6.0.0
nguniversal/module-map-ngfactory-loader 6.0.0

**Comment by ericel** [comment]
I have the same behavior on my universal build. The Dailog box shows twice as seen here:
![universal-material-build](https://user-images.githubusercontent.com/16863721/41536161-a44cfd96-72b9-11e8-83bb-012b9fc5a7ff.PNG)

**Comment by Showtim3** [comment]
@jelbourn @mmalerba @crisbeto @vivian-hu hey guys, I'll be overwhelmed if i get a reply on this thread. I am using angular universal for SSR and i am still getting this issue. Any help guys?
