### ISSUE TITLE
md-tab explicit tabindex

### ISSUE THREAD

**Issue by dhilt** [angular/material2#11814]
#### Bug, feature request, or proposal:

Feature request.

#### What is the expected behavior?

I want to be able to set mat-tabs tabindex values declaratively. 

#### What is the current behavior?

tabindex value of the first md-tab item is 0 by default and others are -1 and I can't change it.

#### What is the use-case or motivation for changing an existing behavior?

1. This came from keyboard accessibility requirements that have explicit tabindex implementation. For example, I have one tabindexed block before mat-tab-group (say, 300 - 308) and another one after (500-504). And I need the first (active) md-tab to have tabindex 400.

2. Another use case is to have a possibility to switch between md-tabs by TAB key pressing.

**Comment by josephperrott** [comment]
Closing as you are able to set the current tab index using the `selectedIndex` attribute on `mat-tab-group` as seen [here](https://stackblitz.com/edit/angular-material2-issue-nnnvtt?file=app%2Fapp.component.html)

**Comment by dhilt** [comment]
@josephperrott This does not solve native `tabindex` attribute issue. No matter of `selectedIndex` on `mat-tab-group` the real `tabindex` on real DOM elements would be 0 (if active) or -1 (inactive). And explicit tabindex keyboard accessibility implementation **would be broken**.

Also, it does not help with `md-tabs` TAB key switching (per -1 `tabindex` attribute value if inactive). Maybe this one should be extracted into a separate issue.

If you have no plans to support native tabindexes manipulation, the issue could stay closed with appropriate comment. Currently it seems there is some misunderstanding...

**Comment by pegues** [comment]
Not good to affect native tabindex behavior. This affects accessibility.
