### ISSUE TITLE
CDK documentation wrong [Portal]

### ISSUE THREAD

**Issue by djleonskennedy** [angular/material2#11825]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
attach(), detach() should return a Promise

#### What is the current behavior?
attach(), detach() do not return a Promise

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
According to documentation attach(), detach() return a Promise

![image](https://user-images.githubusercontent.com/8366455/41542453-abbe2af0-731d-11e8-8614-1b5f5e18c97f.png)

https://stackblitz.com/edit/angular-cdk-portal-template-ygs7q1?file=app/app.component.ts
<br/>

throws error: ERROR TypeError: this.portalHost.attach(...).then is not a function

#### What is the use-case or motivation for changing an existing behavior?
We have behavior that requires as to run mechanism only when component is attached

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular, material 6.x.x

**Comment by crisbeto** [comment]
I've submitted a PR to fix the docs. Since attaching the portals is synchronous, you can do your extra work after `attach` is called.

**Comment by djleonskennedy** [comment]
@crisbeto thank you
