### ISSUE TITLE
Expose CDK testing module

### ISSUE THREAD

**Issue by danguilherme** [angular/material2#11829]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
When using the overlay, I want to test if it is closed after pressing ESCAPE. CDK has helper functions to dispatch keyboard events from an specific element, this way I can use the helpers to quickly simulate an ESCAPE press from `document.body` (just like it's done in the [Dialog tests](https://github.com/angular/material2/blob/abc3d38c57146443c848d5ba26fd2fab8ca185d6/src/cdk-experimental/dialog/dialog.spec.ts#L205)):

https://github.com/angular/material2/blob/abc3d38c57146443c848d5ba26fd2fab8ca185d6/src/cdk-experimental/dialog/dialog.spec.ts#L200-L210

#### What is the current behavior?
`@angular/cdk/testing` module is not exposed, so none of the helper functions can be used.

#### What are the steps to reproduce?
In a project that has CDK as dependency, add the following import:

```typescript
import { dispatchKeyboardEvent } from '@angular/cdk/testing';
```

It fails with the message `[ts] Cannot find module '@angular/cdk/testing'.`.

#### What is the use-case or motivation for changing an existing behavior?
It's easier to use the already existing event creation/dispatch code when writing user interaction tests.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Angular 6.0.4
- `@angular/cdk` 6.2.1

**Comment by jelbourn** [comment]
See https://github.com/angular/material2/issues/9531#issuecomment-359969115

Someone we'd like to do testing utilities, but current it is just our own in-project testing utilities.
