### ISSUE TITLE
MatFormField label and input text alignment incorrect

### ISSUE THREAD

**Issue by gtranter** [angular/material2#11831]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The placeholder label when the field is empty, and the input text when there is no floating label (or when appearance is outline) should be vertically centered in the field.

#### What is the current behavior?
Alignment varies with appearance style and label style, but only seems to be right in two specific use cases - wrong the rest of the time.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-h1lpum-ibhaxe?embed=1&file=app/form-field-appearance-example.html

#### What is the use-case or motivation for changing an existing behavior?
Meet Material Design specifications.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.5, Angular Material 6.2.1

#### Is there anything else we should know?
Details:

The placeholder text when there is no input, and input text when there is no floating label, are always too low **except** in the following use cases:

- Fill appearance with automatic floating label
- Outline appearance with automatic floating label when there is no value so the label is at rest

Also, it looks like the prefix and suffix icons are always slightly too low, so even when the alignment is correct (labels and values vertically centered), it doesn't look quite right.

**Comment by motabass** [comment]
Text-based prefix and suffix are also misaligned in appearance="outline":
https://stackblitz.com/edit/material2-form-field-prefix-appearance

**Comment by kyleraymorgan** [comment]
I can confirm that this is still an issue. It's been 4 months since this issue has been reported. Is this on anybody's to-do list?

**Comment by mmalerba** [comment]
Text prefix/suffixes are no longer shown at all in the Material spec and the icon prefix/suffixes are shown aligned the way Angular Material has implemented: https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Ejie5ILk2-eAB9wBRFG93aJtYV7gJtJV%2Ftextfields-annotations-1.png

We may add text-masking in the future which could be used in place of the prefix/suffix for a similar effect: https://github.com/angular/material2/issues/7645

**Comment by gtranter** [comment]
Yet again - you guys miss the boat and excuse yourselves from the problem by finding a gap in the spec. A lot of what you do is fantastic, but occasionally you really drop the ball, as you have been with text fields for quite a while now. Bottom line - they look shoddy under some conditions.

**Comment by gitkumi** [comment]
Here's a work around to this issue.

`::ng-deep .your-form-class .mat-form-field-prefix,
::ng-deep .your-form-class .mat-form-field-suffix {
  top: 0!important;
}`

**Comment by gtranter** [comment]
@gitkumi - Thanks, but your suggestion makes things worse IMO. It moves the prefix/suffix to align with the text, but it's the text that is out of alignment, not the prefix/suffix. The result is that everything is raised above center in the outline box.

**Comment by gitkumi** [comment]
@gtranter  - you're right. 

Here you go.
`::ng-deep .your-form-class .mat-form-field-infix {
  top: .25em!important;
}`

**Comment by gtranter** [comment]
@gitkumi Thanks again for trying but it's a little more complicated than that because you have to avoid moving the floating label along with the input field. (And also it's **bottom**: .25em.)

```
.mat-form-field-appearance-outline .mat-form-field-infix .mat-input-element { 
  position: relative; 
  bottom: .25em; 
}
```

And of course, the other appearance styles need different workarounds.

**Comment by mrtcmn** [comment]
![image](https://user-images.githubusercontent.com/10677910/48411608-10812100-e753-11e8-8e0e-a7008d129e90.png)


  .mat-icon
    width: 1.3em !important
    position: relative !important
    bottom: -5px !important

Overriding css could be temporary solution. But i don't recomend.

That needs to more responsive solution.

**Comment by samuelzapote** [comment]
I've come accross this problem as well, the solution that has worked for me is a mixture of some existing solutions and some. If there is a way to make this cleaner let me know.

`.mat-form-field-infix {
  top: -0.25em;
}

.mat-form-field-appearance-outline .mat-form-field-prefix, .mat-form-field-appearance-outline .mat-form-field-suffix {
  top: -0.25em !important;
}

.mat-form-field-appearance-outline .mat-form-field-label {
  margin-top: 0em;
}

.mat-form-field:not(.mat-form-field-appearance-legacy) .mat-form-field-suffix .mat-icon-button {
  top: 0.8em;
}`

![Screenshot_2019-04-15 Iautoscars](https://user-images.githubusercontent.com/17343222/56153252-56991580-5f7b-11e9-992a-e61020026083.png)

![Screenshot_2019-04-15 Iautoscars(1)](https://user-images.githubusercontent.com/17343222/56153305-74667a80-5f7b-11e9-93eb-c62e3f1ed7f4.png)

![Screenshot_2019-04-15 Iautoscars(2)](https://user-images.githubusercontent.com/17343222/56153312-79c3c500-5f7b-11e9-9df4-f85403da7e19.png)

**Comment by roalonso** [comment]
> Text prefix/suffixes are no longer shown at all in the Material spec and the icon prefix/suffixes are shown aligned the way Angular Material has implemented: https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Ejie5ILk2-eAB9wBRFG93aJtYV7gJtJV%2Ftextfields-annotations-1.png
> 
> We may add text-masking in the future which could be used in place of the prefix/suffix for a similar effect: #7645

@mmalerba it was readded to the spec again around November-December. Check:
https://material.io/design/components/text-fields.html#filled-text-field

Can you reopen this?
