### ISSUE TITLE
How do I change the padding-bottom of select component?

### ISSUE THREAD

**Issue by kinmy** [angular/material2#11848]
.mat-form-field-appearance-legacy .mat-form-field-wrapper {
    padding-bottom: 1.25em;
}

<style>…</style>
.mat-form-field-appearance-legacy .mat-form-field-wrapper {
    padding-bottom: 1.25em;
}
<style>…</style>
.mat-form-field-wrapper {
    position: relative;
}
<style>…</style>
.mat-form-field-wrapper {
    padding-bottom: 1.34375em;
}
<style>…</style>
.mat-form-field-wrapper {
    padding-bottom: 1.34375em;
}

**Comment by crisbeto** [comment]
This isn't something that we have an API for. You should be able to do it by providing your own styles that override the select's defaults.

**Comment by Angelinsky7** [comment]
Hi @crisbeto,
I've got the same question, in one component, in only one place i would like to remove the `padding-bottom` of the `mat-form-field-wrapper` what is the correct intended way of doing this ?
It seems to me that creating a complete theme only to edit and customize a property of one input is not a good way to handle those kind of problem...
