### ISSUE TITLE
mat-slider-toggle not using correct color. (ignoring hue)

### ISSUE THREAD

**Issue by robindijkhof** [angular/material2#11854]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-slider-toggle should use the exact same color as the primary color.

#### What is the current behavior?
It is ignoring the hue/tint (not sure what it is called)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://github.com/robindijkhof/mat-slide-toggle
![image](https://user-images.githubusercontent.com/22224763/41654615-4fba3c62-748a-11e8-81fb-ed4a65e6ae66.png)

While my primary color is: `$app-primary: mat-palette($mat-blue, 900);`. it is ignoring the 900

#### What is the use-case or motivation for changing an existing behavior?
Incorrect behaviour

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Material 6.3.0

**Comment by DevVersion** [comment]
Previously, with the old Material Design guidelines, the hue colors were explicitly defined.

```ts
checked = Hue 500 (light);
checked = Hue 200 (dark)
```

I'm not sure whether it makes sense to use the `default` hue that can be customized by the user here. 

The slide-toggle won't always look good in dark themes by default, meaning that the user needs to customize his palette and adjust the `default` hue.

---

However I see that there needs to be a way to match those colors. One possibility would be to default to the current logic if the `default` hue is not changed to a different value (e.g. from 500 to 900)

**Comment by robindijkhof** [comment]
@DevVersion In my opinion it make sense to use the default hue. That's because it it a formcontrol and all other formcontrols AFAIK do use the hue.

**Comment by DevVersion** [comment]
I've mentioned in the team meeting and since it would be a visually breaking change we don't want to switch to the default hue yet.

The new design specifications are not very explicit about the proper hue, but the old version was. I will continue researching about the proper hue. Just making clear that this will be a low priority.
