### ISSUE TITLE
"Expression has changed" error when using *ngIf and [stepControl]

### ISSUE THREAD

**Issue by tonysamperi** [angular/material2#11857]
#### Bug, feature request, or proposal:
When having dynamic steps on which there is a [stepControl] attr, the `Expression has changed after it has been checked` error is triggered. I don't see any way to avoid this.

#### What is the expected behavior?
It handles the creation of an inner component

#### What is the current behavior?
I get the error as described above.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/mat-step-error

#### What is the use-case or motivation for changing an existing behavior?
May be problematic in the future

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 
<pre>
<code>
@angular/cdk: 5.2.5
@angular/cli: 1.7.4
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.4.9
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.9.2
webpack: 3.11.0
</code>
</pre>
#### Is there anything else we should know?
At this time...no.

**Comment by julianobrasil** [comment]
You can change your approach a little bit:
```ts
  frmStepOne: FormGroup;
  frmStepTwo: FormGroup;
  frmStepThree: FormGroup;
  frmStepFour: FormGroup;

  stepChangeCallback(event: StepperSelectionEvent): void {
    if (event.selectedIndex === 1 && event.selectedIndex > event.previouslySelectedIndex) {
      this.challengeSteps = [true];
    }

    setTimeout(() => {
      this.stepOneComponent ? this.frmStepOne = this.stepOneComponent.frm : this.frmStepOne = null;
      this.stepTwoComponent ? this.frmStepTwo = this.stepTwoComponent.frm : this.frmStepTwo = null;
      this.stepThreeComponent ? this.frmStepThree = this.stepThreeComponent.frm : this.frmStepThree = null;
      this.stepFourComponent ? this.frmStepFour = this.stepFourComponent.frm : this.frmStepFour = null;
    });
  }
```

**Comment by tonysamperi** [comment]
Timeout ==> horrible approach. Timeout is never the solution.
Actually I solved the problem a few hours after posting this issue...
I just haven't had the time to post my solution.

**The real solution**

<pre><code>
     private _frmStepThree: FormGroup = null;
     get frmStepThree() {
        return this._frmStepThree;
    }

     stepChangeCallback(event: StepperSelectionEvent): void {

        if (event.selectedIndex === 1 && event.selectedIndex > event.previouslySelectedIndex) {
            // DO SOME STUFF HERE
            if (this.stepThreeComponent && this.stepThreeComponent.frmStepThree) {
                this._frmStepThree = this.stepThreeComponent.frmStepThree;
            }
        }
    }
</code></pre>

**Comment by choopage** [comment]
This solution works too 
https://stackoverflow.com/questions/48498966/angular-material-stepper-component-for-each-step
