### ISSUE TITLE
[MatSelect] Order in multiple mode

### ISSUE THREAD

**Issue by JesseHeisenberg** [angular/material2#11871]
#### Bug, feature request, or proposal:
feature 

#### What is the expected behavior?
Using MatSelect with multiple selection,(selectionChange) will give the result which sort by user selected order.
#### What is the current behavior?
When using MatSelect with multiple selection,`(selectionChange)` will give the result which sort by selected options order.I think this order should defined by developer,such as sort by user select or default options order.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Make select value sort rules defined by developer.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.0.0,
Material: 6.0.1,
OS: win10,
TypeScript: 2.7.2,
Browsers: Chrome@67.0.3396.87

**Comment by crisbeto** [comment]
You should be able to sort the values yourself when you get it in the selection change event.

**Comment by yooRabbit** [comment]
@crisbeto Yes, I have fixed by this way.But in `<mat-selcect #select></mat-select>` , It's only way to overwrite the text by `select._elementRef.nativeElement.firstChild.firstChild.children[0].innerText = 'b,a,c'`. In fact, I'm already finish this case,just give some advice for better component.
