### ISSUE TITLE
Using stepper throws an exception "ERROR TypeError: _this._driver.validateStyleProperty is not a function"

### ISSUE THREAD

**Issue by OsamaAwniHamdan** [angular/material2#11875]
#### Bug, feature request, or proposal:
I am using angular 6, I installd the material and I am trying to use the stepper component, like ths:
` <mat-horizontal-stepper>
    <mat-step label="step1">step1</mat-step>
    <mat-step label="step2">step2</mat-step>
  </mat-horizontal-stepper>`
the app.module imports is like this:
` imports: [
    BrowserModule,
    BrowserAnimationsModule,
    RouterModule.forRoot(appRoutes) ,
    FormsModule, HttpClientModule ,
    FormWizardModule ,
    ArchwizardModule,
    MatStepperModule
  ],`
but I got the following exception:
`NewReqComponent.html:16 ERROR TypeError: _this._driver.validateStyleProperty is not a function
    at browser.js:844
    at Array.forEach (<anonymous>)
    at browser.js:843
    at Array.forEach (<anonymous>)
    at AnimationAstBuilderVisitor.push../node_modules/@angular/animations/fesm5/browser.js.AnimationAstBuilderVisitor._validateStyleAst (browser.js:840)
    at AnimationAstBuilderVisitor.push../node_modules/@angular/animations/fesm5/browser.js.AnimationAstBuilderVisitor.visitStyle (browser.js:780)
    at AnimationAstBuilderVisitor.push../node_modules/@angular/animations/fesm5/browser.js.AnimationAstBuilderVisitor.visitState (browser.js:678)
    at browser.js:657
    at Array.forEach (<anonymous>)
    at browser.js:655`

I tried to debug the issue, I found there is a mismatch between the functions parameters:
![image](https://user-images.githubusercontent.com/35865421/41715316-b11f6fd2-755b-11e8-8dbc-581b34328762.png)
the bodyNode contains the driver value and the _driver contains the normlizer and the normlizer is empty
![image](https://user-images.githubusercontent.com/35865421/41715392-f3c76024-755b-11e8-901c-df6813a954bd.png)

**Comment by pemberton** [comment]
I have the same issue with mat-sidenav-container component.

**Comment by GuillaumeMilani** [comment]
Same here with map-paginator

**Comment by mscard02** [comment]
same issue with header

**Comment by doubleqwerty** [comment]
same for mat-form-field

**Comment by ashokars** [comment]
same here for mat-form-field. Any fix so far

**Comment by mscard02** [comment]
temp fix:
go to packages.json -> dependencies
"@angular/animations": "6.0.5",
npm install

**Comment by OsamaAwniHamdan** [comment]
> temp fix:
go to packages.json -> dependencies
"@angular/animations": "6.0.5",
npm install

I tried that but it does not work with me.
Any one have it work?

**Comment by GuillaumeMilani** [comment]
After upgrading Angular to 6.0.6 the problem seems to be fixed

**Comment by nourhannaguib** [comment]
how can i update to Angular 6.0.6 i used the ng update command but it is not working

**Comment by GuillaumeMilani** [comment]
I don't know if there is a more secure or official way to do this, what I did is :
- Replace the version of each `@angular/` dependency in `packages.json` by 6.0.6 (previously 6.0.3 in my case)
- [Optional] remove `node_modules/`folder
- `npm install`

**Comment by magnusrambech** [comment]
> I have the same issue with mat-sidenav-container component

Same issue

>Replace the version of each @angular/ dependency in packages.json by 6.0.6 (previously 6.0.3 in my case)
-[Optional] remove node_modules/folder
-npm install

This did not work for me.  Any fix yet?

**Comment by Chan4077** [comment]
You can also try updating via `npm update`.

**Comment by pemberton** [comment]
> temp fix:
go to packages.json -> dependencies
"@angular/animations": "6.0.5",
npm install

work for me! thank you!

**Comment by hidaytrahman** [comment]
I have updated angular and also tried both solution provided by @GuillaumeMilani
but still getting same issue

**Comment by OsamaAwniHamdan** [comment]
upgrading angular solve the issue.
Thanks to  @GuillaumeMilani

**Comment by josephperrott** [comment]
As noted above, it appears that the @angular/animations package needs to be updated for your project.

**Comment by allnulled** [comment]
I am so sorry that we have to learn your shit... but so sorry... I liked Angular.js. But this has become insane for developers. I have just scraped your Angular 6 documentation. I got a PDF of 1000 pages. Insane.

**Comment by yxz0248** [comment]
Just let your material version  as same as your angular version.

**Comment by vicatcu** [comment]
Sorry to resurrect, but any chance this has come back in "@angular/animations": "6.0.7" + "@angular/material": "6.3.2"?

**Comment by lonnenjunior** [comment]
I'm still facing this problem
`"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/cdk": "^6.0.0",
    "@angular/material": "^6.0.0",
    "hammerjs": "^2.0.8"
  }`
When I downgrade animations to version 6.0.5 it works. But I don't think that a downgrade is a proper solution. Are there any other solutions for this?
