### ISSUE TITLE
Toolbar dense mode

### ISSUE THREAD

**Issue by DevVersion** [angular/material2#11878]
Support for dense mode in toolbars.

![image](https://user-images.githubusercontent.com/4987015/41727717-52d7b96a-7575-11e8-89b5-2ed1d7352d8b.png)

I thought initially about having an input for the `mode`.

```html
<mat-toolbar mode="dense">Dense</mat-toolbar>
```

The `prominent` mode that is also mentioned in the specifications can be archived by just having **two** toolbar rows. This should be maybe documented and demonstrated in an example.

In regards to the scrolling behavior for toolbars: See #4760

**Comment by gtranter** [comment]
Having an input for something that has only one possible option seems tedious. It would be like using `<input functionality="disabled">` instead of just `<input disabled>` for example. I'd prefer to see this as:

```
<mat-toolbar dense>Dense</mat-toolbar>
```

**Comment by DevVersion** [comment]
Agreed with that. Even though there should be some way to toggle it dynamically.

```html
<mat-toolbar dense></mat-toolbar>
<mat-toolbar [dense]="binding"></mat-toolbar>
```

**Comment by DevVersion** [comment]
Closing this as density levels will be added as part of #4597. I initially thought that we could just have the density support on the toolbar since it doesn't involve a lot of changes, but there will be a more generic approach that affects not only a single component.
