### ISSUE TITLE
Dialog over full screen

### ISSUE THREAD

**Issue by NashIlli** [angular/material2#11887]
#### Bug, feature request, or proposal:
When I am on full screen (function of Full Screen Api) and I call open() to a mat dialog, the dialog doesn't render over the div on full screen but instead it is redered behind. When I exit of full screen, the dialog is showed.  

#### What is the expected behavior?
I expect that the dialog is renderized over the container elemente that trriger its open method.

#### What is the current behavior?
Currently, the dialog is renderized behid the full screen div. 

#### What are the steps to reproduce?
Editor: https://stackblitz.com/edit/angular-material2-issue-sgytlb
App: https://angular-material2-issue-sgytlb.stackblitz.io (to full screen functionality)

Click on "Full screen" button. 
Click on "open dialog" (the dialog doesn't show)
Press "esc" to exit full screen. Then, the dialog appears.

**Comment by julianobrasil** [comment]
@NashIlli, it seems you've posted the wrong link.

**Comment by NashIlli** [comment]
It's okay. 
![whatsapp image 2018-06-21 at 9 59 12 pm](https://user-images.githubusercontent.com/6954280/41752652-10af5f8c-759f-11e8-8d65-f04358cd2a4e.jpeg)

**Comment by NashIlli** [comment]
Added editor link! @julianobrasil thanks!

**Comment by crisbeto** [comment]
If you want to use overlay in a fullscreen element, you have to use the `FullscreenOverlayContainer`. [See the "Full-screen overlays" section in the docs](https://material.angular.io/cdk/overlay/overview#full-screen-overlays).
