### ISSUE TITLE
mat-table must have tbody we need it writing code not just in the output

### ISSUE THREAD

**Issue by denek01** [angular/material2#11897]
#### Bug, feature request, or proposal:

We need a container html element for the draggable events and tbody is not in the mat-table. When we add, no data comes.
div mat-tbody <---------- we need this.
   div mat-row /div
/div

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
