### ISSUE TITLE
2.0.0-alpha.8-1 breaks webpack vendors.ts entry point

### ISSUE THREAD

**Issue by RAlfoeldi** [angular/material2#1190]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
App starts

#### What is the current behavior?
App doesn't start

#### What are the steps to reproduce?
Update to angular rc.6 and material alpha.8-1

#### Which versions of Angular, Material, OS, browsers are affected?
angular@2.0.0-rc.6
material@2.0.0-alpha.8-1
mac os x 
chrome

#### Is there anything else we should know?
![screen shot 2016-09-07 at 09 12 20](https://cloud.githubusercontent.com/assets/7020711/18303016/38ea5f18-74db-11e6-91de-9ae14a96b84e.jpg)
![screen shot 2016-09-07 at 09 13 03](https://cloud.githubusercontent.com/assets/7020711/18303036/543295a6-74db-11e6-84f8-92c143bf1176.jpg)

App is being built with webpack and run with webpack-dev-server. 

After the exception, everything goes down the drain. (webpack can't find the module, that throws exception etc.)

Edit: I did my homework... nothing else is mentioned in the changelog.
![screen shot 2016-09-07 at 09 18 25](https://cloud.githubusercontent.com/assets/7020711/18303189/1b3e20a2-74dc-11e6-9205-032cb91deee0.jpg)

**Comment by Maxouhell** [comment]
I had the same issue. 
I have removed all others imports and clean my component (now it's just show hello-world).

I didn't have this error anymore, but i have an other : `Error: Error: Unexpected value '[object Object]' exported by the module 'SharedModule'`

**Comment by RAlfoeldi** [comment]
Including material packages in webpack vendors.ts cause the mentioned exception. Commenting taking them out "solves" the problem. But this cannot be the long term solution. 

From webpack.js (config)
![screen shot 2016-09-07 at 18 16 06](https://cloud.githubusercontent.com/assets/7020711/18319734/4c751810-7527-11e6-82f9-8e7cef8f6e8b.jpg)

vendors.ts: (causes problem described)
![screen shot 2016-09-07 at 18 16 21](https://cloud.githubusercontent.com/assets/7020711/18319759/6fe16b50-7527-11e6-96c0-3372d680738e.jpg)

vendors.ts: ("works")
![screen shot 2016-09-07 at 18 16 50](https://cloud.githubusercontent.com/assets/7020711/18319788/8c602b5e-7527-11e6-8c66-8cf77ec164bc.jpg)

**Comment by RAlfoeldi** [comment]
Solution: change /button/button to /button. Repeat.

(Venting: arrgghhh... Dear Angular Team, Please!!!! mention changes like these.)

![screen shot 2016-09-07 at 18 38 20](https://cloud.githubusercontent.com/assets/7020711/18320481/55196f0e-752a-11e6-9031-e16a57d6066d.jpg)

**Comment by jelbourn** [comment]
@RAlfoeldi that definitely should have been mentioned in the changelog; adding it now in #1199
