### ISSUE TITLE
unable to create horizontal scrollable mat-chip-list

### ISSUE THREAD

**Issue by ThunderRoid** [angular/material2#11915]
#### Bug
`mat-chip-list` doesn't respect css `flex` property

#### What is the expected behavior?
`mat-chip` should display in a horizontal scrollable layout

#### Example
[stackblitz](https://stackblitz.com/edit/share-angular-chips?file=app%2Fchips-stacked-example.scss)

**Comment by leixus** [comment]
这是极好的

**Comment by josephperrott** [comment]
From looking at your reproduction it looks to be that the issue is you are not targeting the `.mat-chip-list-wrapper` container div.  You can see a working fork of your stackblitz [here](https://stackblitz.com/edit/share-angular-chips-q8qas4?file=app%2Fchips-stacked-example.scss)

**Comment by ThunderRoid** [comment]
Why r u using `ViewEncapsulation.None`  doc says - "Don't provide any template or style encapsulation."

But can you explain it a little more

**Comment by ThunderRoid** [comment]
@josephperrott Why r u using `ViewEncapsulation.None`  doc says - "Don't provide any template or style encapsulation."

But can you explain it a little more.

More specifically, why do we have to use it here?

**Comment by elie222** [comment]
It allows you to override the styles of the child components.
