### ISSUE TITLE
Multi-line list items not showing

### ISSUE THREAD

**Issue by m0wh** [angular/material2#11923]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I should see some list items with two lines each

#### What is the current behavior?
I don't see anything

#### What are the steps to reproduce?
my.component.html :

```html
<mat-list>
  <mat-list-item>
    <mat-icon matListIcon>folder</mat-icon>
    <h4 matLine>Main Line</h4>
    <p matLine>Secondary line</p>
  </mat-list-item>

  <mat-list-item>
    <mat-icon matListIcon>folder</mat-icon>
    <h4 matLine>Main Line</h4>
    <p matLine>Secondary line</p>
  </mat-list-item>

  <mat-list-item>
    <mat-icon matListIcon>folder</mat-icon>
    <h4 matLine>Main Line</h4>
    <p matLine>Secondary line</p>
  </mat-list-item>

  <mat-list-item>
    <mat-icon matListIcon>folder</mat-icon>
    <h4 matLine>Main Line</h4>
    <p matLine>Secondary line</p>
  </mat-list-item>
</mat-list>

```

Now when I comment each second line, all works, but no way to display two lines.
Note that icons are always well displayed

### Versions
```
"@angular/material": "^6.2.1"
```
This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 6.0.7.

#### Thanks !

**Comment by josephperrott** [comment]
Can you provide a reproduction of your issue?  Based [this stackblitz](https://stackblitz.com/edit/angular-material2-issue-6aepmy?file=app/app.component.html), it looks like it working as expected.

**Comment by m0wh** [comment]
Okay, i've just restarted a blank project and all worked fine.
I have no error thrown in the problematic project, so I don't know where to look at...

**Comment by m0wh** [comment]
Okay I found the source of the error !
I looked into the compiled html in the inspector :

```html

<mat-list-item _ngcontent-c10="" class="mat-list-item mat-2-line">
  <div class="mat-list-item-content">
    <div class="mat-list-item-ripple mat-ripple" mat-ripple="" ng-reflect-trigger="[object HTMLElement]" ng-reflect-disabled="false"></div>
    <mat-icon _ngcontent-c10="" class="mat-list-icon mat-icon material-icons" matlisticon="" role="img" aria-hidden="true">folder</mat-icon>
    <div class="mat-list-text">
      <h4 _ngcontent-c10="" class="mat-line" matline="">Main Line</h4>
      <p _ngcontent-c10="" class="mat-line" matline="">Secondary line</p>
    </div>
  </div>
</mat-list-item>

```

The "Secondary line" \<p\> has the ``_ngcontent-c10`` attribute. In the inspector I can see and disable this:
```css
p[_ngcontent-c10] {
  height: 150vh;
}
```
This selector is alone in ``<inline stylsheet #11>``
Why is this selector active here and not on the stackblitz ?

**Comment by m0wh** [comment]
Okay i'm done
I wrote this css rule in my component stylesheet...
Sorry for that 😕
