### ISSUE TITLE
Is this the demo for this project ?

### ISSUE THREAD

**Issue by ashishsajwan** [angular/material2#1193]
[Demo for angular 2 material https://justindujardin.github.io/ng2-material] (https://justindujardin.github.io/ng2-material/#/) ??
i stumbled upon this url.. can any one confirm if this demo is build using this same project ??

**Comment by m0t0r** [comment]
@ashishsajwan no, `ng2-material` is a different project. Github issues are not for questions, please follow issues template for bugs, feature requests, or proposals. Questions should be asked on gitter, mailing list, etc.

**Comment by jelbourn** [comment]
We don't yet have a public demo site for material2 yet, but you can see a snapshot of our development app here: https://material2-test.firebaseapp.com/
(slow because dev mode)

**Comment by ashishsajwan** [comment]
thank you guys for clearing out things..
