### ISSUE TITLE
The website visitor have to clear the browser cache to view the page.

### ISSUE THREAD

**Issue by Domvel** [angular/material2#11949]
Sometimes - maybe on every website update - I have to clear my cache to view the website. Otherwise the angular files are not found (404) because outdated. I see a blank page in error case.
I think this is a known issue. I hope so. But just wanted to trigger this issue anyway.
We have the same problem with out own angular website. Idk who to fix it for sure.
Users of our page see the outdated version from thers cache. 

https://material.angular.io

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Comment by m-henderson** [comment]
I am having this issue as well

**Comment by Domvel** [comment]
This is maybe an Angular issue.
