### ISSUE TITLE
rc6 modal improvement

### ISSUE THREAD

**Issue by repetier** [angular/material2#1194]
#### Bug, feature request, or proposal:

proposal

#### What is the expected behavior?

easy modal popups

#### What is the current behavior?

requires module for each popup

Your solution for popups is way to complicated. Had the same issue and this post (not from me) helped me making it much simpler. Essentially use ComponentFactoryResolver and put all potetial popups in your module defintion under 
    entryComponents:[
       PopupComp
    ]
and you can throw away the one module per popup.

https://blog.thecodecampus.de/angular-2-dynamically-render-components/

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/1180
