### ISSUE TITLE
Schematics collection.json is invalid JSON

### ISSUE THREAD

**Issue by hansl** [angular/material2#11957]
The line [here](https://github.com/angular/material2/blob/4166d168a180aa70dcb72ec15570dc54ac0a2c39/src/lib/schematics/collection.json#L31) has an unfinished quotation;

```json
      "aliases": [ "material-nav", "materialNav ]
```

**Comment by jelbourn** [comment]
@hansl closing this because you are on vacation!

**Comment by ladyleet** [comment]
@jelbourn bro. #canteven

**Comment by jelbourn** [comment]
Joking aside, this is fixed in #11839
