### ISSUE TITLE
[Table] sticky columns doesn't work as intended when inside mat-sidenav-content

### ISSUE THREAD

**Issue by IlCallo** [angular/material2#11950]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Sticky columns shall be "over" normal columns (aka have a greater z-index)

#### What is the current behavior?
When the mat-table is inside a sidenav, sticky columns get `z-index: 1`, which is the same `z-index` provided of the mat-sidenav-content element.
Graphically the columns are show in front of the non-sticky ones, but when I try to inspect the element I can see that the non-sticky are logically placed at the top, capturing mouse interaction (click, mousedown etc).

#### What are the steps to reproduce?
See previous point,

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.6
Material 6.3.1

#### Is there anything else we should know?
I saw that there is some kind of "z-index" detection on sticky columns management before deciding what is the best value, this issue should probably by addressed there

**Comment by SergeyMNet** [comment]
I found solution, just update to:

"@angular/cdk": "6.4.7"
"@angular/material": "6.4.7"

**Comment by IlCallo** [comment]
It seems I cannot reproduce the faulty behaviour anymore, so I guess it has been addressed at some point.
Gonna close the issue
