### ISSUE TITLE
https://material.angular.io/ is down

### ISSUE THREAD

**Issue by deanapeterson** [angular/material2#11965]
https://material.angular.io/ is down.

**Comment by mtrdp642** [comment]
The site is up - [here's](https://github.com/angular/material.angular.io/issues/436#issuecomment-390924245) a workaround for getting it to load in Chrome.

**Comment by sircuri** [comment]
That is not the issue. I'm getting 404 errors. Solution suggested from that other ticket is not going to fix that:

https://material.angular.io/runtime.6afe30102d8fe7337431.js (404)

**Comment by ThunderRoid** [comment]
Happened to me thrice this week.

**Comment by crisbeto** [comment]
Closing as a duplicate of #11745. Usually this can also be fixed by clearing your cache.

**Comment by 24hours** [comment]
This issue seems to caused by cached index.html / service worker. imho this is bad bad user experience. We added no-cache flag on index.html, forcing refresh on client when 404 on chunk.js file.
