### ISSUE TITLE
Issue: mdc-datetime-picker is not working properly in RTL direction.

### ISSUE THREAD

**Issue by MichaelJohny** [angular/material2#11964]
#### Bug, feature request, or proposal:
- Bug.

#### What is the expected behavior?
- Date time picker should be drawn in RTL direction as shown below:

![image](https://user-images.githubusercontent.com/19435804/42037634-30a10508-7ae9-11e8-9247-e0a3c0a433a4.png)

#### What is the current behavior?
- In RTL direction, Date time picker is not aligned properly as shown below:

![image](https://user-images.githubusercontent.com/19435804/42037448-ba000926-7ae8-11e8-807c-290e15925a3c.png).

#### What are the steps to reproduce?
- Check the direction of the screen then switch style between margin-right or margin-left as suggested below:

![image](https://user-images.githubusercontent.com/19435804/42038067-4bd8abae-7aea-11e8-8c07-6d72347da1b7.png)

- Here's our checkBodyDir function that we've used to solve the issue which extracts the value of 'dir' attribute for the 'body' element and return true in case it is in the RTL direction

![image](https://user-images.githubusercontent.com/19435804/42039900-bb5d0f02-7aee-11e8-875e-d9d02ef5973a.png)

#### What is the use-case or motivation for changing an existing behavior?
- We are designing a system that supports Arabic but the current behavior of the date time picker is not working properly with RTL direction because it always give the margin-left to hours and doesn't handle margin-right in the other direction

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
-AngularJS 1.6.6 
-TypeScript 2.6.2.0
-Windows 10 OS
-Google chrome browser

#### Is there anything else we should know?
Thank you for your interest. Hope to know if this issue is handled already or not.

**Comment by crisbeto** [comment]
This is the repository for Angular Material, not MDC.
