### ISSUE TITLE
"Promise" is undefined in angular material >= 6.2 for IE11

### ISSUE THREAD

**Issue by m55c55** [angular/material2#11966]
#### Bug, feature request, or proposal:

In Internet Explorer 11, compiled bundle (--prod) breaks for Internet Explorer 11. No problems with Firefox, Chrome, and other "real" browser ;-).

#### What is the expected behavior?

Internet Explorer should show the page.

#### What is the current behavior?

White screen with ""Promise" ist undefiniert" error message in console.

#### What are the steps to reproduce?

Build a minimal angular 6 page with angular material 6.3 and cdk 6.3. Compile with "--prod" options and load the page in Internet Explorer. This will lead to a whitescreen.

Do the same thing with angular material 6.0 and cdk 6.0. No problems here.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.3, Angular 6.0, TypeScript 2.7.2, Internet Explorer 11

**Comment by crisbeto** [comment]
It sounds like you might not have a polyfill for `Promise`.

**Comment by josephperrott** [comment]
Closing as Material does not provide a defintion for Promise as this would need to be defined in a polyfill for IE11.  If you find that even with the polyfill in place this is occuring, feel free to open up a new issue with a reproduction example for us to take a look.
