### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by brackio** [angular/material2#1196]
Can someone please: 
1. Update the Getting Starting to reflect angular2-rc6 and angular2-material-8.1
OR 
2. Provide a link to repo that is currently using angular2-rc6 and angular-material-8.1 successfully.  

I am not a programming expert, but I can follow a tutorial, however, there is none.  I have been trying to make sense out of:

1. [Getting Started](https://github.com/angular/material2/blob/master/GETTING_STARTED.md)
2. [Change Log](https://github.com/angular/material2/blob/master/CHANGELOG.md)
3. [Kara's puppy-love repo](https://github.com/kara/puppy-love/blob/master/src) , and the [demo-app](https://github.com/angular/material2/blob/master/src/demo-app) repo, but still no-luck.

Each repo is running a different version of angular-material and the implementation is different - which makes it confusing.

Please help!

**Comment by cissecedric** [comment]
+1
