### ISSUE TITLE
Invalid collection.json in schematics

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/material2#11979]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Valid JSON

#### What is the current behavior?
Invalid JSON, a double quote is missing after `materialNav` in `schematics/collection.json`, causing errors in tools using schematics (see cyrilletuzi/vscode-angular-schematics#5).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.3

#### Is there anything else we should know?
As an additional note, comments are not valid inside a JSON file. It forces tools which use schematics, like [Angular Schematics extension for VS Code](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics), to install additional JSON parsing libraries, as a normal `JSON.parse()` fail. If it's OK to remove them, I'll open another issue and PR.

**Comment by josephperrott** [comment]
Fixed by https://github.com/angular/material2/pull/11839
