### ISSUE TITLE
Support native <select> in mat-form-field

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#11971]
Should work similarly to using `mat-form-field` with an `<input>`. Styling is obviously best-effort, since we don't have full control over how the OS renders options.

**Comment by vivian-hu** [comment]
It is resolved as PR #12707.

**Comment by jelling** [comment]
Can I ask what prompted this feature? Is there a known performance issue? I'm seeing a bug with mat-select in v6 where the same mat-control code renders mat-options in some scenarios but not in others.

**Comment by jelbourn** [comment]
@jelling It gives people more options. A native select is inherently more performant, more accessible, and has less code.

If you have a bug to report, please open a new issue.
