### ISSUE TITLE
Progress bar configuration

### ISSUE THREAD

**Issue by Jamlearner** [angular/material2#11973]
#### Bug, feature request, or proposal:
Feature request

#### What is the use-case or motivation for changing an existing behavior?
Current Progress bar supports a single value in Determinate mode. Does it support multi-values, a Start Value and End Value?

Maybe it will look like this for Determinate mode.
![image](https://user-images.githubusercontent.com/36904328/42067523-323bdd12-7b79-11e8-9b04-235d0b270cd9.png)

**Comment by Jamlearner** [comment]
![image](https://user-images.githubusercontent.com/36904328/42069548-f99ec120-7b84-11e8-942e-ed9d64ad83c7.png)

**Comment by josephperrott** [comment]
Closing as this is something that does not fit within the Material Design spec for progress bars.
