### ISSUE TITLE
Bug mat-button-toggle: button inherit margin from class in mat-button-toggle 

### ISSUE THREAD

**Issue by LoganDupont** [angular/material2#11976]
#### Bug, feature request, or proposal:
Bug 

#### What is the expected behavior?
The margin should only be set on the mat-button-toggle 

#### What is the current behavior?
The margin is set on the mat-button-toggle and child button element. 

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-csuqbl

#### What is the use-case or motivation for changing an existing behavior?
If a user sets for example a margin-right of 15px. He will get actually 15px on the right on the mat-button-toggle and also 15px on the button element itself.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All browsers
Angular 6.0.6
Material 6.3.1

#### Is there anything else we should know?
Still working on Material 6.3.0

**Comment by LoganDupont** [comment]
@crisbeto Do I need to create a new issue as the same is happening for padding?

**Comment by crisbeto** [comment]
It's not necessary @LoganDupont, I'll include it in my current PR.
