### ISSUE TITLE
Mat-Tree: Resetting datasource data property causes app to become very slow (memory leak?)

### ISSUE THREAD

**Issue by Craig939393** [angular/material2#11985]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
changing the underlying data does not cause the app to run slowly when expanding nodes

#### What is the current behavior?
changing the underlying data causes the app to run slowly when expanding nodes

#### What are the steps to reproduce?
this.nestedDataSource.data = data;

#### Is there anything else we should know?
I am unsure what causes this as it only seems to happen in some instances and I cannot see a pattern to it, sorry I cant be more useful. however my current workaround is:
this.nestedDataSource = new MatTreeNestedDataSource<type>();
this.nestedDataSource.data = data;

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by josephperrott** [comment]
Closing as we are not be able to reproduce this issue.
