### ISSUE TITLE
MatSnackBarContainer throw ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by vedrax-admin** [angular/material2#11988]
Hi,

I'm using version 6.3.0 and when my `snackBar.open` is called in `ngOnInit` the following error is thown _ExpressionChangedAfterItHasBeenCheckedError_. In previous version, I didn't have any problems.

`ngOnInit(): void {
        this.notificationService.getNotification()
            .pipe(takeUntil(this.destroy$))
            .subscribe(msg => {
                if (msg) {
                        this.snackBar.open(msg, 'X', {
                        duration: 3000
                        });
                }
            });
}
`

If I do the following all run as expected:

`setTimeout(()=>{
      this.snackBar.open(msg, 'X', {
      duration: 3000
      });
 });
`

Thanks

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
