### ISSUE TITLE
material.angular.io is down again

### ISSUE THREAD

**Issue by zh99998** [angular/material2#11998]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
https://material.angular.io works properly.

#### What is the current behavior?
white screen with some 404 in console.
I have checked `disable cache` in chrome devtools `network` tab, and refreshes many times.
![image](https://user-images.githubusercontent.com/359622/42125079-4a4df29e-7ca2-11e8-90ba-a6aaf77c36b1.png)
```
https://material.angular.io/runtime.a66f828dca56eeb90e02.js
https://material.angular.io/styles.dac3a9e03d9660e0b6fe.css
https://material.angular.io/main.33d6b00ba0e5df97cddb.js
```

after clean all site data in `Application` tab. it go back works.
but I have meet many times like that. so I think this should be an issue.

**Comment by Chan4077** [comment]
Have you tried force-reloading? (aka <kbd>Ctrl</kbd> + <kbd>F5</kbd> / <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd>)

**Comment by hakimio** [comment]
Hard reload fixes it but if uses have to do that to be able to use the website, maybe there is something is wrong with website's caching policies/response headers?

**Comment by jelbourn** [comment]
@amcdnl can you take another look at the service worker setup?

**Comment by amcdnl** [comment]
@jelbourn - I made a PR that tweaks the SW settings and bumps pkg to latest ( https://github.com/angular/material.angular.io/pull/485 ). At this point, SW are causing more issues than they might be worth. Might be worth considering removing them.

**Comment by vinaykatdare** [comment]
To make material.angular.io work temporarily on chrome client of end user select **Bypass for network** option under chrome developer tools >> Application >> Service workers

**Comment by jelbourn** [comment]
This should be resolved now; it might need one final service worker clear.
