### ISSUE TITLE
[Buttons] Border-radius should be 4px

### ISSUE THREAD

**Issue by IlCallo** [angular/material2#12016]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
As written in [the specs](https://material.io/design/components/buttons.html#specs), border-radius should be 4px instead of the old 2px value (in the specs they're expressed in dp but I guess it's a 1-to-1 conversion)

#### What is the current behavior?
They have 2px border-radius

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.6
Material 6.3.1

#### Is there anything else we should know?
This can probably be addressed directly on the new #11961 base class for buttons

**Comment by crisbeto** [comment]
We're still running against the previous version of the Material design spec. We'll start implementing the new version soon.

**Comment by IlCallo** [comment]
Oh, ok. Shall I close the issue or leave it open?

**Comment by crisbeto** [comment]
Let's close it so the info doesn't get scattered. We'll probably have an issue for tracking all the changes when we get to it.
