### ISSUE TITLE
[tabs, button-toggle @alpha.8-1] Binding to events in the template causes AoT compiler to fail

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#1202]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

No error should be thrown during Ahead-of-Time compilation when binding to `(selectChange)` event of `MdTabGroup` or the `(change)` event of `MdButtonToggle`
#### What is the current behavior?

Binding to these events in the template will cause the AoT compiler (`ngc`) to generate invalid code as shown below
#### What are the steps to reproduce?

In my template, I try to capture the index of the newly selected tab, and assign it to a class property 

```
<md-tab-group (selectChange)="ui.tab=$event.index">
    <md-tab>...<md-tab>
</md-tab-group>
```

This makes the AoT compiler generate the code below:

```
const subscription_0:any = this._MdTabGroup_2_4.selectChange.subscribe(this.eventHandler(this._handle_selectChange_2_0.bind(this)));
```

Notice that the argument of `subscribe()` should be a function; in this case it's not so the following error causes compilation to fail:

```
Error at C:/...ngfactory.ts:448:76: Argument of type 'Function' is not assignable to parameter of type 'NextObserver<MdTabChangeEvent> | ErrorObserver<MdTabChangeEvent> | CompletionObserver<MdTabChange...'.
  Type 'Function' is not assignable to type '(value: MdTabChangeEvent) => void'.
    Type 'Function' provides no match for the signature '(value: MdTabChangeEvent): void'
```

I tried changing the template to call a function, and setting the class property within that function:

```
<md-tab-group (selectChange)="onTabChanged($event)">
    <md-tab>...<md-tab>
</md-tab-group>
```

The code generated is identical and the error remains. 

The same problem occurs when binding to `(change)` event of `MdButtonToggle` as I do here:

```
<md-button-toggle-group multiple >
    <md-button-toggle *ngFor="let option of options" 
            (change)="option.checked = !option.checked">
        {{option.type}}
    </md-button-toggle>
</md-button-toggle-group>
```

Removing the bindings makes the errors go away.
#### What is the use-case or motivation for changing an existing behavior?

This prevents AoT from working as intended. Compilation fails.
#### Which versions of Angular, Material, OS, browsers are affected?

`Angular 2 rc.6`, `Material 2 alpha 8-1`, `node 4.5.0` on `Windows 7`
#### Is there anything else we should know?

I'm not sure whether to file this bug with `angular/material2` or `angular/angular` but I do so here because the `ngc` compiler handles other event bindings in templates so it seems to be a problem with `MdTabGroup` and `MdButtonToggle`. Vanilla transpilation with `tsc` + Just-in-Time compilation in the browser work without a hitch. The problem occurs when `ngc` generates bad code

**Comment by paumayr** [comment]
I can reproduce this issue and I think i found a related issue here:
https://github.com/angular/angular/issues/11064

**Comment by jelbourn** [comment]
@crisbeto I suspect that this has been fixed in alpha.9, could you confirm? You can use https://github.com/jelbourn/material2-app which is already set up for AoT
(you just have to run `./node_modules/.bin/ngc -p ./src` before you `ng serve`)

**Comment by RoxKilly** [comment]
@jelbourn You're right; this problem disappeared after I moved to `alpha 9`
