### ISSUE TITLE
mat-chip cannot be selected

### ISSUE THREAD

**Issue by cnotv** [angular/material2#12020]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The chip should toggle the status of selected on click, if `selectable` is set to `true`.
This should change status and color (to blue) accordingly.

#### What is the current behavior?
It's not possible to select the chip.

#### What are the steps to reproduce?
Click on the chip<br/>
https://stackblitz.com/edit/mat-chip-select-issue?file=app/app.component.html<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Ubuntu 18.10
Chrome and Firefox latest

Version of the link:
- Angular 5.0.0-rc7
- Material/CDK 2.0.0.beta12

My app
- Angular 6.0.5
- Material/CDK 6.2.1

#### Is there anything else we should know?
The bug occurs also in the official documentation:
https://material.angular.io/components/chips/overview

**Comment by BroccolliRevolution** [comment]
I noticed that chip is selectable if you use keyboard - navigate with arrow keys and select chip with space. But this is not working using mouse click. Must be bug

**Comment by josephperrott** [comment]
Closing as this is working as expected as selecting a chip on a `click` event is something that is expected to be handled by the user.

[Here](https://stackblitz.com/edit/mat-chip-select-issue-gp2tvr?file=app/app.component.html) is a working fork from your reproduction.

**Comment by ienzam** [comment]
Will you be willing to add an input "clickable" or something similar to MatChip to allow selection by click?

**Comment by keatkeat87** [comment]
although this is easy to implement, but not easy to understand.
can somebody point out the design concept ? 
Is this based on the material guide ?
