### ISSUE TITLE
Autocomplete input missing for MatInput

### ISSUE THREAD

**Issue by nomistrebla** [angular/material2#12024]
#### Bug, feature request, or proposal:
`MatInput` should have an `autocomplete` input to control the `autocomplete` HTML attribute of the rendered `input` element. I need this, since there seems to be no other way to disable the browser's (e.g. Chrome's) autofill with `autocomplete="off"` or `autocomplete="new-password"`.

#### What is the expected behavior?
A component input `autocomplete` which maps to the `autocomplete` HTML attribute of the `input` element.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.0.5
Material: 6.3.9

#### Is there anything else we should know?
A similar issue was submitted in 2016 regarding `MdInput`:
[https://github.com/angular/material2/issues/789]()

**Comment by julianobrasil** [comment]
Are you sure it doesn't work? It seems to be working as expected: https://stackblitz.com/edit/angular-material2-issue-qujscl

```html
<mat-form-field>
  <input matInput type="text" name="fname" autocomplete="off">
</mat-form-field>
```

**Comment by crisbeto** [comment]
This was resolved recently with https://github.com/angular/material2/pull/11926.
