### ISSUE TITLE
Datepicker select date by user manually type

### ISSUE THREAD

**Issue by fort** [angular/material2#12033]
#### Bug, feature request, or proposal:
MatDatepicker _select method do not update UI

#### What is the expected behavior?
I want calendar to work with user input and with calendar popup window.
I handle dateInput Output event and use  MatDatepicker._select(date) to select inputed date,
but in UI selected date do not highlighted

#### What is the current behavior?
Selected date do not changed in UI popup window

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/TxpRKo<br/>

#### What is the use-case or motivation for changing an existing behavior?
To handle both from user typing date and by picking in popup

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular material - 5.0.0
angular - 5.2.6
typescript - 2.4
OS - osx capitan
Browser - Chrome Version 67.0.3396.87

**Comment by Niaro** [comment]
Though calling a private method isn't a correct thing to do from a client code, the feature itself very reasonable, it would be really cool to be able to change activeDate of an opened datepicker on user input

**Comment by josephperrott** [comment]
Closing as `_select` is an internal method as denoted by the `_` prefix.

**Comment by hiepxanh** [comment]
hello sir, I used `._select()` method and still not update highlight date. I don't know what to do, where to go? I really need this feature. Can you provide me some suggestion? anyway to update selected date? @josephperrott

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/46580266-b43c2a80-ca4b-11e8-8917-bc8e5589c48e.png)
I have the next day button but when I press that button, I try alot but next day not highlight...
