### ISSUE TITLE
[Tabs] tab is not changed when selectedindex changes

### ISSUE THREAD

**Issue by bkappel** [angular/material2#12038]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tab corresponding to the index should be displayed.

#### What is the current behavior?
Previously selected tab is displayed, tabGroup selectedIndex is not updated.

#### What are the steps to reproduce?
This bug can also be found in the documentation/demos. 
[Material Demo](https://material.angular.io/components/tabs/examples)
In the demo "Tag group with dynamically changing tabs" when checking the "Select tab after adding", the tab is not focused when adding a tab.
In custom code the tab is also not focused when updating the selectedIndex.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

- Angular: 6.0.6
- Angular Material: 6.3.2
- OS: Windows
- Browsers: Chrome, FireFox, Opera, IE Edge

**Comment by Drasius2** [comment]
+1

**Comment by candidJ** [comment]
I'm too facing similar issue for MatStepper module. The selectedIndex property is not updated first click event but always on second one. It's similar to what @robertmesserle 
 explained here https://github.com/angular/material2/issues/687 but for stepper module.

**Comment by dmacfarlane** [comment]
The ability to select a tab after adding it appears to have been broken by #9132.

**Comment by Auricopter** [comment]
This is also a serious bug for our business. Please fix the functionality and the example on your page.

**Comment by DevVersion** [comment]
@Auricopter A fix is now pending. Working on getting that in as soon as possible.

**Comment by Auricopter** [comment]
@DevVersion Thank you. It works now. However I need to add a setTimeout() since the code example on your page doesn't wait for the Tab Creation before changing the selectedIndex. 
Is there a callback-function or life cycle hook for the Tab Creation?

**Comment by DevVersion** [comment]
The fix is not merged and published yet. As soon as it will be part of a future Material release, you wouldn't need the `setTimeout` at all. Everything happens in the same change detection run-
