### ISSUE TITLE
Required asterisk not showing in reactive forms

### ISSUE THREAD

**Issue by Tommatheussen** [angular/material2#12037]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Form fields show required asterisk when validator is set through reactive form 

#### What is the current behavior?
form fields do not show the required asterisk when set through a reactive form model

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/angular-p3sswf?file=src%2Fapp%2Fapp.component.ts

#### What is the use-case or motivation for changing an existing behavior?
I would like to be able to have full control over when the field should be required or not (during creation of the fields), without having to add helper functions for the `required` parameter in the template.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.7, material 6.3.2

#### Is there anything else we should know?
If I add a required attribute to the field itself it works.
The actual validation on required does work, focusing and defocusing shows the red error outline. I also noticed from inspecting the elements the classes actually get added (`ng-star-inserted`), it just doesn't show up:
Not working: 
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/13683094/42223682-a0c7e2aa-7ed8-11e8-8d45-69924c36338c.png">

Working (with required attribute in template):
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/13683094/42223760-d4722b38-7ed8-11e8-9237-7d693dc065bf.png">

**Comment by revov** [comment]
@Tommatheussen, please check #2574

**Comment by Tommatheussen** [comment]
@revov yep, same issue, seems I didn't search thorough enough, closing this one
