### ISSUE TITLE
Docs: search components by name in documentation website

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/material2#12031]
#### What is the expected behavior?
There should be a search box on documentation site to search components/directives by there common name (like tab) or actual name (like MatTab)

#### What is the current behavior?
There is no such search box in documentation page

#### What is the use-case or motivation for changing an existing behavior?
For people who are looking for particulate component  can search  that directly instead of navigating through the web

#### Bonus thing
we could also search by component attributes like inputs and outputs

**Comment by josephperrott** [comment]
Closing as feature requests/issues with the material.angular.io site should be opened at its repo [here](https://github.com/angular/material.angular.io/issues/new).
