### ISSUE TITLE
Dark version of the documentation

### ISSUE THREAD

**Issue by pavilion** [angular/material2#12049]
I was wondering if it would be possible to have a dark version of the documentation. Us devs usually spend many hours reading documentation, so it would be great news for the health of our eyes.
Both [Vue](https://vuematerial.io/) and [React's](https://material-ui.com) material docs have this feature... So.. why not? :)

**Comment by Chan4077** [comment]
You can change the theme of the documentation. Two of the themes are dark themes. (It's located next to the Github button on the header)
