### ISSUE TITLE
Slide-toggle

### ISSUE THREAD

**Issue by kgiroux** [angular/material2#1204]
#### request:
Hi everyone, i dont understand how can i use Slide-toggle

<md-slide-toggle [color]="myColor">
  Dynamic Color
</md-slide-toggle>

I would like to use #309DB5 color, but nothing change. It is style purple. 

How can i use it ...

#### What is the expected behavior?
Slide-toggle

#### What is the current behavior?
Slide-toggle

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2-RC6
Material Alpha 8

**Comment by DevVersion** [comment]
Right now Material 2 does not support different Material Design Palettes (See #123).

At the moment the theme is fixed for all components to
- `Teal` : Primary Palette
- `Purple`: Accent Palette
- `Red`: Warn Palette

The slide-toggle uses by default the `accent` palette as per specs.

To be able to switch the different palettes, you could use the following syntax

```html
<md-slide-toggle color="primary">

<!-- Dynamic with Angular host bindings -->
<md-slide-toggle [color]="myColor">
```

Also this is documented in the [Readme](https://github.com/angular/material2/tree/master/src/lib/slide-toggle#theming) of the slide-toggle

**Comment by jelbourn** [comment]
See #123
