### ISSUE TITLE
The border-right in the table's sticky td doesnot fixed.

### ISSUE THREAD

**Issue by kinmy** [angular/material2#12053]
#### Bug, feature request, or proposal:
I added border-right in sticky td, but when I moved the table, the border-right would also move along. Now I want to move the table, border-right is fixed.

#### What is the expected behavior?
The border-right in the table's sticky td should be fixed.

#### What is the current behavior?
The border-right in the table's sticky td will move with table's moving.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Show the customer that can be move the table and show what is fixed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^6.0.3",
"@angular/material": "^6.3.2",
OS: macOS High Sierra 10.13.4,
"typescript": "~2.7.2",
chrome: 67.0

**Comment by kinmy** [comment]
It works in the StackBlitz, but it doesnot work on my mac T.T

**Comment by kinmy** [comment]
I guess mabey the reason is the version.

**Comment by jelbourn** [comment]
@kinmy are you able to determine the difference between your app and the example? There's not really anything for the team to debug otherwise.

**Comment by josephperrott** [comment]
Closing as we are not be able to reproduce this issue.
