### ISSUE TITLE
Why does the mat-active class persist on the first select option when a default option isn't specified?

### ISSUE THREAD

**Issue by shaneamondos** [angular/material2#12056]
#### Bug, feature request, or proposal:
bug or proposal, not sure if intended behavior yet

#### What is the expected behavior?
The expected behavior is to not have an active style when you don't specify a default option

#### What is the current behavior?
The active styling persists on the first option even when a default option is not specified or you hover over another option

#### What are the steps to reproduce?
No StackBlitz, its on your demo:
https://imgur.com/4E3keyz

#### What is the use-case or motivation for changing an existing behavior?
I don't think its the standard way to do things

**Comment by crisbeto** [comment]
That's because the hover and focus styling is the same. The first option is focused, whereas the other one is hovered.

**Comment by crisbeto** [comment]
Closing since this is behaving as expected.
