### ISSUE TITLE
Bug - Drag & Drop - Doesn't Seem to Be Functioning Correctly With Horizontally Stacked Items

### ISSUE THREAD

**Issue by jaredmahan** [angular/material2#12066]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Drag and drop should work as it does with vertically stacked items

#### What is the current behavior?
When you try to drag across to order horizontal items you see strange behavior.

#### What are the steps to reproduce?
See link below: https://stackblitz.com/edit/angular-basic-horizontal-drag-drop

#### What is the use-case or motivation for changing an existing behavior?
We need to be able to utilize drag and drop for items that are stacked horizontally not just vertically

**Comment by crisbeto** [comment]
Since the drag&drop is still a work-in-progress, we haven't gotten around to implementing horizontal sorting yet. [There's even a TODO for it](https://github.com/angular/material2/blob/master/src/cdk-experimental/drag-drop/drop.ts#L138).

**Comment by jaredmahan** [comment]
Cool thanks for the heads up! Any timeline on when the horizontal sorting might be completed? Would love to include this in the app we are developing.

**Comment by crisbeto** [comment]
@jaredmahan you can keep an eye on when #12104 gets released.
