### ISSUE TITLE
Duplicated CSS imports

### ISSUE THREAD

**Issue by andrewtw** [angular/material2#12069]
https://github.com/angular/material2/blob/89cad3fd1511def6ea9aa17c867f9872bf774f2c/src/lib/menu/menu.scss#L3

https://github.com/angular/material2/blob/89cad3fd1511def6ea9aa17c867f9872bf774f2c/src/lib/menu/menu.scss#L5

Why importing the same file twice?

**Comment by FrederikSchlemmer** [comment]
Seems like one import isn't needed. 

@andrewtw Would you like to make a PR? Otherwise I would do this.
