### ISSUE TITLE
Consider updating typography to newest spec

### ISSUE THREAD

**Issue by bgoscinski** [angular/material2#12061]
#### Bug, feature request, or proposal:
Feature request?

#### What is the expected behavior?
Compliance with **newest** spec.

#### What is the current behavior?
Angular Material typography is compliant with [**old** version of the typography spec](https://web.archive.org/web/20180409140108/https://material.io/guidelines/style/typography.html#typography-styles).

#### What are the steps to reproduce?
1. Open https://stackblitz.com/edit/angular-material2-issue-l1jl64
2. On new tab open https://material.io/design/typography/the-type-system.html#type-scale
3. Compare and see lots of differences

#### What is the use-case or motivation for changing an existing behavior?
Compliance with **newest** spec.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

**Comment by IlCallo** [comment]
They haven't started implementing the new spec yet

> We're still running against the previous version of the Material design spec. We'll start implementing the new version soon.

[source](https://github.com/angular/material2/issues/12016#issuecomment-402019686)

**Comment by bgoscinski** [comment]
Thx for the info
