### ISSUE TITLE
Bug Datepicker: disabled attribute doesn't work with Reactive Forms

### ISSUE THREAD

**Issue by Bielik20** [angular/material2#12065]
#### What is the expected behavior?

It should work just like in [example](https://material.angular.io/components/datepicker/examples) -> Disabled datepicker -> Input disabled (the third one)

#### What is the current behavior?

When using reactive forms it isn't disabled and we receive this message:
![image](https://user-images.githubusercontent.com/13436218/42288629-cfb62ff2-7fbb-11e8-9ab4-75989ca18a7d.png)

While I understand purpose of this message, setting `disabled` in form control prevents any changes to that field. I want only manual input to be disabled due to https://github.com/angular/material2/issues/11936 and https://github.com/angular/material2/issues/12064.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-datepicker-disable-bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

- Angular: 6.0.7
- Material: 6.3.2

**Comment by crisbeto** [comment]
This message is being logged by `@angular/forms`, not Material. You can post an issue about it [on the main repo](https://github.com/angular/angular/issues).

**Comment by LoganDupont** [comment]
@Bielik20 Did you found a solution for this problem?

**Comment by Bielik20** [comment]
@LoganDupont Hi, unfortunately no. After moving it to main angular repo I stopped tracking it. The related issue seams to be closed so I guess they found 'a' solution.

**Comment by LoganDupont** [comment]
@Bielik20 Well the issues linked to it seems to focus on how to solve the message and not the problem of disabling the formControl, which solves the message, also results in disabling all parts of the datepicker.

**Comment by Bielik20** [comment]
Well, maybe it is a good idea to ping one of the collaborators there on my
issue to inform them that it is in fact not resolved. Maybe they will
reopen it.

W dniu wt., 22.01.2019 o 17:34 Logan Dupont <notifications@github.com>
napisał(a):

**Comment by brgrz** [comment]
@crisbeto This really shouldn't been closed. As it currently stands it is impossible to have disabled input but enabled datepicker popup with inputs bounds to reactive form controls. This should've been addressed here, it is not a Angular Forms issue.

For others: there is a partial solution to this and it involves setting the readonly attribute however that changes the styling of the control.
