### ISSUE TITLE
Bug: Label and placeholder always appear on Input when parent has 'webkit-text-fill-color' property.

### ISSUE THREAD

**Issue by Joaovtrc** [angular/material2#12074]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It was supposed to only appear the label.

#### What is the current behavior?
Shows both the label and placeholder at the same time.

#### What are the steps to reproduce?
Input needs to be inside a element that has a 'webkit-text-fill-color' property.
https://stackblitz.com/edit/input-color-bug?file=app%2Fcard-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on Chrome and Angular Material 5.2.4 and 6.3.2.

**Comment by DevVersion** [comment]
Nice catch. I've created a PR to fix this.
