### ISSUE TITLE
cdk drag and drop - cdkDragDropped event not triggered

### ISSUE THREAD

**Issue by pas2al** [angular/material2#12086]
#### What is the expected behavior?
The drop event `cdkDragDropped` should trigger the custom method

#### What is the current behavior?
The [demo app for drag drop](https://github.com/angular/material2/tree/master/src/demo-app/drag-drop) has two lists (todo and done). **The items in the list are not updated** from the `cdkDragDropped` event. The associated `drop(event: CdkDragDrop<string[]>){...}` method is not called.

#### What are the steps to reproduce?
I created an example with the exact same implementation like in the material2 demo-app.
https://stackblitz.com/edit/angular-material2-issue-eemhuq

I also tried it with the complete material2 repository. Cloned the repository and started the demo app using `gulp serve:devapp`. Same problem, like in the stackblitz example.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
See stackblitz example

Based on the changes introduced in #11864 by @crisbeto

**Comment by crisbeto** [comment]
It seems like our demo app is using the wrong events. The proper name for it is `dropped`.

**Comment by pas2al** [comment]
Ah, perfect. Found it in your source code. Thanks! Is there progress on the documentation for the cdk drag and drop? If you need any help i can start working on it. I am exploring your implementation.

**Comment by crisbeto** [comment]
I'll continue working on it a bit more over the next week, I was busy with other tasks this week. Also let's keep this issue open since it shows that the dragging is off when the page is scrolled.

**Comment by pas2al** [comment]
> the dragging is off when the page is scrolled
What do you mean by that?

Is there a way to chat with you privately? (other topic)

**Comment by crisbeto** [comment]
I mean that the logic that determines how the item should be sorted, as well as where to render the preview, seems to be thrown off when the page is scrolled down. I've submitted #12098 to fix it.

**Comment by pas2al** [comment]
@josephperrott What about the fix #12092 for the demo app?
