### ISSUE TITLE
[Tooltip] Incorrect position on a sticky element

### ISSUE THREAD

**Issue by oktav777** [angular/material2#12090]
#### Bug, feature request, or proposal:
`Bug`

#### What is the expected behavior?
`Tooltip` should appear just below the hovered element.

#### What is the current behavior?
`Tooltip` is not positioned correctly when an element 'sticks' using `position: sticky`. It just floats down as you scroll.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-jndauw

#### What is the use-case or motivation for changing an existing behavior?
The `Tooltip` as a main UI element should behave correctly.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`@latest`

#### Is there anything else we should know?
Instructions to reproduce inside the demo on stackblitz.

**Comment by crisbeto** [comment]
This is the same underlying issue as https://github.com/angular/material2/issues/11365. Closing as a duplicate.
