### ISSUE TITLE
ng1 upgraded component on dialog not working

### ISSUE THREAD

**Issue by AminRahimi** [angular/material2#12105]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
ng1 upgraded component works on material dialog

#### What is the current behavior?

```
ERROR

Error: StaticInjectorError(AppModule)[$scope]:
StaticInjectorError(Platform: core)[$scope]:
NullInjectorError: No provider for $scope!
```

#### What are the steps to reproduce?
https://stackblitz.com/github/AminRahimi/ngUpgrade

#### Is there anything else we should know?
:heart:

**Comment by DevVersion** [comment]
This is because you didn't provide a `viewContainerRef` and therefore a injector that includes the upgraded component isn't being used.

```ts
constructor(public dialog: MatDialog, private viewContainerRef: ViewContainerRef) { }

onOpenModalClick() {
  ....,
  viewContainerRef: this.viewContainerRef,
});
```
