### ISSUE TITLE
Unable to get my first angular2-material app working!

### ISSUE THREAD

**Issue by muthyas** [angular/material2#1210]
#### Bug, feature request, or proposal:
Unable to run a simple angular 2 material 2 app. Trying to use MdButtonModule and MdCardModule

#### What is the expected behavior?
Expect to see: My First Angular 2 App

Here's my app.component.ts
import { Component } from '@angular/core';
import { MdCardModule } from '@angular2-material/card';
import { MdButtonModule } from '@angular2-material/button';

@Component({
  selector: 'my-app',
  template: '<h1>My First Angular 2 App</h1>'
})
export class AppComponent { }

And here's my app.module.ts

import { NgModule, ApplicationRef }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }   from './app.component';
import { MdCardModule } from '@angular2-material/card';
import { MdButtonModule } from '@angular2-material/button';

@NgModule({
  imports:      [ BrowserModule, 
                    MdButtonModule, 
                    MdCardModule
                 ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})

export class AppModule { 

} 

#### What is the current behavior?
[1] 16.09.09 16:07:59 404 GET /traceur                     
Error: wrapFn@http://localhost:3000/node_modules/zone.js/dist/zone.js:794:35
	invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:365:43
	runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:265:58
	invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:433:41
	Error loading http://localhost:3000/traceur
	Error loading http://localhost:3000/node_modules/@angular2-material/card/card.js as "@angular2-material/card" from http://localhost:3000/app/app.module.js — system.src.js:123:88

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Using Quick-start Angular2 example and add material components

#### Which versions of Angular, Material, OS, browsers are affected?
angular-cli: 1.0.0-beta.10                                 
node: 6.4.0                                                
os: darwin x64 

#### Is there anything else we should know?
Package.json 
{
  "name": "angular2-material",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/compiler-cli": "0.6.0",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/platform-server": "^2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.6",
    "@angular2-material/button": "^2.0.0-alpha.8-1",
    "@angular2-material/card": "^2.0.0-alpha.8-1",
    "@angular2-material/core": "^2.0.0-alpha.8-1",
    "angular2-in-memory-web-api": "0.0.18",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.11",
    "systemjs": "0.19.27",
    "typescript": "^2.0.2",
    "zone.js": "^0.6.17"
  },
  "devDependencies": {
    "concurrently": "^2.2.0",
    "lite-server": "^2.2.2",
    "typescript": "^1.8.10",
    "typings": "^1.3.2"
  }
}

**systems.config.js**
/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      // other libraries
      'rxjs':                       'npm:rxjs',
      'angular2-in-memory-web-api': 'npm:angular2-in-memory-web-api',
      '@angular2-material': 'npm:@angular2-material',
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular2-in-memory-web-api': {
        main: './index.js',
        defaultExtension: 'js'
      },
      '@angular2-material/card': {
        main: './card.js'
      },
      '@angular2-material/button': {
        main: './button.js'
      }
    }
  });
})(this);

**Comment by JanStureNielsen** [comment]
If you're just playing around, I suggest Angular 2.0.0-rc.5 with Angular Material 2.0.0-alpha.7-4. 

I have a working application on Angular 2.0.0-rc.5 with Angular Material 2.0.0-alpha.7-4; the upgrade to Angular 2.0.0-rc.6 + Angular Material 2.0.0-alpha.8-1 requires TypeScript 2.0.2 but my app is still having issues with this combination...so I'm sticking to RC5+Alpha.7-4 until these issues get ironed out...

**Comment by muthyas** [comment]
Thanks. What version of Typescript do you use to get a stable angular2 and material2?

**Comment by JanStureNielsen** [comment]
These are my dependencies from `package.json`:
```
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "core-js": "^2.4.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.6.12",
    "@angular2-material/button": "2.0.0-alpha.7-4",
    "@angular2-material/button-toggle": "2.0.0-alpha.7-4",
    "@angular2-material/card": "2.0.0-alpha.7-4",
    "@angular2-material/checkbox": "2.0.0-alpha.7-4",
    "@angular2-material/core": "2.0.0-alpha.7-4",
    "@angular2-material/grid-list": "2.0.0-alpha.7-4",
    "@angular2-material/icon": "2.0.0-alpha.7-4",
    "@angular2-material/input": "2.0.0-alpha.7-4",
    "@angular2-material/list": "2.0.0-alpha.7-4",
    "@angular2-material/menu": "2.0.0-alpha.7-4",
    "@angular2-material/progress-bar": "2.0.0-alpha.7-4",
    "@angular2-material/progress-circle": "2.0.0-alpha.7-4",
    "@angular2-material/radio": "2.0.0-alpha.7-4",
    "@angular2-material/sidenav": "2.0.0-alpha.7-4",
    "@angular2-material/slide-toggle": "2.0.0-alpha.7-4",
    "@angular2-material/slider": "2.0.0-alpha.7-4",
    "@angular2-material/tabs": "2.0.0-alpha.7-4",
    "@angular2-material/toolbar": "2.0.0-alpha.7-4",
    "@angular2-material/tooltip": "2.0.0-alpha.7-4"
  },
  "devDependencies": {
    "@types/hammerjs": "2.0.32",
    "@types/jasmine": "^2.2.30",
    "@types/protractor": "^1.5.16",
    "angular-cli": "1.0.0-beta.11-webpack.2",
    "codelyzer": "0.0.26",
    "hammerjs": "2.0.8",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "3.3.0",
    "string-replace-loader": "1.0.3",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.0"
  }
```

**Comment by muthyas** [comment]
Finally, got this to work with RC.5 and 2.0.0-alpha.7-4

Thanks!
