### ISSUE TITLE
bug(mat-selection-list): cannot change disabled status via @Input() disabled after programmatically change it 

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#12107]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Change `disabled` state programmatically (via `setDisabledState`) and via `@Input() disabled`

#### What is the current behavior?

If you set the `disabled` programmatically, you cannot change it via `@Input() disabled` anymore.

If you have:

```html
<mat-selection-list #shoes="matSelectionList" [disabled]="_listDisabled">
  <mat-list-option *ngFor="let shoe of typesOfShoes">
    {{shoe}}
  </mat-list-option>
</mat-selection-list>
```

And you do:

```ts
@ViewChild('shoes') _matSelectionList: MatSelectionList;
_listDisabled = false;
...
this._matSelectionList.setDisabledState(true);
```

the list is disabled (you cannot select any option) no matter what the value of `_listDisabled` is after executing `this._matSelectionList.setDisabledState(true)`.

#### What are the steps to reproduce?

Here you have a [Stackblitz demo](https://stackblitz.com/edit/angular-p4hp6x?file=app%2Flist-selection-example.html)

![image](https://media.giphy.com/media/23dN97GGFCGNBwCvFI/giphy.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material 6.3.2

**Comment by DevVersion** [comment]
@julianobrasil Nice catch. We shouldn't update the disabled state of each option individually while we have a `disabled` property on the `MatSelectionList` that will be taken into account by all options.
