### ISSUE TITLE
Bug: element after badge is overlapped

### ISSUE THREAD

**Issue by zijianhuang** [angular/material2#12109]
#### Bug

The element after the badge is overlapped. 

#### What is the expected behavior?

The element after the badge should be rendered right after the badge.

#### What is the current behavior?

The element B is rendered right after element A which is hosting the badge, without considering the space that the badge occupy. 

#### What are the steps to reproduce?

In the tutorial provided https://stackblitz.com/angular/emrqojllmka?file=app%2Fbadge-overview-example.html, add the following:

```html
<p>
  <span matBadge="4" matBadgeOverlap="false">Text with a badge</span>
</p>
<p>
  <span matBadge="3" matBadgeOverlap="false">AAA</span>
  <span> BBBB</span>
</p>

```

#### What is the use-case or motivation for changing an existing behavior?

I have content right after the badge in the same line.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material 6.3.2 and 6.3.1.

In 6.0.0, badge is working fine with content right after.

#### Is there anything else we should know?

This may be related to https://github.com/angular/material2/pull/11599 introduced in 6.3.0.

I have a workaround since the breaking changes in NG MD.

```html
    <span *ngIf="commentsCount" matBadge="{{commentsCount}}" fxFlex="1em"></span>
    <span fxFlex="0.7em"></span>
```

But obviously this is looking clumsy.

**Comment by zijianhuang** [comment]
Overlapping the content following content may be desired, for example, the following content is a big photo, so badge overlapping a tiny corner may be good. However, if the following is textural content, overlapping the following content is bad. Also, I have a use case that the following content is an avatar -- a small photo, badge overlapping the following avatar is bad.

It is good to fix it. Alternatively It may be better to provide a switch property to take care of different scenarios: overlapping or not the following content.

**Comment by crisbeto** [comment]
The changes in https://github.com/angular/material2/pull/11599 were very deliberate. In general we have a rule of not applying margin/padding to the outside of components, however that's what we were doing in the case of the badge, which caused some weird behavior if the badge is hidden. You can handle this yourself by adding a margin on the element with the badge.

**Comment by zijianhuang** [comment]
thanks for the clarification.
