### ISSUE TITLE
Bug: theming breaks when using colors from a palette

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#12108]
#### Bug, feature request, or proposal:
Bug: theming breaks when using colors from a palette

#### What is the expected behavior?
When using colors from a palette, the theming should work properly.
https://stackblitz.com/edit/angular-8dbgv7?file=src%2Fapp%2Fapp.component.css

#### What is the current behavior?
When using colors from a palette, the theming breaks.
https://stackblitz.com/edit/angular-9zwheq?file=src%2Fapp%2Fapp.component.scss

#### What are the steps to reproduce?
Simply loading the theme's palette will break theming:
Within any component, load the palettes
```
@import '~@angular/material/theming';
@import 'src/unicorn-app-theme.scss';
```
https://stackblitz.com/edit/angular-9zwheq?file=src%2Fapp%2Fapp.component.scss

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.7
Material 6.3.2
Chrome 67

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/7990765/42423790-7b38eeae-8300-11e8-9a89-a1e3cf104303.png)

- As you can see, the style is there, though it is overridden due to view encapsulation.
- Also, due to this issue, I had to remove the color palette styles from my component, and notice a drastic weight loss on my bundle (from 750 to 650kb) imagine having this loaded on tons of components.

**Comment by wulfsberg** [comment]
I think the problem is that your `material.theme.scss` includes the `mat-core()` and `angular-material-theme($app-theme)` calls. That keeps re-applying the mixins every time you include the file, duplicating CSS.
If you move those mixins to the `styles.scss`, you can import color variables without re-triggering the whole setup done by those calls.

**Comment by Ploppy3** [comment]
@wulfsberg I tried and it does not fix either of the problems, my app size still gains 130kb and it still breaks the theming.

**Comment by Ploppy3** [comment]
Oh my bad, I understand now. I'm unfamiliar with scss mixins, I did not move the `@include angular-material-theme` lines to the styles.scss. Let me test to see if this still impact the size of the bundle.

**Comment by Ploppy3** [comment]
Ok, I'm able to access the colors and it does not impact the size of the bundle anymore. Thank you.

**Comment by Ploppy3** [comment]
@wulfsberg though I have one more question, let's say I want to apply a color within a component affected by the theme.

In this example: I just want the `p` tag to change color according to the theme primary color. (I could declare `.primary` and `.dark-theme .primary` rules in the styles.scss and set colors globally across the app but it's a really basic example). Though it does not work.

https://stackblitz.com/edit/angular-zozmgg?file=src/app/app.component.scss

**Comment by wulfsberg** [comment]
If you just want to pick a specific color, you can simply pick it with, say, `color: mat-color($primary, 500);`
If you want a component which can react to specific themes, things get more cumbersome.
The core idea is that you provide your own mixin from the component, and the using code pushes the relevant theme to that mixin.
(Which is essentially what you're doing for existing Material components with the `@include angular-material-theme($app-theme);` call).

https://material.angular.io/guide/theming-your-components has the information, though it is not exactly in the friendliest tutorial format.

**Comment by Ploppy3** [comment]
Ok, thank you very much.
