### ISSUE TITLE
Opening mat-menu for the first time in MS Edge causes scrollbars to show

### ISSUE THREAD

**Issue by kygr1990** [angular/material2#12112]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Mat-menu scrollbars shouldn't show on first-time render on MS Edge if styling is not specified.

#### What is the current behavior?
Scrollbars in mat-menus are shown on first time rendering on Edge. Subsequent opening of mat-menus do not render scrollbars. Disabling and enabling overflow styling does not re-render scrollbars.

#### What are the steps to reproduce?
![mat menu scroll1](https://user-images.githubusercontent.com/25546303/42444562-b2f0f0ce-8370-11e8-8e46-b27ccfc61e9b.gif)
![mat menu scroll2](https://user-images.githubusercontent.com/25546303/42444693-029e0f4e-8371-11e8-815b-9185cda4d812.gif)

#### What is the use-case or motivation for changing an existing behavior?
This would appear to be incorrect behaviour for the mat-menu component

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Microsoft Edge 38.14393.2068.0
Microsoft EdgeHTML 14.14393
"@angular/material": "^6.2.0"
"@angular/core": "^6.0.3"

**Comment by crisbeto** [comment]
I wasn't able to reproduce the issue by adding extra content to the menu. Can you post an example that shows the issue? You can fork one of the [examples from the docs](https://material.angular.io/components/menu/examples).

**Comment by kygr1990** [comment]
Hi, I was able to reproduce it. Kindly check the below link:
https://stackblitz.com/edit/angular-nq6s32?file=app/menu-overview-example.css

Basically by simply specifying 
`[mat-menu-item] {
  width: 230px;
}`

I was able to reproduce the issue with reference to the above browser version.

![mat menu scroll3](https://user-images.githubusercontent.com/25546303/42499356-d52c7582-842e-11e8-8f56-074061957d78.gif)
