### ISSUE TITLE
Inconsistent behavior of component's theme when using custom theme

### ISSUE THREAD

**Issue by ayush987goyal** [angular/material2#12110]
#### Bug:
The themes of components behave inconsistently when using a custom theme. 

#### What is the expected behavior?
The behavior should be consistent across all the variants.

#### What is the current behavior?
The components use the custom theme when given the class to them only with `primary` pallet and not with others (See the stackblitz). Others needs to be wrapped with a parent element with the custom theme class.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ams4yt

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Version 6 for all the material and core modules

**Comment by crisbeto** [comment]
That's because the theme classes are intended to be applied on a parent element, otherwise we'd have t generate double the amount of selectors: one targeting the element and another targeting a parent. The `primary` works since this is what we target by default.

**Comment by ayush987goyal** [comment]
Thank's for the clarification.
