### ISSUE TITLE
Expansion panel always opened

### ISSUE THREAD

**Issue by yoedusvanyh** [angular/material2#12118]
#### Bug, feature request, or proposal:
Soma way to put the panel always opened

#### What is the expected behavior?
Don't close never

#### What is the current behavior?
toggle always

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by crisbeto** [comment]
You can have an expansion panel be `expanded` and `disabled` which will prevent the user from toggling it. [Here's an example](https://stackblitz.com/edit/angular-wd3atn?file=app/expansion-overview-example.html).
