### ISSUE TITLE
`md-grid-list`, `md-grid-tile` can't find the way how to align items to left/right

### ISSUE THREAD

**Issue by beatadelura** [angular/material2#1212]
#### Bug, feature request, or proposal:

I can't find the way how to align `md-grid-tile` content to left/right.
#### Which versions of Angular, Material, OS, browsers are affected?

material ver: `2.0.0-alpha.8-1`,
angular2 ver: `2.0.0-rc.6`

**Comment by jelbourn** [comment]
@crisbeto Can we determine if there a bug here or if this is just a question?

**Comment by crisbeto** [comment]
@beatadelura could you post the code that you're using?

**Comment by beatadelura** [comment]
@crisbeto I decided, I will not use grid from `material2` so I don't have the code. Anyway I tried to use the same code from [here](https://github.com/angular/material2/blob/master/src/lib/grid-list/README.md)

**Comment by MohammadKTaha** [comment]
the solution is to remove style.css from angular-cli.json
