### ISSUE TITLE
sidenav (over mode) disable backdrop click to close

### ISSUE THREAD

**Issue by istiti** [angular/material2#1213]
#### Proposal:

Actually when we use sidenav in over mode, we can't disable closing sidenav when clicking on backdrop, any enhancement in mind ?

**Comment by todrules** [comment]
You could use 'pointer-events: none' on the sidenav layout. Just make sure you add 'pointer-events: initial' to any child objects that you want to click on.

**Comment by istiti** [comment]
thanks this workaround will help me , many thanks!!! it will be nice if there is option to disable closing sidenav when clicking on  backdrop thanks

**Comment by istiti** [comment]
https://files.gitter.im/angular/material2/pmEd/sidenav-error.gif Strange error

**Comment by mmalerba** [comment]
@jelbourn how about if we add something like this?

```
@Input('backdrop-action')
backdropAction: 'close' | 'none' | () => boolean = 'close';
```

that way its easy to close or do nothing, but you can still do custom stuff if you like

**Comment by jelbourn** [comment]
@mmalerba we could make it align with the overlay and dialog. Overlay exposes a `backdropClick` observable that lets you do whatever you want, and dialog has a `disableClose` option that prevents the dialog from closing itself based on backdrop click or escape key.

**Comment by mmalerba** [comment]
That seems a little more awkward since you have to set two properties, one to stop the default action and one to supply your own. can we make the overlay work like my proposal instead? :p

**Comment by jelbourn** [comment]
The overlay just exposes the observable to let the component do whatever it wants. The dialog doesn't expose the observable and just has `disableClose`. For the sidenav I'd think that `disableClose` would make sense since I'm not sure what else you'd do with a backdrop clip.

**Comment by mmalerba** [comment]
#1427 is requesting a callback

**Comment by christophechevalier** [comment]
I have a similar error (same to @istiti) when I close the sidenav either by :
- clicking on the backdrop
- doing it programmatically : `this.mySidenav.close()`

![image](https://cloud.githubusercontent.com/assets/7148846/20628340/b4998598-b325-11e6-99d2-1d4820d8bfca.png)

Am I the only one (is there something wrong with my code) ? Or is it something known ?

Thanks

**Comment by mmalerba** [comment]
@christophechevalier see #1899

**Comment by mmalerba** [comment]
This has been implemented via the `disableClose` property on `<md-sidenav>`
