### ISSUE TITLE
<mat-dialog-content> Scrolls wrong because max-height: 65vh

### ISSUE THREAD

**Issue by BamiGorengo** [angular/material2#12134]
The `<mat-dialog-content>` Scrolls wrong because there is a `max-height: 65vh` in the style file of the dialog. I tryed to maka a stackblitz, but i cant make it work: https://stackblitz.com/edit/angular-zzvc3z I get errors there that i never saw before in my IDE.

But if someone can fix this then its ready i think and will show the problem. As fallback here a screenshot: http://prntscr.com/k4s52q

When i overwrite the `max-height` with `auto` then it looks nearly perfect, but then for somehow the `mat-dialog-title` scrolls away if i scoll down.

And when i click on a mobile device on a input, then opens the keyboard and the content is not 100% scrollable. its not possible to see the first and the last input.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

In particular, this issue says the behavior is "wrong", but doesn't elaborate on what you expect the behavior to be.

**Comment by etonyali** [comment]
Try this: 
`.mat-dialog-content {
    max-height: unset;
}`
