### ISSUE TITLE
Is normalize.css required?

### ISSUE THREAD

**Issue by davidshen84** [angular/material2#12133]
#### Bug, feature request, or proposal:

Maybe a bug.

#### What is the expected behavior?

When creating a `material-nav` component, the menu and the navigation bar should align correctly.

#### What is the current behavior?

There's a margin at the top of the title bar, but no margin at the top of the menu bar. 

#### What are the steps to reproduce?

I asked a question at https://stackoverflow.com/questions/51258963/angular-material-navigation-bar-not-aligned/51259364?noredirect=1#comment89501187_51259364, and it was solved. But I think it might be a bug.

#### What is the use-case or motivation for changing an existing behavior?

Want to know if it is really a bug.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.1
typescript                   2.7.2
```

**Comment by crisbeto** [comment]
`normalize.css` isn't required, but we have a rule that Material shouldn't touch elements that it doesn't "own", hence why we don't reset the margin on the `body`.

**Comment by davidshen84** [comment]
So the margin on the top of the navigation bar is expected? I think that looks strange. Maybe I used the `material-nav` component in a wrong way? But I did not find any special notes on https://material.angular.io/guide/schematics regarding how to use the component.

**Comment by crisbeto** [comment]
It's expected that you'll reset it yourself.

**Comment by davidshen84** [comment]
Thanks. At least I now know everything I did was correct, and it's only the result is not what I expected.

**Comment by lonix1** [comment]
@polypus74 What did you decide to use at the end? I thought of extracting "reboot" from bootstrap, but then decided it was easier to go with "normalize.css" package.
