### ISSUE TITLE
Select and deselect All Options in mat-select

### ISSUE THREAD

**Issue by Hamza945** [angular/material2#12135]
#### I am using Angular Material 5 and want to make this costume `SelectAll` functionality.
![select-alls](https://user-images.githubusercontent.com/15921695/42517300-d2360d4e-8478-11e8-90ec-f75c6f027171.PNG)

#### I have tried to add select and deselect all mat-option but i am getting below error.

ERROR Error: Uncaught (in promise): Error: Template parse errors:
There is no directive with "exportAs" set to "ngModel" ("er="Analysis Type" disableRipple [formControl]="documentTypesFormCtrl" [(ngModel)]="selectedValues" [ERROR ->]#analysisType="ngModel" multiple (change)="updateDocumentTypes();">

#### This is my current code.
<mat-select class="analysis-drop" placeholder="Analysis Type" disableRipple 
       [formControl]="documentTypesFormCtrl" 
       [(ngModel)]="selectedValues" 
       #analysisType="ngModel" multiple (change)="updateDocumentTypes();">
          <mat-option
                  class="selectAllVals"
                  [value]="year"
                  (click)="selectAll(analysisType, documentTypesList)">
Select All
</mat-option>
<mat-option *ngFor="let documentType of documentTypesList " [value]="documentType.code">{{documentType.desc}}
</mat-option>
</mat-select>

Please let me know what I should change in it. 
Thanks in advance.

**Comment by jelbourn** [comment]
Adding an extra "action" option like this ins't something we support, since it doesn't fit in well with the accessibility interaction pattern for the select. #11799 added a select-all keyboard shortcut, which does fit into the a11y pattern; you can add an additional button next t the select that would do the same thing.

**Comment by Hamza945** [comment]
Hi @jelbourn ,

Thanks for the quick response. I have tried it but still getting error. I am using [formControl] in html binding. When I remove it then it works otherwise not. I need this [formControl] to get the values of form. Can you please look at this URL ?

[https://stackblitz.com/edit/angular-material-select-multi-qkyxzj](url)

I Would be very thankful to you.
Thanks in advance.

**Comment by hailbop** [comment]
Does anyone know how in the heck to make a div with a form disappear upon deselect? onSelectionChange is supposed to account for deselect, but idk how to remove a div that's already appeared without explicitly adding a "remove" button. I want deselect to take care of this somehow.
