### ISSUE TITLE
Critical bug - angular material 6.3.2 - Date picker disabled property not working

### ISSUE THREAD

**Issue by avindor** [angular/material2#12148]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

According to the documentation, when setting the disabled property on the input of a date picker component, the entire component should be disabled

Here is a part of the documentation:

Disabling parts of the datepicker
As with any standard <input>, it is possible to disable the datepicker input by adding the disabled property. By default, the <mat-datepicker> and <mat-datepicker-toggle> will inherit their disabled state from the <input>, but this can be overridden by setting the disabled property on the datepicker or toggle elements. This can be useful if you want to disable text input but allow selection via the calendar or vice-versa.

#### What is the current behavior?

when setting disabled property on the input, the input is editable and a value of a date can be deleted.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

here is a html code snippet:

```
  <mat-form-field class="col-auto" [hidden]="!endDateControl.value">
    <input  disabled formControlName="insuranceEndDate" matInput [matDatepicker]="picker" placeholder="{{'policy.endDate' | translate}}" >
    <mat-datepicker-toggle  matSuffix [for]="picker"></mat-datepicker-toggle>
    <mat-datepicker  #picker></mat-datepicker>
  </mat-form-field>

```
As you can see, the input field has a disabled property, but it is editable and the value of the date can be deleted

#### What is the use-case or motivation for changing an existing behavior?

Critical bug - cannot use date picker when disabling it is required

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cdk                       6.3.2
@angular/cli                       6.0.8
@angular/material                  6.3.2
@angular/material-moment-adapter   6.3.2
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
rxjs                               6.2.1
typescript                         2.7.2
webpack                            4.8.3

#### Is there anything else we should know?

Worked on 5.* version of angular, but after upgrading to latest version a week ago, stopped working

**Comment by crisbeto** [comment]
This sounds like there might be something wrong with your setup. [Here's an example that's working](https://stackblitz.com/edit/angular-dbtjed?file=app/datepicker-overview-example.html).

**Comment by avindor** [comment]
here is a modification of your example, as you can see, I can edit the form:

https://stackblitz.com/edit/angular-dbtjed-4jrz6a?file=app%2Fdatepicker-overview-example.ts
 
After ngAfterViewInit, I'm updaing the form via code...

**Comment by julianobrasil** [comment]
@avindor, you shouldn't disable a reactive control using the `disabled` atribute. There's a message in your stackblitz demo console pointing in this direction:

```
It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
you. We recommend using this approach to avoid 'changed after checked' errors.

Example: 
form = new FormGroup({
first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
last: new FormControl('Drew', Validators.required)
});
```

Here the stackblitz: https://stackblitz.com/edit/angular-dbtjed-rckoqs?file=app%2Fdatepicker-overview-example.ts

**Comment by avindor** [comment]
Thanks! that works. 
I see it's a reactive form control behavior. You can close this issue. Maybe you can add to the examples in the documentation a reactive form disabling. The same code did work in previous versions of angular, but after upgrading to the latest version - stopped working.
