### ISSUE TITLE
Module build failed: Error: Can't resolve '../../../~@angular/material/prebuilt-themes/_deeppurple-amber.css'

### ISSUE THREAD

**Issue by QingBei** [angular/material2#12145]
#### Bug, feature request, or proposal:
I have an Angular project created with Angular-cli, and after I installed the Angular material as its documentation, `npm install --save @angular/material @angular/cdk` and insert the related theme into my styles.less file, the build output the above error `Module build failed: Error: Can't resolve '../../../~@angular/material/prebuilt-themes/_deeppurple-amber.css'`. i have tried to remove the tilde sign, but it not work at all.

#### What is the expected behavior?
build with no errors with the material theme

#### What is the current behavior?
build with errors with the material theme

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version: 6.0.7
Material version: 6.3.2
OS: Windows 10 professional 
TypeScript version: 2.7.2
Browser: Chrome

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/17331623/42548671-e14da990-84fa-11e8-9f44-22eba2890f7f.png)
![image](https://user-images.githubusercontent.com/17331623/42548684-feb86baa-84fa-11e8-8368-4b00811c0800.png)
![image](https://user-images.githubusercontent.com/17331623/42548722-2a4ffd3c-84fb-11e8-82f7-4de2b3b5448e.png)

**Comment by Chan4077** [comment]
Can you try to use SCSS instead of LESS?

**Comment by QingBei** [comment]
thanks @Chan4077, but i prefer to use LESS, and previously with angular 4.4.4, it works, but now, do not know what's wrong with it...

**Comment by jelbourn** [comment]
I'd suggest opening an on https://github.com/angular/angular-cli. On the Angular Material side, the CSS files are present in the package; I'm not sure how the resource loading code paths work on the CLI side.
