### ISSUE TITLE
Mat dialog height 100%

### ISSUE THREAD

**Issue by Swoox** [angular/material2#12152]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If you put a mat-dialog with 100% you can update the top position.

#### What is the current behavior?
If the mat-dialog has a 100% height the margin-top will be automatic set to 0px.
If change it to 99% it will set the margin-top like normal.

#### What are the steps to reproduce?
https://angular-k9cs7f.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
I just wan to use heigth 100% cause if use from an inner html the margin-top will go to the top instead of inside the inner html.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Material 6.3.3

**Comment by jelbourn** [comment]
Closing this as working-as-intended. You can always use custom css (including the `panelClass` property of the dialog config) to customize spacing.
