### ISSUE TITLE
Autocomplete shouldn't propagate KeyboardEvents

### ISSUE THREAD

**Issue by kristjanjonsson** [angular/material2#12156]
#### Bug, feature request, or proposal:
Bug or Feature Request

#### What is the expected behavior?
If I listen on keyup/keydown on an input with autocomplete there should be some way for me to filter out the key events originating from interacting with the autocomplete panel. I think it should just not propagate them at all.

#### What is the current behavior?
When you select an item from the dropdown by clicking enter a KeyboardEvent is fired on the input element (not the MatOption or the panel) so there's no way of knowing whether the user pressed enter to autofill the input field or not.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-dikpb5?embed=1&file=app/autocomplete-simple-example.ts

#### What is the use-case or motivation for changing an existing behavior?
Use case is a standalone search input in a toolbar that's not contained by a form. On keypress Enter it should perform the search except when enter is pressed on the autocomplete.

**Comment by crisbeto** [comment]
That's because focus never actually leaves the input, which means that the events will originate from it. You should be able to use the [`MatAutocompleteTrigger.panelClosingActions`](https://material.angular.io/components/autocomplete/api#MatAutocompleteTrigger) to figure out when an option has been selected.

**Comment by kristjanjonsson** [comment]
@jelbourn Yes it does! For _keyup_ it doesn't because both `MatAutocompleteTrigger.panelOpen` and `MatAutocomplete.isOpen` are _false_ but switching to _keydown_ they return _true_.
