### ISSUE TITLE
"side" mode sidenav doesn't animate content

### ISSUE THREAD

**Issue by ollwenjones** [angular/material2#1215]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

Content should animate when opening/closing sidenav in 'side' mode, as it does in 'push' mode.
#### What is the current behavior?

Content position is adjusted instantly, while the draw animates. Likely CSS transitions not being applied to the contents.
#### What are the steps to reproduce?

Make a component with a sidenav set to 'side' mode:
http://plnkr.co/edit/H5s8r7830pbJTBGXfgWC?p=preview
#### What is the use-case or motivation for changing an existing behavior?

Disjointed appearance & inconsistent behavior with other modes.
#### Which versions of Angular, Material, OS, browsers are affected?

Angular RC 4-6, Material alphas 5-8. Windows. Chrome, FF, Edge
#### Is there anything else we should know?

No.

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/1040 possibly related?

**Comment by ollwenjones** [comment]
seems like it would be

**Comment by mmalerba** [comment]
fixed by #2486
