### ISSUE TITLE
Unvisible scrollbar in the select component on IOS

### ISSUE THREAD

**Issue by zyabko** [angular/material2#12175]
#### Bug:
In iPhone and iPad, the Material2 Select component periodically does not display a vertical scrollbar when dropping down or even user scrolling this drop-down list, so the user would not know there are more options through a snapshot. 

#### What is the expected behavior?
The scroll controll is always visible when the content in select component is scrolling.

#### What is the current behavior?
When there more than one select component on page and its opening you can't see the scroll even when scrolling opened select list. The list is scrolling but scroll control is unvisible. Its reproducing very offen, maybe in 50% of the times.

#### What are the steps to reproduce?
In https://material.angular.io/components/select/overview, open some examples in a row and try to scroll it. List in select is scrolling but time to time the scroll controll is unvisible.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, Material 5.2.5. All latest browsers. iPhone X / iOS 11.3 iPad mini 3 / iOS 11.2

**Comment by josephperrott** [comment]
Closing, the presence of a scroll indicator is controlled by the browser, it is unfortunately not possible for us to force an indication of the scroll position in the select list drop down.
