### ISSUE TITLE
"Tree with nested nodes" example from https://material.angular.io/components/tree/overview fails

### ISSUE THREAD

**Issue by sneurlax** [angular/material2#12179]
#### Bug:
The "Tree with nested nodes" example from https://material.angular.io/components/tree/overview fails for both Google Chrome Version 67.0.3396.99 (Official Build) (64-bit) and Firefox Quantum 61.0.1 (64-bit) with respective errors:

```
main.620a76fcfee14dac38ac.js:1 ERROR TypeError: this._tree.treeControl.getChildren(...).pipe is not a function
    at t.ngAfterContentInit (main.620a76fcfee14dac38ac.js:1)
...
```

and

```
ERROR TypeError: "this._tree.treeControl.getChildren(...).pipe is not a function"
ngAfterContentInit
...
```

That's all.  Thought you ought to know!

EDIT: I'm on Linux x64.

**Comment by furevor** [comment]
also example with checkboxes fails..
![scr22](https://user-images.githubusercontent.com/24428435/42671938-1715e48c-868d-11e8-9076-7738c6567184.png)

**Comment by jelbourn** [comment]
@DevVersion could you take a look at this one?

**Comment by DevVersion** [comment]
Just took a look and tried to reproduce it in our `demo-app/examples` and docs, but after clearing the cache on the docs everything seemed to work fine. 

Can someone of you please verify if it was just a caching issue?

**Comment by furevor** [comment]
Now I can see that this example work fine (I haven't clean cache, just went to example page) on [home page](https://material.angular.io/components/tree/examples), but I can't examine it on my local version at now. I will try update to 6.3.3 tomorrow and response, but I have tried it before answer at this topic. I don't think this issue will disappear by magic :)

**Comment by DevVersion** [comment]
Yeah, it could be also just that the cached resources expired due to a `7d` cache refresh. 

Yesterday, when I briefly looked at the issue, I also reproduced that those demo's didn't work on the docs, but there was no docs update AFAIK. Let's see how it works out. Thanks for the update!

**Comment by furevor** [comment]
I have tried it on local code, but updated to 6.4.0 before. Seems to be ok!

**Comment by DevVersion** [comment]
Perfect. I assume this issue can be closed then. Let me know if you run into any further issues.

**Comment by furevor** [comment]
Yes! Thanks!

**Comment by Hypenate** [comment]
On [StackBlitz](https://krgmxjankdn.angular.stackblitz.io) I'm still facing this issue.

**Comment by wrakky** [comment]
The StackBlitz link from the docs is still using `6.3.3`. If you update it to use `6.4.0` it works as expected (https://stackblitz.com/edit/angular-znfg1m)

**Comment by rachid-boukhani** [comment]
On the doc (Nested tree section)
That ` private _getChildren = (node: FileNode) => node.children;` should be 
`private _getChildren = (node: FileNode): Observable<FileNode[]> => observableOf(node.children);`

Don't forget to import
`import {BehaviorSubject, Observable, of as observableOf} from 'rxjs';`
