### ISSUE TITLE
Typescript version advancement to 2.9.x

### ISSUE THREAD

**Issue by IlCallo** [angular/material2#12177]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
Angular updated it's typescript dependency from 2.7.x to 2.9.x yesterday with 6.0.9 release.
Is Angular Material following anytime soon?

#### What is the current behavior?
Typescript dependency locked to 2.7.x

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.9
Material 6.3.3

**Comment by Springrbua** [comment]
@IlCallo According to the [Changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md), TypeScript 2.9 will come with Angular 6.1.0, which is now in RC0.
Angular 6.0.9 is still using TypeScript 2.7.

**Comment by IlCallo** [comment]
You're right, I didn't notice their master branch is for 6.1.x and not for 6.0.x.
Anyway I saw a PR has already be made for the version bump, that's great :)

**Comment by danwulff** [comment]
@crisbeto Any news on this?

**Comment by Springrbua** [comment]
@jelbourn @crisbeto will the TypeScript 2.9 support land in a 6.x.x version? Or do we need to wait for version 7?

**Comment by crisbeto** [comment]
The TypeScript version will be bumped to 3.1 in 7.0.

**Comment by Springrbua** [comment]
@crisbeto thanks for the quick reply!
