### ISSUE TITLE
Add autoFocus to BottomSheet component config

### ISSUE THREAD

**Issue by CharlBest** [angular/material2#12188]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Set autoFocus config property on the bottom sheet component (just like dialog) to configure if the first item in the bottom sheet should be focused (highlighted)

#### What is the current behavior?
No autoFocus on BottomSheet config

#### What are the steps to reproduce?
1) Create a bottom sheet component
2) Open bottom sheet with config (no property for setting if it should be auto focused)

#### What is the use-case or motivation for changing an existing behavior?
1) Keep it consistent with the dialog config as they are very similar
2) Prevent highlighting (focus) on list items or buttons when opening the bottom sheet

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
v6.2.1

#### Is there anything else we should know?
If this is added potentially add it to the global config token as well

**Comment by CharlBest** [comment]
Thanks man. This was done so quickly! Your awesome.

**Comment by keyiis** [comment]
autoFocus still not work
https://stackblitz.com/edit/angular-spp34u-tn8mmx
