### ISSUE TITLE
Using [min][max] on MatDatePicker causes year switcher to be really slow to open if also using the moment-date-adapter

### ISSUE THREAD

**Issue by jturmel** [angular/material2#12180]
#### Bug, feature request, or proposal:

Using [min][max] on MatDatePicker causes year switcher to be really slow to open if also using the moment-date-adapter

#### What is the expected behavior?

For it to not be slow

#### What is the current behavior?

It is slow to open the year switching panel.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5, Material 5

**Comment by jotatoledo** [comment]
reproduction?
