### ISSUE TITLE
MdTabs not working on Plunker template

### ISSUE THREAD

**Issue by Cayan** [angular/material2#1219]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

To work
#### What is the current behavior?

No tab is displayed
#### What are the steps to reproduce?

Plunker based on https://github.com/angular/material2/blob/master/src/lib/tabs/README.md
http://plnkr.co/edit/gWAuuLBiU1vU0jaRwO8q?p=preview
#### What is the use-case or motivation for changing an existing behavior?

To report bugs that depend on MdTabs
#### Which versions of Angular, Material, OS, browsers are affected?

Plunkr template from Aug., 19.
#### Is there anything else we should know?

Guess not

**Comment by andrewseguin** [comment]
Check out http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview to use as your plunkr template (found on the main page)

Here's an example of using it to make tabs: http://plnkr.co/edit/46LnwrLjH8yLhCS3r9vL?p=preview
