### ISSUE TITLE
Nested Menu causing ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by anisabboud** [angular/material2#12194]
#### Bug, feature request, or proposal:

Bug: When two menu items trigger the same nested menu, and you switch between them quickly with the mouse, you get `ExpressionChangedAfterItHasBeenCheckedError`.

#### What is the expected behavior?

Nested menus should work without errors.
Also passing data to submenus with [matMenuTriggerData](https://github.com/angular/material2/blob/master/src/lib/menu/menu.md#passing-in-data-to-a-menu) should work.

#### What is the current behavior?

Nested menu crashes.
![Screenshot](https://i.imgur.com/CsthCGH.png)

#### What are the steps to reproduce?

1. Open the official menu examples https://material.angular.io/components/menu/examples
2. Click the "Edit in StackBlitz" icon for **Nested menu**.
3. Open nested-menu-example.html
4. Change `[matMenuTriggerFor]="vertebrates"` to `[matMenuTriggerFor]="invertebrates"`.
5. Refresh, then switch quickly with the mouse between the submenus. You'll get this error in the console:
```
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.
Previous value: '@transformMenu: void'. Current value: '@transformMenu: enter'.
```

#### What is the use-case or motivation for changing an existing behavior?

I am trying to create a nested menu from dynamic data (e.g., imagine the animal data coming from a variable `data = {'vertebrates': ['Fish', 'Mammals'], 'invertebrates': ['Insects', 'Worms']}`.
The same submenu should display Fish+Mammals or Insects+Worms depending on the selected option (vertebrates/invertebrates), but matMenuTriggerData passes properly only for the first selection and then the whole menu stops working/crashes.

Sample code: https://stackblitz.com/angular/qrnkdlqppjy
```html
<button mat-button [matMenuTriggerFor]="animals">Animal index</button>

<mat-menu #animals="matMenu">
  <button mat-menu-item [matMenuTriggerFor]="submenu" [matMenuTriggerData]="{category: 'vertebrates'}">Vertebrates</button>
  <button mat-menu-item [matMenuTriggerFor]="submenu" [matMenuTriggerData]="{category: 'invertebrates'}">Invertebrates</button>
</mat-menu>

<mat-menu #submenu="matMenu">
  <ng-template matMenuContent let-category="category">
    <button mat-menu-item>You selected: {{category}}</button>
  </ng-template>
</mat-menu>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.9
Material 6.3.3

#### Is there anything else we should know?
After this is fixed, I suggest adding a 4th example to the [documentation](https://material.angular.io/components/menu/examples) called "Dynamic nested menu", which is similar to the 3rd "Nested menu" example but pulls the content from a `data` variable in the `.ts` file.

**Comment by anisabboud** [comment]
Thank you for looking into this, @crisbeto!
I just installed Material 6.4.1 and indeed switching between submenus no longer triggers the ExpressionChangedAfterItHasBeenCheckedError.

However, switching between submenus still doesn't pass the `[matMenuTriggerData]` properly.
It passes only to the first selected submenu, but the data is empty when selecting other submenus after the first. (Seems like a separated issue.)

See this simple example (same code snippet from the original post):
https://stackblitz.com/edit/angular-nevxe3?file=app/nested-menu-example.html

**Comment by anisabboud** [comment]
I opened a separate issue for [matMenuTriggerData]: https://github.com/angular/material2/issues/12467.

**Comment by RokiFoki** [comment]
There is a regression of this bug for 6.4.7. I have checked that it does not repro on 6.4.1 but it does on 6.4.7.

**Comment by jrood** [comment]
I'm seeing this also in 7.0.0
