### ISSUE TITLE
MatCard size increases on applying matRipple

### ISSUE THREAD

**Issue by batbrain9392** [angular/material2#12210]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
On adding `matRipple` to a `mat-card` with `mat-card-actions` and clicking on the action `button`, the card size increases since the `<mat-ripple-element>` appears at the bottom and takes up some empty space.

#### What is the expected behavior?
`<mat-ripple-element>` should not take up the aforementioned extra space.

#### What are the steps to reproduce?
1. Add a mat-card with mat-card-actions buttons
2. Add matRipple to mat-card
3. Click on the action button
https://stackblitz.com/edit/angular-material2-issue-2ocoap?embed=1&file=app/app.component.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.0.7
Material: 6.3.0
OS: win32 x64
Typescript: 2.7.2
Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

#### Screenshot
![matripple_issue](https://user-images.githubusercontent.com/16289648/42726064-deca2032-87ab-11e8-9b58-8a16b58d3835.png)

**Comment by DevVersion** [comment]
Thanks for your issue. I'm still looking for possible solutions to fix that issue. 

But closing this particular issue since there is already a similar one: https://github.com/angular/material2/issues/10898

**Comment by adarowiec** [comment]
it's still present

**Comment by rzeiler** [comment]
Use a div -Tag inside of mat-card -Tag. This Fix my issue.
`<mat-card matRipple *ngFor="let row of itmes"><div><mat-card-header><div mat-card-avatar>
{{row.ava}}
        </div>
        <mat-card-title>{{row.title}}</mat-card-title>
        <mat-card-subtitle>{{row.createdate | date}}</mat-card-subtitle>
      </mat-card-header>
      <mat-card-content>
        {{row.content}}
      </mat-card-content>
    </div>
  </mat-card>
`

**Comment by cyberbeast** [comment]
Or you could just add a custom style property to remove the bottom margin.
Something to the effect of -->
```<mat-card-content style="margin-bottom: 0">```
