### ISSUE TITLE
Error in theming.scss when executing ng serve

### ISSUE THREAD

**Issue by arianlopezc** [angular/material2#12225]
#### What is the expected behavior?
To run with no problems when ng serve.

#### What is the current behavior?
Currently, I just copied the code from the Material site and followed the steps but an error is popping out when I try to run ng serve.

My theme.scss file looks like this:

@import '~@angular/material/_theming.scss';

@include mat-core();

$candy-app-primary: mat-palette($mat-indigo);
$candy-app-accent: mat-palette($mat-blue, A200, A100, A400);

$candy-app-warn: mat-palette($mat-red);

$candy-app-theme: mat-light-theme($candy-app-primary, $candy-app-accent, $candy-app-warn);

@include angular-material-theme($candy-app-theme);

The error is this one

ERROR in ./src/styles.css (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./src/styles.css)
Module build failed: Syntax Error

(118:13) Missed semicolon

116 | // We use display: flex on this element exclusively for centering connected overlays.
117 | // When not centering, a top/left/bottom/right will be set which overrides the normal

118 | // flex layout.
| ^
119 | display: flex;
120 |
ℹ ｢wdm｣: Failed to compile.

Any idea guys?

**Comment by levgaas** [comment]
@arianlopezc please double check whether `styles` and `theming` files have the same extension either **.scss** or **.css**

**Comment by arianlopezc** [comment]
@levgaas I check on that but then another error happens

ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.sassLoader (/Users/NodeJS/node_modules/sass-loader/lib/loader.js:24:22)

**Comment by levgaas** [comment]
@arianlopezc try to create empty cli project with **--style=scss** flag. It will install deps that are needed and configure project properly for further usage.

Or try to install them manually.

Additional thought would be is to stick with css for now. Import css theming file for material module as described in docs.
