### ISSUE TITLE
Migration Angular 5 to 6, ng serve --prod add different CSS class mat-select and mat dialog

### ISSUE THREAD

**Issue by tosun-si** [angular/material2#12228]
Hello,

We have a strange behaviour, now in our project, after the migration from Angular 5 to 6.

We hesitated to open this issue in the Material project or Angular cli.

Sorry if our choice for project was not the good.

Our dependencies are : 

"dependencies": {
    "@angular/animations": "^6.0.6",
    "@angular/cdk": "^6.3.3",
    "@angular/common": "^6.0.6",
    "@angular/compiler": "^6.0.6",
    "@angular/core": "^6.0.6",
    "@angular/flex-layout": "6.0.0-beta.16",
    "@angular/forms": "^6.0.6",
    "@angular/http": "^6.0.6",
    "@angular/material": "^6.3.3",
    "@angular/platform-browser": "^6.0.6",
    "@angular/platform-browser-dynamic": "^6.0.6",
    "@angular/router": "^6.0.6",
....
}

"devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^6.0.6",
    "@angular/language-service": "^6.0.6",
     .....
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.7.2"
}

In dev mode, everything work well with "ng serve", but in prod mode with "ng serve --prod", we had problems.

**- The first problem is, all the "mat-select" in the firefox browser (52.8.0), are not correctly displayed.**

![image](https://user-images.githubusercontent.com/12008156/42753330-d9f1afa8-88f0-11e8-869e-3c8896eb0766.png)

The content of mat select is displayed at the bottom of page (this behaviour is only present in firefox). 

After some investigations, we saw that "cdk-overlay-pane" class is different in DEV and PROD.

- In dev "cdk-overlay-pane" has an attribut "top :202.094px"
- In prod "cdk-overlay-pane" has an attribut "bottom : -204.134px" (this cause the problem).

**- the second problem is, the material dialogs are not correctly displayed in chrome, in the prod mode only.**

With the following configuration : 

 const dialogRef = this.dialog.open(UserKillSessionsDialogComponent, {
     width: '500px',
     data: this.currentUser
  });

In dev, the dialog is correctly displayed

![image](https://user-images.githubusercontent.com/12008156/42753692-f8c12174-88f1-11e8-89aa-ff2eea23558f.png)

In prod the dialog is not correctly displayed

![image](https://user-images.githubusercontent.com/12008156/42754317-54a6a926-88f4-11e8-8008-03f20f4e1341.png)

Before, the migration, without "height" configuration, the height of dialogs taken dynamically the height of content.

Now, the height conf is mandatory only in the prod mode (and only in chrome). 

Very thanks for you help.

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
