### ISSUE TITLE
ERROR Error: Cannot find a differ supporting object '[object Object],[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.

### ISSUE THREAD

**Issue by sridharjonnalagadda** [angular/material2#12231]
#### Bug, feature request, or proposal:

IE11 issue only when using  mat-tab-group
<mat-tab-group>
    <mat-tab></mat-tab></mat-tab-group>

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
