### ISSUE TITLE
Angular Cli doest works with angularmaterial

### ISSUE THREAD

**Issue by tavo379** [angular/material2#1223]
npm WARN @angular2-material/core@2.0.0-alpha.8-1 requires a peer of @angular/core@^2.0.0-rc.6 but none was installed.
npm WARN @angular2-material/core@2.0.0-alpha.8-1 requires a peer of @angular/common@^2.0.0-rc.6 but none was installed
this happen when  i try to install packages of angular material 2, what happen and how can i resolved?

**Comment by DevVersion** [comment]
At first glance from your errors, it does not relate to the Angular CLI.

It seems like you have a wrong Angular 2 version installed, which is not compatible with the Angular Material 2 version you explicitly installed (`alpha.8-1`)

Try installing the latest Angular release candidate

```shell
npm i @angular/core@^2.0.0-rc.6 --save
...
```

**Comment by jelbourn** [comment]
@tavo379 Those are npm peer dependency warnings and have nothing to do with the angular cli.
