### ISSUE TITLE
"Unhandled Promise rejection: SyntaxError: Unexpected token import"

### ISSUE THREAD

**Issue by javascriptonian** [angular/material2#1224]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Component should load MdButton from "2angular2-material/button" and display the UI.

#### What is the current behavior?
Doesn't render anything and gives error on console 
```
zone.js:461 Unhandled Promise rejection: SyntaxError: Unexpected token import
	    at Object.eval (http://localhost:3000/app/navbar/navbar.component.js:12:16)
	    at eval (http://localhost:3000/app/navbar/navbar.component.js:37:4)
	    at eval (http://localhost:3000/app/navbar/navbar.component.js:38:3)
	Evaluating http://localhost:3000/vendor/@angular2-material/button/button.js
	Evaluating http://localhost:3000/app/navbar/navbar.component.js
	Evaluating http://localhost:3000/app/app.component.js
	Evaluating http://localhost:3000/app/index.js
	Evaluating http://localhost:3000/main.js
	Error loading http://localhost:3000/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: SyntaxError: Unexpected token import(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): Error: SyntaxError: Unexpected token import(…)
```

#### What are the steps to reproduce?
initi project using angular-cli and follow instructions on 3rd library installation instructions given on the angular-cli github page to set up material 2 components, and trying using any of the material 2 directives in a component. In my case:
```
import { Component } from '@angular/core';
import { MdButton } from '@angular2-material/button';

@Component({
  moduleId: module.id,
  selector: 'app-navbar',
  templateUrl: 'navbar.component.html',
  styleUrls: ['navbar.component.css'],
  directives: [MdButton]
})
export class NavbarComponent {
  navItems : Array<string> = [
    'About',
    'Services',
    'Policies',
    'Fees',
    'Contact'
  ]
}
```

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: rc4
Material: ^2.0.0-alpha.8-1
Browser: Chrome
OS: Windows10

#### Is there anything else we should know?
This has taken me all day and still couldn't fix..

**Comment by m0t0r** [comment]
@javascriptonian the problem might be because you use Angular **RC4** with alpha.8 which might not be compatible due to alignments with the latest Angular RCs. Also, make sure you run `TypeScript 2.0` as it's the requirement for material2 `alpha.8`

**Comment by richardklose** [comment]
Same issue here. 

Angular: 2.0.0-rc.6
Material: 2.0.0-alpha.8-1
Browser: Chrome
OS: macOS 10.11
Typescript: 2.0.0

**Comment by m0t0r** [comment]
@richardklose that's not a possible fix, that's what you should do. Check [CHANGELOG.md](https://github.com/angular/material2/blob/master/CHANGELOG.md) for `alpha.8`

**Comment by jelbourn** [comment]
@m0t0r is right; if you still want the CommonJS output, use the umd bundles from alpha.8 forward.

(also alpha.8 does depend on Angular RC6 or greater)
