### ISSUE TITLE
Link to ViewChildren in ViewChild docs

### ISSUE THREAD

**Issue by 1083** [angular/material2#12252]
#### Bug, feature request, or proposal:

Feature request.

#### What is the expected behavior?

Mention when to use ViewChildren in the ViewChild docs.

#### What is the current behavior?

No mention of ViewChildren on the ViewChild page, or vice versa. I eventually found what I was looking for here:

https://stackoverflow.com/questions/47957755/angular-material-2-matautocompletetrigger

Would be great to incorporate that info and a similar example in the official docs.

#### What are the steps to reproduce?

https://angular.io/api/core/ViewChild

**Comment by leolorenzoluis** [comment]
Fork the repo and submit a pull request would be great! 👍

**Comment by josephperrott** [comment]
Closing, since this is not something specific to the Angular Material library.  The usage of either [`@ViewChildren`](https://angular.io/api/core/ViewChildren) or [`@ViewChild`](https://angular.io/api/core/ViewChild) is dependent on your situation and what your needs are in querying.
