### ISSUE TITLE
Object doesn't support property or method 'fill' thrown from function ReflectionCapabilities.prototype._ownParameter  

### ISSUE THREAD

**Issue by ajborn** [angular/material2#12268]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
MatTable should load data in IE11

#### What is the current behavior?
Error `Object doesn't support property or method 'fill'` is thrown when loading data to table.
Function: `ReflectionCapabilities.prototype._ownParameters = function (type, parentCtor)`

#### What are the steps to reproduce?
Create MatTable as child component and pass data to the MatTable as input

#### What is the use-case or motivation for changing an existing behavior?
Need client app to work in IE11

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
LATEST

#### Is there anything else we should know?
Example of data being passed to mat-table
`<table mat-table (ngModel)="data" [dataSource]="dataSource" matSort [trackBy]="id">`

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

It sounds like you are trying to use a method `fill` which does not exist.  Its likely that `Array.fill` is being used, but this does not exist in IE11, you will either need to avoid using this method or include a polyfill in your app.

**Comment by ajborn** [comment]
Issue was with the .NET Core Angular Template I was using. Angular App does not have polyfills.
