### ISSUE TITLE
Dashboard Schematic does not work properly

### ISSUE THREAD

**Issue by da45** [angular/material2#12279]
#### What is the expected behavior?
The dashboard schematic will create a new component that contains a dynamic grid list of cards.

#### What is the current behavior?
Nothing is shown with the following console error: 

> ng:///AppModule/MainDashboard1Component.ngfactory.js:130 ERROR Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.
>     at NgForOf.push../node_modules/@angular/common/fesm5/common.js.NgForOf.ngOnChanges (vendor.js:24391)
>     at checkAndUpdateDirectiveInline (vendor.js:61488)
>     at checkAndUpdateNodeInline (vendor.js:62756)
>     at checkAndUpdateNode (vendor.js:62718)
>     at debugCheckAndUpdateNode (vendor.js:63351)
>     at debugCheckDirectivesFn (vendor.js:63311)
>     at Object.eval [as updateDirectives] (ng:///AppModule/MainDashboard1Component.ngfactory.js:143)
>     at Object.debugUpdateDirectives [as updateDirectives] (vendor.js:63303)
>     at checkAndUpdateView (vendor.js:62700)
>     at callViewAction (vendor.js:62941)

#### What are the steps to reproduce?
just create a schematic dashboard:
> ng generate @angular/material:material-dashboard --name my-dashboard

and call it:

`<my-dashboard></my-dashboard>`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular:  6.0.3
Material: 6.4.0
CDK: 6.2.0

**Comment by DevVersion** [comment]
Good catch. Has been fixed with https://github.com/angular/material2/commit/b5898281cac13e6b7fdda47ba2443feeb573d5ee#diff-0971fc26ab0589f93c1344ce29da61e4 and should be available in the next patch release.
