### ISSUE TITLE
[material.angular.io] Follow Material Design guidelines in examples

### ISSUE THREAD

**Issue by bushybuffalo** [angular/material2#12282]
#### Bug, feature request, or proposal:
I just noticed while looking at [the overview of the Dialog component](https://material.angular.io/components/dialog/overview#dialog-content) that the code sample illustrating dialog structure directives did not follow the Material Design guidelines regarding [dialogs](https://material.io/design/components/dialogs.html#anatomy) and [alert dialogs](https://material.io/design/components/dialogs.html#alert-dialog).

#### What is the expected behavior?
For dialogs, avoid ambiguous questions as "Are you sure ?" (even though I'm aware that the dialog's title is "Delete all", but then we could just ask "Delete all elements ?" as a title).
Since the provided dialog surely resembles an alert dialog, the example should also provide some explicit action labels, like "Cancel" and "Delete" instead of "No" and "Yes".

#### What is the use-case or motivation for changing an existing behavior?
I believe the examples provided in Angular Material's documentation should reflect Material Design guidelines.
I usually expect documentation examples to follow best practices, especially regarding a library as serious as Angular Material.

**Comment by josephperrott** [comment]
Closing as feature requests/issues with the material.angular.io site should be opened at its repo [here](https://github.com/angular/material.angular.io/issues/new).
