### ISSUE TITLE
MatMenu xPositioning value after ignored

### ISSUE THREAD

**Issue by LukasN** [angular/material2#12290]
#### Bug, feature request, or proposal:

Bug 

#### What is the expected behavior?

The xPositioning input value "after" should cause the menu to render after its trigger.

#### What is the current behavior?

 The menu opens on the left side of the trigger. 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

https://stackblitz.com/edit/angular-pkby21

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Currently we are running on: 
material 6.3.2,
angular: 6.0.7"
typescript: 2.8.3

#### Is there anything else we should know?

yPosition input binding works fine

**Comment by crisbeto** [comment]
This is the expected position. In this case `after` means that the menu's content will flow from the start of the trigger towards the end.
