### ISSUE TITLE
post back after click button 

### ISSUE THREAD

**Issue by MehranMazhar** [angular/material2#1229]
#### Bug, feature request, or proposal:

after i click on event like click ... form submit and post back is happened ... why ? 
<button md-raised-button class="md-primary" (click)="loadSubcomponent()">HELLO</button>

#### Which versions of Angular, Material, OS, browsers are affected?
angular RC 6
Material alpha.8

**Comment by JanStureNielsen** [comment]
To better support you, @MehranMazhar, please consider posting your support question on StackOverflow with all the details including a sample Plunker showing the problem.

**Comment by jmcgoldrick** [comment]
+1 to what @JanStureNielsen suggests, to answer your question, that's how forms work `input[type="submit"] ` or `button[type="submit"]` within a form will cause this behaviour unless you `preventDefault()` the click event - either do that or don't use `[type="submit"]`

**Comment by jelbourn** [comment]
@MehranMazhar it's not clear whether you're reporting a bug or asking a question, and then whether is has anything to do with material. Please follow the issue template.
