### ISSUE TITLE
Cannot use *cdkVirtualFor on a <ng-container> when viewport is autosize.

### ISSUE THREAD

**Issue by grant77** [angular/material2#12307]
#### Bug, feature request, or proposal:
Using  *cdkVirtualFor on a ng-container causes error, "TypeError: view.rootNodes[j].getBoundingClientRect is not a function", when you start scrolling.  This works, however, if I use a div instead.  It also works if I use "itemSize" instead of "autosize" on the viewport.

#### What is the expected behavior?
No error when scrolling.

#### What is the current behavior?
I get an error when scrolling.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-7pzvdl?embed=1&file=app/app.component.html

#### What is the use-case or motivation for changing an existing behavior?
Would like to be able to use ng-container instead of a div.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/cdk-experimental": "^6.4.0"

#### Is there anything else we should know?
No.

**Comment by crisbeto** [comment]
Looks like this was fixed in https://github.com/angular/material2/pull/12183.
