### ISSUE TITLE
MDList sample not working

### ISSUE THREAD

**Issue by vekexasia** [angular/material2#1230]
#### Bug, feature request, or proposal:
List with avatar and titles is not working properly?

#### What is the expected behavior?
<img src="https://material.angularjs.org/material2_assets/list/list-with-avatar-2.png">

#### What is the current behavior?
http://plnkr.co/edit/s07vMUlEudnSS4DqcFAv?p=preview

#### What are the steps to reproduce?
Take a look at app.component.html

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://plnkr.co/edit/s07vMUlEudnSS4DqcFAv?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Not sure on plunkr latest version on local machine

**Comment by jelbourn** [comment]
@vekexasia I think that plunker template is just out of date. With the latest version it seems fine:
http://plnkr.co/edit/ZXR6dZssbPZcvSabFyLa?p=preview
