### ISSUE TITLE
Mark old update tool as outdated

### ISSUE THREAD

**Issue by DevVersion** [angular/material2#12318]
We should mark the old `material-update-tool` as deprecated / outdated. 

_Possible ways_:

* Deprecating in NPM
* Using Github's archive ability. 

Either one of those possibilities, or both. Regardless of those, we should add a note in the `README.md`.

* Related PR that **should** be merged: https://github.com/angular/material-update-tool/pull/28

**Comment by jelbourn** [comment]
I published a version with the notice in the readme and marked the package with `npm deprecate`
