### ISSUE TITLE
Hi there is a way to install this without angular2-cli ?

### ISSUE THREAD

**Issue by clust3rsekt0r** [angular/material2#1232]
#### Bug, feature request, or proposal:
I saw the get started guide and all is for angular2-cli is  a mandatory thing ? there is a way to import all this into a clean angular project from the scratch ?

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by leocaseiro** [comment]
Have you tried using npm?

You can see the list of all components that are available here: https://www.npmjs.com/~angular2-material 

Eq: `npm install @angular2-material/button --save`

**Comment by jelbourn** [comment]
@clust3rsekt0r Please only use GitHub issues for bug reports / feature requests; direct questions to the mailing list, gitter, etc.
