### ISSUE TITLE
stepper to have all steps extended or selected so it can show all the steps content at the same time

### ISSUE THREAD

**Issue by Masber** [angular/material2#12328]
#### Bug, feature request, or proposal:
request

#### What is the expected behavior?
I would like to be able to extended all steps content (not just the label) at once.

#### What is the current behavior?
stepper only have one step as selected

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
My intention is to use stepper to show a sequence of events

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "5.2.8",
    "@angular/cdk": "^5.0.2",
    "@angular/common": "5.2.8",
    "@angular/compiler": "5.2.8",
    "@angular/core": "5.2.8",
    "@angular/forms": "5.2.8",
    "@angular/http": "5.2.8",
    "@angular/material": "^5.0.2",
    "@angular/platform-browser": "5.2.8",
    "@angular/platform-browser-dynamic": "5.2.8",
    "@angular/router": "5.2.8",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "ng-recaptcha": "^3.0.2",
    "pdfmake": "^0.1.35",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20"

**Comment by crisbeto** [comment]
This sounds like a use case for `mat-expansion-panel`.

**Comment by josephperrott** [comment]
Closing, as this does not fit within how the stepper is defined in the material spec this is not something we would add to the stepper.   As @crisbeto noted, thi
