### ISSUE TITLE
scroll lag after opening and closing calendar (or any other overlay like autocomplete)

### ISSUE THREAD

**Issue by fxck** [angular/material2#12341]
See https://youtu.be/1VE5vHXnL84 

It feels as if something is not properly cleaned up.

The popover component I'm using is https://github.com/ncstate-sat/popover and is internally using overlay as well.

Also worth noting is that it happens with or without dev tools open and nothing seems out of the ordinary in the performance and rendering tab.

I'll try to make a repro later today.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.4.0 material, 6.0.9 angular

**Comment by fxck** [comment]
https://stackblitz.com/edit/material-scroll-lag-9qzbai?file=app%2Fsimple-example%2Fsimple-example.component.ts

could not replicate it, any ideas? I mean if it was for the sheer amount of components it contains, it wouldn't just start behaving like this after opening component with an overlay, right..

**Comment by crisbeto** [comment]
Maybe this is happening as a result of a combination of components? It might be easier to see what's going on by doing a recording in the "Performance" tab.

**Comment by crisbeto** [comment]
One more thing to try: once you've opened it a few times and it starts lagging, can you try finding the `cdk-overlay-container` in the DOM and adding a `display: none` to it, and seeing if the lag goes away?

**Comment by fxck** [comment]
> One more thing to try: once you've opened it a few times and it starts lagging, can you try finding the cdk-overlay-container in the DOM and adding a display: none to it, and seeing if the lag goes away?

Can't, the whole app is inside a sidenav so it would hide everything. Which is also one thing I forgot to add to the reproduction.

**Comment by fxck** [comment]
> One more thing to try: once you've opened it a few times and it starts lagging, can you try finding the cdk-overlay-container in the DOM and adding a display: none to it, and seeing if the lag goes away?

Can't it would hide the popover as well.

**Comment by fxck** [comment]
Ok, that did fix the lag.

**Comment by crisbeto** [comment]
Cool, thanks for checking. In that case we should move the detached overlays out of the DOM completely.

**Comment by fxck** [comment]
I still can't quite understand why is it happening, that `cdk-overlay-connected-position-bounding-box` seems harmless..

**Comment by crisbeto** [comment]
It's because, even though they're transparent and unclickable, the elements are still being rendered over the page. Since they're `position: fixed`, they have to be redrawn while you're scrolling.

**Comment by fxck** [comment]
Was this really fixed? Experiencing the problem still using 6.4.7..

**Comment by fxck** [comment]
And it looks like `cdk-overlay-container` is still in DOM after closing the popover..

**Comment by crisbeto** [comment]
The `cdk-overlay-container` is still in the DOM, but it's `display: none` so it won't have an effect on rendering.

**Comment by fxck** [comment]
But it does. Or something does. Nothing really changed since it was "fixed". See https://youtu.be/rvzkiTx4_Fk it's smooth the first time I open the popover, after I close it and open it again, it lags a lot..

**Comment by crisbeto** [comment]
I'm not sure why it ended up in both versions, but an easy way to verify it is to open and close the overlay a couple of times, click around the page somewhere to trigger a round of change detection and see if the `cdk-overlay-container` is empty.

**Comment by fxck** [comment]
![image](https://user-images.githubusercontent.com/1303561/46107476-c14f5300-c1db-11e8-9c50-786f323b3ee5.png)

Also `cdk-overlay-container` is indeed `display: none;`.. but it doesn't fix the lag.. funnily enough it did, when I previously added it manually, as mentioned here https://github.com/angular/material2/issues/12341#issuecomment-408350401

**Comment by crisbeto** [comment]
Then it's most likely something different, but it's hard to say by looking at a video.

**Comment by fxck** [comment]
What can I do?

**Comment by crisbeto** [comment]
Taking a performance recording while scrolling on a list that is laggy could help identify where it's coming from.
