### ISSUE TITLE
[Selection] Better typing for onChange property

### ISSUE THREAD

**Issue by IlCallo** [angular/material2#12347]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
SelectionModel onChange should return Subject or null based on the input value given to the constructor.

#### What is the current behavior?
SelectionModel onChange returns Subject or null without thinking about the input values.

#### What is the use-case or motivation for changing an existing behavior?
I know that the SelectionModel I created emits values, it knows too, but TS complains.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
Atm I don't now if it's possible do do it automatically at the moment, but once TS support bumps to 2.8 conditional types can be used.
Currently, adding an optional type to the SelectionModel class to explicitly express what it should emit can be a workaround.

**Comment by crisbeto** [comment]
In retrospect, I think the better approach here would've been to type it to always be a `Subject`, but just not emitting to it if `emitChanges` is false.
