### ISSUE TITLE
Set data table columns dynamically

### ISSUE THREAD

**Issue by micobarac** [angular/material2#12359]
#### Bug, feature request, or proposal:

I am trying to make a reusable component with data table, but right now it's not possible. Setting columns dynamically through data binding would be a nice feature to make data table reusable.

#### What is the expected behavior?

```html
<table mat-table [dataSource]="dataSource" [columns]="columns" matSort>
...
</table>
```

#### What is the current behavior?

Right now, you have to hard code table structure using `ng-container`:

```html
<!-- Name Column -->
<ng-container matColumnDef="name">
  <th mat-header-cell *matHeaderCellDef mat-sort-header> Name </th>
  <td mat-cell *matCellDef="let element"> {{element.name}} </td>
</ng-container>
```

#### What are the steps to reproduce?
[Official example](https://stackblitz.com/angular/gjvxypxbggrd?file=app%2Ftable-pagination-example.ts)

#### What is the use-case or motivation for changing an existing behavior?

I want to make one data table component wrapper component, which would be capable of showing data, with dynamic columns structure. Something like this:

```typescript
  columns: Array<any> = [
    { name: 'position', label: 'No.' },
    { name: 'name', label: 'Name' },
    { name: 'weight', label: 'Weight' },
    { name: 'symbol', label: 'Symbol' }
  ];
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```shell
Angular CLI: 6.0.8
Node: 9.8.0
OS: darwin x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.2
@angular/cli                      6.0.8
@angular/flex-layout              6.0.0-beta.16
@angular/material                 6.3.2
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by micobarac** [comment]
Actually, I have made it work like this:

```html
    <table mat-table [dataSource]="dataSource" matSort>
  
      <ng-container *ngFor="let column of columns" matColumnDef="{{column.name}}">
        <th mat-header-cell *matHeaderCellDef mat-sort-header>{{column.label}}</th>
        <td mat-cell *matCellDef="let element"> {{element[column.name]}} </td>
      </ng-container>
  
      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
    </table>
  
    <mat-paginator [pageSizeOptions]="[5, 10, 20]" showFirstLastButtons></mat-paginator>
```

```typescript
  columns: Array<any> = [
    { name: 'position', label: 'No.' },
    { name: 'name', label: 'Name' },
    { name: 'weight', label: 'Weight' },
    { name: 'symbol', label: 'Symbol' }
  ];

  displayedColumns: string[] = this.columns.map(column => column.name);
```

This may not be the optimal solution. Any other suggestion could be valuable.

**Comment by jelbourn** [comment]
Yep, that's the way.

**Comment by pcnate** [comment]
In case anyone else is having issues like me:

I had an `*ngIf="displayedColumns.length > 0"`. Instead use `[class.hidden]="displayedColumns.legth < 1"` and set `.hidden` to hide the table in CSS

**Comment by TctRajasekar** [comment]
How to add Edit button in mat table

**Comment by gayathrisuresh10** [comment]
How to add a link in mat-cell inside dynamic column in mat-table

**Comment by nipuna** [comment]
Here you are defining columns in an array and than binding it. How can we rather bind to the json data source for which we dont know what will be .

**Comment by SevdaCimen** [comment]
<span *ngFor="let name of column .name; let i = index" tool>
       {{  column.name }}
   <ng-container *ngIf="i !== column.name.length - 1">,</ng-container>
  </span>
another approach for this problem !

**Comment by jiteshsamal** [comment]
How to add a link or a button in mat-cell inside dynamic column in mat-table
