### ISSUE TITLE
Inconsistent columns width on data table pagination

### ISSUE THREAD

**Issue by micobarac** [angular/material2#12357]
#### Bug, feature request, or proposal:

Columns width should stay unchanged when using pagination option.

#### What is the expected behavior?

Columns width should be consistent across pagination actions.

#### What is the current behavior?

Currently, columns width vary with no logical explanation.

#### What are the steps to reproduce?

[Official example](https://stackblitz.com/angular/gjvxypxbggrd?file=app%2Ftable-pagination-example.ts)

#### What is the use-case or motivation for changing an existing behavior?

Having visually consistent data grid.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```shell
Angular CLI: 6.0.8
Node: 9.8.0
OS: darwin x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.2
@angular/cli                      6.0.8
@angular/flex-layout              6.0.0-beta.16
@angular/material                 6.3.2
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by jelbourn** [comment]
This is the expected behavior; the column size behavior is purely from the native `<table>`. We're interested in eventually exploring auto-sizing features for the table, but don't have anything specifically scheduled. In the meantime, you can use CSS to control the size of columns.

**Comment by micobarac** [comment]
I noticed that when I use table with flex, the column sizes stay consistent on paging and sorting.

**Comment by jelbourn** [comment]
Yeah, there are styling trade-offs between using the flex-table and the native table, which is part of the reason why we support both.
