### ISSUE TITLE
How to integrate with latest ver of angular-cli ?

### ISSUE THREAD

**Issue by usmanwalana** [angular/material2#1235]
As taken from angular-cli docs
```
`Lastly, you can delete these files as they are not needed anymore.

./config/karma-test-shim.js
./config/environment.js
./src/system-config.ts
./angular-cli-build.js
./typings.json
./.clang-format (if present)`
```
The angular-cli-build.js is removed so how to integrate material?

**Comment by cre8** [comment]
When using the webpack version of angular cli webpack will manage the imports, not you anymore. So you just need to install the packages via npm and import them to the files where you need them.

**Comment by jelbourn** [comment]
@usmanwalana Please only use GitHub issues for bug reports / feature requests; direct questions to the mailing list, gitter, etc.
