### ISSUE TITLE
Build warnings when mat-slide-toggle is used in application

### ISSUE THREAD

**Issue by mfilar** [angular/material2#12356]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
No warnings displayed when building prod version

#### What is the current behavior?
Warnings appear in console:

> "export 'MAT_SLIDE_TOGGLE_DEFAULT_OPTIONS' (imported as 'i19') was not found in '@angular/material/slide-toggle'

#### What are the steps to reproduce?
Update angular from version 6.3.3 (no warnings) to 6.4.0 (or 6.4.1)

#### What is the use-case or motivation for changing an existing behaviour?
Clear conscience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.4.0 & 6.4.1

**Comment by PascalHonegger** [comment]
Seems to be the same issue as #12242.
I also had the same issue in my project and was also able to fix it by doing a full re-install.

**Comment by jelbourn** [comment]
Closing this since it seems to be an environment issue. Feel free to open a new issue if you're able to point to a problem in Angular Material specifically.
