### ISSUE TITLE
The toggle method on mat-checkbox does not emit to valueChanges

### ISSUE THREAD

**Issue by adamdport** [angular/material2#12369]
#### Bug, feature request, or proposal:
Bug
#### What is the expected behavior?
`valueChanges` should emit whenever the checkbox's value changes

#### What is the current behavior?
If the checkbox changes value via the `toggle()` method, `valueChanges` does not emit

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-35rjy5

#### What is the use-case or motivation for changing an existing behavior?
Sometimes there are other places in the app that toggle a checkbox

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material 6.4.1

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material2/pull/11902.

**Comment by gizm0bill** [comment]
Like when?! It's been there since August what the heck are you guys waiting for??
