### ISSUE TITLE
Schematics/alias "materialNav" collides with another alias or schematic name.

### ISSUE THREAD

**Issue by DaSchTour** [angular/material2#12362]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Install runs through

#### What is the current behavior?
Error is thrown
Schematics/alias "materialNav" collides with another alias or schematic name.

#### What are the steps to reproduce?
* ng new
* ng add @angular/pwa
* ng add @angular/material

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.8
Node: 8.10.0
OS: darwin x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@angular/material                 6.4.1
@angular/pwa                      0.6.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

**Comment by getsali** [comment]
problem is fixed on angular cli 6.1 RC

**Comment by mbeckenbach** [comment]
@DaSchTour 
There is a work arround for it:
https://github.com/angular/angular-cli/issues/11632

**Comment by DaSchTour** [comment]
seams that the github search is pretty bad 🙄 
Thanks

**Comment by nishimura-yuji** [comment]
After updating to the latest version of angular cli, installation completed.

`ng update @angular/cli`

**Comment by baswanders** [comment]
Thanks @nishimura-yuji , that worked for existing projects!

And to fix it for new projects, update the CLI globally with:

`npm install -g @angular/cli`
