### ISSUE TITLE
sorting by index-column <mat-table>not working properly

### ISSUE THREAD

**Issue by marc0olo** [angular/material2#12366]
#### Bug, feature request, or proposal:
```html
<ng-container matColumnDef="position">
    <mat-header-cell *matHeaderCellDef mat-sort-header> No. </mat-header-cell>
    <mat-cell *matCellDef="let i=index"> {{i+1}} </mat-cell>
</ng-container>
```

#### What is the expected behavior?
Data can be sorted by index-column and values of index-column get sorted when data is sorted by another column.

#### What is the current behavior?
When using a column with the row-index the sorting is not working correctly. The row-index doesn't get sorted when data is sorted by another column.

It is not possible to sort the data by index-column.

#### What are the steps to reproduce?
Reproduce on StackBlitz:
- https://stackblitz.com/edit/sorting-with-index

#### Is there anything else we should know?
related to #10241

**Comment by jelbourn** [comment]
This is working as expected. By default, the sort-header uses the column name as a key to the data. In your example, the data does not have a "position" property. When using the `MatTableDataSource` (vs. using a custom data source), any sorting must be done based on some property of the data itself. With a custom data source, you're able to implement sorting with any custom behavior you might need.
