### ISSUE TITLE
Add Custom CSS File AFTER Material CSS Files

### ISSUE THREAD

**Issue by Auricopter** [angular/material2#12364]
Hello,

There are several older Stackoverflow Threads with this problem, however without a satisfying solution

https://stackoverflow.com/questions/42529838/how-to-change-the-angular-material-2-css-imports-order

https://stackoverflow.com/questions/48269519/how-to-adjust-import-order-of-css-files-in-angular-5

Is there a way to tell Angular to add Material CSS Files BEFORE our own Custom CSS File (like styles.css)?

**Comment by jelbourn** [comment]
This is the behavior of Angular itself; Angular Material doesn't control where styles tags are rendered.
