### ISSUE TITLE
Able to minimize dialog or bottom sheet like in google fonts or gmail

### ISSUE THREAD

**Issue by rohitkrishna12** [angular/material2#12367]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Able to open multiple dialog or bottom sheet and keep them minimized. Similar functionality like in Google Fonts or Gmail website

#### What is the current behavior?
Not able to minimize dialogs or bottom sheet

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
it would be helpful to show multiple concerning information & second hand actions that are connected to page but not directly and keeps the user interaction on same page without swapping multiple pages.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 6.0.3
Material - 6.3.3
OS: Windows 10
Typescript: 2.7.2
Browsers - All

**Comment by jelbourn** [comment]
Something like this would require a more full-blown windowing system, whereas dialog and bottom-sheet are more narrowly scoped in functionality. We don't have any plans to build something like this.

You should be able to build something similar, though, on top of the cdk/overlay code.

**Comment by rohitkrishna12** [comment]
@jelbourn  Thank you for the confirmation
