### ISSUE TITLE
Getting started guide unclear about dependency on @angular/animations

### ISSUE THREAD

**Issue by fetis** [angular/material2#12365]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
https://material.angular.io/guide/getting-started#step-2-animations
Getting started says that 
>If you don't want to add another dependency to your project, you can use the NoopAnimationsModule

So, I expect to don't install `@angular/animations` when I import this module

#### What is the current behavior?
Actually, `@angular/platform-browser/animations` uses the `@angular/animations` internally and it's not possible to compile a project without it.

Hence, the question what's the real difference between this to options?

At the moment it's not possible to use Material without `animations` module
Here's the stackblitz that illustrate the problem https://stackblitz.com/edit/angular-material-animations-problem

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 6.4.1

**Comment by jelbourn** [comment]
Yeah, the getting-started guide isn't very clear. The `@angular/animations` package is always required, but the animations themselves can be disabled.
