### ISSUE TITLE
MatDialog triggered from a leaflet map

### ISSUE THREAD

**Issue by ABC-ACL** [angular/material2#12373]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Normal behaviour for a Dialog

#### What is the current behavior?
The dialog doesn't close when it should and behaves strangely. Sometime it opens twice (just one onInit, though), and closes on lost focus. Hard to explain, but easy to reproduce with the most basic leaflet/matDialog examples.

#### What are the steps to reproduce?
Trigger the opening of a MatDialog from a leaflet map/layer, f.e.:
this.map.on('click', this.openDialog.bind(this));

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest Angular (cli)

**Comment by crisbeto** [comment]
It's hard to say what it could be without looking at the code, but I'd say that you probably have to wrap you `open` call in a `ngZone.run()`.

**Comment by jelbourn** [comment]
I was just about to say the same thing. I've seen this a couple times before, where event handlers from Google Maps specifically escape the zone. Doing
```
this.map.on('click', () => {
  this.ngZone.run(() => {
    this.openDialog();
  });
});
``

**Comment by qannoufoualid** [comment]
Hello, I have the same problem.
I tried the solution but it doesn't seem to work
