### ISSUE TITLE
bug bottomsheet

### ISSUE THREAD

**Issue by qq289089000** [angular/material2#12387]
#### Bug, feature request, or proposal:

i changed data source.
data table  in bottomsheet can't refresh .need click mouse .

**Comment by qq289089000** [comment]
`<tr  *ngFor="let i of dataList;let inx=index">
        <th scope="row">{{inx}}</th>
        <td>{{i.no}}</td>
        <td>{{i.name}}</td>
        <td>{{i.qty}}</td>
        <td>{{i.price}}</td>
      </tr>
`
```
  onChangeFilter(str){
this.dataList=[{},{}]
  }
```
need run double. element refresh

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
