### ISSUE TITLE
Rendering issue with html table and Mat-Elevation and scrolling

### ISSUE THREAD

**Issue by flipZomb** [angular/material2#12385]
#### Bug, feature request, or proposal:
Buy, maybe, or maybe this is intended ????

#### What is the expected behavior?
Elevation should continue on into the scroll area in my opionion.

#### What is the current behavior?
Putting a simple html table in a div with Mat-elevation shows slighly ugly result when a scrollbar comes into play.

![image](https://user-images.githubusercontent.com/33517613/43253073-5b2e4d44-90c4-11e8-954c-0c0406f8aca8.png)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-hta4it-44hwq3?file=app/radio-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.0
Material 6.4.1
See this  behaviour on Edge and Chrome

**Comment by flipZomb** [comment]
Thanks. that would be a work around, even though I feel it would be nicer if it would "work" with the scrolling too.

**Comment by ikkentim** [comment]
In that case you'd have to add `overflow: auto` to the div.

**Comment by flipZomb** [comment]
That does the trick. Great. Thank you !
