### ISSUE TITLE
Updated Material Guidelines from I/O 2018; Plans to incorporate them into material2

### ISSUE THREAD

**Issue by YeomansIII** [angular/material2#12397]
#### Bug, feature request, or proposal:
Proposal

#### Description
Are there any plans or roadmap to update components to the new Material Guidelines?

For example, Google has updated the [Material Input/Text Field guidelines](https://material.io/design/components/text-fields.html#usage) to significantly improve User Experience and text field discoverability.
![image](https://user-images.githubusercontent.com/3809115/43294515-a98bb384-910d-11e8-8b62-f8114c8bdb00.png)
I think that this is a very crucial change, as the original "underline" inputs provided a bad UX and confused users more so than not.

There are many other changes made to the Material Guidelines announced at I/O.

**I wanted to open a discussion about these changes and how best to incorporate them into the material2 package.**

**Comment by YeomansIII** [comment]
I see it's already implemented
https://material.angular.io/components/form-field/overview

**Comment by cnoize35** [comment]
But the timings of the material2 components are totally off compared to the mdc-web components implemented by Google.
The material2 components feel much more sluggish and don't seem to follow the timings provided by the material guidelines.  It's the main reason why i don't wanna use these components. They are simply not fun to work with if you have to use them 8 hours a day.
