### ISSUE TITLE
MatMenu - Double click of matMenu with data can lead to empty content

### ISSUE THREAD

**Issue by raphael22** [angular/material2#12399]
#### Bug, feature request, or proposal:
Bug: Double clicking on button passing data to a matMenu while it was already opened lead to an empty matMenu content.

#### What is the expected behavior?
Lazyloaded matMenu with data should be able to render even when re-triggered immediately.

#### What is the current behavior?
WHEN I Clicked on a button passing data to a matMenu.
IF I Double click on another button passing data to the same matMenu.
THEN matMenu content is empty
![image](https://user-images.githubusercontent.com/3912356/43311034-90cfd614-9189-11e8-9afb-ba0968ce7071.png)

#### What are the steps to reproduce?
Double-click mat-menu button in table list while a matMenu is already open.
Work also with the two button at the bottom, outside of table element.
[https://stackblitz.com/edit/angular-29mmpx](https://stackblitz.com/edit/angular-29mmpx)

#### What is the use-case or motivation for changing an existing behavior?
matMenu in a list or a table element often lead to empty menu

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.1.0
Material: 6.4.1
OS: Linux
Typescript: 2.9.2
Browser

**Comment by crisbeto** [comment]
This might be fixed https://github.com/angular/material2/commit/1e1751f61eca15eb9cf81581bb4c7e191d2a1bbd which will be in the next release.

**Comment by josephperrott** [comment]
@raphael22 can you confirm if this was sorted out in the latest release?
