### ISSUE TITLE
Add support for Armenian language in datepicker

### ISSUE THREAD

**Issue by jacksnipe24** [angular/material2#12417]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Material datepicker should be displayed in Armenian when using 
`{ provide: MAT_DATE_LOCALE, useValue: 'hy-AM' }`

#### What is the current behavior?
Material datepicker displays week names in english and months are displayed M01, M02, M03 and so on.
 
![upqwfm](https://user-images.githubusercontent.com/36839681/43355250-62fc61ee-926a-11e8-886f-34cfca08bc01.jpg)

#### What are the steps to reproduce?
Working minimal example  - https://stackblitz.com/edit/angular-6mbmxu

#### What is the use-case or motivation for changing an existing behavior?
Ability to use material datepicker in Armenian language

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: 6.0.3
Material: 6.4.0,
Typescript: 2.7.2,
OS: Windows

**Comment by jelbourn** [comment]
See https://material.angular.io/components/datepicker/overview#internationalization

Internationalization is performed by the date adapter. You can use one of the existing adapters (with their corresponding trade-offs), or implement a custom adapter to handle more specific cases.

**Comment by jacksnipe24** [comment]
@jelbourn Hi. Docs says to use MAT_DATE_LOCALE with specific value. I tried with Italian, French, Russian, Spanish, even Thai and Chinese. All that works, however when i want to use as a value some not so popular language, i get such behavior. Why there is support for some languages and not for the others ? Even though not widely used languages are supported by Angular

**Comment by jelbourn** [comment]
Which adapter are you using? If you're using the default NativeDateAdapter, it's just whatever your browser supports.

**Comment by jacksnipe24** [comment]
I am using MatNativeDateModule. What does that mean with "browser supports" ?

**Comment by lilitGrigoryan** [comment]
The localize work on firefox but not work on chrome . how to fix it?
