### ISSUE TITLE
Çoklu Dil Desteği

### ISSUE THREAD

**Issue by mcsajans** [angular/material2#12435]
Merhaba;

Çoklu dil desteğiniz bulunmuyor. Bu yüzden Türkçe olarak kaynakta bulamıyoruz. Eğer çoklu dile geçerseniz. Sizlere bu konuda destekte olabiliriz.

İyi Çalışmalar...

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by jelbourn** [comment]
Sorry, we're only able to respond to issues in English.
