### ISSUE TITLE
Bump version dependency to angular 2.0.0 (specifically input, icon, radio, checkbox)

### ISSUE THREAD

**Issue by goelinsights** [angular/material2#1244]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Angular 2.0.0 compatible

#### What is the current behavior?
npm install breaks on newest version of CLI with current material icon and input packages (alpha.8-1) due to dependencies on Angular 2.0.0-RC6 in these two specific libraries

npm WARN @angular2-material/icon@2.0.0-alpha.8-1 requires a peer of @angular/http@2.0.0-rc.6 but none was installed.
npm WARN @angular2-material/input@2.0.0-alpha.8-1 requires a peer of @angular/forms@2.0.0-rc.6 but none was installed.
npm WARN @angular2-material/radio@2.0.0-alpha.8-1 requires a peer of @angular/forms@2.0.0-rc.6 but none was installed.
npm WARN @angular2-material/checkbox@2.0.0-alpha.8-1 requires a peer of @angular/forms@2.0.0-rc.6 but none was installed.

#### What are the steps to reproduce?
Add input and icon packages to newest version of CLI (using angular 2.0.0)

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0.0

**Comment by vvakame** [comment]
http://angularjs.blogspot.jp/2016/09/angular2-final.html :tada:

**Comment by kucharzyk** [comment]
+1  Compatibility with stable Angular2 version is must-have

**Comment by HeavenlyHost** [comment]
Yes Agree, this needs to done urgently :-)

**Comment by maik10** [comment]
I have this error.

GET http://localhost:3000/traceur 404 (Not Found)

**Comment by goelinsights** [comment]
Note to those stuck - as a patch you can manually change the package.json version numbers in the individual packages under @angular2-material in your node_modules

**Comment by Yonet** [comment]
Similar dependency issue, I am also getting this: 
node_modules/@angular2-material/core/gestures/MdGestureConfig.d.ts:4:39
Cannot find name 'HammerManager'.

**Comment by czeckd** [comment]
To resolve the HammerManager problem, what worked for me was adding hammerjs to my project's typings.json ``typings install dt~hammerjs --save --global``  .

**Comment by czeckd** [comment]
@maik10 
Look at the comment by @RoxKilly in issue #1174, specifically the change to ``format: 'cjs'`` and umd ``${name}.umd.js`` and see if that helps with your traceur problem.

**Comment by goelinsights** [comment]
@czeckd did you also have to install the hammerjs library or is that already packaged somewhere and its just the typings that are missing?

**Comment by czeckd** [comment]
@goelinsights — it depends on what modules you're using. For example, with ``md-icon`` all that was needed was the typings. With ``md-silder``, however, HammerJS needs to be added via npm or cdn. See the material2 [Getting Started](https://github.com/angular/material2/blob/master/GETTING_STARTED.md) doc for details.

**Comment by jelbourn** [comment]
Released alpha.8-2 with updated deps.
