### ISSUE TITLE
moment.js demo at stackblitz.com seems not work correctly

### ISSUE THREAD

**Issue by GitStorageOne** [angular/material2#12458]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
After app starts, date should be displayed in form control

#### What is the current behavior?
Empty date field

#### What are the steps to reproduce?
https://stackblitz.com/angular/drkrlbrqvrb?file=app%2Fdatepicker-moment-example.ts

#### What is the use-case or motivation for changing an existing behavior?
--

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1
Angular material 6.4.1
moment 2.22.2

**Comment by mmalerba** [comment]
dup of #9780
