### ISSUE TITLE
mat-tab-group animating on startup

### ISSUE THREAD

**Issue by ToonvanStrijp** [angular/material2#12455]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the mat-tab-group renders it shouldn't start with animating the first tab content

#### What is the current behavior?
When the mat-tab-group renders it starts with animating the view

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-zwcr1a

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: 6.4.1

**Comment by jrood** [comment]
This bug was introduced in 4.6.1, I would guess either by https://github.com/angular/material2/pull/12229 or by https://github.com/angular/material2/pull/12245
