### ISSUE TITLE
mat-paginator print preview mode.

### ISSUE THREAD

**Issue by pcnate** [angular/material2#12459]
#### Bug, feature request, or proposal:
Feature request
An option in `mat-paginator` to disable pagination during print preview, configurable up to a certain size.

#### What is the expected behavior?
Option to render all elements in a table when the user enters print preview.

#### What is the current behavior?
Print preview simply shows what the user sees.

#### What is the use-case or motivation for changing an existing behavior?
User friendly print previews.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 6.1.0
angular/material 6.4.0
Windows 10.0.17134
Android 8.1.0
Chrome 68.0.3440.75

#### Is there anything else we should know?
I tried using javascript to change the `pageSize` but the delay it takes to reflect this change results in Chrome print preview not rendering the change.
I spent some time trying to find this option but the docs are pretty shallow on examples and there isn't a search so I probably missed it if there is a such an option in existence.

#10125 talks about print preview with virtual scrolling but doesn't seem to suggest print preview with pagination exists.

**Comment by jelbourn** [comment]
This isn't something that can be done at the component level. The paginator doesn't actually control the number of items being shown; that lives purely in the data source. You could probably use the `onbeforeprint` event to change the items rendered.

**Comment by pcnate** [comment]
I was able to detect the change and trigger a change, but I don't see a way to trigger mat-table and mat-paginator to refresh quick enough to be rendered in the print preview. I will try using the `onbeforeprint`. Is there some extension of `onbeforeprint` built into angular/material2 that you are aware of?

**Comment by jelbourn** [comment]
If that doesn't do it then I don't think it's possible.

**Comment by pcnate** [comment]
Is there a way to simply disable pagination once it has been initialized?

**Comment by jelbourn** [comment]
This doesn't really work like that. The idea of "pagination" is really just a filter that restricts which data is returned from the data source. The rows for the items in different pages aren't hidden- the table doesn't even know that they exist at all.

I would suggest creating your own print button that updates the data first and then imperatively invoked the print mode.

**Comment by pcnate** [comment]
I expected that the rows don't exist. I was just poking your brain to see if there was a "faster" way of updating the screen with either no pagination filter or change the pagination size to the total length (or at least the longest I wish to render).

I do plan on having a print button for the sake of the users of this application but I would like a native solution for users like me. I will use the print button idea for now to get things going and maybe revisit this idea in the future. Maybe i could interrupt the print key combo, run the same code as the button which could hopefully trigger the print preview as a solution which isn't quite going to cover all then native printing invocations but would get closer.

Thanks for your input and consideration on the subject.
