### ISSUE TITLE
Accordion-like Feature

### ISSUE THREAD

**Issue by Serjster** [angular/material2#1247]
I noticed this abandoned feature for Material for AngularJS:
https://github.com/angular/material/issues/1861

And noticed that there does not seem to be any accordion or even a collapsible list as a listed feature. Do I misunderstand the naming conventions and one of the listed features has accordion-like functionality or do we need to add this as a feature that needs to be developed? Did you guys notice how many +1s are at the link above?

**Comment by jelbourn** [comment]
We currently have no plans to add an accordion component.

**Comment by TarekAlQaddy** [comment]
@jelbourn can anyone contribute to the repo by adding this feature and following your rules or you just don't want an accordion-like component in material 2 ?
