### ISSUE TITLE
"Select Tab after adding" doesn't work in "Tab group with dynamic sample"

### ISSUE THREAD

**Issue by 4engkai** [angular/material2#12487]
#### Bug, feature request, or proposal:
It's a bug.

#### What is the expected behavior?
In the sample, if the "Select Tab after adding" is checked, and then I clicked the "Add new tab" button, the added tab should be selected (actived).

#### What is the current behavior?
Now the added tab is not selected, the selected tab is still the first one.

#### What are the steps to reproduce?
https://stackblitz.com/angular/eardvdpkrkgy should be the right place to play the sample.
1. Check "Selected Tab after adding".
2. Click "Add new Tab" button.
3. Check if the "New" tab is selected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Version is 6.0.9.

#### Is there anything else we should know?
No.

**Comment by DevVersion** [comment]
This has been fixed within the latest Angular Material version: https://stackblitz.com/edit/angular-9ajget?file=main.ts
