### ISSUE TITLE
Button toggle does not follow material design spec

### ISSUE THREAD

**Issue by BrummbQ** [angular/material2#12486]
#### Bug, feature request, or proposal:
The current button toggle styling differs from the guideline: https://material.io/design/components/buttons.html#toggle-button

i.e.:
* There should be no shadow/elevation, just a border around the items
* the angular component is missing the hover effect

Is there a reason for these differences and would you accept pull requests?

**Comment by crisbeto** [comment]
We're in the process of aligning all the components with the latest iteration of the Material design spec. Here's the PR for the button toggle in particular. https://github.com/angular/material2/pull/12443
