### ISSUE TITLE
Add MatRipple docs to the documentation website

### ISSUE THREAD

**Issue by crutchcorn** [angular/material2#12497]
#### Bug, feature request, or proposal:
There are so many instances that I'd like to look through MatRipple docs and having them on the website would be such a boon to development

**Comment by DevVersion** [comment]
Thanks for your issue. I'm working on getting the ripples into the docs. Should be next minor version of Angular Material.

**Comment by DevVersion** [comment]
Docs are finally available for `7.0.0.beta-2`.
