### ISSUE TITLE
Autocomplete dropdown list does not stick to input field

### ISSUE THREAD

**Issue by Konstruktour** [angular/material2#12500]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When an animation starts after the autocomplete dropdown has opened, the list should stick to the autocomplete input field.

#### What is the current behavior?
The list does not stick to the input field.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-dgvxco
![mat-autocomplete-bug](https://user-images.githubusercontent.com/7323845/43636050-4775863e-9711-11e8-98b4-3bdfe32a05a4.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.1
Material 6.4.2

**Comment by crisbeto** [comment]
The dropdown position only gets set when the dropdown is opened. Doing so all the time wouldn't be practical in terms of performance. Once https://github.com/angular/material2/pull/11495 you can use the `updatePosition` method to tell it to re-align once your animation is done.

**Comment by NithinBiliya** [comment]
I know the issue is closed but I noticed that with mat-select, the scrolling is disabled when the dropdown section is open. Probably autocomplete component should also do the same.
