### ISSUE TITLE
md-text not working!!

### ISSUE THREAD

**Issue by prashant162** [angular/material2#1252]
Hi,

I am new to angular material2. I am trying to create a simple text component to understand the architecture of the material2.

I created a simplet text component with selector as "md-text" but on loading in browser it is throwing the console error like below:

![image](https://cloud.githubusercontent.com/assets/12786328/18577480/9913934a-7c07-11e6-83ef-0a8863c324bb.png)

Let me show you my steps that i followed:

1. In src/lib folder i added the "text" folder and added the necessary files, see below screenshot:
![image](https://cloud.githubusercontent.com/assets/12786328/18577607/63648032-7c08-11e6-8d93-7e0419e93a2d.png)

2. In src/demo-app folder i added the folder with name "text" and created the necessary files, screenshot below:
![image](https://cloud.githubusercontent.com/assets/12786328/18577665/ca3a3590-7c08-11e6-9474-835e25e39269.png)

3. Then i created entry in the routes in src/demo-app/demo-app folder as shown below:
![image](https://cloud.githubusercontent.com/assets/12786328/18577770/affc10bc-7c09-11e6-980f-e1d3a4cf939a.png)

4. Then i did "gulp build:devapp" the build was successfull there were no errors:
![image](https://cloud.githubusercontent.com/assets/12786328/18577813/e4d2461c-7c09-11e6-907e-a354f331481a.png)

5. I checked the dist folder the files in the dist/@angular2-material/text folders are as:
![image](https://cloud.githubusercontent.com/assets/12786328/18577867/373a46f2-7c0a-11e6-80c6-bc56d1d29b07.png)

6. And the files in the dist/text folder are as:
![image](https://cloud.githubusercontent.com/assets/12786328/18577891/5674c8a8-7c0a-11e6-9270-a370e8ca218e.png)

7. I did "gulp serve:devapp" hopefully no error here as well:
![image](https://cloud.githubusercontent.com/assets/12786328/18577915/7f882276-7c0a-11e6-98a1-8bff1d0261cb.png)

8. When i run the project in the browser i am getting this:
![image](https://cloud.githubusercontent.com/assets/12786328/18577958/beed87e4-7c0a-11e6-9e41-cbd08c0a95c8.png)

Let me know if you need any other info.

Am i missing something? Please provide help.

**Comment by elvirdolic** [comment]
Simple. There is no md-text component in the current version.

**Comment by prashant162** [comment]
Hi @elvirdolic 

Yes you are right there is no component in the current version.

But i am trying to create a component and contribute to Angular Material.

But i created my own component by following the above steps, and i am confused where am i missing something?

**Comment by m0t0r** [comment]
@prashant162 Github issues for material2 are only for bug, feature request, or proposal reports. They are _not_ intended to address questions. Please use StackOverflow or Google Groups for questions. If you want to contribute to Material2, make sure to read [CONTRIBUTING.md](https://github.com/angular/material2/blob/master/CONTRIBUTING.md).

**Comment by kara** [comment]
@prashant162 Please take a look at our [contribution guidelines](https://github.com/angular/material2/blob/master/CONTRIBUTING.md). It's awesome that you want to contribute (and please do), but it's important that you adhere to the process. For something as large as a component, we ask that you open an issue first outlining your proposal before going any further. This helps us prevent duplicating work or unnecessary effort in a direction we don't plan on taking.  

I'm closing this, as it seems like a support request. But please feel free to open a new issue with a component proposal if you'd still like to contribute.
