### ISSUE TITLE
Is possible to change the animation styles for Angular MatDialog in MaterialDesign ?

### ISSUE THREAD

**Issue by surya5353** [angular/material2#12527]
Dear All,
I have tried to so many ways to change the **MatDialog** animation style but not possible.
ex:Existing **MatDialog** comes with bottom to top but i want to show **Right to Left** ,or **Fade**, or **Top to Bottom** instead of Bottom to Top. I tried css **@keyframes, Transitions , javascript** but not possible in any way.

**Comment by Chan4077** [comment]
Duplicate of #8857

**Comment by crisbeto** [comment]
Closing as a duplicate of #8857.
