### ISSUE TITLE
Form filed color theme does not update if there is a new theme in the component scss file.

### ISSUE THREAD

**Issue by TKul6** [angular/material2#12523]
#### Bug, feature request, or proposal:
**Bug**

#### What is the expected behavior?
When the form field control is inside a div with class specifying a different theme than the rest of the application, **the form field should apply the theme specified in the div's class and not the app's theme**

#### What is the current behavior?
When adding an angular material theme behavior to specific class (in my case is the `new-theme` class) the form field control does not inherit the new theme colors (as you can see in the example below).

Other controls (like the button for example) have no problem applying the new theme.

Oddly enough, if you take the class definition and moves it out of the component's scss file, **the form field control applies the new theme colors**  

#### What are the steps to reproduce?
**Full example:** https://stackblitz.com/edit/angular-material2-issue-xuhtfm
Steps:

1.  Create a class in the *app.component.scss* file.
2. Inside the css class, create new angular material theme.
3. Add **div** with the new class.
4. Add a **form-field** control inside the div.

You shell see the form field has the same color definitions as the rest of the application.
#### What is the use-case or motivation for changing an existing behavior?
I have in my app one section with different color than the rest of the app (much darker) so I wan't a different theme for all the controls in that area.
This area exists in one component only, so I'd like to specify the new theme only there.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.2
typescript                   2.7.2

Browsers: Chrome, Opera (And I believe other will suffer the problem as well)
material version: 6.4.1.

Thanks a lot

**Comment by crisbeto** [comment]
Here's what's going on: Since you've got view encapsulation turned on, Angular will turn all selectors in something like this: 

```css
.new-theme[_ngcontent-c7] .mat-form-field.mat-focused[_ngcontent-c7] .mat-form-field-label[_ngcontent-c7] {
  color: #2196f3;
}
```

Since the `.mat-form-field-label` is inside the template of the `mat-form-field`, it won't get the `[_ngcontent-c7]` attribute which means that it won't be targeted. You've got a few of options to work around it:

1. Move the theme out into your global styles which aren't encapsulated.
2. Disable style encapsulation for the component.
3. If you want to keep the theme next to your component file and you're using Webpack, you can include the theme file as an import. This has the advantage of not being encapsulated, but keeping the theme in the same bundle as the component.

```ts
import {Component} from '@angular/core';
import './theme.scss';

@Component({
  styleUrls: [...]
})
```

**Comment by TKul6** [comment]
Thank you for the quick response, 
Maybe what you said here should be in the documentation.
the only thing I found was: 
`Note that if you include the generated theme file in the styleUrls of an Angular component, those styles will be subject to that component's view encapsulation.` 
However that doesn't state the fact that due to encapsulation the form-field label won't be styled.
You give the solution without telling what is the problem.

What do you think?
Thanks,
