### ISSUE TITLE
Material Desing V2

### ISSUE THREAD

**Issue by nicobytes** [angular/material2#12521]
Hello!

Now the material design system is version 2
- https://www.youtube.com/watch?v=1Dh8ZBQp9jo
- https://material.io/design/components/buttons.html#contained-button
- https://uxdesign.cc/previewing-material-design-2-0-ec0215f0588f

Will the be updated in this lib for use with angular?

**Comment by crisbeto** [comment]
We're in the process of aligning the different components with the new spec. https://github.com/angular/material2/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+label%3A%22target%3A+major%22+design
