### ISSUE TITLE
Snackbar Rounded Corners on Mobile Devices

### ISSUE THREAD

**Issue by malikfaizanhaider** [angular/material2#12525]
#### Bug:
Rounded Corners on Devices

#### What is the expected behavior? 
Rounded Corners shouldn't be abel on Devices.

#### What is the current behavior?
Rounded Corners showing on Devices with bottom LT white spaces.

#### What are the steps to reproduce?
Open on Devices

#### What is the use-case or motivation for changing an existing behavior?
UI Bug

#### Which versions of Angular, Material.
@latest

**Comment by DevVersion** [comment]
Thanks for your issue. Based on the specs for 2018, the default snackbar should not even be full-width anymore. We are going to have a look at this for the next major version when we do the spec alignments.
