### ISSUE TITLE
What is the default transition of the sidebar?

### ISSUE THREAD

**Issue by AhmedMKamal** [angular/material2#12534]
Actually, it's not an issue, I need to make an animation with the same transition of the sidebar, so I want to know what is the default open and close animation transition of the sidebar?

**Comment by crisbeto** [comment]
You can find the sidenav animations here: https://github.com/angular/material2/blob/master/src/lib/sidenav/drawer-animations.ts#L22

**Comment by AhmedMKamal** [comment]
Thanks ❤️

**Comment by eliteproxy7** [comment]
is there a way to override the transition style for the drawer when it opens? (like fade it in on top vs slide it in?)
