### ISSUE TITLE
material 2 is not compatible with angular 2 final release ...i tried it its not working showing error

### ISSUE THREAD

**Issue by kapli-datta** [angular/material2#1253]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by kapli-datta** [comment]
here is the error what i found:
Error loading http://localhost:3000/@angular2-material/button as "@angular2-material/button" from http://localhost:3000/app/app.module.js

**Comment by m0t0r** [comment]
@kapli-datta the latest version is `alpha.8-2`, have you tried to install it ?

**Comment by kapli-datta** [comment]
Hi  thanks for the reply.i tried with the alpha.8-2 still the same error i am getting .
here is my files:
package.json:

{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.0",
    "@angular2-material/button": "^2.0.0-alpha.8-2",
    "@angular2-material/core": "^2.0.0-alpha.8-2",
    "angular2-in-memory-web-api": "0.0.20",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "concurrently": "^2.2.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.2",
    "typings": "^1.3.2"
  }
}
app.module.ts:


import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }   from './app.component';
import {MdButtonModule} from '@angular2-material/button';
@NgModule({
  imports:      [ BrowserModule,MdButtonModule],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }


and my template : app.component.html

<button md-button>Button</button>

**Comment by JanStureNielsen** [comment]
@kapli-datta -- the issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details. 

And note the project's problem reporting template -- it includes a Plunker which has a button...
