### ISSUE TITLE
panelClosingActions on matAutocomplete triggers change detection too often

### ISSUE THREAD

**Issue by oliveti** [angular/material2#12547]
#### Bug, feature request, or proposal: 

Bug

#### What is the expected behavior?

When `panelClosingActions` of `MatAutocompleteTrigger` is subscribed it should not trigger a change detection on every event (like click) on the page but only when the panel is closing.

#### What is the current behavior?

A change detection is triggered on every event on the page when `panelClosingActions`  is subscribed.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-autcomplete-trigger-cd-2

Go to stackblitz, click on `bind panelClosingActions` start to click around and have a look at console.

#### What is the use-case or motivation for changing an existing behavior?

Improve performances by reducing useless change detections

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

latest : angular 6.1.1, material 6.4.2

**Comment by crisbeto** [comment]
The `panelClosingActions` are actions that are supposed to close a panel, it's not something that you should be subscribed to while the panel is closed.

**Comment by oliveti** [comment]
So you suggest that we subscribe to this observable ONLY when the panel is opened ? It would make more sense to be able to subscribe all the time.

In my opinion this `panelClosingActions` should run outside of angular zone and only emit on actual close.

**Comment by crisbeto** [comment]
If you want to know when an autocomplete was opened or closed, the `MatAutocomplete` component has observables for `opened` and `closed`.

**Comment by oliveti** [comment]
Yes sure, but the point is not here. 
Subscribing to `panelClosingActions` should not make the component trigger a change detection on click events anywhere in the page, that's useless and cause performance issues.

**Comment by crisbeto** [comment]
Yes, I get your point, but that observable is mostly meant for internal usage inside the autocompleter itself. It gets created when it is opened and then is removed once it's closed.

**Comment by crisbeto** [comment]
Closing the issue since it's working as expected. If you want to avoid hitting change detection on every click, you should use the `panelClosingActions` as they were intended: only while the panel is open:

```ts
trigger.panelClosingActions.pipe(takeUntil(trigger.autocomplete.closed)).subscribe(...);
```
