### ISSUE TITLE
CDK: Add config to close the overlay when browser back button is pressed

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#12544]
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

An option to close an opened overlay on browser back button

#### What is the current behavior?

Overlay stays opened on browser back button

#### What is the use-case or motivation for changing an existing behavior?

Gives more flexibility to plugins which are built on top of the CDK

My current workaround:

```ts
  constructor(router: Router) {
     // Close the lightbox if the current route has changed
     router.events.pipe(
       filter((event: RouterEvent) => event instanceof NavigationStart),
       tap(() => this.overlayRef.detach()),
       take(1)
     ).subscribe();
   }
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: 6.0.6
Material: 6.3.0

#### Is there anything else we should know?

Similar to the `closeOnNavigation` option in mat-dialog

**Comment by crisbeto** [comment]
We can handle pressing the back button using the `Location` since it's in `@angular/common`, but that won't cover clicking on router links. We can't handle router links, because it would mean introducing a dependency on `@angular/router`. Note that this is the way `MatDialog` works at the moment as well.

**Comment by jelbourn** [comment]
@crisbeto as part of this we should also mention this behavior in the documentation for overlay and for dialog, specifically calling out that it won't work with `routerLink`
