### ISSUE TITLE
angular material datepicker not working on production

### ISSUE THREAD

**Issue by umang6891** [angular/material2#12559]
#### Version:
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.2
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.7.2
@angular-devkit/schematics        0.7.2
@angular/cdk                      6.4.2
@angular/cli                      6.1.2
@angular/flex-layout              5.0.0-beta.14-17a70ee
@angular/material                 6.4.2
@ngtools/webpack                  6.0.7
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.8.3

Datepicker works perfectly fine in development mode but not in production.

#### What are the steps to reproduce?
Run with `ng serve --prod`

**Comment by DevVersion** [comment]
Hey, I've tried to reproduce that issue, but wasn't able to run into your problem. Can you please share more information?

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
