### ISSUE TITLE
Missing @keyframe Definitions for CdkAutofill

### ISSUE THREAD

**Issue by tuhinkarmakar** [angular/material2#12564]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The prebuilt CSS (_text-field-prebuilt.css_) should declare the `keyframe`s needed to hook into browser events.

#### What is the current behavior?
The `CdkAutofill` does not work as the generated CSS doesn't declare the `@keyframe`s. The `@keyframe`s are declared in at line number 6 - 7 in the SASS file.

https://github.com/angular/material2/blob/1e1751f61eca15eb9cf81581bb4c7e191d2a1bbd/src/cdk/text-field/_text-field.scss#L6-L7

According to [text-field.md](https://github.com/angular/material2/blob/1e1751f61eca15eb9cf81581bb4c7e191d2a1bbd/src/cdk/text-field/text-field.md#monitoring-the-autofill-state-of-an-input), the CSS is already included in Angular Material. But the CSS doesn't have the animation declarations. Declaring the `keyframe`s inside `styles.css` fixes the issue.

#### What are the steps to reproduce?
Download the CDK package and inspect the generated CSS.

#### What is the use-case or motivation for changing an existing behavior?
`CdkAutofill` should work out of the box.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I tested with the latest versions of Angular and Angular Material. The TypeScript version was 2.7.2. I tested with Chrome on a Windows 10 machine.

#### Is there anything else we should know?
The [documention](https://material.angular.io/components/input/overview#responding-to-changes-in-the-autofill-state-of-an-code-lt-input-gt-code-) for `matInput` contains a broken link to https://material.angular.io/components/input/overview#monitoring-the-autofill-state-of-an-input. This link should show the contains of [text-field.md](https://github.com/angular/material2/blob/1e1751f61eca15eb9cf81581bb4c7e191d2a1bbd/src/cdk/text-field/text-field.md#monitoring-the-autofill-state-of-an-input).

**Comment by mmalerba** [comment]
Hmm very strange, I wonder if the keyframes are getting stripped out because they're empty?

**Comment by mmalerba** [comment]
@tuhinkarmakar good find, I created a fix

**Comment by tuhinkarmakar** [comment]
This bug makes me wonder, am I the first person who tried to use `CdkAutofill` :thinking:? The feature was DOA. How did this bug slip through? I am not bashing anyone. Just trying to get a picture of how development and testing is done here.

**Comment by mmalerba** [comment]
I think it depends how you compile your SCSS, LibSass had an issue but Dart Sass worked fine. It actually worked in the demo app included in the repo

**Comment by tuhinkarmakar** [comment]
Oh, I see. I hope the PR gets merged soon :grinning:

I have a usage related question. How would you use this directive to mark an autofilled form as valid only when it _really_ is valid? I mean of course I can set the controls as valid when the autofill event is fired. But as I found out, Chrome lets users save input values even if they aren't valid.

For example, let's say I have input field with `type="email"`. Even if a user enters an invalid email, Chrome shows a button to save the value. Now if the user does save this value and hits reload, the autofilled event will get fired and the form field will be marked as valid in my code. But the form is not _really_ valid. I wouldn't even be able to check the value against a regex since the `FormControl` won't get the autofilled value.

**Comment by mmalerba** [comment]
For security reasons, Chrome does not reveal the value until the user interacts with the page. Even reading the `.value` property off the native `<input>` element will return empty string, so unfortunately there's no way to due true validation of the value until after the user clicks.
