### ISSUE TITLE
Sidenav text color is wrong for dark theme on docs site

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#12568]
![image](https://user-images.githubusercontent.com/838736/43795901-93b90542-9a37-11e8-9684-a57ae6071636.png)

**Comment by vivian-hu** [comment]
Do not see this issue in the latest 6.4.7 doc site. 

![image](https://user-images.githubusercontent.com/41269630/45049417-6474d880-b033-11e8-8744-895f058cfb3b.png)
