### ISSUE TITLE
Feat. MatTable should allow customized TrackBy (similar to *ngFor)

### ISSUE THREAD

**Issue by f-aubert** [angular/material2#12561]
#### Bug, feature request, or proposal:
Feat. MatTable should allow customized TrackBy Function.

#### What is the expected behavior?
It should be allowed to set a custom TrackBy function on either MatTable/MatRow/MatCell, via an input/directive.

#### What is the current behavior?
There is no TrackBy input/directive on MatTable/MatRow/MatCell

#### What is the use-case or motivation for changing an existing behavior?
It happens  we need to refresh / replace the DataSource, although most items didn't change, and only a couple were added / removed. When we embed for example things like form fields and autocomplete in the rows, we would rather not recreate them for existing rows that represent a given element of which we know the id. So using a trackBy function similar to the one for a plain *ngFor would allow to return the id as the tracker, and should not recreate the whole row.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest Angular 6, Latest Material 6.3

Thanks for your consideration

**Comment by josephperrott** [comment]
Closing as this is actually already included in `MatTable`.  You can see it in the API documentation [here](https://material.angular.io/components/table/api#MatTable).

**Comment by f-aubert** [comment]
I apologize for missing that. I will try it and report just for closing the whole circle. Thanks for your great and yearlong work on Angular Material.
