### ISSUE TITLE
Internet Explorer: Object doesn't support property or method 'fill'

### ISSUE THREAD

**Issue by mszkudelski** [angular/material2#12579]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Working Angular application with Angular Material's components used in it on Internet Explorer browser.

#### What is the current behavior?
Application doesn't run on Internet Explorer v. 11. That error apears: "Object doesn't support property or method 'fill' vendor.js (67601,1)"

#### What are the steps to reproduce?
I don't know which Material component causes error, but I hope that error message will be enough for you.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.1.0
Material: 6.4.2
OS: Windows 10
Typescript: 2.9.2
Internet Explorer: 11

#### Is there anything else we should know?
There is related issue #12202, which is closed

**Comment by crisbeto** [comment]
The only component that is using `Array.fill` is the `mat-grid-list`. Is this something that you're using?

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.  I was unable to reproduce one myself in either stackblitz or creating a new angular project with cli.

**Comment by mszkudelski** [comment]
@josephperrott, I also cannot reproduce error in StackBlitz because app on IE throws another error ("Unhandled promise rejection TypeError: Unable to get property 'defaultExtension' of undefined or null reference"). I could try to reproduce by creating new app by angular cli and using Material's components in it.

@crisbeto I'm not using this component. Is it possible that another Material's component is using it inside? I could list here component that I use. Would it be helpful?

**Comment by crisbeto** [comment]
That would help @mszkudelski, but from doing a code search, the grid list was the only component that had a reference to `.fill` so it's possible that the error is coming from somewhere else in your app. The easiest solution for you might be to include a polyfill for `Array.fill`.

**Comment by mszkudelski** [comment]
@crisbeto thanks for your advise, but I have already included polyfills for Array (ES7) which are provided with generated Angular project.

Ok, I've propably found place when that method causes error and it is in Angular Core's code. Thank you for help, guys. I'll close issue

**Comment by jigshGitHub** [comment]
I am getting error while running getting started app from angular.io...vendor.js throws error Object doesn't support property or method 'fill' File: vendor.js, Line: 44446, Column: 1

**Comment by atdiff** [comment]
I'm getting the same error in IE - "Object doesn't support property or method 'fill'".  The line it's failing on is 
`var HEADER_FILLER = new Array(HEADER_OFFSET).fill(null);`
which is a part of angular/core.
