### ISSUE TITLE
Angular 6 and Angular materials printing a div returning empty fields with no data and no css attached

### ISSUE THREAD

**Issue by alim90** [angular/material2#12575]
I am having a difficulty in printing div content.

The div is based on angular 6 and its related angular material version.

The div has the following script:

     <div class="order-info-container" id="divToPrint">
        <mat-form-field>
        <input matInput placeholder="Name" [value]="info.name" readonly>
        </mat-form-field>                        
                    
        <mat-form-field>
        <textarea matInput placeholder="Address" matTextareaAutosize [value]="info.address" readonly></textarea>
        </mat-form-field>
     </div>

And the button is:

    <button mat-raised-button type="button" *ngIf="lat!=0 && lng!=0" (click)="print();">Print Order</button>

The typescript function of print() is:

    print(){
        let divToPrint = document.getElementById('divToPrint').innerHTML;
        let newWindow = window.open('', '_blank', 'top=0,left=0,height=100%,width=auto');
        newWindow.document.open();
        newWindow.document.write(`
        <html>
            <head>
              <title>Print tab</title>
              <style>
              
              </style>
            </head>
            <body onload="window.print();window.close()">${divToPrint}   
            </body>
          </html>
        `);
        newWindow.document.close();
      }

And result was empty text boxes with no data, and no css attached.

I think, angular is not displaying the 2 variables as they have been imported from database. But they actually exist on the screen.

[Here is an image of what a printed page looks like][1]. Empty fields and no attached angular material css into it.

  [1]: https://imgur.com/a/aKtiM7W

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
