### ISSUE TITLE
mat-sidenav resize does not resize mat-sidenav-content

### ISSUE THREAD

**Issue by pcnate** [angular/material2#12573]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
When content in the `mat-sidenav` is change, I would expect the size of the 'mat-sidenav-content` to resize accordingly.

#### What is the current behavior?
No resize occurs without triggering a `close` and then an `open` or a double `toggle`.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Content in the sidenav is commonly loading from an API rather than hard coded html. When content is loaded/changed, the sidenav should automatically resize the content window.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/cdk": "^6.4.2",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/material": "^6.4.0",
    "@angular/cli": "~6.0.8",
    "@angular/compiler-cli": "^6.1.0",
    "typescript": "~2.7.2"

Chrome 68.0.3440.84
Firefox 61.0.1

**Comment by mmalerba** [comment]
Please see the documentation section on "Resizing an open sidenav" https://material.angular.io/components/sidenav/overview

**Comment by phanf** [comment]
@mmalerba is correct. The container needs the `autosize` property set
```
<mat-sidenav-container autosize>
<mat-sidenav-container>
```
