### ISSUE TITLE
mat-form-field validation don't work if form includes ControlValueAccessor implementation and it is form itself

### ISSUE THREAD

**Issue by volago** [angular/material2#12584]
#### Bug / feature request:
I have reactive from. One of its controls is custom control which implements ControlValueAccessor, Validate and have another form inside. There is a problem with validation of this control when submit is clicked.

#### What is the expected behavior?
I wish mat-form-field of inner form turns red (if not valid) when I click submit on outer form.

#### What is the current behavior?
Angular Forms recognizes inner form field as invalid, but angular material don't marks mat-form-field as red.

In below example I put 3 fields.
FieldA - regular form field (works)
FieldB - impementation of ControlValueAccessor with FormControl inside (works)
FieldC - impementation of ControlValueAccessor with FormGroup inside (don't work)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-k5eaj3?file=app%2Fform-field-error-example.html
Go to link above and click Submit. Only two first fields turns red. Field C turns red only when it is clicked and blured.

#### What is the use-case or motivation for changing an existing behavior?
One can have highly reusable picker (which can consists of many fields) on form and want to write this picker once.

**Comment by mmalerba** [comment]
According to the html spec, a form element should not be nested inside another form element. This is not a use case we aim to support

From https://www.w3.org/TR/html5/forms.html#the-form-element:
> Content model: Flow content, but with no form element descendants.

**Comment by volago** [comment]
@mmalerba I'm not sure it the case you mentioned, because:

1. fieldB custom control uses form tag and works perfect (it is form in form indeed)
2. I've changed fieldC control not to use form tag (https://stackblitz.com/edit/angular-k5eaj3?file=app%2Flast-name-picker%2Flast-name-picker.component.html) and it still not work.

If I'm still wrong please recommend any strategy to create complex custom controls to use with mat-form-field and it's awesome validation mechanism.
