### ISSUE TITLE
MatDatePicker, timezone

### ISSUE THREAD

**Issue by b-mi** [angular/material2#12580]
#### Bug, feature request, or proposal:
Many days try to find solution for MatDatePicker for normal use in real world.
Timezone problem - who in this world need time zone in date value? When user select 19.6.2019, data MUST contains 19.6.2019 not something else like 2018-09-15T22:00:00.000Z (I know, data with timezone, but nobody need such data). Do not want to manipulate wit user entered data by code.
https://i.imgur.com/QfWF3OQ.png

We have to use Moment.js. We need install separate component, install moment.js, write DateAdapters make many various changes in code - when we want simple have those data which user entered. Why?

Does this enought? NO! When user change date value by keyboard typing, timezone cancer return into value.  Please, fix all basic bugs of MatDatePicker, because this is hardly usable in real world.

#### What is the expected behavior?
Normal, logic behavior - let data contain data which user entered, when user pick date, or edit date, without need to manipulate by user entered data - in standard, withou need of many lines of code and various changes.

#### What is the current behavior?
Curren behavior need a lot of code for correct functionality.

#### What are the steps to reproduce?

- MatDatePicker, format dd.mm.yyyy (sk-SK) (other than default format)
- Try to select value and look at data in model
- Try to edit date value by keyboard and look at data in model
- If it work - see how a lot of code lines you have to write. 
For basic beahvior should be need of 0 lines of code

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6, Material 6, WIN 10, Typescript 2.7.2,  MatDatePicker, ReactiveForms, date format dd.mm.yyyy, all browsers. 

#### Is there anything else we should know?
Thank you

**Comment by jelbourn** [comment]
Dealing with dates and timezones is inherently complex. There is no "just works" engineering solution.
