### ISSUE TITLE
Clicking off MatDialog adds cdk-keyboard-focused class to button that triggered it

### ISSUE THREAD

**Issue by Sharpiro** [angular/material2#12588]
When you click a button to open a modal, after that modal is closed in any way, a "cdk-keyboard-focused" class is added to the button that originally triggered the modal.  This makes it look like the button is highlighted or still active for some reason.

You can see an example of this on any example on your docs page:
https://material.angular.io/components/dialog/overview

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
