### ISSUE TITLE
mat-select - Allow use `this` in compareWith function

### ISSUE THREAD

**Issue by JoniJnm** [angular/material2#12598]
#### Bug, feature request, or proposal:

Proposal & bug?

#### What is the expected behavior?

In my compareWith function, `this` should be the component instance

#### What is the current behavior?

In my compareWith function, `this` is an instance of `MatSelect`

#### What are the steps to reproduce?

Use `this` in the compareWith function

https://stackblitz.com/edit/angular-material2-issue-r8d7v2

#### What is the use-case or motivation for changing an existing behavior?

Allow to use `this` in compareWith function 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All? Until 6.1.2

#### Is there anything else we should know?

The solution is change

```ts
this._compareWith(option.value,  value);

// by

this._compareWith.call(this._compareWith, option.value, value);
```

https://github.com/angular/material2/blob/d5c5f317b0b22bd92a65200422400aadd84cdcd5/src/lib/select/select.ts#L825

**Comment by crisbeto** [comment]
There's no way for `mat-select` to get the context of the component it's in. If you want a proper `this`, you can change the `compareWith` to an arrow function:

```ts
compareWith = (obj1: any, obj2: any) => {
    console.log(this);
    // return obj1 === obj2; // uncomment to see the difference
    return this.complexComparator(obj1, obj2);
}
```

**Comment by JoniJnm** [comment]
Temporary solution

```ts
export class AppComponent implements OnInit {
  options = [1, 2, 3, 4];
  _compareWith: (obj1: any, obj2: any) => boolean;

  ngOnInit() {
    const self = this;
    this._compareWith = (obj1: any, obj2: any): boolean => {
      return self.compareWith(obj1, obj2);
    };
  }

  compareWith(obj1: any, obj2: any): boolean {
    console.log(this);
    return this.complexComparator(obj1, obj2);
  }

  private complexComparator(obj1: any, obj2: any): boolean {
    return obj1 === obj2;
  }
}
```

And use _compareWith in template
