### ISSUE TITLE
Feature Request: Disable label in calendar-body

### ISSUE THREAD

**Issue by lordgit** [angular/material2#12597]
#### feature request
Disable label in calendar-body.html

Line 5: <tr *ngIf="_firstRowOffset < labelMinRequiredCells"
Line 22:  <td *ngIf="rowIndex === 0 && _firstRowOffset"

We need this  for costumer requirements.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.x, Material  6.4.3

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
