### ISSUE TITLE
stepper: inconsistent handling of tabbing and styling of focused step headers

### ISSUE THREAD

**Issue by Splaktar** [angular/material2#12595]
#### Bug, feature request, or proposal:
Bug unless this different is by design due to some a11y requirements

#### What is the expected behavior?
For vertical steppers, after opening a step (via Next button) if the `mat-step-header` is focused, then the styling should reflect that. The first tab press should move focus to the `mat-step`’s first focusable element.

For horizontal steppers, after opening a step (via Next button) if the `mat-step-header` is focused, then the styling should reflect that. The first tab press should move focus to the `mat-step`’s first focusable element.

Note that these expected behaviors are identical.

#### What is the current behavior?
Right now for vertical steppers, after opening a step (via Next button) the focus seems to be ‘left behind’. The first tab press moves focus to the `mat-step-header` and the header's style is changed to reflect that it has focus. The second tab press moves focus to the `mat-step`’s first focusable element.

Right now for horizontal steppers, after opening a step (via Next button) it looks like the `mat-step-header` may have focus but there is no styling to reflect this like in the vertical stepper. The first tab press moves the focus to the `mat-step`’s first focusable element.

#### What are the steps to reproduce?
This is easy to observe in the two examples here: https://material.angular.io/components/stepper/overview

#### What is the use-case or motivation for changing an existing behavior?
It seems like these UI behaviors should be made consistent.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.1
Angular Material 6.4.2
OS: macos
Chrome
TypeScript 2.7.2

#### Is there anything else we should know?
This is related to https://github.com/angular/material2/issues/12578 but it is a separate issue.

**Comment by josephperrott** [comment]
This may have been inadvertently addressed?  @Splaktar are you still seeing this issue as I was not able to reproduce it in Chrome v69 on Linux.

**Comment by Splaktar** [comment]
Yes, this was fixed in one of the recent releases.
