### ISSUE TITLE
Button Toggle Group does not use a divider between buttons

### ISSUE THREAD

**Issue by critchie** [angular/material2#12591]
#### Feature request
Button Toggle Group does not use a divider between buttons.  I tried using the mat-divider but couldn't figure out exactly where to put it.

#### What is the expected behavior?
That each button in the toggle group be separated by a divider/line as the
[Material Design](https://material.io/design/components/buttons.html#toggle-button) shows.

#### What is the current behavior?
The buttons are not separated by any type of border.

#### What are the steps to reproduce?
[StackBlitz](https://stackblitz.com/edit/angular-material-buttontoggle)

#### What is the use-case or motivation for changing an existing behavior?
The users are having a hard time accepting this long list of text and not realizing they are separate buttons.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
See StackBlitz

**Comment by crisbeto** [comment]
This will be addressed when we switch to the new design in https://github.com/angular/material2/pull/12443.

**Comment by critchie** [comment]
Sorry...  I searched and searched but evidently didn't search well enough or for the right thing.  Good enough.  I look forward to the new design.
