### ISSUE TITLE
Mat-Selection-List disabled options keyboard selectable

### ISSUE THREAD

**Issue by PanWill** [angular/material2#12608]
#### Bug, feature request, or proposal:
Hello, I am not sure but I think that one shouldn't be able to override disable via keyboard selection (ie: going to the disabled option via tab, down arrow and return). But could be I missed something in the docs.

#### What is the current behavior?
See StackBlitz please

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-m5gtdy
tab to selection list hit down key and enter

**Comment by DevVersion** [comment]
It's actually intentional. We wanted to make sure that users with a screen reader still have the possibility to see what options are part of the selection list.

**Comment by PanWill** [comment]
Ok, read yes, navigate yes, but act on (hitting enter)? When that is not the same functionality as non screen readers the intention seems counter intuitive. We want screen reader users to have functionality that does not exist otherwise and causing errors to be sent in forms? Is there a way to disable this? Thank you for your response, I can look into disabling keyboard navigation.

**Comment by DevVersion** [comment]
@PanWill Well, a value change while the list is disabled should be surely not the case.

I will look into it.
