### ISSUE TITLE
feat(icons): Sizeable icons

### ISSUE THREAD

**Issue by odahcam** [angular/material2#12603]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Sizeable icons.

#### What is the current behavior?
24px ~or dp maybe~ icons.

#### What is the use-case or motivation for changing an existing behavior?
angular/material2 itself docs uses 40px icons inside feature cards.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/material2 6.4.2

#### Is there anything else we should know?
Just a size attr and a sizing-mode (auto, landscape, portrait or square) should be more than enough.

Yes, I know I can size the icons via CSS.

**Comment by josephperrott** [comment]
This is something we actually chose to not control via `@Input`s because it can be done simply via css.

You should be able create classes that can be applied or you can control the styling directly with style tags.
