### ISSUE TITLE
MatLabel of an Autofilled MatFormField Does Not Float

### ISSUE THREAD

**Issue by tuhinkarmakar** [angular/material2#12627]
#### What is the expected behavior?
The label for an input field will float  when "appearance" is set to "standard" and the field gets autofilled.

#### What is the current behavior?
When "appearance" of `MatFormField` is set to "standard" and the input field gets autofilled, the `MatLabel` doesn't float above the input field. Using "legacy" mode doesn't cause this issue.

![image](https://user-images.githubusercontent.com/11135104/43978813-32cebe8a-9d06-11e8-90d0-1b5e21b6bc97.png)
When using the "legacy" mode

![image](https://user-images.githubusercontent.com/11135104/43978889-6d62e300-9d06-11e8-8473-860ee618ecb0.png)
When using the "standard" mode

#### What are the steps to reproduce?

1. Create a form using `MatFormField` and `MatInput`
2. Set "appearance" of `MatFormField` to "standard"
3. Enter some values in those fields
4. Submit the form
5. Save the input values when the browser prompts
6. Hard reload the page

#### What is the use-case or motivation for changing an existing behavior?
According to [Material Design](https://material.io/design/components/text-fields.html#filled-text-field), the label for a filled input field should float above it.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I tested with the latest versions of Angular and Angular Material. The TypeScript version was 2.9.2. I tested with Chrome on a Windows 10 machine.

**Comment by mmalerba** [comment]
It seems to be working fine for me: https://angular-material2-issue-aa46tt.stackblitz.io/ (code here: https://stackblitz.com/edit/angular-material2-issue-aa46tt?file=app/app.component.html).

If you are still experiencing this problem can you post a reproduction?

**Comment by tuhinkarmakar** [comment]
You need to set "appearance" of the `MatFormField`s to "standard". I forked your code and made the changes. Take a look [here](https://stackblitz.com/edit/angular-material2-issue-jlhaoo?file=app/app.component.html).

![image](https://user-images.githubusercontent.com/11135104/43980429-b39de4c8-9d0b-11e8-8d47-3a14a56fc878.png)

**Comment by mmalerba** [comment]
Oh this is related to the missing keyframes thing it looks like. Here's your example but with the keyframes added in manually: https://angular-material2-issue-mmpq8b.stackblitz.io/ #12567 will fix this as well

**Comment by tuhinkarmakar** [comment]
Yes, you're right. When I added the `@keyframe`s manually the issue disappeared.
