### ISSUE TITLE
Datepicker and Reactive Forms validation bug

### ISSUE THREAD

**Issue by Jakovich** [angular/material2#12633]
#### What is the expected behavior?
The same behavior that was implemented on version 5.1.
If we enter an invalid date, then event is thrown and it changes the state to ‘invalid’.
If we delete an invalid date and the input field is not required, then the state of the input field becomes valid.

#### What is the current behavior?
If an invalid value is entered, then no event is thrown.
This causes two error behaviors  
1. If the input is empty and then an invalid date is entered – the input field keeps a valid state  
2. If we enter a valid date and then replace by an invalid date, then the input field shows an invalid state (normal behavior) but if we delete the invalid date, then the empty input field keeps an invalid state even if it is not required.

#### What are the steps to reproduce?
1. Go to https://material.angular.io/components/datepicker/overview and navigate to "Datepicker selected value”
2. Clean the value and input 'asdf'. No error is displayed.
3. Input a valid date, e.g. 02/02/2018, then change by entering via the keyboard an invalid date, e.g. 45/02/2018, and then delete the input NOT using the backspace key but instead by selecting the value and then delete it with the ‘Delete’ key. The invalid /state of the field is still present whereas this input is not required.

#### What is the use-case or motivation for changing an existing behavior?
I want to enter an invalid date after cleaning the input and get an error.
I want to enter the valid date, change to an invalid date and then delete it and get a valid state of no required input. Otherwise we can have the cases when the valid form is impossible to send because of an invalid state of empty not required input.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6
Material 6.3.0
Typescript: 2.7.2
All browswers

**Comment by lousley** [comment]
i have the same issue: https://github.com/angular/material2/issues/11931

**Comment by alevineplusconsulting** [comment]
When can we expect this to be added to the next release? Or will it even be? Also, is there a workaround I can implement within the application itself (in lieu of modifying the library itself)? Thanks.
