### ISSUE TITLE
Leak Memory in mattooltip

### ISSUE THREAD

**Issue by sorterir** [angular/material2#12644]
#### Bug:
Leak Memory in mattooltip

#### What is the expected behavior?
Memory Release

#### What is the current behavior?
After mouse over control attach to matooltip 

#### What are the steps to reproduce?
After mouse over control

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 6.0.7 and material  6.3.2

#### Is there anything else we should know?
in code file tooltip.ts used code 
`_isHandset: Observable<BreakpointState> = this._breakpointObserver.observe(Breakpoints.Handset);`

and used this property in html but not unsubscibe in ts file 

similar code unsubscripe in snackbar is correct

`this._breakpointObserver.observe(Breakpoints.Handset).pipe(
      takeUntil(overlayRef.detachments().pipe(take(1)))
    ).subscribe(state => {
      if (state.matches) {
        overlayRef.overlayElement.classList.add('mat-snack-bar-handset');
      } else {
        overlayRef.overlayElement.classList.remove('mat-snack-bar-handset');
      }
    });`

**Comment by crisbeto** [comment]
The `_isHandset` observable [is used together with the `async` pipe](https://github.com/angular/material2/blob/master/src/lib/tooltip/tooltip.html#L3) which means that it'll unsubscribe when the component is destroyed.

**Comment by denisoby** [comment]
It should unsubscribe, but actually I've got the same memory leak.
And it is not reproduced in latest material demo app.
Is it already fixed?
