### ISSUE TITLE
NPM does not serve latest version of code.

### ISSUE THREAD

**Issue by mathebox** [angular/material2#1264]
#### Bug
NPM does not serve latest version of code (labeled with `2.0.0-alpha.8-2`). Instead version `2.0.0-alpha.8-1` is served.

#### What is the expected behavior?
The latest version should be available via NPM and should be correctly labeled. (commit id: `9055c3b`)

#### What is the current behavior?
NPM serves version `2.0.0-alpha.8-1` labeled as `2.0.0-alpha.8-2`.

#### What are the steps to reproduce?

- `npm install @angular2-material/tooltip`
- open `node_modules/@angular2-material/tooltip/tooltip.js`
- line 47-53: `ngOnInit` is still marked with `@internal` but this should be fixed with 833368f

**or**

- `npm install @angular2-material/core`
- open `node_modules/@angular2-material/core/overlay/position/global-position-strategy.js`
- line 18 and 23 still have the typo fixed in 484f470

#### Which versions of Angular, Material, OS, browsers are affected?
- Angular: 2.0.0
- Material: 2.0.0-alpha.8-2
- NPM: 3.10.7
- Node: 6.5.0
- OS: OS X 10.11.6

**Comment by jelbourn** [comment]
@mathebox alpha.8-2 is exactly the same code as alpha.8-1 except for having the dependencies on `@angular` packages bumped to 2.0.0. More recent changes will be a part of alpha.9
