### ISSUE TITLE
md-card text overflowing

### ISSUE THREAD

**Issue by jalalat** [angular/material2#1265]
#### What is the expected behavior?
Text should wrap

#### What is the current behavior?
text overflowing the box

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

http://plnkr.co/edit/qGJxAc7ulsgCEL64ZI05?p=preview

**Comment by jelbourn** [comment]
The text does not wrap because there is no whitespace for the browser to break on. This is the expected behavior.
