### ISSUE TITLE
sort header color of the mat-table is not getting changed from the default gray color. Please suggest on how to change it.

### ISSUE THREAD

**Issue by SaifDeveloper** [angular/material2#12664]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
