### ISSUE TITLE
6.4 - Stackblitz examples don't link

### ISSUE THREAD

**Issue by KissBalazs** [angular/material2#12668]
#### Bug, feature request, or proposal:
The exact same problem happens again, but with different numbers, which is described here: https://github.com/angular/material2/issues/11568 
"On angular material website, the stackblitz examples are inaccesible."

#### What is the current behavior?
clicking on example links returns 
`{"error":"UNSATISFIED_RANGE","data":{"name":"@angular/cdk","range":"6.4.4"}}`

#### What are the steps to reproduce?
For example: https://material.angular.io/components/table/examples -> click on a stackblitz example icon

**Comment by josephperrott** [comment]
Closing as duplicate of #12662
