### ISSUE TITLE
docs are not loading

### ISSUE THREAD

**Issue by arashrasoulzadeh** [angular/material2#12665]
#### Bug, feature request, or proposal:
docs page is not working

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by alex7egli** [comment]
Same issue. I'd say about 75% of the time that I try to go to https://material.angular.io/ it doesn't load. I just see a white screen with console error that https://material.angular.io/main.af62af8dab0824d37bac.js could not load due to a 404.

Today I also got this warning:
DevTools failed to parse SourceMap: https://material.angular.io/ngsw_worker.es6.js.map

**Comment by Trent-Matthias** [comment]
Try opening the dev tools in chrome, click on the application tab, then service workers, and check the bypass for network checkbox.

**Comment by arashrasoulzadeh** [comment]
what about safari ? 

error is : 
`
Safari can’t open the page “https://material.angular.io/”. The error is: “FetchEvent.respondWith received an error: Error: Response not Ok (fetchAndCacheOnce): request for https://material.angular.io/index.html returned response 301 ” (WebKitServiceWorker:0)
`

**Comment by jotatoledo** [comment]
Dup of https://github.com/angular/material2/issues/11745

**Comment by denis-n** [comment]
It doesn't work on FireFox too.

> Corrupted Content Error
> 
> The site at https://material.angular.io/components/checkbox/overview has experienced a network protocol violation that cannot be repaired.
> 
> The page you are trying to view cannot be shown because an error in the data transmission was detected.
> 
>     Please contact the website owners to inform them of this problem.

**Comment by mpostelnicu** [comment]
i see a blank page 50% of the time, refresh does not help. then suddenly it starts working. then it starts returning again blank page

`2main.af62af8dab0824d37bac.js:1 Failed to load resource: the server responded with a status of 404 ()`

Xubuntu Linux Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by jelbourn** [comment]
A new version has been deployed that _should_ eliminate this problem.

**Comment by timmyrosen** [comment]
The docs site has been unreachable for me now for a few days.

Here is the console output:
```
Uncaught (in promise) Error: Response not Ok (fetchAndCacheOnce): request for https://material.angular.io/index.html returned response 301 
    at PrefetchAssetGroup.<anonymous> (ngsw-worker.js:576)
    at Generator.next (<anonymous>)
    at fulfilled (ngsw-worker.js:304)
(anonymous) @ ngsw-worker.js:576
fulfilled @ ngsw-worker.js:304
A bad HTTP response code (404) was received when fetching the script.
Failed to load resource: net::ERR_INVALID_RESPONSE
```

I can't clear the service worker or storage either because the site path is just `://`

**Comment by alex7egli** [comment]
Still having the same issue as before. The page is just blank with the same 404 error.

**Comment by jelbourn** [comment]
You may have to clear the service worker one last time to get rid of your cached version.

**Comment by arashrasoulzadeh** [comment]
how ? im using safari

**Comment by timmyrosen** [comment]
@jelbourn I can't even do that. See these attached images of how it looks in chrome dev tools

![skarmavbild 2018-08-22 kl 09 54 50](https://user-images.githubusercontent.com/2311633/44450704-d55ad000-a5f1-11e8-98b0-978c95580e85.png)
![skarmavbild 2018-08-22 kl 09 55 09](https://user-images.githubusercontent.com/2311633/44450705-d5f36680-a5f1-11e8-8930-22f74825af35.png)

Notice on the Clear Storage tab, the path is just "://"
I'm forced to use the incognito window to read the docs right now

**Comment by jelbourn** [comment]
Try using chrome://serviceworker-internals instead of the devtools

**Comment by timmyrosen** [comment]
@jelbourn Thanks, that fixed it!

**Comment by mackelito** [comment]
What PR fixed this? We have similar issues and looking for a solution..
