### ISSUE TITLE
stackblitz requiring cdk 6.4.4

### ISSUE THREAD

**Issue by tsheils** [angular/material2#12662]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
On clicking "open in Stackblitz" on the sidenav examples, I sohuld be able to see Stackblitz

#### What is the current behavior?
error: 
![image](https://user-images.githubusercontent.com/6415791/44060010-2be86acc-9f21-11e8-965e-62b8c30eeb9c.png)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
click on any example here: https://material.angular.io/components/sidenav/overview

#### What is the use-case or motivation for changing an existing behavior?

N/A
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome on Linux, but it is a Stackblitz config issue

**Comment by josephperrott** [comment]
The docs site for 6.4.5 has been pushed.
