### ISSUE TITLE
use key and code instead of keycodes

### ISSUE THREAD

**Issue by sridesmet** [angular/material2#12667]
KeyboardEvent.keyCode is deprecated. https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

KeyboardEvent.key and KeyboardEvent.code should be used instead.

Thoughts?

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Comment by sridesmet** [comment]
Here you go: https://github.com/angular/material2/issues/12672
