### ISSUE TITLE
Rendering issue with accented characters

### ISSUE THREAD

**Issue by justin-nodeboy** [angular/material2#12669]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Render accented characters correctly

#### What is the current behavior?
Accented characters are not rendering correctly, if I use a standard HTML select element, the accented characters are rendered as they should be (see screen shot). But the Angular Material one doesn't. I have determined that it's not exclusively a select causing the issue. Even setting it in the header of a modal you can see it's not being rendered properly. I am at a loss.

![weird behaviour](https://user-images.githubusercontent.com/12255135/44095413-a5fffc94-9fd0-11e8-9a5e-2c3abcd5f645.PNG)

![renderbug](https://user-images.githubusercontent.com/12255135/44095422-acae4d20-9fd0-11e8-9929-9ea12771f71c.PNG)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

Annoyingly this works fine on StackBlitz...

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "^6.4.2"
"@angular/core": "^6.1.0"
"typescript": "~2.7.2"
Windows 7
Chrome Version 67.0.3396.87 (Official Build) (32-bit)
IE 11.0.9600.19080

**Comment by crisbeto** [comment]
Material doesn't do anything special with the string, as far as I'm aware. What could be happening is the front not having a glyph for those characters in particular.

**Comment by justin-nodeboy** [comment]
@crisbeto That was it, god damn company and it's rubbish font :)
