### ISSUE TITLE
Typo in List Readme

### ISSUE THREAD

**Issue by guntram** [angular/material2#1267]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
I should be able to copy paste from the Readme.

#### What is the current behavior?
If i copy paste from the Readme, the import doesn't work:

```import {MdLisTModule} from '@angular2-material/list/list';```

=> should be
```import {MdListModule} from '@angular2-material/list/list';```

#### What are the steps to reproduce?
Copy and paste the line above from the Readme.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
I don't think we need one :)

#### What is the use-case or motivation for changing an existing behavior?
I want to help others who copy paste code from Readme files.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2 final

#### Is there anything else we should know?
I don't think so :)

**Comment by JanStureNielsen** [comment]
@guntram -- with Angular 2.0.0 and Angular Material 2.0.0-alpha.8-2 the import should be:

    `import {MdListModule} from '@angular2-material/list'`

as noted in the [CHANGELOG.md](https://github.com/angular/material2/blob/master/CHANGELOG.md).

**Comment by guntram** [comment]
Dude, this one was fast! 😄
