### ISSUE TITLE
matTooltip not working on ios

### ISSUE THREAD

**Issue by iammanusharma** [angular/material2#12680]
#### What is the expected behavior?
tooltip is displayed on click of button

#### What is the current behavior?
Nothing is shown

#### What are the steps to reproduce?
Open the official documentation example https://material.angular.io/components/tooltip/examples
in ios device - iphone on chrome/safari browser

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5
Material latest
OS : ios
Browsers: All

**Comment by crisbeto** [comment]
On touch devices the tooltip shows up for a long press instead of a click.

**Comment by Priyakshi0703** [comment]
In my application I have imported hammerjs but still the tooltip is not working on long press nor in sigle click

**Comment by fimius23** [comment]
I’m also seeing this issue.

**Comment by cristiansandru11** [comment]
+1
