### ISSUE TITLE
Angular Material https://material.angular.io/ wont load every time after release of new version when browser cached previous version.

### ISSUE THREAD

**Issue by lpikora** [angular/material2#12683]
#### Bug

Every release of new version of Angular Material page (https://material.angular.io/) cause that page wont load on latest Chrome (blank screen), when browser have cached files of previous version of page.

#### What is the expected behavior?

Page (https://material.angular.io/) should load after an update.

#### What is the current behavior?

Page (https://material.angular.io/) wont load after an update when user have previously visited the page. 

Temporary fix is to remove service worker cache. 

<img width="622" alt="screen shot 2018-08-15 at 11 03 29" src="https://user-images.githubusercontent.com/8448523/44140744-4faee64c-a07b-11e8-9320-50beadc186c9.png">

#### What are the steps to reproduce?
Visit https://material.angular.io/, wait for an update, visit https://material.angular.io/ again and you will see blank screen.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Chrome Version 68.0.3440.106 (Official Build) (64-bit), MacOs

#### same issue
https://github.com/angular/material2/issues/12665

**Comment by jotatoledo** [comment]
Dup...

**Comment by jelbourn** [comment]
A new version has been deployed that _should_ eliminate this problem.
