### ISSUE TITLE
Strange rendered span in Radio Button

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#12687]
Does this span have any reason to exist? :-)

![image](https://user-images.githubusercontent.com/6654388/44152297-714565c2-a0a5-11e8-88ec-24d047b9c5f0.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.4.2

**Comment by crisbeto** [comment]
It's there for accessibility. There's a comment about it in the source: https://github.com/angular/material2/blob/master/src/lib/radio/radio.html#L32.
