### ISSUE TITLE
move out mat-checkbox in mat-table

### ISSUE THREAD

**Issue by Bobrovskih** [angular/material2#12685]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
mat-checkbox will remain in the old place

#### What is the current behavior?
mat-checkbox move out

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-amyxhr

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 5.2.11
material 5.2.4
browser google chrome
os windows

#### Is there anything else we should know?

![image](https://user-images.githubusercontent.com/34475297/44143232-946df970-a08b-11e8-91ef-b95b11ffe0fe.png)

helps to add style: 
```
.mat-column-checked {
  overflow: visible;
}
```

**Comment by eTallang** [comment]
Adding the styling you mentioned is mentioned in the docs as a required steps in order to use mat-checkbox in a mat-table. It's therefore debatable if it should be considered a bug.

**Comment by Bobrovskih** [comment]
issue closed, since the documentation says about this
