### ISSUE TITLE
material.angular.io is gone ?

### ISSUE THREAD

**Issue by Eusen** [angular/material2#12695]
![image](https://user-images.githubusercontent.com/14822175/44192575-8da3f680-a162-11e8-9b6a-9d85ac7b5428.png)

```
Unable to access this website

A web page with the address https://material.angular.io/may temporarily be disconnected or it may have been permanently moved to a new web site.

ERR_FAILED
```

In the last two days, this often happens. Today, I can't open it directly. What's the problem with this website?

**Comment by davidmontgom** [comment]
Why is the site down are you kidding me?  F--

**Comment by lpikora** [comment]
Try https://material.angular.io/index.php. It works for somehow.

**Comment by Eusen** [comment]
Today it's at work, I hope it can be worked all the time. =-=
