### ISSUE TITLE
Datepicker filter with available promise response

### ISSUE THREAD

**Issue by day01** [angular/material2#12691]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
`matDatepickerFilter: (date: D | null) => Promise<boolean> | boolean
`
#### What is the current behavior?
`matDatepickerFilter: (date: D | null) => boolean`

#### What are the steps to reproduce?
Preview of days in month

#### What is the use-case or motivation for changing an existing behavior?
I would like to filter days based on backend information. Which days are available which dont. All information cannot be cached on fronted for all years :)

#### Is there anything else we should know?
No :)

**Comment by jelbourn** [comment]
Is there a compelling reason not to just update the `filter` property once the data resolves?

**Comment by day01** [comment]
@jelbourn Could you suggest how? below pseudo-code
```
filterFunction(date: D | null) {
    let lockDaysArray = this.httpConfigurationClientWithCacheOption(date.getMonth(), date.getYear());
    return !lockDaysArray.find((x) => x === date);
}
```

**Comment by jelbourn** [comment]
```ts
class MyComponent {
  dateFilter = () => false;

  constructor() {
    getSomeData().then(dateList) {
      this.dateFilter = d => { dateList.includes(d) };
    }
  }
}
```
```html
<input matInput [matDatepickerFilter]="dateFilter">
```

**Comment by day01** [comment]
And could you say how many data should I take from service getSomeData()? 
1k? 2k? 10k? 100k records?
It doesn't sound good... 
In your proposal, I should download all records from db for all years and months. It means I should download from 1900 to 2100 in my situation all days off: holidays, national day off and weekends. And it cannot be cached because month by month it can be changed. 

It sounds like a really bad idea. 
Could you suggest a more realistic solution in this situation?

**Comment by jelbourn** [comment]
This is just illustrating the idea; you fetch some data and then update the filter. You have total control over what data you fetch, what parameters you use to fetch it, and how often it's called.

**Comment by day01** [comment]
@jelbourn 
I know how to update change dataFilter... 
I totally disagree with you about possibility of a asynchronize usages of datepicker. In my opinion, it sounds like 'it works for me' but you just never try to connect a changing month and download data in one solution.
For a clearer understanding, I will prepare a test case for that. 

Overall problem:
In changing month event is synchronize.  
It means when I start downloading data for days off, a datepicker filter is just starting iterating over days.  After data had downloaded, that all of the days were filtered.
