### ISSUE TITLE
Alignment issue with Stepper's numbers

### ISSUE THREAD

**Issue by amiralgazi** [angular/material2#12696]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The stepper's numbers are aligned to the center

#### What is the current behavior?
The stepper's numbers are not aligned to the center in some resolutions 

![untitled](https://user-images.githubusercontent.com/12114727/44197711-1c574a00-a148-11e8-8568-0e8ab2d987af.png)

#### What is the use-case or motivation for changing an existing behavior?
Design consistency

**Comment by DevVersion** [comment]
Can you explain what those situations are? I will try to look into it in the meanwhile.

**Comment by DevVersion** [comment]
Also some information about your browser, operating system etc. would be appreciated. Thanks

**Comment by amiralgazi** [comment]
@DevVersion 
Screen resolution is: 1920 x 1080,
Browser is: Version 68.0.3440.106 (Official Build) (64-bit),
Operating system is: 64-Bit Windows 10
