### ISSUE TITLE
Change events not fired in reactive forms html

### ISSUE THREAD

**Issue by owlstack** [angular/material2#12702]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, I am seeing this throughout my entire application after I upgraded from Angular 5 to Angular 6 (This behavior works just fine in Angular 5). Any change events set in my html e.g. after selecting a new value in my dropdown list,  should fire but currently does not.  

## Expected behavior
Change event should fire when the dropdown selection is changed for example. 

## Minimal reproduction of the problem with instructions

Add any (change) event to your forms dropdown list and try to change the value of the list after making a selection. 

E.g. I have this code snippet: 

```
 <span class="required transaction-span">
        <mat-form-field>
          <mat-select placeholder="{{'Location' | translate}}*" (change)="onStoreSelection()" formControlName="location" [ngClass]="displayErrors  && !this.form.get('location').valid && showLocationError ? 'inputRedBorder': 'input'">
            <mat-option selected *ngFor="let store of location.storeLocations" [value]="store._storeKey">{{ store._storeName }}</mat-option>
          </mat-select>
        </mat-form-field>
      </span>
```

onStoreSelection() never gets fired when I select a value. 

## What is the motivation / use case for changing the behavior?
Current behavior is broken. 

## Environment

<pre><code>

Angular CLI: 6.1.2
Node: 8.9.4
OS: darwin x64
Angular: 6.1.1
@angular/material                 6.4.2

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.4
- Platform:  Mac

Others:

Possibly related: 
https://stackoverflow.com/questions/51112478/angular-6-change-event-not-trigger-for-select2-dropdown
</code></pre>

**Comment by crisbeto** [comment]
The `change` event was renamed to `selectionChange` to avoid confusion with the native events.

**Comment by owlstack** [comment]
@crisbeto Are there any other breaking/major changes I should be aware of? If so, is there a link to a  list? Thanks!

**Comment by crisbeto** [comment]
You can find the breaking changes for each release in the changelog: https://github.com/angular/material2/blob/master/CHANGELOG.md.
