### ISSUE TITLE
Material control autocomplete override by browser settings

### ISSUE THREAD

**Issue by arun-yadav87** [angular/material2#12709]
#### Bug, feature request, or proposal:
I have tried to off autocomplete for control and form as well but the problem is that In chrome Auto fill functionality is controlled by bowser settings. Even if you have set autocomplete=”off” for a control and form in code that will get override by browser current settings .
If autocomplete is “Off” browser will not show autocomplete suggestion otherwise it will show.

#### What is the expected behavior?
If adding tag autocomplete = “Off” on material control it  should not show auto suggestion for that control.

#### What is the current behavior?
I have added autocomplete="off"  for input control but in chrome browser still showing autocomplete suggestion.

#### What are the steps to reproduce?
mat-form-field flex-xs="100" flex-sm="50" flex="40">
              <input matInput id="zipCode" placeholder="Zip Code" formControlName="zipCode" [(ngModel)]="propertyDetails.zipCode" #zipCode
                maxlength="{{propertyFormLengthValidation.zipCode}}" autocomplete="off" >
Add autocomplete="off" on input control .

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.0 Typescript=2.6.2 , OS=Windows, Browser: Google Chrome

**Comment by crisbeto** [comment]
Material already adds `autocomplete="off"` by default, but it's up to the browser if it wants to ignore it. A way to work around it is to change the value of the `autocomplete` to something different or to pick another `name` for the `input`.

**Comment by arun-yadav87** [comment]
Could you please explain work around with example.

**Comment by crisbeto** [comment]
You should be able to work around it by setting the `autocomplete` attribute to something else, e.g. `<input autocomplete="somethingUnique"/>`.

**Comment by thw0rted** [comment]
Just came here from #11818 to mention to anybody else having this issue, you also need to specify a `name` or Chrome will ignore your `autocomplete` value, even if it's `somethingUnique`.
