### ISSUE TITLE
bug(form-field): floating label conflicts with outline when initially hidden

### ISSUE THREAD

**Issue by CharlBest** [angular/material2#12715]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The form field outline shouldn't overlap with the floating label.

#### What is the current behavior?
Form field outline is overlapping floating label

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-cvq3kq-dwic6p

#### What is the use-case or motivation for changing an existing behavior?
bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.1.3
Material: 6.4.5

#### Is there anything else we should know?
Maybe related: https://github.com/angular/material2/issues/11919 although the label and input value is defined in my example it's just the container that is hidden initially. Thanks for taking a look.

**Comment by josephperrott** [comment]
Closing as we do not support the `hidden` attribute, css styling or `*ngIf` should be used instead.

**Comment by CharlBest** [comment]
@josephperrott Thanks for the feedback.
