### ISSUE TITLE
MatProgressBar _rectangleFillValue didn't display when routing is using hash

### ISSUE THREAD

**Issue by Eusen** [angular/material2#12710]
#### It‘s a Bug:
<mat-progress-bar [mode]='buffer'>

![image](https://user-images.githubusercontent.com/14822175/44251866-a082fd80-a22c-11e8-908b-1645602250f5.png)

In the official website, it is normal.
but in my site:

![image](https://user-images.githubusercontent.com/14822175/44251777-3d916680-a22c-11e8-9147-3ccd563f60b0.png)

u see, it’s blank!!!
In my router config, useHash is true, so my url is like:  `http://localhost:9621/#/preview/home`
This is the only point different from the official website.

I found  the bug:
![image](https://user-images.githubusercontent.com/14822175/44252163-dffe1980-a22d-11e8-8aba-a688709742b5.png)
If I adjust it as follows:
![image](https://user-images.githubusercontent.com/14822175/44252201-02903280-a22e-11e8-9701-c24bc2114834.png)
![image](https://user-images.githubusercontent.com/14822175/44252280-3e2afc80-a22e-11e8-9f81-b72a2b0375cf.png)
It's worked!

#### What is the expected behavior?
To normal.

#### What is the current behavior?
MatProgressBar buffer mode is blank.

**Comment by Eusen** [comment]
I also don't understand why the progress bar in query mode is static.
![280e745ed2930f69cea5085358de6c4](https://user-images.githubusercontent.com/14822175/44253930-cfe93880-a233-11e8-8b53-316860c14638.png)

**Comment by jotatoledo** [comment]
query mode is currently broken, was solved by https://github.com/angular/material2/pull/11459

Should be released on next patch most likely

**Comment by Eusen** [comment]
query mode is likely indeterminate mode, if just set:
```
.mat-progress-bar[mode=query] {
   transform: scale(-1);
}
```
it's simple to implement
