### ISSUE TITLE
BrowserAnimationsModule fail on Android 4.4 and Android 5.0

### ISSUE THREAD

**Issue by jpierront** [angular/material2#12730]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It should works.

#### What is the current behavior?
JS errors occurs.
* TypeError: Cannot read property 'trim' of undefined at applyKeyframeAnimation
* Cannot read property 'split' of undefined at removeKeyframeAnimation

#### What are the steps to reproduce?
Just click on "Pick One" on this official page with an Android 4.4/5.0 device: https://material.angular.io/components/dialog/overview

#### What is the use-case or motivation for changing an existing behavior?
It should works on this device type as Angular do.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
It's works on Angular 5.X + Angular Material 5.X but not on Angular 6.1.4 + Angular Material 6.4.5

#### Is there anything else we should know?
There is no crash when you use NoopAnimationsModule instead of BrowserAnimationsModule ... but there is no animation ;-)

**Comment by crisbeto** [comment]
This looks like an issue with the animations module. The issue should be posted to the main repo: https://github.com/angular/angular/issues.

**Comment by jpierront** [comment]
Sorry, probably an Angular issue. https://github.com/angular/angular/issues/25563
