### ISSUE TITLE
Documentation site won't load

### ISSUE THREAD

**Issue by scooby359** [angular/material2#12745]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Documentation site should load on request to URL - https://material.angular.io/

#### What is the current behavior?
Occasionally doesn't load on direct request to URL, with or without "https//" prefix
Browser console displays error about service worker

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
1. Launch firefox
2. Enter URL material.angular.io

#### What is the use-case or motivation for changing an existing behavior?
n/a

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current Material documentation page - 6.4.5
Using Firefox Quantum 61.0.2

#### Is there anything else we should know?
Behaviour is intermittent and has occured several times for me - 
Browser console wiped so was unable to capture error, unable to reproduce error immediately after

**Comment by DevVersion** [comment]
Hey, we've removed the service worker from the docs a few days ago. As soon as you can hard-refresh the page without using cache, the service worker should be gone.

Meaning that you never should run into the given issue anymore. Let me know if you still run into any other issues with the docs. Thanks!
