### ISSUE TITLE
mat-checkbox does not tigger touched correctly

### ISSUE THREAD

**Issue by michael-letcher** [angular/material2#12743]
#### Bug, feature request, or proposal:
Touched in not set to true correctly

#### What is the expected behavior?
Touched should be set to true on first interaction

#### What is the current behavior?
Touched in not set to true on first interaction

Firefox / Safari: Never changes
Chrome: Changes on second interaction

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Expect the same behaviour from Angular

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.1.3
Material: 6.4.5
OS: MacOS
Browsers: Chrome, Firefox, Safari

#### Is there anything else we should know?
Nope 🥇

**Comment by DevVersion** [comment]
Thanks for your issue. The desired behavior is that the `ng-touched` state will be set on _first_ blur of the checkbox. This seems to work for me inside of Chrome and Firefox. 

Can you please provide more details? Thanks!

**Comment by michael-letcher** [comment]
@DevVersion Thank you for the clarification.

I noticed I didn't add my stackblitz test, but this does work as intended.
https://stackblitz.com/edit/angular-e6z35y
