### ISSUE TITLE
Block scroll strategy for mat-select works same as noop strategy with custom scroll area in Firefox

### ISSUE THREAD

**Issue by dkonasov** [angular/material2#12747]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Block scroll strategy for mat-select must block scroll in closest parent scroll area when panel is opened.

#### What is the current behavior?
If closest parent scroll area is not document element, mat-select with opened panel and block scroll strategy behaves like it has noop scroll strategy.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-819jcf

#### What is the use-case or motivation for changing an existing behavior?
Some apps can have custom scroll area and mat-select scroll strategy will not always work with them as expected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "6.1.3", "@angular/material": "^6.4.5", macOS High Sierra 10.13.3, "typescript": "2.9.2", Firefox 61.0.2 64-bit

#### Is there anything else we should know?
No

**Comment by crisbeto** [comment]
This is the same issue as https://github.com/angular/material2/issues/12746.

**Comment by dkonasov** [comment]
Actually, in case of Firefox it's not the same as #12746. In Firefox backdrop doesn't blocks scroll events, at least if it has zero opacity. If you try Stackblitz example in Firefox, you will see that scrolling isn't actually blocked, while scroll strategy factory returns BlockStrategy. In Chrome yes, scroll is blocked because of backdrop, but not in FIrefox.

**Comment by crisbeto** [comment]
Looks like I made a typo. It's #12746.
