### ISSUE TITLE
Reposition scroll strategy for mat-select doesn't works in Chrome with custom scroll area

### ISSUE THREAD

**Issue by dkonasov** [angular/material2#12746]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Reposition scroll strategy for mat-select should reposition panel during scrolling.

#### What is the current behavior?
When mat-select panel is opened scrolling is blocked&

#### What are the steps to reproduce?
Reposition scroll strategy for mat-select doesn't works in Chrome if scroll area is not on document element (for example when we have some main area div with some vertical-scroll on it).
https://stackblitz.com/edit/angular-material2-issue-mcmlqa

#### What is the use-case or motivation for changing an existing behavior?
Some apps can have custom scroll area and mat-select scroll strategy will not always work with them as expected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "6.1.3", "@angular/material": "^6.4.5", macOS High Sierra 10.13.3, "typescript": "2.9.2", Chrome 68.0.3440.106 64-bit

#### Is there anything else we should know?
No

**Comment by crisbeto** [comment]
That's because the backdrop catches the mouse events. It should be resolved by https://github.com/angular/material2/pull/7779.
