### ISSUE TITLE
mat-select multiple selection pop up translateX too big

### ISSUE THREAD

**Issue by lymychm** [angular/material2#12749]
#### Bug, feature request, or proposal:
**proposal**

#### What is the expected behavior?
Do not set **transform: translateX that big**

#### What is the current behavior?
transform: translateX is set to big for mat-select multiple selection pop up

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
You can just check select on official https://material.angular.io/components/select/overview
multiple select pop up(after click) is out of **card**, when the **single** one is pretty and inside **card**

Single: http://prntscr.com/kkpyv7
Multiple: http://prntscr.com/kkpz9j (as you can see, it out of **card** content)

#### What is the use-case or motivation for changing an existing behavior?
It will look better

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Browser: this behavior in all browsers
Material: 6.4.5
Angular: 6.1.1

**Comment by crisbeto** [comment]
This is the correct behavior. The idea is that the label in the option is supposed to align with the label on the select trigger.
