### ISSUE TITLE
Md-icon has a bug

### ISSUE THREAD

**Issue by HeavenlyHost** [angular/material2#1275]
#### Bug, feature request, or proposal:
When attempting to use an icon as provided by material icons that is named with more than one word the icon is not loaded ?

#### What is the expected behavior?

`<md-icon>perm identity<\md-icon>`

should display using the ligatures name provided but does not, however...

`<md-icon>face<\md-icon>` 

works perfectly fine ?

#### What is the current behavior?
ligatures names of more than one word do not load

#### What are the steps to reproduce?

`<md-icon>perm identity<\md-icon>`

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0.0 final, Material 2 Alpha 8.2, Chrome 52

**Comment by nkwood** [comment]
Try `perm_identity`.

**Comment by HeavenlyHost** [comment]
Really ? I shall try tomorrow, if this works I think the docs need updating because it was not explained very well 😐

**Comment by MoxxNull** [comment]
Had the same problem, as nkwood said, replace any space with an underscore ("_"), that does the trick!

**Comment by jelbourn** [comment]
Closing this, since this is just how the ligatures are defined in the icon font.

**Comment by HeavenlyHost** [comment]
@jelbourn can confirm that fix as described works, although do believe it inaccurate in docs, this needs highlighting 😊

**Comment by michaeljota** [comment]
I support @HeavenlyHost, you should update the docs to show the proper use of the ligatures. (Or is it wide expected to be used as it is?)
