### ISSUE TITLE
explaining the revert to <table>, <th>, <td>

### ISSUE THREAD

**Issue by tatsujb** [angular/material2#12753]
#### Bug, feature request, or proposal:

feature request

#### What is the expected behavior?

having an explanation for this change or docs that are aware of use and syntax evolution through time, why not a migration guide. 

#### What is the current behavior?

not having an explanation for this change or docs that are aware of use and syntax evolution through time, nor a migration guide. 

#### What are the steps to reproduce?

going to https://material.angular.io/components/table/overview#sticky-rows-and-columns

#### What is the use-case or motivation for changing an existing behavior?

having used mat tables 5, 6 and 6.2 then deciding to upgrade to 6.2.1

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

all angular versions all OSes, all typescript versions, all browsers, and all previous versions of Material when upgrading to 6.2.1

#### Is there anything else we should know?

The biggest change we material users must deal with is  `<mat-table>`,  `<mat-header-row>`, `<mat-row>`, `<mat-header-cell>` and `<mat-cell>` tags being switched back out for the more "html" `<table>`,  `<tr>`,  `<tr>` ,  `<th>`, `<td>`, with respective properties detached from the tag name.

I had to find out via the examples in the mat table doc page upon wanting to document myself on the required syntax for pinned header and columns. 

not only that but through trial and error I had to work out that the old tags still do work.

but information is lacking for a number of questions including the two already self-discovered.

Am I missing something or was there no communiqué on this?

If not, can I know why this change was made? I'm guessing performance increased and probably css became clearer? but I don't know for sure but I'm definitely interested in knowing. I could learn from this. And learn to expect this sort of switch in the future.

Also will the tags be deprecated? they work now but switching them out for `<th>`, `<td>`. nukes my  css pretty violently. 

with `<mat-header-cell>` and `<mat-cell>` : 
![image](https://user-images.githubusercontent.com/5132359/44269344-8a793b00-a234-11e8-85c5-fe5579c3da66.png)

with `<table>`,  `<tr>`,  `<tr>` ,  `<th>`, `<td>` : 
![image](https://user-images.githubusercontent.com/5132359/44269781-d7a9dc80-a235-11e8-83e9-dbd9907631c3.png)

If they ARE to be deprecated we would need a transition guide between the two syntaxes.

On another note, thank you very much for the fixed column and header implementation, i use them and appreciate them very much.

**Comment by jelbourn** [comment]
Both are supported; native tables are easier to make accessible and give the advantage of things like `border-collapse` and more intelligent column sizing. We let users make the decision about which is more appropriate for their app, but recommend native `<table>` elements as the default.

**Comment by tatsujb** [comment]
those are good reasons. I want to take advantage of the benefits "`<table>` syntax" presents.

how do I switch from `<mat-table>` to `<table>` replacing all the tags, isn't working : as displayed above? what am I getting wrong? what am I missing?
