### ISSUE TITLE
Add progress indicator for `ng update`

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#12774]
We should ensure that our `ng update` schematic gives some progress indication while it's running so that users don't think that it's frozen.

**Comment by DevVersion** [comment]
Looked into it. There is currently no way we can create a progress indicator our self. I might be able to contribute a progress indicator for the `TSLintFixTask` at some point, but this is not a priority for now.

I'd rather improve the performance of the schematics (for now) by not running rules which don't have a data for the target version.

**Comment by jelbourn** [comment]
That's reasonable. It would be good to at least file an issue on the CLI repo requesting a suitable API.

**Comment by DevVersion** [comment]
I actually chatted with Hans about it, but I agree that it wouldn't hurt having a public issue for it. See: https://github.com/angular/angular-cli/issues/12479

**Comment by DevVersion** [comment]
Closing at it's being tracked on the CLI repository.
