### ISSUE TITLE
Angular material-tree-dynamic not working properly when clicking on multipul nodes parallel 

### ISSUE THREAD

**Issue by studygcs** [angular/material2#12771]
#### Bug:

while expanding multiple nodes parallel respective child nodes are not coming properly 
please see the below screen shots.

Please find this issue in angular material site also.
https://material.angular.io/components/tree/examples 

#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/38679884/44399115-eeb53b00-a563-11e8-93ad-f34956190c01.png)

#### What is the current behavior?

![image](https://user-images.githubusercontent.com/38679884/44399154-1906f880-a564-11e8-917b-ae2162c5b968.png)

#### What are the steps to reproduce?
expand multiple nodes parallel (with in milliseconds)

https://stackblitz.com/edit/material-tree-dynamic?file=app%2Fapp.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular Material 6.4.6 version

**Comment by josephperrott** [comment]
This is occurring because the second update is acting based on the data from before the fake "loading event" completes.

You can see a working fork [here](https://stackblitz.com/edit/material-tree-dynamic-mtip6b?file=app/app.component.ts).
