### ISSUE TITLE
PaginatorIntl doesn't notify on changes

### ISSUE THREAD

**Issue by Pamasich** [angular/material2#12787]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

[MatPaginatorIntl](https://github.com/angular/material2/blob/master/src/lib/paginator/paginator-intl.ts) contains a Subject `changes`, which is supposed to notify the paginator about changes to the labels.

> Stream that emits whenever the labels here are changed. Use this to notify components if the labels have changed after initialization.

Given above quoted comment from the source file, my expectation is that `changes` emits automatically when a label changes, and thus the paginator component gets updated with the new labels.

#### What is the current behavior?

When I change the labels, the paginator won't reflect the changes until I interact with it. I've tried to subscribe to the `changes` subject to see if it even emits anything, and the subscription never triggered. When I manually call `changes.next()` after doing my changes, it works perfectly. But as mentioned above, the comment implies this should happen automatically.

#### What are the steps to reproduce?

Can't provide a stackblitz right now due to too little time, but I might add one later if required.

#### What is the use-case or motivation for changing an existing behavior?

I'm trying to make the paginator work with ngx-translate. Changing the labels whenever the active language changes. It's easy to fix this locally by just calling `changes.next()` after doing my changes, so it's not a huge issue for me. But it looks like it's a bug, so I thought I'd report it.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

* Angular 6.0.8
* Material 6.4.6 (also applies to 6.3.1)

**Comment by crisbeto** [comment]
The point of the `changes` is that you're supposed to call it yourself when you've changed the labels.

**Comment by josephperrott** [comment]
Closed by #13029
