### ISSUE TITLE
100% height on md-sidenav-layout

### ISSUE THREAD

**Issue by istiti** [angular/material2#1278]
#### Bug, feature request, or proposal:
It's envisageable add height 100% whole window to tag md-sidenav-layout

#### What is the current behavior?
Current md-sidenav-layout only fit height of their content...

**Comment by msegers** [comment]
Is it too much of a problem to do this yourself?
I'm not sure if it should go into material2. I just put 100vh on md-sidenav-layout.

**Comment by istiti** [comment]
it was proposition, maybe oversight but OK
