### ISSUE TITLE
mat-error does not display properly using custom cross validation

### ISSUE THREAD

**Issue by Worthy7** [angular/material2#12796]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Show form validation error text

#### What is the current behavior?
mat-error only shows if the Confirm Password field is kept empty.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-59b6pg

#### What is the use-case or motivation for changing an existing behavior?
It's broken.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.4.6

**Comment by manklu** [comment]
@Worthy7 Since you set the error on the group, both form fields are displayed with no error.

**Comment by Worthy7** [comment]
@manklu  I see what you mean but I just moved it and the same thing happens.
https://stackblitz.com/edit/angular-material2-issue-59b6pg

**Comment by Worthy7** [comment]
@manklu Actually I'm not sure what you mean. Can you show me a version that works?

**Comment by manklu** [comment]
@Worthy7 https://stackblitz.com/edit/angular-material2-issue-nk4pbz?file=app%2Fapp.component.html

**Comment by Worthy7** [comment]
I don't fully understand but that works so it's not a bug
