### ISSUE TITLE
AoT: Property 'ngOnInit' does not exist on type 'MdTooltip'

### ISSUE THREAD

**Issue by spock123** [angular/material2#1279]
Hey guys,
- I can use the AoT compiler without errors, but once I start serving the application with Webpack2, the type checker gives me the following errors:

`buttons/buttons.component.ngfactory.ts:881:81 Property 'ngOnInit' does not exist on type 'MdTooltip'.`

Angular: 2.0.0
 Awesome-typescript-loader: 2.2.4
Webpack: 2.1.0-beta.22

Any ideas?

**Comment by ivoviz** [comment]
Had the same issue, as a workaround until it's fixed you can just simply add `ngOnInit(): void;` to `node_modules/@angular2-material/tooltip/tooltip.d.ts`.

**Comment by spock123** [comment]
Thanks @ivoviz - worked beautifully

**Comment by jelbourn** [comment]
This should have been resolved in alpha.9
