### ISSUE TITLE
Angular Table Page-Wise Selection

### ISSUE THREAD

**Issue by accelexcel** [angular/material2#12797]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Angular Table Page-Wise Selection: currently selection model applies to all the rows in the table. There is no way to limit selection to the current page. It seems a fairly common requirement.

#### What is the current behavior?
Selection model applies to all the rows in the table, meaning that clicking the checkbox in the header row selects all the rows in all the pages.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
Here is a solution: https://stackblitz.com/edit/angular-4by7xt

#### What is the use-case or motivation for changing an existing behavior?
In many applications the user needs to select only the rows that are on the current page, since this the page he has been working on.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All versions.

#### Is there anything else we should know?
I can implement a comprehensive solution.

**Comment by accelexcel** [comment]
https://stackblitz.com/edit/angular-4by7xt

**Comment by josephperrott** [comment]
Closing as the implementation that you provided does apply the selection model to all items in the table, however this is due to the nature of the implementation in your example.

There is nothing limiting your selection check from only comparing itself and acting upon currently visible items.
