### ISSUE TITLE
[MatMenu] MatMenuTrigger aria-expanded changeDetection error

### ISSUE THREAD

**Issue by apo34** [angular/material2#12798]
#### Bug, feature request, or proposal:
Clicking on backdrop of menu before it opens, causes error to show up on trigger

#### What is the expected behavior?
Error should not occur

#### What is the current behavior?
Clicking on backdrop of menu before it opens, causes error to show up on trigger

#### What are the steps to reproduce?
[Stackblitz](https://stackblitz.com/edit/angular-qxnyk6?file=src%2Fapp%2Fitem%2Fitem.ts)
Click on menuTrigger -> immediately after, click somewhere else -> error shows in console

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.1.4
Material: 6.4.6

![image](https://user-images.githubusercontent.com/28670067/44508042-24b20680-a6ad-11e8-9358-3cf26420d49d.png)

**Comment by apo34** [comment]
Any ideas how to fix this?

**Comment by apo34** [comment]
I'd gladly fix that if someone was to point me in the right direction.
I found that it's possible to fix this by calling change detection after changing the value, but I'm not quite sure if that this is the best way.

**Comment by PachowStudios** [comment]
Also getting this if I click anywhere while the menu is still opening. Is anyone investigating a fix?

**Comment by apo34** [comment]
Seems to be fixed with version 7: [stackblitz](https://stackblitz.com/edit/angular-yddyvs)
Thanks!

**Comment by StefanoLucchi** [comment]
Still happen by repeatedly and quickly clicking on the trigger menu: [stackblitz](https://stackblitz.com/edit/angular-stgyux)

**Comment by mattiLeBlanc** [comment]
I am also occasionally running into this error while using a mat-menu as part of a mat-table that is dynamically generated.
I can't easily reproduce it, but it seems to happen on a quick click .
