### ISSUE TITLE
Collect code coverage

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#128]
We should collect and surface our unit test code coverage. While a high coverage does not necessarily tell you much about the quality of your tests, a _low_ coverage does tell you that something is amiss.

**Comment by d3viant0ne** [comment]
@jelbourn - I'll pick this one up.

I assume I should work out the particulars with @hansl again?

**Comment by jelbourn** [comment]
@d3viant0ne sounds good! If @hansl is willing to chat about it on gitter that works for me, but we can also do the discussion here. 

As a starting point, I'm okay with just printing out the coverage as part of the Travis jobs. Then, as a follow-up, we can send that data off somewhere (probably some firebase instance) and incorporate it into a dashboard. 

As far as actual implementation goes, I'm not sure what the best avenue will be. The `karma-coverage` plugin uses the instanbul tool, but by itself doesn't support TypeScript. So there's exploration to happen in determining which tools are viable.

**Comment by hansl** [comment]
@d3viant0ne 

Supporting TypeScript in karma with coverage is the problematic part of this plan, actually. Otherwise it should be straightforward. There is a few results for searching "code coverage karma typescript" on Google, but nothing out of the box. It is likely that we will need a custom made solution. For now, making a personal repo (or even just adding files to Material2) and using that should be great. That would be super useful for other TypeScript developers!

I'm not hanging often on gitter so let me know what would be a good time and I'll try to show up.

**Comment by d3viant0ne** [comment]
@hansl - I just did this for Minko's seed project so it's definitely possible in some form. It really just depends if the less than perfect solution is acceptable or if we would rather wait for a home grown version. 
I'll take a run at it, get it executing in travis and we can discuss.

And don't worry about Gitter, I imagine you get spammed with question if your status goes green.

**Comment by d3viant0ne** [comment]
@hansl - I've done TypeScript coverage using [remap-istanbul](https://www.npmjs.com/package/remap-istanbul) on a few projects but the implementation has always been very project specific.

My question is .. Do we want to do this in two parts?

**Phase 1:** Simple implementation of karma-coverage outputting to the command line when running "npm test"

This I could PR right now, karma doesn't exactly make coverage reporting hard :) 
There is also a feature in remap-istanbul#master related to relative paths I would need to make it work.

**Phase 2:** Tailored, more complex implementation using remap-istanbul for dev TS coverage which also reports coverage in CI to a 3rd Party service && comments on the pull request.

While I personally think reporting coverage based on the transpiled javascript should be taken with a grain of salt ( branches in particular ) it does show you where most of the holes are. While it's not something I would keep for historical purposes, I do believe there is a short term benefit for code quality.

**Comment by jelbourn** [comment]
@d3viant0ne sounds good, though you could break it down even smaller:

1. Just like you said, print out the basic js coverage w/ `npm test`
2. Add the mapping back to the TypeScript source
3. Run on Travis, just printing out the results
4. Actually send the data somewhere more useful (TBD)

Thanks for looking into this!

**Comment by d3viant0ne** [comment]
@hansl @jelbourn - I'll spec this out tonight. I have a few DX changes that would go along with this but I want to try them out before hand.

**Comment by d3viant0ne** [comment]
> Implementation using karma-remap-istanbul / remap-istanbul 

- Local dev coverage via command line & html ( will support typescript coverage on watch )
- CI coverage via command line & coverage.json

As far as i can tell externally, historical code coverage isn't kept for Angular / 2 or Material. 

In the short term, do we want to archive the coverage.json in a build artifact / s3 / something google?Do we want to send it to a 3rd party service until a homegrown dashboard exists?

//cc: @hansl @jelbourn

**Comment by d3viant0ne** [comment]
**note:** After a bit of discussion, the "test" task will be left alone. Code coverage will be generated via it's own npm task
