### ISSUE TITLE
Sidebar closes before inputting a value to matInput in Dialog sidebar

### ISSUE THREAD

**Issue by ganeshkbhat** [angular/material2#12806]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Able to focus and provide value to matInput in sidebar. 
#### What is the current behavior?
Unable to focus and provide value to matInput in sidebar. The sidebar closes with a box in a bottom in mobile. Note Focus on the search Key input in the link provided. The sidebar closes before inputting a value to matInput. Dialog sidebar is being used in sidebar.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-7xpsfc?file=app%2Fapp.component.html

Issue can be replicated in Android 5.0 (Check in mobile browser)
https://angular-material2-issue-7xpsfc.stackblitz.io/

#### What is the use-case or motivation for changing an existing behavior?
User expereince

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
**dependencies**
"dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/cdk": "^6.2.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/material": "^6.4.6",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "core-js": "^2.5.4",
    "ng2-ace-editor": "^0.3.8",
    "rxjs": "^6.0.0",
    "zone.js": "~0.8.26"
  }

**NG-CLI**
Node: 10.7.0
OS: linux x64
Angular: 6.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.4
@angular-devkit/build-angular     0.7.4
@angular-devkit/build-optimizer   0.7.4
@angular-devkit/build-webpack     0.7.4
@angular-devkit/core              0.7.4
@angular-devkit/schematics        0.7.4
@angular/cdk                      6.4.6
@angular/material                 6.4.6
@ngtools/webpack                  6.1.4
@schematics/angular               0.7.4
@schematics/update                0.7.4
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
#### Is there anything else we should know?

![screenshot_2018-08-23_201522](https://user-images.githubusercontent.com/3424344/44533155-822c6e80-a712-11e8-873c-349b29d7e0ca.jpg)

**Comment by josephperrott** [comment]
Closing as you are able to focus items after the sidenav opens using the `openedChange` output.

I have [forked the stackblitz](https://stackblitz.com/edit/angular-material2-issue-uzmzcm?file=app/app.component.ts) that you provided to show this
