### ISSUE TITLE
[md-slide-toggle] (change) is fired only on click and not on drag

### ISSUE THREAD

**Issue by vapits** [angular/material2#1280]
#### Bug
Yes

#### What is the expected behavior?
Should work on click but also on drag of the switch.

#### What is the current behavior?
It fires up the noted function only on click on the switch and not on the drag of the switch.

#### What are the steps to reproduce?
http://plnkr.co/edit/BmNRSOvaaRFJKQkiLnFz?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
I have tested in almost all latest versions and in Mac El Capitan and Windows 10 with latest Chrome browser.

**Comment by DevVersion** [comment]
@jelbourn Can you close this as a duplicate for #1390?

**Comment by vapits** [comment]
@DevVersion wasn't this first here? I don't mind closing this if you want.

**Comment by DevVersion** [comment]
@vapits Oh yeah it was definitely the first issue. I just asked to close this one, because otherwise we need to amend the commit of the PR and reference this PR.

If can do that if you want ;)

**Comment by vapits** [comment]
Ok, just said because I was wondering how do you guys choosing what is dup, is it based on timeline or description etc. And said that also because there was already a reference of dup into #1304 to this issue.

**Comment by DevVersion** [comment]
Oh sorry, it sas not related to your description or something else. Your issue is great described.
> Not sure how #1304 relates to your issue though.

**Comment by vapits** [comment]
Yeah didn't read it completely I just saw the reference by @nisdec.
Anyways ;)
