### ISSUE TITLE
Docs: no sample Dialog code

### ISSUE THREAD

**Issue by hughanderson4** [angular/material2#12801]
On the Dialog docs page, all the sample code is for buttons that invoke Dialogs.

Need to include some sample code that shows the actual html of the Dialog itself, not just the button.

Button page contains plenty of button examples.  Dialog page is for Dialog.

Click the "View Source" button in this page (looks like angle brackets `< >`)
https://material.angular.io/components/dialog/examples
Notice there is no code applicable to Dialog in the example.

**Comment by josephperrott** [comment]
You can see the dialog content html [in the running stackblitz example](https://stackblitz.com/angular/mavlvgmydrg?file=app%2Fdialog-overview-example-dialog.html) you referenced.

**Comment by hughanderson4** [comment]
I realize that.  It is just not intuitive that the example code shows no Dialog html.  Don't you consider that a shortfall of the docs?  I would prefer to not have this issue closed, but instead to actually improve the docs to not rely on an external link to show critical information.
