### ISSUE TITLE
not able to use ng-container within mat-grid-list

### ISSUE THREAD

**Issue by tbnovaes** [angular/material2#12809]
#### Bug, feature request, or proposal:
Allow ng-container to work inside mat-grid-list

#### What is the expected behavior?
Being able to use ng-container inside mat-list-grid, so it would allow to have ngSwitch or *ngFor doing some logic before creating the item.

#### What is the current behavior?
If you try to add ng-container nothing is rendered.

#### What are the steps to reproduce?
1 - Create a mat-grid-list
2 - Add ng-container with ngFor or ngSwitch
3 - Add the mat-grid-tile, and nothing is rendered

https://stackblitz.com/edit/angular-material2-issue-8vvb8z

#### What is the use-case or motivation for changing an existing behavior?
Being able to generate a dashboard dynamically based on the type of component you need to load, and use breakpointObserver to define the number of columns based on the type of the widget.

For example:
widget 1 loads a map
widget 2 loads a random number of charts, where it chart should be a tile

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.2
Angular Material 6.4.5
macOS 10.13.6
Typescript 2.9.2
All Browsers

**Comment by geromegrignon** [comment]
mat-grid-list is an host element, you shouldn't rely on ng-container for your structural directives and use them directly in mat-grid-list balise tag.

> <mat-grid-list cols="6" rowHeight="350px" *ngFor="let card of cards" [ngSwitch]="card.type">

**Comment by tbnovaes** [comment]
@geromegrignon Yes I understand, but I still think that limiting it to accept only mat-grid-tile as its child, does not allow too much flexibility on a more complex view. And while I could use flex-layout to achieve the responsive the design I need, it would not be as easy to maintain as using the grid.

**Comment by hughanderson4** [comment]
Please reopen this issue.  It is not fixed in @angular/material@7.1.1

See my Stackblitz link here:  https://stackblitz.com/edit/angular-material2-issue-zdxvqh

I try to use `ng-container` with `ng-template` because i want to transclude the content instead of having that as a string.
