### ISSUE TITLE
Option to disable slide animation in mat-tab content.

### ISSUE THREAD

**Issue by trshafer** [angular/material2#12812]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Ability to disable slide in animation for tabs

#### What is the current behavior?
Tab content currently slides in when a new tab is selected. It would be helpful to add an input option to disable this animation

#### What are the steps to reproduce?
https://material.angular.io/components/tabs/examples
https://stackblitz.com/edit/angular-material2-issue-7aucx8?file=app%2Fapp.component.html

#### What is the use-case or motivation for changing an existing behavior?
The tabs can be distracting for certain audiences or circumstances.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular material: 6.4.6

**Comment by DevVersion** [comment]
Usually you can just disable all animations by using the `NoopAnimationsModule`. I assume you don't want to disable all animations of the application though?

**Comment by kekraft** [comment]
In this case, we want to disable just the slide animation.

**Comment by GitSage** [comment]
@DevVersion Using NoopAnimationsModule can be a problem sometimes, e.g. if you want to conditionally disable animations during runtime, or if you can't deploy a second animation-free build.

Do you know if that PR will make [the `@.disabled` binding](https://angular.io/api/animations/trigger) correctly disable the animation?

**Comment by DevVersion** [comment]
@kekraft @GitSage That makes sense. Using `@.disabled` binding will partly work and only disabling the content slide animation (for now).

My plan is to also disable animations for the inkbar etc. if `@.disabled` is specified.

**Comment by patoncrispy** [comment]
The problem with  @.disabled is that it disables animations for all child components too. I currently have an expansion panel underneath a tab and I need the animation for that but not the tab. Any way to solve that conundrum?

**Comment by patoncrispy** [comment]
@GitSage ".disabled="false" doesn't work. Also, I think to use `animateChild` requires you to know the animation triggered. Also, that shouldn't be a solution. As mentioned before, it should be simple enough to add a property to disable animations on components without having to hack away.

**Comment by fookensoul** [comment]
I've been looking at this as well.  There is no option to disable the sliding in animation.  I've worked around it by hooking into the start and stop events.  What makes it worse is that the actual site uses a better tab transition than any in the api.

**Comment by stagefright5** [comment]
@fookensoul , can you share a bit more detail about your workaround?

**Comment by mik01aj** [comment]
See issue #13428 and PR #13505. The option is already there. This bug can be closed.

**Comment by crisbeto** [comment]
Closing since the option for controlling the animation duration is in master.

**Comment by Alex-Torres** [comment]
Hey @crisbeto the animationDuration is not yet available for Tabs on 7.04 right?

**Comment by crisbeto** [comment]
It should be in 7.1.0.

**Comment by Alex-Torres** [comment]
Nice!  Thank you @crisbeto.
