### ISSUE TITLE
Chip close button out of bounds

### ISSUE THREAD

**Issue by kirill-chirkov-at-clouty** [angular/material2#12818]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Close button should be always visible on chip

#### What is the current behavior?
Long text might push chip close button out of viewport

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-nwqxtf

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 6.4.5

**Comment by crisbeto** [comment]
I took a quick look at it, but I don't think we can do much about it without making `mat-chip` into a component. Since it's a directive, we can't wrap the text in another `div` which would allow us to truncate it. You can work around the issue in your example by adding this to your CSS:

```css
.mat-standard-chip {
  word-break: break-word;
}
```

**Comment by josephperrott** [comment]
Closing as this is not something that can be addressed with the `MatChip` existing as a directive.  As @crisbeto noted, you can address this in your application by handling the truncation yourself for your usages.
