### ISSUE TITLE
Mat tab group content doesn't fill the whole screen

### ISSUE THREAD

**Issue by donpironet** [angular/material2#12826]
#### Bug, feature request, or proposal:
I'm having a mat-tab-group with components as content like this:

```
<mat-tab-group>
  <mat-tab label="Test1"> <app-canvas1></app-canvas1> </mat-tab>
  <mat-tab label="Test2"> <app-canvas2></app-canvas2> </mat-tab>
</mat-tab-group>
```
Both components have on their container height: 100%.
I the components are having just a grid.

#### What is the expected behavior?
That the components are filling the whole screen under the tabs.

#### What is the current behavior?
It only takes 40% of the screen not showing the whole component.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/edit/angular-material2-issue-jkk9xt

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.0
Angular Material 6.4.2

**Comment by aloketewary** [comment]
I think the issue lies on the grid height. you can use dynamicHeight to see the issue of Grid height.

**Comment by donpironet** [comment]
When I enable dynamicHeight nothing changes. How exactly can I debug this with this flag on true? 
Do I need to put a minimum height on my grid?

**Comment by donpironet** [comment]
I found the problem. If you remove the height 100% on the grid container it works.
Thanks for your help.

**Comment by aloketewary** [comment]
In height related issues you try with `percentage `if not works then try with `vh` if it not works then report issue.
