### ISSUE TITLE
optionSelectionChanges not being triggered

### ISSUE THREAD

**Issue by odahcam** [angular/material2#12821]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`optionSelectionChanges` triggered on options change.

#### What is the current behavior?
`optionSelectionChanges` isn't triggered, only `selectionChanges` works.

#### What are the steps to reproduce?
https://stackblitz.com/angular/pldoxdmvjog?file=app%2Fselect-overview-example.html

#### What is the use-case or motivation for changing an existing behavior?
Docs seems to be wrong. (?)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Angular 6.1.1 and 6.1.4
- Material 6.4.2

#### Is there anything else we should know?
Sorry, I dunno.

**Comment by crisbeto** [comment]
It doesn't look like you're subscribing to anything in your example.

**Comment by GitSage** [comment]
Yep, you've linked the wrong stackblitz. You got the first stackblitz from [material.angular.io's official `mat-select` documentation. ](https://material.angular.io/components/select/overview) 

[Here](https://stackblitz.com/edit/angular-yfhhjl?file=app/select-overview-example.html) is a working example using optionSelectionChanges.

However I suspect that what you really want is `selectionChange`. [Here](https://stackoverflow.com/questions/47568626/how-do-i-create-a-callback-on-material-angular-select?rq=1) is an example from StackOverflow:

```
 <mat-form-field>
      <mat-select [(value)]="selected" [formControl]="pc" panelClass="example-panel-{{pc.value}}" (selectionChange)="doSomething($event)">
        <mat-option *ngFor="let panelColor of panelColors" [value]="panelColor.value">
          {{ panelColor.viewValue }}
        </mat-option>
      </mat-select>
    </mat-form-field>
```

**Comment by odahcam** [comment]
Damn! I lost my example. However `selectionChange` works very well, but it's not in the docs.

**Comment by crisbeto** [comment]
`optionSelectionChange` won't work through a template binding (e.g. `(optionSelectionChange)`), because it's not marked as an `Output`.

**Comment by odahcam** [comment]
You're right.

**Comment by GitSage** [comment]
`selectionChange` is in the docs. It's in the API section.
