### ISSUE TITLE
MatPaginator is displaying on main page not in the popup.

### ISSUE THREAD

**Issue by EagleShrikant** [angular/material2#12833]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Dropdown for pagination must open in modal i.e. Pop-up..

#### What is the current behavior?
Dropdown is opening in main page

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: 
https://angular-6-custom-modal-dialog-mgp7e6.stackblitz.io/

1] Go to Link 
2] Click on table.
3] In pop click on paginator. drop down will open in main page not in pop-up
4] after closing popup, you will see drop-down in main page at bottom.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6

**Comment by crisbeto** [comment]
That's what this warning in the console is telling you:

> Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming

You haven't included Material's structural styling, which means that the element won't be positioned correctly. You can read more about it in the getting started guide: https://material.angular.io/guide/getting-started#step-4-include-a-theme

**Comment by EagleShrikant** [comment]
You are correct. Issue is resolved after adding styling. Thank you.
