### ISSUE TITLE
<mat-icon> some icons do not show (e.g. cellular bars)

### ISSUE THREAD

**Issue by RANSoftRA** [angular/material2#12846]
#### Bug, feature request, or proposal:
Using the <mat-icon> component some icons are not being displayed

`<mat-icon>signal_cellular_2_bar</mat-icon>`

#### What is the expected behavior?
Icon should be displayed

#### What is the current behavior?
The icon does not show

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-t4adjm?file=app%2Fapp.component.html

#### What is the use-case or motivation for changing an existing behavior?
Users expect that all icons in https://material.io/tools/icons/ are supported.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular-CLI: 6.1.4
Material: 6.4.6 (installed via ng add @angular/material)
OS: Windows 10
TypeScript: 2.7.2
Browsers: Chrome v68

**Comment by jelbourn** [comment]
`<mat-icon>` provides a way to show icons, but don't include any icons itself; that particular icon is probably in some variant or extended version of the Material Design icon font (I don't actually know myself).

**Comment by RANSoftRA** [comment]
OK, just found out that the iconfonts have not been updated for a while.

Issue https://github.com/google/material-design-icons/issues/786
