### ISSUE TITLE
Module build failed: Unclosed quote

### ISSUE THREAD

**Issue by krunalsheth3** [angular/material2#12844]
#### Bug, feature request, or proposal:
[webpack][error] Module build failed: Unclosed quote (3803:24)

  3801 | 
  3802 |   // Wrapper element that provides the theme background when the
> 3803 |   // user's content isn't inside of a `mat-sidenav-container`.
       |                        ^

#### What is the expected behavior?
Fix the extra 'quote'

#### What is the current behavior?
webpack build fails

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
Building angular material 5 with webpack where it fails to build while installing a custom angular material theme.
By doing @import '~@angular/material/theming';

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version 5, Material design - 5

**Comment by jelbourn** [comment]
@krunalsheth3 there's not enough information here for any kind of answer. If you can point to any reproduction or code snippet feel free to open a new issue.
