### ISSUE TITLE
wrong font-family in some elements

### ISSUE THREAD

**Issue by yinonov** [angular/material2#12841]
style bug in @angular/material": "^6.4.6" theme - 

all typography should inherit the same font family declared in mat-typography-config

but some elements have their own font-family style - 
.mat-button-toggle, .mat-card {
    font-family: Roboto,"Helvetica Neue",sans-serif;
}

**Comment by aloketewary** [comment]
![image](https://user-images.githubusercontent.com/3107840/44630076-e864fb80-a975-11e8-8755-f7b3aa304d03.png)
Here it is...

**Comment by jelbourn** [comment]
Each component can be configured individually through the typography API: https://material.angular.io/guide/typography

**Comment by yinonov** [comment]
the issue occurred because of including mat-core followed by mat-base-typography individually which resulted in a duplication of some typography style. I would still like to leave out the typography mixin to be included separately and not within the mat-core

**Comment by jelbourn** [comment]
That would unfortunately be a breaking change; anyone who doesn't include that mixin would stop getting the default typography styles.

**Comment by yinonov** [comment]
that's true @jelbourn. but perhaps in the future you could consider optional @include of a minimal theme
