### ISSUE TITLE
mat-form-field Labels don't display when Printing

### ISSUE THREAD

**Issue by andyrue** [angular/material2#12861]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When you print a mat-form-field, I expect the input label to also be printed.

#### What is the current behavior?
Printing a page with a mat-form-field and a nested matInput does not display the input label. 

#### What are the steps to reproduce?
You can view this problem on the Angular Material example page for Inputs. Try to print it and you will see the labels are missing. (in Chrome anyway)
https://material.angular.io/components/input/examples

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
OS: Mac OS X 10.13.6
Material 6.4.6
It prints in Firefox, but does not print in Chrome. Safari doesn't seem to render anything.

**Comment by Polyterative** [comment]
Same here

**Comment by bheidary** [comment]
fghfghfg
