### ISSUE TITLE
Sidenav does not work with mat-dialog-content

### ISSUE THREAD

**Issue by kakins** [angular/material2#12868]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I place a sidenav inside `mat-dialog-content`, scrollable content should behave as if I placed it anywhere else.

#### What is the current behavior?
Currently if the `mat-sidenav-content` causes the dialog to overflow/scroll, a weird whitespace begins to take over the entire `mat-dialog-content` view

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-dialog-sidenav-whitespace

#### What is the use-case or motivation for changing an existing behavior?
I want to have a sidenav placed inside a dialog.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I've only tried this on Angular 6.

**Comment by jelbourn** [comment]
You should try `mat-drawer`; `mat-sidenav` is intended for top-level application navigation. Closing this for now, feel free to re-open if problems persist with `mat-drawer`.

**Comment by kakins** [comment]
I would like to re-open this issue.  I switched the components to use `mat-drawer` and still experience the same behavior.
