### ISSUE TITLE
Angular Material Charts

### ISSUE THREAD

**Issue by Flo12345** [angular/material2#12867]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Multiple charts out of the box as Angular Material Components.

#### What is the current behavior?
none

#### What is the use-case or motivation for changing an existing behavior?
Charts, which can be used in the Angular Material environment (theming, typography, etc.)

#### Is there anything else we should know?
Is there any plan to providing chart components out of the box in Angular Material? If not, what alternatives can best be used?

**Comment by jelbourn** [comment]
This is something we'd like to do someday, but don't have any immediately plans for.
