### ISSUE TITLE
Schematics updates for v7

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#12875]
- [ ] Add prompts for `ng add` (custom theme, all components theme vs. specific components, animations, gestures, etc.)
- [x] Separate v5 -> v6 changes from v6 -> v7 changes
- [x] Ensure that all breaking changes and deprecations in v7 are captured by schematics
- [x] Improve constructor signature rule (many instances with lot of constructor changes)

**Comment by Splaktar** [comment]
Prompts exist in 7.0.0-beta.2 for prebuilt vs custom theme and gestures. Animations and specific component theming aren't in there yet.

**Comment by DevVersion** [comment]
The changes have been made.
