### ISSUE TITLE
Date picker required and parsing validation error muddling

### ISSUE THREAD

**Issue by bordecal** [angular/material2#12874]
#### Bug, feature request, or proposal:

Date picker validation errors are unreliable when required validation is mixed with unparseable dates.  Problems observed include the following when a date picker-linked input is bound to a `FormControl`:

- It is possible for both a required and a parsing error to be simultaneously present on the FormControl.
- Validation is not triggered on all updates of the the input (possibly because of the event suppression that occurs in `MatDatepickerInput<D>._onInput` when the old and new dates both evaluate to null after attempted parsing)

#### What is the expected behavior?

- A required validation error should be indicated only when the input is empty (or possibly pure whitespace).
- A parsing error should be indicated only when a non-empty input cannot be parsed to a valid date.
- It should not be possible for both a required and a parsing error to be indicated simultaneously.
- Validation should be triggered even when the input is changed from one invalid value to another.

#### What is the current behavior?

See above.

#### What are the steps to reproduce?

Using the StackBlitz sample at https://stackblitz.com/edit/angular-material2-issue-xukwtg:

1. Select a date using the calendar.
 - Expected error: none
 - Actual error: none
2. Delete the date.
 - Expected error: required
 - Actual error: required
3. Type an alphabetic string in the input (e.g.: foo).
 - Expected error: parsing
 - Actual error: **required**
4. Select a date using the calendar.
 - Expected error: none
 - Actual error: none
5. Add an alphabetic character to the end of the date (resulting in a string like "8/24/2018b").
 - Expected error: parsing
 - Actual error: **required and parsing**
6. Delete the date.
 - Expected error: required
 - Actual error: **required and parsing (for the pre-deletion text)**
7. Select a date using the calendar.
 - Expected error: none
 - Actual error: none
8. Delete the date.
 - Expected error: required
 - Actual error: required
9. Type a few digits, followed by a few alphabetic characters (e.g.: 854efd).
 - Expected error: parsing (for whole text)
 - Actual error: **required and parsing (only for text up to first alphabetic character, e.g.: 854e)**

#### What is the use-case or motivation for changing an existing behavior?

Allow a meaningful error message to be displayed to the user based on the specific validation problem that is present in their entered data

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/material 6.4.6

#### Is there anything else we should know?

The same problem occurs if a `required` attribute is applied to the HTML input instead of applying the validator to the `FormControl`.

**Comment by ampled** [comment]
Any usage of formControl#setValidators overrides the parsing validator when trying to use reactive forms with the datepicker as it exists now, and since the date adapter only returns null or a date object it makes it impossible to use custom validators on user input when the field isn't required.

**Comment by mmalerba** [comment]
If you update the dependencies you will see that the behavior is now a little more consistent: https://stackblitz.com/edit/angular-material2-issue-kcvkpc?file=app/app.component.ts

It mostly works like you're describing above, except whenever there's a parse error you're also going to get a required error. This is because if the date can't be parsed it is treated as null. In your UI you may wish to condition the required error message on there not being a parse error message, but this is WAI
