### ISSUE TITLE
Ng-serve can't find the module!

### ISSUE THREAD

**Issue by psks1204** [angular/material2#1287]
I've been trying to figure it out! I've installed all angular2-material many times using NPM but still it can't find the modules.. please someone fix this!

     Asset     Size  Chunks             Chunk Names
  main.bundle.js  3.17 MB    0, 2  [emitted]  main
styles.bundle.js  10.2 kB    1, 2             styles
       inline.js  5.53 kB       2             inline
      styles.map  14.1 kB    1, 2             styles
      inline.map  5.59 kB       2             inline
        main.map  3.25 MB    0, 2  [emitted]  main

WARNING in ./src/app/app.component.ts
50:16 export 'MD_SIDENAV_DIRECTIVES' was not found in '@angular2-material/sidena
v'

WARNING in ./src/app/app.component.ts
51:16 export 'MD_LIST_DIRECTIVES' was not found in '@angular2-material/list'

WARNING in ./src/app/app.component.ts
52:16 export 'MD_CARD_DIRECTIVES' was not found in '@angular2-material/card'

WARNING in ./src/app/app.component.ts
53:16 export 'MD_TOOLBAR_DIRECTIVES' was not found in '@angular2-material/toolba
r'

ERROR in [default] C:\Users\piyushk\Desktop\first-app\node_modules\@angular2-mat
erial\core\gestures\MdGestureConfig.d.ts:4:39
Cannot find name 'HammerManager'.

ERROR in [default] C:\Users\piyushk\Desktop\first-app\src\app\app.component.ts:2
:8
Module '"C:/Users/piyushk/Desktop/first-app/node_modules/@angular2-material/tool
bar/index"' has no exported member 'MD_TOOLBAR_DIRECTIVES'.

ERROR in [default] C:\Users\piyushk\Desktop\first-app\src\app\app.component.ts:4
:8
Module '"C:/Users/piyushk/Desktop/first-app/node_modules/@angular2-material/side
nav/index"' has no exported member 'MD_SIDENAV_DIRECTIVES'.

ERROR in [default] C:\Users\piyushk\Desktop\first-app\src\app\app.component.ts:5
:8
Module '"C:/Users/piyushk/Desktop/first-app/node_modules/@angular2-material/list
/index"' has no exported member 'MD_LIST_DIRECTIVES'.

ERROR in [default] C:\Users\piyushk\Desktop\first-app\src\app\app.component.ts:6
:8
Module '"C:/Users/piyushk/Desktop/first-app/node_modules/@angular2-material/card
/index"' has no exported member 'MD_CARD_DIRECTIVES'.

ERROR in [default] C:\Users\piyushk\Desktop\first-app\src\app\app.component.ts:9
:8
Module '"C:/Users/piyushk/Desktop/first-app/node_modules/@angular2-material/radi
o/index"' has no exported member 'MD_RADIO_DIRECTIVE'.

ERROR in [default] C:\Users\piyushk\Desktop\first-app\src\app\app.component.ts:1
7:2
Argument of type '{ moduleId: string; selector: string; template: any; styles: a
ny[]; directives: any[]; providers:...' is not assignable to parameter of type '
Component'.
  Object literal may only specify known properties, and 'directives' does not ex
ist in type 'Component'.

ERROR in [default] C:\Users\piyushk\Desktop\first-app\src\app\app.component.ts:2
5:4
Cannot find name 'MD_PROGRESS_CIRCLE_DIRECTIVES'.

ERROR in [default] C:\Users\piyushk\Desktop\first-app\src\app\app.component.ts:2
8:30
Cannot find name 'MdRadioDispatcher'.
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.81 kB       0
webpack: bundle is now VALID.

**Comment by jelbourn** [comment]
It looks like you're attempting to use a later version of Material with an old API. See the changelog and the getting started guide.

**Comment by psks1204** [comment]
Hey, Jelbourn. thanks for replying.
but i just installed angular2-material the latest version still these errors are showing up.. 
i really need to fix this

**Comment by psks1204** [comment]
ujj

**Comment by JigyasaSharma** [comment]
Hi, 
Were you able to solve this?

**Comment by psks1204** [comment]
yeah! @JigyasaSharma  I've solved it.

**Comment by abhishekit29** [comment]
@psks1204  what version of angular/material are you using ?

**Comment by psks1204** [comment]
@abhishekit29 I'm using the latest version of it and I've sorted this problem! Thank you.
