### ISSUE TITLE
Cannot find module @angular/material-moment-adapter

### ISSUE THREAD

**Issue by Hypenate** [angular/material2#12887]
#### Bug:
An error is thrown on this line:
`import {MAT_MOMENT_DATE_FORMATS, MomentDateAdapter} from '@angular/material-moment-adapter';`

The error is:
> Cannot find module '@angular/material-moment-adapter';'

#### What is the expected behavior?
The module is found

#### What is the current behavior?
The module is not found

#### What are the steps to reproduce?
[StackBlitz example for the website](https://stackblitz.com/angular/lmmgngloedgl?file=app%2Fdatepicker-moment-example.ts)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.0.7
angular/material: 6.4.2
Typescript: 3.0.1
#### Is there anything else we should know?
Another question, where is `MatMomentDateModule `located?

**Comment by rsaenen** [comment]
`npm i @angular/material-moment-adapter`

```typescript
import { MatMomentDateModule, MomentDateAdapter } from "@angular/material-moment-adapter";
```

I'm sorry but I guess StackOverflow is better for questions...

**Comment by kanadChourasia** [comment]
And we also need to install moment
`npm install moment --save`
