### ISSUE TITLE
material-table schematics not respecting angular.json settings

### ISSUE THREAD

**Issue by mackelito** [angular/material2#12881]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Component should be created with the correct file extension

#### What is the current behavior?
.css is used

#### What are the steps to reproduce?
ng g @angular/material:material-table --name customerList --dry-run
````
CREATE src/app/customers/components/customer-list/customer-list-datasource.ts (3405 bytes)
CREATE src/app/customers/components/customer-list/customer-list.component.css (0 bytes)
CREATE src/app/customers/components/customer-list/customer-list.component.html (857 bytes)
CREATE src/app/customers/components/customer-list/customer-list.component.spec.ts (654 bytes)
CREATE src/app/customers/components/customer-list/customer-list.component.ts (747 bytes)
UPDATE src/app/customers/customers.module.ts (687 bytes)
````

#### What is the use-case or motivation for changing an existing behavior?
Use-case: Make developers more effeciant

#### Is there anything else we should know?
in angular.json
````
    "@schematics/angular:component": {
      "styleext": "scss"
    }
````
Running ng g c test will give a component with correct extension

**Comment by DevVersion** [comment]
Thanks for your issue. The style extension will be respected in the next major version. See: https://github.com/angular/material2/commit/5144aa790dfad54c1340a0e16435ca3f5253b16e
