### ISSUE TITLE
bug: MatStepperIntl custom implementation not injected

### ISSUE THREAD

**Issue by fmavdb** [angular/material2#12904]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Inject the custom provided `CustomMatStepperIntl` 

#### What is the current behavior?
The default `MatStepperIntl` is used

#### What are the steps to reproduce?

1. Provide `CustomMatStepperIntl` in app.module.ts
`    {
      provide: MatStepperIntl,
      useClass: CustomMatStepperIntl
    }
`
2. Make a lazy loaded module that imports `MatStepperModule`
3. The default `MatStepperIntl` is injected instead (in the lazy loaded module)

#### What is the use-case or motivation for changing an existing behavior?
I want to translate specific labels for the stepper component as per global level and not by lazy loaded module level. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.4
Material 6.4.6

#### Is there anything else we should know?
The `MatPaginatorIntl` works as expected... Why should `MatStepperIntl` work different?

**Comment by crisbeto** [comment]
What does your `CustomMatStepperIntl` look like?

**Comment by fmavdb** [comment]
Example:
`@Injectable()
export class CustomMatStepperIntl extends MatStepperIntl implements OnDestroy {
  private onLangChange: Subscription;

  constructor(private translate: TranslateService) {
    super();

    this.onLangChange = this.translate.onLangChange.subscribe((e: LangChangeEvent) => {
      this.Init();
    });

    this.Init();
  }

  private async Init() {
    this.optionalLabel = await this.translate.get("Optional").toPromise();
    this.changes.next();
  }

  ngOnDestroy(): void {
    this.onLangChange.unsubscribe();
  }
}`

**Comment by crisbeto** [comment]
Can you set the injectable to be provided at the root and seeing if it helps? e.g. `@Injectable({providedIn: 'root'})`

**Comment by fmavdb** [comment]
I tried adding `@Injectable({providedIn: 'root'})` but it doesn't seem to be making any difference.

If you look at the `MatPaginatorModule` that provides `MatPaginatorIntl` and `MatStepperModule` that provides `MatStepperIntl`, you'll see that the implementation of providing them are different. The `MatPaginatorModule` / `MatPaginatorIntl` seem to be using a factory.
