### ISSUE TITLE
material.angular.io site returns error - cannot load it

### ISSUE THREAD

**Issue by davidbarrows** [angular/material2#12903]
#### Bug, feature request, or proposal:

ngswworker.js returns an error.  I cannot load the documentation site.

#### What is the expected behavior?

site should load.

#### What is the current behavior?

A bad HTTP response code (404) was received when fetching the script.
Failed to load resource: net::ERR_INVALID_RESPONSE
The FetchEvent for "https://material.angular.io/" resulted in a network error response: the promise was rejected.
Promise.catch (async)
onFetch @ ngsw-worker.js:1896
constructor.scope.addEventListener @ ngsw-worker.js:1844
ngsw-worker.js:576 Uncaught (in promise) Error: Response not Ok (fetchAndCacheOnce): request for https://material.angular.io/index.html returned response 301 
    at PrefetchAssetGroup.<anonymous> (ngsw-worker.js:576)
    at Generator.next (<anonymous>)
    at fulfilled (ngsw-worker.js:304)
(anonymous) @ ngsw-worker.js:576
fulfilled @ ngsw-worker.js:304
A bad HTTP response code (404) was received when fetching the script.
Failed to load resource: net::ERR_INVALID_RESPONSE

![material angular io returns error](https://user-images.githubusercontent.com/7458428/44849846-4e41d380-ac53-11e8-843e-90acc12e206a.JPG)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

This is on a Windows 10 machine with Chrome:
Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by jelbourn** [comment]
Visit chrome://serviceworker-internals/ and unregister the worker for material.angular.io. This will clear the service worker cache, which persists through hard refresh.

**Comment by davidbarrows** [comment]
That worked.  Thanks for your help.
