### ISSUE TITLE
mattooltip and mobile devices

### ISSUE THREAD

**Issue by twoheaded** [angular/material2#12917]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?

Tooltip  on high pages must be shown on mobile devices

#### What is the current behavior?

Tooltip isn't shown

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-9hcbcn

Open in new window, toggle device toolbar, scroll down to the Action button. Press button. There is no tooltip on click/longpress. 

Can check this link https://angular-9hcbcn.stackblitz.io/ on your device.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Chrome, Android

**Comment by jelbourn** [comment]
I can confirm that tooltips are showing up on my own Android device.
