### ISSUE TITLE
 Include properties type is incorrect for custom form field control

### ISSUE THREAD

**Issue by Freest10** [angular/material2#12923]
Hello, in the documentation for a custom form field control (https://material.angular.io/guide/creating-a-custom-form-field-control), we can take a property as a string (when required = "true") and as boolean, the type of input value for the setter is boolean. You convert value from string to boolean when it string by method coerceBooleanProperty, but include property value is boolean type. it's not right and it's not obvious. It is mean required could be type boolean | string.
```
get required(): boolean { return this._required; }
set required(value: boolean) {
  this._required = coerceBooleanProperty(value);
   this.stateChanges.next();
}
```

The same problem with disabled.
I think you need a required property interceptor that converts a property from a string to a boolean and returns a value to the required setter with the type boolean.

**Comment by jelbourn** [comment]
This is working as intended. It's designed this way to align with the native behavior of boolean attributes such as `disabled` and `checked`. If you write `<mat-checkbox disabled>`, the component should be disabled.

**Comment by Freest10** [comment]
I understand why this is necessary, I wrote that in the setter there is a parameter with a type of boolean, and there comes a boolean or a string for compatibility with httml attributes.

**Comment by jelbourn** [comment]
As far as users are concerned, the type _is_ boolean. The only time a string is passed in should be by the Angular framework, which doesn't know about the type.

**Comment by Freest10** [comment]
You say that the param type (value) is boolean, but in fact a boolean and a string come. and then you do the convertation in case of a string parameter inside function, although you write that param type only boolean.
Bypass typescript is not correct. it must be a mistake in the java.
