### ISSUE TITLE
Disable drag & drop on selected elements

### ISSUE THREAD

**Issue by Enngage** [angular/material2#12929]
#### Feature / question

Version: `7.0.0-beta.0`

I have edit/delete buttons in my drag & drop list and I need a way of telling angular material to **not** handle dragging on these elements. Is there a way of accomplishing this?

As a workaround I have a 'switch' which specifically enables drag & drop functionality, but its not exactly user friendly. 

Thank you!

**Comment by crisbeto** [comment]
You can use the cdkDragHandle directive to configure which element should be draggable.

**Comment by Enngage** [comment]
Yeah, I was thinking of using this, but in this case I need to exclude the buttons from the handle and the drag will not cover full size of the item. It would be really cool to excluding items from dragging as depending on your particular layout using handle might not be the ideal solution.

**Comment by crisbeto** [comment]
I see what you mean, but we try to avoid having multiple ways of doing more or less the same thing, if we can. Would something like this cover your case?

```
.drag-item {
  position: relative;
}

.drag-handle {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 0;
}

.edit-icons {
 position: relative;
 z-index: 1;
}
```

**Comment by Enngage** [comment]
Yeah, I think this should do fine. Thank you!

**Comment by crisbeto** [comment]
Closing the issue for now. It can be reopened if the solution doesn't work out.
