### ISSUE TITLE
Menu position going wrong on Scroll. Reappearance of #11365

### ISSUE THREAD

**Issue by Stexxen** [angular/material2#12937]
#### Bug, feature request, or proposal:
Bug, Reappearance of #11365

#### What is the expected behavior?
Menu should not move

#### What is the current behavior?
It scrolls down and potentially changes shape.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-oy329b-n7au1b
Forked from Angular Docs

Click 'Animal Index' While menu is open scroll window.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.4.7,
Angular 6.1.6

Tested on 
Chrome 68, 71
Firefox 52, 61
Safari 11, 12
Opera 55
all on MacOS 10.13

![image](https://media.giphy.com/media/1oD5H2iGM3iJ4fZzEK/giphy.gif)

**Comment by crisbeto** [comment]
I'm not getting this on the demo app running against master. Maybe the fix didn't get released? cc @jelbourn

**Comment by Stexxen** [comment]
You could be right, I assumed that as the merge was prior to the release of 6.4.7 It would've been included. But now i'm not so sure....

**Comment by Stexxen** [comment]
Have confirmed. Your fix is included in 7 Beta.0 but not in 6.4.7.
Am closing, sorry for the confusion.

**Comment by gpessa** [comment]
This is still there in 6.4.7

**Comment by crisbeto** [comment]
This is fixed in 7.0.0.

**Comment by gpessa** [comment]
7 is a beta and maybe we cant update to it

**Comment by Stexxen** [comment]
@gpessa The particular fix that @crisbeto submitted has not been cherrypicked back to the [6.4.x branch](https://github.com/angular/material2/commits/6.4.x). So I think it unlikely that 6.4.8 will have it either.

I don't know why this is; it may rely on other patches that cannot be back-ported.
