### ISSUE TITLE
Feature request: adding the ability to configure the cdk overlay container insertion point

### ISSUE THREAD

**Issue by Harpush** [angular/material2#12930]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
An option to create the overlay container in another element and not only in body (maybe as part of the OverlayConfig?)

#### What is the current behavior?
The create method always create the container in the body.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
n/a

#### What is the use-case or motivation for changing an existing behavior?
In most cases like modals - creating the overlay container in the body level is sufficient. But if i want to create the overlay in order to hide a div with a loading animation and a semi tranparent backdrop i cant achieve it with the current overlay. On the other hand if i could configure it to be placed in the div - the overlay would hide only the div.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
It is now achievable through some "hack" as explained in [this article](https://medium.com/@manojvignesh/content-specific-progress-loading-indicator-using-cdk-overlay-207d14b603b5). 
Looking at the implementation - it doesn't seem like a tough solution to implement.

**Comment by crisbeto** [comment]
This is possible already by providing a new value for the `OverlayContainer` token.

**Comment by Harpush** [comment]
That's if it's a static element... but what about a dynamic element? Or am i missing the point?

**Comment by crisbeto** [comment]
The point of the overlay container is that it's a single point of managing the stacking of overlays and their `z-index`. Having multiple doesn't make sense, because we wouldn't be able to stack them correctly.

**Comment by Harpush** [comment]
So how can one position it to cover a specific element? Including backdrop

**Comment by Harpush** [comment]
I mean the example i gave concerning the loading cover on a specific element. I can achieve this with FlexibleConnectedPositionStrategy but the backdrop still covers the whole screen.

**Comment by crisbeto** [comment]
Cases like that would be easier to do with a regular element that's `position: absolute`.
