### ISSUE TITLE
Virtual scroll start on bottom

### ISSUE THREAD

**Issue by buu700** [angular/material2#12932]
It'd be very useful (an unblocker for my use case) if the CDK virtual scroller supported an option to start off scrolled to the bottom instead of the top.

With non-virtual scrolling there are plenty of workarounds to achieve something to this effect, but with virtual scrolling (and `autosize`) I can't see an obvious way to accomplish it.

**Comment by buu700** [comment]
Ah wait, if I'm understanding #10116 correctly, it sounds like that will address this?

If so, I'll go ahead and close this and subscribe to that.

**Comment by mmalerba** [comment]
Yes, `scrollToIndex` is currently implemented for fixed size virtual scroll, but not yet for autosize. #10116 is left open to track implementing it for autosize

**Comment by buu700** [comment]
Got it, thanks!

**Comment by buu700** [comment]
I'm still waiting on #10116 for a cleaner solution, but this is what I ended up doing for now:

```
@ViewChild(CdkVirtualScrollViewport) public virtualScrollViewport?: CdkVirtualScrollViewport;

. . .

this.virtualScrollViewport.scrollTo({bottom: 0});
```

**Comment by derSoerrn95** [comment]
> I'm still waiting on #10116 for a cleaner solution, but this is what I ended up doing for now:
> 
> ```
> @ViewChild(CdkVirtualScrollViewport)
> public virtualScrollViewport?: CdkVirtualScrollViewport;
> 
> . . .
> 
> this.virtualScrollViewport.scrollTo({bottom: 0});
> ```

hey, sorry - but i don't get it. I wrote something like that:

```
this.messages$ = merge(this.messageReceiving$, this.messagesLoading$)
      .pipe(
        map((scrolledUp: boolean) => {
          if (!scrolledUp) {
            this.scrollDown = true;
          }
          return this.currentChat.messages;
        }),
        share()
      );

ngAfterViewChecked() {
    if (this.scrollDown === true) {
      this.messageList.scrollTo({ bottom: 0, behavior: 'auto' });
      this.scrollDown = false;
    }
}
```
But this doesn't really run well. How did u handle that @buu700?

**Comment by buu700** [comment]
Well, I'm pretty sure that worked out the time I wrote the comment, but at
some point it stopped the working and we actually ended up just disabling
virtual scrolling for now due to that and various small bugs that made it
unusable :/.

**Comment by derSoerrn95** [comment]
ok, thanks for reply. I also stopped using virtual scrolling for that usecase.

**Comment by Stradivario** [comment]
@buu700 basically we need to stop using virtual scroll provided inside the documentation ? Is that what you say ?
