### ISSUE TITLE
Mat-dialog-actions not at the bottom

### ISSUE THREAD

**Issue by vinagreti** [angular/material2#12949]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Actions to be at the bottom of the dialog

#### What is the current behavior?
Actions right after content

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/edit/angular-cuikyx<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular@6.1.6, material@6.4.7, any browser and any OS

**Comment by josephperrott** [comment]
Closing as duplicate of #4609
