### ISSUE TITLE
bug:(@angular/cdk/drag-drop): inconsistent transfer between cdk-drop

### ISSUE THREAD

**Issue by AhsanAyaz** [angular/material2#12944]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The dragged item should be transferrable between connected drop-zones (`cdk-drop`) but they have some inconsitent behavior. I've shared a stackblitz link below. When you open it:

- Notice that `Drag Me 1` div can be transferred to `Zone2` but then cannot be transferred back to Zone1. 
- Notice that `Drag Me 2` can be dragged to `Zone1` and a preview is shown, but cannot be dropped actually.

#### What is the current behavior?
The item is transferred from zone1 to zone2 but I can not transfer it back to zone1 although they are connected zones. Please correct me if this isn't an appropriate use case :)

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/edit/cdk-drag-drop-issue

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`@angular/cdk@7.0.0-beta.0`

#### Image

![large gif 566x666](https://user-images.githubusercontent.com/9844254/44950185-32545280-ae4a-11e8-8f43-c78ddc7d3257.gif)

**Comment by junraemon** [comment]
Check Netanel Basal's article, there is an example on how to connect 2 drop zones.
https://netbasal.com/getting-to-know-the-angular-cdk-drag-and-drop-feature-d79ba462ce31

**Comment by AhsanAyaz** [comment]
Thanks @crisbeto for the fix and PR. 👍 
I was writing my own article on the CDK when I felt the need to use two drop-zones. Thanks for sharing the above article though!
