### ISSUE TITLE
Expansion Panels - are they planned?

### ISSUE THREAD

**Issue by dsmeltz** [angular/material2#1295]
#### Feature Request
Add Expansion Panels as per the Material spec

[Expansion Panel Spec](https://material.google.com/components/expansion-panels.html)

**Comment by KyleRayMorgan** [comment]
@dsmeltz your link is broken.

**Comment by dsmeltz** [comment]
Link has been updated.

**Comment by jelbourn** [comment]
Currently no plans for this one.

**Comment by richavyas** [comment]
Hi @dsmeltz, please check the expansion panel created by our team @teradata, https://teradata.github.io/covalent/#/components/expansion-panel
It is based on [material spec](https://material.google.com/components/expansion-panels.html)
