### ISSUE TITLE
bug(@angular/cdk/drag-drop) drag preview doesn't show until an action happens

### ISSUE THREAD

**Issue by AhsanAyaz** [angular/material2#12954]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Should show a preview of the dragged element

#### What is the current behavior?
Doesn't show the preview of the element while being dragged. Even on the demo site.

![large gif 480x454](https://user-images.githubusercontent.com/9844254/44961064-3b5d2680-af13-11e8-8bee-35ba7c5fa1f6.gif)

Notice that the preview shows as soon as the inspector is opened i.e. a browser event happens. Seems something to do with the Angular Change Detection or ZoneJS. Just throwing some ideas.

#### What are the steps to reproduce?
Just go to the [demo site](https://beta-angular-material-io.firebaseapp.com/cdk/drag-drop/examples), go to the drag preview example and drag an element. The preview isn't shown.

#### Is there anything else we should know?
Tested on Chrome
Version 68.0.3440.106 (Official Build) (64-bit)

@crisbeto

**Comment by crisbeto** [comment]
Thanks for the report. This will be resolved in https://github.com/angular/material2/pull/12921.

**Comment by AhsanAyaz** [comment]
You guys are awesome @crisbeto

**Comment by AbhijithSugunan** [comment]
Is this issue fixed in cdk 7.3.7 ? Because still am seeing it in cdk 7.3.7
