### ISSUE TITLE
Tooltip for badge possible?

### ISSUE THREAD

**Issue by b-mi** [angular/material2#12969]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Allow matTooltip for matBadge

#### What is the current behavior?
Unable to add matTooltip for matBadge

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Users request, need to better describe content of badge

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6, Material 6, Win 10, TS ~2, any browser

#### Is there anything else we should know?
No

**Comment by jelbourn** [comment]
This isn't something we plan to support, as both badge and tooltip are meant to decorate another element.

**Comment by andmekandja** [comment]
It would be nice to have a questionmar opportunity for tooltip then, so user would know he can get some additional info about element
