### ISSUE TITLE
input placeholder attribute with translate pipe ( 'HELLO' | translate ) and [matChipInput...] attributes does not update inside <mat-chip-list>

### ISSUE THREAD

**Issue by kaps727** [angular/material2#12963]
#### Bug, feature request, or proposal:
Bug/proposal

#### What is the expected behavior?

`  <mat-form-field>
    <mat-chip-list #chipList>
      <mat-chip *ngFor="let entry of dataSelected" [removable]="removable" > {{entry.displayName}}   </mat-chip>
      <input placeholder="{{ 'HELLO' | translate }}" [matChipInputFor]="chipList" [matChipInputSeparatorKeyCodes]="separatorKeysCodes"
        [matChipInputAddOnBlur]="addOnBlur" />
    </mat-chip-list>
  </mat-form-field>`

EXPECTED - 'HELLO' should be translated to 'Hello'

#### What is the current behavior?

 'HELLO' is shown as 'HELLO' for the first time when page is rendered.
when i click on input the placeholder floats with expected value 'Hello'.
Same issue occurs when i translate the language, Only this field doesn't translate as it is the only input tag i have inside mat-chip-list.

#### What are the steps to reproduce?

Working on it. I will update as soon as possible. Till then I have explained as much as I can.

#### What is the use-case or motivation for changing an existing behavior?

while using plugin "ngx-translate" npm package, we may come across situation that translations are provided with URL link / from another server. (as i came across such situation).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.0.9
Material: 6.0.0
OS: linux x64
Typescript: 2.7.2
Browsers: Chrome 68.0.3440.106 (Official Build) (64-bit),
                 Firefox 61.0.1 (64-bit),
                 Safari 11.1.2 (13608.3.8)

#### Is there anything else we should know?

I am using "ngx-translate" npm package with "HttpLoaderFactory" 
ngx-translate/core: 9.1.1
ngx-translate/http-loader: 3.0.1

All placeholder translations working fine, except the one which is inside mat-chip-list.
When i remove [matChipInputFor], [matChipInputSeparatorKeyCodes], [matChipInputAddOnBlur]
attributes the placeholder translation works fine.

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by josephperrott** [comment]
Closing as we are not be able to reproduce this issue.
