### ISSUE TITLE
Mat expansion panel disabled and expanded 

### ISSUE THREAD

**Issue by OvidijusStukas** [angular/material2#12962]
#### Bug, feature request, or proposal:
Hello, I was wondering if it's standard behaviour when expansion panel is disabled it also can be expanded. In the reproduction link you can see that it is disabled and also expanded.

#### What is the expected behavior?
I'm expecting that expansion panel would be closed even when expanded is set to true while expansion panel is disabled.

#### What are the steps to reproduce?
https://angular-material2-issue-dix4u1.stackblitz.io/

**Comment by crisbeto** [comment]
Yes, that's the expected behavior. `disabled` means that the user can't toggle the panel, but it can still be expanded and collapsed programmatically.

**Comment by OvidijusStukas** [comment]
Thanks @crisbeto for fast answer. I will close the ticket.
