### ISSUE TITLE
Mat-Datepicker this._overlay.position(...).flexibleConnectedTo(...).withTransformOriginOn is not a function

### ISSUE THREAD

**Issue by tombalcaen** [angular/material2#12961]
#### Bug, feature request, or proposal:

`<mat-form-field>
      <input formControlName="birthdate" #birthdate id="birthdate" matInput [matDatepicker]="picker3" placeholder="Birth date">
       <mat-datepicker-toggle matSuffix [for]="picker3"></mat-datepicker-toggle>
       <mat-datepicker #picker3></mat-datepicker>
 </mat-form-field> `

**When opening the calendar through the _mat-datepicker-toggle_, An error is reported in the console.**

![screen shot 2018-09-03 at 12 45 43](https://user-images.githubusercontent.com/29797792/44982984-e0a9e600-af77-11e8-9b32-797049d7856d.png)

"ERROR TypeError: this._overlay.position(...).flexibleConnectedTo(...).withTransformOriginOn is not a function"

#### What is the expected behavior?

I expect the calendar pop-up to be opened. 

#### What is the current behavior?

No calendar pop-up opens, in console there is a error report stating the following.

"ERROR TypeError: this._overlay.position(...).flexibleConnectedTo(...).withTransformOriginOn is not a function"

#### What are the steps to reproduce?

unable to reproduce

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

**dependencies**
    "@angular/animations": "^6.0.0",
    "@angular/cdk": "6.0.1",
    "@angular/cli": "^6.1.5",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/core": "^6.0.1",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/material": "^6.4.7",

**Comment by crisbeto** [comment]
You should update your version of `@angular/cdk` to match the version of `@angular/material`.
