### ISSUE TITLE
matMenu on other than button element don`t catch  SPACE key event

### ISSUE THREAD

**Issue by WandererInVoids** [angular/material2#12964]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
open menu

#### What is the current behavior?
menu not open on other element than button with keyboard

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-hbmxke-hamjhn?file=app/menu-icons-example.html
try tab from input than click SPACE menu not open
in another menu it open with SPACE

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.1.5
Node: 10.9.0
OS: win32 x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cdk                      6.4.7
@angular/cli                      6.1.5
@angular/material                 6.4.7
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.1
typescript                        2.9.2
webpack                           4.9.2

#### Is there anything else we should know?
no

**Comment by crisbeto** [comment]
That's because the menu trigger only listens for `click` events which also get fired for space and enter on `button` elements. I don't think it makes sense to add something that does the same for all other node types, because space might mean something completely different on another node. You can fix your case by using the proper element.
