### ISSUE TITLE
There is no ability to disable thumb gap when thumb is at the minumum state and focused (with custom styles)

### ISSUE THREAD

**Issue by sharikovvladislav** [angular/material2#12988]
#### Bug, feature request, or proposal:

I want to use material slider. I want to change the size of thumb. I need it like 13px radius. So I used transform: scale(0.7) to achieve this. I don't want changing of the size on focus (while component is active, when I drag it).

The problem is when thumb is at sliders min state then I see little gap between thumb and track background. 

<img width="286" alt="screen shot 2018-09-05 at 21 32 26" src="https://user-images.githubusercontent.com/5622526/45113501-37b7e280-b153-11e8-9011-2a2dc50a2a8d.png">

#### What is the expected behavior?

I want to disable this thumb gap by option or we don't need constants as thumb gaps. We can check actuall thumb size and use it. 

#### What is the current behavior?

I can not disable thumb gap at min state.

#### What are the steps to reproduce?

Here is the stackblitz example: https://stackblitz.com/edit/angular-material2-issue-dmwx9p

Press on the thumb 1 time. You will se the issue.

#### What is the use-case or motivation for changing an existing behavior?

More flexibility.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All.

**Comment by sharikovvladislav** [comment]
Options, how to handle this:

1. Styles:

```
:host .mat-slider-min-value ::ng-deep .mat-slider-track-background {
  transform: translateX(0px) scale3d(1, 1, 1) !important;
}
```

2. Define _thumbGap in the code

Do not do this :)

```
@ViewChild(MatSlider) matSlider: MatSlider;

ngAfterViewInit() {
  Object.defineProperty(this.matSlider, '_thumbGap', {
    get: () => 0
  });
}
```

**Comment by josephperrott** [comment]
Closing as you are be able to define the size by more specifically targeting the thumb element as seen in [this fork](https://stackblitz.com/edit/angular-material2-issue-wc8ysb?file=app/app.component.html) of your repro

Specifically this css added globally
```css
div.mat-slider-thumb {
  height: 26px;
  width: 26px;
  right: -13px;
  bottom: -13px;
  transform: scale(1);
}
```
