### ISSUE TITLE
plugin in background-image v4

### ISSUE THREAD

**Issue by SmallProgramIndustry** [angular/material2#12998]
#### Bug, feature request, or proposal:

The ionic plug-in doesn't work
background-image: url('../assets/image/xxxx.png') The alarm

#### What is the expected behavior?

ionic v3  app.module.ts => providers in statement
ionic v4  The documentation is also an introduction 
app.module.ts => providers in statement
However, an error was reported in the process used.

-  plugin Object(...) is not a function

ionic v3 background-image: url('../assets/image/xxxx.png') 
ionic v4 background-image: url('../assets/image/xxxx.png')  error

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Is there anything else we should know?

I should have made a mistake in one step. Please tell me how to solve it

**Comment by DevVersion** [comment]
Hey @SmallProgramIndustry, this is not the ionic project. You should consider asking your question on StackOverflow or report an issue on the ionic repository.
