### ISSUE TITLE
You can do with him ?

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/material2#13]
this man ,https://github.com/justindujardin/ng2-material/

Cooperation
Invite him

thank you very much :)

**Comment by leshin** [comment]
+1

**Comment by FoxelFox** [comment]
+1

**Comment by webknjaz** [comment]
+1
@justindujardin

**Comment by mikeandersun** [comment]
+1

**Comment by jelbourn** [comment]
That repo simply mirrored the code that I had previously written [in the angular/angular repo](https://github.com/angular/angular/tree/master/modules/angular2_material). We will be moving it ourselves over the next few weeks (a lot of tests and benchmarks are needed). 

Please keep github issues strictly for bugs, feature requests, etc. Discussion can go on [our Google Group](https://groups.google.com/forum/#!forum/angular-material2).

**Comment by justindujardin** [comment]
@jelbourn I'm excited to hear that an official material components implementation is finally in the works!  I look forward to learning about angular2 best practices through your examples.

That being said, I think your characterization of what I've done in ng2-material is a little unfair. You're correct that I started from your work in the official repo, but it wasn't very usable at that time. I've added considerable testing, new components, visual consistency across browsers, etc. I'm sure you'll address all of these things and more, but it's not fair to dismiss my work as merely a mirror of what you produced.

If you'd prefer not to collaborate, though, I'm okay de-conflicting the `md` prefix by changing my implementation.

**Comment by jelbourn** [comment]
@justindujardin Oh, my apologies. I just did a quick glace at the repo and saw the code from angular/angular and assumed it was just a mirror. We're happy to have community contributions! We should have our CI infrastructure set up soon. If you want to contribute something once that's done, feel free to open an issue with your plans so that the team can discuss it (as described in our [contributing guide](https://github.com/angular/material2/blob/master/CONTRIBUTING.md)). Thanks for clearing that up!

**Comment by iloveyo123u1** [comment]
+1
@justindujardin

**Comment by leshin** [comment]
+1
@justindujardin

**Comment by dlebedynskyi** [comment]
+1 
@justindujardin. 
This guy at very least added something usable for material design with angular 2 in place of void.

**Comment by shprink** [comment]
Can I help in some way?

**Comment by zoechi** [comment]
@shprink #11

**Comment by no-more** [comment]
Yes it would be great if you could work together, ng2-material has already a lot of feature and md-material seems to grow very VERY slowly.

I really like material design (using it on angular1 for one year already) I want to use it on a new project which is starting soon on angular2.

Thanks.
