### ISSUE TITLE
Unable to use  mat-elevation-z8 on mat-card

### ISSUE THREAD

**Issue by sidsaxena0** [angular/material2#13003]
Hi, i am trying to set mat-card elevation to z8 and i am trying the same but instead of increasing elevation it is making elevation gone. It is happening as soon as i apply any mat-elevation-z with any z value it is just making it plane without any shadows.  I am using angular 6.  Please help me with it as i have tried many things but it just not working.

**Comment by benelliott** [comment]
You should be able to do this by applying the `mat-elevation-z8` class to the card.

**Comment by sidsaxena0** [comment]
Yes i am doing the same e.g     <mat-card class="mat-elevation-8"> but it won't work.

**Comment by sidsaxena0** [comment]
Yes i am doing the same but it won't work. I have below code : 

`    <mat-card class="mat-elevation-8">
`

**Comment by benelliott** [comment]
Make sure you have included a theme as per https://material.angular.io/guide/getting-started#step-4-include-a-theme

**Comment by sidsaxena0** [comment]
ok got it now, so you mean default elevation works without theme import but to customize we need to import it?

**Comment by sidsaxena0** [comment]
Thanks for your help. It is working now just after importing the theme by `@import "~@angular/material/prebuilt-themes/indigo-pink.css";` so i am closing the issue. Anyways again a big thanks for pointing me in right direction.
