### ISSUE TITLE
No implementation of md-not-found for Autocomplete in Angular2+

### ISSUE THREAD

**Issue by CarolLevesque** [angular/material2#13013]
#### Bug, feature request, or proposal:
Would like to have mat-not-found or something similar in Angular 2+

#### What is the expected behavior?
Angular 1.* had md-not-found, which allowed the user to realize there was no data they could choose from.

#### What is the current behavior?
Nothing appears if nothing comes back from database or if they typed it incorrectly.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Users don't know if they are doing something wrong or if there is no data in the drop down.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 2+

#### Is there anything else we should know?
If there is a workaround, I would love to hear it. I could't figure out a way around it.

**Comment by julianobrasil** [comment]
@CarolLevesque, it depends on what you want a see, but I think you can build up a workaround with some coding (not too much): https://stackblitz.com/edit/angular-rbirqg?file=app/autocomplete-overview-example.html

On stackblitz, type 'abc' at the input. It's a simple example of what you can do.

![image](https://user-images.githubusercontent.com/25405143/45236458-4668db80-b2b2-11e8-99a1-528bc70d206d.png)

**Comment by CarolLevesque** [comment]
This is exactly what I was looking for. Thank you!

**Comment by julianobrasil** [comment]
Surely... you can apply `pointer-events: none` to `mat-option` to avoid mouse interactions and think of a way to prevent the arrow keys selection.

**Comment by CarolLevesque** [comment]
Great idea. Thanks

**Comment by MumiaIrrequieta** [comment]
Can you please fix the stackblitz example? it's not working.
Nonetheless, the solution is far from optimal (with the option being selectable and all), so please reopen this issue because it's a regression from a previous feature.

**Comment by julianobrasil** [comment]
@MumiaIrrequieta, I've deleted it during a stackblitz clean up. But I built it again: https://stackblitz.com/edit/angular-difosq?file=app%2Fautocomplete-filter-example.ts

I agree that it's not ideal, but unfortunately, I think there's not enough outputs to manage it appropriately. But take a look at this example: the only not so good thing is that you can activate it through the keyboard (so I clear up the trigger when this happens).

**Comment by julianobrasil** [comment]
Ok, take a look again. Using the browser api directly, I was able to intercept the keyboard events and avoid the selection using keyboard keys. I think it's a satisfactory workaround.

**Comment by MumiaIrrequieta** [comment]
Thank you very much for your quick and working answer, it did the trick! but as you said, it's a "workaround".
Valeu!
