### ISSUE TITLE
mat-menu sub-menus don't return to their original size after shrinking 

### ISSUE THREAD

**Issue by f1ghtingfalcons** [angular/material2#13010]
#### Bug, feature request, or proposal:
bug
material sub-menus get stuck in a 95px width state when you collapse the width of the browser and then expand the size of the browser

![mat-menu-error](https://user-images.githubusercontent.com/3945430/45177055-14cb1400-b1cf-11e8-9ab9-37a8704ebb6c.gif)

#### What is the expected behavior?
material sub-menu items should return to their full size when the screen is wide enough

#### What is the current behavior?
sub-menu items remain at 95px after the browser width is reduced such that the sub-menus stack even after the screen width is increased such that they should be free to expand to be larger.

#### What are the steps to reproduce?
You can reproduce the error on the menu/examples page: https://material.angular.io/components/menu/examples

Simply open the nested menus -> collapse your browser width until the nested menus stack -> expand the browser width to the original size ( see gif above ).

#### What is the use-case or motivation for changing an existing behavior?
Text gets cut off unnecessarily making for a worse user experience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular: 6.1.4
@angular/material: 6.4.6
OS: Windows 10
Chrome: 69.0.3497.81
Typescript: 2.7.2

**Comment by crisbeto** [comment]
This will be fixed in 7.0 by https://github.com/angular/material2/pull/12624.
