### ISSUE TITLE
Can't Load Palettes

### ISSUE THREAD

**Issue by colindevs** [angular/material2#1301]
Bug, feature request, or proposal: **Bug**

What is the expected behavior? **Being able to use a prebuilt color palette by importing it from the `theming/prebuilt` folder inside the `core`.**

What is the current behavior? **The when building my project or serving it, I'm getting errors saying that the file `~@angular2-material/core/theming/prebuilt/deeppurple-amber.css` can't be found.** 

What are the steps to reproduce?
**`ng new` an app with Angular CLI beta 15, `npm install` the material 2 `core` and other components. Then add an import statement to `style.css` of the `src` folder importing `~@angular2-material/core/theming/prebuilt/deeppurple-amber.css`. Trying to `ng serve` or `ng build` results in an error:** 
```
ERROR in ./~/css-loader!./~/postcss-loader!./src/styles.css
Module not found: Error: Can't resolve '@angular2-material/core/theming/prebuilt/deeppurple-amber.css' in '/Users/colin/Desktop/maker/src'
 @ ./~/css-loader!./~/postcss-loader!./src/styles.css 3:10-122
 @ ./src/styles.css
 @ multi styles

```

Which versions of Angular, Material, OS, browsers are affected?
Angular: `2.0.0` (finally)
Material `2.0.0-alpha.8-2`
Mac OS X El Capitan
Angular CLI: `1.0.0-beta.15`

#### Is there anything else we should know?
I looked in the `node_modules` folder, went to `@angular2-material/core` and I did not see a `theming` directory. But the theming <a href="https://github.com/angular/material2/blob/master/docs/theming.md" _target="blank">docs</a> say there should be a `theming` folder inside of which there should also be a `prebuilt` folder, etc... I tried an import statement with a random file inside of the `core` folder, and it worked, so there's nothing wrong with the css, importing, webpack, etc... The problem is that `theming` is missing.

**Comment by j3ddesign** [comment]
Theming isn't implemented in the npm version yet. In the readme for the repo they have a list of what's released and isn't :)

**Comment by colindevs** [comment]
Ok, thanks for the clarification. Where is it implemented, if not in the npm version?

**Comment by fxck** [comment]
it's in master, it just isn't released yet, as there are apparently some bugs

**Comment by colindevs** [comment]
Ok

**Comment by colindevs** [comment]
I guess I'll just close the issue since it was just a misunderstanding. I would still like to know where to look out for the release of these themes when they're stable...

**Comment by alan345** [comment]
use 
@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
instead of
@import '~@angular/material/core/theming/prebuilt/deeppurple-amber.css';

https://github.com/angular/material2/blob/master/guides/theming.md
