### ISSUE TITLE
Getting an error 'cannot read property core of undefined' while using material2 modules in angular2 stable

### ISSUE THREAD

**Issue by Muthu2020** [angular/material2#1302]
Uncaught TypeError: Cannot read property 'core' of undefined(button-toggle.umd.js:4)
Uncaught TypeError: Cannot read property 'core' of undefined(button.umd.js:4)

Can anyone give an idea about it?

**Comment by jelbourn** [comment]
@Muthu2020 Please open a new issue following the issue template. This isn't enough information to investigate.
