### ISSUE TITLE
Angular 6 MatSnackBar not working in IE11

### ISSUE THREAD

**Issue by tom33pr** [angular/material2#13023]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
"@angular/material": "6.4.6" MatSnackBar working in IE11

#### What is the current behavior?
"@angular/material": "6.4.6" MatSnackBar NOT working in IE11 (working in Chrome fine)
![e](https://user-images.githubusercontent.com/24266549/45216236-c9c90380-b297-11e8-8512-9442e180bf35.png)

**My setup:**

app.shared.module.ts:
`import { MatSnackBarModule} from '@angular/material';`

my-test.component.ts:
`import { MatSnackBar } from '@angular/material';
...
    constructor(
    private snackbar: MatSnackBar,
...
this.snackbar.open('Submitted','Close',
            {
                duration: 3000,
            });`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "6.4.6"

**Comment by crisbeto** [comment]
I wasn't able to reproduce it under IE11, based on the code snippet from above. Judging by the stack trace, there may be something wrong with your setup. Closing the issue for now, but it can be reopened if there's a live example of it breaking.

**Comment by tom33pr** [comment]
Very helpful indeed, Kristiyan!!

**Comment by SergejSa** [comment]
i got the exact same error in production. not on my local serve build.

**Comment by tom33pr** [comment]
No... He (Kristiyan) didn't bother researching it and I gave up using IE for my app. 
Must say these guys (support here) are pretty quick to closing cases without properly troubleshooting them.

**Comment by SergejSa** [comment]
i found the solution.
i added following pollyfils:

import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/symbol';

one of this fixes the issue

**Comment by SergejSa** [comment]
nevermind. the application does not throw the exception on startup, but if i execute the function.
