### ISSUE TITLE
A button with a dropdown of buttons

### ISSUE THREAD

**Issue by dmytro-krekota** [angular/material2#13026]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Implement a button with a dropdown of buttons

#### What is the current behavior?
Currently, I could not find a good UI solution for it in Angular Material.

#### What are the steps to reproduce?
None

#### What is the use-case or motivation for changing an existing behavior?
I need to implement a custom design for a project.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
For more details see the issue: https://github.com/angular/material2/issues/7765

**Comment by josephperrott** [comment]
Closing as this is not on our roadmap as it does not differ from the select within the Material spec.


You should be able to create something like this yourself using the [`MatButton`](https://material.angular.io/components/button/overview) and [CDK's Overlays](https://material.angular.io/cdk/overlay/overview).

This is the same methodology that `MatSelect` and `MatMenu` use, if you would like to see examples from within the Angular Material Library.

**Comment by dmytro-krekota** [comment]
@josephperrott, ok, thanks.
