### ISSUE TITLE
md-slider ist not working properly

### ISSUE THREAD

**Issue by socke1995** [angular/material2#1304]
#### Bug, feature request, or proposal:

bug
#### What is the expected behavior?

slider handler is dragable
#### What is the current behavior?

handler is just fix at zero, after resizing the window the handler ist dragable 
after this the slider still does not give values back
the slider doesn't hold on to the steps I put in as attributes
#### What are the steps to reproduce?

I have a sidenav layout with another sidenav layout in it
there I have a sidenav with there three tabs
Within these three tabs there ist some content and the slider
#### Which versions of Angular, Material, OS, browsers are affected?

Angular2, Material Alpha 8
tested this under FF and Chrome

**Comment by nisdec** [comment]
I can confirm this.

**Comment by jmcgoldrick** [comment]
I think this is actually related to: #1234 which also explains why it works after window resize. #1303 fixes this issue, though I'm not totally sold that this is the only/best way to handle the issue...

**Comment by berc** [comment]
Hi, I have the same issue when slider is not displayed (display: none) during page load.

**Comment by svcninja** [comment]
Same issue
