### ISSUE TITLE
Text does not float to the right of the div under a progress bar.

### ISSUE THREAD

**Issue by melinda-schmitz** [angular/material2#13064]
#### Bug, feature request, or proposal:
Bug (possibly bug, could be an issue with CSS, please advise)

#### What is the expected behavior?
The text is expected to be floated to the right of the card, 

#### What is the current behavior?
When the text is below the progress bar the text floats to the right of the end of the progress bar.

#### What are the steps to reproduce?
(StackBlitz Editor)[https://stackblitz.com/edit/angular-rfqh9s-aca5p3?file=app%2Fcard-overview-example.html]
(StackBlitz Example)[https://angular-rfqh9s-aca5p3.stackblitz.io]

#### What is the use-case or motivation for changing an existing behavior?
We have a card with a progress bar and we would like to show the details of progress below the bar.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

#### Is there anything else we should know?
We are unsure if it is the styling on the progress bar or an actual issue with the progress bar.

**Comment by josephperrott** [comment]
Closing as the progress bar is a `block` item and elements will enter the flow after the element as they would with any normal `block` item as seen [here](https://stackblitz.com/edit/angular-vi8vkq?file=app/progress-bar-determinate-example.html).
