### ISSUE TITLE
MdGridList typo in Readme.md

### ISSUE THREAD

**Issue by Nefarion** [angular/material2#1306]
The [Readme.md](//github.com/angular/material2/blob/master/src/lib/grid-list/README.md) file for MdGridList shows the following code for importing the module:
`import {MdGridListModule} from '@angular2-material/`**gridlist';`**

The import statement should be 
`import {MdGridListModule} from '@angular2-material/`**grid-list';**

(At least that's the one working for me!)

I'm using version `2.0.0-alpha.8-2` of `@angular2-material/grid-list`

Greetings!

**Comment by bdh1011** [comment]
Docs not apllied yet...
