### ISSUE TITLE
mat-tab not working in ie11 - window10.

### ISSUE THREAD

**Issue by immi5556** [angular/material2#13061]
#### Bug:
mat-tab -> not working in ie11

#### What is the expected behavior?
mat-tab supposed to work with when polyfill included

#### What is the current behavior?
mat-lab - when loading gets the following error
Error: Cannot find a differ supporting object '[object Object],[object Object],[object Object],[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays
![image](https://user-images.githubusercontent.com/16042057/45312647-471b9f00-b54a-11e8-9e5e-2843c9aef0ae.png)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
NG Version : 6.0, 
Affected browser: ie11

#### Is there anything else we should know?

I modified below to fix this issue, but not sure you already have polyfill or any release plan..

//File Edit: \node_modules\@angular\core\fesm5 -> core.js
**File: node_modules\@angular\core\fesm5 -> core.js**

**1st Change**
Line No: 6209
if (collection instanceof QueryList && collection.toArray) { //Immanuel - FIX - 1
    collection = collection.toArray();
 }
 else {
  throw new Error("Error trying to diff '" + stringify(collection) + "'. Only arrays and iterables are allowed");
 }

**2nd Change**
Line no: 7319
 else { //Immanuel - FIX - 1
     if (iterable instanceof QueryList && iterable.toArray) {
     return iterable.toArray();
 }
throw new Error("Cannot find a differ supporting object '" + iterable + "' of type '" + getTypeNameForDebugging(iterable) + "'");

**3rd CHange**
**File Edit:  \node_modules\@angular\common\fesm5 -> common.js**
 Line No:  3377
try { //Immanuel - FIX - 1
    if (value instanceof QueryList && value.toArray) {
      value = value.toArray();
   }
  this._differ = this._differs.find(value).create(this.ngForTrackBy);
 }

**Comment by manklu** [comment]
You should provide an example to reproduce your problem.

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by josephperrott** [comment]
Closing as we are not be able to reproduce this issue.
