### ISSUE TITLE
Can't use mat-button for xhtml:button inside foreignObject

### ISSUE THREAD

**Issue by achmedzhanov** [angular/material2#13089]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-button works well with xhtml:button

#### What is the current behavior?
Template parse errors:
Can't bind to 'disabled' since it isn't a known property of ':xhtml:button'. ("
<foreignObject>
<xhtml:div>
[ERROR ->]<button mat-button>test</button>
</xhtml:div>
</foreignObject>
"): ng:///AppModule/AppComponent.html@5:6, Directive MatButton
Evaluating src/main.ts
Booting application

mat-button works well with xhtml:a

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-cg1d7p?file=src%2Fapp%2Fapp.component.html

Create simple component with markup
<h1> xhtml:button issues </h1>
<button mat-button>test</button>
<svg>
  <foreignObject>
    <xhtml:div>
      <button mat-button>test</button>
    </xhtml:div>
  </foreignObject>
</svg>

#### What is the use-case or motivation for changing an existing behavior?
Use material components inside foreignObject

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular 6.0.0
@angular/material 6.4.7

**Comment by jelbourn** [comment]
At this time Angular (and thus Angular Material) only directly supports HTML (and not XHTML).
