### ISSUE TITLE
Datepicker with custom formats not working

### ISSUE THREAD

**Issue by GuofuHuang** [angular/material2#13096]
#### Bug, feature request, or proposal:
when you open Datepicker examples with stackblitz.com, it doesn't give the expected result. 
Example name: Datepicker with custom formats

#### What is the expected behavior?
Display result with custom formats

#### What is the current behavior?
Now it only displays the default format

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by josephperrott** [comment]
Closing as we are not be able to reproduce this issue.

**Comment by Londovir** [comment]
For what it's worth, this issue has been hit by me today as well, using the actual Stackblitz link that fires from the Material examples from the online documentation. Look under the [Customizing Parse and Display Formats](https://material.angular.io/components/datepicker/overview#customizing-the-parse-and-display-formats) header, first example, launch it in Stackblitz to get this [broken example](https://stackblitz.com/angular/qvqvdjkpedp?file=app%2Fdatepicker-formats-example.ts).

Despite the built-in example on the documentation site working correctly, the standalone Stackblitz duplication of it fails to render using the custom formats. I'm seeing no console errors, but it's not properly outputting the "verbose" text either.
