### ISSUE TITLE
[ngStyle] not working on mat-chip

### ISSUE THREAD

**Issue by loriepisicchio** [angular/material2#13105]
#### Bug, feature request, or proposal:
Bug : styles applied with [ngStyle] are ignored by mat-chip

#### What is the expected behavior?
styles should be applied, as this is the case with classes and [ngClass]

#### What is the current behavior?
styles are not applied, and the generated HTML has ng-reflect-ng-style="[object Object]" attribute

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-gymt21

#### What is the use-case or motivation for changing an existing behavior?
Applying styles with ngStyle allows to use variables or constants instead of declared in CSS files.
In the provided sample the code is cleaner with use of ngStyle

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1
Material 6.4

**Comment by DevVersion** [comment]
Thanks for your issue. It actually works. Just the `!important` for the values of the inline styles are invalid. `inline styles` already have the highest specificity and therefore this is invalid.

See here: https://stackblitz.com/edit/angular-gymt21?file=src%2Fapp%2Fapp.component.ts
