### ISSUE TITLE
bug:(@angular/cdk/drag-drop) - Start end events firing twice Chrome (Android)

### ISSUE THREAD

**Issue by kccsf** [angular/material2#13125]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When touching a cdkDrag item and releasing without dragging, one cdkDragStarted and one cdkDragEnded event are expected.

#### What is the current behavior?
Those events are fired twice, in the following order:
cdkDragStarted, cdkDragEnded, cdkDragStarted, cdkDragEnded.

This does not happen if you drag in between the touch and release, in which case you correctly receive single cdkDragStarted, cdkDragMoved and cdkDragEnded events. 

#### What are the steps to reproduce?
https://angular-92bnjh-lzasmw.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
User code is running twice.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome (Android): 69.0.3497.91

iOS/Chrome (Windows) don't appear to be affected

**Comment by crisbeto** [comment]
Looks like it's because of the fake mouse events that get fired by mobile browsers. I also wanted to thank you about the great bug reports on the drag&drop. They've really helped polish the module up before the final release.
