### ISSUE TITLE
Update MatTable documentation that explains how the filter is applied

### ISSUE THREAD

**Issue by JacobBrandt** [angular/material2#13127]
Since it's been decided that the default behavior isn't going to change based on this issue https://github.com/angular/material2/issues/12914 could you at least update the documentation on the material website.

>By default, each data object is converted to a string of its properties and returns true if the filter has at least one occurrence in that string.

Ambiguous, as I didn't know this meant
```
Data Structure
prop1: help
prop2: me
prop3: now
```
would get converted to "helpmenow" where a filter of "men" would match.

By default, each data object is converted to a **contiguous** string of it's properties and returns true if the filter has at least one occurrence in that string.

By saying the string will be contiguous the statement is not ambiguous.

**Comment by jelbourn** [comment]
I reopened #12914, since that behavior isn't actually correct. I think the issue was misunderstood when it was closed.
