### ISSUE TITLE
elementScrolled event not firing on registered CdkScrollables

### ISSUE THREAD

**Issue by akolybelnikov** [angular/material2#13128]
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

should emit Observables on registered elements

#### What is the current behavior?

the ScrollDispatcher registers all CdkScrollables but no Observables are emitted on scroll events

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-cdk-scrollable-event?file=src%2Fapp%2Fapp.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6.0.3, Angular CDK 6.1.0

**Comment by crisbeto** [comment]
That's because you're not scrolling inside the scrollable elements, rather it's still the window that is scrollable.

**Comment by akolybelnikov** [comment]
If you put cdkScrollable directive on the container div, nothing is emitted either.

**Comment by crisbeto** [comment]
Closing since it works as expected.
