### ISSUE TITLE
Autofill from Chrome shows weird behaviour on the md-input placeholder

### ISSUE THREAD

**Issue by reinos** [angular/material2#1313]
#### #Bug

on the login form chrome tried to autofill the username/email and password. Only the the label of the input keep showing, despite that i set it to hidden. If i remove the value that chrome filled in, and type something, it works good.
#### What is the expected behavior?

It should be hide the label when there is a value. I did it with sass/css

```
.md-input-placeholder.md-float:not(.md-empty),
.md-input-placeholder.md-float.md-focused
    display: none
```
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.0.0
Chrome Version 53.0.2785.116 (64-bit)
Material 2.0.0-alpha.8-1

![screen shot 2016-09-23 at 10 15 26](https://cloud.githubusercontent.com/assets/633730/18779504/90e6d052-8179-11e6-8523-31ce0da7a802.png)

Also, we are using the following code for the button

```
<button disableRipple="true" class="btn-submit" [attr.disabled]="!f.valid || submitted ? true : null" [ngClass]="{'working': submitted}" (click)="register(f)" md-raised-button color="primary">
    <md-spinner class="btn-spinner"></md-spinner> Sign up to Jexia!
  </button>
```

So that the button is disabled when you have nothing filled in, but when all inputs are filled in, the button comes available. But with the autofill function of chrome, this is not triggered, until you click somewhere on your screen.

**Comment by reinos** [comment]
Any idea when you guys can check this issue?

**Comment by mmalerba** [comment]
Chrome intentionally doesn't trigger a value update until the user interacts with the page, see: https://bugs.chromium.org/p/chromium/issues/detail?id=352527

**Comment by ShankzPatil** [comment]
working... is parent div "md-input-container"

```
$(document).ready(function () {
setTimeout(function () {
var $pwdInput = $('input[type="password"]:-webkit-autofill');
$pwdInput.closest("md-input-container").addClass('md-input-has-value');
}, 500);
});
```
