### ISSUE TITLE
Material select - selectionChange not firing when set default value, not by user

### ISSUE THREAD

**Issue by faradoxuz** [angular/material2#13138]
I'm using material select component in my app. Sometimes I have set default value in mat-select. but selectionChange event not firing when set default value. I read the documentation, there were written
`Event emitted when the selected value has been changed by the user.`

Is there any way that I can trigger programmatically?

**Comment by crisbeto** [comment]
You could get a hold of an instance of `MatSelect` using a `ViewChild`/`ContentChild` and emit to `selectionChange` yourself, but it seems a little convoluted, because you know when the event is going to fire since you're the one setting the value.

**Comment by faradoxuz** [comment]
selectionChange you cant use this by ViewChild/ContentChild

**Comment by SWGeekPD** [comment]
I am having the similar kind of problem.
I want to set Mat-Select value from code. And based on assigned drop down value I need to show hide few form fields. I am setting the Mat-Select value from .ts file on initialization. like this
this.myForm.controls.myControl.setValue(this.dd[1]);
This is setting the value in Mat-Select drop down but it is not triggering selectionChange event and hence not able to show/hide other fields. Also reactive form mat-select field is not dirty.
Please suggest if there is a way to achieve this.
