### ISSUE TITLE
md-ripple only enlargens the element it is applied to

### ISSUE THREAD

**Issue by PascalTemel** [angular/material2#1314]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

A ripple effect is applied when the element is clicked
#### What is the current behavior?

The element simply gets bigger with each click
#### What are the steps to reproduce?

Apply the tags `md-ripple [md-ripple-color]="rippleColor"` to an element and click it.

Click the basic button in this plunkr:
http://plnkr.co/edit/LoliY4kSCD66HT5AHgrn?p=preview
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.0.0, Material alpha 8-1, Chrome 53

**Comment by rbaumi** [comment]
To fix that weird issue: 

- With version < 9 include styles:

```
node_modules/@angular2-material/core/style/core.css
node_modules/@angular2-material/core/overlay/overlay.css
```

- From version aplha.9 include:

`/node_modules/@angular/material/core/theming/prebuilt/indigo-pink.css`

You can do that globbaly in your index file:

`<link rel="stylesheet" type="text/css" href="/node_modules/@angular/material/core/theming/prebuilt/indigo-pink.css">`

or just use the styleUrls attribute in component decorator (don't forget about the encapsulation property (probably has to be set to ViewEncapsulation.None) in this case).

**Comment by jelbourn** [comment]
Sounds like this is caused by missing the core styles. See https://github.com/angular/material2/blob/master/docs/theming.md
