### ISSUE TITLE
Allow mat-checkbox click event to read checked value

### ISSUE THREAD

**Issue by SzabKel** [angular/material2#13156]
#### Bug
Checkbox's event has no way to get the `checked` value of the source checkbox if we would like to use the `(click)` event.

#### What is the expected behavior?
Define `event.checked` or a similar property.

#### What is the current behavior?
The values are `undefined`

#### What are the steps to reproduce?
https://stackblitz.com/edit/matcheckbox-checked

#### What is the use-case or motivation for changing an existing behaviour?
I would like to make a checkbox, where value only gets changed if the underlying HTTP request succeeds (there is a confirm box after the click and the request returns the entity changed, so I can get the updated value and change the values based on that, also I display notification about the success or failure..etc). The checkbox should not change value before I handle the event.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I used  `"@angular/core": "^6.1.2"`, `"@angular/material": "^6.4.6"` and ` "typescript": "^2.9.2"`, chrome, but you can check the stackblitz too.

#### Is there anything else we should know?

https://github.com/angular/material2/issues/1142

https://stackoverflow.com/questions/52364296/matcheckbox-preventdefault-and-event-checked-value

**Comment by SzabKel** [comment]
As Chellappan pointed out, [this (stackblitz)](https://stackblitz.com/edit/matcheckbox-checked-a1le6o) works.

**Comment by jelbourn** [comment]
The `click` event on the checkbox is just the native click event, which doesn't know anything about the checkbox itself. Using the change event or just getting a handle on the `MatCheckbox` instance directly (e.g. with `@ViewChildren`) would be the recommended approach.

**Comment by simeyla** [comment]
You can do this:
