### ISSUE TITLE
Date not accepted in yyyy. MM. dd. on Firefox on hungarian locale

### ISSUE THREAD

**Issue by lukibeni** [angular/material2#13158]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Date typed in yyyy. mm. dd. format should be accepted, when locale set to hu-HU on Firefox

#### What is the current behavior?

Date typed in the required format accepted on Chrome but not in Firefox

#### What are the steps to reproduce?

https://angular-material2-issue-vgvnzv.stackblitz.io

1. Type for example 2018. 12. 13.
2. On Chrome, the date is selected, but on Firefox isn't

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: 6.1.3
Material: 6.4.5
Chrome: 69.0.3497.92
Firefox: 62.0

**Comment by lukibeni** [comment]
Can anyone confirm this bug?

**Comment by jelbourn** [comment]
See https://material.angular.io/components/datepicker/overview#internationalization

The i18n is handled either by the browser itself (`NativeDateAdapter`) or by a 3rd party library (e.g. `MomentDateAdapter`). The component itself doesn't know anything about timezones or localization.
