### ISSUE TITLE
Mat-Sort-Header aria-label doesn't support multiple languages

### ISSUE THREAD

**Issue by flyer1** [angular/material2#13167]
When you use a mat-sort-header like this:
`<th mat-sort-header="first name">`

What gets generated contains this:
`aria-label="Change sorting for first name"`

As far as I can tell, there isn't a way to support multiple languages. I know you can customize MatSortHeaderIntl to return a phrase in a different language, but what about the column name? (ie: 'first name' in the example above). 

That value comes from id below: (from mat-sort-header.html)
`[attr.aria-label]="_intl.sortButtonLabel(id)"`

Chasing back where the id comes from: (from mat-sort-header.ts)
`@Input('mat-sort-header') id: string`

And finally in sort-header-intl.ts:
` sortButtonLabel = (id: string) => {
    return 'Change sorting for ${id}';
}`

To loop around, the value that was assigned to mat-sort-header ('first name') is used in the aria phrase. But we need to have that phrase change when the displayed language changes. 

Am I missing something? It seems to me that the code value that is used to help in sorting logic is doing double duty by showing up in the aria label.

**Comment by jelbourn** [comment]
You would provide a custom `MatSortHeaderIntl` that substitutes the correct message based on the column ID passed into `sortButtonLabel`. Something roughly like
```ts
const sortHeaderLabels = {
  'name': 'Trier par nom',
  'age': 'trier par âge',
};

sortButtonLabel = (columnId: string) => {
  return sortHeaderLabels[columnId];
}
```

Obviously the real code depends on how your app does its i18n
