### ISSUE TITLE
When a tab is removed from the mat-tab-group it should destroy orphaned mat-tabs.

### ISSUE THREAD

**Issue by kayvanbree** [angular/material2#13164]
#### Bug, feature request, or proposal:

When building up a mat-tab-group where mat-tabs are based on some array, we get some unexpected behaviour when a value of that array is removed. 

Relevant code:
```javascript
<mat-tab-group #tabs>
	<ng-container *ngFor="let panel of dock.panels">
		<mat-tab>
			<ng-template mat-tab-label>
				<div>
					<span class="tab-title">{{panel.name}}</span>
					<span style="flex: 1 1 auto;"></span>
					<div class="tab-options">
						<button mat-icon-button (click)="onClose(panel)">
              <mat-icon>close</mat-icon>
            </button>
					</div>
				</div>
			</ng-template>

			<!-- ng-template with matTabContent makes the tabs lazy load -->
			<ng-template matTabContent>
				<app-annoying [name]="panel.name"></app-annoying>
			</ng-template>
		</mat-tab>
	</ng-container>
</mat-tab-group>
```

#### What is the expected behavior?

When a tab is removed from the mat-tab-group it should destroy orphaned mat-tabs.

#### What is the current behavior?

Orphaned mat-tabs continue to live on without any reference to them. In my example you can see an interval that is set in the constructor. The interval will continue to log messages from panels that don't exist anymore.

#### What are the steps to reproduce?

To recreate this bug:
- Load this application
- Click panel2 (not the close button)
- Check the console (there should be messages from both panel1 and panel2)
- Close panel2
- Bug: panel2 is still alive and well, as seen in the console.

Expected behavior:
- Any panel not in the tabgroup anymore should have their destructor called

https://stackblitz.com/edit/angular-wfkpqq?file=src%2Findex.html

#### What is the use-case or motivation for changing an existing behavior?

I am trying to build a system where I can dynamically drag tabs from one tab-group to another. Adding works, moving them works, but removing doesn't actually destroy the components. With this bug intervals of removed tabs will continue to do stuff, rxjs subscriptions will continue to live on and the memory will fill up with unused components.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"dependencies": {
    "@angular/animations": "^6.1.7",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.7",
    "@angular/compiler": "^6.1.7",
    "@angular/core": "^6.1.7",
    "@angular/forms": "^6.1.7",
    "@angular/http": "^6.1.7",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.1.7",
    "@angular/platform-browser-dynamic": "^6.1.7",
    "@angular/router": "^6.1.7",
    "core-js": "^2.5.7",
    "rxjs": "^6.3.2",
    "zone.js": "^0.8.26"
  },

#### Is there anything else we should know?

It should be possible to work with the tabgroup in a dynamic way. One way to solve this would be to add some way to programmatically close a tab. Then I can close the tab before updating my data structure that build the tabs.

**Comment by crisbeto** [comment]
The component does get destroyed, but there's no way for Material or Angular to clear that interval for you. You should save a reference to the interval and then clear it yourself in `ngOnDestroy`. [Here's a working fork of your example](https://stackblitz.com/edit/angular-xmjyrk?file=src/app/annoying/annoying.component.ts).
