### ISSUE TITLE
Adding/Removing Tabs

### ISSUE THREAD

**Issue by ajrauen** [angular/material2#1317]
#### Bug, feature request, or proposal:

Add the ability to create and destroy a tab

**Comment by jelbourn** [comment]
@ajrauen Please follow the issue template and add more context to your request. You can already dynamically show and hide tabs with things like `ngIf` and `ngFor`; please explain why this wouldn't be enough.

**Comment by ajrauen** [comment]
I don't want to show/hide, though I admit that hiding could be "good enough" in place of destroying.  I want to be able to add a tab because the tab-content is dynamic. Sometimes it'll be X component, sometimes Y or Z or so on. Or it could be 10 tabs each with component X.

Basically I want the user to be able to click a button and open a new tab based on the button.

**Comment by 13k** [comment]
Use ngFor over an array and add elements to that array when the user clicks
the add tab button.

**Comment by ajrauen** [comment]
But that would only add the tab, remember than the tab content is dynamic.
