### ISSUE TITLE
mat-select not setting value when using *ngFor to fill list

### ISSUE THREAD

**Issue by flipZomb** [angular/material2#13188]
#### Bug, feature request, or proposal:
Maybe a bug.

#### What is the expected behavior?

I would expect the [(value)] binding on both of these mat-selects to work, but I can only get it to work on the first one.

![image](https://user-images.githubusercontent.com/33517613/45719334-5204ae00-bba0-11e8-8def-3285f9c0b7e7.png)

this is the ts code

![image](https://user-images.githubusercontent.com/33517613/45719359-68126e80-bba0-11e8-9be9-81226654e02d.png)

this is the result

![image](https://user-images.githubusercontent.com/33517613/45719252-0a7e2200-bba0-11e8-806e-21adf2f2a80d.png)

So, only when not using the ngFor, does the [(value)] binding seem to work as expected.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-1k7ykb?file=app%2Fselect-value-binding-example.html>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.4.7
Angular 6.1.7

**Comment by feeloor** [comment]
You've forgot to add brackets around "value"-attribute, `[value]="o"` will solve the problem.
Also consider using `[(ngModel)]` instead of `[(value)]` on the select.

See stackblitz: https://stackblitz.com/edit/angular-1k7ykb-cfmaq7

**Comment by mungpara** [comment]
use [value]="o" or value="{{o}}" solve your problem.

**Comment by crisbeto** [comment]
@feeloor and @mungpara are correct. In your current example, the `value` for all the options is set to `o`. Closing as a non-issue.
