### ISSUE TITLE
Spinner Animation Broken When Loading 

### ISSUE THREAD

**Issue by b-mi** [angular/material2#13194]
#### Bug, feature request, or proposal:
Bug, in Chrome, Firefox, Opera browser, in Edge ok

#### What is the expected behavior?
No animation problem

#### What is the current behavior?
Spinner Animation Broken When Loading, visible only part of spinner during http.get

#### What are the steps to reproduce?

```
reload() {
    this.service.spinnerActive = true;
    this.service.shopgetgoods().subscribe(r => {
      const rx = r as any[];
      const sorted = rx.sort((a, b) => a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1);
      this.goods = sorted;
      this.dataSource = new MatTableDataSource<any>(sorted);
      this.dataSource.sort = this.sort;
      this.service.spinnerActive = false;
    });

```

```
    <div>
      <mat-spinner *ngIf="service.spinnerActive===true" mode="indeterminate" diameter="45" color="accent">
      </mat-spinner>
    </div>

```

1 - when no http.get calling - spinner work ok
2 - when http.get is called - spinner is rotating and show only part of spinner
          [https://i.imgur.com/GONEFv0.png](https://i.imgur.com/GONEFv0.png)
3 - when http.get is called - after http.get ends spinner is rotating and full, but it have some rendering issues

Spinner is shown at the beginnig and hidden once at the end.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 material 6.4.7, angular 6.1.7. chrome, win 10m typescript: 2.9.2

**Comment by crisbeto** [comment]
That's because doing work on the main thread will cause the browser to pause animations, if it has to. Since we're using CSS animations for everything in the progress spinner, I don't think there's much more we can do on our end to avoid it.

**Comment by b-mi** [comment]
I thought that httpclient.get with subscribe is working on another thread, or not?

**Comment by crisbeto** [comment]
I don't think it will unless you're doing it explicitly. Also there may be something else on the main thread that is holding it up. Closing the issue since we can't do anything about it either way.

**Comment by b-mi** [comment]
... at last - the problem was in rendering 2-3 hundred rows in mat-table.
