### ISSUE TITLE
Unexpected behavior when adding an element in MatAutocomplete apart from options or customizing the styling of options

### ISSUE THREAD

**Issue by varunrramani** [angular/material2#13192]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
1) Last option or the option which is at the bottom of the panel should not be cropped by the size of the header.

#### What is the current behavior?
1) When adding a header to the mat-autocomplete and navigating the options using the keyboard arrow keys, the last options in the panel get cropped by the size of the header.

2) When applying custom styling to the options and navigating using the keyboard arrow keys the selected option is not always the last option visible on the panel.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-vbcan5?file=app/autocomplete-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Able to replicate on the latest version of Angular and Material.
Tested on OS: Windows 7, Chrome 68

**Comment by crisbeto** [comment]
This isn't something that we support. We assume that all options will be the same height (the same is enforced through CSS) in order to avoid having to measure elements in the DOM. We use the height and the amount of options to determine how far the panel should scroll.

**Comment by varunrramani** [comment]
Could you please have a look at the second point in the issue. We are giving the same height to the options and the scrolling breaks. Its the second mat-autocomplete in the example stackblitz.

Thanks!
