### ISSUE TITLE
Theming documents confusion or possible conflict

### ISSUE THREAD

**Issue by jbeckton** [angular/material2#13206]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Docs would not conflict or be more clear

#### What is the current behavior?

In the [Theming Guide - Custom Theme](https://material.angular.io/guide/theming#defining-a-custom-theme)

There is a paragraph at the end of that heading that reads...

> The theme file should not be imported into other SCSS files. This will cause duplicate styles to be written into your CSS output. If you want to consume the theme definition object (e.g., $candy-app-theme) in other SCSS files, then the definition of the theme object should be broken into its own file, separate from the inclusion of the mat-core and angular-material-theme mixins.

And then in another document regarding [theming your own components](https://material.angular.io/guide/theming-your-components#using-colors-from-a-palette) 

There is a code snippet that shows the theme file being imported into a component.scss file. So either this contradicts the previously mentioned docs or the docs should show us an example of how the definition of the theme object can be broken into its own file and make that obvious in that example.

#### What are the steps to reproduce?
read [Theming Guide - Custom Theme](https://material.angular.io/guide/theming#defining-a-custom-theme) then read [theming your own components](https://material.angular.io/guide/theming-your-components#using-colors-from-a-palette) 

#### What is the use-case or motivation for changing an existing behavior?
clarity?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
v6

#### Is there anything else we should know?
I like turtles

**Comment by benelliott** [comment]
> There is a code snippet that shows the theme file being imported into a component.scss file.

I think maybe you have misunderstood the documentation slightly. It's critical _not_ to import theme mixins in the component SCSS file. Instead the mixins should all be imported in a centralised style file. Note however that the component's theme file itself should live _alongside_ the component's base SCSS file for maintainability.

**Comment by jbeckton** [comment]
So how do we get access to mat-color($primary) in our component.scss without importing the theme file? I suppose I could put all the color attributes in a component theme but I disagree with having the component theme file along side the component base SCSS, this would require a central location to import all those theme files from various locations throughout the file structure creating a maintenance burden. I think the documentation falls short of providing best practice demos for apps that are of medium complexity and higher. What happens when you have a component lib that is shared across apps?
