### ISSUE TITLE
Autocomplete: Add support for dividers in options list

### ISSUE THREAD

**Issue by kseamon** [angular/material2#13200]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Support for dividers in the Autocomplete popup

#### What is the current behavior?
Not supported

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by crisbeto** [comment]
@kseamon you can use `mat-divider` inside `mat-autocomplete` already, but you'll have to set `margin-top: -1px` on it yourself to avoid issues with the keyboard scrolling. I've submitted #13224 to handle it from Material.
