### ISSUE TITLE
[matAutocomplete] Button in input group triggers autocomplete dropdown

### ISSUE THREAD

**Issue by gpit2286** [angular/material2#13208]
#### What is the expected behavior?
When using a button in the same input group, it shouldn't select the autocomplete directly. 

#### What is the current behavior?
When the button is pressed, the autocomplete is focused and the dropdown is displayed. 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>

* Add Dropdown
* Add button to input group 
* Click on button 
* https://stackblitz.com/edit/angular-material2-issue-imef2p

#### What is the use-case or motivation for changing an existing behavior?
Currently I am trying to use the button to add elements on the fly.  When the button is pressed and the add item dialog is opened, the autocomplete panel will also open with (what seems to be) the same z-index as it is not covered by the backdrop.  This is confusing to the user. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular/Material 6.4.7

#### Is there anything else we should know?
Nope.

**Comment by crisbeto** [comment]
That happens, because any click inside the form field will move focus to the input, which in turn opens the autocomplete. @mmalerba should we revisit this decision for things inside the prefix/suffix?

@gpit2286 you can work around it by calling `event.stopPropagation` in the click handler. [Here's a fork of your example](https://stackblitz.com/edit/angular-material2-issue-e1tuj4).

**Comment by mmalerba** [comment]
Yeah it's kind of use-case-dependent, some prefix/suffix are purely decorative so it makes sense to focus the input, and some are actual buttons that do things and then you might not want the focus. I'm not sure if its worth changing at this point.

**Comment by gpit2286** [comment]
@mmalerba @crisbeto  - Thank you. I'll just close this then.
