### ISSUE TITLE
"mat-chip-list" Need to have the movable feature with drag n drop

### ISSUE THREAD

**Issue by Samoulou** [angular/material2#13215]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
It would be nice to have the option to order the chips created with drag n drop

#### What is the current behavior?
You cannot move you chips in your liste at the moment

#### What is the use-case or motivation for changing an existing behavior?
we need mat-chip-list to create some tag and we'd like to order them.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular-devkit/build-angular": "0.8.2",
"@angular/animations": "6.1.7",
"@angular/cdk": "6.4.7",
"@angular/common": "6.1.7",
"@angular/compiler": "6.1.7",
"@angular/core": "6.1.7",
"typescript": "2.9.2"
"@angular/material": "6.4.7",

**Comment by jelbourn** [comment]
This would be a nice example to have if someone wants to open a PR.
