### ISSUE TITLE
cursor: pointer should be used only for links

### ISSUE THREAD

**Issue by VaclovasV** [angular/material2#13214]
#### Bug, feature request, or proposal:
Every clickable element (button, select and etc), has cursor:pointer in angular material, for example:
https://github.com/angular/material2/blob/master/src/lib/core/style/_button-common.scss

#### What is the expected behavior?
https://ux.stackexchange.com/questions/109739/should-anchors-acting-as-buttons-use-the-pointer-cursor

#### What is the current behavior?
cursor:pointer is applied almost on all clickable elements ijn google material ui

#### What is the use-case or motivation for changing an existing behavior?
cursor: pointer should be applied to links only.

**Comment by jelbourn** [comment]
This is working as intended as prescribed by Google's Material Design UX team.

**Comment by simaks** [comment]
Could you provide citation/source to explanation for this? Where can we open issues for Google's UX team?

**Comment by jelbourn** [comment]
It's not something called out in the spec, but from a clarification from some meeting we had with them long ago. They don't really have an issue tracker for the spec.
