### ISSUE TITLE
Changing Colors

### ISSUE THREAD

**Issue by dasois** [angular/material2#1322]
#### Bug, feature request, or proposal:
Proposal: Write a quick tutorial for how to change the $primary/$accent etc. colors (even if it is ugly now).

I got the release source-code, but which gulp task builds the packages in a way, that they are exchangeable with the npm-packages?

**Comment by dasois** [comment]
#123

**Comment by m0t0r** [comment]
@dasois, the theming guide is located [here](https://github.com/angular/material2/blob/master/docs/theming.md). _Note:_ the theming support described in the guide has not been released yet. Check [DEV_ENVIRONMENT.md](https://github.com/angular/material2/blob/master/DEV_ENVIRONMENT.md) if you want to build material2 yourself.

**Comment by jelbourn** [comment]
What @m0t0r said.
