### ISSUE TITLE
mat-table scrolling

### ISSUE THREAD

**Issue by ptitdje45** [angular/material2#13238]
Hello everyone, 

I currently done this on an app and i have a table of 1000+ row. Is there a simple way to handle infinite scrolling on it ? ( note that i load all data before, so i don't really need something loading data on scroll, i feel that a css tricks can be done on this )

`<table mat-table matSort (matSortChange)="sortData($event)" [dataSource]='filteredmails'>`

Thanks

**Comment by jelbourn** [comment]
It's not built into the table yet, but on the roadmap.
