### ISSUE TITLE
Virtual scroll does not show horizontal scrollbar in vertical mode.

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#13231]
#### What is the expected behavior? Horizontal scroll bar should be visible if the
content width is > scroll wrapper

#### What is the current behavior?
No scroll bar.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

See this demo:
https://stackblitz.com/edit/angular-cdk-demo-virtual-scroll-clcggn?file=app%2Fdata%2Fstates.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.0.2 beta

#### Is there anything else we should know?
This happens due to [this commiet](https://github.com/angular/material2/commit/4a9fe87f8ae4fcdf722b10c95de804d97cdeddfe#diff-b12b934c3bb8e9e4b2f03fc09981e8dbR46)

If `.cdk-virtual-scroll-content-wrapper` is set with `contain: content` the scrollbar will now show...
It might boost performance but it has issues with other things.

Maybe we can go half way?
`contain:  style paint`

> This will fix the scroll but still might have issues with other things...

**Comment by shlomiassaf** [comment]
EDIT: Setting to `style paint` will also cause error, scroll will not render once moving it.

**Comment by mmalerba** [comment]
It looks like it actually works fine with `contain: content` as long as the wrapper is allowed to expand to the width of the items: https://stackblitz.com/edit/angular-cdk-demo-virtual-scroll-wfa253?file=app/virtual-scroll/virtual-scroll.component.css

I can probably replace the `right: 0` with `min-width: 100%`. But it also might be easier to just let people add that if they need it.
