### ISSUE TITLE
Virtual scrolling on window

### ISSUE THREAD

**Issue by iskathi** [angular/material2#13237]
Feature request:
Ability to bind virtual scrolling to window.
Ex. <cdk-virtual-scroll-viewport [scrollParent]="window" autosize>...</cdk-virtual-scroll-viewport [scrollParent]=window autosize>

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate/discuss. 

(this is a canned response)
