### ISSUE TITLE
[md-slide-toggle][universal-starter] window is not defined

### ISSUE THREAD

**Issue by morriq** [angular/material2#1323]
Hello. 

When I've added MdSlideToggle to main.node.ts then my project has stopped building. Similar issue is with MdTooltipModule.

> var __decorate$1 = (window && window.__decorate) || function (decorators, target, key, desc) {
>                     ^
> 
> ReferenceError: window is not defined
>     at /www/sites/fakturomat/wwwroot/node_modules/@angular2-material/core/core.umd.js:7:21
>     at c (/www/sites/fakturomat/wwwroot/node_modules/@angular2-material/core/core.umd.js:2:68)
>     at Object.<anonymous> (/www/sites/fakturomat/wwwroot/node_modules/@angular2-material/core/core.umd.js:5:2)

**Comment by m0t0r** [comment]
@morriq see #308

**Comment by jelbourn** [comment]
Dupe of #308
