### ISSUE TITLE
Mat Select 'required' validation not triggering formGroup.invalid

### ISSUE THREAD

**Issue by kovaljames** [angular/material2#13245]
#### Bug, feature request, or proposal:
Bug: Mat Select validations doesnt work without some user interaction

I'm using Mat Select inside a Form Group with Validators:
```
// template
<form [formGroup]="addressForm">
  <mat-form-field>
      <mat-select placeholder="Estado" formControlName="state">
         <mat-option *ngFor="let state of states" [value]="state.name">{{state.name}}</mat-option>
       </mat-select>
       <mat-error *ngIf="addressForm.controls.state.errors?.required">
          State is required.
       </mat-error>
  </mat-form-field>
  ...
  <button  type="submit" [disabled]="addressForm.invalid"> Save </button>
</form>
// component
this.addressForm = this.fb.group({
      state: [null, Validators.required],
      city: [null, Validators.required]
});
```
`addressForm.invalid` doesn't trigger without user interaction with `mat-select` element.

#### What is the expected behavior?
formGroup should be invalid without user interaction because formControl is required.

#### What is the current behavior?
`addressForm.invalid` doesn't work without user interaction with `mat-select` element. After interaction and not selecting anything, validation works as expected.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.1.7
Material: 6.4.7
Typescript: 2.9.2

**Comment by yogeshgadge** [comment]
Your StackBlitz is not correct.

Here is an example where it shows invalid.

https://stackblitz.com/edit/angular-qyx2jr?file=app/select-hint-error-example.html

>  addressForm.invalid doesn't work without user interaction with mat-select element.

because the default ErrorStateMatcher  `isErrorState` on touched (or submitted).

You can supply your own error state matcher to mat-select which is defined as `@input` and there is one example on material.angular.io under Mat Select or Form Field I can't remember

**Comment by yogeshgadge** [comment]
Here is an example of ErrorStateMatcher where you can eagerly display form field in error state. IMO user's don;t like it.

https://stackblitz.com/edit/angular-dqvzr2?file=app%2Fselect-error-state-matcher-example.ts

**Comment by kovaljames** [comment]
Thanks for the examples. I made a StackBlitz and it worked as expected, then I realized a (blur) method on "zipcode" field was throwing some wrong values inside Mat-Select. Now its working... next time i'll make a StackBlitz before opening a issue.
