### ISSUE TITLE
Adjust toolbar title position according to MD spec

### ISSUE THREAD

**Issue by dasois** [angular/material2#1324]
#### Bug, feature request, or proposal:
Feature request: Toolbar-title must start at [72dp from left screen border (scroll down to 'metrics')](https://material.google.com/layout/structure.html#structure-app-bar) on mobile.
On tablet and desktop the title starts at 80dp.

#### What is the expected behavior?
If you just insert the title after the icon, you expect it to be correctly positioned.

#### What is the current behavior?
Title is too far on the left side and thus too near at the toolbar-icon

#### What is the use-case or motivation for changing an existing behavior?
You don't want the user to style this manually, if it is specified that way...

**Comment by dasois** [comment]
I would like to help out with that. Is there a way yet to distinguish between mobile, tablet and desktop?

**Comment by jelbourn** [comment]
I'm not sure this is something we want to do for the toolbar; it's one of those situations where the component trying to be _too_ intelligent might get in the way of a developer trying to do something different.

**Comment by dasois** [comment]
Well if 1/100 developers would take the toolbar and do some crazy styling with it, she can also adjust the position of the title. Yes it must remain configurable.
In my opinion though 99/100 developers would like to see the title just where it is supposed to be according to the spec.

**Comment by aciccarello** [comment]
@jelbourn Does that also apply to `mat-icon-button`s too? I feel like having an icon at the beginning of a row is common pattern (e.g. having a back button). May be a `:first-child` selector could handle this for the default case.

Even if the component should stick with simpler default styling, I'd appreciate either some utility classes or documentation indicating that some styling is necessary to align with the spec.
