### ISSUE TITLE
@angular/cdk/drag-drop: one-way dragging bug

### ISSUE THREAD

**Issue by ptoro** [angular/material2#13246]
#### Bug, feature request, or proposal:
Bug

#### Explanation
If you want to only allow one-way dragging (e.g. left list to right list), you remove the `connectedTo` directive from one of the lists. This causes a problem where if you drag from one list to another list and back to the original list without dropping, the `cdkDrag` element you dragged won't go back to the original list. Here's a gif that showcases this behavior: ![cdk drag-drop one-way drag issue reprodution](https://user-images.githubusercontent.com/4418961/45786057-96855d80-bc23-11e8-8fd2-633d75c60b97.gif)

I can provide a StackBiltz but the only change I had to make from [this StackBlitz](https://stackblitz.com/angular/ayqvpybrlqy) for the [Transferring items between lists](https://beta-angular-material-io.firebaseapp.com/cdk/drag-drop/overview#transferring-items-between-lists) example to reproduce this behavior was to remove `[connectedTo]="[todoList]"` from the `donelist`'s `cdkDrop` selector. (Side note: I had to copy the StackBlitz code and run it locally because none of the StackBiltzs linked to on [this page](https://beta-angular-material-io.firebaseapp.com/cdk/drag-drop/overview) are working. They either won't drag or it shows an error. I didn't notice anyone else mention this or an existing issue for it.)

**Comment by ptoro** [comment]
Thanks for the PR for this @crisbeto. 

Should I create a separate issue for the StackBlitzs not working? I didn't see a resolution for that in this PR but I'm not sure if it's something that should have an issue associated with it since it's probably not considered part of the code base.

**Comment by crisbeto** [comment]
The linked Stackblitz doesn't work, because the drag&drop isn't in the latest stable version yet. Once 7.0.0 final is released, it'll work.
