### ISSUE TITLE
Add margin to cards

### ISSUE THREAD

**Issue by dasois** [angular/material2#1325]
#### Bug, feature request, or proposal:
Feature Request: Cards do have a margin of 8dp [according to Material Design spec](https://material.google.com/components/cards.html#cards-content-blocks)

#### What is the expected behavior?
Cards should have this margin automatically by themselves.

#### What is the current behavior?
Cards do not have a margin.

**Comment by jelbourn** [comment]
We very intentionally do not add margins to any of our components in material2 because, in practice, this is always going to depend on the application.

**Comment by dasois** [comment]
I don't understand.

1. Paddings and margins are used in other components since they are necessary to style them according to the spec
2. These margins are defaults, they can be overwritten, if the application needs that.
3. Cards in Angular-Material 1.x do have default margins.

Generally speaking i would strongly wish for a convention over configuration approach in material2.
If you skip margins, because they depend on the application, you'll also need to skip other margins, paddings, font-sizes etc...

**Comment by david-oyeku** [comment]
lets have default and then we can override them ourselves if we dont want

**Comment by ORESoftware** [comment]
yes default should have a margin. DUH. :)
