### ISSUE TITLE
Angular mention-box feature request

### ISSUE THREAD

**Issue by silentsnooc** [angular/material2#13266]
#### Feature Request

A mention-box as we know it from #Twitter, @github and other sites.

There are repositories out there which offer this but I couldn't find an active one 

Searching for "angular mentions" will lead to https://github.com/dmacfarlane/angular-mentions which, unfortunately, does not allow to add HTML input.

Libraries like https://podio.github.io/jquery-mentions-input/ do have what we want e.g. inserting HTML but also extracing the content in a processable markdown. 

Is there  *any* chance that something like this could fall into angular material's list of components? :S

**Comment by jelbourn** [comment]
Since this isn't something that's part of the Material Design spec, it's not something we'd want to add to Angular Material directly. We could potentially add supporting code for something similar in the cdk, but there's nothing like that on our roadmap currently.
