### ISSUE TITLE
Sidenav animation and routing 

### ISSUE THREAD

**Issue by MaxKorolkov** [angular/material2#1328]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

I'm using angular 2 material sidenav component with these settings:
`<md-sidenav #sidenav mode="side" [opened]="true">`
With these settings, menu using animation popup. It's good, but it's a problem when i using route navigation in my app. It's not normal for permanent use. Sidenav should not be animated, when i turn to route component.
#### What is the current behavior?

Sidenav animate, when i turn to route component.
#### What are the steps to reproduce?

Maybe remove this behavior or make the property.
Best behavior sidenav on this site - https://justindujardin.github.io
Sidenav animate on the first vision and toggle, and not animate when using menu buttons.
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.0.0 RC7, Angular2 Material 2.0.0 alpha.8-2, Windows 10, Chrome 53.

**Comment by AnasSharif** [comment]
<md-sidenav-layout fullscreen>
<md-sidenav #sidenav mode="push" >
<md-nav-list>
<a md-list-item routerLink="notes" (click)='sidenav.close()' >
<md-icon md-list-icon>palette</md-icon>
<span md-line>Notes</span>
</a>
<a md-list-item routerLink="reminders" (click)='sidenav.close()' >
<md-icon md-list-icon>palette</md-icon>
<span md-line>Notes</span>
</a>
</md-nav-list>
</md-sidenav>
<md-toolbar >
<button md-icon-button (click)='sidenav.toggle()' >
 <md-icon>menu</md-icon>
</button>
<b>{{title}}</b>note
</md-toolbar>
<router-outlet></router-outlet>
<md-sidenav-layout>

MaxKorolkov  try this method my routerlink with animation perfect

**Comment by AnasSharif** [comment]
`<md-sidenav-layout fullscreen>
<md-sidenav #sidenav mode="push" >
<md-nav-list>
<a md-list-item routerLink="notes" (click)='sidenav.close()' >
<md-icon md-list-icon>palette</md-icon>
<span md-line>Notes</span>
</a>
<a md-list-item routerLink="reminders" (click)='sidenav.close()' >
<md-icon md-list-icon>palette</md-icon>
<span md-line>Notes</span>
</a>
</md-nav-list>
</md-sidenav>
<md-toolbar >
<button md-icon-button (click)='sidenav.toggle()' >
 <md-icon>menu</md-icon>
</button>
<b>{{title}}</b>note
</md-toolbar>
<router-outlet></router-outlet>
<md-sidenav-layout>`

try this method

**Comment by mmalerba** [comment]
If this is still an issue can you file a new bug with a plunker to reproduce?

**Comment by MiguelAngelLV** [comment]
I have the same problem with Angular 4.2.4 and Material 2.0.0-beta.7
