### ISSUE TITLE
Material Docs/ Mat Table HTTP Example, pageSize not working

### ISSUE THREAD

**Issue by andy-dev** [angular/material2#13281]
#### Bug, feature request, or proposal:
BUG.

#### What is the expected behavior?
Changing the pageSize input should render a table with the number of rows being = to those given as an input.

#### What is the current behavior?
Displays the same # of rows even when changing pageSize input

#### What are the steps to reproduce?
Open the mat-table http example. Change the pageSize input, table renders the same. Similar,  pageSizeOptions input does not change the number of rows displayed

https://stackblitz.com/angular/ovmkryyyvdx?file=app%2Ftable-http-example.html

#### What is the use-case or motivation for changing an existing behavior?
Trying to implement this type of scenario, and got the same behavior with my own data provided to the table. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest, tested on chrome

**Comment by shivensinha4** [comment]
Adding the paginator to the page does not automatically configure the data that the table displays. We will have to link them via our own logic.

To display the appropriate data in the table, we have to obtain the current configuration of the paginator. Then, we need to pass the proper slice of data to the table to display.

How do we know the configuration (that is, the set page size and current index) of the paginator? Of course, the paginator tells us - via the `page` binding.

To store the configuration of the paginator, we may declare two variables in the component - 
```javascript
// MatPaginator Configuration Output
dataStart = 0;
dataEnd = this.pageSize;
```

We define a function to update these values when the paginator sends the event details.
```javascript
updateDisplayedData(event) {
  this.dataStart = event.pageIndex * event.pageSize;
  this.dataEnd = (event.pageIndex + 1) * event.pageSize;
}
```

And finally, pass the correct slice of data to the table.
```html
<table mat-table [dataSource]="data.slice(dataStart, dataEnd)" ...>
```

Here's the modified example of your code: [StackBlitz](https://stackblitz.com/edit/angular-42suom?file=app/table-http-example.html)
