### ISSUE TITLE
(bug) Unable to drag element out of TabContent @v7.0.0-beta.2

### ISSUE THREAD

**Issue by StickNitro** [angular/material2#13294]
#### What is the expected behavior?
With a `<div cdkDrag>...</div>` inside a `MatTabContent`, the expectation is that I can drag the div element anywhere on the page, the `cdkDrag` element remains constrained within the container.  In the StackBlitz below the 'cog' is constrained within the `TabContent` and the 'Drag ME!' is constrained within the `<material-app>` component.

#### What is the current behavior?
Current behaviour with the above is when dragging, the element disappears in overflowed areas, and when dropped is positioned within the `TabContent`

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

StackBlitz can be found here: https://stackblitz.com/edit/angular-material2-issue-ca2rhn

* Drag the cog image and notice that it remains constrained within the element of the `TabContent`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: v6.1.1
Material and CDK: v7.0.0-beta.2
Typescript: v2.7.2
Chrome and Safari
MacOS

**Comment by crisbeto** [comment]
The `drag-drop` module only makes the element draggable, but it doesn't account for things like `overflow: auto` which the tabs have. Closing since supporting such cases would be impractical.
