### ISSUE TITLE
Descenders cut off in form fields

### ISSUE THREAD

**Issue by calebegg** [angular/material2#13293]
The line height for `<input>` elements causes descenders to be cut off on Chrome/Linux with Roboto and the default body font size of 14px.

https://stackblitz.com/edit/angular-material2-issue-zbibdi

![image](https://user-images.githubusercontent.com/782920/45959567-33f7dd00-bfe8-11e8-8113-4e8d22257e9b.png)

**Comment by SchnWalter** [comment]
Dup of #9738

**Comment by calebegg** [comment]
Dang, not sure how I missed that.
