### ISSUE TITLE
Styles in snackBar open from component

### ISSUE THREAD

**Issue by Aw3same** [angular/material2#13300]
#### Bug, feature request, or proposal:
I'm looking for a way to do the following: to show notifications, I want to implement a custom SnackBar. I followed the official doc and I created a simple Snackbar, with some custom configuration. 
    
    this.snackBar.open('Message one', 'OK', configSuccess);
    
    export const configSuccess: MatSnackBarConfig = {
      panelClass: 'style-success',
      duration: 10000,
      horizontalPosition: 'left',
      verticalPosition: 'bottom'
    };

This works fine, but I want a different display in my SnackBar (specifically send data and display two buttons, similar to gmail). Following the docs, I create a component and open my SnackBar from it :

    /*...*/    
    this.snackBar.openFromComponent(SnackbarMessageComponent, {
                  data: 'Message one',
                });
    /*...*/
    
    @Component({
      selector: 'app-snackbar-message',
      templateUrl: './snackbar-message.component.html',
      styleUrls: ['./snackbar-message.component.scss']
    })
    export class SnackbarMessageComponent implements OnInit {
    
      constructor(@Inject(MAT_SNACK_BAR_DATA) public data: any) { }
    
      ngOnInit() {
      }

All ok, but now I have a problem. I want to pass to this new SnackBar the config that I defined before (`config Success` for example), but in the official docs and Google I didn't find anything. 

Is there any way to do it without having to define it globally? Can someone guide me or tell me where to go? Thanks in advance!

#### What is the expected behavior?
Pass info and styles to custom snackbar

#### What is the current behavior?
I have to choose between styles or data

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 6.1.8
material 6.4.7
TS 2.9.2

**Comment by shivensinha4** [comment]
You can provide the styles as well to the `openFromComponent` function, as so -

```javascript
this.snackBar.openFromComponent(SnackbarMessageComponent, {
  data: 'Message one',
  ...this.configSuccess
});
```
Here's the working example: [StackBlitz](https://stackblitz.com/edit/angular-m2nc51?file=app/snack-bar-component-example.ts)

**Comment by Aw3same** [comment]
Very very thank you men, this works like a charm!
