### ISSUE TITLE
mat-select when selecting an option with SPACE key, animation breaks

### ISSUE THREAD

**Issue by jessemoon0** [angular/material2#13309]
### **Bug**, feature request, or proposal:
Bug: 

**Component presenting the bug**: <mat-select></mat-select>

When we use the **SPACE** key on the keyboard to select a focused value (we can change between values with arrows or with the mouse), it does a strange animation and doesn't close the mat-option window.

### What is the expected behavior?
To be able to choose the focused value, close the window

### What is the current behavior?
Makes a strange animation when selecting a value with the SPACE key.

### What are the steps to reproduce?
We can test it with the basic example in the material documentation. We paste it in a fully updated angular app. For some reason in stackblitz is working...

Here is the video of the bug: [Video](https://www.dropbox.com/s/56xspbsi014mmw6/Sep-25-2018%2016-33-08.mp4?dl=0)

### What is the use-case or motivation for changing an existing behavior?

Material Docs say we can manipulate the value with either SPACE or ENTER key

### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

**Material Version**: "@angular/material": "6.4.7"
**Angular Animations Version**: "@angular/animations": "6.1.8"

### Is there anything else we should know?

I copied and pasted the simplest implementation of the mat-select on my app (because I have a more complicated one in there), and presented this bug.

Thank you for the help!!

**Comment by crisbeto** [comment]
This can happen if the space/enter key is held down since the select reopens. We should block opening while the animation is running. That being said, selection should still work properly as it is now.

**Comment by jessemoon0** [comment]
> This can happen if the space/enter key is held down since the select reopens. We should block opening while the animation is running. That being said, selection should still work properly as it is now.

Should I pass the event in the selection and do event.preventDefault()?

**Comment by jessemoon0** [comment]
@crisbeto Thank you for the solution! I got it working by adding `(keydown)="$event.stopPropagation()"` in the `<mat-select>` tag. =D
