### ISSUE TITLE
mat-select option not selecting with particular JSON object key

### ISSUE THREAD

**Issue by naveensain93** [angular/material2#13302]
Hello,
I am giving Array Json object in mat-select for rendering dynamically options. When I am selecting a option then its not selecting json object key which I provide in value of option.

Here is the example:
(https://stackblitz.com/edit/angular-zkakjq-yzx2rm?embed=1&file=app/select-multiple-example.html)

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
