### ISSUE TITLE
How using Material Design Shape With AngularMaterial?

### ISSUE THREAD

**Issue by asmaa3107** [angular/material2#13318]
<div class="post-text" itemprop="text">

<p>Please I am Working on Project Using <strong>Angular Material (Angular v6)</strong> ,and  I need to use Angular <strong>shape</strong> on it check it from <strong>following Link:</strong></p>

<p><a href="https://material.io/design/shape/about-shape.html#shaping-material" rel="nofollow noreferrer">Material Shape</a></p>

<p>is this Possible?</p>
    </div>

**Comment by jelbourn** [comment]
This isn't supported at this time- it's something that will likely become available during 2019.

**Comment by joselcvarela** [comment]
Any plans on this?
