### ISSUE TITLE
matTooltip inconsistency on disabled buttons between browsers

### ISSUE THREAD

**Issue by Eddygn** [angular/material2#13320]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Tooltip consistent behavior between firefox and chrome, on disabled buttons and items inside buttons.

#### What is the current behavior?

A tooltip on disabled button:
```
<button mat-icon-button [disabled]="true" matTooltip="Disabled button">
    <mat-icon>info</mat-icon>
</button>
```
Will display on Firefox, but will not show on Chrome

Setting the tooltips on the icon inside the button will display on Chrome, regardless if the button enabled or disabled, but will not display on Firefox.

```
<button mat-icon-button >
        <mat-icon matTooltip="Active button">info</mat-icon>
</button>
<button mat-icon-button [disabled]="true">
        <mat-icon matTooltip="Disabled button">info</mat-icon>
</button>
```
#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-mthixj

#### What is the use-case or motivation for changing an existing behavior?

Need consistent tooltips on buttons, in my use case I need them on disabled buttons too. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6.1.8
Angular Material 6.4.7

Firefox 62.0.2
Chrome  69.0.3497.100

**Comment by crisbeto** [comment]
This is something that is up to the browser and we can't do too much about. We listen for mouse events to know when to show the tooltip. Some browsers won't dispatch the mouse events on disabled buttons.

**Comment by Eddygn** [comment]
Ah, no big deal then, I'll just wrap the buttons in something.

Thanks
