### ISSUE TITLE
Expansion panel (afterExpand)

### ISSUE THREAD

**Issue by Swoox** [angular/material2#13334]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I except the afterExpand to trigger an event on the Expansion  panel.

#### What is the use-case or motivation for changing an existing behavior?
In this [#12412](https://github.com/angular/material2/pull/12412) there was stated that there where two new output added afterExpand and afterCollapse. Now if I add these on my Expansion  panel the event won't get triggered.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.9.
Typescript 2.7
Materials 6.4.7

#### Is there anything else we should know?
Related [#12433](https://github.com/angular/material2/issues/12433)

**Comment by jelbourn** [comment]
@Swoox can you share a reproduction on stackblitz?

**Comment by klew582** [comment]
@jelbourn @Swoox I have been having this same problem. The (afterExpand) and (afterCollapse) events do not actually work. 

Here's a stackblitz that uses the demo code from the material repository(material2/src/demo-app/expansion/expansion-demo.html):

https://stackblitz.com/edit/angular-lo3ffq

**Comment by jelbourn** [comment]
Ah, this is because those events are new for v7. You can see the tags on the commit (f6b1002b286c134950256294478ab9ca15887536).

**Comment by klew582** [comment]
I see, any estimates on when v7 will be released?

**Comment by jelbourn** [comment]
By the end of October unless something unexpected comes up

**Comment by Swoox** [comment]
I tested it and it's working now cheers.
