### ISSUE TITLE
cannot find modules problems started after importing a card from https://material.angular.io/components/card/overview

### ISSUE THREAD

**Issue by Munodiwa** [angular/material2#13337]
#### Bug, feature request, or proposal:

ERROR in ../node_modules/@angular/cdk/a11y/typings/aria-describer/aria-describer.d.ts(1,53): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/a11y/typings/focus-monitor/focus-monitor.d.ts(9,71): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/a11y/typings/focus-monitor/focus-monitor.d.ts(10,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/a11y/typings/focus-trap/focus-trap.d.ts(1,74): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/a11y/typings/key-manager/list-key-manager.d.ts(8,27): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/a11y/typings/key-manager/list-key-manager.d.ts(9,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/a11y/typings/live-announcer/live-announcer-token.d.ts(8,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/a11y/typings/live-announcer/live-announcer.d.ts(9,57): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/accordion/typings/accordion-item.d.ts(8,60): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/accordion/typings/accordion.d.ts(1,53): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/accordion/typings/accordion.d.ts(2,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/bidi/typings/dir-document-token.d.ts(1,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/bidi/typings/dir.d.ts(8,59): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/bidi/typings/directionality.d.ts(8,41): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/collections/typings/array-data-source.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/collections/typings/collection-viewer.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/collections/typings/data-source.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/collections/typings/selection.d.ts(8,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/collections/typings/unique-selection-dispatcher.d.ts(8,27): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/layout/typings/breakpoints-observer.d.ts(8,35): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/layout/typings/breakpoints-observer.d.ts(10,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/observers/typings/observe-content.d.ts(1,79): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/observers/typings/observe-content.d.ts(2,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/overlay/typings/fullscreen-overlay-container.d.ts(8,27): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/keyboard/overlay-keyboard-dispatcher.d.ts(1,53): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/overlay-container.d.ts(1,53): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/overlay-directives.d.ts(9,126): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/overlay-module.d.ts(1,26): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/overlay-ref.d.ts(10,55): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/overlay-ref.d.ts(11,37): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/overlay/typings/overlay.d.ts(9,60): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/position/connected-position-strategy.d.ts(2,28): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/position/connected-position-strategy.d.ts(3,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/overlay/typings/position/flexible-connected-position-strategy.d.ts(9,28): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/position/flexible-connected-position-strategy.d.ts(12,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/overlay/typings/position/overlay-position-builder.d.ts(9,28): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/scroll/close-scroll-strategy.d.ts(8,24): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/scroll/reposition-scroll-strategy.d.ts(8,24): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/overlay/typings/scroll/scroll-strategy-options.d.ts(9,24): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/portal/typings/dom-portal-outlet.d.ts(8,99): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/portal/typings/portal-directives.d.ts(8,137): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/portal/typings/portal-injector.d.ts(8,26): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/portal/typings/portal.d.ts(8,100): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/scrolling/typings/scroll-dispatcher.d.ts(9,57): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/scrolling/typings/scroll-dispatcher.d.ts(10,42): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/scrolling/typings/scrollable.d.ts(8,55): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/scrolling/typings/scrollable.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/scrolling/typings/viewport-ruler.d.ts(9,45): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/scrolling/typings/viewport-ruler.d.ts(10,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/stepper/typings/step-label.d.ts(8,29): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/stepper/typings/stepper.d.ts(10,122): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/stepper/typings/stepper.d.ts(11,33): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/cdk/stepper/typings/stepper.d.ts(13,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/table/typings/cell.d.ts(8,41): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/table/typings/row.d.ts(8,134): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/table/typings/table.d.ts(9,150): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/table/typings/table.d.ts(10,45): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/text-field/typings/autofill.d.ts(9,69): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/text-field/typings/autofill.d.ts(10,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/text-field/typings/autosize.d.ts(1,71): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/tree/typings/control/base-tree-control.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/tree/typings/control/nested-tree-control.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/tree/typings/control/tree-control.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/cdk/tree/typings/nested-node.d.ts(8,85): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/tree/typings/node.d.ts(8,29): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/tree/typings/outlet.d.ts(8,34): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/tree/typings/padding.d.ts(9,50): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/tree/typings/tree.d.ts(10,166): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/cdk/tree/typings/tree.d.ts(11,54): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/autocomplete/typings/autocomplete-origin.d.ts(8,28): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/autocomplete/typings/autocomplete-trigger.d.ts(10,100): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/autocomplete/typings/autocomplete-trigger.d.ts(11,38): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/autocomplete/typings/autocomplete-trigger.d.ts(14,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/autocomplete/typings/autocomplete.d.ts(8,119): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/badge/typings/badge.d.ts(9,58): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/bottom-sheet/typings/bottom-sheet-config.d.ts(8,50): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/bottom-sheet/typings/bottom-sheet-container.d.ts(8,103): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/bottom-sheet/typings/bottom-sheet-ref.d.ts(8,26): error TS2307: Cannot find module '@angular/common'.
../node_modules/@angular/material/bottom-sheet/typings/bottom-sheet-ref.d.ts(10,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/bottom-sheet/typings/bottom-sheet.d.ts(3,39): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/bottom-sheet/typings/bottom-sheet.d.ts(4,26): error TS2307: Cannot find module '@angular/common'.
../node_modules/@angular/material/button-toggle/typings/button-toggle.d.ts(9,109): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/button-toggle/typings/button-toggle.d.ts(10,38): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/button/typings/button.d.ts(10,39): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/checkbox/typings/checkbox-config.d.ts(8,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/checkbox/typings/checkbox-required-validator.d.ts(8,26): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/checkbox/typings/checkbox-required-validator.d.ts(9,43): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/checkbox/typings/checkbox.d.ts(9,95): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/checkbox/typings/checkbox.d.ts(10,38): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/chips/typings/chip-default-options.d.ts(8,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/chips/typings/chip-input.d.ts(1,53): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/chips/typings/chip-list.d.ts(11,118): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/chips/typings/chip-list.d.ts(12,77): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/chips/typings/chip-list.d.ts(15,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/chips/typings/chip.d.ts(10,61): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/chips/typings/chip.d.ts(12,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/core/typings/common-behaviors/color.d.ts(9,28): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/core/typings/common-behaviors/common-module.d.ts(8,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/core/typings/common-behaviors/error-state.d.ts(10,55): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/core/typings/common-behaviors/error-state.d.ts(11,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/core/typings/common-behaviors/initialized.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/core/typings/datetime/date-adapter.d.ts(8,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/core/typings/datetime/date-adapter.d.ts(9,37): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/core/typings/datetime/date-formats.d.ts(8,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/core/typings/error/error-options.d.ts(1,57): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/core/typings/gestures/gesture-config.d.ts(8,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/core/typings/gestures/gesture-config.d.ts(9,37): error TS2307: Cannot find module '@angular/platform-browser'.
../node_modules/@angular/material/core/typings/label/label-options.d.ts(8,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/core/typings/line/line.d.ts(8,39): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/core/typings/option/option.d.ts(1,117): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/core/typings/option/option.d.ts(2,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/core/typings/ripple/ripple-renderer.d.ts(8,36): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/core/typings/ripple/ripple.d.ts(9,71): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/datepicker/typings/calendar-body.d.ts(8,50): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/datepicker/typings/calendar.d.ts(9,122): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/datepicker/typings/calendar.d.ts(11,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/datepicker/typings/datepicker-input.d.ts(1,53): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/datepicker/typings/datepicker-input.d.ts(2,84): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/datepicker/typings/datepicker-intl.d.ts(1,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/datepicker/typings/datepicker-toggle.d.ts(1,90): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/datepicker/typings/datepicker.d.ts(11,110): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/datepicker/typings/datepicker.d.ts(14,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/datepicker/typings/month-view.d.ts(1,67): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/datepicker/typings/multi-year-view.d.ts(1,67): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/datepicker/typings/year-view.d.ts(1,67): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/dialog/typings/dialog-config.d.ts(8,34): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/dialog/typings/dialog-container.d.ts(8,92): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/dialog/typings/dialog-content-directives.d.ts(8,62): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/dialog/typings/dialog-ref.d.ts(2,26): error TS2307: Cannot find module '@angular/common'.
../node_modules/@angular/material/dialog/typings/dialog-ref.d.ts(3,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/dialog/typings/dialog.d.ts(3,26): error TS2307: Cannot find module '@angular/common'.
../node_modules/@angular/material/dialog/typings/dialog.d.ts(4,55): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/dialog/typings/dialog.d.ts(5,37): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/expansion/typings/accordion-base.d.ts(8,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/expansion/typings/accordion.d.ts(8,45): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/expansion/typings/expansion-panel-content.d.ts(8,29): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/expansion/typings/expansion-panel-header.d.ts(9,58): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/expansion/typings/expansion-panel.d.ts(12,120): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/expansion/typings/expansion-panel.d.ts(13,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/form-field/typings/form-field-control.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/form-field/typings/form-field-control.d.ts(9,27): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/form-field/typings/form-field.d.ts(9,136): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/grid-list/typings/grid-list.d.ts(8,68): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/grid-list/typings/grid-tile.d.ts(8,57): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/icon/typings/icon-registry.d.ts(1,28): error TS2307: Cannot find module '@angular/common/http'.
../node_modules/@angular/material/icon/typings/icon-registry.d.ts(2,26): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/icon/typings/icon-registry.d.ts(3,57): error TS2307: Cannot find module '@angular/platform-browser'.
../node_modules/@angular/material/icon/typings/icon-registry.d.ts(4,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/icon/typings/icon.d.ts(1,62): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/input/typings/input-value-accessor.d.ts(8,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/input/typings/input.d.ts(2,75): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/input/typings/input.d.ts(3,55): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/input/typings/input.d.ts(6,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/list/typings/list.d.ts(8,57): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/list/typings/selection-list.d.ts(10,109): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/list/typings/selection-list.d.ts(12,38): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/menu/typings/menu-content.d.ts(8,110): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/menu/typings/menu-content.d.ts(9,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/menu/typings/menu-directive.d.ts(10,127): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/menu/typings/menu-directive.d.ts(11,37): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/menu/typings/menu-item.d.ts(9,39): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/menu/typings/menu-item.d.ts(11,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/menu/typings/menu-panel.d.ts(8,59): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/menu/typings/menu-trigger.d.ts(11,105): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/paginator/typings/paginator-intl.d.ts(8,26): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/paginator/typings/paginator-intl.d.ts(9,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/paginator/typings/paginator.d.ts(1,68): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/progress-bar/typings/progress-bar.d.ts(8,44): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/progress-spinner/typings/progress-spinner.d.ts(8,44): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/radio/typings/radio.d.ts(10,124): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/radio/typings/radio.d.ts(11,38): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/select/typings/select.d.ts(12,168): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/select/typings/select.d.ts(13,77): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/select/typings/select.d.ts(16,37): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/sidenav/typings/drawer.d.ts(13,155): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/sidenav/typings/drawer.d.ts(14,37): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/sidenav/typings/sidenav.d.ts(8,46): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/slide-toggle/typings/slide-toggle-config.d.ts(8,32): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/slide-toggle/typings/slide-toggle.d.ts(11,98): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/slide-toggle/typings/slide-toggle.d.ts(12,38): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/slider/typings/slider.d.ts(10,80): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/slider/typings/slider.d.ts(11,38): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/snack-bar/typings/snack-bar-config.d.ts(8,50): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/snack-bar/typings/snack-bar-container.d.ts(10,97): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/snack-bar/typings/snack-bar-container.d.ts(11,37): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/snack-bar/typings/snack-bar-ref.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/snack-bar/typings/snack-bar.d.ts(12,72): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/sort/typings/sort-header-intl.d.ts(8,26): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/sort/typings/sort-header-intl.d.ts(9,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/sort/typings/sort-header.d.ts(2,54): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/sort/typings/sort.d.ts(8,60): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/sort/typings/sort.d.ts(11,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/stepper/typings/step-header.d.ts(9,71): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/stepper/typings/stepper-icon.d.ts(8,29): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/stepper/typings/stepper-intl.d.ts(1,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/stepper/typings/stepper.d.ts(11,103): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/stepper/typings/stepper.d.ts(12,57): error TS2307: Cannot find module '@angular/forms'.
../node_modules/@angular/material/table/typings/cell.d.ts(8,28): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/table/typings/table-data-source.d.ts(2,47): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/tabs/typings/ink-bar.d.ts(8,52): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/tabs/typings/tab-body.d.ts(8,124): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/tabs/typings/tab-content.d.ts(8,29): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/tabs/typings/tab-group.d.ts(1,122): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/tabs/typings/tab-header.d.ts(10,122): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/tabs/typings/tab-label-wrapper.d.ts(8,28): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/tabs/typings/tab-nav-bar/tab-nav-bar.d.ts(11,116): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/tabs/typings/tab.d.ts(9,92): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/tabs/typings/tab.d.ts(11,25): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/toolbar/typings/toolbar.d.ts(8,54): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/tooltip/typings/tooltip.d.ts(14,100): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/tooltip/typings/tooltip.d.ts(15,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/tree/typings/data-source/flat-data-source.d.ts(10,45): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/tree/typings/data-source/nested-data-source.d.ts(9,45): error TS2307: Cannot find module 'rxjs'.
../node_modules/@angular/material/tree/typings/node.d.ts(9,85): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/tree/typings/outlet.d.ts(9,34): error TS2307: Cannot find module '@angular/core'.
../node_modules/@angular/material/typings/version.d.ts(8,25): error TS2307: Cannot find module '@angular/core'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trend-radar@0.0.0 build: `ng build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trend-radar@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin-Leer\AppData\Roaming\npm-cache\_logs\2018-09-27T11_14_03_591Z-debug.log
The terminal process terminated with exit code: 1

#### What is the expected behavior?
The project should build

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
