### ISSUE TITLE
Mat-dialog-actions not at the bottom

### ISSUE THREAD

**Issue by vinagreti** [angular/material2#13343]
**Bug, feature request, or proposal:**
Bug

**What is the expected behavior?**
Actions to be at the bottom of the dialog

**What is the current behavior?**
Actions right after content

**What are the steps to reproduce?**
StackBlitz starter: https://stackblitz.com/edit/angular-cuikyx

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**
angular@6.1.6, material@6.4.7, any browser and any OS

**Comment by vinagreti** [comment]
There is an issue since 2017 and nothing has been done. first mention was in #4609

**Comment by manklu** [comment]
Works for me in Edge, Firefox and Chrome

![image](https://user-images.githubusercontent.com/22273143/46189732-5c395180-c2f0-11e8-9619-e52eefc94691.png)

**Comment by vinagreti** [comment]
Works? I do not wee the actions at the bottom....

**Comment by vinagreti** [comment]
Dup #4609

**Comment by manklu** [comment]
@vinagreti Sorry, misunderstood ```at the bottom```
