### ISSUE TITLE
Dialog with flexible connection is out of boundry

### ISSUE THREAD

**Issue by rossanmol** [angular/material2#13347]
#### Bug, feature request, or proposal:

Not sure if this is a bug or a feature request:

When using position strategy with **flexibleConnectedTo**, the element connects only from two sides (top left / bottom right) of the element instead of all four sides.

#### What is the expected behavior?
Dialog starts from top and left of element position and expands to the bottom and right of the element.

#### What is the current behavior?
Dialog starts from top and left of element position, but expands to the bottom and right of the screen.

#### What are the steps to reproduce?
1. Open https://stackblitz.com/edit/angular-hw1mzw
2. Click on Show Dialog button

#### What is the use-case or motivation for changing an existing behavior?
The use case is represented in Stackblitz example.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest versions are affects as listed in Stackblitz example.

**Comment by crisbeto** [comment]
The connected position strategy isn't meant to be used for dialogs, but for things like dropdown menus and tooltips.
