### ISSUE TITLE
CdkDrop should be a Directive rather than a Component

### ISSUE THREAD

**Issue by josephperrott** [angular/material2#13341]
By using a directive rather than a component, the drop area can be easily added on to templating which is controlled by another component.

An example of would be in the `MatTable`/`CdkTable`:

Currently you must do the following for each column:
```html
<ng-container cdkColumnDef="position">
  <th cdk-header-cell *cdkHeaderCellDef>
    <cdk-drop [connectedTo]="drops">
      <span cdkDrag>No.</span>
    </cdk-drop>
  </th>
  <td cdk-cell *cdkCellDef="let element"> {{element.position}} </td>
</ng-container>
```
coupled with something in your components class to determine all of the drop zones.
```ts
@ViewChildren(CdkDrop) dropChildren: QueryList<CdkDrop>;
drops: CdkDrop[] = [];
ngAfterInit() {
  this.dropChildren.changes.subscribe(() => {
    this.drops = this.dropsChildren.toArray();
  });
  // Simple hack for quick example
  Promise.resolve().then(() => {
    this.drops = this.dropsChildren.toArray();
  });
}
```

By moving to using directives we can have the following:

```html
<ng-container cdkColumnDef="position">
  <th cdk-header-cell *cdkHeaderCellDef cdkDrag>No.</th>
  <td cdk-cell *cdkCellDef="let element"> {{element.position}} </td>
</ng-container>

<tr cdk-header-row *cdkHeaderRowDef="displayedColumns" cdkDrop></tr>
```

**Comment by crisbeto** [comment]
@josephperrott now I remember the primary reason why I made it a component, instead of a directive: we need a small set of structural styles for the dragging to work correctly. I made it a component so we can have those styles be included automatically together with the component.
