### ISSUE TITLE
mat-expansion-panel-header with static height in element.style

### ISSUE THREAD

**Issue by RnDMilenio3** [angular/material2#13354]
#### Bug, feature request, or proposal:
Mat-expansion-panel-header has a static height attribute defined in element.style

#### What is the expected behavior?
Possible to define height in the class "mat-expansion-panel-header"

#### What is the current behavior?
Static height on the mat-expansion-panel-header tag

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.1.7
Material: 6.4.7

**Comment by jelbourn** [comment]
For now the height it necessary for the animation. Closing as working-as-intended for now.
