### ISSUE TITLE
routerLink at tr level in MatTable should have native link behavior

### ISSUE THREAD

**Issue by loriepisicchio** [angular/material2#13350]
#### Bug, feature request, or proposal:
Bug (/Feature ?): routerLink defined at mat-table row level should open in new tabs on ctrl+click

#### What is the expected behavior?
I have defined a routerLink at tr level in a mat-table. When I click on a line of the table with ctrl+click, I expect the link to be opened in a new tab or window depending on the browser

#### What is the current behavior?
The link is opened in the same window

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-syj5ik

#### What is the use-case or motivation for changing an existing behavior?
We could implement this behavior with a custom event handler, but this would be nice to rely on native link features

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/cdk": "6.4.7",
    "@angular/core": "6.0.6",
    "@angular/http": "6.0.6",
    "@angular/forms": "6.0.6",
    "@angular/common": "6.0.6",
    "@angular/router": "6.0.6",
    "@angular/compiler": "6.0.6",
    "@angular/material": "6.4.7",

Tested on Chromium 67.0, Firefox 61.0

**Comment by jelbourn** [comment]
The current behavior doesn't really have anything to do with the table; this is the behavior of the `routerLink` directive from `@angular/router`. In general, the most accessible thing to do is to use a real `<a>` element inside of the table cells; this will cause shift+click and ctrl+click to work as expected while providing the right semantic structure for screen-reader users.
