### ISSUE TITLE
I want to add menu and dropdown list inside the menu. But when i click the dropdown the menu get closed, I have added (click)="$event.stopPropagation() to avoid closing, but then value does not change due to stopPropagation ?? Any Help ???

### ISSUE THREAD

**Issue by Rashid75** [angular/material2#13371]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by Newbie012** [comment]
Please edit your question so people will take you seriously...

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
