### ISSUE TITLE
Documentation with links to fragment identifer don’t work

### ISSUE THREAD

**Issue by paulferaud** [angular/material2#13388]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
On the page https://material.angular.io/components/input/overview, the links for:
* In some cases that `<mat-form-field>` may use the placeholder as the label (see the
[form field label documentation](https://material.angular.io/components/form-field/overview#floating-label)).
* In some cases that `<mat-form-field>` may use the placeholder as the label (see the
[form field label documentation](https://material.angular.io/components/form-field/overview#floating-label)).

Should link to:
* https://material.angular.io/components/form-field/overview#floating-label
* https://material.angular.io/components/form-field/overview#floating-label

#### What is the current behavior?
On the page https://material.angular.io/components/input/overview, the links generated point to (notice `input` rather than `form-field`):
* https://material.angular.io/components/input/overview#floating-label
* https://material.angular.io/components/input/overview#error-messages

Specifically, this is the "current page" + "fragment identifier".
In the actual generated html, the contents are:
* `<a href="/components/input/overview#floating-label" class="docs-markdown-a">form field label documentation</a>`
* `<a href="/components/input/overview#error-messages" class="docs-markdown-a">associate error messages</a>`

#### What are the steps to reproduce?
You can only see the issue on https://material.angular.io/components/input/overview. The github page hosted at https://github.com/angular/material2/blob/master/src/lib/input/input.md seems to work correctly.

#### What is the use-case or motivation for changing an existing behavior?
The link does not exist

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.4.7+ according to docuementation

#### Is there anything else we should know?
This seems like an issue when the markdown code is moved into https://material.angular.io. I believe the markdown detects the link is on the same domain, and somehow messes up the domain-relative link.

**Comment by jelbourn** [comment]
@DevVersion you had a fix for this, right?

**Comment by DevVersion** [comment]
@jelbourn Yeah, but it doesn't look like it has been published as part of the beta doc sites, right?

**Comment by jelbourn** [comment]
Right, it looks like it just hasn't been published yet.

**Comment by DevVersion** [comment]
Let's close this here because the bug _should_ be fixed and we already had https://github.com/angular/material.angular.io/issues/396

**Comment by jelbourn** [comment]
I just did a test deployment and it does work there:
https://material2-docs-dev.firebaseapp.com/components/autocomplete/overview#setting-separate-control-and-display-values

**Comment by paulferaud** [comment]
Thanks.

How do I know when angular/material.angular.io@ce75bac will get published? Just to double check. I have reason to believe the issue only happens on the actual `angular.io` domain.

**Comment by jelbourn** [comment]
We publish an update any time there's a release- the last few week's we've only published a beta/rc version, so the main material.angular.io hasn't been updated. At the very latest it will be updated when v7 lands.
