### ISSUE TITLE
Precisamos de uma biblioteca para PDF.

### ISSUE THREAD

**Issue by Heverton** [angular/material2#13385]
#### Bug, feature request, or proposal:
Biblioteca de recursos para PDF, sugiro https://mozilla.github.io/pdf.js/

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by kounelios13** [comment]
@Heverton please use english
