### ISSUE TITLE
<Removed due to code of conduct violation>

### ISSUE THREAD

**Issue by kd7yva** [angular/material2#1339]
<Removed due to code of conduct violation>

**Comment by hacknaked** [comment]
@kd7yva Feel free to hire best developers, build your own fantastic framework and shared it for free. Then, you'll probably still have to practice your PRESENTATION before go to a conf.

**Comment by JanStureNielsen** [comment]
@kd7yva - the issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details. 

This project is still in alpha and by using it you've agreed to comply with the CODE_OF_CONDUCT.md -- if you cannot uphold your obligations to the project, this project may not be right for you at this time.

**Comment by matticusfinch** [comment]
You're not alone, multiple developers on multiple environments at my work have tried the getting started guide and can't get past 
`npm install --save @angular/material`
Presenting an Alpha is not a good idea at all though.... Just chill and wait for things to be fixed. It will be worth it in the end. Wish I was talented enough to contribute.

**Comment by spock123** [comment]
For what it's worth - it works perfectly for me here (alpha 9)

**Comment by slmyers** [comment]
Sounds like poor planning on your part.

**Comment by spock123** [comment]
@kd7yva  which version did you try to install?

Remember that Alpha 9 dropped today, putting everything into one MaterialModule instead of many individual.. maybe that's the issue?

**Comment by spock123** [comment]
@matticusfinch  > 

- which version did you install?
- did you update the code to use MaterialModule?
- any error messages we can look at?
- any other hints you can give?

I'd like to help but it's difficult without any further details.. 

Cheers

**Comment by matticusfinch** [comment]
@spock123 honestly, thanks for the help, but it's probably not worth your time. I was just following directions on the [getting started guide](https://github.com/angular/material2/blob/master/GETTING_STARTED.md) and I received the below error: 
```
 npm install --save @angular/material

> node-zopfli@1.4.0 install C:\apps\MaterialPortal\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.6.0 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\apps\MaterialPortal\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\apps\MaterialPortal\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\apps\MaterialPortal\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\apps\\MaterialPortal\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\apps\\MaterialPortal\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=C:\\apps\\MaterialPortal\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64"
gyp ERR! cwd C:\apps\MaterialPortal\node_modules\node-zopfli
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\apps\MaterialPortal\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\apps\MaterialPortal\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\apps\MaterialPortal\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\apps\MaterialPortal\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\apps\\MaterialPortal\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\apps\MaterialPortal\node_modules\node-zopfli
node-pre-gyp ERR! node -v v6.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\apps\MaterialPortal\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\apps\MaterialPortal\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\apps\MaterialPortal\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
material-portal@0.0.0 C:\apps\MaterialPortal
+-- UNMET PEER DEPENDENCY @angular/common@2.0.0
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0
+-- @angular/material@2.0.0-alpha.9
`-- UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/common@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/platform-browser@2.0.1 but none was installed.
```

I'm on Node 6.6.0 and 3.10.3, but really, I can wait for the beta!

**Comment by joejordanbrown** [comment]
@matticusfinch 

If you go into your node_modules folder and look inside the @angular module can you see the material module?
> node_modules/@angular/material


If not what happens when you run the install command again?
> npm install --save @angular/material

**Comment by matticusfinch** [comment]
@joejordanbrown It's there, so maybe it's still installing fine even though it throws errors. Running the command a second time just throws the same errors again.

I can run NPM start and get the app works! message.

**Comment by ADominguezes** [comment]
Hello I'm having the same problem:

+-- UNMET PEER DEPENDENCY @angular/common@2.0.0                                                                                                                                                         
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0                                                                                                                                                       
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0                                                                                                                                                           
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0  

when I type npm install --save @angular2-material/core

I haven't got the folder material in node_modules/@angular

Running with node v6.5.0 and npm v3.10.3

**Comment by kd7yva** [comment]
For what it's worth, you guys took my comment way too seriously :)
I can see why though; re-reading it.  Sorry blokes.

My presentation highlighted how awesome the Angular Material Design Implementation is...

I presented on your Angular 1.x impl last year, and it was one of the best presentations of the conference.  My presentation this year was also on your NG 1.x version.

However, these days you can't present on NG without covering the same content for NG2.  I had to cover it.  So I showed the audience how to follow the instructions and create an app with Angular Material 2.  But when following the instructions from scratch in a new folder this morning in the presentation - 'ng serve' blew chunks.  I was surprised too.

Honestly, I was able to get everything you have released to work a couple days ago.  And in the end I showed my audience my few-day-old working version of angular material 2.  So they got to see it working.

Nice work you guys!!!  Everyone LOVES material design, especially the Angular impl.

I guess the only thing I hoped the project members would take from my issue was that it stinks that the getting started instructions didn't produce a something that runs.  After all, master is master - even on an Alpha project.

Aside from that - I apologize for offending you.  That wasn't my intent.

**Comment by joejordanbrown** [comment]
@matticusfinch 
It should work then, I've seen them errors a few times but still everything works fine.

Have you tried to use any of the material modules?
