### ISSUE TITLE
Question: being able to not have any tabs selected in mat-tab-group

### ISSUE THREAD

**Issue by mterczynski** [angular/material2#13403]
#### Bug, feature request, or proposal:
Question

#### What is the expected behavior?
Being able to not have any tabs selected in mat-tab-group when using [selectedIndex]="null" on mat-tab-group-element.

#### What is the current behavior?
There is always one tab selected even if you use input value [selectedIndex]="null".

**Comment by jelbourn** [comment]
The tabs are built such that one tab is always showing. You could use `ngIf` to hide the whole tab group if you want to show nothing.
