### ISSUE TITLE
Help on changing md-sidenav-content to width: 100%?

### ISSUE THREAD

**Issue by donjae** [angular/material2#1341]
Hi, I have a question on trying to make md-sidenav-content to have a width of 100%.
#### Bug, feature request, or proposal:

Md-Sidnav-Content width not modifiable, due to creation of md-sidenav-content tag on build/compiling. AKA, child elements cannot have 100% width of sidenav-content, when md-sidenav-content bases width on child element. 
#### What is the expected behavior?

md-sidenav-content needs to have `width: 100%;` or at least an option to. 
#### What is the current behavior?

md-sidenav-content width property is only specified when you have a fixed width length for the child content/element. Thus changing the width based on the child property.

BUT if you want the child element to take up the width of the full screen by 100%, it can't, because md-sidenav-content bases width on child element. 
#### What are the steps to reproduce?

Try changing property width property on md-sidenav-content to 100% through src files. Not possible, because it is only instantiated through compilation/build
#### What is the use-case or motivation for changing an existing behavior?

n/a (perhaps flexibility) 
#### Which versions of Angular, Material, OS, browsers are affected?

Latest (2.0 alpha 2.8)
#### Is there anything else we should know?

n/a

**Comment by souppower** [comment]
Adding fullscreen to your md-sidenav-layout might fix your problem, in case if you haven't figured it out yet.
See #1520 #759

**Comment by souppower** [comment]
@donjae Adding fullscreen to your md-sidenav-layout might fix your problem, in case if you haven't figured it out yet.
See #1520 #759

**Comment by souppower** [comment]
@donjae Adding fullscreen to your md-sidenav-layout might fix your problem, in case you haven't figured it out yet.
See #1520 #759

**Comment by donjae** [comment]
@souppower hmm, still not working. You mind giving an example of how you would implement the mixin?

**Comment by mmalerba** [comment]
Can you not just target the div with CSS?

md-sidenav-layout.my-sidenav-layout .md-sidenav-content {
  width: 100%;
}

**Comment by mmalerba** [comment]
#1966 adds an example of a fullscreen sidenav

**Comment by crosshopes** [comment]
Something I can't understand so far.
where there is a doc which explain that we can touch this .md-sidenav-content
I go through the official doc and never see this.
Does it exist a specification saying what we could use in term of Css properties?

Thx
