### ISSUE TITLE
Add option to disable tab animations

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#13428]
* Add an `@Input` to `mat-tab-group` to disable the animation
* Add a `MAT_TABS_OPTIONS` provider to configure it globally

**Comment by crisbeto** [comment]
@jelbourn for the most part this works already with the `@.disabled` binding (see https://stackblitz.com/edit/angular-gyxwjs), aside from the ink bar and ripples which are CSS based. Is this new binding supposed to disable everything or just the tab body animations?

**Comment by jelbourn** [comment]
@crisbeto just the tab body animation. My understanding is that using `@.disabled` will also disable all of the animations _within_ the tab, which users don't always want. 

Another option here would be to introduce an alternate animation that looks better on desktop with very wide tab bodies (though still probably allowing disabling it).

**Comment by crisbeto** [comment]
I see. In that case it would be better to introduce an input for the animation duration so people can also speed it up/slow it down, or set it to zero.

**Comment by leopardy** [comment]
What are valid values for animationDuration? I was trying to have no animation happen.

I used `<mat-tab-group mat-stretch-tabs [animationDuration]="0" id="tab-group">`

and received error
```
Unable to process animations due to the following failed trigger transitions
 @translateTab has failed due to:

- The provided timing value "0 cubic-bezier(0.35, 0, 0.25, 1)" is invalid.
```

I thought maybe I needed '0ms' but then I received `Parser Error: Unexpected token 'ms' at column 2 in [0ms]`

**Comment by crisbeto** [comment]
@leopardy it accepts a string. E.g. `animationDuration="100ms"` or `[animationDuration]="'100ms'"`.

**Comment by leopardy** [comment]
> @leopardy it accepts a string. E.g. `animationDuration="100ms"` or `[animationDuration]="'100ms'"`.

@crisbeto Thank you. Yes, silly me. This worked `[animationDuration]="'0ms'"`

**Comment by jelbourn** [comment]
@crisbeto we should probably make `0` by itself work
