### ISSUE TITLE
[mat-select]  Dropdown position below or above the component, instead of on top of it.

### ISSUE THREAD

**Issue by ukon1990** [angular/material2#13426]
#### Bug, feature request, or proposal:
This would be a feature request.

#### What is the expected behavior?
What I would like, is for the dropdown position to be below or above the component, instead of on top of it. This obviously depending on if the mat-select is on the bottom of the page or not. I think that this could be a parameter that you add to the mat-select.

(https://material.io/design/components/menus.html#exposed-dropdown-menu). I would expect, the select to have the same behavior as the dropdowns that you can see over there.

#### What is the current behavior?
The dropdown position is on top of the select. And I can't change it to be above or below. Like I can with, let's say: tooltips.

#### What are the steps to reproduce?
This is the default behavior. So you could just go to -> https://material.angular.io/components/select/overview

#### What is the use-case or motivation for changing an existing behavior?
Part of the motivation is that I and my customer think that it looks better that way.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All versions are affected. At least up to 6.4.7 of angular material and angular core && cli 6.1.9.

#### Is there anything else we should know?
No, I do not think so. it would have been fantastic, if you implemented this however.

**Comment by crisbeto** [comment]
Does the `disableOptionCentering` input do what you'd expect?

**Comment by ukon1990** [comment]
Wow, yeah. Can't believe that I missed it. Looked over the documentation for it several times.
It does indeed look like what we were looking for. Thank you for the reply @crisbeto !

Have a nice weekend.
