### ISSUE TITLE
Problem in install

### ISSUE THREAD

**Issue by tluanga** [angular/material2#1344]
im getting this error while installing please help

E:\development\code\maxi>npm install --save @material/core

> node-zopfli@1.4.0 install E:\development\code\maxi\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.6.0 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (E:\development\code\maxi\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at E:\development\code\maxi\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at E:\development\code\maxi\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\development\\code\\maxi\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\development\\code\\maxi\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=E:\\development\\code\\maxi\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64"
gyp ERR! cwd E:\development\code\maxi\node_modules\node-zopfli
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe E:\development\code\maxi\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\development\code\maxi\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=E:\development\code\maxi\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\development\code\maxi\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\development\\code\\maxi\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\development\code\maxi\node_modules\node-zopfli
node-pre-gyp ERR! node -v v6.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe E:\development\code\maxi\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\development\code\maxi\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=E:\development\code\maxi\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
maxi@0.0.0 E:\development\code\maxi
+-- UNMET PEER DEPENDENCY @angular/common@2.0.0
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0
`-- @material/core@2.0.0-dev.20160903

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/common@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/platform-browser@2.0.1 but none was installed.

E:\development\code\maxi>

**Comment by jelbourn** [comment]
It's `@angular/material`

**Comment by santhanam87** [comment]
@jelbourn I am getting same error, when I tried to install it today in my Windows 64 bit version.

npm install --save @angular/material                                                                                                                                                                        > node-zopfli@1.4.0 install C:\projects\angular_cli\timetrax_ui\node_modules\node-zopfli                                > node-pre-gyp install --fallback-to-build                                                                                                                                                                                                      node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz                                                                                                                       node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.3.1 (node-v48 ABI) (falling back to source compile with node-gyp)                                                                                               Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.             MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".                   gyp ERR! build error                                                                                                    gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1              gyp ERR! stack     at ChildProcess.onExit (C:\projects\angular_cli\timetrax_ui\node_modules\node-gyp\lib\build.js:276:23)                                                                                                                       gyp ERR! stack     at emitTwo (events.js:106:13)                                                                        gyp ERR! stack     at ChildProcess.emit (events.js:191:7)                                                               gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)                            gyp ERR! System Windows_NT 10.0.14393                                                                                   gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\projects\\angular_cli\\timetrax_ui\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\projects\\angular_cli\\timetrax_ui\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=C:\\projects\\angular_cli\\timetrax_ui\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64"                                                  gyp ERR! cwd C:\projects\angular_cli\timetrax_ui\node_modules\node-zopfli                                               gyp ERR! node -v v6.3.1                                                                                                 gyp ERR! node-gyp -v v3.4.0                                                                                             gyp ERR! not ok                                                                                                         node-pre-gyp ERR! build error                                                                                           node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\projects\angular_cli\timetrax_ui\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects\angular_cli\timetrax_ui\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\projects\angular_cli\timetrax_ui\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)                                                     node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\projects\angular_cli\timetrax_ui\node_modules\node-pre-gyp\lib\util\compile.js:83:29)                                                                                               node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)                                                               node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)                                                      node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)                                            node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)                    node-pre-gyp ERR! System Windows_NT 10.0.14393                                                                          node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\projects\\angular_cli\\timetrax_ui\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"                                                         node-pre-gyp ERR! cwd C:\projects\angular_cli\timetrax_ui\node_modules\node-zopfli                                      node-pre-gyp ERR! node -v v6.3.1                                                                                        node-pre-gyp ERR! node-pre-gyp -v v0.6.30                                                                               node-pre-gyp ERR! not ok                                                                                                Failed to execute 'C:\Program Files\nodejs\node.exe C:\projects\angular_cli\timetrax_ui\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects\angular_cli\timetrax_ui\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\projects\angular_cli\timetrax_ui\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)                                                                                    npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`                npm WARN install:node-zopfli@1.4.0 Exit status 1                                                                        timetrax-ui@0.0.0 C:\projects\angular_cli\timetrax_ui                                                                   +-- UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.5                                                                    +-- UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.5                                                                      +-- @angular/material@2.0.0-alpha.9                                                                                     +-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11                                                                            `-- UNMET PEER DEPENDENCY typescript@2.0.3                                                                                                                                                                                                      npm WARN optional Skipping failed optional dependency /chokidar/fsevents:                                               npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14                              npm WARN @angular/compiler-cli@0.5.0 requires a peer of typescript@^1.9.0-dev but none was installed.                   npm WARN @angular/compiler-cli@0.5.0 requires a peer of @angular/platform-server@^2.0.0-rc.5 but none was installed.    npm WARN @angular/core@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.                          npm WARN @angular/http@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.                          npm WARN @angular/material@2.0.0-alpha.9 requires a peer of @angular/core@^2.0.0 but none was installed.                npm WARN @angular/material@2.0.0-alpha.9 requires a peer of @angular/common@^2.0.0 but none was installed.              npm WARN @angular/router@3.0.0-rc.1 requires a peer of rxjs@5.0.0-beta.6 but none was installed.                        npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but none was installed.                    npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but none was installed.

**Comment by anroBL4CK** [comment]
Also getting this error on Linux Ubuntu 14.04 LTS.

**Comment by santhanam87** [comment]
Yeah, I tried it in Ubuntu 14 as well. Still I am getting the same error when we are installing Material.

**Comment by santhanam87** [comment]
Its not the problem in materiel, This url (https://github.com/nodejs/node-gyp) helped me a lot. Now it is installing fine for me. But Material team should keep a note about this dependency.
