### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by bigredpanda** [angular/material2#1346]
Hey guys, help me pls. I have the next error: [screen 1](http://screencloud.net/v/tgu6), [screen2](http://screencloud.net/v/qb8K)

**Comment by CDoughty08** [comment]
You need to change your systemjs config to import the ".umd.js" version of the code.
i.e.
`var materialPkgs = [
      'core',
      'button',
      'card',
      'toolbar',
      'progress-circle',
      'icon',
      'input',
      'sidenav',
      'list'
    ];

materialPkgs.forEach(function (matPkgName) {
      packages['@angular2-material/' + matPkgName] = { main: matPkgName + '.umd.js', defaultExtension: 'js', format: 'cjs' };                   
    });`
