### ISSUE TITLE
question: Can file upload input be part of angular material?

### ISSUE THREAD

**Issue by ptsydzik** [angular/material2#1347]
just question:
Did file upload input will be available in angular material? or its out of scope?

**Comment by jelbourn** [comment]
We don't have any plans to do a file upload presently.

**Comment by thibaultsavary** [comment]
You can use some tricks to make it look less ugly.
It seems to work on firefox.
On chrome the parent may be clicked to update the filename.
On edge, it doesn't work but [this is a known bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8282613/)

It's very likely that this kind of workaround will cause weird behaviors and issues but you can experiment in this direction if like me, you're forced to have a file input and you don't want it to be visually horrible.

For example, in a list:

```
</md-list>
  <md-list-item>
    <label md-mini-fab md-list-avatar>
      <md-icon>add</md-icon>
        <input #file type="file" [style.display]="'none'"> 
    </label>
    <h4 md-line><span>{{file.value}}</span></h4>
  </md-list-item>
<md-list>
```

**Comment by finalxcode** [comment]
i'm interested in this good idea.

**Comment by OnlyBelter** [comment]
We really need one, It is important for web-based websites! Could you please have a try???

**Comment by BamiGorengo** [comment]
@jelbourn kidding us? with "We don't have any plans to do a file upload presently." ?

**Comment by merlosy** [comment]
Hi,
If you really need one; I made a custom one (Angular 4.3.s and material look)
https://gist.github.com/merlosy/ab33dd7edaacfd92d6c9a5daea0a1240
Feedback is great !

**Comment by CharlieGreenman** [comment]
Just curious @josephperrott 

> As file uploads are not part of the material spec, there are not any plans to support file uploads whether via drag or input.

If someone from outside of Material were to make a pr, would it be accepted?

**Comment by merlosy** [comment]
Hi @CharlieGreenman, i made one actually. It has a material look and support for drop event is coming. Works with ng v6.
You can play with the demo as well.

https://github.com/merlosy/ngx-material-file-input

**Comment by CharlieGreenman** [comment]
@merlosy this looks fantastic. However, as  I'm sure you can understand how an enterprise would be reluctant to use your plugin. Primarily due to maintenance, future versions, and integrity of plugin.
