### ISSUE TITLE
mat-tabs: replace mat-ink-bar animated props with transform 

### ISSUE THREAD

**Issue by levgaas** [angular/material2#13472]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Replace `width / left` animated props of mat-ink-bar with `scaleX / translateX` to gain some performance.

The only caveat is border radius. Which user probably might want to customize

**Comment by crisbeto** [comment]
We tried doing this already through https://github.com/angular/material2/commit/63b6fd9fc30c7f8084a9e2e46c33fad4079976c7, but we had to revert it in https://github.com/angular/material2/pull/11661, because it was causing some other issues.

**Comment by levgaas** [comment]
@crisbeto Thanks for your response.

Unfortunately your implementation didn't work because `width: 1px` was used. And this had an impact on scale. If we do next steps things will work for us =)

- pick the tab with maximum width (`maxWidth`)
- set ink-bar width to `width: maxWidth`
- calculate `scaleX(${ currentTabWidth / maxWidth }px)`. So our `scaleX` always be less than `1`

Tested on Chrome / Firefox.

Video is attached to make it more visible https://youtu.be/s_-tn1THjoM

cc.@andrewseguin

**Comment by crisbeto** [comment]
Having to measure all the tabs in order to find the largest one sort of defeats the purpose since it'll trigger even more style recalculations. This is something that we'd have to do whenever the content of any of the tabs changes or when the window is resized.

**Comment by levgaas** [comment]
@crisbeto true. 

My point is that to achieve this goal we need to ensure that `scaleX` is less than `1`.
I just made an assumption that tab width won't never be more that `1000px` width. 

And it works
In any case it is something to keep in mind
