### ISSUE TITLE
cdk-drag-drop connected sorting example stackblitz is broken

### ISSUE THREAD

**Issue by PaulIvanov** [angular/material2#13495]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
should be functionally equivalent to the material.angular.io docs

#### What is the current behavior?
currently throws template parse errors in the stackblitz example

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/angular/lpkobqdlppp

**Comment by crisbeto** [comment]
Looks like the `DragDropModule` isn't imported. @DevVersion should this be fixed once https://github.com/angular/material.angular.io/commit/360393fc19b96cf76e0d88855492a61428816eb8 is released?

**Comment by DevVersion** [comment]
@crisbeto Yeah should be fixed once the fix is published with a new docs version.
