### ISSUE TITLE
Matsnackbar politeness config doesn't work with openFromComponent

### ISSUE THREAD

**Issue by bsteffl** [angular/material2#13494]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Using `openFromComponent` to create a custom toast doesn't allow you to use politeness config.

#### What is the current behavior?
Using politeness config doesn't seem to update with openFromComponent.  
![image](https://user-images.githubusercontent.com/10760551/46630308-7b628b00-cb09-11e8-9c03-91b422e6993c.png)  

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
If you change the politeness values, notice the custom toast one doesn't update but the default toast one does.
Custom Toast: https://stackblitz.com/edit/angular-4xj5hs-xntn4j
compared to Default Toast: https://stackblitz.com/edit/angular-mk9q97

#### What is the use-case or motivation for changing an existing behavior?
API isn't working correctly.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.0, Material 6.4.2

**Comment by crisbeto** [comment]
The politeness doesn't change, because you haven't set an `announcementMessage`, which means that the live announcer won't be called.
