### ISSUE TITLE
Mobile Swipe Gestures block Vertical Scroll

### ISSUE THREAD

**Issue by gtsopour** [angular/material2#13490]
#### Bug, feature request, or proposal:
Just by defining the following, vertical scroll over this div is lost.

```
<div (swipeleft)="onSwipeLeft()" (swiperight)="onSwipeRight()">
CONTENT
</div>
```

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by jelbourn** [comment]
Not related to Angular Material.
