### ISSUE TITLE
MatSidenav bug with nativeElement.scrolIntoView with smooth scroll

### ISSUE THREAD

**Issue by corinna000** [angular/material2#13491]
#### Bug, feature request, or proposal:
When:
1. Using Chrome
2. With matSidenav
3. With nativeElement.scrollIntoView with smooth scrolling

Then after triggering the scrollIntoView, the sidenav gets translated about 50% offscreen. 

#### What is the expected behavior?
The sidenav panel should not shift after smooth scrolling to a child element

#### What is the current behavior?
The sidenav panel shifts after smooth scrolling to a child element

#### What are the steps to reproduce?
Use Chrome (reported on Chrome 69 on Mac)
https://stackblitz.com/edit/angular-material2-issue-slhmfx

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6
Material 6.4.1

#### Is there anything else we should know?
Related to #9757 

The workaround is to not use smooth scrolling with `scrollIntoView()`

**Comment by manklu** [comment]
It seems that this is your problem: https://bugs.chromium.org/p/chromium/issues/detail?id=766319

**Comment by corinna000** [comment]
Yes, that seems like the issue exactly! In that case, I'll close this and hope that Chrome fixes this eventually.
