### ISSUE TITLE
CDK drag and drop - z-order, dragged element (div) "goes under" another and is not draggable anymore

### ISSUE THREAD

**Issue by antimagnes** [angular/material2#13510]
#### Bug, feature request, or proposal:

I try to implement a timeline using angular. I have a div with fxLayout column. Inside this div i have the timeline divs, and inside those with position: absolute the events, which are also divs. If I make the event divs draggable using cdkDrag and drag them, anything dragged from an upper timeline div will go under the timelines below (e.g. if I drag an event from the second line it goes under timeline 3, 4, 5 etc, but not 1 and 2). I tried to mess around with the z-index but to no avail.

#### What is the expected behavior?

The dragged element drags over the other elements

#### What is the current behavior?

The dragged element goes under other elements.

On the official docs site (this is what I mean https://beta-angular-material-io.firebaseapp.com/cdk/drag-drop/overview) I also noticed that if I drag the rectangle from "Basic Drag&Drop" over the "View source" and "Edit in StackBlitz" buttons of the "Basic Drag&Drop" box, than those are covered, but if I drag further down the site e.g. to the box "Drag&Drop sorting" the two button are over the rectangle.

#### What are the steps to reproduce?
see in current behvaiour

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.0.0-rc.1

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/3868367/46670769-62261100-cbd3-11e8-86d3-64f4fad6f84b.png)
![image](https://user-images.githubusercontent.com/3868367/46670884-add8ba80-cbd3-11e8-8645-a234bb19a4f9.png)

**Comment by crisbeto** [comment]
The CDK only moves the element around using a `transform`. It won't add a `z-index` since we'd have to make some assumptions about how much the `z-index` is supposed to be. Usually it's up to you to do the styling in order for it to fit within your layout.
