### ISSUE TITLE
MatSelectionList steals focus when selection options are removed.

### ISSUE THREAD

**Issue by simon-bar** [angular/material2#13528]
#### Bug, feature request, or proposal:

I think it could be considered a bug, but I would classify it as a feature request: adding a configuration option to control the _keyManager's behavior, or at least its skipPredicate:

https://github.com/angular/material2/blob/master/src/lib/list/selection-list.ts#L341

#### What is the expected behavior?

The list shouldn't steal focus whenever it wants.

#### What is the current behavior?

I modify the contents of the list based on an input the user is filling in. The list focuses its elements and it is impossible for the user to continue typing. Setting up the skipPredicate with childComponent._keyManager.skipPredicate(() => true) allowed me to hack out the desired behavior.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Is there anything else we should know?

If relevant, I can handle coding it up :)

**Comment by crisbeto** [comment]
@simon-bar it'll be fixed by #13531. You should keep in mind that setting the `skipPredicate` to `() => true` will disable the arrow key controls for the list completely.

**Comment by simon-bar** [comment]
Yes I know, but this was the best temporary workaround I could come up with ;)
Thanks for fixing it so quickly!

**Comment by crisbeto** [comment]
Fixed by https://github.com/angular/material2/commit/2c4c5ba8be0366589180127deb5bdc1103ae734e.
