### ISSUE TITLE
Alpha 9: 'md-button' is not a known element

### ISSUE THREAD

**Issue by jrosseel** [angular/material2#1352]
Hi everyone,

I encountered a bug while upgrading to the new version of material. 

In my main and library modules, I removed all imports of the different material modules I use and replaced them with the single import of MaterialModule.forRoot().

However, when I now load my app I get the following error: 'md-button' is not a known element. This makes me think there is something wrong with the import. Any thoughts?

![image](https://cloud.githubusercontent.com/assets/3729474/18914871/22e425ae-858f-11e6-8021-bf0ce67d87c4.png)

**Comment by SamiAl90** [comment]
You only call MaterialModule.forRoot() in your appmodule. Every other module must import MaterialModule but without forRoot().

**Comment by jrosseel** [comment]
Thanks for the feedback. I did that but it didn't solve the problem. Fixed it now. <md-button></md-button> is apparantly no longer a directive. Changing it to <div md-button></div> fixed the problem.

**Comment by SamiAl90** [comment]
Oh didn't know that it was always that way. Been using it always that way
<button md-button>Bla</button>
