### ISSUE TITLE
When multiple dialogs are open, closing one restores Focus to the parent instead of the next dialog in the stack

### ISSUE THREAD

**Issue by dankaste** [angular/material2#13535]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I would expect the next dialog to get focus.

#### What is the current behavior?
The parent element get focus

#### What are the steps to reproduce?
Our case is if we have a dialog open and some event happens that wants to replace the currently shown dialog with a new one we will close the current dialog using the dialogRef and then open the new one.
What we see is the new dialog getting focus and then after a short delay you see the dialog lose focus and the parent restores focus to the last element that had it. I assume this happens because in some cases the animation for opening the new dialog finishes before the closing animation finishes.

I've created a stackblitz that isn't our exact case but it exaggerates what I believe our root issue is.

https://stackblitz.com/edit/multi-dialog-restorefocus

#### What is the use-case or motivation for changing an existing behavior?
In our case the dialogs that are open have the backdrop up to prevent the user from performing an action on the screen behind the dialogs. The current behavior allows the user to tab around on the screen behind the dialog and perform invalid operations.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I would assume all but we are using:
-Angular 6.07
-Material 6.3.1 (also tested with 6.4.7)
-Typescript 2.72
-OSX (Haven't confirmed but we suspect this is also root for some issues we are seeing on iOS)
-Chrome

**Comment by crisbeto** [comment]
The logic behind `MatDialog` is that each dialog tries to restore focus to the element that was focused before it was opened which is the correct behavior in the majority of cases. Since yours is a special case, you can use the `restoreFocus` option to disable focus restoration and then handle it yourself. You can get a hold of all the open dialogs from `MatDialog.openDialogs`.

**Comment by chenson42** [comment]
@crisbeto do you have any recommendations on how to work around the issue in angular 6?
