### ISSUE TITLE
MatTableDataSource: doesn't update data array if using .push or other methods

### ISSUE THREAD

**Issue by epelc** [angular/material2#13537]
#### Bug, feature request, or proposal:

Updating the underlying data on a `MatTableDataSource` must replace the entire array in order to trigger a table update(internal observable).

https://github.com/angular/material2/blob/b8c1024a09f89eab39a213fe13f47d529dccdd74/src/lib/table/table-data-source.ts#L63

#### What is the expected behavior?
Array methods on `data` should either update the internal observable or this should be documented to prevent confusion.

#### What is the current behavior?

Using a method like `myDt.data.push(foo)` doesn't trigger the `set data` method which in turn ends up not updating the internal observable.

**Comment by manklu** [comment]
@epelc It's common in angular that no deep checks are done.

**Comment by epelc** [comment]
@manklu that's understood but using builting array methods to modify the array should be covered. Honestly I just think a warning that hey the data won't be updated unless you replace the entire array or call X new force update method.

I was left wondering what was wrong with my table for a bit when it wasn't rendering updates and this was an unexpected cause. Requiring people to understand setters and the internals of `MatTableDataSource` seems a bit much when a one line doc addition could warn you.

**Comment by jelbourn** [comment]
This is working as intended. The intent is to avoid potentially costly deep checks on complex objects. Angular itself has no way of knowing _how_ the array was modified.
