### ISSUE TITLE
update readme to alpha9

### ISSUE THREAD

**Issue by daniele-zurico** [angular/material2#1354]
#### request, or proposal:
the readme still say 8-2 but alpha9 has been released  the npm package to install has been changed and we don't need to include all the separate modules as well.

https://www.npmjs.com/package/@angular/material

<img width="414" alt="screen shot 2016-09-28 at 14 43 53" src="https://cloud.githubusercontent.com/assets/3193095/18915786/0478649a-858a-11e6-9a96-102622a3b2f3.png">

**Comment by dasois** [comment]
Just ignore, was already fixed with: #1340

**Comment by daniele-zurico** [comment]
Ah cool.iI think that it still has not been merged and by the way looking on your branch you didn't updated the big table on the readme file that show all the component. I think that all the community was waiting the dialog and now it's available ;)

**Comment by dasois** [comment]
Yeah I didn't finish when I saw that other pull request, thanks ;)

Am 28. September 2016 16:51:57 MESZ, schrieb Daniele Zurico <notifications@github.com>:
