### ISSUE TITLE
Radio button ripple effect 7.0.0-rc.1

### ISSUE THREAD

**Issue by timdeschryver** [angular/material2#13544]
#### Bug, feature request, or proposal:
Regression

#### What is the expected behavior?
I would expect it the radio button to hide it's ripple effect after the animation,
the same like like it did in v6.1 (or the same way like a checkbox).

#### What is the current behavior?

When you click on a radio button the ripple doesn't fade away until it loses focus.

![repro](https://user-images.githubusercontent.com/28659384/46759861-bb279f00-ccd0-11e8-9d34-ee81a6638be5.gif)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

It's visible on the beta website:
https://beta-angular-material-io.firebaseapp.com/components/radio/overview

Stackblitz link to the example:
https://stackblitz.com/angular/gaqjboybjao?file=app%2Fradio-overview-example.ts

#### What is the use-case or motivation for changing an existing behavior?
I noticed it while creating a new (v7.0.0-rc.1) project and thought this could be not intended. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: 7.0.0-rc.0
Material: 7.0.0-rc.1 (and also in 7.0.0-rc.0)

**Comment by jelbourn** [comment]
I believe this is intentional per the 2018 Material Design spec update. @crisbeto can you confirm?

**Comment by crisbeto** [comment]
It is intentional, but it's only supposed to be for keyboard and programmatic focus. We have PRs fixing something similar for `checkbox` and `slide-toggle`. I'll submit one for `radio` as well.

**Comment by timdeschryver** [comment]
Thanks for the quick response(s) 😄

**Comment by sivarama-subramanian** [comment]
> It is intentional, but it's only supposed to be for keyboard and programmatic focus. We have PRs fixing something similar for `checkbox` and `slide-toggle`. I'll submit one for `radio` as well.

mat-radio has been fixed
https://github.com/angular/material2/blob/76c2a3cea4da45fe952487460bf80a6bd55e4526/src/lib/radio/radio.scss#L156

mat-checkbox has also been fixed
https://github.com/angular/material2/blob/76c2a3cea4da45fe952487460bf80a6bd55e4526/src/lib/checkbox/checkbox.scss#L289

but it seems **slide-toggle has not been fixed** 
https://github.com/angular/material2/blob/76c2a3cea4da45fe952487460bf80a6bd55e4526/src/lib/slide-toggle/slide-toggle.scss#L213

@crisbeto please fix this
