### ISSUE TITLE
MatSelect opens to the wrong direction

### ISSUE THREAD

**Issue by eyalhakim** [angular/material2#13561]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When enough space exists on the bottom, the mat-select should open downwards.

#### What is the current behavior?
Opens upwards.

#### What are the steps to reproduce?

https://in-office.wekudo.com/experience/12/new/time

Click on the number 12 to see the bug.

**Comment by crisbeto** [comment]
`mat-select` tries to position the dropdown on top of the selected option. Since 12 is the last one, the panel has to open upwards. You can disable this behavior through the `disableOptionCentering` option.

**Comment by eyalhakim** [comment]
Thank you

**Comment by NitsanBaleli** [comment]
@crisbeto is there any plan to make this global by overriding a constant? adding this input to each and every select doesn't seem right.

thank you
