### ISSUE TITLE
Mat-Pagination doesn't update on language change

### ISSUE THREAD

**Issue by nhuurnink** [angular/material2#13566]
Hi,

I'm using the MatPaginatorIntl class to update my labels based on my preferred language.
However, when updating the labels after the component is already loaded (when user changes language), the grid is not re-rendered.

I can work around this by calling this.paginator._changePageSize(this.paginator.pageSize);
But there is no proper way to refresh the labels?

**Comment by crisbeto** [comment]
If you're updating the labels after init, you have to emit to the `changes` subject.

**Comment by josephperrott** [comment]
Closing as this is working as expected.  As noted above you will need to emit on the `changes` subject to notify components the labels have changed since initialization.
