### ISSUE TITLE
Add support for `color` attribute to mat-option

### ISSUE THREAD

**Issue by marslan390** [angular/material2#13568]
Add support for `color` attribute to mat-option

**Comment by Chan4077** [comment]
You can set the option's colour/color by setting the `color` input on `mat-select`.

**Comment by crisbeto** [comment]
Can you elaborate about the use case? The idea with `mat-option` is that it's supposed to match the color of its parent component.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
