### ISSUE TITLE
drag-drop: cdkDropEnterPredicate passed source drop region rather than destination

### ISSUE THREAD

**Issue by zeddic** [angular/material2#13577]
#### Bug, feature request, or proposal:
cdkDrop has a Input cdkDropEnterPredicate that lets a custom function be defined "to determine whether an item is allowed to be moved into a drop container." This function is called with both a CdkDrag and a CdkDrop as a parameter and must return a boolean. 

Currently the predicate is passed the item being dragged and the drop target that the item is coming from. The function is not supplied a reference to the drop target that is being tested. Both parameters are undocumented, so this could be intended behavior, but I did find it unexpected.

https://github.com/angular/material2/blob/master/src/cdk/drag-drop/drop.ts#L84

#### What is the expected behavior?
The enterPredicate is supplied with the item being dragged and the drop target being tested.

#### What is the current behavior?
The enterPredicate is supplied with the item being dragged and the drop target the item is coming from.

#### What are the steps to reproduce?
See:  https://stackblitz.com/edit/angular-material2-issue-38r2rw
Open the console in the preview. It will log the id of the drop target that is passed to the predicate check. Try dragging the block between different regions and note the drop target that is called for each check function.

#### What is the use-case or motivation for changing an existing behavior?
My first thought was that the enterPredicate would be supplied all the information it needed to make the decision as parameters so that a predicate function could be reused for multiple drop targets. Since it is not passed the drop target being tested, this requires you to create a new predicateFn for every drop target.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/cdk": "^7.0.0-rc.1",

**Comment by crisbeto** [comment]
Should've been fixed in master for a while now.
