### ISSUE TITLE
X timer(s) still in the queue._ error when mat-sidenav 'opened' input is true

### ISSUE THREAD

**Issue by IIFE** [angular/material2#13571]
#### Bug, feature request, or proposal:
**Bug**

#### What is the expected behavior?
Testing component with `mat-sidenav` and `[opened]=true` should run without **X timer(s) still in the queue._** error.

#### What is the current behavior?
Running a spec for a component that has `mat-sidenav` and `[opened]=true` produces **X timer(s) still in the queue._** error.

#### What are the steps to reproduce?
I have the following component:
```
<div>
  <mat-sidenav-container>
    <mat-sidenav [opened]="true" role="navigation">
      <mat-nav-list>
        <a mat-list-item routerLink="/auth/register">Register</a>
      </mat-nav-list>
    </mat-sidenav>

    <mat-sidenav-content>
      <router-outlet></router-outlet>
    </mat-sidenav-content>
  </mat-sidenav-container>
</div>
```

And the following spec:
```
import { fakeAsync, ComponentFixture, TestBed } from '@angular/core/testing';
import { NavbarComponent } from './navbar.component';
import { RouterTestingModule } from '@angular/router/testing';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { MatSidenavModule, MatListModule } from '@angular/material';

describe('NavbarComponent', () => {
  let component: NavbarComponent;
  let fixture: ComponentFixture<NavbarComponent>;

  beforeEach(fakeAsync(() => {
    TestBed.configureTestingModule({
      imports: [NoopAnimationsModule, MatSidenavModule, MatListModule, RouterTestingModule],
      declarations: [NavbarComponent]
    }).compileComponents();

    fixture = TestBed.createComponent(NavbarComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  }));

  it('should compile', () => {
    expect(component).toBeTruthy();
  });
});
```
I am using `jest` as the test framework. When I run `ng test` I get the following error on the above spec:
```
NavbarComponent › should compile

    3 timer(s) still in the queue.

      at ../../node_modules/zone.js/dist/fake-async-test.js:604:27
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:128:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/dist/zone.js:138:43)
      at Object.testBody.length (../../node_modules/jest-zone-patch/index.js:50:27)
```

However if I change the `opened` input of `mat-sidenav` from `true` to `false`, the test runs fine. I thought that importing the `NoopAnimationsModule` in the test would solve the issue, as I guess the timers are for the animation of opening the sidenav, but that doesn't solve the issue.

I can workaround the issue by binding the `opened` input to a variable and setting it to `false` from the test, but I'd like to know what exactly is causing the issue and if there is a better way to solve it.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using 6.1.0 for Angular, 6.4.7 for Material, and 2.9.2 for Typescript.

Thanks

**Comment by crisbeto** [comment]
It's due to the animations and importing the `NoopAnimationsModule` won't help because it only makes the animations instant, but the timers are still added. Closing the issue since we can't do much about it.
