### ISSUE TITLE
Nested mat menu blinks on iPad

### ISSUE THREAD

**Issue by RandomNonameDude** [angular/material2#13582]
#### Bug, feature request, or proposal:

Nested mat-menu blinks when it is opened for the first time on Safari, iPad.

#### What is the expected behavior?

It shouldn't blink at all.

#### What is the current behavior?

Nested menu blinks when you try to open it for the first time on iPad's Safari. When you open it for the second time, it doesn't blink.

#### What are the steps to reproduce?

You can see the behavior on the last example here: https://material.angular.io/components/menu/examples

#### What is the use-case or motivation for changing an existing behavior?

Better user experience.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

iPad, Safari 12.0.0, iOS 12.0.0

#### Is there anything else we should know?

Seems to work fine on desktop Safari or iPhone...

**Comment by crisbeto** [comment]
This is fixed in master where the menu has a different animation.
