### ISSUE TITLE
Im unable to install please help, i tried on 3 machines still getting the same result

### ISSUE THREAD

**Issue by tluanga** [angular/material2#1358]
![image](https://cloud.githubusercontent.com/assets/1406978/18925000/cb01edda-85cf-11e6-854e-8671d27159ba.png)

**Comment by sebfag** [comment]
Do you have python installed ?

**Comment by slmyers** [comment]
http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm 

I didn't read the whole thread, but it seems like this is a semi-common error. Hope this helps. 
p.s. if you can I'd recommend dual booting with ubuntu and running nvm, but that's just my preference.

**Comment by jelbourn** [comment]
Closing as unrelated to material.
