### ISSUE TITLE
CdkDialog afterClosed called twice on safari & edge

### ISSUE THREAD

**Issue by jpzwarte** [angular/material2#13585]
#### Bug, feature request, or proposal:
`afterClosed` is called twice after closing the dialog on Safari & Edge. It is *not* called twice on Chrome & FF.

#### What are the steps to reproduce?
See https://stackblitz.com/edit/angular-tqgsk7

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest *stable* CDK (6.4.7)

Works fine on Chrome & FF
Does not work on Safari & Edge

**Comment by jpzwarte** [comment]
cc @crisbeto

**Comment by crisbeto** [comment]
Since `afterClosed` depends on the animation callback, this might be caused by https://github.com/angular/angular/issues/24084.

**Comment by jpzwarte** [comment]
@crisbeto Right, thnx for the quick response!

Related question: what's the roadmap for `CdkDialog`? Will this replace the `MatDialog` implementation? I know of at least 2 companies which use `CdkDialog` in production atm.

**Comment by crisbeto** [comment]
cc @josephperrott

**Comment by jpzwarte** [comment]
Workaround for those having the same issue: `dialogRef.afterClosed().pipe(take(1)).subscribe(...)`
