### ISSUE TITLE
mat-toolbar overflow items

### ISSUE THREAD

**Issue by IIFE** [angular/material2#13590]
#### Bug, feature request, or proposal:
**More of a question than anything else.**

Is it possible to use `mat-toolbar` in a way where if the screen is resized, the toolbar resizes with it and any toolbar buttons/items that cannot fit on the screen are put in an overflow menu?

Something similar to the following, which is taken from https://material.io/design/components/app-bars-top.html

https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1KdAErO7UPreCyc_6PJWv78o-0XawHtAt%2Ftopappbars-behavior-nesting.mp4

I have tried the mechanism from https://stackblitz.com/edit/angular-v6xwte?file=src%2Fapp%2Fapp.component.html, however it only works if I know before runtime how many items will be on the toolbar, and decide how many items each media size can display. Instead, can `mat-toolbar` dynamically add toolbar items to an overflow section/menu while the screen is being resizing, or do I have to listen to the resize event, and calculate how many items can the toolbar display based on the current client width and the width of each toolbar item? Basically dividing the client width by the toolbar item width, and using the result as the total number of items that can fit the screen, with the rest being put in an overflow menu.

Thanks

**Comment by jelbourn** [comment]
There's nothing built-in that does this. The mat-toolbar isn't much more than a colored div.

**Comment by tmtron** [comment]
such a feature would be great: is there anything planned to implement such a feature?
does anyone know existing 3rd party components that can do this?

**Comment by tmtron** [comment]
@IIFE did you find any solution - maybe 3rd party or open source lib?
