### ISSUE TITLE
Feature request md-toolbar fix position for header

### ISSUE THREAD

**Issue by 3mp3ri0r** [angular/material2#1359]
#### Bug, feature request, or proposal:

Feature request
#### What is the expected behavior?

Toolbar can be set to fix, so we can stick header (toolbar) in top of page.
#### What is the current behavior?

No feature for fix toolbar position
#### What is the use-case or motivation for changing an existing behavior?

Just want to create appbar like in android app that describe in google material layout.

**Comment by jelbourn** [comment]
Right now we don't have plans to support this as a part of tooolbar, since it's more of a layout concern.
