### ISSUE TITLE
dynamic cdkDropConnectedTo

### ISSUE THREAD

**Issue by beachjf** [angular/material2#13605]
#### Bug, feature request, or proposal:
cdk-drag-drop-connected-sorting

Actually, there seem to have no way to dynamically specify cdkDropConnectedTo elements.

Let's say I have a dynamic list of ROWS (cdkDrop)
Within each ROWS, we got Cells. (cdkDrag)

How can I move cells from a row to another without being able to dynamically specify cdkDropConnectedTo attribute?

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by crisbeto** [comment]
`cdkDropConnectedTo` can be set either to a reference to [a `CdkDrop` or the string `id` of a `CdkDrop`](https://github.com/angular/material2/blob/master/src/cdk/drag-drop/drop.ts#L62). You can assign unique IDs to your drop zones and connect them that way.

**Comment by bharathmuppa** [comment]
Above link is being linked to 404 page. Dynamic behavior of cdkDropConnectedTo  is not working properly.
`selectDraggableZones(groupId: string, type: string, index: number) {
    const droppableZone = [];
    for (let i = 0; i <= (index + 1); i++) {
      droppableZone.push(`${groupId}-${type}-${i}`);
    }
    return droppableZone;
  }`

above function has to allow item to dragged into all containers before it and one container after it. but unfortunately it is being dragged to other containers as well

**Comment by Spardevil** [comment]
Why is this issue closed ? I have a data-table, where in each row there is a drop list. I still can't set multiple drop zones.
