### ISSUE TITLE
Drag using requestAnimationFrame?

### ISSUE THREAD

**Issue by johncrim** [angular/material2#13606]
#### Bug, feature request, or proposal:
Proposal, or question for clarification on current design

#### What is the expected behavior?
I expect the new drag functionality in angular/material2 7.0 (currently in RC) to be as efficient as possible.

Looking at https://github.com/angular/material2/blob/master/src/cdk/drag-drop/drag.ts, I don't see a reference to `requestAnimationFrame` to perform the animation efficiently. I have not established for sure that this is a defect, but I would expect it to minimize the performance overhead. If this is by design (eg you know that the mouse move events don't occur at a higher frequency than the animation frame), then go ahead and resolve.

Certainly I can do some more work to evaluate whether I see any issues in current browsers, but I thought I'd raise this ASAP with the thought that it should be considered before releasing the RC.

#### What is the current behavior?
Looking at https://github.com/angular/material2/blob/master/src/cdk/drag-drop/drag.ts, I don't see a reference to `requestAnimationFrame` to perform the animation efficiently.

#### What are the steps to reproduce?
Here's an example from the article: https://stackblitz.com/edit/mat-drag-drop . I do see a spike in CPU in the Chrome profiler while drag/dropping, but I can't state without further testing that this is unreasonable.

#### What is the use-case or motivation for changing an existing behavior?
I think this should be considered before the RC is released, b/c releasing it and fixing it later could introduce a breaking change. If the answer is "we've considered this, but it's not an issue; using requestAnimationFrame won't help efficiency", that's fine.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0 RC1, Angular Material 7.0 RC1.

#### Is there anything else we should know?
I can't take credit for identifying this possible issue. I read this article + comment: https://medium.com/@asokolovski/nice-article-2f0ef6d0c924  , and decided I'd raise the issue.

**Comment by crisbeto** [comment]
Adding `requestAnimationFrame` won't make a difference because we don't animate anything with CSS. All animations are done using CSS and a `transform`.
