### ISSUE TITLE
Visual Style differences between 6 and 7

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#13625]
I've just installed the current rc.2 to see what the impact on visual styles will be on our existing applications. All buttons are displayed totally different, some elevation styles have been changed. Not sure what else.

Are you aware that customers in b2b will not accept when their application design changes? Especially not customers who have several angular 1 and 2 material design applications where layout and design have been made as similar as possible.

Are you aware of the costs for overwriting your style changes for development companies to keep the old design for their customers?

We're not talking about some todo lists. We're talking about enterprise business applications.

**Comment by jelbourn** [comment]
We know more than anyone the cost of updating applications- when we make changes like this, our team has to ensure that all of the applications inside Google update smoothly. 

We weighed the idea of supporting both styles for a time, but ultimately concluded:
* The majority of developers do want the most up-to-date Material Design visuals
* We can't support every visual variation indefinitely, so the old styles have to be removed _eventually_.
* The 2018 changes are relatively minor
* Supporting more than one set of styles would negatively impact payload size and make maintenance more difficult.
