### ISSUE TITLE
Not all chips in chip Input are selectable via keyboard arrows

### ISSUE THREAD

**Issue by mtotheoneandonlyk** [angular/material2#13627]
#### Bug, feature request, or proposal:
Not all chips in chip Input are selectable via keyboard arrows.

#### What is the expected behavior?
All chips in chip input are selectable via keyboard arrows.

#### What is the current behavior?
When at least 3 chips exist, the third chip is not selectable via arrow keys. Instead only the first two chips take turns.

#### What are the steps to reproduce?
Go to chip input with tab (or select the first chip with mouse) and navigate via arrow key (-->) to the third chip (or further when available).
Use StackBlitz/Example from Material doc: https://gaxpxeeookb.angular.stackblitz.io/ (with code here: https://stackblitz.com/angular/gaxpxeeookb?file=app%2Fchips-input-example.ts)

#### What is the use-case or motivation for changing an existing behavior?
Accessibility.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using latest (non beta) Material version 6.4.7

#### Is there anything else we should know?
Material is awesome! :)

**Comment by crisbeto** [comment]
This has been fixed by https://github.com/angular/material2/pull/12987.

**Comment by mtotheoneandonlyk** [comment]
Ok, seems like an fix is available in 7.0.0-beta.2 here: https://github.com/angular/material2/commit/959c827fe4908d45dd428a1c3141a2f28437a211
