### ISSUE TITLE
[Tabs] Inverted md-tabs style

### ISSUE THREAD

**Issue by anderflash** [angular/material2#1362]
#### Bug, feature request, or proposal:

Feature enhancement
#### What is the expected behavior?

I would like tabs with same background as toolbar when they are next to each other. We could switch background and color properties (it could be a new md-tabs property).  You see this style in [Google Material Design](https://material.google.com/components/tabs.html).
#### What is the current behavior?

Now md-tabs just has the option of change color (which changes text color and ink bar), instead of setting the background.
#### What are the steps to reproduce?

Not applicable
#### What is the use-case or motivation for changing an existing behavior?

More consistency between toolbar and tabs. Developer might choose between light (text color) and dark (background color) versions.
#### Which versions of Angular, Material, OS, browsers are affected?

Latest
#### Is there anything else we should know?

Just a `reverse-style="true"` attribute might work well.

**Comment by willshowell** [comment]
@andrewseguin thoughts on an API like this?

```html
<md-tab-group color="accent" background="primary">
  <md-tab label="Tab 1">Content 1</md-tab>
  <md-tab label="Tab 2">Content 2</md-tab>
</md-tab-group>
```

`[color]` set the inkbar and active tab-label color
`[background]` sets the tab-header color

When `[background]` is used, the tab-label color is overriden to be white

Related to #2908
