### ISSUE TITLE
Round button

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/material2#13626]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
new `mat-round-button` directive

#### What are the steps to reproduce?
[Material Crane button](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1h6OLc3XPy1ivhZRbPf5HJGoavpGngQXp%2Fbutton-crane-color.png) taken from [https://material.io/](https://material.io/)

#### What is the use-case or motivation for changing an existing behavior?
would be nice to have directive for out of the box rounded button like in the picture

**Comment by josephperrott** [comment]
The creation of this rounded button is from affordances in the Material spec for modifying shaping of components.  This rounding can be done by modifying the `border-radius` of the buttons which you can target using css styling.

As it is not part of the default spec, but rather a modification to the component, this is not something that we would create a component/directive for.
