### ISSUE TITLE
Removal of the empty first row of the datepicker including the month label

### ISSUE THREAD

**Issue by Tetrygon** [angular/material2#13631]
#### Bug, feature request, or proposal:
Remove the month label from the first row of the days in the datepicker calendar, or provide a way to hide it (along with the empty row that it takes up)

#### What is the use-case or motivation for changing an existing behavior?
The label is redundant due to the month already being displayed in the month-picker-area literally right above it. It also takes up a row of the calendar, which can be a landscape availability problem if trying to use mat-calendar as a standalone element. It also sits in the date area, when it is not a date...
![datepicker2](https://user-images.githubusercontent.com/18582872/47028143-bf234900-d136-11e8-9d07-53f69293e602.png)
![datepicker](https://user-images.githubusercontent.com/18582872/47028195-d6facd00-d136-11e8-8fa9-def685662803.png)

**Comment by jelbourn** [comment]
It's there because that area will eventually be scrollable (similar to the [AngularJS version](https://material.angularjs.org/latest/demo/datepicker)). The new cdk virtual-scroll stuff unblocks moving forward on that.
