### ISSUE TITLE
NO SPA

### ISSUE THREAD

**Issue by smile2014** [angular/material2#1364]
Hello,can you help me, I want to do a click on the menu, add a new TAB, rather than as it is now click menu routing switch, the middle area is changed, how to implement

**Comment by JanStureNielsen** [comment]
@smile2014 - the GitHub issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.

**Comment by smile2014** [comment]
@jelbourn  thank you
