### ISSUE TITLE
drag-drop: cdkDragHandle and cdkDrag are not working on projected content in a cdkDropList

### ISSUE THREAD

**Issue by philmtd** [angular/material2#13653]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
1. I expect to be able to make a draggable component and use a drag handler which is projected into this component.
2. I expect to be able to use `cdkDrag`, `cdkDragHandle` and `cdkDragRootElement` on a projected element in a component in combination with a `cdkDropList`

#### What is the current behavior?
1. The `cdkDrag` element does not seem to recognize the projected `cdkDragHandle` and makes the whole element draggable.
2. The `cdkDrag` element seems to recognize the `cdkDropList` but the `cdkDropList` does not find the draggable element as one of its children and thus throws an error when dragging an element:
`undefined is not an object (evaluating 'siblings[currentIndex].clientRect')`

#### What are the steps to reproduce?
StackBlitz for 1: https://stackblitz.com/edit/angular-material2-issue-drag-drop-1

Here I tried to make the `mat-expansion-panels` draggable inside the accordion using a wrapping div and the `mat-expansion-panel-header` as `cdkDragHandle`. Unfortunately the whole expansion panel (e.g. also the content) is draggable.

StackBlitz for 2: https://stackblitz.com/edit/angular-material2-issue-drag-drop-2

This is the same example as in 1 but trying to workaround the issue by using `cdkDrag` on the header combined with `cdkDragHandle` and `cdkDragRootElement`, which selects the containing div as the root element. Now only the header of the expansion panel is used as the drag handle (success!) and the `cdkDrag` seems to recognize that it belongs to a list, but the `cdkDropList` is not aware of the draggable elements and throws errors when trying to drag one of them.

Both these issues seem to appear because some of the directives are used on elements that are projected into other components (in this examples a mat-expansion-panel, but this will probably affect all components that allow content projection).

#### What is the use-case or motivation for changing an existing behavior?
To use drag and drop on more complex components with custom drag handles (where complex already describes a mat-expansion-panel) a fix for this bug is necessary. Components with projection are a basic feature of Angular which is also used in many Angular Material components and drag & drop should have support for this.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.0.0-rc.2

**Comment by crisbeto** [comment]
Currently only direct descendants can be used as handles. The issue will be fixed by https://github.com/angular/material2/pull/13360.

**Comment by philmtd** [comment]
Thanks, I didn't see that one! :)
