### ISSUE TITLE
[DataPicker] User can input value out of the range of min|max date in control

### ISSUE THREAD

**Issue by VitalyVrublevskyy** [angular/material2#13666]
Bug:
Datapicker have great support limitation of min/ max values when you select value via mouse in dropdown. In the same time user can input any date in textfield which is out of the range.  

#### What is the expected behavior?
* Input value should be limited to values in min / max range   

#### What is the current behavior?
* Internal ngModel value updated for value out of the range: 01/10/201. 

#### What are the steps to reproduce?
- set **min** and **max**  date for datapicker. (min as 01/01/2018, max: 01/12/2018)
- select from dropdown some date, like 01/10/2018
- put cursor in textinput and delete one symbol from year (01/10/201) 

#### Is there anything else we should know?
We don't have any support here:
https://github.com/angular/material2/blob/master/src/lib/datepicker/datepicker-input.ts#L322:L333

**Comment by manklu** [comment]
> Internal ngModel value updated for value out of the range: 01/10/201.

And is validated like any other form field.
https://stackblitz.com/edit/angular-hagly7?file=app/datepicker-min-max-example.ts

**Comment by VitalyVrublevskyy** [comment]
> And is validated like any other form field.
> https://stackblitz.com/edit/angular-hagly7?file=app/datepicker-min-max-example.ts

Correct. But main point isn't validation. Validation it's another aspect. 
In my particular case I have relation in components: like two datapickers (start / end date) and re-create onChange  appropriate text inputs count by months.  In this case I should limit programmatically  input users value into datapicker in some range via *min* and *max* property of data pickers.

**Comment by VitalyVrublevskyy** [comment]
> > Internal ngModel value updated for value out of the range: 01/10/201.
> 
> And is validated like any other form field.
> https://stackblitz.com/edit/angular-hagly7?file=app/datepicker-min-max-example.ts

Form validation works fine. However it is another aspect.
Issue is critical when you have bunch of related controls, and one of them handle changes of datapicker as '@Input'.  For example: handle changes of start and end date and base on diff in month create appropriate  amount of text inputs. In this case not so good to inject into component invalid date.

**Comment by mmalerba** [comment]
Our goal when implementing this component is to keep the behavior as close as possible to how Angular handles native fields like `type="number"`. Angular does not prevent users from typing values that are out of the range, it merely marks the value as invalid when they do. Therefore we do the same thing with the datepicker, by design

**Comment by VitalyVrublevskyy** [comment]
> Our goal when implementing this component is to keep the behavior as close as possible to how Angular handles native fields like `type="number"`. Angular does not prevent users from typing values that are out of the range, it merely marks the value as invalid when they do. Therefore we do the same thing with the datepicker, by design

@mmalerba Following up your example about native type="number". In the same time control prevent input invalid symbols except digits mask. 
So, it would be great to take into account *min* and  *max* property on user input as well.
I mean add similar if statement in case one of mentioned property provided into component:
https://github.com/angular/material2/blob/master/src/lib/datepicker/datepicker-input.ts#L327

**Comment by manklu** [comment]
> In the same time control prevent input invalid symbols except digits mask.

However, it doesn't prevent entering a value outside the min and max range. It's only validated.

https://stackblitz.com/edit/js-hzya2v?file=index.html
