### ISSUE TITLE
many 404 in material.angular.io

### ISSUE THREAD

**Issue by zh99998** [angular/material2#13678]
#### Bug, feature request, or proposal: bug

https://material.angular.io/components/categories/layout
![image](https://user-images.githubusercontent.com/359622/47200141-65758580-d3a7-11e8-8b4f-489b1342252f.png)

**Comment by josephperrott** [comment]
This is caused by our not having iconography for some of the components to show in the description cards.

This is being tracked in https://github.com/angular/material.angular.io/issues/463
