### ISSUE TITLE
Tree component can auto generate?

### ISSUE THREAD

**Issue by keyiis** [angular/material2#13677]
Now define tree component is too complex,i need manual dfine `treeControl,treeFlattener,treeDataSource......`.
### 1:should auto generate tree through define map field for data source,ex:
```
**way 1:flat data**
id,name,parent
**way 2:nest data**
id,name,children:[
{id,name,children:[...]}
]
```
### 2:add order support
ex:
`id,name,order,parent`

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
