### ISSUE TITLE
Shadow effect missing in some md-card presets.

### ISSUE THREAD

**Issue by ibraback** [angular/material2#1367]
I tested this card [component](https://github.com/angular/material2/blob/master/src/lib/card/README.md#preset-layouts) that exists in the docs, I noticed that there is a difference between what I saw in my browser and the screenshot describing it.

#### What is the expected behavior?
I expect the same behavior as described in the [screenshot](https://camo.githubusercontent.com/f0dcf37b18880da0fbbcac82b5218baa8b0d02d6/68747470733a2f2f6d6174657269616c2e616e67756c61726a732e6f72672f6d6174657269616c325f6173736574732f63617264732f6865616465722d636172642d6d696e2e706e67) available in the docs.

#### What is the current behavior?
No shadow effect on the borders of `<img>` tag and the `md-card-content`  preset inside the **_md-card_** tag.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.0.0 final
Material: 2.0.0-alpha.9
Browsers: Mozilla Firefox 49.0.1 x86 / Google Chrome 53
OS: Windows 10 x64

#### Is there anything else we should know?

Here is a screenshot where I compared two cards (tested in the environment conditions listed above):

![untitled](https://cloud.githubusercontent.com/assets/19997619/18951619/06118cf0-863e-11e6-9196-72aa658f66cd.png)

**Comment by sebfag** [comment]
You should try material alpha.9

**Comment by Ploppy3** [comment]
It is working for me.

**Comment by ibraback** [comment]
Sorry, I used Alpha 9 version of material in this test (I corrected it).
@Ploppy3 you just used that example in the docs without changing anything?

**Comment by Ploppy3** [comment]
@ibraback Here is [a working example](http://plnkr.co/edit/zaY2SY485BEQQuiHrhpK?p=preview). I only replaced the URL of the images provided in [the example of the documentation](https://github.com/angular/material2/blob/master/src/lib/card/README.md#preset-layouts).

**Comment by ibraback** [comment]
@Ploppy3 it's obvious that it is working in that link, but I don't think that the latest version of Angular is used in that sample, `import {bootstrap} from '@angular/platform-browser-dynamic';` in **app.component.ts** file is deprecated for example, maybe there is no bug in that version of Angular used in that example for the desired shadow effect behavior.

**Comment by Ploppy3** [comment]
@ibraback I just tested it on my project on angular-cli 1.0.0-beta.16 with material 2.0.0-alpha.9 and the shadows are working correctly.

**Comment by ibraback** [comment]
@Ploppy3 I used **angular-cli@1.0.0-beta.16** to create that project too.

**Comment by ibraback** [comment]
Sorry guys, that was a CSS problem ( `max-height`).
