### ISSUE TITLE
Mat menu using <a> with dynamic href

### ISSUE THREAD

**Issue by atolimbi** [angular/material2#13676]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

Assign the correct value to href attribute on tag <a> by calling the function getStringTemp() just one time

#### What is the current behavior?

href get returned correctly, however the function getStringTemp() gets called multiple times when opening the menu, but even other actions like hover (on the <a> tag using the function getStringTemp()) and closing the menu also call the function multiple times

#### What are the steps to reproduce?

```
Template code (HTML)
<mat-menu #appMenu="matMenu">
  <ng-template matMenuContent let-name="name">
    <a mat-menu-item [href]="getStringTemp()">Settings</a>
    <a mat-menu-item>Log off {{name}}</a>
  </ng-template>
</mat-menu>

<button mat-icon-button [matMenuTriggerFor]="appMenu" [matMenuTriggerData]="{name: 'Sally'}">
  <mat-icon>more_vert</mat-icon>
</button>

the function getStringTemp is just as simple as the one below:

getStringTemp(): string {
    console.log('Hola');
    return('Leonardo');
  }
```

#### What is the use-case or motivation for changing an existing behavior?

Is this a bug or is it supossed to work like this...I have not been able to identify the cause :S

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version is 6.1.1, typescript 2.9.2 and so far all browser behave the same

**Comment by jelbourn** [comment]
Angular generally makes no guarantees around how many times a binding will be evaluated.

**Comment by atolimbi** [comment]
@jelbourn Thank you very much for the answer
