### ISSUE TITLE
drag-drop: allow to select multi items to drag

### ISSUE THREAD

**Issue by devlfm** [angular/material2#13683]
#### feature
Add selection to cdk

#### What is the use-case or motivation for changing an existing behavior?
selection + sort + move

-----------------------------------------------

Hi guys, thank you very much for this big update!
What would be the best way to implement this feature?

Thanks!

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
