### ISSUE TITLE
matDatepicker setting locale not recognized if typing in input box

### ISSUE THREAD

**Issue by mappopo** [angular/material2#13682]
#### Bug, feature request, or proposal:
Bug, if setting a locale it works if the user select date from picker, but if he types inside the input box the date is not parsed in the right way. Eg: the Italian format is dd/mm/yyyy, if the user select March 31th,2018 in the box we get "31/03/2018" (it's ok) but if he types "31/03/2018" the date is not validate (but it is a valid Italian date). If he types "03/05/2018" we get March, 5th instead of May 3rd.

#### What is the expected behavior?
if the user insert 31/03/2018 the value must be validated and the value must be set to March 31th,2018
if the user insert 03/31/2018 the value must not be validatedand set to null

#### What is the current behavior?

if the user insert 31/03/2018 the value is not validated and set to null
if the user insert 03/31/2018  the value is validated and the value is set to March 31th,2018 and the content of the box automatically became 31/03/2018 when focus is lost

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-jzbpfb

#### What is the use-case or motivation for changing an existing behavior?
permit the user to use both input box and picker

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Curren versions of Angular, Material,
Firefox, Chorme, edge, windows 10
Maybe also other versions

**Comment by manklu** [comment]
Use MomentDateAdapter for better NLS support.

https://stackblitz.com/edit/angular-material2-issue-dfaxq5?file=app/app.module.ts

**Comment by mappopo** [comment]
manklu, I can not find any difference in the beahviour of https://stackblitz.com/edit/angular-material2-issue-dfaxq5?file=app/app.module.ts

If I am not wrong, it is an issue of angular-material to be solved. But I will appreciate any workaround.

**Comment by mmalerba** [comment]
There is an issue with Angular on stackblitz where overriding the providers doesn't seem to work right: https://github.com/angular/material2/issues/9780 these broken demos look like probably a result of that bug

**Comment by manklu** [comment]
@mmalerba Luckily you only need to import the locale in main.ts

https://stackblitz.com/edit/angular-material2-issue-dfaxq5?file=main.ts

**Comment by mappopo** [comment]
@manklu  thanks for the workaround.
@mmalerba the problem was not originarly in stackblitz, but in a project of mine. Is it mandatory to use Moment as suggested by manklu?

**Comment by mmalerba** [comment]
You don't have to use Moment, but the `NativeDateAdapter` doesn't handle dd/mm/yyyy format. You could create your own adapter by extending the `NativeDateAdapter` and overriding the `parse` and `format` methods
