### ISSUE TITLE
mat-select strange behavior on alt + arrow_key when panel open

### ISSUE THREAD

**Issue by nokiiam** [angular/material2#13684]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

mat-select should have the same behavior as select when the pannel is open which is to :
On alt+down the last option in his option list must be set active
On alt+up the first option in his option list must be set active

#### What is the current behavior?

when the panel is open alt+down and alt+up close the panel

#### What are the steps to reproduce?

this behavior can be tested on https://material.angular.io/components/select/overview

#### What is the use-case or motivation for changing an existing behavior?

the intent of the source code was to match the behavior of  select

> // Close the select on ALT + arrow key to match the native \<select\>

but it's not the behavior of select and the real behavior of select is useful to rapidly go to the top or bottom of the select

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6.0.7
Material 6.4.7
macOS High Sierra version 10.13.6
typescript 3.0.3
at least Chrome and Safari

**Comment by crisbeto** [comment]
The comment refers to the fact that this is the behavior of the native `select` on Windows. I'm guessing it might be different on other OS-es.

**Comment by crisbeto** [comment]
Closing since this works as expected.
