### ISSUE TITLE
Adding custom styles to the dropdown panel doesn't work in 7.0.0

### ISSUE THREAD

**Issue by fabva79** [angular/material2#13686]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It's possible to apply a custom style to the dropdown panel 

#### What is the current behavior?
The style doesn't change

#### What are the steps to reproduce?
The bug is present in the sample in the documentation https://material.angular.io/components/select/overview
In version 6.4.7 it works correctly.

**Comment by josephperrott** [comment]
Custom styling for the dropdown is still possible, the example's CSS just needed to be corrected.  You can see a working stackbiltz [here](https://stackblitz.com/edit/angular-srsipa).
