### ISSUE TITLE
CDK 7.0.0 missing distributed scss files

### ISSUE THREAD

**Issue by emilio-martinez** [angular/material2#13714]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
CDK shipped with scss files for packages like overlay and a11y.

#### What is the current behavior?
As of 7.0.0, the distributed scss files are no longer there—only the prebuilt ones.

#### What are the steps to reproduce?
See https://unpkg.com/@angular/cdk@6.4.7/ vs https://unpkg.com/@angular/cdk@7.0.0/.

#### What is the use-case or motivation for changing an existing behavior?
Access to the scss files allows overriding the variables provided before applying by the mixin. The prebuilt ones don't.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CDK 7.0.0

**Comment by crisbeto** [comment]
Fixed in https://github.com/angular/material2/pull/13679.
