### ISSUE TITLE
Binding with Angular JS and ng

### ISSUE THREAD

**Issue by briangmilnes** [angular/material2#13717]
#### Bug, feature request, or proposal:
The getting started documentation, or others, does not say which ng a new user should be
running with which version of Materia2/AngularJS. 

#### What is the expected behavior?
The user should have a clear statement such as a table that says
ng > X.X.X will work with the examples. And AngularJS > Y.Y.Y will work
with the examples.

#### What is the current behavior?
User setup confusion.

**Comment by djleonskennedy** [comment]
@briangmilnes  ![image](https://user-images.githubusercontent.com/8366455/47279666-38a9b400-d5db-11e8-9ce7-88219215890e.png)

**Comment by jelbourn** [comment]
The major version of Angular and Angular Material/CDK should always match. Aside from that any combined minor/patch versions are fine.
