### ISSUE TITLE
App freeze after upgrading to version 7, the issue is related to BreakpointObserver

### ISSUE THREAD

**Issue by AlQuraian** [angular/material2#13711]
When I upgraded my app to version 7 of Angular, Angular Material and CLI. My app hangs on the loading screen. After a lot of digging around I found the source of the issues, it has to do with BreakpointObserver from Angular CDK.

Here's the link on [StackBlitz](https://stackblitz.com/edit/angular-ztyba6)

All you have to do is to add the following to an element in the AppComponent template:
`[style.minHeight.px]="height | async"`
Then the app will freeze.

**Comment by AlQuraian** [comment]
angular/angular#26586

**Comment by manklu** [comment]
All you have to do is create your observable only once. Currently you create a new one with every call to height().

**Comment by crisbeto** [comment]
@manklu is correct. The way you have it set up at the moment will introduce a memory leak. Closing since it works as expected.
