### ISSUE TITLE
Angular Material 7.0.0 SVG icon not showing properly

### ISSUE THREAD

**Issue by rmiller-sgntr** [angular/material2#13712]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-icon should display custom svg icons properly (using MatIconRegistry).
It still worked today with v6.4.7 before update to v7.0.0

#### What is the current behavior?
It currently displays a filled square (see picture below).

#### What are the steps to reproduce?
Just try to register svg icon - nothing happens in the following [stackblitz example](https://stackblitz.com/edit/angular-material-t3bugd)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular + Material 7.0.0

#### Is there anything else we should know?

I upgraded from Angular v6 to v7 (including material). Now my SVG icons do not show up right as you can see here (icons show as black/blue squares instead of the actual icon):

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/mJNTU.png

My code for adding the icons (did not change from previous version): 

    export class AppComponent implements OnInit {
        constructor(
            private matIconRegistry: MatIconRegistry,
            private domSanitizer: DomSanitizer
        ) {
            // Register icons
            this.matIconRegistry.addSvgIcon(
                "icon1",
                this.domSanitizer
                    .bypassSecurityTrustResourceUrl("<path_to_icon1>.svg")
            );
    
            // Register icons
            this.matIconRegistry.addSvgIcon(
                "icon2",
                this.domSanitizer
                    .bypassSecurityTrustResourceUrl("<path_to_icon1>.svg")
            );
        }
    }

The paths are correct since the icons color is right. From looking at the docs, I can't see any change between the versions.

Any idea?

And my package dependencies:
```
  "dependencies": {
    "@angular/animations": "^7.0.0",
    "@angular/cdk": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "^7.0.0",
    "@angular/http": "^7.0.0",
    "@angular/material": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "@ngrx/store": "^6.1.0",
    "@swimlane/ngx-charts": "^9.0.0",
    "@swimlane/ngx-graph": "^5.1.1",
    "@types/uuid": "^3.4.4",
    "angular2-signaturepad": "^2.8.0",
    "body-parser": "^1.18.3",
    "compression": "^1.7.3",
    "core-js": "^2.5.7",
    "cors": "^2.8.4",
    "d3": "^5.7.0",
    "hammerjs": "^2.0.8",
    "html2pdf.js": "^0.9.0",
    "n": "^2.1.12",
    "npm": "^6.4.1",
    "path": "^0.12.7",
    "pusher-js": "^4.3.1",
    "rxjs": "^6.3.3",
    "rxjs-tslint": "^0.1.5",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.8",
    "@angular/cli": "~7.0.2",
    "@angular/compiler-cli": "^7.0.0",
    "@angular/language-service": "^7.0.0",
    "@compodoc/compodoc": "^1.1.5",
    "@types/hammerjs": "^2.0.36",
    "@types/jasmine": "^2.8.9",
    "@types/jasminewd2": "^2.0.5",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "^5.0.1",
    "tslint": "~5.9.1",
    "typescript": "^3.1.3"
  }
```

**Comment by crisbeto** [comment]
There are a couple of issues in your example:

1. It can't fetch the icon, because the `HttpClientModule` isn't included. There's an error about it in the console.
2. It seems like HTTP request for the icon fails, even if the `HttpClientModule` is included.

Here's a fork of your example where I've resolved it by setting the icon inline and it seems to work: https://stackblitz.com/edit/angular-material-r3ciqw

**Comment by rmiller-sgntr** [comment]
Thanks,
So apparently there was an issue with the SVG itself - it had background colors and that messed up the view. But it is weird that it worked on v6 and not on v7. And since you did manage to solve it by in-lining it, makes me wonder if something is indeed wrong here.
Since my designer fixed it by creating a new colorless (all black, no background) SVG, I am going to go ahead and close this, as it seems no one else is having this issue. 

Thanks again.
