### ISSUE TITLE
Mat-menu not working on firefox

### ISSUE THREAD

**Issue by 231293** [angular/material2#13728]
Bug- Want to open mat menu on button click

on chrome and edge its working as expected.

Expected-
It should work on Mozilla Firefox

Repro url
[https://stackblitz.com/edit/mat-menu-firefox-issue](https://stackblitz.com/edit/mat-menu-firefox-issue)

**Comment by vguleaev** [comment]
Set [matMenuTriggerFor] not on the icon (dunno why u do it) but on the bottom. Like this:
```
      <button mat-icon-button  matTooltipPosition="right" [matMenuTriggerFor]="menu">
         <mat-icon >more_horiz</mat-icon>
      </button>

```
And stop creating issues for fun.

**Comment by 231293** [comment]
> Set [matMenuTriggerFor] not on the icon (dunno why u do it) but on the bottom. Like this:
> 
> ```
>       <button mat-icon-button  matTooltipPosition="right" [matMenuTriggerFor]="menu">
>          <mat-icon >more_horiz</mat-icon>
>       </button>
> ```
> And stop creating issues for fun.

firstly I havent added an issue for fun.
If I have written wrong code then how it works on chrome and edge???

**Comment by 231293** [comment]
> > Set [matMenuTriggerFor] not on the icon (dunno why u do it) but on the bottom. Like this:
> > ```
> >       <button mat-icon-button  matTooltipPosition="right" [matMenuTriggerFor]="menu">
> >          <mat-icon >more_horiz</mat-icon>
> >       </button>
> > ```
> > And stop creating issues for fun.
> 
> firstly I havent added an issue for fun.
> If I have written wrong code then how it works on chrome and edge???

I found your code useful and its working as expected.
Closing the issue.
