### ISSUE TITLE
Compiling with Ivy

### ISSUE THREAD

**Issue by Rikarin** [angular/material2#13720]
Hi,
when I enabled ivy renderer it looks like something went wrong during the compilation of material.
I'm using 7.0.0 angular with 7.0.0 material.

```
The pipe 'async' could not be found ("<div class="mat-tooltip" [ngClass]="tooltipClass" [[ERROR ->]class.mat-tooltip-handset]="(_isHandset | async)?.matches" [@state]="_visibility" (@state.start)="_an"): /Users/Satoshi/Desktop/pegasus/Website/node_modules/@angular/material/tooltip/typings/index.d.ts.TooltipComponent.html@0:51
```

**Comment by manklu** [comment]
See angular/angular#26436

**Comment by Rikarin** [comment]
Thanks!

**Comment by revanthr1** [comment]
Hey @Rikarin did you get to fix the issue. Even am having the same AOT issue. If you fixed it just lemme know what all the changes should be made. Thank You.
