### ISSUE TITLE
Allow to change $mat-form-field-default-infix-width (and other sass variables)

### ISSUE THREAD

**Issue by JoniJnm** [angular/material2#13737]
#### Bug, feature request, or proposal:

I'm not sure

#### What is the expected behavior?

Setting `$mat-form-field-default-infix-width` before `@include mat-form-field-theme($candy-app-theme);` is not working.

#### What is the current behavior?

Allow to change default 180px of .mat-form-field-infix width

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-h6ccpg

#### What is the use-case or motivation for changing an existing behavior?

Without this feature I have to change the value using !important.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

6

#### Is there anything else we should know?

I think we should be able to change all sass variables. I suppose the width is included in stylesUrl in mat-form-field @component instead of in the mixin.

**Comment by jelbourn** [comment]
See #13008, #4003, #3152
