### ISSUE TITLE
Feature Request md-tab change color

### ISSUE THREAD

**Issue by 3mp3ri0r** [angular/material2#1373]
#### Bug, feature request, or proposal:

Feature Request
#### What is the expected behavior?

md-tab has properties color so developer can change tab color. I personally will use it to make tab color same with toolbar.
#### What is the current behavior?

No color properties.
#### What is the use-case or motivation for changing an existing behavior?

Me and maybe other want to make the tab color same with the toolbar.

**Comment by Aleph06** [comment]
I think this should help: https://github.com/angular/material2/blob/master/docs/theming.md

**Comment by 3mp3ri0r** [comment]
I think this feature should be merge in md-tab core, not by user modification.

**Comment by andrewseguin** [comment]
To create a consistent coloring style across the app, which it sounds like to be your case where you want the toolbar coloring matching the tabs, then theming will be the way to go. For specific coloring changes, using custom CSS styling should fit your needs. The proposed idea of including a color property will be essentially what themes are meant to solve.
