### ISSUE TITLE
Question(drag-drop): iOS 12 Safari scrolls on drag

### ISSUE THREAD

**Issue by philmtd** [angular/material2#13740]
#### Bug, feature request, or proposal:
question (bug?)

#### What is the expected behavior?
The touchmove event should be default-prevented.

#### What is the current behavior?
In our application this does not happen. While the handler method in the DragDropRegistry gets called and also calls preventDefault() on the event, this does not work, even though there is logic to bypass the underlying WebKit bug (and which seems to work in the examples).

#### What are the steps to reproduce?
I don't know.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.0.0

#### Is there anything else we should know?
The examples in the docs are all working fine and I was not able to reproduce this issue outside of the app we're developing. I was able to solve this by adding an empty active touchmove-Listener in my `main.ts` file:

```javascript
document.addEventListener('touchmove', () => {}, {passive: false});
```

This actually solves the issue for me, but I'm curious as to why this might happen. This might also affect other users of drag & drop.

Could this be related to us having a hybrid AngularJS/Angular application?

**Comment by crisbeto** [comment]
This might be happening if you have a `touchmove` listener somewhere in your app that's calling `stopPropagation`. Another possibility is if there's a `touchstart` listener with a `preventDefault`.

**Comment by philmtd** [comment]
We don't register any listeners to these events. But as we're upgrading our app, we're running AngularJS alongside angular-material and other AngularJS libraries. Might be one of those is responsible for this. Guess I will not investigate it too much, but thanks for the answer!
