### ISSUE TITLE
Feature request md-badge

### ISSUE THREAD

**Issue by 3mp3ri0r** [angular/material2#1374]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Ther is directive for creating badge like in [mdl](https://getmdl.io/components/index.html#badges-section).

#### What is the current behavior?
No badge.

#### What is the use-case or motivation for changing an existing behavior?
I want to use badge for shopping cart, message, and other.

**Comment by jelbourn** [comment]
We don't currently have any plans to implement this, but would be open to adding it further down the road.

**Comment by 3mp3ri0r** [comment]
So sad. But thanks for reply.
