### ISSUE TITLE
[proposal]: MatIconPicker - Material Icon Picker

### ISSUE THREAD

**Issue by chrisabovo** [angular/material2#13742]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Let the user give the possibility to enter/select a specific Material Icon. 
I was thinking of something similar as: [tech-advantage – ngx-icon-picker](https://github.com/tech-advantage/ngx-icon-picker).
Print examples for new component.

![image](https://user-images.githubusercontent.com/3661712/47297238-ea041600-d5ea-11e8-9d74-52e037691bb4.png)

![image](https://user-images.githubusercontent.com/3661712/47297245-ee303380-d5ea-11e8-8444-5347fd976ec2.png)

![image](https://user-images.githubusercontent.com/3661712/47297256-f4beab00-d5ea-11e8-90c5-0ce971470432.png)

#### What is the current behavior?
Not implemented yet in Material Angular and i don’t find any icon picker to Material Icon.

#### Is there anything else we should know?
A good features to this new componente:
- Show icons separeted by your group.
- Action - 3d_rotation, accessibility, ...
- Alert - add_alert, error, ...
- Show/Hide icons names.
- Filter icons by group ou name.
- Paginated or not the list.

**Comment by josephperrott** [comment]
Closing as this is not something defined by the Material Design spec and therefore is not something we are likely to consider for creation.

**Comment by chrisabovo** [comment]
Ok, Thank you.
