### ISSUE TITLE
Virtual scrolling on window

### ISSUE THREAD

**Issue by CharlBest** [angular/material2#13746]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Have the ability to scroll the window but have a section/portal that still makes use of the virtual scrolling capabilities to recycle DOM elements.

#### What is the current behavior?
The scroll container and the portal/content section is the same thing and can't be specified separately.

#### What are the steps to reproduce?
n/a

#### What is the use-case or motivation for changing an existing behavior?
At the moment it's not possible (AFAIK) to have an infinite scroll feed of items that causes the window to scroll. The reason you would want to put the scroll on the window it to cater for headers, footers and other sections that should also scroll with the page.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7
Material 7
Typescript 3.1

#### Is there anything else we should know?
n/a

**Comment by mmalerba** [comment]
Closing as dup of #13862
