### ISSUE TITLE
DragDrop 1:many stop working after upgrade to Angular 7 and Material 7.0.1

### ISSUE THREAD

**Issue by MaciejWWojcik** [angular/material2#13753]
#### Bug, feature request, or proposal:
I have a component which has one list connected to other lists using a drag&drop feature. I was working on this during Material 7.0.0.beta... and everything was working fine. I mean there were one empty list (main) and other lists with items and I was able to drag and drop from any "child" list to main-list. Currently, this is impossible. Drag is bugging and I receive this error when I start the drag.
 

> polyfills.43b211ceda3e04bd6c03.js:9888 Uncaught TypeError: Cannot read property 'nativeElement' of undefined
    at main.e8ed8c1f99b446498fb1.js:11580
    at Array.map (<anonymous>)
    at CdkDropList.push../node_modules/@angular/cdk/esm5/drag-drop.es5.js.CdkDropList._cachePositions (main.e8ed8c1f99b446498fb1.js:11580)
    at CdkDropList.push../node_modules/@angular/cdk/esm5/drag-drop.es5.js.CdkDropList.start (main.e8ed8c1f99b446498fb1.js:11263)
    at CdkDrag.push../node_modules/@angular/cdk/esm5/drag-drop.es5.js.CdkDrag._startDragSequence (main.e8ed8c1f99b446498fb1.js:10661)

Here is my template code:

```
<div #selectedItemsList [cdkDropListData]="selectedItems"
       [cdkDropListConnectedTo]="[availableItemsList]"
       class="result list" (cdkDropListDropped)="dropItem($event)" cdkDropList>
    <div class="box" *ngFor="let box of selectedItems" cdkDrag>{{box.name}}</div>
  </div>

  <ng-container *ngFor="let item of availableItems">
    <div #availableItemsList [cdkDropListData]="item.items" [cdkDropListConnectedTo]="[selectedItemsList]"
         class="list"
         (cdkDropListDropped)="dropItem($event)" cdkDropList>
      <div class="box" *ngFor="let box of item.items" cdkDrag fxLayout="column">
        {{box.name}}
      </div>
    </div>
  </ng-container>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.0
Material & CDK 7.0.1

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by crisbeto** [comment]
@MaciejWWojcik it's breaking because the `cdkDropList` was turned into a directive, which means that you need to change your template references from `#selectedItemsList` to `#selectedItemsList="cdkDropList"`. The same goes for the `#availableItemsList`.
