### ISSUE TITLE
Mat Stepper Propery labelPosition not working

### ISSUE THREAD

**Issue by Barvor** [angular/material2#13768]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Mat-horizontal-stepper labelPosition property should work as intended

#### What is the current behavior?
Mat-horizontal-stepper labelPosition property does nothing.

**Comment by crisbeto** [comment]
Can you post a code sample of what you're trying to do? It would also be helpful to know what version of Material you're running.

**Comment by brianpilati** [comment]
@crisbeto I am seeing the issue too. It is always "at the end" and never "bottom"

<mat-horizontal-stepper linear #stepper (labelPosition)="bottom">


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.2.2
Node: 10.10.0
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.2
@angular-devkit/core         0.8.2
@angular-devkit/schematics   0.8.2
@schematics/angular          0.8.2
@schematics/update           0.8.2
rxjs                         6.2.2
typescript                   2.9.2

"@angular/material": "^6.4.7"

**Comment by brianpilati** [comment]
@crisbeto You can use this example: https://stackblitz.com/angular/jnmaooqparx?file=app%2Fstepper-overview-example.ts and add this line of code

<mat-horizontal-stepper linear #stepper (labelPosition)="bottom">

**Comment by crisbeto** [comment]
@brianpilati you're not binding the value correctly. You should be setting it either as `labelPosition="bottom"` or `[labelPosition]="'bottom'"`, whereas what you're doing now is an event binding. Here's a working example: https://stackblitz.com/edit/angular-zcqlf4

**Comment by Barvor** [comment]
I am using Material 6.1.0. and as brian said even when using labelPosition="bottom" it does not change a thing.

I tried replicating it with the code provided by the documentation but even there it does not work

**Comment by Barvor** [comment]
in brians example it suddenly works but with this code it does not:

`<form (ngSubmit)="onSubmit()" [formGroup]="form" novalidate>
  <mat-horizontal-stepper labelPosition="bottom" linear>

    <ng-template matStepperIcon="edit">
      <span class="fa fa-check"></span>
    </ng-template>

    <ng-container *ngFor="let step of formSteps; index as i">
      <mat-step [formGroupName]="step.key" [stepControl]="form.get(step.key)">
        <ng-template matStepLabel>{{step.label}}</ng-template>
        <div class="row">
          <div [ngClass]="element.gridClasses" *ngFor="let element of step.elements">
            <smit-form-element [element]="element" [form]="form.get(step.key)"></smit-form-element>
          </div>
          <div class="col-12">
            <div class="d-flex justify-content-end align-items-center">
              <ng-container *ngIf="i > 0">
                <button mat-button color="primary" matStepperPrevious type="button">Zurück</button>
              </ng-container>
              <ng-container *ngIf="i !== formSteps.length - 1">
                <button mat-raised-button color="primary" matStepperNext type="button" [disabled]="!form.get(step.key).valid">Weiter</button>
              </ng-container>
              <ng-container *ngIf="i === formSteps.length - 1">
                <button mat-raised-button color="primary" type="submit" [disabled]="!form.valid">{{submitLabel}}</button>
              </ng-container>
            </div>
          </div>
        </div>
      </mat-step>
    </ng-container>

  </mat-horizontal-stepper>

</form>`

can you tell me why?

**Comment by Barvor** [comment]
![2018-10-24_09h06_39](https://user-images.githubusercontent.com/37341676/47412460-1eeba680-d76c-11e8-8894-1fe65f8dabe9.png)

Can not paste code, the first two lines are always missing

**Comment by crisbeto** [comment]
It's probably because your version of Material doesn't have the option. Note that the Stackblitz from @brianpilati is using Material 7.0. I can't tell when the feature was released, because the PR that introduced it wasn't labelled correctly so it doesn't show up in the changelog.

**Comment by Barvor** [comment]
@crisbeto upgrading material to 7.0.1 (and cdk on 7.01.) made it possible.

thank you!
