### ISSUE TITLE
virtual-scroll inside mat-select doesn't work

### ISSUE THREAD

**Issue by fabva79** [angular/material2#13762]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Using `cdk-virtual-scroll-viewport` inside a mat-select the options panel behaviour should be the same as without `cdk-virtual-scroll-viewport`.

#### What is the current behavior?
The options panel isn't visible.

#### What are the steps to reproduce?
[https://stackblitz.com/edit/angular-jgncyh](https://stackblitz.com/edit/angular-jgncyh)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 7.0.0
@angular/cdk 7.0.0

**Comment by gilsdav** [comment]
You need to specify a height on dk-virtual-scroll-viewport like `style="height:256px"` but it will not work properly.
Select use `@ContentChildren(MatOption, { descendants: true }) options: QueryList<MatOption>;` but that means it needs all the options. A virtual scroll does not seem possible at the moment.

**Comment by mmalerba** [comment]
Closing this since #10122 is being used to track integration of virtual-scroll with other components
