### ISSUE TITLE
Issue: md-toolbar: unable to alter CSS on first row (auto-generated)

### ISSUE THREAD

**Issue by Hugmungus** [angular/material2#1376]
#### Bug, feature request, or proposal:

When using md-toolbar in Angular, it creates the first md-toolbar row automatically. Since there is no tag designation for this in the html, you are unable to alter the CSS for it (ie, change the height)
#### What is the expected behavior?

You should be able to alter the CSS on every piece of the md-toolbar
#### What are the steps to reproduce?

Plunker: http://plnkr.co/edit/kP6MYoVdFQlECDX7T7Hs?p=preview
#### What is the use-case or motivation for changing an existing behavior?

A user will have limited control over the first md-toolbar-row while using this framework
#### Which versions of Angular, Material, OS, browsers are affected?

Angular2: 2.0.1
Material: 2.0.0-alpha.8-2
Chrome:  53.0.2785.116 m

**Comment by PascalTemel** [comment]
@Hugmungus You can use the `:host >>> md-toolbar-row` selector. Here's a modified plunkr: http://plnkr.co/edit/IWq5nWl4ymU3rR3xKwrH?p=preview

**Comment by Hugmungus** [comment]
Thanks @PascalTemel, that seems to do the trick.

**Comment by jelbourn** [comment]
@DevVersion we should discuss this a bit

**Comment by DevVersion** [comment]
@jelbourn Sounds good. I already have some API ideas, how we could fix this issue and perhaps #1718 as well.

**Comment by DevVersion** [comment]
Related to #1718

**Comment by DevVersion** [comment]
I will close that issue in favor of #1718.
