### ISSUE TITLE
How to pass valued to MDdialogue ?

### ISSUE THREAD

**Issue by santhanam87** [angular/material2#1377]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Pre-populated dialogue window, based on the value from the component or other classes.

#### What is the current behavior?
No docs provided for that case.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by jelbourn** [comment]
The dialogRef has a `componentInstance` property. You can set whatever values necessary to that. README for dialog will be coming soon.

**Comment by santhanam87** [comment]
@jelbourn in dialog-config.ts I saw a DialogRole Parmeter, I like to have similar sort of multiple types of dialogue box like alert, confirm and inline. Is it a better approach to have it along with dialog module or else do I need to create a entry component for each type like jazzdialogue ?

**Comment by skined90** [comment]
@jelbourn Can you please explain little bit more how to pass the data to the dialog component via componentInstance property?
