### ISSUE TITLE
mat-select two way binding doesn't invoke selectionchange

### ISSUE THREAD

**Issue by mihirkhatri87** [angular/material2#13778]
#### Bug, feature request, or proposal:
I've done two way binding for mat-select in below fashion.
<mat-form-field>
  <mat-select [(value)]="selected" (selectionChange)="changed($event)">
    <mat-option>None</mat-option>
    <mat-option value="option1">Option 1</mat-option>
    <mat-option value="option2">Option 2</mat-option>
    <mat-option value="option3">Option 3</mat-option>
  </mat-select>
</mat-form-field>
Now, when selected value changes from component, mat-select doesn't emit selectionChange.

#### What is the expected behavior?
Whenever two-way bound property's value changes from background, selectionChange should trigger on mat-select

#### What is the current behavior?
mat-select accepts new selected value and shows new selected item but doesn't fire selectionChange

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-eauvjk?file=app/select-value-binding-example.html
Here, on click on change button I should see alert window as specified in my selectionChange handler but that never happens

#### What is the use-case or motivation for changing an existing behavior?
I've two-way bindings in my application and there are more than 1 places from where selected value could change

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.2.1

**Comment by crisbeto** [comment]
From the `selectionChange` docs:

> Event emitted when the selected value **has been changed by the user**.
