### ISSUE TITLE
(bug) cdk-virtual-scroll-viewport unfluency when item height is uncertain.

### ISSUE THREAD

**Issue by Eusen** [angular/material2#13806]
#### Bug, feature request, or proposal:
![image](https://user-images.githubusercontent.com/14822175/47489260-c48c3c00-d878-11e8-9424-2c89a337c714.png)
In the official example, I make each element have a different height, and then during the test, I found that there was unfluency when the next two elements were different in height.

#### What is the expected behavior?
Views slide smoothly

#### What is the current behavior?
Views slide unfluency

#### What are the steps to reproduce?
` <div class="example-item-detail" [style.height.px]="index % 2===0 ? 100 : 20">Item: {{item}}</div>`

#### What is the use-case or motivation for changing an existing behavior?
Repair problems

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Same as example

#### Is there anything else we should know?
no~

**Comment by webcat12345** [comment]
Something related with this [issue](https://github.com/angular/material2/issues/10113)?

I think this feature is really required, most cases we actually we use items with different heights.

And is there any way to give some preload section so we can use this scroll with img tags? right now it is very jumpy when there is an img tag with the item.

**Comment by webcat12345** [comment]
@Eusen I have tested `autosize` feature from experimental lib, and it works well, I think we can close this stream and watch the issue #10113 together.

**Comment by Eusen** [comment]
haha I see, thanks~
