### ISSUE TITLE
Add support to combine virtual scroll and drag and drop features

### ISSUE THREAD

**Issue by doronsever** [angular/material2#13804]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Make drag and drop workable when rendering a list using a virtual scroll

#### What is the current behavior?
They don't play nicely together

#### What are the steps to reproduce?
https://angular-material-dragdrop-virtualscroll.stackblitz.io

Provided a demo on how they both play together, I combined both examples from your website

#### What is the use-case or motivation for changing an existing behavior?
We have a list that might contain lots of items.
We would like to render it using the material virtual scroll for better performance, the issue is that it breaks our recording drag and drop  

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 7, Material 7.0.1

**Comment by mmalerba** [comment]
Closing this since #10122 is being used to track integration of virtual-scroll and various other components
