### ISSUE TITLE
Menu list do not close when clicking another menu item - so multiple menu stay on screen

### ISSUE THREAD

**Issue by Son-Lam** [angular/material2#1380]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
For menu bar with multiple menu buttons, when selecting another menu button, any previous menu drop box should be closed.

#### What is the current behavior?
+ Previous menu drop box stay on screen
+ One mouse click outside only close one menu

#### What are the steps to reproduce?
![angular2-material-menu-bug](https://cloud.githubusercontent.com/assets/7008339/18978425/efe78940-8677-11e6-83e0-698667c68bc1.png)

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by Ploppy3** [comment]
Already reported here : [#1360](https://github.com/angular/material2/issues/1360)

**Comment by jelbourn** [comment]
Due of #1360
