### ISSUE TITLE
Problem with Alpha.9-3 installation

### ISSUE THREAD

**Issue by rafaelss95** [angular/material2#1381]
I just started a new project and I did everything as is in the [GETTING_STARTED.md](https://github.com/angular/material2/blob/master/GETTING_STARTED.md)

After I did `npm install --save @angular/material`

I got: 

```
angular@0.0.0 /path
├── UNMET PEER DEPENDENCY @angular/common@2.0.0
├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0
├── UNMET PEER DEPENDENCY @angular/core@2.0.0
├── @angular/material@2.0.0-alpha.9-3 
└── UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0

npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/common@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/platform-browser@2.0.1 but none was installed.
```

And when I did ` ng serve` I got:

```
ERROR in [default] /path/node_modules/@angular/material/core/gestures/MdGestureConfig.d.ts:4:39 
Cannot find name 'HammerManager'.

ERROR in [default] /path/node_modules/@angular/material/slide-toggle/slide-toggle.d.ts:68:19 
Cannot find name 'HammerInput'.

ERROR in [default] /path/node_modules/@angular/material/slider/slider.d.ts:61:19 
Cannot find name 'HammerInput'.

ERROR in [default] /path/node_modules/@angular/material/slider/slider.d.ts:63:24 
Cannot find name 'HammerInput'.
```
I tried to install `npm install hammerjs`, but it doesn't work also.

Thanks in advance.

**Comment by spock123** [comment]
Just a quick question: did you use npm 3?

**Comment by slmyers** [comment]
try `npm install @types/hammerjs`

**Comment by cre8** [comment]
Restarting the server (`ng serve`) and adding types helped me.

**Comment by rafaelss95** [comment]
@spock123, Yes I'm using the version 3.10.8.

Well, it's a little bit strange.. first of all I think I don't need add `hammerjs` since I wasn't using any component yet, and in [GETTING_START.md](https://github.com/angular/material2/blob/master/GETTING_STARTED.md) says clearly I just need to add it if I use `md-slide-toggle` and `md-slider`. However I installed as I mentioned `npm install hammerjs`, but it still also gives me error.

Now the problem is solved using the suggestion given by @slmyers, but why is it necessary? If I'm not even using none of the modules that required `hammerjs`?

Also, the `UNMMEET PEER DEPENDENCY` is something that I have to worry about? Because it's still here.

**Comment by spock123** [comment]
@rafaelss95  don't worry about the dependency stuff.. it's just npm3 telling you about them.. it's nothing to worry about afaik...

I think hammer.js is needed by Material-core now, but I'm not sure about this.. just install it to be sure :)

**Comment by rafaelss95** [comment]
Hmm, thanks for all helpful information.

Can you tell me what's the problem with this simple example:

```
<button md-raised-button color="primary">PRIMARY</button>
<button md-raised-button color="accent">ACCENT</button>
<button md-raised-button color="warn">WARN</button>
```

It's displaying without colors.
Do I need to do something more than it to make it work? In my ts file, for example?

**Comment by dahaupt** [comment]
@rafaelss95 I think you have to include a theme or write your own. Check the **theming.md** in the **docs** folder. For more information.

**Comment by vinagreti** [comment]
You can see in this PR #1385 how to use themes to customize your own components.
