### ISSUE TITLE
Changing the autocomplete on a trigger does not change the overlay (options)

### ISSUE THREAD

**Issue by thomaspink** [angular/material2#13812]
#### Bug, feature request, or proposal:
Changing the autocomplete on a trigger does not change the options in the overlay.

#### What is the expected behavior?
When changing the autocomplete (`dtAutocomplete` input) on a trigger, the overlay should display the new options.

#### What is the current behavior?
When changing the autocomplete (`dtAutocomplete` input) on a trigger, the overlay options
are still the initial ones.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-7djgzt?file=app%2Fautocomplete-simple-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current

**Comment by manklu** [comment]
You could simply switch between the lists.

https://stackblitz.com/edit/angular-7djgzt-bzagsq

**Comment by thomaspink** [comment]
Yes i know, but this does not show the issue.

**Comment by manklu** [comment]
Still no problem.

https://stackblitz.com/edit/angular-7djgzt-fr6q4s
https://stackblitz.com/edit/angular-7djgzt-x5l31h

**Comment by thomaspink** [comment]
This example is there to show the issue of not updating the template/portal when changing the autocomplete panel. Workarounds/other solutions of course work but do not solve this problem
