### ISSUE TITLE
Drag and drop only in current block (list)

### ISSUE THREAD

**Issue by launcelot66** [angular/material2#13826]
#### Bug, feature request, or proposal:
Feature request / Question

#### What is the expected behavior?
Dragged element cant be dragged out of current list (block)

#### What is the current behavior?
Dragged element go over current list

#### What are the steps to reproduce?
example from [material](https://material.angular.io/cdk/drag-drop/overview#reordering-lists) 
and add `cdkDragLockAxis="y" ` to cdkDrag element

#### What is the use-case or motivation for changing an existing behavior?
So that the user understands that sorting is possible only in the current list.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.0
Material: 7.0
os: iOS Mojave
TypeScript: 3.1.3
browser: chrome
npm: 6.4.1
node: 10.2

#### Is there anything else we should know?
multiple drag elements - will be good

**Comment by josephperrott** [comment]
It seems like we should be able to do the same API as `enterPredicate` and have an `exitPredicate`.

**Comment by crisbeto** [comment]
This is possible now using the `cdkDragBoundary` input.
