### ISSUE TITLE
Radio Buttons does not work on Android 4.4

### ISSUE THREAD

**Issue by mazhekin** [angular/material2#13858]
#### Bug, feature request, or proposal:
Bug radio buttons does not work on Android 4.4

#### What is the expected behavior?
Must be work as usual

#### What is the current behavior?
https://stackoverflow.com/questions/53050016/angular-material-radio-buttons-does-not-work-on-android-4-4

**Comment by crisbeto** [comment]
Android 4.4 isn't something that we test against. See the browser support section of our docs: https://github.com/angular/material2#browser-and-screen-reader-support.
