### ISSUE TITLE
Cdk virtual scroll trackBy function not removing items

### ISSUE THREAD

**Issue by RollyPeres** [angular/material2#13851]
#### Bug, feature request, or proposal:
*cdkVirtualFor's trackBy function not removing items.

#### What is the expected behavior?
*cdkVirtualFor should remove items when trackBy function is based on a custom field.
E.g: 
trackByIdx(i, item: Person) {
    return item.id;
  }

#### What is the current behavior?
Deleted item is not removed from the view.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7, material 7.0.1, cdk 7.0.1, Typescript 3.1.3

**Comment by MurhafSousli** [comment]
I think you need to add a reproduction!

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by RollyPeres** [comment]
Do you have a stackblitz starter template for Angular 7 and material 7 ?

**Comment by RollyPeres** [comment]
I apologize, it was a mistake on my side, some side effect from rxjs scan :) Have a great day!
