### ISSUE TITLE
Virtual scroll infinite loop in both direction

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#13857]
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

Infinite scroll in both direction

#### What is the current behavior?

Currently the infinite scroll is not possible in both direction

#### What is the use-case or motivation for changing an existing behavior?

I am using horizontal virtual scroll, I need to provide infinite scroll in both direction and keep the current index always in center of the view port

Assume the array is 

[0][1][2][3][4][5][6][7][8][9]

                           currIndex
                              |       
      [6][7]       |   [8][9][0][1][2]   |   [3][4][5]
    Not rendered   |      Rendered       |  Not rendered

Let's say user go to `viewport.scrollToIndex(2)`

                           currIndex
                              |       
      [8][9]       |   [0][1][2][3][4]   |   [5][6][7]
    Not rendered   |      Rendered       |  Not rendered

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: 7.0.1
Material: 7.0.2

**Comment by MurhafSousli** [comment]
I have tried to implement it with current functionality (7.0.2), can anyone check this example, maybe it is simple! 
[stackblitz](https://stackblitz.com/edit/angular-5y6key?file=src%2Fapp%2Fapp.component.ts)
[stackoverflow question](https://stackoverflow.com/questions/53143204/angular-cdk-virtual-scroll-infinite-loop)

**Comment by mmalerba** [comment]
I would suggest using a custom data source for this (see the [custom data source example](https://stackblitz.com/angular/nvpnqpjmrnqg?file=app%2Fcdk-virtual-scroll-data-source-example.ts) from the [virtual scroll docs](https://material.angular.io/cdk/scrolling/overview))

**Comment by MurhafSousli** [comment]
@mmalerba I tried to implement it in this [stackblitz](https://stackblitz.com/angular/nvpnqpjmrnqg?file=app%2Fcdk-virtual-scroll-data-source-example.ts) but I still haven't got it right

**Comment by mmalerba** [comment]
here's an example that adds new copies of the data when you get near the end of the list: https://stackblitz.com/edit/angular-qpsjxm?file=app/cdk-virtual-scroll-data-source-example.ts

**Comment by MurhafSousli** [comment]
@mmalerba Thanks! that looks good! but is it possible to do the same for the opposite direction? I want to make the same for scrolling up

**Comment by mmalerba** [comment]
You could start off scrolled to the middle of the list, that would allow the user to scroll up or down
