### ISSUE TITLE
md-slider thumb position does not move when value is updated by external data source

### ISSUE THREAD

**Issue by danny-swimmer** [angular/material2#1386]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The slider's thumb position should be updated when an external data source updates the value of the md-slider.

#### What is the current behavior?
The slider's thumb position is not updated when an external data source updates the value of the md-slider.

#### What are the steps to reproduce?
Please refer to this plunk: http://plnkr.co/edit/sZHhzGHu5vg2lyj7B0On
I'm using property binding to link the AppComponent class's data property into a target element property (the md-slider).
Note that when an external data source (simulated in the plunk by an input field) changes the component's "level" property, the value of the md-slider (shown to the right of the slider) DOES update. 
However the graphical md-slider thumb element DOES NOT update its position.

#### What is the use-case or motivation for changing an existing behavior?
It's a bug.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0 final.
@angular2-material/slider - v2.0.0-alpha.8-2 - Angular 2 Material Slider
Server is running linux.
Browser is running on Windows 7, Chrome v53.0.2785.116 m

**Comment by danny-swimmer** [comment]
Hi @jelbourn,
Please forgive me if my assumptions are incorrect.
I noticed that this issue was marked as fixed in release 2.0.0-alpha.10.
I assume that this release now becomes the default for newly-created plunks, such as this one I just made to test the fix:
http://plnkr.co/edit/IojSZiv89EVPotxUr1u0
However the behaviour has not changed - the slider still doesn't move when the value binding changes.

**Comment by jelbourn** [comment]
@danny-swimmer I don't believe the plunker has been updated yet.
