### ISSUE TITLE
Emit Drop Target Index Change

### ISSUE THREAD

**Issue by techy2493** [angular/material2#13863]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
When a user drags a cdkDrag around in a cdkDropList container, and the index it will dropped into changes emit an event with the new drop target index. 

#### What is the current behavior?
No event is emitted, you must wait for the user to drop the CdkDrag to know what index the item will drop into.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
It would be beneficial to know this so that designers can provide additional context of where the user is preparing to drop an item. For example: Dragging a numbered list, showing the numeric position of the drop target in the placeholder.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material/Cdk > 7.0.1

#### Is there anything else we should know?
There is already a basis for this functionality, with the CdkDropList's 
_getItemIndexFromPointerPosition(item: CdkDrag, pointerX: number, pointerY: number,                                   delta?: {x: number, y: number}) method and CdkDrag's CdkDragMoved ( source, pinterPosition, event, delta). 
If _getItemIndexFromPointerPosition were public it would be trivial to implement a work-around so that we could get the required information.

**Comment by crisbeto** [comment]
To be clear, do you expect the index in the `cdkDropListEntered` event?

**Comment by techy2493** [comment]
@crisbeto No. This isn't when you enter a cdkDropList, This would be any time the target index changes, even if the cdkDrag stays in the same cdkDropList.  For example, it should emit an event with the index  of the placeholder any time the placeholder moves.

**Comment by techy2493** [comment]
Here is a gif with an example. Any time the palceholder moves an event with the new index of the placeholder should be emitted. This would be the target index where the cdkDrag would be dropped if the user released at that time. https://puu.sh/BSZO3/4e203775af.gif

**Comment by techy2493** [comment]
@crisbeto Thank you for jumping on this so quickly! #13887 addresses this perfectly. I totally missed _sortItem being invoked by CdkDrag! This is a much better solution than my initial thoughts for a workaround. I'm going to try this in my particular use case today, until a release which includes this becomes available.

**Comment by uareurapid** [comment]
Hi guys..
by the way, can someone tell me if is this possible already? 

> "To be clear, do you expect the index in the cdkDropListEntered event?"

Is there a way i can check in which position of the target drop list, my dragged element is entering? (i mean before the drop takes place)
thanks in advance

**Comment by vuonghungvinh** [comment]
same question, I need currentIndex in cdkDropListEntered event
