### ISSUE TITLE
Drag and drop inside drag and drop

### ISSUE THREAD

**Issue by Korfoo** [angular/material2#13874]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
You should be able to reorder items in a list that is in an other sortable list. 

#### What is the current behavior?
When you take an item to reorder it, you take the full list. You can only reorder the lists, not the items within.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-qrezcs
If you want to reorder an item in one of the lists you take the whole list. 

#### What is the use-case or motivation for changing an existing behavior?
It makes sorting tree-like structures easier for the user. And the current behavior is just strange and buggy.
This makes it possible to sort for example employees within a team and the teams within an organisation.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7

**Comment by crisbeto** [comment]
Fixed by https://github.com/angular/material2/pull/13820.
