### ISSUE TITLE
md-menu with icons and colors

### ISSUE THREAD

**Issue by no-more** [angular/material2#1388]
#### Bug, feature request, or proposal:

feature request
#### What is the expected behavior?

Correctly display icons inside md-menu.
Be able to add style using md-primary md-accent ... 
#### What is the current behavior?

icons are displayed too close of the text, maybe I don't use it correctly but if that's it then the docs needs to be updated.
It would also be great to change the style by using md-accent, md-primary ... classes as for md-button
#### What are the steps to reproduce?

```
<md-menu x-position="before" #globalMenu="mdMenu">
            <button md-menu-item>
                <md-icon fontIcon="search"></md-icon>
                globalMenu.apps
            </button>
            <button md-menu-item class="md-primary">
                <md-icon fontIcon="search"></md-icon>
                globalMenu.account
            </button>
</md-menu>
```

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
I didn't manage to make md-menu works with the plunker sorry
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.0.1
Material 2.0.0-alpha.9-2

**Comment by vinagreti** [comment]
Try to use md-list-icon attr in your mmd-icon as:
<md-icon fontIcon="search" md-list-icon></md-icon>

**Comment by no-more** [comment]
Thanks but it does not change any thing as you can see in the screenshot below icons are to close to text.

![2016-10-01_092139](https://cloud.githubusercontent.com/assets/3856871/19011998/73ecdfa6-87b8-11e6-8f1e-3624b6c624c1.jpg)

Thanks
