### ISSUE TITLE
DragAndDropModule not able to scoll on mobile

### ISSUE THREAD

**Issue by soeberg84** [angular/material2#13895]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
I would like to be able to scroll on android devices and chrome device emulator.

#### What is the current behavior?
Scrolling is not enabled if the list fills the entire screen.
When using cdkDragHandle I'm not able to scroll pressing on the list elements.

#### What are the steps to reproduce?
Touch device (chrome emulator):

https://stackblitz.com/angular/glvkoklvppy?file=app%2Fcdk-drag-drop-sorting-example.css

cdkDragHandle: 
https://stackblitz.com/angular/rklpvgllplv?file=app%2Fcdk-drag-drop-handle-example.ts

Set mat-app-background to height=5000px
e.g. div class="mat-app-background basic-container" style="height: 5000px"

#### What is the use-case or motivation for changing an existing behavior?
It would be nice to be able to scroll even if draggable elements fill entire screen
and drag handle does not block scrolling

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.0.2

#### Is there anything else we should know?
I'm currently using:
http://timruffles.github.io/mobile-drag-drop/demo/
where you can set a delayed drag so the user have to do "long" press before dragging otherwise it scrolls.
"holdToDrag: 200"

**Comment by crisbeto** [comment]
Some of this will be mitigated by https://github.com/angular/material2/pull/13780 where the touch-blocking styling will be confined to the handle.

**Comment by josephperrott** [comment]
Closed by #13780
