### ISSUE TITLE
Ability to delay dragging event by X milliseconds 

### ISSUE THREAD

**Issue by MortPed** [angular/material2#13908]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Set property to delay dragging event by X milliseconds 
`<div cdkDrag cdkDragDelay="2000">Hold for 2 seconds to move this item</div>`

#### What is the current behavior?
No option to prevent dragging on initial touch rendering this very hard to use on mobile.
(This is certainly not helped by the fact that cdkDrag elements disable mobile scroll events)

#### What is the use-case or motivation for changing an existing behavior?
Currently click events immediately trigger leading to unintended re-ordering. Many sites and native devices solves this issue by not starting the drag event unless user have clicked and hold the object for a short amount of time.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 @angular/cdk: 7.0.2

**Comment by crisbeto** [comment]
The `CdkDrag` directive only starts dragging [after a certain threshold](https://github.com/angular/material2/blob/master/src/cdk/drag-drop/drag.ts#L79), however the default of  5px might too low for a mobile device. You can try to set a different threshold through the `CDK_DRAG_CONFIG` provider.

**Comment by MortPed** [comment]
I am not sure this will solve the issue regarding touch devices, as you are scrolling down content it is unfortunate to reorder up random elements, and not sure any amount of distance threshold will resolve this. I believe that #13895 will make this Drag'n'Drop usable for smaller touch devices, but for the next iteration, I still think implementing an optional time-based threshold would make it act more intuitive to the users and make it behave more like native implementations.

**Comment by philmtd** [comment]
I +1 this idea. On the other hand a custom solution could probably be created once #13722 is merged. You'd then just manually need to handle the long-press and after that enable the dragging of that element.

Or you could use separate drag handles that are only active and visible on mobile devices.

**Comment by lornz** [comment]
+1 this feature.
Right now it is possible to disable drag, so one could just disable it until a certain time (!) threshold is passed. But unfortunately enabling doesn't work reliable, sometimes the dragging starts sometimes not. So I think a built-in time delay (aka longpress) would be very helpful for a lot of use cases.
