### ISSUE TITLE
md-slide-toggle does not emit event when thumb is dragged

### ISSUE THREAD

**Issue by danny-swimmer** [angular/material2#1390]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
When the user changes state by dragging the thumb, a change event should be emitted.

#### What is the current behavior?
Change event is not emitted.

#### What are the steps to reproduce?
Please see this plunk: http://plnkr.co/edit/gMK2P5tCWyT4mszL08ih

Click on the switch to change the state. Note that we see a message indicating that a change event was received. Now drag the thumb from one side to the other. Note that the change event is not generated.

#### What is the use-case or motivation for changing an existing behavior?
I believe we should follow the principle of "If the feature is there, it should work". If we're giving the user the capability of changing the state by dragging the thumb, then this action should take affect.
As an average user, I was surprised that it doesn't affect the state.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0 final.
@angular2-material/slide-toggle - v2.0.0-alpha.8-2 - Angular 2 Material Slide Toggle.
Server is running linux.
Browser is running on Windows 7, Chrome v53.0.2785.116 m

#### Is there anything else we should know?
No.

**Comment by Snesi** [comment]
I don't know what I'm missing but this is still happening to me in production. On my machine, it works fine, but when I build the project with angular-cli it stops working. I'm using `2.0.0-beta.5`

**Comment by Snesi** [comment]
Never mind [this](https://github.com/angular/material2/issues/4278#issuecomment-301082315) solved it. Thank you @iliketomatoes!
