### ISSUE TITLE
CDK Virtual Scroll ViewDestroyed Error

### ISSUE THREAD

**Issue by lujakob** [angular/material2#13901]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Scrolling of virtual-scroll list is possible during an updating process of the data without any errors.

#### What is the current behavior?
When a virtual scroll list of items is during an update process of the items, scrolling the list causes an "Attempt to use a destroyed view" error. In realworld use case an array of objects are being updated (property changes in the objects). In the stackblitz demo a setInterval updates the data. I suspect the error is caused through reassignment of the data during scrolling.

#### What are the steps to reproduce?

StackBlitz starter: https://stackblitz.com/edit/angular-cwrtae
Open console, press button to start updating the data and then scroll back and forth continuously.

#### What is the use-case or motivation for changing an existing behavior?
The virtual-scroll directive should be possible to use with a list of data that is being in an updating/changing process. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.0.0

**Comment by lujakob** [comment]
The stack traces lead to `_updateContext` function. I suspect a view trying to be updated, when it's already been replaced.
https://github.com/angular/material2/blob/master/src/cdk/scrolling/virtual-for-of.ts#L279
There is a Todo for @mmalerba in the source, maybe this is a place to start.

**Comment by ireneguijarro** [comment]
Same problem here, :cry:
