### ISSUE TITLE
ng update from 6.4.0 to 7.0.3 throws custom rule errors

### ISSUE THREAD

**Issue by crutchcorn** [angular/material2#13913]
#### Bug, feature request, or proposal:
When running `ng update @angular/material --force --from=6.4.0 --migrate-only`, there are errors:
```
Could not find custom rule directory: ./attribute-selectors/
```

#### What is the expected behavior?
Run migration without errors

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI v7, migrating Material from 6.4.0 to 7.0.3

**Comment by DevVersion** [comment]
If you run `ng update` with `--migrate-only` it should just the `ng-update` schematic from `v6` which was before our major cleanup of the schematics and it potentially broken. Can you try without `--migrate-only`?

**Comment by crutchcorn** [comment]
The reason I did `--migrate-only` was because I had already ran `ng update` and had errors thrown (due to something totally unrelated) but didn't want to go back to an older package.json and `npm i` again, so I thought the `migrate-only` would run the same migrations without modifying `package.json`. I can go back to an older commit, try again, and report back later

**Comment by DevVersion** [comment]
Yeah, the `--migrate-only` option is somehow ambiguous. Based on the source code for the `ng update` command, it just runs the schematics for the version that is currently installed. 

So in that case it would run the schematics from `v6.4.0`

**Comment by DevVersion** [comment]
It does have an effect if you are on a higher version but you still want to run the migrations for a previous version. If you already upgraded to `7.0.3` and then ran `ng update` then it should technically run the latest schematic code. I ran without `--migrate-only` and it worked fine on various projects. 

Do you have some more information? The `attribute-selectors` folder should be there in all cases. Can you:

* Make sure you've updated the CDK as well?
* Could you run: `ls ./node_modules/\@angular/cdk/schematics/ng-update/upgrade-rules`

That would be awesome. Thanks in advance!

**Comment by DevVersion** [comment]
Also to make it a bit more clear: For example if you run `ng update @angular/material` and you are on V6, the CLI updates immediately to V7 and then runs the migrations from our V7 code base for V6 *and* V7.

**Comment by adamdport** [comment]
I got this trying to update from 6.4.5. I did not set the `--migrate-only` switch. I just ran `ng update --all --force --registry <my-company-registry>`. As of this post, latest material is 7.0.3.

**Comment by adamdport** [comment]
...running `ng update @angular/material` didn't throw the error, but immediately running `--all --force` later on finished with the error again: 

    added 164 packages from 113 contributors, removed 146 packages, updated 199 packages and moved 10 packages in 214.904s
    Could not find custom rule directory: ./attribute-selectors/

**Comment by DevVersion** [comment]
@adamdport I've set up several projects using Angular Material V6, and tried running `ng update @angular/material` (also tried with `--force` and `--all`) and it worked as expected.

I'm not able to investigate further without more information. It would be good if someone could run 

* `ls ./node_modules/\@angular/cdk/schematics/ng-update/upgrade-rules` 
* `cat ./node_modules/\@angular/cdk/package.json | grep version` 

after the failure shows up in the console.

**Comment by DevVersion** [comment]
Closing as there is not enough information provided. Sorry, I'm not able to help without any reproduction. I've verified against various _but limited_ projects, but can't figure out what breaks for you guys.

**Comment by Roelensdam** [comment]
I have the same issue when upgrading from 6.1.8 to 7.2.0. (`Could not find custom rule directory: ./attribute-selectors/`)

I did `dir ./node_modules/\@angular/cdk/schematics/ng-update/upgrade-rules` as it's the windows version of `ls ./node_modules/\@angular/cdk/schematics/ng-update/upgrade-rules`

> 
> Répertoire : C:\Git\front_myethias_sso\node_modules\@angular\cdk\schematics\ng-update\upgrade-rules
> 
> Mode                LastWriteTime         Length  Name
> ----                -------------         ------ ----
> d-----         08-01-19     14:26                    attribute-selectors
> d-----         08-01-19     14:26                    class-inheritance
> d-----         08-01-19     14:26                    class-names
> d-----         08-01-19     14:26                    css-selectors
> d-----         08-01-19     14:26                    element-selectors
> d-----         08-01-19     14:26                    input-names
> d-----         08-01-19     14:26                    misc-checks
> d-----         08-01-19     14:26                    output-names
> d-----         08-01-19     14:26                    property-names
> d-----         08-01-19     14:26                    signature-check
> -a----         26-10-85     10:15            570 index.d.ts
> -a----         26-10-85     10:15           2440 index.js
> -a----         26-10-85     10:15           1094 index.js.map
> -a----         26-10-85     10:15            463 project-tsconfig-paths.d.ts
> -a----         26-10-85     10:15           2780 project-tsconfig-paths.js
> -a----         26-10-85     10:15           1747 project-tsconfig-paths.js.map
> -a----         26-10-85     10:15           1380 tslint-config.d.ts
> -a----         26-10-85     10:15           3136 tslint-config.js
> -a----         26-10-85     10:15           1501 tslint-config.js.map
> 

We can see that the "attributes-selectors" is there.

And here is the content of the "/node_modules/@angular/cdk/package.json

```
{
  "_from": "@angular/cdk@^7.2.1",
  "_id": "@angular/cdk@7.2.1",
  "_inBundle": false,
  "_integrity": "sha512-oU1Pjq3JkDtkXquLxWK84A2jOCeYRf352dVGbQCxWoSOQ5KBtMAd42huGidPiOSHN6/f7xZwL3n4fq3fVIut8A==",
  "_location": "/@angular/cdk",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "@angular/cdk@^7.2.1",
    "name": "@angular/cdk",
    "escapedName": "@angular%2fcdk",
    "scope": "@angular",
    "rawSpec": "^7.2.1",
    "saveSpec": null,
    "fetchSpec": "^7.2.1"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/@angular/cdk/-/cdk-7.2.1.tgz",
  "_shasum": "f3673d026a0a38f93629bbd67039bbbb50a36f1c",
  "_spec": "@angular/cdk@^7.2.1",
  "_where": "C:\\Git\\front_myethias_sso",
  "bugs": {
    "url": "https://github.com/angular/material2/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "parse5": "^5.0.0",
    "tslib": "^1.7.1"
  },
  "deprecated": false,
  "description": "Angular Material Component Development Kit",
  "es2015": "./esm2015/cdk.js",
  "homepage": "https://github.com/angular/material2#readme",
  "keywords": [
    "angular",
    "cdk",
    "component",
    "development",
    "kit"
  ],
  "license": "MIT",
  "main": "./bundles/cdk.umd.js",
  "module": "./esm5/cdk.es5.js",
  "name": "@angular/cdk",
  "ng-update": {
    "migrations": "./schematics/migration.json"
  },
  "optionalDependencies": {
    "parse5": "^5.0.0"
  },
  "peerDependencies": {
    "@angular/core": ">=7.0.0",
    "@angular/common": ">=7.0.0"
  },
  "releaseGitBranch": "7.2.x",
  "releaseGitCommitSha": "22b0ad61357415982742c387027ae09ba5d52199",
  "releaseGitUser": "Miles Malerba <mmalerba@google.com>",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/angular/material2.git"
  },
  "schematics": "./schematics/collection.json",
  "sideEffects": false,
  "typings": "./cdk.d.ts",
  "version": "7.2.1"
}
```

I hope it helps for the resolution.
