### ISSUE TITLE
Clicking many times on md-button displays the scrollbar

### ISSUE THREAD

**Issue by tommysella** [angular/material2#1392]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Not showing the scrollbar after many clicks (like it is for a normal normal button 
![image](https://cloud.githubusercontent.com/assets/8840471/19011994/988e22ae-87a7-11e6-99e3-0c1f938154e7.png)
).

#### What is the current behavior?

When clicking a md-button many times, after some clicks the scrollbar in the browser shows. This does not happen for a normal button (
![image](https://cloud.githubusercontent.com/assets/8840471/19011995/9c525af4-87a7-11e6-9f2d-1c15f08f7404.png)
).

#### What are the steps to reproduce?

1. Use angular CLI (version 1.0.0-beta.16) to create a project.
2. Add angular 2 material  according to the getting started guide (https://github.com/angular/material2/blob/master/GETTING_STARTED.md).
3. In the app.component.html add a md-button under the h1-tag like the following example:

![image](https://cloud.githubusercontent.com/assets/8840471/19011987/591961a6-87a7-11e6-841d-9e36b95fd396.png)

4. Click a few times on the button and after some clicks the scrollbar shows.

#### Which versions of Angular, Material, OS, browsers are affected?

Angular version 2.0.0
Material version: 2.0.0-alpha.9-3
OS: Windows 10
Error shows in both Chrome and Microsoft Edge

**Comment by hesxenon** [comment]
Can confirm, it appears that some "ripple divs" are not cleaned up?
![alt text](https://i.imgur.com/HIgUCQ8.png "Divs not cleaned up")

**Comment by RoxKilly** [comment]
You may need to include `core.css` styles.  See #1105

**Comment by hesxenon** [comment]
thanks @RoxKilly, you pointed me in the right direction, see more here:

https://github.com/angular/material2/issues/1139#issuecomment-249809135

**Comment by jelbourn** [comment]
Closed as solved.
