### ISSUE TITLE
CdkOverlayOrigin and CloseScrollStrategy

### ISSUE THREAD

**Issue by skoropadas** [angular/material2#13923]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
CdkOverlayOrigin not emit detach output when scroll strategy is CloseScrollStrategy

#### What is the current behavior?
detach output not emitted event

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-143kfh
Press toggle button. scroll the container, and see isOpen value in caption

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.0.2
Cdk: 7.0.2

#### Is there anything else we should know?

**Comment by crisbeto** [comment]
This is fixed in https://github.com/angular/material2/pull/7950 which has been open for a while. Should we have another go at presubmitting it @jelbourn?

**Comment by skoropadas** [comment]
@crisbeto To fix this, need subscribe to the overlayContainerRef.detachments and call this.detach method in CdkOverlayOrigin directive. #7950 don't fix the current bug.

**Comment by crisbeto** [comment]
That's exactly what it's doing here: https://github.com/angular/material2/pull/7950/files#diff-3a80596af2bb5fefb10ac0b3a932d14dR263

**Comment by skoropadas** [comment]
@crisbeto sorry I didn't notice, you're right

**Comment by skoropadas** [comment]
Guys this bug is reproduced in 7.2.1
