### ISSUE TITLE
Unit Test Examples

### ISSUE THREAD

**Issue by leonaAtkins** [angular/material2#13925]
#### proposal:
To include unit tests with examples, not just examples by themselves, but give instructions on how developers can unit test the features, even if just a basic framework, how developers can best test the results of the features.
For example given 
```
class MyComponent {
  constructor(breakpointObserver: BreakpointObserver) {
    breakpointObserver.observe([
      Breakpoints.HandsetLandscape,
      Breakpoints.HandsetPortrait
    ]).subscribe(result => {
      if (result.matches) {
        this.activateHandsetLayout();
      }
    });
  }
}
```
how would someone test that 
``` this.activateHandsetLayout() ```
had been called or not called in different scenarios 
What boilerplate setup would be required, what mocks would be needed, etc.

#### What is the expected behaviour?
When viewing the documentation, as well has having examples of how to use the features, also have examples on how we can test them.

#### What is the current behaviour?
No examples of unit tests.

#### What are the steps to reproduce?
N/A

#### What is the use-case or motivation for changing an existing behaviour?
We need to implement software quickly and also be able to write test suits quickly, this currently isn't possible and is slowing down development.

**Comment by jelbourn** [comment]
I'm going to close this into #14510, which is something we plan to do in 2019.
