### ISSUE TITLE
Mat-tab locates the current tab error when this tab is displayed asynchronously

### ISSUE THREAD

**Issue by 2eron** [angular/material2#13939]
#### Bug, feature request, or proposal:
Bug. The currently selected tab is hide by default, and its status based on asynchronous results.

#### What is the expected behavior?
When the page is loaded, the selected tab should be located correctly.

#### What is the current behavior?
The currently selected state will move to the next one of the asynchronous tab.

#### What are the steps to reproduce?
https://angular-wns1nm.stackblitz.io/

The Sync Tab is the selected tab, and it will be displayed in 3s, but after displayed, the selected state move to the  Third tab.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.10 
Angular Material 6.4.7

**Comment by josephperrott** [comment]
I am not quite sure I follow.  Based on your demo it appears to be working as expected.

The selected tab index is `2` which is the 3rd tab currently in the tab group.  When the observable emits the event after 3 seconds, the `*ngIf` evaluates to `true` and the tab is added into the group.  When the tab is added the currently selected tab value is updated to reflect the selected tab's new index.
I forked your [stackblitz here](https://stackblitz.com/edit/angular-mvgcor?file=src/app/tabs-demo.component.ts) to add showing the current tab index to illustrate this.

**Comment by 2eron** [comment]
> I am not quite sure I follow. Based on your demo it appears to be working as expected.
> 
> The selected tab index is `2` which is the 3rd tab currently in the tab group. When the observable emits the event after 3 seconds, the `*ngIf` evaluates to `true` and the tab is added into the group. When the tab is added the currently selected tab value is updated to reflect the selected tab's new index.
> I forked your [stackblitz here](https://stackblitz.com/edit/angular-mvgcor?file=src/app/tabs-demo.component.ts) to add showing the current tab index to illustrate this.

While the update of the current tab is not I expected.  Follow this, when all tabs are loaded, click the tab `Async tab`, then refresh the page, and what I expect is the selected tab is still `Async tab`, but the result is after the `Async tab` displayed, the current tab become to the tab `Third`.  Can you see what I'm saying? I think if you set the selected index, you probably shouldn't update it, whether or not the tabs are increased or decreased.

**Comment by josephperrott** [comment]
This is working as expected because holding the selected state of both if the async tab is shown and which tab is selected is something that is the responsibility of the developer.

When the page is refreshed, all of the components are initialized from the beginning once more and the same state is reached as it was initially.

It was an  intentional choice to only automatically updating the `selectedIndex` if a tab is added affects the index of the current tab.  This is because the `selectedIndex` represents which tab's content is showing and that the tab's content shouldn't change because of a change in the selected index.

**Comment by 2eron** [comment]
> This is working as expected because holding the selected state of both if the async tab is shown and which tab is selected is something that is the responsibility of the developer.
> 
> When the page is refreshed, all of the components are initialized from the beginning once more and the same state is reached as it was initially.
> 
> It was an intentional choice to only automatically updating the `selectedIndex` if a tab is added affects the index of the current tab. This is because the `selectedIndex` represents which tab's content is showing and that the tab's content shouldn't change because of a change in the selected index.

Okay, I got it.
