### ISSUE TITLE
How to use Material Design 2018 spec

### ISSUE THREAD

**Issue by jacobfederer** [angular/material2#13941]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?

The release notes of the 7.0.0 update say that the new version has
> Updated component styles throughout the library matching the 2018 Material Design Spec refresh.

Now I'm trying to make use of this aligned styles with the 2018 spec but couldn't find any documentation on how to use it. For example I would like to use text fields/ inputs as outlined or filled variants like this: 

<img width="761" alt="bildschirmfoto 2018-11-02 um 19 41 27" src="https://user-images.githubusercontent.com/1516212/47916103-9f7e7580-ded7-11e8-845e-d597ca1d528b.png">

#### What is the current behavior?

Currently inputs still look like this:

<img width="534" alt="bildschirmfoto 2018-11-02 um 19 44 48" src="https://user-images.githubusercontent.com/1516212/47916164-d18fd780-ded7-11e8-88c6-15503a638a34.png">

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

7.0.2

**Comment by Eddygn** [comment]
Unless I misunderstand you question, you can find them here: 
https://material.angular.io/components/form-field/overview

It's under "Form field appearance variants".

In essence:
it's an `appearance` attribute on the `mat-form-field` tag

appearance="outline"
appearance="fill"

From the examples:
```
  <mat-form-field appearance="outline">
    <mat-label>Outline form field</mat-label>
    <input matInput placeholder="Placeholder">
    <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
    <mat-hint>Hint</mat-hint>
  </mat-form-field>
```

```
  <mat-form-field appearance="fill">
    <mat-label>Fill form field</mat-label>
    <input matInput placeholder="Placeholder">
    <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
    <mat-hint>Hint</mat-hint>
  </mat-form-field>
```

**Comment by josephperrott** [comment]
Closing as the the variants of the form fields defined in the latest spec are available and documented [here](https://material.angular.io/components/form-field/overview)
