### ISSUE TITLE
md-input changing un-focus text and under-line color

### ISSUE THREAD

**Issue by bkarv** [angular/material2#1394]
![screen shot 2016-10-01 at 10 41 08 pm](https://cloud.githubusercontent.com/assets/10624315/19014140/3dfbcbb2-8828-11e6-8abc-d49e004a030f.png)
Hi,
Very excited with the progress being made, excellent work and thank you.

I have simple question, is it possible to change md-input text color and line color when it is un-focused? For example I am using md-input on a dark background hence would like a white font and underline.

**Comment by JanStureNielsen** [comment]
@bkarv -- the GitHub issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.

**Comment by vinagreti** [comment]
If you look at md-input theme and component scss files you will find out how they implement it. It is easy to customize for your needs.
I think you should look at theming.md file. Theming allow you to customize your components based in a theme.
I've made a PR #1385 that explain a little more about theming custom components. I do not know if it is the better way of doing this but is the way I've found.

**Comment by bkarv** [comment]
I tried stackoverflow and no luck as this is something. I've using css selectors eg #test input:first-child {color:white;} and no luck. Just want to if it is actually possible?

**Comment by MarouaneSH** [comment]
To change label color and underline : 
`mat-focused .mat-form-field-label{
  color: #ee6e73;
}
.mat-focused .mat-form-field-underline .mat-form-field-ripple{
  background: #ee6e73;
}`

**Comment by JaimeBulaHNP** [comment]
> To change label color and underline :
> `.mat-focused .mat-form-field-label{ color: #ee6e73; } .mat-focused .mat-form-field-underline .mat-form-field-ripple{ background: #ee6e73; }`

This Works, thaks MarouaneSH

**Comment by ashaikh-wal** [comment]
.mat-form-field-appearance-legacy {
  .mat-form-field-underline {
    height: 0 !important;
  }
  .mat-form-field-wrapper{
    padding-bottom: 0 !important;
  }
  .mat-form-field-infix{
    // padding: 0 !important;
    border-top: 0 !important;
  }
}

.mat-focused {
  .mat-form-field-label
  { 
    color: #78818b !important; 
  } 
  .mat-form-field-underline {
    .mat-form-field-ripple {
      display: none !important; 
    }
  }
}

**Comment by MarouaneSH** [comment]
@JaimeBulaHNP you welcome 👌
