### ISSUE TITLE
Accordion in dialog starts open and jerks closed

### ISSUE THREAD

**Issue by johnchristopherjones** [angular/material2#13954]
#### Bug, feature request, or proposal:
When an accordion is placed in a dialog, the accordion starts in the open position and then jerks closed.  The jerking appears to happen at the end of the dialog open animation.

#### What is the expected behavior?
An accordion in a dialog should be in its closed position during the dialog animation.

#### What is the current behavior?
The accordion is open during the dialog animation and jerks closed afterwards.

#### What are the steps to reproduce?
1. Create a dialog that contains an accordion
2. Open the dialog

StackBlitz: https://angular-material2-issue-vo7but.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?

I have a dialog that has a long-ish selection list, broken up into sections with accordions.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    "@angular/core": "^7.0.2",
    "@angular/material": "^7.0.2",
    "typescript": "3.1.6",

Chrome 70.0.3538.77

macOS 10.14.1

**Comment by crisbeto** [comment]
A fix for this was merged in yesterday. See https://github.com/angular/material2/pull/13888.
