### ISSUE TITLE
 cdk-virtual-scroll with mat-autocomplete works irregular

### ISSUE THREAD

**Issue by ilseh** [angular/material2#13958]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
On using cdk-virtual-scroll in the mat-autocomplete, when scrolling slowly (in chrome, using scroll arrow down), scrolling is expected to work no matter how far one is in the list. It is expected to work like in the mat-select.

#### What is the current behavior?
On using the cdk-virtual-scroll in the mat-autocomplete, when scrolling slowly (in chrome, using scroll arrow down), scrolling seems to stall around the max buffer size.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-xv1n2e?file=src/app/app.component.html

This contains example with mat-autocomplete compared with mat-select (which seems to work fine)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular, Material, CDK: version 7
Typescript: 3.1
Chrome: Version 70.0.3538.77 (Official Build) (64-bit)
Ubuntu: Version 70.0.3538.77 (Official Build) (64-bit)
Windows 10

#### Is there anything else we should know?
On stackoverflow: https://stackoverflow.com/questions/53073943/cdk-virtual-scroll-with-mat-autocomplete-works-irregular

**Comment by mmalerba** [comment]
Closing this issue as virtual scroll integration with various material components is being tracked here: https://github.com/angular/material2/issues/10122
