### ISSUE TITLE
Error state for <md-input>

### ISSUE THREAD

**Issue by siva636** [angular/material2#1396]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
There should be an error state for `<md-input>`, like shown bellow, as described in the [specification](https://material.google.com/components/text-fields.html#text-fields-single-line-text-field).
![error](https://cloud.githubusercontent.com/assets/3191656/19014487/a419b958-880b-11e6-8e7f-8c5731e76cad.png)

#### What is the current behavior?
There seem to be no out of the box way to show error state.

**Comment by jelbourn** [comment]
See #348
