### ISSUE TITLE
mat-table-component has conflict with ng-zorro-antd

### ISSUE THREAD

**Issue by shenchaoran** [angular/material2#13968]
**Bug report**
when use ng-zorro-antd and material simultaneously, got some error like:  `Error: Missing definitions for header, footer, and row; cannot determine which columns should be rendered.`

**Enviroment:**
angular              7.0.2
material             7.0.2
ng-zorro-antd   1.8.0

**Reproduce [here](https://stackblitz.com/edit/ng-material-starter)**

**Comment by andrewseguin** [comment]
Reproduction example is not showing any errors. Please re-open if you can reproduce the issue so we can investigate

**Comment by shenchaoran** [comment]
still conflict, please find [here](https://stackblitz.com/edit/mat-table-conflict-with-zorro)

**Comment by andrewseguin** [comment]
As far as I can tell, this is being caused because zg-zorro-antd is defining its own directives and components that also match table selectors (e.g. `tr`)

Rather than importing the whole module, perhaps just import only the component modules you need from ng-zorro-antd

**Comment by shenchaoran** [comment]
got it, actually it's because of `NzTableModule` in ng-zorro-antd. I import the ng-zorro-antd module separately solved this problem, thanks

**Comment by chitayta** [comment]
@shenchaoran Can you share in details how to import ng-zorro-antd modules separately? I tried to import them individually on app.ts.module, it's OK with "ng build" command but got an error when trying "ng build --prod".

![image](https://user-images.githubusercontent.com/20698545/54580434-a1864280-4a3a-11e9-82ac-982ae05b2392.png)

**Comment by shenchaoran** [comment]
Sorry, I tried but failed.
According the official docs, ng-zorro-antd doesn't recommend importing
separately, please find here
<https://ng.ant.design/docs/faq/en#why-individually-importing-is-not-supported>
.
So maybe you should avoid importing MatTableModule where you are using
ng-zorro-antd.

chitayta <notifications@github.com> 于2019年3月19日周二 下午12:32写道：

**Comment by chitayta** [comment]
Thanks so much, @shenchaoran.
Seems that's right. :D
