### ISSUE TITLE
*cdkDragPreview directive is not updating when parent has ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by tocjent** [angular/material2#13979]
#### Bug, feature request, or proposal:
Bug (or proposal)

#### What is the expected behavior?
*cdkDragPreview should update with OnPush change detection strategy (or there should be a note about this in the docs)

#### What is the current behavior?
*cdkDragPreview directive is not updating when parent has OnPush change detection strategy.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-pwtsl2?file=app/cdk-drag-drop-custom-preview-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cdk: 7.0.2
Typescript: 3.1.3
Chrome: Version 70.0.3538.77 (Official Build) (64-bit)
Ubuntu 18.04

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material2/pull/13703.
