### ISSUE TITLE
Calendar view similar to Outlook / Mac Calendar / etc

### ISSUE THREAD

**Issue by smnbbrv** [angular/material2#13980]
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

I'd like to have a full-page calendar view, e.g. like macos calendar, outlook, etc.

Currently I am using a self-written thing (not that complicated to do that, though), however I'd like a natively supported component for this.

That's what I have so far:

![image](https://user-images.githubusercontent.com/13453858/47988712-43883c80-e0e3-11e8-9f79-171d4829eb43.png)

The expected functionality would be:

- month / week / year (?) view
- custom content for each day (like e.g. mat-table does it)
- ability to set date formatting / theming for each day (which I guess is a part of the previous point, however it's important to mention it)
- scrollable
- as lazy as possible (if the endless scrolling is taking place)
- of course responsive

#### What is the current behavior?

No calendar widget / tool available

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by josephperrott** [comment]
Closing as this is not something that is defined by the Material Spec and therefore is not something we are likely to implement.
