### ISSUE TITLE
cdk virtual scrolling working abnormally on mat-tab-group

### ISSUE THREAD

**Issue by rodent129** [angular/material2#13981]
#### Bug, feature request, or proposal:
1. cdk virtual scrolling position calculation error on mat-tab-group.  If the virtual scroll component is not the first tab, put it second tab or later, the content positions are not correct at all. 
The second tab use the virtual scrolling, then can see the issue clearly.
2. scroll content up/down by using arrow keys, it stop to scroll at some point.
#### What is the expected behavior?
1. To calculate the positioning of the contents of correctly.
2. up/down arrow keys, can scroll correctly without stopping at some point.
#### What is the current behavior?
content position got weird.

#### What are the steps to reproduce?
[https://stackblitz.com/edit/angular7-virtual-scroll-issue?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/angular7-virtual-scroll-issue?file=src%2Fapp%2Fapp.component.html)
[https://github.com/rodent129/angular7-virtual-scroll](https://github.com/rodent129/angular7-virtual-scroll)

#### What is the use-case or motivation for changing an existing behavior?
If not changed, then cannot use virtual scrolling

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 7.0.2
Material - 7.0.2
TypeScript - 3.1.6
Browser - Chrome 70.0.3538.77
OS - Mac high Sierra

**Comment by mmalerba** [comment]
It looks like it works if I switch the order of the tabs: https://stackblitz.com/edit/angular7-virtual-scroll-issue-tf6mdz?file=src/app/app.component.html

I think what's happening is that it's calculating the height of the viewport when the tab is still hidden and then caching it and never updating it even once the viewport is shown. I do have an open feature request for adding support this: https://github.com/angular/material2/issues/10117
