### ISSUE TITLE
package name changed?

### ISSUE THREAD

**Issue by samdevx1029** [angular/material2#1399]
#### Bug, feature request, or proposal:
Package name @angular/material does not seem to exist. I think the name changed to @angular2-material. If that is the case, the documentation at this repo should be updated.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by jelbourn** [comment]
See the changelog.
