### ISSUE TITLE
Release alpha.0

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#140]
- [x] Inline html and css (#153)
- [x] All sources are either in `components/` or `core/`
- [x] Add `package.json` for each component
- [x] Create CommonJS modules for npm 
- [x] Something something re-exports
- [x] Release script to perform all of the steps for publishing.
- [x] Publish `angular2-material` plus scoped packages for each component and core (w/ `angularcore` login)

For now, everything in `core/` will be considered one (scoped) npm package and components depending on it as necessary. Eventually things can be moved _out_ of core and into a separate package (something like `angular2-component-kit`). 

A part 2 for this will be creating a SystemJS config and output (for demos, plunkers, etc.), but that may be a good follow-up for a community member.

**Comment by d3viant0ne** [comment]
Sounds like fun, I'll pick it up :)

**Comment by jelbourn** [comment]
Released!

**Comment by d3viant0ne** [comment]
@jelbourn - May be worth noting in the README that you need https://git-lfs.github.com/ to clone material2 now

**Comment by jelbourn** [comment]
@d3viant0ne filed https://github.com/angular/material2/issues/170
