### ISSUE TITLE
Snackbar extends off screen on small mobile devices (iPhone 5 is 320px, snackbar has min-width: 344px;)

### ISSUE THREAD

**Issue by adamdport** [angular/material2#14008]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Snackbar should look good on all major devices

#### What is the current behavior?
Snackbars on small devices extend beyond the device's width

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-jnypqb

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.0.2

**Comment by crisbeto** [comment]
Fixed by https://github.com/angular/material2/pull/13880.
