### ISSUE TITLE
(menu) - export the items count

### ISSUE THREAD

**Issue by TKul6** [angular/material2#14005]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
When a menu has no items the trigger should be hidden / disabled, otherwise the client press on a button that do nothing.

Currently I'm working on a wrapper that accept the menu from the nested component.
I can't know what `menu-item`s would be provided, but I know I don't want to show the trigger button if the menu is empty.

I know in the past there was a query list, but now it's deprecated.

Is there any way to know from the menu itself it it has no children items? (instead of passing around another input to indicate if the menu should be visible)?

#### What is the current behavior?
The menu will be opened even if there are no items to presents

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-6e1x8z-6pd65g

#### What is the use-case or motivation for changing an existing behavior?
Mentioned above

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.0.2
Node: 9.0.0
OS: win32 x64
Angular: 7.0.0
... compiler, core

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@angular/cli                 7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3
material              7.0.2

#### Is there anything else we should know?
Maybe the default behavior is fine, but I really think there should be an indicator in the menu level if it has children items or not.

Thanks

**Comment by crisbeto** [comment]
> I can't know what menu-items would be provided, but I know I don't want to show the trigger button if the menu is empty.

Why wouldn't you know which items are provided? I'm assuming that you'll have something like:

```html
<mat-menu>
  <button *ngFor="let item of items">{{item}}</button>
</mat-menu>
```

In this case you can look at the `length` of the items. The `MatMenu` component does expose the `items` property which contains the amount of items in the menu, but you should keep in mind that using it in the view might lead to "Changed after checked" errors.

**Comment by TKul6** [comment]
Thanks for the response.
Unfortunately, my case is not so easy.

As I mentioned above, the menu button is inside a infrastructural component. 

The user can wrap his component around his component and **provide a template for the menu itself** Meaning I don't have something like 
`<button *ngFor="let item of items">{{item}}</button>`.

I guess it's more like this example: https://stackblitz.com/edit/angular-material2-issue-rrryta

You can see that from the `wrapper` component I can't have any indication whether the mat-menu provided from `app.component` has items.

(I actually have another layer of abstraction  that renders a `ng-template` inside the `mat-menu`, but I think the stackblitz demonstrate the problem)

Do you have any suggestions?

Thanks

**Comment by TKul6** [comment]
It seems the `items` property is deprecated (At least from the documentation), that's why I started this issue from the first place.

Is there any other way to achieve that?

Thanks
