### ISSUE TITLE
fix (mat-select): do not allow ctrl + arrowUp/arrowDown when mat-select closed and focused

### ISSUE THREAD

**Issue by d8dev** [angular/material2#14003]
**Bug, feature request, or proposal:**
Bug.

**What is the expected behavior?**
When `mat-select` closed and focused, switching should not work with `ctrl + ArrowUp` / `ctrl + ArrowDown` ,like in classic html select.

**What is the current behavior?**
When `mat-select` closed and focused I can switch option with  `ctrl + ArrowUp` / `ctrl + ArrowDown` hotkeys.

**What are the steps to reproduce?**
[Demo Stackblitz](https://stackblitz.com/edit/angular-material-select-bug)

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**
Windows 10 Pro 64bit, Google Chrome Version 70.0, Mozilla Firefox 63.0.1, Angular 6 / 7, Angular Material 6 / 7, TypeScript 3.1.

**Comment by crisbeto** [comment]
Should be resolved by https://github.com/angular/material2/pull/13503.

**Comment by d8dev** [comment]
Great, thx!

**Comment by crisbeto** [comment]
Closing since #13503 got in a while ago.
