### ISSUE TITLE
svgIcon directive wrongly mangles URLs to filters in internal SVG defs

### ISSUE THREAD

**Issue by tarekis** [angular/material2#14002]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
For the directive not to mangle the `url` to the filter

#### What is the current behavior?
The directive mangles the filter url (`filter="url(#filter-1)"`) to a relative url: `filter="url(current/route#filter-1)"`
In some cases - frankly I do not know *why* - this breaks the SVG, the browser requests the URL, it fails and the SVG won't get displayed.
Example file here: https://stackblitz.com/edit/angular-4mu1bl?file=assets%2Fimg%2Fexamples%2Fmodal-trap-open.svg

#### What are the steps to reproduce?
Reproduction Project: 
[icontest.zip](https://github.com/angular/material2/files/2552337/icontest.zip)
(StackBlitz reproduction not possible, original material StackBlitz does not work either, "throws" `Error retrieving icon: <svg> tag not found`, see: https://stackblitz.com/angular/gknedddpamx)

#### What is the use-case or motivation for changing an existing behavior?
This worked back in `5.0.3`, for some reason it no longer does as of `7.0.1` (or previous, did not check specific versions).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Could reproducte this with:
`@angular/core@7.0.1`
`@angular/material@7.0.1`
`typescript@3.1.3`

OS: Ubuntu 16.04 LTS

Browsers:
Chrome  68.0.3440.84
Firefox 63.0

Other versions or version combinations could be affected.

**Comment by crisbeto** [comment]
Do you have any query parameters in your URL? If you do, you might be hitting the same issue as https://github.com/angular/material2/issues/13924.

**Comment by tarekis** [comment]
Sorry about the late reply, the linked issue is exactly the reason the SVG breaks on this specific route:
> In some cases - frankly I do not know why - this breaks the SVG [...]

On the other hand, why are "external" resources getting prefixes inside SVGs, and why are they getting prefixed with the _current_ route? Is this intended in the case of the SVG i have linked?

As you can see, the filter is in the SVG's own `defs`, a prefix would not be neccesary, I am not an expert in SVGs, but to me it seems this simply gets ignored, as it does not seem to have any effect other than generating a (obsolte?) request.

**Comment by crisbeto** [comment]
The resources get prefixed with the current path in order to smooth out some cross-browser issues. See https://github.com/angular/material2/issues/9276.

**Comment by tarekis** [comment]
Alright, AFAICT the behavior is all intended in this case then, which makes this a duplicate of #13924, closing this.
