### ISSUE TITLE
md-checkbox easy way to size?

### ISSUE THREAD

**Issue by J-Siu** [angular/material2#1401]
#### Bug, feature request, or proposal:

Not sure if this is a bug.
#### What is the expected behavior?

Need an easy way to size md-checkbox.
#### What is the current behavior?

There doesn't seems to be a way to change md-checkbox size easily.
#### What are the steps to reproduce?

http://plnkr.co/edit/PMez6Y?p=preview

Currently I override md-checkbox inner objects' properties to change md-checkbox size:

```
    .custom .md-checkbox-inner-container {
      height: 12px;
      width: 12px;
    }

    .custom .md-checkbox-label {
      line-height: 12px;
    }
```

But this seems overly hackish.
#### What is the use-case or motivation for changing an existing behavior?

UI elements size is always base on interface design and needs. 
#### Which versions of Angular, Material, OS, browsers are affected?

Angular: 2.0.0
Material: 2.0.0-aplha.9
OS X
Browser: Safari, Chrome
#### Is there anything else we should know?

I have to do similar thing to create md-toolbar with custom height.

**Comment by jelbourn** [comment]
@traviskaufman Should checkbox size be configurable?

**Comment by J-Siu** [comment]
@jelbourn Let say we use material2 to create a voting page / apps, and showing options with font size 64. I updated my plunker: http://plnkr.co/edit/PMez6Y?p=preview

**Comment by jelbourn** [comment]
We're not officially supporting changing the size of the controls just now. In the future we'll be adding different density configuration options.
