### ISSUE TITLE
feat(cdkDropList): Add configuration input to prevent list rearranging

### ISSUE THREAD

**Issue by dpsthree** [angular/material2#14027]
#### Bug, feature request, or proposal:
Add an input property to cdkDropList directive that prevents the draggable elements within it from rearranging. For example:
`@Input() preventRearrange: boolean = false`

#### What is the expected behavior?
When preventRearrange is set to true the other elements within the drop list would remain in the initial position while the user is dragging an element. When set to false, cdkDropList would behave as it does now.

#### What is the current behavior?
There is currently no way to prevent list items from rearranging

#### What is the use-case or motivation for changing an existing behavior?
This is useful for features in which the user is expected to move items between lists, but the order is determined by sources other than the user. For example, if two lists are supposed to remain in alphabetical order, but users can move items from one list to the other.

This would also make it easier to develop features where the item being dragged is not removed from the source list. For example, a tool pallet that allows for the dragging and dropping of the same item multiple times.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7+

**Comment by dpsthree** [comment]
Alternatively, the implementation of [arbitrary from/to without a dropList](https://github.com/angular/material2/issues/13987) could also solve this problem.

**Comment by princemaple** [comment]
@crisbeto looks like this one can be closed since your https://github.com/angular/material2/pull/15064 is in.

**Comment by crisbeto** [comment]
Thanks for the heads-up. Closing.
