### ISSUE TITLE
MatFormField with appearance="outline" draws line through the label if the form field starts out as "display: none."

### ISSUE THREAD

**Issue by grant77** [angular/material2#14031]
#### Bug, feature request, or proposal:
MatFormField with appearance="outline" draws line through the label if the form field starts out as "display: none."  Is see Bug #12555, but I don't think it covers this scenario.  I have provided a very simple stackblitz to duplicate.

#### What is the expected behavior?
There should not be a line going though the label.

#### What is the current behavior?
There is a line going though the label.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-ovrlab

#### What is the use-case or motivation for changing an existing behavior?
It's ugly.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/material": "7.0.2"

#### Is there anything else we should know?
No.

**Comment by mmalerba** [comment]
@crisbeto did your PR for this land yet?

**Comment by crisbeto** [comment]
Doesn't look like it has https://github.com/angular/material2/pull/13477.

**Comment by mmalerba** [comment]
closing as a dup of https://github.com/angular/material2/issues/13328, should be fixed by #13477
