### ISSUE TITLE
Calling open() on MatExpansionPanel via ViewChild reference opens the wrong panel

### ISSUE THREAD

**Issue by eitama** [angular/material2#14040]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Assuming: 
`<mat-expansion-panel #secondPanel>`

When I call :
`this.secondPanel.open();`

Which according to documentation should open the 2nd panel (bottom one)

#### What is the current behavior?
For some reason the top panel expands

#### What are the steps to reproduce?
1. https://stackblitz.com/edit/angular-v6n1yp
2. Click Open bottom panel button I have added, and watch as the wrong panel expands.

#### What is the use-case or motivation for changing an existing behavior?
To work as expected, to be able to progrematically open/close individual panels, which might or might not share the same accordion html element.
I tried :
- 2 accordion elements, each holding it's own panel
- 1 accordion holding both panels
- no accordions at all just panels

The behavior didn't change, it was wrong in all cases.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.0.3
Node: 8.11.3
OS: linux x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cdk                      7.0.2
@angular/cli                      7.0.3
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.0.2
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
    
[eitamd@localhost webui]$

**Comment by crisbeto** [comment]
That's because both of your `ViewChild` queries are returning the same panel. When you set `@ViewChild(MatExpansionPanel)`, Angular will find the first instance of `MatExpansionPanel`. You can switch it to `ViewChildren` so you get all of the panels.

**Comment by eitama** [comment]
> ViewChildren

Verified.  Thanks!

I misread the documentation of ViewChild.
I only have 2 panels, and even if more are added it's not dynamic, so I just changed :
@ViewChild(MatExpansionPanel) to @ViewChild('panel') and @ViewChild('secondPanel') and now I have proper references and it works :)

@crisbeto Thanks!
