### ISSUE TITLE
mat-input: text in input element does not respect theme when using dark theme

### ISSUE THREAD

**Issue by eTallang** [angular/material2#14048]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The input should have a text color that respects the selected theme

#### What is the current behavior?
If a `matInput` is placed within a container that uses a `mat-dark-theme` color scheme, the text color in the `matInput` remains black, while every other aspect of the form field respects the dark theme and turns light.

#### What are the steps to reproduce?
https://stackblitz.com/edit/mat-input-dark-theme-bug

#### What is the use-case or motivation for changing an existing behavior?
The input should be readable when using dark theme

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Testet using Angular Material v6.4.7 and 7.0.3, and the error is in both versions.

#### Is there anything else we should know?
No

**Comment by eTallang** [comment]
It appears to me that this issue extends far beyond only inputs. I've updated the Stackblitz with a `mat-icon`, `mat-slide-toggle`, `mat-radio-button` `[mat-button]` and `mat-checkbox`, and all of these components have dark text when used within a container using the `mat-dark-theme` scheme.

Please correct me if I'm wrong, or there's something that I've misunderstood regarding the use of the dark theme, because it surprises me if all of these components' styles are broken when using a dark theme and nobody has reported an issue about it.

**Comment by coltenkrauter** [comment]
I am experiencing the same issue. I am using a dark mode and the input box text is black so you can hardly see it.

**Comment by ccpony** [comment]
Surprised that this issue isn't getting more attention.  The dark mode is unusable in its current condition.

**Comment by eTallang** [comment]
Thanks for the reply @jelbourn. Does this mean that it's impossible to use the light theme for an application, while at the same time using the dark theme only for a isolated part of the same application (considering the dark theme has to be applied at the root level of the application if I understand you correctly)?

**Comment by ccpony** [comment]
Nope.  The issue with the angular material dark mode has been well documented for a long time.  Regardless of jelbourn's explanation, a theme is of no value if components can't be seen against the background.  What is very confusing to me is that there is no readily available end-user fix.  Some have suggested using the /deep/ combinator but /deep/ has been deprecated.  I've seen no other suitable fix.

So, yes.  This IS a bug and it needs to be addressed.

**Comment by jelbourn** [comment]
To clarify this a little more:
* All of those components use the current `font-color` (i.e. `currentColor`). The browser defaults this to black.
* The `angular-material-theme` mixin does not change the `font-color` because the mixin is not inherently scoped to any selector. I.e., when you write `@include angular-material-theme($theme)`, there is no universal selector on which `font-color` could be applied without being overly broad / destructive. 

The thing to do here, then, is to either set the `font-color` as part of the alternate theme definition:
```scss
.dark-theme {
  @include angular-material-theme($dark-theme);
  font-color: white;
}

Or to apply the `.mat-app-backround` class as a child or sibling of the `.dark-theme` class.
```

**Comment by ccpony** [comment]
Thanks jelbourn.  You're clearly more versed on this stuff than I am.  Can you be a bit more specific as to where I might apply your suggested fixes?

**Comment by ccpony** [comment]
Thanks jelbourn.  But the problem I face is not to change the color of the text or the placeholder.  What I've not been able to do is change the color of the mat-put component itself - - especially when focused.  That's the issue.

**Comment by mmalerba** [comment]
You can change the color to the primary, accent, or warn color of your theme. Based on the stackblitz it looks like you probably want color="accent" to make it yellow like your other components: https://stackblitz.com/edit/mat-input-dark-theme-bug-oeacdm?file=app/app.component.html

**Comment by ccpony** [comment]
Yes mmalerba - you can do that.  However, changing the accent color to accommodate mat-form-field completely changes the entire theme.  So... no.  That's really not a good fix.

**Comment by mmalerba** [comment]
@ccpony I don't understand what you're asking for, did you look at the stackblitz I posted? If that's not what you're trying to do can you please explain
