### ISSUE TITLE
SideNav in side mode does not hid the background

### ISSUE THREAD

**Issue by codemonkey00** [angular/material2#14045]
#### Bug, feature request, or proposal:
Upgraded from Angular 5.2.5 to 6.10.3 (material 5.2.5 to 6.4.7) and the SideNav [mode]='side' does not collapse completely.

#### What is the expected behavior?
Expected the side menu to completely hide when [opened]='false'

#### What is the current behavior?
My SideNav in [mode]='side' no longer sets the margin-left to 0 when [opened]="false", which displays the menu background color but the menu content hides.

#### What are the steps to reproduce?
StackBlitz version 5.2.5: https://angular5-mysite.stackblitz.io/home

StackBlitz version 6.10.3: https://angular6-mysite.stackblitz.io/home

#### What is the use-case or motivation for changing an existing behavior?
The behavior appears to have changed between the 2 versions.  The menu should still hide when it is collapsed instead of displaying the background.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Works as expected in Angular version 5.2.5 with Material version 5.2.5
Does not work in Angular version 6.10.3 with Material version 6.4.7
Tested in Chrome and Firefox and both have the same behavior.

#### Is there anything else we should know?
This is an issue with the side mode so the browser needs to be greater then 840, otherwise the menu will change to over mode.

**Comment by mmalerba** [comment]
It seems to work fine here: https://stackblitz.com/edit/angular-zlvzje?file=app/sidenav-overview-example.html I think what you're seeing in your example might be due to additional CSS that your app applies
