### ISSUE TITLE
Datepicker Value Example deserialization example doesn't demonstrate deserialization

### ISSUE THREAD

**Issue by gtranter** [angular/material2#14046]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If the date is changed using the picker or input field, the internal form control's value should continue to be an ISO string (produced via Date.toISOString()) as it was upon initialization.

#### What is the current behavior?
If the date is changed, the form control value becomes a date string via Date.toString().

#### What are the steps to reproduce?

Original Stackblitz example modified to display the form control value of the "deserialized" datepicker example: https://stackblitz.com/edit/angular-8o4o6f?file=app%2Fdatepicker-value-example.html

(Original Stackblitz example unmodified: https://stackblitz.com/angular/pmkpqodmjam)

On startup, note the value is an ISO string. Change the date and note that the value changes to a date string.

#### What is the use-case or motivation for changing an existing behavior?
the example does not properly demonstrate "deserialization" as intended. It is actually quite unhelpful.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.2, Material 7.0.3

**Comment by mmalerba** [comment]
The example does indeed show deserialization. The `FormControl` is initialized with a string, not a `Date` object. The datepicker deserializes this string and appropriately initializes the date. What you appear to be asking about is serialization. If you want to serialize a `Date` to a string, just use the native date's `toISOString()` method: https://stackblitz.com/edit/angular-8o4o6f-du8fqq?file=app/datepicker-value-example.html

**Comment by gtranter** [comment]
Seriously? The example is useless.

**Comment by mmalerba** [comment]
It demonstrates something other than what you're trying to accomplish, that doesn't make it useless

**Comment by gtranter** [comment]
I'm not trying to accomplish anything (with this example, not in general :)) I'm just looking at this example and thinking "what's the point?" While you may be able to make an argument that the ISO format date string is an example of a serialized date object, by calling the form control object "serializedDate" you are misleading users to believe that the form control is storing a serialized version of the selected date. And of course it doesn't, except upon initialization from the "serialized" ISO string. So that part of it is useless, or at least misleading.
