### ISSUE TITLE
mat-expansion-panel-header :hover style sticks after expansion

### ISSUE THREAD

**Issue by chrisrrowland** [angular/material2#14047]
#### Bug, feature request, or proposal:
If you use a custom style for the header, the hover style should go away after you click to expand a panel and mouse away.

#### What is the expected behavior?
After expanding the original style returns

#### What is the current behavior?
When you mouse over the header to expand, the hover style is applied.  When you expand and mouse away it stays until you click something else or perform some other sort of action on the page.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ojcyga

#### Is there anything else we should know?
Maybe this is not how you are intended to override the default style.  If so I'm not sure how that might be made more clear.

**Comment by jingleleung** [comment]
I found a simple workaround by setting the header background colors to `!important`
```
.header {
  background-color: #e4e1df !important;
}

.header:hover {
  background-color: #ffcb05 !important;
}
```

**Comment by crisbeto** [comment]
Closing since this is an issue with the custom styling, rather than Material.
