### ISSUE TITLE
Documentation of style differences between 5, 6 and 7

### ISSUE THREAD

**Issue by klmcwhirter** [angular/material2#14063]
#### Bug, feature request, or proposal:
Question - is there documentation showing / describing the style differences between Angular 5, 6 and 7?

Echoing the concerns in #13625, I need to estimate effort for moving to Angular 7 from 5.

We are utilizing custom themes where business requirements cause us to override default Material Design guide recommendations.

#### What is the expected behavior?
Documentation of changes across versions.

#### What is the current behavior?
Unknown - is there such documentation? I have not been able to find this information at material.io, material.angular.io or this github repo.

#### What are the steps to reproduce?
This is just a question / request for documentation.

#### What is the use-case or motivation for changing an existing behavior?
No change is being requested.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5 with desire to move to Angular 7. Chrome 70 is currently in use by our users.

#### Is there anything else we should know?
I want to echo the concerns raised in #13625. I do understand the arguments from the dev team, and agree with them. I want smaller bundle sizes and improved maintainability so you can more easily continue to produce this wonderful product.
But please keep in mind that as more people (especially enterprise customers) rely on the library we need help from you to enable us to justify the cost of upgrades to those who control our budgets.

Thanks for the hard work. @angular/material has come a long way ...

**Comment by jelbourn** [comment]
The canonical place for discovering changes like this is the [changelog](https://github.com/angular/material2/blob/master/CHANGELOG.md). I agree that it's not not robust, other than notes like "Updated to match 2018 spec". 

Going forward, what would be the most useful way to present this information?

**Comment by klmcwhirter** [comment]
I am not sure.

I do not think a visual format would be feasible although that would be ideal.

Perhaps a _one-pager_ that describes the items changing. We could use that as a checklist to go to the individual pages in the material.angular.io site for visual reference of current state.

But. as you can tell, wading through the change log is very difficult as a means for gleaning this information.

I only see this one line in the 7.0.0 release notes and no links for further details:
Updated component styles throughout the library matching the 2018 Material Design Spec refresh.

And I think that is the right level of detail for release notes.

But as I pointed out, it is not obvious where on the material.io site where to find that information either. _note, I will open a separate incident with them if required._

If they had a _What's New_ page you could just link to it maybe.

I am sure you have much more creative folks on your team than me. So I will defer to your best judgement.

Mainly wanted you to be aware of the need.

**Comment by jelbourn** [comment]
Going forward for major versions, we'll work on making the specific changes more clear and digestible. Closing since there's no direct action to take right now.
