### ISSUE TITLE
The documenation has CdkDragStarted event listed as CdkDragStart

### ISSUE THREAD

**Issue by kvabakoma** [angular/material2#14060]
#### Bug, feature request, or proposal:
There's an error in the documentation (https://material.angular.io/cdk/drag-drop/api#CdkDragStart).
The event CdkDragStarted is listed as CdkDragStart.

#### What is the expected behavior?
The event is called CdkDragStarted

#### What is the current behavior?
The documentation has it listed as CdkDragStart

#### What are the steps to reproduce?
Visit https://material.angular.io/cdk/drag-drop/api#CdkDragStart

#### What is the use-case or motivation for changing an existing behavior?
It took some time to find why CdkDragStart did not work 🤦‍♂️

**Comment by josephperrott** [comment]
The [outputted event is `cdkDragStarted`](https://github.com/angular/material2/blob/ba31c7207ae4538d11f0408d7da1c7d0cafa4e48/src/cdk/drag-drop/drag.ts#L204) but the event emits a an object with the [type of `CdkDragStart`](https://github.com/angular/material2/blob/ba31c7207ae4538d11f0408d7da1c7d0cafa4e48/src/cdk/drag-drop/drag-events.ts#L13)

It looks like the portion of the documentation you linked to was the description of the interface for the type the event emits.
