### ISSUE TITLE
Web worker support

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#1406]
#### Bug, feature request, or proposal:

Proposal.

Please keep us informed about any progress towards making this library compatible with web workers, for those of us who wish to run our app within a web worker as seen [in this sample app.](https://github.com/angular/angular/tree/master/modules/playground/src/web_workers/kitchen_sink)
#### What is the use-case or motivation for changing an existing behavior?

To allow `Material` to be used in a multitude of environments, in  high performance apps.

**Comment by jelbourn** [comment]
Current plan is to support it once the WebWorker support in Angular core improves. In particular, Material needs custom renderers (to deal with marshalling between UI and worker threads). 

However, it's not yet clear whether using web workers at all would actually be an improvement for the types on lower-level ui components that material offers; pretty much _all_ of the logic in the components deals with changing the rendered DOM in some way. Given that, it may end up being faster for material to continue running on the UI thread even when web-worker support is out of experimental.

**Comment by RoxKilly** [comment]
@jelbourn didn't think of it that way. Perhaps what's needed is for `Angular` to facilitate a way to run `MaterialModule` on the UI thread, but the rest of the app on the worker thread. Sounds complicated.

My own use case for web workers is a smoother UI during start up.  While the initial JS packages download and bootstrap, I have temporary content with animation:
```
<body>
  <ng-root-component>
       <!-- content & animation here to be removed by Angular after bootstrapping -->
  </ng-root-component>
</body>
```
Since the bootstrapping is occurring on the UI thread, the content and animation are frozen until `Angular` is ready, which defeats their purpose

**Comment by PascalTemel** [comment]
@RoxKilly I have implemented a similiar "loading screen" feature using pure CSS. Maybe this might help you: 
* https://github.com/PascalTemel/temel.me/blob/master/src/index.html
* https://github.com/PascalTemel/temel.me/blob/master/src/index.css

Live demo on http://temel.me/

**Comment by slmyers** [comment]
@PascalTemel that is beautiful, thanks for sharing.

**Comment by RoxKilly** [comment]
@PascalPrecht thanks for sharing. Mine is also Javascript-free. In fact it doesn't require any externally loaded asset (CSS stylesheet or icons)

The issue I was addressing was that the UI animation is not smooth because it is run by the same thread that bootstraps `Angular`. So framerate drops while `Angular` loads.

**Comment by jelbourn** [comment]
Closing this until a time when web-worker support in core is more solid.

**Comment by naveedahmed1** [comment]
Any update on this?

**Comment by patrickpereira** [comment]
+1

**Comment by naveedahmed1** [comment]
Is there any update on this?

**Comment by mhosman** [comment]
Any update???
