### ISSUE TITLE
bug: md-icon doesn't render correctly icon ligature with white-space, work with underscore

### ISSUE THREAD

**Issue by thibaultsavary** [angular/material2#1407]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`md-icon` should render icon ligature composed of two or more words

#### What is the current behavior?
`md-icon` doesn't render icon ligature composed of two or more words
or
`md-icon` render an icon using the ligature separately,
 for example:
`<md-icon>add alarm</md-icon>` 
should render the `add alarm` icon, and render the `add` and the `alarm` icon instead.

#### What are the steps to reproduce?
use any of the icons using a ligature composed of two or more word 

#### Which versions of Angular, Material, OS, browsers are affected?
angular-cli beta.16
angular material alpha.9-3

**Comment by ocarreterom** [comment]
Try `<md-icon>add_alarm</md-icon>` (with underscore).

**Comment by thibaultsavary** [comment]
It works.
I should have thought about that.
This can be close I think, the icon readme might benefit from this explanation.
Thanks @ocarreterom

**Comment by jelbourn** [comment]
This is unrelated to `md-icon`, it's just how the ligatures are defined.

**Comment by cmermingas** [comment]
@jelbourn - Just a quick note that the sample app linked from [the "getting started" guide](https://github.com/angular/material2/blob/master/GETTING_STARTED.md) uses space.

At the very end of [app.component.html](https://github.com/jelbourn/material2-app/blob/master/src/app/app.component.html):

![screen shot 2016-10-13 at 7 34 27 am](https://cloud.githubusercontent.com/assets/7100704/19347578/83b8cb3a-9117-11e6-9841-2657715003cf.png)
