### ISSUE TITLE
CDK overlay(tooltip, menu) show slow when many items in a page

### ISSUE THREAD

**Issue by qazq** [angular/material2#14079]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
CDK overlay show smooth no matter how many items in a page

#### What is the current behavior?
CDK overlay(tooltip, menu) show slow when many items in a page

#### What are the steps to reproduce?

StackBlitz starter: https://goo.gl/bGFsQD

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6 and 7

#### Is there anything else we should know?

This sample code is modified from Angular Material official table sample code.

Open the sample code, the default data size is 1000, it will draw a table contain 10000 rows. After the page rendered, please move the mouse to the Tooltip#1 then move to Tooltip#2 , Tooltip#3. The pop-up animation so slow when switching between each tooltip button. Click the Menu button to show the menu, the response is slow also.

Modify the code to reduce the data size to 1. The tooltip, menu will show fast.

Although the table content big, I think once the page is rendered, it shouldn't affect the performance of CDK overlay showing.

**Comment by djleonskennedy** [comment]
@qazq Hello, could you try https://material.angular.io/cdk/scrolling/overview with large data sets

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by andrewseguin** [comment]
Try changing your component to OnPush to reduce any unnecessary change detection. I tried your example with this and it seems to be as performant as you can expect when rendering a table with 10,000 rows.

https://angular-qtbnv4-lj6ad9.stackblitz.io/

Here's the editor version: https://stackblitz.com/edit/angular-qtbnv4-lj6ad9?file=app/table-basic-example.ts

Note: Rendering 10,000 rows will inevitably be tough on many user devices and you will see performance drops regardless of the framework supporting the page. Check out [developers.google.com](https://developers.google.com/web/tools/lighthouse/audits/dom-size) for more information on this.
