### ISSUE TITLE
Side nav bar is not in sync with the theme

### ISSUE THREAD

**Issue by castasint** [angular/material2#14088]
#### What is the expected behavior?
Side navigation bar should have the same theme as the toolbar

#### What is the current behavior?
The background is not set
![image](https://user-images.githubusercontent.com/16588875/48315052-90927400-e5f7-11e8-8c6c-ed1d15d32798.png)

#### What are the steps to reproduce?
1. Create a brand new angular project
2. Add angular Material to it(Selected indigo-pink theme)
3. Add the nav component using schematics(ng generate @angular/material:nav <component-name>)

#### What is the use-case or motivation for changing an existing behavior?
We are not trying to change the existing behavior. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

![image](https://user-images.githubusercontent.com/16588875/48315036-5cb74e80-e5f7-11e8-99f5-8fa9e12944bf.png)

#### Is there anything else we should know?
No, it is pretty straightforward. I tried checking in MS-Edge, Firefox, and Chrome. All the browsers have the same behavior

**Comment by castasint** [comment]
I'll be happy to assist with any information that is required to debug/fix the issue.

**Comment by DevVersion** [comment]
Thanks for your issue. Based on the PR that recently changed the schematic, this is by intention. See: https://github.com/angular/material2/pull/13282

Based on the information in the PR, the toolbar should align with the color of the content though.

**Comment by DevVersion** [comment]
@castasint I tried looking into it, but couldn't reproduce the case where the `.mat-toolbar` does not inherit the color from the background.

Can you inspect the toolbar in the sidenav and check if there is a `background: inherit` statement?
