### ISSUE TITLE
change css label on md-input

### ISSUE THREAD

**Issue by JuuuM** [angular/material2#1408]
Hi, 

Hello,

I would, in case of error on my form, change the label of my input as well as the text color and border-color below, much like with dividerColor, but without focus, I'd like that persistent.

So I made this code there for the label:
`md-input:not(.ng-invalid) label {
        background-color: red !important;
        color:red !important;
    }`
However, when I run the project, my css is modified in this way:
`md-input[_ngcontent-fcu-13]:not(.ng-invalid)   label[_ngcontent-fcu-13] {
        background-color: red !important;
        color:red !important;
    }
    `
And therefore, it does not work.
Do you have an idea ?
(Translated by google translation)

**Comment by jelbourn** [comment]
Your css is being encapsulated by Angular. See https://angular.io/docs/ts/latest/guide/component-styles.html

Also see #348
