### ISSUE TITLE
bug(progress-spinner): Failed to execute 'insertRule' on 'CSSStyleSheet'

### ISSUE THREAD

**Issue by Eusen** [angular/material2#14087]
#### Bug, feature request, or proposal:
DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '
 @keyframes mat-progress-spinner-stroke-rotate-32 {
    0%      { stroke-dashoffset: 65.65928646002666;  transform: rotate(0); }
    12.5%   { stroke-dashoffset: 13.82300767579509;    transform: rotate(0); }
    12.5001%  { stroke-dashoffset: 13.82300767579509;    transform: rotateX(180deg) rotate(72.5deg); }
    25%     { stroke-dashoffset: 65.65928646002666;  transform: rotateX(180deg) rotate(72.5deg); }

#### What is the expected behavior?
Business as usual !!!

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/14822175/48309924-725c5200-e5be-11e8-8396-dd9acf3343d3.png)
In Android 5.1 and below devices, the mat style is abnormal, and console has been reporting this error a lot.

#### What are the steps to reproduce?
You can browse https://material.angular.io/ on Android 5.1 device.
See if everything is normal ?!

#### What is the use-case or motivation for changing an existing behavior?
Unable to use normally !!!

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All latest !

**Comment by Eusen** [comment]
I wonder why I added the crosswalk plugin, but it didn't do anything??

**Comment by crisbeto** [comment]
Can you post the full stack trace?

**Comment by Eusen** [comment]
![image](https://user-images.githubusercontent.com/14822175/48312108-d560df80-e5e4-11e8-9ec0-9e72fed9d346.png)
![image](https://user-images.githubusercontent.com/14822175/48312109-da259380-e5e4-11e8-94ed-1541dc8a3f96.png)

A basic fact is that this component can not be used in version 5.1 and later.

**Comment by Eusen** [comment]
Are there any polyfill can be solved?

**Comment by crisbeto** [comment]
That is the kind of error that'll be thrown when the browser doesn't support `@keyframes`. In your case the dynamic keyframes that get inserted by Material would have to be prefixed with `-webkit-`. Adding the prefix won't be difficult, however we don't support any browsers that use the prefixed `keyframes.`

**Comment by Eusen** [comment]
> That is the kind of error that'll be thrown when the browser doesn't support `@keyframes`. In your case the dynamic keyframes that get inserted by Material would have to be prefixed with `-webkit-`. Adding the prefix won't be difficult, however we don't support any browsers that use the prefixed `keyframes.`

Does mean that  material does not support Android devices 5.1 and below?

**Comment by crisbeto** [comment]
It does, here's the note on browser support from our readme:

> Angular Material supports the most recent two versions of all major browsers: Chrome (including Android), Firefox, Safari (including iOS), and IE11 / Edge

That being said, [looking at caniuse](https://caniuse.com/#feat=css-animation), Android 5 should support unprefixed CSS animations. Since you mentioned that the error is only thrown when you change the diameter, does the spinner animate if you leave it in with the default diameter?

**Comment by Eusen** [comment]
No, they will remain motionless....

**Comment by Eusen** [comment]
I tested it on the x86 5.1 version of the virtual machine.

**Comment by crisbeto** [comment]
> No, they will remain motionless....
That means that the browser either doesn't support CSS animations altogether, or it requires a fix. Either way it's not a browser that we support.
