### ISSUE TITLE
snackbar - why is `ViewContainerRef` required

### ISSUE THREAD

**Issue by fxck** [angular/material2#1409]
Honestly why? Can't it use root component's `ViewContainerRef` by default? Sure, when you are making a demo and triggering the snackbar from a component upon a button click, getting hold of `ViewContainerRef` is easy. But you know, in real life, you are probably going to be triggering it from a service, or an [effect](https://github.com/ngrx/effects), and there's no [easy](http://stackoverflow.com/a/38109012/301596) [way](https://github.com/angular/angular/issues/9293) to get hold of any `ViewContainerRef` there, making snackbar extremely annoying to use.

**Comment by jelbourn** [comment]
> But you know, in real life, you are probably going to be triggering it from a service, or an effect, and there's no easy way to get hold of any ViewContainerRef there

We don't have a way of getting access to one either. See https://github.com/angular/angular/issues/9293

I'm trying to get support for this added to core before Material gets to beta.
