### ISSUE TITLE
[md-slide-toggle] Styling issues after upgrade to 2.0.0-alpha.9-3

### ISSUE THREAD

**Issue by vapits** [angular/material2#1411]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
![image](https://cloud.githubusercontent.com/assets/8594758/19040188/5c3aa06a-8983-11e6-9dbd-d665cd6ba9ee.png)

#### What is the current behavior?
![image](https://cloud.githubusercontent.com/assets/8594758/19040176/510e8c74-8983-11e6-8cbe-0c92a939b39f.png)
It's not styled (not even the default) and it appears a checkbox also.

#### What are the steps to reproduce?
Just upgrade to latest version from alpha.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular `2.0.0`
Angular Material `2.0.0-alpha.9-3`

**Comment by DevVersion** [comment]
This is not an issue with the slide toggle.

You need to include a theme stylesheet or build your own theme.

```
@angular/material/core/theming/prebuilt/XXX.css
```

**Comment by vapits** [comment]
@DevVersion is this on the docs somewhere?

**Comment by vapits** [comment]
Ok I just saw that, sorry and thx:
https://github.com/angular/material2/blob/master/docs/theming.md
