### ISSUE TITLE
mat-select with multiple

### ISSUE THREAD

**Issue by DuncanFaulkner** [angular/material2#14121]
#### Bug
Mat-select with multiple 

#### What is the expected behaviour?
to create a drop down list that allows multiple items to be selected

#### What is the current behaviour?
Error: Value must be an array in multiple-selection mode.

#### What are the steps to reproduce?
```
  <mat-form-field>
       <mat-select multiple placeholder="placeholder" formControlName="formGroup" required>
              <mat-option *ngFor="let c of items" [value]="c.value">{{ c.value }}</mat-option>
       </mat-select>
</mat-form-field>
```

#### What is the use-case or motivation for changing an existing behaviour?
this was working, seems to be broken in v7, have tried adding [(ngModel]) which does make it work but get a warning saying ngModel has been removed from v7 angular material mat-select

#### Which versions of Angular, Material, OS, Typescript, browsers are affected?
Ubuntu 18.4 
64 bit
vs code 1.29 insiders
chrome v:70
typescript 3.1.6
angular 7.0.2

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

Based on our [our docs site](https://stackblitz.com/angular/yagjggxxklj?file=app%2Fselect-multiple-example.ts) it appears to allow for multi-selects.
