### ISSUE TITLE
Release tooling: warn for non-standard tags

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#14125]
When doing a release, if the npm tag is not `latest` or `next`, we should show a "are you sure" warning prompt. 

This is mainly to guard against typos when tagging a release; 7.0.4 was accidentally tagged initially as `lastest`.

**Comment by DevVersion** [comment]
Sounds like a good idea. Regarding `7.0.4`, isn't it right to have the patch release in `latest`?

**Comment by devversion** [comment]
I'm closing this as with the upcoming publish release script, a prompt will be used to select the NPM dist tag. That way, there will be never a wrong dist tag selected.

Closing in favor of #13455
