### ISSUE TITLE
API documentation lacks links

### ISSUE THREAD

**Issue by pappasa** [angular/material2#14122]
#### Bug, feature request, or proposal: feature request

In the API documentation I would like to have a link to the base class. A link to the base class would save a lot of time searching for the base class.

**Comment by josephperrott** [comment]
@DevVersion is this something we could do with our currently set up?  If I remember correctly, you were the one who did our dgeni setup.

**Comment by DevVersion** [comment]
@josephperrott Yeah, that would be part of Dgeni. It's just a bit difficult to determine the link to another class if we generate the docs content without knowing under which URLs/routes they end up.

I will have a look at this.

**Comment by DevVersion** [comment]
Done. This should be in the next release.
