### ISSUE TITLE
[MatSidenavContainer] content margin updates stop working after sidenav is toggled

### ISSUE THREAD

**Issue by rafehi** [angular/material2#14157]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Updating `matSidenavContainer._contentMargins` should correctly update the margin of the contents.

#### What is the current behavior?
It works correctly up until the sidenav is toggled.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-epidzc

The content margin is updated correctly initially. Pressing the button, which calls `sidenav.open()`, causes the content margin to update sporadically.

#### What is the use-case or motivation for changing an existing behavior?
Our app is using a sidenav which can be toggled to a collapsed state, showing only icons. Toggling between full and collapsed state occurs over 300ms. 
Due to the animation, we need to manually update the content margin to ensure the content animates correctly (using _updateContentMargins). This works fine up until the sidenav is opened or closed (e.g. when switching between mobile and desktop resolutions).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All versions of Angular Material tested (both 6 and 7), however it behaves slightly differently between versions. In version 6, the content updates but lags behind the sidenav animation. In version 7, animation stops entirely.

#### Is there anything else we should know?
Setting autosize=true has no effect. I've also tried the following with no success:
```
 this.sidenavContainer._ngZone.onMicrotaskEmpty.subscribe(() => {
    this.sidenavContainer._contentMargins = { left: i * 2 % 300, right: 0 };
     this.sidenavContainer._changeDetectorRef.markForCheck();
});
```

**Comment by josephperrott** [comment]
Closing as `_contentMargins` is an internal property of the sidenav and should not be expected to be responded to by user updates.
