### ISSUE TITLE
[cdk-virtual-scroll] sometimes jumps unexpectedly

### ISSUE THREAD

**Issue by bob-lee** [angular/material2#14167]
#### Bug, feature request, or proposal:
Bug(?)

#### What is the expected behavior?
When showing a list of variable height items, viewport scrolls smoothly while scrolling up and down.

#### What is the current behavior?
Sometimes it jumps unexpectedly, so make it hard to view a certain item as a whole.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-7-virtual-scroll-jumping
Toggle between `ngFor` and `virtualFor` and try scrolling down, in `virtualFor`, it jumps a bit around the 3rd image.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: `7.0.1`
Material: `7.0.4`
OS: `windows`
Browsers: Chrome/FF/Brave

#### Is there anything else we should know?
Seems like it jumps when a set of rendered items change.

**Comment by bob-lee** [comment]
Didn't know about `autosize` strategy currently available in `@angular/cdk-experimental`, stackblitz demo updated to use it and seems to work, closing the issue.

**Comment by Joaovtrc** [comment]
There's any other way to 'fix' this without using the autosize on cdk-

> Didn't know about `autosize` strategy currently available in `@angular/cdk-experimental`, stackblitz demo updated to use it and seems to work, closing the issue.

There's any way of fixing this 'jump' issue without using the `@angular/cdk-experimental` ?

**Comment by TimeTravelersHackedMe** [comment]
This issue is still present on Android Chrome (Latest) Samsung S9+.

Is there any way to fix this?
