### ISSUE TITLE
Email validation failure

### ISSUE THREAD

**Issue by AndrewNikolin** [angular/material2#14160]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Email validation fails

#### What is the current behavior?
Email validation succeeds

#### What are the steps to reproduce?
1. Input an email in format `user@domaincom` without dot between `domain` and `com`
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/angular/eaaxpopenenr?file=app%2Finput-error-state-matcher-example.ts<br/>

#### What is the use-case or motivation for changing an existing behavior?
Fix email validation

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.0.4

**Comment by AndrewNikolin** [comment]
Isn't it way too strange for internet services operating in the WWW? My first assumption when I saw this was that this isn't the clear way and allows users to make mistakes.
My fault is that I didn't check RFC before submitting, now I see that this domain actually is valid from RFC perspective

**Comment by jelbourn** [comment]
Angular Material does not include any validators itself. You may be looking for `@angular/forms`, which lives on the main [angular/angular](https://github.com/angular/angular/) repo.
