### ISSUE TITLE
Downgrade non-default builders error to warning

### ISSUE THREAD

**Issue by FrozenPandaz** [angular/material2#14176]
#### Bug, feature request, or proposal:

Feature request for schematics

#### What is the expected behavior?

Not having the default builders and using the schematics should throw a warning.

Ideally, there would also be an option to silence it.

#### What is the current behavior?

Having non-default builders throws an error

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

```sh
npx @nrwl/schematics my-proj --no-interactive
cd my-proj
ng g app app1 --unit-test-runner jest --no-interactive
ng add @angular/material
```

#### What is the use-case or motivation for changing an existing behavior?

Users should be able to use their own builders at their own risk.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Whichever versions material enforce the builders (6+?)

#### Is there anything else we should know?

Original Issue:
https://github.com/nrwl/nx/issues/868

**Comment by DevVersion** [comment]
So, if someone uses non-default CLI builders, you expect the schematic to still run but just with a warning?

I'm wondering how that would work if someone runs `ng add @angular/material` and we want to add a theme style to the `build` builder. How would that work? just skipping that step?

**Comment by FrozenPandaz** [comment]
Yes. That's a good question. Skipping it seems appropriate. I wonder if there's a way to see if a builder accepts some option by reading the schema. But skipping with a link to the docs in the message is a good approach. Another issue would be reading from the config as well. 

I guess a good example of this would be someone with a custom webpack build using the webpack builder. 

If you don't feel comfortable with downgrading to a warning for build because it's so integral to the schematic, I understand. I imagine other targets like test are not as integral.

**Comment by DevVersion** [comment]
I see, reading the `config` for a builder sounds very reasonable, but I'm afraid that this is out-of-scope for our Material schematics.

Maybe we can work on some public API (maybe there already is one, not too sure yet), and then we can consider using that API in order to check if there is a `styles` option available.

**Comment by DevVersion** [comment]
Downgrading to a warning feels a bit odd because the styles are a major part of setting up Angular Material, and leaving that setup step is basically an incomplete `ng add` run.

**Comment by FrozenPandaz** [comment]
I'm fine with that approach.

Recap/ Requirements:
* Erroring on `build` for `ng-add` not matching the default builder because the schematic cannot deliver it's purpose without it.
  * For other schematics, if nothing is being altered in the `angular.json`, it may be nice if it is not an error.
* Warning on `test`, `lint`, `e2e` not matching the default builder because the schematic can deliver it's purpose but it is not guaranteed to work and there is some risk.

> For transparency, Nx does not alter the default `build` builder so checking of `build` doesn't affect Nx users at the moment.

Let me know if this makes sense to you.

Thank you!

**Comment by DevVersion** [comment]
@FrozenPandaz Sounds reasonable. Here is the PR: #14203
