### ISSUE TITLE
opening md-menu from an element that is fixed 

### ISSUE THREAD

**Issue by fxck** [angular/material2#1417]
When you do that, and scroll down or up menu is not scrolling along.

![](https://media.giphy.com/media/l0HlVyagyH0d9s0Tu/giphy.gif)

**Comment by jelbourn** [comment]
This is one of the main features of overlay that hasn't been implemented yet (repositioning when scrolling occurs in an `overflow: auto` child of the body).

**Comment by jelbourn** [comment]
Tracking this via #1430 now

**Comment by dfarago** [comment]
I would like to see md-menu positioned relative to the triggering (button) element. Also, with better control over offset distance from the triggering element.
