### ISSUE TITLE
Drag and Drop performance issue

### ISSUE THREAD

**Issue by pandamorphism** [angular/material2#14175]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
poor performance while start/stop dragging

#### What is the current behavior?
when page contains a lot of elements, drag start and drag stop events cause style recalculation on whole body
https://github.com/angular/material2/blob/master/src/cdk/drag-drop/drag-drop-registry.ts#L128

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
it is not possible to use cdk drag-n-drop on 'big' pages 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular-devkit/architect         0.6.5
@angular-devkit/build-angular     0.6.5
@angular-devkit/build-optimizer   0.6.5
@angular-devkit/core              0.6.5
@angular-devkit/schematics        7.0.2
@angular/cdk                      7.0.1
@angular/cli                      7.0.2
@angular/material                 7.0.1
@ngtools/webpack                  6.0.5
@schematics/angular               7.0.2
@schematics/update                0.10.2
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.8.3

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/1943206/48636579-fefa7c00-e9d3-11e8-8a3b-249e92035952.png)

**Comment by aGoncharuks** [comment]
Hi @crisbeto 

I believe this was fixed by: https://github.com/angular/material2/pull/14189

**Comment by crisbeto** [comment]
Thank you for the heads-up, looks like I forgot to reference to issue in my PR.
