### ISSUE TITLE
mdInput of type date does not show date picker in safari

### ISSUE THREAD

**Issue by Borntofly** [angular/material2#1418]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
drop-down with date picker like in chrome

#### What is the current behavior?
no drop-down shown

#### What are the steps to reproduce?
<md-input placeholder="Date" type="date" ></md-input>

#### What is the use-case or motivation for changing an existing behavior?
Same functionality in all browsers

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-alpha.9

**Comment by vinagreti** [comment]
Until now, MD does not have a datepiker. That one you see in chrome is the default HTML5 one. Are you sure that Safari has support for HTML5 date input?

**Comment by Borntofly** [comment]
You are right, Safari do not support it. 
Could you suggest any solution, which datepicker to use until angular material 2 datepicker is available?

**Comment by vinagreti** [comment]
You can try this https://github.com/Promact/material2

**Comment by Borntofly** [comment]
Thank you!
