### ISSUE TITLE
bug(chips-input) NO error state !

### ISSUE THREAD

**Issue by Eusen** [angular/material2#14195]
#### Bug, feature request, or proposal:
Bug
``` html
<form [formGroup]='group'>
  <mat-form-field class="example-chip-list">
    <mat-chip-list #chipList>
      <mat-chip *ngFor="let fruit of fruits" [selectable]="selectable"
              [removable]="removable" (removed)="remove(fruit)">
        {{fruit.name}}
        <mat-icon matChipRemove *ngIf="removable">cancel</mat-icon>
      </mat-chip>
      <!-- add formContorlName 'newFruit'  -->
      <input placeholder="New fruit..."
            formContorlName='newFruit'
            [matChipInputFor]="chipList"
            [matChipInputSeparatorKeyCodes]="separatorKeysCodes"
            [matChipInputAddOnBlur]="addOnBlur"
            (matChipInputTokenEnd)="add($event)">
    </mat-chip-list>
      <!-- add mat-error  -->
    <mat-error *ngIf="group.controls.newFruit.hasError('required')">required!</mat-error>
  </mat-form-field>
</form>
```

#### What is the expected behavior?
In this case, it can display error!

#### What is the current behavior?
If input is empty, no error will be displayed.

#### What are the steps to reproduce?
https://stackblitz.com/angular/pxxkxklrgaqg?file=app%2Fchips-input-example.html
You can try it on your example..

#### What is the use-case or motivation for changing an existing behavior?
Displaying error prompts when errors occur

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All latest

#### Is there anything else we should know?
No.

**Comment by Tonksi** [comment]
I am seeing the same issue

**Comment by Tonksi** [comment]
User error on my side, my reactive form had the field defined as:
`fieldName: new FormArray([])`

I switched to:
fieldName: new FormControl([])

**Comment by josephperrott** [comment]
Closing as the form control should actually go onto the `MatChipList` since the list is what shows all of the control values.

You can see a [fork of the stackblitz here](https://stackblitz.com/edit/angular-nuifjo?file=app/chips-input-example.html) in which if all of the chips are removed will show an error for required.

**Comment by alexmacavei** [comment]
@josephperrott Your stackblitz does not work after you delete the fruit the first time. You need to retouch the input. There seems to be a validation issue when the chip input initializes. I'm currently having this issue on a real-life app.
