### ISSUE TITLE
Problem with mat-select with multiple selections

### ISSUE THREAD

**Issue by alekseyLymarev** [angular/material2#14209]
#### Bug, feature request, or proposal:
Hello, when I try to insert an element select mat into the code and try to select an option when I click on an outsideside, the optimon elements are not hidden

#### What is the expected behavior?
mat-options must hide

#### What is the current behavior?
mat-options not hide

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
version 7.0.4 windows 10

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by alekseyLymarev** [comment]
Problem solved. The following code was found in project styles:

`* {
pointer-events: auto;
}`

**Comment by alekseyLymarev** [comment]
Thank you for trying to help.
