### ISSUE TITLE
When filter applied on last page, MatTable doesn't display any rows. But it displays correctly when filter applied on first page.

### ISSUE THREAD

**Issue by kamalSaiDd** [angular/material2#14206]
#### Bug, feature request, or proposal:
When filter applied on last page, MatTable doesn't display any rows. But it displays correctly when filter applied on first page.

#### What is the expected behavior?
When filter applied on last page,MatTable should display rows which are available.

#### What is the current behavior?
When filter applied on last page, Table doesn't display any rows.

#### What are the steps to reproduce?
StackBlitz: 
https://stackblitz.com/edit/angular-material2-issue-oyejx1

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular6.4.1, TypeScript - ~3.1.1.

#### Is there anything else we should know?

Please find screenshot for referrence:

![image](https://user-images.githubusercontent.com/44686078/48741188-2b4e0c80-ec0f-11e8-8855-711cb719a93e.png)

**Comment by kamalSaiDd** [comment]
Hi..

Any update on this issue ?

**Comment by andrewseguin** [comment]
The issue you are seeing is that the paginator does not automatically go to the first page of results when you filter. To fix this, add `this.paginator.firstPage();` to your `applyFilter` function.

https://stackblitz.com/edit/angular-material2-issue-qhhaav?file=app/app.component.ts

**Comment by kamalSaiDd** [comment]
> The issue you are seeing is that the paginator does not automatically go to the first page of results when you filter. To fix this, add `this.paginator.firstPage();` to your `applyFilter` function.
> 
> https://stackblitz.com/edit/angular-material2-issue-qhhaav?file=app/app.component.ts

Awesome. Thank you much.
