### ISSUE TITLE
MatButton Wrap or Break text

### ISSUE THREAD

**Issue by JDillon522** [angular/material2#14201]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When a button's content overflows its width it should wrap or break text. 

#### What is the current behavior?
The text flows outside of the button container

#### What are the steps to reproduce?
[Stackblitz Demo](https://stackblitz.com/edit/angular-material2-issue-mat-button-wrap-and-break-text)

#### What is the use-case or motivation for changing an existing behavior?
In my particular case I have a button with a filename as the text. Clicking the button downloads the file. Sometimes the filename can be long and I need to wrap the text but I cannot.

**Comment by thomaspink** [comment]
The material spec states you should not wrap/break text in buttons:

> Don’t wrap text. For maximum legibility, a text label should remain on a single line.
https://material.io/design/components/buttons.html#anatomy

So in my opinion the implementation is correct.

**Comment by josephperrott** [comment]
Closing as this is intended based on the spec since buttons are supposed to be single line.
