### ISSUE TITLE
Sidenav blocking toolbar shadow - CSS

### ISSUE THREAD

**Issue by AmirTugi** [angular/material2#1422]
I am using the toolbar above the sidenav + sideav layout.
Recently I have noticed that the toolbar shadow does not show up.
I thought I needed to configure it by myself, but after a while I figured that it is the sidenav layout who is blocking me from seeing the shadow.

See this [plunker](http://plnkr.co/edit/ZWaRcSRuuQW4Y33eR4YU?p=preview)

Tried to understand by myself what is going on over there, and why I can't stop this peculiar scenario, but to no avail.

What I want, obviously, is that the shadow of the md-toolbar to be displayed :)

**Comment by chouclee** [comment]
I'd rather say this is a css problem than a bug. The ```md-sidenav-layout``` has a default background-color which is not transparent.
You can override it using inline style (or css, whatever) to make the layout background transparent. 
```
<md-sidenav-layout style='width: 50%; background-color: rgba(255,255,255,0)'>
```

Or you can make the tool-bar's layer in top of sidenav-layout
```<md-toolbar color="primary" style="box-shadow: 0 5px 5px #999;z-index: 1;position: relative;">```

**Comment by AmirTugi** [comment]
Oh, that `position: relative` solved it.
But how? Why?

**Comment by chouclee** [comment]
@AmirTugi Did you mean why ```position: relative``` is needed to make it ```z-index: 1``` work?

**Comment by mmalerba** [comment]
closing since this was just a CSS issue
