### ISSUE TITLE
Open datepicker on focus

### ISSUE THREAD

**Issue by binu101** [angular/material2#14239]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Option to open de datepicker when focussing the input, keeping the focus in input. The same behaviour as clicking the suffix icon which both opens the calendar and focusses the input field. I want to be able to tab through the form without needing to click to open the calendar.

#### What is the current behavior?
I've seen many examples ranging from simply adding a (focus)="picker.open()" to complex click event listeners, but none seem to replicate the suffix click behaviour,

#### What is the use-case or motivation for changing an existing behavior?
I want to be able to tab through the form without needing to click to open the calendar. The need for a click is disrupting a user's flow tabbing through form inputs.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Currently using V6 of both Angular and Angular Material

**Comment by josephperrott** [comment]
Closing, as you mentioned you should be able to call the `open` method on the datepick on `focus` of the input.  Clicking the suffix button opens the calendar, but does not focus the input as you mentioned.  The focus is instead placed on the currently selected date.

**Comment by binu101** [comment]
In my case, I use an <fa-icon> FontAwesome component with the matSuffix directive (without the datepicker-toggle component), which does open and focus at the same time.

But if we take the suffix out of consideration (which I only used as an example of desired behaviour), adding a call to the open() method from the (focus)="" output blurs the input field. 

I want to keep focus on the input and also open the calendar. This however seems to be quite the challenge although IMO this should be a simple request..
