### ISSUE TITLE
Color Issue

### ISSUE THREAD

**Issue by AnasSharif** [angular/material2#1423]
when i install the using angular cli material it install successfully but color not working....

<button md-raised-button color="accent">Click me</button> 

color ="accent" not work not implement on button

**Comment by DevVersion** [comment]
Did you include a theming stylesheet? 

- https://github.com/angular/material2/blob/master/docs/theming.md

**Comment by jelbourn** [comment]
See the getting started and theming guides.

**Comment by sstorie** [comment]
I know this is closed, but FWIW I am using alpha.10 and am seeing a similar issue with a simple button. I've included the indigo-pink CSS theme, put a button in a component (with encapsulated styles if that matters), but I don't see the expected styling when using `color="primary"` on the button:

![image](https://cloud.githubusercontent.com/assets/3630784/20805099/0fc098d2-b7bb-11e6-832f-08ff114ad3fe.png)

...here's what I actually see in Chrome:

![image](https://cloud.githubusercontent.com/assets/3630784/20805020/cac4b650-b7ba-11e6-8260-1eacd629ad64.png)
