### ISSUE TITLE
Implementing amazing-time-picker

### ISSUE THREAD

**Issue by torabian** [angular/material2#14246]
#### Request

Let's import the amazing-time-picker as a default time picker for Angular Material

#### What is the expected behavior?
Consumers will be able to install time-picker within the angular material package.

#### What is the current behavior?
Consumers must install time picker from a thirdparty.

#### What is the use-case or motivation for changing an existing behavior?
It will be a standard use-case motivation.
 

#### Is there anything else we should know?
I am looking forward if the Angular Material team will be merging this code into their repository.

**Comment by josephperrott** [comment]
Closing as this repository is meant to house the Material components that are made available directly, we very intentionally try to have the absolute minimum dependencies for our downstream users.  If you would like to contribute a time picker to our repository let us know.  We can talk about what the process would entail and get started towards a [design doc](https://github.com/angular/material2/wiki/Design-doc-directory) for the component.
