### ISSUE TITLE
Global appearance setting for mat-form-field

### ISSUE THREAD

**Issue by digeomel** [angular/material2#14248]
#### Bug, feature request, or proposal:
Feature request: provide a way to define a global appearance attribute value for all mat-form-fields in an application.

#### What is the expected behavior?
To define the appearance attribute value for all mat-form-fields once in the application. Maybe something like MAT_LABEL_GLOBAL_OPTIONS.

#### What is the current behavior?
To my best understanding, there is no way to define this globally. The appearance attribute has to be defined in each instance of a mat-form-field, or at least once in every component template. Even by setting it in a service and injecting the service in every component is too much hassle.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.3, Angular Material 7.0.4, Windows 10, TypeScript 3.1.6, All browsers

**Comment by crisbeto** [comment]
You can use the `MAT_FORM_FIELD_DEFAULT_OPTIONS` injection token to set the appearance globally.
