### ISSUE TITLE
Change button corner radius from 3px to 2px.

### ISSUE THREAD

**Issue by jcomputer** [angular/material2#1424]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
As per the Material Design spec (https://material.google.com/components/buttons.html), buttons should have a 2px corner radius.

#### What is the current behavior?
Border radius is currently 3px.

**Comment by hacknaked** [comment]
That link...

**Comment by jelbourn** [comment]
Closed by #1441
