### ISSUE TITLE
Stackblitz demo of locale runtime switching using moment is broken

### ISSUE THREAD

**Issue by blackholegalaxy** [angular/material2#14243]
#### Bug, feature request, or proposal:

On [locale code page](https://material.angular.io/components/datepicker/overview#setting-the-locale-code) the inline example *Datepicker with different locale* works properly. We can see Japanese calendar is displayed then clicking on french changes the locale properly.

But [the stackblitz demo](https://stackblitz.com/angular/yryblljrbrk?file=app%2Fdatepicker-locale-example.ts) when we click on `Edit on Stackblitz` is broken and doesn't reflect this behavior.

#### What is the expected behavior?

The stackblitz demo provided as editable example by Angular Material website should work properly and in the same way as the inline demo.

#### What is the current behavior?
The stackblitz editable example doesn't work at all: calendar is never displayed in japanese (it's defaulted to en-US) and clicking on french doesn't changes the locale in the datepicker.

<img width="1673" alt="screen shot 2018-11-22 at 9 41 50 pm" src="https://user-images.githubusercontent.com/11064123/48926857-741bf480-ee9f-11e8-8148-7552e55e5bf8.png">

#### What are the steps to reproduce?
Just go on your own stackblitz example to see the provided example doesn't work: 

https://stackblitz.com/angular/yryblljrbrk?file=app%2Fdatepicker-locale-example.ts

#### What is the use-case or motivation for changing an existing behavior?
Stackblitz example are used as base especially when trying to expose bugs to your team. We should be able to rely on official example to serve as reliable and functional bases.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

7.1.0, 7.0.4, 6.4.7 ?

#### Is there anything else we should know?

We discovered this behavior when trying to create a reproduction for a bug we encounter in the date moment adapter. We cannot switch back to en-US using `this.adapger.setLocale('en-US')` or `this.adapter.setLocale('en)` as it produces an error:

![image 5](https://user-images.githubusercontent.com/11064123/48926755-c01a6980-ee9e-11e8-95db-b75c679efb94.png)

It may be related. If not, we'll open another issue when able to reproduce proper working behavior using official examples.

**Comment by josephperrott** [comment]
It looks like the issue you are seeing is unrelated as this example works as expected if `{provide: MAT_DATE_LOCALE, useValue: 'ja-JP'},` is moved to the `DemoMaterialModule` decorator in the `material-module.ts` file.

**Comment by blackholegalaxy** [comment]
ok so the example is simply broken on StackBlitz. Guess it will be fixed. I will open another issue for my other problem :)

**Comment by mmalerba** [comment]
I think this is the same issue with providers in stackblitz being tracked here: https://github.com/angular/material2/issues/9780
