### ISSUE TITLE
@angular/cdk/drag-drop not working in lazy-loaded Module.  

### ISSUE THREAD

**Issue by Sree-001** [angular/material2#14256]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by crisbeto** [comment]
Can you post any error that you might be getting?

**Comment by Sree-001** [comment]
Not getting any error

**Comment by crisbeto** [comment]
It's hard to tell what's going on without looking at code. Most likely you have to import the `DragDropModule` into your lazy-loaded module.
