### ISSUE TITLE
CDK: scrolling page while dragging item does not work

### ISSUE THREAD

**Issue by aidvb** [angular/material2#14273]
#### Bug, feature request, or proposal:
Bug / Feature request

#### What is the expected behaviour?
When dragging an item with cdkDrag attribute, user should be able to use mouse wheel to scroll down the page, or the page should scroll down automatically if the draggable list longer than current page's height.

#### What is the current behaviour?
Mouse scroll on page is not working when dragging an item.

#### What are the steps to reproduce?
A) Goto https://material.angular.io/cdk/drag-drop/overview
Click on Draggable square in Basic Drag&Drop (Getting started section). While holding left mouse button pressed, try to scroll the page down with mouse wheel or touchpad.

B) Click on Draggable list item in Drag&Drop sorting (Reordering lists section). Make sure that half of the list is not visible in viewport. Click on any item and start dragging it to the bottom of the list. Again, mouse wheel scroll is not working, neither the page gets scrolled down automatically when you try to drag item down the list.

#### What is the use-case or motivation for changing an existing behaviour?
This is Accessibility related issue and should be working to get the best user experience.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.

#### Is there anything else we should know?
If you check React's draggable component here (https://react-beautiful-dnd.netlify.com/?selectedKind=single%20vertical%20list&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) you should get a better understanding of the expected Accessibility feature. Drag the top item to the bottom of the list and see how the page scrolls down. Mouse wheel scroll is also working fine.

**Comment by crisbeto** [comment]
Currently scrolling is disabled intentionally. It'll be enabled once https://github.com/angular/material2/issues/13588 is resolved.

**Comment by Maks-Yaremenko** [comment]
any progress on this issue?

**Comment by sureshdotariya** [comment]
Angular 8 CDK release adding this support? drag and drop inside scroll container

**Comment by vidhya-longani** [comment]
Any update here?

**Comment by vincentdsf** [comment]
This is real show stopper for us as our webapp shows a lot of data and with Dragular2 its no problem to scroll also while dragging. We had to cancel our (almost complete) migration to Material Drag because of this Bug, please fix it soon if possible :/

**Comment by sandeepsuvit** [comment]
Hi i have tried using this library for my projects [ngx-smooth-dnd](https://kutlugsahin.github.io/ngx-smooth-dnd/). Work really well with dnd support and drag on scroll as-well. I have made a sample demo app here ```https://github.com/sandeepsuvit/angular-dnd-survey-creator```. Here is a working [demo](https://angular-dnd-survey-creator.netlify.com/) of the app that i created using ```ngx-smooth-dnd```. Hope this helps someone until this issue is fixed :)

**Comment by kflo** [comment]
BUMP

**Comment by kflo** [comment]
This bug really is a deal breaker in the Angular Material CDK...

**Comment by woteska** [comment]
Any update on this? https://github.com/angular/components/issues/13588

**Comment by filipemendes1994** [comment]
Any news?

**Comment by SurjithP** [comment]
Any update ?

**Comment by subotin94** [comment]
Any update?

**Comment by smiles2424** [comment]
If I'm reading the chain properly:

In issue #13588 it references PR #16382 that was closed on July 9th. So this should be in 8.1.0 and above.

Hoping this helps.

**Comment by gnusiva** [comment]
any updates?

**Comment by BlindDespair** [comment]
any updates?

**Comment by hamzadiaz** [comment]
Still having same issue, is there a way to enable scrolling while dragging??

**Comment by shlomishe** [comment]
any updates?

**Comment by Enngage** [comment]
I also wonder what changed as dragging while scrolling worked after the update, but now it started happening again - scrolling while dragging somehow offsets the row position so it's not possible to drag item to correct position after scroll has be initiated. 

This is not happening on the sample https://material.angular.io/cdk/drag-drop/overview, but I'm still wondering what could be the cause of this..

**Comment by liesahead** [comment]
So, if anyone still has issues with this I can share with solution I found and it's super strange it's not clearly documented.

So, let's say you have a list and you want to implement DnD with autoscroll for it:
```html
<div class="scrollable-content" cdkScrollable>
    <ul cdkDropList>
        <li cdkDrag *ngFor="let item of items"></li>
    </ul>
</div>
```

The important thing here is `cdkScrollable` for scrollable container. It can be far ancestor and not direct parent (in our case it's like that).

So, to enable autoscroll you need to import `CdkScrollableModule` and set `cdkScrollable` for scrollable container which should scroll on drag.

**Comment by augustinw** [comment]
> 
> 
> So, if anyone still has issues with this I can share with solution I found and it's super strange it's not clearly documented.
> 
> Let's say you have a list and you want to implement DnD with autoscroll for it:
> 
> ```
> <div class="scrollable-content" cdkScrollable>
>     <ul cdkDropList>
>         <li cdkDrag *ngFor="let item of items"></li>
>     </ul>
> </div>
> ```
> 
> The important thing here is `cdkScrollable` for scrollable container. It can be far ancestor and not direct parent (in our case it's like that).
> 
> To summarize, to enable autoscroll you need to import `CdkScrollableModule` and set `cdkScrollable` for scrollable container which should scroll on drag.

So for me the import was actually 
```import {ScrollingModule} from '@angular/cdk/scrolling';```
Here's the docu: https://material.angular.io/cdk/scrolling/api ( not mentioning DragDrop though)
