### ISSUE TITLE
Mat Sidenav - TypeError: Cannot read property 'runOutsideAngular' of undefined

### ISSUE THREAD

**Issue by knoefel** [angular/material2#14271]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
It is possible to use mat-sidenav component with target "es-6"

#### What is the current behavior?
It is not possible to use mat-sidenav component with target "es-6".

#### What are the steps to reproduce?
After importing and using mat-sidenav in template files the following error is shown:

![capture](https://user-images.githubusercontent.com/2396344/49009935-1a9f1880-f172-11e8-93f5-4331df1c67d2.PNG)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1; Angular Material 7.1; Typescript 3.1.6 

#### Is there anything else we should know?
Actually there are other similiar issues covering this. But all these older issues expected, that this error will be fixed with version 7.1. Setting the target to "es5" or using --aot flag for ng serve is not an option!!

**Comment by DevVersion** [comment]
Thanks for your issue! This is being tracked with angular/angular#27267 now.
