### ISSUE TITLE
Updating BottomSheet Instance Data

### ISSUE THREAD

**Issue by ErraticFox** [angular/material2#14276]
#### Bug, feature request, or proposal:
Bug(?)

#### What is the expected behavior?
To update data of BottomSheet instance

#### What is the current behavior?
Instance updates, but not visually though the data object of the instance changes fine.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-zh3ho6

#### What is the use-case or motivation for changing an existing behavior?
Updating BottomSheet data

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.10, 7.10, Win10, 3.1.6

**Comment by josephperrott** [comment]
Closing as this is working as expected.  The instance of the data object you are updating is not the instance of the object that is being used in your component.  You can see in this [fork of your stackblitz](https://stackblitz.com/edit/angular-material2-issue-8slsq8?file=app/app.component.ts) that updating the instance of the data object which was injected into the component works as expected.
