### ISSUE TITLE
Material Checkbox become smaller size - After update to version 7.x

### ISSUE THREAD

**Issue by Gil-Epshtain** [angular/material2#14277]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Material Checkbox should look the same between version 6.x and 7.x

#### What is the current behavior?
Checkbox on version 7.x is SMALLER than in 6.x

#### What are the steps to reproduce?
1. Open this link (Material v6): https://v6.material.angular.io/components/checkbox/overview
and notice the Checkbox
2. Open this link (Material v7): https://material.angular.io/components/checkbox/overview
and notice the Checkbox
3. Compare the size (width x height) of the Checkbox

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.x
TypeScript 3.x
Node 10.x
OS: window 10 64bit
Browser: Chrome

**Comment by Gil-Epshtain** [comment]
![6 4](https://user-images.githubusercontent.com/7883039/49031808-ab4a1880-f1b3-11e8-9a3e-d66940973f6c.png)
![7 1](https://user-images.githubusercontent.com/7883039/49031811-ae450900-f1b3-11e8-8b26-3f5460b96c65.png)

**Comment by crisbeto** [comment]
This is intentional in order to bring in line with the latest Material Design spec.

**Comment by Gil-Epshtain** [comment]
@crisbeto - My application UI brake after this change! What CSS should I apply to display the Checkbox as before? I've try to give the "mat-checkbox-frame" a width and hight of 20px - which make the border of the checkbox bigger, however the label and the V mark appear not centered. Any quick fix to make it appear back as it was?

**Comment by crisbeto** [comment]
You can try to revert the changes from https://github.com/angular/material2/pull/12493, however it would be up to you to maintain it since it's not something that we support.

**Comment by Gil-Epshtain** [comment]
@crisbeto - thank you
