### ISSUE TITLE
 The underline for current active `mat-tab` doesn't show up when set the parent's `display` property from 'none' to other at the first time

### ISSUE THREAD

**Issue by DashanWang1** [angular/material2#14279]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If parent element of `mat-tab-group` change `display: none` to other when the animation of underline is not finished, the underline should be applied to current active tab

#### What is the current behavior?

The underline also doesn't show up when set the parent's `display` property from 'none' to other.

The underline cannot be applied to the current active tab when parent element toggle css `display` property.

#### What are the steps to reproduce?
1. open the example below.
2. select a tab.
3. after did 2， click the `Toggle` button quickly.
StackBlitz starter: https://stackblitz.com/edit/angular-mat-stepper-in-mat-tab-group-asta26?file=app%2Fapp.component.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
                "@angular/animations": "^6.1.7",
		"@angular/cdk": "^7.1.0",
		"@angular/common": "^6.0.6",
		"@angular/compiler": "^6.0.6",
		"@angular/core": "^6.0.6",
		"@angular/material": "^6.4.7",

Chrome Version 70

**Comment by josephperrott** [comment]
The inkbar cannot be positioned until the tab header is visible on the page.  You can call for the realignment of the inkbar by calling `realignInkBar` on the `MatTabGroup` instance after you change the css `display` value.

**Comment by davidwillianx** [comment]
> The inkbar cannot be positioned until the tab header is visible on the page. You can call for the realignment of the inkbar by calling `realignInkBar` on the `MatTabGroup` instance after you change the css `display` value.

Thx! I my case works perfect

**Comment by Gericho91** [comment]
Use [hidden] attr instead of display none
