### ISSUE TITLE
Material pagination does not take the table size

### ISSUE THREAD

**Issue by rohanshenoy96** [angular/material2#14284]
#### Bug, feature request, or proposal:
If the table is kept as overflow(scroll feature is added) then the paginator does not take the same size as table. Have tried CSS to alter the size but it does not work. Request to fix this bug.

#### What is the expected behavior?
If the table size is increased then pagination should also be extended

#### What is the current behavior?
Table is getting bigger horizontally. But pagination size takes the screens size instead of tables.

#### What is the use-case or motivation for changing an existing behavior?
Developing an application for a company.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.0.3
Node: 8.11.3
OS: win32 x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cdk                      7.0.2
@angular/cli                      7.0.3
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.0.2
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.4
webpack                           4.19.1

**Comment by josephperrott** [comment]
Since the paginator is simply an element on the page next to the table, you will need to use css styling to change the sizing of the paginator as well.  Since the paginator is (typically though not required to be) placed next to the table in the DOM, its not possible for the paginator to know how to automatically adjust.
