### ISSUE TITLE
Easy and fast to implement feature for Tabs, fixes a bug / issue

### ISSUE THREAD

**Issue by nekkon** [angular/material2#1428]
#### Bug, feature request, or proposal:

Need a state where none of the tabs are selected (SelectedIndex). There is no such option atm. One easy way would be when SelectedIndex is equal to -1.
#### What is the expected behavior?

When SelectedIndex == -1 then none of the Tabs are selected/active.
#### What is the current behavior?

Uncaught TypeError:Cannot read property 'elementRef' of undefined
#### What is the use-case or motivation for changing an existing behavior?

There are cases when a Tab might not be selected.

**Comment by Ploppy3** [comment]
Out of curiosity, can you give me an example where you don't have any tab selected ?

**Comment by nekkon** [comment]
An example is when there is a footer along with a set of Tabs that you want to be shown at all occasions.  Each Tab ( on the top ) shows its own content. If a user clicks on an option in the footer (bottom) and you don't want one of the Tabs to be selected ( as it shows content non-related to that tab, or general like the example ), no Tab should be active. I agree that this is something rare, if not non-ordinary, but there should be an option if someone does not want to have an active Tab, to be able to set the Tabs in such state.
![screen2](https://cloud.githubusercontent.com/assets/8094269/19146570/b4e541da-8bbc-11e6-9c90-43c2df5a2e88.png)
![screen1](https://cloud.githubusercontent.com/assets/8094269/19146569/b4e1a93a-8bbc-11e6-82b6-7bf9b880b8c4.png)

**Comment by nekkon** [comment]
Also the example above follows fixed Tabs in Material Design Guidelines
[link](https://material.google.com/components/tabs.html#tabs-specs)

**Comment by andrewseguin** [comment]
It's not clear to me that this is in the material spec. Fixed tabs refer to tabs that stretch across the header with equal widths, but do not refer to a state where there is no active tab. 

In your example it appears you want to be using a nav bar rather than a tab group.
