### ISSUE TITLE
Event before CdkDragStart

### ISSUE THREAD

**Issue by adrigm** [angular/material2#14294]
it would be interesting to have a function that allows it to be executed right at the beginning of a drag event. Before CdkDragStart and before counting the items in cdkDropList.

I need to remove some items from the cdkDropList list when a cdkDrah event is triggered. Any way to do it?

I'm trying to simulate a multiple drag-drop

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
