### ISSUE TITLE
Feature Request: Tiered option for Menu Component

### ISSUE THREAD

**Issue by ajrauen** [angular/material2#1429]
#### Bug, feature request, or proposal:

Ability to create tiered menu with Menu component
#### What is the expected behavior?

When a user hovers over a specified element, a sub men is opened next to it. Similar to Chromes menu
#### What is the current behavior?

None exist
#### What is the use-case or motivation for changing an existing behavior?

I would like the ability to created a tiered menu instead of having to create multiple menus side by side. 
#### Which versions of Angular, Material, OS, browsers are affected?

2.0.0-alpha.9

**Comment by jelbourn** [comment]
This is planned for md-menu.

**Comment by ajrauen** [comment]
Excellent :)

**Comment by manndave** [comment]
Any ETA?
