### ISSUE TITLE
Radio button (mat-radio) Click effect not disappear until focus lost (Version 7.x regression)

### ISSUE THREAD

**Issue by Gil-Epshtain** [angular/material2#14290]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Radio button (mat-radio) click effect should disappear after the click event finished

#### What is the current behavior?
Radio button (mat-radio) click effect say around the radio button as long as the radio has focus.

#### What are the steps to reproduce?
1. Open Material site on v6.x: [Mat-Radio v6](https://v6.material.angular.io/components/radio/overview) - click the radio button, and watch the click effect.
2. Open Material site on v7.x: [Mat-Radio latest](https://material.angular.io/components/radio/overview) - click the radio button, and watch the click effect.
3. Compare both effects.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: v7.1
Angular: v7.0
NodeJS: v10
TypeScript: v3.x
Browser: Chrome
OS: Win10 64bit.

See pictures in first comment

**Comment by Gil-Epshtain** [comment]
![6](https://user-images.githubusercontent.com/7883039/49087221-169cf480-f25f-11e8-8698-d3f7a7193168.png)
![7](https://user-images.githubusercontent.com/7883039/49087222-18ff4e80-f25f-11e8-8704-ece59aed10eb.png)

**Comment by josephperrott** [comment]
Closing as this was an intentional change to match the updated Material Design spec.  The purpose of continuing to show the indicator is to show the currently focused state.

**Comment by Gil-Epshtain** [comment]
@josephperrott - How is this "intentional" why would any one want to keep the click effect after the click had finished. 
1. Where can I find a list of all "intentional" changes that where made between v6.x and v7.x?? (I already found that: checkbox, radio-button and button-toggle - all had appearance modification. Did any other component was changes???)
2. Is there a work-around to solve this issue, can I remove this click effect after the click was finished (Css/Js?) ?

**Comment by thw0rted** [comment]
The Material spec is available [here](https://material.io/design/components/selection-controls.html#radio-buttons).  It was completely overhauled some months ago -- I'm not aware of anywhere that they've documented all the changes between "versions" of the spec, but it's outside the scope of this project.
