### ISSUE TITLE
Datepicker: dateChange event returns null or undefined in Firefox

### ISSUE THREAD

**Issue by jephelijay** [angular/material2#14308]
I am having issues with the dateChange event in the datepicker for Firefox. We are currently using version 6.4.7, however, a brief test on the demos confirms that this issue is still happening on the latest version.

Here are the screenshots for this issue:

On Chrome
![image](https://user-images.githubusercontent.com/24837926/49137473-7d85e080-f327-11e8-92cd-bb376cce1fa5.png)

On Firefox
![image](https://user-images.githubusercontent.com/24837926/49137523-a73f0780-f327-11e8-9e11-56a599d141a6.png)

Addendum: Do note that the format that we use is MM.DD.YYYY.

EDIT: Quickly checked and it seems that dot and dash delimiters are broken in Firefox. Slashes are good though.

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
