### ISSUE TITLE
angular-material-typeography Incompatible units 

### ISSUE THREAD

**Issue by davepotts** [angular/material2#14312]
#### Bug, feature request, or proposal:

When using a custom mat-typography-config and applying it to  angular-material-typography or mat core the application fails to compile with the below error

#### What is the expected behavior?
Application should compile.

#### What is the current behavior?

ng serve throws an error

```
ERROR in ./src/screach-themes.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/screach-themes.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
                           ^
      Incompatible units: 'px' and 'em'.
      in C:\Users\davep\Development\MyScreach\node_modules\@angular\material\_theming.scss (line 4651, column 29)
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
                           ^
      Incompatible units: 'px' and 'em'.
      in C:\Users\davep\Development\MyScreach\node_modules\@angular\material\_theming.scss (line 4651, column 29)
i ｢wdm｣: Failed to compile.
```

#### What are the steps to reproduce?
see stackblitz for reproduction of issue
https://angular-material2-issue-uerym6.stackblitz.io

**Comment by josephperrott** [comment]
Closing as this is a limitation by the design of the input typography. As noted [here](https://github.com/angular/material2/blob/master/src/lib/core/typography/_typography.scss#L36), the "line-height of `$input` must be a unit-less fraction of the font-size".  The computations [here](https://github.com/angular/material2/blob/master/src/lib/input/_input-theme.scss#L60) require a unitless value.

I made a [fork of your stackblitz](https://stackblitz.com/edit/angular-material2-issue-rd37te?file=theme.scss) setting the line-height of the `$input` as a unit-less value.

**Comment by davepotts** [comment]
Thanks @josephperrott All clear. 

Its worth adding this comment to the Material documentation or guides
