### ISSUE TITLE
plunker template is missing `.forRoot()`

### ISSUE THREAD

**Issue by fxck** [angular/material2#1431]
Which is causing problems, for example `[md-menu-trigger-for]="menu"` is throwing 

> Unhandled Promise rejection: Error in app.component.html:1:0 caused by: No provider for a!

- no `.forRoot()`, not working http://plnkr.co/edit/5WGdX9RR6HMYvWKZ1xRb?p=preview
- with `forRoot()`, working http://plnkr.co/edit/feKPYaNbVoAwWo0mxFZk?p=preview

**Comment by DevVersion** [comment]
I just updated the Plunker Bundle and Template to the last commit (pending #1222)

> It also uses the `.forRoot` now by default.

**Comment by jelbourn** [comment]
Thanks!
