### ISSUE TITLE
Datepicker: dateChange event returns undefined or null value when entering a date with a format of MM.DD.YYYY on Firefox browsers.

### ISSUE THREAD

**Issue by jephelijay** [angular/material2#14319]
#### Bug, feature request, or proposal:
This is a bug encountered on Firefox.

#### What is the expected behavior?
When you type in a date in the format of MM.DD.YYYY, the dateChange event should an object of MatDatepickerInputEvent<D>, with the value property containing the parsed date. Expected that this is working on all web browsers.

#### What is the current behavior?
In Firefox, when you type in a date in the format of MM.DD.YYYY, the dateChange event returns an Object object, of which the value property is null or undefined.

#### What are the steps to reproduce?
This can be simply reproduced by going to the angular material 2 demo for the datepicker input and change events:

Open the site on both Chrome and Firefox browsers:

In the input box as follows, enter 02.05.2018.

In Chrome, you can view the results, and the value from the event object is successfully parsed and returned:

![image](https://user-images.githubusercontent.com/24837926/49194028-71982e00-f3bc-11e8-8fe7-31e2fdd0ab7f.png)

While in Firefox, the input is not parsed, and the value from the event object is undefined:

![image](https://user-images.githubusercontent.com/24837926/49194050-8b397580-f3bc-11e8-99aa-77f98428d056.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
In my project, the version is 6.4.7. On the demo site, I would assume that it uses the latest version of Angular Material. 

Tested and it affects the latest Firefox browsers (v63.0.3).

#### Is there anything else we should know?

MM-DD-YYYY returns an undefined value in Firefox. MM/DD/YYYY works fine though.

**Comment by manklu** [comment]
Have a look at the documentation https://material.angular.io/components/datepicker/overview

Especially the chapter "Choosing a date implementation and date format settings"

**Comment by jephelijay** [comment]
Thanks @manklu. It seems that native javascript Date has different browser implementations, and while Chrome might accept ambiguous date formats, Firefox and Safari does not. Modified the custom adapter I used to extend from MomentDateAdapter rather than NativeDateAdapter and the problem went away.

I think someone can close this issue now.
