### ISSUE TITLE
CDK overlay: Backdrop can't be created, can't be clicked

### ISSUE THREAD

**Issue by sangupta007** [angular/material2#14316]
#### Bug

I have a very simple cdk overlay. But I want its backdrop to be seen (with grey color or something) and when the backdrop is clicked, it should close the overlay.

Problem:

1. When I apply `[hasBackdrop]="true"` as in Line A (_see my code below_), I get `Can't bind to 'hasBackdrop' since it isn't a known property of 'ng-template'.`
2. `(backdropClick)="showAlert()" `simply doesn't work.

**Code:**
```
   <button (click)="showOverlay = !showOverlay"
      #overlayOrigin="cdkOverlayOrigin"
      cdkOverlayOrigin>
      click me!!
    </button>

    <ng-template
      cdkConnectedOverlay
      [hasBackdrop]="false" //<=== Line A
      (backdropClick)="showAlert()"
      [cdkConnectedOverlayOrigin]="overlayOrigin"
      [cdkConnectedOverlayOpen]="showOverlay">
      <p class="dialog-container">hello</p>
    </ng-template>
```

#### What is the expected behavior?
Backdrop should be created. And overlay should go away when backdrop is clicked.

#### What is the current behavior?
Backdrop is not being created.

#### What are the steps to reproduce?
https://stackblitz.com/edit/github-e6fr4y?file=src/app/overlay/overlay.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.0.9
Material: 6.3.3
OS: Windows 10
Browser: Chrome. Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by crisbeto** [comment]
The input for `hasBackdrop` is called `cdkConnectedOverlayHasBackdrop`.

**Comment by sangupta007** [comment]
@crisbeto Thanks for your reply. I tried that already and it's not working. Can you edit in my stackblitz demo and check?

**Comment by oleynichenko** [comment]
same problem also I am using `cdkConnectedOverlayHasBackdrop`
