### ISSUE TITLE
label of mat-select with mat-form-field appearance="outline" not centered

### ISSUE THREAD

**Issue by ThomasPe** [angular/material2#14322]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Label of mat-select should be vertically centered.

#### What is the current behavior?
The label is too far down compared to the arrow icon.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-bgxnpd

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1.1, Material 7.1.0

**Comment by mmalerba** [comment]
For all of the form field variants other than legacy, placeholder and label are not the same thing. You probably want to use label instead of placeholder: https://stackblitz.com/edit/angular-bgxnpd-c2rksf?file=app/select-overview-example.html

**Comment by ThomasPe** [comment]
Actually I specifically don't want to use label as I don't want it to be seen when I select a value.
