### ISSUE TITLE
MatSelectTrigger not showing values

### ISSUE THREAD

**Issue by mackelito** [angular/material2#14329]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Selected values should be shown

#### What is the current behavior?
First mat-select-placeholder shows
Once a MatOption has been selected it does not show in the MatSelectTrigger

![kapture 2018-11-29 at 23 01 59](https://user-images.githubusercontent.com/598463/49255033-29642480-f42b-11e8-90c5-6e6074faa303.gif)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-7hv9ue?file=app/select-multiple-example.html

**Comment by crisbeto** [comment]
That's because you've put the select trigger inside one of the option groups. Here's a working example: https://stackblitz.com/edit/angular-7hv9ue-7mones.

**Comment by mackelito** [comment]
@crisbeto eeeehrm... well.. yes.. you are correct 😂
You have now witnessed what 4h of sleep can do! 😂

thx!
