### ISSUE TITLE
virtual scrolling can't support router config:ExtraOptions->scrollPositionRestoration='enabled' ?

### ISSUE THREAD

**Issue by clkz** [angular/material2#14320]
### Steps：

1. use  '@angular/router' and setting config:
` 
imports: [RouterModule.forRoot(routes, { scrollPositionRestoration: 'enabled' })] 
`
2. use '@angular/cdk/scrolling' in module  && config to `List Route` && code in list component:
```
<cdk-virtual-scroll-viewport itemSize="50" class="example-viewport">
  <div *cdkVirtualFor="let item of items$ | async" class="example-item" (click)="toDetail">{{item}}</div>
</cdk-virtual-scroll-viewport>
```
3. pull the scroll bar  or touch up ` to any position`

4. click the item: ` to Detail Route`

5. return  (broswer back button or router back) to List Route, the position always stay at 0,0 

scrollPositionRestoration is not work

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
