### ISSUE TITLE
md-input doesn't expose the change event

### ISSUE THREAD

**Issue by fxck** [angular/material2#1433]
http://plnkr.co/edit/aXL7VaqNAbenCII3OygL?p=preview / https://github.com/angular/material2/blob/master/src/lib/input/input.html#L36

which is something https://ng-bootstrap.github.io/#/components/datepicker apparently needs to be able to use it on custom elements

**Comment by jmcgoldrick** [comment]
Hey @fxck, I have no problem using the `(change)` output on an `<md-input>`, see an updated version of your plunk here: http://plnkr.co/edit/63JU6qB1wRNGSRkjjFcx?p=preview
