### ISSUE TITLE
mat-radio-button animation - outer circle remains at the end of the animation

### ISSUE THREAD

**Issue by kodwi** [angular/material2#14349]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

The circle should disappear itself at the end of the animation.

#### What is the current behavior?

The animation of mat-radio-button doesn't complete correctly  - the outer circle remains at the end of the animation and disappears only if I click somewhere.

#### What are the steps to reproduce?

The bug reproduces in all browsers.
Just check it out on the official guide example switching the radion buttons.
[Link](https://material.angular.io/components/radio/examples)

#### What is the use-case or motivation for changing an existing behavior?

Unexpected behavior.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular Material 7.1.0

**Comment by josephperrott** [comment]
This is working as intended as it is the focus indicator for the radio button.

**Comment by jcanaan88** [comment]
Is there a way to prevent it from blocking click events on other elements? After making a selection on a radio button, the focus stays on the option, and I then have to click off of the radio button in order to interact with other elements.
