### ISSUE TITLE
How to get all checked rows from Angular Material Selection Table

### ISSUE THREAD

**Issue by prashantpimpale93** [angular/material2#14347]
#### Bug, feature request, or proposal:

Question: How to get all checked rows or object or key etc. from Angular Material Selection Table 

#### What is the expected behavior?
Is there any way to get the Checked Items index or single object on submit button click where I can push into SelectedList Array?

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/edit/angular-jlk4vf<br/>

#### What is the use-case or motivation for changing an existing behavior?
It would be better to get the checked objects and call API

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6 and >

**Comment by manklu** [comment]
Via the selection model?

``this.selection.selected``

**Comment by prashantpimpale93** [comment]
@manklu Thanks! That is what I am looking for!
