### ISSUE TITLE
Performance issue on filtering mat-table

### ISSUE THREAD

**Issue by abhisb** [angular/material2#14354]
#### Bug, feature request, or proposal:
Performance issue

#### What is the expected behavior?
mat table should not have performance issues while filtering

#### What is the current behavior?
Performance issue for more than 500 table rows

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0

When I try to filter the table(with more than 500 rows) data using the below code, it is taking some delay to filter it. If the number of rows are below 500 it is not taking much time to filter.

```
 doFilter(value: string, type: string) {
    this.filter = {
      ...this.filter,
      [type]: value.trim().toLowerCase()
    };
    this.dataSource.filter = JSON.stringify(this.filter);
  }

```

**Comment by andrewseguin** [comment]
Please re-open with steps to reproduce, preferably with a reproduction in StackBlitz, so we can diagnose the potential issue and create a fix. Thanks
