### ISSUE TITLE
Mat-icon cannot be displayed using svgIcon

### ISSUE THREAD

**Issue by conyxun** [angular/material2#14360]
#### Bug, feature request, or proposal:
mat-icon cannot be displayed using svgIcon.

#### What is the expected behavior?
![fy34rsdzogs klv07q9ug x](https://user-images.githubusercontent.com/24432969/49350610-8ccfaa00-f6ea-11e8-9e3d-e9a471070db5.png)

#### What is the current behavior?
The icon does not display properly, and I did not find a valid solution
![vly_l6s62w17pn0j88sr _5](https://user-images.githubusercontent.com/24432969/49350660-c2749300-f6ea-11e8-9fde-720272bf9bf8.png)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/angular/qvnnodrrkdo?file=app%2Ficon-svg-example.html<br/>
The official example also fails to display on stackblitz.com.

**Comment by MarcusCalidus** [comment]
I was not able to reproduce my solution in stackblitz. I guess this might be an issue of the platform.
Here's how I solve the problem

in your local typings.d.ts
```
declare module "*.svg" {
    const value: any;
    export default value;
}
```

in your component/module (I use the app.module.ts)
```
import icon_wrench from '@fortawesome/fontawesome-pro/svgs/regular/wrench.svg'; // or any local path relative to your current file
```

in your loader routine (e.g. app.module constructor)
```
matIconRegistry.addSvgIcon('wrench', domSanitizer.bypassSecurityTrustResourceUrl(icon_wrench));
```

There is a working copy'n'paste example in the following package: https://github.com/MarcusCalidus/ts-material-icons-svg

**Comment by conyxun** [comment]
@MarcusCalidus 
I am very sorry, I finally found the error after trying the suggestion.
The reason why the icon is not displayed is caused by rewriting the event.body content in the HttpInterceptor.
But I don't understand why the same effect is seen when viewing the official example, so that I think it is a matter of material.
