### ISSUE TITLE
Npm version doesn't match the latest alpha.9-3

### ISSUE THREAD

**Issue by Yonet** [angular/material2#1437]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Being able to install 2.0.0-alpha.9-3

#### What is the current behavior?
npm install latest is v2.0.0-alpha.8-2 

#### Which versions of Angular, Material, OS, browsers are affected?
material2@2.0.0-alpha.9-3

**Comment by Ploppy3** [comment]
The repository changed to @angular/material for alpha 9.

**Comment by ocarreterom** [comment]
Dup #1435
