### ISSUE TITLE
Feature Request: matFormField appearance="fill" has no way to control the background color.

### ISSUE THREAD

**Issue by stot3** [angular/material2#14381]
I am enjoying the new additions to mat-form-field but I am unable to use them in my project because the background color of the input is too hard to select. I've tried all manner of css selectors and between inline styling, I have yet to find a way to change the background-color or any documentation stating how the theme it. I am aware that input allows for the underline, and the label, but in this case, there is no way to change the fillColor. I propose maybe something like 

```
<mat-form-field appearance="fill>
<input matInput name="name" fillColor="accent"> 
</mat-form-field>
```

or
```
<mat-form-field appearance="fill" fillColor="accent">
<input matInput name="name>
</mat-form-field>
```

This change will greatly improve the versatility of matInput, and allow for matInput to be used in a variety of applications!

**Comment by mmalerba** [comment]
It's probably not something we plan to do since it isn't part of the spec. If you must, you can override the CSS: https://stackblitz.com/edit/angular-material2-issue-svudcf?file=app%2Fapp.component.css (make sure to disable view encapsulation or use `::ng-deep`)
