### ISSUE TITLE
Material Tabs with lazy loading rendering every time it's active

### ISSUE THREAD

**Issue by happyPrograming** [angular/material2#14386]
Bug, feature request, or proposal :

Material tabs (with matTabContent) are rendering  every time it's active (clicking on it ).

What is the expected behavior?

rendrer the first time it's activated only .

 What is the current behavior?

rendering each time we click on it.

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
