### ISSUE TITLE
cdkDropList broken on touch devices on touchend

### ISSUE THREAD

**Issue by atscott** [angular/material2#14390]
#### What is the expected behavior?
cdkDropList does not error

#### What is the current behavior?
The _cleanupDragArtifacts method now calls _getPointerPositionOnPage which does not handle touchend events correctly:
`const point = this._isTouchEvent(event) ? event.touches[0] : event;` 
 ==> When the event is "touchend" the event.touches array is empty. Instead changedTouches has the Touch object you need.
Documentation for the touches array (key portion "touch points that are currently in contact"):
A TouchList listing all the Touch objects for touch points that are currently in contact with the touch surface, regardless of whether or not they've changed or what their target element was at touchstart time.

#### What are the steps to reproduce?
I don't think this is available as an npm yet, so I can't get a stackblitz.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I believe this was caused by https://github.com/angular/material2/pull/14140 and affects all touch-based browsers

**Comment by crisbeto** [comment]
@atscott what is the case in which the `event.touches` would be empty?

**Comment by atscott** [comment]
For a cdkDropList, it happens at the very end when you drop the element. This is a touchend event, which does not have any active touch points so the `event.touches` array is empty. This can be reproduced in the chrome developer console.

**Comment by atscott** [comment]
I think this could be solved simply with:
`const point = this._isTouchEvent(event) ? (event.touches[0] || changedTouches[0]) : event;`

**Comment by crisbeto** [comment]
Yes, I can put in a fix for it, but first I want to understand how the issue happens. I wasn't able to reproduce it with the dev tools:

![demo2](https://user-images.githubusercontent.com/4450522/49541099-02e23580-f8d2-11e8-8a9c-d8344c863779.gif)

**Comment by atscott** [comment]
You're doing the right thing to reproduce the bug. I don't think the bug is in the 7.1.1 release (even though that was created 2 days ago and the PR was submitted 7 days ago). I don't see the bug fix in the release notes and if I inspect the source, I don't see the call to _getPointerPositionOnPage in _cleanupDragArtifacts.

**Comment by crisbeto** [comment]
Thanks, I see it when I run master.
