### ISSUE TITLE
drag-drop: invoke renderRows() method to refresh mat-table, but cdkDropList has not been updated

### ISSUE THREAD

**Issue by wswanking** [angular/material2#14401]
#### What is the expected behavior?
update cdkDropList after invoking mat-table.renderRows() method

#### What is the current behavior?
cdkDropList has not been updated after invoking mat-table.renderRows() method

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular:7.0.4 
OS:window 10
TypeScript:3.1.6
browsers:Google Chrome 67.0.3396.87

**Comment by andrewseguin** [comment]
Please re-open with steps to reproduce, preferably in StackBlitz, so we can diagnose your issue and create a fix if necessary. Thanks!
