### ISSUE TITLE
Implementation of the new material style guide planned?

### ISSUE THREAD

**Issue by BamiGorengo** [angular/material2#14400]
As everyone knows, many things changed in the material styleguide not long ago. Just as an example: Everything is round and especially noticeable the [new input fields](https://material.io/design/components/text-fields.html)

I find the new styleguide more beautiful than the old one. I can not find any information about whether this implementation is planned or not, I thought I just ask here.

**Comment by crisbeto** [comment]
The new Material Design spec is mostly supported (with a couple of exceptions). You can get the new form fields using the `appearance` input.
