### ISSUE TITLE
bug(drag-drop): Safari selects text on drag

### ISSUE THREAD

**Issue by philmtd** [angular/material2#14403]
#### What is the expected behavior?
Safari (or any browser) should not select text when starting to drag an item.

#### What is the current behavior?
When starting to drag an item in a drop list, Safari selects the text that is near to the dragged item.

#### What are the steps to reproduce?
**Stackblitz:** https://stackblitz.com/edit/angular-material2-issue-b6tvka
Switch the versions of cdk and material to 7.1.0 to see the previous and correct behaviour.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
* Safari 12.0.1 (but probably not only this version)
* CDK & Material 7.1.1 

#### Is there anything else we should know?
I tried it with Chrome and Firefox on macOS and the bug did not appear there, so it is probably exclusive to Safari. This bug was introduced in the 7.1.1 release. Downgrading to 7.1.0 fixes this behaviour. This can easily be verified using the stackblitz example from above.

**Comment by crisbeto** [comment]
This is most likely due to https://github.com/angular/material2/commit/1c74b034c9cd4183dff994fe43565410d138e6fd. We had to remove our previous workaround for Safari, because it had a lot of performance implications on pages with a lot of elements.

**Comment by philmtd** [comment]
I also suspected that. Thanks for fixing it so fast :)
