### ISSUE TITLE
Autocomplete scrolls text to the beginning when blurred

### ISSUE THREAD

**Issue by mtaran-google** [angular/material2#14425]
#### What is the expected behavior?
Text should remain as is when blurred

#### What is the current behavior?
Text gets scrolled to the beginning when blurred

#### What are the steps to reproduce?
1. type a long string into the autocomplete at https://material.angular.io/components/autocomplete/examples
2. click out of the field
3. watch as the long text gets scrolled right such that the beginning of the text is visible at the beginning of the field (rather than the end of the text being visible at the end of the field)

#### Is there anything else we should know?
At the very least there should be some API available to disable this behavior, since we use a version of an autocomplete that can complete multiple values, and so a possible case is that *many* values get autocompleted, in which case having this behavior gets very annoying if you want to e.g. copy paste in multiple values in order at the end.

**Comment by crisbeto** [comment]
This is default behavior for `input` elements, `mat-autocomplete` doesn't do anything. You can try out a regular `input` which does the same: https://codepen.io/crisbeto/pen/GPKQWj

**Comment by mtaran-google** [comment]
mind blown :O
