### ISSUE TITLE
Allow dynamic access to palettes

### ISSUE THREAD

**Issue by code-tree** [angular/material2#1442]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Palettes can be dynamically chosen: `md-palette($palette-name)`

#### What is the current behavior?
Palette choices must be hard-coded: `md-palette($md-red)`

#### What are the steps to reproduce?
```scss
$palette-name: red;
$palette: md-palette($palette-name)
```

#### What is the use-case or motivation for changing an existing behavior?
My app is built for different deployments, and needs to set a different palette per deployment. Other users may want to loop through palettes to deploy them all (and let user select colors).

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0-alpha.9

#### Is there anything else we should know?
Either the palettes could all be contained within a map already, or the following map could be added alongside the palettes:

```scss
$name-to-palette: (
    red: $md-red,
    pink: $md-pink,
    purple: $md-purple,
    deep-purple: $md-deep-purple,
    indigo: $md-indigo,
    blue: $md-blue,
    light-blue: $md-light-blue,
    cyan: $md-cyan,
    teal: $md-teal,
    green: $md-green,
    light-green: $md-light-green,
    lime: $md-lime,
    yellow: $md-yellow,
    amber: $md-amber,
    orange: $md-orange,
    deep-orange: $md-deep-orange,
    brown: $md-brown,
    grey: $md-grey,
    blue-grey: $md-blue-grey,
);
```

**Comment by jelbourn** [comment]
@code-tree you can do something like:
```scss
$my-app-palette: $md-red; // or $md-blue, etc.

$my-primary: md-palette($md-app-palette);
```

It's all just normal sass variables.

**Comment by code-tree** [comment]
Yea, I tried that but I was injecting the variable at the start of the sass file, which wasn't allowed as it came before the import for `$md-red`. I solved it with the map I posted above, so no problem. Was just thinking it might help someone else too (they can just search and find it here then).
