### ISSUE TITLE
md-line does not work inside a template

### ISSUE THREAD

**Issue by maryamsoprano** [angular/material2#1443]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I expect to have multiple lines for each md-list-item . I use template tag , and clone it's content inside of my *ngFor loop.

#### What is the current behavior?
I don't have multiple lines. 
 

#### What is the use-case or motivation for changing an existing behavior?
I have a component named DynamicRepeater,
   DynamicRepeater.html:

```html
<md-list>
  <md-list-item *ngFor="let item of items ; let i = index" (click)="itemSelect(item)">
    <template [render]="itemTemplateRef" [context.item]="item"
              [context.index]="index"></template>
  </md-list-item>
</md-list>
```
and this is my AppComponent.html:

```html
<dynamic-repeater [items]="service.records" [itemSelect]="select">

  <template #itemRenderer let-item="item">
    <img md-list-avatar src="{{item.img}}">
    <p md-line>
      {{item.firstName}} {{item.lastName}}
    </p>

    <p md-line>
      <md-icon>message</md-icon>
    </p>
  </template>
  </sei-summary>
```

I expected that message Icon appears at the next line of firstName and lastName, but I have both of them in one line.

#### Which versions of Angular, Material, OS, browsers are affected?
I am using last version(final) version of angular and materials

**Comment by maryamsoprano** [comment]
Hi,

Sorry , It was my mistake.I should have use it like this:

` <p md-line>
            <a md-line>
              {{item.firstName}} {{item.lastName}}
            </a>
            <a md-line>
             
              <md-icon>message</md-icon>
             
            </a>
          </p>
`

Now It works

**Comment by fxck** [comment]
Can you close this then @maryamsoprano ?

**Comment by no-more** [comment]
Hi,

I'm not sure to understand your solution, seems like you set md-line elements inside of an md-line element ? 

If that's it I'm not sure this is the expected behavior nor the way to do it.

**Comment by jelbourn** [comment]
I don't really follow the code in the original report, but it seems the reporter is satisfied.
