### ISSUE TITLE
Checkbox appears to high when placed in mat-table

### ISSUE THREAD

**Issue by sebasijan** [angular/material2#14433]
#### What is the expected behavior?

Checkboxes should appear within column just like [here](https://stackblitz.com/edit/delete-rows-mat-table?file=app%2Ftable-selection-example.css)

#### What is the current behavior?

The checkboxes are just too high.... Why?

![image](https://user-images.githubusercontent.com/13226838/49694293-54b7e380-fb90-11e8-97f9-99fb6fdf1686.png)

#### What are the steps to reproduce?

Here is the table:

It all works fine, just the checkbox is too high...

        <div class="container loansContainer">
        
      <h1>Current Loans</h1>

        <table #table mat-table [dataSource]="dataSource" 
              class="mat-elevation-z8" matSort>
          
          
        <ng-container matColumnDef="select">
          <mat-header-cell *matHeaderCellDef>
            <mat-checkbox (change)="$event ? masterToggle() : null"
                          [checked]="selection.hasValue() && isAllSelected()"
                          [indeterminate]="selection.hasValue() && !isAllSelected()">
            </mat-checkbox>
          </mat-header-cell>
          <mat-cell *matCellDef="let row">
            <mat-checkbox (click)="$event.stopPropagation()"
                          (change)="$event ? selection.toggle(row) : null"
                          [checked]="selection.isSelected(row)">
            </mat-checkbox>
          </mat-cell>
        </ng-container>
          
          <ng-container matColumnDef="id">
              <th mat-header-cell *matHeaderCellDef mat-sort-header> Id </th>
              <td mat-cell *matCellDef="let loan">{{loan.id}}</td>
            </ng-container>
        
          <ng-container matColumnDef="borrowerName">
            <th mat-header-cell *matHeaderCellDef mat-sort-header> Client Name </th>
            <td mat-cell *matCellDef="let loan">{{loan.borrowerName}}</td>
          </ng-container>
          <ng-container matColumnDef="fundingAmount">
              <th mat-header-cell *matHeaderCellDef mat-sort-header> Funding </th>
              <td mat-cell *matCellDef="let loan">{{loan.fundingAmount}}</td>
            </ng-container>
            <ng-container matColumnDef="repaymentAmount">
                <th mat-header-cell *matHeaderCellDef mat-sort-header> Repayment </th>
                <td mat-cell *matCellDef="let loan">{{loan.repaymentAmount}}</td>
              </ng-container>

              <ng-container>
                <th> Delete </th>
                <td>X</td>
              </ng-container>
              
        
          <tr mat-header-row *matHeaderRowDef="columnsToDisplay"></tr>
          <tr mat-row *matRowDef="let myRowData; columns: columnsToDisplay;"
            (click)="selection.toggle(row)"></tr>
        </table>
    </div>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    ng version 
			 _                      _                 ____ _     ___
			/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
		   / Ôû│ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
		  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
		 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
						|___/
			

		Angular CLI: 7.1.1
		Node: 10.13.0
		OS: win32 x64
		Angular: 
		... 

		Package                      Version
		------------------------------------------------------
		@angular-devkit/architect    0.11.1
		@angular-devkit/core         7.1.1
		@angular-devkit/schematics   7.1.1
		@schematics/angular          7.1.1
		@schematics/update           0.11.1
		rxjs                         6.3.3
		typescript                   3.1.6

**Comment by andrewseguin** [comment]
It's not clear based on what you provided why that is happening. If you swing over to Gitter or StackOverflow with a reproduction in StackBlitz, I'm sure someone can help you out.
