### ISSUE TITLE
If an md-grid-list is populated with a *ngFor loop, gutters are not displayed between the rows.

### ISSUE THREAD

**Issue by danny-swimmer** [angular/material2#1444]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Regardless of how the md-grid-list is populated, gutters should be displayed between the rows.

#### What is the current behavior?
If an md-grid-list is populated with a *ngFor loop, gutters are not displayed between the rows.

#### What are the steps to reproduce?
Please see this plunk: http://plnkr.co/edit/ZRMDUBiqdSCMMniMCcdx
It shows a good and a bad case.

#### What is the use-case or motivation for changing an existing behavior?
In real life, most grid lists will be populated with a ngFor loop.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0.1
@angular2-material/grid-list - v2.0.0-alpha.8-2

#### Is there anything else we should know?
No

**Comment by fxck** [comment]
Well you are iterating over `md-grid-list`, that's why there's no gutter, iterate over tiles instead http://plnkr.co/edit/6ittGUZa6WggPRo2vJOQ?p=preview

**Comment by danny-swimmer** [comment]
Thanks @fxck for pointing out my error. I'm closing the issue.
