### ISSUE TITLE
mat-tab-nav-bar cannot show full tab

### ISSUE THREAD

**Issue by sylvester-etronix** [angular/material2#14460]
#### What is the expected behavior?
The tab group can show all the tab need assign in the array.

#### What is the current behavior?
Currently the tab group cannot show all the tab.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/edit/angular-fkmnx7?file=app/tab-nav-bar-basic-example.ts<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version: "@angular/cli": "7.1.1"
Material Version: "@angular/material": "7.1.1"
OS:window 10
TS:  "typescript": "3.1.6"

![capture](https://user-images.githubusercontent.com/45072247/49792197-14618c80-fd6d-11e8-9cbc-a5ea9d01efa3.PNG)

**Comment by andrewseguin** [comment]
Looks like your reproduction link is broken, can you re-open the ticket with a working example? Thanks

**Comment by sylvester-etronix** [comment]
here is the link https://stackblitz.com/edit/angular-4wjrxr?file=app%2Ftab-group-basic-example.ts

**Comment by anisabboud** [comment]
Duplicate of #2177
