### ISSUE TITLE
Allow more colors on a theme

### ISSUE THREAD

**Issue by tbnovaes** [angular/material2#14474]
#### Please describe the feature you would like to request.
It would be great if we could have more than just primary, accent and warn colors.

#### What is the use-case or motivation for this proposal?
It is very hard to use only 3 colors on the entire application, and even tho it is possible to use css classes, when you create an application supporting multiple themes, it gets hard to maintain it as application grows.

#### Is there anything else we should know?
It also would be great if we could have an extra directive to define what color shade from the palette we want to use as base. 

For Example.: `<button color="accent" colorShade="300">Button</button>`

**Comment by mattdanna** [comment]
💯 agreed. The workarounds to hack in additional colors adds a lot of bloat

**Comment by jelbourn** [comment]
We unfortunately have no plans to expand the theming system until we're able able to switch to CSS variables (when we can drop support for IE11).
