### ISSUE TITLE
Material select - selectionChange not firing when setting value from code, not by user but programmatically.

### ISSUE THREAD

**Issue by SWGeekPD** [angular/material2#14486]
I want to set Mat-Select value from code. 
And based on assigned drop down value I need to show/hide few form fields. I am setting the Mat-Select value from .ts file on initialization. like this
**this.myForm.controls.myControl.setValue(this.dd[1]);**

This is setting the value in Mat-Select drop down, but it is not triggering **selectionChange** event and hence not able to show/hide other fields. Also reactive form mat-select field is not dirty.
Please suggest if there is a way to achieve this.

**Comment by dhrn** [comment]
can you **reproduce** the issue with [stackblitz](https://stackblitz.com/)?

**Comment by crisbeto** [comment]
This is working as intended. Via the API docs:

> Event emitted when the selected value **has been changed by the user**.

You can use `valueChange` if you want to know about all the changes.
