### ISSUE TITLE
Toggle (mat-slide-toggle) highlight not fading away after interaction

### ISSUE THREAD

**Issue by ismailgurler** [angular/material2#14485]
#### What is the expected behavior?
The shadow/highlight when turning the toggle either on or off should disappear after setting the toggle.

#### What is the current behavior?
The shadow/highlight stays after setting the toggle.

#### What are the steps to reproduce?
The bug is also present here (version 7.1.1) --> https://material.angular.io/components/slide-toggle/overview 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1.1
Material 7.1.0

**Comment by devversion** [comment]
This will be fixed with #13562
