### ISSUE TITLE
md-radio-button ripple effect

### ISSUE THREAD

**Issue by joshterrill** [angular/material2#1449]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

When you click a radio button, the ripple ripples and then you see it checked.
#### What is the current behavior?

When you click a radio button, it freezes at the beginning of the ripple and a yellow outlined circle is around it.
#### What are the steps to reproduce?

Plunkr: http://plnkr.co/edit/Psw6jjHvIHhWJRj6COfq?p=preview
#### What is the use-case or motivation for changing an existing behavior?

So it works the way it's supposed to!
#### Which versions of Angular, Material, OS, browsers are affected?

Angular version: 2.0.2
Material version: 2.0.0-alpha.9-3
OS: Mac OSX El Capitan
Browser: Chrome Version 53.0.2785.143 (64-bit)
#### Is there anything else we should know?

The material 1 radio button works as expected in the same browser and OS: https://material.angularjs.org/latest/demo/radioButton

Here's a screenshot of what it looks like on first click:

![Imgur](http://i.imgur.com/bmzrKek.png)

Then once you click off of it or focus something else, it unfreezes the ripple effect.

**Comment by fxck** [comment]
Ripples are not quite done yet, this is more of a placeholder. https://github.com/angular/material2/issues/108

**Comment by joshterrill** [comment]
What do you mean by that's more of a placeholder? Is there a way to add that to my radio button to make it work?

**Comment by mikekauffman** [comment]
Having the same problem. Is it possible to disable the broken effect until it's fixed. Radio buttons are not currently usable.

**Comment by tinayuangao** [comment]
Fixed by #1553
