### ISSUE TITLE
mat-expansion-panel not working first-time

### ISSUE THREAD

**Issue by ORESoftware** [angular/material2#14495]
I have these 3 components:

grandparent:

```html
<app-route-group *ngFor="let list of routes" [ves]="r" [list]="list">
</app-route-group>
```

parent:
```html
<mat-card>
  <mat-card-content>

    <app-route *ngFor="let r of list" [ves]="r"></app-route>

  </mat-card-content>
</mat-card>
```

and grandchild:

```html
<mat-expansion-panel>
  <mat-expansion-panel-header>
    <mat-panel-title>
      This is the expansion title
    </mat-panel-title>
    <mat-panel-description>
      Mat Panel Description
    </mat-panel-description>
  </mat-expansion-panel-header>

( This is the primary content of the panel)

</mat-expansion-panel>
```

the problem is that on first render - the expansion panels are really slow to respond, 1 or 2 second delay to expand upon a click.
If I re-render, then the expansion panels are much more responsive, back to normal. Has anyone experienced this problem before? I don't see how my code could be a problem perse, it works, just daaaaamn slow the first time.

My only other hypothesis is a loop (feedback loop) in the code, that's not quite infinite, but sucks up some time until it breaks out. But I am not seeing such a loop in my code with logging statements.

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
