### ISSUE TITLE
Create folders by merging app icons - need support for move and dragInto eventing

### ISSUE THREAD

**Issue by bitbaggi** [angular/material2#14499]
Hi Guys,

is there a way to distinguish the drop and hover event over the target cdkDrag element, because we want to create an app/folder design where you can drag apps on other apps to create folders like on your Smartphone.
So the Drop/Hover event has to distinguish between moving the apps and dropping apps onto each other.

Thanks in advance.
Pascal

**Comment by crisbeto** [comment]
Couldn't you use the `cdkDropListEntered` and `cdkDropListExited` events to know when the user has entered/exited?

**Comment by bitbaggi** [comment]
![image](https://user-images.githubusercontent.com/19170730/49996581-49e1c200-ff87-11e8-9f6a-7e4ab0c0a376.png)

This is my Code:
[code.txt](https://github.com/angular/material2/files/2679621/code.txt)
needs angular component with DragDropModule

don't know how to use cdkDropListEntered with this construct
