### ISSUE TITLE
mat-tab remove the tab-body DOM but not hide it

### ISSUE THREAD

**Issue by shenchaoran** [angular/material2#14512]
#### What is the expected behavior?
When switch mat-tabs, the unselected tab content DOM is removed

#### What is the current behavior?
hide the unselected tab-content DOM by `display: none` 

#### What are the steps to reproduce?
[here](https://stackblitz.com/edit/ng-material-starter?file=src%2Fapp%2Fmat-tab%2Fmat-tab.component.html)

I use jexcel in the md-tab, when I
- select a cell
- switch to tab 2
- switch back to tab 1

I got some error like `Cannot read property 'onblur' of undefined`, because the jexcel container DOM is removed but not hiddened. 

So should we hidden it but not remove it like bootstrap?

**Comment by andrewseguin** [comment]
When I am able to reproduce the error, it seems that the problem is jexcel has trouble removing selection when the tab is not on the page. I recommend listening to the `selectedTabChange` and destroying the table if the tab is switched, just like you would do if the component is destroyed.

https://stackblitz.com/edit/ng-material-starter-9q8wjz?file=src/app/mat-tab/mat-tab.component.html

**Comment by taraa62** [comment]
I have the same removal problem.
In the first tab put the download of the game, the second feature for it, when I turn into the second, and turn back, all the content is recovered but the game has already worked to delete and is loaded again ..
Is there a solution to this problem? or is it better not to use this component?

**Comment by shenchaoran** [comment]
> I have the same removal problem.
> In the first tab put the download of the game, the second feature for it, when I turn into the second, and turn back, all the content is recovered but the game has already worked to delete and is loaded again ..
> Is there a solution to this problem? or is it better not to use this component?

I think this component don't support this demand, because it recreate the DOM in the tab. You can choose a component toggle the display state by `display: none` like Bootstrap
