### ISSUE TITLE
[Discussion] - Making CDK as a separated project

### ISSUE THREAD

**Issue by andrewtw** [angular/material2#14517]
I'm not sure whether `material2` repo allows discussion, but I've been wondering for months.

CDK provides fundamentals for developers to create their own components faster, I assume CDK is firstly introduced to provide basic functionality for `material2`.

Although CDK is published as a separated package on NPM, its source code still exists under `material2`.

Furthermore, CDK documents are put in material website instead of its own one, this strategy makes Angular community weaker to those newcomers, because material design is not suitable for all applications, but when they are looking for something that can help to build their own UIKit, they will eventually be at `material.angular.io` which may cause misunderstanding, eg. [Please look at the answers and comments, from StackOverflow](https://stackoverflow.com/questions/42340649/what-is-cdk-in-angular-material-2-components)

Building UIKit faster and easier is a huge attractive point for developers, and CDK is the key to influence the people's willing at adapting Angular.

Any open source projects should maintain the passions and motivations of their communities so they can go stronger and bigger.

Don't get me wrong, as an engineer from Asia, I've been working hard to share the developing experiences with others, including writing CDK tutorial in Chinese version in Traditional and Simplified directly, the fact is, popularity and community of Angular are still far behind Vue and React, after several talks, I figure out most developers consider Angular lacks of flexibility on making own UIKit for their companies/projects.

**Comment by jelbourn** [comment]
We definitely agree- I don't have anything specific to share right now, but we're looking at how to make this more clear in 2019. 

Going to close this issue since it's not immediately actionable, but stay tuned in 2019 for updates.

**Comment by johanchouquet** [comment]
I agree too. Would be a lot nicer. Now that each material element has its own module, I think it makes a lot of sense.

Any update on this ?
