### ISSUE TITLE
mat-expansion-panel with *ngFor fires datamethod infinitely

### ISSUE THREAD

**Issue by lietzi** [angular/material2#14521]
#### What is the expected behavior?
Displaying an useable accordion with expansion panels generated 
out of dynamic data fetched by a method in a *ngFor-loop

#### What is the current behavior?
fires method infinitely until process ran out of memory and freezes

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-esus4p

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.1.2
Node: 10.10.0
OS: win32 x64
Angular: 7.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.2
@angular-devkit/build-angular     0.11.2
@angular-devkit/build-optimizer   0.11.2
@angular-devkit/build-webpack     0.11.2
@angular-devkit/core              7.1.2
@angular-devkit/schematics        7.1.2
@angular/cdk                      7.1.1
@angular/material                 7.1.1
@ngtools/webpack                  7.1.2
@schematics/angular               7.1.2
@schematics/update                0.11.2
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

**Comment by crisbeto** [comment]
This is how change detection works and it doesn't have anything to do with Material. Angular has to re-run the `getPanels` function on each change detection cycle in order to know whether something has changed.
