### ISSUE TITLE
 bootstrap panel equivalent in angular material

### ISSUE THREAD

**Issue by Furqanaa** [angular/material2#14527]
If you go to the [official Angular Material website](https://material.angular.io/components/card/overview), you'll see the examples are wrapped in what looks to be Bootstrap panels (see Basic Card). Yet there is no material component for these panels. The closest I can find is mat-card, which does not appear the same.

Is there a native html element for this? What am I missing?

**Comment by jelbourn** [comment]
It's not a pattern included in the library, it's just something specific to the docs. You should be able to use the [elevation APIs](https://material.angular.io/guide/elevation) to pretty much do the same thing.

**Comment by Furqanaa** [comment]
@jelbourn I already started using that. thanks
