### ISSUE TITLE
No background-color css in mat-select-panel 

### ISSUE THREAD

**Issue by Abdullah-FAl** [angular/material2#14546]
#### What is the expected behavior?

https://material.angular.io/components/select/overview

#### What is the current behavior?
No background-color css in class .mat-select-panel 

 
![image](https://user-images.githubusercontent.com/22343540/50091531-b1fd0600-021c-11e9-9f11-4b87a36621ec.png)  «««««

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/angular/nqgbrbknjje<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1.3
material 7.1.1
typescript 3.1.6

**Comment by crisbeto** [comment]
My guess is that either something isn't correctly or you've got some of your own styles overriding the panel's background. Are you sure that your theme CSS isn't included inside of a component with view encapsulation?

**Comment by Abdullah-FAl** [comment]
yes i am sure theme CSS isn't included inside of a component with view !

I have a normal component
And added a mat-select component to it
form material.angular.io

**Comment by Abdullah-FAl** [comment]
Some styles appear and some do not appear in mat-select component

**Comment by jelbourn** [comment]
@Abdullah-FAl can you share a reproduction?

**Comment by rskendzic** [comment]
I reproduced the same issue with:

`"@angular/cdk": "~7.2.0",`
`"@angular/material": "^7.2.0",`

inside [Mat Table Paginator](https://material.angular.io/components/paginator/overview) items per page select. 

I am not using prebuilt theme, I have created my own: 

`$app-primary: mat-palette($mat-red);
$app-accent: mat-palette($mat-indigo, A200, A100, A400);
$app-warn: mat-palette($mat-amber, 400);
$app-dark-theme: mat-dark-theme(
$app-primary,
$app-accent,
$app-warn
);`

and wrapped it inside a class as [per docs](https://material.angular.io/guide/theming)

`.theme__dark {
  @include angular-material-theme($app-dark-theme)
}`

this class is set in app.component.ts
`<div class="theme-dark"><router-outlet></router-outlet></div>`

Inside this router outlet obviously is the Mat Table Component :) with the problem... 

I managed to solve the problem with `::ng-deep .mat-select-panel {
  background: white;
}` but I have lost ripple and hover effects... 

Other components on the page( mat-cards, table itself...) don't have before-mentioned problem, only mat-select component

**Comment by crisbeto** [comment]
@rskendzic I tried out your theme config against our dev app and it seems to work:

![angular_material_-_google_chrome_2019-01-04_15-08-06](https://user-images.githubusercontent.com/4450522/50689478-91151d00-1032-11e9-8b78-b5156f4ecf46.png)

**Comment by Abdullah-FAl** [comment]
Hello! @ @jelbourn  and @rskendzic  Sorry for the late reply !
I'm after some debugging
**I solved the problem!**
**It was @import ~ @ angular / material / theming**
**More than once and I am the cause of the problem!**
You can view my [#commit](https://github.com/Abdullah-FAl/my-Angular-Material-project/commit/855076c8a36e56a0f7690870c541d5dae9dfc9d7) to this [Test Project](https://github.com/Abdullah-FAl/my-Angular-Material-project)

### **Providing a StackBlitz reproduction !** 
StackBlitz starter:   https://stackblitz.com/github/Abdullah-FAl/my-Angular-Material-project
