### ISSUE TITLE
Must the button to make md-sidenav visible be contained in md-sidenav-layout?

### ISSUE THREAD

**Issue by churchilllake** [angular/material2#1455]
#### Bug, feature request, or proposal:
Bug: button to make md-sidenav visible has to be contained in md-sidenav-layout

#### What is the expected behavior?
md-sidenav made visible from component outside md-sidenav-layout

#### What is the current behavior?
md-sidenav is inert

#### What are the steps to reproduce?
non-working md-sidenav:
[http://plnkr.co/edit/HUylyrN05AYtx77LzaTZ?p=preview](url)

Move md-sidenav-layout to top and it works

#### What is the use-case or motivation for changing an existing behavior?
Need to know if md-sidenav-layout must enclose the button that makes it visible.

#### Which versions of Angular, Material, OS, browsers are affected?
angular-cli: 1.0.0-beta.16
node: 6.4.0
os: darwin x64
material: 2.0.0-alpha.9-3

**Comment by jmcgoldrick** [comment]
You just need to have something in that main content area for some reason, and it works just like you would expect, see: http://plnkr.co/edit/rygo7bBAVAKt7x4Kk8yF?p=preview
