### ISSUE TITLE
mat-ripple doesn't works sometimes

### ISSUE THREAD

**Issue by shenchaoran** [angular/material2#14558]
#### What is the expected behavior?
ripple effect 

#### What is the current behavior?
I use mat-ripple in `@material/image-list` of `material-components-web`, but in the first row, it only works the first column.

#### What are the steps to reproduce?
please find [here](https://stackblitz.com/edit/ng-material-starter?file=src%2Fapp%2Fimage-list%2Fimage-list.component.html)

the row1 column2 and row1 column3 doesn't work

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1.3
Material 7.1.1

**Comment by jelbourn** [comment]
You're looking for https://github.com/material-components/material-components-web

**Comment by jelbourn** [comment]
Ah, I misread at first.

**Comment by jelbourn** [comment]
@shenchaoran your stackblitz doesn't seem to run

**Comment by shenchaoran** [comment]
@jelbourn sorry, it should work now

**Comment by devversion** [comment]
I looked into it, but the logic of `MatRipple` seems right. Something seems to be throwing off the absolute positioning of the ripple.

This looks like the following chromebug: https://bugs.chromium.org/p/chromium/issues/detail?id=527709

Closing as this seems to be a bug within Chrome.
