### ISSUE TITLE
MatChipList change event not fired on toggleSelected

### ISSUE THREAD

**Issue by gianlucaparadise** [angular/material2#14554]
#### What is the expected behavior?
MatChipList change event should be fired when I call `toggleSelected()` on one of the MatChips inside the list.

#### What is the current behavior?
MatChipList change event is fired only when I select the MatChip pressing the space button on the keyboard.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ynznsk?file=app%2Fchips-stacked-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "rxjs": "6.3.3",
    "moment": "2.23.0",
    "core-js": "2.6.0",
    "zone.js": "0.8.26",
    "hammerjs": "2.0.8",
    "@angular/cdk": "7.1.1",
    "@angular/core": "7.1.3",
    "@angular/http": "7.1.3",
    "@angular/forms": "7.1.3",
    "@angular/common": "7.1.3",
    "@angular/router": "7.1.3",
    "@angular/compiler": "7.1.3",
    "@angular/material": "7.1.1",
    "web-animations-js": "2.3.1",
    "@angular/animations": "7.1.3",
    "@angular/platform-browser": "7.1.3",
    "angular-in-memory-web-api": "0.5.4",
    "@angular/material-moment-adapter": "7.1.1",
    "@angular/platform-browser-dynamic": "7.1.3"

#### Is there anything else we should know?
Change event is also **not** fired when:

* MatChip `select()` method is called
* MatChip `selected` property is updated
* The model property bound to the MatChip `selected` property is updated

**Comment by crisbeto** [comment]
From the change event docs:

> Event emitted when the selected chip list value has been **changed by the user**.

You can use the `valueChange` event or a two-way binding on the `value` if you want to react to all changes.
