### ISSUE TITLE
Drag and Drop List Group Drag

### ISSUE THREAD

**Issue by eugene-chehovskoy** [angular/material2#14571]
#### Please describe the feature you would like to request.
I need to be able to drag and drop not only list items withing list and between different lists, I also need to be able to to drag lists.

#### What is the use-case or motivation for this proposal?
Good examples are "Trello" and "GitHub Projects" where I can create cards and add rows to cards, move rows within card (this is possible in Material Drag and Drop), move rows between cards (this is possible in Material Drag and Drop by using cdkDropListGroup) and finally move cards themselves (it's impossible or I don't understand how to achieve this)

**Comment by crisbeto** [comment]
You can put `cdkDropList` and `cdkDrag` on the same element.
