### ISSUE TITLE
bug(docs): lockAxis should be cdkDropListLockAxis on Drag&Drop overview

### ISSUE THREAD

**Issue by IlCallo** [angular/material2#14572]
#### What is the expected behavior?
https://material.angular.io/cdk/drag-drop/overview#restricting-movement-along-an-axis

Into overview documentation, `lockAxis` on cdkDropList should be `cdkDropListLockAxis`, as rightfully stated into API tab.
`lockAxis` won't work.

#### What is the current behavior?
Wrong property name is displayed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.2.0

**Comment by crisbeto** [comment]
We've had a PR to fix it for a while, but the CLA was never signed so we can't merge it. https://github.com/angular/material2/pull/13802

**Comment by IlCallo** [comment]
Can I just redo the PR myself with GitHub GUI? Or is there some kind of legal stuff preventing others to do it once someone else does it?

**Comment by crisbeto** [comment]
You're free to do it yourself. The only the is that the CLA needs to be signed before we can merge it.
