### ISSUE TITLE
Angular Material Date Picker to show 2 months dates instead of 1 month dates

### ISSUE THREAD

**Issue by sriharibalgam** [angular/material2#14586]
#### feature request, or proposal:
<img width="608" alt="screen shot 2018-12-20 at 11 24 14 am" src="https://user-images.githubusercontent.com/8267535/50266532-eefa1000-0449-11e9-8e0d-dfa3c7e4c247.png">

#### What is the expected behavior?
The Date picker should show 2 months dates, There should be arrows on each side. On click of which the next month should be added.
For Example:

If i am opening date picker and its showing November and December Months now. On click of arrow beside December. Now it should show December and January months.

#### What is the current behavior?
It shows only one month dates on click of arrow next month is displayed.

#### What are the steps to reproduce?
The Request Date Picker format is available in this link 👍 http://fragaria.github.io/angular-daterangepicker/
The current behaviour date picker is available in this link: https://material.angular.io/components/datepicker/overview

#### What is the use-case or motivation for changing an existing behavior?
bootstrap, and other has the same but it doesnt have in angular material.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular : 2 and above
Angular Material which is compatible with angular 6.

**Comment by WonderfulNature** [comment]
Even am looking for the same behaviour.Thanks for the posting this.

**Comment by jelbourn** [comment]
This is not a pattern we plan to support.
