### ISSUE TITLE
cdk-virtual-scroll-viewport usage with angular/flex-layout

### ISSUE THREAD

**Issue by maku** [angular/material2#14587]
I would like to use virtual scrolling with flexlayout - e. g. the following code should work with virtual scrolling:

```
 <div fxLayout="row wrap" fxLayoutAlign="start center">
      <div *ngFor="let size of fixedSizeData; let i = index" [style.height.px]="size">
        <div style="border: 1px dashed; padding: 6px;" [style.height.px]="size - 20">
          Item #{{i}} - ({{size}}px)
        </div>
      </div>
  </div>

```
I made a little demo: https://stackblitz.com/edit/angular-tikbvh

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
