### ISSUE TITLE
WARNING export 'STEPPER_GLOBAL_OPTIONS' was not found in '@angular/cdk/stepper'

### ISSUE THREAD

**Issue by glur4k** [angular/material2#14593]
#### What is the expected behavior?
Compilation of the app shows no warnings.

#### What is the current behavior?
After the update to v7.2.0 there is a Warning while compilation:
```
WARNING in ./node_modules/@angular/material/esm5/stepper.es5.js 294:83-105
"export 'STEPPER_GLOBAL_OPTIONS' was not found in '@angular/cdk/stepper'
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
"dependencies": {
    "@angular/animations": "^7.1.2",
    "@angular/cdk": "^7.1.1",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/material": "^7.2.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^6.1.2",
    "@ngrx/router-store": "^6.1.2",
    "@ngrx/store": "^6.1.2",
    "@ngrx/store-devtools": "^6.1.2",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "bootstrap": "^4.1.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "jwt-decode": "^2.2.0",
    "moment": "^2.22.2",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.11.0",
    "@angular/cli": "~7.1.2",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
```

#### Is there anything else we should know?
Version 7.1.2 didn't show this warning.

**Comment by devversion** [comment]
@glur4k It looks like you didn't update the Angular CDK. Please update the CDK to `7.2.0` and see if that fixes it.

If that didn't fix it, please post here again, so that I can have another look.

**Comment by AzeredoDeveloper** [comment]
Hi!

I have some issue, can help me?
my package:
`  "dependencies": {
    "@angular/animations": "6.0.4",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "6.0.4",
    "@angular/compiler": "6.0.4",
    "@angular/core": "6.0.4",
    "@angular/forms": "6.0.4",
    "@angular/http": "6.0.4",
    "@angular/material": "^6.4.7",
    "@angular/material-moment-adapter": "^6.4.2",
    "@angular/platform-browser": "6.0.4",
    "@angular/platform-browser-dynamic": "6.0.4",
    "@angular/router": "6.0.4",
    "@mongeral/componentes-authentication": "^1.1.0",
    "@mongeral/componentes-communication": "^1.0.1",
    "@mongeral/componentes-icommunication": "^1.0.0",
    "@mongeral/componentes-insights": "^1.0.1",
    "@mongeral/componentes-ui": "^1.8.0",
    "bootstrap": "^4.1.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "deep-equal": "^1.0.1",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.11",
    "material-icons": "^0.2.3",
    "moment": "^2.23.0",
    "ngx-toastr": "^9.1.1",
    "normalize.css": "^8.0.0",
    "rhea": "^0.3.4",
    "rxjs": "6.3.3",
    "vanilla-masker": "^1.2.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.3",
    "@angular/cli": "6.0.8",
    "@angular/compiler-cli": "6.0.4",
    "@angular/language-service": "6.0.4",
    "@types/applicationinsights-js": "^1.0.7",
    "@types/chance": "^1.0.1",
    "@types/jest": "^22.2.3",
    "@types/node": "^6.0.113",
    "chance": "^1.0.16",
    "codelyzer": "~4.2.1",
    "husky": "^1.0.0-rc.1",
    "jest": "^22.4.3",
    "jest-junit": "^3.6.0",
    "jest-localstorage-mock": "^2.2.0",
    "jest-preset-angular": "^5.2.1",
    "ng-packagr": "^3.0.1",
    "protractor": "~5.3.0",
    "rxjs-compat": "^6.2.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "tslint-eslint-rules": "^5.1.0",
    "typescript": "2.7.2"
  }`

**Comment by deepakpreman** [comment]
@AzeredoDeveloper did you fixed it. without updating cdk version (^6.4.7)
