### ISSUE TITLE
Drag and drop previews do not show the correct value within a select element

### ISSUE THREAD

**Issue by Zak-C** [angular/material2#14591]
#### What is the expected behavior?
While an item containing a select element is being dragged, the preview should display the correct selected value within the select element.

#### What is the current behavior?
While an item containing a select element is being dragged, the preview displays the select element, with the value set to the default value. Once the item has been dropped, the value is then displayed correctly.

#### What are the steps to reproduce?
In the following StackBlitz example, change one of the select options to anything other than the default 'Please select an extra...' option. Now when you drag the amended item, note how the select element has been reset to 'Please select an extra...' within the preview. Once the element has been dropped, the value is displayed correctly.

https://angular-cdqlup.stackblitz.io

**Comment by crisbeto** [comment]
This is definitely a valid issue, but I don't think we can do much about it. We use `cloneNode` to create the preview which won't transfer the select's value, [unless its set as an attribute](https://stackoverflow.com/questions/44983149/javascript-clone-node-is-not-copying-all-values-from-cloned-to-new-object). There are probably some more edge cases like this one, which would be difficult/expensive to handle.
