### ISSUE TITLE
Use material theme colors as typescript variables

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#14592]
#### Please describe the feature you would like to request.

In some cases and especially when building a dashboard kind of app, we want to set the theme colors based on specific event like giving the user the option to choose the colors, or choose from material colors to define his own custom theme.

Currently we can only define pre-built themes for him, which all have to be loaded on app start and the user has very limited options to choose from.

Styling our components is a terrible DX because of the fanatic way of styling

```scss
@import '~@angular/material/theming';

$footer-bg: mat-color(mat-palette($mat-blue));
$note-bg:  mat-color(mat-palette($mat-cyan), 50);
$note-color: mat-color(mat-palette($mat-cyan));
$dialog-bg: mat-color(mat-palette($mat-purple));
```

And then in each component we need to repeat the imports

```scss
@import '../../assets/styles/variables';

:host {
   color: $note-bg;
}
```

There is kind of a **BLOCK** between our code logic and the styles, weakens our control over the app and eradicates the idea of style binding.

We can take Angular Flex-layout as an example of how it changed the old-fashioned way to the Angular way of things.

I am wondering why can't we use material theme colors as typescript variables?

**Example:**

```ts
import { red, purple } from '@angular/material/colors';

const primary = red[500]; // #F44336
const accent = purple['A200']; // #E040FB
const accent2 = purple.A200; // #E040FB (alternative method)
```
```ts
import { createMaterialTheme } from '@angular/material/styles';
import { purple } from '@angular/material/colors';

const theme = createMaterialTheme ({
  palette: {
    primary: purple,
    secondary: {
      main: '#f44336',
    },
  },
});
```
#### What is the use-case or motivation for this proposal?

Check how cool is material UI color system https://material-ui.com/style/color/#color-system

#### Is there anything else we should know?

Happy new year

**Comment by jelbourn** [comment]
For now we have no plans to expose any theming in the JavaScript space. We're exceptionally mindful of payload size in this regard, and we believe that having any kind of theming mechanisms in the JavaScript would have a negative impact on that.

**Comment by MurhafSousli** [comment]
> having any kind of theming mechanisms in the JavaScript would have a negative impact on that.

Material-UI is pretty popular, their JS solution does not seem to cause a payload size issue.

I don't have a deep understanding of how material theme works, but I think about a CSS variables solution and material color palettes written in JS that can be imported, tree-shaking might be helpful here.

Setting the theme would be a matter of calling `body.setProperty('style', serializedCssVariables)`, but you know better..
