### ISSUE TITLE
Custom Theme issue

### ISSUE THREAD

**Issue by vapits** [angular/material2#1461]
#### Bug, feature request, or proposal:
Bug? Feature request?

#### What is the expected behavior?
Following this:
https://github.com/angular/material2/blob/master/docs/theming.md#defining-a-custom-theme
I should be able to introduce a custom the in my project.

Btw current themes (coming with the lib) are working fine. I'm only getting this error with custom themes.

#### What is the current behavior?
On the compile (angular-cli - webpack)
I'm getting:
```
ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/assets/styles/material-theme.sass
Module build failed:
  $color: map-get($palette, $hue);
         ^
      Argument `$map` of `map-get($map, $key)` must be a map

Backtrace:
	node_modules/@angular/material/core/theming/_theming.scss:54, in function `map-get`
	node_modules/@angular/material/core/theming/_theming.scss:54, in function `md-color`
	node_modules/@angular/material/core/theming/_theming.scss:51, in function `md-color`
	node_modules/@angular/material/core/ripple/_ripple.scss:68, in mixin `md-ripple-theme`
	node_modules/@angular/material/core/_core.scss:26, in mixin `md-core-theme`
	node_modules/@angular/material/core/theming/_all-theme.scss:26, in mixin `angular-material-theme`
	stdin:23
      in /Projects/Jexia/WebApp/node_modules/@angular/material/core/theming/_theming.scss (line 54, column 11)
 @ ./src/assets/styles/material-theme.sass 4:14-185
 @ multi styles
```
#### What are the steps to reproduce?
My current setup:

My custom theme:
```sass
@import '~@angular/material/core/theming/all-theme'
@import 'variables'
@include md-core()

$primary: '#fab700'
$accent:  '#fab700'
$warn:    md-palette($md-red)

$theme: md-light-theme($primary, $accent, $warn)

@include angular-material-theme($theme)
```

My `angular-cli.json` (related part only):
```json
"styles": [
      "./assets/styles/material-theme.sass"
]
```

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: `2.0.0`
angular-cli: `1.0.0-beta.16`

**Comment by vapits** [comment]
As discuss in `gitter` it seems that the issue is that you cannot use custom colours but only choose from the palettes that are available in `_palette.scss` file in theming directory.

I'm guessing this is an issue so I'm not closing it.

**Comment by jelbourn** [comment]
Your `$primary`, `$accent`, etc. are not what the theme function is expecting. If you look at our pre-built themes as examples, you'll see that it's expecting one of the Material Design color palettes ([such as `$md-red`](https://github.com/angular/material2/blob/master/src/lib/core/theming/_palette.scss#L12)), not just a single color. If you create a map with the same structure it will work.

**Comment by guibot17** [comment]
@jelbourn It seems that I'm having the same issue, although I'm using the pre-built theme from the Material Design color palettes: $primary: md-palette($md-cyan); $accent: md-palette($md-amber); $warn: md-palette($md-red); just like in the example. But I'm getting the error. Any help would be greatly appreciated.

**Comment by guibot17** [comment]
Hey guys, based on the Backtrace of my error report, I looked at the 
`nodemodules/@angular/material/core/ripple/_ripple.scss ligne 65`
and found out this: 
`$accent: map-get($theme, accent);`
which means the function `map-get` requires a second parameter which is an accent color from the material design palette. In other word, to define the $accent palette, we need to define both the primary $md-colorname and any accent color code as such:
`$accent: md-palette($md-blue, A200, A100, A400);`

I hope this will help.

**Comment by nshahpazov** [comment]
Hey guys, did this issue got resolved. I'm having the same problem and I'm not using custom colours.

**Comment by MadUser** [comment]
I got the same issue only on prod build. dev build works fine.

**Comment by amaneer94** [comment]
same issue for me.. works fine for dev but custom classes stop working in prod build/

**Comment by flpms** [comment]
I'm getting the same error in dev.

**Comment by amaneer94** [comment]
Theme works if we run prod mode with AOT disabled.
`ng build --prod --aot=false`

**Comment by hawkrdg** [comment]
If this issue is resolved, I am still having trouble:
Win7x64
cli v1.1.3
material v2.0.0-beta.7
angular v4.0.0
node v8.1.2

.angular-cli.json:
     "styles": [
         "styles.css",
         "custom-theme.scss"
      ],

custom-theme.scss:
  @import '~@angular/material/theming';
  @include mat-core();

  $myPrimary: mat-palette($mat-cyan);
  $myAccent: mat-paletter($mat-amber, A400, A100, A700);
  $myWarn: mat-palette($mat-orange);

  $custom-theme: mat-light-theme($myPrimary, $myAccent, $myWarn);

  @include angular-material-theme($custom-theme);

just like in the guide using defined color palettes.

CLI bombs with

ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader
?{"ident":"postcss"}!./~/sass-loader/lib/loader.js?{"sourceMap":false,"precision
":8,"includePaths":[]}!./src/custom-theme.scss
Module build failed:
undefined
         ^
      Argument `$map` of `map-get($map, $key)` must be a map

So any help will be greatly appreciated...

**Comment by swprqa** [comment]
@hawkrdg 
$myAccent: mat-palette**r**($mat-amber, A400, A100, A700);

**Comment by nhducseuit** [comment]
I'm having same issue. I just tried to create a custom theme with sample on StackOverflow then ran "ng serve" to compile and see if it work. Angular material version 2.0.0-beta.8

The custom theme I tried with:
`@import '~@angular/material/_theming';

$mat-custom: (
  50: #eceff1,
  100: #cfd8dc,
  200: #b0bec5,
  300: #90a4ae,
  400: #78909c,
  500: #607d8b,
  600: #546e7a,
  700: #455a64,
  800: #37474f,
  900: #263238,
  A100: #cfd8dc,
  A200: #b0bec5,
  A400: #78909c,
  A700: #455a64,
  contrast: (
    50: $black-87-opacity,
    100: $black-87-opacity,
    200: $black-87-opacity,
    300: $black-87-opacity,
    400: white,
    500: white,
    600: $white-87-opacity,
    700: $white-87-opacity,
    800: $white-87-opacity,
    900: $white-87-opacity,
    A100: $black-87-opacity,
    A200: $black-87-opacity,
    A400: white,
    A700: $white-87-opacity,
  )
);

@include mat-core();

$my-app-primary: mat-palette($mat-custom);
$my-app-accent:  md-palette($mat-pink, A200, A100, A400);
$my-app-warn:    md-palette($mat-red);

$my-app-theme: mat-light-theme($my-app-primary, $my-app-accent, $my-app-warn);

@include angular-material-theme($my-app-theme);

.alternate-theme {
  $alternate-primary: mat-palette($mat-light-blue);
  $alternate-accent:  mat-palette($mat-yellow, 400);

  $alternate-theme: mat-light-theme($alternate-primary, $alternate-accent);

  @include angular-material-theme($alternate-theme);
}`

**Comment by swprqa** [comment]
@nhducseuit again, look for typos:
$my-app-primary: **mat**-palette($mat-custom);
$my-app-accent: **md**-palette($mat-pink, A200, A100, A400);
$my-app-warn: **md**-palette($mat-red);

**Comment by odahcam** [comment]
For anyone that is worryied about how to create these pallets, oyu can use tools like [mcg](http://mcg.mbitson.com/), [example](http://mcg.mbitson.com/#!?teste1=%23013674&teste2=%23ffcc33&este3=%2326a69a&themename=mcgtheme).

**Comment by neverlose-lv** [comment]
Make sure you write correct function!
**mat-palette** is correct
**md**-palette is wrong
mat-pa**ll**e**t**e is wrong
mat-pallete**r** is wrong

**Comment by bmoman** [comment]
Has this been resolved?  I'm getting the same error.  However, when I remove the "warn" from the mat-light theme as follows, the error no longer occurs so it appears to be an issue with the optional warn parameter

$default-theme:   mat-light-theme($default-theme-primary, $default-theme-accent);

**Comment by neverlose-lv** [comment]
make sure you write mat-palette!
mat-pallete - is not correct
it's double t, not double l

**Comment by odahcam** [comment]
It's worth to look again: https://github.com/angular/material2/issues/1461#issuecomment-369183835
