### ISSUE TITLE
Display additional custom text alongside dates in material datepicker

### ISSUE THREAD

**Issue by karthickms** [angular/material2#14624]
#### What is the expected behavior?

We have just add the custom text in all dates like below

![screenshot from 2018-12-24 19-10-05](https://user-images.githubusercontent.com/16956722/50400862-13d6e600-07b0-11e9-9d35-d922c428a2f9.png)

**Comment by vivian-hu** [comment]
@karthickms My understanding is you are asking us to add such a support as a feature request but you seem already did it yourself.  Can you clarify it a little more?
