### ISSUE TITLE
_theming.scss deprecation warnings

### ISSUE THREAD

**Issue by emreyalvac** [angular/material2#14636]
Deprecation warnings when get build

_theming.scss line 1404:

from -> @return if($font-family == null, $font-family, unquote($font-family));
to -> @return if($font-family == null, $font-family, $font-family);

**Comment by crisbeto** [comment]
I'm not getting any warnings. What version of node-sass are you using?

**Comment by emreyalvac** [comment]
4.11.0

**Comment by crisbeto** [comment]
I tried updating and testing it against our local dev app and a project generated with the CLI, but I wasn't able to. Can you post the entire warning? Also it seems like the warning is coming from something in the typography utilities, could you post your typography config?

**Comment by emreyalvac** [comment]
fixed
