### ISSUE TITLE
directives do not perform correct in Angular 7.0.0

### ISSUE THREAD

**Issue by balflare** [angular/material2#14633]
i try to use Material<7.2.0> directive <mat-card> in Angular 7.0.0

use the mat-card example:

<mat-card>Simple Card</mat-card>

and i also import the prebuild-theme

but i found that there's no class="mat-card" generated in this directive

then i append this class by my self ,but there's still lose some css style which should be generated by the

MatCard directive (selector: mat-card  export:matCard);

so my question is : is this the issue of Angular's version? should it will be alright under lower angular version?

**Comment by crisbeto** [comment]
You're supposed to use `mat-card` as an element. [There are some code samples in our documentation](https://material.angular.io/components/card/overview).
