### ISSUE TITLE
Add Multiple columns for same header on click button dynamically in mat-table angular. Is this possible in mat table

### ISSUE THREAD

**Issue by NaveenMysuru** [angular/material2#14649]
I need to create a table where rows and columns are added and removed dynamically. While adding a column I need to add a column for the same header.

Currently, the column gets added along with the header.

refernce: https://stackblitz.com/angular/gkmlpqvpbpj?file=app%2Ftable-dynamic-columns-example.ts

**Comment by andrewseguin** [comment]
Can you clarify what you are expecting to do with the table? Is this a feature request or bug? You're example seems to be working well adding and removing columns. 

Please re-open with more clarification on your goals. Thanks
