### ISSUE TITLE
Material Calendar to display 2 months dates instead of 1 month dates

### ISSUE THREAD

**Issue by karthickms** [angular/material2#14647]
#### What is the expected behavior?

We need 2 months calendar. If it is showing December and January, when we click the right arrow button now we will display January and February.

![screenshot from 2018-12-27 11-55-17](https://user-images.githubusercontent.com/16956722/50468598-c2587200-09ce-11e9-8e08-cc1e53001434.png)

#### What is the current behavior?
It shows only one month dates on click of arrow next month is displayed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I am using angular 6

**Comment by jelbourn** [comment]
This is not a feature we plan to support.
