### ISSUE TITLE
Mat-menu keyboard accessibility breaks when mat-menu-item is hidden

### ISSUE THREAD

**Issue by lokeshdaiya** [angular/material2#14653]
#### What is the expected behavior?
When hidden item is used in mat-menu then focus should not go to that item.
If hidden field is used then while navigation it should skip that item and focus on next visible item.

#### What is the current behavior?

Currently if hidden item is used in mat-menu  then user need to press Down Arrow key two times to reach on next visible item

In below example user needs to press **DOWN ARROW** two time to reach on item4 from item2.
`
<mat-menu #menu="matMenu">
  <button mat-menu-item>Item 1</button>
  <button mat-menu-item>Item 2</button>
  <button mat-menu-item style="display:none">Item 3</button>
  <button mat-menu-item>Item 4</button>
  <button mat-menu-item>Item 5</button>
</mat-menu>
`
#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-mat-menu-accessibility-issue

Open above link and follow below steps
1. Enter on menu button
2. Observe behavior on item2 when you press DOWN ARROW key, you will find you need to press key two time to reach on item4 as item3 is hidden.
 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7+

**Comment by crisbeto** [comment]
The menu's keyboard controls look at what's in the DOM, rather than what's visible since it's a lot cheaper to do so. There are a couple of different ways you can work around your issue:

1. Disable an item while it's hidden by setting the `disabled` attribute.
2. Use `ngIf` to remove the item.

Closing the issue since handling this from Material would be impractical and it can be worked around easily.

**Comment by lokeshdaiya** [comment]
@crisbeto Yes that can be done but in my use case I have to use display:none. I want to hide and show based on the classes not using ngIf.

**Comment by crisbeto** [comment]
In that case you can bind the same condition to `disabled`. E.g. `<button mat-menu-item [disabled]="someExpression" [style.display]="someExpression ? 'none' : 'block'"></button>`.
