### ISSUE TITLE
OverlayRed 'updatePositionStrategy' does not remove offsets

### ISSUE THREAD

**Issue by alexandercarls** [angular/material2#14657]
#### What is the expected behavior?
When calling `updatePositionStrategy` The previous strategy must be completely removed.

#### What is the current behavior?
The `offset` value of a position `flexibleConnectedTo` does not get removed when the position strategy gets updated.

#### What are the steps to reproduce?
https://stackblitz.com/edit/overlayref-positionstragy-bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested with Material Version 7.0.1 and 7.2.0

**Comment by crisbeto** [comment]
Thank you for the report, the issue will be fixed by #14660. Until it gets released, you can work around it by resetting the `transform` yourself through the `OverlayRef.overlayElement`.
