### ISSUE TITLE
[mat-sort] causing warning when running unit tests: WARN: 'The "longpress" event cannot be bound because Hammer.JS is not loaded and no custom loader has been specified.'

### ISSUE THREAD

**Issue by philmayfield** [angular/material2#14668]
#### What is the expected behavior?
Expect to not see a warning running a test

#### What is the current behavior?
Seeing a warning running a unit test

#### What are the steps to reproduce?
I cant seem to figuire out how to run a Jasmine test with StackBlitz, but I copied the example from the [sorting section](https://material.angular.io/components/table/overview#sorting), and created the [this unit test](https://pastebin.com/XrjSQdWz).

Which does pass, but throws the warning:

> WARN: 'The "longpress" event cannot be bound because Hammer.JS is not loaded and no custom loader has been specified.'

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1.4 (down to 7.0.0)
Material 7.2.0
Jasmine 3.3.0
Karma 3.1.4

**Comment by crisbeto** [comment]
It's because the sort header is using some gestures from Hammer.js. You should be able to work around it by providing a dummy Hammer loader:

```
providers: [{
  provide: HAMMER_LOADER,
  useValue: () => new Promise()
}]
```

**Comment by philmayfield** [comment]
That indeed worked for me, thank you very much @crisbeto!  Closing this issue.

**Comment by philmayfield** [comment]
Just another solution in case someone stumbles across this is to add hammer to the scripts arrays in your `angular.json` file.  eg `"scripts": ["node_modules/hammerjs/hammer.min.js"]`

**Comment by DanielP42** [comment]
If you use jest for testing you can import 'hammerjs' in your jest.ts file.

**Comment by AKlaus** [comment]
Adding `import 'hammerjs';` into the `test.ts` solves the problem. 
The one which appears in `angular.json` under:
```
"test": {
	"builder": "@angular-devkit/build-angular:karma",
	"options": {
		"main": "src/test.ts",
...
```

Adding HammerJs to the `scripts` section of `angular.json` (as @philmayfield suggested above) didn't help.

**Comment by geyuqiu** [comment]
@crisbeto adding the code in app.module.ts unfortunately did not solve the issue for me :(

**Comment by izerozlu** [comment]
> Adding `import 'hammerjs';` into the `test.ts` solves the problem.
> The one which appears in `angular.json` under:
> 
> ```
> "test": {
> 	"builder": "@angular-devkit/build-angular:karma",
> 	"options": {
> 		"main": "src/test.ts",
> ...
> ```
> 
> Adding HammerJs to the `scripts` section of `angular.json` (as @philmayfield suggested above) didn't help.

That precise suggestion ( from @philmayfield ) resolved my problem. That's weird.

**Comment by houh60** [comment]
I think you have to try both ways:  if it doesn't work when you import 'hammerjs' in test.ts, then try to to import import 'hammerjs' in app.module.ts.
The first way didn't work for me, but the second did.
