### ISSUE TITLE
Label is moved very close to the hint/description text

### ISSUE THREAD

**Issue by skounis** [angular/material2#14671]
#### What is the current behavior?
In the case of the `legacy` and `standard` style the label is moved very close to the hint/description text of the fields right above it. So there is no clear visual communication of their purpose, something that increases the cognitive load. 
![hint label](https://user-images.githubusercontent.com/690575/50536824-2874fe80-0b61-11e9-98ed-8197d72f761f.png)

#### What is the expected behavior?
This could be improved if we add some space after each field
![hint label-fix-1](https://user-images.githubusercontent.com/690575/50536836-46dafa00-0b61-11e9-83b6-eb93bb5c9dff.png)
![hint label-fix-2](https://user-images.githubusercontent.com/690575/50536739-28c0ca00-0b60-11e9-9d28-980ae579a19f.png)
![hint label-fix-3](https://user-images.githubusercontent.com/690575/50536740-2bbbba80-0b60-11e9-8a9d-9a86675673a9.png)

#### What are the steps to reproduce?
Visit this app and enter a name and a city. Then check how close the hint text is to the label and the button
- https://stackblitz.com/edit/ngx-formly-ui-material-label-issue

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.x
Material 7.x

**Comment by mmalerba** [comment]
We intentionally don't apply margin to the outer-most element out of the box, so that users can apply a margin that is appropriate for their use case. e.g.:

```
mat-form-field {
  margin: 10px;
}
```
