### ISSUE TITLE
Provide way to set focus target when opening dialog

### ISSUE THREAD

**Issue by tuckerjt07** [angular/material2#1468]
#### Bug, feature request, or proposal:

For dialogs with titles do not force focus onto the title cancel button (usually an X icon button in the right section of the title area). Or can we have this so that we can manually override. 
#### What is the expected behavior?

Focus the first non-button input instead
#### What is the current behavior?

The cancel button is focused.
#### What are the steps to reproduce?

Create a custom dialog with a button as the first input HTML element in the document.

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
#### What is the use-case or motivation for changing an existing behavior?

I understand the use case, especially around accessibility issues, but it would provide a better experience in this case not to have it.

**Comment by jelbourn** [comment]
The real feature needed here is the ability to set the focus target should be for dialog open.
