### ISSUE TITLE
Error Must provide a portal to attach

### ISSUE THREAD

**Issue by msegmx** [angular/material2#14694]
#### What is the expected behavior?
I'm trying to do the most basic CDK Portal example possible, but I'm not sure whether I get this error because of  a bug or not. If not, I'm not able to find the culprit and need support.

#### What is the current behavior?
When trying to attach 

```
@ViewChild(CdkPortal)
  private portal: CdkPortal;
```

to a DomPortalHost like this :

```
this.host = new DomPortalHost(
      document.querySelector('#action'),
      this.componentFactoryResolver,
      this.applicationRef,
      this.injector
    );

```
I get an error message in javascript console : "Must provide a portal to attach"

#### What are the steps to reproduce?
Here is the [Stackblitz](https://stackblitz.com/edit/angular-9vwv5x).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 7.1.4
Node: 11.5.0
OS: linux x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cdk                      7.2.0
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
```

#### Is there anything else we should know?
Posted this issue on [Stackoverflow](https://stackoverflow.com/questions/53975777/angular-7-cdk-portal-error-must-provide-a-portal-to-attach) before posting here.

**Comment by crisbeto** [comment]
It's throwing the error, because the portal that you're trying to attach is undefined. It hasn't been merged yet, but you can take a look at an example that'll show up on the docs eventually that shows how to use a portal. https://github.com/angular/material2/pull/14655/files
