### ISSUE TITLE
No Success Message while Creating New project

### ISSUE THREAD

**Issue by MuhammadUsmaann** [angular/material2#1471]
#### Bug, What is the current behavior?
I was creating new project while while reading you GETTING_STARTED.md online, There is no success message after successfully creating project.
 
#### What is the expected behavior?
I was expected that there will be a success message of successfully created project.

**Comment by fxck** [comment]
What, from `ng new my-project`? Report it to the CLI repo then https://github.com/angular/angular-cli it's got nothing to do with material2.

**Comment by jelbourn** [comment]
@MuhammadUsmaann wrong repo.
