### ISSUE TITLE
Icons thumb_up_alt and thumb_up_down do not display an outlined icon but a filled one.

### ISSUE THREAD

**Issue by maurice85** [angular/material2#14713]
#### What is the expected behavior?
The icons should be displayed as outlined thumbs up and downs as seen on the example page
https://material.io/tools/icons/?icon=thumb_down_alt&style=outline

#### What is the current behavior?
The icon codes thumb_down_alt and thumb_up_alt show filled thumbs that are a bit smaller then the regular filled thumbs (thumb_down and up) instead.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue

The behaviour in stackblitz is different as opposed to the behaviour in edge en Chrome. In the 2 browsers the outlined icons are displayed as filled icons on a white background, in stackblitz they become invisible. Only when changing the background to black are they visible.

I would like the icons to appear the same way as depicted on the icons example page of material.io

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular material version 6.4.1
Angular cli 6.2.8
typescript 2.9.2
Windows 10: 
Microsoft Edge 42.17134.1.0
Chrome version: 71.0.3578.98

**Comment by crisbeto** [comment]
The icons aren't maintained in this repo. You can post an issue here https://github.com/material-components.
