### ISSUE TITLE
Invalid text color at _theming.scss

### ISSUE THREAD

**Issue by Shehab-Eltawel** [angular/material2#14735]
#### What is the expected behavior?
Text color should be white for components such as mat-button or mat-tab-group when using $mat-green or $mat-light-green theme.

#### What is the current behavior?
the text color is black when using $mat-green / $mat-light-green as my primary color which is against Material guidelines.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.
Angular Material 7.2.0

#### Is there anything else we should know?
I din any customization and the CSS rule which cause this  is written at node_modules in _theming.scss file. I want to know why the team decided that greens should have black color!

**Comment by willshowell** [comment]
The color palettes are based on the 2014 Material Design palettes as you can see here: https://material.io/design/color/the-color-system.html#tools-for-picking-colors

The colors and contrasts are defined here: 

https://github.com/angular/material2/blob/0fbe6dde8c17332fcb421f37c8f22f3b0d31a2a4/src/lib/core/theming/_palette.scss#L336-L400

**Comment by Shehab-Eltawel** [comment]
Thank you.
