### ISSUE TITLE
Angular Material Auto Complete lags 10 sec with 30K objects

### ISSUE THREAD

**Issue by Raulkg** [angular/material2#14738]
#### What is the expected behavior?
The auto complete should be smooth to display any number of elements . any other library can handle(Ex: snechajs,highcharts) or pure vanilla can handle atleast 50K+ objects

#### What is the current behavior?
lags and crashes website when loading 30k_+ objects for auto complete 

#### What are the steps to reproduce?
Create a auto complete . fetch an observable with atleast 30K+ items .
type the word with debounce time 500 ms and remove each word.
The website crashes

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "^7.0.4",
    "@angular/cdk": "^7.0.4",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "^7.0.4",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/material": "^7.0.4",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/pwa": "^0.10.6",
    "@angular/router": "~7.0.0",
    "@angular/service-worker": "~7.0.0",
    "typescript": "~3.1.6",
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.6",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",

#### Is there anything else we should know?
I have read other issues similar to this . The best answer i saw was ..this is end user managed this not related to angular material .  I am willing to learn how to handle this and get a performant version of the material auto complete . How can i detach unusable watchers from the list of large objects. I am looking for a viable solution. If this is a dumb question please point me to location where to start solving this.

**Comment by manklu** [comment]
You should first provide a complete Stackblitz sample. Maybe you attract someone's interest.

**Comment by andrewseguin** [comment]
Loading 30,000 items into the DOM is not recommended and is likely not what the user needs. I don't suspect we will be able to help improve the latency in loading so many objects.

**Comment by Raulkg** [comment]
Yes, i realized that. I am then planning to implement virtual scroll for auto complete as a custom component. If you have a better solution please comment. Thank you
