### ISSUE TITLE
Ability to add commas to Paginator results, when results are more than 999+

### ISSUE THREAD

**Issue by benhaynie** [angular/material2#14730]
#### Please describe the feature you would like to request.
Not sure if this is a bug, but if I have 1,234 pages of results, the paginator control shows that as 1 of 1234.
It would be nice if I could specify localization, or have control to some how format the total number of pages as 1,234 (with the comma in there)

#### What is the use-case or motivation for this proposal?
Picky customer wants numbers formatted with thousands separators.

**Comment by crisbeto** [comment]
You can do this already by providing a new value for `MatPaginatorIntl` and customizing the `getRangeLabel` function.

**Comment by benhaynie** [comment]
I wanted to say thank you for pointing this out.  I didn't see this option in the API documentation I was looking for.  Your knowledge of the framework is much appreciated, thank you.
