### ISSUE TITLE
MatDialog - Click event is fired when the dialog is opening

### ISSUE THREAD

**Issue by essoShopbox** [angular/material2#14744]
#### What is the expected behavior?
the click event not fired when opening the dialog

#### What is the current behavior?
the click event is fired when opening a dialog

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-idrvwl

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material v7.2.0

#### Is there anything else we should know?

**Comment by manklu** [comment]
@essoShopbox
In addition, click events bubbles up until you stop them. Something like

```html
<button mat-raised-button (click)="openDialog();$event.stopPropagation()">Pick one</button>
```
