### ISSUE TITLE
Angular data table with nested array 

### ISSUE THREAD

**Issue by yeshwanthmn** [angular/material2#14746]
#### Bug, feature request, or proposal:
How to display data table with nested array in material table.  

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by billbarni** [comment]
You provided no example.
You provided no expected behavior.
You did not show what a "nested array" really means.
You attatched an empty stackblitz starter.

Really hard to respond to that or even try to help.
