### ISSUE TITLE
Polyfills should work the same in dev and production builds

### ISSUE THREAD

**Issue by masterfix** [angular/material2#14743]
#### What is the expected behavior?
Polyfills should work the same in dev and production builds

#### What is the current behavior?
We use angular material for displaying a simple dialog. The problem occurs only in Internet Explorer 11 in combination with the core-js/es6/weak-map polyfill. First we forgot to include this polyfill but in dev mode the dialog still worked. But when we tested the production build the dialog did not open and throwed an error. Now it's clear for us that it should fail because of the missing polyfill. But why is it working in dev mode without the polyfill?

#### What are the steps to reproduce?
At the moment we can not provide a stackblitz example because you cannot set dev/prod mode.
We have a sample cli based project to show the issue here: https://github.com/olmero/matdialog-ie11.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1 (project generated with cli)

**Comment by crisbeto** [comment]
Material doesn't really do anything when it comes to polyfills, it just assumes that the functionality will be there. It's more likely that the CLI is including a different set of files in development vs production mode.
