### ISSUE TITLE
MatSelect combobox wrong position

### ISSUE THREAD

**Issue by cTahirih** [angular/material2#14755]
#### What is the expected behavior?
* It is expected that to open the combobox this always opens in the center, below or on the selected field depending on the space it is.

![5eb22204-8f9d-47a9-aef3-1a75bd338456](https://user-images.githubusercontent.com/32286691/50849261-7bf70180-1344-11e9-9e60-260af9798dee.jpg)

#### What is the current behavior?

![a8fd9894-9043-440b-8cd3-c3d3f64b177d](https://user-images.githubusercontent.com/32286691/50849272-844f3c80-1344-11e9-8171-7678fc3cbd60.jpg)

* Occasionally you can see that the combobox opens in a higher position than the select component position and this makes it visually not look good.

#### What are the steps to reproduce?
There is no determined steps to reproduce this bug because is random so we just can atach a screenshot:

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0
TS 2.4.2
Material 5.0.4
Chrome V70

#### Is there anything else we should know?
This bug is random

**Comment by andrewseguin** [comment]
Without a reproducible case, it will be very difficult for us to understand what is causing your issue. Please re-open if you can provide something we can investigate with. Thanks
