### ISSUE TITLE
Radiobutton doesn't focus when selecting the associated label

### ISSUE THREAD

**Issue by juristr** [angular/material2#14753]
#### What is the expected behavior?

Clicking the radiobutton in a radio button list should select the radio button accordingly.

#### What is the current behavior?

Clicking the radiobutton in a radio button list does activate the clicked radio button in case when I select the label text. The ripple effect of the click however triggers properly

![material-radiobuttonlist-bug](https://user-images.githubusercontent.com/542458/50844176-7a403480-136a-11e9-8b30-b784038d7dbb.gif)

#### What are the steps to reproduce?

Can be reproduced directly on the material docs site: https://material.angular.io/components/radio/overview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

latest of both, tried in the docs site.

#### Is there anything else we should know?

Happy to provide a PR with some guidance where the issue could be.

**Comment by Suresh918** [comment]
Not able to reproduce. It's working as expected when I checked now at [](https://material.angular.io/components/radio/overview)

**Comment by andrewseguin** [comment]
Seems to be working on our end as well. Not sure what caused the issue but if you can reproduce, feel free to re-open

**Comment by juristr** [comment]
@andrewseguin 🤔 hmm...I still reproduce it. You have to select the label and click on that label, not the radio button itself. Reproduced in Chrome and on MacOS.

Here's a short video where I reproduce it: https://youtu.be/oR-LRzvlfRA

**Comment by andrewseguin** [comment]
Thanks for the video, that helps a lot. Definitely looks like a bug, albeit a bit low priority but something we ought to get fixed.

**Comment by swseverance** [comment]
I'm able to reproduce in Chrome, but not in Safari on MacOS. The issue appears to be that although a `click` event does get dispatched to the `label` element, a generated click event does not appear to be dispatched to the `input` element. I'm unable to explain why that is.

However, the following changes seem to resolve the issue:

radio.html
```html
<label [attr.for]="inputId" class="mat-radio-label" #label (click)="_onLabelClick()">
```
radio.ts
```ts
_onLabelClick() {
  this._inputElement.nativeElement.click();
}
```

I can submit a PR with these changes but as of now I'm unable to provide an accompanying unit test that replicates the behavior we're seeing.
