### ISSUE TITLE
Can't change height of toolbar-row. Fixed at 64px;

### ISSUE THREAD

**Issue by dfarago** [angular/material2#1477]
Trying to set the toolbar-row height to 50px; Setting the toolbar height works fine;

**Comment by kara** [comment]
It sounds like you're not turning ViewEncapsulation off in the component that uses the toolbar. If you do, the styles should work as expected.

```ts
@Component({
   ...
   encapsulation: ViewEncapsulation.None
})
```

**Comment by moravcik** [comment]
@kara, this is not very nice and maintainable solution for all components, which I need to customize material styles for, with `ViewEncapsulation.None` encapsulaton and to force styles with `!important` suffix. It looks like CSS hacking to me.

It would be much better and cleaner solution to use toolbar SCSS variables, which have the !default moditier by the way, so they expect to be overwritten from outside:

    $mat-toolbar-height-desktop: 64px !default;
    $mat-toolbar-height-mobile-portrait: 56px !default;
    $mat-toolbar-height-mobile-landscape: 48px !default;

But unfortunately the SCSS files for components are not accessible anymore, which is a pity and I would say a showstopper for some more serious customization.

**Comment by Selast** [comment]
Hello guys ! I'm having the same issue and the solution @kara gave isn't really working with the `heigth`. Comment if something was founded.
