### ISSUE TITLE
Dialog does not restore focus to the element on which it was called

### ISSUE THREAD

**Issue by mSutkevicius** [angular/material2#14782]
#### What is the expected behavior?
When I close dialog it should return focus to the element on which the dialog was called.

#### What is the current behavior?
After transitioning from angular/material 6.2.1 to 7.1.0 it stopped working. If I go back to v6.2.1 it works fine/as expected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Currently I am on 7.1.0

#### Is there anything else we should know?
I've tried bumping to the latest version, but it's not working as expected either.

**Comment by andrewseguin** [comment]
The [overview example](https://stackblitz.com/angular/rkkngoqqlod?file=app%2Fdialog-overview-example.ts) from the docs show that this behavior is still working. Please re-open this issue if you can provide a reproduction of the problem, so that we can investigate
