### ISSUE TITLE
Pagination, Sorting, Filtering on Div

### ISSUE THREAD

**Issue by lashisu** [angular/material2#14794]
#### Please describe the feature you would like to request.
I think it would be best to have the same feature of mat-table for a div. Where user can sort, filter and paginate the data.

#### What is the use-case or motivation for this proposal?
It will be used in list view instead of looping through TABLE, TR, TD.

#### Is there anything else we should know?
A lot of people will be benefitted from this feature.

**Comment by crisbeto** [comment]
This is possible already. See the `Tables with display: flex` example in the docs: https://material.angular.io/components/table/overview#tables-with-code-display-flex-code-
