### ISSUE TITLE
Template Reference Variable cannot be accessed inside conditionally rendered element

### ISSUE THREAD

**Issue by FreeVote** [angular/material2#14805]
#### What is the expected behavior?
The template reference variable should always be available

#### What is the current behavior?
When a Template Variable is defined inside an element which has an ngIf directive, the Template Reference is undefined

#### What are the steps to reproduce?
- create a div with *ngIf
- Inside that div add a template variable to an input element
- that template variable is undefined

https://stackblitz.com/edit/free-vote-angular-material-forms-required

Even when the ngIf on the containing div is set to 'true', the template variable tvPassword is undefined.

Cannot read property 'touched' of undefined

Remove the ngIf on the div entirely and all is OK

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/material 7.2.1

**Comment by mmalerba** [comment]
I don't think this has anything to do with Angular Material. It looks like an issue with Angular itself, I can reproduce it even after removing Angular Material from your demo: https://stackblitz.com/edit/free-vote-angular-material-forms-required-c1sbvg?file=src/app/app.component.html
