### ISSUE TITLE
when I try install material2, I have error connected with webpack

### ISSUE THREAD

**Issue by rostixman** [angular/material2#1480]
#### Bug?:

when I try install material2, I have error:

> npm ERR! Darwin 16.0.0
> npm ERR! argv "/usr/local/bin/node" "/Users/username/projects/ng-project/node_modules/.bin/npm" "install" "--save" "@angular/material"
> npm ERR! node v6.7.0
> npm ERR! npm  v2.14.21
> npm ERR! code EPEERINVALID
> 
> npm ERR! peerinvalid The package webpack@2.1.0-beta.25 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer webpack-dev-middleware@1.8.4 wants webpack@1 || ^2.1.0-beta
> npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
> npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
> npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
> npm ERR! peerinvalid Peer string-replace-loader@1.0.5 wants webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta
> npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.3 wants webpack@^2.1.0-beta
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/username/projects/ng-project/npm-debug.log
> 

#### Steps to reproduce:

npm install -g angular-cli
ng new ng-project
cd ng-project 
npm install --save @angular/material

#### Versions of Angular, OS, node, npm
1) angular 2
2) mac os Sierra
3) node v6.7.0
4) npm  v2.14.21

**Comment by jmcgoldrick** [comment]
You should be able to safely ignore those `peerinvalid` errors (i.e even if you see them, everything should still work so just don't worry about them), but run `npm install -g npm` because 2.14.21 is very out of date.

**Comment by rostixman** [comment]
I have npm v 3.10.8 on my machine outside folder with angular cli project. But when I inside folder with angular cli project, npm v shows me version 2.14

**Comment by jelbourn** [comment]
This isn't a problem with material; it is due to other packages in your environment.

**Comment by rostixman** [comment]
when i did what written in readme file (https://github.com/angular/material2/blob/master/GETTING_STARTED.md install angular-cli and material) - result is error, why this is not a bug?
