### ISSUE TITLE
[Tabs] Add icon support for tabs

### ISSUE THREAD

**Issue by RaulRG** [angular/material2#1481]
#### Bug, feature request, or proposal:

Please add icon support for tabs
#### What is the expected behavior?

It should be possible to add icons to the tabs as specified in the Material Design Guidelines
#### What is the current behavior?

I managed to add icons to the tabs, but then I cannot display the text. I used the template as this:

```
          <template md-tab-label>
            <md-icon>information</md-icon>
            <p>Instances</p>
          </template>
```

This displays the icon as expected (centered in the tab - great!), but the tab does not grow to display the text below.
#### What are the steps to reproduce?

Create a tab component and try to add icon AND text that should be displayed. The icon centered above and then the text below.
#### What is the use-case or motivation for changing an existing behavior?

To be able to create web apps that compliant with the material design guidelines.
#### Which versions of Angular, Material, OS, browsers are affected?

All

**Comment by thw0rted** [comment]
The layout for images + text is described [in this section of the spec](https://material.io/guidelines/components/tabs.html#tabs-specs).

**Comment by jelbourn** [comment]
AFAIK this should work today

**Comment by TheRedD0t** [comment]
@jelbourn
> AFAIK this should work today

 **Yes**, you can use text with an icon today already, but **no**, this doesn't work well(...you can't even bring the text after the icon to a new line, because of the `display: inline-flex`...), at least not without heavily manipulating the CSS, if you want a tab that does match with the specs.

**Comment by thw0rted** [comment]
@jelbourn if this is a recent change, then the docs need an example of using an image in a tab in a spec-compliant way.

**Comment by philip-firstorder** [comment]
Use this code in your styles.scss to have your icon above the label.

<img width="479" alt="Screenshot 2019-03-21 at 16 05 29" src="https://user-images.githubusercontent.com/30979663/54761863-3b90eb00-4bf3-11e9-8bc7-501dc2705c64.png">



```
// mat-tab-label corrections
// https://github.com/angular/material2/issues/1350
// https://github.com/angular/material2/issues/1481
.mat-tab-label {
  height: auto !important;
  max-width: 360px;
  min-width: 90px !important;
  .mat-tab-label-content {
    display: flex;
    flex-direction: column;
    padding: 12px 0;
    p {
      margin: 4px 0;
    }
  }
}
```
