### ISSUE TITLE
Invalid theming import on guide

### ISSUE THREAD

**Issue by mrtcmn** [angular/material2#14818]
#### What is the expected behavior?
Wrong or deprecated import path on theming guide:

Must be like this.
`@import '~@angular/material/_theming.scss';`

#### What is the current behavior?
Import of current example is: 
`@import '~@angular/material/theming';`

#### What are the steps to reproduce?
https://material.angular.io/guide/theming

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I detected this problem on;
Angular Material 7.2.1

**Comment by M07amed-a7med** [comment]
@mrtcmn have you tried any work around cause I am facing the same?

**Comment by mrtcmn** [comment]
@M07amed-a7med  I'm using SASS, and this import works for me.

`@import '~@angular/material/_theming.scss'`

**Comment by Splaktar** [comment]
What error message are you getting and what tool is generating it?

This import path works fine for me ([one example](https://github.com/angular-hispano/angular-hispano/blob/c324c4bcb5170bbcfc5f6732c1702976af9335b8/projects/web/src/styles.scss#L3) using `7.3.6`).

**Comment by mrtcmn** [comment]
Hi, im on 7.3.7 now. And i have no error. Maybe problem was on 7.2.1. I can't say which one is. But seems problem doesn't exisist now. This issue must be closed. Thanks for support!
