### ISSUE TITLE
This is moving incredibly slow?  Is this ran by google? If so why is this not complete?  

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#1482]
Material is great why is this taking so long?

**Comment by vincentpalita** [comment]
Please read the readme, and search in other issues as this kind of questions have already been addressed by the Material team.
In my opinion you should never ask that type of question for a project that you do not invest your time in and moreover that is completely free of use as it is open-source.

**Comment by CoreyGrant** [comment]
There are a lot of components, written in a bleeding edge framework (which has changed several times over just the past few months), and the requirements are very strict. There is a huge amount of work to be done, and not all that many people to do it.

There are plenty of changes which are marked as safe for community contribution, but even then the work done has to be reviewed (most likely involving several stages of back and forth), that is if the solution is high enough quality to begin with.

**Comment by JanStureNielsen** [comment]
@xtianus79 -- the GitHub issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.

**Comment by xtianus79** [comment]
Im sorry but I am not going to apologize for google doing something awesome on one hand and completely incomplete on the other hand.  It is not a criticism but a reality of the situation... thus I feel the criticism is fair.

**Comment by xtianus79** [comment]
@CoreyGrant Hey how's it going?  Just wondering if material 2 is ever going to be completed prior to Angular 4 being released.

**Comment by JanStureNielsen** [comment]
@xtianus79 -- please don't comment on closed issues. Angular Material supports Angular 4 -- see https://github.com/angular/material2/releases/tag/2.0.0-beta.3 for details.
