### ISSUE TITLE
Button Toggle has same color of tab-highlighted and selected

### ISSUE THREAD

**Issue by nickwinger** [angular/material2#14839]
#### What is the expected behavior?
In my opinion when i tab through the button toggle group via keyboard it should not have the same color as if it were selected but the color the mouse hover has

#### What is the current behavior?
When i tab through the button toggle group with the keyboard and have already selected an item the user cannot distinguish which one is the currently selected as they have the same color.

#### What are the steps to reproduce?
You can look it up on the material page itself:
https://material.angular.io/components/button-toggle/overview
Select italic and the press the tab keyboard key. they have the same color now...
which one is the current selected one ?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
current, like on the material homepage

#### Is there anything else we should know?
I'm not a ux designer, i'm interested in other opinions, but my team thinks that the tab highlight should have the lighter color as the mouse hover color

**Comment by josephperrott** [comment]
Unfortunately this is something that is defined by the Material Spec.  As such it is not something that we will change, unless the Material Spec changes.
