### ISSUE TITLE
[drag-drop] Allow to disable sorting within a CdkDropList

### ISSUE THREAD

**Issue by yarinr** [angular/material2#14838]
#### Please describe the feature you would like to request.
I want to be able to disable sorting within a CdkDropList. That is, I want to be able to drag items from a CdkDropList to it's connected CdkDropList, while not allowing items within the source CdkDropList to be swapped (sorted).

I guess it would be used as an input of CdkDropList, something like this: `
@Input('cdkDropListSortable')
sortable: boolean
`, that when true will disable sorting within the drop list.

Also, if there's a way to achieve this behavior using the current API, I would love to hear about that. Searching online I found a few people asking the same question (https://stackoverflow.com/questions/53380336/how-to-disable-sort-in-a-cdkdroplist-using-angular-cdk-v7-0-0), but none received a relevant answer.

Thanks!

**Comment by crisbeto** [comment]
[This sounds very close to the `cdkDropListDisabled` input.](https://material.angular.io/cdk/drag-drop/api#CdkDropList) Does it do what you need?

**Comment by creadicted** [comment]
This would disable the dragging completely. I think yarinr has the same issue I have. I want to drag something out of a list. And I use a clone method to do that. What I do not want is that, while i drag my object over the list the list will be also sorted. Does this make sense?

**Comment by yarinr** [comment]
@creadicted Yes, that's exactly what I mean.
@crisbeto See the reply by @creadicted - `cdkDropListDisabled` does not achieve the behavior I'm talking about.

Thank you both for your input!

**Comment by creadicted** [comment]
I saw request in multiple locations. In the past i played around with other d&d components. Like https://github.com/bevacqua/dragula . They expose a function that allows to manipulate what to do when hovering of a 'bucket'. So you could intercept the sorting behavior. A simple option would be easier.

**Comment by fmavdb** [comment]
I too want to just disable the sorting and only allow dragging between lists and on items. An usecase I'm working on is for example an already sorted file/folder list. I want to be able to drag and drop files on folders, not order them.

**Comment by maknapp** [comment]
This issue is similar to #13906

**Comment by MrDywar** [comment]
> I saw request in multiple locations. In the past I played around with other d&d components. Like https://github.com/bevacqua/dragula . They expose a function that allows to manipulate what to do when hovering over a 'bucket'. So you could intercept the sorting behavior. A simple option would be easier.
> 
> For a quick you can just have an `cdkDropList `around each `cdkDrag `object. But that is definitely not a nice solution.

Alternatively you can just override css transform on you cdkDrag, by setting it to "transform: none !important".
The cdkDropList still changes transform, but it has no effects.

May be it will break some animations, but drop event works perfectrly with current and previouse indexes.

**Comment by ceyhunnabiyev** [comment]
I have one case, too. If folder and files in the same CdkDropList, what can I do. `[cdkDropListSortingDisabled]` option doesn't support this.

**Comment by DenisDremkov** [comment]
You can just set above your source list that you want to disable copy of source list without CDK drag attributes after  dragStarted event, it works fine, if you think that it bad decision write - why?  trigger for appear of fake block you can use - dragStarted(event: CdkDragStart) {  this.isDragging = true; }

**Comment by LordMidi** [comment]
> I have one case, too. If folder and files in the same CdkDropList, what can I do. `[cdkDropListSortingDisabled]` option doesn't support this.

Looking into the branches/tags this will be included in the release of version 8. It's allready in the RCs I think. But this need also an update to Angular 8. Very sad that it hasn't been released in a v7.x version :-(

**Comment by ceyhunnabiyev** [comment]
> You can just set above your source list that you want to disable copy of source list without CDK drag attributes after dragStarted event, it works fine, if you think that it bad decision write - why? trigger for appear of fake block you can use - dragStarted(event: CdkDragStart) { this.isDragging = true; }

I don't need connected lists. This is for connected lists.

**Comment by ceyhunnabiyev** [comment]
> Looking into the branches/tags this will be included in the release of version 8 of Angular Material. It's allready in the RCs I think. But this requires an update to Angular 8. Very sad that it hasn't been released in a v7.x version :-(

I think, it won't be released for angular 7.
