### ISSUE TITLE
<Border-radius> for <md-raised-button> theming

### ISSUE THREAD

**Issue by krigton** [angular/material2#1484]
#### Bug, feature request, or proposal:
Not sure if this is the case for material 1, but I'm trying to have different rounding for the md-raised-buttons for various themes. The rounding takes place inline on the component. I cannot see a way how to do this other then create a new component based on`<md-button>` or add a rule which overrides the `[md-button]` selector. Neither of these solutions looks to be a good one.

#### What is the expected behavior?
It would be nice to move this out to the theming. 

#### What is the current behavior?
The rounding is in the component's css, so not really possible to globaly override the border-radius for every button without changing the specificity of selector (`.name-of-theme [md-raised-button] {}`)

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

#### What is the use-case or motivation for changing an existing behavior?
Easier theming for rounding

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.0.0, material@2.0.0-alpha.9-3

#### Is there anything else we should know?
I'm very newbie with angular 2 and material design :D

**Comment by jmcgoldrick** [comment]
Hi @krigton, the spec (https://material.google.com/) is pretty clear about things like radius' on buttons etc. I'm not 100% sure but it seems to me like the `@angular/material` project is pretty intent on sticking to the spec so offering easy ways to go "off-spec" seems like it will be a low-priority.

For use-cases like yours, I either do what you suggested (encapsulate the component in a wrapper and apply a class that overrides what I want); or, even with view encapsulation **on** you can override the styles via classes so long as you are more-specific than the current selectors, (which if you use the current selector for the element plus the class you added you will be, I know.. weird but effective

**Comment by krigton** [comment]
yes, thought so, but hoped we might have this in theming I mean. 3px vs 5px should be off too much of the guidelines. I will just do something like `html [md-raised-button {...}`. thanks

**Comment by emilio-martinez** [comment]
Quick thought in regards to the specificity: using `button[md-raised-button], a[md-raised-button]` as selectors should suffice.

**Comment by krigton** [comment]
yes, better, clearer
thanks
