### ISSUE TITLE
Change displayed text when selecting an option

### ISSUE THREAD

**Issue by jmtt89** [angular/material2#14856]
#### Please describe the feature you would like to request.
Change displayed text when selecting an option

#### What is the use-case or motivation for this proposal?
If the content of the options has a complex design as an image with title and description, the selected option looks ugly

#### Is there anything else we should know?
On master branch when a option it's selected the select only call a viewValue of the option 

https://github.com/angular/material2/blob/master/src/lib/core/option/option.ts
```
  /**
   * The displayed value of the option. It is necessary to show the selected option in the
   * select's trigger.
   */
  get viewValue(): string {
    // TODO(kara): Add input property alternative for node envs.
    return (this._getHostElement().textContent || '').trim();
  }
```

https://github.com/angular/material2/blob/master/src/lib/select/select.ts
```
  /** The value displayed in the trigger. */
  get triggerValue(): string {
    if (this.empty) {
      return '';
    }

    if (this._multiple) {
      // HERE
      const selectedOptions = this._selectionModel.selected.map(option => option.viewValue);

      if (this._isRtl()) {
        selectedOptions.reverse();
      }

      // TODO(crisbeto): delimiter should be configurable for proper localization.
      return selectedOptions.join(', ');
    }

    // AND HERE
    return this._selectionModel.selected[0].viewValue;
  }
``` 

I think that its very easy to accomplish, only need to add an Input on mat-option for selected display and return it when the option was selected if option don't have define this input only show the current viewValue.

**Comment by crisbeto** [comment]
You can customize the trigger label with the `mat-select-trigger` directive. There's an example of how to use it in the docs: https://material.angular.io/components/select/overview#customizing-the-trigger-label.
