### ISSUE TITLE
cdkDrag elements should have a individual 'cdkShiftDisabled' as a counter part to 'cdkDragDisabled'

### ISSUE THREAD

**Issue by andreElrico** [angular/material2#14869]
#### Please describe the feature you would like to request.
When inside a cdkDropList and "el1"  is dragged over to "el2" a shifting/sorting animation is occurring. That's highly desirable.

So with the new feature for cdkDrag Elements. Maybe called:
@Input('cdkShiftDisabled')
disabled: boolean

The shifting animation of the passive element "el2" could be omitted. Its remains static while dragging and mouseover el2. The placeholder should stay in front of el2 until (in a vertical scenario) el1 leaves el2 in a downward direction. If el1 left el2 in the downward direction the placeholder should be below el2 and the "known" shifting/sorting animations should happen.

#### What is the use-case or motivation for this proposal?
I'm suggesting this behavior feature because this would make nested drag and drop possible with a good UX.
So let's say:
+ el1 and el2 are both in a vertical/normal cdkDropList.
+ el2 contains an own horizontal cdkDropList.

Its impossible to add el1 into the horizontal DropList because of the sorting and swiveling.

There are at least three questions about nested dnd on stackoverflow.

Best regards,
André

**Comment by crisbeto** [comment]
Looks like this is resolved by https://github.com/angular/material2/pull/15064.
