### ISSUE TITLE
feat(cdkDragDrop): A way to block the origin list during a dragging action

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#14863]
#### Please describe the feature you would like to request.

A way to disable drag-and-drop on the origin list after a dragging has started and, afterward, restore its capability after the drop action

#### What is the use-case or motivation for this proposal?

I have a bunch of lists. One of them works as a source of resources (each element represents a resource type). The other lists work as the consumers of the resources.

In the source list, each element shows the total number of available resources of the type it represents. I decrement this number whenever a resource is dragged and dropped on one of the consumer lists.

The problems is that I should be able to drag elements from/to the source. But I do not want to see a placeholder in either of these situations (despite the fact that I'd like to still be able to drag-and-drop elements from/to it):

    1 - when I am dropping an element to it, I do not want to show any placeholder
    2 - when I am dragging an element from it and hover the dragged element over it again, I do not want to see any placeholder (which seems to be the default behavior).

#### Is there anything else we should know?

I kind of worked it around by hiding the list while dragging (and showing a not draggable clone of it), and forbidding the dropping from other lists to it.

There are some possible similarities to #14539 (the item 2 above could be solved if I could set a placeholder to `none` in the drop list with some kind of `@Input()` or set a different placeholder depending on the origin of the element being dropped on it). The lists, in this use case, have different shapes.

**Comment by crisbeto** [comment]
Is this covered by https://github.com/angular/material2/pull/15064?

**Comment by julianobrasil** [comment]
Likely yes, but I'd have to take a closer look at it to be sure. Do you want me to close this one for now?

**Comment by crisbeto** [comment]
Sure, I'll close it for now and it can be reopened if that's not what you were looking for.

**Comment by julianobrasil** [comment]
@crisbeto, I was taking a look at the `cdkDropListSortingDisabled` directive. This is not exactly what I was trying to achieve when I opened this issue (right now I'm not sure if what I want is part of the expected behavior).

Supposing you are using the `cdkDropListSortingDisabled` directive, when you drag an item from the source, you left a placeholder behind, at the source list, while you're dragging. Imagine a situation where you have four instances of each item on the source list. But an instance is noticed as a number in the item instead of a real item, for example, in the item name after 'carrots', you'd have 10, indicating that you have 10 carrots at the store. When you drag a carrot item, instead of leaving a placeholder on the source, you'd leave the real item. So you'd have at the same time the dragging item and the original item visible on the source list. When you finally dropped the item on the destiny list, the number on the source list would be updated to 9 carrots. The main point is: when you're dragging... is there a way to move an item from the source without actually erasing it from the source and drop it on the destiny without necessarily add a new item there?

**Comment by crisbeto** [comment]
Can you post the same info to a new issue @julianobrasil? Leaving it in a comment here will probably get lost over time.
