### ISSUE TITLE
triggering a dialog from a menu item doesn't focus dialog properly

### ISSUE THREAD

**Issue by mtaran-google** [angular/material2#14879]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The element in the dialog that has the `cdkFocusInitial` directive should gain focus when the dialog opens. This is also how it worked as of angular/material2 5, but broke in 6.

#### What is the current behavior?
Focus returns to the menu trigger button (now hidden behind the dialog's backdrop, so not that helpful).

#### What are the steps to reproduce?
broken with angular 6: https://stackblitz.com/edit/checkbox-reactive-2zhjpp
working with angular 5: https://stackblitz.com/edit/checkbox-reactive-soumtp

#### What is the use-case or motivation for changing an existing behavior?
See above -- this is a regression.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 5+material 5 work fine, angular 6 + material 6 are broken (that's as far as I backtraced it)

#### Is there anything else we should know?
there were noticeable changes in the interim timeframe to https://github.com/angular/material2/blame/246320032404e912461bf8c39b65d6d2b92646ca/src/cdk/a11y/focus-monitor/focus-monitor.ts#L245 (which is what's called to focus the trigger)

**Comment by manklu** [comment]
Both of your samples use version 5

**Comment by mtaran-google** [comment]
this is basically a dup of #11696 and was fixed recently

**Comment by takamori** [comment]
I'd like to reopen this; it's not that we want an option, but rather that we want to fix this focus issue described to be fixed. It should be noted that the issue only occurs when `NoopAnimationsModule` is used; it does not occur when `BrowserAnimationsModule` is used. The current workaround is to disable the menu button for the duration that the dialog is open.

**Comment by Brhav** [comment]
+1 for reopening this issue
