### ISSUE TITLE
Policy on view encapsulation?

### ISSUE THREAD

**Issue by bertvh** [angular/material2#1487]
I'm trying to use material2 in an existing project using MaterializeCss. I'm encountering a lot of interference between styles: the global stylesheet has impact on the material2 components, resulting in not-so-nice styling.

I assume this could all be avoided by turning on ViewEncapsulation for the material2 components. However, this is decided by the implementer of the components. I can't seem to alter the setting from the outside.

What is the general policy on this issue? Will all Material2 components have view encapsulation set to none? Will there be a way the change this setting?

Thanks.

**Comment by jelbourn** [comment]
In general, please direct questions to other avenues and keep github issues for bugs/feature requests.

However, for this I will say that material2 components using ViewEncapsulation won't prevent outside styles from leaking _into_ material components; it only stops styles leaking _out_ of the components.
