### ISSUE TITLE
Add package-config to @angular/cdk/schematics

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/material2#14888]
#### Please describe the feature you would like to request.
Can we add material2/src/lib/schematics/ng-add/package-config.ts functions to @angular/cdk/schematics

#### What is the use-case or motivation for this proposal?
I want to use those functions in my project's schematic

**Comment by devversion** [comment]
Thanks for your issue. Actually `@angular/cdk/schematics` is only intended for our internal usage, so we won't be moving it to a location where it can be imported by others.

If you think that it would be reasonable to have some general utilities for building Angular schematics, I'm on your side with that, but I'm not sure if the Angular CDK is the proper place for that. Better would be the CLI in my opinion.

**Comment by mohammedzamakhan** [comment]
Oh, what! I am using it successfully in one of the schematics that I created this week! They are actually really helpful functions that the community can use too.
