### ISSUE TITLE
[progress-circle] show percentage in the middle of the circle

### ISSUE THREAD

**Issue by neuquino** [angular/material2#1488]
#### Bug, feature request, or proposal:

Feature request
#### What is the expected behavior?

Show the value inside the circle
#### What is the current behavior?

Does not show the percentage value
#### What are the steps to reproduce?

http://plnkr.co/edit/v0B4uU
#### What is the use-case or motivation for changing an existing behavior?

http://i.stack.imgur.com/DzNnN.png
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2+
Material 2.0.0-alpha.9
#### Is there anything else we should know?

No

**Comment by michaeljota** [comment]
Maybe just allow to print anything inside the circle, with `ng-content` only.

**Comment by michaeljota** [comment]
OK. @neuquino I manage to do a workaround with css. Just `position: absolute;` the section you want to show inside the spinner. Both must be inside a single div, and only them to be. Well, I have not tested out of my project, but I guess this should work, as the middle of the spinner is transparent.

**Comment by mackelito** [comment]
plunkr is broken

**Comment by DanjBethel** [comment]
Is anyone still working on this?

**Comment by jelbourn** [comment]
Closing this since there are no plans to add this feature.
