### ISSUE TITLE
Md-Tab-Group: Accessing the Label Content on Tab change event.

### ISSUE THREAD

**Issue by j3ddesign** [angular/material2#1489]
#### Bug, feature request, or proposal:
feature-request

While attempting to have deep-linked tabs, I was trying to get the value of the selected tab's label content, so I could in turn, change the active route (using componentless routes) - I couldn't find this on a public property at all, with the only references being at: 
`event.tab.label._attachedHost._viewContainerRef.element.nativeElement.nextSibling.data` or
`this.tabGroup['_currentLabelWrapper'].textContent` - Eventually I settled on the latter, though obviously this is a public property, so I'd like to avoid it where possible.

#### What is the expected behavior?
To be able to pull either the ElementRef of the LabelWrapper, or the raw text value passed into the Label template, inside the `onTabChange` event

#### What is the current behavior?
The value seems to be protected behind private properties only

#### What are the steps to reproduce?
Attempt to get the content of the label on tab change

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
I'd like to be able to route directly to a specific tab, and have the route change on tab change. 

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.0.0
Material: 2.0.0-alpha.9-3

**Comment by j3ddesign** [comment]
I ended up realising my stupidity and calling from an array of the tab labels by the `selectedIndex` property - which while much cleaner than my previous approach, still feels a little less DRY.

It'd be great to be able to call `event.label.content` on tab change and get the string value of the label template - if possible.

**Comment by jelbourn** [comment]
Our take on this is that the user is the one responsible for putting the text content _into_ the tab, so you should also know what that content is based on the selected tab.
