### ISSUE TITLE
cdkDrag : Reset all dragged element to initial position or specified position

### ISSUE THREAD

**Issue by manjunathkundar** [angular/material2#14890]
#### Please describe the feature you would like to request.
Feature Request

#### What is the use-case or motivation for this proposal?
I am building Hotspot feature to an image. All the hotspots are set by the end user by dragging. I am able to build everything from cdkdrag but I need all Hotspot to reset to initial/custom position by a click of button.

#### Is there anything else we should know?
There is reset on cdkDragEnded. But how to apply this to button when all the hotspots are dragged.

**Comment by crisbeto** [comment]
Will be added by https://github.com/angular/material2/pull/14696.
