### ISSUE TITLE
Revert default snackbar animation and position to version 6.4.7

### ISSUE THREAD

**Issue by camden-kid** [angular/material2#14903]
#### Please describe the feature you would like to request.
Revert the snackbar animation and position to that in version 6.4.7

#### What is the use-case or motivation for this proposal?
It is much better.

#### Is there anything else we should know?
In version 6.4.7 the snackbar animated up from off-screen and did not have a gap. In the current version (7.2.1) the snackbar just animates on-screen and there is a gap between it and the edge of the screen.

**Comment by crisbeto** [comment]
This is the behavior according to the Material Design spec which we're following.

**Comment by camden-kid** [comment]
@crisbeto Fair enough. Did the Material Design spec change between the versions? It's quite a difference.

**Comment by crisbeto** [comment]
Yes, there was a new version of the spec after Google I/O.

**Comment by camden-kid** [comment]
@crisbeto Thanks.

**Comment by crisbeto** [comment]
Under the 7.0.0 changes:
> Updated component styles throughout the library matching the 2018 Material Design Spec refresh.

**Comment by camden-kid** [comment]
@crisbeto Oh, nice. Thank you.
