### ISSUE TITLE
Overriding `$md-button-line-height` while `box-sizing: border-box` offsets `md-icon` in `button[md-fab]` and `button[md-mini-fab]`

### ISSUE THREAD

**Issue by emilio-martinez** [angular/material2#1490]
#### Bug, feature request, or proposal:
Proposal, maybe bug depending on your perspective

#### Description of expected and current behavior?

In the plunkr below, I've applied some styles to show what I've run into in a project. This description that follows can also be found next to the styles in the plunkr—which would provide more context, but I'll supply them here just the same:

First portion refers to setting all `box-sizing` to `border-box`. It's a common practice and most notably found in the Bootstrap reboot (added on from normalize in that context).
Credit: https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

The second portion is an attempt to simulate the impact of overriding the sass variables while theming. `$md-button-line-height` is set to 1.3em to allow for multiline text in a button, and additionally, although not necessarily related to this issue $md-button-padding is set to 8px 16px just to compensate for the vertical spacing that the line-height offered before.

The main issue here is that modifying the `line-height` when `box-sizing: border-box;` is set globally collapses `<md-icon>`, offsetting it only on buttons (oddly enough). Tested briefly on Chrome and Firefox.

To this I would suggest reiterating `box-sizing: content-box;` if the styling is dependent on the vertical padding on `md-icon` while inside `md-fab` and `md-mini-fab` (set by sass function `md-fab` by passing in `$md-fab-padding` and `$md-mini-fab-padding`.

#### What are the steps to reproduce?
http://plnkr.co/edit/0jWuFZ0AKwVicKhvnvsK?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Simply compatibility with a common use case that others might find. I understand that setting a box-sizing property globally is the author's choice and generally they would have to deal with those repercussions. That said, many other styles are not impacted by this, and from my perspective this might save some time is somebody runs into this type of issue—alignment.

**Comment by jelbourn** [comment]
The styles are written in such a way that an icon inside of the fab looks right based on the line-height defined in the library. If you override the line height, you'll also have to do extra work to make icons inside of fabs aligned correctly.
