### ISSUE TITLE
Virtual scroll: Issue when scrolling to newly added item

### ISSUE THREAD

**Issue by TKul6** [angular/material2#14905]
#### What is the expected behavior?

When adding an element to the list and then scrolling to that element, the element should appear in the view port.

#### What is the current behavior?
After adding new element to a list, I want that element to be in the viewport.
To do so I use the `scrollToIndex` method, but it doesn't work, instead the virtual scroll, is scrolled to the second element from the last of the list.

See stackBlitz for example
#### What are the steps to reproduce?
https://angular-qbdchv-mzmbsv.stackblitz.io

When clicking on the Add Row button it seems the virtual scroll is working but in reality you can still scroll to the element.

Keep in mind that the last items (near the add button), is different than the last item displayed in the list.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.11.3
@angular-devkit/core         7.1.3
@angular-devkit/schematics   7.1.3
@angular/cli                 7.1.3
@schematics/angular          7.1.3
@schematics/update           0.11.3
rxjs                         6.3.3
typescript                   3.1.3
Material: 7.2.1

**Comment by TKul6** [comment]
Guys, any news???

Thanks

**Comment by mmalerba** [comment]
You need to wait for the item to be rendered before you can scroll to it, you can do this with `requestAnimationFrame`: https://stackblitz.com/edit/angular-qbdchv-g23dof?file=app%2Fcdk-virtual-scroll-fixed-buffer-example.ts

**Comment by TKul6** [comment]
Thanks, that seems to do the trick 👍
