### ISSUE TITLE
MatSnackBar display animation

### ISSUE THREAD

**Issue by aurora-x1994** [angular/material2#14901]
#### Bug, feature request, or proposal:
          I want to change the animation when MatSnackBar appears, but I didn't find the relevant documentation.

#### What is the expected behavior?
          sliding from bottom to top

#### What is the current behavior?
         I added an extra CSS class to animate but will not execute until the default animation has finished executing.
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
          V7.2.0

**Comment by CrabUncle** [comment]
sorry,  i don't know how to help you, i really like you and want to help, but i know none shit about anguluar ! maybe you can use VUE .

**Comment by josephperrott** [comment]
The animations for snackbar are not customizable as they are defined by the material spec.  There is a larger effort under way to determine how to allow for all of our animations to be customizable, though there is not any specific progress on it at this point.
