### ISSUE TITLE
mat-table: null values shows 'null' in dynamic columns but '' in HTML declared columns 

### ISSUE THREAD

**Issue by JessyParis** [angular/material2#14904]
#### What is the expected behavior?
null values should show the same text in the cells (nothing = '') wether the column is created in typescript or in HTML

#### What is the current behavior?
When a column is declared in html, null values dont show anything in the cell
```HTML
<ng-container matColumnDef="AdresseOrigineVille">
	<mat-header-cell *matHeaderCellDef mat-sort-header>AdresseOrigineVille</mat-header-cell>
	<mat-cell *matCellDef="let item"> {{item.AdresseOrigineVille}} </mat-cell>
</ng-container>
```
But when the same column is declared in TypeScript, null values show 'null' in the cell
```HTML
<ng-container *ngFor="let column of columns" [matColumnDef]="column.columnDef">
	<mat-header-cell *matHeaderCellDef>{{ column.header }}</mat-header-cell>
	<mat-cell *matCellDef="let item">{{ column.cell(item) }}</mat-cell>
</ng-container>
```
```TypeScript
this.columns.push({ columnDef: "AdresseOrigineVille", header: "AdresseOrigineVille", cell: (item: (myInterface or any produces the same result))) => `${item.AdresseOrigineVille}` });
```
#### Version
Material 6.4.7

Regards,

**Comment by andrewseguin** [comment]
Thanks for reporting this issue but you forgot to include a reproduction. Feel free to re-open this issue with a reproduction of what you are seeing so we can investigate and fix the issue.

Here's a starter template to use: https://run.stackblitz.com/api/angular/v1?file=app%2Ftable-basic-example.ts
