### ISSUE TITLE
perf: OnHovering over the sort header triggers change detection

### ISSUE THREAD

**Issue by sheikalthaf** [angular/material2#14911]
#### Please describe the feature you would like to request.
Lib: MatSortModule

On hovering over the sort header triggers the changedetection, which we can prevent to improve the performance of this lib

#### What is the use-case or motivation for this proposal?
Motivation is to increase the performance of the lib. We can run the listeners out side of the angular with the help of zonejs. This is y because most of the time we are not going to sort the header but header will hover without on cursor move over the screen

**Comment by andrewseguin** [comment]
The change detection on hover is used to animate the sort indicator to let the user know that the column is sortable. Without this, the animation would not play.
