### ISSUE TITLE
bug(cdk-overlay): scrollbar doesn't appear inside container with long content in IE

### ISSUE THREAD

**Issue by iwonz** [angular/material2#14926]
#### What is the expected behavior?
If we have container with long content inside cdk-overlay we expect scrollbar.

#### What is the current behavior?
It appears in Chrome but doesn't appear in IE.

Google Chrome: 71.0.3578.98 (Official Build) (64-bit)
![2019-01-23 14-04-51 angular-dd3qyr - stackblitz - google chrome](https://user-images.githubusercontent.com/17701819/51603281-6d027880-1f1a-11e9-8c57-d56241816a6d.jpg)

IE: 11.2670.14393.0
![2019-01-23 14-05-44 angular-dd3qyr - stackblitz - internet explorer](https://user-images.githubusercontent.com/17701819/51603286-7095ff80-1f1a-11e9-949a-eb8f227d0bc0.jpg)

It works fine if i limit height of container or cdk-overlay-pane.

OS: Windows 10

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/edit/angular-dd3qyr

#### Is there anything else we should know?
Sorry if it's just my misundertanding of technology.

**Comment by crisbeto** [comment]
It's because you're not passing in a position strategy. Here's a working example: https://stackblitz.com/edit/angular-8f2njx?file=src/app/app.component.ts.

**Comment by iwonz** [comment]
> It's because you're not passing in a position strategy. Here's a working example: https://stackblitz.com/edit/angular-8f2njx?file=src/app/app.component.ts.

Thx for answer, Kristiyan. Maybe the problem in bug it's easy to fix. Despite the fact that fix didn't answer why example works in Chrome and don't work in IE. A global position just makes limited by height wrapper and I wrote what that fix my problem. But what if I have something like this?
https://stackblitz.com/edit/angular-khuzpz
