### ISSUE TITLE
mat-list-item' is not a known element

### ISSUE THREAD

**Issue by scriptsure** [angular/material2#14936]
Getting following issue when trying to import list:

ERROR Error: Uncaught (in promise): Error: Template parse errors:
'mat-list-item' is not a known element:
1. If 'mat-list-item' is an Angular component, then verify that it is part of this module.
2. If 'mat-list-item' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<mat-list>
  [ERROR ->]<mat-list-item *ngFor="let video of videos">
    {{video.title}}
  </mat-list-item>
"): ng:///DashboardModule/VideoDashboardComponent.html@1:2
'mat-list' is not a known element:
1. If 'mat-list' is an Angular component, then verify that it is part of this module.
2. If 'mat-list' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<mat-list>
  <mat-list-item *ngFor="let video of videos">
    {{video.title}}
"): ng:///DashboardModule/VideoDashboardComponent.html@0:0

**I have also tried to directly import from @angular/material/list but it is giving the same error.**

#### What are the steps to reproduce?
import {MatButtonModule, MatCheckboxModule, MatToolbarModule, MatListModule} from '@angular/material';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    MatToolbarModule,
    MatButtonModule,
    MatCheckboxModule,
    MatListModule,
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule
  ],

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.2.2

**Comment by andrewseguin** [comment]
Please provide a reproduction in Stackblitz so we can investigate

**Comment by AnouarBenZahra** [comment]
Try to import {MatListModule} from '@angular/material/list'; it's works

**Comment by vis-8757** [comment]
@AnouarBenZahra  I did the same. From '@angular/material/list'. its still showing the exact same error as mentioned. 
My code is the same as the one mentioned in the issue except that i'm not using MatButtonModule and MatCheckboxModule. I'm importing the MatListModule like mentioned above.
