### ISSUE TITLE
Datepicker - matDatepickerParse.text not setting properly in 7.0.3 version 

### ISSUE THREAD

**Issue by AngularTx** [angular/material2#14945]
#### What is the expected behavior?
matDatepickerParse.text should have the value as ' ' ,  if the user has removed the complete date using the cursor (backspace) . 
>>>>>>>>>>>>>>This was working with older version of material  (5.2.4) <<<<<<<<<<<<<<<<<<<<

#### What is the current behavior?
now matDatepickerParse.text doesnot get updated completely even after removing the date. 
Example : 2014.11.11 -> if we start removing the text using the back space , and remove it completely , 
we see the matDatepickerParse.text as '2014.11.1' .

We would expect matDatepickerParse.text to be  '  ' . 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular and material  version 7.0.3.

#### Is there anything else we should know?
matDatepickerParse.text was getting updated to '' when we remove the date completely . But now it doesn't happen .

**Comment by AngularTx** [comment]
I have now upgraded to the 7.2.2 version(all dependencies of angular)  and still have the same issue . 
Our application is not stable now because of this breaking functionality.

**Comment by mmalerba** [comment]
I believe #14423 should fix this

**Comment by mmalerba** [comment]
Likely will be Monday

**Comment by AngularTx** [comment]
Hi @mmalerba  
Thanks for the update. It would be great if you could reply with the version so we could test the changes.

**Comment by AngularTx** [comment]
Any update on the release ? Few Of the functionality is broken because of this in production. So would like to know the estimated time to get this live ?

**Comment by mmalerba** [comment]
7.3 is out now and should have the fix

**Comment by AngularTx** [comment]
I can confirm that the fix is working fine now ! Thanks!

**Comment by mmalerba** [comment]
Fantastic! closing this issue
