### ISSUE TITLE
Update Travis CI to use yarn instead of npm install

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#1494]
Need to verify that it's faster, but yarn will likely be an improvement.

**Comment by jelbourn** [comment]
Relevant https://twitter.com/kentcdodds/status/786282951210262528

**Comment by pi0** [comment]
Please checkout [YarNPM](https://github.com/pi0/yarnpm) :)

**Comment by d3viant0ne** [comment]
@jelbourn - Tinkered around with this on my fork, the end result is it's a wash.

We spend ~70 seconds give or take to install with npm ( no cache ) and under 10 seconds with it.
With yarn it takes ~50 seconds ( no cache ) and ~8 seconds with it. 

In either case you have to pull down the cache from Amazon s3, a large chunk of the overall performance improvements you see with yarn locally disappear when you cache isn't local. 

It's a pretty consistent theme. Yarn is great for a lot of things, container driven, hosted CI really isn't one of them. The only place I have had a great deal of success is an internal Jenkins server running ec2 slaves.

Also worth noting, there are side effects in the gulp scripting that would have to be fixed should you chose to have this implemented.

**Comment by d3viant0ne** [comment]
If you still want it done, i'll clean up the work and PR in the Travis changes and fixes to the gulp scripting.

**Comment by d3viant0ne** [comment]
It's also worth noting, if switching to yarn is creating side effects in the build scripting it's reasonable we are going to see it in the library proper. IMO the minimal time savings that will exist once yarn is included in the Travis containers doesn't outweigh the risk of the above mentioned side effects.

**Comment by jelbourn** [comment]
@d3viant0ne thanks for investigating! Since there's not a noticeable improvement, I'm okay with sticking to `npm`.
