### ISSUE TITLE
nav responsive by default?

### ISSUE THREAD

**Issue by ORESoftware** [angular/material2#14969]
#### Please describe the feature you would like to request.
Make nav responsive by default (for small/mobile screens)

I have this in app.component.html:

```html
<app-nav></app-nav>

<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
</div>


<section>
  <router-outlet></router-outlet>
</section>
```

and then for nav.component.html I have:

```html
<header>
  <div class="container">
    <a routerLink="/" class="logo">API Docs</a>
    <nav>
      <ul>
        <li><a routerLink="/">Main/Home</a></li>
        <li><a routerLink="/about">About</a></li>
        <li><a routerLink="/contact">Contact us</a></li>
      </ul>
    </nav>
  </div>
</header>

```

but when I shrink my browser window down, medium size looks like this:

![screenshot from 2019-01-26 15-09-43](https://user-images.githubusercontent.com/11139560/51793872-7a1ea200-217c-11e9-891f-6832d7769d3f.png)

then the smallest I can make it with Chrome is like this:

![screenshot from 2019-01-26 15-10-31](https://user-images.githubusercontent.com/11139560/51793894-91f62600-217c-11e9-99ac-89b2c1841042.png)

as you can see the nav menu items overlap each other, is there a way to get them to use the responsibe drop-down menu style?

**Comment by jelbourn** [comment]
This appears to be unrelated to Angular Material.

**Comment by ORESoftware** [comment]
@jelbourn hmmm I am confused - I would think Material would be responsive by default - is there someone that might know what's going on and how I can make it responsive? I am not a front-end guru, just need some info, thanks. Does Material using Bootstrap under the hood or some other responsive library? Why might it not be responsive by default?

**Comment by jelbourn** [comment]
Angular Material is purely a component library and does not take any opinions on application layout and does not apply any global styles to your application. Your code snippets do not show use of any Angular Material components.
