### ISSUE TITLE
Exports keys as string values in @angular/cdk/keycodes

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#14977]
#### What is the expected behavior?

Since `event.keyCode` is marked as deprecated,  `@angular/cdk/keycodes` should export key as string values to so they can be compared with either `event.key` or `event.code`

#### What is the current behavior?

It works, but the keyboard's `event.keyCode` is marked as deprecated

#### What are the steps to reproduce?

For example:
```ts
import { ESCAPE } from '@angular/cdk/keycodes';

// Close on escape click
 this._overlayRef.keydownEvents().subscribe((event: KeyboardEvent) => {
   if (event.keyCode === ESCAPE) {
     this.close();
   }
 });
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material@7.2.2

**Comment by crisbeto** [comment]
If I remember correctly, the problem with using `key` is that it the browser support wasn't great and that different browsers call the keys differently (e.g. IE and Edge call the down arrow `Down`, whereas all other browsers call it `ArrowDown`). Also even though `keyCode` is marked as deprecated, I doubt that it's going away any time soon.

**Comment by jelbourn** [comment]
This is captured as part of #7374
