### ISSUE TITLE
Form Pristine & Dirty values are wrong when matInput has placeholder attribute in IE 11

### ISSUE THREAD

**Issue by raghufsmk** [angular/material2#14993]
#### What is the expected behavior?
on loading page, form should have the following default value with matInput and placeholder attribute in IE11

prisitine - true
dirty - false

**Note:** Its working fine as expected without placeholder attribute in matInput.

#### What is the current behavior?
Onload it has below value in IE 
pristine - false
dirty - true

which is different from Chrom and Firefox

#### What are the steps to reproduce?
https://stackblitz.com/edit/form-status

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
**Angular version:** 6.01
**Browser:** IE 11
**Language:** TypeScript

#### Is there anything else we should know?
NIL

**Comment by crisbeto** [comment]
This looks to be the same issue as #14440. Closing since Material doesn't gave anything to do with when the form control is marked as dirty.

**Comment by debasis558** [comment]
Try with adding placeholder like below
