### ISSUE TITLE
Stackblitz examples are broken

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#14991]
#### What is the expected behavior?

The stackblitz examples should work.

#### What is the current behavior?

![image](https://user-images.githubusercontent.com/25405143/51898510-2f797180-2398-11e9-808f-3cdfe93044eb.png)

![image](https://user-images.githubusercontent.com/25405143/51898541-3e602400-2398-11e9-9846-209d8e87c333.png)

#### What are the steps to reproduce?

--

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

--

#### Is there anything else we should know?

--

**Comment by StefanKern** [comment]
Can reproduce it by clicking any stackblitz buttons in the examples of "https://material.angular.io/components/form-field/overview".

Cannot post a link, a direct link to a stackblitz example, since it seems to make some kind of post.

**Comment by devversion** [comment]
Possibly related to https://github.com/stackblitz/core/issues/624. I don't seem to be able to install `@angular/material` on a plain stackblitz project.

**Comment by devversion** [comment]
Confirmed locally that NPM/Yarn install the correct version of Angular Material, so I'm fairly sure that this is related to the issue I just linked above.

I'm wondering if there is anything we could do about this.. because I suspect we'll experience similar issues when publishing new versions.

**Comment by StefanKern** [comment]
Follup: the last version of angular in npm is 7.2.2. So it is correct that stackblitz fails, when it tries to reference version 7.3.0 in my opinion

(https://www.npmjs.com/package/@angular/animations )

**Comment by julianobrasil** [comment]
@SargoDarya, the correct link on NPM is https://www.npmjs.com/package/@angular/material. It's already 7.3.0 (despite the fact stackblitz cannot install it). One funny thing is that stackblitz successfully installs `@angular/cdk` 7.3.0 at NPM.

**Comment by julianobrasil** [comment]
Closing this as it seems to be fixed as pointed out by @EricSimons
