### ISSUE TITLE
Q1 2019 / 2019 plans

### ISSUE THREAD

**Issue by fxck** [angular/material2#14992]
Hi, hello, could you please update readme with what's planned for Q1 2019, and perhaps say something about what's planned for 2019 in general? 

I especially look forward for news on https://github.com/angular/material2/pull/7835 and whether this https://github.com/angular/material2/issues/4444 is something you plan on looking into, now that Ivy is finishing.

Thank you!

**Comment by Misiu** [comment]
@jelbourn any news? 😉

**Comment by jelbourn** [comment]
I'll try to update the readme shortly, but TL;DR most of the team is on loan helping with Ivy
