### ISSUE TITLE
<mat-icon> 'cast_for_education' missing

### ISSUE THREAD

**Issue by MicMicMon** [angular/material2#14997]
#### What is the expected behavior?
`cast_for_education` should be ok as shown on [Material design page](https://material.io/tools/icons/?icon=cast_for_education&style=baseline)

#### What is the current behavior?

Icon `cast` is shown instead.

#### What are the steps to reproduce?
[Stackblitz showing issue](https://stackblitz.com/edit/angular-material2-issue-8seawf)

**Comment by crisbeto** [comment]
The Material Design icons are maintained on this repo. [You can try posting your issue here](https://github.com/material-components).

**Comment by MicMicMon** [comment]
Ok. Posted [https://github.com/google/material-design-icons/issues/902](here).
