### ISSUE TITLE
Stackblitz examples don't link on angular material components

### ISSUE THREAD

**Issue by jtobelem-simplon** [angular/material2#14995]
#### What is the current behavior?
I got this error when opening the link :
`{"error":"UNSATISFIED_RANGE","data":{"name":"@angular/material","range":"7.3.0"}}`

#### What are the steps to reproduce?
https://material.angular.io/components/table/examples

**Comment by devversion** [comment]
Thanks for the issue, but please just use the existing issue in #14991.
