### ISSUE TITLE
md-menu click catcher is fixed to a container.

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#1499]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
The click catcher for md-menu should be applied on the whole screen.

#### What is the current behavior?
```
<div class="md-menu-click-catcher"></div>
```
The click catcher element is located within the menu directive this means that in some situations the fixed viewport is not the body but some element in the DOM tree between the body and the click catcher.
This can happen when an element (ancestor of css catcher) applies CSS transform. When this happen the click catcher will be bound to the element's view port and not the body.

A great example is the `SideNav`, the sidenav's content element applies a `transform: translate3d(0px, 0px, 0px);` and when opened the `margin-left` CSS property reduce's the content size thus reduces the click catcher size, in this scenario clicks over the sidebar navigation are will not trigger a close event. (hovers will works as well... etc)

The menu is rendered in the the overlay container area but its not using the overlay backdrop, I guess since you can't control the styling of the backdrop to make it transparent...

**Comment by shlomiassaf** [comment]
Another issue related to the click catcher element is when a menu item has a `routerLink` that does not exist. This will trigger an exception.

When this happens the click catcher is not removed, if the click catcher is not inside a router outlet (above it) the whole app becomes non responsive (can't click)

**Comment by fxck** [comment]
related
https://github.com/angular/material2/issues/998
https://github.com/angular/material2/issues/1417

**Comment by shlomiassaf** [comment]
The issue is really using a backdrop inside the menu content but creating the dom element inside the overlay container.

The right solution is to use the overlay's backdrop and being able to control the backdrop background color

**Comment by jelbourn** [comment]
The current behavior is just temporary until menu uses the Overlay's backdrop.

**Comment by jelbourn** [comment]
Closed via #1534
