### ISSUE TITLE
Feature Request: Context Menu, and TreeView

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [angular/material2#150]
I would like to request to add two more things:

1- Custom Context Menu for components: I'm currently trying to build one on my own, but many difficulties come with context menus. Also, if I want to add it as a directive on top of components, I can't seem to have a template for it, I will have to create it using jQuery or some other library. Am I correct?

2- TreeView: Well it is a highly-needed component :)

**Comment by jelbourn** [comment]
These aren't components we plan on building for our initial release. I'm going to close this, but feel free to come back and re-file after we release our 1.0.
