### ISSUE TITLE
expose `addThemeStyleToTarget` method from schematics

### ISSUE THREAD

**Issue by richavyas** [angular/material2#15006]
#### Please describe the feature you would like to request.
It would be great if `addThemeStyleToTarget` method can be exposed so that it can be reused. (https://github.com/angular/material2/blob/master/src/lib/schematics/ng-add/theming/theming.ts#L103)

#### What is the use-case or motivation for this proposal?
I am writing a schematic which involves adding `theme.scss` to a project. I found this method pretty useful and IMO, it is generic enough to be exposed.

**Comment by jelbourn** [comment]
We currently don't consider our schematics utility code to be a public API; anything useful here should become feature requests on the [Angular CLI](https://github.com/angular/angular-cli/) repo
