### ISSUE TITLE
md-tab-group is not defined in the prebuilt themes

### ISSUE THREAD

**Issue by fedecarpi** [angular/material2#1501]
#### What is the expected behavior?
Changing the prebuilt css theme should change the colors of the component (just like happen with other components, input text, button, etc)

#### What is the current behavior?
Always shows the same (light-green) color not matter what's the theme imported.

#### What are the steps to reproduce?
Create a basic page with a tab group and two tabs, import different themes, you will see the colors of the tabs and the underline never change.

#### What is the use-case or motivation for changing an existing behavior?
This seems to be a bug.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0, Material 2.0.0-alpha.9-3, OS: OSx, browsers: Chrome, FF, Safari.

**Comment by andrewseguin** [comment]
Cannot reproduce the issue, are you sure you are pulling in the prebuilt CSS?

Here are a couple plunker examples of applying a theme to the tab
 - pink-bluegrey.css: http://plnkr.co/edit/2ZRZvZb47waXYkz3ik9v?p=preview
 - indigo-pink.css: http://plnkr.co/edit/YeV8s43Zq0xNgipnoKlN?p=preview
