### ISSUE TITLE
 does not supports nodes with ids.?

### ISSUE THREAD

**Issue by malikfaizanhaider** [angular/material2#15029]
Here is any way to print node ID?

For Example:
`<mat-tree-node [attr.id]="node.id" *matTreeNodeDef="let node;when: hasChild" matTreeNodePadding></mat-tree-node>`

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
