### ISSUE TITLE
FullscreenOverlayContainer not working

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/material2#15033]
#### What is the expected behavior?
Fullscreen should correctly display CDK drag & drop while in fullscreen via javascript Fullscreen API 

#### What is the current behavior?
dragged object is not visible while dragging.

#### What are the steps to reproduce?
1. register FullscreenOverlayContainer in module providers:
`{provide: OverlayContainer, useClass: FullscreenOverlayContainer}`
2. use `screenfull` npm package in angular aplication to implement fullscreen feature

dragged elements should be visible while dragging but not
![fullscreendrag](https://user-images.githubusercontent.com/11920691/52051556-364ce380-2554-11e9-836d-0ccfa5e9abad.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.2.3
Material & CDK: 7.3.0
Typescript 3.2.4
Windows 10
Chrome

#### Is there anything else we should know?
I create my own MaterialModule which imports & exports necessary modules from `@angular/material`. That module is being imported into each feature module that use the fullscreen function.

**Comment by crisbeto** [comment]
This is more of an issue with `cdk/drag-drop` than `overlay`.

**Comment by Ryan-Haines** [comment]
I also put this comment on #10679 :

I've added the `FullscreenOverlayContainer` to my `@ngModule`, and on desktop browsers, it works great! However, it does not work on Android - the menu is still shown behind the main content as it did before adding this provider. Is this a known issue and are there any workarounds to get this working on the android browser?
