### ISSUE TITLE
Corrupted arrow-buttons in Ie11 (Datepicker)

### ISSUE THREAD

**Issue by oky1** [angular/material2#15032]
#### What is the expected behavior?
Buttons on ie11 not corrupted

#### What is the current behavior?
Buttons on ie11 corrupted

#### What are the steps to reproduce?
Open calendar. At rigth-top corner corrupted arrows.
https://i.gyazo.com/8e1621c90480276cc77554a560ffeb32.png
https://i.gyazo.com/d8773304f2c1a0cddf49b4edaa70ac7e.png%20we%20use%20calendar%20from%20angular%20material%20and%20don't%20control%20their%20appearance

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0, Ie11 (11.285.17134.0). Mater 7.0

**Comment by crisbeto** [comment]
I couldn't reproduce it against IE11. It looks like there might be some other styles from your app that are interfering with it.
