### ISSUE TITLE
'disableRipple' on Calendar don't disabling ripples

### ISSUE THREAD

**Issue by oky1** [angular/material2#15031]
Ref to #13986

Bug, feature request, or proposal:
matRippleDisabled at mat-datepicker-toggle.
'disableRipple' added to src/lib/datepicker/datepicker-toggle.ts don't solve problem

What is the expected behavior?
matRippleDisabled should disable ripple on button

What is the current behavior?
Not disabled ripple on button

What are the steps to reproduce?
Add matRippleDisabled at mat-datepicker-toggle component

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Ang 7.2.3, Crome 71.035, AngMaterial 7.3

**Comment by crisbeto** [comment]
Can you post your markup? It definitely should pass the `disableRipple` value to the underlying button, but you'll have to pass it in like this:

```
<mat-datepicker-toggle [disableRipple]="true"></mat-datepicker-toggle>
```

**Comment by oky1** [comment]
I tried it all, but sorry

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.

(this is a canned response)
