### ISSUE TITLE
Can not zoom sidenav examples

### ISSUE THREAD

**Issue by mfairchild365** [angular/material2#15040]
#### What is the expected behavior?
Users must be able to zoom in on a page on mobile browsers

#### What is the current behavior?
Users can not zoom in on a page on mobile browsers

#### What are the steps to reproduce?
Note: I was unable to load the StackBlitz example on my iphone, so steps to identify the error using axe-core are listed below.

1. If you do not already have the [axe-core extension](https://www.deque.com/axe/) installed, install it.
2. Open the [sidenav example](https://material.angular.io/components/sidenav/examples).
3. Click the button to edit the "basic sidenav" example in StackBlitz
4. Click the button to open the StackBlitz example in a new window
5. Run axe-core on the page
6. Observe that a critical issue "Zooming and scaling must not be disabled" is found

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Angular Material Example 7.2.2 located at https://material.angular.io/components/
- NVDA 2018.4.1 + FireFox 64
- VoiceOver for IOS (12.1.3) + Safari (12.1.3)

#### Is there anything else we should know?
This issue doesn't appear to be built in to the component, but the example should demonstrate the component with no accessibility issues.

**Comment by crisbeto** [comment]
Closing since there's not much we can do about Stackblitz issues.
