### ISSUE TITLE
make aria-describedby optional for matTooltip

### ISSUE THREAD

**Issue by jasonzhang2022** [angular/material2#15048]
#### Bug, feature request, or proposal:
when matTooltip is used, aria-describedby is auto added. I want to make this optional.

#### What is the expected behavior?
Make this optional.

#### What is the current behavior?
It is automatically, there is no way to turn this off.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
when JAWS is used, JAWS ignores aria-describeby during linear navigation. 

aria-label can be recognized by all screen reader.

However, If I have both matTooltip, and aria-label, the text will be announced twice by VoiceOver and Vox.

So I intend to use the matTooltip like this

[matTooltip]="my text" aria-label="my text" no-describedby. 

By this way, I completely control the accessibility behavior.

**Comment by manklu** [comment]
Then it would be better to always use aria-label instead of making aria-describedby optional.

**Comment by crisbeto** [comment]
@jelbourn would it make sense to not add `aria-describedby` if an `aria-label` is present?

**Comment by jelbourn** [comment]
I put this question on the agenda for my next sync with the Google a11y folks
