### ISSUE TITLE
cdkDragMoved prevent move

### ISSUE THREAD

**Issue by DaniJunsui** [angular/material2#15055]
#### Please describe the feature you would like to request.
The event handler cdkDragMoved should have a method to avoid the move.

#### What is the use-case or motivation for this proposal?
Having for example 2 different drag elements on the same parent container, check that one of them cant exceed the second one.

![image](https://user-images.githubusercontent.com/29247262/52113220-057ab600-2609-11e9-9303-d262acb01d23.png)

My code: 
![image](https://user-images.githubusercontent.com/29247262/52113309-44107080-2609-11e9-9c13-353b91c7df82.png)

![image](https://user-images.githubusercontent.com/29247262/52113323-4b377e80-2609-11e9-8e24-155edf7f6698.png)

#### Is there anything else we should know?

This could be useful for make own custom sliders with multiple sections.

**Comment by crisbeto** [comment]
If I'm reading this correctly, you want to prevent the dragged element from leaving one its parents. This is possible already with the `cdkDragBoundary` attribute. [Here's an example from the docs](https://material.angular.io/cdk/drag-drop/overview#restricting-movement-within-an-element).

**Comment by DaniJunsui** [comment]
> If I'm reading this correctly, you want to prevent the dragged element from leaving one its parents. This is possible already with the `cdkDragBoundary` attribute. [Here's an example from the docs](https://material.angular.io/cdk/drag-drop/overview#restricting-movement-within-an-element).

Thanks for the answer.

This is the behaviour I want, but not with the parent, but with the brother.
So, instead the "return false" in the code, a method that prevents for moveing.

The "`cdkDragMoved`" event is call for "each pixel" the box 1 is moved. My idea is to call like a method to prevent the next movement, so the box is stacked on the same place.

My final idea is this one:
![image](https://user-images.githubusercontent.com/29247262/52121166-eedf5980-261e-11e9-98b4-f639c45f3cc9.png)

Having 3 sliders (all of them can only move in the X axe inside the black box (`cdkDragBoundary`)
Slider Red: Can just move to the right, until the green box and left until the black parent one.
Slider Green: Can move to the left and right, but just until Box Red and box Blue
Slider Blue: Can move until right parent black box and left until brother green one.

**Comment by crisbeto** [comment]
You should be able to get something like that by wrapping the 3 arrow boxes with a flex parent that expands until the next sibling. Then you can set the flex parent to be the boundary.

**Comment by DaniJunsui** [comment]
> You should be able to get something like that by wrapping the 3 arrow boxes with a flex parent that expands until the next sibling. Then you can set the flex parent to be the boundary.

This was my other approach, but it dosent work well: I had to change the boundary for the left & right element on moveing the middle one, but on changint the width, the draggable moves too...

**Comment by andreElrico** [comment]
@DaniJunsui could you post a stackblitz that uses the new feature?

**Comment by kykint** [comment]
when is it going to be released? As I can see it is still not available on npm
