### ISSUE TITLE
MatSnackBar would not show when .open is used.

### ISSUE THREAD

**Issue by bamboozooled** [angular/material2#15050]
#### What is the expected behavior?
I expect MatSnackBar to show when I call snackbar.open
#### What is the current behavior?
The Snackbar would not even appear

#### What are the steps to reproduce?
My app module
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {FlexLayoutModule} from '@angular/flex-layout';
import { HomeComponent } from './home/home.component';
import { NavComponent } from './nav/nav.component';
import {MatToolbarModule} from '@angular/material';
import {AuthService} from './services/auth.service';
import {MatSnackBarModule} from '@angular/material/snack-bar';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    NavComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    FlexLayoutModule,
    MatToolbarModule,
    MatSnackBarModule
  ],
  providers: [AuthService],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

my component trying to trigger the snackbar

```
import { Injectable } from '@angular/core';
import * as firebase from 'firebase/app';
import {MatSnackBar} from '@angular/material';
declare var $: any;
@Injectable({
  providedIn: 'root'
})
export class AuthService {

  constructor(public snackbar: MatSnackBar) { }

  signup(email: string, pass: string) {
    this.snackbar.open("hello", null, {duration:5000});
    // firebase.auth().createUserWithEmailAndPassword(email, pass).then((response) => {
    //   this.sb.open('Sign up successful', null, {duration: 5000});
    //   $('#modal-form').modal('hide');
    //   $('#modal-subscribe').modal('show');
    // }).catch((error) => {
    //   this.sb.open('An error occurred signing up', null, {duration: 5000});
    // });

  }
}
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Using Angular Material 7.3.0 and running on Angular 7

```
{
  "name": "unamed app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.0.4",
    "@angular/cdk": "^7.3.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/material": "^7.3.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "core-js": "^2.5.4",
    "firebase": "^5.8.2",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.12.3",
    "@angular/cli": "~7.0.2",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
}

```

**Comment by manklu** [comment]
Works for me

https://stackblitz.com/edit/angular-dv6wwl?file=app%2Fsnack-bar-component-example.ts

**Comment by bamboozooled** [comment]
Strange. From your example, the only difference is I am also using a bootstrap dialog. Could the bootstrap dialog being open at the same time cause this behavior?

**Comment by julianobrasil** [comment]
@bamboozooled, it's not a good idea using two styling libraries together, but I did it myself in the past without much problems (material + bootstrap, without bootstrap's javascript part). But it doesn't look like to be the problem in your case.

Are you, by any chance, calling the service outside `NgZone`? This would cause a similar behavior. Maybe some other external library is firing the event that is calling your auth service. You can test it by injecting zone and forcing the snackbar to run inside `NgZone` again:

```ts
  constructor(public _zone: MatSnackBar, private _zone: NgZone) { }

  signup(email: string, pass: string) {
    _zone.run(() => {
      this.snackbar.open("hello", null, {duration:5000});
    });
  }
```

If the code above fixes your problem, there must be some code (maybe external to your project) calling your service ouside `NgZone`.

**Comment by julianobrasil** [comment]
@bamboozooled, it's not a good idea using two styling libraries together, but I did it myself in the past without much problems (material + bootstrap, without bootstrap's javascript part). But it doesn't look like to be the problem in your case.

Are you, by any chance, calling the service outside `NgZone`? This would cause a similar behavior. Maybe some other external library is firing the event that is calling your auth service. You can test it by injecting zone and forcing the snackbar to run inside `NgZone` again:

```ts
  constructor(public _zone: MatSnackBar, private _zone: NgZone) { }

  signup(email: string, pass: string) {
    _zone.run(() => {
      this.snackbar.open("hello", null, {duration:5000});
    });
  }
```

If the code above fixes your problem, there must be some code (maybe external to your project) calling your service ouside `NgZone`.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.

(this is a canned response)
