### ISSUE TITLE
mat-select seems to be broken in iOS safari

### ISSUE THREAD

**Issue by shazmoh** [angular/material2#15058]
#### What is the expected behavior?
mat-select should be working in iOS safari as it does in other browsers

#### What is the current behavior?
Drop-down selection is not functional and also produces erroneous dropdown overlay

![screen shot 2019-02-01 at 11 28 34 am](https://user-images.githubusercontent.com/458267/52139787-159d9000-261f-11e9-9ea1-f3c5c4cd54fa.png)

![screen shot 2019-02-01 at 12 46 29 pm](https://user-images.githubusercontent.com/458267/52139941-75943680-261f-11e9-94b8-2259ade2a43e.png)

#### What are the steps to reproduce?
1. Go to mat-select documentation page using Safari browser in iPad 
2. Scroll down to the "Basic select" demo section and click on the mat-select
3. Try selecting the value from the dropdown
4. Try clicking the mat-select again and try another selection (if it works fine the first time)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest versions as used in the material docs site:
Material: 7.3.0
Angular: 7.1.4
Browser: iOS Safari

#### Is there anything else we should know?
Used a physical device to reproduce this. 
Device details:
iPad 
iOS version [11.4.1]

**Comment by crisbeto** [comment]
I wasn't able to reproduce it on an iPad with iOS 12.1.

**Comment by julianobrasil** [comment]
It's also ok with a laptop running 12.1 safari.

**Comment by shazmoh** [comment]
Seems to be working fine after the iOS update. Sorry for the distraction. We can go ahead and close this issue. Thanks for your time @crisbeto @julianobrasil
