### ISSUE TITLE
Sketch Theme Editor

### ISSUE THREAD

**Issue by Wildhammer** [angular/material2#15074]
#### Please describe the feature you would like to request.
Should be able to pass in all the things I can change through sketch theme editor(including on-primary, on-secondary text colors and corners) to theme creator

#### What is the use-case or motivation for this proposal?
One of the main reasons I became interested in this library was sketch theme editor plugin. After mocking up a bunch of screens and tweaking the colors, text colors etc. using the provided plugin I realized I can only pass in three color arguments, primary, secondary, warn and that's it(not text color for example) to either one of mat-light-theme or mat-dark-theme creators. After searching forums, blogs for hours I realized that setting text color is actually not an option although some people have found very hacky workarounds to address this(basically overriding the services in theming.scss) which kinda defeats the purpose.

#### Is there anything else we should know?
I do appreciate all the work that has been done to facilitate things for both development and design teams but the thing is I can't tell my designers go ahead and mock up the app screens with this plugin but keep in mind the implementation is going to be only 80 percent like your mock-ups.

**Comment by jelbourn** [comment]
This isn't something we plan to do in the immediate future.

**Comment by DaSchTour** [comment]
Is there any hope that why might get some more theming options beyond just changing primary and accent color and using a different font then Roboto? I really love the material design and the work that was put into this library. But some more options for individualization would be really nice.
