### ISSUE TITLE
[cdkDrag] get position from cache after removing transform value

### ISSUE THREAD

**Issue by MDzyga** [angular/material2#15084]
#### What is the expected behavior?
After set empty value in transform attribute component should begin dragging from position 0,0.

#### What is the current behavior?
Currently after setting empty value in transform attribute, drag&drop begin dragging from previous value.

#### What are the steps to reproduce?
This is our HTML:
```
<div class="background-image">
        <img #layout
             cdkDragBoundary=".background-image"
             cdkDrag
             (cdkDragEnded)="dragMoved()"
             class="qr-code-image"
             src="images/qr-code.png"
             alt="QR Code">
</div>
<mat-form-field>
        <input matInput
               placeholder="Position X"
               type="number"
               min="0"
               matTooltip="Move from left"
               [ngModel]="positionX"
               (ngModelChange)="changePosition($event, 'positionX')">
</mat-form-field>
<mat-form-field>
        <input matInput
               placeholder="Position Y"
               type="number"
               min="0"
               matTooltip="Move from top"
               [ngModel]="positionY"
               (ngModelChange)="changePosition($event, 'positionY')">
 </mat-form-field>
```
and function which 
```
dragMoved() {
	const transform: string = this.layout.nativeElement.style.transform ||
	  this.layout.nativeElement.style.webkitTransform ||
	  this.layout.nativeElement.style.mozTransform ||
	  this.layout.nativeElement.style.msTransform;

	let transformData: RegExpMatchArray = transform.match(/^translate3d\((.+)\)$/);

        if (transformData[1].includes(' translate3d(')) {
           transformData = transformData[1].split(' translate3d(');
        }

	this.positionX  = this.initialPositionX + parseFloat(transformData[1].split(', ')[0]);
	this.positionY = this.initialPositionY + parseFloat(transformData[1].split(', ')[1]);
}

changePosition(positionValue: number, changedPropertyName: string) {
	if(changedPropertyName === 'positionX') {
	  this.positionX = positionValue;
	} else {
	  this.positionY = positionValue;
	}

	this.layout.nativeElement.style.transform = this.positionY > 0 || this.positionX > 0 ?
	  `translate3d(${this.positionX}px, ${this.positionY}px, 0px)` :
	  '';
}
```
Steps to reproduce:
1) drag an image in right down corner
2) set position using inputs to left up corner (set empty value in transform attribute).
3) try to drag an image (cdk remember that his previous position was in right down corner)

Second bug is doubling translate3d value in transform attribute. 
This bug exists when I set position using saved coordinates and drag image. I set value using  **changePosition** method.

`<img _ngcontent-c18="" alt="QR Code" cdkdrag="" cdkdragboundary=".background-image" class="qr-code-image cdk-drag" src="images/qr-code.png" ng-reflect-boundary-element-selector=".background-image" ng-reflect-disabled="false" style="width: 92.61px; touch-action: none; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; user-select: none; transform: translate3d(158px, 101px, 0px) translate3d(142px, 54px, 0px);">`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
"@angular/animations": "^7.2.1",
"@angular/cdk": "^7.2.1",
"@angular/common": "^7.2.1",
"@angular/compiler": "^7.2.1",
"@angular/core": "^7.2.1",
"@angular/forms": "^7.2.1",
"@angular/http": "^7.2.1",
"@angular/material": "^7.2.1",
"@angular/platform-browser": "^7.2.1",
"@angular/platform-browser-dynamic": "^7.2.1",
"@angular/pwa": "^0.12.2",
"@angular/router": "^7.2.1",
"@angular/service-worker": "^7.2.1",
```

**Comment by crisbeto** [comment]
https://github.com/angular/material2/pull/14696 will add an API to get/set the current position.
