### ISSUE TITLE
Style mat-option of subcomponent not possible

### ISSUE THREAD

**Issue by lippoliv** [angular/material2#15088]
#### What is the expected behavior?
DEVs must be able to style subcomponents, for example `mat-option`.

#### What is the current behavior?
As of `mat-option` will be rendered in the BODY, not in the current DOM path, styling can get impossible.

For reducing code duplication, I have a SelectComponent which do wrap MatSelect. In the real application, some more business-logic will exist here.
The whole application will just use my SelectComponent.
Also I do have a HeaderComponent.
In this HeaderComponent I also do use SelectComponent, but the `mat-option`'s here should be styled differently.

#### What are the steps to reproduce?

1. https://stackblitz.com/edit/angular-jgya59
1. Try to just change the padding of the mat-options for the mat-select with green background

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Plain Stackblitz Angular project, Angular 7.2.3 + Material 7.3.1

#### Is there anything else we should know?

The `mat-option` elements will have `_ngcontent-c3` while my component, where I need to place the CSS in will have `_ngcontent-c2` (numbers can variate, but the difference will be there).

**Comment by jelbourn** [comment]
See https://material.angular.io/guide/customizing-component-styles

**Comment by JessyParis** [comment]
This is how I style mat options for now:

![Mat-option-styling](https://user-images.githubusercontent.com/44050341/60865909-53828e00-a227-11e9-87c9-7ac971e982a3.png)

CSS
`.ev-commande-fournisseur-statut-1 {
    background-color: #9F9F9F;
}
.ev-commande-fournisseur-statut-2 {
    background-color: #69B32A;
}
.ev-commande-fournisseur-statut-3 {
    background-color: #E7342F;
}
`
HTML
`<mat-select placeholder={{applicationUserContext.getCulturedRessourceText(462)}} formControlName="CommandeFournisseurStatutList" (selectionChange)="onCommandeFournisseurStatutSelected($event.value)">
                                <mat-option *ngFor="let commandeFournisseurStatut of commandeFournisseurStatutList" [value]="commandeFournisseurStatut.RefCommandeFournisseurStatut"><div [class]="'ev-commande-fournisseur-statut-' + commandeFournisseurStatut.RefCommandeFournisseurStatut">{{commandeFournisseurStatut.Libelle}}</div></mat-option>
                            </mat-select>`
