### ISSUE TITLE
pointer-events doesnt allow to set dragging item css properties like 'grab' or 'move'

### ISSUE THREAD

**Issue by kernyden** [angular/material2#15090]
#### What is the expected behavior?

'move' effect of cursor is still located to item when we leave container (cdkDropList), here is version 7.1.1 cdk
https://stackblitz.com/edit/angular-b8kjj3-r993mc?embed=1&file=app/cdk-drag-drop-overview-example.css

#### What is the current behavior?

'move' effect doesnt located to item when we  leave container (cdkDropList)
https://cdn1.savepice.ru/uploads/2019/2/5/2452e009f67846ee1b23c4a424f03110-full.png

#### What are the steps to reproduce?
https://stackblitz.com/angular/yvmnrxexppp?file=app%2Fcdk-drag-drop-connected-sorting-example.ts

start moving item off container

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 7.2.0, cdk 7.2.1, ts 3.2.2

**Comment by andreElrico** [comment]
what do you suggest? Should the cursor stay "move" all the time? Should it become "default" on drag-start?

**Comment by crisbeto** [comment]
We can't remove the `pointer-events: none`, because we use `document.elementFromPoint` to figure out the top-most element that the user is hovering over. If the dragged element had pointer events, it would always be the top-most element.

**Comment by shlomiassaf** [comment]
We know when an item starts drag and when it is dropped.

You can easily set the `cursor` of the body (or any other top-container_ to `move`, `grab` or whatever and remove it once dropped.

Because it is at the top any specific cursor will override it but that should be fine... especially if you hit places you can't drop in.

**Comment by crisbeto** [comment]
Closing the issue since we have a technical limitation that forces us to remove the pointer events and it can be worked around with current APIs.
