### ISSUE TITLE
Bug: Nested lists cause duplicated landmark roles

### ISSUE THREAD

**Issue by bsteffl** [angular/material2#15096]
#### What is the expected behavior?
Nested mat-nav-lists should not have have duplicate role="navigation".

#### What is the current behavior?
Currently if you nest lists you get multiple landmark regions of navigation for one list.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-dyyctn  

![nested-lists-extra-role](https://user-images.githubusercontent.com/10760551/52308427-e6f72080-2962-11e9-905e-fa143d8fbc28.png)  
![image](https://user-images.githubusercontent.com/10760551/52308477-0a21d000-2963-11e9-89ae-2ef101d6bab0.png)  

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.3.1

#### Is there anything else we should know?
It's unclear from documentation if you support nested lists.

**Comment by jelbourn** [comment]
IMO this is working as intended since the lists generally shouldn't be nested. That said, you can directly overwrite the `role` on nav-list.

**Comment by bsteffl** [comment]
> IMO this is working as intended since the lists generally shouldn't be nested. That said, you can directly overwrite the `role` on nav-list.

I tried change the role on the second list and it didn't seem to update it. So there isn't a way to do multiple levels of lists?

**Comment by jelbourn** [comment]
The workaround would be to set the role as a binding:
```html
<nav-list [attr.role]="'presentation'">
```

https://stackblitz.com/edit/angular-itxnos?file=src%2Fapp%2Fapp.component.html

**Comment by bsteffl** [comment]
Thank you @jelbourn that works.

**Comment by bsteffl** [comment]
This isn't an expected use case for mat-nav-list then.
```
<nav>
  <ul>
    <li><a href="javascript:void(0);">Produce</a>
      <ul>
        <li><a href="javascript:void(0);">Apples</a></li>
        <li><a href="javascript:void(0);">Oranges</a></li>
      </ul>
    </li>
    <li><a href="javascript:void(0);">Dairy</a>
      <ul>
        <li><a href="javascript:void(0);">Cheese</a></li>
        <li><a href="javascript:void(0);">Milk</a></li>
      </ul>
    </li>
  </ul>
</nav>
```

**Comment by jelbourn** [comment]
We don't support hierarchical lists since the Material Design spec didn't previously provide any guidance on what that would look like. We might explore this pattern more in the future.
