### ISSUE TITLE
Allow overriding of all component style variables

### ISSUE THREAD

**Issue by gelidus** [angular/material2#1509]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
Ability to override other variables within the components, e.g. toolbar height, list item height, etc.

#### What is the current behavior?
We are able to override colors

#### What is the use-case or motivation for changing an existing behavior?
We could customize the components to our needs.

**Comment by kara** [comment]
@gelidus You should be able to override these variables already if your `ViewEncapsulation` is turned off.  Can you add plunker repro case?

**Comment by jelbourn** [comment]
@gelidus Are you talking about sass variables? If so, there is not a good distribution mechanism for supporting this as any kind of public API short of you pulling in the scss sources and compiling all the css output yourself.

**Comment by gelidus** [comment]
Alright @jelbourn , thanks
