### ISSUE TITLE
Support derived material elements?

### ISSUE THREAD

**Issue by rcketscientist** [angular/material2#15100]
#### What is the use-case or motivation for changing an existing behavior?
I would like to extend MatTooltip to support additional styling and an optional error message.

![tooltip3](https://user-images.githubusercontent.com/4026030/52346802-6b42b580-29ee-11e9-894e-b1576fdb3e6e.gif)

#### Is there anything else we should know?
The Material elements make copious use of `private` which effectively renders them final.  Would the team be opposed to a PR making some more pliable with `protected`?  In my use-case I require a minor change to the constructor and `show`, but that requires the private `_createOverlay` which in turns ripples into almost a full code copy.  I'd love to leverage the existing maintenance and knowledge base of the core project.  Thanks!

**Comment by jelbourn** [comment]
This isn't something we plan to support in the immediate future.
