### ISSUE TITLE
Allow CSS variables in color paletts

### ISSUE THREAD

**Issue by StefanKern** [angular/material2#15107]
#### Please describe the feature you would like to request.
A color pallet has to be defined by by using COLOR values, but doesn't allow CSS variables. 

Example:
````
$sample-pallet: (
  50 : var(--color-primary), ...
````
is invalid.

#### What is the use-case or motivation for this proposal?
We have a application, where we defined the colors as CSS variables, so we can switch for  different brandings.

#### Is there anything else we should know?
Only two places are depending on the colors:

```
  .mat-calendar-body-disabled > .mat-calendar-body-selected {
    background-color: fade-out(mat-color($palette), $mat-datepicker-selected-fade-amount);
  }
```
_theming.scss 2542

```
.mat-calendar-body-disabled > .mat-calendar-body-today:not(.mat-calendar-body-selected) {
    border-color: fade-out(mat-color($foreground, hint-text), $mat-datepicker-today-fade-amount);
  }
```
_theming.scss 2603

If these lines are commented out, a `pallet` can be used with `CSS variables`. 

I know CSS variables are not supported by Internet explorer. However just changing these two lines (the calendar disables state), would allow their usage!

**Comment by jelbourn** [comment]
@mmalerba we should remove this use of `fade-out` from the calendar CSS

@crisbeto we should have something that asserts that people can successfully use css variables like this

**Comment by StefanKern** [comment]
Will this be in the next release?
