### ISSUE TITLE
FocusMonitor doesn't trigger focus on mouse interaction in Firefox and Safari

### ISSUE THREAD

**Issue by woble** [angular/material2#15105]
#### What is the expected behavior?

cdk focus classes being added to the element.

#### What is the current behavior?

Both latest (unsure about previous versions) stable Firefox and Safari seem to ignore mouse focus on an element that is monitored by FocusMonitor. Works in Chrome/Chromium. Did not test in IE/Edge.

#### What are the steps to reproduce?

Go to Material buttons demo page, inspect a button, interact with it with mouse and observe no `cdk-focused` class being added to the button element.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular - latest stable
Firefox - latest stable
Safari - latest stable

**Comment by crisbeto** [comment]
I wasn't able to reproduce it against on the latest Firefox on Windows both against the dev app and the docs site.

**Comment by woble** [comment]
What about Firefox on macOS?

**Comment by crisbeto** [comment]
Just tried it on a Mac and I could reproduce it against the docs site.

**Comment by crisbeto** [comment]
Seems to be because buttons can't receive focus on click in general due to some OS-level limitation. See https://gist.github.com/cvrebert/68659d0333a578d75372 and the links to MDN at the bottom.
