### ISSUE TITLE
cannot redeclare block-scoped variable 'module'

### ISSUE THREAD

**Issue by nadavten** [angular/material2#1510]
#### Bug
unable to compile my app after upgrading to alpha.9-3.
error in file 'typings.d.ts' saying : 

> cannot redeclare block-scoped variable 'module'

![image](https://cloud.githubusercontent.com/assets/17804204/19411185/8f32b5da-9305-11e6-8411-c11eadb63c41.png)

**Comment by jelbourn** [comment]
@nadavten Please follow the issue template.
