### ISSUE TITLE
[DragDropModule] Getting css Style of Elements

### ISSUE THREAD

**Issue by Vibrat** [angular/material2#15123]
#### Please describe the feature you would like to request.
Current [DragDropModule](https://material.angular.io/cdk/drag-drop/overview) does offer nice dragging effects but I can't find a way to export css styling that the module has changed over dragging. 

#### What is the use-case or motivation for this proposal?
The reason to export this is to get information about the previous drag so that event browser hits refreshing, user can still have their current dragging based on data saved in server side

#### Is there anything else we should know?
[DrapDrop Service](https://material.angular.io/cdk/drag-drop/api) offers create drag element when app is running. It's recommended to have a method inside this Service to export css value changed.

**Comment by crisbeto** [comment]
If I understand correctly, you want to restore the dragged position of an element if the user leaves a page and comes back? If that's the case, https://github.com/angular/material2/pull/14696 should solve it for you.

**Comment by Vibrat** [comment]
@crisbeto Yes. It solves my problems. 
__Close as it has been referred to #14696 __
