### ISSUE TITLE
please angular material datepicker hide day text

### ISSUE THREAD

**Issue by sofkaints** [angular/material2#15122]
<img width="311" alt="2019-02-08 10 41 34" src="https://user-images.githubusercontent.com/11291160/52454364-d88d4c80-2b8e-11e9-86b8-b7f740ca1b94.png">
8일 -> 8
useValue : 'ko-KR'

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
