### ISSUE TITLE
support for multiple sidenav on each side

### ISSUE THREAD

**Issue by Debananda** [angular/material2#1514]
#### Bug, feature request, or proposal:
Feature Request : To have multiple sidenav on each side as we have in angular-material1

#### What is the expected behavior?
Multiple sidenavs on each side

#### What is the current behavior?
only one sidenav per side

**Comment by jelbourn** [comment]
This feature is already present.

**Comment by Debananda** [comment]
@jelbourn : I am still getting below exception while i have more than one sidenav on rightside

 **"EXCEPTION: Error in ./AppComponent class AppComponent - inline template:1:0 caused by: A sidenav was already declared for 'align="end"'**

Code:

<md-toolbar class="portal-header">
  <button md-icon-button *ngIf="hamburgerAvailable" (click)="navClick('appNavigation')" disableRipple>
                    <i class="icon icon-lg icon-white icon-hamburger"></i>
                </button>
  <h3 flex class="app-name">{{appName}}</h3>
  <button md-icon-button disableRipple *ngIf="searchAvailable">
                    <i class="icon icon-md icon-white icon-search"></i>
                </button>
  <button md-icon-button (click)="navClick('userApps')" disableRipple *ngIf="appsAvailable">
                    <i class="icon icon-md icon-white icon-applications"></i>
                </button>
  <button md-icon-button (click)="navClick('userStories')" disableRipple *ngIf="storiesAvailable">
                    <i class="icon icon-md icon-white icon-stories_stroke"></i>
                </button>
  <button md-icon-button (click)="navClick('userNotifications')" disableRipple *ngIf="notificationsAvailable">
                    <i class="icon icon-md icon-white icon-alerts"></i>
                </button>
  <button md-icon-button disableRipple *ngIf="profileAvailable">
                    <img src="{{profilePic}}" class="img-circle profile-icon"/>
                </button>
</md-toolbar>

**Comment by jelbourn** [comment]
Oh, I misread and didn't see the "per side". I don't think this is a feature we would want to add, as it doesn't really mesh with the material design spec.

**Comment by Debananda** [comment]
ok

**Comment by xtianus79** [comment]
@jelbourn this is a feature I would most definitely want to use.  Is this possible as it is in Angular 1?  

Also, I will make this pitch as to way someone would want to use it.  The sidenav isn't a sidenav... It is a side modal panel.  Which is much more convenient to work with information and perhaps interact with it. Think form entry, quick info interaction, etc.  The dialog box shouldn't be the sole mechanism for this... In fact, sidenav should have the same or more power than mddialog.  It just makes more sense.

**Comment by POFerro** [comment]
Was looking for this feature. I'm pretty sad it is not supported in material 2. Currently I'm migrating an application from material 1 and got stuck in this because it uses two left side navs.
Is this request going to be reopened?

**Comment by rudzikdawid** [comment]
https://material.angular.io/components/component/sidenav
inside docs:
```
...
A sidenav container may contain one or two <md-sidenav> elements.
When there are two <md-sidenav> elements,
each must be placed on a different side of the container.
See the section on positioning below.
...
```

but it doesn't work
Google Music, material design app by the way... has two sidenav.
And it is very elegant solution

**Comment by willshowell** [comment]
@rudzikdawid They can't both be "start". Did you align them "start" and "end"?

**Comment by lucaslopez** [comment]
You can actually achieve something similar by including a sidebar inside another sidebar:
`        <md-sidenav-container fxFlex="1 1 100%;">

          <md-sidenav mode="side" #menuLeft (open)="closeStartButton.focus()">
            Start Sidenav.
            <br>
            <button md-button #closeStartButton (click)="menuLeft.close()">Close</button>

            <md-sidenav mode="side" #menuLeft2 (open)="closeStartButton.focus()">
              Second
              <br>
              <button md-button #closeStartButton (click)="menuLeft2.close()">Close</button>
            </md-sidenav>
          </md-sidenav>



          <md-sidenav mode="push" #menuRight align="end">
            End Sidenav.
            <button md-button (click)="menuRight.close()">Close</button>
          </md-sidenav>

          My regular content. This will be moved into the proper DOM at runtime.
          <button md-button (click)="menuLeft.open()">Open start sidenav</button>
          <button md-button (click)="menuLeft2.open()">Open start sidenav 2</button>
          <button md-button (click)="menuRight.open()">Open end sidenav</button>

        </md-sidenav-container>
      </div>`

**Comment by waterlooblue** [comment]
Instead of having multiple side panels, you can make the content within the side panel dynamic to achieve the same result.

**Comment by Broozsoft** [comment]
you can have two side bar one right and other left

     <mat-sidenav-container>

        <mat-sidenav #right position="start">
           Start Sidenav.
        </mat-sidenav>

        <mat-sidenav #left position="end">
           End Sidenav.
        </mat-sidenav>

    <div>
        <button mat-button (click)="right.open()">right</button>
        <button mat-button (click)="left.open()">left</button>
    </div>

    </mat-sidenav-container>

**Comment by evanjmg** [comment]
This is still an issue and should not be closed. Components should be flexible and dynamic especially when it comes to positioning

**Comment by oussamaABID** [comment]
inside sidenav you can use switch to show component

```ts
onToggle() {
    if ( this.openedNav) {
      this.myNav.close().then(() => {
        this.myNavType = 'small';
        this.myNav.open();
      });
    } else {
      this.myNav.open().then(() => {
      this.myNavType = 'big';
      });
    }
```

**Comment by StickNitro** [comment]
I cam across this issue today in an app I am working on, I am creating a settings UI which has a nav list in the drawer content and each button in the nav list opens its own corresponding drawer.  I have three drawers and they all work with `position="end"` with the only drawback being the error that I get in the console

@waterlooblue mentioned making the content of the sidebar dynamic which is interesting, does this mean loading the component using the `ComponentFactoryResolver`?

**Comment by jwa107** [comment]
We have a use case where we have a left nav menu that opens up a panel when certain menu items are clicked. We did this using nested containers, where every container just has one side-nav (demo link: https://stackblitz.com/edit/angular-hpgcjr?file=app%2Fsidenav-overview-example.html)

The content in our panel also needs to be dynamic, so we just swap out what we render in there when certain items are clicked giving the illusion of there being even more panels.

**Comment by waterlooblue** [comment]
@StickNitro what I meant was the content inside the sidenav changes depending on what triggers it to open. So I only have one mat-sidenav but the component that shows inside changes.
