### ISSUE TITLE
Disable Sort for multi select

### ISSUE THREAD

**Issue by manasarora119** [angular/material2#15142]
How to get list of data from multi select dropdown  in same order in which user chooses .

Currently list gets sorted ,how to override / disable this sort functionality

**Comment by ViktorSlavov** [comment]
@manasarora119 
You can use the `sortComparator` input to pass a custom sorting function that is [called when sorting](https://github.com/angular/material2/blob/master/src/lib/select/select.ts#L967) the selected values.

[Here is a stackblitz example](https://stackblitz.com/edit/mat-select-sortcomparator?file=app%2Fselect-multiple-example.ts)

**Comment by manasarora119** [comment]
@ViktorSlavov  ,
Great   , it works fine . 


Thanks for your quick response
