### ISSUE TITLE
Mat-Stepper horizontal and vertical as directive

### ISSUE THREAD

**Issue by Rapiiidooo** [angular/material2#15143]
#### Please describe the feature you would like to request.
The feature would be to group them in one component and add a new directive to change the orientation of the mat-stepper. (Like slider and divider for example)

#### What is the use-case or motivation for this proposal?
As the title explain, there are mat-stepper-vertical and mat-stepper-horizontal components, what I am requesting would be more intuitive and really faster to switch between vertical and horizontal for responsive design.

#### Is there anything else we should know?
Nothing, except thanks to all contributors of this project, you are amazing and keep going :)

**Comment by crisbeto** [comment]
See https://github.com/angular/material2/pull/9173.
