### ISSUE TITLE
[sidenav @alpha 9] Regression in styling: sidenav positioning is no longer fixed

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#1515]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

`md-sidenav` should remain visible (fixed) even as the user scrolls down the `md-sidenav-layout`.  This is how `alpha 7 or 8` worked.
#### What is the current behavior?

`alpha 9` has regressed. Now, when a user scrolls down to reveal more `md-sidenav-layout` content, `md-sidenav` goes off the page.

At top of the page; sidenav open:

![1](https://cloud.githubusercontent.com/assets/12346501/19466401/9c19fda6-94d8-11e6-9455-10dbe911f027.png)

After scrolling down; sidenav open:

![2](https://cloud.githubusercontent.com/assets/12346501/19466407/a24b3f6e-94d8-11e6-9007-939f2c664c33.png)
#### What are the steps to reproduce?
- [open this plunker](http://plnkr.co/edit/n2tscYvP3jrQwOuvF8kJ?p=preview)
- scroll down the page
- open the sidenav
- the side menu is not visible.
#### What is the use-case or motivation for changing an existing behavior?

the `md-sidenav` typically shows a menu or other content that should be visible whenever the panel opens. Currently, the user experience is very poor: the user thinks the site is broken when she opens the sidenav and sees no content (scrolling up is required to reveal the content)
#### Which versions of Angular, Material, OS, browsers are affected?

Early alphas had this problem, but it was fixed probably around `alpha 5`. There has been a regression and I noticed the problem on `alpha 9-3` on `Firefox 49`

**Comment by jelbourn** [comment]
@hansl might need some discussions about how we want scrolling to work with sidenav

**Comment by mischkl** [comment]
This is definitely an issue, and seems to be duplicated by #2416, #1793 and #2033 (and maybe more...). To be honest I'm not sure why anyone would want a sidebar where the navigation scrolls away simultaneously with the content - whereas the use case for keeping the sidebar fixed while scrolling the content seems universal. This is an issue which clearly has a lot of community demand and should be highly prioritized IMHO.

**Comment by PrazSam** [comment]
I just fixed it following the accepted answer of this [stackoverflow question](http://stackoverflow.com/questions/39683548/sticky-mdtoolbar-inside-mdsidenavlayout) . Have a look. This can be used as a workaround for the moment.
