### ISSUE TITLE
MatTree examples not applying material styling

### ISSUE THREAD

**Issue by Helveg** [angular/material2#15163]
#### What is the expected behavior?
I'm trying to recreate the examples found here https://material.angular.io/components/tree/overview

#### What is the current behavior?
The examples all behave strange: The nested tree example shows only top level chevrons, not even node names and appears unstyled. The flat architecture does list all nodes but still looks unstyled.
![image](https://user-images.githubusercontent.com/28923979/52647273-af4d2300-2ee4-11e9-82f1-12c4bd72d777.png)

#### What are the steps to reproduce?
The issue is not reproducible in StackBlitz.
* Initialize new Angular project: `ng new mat-test`
* Angular Routing: Y
* Stylesheets: SCSS
* `ng add @angular/material`
* Indigo/Pink theme
* HammerJS: Yes
* Copy paste example code into a new component (TS & HTML code)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7

#### Is there anything else we should know?
I first got a yellow notification in the console about a missing stylesheet, but the ng add command did import the indigo theme stylesheet into angular.json's styles array.

**Comment by andrewseguin** [comment]
The example uses `<button mat-icon-button>` and it looks like you may not have imported the `MatButtonModule` which would bring in the correct styles.

Try adding `MatButtonModule` to your module:

```ts
...
import {MatButtonModule} from '@angular/material';

@NgModule({
  ...
  imports: [
    ...
    MatButtonModule,
  ],
})
export class AppModule { }
```

If this doesn't work, feel free to open the issue again
