### ISSUE TITLE
[docs] Mention how ton include Material components in sub modules

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/material2#1516]
#### Bug, feature request, or proposal:
The Getting Started guide (and the sample app) just mentions to include MaterialModule.forRoot() in the app root module. But no serious app will have only one module, and with Angular we have to include again each components we need in each submodule. So docs should mention how to properly include the Material components we need in a sub module.

#### What is the current behavior?
For now I included "MdButtonModule" and others (without forRoot()) in submodules, but not sure it's the right way to do.

#### Which versions of Angular, Material, OS, browsers are affected?
Material alpha 9

**Comment by fxck** [comment]
Yes, that is the right way. But it's simply how angular works, nothing specific to material2.

**Comment by cyrilletuzi** [comment]
@fxck Yes but that's not intuitive : usually modules which need re-import in sub modules (like the Router) use the forChild() method (as opposed to forRoot()), not a direct import.

**Comment by SamiAl90** [comment]
Since alpha.9 u just import MaterialModule with forRoot() in ur AppModule afaik.
https://github.com/angular/material2/blob/master/GETTING_STARTED.md

Then again the MaterialModule, in the submodules of ur application but w/o forRoot()

**Comment by cyrilletuzi** [comment]
@SamiAl90 Is there a reason it's not following the forChild() convention ?

**Comment by fxck** [comment]
`forChild` is not a convention, it literally means that you are passing it child routes, no root routes.

**Comment by cyrilletuzi** [comment]
[Angular ngModule doc](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-for-root) :

> forRoot and forChild are conventional names for methods that deliver different import values to root and feature modules. Angular doesn't recognize them but Angular developers do.
> 
> Follow this convention if you write a similar module that has both shared declarables and services.

Then in the FAQ : 

> forRoot and forChild are conventional names for methods that configure services in root and feature modules respectively.

I work with Angular 2 since one year and no other modules are doing it like Material. Simple modules (like CommonModule) are imported directly, and modules that need to be reimported in every submodule for including components without providing again the same services (like the RouterModule) use the forRoot() / forChild convention.

I've seen no other modules needing to import forRoot() in the app module and then the module itself in child modules. If it's counter intuitive for someone used to Angular 2, it will be even more confusing for beginners. And I think ngModule are confusing enough for beginners without adding to it.

**Comment by jelbourn** [comment]
The `forRoot` is used because the modules add providers. Without some way of importing without those providers, they would get clobbered from doing lazy loading. I'm not 100% a fan of the `forRoot` as it is now though; we might change it later on based on feedback.

**Comment by johnking** [comment]
Hi @jelbourn, @fxck and others, 

  I have some challenges to use `material2` at _feature_ modules.

  I have __no issues__ to import `material2`  into my main module and use `material2` components in my own components defined in _main_ module. 

`app.module.ts`
```
@NgModule({
  imports: [
    BrowserModule,
    MaterialModule.forRoot(),
    AppRoutingModule,    
    KepanModule
  ],
```
 but in my _feature_ module,  __I have to import each individual material2 component module__ in order for Angular2 to recognize the material2 directives, even I have imported `MaterialModule`! 

  For example, in my feature module definition file, 

`kepan.module.ts`
```
@NgModule({
  imports: [
    CommonModule,
    MaterialModule,
    KepanRoutingModule,
    MdToolbarModule
  ],
  declarations: [
    KepanComponent
  ],
  providers: [
    KepanData
  ]
})
export class KepanModule {}
```

  If I only import `MaterialModule`,  then `angular2` does not recognize `toolbar` related directives/components.

   But in `main` module, I only need to import `MaterialModule.forRoot()` without importing any individual module. 

  I wonder why? and how to import all the material2 directives with a single import at feature module? 

thanks a lot for any suggestions and comments. 

-John

**Comment by asadsahi** [comment]
having same issue. I have import MaterialModule.forRoot() in app.module and then imported MaterialModule in a SharedModule. SharedModule is imported in each lazy loaded module, but getting error for all directives/components used in that lazy module:

![image](https://cloud.githubusercontent.com/assets/3470892/24497140/5cc95a86-1532-11e7-81ba-0aa1f91c689c.png)

Difficult to find an example online with some lazy loading routes and multiple pages. material2-app app by @jelbourn is using just app component. Can anyone ponit to an example which is using material 2 in multiple pages with lazy loaded routes scenario?

Thanks

**Comment by jelbourn** [comment]
* Every component lives in exactly one NgModule (there one where it's in `declarations`).
* Any component that uses another component must have an import to the latter in the module where it lives.

**Comment by asadsahi** [comment]
@jelbourn 

> Any component that uses another component must have an import to the latter in the module where it lives.

Thats what I was trying to achieve by importing MaterialModule in a SharedModule and and then immediately exporting from shared. But when I tried to import shared in every lazy module. application was hanging. Tried hard to find an example online which has one lazy module and showing material working.

Any pointers for an example?

**Comment by dahaupt** [comment]
@asadsahi But it's working for non-lazy modules and its components? I have a similar structure with a SharedModule which imports `MaterialModule` and it's working fine, but I have not tested lazy-loading yet.

**Comment by kanjareeyalalji** [comment]
same issue i have imported in app.module.ts however also need to import in child module.
