### ISSUE TITLE
The ESC key is never documented

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/material2#15165]
#### What is the expected behavior?

Most docs have a section _Keyboard interaction_, which should contain all keyboard controls.

#### What is the current behavior?

I've noticed that the key ESC is missing from all of them (at least according to the search `<kbd>ESC</kbd>` project-wise).

#### What are the steps to reproduce?

Use the power of thy eyes: https://material.angular.io/components/autocomplete/overview#keyboard-interaction

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

N/A.

#### Is there anything else we should know?

I could go through all docs and add the ESC item whenever it's relevant, but I want to check firstly if it's omitted on purpose. Can't find anything in previous issues about it.

**Comment by andrewseguin** [comment]
Hey @lazarljubenovic, thanks for spotting this and offering to help. I don't think we left it out intentionally. We'd definitely appreciate a pull request that would improve our docs here. Thanks!
