### ISSUE TITLE
bug(native select) when option value is object

### ISSUE THREAD

**Issue by mattiacorci** [angular/material2#15178]
#### What is the expected behavior?
When using a `<select>` like this:
```html
<select […]>
    <option *ngFor="let item of itemList" [value]="item">{{item.label}}</option>
</select>
[…]
```
The selected value shoud be the entire item object, as I got using a `<mat-select>` element.

#### What is the current behavior?
Instead of this, I'm getting `[object Object]`.
![image](https://user-images.githubusercontent.com/6996137/52726132-d96d1680-2fb2-11e9-92bc-436d600c1b27.png)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ru5igp?file=app/select-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Using Chrome or Firefox on Windows 7.
![image](https://user-images.githubusercontent.com/6996137/52726172-f1dd3100-2fb2-11e9-826e-0d18bdd4d9cc.png)

**Comment by crisbeto** [comment]
This is how the native HTML select works, Material doesn't do anything to it apart from styling. Alternatively, you can use `mat-select` which supports object values.
