### ISSUE TITLE
Portal overview Stackblitz not working (Needs `PortalModule`)

### ISSUE THREAD

**Issue by swseverance** [angular/material2#15175]
#### What is the expected behavior?
The Stackblitz example should work

#### What is the current behavior?
The example fails to compile.

#### What are the steps to reproduce?
1. Visit https://material.angular.io/cdk/portal/overview#portals
2. Click the [Edit in Stackblitz link](https://stackblitz.com/angular/ggebemmmbkv?file=app%2Fcdk-portal-overview-example.ts)
3. Observe the compilation error

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "7.3.1"

#### Is there anything else we should know?
Adding `PortalModule` to the example's material module appears to resolve the issue.

**Comment by RekiDunois** [comment]
I have this problem to, it said `Can't bind to 'ngif' since it isn't a known property of 'mat-sidenav-container'.`
I use [this](https://stackblitz.com/angular/plqkbovbaqv?file=material-module.ts) stackblitz link to Edit, and other example in angular material also not work in stackblitz too.

**Comment by swseverance** [comment]
@jelbourn I've submitted angular/material.angular.io#582
