### ISSUE TITLE
Rename material2 to material in order to be semver compliant ?

### ISSUE THREAD

**Issue by maxime1992** [angular/material2#1517]
#### Bug, feature request, or proposal:
Proposal

#### What is the use-case or motivation for changing an existing behavior?
Angular is now using semver and angular V3 is on his way (6 months I heard).

from http://angularjs.blogspot.fr/2016/09/angular2-final.html :
>**Semantic Versioning**
We heard loud and clear that our RC labeling was confusing. To make it easy to manage dependencies on stable Angular releases, starting today with Angular 2.0.0, we will move to semantic versioning.  Angular versioning will then follow the MAJOR.MINOR.PATCH scheme as described by semver:
the MAJOR version gets incremented when incompatible API changes are made to stable APIs,
the MINOR version gets incremented when backwards-compatible functionality are added,
the PATCH version gets incremented when backwards-compatible bug are fixed.

It will be weird to have != names between angular and his library (angular 3 and material2 ?).

**Comment by RoxKilly** [comment]
`material2` was never part of the library's name, although it is in that folder on `github`.  With `alpha 9`, the library moved from [`@angular2-material`](https://www.npmjs.com/~angular2-material) to simply [`@angular/material`](https://www.npmjs.com/package/@angular/material)

**Comment by jelbourn** [comment]
The `2` in the github repo isn't going away, and it's already gone from the package names.

**Comment by maxime1992** [comment]
I guess I can now consider that solved :stuck_out_tongue: 

![image](https://user-images.githubusercontent.com/4950209/60801206-87e64380-a16e-11e9-959c-5b04b88e54f4.png)
