### ISSUE TITLE
Property 'steps' does not exist

### ISSUE THREAD

**Issue by chr1soscl** [angular/material2#15186]
I recently installed @angular/material version 7.3.2 and I am trying to build my project for production:
ng build --prod

but and I keep getting this error:
ERROR in node_modules\@angular\material\stepper\typings\index.d.ts.MatHorizontalStepper.html(1,68): : Property 'steps' does not exist on type 'MatHorizontalStepper'. Did you mean '_steps'?

node_modules\@angular\material\stepper\typings\index.d.ts.MatHorizontalStepper.html(1,1033): : Property 'steps' does not exist on type 'MatHorizontalStepper'.
Did you mean '_steps'?

node_modules\@angular\material\stepper\typings\index.d.ts.MatVerticalStepper.html(1,23): : Property 'steps' does not exist on type 'MatVerticalStepper'. Did you mean '_steps'?

**Comment by macjohnny** [comment]
https://github.com/angular/material2/blob/9ca5722d68274b7548ea0c20a7dd0031e6c7e317/src/cdk/stepper/stepper.ts#L257-L260

https://github.com/angular/material2/blob/9ca5722d68274b7548ea0c20a7dd0031e6c7e317/src/lib/stepper/stepper.ts#L87

https://github.com/angular/material2/blob/9ca5722d68274b7548ea0c20a7dd0031e6c7e317/src/lib/stepper/stepper.ts#L148

which is correctly used here
https://github.com/angular/material2/blob/9ca5722d68274b7548ea0c20a7dd0031e6c7e317/src/lib/stepper/stepper-horizontal.html#L2

@chr1soscl are you sure you also updated `@angular/cdk` to version `7.3.2`?
a created a dummy project with a horizontal stepper with `@angular/material@7.3.2` and `@angular/cdk@7.3.2` (`@angular/cli@7.3.1`, `@angular/devkit/build-angular@0.13.1`) and running `ng build --prod` successfully works without the issue you described.

**Comment by chr1soscl** [comment]
@macjohnny thank you very much. I believe this will fix my issue, I will test it this evening.
