### ISSUE TITLE
Tree-table view

### ISSUE THREAD

**Issue by AlexLvovsky** [angular/material2#15187]
I would like to have a tree-table view, that all the below logic will be inside.
Features:
expand/collapse rows
sort by level

Something like this
![image](https://user-images.githubusercontent.com/3778760/52776585-9b233600-304a-11e9-8ecf-662496a6f98c.png)

**Comment by andrewseguin** [comment]
You should be able to do this using the table currently, and to make it easier you can use the `TreeControl` to help you traverse your data and manage expansion state

https://stackblitz.com/edit/angular-m77g7e-semvxp?file=app%2Ftable-basic-example.html

**Comment by AlexLvovsky** [comment]
@andrewseguin 
This is great, but how can I sort this table by column?

**Comment by andrewseguin** [comment]
If you want more functionality, I recommend putting in the `MatSort` and listening for its events to sort the data that you provide to the data source. We do not have plans to add a tree data source that sorts each level by a particular column.
