### ISSUE TITLE
Can't reset Mat Radio Button

### ISSUE THREAD

**Issue by izmaylovdev** [angular/material2#15180]
#### What is the expected behavior?
Button must be unchecked after click on it twice (look at stackblitz).

#### What is the current behavior?
Model set to 'null' but button is still display as checked.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-mx7uc8?file=app/radio-ng-model-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
  "@angular/cdk": "7.3.1",
    "@angular/core": "7.2.4",
    "@angular/http": "7.2.4",
    "@angular/forms": "7.2.4",
    "@angular/common": "7.2.4",
    "@angular/router": "7.2.4",
    "@angular/compiler": "7.2.4",
    "@angular/material": "7.3.1",
    "web-animations-js": "2.3.1",
    "@angular/animations": "7.2.4",
    "@angular/platform-browser": "7.2.4",
    "angular-in-memory-web-api": "0.5.4",
    "@angular/material-moment-adapter": "7.3.1",
    "@angular/platform-browser-dynamic": "7.2.4"

**Comment by Iamakr** [comment]
@izmaylovdev radio button is working as expected. However if you need to reset the radio button. You can use either of the following functions to achieve the same.
1. `  setValue(event, season) {
    event.preventDefault()
    if (this.favoriteSeason === season) {
      this.favoriteSeason = null; 
      this.favoriteSeason = null;
    } else {
      this.favoriteSeason = season;
    }
  }`
2. `  setValue(season) {
    if (this.favoriteSeason === season) {
      this.favoriteSeason = null; 
      setTimeout(() => this.favoriteSeason = null, 0)
    } else {
      this.favoriteSeason = season;
    }
  }`

you can check the updated code here [updated stackblitz code ](https://stackblitz.com/edit/angular-mx7uc8-8jixsc)

**Comment by jelbourn** [comment]
This is working as intended. The behavior matches the native `<input type="radio">`

(because it _is_ a native radio button under the hood)
