### ISSUE TITLE
Bottom sheet scss not used?

### ISSUE THREAD

**Issue by uahic** [angular/material2#15199]
#### What is the expected behavior?
Bottom sheet container.ts should include the bottom-sheet-container.scss

#### What is the current behavior?
It uses ´css´ as extension, I assume thats a typo

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
The current master branch

**Comment by crisbeto** [comment]
It's not a typo. The `.scss` file ends up being transpiled to `.css` which is then used.
