### ISSUE TITLE
bug(typography): custom letter-spacing is not taking into account

### ISSUE THREAD

**Issue by jedjebari** [angular/material2#15197]
#### What is the expected behavior?
Typography levels should apply custom letter-spacing defined in mat-typography-level() function when a custom typography is created

#### What is the current behavior?
letter-spacing is hardcoded in each level. Example : 
`.mat-display-4, #{$selector} .mat-display-4 {
    @include mat-typography-level-to-styles($config, display-4);
    margin: 0 0 56px;
    letter-spacing: -0.05em;
  }
`

#### What are the steps to reproduce?
Create a custom typo with letter-spacing defined at any level :
`  
$display-4: mat-typography-level(86px, 86px, 400, $my-super-font, 2.2px),
`
The letter spacing is still -0.05em

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm on : 
Angular 7.2.4 
Angular Material 7.3.1
Typescript 3.2.4
MacOS 10.13.6

**Comment by MicMicMon** [comment]
stumbled on this too, but the fix has not made it to the release.

Would it be possible to get that in the next release?
