### ISSUE TITLE
Partial prints from fullscreen sidenavs

### ISSUE THREAD

**Issue by nkholski** [angular/material2#1520]
#### Bug, feature request, or proposal:

Bug: Only visible the visible part of the page is printed (as in ctrl+p) when the content is in a sidenav with a fullscreen attribute (`<md-sidenav-layout fullscreen>`)
#### What is the expected behavior?

To be able to print the complete contents regardless of "fullscreen" property (To get the same result with `<md-sidenav-layout fullscreen>`as with  `<md-sidenav-layout>`).
#### What is the current behavior?

One page is printed, only the content visible on screen.
#### What are the steps to reproduce?

http://plnkr.co/edit/lYPHtQjmaLDrCkmRC6J2
1. Open in separate window and press "ctrl+p" => Only one page.
2. Remove "fullscreen" in `<md-sidenav-layout fullscreen>` in app.component.html, press "ctrl+p" => All content on multiple pages
#### What is the use-case or motivation for changing an existing behavior?

I want to print it ALL :-)
#### Which versions of Angular, Material, OS, browsers are affected?

Tested with Angular 2.1.0, material2 alpha-9.3, Chrome 52.0.2743.116, Ubuntu 16.04
#### Is there anything else we should know?

Having a great time developing with Angular 2 / Material 2.

**Comment by RoxKilly** [comment]
@nkholski is the `fullscreen` attribute specific to `Material`? I'd like to learn about it, but there is no reference to it in [the `sidenav` docs](https://github.com/angular/material2/blob/master/src/lib/sidenav/README.md).

**Comment by jelbourn** [comment]
We're considering replacing the `fullscreen`attribute with something else.

**Comment by nkholski** [comment]
@RoxKilly Someone correct me if I'm wrong but I think it's a custom attribute and not a a part of the HTML-standard.

**Comment by matt1** [comment]
Same issue for me - I was only printing the "viewable" region.  Some fiddling around led to this work-around that you can add to your CSS:

```css
@media print {
  .md-sidenav-content {
    height: initial !important;
  }
```

Bit hacky but does the trick for now.

**Comment by jelbourn** [comment]
@mmalerba is this still a thing?

**Comment by mmalerba** [comment]
`fullscreen` attribute is gone now, https://material.angular.io/components/component/sidenav shows recommended approach for fullscreen sidenav
