### ISSUE TITLE
A question on z-index measurements

### ISSUE THREAD

**Issue by cary-smith** [angular/material2#15204]
#### What is the expected behavior?
Z-index settings of components should match the DP concept from the [Material Design Elevations](https://material.io/design/environment/elevation.html#default-elevations)

#### What is the current behavior?
Without checking all the available elements, a Dialog is supposed to have a DP of 24. The current angular design has it at 1000. 

#### What are the steps to reproduce?
Open the dialog in the documentation and check the z-index value of the component. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.3.1, likely others

#### Is there anything else we should know?
Nope. I am ok if you choose to tell me to go fly a kite, but we are building web components that match the specifications to the best of our abilities. For developers that use our components along with angular material, this can cause some consternation since our autocomplete component has a body-attached popup that sits at a z-index of 24. We can set it higher, but this creates a brittleness should you choose to change the elevations on yours. 

I am curious what might be a our best options for both maintaining the spec (at least in spirit) and remain easily inter-operable with libraries that are also intended to be compatible to the specification? 

Any help is appreciated. Thanks!

**Comment by crisbeto** [comment]
The elevation refers to the size/spread of the `box-shadow` of an element, not the `z-index`.

**Comment by cary-smith** [comment]
I am OK with that reading though I disagree. Why use a DP at all when talking about the differing heights since they use it as an actual measurement everywhere else in the documentation.

**Comment by cary-smith** [comment]
May be related to https://github.com/angular/material/issues/8475

**Comment by jelbourn** [comment]
For now this is working as intended. We interpret the spec to only apply to the shadows.
