### ISSUE TITLE
mat-paginator doesn't work on top of page

### ISSUE THREAD

**Issue by rever96** [angular/material2#15203]
#### What is the expected behavior?
I want to use the mat-paginator tag on top of my content to show up

#### What is the current behavior?
The paginator go to next page for the first time (but it show always to be on the first one), then I can click on the next page icon and it reload the same items (the seconds one) and I can't click on the previous page icon because it is disabled.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using Angular 7

#### Is there anything else we should know?
If i move the paginator to bottom page it works without issues

**Comment by rever96** [comment]
I noticed that the problem doesn't regard of the position of mat-paginator, but it is broke when there is an *ngIf on it or it's parent.
So I've solved making permanent visible the paginator even when data is loading.
Should I close the git issue?

**Comment by andrewseguin** [comment]
You are probably setting the `MatPaginator` on your data source after `ngOnInit`, but it's undefined since the `ViewChild` is not filled in until `ngAfterViewInit`.
