### ISSUE TITLE
cdk-drop-list-dragging not removed when exiting drop area

### ISSUE THREAD

**Issue by kyashan** [angular/material2#15233]
#### Bug, feature request, or proposal:
 Bug

#### What is the expected behavior?

Cdk-drop-list-dragging class should be removed when the pointer leaves the target container area.
When the dragged element is dropped outside a target container after passing over it should return the source container as result

#### What is the current behavior?

I'm implementing a drag & drop from one container to multiple drop areas: when entering these areas I want to highlight these areas by using cdk-drop-list-dragging class, but once exiting one area, the class is not removed. Also, I've noticed that dropping an element outiside a drop area, the element gets assigned to last visited drop area, even if pointer is not there anymore.

#### What are the steps to reproduce?
![Alt Text](https://raw.githubusercontent.com/kyashan/Utils/master/2019-02-19%2018.19.20.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/animations": "^7.2.4",
    "@angular/cdk": "^7.3.2",
    "@angular/common": "^7.2.4",
    "@angular/compiler": "^7.2.4",
    "@angular/compiler-cli": "^7.2.4",
    "@angular/core": "^7.2.4",
    "@angular/fire": "^5.1.1",
    "@angular/forms": "^7.2.4",
    "@angular/http": "^7.2.4",
    "@angular/material": "^7.3.2",
    "@angular/platform-browser": "^7.2.4",
    "@angular/platform-browser-dynamic": "^7.2.4",
    "@angular/platform-server": "^7.2.4",

**Comment by crisbeto** [comment]
I wasn't able to reproduce [the issue here](https://stackblitz.com/edit/angular-8jcl5s). Note that the item is still considered part of a drop list until it gets dragged into a different list.

**Comment by volser** [comment]
I'm getting error all time [here](https://stackblitz.com/edit/angular-8jcl5s)
http://recordit.co/3j2iS4IJ6I
```
Error in /turbo_modules/@angular/cdk@7.3.1/bundles/cdk-drag-drop.umd.js (1829:54)
Cannot read property 'clientRect' of undefined
```

**Comment by volser** [comment]
@crisbeto https://stackblitz.com/edit/angular-8jcl5s-ycs362

**Comment by volser** [comment]
d&d is not working very well with `changeDetection: ChangeDetectionStrategy.OnPush` (
