### ISSUE TITLE
Doc examples are overly complex

### ISSUE THREAD

**Issue by EvanCarroll** [angular/material2#15230]
#### What is the expected behavior?

A copy of the html and API tab (which includes the import) should work and render with proper styles.

#### What is the current behavior?

The button from the example in the menu is unstyled because it requires you to implement the mat-button component which is only documented on the button tab.

I found this confusing myself (the assumption that we would know to include the button component). You can see my question on SO here https://stackoverflow.com/q/54720016/124486

**Comment by jelbourn** [comment]
We have some long term plans to revamp the content on the docs site, but for now it assumes knowledge that you have to import the `NgModule` for a component before using it.
