### ISSUE TITLE
mat-selection-list defaults to accent color and cannot be set to primary

### ISSUE THREAD

**Issue by Admiralfeb** [angular/material2#15234]
#### What is the expected behavior?
I should be able to control the color of the checkboxes of the mat-selection-list

#### What is the current behavior?
The color is set to accent only and does not permit me to change it via a color property. The [documentation](https://material.angular.io/components/list/overview#selection-lists) does not state that the color is set to accent

#### What are the steps to reproduce?
Provided stackblitz shows the issue.
https://stackblitz.com/edit/angular-material2-issue-fvzopz

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.3.2
Node: 11.9.0
OS: win32 x64
Angular: 7.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.2
@angular-devkit/build-angular     0.13.0
@angular-devkit/build-optimizer   0.13.0
@angular-devkit/build-webpack     0.13.0
@angular-devkit/core              7.3.2
@angular-devkit/schematics        7.3.2
@angular/cdk                      7.3.2
@angular/cli                      7.3.2
@angular/material                 7.3.2
@ngtools/webpack                  7.3.0
@schematics/angular               7.3.2
@schematics/update                0.13.2
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

**Comment by mkurcius** [comment]
When this will be released?
There were 3 releases since 22 Feb (merge date) :)

**Comment by mmoussikhine** [comment]
There is still a problem here. If the parent component has *mat-primary* class set (like *mat-tab-group* does by default), then changing color to *accent* on *mat-selection-list* or *mat-list-option* has no effect, since *mat-accent* is never explicitly set as only *primary* and  *warn* values are checked:
```
    ...
    '[class.mat-primary]': 'color === "primary"',
    '[class.mat-warn]': 'color === "warn"',
    ...
```
