### ISSUE TITLE
MatMomentDateModule: year is not filled with actual year

### ISSUE THREAD

**Issue by andrewinkler1** [angular/material2#15246]
#### What is the expected behavior?
When I enter 1.1.5 in the datapicker, the date should be 01.01.2005. This works with the native date adapter but not with the moment date adapter.

#### What is the current behavior?
1.1.5 -> 01.01.0005

#### What are the steps to reproduce?
Test it with 1.1.5 on the angular matrial page: https://material.angular.io/components/datepicker/overview
under: Datepicker that uses Moment.js dates

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Version 6 and above

**Comment by crisbeto** [comment]
Material doesn't really do anything to the date. It just takes the value, passes it to Moment, and renders the result. If you want to customize the logic for how it is formatted, you can create your own date adapter that extends the `MatMomentDateAdapter`.
