### ISSUE TITLE
Native control appears below md look/skin

### ISSUE THREAD

**Issue by doorman02** [angular/material2#1525]
![image](https://cloud.githubusercontent.com/assets/4180567/19516883/76b0e7ce-95fe-11e6-9103-2298d8765310.png)

#### Bug, feature request, or proposal:
I have a strange bug, the native radiobutton control appears below the material design look. See image.
This happens after updating to the latest @angular/material package
"@angular/material": "2.0.0-alpha.9-3",
Any idea what may be causing this to happen?

#### What is the expected behavior?
The native control should be hidden

#### What is the current behavior?
The native control is not hidden

#### Which versions of Angular, Material, OS, browsers are affected?
Latest Chrome, Angular 2.1.0, "@angular/material": "2.0.0-alpha.9-3",

**Comment by 0x4F72** [comment]
sounds pretty similar to #1411 
do you have any of the themes included?

**Comment by doorman02** [comment]
Thanks, this was the problem....

**Comment by 0x4F72** [comment]
Fine, then please close this issue.
