### ISSUE TITLE
mat-select calculated tabindex ignored

### ISSUE THREAD

**Issue by robmass94** [angular/material2#15282]
#### What is the expected behavior?
Tabindex should be set to calculated value

#### What is the current behavior?
Tabindex is set to 0

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/edit/angular-ahlxa1

When tabbing from the first select, I expect to go to the third select, then the second, and then the fourth. However, it's just going in order, since the tabindex is being to set 0.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.3

**Comment by crisbeto** [comment]
You should bind to `tabIndex`, rather than `tabindex`. [Here's a working example](https://stackblitz.com/edit/angular-grg56y).

**Comment by robmass94** [comment]
> You should bind to `tabIndex`, rather than `tabindex`. [Here's a working example](https://stackblitz.com/edit/angular-grg56y).
Ah, I should've realize that. Thank you for your help. I'm curious why tabindex was not chosen as the input name for consistency?

**Comment by crisbeto** [comment]
It was chosen so that it matches with the property on a native DOM node which is also `tabIndex`.
