### ISSUE TITLE
Mat-option div being generated dynamically outside app-root and dropdown appears at the bottom of the page

### ISSUE THREAD

**Issue by subhroneeldey** [angular/material2#15287]
I am using autocomplete as mentioned in the docs and using a service i am populating my data for the dropdown which is reading from a json. The problem i face is while the UI is populated the dropdown appears at the bottom of the page and the div of mat-option is being loaded outside app-root. I tried to find the fix from many sources but was not able to resolve. Would appreciate some help. One bad practice i have followed is that all the UI code is in the app.component.

**Comment by crisbeto** [comment]
This sounds like you haven't included a theme. You can see the ["Include a theme" step in the "Getting started" guide](https://material.angular.io/guide/getting-started#step-4-include-a-theme).
