### ISSUE TITLE
Console error when using arrow keys in a mat-select with a mat-option without value.

### ISSUE THREAD

**Issue by ClementChangenot** [angular/material2#15312]
#### What is the expected behavior?
When selecting a "no value" or "null value" mat-option with keyboard, no error appears in the console output.

#### What is the current behavior?
When selecting a "no value" or "null value" mat-option with keyboard, an error appears in the console output.

> main.5b2eef94be108354fa6e.js:1 ERROR TypeError: Cannot read property 'viewValue' of undefined

NB : no problem when selection is done with mouse click.

#### What are the steps to reproduce?
Error is appearing in angular material documentation web site : 
https://material.angular.io/components/select/overview#getting-and-setting-the-select-value

1. Open browser console
2. Select "Option 1" with mouse
3. Use up arrow key to select the "empty mat-option" (None)
4. Look the console output

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7
Material 7.3.1
Tested with Chrome and firefox

#### Is there anything else we should know?

**Comment by crisbeto** [comment]
Will be fixed in the next release by https://github.com/angular/material2/pull/15160.
