### ISSUE TITLE
CdkDropListGroupDisabled Blocking Native Interactions

### ISSUE THREAD

**Issue by DavidMarquezF** [angular/material2#15319]
#### What is the expected behavior?

That `cdkDropListGroupDisabled` directive disabled all the `cdkDrag` components but kept the scrolling behaviour.

#### What is the current behavior?

Native Input not working when using `cdkDropListGroupDisabled`. The disabled effect works, because you can't drag any cdkDrag component. 

Looking at the source code I found that this happened in this function:
https://github.com/angular/material2/blob/740a2eeaa921c201c21b7a0fee980cf05ad7c2aa/src/cdk/drag-drop/drag-ref.ts#L965-L976

Which will call this function:

https://github.com/angular/material2/blob/740a2eeaa921c201c21b7a0fee980cf05ad7c2aa/src/cdk/drag-drop/drag-styling.ts#L47-L59

It adds to the style of the component `touch-action: none` when the enabled parameter is false.

Then I looked why it passed false when the disabled variable should be true.

https://github.com/angular/material2/blob/740a2eeaa921c201c21b7a0fee980cf05ad7c2aa/src/cdk/drag-drop/drag-ref.ts#L216-L223

This should get called when disabled and it actually isn't (I placed a breakpoint there).

Then I tested using `cdkDragDisabled` insted of `cdkDropListGroupDisabled` and the setter disable was called and everything worked correctly.

#### What are the steps to reproduce?

Create a `cdkDropListGroup` and disable it.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular Material 7.3.3, Angular CDK 7.3.3

**Comment by Aleksandyr** [comment]
@crisbeto  I can try to dig into the problem if it's okay.
But @DavidMarquezF I couldn't get the essence of the problem. Could you please specify which scrolling and native input is not working. Can you provide a sample or just explain the problem with more details within your scenario?

**Comment by DavidMarquezF** [comment]
Nevermind, now it worked correctly. I don't really understand why, because I haven't changed anything since yesterday. 

Sorry for the inconvenience.
