### ISSUE TITLE
dropdown arrow for native select is not clickable.

### ISSUE THREAD

**Issue by jasonzhang2022** [angular/material2#15318]
#### What is the expected behavior?
it should be clickable and show drop down

#### What is the current behavior?
It is not clickable

#### What are the steps to reproduce?
https://material.angular.io/components/select/examples

check the Basic Native Select exmaple.

**Comment by Aleksandyr** [comment]
@jasonzhang2022 I couldn't reproduce the issue. Is there any specific platform that you are encountering the problem?
![image](https://user-images.githubusercontent.com/7037740/53494422-67162f00-3aa6-11e9-99a4-1f6b4a4d9561.png)
