### ISSUE TITLE
mat-select does not have value 

### ISSUE THREAD

**Issue by dcolakchile** [angular/material2#15334]
#### What is the expected behavior?

var element = document.getElementById( 'id of mat-select' ) as HTMLInputElement;

element.value != null

#### What is the current behavior?

There is no .value within the element

#### What are the steps to reproduce?

Create <mat-select> control and try to get the selected value via document.getElementById

It fails.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All latest versions.

#### Is there anything else we should know?

No.

**Comment by agpreynolds** [comment]
This is because by default the mat-select element doesn't actually produce a native select element. If you require a native select element you can use the 'matNativeControl' directive:

```
  <mat-form-field>
    <select matNativeControl placeholder="Favorite car" [(ngModel)]="selectedCar" name="car">
      <option value="" selected></option>
      <option *ngFor="let car of cars" [value]="car.value">
        {{car.viewValue}}
      </option>
    </select>
  </mat-form-field>
```

With this format you will be able to use `document.getElementById().value.`

Alternatively you can still get the value of a standard mat-select by using `document.getElementById().innerText.trim()`

Ultimately I would be interested to know why you need this kind of DOM level control? Are you using angular material without material?

**Comment by crisbeto** [comment]
@agpreynolds is correct: you should get a reference to the `MatSelect` instance either with a `ViewChild` or a template reference.

**Comment by dcolakchile** [comment]
document.getElementById().innerText.trim() show the TEXT not the VALUE.

Why doesn't it produce a native element with the VALUE, when it already has TEXT?

I cannot use ViewChild because those controls are dynamically created.

matNativeControl crashes with:

ERROR TypeError: Cannot read property 'label' of undefined
    at MatInput.get [as shouldLabelFloat] (input.es5.js:586)
    at MatFormField.push../node_modules/@angular/material/esm5/form-field.es5.js.MatFormField._shouldLabelFloat (form-field.es5.js:535)
    at Object.eval [as updateRenderer] (DbAddnewComponent.html:39)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:22482)
    at checkAndUpdateView (core.js:21857)
    at callViewAction (core.js:22093)
    at execEmbeddedViewsAction (core.js:22056)
    at checkAndUpdateView (core.js:21853)
    at callViewAction (core.js:22093)
    at execEmbeddedViewsAction (core.js:22056)

**Comment by agpreynolds** [comment]
You are quite right, .innerText() was a hack for you to achieve what you want to without using angular data binding. I made a sloppy assumption that the text and value would be the same.

The example I provided this morning was lifted directly from the material docs:
https://material.angular.io/components/select/overview#form-field-features

If you can't resolve this issue using the docs for reference, perhaps create a minimal reproduction in something like stackblitz?
