### ISSUE TITLE
No way to get the selected item value out of dynamically created mat-select

### ISSUE THREAD

**Issue by dcolakchile** [angular/material2#15341]
#### What is the expected behavior?

Being able to get the selected value out of a dynamically created mat-select control with document.getNativeElement or any other way

#### What is the current behavior?

NativeElement created by mat-select does not hold the selected value

#### What are the steps to reproduce?

```
<mat-form-field>
<mat-select id={{column.columnName}} placeholder="{{column.columnName|translate|capitalize}}">
<mat-option *ngFor="let foreignRow of foreignDataMap[getForeignTableName(column.columnName)]" [value]="foreignRow.uid">
 {{foreignRow.value}}
</mat-option>
</mat-select>
</mat-form-field>
```

```
var element = document.getElementById( column.columnName ) as HTMLInputElement;

element.value <-- does not exist
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All latest.

#### Is there anything else we should know?

No.

**Comment by agpreynolds** [comment]
Here is a stackblitz example of how to use the native select control to achieve this.

https://stackblitz.com/edit/angular-material2-issue-1symtn

As discussed in my comment on
https://github.com/angular/material2/issues/15334

**Comment by crisbeto** [comment]
The answer is the same as in #15334.

**Comment by dcolakchile** [comment]
PEOPLE, WE DO NOT WANT TO USE NATIVECONTROL BECAUSE IT IS DRAWN COMPLETELY DIFFERENT! STOP CLOSING THE BUG!

**Comment by agpreynolds** [comment]
I understand your frustration, however please mind the tone of your messages. Remember this is an open source community and many of the individuals offering you support are volunteers with no obligation to do so.

I accept the native control has some visual differences with the mat-select, however this control was designed to offer support for users who still required access to the underlying select control.

I believe you can solve your issue using mat-select without resorting to document. Getelementbyid(). If you provide some more information about your use case I would be happy to help recommend an alternative mechanism for retrieving the value.

**Comment by dcolakchile** [comment]
The sample code is posted.

That's is the use case, dynamically created controls that I need to access in order to get the selected value.

Unfortunately mat-select does not offer the way to get the selected value out of it, if it was dynamically created.

**Comment by agpreynolds** [comment]
I think you need to consider a different approach to the problem.

Option 1 - Change Events
Every time a change happens, update a component variable to access later.

Option 2 - Reactive Forms
Bind to the generated control name, then access this control when you need the value.

I've updated my stackblitz example with both of these options, i've kept the native control option there for reference.

https://stackblitz.com/edit/angular-material2-issue-1symtn

**Comment by dcolakchile** [comment]
Thx, using events is a nice solution, I'll use it.

But, why having to come up with solutions when value should be part of the control just like selected text is?

This should be a bug to be fixed.

**Comment by dcolakchile** [comment]
There is a problem with the event solution.

If the user never selected a new value, we cannot get it.

So much complication because of the bug in material.

**Comment by agpreynolds** [comment]
I personally disagree that this is a bug, there is no reason for material to render the literal value in the HTML. The text value is displayed only because it is displayed to the user.

DOM manipulation using functions like document.getElementById() has very few use cases in the world of angular and material and honestly I very much doubt this is one of them.

To solve your event issue, you could always set a default value for each select in currentValueMap in the class constructor or onInit function.

How does reactive forms work with more than one field?
Use a for loop.

I've added another example to the stackblitz showing how you could solve this using template driven forms, seeing as you seem unhappy with the reactive forms example. 
https://angular-material2-issue-1symtn.stackblitz.io

**Comment by dcolakchile** [comment]
Oh man:

"there is no reason for material to render the literal value in the HTML. The text value is displayed only because it is displayed to the user."

Really? "Text value is displayed only because it displayed to the user?" And the selected value is of no meaning to the user? Come on!

Unless you want to do by hand every form and there are tens and hundreds of them, you are going to use DOM to make a nice little framework that will do it for you.

mat-table not putting value into the element is absolutely ridiculous.

They simply forgot!

They should put it in there, it does not make sense to leave it as it is today.
