### ISSUE TITLE
mat-action-list does not have a hover/focus visual

### ISSUE THREAD

**Issue by mitchellwills** [angular/material2#15349]
#### What is the expected behavior?
mat-action-list behaves similar for focus/hover to mat-nav-list

#### What is the current behavior?
When button mat-list-item in a mat-action-list are hovered/focused there is no visual indication of such (eg. darkened background like in mat-nav-list).

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-fvnkgw
Hover over a mat-action-list and compare to the mat-nav-list
Tab through focus in the page

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.3.1

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material2/pull/14147.

**Comment by crisbeto** [comment]
Fixed in https://github.com/angular/material2/commit/3f876e2cd14288eeae91f488bbf3a354d285671e.
