### ISSUE TITLE
CDK virtual scroll |  scrollToIndex method not work as expected

### ISSUE THREAD

**Issue by ofirrifo** [angular/material2#15351]
#### What is the expected behavior?
using this ```this.viewPort.scrollToIndex(4999, 'auto');```
should scroll to index 4999

#### What is the current behavior?
it scrolls to index 4971 

#### What are the steps to reproduce?
1. create a list of 5000 items 
2. use this method  ```this.viewPort.scrollToIndex(4999, 'auto');```
[stackblitz example](https://stackblitz.com/edit/cdk-virtual-scroll-issue?file=app%2Fcdk-virtual-scroll-overview-example.ts)

in the example wait 2 sec then it scrolls to the wrong item

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/cdk": "7.3.1",
    "@angular/core": "7.2.7",
    "@angular/http": "7.2.7",
    "@angular/forms": "7.2.7",
    "@angular/common": "7.2.7",
    "@angular/router": "7.2.7",
    "@angular/compiler": "7.2.7",
    "@angular/material": "7.3.1",

OS: mac-os 
browsers: I just try chrome

**Comment by djleonskennedy** [comment]
@ofirrifo I've tried your stack

![image](https://user-images.githubusercontent.com/8366455/53635738-b84d2c80-3c26-11e9-9b5c-1492432c4c10.png)

all works as expected

**Comment by ofirrifo** [comment]
@djleonskennedy 
I just take a video for this issue reproduce 
https://screencast.com/t/rFlgOFTE

did you try it on chrome browser? since it happens on chrome.

**Comment by djleonskennedy** [comment]
@ofirrifo i've used last chrome (Chrome 72) and windows 10

**Comment by supdegrave** [comment]
@ofirrifo Works for me, both Chrome and Canary.

**Comment by OlielNoy** [comment]
This also happens to me. Also scrolls to index 4971 with the provided [example](https://screencast.com/t/rFlgOFTE) from @ofirrifo
I'm using chrome Version 72.0.3626.119 (Official Build) (64-bit)
