### ISSUE TITLE
CDK Drag & Drop item doesn't scroll page/container

### ISSUE THREAD

**Issue by hassanasad** [angular/material2#15365]
#### What is the expected behavior?
Moving and dragging the item at window top or bottom bounds will scroll in that direction.

#### What is the current behavior?
It doesn't scroll window/container.

#### What are the steps to reproduce?
https://stackblitz.com/angular/kelvlyydgmb
Try to pick an item from end of the list and bring it to first position. Page wont scroll up (without using mouse wheel)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest versions

#### Is there anything else we should know?
No

**Comment by volser** [comment]
https://github.com/angular/material2/issues/13588

**Comment by crisbeto** [comment]
Closing as a duplicate of #13588.
