### ISSUE TITLE
Issue with documentation regarding datepicker

### ISSUE THREAD

**Issue by jpike88** [angular/material2#15377]
https://material.angular.io/components/datepicker/overview

There's a reference to choosing date implementation ('Choosing a date implementation'), it doesn't go anywhere. I can't find how to properly implement date.

**Comment by crisbeto** [comment]
The link is correct, but it looks like our documentation generator is off. It's supposed to link to [here on the same page](https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings).
