### ISSUE TITLE
paginator async translations

### ISSUE THREAD

**Issue by sfabriece** [angular/material2#15378]
#### Please describe the feature you would like to request.

I would like to be able to provide translation for the paginator labels.
Currently I'm using ngx-translate that provides a `.instant` method to load translations.  The problem with it is that it can't reload translations on reload. It only works if one navigates to the translated page from another page.

I'm assuming that there are something asynchronous happening with the instant method.

example (not working consistently): 

```ts
export function getTranslatePaginatorIntl(translate: TranslateService) {
  const paginatorIntl = new MatPaginatorIntl();

  paginatorIntl.itemsPerPageLabel = translate.instant(
    'paginator.itemsPerPageLabel'
  );
  paginatorIntl.firstPageLabel = translate.instant('paginator.firstPageLabel');
  paginatorIntl.previousPageLabel = translate.instant(
    'paginator.previousPageLabel'
  );
  paginatorIntl.nextPageLabel = translate.instant('paginator.nextPageLabel');
  paginatorIntl.lastPageLabel = translate.instant('paginator.lastPageLabel');

  return paginatorIntl;
}
```
#### What is the use-case or motivation for this proposal?
easier integration with localization libraries

**Comment by crisbeto** [comment]
You can tell the paginator to update its labels by emitting to the `changes` subject.

**Comment by sfabriece** [comment]
I don't understand how I'm supposed to use that in combination with an external library in a maintainable way. I know It's much to ask, but an example would be helpful. Especially with ngx-translate.

**Comment by crisbeto** [comment]
You just have to add this at the bottom of your function:

```
paginatorIntl.changes.next();
```

**Comment by sfabriece** [comment]
Thanks @crisbeto, I'll try that.

**Comment by sfabriece** [comment]
@crisbeto The following did not work:


```ts
export function getTranslatePaginatorIntl(translate: TranslateService) {
  const paginatorIntl = new MatPaginatorIntl();

  paginatorIntl.itemsPerPageLabel = translate.instant(
    'paginator.itemsPerPageLabel'
  );
  paginatorIntl.firstPageLabel = translate.instant('paginator.firstPageLabel');
  paginatorIntl.previousPageLabel = translate.instant(
    'paginator.previousPageLabel'
  );
  paginatorIntl.nextPageLabel = translate.instant('paginator.nextPageLabel');
  paginatorIntl.lastPageLabel = translate.instant('paginator.lastPageLabel');

  paginatorIntl.changes.next();  // add this line

  return paginatorIntl;
}
```

still getting this after reload:

![image](https://user-images.githubusercontent.com/3108592/53816352-b4d9de00-3f63-11e9-9a08-f52becca35da.png)

**Comment by shefalimittal-fujitsu** [comment]
@sfabriece 

Did you get a solution to this problem. I am facing same.

**Comment by sfabriece** [comment]
not yet @shefalimittal-fujitsu. Still looking for a solution. Please update this issue if you figure it out.

**Comment by shefalimittal-fujitsu** [comment]
I have resolved it as follows - 

`import { MatPaginatorIntl } from '@angular/material';
import { TranslateService } from '@ngx-translate/core';
import { Injectable } from '@angular/core';

@Injectable()
export class PaginatorI18n extends MatPaginatorIntl {

    constructor(private translate: TranslateService) {
        super();
        this.getPaginatorIntl();
    }

    getPaginatorIntl() {
        this.translate.get(['PAGINATOR.ITEMS_PER_PAGE_LABEL', 'PAGINATOR.NEXT_PAGE_LABEL', 'PAGINATOR.PREVIOUS_PAGE_LABEL', 'PAGINATOR.FIRST_PAGE_LABEL', 'PAGINATOR.LAST_PAGE_LABEL']).subscribe(translation => {
            this.itemsPerPageLabel = translation['PAGINATOR.ITEMS_PER_PAGE_LABEL'];
            this.nextPageLabel = translation['PAGINATOR.NEXT_PAGE_LABEL'];
            this.previousPageLabel = translation['PAGINATOR.PREVIOUS_PAGE_LABEL'];
            this.firstPageLabel = translation['PAGINATOR.FIRST_PAGE_LABEL'];
            this.lastPageLabel = translation['PAGINATOR.LAST_PAGE_LABEL'];
            this.changes.next();
        });
    }

    getRangeLabel = (page: number, pageSize: number, length: number) => {
        if (length === 0 || pageSize === 0) {
            return this.translate.instant('PAGINATOR.RANGE_PAGE_LABEL_1', { length });
        }
        length = Math.max(length, 0);
        const startIndex = page * pageSize;
        // If the start index exceeds the list length, do not try and fix the end index to the end.
        const endIndex = startIndex < length ? Math.min(startIndex + pageSize, length) : startIndex + pageSize;
        return this.translate.instant('PAGINATOR.RANGE_PAGE_LABEL_2', { startIndex: startIndex + 1, endIndex, length });
    }
}`

**Comment by sfabriece** [comment]
that solved it @shefalimittal-fujitsu 

You are a life save 😄
