### ISSUE TITLE
mat-table, multiTemplate, matSort: expanding issue after sort

### ISSUE THREAD

**Issue by cdupetit** [angular/material2#15380]
#### What is the expected behavior?
After sorting, I expect the row expand when I click on it.

#### What is the current behavior?
The expand action works fine until records are sorted.
After the sort action, and if the row has never been expanded, the expand row appears only after 3 click.

#### What are the steps to reproduce?
[StackBlitz Demo](https://stackblitz.com/edit/angular-material-issue-table-multitemplate-sort?embed=1&file=src/app/app.component.html)
1. Click on a row. The row expands correctly.
2. Sort the records.
3. Click on a never expanded row, the row didn't expand.
4. Click again, the row didn't expand.
4. Click again, the row expands.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.2.7
Material: 7.3.3
TypeScript: 3.1.1
Browsers: Google Chrome

#### Is there anything else we should know?
No

**Comment by husaynable** [comment]
Looks like there is something wrong with animations triggering for collapsed row...

**Comment by cdupetit** [comment]
Hello @husaynable 
Do you mean in my code or in the library code ?
Thanks

**Comment by husaynable** [comment]
Hi @cdupetit !
I mean in the library code, because if we use CSS instead of angular animations it works well.
[My StackBlitz fork with this correction](https://stackblitz.com/edit/angular-material-issue-table-multitemplate-sort-uyacyv?embed=1&file=src/app/app.component.html)

**Comment by husaynable** [comment]
Hello again @cdupetit 
I found this issue related to [this](https://github.com/angular/angular/issues/18847) Angular Bug.

In current case, when the elements rearranged by sorting, their state is changed to 'void' because of this bug.

It can be fixed by adding the 'void' state:
`
animations: [
    trigger('detailExpand', [
      state('collapsed**, void**', style({ height: '0px', minHeight: '0', display: 'none' })),
      state('expanded', style({ height: '*' })),
      transition('expanded <=> collapsed**, void => expanded**', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)')),
    ])
  ]
`

**Comment by cdupetit** [comment]
Hello @husaynable,
Thank you very much for your time and the fix.
It's not a Material issue, so I close this issue.
