### ISSUE TITLE
mat-select options overlay shifted left when first child element is a mat-optgroup

### ISSUE THREAD

**Issue by aag5586** [angular/material2#15382]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Options overlay renders at the same position regardless its first child element

#### What is the current behavior?
When a mat-select's first child element is a mat-optgroup (vs a mat-option), the options overlay is shifted to the left. This is more noticeable when combined with a mat-form-field's appearance="outline"

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-hskr5f?file=app%2Fselect-optgroup-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2.7
Angular Material 7.3.1
macOS 10.14.3
Chrome 72.0.3626.119
Firefox 65.0.1
Safari 12.0.3

**Comment by crisbeto** [comment]
The select tries to position either the selected option or the first option on top of the trigger text. Options inside groups have some indentation which we have to compensate for, hence why the panel is moved more to the left. Closing because it works as expected.
