### ISSUE TITLE
pre-commit hook code formatting

### ISSUE THREAD

**Issue by swseverance** [angular/material2#15394]
#### Bug, feature request, or proposal:
This project appears to now have a pre-commit hook that runs code formatting on staged files. My question is, **are there plans to run code formatting on the entire codebase in a single PR?** It seems like running code formatting only on staged files will result in much larger diffs associated with each PR. Each PR will contain the changes explicitly made by the contributor as well as a potentially large number of differences that result from code being reformatted. I would think this would make the process of reviewing PR's more difficult.

#### What is the expected behavior?
N/A

#### What is the current behavior?
N/A

#### What are the steps to reproduce?
N/A

**Comment by mmalerba** [comment]
I think we'll disable the format-on-save in `.vscode/settings.json`. I wasn't really thinking and just copied those settings from @angular/angular. The `yarn format` command should only affect lines that have already been edited though, so it's fine to have the pre-commit hook asking people to run that.
