### ISSUE TITLE
MdIconRegistry._setSvgAttributes takes unnecessary config arg

### ISSUE THREAD

**Issue by code-tree** [angular/material2#1539]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

`MdIconRegistry._setSvgAttributes` makes use of all the args passed to it. 
#### What is the current behavior?

`MdIconRegistry._setSvgAttributes` takes a `config` arg but doesn't use it.
#### What are the steps to reproduce?

[Simply read the code](https://github.com/angular/material2/blob/cfe3e981bd068f7f06be1893d0894aae26904a26/src/lib/icon/icon-registry.ts#L333)
#### What is the use-case or motivation for changing an existing behavior?

Cleanup
#### Which versions of Angular, Material, OS, browsers are affected?

@angular/material 2.0.0-alpha.9-3
#### Is there anything else we should know?

No

**Comment by jelbourn** [comment]
I believe the config was added as an argument because there _will_ be options later, but I don't remember what those options are off the top of my head.

@dozingcat do you remember?

**Comment by dozingcat** [comment]
_setSvgAttributes is private and doesn't look like it should be doing anything other than modifying the SVG element itself, so this seems like a safe refactor. If the config argument is removed there, it can also be removed from _createSvgElementForSingleIcon and _extractSvgIconFromSet.
