### ISSUE TITLE
MatBottomSheet incomplete docs

### ISSUE THREAD

**Issue by ishankhare07** [angular/material2#15402]
#### What is the expected behavior?
Should work if you follow the docs in example section. Instead I'm reported with error `no provider for MatBottomSheetRef`

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Is there anything else we should know?
I was able to fix it by adding
```typescript
providers: [
  {provide: MatBottomSheetRef, useValue: {}}
]
```

**Comment by crisbeto** [comment]
You shouldn't have to use the `providers` to add the `MatBottomSheetRef`, because it's something that Material injects automatically. This is most likely an issue with your setup.
