### ISSUE TITLE
distinguising MatRadioGroup change event from DOM change event

### ISSUE THREAD

**Issue by alexfung888** [angular/material2#15409]
#### Please describe the feature you would like to request.

MatRadioGroup raises event with a name different from change

#### What is the use-case or motivation for this proposal?

Currently, the only output of MatRadioGroup is (change).
It has the same name as the native DOM event.
If you wrap a <mat-radio-group> outside for example an <input>, then the change event raised by the <input> element will bubble up MadRadioGroup. The handler will be confused, receiving a DOM event without event.source or event.value.

Yes, the handler should check the event object first, but it is a trap for every programmer.

use case: I use a radio group so that user will be filling different part of the form according to the radio button choice. something like only fill in part A when you choose option A, and B B. So I got all sorts of controls inside the radio group.

If MatRadioGroup has used something like sectionChange of MatSelect, then this ambiguity won't happen.

**Comment by crisbeto** [comment]
[We have some code that handles this case specifically.](https://github.com/angular/material2/blob/master/src/lib/radio/radio.ts#L548) Can you post an example that shows it breaking?

**Comment by alexfung888** [comment]
[stackblitz](https://stackblitz.com/edit/angular-radiogroup)
follow the instructions on the screen

**Comment by crisbeto** [comment]
Putting a `mat-form-field` inside a `mat-radio-button` isn't something that we support.

**Comment by alexfung888** [comment]
@crisbeto  I can understand that this is not a supported scenario, but I believe that the usage is common: to have additional form elements "clinging on" to inidividual radio buttons, because the elements are relevant only when the radio button has one of the available values.
