### ISSUE TITLE
Should menu expand the page when positioned in the bottom?

### ISSUE THREAD

**Issue by ottosson** [angular/material2#1540]
At https://material2-app.firebaseapp.com/ the menu positioned at the bottom of the page. And when opened the menu is hidden and you have to scroll down to see more of it.

Is this the desired behavior or should/could it open upward instead?

**Comment by fxck** [comment]
If you know it's going to be at the very bottom of the page, you should explicitly use the `y-position` attribute. For now anyway, I suppose that one day there will be automatic positioning depending on scroll / element position, similarly as how it works in material1.
