### ISSUE TITLE
Placeholder Disappearing From Option/Select  When Options Are Reset

### ISSUE THREAD

**Issue by Portismouth** [angular/material2#15420]
I have two select fields, the second of which options depend on the value of the first. When the options of the second are reset and the placeholder text disappears until you interact with the form field. 

#### What is the expected behavior?
I'm expecting the placeholder value to be shown when the options reset.

#### What is the current behavior?
The placeholder value disappears.

#### What are the steps to reproduce?
https://stackblitz.com/edit/select-issue

Select Liquid Flavor from the Product Form field then choose any option from the Product Type. Next, change the option in the first field to Powder Flavor - the second field clears out.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7, Material 7, Chrome on Windows

#### Is there anything else we should know?
I noticed that the the event triggers something that adds the .mat-form-field-hide-placeholder class to the form field. But that's as far as I have been able to get. I would love a point in the right direction on how to troubleshoot this.

**Comment by agpreynolds** [comment]
The placeholder disappears because your product type select still has a value set, it just so happens that the value in question no longer exists.

I would suggest using reactive forms to access to product type select, and reset if the selected option is no longer available. See stackblitz:

https://stackblitz.com/edit/select-issue-filcpf

**Comment by Portismouth** [comment]
Thanks! Not the exact solution - def pointed me in the right direction, however.
