### ISSUE TITLE
writeValue gets called before ngOnInit

### ISSUE THREAD

**Issue by romansattler** [angular/material2#15434]
#### What is the expected behavior?
`ngOnInit` should be called before `writeValue`

#### What is the current behavior?
`writeValue` gets called before `ngOnInit` when the value accessor is set directly as described in the [docs](https://material.angular.io/guide/creating-a-custom-form-field-control#-code-ngcontrol-code-) under `ngControl`, i.e. by using
```
if (this.ngControl != null) {
    this.ngControl.valueAccessor = this;
}
```
in the constructor to avoid `cyclic dependency error` when providing `NG_VALUE_ACCESSOR`.

#### What are the steps to reproduce?
[Stackblitz](https://stackblitz.com/edit/angular-form-control-bug)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular/Material: 7.2.8

**Comment by crisbeto** [comment]
This is related to the `@angular/forms` package, not Material or the CDK. It should be posted here: https://github.com/angular/angular.

**Comment by romansattler** [comment]
I don't necessarily agree. The issue arises when implementing `MatFormFieldControl`. The workaournd from the docs wouldn't be necessary otherwise.

I'm quite sure that the `@angular/forms` team will say that it's not intended use. But I can try.
