### ISSUE TITLE
Mat-Dialog: open second dialog from first dialog positioning issue

### ISSUE THREAD

**Issue by WadeMartin** [angular/material2#15437]
#### What is the expected behavior?
I am trying to open a modal which opens a second modal within the screen. expected behavior is that the second modal will open on top of the first modal.

#### What is the current behavior?
The first modal opens up perfectly whilst the second modal's position gets obscured and cannot be seen within the screen

#### What are the steps to reproduce?
Stackblitz link: https://stackblitz.com/edit/modal-issue-angular-7

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular-material: 7.3.1

**Comment by macjohnny** [comment]
the error message in the console 
```
Error: No component factory found for DialogOverviewExample2Dialog. Did you add it to @NgModule.entryComponents?
```
means that you need to add `DialogOverviewExample2Dialog` to your module.
See this working example: https://stackblitz.com/edit/modal-issue-angular-7-429dn9?file=main.ts

**Comment by crisbeto** [comment]
Closing since it looks like an implementation issue.
