### ISSUE TITLE
Importing material module in cli lib with Ivy enabled doesn't work

### ISSUE THREAD

**Issue by epelc** [angular/material2#15465]
Not sure if this is a material bug or a cli one but it wasn't happening with other libraries afaik.

#### What is the expected behavior?
You should be able to import a module like `MatProgressSpinnerModule` from within an NgModule in an angular cli library with the ivy renderer enabled using angular v8 beta.

#### What is the current behavior?

It works with ivy disabled but when you enable ivy it breaks with the following error.

` Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class` `LoadingModule` is my module name within the cli library.

```
Building Angular Package
Building entry point '@greatcloak/utils'
Compiling TypeScript sources through ngc

BUILD ERROR
node_modules/@angular/common/common.d.ts(115,22): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class
node_modules/@angular/material/progress-spinner/typings/progress-spinner-module.d.ts(1,15): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class
node_modules/@angular/flex-layout/typings/module.d.ts(16,22): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class

Error: node_modules/@angular/common/common.d.ts(115,22): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class
node_modules/@angular/material/progress-spinner/typings/progress-spinner-module.d.ts(1,15): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class
node_modules/@angular/flex-layout/typings/module.d.ts(16,22): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class

    at Object.<anonymous> (/myprojectdir/_web/node_modules/ng-packagr/lib/ngc/compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
    at fulfilled (/myprojectdir/_web/node_modules/ng-packagr/lib/ngc/compile-source-files.js:4:58)

node_modules/@angular/common/common.d.ts(115,22): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class
node_modules/@angular/material/progress-spinner/typings/progress-spinner-module.d.ts(1,15): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class
node_modules/@angular/flex-layout/typings/module.d.ts(16,22): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class

Error: node_modules/@angular/common/common.d.ts(115,22): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class
node_modules/@angular/material/progress-spinner/typings/progress-spinner-module.d.ts(1,15): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class
node_modules/@angular/flex-layout/typings/module.d.ts(16,22): error TS-996002: Appears in the NgModule.imports of LoadingModule, but could not be resolved to an NgModule class

    at Object.<anonymous> (/myprojectdir/_web/node_modules/ng-packagr/lib/ngc/compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
    at fulfilled (/myprojectdir/_web/node_modules/ng-packagr/lib/ngc/compile-source-files.js:4:58)
```

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

Create a cli library with an ng module that imports a material module, enable ivy, then try and build it.

Enabled ivy renderer in your `tsconfig.json`
```
  "angularCompilerOptions": {
    "enableIvy": "ngtsc"
  }
```
Also doesn't work with `true` which uses different mixed pipeline iirc.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
"@angular/cdk": "7.3.4",
"@angular/material": "7.3.4",

"@angular/animations": "8.0.0-beta.8",
"@angular/common": "8.0.0-beta.8",
"@angular/compiler": "8.0.0-beta.8",
"@angular/core": "8.0.0-beta.8",
"@angular/flex-layout": "7.0.0-beta.23",
"@angular/forms": "8.0.0-beta.8",
"@angular/http": "8.0.0-beta.8",
"@angular/platform-browser": "8.0.0-beta.8",
"@angular/platform-browser-dynamic": "8.0.0-beta.8",
"@angular/pwa": "^0.13.5",
"@angular/router": "8.0.0-beta.8",
"@angular/service-worker": "8.0.0-beta.8",
"@angular/cli": "^8.0.0-beta.5",
"@angular/compiler-cli": "8.0.0-beta.8",
"@angular/language-service": "8.0.0-beta.8",

```

#### Is there anything else we should know?
Works fine using angular v8 beta with ivy disabled(also worked on 7.x).

It works if you import material libraries in a regular app project for some reason with ivy enabled.

**Comment by vladimirdjurdjevic** [comment]
I managed to build and run application, but i get runtime error when trying to open dialog with MatDialog.  

![image](https://user-images.githubusercontent.com/17208031/54377003-928f4100-4684-11e9-8481-1fc3b90e2d78.png)

**Comment by mohammedzamakhan** [comment]
@vladimirdjurdjevic how did you manage to build and run the application?

**Comment by vladimirdjurdjevic** [comment]
Just updated cli version to 8.0.0-beta.5, ng new myapp --enableIvy, and added "aot": true to angular.json options. Check if you have postinstall setup in package.json, "postinstall": "ivy-ngcc".

**Comment by epelc** [comment]
https://next.angular.io/guide/ivy

**Comment by vladimirdjurdjevic** [comment]
Anyone has idea why material won't work with ivy?

**Comment by vladimirdjurdjevic** [comment]
Just to add, when i turn ivy off, dialog opens as expected.

**Comment by epelc** [comment]
@vladimirdjurdjevic After messing with it more today my assumption is that ivy just isn't finished yet hence the beta and aot isn't fully supported or it possible needs some lib updates?

Specifically the docs on "ngModule-less bootstrapping" are not really there and using `erenderComponent` is still a private api. v8 is supposed to release march/april so maybe just use without AOT if you need ivy specific fixes or stick with v7 until v8 is fully released.

**Comment by vladimirdjurdjevic** [comment]
I think i will have to stick to v7 for now. It is broken with "aot": false also. I need ivy for dynamic component loading, since i have dialogs in lazy modules, and i don't like moving them to app module. But i will have to wait :)

**Comment by crisbeto** [comment]
Things with Ivy are still a work in progress. Material will work with it correctly once 8.0 stable is released.

**Comment by qzmfranklin** [comment]
Got very similar error message with `angular@8.0.0-rc.3`.

But [this commit](https://github.com/angular/components/commit/816a833f4e186f326d34ac0b1ec73c16fda16d4b) gives me some faith that Ivy is landing soon.

**Comment by fclemonschool** [comment]
I have same error at "@angular/core": "^8.1.0-next.1"
and "@angular/cli": "https://github.com/angular/cli-builds".

error TS-996002: Appears in the NgModule.imports of ~~~Module, but itself has errors

**Comment by avoliva** [comment]
Getting the same error. Have @angular/material at version 8.0.1 too.

**Comment by tcozzens** [comment]
I am getting the same thing with ```primeng@8.0.0```

**Comment by jmesa-sistel** [comment]
@tcozzens Known issue. You can see it this [angular doc](https://docs.google.com/document/d/1Dije0AsJ0PxL3NaeNPxpYDeapj30b_QC0xfeIvIIzgg/mobilebasic)
Issue: [30565](https://github.com/angular/angular/issues/30565)
Primeng team should change the way they build the library

**Comment by mtuzinskiy** [comment]
Same error with `"@angular/core": "^8.2.0-next.0"`

**Comment by duard** [comment]
same error 

`➜ ng v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.2
Node: 12.4.0
OS: linux x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.6
@angular-devkit/build-angular      0.800.6
@angular-devkit/build-ng-packagr   0.800.6
@angular-devkit/build-optimizer    0.800.6
@angular-devkit/build-webpack      0.800.6
@angular-devkit/core               8.0.6
@angular-devkit/schematics         8.1.2
@angular/cdk                       8.1.1
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.1.1
@angular/upgrade                   8.2.0-next.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.6
@schematics/angular                8.1.2
@schematics/update                 0.801.2
ng-packagr                         5.3.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0
`
