### ISSUE TITLE
Select throws error to console on keyboard interarction with reset option

### ISSUE THREAD

**Issue by RandomNonameDude** [angular/material2#15494]
#### What is the expected behavior?

Select should not throw errors to console.

#### What is the current behavior?

When a select component has a reset option (but a non-reset option is currently selected) and is focused (the option list is closed), and you start pressing _arrow-up_ key, the component throws error to console when you reach the reset option.

#### What are the steps to reproduce?

1. Create select component with reset option
2. Select non-reset option
3. Focus the select but don't open the options list (e. g. focus with _tab_ key)
4. Start pressing the _arrow-up_ until you reach the reset option
5. Take a look into the console

The issue is reproducible on the Material documentation in select examples, e. g. **Select with 2-way value binding** or **Select with reset option**

https://material.angular.io/components/select/examples

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material 7.3.4, tested on Chrome only.

#### Is there anything else we should know?

Nope.

**Comment by crisbeto** [comment]
Fixed by https://github.com/angular/material2/pull/15160.
