### ISSUE TITLE
mat-button draws over mat-header-cell columns when scrolling table

### ISSUE THREAD

**Issue by nickkhan** [angular/material2#15506]
#### What is the expected behavior?
Create a mat-table using MaTtableDatasource. Create one column for creating a link
        <ng-container matColumnDef="actions">
          <th  mat-header-cell *matHeaderCellDef mat-sort-header disableClear></th>
          <td  mat-cell *matCellDef="let item">
            <button mat-icon-button [matMenuTriggerFor]="menu">
              <mat-icon>more_horiz</mat-icon>
            </button>
            <mat-menu #menu="matMenu">
                <a mat-menu-item [routerLink]="['/details']">View Details</a>
            </mat-menu>
          </td>
        </ng-container>

if you scroll the table, the mat-button scrolls over the column-header cells and draws over it. 
#### What is the current behavior?
The button link should go under the mat-header-cell columns like other columns

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular-extensions/model": "^7.1.2",
    "@angular/animations": "^7.2.1",
    "@angular/cdk": "^7.3.4",
    "@angular/common": "^7.2.1",
    "@angular/compiler": "^7.2.1",
    "@angular/compiler-cli": "^7.2.1",
    "@angular/core": "^7.2.1",
    "@angular/forms": "^7.2.1",
    "@angular/material": "^7.3.4",
![Untitled](https://user-images.githubusercontent.com/5621663/54482620-d2892c00-481c-11e9-9ea6-2e2cf54372d9.png)

**Comment by nickkhan** [comment]
I can confirm the button draws over column header,
  <button mat-icon-button color="warn">
    <mat-icon aria-label="Example icon-button with a heart icon">favorite</mat-icon>
  </button>

**Comment by crisbeto** [comment]
It's hard to see what's going on purely from a screenshot. Can you post an example of it breaking?
