### ISSUE TITLE
stepControl is no longer of type AbstractControl

### ISSUE THREAD

**Issue by tobang** [angular/material2#15514]
#### What is the expected behavior?
CdkStep stepControl is of type AbstractControl as defined in the documentation

#### What is the current behavior?
When looking at the type definitions for CdkStep stepControl is as defined as follows:
 stepControl: {
        valid: boolean;
        invalid: boolean;
        pending: boolean;
        reset: () => void;
    };

#### What are the steps to reproduce?
Install Material/CDK 7.3.4. Try to use stepControl get function it will fail with the following typescript error:

 TS2339: Property 'get' does not exist on type '{ valid: boolean; invalid:
boolean; pending: boolean; reset: () => void; }'.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2.9
Material 7.3.4
CDK 7.3.4
Typescript 3.1.6

#### Is there anything else we should know?
Downgrading to Material/CDK 7.3.2 fixes the issue

**Comment by crisbeto** [comment]
Should be fixed in 7.3.5.
