### ISSUE TITLE
stepper.next() with [completed] value don't behave like expected

### ISSUE THREAD

**Issue by leobouts** [angular/material2#15511]
#### What is the expected behaviour?
after finishing a step the completed value of the step is assigned to true. Calling stepper.next() will advance you to the next step.

#### What is the current behaviour?
after finishing a step the completed value of the step is assigned to true. After that stepper.next() is called and nothing happens. With a second call to this method the stepper advances. The user needs to click once, not twice.

#### What are the steps to reproduce?
https://stackblitz.com/edit/mat-horizontal-stepper-lyqe5x

**Comment by FritzHerbers** [comment]
The example has some old library dependencies. Try to upgrade first.

**Comment by FritzHerbers** [comment]
#15310

**Comment by leobouts** [comment]
@FritzHerbers this was from an old stackblitz i edited, my main project behaves like this with the current dependencies. Also i found out that if i put an async function call between the completed = true and the stepper.next() commands it works like charm.

**Comment by crisbeto** [comment]
Looks like this is the same issue as https://github.com/angular/material2/issues/15310. Closing as a duplicate.
