### ISSUE TITLE
MatAutocomplete doc use unnecessary value for template variable

### ISSUE THREAD

**Issue by nreynis** [angular/material2#15529]
#### What is the current behavior?

The MatAutocomplete documentation provides examples like that:

```html
<mat-form-field>
  <input type="text" matInput [formControl]="myControl" [matAutocomplete]="auto">
</mat-form-field>

<mat-autocomplete #auto="matAutocomplete">
  <mat-option *ngFor="let option of options" [value]="option">{{option}}</mat-option>
</mat-autocomplete>
```

In this snippet the template reference variable `#auto` has an associated value of `matAutocomplete`.
This value seems unnecessary (the example work without it) and is also confusing: it's unclear what is it's purpose, is a directive changing the reference in some way ?

#### What is the expected behavior?

Remove the unnecessary value:

```html
<mat-form-field>
  <input type="text" matInput [formControl]="myControl" [matAutocomplete]="auto">
</mat-form-field>

<mat-autocomplete #auto>
  <mat-option *ngFor="let option of options" [value]="option">{{option}}</mat-option>
</mat-autocomplete>
```

Or maybe, if there's some subtility going on that I missed, add a note to explain why it's necessary to keep the value.

**Comment by crisbeto** [comment]
It's true that the variable isn't strictly necessary in this case since `MatAutocomplete` is a component, but it doesn't hurt to have it either. Usually it's good to keep the reference, because it can be confusing if there are multiple references on the same element.
