### ISSUE TITLE
External label (not mat-label) isn't triggering mat-select

### ISSUE THREAD

**Issue by fleish80** [angular/material2#15534]
#### What is the expected behavior?

Click on label should trigger related input or button. This behavior occurs with 'for' attribute on label and same value of 'id' on input or button. This behavior is important in both, with accessibility and with mobile devices.
#### What is the current behavior?
Using an external label (not mat-label) related to mat-select with for and id not triggering mat-select because it's not button or input behind.

#### What are the steps to reproduce?
https://stackblitz.com/edit/external-label-with-mat-select?file=src%2Fapp%2Fapp.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.2.0
Material: 7.3.4
Cdk: 7.3.4
Typescript: 3.2.2
Browsers: All

#### Is there anything else we should know?
I think that the solution for this is also open the opportunity to use mat-select as directive, see this:
https://stackblitz.com/edit/external-label-with-mat-select-as-directive?file=src/app/app.component.ts
exactly like you did with mat-table:
https://stackblitz.com/angular/kkxxemgjpmk?file=app%2Ftable-basic-example.ts
maybe even you should consider change permanently mat-select to button behind in dom.

**Comment by crisbeto** [comment]
`label` nodes can only target labelable elements like `button` or `input`. Since the `mat-select` is a custom element, there's not much we can do and changing the selector could be a breaking change. You can work around it either by using `mat-label`, or a native `select` inside of `mat-form-field`.
