### ISSUE TITLE
coloumn cannat be null error in angualr

### ISSUE THREAD

**Issue by suhailshaik777** [angular/material2#15544]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by suhailshaik777** [comment]
iam getting this type of error when iam going signup the `page`<div class="container-Signup">

  <div>
    <div class="wrap-Signup">
      <form class="Signup-form validate-form">

        <div class="logo">
          <span class="login-form-title"><img src="../../../../assets/images/Logos/logo.png"/>justredeem</span>
        </div>  
     
       

 

        <div class="input-group">
          <input class="input" type="text" name="Name" [(ngModel)]="registerdetails.FullName"
            required>
          <span class="highlight"></span>
          <span class="bar"></span>
          <label>Name</label>
          
          <div class="alert alert-danger" Id="Namevalidation" style="display:none"><i class="fa fa-info-circle"></i>Name is required.</div>
        </div>

        <div class="input-group">
          <input class="input" type="text" name="Email" [(ngModel)]="registerdetails.EmailId" required>
          <span class="highlight"></span>
          <span class="bar"></span>
          <label>Email Id</label>
          <div class="alert alert-danger" Id="Emailvalidation" style="display:none"><i class="fa fa-info-circle"></i>Email is required.</div>
        </div>

        <div class="input-group">
          <input class="input passwordfield" type="password" name="pass" [(ngModel)]="registerdetails.Password" required>
          <span class="highlight"></span>
          <span class="bar"></span>
          <label>Password</label>
          <div class="alert alert-danger" Id="Passwordvalidation" style="display:none"><i class="fa fa-info-circle"></i>Password is required.</div>
        </div>


        <div class="input-group" style="margin-bottom: 10px;">
          <input class="input passwordfield" type="text" name="pass" [(ngModel)]="registerdetails.MobileNumber" required>
          <span class="highlight"></span>
          <span class="bar"></span>
          <label>Mobile Number</label>
          <div class="alert alert-danger" Id="Mobilevalidation" style="display:none"><i class="fa fa-info-circle"></i>Mobile Number is required.</div>
        </div>


        <div class="input-group radioinputs">

          <span style="margin-right:20px;">
                <input id="Male" ej-radiobutton text="Male" name="category" value="Male" [(ngModel)]="registerdetails.Gender" />
          </span>
            
           <span class="genderradiobtn">
              <input id="Female" ej-radiobutton text="Female" name="category" value="Female" [(ngModel)]="registerdetails.Gender" />           
            </span>

            <div class="alert alert-danger" Id="Gendervalidation" style="display:none"><i class="fa fa-info-circle"></i>Gender is required.</div>

        </div>

        <div style="position: relative">
        <div class="content-container-fluid datefield">

          <div class="row" style="margin-left: 0px;margin-right: 0px">
              <label style="position: relative;top:0">DOB</label>
              <div class="cols-sample-area" style="margin:0 auto;">
                  <input type="text" ej-datepicker id="datepick" name="Datefield" [(ngModel)]="registerdetails.DateOfBirth" dateFormat ="dd/MM/yyyy" />
              </div>
          </div>

        </div>
        <div class="alert alert-danger" Id="DoBvalidation" style="display:none;top:70px !important"><i class="fa fa-info-circle"></i>D.O.B is required.</div>
      </div>


        <div class="container-Signup-form-btn">
          <button (click)="signup(this.registerdetails)" class="Signup-form-btn">
            Sign Up
          </button>
        </div>


      </form>

    </div>
    <p class="LoginInSignup">Already a Registered User ? <a [routerLink]="['/Login']">Login</a></p>
  </div>
  
  <div class="alert ErrorAlert" id="ErrorAlert" style="display:none">{{AlertMessage}}</div>

</div>`

Getting this type of error:
{Status: "Registration UnSuccesfull", Message: "Column 'Gender' cannot be null", Result: null, StackTrace: null}

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
