### ISSUE TITLE
Is there a way to set mat-stepper at the bottom of the page

### ISSUE THREAD

**Issue by akvaliya** [angular/material2#15547]
I have a requirement from my customer that steps should be at the bottom of the page.

I'd like to know if there is a way to set mat-stepper-header at the bottom of the page.

I tried to find this feature, but so far i am unable to find anything.

**Comment by crisbeto** [comment]
Will be added in https://github.com/angular/material2/pull/15509.

**Comment by akvaliya** [comment]
Any estimation when will it be added?
