### ISSUE TITLE
My own palette in theme

### ISSUE THREAD

**Issue by Layyy** [angular/material2#1555]
#### Bug, feature request, or proposal:
I want to add my own palette in theme but it seems I need opacity palette to which I don't know how to include if there is a possible way to do it. Maybe there is another way how to use my own palette but I don't know about it. I used this guide for theme https://github.com/angular/material2/blob/master/docs/theming.md

#### What is the expected behavior?
You should be able to include your own palette.

#### What is the current behavior?
You can use only predefined palettes.

#### What is the use-case or motivation for changing an existing behavior?
People can use their own pallets for styling, so they don't need to stick with predefined palettes

**Comment by jelbourn** [comment]
@Layyy you can define your own palette already. It just has to match this data structure:
https://github.com/angular/material2/blob/master/src/lib/core/theming/_palette.scss#L12
