### ISSUE TITLE
Material 7 Drag and Drop ng-template incompatibility

### ISSUE THREAD

**Issue by zombaki** [angular/material2#15553]
#### What is the expected behavior?
Transferring items between lists should be possible,even when the components are created dynamically using ng-Template and  ViewContainerRef.

#### What is the current behavior?
Dragging works but compoenent is not able to find the parent cdkDropList and behaving as simple cdkDrag.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ngtemplate-reorder?file=src%2Fapp%2Fapp.component.html
-> Click Button Add panel to add panel component 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.2, Material 7.0.2, TypeScript 3.1.6, reproduced in Chrome on Windows OS

**Comment by crisbeto** [comment]
`CdkDrag` uses dependency injection to find out whether it's inside a `CdkDropList` which doesn't work when the template is inside a different component. For more advanced cases like this one you can use the `DragDrop` service to attach the drag&drop functionality yourself.

**Comment by zombaki** [comment]
HI @crisbeto 
I tried implementing DragDropService but due to some reason it still dosn't behave as expected .
Please find below stackblitz implementation for the same.
https://stackblitz.com/edit/angular-ngtemplate-reorder-7i6uuk?file=src%2Fapp%2Fapp.component.ts
 
![image](https://user-images.githubusercontent.com/15192370/54783612-d5569900-4bef-11e9-81cf-54af83b1fd1e.png)

**Comment by zombaki** [comment]
Hey finally working .....we were missing " droplistREf.withItems(this.localDragRef);"

https://stackblitz.com/edit/angular-ngtemplate-reorder-7i6uuk?file=src%2Fapp%2Fapp.component.ts

**Comment by vkk1985** [comment]
Hi @zombaki ,
It is not working. can you provide me the solution or what need to fix?

**Comment by vkk1985** [comment]
> Hey finally working .....we were missing " droplistREf.withItems(this.localDragRef);"
> 
> Working stack blitz for reference :
> https://stackblitz.com/edit/angular-ngtemplate-reorder-7i6uuk?file=src%2Fapp%2Fapp.component.ts

Hi @zombaki ,
It is not working. can you provide me the solution or what need to fix?
