### ISSUE TITLE
Dialog: mat-stroked-button doesn't have margin in mat-dialog-actions

### ISSUE THREAD

**Issue by Wykks** [angular/material2#15561]
#### What is the expected behavior?
A `margin-left: 8px;` in actions buttons (except the first one).

#### What is the current behavior?
When using stroked buttons, the margin is missing

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-r6u5wc

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material & cdk 7.3.5

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material2/pull/11961.
