### ISSUE TITLE
material button toggle/ switch between two icons.

### ISSUE THREAD

**Issue by andreElrico** [angular/material2#15578]
#### Please describe the feature you would like to request.

Buttons are often used to toggle state. Toggling state often comes with the need of changing the icon inside the button.
this
`<button (click)="toggleState = !toggleState" mat-button>{{ toggleState ? 'more_vert' : 'more_horiz' }}</button>`

Does not work for obvious reasons.

instead I would have to go caveman style:

`<button *ngIf="toggleState" (click)="toggleState = !toggleState" mat-button>more_vert</button>
<button *ngIf="!toggleState" (click)="toggleState = !toggleState" mat-button>more_horiz</button>`

Would be cool to have something like this:

`<button #button (click)="toggleState = !toggleState; button.toggleIcon()" secondIcon="more_horiz" mat-button>more_vert</button>`

(if possible a "transition" animation from icon to icon could happen. I know that's a tough one since "svg nodes" need to line up beween icons etc ...)

**Comment by ccjmne** [comment]
Hello 👋
I don't quite get this:

> `<button (click)="toggleState = !toggleState" mat-button>{{ toggleState ? 'more_vert' : 'more_horiz' }}</button>`
> Does not work for obvious reasons.

I don't see the reason why that wouldn't work — this does seem reasonable to me.

As for your questions about animations, Angular does have this covered!
Here's the official ["getting started" for Angular animations](https://angular.io/guide/animations). I browsed through it just yesterday, and it is quite comprehensible.

I built a [StackBlitz featuring a "toggle button"](https://stackblitz.com/edit/angular-material2-issue15578) like the one you suggested, with Angular-powered transitions.

Here's the gist of it.

```typescript
@Component({
  selector: 'hello',
  template: `
    <button mat-button
      [@direction]="direction"
      (click)="state = !state">
      <mat-icon>more_{{ direction }}</mat-icon>
    </button>`,
  styles: [`h1 { font-family: Lato; }`],
  animations: [
    trigger('direction', [
      state('horiz', style({
        transform: `scale(1)`,
      })),
      state('vert', style({
        transform: `scale(1)`,
      })),
      transition('horiz <=> vert', [
        style({
          transform: `scale(1.5)`,
          opacity: .5
        }),
        animate('.2s 0s ease-out')
      ])
    ])
  ]
})
export class HelloComponent {
  @Input() public state: boolean = false;

  protected get direction(): 'vert' | 'horiz' {
    return this.state ? 'vert' : 'horiz';
  }
}
```

Is there something I am missing in your question? Or does my approach help you?

**Comment by andreElrico** [comment]
I guess i was missing the mat-icon part :/. Thank you for your great help!
