### ISSUE TITLE
md-slider distortion when value bigger than min or max is assigned

### ISSUE THREAD

**Issue by stanislavgatsev** [angular/material2#1557]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When value bigger than max or smaller than min is set to the slider the thumb should stay at the end of the track.

#### What is the current behavior?
Now the thumb goes out of the track.

#### What are the steps to reproduce?

<md-slider [(ngModel)]="sliderValue" min="{{sliderValueMin}}" max="{{sliderValueMax}}" value="{{sliderValue}}"></md-slider>

When slider value is changed in order to exceed limits.

#### What is the use-case or motivation for changing an existing behavior?
When slider is connected to another text input control and user puts invalid value in the input.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0.0, Material 2.0.0-alpha.8-2, All, All

**Comment by feloy** [comment]
I can work on this
