### ISSUE TITLE
Animations (step and tab) causing a weird behavior in floating elements

### ISSUE THREAD

**Issue by WagnerMattei** [angular/material2#15585]
#### What is the expected behavior?

A floating element inside a mat-step content, or mat-tab content should be floating, just as when it is outside.

#### What is the current behavior?

When tabs/steps transition animations starts, the floating elements behave like they are not `position: "fixed"`.
Then, when the animations ends, they assume his correct position.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-gtnwar

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
"dependencies": {
    "@angular/animations": "~7.0.4",
    "@angular/cdk": "^7.0.4",
    "@angular/common": "~7.0.4",
    "@angular/compiler": "~7.0.4",
    "@angular/core": "~7.0.4",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "~7.0.4",
    "@angular/material": "^7.0.4",
    "@angular/platform-browser": "~7.0.4",
    "@angular/platform-browser-dynamic": "~7.0.4",
    "@angular/router": "~7.0.4",
    "angular2-text-mask": "^9.0.0",
    "core-js": "^2.5.7",
    "hammerjs": "^2.0.8",
    "ng2-device-detector": "^1.0.1",
    "ngx-image-cropper": "^1.3.8",
    "ngx-mask": "^7.0.3",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.10.6",
    "@angular-devkit/build-ng-packagr": "0.10.6",
    "@angular/cli": "~7.0.4",
    "@angular/compiler-cli": "~7.0.4",
    "@angular/language-service": "~7.0.4",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.4",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.2.0",
    "protractor": "~5.4.1",
    "ts-node": "~7.0.1",
    "tsickle": ">=0.29.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
```

**UBUNTU 18.04 x86_64**

#### Is there anything else we should know?
The only way to 'fix' it is set the animations to disabled with `[@.disabled] = "true"`

**Comment by crisbeto** [comment]
That's because the stepper uses `transform` to animate itself which creates a new stacking context relative to which all `position: fixed` elements position themselves. I don't think we can do much about it, aside from not using `transform` for the animation which won't animate nearly as smoothly.
