### ISSUE TITLE
Drag-and-drop disabled inputs not working

### ISSUE THREAD

**Issue by Wisdomb33r** [angular/material2#15592]
#### What is the expected behavior?

Drap-and-drop of disabled elements should be possible. Drag-and-drop should only be disabled by [cdkDragDisabled], not by the HTML "disabled" attribute.

#### What is the current behavior?

**cdkDrag on inputs**

- With cdkDrag on inputs, drag-and-drop is working as expected.
- With cdkDrag and cdkDragDisabled on inputs, drag-and-drop is blocked as expected.
- With cdkDrag on **disabled** inputs (HTML disabled attribute), drag-and-drop is **not** working. **This is not what I did expect according to the CDK documentation** which states drag-and-drop is disabled by [cdkDragDisabled].

**cdkDrag on a div wrapping inputs**

- With cdkDrag on a div wrapping inputs, drag-and-drop is working as expected.
- With cdkDrag on a div wrapping **disabled** inputs (HTML disabled attribute), drag-and-drop is working on Chrome and Internet Explorer. However, it is NOT working on Firefox and Edge. The behavior is here **inconsistent across browsers**.

#### What are the steps to reproduce?

Here is a stackblitz project to reproduce these 5 different cases : 
[https://stackblitz.com/edit/angular-dhlkfm](https://stackblitz.com/edit/angular-dhlkfm)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 7.2.10, CDK 7.3.5, Material 7.3.5, TypeScript 3.2.4.

Browsers used for these tests (all desktop Win10 versions) :

- Chrome 72
- Firefox 66
- Microsoft EdgeHTML 17.17134
- Internet Explorer 17.648.17134.0

#### Is there anything else we should know?

I've got bad news : your Google Chrome browser behavior is identical to the very-old-and-obsolete Internet Explorer :-)

Beside this joke, I'm using drag-and-drop to let the app user configure which fields of a search bar are displayed and which are not. During the "configuration" mode (which is enabling drag-and-drop), I do not want the user to be able to enter values within the search inputs. For this reason, I need the input fields to be disabled during this configuration process.

I could not think about much options to work around this problem. The only option I can think of is to add a drag handle within the div wrapper, but this means my drag-and-drop elements are increasing in size, which I would rather avoid if possible.

**Comment by crisbeto** [comment]
The problem is that it's up to the browser to decide whether or not to dispatch events from a disabled input so we have no way of knowing when the user is dragging. As you mentioned, the workaround is to put the `cdkDrag` on an element that wraps the disabled input.

**Comment by Wisdomb33r** [comment]
However, the cdkDrag on the div wrapper is working only on Chrome and Internet Explorer, not on Firefox and Edge.

**Comment by Wisdomb33r** [comment]
I finally went for a different way of working around this problem. I'm hiding the search bar during configuration and displaying a "fake" search bar, with divs styled to be close to disabled inputs. Difference is hardly visible. For my use case I do not really need dragged element to be the real input, a fake one is perfectly fine.
Anyway, that you for your explanation about the browsers not dispatching events for disabled inputs.
