### ISSUE TITLE
Mat-tree: Title of leaf node is not vertically centered align on IE if we do not use disabled button

### ISSUE THREAD

**Issue by sandeeppatidar30** [angular/material2#15593]
#### What is the expected behavior?
Title of leaf node should be vertically centered align if we do not use disabled button for extra padding.

#### What is the current behavior?
Title of leaf node is top aligned if we do not use disabled button for extra padding.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/edit/angular-pnxpdm?file=app/tree-flat-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular@7.2.10, material@7.3.5, Windows7, Typescript@3.1.1, IE browser
![mat-tree-issue](https://user-images.githubusercontent.com/31273891/54906000-4eaffd80-4f08-11e9-8fd2-095f90c6bc83.png)

**Comment by crisbeto** [comment]
Fixing this requires changes in `mat-button` which can cause breakages in a wide array of scenarios. Closing the issue and for reference, you can fix it in your own app by applying the styling from https://github.com/angular/material2/pull/15598 to the particular case.
