### ISSUE TITLE
Support [md-menu-trigger-for] with anything conforming to MdMenu interface

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#1560]
Right now, `[md-menu-trigger-for]` requires that its value be an instance of `MdMenu`:

``` html
<button md-icon-button [md-menu-trigger-for]="menu"> Open Menu </button>

<md-menu #menu="mdMenu">
  <button md-menu-item> Hello! </button>
</md-menu>
```

It would be more flexible to allow the value to be anything that conforms to the expected interface (something like `interface MdCustomMenu`).

**Comment by trshafer** [comment]
I went back and forth on whether or not to make it an abstract class with many of the implementation details on the abstract class. I went with the interface because it's less invasive to the consumer than an abstract class.
