### ISSUE TITLE
Angular 8 Ivy / MatDialog: this._portalOutlet is undefined / Cannot read property 'hasAttached' of undefined

### ISSUE THREAD

**Issue by markusdresch** [angular/material2#15605]
#### What is the expected behavior?
MatDialog.open should show component.

#### What is the current behavior?
MatDialogContainer.attachComponentPortal throws `Cannot read property 'hasAttached' of undefined`

#### What are the steps to reproduce?
Unfortunately it can't be reproduced in stackblitz, it just works there, i'm not sure what's the difference there: https://stackblitz.com/edit/angular-eyxeek?file=angular.json<br/>

* `ng new demo --enable-ivy`
* `ng add @angular/material`
* in app.module `imports: [ BrowserAnimationsModule, MatDialogModule ]` (also tried with PortalModule)
* `ng g c demo-dialog`
* add mat-dialog-content and mat-dialog-actions to demo-dialog template
* in app.component call `MatDialog.open`, passing demo-dialog component

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All Browsers. Tested on Windows 10 x64, but should apply to all.

    "@angular/animations": "~8.0.0-beta.9",
    "@angular/cdk": "~7.3.5",
    "@angular/common": "~8.0.0-beta.9",
    "@angular/compiler": "~8.0.0-beta.9",
    "@angular/core": "~8.0.0-beta.9",
    "@angular/forms": "~8.0.0-beta.9",
    "@angular/material": "^7.3.5",
    "@angular/platform-browser": "~8.0.0-beta.9",
    "@angular/platform-browser-dynamic": "~8.0.0-beta.9",
    "@angular/router": "~8.0.0-beta.9",
    "typescript": "~3.3.3333"

#### Is there anything else we should know?
Probably related to https://github.com/angular/material2/issues/14900

**Comment by andrewseguin** [comment]
Thanks for the heads up but our library is not yet compatible with Ivy. We're currently working through the issues and getting all tests to pass
