### ISSUE TITLE
Bottomsheet is not appeared even though background is dimmed

### ISSUE THREAD

**Issue by realgsong** [angular/material2#15620]
#### What is the expected behavior?
Bottomsheet should be displayed

#### What is the current behavior?
Occasionally bottomsheet is not appeared event though background is dimmed.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

I have no exact steps to reproduce this bug but it occurs occasionally.

1. Open bottomsheet
1. Whole screen is dimmed but bottomsheet is not appeared.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material: ^7.3.4
@angular/common: ^7.2.9,
@angular/compiler: ^7.2.9,
@angular/core: ^7.2.9,
typescript: ~3.2.4
os: Android 8.0
Chrome 72.0.3626.121

#### Is there anything else we should know?
I'll add more info when I meet this error again. Please let me know if you need any debugging information or logs.

**Comment by crisbeto** [comment]
Please reopen when there is more information on when the bug happens. Usually you can run into something like this if your try to open a bottom sheet outside of the `NgZone`.
