### ISSUE TITLE
Disabling sorting on Drag & Drop list doesn't work

### ISSUE THREAD

**Issue by LordMidi** [angular/material2#15621]
#### What is the expected behavior?
Drag & Drop list items **can't** be sorted when cdkDropListSortingDisabled set.

#### What is the current behavior?
Drag & Drop list items **can** be sorted when cdkDropListSortingDisabled set.

#### What are the steps to reproduce?
https://material.angular.io/cdk/drag-drop/overview#disabled-sorting

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.3.6

**Comment by crisbeto** [comment]
These changes haven't been released yet. It looks like our docs were generated against the latest code from `master` rather than the latest stable version. See https://github.com/angular/material2/issues/15632.

**Comment by wc2582** [comment]
Also, would the documentation be updated also?
In  https://material.angular.io/cdk/drag-drop/api, the description for cdkDragDisabled and cdkDropListSortingDisabled are the same, which makes it very confusing.

**Comment by crisbeto** [comment]
Thanks for the heads-up @wc2582, I've submitted a PR to correct it.

**Comment by MadhuSudhanBhaskar** [comment]
@crisbeto this still does not work.

**Comment by kflo** [comment]
bump...!

**Comment by LordMidi** [comment]
> bump...!

should be included in the last release of Angular Material v8.
(haven't tried it yet)
