### ISSUE TITLE
typography url is wrong

### ISSUE THREAD

**Issue by anlexN** [angular/material2#15638]
#### What is the expected behavior?
https://material.angular.io/guides/typography
![image](https://user-images.githubusercontent.com/8686739/55149519-47495800-5185-11e9-89a4-992e476e43dd.png)
#### What is the current behavior?
https://material.angular.io/guide/typography

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all latest

**Comment by andrewseguin** [comment]
Can you explain the typo? I'm missing it. The link points correctly to the typography page

**Comment by anlexN** [comment]
i mean: "https://material.angular.io/guides/typography" redirect to "https://material.angular.io/". it is wrong
