### ISSUE TITLE
Duplicate export 'HttpXsrfModule'

### ISSUE THREAD

**Issue by hckhanh** [angular/material2#15662]
#### What is the expected behavior?
I try to enable Ivy. Everything is fine until Material is installed

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/6380436/55277226-44d73180-5330-11e9-8251-68d60513c632.png)

#### What are the steps to reproduce?
Please use the lastest version of Angular CLI with Ivy flag then Install Angular.
I cannot reproduce issue on stackblitz (sorry about that)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.3.7
Node: 11.12.0
OS: win32 x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cdk                      7.3.6
@angular/cli                      7.3.7
@angular/fire                     5.1.2
@angular/material                 7.3.6
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

**Comment by crisbeto** [comment]
Closing, because it doesn't look like this has anything to do with Angular Material.

**Comment by hckhanh** [comment]
Can you explain me more? Please give me more information before closing quickly like that. 😒

**Comment by crisbeto** [comment]
This is the repository for Angular Material and it doesn't look like the error has anything to do with Material.
