### ISSUE TITLE
[Feature] Select Separator

### ISSUE THREAD

**Issue by michael-letcher** [angular/material2#15669]
#### Please describe the feature you would like to request.
We should be able to add separators instead of groups. 

#### What is the use-case or motivation for this proposal?
As found in Google's Account management page, we can group without having to add large obtrusive labels & groups but just a simple separator.
![image](https://user-images.githubusercontent.com/4531036/55295843-a5b05800-545d-11e9-8854-df746f696197.png)

**Comment by ccjmne** [comment]
Hey 👋

How about using a `<mat-divider>`, like this?

```html
<mat-form-field>
  <mat-label>Favorite food</mat-label>
  <mat-select>
    <mat-option value="pizza">Pizza</mat-option>
    <mat-divider></mat-divider>
    <mat-option value="apple">Apples</mat-option>
    <mat-option value="orage">Oranges</mat-option>
    <mat-option value="apricot">Apricots</mat-option>
    <mat-divider></mat-divider>
    <mat-option value="pork">Pork</mat-option>
    <mat-option value="fish">Fish</mat-option>
    <mat-divider></mat-divider>
    <mat-option value="carrot">Carrots</mat-option>
    <mat-option value="celeri">Celeri</mat-option>
  </mat-select>
</mat-form-field>
```

See it [live on StackBlitz](https://stackblitz.com/edit/angular-material2-issue15669).

Is that what you're looking for?

**Comment by michael-letcher** [comment]
@ccjmne Ahh of course, thanks!
