### ISSUE TITLE
Critical crash bug "typeError: intl is not available"

### ISSUE THREAD

**Issue by almogyehuda** [angular/material2#15687]
#### What is the expected behavior?
Have a fallback for Intl while is not available

#### What is the current behavior?
Unexpectedly, all the app crashed and "typeError: intl is not available" error is presented at console.
Only IE-11 

#### What are the steps to reproduce?
I Don't know if we can repro this, but I'll give the background story as far as it can help.
While changing the localization - 

App crashed on this line: 
const hasV8BreakIterator = (typeof Intl !== 'undefined' && (Intl as any).v8BreakIterator);  
from this file:
https://github.com/angular/material2/blob/master/src/cdk/platform/platform.ts

with this error: "typeError: intl is not available".
This crash won't let the app start, and there is no fallback.
We manage to fix it while editing the vendor.**.js file, and adding try-catch
block for this line.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.2.1
CDK: 7.2.1
TypeScript: 3.2.2
Browsers: IE 11

#### Is there anything else we should know?
**Critical bug**, should provide hotfix.

**Comment by HawkSoftDevTeam** [comment]
We have been experiencing this as well, same fix - editing the vendor.js and inserting a try/catch.

Angular: 5.2.9
CDK: 5.2.5
TypeScript: 2.7.2
Browsers: IE 11

**Comment by almogohayon1** [comment]
@HawkSoftDevTeam Do you know the root cause?

**Comment by HawkSoftDevTeam** [comment]
@almogyehuda Not all instances of IE11 display this problem. It has gotten worse in the last month or two however. We are currently trying to find a commonality between instances of the problem. Seems to happen on Windows 2012, Windows 8.1 boxes. Currently suspecting this KB and testing: https://support.microsoft.com/en-us/help/4483187/cumulative-security-update-for-internet-explorer-december-19-2018

**Comment by HawkSoftDevTeam** [comment]
Can confirm installing a language pack induces the error state on a previously working machine. Reinstalling the KB does not fix the error.

**Comment by thealmogg** [comment]
> Can confirm installing a language pack induces the error state on a previously working machine. Reinstalling the KB does not fix the error.

@HawkSoftDevTeam Hi, That's almogyehuda.
Can you email me? Our teams can work together...
psitethea@gmail.com

**Comment by almogohayon1** [comment]
We see that issue started on our end after the following updates were installed, testing.
https://support.microsoft.com/en-us/help/4489881/windows-8-1-update-kb4489881

**Comment by almogohayon1** [comment]
We can now confirm that the issue (Angular App not being rendered)  after kb4489881 installed on win8.1/winserver2012 + IE11.
https://support.microsoft.com/en-us/help/4489881/windows-8-1-update-kb4489881
@almogyehuda @HawkSoftDevTeam @thealmogg @crisbeto

**Comment by crisbeto** [comment]
I've submitted a fix at https://github.com/angular/material2/pull/15693, but it would be nice to get it double-checked against the particular Windows version before it goes in.

**Comment by almogohayon1** [comment]
Thanks much @crisbeto! We are double checking now

**Comment by almogohayon1** [comment]
@crisbeto 
We did double check install/uninstall and the update is the root cause for that problem

**Comment by crisbeto** [comment]
Sorry, what I meant is to check whether the changes from #15693 would fix the issue.

**Comment by thealmogg** [comment]
> Sorry, what I meant is to check whether the changes from #15693 would fix the issue.

@crisbeto Yes,
We validated and that's the proper fix.

**Comment by almogohayon1** [comment]
@mmalerba Thanks much!
Any idea when it will be tagged? We're currently not functioning in production envs effecting more than 20k users daily.
Sorry for the rush but we need it ASAP.

**Comment by almogyehuda** [comment]
@crisbeto Any new with tag for this fix? We're depend on this commit right now...

**Comment by mmalerba** [comment]
this will go out with our next release on Monday
