### ISSUE TITLE
Mat-Tab - No scrollbar in mat-tab content

### ISSUE THREAD

**Issue by rsrgithub** [angular/material2#15707]
#### What is the expected behavior?
The scrollbar should appear if contents are going beyond the view area

#### What is the current behavior?
No scrollbar is appearing

#### What are the steps to reproduce?
See the following Stackblitz example. It is the same as on the official website; I have added some large content. Notice that scrollbar is on the whole page not in the respective tab. My chrome browser version is - **Version 73.0.3683.86 (Official Build) (64-bit)**
https://stackblitz.com/edit/angular-jakbce?file=app/tab-group-basic-example.html
**NOTE - Scrollbar may appear in Chrome Version 72. But for some reason scrollbar is not visible in Chrome Version 73**

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome browser version - **Version 73.0.3683.86 (Official Build) (64-bit)**

#### Is there anything else we should know?
I could see a similar issue(s) were logged before and a possible solution was height: 100% but for some reason on the specified chrome browser version, the scrollbar is not appearing.

**Comment by andrewseguin** [comment]
The tab group is not bound by any specific height. If you want to add a height, e.g. `height: 500px` or `height: 100%`. 

For example, here's the tab group with a height of 500px: https://stackblitz.com/edit/angular-jakbce-ub2wcv?file=app/tab-group-basic-example.css

**Comment by rsrgithub** [comment]
@andrewseguin 
Of course, fixed height works. But what if content's height is not predefined? i.e. contents are dynamic.
As you mentioned, setting the height to 100% should work. But when I attempt to set the height to 100%, scrollbar appeared on the whole page [which is not expected]. **Please NOTE this issue is on Version 73.0.3683.86 (Official Build) (64-bit)**

**Comment by artisanumerique** [comment]
same problem with Version 74.0.3729.108 (Build officiel) (64 bits)
