### ISSUE TITLE
cdkDragDelay input doesn't actually work

### ISSUE THREAD

**Issue by jpduckwo** [angular/material2#15710]
#### What is the expected behavior?
Bind cdkDragDelay like `[cdkDragStartDelay]="..."` works.

#### What is the current behavior?
Specifying `cdkDragStartDelay="..."` allows the app the load but doesn't actually delay. Specifying `[cdkDragStartDelay]="..."` results in error message at run time:
```
Template parse errors:
Can't bind to 'cdkDragStartDelay' since it isn't a known property of 'div'.
```

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-cdkdragdelay

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.3.6

**Comment by crisbeto** [comment]
The feature hasn't been released yet. We accidentally generated the docs against the master branch, rather than the latest stable one. See https://github.com/angular/material2/issues/15632.
