### ISSUE TITLE
Is there pagination component?

### ISSUE THREAD

**Issue by keryhu** [angular/material2#1572]
#### Bug, feature request, or proposal:
feature

#### What is the expected behavior?

a pagination  component like this : https://ng-bootstrap.github.io/#/components/pagination

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by fxck** [comment]
There's a list of existing and planned components in the README, https://github.com/angular/material2/blob/master/README.md#feature-status do you see `pagination` somewhere?

**Comment by keryhu** [comment]
I think this is a function that most people need, can consider plus。

**Comment by jelbourn** [comment]
We don't have anything like this planned in the near future.
