### ISSUE TITLE
Inject the RowContext from the CDK Table to a component inside a CdkCell

### ISSUE THREAD

**Issue by cfagudelo96** [angular/material2#15733]
#### Please describe the feature you would like to request.
Hi, I really don't know if this is possible, but I would like to define a component inside a CDK table cell that would be able to inject the current row's CdkCellOutletRowContext or the RowContext for that matter. That way the component inside the cell would know its index and element always.

I know that I can declare an input in my component to get that information, but I would like that the component gets that information from the constructor.

#### What is the use-case or motivation for this proposal?
I don't want to always have to declare an input and pass the input to a component inside one of the CDK table cells, I think it would be better if the component is able to inject that context.

#### Is there anything else we should know?
I don't know if it is technically possible to implement this, or if there is already a solution to this problem.
English is not my first language, please forgive me if I wasn't clear.

**Comment by andrewseguin** [comment]
Thank you for the feature request but we do not plan on supporting this case. For now, providing the information through inputs is the best way forward.
