### ISSUE TITLE
Angular material multiple mat-radio-group with same name/field

### ISSUE THREAD

**Issue by akvaliya** [angular/material2#15731]
I am using angular material 7.

I am using **radio-button-group**.

I have a **table design** which i have to use. So that is fixed.

When i try to use **radio-buttons in td**, i am not sure hot to give same group.

below is my html.

    <tr>
          <td>
            <mat-radio-group >
              <mat-radio-button value="maternal"></mat-radio-button>
            </mat-radio-group>
          </td>
          <td>
            <mat-radio-group >
              <mat-radio-button value="paternal"></mat-radio-button>
            </mat-radio-group>
          </td>
        </tr>

Here is stackblitz of my issue [https://stackblitz.com/edit/angular-tt2kep-woea34][1].

  [1]: https://stackblitz.com/edit/angular-tt2kep-woea34

I want one radio to be selected per row/tr. Can anyone tell me how to achieve this? Like we use `input[type=radio]` with same `ngModel`

**Comment by suleodu** [comment]
i need the solution also

**Comment by jelbourn** [comment]
You can manually bind the `name` on either the group or the radio button

**Comment by akvaliya** [comment]
@jelbourn How can we do that? Can you provide solution in my stackblitz?
