### ISSUE TITLE
Angular material Table - keyvalue pair mapping 

### ISSUE THREAD

**Issue by AngularTx** [angular/material2#15748]
#### What is the expected behavior?

I would like to have a very generic solution where I pass a key value object 
like { name: 'abc' , age : 32 } . Would like to map this data to the table . 

So when ever the new values are added in the object (like we might add address : 'abc' , without any code change would like the table to render this data. 
Columns name can be static like "key" "value" . 

I am referring to the behavior we have in angular - keyValue which will map the key and value accordingly
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All are latest versions

**Comment by andrewseguin** [comment]
You should be able to do this currently by using an `ngFor` to create your columns, and setting your columns array to be whatever keys are in the data object.

See here for a static example: https://stackblitz.com/edit/angular-mypmua?file=app/table-dynamic-columns-example.html

To make this dynamic (if data changes), just re-calculate that columns array when your data changes.
