### ISSUE TITLE
Uncaught Error: Cannot find module '@angular/http'

### ISSUE THREAD

**Issue by DAB0mB** [angular/material2#1574]
#### Uncaught Error: Cannot find module '@angular/http'

When installing `@angular/material` and importing it the following error is thrown:

```
Uncaught Error: Cannot find module '@angular/http'
```

Weird because `@angular/http` is registered as one of the dependencies, but I double checked the issue just to make sure and still had the same result.

**Comment by fxck** [comment]
I think having it under `dependencies` in package.json doesn't actually install it for you, you still have to install it yourself. And it's not necessarily a bug either, it's basically telling you that you forgot to install it, but I guess it should be stated in GETTING_STARTED(that it's required for the icon module). I guess they assumed you wouldn't use angular2 without Http.

**Comment by Urigo** [comment]
why would you need HTTP for icon?

**Comment by gdi2290** [comment]
the MdIconRegistry requires it
https://github.com/angular/material2/blob/99396a47f6c4d12e55c30ab9e6e6a7d02102a3b1/src/lib/icon/icon-registry.ts#L77

https://github.com/angular/material2/blob/99396a47f6c4d12e55c30ab9e6e6a7d02102a3b1/src/lib/icon/icon.ts#L231

**Comment by SamiAl90** [comment]
@Urigo because you are able to load iconfonts from URIs and you use the MdIconRegistry to register them.

**Comment by DAB0mB** [comment]
OK so it just seems like a `peerDependency` field is needed

**Comment by jelbourn** [comment]
Fixed in #1579, will be a part of the next release.
