### ISSUE TITLE
Table with sticky columns scroll should start after sticky column

### ISSUE THREAD

**Issue by Lakshman1996** [angular/material2#15747]
#### What is the expected behavior?
When a particular column or row is sticky, the scroll should start after the sticky element since it doesn't move.

![edited](https://user-images.githubusercontent.com/29203844/55679613-37bbd300-592c-11e9-803e-596b79e3b652.jpeg)

#### What is the current behavior?
When a sticky directive is applied the scroll starts from the place where sticky is applied even though it doesn't move.

#### What are the steps to reproduce?
Please refer the stackblitz example. Here i have made first column and first row as sticky <br/>
Table with sticky row and column: https://stackblitz.com/edit/angular-tdaevu<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material : 7.1.0
Angular: 7.1.0
Typescript: 3.1.6
Browsers: Chrome
OS: Ubuntu 16.04

#### Is there anything else we should know?
I have not been able to get workaround currently.

Cheers.

**Comment by Airblader** [comment]
As far as I know this is a known and accepted limitation as it keeps the implementation much simpler and provides a graceful fallback on IE.

**Comment by andrewseguin** [comment]
This is the sticky implementation by the browser and not something we can change. I also thought it looked funny at first, but it makes much more sense when you consider that the sticky element may not start at the edge. For example, consider your expectations if the second column was sticky, not the first. Where should the scrollbar be?
