### ISSUE TITLE
Multiline md-input or textarea

### ISSUE THREAD

**Issue by Mc128k** [angular/material2#1575]
Hi, is a multline version of md-input implemented? I don't see it in the docs. I'm looking for something like this:
https://material.angularjs.org/latest/demo/input (see the biography field)

(didn't find any relevant question, close if it's duplicate, thanks)

**Comment by fxck** [comment]
I'm sure you checked the README and read the list of features, planned and implemented, right?

https://github.com/angular/material2/blob/master/README.md#feature-status

So you surely must know, that there already is an issue created for textarea(https://github.com/angular/material2/issues/546), which you must have scrolled thru and you found out that there is an open PR for it https://github.com/angular/material2/issues/1562

Or you didn't? And you did it the hard way, by searching for "textarea" https://github.com/angular/material2/issues?utf8=%E2%9C%93&q=textarea 

![image](https://cloud.githubusercontent.com/assets/1303561/19629069/adc12fd2-996c-11e6-91b0-ac6fee5ea433.png)


Right, right?

**Comment by Mc128k** [comment]
-.- how the heck couldn't I see this. I also searched in the issues.
Sorry for the wasted time. Won't open any more issues.

**Comment by fxck** [comment]
It happens to the best of us.
