### ISSUE TITLE
_element should not be private in MatSelectionList

### ISSUE THREAD

**Issue by hughanderson4** [angular/material2#15756]
#### What is the expected behavior?

need access to _element: ElementRef of MatSelectionList but it's currently private.
i need to scroll MatSelectionList to the top by accessing the element.scrollTop

#### What is the current behavior?

can't get access to _element because it's private.

#### What are the steps to reproduce?

My use case is I have dynamically added an item to the list, and it's at the top.  but the user could be looking at the bottom of the list.  i need to scroll the list to the top at that time.  it would be really easy if i could have access to the ElementRef.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

7.3.5

#### Is there anything else we should know?

I think it is not harmful to allow access to the ElementRef.

**Comment by hughanderson4** [comment]
[Here's a link to the line of code to change.](https://github.com/angular/material2/blob/833d428fa423d40f276cd93ebb1cf83c73b64a88/src/lib/list/selection-list.ts#L369)  I think changing "private" to "public" would be enough.

**Comment by crisbeto** [comment]
If you're getting a hold of the `MatSelectionList` with a `ViewChild` or `ContentChild`, you can get the `ElementRef` like this:

```ts
@ViewChild(MatSelectionList, {read: ElementRef})
```

**Comment by jelbourn** [comment]
What @crisbeto said.

**Comment by hughanderson4** [comment]
Hey thanks! It works.
