### ISSUE TITLE
Implement ControlValueAccessor for cdkDropList

### ISSUE THREAD

**Issue by Airblader** [angular/material2#15768]
#### Please describe the feature you would like to request.

It would be nice if `cdkDropList` provided a ControlValueAccessor implementation so this works:

```
<app-list cdkDropList [(ngModel)]="items">
  <app-item cdkDrag *ngFor="let item of items" [item]="item"></app-item>
</app-list>
```

#### What is the use-case or motivation for this proposal?

Make it easier for users to use drag and drop in forms.

**Comment by jelbourn** [comment]
This isn't something we plan on adding, but you could create a custom directive to put on top of `cdkDropList`

**Comment by Airblader** [comment]
Yes, that is my plan, I just figured it could be useful to have in the framework. Fair enough, thanks!
