### ISSUE TITLE
Document cdk-drag-handle class

### ISSUE THREAD

**Issue by Airblader** [angular/material2#15767]
#### Please describe the feature you would like to request.

The fact that `cdkDragHandle` adds a `cdk-drag-handle` class is currently undocumented.

**Comment by jerome-nelson** [comment]
Would it be ok to take this issue? Seems do-able

**Comment by Airblader** [comment]
Yeah, from my side go ahead if you want and thanks for taking care of it. :-) There already is a Styling section in the docs, I think it should just be added there.
