### ISSUE TITLE
Custom header name in Table with expandable rows

### ISSUE THREAD

**Issue by heliomarcellus** [angular/material2#15763]
#### Please describe the feature you would like to request.

Using the [exemple](https://run.stackblitz.com/api/angular/v1?file=app%2Ftable-expandable-rows-example.ts) provided in docs, I realized that is not possible customize the header string, being the same name of the variable `columnsToDisplay`.

#### What is the use-case or motivation for this proposal?

Being able to render a custom text in the header and not necessarily the `columnsToDisplay` array strings, which relates to `ELEMENT_DATA` fields 

#### Is there anything else we should know?

No.

Thanks!

**Comment by jelbourn** [comment]
That particular example uses an `ngFor` for cell templates, but they can also be manually written out with whatever custom template you need. Several of the other examples do this.

**Comment by heliomarcellus** [comment]
Thank you!
