### ISSUE TITLE
bug: tooltip remains visible after clicking the button

### ISSUE THREAD

**Issue by Miiekeee** [angular/material2#1577]
#775

I have the situation where the tooltip remains visible and can't be removed after clicking a button which redirects me to a different page.

![capture](https://cloud.githubusercontent.com/assets/20771477/19639043/f1898c68-99d6-11e6-80eb-752b64b23f21.PNG)

This tooltip is from this button 
![capture2](https://cloud.githubusercontent.com/assets/20771477/19639075/13e8dd68-99d7-11e6-855e-f68f0d3e4f06.PNG)

**Comment by BobBDE** [comment]
Hi,

It is a know issue, please see #1111

**Comment by jelbourn** [comment]
Fixed by #1470
