### ISSUE TITLE
I have five elements in the ngfor list. one of them jumps the order and moves to top when dragged.

### ISSUE THREAD

**Issue by digish777** [angular/material2#15796]
I have five elements in the *ngfor list. one of them jumps the order and moves to top when dragged.

I could not find the reason why it was behaving so. the same type of behavior is done by another element in the list. they are all div containers containing different items. but why this alone behaves so I am not sure. 

it just jumps sequence and goes to top. 

At times, the item in the top would refuse to move. 

my list is single ngfor div with div repeating inside with difference type of content inside.

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
