### ISSUE TITLE
Badge maximum numbers

### ISSUE THREAD

**Issue by kkseven07** [angular/material2#15829]
#### Please describe the feature you would like to request.
Set the max property to cap the value of the badge content.

#### What is the use-case or motivation for this proposal?
https://material-ui.com/demos/badges/ - example from React material-ui library

#### Is there anything else we should know?
It's really disappointing that more than 2 digits inside the badge become hidden. Workarounds like css look so ugly

**Comment by jelbourn** [comment]
I think this feature is something that would be more appropriate in application code
