### ISSUE TITLE
Centering mat-hint

### ISSUE THREAD

**Issue by danieldanielecki** [angular/material2#15831]
#### Please describe the feature you would like to request.

Add centering to **mat-hint** element, maybe there could by any directive for others form elements as well.

#### What is the use-case or motivation for this proposal?

Text centering for **mat-hint** in some scenarios when centering a hint for an input is desired.

#### Is there anything else we should know?

Currently it adds **mat-form-field-hint-spacer** class, and due to the reason cannot center text in **mat-hint**. Right now to make it working I have to make these 3 following tricks to make it working:
```
mat-form-field {
  text-align: center;
}

mat-hint {
  width: 100%;
}

.mat-form-field-hint-spacer {
  display: none;
}
```

**Comment by crisbeto** [comment]
Closing, because centered hint text isn't in the Material design spec.
