### ISSUE TITLE
Unexpected value 'OverlayContainer' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by sridhar-natuva** [angular/material2#15861]
#### What is the current behavior?
In the browser console i get this error.
`Unexpected value 'OverlayContainer' imported by the module 'AppModule'. Please add a @NgModule annotation.`

#### What are the steps to reproduce?
importing OverlayContainer n ngmodule.
` import { OverlayContainer } from '@angular/cdk/overlay';`
and in imports
`  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    MaterialModule,
     OverlayContainer
  ],`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.3.8
Node: 10.5.0
OS: win32 x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/material                 7.3.7
@ngtools/webpack                  6.1.5
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.9.2

**Comment by jelbourn** [comment]
Looks like you're missing `OverlayModule`
