### ISSUE TITLE
Placeholder not working when using appearance other than legacy for a custom form field control

### ISSUE THREAD

**Issue by gauravsoni119** [angular/material2#15867]
#### What is the expected behavior?
It should render placeholder for other appearances(fill, standard and outline).

#### What is the current behavior?
Currently, the placeholder is rendered only for legacy appearance.

#### What are the steps to reproduce?
Add appearance input property with value other than legacy on mat-form-field for custom form field  <br/>
StackBlitz link: https://stackblitz.com/edit/angular-fbrvrr?file=app%2Fform-field-custom-control-example.ts<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular material version - 7.3.7
OS - Ubuntu
Browser - Chrome, Firefox

#### Is there anything else we should know?
I am writing a custom form field and facing the same issue. So I think the issue is not related to the example given in documentation but maybe with in code.

**Comment by crisbeto** [comment]
Providing the placeholder as the floating label is something that we'll deprecate eventually. You should use the `mat-label` element to provide it instead.
