### ISSUE TITLE
Angular MatSelect not displaying correctly

### ISSUE THREAD

**Issue by zyi103** [angular/material2#15874]
#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/25201475/56517598-4ea51c80-650b-11e9-9695-59dd9927411f.png)

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/25201475/56517647-68defa80-650b-11e9-9b11-28f14c6ca866.png)

#### What are the steps to reproduce?
(from official website)
https://material.angular.io/components/select/overview
https://stackblitz.com/angular/nvpyvykdldxn?file=app%2Fselect-form-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current Version: 7.3.7

#### Is there anything else we should know?
The example on the https://material.angular.io/components/select/overview is not displaying properly

**Comment by crisbeto** [comment]
Material supports two kinds of selects: a custom one with our own styling and animations (`mat-select`), as well as putting a native `select` element inside a `mat-form-field`. In the docs examples the "native select" refers to the built-in `select` element.
