### ISSUE TITLE
BottomSheet viewContainerRef parameter doesn't work

### ISSUE THREAD

**Issue by vagsa2** [angular/material2#15879]
#### What is the expected behavior?

If we pass viewContainerRef when open bottom sheet, it should be opened in this container 

#### What is the current behavior?

This parameter seems like it is ignored

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-zu4xeo?file=app%2Fbottom-sheet-overview-example.ts

click openfile and bottom sheet should be opened in red square

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by crisbeto** [comment]
The `viewContainerRef` only tells Angular where the bottom sheet should be in Angular's _logical_ tree, not in the DOM. If you want to put it in a different place in the DOM, you can provide a custom `OverlayContainer`.
