### ISSUE TITLE
Tooltip theme mixin does not use $theme variable

### ISSUE THREAD

**Issue by jrabbe** [angular/material2#15886]
#### What is the expected behavior?

Tooltip should be taking its background color from the `$theme` variable in the `mat-tooltip-theme` mixin.

#### What is the current behavior?

Tooltip is using a color value hardcoded inside the theme mixin.

https://github.com/angular/material2/blob/master/src/lib/tooltip/_tooltip-theme.scss#L16

#### What are the steps to reproduce?
n/a

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current

**Comment by jelbourn** [comment]
This currently works as intended; the background color is the same for both light and dark themes.
