### ISSUE TITLE
Sticky columns show scrolled data behind them

### ISSUE THREAD

**Issue by stevencraigadesa** [angular/material2#15883]
#### What is the expected behavior?
Sticky columns should not resize to allow scrolling column data to show between them.

#### What is the current behavior?
When browser is maximized and get data on the table when resize the screen the sticky columns resize and show data from the scolled columns between them.

#### What are the steps to reproduce?
Start out with a full size screen and then reduce the size of the screen.  The sticky columns size changes and allows the scrolled data to display in the gaps.

![image](https://user-images.githubusercontent.com/40296678/56586873-82854e00-65ae-11e9-8211-ce78c76e6ca8.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7, Material 2

#### Is there anything else we should know?
Refresh are the resize it fixes iteself.

**Comment by andrewseguin** [comment]
I'm unable to reproduce this, can you re-open with a reproducible case?

Seems fine here https://stackblitz.com/edit/angular-ay2dr9?file=app/table-sticky-columns-example.css

**Comment by stevencraigadesa** [comment]
That example also has the same issue when you make more than one column sticky.  I made the first 3 columns sticky and the 4th column starts to display between column 2 and 3.

![image](https://user-images.githubusercontent.com/40296678/56601581-896d8a00-65c9-11e9-95e6-20bbbfa1f70d.png)
