### ISSUE TITLE
indicator rotation customization 

### ISSUE THREAD

**Issue by feech** [angular/material2#15884]
#### Please describe the feature you would like to request.
customize rotation angle for indicator  

#### What is the use-case or motivation for this proposal?
expansion indicator rotates on 180 deg when state changes (and its directions changes from bottom to top)
there is a demand the indicator changes direction from right to bottom

it's already possible to change view and initial position of the indicator by setting the style
`.mat-expansion-panel .mat-expansion-indicator::after {
  border-width: 0 1px 1px 0;
  padding: 5px;
  transform: rotate(-45deg);
}`

but I'm failed to find the way how to customize the final position

#### Is there anything else we should know?
the code defines the final position 

https://github.com/angular/material2/blame/6a7327351f76da14844f8386c6b29b06ec7c314e/src/lib/expansion/expansion-animations.ts#L53

**Comment by jelbourn** [comment]
We have no plans to support changing the expansion indicator at this time.
