### ISSUE TITLE
MatTabContent not working inside ngIf

### ISSUE THREAD

**Issue by Malex** [angular/material2#15881]
I am using a switch between lazy and eagerly loaded tabs depending on application parameters, but this does not work the moment i actually activate the lazy-loading structure, since apparently the ng-template is not attached if it is inside an ngIf / else branch of ngIf.

The structure I'm trying to achieve is something along the lines of:
<ng-container *ngIf="doCache else lazy">something</ng-container>
<ng-template #lazy><ng-template matTabContent>something lazy</ng-template></ng-template>

Of course I cannot really put the matTabContent on the parent template otherwise it ovverrides the container.
I tried using 2 cointainers with switching *ngIf, but still the semplace of the second half doesnt get evaluated

**Comment by Airblader** [comment]
It would he good if you posted an actual example rather than two incomplete and incorrect lines of code.

**Comment by jelbourn** [comment]
`MatTab` doesn't support using `ngIf` or `ngFor` on `MatTabContent`. You should put the `ngIf` inside of the `MatTabContent` template.
