### ISSUE TITLE
input field behaving lag in angular 5

### ISSUE THREAD

**Issue by kishoreRedd** [angular/material2#15890]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by kishoreRedd** [comment]
other than angular applications it is working fine it is taking not much time take to show data , 
it is taking lot of time to show data , i am using mat-input field 
i tested with normal html input filed it is also working like that only.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
