### ISSUE TITLE
Server side pagination with mat-paginator

### ISSUE THREAD

**Issue by raghufsmk** [angular/material2#15892]
#### Please describe the feature you would like to request.
Server side pagination with mat-paginator. Onclick of page icon make WebAPI call to get data for specific page and render same in browser

#### What is the use-case or motivation for this proposal?
WebAPI is giving certain page data but table is not rendering properly with pagination icons

**Comment by jelbourn** [comment]
The paginator component only deals with page state; it doesn't actually do the pagination. You can use it for either client-side or server-side operations.
