### ISSUE TITLE
md-button text not vertically aligned - (Chrome on Android)

### ISSUE THREAD

**Issue by tomscript** [angular/material2#1590]
#### Bug, feature request, or proposal:

md-button text is just slightly misaligned. Notice in the screenshot 'RAISED' is maybe 3px higher than mid center. I can only verify this misalignment on Chrome (54.0.2840.68) I'm on Android 7.1.1; Nexus 6P Build/NPF10C

![image](https://cloud.githubusercontent.com/assets/3085610/19669466/564c7272-9a14-11e6-9946-ef023306f7e3.png)
#### What is the expected behavior?

Text should be vertically aligned.
#### What is the current behavior?

Text is not vertically aligned.
#### What are the steps to reproduce?

View the demo site (https://material2-app.firebaseapp.com/) on Chrome using Android N.
#### Which versions of Angular, Material, OS, browsers are affected?

Chrome: 54.0.2840.68
Android 7.1.1; Nexus 6P Build/NPF10C

**Comment by jelbourn** [comment]
@tinayuangao is this still valid?

**Comment by jelbourn** [comment]
Looking at this now, but buttons look right to me on Android. Closing as not reproducible, feel free to open a new issue if there's still a problem.
