### ISSUE TITLE
Slider handlebar not moving when dragged

### ISSUE THREAD

**Issue by doorman02** [angular/material2#1595]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the slider handlebar is dragged it should move with the mouse. 
Not working anymore after updating to 2.0.0-alpha.9.3

#### What is the current behavior?
The handlebar doesn´t move with the mouse. However when pressing somewhere on the slider the handlebar jumps to the clicked location.

#### What are the steps to reproduce?
Here is a plunkr with the slider working because it's based on the template plunkr which probably doesn't have the latest Material Design version 9-3
http://plnkr.co/edit/7ZtyjyPNkc1QADQEmusH?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.1.0, Material Design 2.0.0-alpha.9-3

**Comment by fxck** [comment]
Are you sure you followed the geting started guide and you installed and imported hammerjs, which is a requirement for slider and slide-toggle?

Plunker temlate **is** on 9-3.

**Comment by doorman02** [comment]
Thanks for your feedback, after a closer look the problem was that I was importing the Material modules before importing the BrowserModule from '@angular/platform-browser'. After moving the import statement for MD after it the slider was fixed.
