### ISSUE TITLE
Add onAction observable for simple snackbars

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#1616]
Adds a way to be notified when the action is invoked.

**Comment by rolandjitsu** [comment]
Is this still being worked on or what's the status?

**Comment by rolandjitsu** [comment]
Made a PR, [1729](https://github.com/angular/material2/pull/1729), but the tests on saucelabs are timing out.

**Comment by rolandjitsu** [comment]
Closed my PR, messed up some commits. Is anyone working on this at this point or can I give it another try?

**Comment by jelbourn** [comment]
@josephperrott?

**Comment by michaeljota** [comment]
If the PR got merge, this should this still open? I think this can be safely closed.
