### ISSUE TITLE
Card that slides more information up when you click it.

### ISSUE THREAD

**Issue by ripbandit** [angular/material2#1621]
#### Bug, feature request, or proposal:

Feature Request 
#### What is the expected behavior?

A card that slides up more information when clicked, kind of like what Materialize has implemented [here](http://materializecss.com/cards.html#reveal).
#### What is the current behavior?

Currently doesn't exist.
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by jelbourn** [comment]
Closing this since we consider the card to just be a dumb container, so this would be something custom inside the card.
