### ISSUE TITLE
Animation of md-checkbox doesn't end

### ISSUE THREAD

**Issue by mxii** [angular/material2#1627]
#### Bug, feature request, or proposal:
- Bug

#### What is the expected behavior?
- Half-transparent circle around the checkbox should be removed after animation ends.

#### What is the current behavior?
- The half-transparent circle stays visible until you click anywhere else!

#### What are the steps to reproduce?
- Visit https://material2-test.firebaseapp.com/checkbox
- Click the first checkbox and do not click anywhere else
- circle around that checkbox stays visible

#### What is the use-case or motivation for changing an existing behavior?
- better UX

#### Which versions of Angular, Material, OS, browsers are affected?
- latest Material? Idk when versions will be uploaded to https://material2-test.firebaseapp.com/ ..
- Chrome, IE, (not tested any other browser)

**Comment by fxck** [comment]
It's not really an animation, it's a placeholder and was likely fixed by https://github.com/angular/material2/pull/1611 which is already in master, just not released yet.

**Comment by mxii** [comment]
@fxck thanks!
