### ISSUE TITLE
bug(menu): menu doesn't work in full screen mode

### ISSUE THREAD

**Issue by quanterion** [angular/material2#1628]
If I put md-toolbar with md-menu on a div element and go into full screen mode using

```
var elem = document.getElementById("my-div-id");
if (elem.requestFullscreen) {
  elem.requestFullscreen();
}
else if (elem.webkitRequestFullScreen) {
  elem.webkitRequestFullScreen();
}
```

then md-menu doesn't show at all

plunker: http://plnkr.co/edit/NCYYbZklZIdYra0xYsfF?p=preview
PS: you should launch it in separate window in order to process fullscreen requests

Environment: Angular 2.0.1 with Material alpha-9-3 using ng-cli
Browsers: latest Chrome & Firefox

**Comment by quanterion** [comment]
Also the same problems appears with dialog, tooltip - all overlay-based components. It looks like overlay service should be tweaked to support full-screen mode (i.e. temporarily use another ElementRef to inject overlays)

**Comment by willshowell** [comment]
Should be closed via #1949, right?

**Comment by jelbourn** [comment]
Yep

**Comment by nancy-ly** [comment]
Can this be re-opened? I am still able to reproduce this issue: https://codepen.io/anon/pen/zRXqwm

**Comment by quanterion** [comment]
@nancy-ly This is a library for Angular 2 and later, not for Angular 1.x

**Comment by arlowhite** [comment]
@jelbourn this should be reopened
https://angular-material2-issue-siqbmy.stackblitz.io

**Comment by quanterion** [comment]
you should provide full screen overlay:

`{ provide: OverlayContainer, useClass: FullscreenOverlayContainer },`

```
import {
  OverlayContainer,
  FullscreenOverlayContainer
} from '@angular/cdk/overlay';
```
