### ISSUE TITLE
md-list row overlap when put inside another md-list

### ISSUE THREAD

**Issue by ipoj** [angular/material2#1629]
#### Bug, feature request, or proposal:
bug(maybe)

#### What is the expected behavior?
each row(md-list-item) not overlap

#### What is the current behavior?
md-list row overlap when put inside another md-list

#### What are the steps to reproduce?

check this http://plnkr.co/edit/anPuBx3yCLg2ssaUPyNX
click on first level item to show detail

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?

display another list when click on list item 

#### Which versions of Angular, Material, OS, browsers are affected?

^2.0.0-alpha.9-3

**Comment by jelbourn** [comment]
Nesting md-lists isn't something we support
