### ISSUE TITLE
ng-bootstrap Modal and md-button compatibility

### ISSUE THREAD

**Issue by alanpurple** [angular/material2#1630]
since md-dialog has no tools for input ( no ways to access dialog instance also )
I had to use ng-bootstrap NgbModal

and this cause problem with mdButton

when this button is not focused before click, it's okay

but when focused, if I click and modal came, then "changed" property of button(with md-button) element cause "hasChangedAfterItWasCheckedException" since changed become false right after modal came

Is there any wise solution?

**Comment by jelbourn** [comment]
@alanpurple Please follow the issue template if you're reporting a bug. I can't tell from your description what's actually going on.

WRT dialog, you get the instance of the component from `dialogRef.componentInstance`

**Comment by alanpurple** [comment]
@jelbourn  thx, MdDialog has no trouble with MdButton,  only NgbModal has a trouble with that.

solved
