### ISSUE TITLE
bug(dialog): opening a dialog, scrolls my page to the top.

### ISSUE THREAD

**Issue by ericjim** [angular/material2#1633]
#### Bug, feature request, or proposal:

Bug.
#### What is the expected behavior?

Whenever I open a dialog, my page scrolls to the top.
#### What is the current behavior?

I would like my dialog to be instantiated at the center of what is currently in view.
#### What are the steps to reproduce?

Create a page with a long list, and open a dialog while at the bottom of the list.
#### What is the use-case or motivation for changing an existing behavior?

I would like to have a list, where each entry can produce a dialog.
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.1.0, @angular/material": "2.0.0-alpha.9-3, Chrome 54
#### Is there anything else we should know?

<3

**Comment by crisbeto** [comment]
For future reference, this is caused by the `.md-overlay-container` being absolutely positioned. Switching it to `fixed` will fix it. It probably wasn't noticed, because all of the scrollable content in the demo app is within a `position: fixed` element.
