### ISSUE TITLE
slide-toogle : change not fired with drag'n drop

### ISSUE THREAD

**Issue by zigzago** [angular/material2#1639]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

with
`<md-slide-toggle [(ngModel)]="test" (change)="printTest($event.checked)">`
I expect
printTest() is called with click or drag'n drop

#### What is the current behavior?

printTest() is called on a click BUT NOT on drag'n drop. In both cases, the value "test" is updated though.

workaround : 

` <md-slide-toggle [(ngModel)]="test" (ngModelChange)="printTest($event)">`

#### Which versions of Angular, Material, OS, browsers are affected?

2.0.0-alpha.9-3 , last chrome or firefox

**Comment by DevVersion** [comment]
This should be fixed with https://github.com/angular/material2/commit/0b5b6f2fda62a4977f03c761e02ff2eb934cf52f, but is not released yet.
