### ISSUE TITLE
[md-button] click on to hide Template-Driven Forms/Reactive Forms  will redirect url 

### ISSUE THREAD

**Issue by keryhu** [angular/material2#1649]
#### Bug, feature request, or proposal:

bug
#### What is the expected behavior?

hidden form will never redirect url or reload page
#### What is the current behavior?

I build a child component --

html:

```
<p *ngIf="showContent" (click)="cancelContent()">
  click me show form
</p>

<form #heroForm="ngForm" *ngIf="!showContent"  (ngSubmit)="onSubmit()">
  <input type="text" [(ngModel)]="name" name="name">

  <button type="button" (click)="cancelForm()">
    hiddenForm
  </button>

  <button md-button  (click)="cancelForm()">hiddenForm2</button>

</form>

```

and child component:

```
private showContent:boolean=true;
 cancelContent(){
    this.showContent=false;
  }

  cancelForm(){
    this.showContent=true;
  }
```

init page is --

> <p>click me show form</p>

when i click it , will show a input form . then i click **"hiddenForm"**button, the form can hidden expected.  

but if i click **"hiddenForm2" [md-button].**  the url will **redirect** to **"url/?name="**,and page **reload** ..

//-------------

if i change to **Reactive Forms**:

```
<form [formGroup]="form" *ngIf="!showContent"
      (ngSubmit)="onSubmit(form.value)" >

    <input type="text" formControlName="name">

 <button type="button" (click)="cancelForm()">
    hiddenForm
  </button>

  <button md-button  (click)="cancelForm()">FLAT</button>

</form>
```

**result:**

**hiddenForm"button** clicked work fine, neither reload nor redirect .

but --click **"hiddenForm2" [md-button]**, the page **redirect to "url/?",and page reload**.
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
#### Which versions of Angular, Material, OS, browsers are affected?

angular2 2.1.1 material: 2.0.0-alpha.9-3

**Comment by jelbourn** [comment]
Closing this since I think this is the behavior of the browser and not anything related to Angular Material. Feel free to open a new issue if there is some bug in Angular Material that should be resolved.
