### ISSUE TITLE
npm install --save @angular/material failed 

### ISSUE THREAD

**Issue by dahlia05** [angular/material2#1654]
#### Bug, feature request, or proposal:

I am not sure if this defect has been discussed .
However I am using all latest version of angular cli and nodejs and  after running 
npm install --save @angular/material 

I am getting following warning message 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})

and after running ng serve

I am getting so many error . Most of them are complaining Cannot find module '@angular/core'.
#### What is the current behavior?

ERROR in [default] E:\rafflesia_sdp\material2\node_modules\@angular\material\cor
e\gestures\MdGestureConfig.d.ts:4:39
Cannot find name 'HammerManager'.

ERROR in [default] E:\rafflesia_sdp\material2\node_modules\@angular\material\sli
de-toggle\slide-toggle.d.ts:68:19
Cannot find name 'HammerInput'.

ERROR in [default] E:\rafflesia_sdp\material2\node_modules\@angular\material\sli
der\slider.d.ts:61:19
Cannot find name 'HammerInput'.

ERROR in [default] E:\rafflesia_sdp\material2\node_modules\@angular\material\sli
der\slider.d.ts:63:24
Cannot find name 'HammerInput'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\button-toggle
\button-toggle.d.ts:1:70
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\button-toggle
\button-toggle.d.ts:2:37
Cannot find module '@angular/forms'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\button-toggle
\button-toggle.d.ts:3:27
Cannot find module 'rxjs/Observable'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\button\button
.d.ts:1:58
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\card\card.d.t
s:1:36
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\checkbox\chec
kbox.d.ts:1:72
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\checkbox\chec
kbox.d.ts:2:37
Cannot find module '@angular/forms'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\a11y\foc
us-trap.d.ts:1:27
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\a11y\ind
ex.d.ts:1:36
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\a11y\liv
e-announcer.d.ts:1:28
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\core.d.t
s:1:36
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\gestures
\MdGestureConfig.d.ts:1:36
Cannot find module '@angular/platform-browser'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\gestures
\MdGestureConfig.d.ts:4:39
Cannot find name 'HammerManager'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\line\lin
e.d.ts:1:48
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\overlay\
overlay-directives.d.ts:1:98
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\overlay\
overlay-ref.d.ts:3:27
Cannot find module 'rxjs/Observable'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\overlay\
overlay.d.ts:1:41
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\overlay\
position\connected-position-strategy.d.ts:2:27
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\overlay\
position\overlay-position-builder.d.ts:3:27
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\portal\d
om-portal-host.d.ts:1:55
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\portal\p
ortal-directives.d.ts:1:107
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\portal\p
ortal.d.ts:1:82
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\ripple\r
ipple.d.ts:1:92
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\core\rtl\dir.
d.ts:1:50
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\dialog\dialog
-config.d.ts:1:33
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\dialog\dialog
-container.d.ts:1:48
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\dialog\dialog
-ref.d.ts:2:27
Cannot find module 'rxjs/Observable'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\dialog\dialog
.d.ts:1:46
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\grid-list\gri
d-list.d.ts:1:98
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\grid-list\gri
d-tile.d.ts:1:66
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\icon\icon-reg
istry.d.ts:1:21
Cannot find module '@angular/http'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\icon\icon-reg
istry.d.ts:3:27
Cannot find module 'rxjs/Observable'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\icon\icon.d.t
s:1:109
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\input\input.d
.ts:1:102
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\input\input.d
.ts:2:37
Cannot find module '@angular/forms'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\input\input.d
.ts:4:27
Cannot find module 'rxjs/Observable'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\list\list.d.t
s:1:87
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\menu\menu-dir
ective.d.ts:1:53
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\menu\menu-ite
m.d.ts:1:37
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\menu\menu-tri
gger.d.ts:1:95
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\menu\menu.d.t
s:1:36
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\module.d.ts:1
:36
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\progress-bar\
progress-bar.d.ts:1:36
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\progress-circ
le\progress-circle.d.ts:1:66
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\radio\radio.d
.ts:1:87
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\radio\radio.d
.ts:2:37
Cannot find module '@angular/forms'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\select\index.
d.ts:1:36
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\sidenav\siden
av.d.ts:1:101
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\slide-toggle\
slide-toggle.d.ts:1:76
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\slide-toggle\
slide-toggle.d.ts:2:37
Cannot find module '@angular/forms'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\slide-toggle\
slide-toggle.d.ts:3:27
Cannot find module 'rxjs/Observable'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\slide-toggle\
slide-toggle.d.ts:68:19
Cannot find name 'HammerInput'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\slider\slider
.d.ts:1:66
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\slider\slider
.d.ts:2:37
Cannot find module '@angular/forms'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\slider\slider
.d.ts:61:19
Cannot find name 'HammerInput'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\slider\slider
.d.ts:63:24
Cannot find name 'HammerInput'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\snack-bar\sna
ck-bar-config.d.ts:1:33
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\snack-bar\sna
ck-bar-container.d.ts:1:29
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\snack-bar\sna
ck-bar-ref.d.ts:2:27
Cannot find module 'rxjs/Observable'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\snack-bar\sna
ck-bar.d.ts:1:36
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\tabs\ink-bar.
d.ts:1:37
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\tabs\tab-cont
ent.d.ts:1:46
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\tabs\tab-labe
l-wrapper.d.ts:1:27
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\tabs\tab-labe
l.d.ts:1:46
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\tabs\tabs.d.t
s:1:55
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\tabs\tabs.d.t
s:6:27
Cannot find module 'rxjs/Observable'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\toolbar\toolb
ar.d.ts:1:36
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\toolbar\toolb
ar.d.ts:2:25
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\toolbar\toolb
ar.d.ts:3:27
Cannot find module '@angular/core'.

ERROR in [default] E:\rafflesia_sdp\node_modules\@angular\material\tooltip\toolt
ip.d.ts:1:85
Cannot find module '@angular/core'.
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.81 kB       0
webpack: bundle is now VALID.
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by RoxKilly** [comment]
Why do you feel this is an issue with Angular Material itself rather than your build setup?

**Comment by dahaupt** [comment]
As @RoxKilly already says, I think your setup is broken and your imports aren't done correctly. That's why you get so many "**Cannot find module XYZ**" errors. 

You should try to follow the [Getting Started](https://github.com/angular/material2/blob/master/GETTING_STARTED.md).

**Comment by alanpurple** [comment]
those warnings are unharmful.
and those errors are caused by incorrect settings( mb tsconfig.json  )

**Comment by dahlia05** [comment]
@RoxKilly , Thanks for your quick response. The reason, I have created a number of angular2 project and as long as I am not installing @angular/material, Its ok. no complain . However, the moment I am installing @angular/material. The build is broken.  So I was thinking what I have I done wrong. 

@alanpurple , thanks  for your response . I will take a look .

**Comment by jineshmehta16** [comment]
when I install npm install --save @angular/material
**It gives me following response :** 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**But this are just warnings , but when I try to actually import it in app.module.ts npm start breaks :** 
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\My Projects\angular-quickstart-master\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\My Projects\angular-quickstart-master\npm-debug.log



I am not sure what is the exact issue. Can any one please help.
