### ISSUE TITLE
[md-radio] required attribute doesn't work for md-radio-group or md-radio-button

### ISSUE THREAD

**Issue by chase0213** [angular/material2#1656]
#### Bug, feature request, or proposal:

bug, (or feature request)

#### What is the expected behavior?

`required` attribute is available in `md-radio-group` or `md-radio-button`,
i.e., when a user clicks submit button in a form without selecting any required radio options,
the form should tell the user that (s)he needs to select one of those.

refs. w3c description about "input required"
https://www.w3.org/TR/html5/forms.html#attr-input-required

#### What is the current behavior?

`required` attribute is ignored without any errors or warnings.

#### What are the steps to reproduce?

Visit the following plunker page:
http://plnkr.co/edit/6Y2L1cLwYX2TOXv5UDOu?p=preview

In the plunker, we have 2 forms, one with naive html5 radio buttons and the other with md-radio-group and md-radio-buttons.
In the upper form, we cannot 'save' without selecting any options,
but in the lower one, it seems we can 'save' without selecting anything.

#### What is the use-case or motivation for changing an existing behavior?

Client side validation same as md-input or naive `input type='radio'`.

#### Which versions of Angular, Material, OS, browsers are affected?

angular: 2.0.2
material: 2.0.0-alpha.9-3
os: OSX El Capitan 10.11.6
browser: Google Chrome 54.0.2840.71 (64-bit)

**Comment by krigton** [comment]
@jelbourn @kara Hello, do we intend to fix this. I started to work on this by adding the `required` property on the `md-radio-group` and automatically updating the attribute on the `md-radio-button`. Is that ok? Should I create the PR? 
thanks

**Comment by emreavsar** [comment]
is this still untouched? i'm very interested in that pr

**Comment by willshowell** [comment]
@emreavsar looks like @krigton put together a PR (https://github.com/angular/material2/pull/1690) that was approved but stalled for a few months and closed

**Comment by RenaldasK** [comment]
This is still an issue.
