### ISSUE TITLE
md-grid-list/md-grid-tile jams IE11 with bigger data lists

### ISSUE THREAD

**Issue by fedu** [angular/material2#1658]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Works normally in Chrome. IE11 jams.

#### What is the current behavior?
With `md-grid-list` as a wrapper to a simple table list of data, causes IE11 to jam when there are 100+ data rows. All ajax queries, form usage and renders get very slow and can halt the browser for few minutes on slower machines.

When md-grid-list is removed, everything works normally again.

#### What are the steps to reproduce?
```<md-grid-list gutterSize="8px" cols="1" rowHeight="800"><md-grid-tile><table><tr><td>.... data ...</td></tr></table>```

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-alpha-8.2
IE11 (Version: 11.321.14393.0)
Windows 10 64bit

**Comment by crisbeto** [comment]
I tried giving this a quick try, but I couldn't get IE 11 to lock up with a grid list of 400+ items. Can you post a live code sample? Also it might be a good idea to try with a newer version of Material first.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via Plunker.
