### ISSUE TITLE
Packaged version is using System.register instead of commonjs

### ISSUE THREAD

**Issue by UnwrittenFun** [angular/material2#167]
How do you propose this to be used without SystemJS?

I am currently using webpack for my angular 2 app and have been following this repo closely, however with alpha.0 it seems it can only be consumed if you are using SystemJS due to the packages using System.register.

It would be nice to see this usable in a commonjs environment.

**Comment by jelbourn** [comment]
@UnwrittenFun Hmm, this looks like a bug in the release process. It was supposed to be commonjs modules in the release.

**Comment by aberenyi** [comment]
Is it not just the simple case of replacing `system` with `commonjs` here https://github.com/angular/material2/blob/master/src/tsconfig.json#L7?

**Comment by jelbourn** [comment]
It is. The release script was supposed to do that automatically.

**Comment by jelbourn** [comment]
This should be fixed now with the `alpha.1` release.
