### ISSUE TITLE
npm error for alpha.9-3

### ISSUE THREAD

**Issue by lghinet** [angular/material2#1688]
hello
i get an error in npm
59 error node v6.2.1
60 error npm v3.9.3
61 error No compatible version found: @angular2-material/core@2.0.0-alpha.9-3
61 error Valid install targets:
61 error 2.0.0-alpha.8-experimental3, 2.0.0-alpha.8-experimental2, 2.0.0-alpha.8-experimental1, 2.0.0-alpha.8-2, 2.0.0-alpha.8-1, 2.0.0-alpha.7-9, 2.0.0-alpha.7-8, 2.0.0-alpha.7-7, 2.0.0-alpha.7-6, 2.0.0-alpha.7-5, 2.0.0-alpha.7-4, 2.0.0-alpha.7-3, 2.0.0-alpha.7-2, 2.0.0-alpha.7-12, 2.0.0-alpha.7-11, 2.0.0-alpha.7-10, 2.0.0-alpha.6-3, 2.0.0-alpha.6-2, 2.0.0-alpha.5-3, 2.0.0-alpha.5-2, 2.0.0-alpha.4-3, 2.0.0-alpha.8, 2.0.0-alpha.7, 2.0.0-alpha.6, 2.0.0-alpha.5, 2.0.0-alpha.4, 2.0.0-alpha.3, 2.0.0-alpha.2, 2.0.0-alpha.1, 2.0.0-alpha.0
62 error If you need help, you may report this error at:

do i need to upgrade node ?
or the latest version in npm is 8-2

**Comment by fxck** [comment]
it's not under `@angular2-material` anymore, it's under `@angular/material`, see the changelog.

**Comment by lghinet** [comment]
thanks
