### ISSUE TITLE
Input - missing important features

### ISSUE THREAD

**Issue by AmitMY** [angular/material2#1691]
#### Bug, feature request, or proposal:
(essential) Features request

#### What is the expected behavior?
Behave as it was in ng1

#### What is the current behavior?
Very features-lacking

#### What are the steps to reproduce?
Not relevant

#### What is the use-case or motivation for changing an existing behavior?
Nicer validation management

#### Which versions of Angular, Material, OS, browsers are affected?
NG2 latest, Material2 latest, 

#### Is there anything else we should know?
This demo of ng1 with material:
https://material.angularjs.org/latest/demo/input
shows "pattern", messages, hints, "min", "max" and maybe other stuff I don't notice.
Those are important I think.

**Comment by poloagustin** [comment]
Have you tried <md-input [max]="20" [min]="0"></md-input> ?

**Comment by AmitMY** [comment]
Well of course I have.
The attributes do exists, but they dont **behave** in the expected way.

**Comment by jelbourn** [comment]
"Add more features" is not a specific, actionable issue.
