### ISSUE TITLE
MdDialog Feature Request: Ability to change Width and off-set 

### ISSUE THREAD

**Issue by bkarv** [angular/material2#1698]
#### Feature Request
Ability to set width of Dialog and dialog off-set (x,y) through input parameters so that dialogs can be made responsive to the screen media. For example on mobile media the programmer could set dialog box to be 100% and off-set would be set to 0,0 so it takes up the entire screen. For desktop media the programmer would set to default standard position that is in the centre.

**Comment by jelbourn** [comment]
@crisbeto this has been an intended feature, we should chat about the API
