### ISSUE TITLE
[Feature] List Item Click

### ISSUE THREAD

**Issue by AmitMY** [angular/material2#1699]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Same as when having "ng-click" in the old version (having a ripple effect)
https://material.angularjs.org/latest/demo/list

#### What is the current behavior?
No ripple click feel

#### What are the steps to reproduce?
```
<md-list-item class="md-1-line" ngClick="menuClick(item)">
         <div class="md-list-text">{{item.title}}</div>
</md-list-item>
```

#### What is the use-case or motivation for changing an existing behavior?
Better material feel

#### Which versions of Angular, Material, OS, browsers are affected?
NG2, Material2

#### Is there anything else we should know?
UX wise it just doesn't feel right to not have a highlight and a ripple effect

**Comment by jelbourn** [comment]
We plan to implement this as `<md-action-list>`

This is currently tracked via #107
