### ISSUE TITLE
Detail git-lfs requirement in DEV_ENVIRONMENT.md

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#170]
Explain what it is, why we need it, and how to set it up.

**Comment by robertmesserle** [comment]
I have a Gist here that explains it:

https://gist.github.com/robertmesserle/d9e73ebf392482374b26

Let me go ahead and add that to DEV_ENVIRONMENT.md

**Comment by jelbourn** [comment]
Closing as we move away from lfs
