### ISSUE TITLE
Form blocking loading overlay

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#1707]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Modal or div loading overlay similar to the style that firebase dashboard uses:

![image](https://cloud.githubusercontent.com/assets/6654388/19962175/c2ee3de4-a1b6-11e6-95e2-85eb8d07c905.png)

#### What is the use-case or motivation for changing an existing behavior?
Quite you need to lock forms after a submit, so that users cannot change values or click links while a long running process is running.

**Comment by jelbourn** [comment]
I don't think we need a component for this- you should be able to accomplish it with the md-spinner and some CSS.
