### ISSUE TITLE
Additional Input field style

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#1708]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
In addition to the default md-input style, it would be great to have some kind mix between traditional input boxes and the style that angular material uses. You can see in my screenshot from firebase what i mean. The inputs are classical boxes with only a colored border at the bottom. 

![image](https://cloud.githubusercontent.com/assets/6654388/19962294/523303fe-a1b7-11e6-9c7f-5aac56dee235.png)

#### What is the use-case or motivation for changing an existing behavior?
In some cases, especially when dealing with huge forms or extremly long lables, this enables a much cleaner ui.

**Comment by mbeckenbach** [comment]
BTW: I love the way they provide some additional info regarding this field on the right side.

**Comment by joejordanbrown** [comment]
I believe this feature is already available.

If you don't want the floating placeholder set `floatingPlaceholder` to `false` like the following:

```
<label>Projecktname</label>
<md-input placeholder="Mein Projekt" floatingPlaceholder="false"></md-input>
```

**Comment by jelbourn** [comment]
@mbeckenbach is turning off the floating placeholder just what you wanted?

**Comment by jelbourn** [comment]
Closing this since I think it can be accomplished with `floatingPlaceholder` and some custom css on the input.
