### ISSUE TITLE
For <md-grid-list cols="3" rowHeight="fit"> (rowHeight is not working)

### ISSUE THREAD

**Issue by amanullahnxb** [angular/material2#1709]
<md-grid-list cols="3" rowHeight="200px"> is working.. but when i use rowHeight="fit". It does not work. (whole grid crashes)

**Comment by kara** [comment]
@amanullahnxb Are you setting a height for the grid list? It needs a fixed height if you are using fit mode.  If you are, please send a minimal repro case using our plunker template (in our issue template).

**Comment by kara** [comment]
Since we haven't heard back, I'm going to close this. Feel free to re-open with a plunker demonstrating the issue.

**Comment by badbye** [comment]
https://plnkr.co/edit/9Ji0aydpjyxxAFANdVhM?p=preview
May this example be a bad case.
