### ISSUE TITLE
how to define z-depth

### ISSUE THREAD

**Issue by elaijuh** [angular/material2#1710]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
class to define z-depth

#### What is the current behavior?
seems no such class

#### Is there anything else we should know?
if there is a way to define z-depth (shadow) pls advise and pardon me.

**Comment by jelbourn** [comment]
`.md-elevation-z0` through `.md-elevation-z24`

**Comment by vannel** [comment]
It's ```.mat-elevation-z0``` ~ ```.mat-elevation-z24``` with ver. 5.2.5
