### ISSUE TITLE
Introduce [ltr, rtl] layout direction service

### ISSUE THREAD

**Issue by kara** [angular/material2#1719]
Similar to what the Dir directive does, but will also capture "dir" attributes outside the Angular app. 

cc: @jelbourn

**Comment by jelbourn** [comment]
@EladBezalel would you be interested in working on this? I have some thoughts in mind for it

**Comment by EladBezalel** [comment]
@jelbourn sure! i'm always up to RTL stuff :D

**Comment by EladBezalel** [comment]
Simpler solution on #3600
