### ISSUE TITLE
[slider @alpha.9-3] Static value raises "expression was changed after checked" exception

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#1725]
#### Bug, feature request, or proposal:
Either bug, or ignorance on my part

#### What is the expected behavior?
When `md-slider` is bound to `ngModel` value that never changes, "*expression was changed after it was checked*" exception should not be raised

#### What is the current behavior?
The exception is thrown

#### What are the steps to reproduce?
[Run this plunk](http://plnkr.co/edit/IjDpZRD84mmGIdaRt9JA?p=preview) and look at the console.  

 - If you change `[(ngModel)]="slider.value"` to `value="10"`, the error disappears.
 - if you run `enableProdMode()` in `main.ts` the error disappears.

I understand that in development mode, change detection is run twice but I still don't get why the code linked would raise that exception. The expression `slider.value` [is idempotent ](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#idempotence)in my example isn't it?

#### What is the use-case or motivation for changing an existing behavior?
I'm not sure it's a bug, so this doesn't apply

#### Which versions of Angular, Material, OS, browsers are affected?
`Angular 2.0.1`, `Material 2 alpha 9-3`

#### Is there anything else we should know?
If  this isn't a bug, please tell me what's wrong with my code

**Comment by mmalerba** [comment]
fixed in master
