### ISSUE TITLE
Material 2 Grid

### ISSUE THREAD

**Issue by ImElango** [angular/material2#1727]
<md-grid-list cols="3" rowHeight="**AutomacitcallyAdjustable**">
Do we have any option like the corresponding md-grid-list cell automatically adjustable based on the data in that cell?

**Comment by dahaupt** [comment]
Please use the [official issue template (https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md) to open an issue (next time).

**Comment by jelbourn** [comment]
@ImElango please follow the issue template.
