### ISSUE TITLE
Bug - tabs doesn't show

### ISSUE THREAD

**Issue by AmitMY** [angular/material2#1740]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Showing the tab content & label

#### What is the current behavior?
Tab content & label doesn't show

#### What are the steps to reproduce?
Copy the example from the tabs README

#### Plunker
http://plnkr.co/edit/wuz37HLEdWZWuoLa2ucj?p=preview
(No labels, no content)

#### Which versions of Angular, Material, OS, browsers are affected?
NG2 latest, Material2 latest

**Comment by clydin** [comment]
The tabs readme represents master not the latest npm release

**Comment by DevVersion** [comment]
Yeah, the Plunker template currently uses the latest release and does not include the changes in `master`.

> I just updated the Plunker template to use one of the most recent commits.

By using `master` the tabs properly show up ([See here](http://plnkr.co/edit/bJhYGFqQ0z1rzBhTuVm4?p=preview))
