### ISSUE TITLE
Can't use md-textarea component

### ISSUE THREAD

**Issue by b-ponomarenko** [angular/material2#1743]
#### Bug, feature request, or proposal:
Can't use `md-textarea` component

#### What is the expected behavior?
I expect to see `md-textarea` element

#### What is the current behavior?
In source code `md-textarea` component is exist, but in build isn't exist (`"@angular/material": "^2.0.0-alpha.9-3"`)

#### What are the steps to reproduce?
1. Create simple project (`ng new test`)
2. Install material (`npm i @angular/material -S`)
3. Add material to project
4. Try to use `md-textarea` compoent

P.S. If I open source code of `md-input` component I not see template for `md-textarea` component, but in github repo i see it :(

<img src="http://dl2.joxi.net/drive/2016/11/05/0007/1971/464819/19/7a9ae2ed15.jpg">

my package.json
<pre>
{
  "name": "frontend",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/material": "^2.0.0-alpha.9-3",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.16",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}

</pre>

**Comment by quanterion** [comment]
md-textarea is in master but not yet released

**Comment by b-ponomarenko** [comment]
@quanterion what is easyest way to use it?

**Comment by clydin** [comment]
Easiest would be to wait for the next release. Otherwise you'd need to clone the repo and build a local copy

**Comment by erasethis** [comment]
What's up with releases anyway? Before Angular 2 went out of beta there were npm releases every couple of days, now we're stuck with alpha-9.3 for over a month and that package is seriously broken with Angular 2.1.2 like transparent side navs, native controls appearing side by side with their Material 2 counterpart and the list goes on. Am I supposed to clone the repo now to be able to use Material 2 along with the latest Angular 2 release? Looking forward to reporting to product management already.

**Comment by jmcgoldrick** [comment]
`npm install --save @anular/material@experimental` this tag has it

**Comment by clydin** [comment]
This is alpha level software; expect things to not work, be unfinished, etc.

**Comment by erasethis** [comment]
I'm aware of that, what is annoying though is that I have to come here in order to learn how to get an npm package of the current version. I would have expected to get that same piece of information on npm.org, but the page for material2 hasn't been updated in weeks.

Anyway, things finally started working again so I'm out of here ;)

**Comment by dahaupt** [comment]
@erasethis I can understand your point, but actually I think the devs are doing a great job and I expect a new alpha version in the next couple of days with bug fixes and some new features. Releasing a new version for every commit or every day is not useful. But a new version at least every month would be awesome.

**Comment by dahaupt** [comment]
@jmcgoldrick 
> npm install --save @angular/material@experimental this tag has it

Where did you get that from? I can't find that command anywhere :(

**Comment by Ploppy3** [comment]
I'm kind of new to node.js but I'll try to help with what I know.
If you wanna get information about the material package type the following command:
`npm view @angular/material`
You will see that there are 2 dist-tags, 'latest' which is latest stable release and an other one 'experimental'.
When you install a package you can specify the distribution tag by appending the package with @dist-tag
So the following command will install the 'experimental' version of the '@angular/material' package:
`npm install --save @angular/material@experimental`

**Comment by dahaupt** [comment]
@Ploppy3 Thanks a lot, **`npm view`** was new to me :)

**Comment by jelbourn** [comment]
The textarea hasn't been released yet. You can see the status of any component in the [README](https://github.com/angular/material2/blob/master/README.md) and see changes to the library in the [CHANGELOG](https://github.com/angular/material2/blob/master/CHANGELOG.md)
