### ISSUE TITLE
Ripple effect stuck when switching tabs

### ISSUE THREAD

**Issue by oliversalzburg** [angular/material2#1755]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When a ripple effect is used, like on a checkbox, the ripple disappears after the animation is completed and it won't re-appear unless triggered again.

#### What is the current behavior?
The ripple can get "stuck" on the final animation frame.
![image](https://cloud.githubusercontent.com/assets/1658949/20066710/d166b5b8-a512-11e6-9240-f07c8564f86a.png)

This even effects "no ink" elements:
![image](https://cloud.githubusercontent.com/assets/1658949/20066762/0ac3d638-a513-11e6-9d77-8bc7d2e47e64.png)

#### What are the steps to reproduce?
1. Go to https://material.angularjs.org/latest/demo/checkbox
2. Click the first checkbox in the demo and wait for the ripple effect to complete
3. Switch to another tab
4. Switch back to the previous tab

#### Which versions of Angular, Material, OS, browsers are affected?
Latest or whatever is used on the documentation, Windows 10, Chrome Stable

**Comment by dahaupt** [comment]
@oliversalzburg I think you are in the wrong repository, because [this](https://material.angular.io/) is the website of Material Design for Angular 2. Your bug seems to be in Material Design for Angular 1.x.

**Comment by DevVersion** [comment]
Yeah this is a bug for Material (and also has been solved already https://github.com/angular/material/commit/002207cdd32dcdb1228f0f1a3ce70328fac69c95).

Please report issues to the [angular/material](http://github.com/angular/material) repository instead.

**Comment by oliversalzburg** [comment]
Whoops. Sorry, don't know how I ended up in the wrong tracker :)
