### ISSUE TITLE
DIalogInjector and lazy-loaded modules Injectors

### ISSUE THREAD

**Issue by eagle-dan1349** [angular/material2#1765]
#### Bug, feature request, or proposal:
[x] Bug

#### What is the expected behavior?
DialogInjector should be aware of Injector from lazy-loaded module

#### What is the current behavior?
DialogInjector is unaware of lazy-loaded module and attempts to inject services provided by lazy-loaded module result in 'No provider for ...' errors

#### What are the steps to reproduce?
1. Create route to lazy loaded module.
2. Provide service from lazy-loaded module.
3. Declare dialog component in lazy-loaded module.
4. Inject service to dialog component.
5. Try to display dialog.
6. Catch error.

Plunker template: http://embed.plnkr.co/eBQNsfV7jTys4THqfT77/

#### What is the use-case or motivation for changing an existing behavior?
I try to split my app into lazy-loaded modules.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: ~2.1.0
Material: ^2.0.0-alpha.9-3

**Comment by jelbourn** [comment]
Thank you for your excellent bug report.

**Comment by karolmie1** [comment]
@jelbourn Any tips on how to circumvent this? Just recently stumbled uppon this problem. Shame its unlikely i can help fixing it.

**Comment by eagle-dan1349** [comment]
I had to give up lazy loading until the issue is resolved

**Comment by jelbourn** [comment]
@eagle-dan1349 I think the next release will fix this- we're getting rid of `forRoot` (#2556), so the lazily-loaded module can import `MdDialogModule` and it will get a new instance with the appropriate injector. You can install the latest SHA from https://github.com/angular/material2-builds to test it out.

**Comment by coder925** [comment]
Excellent! It works with the latest bits given that you are also importing _MaterialModule_ in the lazy loaded sub-module. Thanks!

**Comment by istiti** [comment]
@eagle-dan1349 can you close this issue please,  the [new way ](https://github.com/jelbourn/material2/blob/147a07794f814792137bf859602ce3b589eca5c3/src/lib/icon/icon.ts#L255)is always import material module without `forRoot()` method, and internally material check for each service if token exist use it otherwise create new instance.

cc @jelbourn

**Comment by DrewImm** [comment]
@sebrojas14 
> What about this with angular 8?

In Angular 8, I solved the issue by adding `MatDialogModule` into the submodule's `import` array:

```typescript
...
import { MatDialogModule } from '@angular/material/dialog';
...

@NgModule({
	declarations: [ TheDialogComponent ],
	imports: [
		...,
		MatDialogModule, // < Add this line!
		...
	],
	entryComponents: [ TheDialogComponent ]
})
export class TheSubModule {}
```

Note:
Unless you have dialog components in the app module, your app module does not need to import `MatDialogModule`

**Comment by joesleiman** [comment]
@DrewImm 
i didn't work for me. any new suggestion?

**Comment by Splaktar** [comment]
I can't confirm that this is the case 100%, but there is some discussion about how Ivy may improve upon this behavior in https://github.com/angular/angular/issues/14324#issuecomment-534716807.
