### ISSUE TITLE
MdDialogRef does not capture a type for the close result

### ISSUE THREAD

**Issue by eagle-dan1349** [angular/material2#1766]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Stronger typed MdDialogRef<T, U> class with something like close(dialogResult?: U) method. Or may be close method should accept some sort of template class like MdDialogResult<U> or something.

#### What is the current behavior?
MdDialogRef's close() method accepts argument of type any.

#### What are the steps to reproduce?
N/a

#### What is the use-case or motivation for changing an existing behavior?
Follow TypeScript way

#### Which versions of Angular, Material, OS, browsers are affected?
Any

**Comment by jelbourn** [comment]
This was added in #8766
