### ISSUE TITLE
Question: Does material2 md-input support attribute directive 

### ISSUE THREAD

**Issue by andlcool** [angular/material2#1768]
#### Bug, feature request, or proposal:
Does angular material 2 support attribute directive?

https://angular.io/docs/ts/latest/guide/attribute-directives.html

What I am trying to do is to build a focus and select directive. The attribute directive works for normal input element but throws error when using md-input

<md-input focusSelectDirective></md-input>

Thanks.

**Comment by jelbourn** [comment]
There's nothing special about md-input that would prevent this from working.
