### ISSUE TITLE
Release Schedule?

### ISSUE THREAD

**Issue by tomwanzek** [angular/material2#1770]
#### Bug, feature request, or proposal:

Most importantly, thanks for all the hard work on Material 2!!! One quick question though: While I understand that this project is still in alpha. Could you kindly clarify, the "order of magnitude" release schedule?

It seems, in the past, formal alpha releases were appr. 1 month apart. Is it a reasonable expectation that a new alpha release should be expected in the very near future?

I have seen issue #577 regarding nightly builds. Is the only current alternative to waiting for the next formal release, to install directly from master?

Thanks for your guidance

**Comment by jelbourn** [comment]
We're working on a release now; meant to do it last week, but we've hit some roadblocks with last-minute bugs.
