### ISSUE TITLE
Can't install master or a specific commit

### ISSUE THREAD

**Issue by epelc** [angular/material2#1774]
#### Bug, feature request, or proposal:
I can not install master or a specific commit using npm. 

```
$ node -v
v6.9.1
$ npm -v
3.10.8
```

#### What is the expected behavior?
`npm install --save @angular/material#master` should install the latest commit on master.

#### What is the current behavior?
It does not work. I receive the following error.
```
$ npm install --save @angular/material#master
npm ERR! addLocal Could not install PROJECT_DIR/@angular/material#master
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/ed/.nvm/versions/node/v6.9.1/bin/node" "/Users/ed/.nvm/versions/node/v6.9.1/bin/npm" "install" "--save" "@angular/material#master"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path PROJECT_DIR/@angular/material#master
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'PROJECT_DIR/@angular/material#master'
npm ERR! enoent ENOENT: no such file or directory, open 'PROJECT_DIR/@angular/material#master'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     PROJECT_DIR/npm-debug.log
```

I receive a similar error with `npm install --save @angular/material#some-sha`

#### What are the steps to reproduce?
Run `npm install --save @angular/material#master` 

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
There are several major issues I need fixes for so I want to pin the latest version. Since tagged releases are at least a month apart this is a real pain. 

Specifically I'm trying to use the new version of tabs.

#### Is there anything else we should know?

You can install the project using the git url but despite everything I try npm installs it under `node_modules/material2`.

Installs latest master under `material2` instead of `@angular/material`
`npm install --save https://github.com/angular/material2`
Updating your package.json dependencies key name to `@angular/material` doesn't fix it.

**Comment by epelc** [comment]
Changing the `name` to `@angular/material` in this repo's `package.json` fixes the install path. However you end up with the source installed. [Example](https://github.com/epelc/material2/blob/master/package.json#L2)

I'm guessing the project needs some sort of CD setup so a build can be published for every commit.

**Comment by jelbourn** [comment]
We don't currently have per-SHA releases. See #577

**Comment by epelc** [comment]
@jelbourn Thanks for the info.

I worked around this by cloning the current master, building it, and then pushing the built assets to a separate repo.

**Comment by QuentinFchx** [comment]
@jelbourn Do you have an estimation on the next release?
I'm totally ok with another alpha but a lot of interesting stuff was added recently and I'd *love* to be able to use it (without the clone/build that @epelc mentionned)
Do you think we could cut a release (alpha/beta whatever) twice a month?

**Comment by epelc** [comment]
I also forgot to mention that you need to rename the `name` field in package.json to `@angular/material` or the clone/build method doesn't work(you end up with the repo installed under `material2`).

@jelbourn What do you think about changing the `name` field in this repo? I don't think it would break anything since everyone is already using `@angular/material` as the canonical name.

The main angular 2 repo also has this problem. Maybe I'm missing the reasoning for using different names.
