### ISSUE TITLE
Add option to disable ripples globally

### ISSUE THREAD

**Issue by mwarton** [angular/material2#1776]
#### Bug, feature request, or proposal:
An option to globally disable ripple animations would help to reduce flakiness in screendiff testing.

#### What is the expected behavior?
Globally diable ripple animations for screen diff testing.

#### What is the current behavior?
Ripple animations can only be disabled on an element by element basis.

#### What is the use-case or motivation for changing an existing behavior?
Making screenshot diff tests more reliable.

#### Which versions of Angular, Material, OS, browsers are affected?
angular/material2

**Comment by jelbourn** [comment]
This should probably be similar to disabling animations globally.

**Comment by spock123** [comment]
It would be a nice option to have.

Especially on mobile devices, the ripples animations kill anything but the top dog phones.

**Comment by thomaspink** [comment]
Would like to take on this.
@jelbourn could not find the code for disabling animations globally. Is this already implemented?

**Comment by M-a-c** [comment]
@jelbourn Seems to be added
feat(ripple): support for global ripple options (#3463)

https://github.com/angular/material2/blob/fb75a136e72489d75c44ca8e68d99352dc71afef/src/lib/core/ripple/ripple.ts#L20

**Comment by jelbourn** [comment]
So it is.
