### ISSUE TITLE
[md-subheader] Incorrect font family

### ISSUE THREAD

**Issue by chouclee** [angular/material2#1777]
#### Bug, feature request, or proposal:
Bug md-subheader cannot inherit proper font family

#### What is the expected behavior?
by default, font family of md-subheader should be **Roboto**

#### What is the current behavior?
The default font family is **Times** (inherited from body, might be ``Roboto``, decided by how you give global style to ``body``) 

#### What are the steps to reproduce?
http://plnkr.co/edit/I1kueZi21gdktAGLIupS?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Fonts should be same by across all material2 components by default

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.1.0
Material: master branch
OS: Mac OS 10.11.6
Browsers: Chrome, Firefox, Safari

#### Is there anything else we should know?
Nope

**Comment by chouclee** [comment]
@kara any update on this issue? I can fix this one if you wish. Only an extra line of css

**Comment by kara** [comment]
@chouclee Go for it!
