### ISSUE TITLE
md-icon-button background should be transparent

### ISSUE THREAD

**Issue by thibaultsavary** [angular/material2#1787]
#### Bug, feature request, or proposal:
Inconsistency

#### What is the expected behavior?
```
<button md-icon-button>
  <md-icon>some_ligature</md-icon>
</button>
```
background should be transparent

#### What is the current behavior?
```
<button md-icon-button>
  <md-icon>some_ligature</md-icon>
</button>
```
is not transparent

but
```
<a md-icon-button>
  <md-icon>some_ligature</md-icon>
</a>
```
is transparent

#### What is the use-case or motivation for changing an existing behavior?
Inconsistency with the documentation and the behavior of  `a` & `button`
https://github.com/angular/material2/blob/master/src/lib/button/README.md

#### Which versions of Angular, Material, OS, browsers are affected?
Alpha9-3

**Comment by tinayuangao** [comment]
Both `button` and `a` have transparent background in current master.

**Comment by sothychan** [comment]
This appears to longer be true.  <button mat-icon-button> is not transparent to me.  I have @angular/material-5.2.3 installed.
