### ISSUE TITLE
[md-radio-group] The value two-way binding not working?

### ISSUE THREAD

**Issue by krigton** [angular/material2#1790]
#### Bug, feature request, or proposal:
Bug [x]

#### What is the expected behavior?
According to the readme.md of the radio, there is `value` property on the group with two way binding. 
If I set a variable with one of the possible value selections of the radios inside the group, then the radio which value attribute matches the variable's value will be selected. But if I select another radio the variable's value will not get updated. I guess the cause of this behaviour is that there is no `valueChange EventEmitter` created in the `MdRadioGroup` class

The variable's value should updated when new radio is selected

#### What is the current behavior?
The variable's value is not updating when new radio is selected

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: 
http://plnkr.co/edit/8aHnV0luO8Oie2kwQqek?p=preview

#### What is the use-case or motivation for changing an existing behavior?

There is the change event which has the value property so that might be enough, but then the readme.md file should be updated.

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0
2.0.0-alpha.9-3
Mac os X crhome

#### Is there anything else we should know?
not too much experience with Angular 2

**Comment by jelbourn** [comment]
The docs are just wrong here- it should be using `ngModel` there.
