### ISSUE TITLE
md-sidenav with a position:fixed (non scrollable)

### ISSUE THREAD

**Issue by Ennos-Rep** [angular/material2#1793]
#### Bug, feature request, or proposal:
I don't know if I am in the right place to ask for this (I'm new here, and sorry for my bad english, I'm french), but I want a "fixed" content in the md-sidenav, while the main content scrolls. I don't see this in the bound properties and I tried to do it with css properties, but it has no effect or it breaks everything.

#### What is the expected behavior?
The content of the choosen md-sidenav doesn't scroll when the web page scroll.

#### What is the current behavior?
The content of each side scroll in the same time.

#### What is the use-case or motivation for changing an existing behavior?
I'm developping a site with two sidenav, with default behavior (opened or closed, mode over or side, etc.) depending on window.innerWidth, etc. (that works fine), but I want that one of the two sidenav doesn't scroll at all, somethink like the behavior of the md-sidenav-left on : https://material.angularjs.org/latest/

#### Which versions of Angular, Material, OS, browsers are affected?
Angular ~2.1.2, Material ^2.0.0-alpha.9-3

#### Is there anything else we should know?
I come back coding since a long time (since java spring hibernate and javascript prototype with the bugs of IE 6,7,8...) and I'm enthusiastic working with nodejs, both on server side and client side. Thank you for your amazing job : Angular is exactly what I expected and the github community offers a lot.

**Comment by mmalerba** [comment]
Please see the "Sidenav with a FAB" example (under the "examples" tab) here: https://material.angular.io/components/component/sidenav This demonstrates how to have an independently scrolling main content and sidenav.

**Comment by crutland** [comment]
That page is currently broken in all browsers I've tested with (Chrome, Firefox, IE).

The content is shown, and clicking the FAB generates an error in the console.

**Comment by willshowell** [comment]
@crutland See https://github.com/angular/material2/issues/4963. It'll be fixed whenever the docs are updated via a new release

**Comment by knightcode** [comment]
Still a problem in Mobile Safari
