### ISSUE TITLE
color="primary" does not work

### ISSUE THREAD

**Issue by dolanmiu** [angular/material2#1798]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
`primary` `accent` `warn` colors don't work. Shows up as grey.

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/material": "^2.0.0-alpha.9-3",

I am using electron too

I have my code here:
```html
<button md-raised-button color="primary">PRIMARY</button>
<button md-raised-button color="accent">ACCENT</button>
<button md-raised-button color="warn">WARN</button>
```

but it shows up as:
![screen shot 2016-11-10 at 01 49 33](https://cloud.githubusercontent.com/assets/2917613/20161720/54dcc2c6-a6e8-11e6-993d-ffc9b555bdd5.png)

I am including `core.css`, `overlay.css` and `material.indigo-pink.min.css` in index.html:

```html

    <link href="https://unpkg.com/@angular2-material/core/overlay/overlay.css" rel="stylesheet">
    <link href="https://unpkg.com/@angular2-material/core/style/core.css" rel="stylesheet">
    <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.indigo-pink.min.css">
```

### Note
`material.indigo-pink.min.css` is definately loaded because some parts of my app turned pink, as shown in the screen shot.

**Comment by jelbourn** [comment]
@dolanmiu you've confused this project with [Material Design Lite](https://getmdl.io), which is something else completely. 

[Follow our theming guide for how to bring the colors into your app.](https://github.com/angular/material2/blob/master/docs/theming.md)

**Comment by dolanmiu** [comment]
Quoted straight from the spec:

> ## Using a pre-built theme

> Angular Material comes prepackaged with several pre-built theme css files. These theme files also include all of the styles for core (styles common to all components), so you only have to include a single css file for Angular Material in your app.

> You can include a theme file directly into your application from @angular/material/core/theming/prebuilt

> If you're using Angular CLI, this is as simple as including one line in your style.css file:

> `@import '~@angular/material/core/theming/prebuilt/deeppurple-amber.css';`

This is exactly what I have done (but using `<link>` instead). But it isn't working?

Please help

**Comment by jelbourn** [comment]
You are including the css file from Material Design Lite, not Angular Material. The correct file is in the `@angular/material` npm package.
