### ISSUE TITLE
md-button for anchor element is visually not same as button

### ISSUE THREAD

**Issue by metanav** [angular/material2#1801]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
```
 <a  md-button color="primary" [routerLink]="['/gotosomewhere']">Click me</a>
```
The button created using anchor element should be visually same as button element.
#### What is the current behavior?
It is not same. There is no mouse (one finger hand) icon and  text is dimmed.

#### What are the steps to reproduce?
Just upgraded from alpha9 to alpha10.

#### What is the use-case or motivation for changing an existing behavior?
None
#### Which versions of Angular, Material, OS, browsers are affected?
Material alpha10

#### Is there anything else we should know?
None

**Comment by kyleledbetter** [comment]
it's bc it's getting `disabled="false"` by default and to an `<a>` tag that's still treated as `disabled`, probably from this commit https://github.com/angular/material2/commit/6b9e11cfd7700718016c444c651b9aa7e5222904#diff-96337821f283af0f38c4fd8ed4c98065R46

**Comment by kyleledbetter** [comment]
`'[attr.disabled]': 'disabled',` <-- anchors
`'[disabled]': 'disabled',` <-- buttons

**Comment by Splaktar** [comment]
Yep, this is a regression that I'm seeing as well. There is [PR](https://github.com/angular/material2/pull/1789) already open to fix it, but it didn't make it into alpha.10 unfortunately.

**Comment by Splaktar** [comment]
I spent a good while trying to work around this issue and override styles, etc. But it was just too much trouble. I've had to roll back to `alpha.9-3`.
