### ISSUE TITLE
(slideend) is not working as expected with [(ngModel)]  [material version is alpha 10]

### ISSUE THREAD

**Issue by amanullahnxb** [angular/material2#1802]
i did two way binding md-slider with class attribute 'sliderVal'. as below code.

<md-slider (slideend)="onSlideEnd();" [min]="0" [max]="100"  [(ngModel)]="sliderVal"></md-slider>

//class members

sliderVal: number = 10;

onSlideEnd(){
                console.log("slider value", this.sliderVal);
    }

but the problem is when onSlideEnd() is called. its shows previous slider value in console.

**Comment by jelbourn** [comment]
The `slideend` event isn't really meant to be used on the slider element. If you're just looking to know when the value changes, the slider now has a `change` event. Is that what you need?

**Comment by amanullahnxb** [comment]
yes.. i have used (change) event too. but i am facing same problem

**Comment by amanullahnxb** [comment]
`<md-slider (change)="onSlideEnd($event);" [min]="0" [max]="100" [(ngModel)]="sliderVal"></md-slider>

//class members

sliderVal: number = 10;

onSlideEnd($event){
console.log("slider value", this.sliderVal);
}`

again.. the value for sliderVal shows previous value. (not the current value of slider)

**Comment by josephperrott** [comment]
Are you importing the FormsModule?

I was able to get this working with `(slideend)`

You can see a working plnkr [here](http://plnkr.co/edit/tcVgLUcAosWspGV0ilK9?p=preview)
