### ISSUE TITLE
md-slider won't update [(ngModel)] half of the times

### ISSUE THREAD

**Issue by alexlacasa86** [angular/material2#1805]
#### Bug, feature request, or proposal:
*BUG*

#### What is the expected behavior?
Every time the _md-slider_ is _changed_, the [(ngModel)] value gets updated.

#### What is the current behavior?
[(ngModel)] value gets updated only half of the times than _md-slider_ is _changed_. It works in alternate changes: 1st yes, 2nd nope, 3rd yeap, etc. Weird, eh?

After some investigation (not really deep...) I found out that it works nicely as long as I don't include the (change) or (ngModelChange) output...

#### What are the steps to reproduce?
`<md-slider
  min="0"
  max="1"
  step="0.01"
  (change)="rangeChanged()"
  [(ngModel)]="weight">
</md-slider>`

#### What is the use-case or motivation for changing an existing behavior?
Well... Making things work as it should.

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material: 2.0.0-alpha.10
macOS + Chrome

#### Is there anything else we should know?
Nope...

**Comment by jelbourn** [comment]
@mmalerba you can consult with @kara if you run into any problems with `NgModel` or anything else in the forms api.

**Comment by mmalerba** [comment]
@alexlacasa86 Can you give a more detailed description of how to reproduce? I'm not seeing this behavior.

**Comment by alexlacasa86** [comment]
I was not able to create a Plunkr with the _failing_ code. I finally removed the 2-way binding and emitted the value manually, so now it seems to be working.

I'm sorry I cannot be any more helpful on this issue.

**Comment by mmalerba** [comment]
Ok, closing for now, feel free to re-open if you find a way to consistently reproduce it
