### ISSUE TITLE
Allow configuration of tooltip hide delay

### ISSUE THREAD

**Issue by da45** [angular/material2#1806]
BUG

**Comment by rolandjitsu** [comment]
@da45 this is not a bug, it seems to be on purpose. Perhaps there is a plan to customize this timing globally.

**Comment by nkwood** [comment]
The delay (1.5 seconds) actually conforms to the [material design spec](https://material.google.com/components/tooltips.html#tooltips-interaction): 

> On lift, display the tooltip for 1.5 seconds.

However I agree it seems too long and it would be nice if it was exposed as a configuration option.

**Comment by jelbourn** [comment]
Working as intended now per [the spec](https://material.google.com/components/tooltips.html#tooltips-interaction). It will also go away if you interact with anything on the page. 

However, we should make this configurable.

**Comment by rolandjitsu** [comment]
I opened a proper issue [here](https://github.com/angular/material2/issues/1808).

**Comment by jelbourn** [comment]
Closing in favor of #1808
