### ISSUE TITLE
[Tooltip] allow configuration of the hide delay

### ISSUE THREAD

**Issue by rolandjitsu** [angular/material2#1808]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
`TOOLTIP_HIDE_DELAY` should be configurable even though according to the [specs](https://material.google.com/components/tooltips.html#tooltips-interaction) is set to be `1.5` seconds.
Ideally, a user should configure it via an opaque token:
```
import {TOOLTIP_HIDE_DELAY} from '@angular/material';

@NgModule({
    providers: [
        {provide: TOOLTIP_HIDE_DELAY, useValue: 450}
    ]
})
export class MyModule {}
```
#### What is the current behavior?
Currently you cannot configure the timing.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Some users may wish to hide the tooltip earlier than the spec dictates.

#### Which versions of Angular, Material, OS, browsers are affected?
`2.0.0-alpha.10`

**Comment by t0f3rchr15** [comment]
Is a configurable delay on open() on the roadmap as well?

**Comment by aciccarello** [comment]
@t0f3rchr15 See #3286
