### ISSUE TITLE
MdTooltip: allow only one tooltip to be viewed at once

### ISSUE THREAD

**Issue by rolandjitsu** [angular/material2#1810]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
According to [specs](https://material.google.com/components/tooltips.html#tooltips-interaction) `If the user takes another action before that time ends, the tooltip will disappear.`. This should include showing a second tooltip as well, only one tooltip should be visible at once.

#### What is the current behavior?
Currently, I can view any amount of tooltips at once, which in my opinion can be confusing for users.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by andrewseguin** [comment]
Fixed in #1819
