### ISSUE TITLE
Menu ripple doesn't work if scrolled beneath the fold

### ISSUE THREAD

**Issue by kara** [angular/material2#1811]
Looking into it!

Edit: It turns out that the ripple is acting funky if scrolled beneath the fold. For some reason, it takes longer to animate and so it isn't removed before the menu closes.

Related to https://github.com/angular/material2/issues/1817 & https://github.com/angular/material2/issues/1818

**Comment by krigton** [comment]
@kara hi. I understand (i guess) what you mean now. Are you working on this? If not i can pick it up. thanks

**Comment by kara** [comment]
Yep, working on it. Generally when I assign something to myself, I'm working on it.

**Comment by krigton** [comment]
Ah ok then I should leave it. Sorry.

**Comment by krigton** [comment]
Is that a general rule here that if someone is assigned to an issue they are working on it? Or they are assigned but it might happen that it's not in progress? Just trying to pick up an issue and not overlapping with others. thanks

**Comment by kara** [comment]
@krigton Fair point. If you see that an issue hasn't gotten any activity in a while (like a few weeks), the best thing is just to ask like you did here. Also check out the "projects" section. I keep track of my current workload in there, so typically if it's on the board, I plan on working on it soon.

**Comment by krigton** [comment]
@kara thanks for the explanation

**Comment by krigton** [comment]
thanks!

**Comment by kara** [comment]
Should have been fixed by #1915
