### ISSUE TITLE
md-hint doesn't support css hidden attribute anymore

### ISSUE THREAD

**Issue by clarenceh** [angular/material2#1822]
#### Bug:
Observed that in input.scss, for CSS class md-hint, the following css attribute had been added:
- display: block

#### What is the expected behavior?
Current I am using md-hint to show validation error message. I use the hidden attribute to control whether the hint should display base on the control status. Sample code shown below:
```
<md-input class="mek-input mek-full-width" required placeholder="Location" formControlName="location" i18n-placeholder="Expense form|Location placeholder">
    <md-hint class="mek-error-msg" [hidden]="location.untouched || location.valid" i18n="Expense form|Location error message">
                  Location is required and between 2 to 60 characters
    </md-hint>
</md-input>
```
#### What is the current behavior?
Now the hidden behaviour no longer works as the display: block was added

#### What are the steps to reproduce?
The above description is sufficient.

#### What is the use-case or motivation for changing an existing behavior?
* Is it the recommended way to use md-hint for validation error reporting?
* Should I use *ngIf instead of [hidden] to control the display of md-hint?

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.1.2
Material2: 2.0.0-alpha.10

**Comment by jelbourn** [comment]
We consider using the `hidden` property an anti-pattern because of the way that browsers implement it. The "hidden" state is only applying a style like
```css
[hidden] {
  display: none;
}
```

This is less specific than any user-space rules and can be very easily overridden. We recommend using a css class to hide stuff.

**Comment by kuncevic** [comment]
I just had same behaviour with using `[hidden]` with `md-hint`. Adding the style `[hidden] { display: none !important; }` works  but I just changed `[hidden]=(..) to `*ngIf=!(..)` so this way it is works without adding `[hidden] { display: none !important; }`.
