### ISSUE TITLE
Add components to `entryComponents` array to allow dynamic creation

### ISSUE THREAD

**Issue by bradringel** [angular/material2#1823]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I would like to be able to dynamically add angular material components to my application using the `Compiler` service and the `ViewContainerRef` service. Adding the components in each module to the `entryComponents` array of the `NgModule` declaration will allow the components to be created programmatically

#### What is the current behavior?
After compiling any of the angular material modules, there aren't component factory instances for many of the components in that module

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Creating some components on the fly and adding them to the application can be useful for showing components based on internal logic. As a specific example, adding a directive that can be applied to md-input that will add an md-hint component if a warning needs to be shown.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0.0
Angular Material 2.0.0-alpha.9-3

**Comment by jelbourn** [comment]
Doing this would make the components impossible to tree-shake. You can add the components to the `entryModules` property of your own NgModule.

**Comment by NidhiLive** [comment]
I'm trying to create component dynamically which not existing on any modules. And am facing an error  which says mention the component in entrycomponents [ ].  How to add dynamically generated component into entrycomponents [ ]? Can anyone help me on this?

    protected _createComponentFactory(component:any, data:any){
    const compFactory = this.ComponentFactoryResolver.resolveComponentFactory(component);

    const compRef = compFactory.create(this.Injector);
    
    const compInstance: any = compRef.instance;
    
    compInstance.data = data;
    
    this.ApplicationRef.attachView(compRef.hostView);
    
    const compElement = (compRef.hostView as EmbeddedViewRef<any>).rootNodes[0] as HTMLElement;
    
    console.log(compElement);}

`

     protected _createNewComponent (tmpl:string, selector:string) {
      @Component({
          selector: selector,
          template: tmpl,
      })
      class CustomDynamicComponent  implements OnInit {
          @Input()  public data: any;
          ngOnInit(){}
      };
      
      return CustomDynamicComponent;
    }

`

`
`   

    let Component_template = '<h1>Sample Heading</h1>';
    let Component_selector = '.heading';
    this._createComponentFactory(
                                  this._createNewComponent(
                                                              Component_template, 
                                                              Component_selector
                                                          ),
                                '');
`

`

**Comment by mperk** [comment]
You can use ANALYZE_FOR_ENTRY_COMPONENTS 
Please look the page:
https://angular.io/api/core/ANALYZE_FOR_ENTRY_COMPONENTS

**Comment by NidhiLive** [comment]
Thanks @Mehmet Perk.
