### ISSUE TITLE
select: Label alignment is off when a value has been selected on IE

### ISSUE THREAD

**Issue by crisbeto** [angular/material2#1831]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The label should be aligned.

#### What is the current behavior?
![jkzqg7b](https://cloud.githubusercontent.com/assets/4450522/20229036/97cbe1ee-a854-11e6-8ea2-cc3bd48ed606.png)

#### What are the steps to reproduce?
On IE11, go to the select demo and select a value.

**Comment by kara** [comment]
Yep - it's been on my md-select board for a bit: https://github.com/angular/material2/projects/2
