### ISSUE TITLE
MdSlider severe performance impact

### ISSUE THREAD

**Issue by borislemke** [angular/material2#1837]
#### Bug, feature request, or proposal:
Bug / performance issue

#### What is the expected behavior?
Better performance for MdSlider

#### What is the current behavior?
MdSlider takes ~96ms to initiate, mainly from the getBoundingClientRect function inside ngAfterContentInit.

I'm not sure if this is a suitable post for the issues section but this needs to be looked into as 96ms can be unacceptable for some browsers, especially mobile.

Chrome CPU profiler
```
94.3 ms 9.00 %	94.3 ms 9.00 %	getBoundingClientRect
94.3 ms 9.00 %	94.3 ms 9.00 %	SliderRenderer.getSliderDimensions
94.3 ms 9.00 %	94.3 ms 9.00 %	MdSlider.ngAfterContentInit
```

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2 ~2.1.1
Material alpha.8-2
Chrome, Safari on MacOS Sierra, Crodova wrapper in Android and iOS

**Comment by crisbeto** [comment]
This sounds strange since:

1. The slider class doesn't implement `ngAfterContentInit`.
2. `getSliderDimensions` is only called when the cursour goes into a slider element. It woun't get triggered on init.
3. At least in our demo app, the `getBoundingClientRect` call takes 0.3 milliseconds, even in IE.

**Comment by borislemke** [comment]
@crisbeto 
I can see that alpha.8-2 still implements ngAfterContentInit, may have been removed in alpha.10
```
    MdSlider.prototype.ngAfterContentInit = function () {
        this._sliderDimensions = this._renderer.getSliderDimensions();
        // This needs to be called after content init because the value can be set to the min if the
        // value itself isn't set. If this happens, the control value accessor needs to be updated.
        this._controlValueAccessorChangeFn(this.value);
        this.snapThumbToValue();
        this._updateTickSeparation();
    };
```

Is there a way to npm install alpha.10? With a @beta or @experimental flag perhaps? The current npm package is at alpha.8-2.

**Comment by crisbeto** [comment]
Not sure why alpha.10 isn't on NPM, but you should be able to get a more recent version with `@experimental`.

**Comment by DevVersion** [comment]
@borislemke Material 2 Alpha.10 seems to be on NPM

```bash
npm install @angular/material@2.0.0-alpha.10

# Use this command to see all available versions
npm view @angular/material versions
```

**Comment by borislemke** [comment]
@DevVersion @crisbeto right, I was not aware of the move from @angular2-material to @angular/material@2xx.
Will check if the issue persists with alpha.10

**Comment by borislemke** [comment]
@crisbeto @DevVersion 
hey guys, this problem seems to be fixed in alpha-10. MdSlider no longers implements AfterContentInit and processes within MdSlider takes less than 1ms on average. Thanks for the help!
