### ISSUE TITLE
Alpha 10: Background for md-fab on <a> different then on <button>

### ISSUE THREAD

**Issue by elvirdolic** [angular/material2#1843]
#### Bug, feature request, or proposal:
Bug?
#### What is the expected behavior?
if you use the md-fab directive on a button the primary background color is set if you use it on a <a> link it'ts not

#### What is the current behavior?
Same behavior should be for <a> as it is for <button>

#### What are the steps to reproduce?
	```
	<a md-fab href="http://orderlink" target="_blank">
			<md-icon class="md-24">add_shopping_cart</md-icon>
		</a>
```

vs

	```
<button md-fab (click)="openUploadDocumentDialog()" [disabled]="dialogRef">
            <md-icon class="md-24">add</md-icon>
        </button>
```

**Comment by crisbeto** [comment]
Could you post an example that shows the issue? I tried it locally with our demo app and they looked exactly the same.

**Comment by simonh1000** [comment]
I get the same with regular buttons:

![image](https://cloud.githubusercontent.com/assets/5256724/20263533/7e34102a-aa67-11e6-85e4-26be6feb244d.png)

    <button md-raised-button color="accent" (click)="deleteSelectedTps()">Delete points</button>
    <a [routerLink]="['upload']" md-raised-button color="accent">Return to Upload</a>

**Comment by crisbeto** [comment]
Weird @simonh1000, here's what I get against master with the exact same HTML (obviously the color will be different):

![material2_-_google_chrome_2016-11-14_18-45-34](https://cloud.githubusercontent.com/assets/4450522/20275911/8b6abb94-aa9a-11e6-84eb-25e60555622e.png)

**Comment by kyleledbetter** [comment]
sounds like a dup of https://github.com/angular/material2/issues/1801 which has an unreleased fix in `master` https://github.com/angular/material2/pull/1789

**Comment by elvirdolic** [comment]
Yes this solves the issue #1789
