### ISSUE TITLE
If md-slider changes position after initialization, it can't be clicked in the new location

### ISSUE THREAD

**Issue by alxhub** [angular/material2#1845]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

If md-slider changes position on the page after initialization (e.g. if an NgIf becomes true and more elements appear), it should be usable in the new position.

#### What is the current behavior?

If md-slider changes position on the page after initialization , clicking the slider bar will not work. Clicking the handle results in the handle being rendered far to the right of the mouse pointer.

#### What are the steps to reproduce?

In plunker: http://plnkr.co/edit/dAKSvx6Evjpz1Z5D2DQ7?p=preview

Load the plunk, wait for the hidden content to be shown after 1s timer. Then, try to use the slider.

#### What is the use-case or motivation for changing an existing behavior?

It's horribly broken!

#### Which versions of Angular, Material, OS, browsers are affected?

Unknown, but would guess plunker is using the latest.

#### Is there anything else we should know?

Feel free to ask me to show you the issue in my real app. :)

**Comment by crisbeto** [comment]
There was a change, at some point, that made the slider get the dimensions on mouse enter, instead of on init. Might be worth updating since it looks like the Material version in the Plunker template is old.

**Comment by NicholasAzar** [comment]
Looks like @crisbeto is correct. After updating the systemjs.config.js to:
'@angular/material': 'https://unpkg.com/@angular/material@2.0.0-alpha.10',
resolves this issue when i tried.

**Comment by jelbourn** [comment]
@mmalerba can you investigate?

**Comment by mmalerba** [comment]
yeah, this was fixed by #1663
