### ISSUE TITLE
On IOS Safari, md-button needs to click twice

### ISSUE THREAD

**Issue by johnqiuwan** [angular/material2#1847]
dup #1792

**Comment by crisbeto** [comment]
Have you tried the solution from #1792?

**Comment by johnqiuwan** [comment]
First, I have updated the version to @angular/material": "^2.0.0-alpha.10
Also, I have update the code in the following file based on the instruction of #1792.

However,  the problem is still exist. It looks like the issue is ONLY on md-button but not on md-raised-button.

**Comment by crisbeto** [comment]
I'll give it another look, in that case. Regarding this:

> ...  It looks like the issue ONLY exists on md-button but not on md-raised-button.

If you [comment out this line](https://github.com/angular/material2/pull/1792/files/c0f4d3de106045fba336f37737247788f33484a3#diff-750d8b0165eb725928c42839553a022bR7), does the raised button break again?

**Comment by crisbeto** [comment]
Could you post a simplified example @johnqiuwan, I've been trying this out locally against the `master` branch and it works fine, both on raised buttons and on regular ones:

```html
Click counter: {{ clickCounter }}
<button md-button (click)="clickCounter=clickCounter+1" color="primary">Click</button>
<button md-raised-button (click)="clickCounter=clickCounter+1" color="primary">Click</button>
```

**Comment by johnqiuwan** [comment]
Hi @crisbeto,


```
<div class="banner-button">
	<a md-button (click)="showLoginModal = true" >Register Now</a>
</div>

```

Only on ios, the "click" not been caught on the first click but on the second click. If I use md-raised-button instead of md-button, the problem is gone.

In addition, it has no issue on Android and Web.

**Comment by crisbeto** [comment]
Hmm, I hadn't tried with a link, I was only testing with `button`. Does the `.banner-button` class have any special styling (`:hover`, `:active` etc.)?

**Comment by johnqiuwan** [comment]
I just enable / disable the :hover on the .banner-button class. However, it is not working on both cases on ios. No matter the .banner-button class has a :hover or not.

**Comment by crisbeto** [comment]
I see, I'll try it out with links later.

**Comment by crisbeto** [comment]
Still works fine @johnqiuwan, I used the exact same HTML. It might be better to revisit this once the fix in master has been released.

**Comment by crisbeto** [comment]
@johnqiuwan alpha.11 was released with the fix for this. Can you give it another shot?

**Comment by crisbeto** [comment]
It's been a while since the last response and it has been 2 releases since the fix for this was released. I'll close the issue, but it can always be re-opened if it's still a problem.

**Comment by johnqiuwan** [comment]
Sorry for the late reply. I have confirmed that the alpha.11 fixes the bug

Thank you for your great work : )
