### ISSUE TITLE
Alpha10 - New errors thrown when attempting to integrate with Universal

### ISSUE THREAD

**Issue by MarkPieszak** [angular/material2#1850]
#### Bug, feature request, or proposal:
`TypeError: Cannot read property 'toLowerCase' of undefined at new styleCompatibility (material.umd.js)`

#### What is the expected behavior?
Render Material2 on the server.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.1.2
Material 2.0.0-alpha10
Windows 10

#### Is there anything else we should know?
Alpha 8 can be integrated with Universal, but when trying the new `@angular/material` alpha 10, it throws errors on the server.

> You can reproduce by getting the universal-starter (https://github.com/angular/universal-starter) and upgrading it to use the newest version of Material2.

**Comment by jmurphzyo** [comment]
I see you closed this did you find a work around?

**Comment by MarkPieszak** [comment]
Apologies, no I didn't. I just started getting different errors. I'll leave it open for now, but I'll try and post a reproducible repo etc so we can investigate it further. @jmurphzyo

**Comment by jelbourn** [comment]
It's a known issue that Material doesn't work with Universal; you can follow the progress on #308

**Comment by MarkPieszak** [comment]
Saw that one, ok thanks Jeremy apologies on the duplicate! We had some hacks to get it somewhat working with alpha 8 I believe, but they don't work anymore ;)

**Comment by EricLease** [comment]
@fdambrosio I was getting that error from what appears to be a compatibility guard in case you're using material 1 and 2 together.  If you're not using them both, you may be able to use something like the following...

1. Install [string-replace-webpack-plugin](https://www.npmjs.com/package/string-replace-webpack-plugin)
2. Add the following to vendor sever bundle config:
```
var merge = require('webpack-merge');
var StringReplacePlugin = require('string-replace-webpack-plugin');
...
var serverBundleConfig = merge(sharedConfig, {
...
module: {
        loaders: [ 
            ...
            { test: /material/, 
              loader: StringReplacePlugin.replace({
                  replacements: [
                      {
                          pattern: /renderer\.setElementClass\(element, element.nodeName.toLowerCase\(\), true\);/,
                          replacement: function(match, p1, offset, string) {
                              return '';
                          }
                      }
                  ]
              })
            }
        ]
    },
    plugins: [
        new StringReplacePlugin(),
        ...
     ]
    ...
}
```

But this just led me to the next issue - ripple rendering.  I guess I'll turn off pre-rendering for the time being.
