### ISSUE TITLE
md-input tabindex

### ISSUE THREAD

**Issue by bpearce6942** [angular/material2#1852]
#### Bug, feature request, or proposal:
providing tabindex value results in md-input element receiving focus, in addition to actual input element

#### What is the expected behavior?
tabbing results in the input element receiving focus without md-input receiving focus

#### What are the steps to reproduce?
apply a tabindex attribute to <md-input> and attempt to tab to it

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
specifying a non-default tab order 

#### Is there anything else we should know?
seems like this could be remedied by removing/not applying tabindex attribute to the root level element (md-input).

**Comment by jelbourn** [comment]
Will be resolved as part of md-input refactoring

**Comment by mmalerba** [comment]
`md-input-container` is now available which gives the user control of the underlying `input` element. you should be able to place the tabindex on the native `input` now
