### ISSUE TITLE
Input type datetime-local overlaps with placeholder

### ISSUE THREAD

**Issue by TrevorBroderick1** [angular/material2#1853]
#### Bug, feature request, or proposal:
When the value string is empty, the placeholder of the md-input will overlap with the field.
![image](https://cloud.githubusercontent.com/assets/19823278/20276711/46362100-aa52-11e6-8fa0-b38545a8f5fa.png)

#### What is the expected behavior?
The placeholder should stay above the field

#### What is the current behavior?
The placeholder overlaps with the field

#### What are the steps to reproduce?
Bind an empty string to md-input with type `datetime-local`.

http://plnkr.co/edit/p5vpltRGiy5SQXME2AAh?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It's broken.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.1.2
Material Alpha 10, 9, 8 at least.
Windows 10
Chrome (datetime-local is only supported in chrome afaik).

#### Is there anything else we should know?
This was fixed for `type="date"` in https://github.com/angular/material2/issues/1238 but not for `type="datetime-local"`.

**Comment by mmalerba** [comment]
This is fixed for `md-input-container` which will replace `md-input`
