### ISSUE TITLE
Version "2.0.0-alpha.10" is not greater than "2.0.0-alpha.9-3"

### ISSUE THREAD

**Issue by lqc** [angular/material2#1859]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Running "npm install" when package.json defines ``^2.0.0.alpha.9-3`` should update the package to latest alpha

#### What is the current behavior?

Nothing happens. 

This is because:

```
> a = semver.parse("2.0.0-alpha.9-3")
SemVer {
  loose: undefined,
  raw: '2.0.0-alpha.9-3',
  major: 2,
  minor: 0,
  patch: 0,
  prerelease: [ 'alpha', '9-3' ],
  build: [],
  version: '2.0.0-alpha.9-3' }
> b = semver.parse("2.0.0-alpha.10")
SemVer {
  loose: undefined,
  raw: '2.0.0-alpha.10',
  major: 2,
  minor: 0,
  patch: 0,
  prerelease: [ 'alpha', 10 ],
  build: [],
  version: '2.0.0-alpha.10' }
> semver.gt(b, a)
false
```

It's not a big deal because changing packages to `^2.0.0-alpha.10` works, but it would be great if you didn't make any more "alpha.X-Y" releases. Thanks

**Comment by hacknaked** [comment]
By the way, could you please upload the last version (2.0.0-alpha.11) to npm?

**Comment by jelbourn** [comment]
Going to close this since there's not much we can do about it at this point.

In general, I don't recommending using `^` on these alpha releases because there will be at least a couple breaking changes in each one.
