### ISSUE TITLE
class md-tall md-hue-2 for md-toolbar

### ISSUE THREAD

**Issue by dreweird** [angular/material2#1864]
#### Bug, feature request, or proposal:
please include this feature..

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by DevVersion** [comment]
@dreweird I'm going to close that issue, because we think that the developers can set their custom height on their own and having a `md-tall` class might just collide with the responsive heights functionality.
