### ISSUE TITLE
[BUG] md-input is laggy on lower end machines (video included)

### ISSUE THREAD

**Issue by AmitMY** [angular/material2#1866]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`md-input` to behave as smoothly as HTML input

#### What is the current behavior?
`md-input` is laggy when typing, compared to normal HTML input
Video for demonstaration:
https://youtu.be/TqrzeR5EGIE

#### What are the steps to reproduce?
Source code:
```
<md-card>
    <md-input placeholder="MD input"></md-input>
    <input type="text" placeholder="HTML input" />
</md-card>
```
OS: 
- Android using Meizu, OnePlus 2, Galaxy S2 (Most prominent on Android)
- Windows 10 under a busy workload. (I can reproduce in some computers, and some not)

Plunker:
http://plnkr.co/edit/gR9TjCTZcFtz8Hw4mfJP?p=preview
Still have the issue, but not as bad 

#### What is the use-case or motivation for changing an existing behavior?
UX

#### Which versions of Angular, Material, OS, browsers are affected?
Latest NG2, latest material2, Android, Chrome

#### Is there anything else we should know?
No

**Comment by jelbourn** [comment]
May be obsolete with md-input refactoring.

**Comment by mmalerba** [comment]
@AmitMY any chance you could try this test again with `md-input-container`?

**Comment by AmitMY** [comment]
@mmalerba Sorry, can't. Moved my entire code to ionic2..

**Comment by AmitMY** [comment]
Now that angular/material moved to use `input`, this problem is irrelevant
