### ISSUE TITLE
md tab content not working

### ISSUE THREAD

**Issue by PrabhakaranD** [angular/material2#1867]
I am able to get the tab headers through md tab & md-tab-label

But  md-tab-content not showing. Its not rendering the view. Tried md-tab-body also.

My code: 

        <md-tab-group>
          <md-tab>
            <template md-tab-label>Details</template>
            <template md-tab-content>
              Tab 1
            </template>
          </md-tab>
          <md-tab>
            <template md-tab-label>Feed</template>
            <template md-tab-content>
              Tab 2
            </template>
          </md-tab>
        </md-tab-group>

Output: 

![tabs](https://cloud.githubusercontent.com/assets/22492785/20307267/ad80a214-ab64-11e6-8699-29544cba5267.JPG)

Html rendered code as:

<(adding intentionally)div _ngcontent-jdk-10="" class="md-tab-body" role="tabpanel" ng-reflect-id="md-tab-content-0-0" id="md-tab-content-0-0" aria-labelledby="md-tab-label-0-0">  </div(adding intentionally)>

<div(adding intentionally) _ngcontent-jdk-10="" class="md-tab-body md-tab-active" role="tabpanel" ng-reflect-id="md-tab-content-0-1" id="md-tab-content-0-1" aria-labelledby="md-tab-label-0-1">  
            
            
            </div(adding intentionally)>

Please HELP!

**Comment by ocarreterom** [comment]
`md-tab-content` has been removed. You have how to use tabs in the doc:
 https://github.com/angular/material2/blob/master/src/lib/tabs/README.md

**Comment by jelbourn** [comment]
Please see the changelog when there is a new release:
https://github.com/angular/material2/blob/master/CHANGELOG.md

**Comment by PrabhakaranD** [comment]
Thanks a ton @jelbourn  @ocarreterom  for your quick response.
