### ISSUE TITLE
MdDataTable proposal

### ISSUE THREAD

**Issue by eagle-dan1349** [angular/material2#1869]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Availability of MdDataTableComponent and related components

#### What is the current behavior?
Lack of MdDataTableComponent and related components

#### What are the steps to reproduce?
N/a

#### What is the use-case or motivation for changing an existing behavior?
Angular2-based implementation of Material data table

#### Which versions of Angular, Material, OS, browsers are affected?
Any

#### Is there anything else we should know?
I'm working on very similar task and willing to cooperate.

**Comment by jelbourn** [comment]
#581
