### ISSUE TITLE
md-checkbox layers on default checkbox

### ISSUE THREAD

**Issue by arekKalbarczyk** [angular/material2#1870]
**Bug, feature request, or proposal:**
Bug ?

**What is the expected behavior?**
Browser renders only one checkbox (md-checkbox)

**What is the current behavior?**
2 checkboxes(default and md-checkbox) are rendered on top of eachother

**What are the steps to reproduce?**
Migrate from alpha 8 to alpha10, add simple md-checkbox to a view, render in chrome

before selecting:
![image](https://cloud.githubusercontent.com/assets/15320515/20311176/172a9e4c-ab4f-11e6-9152-dca5d855f524.png)
after selecting:
![image](https://cloud.githubusercontent.com/assets/15320515/20311274/6f982afe-ab4f-11e6-8fd9-cf6388420d01.png)
Checkboxes worked correctly before the migration.
I have removed node_modules, cleared cached and reinstalled everything in my app.

Code itself isn't really complicated.
```
<md-checkbox formControlName="remember">
  {{ 'remember' | translate }}
</md-checkbox>
```

#EDIT
This was caused by themes not loading themselves properly.

**Comment by ashishsajwan** [comment]
@arekKalbarczyk  

> I have removed node_modules, cleared cached and reinstalled everything in my app.

this fixed the issue ?? material theme loaded after this ??
