### ISSUE TITLE
md-menu when posted  does not maintain its position relative to trigger button after scrolling.

### ISSUE THREAD

**Issue by cwjolly** [angular/material2#1879]
#### Bug, feature request, or proposal:
This is a bug. I discovered this when trying to scroll a div under a fixed header with the menu posted to the screen. the trigger buttons scroll but the menu does not.  Plunker shows issue 

#### What is the expected behavior?
the posted menu should maintain it positon relative to the trigger button regardless of scrolling 

#### What is the current behavior?
plunker : http://plnkr.co/edit/tvRKbZCOku9Rk4tQ97nW?p=preview
1. click menu button then scroll the view port the menu maintains its position relative to the 
   viewport not the trigger button. 
Alternatively 
2. Scroll menu up the screen then click trigger button . Menu appears where the trigger button orignally appeared. 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
obvious from plunker.  Even if you somehow force menu to unpost when scrolling the next time 
you post the menu it is still posting to old positon. Makes scrolled content with menu unusable. 

#### Which versions of Angular, Material, OS, browsers are affected?
I assume plunker has latest. However, my project is usiing angular 2.1.0 and material : experimental

#### Is there anything else we should know?
seems like a serious bug .

**Comment by jelbourn** [comment]
Tracked via #1430
