### ISSUE TITLE
Dialog : Disable close does not exist

### ISSUE THREAD

**Issue by kenp77** [angular/material2#1886]
Hi,

Based on the last update of the Dialog Material 2, i added `disableClose: false `
```
  this.dialogRef = this.dialog.open(JazzDialog, {
     disableClose: false
    })
```
But now im getting an error : `Argument of type '{ disableClose: boolean; }' is not assignable to parameter of type 'MdDialogConfig'.`

Any idea why i'm having this error ?

**Comment by crisbeto** [comment]
What version of Material are you using? This was introduced in `alpha.10`.

**Comment by kenp77** [comment]
I was using 9.3 and now i just updated to 10 and it solved the problem. Thank you
