### ISSUE TITLE
Basic theming for md-icon

### ISSUE THREAD

**Issue by tdawgy** [angular/material2#1888]
#### Bug, feature request, or proposal:
Theming isn't currently implemented for md-icon.

#### What is the expected behavior?
Color an icon based on the primary/accent/warn colors defined in a theme.

#### What is the current behavior?
icon_theming file exists but has yet to be implemented.

#### What are the steps to reproduce?
Create a theme, use md-icon.

#### What is the use-case or motivation for changing an existing behavior?
Create consistent icon coloring across applications.

#### Which versions of Angular, Material, OS, browsers are affected?
All, as far as I am aware.

#### Is there anything else we should know?
I appreciate all the great work you're doing 👍

**Comment by jelbourn** [comment]
We probably should have a `color="primary|accent|warn"` property for icon.

**Comment by tdawgy** [comment]
Good call, I've created a PR (#1896) for this, let me know if I've missed some of the contributing guidelines or if you have any concerns.

**Comment by DevVersion** [comment]
This seems to be solved with #1896 now
