### ISSUE TITLE
Getting Started Guide missing a step to install @types/hammerjs

### ISSUE THREAD

**Issue by shaozi** [angular/material2#1889]
#### Bug, feature request, or proposal:

Documentation

#### What is the expected behavior?

New project with angular-cli and tried to add material2 by following Getting Started Guide.
After added a material tag, compile failed with bunch of `Cannot find name 'HammerManager'.` and `Cannot find name 'HammerInput'.` errors.

The solution is as in issue #977 to install 

`npm install --save hammerjs @types/hammerjs`

#### What is the use-case or motivation for changing an existing behavior?

Document usability

#### Which versions of Angular, Material, OS, browsers are affected?

Latest

**Comment by jelbourn** [comment]
@shaozi we do mention it: https://github.com/angular/material2/blob/master/GETTING_STARTED.md#additional-setup-for-md-slide-toggle-and-md-slider

Do you want to send a PR to make this more specific?

**Comment by bluedragonknight** [comment]
I followed both the Quickstart and other posts i still get a 404 error with HammerJS.  I have updated my systemjs.config app as they have updated Angular.IO.  I am not using the CLI as i already had a testing app started before they moved to the Webpack and not sure i want to learn it until Webpack2 comes out.  These errors only started as of late once i did an update to angular.io files.  Without hammerjs nothing works and with it i get the 404.

tsconfig
`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": ["./node_modules/@types"],
    "types": [ "hammerjs" ]
  }
}`

app.module
`import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { MaterialModule }from '@angular/material';
import { AppComponent }  from './app.component';
import { MaterialNavComponent } from './UITools/MaterialNav/UITools.MaterialNav.Component';
import { myComboBox } from './UITools/ComboBox/app.uitools.combobox';

import 'hammerjs';

@NgModule({
    imports:      [ BrowserModule, MaterialModule.forRoot() ],
    declarations: [ AppComponent, MaterialNavComponent, myComboBox ],
    bootstrap:    [ AppComponent, MaterialNavComponent, myComboBox ]
})
export class AppModule {

}`

> Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/hammerjs
	Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/hammerjs
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:889:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:345:33) [<root>]
	Error loading http://localhost:3000/node_modules/hammerjs as "../node_modules/hammerjs" from http://localhost:3000/app/app.module.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:889:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:345:33) [<root>]
	Error loading http://localhost:3000/node_modules/hammerjs as "../node_modules/hammerjs" from http://localhost:3000/app/app.module.js
