### ISSUE TITLE
Resizing to icons

### ISSUE THREAD

**Issue by michaeljota** [angular/material2#1891]
#### Bug, feature request, or proposal:

feature request

#### What is the expected behavior?

A simple way to resizing the icons with directives. It could be like:

```html
<md-icon size="2"></md-icon> <!-- This would make the icon size twice -->
```
or
```html
<md-icon x2></md-icon> <!-- This would make the icon size twice -->
```

#### What is the current behavior?

There is not *simple* way, or not a documented one at least, to resize the icons. If you want to resize the icons, you have to set the height, width, and font-size at the same size in the [s]css. 

#### What is the use-case or motivation for changing an existing behavior?

The need of a simple way to resize the icon and the font.

**Comment by SamiAl90** [comment]
By the definition of material icons they have a size of 24x24px.
https://material.google.com/style/icons.html#icons-system-icons

however if you still prefer to resize them based on the width of the screen, you can use css media-queries.
http://www.w3schools.com/cssref/css3_pr_mediaquery.asp

**Comment by michaeljota** [comment]
When using icons as `md-prefix` inside of a `md-input`, the size pulls the input upwards and breaks the layout of the input element.

**Comment by jelbourn** [comment]
We would recommend people use css to size the icons.

**Comment by michaeljota** [comment]
As I said, when using an icon with `md-icon`, in a `md-prefix`, the size of the icon push the input text upwards, breaking the layout.

![prefix](https://cloud.githubusercontent.com/assets/10507776/20540271/fce24b40-b0ce-11e6-8841-84ee1788238b.gif)

I expect the icon to resize itself, or at least an easy way to resize it.
