### ISSUE TITLE
md-button-toggle display bug.

### ISSUE THREAD

**Issue by Borki** [angular/material2#1893]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

the md-button-toggle looks like a button

#### What is the current behavior?
http://imgur.com/jlM5qqr

#### What are the steps to reproduce?

create toggle buttons without a **theme**.

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/material": "2.0.0-alpha.10"
"@angular/core": "~2.1.0"

**Comment by jelbourn** [comment]
A theme is required.
