### ISSUE TITLE
Blur text on floating label animation on md-input in a form

### ISSUE THREAD

**Issue by johnqiuwan** [angular/material2#1897]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The floating label animation on md-input should NOT make the text blur while transforming

#### What is the current behavior?
The text will become blur while transforming (floating)

#### Which versions of Angular, Material, OS, browsers are affected?
Angualr2 / "@angular/material": "^2.0.0-alpha.10" / Windows 8.1 / Only on desktop but not on mobile browsers

**Comment by jelbourn** [comment]
@hansl may be fixed as obselete as part of md-input refactor

**Comment by mmalerba** [comment]
The text doesn't seem blurry. There is a little bit of jank in the transition, I think because the padding change isn't transitioned. #2246 should fix that.
