### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by herlon214** [angular/material2#19]
Hi guys, can anyone tell me the project status? Can I use him at production? I didn't found any example to use this material2 with angular2.

Thanks in advance.

**Comment by joshtoo** [comment]
No, this is nowhere near ready. Currently the infrastructure is being added to facilitate the community beginning to add Material2 Components.

So in short, it isn't even ready for us to begin working on it and no way to know when it will be in a usable state as a package.

**Comment by herlon214** [comment]
Thanks for the explanation Joshua! I'm so exited to use this lib as far as
possible :)

Em terça-feira, 19 de janeiro de 2016, Joshua Wiens <
notifications@github.com> escreveu:

> No, this is nowhere near ready. Currently the infrastructure is being
> added to facilitate the community beginning to add Material2 Components.
>
> So in short, it isn't even ready for us to begin working on it and no way
> to know when it will be in a usable state as a package.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material2/issues/19#issuecomment-172762994>.
>


-- 
*Att, Herlon Aguiar*

**Comment by jelbourn** [comment]
Yeah, if you check the source, you'll see that there's just one component (button) with one unit test while we're getting everything set up. I don't think anyone would _want_ to use it yet.
