### ISSUE TITLE
[md-nav-list][bug] Keyboard support

### ISSUE THREAD

**Issue by chouclee** [angular/material2#1902]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
https://github.com/angular/material2/pull/1599
nav-list should support keyboards events like keyup, keydown.

#### What is the current behavior?
Only works when scroll bar can scroll.  

#### What are the steps to reproduce?
http://plnkr.co/edit/7KTO8hIAgb9VO7oubNoF?p=preview
Click 'AB'. Keyup will not work. Keydown works until 'BB' 

#### What is the use-case or motivation for changing an existing behavior?
Fully support of keyboards events, at least for keyup, keydown and enter.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.1.0
Material: Master
OS: MacOS 10.11.6
#### Is there anything else we should know?
Nope

**Comment by jelbourn** [comment]
@marcysutton For a list of anchors, should the interaction just to be to rely on the browser's default behavior (tabbing through them vs. having arrow-key shortcuts)?

**Comment by marcysutton** [comment]
@jelbourn yes, that is correct!

**Comment by jelbourn** [comment]
Going to close this as working-as-intended then; the a11y for the nav-list determines the interaction here.
