### ISSUE TITLE
MdDialog in another document

### ISSUE THREAD

**Issue by belveryin** [angular/material2#1908]
#### Bug, feature request, or proposal:
Feature request.

#### What is the expected behavior?
The possibility to attach the dialog to another but the current document.

#### What is the current behavior?
It is attached to the current document.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Have different applications in different iframes with different frameworks works fine but if the application with angular and Material is not in the parent frame the dialog backdrop is limited to it's iframe.

**Comment by jelbourn** [comment]
This is not something we'd really want to support any time in the near future (if ever).
