### ISSUE TITLE
BUG - md-input (change) is not called

### ISSUE THREAD

**Issue by AmitMY** [angular/material2#1912]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
call output change every time the input changes

#### What is the current behavior?
Calls (change) when press "enter", or unfocused the input

#### What are the steps to reproduce?
http://plnkr.co/edit/Ew5eVXrxcedTbYHvF81x?p=preview

write something, then press enter

#### What is the use-case or motivation for changing an existing behavior?
Input changes tracking, validation

#### Which versions of Angular, Material, OS, browsers are affected?
2.2.0, beta 10, ALL

**Comment by mtrdp642** [comment]
This isn't a bug specific to Material; add a regular <input type="text" /> with the same bindings and the same result occurs. [Reading up on the change event ](https://developer.mozilla.org/en-US/docs/Web/Events/change) shows that its behavior varies between browsers and controls.

Sounds like you need one of the key events, such as [keypress](https://developer.mozilla.org/en-US/docs/Web/Events/keypress), [keydown](https://developer.mozilla.org/en-US/docs/Web/Events/keydown), or [keyup](https://developer.mozilla.org/en-US/docs/Web/Events/keyup), or perhaps the [input event](https://developer.mozilla.org/en-US/docs/Web/Events/input).

**Comment by jelbourn** [comment]
It's currently working as intended.

Note, though, that `md-input` is currently being factored. In an upcoming release it will be`<input md-input>` and simply use the native `(change)` event.
