### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by chriscerk** [angular/material2#1914]
#### Bug, feature request, or proposal:

Bug / Proposal

Similar to #308 but posting for exposure of the stack-trace I'm getting.

#### What is the expected behavior?

Correct rendering of md components. 

Incompatibility with Universal should be strongly noted in the README.md. I spent 4 hours trying to render the material components until I saw a thread mentioned Universal incompatibility by @jelbourn 

#### What is the current behavior?

Worked correctly for certain combinations of md components but then...

Consistent Error thrown:

> Exception: Call to Node module failed with error: TypeError: Cannot read property 'toLowerCase' of undefined
> at new StyleCompatibility (C:\Code\decisionmaker\src\decisionmaker\node_modules\@angular\material\core\compatibility\style-compatibility.js:26:59)
> at AppView._View_AppComponent0.createInternal (AppComponent.ngfactory.js:17:34)
> at AppView.create (C:\Code\decisionmaker\src\decisionmaker\node_modules\@angular\core\bundles\core.umd.js:9178:25)
> at AppView._View_AppComponent_Host0.createInternal (AppComponent_Host.ngfactory.js:17:14)
> at AppView.create (C:\Code\decisionmaker\src\decisionmaker\node_modules\@angular\core\bundles\core.umd.js:9178:25)
> at ComponentFactory.create (C:\Code\decisionmaker\src\decisionmaker\node_modules\@angular\core\bundles\core.umd.js:5832:40)
> at ApplicationRef_.bootstrap (C:\Code\decisionmaker\src\decisionmaker\node_modules\@angular\core\bundles\core.umd.js:6804:44)
> at C:\Code\decisionmaker\src\decisionmaker\node_modules\@angular\core\bundles\core.umd.js:6713:93
> at Array.forEach (native)
> at PlatformRef_._moduleDoBootstrap (C:\Code\decisionmaker\src\decisionmaker\node_modules\@angular\core\bundles\core.umd.js:6713:46) 
> 

#### What are the steps to reproduce?

Angular Universal + .NET Core + webpack

Project is in my repo.

#### What is the use-case or motivation for changing an existing behavior?

Having the info that material2 is not compatible with Universal in a more prominent location will save future individuals time and frustration.

Fixing the Universal-Material2 issue is important if Angular 2 is supposed to be the leading multi-platform framework.

#### Which versions of Angular, Material, OS, browsers are affected?

>     "@angular/common": "2.1.0"
>     "@angular/core": "2.1.0"
>     "@angular/material": "^2.0.0-alpha.10"
>     "angular2-universal": "2.1.0-rc.1",

Browser: Vivaldi, Chrome

#### Is there anything else we should know?

Love the work that's done so far and I'm excited for when it's fully compatible with Angular Universal.

**Comment by jelbourn** [comment]
Tracking this via #308
