### ISSUE TITLE
Basic theming for md-tooltip

### ISSUE THREAD

**Issue by tdawgy** [angular/material2#1920]
#### Bug, feature request, or proposal:
Theming isn't currently implemented for md-tooltip.

#### What is the expected behavior?
Color a tooltip based on the primary/accent/warn colors defined in a theme.

#### What is the current behavior?
tooltip_theming file exists but has yet to be implemented.

#### What are the steps to reproduce?
Create a theme, use md-tooltip.

#### What is the use-case or motivation for changing an existing behavior?
Create consistent tooltip coloring across applications.

#### Which versions of Angular, Material, OS, browsers are affected?
All, as far as I am aware.

#### Is there anything else we should know?
I appreciate all the great work you're doing 👍

**Comment by jelbourn** [comment]
@tdawgy what do you consider missing? The [Material Design spec](https://material.google.com/components/tooltips.html#tooltips-tooltips-desktop) gives a single specific color for tooltips regardless of light/dark theme.

**Comment by tdawgy** [comment]
My mistake, I made a bad assumption about tooltips without first double checking the MD spec.
