### ISSUE TITLE
menu moves with the scrolling of the page

### ISSUE THREAD

**Issue by ottosson** [angular/material2#1922]
#### Bug, feature request, or proposal:
Bug(?). Open menus will follow along when scrolling the page. This means it moves out of it's intended position when scrolling.

#### What is the expected behavior?
The menu should stay in place when scrolling.

#### What are the steps to reproduce?
Open menu. Scroll page until menu should be "out of picture".

#### Which versions of Angular, Material, OS, browsers are affected?
Same as [Angular Material2 Example App](https://material2-app.firebaseapp.com/), as of the date of this post.

**Comment by fxck** [comment]
dup of https://github.com/angular/material2/issues/1430

to me, this is one of the most ux breaking things in the project, especially annoying with tooltips and menus

**Comment by jelbourn** [comment]
Closed into #1430
