### ISSUE TITLE
getting component not found for md-select in angular2 2.1.0

### ISSUE THREAD

**Issue by prakashs-mtsin** [angular/material2#1924]
my code :
 <md-select placeholder="Food">
<md-option *ngFor="let food of options" [value]="food.value"> {{ food.value }} </md-option>
</md-select>

Unhandled Promise rejection: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'md-option'.
1. If 'md-option' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'md-option' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("      -->
         <md-select placeholder="Food">
          <md-option *ngFor="let food of options" [ERROR ->][value]="food.value"> {{ food.value }} </md-option>
        </md-select>
        <div class="pullButt"): RoleComponentComponent@8:50 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'md-option'.
1. If 'md-option' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'md-option' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("      -->
         <md-select placeholder="Food">
          <md-option *ngFor="let food of options" [ERROR ->][value]="food.value"> {{ food.value }} </md-option>
        </md-select>
        <div class="pullButt"): RoleComponentComponent@8:50
    at TemplateParser.parse (http://localhost:4200/main.bundle.js:17250:19)
    at RuntimeCompiler._compileTemplate (http://localhost:4200/main.bundle.js:38247:51)
    at http://localhost:4200/main.bundle.js:38167:62
    at Set.forEach (native)
    at RuntimeCompiler._compileComponents (http://localhost:4200/main.bundle.js:38167:19)
    at createResult (http://localhost:4200/main.bundle.js:38063:19)
    at ZoneDelegate.invoke (http://localhost:4200/main.bundle.js:84086:26)
    at Zone.run (http://localhost:4200/main.bundle.js:83968:43)
    at http://localhost:4200/main.bundle.js:84356:57
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:84119:35)

**Comment by jelbourn** [comment]
@prakashs-mtsin `md-select` has not been released yet.

**Comment by johnking** [comment]
Hi @jelbourn, 

Do you know when this component will be released? 

I need it ... 

thanks
