### ISSUE TITLE
Sidenav does not animate content when sidenav content is contained in a child component

### ISSUE THREAD

**Issue by xikky** [angular/material2#1926]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
page content is pushed and pulled with sidenav

#### What is the current behavior?
sidenav opens on top of content

#### What are the steps to reproduce?
Place sidenav content in a component, wrap the component selector with md-sidenav-layout and place content under the component selector, as shown here:
http://plnkr.co/edit/xqrUKbT9WYJfCEZa6rrR?p=info

#### What is the use-case or motivation for changing an existing behavior?
Mainly for organisational purpose. I think it's nice to have sidenav content in it's own component, rater then having to put the rest of the page content within the same component

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.1.1
Material: alpha-10
chrome

**Comment by xikky** [comment]
I hope I am clear enough with this problem :)

**Comment by mmalerba** [comment]
dup of #2174
