### ISSUE TITLE
Feature Request - MdBarcode

### ISSUE THREAD

**Issue by vinagreti** [angular/material2#1927]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
When using a barcode reader, we need to get the scanned code avoiding conflicts with browsers

#### What is the current behavior?
When using a barcode reader in a input, Chrome opens history and Firefox opens Bookmarks window.  Not tested with other browsers.

#### What are the steps to reproduce?
Just focus in an input and scan a bar code. You will see that chrome opens the hisstory and Firefox open bookmarks

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
It is not a material bug, it is a browsers and barcode reader conflict

#### What is the use-case or motivation for changing an existing behavior?
Nothing is changing we are creating a new component to handle the barcode and browsers conflict

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-alpha.10

#### Is there anything else we should know?
https://bugs.chromium.org/p/chromium/issues/detail?id=50171
https://www.experts-exchange.com/questions/26682548/handheld-barcode-scanner-opens-IE-favorites-when-scanning-barcodes.html

**Comment by jelbourn** [comment]
This isn't really something that falls within the purview of the Angular Material project.
