### ISSUE TITLE
Setting md-list-item background color

### ISSUE THREAD

**Issue by theunreal** [angular/material2#1928]
I'm trying to simply set a background color to `md-list-item`.

`<md-list-item style="background-color:red">`

the background color stays white.

What's wrong?

Basically what I'm trying to do is set `md-list-item` to active and change it's background color if the item is active.

**Comment by mwawrusch** [comment]
not tested, but have you tried:  <md-list-item [style.background-color]="'red'">....

**Comment by theunreal** [comment]
Yeah, it's same.

**Comment by jelbourn** [comment]
@theunreal please follow the issue template. Providing a plunker is the best way to have your issue looked at.

**Comment by tyholby** [comment]
@theunreal Just had this problem. My fix was making sure to import the MdListModule in my AppModule.
