### ISSUE TITLE
Optional delay when showing spinner

### ISSUE THREAD

**Issue by mwawrusch** [angular/material2#1929]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
I would be amazing if the spinner would have some delayed show capability. In most cases this would be outside the scope of the control but given its ubiquitous use it might make sense to incorporate directly. E.g. when visibility changes the spinner should show after X ms

#### What is the current behavior?

Spinner is shown immediately.

#### What are the steps to reproduce?

n/a

#### What is the use-case or motivation for changing an existing behavior?

The reason for this is better UI. We don't want to show a spinner when the loading time is less than ~250ms - it only distracts.

#### Is there anything else we should know?
We have 75 degrees in Santa Monica today, which totally beats San Francisco...

**Comment by jelbourn** [comment]
This isn't a responsibility that really belongs in the component; the app can be responsible for showing the spinner at the appropriate time.
