### ISSUE TITLE
md-input maxlength is not working with type number....

### ISSUE THREAD

**Issue by r-vijay-r** [angular/material2#1934]
#### Expected to get mobile number from user with 10 digits with the code
`<md-input type="number" maxlength=10 #mobile />`

#### the limit is not taking into consideration and charactercount and invalid also not working as expected... 

####using windows7, angular2 (latest), material2(latest)

**Comment by mmalerba** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-maxlength

>If the value of the type attribute is text, email, search, password, tel, or url, this attribute specifies the maximum number of characters (in Unicode code points) that the user can enter. For other control types, it is ignored.

It sounds like you probably want `type=tel`
