### ISSUE TITLE
feat(data-table) : Add module MdDataTable !

### ISSUE THREAD

**Issue by bastienlemaitre** [angular/material2#1935]
Hi, i've created a MdDataTableModule !
Tried to pull but error 403.. So:
![image](https://cloud.githubusercontent.com/assets/11610748/20455869/87cce032-ae66-11e6-9ab4-ff17bdc516f3.png)
![image](https://cloud.githubusercontent.com/assets/11610748/20455872/a1425772-ae66-11e6-851a-7dae872735c2.png)
![image](https://cloud.githubusercontent.com/assets/11610748/20455877/ae80935e-ae66-11e6-807f-3e9f7de70aec.png)
Code:
```
<md-data-table-card>
  <md-data-table-header searchable>Materials</md-data-table-header>
  <md-data-table selectable [data]="materials" key="id">
    <md-data-table-column header="Nom" property="name" text-cell sortable sorted></md-data-table-column>
    <md-data-table-column header="Prix" property="price" sortable></md-data-table-column>
    <md-data-table-column header="Quantitée" property="quantity" sortable></md-data-table-column>
  </md-data-table>
  <md-data-table-pagination></md-data-table-pagination>
</md-data-table-card>
```
Missing md-select for it !

**Comment by jelbourn** [comment]
@bastienlemaitre I can't really follow what your issue is. Please use the issue template.
