### ISSUE TITLE
Container for non-sidenav-layouts

### ISSUE THREAD

**Issue by mmmichl** [angular/material2#1938]
For layouts not using the `<md-sidenav-layout>`, dark themes can not be used, as the background does not change. Due to that, the text gets invisible and form items look bad.

To understand, what I mean, check out the plunkr. Basically I took your template and changed the theme: http://plnkr.co/edit/w4v95im2irvNm4dAzQ5k

I was looking for some container class or element, but wasn't lucky in finding any.

**Comment by michaeljota** [comment]
Layout component it's not even started yet. Does not have an issue tracking the status either.

**Comment by mmmichl** [comment]
If this is covered by the layout components, then this issue should be closed.

BTW, found a workaround by wrapping everything within a `<md-sidenav-layout>`.

**Comment by jelbourn** [comment]
We should have something for this, but as a workaround you can simply create a css class that uses the appropriate color, e.g.
```scss
.my-background {
  background-color: md-color($background-palette, background);
}
```
