### ISSUE TITLE
PR worth making?

### ISSUE THREAD

**Issue by John0x** [angular/material2#1939]
Hey, material2 has a lot of problems with angular universal right now and I was wondering whether or not it would be worth the effort to create a PR fixing those problems?

I saw that there are a lot of PR's that are waiting to merged for qutie some time now. Are the material2 maintainers too busy right now to take care of them?

**Comment by fxck** [comment]
yo @jelbourn @kara

**Comment by jelbourn** [comment]
I chatted with the maintainers of Universal and they said that we should hold off on any work related to that as they do some large-scale refactorings and much of the code is moved into `angular/angular`. I'll update #308 when we're ready to start making changes to support it. 

@fxck Keep in mind that last week was a holiday week in the US.

**Comment by fxck** [comment]
It's not only about this issue, issues are often not properly labelled and/or people don't get replies from team members and it causes some confusion. I know it's pain in the ass to manage, but isn't it worth it?
