### ISSUE TITLE
Cannot find name 'HammerInput' and 'HammerManager'

### ISSUE THREAD

**Issue by j-tee** [angular/material2#1944]
I installed Angular Material 2.0.0-alpha.10 alongside hammerjs@2.0.8 and @types/hammerjs@2.0.33.
Per the instructions, guidelines and suggestions, I imported hammerjs in my main.ts file but I could not get rid of the errors. After several weeks I thought I should import 'hammerjs' in the files containing the errors as well. After importing hammerjs in MdGestureConfig.d.ts all the errors disappeared. I really dont know what to make of this. So I thought I should ask the experts about it

**Comment by SRutter75** [comment]
I had the same error. I just needed to restart the server running from angular-cli then the 'HammerInput' and 'HammerManager' dependancies are resolved.

**Comment by j-tee** [comment]
I just started work on getting the sidenav to work. Hoping I made the right call

**Comment by crisbeto** [comment]
@j-tee You need to include `hammerjs` in the types section of your `tsconfig.json`:

```js
{
  "compilerOptions": {
    // other typescript options
    "types": [
      "hammerjs"
    ]
  }
}
```

I'll see how to make this clearer in the docs.
