### ISSUE TITLE
Documentation is unclear about how to get data into a Dialog.

### ISSUE THREAD

**Issue by SamMousa** [angular/material2#1947]
#### Bug, feature request, or proposal:
Documentation bug.

#### What is the expected behavior?
When I use the MdDialog service to open a dialog with some component, I'd love to be able to pass some configuration into that component.

#### What is the current behavior?
The `dialogRef` exposes `componentInstance`, which allows me to set properties / call functions on the component after construction, however I'm unsure if this is the recommended approach since it is not mentioned in the docs.

#### What are the steps to reproduce?

Read the docs at https://github.com/angular/material2/blob/master/src/lib/dialog/README.md, and notice the example uses a "static" dialog. 

#### What is the use-case or motivation for changing an existing behavior?
It would improve the documentation and reduce the number of future issues.

#### Which versions of Angular, Material, OS, browsers are affected?
Latest /all

#### Is there anything else we should know?
I can submit a PR for improved documentation of an answer from this threads provides sufficient information!

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/material2/issues/1377#issuecomment-250632661

**Comment by DzmitryShylovich** [comment]
> The dialogRef exposes componentInstance, which allows me to set properties / call functions on the component after construction, however I'm unsure if this is the recommended approach since it is not mentioned in the docs.

https://github.com/angular/material2/issues/1377#issuecomment-250632661

**Comment by eagle-dan1349** [comment]
@SamMousa, as I see it's actually the only way to do it directly. You can use an injected service for that, but, IMHO, it would be an overkill.

**Comment by SamMousa** [comment]
I've added this to my todo list.

**Comment by tmburnell** [comment]
Is there any timeframe of when this will be added? if not could a code snippet be created here to show how to do it?

**Comment by SamMousa** [comment]
@tmburnell I'm currently no longer working on an angular related project so it's low on the list.

**Comment by tmburnell** [comment]
I figured it out from another post: 
use this when opening
```
let dialogRef = this.dialog.open(myModal);
dialogRef.componentInstance.data = myData;
```
use this in the modal 
```
this.data = this.dialogRef.componentInstance.data;
```

**Comment by M-a-c** [comment]
@SamMousa 
I know in general components should share data (typically modeled data) with a service. (depending on what you're doing)
https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#bidirectional-service

If you're looking for something quick I don't think there is anything wrong with tmburnells example, it just depends on what you're trying to accomplish and how expandable or modular you want it to be.

**Comment by SamMousa** [comment]
I'm gonna close this since I no longer expect I'll be working on it in the foreseeable future.

**Comment by M-a-c** [comment]
@SamMousa I have a PR out for this, you were right about it being confusing.
