### ISSUE TITLE
Select is blurry on IE11

### ISSUE THREAD

**Issue by crisbeto** [angular/material2#1953]
The select is blurry in the demo app on IE 11:

![a](https://cloud.githubusercontent.com/assets/4450522/20498388/4fcf6042-b02d-11e6-8bd3-027ecf372660.png)

**Comment by kara** [comment]
@crisbeto Is this still happening?

**Comment by crisbeto** [comment]
Yes, but I haven't been able to figure out why. It's not because of the transform like the issues we had before.
