### ISSUE TITLE
Bug: md-menu

### ISSUE THREAD

**Issue by joejordanbrown** [angular/material2#1956]
Bug

#### What is the expected behavior?
When a menu is open and you click another action outside of the menu it should follow through with that action.

#### What is the current behavior?
When a menu is open and you click another action outside of the menu it closes the menu and doesn't follow through with the action.

#### What is the use-case or motivation for changing an existing behavior?
When a component uses a transparent overlay this indicates that it should not affect the users other actions.

#### Which versions of Angular, Material, OS, browsers are affected?
Latest

**Comment by jelbourn** [comment]
This is working as intended
