### ISSUE TITLE
Md-Select start value or active value

### ISSUE THREAD

**Issue by dahaupt** [angular/material2#1973]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
The Md-Select-Component should be able to have a start value, which should remain active even after the page has been reloaded. 

After reloading or switching routes I wanna see it like this:
![Image](http://i.imgur.com/4YuQIhj.png)

#### What is the current behavior?
We can't set a start value for select. We can click a button to set it, but there is no attribute available to bind it directly with a variable.

#### What are the steps to reproduce?
Look into existing select examples and try to set a startup value. 

#### Which versions of Angular, Material, OS, browsers are affected?
Angular Material latest version (from master)

#### Is there anything else we should know?
I am not sure if I just don't see the way to do it or if it's already planned for the future.

**Comment by bastienlemaitre** [comment]
Hi, md-select has not been released yet.
Please see [https://github.com/angular/material2/blob/master/README.md](url).

> Will be released in alpha.11

**Comment by dahaupt** [comment]
@bastienlemaitre Hi, I am aware of that, but alpha.11 is already the next version and I can't find any plans (md-select in projects) to realize this feature.

**Comment by seanrkerr** [comment]
@kara & @jelbourn, Just a question around the release date of the Alpha 11. Will this be in November or are we looking at December for this one?

**Comment by DzmitryShylovich** [comment]
December 5th

**Comment by jelbourn** [comment]
We don't yet have an exact date for the next release.

**Comment by seanrkerr** [comment]
ok, no worries.

**Comment by jelbourn** [comment]
@dahaupt  I don't quite follow- is this not just the `value` property of the select?

**Comment by kara** [comment]
@dahaupt The select is a custom value accessor, so you should be able to use ngModel or any other available form directive in Angular 2.

```<md-select [(ngModel)]="food"></md-select>````

**Comment by dahaupt** [comment]
@kara & @jelbourn  This would lead me to set the value with a FormControl object for example. Let's stay in the demo-app select example:

`foodControl = new FormControl('pizza-1');`

This should set a start value of the md-select component. But even if the value is right now, I can just see the placeholder:
![wrong behaviour](http://i.imgur.com/6HrEkbi.png)

This button works fine:

`<button md-button (click)="foodControl.setValue('pizza-1')">SET VALUE</button>`

How can I achieve that in the TypeScript of my component before? What am I doing wrong?

**Comment by kara** [comment]
@dahaupt Aha! Okay, I see what you're talking about, thanks for clarifying. While setting the initial value using `ngModel` does work, setting an initial value using `formControl` doesn't yet because the value is written synchronously before the options exist. I'm submitting a quick fix that should make the code above work. When the select component is released, the fix should go out with it.

**Comment by dahaupt** [comment]
@kara Thanks and keep up the great work! 👍

**Comment by istiti** [comment]
@kara can you please update plan for December ? 
What's about 2 new employee (planned for October)
