### ISSUE TITLE
align right image is not working??

### ISSUE THREAD

**Issue by dreweird** [angular/material2#1975]
` <md-list>
          <md-list-item *ngFor="let item of messages" align="right">
            <img md-list-avatar src="assets/avatar/avatar.png" alt="..."> 
            <h3 md-line> {{item.name}} </h3>
            <p md-line>
              <span> {{item.message}} </span>
            </p>
          </md-list-item>
        </md-list>`

![image](https://cloud.githubusercontent.com/assets/16024897/20585246/b25b5d66-b234-11e6-8c5c-370c10781878.png)

I want it this way

![image](https://cloud.githubusercontent.com/assets/16024897/20585273/d7711fe6-b234-11e6-893a-7ed42b58f946.png)

**Comment by jelbourn** [comment]
@crisbeto can you determine if there's a bug here?

**Comment by dreweird** [comment]
there's no bug but i want the avatar to align also in the right corner in my chat app..alternatively when someone reply....it's more in css i think

**Comment by crisbeto** [comment]
You can achieve the same by setting the list in RTL mode @dreweird:

```html
<md-list dir="rtl">
  <h3 md-subheader>Items</h3>
  <md-list-item *ngFor="let item of items">
    {{item}}
  </md-list-item>
</md-list>
```

Note that you can also do this on individual list items.
