### ISSUE TITLE
How to limit progresss circle to full under 100  instead of value100

### ISSUE THREAD

**Issue by blackhawk389** [angular/material2#1977]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by elekzalan** [comment]
@blackhawk389 Using math. I think if you convert your values to percentages, it solves your problem. For example:
 
![screenshot_1](https://cloud.githubusercontent.com/assets/17826369/20590258/c3a57b60-b22a-11e6-9baa-495206549515.png)

(X) is the spinner value at any moment
(Y) is your value which you want to convert to percentages. 30 in the example.
(Z) is your max value, it can be bigger or smaller than 100. 80 in the example.

**Comment by blackhawk389** [comment]
I was able to do this by yesterday, now its not working

**Comment by jelbourn** [comment]
The progress-circle is always in the "percent space" of 0 to 100. Whatever your actual progress space is (e.g., 0 to 2379 files), you need to map it to percent space.
