### ISSUE TITLE
Visibility problems with md-sidenav

### ISSUE THREAD

**Issue by drager** [angular/material2#1978]
We have two md-sidenav on the same page, one on the left side and another on the right side. If you open the left sidenav on a mobile and tries to swipe away that sidenav, the other sidenav is showed and it should not be showed because we have never opened it.

This is happening because you have just set `visibility: hidden` for `md-sidenav-closed` and not used `display: none` https://github.com/angular/material2/blob/master/src/lib/sidenav/sidenav.scss#L12

**Comment by jelbourn** [comment]
@mmalerba Can you determine if there's a bug?

**Comment by mmalerba** [comment]
I'm not able to reproduce this. If you still have this problem can you please file a new issue with a plunker to reproduce.
