### ISSUE TITLE
md-list background is not same as shown in the document 

### ISSUE THREAD

**Issue by BhattaRj** [angular/material2#1979]
md-list as in document 
![material2 src lib list at master angular material2](https://cloud.githubusercontent.com/assets/11895857/20601098/f78864b6-b27e-11e6-8a41-b39b819f06e2.png)

When implementing 
![admin1040](https://cloud.githubusercontent.com/assets/11895857/20601172/4dc72fd8-b27f-11e6-811d-6d4b4e983ec8.png)

looks very different .dnt knw why

**Comment by crisbeto** [comment]
Can you be a little more specific @BhattaRj? What "doc list" are you referring to?

**Comment by ramRkanna** [comment]
@BhattaRj Can you provide some more details or example?

**Comment by BhattaRj** [comment]
In documentation md-list is like card and background is white when implementing component is not like card and background of md-list is not white ..

**Comment by ocarreterom** [comment]
In documentation md-list is inside md-card component that have white background color. md-list don't have default background color.

**Comment by jelbourn** [comment]
@ocarreterom is correct. `md-list` doesn't have its own background color; it uses the background color of whatever element it is inside of.
