### ISSUE TITLE
hammerjs, universal/node 

### ISSUE THREAD

**Issue by aaltotsky** [angular/material2#1980]
When I installed package V: 2.0.0-alpha.10 together with "hammerjs": "^2.0.8","@types/hammerjs": "^2.0.33", and run with "angular2-universal": "~2.1.0-rc.1", I'm getting an error:

> Exception: Call to Node module failed with error: ReferenceError: window is not defined at Object.<anonymous> (C:\Dev\WWP\x-p\wwp\web\Angular.WebApi\node_modules\hammerjs\hammer.js:2643:4)

Is there a work around of this issue? Obviously, the issue is in hammerjs, but Angular Material2 is integrated with hammerjs.

**Comment by DzmitryShylovich** [comment]
all universal issues are tracked here https://github.com/angular/material2/issues/308
