### ISSUE TITLE
md-icon doesn't get centered as i increase it's font-size

### ISSUE THREAD

**Issue by mhmo91** [angular/material2#1982]
#### Bug, feature request, or proposal:
md-icon doesn't get centered as i increase it's font-size

#### What is the expected behavior?
the icon should maintain it's position.

#### What is the current behavior?
when the icon size is default, it's centered, but as i increase the icon size, it increases size while not maintaining it's center position
if i used the normal material icons, it behaves normally as expected
#### What are the steps to reproduce?
https://drive.google.com/file/d/0B_YegFpj9ymOaDZKWEZBNzQ2Qlk/view?usp=sharing

```html
<div class="container w-100">
    <div class="row feature flex-items-xs-middle flex-items-xs-center">
        <div class="col-xs-12 col-sm-5 text-xs-center">
                   <md-icon class="md-72 pr-xs-8 text-muted">done</md-icon>
            <!--<i class="material-icons md-72 pr-xs-8 text-muted">done</i>-->
        </div>
        <div class="col-xs-12 col-sm-7 text-xs-center text-md-left pr-3">
            <h1> Feature here </h1>
            <p>some description here some description here some description here some description</p>
        </div>
    </div>
</div>
```

#### Which versions of Angular, Material, OS, browsers are affected?

"@angular/core": "2.2.1",
"@angular/material": "^2.0.0-alpha.10",
"@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.13",
running in chrome canary

**Comment by mhmo91** [comment]
I found the problem with the css display property display that are applied to the material-icons class and md-icon tag
when setting the display to inline or initial instead of inline-block, it worked

**Comment by tinayuangao** [comment]
It's hard to tell how you changed the icon size without css.

What I tried is `md-72 {
  width: 72px;
  height: 72px;
  font-size: 72px;
}` and it centered correctly.

**Comment by MubbleAnkur** [comment]
I did some digging in Material icon **css** 
And i found out that the **height**  and **width**  property of icon causing this behaviour 
so In order to correct it, you have to explicitly set the height and width property equal to the **font-size** property in order to center the md icon
