### ISSUE TITLE
I want to use $primary, $accent, $warn in my custom css classes. (angular2, material2)

### ISSUE THREAD

**Issue by amanullahnxb** [angular/material2#1983]
Is there any option to do so?

```
.my-css-class {
background-color: $primary; /*where $primary is from material theme .scss*/
}
```

**Comment by amanullahnxb** [comment]
I am stucked in making application in which we can switch easily from theme to theme. Actually i want to apply same theme to other elements of html too along with material  components.

**Comment by fxck** [comment]
how about actually reading the theming docs 

https://github.com/angular/material2/blob/master/docs/theming.md
https://github.com/angular/material2/blob/master/docs/theming-your-components.md

**Comment by jelbourn** [comment]
This should be what you're looking for:
https://github.com/angular/material2/blob/master/docs/theming-your-components.md

**Comment by amanullahnxb** [comment]
+1
