### ISSUE TITLE
How to change aria-valuemax of progress circle

### ISSUE THREAD

**Issue by blackhawk389** [angular/material2#1984]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by jelbourn** [comment]
The progress-circle is always in the "percent space" of 0 to 100. Whatever your actual progress space is (e.g., 0 to 2379 files), you need to map it to percent space.
