### ISSUE TITLE
md-cards without margin overlap each other

### ISSUE THREAD

**Issue by mozgor** [angular/material2#1985]
Bug on the md-card component

I read the documentation several times, and nothing warned me it would be impossible, so I expected to be able to have several card in the same component without need of any custom css.

Turns out it doesn't work. Without forced separation such as plain text, text wrapped in div, etc, the second car will 'work' (aka its content is still working) but the previous one wont.

The only solution I found to avoid having to write random stuff between each of my cards was to add a custom css class which force margin top / bot to be sure they don't touch.

Unfortunately, I am kinda new on Angular 2 so I didn't manage to produce a Plunker reflecting my settings (Webpack / Angular 2 TS / "@angular/material": "^2.0.0-alpha.10"). Just to let you know, my app is just an Hello world in which I try to put as many angular 2 material graphic components to learn how they work and what kind of workaround would be needed to use the lib even if it's just an alpha atm.

So I don't have any fancy code in my component.ts file, or anywhere, it is empty. Here is my html code after I "solved" the problem : 
`  <md-card class="col-md-12 info-card">
    <h2>A title</h2>
    <md-radio-group>
      <md-radio-button value="option_1">Foo</md-radio-button>
      <md-radio-button value="option_2">Bar</md-radio-button>
    </md-radio-group>

    <md-list>
      <md-list-item *ngFor="let todo of todos">
        <h3 md-line> {{todo.name}} </h3>
        <p md-line>
           <span> {{todo.desc}} </span>
           <span> - {{todo.details}} </span>
        </p>
      </md-list-item>
    </md-list>
  </md-card>

  <md-card class="info-card col-md-12">
    <md-radio-group>
      <md-radio-button>Alpha</md-radio-button>
      <md-radio-button>Beta</md-radio-button>
      <md-radio-button disabled>Gamma</md-radio-button>
    </md-radio-group>
  </md-card>`

And here is the css I used : 
`.info-card {
  margin-top: 10px;
  margin-bottom: 10px;
}`

I am sorry if it results of my missunderstanding, but I believe it is not, so I would like to know if someone else got the problem and if there is a cleaner solution than mine.

This problem occured on version 2.0.0-alpha.10, on windows, on Firefox 50.0 and Google Chrome 54.0.

**Comment by fxck** [comment]
this is expected behaviour, none of the material components have margins, so you can define your own

**Comment by mozgor** [comment]
I might be wrong, but what I meant is, without the custom margins (which i didn't want / need) the cards *look* fine but I *guess* they overlap or something because without those custom margins, the first card is "disabled" or whatever by the second one, aka no input possible any more (text / click on radio button / etc do no work without the custom margins).

So if this is the expected behaviour, "define your own margin or get your page frozen to death", it might be cool to precise it on the doc. If this is not (as I supposed), there is an issue.

**Comment by jelbourn** [comment]
@mozgor can you reproduce your issue in a plunker? There's nothing in material that would be making cards overlap with each other.

**Comment by mozgor** [comment]
I will do one asap but for now, I get tons of 403 errors when loading plunker template. It could be because of my shitty proxy here, so I'll try later to provide one from 'regular' connection.
