### ISSUE TITLE
Tour of Heroes app uses angular2-material

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#199]

**Comment by m0t0r** [comment]
@jelbourn, is this issue `good for community contribution` ?

**Comment by jelbourn** [comment]
@m0t0r sure, but it's @johnpapa that owns that app; I mainly made this issue to remind myself to talk to him about it.

**Comment by m0t0r** [comment]
Okay, I think I can find time in a couple of days and I would like to help. @jelbourn what do think is the best way to start ? Should I wait for @johnpapa's instructions ?   what exactly is expected ? something like a written guidelines of original `Tour of Heroes` but replaced with material2 components + app?

**Comment by johnpapa** [comment]
yes, i *want* ToH to use AM2 once its ready

**Comment by jelbourn** [comment]
@johnpapa if you let us know which components the app uses / needs, I can let you know when we're ~ready to try it out.

**Comment by BernhardRode** [comment]
I think AM2 is a bit to much for the basic ToH, beginners will be overwhelmed.

**Comment by ciasej** [comment]
Instead of rewriting the original TOH would it be better to provide an additional section to the end of the existing guide that shows developers how to update the completed TOH app and it's components into md2 components?

**Comment by jelbourn** [comment]
Planning now to have a separate starter app / tutorial for Material.

**Comment by imVinayPandya** [comment]
@jelbourn have to created AM2 starter app / tutorial for material? I hope it will have universal + AM2 + Angular 5+ supports.
