### ISSUE TITLE
Grid List & List Animation

### ISSUE THREAD

**Issue by AmirTugi** [angular/material2#1992]
#### Bug, feature request, or proposal:
According to the [material design spec](https://material.google.com/motion/choreography.html#choreography-creation) a staggering animation should be applied.
Would be nice to have built-in and not have to implement by ourselves

#### What is the current behavior?
Currently, there are no animations on creation of grid/ list items.

**Comment by jelbourn** [comment]
The page you linked is more talking about general patterns (dos and dont's), not specifically requirements. It's also talking about creating new surfaces (floating panels). You should be able to use the animation features built into core to animate list items in a manner that suits your own app.
