### ISSUE TITLE
MdDialog error in Angular-CLI

### ISSUE THREAD

**Issue by whizkidwwe1217** [angular/material2#1993]
#### Bug, feature request, or proposal:

I'm trying to implement the MdDialog in Angular-CLI but I got this error:

```
EXCEPTION: Uncaught (in promise): Error: No provider for MdDialog!
Error: No provider for MdDialog!
    at NoProviderError.BaseError [as constructor] 
```

#### What is the expected behavior?

Should not throw the error above. Should be able to show dialog.

#### What is the current behavior?

Produces the error mentioned above.

#### What are the steps to reproduce?

Just follow the samples for dialog.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

#### What is the use-case or motivation for changing an existing behavior?

Creating an MdDialog is cumbersome. It will be much better if you could just call a static function for showing the dialog and just pass in some config to set the template and callbacks.

**Comment by joejordanbrown** [comment]
@whizkidwwe1217 

Is your configuration like the following:

```
import { MaterialModule } from '@angular/material';
import { DialogComponent } from './dialogl';

@NgModule({
  imports: [ 
    BrowserModule, 
    MaterialModule.forRoot()
  ],
  declarations: [ AppComponent],
  entryComponents: [ DialogComponent ],
  bootstrap: [ AppComponent ]
})
export class AppModule {}
```

**Comment by jelbourn** [comment]
You need to include either `MaterialModule.forRoot()` or `MdDialogModule.forRoot()` in your root application module.

**Comment by manatico4** [comment]
**forRoot** is deprecated: [https://github.com/angular/material2/issues/3320](url)

**Comment by priyaragavan** [comment]
[](https://github.com/angular/material2/issues/3320) - Not Found.
