### ISSUE TITLE
npm install -g @angular/material not working in powershell windows 7 but works perfectly with cmd

### ISSUE THREAD

**Issue by vijay2work4soddisfare** [angular/material2#1996]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by asaph26** [comment]
@vijay2work4soddisfare @angular/material needs to be installed on a per project basis and not globally. 

You could go to your project directory and do npm install @angular/material --save and it should work

**Comment by jelbourn** [comment]
You may need to escape the `@`. This is a general issue with npm scoped packages and not related to material.
