### ISSUE TITLE
Angular 2 Checkbox in RTL issue [Chrome]

### ISSUE THREAD

**Issue by theunreal** [angular/material2#2000]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
One checkbox - Normal checkbox appearance

#### What is the current behavior?
Checkboxes appear doubled, Image:

![image](https://cloud.githubusercontent.com/assets/6171883/20650586/a14bd6c4-b4da-11e6-8861-96581ff69ea9.png)

After clicking the checkbox, it returns to normal.

This bug appears in Google Chrome. In firefox the view is fine.

#### What are the steps to reproduce?
Putting checkboxes in an RTL angular 2 app

#### What is the use-case or motivation for changing an existing behavior?
Checkboxes work right in RTL

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.1.2
Material 10
Google Chrome

**Tested on firefox:** Works

**Comment by crisbeto** [comment]
How are you setting the RTL direction? Using the CSS `direction` or the HTML attribute? Currently it should work with the attribute.

**Comment by theunreal** [comment]
I'm using `<html dir="rtl">`

**Comment by theunreal** [comment]
I added a `clear:both` below this and the problem fixed. Strange thing..

**Comment by crisbeto** [comment]
That sounds weird. The only way I got it to break yesterday was with the CSS property, I'll check if the `clear` also fixes it in that case.

**Comment by crisbeto** [comment]
Now I'm having a hard time reproducing it at all, this is really odd.

**Comment by theunreal** [comment]
Yeah, it shows again after using `clear:both`. I think it's releated to the content after the checkboxes, but I have no clue why it occurs and when.
