### ISSUE TITLE
[md-checkbox] checked and indeterminate state problem.

### ISSUE THREAD

**Issue by joejordanbrown** [angular/material2#2004]
#### Bug
I believe this is a bug.

#### What is the expected behavior?
If both checked and indeterminate are true and then checked is set to false it should show indeterminate.

#### What is the current behavior?
If both checked and indeterminate are true and then checked is set to false it should show indeterminate but instead, it shows unchecked.

#### What are the steps to reproduce?
If you use the toggles you will see the state of the checkbox not being correct against the set values.
https://embed.plnkr.co/v7euQHvzVsAFHNcpsEFo

#### Which versions of Angular, Material, OS, browsers are affected?
Latest

**Comment by jelbourn** [comment]
@tinayuangao can you compare this to the native checkbox behavior?

**Comment by joejordanbrown** [comment]
@jelbourn I've updated the plunker to compare both to make it easier for you to see what's different.

**Comment by jelbourn** [comment]
That does look like a bug, then.

**Comment by tinayuangao** [comment]
Checked the native checkbox behavior in the plunker, and not sure whether we should follow it:

When `checked = true, indeterminate = true`, the box shows ` - ` if the values are set programmatically, while it shows `✓` if set `checked` to `true` by clicking on the checkbox.

When `checked = false, indeterminate = true`, the box shows ` - ` if the values are set programmatically, while it shows `   ` if set `checked` to `false` by clicking on the checkbox.

**Comment by tinayuangao** [comment]
@jelbourn We did this on purpose. Should we change the current behavior? 

See checkbox comment on indeterminate: 

>   Whether the checkbox is indeterminate. This is also known as "mixed" mode and can be used to
   represent a checkbox with three states, e.g. a checkbox that represents a nested list of
    checkable items. Note that whenever `checked` is set, indeterminate is immediately set to
   false. This differs from the web platform in that indeterminate state on native
    checkboxes is only remove when the user manually checks the checkbox (rather than setting the
    `checked` property programmatically). However, we feel that this behavior is more accommodating
    to the way consumers would envision using this component.

**Comment by joejordanbrown** [comment]
@tinayuangao if you're saying that when the `md-checkbox` `checked` value is set to `true` that the indeterminate is set to `false `that's not correct please check the video https://youtu.be/1WA7fpRgqqU 

I agree with the comments, especially when all the browsers seem to have a different idea on how the native indeterminate checkbox should work. just that's not how it's currently working

Some pictures may also help.

When both are true
![image](https://cloud.githubusercontent.com/assets/10200431/20820645/b183c7d8-b834-11e6-9d7b-ba929f5c6770.png)

When both are true and then checked is set to false
![image](https://cloud.githubusercontent.com/assets/10200431/20820631/8971b4c6-b834-11e6-9365-77510c444a96.png)

When both are false and indeterminate is set to true
![image](https://cloud.githubusercontent.com/assets/10200431/20820692/fe1364be-b834-11e6-8315-478471c1a7c8.png)


Now I'm sure you can see the problem?

**Comment by tinayuangao** [comment]
@joejordanbrown 

> When both are true
![image](https://cloud.githubusercontent.com/assets/20677343/21036808/7605aa12-be03-11e6-936a-78c0c6246252.png)

The `indeterminate` inside MdCheckbox is set to false when setting `checked = true`. However, it will not emit an event to update the `indeterminate` outside MdCheckbox. Similar thing happens when you set `checked = false` in the second case. 

One way to solve this issue is to emit event when `indeterminate` changed.
