### ISSUE TITLE
Unable to set styles on md-list-item

### ISSUE THREAD

**Issue by johnrbaur** [angular/material2#2012]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Adding a style or class to an anchor tag with the md-list-item directive should modify the style of the list item.

#### What is the current behavior?
The style/class is applied to the anchor tag, but not to the inner div elements created by the directive. The applied style is not visible on the page.

#### What are the steps to reproduce?

http://plnkr.co/edit/B0LLmc7We95gMAuySZbv?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Adding style to indicate the currently selected item

#### Which versions of Angular, Material, OS, browsers are affected?
All?

**Comment by crisbeto** [comment]
@johnrbaur That's because the `md-list-item` has collapsed. Forwarding the styles to the inner elements isn't necessary, you just need to add a `display: block`. I've put in a PR that should fix it on Material's side.
