### ISSUE TITLE
Create automatically updated Plunker templates for master and latest release

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#2015]
We should have two Plunker templates that are automatically created:
* `master`, which should be done as part of Travis run
* `latest-release` which should be done as part of the release script (only when the tag is `latest`, since we publish a decent number of experimental versions)

**Comment by jelbourn** [comment]
@DevVersion do you want to work on this?

**Comment by DevVersion** [comment]
@jelbourn Yeah - I already had a PR which did something similar (See #1222)

I personally think that this issue can be solved better by:
- Having nightly builds which can be used by Plunker (Github or NPM) - `master`
- Using `unpkg` for the `@latest` version (currently doing that and it works perfect) - `latest release` 

So I think it would be just necessary to work on the nightly builds (#577)

**Comment by jelbourn** [comment]
Rather than nightly, per-commit builds would give us better granularity. Ideally I'd like to do that the same way that `angular/angular` does.

**Comment by DevVersion** [comment]
@jelbourn Oh yeah, that would be more effective. We already had an issue for it https://github.com/angular/material2/issues/928. 

From what I remember @hansl wanted to take care of it.

**Comment by jelbourn** [comment]
@DevVersion Up for grabs now if you want to do it

**Comment by DevVersion** [comment]
@jelbourn Yeah would be interesting. I will ping you on Slack about it.

**Comment by DevVersion** [comment]
Updates for the Plunker builds:
* The template plunker already runs with `material2-builds`@master
* Our docs (material.angular.io) always serve the latest release.

This should fulfill our requirements on this issue.
