### ISSUE TITLE
Clicking many times on md-button displays the scrollbar - comeback

### ISSUE THREAD

**Issue by karolmie1** [angular/material2#2018]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Not showing the scrollbar after many clicks 

#### What is the current behavior?
When clicking a md-button many times, after some clicks the scrollbar in the browser shows. This does not happen for a normal button

#### What are the steps to reproduce?

Same as in #1392 

#### Which versions of Angular, Material, OS, browsers are affected?

Angular version 2.2.3
Material version: 2.0.0-alpha.10
OS: Manjaro Linux
Error shows on firefox

#### Is there anything else we should know?

I've read this issue: #1392 
Problem should stop after importing prebuild style, for example: 
@import '~@angular/material/core/theming/prebuilt/deeppurple-amber.css'

Problem is it still exists.
I managed to fix it by also importing: 
https://unpkg.com/@angular2-material/core/style/core.css" rel="stylesheet"
in head of index.html, as was described in other issues.

Should not prebuild themes have all required information? Also can  this suplementary core.css file be included in node_modules, so it can be compiled with the rest of the stuff (and so it would be in the proper version)?

in the end I just used [disableRipple]="true"

Maybe this [disableRipple]="true" workaround should be described in readme until the problem won't be fixed? It took me a reaaaly long time to figure out what was wrong, and lot's of people is experiencing this issue.

**Comment by fxck** [comment]
are you 100% that 

```
@import '~@angular/material/core/theming/prebuilt/deeppurple-amber.css'
```

actually imported those styles? check the generated file in your bundle.. the way you import from node modules differ depending on your setup

**Comment by karolmie1** [comment]
@fxck All the colors and styles changed, so I assume everything is loaded correctly. 
md-menu has same problem, but disableRipple doesn't help and window won't pop up.

I think I'll wait for at least beta, because currently material is really pretty, but unusable. 

If you wan't to make sure that the styles are imported you can take a look at my attempts with angular2 here: https://bitbucket.org/kmierzej/fragaria-webapp/src/345aaa136aae0565994932b9d2ec6ebfb4cb4b02/?at=material2

You run it with yarn start, branch material2

**Comment by fxck** [comment]
https://bitbucket.org/kmierzej/fragaria-webapp/src/345aaa136aae0565994932b9d2ec6ebfb4cb4b02/src/app/app.component.ts?at=material2&fileviewer=file-view-default#app.component.ts-6 try adding 

```
encapsulation: ViewEncapsulation.None
```

here

**Comment by karolmie1** [comment]
@fxck that would explain a lot of things. I will check it out asap (and hopefully close in a minute). Thanks for help!

**Comment by karolmie1** [comment]
@fxck So it turned out only my less than medicore knowledge of angular prevented me from enjoying material2 in the fullest. I take back that unstability claim for know. Yet again many thanks!
