### ISSUE TITLE
Duration is missing from MdSnackBar

### ISSUE THREAD

**Issue by michaeljota** [angular/material2#2020]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

According to docs, there should be a `duration` property in `MdSnackBarConfig` type

#### What is the current behavior?

There is not a `duration` property in `MdSnackBarConfig`

Throws:
```cmd
Argument of type '{ duration: number; }' is not assignable to parameter of type 'MdSnackBarConfig'.
Object literal may only specify known properties, and 'duration' does not exist in type 'MdSnackBarConfig'.
``` 

#### What are the steps to reproduce?

Try to add a `duration` property to the configuration object when open a SnackBar. 

#### Which versions of Angular, Material, OS, browsers are affected?

Angular: 2.2.1
Material: alpha-10
OS: Windows 10 AU

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/material2/blob/master/src/lib/snack-bar/snack-bar-config.ts#L18

**Comment by michaeljota** [comment]
It is in source, but...

![duration](https://cloud.githubusercontent.com/assets/10507776/20713013/04f794f4-b61d-11e6-90fe-267f88f346b2.png)

![duration_2](https://cloud.githubusercontent.com/assets/10507776/20713017/07d4a8ce-b61d-11e6-8b6f-28455e8bb8f5.png)

If the property exist, but it is not released yet, it should commented out of the docs until sees released. If it was released in alpha.10, then it's weird. :/

**Comment by DzmitryShylovich** [comment]
I think it either hasn't been released yet or u have incorrect version.
There're several experimental releases http://prntscr.com/dd7u88
try them out.

**Comment by crisbeto** [comment]
It's definitely in master, although you should keep in mind that you can't pass in a config object, you need to set it as a property individually, e.g.:

```js
let config = new MdSnackBarConfig();
config.duration = 1000;
```

It would probably make sense to include the ability to pass an object since we did something similar for the dialog already.

**Comment by jelbourn** [comment]
This will be released in alpha.11

**Comment by michaeljota** [comment]
Thanks you all. :)

**Comment by valdestrijus** [comment]
Temporary workaround:
```
import { Injectable } from '@angular/core';
import { MdSnackBarRef, MdSnackBar } from '@angular/material';

@Injectable()
export class AlertsService {
	public snackBarRef: MdSnackBarRef<any>;

	constructor(
		private snackBar: MdSnackBar
	) { }

	showMsg(msg: string, haveAction: boolean, actionLabel: string, duration: number) {
		let config: any = {}; // <-- https://github.com/angular/material2/issues/2020 TODO: After alpha.11 use MdSnackBarConfig
		config.duration = (duration || 1) * 1000;

		this.snackBarRef = this.snackBar.open(msg, haveAction && actionLabel, {});

		setTimeout(() => {
			this.snackBarRef.dismiss();
		}, config.duration);
	}
}
```
