### ISSUE TITLE
Slider wrong coloring [RTL]

### ISSUE THREAD

**Issue by theunreal** [angular/material2#2022]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Spinner fill color correctly

#### What is the current behavior?
Spinner empty - Correct: 
![image](https://cloud.githubusercontent.com/assets/6171883/20715542/3663b6d6-b658-11e6-8138-b4b775188759.png)
Spinner full - Correct:
![image](https://cloud.githubusercontent.com/assets/6171883/20715554/3f329066-b658-11e6-9f5c-3ef787e6f415.png)
Spinner with some value - incorrect
![image](https://cloud.githubusercontent.com/assets/6171883/20715568/4c94c116-b658-11e6-8268-70f5be1fb2fd.png)
![image](https://cloud.githubusercontent.com/assets/6171883/20715582/52decc10-b658-11e6-9ba7-ff7adcf1f9f4.png)

#### What are the steps to reproduce?

Put a spinner in html dir="rtl" angular 2 app

#### What is the use-case or motivation for changing an existing behavior?
Fixing RTL issue using the spinner module

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.1.2
Material 10
Chrome, Edge

**Comment by JanStureNielsen** [comment]
@theunreal  - with RTL are the empty and full also incorrect? It seems like the empty spinner be at the righ-most position and the full spinner at the left-most position...

**Comment by crisbeto** [comment]
I couldn't reproduce this locally, although the dragging gesture doesn't account for RTL. That's pending an RTL service, though.

**Comment by jelbourn** [comment]
@mmalerba does your latest PR fix this?

**Comment by mmalerba** [comment]
yes, I believe #1794 will fix this
