### ISSUE TITLE
[Proposal][Docs] Update docs how to import MdDialogModule and others

### ISSUE THREAD

**Issue by luchillo17** [angular/material2#2023]
#### Bug, feature request, or proposal:
The MdDialogModule and other modules present an issue when importing, you expect us to import the full material module, i'm only importing 3 modules, i didn't see anywhere in the docs an explanation regards importing individual modules, like the dialog one needs `forRoot()` call in the import as:

```
@NgModule({
  imports: [
    MdDialogModule.forRoot(),
  ], ...
})
```
#### What is the expected behavior?
The docs should state the correct way of importing specific modules, seems a few of them like `MdDialogModule` needs to be imported with `forRoot()` function (is it a factory?), while some other like the button, card, list... can be imported without that function call.

#### What is the current behavior?
The docs don't state how to correctly import individual modules.

#### What is the use-case or motivation for changing an existing behavior?
Avoid confusion, i had to take a look to the main module source to understand and fix my issues.

#### Which versions of Angular, Material, OS, browsers are affected?
Doesn't matter, it's about the docs.

#### Is there anything else we should know?
Would like to know which ones does need the `forRoot()` function call.

**Comment by Daeluse** [comment]
The rule of thumb would be to import them all with forRoot() since they all are exported as a module with providers and have the method available, though in some cases it is empty. This prevents you from having to sniff out issues down the road if they add a provider to a module which you were not already calling the forRoot method on.

**Comment by Luchillo** [comment]
Ok so where's written that rule of thumb? i haven't touched Material until yesterday, for the time being i was using PrimeNg, so this is the first time aside the angular router that i see that `forRoot()` function.

**Comment by jelbourn** [comment]
This is obsolete now that `forRoot` has been made unnecessary.
