### ISSUE TITLE
Question about differences in package installations (NPM package vs from github)

### ISSUE THREAD

**Issue by cielo** [angular/material2#2027]
To use one of the latest feature from recent commits that is not part of released versions, I updated my package.json like below.

Old: `"@angular/material": "2.0.0-alpha.10",`

New: `"@angular/material": "angular/material2",`

so that my app will use the latest commits from 'angular/material2' github commits.

However, when I change package version like above, and install directly from github, installation directory of material2 is different.  

Example old: 'node_modules/@angular/material/snack-bar/snack-bar-config.js'
Example new: 'node_modules/material2/src/lib/snack-bar/snack-bar-config.ts'

Is there a way which I can install material2 package with the latest commits, similar to how released version is structured? Do I need to compile typescript files?

**Comment by fxck** [comment]
That's not how it works. There are no per commit releases and there is no github repo with builds of master. 

This is tracked via https://github.com/angular/material2/issues/577

**Comment by cielo** [comment]
I see. Typescript and NPM are new to me so I wasn't sure how they worked. I will subscribe to that issue.
