### ISSUE TITLE
How do I make an anchor that looks like a button?

### ISSUE THREAD

**Issue by colemickens** [angular/material2#2028]
From: https://github.com/angular/material2/tree/cde9ab38c04a7ad0248c71b295d70c5470faad6f/src/lib/button

>Users should employ a button element (`<button>`) when clicking triggers some action in the current view without navigating. An anchor element (`<a>`) should be used when clicking navigates the user to another URL. Depending on which element is used, the component will either be an instance of MdButton or MdAnchor. Visually, the two are identical.

So, what syntax do I use to get an anchor tag that looks like an `md-button`?

**Comment by colemickens** [comment]
Answer:

`<a md-button href="...">Some text</a>`

**Comment by BamiGorengo** [comment]
This dont work anymore...
