### ISSUE TITLE
Will pagination be available in near future ?

### ISSUE THREAD

**Issue by codejith** [angular/material2#2029]
#### Bug, feature request, or proposal:
Will  pagination be available in near future ?

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by fxck** [comment]
Nope https://github.com/angular/material2/issues/1572#issuecomment-255802683 

use https://ng-bootstrap.github.io/#/components/pagination

**Comment by jelbourn** [comment]
We will likely have something similar as part of data-table (#581), but nothing in the short-term. Follow #581 for updates.
