### ISSUE TITLE
test: karma should use sourcemaps.

### ISSUE THREAD

**Issue by DevVersion** [angular/material2#203]
I don't know if this is possible, but I will file an issue to keep track on it.

At the moment, we always retrieve failure messages from the compiled javascript code.
![image](https://cloud.githubusercontent.com/assets/4987015/13885707/01d86648-ed34-11e5-98f5-4c7ea919bbba.png)

This complicates debugging.

**Comment by jelbourn** [comment]
@hansl probably also relates to the cli

**Comment by DevVersion** [comment]
@jelbourn No, we are just not initializing the sourcemaps in the karma files.

See [the karma source](https://github.com/karma-runner/karma/commit/70e4abd9b8db6b05de557ca6e9204339a21be06b#diff-9c2c5321be7865c99a5ebe09be07d08fR86)

I'm trying to submit a PR, if encouraged.

**Comment by jelbourn** [comment]
@DevVersion if you've got a fix in mind go for it.

**Comment by DevVersion** [comment]
I'm still trying to get it running. 

I'm failing with the sourcemaps, because it seems like there are not correct in the `dist` folder.
```js
//# sourceMappingURL=../../../../components/button/button.js.map
```

Do you recall why these aren't correct?

**Comment by DevVersion** [comment]
@jelbourn @hansl Yes, it seems like the CI is applying some wrong / relative sourcemap paths to the distribution. Sorry I was a bit hasty.

**Comment by jelbourn** [comment]
Tracking this on the CLI
https://github.com/angular/angular-cli/issues/456
