### ISSUE TITLE
Opened md-sidenav has the class 'md-sidenav-opening' after page load

### ISSUE THREAD

**Issue by sunderw** [angular/material2#2032]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
An opened sidenav should have the class _md-sidenav-opened_ when the page is loaded with the sidenav opened.

#### What is the current behavior?
The sidenav has the class _md-sidenav-opening_, but toggling it once sets the correct class.

#### What are the steps to reproduce?
Have a page with a sidenav opened at first. [Plunker link](http://plnkr.co/edit/a5S5K00hy5tlwG1xg394?p=preview)

#### Which versions of Angular, Material, OS, browsers are affected?
Tried with **Angular 2.1** and both **Material 0.9-3** and **Material 0.10**.

**Comment by mmalerba** [comment]
In your plunker demo I see the correct classes as soon as it loads `class="md-sidenav-opened md-sidenav-side"`.

**Comment by sunderw** [comment]
The plunker doesn't work anymore. I just tried with the latest material / angular and indeed, it is now working.
Thanks to the material team !
