### ISSUE TITLE
md-input floating placeholder misaligned in RTL

### ISSUE THREAD

**Issue by AsherBarak** [angular/material2#2034]
#### Bug, feature request, or proposal:
feature request

#### What is the use-case or motivation for changing an existing behavior?
Support for right to left languages, display direction and flow

#### Which versions of Angular, Material, OS, browsers are affected?
All

**Comment by crisbeto** [comment]
Most of the components should already have support for RTL. Have you run into any issues?

**Comment by AsherBarak** [comment]
Check out his screenshot
![image](https://cloud.githubusercontent.com/assets/6647171/20758139/8d489484-b721-11e6-85f8-5f90692b8503.png)

**Comment by jelbourn** [comment]
@mmalerba we should apply fix to new md-input as well

**Comment by mmalerba** [comment]
looks like it should just work since i'm relying on the same css
