### ISSUE TITLE
Angular Material 2 Dialog Lazy Injection Issue

### ISSUE THREAD

**Issue by manuelmoyaroldan** [angular/material2#2036]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Lazy loaded component open dialog.

#### What is the current behavior?
Lazy loaded component does not load lazy loaded component on dialog. I get error.

#### What are the steps to reproduce?

http://embed.plnkr.co/eBQNsfV7jTys4THqfT77/

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.2.3, Material 2.0.0-alpha.10

**Comment by manuelmoyaroldan** [comment]
Sorry.. It works now.

**Comment by jlutz777** [comment]
@manuelmoyaroldan What was the solution for this? I'm running into something really similar where as soon as I moved to a lazy loaded module, I cannot use a dialog.
