### ISSUE TITLE
gutterSize not displaying any space between grid tiles.

### ISSUE THREAD

**Issue by httpNick** [angular/material2#2039]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
have space between grid-list tiles

#### What is the current behavior?

No space between tiles.

#### What are the steps to reproduce?

This plunk shows the issue: 

http://plnkr.co/edit/lm8zgipSsSAIPimPZSGW

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, browsers are affected?

"@angular/material": "^2.0.0-alpha.10"

angular v2.0.2

Firefox and Chrome

**Comment by jelbourn** [comment]
@crisbeto could you take a look at this?

**Comment by crisbeto** [comment]
The grid list works fine. The demo doesn't have space between the tiles because the background is applied to the wrapper element. [Here's a forked Plunkr that only moves the inline styles.](http://plnkr.co/edit/5ew0MWp40npP3Hhi2LGe?p=preview)
