### ISSUE TITLE
[md-button] will not call click event when nested inside [md-card]

### ISSUE THREAD

**Issue by dzrust** [angular/material2#2040]
#### Bug:
While a [md-button] is nested inside a [md-card] either [md-card] or nested in [md-card-actions] the (click) event is not called.

#### What is the expected behavior?
The click event should fire.

#### What is the current behavior?
The click event does not fire.

#### What are the steps to reproduce?
Place a button with a (click)="func()" attribute inside a [md-card] element and it will not call the event.
[Plunker example](http://plnkr.co/edit/uArBcDKpwS2nNF2R4U95?p=preview)

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2 - 2.2.0
Material - 2.0.0-alpha.10
OS - windows 10
Chrome

#### Update 12/1/2016
I was messing around and also found that if you move the (click)="func()" from <md-card> to <md-card-title> the button (click)="func()" will work however the (click)="func()" on the <md-card-title> will no longer fire off.

**Comment by jelbourn** [comment]
@crisbeto I took a quick look at the Plunker and something seems amiss, but I'm not sure where the problem lies.

**Comment by crisbeto** [comment]
It doesn't look like this is an issue. The click event isn't being called, because both the `md-button` and the `md-card` have a click handler. When you click the button, the click event propagates up to the card which then resets the value. If you look at the HTML:

```html
<md-card (click)="setTest('Home')"> <!-- Click event propagates to here, now the value is reset back to 'Home' -->
  <!-- some content -->
  <md-card-actions *ngIf="test === 'Home'">
    <button md-button (click)="setTest('NA');">THIS WONT CALL CLICK EVENT</button> <!-- This will be called first when click. The test value is now at 'NA'-->
  </md-card-actions>
</md-card>
```

@dzrust, you can avoid this by either removing the click event from the card or stopping the event propagation:

```html
<md-card (click)="setTest('Home')">
  <!-- some content -->
  <md-card-actions *ngIf="test === 'Home'">
    <button md-button (click)="setTest('NA'); $event.stopPropagation()">This works now</button>
  </md-card-actions>
</md-card>
```
