### ISSUE TITLE
Any plan to provide a file uploader component

### ISSUE THREAD

**Issue by alvachien** [angular/material2#2041]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Select and upload the file to a specified backend URL.
It shall provide the capability to restrict the file extension, size or other special requirements.
It will be great if combining with the progress bar.

#### What is the current behavior?
There is no such component.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Select file and upload is quite a common behavior in mobile world and in the web app.

#### Which versions of Angular, Material, OS, browsers are affected?
All.

**Comment by mtrdp642** [comment]
[Covalent](https://teradata.github.io/covalent/#/components/file-upload) has a nice file upload that has a material look to it and [PrimeNG](http://www.primefaces.org/primeng/#/fileupload) has another one you can use. [Here's another one](http://valor-software.com/ng2-file-upload/) that is better for a series of downloads and file queuing.

#1347 References this question as well.

**Comment by jelbourn** [comment]
We may explore this in the future but it isn't currently on the roadmap.

**Comment by merlosy** [comment]
Hi,
If you really need one: I made a custom one (Angular 4.3.s and material look)
https://gist.github.com/merlosy/ab33dd7edaacfd92d6c9a5daea0a1240
Feedback is great !
