### ISSUE TITLE
MdDialog Content Overflow

### ISSUE THREAD

**Issue by manuelmoyaroldan** [angular/material2#2042]
#### Bug, feature request, or proposal:
When the content of a MdDialog overflows the height of the browser, the content is hidden.

#### What is the expected behavior?
Scroll the content of MdDialog

#### What is the current behavior?
The content overflowed is hidden.

#### What are the steps to reproduce?

http://plnkr.co/edit/9S2ZUzQTmquS4sjmjuoO?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Last/Last Material

**Comment by crisbeto** [comment]
I had some plans on addressing this, but it depends on https://github.com/angular/material2/pull/1962

**Comment by fxck** [comment]
probably part of https://github.com/angular/material2/issues/1624 as md-dialog-content will likely have max-height and overflow auto

**Comment by crisbeto** [comment]
That one might be a little tricky @fxck. AFAIK we don't have the ability to project elements to multiple slots, yet.

**Comment by codelovesme** [comment]
I have the same issue.
"@angular/material": "^2.0.0-beta.6",
"@angular/cli": "^1.2.0"
