### ISSUE TITLE
md-checkbox not behaving correctly (not unchecking on first click)

### ISSUE THREAD

**Issue by rotemx** [angular/material2#2043]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When using native checkboxes with [Angular2-Data-Table](https://github.com/swimlane/angular2-data-table) I can toggle columns on or off the table. 
When trying to implement md-checkbox the first click doesn't work - the checkbox remains checked. 
After the first click the checked value is opposite to the model, i.e. opposite to the native checkboxes.

I tried many ways to fix this but without luck. this seems to be a bug in md-checkbox.

see plunker : 
https://plnkr.co/edit/HGUjy5

#### What is the current behavior?
The first click should toggle the checkbox correctly.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://plnkr.co/edit/HGUjy5
#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.1.2
latest Angular 2 Material

**Comment by jelbourn** [comment]
@tinayuangao can you reproduce this?

**Comment by tinayuangao** [comment]
This is not a bug in `md-checkbox`. Your `isChecked(col)` needs to return a boolean to make it work - now it returns `{name: ColName}`.

The correct `isChecked(col)` function should be `isColChecked(col:any) {
    return this.columns.find(c => {
      return c.name === col.name;
    }) != undefined;
  }`

**Comment by tinayuangao** [comment]
You also need to change `(click)="toggle(col)"` in template to `(change)=toggle(col)`.  The `(change)` event in MdCheckbox will toggle the checkbox again.
