### ISSUE TITLE
when will alpha .11 be coming?  

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#2045]
#### Bug, feature request, or proposal:
please hurry i don't want to use ng prime

**Comment by xtianus79** [comment]
lol no love @jelbourn ?

**Comment by jelbourn** [comment]
In general, any issues of the form "when will XXX happen" are just auto-closed. GitHub issues are for bug reports and feature requests.

**Comment by xtianus79** [comment]
@jelbourn so what is the best venue for such questions?

**Comment by jelbourn** [comment]
I try to answer short questions on twitter

**Comment by xtianus79** [comment]
@jelbourn thank you.  I will ask it on there.  I appreciate you guys
