### ISSUE TITLE
Problem with progress bar? Or built on purpose?

### ISSUE THREAD

**Issue by ayumiknight** [angular/material2#2053]
#### Bug, feature request, or proposal:
I'm using the Indeterminate progress bar for indicating loading event.
However, when the loading fails and pops an alert, the progress bar act weird until the alert box goes away.
Basically, you can see that progress bar's length is changing but the position is frozen.

#### What is the expected behavior?
Progress bar should shift through the screen when alert popup is on.

#### What is the current behavior?
Progress bar's position is frozen, however the length is still changing

#### What are the steps to reproduce?
Add a indeterminate progress bar, and a button to trigger alert box.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by jelbourn** [comment]
using `alert`, `confirm`, and `prompt` block the UI thread from doing anything until the pop-up is dismissed. There's really nothing we _can_ do to avoid this; it's the nature of the browser.
