### ISSUE TITLE
Uncaught Error: Unexpected value 'undefined' imported by the module 'MdInputModule'

### ISSUE THREAD

**Issue by divanvb** [angular/material2#2057]
#### Bug, feature request, or proposal:
Getting this error when launching my app and is preventing the app from running

#### What is the expected behavior?
Not throwing this error

#### What is the current behavior?
Not launching my application

#### What are the steps to reproduce?
Tried installing material2 to my fountain-webapp project and then got the error

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.x.x, material 2.0.0-alpha.10, windows 10, chrome

#### Is there anything else we should know?
Not really.

**Comment by fxck** [comment]
create a plunker reproduction

**Comment by jelbourn** [comment]
@divanvb Please provide more reproduction information. What module loader are you using? What does your app's NgModule look like?

**Comment by jelbourn** [comment]
Closing this for lack of information. Feel free to file a new issue if you have provide more specifics.
