### ISSUE TITLE
Probleme integrate md-subheader in md-list

### ISSUE THREAD

**Issue by Symfomany** [angular/material2#2079]
#### Bug, feature request, or proposal:
      <md-subheader class="md-no-sticky">3 line item</md-subheader>
Not available for md-list?

#### What is the expected behavior?

      <md-subheader class="md-no-sticky">3 line item</md-subheader>

#### What is the current behavior?
No integration for md-subheader

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by EladBezalel** [comment]
Please reproduce the issue in Plunker so we can investigate further.

**Comment by jelbourn** [comment]
@Symfomany It's not really clear what you're reporting / asking for. Feel free to open a new issue with more specifics.
