### ISSUE TITLE
slider does not slide on iPhone

### ISSUE THREAD

**Issue by mbateman66** [angular/material2#2083]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Slider should work on the iPhone like it does on other platforms.

#### What is the current behavior?
Slider does not slide on iPhone. You can touch in a new location, and it will send the new value, but touching the slider circle does not allow it to be moved.

#### Which versions of Angular, Material, OS, browsers are affected?
IOS 10.1.1, both Safari and Chrome

NPM:
  "dependencies": {
    "@angular/common": "^2.1.0",
    "@angular/compiler": "^2.1.0",
    "@angular/core": "^2.1.0",
    "@angular/forms": "^2.1.0",
    "@angular/http": "^2.1.0",
    "@angular/material": "^2.0.0-alpha.10",
    "@angular/platform-browser": "^2.1.0",
    "@angular/platform-browser-dynamic": "^2.1.0",
    "@angular/router": "3.0.0",
    "@types/chai": "^3.4.34",
    "@types/chartist": "^0.9.33",
    "admin-lte": "^2.3.8",
    "angular2-chartist": "^0.10.1",
    "angular2-jwt": "^0.1.24",
    "angular2-toaster": "^1.0.2",
    "angularfire2": "^2.0.0-beta.6",
    "auth0-lock": "^10.4.0",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.4.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "ionicons": "^3.0.0",
    "jquery": "^3.1.1",
    "ng2-bootstrap": "^1.1.5",
    "ng2-charts": "^1.4.1",
    "rxjs": "^5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },

**Comment by SamiAl90** [comment]
did you include hammerjs in your polyfills or main file?

`import 'hammerjs';`

**Comment by mbateman66** [comment]
Yes, I have the following line in my src/app/app.module.ts:
import 'hammerjs';

I do not have the types entry in the tsconfig.json, since adding that breaks the compile for other modules. But there is an entry for typeRoots that includes the node_modules/@types directory where the hammerjs types are located.

**Comment by ayazhussein** [comment]
I got the same problem, trying to slide on mobile doesn't work correctly, when I try to slide, it shows the tooltip and then stays stuck, unless I tap somewhere else and then I try again, after that it works.

**Comment by mbateman66** [comment]
For me, it will never slide, even after a tap.
