### ISSUE TITLE
Toolbar height should adjust based on @media

### ISSUE THREAD

**Issue by code-tree** [angular/material2#2085]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Toolbar height [follows spec](https://material.google.com/layout/structure.html#structure-app-bar)

> Mobile Landscape: 48dp
> Mobile Portrait: 56dp
> Tablet/Desktop: 64dp

#### What is the current behavior?
Toolbar height is static at 64px.

#### What are the steps to reproduce?
n/a

#### What is the use-case or motivation for changing an existing behavior?
Follow spec

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0-alpha.10

#### Is there anything else we should know?
This should probably be implemented using CSS @media?

**Comment by DevVersion** [comment]
@jelbourn Should we implement that? From what I remember we decided to let the user take care of it?

**Comment by code-tree** [comment]
I'm fine with that, as I've already made my own implementation

**Comment by jelbourn** [comment]
@DevVersion I'd be okay with making it responsive per the spec.

**Comment by DevVersion** [comment]
@jelbourn I'd rather make it optional like having an attribute like `md-responsive`, because I think it would confuse users.

**Comment by jelbourn** [comment]
Being responsive by default seems good to me, though, since users can always explicitly set the height to override the default behavior.

**Comment by DevVersion** [comment]
Ah yeah makes sense. I'm going to create a PR to change it.
