### ISSUE TITLE
Passing local data to md dialog???

### ISSUE THREAD

**Issue by dreweird** [angular/material2#2086]
----in my html code---
` <td *ngIf="item.clickable=='yes'" (click)="openDialog(item)">{{item.kilo[0] | number: '1.2-2'}}</td>`

---in my component code---

```
 openDialog(item) {
    let dialogRef = this._dialog.open(DialogContent);

    dialogRef.afterClosed().subscribe(result => {
      this.lastDialogResult = result;
    })
  }
```
How to show the local variables in the md-dialog template???? I want to display the value of item
```
@Component({
  template: `
    <p>This is a dialog</p>
    <p>
    {{item}}
      <label>
        This is a text box inside of a dialog.
        <input #dialogInput>
      </label>
    </p>
    <p> <button md-button (click)="dialogRef.close(dialogInput.value)">CLOSE</button> </p>
  `,
})
export class DialogContent {
  constructor(@Optional() public dialogRef: MdDialogRef<DialogContent>) { }
}
```

**Comment by crisbeto** [comment]
[Try the suggestion from here.](https://github.com/angular/material2/issues/1377#issuecomment-250632661) We should probably document this option a little bit better.
