### ISSUE TITLE
Infinite horizontal slider (carousel-like)

### ISSUE THREAD

**Issue by xikky** [angular/material2#2087]
I've been dwelling with this for more than two full days and I cannot make it work properly. Something which looks trivial but truth is it's tricky, also something that is commonly used in web applications.

The idea is to have a carousel-like slider, always sliding to one side, with element boxes being added on interval on one side, and removed from the other side; so as to keep populating the slider with new element boxes, and removing those that are no longer in view.

A good application example of this would be a feed of casino slot winners. The frontend makes request to get winners every say 10 minutes, the result is pushed in an array, which is looped in the DOM to create such element boxes, placed next to each other horizontally. Angular animation takes care to slide each one to the left, showing new once from the right.

The issue here is that, since I'm translating horizontally each element box by -100%, the new element boxes added are not placed right next to where the other elements are slided, but to where the other elements where originally placed ( = before animation ).

Here is a similar example of what this slider is able to do: [example](http://plnkr.co/edit/IP75MAoLlw0qcNhJXxf4?p=preview)

I'm trying to avoid from reading DOM elements and do calculations to make this work. Also as far as I know, I cannot put dynamic values in my animation states, is this true?

**Comment by EladBezalel** [comment]
Hey @xikky, regarding your last question - no ATM you can't use dynamic values in animations.

This issue is not related to the Material repository at all, i suggest you'd ask that at the [angular](https://github.com/angular/angular) repository or other support forums, good luck :)

**Comment by xikky** [comment]
Oh yes you are right! My bad, thanks! :)

**Comment by xikky** [comment]
For those who just might want to follow, the problem is on [stackoverflow](https://stackoverflow.com/questions/41013657/infinite-horizontal-slider-carousel-like)
