### ISSUE TITLE
Modal component

### ISSUE THREAD

**Issue by karan1276** [angular/material2#2088]
Are there any plans to make a "modal" component, like bootstrap maybe? 
ref: http://getbootstrap.com/javascript/#modals

**Comment by crisbeto** [comment]
[It's implemented already as `dialog`.](https://github.com/angular/material2/tree/master/src/lib/dialog#mddialog)

**Comment by karan1276** [comment]
Thanks

**Comment by karan1276** [comment]
you guys rock
