### ISSUE TITLE
Installation fails if typings is not installed globally

### ISSUE THREAD

**Issue by bjspencer** [angular/material2#2089]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should be able to install without typings installed

#### What is the current behavior?
Installing this package fails if typings is not installed globally. The error is `ERR! material2@2.0.0-alpha.6-2 postinstall: 'npm run typings'`

#### What are the steps to reproduce?
1. Remove typings if you have it installed (`npm uninstall -g typings`)
2. Attempt to install this package, either by deleting `node_modules` then running `npm install` in an existing project, or running `npm install material2 --save` on a project which does not have material2

#### What is the use-case or motivation for changing an existing behavior?
Typings is not listed as being required in `README.md`, and requiring it leads to confusing errors, both for those trying to develop with material2 for those trying to install other packages which depend on material2.

#### Which versions of Angular, Material, OS, browsers are affected?
Tried on npm 3.10.9 and 4.0.3 with node 6.9.1

**Comment by bjspencer** [comment]
Aha, so it appears this was fixed some time ago, but the npm version is old enough it doesn't have the fix.

**Comment by bjspencer** [comment]
Whoops, got an outdated package from npm with `material2`, rather than `@angular/material2`. Please remove issue.

**Comment by dahaupt** [comment]
@bjspencer I think you can close this issue yourself.
