### ISSUE TITLE
Checkbox Demo has an ordering issue with RTL 

### ISSUE THREAD

**Issue by arciisine** [angular/material2#2095]
#### Bug, feature request, or proposal:
In the demo app, the checkbox section, when using RTL, has an ordering issue.  The label and the associated checkbox are being separated, causing some odd behavior.

#### What is the expected behavior?
The checkboxes and labels should work the same, just with the visual order reversed.

#### What is the current behavior?
The label and checkbox are not reversed in RTL, but the very first checkbox is moved to the very end, while the label is left as is.
![image](https://cloud.githubusercontent.com/assets/1264175/20965980/d56dc696-bc3d-11e6-8223-8493538e8ad3.png)
![image](https://cloud.githubusercontent.com/assets/1264175/20965988/de73919e-bc3d-11e6-92f4-462e8d3549dd.png)
![image](https://cloud.githubusercontent.com/assets/1264175/20965992/e411fa00-bc3d-11e6-8b63-6b1d0d3f3df8.png)

#### What are the steps to reproduce?

Run the demo app, and use the Checkbox demo in RTL mode.

#### Which versions of Angular, Material, OS, browsers are affected?
alpha-10

**Comment by EladBezalel** [comment]
It seems like it's not our problem 😅 
I replicated it in [Codepen](http://codepen.io/EladBezalel/pen/dOKOJd).

The docs site is currently under development and this issue would be considered, thanks for pointing that out.
