### ISSUE TITLE
npm doesnt have dialog package

### ISSUE THREAD

**Issue by LeniM** [angular/material2#2096]
#### Bug, feature request, or proposal:
Npm is not aware of the dialog package

#### What is the expected behavior?
adding the repo to dependencies and getting all the packages

#### What is the current behavior?
adding the repo to dependencies and not getting the dialog package

#### What are the steps to reproduce?
npm install --save @angular/material

#### What is the use-case or motivation for changing an existing behavior?
using dialog in my project !

#### Which versions of Angular, Material, OS, browsers are affected?
all

#### Is there anything else we should know?
https://www.npmjs.com/~angular2-material

**Comment by crisbeto** [comment]
This is outdated. You should use the `@angular/material` package.

**Comment by fxck** [comment]
@crisbeto @jelbourn can you not change readme in packages in angular2-material.. to say something like "DEPRECATED, USE @angular/material"

**Comment by jelbourn** [comment]
@fxck Yeah, we should do that. I'll file a separate issue.
