### ISSUE TITLE
Mark old @angular2-material packages as obsolete

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#2103]
The [old `@angular2-material` packages](https://www.npmjs.com/~angular2-material) don't give any indication that they're obsolete. We should republish them with new README files that tell people what to do.

**Comment by dahaupt** [comment]
Would it not make sense to remove the old packages in 1-2 months completely from npm?

**Comment by jelbourn** [comment]
@dahaupt Like diamonds, npm packages are forever.

**Comment by jelbourn** [comment]
Done.
