### ISSUE TITLE
<md-input> placeholders are not working on the pink-bluegrey theme.

### ISSUE THREAD

**Issue by alxhub** [angular/material2#2106]
#### Bug, feature request, or proposal:

Bug report.

#### What is the expected behavior?

Placeholders show up on &lt;md-input&gt; when using the pink-bluegrey theme.

#### What is the current behavior?

Placeholder text is white until the &lt;md-input&gt; is focused.

#### What are the steps to reproduce?

http://plnkr.co/edit/qjcghUoBEs0GMING1eS9?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?

Alpha 10, Chrome 54

**Comment by crisbeto** [comment]
This due to it being a dark theme, but we don't actually apply the theme background to the body, we only have it on the `md-sidenav-layout` (which we use in the demo app). @jelbourn should I add the theme background to the body?

**Comment by jelbourn** [comment]
@crisbeto Nope. We shouldn't change the styles of any elements not owned by a component. This should probably just be something that goes into the theming guide.

**Comment by crisbeto** [comment]
Wouldn't this be something that's a pretty common use case? I'd imagine that not everybody will use `md-sidenav-layout` as their main wrapper element.

**Comment by jelbourn** [comment]
Potentially, but I want to stick to that policy for now and try to address this with documentation.
