### ISSUE TITLE
Is there a 12 column responsive grid system there in material 2.?

### ISSUE THREAD

**Issue by codejith** [angular/material2#2113]
#### Bug, feature request, or proposal:
(Feature Request):  12 column responsive grid system

#### What is the expected behavior?
 Something like this http://materializecss.com/grid.html

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by fxck** [comment]
There won't be any grid system as part of this repo.

Check https://github.com/angular/flex-layout

**Comment by hrantbagdasarian** [comment]
The Material2 feature list still includes a "layout" component. Is that still relevant or should we use the angular/flex-layout instead? If not, what are/will be the differences between both?

**Comment by jelbourn** [comment]
We'll have an official blog post on this soon, stay tuned to the Angular blog.

**Comment by charsi** [comment]
Might be useful to put a link to flex-layout in the docs for people looking for responsive options within Angular Material.

**Comment by russelltrafford** [comment]
in Dec 2016 there was a post from @jelbourn saying there will be an official blog post on this, could a link be provided, as that would help a lot :)

**Comment by chetan-rathod** [comment]
i am also stuck in this problem 
plz provide a solution for that it will help a lot to everyone

**Comment by rasert** [comment]
Please help. I tried to use flex-layout to put a card in the center of the page. Center in both axis. But it does not work. I can only put it in the center of the row.

**Comment by mackelito** [comment]
@rasert do you have a plunkr? If so please share and I´ll help if I can! :)

**Comment by nicksloan** [comment]
@russelltrafford I'm sure you've seen this by now, but for others who might land here while researching, this is the blogpost that @jelbourn mentioned: http://angularjs.blogspot.com/2016/12/angular-material-beta-release-new-flex.html

**Comment by rdineshkumar88** [comment]
For Angular Material 6.2.1, here's the tutorial to create 12 columns responsive grid. 
https://ampersandacademy.com/tutorials/angular-material/responsive-grid-layout-in-angular-material

**Comment by rdineshkumar88** [comment]
It seems to be working fine. Kindly check.

**Comment by rafadpedrosa** [comment]
This website is not working for me either @chauey :(

**Comment by chauey** [comment]
@rafadpedrosa I had to reset service worker. https://github.com/angular/material.angular.io/issues/378 "Visit chrome://serviceworker-internals/ and unregister the worker for material.angular.io. This worked for me."
