### ISSUE TITLE
[Tabs] Use MutationObserver to update tab header pagination

### ISSUE THREAD

**Issue by andrewseguin** [angular/material2#2115]
The tab header displays scrolling that updates when the header is initialized or when tabs are removed/added. This misses the case where the tab label's text changes and the scrolling should reflect the update.

Add a `MutationObserver` that notifies changes to the text node and lets the scrolling react to the change.

**Comment by jelbourn** [comment]
@EladBezalel could you take a pass at this? I want to create a general directive in core that just fires an event when the text content of an element changes uses a `MutationObserver`. The tabs should then use that as a signal to recalculate the width of the tab bar (for scrolling)

**Comment by EladBezalel** [comment]
closed with #2186

**Comment by EladBezalel** [comment]
closed with #2186
