### ISSUE TITLE
Sidenav is not working under ngIf control.

### ISSUE THREAD

**Issue by greg-md** [angular/material2#2118]
If the `md-sidenav` is under `ngIf` control, I'm getting "Cannot read property 'open' of undefined" when I want to open the sidenav.

Plunker: http://plnkr.co/edit/yEUe7pUZrbhZgfRTHclx?p=preview

**Comment by mmalerba** [comment]
This is a limitation of ngIf (see https://github.com/angular/angular/issues/6179)

You can work around it by using `@ViewChildren`:
```ts
@ViewChildren('start') sc: QueryList<MdSidenav>;
```
```html
<md-sidenav-container>
  <md-sidenav #start *ngIf="true">Hi</md-sidenav>
  <button md-button (click)="sc.first.open()">open</button>
</md-sidenav-container>
```
