### ISSUE TITLE
Select should adjust height when font-size changes

### ISSUE THREAD

**Issue by kara** [angular/material2#2127]
Currently when you change the font size of the select to override the default font size, the placeholder doesn't adjust to make space for a larger font. Md-input does do this, so select should as well.

**Comment by ReneVallecillo** [comment]
Just for reference Kara, I put a md-select after a md-input, and it overlaps without changing the font size. 

```html
<div>
      <md-input-container>
        <input md-input type="text" name="name" placeholder="Full name" formControlName="name">
      </md-input-container>
    </div>
    <div>
      <md-select placeholder="Company Name" formControlName="company">
        <md-option *ngFor="let company of companies" [value]="company.value">{{ company.viewValue}}</md-option>
      </md-select>
    </div>
```

**Comment by p-jan** [comment]
I had the same issue.
I was able to workaround it by applying the following style:

`:host /deep/ .mat-select-trigger {
    font-size: inherit;
    height: inherit;
}

:host /deep/ .mat-select-value-text {
    line-height: inherit;
}`

**Comment by hblieb** [comment]
@p-jan work around partly worked for me. I only needed the 
```
:host /deep/ .mat-select-trigger {
    font-size: inherit;
}
```
And I added
```
.mat-select {
    padding-top: 5px;  //makes the select's baseline align with neighboring text input
    margin-bottom: 14px //makes the text input below my select align with it's neighbor also
}
```

**Comment by javagaba** [comment]
Any news on this? This issue still seems to exist in the latest version...

**Comment by makdeniss** [comment]
I've fixed the alignment issue with this code:
```
.mat-select {
  margin-top: 14px;
}
```
You have to play with the `margin-top` value in your context. But that will align the input field and select field correctly with each other.

**Comment by richmwatts** [comment]
Still no fix for this?

**Comment by qstiegler** [comment]
Please fix this issue! Also the space between label and selected option is not the same than between label and text of an input field if you change the font-size.

**Comment by willshowell** [comment]
AFAIK this will be fixed by https://github.com/angular/material2/pull/6488

**Comment by jelbourn** [comment]
Should be resolved with the existence of `mat-form-field`
