### ISSUE TITLE
Some SCSS files refer to invalid path (a11y)

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#2133]
In [5cf7d175d66120b0e8262bef561f230cb6e31d11](https://github.com/angular/material2/commit/5cf7d175d66120b0e8262bef561f230cb6e31d11) several components got **a11y** support using a new SCSS resource.

The import is `@import '../a11y/_a11y';`
Which looks for the file in **material/src/lib/a11y/_a11y**

**a11y** is in **core**

The file exists in **material/src/lib/core/a11y/_a11y**

I don't know how the build passed but it's should be fixed

`@import '../core/a11y/_a11y';`

The files:
src/lib/button/button.scss
src/lib/card/card.scss
src/lib/dialog/dialog-container.scss
src/lib/menu/menu.scss
src/lib/select/select.scss
src/lib/sidenav/sidenav.scss
src/lib/slide-toggle/slide-toggle.scss
src/lib/snack-bar/snack-bar-container.scss
src/lib/tooltip/tooltip.scss

@crisbeto @mmalerba

**Comment by shlomiassaf** [comment]
@crisbeto can it be release as alpha 11-3 instead of waiting for 12?

**Comment by crisbeto** [comment]
This isn't up to me to decide, but I'll definitely look into why it's breaking. It worked when I was testing out the new fixed. How are you getting the error?

**Comment by shlomiassaf** [comment]
It doesn't break on the build probably because some paths were includes as roots (in the sass build) so it aligns, somehow...

But it's not right, the path is clearly wrong.

We have a special build process where we use the SCSS files in the NPM package to rebuild the SCSS for each component we opt-in to do so and it will replace the CSS in the component with our new build.
It allows customising the components by pre setting some SCSS $vars

we do it via a webpack loader.

**Comment by crisbeto** [comment]
Alright, I can't reproduce it just by running the build locally, but can you try to replace all of these:

```scss
@import '../a11y/_a11y';
```

With this:

```scss
@import '../a11y/a11y';
```

**Comment by shlomiassaf** [comment]
It won't help, i'm running a different build... but my process is not that relevant.

The relative path is not valid, if you follow it there's no file at the end... all other files does use **core** as part of the path.

It works because some configuration in the build made this path resolvable...

**Comment by crisbeto** [comment]
I mean if you could go into the `node_modules`, change the path and see if that helps with compilation.

**Comment by shlomiassaf** [comment]
yes, did that, didn't help... the file is not there.

**Comment by shlomiassaf** [comment]
When I add **core** it works

**Comment by crisbeto** [comment]
Oh, I see. Yeah no idea how that ended up compiling. I'll put in a PR.

**Comment by shlomiassaf** [comment]
It's actually interesting and error prone, this will probably repeat.

**Comment by shlomiassaf** [comment]
@jelbourn Can this reflect in a **alpha.11-3** version?

**Comment by jelbourn** [comment]
I'll try to do one shortly

**Comment by shlomiassaf** [comment]
@jelbourn a BIG thanks!

**Comment by jelbourn** [comment]
alpha.11-3 is released, should fix this
