### ISSUE TITLE
typescript miscompilation error when trying to run "demo-app" task 

### ISSUE THREAD

**Issue by shootermv** [angular/material2#2134]
Bug:

expected - the demo app to run

current behavior -
geting error:
Unable to compile TypeScript
tools/gulp/tasks/release.ts (52,10): Type 'Promise<{}>' is not assignable to type 'Promise<void>'

steps to reproduce:
 open terminal in root directory of project and run "npm run demo-app"

proposition for fix:
replace following line (tools/gulp/tasks/release.ts (52,10)):
"function _execNpmPublish(label: string): Promise< void > {"
 with:
"function _execNpmPublish(label: string): Promise<{}> {"

I'm newbie, so i guess there may be some more elegant solutions...

**Comment by crisbeto** [comment]
https://github.com/angular/material2/pull/2132 should fix it.

**Comment by crisbeto** [comment]
Closing since #2132 was merged.
