### ISSUE TITLE
Elements being inserted with incorrect order (Dialog)

### ISSUE THREAD

**Issue by crownz** [angular/material2#2136]
Just installed alpha 11, possible bug?

When opening dialog, overlay backdrop gets placed below dialog container and that makes it take all of the pointer events (closes dialog when I click anywhere on the screen)..

Also dialog is not getting centered by default (I did not add any position settings to config).

To replicate simply open new dialog.

![dialog issue](https://cloud.githubusercontent.com/assets/9164289/21043022/cd7f8f72-bdec-11e6-9003-d59c9b7cec77.png)

**Comment by crisbeto** [comment]
1. That's the proper position and behavior of the backdrop - it's supposed to close the dialog when you click outside. If you don't want user to be able to click outside to close, you can pass in the `disableClose` option.
2. Regarding the centering, what does your dialog config look like? Both opening it without a config and and with an empty config centers the dialog for me.

**Comment by crownz** [comment]
The issue is that the backdrop overlays the dialog itself and also closes when I click on the dialog. Just checked, md-select is also missbehaving, probably the issue is not with dialog but something went wrong with installation..

![material issue](https://cloud.githubusercontent.com/assets/9164289/21043484/041c85b0-bdef-11e6-9333-b8834529ec11.png)

**Comment by crisbeto** [comment]
Seems similar to https://github.com/angular/material2/issues/2137. I wonder whether the SASS failed to compile properly due to https://github.com/angular/material2/issues/2133

**Comment by crisbeto** [comment]
For completeness sake, are you building the CSS yourself @crownz? I've been trying to reproduce it on a plain app where I followed the getting started guide, but it works as expected.

**Comment by crownz** [comment]
Nop, I am not building CSS myself..

**Comment by crisbeto** [comment]
Alright, can you also try to delete the `@angular/material` from the `node_modules` and reinstalling it? Also what version are you using?

**Comment by crownz** [comment]
Rebuilt, seems to be working fine even without changing a11y paths to core. Thanks for help @crisbeto

**Comment by crisbeto** [comment]
You're welcome. I'll consider this resolved.
