### ISSUE TITLE
Angular 2 select wrong screen blur

### ISSUE THREAD

**Issue by theunreal** [angular/material2#2137]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When clicking the md-select to pick an option, the screen becomes darker and the options need to be focused and not blurred

#### What is the current behavior?
When clicking hte md-select to pick an option the screen becomes darker and the options along with it

![image](https://cloud.githubusercontent.com/assets/6171883/21043147/2fa5635a-bdfe-11e6-9c81-a6f644a154d3.png)

#### What are the steps to reproduce?
I actually have no idae how to reproduce, my app is quite big, but the select is inside a sidenav content,
and the app is RTL.

#### What is the use-case or motivation for changing an existing behavior?
Fix select user experience in such cases

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.3.0
Material beta 11
Tested on Chrome, Firefox

#### Is there anything else we should know?
RTL app

**Comment by crisbeto** [comment]
This seems similar to https://github.com/angular/material2/issues/2136. Can you try removing the `@angular/material` from the `node_modules` and reinstalling?

**Comment by theunreal** [comment]
Removed the `@angular/material` folder, reinstalled the  `@angular/material` package, restarted my application, issue still exists

**Comment by crownz** [comment]
Double check if you are not using custom built theme. If you do - try rebuilding it.

**Comment by theunreal** [comment]
Thanks @crownz yep it was the theme. I updated the theme to the new version theme css file, and it now works as excepted.
