### ISSUE TITLE
[Tabs] Example - no content displayed - docs outdated

### ISSUE THREAD

**Issue by atodd-geoplan** [angular/material2#2139]
#### Bug, feature request, or proposal:
Outdated document

#### What is the expected behavior?
When viewing a Tab, its content should be displayed

#### What is the current behavior?
Tab content is not displayed

#### What are the steps to reproduce?
Copy the tabs example from the docs

#### What is the use-case or motivation for changing an existing behavior?
Basic usage

#### Is there anything else we should know?
Update the docs - the examples are missing the template tab for content this is how it should be:

```
  <md-tab>
    <template md-tab-label>
      <md-icon>thumb_down</md-icon> The worst sushi
    </template>
    <template md-tab-content>
      <h1>Terrible sushi restaurants</h1>
      <p>...</p> 
    </template>
  </md-tab>
```

**Comment by jelbourn** [comment]
@atodd-geoplan `md-tab-content` was removed in alpha.10. You didn't provide the version of material you're using, so I'm guessing it's out of date. Closing this issue, feel free to open a new one with more information if you're seeing something not working in alpha.11

**Comment by atodd-geoplan** [comment]
Then I'm even more confused. I have installed following the guide, which leaves you with: 

"material2": "^2.0.0-alpha.6-2",

So how to get v10 ?

**Comment by atodd-geoplan** [comment]
This is an aside. The issue persists through to latest version:

    "@angular/material": "^2.0.0-alpha.11-3",

I still need the the tab-content. Class still exists:

**Comment by atodd-geoplan** [comment]
@jelbourn would it be possible to add a tab group example to your material2-app example?

**Comment by jelbourn** [comment]
@atodd-geoplan npm doesn't understand the `alpha.xx-yy` syntax; your best best is to point to a specific version, especially while we're still changing APIs in alpha. I recommend manually setting the dependency, clearing your `node_modules`, and re-installing with `npm` (not `yarn`, which has issues).
