### ISSUE TITLE
RTL Application dialog is LTR

### ISSUE THREAD

**Issue by theunreal** [angular/material2#2140]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Content inside a dialog should be similiar to the application direction

#### What is the current behavior?
Dialog content inside RTL application (html dir="rtl") is LTR

#### What are the steps to reproduce?
Opening any dialog in RTL app

#### What is the use-case or motivation for changing an existing behavior?
Make dialog work again for RTL apps

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.3.0
Material 11
All browsers

#### Is there anything else we should know?
The RTL applied fine and worked as excepted in Material 10

**Comment by jelbourn** [comment]
This will be addressed as part of #1719
