### ISSUE TITLE
Sidenav not working well with align end

### ISSUE THREAD

**Issue by andrewseguin** [angular/material2#2144]
The behavior for the sidenav is janky when opened from the right (`align="end"`)

See demo site https://material2-dev.firebaseapp.com/sidenav for example

**Comment by paulogr** [comment]
Has someone a workaround for this?

Thank you!

**Comment by mmalerba** [comment]
It seems this was fixed by #1990

**Comment by paulogr** [comment]
@mmalerba  Is this fix on master branch?

**Comment by paulogr** [comment]
@mmalerba  This commit you reference to is older than the reported issue

**Comment by andrewseguin** [comment]
It does appear to have been fixed in master by #1990. The jank is no longer there on the demo site. BTW this issue was reported in the morning and the commit was pushed to master in the afternoon.

**Comment by paulogr** [comment]
Thank you for clarification @andrewseguin, really appreciate.
