### ISSUE TITLE
md-select applying error styles before it is touched.

### ISSUE THREAD

**Issue by blyndcide** [angular/material2#2147]
When another control in a form is touched, md-select applies error styles even though it hasn't been touched yet.  The classes on md-select remain class="ng-untouched ng-pristine ng-invalid".

**Comment by dahaupt** [comment]
I've noticed the same problem. 

material2 version: **2.0.0-alpha.11-2**

**Comment by kara** [comment]
@blyndcide Thanks for the report! The selector for the invalid styles was too general, so it was picking up when the form was touched as well as its own control. Should be fixed by #2166.
