### ISSUE TITLE
MdTooltip broke the app after beta.11

### ISSUE THREAD

**Issue by paulogr** [angular/material2#2153]
#### Bug, feature request, or proposal:

Bug: MdTooltip broke my app after upgrade to beta.11

#### What is the expected behavior?

Before beta.11 the usage of MdTooltip was working as expected.

#### What is the current behavior?

Do not display my cards and broke the app.

#### What are the steps to reproduce?

Just create a simple button with a tooltip like this:

```
<button md-button md-tooltip="just a test" >
  <md-icon>play_arrow</md-icon>
</button>
```

#### What is the use-case or motivation for changing an existing behavior?

Avoid this error.

#### Which versions of Angular, Material, OS, browsers are affected?

angular-cli: 1.0.0-beta.22-1
@angular: 2.2.3
@angular/material: 2.0.0-alpha.11-3
node: 6.5.0
os: darwin x64

#### Is there anything else we should know?

Here it goes a print screen of the error on Chrome console.

![screen shot 2016-12-09 at 21 52 12](https://cloud.githubusercontent.com/assets/30919/21068627/5b445852-be5a-11e6-8d3b-2a83b5c3926e.png)

I have no idea what this error means, but if I remove the tooltip from the button everything works as expected.

Thank you.

**Comment by dahaupt** [comment]
@paulogr
```
<button md-button md-tooltip="just a test" >
  <md-icon>play_arrow</md-icon>
</button>
```

That code is working fine here. Are you sure your issue is based on md-tooltip? I don't think so.
Please provide a plunker example or nobody can ever reproduce your issue.

Your problem seems to be in `PlaylistComponent` at a different position.

**Comment by paulogr** [comment]
The problem is, with the same template and component, when I remove the tooltip everything works fine again.

Do you have a configured plunker with angular2 + material2? 

So I can try to reproduce the error.

**Comment by dahaupt** [comment]
@paulogr Before we do that, have you tried to remove @angular/material from node_modules and reinstall it new?

**Comment by paulogr** [comment]
Yeah, I did that 3 times, remove the node_modules/@angular/material and reinstall again. 

Same error.

The playlist component is very simple, just receive a list of playlists and display it.

`<div class="as-playlists">
  <ul class="playlist-row">
    <li class="playlist-cell" *ngFor="let playlist of playlists; let i = index;">
      <div class="playlist-card" (click)="select(playlist, i)">
        <div class="header" [class.active]="isPlayingPlaylist[i] && isPlaying()" [class.loading]="isPlayingPlaylist[i] && isLoading()">
          <img src="/assets/img/playlist01.png" />
        </div>
        <div class="content">
          <h3>{{playlist.title}}</h3>
          <p>{{playlist.description}}</p>
        </div>
        <div class="actions">
          <button md-button>
            <md-icon>play_arrow</md-icon>
          </button>
          <button md-button (click)="schedule($event, playlist)">
            <md-icon>playlist_add</md-icon>
          </button>
          <button md-button (click)="schedule($event, playlist)">
            <md-icon>favorite</md-icon>
          </button>
          
        </div>
      </div>
    </li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
  </ul>
</div>`

**Comment by dahaupt** [comment]
@paulogr Can you copy your complete inline template of your `PlaylistComponent`? Maybe we can find an issue there.

**Comment by paulogr** [comment]
I tried to do that but GH parse my HTML...

Again

`<div class="as-playlists">
  <ul class="playlist-row">
    <li class="playlist-cell" *ngFor="let playlist of playlists; let i = index;">
      <div class="playlist-card" (click)="select(playlist, i)">
        <div class="header" [class.active]="isPlayingPlaylist[i] && isPlaying()" [class.loading]="isPlayingPlaylist[i] && isLoading()">
          <img src="/assets/img/playlist01.png" />
        </div>
        <div class="content">
          <h3>{{playlist.title}}</h3>
          <p>{{playlist.description}}</p>
        </div>
        <div class="actions">
          <button md-button>
            <md-icon>play_arrow</md-icon>
          </button>
          <button md-button (click)="schedule($event, playlist)">
            <md-icon>playlist_add</md-icon>
          </button>
          <button md-button (click)="schedule($event, playlist)">
            <md-icon>favorite</md-icon>
          </button>
          
        </div>
      </div>
    </li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
  </ul>
</div>`

**Comment by paulogr** [comment]
```<div class="as-playlists">
  <ul class="playlist-row">
    <li class="playlist-cell" *ngFor="let playlist of playlists; let i = index;">
      <div class="playlist-card" (click)="select(playlist, i)">
        <div class="header" [class.active]="isPlayingPlaylist[i] && isPlaying()" [class.loading]="isPlayingPlaylist[i] && isLoading()">
          <img src="/assets/img/playlist01.png" />
        </div>
        <div class="content">
          <h3>{{playlist.title}}</h3>
          <p>{{playlist.description}}</p>
        </div>
        <div class="actions">
          <button md-button>
            <md-icon>play_arrow</md-icon>
          </button>
          <button md-button (click)="schedule($event, playlist)">
            <md-icon>playlist_add</md-icon>
          </button>
          <button md-button (click)="schedule($event, playlist)">
            <md-icon>favorite</md-icon>
          </button>
          <!--<button md-button md-tooltip="Tocar a playlist" tooltip-position="above" >
            <md-icon>play_arrow</md-icon>
          </button>
          <button md-button md-tooltip="Adicionar às minhas músicas" tooltip-position="above" (click)="schedule($event, playlist)">
            <md-icon>playlist_add</md-icon>
          </button>
          <button md-button md-tooltip="Marcar como favorita" tooltip-position="above" (click)="schedule($event, playlist)">
            <md-icon>favorite</md-icon>
          </button>-->
        </div>
      </div>
    </li>
    `<li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
    <li class="playlist-cell playlist-cell--ghost"></li>
  </ul>
</div>```

**Comment by dahaupt** [comment]
@paulogr I can't find any problem in your template. 

Tooltips are working fine in my project and also on dev demo page:
https://material2-dev.firebaseapp.com/tooltip

But maybe there is a real problem I am not able to see, but I am not sure how to debug it without a reproducing plunker.

**Comment by crisbeto** [comment]
I don't see anything in Material that could be throwing this. @paulogr can you try changing this expression in your template `[class.active]="isPlayingPlaylist[i] && isPlaying()"` into this `[class.active]="isPlayingPlaylist && isPlayingPlaylist[i] && isPlaying()"`?

**Comment by paulogr** [comment]
Thank you @dahaupt and @crisbeto for you help.

After some debugging and testing the `md-tooltip` in other section of my app finally I got an error message the shows me the I miss to include the hammerJS on my app.

Just included HammerJS on my app and don't get this error anymore.

That sai, now my question is...

Is this mandatory to use hammerJS now? Before beta.11 I never needed to include HammerJS and the docs said to include only if you are using `md-slide-toggle` or `md-slider` [https://github.com/angular/material2/blob/master/GETTING_STARTED.md#additional-setup-for-md-slide-toggle-and-md-slider](https://github.com/angular/material2/blob/master/GETTING_STARTED.md#additional-setup-for-md-slide-toggle-and-md-slider)

**Comment by crisbeto** [comment]
I don't think it should. While it does use touch events, it just binds to the native ones and it also doesn't import Hammer. The only components that depend on it should be the slider and slide toggle.

**Comment by paulogr** [comment]
Well, I'll close this issue now, and try to make a test with a plunker without hammerJS to see if the problem happens.

And @crisbeto do you have a plunker with angular + material configured? Do you know when I can find one?

Thank you.

**Comment by crisbeto** [comment]
Yes, there is one in the template when you're creating an issue. Here's the link  http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by QuentinFchx** [comment]
I also had the same issue with `md-tooltip` and Hammer.js being required for its usage.

**Comment by andrewseguin** [comment]
@QuentinFchx is right, the `longpress` event depends on hammerJS. This is to match the spec of material design where longpress will trigger the tooltip for mobile and then hide the tooltip after some delay.

The docs should be updated to reflect that tooltip now requires hammerJS.
