### ISSUE TITLE
feat(<md-sidenav>): decrease box-shadow

### ISSUE THREAD

**Issue by rolandjitsu** [angular/material2#2158]
#### Bug, feature request, or proposal:
Proposal.

#### What is the expected behavior?
It would be visually much better if the box shadow (elevation) on the `<md-sidenav>` would be a little smaller. At least when the sidenav is set to `side` mode. I force it to the same value as `.md-elevation-z2` and it seems to look much better.

#### What is the current behavior?
The `<md-sidenav>` currently has a lot of box shadow.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
Angular `2.3.0`
Material `2.0.0-alpha.11`

**Comment by DevVersion** [comment]
The material design specifications mention a box-shadow of z-16. 

But as you said, you can always customize the box-shadow on your own.
