### ISSUE TITLE
md-select placeholder overlaps with md-toolbar

### ISSUE THREAD

**Issue by belev** [angular/material2#2168]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-select placeholder not to overlap with md-toolbar

#### What is the current behavior?
md-select placeholder overlaps with md-toolbar

#### What are the steps to reproduce?
Click to select item, the placeholder overlaps. After selecting an item the placeholder is not visible too.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/uJR8DXST8lTBOptjgkN4?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0-alpha.11-2 (tested on master too), Chrome 55

#### Is there anything else we should know?
Not sure if that's actually a bug or the user should handle the margin/padding after the toolbar.

**Comment by pj-agfa** [comment]
I noticed that the positioning and transform of the md-input placeholder is different compared to the md-select placeholder. This is probably related to this issue.

**Comment by kara** [comment]
Yeah, related to https://github.com/angular/material2/issues/2124 and https://github.com/angular/material2/issues/2127

**Comment by SalmaKolkari** [comment]
margin: 1em 0;
padding-bottom: 6px;

these css properties are missing in select.css file.

Please add : 

md-select {
  display: inline-block;
  outline: 0;
  margin: 1em 0;
  padding-bottom: 6px;
}

in select.css file

and add same css properties in

styles: ["md-select{display:inline-block;outline:0;margin: 1em 0;padding-bottom: 6px;} 

in 

Component({selector: 'md-select, mat-select', 

in 

select.js file in select folder of @angular/material directory.

**Comment by jelbourn** [comment]
Tracking via #2124
