### ISSUE TITLE
Can't resolve 'hammerjs'

### ISSUE THREAD

**Issue by holms** [angular/material2#2172]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

hammerjs loaded successfully.

#### What is the current behavior?

```
frontend_1  | ERROR in ./src/app/app.module.ts
frontend_1  | Module not found: Error: Can't resolve 'hammerjs' in '/frontend/src/app'
frontend_1  |  @ ./src/app/app.module.ts 2:0-19
frontend_1  |  @ ./src/app/index.ts
frontend_1  |  @ ./src/main.browser.ts
frontend_1  |  @ multi main
frontend_1  | Child html-webpack-plugin for "index.html":
frontend_1  |     chunk    {0} index.html 542 kB [entry]
frontend_1  |          + 4 hidden modules
```

#### What are the steps to reproduce?

Just download angular2-webpack-starter, and follow instructions of your GETTING_STARTED.md regarding md-toggle and hammerjs dependency.

#### What is the use-case or motivation for changing an existing behavior?

I just want this damned material2 start to work with angular2-webpack-starter.

#### Which versions of Angular, Material, OS, browsers are affected?

* OS: Debian Jessie
* Angular: 2.2.1
* NPM: 1.4.21

**Comment by crisbeto** [comment]
Are you sure you followed everything?

You need to run this:

```bash
npm install --save hammerjs 
npm install --save-dev @types/hammerjs
```

Afterwards you have to add `import 'hammerjs';` in you app's main module. Finally you should add the following to your `tsconfig.json`.

```json
{
  "compilerOptions": {
    "types": [
      "hammerjs"
    ]
  }
}
```

**Comment by holms** [comment]
Just download angular2-webpack-starter and try yourself. 

After doing this:

```
npm install --save hammerjs 
npm install --save-dev @types/hammerjs
```

`tsconfig.json` already contains hammerjs in types. `import 'hammerjs';` is at the first line of app main module file.

**Comment by JanStureNielsen** [comment]
See http://stackoverflow.com/a/39496268/3342253

**Comment by holms** [comment]
@JanStureNielsen have you at least noticed my comment on that stackoverflow topic? mm..? please don't throw generic solution, because there's none. Download this: https://github.com/AngularClass/angular2-webpack-starter/ do instruction from that link you gave me, and enjoy error which pop ups. :)

**Comment by JanStureNielsen** [comment]
@holms -- you submitted an issue in the `angular/material2` project (this project) but your comment above references the `AngularClass/angular2-webpack-starter` project (not this project). Are you having problems when you follow these instructions:

  https://github.com/AngularClass/angular2-webpack-starter

or when you follow this project's instructions:

  https://github.com/angular/material2/blob/master/GETTING_STARTED.md

For the former, please open an issue in the AngularClass/angular2-webpack-starter project...

**Comment by holms** [comment]
I have a problem for
https://github.com/angular/material2/blob/master/GETTING_STARTED.md

**Comment by JanStureNielsen** [comment]
What do the following commands show, @holms:

    ng --version
    npm --version

**Comment by holms** [comment]
@JanStureNielsen I don't use ng

```
$ npm --version
3.10.9
```

**Comment by JanStureNielsen** [comment]
@holms -- this project's `GETTING_STARTED.md` starts with installing Angular CLI and uses it throughout; so, you're **not** following this project's GETTING_STARTED.md. As noted in this project's CONTRIBUTING.md document, support questions should be directed to StackOverflow -- I suggest you do just that and add a plunker reproducing your problem...and you might consider using Angular CLI at least to get started.

**Comment by holms** [comment]
Basically what you're saying is that this project doesn't support webpack.

**Comment by JanStureNielsen** [comment]
No, @holms -- that's not what I'm saying at all. I'm using Angular 2, Angular 2 Material, Angular CLI and webpack in my project and it's working very nicely. Try Angular CLI -- it'll be well worth your time to at least get something up and running.
