### ISSUE TITLE
Select panel/overlay has wrong position

### ISSUE THREAD

**Issue by elvirdolic** [angular/material2#2178]
#### Bug, feature request, or proposal:
Somehow the position of the opened select overlay/panel is not close to the trigger. It seems that this has todo with the scroll position. 

Example with multiple selects inside a table

![select_panel_wrong](https://cloud.githubusercontent.com/assets/17769458/21083122/a5e95c3c-bfe9-11e6-9fed-e150628d5988.png)

Single select
![select_pnael_wrong2](https://cloud.githubusercontent.com/assets/17769458/21083124/b85fa182-bfe9-11e6-935d-9655f44e8afe.png)

#### What is the expected behavior?
Should be near the trigger

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
alpha-11

**Comment by crisbeto** [comment]
Does this happen when you open the select or if you try to scroll after it was opened? Currently we don't block scrolling when overlays are open (there's a pending PR for it, though).

**Comment by elvirdolic** [comment]
This happens when I click the select.

**Comment by kara** [comment]
@elvirdolic Can you provide a plunker repro?  Having a hard time replicating.

**Comment by elvirdolic** [comment]
@kara the plunker template is out of date. <md-select> is not available.

It seemt that this is related to the scrollbar. Without scroll bar the position is always OK.

See two screens. If I scroll down and click on the select the panel is opened somewhere above and the scrollbar is also scrolled to the panel (maybe due the focus)

![image](https://cloud.githubusercontent.com/assets/17769458/21092956/87518978-c04f-11e6-9cb2-272c7c373f9a.png)

**Comment by kara** [comment]
@elvirdolic Sorry about the plunker template; didn't realize. It should be updated soon! 

In our demo app, we also have a scrolled environment, but we don't see this issue when scrolling. Can you post some of the code you're using? Or link to a branch?

**Comment by jelbourn** [comment]
@DevVersion isn't the plunker always pointing to the latest release?

**Comment by DevVersion** [comment]
@jelbourn The Plunker template should always point to the latest release on npm. (See http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview)

**Comment by elvirdolic** [comment]
@DevVersion it's not the latest one if you put   <md-select><md-option>Hello</md-option></md-select> inside it's not working

Nevertheless issue is not a related to md-select. We had some modifications on the overlay-container css class which were necessary in the previous versions.

**Comment by DevVersion** [comment]
@elvirdolic This works for me. I can imagine that the old `UMD` bundle is still cached on your browser. 

> The caching issue could be fixed by adding some random hash to the URL parameters. We will fix that soon with the new Plunker concept.
