### ISSUE TITLE
placeholder disappears when using md-line with md-select 

### ISSUE THREAD

**Issue by geelus** [angular/material2#2179]
#### Bug, feature request, or proposal:
placeholder disappears when using md-line with md-select 

#### What is the expected behavior?
placeholder to remain on screen when using md-line with md-select 

#### What is the current behavior?
placeholder disappears when using md-line with md-select 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

`<md-list>
<md-list-item>
      <md-select md-line placeholder="disappearing placeholder">
        <md-option>Option</md-option>
        <md-option>Option</md-option>
        <md-option>Option</md-option>
      </md-select>
    </md-list-item>
  </md-list>`

**Comment by kara** [comment]
Related to https://github.com/angular/material2/issues/2124 and https://github.com/angular/material2/issues/2127

**Comment by lukaspj** [comment]
I'm seeing a similar issue, however re-creating it in the Plunker template it works. Has there been any specific changes to amend this?

**Comment by geelus** [comment]
I've still got the same issue. Unfortunately no fix yet. I can't replicate in plunker either.

**Comment by geelus** [comment]
By the way to fix I'm using fxFlex instead of md-line

**Comment by jelbourn** [comment]
MdLine is intended to be used for text content only, not for more complex components.
