### ISSUE TITLE
Sidenav Toolbar buttons are hidden but they are clicked when using fullscreen and closed sidenav

### ISSUE THREAD

**Issue by geelus** [angular/material2#2182]
#### Bug, feature request, or proposal:
I'm using different pages and based on my need I'm setting the md-sidenav-layout to fullscreen mode. The issue is that the new sidebar that I use on the fullscreen page, although showing the toolbar buttons (like back arrow button) but when I click on them, they trigger the action of the button behind them. 

Note that this happens when the sidenav is in collapse mode (opened = false). 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template (in providing relevant info). Please file a new issue that follows the template, which gives the team the information needed to investigate.
