### ISSUE TITLE
MdSnackBar does not close when MdDialog is closed

### ISSUE THREAD

**Issue by jermowery** [angular/material2#2190]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

MdSnackBar should be closed automatically when it's host MdDialog is destroyed or should be closable in ngOnDestroy.

#### What is the current behavior?

MdSnackBar remains open even after it's host MdDialog is destroyed. The SnackBar will be unresponsive with the buttons unclickable.

#### What are the steps to reproduce?

1. Open an MdSnackBar from an MdDialog.
2. Close the MdDialog 

Plunker with the behavior: http://plnkr.co/edit/xrf3OSZec4J1w2MncFbY?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Better user and developer experience

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2, Material 2

**Comment by crisbeto** [comment]
All of the Material modules are intended to do be independent of each other. If we closed all of the toasts automatically when a dialog is closed, we'd make the dialog module dependent on the snack bar. You can achieve the same by subscribing to the dialog's close observable:

```ts
this.dialogRef = this.dialog.open(SomeDialog);

this.dialogRef.afterClosed().subscribe(result => {
  // close your snack bar
});
```

**Comment by jermowery** [comment]
Here is a Plunker showing the issue: http://plnkr.co/edit/xrf3OSZec4J1w2MncFbY?p=preview

The component shown in the dialog is the component creating the snackbar

**Comment by jermowery** [comment]
In the above example dismiss is called on the MdSnackBarRef instance in ngOnDestroy of the dialog component

**Comment by jelbourn** [comment]
@crisbeto could you take a look at this one?
