### ISSUE TITLE
BUG - md-input ng-reflect-model not reflect the input

### ISSUE THREAD

**Issue by eslammahgoub** [angular/material2#2198]
#### Bug, feature request, or proposal:
I use ngModule form with dynamics inputs and when you set data and try to add new inputs it show in md-input the ng-reflect-model but not in input the ng-reflect-model in md-input-infix so it's not showing in the view.

#### What is the expected behavior?
the ng-reflect-model in md-input has the same data as the ng-reflect-model in input

#### What is the current behavior?
the ng-reflect-model in md-input hasn't the same data as the ng-reflect-model in input

#### What are the steps to reproduce?
 Here is a Plunker is the *best* way to get the team to see your issue.
Plunker template: https://plnkr.co/edit/jUWH4P?p=preview
Try add data and after then click On Add Button

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2  @2.3.0
angular2-material @2.0.0-alpha.8-2

#### Is there anything else we should know?
there are also an attachment for inspect
![screenshot from 2016-11-17 11-15-12](https://cloud.githubusercontent.com/assets/5474280/21148485/11ab4f7a-c161-11e6-861e-5ef2e6fa36a7.png)

**Comment by mmalerba** [comment]
`md-input-container` is now available which gives the user control of the underlying `input` element. should work for your use case, just put the ngModel on the native `input`

**Comment by eslammahgoub** [comment]
see `md-input-container` not supported yet [#2267](https://github.com/angular/material2/issues/2267)

**Comment by kotsengkuba** [comment]
Hi. It seems that the issue is still present even when the native `input`  is used. 
https://plnkr.co/edit/0mZ4dl4ywGWUWulQog3r?p=preview

**Comment by mmalerba** [comment]
@eslammahgoub yes apologies, I meant available in head and will be released in the next version
