### ISSUE TITLE
Select menu not appearing

### ISSUE THREAD

**Issue by doorman02** [angular/material2#2199]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The select menu should appear when the select arrow is clicked

#### What is the current behavior?
The select menu doesn´t appear

#### What are the steps to reproduce?
This is how the select looks like in my template.
 ```
<md-select placeholder="Testing" [(ngModel)]="currentOption" [disabled]="false">
        <md-option [value]="option1">Option1</md-option>
        <md-option [value]="option2">Option2</md-option>
        <md-option [value]="option3">Option3</md-option>
        <md-option [value]="option4">Option4</md-option>
  </md-select>
```

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
Material Design alpha 11.3, using Chrome

**Comment by negberts** [comment]
Try adjusting the z-index. We had the same issue with md-select on a dialog

**Comment by kara** [comment]
@doorman02 Your code snippet works fine for me. Can you post more code or a plunker repro?

**Comment by doorman02** [comment]
Hi @kara , @negberts was right the select was inside a div where the z-index was set to 2001, when I removed the z-index it appeared. I was trying to setup a plunkr based on the template but it looks like the Material Module cannot be found. 
http://plnkr.co/edit/yk0k2S7CvVqwSdAYAVcN?p=preview

Would be nice if this would also work with different parent div z-indexes.

Is there any documentation available for the select component?

Thanks for your help!

**Comment by kara** [comment]
Okay, seems like this is resolved. Closing!
