### ISSUE TITLE
Failing E2E keyboard interaction test for md-menu

### ISSUE THREAD

**Issue by belev** [angular/material2#2201]
The test `should auto-focus the first item when opened with SPACE` in `menu.e2e.ts` fails. It seems to me like `sendKeys` don't send properly the space key.
![screenshot from 2016-12-13 19 54 25](https://cloud.githubusercontent.com/assets/5807771/21152804/968dddac-c170-11e6-84aa-2576528ed56d.png)

**Comment by DevVersion** [comment]
Yeah this is an issue with the `chromedriver` version 2.25. 

Recently a new `chromedriver` v2.26 has been released and is going to be available soon for protractor.

See SHA https://github.com/angular/webdriver-manager/commit/b40a93f00f661b128b7853590d79cbc6dd3b87ee
