### ISSUE TITLE
Slide Toggle doesn't refreshed when operation cancelled in the componnet

### ISSUE THREAD

**Issue by brachi-wernick** [angular/material2#2203]
Bug
if I have a case when I change my slider from off to on: meaning from false to true,
and then I have some logic in my component class that cancel this change, for example: I open a modal on change, and the user hit cancel.
then I want the slider to becomes off-false again.

#### What is the expected behavior?
I should see in the page that the slider becomes off again, even if it was checked.

#### What is the current behavior?

the value in the component class becomes false, but the page doesn't refreshed with the new value
and I see like it is checked-on-true.

here a plunker describes this:
I put there also a simple input checkbox, there it works.

http://plnkr.co/edit/jT3uk0SpWCu9LyJkFTYh?p=preview

**Comment by DevVersion** [comment]
It looks like the `native` checkbox isn't able to handle that as well.

* I personally don't consider this as a big deal and it looks more like this should be reported to the Angular repo instead?

**Comment by brachi-wernick** [comment]
@DevVersion 
>It looks like the native checkbox isn't able to handle that as well.

what doesn't behave well in checkbox?
> it looks more like this should be reported to the Angular repo instead?

don't think so, works well with any other native element.

I have workaround, if I put `undefine`d then it works, because there is a change.
I think you aren't trigger a change because it is not changed, it was false and remain false, maybe it is related to the `OnPush` strategy?

**Comment by DevVersion** [comment]
@brachi-wernick I'm having trouble understanding your issue here.

It's that the `slide-toggle` is not updating the state when you update the binding in the `(change)` hook?

When I did exactly the same with the `<input>` it didn't work either
- http://plnkr.co/edit/eq2Ad8bGm5C3zDYpyhKx?p=preview

**Comment by DevVersion** [comment]
Closing this issue for now. I can reopen if we there is some additional feedback.

**Comment by brachi-wernick** [comment]
@DevVersion this link is broken

**Comment by DevVersion** [comment]
http://plnkr.co/edit/Xp98aP930uLoNPtY8eZJ?p=preview
