### ISSUE TITLE
Documentation for gestures module

### ISSUE THREAD

**Issue by code-tree** [angular/material2#2206]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Docs exist that explain how to use the gestures module.

#### What is the current behavior?
No docs seem to exist

#### Is there anything else we should know?
It took me a while to figure out that I needed to put `{provide: HAMMER_GESTURE_CONFIG, useClass: MdGestureConfig},` in my core module to allow binding to touch events in my app.

I'm still not sure whether I should add that as a provider in the root of my app, or just in the components that need it?

Even more confusing. Some events were already working (like pan), but others were not (swipe). I assume this is because of the defaults Hammer has??

**Comment by jelbourn** [comment]
Closing into #2789
