### ISSUE TITLE
Refactor one-time completion observables to Promises

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#2208]
There are a few places where we use an `Observable` for something that only ever "completes" (dialog and snackbar off the top of my head). We should use promises instead so that those APIs work with `await` TS 2.1.

**Comment by maxencefrenette** [comment]
Another way to go about it would be to embrace the Observables and only ever use them. For instance, the http service only uses observables and I find it quite useful.

**Comment by jelbourn** [comment]
Actually going to close this because at this point it's too much of a breaking change.
