### ISSUE TITLE
'md-sidenav-container' is not a known element:

### ISSUE THREAD

**Issue by SikFar** [angular/material2#2213]
#### What is the expected behavior?
To run md-sidenav-container example

#### What is the current behavior?
md-sidenav-container does not show, console shows error
`zone.js:388 Unhandled Promise rejection: Template parse errors:
'md-sidenav-container' is not a known element:
1. If 'md-sidenav-container' is an Angular component, then verify that it is part of this module.
2. If 'md-sidenav-container' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("<md-toolbar>Home</md-toolbar>
[ERROR ->]<md-sidenav-container>
  <md-sidenav #start (open)="closeStartButton.focus()">
    Start Sidenav.`

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
```
"dependencies": {
...
"@angular/material": "^2.0.0-alpha.9-3",
"angular-cli": "1.0.0-beta.19-3",
...
}
```

```
"devDependencies": {
...
"angular-cli": "1.0.0-beta.18",
...
}
```

**Comment by SamiAl90** [comment]
md-sidenav-container is only available on the current version, which is not yet released.
You still have to use md-sidenav-layout.

**Comment by SikFar** [comment]
@SamiAl90 Ah, I see. Thank you!

**Comment by crisbeto** [comment]
Closing since the renamed element should be in the next version.
