### ISSUE TITLE
Menu not functioning properly on RTL

### ISSUE THREAD

**Issue by AsherBarak** [angular/material2#2214]
#### Bug, feature request, or proposal:
Bug

check out this screenshot:
![image](https://cloud.githubusercontent.com/assets/6647171/21182458/eb7ec6d2-c20b-11e6-8d2d-bf88f1ae815e.png)

When the menu button was not positioned to the left, the menu was not visible altogether, as it was positioned off screen:
![image](https://cloud.githubusercontent.com/assets/6647171/21182669/ec08ddbc-c20c-11e6-8fd8-541c619bfc0e.png)

@crisbeto & @jelbourn @mmalerba is RTL a high priority for you? I can put some testing efforts on it for a project due in a few months (do not expect dev contribution), are you expecting to be in BETA in that time-frame?

**Comment by jelbourn** [comment]
All the components support RTL now, the only small piece missing for overlay components is that part that tells them that they're in an RTL context. Tracked via #1719
