### ISSUE TITLE
Item rendering has become very slow in md-list/md-nav-list (alpha.11-3)

### ISSUE THREAD

**Issue by s-f-a-g** [angular/material2#2215]
#### 
```
<my-component>
   <my-list [theList]='theListFromBackend'>
  </my-list>
</my-component>
```

my-list component 
```
<md-list>
  <my-item *ngFor="let item of items" [item]="item">
  </my-item>
</md-list>

```
finally the my-item component
```
<md-list-item>
  <md-icon md-list-avatar *ngIf="!item.purchased">check_box_outline_blank</md-icon>
  <md-icon md-list-avatar  *ngIf="item.purchased">check_box</md-icon>
  <h4 md-line>{{item.name}}</h4>
  <span md-line>{{ item.purchasedDate }}</span>
  <md-icon *ngIf="item.starred">star_full</md-icon>
  <md-icon [md-menu-trigger-for]="menu">more_vert</md-icon>
</md-list-item>
```

#### 
Angular : 2.3.0 
Material : 2.0.0-alpha.11-3 
Browser : Chrome
OS : windows 7
"Backend" : firebase with angularfire2

**Comment by crisbeto** [comment]
Going by the changelog, it doesn't look like there have been any commits that could cause this. Can you post a Plunkr?

**Comment by sebfag** [comment]
I didn't parse all the commits but there are some related to list.
I will try to make a plunkr

**Comment by mmrath** [comment]
Not 100% sure, but it could be related to Angular 2.3.0. I have a table which is slow with 2.3.0 but works fine on 2.2.4. @sebfag could you try angular 2.2.4 and see if it is still and issue?

**Comment by jelbourn** [comment]
Closing this as I suspect it may be obsolete. Feel free to re-open if there's still a problem.
