### ISSUE TITLE
No method in md-input to select the entered text

### ISSUE THREAD

**Issue by kunalapila** [angular/material2#2218]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
There is no function to select the text that has been entered by a user in the md-input component

#### What is the current behavior?
This is how I tackled the issue, although using _vars in the code in not a good practice
http://plnkr.co/edit/7BFzayYpgHS8JCtaVOst

#### Proposed solution:
I can fix this by writing a wrapper select() to achieve the required behavior.

**Comment by mmalerba** [comment]
`md-input-container` is now available which gives the user control of the underlying `input` element. should make this easy
