### ISSUE TITLE
Allow styling of menu actuators

### ISSUE THREAD

**Issue by dansanderson** [angular/material2#2220]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
When I trigger an md-menu with an actuator (usually a button) connected with md-menu-trigger-for, I want an easy way to change the appearance of the actuator for as long as the menu is open that doesn't involve a custom component or directive.

#### What is the current behavior?
md-menu-trigger-for offers onMenuOpen and onMenuClose events that allow for custom behaviors but it does nothing to allow custom appearances with just template logic and CSS.

#### What are the steps to reproduce?
Standard button menu example:

<button md-icon-button class="md-primary"
    [md-menu-trigger-for]="myMenu">
  <md-icon>create</md-icon>
</button>
<cfc-menu #myMenu="cfcMenu" [menu]="myMenuModel"></cfc-menu>

#### What is the use-case or motivation for changing an existing behavior?
Many Material menu buttons I know use a "held open" appearance for the button while the menu is opened. This goes away when the menu is closed by any means (clicking on the backdrop, clicking on the button again, etc.).

#### Which versions of Angular, Material, OS, browsers are affected?
ng2 Material 2

#### Is there anything else we should know?
jelbourn proposed: "I would implement it as the menu exposing an `isOpen` property, so you could do something like:"

<button md-menu-trigger-for="myMenu" [class.xx-menu-open]="myMenu.isOpen">

**Comment by kara** [comment]
@dansanderson The menu trigger already exposes a `menuOpen` property that is true when the menu is open. Is this not doing what you need?

**Comment by dansanderson** [comment]
@kara Ah, sorry, I didn't see that. :) Can you teach me how to refer to that property in a binding expression on the element? I assume I can do something like <button md-button md-menu-trigger-for="myMenu" [class.xx-menu-open]="....menuOpen">? Thanks for your help!

**Comment by jelbourn** [comment]
@dansanderson Ah, I missed that property. It would be

```html
<button md-menu-trigger-for="..." 
    #trigger="MdMenuTrigger" 
    [class.xx-open]="trigger.menuOpen">
```

**Comment by dansanderson** [comment]
Thanks for the help!
