### ISSUE TITLE
md-sidenav mode="over" focus state

### ISSUE THREAD

**Issue by robisim74** [angular/material2#2224]
#### Bug, feature request, or proposal:
The base path remains in active state when you select another link and you close and reopen the sidenav, only in mode="over". Need an event, like a click, to deactivate it.

#### What is the expected behavior?
It has worked fine up to 2.0.0-alpha.10

#### What is the current behavior?
<img width="584" alt="2016-12-14" src="https://cloud.githubusercontent.com/assets/14012361/21203589/6792c074-c253-11e6-9a7c-a24c2d4e9e68.png">

#### What are the steps to reproduce?

http://plnkr.co/edit/R9p0F7

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0-alpha.11-xx, in all browsers.

#### Is there anything else we should know?
I tried Angular workarounds (routerLinkActive) without success.

Thanks

**Comment by robisim74** [comment]
Same problem with Material 2.0.0-beta.X, except in Firefox.

**Comment by jelbourn** [comment]
@mmalerba re: focus state

**Comment by helzgate** [comment]
@robisim74 wanna hear something really weird regarding that icon?   I have the same issue, it stays active after use, but what's even more strange is I've found that certain `<div *ngIf="bool">hi</div>` elements won't show after changing value of bool to true until I hover over this same icon.  Then they magically appear.  Other md-button and similar elements on the page don't have this same magical affect, only that menu button.

**Comment by robisim74** [comment]
@helzgate I didn't have time to investigate.

**Comment by robisim74** [comment]
@jelbourn @mmalerba The error on base path and on icon is still present in v2.0.0-beta.2

**Comment by mmalerba** [comment]
@robisim74 Can you provide a more detailed set of repro steps and description of what the problem is. I updated your plunker to work with the latest material version: http://plnkr.co/edit/IvLXYMiAHqr8mbmT9cGB?p=preview

Everything appears to be working correctly? Are you referring to the focus outline that appears around the "Home" link when you open the sidenav?

**Comment by robisim74** [comment]
Hi @mmalerba,

yes, the focus is always on the base path _Home_:

![image](https://cloud.githubusercontent.com/assets/14012361/25764457/28833f44-31e8-11e7-84c1-1fd2c65d8fce.png)


Steps:
- I open the menu
- I click on _Resources_
- I close the menu
- I reopen the menu: the focus is on _Home_ (blue border & grey background)

You can see this behavior also in the official Angular Material site:

![image](https://cloud.githubusercontent.com/assets/14012361/25764411/e32716e6-31e7-11e7-80cb-14f6b323171d.png)

Instead, the icon's focus was solved by version beta.3.

Thanks

**Comment by mmalerba** [comment]
I see, I'm not sure which is the correct item to focus from an accessibility standpoint (the first one or the current one) - I will look into that. The outline seems like a bug, you can fix it for now by adding this to your CSS:

```css
.mat-list-item { outline: none; }
```

**Comment by robisim74** [comment]
In my opinion always the current one, according to `routerLinkActive`. Thanks for the tip.
Greetings,
Roberto

**Comment by clark-stevenson** [comment]
Sorry guys I know this is closed, but I have been kicking a few tumbleweeds.

When I open my SideNav, the first `<a>` Item is selected. `mat-list-item-focus` class is applied to it.

Meanwhile, I have a `[routerLinkActive]` binding on one of these other `<a>` items which is setting an `active` class.  The end result is when I open my side nav, the `active` item is highlighted, and so is the first item in the list.

I am a newbie, and not straying far from basic usage, I thought it would be cool to add a clickable side nav which took mere seconds, but have spent a few evenings wondering how to fix it. I am sure I could figure out how to hide keyboard stuff....

I even seen a work around of adding a "hidden item" but it all seems a bit lame.

Can anyone point me to a fresh line of inquiry?
