### ISSUE TITLE
The cursor is reset when deleting from input type=number

### ISSUE THREAD

**Issue by ratherblue** [angular/material2#2227]
#### Bug, feature request, or proposal:
When using `<md-input type="number"></md-input>`, if you enter in a value like `12345`, then move the cursor to  the `2` and delete `2`, the `2` is deleted, but the cursor moves to after the `5`..

#### What is the expected behavior?
The cursor should stay in place

#### What is the current behavior?
The cursor moves to the end of the input value

#### What are the steps to reproduce?
1. Add `<md-input type="number"></md-input>` to a page, 
2. Type several numbers in the input 
3. Delete the values starting somewhere else than the end of the input value.
4. Notice that the cursor always moves to the end of the input value instead of staying in place

http://plnkr.co/edit/hVdzTFK7pX3vi5nvjunx?p=preview

#### What is the use-case or motivation for changing an existing behavior?
This is not how the native component works. It's very error-prone for any kind of number deletion. It also means you have to delete numbers one at a time which is fairly cumbersome.

#### Which versions of Angular, Material, OS, browsers are affected?
Latest

#### Is there anything else we should know?
It's happening due to `convertValueForInputType`. When it converts the value to a number it causes the input to update and the cursor to reset.

**Comment by crisbeto** [comment]
@ratherblue the `<md-input>` directive has been deprecated in `beta.0` If you use the newly-introduced `md-input-container`, this issue doesn't happen.
