### ISSUE TITLE
Md-Select style issue

### ISSUE THREAD

**Issue by ManishJainGitHubUser** [angular/material2#2229]
I am using latest version of material 2. Rel 11. 

I have applied below style to select.
   font-size: 30px;
    padding: 12px;
    margin: 12px;
  
which misaligned values inside control (see screenshot). Upon digging into styles of control, found out that
.md-select-trigger setting up height: 30px

I tried to modify height with 
  height: 50px; or with important but it didn't work.

Any ideas how to fix this ?

Thanks,
Manish

![image](https://cloud.githubusercontent.com/assets/1090670/21209124/49000ab2-c227-11e6-9176-2bcd244c5aa3.png)

**Comment by kara** [comment]
@ManishJainGitHubUser  Thanks for reporting. We do plan to adjust the height of the select based on font size - see existing issue [here](https://github.com/angular/material2/issues/2127).
