### ISSUE TITLE
Autoprefixer build

### ISSUE THREAD

**Issue by Thommas** [angular/material2#2230]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?

Material2 should be compatible with iOS8+ (two latest version of iOS right?) but some autoprefixed css rules are missing (especially flexbox).

#### What is the current behavior?

If you look at the source code, in node_modules/@angular/material/toolbar/toolbar.js for instance:
```
   MdToolbar = __decorate([
   ...
   styles: ["md-toolbar { display: flex; box-sizing: border-box;... flex-direction: column ...
   ...
```
The css is inlined **without** the autoprefixed CSS rules.

#### What is the use-case or motivation for changing an existing behavior?

With autoprefixer installed, angular-cli autoprefixes our SCSS code inside our src components.
But material2 components are not processed.
My guess is that webpack bundles the material2 .js directly with the CSS inlined, so it's never going to fix the CSS rules.

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.3.0
Material alpha11
ios7+ safari

#### Is there anything else we should know?

The hotfix right now is to manually edit those .js files and add the correct CSS rules but this is too time consuming so we're not even doing it.

**Comment by crisbeto** [comment]
If you take a look at the readme, it states that "Angular Material supports **the most recent two versions** of all major browsers". The two most recent versions of iOS Safari are 10 and 9.

**Comment by Thommas** [comment]
My bad.

We use browserstack to test and ios8 and 9 are accessible on iPhone5/6. That's why we were worried.

The conclusion is that these CSS rules won't be fixed ?
Material2 will always be broken on safari iOS8 ?

https://developer.apple.com/support/app-store/

OK so at worse 8% of our users won't be able to display the app. And it should resorb in the next 3 to 6 months so no worry.

I think you can close this.

Thank you for your feedback.
