### ISSUE TITLE
Touch action incorrect for swipe gesture

### ISSUE THREAD

**Issue by code-tree** [angular/material2#2231]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`touch-action: pan-y` when `(swipeleft)='something()'`

#### What is the current behavior?
`touch-action: none`

#### What are the steps to reproduce?
http://plnkr.co/edit/x8rl6HY88JbMWbJzwVbv?p=preview

Inspect the div element and you'll see the value of touch-action.

#### Which versions of Angular, Material, OS, browsers are affected?
bac0388ca323efcf860b3b28cd40267c15a9a85a

#### Is there anything else we should know?
This breaks scrolling, so not good!
Angular's default gesture config also seems to contain this bug.
Using Hammer's default config fixes this issue.

**Comment by code-tree** [comment]
I've had to set `pan-y` globally for the Hammer manager to get around this issue. Any ideas on an actual solution?

**Comment by jelbourn** [comment]
I believe this is a bug for https://github.com/angular/angular/ ; we don't specify `touch-action` anywhere in Material at time of this writing.
