### ISSUE TITLE
md-sidenav containing md-list and md-tab height issue

### ISSUE THREAD

**Issue by StephaneMourgues** [angular/material2#2237]
#### Bug, feature request, or proposal:
If in a md-sidenav you put a md-list with an item containing a md-tab-group, when the content of the tab is too long the tabs are moved up above other components.

#### What is the expected behavior?
The tabs should stay in place and their content should grow downards.

#### What is the current behavior?
The tabs are pushed up, above other components. The longer the content, the higher they go.

#### What are the steps to reproduce?

open this plunker
https://plnkr.co/edit/Uo9B6E1ccVpVBT6vB2Nv?p=preview
Click on open to open the sidenav then click on tab1 and tab2 to see how the different content of the tabs pushes up the tab-group. The tabs should always be under the heart icon.

#### Which versions of Angular, Material, OS, browsers are affected?
    @angular 2.2.4
    @angular/material 2.0.0-alpha.11-3
Chrome 55

**Comment by jelbourn** [comment]
List items really aren't meant to contain tabs. This issue is probably obsolete now, but I'd recommend structuring your content differently.
