### ISSUE TITLE
Allow color binding

### ISSUE THREAD

**Issue by mtrdp642** [angular/material2#2239]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
For the components that support the 'color' attribute, allow binding to the color attribute.

#### What is the current behavior?
Binding the color attribute to a variable results in:

`Can't bind to 'color' since it isn't a known property of [component].`

#### What are the steps to reproduce?
Plunker template: http://plnkr.co/edit/pdP6neVhJndQPPlfriiM?p=preview

#### What is the use-case or motivation for changing an existing behavior?
In my application, I have a long running http call that monitors the progress of a job, which is reported to the user with a md-progress-circle. The job is user-cancellable with the click of a button, but since the job can take time to actually cancel, it would be nice to have the progress circle change color on button click to the 'accent' or 'warn' values of the theme in the meantime.

#### Which versions of Angular, Material, OS, browsers are affected?
All

#### Is there anything else we should know?
My plunkr is specific to the md-progress-circle, but if decided to implement this, this should be extended to other controls such as buttons, md-progress-bar, toolbar, etc.

**Comment by belev** [comment]
You can do this by binding `color` through `attr`. Instead of using `[color]='progCircleColor'` you can use `[attr.color]='progCircleColor'` which will work: [updated plunker](http://plnkr.co/edit/zaGeOuztHUxaXcyuaxVf?p=preview).

**Comment by mtrdp642** [comment]
Perfect, forgot about `attr`! Thank you.
