### ISSUE TITLE
style is not applied to all the components

### ISSUE THREAD

**Issue by daniele-zurico** [angular/material2#2247]
#### Bug, feature request, or proposal:
Hi I'm using angular cli (scss) I added angular material but for some reason the css is not applied to all the component. For example the button don't take the primary color 

<img width="441" alt="screen shot 2016-12-15 at 16 31 23" src="https://cloud.githubusercontent.com/assets/3193095/21247424/291a4150-c2e4-11e6-8158-af408fb4a7fb.png">

As you can see the select and the input take the style but not the button
In my style.scss I did:
@import '~@angular/material/core/theming/prebuilt/deeppurple-amber.css';

And in my mainmodule:
```
MaterialModule.forRoot(),
```

#### What is the expected behavior?
The css is applied to all the material component

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://github.com/daniele-zurico/table-order

#### Which versions of Angular, Material, OS, browsers are affected?

^2.0.0-alpha.11-3

**Comment by andrewseguin** [comment]
Your main module uses forRoot which will give your app all the service provider dependencies for material, but that will not provide the components to every module in your app.

Your `PersonInputModule` includes HTML that uses two components: `md-input` and `md-button`. To use these in this module, you must import them. You correctly imported `MdInputModule` but did not import `MdButtonModule`. That is why the button seems to lack the styling.

To fix your issue, simply import  `MdButtonModule` in  `PersonInputModule`.
