### ISSUE TITLE
Bug - select not firing change event

### ISSUE THREAD

**Issue by mmrath** [angular/material2#2248]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
(change) should be fired when value of select is changed manually 

#### What is the current behavior?
(change) is not fired

#### What are the steps to reproduce?
This plunker reproduces the issue
https://plnkr.co/edit/MyhgEgH4SzFJs7aoJtzy?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Latest all

**Comment by kara** [comment]
@mmrath  There is no change event in the select's API at the monet. If you'd like to know when the value changes, you can use the standard `valueChanges` event from @angular/forms.

**Comment by Ploppy3** [comment]
@kara Hello, does it support optgroup already?
