### ISSUE TITLE
Proposed feature: md-ticker

### ISSUE THREAD

**Issue by NateMay** [angular/material2#2254]
I've created a ticker directive [PLUNKR](https://embed.plnkr.co/4mBHkIVTetC0kh34JOyT/)

I'd love improve this and bring this to the Material2 community, but I'm not sure what requirements there are. How can I get started?

**Comment by andrewseguin** [comment]
Unfortunately the material design spec does not account for a ticker so we would be unlikely to add it into our official collection of components. However, feel free to release this as a separate package in your own repo that others can use to install and import into their apps.
