### ISSUE TITLE
md-input-container is not working

### ISSUE THREAD

**Issue by ush189** [angular/material2#2263]
Hi, 

I just npm installed material. In my package.json this version is stated: "@angular/material": "^2.0.0-alpha.11-3"

When I try using the `md-input-container` as it is described here (https://github.com/angular/material2/blob/master/src/lib/input/README.md), I get this error message: 

```
zone.js:388Unhandled Promise rejection: Template parse errors:
'md-input-container' is not a known element
```

However, when I use the deprecated `md-input` it works. 

So what's wrong? Do I need to use another version of @angular/material?

**Comment by Uniqen** [comment]
The 2.0.0-alpha.11-3 release does not include md-input-container. The docs has been updated for upcoming release. Use md-input/md-textarea until next release.

**Comment by ush189** [comment]
Ok, thanks for the quick answer.

**Comment by starksds** [comment]
How are we supposed to use this library if the documentation can't be trusted?

**Comment by CraigAOliver** [comment]
When viewing the documentation select the tag of the version you are interested in (the dropdown in top left corner of the code tabs contents)

Also when updating from an older version review the change log for breaking changes and new/changed features.
https://github.com/angular/material2/blob/master/CHANGELOG.md

Also please remember these are Alpha releases

**Comment by ashishsober** [comment]
when we started using <md-input-container>,when we do have a latest release.any idea

**Comment by ponmani** [comment]
@ashishsober I am using <md-input-container tag for angular material 2 beta release. But same error repeat. How can i start .Net core app

**Comment by EvgenStudent** [comment]
I solved same problem. I just imported "MdInputModule" from "@angular/material"
