### ISSUE TITLE
md-input-container doesn't work in child modules

### ISSUE THREAD

**Issue by agroupp** [angular/material2#2265]
#### Bug:
md-input-container

Gives following error "'md-input-container' is not a known element" when implemented in child component.

MaterialModule is imported in child module with no .forRoot()

Toolbar, buttons, TabGroup and RadioGroup works fine.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.2.3, Material 2.0.0-alpha.11-3

**Comment by crisbeto** [comment]
The `md-input-container` wasn't in `alpha.11-3`, but it should be in the next release. The readme currently reflects the components in `master`.

**Comment by benishak** [comment]
I'm using version 2.0.0-beta.8 but I also get the same error
