### ISSUE TITLE
Bug: md-input-container is missing on npm ('md-input-container' is not a known element...)

### ISSUE THREAD

**Issue by Igonato** [angular/material2#2267]
#### Bug:
`md-input-container` seems to be missing when installing the library with npm.
Tried versions 2.0.0-alpha.11-3 (latest on npm) and 2.0.0-alpha.11-2 (to match HEAD on master)

#### What is the expected behavior?
```
$ npm install @angular/material@2.0.0-alpha.11-3
...
$ grep 'md-input-container' node_modules/@angular/material/*.js
... stuff ...
$
```

#### What is the current behavior?
```
$ npm install @angular/material@2.0.0-alpha.11-3
...
$ grep 'md-input-container' node_modules/@angular/material/*.js

$
```

node v6.9.1, npm  v3.10.9

**Comment by crisbeto** [comment]
`md-input-container` hasn't been released yet, but it should be in the next version. The readme of the `input` component reflects the current state in `master`.

**Comment by Igonato** [comment]
Thanks. Good to know.

**Comment by Cleudi** [comment]
When can we expect a new version of material? I need a textarea for my project, and now the big question is if it is worth doing my own or wait for next release... 

Thanks in advance for some information... :)

**Comment by crisbeto** [comment]
Soon™

**Comment by Cleudi** [comment]
Hm... expected an answer which is a bit more... let' call it concrete... ;-)

**Comment by CraigAOliver** [comment]
In case you are not aware mdtextarea does exist in the current release

On Fri, 23 Dec 2016 1:42 am Cleudi <notifications@github.com> wrote:

Hm... expected an answer which is a bit more... let' call it concrete... ;-)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/angular/material2/issues/2267#issuecomment-268791959>,
or mute the thread

**Comment by william-mcmillian** [comment]
@crisbeto the documentation for md-input says that it is deprecated, and md-input-container should be used instead. Isn't this wrong?

**Comment by crisbeto** [comment]
It is correct, but the version that deprecates them hasn't been released yet.

**Comment by william-mcmillian** [comment]
Thanks crisbeto. Man, the Angular 1 Material docs combined with the name change of the node module to @angular/material and the documentation have really thrown us for a loop. Is there up to date documentation for the latest release version of Angular 2 Material?

**Comment by CraigAOliver** [comment]
You can view it within github by switching to the tag of the version you
are interested in (Github page top left corner select defaults to
Branch:master).

**Comment by crisbeto** [comment]
It's out now as a part of `beta.0`.

**Comment by Cleudi** [comment]
Wohooo, thanks for the christmas present! :)
