### ISSUE TITLE
Bug: Select doesn't have initial value when change detection set to onPush

### ISSUE THREAD

**Issue by goldenbearkin** [angular/material2#2269]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
should show the initial value set by form builder.

e.g.
````js
this.form = this.fb.group({
      name: 'angular',
      sex: 'F'
    });
````

#### What is the current behavior?
when change detection set to onPush, Select shows empty value.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://plnkr.co/edit/G8ueOSwYMCZTigydRHbs

**Comment by elvirdolic** [comment]
Have the same issue also with ngModel and template driven form

**Comment by DmitryEfimenko** [comment]
I believe this came back.
Here is [plunker showing it](http://plnkr.co/edit/Pfw3FIW90X1n1TY05EDP?p=preview)
Should I open a new issue?
