### ISSUE TITLE
Getting started guide does not work

### ISSUE THREAD

**Issue by kevmo314** [angular/material2#2270]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

The steps in the getting started guide work correctly.

#### What is the current behavior?

They do not. After reproduction steps below I get the following result: http://i.imgur.com/iuosDKT.png

The radio button does not select properly and no animations/ripples appear. Similar behavior with other directives.

#### What are the steps to reproduce?

```
npm install -g angular-cli
ng new some-project
cd some-project
npm install @angular/material
```

Edit `app.module.ts` to be the following:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { MaterialModule } from '@angular/material';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    MaterialModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Edit `app.component.html` to be the following:

```
<md-radio-group>
  <md-radio-button value="option_1">1</md-radio-button>
  <md-radio-button value="option_2">2</md-radio-button>
</md-radio-group>
```

Run `npm start`, open in browser.

#### Is there anything else we should know?

Does anyone else miss the good ol' days when you could just include a <script> tag. :\

**Comment by kevmo314** [comment]
Turns out it was because I forgot to add

```
@import '~@angular/material/core/theming/prebuilt/indigo-pink.css';
```

to `styles.css`. It would be nice if this were more prominent in the guide. I see the "Include the core and theme styles" step, however it would be nice if this code snippet were there too.

**Comment by mLaird** [comment]
@kevmo314 Thanks for the clue.  Yes, documentation could be much better.  They should also mention that indigo-pink is the only theme that works, at the moment.  I tried others listed in the prebuilt folder and they all broke the page - in varying ways.  Path is important.  In my case, the CSS file expression that worked is:
    
    @import '/node_modules/@angular/material/core/theming/prebuilt/indigo-pink.css';
