### ISSUE TITLE
md-input-container is missing

### ISSUE THREAD

**Issue by byrotron** [angular/material2#2271]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Install via npm the material version 2.0.0-alpha.11-3 and insert input component

#### What is the current behavior?

Error is thrown "md-input-container is not an angular component"

#### What are the steps to reproduce?

install app via angular-cli
install Material via npm
import material
copy/paste  code form below link
https://github.com/angular/material2/blob/master/src/lib/input/README.md
Error is thrown

#### What is the use-case or motivation for changing an existing behavior?

N/A

#### Is there anything else we should know?

Other modules are working correctly, once  installed I have noticed that the file "input-container.ts" is missing, along with all the other files pertaining to the input-container.

**Comment by crisbeto** [comment]
`md-input-container` isn't in alpha.11-3, but it should be in the next version.

**Comment by byrotron** [comment]
Thanks for the clarity. However, i still see an issue. When you install the package via npm, it does not reflect what is in the documentation. The other issue I find a little confusing, is that when I view the package.json it shows the version as alpha.11-2 which then includes the md-input-container.

**Comment by crisbeto** [comment]
That should be better once we have a docs site up and running. Currently the readme reflects whatever is in `master`.
