### ISSUE TITLE
md-select overlay not dismissed inside dialog

### ISSUE THREAD

**Issue by chpasha** [angular/material2#2272]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
if you open md-select inside md-dialog component and click somewhere outside of md-select overlay (but inside of dialog itself), the md-select overlay should be closed and onClose event should be fired

#### What is the current behavior?
now if you click inside dialog outside of md-select overlay, overlay is not closed. but if you click outside dialog overlay, it is closed 

#### What are the steps to reproduce?
http://plnkr.co/edit/oIJQsOZVt0aKRFPe9rde

actually it is never dismissed in plunker, and what is worse, the overlay of md-select is shown below dialog overlay. But in real world application I get the behaviour described above - md-select is dismissed when clicking outside overlay, but not if it is within dialog

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.2.4, material 2.0.0-alpha.11-3, ubuntu 14.04, Firefox 50.1, Chrome 55

**Comment by crisbeto** [comment]
Your Plunkr breaks because it's missing some CSS (e.g. the overlay isn't `position: absolute`), however there definitely is an issue with the backdrop not being over the dialog.

**Comment by fxck** [comment]
Yes, there needs to be a proper stacking manager. 

https://github.com/angular/material2/pull/1584#issuecomment-256601624
