### ISSUE TITLE
md-menu is not working (cause by: unknown mdMenuTriggerFor)

### ISSUE THREAD

**Issue by ThangLeQuoc** [angular/material2#2273]
I attempt to create a md-menu base on the Angular 2 Material document, code as follow

```
<!-- menu opens when trigger button is clicked -->
<button md-icon-button [mdMenuTriggerFor]="menu">
   <md-icon>more_vert</md-icon>
</button>

<md-menu #menu="mdMenu">
    <button md-menu-item> Refresh </button>
    <button md-menu-item> Settings </button>
    <button md-menu-item> Help </button>
    <button md-menu-item disabled> Sign Out </button>
</md-menu>
```

The template fail to parse, error log on the console indicate that: 

> Unhandled Promise rejection: Template parse errors:
> Can't bind to 'mdMenuTriggerFor' since it isn't a known property of 'button'. ("f="loggedIn">
>       
>       <button md-icon-button [ERROR ->][mdMenuTriggerFor]="menu">
>    <md-icon>more_vert</md-icon>
> </button>
> "): AppComponent@19:29 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:

Could you show me how to fix this ? Thank you

**Comment by HopScotch47** [comment]
The api for this has changed very recently. If you use the 11-3 version use md-menu-trigger-for instead

**Comment by ThangLeQuoc** [comment]
@HopScotch47 That's precisely cool and clean. Thank you very much. Now It work like a charm
