### ISSUE TITLE
Support template content for selected value in md-select

### ISSUE THREAD

**Issue by wouterbeukers** [angular/material2#2275]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Selected option of a md-select supports html-tags

#### What is the current behavior?
Selected option of a md-select doesn't supports html-tags

#### What are the steps to reproduce?
See http://plnkr.co/edit/QJUCobw9yFcu1l1WtpOR?p=preview
Open the md-select.
In the dropdown the option supports html tags
Select the option
All html tags are stripped of the shown value in the md-select.

**Comment by DougMoreira** [comment]
Use this to display the formatted html:
`<div [innerHtml]="selectedValue"></div>`

**Comment by wouterbeukers** [comment]
That isn't the issue. 
It is about the value what the md-selects shows after you select an option.
This value is stripped of al it's html-tags.

**Comment by negberts** [comment]
The html is stripped here:

get viewValue(): string {
    // TODO(kara): Add input property alternative for node envs.
    return this._getHostElement().textContent.trim();
}

I would love to change it, but I don't know what the impact will be. There's probably a reason why textContent is taken and not just value

**Comment by fxck** [comment]
@kara do you have something in mind regarding this? I would probably like to take a look at it..

**Comment by crisbeto** [comment]
I don't expect any issues with multi select since it'll use the same properly to get the text. I was actually considering giving this a shot in the next few days.

**Comment by andreasrueedlinger** [comment]
@crisbeto thanks for your PR. So I guess you intended that with this change you can add the "plain HTML" option as label as follows:
`<md-select-label [innerHtml]="select.selected?._getHostElement().innerHTML"></md-select-label>`

**Comment by crisbeto** [comment]
This is the intended usage @andreasrueedlinger:

```html
<md-select placeholder="Food" [formControl]="control" #select="mdSelect">
  <md-select-label>
    {{ select.selected?.viewValue }}
  </md-select-label>
  <md-option *ngFor="let food of foods" [value]="food.value">
    {{ food.viewValue }}
  </md-option>
</md-select>
```

**Comment by andreasrueedlinger** [comment]
@crisbeto but that does not fix the problem adressed in this issue, namely that the label does not support Html!

**Comment by crisbeto** [comment]
You can put any HTML you want inside the `md-select-label` element.

**Comment by fxck** [comment]
That's not what he meant I think. 

When you have..

```html
<md-option>
  <img src="whatever.jpg" /> Whatever
</md-option>
```

..and you select it, the selected value won't be `<img src="whatever.jpg" /> Whatever`, it will be stripped down to `Whatever`. He wants the original unstripped HTML to be there instead. I'm not sure if `{{ select.selected?.viewValue }}` does that?

**Comment by andreasrueedlinger** [comment]
But in your example you use normal binding and `viewValue` which returns the trimmed textContent, so no Html anymore.
My example:
```ts
<md-select placeholder="Feedback" [formControl]="control" #select="mdSelect">
  <md-select-label [innerHtml]="select.selected?._getHostElement().innerHTML"></md-select-label>
  <md-option value="good">
    <md-icon>thumb_up</md-icon> Nice!
  </md-option>
  <md-option value="bad">
    <md-icon>thumb_down</md-icon> Bad!
  </md-option>
</md-select>
```

**Comment by crisbeto** [comment]
That's true, but if we just dumped the `innerHTML` instead, we'd be opening the user up to XSS, in addition to the potential performance implications.

**Comment by fxck** [comment]
There should be a way straightforward to do it nevertheless. It's pretty limiting when you know the values are safe.

**Comment by fxck** [comment]
Also the way it works currently is that if I have..

```
<md-option><span class="in-a-circle-with-background-and-uppercase">un</span>User Name</md-option>
```

..the selected value will be `unUser Name`, which is pretty annoying..

**Comment by crisbeto** [comment]
You can still use `_getHostElement().innerHTML` as @andreasrueedlinger mentioned, but there are better ways to do the same (e.g. you could map images or icons to values in your component).

**Comment by andreasrueedlinger** [comment]
XSS should not be a problem since Angular sanitizes the input to `innerHtml` unless you explicitely allow (https://angular.io/docs/ts/latest/api/platform-browser/index/DomSanitizer-class.html)

**Comment by ermarkar** [comment]
support for multiple selection ?

**Comment by fxck** [comment]
Good thing is that I think this could be used for https://github.com/angular/material2/pull/2722#issuecomment-277622084

**Comment by Toub** [comment]
Is there any workaround with 2.0.0-beta.3 ?

**Comment by fxck** [comment]
@Toub still waiting for https://github.com/angular/material2/pull/3341

**Comment by matte00** [comment]
Any news about this?

**Comment by negberts** [comment]
An updated plunker for the problem can be found here: http://plnkr.co/edit/vuF3Pz7UHDXERXZbtiIK?p=preview

**Comment by mladilav** [comment]
Any news about this?

**Comment by sdargaud** [comment]
As a dirty workaround I am currently using somehting along those lines :
```
<md-select placeholder="Feedback" [formControl]="control" #select="mdSelect">
  <md-option value="good">
    <md-icon *ngIf="select.panelOpen">thumb_up</md-icon> Nice!</md-icon>
    <div *ngIf="!select.panelOpen">Nice!</div>
  </md-option>
</md-select>
```

At least I don't have "thumb_up Nice!" displayed and can work with it until it's fixed (be aware, it does seem to take some time to evaluate the template when opening the select, and the raw html is shown for a short period of time).

**Comment by LayZeeDK** [comment]
For future reference, you can use the [`<mat-select-trigger>`](https://material.angular.io/components/select/overview#customizing-the-trigger-label) to change the display of the selected value.

It was added by @crisbeto in Angular Material version 2 beta 10.
