### ISSUE TITLE
Semantic Versioning of pre-release tags

### ISSUE THREAD

**Issue by paumayr** [angular/material2#2278]
#### Proposal:
Switch to dot separator for pre-release version numbers. (e.g. alpha.11.2 instead of alpha.11-2)

#### What is the expected behavior?
Expected behavior would be that "@angular/material": "^2.0.0-alpha.11-2" does not install alpha.9-3, but alpha.11-2 (at the time of this writing). 
According to http://semver.org/ §11:
"Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal."

#### What is the current behavior?
Updating from one alpha to another fails, because the pre-release tag uses a scheme like
alpha.9-1 alpha.9-2 etc.
alpha.11 alpha.11-1 alpha.11-2

in packageJson, "@angular/material" : "^2.0.0-alpha.9-3" is stuck at alpha.9-3 because "alpha.11-1" is compared alpha-numerically, and is therefore smaller than "alpha.9-3".

#### What are the steps to reproduce?
create new project with a package json, add a dependency to "@angular/material" : "^2.0.0-alpha.11-2", call npm install. It will install alpha.9-3 instead.

#### What is the use-case or motivation for changing an existing behavior?
Easier upgradabiltiy.
#### Which versions of Angular, Material, OS, browsers are affected?
anything after angular material 9-3.

#### Is there anything else we should know?
I know this will be hard to change while in alpha, as alpha.9-3 is out there and numeric identifiers always have lower precedence than non-numeric identifiers, but it can be changed when switching to beta.

So i think, beta versioning should be, e.g.,
2.0.0-beta.1.1 < 2.0.0-beta.1.2 < 2.0.0-beta.2.1 < ... < 2.0.0-beta.9 < 2.0.0-beta.11 < 2.0.0-beta.11.2 
notice: dots instead of hyphens to make sure they are compared numeric.

**Comment by jelbourn** [comment]
Moving forward we won't be releasing any more dashed versions (it will always be beta.3, beta.4, etc.).
