### ISSUE TITLE
It is not possible to set the Height of the first <md-toolbar-row>

### ISSUE THREAD

**Issue by AsherBarak** [angular/material2#2279]
#### Bug, feature request, or proposal:
Bug

First <md-toolbar-row> is created automatically so there is no way to apply styles to it. Height is set to 64px in CSS. 
I want to have the height of the toolbar fit it's content and cannot seem to find a way.

Maybe create first <md-toolbar-row> only if no row elements are explicitly created? This also seems to create a more unified UX.

**Comment by DevVersion** [comment]
Yeah, this is a good point. We already have an issue for that one. See #1718
