### ISSUE TITLE
Disable screenshot capture and delete existing screenshots

### ISSUE THREAD

**Issue by RichOren** [angular/material2#228]
When I fork this repo it is detecting changes to the PNG files and wanting me to commit those files and then it just keeps adding them to my staged list. Do these really need to be version controlled? Can they be ignored?

**Comment by DevVersion** [comment]
@RichOren I have the same problem. Removing / discarding them isn't working, seems like `Git LFS` always recreates them.

**Comment by RichOren** [comment]
@DevVersion - Confirmed that is what is happening to me also.

**Comment by jelbourn** [comment]
@robertmesserle we should remove the screenshot running from the repo for now, since we're not really getting any value from it.

**Comment by robertmesserle** [comment]
@jelbourn Agreed, I'll submit a PR.

**Comment by DevVersion** [comment]
Meanwhile, #232 is pending, I deleted all contents of `.git/lfs/`, otherwise I'm not able to switch branches.
