### ISSUE TITLE
'md-sidenav-container' is not a known element:

### ISSUE THREAD

**Issue by axtlotic** [angular/material2#2282]
#### Bug, feature request, or proposal:
'md-sidenav-container' is not a known element:

#### What is the expected behavior?
View a side nav, using md-sidenav-container

#### What is the current behavior?
error: 'md-sidenav-container' is not a known element:

#### What are the steps to reproduce?
replace md-sidenav-layout with md-sidenav-container

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/S33OfZpzdz4r0fvA2fgF?p=preview

#### What is the use-case or motivation for changing an existing behavior?
documentation says md-sidenav-layout is deprecated

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-alpha.11-3

**Comment by belev** [comment]
@axtlotic It looks like this didn't end up in the release. No message in the [Changelog](https://github.com/angular/material2/blob/master/CHANGELOG.md). Also looking at the code after fresh npm install of version 2.0.0-alpha.11-3 and there `md-sidenav-layout` is used. So for now I think you can't use `md-sidenav-container` and you should stick to the old `md-sidenav-layout`.

**Comment by hans-pragt** [comment]
The documentation also appears to be ahead of the released package in the various dialog containers, as well as `md-input-container`.

**Comment by fxck** [comment]
the documentation you see in this repo is obviously from master, if you want docs for whatever is currently released, browse files at that point https://github.com/angular/material2/tree/0a9ba8bf9230ceb21ee76aa4828d62f7bcdf107b

**Comment by hans-pragt** [comment]
Right, and I think the docs being kept up-to-date is awesome, but if you look at it from the perspective of someone who followed a link from the README on the main page, it may be a little confusing. Note that even if you go to the README from the document at the point in time you link to and follow any of the links to the components, you end up on master again.

**Comment by crisbeto** [comment]
Now that beta is out, this shouldn't be an issue anymore.
