### ISSUE TITLE
md-date-picker

### ISSUE THREAD

**Issue by jlno** [angular/material2#2284]
The commit `https://github.com/angular/material2/pull/1903/commits/de39d24ca8e7008c7331919272e7d63e98aded75` not work on project `material2` after setup in app module, console says:
> Unhandled Promise rejection: Template parse errors:
> Can't bind to 'value' since it isn't a known property of 'md-input'.
> 1. If 'md-input' is an Angular component and it has 'value' input, then verify that it is part of this module.
> 2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

**Comment by fxck** [comment]
that pull request was closed and was from an external contributor, why do you expect it to work?

**Comment by jlno** [comment]
Resolved in my [repository](https://github.com/jlno/material2).
<img src="https://i.imgur.com/Wk9UzEl.png">
