### ISSUE TITLE
After update to alpha 11-3 'md-input-container' is not a known element

### ISSUE THREAD

**Issue by bkarv** [angular/material2#2285]
#### Bug, feature request, or proposal:
After upgrading to 2.0.0-alpha.11-3 and trying to implement md-input-container as per the md-input readme in my template html eg,
<md-input-container>
  <textarea md-input></textarea>
</md-input-container>

I get an an error 'md-input-container' is not a known element. I use Angular CLI 1.0.0-beta.22-1 and angular 2 - 2.2.3

#### What is the expected behavior?
No errors allows me to use md-input-container 

#### What is the current behavior?
'md-input-container' is not a known element

#### What are the steps to reproduce?
Below is  my module.ts and package.json file. I followed instructions as well be deleting the material folder in @angular. And then running npm install --save @angular/material in the terminal. 

Also I currently do not import md-input-container into my component as it has not been a requirement.  Could this be this the reason for the error?

**app.module.ts**
```
// Core
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { routing } from './app.routing';
// Plugins
import { MaterialModule } from '@angular/material';

@NgModule({
  declarations: [
    AppComponent
  ],
  entryComponents: [
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    routing,
    MaterialModule.forRoot()
  ],
  providers: [AUTH_PROVIDERS],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
**Package.json**
```
{
  "name": "todo1",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/material": "^2.0.0-alpha.11-3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/router": "3.2.3",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "tslint": "^4.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.2.3",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.22-1",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3",
    "webdriver-manager": "10.2.5"
  }
}

```

**Comment by HopScotch47** [comment]
This change is only in the master branch which is not released yet.
Change your view to the tag: 2.0.0-alpha.11 in order to see the code/documentation that is in line with that.

**Comment by bkarv** [comment]
I thought because it was stated in the readme it was released. Good thought it was something I was doing.
