### ISSUE TITLE
@angular/material doesn't pass strictNullChecks

### ISSUE THREAD

**Issue by pdavin** [angular/material2#2287]
#### Bug, feature request, or proposal:
Can you consider enabling strictNullChecks (https://www.typescriptlang.org/docs/handbook/compiler-options.html) for the Material code?  

Currently there are null check errors in Material which prevent us from enabling strictNullChecks on our AoT (ngc compiled) build. We can still run strict null checks on our dev build (non-AoT), so it's not a complete blocker, but it would be good if Material passed strictNullChecks too.

#### What is the current behavior?

src/ngfactory/src/app/app.module.ngfactory.ts(419,42): error TS2345: Argument of type 'MdGestureConfig' is not assignable to parameter of type 'HammerGestureConfig'.
  Types of property 'buildHammer' are incompatible.
    Type '(element: HTMLElement) => HammerManager' is not assignable to type '(element: HTMLElement) => HammerInstance'.
      Type 'HammerManager' is not assignable to type 'HammerInstance'.
        Types of property 'off' are incompatible.
          Type '(events: string, handler?: HammerListener | undefined) => void' is not assignable to type '(eventName: string, callback: Function) => void'.
            Types of parameters 'handler' and 'callback' are incompatible.
              Type 'Function' is not assignable to type 'HammerListener | undefined'.
                Type 'Function' is not assignable to type 'HammerListener'.
                  Type 'Function' provides no match for the signature '(event: HammerInput): void'

#### What are the steps to reproduce?

Build an Angular 2 app including Material with ngc.

The line of code triggering the error is: 
      new import102.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_55)

Note this may not be the only error though, because strictNullChecks typically doesn't emit all offending lines, it just emits the first one it encountered. 

#### What is the use-case or motivation for changing an existing behavior?

Better coding practices. 

#### Which versions of Angular, Material, OS, browsers are affected?
    "@angular/material": "^2.0.0-alpha.10",
    "hammerjs": "^2.0.8",
    "@types/hammerjs": "^2.0.33",

**Comment by crisbeto** [comment]
Closing this and will continue tracking on https://github.com/angular/material2/issues/3465.
