### ISSUE TITLE
MdRadio when page has scrollbar, clicking / checking a radio button scrolls page

### ISSUE THREAD

**Issue by ashishsajwan** [angular/material2#2294]
#### Bug
When the page has a scrollbar and a MdRadio element, then clicking on the radio buttons scrolls the page.

#### What is the expected behavior?
on clicking, it should just mark the radio button selected and not scroll the page in any way

#### What is the current behavior?

currently, it scrolls the page and sometimes the page gets blank.

**Comment by wallace41290** [comment]
I am also experiencing this issue on beta.1.

**Comment by jelbourn** [comment]
I haven't been able to reproduce this. Feel free to open a new issue with additional information or a reproduction.
