### ISSUE TITLE
Slider doesn't work with (input) event

### ISSUE THREAD

**Issue by lelezeus88** [angular/material2#2296]
#### Bug, feature request, or proposal:
Given a simple slider, it does not call "myFunction" subscribed to (input) event :
<md-slider #mySlider min="0" max="100" (input)="myFunction(mySlider.value)"></md-slider>

Then if I subscribe to (change) event it works and it triggers the function at the end of sliding:
<md-slider #mySlider min="0" max="100" (change)="myFunction(mySlider.value)"></md-slider>

The problem is that I need to call "myFunction" each step of slider and this is possible only subscribing to (input) event.

#### What is the expected behavior?
The expected behaviour should be that if I subscribe "myFunction" to (input) event,  "myFunction" get called each step.

#### What is the current behavior?
At the moment "myFunction" is not triggered

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/material": "2.0.0-alpha.10",

**Comment by DevVersion** [comment]
The `input` event is not developed yet. Working on a PR for this.

**Comment by alexjlockwood** [comment]
+1 this would be great!
