### ISSUE TITLE
Password field contents shown in page HTML

### ISSUE THREAD

**Issue by simpss** [angular/material2#2302]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Password field values are only kept in memory and not shown anywhere by default.

#### What is the current behavior?
Password field values are added to the DOM with attribute `ng-reflect-model`

#### What are the steps to reproduce?
Create an input with `[type]="'password'"`.  
Write something to the input field.  
Find the generated input field from HTML and check the `ng-reflect-model` attribute.  
http://plnkr.co/edit/d7zAz3quuyYXMLqbbqTn?p=preview
![screenshot](https://cloud.githubusercontent.com/assets/6879043/21369796/427525b2-c711-11e6-9380-1a86b6df3b99.png)

#### What is the use-case or motivation for changing an existing behavior?
Having password values inside the html adds an attack vector.  
An example:  
1. browser autofills the field.
2. user is told to do 'Save Page As' for debugging purposes.
3. the password field content is saved together with the page HTML.

#### Which versions of Angular, Material, OS, browsers are affected?
material: 2.0.0-alpha.11-3 (all versions are probably affected)
browser: firefox 45.4.0
OS: debian jessie 8

#### Is there anything else we should know?
I know the ng-reflect-model attribute is needed for the input to work at the moment, but even as a developer I was surprised when my saved password showed up in the page inspector when debugging code with another developer.

If there is any way to make it work without that attribute I think it should be at least evaluated.

**Comment by crisbeto** [comment]
This is how Angular works, it's not something that Material has control over. One thing to note though: if the user knows how to use the dev tools, they can do the same by changing the input type from `password` to `text`. Also this probably gets removed if you're running the app in prod mode.

**Comment by simpss** [comment]
the point is, when the user changes the type from password to text they have to do something explicit to unmask the password.  
At the current state, it is shown by default. 

Anyway, I checked when running the app in production mode, the attribute is indeed hidden. :+1:
