### ISSUE TITLE
md-select wrong style when inside an invalid form

### ISSUE THREAD

**Issue by HopScotch47** [angular/material2#2304]
#### Bug, feature request, or proposal:
Bug. 

#### What is the expected behavior?
The select control should prioritize its own valid flag over the form's invalid flag

#### What is the current behavior?
ng-select shows invalid state if the form is marked as ng-invalid even when the select itself has the ng-valid class

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker: http://plnkr.co/edit/wLkZWMBZs0gngUmkMJHn?p=preview
I fudged the classes to simplify the plunkr

#### Which versions of Angular, Material, OS, browsers are affected?
I noticed this on 11-3 but I believe the plunkr uses the master version which still has this behaviour

**Comment by kara** [comment]
This was fixed in https://github.com/angular/material2/pull/2166.  It's fixed in master (the plunker actually points to the last release on npm).
