### ISSUE TITLE
Move umd bundles into `bundles/` dir in npm package

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#2308]

**Comment by fredrikredflag** [comment]
@jelbourn Don't know if this should be a separate issue, but could the .umd.js files get read permissions for everyone in the npm package?

**Comment by philipooo** [comment]
Looks like the [package.json](https://github.com/angular/material2/blob/master/src/lib/package.json#L5) does not reflect this change.

      "main": "./material.umd.js",

should be

      "main": "./bundles/material.umd.js",
