### ISSUE TITLE
md-slider doesn't work correctly in the Safari browser

### ISSUE THREAD

**Issue by vertinskydv** [angular/material2#2322]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
drag&drop action move md-slider-track-fill and md-slider-thumb.

#### What is the current behavior?
drag&drop action move only md-slider-track-fill.

#### Which versions of Angular, Material, OS, browsers are affected?
Mac os Siera, Safari 10,
Material: 2.0.0-alpha.11-3,
Angular: 2.1.1

![slider](https://cloud.githubusercontent.com/assets/17768605/21390315/6b3d13a2-c797-11e6-829c-c1463026d30b.jpg)

**Comment by crisbeto** [comment]
I couldn't reproduce it with Safari 10.0, can you post a Plunkr? You can use this one as a base: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by SlavaSelivonchyk** [comment]
I even can't run your example in Safari, cause faced with CORS issue. One of errors:
XMLHttpRequest cannot load http://unpkg.com/@angular/http/bundles/http.umd.js. Cross-origin redirection denied by Cross-Origin Resource Sharing policy.

**Comment by crisbeto** [comment]
Try this https://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=info

**Comment by vertinskydv** [comment]
Slider works correctly after version updates

![a8630-clip-13kb](https://cloud.githubusercontent.com/assets/17768605/21482472/82d470a4-cb85-11e6-9ceb-ee1609288221.png)
