### ISSUE TITLE
Incorrect extra number of overlays with multiple dialog

### ISSUE THREAD

**Issue by guojenman** [angular/material2#2324]
#### What is the expected behavior?
When instantiating multiple dialogs, there should be only one overlay and update it's z-index so that it's over the previous dialog

#### What is the current behavior?
One overlay is create for each dialog and all of the z-index are always 1 so that it never hides the previous still opened dialog

#### What are the steps to reproduce?
http://plnkr.co/edit/hQKwfp?p=preview

click open modal 1 on main app + click open modal 2 in opened dialog
1. you can still interact with dialog 1
2. you see the overlay darken because there are now 2 overlays

#### What is the use-case or motivation for changing an existing behavior?
1. By creating a new overlay for each opened dialog, it darkens then look of the overlay for each on that is opened
2. Should not be able to interact with dialog 1 until dialog 2 is closed, currently you can still click on "open modal 2" from dialog 1 which keeps creating dialog 2s and overlay keeps getting darker and darker for each overlay instantiated

#### Which versions of Angular, Material, OS, browsers are affected?
Material: 2.0.0-alpha.11-3 
Angular: All

**Comment by crisbeto** [comment]
I'm not sure I agree that only one dialog should be open at a time. That being said, the backdrop stacking issues should be solved with https://github.com/angular/material2/pull/2276

**Comment by guojenman** [comment]
@crisbeto I'm not advocating for one dialog at a time. Overlay stacking described in #2276 may be close to what I'm saying, though after cloning from master and running "gulp build:components" and rebuilding my app to use that version, I see no difference with the overlays in my dialogs (2 opened sequentially and left opened)

1. both overlays were still under both dialogs
2. because there were two overlays, they looked darker

IMO, both of these behavior are not correct. Maybe I'm not building from source correctly to see the change?

**Comment by crisbeto** [comment]
Here's what it looks like for me on master @guojenman:

![1](https://cloud.githubusercontent.com/assets/4450522/21417750/6549f08a-c825-11e6-8949-f2e5704f8372.png)

Regarding the overlays looking darker, I think that my example illustrates why it's necessary: when you have multiple dialogs and one doesn't overlap the other completely, you need some kind of indication that the lower one isn't clickable (hence the darkening). It might make sense to have a config option to be able to disable it, though.

**Comment by guojenman** [comment]
@crisbeto your build looks like the right behavior. Thank you.
