### ISSUE TITLE
md-tooltip eats the button click on mobile

### ISSUE THREAD

**Issue by eslammahgoub** [angular/material2#2326]
#### Bug, feature request, or proposal:
Bug
Same as [issue in material 1](https://github.com/angular/material/issues/6792)

#### Which versions of Angular, Material, OS, browsers are affected?
tested in ipad

**Comment by doorman02** [comment]
Hello, is this fix part of the new beta2 release?

**Comment by DevVersion** [comment]
Nope. It hasn't been merged yet.

**Comment by doorman02** [comment]
Can I replace the tooltip.ts and features.ts files manually until the merge is done? 
Right now I need to have two versions of most of my buttons one for mobile and another one with tooltip for desktop.
