### ISSUE TITLE
Dialog not working (template fail to parse <md-dialog-actions>)

### ISSUE THREAD

**Issue by ThangLeQuoc** [angular/material2#2346]
I attempt to create md-dialog base on the turtorial.
However, I was unable to parse the template.
The dialog template:
```
<h1 md-dialog-title>Would you like to order pizza?</h1>
  <md-dialog-actions>
    <button (click)="dialogRef.close('yes')">Yes</button>
    <button md-dialog-close>No</button>
  </md-dialog-actions>
```

Error on the console indicated that:

> Unhandled Promise rejection: Template parse errors:
> 'md-dialog-actions' is not a known element:
> 1. If 'md-dialog-actions' is an Angular component, then verify that it is part of this module.
> 2. If 'md-dialog-actions' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("<h1 md-dialog-title>Would you like to order pizza?</h1>

Is this cause by a recent change in the API ? Could you please show me how to fix this ? Thank you

**Comment by crisbeto** [comment]
The `md-dialog-actions` haven't been released yet, but they should be in the next release. It shows up in the examples, because the readme reflects the state of the code in master.
