### ISSUE TITLE
[Feat] Embed styles in components

### ISSUE THREAD

**Issue by Luchillo** [angular/material2#2349]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Be able to npm install from github, and use the components directly.

#### What is the current behavior?
In my case webpack complains for each component of material 2 where it requests for css files when they haven't been compiled from scss.

#### What are the steps to reproduce?

Install from github and just import any material 2 module in the app module (in my case the dialog module):

```sh
npm i -S git+https://github.com/angular/material2.git
```

#### What is the use-case or motivation for changing an existing behavior?
Testing the most recent version is impossible due to the need of the library to be compiled before being used, using directly from source should be possible without having to compile the `scss` files through a `sass` compiler, in my case i have the webpack's `sass-loader` taking care of those extensions.

#### Which versions of Angular, Material, OS, browsers are affected?
Most likely all when installed directly from github.

#### Is there anything else we should know?
I think either you tell the component to use the `scss` files and when built embed the compiled `css` into the component itself, or you keep the `css` compiled version committed to github to be able to use the source directly.

I'm using webpack with `awesome-typescript-loader`, `angular2-template-loader`, `sass-loader` to embed the css in the angular component, that's why i think it's better to embed the css instead of making those components trigger a stylesheet download, as my styles are embedded i don't have any `css` files in my production build.

**Comment by clydin** [comment]
give "angular/material2-builds" a try.

**Comment by Luchillo** [comment]
Ok where to go then? is that an npm package?

**Comment by clydin** [comment]
GitHub repo for material builds synced with master

**Comment by Luchillo** [comment]
Btw i have noticed some weird thing, with `npm show @angular/material` i can se the version `2.0.0-alpha.11-3` but the one in both `material 2` and `material2-builds` reference the `2.0.0-alpha.11-2` version, what's going on here?

**Comment by jelbourn** [comment]
The css has been inlined into the components for quite a long time now. Looking at the latest package (beta.1), everything still seems to be correctly inlined.

**Comment by Luchillo** [comment]
@jelbourn Have you tried installing from github directly? i can't test right now so i'll like to know if it worked for you when trying directly from github repo.

**Comment by jelbourn** [comment]
The inlining is a build step that's only run when performing a release (`gulp build:release`).
