### ISSUE TITLE
size tabs scroll

### ISSUE THREAD

**Issue by niveo** [angular/material2#2352]
**when scroll is activated tab don't resize**

`for(let i = 0; i < 100;i++){this.tabs.push({id: i,descricao: 'Terrible sushi restaurants - ' + i});}`

`<md-tab-group [(selectedIndex)]="selectedIndex">
<md-tab *ngFor="let tab of tabs">
    <template md-tab-label>
        <md-icon>person</md-icon>
        <span>{{tab.descricao}}</span>
        <md-icon>close</md-icon>
    </template>
    <h1>Terrible sushi restaurants</h1>
    <p>...</p>
</md-tab>
</md-tab-group>`

![image](https://cloud.githubusercontent.com/assets/5286878/21436021/ac3680d8-c863-11e6-93a3-96eee4beb754.png)

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate further

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
