### ISSUE TITLE
listLazyRoutes is undefined

### ISSUE THREAD

**Issue by jlno** [angular/material2#2353]
Console says `Cannot read property 'listLazyRoutes' of undefined` in my new project made by cli.

**Comment by Ron537** [comment]
I had the same issue.
Updating to `"angular-cli": "1.0.0-beta.24"` fixed the problem.
I think this bug is related to angular-cli itself and not to @angular/material.

An issue is already submitted to angular-cli's repository : 
https://github.com/angular/angular-cli/issues/3662
