### ISSUE TITLE
feat: @angular2-material/all

### ISSUE THREAD

**Issue by gdi2290** [angular/material2#236]
it would be great if we had `@angular2-material/all` that also exported `MATERIAL_DIRECTIVES` and `MATERIAL_PROVIDERS`. At the moment, you need to require everything manually

```typescript
import {MD_SIDENAV_DIRECTIVES} from '@angular2-material/sidenav';
import {MdToolbar} from '@angular2-material/toolbar';
import {MdButton} from '@angular2-material/button';
import {MdCheckbox} from '@angular2-material/checkbox';
import {MdRadioButton} from '@angular2-material/radio';
import {MdSpinner} from '@angular2-material/progress-circle';
import {MD_CARD_DIRECTIVES} from '@angular2-material/card';
const MATERIAL_DIRECTIVES = [
  ...MD_SIDENAV_DIRECTIVES,
  ...[ MdToolbar, MdButton, MdCheckbox, MdRadioButton, MdSpinner ],
  ...MD_CARD_DIRECTIVES
];
```
```json
  "dependencies": {
    "@angular2-material/button": "^2.0.0-alpha.1",
    "@angular2-material/card": "^2.0.0-alpha.1",
    "@angular2-material/checkbox": "^2.0.0-alpha.1",
    "@angular2-material/core": "^2.0.0-alpha.1",
    "@angular2-material/progress-circle": "^2.0.0-alpha.1",
    "@angular2-material/radio": "^2.0.0-alpha.1",
    "@angular2-material/sidenav": "^2.0.0-alpha.1",
    "@angular2-material/toolbar": "^2.0.0-alpha.1",
    "angular2": "2.0.0-beta.12",
    "core-js": "^2.1.5",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.6"
  },
```

**Comment by naveedahmed1** [comment]
I believe both options should be supported, i.e 

`import all MATERIAL_DIRECTIVES and MATERIAL_PROVIDER`
Good for the projects utilizing all/most of the directive/providers

`import specific MATERIAL_DIRECTIVES and MATERIAL_PROVIDER`
Good for projects utilizing only specific directives

May be more option could be given by grouping related directives:

`@angular2-material/all`
import all directives

`@angular2-material/form-directives`
import form related directives such as input, checkboxes, radio, slide toggle, select etc.

`@angular2-material/ui `
import ui related directives related directives such as side nav, menu, list, dialog, tabs etc.

**Comment by m0t0r** [comment]
@jelbourn this issue seems ready to be closed as #950 exports `all` module.

**Comment by itrethan** [comment]
Can you please release the @angular2-material/all to npm repo? The code is there but it's not available in npm.

**Comment by elvirdolic** [comment]
@itrethan you can copy this code and adapt it to your needs. This has the benefit that you can include in this file only modules which you use in your app instead of including all modules.

**Comment by DevVersion** [comment]
@jelbourn I think this can be closed now?

**Comment by jelbourn** [comment]
Yep.
