### ISSUE TITLE
md-input does not honor [value] expressions

### ISSUE THREAD

**Issue by arciisine** [angular/material2#2363]
#### Bug, feature request, or proposal:
When using `input[md-input]` and binding a value using `[value]="expr"`, the internal value is not updated when `[value]` resolves.  This in turn propagates to `empty` not updating once `[value]` resolves.  

#### What is the expected behavior?

When setting an input's value with `[value]`, it should be honored.  The placeholder should move out of the way when value is set.

#### What is the current behavior?
The input believes it is empty and the placeholder stays in the original spot.

#### What are the steps to reproduce?

http://plnkr.co/edit/79XlYsdCjUKQvnKQyDRU?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0-beta.0

**Comment by arciisine** [comment]
As a follow up, this works properly when using `ngModel` or `formControlName`.  I actually have a scenario in which I want to show readonly form elements without binding the data to a form.  It also does work if using `value="name"` but not using `value="{{name}}"`

**Comment by bboehm86** [comment]
same is true when using reactive forms and not setting the values right from the start (eg set them after http call or a timeout)
http://plnkr.co/edit/JkLHwmauIhJGy7dJfQU7?p=preview

**Comment by MarcusCalidus** [comment]
it also seems not to work when binding via `[value]="some.value"`

![image](https://cloud.githubusercontent.com/assets/4113366/21452109/cac208c8-c904-11e6-8bc3-62f4fe5537fe.png)

**Comment by arat3091** [comment]
it also seems not to work when binding via [disabled]="testCondition" or [disabled]= "'true'"

We still can edit the value when testCondition is true.

**Comment by fxck** [comment]
It doesn't work even when using `formControl` or `formControlName`, specifically when the value is set asynchronously.
