### ISSUE TITLE
material.umd.js is missing in 2.0.0-beta.0 npm package

### ISSUE THREAD

**Issue by MarcusCalidus** [angular/material2#2366]
#### Bug, feature request, or proposal:

Bug: material.umd.js package is missing in npm package 2.0.0-beta.0

#### What is the expected behavior?

expected to work like in package version 2.0.0-alpha.11

#### What is the current behavior?
The diff of my package.json
![image](https://cloud.githubusercontent.com/assets/4113366/21448839/4387eda4-c8e7-11e6-9f24-9915474d3c2b.png)

The excerpt of my systemjs.config.ts which worked previously
![image](https://cloud.githubusercontent.com/assets/4113366/21448861/7eb4f232-c8e7-11e6-86e5-bd8e45b653bd.png)

**Comment by Faltek** [comment]
Agree. I was making the same issue.

**Comment by Rob-Post** [comment]
It's now located at @angular/material/**bundles**/material.umd.js

**Comment by Faltek** [comment]
Thanks. But documentation should be fixed.

**Comment by Sabartius** [comment]
Its even worse for webpack-users. The main-attribute of the package.json still points to the old location of the umd bundle, so it's not possible to run a compiled application, as it won't find anything material related.

**Comment by DevVersion** [comment]
Thanks guys for the issue. I've provided a PR for it and hopefully it will be fixed as soon as possible.

**Comment by sunshineo** [comment]
Someone need to update the tutorial here https://material.angular.io/guide/getting-started

**Comment by charlieamat** [comment]
Lost about half an hour to this today because the getting started section hasn't been updated yet.
