### ISSUE TITLE
md2-dialog genreate some html code when our application running but I want to add one class for css. How to add class for that ?

### ISSUE THREAD

**Issue by aminsmartsense** [angular/material2#2370]
This is my actual code:` <md2-dialog #new title="Create"></md2-dailog>`

**Comment by aminsmartsense** [comment]
This is my generated code: (I want to add class in this):  <div id="md-overlay-3">
  <div class="md2-dialog open">
       <div class="md2-dialog-container"></div>
 </div>
</div>

**Comment by aminsmartsense** [comment]
This is my generated code: (I want to add class in this)
**

- <div id="md-overlay-3">
-   <div class="md2-dialog open">
-        <div class="md2-dialog-container"></div>
-  </div>
- </div>

**

**Comment by aminsmartsense** [comment]
This is my generated code: (I want to add class in this)
```
<div id="md-overlay-3">
  <div class="md2-dialog open">
       <div class="md2-dialog-container"></div>
 </div>
```
</div>

**Comment by fxck** [comment]
what's `md2-dialog`?  you sure it's from this repo?
