### ISSUE TITLE
Menu doesn't work in beta.0

### ISSUE THREAD

**Issue by skined90** [angular/material2#2371]
When I paste exactly same code from the documentation, on icon click nothing happens. Menu won't open, but there is no any error in console. Is this a bug or documentation is outdated?

**Comment by crisbeto** [comment]
Can you post the code that you're using?

**Comment by skined90** [comment]
`

<button md-icon-button [mdMenuTriggerFor]="menu">
   <md-icon>more_vert</md-icon>
</button>

<md-menu #menu="mdMenu">
    <button md-menu-item> Refresh </button>
    <button md-menu-item> Settings </button>
    <button md-menu-item> Help </button>
    <button md-menu-item disabled> Sign Out </button>
</md-menu>
`
