### ISSUE TITLE
.md-overlay-container added out of app container

### ISSUE THREAD

**Issue by GerrAlt12** [angular/material2#2373]
Looks like
```html
<div class="md-overlay-container">
```
inserted into markups BODY tag childrens, instead of adding it to the list of app root element children.

For example looks at markup I get after click on menu button:

```html
<body>
  <jmc-admin ng-version="2.4.1" _nghost-aod-23="">
    <!-- apps markup -->
  </jmc-admin>
  <div class="md-overlay-container">
    <!-- menu items -->
  </div>
</body>
```
This behavior broke style association: all styles automatically prefixed with "_nghost-aod-23" attribute by angular compiler, but md-overlay-container is out of the app container and selectors like ".md-overlay-container[_ngcontent-aod-23]" does not match it.

Plunker: http://plnkr.co/edit/qDCkFvodD5wBqFoZIdRC?p=preview
As you see, element added out of app scope. It rendered well just because application is not compiled with angular AoT compiler.

**Comment by jelbourn** [comment]
This is working as intended. The overlay container is added directly to the body in order to prevent overlays from being clipped by a containing element. The current recommendation is to style overlays using a CSS file loaded via `<link>` element in your `index.html`.

**Comment by Striveyazi** [comment]
@jelbourn  hi, i have one problem that i want to remove this overly container, and the dialog's position can custom. this idea can achieve? if not ,have you some good suggestions? thank u very much.
