### ISSUE TITLE
[Bug|self error] md-select in md-dialog can't use providers data

### ISSUE THREAD

**Issue by Luchillo** [angular/material2#2374]
#### Bug, feature request, or proposal:
Bug or misconfiguration.

#### What is the expected behavior?
I was expecting the dialog component to have available the same service instance of the caller(parent) component, but that service is local to the caller(parent) component, after that i request some data and put that in the `md-select`, and set a default.

I set the default value from the caller(parent) component through the instance of the dialog component.

#### What is the current behavior?
I'm forced to open the dialog, get the dialog instance and set the service manually instead of asking for it to the injector.

However it doesn't end there, i had to set the value from the parent component, then in the dialog component was getting the select data from service, but the default selected value wasn't being set.

I'm forced to both pass the default selected value as well as the options data from the parent through the instance of the dialog component.

#### What is the use-case or motivation for changing an existing behavior?
Harder to deal with if we need to set everything from the parent through the instance of the dialog component instead of using the injector.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.2.1
Material: 2.0.0-beta.0
Browser: Chrome 55.0.2883.95

#### Is there anything else we should know?
I suspect it has to do with the value being set before the data for the select is available.

~~Maybe the value set from the parent through instance is outside of the `ngZone`?~~

Scratch the last sentence, it is in the zone since it works when i set all from the parent through the instance of the `md-dialog` component.

**Comment by Luchillo** [comment]
@icordoba8 take a look.

**Comment by EladBezalel** [comment]
Can you please provide a codepen so we can investigate further?

**Comment by Luchillo** [comment]
Can you give me a base pen to start?

**Comment by EladBezalel** [comment]
Plunker : http://plnkr.co/edit/o077B6uEiiIgkC0S06dd :)

**Comment by Luchillo** [comment]
Ok here it is, just click the button that says `showDialog`, then it should show an error in console like this:
![image](https://cloud.githubusercontent.com/assets/9698639/21904314/2da8593e-d8d1-11e6-906b-e89b78bf3abf.png)

Please note that the service is local to the `CustomerComponent` component, instead of a singleton provider it would be if it were a provider declared in `main.ts` in the `AppModule`.

In such case we were forced to deal with it like this, setting the service through the `dialogRef`'s component instance directly, is this the correct way of dealing with it?:
```ts
showDialog() {
    this.dialogRef = this.dialog.open(CustomerDialogComponent, {
      disableClose: false
    });

    this.dialogRef.componentInstance.customerService = this.customerService;

    this.dialogRef.afterClosed().subscribe(result => {
      console.log('result: ' + result);
      this.dialogRef = null;
    });
  }
```

**Comment by EladBezalel** [comment]
Took me a while to realize you forgot to include your service as a provider 😅 
http://plnkr.co/edit/iDSXXjKxY7QNqO7ABCe6?p=preview

**Comment by Luchillo** [comment]
For the love of ...

You didn't understand my point, i don't want a singleton provider available to the full app, i want a local provider to the customer component, originally in my project it was an Order provider, which could have multiple order instances, thus multiple OrderService instances as well.

The issue is that the local provider isn't available to the Dialog even if the parent that instantiated the Dialog does have access to the provider.

I mean, did you look at the CustomerComponent providers section in [my pen](http://plnkr.co/edit/zZfmQ6AOPjMpnuigyrAL?p=preview)?
![image](https://cloud.githubusercontent.com/assets/9698639/21931819/7bf9e70c-d96b-11e6-8415-a3d786f4ec6d.png)
