### ISSUE TITLE
Icon Toggle [new component request]

### ISSUE THREAD

**Issue by hacknaked** [angular/material2#2375]
Would be great to include icon toggles as defined in https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons

MDC has a nice implementation of this
https://material-components-web.appspot.com/icon-toggle.html

**Comment by fxck** [comment]
https://github.com/angular/material2/tree/master/src/lib/button-toggle#exclusive-selection ?

**Comment by hacknaked** [comment]
@fxck Yes, maybe a icon toggle can be implemented using exclusive selection button group, but seem wired to me (a group with only one element and two level html markup. Something like `<mg-icon-toggle>my-icon</mg-icon-toggle>` is clearer for me.

**Comment by jmcgoldrick** [comment]
How would `md-icon-toggle` work with different icon fonts etc? I've been doing something like this: http://plnkr.co/edit/RMXpNJj8Ep1wcfK1VYtr?p=preview which is even nicer using the new `NgIfElse`

**Comment by EladBezalel** [comment]
MDC implementation is not following the [material design spec](https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons) (no outlines) - 
We do have [icon buttons](https://plnkr.co/edit/WSTUtfQOunWYrKBuiFvr?p=preview)

**Comment by hacknaked** [comment]
@EladBezalel 

> MDC implementation is not following the material design spec

Well, It's really wired.

https://material.io/components/ links to https://github.com/material-components/material-components-web#useful-links. If you follow the [Demos](https://material-components-web.appspot.com/) link you will reach the Icon Toggle demo I've post. 

Seems that  MDC Icon Toggle was made by the same guys that write Material Design Spec.

**Comment by EladBezalel** [comment]
Well, https://material.io/components/ is the website for  https://github.com/material-components/material-components-web#useful-links.

They're not the same guys and even if they're if its not in the spec, we won't implement it.

**Comment by hacknaked** [comment]
@EladBezalel 

But, what's the official Material spec? 
In your first comment you linked to https://material.io/guidelines

Are you saying that people who write https://material.io/guidelines are not the same that people who implement https://material.io/components? Why they don't follow their own spect? Sorry, for dumb questions, but it's confusing.

**Comment by EladBezalel** [comment]
Yes, just as the people that write [material.angular.io](https://material.angular.io) are not the same as [augury.angular.io](https://augury.angular.io)

**Comment by cesartolosa** [comment]
I am confused @EladBezalel, why you said 

> MDC implementation is not following the material design spec 

if icon toggles is included in the [material design spec](https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons) ???

**Comment by EladBezalel** [comment]
I'm talking about outlining the icon itself, this part is not included in the material design spec.

You can totally have icon buttons as simple as:
```html
<button mdIconButton>
  <md-icon>my_icon</md-icon>
</button>
```

**Comment by cesartolosa** [comment]
Ok @EladBezalel, but what about the ripple ink response? The ripple ink boundary seems to be different (out of boundaries) to icon toggles than the regular icon button.

**Comment by EladBezalel** [comment]
@cesartolosa #3208

**Comment by cesartolosa** [comment]
@EladBezalel, thanks!!!

**Comment by thw0rted** [comment]
I know this is super old, but @EladBezalel or others, as far as I can tell there's still no official implementation of "Icon Toggle" from [the spec](https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons).  Yes, you can hack in behavior for a toggle based on `mat-icon-button` but I'd like to see something as easy to use as `mat-checkbox`, where toggle state is maintained by the component.

Since icon toggles are in the spec, I would suggest that they *should* have an example in the docs (and, ideally, easy to use syntax).
