### ISSUE TITLE
Question / possible Correction in documentation "getting started with the CLI"

### ISSUE THREAD

**Issue by daBishMan** [angular/material2#2379]
#### Bug, feature request, or proposal:
Bug in documentation I believe

#### What is the expected behavior?
we no longer need to add to hammerjs to the types section of tsconfig.  per documentation of TS only typesRoots or types is used, and with installing @types/hammerjs and the typesRoots included in the CLI nothing else needs to be added.  

Also, I am not sure we need to "import 'hammerjs'" into app.module.ts as the types are there already?

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

#### What is the current behavior?
we add types section to tsconfig which loses the typings for other libraries in the ide, i.e. visual studio code.

#### What are the steps to reproduce?
Documentation issue.

#### What is the use-case or motivation for changing an existing behavior?
so the user does not lose typings for the rest of the libraries.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.1, material 2.0.0.beta.0, Windows 10

#### Is there anything else we should know?
no

**Comment by jelbourn** [comment]
Change getting-started guide to be more clear about hammerjs.

**Comment by daBishMan** [comment]
@jelbourn I think you still need to include the npm install @types/hammerjs
