### ISSUE TITLE
CSS Guidelines

### ISSUE THREAD

**Issue by Martin-Andersen** [angular/material2#2380]
Congratulations with the new site and and the beta.0 milestone looks really good.

I am missing examples for typography and everything css related like [bootstrap](http://getbootstrap.com/css/#type) have it.

Last, does material2 have a responsive grid based on flexbox?

Thanks

**Comment by jelbourn** [comment]
See #205 and https://github.com/angular/flex-layout/

**Comment by Martin-Andersen** [comment]
I would prefer a "normal" grid. I have tried the flex-layout demo and it is slow to layout its elements.
