### ISSUE TITLE
what's this mean ? "export class PizzaPartyAppModule { }"

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [angular/material2#2386]
# export class PizzaPartyAppModule { }

```sh
$ npm i -S @angular/material
``` 

## Import the Angular Material NgModule

> src/app/app.module.ts  

```codes
import { MaterialModule } from '@angular/material';
// other imports 
@NgModule({
  imports: [MaterialModule.forRoot()],
  ...
})
export class PizzaPartyAppModule { }
```

**Comment by xgqfrms-GitHub** [comment]
**PizzaPartyAppModule  is an optional name ?**

**Comment by jammerware** [comment]
Yes, **PizzaPartyAppModule** could be any arbitrary name, more or less. By convention, I think the primary module of any Angular (2 and forward) app is called AppModule. It's just the name of the class.

**Comment by xgqfrms-GitHub** [comment]
# ng2  material design  

https://material.angular.io/guide/getting-started  
https://material2-app.firebaseapp.com/  
https://github.com/angular/material2/issues/2386   

## step1:   
```sh
$ npm i -S @angular/material
``` 
## Import  MaterialModule

> src/app/app.module.ts  

```codes
# step 2
import { MaterialModule } from '@angular/material';

# step 3
@NgModule({
  imports: [
           MaterialModule.forRoot(),
    ],
})
``` 

I have to say that the offfical tutorial/guide is little useful for me, just confused me!

Anyway, thanks for your reply!
