### ISSUE TITLE
sideNav: content projection appears to interfere with overlay shadow

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material2#2402]
Here is a [Plunkr Demo](https://plnkr.co/edit/rkF70n7X4Yv8WmP4Thu5?p=preview) where I use multi-slot content projection with a SideNavContainer  + SideNav. This example models that used on [Material2 SideNav Overview](https://material.angular.io/components/component/sidenav).

*  The Material2 version **shows a content shadow** when the sideNav is programmatically opened. 
*  The Plunkr does NOT show the content shadow.

> Then only apparent difference is the content projection.

**Comment by dahaupt** [comment]
Your responsive behavior looks interesting. 

@jelbourn Is this something we can expect for the future in the sidenav component?

**Comment by crisbeto** [comment]
It's because you're missing the theme file which provides the backdrop's color. Here's a forked Plunkr: https://plnkr.co/edit/2CXsvdZmE6mE4MD71xKc?p=preview

**Comment by ThomasBurleson** [comment]
@crisbeto - well that was embarrassing.
