### ISSUE TITLE
md-dialog and menu  out of md-sidnav-layour/ md-sidnav-container

### ISSUE THREAD

**Issue by Shifeng-ON** [angular/material2#2403]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
md-dialog should be at center of screen and menu should act like a dropdown

### What is the current behavior?
they both got squeezed at buttom of sidnav container

### Which versions of Angular, Material, OS, browsers are affected?
angular2, beta.1
#### Is there anything else we should know?
it worked fine when using angular2.alpha.11

#### normal (using angular2.alpha.11)
<img width="167" alt="normal_menu" src="https://cloud.githubusercontent.com/assets/24700723/21469972/5abc1ba8-ca40-11e6-84eb-f888a5c16cd6.png">

<img width="1192" alt="normal_dialog" src="https://cloud.githubusercontent.com/assets/24700723/21469974/5dc2c55e-ca40-11e6-94dc-8afea4fa1d4b.png">

#### abnormal  (using angular2.beta.1)

<img width="642" alt="abnormal_menu" src="https://cloud.githubusercontent.com/assets/24700723/21469977/637c830e-ca40-11e6-9ff6-85a68156085d.png">
<img width="1051" alt="abnormal_dialog" src="https://cloud.githubusercontent.com/assets/24700723/21469978/64bb6faa-ca40-11e6-9f7e-17a26c662a2f.png">

**Comment by crisbeto** [comment]
We haven't really changed that much about positioning between alpha and beta. Try clearing your node_modules and reinstalling.

**Comment by Shifeng-ON** [comment]
i delete the modules each time i change the version.

as soon as i use beta, the problem appears

**Comment by Shifeng-ON** [comment]
https://embed.plnkr.co/146tRVG666CtylkEHYoH/ see this.

**Comment by crisbeto** [comment]
It looks like you haven't included the a theme. Try adding this to your Plunk (these are also distributed as a part of the Material builds):

```html
<link href="https://unpkg.com/@angular/material/core/theming/prebuilt/indigo-pink.css" rel="stylesheet">
```

**Comment by Shifeng-ON** [comment]
than you , it works now. I re-compiled my theme.

**Comment by crisbeto** [comment]
In that case I'll consider it resolved.
