### ISSUE TITLE
Why didn't my button color?

### ISSUE THREAD

**Issue by Michael199315** [angular/material2#2406]
<img width="453" alt="2016-12-26 4 30 06" src="https://cloud.githubusercontent.com/assets/18457848/21478656/975c3130-cb88-11e6-8659-eb860d458474.png">

<img width="345" alt="2016-12-26 4 25 21" src="https://cloud.githubusercontent.com/assets/18457848/21478607/1edaf84a-cb88-11e6-845b-24eb627c8c7a.png">
Why didn't my button color?
What should I do?

**Comment by faisalmuhammad** [comment]
@Michael199315 Hi, Can you provide more details? What version of material package you are using?

**Comment by dahaupt** [comment]
@Michael199315 Most likely you forgot to include a theme into your app. 
See [this guide](https://github.com/angular/material2/blob/master/guides/theming.md).

**Comment by DevVersion** [comment]
Just confirmed that it works locally. As said, it looks like you forgot to include a theme stylesheet.
