### ISSUE TITLE
please update github code as it is working in this url: https://material.angular.io/components

### ISSUE THREAD

**Issue by fernandesmelwyn** [angular/material2#2410]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by EladBezalel** [comment]
It is, material.angular.io is built upon this repository.

P.S please notice that this issue is not following our issue submission instructions.
