### ISSUE TITLE
md-select multiple support

### ISSUE THREAD

**Issue by jmiguelherazo** [angular/material2#2412]
#### feature request:
Is there support for multiple selection in md-select?

**Comment by dahaupt** [comment]
@jmiguelherazo Not yet, look [here ](https://material.angular.io/components/component/select) for all current features. The same applies to all other components. 

But I'd also like to see multiple selection in the future.

**Comment by pdavin** [comment]
+1'ing this to note we need multiple select for our project. 
AngularJS Material supported it (see "Option Groups"): https://material.angularjs.org/latest/demo/select

If Material 2 isn't going to add it soon, are there any alternatives to consider?

**Comment by spyter** [comment]
@pdavin I need it for a project I am working on as well. This would be a great addition to have!

**Comment by aitchkhan** [comment]
Has this been documented? Could not find this in documentation, or is it just me?

**Comment by Hassan0Rehman** [comment]
I also couldn't find documentation and support. Looks like this feature is not offered yet. As a workaround we can use this http://softsimon.github.io/angular-2-dropdown-multiselect/#

**Comment by crisbeto** [comment]
It has been supported for a while now. You have to add the `multiple` attribute to your `md-select`. You can see the `multiple` property in the API documentation: https://material.angular.io/components/select/api

**Comment by hirrus** [comment]
Just for somebody new to angular, please use this example: https://angular-material2-issue-wak6cs.stackblitz.io
