### ISSUE TITLE
【Feature addition request】define list component

### ISSUE THREAD

**Issue by kgtkr** [angular/material2#2415]
<md-dl>

**Comment by crisbeto** [comment]
Can you be a little more specific?

**Comment by kgtkr** [comment]
I want <dl><dd><dt>
For example

    <md-card>
      <md-dl>
        <dt>name</dt>
        <dd>Taro</dd>
        <dt>from</dt>
        <dd>Japan</dd>
      </md-dl>
    </md-card>

**Comment by danielgek** [comment]
@kgtkr something like [this](https://github.com/angular/material2/blob/master/src/lib/list/OVERVIEW.md) maybe ?

**Comment by kgtkr** [comment]
I did not know that
thank you

**Comment by dahaupt** [comment]
@kgtkr If that is what you've searched, please close this issue yourself.

**Comment by kgtkr** [comment]
OK
