### ISSUE TITLE
textarea not manually resizable via resizeToFitContent method

### ISSUE THREAD

**Issue by mark-langer** [angular/material2#2419]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
[According to the API](https://material.angular.io/components/component/input), one should be able to call the method `resizeToFitContent` on the `MdTextareaAutosize` directive to manually trigger an auto-resize of the textarea that is labeled with `md-autosize`.

Since you have to declare a handle for the directive through a template variable, e. g. `#myTextareaAutosizeDirective="mdTextareAutosize"`, to call any methods on it, the MdTextareaAutosize directive should have a decorator property `exportAs` defined.

#### What is the current behavior?
If you try to assign the directive to a template variable, an error is thrown. I assume this error occurs because of the directive's missing exportAs decorator property mentioned above.

The error reads: `There is no directive with "exportAs" set to "mdTextareaAutosize"`

#### What are the steps to reproduce?
This plunker [shows the use case](http://plnkr.co/edit/sHpwxl20r0lVMrRopW2w?p=preview).

This plunker includes the [template variable assignment that throws the error](http://plnkr.co/edit/F3Z0hO5sbpJYB1cq57Ny?p=preview).

#### What is the use-case or motivation for changing an existing behavior?
In our app, we insert text into the textarea through a function which does not trigger the `change` event of the textarea that is normally used for resizing.

#### Which versions of Angular, Material, OS, browsers are affected?
beta.0

#### Is there anything else we should know?
Nope.

**Comment by szykov** [comment]
Was it fixed? I tried plunkr and it still doesn't trigger a change event and textarea doesn't resize automatically when inserting value through the code. In my project the same behavior...

ps - also I noticed that plunkr isn't working when using **md-input** attribute but with **mdInput** works fine. Feature or bug? :)

**Comment by mark-langer** [comment]
The fix has been published with beta.2 just yesterday.

**Comment by szykov** [comment]
In the plunkr repo, autosize still isn't working with a new beta.2 release.  
I forked repo with updated md-input to mdInput:

http://plnkr.co/edit/JfAu98HL5faXM2LDuP8c?p=preview

**Comment by guojenman** [comment]
@szykov updated your plnkr with edits to make it work
http://plnkr.co/edit/w2qdyYJTtT6cg07MCZmU?p=preview

**Comment by szykov** [comment]
@guojenman thanks for working example. I was expecting that it will trigger automatically resizing but manual call for **resizeToFitContent** is also fine. Thanks.

**Comment by guojenman** [comment]
@szykov Yeah, I was expecting that too. Maybe this directive needs to respond to ngModelChange event

**Comment by guojenman** [comment]
Edit 2: If DefaultValueAccessor could fire an effect on writeValue, we can listen and to respond to this. Considering requesting this feature to @angular/forms but I want to see if there's another way first.

**Comment by szykov** [comment]
@gucheen Grrr I found another bug related to this one. I updated plunkr repo:
http://plnkr.co/edit/6Od4nfkgoAT694nkYbgf?p=preview

This is a normal behaviour:
![image](https://cloud.githubusercontent.com/assets/16446651/24252313/f055fc66-0ffe-11e7-97f1-8bb6ea792efc.png)

This is what happens if resize manually:
![image](https://cloud.githubusercontent.com/assets/16446651/24252385/3047c94e-0fff-11e7-91c7-e5be15368abb.png)

@DevVersion  could you please reopen issue and help us? Thanks.

**Comment by sl007** [comment]
Iam using material 2.0.0-beta6 have same error: There is no directive with "exportAs" set to "mdTextareaAutosize"

**Comment by MatthewTrout** [comment]
Still not working beta 10..
