### ISSUE TITLE
How to open a particular menu programmatically if more than one menu element?

### ISSUE THREAD

**Issue by vkishorekumar80** [angular/material2#2421]
If I have more than one menu element in a page, how will I open a particular menu based on the context or how can I select a menu element using ViewChild by specifying the name?

Plunker: https://plnkr.co/edit/iVgoBU?p=preview

**Comment by vkishorekumar80** [comment]
@crisbeto What could be done for this kind of scenario?

**Comment by EladBezalel** [comment]
I couldn't got your question, what would you like to achieve?

**Comment by vkishorekumar80** [comment]
https://plnkr.co/edit/gbpvuno5thiUzlYNIcb3?p=preview
In the example, how will I open the second menu when I click on the "open second menu button"?.

**Comment by EladBezalel** [comment]
So you can do something like that: 
https://plnkr.co/edit/ScrbSJQWkAdjaAI7EKQU?p=preview
The better approach would be using a query selector
```ts
  @ViewChild('trial') trigger: MdMenuTrigger;
```
But i'm getting the `mdButton` directive instead of the trigger, i will check what we can do with that.

**Comment by vkishorekumar80** [comment]
Thanks @EladBezalel . Will wait for the update.
I got the same result when I tried with the first plnkr sample. 
At times we cannot rely in the index and need to find out the controls by name.

**Comment by EladBezalel** [comment]
Take a look here: https://plnkr.co/edit/AmWcuUNw1YaZeluLq0aJ?p=preview

**Comment by vkishorekumar80** [comment]
Perfect. @EladBezalel Thanks for the help.

**Comment by shijithkm** [comment]
How do we assign mdMenuTriggerFor dynamically ?

[mdMenuTriggerFor]="link.menuName"

**Comment by SergeyKurdyukov** [comment]
@shijithkm 
You can see here https://stackblitz.com/edit/dynamic-nested-menus?file=app%2Fapp.component.ts
