### ISSUE TITLE
Tabs not displaying correctly with Sidenav

### ISSUE THREAD

**Issue by paistipoikka** [angular/material2#2424]
#### Bug, feature request, or proposal:

When opening the sidenav in an application page containing tabs, the horizontal rule on the tabs is on top of the sidenav.

#### What is the expected behavior?

The horizontal rule should be under the sidenav. 

#### What are the steps to reproduce?

Create page with a sidenav and a tabs. Open the sidenav and the problem should be there.

Here's some code to give you an idea of what is going on.

```
<br><br><br><br><br>

<md-tab-group class="demo-tab-group">
  <md-tab label="Earth">
    This tab is about the Earth!
  </md-tab>
  <md-tab label="Fire">
    This tab is about combustion!
  </md-tab>
</md-tab-group>
<br><br><br><br><br><br><br>
<md-sidenav-container fullscreen>
  <md-sidenav #start>
    <md-nav-list>
      <a md-list-item>
        blah
      </a>

      <hr>
    </md-nav-list>
    <button md-button (click)="start.close()">CLOSE</button>
  </md-sidenav>
    <md-toolbar color="primary">
      <button md-icon-button (click)="start.open()">
        <md-icon class="md-24" >open menu</md-icon>
      </button>
    </md-toolbar>


</md-sidenav-container>
```

#### Which versions of Angular, Material, OS, browsers are affected?
Chrome on OSX

**Comment by dahaupt** [comment]
@paistipoikka You can solve this problem by using the `md-sidenav` in the correct way, as described here: https://material.angular.io/components/component/sidenav.

You have to place your `md-tab-group` inside the `md-sidenav-container`, the way you did it with the `md-toolbar`.

Here is a plunker where I did exactly that: http://plnkr.co/edit/4SYEM3Oy0n2EAJrFXiUz?p=info

**Comment by paistipoikka** [comment]
@dahaupt thanks very much.
