### ISSUE TITLE
layout styles

### ISSUE THREAD

**Issue by mikehaas763** [angular/material2#243]
* **Do you want to request a *feature* or report a *bug*?**

Layout system, like what ng1 material provides with the layout flex grid. Is the plan essentially to just take the styling for this as it exists for ng1 material?

**Comment by zoechi** [comment]
For support questions please use other channels like the ones listed in https://github.com/angular/material2/blob/master/CONTRIBUTING.md#question

**Comment by mikehaas763** [comment]
@zoechi I'm not asking for support. I'm asking for a feature. Also asking for some more information because then perhaps it's something I can work on and submit as a PR.

**Comment by jelbourn** [comment]
For Angular 2, we are likely going to break the layout module into its own library, since there's not a great reason for it to be tightly coupled to the components. I'm closing this issue for now as we don't have plans to work on it in the short term.
