### ISSUE TITLE
MdMenu: Items with MdIcons appear on two lines in FireFox

### ISSUE THREAD

**Issue by jermowery** [angular/material2#2435]
#### Bug, feature request, or proposal:
If you have an MdMenu where the menu items are an MdIcon and text, the items will split into two lines on Firefox (contrary to the README for MdMenu).

#### What is the expected behavior?
A single line as shown in the MdMenu README

#### What is the current behavior?
Two lines are created for the MenuItem

#### What are the steps to reproduce?

This Plunker uses the exact HTML has the example for MdMenu, open it in FireFox and click the menu trigger button at the bottom

http://plnkr.co/edit/KvR8H9ZReNHzwcnFIj6H?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It doesn't look as expected

#### Which versions of Angular, Material, OS, browsers are affected?
Latest, Latest, Ubuntu, FireFox

**Comment by dahaupt** [comment]
Firefox doesn't support `display: flex` in a button. 
`Just put a div inside of your <button>, and make that div display:flex.`

This should temporarily solve your problem for Firefox.

http://stackoverflow.com/questions/24289251/flexbox-not-working-in-buttons-in-firefox

**Comment by willshowell** [comment]
Can this be closed?

Copied repro to latest template: http://plnkr.co/edit/IC0zXmiPr4UcvBAAajT8?p=preview

**FF 45.0**
![screen shot 2017-05-16 at 10 42 57 am](https://cloud.githubusercontent.com/assets/6475576/26111954/8df05f4e-3a24-11e7-9700-76d8747dbb49.png)

**FF 53.0**
![screen shot 2017-05-16 at 10 42 16 am](https://cloud.githubusercontent.com/assets/6475576/26111975/9d81472a-3a24-11e7-869a-529c72bc5c5a.png)

**Comment by jelbourn** [comment]
Closing since it seems obsolete
