### ISSUE TITLE
md-icon-button bug in dialog

### ISSUE THREAD

**Issue by helzgate** [angular/material2#2436]
#### Bug, feature request, or proposal:
When using md-icon-button in a dialog, it always starts out in a hovered or focused state, with the background highlighted.

#### What is the expected behavior?
The background of the md-icon-button shouldn't be highlighted when it hasn't been touched or hovered over.

#### What are the steps to reproduce?
Place an md-icon-button inside a dialog.
Here is the [Plunker](http://plnkr.co/Gnua9hidzVPqZ1LBgCSL)

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.1
Material 2.0.0-beta.1

**Comment by crisbeto** [comment]
This is an accessibility feature: Material tries to focus the first focusable element. You can exclude it either by setting it's `tabindex` to -1, or setting a higher `tabindex` on some other element.

**Comment by helzgate** [comment]
This worked, thanks!
