### ISSUE TITLE
Missing css support for Android 4.4 (15% of market)

### ISSUE THREAD

**Issue by eruano** [angular/material2#2437]
#### Bug, feature request, or proposal:
The current browserlist query does not match Android 4.4 browsers.  While they have a very limited market share, mobile applications build with tools like Apache Cordova amd Ionic use the embedded webkit components.  This means that they run on these older mobile browsers and will not work correctly if not supported.  I has having issues with a sidenav not animating or closing.  

#### What is the expected behavior?
 The Angular Material 2 Demos showed the same behavior on and Android 4.4 browser where the sidenav does not animate or close.  It just appears when you click the menu button and you can not get rid of it after that.  The problem is that the css is missing the -webkit version of the transformation properties.

#### What is the current behavior?
Sidenav should work the same as in a browser.

#### What are the steps to reproduce?

This issue depends on the browser agent and therefore cannot be demostrated through a Plunker.  It can be reproduced with the material demo app.

#### What is the use-case or motivation for changing an existing behavior?
Without support for Android 4.4 anyone developing mobile apps with ionic or Cordova or other technologies will miss out on 15% of the Android markey.  Yes, while the Android 4.4 browser share is very not (between 1%-2%), it represents 15% of the Android devices.
https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=1

#### Which versions of Angular, Material, OS, browsers are affected?
Android 4.4 (and other similar webkit based devices/browsers).

#### Is there anything else we should know?
Adding ">1%" to the browserlist config adds Android4.4 to the supported list.
http://browserl.ist/?q=%3E1%25%2Clast+2+versions

This is the change I made to fix this locally in constants.ts:
`
export const SASS_AUTOPREFIXER_OPTIONS = {
  browsers: [
      '>1%',
    'last 2 versions',
    'not ie <= 10',
    'not ie_mob <= 10',
  ],
  cascade: false,
};`

**Comment by jelbourn** [comment]
For now we are not supporting Android 4
