### ISSUE TITLE
MdMenu documentation error, menu says to use "mdMenuTriggerFor" attribute for triggering the menu but it uses -> "md-menu-trigger-for"

### ISSUE THREAD

**Issue by nombrekeff** [angular/material2#2445]
#### MdMenu Documentation error.
MdMenu documentation say to trigger menu with `mdMenuTriggerFor` attribute, camel cased, but when i've looked at the code it expects `md-menu-trigger-for`, If I use `md-menu-trigger-for` it works as expected.

###### Does not work if i pass `mdMenuTriggerFor`:
```html
<button md-icon-button [mdMenuTriggerFor]="menu">
     <md-icon>more_vert</md-icon>
</button>
<md-menu #menu="mdMenu">
   <button md-menu-item> Refresh </button>
   <button md-menu-item> Settings </button>
   <button md-menu-item> Help </button>
   <button md-menu-item disabled> Sign Out </button>
</md-menu>
```
###### **Above code throws**:
```shell
zone.js:355 Unhandled Promise rejection: Template parse errors:
Can't bind to 'mdMenuTriggerFor' since it isn't a known property of 'button'. ("
      </div>
    </div>
    <button md-icon-button [ERROR ->][mdMenuTriggerFor]="menu">
       <i class="fa fa-ellipsis-v"></i>
    </button>
")
```

###### But if I pass `md-menu-trigger-for` it works as expected?

```html
<button md-icon-button [md-menu-trigger-for]="menu">
     <md-icon>more_vert</md-icon>
</button>
<md-menu #menu="mdMenu">
   <button md-menu-item> Refresh </button>
   <button md-menu-item> Settings </button>
   <button md-menu-item> Help </button>
   <button md-menu-item disabled> Sign Out </button>
</md-menu>
```

#### Which versions of Angular, Material, OS, browsers are affected?
Material version: @angular/material@2.0.0-alpha.11-3
Angular version: @angular@3.3.12

**Comment by crisbeto** [comment]
The camel-cased property was introduced with Material `beta.0`, it seems like you're using alpha.

**Comment by nombrekeff** [comment]
Ok, didn't realize it might of been added to newer versions, thanks, i will update and check the beta
