### ISSUE TITLE
Tabs animations

### ISSUE THREAD

**Issue by dfgkzhang** [angular/material2#2450]
I'm using version 2.0.0-alpha.11 of angular/material and I'm wondering if there was a way to disable the tab animations. 

I'm also running into issues in my karma tests where the tabs don't change, which may be caused by the animations, since I didn't have this issue with alpha.10.  Do I need to add an additional import or dependency to the TestBed to get this working?

Here is the test and selectChange method for the tab group:
```
it('should change activeTabIndex when tab changes', async(() => {
    let fixture = TestBed.createComponent(AppComponent);
    let component = fixture.componentInstance;

    fixture.detectChanges();

    let compiled = fixture.debugElement.nativeElement;
    let tabs = compiled.querySelectorAll('.md-tab-label');
    tabs[1].click();	// change to something other than tab 0
    expect(component.activeTabIndex).toBe(1);
 }));
```

```
  selectChange(event: MdTabChangeEvent): void {
    this.activeTabIndex = event.index;
    console.log(event.index);
  }
```

**Comment by crisbeto** [comment]
Try adding another `fixture.detectChanges()` after clicking the tab.

**Comment by dfgkzhang** [comment]
I've tried that and it doesn't work.

**Comment by crisbeto** [comment]
Otherwise you can see how we're testing it here: https://github.com/angular/material2/blob/master/src/lib/tabs/tab-group.spec.ts#L44

**Comment by dfgkzhang** [comment]
In your test, you test for the MdTabGroup's selectedIndex which does change.  However, I'm trying to test whether my selectChange callback gets called and it doesn't.  The activeTabIndex value never gets updated.

**Comment by dfgkzhang** [comment]
```
<md-tab-group (selectChange)="selectChange($event)">
</md-tab-group>
```
This is how I'm defining the selectChange callback and this works when I run the app normally.  Just doesn't work in the tests.  

Also to reiterate my other question, is it possible to disable the animations?

**Comment by crisbeto** [comment]
I don't think it is, unless you do something like `* { animation: none !important; transition: none !important; }` in your CSS. 

Regarding the test, what are you doing in the `selectChange` method? Maybe something isn't being updated there?

**Comment by dfgkzhang** [comment]
The selectChange method is in my first post.

**Comment by crisbeto** [comment]
Ah sorry, I missed it. What value comes back when you try to log the index? `undefined`?

**Comment by dfgkzhang** [comment]
Yes undefined.

**Comment by crisbeto** [comment]
In our tests it also looks like we flush the timeouts. Try changing your test to this:

```ts
import {fakeAsync} from '@angular/core/testing';

it('should change activeTabIndex when tab changes', fakeAsync(() => {
  let fixture = TestBed.createComponent(AppComponent);
  let component = fixture.componentInstance;

  fixture.detectChanges();

  let compiled = fixture.debugElement.nativeElement;
  let tabs = compiled.querySelectorAll('.md-tab-label');
  tabs[1].click();  // change to something other than tab 0
  
  fixture.detectChanges();
  tick();

  expect(component.activeTabIndex).toBe(1);
}));
```

**Comment by LOZORD** [comment]
Yeah, be sure to call `fixture.detectChanges()` __after__ the click. I've also experienced some strange behavior with `debugElement`, so maybe try using `fixture.nativeElement` instead.

**Comment by dfgkzhang** [comment]
Finally got it working, but I had to change the tick to tick(1000).  Thanks.

**Comment by crisbeto** [comment]
Cool, glad to help. I'll close the issue.

**Comment by evanjmg** [comment]
Anyway to disable animation by a class or property on md-tab-group? the css hack doesn't work.

**Comment by ciesielskico** [comment]
I also need disabling of tabs animation, +1
