### ISSUE TITLE
md-select should emulate select behavior with [value] and (change) 

### ISSUE THREAD

**Issue by mbellezi** [angular/material2#2459]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
md-select should support the property [value] for change it's value and the event (change) when a new value is selected. This way, it can be used as a direct replacement in code using select.

#### What is the current behavior?
It does not implements the property [value] and the event (change)

**Comment by crisbeto** [comment]
The change event will be added with https://github.com/angular/material2/pull/2458.

**Comment by kara** [comment]
@mbellezi It's worth noting that it's already compatible with both Angular core forms modules. Using `formControl` or `ngModel` to track value and changes will already work.

**Comment by mbellezi** [comment]
In a regular situation, I agree. But, when you are using the component to build composed components witch will use the formControl or ngModel itself, this is very useful.
