### ISSUE TITLE
md-select placeholder blends with other text.

### ISSUE THREAD

**Issue by davidwilcox** [angular/material2#2465]
#### Bug, feature request, or proposal:
md-select placeholder text is placed under text that occurs immediately prior.

#### What is the expected behavior?
Padding is built into the md-select so that the placeholder text is not placed over or under any text that comes prior.

#### What is the current behavior?
The placeholder attribute goes over any text that is prior to it.

#### What are the steps to reproduce?
Use an md-select element with a placeholder attribute.

http://plnkr.co/edit/R906XtG5GXTA4SNtQUZy?p=preview
Select "Salt Lake City" from the input element.

#### What is the use-case or motivation for changing an existing behavior?
It looks kind of bad the way it is where you have two things of text on top of each other. It doesn't make sense from a developer's standpoint for this to happen. It's onerous to build into each md-select padding necessary in order to make it look good.

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/core@^2.4.1
@angular/material@^2.0.0-beta.1
Ubuntu 16.04
Google Chrome browser.

#### Is there anything else we should know?
Nope! Great job! Thanks for your help!

**Comment by peluprvi** [comment]
Select with placeholder has the same height as a text field ([Material guidelines](https://material.io/guidelines/components/text-fields.html#text-fields-single-line-text-field)):

![image](https://cloud.githubusercontent.com/assets/1561360/23839063/1ab989ce-077a-11e7-8905-0d2c80e2b811.png)


Material text field specs:

![image](https://cloud.githubusercontent.com/assets/1561360/23838978/7504f716-0779-11e7-820b-12ff41082754.png)

**Comment by jelbourn** [comment]
Tracking via #2124
