### ISSUE TITLE
 this._ngZone.onMicrotaskEmpty.first is not a function

### ISSUE THREAD

**Issue by elaijuh** [angular/material2#2467]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It should not produce any errors

#### What is the current behavior?
I am using `mdSidenav`, when it's opened by a button, there is an error
` this._ngZone.onMicrotaskEmpty.first is not a function`

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
angular: 2.4.1
angular/router: 3.2.1
angular/material2: 2.0.0-beta.1
zone.js: 0.7.4

**Comment by crisbeto** [comment]
Can you post a Plunkr that shows the error? We're using sidenavs, triggered by buttons, in a bunch of places (e.g. our docs site and our demo app) and none of them throw the error. You can use this as a base: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by elaijuh** [comment]
@crisbeto , I have used your template to test md-sidenav and it works.
I am not sure if it's package version conflict problem.

**Comment by crisbeto** [comment]
I think that you might be missing the `first` operator from Rxjs. Try adding this to your app: 

```ts
import 'rxjs/add/operator/first';
```

**Comment by elaijuh** [comment]
I update rxjs to latest version and the problem is solved.
