### ISSUE TITLE
grid-list footer disappears when using "overflow:auto" for items that need scroll to be visible (android chrome browser)

### ISSUE THREAD

**Issue by geelus** [angular/material2#2469]
#### Bug, feature request, or proposal:
At the moment when using Grid-List, item's footer is not displayed for items awaiting scroll and not visible on the first page. This behavior only happens when using **Android's Google Chrome browser**.

#### What is the expected behavior?
To show the footers after scrolling

#### What is the current behavior?
At the moment when using Grid-List, item's footer is not displayed for items awaiting scroll and not visible on the first page

#### What are the steps to reproduce?

Plunker:
http://plnkr.co/edit/6KZh5zMEbaNZLnSKVJdx?p=info 

#### Which versions of Angular, Material, OS, browsers are affected?
Android's Google Chrome browser all latest versions

**Comment by crisbeto** [comment]
What version of Android are you testing against @geelus? I've been trying out against the latest one on Browserstack and it works fine.

**Comment by geelus** [comment]
Android version 6.0.1

**Comment by geelus** [comment]
On the plunk above, if you scroll down you will see the items displayed ... instead of the item name

**Comment by geelus** [comment]
Try this from your phone:
[](http://embed.plnkr.co/6KZh5zMEbaNZLnSKVJdx/)

**Comment by geelus** [comment]
[http://embed.plnkr.co/6KZh5zMEbaNZLnSKVJdx/](http://embed.plnkr.co/6KZh5zMEbaNZLnSKVJdx/)

**Comment by crisbeto** [comment]
I don't have an Android phone, but copying your example in our demo app and testing against Browserstack worked fine. Can you show a screenshot of what it looks like when it's broken?

**Comment by geelus** [comment]
I'm having this issue on my phone for another project. Now when I tried to take a screenshot, I realized the reason it is not appearing properly is that it does not fit the screen and therefore it's showing ...
When I rotated my phone to landscape, it did not happen again but my original problem still exists and I suspect it is because of the length of the text as well.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via Plunker.
