### ISSUE TITLE
Bug: md-input with min and max break element display

### ISSUE THREAD

**Issue by no-more** [angular/material2#2470]
#### Bug, feature request, or proposal:
When specifying both min and max on a md-input number the displayed element size breaks

![image](https://cloud.githubusercontent.com/assets/3856871/21562283/3c481244-ce91-11e6-9732-6df3742f6410.png)

#### What are the steps to reproduce?

http://plnkr.co/edit/TJl6TFi9WefY9I6HHjB0?p=preview

**Comment by crisbeto** [comment]
This is actually a Chrome bug. [I reported it a while ago and doesn't seem to be fixed yet.](https://bugs.chromium.org/p/chromium/issues/detail?id=598164&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified). You can work around it though, you just need to set a `step` attribute. I'll path it into Material as well.

**Comment by crisbeto** [comment]
Closing the issue since there's an easy workaround it: you need to set **some** kind of value on the `step` attribute: either `any` or some number.

**Comment by no-more** [comment]
Thanks that's fine to me. Hope chrome team will fix this issue one day.
