### ISSUE TITLE
fix(MdInput): placeholders don't float when MdInput value has bound expression

### ISSUE THREAD

**Issue by PascalPrecht** [angular/material2#2477]
#### Bug, feature request, or proposal:
When binding a value to `MdInput` using an expression, `placeholder` attribute (or `md-placeholder`) don't float when value is set, which results in placeholder text + input value to overlap. Also after focussing and blurring the input, the placeholder goes back to its original position. However, when using a static value, it works perfectly fine.

#### What is the expected behavior?
`placeholder` attribute (and/or `MdPlaceholder`) should float, also when initial `MdInput` value comes from an expression.

#### What are the steps to reproduce?

1. Create a property on component (`foo="bar"`)
2. Bind property to `MdInput` and give it a placeholder (`placeholder="Some Placeholder"`)

Here's a Plunk that reproduces the bug: https://plnkr.co/edit/NnwmYrakshZ5DEBkW27D?p=preview

#### Is there anything else we should know?
There's an issue that *might* be related to this bug. When setting form values programmatically, placeholder positions also aren't updated. This issue can be found here: https://github.com/angular/material2/issues/2441

Someone came up with a fix for that as well: https://github.com/crisbeto/material2/commit/72bc74250501c4ec839c257afc67b64f3d88f818

**Comment by DevVersion** [comment]
Just confirmed that this will be fixed with https://github.com/angular/material2/pull/2455.

* Here is a Plunker with an UMD bundle from PR #2455, which shows that it works: [Plunker](https://plnkr.co/edit/2vt6vrXADAWuI0gL65Jh?p=preview)

**Comment by PascalPrecht** [comment]
@DevVersion Wow, thanks for the quick reply!! I haven't found that PR right away, would've otherwise not opened this issue. I'll leave it open though, until #2455 is merged!

Thanks so much!

**Comment by DevVersion** [comment]
@PascalPrecht No worries. Thanks for the issue 😄  I will reference your issue, so it will be closed once the PR is merged.
