### ISSUE TITLE
Check box gets into a weird state

### ISSUE THREAD

**Issue by fringd** [angular/material2#248]
**Note: for support questions, please use one of these channels:**
https://github.com/angular/material2/blob/master/CONTRIBUTING.md#question.
This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
![weird-checkbox](https://cloud.githubusercontent.com/assets/272709/14159406/c4795dba-f6a3-11e5-8b70-f77e531bfad3.png)

you get a weird checkbox when you toggle state in the right order in the demo app

To reproduce:

1. uncheck the checkbox
2. make it "indeterminate"
3. check the checkbox

* **What is the expected behavior?**
the box becomes unchecked normally.

* **What is the motivation / use case for changing the behavior?**
the blue box is weird.

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

Tested this only on master synced today, 3/30/2016

* **Other information**
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by jelbourn** [comment]
@traviskaufman is this related to your recent PR about Chrome's layering?

**Comment by traviskaufman** [comment]
It is. That PR fixes this issue.

**Comment by jelbourn** [comment]
Fixed by #263
