### ISSUE TITLE
Bug: input placeholder is not displayed on field reset after editing

### ISSUE THREAD

**Issue by Parez** [angular/material2#2489]
Bug: if the input field is cleared with reset after being changed, the placeholder is not displayed. Feels like it should if the field is empty and marked as untouched.

Following steps to reproduce:

Using reactive forms.
1. Create an input field (md-input) with placeholder set to some text inside md-input-container .
2. On some event (e.g.) checkbox selected - reset the input.
3. Now two cases:
    1. If placeholder is floatingPlaceholder it stays above (though should go down if field is reset)
    2. If placeholder is not floatingPlaceholder it is not displayed at all (though it should be)

I was making a form where the input should get cleared and disabled once checkbox is selected. And default value (e.g. placeholder) should be displayed instead of the text in the input. Spent all day trying to figure out how it can be solved. Didn't find a way.

"@angular/material": "^2.0.0-beta.1", Chrome

The other thing which also feels as quite weird behaviour:
When input is programmatically disabled via reactive forms, the border is not becoming dotted. The same setup as above.
<img width="680" alt="screen shot 2017-01-01 at 22 16 23" src="https://cloud.githubusercontent.com/assets/5672050/21582605/fdd9f096-d06f-11e6-83a6-e46f4cfef486.png">

**Comment by DevVersion** [comment]
Please provide a Plunker for your issue. 

> Template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

**Comment by Parez** [comment]
http://plnkr.co/edit/id4euKCck0CCJPPhXuIN?p=preview

**Comment by DevVersion** [comment]
Thanks for the Plunker! I just confirmed that your issue will be solved with #2455.

Here is an updated Plunker using the fix: http://plnkr.co/edit/Rls3SCRQ94J6bLtCXaPt?p=preview

I will close that issue since we already have related ones #2477, #2363, #2441
