### ISSUE TITLE
md-radio button style error

### ISSUE THREAD

**Issue by FinalDes** [angular/material2#2495]
#### Bug, feature request, or proposal:
md-radio button style issues

#### What is the expected behavior?
radio button and the input circle should be align

#### What is the current behavior?
radio button and the input is not aligned, don't have custom css overwrited the rules
<img width="250" alt="screen shot 2017-01-02 at 8 45 53 pm" src="https://cloud.githubusercontent.com/assets/1146609/21589512/78e06c4e-d12d-11e6-89b1-d484db98a273.png">

#### What are the steps to reproduce?
Default setup of angular material with meteor js

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material@2.0.0-beta.1
meteorjs

**Comment by crisbeto** [comment]
I'm pretty sure that this is because you haven't included the theming CSS. [See the theming guide.](https://github.com/angular/material2/blob/master/guides/theming.md)

**Comment by DevVersion** [comment]
Yeah, that's exactly how it looks without a theme stylesheet.

**Comment by FinalDes** [comment]
can u guys add it [Getting started](https://material.angular.io/guide/getting-started)
