### ISSUE TITLE
Bug: md-select doesn't set selected value if options are initialized after the model

### ISSUE THREAD

**Issue by shedar** [angular/material2#2497]
#### Bug, feature request, or proposal:

Bug, if ngModel of md-select is set before setting of options - select doesn't show selected value after both (options and model) are set.

#### What is the expected behavior?

Showing selected value after both (model and options) are set.

#### What is the current behavior?

Selected value is shown if options are set before ngModel value, otherwise selected value is not shown.

#### What are the steps to reproduce?

http://plnkr.co/edit/yL8QJBjABGPRerqGIR2b?p=preview

You see two selects, left one shows selected value, right one - doesn't.

#### What is the use-case or motivation for changing an existing behavior?

For ajax loaded value and options the order of initialization is not guaranteed. Without fixing this bug you need to add an additional logic to the app to init select value only after options array is set.

#### Which versions of Angular, Material, OS, browsers are affected?

Tested with Angular 2.4.1, Angular material 2.0.0-beta.1.

**Comment by drPavka** [comment]
Is there any way to apply this patch https://github.com/crisbeto/material2/commit/2f2cc8e0b6fe01d0e3a4ea7bb76918e47f9c1300 to the project 
until it will be merged to production branch?

**Comment by shedar** [comment]
@drPavka as a workaround you can add something like  *ngIf="options && options.length" to your md-select. This way component would not be initialized until options are ready.
