### ISSUE TITLE
Support hint text with select

### ISSUE THREAD

**Issue by jt-helsinki** [angular/material2#2498]
#### Bug, feature request, or proposal:

Feature request
#### What is the expected behavior?

```
<md-select ... >
    <md-option ... ></md-option>
    ...
    ...
    <md-hint>some hint text</md-hint>
</md-select>
```

#### What is the current behavior?

not supported

#### What is the use-case or motivation for changing an existing behavior?

A hint below the select box. This could be used (For example) as a validation message when the select is not selected. Behaviour similar to the <input> component.

#### Which versions of Angular, Material, OS, browsers are affected?

Material2 v2.0.0-beta.1
Angular 2.4.1

**Comment by SherwinJames** [comment]
Is there a recommended alternate way to handle error hints for md-select (e.g. required)?

**Comment by leonardovff** [comment]
@SherwinJames look the soluction of codef0rmer in this issue https://github.com/angular/material2/issues/2624

**Comment by dhineshwiz** [comment]
Can we something like 
`<div class="hint"> This is used as primary message</div>`
Supported in Md-Select

**Comment by sdargaud** [comment]
Please don't forget md-error.

**Comment by makdeniss** [comment]
For md-error for md-select I've done something like this:
```
<md-error *ngIf="type.touched && type.invalid">
          <span class="error-small-text" *ngIf="type.errors.required">
             Company Type is <strong>required</strong>
          </span>
</md-error>
```


```
.error-small-text {
  position: relative;
  top: -18px;
  font-size: 0.8em;
}
```

**Comment by finalxcode** [comment]
+1 @makdeniss cool

**Comment by jelbourn** [comment]
This is done now that select goes in mat-form-field
