### ISSUE TITLE
Problem: when pointing to the button, outline is visible.

### ISSUE THREAD

**Issue by Parez** [angular/material2#2503]
Not sure if it's a bug or it's just me. But when I mouse-down on the clickable element, it's default outline becomes visible. The strange thing is everything is ok with the demo-app I'm running in the same browser (Chrome).
I think it would be better to remove such behaviour by default if not done yet. It's especially not in-place for buttons with icons. 
<img width="507" alt="screen shot 2017-01-03 at 12 06 17" src="https://cloud.githubusercontent.com/assets/5672050/21603350/adb99be0-d1ad-11e6-8d68-d51e88eba4c6.png">

p.s.
I'm able to remove it. Just interested - shouldn't it be disabled by default.

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate further.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by realappie** [comment]
I think you are only importing the `MdButtonModule` correct?

**Comment by samtheprogrammer** [comment]
+1
