### ISSUE TITLE
Warning on use of deprecated elements

### ISSUE THREAD

**Issue by feloy** [angular/material2#2506]
#### Bug, feature request, or proposal:

It could be interesting to (optionally) get a message in the console or at compile time when using a deprecated element (md-input, ...).

#### Is there anything else we should know?

I'll have to replace deprecated elements in a project I'm working on. I'm available for working on/testing this work.

**Comment by jelbourn** [comment]
This would have been good if we had been able to include it in beta, but at this point we're already planning on removing the deprecated APIs in the next release, so there wouldn't be a timeframe in which people would see the warnings. We'll keep this in mind in the future, though.
