### ISSUE TITLE
bug: <md-select>: line spacing of the select element and distance/hight of its floating placehoder incorrect

### ISSUE THREAD

**Issue by chrisi** [angular/material2#2508]
#### What is the expected behavior?

http://plnkr.co/edit/0tnEStOBvtVodFQFVX3c?p=preview (2nd card)

#### What is the current behavior?

http://plnkr.co/edit/0tnEStOBvtVodFQFVX3c?p=preview (1st card)

#### Which versions of Angular, Material, OS, browsers are affected?
OS: Windows, Mac
Chrome 55.0.2883.87 m
Angular 2.3.1
Material 2.0.0-beta.1
Typescript 2.0.10

#### Is there anything else we should know?

this seems to fix the distance of the paceholder:
```
.md-select-placeholder.md-floating-placeholder {
    top: -20px; /* was -22px */
    left: -2px;
    transform: scale(.75);
}
```
line spacing can be corrected with:
```
style="margin: 10px 0 10px 0;"
```

**Comment by chrisi** [comment]
additional stylesheet issues with md-select:

-distance between text and baseline also differs from standard md-input.
-onEnter / onBlur doesn't fade like other md-inputs
-unlike md-inputs basline width of focused md-selects is only 1px

**Comment by chrisi** [comment]
is partially duplicated with #2465

**Comment by jelbourn** [comment]
Tracking via #2124
