### ISSUE TITLE
slider decimal point

### ISSUE THREAD

**Issue by phmello** [angular/material2#2511]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
when the step attribute is set to 0.1 it should increment the value accordingly
13.9
23.2

#### What is the current behavior?
the component is displaying huge fractions such as 
13.900000000000006
23.299999999999997

#### What are the steps to reproduce?

<md-slider [min]="-50" [max]="50" [step]="0.1" thumbLabel [(ngModel)]="annualReturn"></md-slider>

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://plnkr.co/edit/oeToNQlCIT3WZebLDAg5?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/material": "^2.0.0-alpha.11-3",

**Comment by anandsummer28** [comment]
It is still not working correctly.

For a step size of 0.005 it sometimes generates huge fractions like the prior case.
![image](https://user-images.githubusercontent.com/22359616/53073412-f2dff800-34b5-11e9-8218-019abbb925b6.png)
