### ISSUE TITLE
Focus on checkbox not working using keyboard navigation

### ISSUE THREAD

**Issue by arthurvieiras** [angular/material2#2520]
Bug, feature request, or proposal:

Bug

What is the expected behavior?

When a checkbox is selected it should display a rounded shadow around the component.

See 
[https://material.io/guidelines/components/selection-controls.html#selection-controls-radio-button](url)
[https://material.angularjs.org/latest/demo/checkbox](url)

What is the current behavior?

When you select it by clicking it, it works fine, but when navigating using Tab (keyboard navigation) it doesn't show any sign of being fucused.

What are the steps to reproduce?

Just navigate using Tab between the two checkbox provided below
http://plnkr.co/edit/fruZ4obuY9GzVuYDEKQG

**Comment by crisbeto** [comment]
https://github.com/angular/material2/pull/1730 should resolve this

**Comment by jelbourn** [comment]
Should be resolved now
