### ISSUE TITLE
md-icon svgSrc dont work

### ISSUE THREAD

**Issue by BamiGorengo** [angular/material2#2521]
I installed fresh,the latest Version of Material2.

md-icon: `<md-icon svgSrc="img/icons/social/facebook.svg"></md-icon>`

dont give out any icon. In Material1 it include the svg code in the html template. But for me in new Material absolutly nothing happens. I dont get any error to.

**Comment by fxck** [comment]
https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes-from-alpha11

> The svgSrc propert of <md-icon> has been removed. All SVG URLs must now be explicitly marked as trusted using Angular's DomSanitizer service.

**Comment by BamiGorengo** [comment]
Thanks! But this is so new that i find absolutly no guide how to use icons with DomSanitizer... I am realy bad with JavaScript. :)

**Comment by BamiGorengo** [comment]
hmmm sounds cool. is there allready a version of material icon in that format?

**Comment by armno** [comment]
If I have many icons in my app (50+), should I register each icon explicitly or is there a better approach for this? I was thinking about using [icon sets](https://github.com/angular/material2/blob/master/src/lib/icon/README.md#icon-sets) but not sure if it will be easy to maintain different icons (got from the designers) in a single SVG file myself.

**Comment by BamiGorengo** [comment]
I hope that it is possible to import a Material-Icon Component and pass the names into all modules. That its easy to include them with <md-icon svgIcon="md-thumb-up"></md-icon> (md) is a random suffix.

**Comment by medeirosrich** [comment]
I would also like to know if there is a way to register all icons globally

**Comment by EladBezalel** [comment]
Closing as i think this has been answered if you still have some questions please comment and i will reopen

**Comment by medeirosrich** [comment]
@EladBazelel
Would still love to see an example or documentation on how to Register all icons at once for use app wide with any component. Instead of repeating the registration in the constructor of each component.

**Comment by EladBezalel** [comment]
@medeirosrich can you open a new issue for that?

**Comment by BamiGorengo** [comment]
Please link the new issue here then, after opening it.

**Comment by CanKattwinkel** [comment]
Readme needs update:

https://github.com/angular/material2/blob/master/src/lib/icon/README.md

**Comment by Splaktar** [comment]
@CanKattwinkel Elad just opened a [PR](https://github.com/angular/material2/pull/2692) to fix the docs.

**Comment by mcblum** [comment]
Just finding this issue after trying to figure out how to set the default icon set provider in Angular Material for Angular 2+. Can I give it a file with all of the SVG definitions like I could in Angular Material 1?

**Comment by kxlow** [comment]
@mcblum Yes, you can. In fact, there's a tutorial to do just that on materialdesignicons.com (https://materialdesignicons.com/getting-started, scroll down to the Angular 2.x/4.x section).
