### ISSUE TITLE
Snackbar notification leaves message on page

### ISSUE THREAD

**Issue by largeDachshund** [angular/material2#2525]
#### Bug:
When I invoke Snackbar, the message appears both in a floating box and as text, just above the snackbar.
![image](https://cloud.githubusercontent.com/assets/7054672/21654348/fd6b7340-d269-11e6-8e24-819a42ccf037.png)

After the snackbar disappears, the text remains on the page.

#### What is the expected behavior?
When the snackbar is invoked, the text that appears on the page should not be shown.

#### Which versions of Angular, Material, OS, browsers are affected?
"angular-cli": "^1.0.0-beta.24"
"hammerjs": "^2.0.8",
"@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1"
"@angular/material": "^2.0.0-beta.1"

Chrome

#### Is there anything else we should know?
I created a service:
`@Injectable()
export class NotificationService {
    private _snackBarConfig: MdSnackBarConfig;

    constructor(public snackBar: MdSnackBar) {
        this._snackBarConfig = new MdSnackBarConfig();

        this._snackBarConfig.duration = 10000;
    }

    public callSnackBar(message: string) {
        this.snackBar.open(message, null, this._snackBarConfig);
    }`
Then, when I call it:
`this._msgNotification = "The system did not return any " +
                            "tenants.  You're session may have expired.  Please login, again.";

                        this._notifService.callSnackBar(this._msgNotification);`

**Comment by crisbeto** [comment]
One of those texts is supposed to be hidden and used to announce the snack bar to screen readers. Are you sure that you followed the [theming guide](https://github.com/angular/material2/blob/master/guides/theming.md) and included all of the necessary CSS?

**Comment by largeDachshund** [comment]
@crisbeto , I haven't had a chance to implement a theme.  Is it really required, then?

**Comment by crisbeto** [comment]
It is, because it provides some of the core styles, e.g. the backdrops will be transparent if you don't provide one. There are some pre-built ones that are distributed with the Material releases.

**Comment by largeDachshund** [comment]
@crisbeto , so, taking the example, how do i reference the theme in the template?  is it as simple as (app.component.html): 
`<div class="candy-apple-theme">
angular stuff here
</div>
`

**Comment by crisbeto** [comment]
You don't need to reference, you just include it as a regular CSS file somewhere in your HTML.

**Comment by largeDachshund** [comment]
i'm using angular-cli.  according to the example, you save it as a SASS file....don't do this?

**Comment by largeDachshund** [comment]
@crisbeto , thanks for the help.  I'm implementing the theme, now.  and i'm still seeing that text left by the snackbar notification!

**Comment by crisbeto** [comment]
Cool, glad to help. I'll consider this one resolved.

**Comment by largeDachshund** [comment]
yes.  consider it resolved.  there should be some explanation on Snackbar that theming is required.
