### ISSUE TITLE
Ripple Starts at Expanded State for Slide-Toggle in a Form In A Dialog.

### ISSUE THREAD

**Issue by antonyRoberts** [angular/material2#2533]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Ripple to only be visible when activated

#### What is the current behavior?
Ripple starts in its expanded state when in a form inside of a dialog box.

#### What are the steps to reproduce?
Use md-slide-toggle in a form inside of a md-dialog. 

Plunker of the Issue http://plnkr.co/edit/prSrEY3fxm5cyV5BXeLd?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.1.2, Material 2.0.0-beta.1, OS Windows 10, Chrome, Firefox 

#### Is there anything else we should know?
![slidetoggleripple](https://cloud.githubusercontent.com/assets/19535379/21666428/9ee3dc3a-d2bf-11e6-8013-64a6106e571b.png)

**Comment by crisbeto** [comment]
This is because Material focuses the first focusable element in a dialog for accessibility reasons. You can override it by setting the `tabindex`.

**Comment by antonyRoberts** [comment]
Thanks @crisbeto setting the tab index does in fact get rid of the ripple on the first slide-toggle in the dialog. This should probably be in the documentation

**Comment by DevVersion** [comment]
I agree, we had a bunch of similar issues for this. 

@crisbeto I think adding a small text to the `dialog` overview file, which says that the first tabbable element will be focused upon open, should be fine.
