### ISSUE TITLE
md-input dynamic type not being applied

### ISSUE THREAD

**Issue by starksds** [angular/material2#2534]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I wrap an input control and pass the type it should be applied

#### What is the current behavior?
The type does not get set in the markup so something like date or number does not work as expected

#### What are the steps to reproduce?
Use the input example and then wrap the example with your own component.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Documented features should work

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.1
Material 2 beta 1
Chrome

#### Is there anything else we should know?
here is a code example, the top works, the second doesn't:

```
Md example:
<md-input-container align="end">
    <input md-input placeholder="Number" type="number">
</md-input-container>

Base Input:
<md-input-container align="{{align}}">
    <input md-input type="{{type}}" placeholder="{{placeholder}}">
</md-input-container>

Implementation:
<my-input [align]="'end'"
    [placeholder]="'Number'"
    [type]="'number'">
</my-input>
```

**Comment by starksds** [comment]
Actually works if I use [attr.type]="type" instead of type={{type}} but still might be a bug

**Comment by crisbeto** [comment]
Not really a bug, this is how Angular 2's data binding works. Material doesn't do anything with the input, apart from projecting it inside the input container.

**Comment by starksds** [comment]
@crisbeto for what it is worth this worked before the introduction of the md-input-container
