### ISSUE TITLE
md-checkbox, md-radio-button still show the original input

### ISSUE THREAD

**Issue by n2lose** [angular/material2#2535]
#### Bug, feature request, or proposal:
I have installed angular-cli and material 2 on my local. I would like to do a template like this https://material2-app.firebaseapp.com/
but when in try added:
md-checkbox
md-radio-button

it still display the orginal input. Please see the image attached for details.
![md-checkbox-radio](https://cloud.githubusercontent.com/assets/443793/21668981/1831d252-d33a-11e6-8f59-d7f359a64b75.png)

#### What is the expected behavior?
It should be show like this
![m2app](https://cloud.githubusercontent.com/assets/443793/21668982/1cdebb4e-d33a-11e6-90e3-d3ab7134f482.png)

#### What is the current behavior?
1. In the [getting started](https://material.angular.io/guide/getting-started) to install new project angular cli and angular material, install font-icons OK
2. In the [theme guide](https://material.angular.io/guide/theming)
```
@import '~@angular/material/core/theming/_all-theme.scss';
@include md-core();

$primary: md-palette($md-deep-purple);
$accent:  md-palette($md-amber, A200, A100, A400);
$warn:    md-palette($md-deep-orange);
$theme: md-light-theme($primary, $accent);

@include angular-material-theme($theme);

.m2app-dark {
  $dark-primary: md-palette($md-pink, 700, 500, 900);
  $dark-accent:  md-palette($md-blue-grey, A200, A100, A400);
  $dark-warn:    md-palette($md-deep-orange);

  $dark-theme: md-dark-theme($dark-primary, $dark-accent, $dark-warn);

  @include angular-material-theme($dark-theme);
}
```

#### Which versions of Angular, Material, OS, browsers are affected?
angular-cli: "version": "1.0.0-beta.24",
"@angular/material": "^2.0.0-beta.1",
Chrome/Window10

**Comment by DevVersion** [comment]
I'm a bit confused from the `What is the current behavior` answer -  did you create a theme for your project?

**Comment by alexandermikuta** [comment]
I have the same issue without any included theme.

**Comment by n2lose** [comment]
Yes, to fix it this issue, i have to import the one of prebuilt themes in the app.component.html : 
```
<!--<link href="https://rawgit.com/angular/material2-builds/master/core/theming/prebuilt/deeppurple-amber.css" rel="stylesheet">-->
<link href="https://rawgit.com/angular/material2-builds/master/core/theming/prebuilt/indigo-pink.css" rel="stylesheet">
<!--<link href="https://rawgit.com/angular/material2-builds/master/core/theming/prebuilt/pink-bluegrey.css" rel="stylesheet">-->
<!--<link href="https://rawgit.com/angular/material2-builds/master/core/theming/prebuilt/purple-green.css" rel="stylesheet">-->
```

Can I create a new theme (default-theme.scss) and import it in app.component.ts or app.component.scss ?
Example: default-theme.scss
```
@import '~@angular/material/core/theming/_all-theme';

// Include non-theme styles for core.
@include md-core();

.default-theme {
  // Define a theme.
  $primary: md-palette($md-cyan, 500);
  $accent:  md-palette($md-amber, A200, A100, A400);
  $warn:    md-palette($md-deep-orange);

  // Create the theme object (a Sass map containing all of the palettes).
  $default-theme: md-light-theme($primary, $accent, $warn);

  @include angular-material-theme($default-theme);

}
```
and in the app.component.scss : 
`@import 'default-theme.scss';`

I think it can make structure files in the app clearly, easy to understand and working on that.

Thanks,
Lam
