### ISSUE TITLE
Integrate circular loader with FAB

### ISSUE THREAD

**Issue by dasois** [angular/material2#254]
The Material Design Specification defines that the floating action button [can have a circular progress indicator integrated.](https://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators)

[--> One native Android implementation](https://github.com/JorgeCastilloPrz/FABProgressCircle)

This is not implemented in Angular Material 1.x but would be a very nice feature.

**Comment by DevVersion** [comment]
That's how it would look with Material 1 (just a little preview - play) http://codepen.io/DevVersion/pen/vGebGB

**Comment by GongT** [comment]
+1

**Comment by DevVersion** [comment]
I'm currently working on that feature. 

- https://i.gyazo.com/4cb5fe4e70c4845e58d1c382d95f1eed.mp4

I think it matches the spec really good.

**Comment by dasois** [comment]
sweet! :+1:

**Comment by DevVersion** [comment]
PR is not referenced yet, because I wanted to get some feedback before. - #290

**Comment by dasois** [comment]
This looks very good!

If you are looking at the Material Design spec for it, they have some other sort of animation. Would it be possible to integrate that, too?

**Comment by DevVersion** [comment]
At the moment the animation is depending on the circle (`determinate` and `indeterminate`). I would like to address those other animations after the actual component is landed.

**Comment by jelbourn** [comment]
Closing this since there are no plans to add this feature.
