### ISSUE TITLE
MdSnackBarConfig does not have duration property

### ISSUE THREAD

**Issue by tcrack326** [angular/material2#2540]
#### Bug, feature request, or proposal:
MdSnackBarConfig has no property duration and the README seems to be outdated with the correct property name for the politeness.

#### What is the expected behavior?
I expect the property duration to exist on a MdSnackBarConfig and the README to have the correct name for the politeness property.

#### What is the current behavior?
There is no duration property on the MdSnackBarConfig. The README lists the 'politeness' property as 'role'.

#### What are the steps to reproduce?
Create a new MdSnackBarConfig and try to set duration. The property currently doesn't exist and the 'role' property is called 'politeness'.
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Need a duration to get rid of snackbar after period of time.

#### Which versions of Angular, Material, OS, browsers are affected?
All

#### Is there anything else we should know?
No

**Comment by melocotton** [comment]
I just implemented a MdSnackBar with MdSnackBarConfig and duration yesterday and it works for me. (material 2.0.0-beta.1). You can also make it permanent (and add a close button) with a duration set to 0.

**Comment by DevVersion** [comment]
Yeah, can you please provide a Plunker for your issue?

**Comment by tcrack326** [comment]
Sorry for the confusion, npm led me to believe I had the current version (2.0.0-beta.1) when I guess it was really outdated although npm outdated did not tell me it was. I re-installed the packages with the correct version and I see the duration property now and it is working normally. Sorry again, I'll close the issue.

**Comment by DevVersion** [comment]
Glad to hear that it works now. Thanks for the update.
