### ISSUE TITLE
Input - Icon Support

### ISSUE THREAD

**Issue by BamiGorengo** [angular/material2#2541]
I tryed to add a Icon to a Input with md-prefix, but it looks little strange. Anyone know about plans, that if anyone place a icon with <i> tag inside the "md-prefix" that it is correct styled? i think its a good idea to implement any way to include icons.

**Comment by BamiGorengo** [comment]
Just give the.md-input-infix a display flex...

**Comment by jelbourn** [comment]
@mmalerba did your latest input change touch on the style of icons in prefix/suffix?

**Comment by mmalerba** [comment]
It did, I changed the behavior to match the spec. @BamiGorengo can you include a plunker to reproduce?

**Comment by SimplerSoftware** [comment]
Just ran into this issue I believe after upgrading from Beta 6 to Beta 7.  I've created a plunker for you [here](http://plnkr.co/edit/VkApx0?p=preview).  In Beta 6 the icons would be on the same row something like this: 
![image](https://user-images.githubusercontent.com/11198735/27880435-2cf49c20-6182-11e7-9a28-ea1e3349f2ab.png)

**Comment by mmalerba** [comment]
Ah, the deprecated `md-suffix` and `md-prefix` have been removed, use `mdSuffix` and `mdPrefix` instead: http://plnkr.co/edit/SehrHvb2a6BGyp2AHZ9i?p=preview

**Comment by SimplerSoftware** [comment]
That worked!  I guess I hadn't seen that those were deprecated. Thanks for pointing that out!
