### ISSUE TITLE
Mdtooltip Not Working

### ISSUE THREAD

**Issue by darrenbrett** [angular/material2#2543]
Since I've been having trouble getting the mdTooltip to work in my Angular 2 app, I decided to try it in a fresh install of the Angular CLI. Even there, it's not working. I can use md-raised-button and get it working easily enough, but the tooltip does nothing when I scroll over the text.

My setup: 
Macbook Air
OS X El Capitan, 
Angular-cli: 1.0.0-beta.24
Node: 6.8.0

Here is what I have in my package.json:

```
{
  "name": "jan",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/material": "^2.0.0-beta.1",
    "@angular/router": "^3.3.1",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3"
  }
}
```

And here's my app.module.ts file contents:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { MaterialModule } from '@angular/material';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    MaterialModule.forRoot(),
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  exports: [
        MaterialModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Then, in my root app.component.html file, I have this:

```
<h1>
  {{title}}
</h1>

<button md-raised-button>RAISED</button>
<p mdTooltip="Tooltip!">I have a tooltip</p>
```

I see the interpolation working.
I see the raised button working.
I see the text "I have a tooltip".
But when I scroll over that text, no tooltip shows up.

**Comment by jmcgoldrick** [comment]
Are you applying a theme? (https://github.com/angular/material2/blob/master/guides/getting-started.md#include-the-core-and-theme-styles)

**Comment by darrenbrett** [comment]
I shouldn't need to, should I? If the button components work as is, I assume the same should be the case for a very basic tooltip.

**Comment by darrenbrett** [comment]
Thanks to jmcgoldrick, I did get this resolved. Two things were necessary: 
1.) mdTooltip requires hammerjs. 
2.) I need to add this to my root CSS:
@import '~@angular/material/core/theming/prebuilt/deeppurple-amber.css';

After that, it's working. :)

**Comment by SpEcHiDe** [comment]
I am using material.angular.io in one of my projects. The MdToolTip thing is working in FireFox, but not working in chrome. 

Please help me in debugging.
