### ISSUE TITLE
MdSidenav should provide an option to disable the default functionality of closing the sidenav when escape is pressed

### ISSUE THREAD

**Issue by s992** [angular/material2#2544]
Currently, there is not an easy way to prevent sidenav from closing when the escape key is pressed due to the [`handleKeyDown` method](https://github.com/angular/material2/blob/master/src/lib/sidenav/sidenav.ts#L235) on MdSidenav.

It would be ideal to have a way to override this method, or at least be able to provide a boolean indicating that we do or do not want escape to close the sidenav.

For anyone searching for a workaround, it can be accomplished by using `ViewChild` and overriding the method in `ngAfterViewInit` (only including relevant bits in this snippet):

```js
import { ViewChild, AfterViewInit } from '@angular/core';
import { MdSidenav } from '@angular/material';

export class SidebarComponent implements AfterViewInit {
  @ViewChild(MdSidenav) sidenav: MdSidenav;

  ngAfterViewInit() {
    this.sidenav.handleKeydown = () => {};
  }
}
```

**Comment by crisbeto** [comment]
Should be taken care of with https://github.com/angular/material2/pull/2501.

**Comment by s992** [comment]
Sounds good! Closing this as a duplicate, then.

**Comment by ManuelQuiroz** [comment]
include property **disableClose** : boolean
```
<md-sidenav-container>
       
        <md-sidenav opened mode="side" disableClose="true"   >
        <!-- sidenav content -->
        </md-sidenav>

  <!-- primary content -->
</md-sidenav-container>
```
