### ISSUE TITLE
when value is bound to input, the placeholder overlaps with the value

### ISSUE THREAD

**Issue by kkarandikar0807** [angular/material2#2545]
#### What is the expected behavior?

Placeholder should be at the top left corner when value is entered
#### What is the current behavior?

when value is bound to input, the placeholder overlaps with the value.
The placeholder and value are at the same place
#### What are the steps to reproduce?
Just bind a value to the <md-input-container>
<input md-input value="{{boundValue}}"
</md-input-container>
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by fxck** [comment]
first of all, you should not do 

```html
<input value="{{boundValue}}" />
```

and do this instead 

```html
<input [value]="boundValue" />
```

while it might work, it's simply not valid way of doing things in angular(2)

...as for the actual problem, it was recently fixed, so it will be working in the next release(you can use https://github.com/angular/material2-builds meanwhile)

**Comment by crisbeto** [comment]
Sounds like something that https://github.com/angular/material2/pull/2455 should fix.

**Comment by BansalPooja** [comment]
still facing this issue with material version 5.0.4
