### ISSUE TITLE
material.angular.io/components section missing scrollbars

### ISSUE THREAD

**Issue by goelinsights** [angular/material2#2548]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Able to scroll down to see full examples.  Exists on other parts of site, including the menu sidebar on the left, but missing in the components body section.

#### What is the current behavior?
Unable to view content beyond the fold
![ngmaterial](https://cloud.githubusercontent.com/assets/2880781/21710745/759b5b06-d39f-11e6-8c9a-a111df99656e.jpg)

#### What are the steps to reproduce?

Visit url: https://material.angular.io/components/component/slide-toggle and note that scrollbars don't exist on right edge of the page enabling scrolling

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Able to fully explore the documentation and examples

#### Which versions of Angular, Material, OS, browsers are affected?
Chrome 50

#### Is there anything else we should know?
Happy to do a pull request if you point me to the docs repo.

**Comment by fxck** [comment]
![screen shot 2017-01-06 at 08 47 30](https://cloud.githubusercontent.com/assets/1303561/21711057/e6793f1c-d3ec-11e6-9204-574337e74f82.png)

works fine for me(Version 55.0.2883.95 (64-bit))

also wrong repo https://github.com/angular/material.angular.io

**Comment by melocotton** [comment]
The scroll bar you are mentioning exists, it is just that sometimes it doesn't work if you try to use scroll wheel with your mouse in the middle of the page (you have to click inside the page to reactivate scrolling).

**Comment by fxck** [comment]
not experiencing that either, works fine even when chrome is out of focus

**Comment by goelinsights** [comment]
Strange, it works fine for me in Firefox but I'm unable to get it working in chrome.  Happy to close if its just me (could be an extension) but curious if its a problem for anyone else, as I'm not seeing an error or any blocking elements.  
Chrome version: 50.0.2661.94 (64-bit) on a macbook pro

**Comment by crisbeto** [comment]
Please direct issues with the site to its repo https://github.com/angular/material.angular.io/issues
