### ISSUE TITLE
Documentation website freezes when clicking the Pizza Party button repeatedly

### ISSUE THREAD

**Issue by larsrotgers** [angular/material2#2550]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Website should not freeze.

#### What is the current behavior?
Website freezes, and stops functioning.

#### What are the steps to reproduce?
Click the Pizza Party button repeatedly @ (https://material.angular.io/components/component/snack-bar)
Spam left mouse button.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Site shouldn't break.

#### Which versions of Angular, Material, OS, browsers are affected?
No idea, its on https://material.angular.io/components/component/snack-bar. I'm using Google Chrome.

#### Is there anything else we should know?
https://material.angular.io/components/component/snack-bar

**Comment by crisbeto** [comment]
This was fixed with https://github.com/angular/material2/pull/2392, but hasn't been released yet.
