### ISSUE TITLE
Get started with Angular Material 2 :: Docs Incorrect

### ISSUE THREAD

**Issue by sachinvettithanam** [angular/material2#2554]
#### Bug, feature request, or proposal:
Bug :: incorrect Docs https://material.angular.io/guide/getting-started

#### What is the expected behavior?
Incorrect systemjs configuration ::
@angular/material': 'npm:@angular/material/material.umd.js'
actual is
@angular/material': 'npm:@angular/material/bundles/material.umd.js'

#### What is the current behavior?
File Not Found :: nothing works for those who follow material.angular.io :: Proper docs can be found on https://github.com/angular/material2/blob/master/guides/getting-started.md

**Comment by sunshineo** [comment]
I just experienced this problem. Really bad first impression.

**Comment by DevVersion** [comment]
We have fixed this with SHA https://github.com/angular/material2/commit/d286e6d6472910ab41b8437d405cd3e902c9c848
