### ISSUE TITLE
md-menu binding # dynamic

### ISSUE THREAD

**Issue by loongdefect** [angular/material2#2559]
Hi all,
I want to assign the md-menu trigger action as the code below, but failed. Can you guide me?

```html
  <div *ngFor="let menuItem of mainMenu">
   <div ng-if="menuItem.item.length > 0">
    <button md-button [mdMenuTriggerFor]="menuItem.mdMenuTriggerFor">
     <md-icon svgIcon="{{menuItem.icon}}"></md-icon>
     <span>{{menuItem.title}}</span>   
    </button>
    <md-menu {{menuItem.mdMenuTriggerFor}}="mdMenu">
     <div *ngFor="let item of menuItem.item">
      <button md-menu-item routerLink="{{item.routerLink}}">
       <md-icon svgIcon="{{item.icon}}"></md-icon>
       <span>{{item.title}}</span>
      </button>
     </div>
    </md-menu>
   </div>
   <div ng-if="menuItem.item.length == 0">
    <button md-button routerLink="{{menuItem.routerLink}}">
     <md-icon ng-if="menuItem.icon.length != 0" svgIcon="{{MenuItem.icon}}"></md-icon>
     <span>{{menuItem.title}}</span>   
    </button>
   </div>
```

**Comment by loongdefect** [comment]
Closed

**Comment by mblundred-yseop** [comment]
What was the fix? I'm having this problem too.

**Comment by EladBezalel** [comment]
@mblundred-yseop please read the menu documentation: 
https://material.angular.io/components/component/menu
https://github.com/angular/material2/blob/master/src/lib/menu/README.md

**Comment by apeter10** [comment]
@EladBezalel Could you please give me some examples? I have the same problem.

**Comment by loongdefect** [comment]
I binding with same ref name.

**Comment by apeter10** [comment]
@loongdefect I write the code in Plunker but failed. Could you please help me?
`http://plnkr.co/edit/qRB9rT`

**Comment by loongdefect** [comment]
display correct
'<div *ngFor="let menuItem of menus">'
    '<button md-button [mdMenuTriggerFor]="menu">'
        '<span>{{menuItem.title}}</span>'
    '</button>'
    '<md-menu #menu="mdMenu">'
      '<button md-menu-item>Refresh - {{menuItem.title}}</button>'
      '<button md-menu-item>Settings - {{menuItem.title}}</button>'
    '</md-menu>'
'</div>'

**Comment by bhawin-bigstep** [comment]
Only first button is working via this example @loongdefect
