### ISSUE TITLE
Getting started guide doesn't compile

### ISSUE THREAD

**Issue by mtman** [angular/material2#2568]
Following the steps:
https://github.com/angular/material2/blob/master/guides/getting-started.md
1. `ng new myproj`
2. `npm install --save @angular/material`
3. Add to app.module.ts:
```
import { MaterialModule } from '@angular/material';
// other imports 
@NgModule({
  imports: [MaterialModule.forRoot()],
  ...
})
export class PizzaPartyAppModule { }
```
4. Add `@import '~@angular/material/core/theming/prebuilt/deeppurple-amber.css';` to style.css
5. `ng serve`

Error:
```
node_modules\loader-runner\lib\LoaderRunner.js:109
                        throw e;
                        ^
TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (node_modules\source-map\lib\source-node.js:115:26)
...
```

Win 10
Node 7.4.0, both x64 and x86 
@angular/material@2.0.0-beta.1
angular-cli@1.0.0-beta.24
@angular/compiler@2.4.2

**Comment by kuncevic** [comment]
Use Node 6, I am on version 6.9.2 all working for me.

**Comment by mtman** [comment]
That doesn't make a difference in my case (2.4.x compiler).

There's a new error for 2.4.3:
```
PS myproj> ng serve
** NG Live Development Server is running on http://localhost:4200. **
Hash: 88cf857cc3bed4b67def
Time: 20480ms
chunk    {0} styles.bundle.js, styles.bundle.map (styles) 123 bytes {2} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.map (main) 2.49 MB [initial] [rendered]
chunk    {2} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in myproj/src/environments/environment.ts
Module build failed: TypeError: Cannot read property 'text' of undefined
    at IdentifierObject.TokenOrIdentifierObject.getText (myproj\node_modules\typescript\lib\typescript.js:53644:56)
    at myproj\node_modules\@ngtools\webpack\src\loader.js:83:72
    at Array.some (native)
    at myproj\node_modules\@ngtools\webpack\src\loader.js:83:32
    at Array.filter (native)
    at _removeModuleId (myproj\node_modules\@ngtools\webpack\src\loader.js:82:10)
    at myproj\node_modules\@ngtools\webpack\src\loader.js:167:48
 @ myproj/src/main.ts 4:0-57
 @ multi main

ERROR in myproj/src/app/app.module.ts
Module build failed: TypeError: Cannot read property 'text' of undefined
    at IdentifierObject.TokenOrIdentifierObject.getText (myproj\node_modules\typescript\lib\typescript.js:53644:56)
    at myproj\node_modules\@ngtools\webpack\src\loader.js:83:72
    at Array.some (native)
    at myproj\node_modules\@ngtools\webpack\src\loader.js:83:32
    at Array.filter (native)
    at _removeModuleId (myproj\node_modules\@ngtools\webpack\src\loader.js:82:10)
    at myproj\node_modules\@ngtools\webpack\src\loader.js:167:48
 @ myproj/src/main.ts 5:0-45
 @ multi main
webpack: bundle is now VALID.
```

I've tested the project on Ubuntu (same toolset) and it works there.

> angular-cli: 1.0.0-beta.25.5
node: 7.4.0
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

**Comment by kuncevic** [comment]
Once you changed to `Node 6.x` did you remove the `node_modules` folder and then run `npm install`

**Comment by mtman** [comment]
You are right, the new error is no longer material specific -- it now occurs in a basic project as well. I removed node_modules and ran it again using node 6.9.2 but the error remains. Ng has installed typescript 2.0.10.
