### ISSUE TITLE
Support non-floating placeholder with select

### ISSUE THREAD

**Issue by Faris-AH** [angular/material2#2569]
#### Bug, feature request, or proposal:

Feature request
#### What is the expected behavior?
<md-select [floatingPlaceholder]:boolean >
    <md-option ... ></md-option>
<\/md-select>
or
<md-input-container [floatingPlaceholder]:boolean>   
 <md-select ...>
       <md-option ... ></md-option>
   <\/md-select>
 <\/md-input-container>
 
#### What is the current behavior?
not support

#### What is the use-case or motivation for changing an existing behavior?
Input elements  can have floating or non-floating placeholder .Select can be use with  input elements.
Select should have floating or non-floating placeholder.Similar to <md-input-container>

#### Which versions of Angular, Material, OS, browsers are affected?
Material2 v2.0.0-beta
Angular 2.4.1

**Comment by fxck** [comment]
Damn, this is like the third issue I was about to open today and try to fix, only to found out it's not only already open but has a PR as well. What is the reason for PRs not being reviewed/merged @crisbeto? Does it have something to do with prior testing on internal google apps? Or is it just that Kara and Jeremy are busy with their own stuff?

**Comment by crisbeto** [comment]
Well, people are busy and Jeremy is on vacation for a bit.
