### ISSUE TITLE
Toolbar Style not applied when not placed in styles.scss

### ISSUE THREAD

**Issue by JDillon522** [angular/material2#2573]
#### Bug, feature request, or proposal: 

Bug

#### What is the expected behavior?

I have two material components on my test app: a toolbar and a card. Both located in `app.component.html`. 

```
<div>
  <md-toolbar color="primary">

      <span><h2>Angular 2</h2></span>

      <button md-icon-button [md-menu-trigger-for]="menu">
        <md-icon class="material-icons">menu</md-icon>
      </button>

  </md-toolbar>

  <md-menu x-position="before" #menu="mdMenu">
    <button md-menu-item>Option 1</button>
    <button md-menu-item>Option 2</button>
  </md-menu>

  <md-card>
       Content
  </md-card>

</div>
```

In `app.component.scss` I have the following simple styles:

```
md-toolbar-row {
  justify-content: space-between;
}


md-card {
  max-width: 95%;
  margin: 0.5em auto;
  text-align: center;
}
```

The toolbar renders with "Angular 2" on the left side and the menu icon on the right. 
The card renders normally.

#### What is the current behavior?
The `md-card` renders with the applied styles. However the `md-toolbar-row` does not even though the style is in the generated `<style>` tag in the head. 

Whats odd is that the `md-toolbar-row` renders properly if I move the relevant styles into the `styles.scss` file. 

#### What are the steps to reproduce?

PLUNKER: http://plnkr.co/edit/ujMnYCZgMuLvOX3647hW?p=preview

I dont know how to show the difference when its applied to the `styles.scss` file in Plunker. Sorry.

#### Which versions of Angular, Material, OS, browsers are affected?
```
ng --version

angular-cli: 1.0.0-beta.24
node: 6.9.3
os: darwin x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2
```

**Comment by DevVersion** [comment]
Please provide a screenshot of your app?

**Comment by JDillon522** [comment]
When the following style is in `app.component.scss`:
```
md-toolbar-row {
  justify-content: space-between;
}
```
![screen shot 2017-01-09 at 4 55 28 pm](https://cloud.githubusercontent.com/assets/4861202/21770606/a245c642-d68c-11e6-8d33-47d79e4e0c4c.png)

And when its in `styles.scss`:
![screen shot 2017-01-09 at 4 56 04 pm](https://cloud.githubusercontent.com/assets/4861202/21770623/af834762-d68c-11e6-9b6a-d8ed7a4ddf4c.png)

**Comment by DevVersion** [comment]
It doesn't look like an issue of Material 2, since the components render properly. It looks more like the SCSS is not compiled properly for the component.

**Comment by JDillon522** [comment]
Whats odd though is that it renders the styles properly when placed in `app.component.scss`, and its being applied to `md-card` but not being applied to `md-toolbar-row`.

```
// app.component.scss
md-toolbar-row {
  justify-content: space-between;
}

md-card {
  max-width: 95%;
  margin: 0.5em auto;
  text-align: center;
}
```

![screen shot 2017-01-09 at 6 04 31 pm](https://cloud.githubusercontent.com/assets/4861202/21773009/1ce5972a-d696-11e6-92cb-7ff8024425b0.png)

![screen shot 2017-01-09 at 6 05 23 pm](https://cloud.githubusercontent.com/assets/4861202/21773056/431b83e6-d696-11e6-857c-ddbca6ed6f46.png)
![screen shot 2017-01-09 at 6 05 34 pm](https://cloud.githubusercontent.com/assets/4861202/21773055/4317f712-d696-11e6-8542-97feca10d0e1.png)

**Comment by DevVersion** [comment]
Ah I understand. That's due to Angular's View Encapsulation which ensures that styles from a component can't affect elements of another component.

```html
<md-card comp-1-app>

   <!-- Inside of the `md-card` component -->
  <md-card-content comp-2-card></md-card-content>
  <md-card-actions comp-2-card></md-card-actions>

</md-card>

<md-toolbar comp-1-app>

  <!-- Inside of the `md-toolbar` component -->
  <md-toolbar-row comp-3-toolbar></md-toolbar-row>

</md-toolbar>
```

So all styles from your `app.component.scss` will only apply to elements which are inside of your component.

So the children of the `md-toolbar` and `md-card` are not affected by any CSS change.

There are tricks to make the CSS change though. See the `/deep/` selector

```scss
/deep/ md-toolbar-row {
  /* STYLES */
}
```

Read more here: https://angular.io/docs/ts/latest/guide/component-styles.html

**Comment by JDillon522** [comment]
Ahh gotcha. That fixed it. I'll read up on the `/deep/` selector. Havent come across that one before. 

Thanks.

**Comment by codeepic** [comment]
As of April 2019 (and possibly some time before that) `/deep/` is deprecated.
[https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep )
