### ISSUE TITLE
Sidenav mode not honored on IE 11

### ISSUE THREAD

**Issue by xzy3** [angular/material2#2577]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-sidenav mode="slide" pushes main content out.

#### What is the current behavior?
Chrome resizes content correctly:
![image](https://cloud.githubusercontent.com/assets/7871125/21772435/39e9fb1e-d659-11e6-8911-151caa85380e.png)

IE acts like the sidenav is set to mode="over":
![image](https://cloud.githubusercontent.com/assets/7871125/21772454/4e9f0a90-d659-11e6-807a-fc8173e49ac0.png)

#### What are the steps to reproduce?

http://embed.plnkr.co/oFBZS1JvEDMFeK1TpdsC/

#### Which versions of Angular, Material, OS, browsers are affected?
IE 11.0.9600.18537
Material 2.0.0-alpha.8-2
Angular 2.4.1
Windows 7 Enterprise

**Comment by mmalerba** [comment]
updated the provided example to work with the latest version and it seems to be correct on IE11 http://plnkr.co/edit/hroO31xhoySL6jQ2A3AN?p=preview
