### ISSUE TITLE
Doc error material.angular.io

### ISSUE THREAD

**Issue by thibaultsavary** [angular/material2#2579]
There's an error in the documentation of the card:
https://material.angular.io/components/component/card

_An `<md-title-group>` can be used to combine a title, subtitle, and image into a single section. This element can contain:
..._

It should be `<md-card-title-group>`

**Comment by irfanhudda** [comment]
I would like to fix this

**Comment by M-a-c** [comment]
@jelbourn I think this one is 

- [x] done

https://github.com/angular/material2/pull/2607/files/49aba6106c821dac00900762589de23e660de9f0
was merged.
