### ISSUE TITLE
Missing value-field in md-checkbox

### ISSUE THREAD

**Issue by Undrium** [angular/material2#2583]
Dove deep into trying to find a reason to exclude the value field. Is there any plans on a native option to set the value of a md-checkbox or are we bound to Booleans? From experience of all the 100s of checkbox fields I have encountered they are rarely used for straight true/false value extraction. 

It seems most solutions around this are that you will have to translate the input from the change attribute.

**Comment by jelbourn** [comment]
Indeed, `value` should be forwarded to the underlying native checkbox (which is used as the submission value for the form).
