### ISSUE TITLE
md-icon as input prefix / prefix on wide inputs 

### ISSUE THREAD

**Issue by fxck** [angular/material2#2586]
currently this happens when you try to use `md-icon` in a prefix
![image](https://cloud.githubusercontent.com/assets/1303561/21807898/2081b0d4-d741-11e6-8ab8-82c8f31aa95b.png)

there two issues

1) icon is too big, which messes with input's alignment 
![image](https://cloud.githubusercontent.com/assets/1303561/21807959/62020090-d741-11e6-8cfd-e986e3fccf85.png)

2) icon is too wide, which meses with `display: table-cell` and pushes the input unreasonably far right

should this even supported? I could work on it I guess

also why is table cell used instead of flex? it's hacky and puts way too much space around prefix even if I used `$`(if my md-input is wide)
![image](https://cloud.githubusercontent.com/assets/1303561/21808126/28a2061e-d742-11e6-9767-249837872523.png)

**Comment by crisbeto** [comment]
In regards to flexbox, I agree that it would be better to use. Otherwise I think that https://github.com/angular/material2/pull/2496 may fix this.

**Comment by fxck** [comment]
it will probably fix the stretching(but I think it would be worth converting to flex instead), but not the vertical alignment

**Comment by kara** [comment]
Fixed by https://github.com/angular/material2/pull/3342

**Comment by marshall007** [comment]
@kara @mmalerba the same issue pops up when using `md-icon` within an `md-placeholder`. I wasn't sure if I should create a separate issue or if you just want to reopen this one as it's essentially the same bug.

This is solved by applying the same fix from #3342 to `.mat-input-placeholder .mat-icon`. Alternatively, it seems that all three cases (prefix/suffix/placeholder) could potentially be handled more generally as `.mat-input-container .mat-icon`.

**Comment by marshall007** [comment]
Upon further investigation, `.mat-input-container .mat-icon` is almost certainly the way to go in terms of future-proofing. I just noticed `md-hint > md-icon` has the same issue (and same resolution).
