### ISSUE TITLE
Adding Chips to Input

### ISSUE THREAD

**Issue by arat3091** [angular/material2#2587]
#### Bug, feature request, or proposal:
Just like material one we should be able to add the chips to the input fields , remove the chips from the input field and a proper example to showcase how to do it.

This is a very common requirement these days.

material 1 example
https://material.angularjs.org/latest/demo/chips

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by fxck** [comment]
Both chips and autocomplete are WIP, I'm sure both "tagging" and "contact chips"(hopefully this will be named something better and be made more universal) will probably be coming after those two are finished.

**Comment by EladBezalel** [comment]
This would be part of #120
