### ISSUE TITLE
Error when testing components dynamically created inside an MdDialog

### ISSUE THREAD

**Issue by JDillon522** [angular/material2#2588]
#### Bug, feature request, or proposal:
Bug / Help

#### What is the expected behavior?
I import `MdDialogModule.forRoot()` and `MdDialogRef` in my `TestBed` and execute my tests. 

#### What is the current behavior?
I have the following setup:
```
TestBed.configureTestingModule({
      declarations: [
        AddUserComponent
      ],
      imports: [
        MaterialModule.forRoot(),
        MdDialogRef
      ]
    })
    .compileComponents();
```

When I run my tests I get the following error:
> Failed: Unexpected value 'MdDialogRef' imported by the module 'DynamicTestModule'

#### What are the steps to reproduce?
You should be able to reproduce this by creating two components, one the parent container that launches the dialog, and the other being the content for the dialog. Then run your tests.

#### Which versions of Angular, Material, OS, browsers are affected?
```
angular-cli: 1.0.0-beta.24
node: 6.9.3
os: darwin x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2
```

#### Is there anything else we should know?

The dialog works just fine in the app, but testing the component used in it fails.

**Comment by JDillon522** [comment]
Any advice on how to fix my tests?

I would recommend a section in the docs for each component on how to handle testing components like this.

**Comment by jelbourn** [comment]
`MdDialogRef` is a simple class, not an NgModule.
