### ISSUE TITLE
Sidenav - provide means to open/close from non-child elements

### ISSUE THREAD

**Issue by robwormald** [angular/material2#2591]
#### Bug, feature request, or proposal:

Given usage like:
```html
<md-sidenav-container>
  <md-sidenav>
    <ul></ul>
  </md-sidenav>
  <my-component></my-component>
</md-sidenav-container>
```

Because `my-component` is not a child of the `md-sidenav` element, you can't inject MdSidenav into it, which makes programmatically toggling the Sidenav rather difficult (either you end up having to @ViewChild() query for it, and wiring that all up through your own service)

#### What is the expected behavior?

Developers should have an easy way to programmatically control the md-sidenav 

#### What is the current behavior?

See above

#### Is there anything else we should know?

Material 1 provided a `$sideNav` service, which is the kind of thing i'm describing here: https://material.angularjs.org/latest/api/service/$mdSidenav

**Comment by EladBezalel** [comment]
@jelbourn do we want to stick with the `component-id` functionality from material1 or do you have something else in mind?

**Comment by jelbourn** [comment]
@robwormald I took a look at this, and `MdSidenavContainer` does let you do this already. The tricky thing is that the container can have two `MdSidenav` instances (one on the left and one on the right). You get these through `sidenavContainer.start` and `sidenavContainer.end`. Maybe not the best names, but it exposes the instance. 

@EladBezalel ideally people who are just using one sidenav would want to just inject `MdSidenav` and get the instance they care about, but I'm not sure we have any mechanism to do this. Creating a separate service and getting the sidenav by some name/id is about the same as injecting `MdSidenavContainer` and accessing the `start`/ `end` sidenav.
