### ISSUE TITLE
No app.module.ts on src folder

### ISSUE THREAD

**Issue by kingkarki** [angular/material2#2593]
There is not app.module.ts file on my project.

I went through the getting started guide here https://github.com/angular/material2/blob/master/guides/getting-started.md

i did ` ng new my-project`
`npm install --save @angular/material`

and doc says 
```
Import the Angular Material NgModule

src/app/app.module.ts

import { MaterialModule } from '@angular/material';
// other imports 
@NgModule({
  imports: [MaterialModule.forRoot()],
  ...
})
export class PizzaPartyAppModule { }

```
when i check src/app/ folder there is no app.module.ts file.
Is doc out dated or i did some mistake? 

My node version is v6.9.4

**Comment by DevVersion** [comment]
I just created an Angular CLI project and there is a `app.module.ts` file for me.

What Angular-CLI version do you use?

**Comment by kingkarki** [comment]
angular-cli: 0.1.0
node: 6.9.4
os: darwin x64

**Comment by DevVersion** [comment]
@kingkarki Did you solve your issue?

**Comment by kingkarki** [comment]
yes actually it was not the real issue. It was my confusion. app.module.ts was my projectname.module.ts. Thanks @DevVersion

**Comment by DevVersion** [comment]
@kingkarki Cool. Glad you fixed it!
