### ISSUE TITLE
Bug: Unchecked required checkbox is still considered as valid

### ISSUE THREAD

**Issue by no-more** [angular/material2#2595]
#### Bug, feature request, or proposal:
I have a required checkbox already checked, when I uncheck it the form is still considered as valid which I think shouldn't (but maybe I'm wrong ?)

#### What is the expected behavior?
Unchecked required checkbox should always be invalid

#### What are the steps to reproduce?
http://plnkr.co/edit/lfZ2a1P5CGeIXV7KS0HI?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.1
Material 2.0.0.beta.1

Thanks.

**Comment by EladBezalel** [comment]
We rely on the [native checkbox functionality](http://plnkr.co/edit/RjJjkCHfGpFcWsr0SGq3?p=preview), this might be a bug of Forms and be better addressed over there.

**Comment by natsid** [comment]
@EladBezalel your plunk shows validation working correctly for checkboxes defined in reactive forms. However, validation does not work quite properly for template-driven checkboxes. See [this plunk](http://plnkr.co/edit/olG3GWEqS95YScibmSiz?p=preview).

The second checkbox (material and template-driven) is properly shown as invalid initially. When it is checked, it is then properly updated to valid. But after that it stops properly updating the validity state.
