### ISSUE TITLE
md-tab-group Promise rejection: Failed to execute 'animate' on 'Element'

### ISSUE THREAD

**Issue by sebsn86** [angular/material2#2597]
#### Bug, feature request, or proposal:
Hi,

the mdTabGroup component seems doesn't like the [selectedIndex] attribute. 
Each time this parameter is defined, I have this error in the Chrome console :

`Promise rejection: Failed to execute 'animate' on 'Element': Partial keyframes are not supported. ; Zone: <root> ; Task: Promise.then ; Value: DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.`

Any idea ?

Best regards,

**Comment by crisbeto** [comment]
What version of Angular are you using?

**Comment by sebsn86** [comment]
I am using the current version, the 2.0.0-beta.1

**Comment by crisbeto** [comment]
I mean which version of the Angular framework, not Angular Material.

**Comment by sebsn86** [comment]
Sorry, 2.4.2

**Comment by crisbeto** [comment]
Thanks. This sounded similar to https://github.com/angular/material2/issues/2151, although that one should be fixed with Angular 2.4.2.

**Comment by sebsn86** [comment]
Yes ! Thanks, it's works perfectly with Angular 2.4.2,

have a nice day !

**Comment by vivian7169** [comment]
I also encountered similar issue when I generate the 2nd tier of dynamic tabs (the 1st tier of tabs are static). 

error: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

Attached sample coding for reference. Thanks.
[test-tab.component.txt](https://github.com/angular/material2/files/701213/test-tab.component.txt)




angular: 2.4.1
material: 2.0.0-beta.1

**Comment by crisbeto** [comment]
Can you try using Angular 2.4.2 @vivian7169?

**Comment by vivian7169** [comment]
Yes, just now upgraded to 2.4.2 and the issue fixed.

Thanks!
