### ISSUE TITLE
Cannot achieve 100% vertical md-slider's track height.

### ISSUE THREAD

**Issue by MarcinMilewski** [angular/material2#2598]
Hi i need to achieve 100% (of container) vertical md-slider's track height, but i can't. There is always some space on the top and on the bottom of the track. I have set md-slider padding to 0 but it doesn't work. How I can achieve this?

#### Bug, feature request, or proposal:
Question

#### What is the expected behavior?
100% container's height of track

#### What is the current behavior?
When "height:100%;" set, there is always some free space on the top and on the bottom.

#### What are the steps to reproduce?
https://plnkr.co/edit/KUePphiHPIOzzQBXoLDV?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Cannot set grid lines correctly in percents.

#### Which versions of Angular, Material, OS, browsers are affected?
angular2-material 2.0.0-beta.1

**Comment by EladBezalel** [comment]
It's working as designed,
There's `8px` "padding" so the thumb would have space. 
you can override it by doing:
```css
.md-slider-vertical .md-slider-track {
  top: 0!important;
  bottom: 0!important;
}
```
in your css

[plunker](https://plnkr.co/edit/ZPufFqqjr8iecCSsUiFE?p=preview)

**Comment by MarcinMilewski** [comment]
Thank You very much.
