### ISSUE TITLE
Remove individual README.md content, point to material.angular.io instead

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#2605]
We should delete the content of each individual README and replace it with a link to the corresponding page on material.angular.io.

Requirements:
* The content should be captured in the overview doc
* Any significant examples in the README should be turned into a live example on the docs site before removing the content.

**Comment by M-a-c** [comment]
@jelbourn I could use some clarification if this task. All docs to already link to material.angular.io unless they are core. If there are docs that need more meat to them I'd be happy to add some material. Suggestions welcome.

**Comment by jelbourn** [comment]
This was done but we forgot to close the issue.
