### ISSUE TITLE
Using md-select in components template breaks banana-binding

### ISSUE THREAD

**Issue by AsherBarak** [angular/material2#2609]
#### Summary
When using `md-select` in the template of a component to be used with `[(ngModule)]` (implementing `ControlValueAccessor`), said component binding does not function (internally, angular does not invoke `ControlValueAccessor `methods)

#### What are the steps to reproduce?

http://plnkr.co/edit/BzgXV2?p=preview
This plunker contains two identical components where the only difference is the inclusion of `md-select` in the template of `with-select` component. This breaks banana binding as described.

#### Is there anything else we should know?
I have nested other banana-bound components into my components with no issue.

See also https://github.com/angular/angular/issues/13886

**Comment by kara** [comment]
@AsherBarak  We forgot to include the `@Self()` selector, so the select is swallowing up your custom value accessor. Should be a quick fix. Looking into doing so now.
