### ISSUE TITLE
md-select initial value not loaded

### ISSUE THREAD

**Issue by csyperski** [angular/material2#2615]
#### Bug, feature request, or proposal:

I am having an issue with Angular2's material md-select component where the value from a FormGroup is not loading or being populated into the select. Here is the code...

https://embed.plnkr.co/p7Fm9lC4TxoVaZ8ydYf0/

The value for the control 'formal' is set to 1, but the UI shows as if no value is populated with the placeholder message.

Am I doing something wrong or is this a bug?

#### What is the expected behavior?

The select should be populated with the correct value

#### What is the current behavior?

It defaults to the no selections or placeholder text

#### What are the steps to reproduce?

https://embed.plnkr.co/p7Fm9lC4TxoVaZ8ydYf0/

#### What is the use-case or motivation for changing an existing behavior?

It is expected user behavior

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.4.1

**Comment by ahmedlafta** [comment]
Number -> String
```
ngOnInit() {
    this.form = new FormBuilder().group({
      'formal': ['1']
      });
  }```

**Comment by csyperski** [comment]
That was stupid of me, Thanks!
