### ISSUE TITLE
Roboto font-weight not working

### ISSUE THREAD

**Issue by Jonatthu** [angular/material2#2617]
#### Bug, feature request, or proposal:
Bug: When I change the font-weight property to 300 is not working correctly or right

#### What is the expected behavior?
Should change the font-weight

#### What is the current behavior?
Is just showing normal and bold

#### Which versions of Angular, Material, OS, browsers are affected?
beta 1

**Comment by jelbourn** [comment]
The Roboto font isn't part of Angular Material (we just set `font-face` to Roboto).

**Comment by Jonatthu** [comment]
Well I'm importing the font family fromgoogle fonts and that does not work nether:/ font-weight is not doing the desire behavior

**Comment by ArtworkAD** [comment]
@Jonatthu you have to explicitly add the font-weight to roboto https://fonts.google.com/specimen/Roboto?selection.family=Roboto:400,500
