### ISSUE TITLE
Dark theme - Disabled checkbox style not showing

### ISSUE THREAD

**Issue by MarkPieszak** [angular/material2#2618]
#### What is the expected behavior?
Show checkbox as disabled when using Dark Theme.

#### What is the current behavior?
The checkbox looks like the regular ones, notice Gamma in the dark theme:

![image](https://cloud.githubusercontent.com/assets/2574412/21907511/da3d51f2-d8dd-11e6-8fa7-12fa3523c100.png)

#### What are the steps to reproduce?
https://material2-app.firebaseapp.com/
Select the Dark theme toggle on the material2 Demo app.

**Comment by volkangurol** [comment]
checkbox disabled has  border-color:  #686868

**Comment by jelbourn** [comment]
@tinayuangao it may be possible that the spec'ed value doesn't capture dark themes well; if that's the case we can follow-up with the Material UX team

**Comment by tinayuangao** [comment]
Tried material2-app and it's very strange that dark theme for `.md-radio-disabled .md-radio-outer-circle` doesn't apply to the radio button. By using the same theme in our demo-app, the disabled radio button looks correct. ![screenshot from 2017-01-26 14 22 00](https://cloud.githubusercontent.com/assets/20677343/22352914/f4c51ffa-e3d2-11e6-9a6d-0228e9bc1052.png)

**Comment by jelbourn** [comment]
I wonder if material2-app is just out of date now.

**Comment by MarkPieszak** [comment]
It may be, sorry I should of put down more info, randomly ran into it when demo'ing Material to a few people and only had time to log it quickly!

Should I close this one out?
