### ISSUE TITLE
Example usage of MdDialog doesn't use md-dialog-content

### ISSUE THREAD

**Issue by alexsapps** [angular/material2#2621]
This page gives an example of how to use MdDialog but it does not surround the dialog contents with <md-dialog-content> ... </md-dialog-content>
https://github.com/angular/material2/tree/master/src/lib/dialog

(I assume it is always required. The description of md-dialog-content is: "Scrollable content of the dialog." does not say that it's only required if scrolling is desired.)

**Comment by antonyRoberts** [comment]
It's not required, and you can implement scrolling without it by using CSS

**Comment by jelbourn** [comment]
@crisbeto can you add an example for this once the examples are moved to the material2 repo in #2781?

**Comment by machtyn** [comment]
For reference:

```
        <p md-dialog-title>{{ title }}</p>
        <md-dialog-content>
          <p>{{ message }}</p>
        </md-dialog-content>
        <md-dialog-actions>
          <button md-raised-button md-dialog-close>{{closeText}}</button>
          <button type="button" md-raised-button *ngIf="enableNext"
              (click)="dialogRef.close(true)">{{nextText}}</button>
        </md-dialog-actions>
```

This snippet demonstrates several things:
1. variables can be utilized to insert text of anything.
2. How md-dialog-title is used (this is documented in the example)
3. How md-dialog-content is used.
4. How <md-dialog-actions> is used.
