### ISSUE TITLE
Internal usages of RxJS operators should not patch the prototype of Observable

### ISSUE THREAD

**Issue by robwormald** [angular/material2#2622]
#### Bug, feature request, or proposal:

All internal usages of Observable / RxJS operators should use the non-patch syntax for imports.

#### What is the expected behavior?

Usages of RxJS operators should use the "longhand" syntax, which avoids polluting the Observable.prototype in userland:

```ts
//desired syntax
import {Observable} from 'rxjs/Observable'
import {map} from 'rxjs/operator/map'

map.call(sourceObservable, (x) => x + 1).subscribe(...)
```

#### What is the current behavior?

```ts
//current syntax
import {Observable} from 'rxjs/Observable'
import 'rxjs/add/operator/map'

sourceObservable.map((x) => x + 1).subscribe(...)
```

#### What is the use-case or motivation for changing an existing behavior?

Currently the "patch" operators are used, which pollute the Observable prototype and can lead to unexpected results if, for example, Material uses the .map() operator today, and then removes it in the future. If a user uses `.map()` without explicitly importing it, their app would break upon removal by Material.

#### Is there anything else we should know?
 
Sample of correct usage in Router : https://github.com/angular/angular/blob/52be848f94a70feffd44a1d688286f750d0471d9/modules/%40angular/router/src/router_config_loader.ts#L34

**Comment by crisbeto** [comment]
@robwormald how do you recommend handling the longer chains of calls? I ended up adding a function for chaining them, but the syntax ends up being kind of awkward:

```ts
chainCalls(this._loadSvgIconFromConfig(config),
  [observableDo, (svg: SVGElement) => config.svgElement = svg],
  [map, (svg: SVGElement) => cloneSvg(svg)]);
```

My chaining function ended up looking like this:

```ts
function chainCalls(initialThis: any, ...functions: any[][]) {
  return functions.reduce((previousValue, currentValue) => {
    return (currentValue.shift() as Function).apply(previousValue, currentValue);
  }, initialThis);
}
```

CC @jelbourn

**Comment by mgechev** [comment]
Here's a tslint [rule](https://palantir.github.io/tslint/rules/no-import-side-effect/) I implemented some time back based on a discussion we had with @hansl, which may work.
