### ISSUE TITLE
Ripple speed too fast, and a bit too faded

### ISSUE THREAD

**Issue by mxchange** [angular/material2#2626]
#### Bug, feature request, or proposal:
The ripple speed on buttons (and all other ripple elements) is so fast it's barely noticeable, expecially on smaller and/or colored elements.
If I compare it to an android ripple effect, which seems about twice as slow.
![material-ripple](https://cloud.githubusercontent.com/assets/24876534/21926142/c7b0b936-d980-11e6-98da-fed50778bc4c.gif)

#### What is the expected behavior?
The ripple effect to be slow enough to be noticeable, like on the latest Android versions.
And for the ripple color to be a bit more opaque, so it shows better on colored elements.

#### What is the current behavior?
The effect is only really noticeable on larger buttons.
And is not very noticeable on FABs, perhaps also more due to the ripple color being a bit too faded.

#### What are the steps to reproduce?
Run the `demo-app`

#### What is the use-case or motivation for changing an existing behavior?
I think it is not close enough to the material design specs/guidelines. Probably a 100ms would make a big difference already, or maybe 60/70ms, which in my experience tends to be high enough to notice.
Maybe it is a rendering issue with browsers (at the start of drawing), and with slower devices will seem too slow, while on fast devices it will look too fast, like in my case.

#### Which versions of Angular, Material, OS, browsers are affected?
Latest Chrome and Firefox

#### Is there anything else we should know?
I love you

**Comment by jelbourn** [comment]
@EladBezalel the ripples should match MDC Web: https://material-components-web.appspot.com/button.html, which is the definitive correct ripple. 

Want to take a look at this?

**Comment by DevVersion** [comment]
@mxchange This issue has been fixed as part of PR https://github.com/angular/material2/pull/2859. Thanks again for the issue.
