### ISSUE TITLE
md-focused is not added on focus in electron

### ISSUE THREAD

**Issue by riksof-zain** [angular/material2#2629]
#### Bug, feature request, or proposal:

md-focused is not added on focus on in electron

#### What is the expected behavior?

when input is focused it should add md-focused

#### What is the current behavior?

it is woking on browser but not on electron

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
