### ISSUE TITLE
Material doesn't run in Dialog

### ISSUE THREAD

**Issue by Jhonatangiraldo** [angular/material2#2632]
#### Bug, feature request, or proposal:
When i use directives of angular material, the app doesn't recognize the elements and/or directives

#### What is the expected behavior?
Directives run normal, with angular material styles

#### What is the current behavior?
The application doesnt recognize angular material elements.
https://cloud.githubusercontent.com/assets/6934447/21935981/8dbba2fc-d97d-11e6-9f5e-8259c8d208d4.png

#### What are the steps to reproduce?
Use a dialog of anglular material and put in it, an element of angular material like 
<md-select placeholder="¿Select the option?">
        <md-option [value]="a">
            Opcion1
        </md-option>
    </md-select>

#### What is the use-case or motivation for changing an existing behavior?
To run my application

**Comment by codef0rmer** [comment]
@Jhonatangiraldo You should either import `MdSelectModule` or `MaterialRootModule` and reference it under @NgModule.

**Comment by jelbourn** [comment]
@Jhonatangiraldo sounds like the NgModule in which your component is declared does not import the appropriate material modules.
