### ISSUE TITLE
routerlinkactive="activeStyle" is not loading the tab using tab-nav-bar and md-tab-link

### ISSUE THREAD

**Issue by vkishorekumar80** [angular/material2#2633]
When navigating to a route (tab3) from browser, the default implementation of the navbar using <a> and rountLinkActive is loading the content properly and selecting the specified navigation link.

But When I try to do the same flow using md-tab-nav-bar and md-tab-link, the content is loaded properly but the navigation link not getting selected.

[ng2material-navbarlink.zip](https://github.com/angular/material2/files/704747/ng2material-navbarlink.zip)

**Comment by chouclee** [comment]
Check how to use md-tab-nav-bar in the [overview](https://github.com/angular/material2/blob/master/src/lib/tabs/OVERVIEW.md)

And be sure to read this issue https://github.com/angular/material2/issues/1967.

**Comment by vkishorekumar80** [comment]
Hi @chouclee 

Instead of looking into the overview document, directly went in to the tabs-demo.html page where I  routerLinkActive #rla="routerLinkActive" was not mentioned in the sample. Apology from my side for note reading the overview.

After reading the  issue #1967 got the workaround and now working as expected.

` <a md-tab-link
       *ngFor="let tabLink of navItems; let i = index"
        [routerLink]="tabLink.link"
        routerLinkActive #rla="routerLinkActive"
        [active]="rlaSafe && rla.isActive">
      {{tabLink.label}}
    </a>`

`private rlaSafe: boolean = false;

  constructor(private changeDetectorRef: ChangeDetectorRef)
  {

  }
  public ngAfterViewInit() {
    this.rlaSafe = true;
    this.changeDetectorRef.detectChanges();
  }`
