### ISSUE TITLE
md-prefix and md-suffix selectors should be camel-cased

### ISSUE THREAD

**Issue by PascalPrecht** [angular/material2#2636]
#### Bug, feature request, or proposal:
This is a leftover from moving from dash-cased to camel-cased directive names.

Currently it looks like this:
```html
<md-input-container align="end">
  <input mdInput placeholder="amount">
  <span md-prefix>$&nbsp;</span>
  <span md-suffix>.00</span>
</md-input-container>
```

But it should be this:
```html
<md-input-container align="end">
  <input mdInput placeholder="amount">
  <span mdPrefix>$&nbsp;</span>
  <span mdSuffix>.00</span>
</md-input-container>
```

**Comment by jelbourn** [comment]
We will need to support both selectors temporarily and then remove the dash-case versions in a subsequent release.
