### ISSUE TITLE
buttons do not have expected color and text-transform

### ISSUE THREAD

**Issue by jrood** [angular/material2#2637]
#### Bug, feature request, or proposal:
Buttons do not have the coloring or capitalizing text-transform.

#### What is the expected behavior?
That `<button md-button>` would display the same way that it does in the documentation.

#### What is the current behavior?
It's not gray, and it's not all capps

#### What are the steps to reproduce?

Go to https://material.angular.io/components/component/button and click the button to edit in plunker. The example in plunker looks different than the one in the documentation.

#### What is the use-case or motivation for changing an existing behavior?
When developers use the examples provided in the docs, they should be able to expect that the results would look the same as how they look in the docs.

**Comment by codef0rmer** [comment]
@jrood I think caps can not be the default behavior but definitely the plunkr should be updated for consistency.

**Comment by jelbourn** [comment]
Button color is set via the `color` property. 

We specifically do not use `text-transform` as it may have internationalization issues (changing the case may change the meaning of the text in some locales). If you always want to to capitalize the button text, you can add a global rule specific to your application.

**Comment by erikschull** [comment]
Just wondering if anybody knows any specific examples of languages where this causes a problem; the product I'm working on only supports a couple dozen languages, and being able to simply use the text-transform: uppercase solution would simplify things a great deal.

**Comment by jelbourn** [comment]
@erikschull You can easily add the style to your own application, e.g.
```css
[md-button] {
  text-transform: uppercase;
}
```

**Comment by jrood** [comment]
@erikschull I think "capitonyms" is what you would search for to find specific examples.
