### ISSUE TITLE
md-progress-circle customize svg

### ISSUE THREAD

**Issue by bsteffl** [angular/material2#264]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
Current progress circle doesn't allow you to customize the SVG.

**What is the expected behavior?**
Add the ability to inject your own SVG for progress circle.

**What is the motivation / use case for changing the behavior?**
Flexibility to have a different SVG and capability to override animations to customize to fit your own theme.

**Comment by jelbourn** [comment]
@bsteffl If you want to use a different SVG with a different animation, then I think you just want your own custom component; there's very little the progress circle does beside those two things.
