### ISSUE TITLE
md-slider & md-slide-toggle don't work correctly

### ISSUE THREAD

**Issue by nkas** [angular/material2#2651]
I try to make Angular based app according to this tutorial: https://material.angular.io/guide/getting-started

The issue is that there is no sliding functionality on Slider and SlideToggle components, the value changes only on click. All dependencies are installed as it is mentioned in Getting started tutorial.
I'm using Chrome 55, HammerJs version 2.0.34, Angular 2.4.3, Material 2.0.0-beta.1

**Comment by codef0rmer** [comment]
@nkas Make sure to `import 'hammerjs';` in `app.module.ts`. Also, confirm if you see following error in the console, `Could not find HammerJS. Certain Angular Material components may not work correctly.`

**Comment by mojtab23** [comment]
I have similar problem too.
I created an angular project with angular cli and then followed this guide:[https://material.angular.io/guide/getting-started](https://material.angular.io/guide/getting-startedl)
and some of material controls in addition to Slider not works, such as [https://material.angular.io/components/component/progress-bar](progress bar)

**Comment by DevVersion** [comment]
@mojtab23 Can you take a look if there is a log message in the console?
>  (`Could not find HammerJS. Certain Angular Material components may not work correctly.`)

**Comment by codef0rmer** [comment]
@mojtab23 I noticed an issue with css - no component was rendered. So added the missing stylesheet:

`<link href="https://unpkg.com/@angular/material/core/theming/prebuilt/indigo-pink.css" rel="stylesheet">`

**Comment by nkas** [comment]
@codef0rmer Yes, I imported hammerjs into app.module.ts. Also there are no errors in the console.

**Comment by codef0rmer** [comment]
@nkas I see. Now only a working demo would save you :-) Share a screenshot if possible.

**Comment by mojtab23** [comment]
Thank you @DevVersion and @codef0rmer !
@codef0rmer answer fixed my problem.
There is two more things:

1. This guide [https://material.angular.io/guide/getting-started](https://material.angular.io/guide/getting-started) is not working correctly.
2.  And I have one question: How can I set the Material 2 theme to dark-theme? I asked this [question](http://stackoverflow.com/q/41684093/3291867) at  StackOverflow .

**Comment by DevVersion** [comment]
@mojtab23 Glad it works now.

Regarding 1) We are aware of that - and it will be fixed as soon as possible
Regarding 2) The response from @codef0rmer is correct. Either you need to use SCSS or a prebuilt theme.
