### ISSUE TITLE
ChangeDetectionStrategy.OnPush problem

### ISSUE THREAD

**Issue by IliaIdakiev** [angular/material2#2663]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When using ChangeDetectionStrategy.OnPush the md-select value is cleared when ngModel variable is set to null

#### What is the current behavior?
ngModel is null but md-select value persists

#### What are the steps to reproduce?
https://plnkr.co/edit/RGEWSXblOySdltKBku9o?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Application Performance Optimization

#### Which versions of Angular, Material, OS, browsers are affected?
Angular v2.4.3
Angular Material v2.0.0-beta.1

#### Is there anything else we should know?
Maybe there are other controls not working with ChangeDetectionStrategy.OnPush

**Comment by farin99** [comment]
I still see this bug in beta.2 when using reactive forms.

**Comment by mjolk** [comment]
I'm seeing the same, beta.2/angular 4.0.0 reactive forms with ChangeDetectionStrategy.OnPush still exhibits this behaviour. Is there a temporary quickfix?
