### ISSUE TITLE
Plunker Template on README does not work on Safari

### ISSUE THREAD

**Issue by jeongjoonlee3** [angular/material2#2666]
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
It should render html template.

#### What is the current behavior?
It shows "Loading the Angular 2 Material App..." message.

#### What are the steps to reproduce?
Click Plunker Template link on README page with Safari

#### Which versions of Angular, Material, OS, browsers are affected?
Safari: 10.0.2

**Comment by jelbourn** [comment]
@EladBezalel do you have a Mac to try this?

**Comment by EladBezalel** [comment]
@jelbourn sorry, i have a real machine 😅

**Comment by chickson-va** [comment]
I looked into this and found that if I changed the Angular specific mappings in `systemjs.config.js` to map to `https` vs `http` then it worked fine.

It looks like the Safari issue came up because of a cross origin request issue.

**Comment by DevVersion** [comment]
@chickson-va Thanks for the investigations. Unfortunately it's not possible to propose any changes to a Plunker.

I've made the changes on the Plunker template. Can you re-test that everything works?

**Comment by chickson-va** [comment]
Took a look at the new link and things are loading for me in Safari 👍

**Comment by DevVersion** [comment]
@chickson-va Cool. Thanks for checking.
