### ISSUE TITLE
When I have to open md-select and press 'A' key then move focus should be on 'A' string like 'Apple' 

### ISSUE THREAD

**Issue by smartHasmukh** [angular/material2#2668]
Please have a demo - [md-select example](http://plnkr.co/edit/JIEFHNvWK6LVwEsYLVD8?p=preview)

![focus](https://cloud.githubusercontent.com/assets/8941195/21981198/4348f7d8-dc0c-11e6-8c59-d662d57c9611.png)

Right now focus on 'Mango'. After press key 'A' I wanted to know second screenshot

![plunker](https://cloud.githubusercontent.com/assets/8941195/21981215/573f2938-dc0c-11e6-87d6-431699b3ee4f.png)

**Comment by smartHasmukh** [comment]
I wanted to know same as with angular2 - [AngularJS Demo](http://codepen.io/beaver71/pen/LGxqjp)

**Comment by naveedahmed1** [comment]
@crisbeto should we expect it to be available in next release?

**Comment by naveedahmed1** [comment]
Please also add support of Home and End key as its in native select list. Home key sets focus on first element and End key sets focus on last element,

**Comment by dimuthulakshan** [comment]
I got latest version but still key focusing is not working in my application.  Could you please let me know how I can use this feature in material library.

**Comment by donroyco** [comment]
@dimuthulakshan What do you mean by 'latest version'?

**Comment by dimuthulakshan** [comment]
I deleted existing material installation in my node_modules and  re-installed it again using npm. Kindly provide me  instructions to get this change to  my application.
