### ISSUE TITLE
md-input heights are not consistent between types of inputs

### ISSUE THREAD

**Issue by itayper** [angular/material2#2676]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
Currently inputs are not aligned correctly with each other: http://plnkr.co/edit/RHrE8rJe1SdJclYBKKh8?p=preview
I mean that date and text aren't same height and so does md-select

#### What is the use-case or motivation for changing an existing behavior?
It just doesn't look right when you try and make a form with inputs next to each other

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.2.0
Material: 2.0.0-beta.1
OS: Windows 10
Browsers: Chrome Version 55.0.2883.87 m (64-bit)

**Comment by EladBezalel** [comment]
Would be resolved with #2309
