### ISSUE TITLE
MdCheckBox - error when [(ngModel)] on md-checkbox inside ngFor

### ISSUE THREAD

**Issue by nadavten** [angular/material2#2679]
```
<tr *ngFor="let alarm of alarms">
  <md-checkbox [(ngModel)]="alarm.isActive"></md-checkbox>
</tr>
```

throws an error in the console:

> "Uncaught (in promise): TypeError: Cannot set property 'stack' of undefined
> TypeError: Cannot set property 'stack' of undefined
>     at SyntaxError.set [as stack] (eval at <anonymous> (file:///C:/projects/school/dist/vendor.js:17:2), <anonymous>:1628:63)
>     at assignAll (eval at <anonymous> (file:///C:/projects/school/dist/polyfills.js:1744:2), <anonymous>:704:29)
>     at SyntaxError.ZoneAwareError (eval at <anonymous> (file:///C:/projects/school/dist/polyfills.js:1744:2), <anonymous>:775:16)
>     at SyntaxError.BaseError [as constructor] (eval at <anonymous> (file:///C:/projects/school/dist/vendor.js:17:2), <anonymous>:1590:18)
>     at new SyntaxError (eval at <anonymous> (file:///C:/projects/school/dist/vendor.js:17:2), <anonymous>:1793:18)
>     at TemplateParser.parse (eval at <anonymous> (file:///C:/projects/school/dist/vendor.js:17:2), <anonymous>:11210:21)
>     at JitCompiler._compileTemplate (eval at <anonymous> (file:///C:/projects/school/dist/vendor.js:17:2), <anonymous>:27480:70)
>     at eval (eval at <anonymous> (file:///C:/projects/school/dist/vendor.js:17:2), <anonymous>:27363:64)
>     at Set.forEach (native)
>     at JitCompiler._compileComponents (eval at <anonymous> (file:///C:/projects/school/dist/vendor.js:17:2), <anonymous>:27363:21)
>     at createResult (eval at <anonymous> (file:///C:/projects/school/dist/vendor.js:17:2), <anonymous>:27246:21)
>     at ZoneDelegate.invoke (eval at <anonymous> (file:///C:/projects/school/dist/polyfills.js:1744:2), <anonymous>:242:26)
>     at Zone.run (eval at <anonymous> (file:///C:/projects/school/dist/polyfills.js:1744:2), <anonymous>:113:43)
>     at eval (eval at <anonymous> (file:///C:/projects/school/dist/polyfills.js:1744:2), <anonymous>:535:57)
>     at ZoneDelegate.invokeTask (eval at <anonymous> (file:///C:/projects/school/dist/polyfills.js:1744:2), <anonymous>:275:35)
>     at Zone.runTask (eval at <anonymous> (file:///C:/projects/school/dist/polyfills.js:1744:2), <anonymous>:151:47)
>     at drainMicroTaskQueue (eval at <anonymous> (file:///C:/projects/school/dist/polyfills.js:1744:2), <anonymous>:433:35)"

**Comment by jmcgoldrick** [comment]
Looks like an error with `zone.js@0.7.5` (see: https://github.com/angular/angular/search?q=zone.js+0.7.5&type=Issues)

`npm install zone.js@0.7.4` resolved similar issue for me

**Comment by nadavten** [comment]
then it would throw the following error

> (program):405 Unhandled Promise rejection: Template parse errors:
> Can't bind to 'ngModel' since it isn't a known property of 'md-checkbox'.
> 1. If 'md-checkbox' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
> 2. If 'md-checkbox' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

**Comment by DevVersion** [comment]
Seems to work for me: http://plnkr.co/edit/AcJc12SViI5VGKMyLgVj?p=preview

**Comment by nadavten** [comment]
my mistake. forgot FormsModule ..
