### ISSUE TITLE
tabs - unable to trigger click hander within md-tab-label

### ISSUE THREAD

**Issue by dmacfarlane** [angular/material2#2681]
#### Bug, feature request, or proposal:

Bug or feature request

#### What is the expected behavior?

Clicks on elements within md-tab-label should trigger the associated event handlers.

#### What is the current behavior?

Click events are not triggered.

#### What are the steps to reproduce?

http://plnkr.co/edit/5bY29Nm9pUNu4pu4wRwV?p=preview

Clicking the close icon on the tab labels should close the tabs.

#### What is the use-case or motivation for changing an existing behavior?

To provide a familiar/easy/standard way to close tabs.

#### Which versions of Angular, Material, OS, browsers are affected?

This was working in alpha.10 and is not working since alpha.11.

#### Is there anything else we should know?

In the Plunker, see systemjs.config.js:

  //CLOSE ICON WORKS:
  //var materialVer = '@2.0.0-alpha.10'; // ng-Material version
  //CLOSE ICON DOES NOT WORK:
  var materialVer = '@2.0.0-alpha.11'; // ng-Material version

This issue may be related to focus-trapping?

**Comment by colinfang** [comment]
`md-tooltip` doesn't work either if applied on elements within `md-tab-label`

**Comment by klesky** [comment]
Currently facing the same issue of not being to apply tooltip for tab labels

**Comment by eliteproxy7** [comment]
same here, that jump, looks like it changes the width of md-tab-label and and changes it back to what it should be

**Comment by firdausng** [comment]
any update on this issue?

**Comment by andrewseguin** [comment]
This doesn't seem to be a problem in the current version of material. 

https://plnkr.co/edit/AYsLjvcmDwTUipfEWRe1?p=preview
