### ISSUE TITLE
broken link on getting started guide

### ISSUE THREAD

**Issue by goleary** [angular/material2#2682]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
https://material.angular.io/guide/getting-started
when I click the 'theming guide' link it should take me to the mentioned guide.

#### What is the current behavior?
it takes me back to the home page

#### What are the steps to reproduce?
should be obvious

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by M-a-c** [comment]
@jelbourn Issue seems to be working.
But visiting any other link that goes external does not work. Should I open an issue?

Material Sample App on the getting started page, and anything else that isn't a internally hosted link breaks.

**Comment by goleary** [comment]
no longer an issue
