### ISSUE TITLE
newly created angular-cli app getting error in console

### ISSUE THREAD

**Issue by goleary** [angular/material2#2683]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
I have added a `<button md-button></button>` component but I get an error in the console. Its the only thing in the entire application

#### What is the current behavior?

When I use angular-cli to serve the application I see this error: 
![image](https://cloud.githubusercontent.com/assets/16123225/22009021/0a9825c0-dc35-11e6-8eb1-f3dc9cdea0a5.png)

#### What are the steps to reproduce?

Bug can be seen by serving the application in this repo: https://github.com/goleary/strava-extended-stats

**Comment by irfanhudda** [comment]
This is probably an issue with `zone.js`. There was an extensive discussion about this issue [https://github.com/angular/zone.js/issues/427](https://github.com/angular/zone.js/issues/427).

One suggestion from above thread is pinning `zone.js` at `0.7.2`.

**Comment by goleary** [comment]
pinning solved my problem.  Thanks!
