### ISSUE TITLE
Incorrect installation instructions

### ISSUE THREAD

**Issue by casperbrike** [angular/material2#2684]
https://material.angular.io/guide/getting-started 

In section **Configuring SystemJS**:
```
System.config({
  // existing configuration options
  map: {
    ...,
    '@angular/material': 'npm:@angular/material/material.umd.js'
  }
});
```

But should be:
```
System.config({
  // existing configuration options
  map: {
    ...,
    '@angular/material': 'npm:@angular/material/bundles/material.umd.js'
  }
});
```  
Also after following instructions for HammerJS configuration i got some errors in browser console:
`"(SystemJS) XHR error (404 Not Found) loading http://localhost:3001/hammerjs	patchProperty/desc.set/wrapFn@http://localhost:3001/node_modules/zone.js/dist/zone.js:962:26 [<root>]	Zone.prototype.runTask@http://localhost:3001/node_modules/zone.js/dist/zone.js:151:28 [<root> => <root>]	ZoneTask/this.invoke@http://localhost:3001/node_modules/zone.js/dist/zone.js:345:28 [<root>]		Error loading http://localhost:3001/hammerjs as "hammerjs" from http://localhost:3001/dist/app.module.js"`  
 
Fixed this by adding this line in `systemjs.config.js` map section:
```
 'hammerjs': 'npm:hammerjs/hammer.js'
```

My environment:
OS: Ubuntu 16.04
Node version: v6.9.2
Npm version: 3.10.9
Application dependencies
```
"dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/material": "^2.0.0-beta.1",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0",
    "@types/hammerjs": "^2.0.34",
    "angular-in-memory-web-api": "~0.2.4",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "zone.js": "^0.7.4"
  }
```

**Comment by DevVersion** [comment]
The path for the umd bundle has been solved with SHA https://github.com/angular/material2/commit/d286e6d6472910ab41b8437d405cd3e902c9c848
