### ISSUE TITLE
[Updated] Md-Tabs - Navigate Options & Count Tabs

### ISSUE THREAD

**Issue by Ganim** [angular/material2#2685]
**Bug, feature request, or proposal:**

Feature request

**What is the expected behavior?**

#1 - I would like to change tabs by buttons, 
#2 - count how many tabs I have.

**What is the current behavior?**

`tabsNumber  = document.getElementsByTagName('md-tab').length;` 
Doesn´t work to count tabs. If i don´t know how tabs I have, a can´t limite the "Next" Button

**What is the use-case or motivation for changing an existing behavior?**

Thats a way to navigate better the tabs, and a way to do a multi step form.

**Which versions of Angular, Material, OS, browsers are affected?**

@angular/material: 2.0.0-beta.1

**Comment by Ganim** [comment]
[Updated] - Use the template question form, sorry by changed this before.

**Comment by andrewseguin** [comment]
Here's an example of (1) changing the tabs using buttons and (2) counting how many tabs there are using a ViewChildren query.

http://plnkr.co/edit/cyb5sRINXprP0pwXsCmB?p=preview

Please feel free to open the issue if you find a bug or missing feature
