### ISSUE TITLE
Add info about entryComponents in Dialog documentation

### ISSUE THREAD

**Issue by coder925** [angular/material2#2686]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
It should be easy to follow the [dialog overview sample](https://material.angular.io/components/component/dialog) and get it up and running using a new app created with Angular CLI.

#### What is the current behavior?
I was struggling with getting the Dialog component to work without showing errors in the console. I finally solved it by adding my DialogContentComponent to the module’s _entryComponents_. It would be helpful if there was a section in the documentation if this is a requirement.

#### What are the steps to reproduce?
The steps to reproduce the errors in the console is available from:
https://github.com/coder925/sample-angular-material-dialog-overview#sample-angular-material-dialog-overview

#### What is the use-case or motivation for changing an existing behavior?
It would improve the documentation if this is a requirement and help other people who might struggle with the same issue.

#### Which versions of Angular, Material, OS, browsers are affected?
https://github.com/coder925/sample-angular-material-dialog-overview#versions

#### Is there anything else we should know?
I can submit a PR for improved documentation. However, I am afraid my knowledge regarding why you must place the _content dialog component_ in _entryComponents_ is not sufficient to be able to describe the reasons for this requirement correctly.
The Plunkr sample of the Dialog Overview places the *content dialog component* in the module’s bootstrap instead. I was not able to get this to work.

**Comment by coder925** [comment]
I see that the requirement of _entryComponents_ is mentioned in the [README of the Dialog](https://github.com/angular/material2/tree/master/src/lib/dialog#example). So my proposal is merely to also include this information on https://material.angular.io/components/component/dialog . Thanks!

**Comment by jelbourn** [comment]
Yep, looks like that information was accidentally lost in the transition from readme to overview.

**Comment by rosslavery** [comment]
What also should be made clear is whether it should be added to:

- `entryComponents` of the module the component belongs to
- `entryComponents` of the module that contains the actual call to `dialog.open()` - as this could be a different module than the above-mentioned module
- Both of the above

I'm actually still not clear myself on which it is to be honest.
