### ISSUE TITLE
Documentation Website is difficult to read

### ISSUE THREAD

**Issue by diminutivesloop** [angular/material2#2689]
It's exciting to see the full website for Angular Material 2 finally take shape. Unfortunately the new design has a very low text contrast ratio that makes the site content noticeably hard to read. Obviously there are stylistic considerations at play here, but since this site is primarily a working resource for developers it seems that readability should be given increased priority.

**Comment by istiti** [comment]
Second it!

**Comment by jelbourn** [comment]
@diminutivesloop can you describe the specific parts of the site where this is an issue?

**Comment by diminutivesloop** [comment]
I think it's most noticeable on the component documentation and guide pages. It also seems to be dependent on display quality as the pages appeared more readable on my personal MacBook (non-retina) than on my work PC. Also I haven't noticed the same readability issues on the main Angular website.

**Comment by davidglezz** [comment]
In https://material.angular.io/components/component/snack-bar I see:
![captura](https://cloud.githubusercontent.com/assets/194784/22436405/28881140-e724-11e6-89c2-0362ae59f95a.PNG)
The text color is Black 54%
Material design guidelines recommends Black 87%
https://material.io/guidelines/style/typography.html#typography-other-typographic-guidelines

**Comment by EladBezalel** [comment]
Will be fixed with https://github.com/angular/material.angular.io/pull/91

**Comment by davidglezz** [comment]
Text still at .54

**Comment by slimlime** [comment]
I'm glad I'm not the only one who is bothered by this.
