### ISSUE TITLE
[BUG] mdInput type="time" - placeholder running over input when time not fully entered

### ISSUE THREAD

**Issue by nadavten** [angular/material2#2700]
BUG - 
![image](https://cloud.githubusercontent.com/assets/17804204/22038993/10e50e6c-dd06-11e6-8a71-f6f021f5662f.png)

**Comment by DevVersion** [comment]
Works for me in `master`. Are you using the `mdInput` directive or the deprecated `<md-input>` element?

![](https://i.gyazo.com/f19c14827ad18eecf5844381f3610096.png)

**Comment by nadavten** [comment]
md-input. how do u use mdInput ?

**Comment by DevVersion** [comment]
Well, `<md-input>` has been deprecated in favor of the `<input md-input>` attribute.

But we also have made some changes to that recently: 
- In Beta.1 it can be used `<input md-input>`
- In the future releases it will be `<input mdInput>`

Here is some info about `master`: https://github.com/angular/material2/tree/master/src/lib/input

**Comment by nadavten** [comment]
`<input md-input placeholder="Name" [value]="someValue" type="text"/>`

![image](https://cloud.githubusercontent.com/assets/17804204/22079205/aad92c5c-ddc3-11e6-9afe-d59c60b14fe1.png)

**Comment by DevVersion** [comment]
What Angular Material version are you using? - Next time please use the issue template..

**Comment by nadavten** [comment]
beta-1

**Comment by DevVersion** [comment]
Be sure to have a `<md-input-container>` element around it. As in the documentation: https://material.angular.io/components/component/input

**Comment by nadavten** [comment]
![image](https://cloud.githubusercontent.com/assets/17804204/22118855/066b900a-de82-11e6-9c56-196d5cf98f68.png)

```
<tr *ngFor="let alarm of alarms">
            <td>
                <md-input-container>
                    <input md-input placeholder="Name" [value]="alarm.name"/>
                </md-input-container>
            </td>
```

**Comment by arciisine** [comment]
This is a bug that has been fixed in master, but not yet released.  As far as I know, beta.2 should provide support for `[value]="alarm.name"`. Right now when you set value directly, the mdInput directive doesn't register the change (and the placeholder stays in place).
