### ISSUE TITLE
md-button-toggle-group, CSS for button states

### ISSUE THREAD

**Issue by JordanSliz** [angular/material2#2709]
I haven't seen anyone talking much about this, so I'm adding it as a new issue.

What I'd like to achieve is to style the button states of the md-button-toggle-group.  :hover works with no issue.  However, :active only works on mouse down, and none of the other pseudoclasses, :checked, :enabled, ::selection, :valid, nor :focus, have any effect of any kind of them.  (Obviously some of those were desperate.)

It's my assumption that somewhere, there is a primary color/similar being assigned to it in the scripting.  Alas, as a designer first and programmer second, this is all a little above my head as yet.  Hopefully someone can help me out.

Plunker here:
https://plnkr.co/edit/FwMb2w7wrWWzD256mOkI?p=preview

**Comment by JordanSliz** [comment]
Answered my own question in time.  It's injecting classes on multiple element levels that lay-over one another.  .md-button-toggle-checked and .md-button-toggle-label-content both are injected on click.

**Comment by JordanSliz** [comment]
The real trouble is that the TS injecting classes on actions makes it nigh impossible to tell if the page-level styles will or will not overwrite what you have written.

**Comment by JordanSliz** [comment]
So, having done my own theming for Ang2 now, I can't seem to access md-button-toggle or md-button-toggle-group.

Can anyone explain how to affect these items?

**Comment by rdelriods01** [comment]
if you want to change the default gray color from the md-button, you only need to add this line in the main styles.css file 
`.md-button-toggle-checked .md-button-toggle-label-content{
    background-color:#8BC34A !important;
}`

**Comment by abansal77** [comment]
Does it work? I want to change padding for md-button-toggle-label-content from "0 16px" to "0 10px".

Should i change in library files? is there a way I can override?

**Comment by jelbourn** [comment]
Closing this since I think it's gone off-topic. Feel free to open a new issue that uses the issue template to clarify what you're reporting / proposing.
