### ISSUE TITLE
svg source for md-icon not working

### ISSUE THREAD

**Issue by sarora2073** [angular/material2#2712]
#### Bug, feature request, or proposal:
Bug with md-icon in 2.0.0-beta.0 / 2.0.0-beta.1

#### What is the expected behavior?
ability to specify/load an .svg source file (locally or external) on an md-icon component

#### What is the current behavior?
get this error when trying to specify a local .svg file source for an md-icon
Can't bind to 'md-svg-src' since it isn't a known property of 'md-icon'

I'm using syntax shown in the latest docs like this:

<md-icon md-svg-src="{{mySvgImage}}"></md-icon>

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-beta.0 / 2.0.0-beta.1 are broken using old (svgSrc="") or new syntax (md-svg-src="")
2.0.0-alpha.11-3 - works using the svgSrc="" syntax:
<md-icon svgSrc="{{mySvgImage}}"></md-icon>

**Comment by xban1x** [comment]
[Material MdIcon](https://material.angular.io/components/component/icon).

Please review the example.The new property is  `svgIcon` and icon must be cleared by DomSanitizer.

**Comment by sarora2073** [comment]
Tried that and it doesn't work. I guess i mistakenly thought mg-svg-src was the new property because i was looking at this page which is actually for materialjs: https://material.angularjs.org/latest/api/directive/mdIcon

You'll notice on that old materialjs site that there are 2 properties. I'm looking for the latest equivalent of md-svg-icon for materio.io, and it appears you have given the latest equivalent md-svg-icon.  To be sure, I tried you're suggestion and confirmed it doesn't work. It appears to me that the svgSrc property that was working recently got broken in the 2.0.x beta versions.

-- excerpt from materialjs site copied below --
* md-svg-src	string	
String URL (or expression) used to load, cache, and display an external SVG.
* md-svg-icon	string	
md-svg-icon String name used for lookup of the icon from the internal cache; i

**Comment by sarora2073** [comment]
On further review of the source code, it appears svgSrc was (and is?) the correct property but was modified by this commit:
https://github.com/angular/material2/commit/4571561dd51b350bbe58e3af6c17ef0e53cd3dd7

The code suggests some intention to support a 'SafeResourceUrl'..however, i'm unclear as to how I can configure the component to trust a local file path. Also, the error i get when using svgSrc (Can't bind to 'svgSrc' since it isn't a known property of 'md-icon') suggests other implementation issues aside from my usage. Any ideas?

**Comment by mtrdp642** [comment]
[Plunker example](http://plnkr.co/edit/eWi18QNOrzhrvVUbK1rH?p=preview) with working DomSanitizer to trust local file paths. Example in app.component.ts

**Comment by jelbourn** [comment]
Working as intended. `svgSrc` was removed in beta.0. See the example at https://material.angular.io/components/component/icon

**Comment by s3ppo** [comment]
@jelbourn when i use svgIcon with domsanitizer within a md-nav-list, the size of the icon scales with the windowsize, is this normal?
