### ISSUE TITLE
md-tab-group/md-tab default width

### ISSUE THREAD

**Issue by D-Aymen** [angular/material2#2715]
#### **_`if (Σ (md-tab widths) < 100vw), and  (N =  Σ (md-tabs)): md-tab width = 100vw/N`_**

`Exemple: If we have 4 md-tabs, default md-tab width will be 1/4 of the container (vw or container)`

`Notes: in this case i take page width as reference, the proposal concern also any container's width.`

**Comment by andrewseguin** [comment]
In the future please use the issue template. It helps us understand the issue in terms of actual/expected behavior. In addition, having a plunker example that displays your issue really helps. Feel free to reopen with the issue template.
