### ISSUE TITLE
IE11 MdTooltip issue

### ISSUE THREAD

**Issue by CPANinjaDoug** [angular/material2#2717]
#### Bug, feature request, or proposal:
If I add mdTooltip="This is a Test" to an HTML element everything works fine in Chrome or Firefox, but it doesn't work in IE11. I have imported MaterialModule into the main app.module.ts file and included 
`<link` rel="stylesheet" `href="//rawgit.com/angular/material2-builds/master/core/theming/prebuilt/indigo-pink.css">` in the index.html file.

#### What is the expected behavior?
Tool tip to work in IE11 the same way it does in Chrome and Firefox.

#### What is the current behavior?
Usually nothing happens. Sometimes clicking on the HTML element will display the tool tip momentarily, but it disappears within a second.

#### What are the steps to reproduce?
Add <button mdTooltip="This is a test">Click Me</button> to an Angular 2 project and then hover over the button in IE11.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
Plunker template itself isn't working in IE11

#### What is the use-case or motivation for changing an existing behavior?
Desire for cross-browser compatibility

#### Which versions of Angular, Material, OS, browsers are affected?
Unknown, but using Angular 2, latest Material, Windows 7/IE11 it doesn't work.

**Comment by crisbeto** [comment]
I couldn't reproduce it against IE11 and [the example from our docs.](https://material.angular.io/components/component/tooltip)

**Comment by CPANinjaDoug** [comment]
This turned out to be an employer-enforced security issue which has since been resolved. Thank you for looking into this and I apologize for the inconvenience.
