### ISSUE TITLE
Components site in Demo-App is not scrollable in Safari

### ISSUE THREAD

**Issue by ceelian** [angular/material2#2731]
#### Bug, feature request, or proposal:

Components site in Demo-App is not scrollable in Safari (Version 10.0.2 (12602.3.12.0.1) and also in mobile Safari.

#### What is the expected behavior?

The component site should scroll

#### What is the current behavior?

It does not allow scrolling by touch nor mouse.

#### What are the steps to reproduce?

Browse with safari to e.g. https://material.angular.io/components/component/input
and try to scroll.

#### What is the use-case or motivation for changing an existing behavior?

This is basic behaviour and should work out of the box.

#### Which versions of Angular, Material, OS, browsers are affected?

Commit: 5def001e595384672dc974beb39f9b5f38180666 (recent master)
Safari Version 10.0.2 (12602.3.12.0.1)

**Comment by mac2000** [comment]
Adding `overflow: scroll` to `.docs-component-viewer-sidenav-container.md-sidenav-container` fixes the problem

**Comment by jelbourn** [comment]
I believe this is fixed now.
