### ISSUE TITLE
MdDialog seems to leak the displayed components

### ISSUE THREAD

**Issue by mirceac72** [angular/material2#2734]
#### Bug, feature request, or proposal:
Hi All,

I am using MdDialog to display some modal views defined by Angular 2 components. I observed that the instances of these components are still present in the browser snapshots after the dialog was closed. For example, I display a confirmation dialog for 10 times using a TwoOptions component. After that, the memory snapshot will contain 10 instances of the TwoOptions component.

#### What is the expected behavior?
No instance of the displayed components using MdDialog should remain.

#### What is the current behavior?
The instances of the displayed component are still present, being retained by MdDialogContainer.

#### What are the steps to reproduce?

Open and close a MdDialog view specifying a custom component.

The following plunker provided by 
[Making use of Dialogs in Material 2 (MdDialog)](https://medium.com/@tarik.nzl/making-use-of-dialogs-in-material-2-mddialog-7533d27df41#.r2tkj2lxf)
 can be used to ilustrate the issue
http://plnkr.co/edit/6Eta3GhQLUJTsYz22wsL?p=preview

Press Open Dialog for few times, collect a snapshot in Chrome and check for the ConfirmDialog instances.
![image](https://cloud.githubusercontent.com/assets/25049015/22165960/3be0e4ca-df67-11e6-8d8a-652c8d2c2dfc.png)

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.3, @angular/material: 2.0.0-beta.1, Windows 7, Chrome, Firefox

**Comment by crisbeto** [comment]
Managed to track this one down, but am still looking for a proper fix. As an aside, we seem to be leaking some more objects as well: the `MdDialogContainer` and `MdDialogRef` instances. I'll try to address the other leaks separately.
