### ISSUE TITLE
`md-grid-list`, `md-grid-tile` can't find the way how to align items to left/right #1212

### ISSUE THREAD

**Issue by stefanaerts** [angular/material2#2736]
#### Bug, feature request, or proposal:
iits closed without to say how to do it.
I cat align the text within colums to the left

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by stefanaerts** [comment]
i did it like this,with a div and a class
.text-inside-grid {
  position: absolute;
  left: 5px;
}
probably not the best way,but i don't know the standard way within md-grid

**Comment by yuriyovych** [comment]
any news about this issue?

**Comment by dojchek** [comment]
@yuriyovych 
Just came across this one. Solved it by wrapping the `mat-grid-tile` content with div and setting it to `width: 100%; display: flex; align-items: flex-start;`
