### ISSUE TITLE
core.js missing from alpha.2 package

### ISSUE THREAD

**Issue by cescoferraro** [angular/material2#274]
```
System.config({
	map: {
		text: 'js/text.js'
	},
	packages: {
		'ts': {
			format: 'register',
			defaultExtension: 'js'
		},
		// The core package is required as a peerDependency for other components.
		'node_modules/@angular2-material/core': {
			format: 'cjs',
			defaultExtension: 'js',
			main: 'core.js'
		},
		'node_modules/@angular2-material/checkbox': {
			format: 'cjs',
			defaultExtension: 'js',
			main: 'checkbox.js'
		}


	}});
System.import('ts/boot')
	.then(null, console.error.bind(console));

//
System.import('node_modules/@angular2-material/core')
	.then(null, console.error.bind(console));


System.import('node_modules/@angular2-material/checkbox')
	.then(null, console.error.bind(console));
```

System js cannot find the core.js file inside node_modules, because there are not any.
```

system.src.js:1154 GET http://localhost:9000/node_modules/@angular2-material/core/core.js 404 (Not Found)fetchTextFromURL @ system.src.js:1154(anonymous function) @ system.src.js:1710ZoneAwarePromise @ angular2-polyfills.js:589(anonymous function) @ system.src.js:1709(anonymous function) @ system.src.js:2734(anonymous function) @ system.src.js:3308(anonymous function) @ system.src.js:3575(anonymous function) @ system.src.js:3960(anonymous function) @ system.src.js:4419(anonymous function) @ system.src.js:4671(anonymous function) @ system.src.js:406ZoneDelegate.invoke @ angular2-polyfills.js:332Zone.run @ angular2-polyfills.js:227(anonymous function) @ angular2-polyfills.js:576ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482F @ system-polyfills.js:4H @ system-polyfills.js:4q.when @ system-polyfills.js:4T.run @ system-polyfills.js:4t._drain @ system-polyfills.js:4drain @ system-polyfills.js:4e @ system-polyfills.js:4
angular2-polyfills.js:332 Error: Error: XHR error (404 Not Found) loading http://localhost:9000/node_modules/@angular2-material/core/core.js(…)
```

Neither can i 
```
cesco@desktop: ~/code/go/src/bitbucket.org/cescoferraro/templatego/node_modules/@angular2-material on master [+!]
$ tree
.
├── checkbox
│   ├── checkbox.css
│   ├── checkbox.d.ts
│   ├── checkbox.html
│   ├── checkbox.js
│   ├── checkbox.js.map
│   ├── checkbox.scss
│   ├── checkbox.spec.d.ts
│   ├── checkbox.spec.js
│   ├── checkbox.spec.js.map
│   ├── package.json
│   └── README.md
└── core
    ├── annotations
    │   ├── field-value.d.ts
    │   ├── field-value.js
    │   ├── field-value.js.map
    │   ├── field-value.spec.d.ts
    │   ├── field-value.spec.js
    │   └── field-value.spec.js.map
    ├── live-announcer
    │   ├── live-announcer.d.ts
    │   ├── live-announcer.js
    │   ├── live-announcer.js.map
    │   ├── live-announcer.scss
    │   ├── live-announcer.spec.d.ts
    │   ├── live-announcer.spec.js
    │   ├── live-announcer.spec.js.map
    │   └── README.md
    ├── overlay
    │   ├── overlay-container.d.ts
    │   ├── overlay-container.js
    │   ├── overlay-container.js.map
    │   ├── overlay.d.ts
    │   ├── overlay.js
    │   ├── overlay.js.map
    │   ├── overlay-ref.d.ts
    │   ├── overlay-ref.js
    │   ├── overlay-ref.js.map
    │   ├── overlay.scss
    │   ├── overlay.spec.d.ts
    │   ├── overlay.spec.js
    │   ├── overlay.spec.js.map
    │   ├── overlay-state.d.ts
    │   ├── overlay-state.js
    │   ├── overlay-state.js.map
    │   └── position
    │       ├── global-position-strategy.d.ts
    │       ├── global-position-strategy.js
    │       ├── global-position-strategy.js.map
    │       ├── global-position-strategy.spec.d.ts
    │       ├── global-position-strategy.spec.js
    │       ├── global-position-strategy.spec.js.map
    │       ├── position-strategy.d.ts
    │       ├── position-strategy.js
    │       ├── position-strategy.js.map
    │       ├── relative-position-strategy.d.ts
    │       ├── relative-position-strategy.js
    │       └── relative-position-strategy.js.map
    ├── package.json
    ├── portal
    │   ├── dom-portal-host.d.ts
    │   ├── dom-portal-host.js
    │   ├── dom-portal-host.js.map
    │   ├── portal-directives.d.ts
    │   ├── portal-directives.js
    │   ├── portal-directives.js.map
    │   ├── portal.d.ts
    │   ├── portal-exceptions.d.ts
    │   ├── portal-exceptions.js
    │   ├── portal-exceptions.js.map
    │   ├── portal.js
    │   ├── portal.js.map
    │   ├── portal.spec.d.ts
    │   ├── portal.spec.js
    │   ├── portal.spec.js.map
    │   └── README.md
    ├── README.md
    ├── rtl
    │   ├── dir.d.ts
    │   ├── dir.js
    │   └── dir.js.map
    └── style
        ├── core.scss
        ├── _default-theme.scss
        ├── _elevation.scss
        ├── _mixins.scss
        ├── _palette.scss
        ├── _theme-functions.scss
        └── _variables.scss
```

**Comment by jelbourn** [comment]
@cescoferraro you're right, it is missing from the latest package. However, you shouldn't need to directly import `@angular2-material/core`; all of the components directly reference the contents of core rather than doing through `core.js`.

**Comment by cescoferraro** [comment]
@jelbourn without loading the core module I get 

`angular2-polyfills.js:332 Error: SyntaxError: Unexpected token <(…)ZoneDelegate.invoke @ angular2-polyfills.js:332Zone.run @ angular2-polyfills.js:227(anonymous function) @ angular2-polyfills.js:576ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482ZoneTask.invoke @ angular2-polyfills.js:434` 

everytime I try to add Mdcheckbox to the component directives

**Comment by jelbourn** [comment]
@cescoferraro I have a simple app using System and Angular Material 2 here: https://github.com/jelbourn/material2-app. I've verified that it works with the latest release; do you see a way in which your app is set up differently?

**Comment by cescoferraro** [comment]
@jelbourn  I am on a Golang backend :bowtie:

**Comment by jelbourn** [comment]
@cescoferraro Shouldn't this be backend-agnostic since System handles loading the modules on the client?

**Comment by cescoferraro** [comment]
All the files are accessible, but some why it breaks on my setup

```
	mux := http.NewServeMux()
	mux.Handle("/node_modules/", http.StripPrefix("/node_modules", http.FileServer(http.Dir("./node_modules"))))
	mux.Handle("/html/", http.StripPrefix("/html", http.FileServer(http.Dir("./html"))))
	mux.Handle("/js/", http.StripPrefix("/js", http.FileServer(http.Dir("./js"))))
	mux.Handle("/ts/", http.StripPrefix("/ts", http.FileServer(http.Dir("./ts"))))
	mux.Handle("/css/", http.StripPrefix("/css", http.FileServer(http.Dir("./css"))))
	mux.Handle("/api/register", util.Adapt(api.RegisterHandler(mux),
		api.GetMongoConnection(),
		api.EmptyRegisterUserForm("userRegister"),
		api.EncodeUserJson("userRegister"),
		api.ExpectBody(),
		api.ExpectPOST(),

	))
	mux.Handle("/api/login",util.Adapt(api.LoginHandler(mux),
		api.GetMongoConnection(),
		api.EmptyLoginUserForm("userLogin"),
		api.EncodeUserJson("userLogin"),
		api.ExpectBody(),
		api.ExpectPOST(),

	))

        ...
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "html/index.html")
	})
```

**Comment by SirDarquan** [comment]
Just my two cents. It previously felt like we needed to import the core into the application for the components to work correctly. As such, I had `import "@angular2/core";` in my app.ts file. Since the update I experienced the same issue here. According to @jelbourn, it's no longer necessary to do the import. SO when I removed that line, SystemJs no longer tried to import it.

Seems like information that should have been communicated in the change log. But I'm not 100% sure if that import was actually necessary in the alpha.1. If @cescoferraro can confirm there is a statement to import the core in his code, this issue may be able to be dropped.

**Comment by jelbourn** [comment]
@SirDarquan Indeed, even in alpha.1 you shouldn't ever have had to import anything from core; all of the components should import their dependencies directly from where they live _within_ core (which, incidentally, is _why_ core.js wasn't emitted- nothing imported it).

**Comment by cescoferraro** [comment]
i am not importing anything from angular material. It my first angular-material try. 
There is no angular2-material code inside my app.
I think there is something with the fact that I am loading through http and not with the filesystem. I dont know, it might confuse Systemjs.

**Comment by SirDarquan** [comment]
Ok well, I just thought I'd share what happened with me and confirm that @jelbourn is right and that it (now) works for me also.

**Comment by cescoferraro** [comment]
thanks @SirDarquan

**Comment by jelbourn** [comment]
@cescoferraro The same app also loads all of the resources over http. I suspect that, after removing the import for core, you're running into an unrelated problem. Are all of your dependencies up-to-date (especially the polyfills and zones)?

**Comment by cescoferraro** [comment]
@jelbourn I have just deleted my node-modules folder. Gonna give it a try with the docs specs from https://angular.io/docs/ts/latest/guide/npm-packages.html

**Comment by cescoferraro** [comment]
Same results. 
But now I get a lot of those `Failed to parse SourceMap: http://localhost:9000/components/button/button.js.map` because of the sourcemaps line on the bottom of the js files
`//# sourceMappingURL=../../../../components/button/button.js.map`

**Comment by jelbourn** [comment]
@cescoferraro Are you sure you installed `alpha.2`? I'm looking at the published bundle right now and I see `//# sourceMappingURL=button.js.map`

**Comment by cescoferraro** [comment]
I was trying alpha1 because of the core file, will update soon

**Comment by cescoferraro** [comment]
With alpha2, the sourcemaps string are gone from the button file, but are still present on core.js, core/annotations/one-of.js and core/facade/html.js @jelbourn

**Comment by jelbourn** [comment]
@cescoferraro In `alpha.2` all of those files have been deleted; you likely have leftovers from `alpha.1`

**Comment by cescoferraro** [comment]
Deleted the angular2 folder manually and the sourcemaps are not an issue anymore. But still having the polyfill error.
Everything stops working as soon as I remove the comments


```
import {Component} from 'angular2/core';
import {MenuComponent} from './menu.component';
import {ROUTER_DIRECTIVES, RouteConfig} from 'angular2/router';
import {RegisterComponent} from './register/register.component';
import {LoginComponent} from './login/login.component';
import {DashboardComponent} from './dashboard/dashboard.component';
import {LightsComponent} from './lights/lights.component';
import {SoundComponent} from './sound/sound.component';
// import {MdButton} from '@angular2-material/button';


@Component({
  selector: 'chrome',
  template:`<menu></menu><button md-button>FLAT</button>`,
  directives: [ROUTER_DIRECTIVES,
	  RegisterComponent,
	  LoginComponent,
	  MenuComponent,
	  // MdButton
  ],
  styleUrls: ['css/main.css']
  })


@RouteConfig([
  {path: '/login', name: 'Login', component: LoginComponent},
  {path: '/register', name: 'Register', component: RegisterComponent},
  {path: '/dashboard', name: 'Dashboard', component: DashboardComponent},
  {path: '/dashboard/lights', name: 'Lights', component: LightsComponent},
  {path: '/dashboard/sound', name: 'Sound', component: SoundComponent}
])

export class ChromeComponent {
   ngOnInit() {
    console.log('angular version');
  }
}
```

**Comment by jelbourn** [comment]
@cescoferraro without more information about the error being thrown, it's impossible to know what the problem might be. My best guess it to compare how you're loading your polyfills compared to the example app I linked earlier and make sure the order and the versions are the same.

**Comment by cescoferraro** [comment]
Thanks @jelbourn and @SirDarquan! I got it now. 
If you check my first comment, I was trying to load the angular/material2 files from inside the node_modules file server. Now I created the a file server  /@angular2-material endpoint for and am loading the files from there. That extra folder was messing everything up. Still do not know why, but it works now.
