### ISSUE TITLE
ng test error md-select

### ISSUE THREAD

**Issue by leovafme** [angular/material2#2741]
#### Bug, feature request, or proposal:
The test fails when the md-select component is added in the html

When running ng test causes the following error:

at createResult (webpack:///~/@angular/compiler/src/jit/compiler.js:147:0 <- src/test.ts:39096:19)
	    at JitCompiler._compileModuleAndAllComponents (webpack:///~/@angular/compiler/src/jit/compiler.js:151:0 <- src/test.ts:39100:88)
	    at JitCompiler.compileModuleAndAllComponentsSync (webpack:///~/@angular/compiler/src/jit/compiler.js:98:0 <- src/test.ts:39047:21)
	    at TestingCompilerImpl.compileModuleAndAllComponentsSync (webpack:///~/@angular/compiler/bundles/compiler-testing.umd.js:482:0 <- src/test.ts:55576:35)
	    at TestBed._initIfNeeded (webpack:///~/@angular/core/bundles/core-testing.umd.js:761:0 <- src/test.ts:18124:40)
	    at TestBed.createComponent (webpack:///~/@angular/core/bundles/core-testing.umd.js:844:0 <- src/test.ts:18207:18)
	    at Function.TestBed.createComponent (webpack:///~/@angular/core/bundles/core-testing.umd.js:673:0 <- src/test.ts:18036:33)
Chrome 55.0.2883 (Mac OS X 10.12.2): Executed 4 of 4 (4 FAILED) ERROR (1.189 secs / 0.563 secs)

code:
app.component.html

```
> <md-toolbar color="primary">
>   <span>Application Title</span>
> 
>   <!-- This fills the remaining space of the current row -->
>   <span class="example-fill-remaining-space"></span>
> 
>   <span>Right Aligned Text</span>
> </md-toolbar>
> 
> <h1>
>   {{title}}
> </h1>
> 
> <h2>
>   {{title}}
> </h2>
> 
> <span id="gh">Click me!</span>
> 
> <md-input-container>
>   <input md-input placeholder="Favorite food" value="Sushi">
> </md-input-container>
> 
> <md-select placeholder="Favorite food">
>   <md-option *ngFor="let food of foods" [value]="food.value">
>     {{ food.viewValue }}
>   </md-option>
> </md-select>
```

<button md-button color="primary" md-raised-button>Click me!</button>

app.component.ts

import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';

  foods = [
    {value: 'steak-0', viewValue: 'Steak'},
    {value: 'pizza-1', viewValue: 'Pizza'},
    {value: 'tacos-2', viewValue: 'Tacos'}
  ];
}

module.ts

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { MaterialModule } from '@angular/material';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    MaterialModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

app.component.spec.ts

import { TestBed, async } from '@angular/core/testing';
import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
    });
    TestBed.compileComponents();
  });

  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));

  it(`should have as title 'app works!'`, async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).toEqual('app works!');
  }));

  it('should render title in a h1 tag', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('h1').textContent).toContain('app works!');
  }));

  it('should render title in a h2 tag', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('h2').textContent).toContain('app works!');
  }));

});

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by kara** [comment]
Do you have the actual error text? It seems to be missing above.

**Comment by leovafme** [comment]
@kara , I was testing and the code fails when you add the md-select component inside the templateUrl and run the ng test command

**Comment by kara** [comment]
@leovafme Can you please post the specific error? We are not able to reproduce in any of the tests in our repo that use md-select. See them [here](We have an entire suite of md-select tests running in our CI that don't fail).

**Comment by leovafme** [comment]
@kara Please look at the repository and the test in travis ci
[https://github.com/leovafme/md-select-test](https://github.com/leovafme/md-select-test)
[https://travis-ci.org/leovafme/md-select-test/jobs/195037169](https://travis-ci.org/leovafme/md-select-test/jobs/195037169)

**Comment by kara** [comment]
@leovafme Thanks! It looks like you didn't call `fixture.detectChanges()` in that test, so change detection never runs. The select component won't be set up properly if change detection doesn't happen. See example code below:

```ts
it(should have as title 'app works!', async(() => {
const fixture = TestBed.createComponent(AppComponent);
fixture.detectChanges();
const app = fixture.debugElement.componentInstance;
expect(app.title).toEqual('app works!');
}));


```
