### ISSUE TITLE
How do you debug this project?

### ISSUE THREAD

**Issue by acpower7** [angular/material2#2749]
I am trying to set breakpoints and debug this app to better understand some parts.
However I don't get the original source but instead some HTML. Please see screenshots. 

Also, And use gulp, why not Webpack 2 ?

<img width="2362" alt="screenshot" src="https://cloud.githubusercontent.com/assets/5999365/22179065/d19c57b6-e09c-11e6-9665-343e906053aa.png">

**Comment by DevVersion** [comment]
@acpower7 Webpack is not the right choice for libraries at the moment. For Material 2 we need a lot of flexibility to generate Metadata files to support AOT and more.

From looking at your sources in the screenshot I can see that you try to open the files from the `src/` path. 
> Once the demo-app is served, the `dist/` folder will be served, and all other web requests that are invalid will be redirected to the index HTML file.

You should just the `.js` files and those will be automatically mapped to the associated TS file.

**Comment by acpower7** [comment]
Thanks for the reply.

I'm not sure I undertand as I can't find a dist folder in the chrome tools, or even an src/ path. The .js files are es5 and .ts files all show html. Can you give me more clear instructions.

<img width="562" alt="screenshot" src="https://cloud.githubusercontent.com/assets/5999365/22181584/70a61590-e0e3-11e6-8df5-146a3eadc7b1.png">

**Comment by DevVersion** [comment]
What happens if you now click on the `slide-toggle` folder and open the TS file? Does that work?

**Comment by acpower7** [comment]
No it doesn't. Honestly this whole project has a very poor development process, I would have expected more from Google.

![screenshot](https://cloud.githubusercontent.com/assets/5999365/22182088/162979ec-e0f0-11e6-86f3-5f58dca11aa3.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/5999365/22182091/251c1a68-e0f0-11e6-9a21-6d90a69e7acf.png)

**Comment by acpower7** [comment]
edit

**Comment by acpower7** [comment]
Hey, I really don't want to create a new issue......

**Comment by DevVersion** [comment]
Take a look at PR https://github.com/angular/material2/pull/2753 and also notice that the UMD bundles still don't have any sourcemaps. Will will address that in a follow-up PR.

**Comment by acpower7** [comment]
So how do you guys currently debug this library, set breakpoints etc? How do you do it?

**Comment by DevVersion** [comment]
So if we run into issues with components: 

* Most of the time the unit-tests are showing errors and can be solved then easily.
* Debugging most of the time does happens in the unit tests and in the demo-app

Also the sourcemaps for the demo-app & e2e-app are only broken since recently.

So basically there is no big secret about debugging here. We just write a lot of tests that can detect issues quickly.
