### ISSUE TITLE
mdInput cannot override placeholder color

### ISSUE THREAD

**Issue by gioragutt** [angular/material2#2751]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I set the '.md-input-placeholder' color style, the placeholder color would change

#### What is the current behavior?
Angular loads the css in a way that it's overridden by the angular material css bundle

#### What are the steps to reproduce?
I copied the example from https://material.angular.io/components/component/input overview, pasted it in my page, and the color is rgba(255,255,255,0.3), which is basically invisible.

#### What is the use-case or motivation for changing an existing behavior?
Motivation is that the placeholder is basically invisible for some reason.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.3.1, (can't find material dependency in the package.json for some reason), Ubuntu 16.04, chromium

#### Is there anything else we should know?
It's a small change, I don't know why it is impossible to override by default, which I assume is something you'd generally want to allow

**Comment by fxck** [comment]
same "problem" as with https://github.com/angular/material2/issues/2745
