### ISSUE TITLE
Error messages using mdDialog component

### ISSUE THREAD

**Issue by ronaldoSf** [angular/material2#2755]
#### Bug, feature request, or proposal:
Angular displays error on console using the MdDialog component

#### What is the expected behavior?
Not display any error

#### What is the current behavior?
Dialog components need to be in the bootstrap section of the module declaration, otherwise it does not work. When the component is declared on bootstrap section everithing works fine but these messages are showed at the beginning of the page load, what is annoying:

![image](https://cloud.githubusercontent.com/assets/9108098/22184259/4ef3d51e-e0b5-11e6-924a-8d837d39d5b6.png)

#### What are the steps to reproduce?
Access this page: https://material.angular.io/components/component/dialog
Go to "Edit in plunker"
Access the console of chrome or any browser and see the error messages

#### What is the use-case or motivation for changing an existing behavior?
I dont know why it's needed to declare the dialog component in bootstrap section, but declaring it is the cause of these messages

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.3.1, Material 2.0.0-beta.1, Google Chrome

#### Is there anything else we should know?
No

**Comment by thomaspink** [comment]
`DialogOverviewExampleDialog` hast to be moved from to `bootstrap` array to `entryComponents` in the module.

Updated Plnkr:
https://plnkr.co/edit/3XdN8VSe205h2iKSjxmY?p=preview

**Comment by jelbourn** [comment]
This was changed in #2556 and will be in the next release
