### ISSUE TITLE
md-spinner no color change

### ISSUE THREAD

**Issue by stefanbachert** [angular/material2#2756]
#### Bug, feature request, or proposal:

Changing color has no effect 

&lt;md-spinner color="warn"&gt;&lt;/md-spinner&gt;

#### What is the expected behavior?

Color should change

#### What is the current behavior?

No color change

#### What are the steps to reproduce?

https://material.angular.io/components/component/progress-spinner
Goto "Example Tab" and change color

#### Which versions of Angular, Material, OS, browsers are affected?

I am using Chrome/Windows 10, current version of Angular Material, Website does not show used version

**Comment by sumpton** [comment]
I don't know if this is related, but the plnkr example appears to be incorrect.

This example from https://material.angular.io/components/component/progress-spinner

did not work for me

https://plnkr.co/edit/Rf4tEd9Ox6GysJPZXXJM?p=preview

```html
<md-progress-circle
        class="example-margin"
        [attr.color]="color"
        [mode]="mode"
        [value]="value">
</md-progress-circle>
```
but this works

https://plnkr.co/edit/Xlk4PWG1LcDKksnKGuec?p=preview

```html
<md-progress-circle
        class="example-margin"
        color="{{ color }}"
        mode="{{ mode }}"
        value="{{ value }}">
</md-progress-circle>
```

https://plnkr.co/edit/Xlk4PWG1LcDKksnKGuec?p=preview

**Comment by stefanbachert** [comment]
Dear All,
I changed the plunker example like this: 
...    <md-progress-circle        class="example-margin"        color="warn"            // attribute        [color]="color"          // property        [mode]="mode"        [value]="value">    </md-progress-circle>..
I would expect starting with color "warn", which failed.Changing the property using the radiobuttons will work.
For me it looks like the ATTRIBUTE color will not used as initial value for the PROPERTY color.

Best Regards
Stefan
      Von: Jerry Sumpton <notifications@github.com>
 An: angular/material2 <material2@noreply.github.com> 
CC: stefanbachert <stefanbachert@yahoo.de>; Author <author@noreply.github.com>
 Gesendet: 19:10 Samstag, 28.Januar 2017
 Betreff: Re: [angular/material2] md-spinner no color change (#2756)
   
I don't know if this is related, but the plnkr example appears to be incorrect.This example from https://material.angular.io/components/component/progress-spinnerdid not work for mehttps://plnkr.co/edit/Rf4tEd9Ox6GysJPZXXJM?p=preview<md-progress-circle
        class="example-margin"
        [attr.color]="color"
        [mode]="mode"
        [value]="value">
</md-progress-circle>but this workshttps://plnkr.co/edit/Xlk4PWG1LcDKksnKGuec?p=preview<md-progress-circle
        class="example-margin"
        color="{{ color }}"
        mode="{{ mode }}"
        value="{{ value }}">
</md-progress-circle>https://plnkr.co/edit/Xlk4PWG1LcDKksnKGuec?p=preview—

**Comment by stefanbachert** [comment]
Dear All,
I took a look on the code:

| export class MdProgressSpinner implements OnDestroy { |
| ... | 
 |
|  |  private _color: string = 'primary'; |


This is one part of the defect. Primary color hardcoded as initial initial value. The ATTRIBUTE color will not taken into account.
A better approach would be to let it to an explicit undefined value.When the requesting would result in an undefined value,first check ATTRIBUTE color of the element, if not available then and only then usr color "primary"
This approach has some runtime effects. One could change ATTRIBUTE color programmatically, depending timing results may different. However, this seems unlikely to me.
This approach could be modified to be applied during initialization


Hope this helps

Best Regards
Stefan Bachert



      Von: Jerry Sumpton <notifications@github.com>
 An: angular/material2 <material2@noreply.github.com> 
CC: stefanbachert <stefanbachert@yahoo.de>; Author <author@noreply.github.com>
 Gesendet: 19:10 Samstag, 28.Januar 2017
 Betreff: Re: [angular/material2] md-spinner no color change (#2756)
   
I don't know if this is related, but the plnkr example appears to be incorrect.This example from https://material.angular.io/components/component/progress-spinnerdid not work for mehttps://plnkr.co/edit/Rf4tEd9Ox6GysJPZXXJM?p=preview<md-progress-circle
        class="example-margin"
        [attr.color]="color"
        [mode]="mode"
        [value]="value">
</md-progress-circle>but this workshttps://plnkr.co/edit/Xlk4PWG1LcDKksnKGuec?p=preview<md-progress-circle
        class="example-margin"
        color="{{ color }}"
        mode="{{ mode }}"
        value="{{ value }}">
</md-progress-circle>https://plnkr.co/edit/Xlk4PWG1LcDKksnKGuec?p=preview—
