### ISSUE TITLE
md-dialog not supporting modularity

### ISSUE THREAD

**Issue by feniixx** [angular/material2#2759]
#### What is the expected behavior?
Having submodules and declaring the dialog components at those submodules, and also add the `entryComponents` property value at that submodule and get to work the dialog.

#### What is the current behavior?
The dialog is not working, the component has to be declared and added as an entryComponent at the **AppModule** *or the root module* to work

#### What are the steps to reproduce?
Create an app with a dialog component in a submodule, declare the component at the submodule and also add it as an entryComponent at the submodule.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.4.3
Material: 2.0.0-beta.1
OS: OS X El Capitan
Browsers: Chrome(Just tested in this)

Error message:

>EXCEPTION: Error in ./UsersComponent class UsersComponent - inline template:23:2 caused by: No component factory found for AddUserDialog. Did you add it to @NgModule.entryComponents?

**Comment by pierreclr** [comment]
I have exactly the same problem ..

**Comment by Roman-K93** [comment]
+1

**Comment by delsner** [comment]
@feniixx are you lazy-loading the submodules ? If so this is possibly related to #1765

**Comment by jelbourn** [comment]
This is changed in #2556 and will be part of the next release
