### ISSUE TITLE
md-select default value

### ISSUE THREAD

**Issue by Tytam** [angular/material2#2762]
#### Bug, feature request, or proposal:
When using formBuilder default value passed to formBuilder does not show as selected in md-select. 

#### What is the expected behavior?
If I select value in formBuilder its name and value should appear as selected option of md-select.

#### What is the current behavior?
Placeholder is displayed instead.

#### What are the steps to reproduce?
typescript:
`this.editForm = this.formBuilder.group({
                            projectId: [this.task.project._id]
                          });`
or:
`this.editForm = this.formBuilder.group({
                            projectId: new FormControl({value: this.task.project._id}, Validators.required)
                          });`

html:
`<form  layout="column" [formGroup]="editForm" (ngSubmit)="saveTask(task)"><md-select formControlName="projectId" name="project" placeholder="{{'FORM.PROJECT' | translate }}"><md-option *ngFor="let project of projects | async" [value]="project._id">{{project.name}}</md-option></md-select><select formControlName="projectId" name="project"><option *ngFor="let project of projects | async" [value]="project._id">{{project.name}}</option></select></form>`

standard html works, md does't
#### What is the use-case or motivation for changing an existing behavior?
Edit forms.  Lets have a class with 20 attributes each of them can be changed using one form. You don't want to refill all these attributes if you want to change just one.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.2.1
Material 2.0.0-beta.1
WIN 10 Vivaldi Firefox tested (but probably all affected)

**Comment by asbcoder** [comment]
Was about to raise a similar issue regarding the default value on md-select. The following does not set the default value of the select either: -

`<md-select placeholder="Year" [(ngModel)]="selectedYear.Key" (change)="onYearSelect()">
           <md-option *ngFor="let year of (yearsByCourse$|async)" [value]="year.Key">
                            {{ year.Description }}
            </md-option>
</md-select>`

When selectedYear.Key : -

 `this.selectedYear = { Key: '000116', Description: '16/17', CalendarYear: 2016 };`

Works fine on a normal <select>. Maybe raise this as seperate issue?

**Comment by Tytam** [comment]
Somehow my code now works (we made mayor backend changes). So my issue bay be caused by angular 2 meteor I use and not material problem. If I find out something new I write a comment here.

**Comment by kara** [comment]
@Tytam Given that your code now works, I'm going to close this for now. Feel free to open a new issue if you run into anything else.

@asbcoder It sounds like you may have run into https://github.com/angular/material2/issues/2497, which was fixed in https://github.com/angular/material2/pull/2499. It's in master, but not yet released. If you're still having problems after the next release, please open an issue.

**Comment by MrCroft** [comment]
Hmmm... In my case, it has nothing to do with #2497 (`options initialized after the model`).
But what's even stranger is that, out of 2 selects, one automatically shows the first value as selected and the other one shows the placeholder text. I can't explain it.

This is what I have in my component:
`filters.component.ts`:
```
ngOnInit() {
    let sortBy = 'date_uploaded-desc';
    let perPage = '20';

    this.filterForm = new FormGroup({
        'sortBy': new FormControl(sortBy),
        'perPage': new FormControl(perPage)
    });
}
```

`filters.component.html`:
```
<form class="filters"
    [formGroup]="filterForm">
        <md-select placeholder="Sort by"
            formControlName="sortBy">
                <md-option [value]="'views-desc'">Views</md-option>
                <md-option [value]="'status-desc'">Status</md-option>
                <md-option [value]="'date_published-desc'">Date Published</md-option>
                <md-option [value]="'date_uploaded-desc'">Date Uploaded</md-option>
        </md-select>

        <md-select placeholder="Show"
            formControlName="perPage">
                <md-option [value]="'10'">10</md-option>
                <md-option [value]="'20'">20</md-option>
                <md-option [value]="'30'">30</md-option>
        </md-select>
</form>
```

When the component is initialized, the `perPage` select shows the first option (`10`) and the `sortBy` select shows the placeholder text `Sort by`...

@angular/material - **2.0.0-beta.3**
@angular/* - **4.1.0-rc.0**

So, I understand this will be solved with the next release...

**Comment by jeewanaryal2012** [comment]
Please open this issue, I am having the same issue now. The default value does not show up, it shows the placeholder instead.

**Comment by peterramsing** [comment]
I've run into this before with numbers and it was because our types misaligned. Worth making sure your types are correct if one runs into this.

**Comment by kailash-cd** [comment]
Facing same issue in following -- 
<md-select
            placeholder="Choose your country"
            [(ngModel)]="selectedCountries"
            multiple searchable
            class="infoRow2 input-container" >
            <md-input-container class="infoRow2 input-container" style="width:100%;" ngClass="{{companyTheme+'_themeInput'}}">
                <input
                    mdInput
                    ngClass="{{companyTheme+'_themeInput'}}"
                    [(ngModel)]="poiModule.countryFilterKey" 
                    type="search"
                    placeholder="Search Country">
              </md-input-container>
              
            <md-option
              ngClass="{{companyTheme+'_themeSelectOption'}}"
              *ngFor="let country of countryOptions | filter: {'name':countryFilterKey} "
              [value]="country"
              (click)="updateCountries(country)">
              {{ country.name }}
            </md-option>
          </md-select>

default value --
selectedCountries = [
        {'code': 'JA', 'name': 'Japan', 'center': [36.204824,138.252924]},
        {'code': 'US', 'name': 'United States', 'center': [37.2566274, -95.712891]}
      ];
