### ISSUE TITLE
Md-Select (change) not working

### ISSUE THREAD

**Issue by sanyooh** [angular/material2#2766]
Type: Bug

#### What is the expected behavior?
(change) on md-select component should register change in selected value.

#### What is the current behavior?
(change) on md-select component is not recognizing a change.

I've created a plunker to see the behaviour:
Plunker template: https://plnkr.co/edit/biiHzaidgwgRF1efyXF5?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Md-select should provide the same functionality as a basic select element.

**Comment by mwamufiya** [comment]
Is there any reason your not binding your md-select to an model so the change is registered? 

ie: md-select [(ngMode)]="selectedValue". 

https://plnkr.co/edit/IcLEoesRIDXTYZ8NV90z?p=preview

also, according to the API specs, the "onSelect" method is on md-option not md-select. if I'm reading this right.

https://material.angular.io/components/component/select

**Comment by kara** [comment]
@sanyooh The 'change' event is a feature that was added to the select by https://github.com/angular/material2/pull/2458. It's in master, but has not yet been released. It will be available in the next Material release.

As @mwamufiya mentioned, in the meantime, you should be able to use any directive from either `FormsModule` or `ReactiveFormsModule`.
