### ISSUE TITLE
Dialog opening twice in Chrome.

### ISSUE THREAD

**Issue by moyzes** [angular/material2#2769]
#### Bug, feature request, or proposal:

After implementing the tutorial, when we click to open the dialog, it opens twice; one dialog over other. It's happening only in Chrome, tested in Firefox and it's working OK.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by andrewseguin** [comment]
Can you provide an example plunker that reproduces your issue? Here's an example of dialog usage that is not showing duplicated dialogs: https://plnkr.co/edit/dYbIJ95IyfpxlY91BADX?p=preview

What version of material are you using?

**Comment by moyzes** [comment]
My bad Andrew, I was calling twice (in a parent element and in a child element with different parameters). I split them and it worked perfectly. Somehow Firefox ignored the child calling.
