### ISSUE TITLE
The md-input background color is not defined in terms of the theme

### ISSUE THREAD

**Issue by UnwrittenFun** [angular/material2#277]
The underlying input of the md-input has a white background (as is default in browsers).

This means the input doesn't look great on non-white backgrounds.

![](https://share.unwrittenfun.uk/WebStorm_2016-04-08_03-43-55.png)

using alpha2 on electron

**Comment by gxclarke** [comment]
I came across this too, and added the following to my style-sheet to address:

    md-input input { background-color: inherit; }

I'm sort of expecting to hear from the material 2 team that this should be a styling concern for the consuming application rather than a responsibility of the component. We shall see...
