### ISSUE TITLE
md-radio-group doesn't work in module included via *ngFor

### ISSUE THREAD

**Issue by mcalmus** [angular/material2#2772]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should show all model-bound values.

#### What is the current behavior?
Only showing value from last bound model.

#### What are the steps to reproduce?
Create a component containing ng-button-group bound to a model.
Include that component in another page uinsg *ngFor

I'm having problems unrelated to the issue, but here is the plnkr that shows the code.
http://plnkr.co/edit/HLD0PrdSzDs6KitUAeQh?p=info

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-beta1, Windows 7, FF, haven't tried others.

#### Is there anything else we should know?
If I pass an index variable from the loop into the component and name the ng-button-group using that index (index="val-{{index}}") things work ok, but I don't think that should be required.

I think this is related to 
https://github.com/angular/material2/issues/831

**Comment by tinayuangao** [comment]
The plunker is using `*ngIf` instead of `*ngFor`.

Following piece of code works: 

```
values: boolean[] = [true, false, true];
<form >
  <div *ngFor="let value of values; let i = index">
    <md-radio-group [(ngModel)]="values[i]" name="valField-{{i}}">
      <md-radio-button [value]="true">True</md-radio-button>
      <md-radio-button [value]="false">False</md-radio-button>
    </md-radio-group>
  </div>
</form>
```

**Comment by mcalmus** [comment]
Your sample code virtually demonstrates the problem. The radio group only works if the name has the index as a part of it. That's fine when it's inlined. When it's included as a separate component (as in the plunkr example) it's not reasonable to have to index the name.
