### ISSUE TITLE
`locals` use in `TemplatePortalHost`

### ISSUE THREAD

**Issue by emilio-martinez** [angular/material2#2777]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Portal is an interesting part of a component dev toolkit, and one portion that strikes me as with potential but not very much explored—at least from an outside perspective—is the `locals` property in `TemplatePortalHost` which is not explained very much in either documentation or via examples in the unit or e2e testing. Further clarification on those items would be great to have.

#### What is the current behavior?
Little to no documentation. There are some `TODO` comments to return `locals` but they're pending within. Additionally, there are no tasks slotted in Github that I can identify to complete this piece, either in code or documentation.

#### Is there anything else we should know?
Currently viewing this on angular/material2 v2.0.0-beta.1

**Comment by jelbourn** [comment]
Closing into the broader #2789
