### ISSUE TITLE
(SystemJS) Unexpected token <

### ISSUE THREAD

**Issue by victorschinaider** [angular/material2#2778]
#### Bug, feature request, or proposal:
I'm trying to setup angular material, but i'm getting this error...

Console:
```
(SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:8081/public/js/ts/app.module.js:15:20)
	    at eval (http://localhost:8081/public/js/ts/app.module.js:38:4)
	    at eval (http://localhost:8081/public/js/ts/app.module.js:39:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:8081/public/@angular/material/material.umd.js
	Evaluating http://localhost:8081/public/js/ts/app.module.js
	Evaluating http://localhost:8081/public/js/ts/app.main.js
	Error loading http://localhost:8081/public/js/ts/app.main.js
```

**System.js file**
```
map: {
    ...,
    '@angular/material': 'npm:@angular/material/material.umd.js'
}
```

**app.module.ts**
```
import { MaterialModule } from '@angular/material';

@NgModule({
    imports: [
        ...,
        MaterialModule.forRoot()
    ],
    ....
})
```

I search 'similar' issues, and tried to do somethings, but no success.
- I already tried to remove 'node_modules' and reinstall.
- I tried to update the node.js to 7.4.0.
- Angular 2.4.4
- TypeScript 2.1.5

#### What is the expected behavior?
No error, like Getting Started

#### What is the current behavior?
Sending me error

#### What are the steps to reproduce?
Configuration error, see first question.

#### Which versions of Angular, Material, OS, browsers are affected?
lastest

#### Is there anything else we should know?
In first question.

**Comment by DevVersion** [comment]
Sorry for that. The correct path is

```js
    '@angular/material': 'npm:@angular/material/bundles/material.umd.js'
```

We have fixed that in the source and the docs will be re-published soon. Thanks for the issue.

**Comment by victorschinaider** [comment]
This solved the problem. Thanks!
