### ISSUE TITLE
MdSideNav closes when soft keyboard appears on Android

### ISSUE THREAD

**Issue by doorman02** [angular/material2#2779]
#### Bug, feature request, or proposal:
When MdSideNav is open and it contains a input field. When the input field get's focus the soft keyboard appears. When the keyboard appears the MdSideNav closes automatically.

#### What is the expected behavior?
The MdSideNav should stay open even when keyboard appears.

#### What is the current behavior?
The MdSideNav closes when keyboard appears.

#### Which versions of Angular, Material, OS, browsers are affected?
Latest angular and material, android, chrome

**Comment by mmalerba** [comment]
@doorman02 can you provide some code to repro this? It seems to work fine for me

**Comment by doorman02** [comment]
Hi, you are right this was a bug on my site. I assumed it was android related because it worked fine on iPhone. Thanks for your help!
