### ISSUE TITLE
undefined variable compiling core.scss

### ISSUE THREAD

**Issue by UnwrittenFun** [angular/material2#278]
When compiling core.scss from the core package to use the elevation classes, it complains about an undefined variable `$md-fast-out-slow-in-timing-function`. It looks to me like core.scss or _elevation.scss should be importing _variables.scss but isn't.

**Comment by jelbourn** [comment]
Fixed in #293

**Comment by shotleybuilder** [comment]
Is this error back or is it my compile ...?

> 
Scss compiler error: Undefined variable: "$md-fast-out-slow-in-timing-function".

My main.scss
```
@import "../../node_modules/@angular2-material/core/style/core.scss";
@import "../../node_modules/@angular2-material/button/button.scss";
@import "../../node_modules/@angular2-material/input/input.scss";
@import "../../node_modules/@angular2-material/checkbox/checkbox.scss";
```

I've manually patched like this
example checkbox.scss
```
@import '../core/style/default-theme';
@import '../core/style/theme-functions';
@import '../core/style/variables';
@import '../core/style/mixins';
```

Because of #887

**Comment by shotleybuilder** [comment]
Fixed by changing core.scss from

```
@import 'elevation';
@import 'variables';
```

to

```
@import 'variables.scss';
@import 'elevation.scss';
```

The order matters.

Then complained about the $md--light-theme-background' variable being undefined

Simply added .scss extension to the imports in _default-them.scss.

All now compiles.
