### ISSUE TITLE
md-select: add compareWith function

### ISSUE THREAD

**Issue by kara** [angular/material2#2785]
Currently, md-select values are compared by object reference. This is a bit inflexible. We want to allow people to compare options by a custom comparator in case they only care about the object's ID or some other property.

Example markup:

```html
<md-select placeholder="Food" [(ngModel)]="food" [compareWith]="compareById">
   <md-option *ngFor="let food of foods" [value]="food"> {{ food.name }} </md-option>
</md-select>
```

```ts
compareById(obj1, obj2) {
   return obj1.id === obj2.id;
}

```

This will be parallel to [functionality being added to native selects in core](https://github.com/angular/angular/pull/13349).

**Comment by jamalx31** [comment]
+1

**Comment by am-a** [comment]
+1

**Comment by paistipoikka** [comment]
@kara is this still being considered?

**Comment by mackva** [comment]
What news?

**Comment by linuradu** [comment]
Sounds good, regarding commit :) When will be the next release?

**Comment by pdavin** [comment]
Any update on this? Looks like there's a fix in a forked branch but not submitted for PR / review yet.

**Comment by kweinmeister** [comment]
It looks like there is a PR, but it now has a merge conflict: https://github.com/angular/material2/pull/4540

**Comment by jeanpchr** [comment]
Has anyone implemented a workaround?

**Comment by ppham27** [comment]
I have PR #4540 open. I'm pretty good about rebasing it pretty often, so if you really need the feature, you could build against my branch. I'm not sure when/if they plan on merging it into master.

**Comment by reppners** [comment]
Desperately need this 👍
