### ISSUE TITLE
Documentation for Component Dev Kit 

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#2789]
Currently material.angular.io only documents the components. Once we reach a point where we're happy with the stability / features of the cdk, we will expand that documentation to include the cdk pieces.

**Comment by jhwegener** [comment]
The latest post on http://angularjs.blogspot.de/ announces the CDK - but the link in this sentence (To get started building components using the CDK, install it from our npm repository and take a look at our documentation on GitHub for usage information.) only links to this repo!?
Is there a documentation already?

**Comment by jelbourn** [comment]
I was referring to the markdown files in github, e.g. https://github.com/angular/material2/blob/master/src/cdk/a11y/live-announcer.md

We'll be adding the docs to material.angular.io eventually, but for now the basic docs live on github.

**Comment by jelbourn** [comment]
Closing this issue
