### ISSUE TITLE
`md-ink-bar` doesn't calculate initial width properly when min-width of `md-tab-link` is overriden

### ISSUE THREAD

**Issue by fxck** [angular/material2#2794]
![image](https://cloud.githubusercontent.com/assets/1303561/22282948/b360506e-e2df-11e6-9449-283b4a6a7e43.png)

while it's perhaps not on spec to have a tab without min-width, I think it's not an unreasonable thing to do for a consumer.. also it works fine after you click on a tab

see http://plnkr.co/edit/u5M39n994lJriqMABMod?p=preview

@andrewseguin @jelbourn maybe?

**Comment by andrewseguin** [comment]
Issue has been fixed by #3037
