### ISSUE TITLE
Add elevation guide

### ISSUE THREAD

**Issue by Splaktar** [angular/material2#2800]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
That `.md-elevation-zX` classes are documented.

#### What is the current behavior?
No documentation exists other than within closed [PR](https://github.com/angular/material2/pull/2212) and [issue](https://github.com/angular/material2/pull/222/files) comments. There are some [design documents](https://docs.google.com/document/d/1W3NGSLqDZzjbBBLW2C6y_6NUxtvdZAVaJvg58LY3Q0E/edit?usp=sharing), but they aren't really designed for developers using the APIs.

#### What is the use-case or motivation for changing an existing behavior?
To avoid repeated [questions](https://github.com/angular/material2/pull/222#issuecomment-243015295) and rejected PRs like https://github.com/angular/material2/pull/2212.

#### Is there anything else we should know?
I would like to help with this documentation, but I would like some feedback on how the team would like this to be done before I submit a PR.

Should there be a separate doc/guide for elevation that covers examples of multiple components?

Should there be examples of using elevation in each component that it applies to?
Is there a list of such components?

**Comment by jelbourn** [comment]
It would be great to have a short and simple guide on elevation in the `guides/` directory.

**Comment by ladyleet** [comment]
agreed would be fabulous! // @EladBezalel (thx @Splaktar!) I like the simplicity of MaterializeCSS docs http://materializecss.com/shadow.html

**Comment by farantesrodrigues** [comment]
The mixins should also be documented like ```@include md-elevation($zValue);``` (the design documents this is ```mdElevation($zValue)```)

**Comment by rviveiros** [comment]
Now we should use   @include mat-elevation($zValue);

**Comment by M-a-c** [comment]
@Splaktar Do you have a Pr in progress that I could help with or anything like that?

**Comment by Splaktar** [comment]
@M-a-c no sorry. I had other priorities jump up and haven't had a chance to get back to this. Thank you for helping out!

**Comment by megamindbrian** [comment]
I have a problem with hundreds of elevation directives being injected in for EVERY component.  Every components has CSS styles like this:
```
.mat-elevation-z0 {
  box-shadow: 0px 0px 0px 0px rgba(0, 0, 0, 0.2), 0px 0px 0px 0px rgba(0, 0, 0, 0.14), 0px 0px 0px 0px rgba(0, 0, 0, 0.12); }

.mat-elevation-z1 {
  box-shadow: 0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12); }

.mat-elevation-z2 {
  box-shadow: 0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 5px 0px rgba(0, 0, 0, 0.12); }

.mat-elevation-z3 {
  box-shadow: 0px 3px 3px -2px rgba(0, 0, 0, 0.2), 0px 3px 4px 0px rgba(0, 0, 0, 0.14), 0px 1px 8px 0px rgba(0, 0, 0, 0.12); }

.mat-elevation-z4 {
  box-shadow: 0px 2px 4px -1px rgba(0, 0, 0, 0.2), 0px 4px 5px 0px rgba(0, 0, 0, 0.14), 0px 1px 10px 0px rgba(0, 0, 0, 0.12); }

.mat-elevation-z5 {
  box-shadow: 0px 3px 5px -1px rgba(0, 0, 0, 0.2), 0px 5px 8px 0px rgba(0, 0, 0, 0.14), 0px 1px 14px 0px rgba(0, 0, 0, 0.12); }

.mat-elevation-z6 {
  box-shadow: 0px 3px 5px -1px rgba(0, 0, 0, 0.2), 0px 6px 10px 0px rgba(0, 0, 0, 0.14), 0px 1px 18px 0px rgba(0, 0, 0, 0.12); }

.mat-elevation-z7 {
  box-shadow: 0px 4px 5px -2px rgba(0, 0, 0, 0.2), 0px 7px 10px 1px rgba(0, 0, 0, 0.14), 0px 2px 16px 1px rgba(0, 0, 0, 0.12); }

.mat-elevation-z8 {
  box-shadow: 0px 5px 5px -3px rgba(0, 0, 0, 0.2), 0px 8px 10px 1px rgba(0, 0, 0, 0.14), 0px 3px 14px 2px rgba(0, 0, 0, 0.12); }

.mat-elevation-z9 {
  box-shadow: 0px 5px 6px -3px rgba(0, 0, 0, 0.2), 0px 9px 12px 1px rgba(0, 0, 0, 0.14), 0px 3px 16px 2px rgba(0, 0, 0, 0.12); }

.mat-elevation-z10 {
  box-shadow: 0px 6px 6px -3px rgba(0, 0, 0, 0.2), 0px 10px 14px 1px rgba(0, 0, 0, 0.14), 0px 4px 18px 3px rgba(0, 0, 0, 0.12); }

.mat-elevation-z11 {
  box-shadow: 0px 6px 7px -4px rgba(0, 0, 0, 0.2), 0px 11px 15px 1px rgba(0, 0, 0, 0.14), 0px 4px 20px 3px rgba(0, 0, 0, 0.12); }

.mat-elevation-z12 {
  box-shadow: 0px 7px 8px -4px rgba(0, 0, 0, 0.2), 0px 12px 17px 2px rgba(0, 0, 0, 0.14), 0px 5px 22px 4px rgba(0, 0, 0, 0.12); }

.mat-elevation-z13 {
  box-shadow: 0px 7px 8px -4px rgba(0, 0, 0, 0.2), 0px 13px 19px 2px rgba(0, 0, 0, 0.14), 0px 5px 24px 4px rgba(0, 0, 0, 0.12); }

.mat-elevation-z14 {
  box-shadow: 0px 7px 9px -4px rgba(0, 0, 0, 0.2), 0px 14px 21px 2px rgba(0, 0, 0, 0.14), 0px 5px 26px 4px rgba(0, 0, 0, 0.12); }

.mat-elevation-z15 {
  box-shadow: 0px 8px 9px -5px rgba(0, 0, 0, 0.2), 0px 15px 22px 2px rgba(0, 0, 0, 0.14), 0px 6px 28px 5px rgba(0, 0, 0, 0.12); }

.mat-elevation-z16 {
  box-shadow: 0px 8px 10px -5px rgba(0, 0, 0, 0.2), 0px 16px 24px 2px rgba(0, 0, 0, 0.14), 0px 6px 30px 5px rgba(0, 0, 0, 0.12); }

```

How do I turn this off?

**Comment by willshowell** [comment]
@megamindbrian You are probably indirectly including `mat-core` in each component

**Comment by megamindbrian** [comment]
@willshowell Thanks for the response!  I only included mat-core 1 time in my "layout.scss".  I've added "layout.scss" to angular-cli.json:
```
{
    "apps": [
        {
            "name": "my-app",
            ... main, polyfills, etc
            "styles": [
                "layout.scss"
            ]
        }
    ]
}
```

I've just confirmed layout.scss is not referenced anywhere else in the project, only angular-cli.json.
Here is a screenshot of the inspector, as you can see there are A DOZEN ```<style>``` tags.

![image](https://user-images.githubusercontent.com/25057134/28639032-9336bba6-71fb-11e7-882e-bcb58f17793d.png)
