### ISSUE TITLE
md-radio: animation is triggered without state change 

### ISSUE THREAD

**Issue by Nightapes** [angular/material2#2801]
#### Bug, feature request, or proposal:
   Bug or proposal

#### What is the expected behavior?

 When clicking on a radio with a shorter label, the click animation is triggered and the state is changed or the animation is not triggered. 

#### What is the current behavior?

 When clicking on a radio with short label, the click animation is triggered, but the state is not changed.

#### What are the steps to reproduce?

![radio](https://cloud.githubusercontent.com/assets/15911153/22303821/425bd22a-e335-11e6-92a5-b2c9961e3783.gif)

#### Which versions of Angular, Material, OS, browsers are affected?

Tested with Chrome and https://material.angular.io/components/component/radio

**Comment by jelbourn** [comment]
Probably same cause as #2783
