### ISSUE TITLE
Bug: MdInputContainer dividerColor has no effect

### ISSUE THREAD

**Issue by SwagStormer** [angular/material2#2811]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MdInputContainer should change colors with the dividerColor directive

#### What is the current behavior?
Nothing happens when changing the dividerColor, and clicking on it does nothing

#### What are the steps to reproduce?
The main focus below is in the Username and Password fields
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

Have a custom theme, and use the code below. The example in the docs doesn't work either

<img width="590" alt="screen shot 2017-01-25 at 10 00 13 pm" src="https://cloud.githubusercontent.com/assets/14855325/22320449/b8951bc2-e349-11e6-9334-4c5286bb918f.png">

#### What is the use-case or motivation for changing an existing behavior?
I'm not sure what to say other than it doesn't work at all

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.3.2
AngularMaterial2: 2.0.0-beta.1

#### Is there anything else we should know?
<img width="436" alt="screen shot 2017-01-25 at 9 56 41 pm" src="https://cloud.githubusercontent.com/assets/14855325/22320375/30cedf84-e349-11e6-922c-1e619303cb3c.png">

**Comment by mmalerba** [comment]
Are any of the inputs in your screenshot focused? the dividerColor only affects the color when focused. It seems to be working fine to me

**Comment by SwagStormer** [comment]
@mmalerba The first one is focused. I changed my version from 2.0.0.beta-1 2.0.0.alpha.9-3 and changed the containers to the deprecated md-input and it worked fine. I also tested this on another project and got the same result, meaning it isn't just a weird use case

**Comment by mmalerba** [comment]
It seems to be working for me: http://plnkr.co/edit/42trGBbs8gdShrtmZf8U?p=preview you might have CSS styles on your site that are interfering. your inputs look darker than they naturally would be

**Comment by SwagStormer** [comment]
I've narrowed this down to an issue with custom theming. If you include the css style in the html sheet like you have it works fine, but with custom theming it does not. All other components are functional with the styling sheet being imported with scss that's how I know the import is at least getting through.

**Comment by mmalerba** [comment]
It works for me when using custom themes as described in the guide: https://github.com/angular/material2/blob/master/guides/theming.md
