### ISSUE TITLE
md-select: support md-icon

### ISSUE THREAD

**Issue by ciesielskico** [angular/material2#2814]
#### Bug, feature request, or proposal:
Bug/Feature request

#### What is the expected behavior?
md-select should support md-icons

#### What is the current behavior?
The icon's string representation is printed inside the md-select, instead of the actual icon.

#### What are the steps to reproduce?

http://plnkr.co/edit/JUvYgIAoIexRvW19Fng3?p=preview

1. Open plunkr
2. Select an item from md-select (notice that icons in md-option are displayed)
3. After selecting an item, the icon's string representation is displayed inside md-select, instead of the actual icon.

#### Which versions of Angular, Material, OS, browsers are affected?

angular-cli: 1.0.0-beta.24
node: 6.9.4
os: linux x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.1.1
@angular/compiler-cli: 2.4.3

**Comment by arlowhite** [comment]
I'm on material2 master
`@angular/material@2.0.0-beta.2  (git+https://github.com/angular/material2-builds.git#1a385805bf23db2e5fd95b6f412155bbec190873)`

md-icon works for me
```
<md-select>
 <md-option><md-icon>star</md-icon> my label</md-option>
</md-select>
```

**However, the icon is vertically aligned to the top, not middle.**

ng version

> @angular/cli: 1.0.0
> node: 6.9.1
> os: linux x64
> @angular/animations: 4.0.1
> @angular/common: 4.0.1
> @angular/compiler: 4.0.1
> @angular/core: 4.0.1
> @angular/flex-layout: 2.0.0-rc.1
> @angular/forms: 4.0.1
> @angular/http: 4.0.1
> @angular/material: 2.0.0-beta.2
> @angular/platform-browser: 4.0.1
> @angular/platform-browser-dynamic: 4.0.1
> @angular/router: 4.0.1
> @angular/cli: 1.0.0
> @angular/compiler-cli: 4.0.1
> @angular/language-service: 4.0.1
>

**Comment by skoblenick** [comment]
Fix for the supplied Plunker: http://plnkr.co/edit/fy1PnCCHnZvmnrrW2Eue?p=preview

**Comment by atinybeardedman** [comment]
Looks like the plunker isn't working. Here's a working one that shows the issue. 
@arlowhite the vertical alignment is a simple css fix. If you change the md-icon vertical alignment to text-bottom it looks fine.

[https://plnkr.co/edit/M7rT7n?p=preview](url)

**Comment by sangecz** [comment]
how does it look? is there any workaround to remove md-icon text?

**Comment by willshowell** [comment]
@sangecz see https://github.com/angular/material2/pull/3341 for customizing the trigger value

**Comment by TimoKunze** [comment]
@willshowell So can md-select-trigger be used to display the selected option's icon (md-icon or img)? I gave it a short try, but could not make it work. Maybe the select docs could be extended with a sample how to do this.

**Comment by willshowell** [comment]
@TimoKunze, my suggestion is more suitable for removing the `md-icon` text as @sangecz asked.

That said, if you have some flexibility in how you configure it, this works fine as a workaround for the original issue: http://plnkr.co/edit/7eHeaRGvR87N2MMA32xH?p=preview

**Comment by sangecz** [comment]
I used svgIcon on md-icon and MdIconRegistry to avoid showing md-icon text:
template: 
`<md-icon svgIcon="chat"></md-icon>`
cmp:
```
constructor(iconRegistry: MdIconRegistry, sanitizer: DomSanitizer) {
  iconRegistry.addSvgIcon( 'chat', sanitizer.bypassSecurityTrustResourceUrl('assets/img/chat.svg'))
}
```

but @willshowell's solution looks suitable.

**Comment by jelbourn** [comment]
I believe this issue is obsolete now that `mat-select-trigger` exists
