### ISSUE TITLE
build(sauclabs): access

### ISSUE THREAD

**Issue by Nightapes** [angular/material2#2817]
Should be the access keys in the repro? 
https://github.com/angular/material2/blob/master/.travis.yml#L15
https://github.com/angular/material2/blob/master/.travis.yml#L17

**Comment by DevVersion** [comment]
Right now they are intentionally in the `.travis.yml` to support Sauce & Browserstack for PR's as well.

And yeah we have been thinking about encrypting those more.

**Comment by DevVersion** [comment]
Update, just discovered that encrypted tokens in the `.travis.yml` are not accessible for PRs. I thought that only variables from the Saucelabs Web UI are not available for PRs

Closing this issue now, since we don't have any other option.

**Comment by Nightapes** [comment]
For saucelabs there is a way: https://docs.travis-ci.com/user/jwt. But unfortunately not supported by Browserstack.

**Comment by DevVersion** [comment]
@Nightapes Thanks for the doc. Will look into this later.
