### ISSUE TITLE
Proposal: Allow md-slide-toggle to be aligned start or end

### ISSUE THREAD

**Issue by bsteffl** [angular/material2#2820]
#### Proposal:
Allow md-slide-toggle to be aligned start or end.

#### What is the expected behavior?
To be able to allow the toggle element to come after the label visually.
![image](https://cloud.githubusercontent.com/assets/10760551/22345450/bf72a988-e3c5-11e6-86a4-312a26f8fdef.png)

#### What is the current behavior?
Currently the toggle element only positions on the left of the label.
![image](https://cloud.githubusercontent.com/assets/10760551/22345336/65a1076a-e3c5-11e6-84b4-7510561b2bf9.png)

#### What is the use-case or motivation for changing an existing behavior?
Enhancement to existing component to allow flexibility of display easily.

#### Which versions of Angular, Material, OS, browsers are affected?
Version: 2.0.0-beta.1

**Comment by DevVersion** [comment]
I think that's a pretty good idea. We should just respect the current direction (RTL | LTR). Do you think this is something useful @jelbourn ?

**Comment by jelbourn** [comment]
@DevVersion yeah, it should be the same API / behavior as md-checkbox.
