### ISSUE TITLE
Any plans to include md-content?

### ISSUE THREAD

**Issue by CarlosV89** [angular/material2#2827]
#### Bug, feature request, or proposal:
The reason I'm asking is because I don't see it in the list of things to be implemented and the ones that have. 
https://material.angularjs.org/latest/api/directive/mdContent

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by jelbourn** [comment]
We have no plans for an equivalent to `<md-content>`.

**Comment by sdebionne** [comment]
@jelbourn No plans because there is another (better) way to achieve the same result?
