### ISSUE TITLE
BUG - Sidenav template close handler not working properly

### ISSUE THREAD

**Issue by ArthurianX** [angular/material2#2830]
#### Bug, feature request, or proposal:

I have this piece of code:

```javascript
<md-sidenav #contextSidebarControl mode="over" align="end" class="sidenav contextual">
            <button (click)="contextSidebarControl.close()" class="contextual-close"><i class="fa fa-times" aria-hidden="true"></i></button>
            <contextualSidebar
                    (triggerContextualSidebarOpen)="contextSidebarControl.open()"
                    (triggerContextualSidebarClose)="contextSidebarControl.close()"
            ></contextualSidebar>
        </md-sidenav>
```

Emitting an event to trigger `contextSidebarControl.open()` works, but when triggering the close action the sidebar won't close. I ended up clicking the already present close button from the component which the above html code is from. 

I don't need to say that this is hackish :)

Has someone else encountered this problem ?
Is it a known bug?

#### What is the expected behavior?
`contextSidebarControl.close()` should close the sidebar.

#### What is the current behavior?
`contextSidebarControl.close()` does not close the sidebar.

#### What are the steps to reproduce?
I have no plunker with this.

#### Which versions of Angular, Material, OS, browsers are affected?
- angular `2.2.4`
- material `2.0.0-beta1`

**Comment by DevVersion** [comment]
There isn't much code we can look at. If possible please try to provide a Plunker.

Can you confirm that your `(triggerContextualSidebarClose)` event is dispatched at all?

**Comment by kara** [comment]
@ArthurianX Can you add a plunker so we can look into this?

**Comment by ArthurianX** [comment]
@DevVersion - `triggerContextualSidebarClose` is surely dispatched, at this point it fires a function which runs in the parent component and that one closes the sidebar.

Sorry! I haven't gotten to it yet.

On my codebase it was reproducible every time I tried, and I can't paste that, but I'll try this evening to make a plunker with the same structure.

**Comment by ArthurianX** [comment]
@kara - Ok, I made a plunker right now, I postponed this enough.

Here it is, http://plnkr.co/edit/WpXm2rA54JXsQ6YkNpye?p=preview

**Comment by willshowell** [comment]
@ArthurianX, I don't think you should be bootstrapping your `SidebarComponent` in `PlunkerAppModule`. Removing it from the `bootstrap` array fixed the issue for me

http://plnkr.co/edit/pAGkrpOW0Uc8PWHKJXEj?p=preview

**Comment by ArthurianX** [comment]
I can't test now as I'm on my phone. 

What's the connection between bootstrapping this and the close event not firing?

**Comment by willshowell** [comment]
It isn't clear to me what the connection is, but if you look in this plunkr, I've added a log to see if `triggerContextualSidebarClose.emit()` is being caught by `AppComponent`. It is not.

http://plnkr.co/edit/Ww8cNpvfDccONvBhn9sW?p=preview

**Comment by kara** [comment]
@ArthurianX As @willshowell mentioned, adding the `SidebarComponent` to the bootstrap array separately is causing this problem. Since it should be a child component of the root AppComponent, you only need to bootstrap the AppComponent. Otherwise, the hierarchy won't be set up correctly. Removing SidebarComponent from your bootstrap should fix the issue.
