### ISSUE TITLE
date input when binding to getter and setter property

### ISSUE THREAD

**Issue by niwrA** [angular/material2#2831]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When modelbinding is initialised with a property that is a typescript getter/setter binding to an internal state object, it should take and display the initial value.
`    <md-input (blur)="changeStartDate()" type='date' [(ngModel)]='project.startDate' placeholder="StartDate"></md-input>
`
#### What is the current behavior?
 the initial value is not set on the control. Updating to the property works fine, but initialising a value from it fails. When doing this with a plain Object / non-setter/getter typed object there is no issue. 
EDIT: hmm, there seems to be more going on, as this no longer seems to work now either.

#### What are the steps to reproduce?
Couldn't get plunker to work. 

#### What is the use-case or motivation for changing an existing behavior?
Bug

#### Which versions of Angular, Material, OS, browsers are affected?
material 2.0.0.0.beta.1 angular 2.3.1 Chrome latest on Windows 10

#### Is there anything else we should know?
The same kind of name property binding to a text input works fine. And it worked with dates before I added the wrapping object

**Comment by niwrA** [comment]
I can't figure this out. I don't know if it is angular material or ng-material2 or even the CLI - it changed after I updated angular to 2.3.1 while updating the angular cli. If anyone has any ideas, would be more than welcome!

**Comment by jagrodal** [comment]
Is project.startDate a Date or a string? I guess you the ngModel should be a string ('YYYY-MM-DD').

**Comment by kara** [comment]
@niwrA Can you try again with plunker? There isn't much information for us to use to repro.

**Comment by mmalerba** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
