### ISSUE TITLE
Mention that <!DOCTYPE html> is required in getting started docs

### ISSUE THREAD

**Issue by alexsapps** [angular/material2#2832]
#### Bug, feature request, or proposal:
Mention that page must have `<!DOCTYPE html>` for Material components to render properly as HTML 5. Just a suggestion.
here: https://github.com/angular/material2/blob/master/guides/getting-started.md
and here: https://material.angular.io/guide/getting-started
(not sure why there are two getting started guides)

#### What is the use-case or motivation for changing an existing behavior?
This problem with dialogs is hard to troubleshoot:
https://github.com/angular/material2/issues/2351

In general when something isn't displaying right, DOCTYPE makes for an insidious culprit. You have to wonder if you're including the right CSS, check all your own CSS, and post stackoverflow questions or github issues, or maybe just add your own CSS hacks to patch up the problem before thinking to double check your DOCTYPE.

**Comment by crisbeto** [comment]
I'm not sure that it belongs in the getting started guide, but I was going to log a warning in dev mode, if you're missing it, I just haven't gotten around to it yet. Closing since this is being tracked via #2351.
