### ISSUE TITLE
Cannot transclude md-hint to md input between 2 components

### ISSUE THREAD

**Issue by nicolae536** [angular/material2#2854]
#### Bug, feature request, or proposal:
Is this an angular problem ? or just md-input implementation ?
I created in my project an autocomplete component which has an md-input, and I want to make it work like md-inputs including md-hint, placeholder, suffix, preffix transclusion. The problem is that I cannot transclude the content between two components. 

The first component is this one for exemple
```html
<my-test>
  <md-hint>This is my hint</md-hint>
</my-test>
````
And the test component template looks like this
```html
<div>
      <md-input placeholder="Test">
        <ng-content selector="md-hint"></ng-content>
      </md-input>
</div>
```
#### What is the expected behavior?
I would expect to transclude the content from my-test to md-input

#### What is the current behavior?
The content is not transcluded

#### What are the steps to reproduce?

Here is a plunker which reproduces the problem: https://plnkr.co/edit/ePMygDJa33Ev5H85wpNz?p=preview

#### What is the use-case or motivation for changing an existing behavior?
[I want to have a generic form component. Here is the repository link for the exact case I want
](https://github.com/nicolae536/ng2Tools/blob/master/src/core/components/generic-form/generic-form.html). What I want to do is to create a generic behavior between forms so I can use this component over my applications. Besides material design components I want to add a few more which I think are usefull.

#### Is there anything else we should know?
Package.json libraries versions.
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "^2.0.0-beta.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1"

**Comment by mmalerba** [comment]
`md-input-container` looks for a view child `<md-hint>` in your example there is no view child `<md-input>` (only a content child one). in order to make something like this work you could do:

```html
<my-test>
  <my-hint>This is my hint</my-hint>
</my-test>
```
```html
<md-input-container>
        <input mdInput placeholder="Test">
        <md-hint><ng-content select="my-hint"></ng-content></md-hint>
</md-input-container>
```
