### ISSUE TITLE
mdDialog, arrow keys navigate through buttons

### ISSUE THREAD

**Issue by vipdorian** [angular/material2#2858]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Regarding mdDialog, when it's open, if it has 2 or more buttons (example: Yes, No, Maybe), I should be able to navigate with arrow keys on this buttons.

#### What is the current behavior?
Navigation possible only with TAB.

#### What are the steps to reproduce?
Navigate to https://material.angular.io/components/component/dialog
Try using arrow keys.

#### What is the use-case or motivation for changing an existing behavior?
Using arrow keys is the expected behaviour.
See another plugin using arrowkwys: http://alertifyjs.com/

**Comment by kara** [comment]
For accessibility, the standard is actually only TAB: https://www.w3.org/TR/wai-aria-practices/#dialog_modal.

**Comment by marcysutton** [comment]
I think if you want arrow-key-navigable buttons like that, you should use radio buttons–especially if the answers are mutually exclusive. That form control will give you the user interaction pattern you're looking for.

**Comment by jelbourn** [comment]
This is not something we plan on implementing.
