### ISSUE TITLE
Unsafe value used in a resource URL context when using svgIcon

### ISSUE THREAD

**Issue by apreg** [angular/material2#2860]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Does not throw error.

#### What is the current behavior?
It throws "unsafe value used in a resource URL context"

#### What are the steps to reproduce?
register a svg icon
```
export class AppComponent {

  constructor(mdIconRegistry: MdIconRegistry){
    mdIconRegistry.addSvgIcon('hamburger', 'assets/svg/hamburger.svg');
```
then use it in template
`<md-icon svgIcon="hamburger"></md-icon>`
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?

angular v2.4.5
material v2.0.0-beta.1
windows 10 x64
nodejs v6.9.2

#### Is there anything else we should know?
This way I can avoid the error:
  `constructor(mdIconRegistry: MdIconRegistry, private sanitizer: DomSanitizer ){
    mdIconRegistry.addSvgIcon('hamburger', sanitizer.bypassSecurityTrustResourceUrl('assets/svg/hamburger.svg'));
`

**Comment by DevVersion** [comment]
Yeah you always need to trust your URL's for the `MdIconRegistry`. See this PR https://github.com/angular/material2/pull/1933.

https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes-from-alpha11
