### ISSUE TITLE
hammerjs import error => Cannot find name 'HammerManager'

### ISSUE THREAD

**Issue by crossme** [angular/material2#2863]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
You need to 'import hammers' at @angular2-material/core/gestures/MdGestureConfig.d.ts

#### What is the current behavior?
Error for import.

**Comment by crisbeto** [comment]
What version of Material are you using @crossme?

**Comment by kara** [comment]
@crossme Can you provide some more info about your Material version and what you're trying to do?

**Comment by tinayuangao** [comment]
```Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.```
