### ISSUE TITLE
Md Select - select.html has 'this' mentioned in html

### ISSUE THREAD

**Issue by venkateshwarv** [angular/material2#2865]
#### Bug, feature request, or proposal:

[class.md-floating-placeholder]="this.selected"

Shouldn't it be 'selected' instead of 'this.selected'.

Request: Can we expose the foatingPlaceholder as property like md-input-container?

**Comment by crisbeto** [comment]
I think I removed the `this.selected` at some point, but it shouldn't be an issue anyway. Regarding the `floatingPlaceholder`, there a PR pending for it at https://github.com/angular/material2/pull/2571
