### ISSUE TITLE
Unit tets of snackbar is failing when run "gulp test"

### ISSUE THREAD

**Issue by shootermv** [angular/material2#2866]
#### Bug, feature request, or proposal:
should dismiss automatically after a specified timeout - expected false to be truthy

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by kara** [comment]
@shootermv This is not reproducible without some sort of code snippet or plunker. Please feel free to open a new issue with something we can reproduce.
