### ISSUE TITLE
docs: explain impacts of using types in tsconfig

### ISSUE THREAD

**Issue by DevVersion** [angular/material2#2868]
Our documentation explains how to install `hammerjs` and the associated types.

Link: https://material.angular.io/guide/getting-started

> Those types shouldn't be *necessary* anymore (we have a mock now)

And most important, we should mention that when using `types` in the `tsconfig`, TypeScript wouldn't be able to automatically detect types anymore. 

See https://github.com/angular/material2/issues/2474#issuecomment-276127146

**Comment by szykov** [comment]
Can somebody explain why do we need to specify types in tsconfig? 
By default it automatically includes types and hammerjs type will be included.

**Comment by DevVersion** [comment]
@szykov Exactly, that's why I think we should just say that TypeScript automatically detects the types.

And probably we can also remove that section completely because Material 2 now provides its own minimalist set of Hammer types (which makes `@types/hammerjs` not required)

**Comment by szykov** [comment]
@DevVersion  I just tried to check if slide-toggle works without hammerjs and it did. 
But now it says in a console:
`Could not find HammerJS. Certain Angular Material components may not work correctly.`

That actually why I added hammerjs in a first place.

**Comment by DevVersion** [comment]
Yeah those components need `hammerjs`, but it's **not** necessary to include the `@types/hammerjs` since we have our own now.

**Comment by szykov** [comment]
well, by 'types' you meant 'type definitions', now I got it. thanks 👍

**Comment by DevVersion** [comment]
This seems to be unnecessary now. Especially since we don't depend on the typings anymore.
