### ISSUE TITLE
Theme implementation?

### ISSUE THREAD

**Issue by samio80** [angular/material2#287]
How to change the theme from the dist package if the component styles have fixed css?

**Comment by msegers** [comment]
I think this is a feature which will appear in or right before beta.

**Comment by jelbourn** [comment]
@samio80 The styles are currently written with theming in mind, but we don't have a deployment strategy for theming ready yet. As a workaround in the meantime, you can pull the source directly and customize the theme by modifying `_default-theme.scss` and creating npm packages (via the script `stage-release.sh`). 

Keep in mind that we're still early in the alpha process and, as such, the APIs or behaviors can change between releases.

**Comment by samio80** [comment]
Yes I thought so too thank you for the reply and cheers for the good work!

**Comment by Delagen** [comment]
There is no way to build theme from NPM packages, so I think it must be separated from component and attached manually (may be tunable). So in this state NPM packages are only for demo purposes

**Comment by daniele-zurico** [comment]
Any news about that?

**Comment by devpaulson** [comment]
Any updates on this now?

**Comment by daniele-zurico** [comment]
Look on rc9

**Comment by jainhitesh90** [comment]
Any update?

**Comment by jainhitesh90** [comment]
" As a workaround in the meantime, you can pull the source directly and customize the theme by modifying _default-theme.scss and creating npm packages (via the script stage-release.sh)."

I've updated the _default-theme.scss file, can some 1 pls help me with steps for "creating npm packages (via the script stage-release.sh)." :(

**Comment by jelbourn** [comment]
See the changelog.
