### ISSUE TITLE
Slider does not work in all cases within a *ngFor

### ISSUE THREAD

**Issue by TheCasualObserver** [angular/material2#2871]
#### Bug, feature request, or proposal:

Bug

#### What is the current behavior?

In some cases the slieder does not work when within a *ngFor.
In the code listed below slider 1 and 2 work fine.
Slider 3 however is not responsive in the sense, that clicking with the mouse on the slider does not move it. However in some tests I noticed that the (change) event gets triggered, which always delivers the initial value of the slider.

#### What are the steps to reproduce?

http://plnkr.co/edit/T1l38xGUfX2NDnDrN7cV?p=preview (I find it strange that the Plunker preview shows "Not found")

```
import { Component } from '@angular/core';

@Component({
    selector: 'test-display',
    template: `
    <md-slider></md-slider> Slider 1
    <div class="test" *ngFor="let data of getbar1()">
        <md-slider></md-slider> Slider 2
    </div>
    <div class="test" *ngFor="let data of getbar2()">
        <md-slider></md-slider> Slider 3
    </div>
    `,
})
export class TestCase {
    aa = [{foo: 1}];

    getbar1() : {foo:number}[] {
        return this.aa;
    }
    getbar2() : {foo:number}[] {
        return [{foo: 1}];
    }
}
```

#### Which versions of Angular, Material, OS, browsers are affected?

Windows 8.1, Firefox 51.0 & Internet Explorer 11 & Chrome 56.0

test@0.0.0 F:\dev\test
+-- @angular/common@2.4.5
+-- @angular/compiler@2.4.5
+-- @angular/compiler-cli@2.4.5
+-- @angular/core@2.4.5
+-- @angular/forms@2.4.5
+-- @angular/http@2.4.5
+-- @angular/material@2.0.0-beta.1
+-- @angular/platform-browser@2.4.5
+-- @angular/platform-browser-dynamic@2.4.5
+-- @angular/router@3.4.5
+-- @types/hammerjs@2.0.34
+-- @types/jasmine@2.5.38
+-- @types/node@6.0.62
+-- angular-cli@1.0.0-beta.26
+-- angular2-cookie@1.2.6
+-- hammerjs@2.0.8
+-- typescript@2.0.10

**Comment by mmalerba** [comment]
this is a misuse of `ngFor`. since `getbar2` returns a new array instance each time the slider is constantly getting destroyed and replaced with a new slider

**Comment by TheCasualObserver** [comment]
Thank you for pointing out my mistake.
