### ISSUE TITLE
`Unexpected end of input.` in IE11, progress-bar

### ISSUE THREAD

**Issue by szykov** [angular/material2#2881]
#### Bug, feature request, or proposal:
Bug in IE11

#### What is the expected behavior?
Console without errors

#### What is the current behavior?
Produce this error:
```
XML5602: Unexpected end of input.
Line: 1, Column 252
```

#### What are the steps to reproduce?
You can follow this link by using IE 11 and see console:
https://material.angular.io/components/component/progress-bar

**Comment by crisbeto** [comment]
This seems to be due to the SVG background in buffer mode. Some of the more obvious fixes didn't work.
