### ISSUE TITLE
md-select preselected value

### ISSUE THREAD

**Issue by lynxone67** [angular/material2#2882]
I have following code:

```
<md-select placeholder="Country" (ngModel)]="person.address.country">
      <md-option *ngFor="let krajina of country | async" [value]="krajina.id">
             {{krajina.abbreviation_iso}}
      </md-option>
</md-select>
```

When my form loads it doesn't show the corresponding link of preselected value. I saw more issues with similar question, but none of them solved my problem. Can anyone help, please?

**Comment by web265p3** [comment]
Yep! Same problem :)

**Comment by fxck** [comment]
Provide a plunk reproduction. You are missing `[` at `ngModel`, not sure if that's just a typo. Try putting `*ngIf="(country | async)?.length"` on md-select, it could work as a workaround.




Slightly offtopic but..

> let krajina of country

..makes me cringe.

**Comment by lynxone67** [comment]
`*ngIf="(country | async)?.length" ` did't work for me.

**Comment by web265p3** [comment]
Opps - for me it was just the problem, that I used onPush. With default it works. So in my case it was just [this](https://github.com/angular/material2/issues/2663) issue :)

**Comment by crisbeto** [comment]
I'll close this as a duplicate. There's a pending fix for the `OnPush` issue.
