### ISSUE TITLE
md-select label higher than md-input

### ISSUE THREAD

**Issue by pacoferre** [angular/material2#2884]
#### Bug, feature request, or proposal:

Images taken from material.angular.io website. Left is md-input and right is md-select.
![image](https://cloud.githubusercontent.com/assets/10376690/22509882/1bc444de-e890-11e6-918e-32a8fac9c9e2.png)

Why are the labels in different positions?

#### What is the expected behavior?

Same label position in both components.

#### What is the current behavior?

md-select label is higher than md-input label.

#### What are the steps to reproduce?

Just look at md-input/md-select help sections in material.angular.io

#### What is the use-case or motivation for changing an existing behavior?

User experience is not good.

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.4.4
Angular Material 2.0.0-beta.1
Chrome/IE/Edge

#### Is there anything else we should know?

md-input-container is not allowed with md-select

**Comment by pacoferre** [comment]
Ok, changing

.md-select-placeholder.md-floating-placeholder { top: -17px }
.md-select-value { top 2px }
.md-select-trigger height { 25px }

Also in -17 instead of -22 in:
https://github.com/angular/material2/blob/master/src/lib/select/select-animations.ts#L24
and 
https://github.com/angular/material2/blob/master/src/lib/select/select-animations.ts#L29

Fixes the position of all elements.

**Comment by tom-startsat60** [comment]
.md-select-trigger {margin: 8px 0;} worked for me

**Comment by kara** [comment]
Select and input should definitely align. There is an existing issue tracking this though (https://github.com/angular/material2/issues/2124), so closing this as a dupe.

**Comment by atul221282** [comment]
show stopper at the moment 
![capture](https://cloud.githubusercontent.com/assets/4570393/24829987/0ebd581a-1cbc-11e7-92e5-3571b388e761.PNG)

**Comment by spyter** [comment]
Has there been a fix for this yet?
