### ISSUE TITLE
 md-button-toggle-group & md-radio-group: Doesn't work well together

### ISSUE THREAD

**Issue by abidev** [angular/material2#2885]
**Bug:** md-button-toggle-group & md-radio-group doesn't work as expected if present in the same component

**Current Behaviour:**
If we select a button in button toggle group then selecting radio group automatically unselects the button group and vice versa. It's only occurring for first button toggle group and first radio group in a component.

Please Check the Below Link to reproduce the issue.
**Plunker:** https://plnkr.co/edit/Ff1oQuPg7nlPPYVvXg98?p=preview

**Versions:**

- Angular Material 2.0.0-beta.1 rebar-teacup

**Note:** Correct me if something wrong in the above approach

**Comment by crisbeto** [comment]
This was fixed in https://github.com/angular/material2/pull/2343. You can work around it by setting a name explicitly.
