### ISSUE TITLE
MdInput dimensions are not equal to those in spec

### ISSUE THREAD

**Issue by jakpaw** [angular/material2#2887]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

MdInput height and vertical distances between label, input and underline should be equal to those in spec: https://material.io/guidelines/components/text-fields.html#text-fields-labels

#### What is the current behavior?

MdInput dimensions are font-size dependent, but neither setting font size to 16px nor to 13px (sizes defined in spec for normal and dense input) gives the right dimensions.

#### What are the steps to reproduce?

Check mdInput dimensions at https://material.angular.io/components/component/input

#### What is the use-case or motivation for changing an existing behavior?

To be compliant with spec.

#### Which versions of Angular, Material, OS, browsers are affected?

2.0.0-beta.1

**Comment by jelbourn** [comment]
Should be resolved via #4788
