### ISSUE TITLE
Docs for input should say MdInput not md-input

### ISSUE THREAD

**Issue by alexsapps** [angular/material2#2896]
https://material.angular.io/components/component/input

Examples -> HTML, the example says:

`<input md-input placeholder="First name">`

It should say:

`<input mdInput placeholder="First name">`

Otherwise, it results in this error:

`md-input-container must contain an mdInput directive. Did you forget to add mdInput to the native input or textarea element?`

**Comment by kara** [comment]
@alexapps The material.angular.io docs site is synced to match the latest @angular/material release on NPM, and our latest release still expects the `md-input` selector.  In master, we have updated the selector to use `mdInput`, but it's not currently released.  As soon as beta.2 comes out, we will update the docs site to match.

**Comment by natejgardner** [comment]
Installing from npm today, `mdInput` is required, and the docs aren't up to date
