### ISSUE TITLE
Multiple npm packages on npmjs.com - material2 and @angular/material

### ISSUE THREAD

**Issue by vlodko** [angular/material2#2898]
#### Proposal:

I'm seeing multiple different npm packages on `npmjs.com`:
[material2](https://www.npmjs.com/package/material2),
[@angular/material](https://www.npmjs.com/package/@angular/material)
and [angular2-material](https://www.npmjs.com/~angular2-material) which is a list of component actually.

All of them are pointing to the same github repo: `https://github.com/angular/material2`.

**Is there a possibility to have only one official page for material2 package because it's quite confusing?**
Thanks

**Comment by emoralesb05** [comment]
`angular2-material` was the name the package had before, and anything published in `npm` stays there forever (unless you talk to the `npm` people).

The rebranding and supported packages are `@angular/material`, so just ignore the other ones.

**Comment by DevVersion** [comment]
@emoralesb05 Yeah that's true. Also the NPM package `material2` is not an official one.

**Comment by vlodko** [comment]
@emoralesb05 @DevVersion thanks for clarification.
Can I use `angular2-material` separate packages? Do you have plan to update those?

**Comment by DevVersion** [comment]
@vlodko No those `angular2-material` packages are outdated and all newer versions of Angular Material will be released under `@angular/material`. 

By using tree-shaking you will automatically only include the packages you use in your Angular application.

**Comment by vlodko** [comment]
@DevVersion thanks for reply! Need to add tree-shaking to the project now :)
