### ISSUE TITLE
Example of custom theme does not work in 2.0.0

### ISSUE THREAD

**Issue by farantesrodrigues** [angular/material2#2899]
#### Bug, feature request, or proposal:
Example to define a custom theme imports a file that doesn't exist.
```@import '~@angular/material/core/theming/all-theme';```
https://material.angular.io/guide/theming

#### What is the expected behavior?
A correct example. I'm still figuring out how to work with custom themes in Angular2.

#### What is the current behavior?
<img width="331" alt="screen shot 2017-02-02 at 11 37 02" src="https://cloud.githubusercontent.com/assets/1882468/22546116/f9227da4-e93b-11e6-9692-e605e2df5b43.png">

#### What are the steps to reproduce?
Install latest via npm and there is no theming folder in @angular2-material/core
``` "@angular2-material/core": "^2.0.0-alpha.8-2"```

**Comment by cebor** [comment]
Try: `npm install --save @angular/material`, `@angular2-material/core` does not get updates anymore ...

**Comment by farantesrodrigues** [comment]
Oh, I see. Got the versions mixed up...

**Comment by n2lose** [comment]
does this issue fixed?
