### ISSUE TITLE
slide-toggle: use ripple service instead of temporary ripple

### ISSUE THREAD

**Issue by darrenbrett** [angular/material2#2900]
Right now, using Chrome (Version 56.0.2924.87 (64-bit)), when I click on the md-slide-toggle, the glow effect seems to lock in place, rather than degrade gently to zero. Currently the only way to get rid of the glow on a clicked md-slide-toggle is to click on another element, or click somewhere else on the page. Is this a bug - or the desired effect? Seems like a gentle fade to zero after click would work better. Secondly, is there a way to disable the glow effect?

**Comment by DevVersion** [comment]
Yeah right now the `ripple` shows on thumb focus. That means that it only disappears as soon as you click another element (`blur` event)

Once PR https://github.com/angular/material2/pull/2859 is merged, we are going to use the *actual* ripple service for the `md-slide-toggle`.

With that you will be able to disable the ripple effect and it will only show on `mouseup` / `mousedown`.

**Comment by darrenbrett** [comment]
Okay, thanks.

**Comment by DevVersion** [comment]
@darrenbrett No problem. I will keep that issue open so I can keep track of it. Thanks again for your issue.
