### ISSUE TITLE
(ripple): make sure ripples are on spec - speed & color

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#2901]
button seems faster than is shown here: https://material.io/guidelines/motion/material-motion.html#material-motion-why-does-motion-matter. radio and checkbox explicitly set a faster speed, maybe this should be the default?

color also seems wrong for button ripples, primary/accent colored buttons still have gray ripples

**Comment by shalugin** [comment]
Is it possible to define global ripple speed?

**Comment by DevVersion** [comment]
Hmm not yet, but I'm up to add it. Are there any specific use-cases to argue with?

**Comment by shalugin** [comment]
> Are there any specific use-cases to argue with?

I don't know about these cases.

**Comment by DevVersion** [comment]
I was just wondering if there is any situation where you want to modify the global ripple speed?

**Comment by shalugin** [comment]
Current speed settings is too slow (version 2.0.0-beta.2).
