### ISSUE TITLE
(tests): firefox doesn't fire focus/blur events in tests

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#2903]
Had to exempt firefox from tests added in ##2646 due to this issue. It seems to be a result of firefox not firing the events when it isn't the active window. I was able to reproduce by doing the following:

1. patch #2646
2. remove firefox exemption from tests
3. switch local karma tests to use firefox
4. start tests and click the firefox window to make sure its active as soon as it pops up
5. tests pass
6. start tests again, click away from the firefox window as soon as it pops up to make sure its inactive
7. tests fail

The internet has some mentions of setting a firefox pref, focusmanager.testmode = true as a potential solution for this.

**Comment by crisbeto** [comment]
This seems to be an issue on Chrome as well (at least locally).
