### ISSUE TITLE
Multiple md-card within md-tab losing box shadow style

### ISSUE THREAD

**Issue by JoeMellon** [angular/material2#2913]
When using multiple md-card within an md-tab after the 3rd card the box shadow is no longer applied to the cards. I have tried everything from inline styles to get it to show but it won't. If I move the cards out of the tabs they display as expected. 

Anyone know how I can fix this or why it's occurring?

Thanks!

**Comment by donroyco** [comment]
Can you expand your question with a working example? Here's a Plunker template for adding the behaviour: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview See also other 'bugs' like #2909 to add more info to your question.

**Comment by tinayuangao** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by ektakanojiya** [comment]
currently i am facing the same issue .md-card losing box shadow style when use inside md-tab.
here's plunker template [http://plnkr.co/edit/Ruk1ffObOPFeEpdu2iNa?p=preview](http://plnkr.co/edit/Ruk1ffObOPFeEpdu2iNa?p=preview)
