### ISSUE TITLE
md-menu before/above position issues

### ISSUE THREAD

**Issue by DanPlaza** [angular/material2#2920]
#### Bug, feature request, or proposal:
I've been experiencing some issues with the md-menu position. They were working correctly in alpha, but as soon as I upgraded to material-beta the menus are not displayed on the positions defined with the attributes.

#### What is the expected behavior?
`md-menu`s should be positioned according to the position defined as attribute, i.e. above or before.

#### What is the current behavior?
`md-menu`s are displayed in the correct position when their trigger is shown while the page scrolled to the top, but when they are triggered at a different position of the page, the position of the menu is the default, and, in my case, off the page.

#### What are the steps to reproduce?
Set a menu on the top right of the page with the attribute x-position="before", and trigger it while the page is scrolled to the top and else.

Set another that becomes visible once you scroll down with the attributes x-position="before" y-position="above" and trigger it.

I'll try to provide a plunker in the next few days.

#### What is the use-case or motivation for changing an existing behavior?
The previously working features are not working correctly.

#### Which versions of Angular, Material, OS, browsers are affected?
I'm using angular 2.4.6, angular material 2.0.0-beta.1 with node 6.9.5 on linux mint 18 64-bit, and testing on Google Chrome 56.

#### Is there anything else we should know?
After upgrading to beta I noticed that the position of the menus are not set using css transforms, but with `position: absolute`, but they still have css code to transform the origin right or bottom depending on the position attributes _before_ or _above_, but that css code doesn't affect the position. For some reason if the page is not scrolled to the top the code doesn't correctly calculate the position the menu should have.

I'm posting this because I haven't found this on the issues and it might not be obvious to many people.

Thanks in advance.

**Comment by crisbeto** [comment]
Can you try installing the latest Material? It should be fixed in `master`:

```
npm install https://github.com/angular/material2-builds.git
```

**Comment by DanPlaza** [comment]
I will and let you know. Thanks.

**Comment by DanPlaza** [comment]
It's working. Thank you, @crisbeto

**Comment by crisbeto** [comment]
No problem, thank you for confirming.
