### ISSUE TITLE
(overlay): consider adding MdPopup similar to MdDialog

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#2926]
Many components (select, autocomplete, menu, datepicker) have similar boilerplate related to opening a popup attached to some trigger element. It would be nice to add something like `MdPopup` that would make it easier to do this (like how `MdDialog` does for dialogs).

**Comment by fxck** [comment]
This would be very nice. And I think possibility of other trigger methods should be considered as well.

**Comment by jelbourn** [comment]
Tracking #2691
