### ISSUE TITLE
I can not display correctly when I insert md-input in md-dialog in IOS

### ISSUE THREAD

**Issue by kgtkr** [angular/material2#2929]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Clearly display

#### What is the current behavior?
The display collapses

#### What are the steps to reproduce?
I put md-input in md-dialog and watch it in IOS

#### Which versions of Angular, Material, OS, browsers are affected?
IOS9、Chrome

**Comment by crisbeto** [comment]
Can you post an example? It works fine for me on iOS.

**Comment by tinayuangao** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
