### ISSUE TITLE
Dialog change width after opening?

### ISSUE THREAD

**Issue by seanbotha123** [angular/material2#2930]
**#### Bug, feature request, or proposal:**
Feature request

**#### What is the expected behavior?**
Allow changing of MdDialogConfig in the opened component, through the MdDialogRef.

**#### What is the use-case or motivation for changing an existing behavior?**
We need to open a dialog with a width of 400px, and after a network request resize the dialog to around 800px, to display the retrieved data.

The reason we need the resizing is because when you first open the dialog there are only 2 fields that need to be entered, and this does not warrant a massive 800px dialog.

Having the ability to resize the dialog would be an amazing addition and it would be great to have control over that while the dialog is open.

Not sure if this is possible, but it would be a great feature.

Thanks!

**Comment by crisbeto** [comment]
It's definitely possible to add this, although you can still do something similar by not setting the width through the dialog config, but rather through your own CSS.
