### ISSUE TITLE
Unclear docs example for Dialog component

### ISSUE THREAD

**Issue by jamzi** [angular/material2#2934]
Dialog with a result example in the docs is a little bit unclear in my opinion on how to return the value back to DialogResultExample component. If you open the plunker version, you can nicely see two .html files where it shows you that on close method you pass in the parameter. But in the docs version, there is only html for DialogResultExample component.

I am suggesting that the html tab for docs on this example would be like this:

```html
//dialog-result-example.html
<button md-button (click)="openDialog()">Launch dialog</button>
You chose: {{selectedOption}}

//dialog-result-example-dialog.html
<h1 md-dialog-title>Dialog</h1>
<div md-dialog-content>What would you like to do?</div>
<div md-dialog-actions>
  <button md-button (click)="dialogRef.close('Option 1')">Option 1</button>
  <button md-button (click)="dialogRef.close('Option 2')">Option 2</button>
</div>
```

P.S. also, the title of example is Dailog with a result (notice the typo for Dialog).

Btw, you are doing an amazing work on Angular Material!

**Comment by M-a-c** [comment]
@kara The code to fix this is probably out side of the scope of what the 'Git' touches.
I've looked everywhere this feature is in there.. (Might not be 'good for community contribution)

@DevVersion You seem to do the tooling, I think these issues are related to that. I would love to help but really cannot find the code that generates these issues.

See :
https://github.com/angular/material2/blob/f526c9de8725496b04743a326c47f6fcc35b54e2/src/examples/example-module.ts#L111
https://github.com/angular/material2/blob/master/src/examples/example-data.ts#L27
The files are supposed to be injected into the md-tab-group inside the docs-example-viewer-source but they're not ¯\_(ツ)_/¯.
Would gladly try and fix this if I could find out where exactly where the tabs for examples are generated
https://material.angular.io/components/component/dialog --> examples  --> (view source)
Notice: html ts css  but no additional html file.

These issues are related to #3002 but that is also missing additional files list in its definition in example-module.ts

**Comment by jelbourn** [comment]
Tracking via https://github.com/angular/material.angular.io/issues/165

**Comment by coocoorhin** [comment]
great job! i have been working on the issue for a very long time when i was following the doc. your solution magically made it work!!! thanks
