### ISSUE TITLE
MdGridList: gutterSize breakpoints support

### ISSUE THREAD

**Issue by xban1x** [angular/material2#2938]
#### Bug, feature request, or proposal:

Feature Request

#### What is the expected behavior?

To, have some kind of support to specify gutterSize based on FlexLayout breakpoints.

#### What is the current behavior?

Currently we have fixed gutterSize for all breakpoints. Well there is no breakpoints defined currently.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?

Better responsivness.

#### Which versions of Angular, Material, OS, browsers are affected?

All

**Comment by kara** [comment]
We have an existing TODO for better responsive sizing support in grid-list. This is something we definitely want to improve on. See https://github.com/angular/material2/issues/1072 for tracking.
