### ISSUE TITLE
MdDialog: Unable to resolve NgFactory for Entry Components of Lazy Loaded components

### ISSUE THREAD

**Issue by Toxicable** [angular/material2#2946]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Able to use MdDialog on Lazy Loaded Modules

#### What is the current behavior?
Angular throws an Error when you use MdDialog in a Lazy Loaded Module with Entry Components

#### What are the steps to reproduce?
https://plnkr.co/edit/SkB3HyUcamg1eu6PUcHp?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Angular Version: 2.4.6
Angular Material Version: 2.0.0-beta.1

**Comment by ciesielskico** [comment]
Dup of https://github.com/angular/material2/issues/1765 https://github.com/angular/material2/issues/2517

**Comment by Toxicable** [comment]
@ciesielskico my mistake, my search skills must be failing me, thanks for pointing that out.
