### ISSUE TITLE
Scroll is broken on angular.material.io

### ISSUE THREAD

**Issue by patouche7519** [angular/material2#2957]
### Bug, feature request, or proposal:
Bug : on iPhone 7 with the latest iOS and Safari version. Scroll is inactive and the page is cut. It appears only on the components section.

#### What is the expected behavior?
Can scroll and see all the page view 

#### What is the current behavior?
You can the img attached. The view is partial.
![img_2968](https://cloud.githubusercontent.com/assets/11588954/22671583/59ea4144-eccf-11e6-8c98-18c1df4c00cf.PNG)
![img_2967](https://cloud.githubusercontent.com/assets/11588954/22671656/b4d69de6-eccf-11e6-87dd-be0c0fdac527.PNG)

#### What are the steps to reproduce?
Go to components section on the website with an iPhone.
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by DevVersion** [comment]
Just looked at it and tested the docs locally on an iPhone. 

It looks like @andrewseguin solved this issue with https://github.com/angular/material.angular.io/pull/82 and it just needs to be deployed.

**Comment by patouche7519** [comment]
Thanks for your quick answer. I had not seen the material.angular.io repo.
And thanks to the whole team for the amazing work you do.
