### ISSUE TITLE
md-menu multilevelitems 

### ISSUE THREAD

**Issue by Sridhar-Narasimhan** [angular/material2#2961]
#### What is the current behavior?
`<md-menu>` having support for `single level menu item`. I have a scenario which needs `multi-level item` navigation.

```
<button md-button [mdMenuTriggerFor]="menu">Menu</button>
<md-menu #menu="mdMenu">
  <button md-menu-item>Item 1</button>
  <button md-menu-item>Item 2</button>
</md-menu>
```
`Item 1--> item 11` like behavior.

Is there anyway to achieve this.?

**Comment by kara** [comment]
@Sridhar-Narasimhan Having multi-level menus like Material 1 is definitely on our TODO, but no one is working on it quite yet. I'll keep this issue open to track when it gets in.

**Comment by counsellorben** [comment]
I have submitted https://github.com/angular/material2/pull/3259 addressing this issue. This PR needs review.

**Comment by monsteradurm** [comment]
any change of an update to this feature soon?

**Comment by serdardemir** [comment]
Is there any movement on this?

**Comment by patrikx3** [comment]
i think it is not gonna happen. i change my setup, instead like office toolbar. menu is too old. multi level. new frontend ☺️

**Comment by patrikx3** [comment]
collapse, popup, toolbar, etc

**Comment by alexzuza** [comment]
Check this https://plnkr.co/edit/KssNGRhyLRbRzEN59P4C?p=preview

**Comment by jelbourn** [comment]
Tracked via #1429
