### ISSUE TITLE
mdTooltip with long messages show only part of it by 2 element next to each other in IE

### ISSUE THREAD

**Issue by chandra9990** [angular/material2#2964]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tooltip show completely in IE

#### What is the current behavior?
tolltip only show part of it in IE

#### What are the steps to reproduce?
in IE:
- create 2 buttons next to each other
- put tooltip with long messages to each of this buttons
- hover between this 2 buttons
- tooltip will only show part of it

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://plnkr.co/edit/9FWitPZdQqxujVWXAZD5?p=preview

#### What is the use-case or motivation for changing an existing behavior?
to improve md-tooltip performance in IE

#### Which versions of Angular, Material, OS, browsers are affected?
master

#### Is there anything else we should know?
screenshot:
![portion oftooltip](https://cloud.githubusercontent.com/assets/16048033/22697640/6ad3f198-ed52-11e6-999d-eab9302080cd.JPG)

**Comment by tmakin** [comment]
This issue goes away if you add the web-animations polyfill as described in #3605.

I found some useful tips on how to install it here:
https://stackoverflow.com/questions/38836532/how-to-add-web-animations-api-polyfill-to-an-angular-2-project-created-with-angu
