### ISSUE TITLE
Input component does not have a 'X' reset button in Chrome browser

### ISSUE THREAD

**Issue by ksmirnoff** [angular/material2#2966]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by tinayuangao** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
