### ISSUE TITLE
Feature request: add color attribute to md-slider

### ISSUE THREAD

**Issue by Mufasa** [angular/material2#2968]
#### Bug, feature request, or proposal:
It would be nice to have the option to set the slider bubble color to one of primary, accent or warn. Similar to the way we can do this for buttons.

#### What is the expected behavior?
e.g. <md-slider color="primary"> should set the sliders bubble color to the themes primary color. 

#### What is the current behavior?
I believe it currently always uses the themes accent color for the bubble.

#### What are the steps to reproduce?
N/A

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
N/A

#### What is the use-case or motivation for changing an existing behavior?
My customer wants this change in color - so this is a customer driven requirement.

#### Which versions of Angular, Material, OS, browsers are affected?
All

#### Is there anything else we should know?
No

**Comment by DevVersion** [comment]
I think this can depend on  https://github.com/angular/material2/issues/2965 because I'm planning on creating a new directive for the color classes.
