### ISSUE TITLE
Instructions Bug: How 'bout a couple more details

### ISSUE THREAD

**Issue by largeDachshund** [angular/material2#297]
* **Do you want to request a *feature* or report a *bug*?**
The installation instructions lack specificity.  Could we please just add some lines to explain what installing the core module entails? Thanks,

I can't make out how to install the "core module" from this:
# The core module is required as a peerDependency for other components
npm install --save @angular2-material/core @angular2-material/checkbox

Additionally, and this might be a consequence of not properly installing line "#", npm returns an "Unrecognized token in source text" error.

 **What is the current behavior?**
Angular2-material is not installed

* **If the current behavior is a bug,
Follow the instructions on ReadMe.md

* **What is the expected behavior?**
Angular2-material checkbox module is installed.

* **What is the motivation / use case for changing the behavior?**
I can't install Angular2-material, but I would love to try it out in my project!

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Angular2.0.0.beta-14, Chrome, Windows 7
Did this work in previous versions of Angular / Material? N/A

I heard about this project on Adventures in Angular and I'd love to use your project.  Thanks!!

**Comment by jelbourn** [comment]
`npm install --save @angular2-material/core` works fine when I try it. 

What version of  `node` / `npm` are you using?

**Comment by largeDachshund** [comment]
I'm using npm: 3.8.6 and node: 5.10.1

@jelbourn this is what I get, when I put in the same line you reference:
![image](https://cloud.githubusercontent.com/assets/7054672/14477011/130724e6-00c0-11e6-93bf-354088fec3f7.png)

**Comment by jelbourn** [comment]
@largeDachshund I've successfully installed the package on Ubuntu, OSX, and Windows 10 with the same versions of node and npm. I suspect there's some issue with your environment. I'm closing this issue now, feel free to re-open it if you have more information about some problem with the package itself.

**Comment by largeDachshund** [comment]
@jelbourn, thanks for your response.  I guess I ran into a syntax issue with Windows PowerShell.  If I do your command from an administrator's command prompt, I get a successful implementation.  Thanks.  Looking forward to using this library!

**Comment by esinek** [comment]
I had the same issue with PS (run as Administrator) on Win7. Switched over to cmd and it worked fine.

**Comment by magigedaniel** [comment]
Same to me, wasted the whole  3 hours working on **npm i -g @microsoft/generator-sharepoint**
till when I move to cmd and run as  Administrator.... It worked well
