### ISSUE TITLE
Feature request: md-slider placeholder attribute

### ISSUE THREAD

**Issue by Mufasa** [angular/material2#2971]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I would like to be able to specify a placeholder attribute for the md-slider component which should be displayed just above the slider (similar to the way a placeholder is displayed on an md-input component). When the md-slider receives focus then this placeholder should animate upwards while reducing its font size - again similar to the way the placeholder attribute behaves on the md-input component.

#### What is the current behavior?
Currently this component just displays a slider with a draggable bubble. I have to add my own component above it (e.g. a <label> component) to indicate to the user what this slider represents and I also have to animate the focus/blur behaviour myself in order to get it to behave in a consistent manner to the other components on my form.

#### What are the steps to reproduce?
Just add an md-slider to your form.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Current behaviour can be observed here:
https://material.angular.io/components/component/slider

#### What is the use-case or motivation for changing an existing behavior?
To make the md-slider behave in a consistent and more integrated manner to the other material components I use in a form (e.g. md-input, md-select).

#### Which versions of Angular, Material, OS, browsers are affected?
All

#### Is there anything else we should know?
No

**Comment by e-cloud** [comment]
for now, 
> Currently this component just displays a slider with a draggable bubble.
there is no draggable bubble.

**Comment by mmalerba** [comment]
Floating labels for sliders are not somethnig that's currently part of the material spec: https://material.io/guidelines/components/sliders.html
