### ISSUE TITLE
md-select : onSelect emitted before ngModel updated

### ISSUE THREAD

**Issue by nadavten** [angular/material2#2972]
beta-1 BUG:
onSelected is emitted before the model (ngModel) updated , not showing the current state of the model.

**Comment by nadavten** [comment]
i want to update my model property and update some other model properties
depending on that model. i didnt know there 'ngModelChanged' in md-select.
and if there is it makes me wonder why there is 'onSelect' ?

**Comment by fxck** [comment]
`ngModelChanged` is simply a part of @angular/forms intergration. `onSelect` is there if you need to use md-select without @angular/forms.

**Comment by kara** [comment]
As @fxck mentioned, `ngModelChange` is part of the Angular core FormsModule. Select just integrates with it. You can use `onSelect` if you aren't using one of the forms modules, but they aren't intended to be used together in this way. As there is already a recommended way to get your use case working, I'm going to close this.
