### ISSUE TITLE
Compatibility to angular 2.4.2

### ISSUE THREAD

**Issue by nottinhill** [angular/material2#2975]
When will this be compatible to 2.4.2?

I am getting:
```

├── UNMET PEER DEPENDENCY @angular/common@^2.2.0
├── UNMET PEER DEPENDENCY @angular/core@^2.2.0
├── UNMET PEER DEPENDENCY @angular/http@^2.2.0
└── @angular/material@2.0.0-beta.1  (git+https://github.com/angular/material2-builds.git#b248eb0a359908972c24333e6d565c4fec1c9e0f)

npm WARN @angular/material@2.0.0-beta.1 requires a peer of @angular/core@^2.2.0 but none was installed.
npm WARN @angular/material@2.0.0-beta.1 requires a peer of @angular/common@^2.2.0 but none was installed.
npm WARN @angular/material@2.0.0-beta.1 requires a peer of @angular/http@^2.2.0 but none was installed.
```

**Comment by d3viant0ne** [comment]
@nottinhill - material2 is compatible with 2.4.x right now, the peer dep. warnings can be ignored.

You could flip the material2 project dependencies to 2.4.6 right now and everything will still work. 

There are quite a few changes between angular 2.2.x and 2.4.6 / 4.x-beta that need to be accounted for before the material2 team would bump the angular version in the published package but there is no reason why you can't run material2 beta.1 with angular 2.4.6.

**Comment by nottinhill** [comment]
Thanks for is, unfortunately I get typings problems related to this. Any idea on this issue? 

```
[default] Checking started in a separate process...
[default] /Users/tyrion/devel/saveup-policy-front/front/node_modules/@types/node/index.d.ts:85:13
    Cannot redeclare block-scoped variable 'module'.
[default] /Users/tyrion/devel/saveup-policy-front/front/src/app/saveup-common/node_modules/@angular/material/typings.d.ts:1:15
    Cannot redeclare block-scoped variable 'module'.
[default] Checking finished with 2 errors
```

**Comment by d3viant0ne** [comment]
Use the version 6 node types

**Comment by nottinhill** [comment]
Thanks a lot! Turns out root cause was a second node_modules folder in my team's git submodule.

**Comment by alxhotel** [comment]
@d3viant0ne does that mean we can run `material2` with `angular 4.0.0.rc-1` even though there are `UNMET PEER DEPENDENCY` ?
