### ISSUE TITLE
snackbar action button styling when no other md-button is used on the page 

### ISSUE THREAD

**Issue by fxck** [angular/material2#2979]
this happens(http://plnkr.co/edit/0x5guGIc5ofmxDyCJ7Sm?p=preview) when there are no `md-button`s used on the page

![image](https://cloud.githubusercontent.com/assets/1303561/22728495/8ad35d62-edde-11e6-8b68-1d23e84a139a.png)

when you actually use md-button on the page(http://plnkr.co/edit/oOsUEcDjIkNIi9REGxvA?p=preview), it's fine

![image](https://cloud.githubusercontent.com/assets/1303561/22728518/a9938060-edde-11e6-8179-e6a0471e7348.png)

@crisbeto maybe?

**Comment by crisbeto** [comment]
Seems weird, will look into it.
