### ISSUE TITLE
md-option by Image

### ISSUE THREAD

**Issue by Antonystefano** [angular/material2#2982]
`<md-select>
      <md-option *ngFor="let Disp of DisplayList ">
             <img " src="{{Disp.src}} ">
      </md-option>
 </md-select>`

How can I make md-select by images?
Is it possible?

**Comment by fxck** [comment]
what you posted would work, but only in the actual selection, not in the selected value.. and there's already an issue for that

**Comment by kara** [comment]
Closing as a dupte of #2275
