### ISSUE TITLE
Ripple occuring on whole screen instead of it being constrained on clicked element

### ISSUE THREAD

**Issue by CarlosV89** [angular/material2#2986]
#### Bug, feature request, or proposal:
Ripple occuring on body instead of it being constrained on clicked element

#### What is the expected behavior?
Ripple should occur on clicked element.

#### What are the steps to reproduce?
Clone: https://github.com/AngularClass/angular2-webpack-starter
Add pug support through pug-loader

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Pretty extensive App, I dont think I'll be able to reproduce it on a Plunker, perhaps going the same way on that webpack starter, I created a module and inside it a component that has a child-component that has a child-component, doesnt matter to which element I add the md-rippling it ripples on whole container of component that it is calling it currently.

**Comment by kara** [comment]
@CarlosV89 It sounds like your project might not have our core CSS.  Did you add the core styles?  Worth noting that this will be hard for us to look into if there is no repro case.

**Comment by CarlosV89** [comment]
I did have the Core CSS! What I did not know, was that the element had to be relatively positioned for it to work. All I did was add relative position to it and it started working, so I'm going to go ahead and close this one, sorry for the troubles.
