### ISSUE TITLE
Use method calls on click in material2 tabs and tab groups 

### ISSUE THREAD

**Issue by nottinhill** [angular/material2#2995]
Question (not an issue): In Bootstrap tabs we have this in our code: 

```
<ul class="nav nav-tabs">
    <li class="active"><a>Start</a></li>
    <li><a (click)="viewmode.setMode1()">mode1</a></li>
    <li><a (click)="viewmode.setMode2()">mode2</a></li>
</ul>
```

Now this is calling a utterly complicated hack where routing is accomplished with tampering URLs and parameters that I do not dare to touch. There is not much angularic about that code and I dont have time to change it. So I want to let the current strange routing in place, and need to trigger it with method calls from my tabs. Is this possible with material2 tabs?

e.g.: 

```
 <md-tab-group>
      <md-tab (click)="viewmode.setMode1()" label="mode1">
        <h1>Some tab content</h1>
        <p>...</p>
      </md-tab>
 ....
```

**Comment by andrewseguin** [comment]
Sounds like you want to look at the nav bar

```
<nav md-tab-nav-bar>
  <a md-tab-link
     *ngFor="let link of navLinks"
     [routerLink]="link"
     routerLinkActive #rla="routerLinkActive"
     [active]="rla.isActive">
    {{tabLink.label}}
  </a>
</nav>
```

See the bottom section of https://material.angular.io/components/component/tabs

**Comment by adamdport** [comment]
For those considering the md-tab-nav-bar, be sure to check out [2177](https://github.com/angular/material2/issues/2177) first. It wraps on mobile and looks terrible today.

@andrewseguin is there a way to add click handlers to md-tabs like OP asked so I can make it work until the nav bar gets fixed?

**Comment by hugo-martinez-chamonica** [comment]
I am trying to add pagination for md-tab-nav-bar  but its not easy, of course I don`t have so much experience on css and no matter pagination is working the result looks awful when you try to display on responsive environment. There is any suggestion on how to use router.navigate for tabs

**Comment by divyameher** [comment]
@andrewseguin In the code snippet that you have provided you are using  [active]="isActive" but **isActive** property should be independent to each and every **tab-link** right? On click on every tab how to make that clicked/ selected tab as active so that it shows underline?
Any help appreciated.
Thanks

**Comment by willshowell** [comment]
@divyameher yes that was probably implied. One way would be to do it like this,

```html
<nav md-tab-nav-bar>
  <a md-tab-link
     *ngFor="let link of navLinks; let i=index"
     [active]="activeLinkIndex === i">
    {{link.label}}
  </a>
</nav>
```

**Comment by divyameher** [comment]
@willshowell so from my understanding in the above code we will be setting **activeLinkIndex** on every Click event of tabs right?

**Comment by willshowell** [comment]
@divyameher it would be up to your component class to keep `activeLinkIndex` updated. If you're having the same problem as the original issue, yes, you should modify it in a `click` event handler.
