### ISSUE TITLE
md-checkbox inside form tag get this error: "If ngModel is used within a form tag, either the name attribute must be set" 

### ISSUE THREAD

**Issue by marciomsm** [angular/material2#2996]
When I use md-checkbox inside form tag with ngModel I get this error "If ngModel is used within a form tag, either the name attribute must be set". How can I fix this problem? Could anybody help me please?

**Comment by kara** [comment]
It sounds like you didn't set the name attribute. This is a requirement of the Angular core `FormsModule` (which contains the `ngModel` directive).  See example plunker here: http://plnkr.co/edit/X4mckCDOikBBsQHRnnMo?p=preview.

As this is expected, closing.

**Comment by marciomsm** [comment]
Hi @kara thank you for your help!
