### ISSUE TITLE
Input 'date' type can't work in Safari, Firefox

### ISSUE THREAD

**Issue by vivian7169** [angular/material2#2998]
in 'md-input-container':

example:
input md-input required type="date" placeholder="Start Date" name="startDate"

Only can work in Chrome...

**Comment by emoralesb05** [comment]
This is an `html5` issue with the native input. Safari and Firefox dont support it.

http://caniuse.com/#feat=input-datetime

**Comment by crisbeto** [comment]
This is a browser issue.
