### ISSUE TITLE
Misaligned icon in nav-list

### ISSUE THREAD

**Issue by AsherFoster** [angular/material2#2999]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-icon should be vertically centered relative to list item text

#### What is the current behavior?
md-icon is misaligned

#### What are the steps to reproduce?
```
md-nav-list
  md-list-item
    md-icon[md-list-avatar]
    p[md-line]
```
http://plnkr.co/edit/qAVB6mOYNf4p8yxtRSQX?p=preview
![Screenshot](https://cloud.githubusercontent.com/assets/11432528/22768820/65fb38d2-eee9-11e6-8ff3-f7c979946d31.png)

#### What is the use-case or motivation for changing an existing behavior?
Devs shouldn't have to modify CSS to achieve what should be the default behaviour of this list

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-beta.1. Tested on Chrome 56.

#### Is there anything else we should know?
Commenting out the height: 40px line in devtools seemed to resolve the problem, but this may break alignment for multiline items

**Comment by doender** [comment]
I used `<md-icon md-list-icon></md-icon>` instead of `md-list-avatar`, which seems to work.
I think the documentation is off here.

**Comment by ocarreterom** [comment]
https://github.com/angular/material2/issues/2650

**Comment by kara** [comment]
`md-list-icon` is intended to be used with icons, while `md-list-avatar` is really intended for image tags. This is really unclear in the documentation, though, so I've created this PR to fix that.
