### ISSUE TITLE
md-sidenav is open even when opened="false"

### ISSUE THREAD

**Issue by rahulbats** [angular/material2#300]
i used the following code for side nav
` <md-sidenav #start mode="side" opened="false">`

but the sidenav is still open instead of closed.

**Comment by jelbourn** [comment]
@rahulbats Looks like your code snippet is missing.

**Comment by rahulbats** [comment]
sorry i forgot to add the code tags around. I have updated the comment above.

**Comment by rahulbats** [comment]
the solution to this is using it like angular 2 dom property
` <md-sidenav #start mode="side" [opened]="false">`
instead of 
` <md-sidenav #start mode="side" opened="false">`

If this is intentional the README is misleading 
https://github.com/angular/material2/tree/master/src/components/sidenav#bound-properties
