### ISSUE TITLE
Failed to open example source code in Plunker on documentation website

### ISSUE THREAD

**Issue by thanhpd** [angular/material2#3000]
#### Bug, feature request, or proposal:
Bug: On Windows 10 with Chrome 56/Firefox 51/IE 11, when click on Edit in Plunker button the Plunker page popup is not displayed

#### What is the expected behavior?
The page open a new window in Plunker to view/edit source code

#### What is the current behavior?
Nothing happened when click on Edit in Plunker button. Dev tool console in Chrome throw errors that can be seen in this screen (Popups option of Chrome was set to Allow), there are no errors in Dev Tool in other browsers:
![image](https://cloud.githubusercontent.com/assets/6737911/22771917/508619ee-eecc-11e6-9759-bf6bb0777c0a.png)

#### What are the steps to reproduce?
Click Edit in Plunker button in Overview/Examples tab of any component

#### Which versions of Angular, Material, OS, browsers are affected?
OS: Windows 10, Windows 8.1
Browser: Chrome 56, Firefox dev 53/Firefox 51, IE 11

#### Is there anything else we should know?
- This seems to be a new issue as I was able to open source code in Plunker with older version of Chrome/Firefox a few weeks ago
- Edit in Plunker option did work in Edge 14

**Comment by kara** [comment]
@thanhpd  This was [fixed in the material.angular.io repo](https://github.com/angular/material.angular.io/pull/93) last week, but we haven't yet pushed out a new version of the docs site. It should go out with our next beta release (soon!).
