### ISSUE TITLE
using the md-button keeps the remains of unknown hover effect

### ISSUE THREAD

**Issue by yubeen** [angular/material2#3003]
I had a problem while studying Matelial 2.

using the md-button keeps the remains of unknown hover effect

Using the buttonsA(md-button), the alert(md-card) was executed.

The md-button implemented in the executed alert has a gray hover effect when no action is taken.

Also,When this alert is closed, The gray hover overlaps with the button A.

The generated hover disappears when you click anywhere

It was thought that the cause of the hover was related to the ripple.

But setting up ripple did not solve the problem.

I am curious as to how to solve this problem.

I using macOS(sierra), Angular2 material

**Comment by fxck** [comment]
can you provide a plunk demonstrating your problem?

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
