### ISSUE TITLE
md-select not working with object

### ISSUE THREAD

**Issue by EddyNll** [angular/material2#3004]
#### Bug, feature request, or proposal:
Im using multiple md-select on a page. Some work and others don't. The ones containing an object don't work. When using a normal select they all work.

#### Strange behaviour
The id property of md-option and aria-owns property of md-select keeps increasing unlimited.
This also makes the option dialog flicker.

#### Examples
Example of non working md-select
```
<md-select placeholder="Related definition" [(ngModel)]="field.relatedDefinition" #definition="ngModel">
    <md-option *ngFor="let definition of definitions" [value]="definition._id">
        {{definition.name}}
    </md-option>
</md-select>
```

Working select 
```
<select [(ngModel)]="field.relatedDefinition" #definition="ngModel">
    <option *ngFor="let definition of definitions" [value]="definition._id">
        {{definition.name}}
    </option>
</select>
```

**Comment by kara** [comment]
@EddyNll Can you add a plunker repro?  Objects are working on my end as long as the reference is the same.

**Comment by EddyNll** [comment]
@kara My bad, list of Objects got updated because of an observable. Works fine.
