### ISSUE TITLE
Does not setup import angular-material.css to Material 2?

### ISSUE THREAD

**Issue by marciomsm** [angular/material2#3006]
Using this setup "https://material.angular.io/guide/getting-started" to Angular 2 we don't have the angular-material.css imported like this http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.css?

Do I need to import it manually in my index.html?

Thanks.

**Comment by fxck** [comment]
Issues are for bugs, feature requests or proposals, use gitter for questions.

You need to do exactly what is described in the guide - https://material.angular.io/guide/theming

**Comment by marciomsm** [comment]
I wrote here because it can be a bug.

I did all steps that is described on this guide (https://material.angular.io/guide/getting-started), but I cannot find this file http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.css imported. I know that Material has a reset css file, but I cannot see it imported.

**Comment by fxck** [comment]
There is not a single mention of any "http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.css" in that guide, and the [theming guide](https://material.angular.io/guide/theming) is pretty clear about what you should do if you want to use the pre-built theme

![image](https://cloud.githubusercontent.com/assets/1303561/22783368/c6845526-eecb-11e6-974b-2655d7c84891.png)

Perhaps [this](http://www.readingbear.org/) could be of help?

**Comment by marciomsm** [comment]
@fxck I am searching help from serious people. I am not playing here. If you haven't anything to do, go search.

Thank you. I don't need more for your help.

**Comment by f1xpl** [comment]
Same issue for me. I tried to link prebuilt css to index.html file, import it to my main styles.css file, added it to .angular-cli.json but nothing works. I followed the guide but nothing works at all.

**Comment by willshowell** [comment]
@f1xpl can you link to a minimum repo that shows what you've tried?

**Comment by talentedandrew** [comment]
I had a similar issue where I had included the stylesheet in my index file but it was not working.I did this by 
`<link href="../node_modules/@angular/material/prebuilt-themes/indigo-pink.css" `rel="stylesheet">`

But after changing the location of this file to my css folder i.e copying and pasting this file to my css folder and changing the index file like this
 `<link href="/css/indigo-pink.css" rel="stylesheet">`
It started working.
Hope if anyone else having this issue will resolve it.
