### ISSUE TITLE
Slider change event not firing

### ISSUE THREAD

**Issue by robianmcd** [angular/material2#3008]
#### What is the expected behavior?
A slider's `change` event is fired as your drag the slider
A slider's `change` event is fired when you use the arrow keys to manipulate it's value

#### What is the current behavior?
A slider's `change`  event is only fired if you drag a slider with your mouse and release the mouse button.

#### What are the steps to reproduce?
In the following plunkr drag the slider with your mouse and notice that the value binding only updates when you release the slider

Plunker template: https://plnkr.co/edit/MWdB3bsOoNcmslvvyGCP?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I am trying to use a slider to fade out an audio signal so I need a steady stream of change events as it is being dragged.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.7
Material 2.0.0-beta-1

**Comment by DevVersion** [comment]
That's by design. The `change` event only fires on release (similar as for native ranges).

We have added an `input` event that fires when moving the thumb. See SHA https://github.com/angular/material2/commit/99963c4fd182b490241e4b25f08e948020d7ced8

**Comment by robianmcd** [comment]
great I'll try to input event out when it is released. @DevVersion I think the arrow keys not triggering the event is a bug though

**Comment by robianmcd** [comment]
I did provide a plunker. Click the slider and then press left or right and notice that the binding does not update

**Comment by DevVersion** [comment]
@robianmcd I see. Just didn't look like a Plunker because you left the `Plunker template` before :)

**Comment by DevVersion** [comment]
Just ran the Plunker against `master`. It looks like this has been solved: https://plnkr.co/edit/oK9LoHHVFiYWbUCOlBwz?p=preview

**Comment by robianmcd** [comment]
ok great
