### ISSUE TITLE
[feature] Code in Javascript

### ISSUE THREAD

**Issue by darkyndy** [angular/material2#301]
* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
none

* **What is the expected behavior?**
Code should be available in Javascript

* **What is the motivation / use case for changing the behavior?**
I will not use typescript for Angular2

* **Other information**
It will be nice to have Angular Material available in plain Javascript.

**Comment by nesukun** [comment]
You don't need to use typescript at all to use angular 2 material. The published packages contain already transpiled code.[http://i.imgur.com/V9XZJJw.png](http://i.imgur.com/V9XZJJw.png)

**Comment by jelbourn** [comment]
The should indeed work with JS already, but you do need a module loader that understands CommonJS modules (at this stage of the alpha, at least).
