### ISSUE TITLE
md-input

### ISSUE THREAD

**Issue by AyzPat** [angular/material2#3027]
using an input tag under the md-container but the color-pallete effect is not working..

` <md-input-container style="width: 100%;">
  <input type="password" md-input placeholder="password">
 </md-input-container`

in module.ts i have imported:--

` MaterialModule.forRoot(),`

the animation works but the color scheme is not working ..

**Comment by fxck** [comment]
create a plunk demonstrating your problem

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. A plunker would help in this case.
