### ISSUE TITLE
Textarea element using md-input when binding model has initial state as dirty in IE

### ISSUE THREAD

**Issue by thanhpd** [angular/material2#3029]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Textarea element using md-input when binding model has initial state as pristine in IE

#### What is the current behavior?
Textarea element using md-input when binding model has initial state as dirty in IE

#### What are the steps to reproduce?
Using md-input on textarea element and bind model into it.

Plunker example: https://plnkr.co/edit/SQ3o6X19M6isDB3ShFSK?p=preview
Inspect Address textarea in browser development tool. `md-input-container` element has `ng-pristine` class in Chrome/Firefox/Edge while it has `ng-dirty` class in IE

#### Which versions of Angular, Material, OS, browsers are affected?
Material: 2.0.0-beta1
Browser: IE11

**Comment by mmalerba** [comment]
This looks like an angular forms issue since the same thing happens with a plain textarea not inside a md-input-container. Please open an issue at https://github.com/angular/angular
