### ISSUE TITLE
[Tabs] Add output for onCentered

### ISSUE THREAD

**Issue by vladimir-ivanov** [angular/material2#3032]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I would like to have have a hook on top level (@Output property) on md-tab-group to know when the sliding in animation as defined in MdTabBody completed.
Ideally proxying @Output() onCentered from MdTabBody on MdTabGroup component to re emit.

#### What is the current behavior?
We don't have an option to resize third party components once the slide in has completed ->
 this._portalHost.attach happens initially in ngAfterViewChecked for MdTabBody, but at that point the portalHost element does not have width and height defined, which the child component we are attaching can not size itself correctly.

#### What is the use-case or motivation for changing an existing behavior?
So nested components inside tabs which are not active get correct width and height properties/ or allow them to be resized on animation complete -> e.g. onCentered.emit() for MdTabBody

#### Which versions of Angular, Material, OS, browsers are affected?
@angular: "2.4.1"
@angular/material: "2.0.0-beta.1"

**Comment by amcdnl** [comment]
PR in progress for this - https://github.com/angular/material2/pull/6811
