### ISSUE TITLE
ExtraClasses property on snackBarConfig

### ISSUE THREAD

**Issue by pixelsailor** [angular/material2#3034]
#### Bug, feature request, or proposal:
The snackbar demo still shows an `extraClasses` property attached to the MDSnackBarConfig reference. This feature appears to have been deprecated however I think it would still be super helpful to include. 

#### What is the expected behavior?
Unclear. Was the property intentionally removed?

#### What is the current behavior?
`.extraClasses` is unsupported and causes a TS error.

#### What are the steps to reproduce?
From the source of the demo app
```
open() {
    let config = new MdSnackBarConfig();
    config.duration = this.autoHide;
    config.extraClasses = this.addExtraClass ? ['party'] : null;
    this.snackBar.open(this.message, this.action && this.actionButtonLabel, config);
}
````

#### What is the use-case or motivation for changing an existing behavior?
Adding custom classes was a useful feature

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0-beta.1

**Comment by crisbeto** [comment]
`extraClasses` was only added a few days ago, which is why it isn't in beta.1. It should be included in beta.2.
