### ISSUE TITLE
Overlay issue -> No provider for Token overlayContainer!

### ISSUE THREAD

**Issue by JimmyMagee** [angular/material2#304]
I'm trying to get overlay working in a angular2 webpack starter project (https://github.com/AngularClass/angular2-webpack-starter), following the demo overlay example however I'm getting the following error at runtime - No provider for Token overlayContainer! 

Here is the import statements of the updated home component.

import {Component, ElementRef, ViewChildren, QueryList, ViewEncapsulation, OpaqueToken} from 'angular2/core';
import {AppState} from '../app.service';
import {
Overlay,
OverlayState} from '@angular2-material/core/overlay/overlay';
import {ComponentPortal, Portal} from '@angular2-material/core/portal/portal';
import {TemplatePortalDirective} from '@angular2-material/core/portal/portal-directives';

Providers and directives setup like so..

 providers: [
    Overlay,
    Title
  ],

  directives: [
    TemplatePortalDirective
  ],
  encapsulation: ViewEncapsulation.None,

I've copied the demo app openRotiniPanel() function to the updated home component and
in the components template I've added 

<button (click)="openRotiniPanel()">
  Pasta 1
</button>

<template portal>
  <p class="demo-fusilli"> Fusilli </p>
</template>

Here's the error in the browser console.

browser_adapter.ts:73 Error: Uncaught (in promise): No provider for Token overlayContainer! (Home -> Overlay -> Token overlayContainer)
    at resolvePromise (zone.js:576)
    at zone.js:553
    at ZoneDelegate.invoke (zone.js:364)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (ng_zone_impl.ts:65)
    at ZoneDelegate.invoke (zone.js:363)
    at Zone.run (zone.js:257)
    at zone.js:609
    at ZoneDelegate.invokeTask (zone.js:397)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.ts:54)
    at ZoneDelegate.invokeTask (zone.js:396)

Thoughts?

**Comment by UnwrittenFun** [comment]
I ran into the same issue and solved it by add the following to my providers array:
```typescript
import {provide} from "angular2/core";
import {
  OVERLAY_CONTAINER_TOKEN,
  createOverlayContainer
} from "@angular2-material/core/overlay/overlay";

// ....

providers: [
  // Other providers....
  provide(OVERLAY_CONTAINER_TOKEN, {useValue: createOverlayContainer()}),
]
```

**Comment by JimmyMagee** [comment]
That done the trick, thanks J.
