### ISSUE TITLE
Error in website doc

### ISSUE THREAD

**Issue by pabx06** [angular/material2#3054]
#### Bug, feature request, or proposal:
i followed the theming guide of https://material.angular.io/guide/theming

i add the following line in styles.css:
@import '~@angular/material/core/theming/all-theme';

@angular/cli gives me webpack error:
`Module not found: Error: Can't resolve '@angular/material/core/theming/all-theme' in 'C:\Users\me\WebstormProjects\myproject\
src'
 @ ./~/css-loader?{"sourceMap":false}!./~/postcss-loader!./src/styles.css 4:10-123
 @ ./src/styles.css
 @ multi ./src/styles.css
webpack: Failed to compile.
`

i guess the documentation is not uptodate ?

SOLUTIN WAS to rename styles file:
mv styles.css styles.scss
then adjusting angular-cli.json 

VERSION:
"@angular/cli": "1.0.0-beta.31",
"@angular/material": "^2.0.0-beta.1",

**Comment by d3viant0ne** [comment]
The CLI is expecting that import to be `.css` 

As it is, you are trying to import `.scss` into `.css` without preprocessing it hence the error. This isn't a documentation issue, it's a configuration issue. IMO if you want to leverage the theming engine in material, just use scss in your project, particularly if you are using the CLI.

**Comment by kara** [comment]
Given that this seems specific to your build setup, I'm going to close this.

**Comment by pabx06** [comment]
Changed the cli to use scss. A thing  witch is not hinted the documentation
