### ISSUE TITLE
Md-snackbar: Styling it's container 

### ISSUE THREAD

**Issue by mrmeku** [angular/material2#3055]
Feature request:
Add an option to specify a class name, style URL or someone means of styling the element wrapping an md-snackbar. 

What is the expected behavior?
Allow users to make snack bars different colors, or sizes if they need that flexibility. 

What is the current behavior?
The component placed into an md-snackbar is wrapped in a container. This container has a dark background and a preset size. The inner component cannot style it's parent due to style encapsulation. 

What are the steps to reproduce?
Show a snack bar using the mdSnackbar service. 

What is the use-case or motivation for changing an existing behavior?
On my platform we use snack bars as part of our error handling. When an error occurs we would like to display a snack bar with a warning color to offer an affordable that an error occured. 

Which versions of Angular, Material, OS, browsers are affected?
All

 Is there anything else we should know?
Nope

**Comment by kyle-sama** [comment]
at the very, very least, "Add an option to specify a class name"

**Comment by mrmeku** [comment]
I want to mention I would be happy authoring a pull request for this feature. But before I start I would like someone from the core team to comment on the API they would like to support

**Comment by mrmeku** [comment]
This also affects mdDialog in the same way

**Comment by donroyco** [comment]
Isn't this partly fixed by #2804 ?

**Comment by mrmeku** [comment]
Yep, I think this can be closed now
