### ISSUE TITLE
(textarea): multiline input disappears on top

### ISSUE THREAD

**Issue by axtho** [angular/material2#3057]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
On entering text wit multiple lines the textarea box should adapt downwards (see [MAT1](https://material.angularjs.org/latest/demo/input))

#### What is the current behavior?
The text disappears upward. No dynamic adaptation takes place.

#### What are the steps to reproduce?
Compare the [MAT1](https://material.angularjs.org/latest/demo/input) and [MAT2](https://material.angular.io/components/component/input) implementation.

#### What is the use-case or motivation for changing an existing behavior?
Usability

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/flex-layout: 2.0.0-beta.5
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.1 (https://github.com/angular/material2-builds.git)
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
@angular/platform-server: 2.4.7

Chrome 56.0.2924.87

**Comment by dahaupt** [comment]
@axtho There is already a directive to achieve this behavior. You can use `mdTextareaAutosize` inside your `textarea` tag to automatically resize the textarea while entering text. (https://material.angular.io/components/component/input)

Please close this issue yourself if you have no more questions :)

**Comment by axtho** [comment]
Thanks! Those who can read have an advantage ;)
