### ISSUE TITLE
checkbox - incorrect styling

### ISSUE THREAD

**Issue by michaelb-01** [angular/material2#3060]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Styling as illustrated in the online demo app

#### What is the current behavior?

Styling looks incorrect:
<img width="114" alt="screen shot 2017-02-11 at 16 01 11" src="https://cloud.githubusercontent.com/assets/3755633/22855191/bcc4e6a0-f073-11e6-9cbf-70a88294173c.png">

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?

2.0.0-beta.1

**Comment by dahaupt** [comment]
@michaelb-01 Where is your plunker example to reproduce your issue? Most likely you forgot to include the core theme.

**Comment by michaelb-01** [comment]
You were right, I had forgotten to include the theme, i've included the following and now the checkbox correct:

<link href="https://rawgit.com/angular/material2-builds/master/core/theming/prebuilt/indigo-pink.css" rel="stylesheet">

However now nothing happens when I click it.. (no errors in the console though)

**Comment by dahaupt** [comment]
@michaelb-01 What do you expect to happen when you click the checkbox?
In case you missed the docs for checkbox: https://material.angular.io/components/component/checkbox

**Comment by michaelb-01** [comment]
Hi @dahaupt, yes i'm expecting to be able to toggle the checkbox as in the link you provided, however nothing happens when I click the checkbox (no tick etc. but no errors either). I created a quick project with angular cli and the checkbox worked fine there so i'm not sure what i've done.. Its a meteor-angular2 project, I don't know if there are any known issues with meteor?

**Comment by wbhob** [comment]
If it has an `[(ngModel)]`, make sure you have defined it in your component code. Make sure the options are valid. Please make a plunkr reproducing the issue. I'd be happy to take a look.

**Comment by michaelb-01** [comment]
Hi @wbhob, I can't think how to make a plunkr without uploading my whole project, i'm literally just trying the example from the demo site (so no ngModel):

<md-checkbox>Check me!</md-checkbox>

I've just updated all my angular packages to check if that was the problem but still no luck, this is my package.json:

```
{
  "name": "Pipe",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "test": "meteor test --driver-package practicalmeteor:mocha",
    "test:ci": "meteor test --once --driver-package dispatch:mocha-phantomjs",
    "postinstall": "typings i",
    "step": "node ./git-helpers/step",
    "desktop": "meteor-desktop"
  },
  "devDependencies": {
    "@types/chai": "^3.4.33",
    "@types/hammerjs": "^2.0.33",
    "@types/mocha": "^2.2.32",
    "chai": "3.5.0",
    "chai-spies": "0.7.1",
    "meteor-desktop": "^0.4.0",
    "minimist": "^1.2.0",
    "typings": "^1.3.3"
  },
  "dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0",
    "@angular/material": "^2.0.0-beta.1",
    "@types/mocha": "^2.2.33",
    "angular2-meteor": "^0.7.1",
    "angular2-meteor-accounts-ui": "^0.8.0",
    "angular2-meteor-polyfills": "^0.1.1",
    "angular2-meteor-tests-polyfills": "0.0.2",
    "babel-runtime": "^6.18.0",
    "bcrypt": "^0.8.7",
    "hammerjs": "^2.0.8",
    "meteor-node-stubs": "0.2.3",
    "meteor-rxjs": "0.3.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.1",
    "zone.js": "^0.7.6"
  }
}
```

Then i'm including angular material in my ngmodule:

```
import { MaterialModule } from '@angular/material';

...
imports: [
    MaterialModule.forRoot()
],

...
```

Then I include the theme in my index.html:

`<link href="https://rawgit.com/angular/material2-builds/master/core/theming/prebuilt/indigo-pink.css" rel="stylesheet">`

Have I done anything wrong?

**Comment by michaelb-01** [comment]
So i've figured out part of the problem, the indigo-pink theme I was using had 'mat-' as a prefix (e.g. mat-checkbox-checked) but the html generated <md-checkbox> used 'md-' as a prefix for all the classes... Which one is correct and how should I unify them?

**Comment by wbhob** [comment]
md if you're using the npm beta 1 version, mat if you're using github build

Wilson Hobbs
CEO/Founder/Developer at Canal
11th Grade at The Lovett School

Personal Information
E-mail: wilsonhobbs1@gmail.com
Cell: (404) 719-3252
Website: www.wilsonhobbs.com (https://www.wilsonhobbs.com)
Twitter/Instagram/Facebook: @wbhob

Canal Information
E-mail: wilson@getcanal.com
Web: www.getcanal.com (https://www.getcanal.com/)

Twitter/Instagram/Facebook: @getcanal

**Comment by michaelb-01** [comment]
Presumably these will be unified? which one will be used in the future?

**Comment by wbhob** [comment]
No, I believe it is universally `mat-` now.

Wilson Hobbs
CEO/Founder/Developer at Canal
11th Grade at The Lovett School

Personal Information
E-mail: wilsonhobbs1@gmail.com
Cell: (404) 719-3252
Website: www.wilsonhobbs.com
Twitter/Instagram/Facebook: @wbhob

Canal Information
E-mail: wilson@getcanal.com
Web: www.getcanal.com
Twitter/Instagram/Facebook: @getcanal

**Comment by jelbourn** [comment]
Yes, all the css is `mat-` everywhere now.
