### ISSUE TITLE
Possible error in getting started guide

### ISSUE THREAD

**Issue by kiranj321** [angular/material2#3061]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Documentation at https://github.com/angular/material2/blob/master/guides/getting-started.md#install-angular-cli 
indicates to include 
import 'hammerjs';

#### What is the current behavior?
To avoid warnings, it should be 
import 'hammerjs/hammer';

#### What are the steps to reproduce?
Just follow the getting started guide

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Clean documentation

**Comment by vitorreis** [comment]
I opened a pr for it

**Comment by victorschinaider** [comment]
I think this issue shouldn't be closed yet, right?

https://github.com/angular/material2/pull/3216

**Comment by DevVersion** [comment]
Shouldn't be necessary - Loaders are actually smart enough to detect that the package from HammerJS redirects to the `hammer.js` file. See for example [this](https://unpkg.com/hammerjs@2.0.8/package.json)
