### ISSUE TITLE
Garbage appears over input/textarea in prod build

### ISSUE THREAD

**Issue by jymdman** [angular/material2#3062]
#### Bug, feature request, or proposal:
In latest builds there appears garbage characters '\00a0' over input and textarea when building with flag -prod, eg 'ng serve -prod'.
If build on dev mode, 'ng serve', the characters don't appear!

#### What is the expected behavior?
Garbage characters shouldn't appear

#### What are the steps to reproduce?
Link to screenrecording showing the problem:
https://drive.google.com/open?id=0ByCXNvMwFOMrRE5NcjFiU0lNUFU

#### Which versions of Angular, Material, OS, browsers are affected?

package.json:

{
  "name": "gnosjo-frasteknik-stalldata",
  "version": "0.0.9",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\" --project src/tsconfig.json --type-check && tslint \"e2e/**/*.ts\" --project e2e/tsconfig.json --type-check",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.4.4",
    "@angular/compiler": "2.4.4",
    "@angular/core": "2.4.4",
    "@angular/forms": "2.4.4",
    "@angular/http": "2.4.4",
    "@angular/material": "git+https://github.com/angular/material2-builds.git",
    "@angular/platform-browser": "2.4.4",
    "@angular/platform-browser-dynamic": "2.4.4",
    "@angular/router": "3.4.4",
    "angular2-uuid": "^1.1.0",
    "angularfire2": "^2.0.0-beta.7",
    "core-js": "^2.4.1",
    "firebase": "^3.6.2",
    "hammerjs": "^2.0.8",
    "ng2-imageupload": "^1.3.0",
    "ng2-smart-table": "^0.5.3-0",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0-beta.31",
    "@angular/compiler-cli": "2.4.4",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }
}

#### Is there anything else we should know?

This has been introduced in the last couple of days...
Don't know exactly when I upgraded material2 last time, but no more than a week ago...

**Comment by crisbeto** [comment]
This should've been solved by https://github.com/angular/material2/pull/3025. Can you try installing from `master` again?

**Comment by jymdman** [comment]
Looks like that commit hasn't been pushed to material2-builds yet....
I guess I have to wait then!
Thanks!

**Comment by crisbeto** [comment]
Alright, well either way it should be gone. I'll close the issue.

**Comment by jymdman** [comment]
I updated the css file manually, and everything seems to be ok with that commit.
So it should indeed be closed! 👍
