### ISSUE TITLE
(md-select) with placeholder changes size when selected

### ISSUE THREAD

**Issue by benb7760** [angular/material2#3073]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
An md-select with a selection should be the same size as with no selection

#### What is the current behavior?
This is true for an md-select with no placeholder, but when I provide a placeholder, the control sizes differently

As a side note - can anybody comment on why the second controls placeholder overlaps with the control above, when selected? Is this a bug which should be filed separately?

#### What are the steps to reproduce?
Select a value in both of the lists, and you'll see an offset

http://plnkr.co/edit/KdHQWMFXj2hEFWWFRJyq?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Reproduced in Chrome and Safari latest (not tried other browsers)

**Comment by dahaupt** [comment]
@benb7760 To answer your second question: This issue is already known and will be fixed soon with #2309.

**Comment by dahaupt** [comment]
This is because of this method in `select.ts`:
```typescript
private _setValueWidth() {
    this._selectedValueWidth =  this._triggerWidth - 13;
  }
```

When removing this line it works fine, but I'm not sure about the side effects of that.

**Comment by dahaupt** [comment]
To fix this temporary you can use:
```css
span.mat-select-placeholder.mat-floating-placeholder {
  width: auto !important;
}
```

**Comment by jelbourn** [comment]
Tracking via #2124
