### ISSUE TITLE
Unit tests process crashes

### ISSUE THREAD

**Issue by dahaupt** [angular/material2#3074]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The unit tests should work on master branch.

#### What is the current behavior?
The process fails in step `:build:components:spec` with:
```
node_modules/@types/jasmine/index.d.ts(39,38): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.
node_modules/@types/jasmine/index.d.ts(39,46): error TS2304: Cannot find name 'keyof'.
node_modules/@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected.
```

#### What are the steps to reproduce?
Run `gulp test` on the master branch.

#### Which versions of Angular, Material, OS, browsers are affected?
Latest Version of Material, Windows 10, Angular 2.4.7

#### Is there anything else we should know?
I'm no expert in unit tests, but simply starting them on a new cloned repository should work (e2e tests are working fine). It could be possible too, that this is just a problem on my system, because otherwise someone would have already noticed this.

**Comment by modernfidelity** [comment]
I'll also getting this via ->  gulp build:release  at the "Starting ':build:components:ngc'" step

**Comment by kara** [comment]
Running tests works for me on master. What version of node are you running?  I'm running 6.2.2.

**Comment by dahaupt** [comment]
@kara I'm running version v6.9.5 of node.

**Comment by trshafer** [comment]
I have the same issue. I'm running 6.9.4, as that is what travis is running on: https://github.com/angular/material2/blob/master/.travis.yml#L5

**Comment by kara** [comment]
How about Typescript versions?

**Comment by dahaupt** [comment]
My global Typescript version is 2.1.5, in the project (master) it is 2.0.10. I'm not sure which one is used for tests.

**Comment by trshafer** [comment]
Did a git bisect of "npm install && npm test". This is the commit where it changed from a warning to an error 4a4261e141c23ad3a14fe5869498dcde2640db6b.

**Comment by kara** [comment]
Okay, just blew away my node modules and started from scratch. Also getting the error now.

**Comment by modernfidelity** [comment]
Solved this by reducing the @types/jasmine to 2.5.38

**Comment by owlstack** [comment]
I'm having the same issue. Is this resolved? should I wait for latest release?

**Comment by trshafer** [comment]
@owlstack, are you still getting the issue with #3080 merged in? Did you remove your node_modules folder and re install?

**Comment by Slashmsu** [comment]
I have the same error, I removed node_modules and reinstalled it, but I still have this error

**Comment by jppellerin** [comment]
I had this issue and I can confirm that going back down to 2.5.38 resolved it.
