### ISSUE TITLE
Please update High level items planned for February 2017

### ISSUE THREAD

**Issue by vipdorian** [angular/material2#3075]
Hi,
Please update High level items planned for February 2017.

Thanks

**Comment by fxck** [comment]
the person who usually does that is on holiday, wait couple more days

**Comment by RicardoVaranda** [comment]
@fxck Thanks for the update! As a matter of interest would you happen to know when the next released is scheduled for?

**Comment by fxck** [comment]
Not really, but personally I feel there are quite a few pull requests that are pretty much ready, just waiting for review, or are even already labelled as merge ready for a while, and it would be a shame to release without those, given how rare releases are, so I hope they merge those first(most of them are assigned to Jeremy, same person that usually updates plans in readme). So next release might be, give or take, in somewhere between week and a month. 

Anyway, if you don't mind fishing for potential breaking changes, just use https://github.com/angular/material2-builds it's always up to date with what's in master.
