### ISSUE TITLE
md-input-container in md-card makes strange warning

### ISSUE THREAD

**Issue by alanpurple** [angular/material2#3076]
```
<md-card>
    <md-input-container>
        <input md-input type=text>
    </md-input-container>
</md-card>
```

this makes the following warning

The specified value "" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.

material2 2.0.0-beta.1
angular 4.0.0-beta.7

**Comment by crisbeto** [comment]
This has been fixed by https://github.com/angular/material2/pull/2906.
