### ISSUE TITLE
How to use swipe directive?

### ISSUE THREAD

**Issue by gkucmierz** [angular/material2#3079]
How to use swipe directive?
```js
md-swipe-left="onSwipeLeft()"
```
is not working

**Comment by dahaupt** [comment]
@gkucmierz You should follow the issue template and provide a plunker for your issue. Otherwise it will probably get removed.

 [Issue Template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by gkucmierz** [comment]
Ok, you can remove it.
I have question actually, not an issue.

**Comment by dahaupt** [comment]
@gkucmierz I can't remove it, because I'm no Member of this repository. You can close it yourself and ask your question here: https://gitter.im/angular/material2
