### ISSUE TITLE
md-tab *ngFor not work

### ISSUE THREAD

**Issue by stefanofalasca** [angular/material2#3084]
#### Bug, feature request, or proposal:
I am trying to create tab dynamically like this:
<md-tab-group>
    <md-tab label="componente.Nome" *ngFor="let componente of dati?.Componenti" [dati]="componente">
    </md-tab>
  </md-tab-group>

but it not work

**Comment by andrewseguin** [comment]
Using the full issue template really helps us resolve your issue, especially by including a reproducible plunker that we can work with. Feel free to open the issue back up if you can provide an example of the problem.
