### ISSUE TITLE
Extract variables per component

### ISSUE THREAD

**Issue by grizzm0** [angular/material2#3085]
#### Bug, feature request, or proposal:
Feature request:
Extract variables from ie. card/card.scss to card/_variables.scss

#### What is the use-case or motivation for changing an existing behavior?
I'm writing my own component that is dependent on the toolbar height for positioning. Importing toolbar/toolbar.scss would render an unnecessary md-toolbar CSS-class. 

Instead I need to copy all the variables to my own component.scss. It would be really helpful it the variables where in their own partial file so I could simply import them.

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-beta.1

**Comment by wbhob** [comment]
Just make a variables file, add it to angular-cli.json, and link to it in each of your components.

**Comment by grizzm0** [comment]
@wbhob Don't think you quite understood what I meant. I want to use the already defined variables in @angular/material without having to create my own variables file and/or a copy of the variables.

Also, the style tag in angular-cli.json and component styles are two separate scopes.

**Comment by grizzm0** [comment]
Not really relevant anymore due to #4003
