### ISSUE TITLE
Create a Plunker template using angular2-material

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#309]
This should be similar to the plunker for Angular 2 itself:
https://angular.io/resources/live-examples/quickstart/ts/plnkr.html

This will involve hosting the most recent published bundles somewhere.

**Comment by Todd-Werelius** [comment]
+1 and it would pretty helpful, I played around with it for a few minutes but couldn't get any joy, rather new to ang2 in general

**Comment by GongT** [comment]
learned new thing :D

**Comment by GongT** [comment]
there is a full demo in /src folder
start it using `npm install` && `npm run demo-app`

so, why not write these in readme or "good for community contribution" ?

**Comment by alexandermikuta** [comment]
An example/ in combination with Angular-CLI would be nice...

**Comment by colemickens** [comment]
I'd argue that the demo-app in the `src/` folder isn't sufficient. The demo-app references the components locally. I personally would greatly benefit from a canonical example repo that is standalone and consumes these components.

**Comment by Auha** [comment]
The closest thing that I could find is from ng-conf in the following link:

https://github.com/kara/puppy-love

It is built using angular-cli and some of the basic stuff.
