### ISSUE TITLE
Adjust width and height of md-select

### ISSUE THREAD

**Issue by basherr** [angular/material2#3090]
**Template:**
```
<md-select placeholder="Select Costcode Template" name="costcode_template" 
              [width]="'100%'"
              cdk-connected-overlay 
              ngModel>
```
**Component.ts**
```
import { MdSelect, MdOption } from '@angular/material';
```
**Module**
```
import { MdSelectModule, OverlayModule } from '@angular/material';
@NgModule({
    declarations: [
        ProjectComponent,
    ],
    imports: [
        FormsModule,
        HttpModule,
        projectsRouting,
        MdSelectModule,
        OverlayModule
    ]
})
```
#### What is the expected behavior?
The select should adjust the width and height.

#### What is the current behavior?
`caused by: No provider for TemplateRef!`

#### Which versions of Angular, Material, OS, browsers are affected?

os: win32 x64
@angular/core: 2.4.7
@angular/material: 2.0.0-beta.1
@angular/cli: 1.0.0-beta.31

**Comment by fxck** [comment]
try either 

```
[style.width]="'100%'"
```

or even better, put a css class on it and just use css

**Comment by basherr** [comment]
@fxck But the just set the width of the select box while options width just remains as is.
![screencast](https://cloud.githubusercontent.com/assets/10073316/22929383/4423c934-f2dd-11e6-9afb-b48a983c7ad9.png)

**Comment by fxck** [comment]
You need to do `MaterialModule.forRoot()` on in your root component. Or create a plunk if the problem persists.

**Comment by basherr** [comment]
@fxck http://plnkr.co/edit/BC9gNtUvW0CoNPS9cpsU?p=preview

**Comment by fxck** [comment]
http://plnkr.co/edit/Bnn3uF5e6NzIADYfo6WK?p=preview this is what you want?

**Comment by andrewseguin** [comment]
The TemplateRef error is due to the cdk-connected-overlay added to your element. Remove that directive to fix that issue.

You should be able to use [style.width]="'100%'" on the <md-select> to extend it. Although, the options will extend 16px on either side so you likely want "'calc(100% - 32px)'".

http://plnkr.co/edit/Ewq7wKZGEmcTgxCFltid?p=preview

**Comment by josephperrott** [comment]
Closing as `MdSelect` styling has been rewritten/changed and this no longer applies.
