### ISSUE TITLE
Add labelPosition to md-slide-toggle

### ISSUE THREAD

**Issue by crutchcorn** [angular/material2#3092]
#### Bug, feature request, or proposal:
Just as `<md-checkbox>` has `labelPosition`, I propose that the same property should be added to `md-slide-toggle`

#### What is the expected behavior?
When adding:

`<md-slide-toggle labelPosition="before">Available Offline</md-slide-toggle>`

The label would be before the toggle.

#### What is the current behavior?
The label-position does nothing, as it is not implamented.

#### What are the steps to reproduce?
Add above code into file. See the following:
http://plnkr.co/edit/8Z2V2T16tmMoIvY9np4t

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
In order to provide more functionality and consistency in code

#### Which versions of Angular, Material, OS, browsers are affected?
```
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/compiler-cli: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/platform-server: 2.4.6
@angular/router: 3.4.6
@angular/upgrade: 2.4.6
Chrome: 56.0.2924.87 
OS: Windows 10 Pro
```

**Comment by DevVersion** [comment]
Thanks for the issue. This has been added recently in SHA https://github.com/angular/material2/commit/68a0c9044e701392f6fe52b6bdf81ce498b9cfab. It will be available in `beta.2`.

**Comment by crutchcorn** [comment]
I apologize. Glad to see it's been added! Cheers!
