### ISSUE TITLE
macbook pr

### ISSUE THREAD

**Issue by garyking11** [angular/material2#3096]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by wbhob** [comment]
I'm having trouble understanding exactly what's going on here...

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
