### ISSUE TITLE
Menu in a fixed toolbar flips direction when window scrollY >= some px threshold

### ISSUE THREAD

**Issue by yasserlens** [angular/material2#3099]
#### Bug, feature request, or proposal:
Bug in MdMenu

#### What is the expected behavior?
Menu panel should respect position-x and position-y attributes. It should also be consistent, not change behavior based on window.scrollY or scrollX.

#### What is the current behavior?
Menu panel x-position shifts to the left when window.scrollY >= a certain threshold.

#### What are the steps to reproduce?
- Menu trigger is in a fixed panel at the top of the page, positioned as follows:
    position: fixed;
    left: 0;
    top: 0;
    z-index: 10;
- Menu panel is placed in the same container that has the trigger (not that it matters).
- Menu appears as it should when window.scrollY = 0
- When window.scrollY >= 169px, menu panel shifts to the left.
- The threshold is different in the plunkr attached than in the app I have.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://plnkr.co/edit/kCCCXUWd1FT5FtZwK8sP?p=preview

#### What is the use-case or motivation for changing an existing behavior?
To fix it!

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/material": "^2.0.0-beta.1",
"@angular/core": "^2.4.7",

Chrome Version 55.0.2883.95 (64-bit)
And Android Nexus 5X User Agent

**Comment by crisbeto** [comment]
This has been fixed by https://github.com/angular/material2/pull/2677 which should land in the next release. You can give it a try by running `npm install https://github.com/angular/material2-builds.git`.

**Comment by yasserlens** [comment]
Thanks @crisbeto , I can confirm that it is fixed.
