### ISSUE TITLE
md-tab not work using *ngFor

### ISSUE THREAD

**Issue by stefanofalasca** [angular/material2#3100]
#### Bug, feature request, or proposal:
here sample on plunker, you can see that secon tab group is not showed, and I used ngFor
https://plnkr.co/edit/ScYwmDUCfnuviJU9xm6X?p=preview

**Comment by mxii** [comment]
It's not an material2 problem.

Working demo: https://plnkr.co/edit/8sf5JVoCVtKf5fsNeIDz?p=preview

```TypeScript
export class AppComponent {
  /* private, public or 'nothing' */ tabs:string[]=["tab1", "tab2"];
}
```

**Comment by crisbeto** [comment]
As @mxii mentioned, this isn't a Material issue. It doesn't work, because you have a `var` before the property declaration.
