### ISSUE TITLE
Checkbox/Radio button does not have any indicator to show its focus state

### ISSUE THREAD

**Issue by thanhpd** [angular/material2#3102]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Checkbox/Radio button has focus ripple in focused state

#### What is the current behavior?
Checkbox/Radio button does not have any indicator to show its focused state

#### What is the use-case or motivation for changing an existing behavior?
- Usability
- Material spec: https://material.io/guidelines/components/selection-controls.html

![image](https://cloud.githubusercontent.com/assets/6737911/22967479/31779f38-f399-11e6-8946-9e0bf790728e.png)

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2-beta1

**Comment by crisbeto** [comment]
This has been fixed in https://github.com/angular/material2/pull/1730 and https://github.com/angular/material2/pull/1731 although those PRs should be freshened up a bit.
