### ISSUE TITLE
website outdated, example doesn't work

### ISSUE THREAD

**Issue by ramarro123** [angular/material2#3105]
https://material.angular.io/components/component/select

on examples i read

  <md-select placeholder="Favorite food" [(ngModel)]="selectedValue" name="food">

ngModel isn't the 2 way databind things that was removed in angular2?

i am new to angular2, so i might be wrong

**Comment by fxck** [comment]
Yes, you are wrong. `ngModel` is still there. And it seems to be working for me

![image](https://cloud.githubusercontent.com/assets/1303561/22973453/00484108-f37e-11e6-81d9-6b8203a31be2.png)

**Comment by ramarro123** [comment]
shame on me, i haven't import FormsModule on app.module :(

sorry
