### ISSUE TITLE
md-ink-bar not visible using <nav md-tab-nav-bar>

### ISSUE THREAD

**Issue by ArtworkAD** [angular/material2#3107]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

md-ink-bar should be visible

#### What is the current behavior?

<img width="641" alt="bildschirmfoto 2017-02-15 um 12 25 25" src="https://cloud.githubusercontent.com/assets/524580/22972440/e305c43e-f379-11e6-900c-ad02e2e6cbf9.png">

md-ink-bar is not visible

#### What are the steps to reproduce?

http://plnkr.co/edit/qXJdsDIr5pwXxCdbRyLL

The plunker includes a simple example, however I could not get the router to work correctly, because I am not familiar with plunker. 

#### What is the use-case or motivation for changing an existing behavior?

```<nav md-tab-nav-bar>``` should yield the same presentation as ```<md-tab-group>```

#### Which versions of Angular, Material, OS, browsers are affected?

Tested on angular 2.3 and 2.4, material2 2.0.0-beta.1,  Chrome v56

#### Is there anything else we should know?

nope

**Comment by andrewseguin** [comment]
This should be fixed by #3041
