### ISSUE TITLE
MdDialog not work correct 

### ISSUE THREAD

**Issue by cbyniiaii** [angular/material2#3108]
#### Bug, feature request, or proposal:
MdDialog not work correct

#### What is the expected behavior?
<button md-button (click)="openDialog()">Open dialog</button>
constructor(public dialog: MdDialog) {}
openDialog() {
    this.dialog.open(ProgressDialogComponent);
  }

@Component({
  selector: 'progress-dialog',
  templateUrl: `
    <div md-dialog-content>
        <md-spinner></md-spinner>
    </div>
`,
})
export class ProgressDialogComponent {
}

#### What is the current behavior?
every click it will display a dialog 

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/core": "2.4.6", 
 "@angular/material": "^2.0.0-beta.1",
macOS Sierra
Chrome 56

![Uploading WX20170215-235125.png…]()

**Comment by kara** [comment]
Can you provide a plunker repro case of this?
