### ISSUE TITLE
Styleguide Pattern

### ISSUE THREAD

**Issue by DiegoYungh** [angular/material2#311]
Just leaving a **suggestion**.

I've seen a lot of people following this pattern, and it seems to be plausible
https://github.com/mgechev/angular2-style-guide

would be awesome having everybody structuring the same way initially, also will help people to contribute, since they will probably already know how to structure it.

Also helps with future code generators.

**Comment by jelbourn** [comment]
We will be following the angular style guide when it's actually complete (the team it still iterating rapidly on the guide). Our very own @hansl is overseeing angular-cli work, so we're already the guinea pig for tooling.
