### ISSUE TITLE
md-core mixin not found when building 2.0.0-beta.2

### ISSUE THREAD

**Issue by fredrik-macrobond** [angular/material2#3126]
Using 
@angular/material 2.0.0-beta.2
webpack 2.3.0
sass-loader 6.0.0
postcss-loader 1.3.0

I get a build error:

Module build failed: 
@include md-core();
        ^
      No mixin named md-core

Backtrace:
	stdin:7
      in R:\fb_wp\sass\angular-material.scss (line 7, column 10)
 @ ./sass/angular-material.scss 4:14-174

**Comment by crisbeto** [comment]
Try using `mat-core` instead.

**Comment by DmitriyPotapov** [comment]
After the release '2.0.0-beta.2', some prefixes replaced with **_md-_** to **_mat-_**

For example:
  [Old theming guide code](https://material.angular.io/guide/theming) 
`
@import '~@angular/material/core/theming/all-theme';

@include md-core();
$candy-app-primary: md-palette($md-indigo);

$candy-app-accent:  md-palette($md-pink, A200, A100, A400);

$candy-app-warn:    md-palette($md-red);

$candy-app-theme: md-light-theme($candy-app-primary, $candy-app-accent, $candy-app-warn);

@include angular-material-theme($candy-app-theme);

`
----- 

**The same code after release '2.0.0-beta.2'**

`
@import '@angular/material/core/theming/all-theme';
@include mat-core;

$candy-app-primary: mat-palette($mat-indigo);
$candy-app-accent:  mat-palette($mat-pink, A200, A100, A400);

$candy-app-warn:    mat-palette($mat-red);

$candy-app-theme: mat-light-theme($candy-app-primary, $candy-app-accent, $candy-app-warn);

@include angular-material-theme($candy-app-theme);

`

**Comment by fredrik-macrobond** [comment]
Sorry, this was my mistake. I hadn't updated the scss code that I got from https://github.com/angular/material2/blob/master/guides/theming.md

Everything works now when using the updated code from the link above. And yes, the solution was to exchange the 'md-' prefix to 'mat-'.

Thanks all for your help!
