### ISSUE TITLE
md-select default value is not reapplied after ngDestroy and then re-initializing the component view.

### ISSUE THREAD

**Issue by craigt1212** [angular/material2#3127]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The default value on the md-select directive should be set after ngDestroy and then re-initializing the component view. 

#### What is the current behavior?
The md-select default value is set initially but when navigating away from the component and back to the component it is blank. The input box associated to the same ngModel (selectedNode) retains its value as expected.

#### What are the steps to reproduce?

```?
<table class="tn-table tn-links-table">
    <tbody>
    <tr *ngFor="let link of selectedNode.links; let i = index;">
      <td width="50">
          <md-select class="tn-links-select" placeholder="Link Type" [(ngModel)]="selectedNode.links[i].linkTypeDn.name"> 
            <md-option *ngFor="let linkType of linkTypes; let j = index;" [value]="linkType.name">
              {{linkType.name}}
            </md-option>
          </md-select>
      </td>
      <td>
          <md-input-container class="tn-md-input-container">
            <label class="tn-label">Dn</label>
            //this input box displays the value as expected.
            <input class="tn-md-input" md-input [(ngModel)]="selectedNode.links[i].dnLink.dn" type="text">
          </md-input-container>
      </td>
    </tr>
    </tbody>
  </table>
```
```?
 @Component({
  selector: 'tn-admin-information-links',
  templateUrl: './links.component.html',
  styleUrls: ['./links.component.scss']
})
export class LinksComponent implements OnInit {
  @Input() selectedNode: any;
  private linkTypes: any;

  constructor(private _logger: Logger, private _nodeTree: NodeTreeService) {
    let orig = this;

    this._nodeTree.findTreeSchemaLinks().subscribe(
      data => {
        orig.linkTypes = data;
      },
      err => {
        orig._logger.error(err);
      });
  }

  ngOnInit() {
  }
} 
```

#### What is the use-case or motivation for changing an existing behavior?
It limits the functionality on the md-select component.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.3.1, Material 2.0.0-beta.1, Windows 7, Firefox and Chrome

**Comment by crisbeto** [comment]
Thanks for the report, could you please wrap the longer code blocks with \`\`\`?

**Comment by craigt1212** [comment]
Thanks for the quick response, code blocks applied.

**Comment by mmalerba** [comment]
The given code appears to be very outdated. The `md-` prefix has been deprecated for quite some time and the select has been rewritten to work inside of `mat-form-field`. If you are still able to reproduce this in the latest version of Angular Material please feel free to file a new issue with a stackblitz reproduction.
