### ISSUE TITLE
md-list-item issue

### ISSUE THREAD

**Issue by joshikumarmanne** [angular/material2#3128]
i am using angular 2.4.0 , material ^2.0.0-beta.1
This is my code using md-list item:
` <md-list>
      <md-list-item *ngFor="let task of tasks">Item 1</md-list-item>
 </md-list>`
when i'm running my code.It's throwing below bug.

Can't bind to 'ngForOf' since it isn't a known property of 'md-list-item'.
1. If 'md-list-item' is an Angular component and it has 'ngForOf' input, then verify that it is part of this module.
2. If 'md-list-item' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
    <md-list>
      <md-list-item [ERROR ->]*ngFor="let task of tasks">Item 1</md-list-item>
    </md-list>

What is this?

**Comment by ciesielskico** [comment]
You didn't import CommonModule from `@angular/common`

**Comment by joshikumarmanne** [comment]
Thanks . Got it.
