### ISSUE TITLE
md-icon - svgIcon not found error

### ISSUE THREAD

**Issue by dominikstrasser** [angular/material2#3130]
#### Bug, feature request, or proposal:
The app crashes if the svgIcon was not found in the iconRegistry

#### What is the expected behavior?
The app should not crash - a propper error should be logged

#### What are the steps to reproduce?
http://plnkr.co/edit/ba0rqIHlf6jc9c5mnGXZ?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Beta.01

#### Is there anything else we should know?
PR --> https://github.com/angular/material2/pull/3129

**Comment by kara** [comment]
Closed by #3129
