### ISSUE TITLE
Custom theming md-core() is not defined

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#3140]
#### Bug, feature request, or proposal:

bug

#### Which versions of Angular, Material, OS, browsers are affected?

angular 2.4.0, material 2.0.0-beta.2, Win 10, chrome

#### Is there anything else we should know?

I followed the guide for custom theme

```scss
@import '~@angular/material/core/theming/all-theme';

@include md-core();

$md-default: $font-color;
$md-action: $action-color;
$md-output: $output-color;

$candy-app-primary: md-palette($md-default);
$candy-app-accent: md-palette($md-action, A200, A100, A400);
$candy-app-warn: md-palette($md-output);
$candy-app-theme: md-light-theme($candy-app-primary, $candy-app-accent, $candy-app-warn);

@include angular-material-theme($candy-app-theme);
```
**Error:**

`ERROR in ./~/css-loader?{"sourceMap":false}!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module build failed: 
@include md-core();
        ^
      No mixin named md-core`

**Comment by MurhafSousli** [comment]
Oh, I just saw the breaking change 

```scss
@include mat-core();
```

**Comment by nydiarra** [comment]
Thank you MurhafSousli . I run into the same problem because I didn't notice the change of prefix in the latest version from 'md' to 'mat'.
