### ISSUE TITLE
Typo in ts code of Progress Spinner Example

### ISSUE THREAD

**Issue by userexperiences** [angular/material2#3148]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
"Primary" radio button should be selected

#### What is the current behavior?
Radio button not selected

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
https://material.angular.io/components/component/progress-spinner
Change 

export class ProgressSpinnerConfigurableExample {
  color = 'praimry';

to

export class ProgressSpinnerConfigurableExample {
  color = 'primary';

**Comment by vitorreis** [comment]
I would like to work on this
