### ISSUE TITLE
mat-input-container doesn't line up with mat-select

### ISSUE THREAD

**Issue by JacobBrandt** [angular/material2#3149]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When placing an md-input-container next to an md-select the two underlines should line up

#### What is the current behavior?
The mat-input-container is higher or lower than the mat-select depending on browser.  Chrome
<img width="316" alt="screen shot 2017-02-16 at 6 03 47 pm" src="https://cloud.githubusercontent.com/assets/5314322/23048335/528908cc-f472-11e6-90b3-4d8791b24fc1.png">
Firefox
<img width="313" alt="screen shot 2017-02-16 at 6 10 02 pm" src="https://cloud.githubusercontent.com/assets/5314322/23048453/2ac71d3c-f473-11e6-8cd3-94890dc902a8.png">

#### What are the steps to reproduce?
md-input-container next to an md-select

#### What is the use-case or motivation for changing an existing behavior?
My OCD.

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.4.7, Material beta2, MacOS X 10.11.6, Chrome 57.0.2987.37, Firefox 51.0.1

**Comment by kara** [comment]
@JacobBrandt You're totally right that the form control components should line up properly. We actually already have an issue to track this though, https://github.com/angular/material2/issues/2124, so I'm closing this one.
