### ISSUE TITLE
Can't change the size of toolbar

### ISSUE THREAD

**Issue by PeterQT** [angular/material2#315]
**Change size of toolbar**
Currently, md-toolbar only has the size of 64px. 
It's too height and I want to change it to a smaller height such as 50px.
I want to add my-tool-size class to md-toolbar like this:
```
.my-small-size {
     min-height: 50px;
     height: 50px;
}
<md-toolbar color="primary" size="my-small-size">
</md-toolbar>
```

**Comment by DevVersion** [comment]
If your markup is provided correctly, you should use `class="my-small-size"

```html
<md-toolbar color="primary" class="my-small-size">
</md-toolbar>
```

**Comment by jelbourn** [comment]
Just double-checked to confirm that adding a css class works; in general, we want people to style components just like any other DOM element.

**Comment by dfarago** [comment]
That will resize the toolbar, but not the contained toolbar-row, which stays at 64px. How do I resize toolbar-row height?
