### ISSUE TITLE
md-autocomplete: Crashes if they are dynamically created

### ISSUE THREAD

**Issue by JacobBrandt** [angular/material2#3150]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should behave normally

#### What is the current behavior?
A dynamically created autocomplete crashes on focus because the pos object passed to the ConnectedPositionStrategy.prototype._getOriginConnectionPoint is undefined..
ConnectedPositionStrategy.prototype._getOverlayPoint crashes for Firefox.

#### What are the steps to reproduce?
Dynamically create an autocomplete and try to use it

#### What is the use-case or motivation for changing an existing behavior?
To make the control useable

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.4.7, Material beta2, MacOS X 10.11.6, Chrome 57.0.2987.37, Firefox 51.0.1

**Comment by kara** [comment]
Can you add a plunker repro?

**Comment by kara** [comment]
Closing, as we can't reproduce. Please re-open with a plunker if you are still seeing issues.

**Comment by JacobBrandt** [comment]
@kara This seems to happen most often when I have the developer tools open.  It also seems to only happen when the dropdown should be rendered below.  See this GIF for what I mean.
![autocomplete_crash](https://cloud.githubusercontent.com/assets/5314322/24281734/8afd451e-1020-11e7-918b-5982533f7fd5.gif)

**Comment by kara** [comment]
In that case, looks like a dupe of https://github.com/angular/material2/issues/3176. Should be fixed in master.

**Comment by JacobBrandt** [comment]
OK, thank you.
