### ISSUE TITLE
md-hint isn't working with textarea.

### ISSUE THREAD

**Issue by szykov** [angular/material2#3151]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`<md-hint align="right">md-hint-example</md-hint>`

Should appear aligned hint with text 'md-hint-example'

#### What is the current behavior?
Nothing appears. Works only if I use **hintLabel** attribute of **md-input-container**.

#### What are the steps to reproduce?
http://plnkr.co/edit/RYUhDsQABDxUc51cL9F0?p=preview

hintLabel - working
md-hint - isn't working

#### Which versions of Angular, Material, OS, browsers are affected?
Latest.

**Comment by dahaupt** [comment]
@szykov You should use it this way:
```html
<md-input-container>
    <textarea mdInput [(ngModel)]="exampleText"></textarea>
    <md-hint align="right">md-hint-example</md-hint>
</md-input-container>
```

**Comment by szykov** [comment]
@dahaupt Thanks. I wrapped it in textarea html tag. Sorry. :(
ps - also I noted that 'align' should be equal 'end' instead of 'right'.

**Comment by dahaupt** [comment]
@szykov No problem, we all make some little mistakes. You're welcome :)
