### ISSUE TITLE
funny prefix

### ISSUE THREAD

**Issue by vitaly-t** [angular/material2#3154]
> Styling is no longer prefixed by `md-`. All styling is now prefixed by `mat-`.

Russian developers are having a laugh here, because in russian `mat` means `foul language`.

Should have gone for something simpler and more neutral, like `mt-`.

**Comment by Nikki1993** [comment]
can't accommodate all languages tbh :P

**Comment by Nikki1993** [comment]
Can't really accommodate all languages. mat is short for material and to me sounds really good :P

**Comment by kara** [comment]
Ha, well, that's good to know!  The decision has been made to mat- though, and in the interest of not stressing out our community, we'd prefer not to roll out another large breaking change just to change the prefix.
