### ISSUE TITLE
mdInput with *ngIf gives error "Expression has changed after it was checked."

### ISSUE THREAD

**Issue by Weezlo** [angular/material2#3158]
#### Bug
If I put an `*ngIf` directive in an `input` element having `mdInput `directive, angular throws an error.

#### What is the expected behavior?
I should be able to choose which mdInput i want to display in an md-input-container using an *ngIf directive.

#### What is the current behavior?
It throws an error:
`Expression has changed after it was checked. Previous value: 'undefined'. Current value: ''.`

#### What are the steps to reproduce?
just add this code to any template:
```
  <md-input-container>
    <input *ngIf="true" mdInput type="text" placeholder="problematic input">
    <input *ngIf="false" mdInput type="text" placeholder="problematic input">
  </md-input-container>
```
Plunker: http://plnkr.co/edit/mOnd05oDHfQTMrcAUa0B?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.3.1
Material 2.0.0-beta.2
Windows 7
Chrome 56.0.2924.87

#### Is there anything else we should know?
The problem wasn't happening with Angular 2.2.3 and Material 2.0.0-beta.2.

**Comment by mmalerba** [comment]
`*ngIf` should go on the container

**Comment by Weezlo** [comment]
@mmalerba This is what I ended up doing.
