### ISSUE TITLE
md-autocomplete trigger submit on ENTER

### ISSUE THREAD

**Issue by Knoxvillekm** [angular/material2#3159]
md-autocomplete trigger submit form by ENTER click on option:
Plunker template: https://plnkr.co/edit/0a8lqrodE9WVTZEJprlI?p=preview

**Comment by sumpton** [comment]
I am not sure I understand what @Knoxvillekm is after, but it likely relates to my question.

Are there plans for something like a "change" Output in md-select, or "selectItem" I am currently using in  

> https://ng-bootstrap.github.io/#/components/typeahead

**Comment by szykov** [comment]
@Knoxvillekm as workaroudn you can use this:
`<form action="" method="POST" (keydown.enter)="$event.preventDefault()">`

**Comment by frankspin89** [comment]
This is indeed a bug in my opinion. When using enter on autocomplete field, it needs to prevent submitting the form.

**Comment by M-a-c** [comment]
++

**Comment by jefersonestevo** [comment]
I agree with @frankspin89 that the enter should not submit the form. I think that it should just select the option like the md-select does.

**Comment by oshri551** [comment]
I think the same thing exist in mdInput so it's probably related

**Comment by xuanshenbo** [comment]
This is definitely a bug. If ENTER does not trigger submit in a textarea, it shouldn't either for autocomplete

**Comment by PeS82** [comment]
@oshri551 `mdInput` is different beast. It _should_ submit form when hitting Enter from regular INPUT fields. Unlike in TEXTAREA where you need Enter for paragraph. 

And unlike in combo/select and here (autocomplete) where it should select activated option but by all means should not submit form.

I was about to file an issue and found this one instead. +1

**Comment by jefersonestevo** [comment]
I've created the PR #3727 that fixes this behavior and if the material team think that it's ok we may get that fixed soon

**Comment by frankspin89** [comment]
@jefersonestevo Thank you sir. Hoping that your pr is merged soon.
