### ISSUE TITLE
Test Material with Angular 4.x

### ISSUE THREAD

**Issue by kara** [angular/material2#3174]

**Comment by leo6104** [comment]
In Angular 4.0.0-rc.1, template tag is deprecated. Recommendation is ng-template tag.

Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[ERROR ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): MdAutocomplete@0:0.

**Comment by thmb** [comment]
After Angular 4 is released will material and flex-box follow the same version numbering?
