### ISSUE TITLE
[Tooltip] Scroll subscription should be lazy

### ISSUE THREAD

**Issue by andrewseguin** [angular/material2#3179]
Tooltip subscribes to the scroll dispatcher on init. Should move this to be done on show.

**Comment by noemi-salaun** [comment]
It looks like this was fixed in commit c8ec9814bcd2e3087dbb778cec7265296b528890 `feat(overlay): add scroll handling strategies`

**Comment by saulotoledo** [comment]
@andrewseguin @mmalerba Was this fixed in the commit mentioned above? If yes, I think this issue can be closed. :)
