### ISSUE TITLE
md-icon with open_in_new_window has large width hover state

### ISSUE THREAD

**Issue by andrewseguin** [angular/material2#3180]
For some reason (maybe because open_in_new_window is such a long name), the hover state for the icon is too wide.

https://plnkr.co/edit/Cf3CEfvcHudkd2lt3bPc?p=preview

**Comment by crisbeto** [comment]
The hover state looks like it's too wide, because the `border-radius` is too small. In order for the icon to look like a circle, it needs a `border-radius: 40px` or `border-radius: 50%`.

**Comment by andrewseguin** [comment]
Figured out the issue, open_in_new_window isn't an icon =P Turns out if you add the `_window` part, it adds a huge space to the right that can be hovered over. (issue wasn't that the hover wasn't a perfect circle)
