### ISSUE TITLE
md-input is not known, but md-card is

### ISSUE THREAD

**Issue by kootenpv** [angular/material2#3185]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
working md-input

#### What is the current behavior?
I can use `<md-card>`, but `<md-input>` is not a known element

**Comment by antonyRoberts** [comment]
md-input was deprecated with the latest release.
[https://github.com/angular/material2/blob/master/CHANGELOG.md](url) use 
```<md-input-container>
  <input mdInput name="value" ngModel>
</md-input-container> ```

**Comment by antonyRoberts** [comment]
md-input was deprecated with the latest release.
[https://github.com/angular/material2/blob/master/CHANGELOG.md](url) use 
```
<md-input-container>
  <input mdInput name="value" ngModel>
</md-input-container> ```

**Comment by kootenpv** [comment]
Thanks, it works!

**Comment by NeuralChris** [comment]
Why would only mdInput use camel case, yet everything else uses hyphens?  This is dumb.

**Comment by sumpton** [comment]
@NeuralChris your profile looks like mine :)
