### ISSUE TITLE
Wrong baseline for checkbox's label

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#3193]
#### What is the expected behavior?
Correct baseline for md-checkbox's label.

#### What is the current behavior?
Wrong baseline for md-checkbox's label.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-gzawqn?file=app/app.component.html

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0-beta.3

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by Ploppy3** [comment]
The title says everything, what can I do?
I'm tired of reporting issues.

![image](https://cloud.githubusercontent.com/assets/7990765/24842089/81fdf740-1d92-11e7-8e22-f29a81f550ee.png)

Off by 1px vertically.

**Comment by Ploppy3** [comment]
@jelbourn Added a plunker.

**Comment by Ploppy3** [comment]
@jelbourn Issue still persist today, updated to Stackblitz demo
