### ISSUE TITLE
Horizontal padding of the toolbar do not respect Material guidelines

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#3194]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
According to https://material.io/guidelines/layout/structure.html#structure-app-bar
The toolbar should have no padding on sides or a padding of 8px in our case instead of the current 16px.
The 16px padding create problems when you are trying to add buttons in the toolbar.
See your development app: https://material2-dashboard.firebaseapp.com/
The padding is too big, should have been 8px.
I see many people having wrong layout with their material app due to this bug. Therefore I thought it was a good idea to report it.

#### What is the current behavior?
Padding of 16px on the toolbar creates problem when you want to use buttons.

#### What are the steps to reproduce?
https://material2-dashboard.firebaseapp.com/

**Comment by DevVersion** [comment]
@Ploppy3 I might be blind, is there any specific picture that says that the padding should be `8px` instead?

Also are we only talking about the horizontal padding or also for the vertical?

**Comment by Ploppy3** [comment]
Ok, I'm gonna try to explain the issue as much I can, I'm not English, so please, forgive me.

First of all there is a work around, but in my opinion if it was done in a other way it would be way less annoying.

When people create toolbar, usually they will add buttons on sides. With the current behavior here is the result taken from your own dev app and it's far from being a counterexample as I've seen multiple people do it wrong too:

![image](https://cloud.githubusercontent.com/assets/7990765/23142377/f06c5b4c-f7bb-11e6-8b79-78999923ae7c.png)

And how it should be:

![image](https://cloud.githubusercontent.com/assets/7990765/23142392/fcc2aa4a-f7bb-11e6-9316-0c9bbb6df0cf.png)

I've done only 2 things to fix this:

- Changed the horizontal padding from 16px to 8px (nb: it also fixes the padding for the button on the far right not visible in the picture)
- Added an horizontal padding of 8px to the H1 title.

It's one way of doing it. But it's how it is described in the material guideline.

It seems logical to me that we should add padding, instead of removing it.

---

Maybe it's my OCD but... I wanna explain here how I work:
If you understand the explanation above and consider you fixed it, you'll notice that the only thing a dev has to do is to add an horizontal padding of 8px to the toolbar text.

---

Also I understand that if the current padding is OK if the toolbar has only text, but usually that's not how it works, either on the left or on the right you end up with icons.

**Comment by Ploppy3** [comment]
I will add that there is nothing that say the padding of the toolbar should be 8px.
What is said though is that the padding on sides and between elements should be 16px.
The current behavior is a 16px padding on sides, and md-icon-button have a 8px padding already.
So you end up with a 24px padding instead of 16px. Plus as many people do, you forget to add a 8px padding arround text and the result is even more wrong (see pictures above).

**Comment by DevVersion** [comment]
Ah I see what you mean with the `8px` in relation to the `md-icon-button` directive.

I just think it would be weird to change the horizontal padding to `8px` in favor of the `md-icon-button` directive. There will be so many different cases, where the margin will be incorrect for the `md-toolbar`.

The easiest would be just to follow the specs with the `16px` and letting the user decide.

**Comment by Ploppy3** [comment]
I understand the struggle and I can't find a solution to this problem but on the other side, I think that if we just put in the toolbar simple text and material components it should work without any trick and not give such a result.

**Comment by DevVersion** [comment]
Not really sure. We would need to overwrite styles for all components in the toolbar to have proper margins.

Polymer doesn't seem to take care of that either.

**Comment by Ploppy3** [comment]
@DevVersion Polymer is not Material2, you can chose to not do the same mistakes.

And I repeat, even your dev app has wrong toolbar padding. So it's clear to me that there is a problem.

**Comment by DevVersion** [comment]
@Ploppy3 Nobody said that Material 2 is Polymer. But when building libraries you do also consider other libraries like MDL, Polymer, M1 that may ran into similar issues. 

In our case, we would need to make adjustments for likely every-component to properly *look* in the `toolbar`.

We did this for Material 1, and the styles ended up in a miss. Styles like `margin-left: -8px` have been applied to work like a band-aid ([see styles](https://github.com/angular/material/blob/master/src/components/toolbar/toolbar.scss#L13))

I'm not against fixing this issue, I'm just careful with adding such thing..

**Comment by Ploppy3** [comment]
@DevVersion Alright, keep on improving this awesome framework.
