### ISSUE TITLE
Not working on cli project

### ISSUE THREAD

**Issue by xg-wang** [angular/material2#3200]
#### What is the current behavior?
It should work partly, but very incomplete.

#### What are the steps to reproduce?
ng new my-project
npm install -g @angular/cli@latest

then add module and add any component

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/cli: 1.0.0-beta.32.3
node: 6.9.4
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

**Comment by victorschinaider** [comment]
O think you need to put more details...

Show you core. Are you importing the module?

**Comment by mackelito** [comment]
I´m running this on a CLI project.. no issues here.. have a basic setup with no "hacks"

**Comment by Ploppy3** [comment]
A common issue is to forget to import the material theme.

https://material.angular.io/guide/theming

**Comment by xg-wang** [comment]
Sorry I forgot to import the theme.
