### ISSUE TITLE
The new beta version is breaking

### ISSUE THREAD

**Issue by SatyabratKumarSingh** [angular/material2#3203]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

Everything was working fine until I updated to beta.2 version

#### What is the current behavior?

Getting error "If 'md-input' is an Angular component and it has 'placeholder' input, then verify that it is part of this module"

#### What are the steps to reproduce?

Update to new version

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by mackelito** [comment]
When updating.. always read the release notes :)
https://github.com/angular/material2/releases/tag/2.0.0-beta.2

**Comment by SatyabratKumarSingh** [comment]
sorry.. Thanks a lot :)
