### ISSUE TITLE
Autocomplete optionSelections to return one observable rather than an array

### ISSUE THREAD

**Issue by christinakayastha** [angular/material2#3205]
#### Bug, feature request, or proposal:
It would be easier to consume optionSelections if it returned a single observable that streamed which option was selected rather than an array, or alternatively emitted a change event like mdSelect.

The modification would be to this function:
https://github.com/angular/material2/blob/master/src/lib/autocomplete/autocomplete-trigger.ts#L163

#### What is the expected behavior?
The user should be able to call
```
trigger.optionSelections.subscribe(optionSelected => {
    // do stuff with the selected option
})
```

or alternatively listen to a change event

#### What is the current behavior?
Currently, to listen to what option changed, I have to subscribe to each one of the observes in optionSelections[]

#### Is there anything else we should know?
You guys are awesome :D I love angular2 material!! 
:fireworks: Wooo autocomplete :fireworks:

**Comment by crisbeto** [comment]
FWIW, you can still do `Observable.merge(trigger.optionSelections)` to subscribe to all of them at once.

**Comment by sumpton** [comment]
Material2 is great. Thank you.

Is there an example of how to  use MdAutocompleteTrigger and optionSelections?

**Comment by crisbeto** [comment]
@sumpton you can query for it with `@ViewChild(mdAutocompleteTrigger)` which then gives you access to the option selections. We should probably do a separate change event at some point.
