### ISSUE TITLE
Material Icons Styling Sometimes Not Showing Up in Angular 2 App

### ISSUE THREAD

**Issue by darrenbrett** [angular/material2#3207]
My development environment:
@angular/cli: 1.0.0-beta.31
node: 7.4.0
MacBook Air
OS X El Capitan Version 10.11.6

I am using Angular Material elements in my Angular 2 project, and, for the most part, it's working as expected. However, occasionally when I load a page the material icon styling won't be applied. For instance, with this button:

`<button md-button (click)="onAddAddressClicked()">Add an address</button>`

Most of the time it loads correctly. But occasionally when I visit a page with this button, only the default browser styling will be applied, rather than the material styling. Not sure what's causing this. I have followed the material font/icon directions, and I am calling the link from my index file, like this:

```
<!doctype html>
<html>
<head>
    <base href="/">
    <title>APP</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="app/styles/app.styles.css">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
<app>Loading...</app>
</body>
</html>
```

Therefore, I'm not sure what the issue is. Again, most of the time the icons Angular2 material icons load as expected. But occasionally the styling isn't applied and I see the basic browser styling instead.

**Comment by shankar517** [comment]
Hi
Did u able to solve the issue..If Yes can you please guide how??
