### ISSUE TITLE
Template parse errors: Can't bind to 'placeholder' since it isn't a known property of 'md-input'

### ISSUE THREAD

**Issue by selem1** [angular/material2#3210]
#### Bug, feature request, or proposal:
I'd upgraded to **`@angular/material 2.0.0-beta.2`**, although `MaterialModule` is imported in the relevant module file , once launching the application, the `md-input` tag could not be recognized and the application throws the well known angular exception (mentioned in title). The weird part is it was running smoothly with the **`@angular/material 2.0.0-beta.1`** .

#### What is the current behavior?

```
Template parse errors:
Can't bind to 'placeholder' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'placeholder' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message....
```

#### Which versions of Angular, Material, OS, browsers are affected?

> @angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.30]
node: 7.5.0
os: linux x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

#### Is there anything else we should know?
There was no similar issues with `@angular/material: 2.0.0-beta.1`

**Comment by diicar** [comment]
md-input is no longer exists, please use mdInput instead

**Comment by selem1** [comment]
@diicar Thank you indeed, actually your comment is a bit misleading but it helps me.. Thanks a lot, infact it was deprecated really and switched by 

```
<md-input-container>
  <input mdInput placeholder="...">
</md-input-container>
```
where the `dividerColor="..."` is an attribute of the parent element `<md-input-container>` not its child (once used).

**Comment by ig16022** [comment]
This is a breaking change, is there a change log for beta1/beta2 switch?

**Comment by andrewseguin** [comment]
The changelog between releases is always updated in [CHANGELOG.md](https://github.com/angular/material2/blob/2.0.0-beta.2/CHANGELOG.md)

**Comment by ig16022** [comment]
Thank you @andrewseguin
