### ISSUE TITLE
Material Sample App - link is broken

### ISSUE THREAD

**Issue by svidlak** [angular/material2#3214]
#### Bug, feature request, or proposal:

https://material.angular.io/guide/getting-started
the example projects links are broken, as im just starting to learn angular and decided to go with Ng material over Bootstrap, please fix

**Comment by kara** [comment]
Yeah, we are definitely planning to fix. Track in existing issue, https://github.com/angular/material2/issues/3147.  In the meantime, the correct links are [here](https://github.com/angular/material2/blob/master/guides/getting-started.md)
