### ISSUE TITLE
Sidenav and Toolbar buttons are highlighed automatically

### ISSUE THREAD

**Issue by bm-software** [angular/material2#3215]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

When the sidenav is opened and the user move the cursor on one of buttons the first button is always highlighted automatically.

Moreover, when the sidenav is closed the menu button on the toolbar is highlighted automatically until the user click somewhere else.

#### What is the current behavior?

Highlights should be shown only if the user moves the cursor on button.

#### What are the steps to reproduce?

Plunker -> https://plnkr.co/edit/ve5Ez0WSinNyowxI46LO?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?

    "@angular/common": "2.4.7",
    "@angular/compiler": "2.4.7",
    "@angular/core": "2.4.7",
    "@angular/flex-layout": "^2.0.0-beta.4",
    "@angular/forms": "2.4.7",
    "@angular/http": "2.4.7",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "2.4.7",
    "@angular/platform-browser-dynamic": "2.4.7",
    "@angular/platform-server": "2.4.7",

**Comment by joh04667** [comment]
This is related to the `md-button` directive. The first `md-button` in the sidenav shows this behavior. As a workaround, you can set a 'dummy' anchor tag or button at the start of the sidenav with an `md-button` attribute, then set its height to 0 and position it absolutely. 

http://stackoverflow.com/questions/42442406/angular-2-material-sidenav-focus-on-the-first-navigation-item/42443947#42443947

**Comment by mmalerba** [comment]
Just looked into this. It's WAI that the sidenav focuses the first focusable element upon opening, though as @joh04667 pointed out the md-button is treating the programmatic focus from the focus-trap as a keyboard focus and applying the keyboard focus styling. I'll prepare a PR to switch md-button over to using the new FocusOriginMonitor which handles this edge case.

**Comment by joh04667** [comment]
@mmalerba just to be clear....it's WAI to have the keyboard focus only show up and stick to the first element when any `md-button` element is hovered over? And for it to lose keyboard focus when an empty space in the sidenav is clicked? This doesn't seem like a very good feature to me; the keyboard focus is not shown initially and is able to be removed trivially. 

Here's a simpler Plunker with that behavior: https://plnkr.co/edit/wPWpZINvhfhyhViXc9Jt?p=preview

**Comment by mmalerba** [comment]
It's WAI for the first focusable element in the sidenav to be focused when the sidenav is opened. However buttons should only have the darkened background style when they are focused via they keyboard (i.e. pressing tab).

**Comment by takahser** [comment]
2018 update: I'm still having this problem 1 year later, I was able to solve it using a variation of @joh04667's hacks, adapted to the current angular version.

- force the first button in the side nav to stay unfocused => still works
- force the menu button outside the side nav to stay unfocused => calling `_removeKeyboardFocus()` didn't work for me, instead I came up with the following hack

**template:**

```
<mat-sidenav #sidenav (close)="handleClose(menuButton)">
  <!--...-->
</mat-sidenav>
<mat-sidenav-content>
  <button #menuButton mat-icon-button (click)="sidenav.toggle()">
    <mat-icon>menu</mat-icon>
  </button>
  <!--...-->
</mat-sidenav-content>
```

**controller:**

```
  @ViewChild('menuButton') menuButton: MatButton;

  handleClose = (button: MatButton) => {
    // <any> needed to satisfy ts compiler, otherwise it won't allow accessing MatButton's private methods
    (<any>button)._focusMonitor.stopMonitoring(button._getHostElement());
  }
```

**Comment by Tyler-V** [comment]
Just noticed this as well... very odd behavior and definitely a bug we shouldn't have to account for

**Comment by drewpayment** [comment]
This might not be the best solution, but it seems like the easiest from what I have read. I just simply overrode the focus class (in my case, `.mat-list-item-focus`) to `background-color: inherit !important;` since it is just slightly changing the background color and isn't doing anything else. Then I made a custom class that I apply with `routerLinkActive`. 

Obviously, this only works assuming you're using Angular routing, but could easily be modified to suit your situation.

**Comment by lukegeor** [comment]
> 2018 update: I'm still having this problem 1 year later, I was able to solve it using a variation of @joh04667's hacks, adapted to the current angular version.
> 
> * force the first button in the side nav to stay unfocused => still works
> * force the menu button outside the side nav to stay unfocused => calling `_removeKeyboardFocus()` didn't work for me, instead I came up with the following hack
> 
> **template:**
> 
> ```
> <mat-sidenav #sidenav (close)="handleClose(menuButton)">
>   
> </mat-sidenav>
> <mat-sidenav-content>
>   <button #menuButton mat-icon-button (click)="sidenav.toggle()">
>     <mat-icon>menu</mat-icon>
>   </button>
>   
> </mat-sidenav-content>
> ```
> **controller:**
> 
> ```
>   @ViewChild('menuButton') menuButton: MatButton;
> 
>   handleClose = (button: MatButton) => {
>     // <any> needed to satisfy ts compiler, otherwise it won't allow accessing MatButton's private methods
>     (<any>button)._focusMonitor.stopMonitoring(button._getHostElement());
>   }
> ```
> Note that this is **still a hack**, so if someone knows a cleaner solution please, let me know!

IMO a better way to handle this is to put the stopMonitoring line in ngOnInit in the containing component. Remove the close handler, add the ViewChild variable to your containing component, and in ngOnInit call of the enclosing component, put (<any>menuButton)._focusMonitor.stopMonitoring(menuButton._getHostElement()); There's no need to call stopMonitoring every time you close the sidenav.

**Comment by stefanolsenn** [comment]
> 
> 
> so is this issue still open? I can see the same issue with what I am doing right now..

Yes, it's still a issue. You'll have to do the hacky ways in this thread to get around it. At least in 6.4.6. Haven't tested in version 7+

**Comment by zwand19** [comment]
I believe this is related to https://github.com/angular/material2/issues/10402? Found this thread via google long before that one and was stuck for a while.
