### ISSUE TITLE
Autocomplete and page scroll

### ISSUE THREAD

**Issue by FilipeQ** [angular/material2#3219]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Autocomplete options should stay near input

#### What is the current behavior?
Autocomplete options don't change css top property when we scroll on the page.
After scroll autocomplete options don't follow the input position.

#### What are the steps to reproduce?

https://plnkr.co/edit/I2TAghRrpbzmgQK5SsXd?p=preview

I use the material Docs plunker and add some fake scroll, to reproduce the problem.

**Comment by fxck** [comment]
None of the `Overlay` utilising components does. There's a PR for a solution that will block scrolling while any overlay is open, but https://github.com/angular/material2/pull/1971 either there's some problem with it or the assignee is busy.

**Comment by Ao21** [comment]
I got around it by sticking a scroll dispatcher on the body and updating the position manually as the user scrolls, but there are some issues on iOS safari with fixed positioning when the keyboards open.

**Comment by pabx06** [comment]
@fxck would you mind sharing the code that fix it ? having the same issue here

**Comment by dalemanthei** [comment]
It is perhaps a naive implementation but it seems like a stacking context would be one solution. What don't I get about what the overlay is providing?

**Comment by jelbourn** [comment]
Now tracking via #4093
