### ISSUE TITLE
Input background color

### ISSUE THREAD

**Issue by ashokacharya** [angular/material2#322]
how to change background color through attribute in md input

**Comment by ashokacharya** [comment]
why did you closed, i suppose its a issue for different background color for input boxes rather then white.and also changing the color of the placeholder text

**Comment by jelbourn** [comment]
@ashokacharya Please follow the issue template. This issue falls under "Request for support", which will be closed.

**Comment by ashokacharya** [comment]
if the background of the input be transparent ,and we can change the text and placeholder color with attribute value then it can be more productive for different designs

**Comment by ashokacharya** [comment]
@jelbourn so please i am stuck in the issue,i tried to change the components but i dont want to make its work flow dirty, where should i get the answer can you sent me the link for support

**Comment by ashokacharya** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7150475/14611995/af0f3790-05b4-11e6-8eb3-e8e069614a31.png)
@jelbourn

**Comment by jelbourn** [comment]
@ashokacharya The components are _really_ not production ready at the moment. You can still style individual elements with CSS, so something like 
```css
md-input input {
   /** whatever you want here */
}
```
would probably do what you want for now.

**Comment by ashokacharya** [comment]
Yes its working on ViewEncapsulation.None but not in Emulated .i think css load  after content is loaded or something, also for buttons theme doesnot work in emulated ,anyway thanks .i will make it work
