### ISSUE TITLE
md-card-reveal

### ISSUE THREAD

**Issue by AntiCZ** [angular/material2#3224]
Please implement the card reveal feature

http://demo.geekslabs.com/materialize/v2.1/layout02/ui-cards.html#card-reveal

**Comment by crisbeto** [comment]
We had another issue for this and I've tried looking into it. The issue is that the card reveal from Materialize isn't a part of the Material spec. There is something similar, however it ends up pushing other content down instead: https://material.io/guidelines/components/cards.html

**Comment by jelbourn** [comment]
This isn't something we plan on implemented in the near term.
