### ISSUE TITLE
Add focus styling for anchors in md-nav-list

### ISSUE THREAD

**Issue by kara** [angular/material2#323]

**Comment by traviskaufman** [comment]
The UX is similar to focus states for flat buttons. For example, we darken the list item's background on the spec site.
<img width="1199" alt="screen shot 2016-05-18 at 15 45 57" src="https://cloud.githubusercontent.com/assets/1185269/15377323/c380fb60-1d0f-11e6-9634-72de610ef722.png">

Where "Navigation" is active and "Loading Images" is tab focused.
