### ISSUE TITLE
bug(md-slide-toggle): selectable area gets 100% of container width

### ISSUE THREAD

**Issue by jefersonestevo** [angular/material2#3230]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
The selectable area from md-slide-toggle should fit to it's content

#### What is the current behavior?
md-slide-toggle gets 100% of the container width as selectable area

#### What are the steps to reproduce?
[Plunker](http://plnkr.co/edit/PF5nzeUhUbtCBbsw2utR?p=preview)

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/material" :"2.0.0-beta.2"

**Comment by DevVersion** [comment]
Note: This would be similar to the `md-checkbox`.
