### ISSUE TITLE
Input element with mdInput inside md-input-container does not display the placeholder when field is empty

### ISSUE THREAD

**Issue by rahulsethi-daffodilsw** [angular/material2#3235]
#### Input element with mdInput inside md-input-container does not display the placeholder when field is empty

Just started with Angular 2 and material design after working with material in React.js apps. First impression of angular/material2 does not seem to be good as it's React counterpart.

So here's what is happening... there is no grey placeholder when the input field is empty and unfocused. Please see the image below:
![angular2-md-bug](https://cloud.githubusercontent.com/assets/19944568/23203405/64291366-f908-11e6-9bb1-74b0c6327972.PNG)

It only jumps out above when the field is not empty or focused

![angular2-md-bug2](https://cloud.githubusercontent.com/assets/19944568/23203480/b76d51f4-f908-11e6-9ace-ef2c42d176e1.PNG)

Here is the code below:

```ts
import { Component } from '@angular/core';
import '../styles/styles.scss';

@Component({
  selector: 'my-app',
  template: `<div>
      <p>
      <md-input-container>
        <input mdInput placeholder="Name" />
      </md-input-container>
      </p>
      <p>{{name}}</p>
  </div>`,
})
export class AppComponent {
  title: string = 'Minimal Angular 2 setup with Webpack';
  name = null;
}
```

**Comment by benb7760** [comment]
Can you check your doctype? #3196

**Comment by rahulsethi-daffodilsw** [comment]
@benb7760 Thanks. Resolved. Thanks to @crisbeto for noticing.
