### ISSUE TITLE
Type casting error in input,checkbox,progressbar,sidenav

### ISSUE THREAD

**Issue by ashokacharya** [angular/material2#325]
why i am having this error

build\asset\material2\components\checkbox\checkbox.ts(93,19): error TS1110: Type expected.
build\asset\material2\components\checkbox\checkbox.ts(93,35): error TS1005: ';' expected.
build\asset\material2\components\input\input.ts(84,19): error TS1110: Type expected.
build\asset\material2\components\input\input.ts(84,35): error TS1005: ';' expected.
build\asset\material2\components\input\input.ts(132,19): error TS1110: Type expected.
build\asset\material2\components\input\input.ts(132,35): error TS1005: ';' expected.
build\asset\material2\components\input\input.ts(133,26): error TS1110: Type expected.
build\asset\material2\components\input\input.ts(133,56): error TS1005: ';' expected.
build\asset\material2\components\progress-bar\progress-bar.ts(73,9): error TS1110: Type expected.
build\asset\material2\components\progress-bar\progress-bar.ts(73,62): error TS1005: ';' expected.
build\asset\material2\components\progress-circle\progress-circle.ts(44,18): error TS1110: Type expec
ted.
build\asset\material2\components\progress-circle\progress-circle.ts(44,50): error TS1005: ';' expect
ed.
build\asset\material2\components\sidenav\sidenav.ts(46,19): error TS1110: Type expected.
build\asset\material2\components\sidenav\sidenav.ts(46,35): error TS1005: ';' expected.
build\asset\material2\components\sidenav\sidenav.ts(49,18): error TS1110: Type expected.
build\asset\material2\components\sidenav\sidenav.ts(49,43): error TS1005: ';' expected.
build\asset\material2\core\live-announcer\live-announcer.ts(10,34): error TS1110: Type expected.

**Comment by jelbourn** [comment]
@ashokacharya I am closing this because you are not following our issue template. Feel free to open a new issue when you can provide more information.
