### ISSUE TITLE
expose dialog close attempts

### ISSUE THREAD

**Issue by fxck** [angular/material2#3251]
context:

https://github.com/angular/material2/pull/2853#discussion_r98515217
https://github.com/angular/material2/pull/2853#issuecomment-276301986

will try to do it myself later next week, unless someone wants to take it ( @crisbeto )

**Comment by ggranum** [comment]
Dredging up some seriously old memories, I believe this was just called 'beforeClose' in ExtJS (and possibly others). Not a clue if they still use the paradigm, but many action events had 'beforeEVENT_NAME' versions that would abort the primary event if any of the 'before' listeners returned false. 

Not suggesting it is ideal for this case, just throwing out some existing terminology that jumped to mind. Looking forward to this feature, for the basically exact reasoning you mentioned - catching a close before it happens and updating a model. The model update has a validation step, meaning that I might need to prevent the close.

**Comment by fxck** [comment]
I don't know, `beforeClose` has the opposite problem of what @crisbeto [has](https://github.com/angular/material2/pull/3460#issuecomment-284670342), with `closeAttempt`.. if "attempt" implies fail, "beforeClose" pretty much implies success. I still think attempt fits better. Anyway I lost hope of that PR ever getting merged or reviewed anyway.

**Comment by ggranum** [comment]
It has the advantage of being prior art. A whole lot of people are familiar with ExtJs / Sencha. Perhaps `closeRequest` or `closeRequested` - but I don't think that improves on `closeAttempt`. 

The advantage of `beforeClose`, is that it is quite clear that it takes place before an actual close. It isn't as obvious that the close attempt isn't guaranteed to follow.

Just making noise. Could call it `perhapsClosingSoonMaybe` for all I care. I just want to be able to abort the close! I can see why you're frustrated.
