### ISSUE TITLE
Autocomplete IE 11 Compatibility

### ISSUE THREAD

**Issue by donduni** [angular/material2#3255]
#### Bug, feature request, or proposal:
Bug / IE 11 compatibility

#### What is the expected behavior?
1. Option selection via mouse
2. Correct initial placeholder position when input field empty
![image](https://cloud.githubusercontent.com/assets/14808357/23255511/32142d7a-f9bc-11e6-9213-4a0f8b789302.png)

#### What is the current behavior?
1. Option List select via mouse click doesn't write the selected option into the input field. (Works using arrow keys)
2. On init with no input value, the placeholder should place down
![image](https://cloud.githubusercontent.com/assets/14808357/23255547/534f6180-f9bc-11e6-8a26-992b2ca3508a.png)

#### What are the steps to reproduce?
The plunker example at the official documentation page.
https://material.angular.io/components/component/autocomplete

#### What is the use-case or motivation for changing an existing behavior?
Provide basic autocomplete functionality for IE 11.

#### Which versions of Angular, Material, OS, browsers are affected?
Internet Explorer 11 (11.576.14393.0)

**Comment by crisbeto** [comment]
These should've been fixed by https://github.com/angular/material2/pull/3188, https://github.com/angular/material2/pull/3190 and https://github.com/angular/material2/pull/3189.

**Comment by donduni** [comment]
Thanks  👍
