### ISSUE TITLE
Is it possible to only include imported material components to the bundle? 

### ISSUE THREAD

**Issue by marcorinck** [angular/material2#3258]
#### Bug, feature request, or proposal:
I'm using angular-cli beta.32 und angular-material 2 beta 2. Even when only import material components that are actually used in my templates, source-map-explorer is showing me, that all angular-material components are getting included in the bundle. 

I don't know if this is an angular-cli or webpack problem, I couldn't find this specific topic mentioned anywhere. #webpack/webpack

If this is due to the webpack tree-shaking problem ( https://github.com/webpack/webpack/issues/2867 ) feel free to close this issue. Its my first angular-cli project and I don't have much experience yet. 

#### What is the expected behavior?

Only include components in bundle that are used in components of the app.

#### What is the current behavior?

All components of angular-material are included

#### What are the steps to reproduce?

I have this component in my app, no other component is importing MaterialModule anywhere. The bundle produced by angular-cli still contains components like tabs, select, slider, etc. 

````
import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {TelefonanlageRoutingModule} from './telefonanlage-routing.module';
import {TelefonanlageComponent} from './telefonanlage.component';
import {
	MdButtonModule, MdCardModule, MdCoreModule, MdDialogModule
} from '@angular/material';
import {WarteschleifeCardComponent} from './warteschleife-card/warteschleife-card.component';
import {TagesstatistikComponent} from './tagesstatistik/tagesstatistik.component';


@NgModule({
	imports: [
		CommonModule,
		MdCoreModule,
		MdButtonModule,
		MdCardModule,
		MdDialogModule,
		// MaterialModule,
		TelefonanlageRoutingModule
	],
	declarations: [TelefonanlageComponent, WarteschleifeCardComponent, TagesstatistikComponent],
	entryComponents: [TagesstatistikComponent]
})
export class TelefonanlageModule {
}
````

#### What is the use-case or motivation for changing an existing behavior?

Smaller production bundles

#### Which versions of Angular, Material, OS, browsers are affected?

angular cli beta 32, angular material 2 beta 2, angulaer 2.4.8

**Comment by mmalerba** [comment]
I think this is a webpack issue that it doesn't get tree-shaken properly. I'm not sure there's much we can do about it from the material side unfortunately.
