### ISSUE TITLE
material2 not support input file upload

### ISSUE THREAD

**Issue by rubinus** [angular/material2#3262]
Input type "file" isn't supported by md-input-container.

**Comment by mmalerba** [comment]
This is not currently on our roadmap

**Comment by HoumanKml** [comment]
I was looking for the same; however, the workaround is simple: use a md-button to trigger a hidden input:

```
  <button type="button" md-button (click)="imgFileInput.click()">Add a photo</button>
  <input hidden type="file" #imgFileInput (change)="previewImage($event)"/>
```

**Comment by maxime1992** [comment]
That's what I ended up using @HoumanKml. Another problem is to do that with reactive forms, but that's another story :+1:

**Comment by merlosy** [comment]
Since it isn't (anf will not be) part of the roadmap, I made my own
Gist here:  https://gist.github.com/merlosy/ab33dd7edaacfd92d6c9a5daea0a1240
Working fine on Angular 4.3.x
Feedback appreciated :)

**Comment by maxime1992** [comment]
Don't have the time to try it out right now but thx for sharing @merlosy!
Also, if you have the time it might be nice to create a demo on [stackblitz], plunkr or other :)
:beers:

**Comment by nni123** [comment]
@HunderlineK 

Style the button for 4.4.3 & material 2 build 12 (real pain to keep up with breaking changes...hate angular sometime)

`     <div class="button-row">
      <button mat-button color="accent" mat-mini-fab (click)="imgFileInput.click()"><mat-icon>attachment</mat-icon></button>
      <input hidden type="file"  #imgFileInput (change)="previewImage($event)"/>
    </div>`

`.example-button-row {
  display: flex;
  align-items: center;
  justify-content: space-around;
}`

**Comment by merlosy** [comment]
Based on the [new guidelines](https://material.angular.io/guide/creating-a-custom-form-field-control), I updated my gist with custom input file working with Angular 4.4.x + Material Beta 12

https://gist.github.com/merlosy/ab33dd7edaacfd92d6c9a5daea0a1240

**Comment by merlosy** [comment]
@maxime1992 Plunker here: http://plnkr.co/edit/VGCSprNVT1pobOxjWwmT?p=preview

**Comment by nni123** [comment]
@merlosy nice update thanks

**Comment by misamae** [comment]
@merlosy thanks for sharing. The referenced plunker is not loading.

**Comment by merlosy** [comment]
@misamae updated for Angular 5 and material 5.0.0-RC.0:
http://plnkr.co/edit/VGCSprNVT1pobOxjWwmT?p=preview

**Comment by DJHightower** [comment]
Hey merlosy. I like your control.
Just having some problems combining it with drag&drop (i am using https://valor-software.com/ng2-file-upload). Could not get your control to accept the dropped file(s) as a valid model. I tried adding the files into FileInput instance bound via [(ngModel)] - but your Control isnt recognizing/showing them. Mabe some time you are in a mood to to do a little improvement in this direction.

**Comment by matheusdavidson** [comment]
nice solution @merlosy

**Comment by rvalenciano** [comment]
Hey @merlosy your latest plnkr is not loading anymore :(

**Comment by jdlopezq** [comment]
i have a problem show the file in the placeholder...

**Comment by merlosy** [comment]
Ill look into it. Ill post an update here when it's fixed :)

**Comment by rvalenciano** [comment]
Thanks, @merlosy for your idea, I made it work for my app but it would be good that the plunkr is working also :) It seems like there is a broken script.

**Comment by merlosy** [comment]
Plunker is working again! 
https://plnkr.co/edit/VGCSprNVT1pobOxjWwmT?p=preview

The code didn't changed, just broken imports since release of Material 5.0.0

**Comment by marklagendijk** [comment]
@merlosy nice! You should publish it as a module on Github and NPM.

**Comment by kamok** [comment]
@HunderlineK Your solution auto focuses the initial button that calls the hidden button when you finish uploading. Do you have any idea to get out of the focus?

**Comment by HunderlineK** [comment]
@kamok I haven't worked with angular in a long time, but I suppose you can monitor the status of the file upload event and then after the upload do whatever you like to do, or maybe use merlosy's solution, It seems more robust to me

**Comment by merlosy** [comment]
@marklagendijk Your wish has been real: https://github.com/merlosy/ngx-material-file-input
It has a few bug fixes. It should support jit, aot, and different kind of imports.
Still a lot I want to do, but one step at a time... Feedback is welcome!

**Comment by MoazzamAlyKhan** [comment]
Hi!

I'm getting this error on using @merlosy 's solution

 ```
Uncaught (in promise): Error: StaticInjectorError(AppModule)[FileInputComponent -> NgControl]: 
  StaticInjectorError(Platform: core)[FileInputComponent -> NgControl]: 
    NullInjectorError: No provider for NgControl!
```

Help will be appreciated!

**Comment by leonlovett** [comment]
The solution suggested by @HunderlineK is working perfectly for me. I went ahead and put together a simple Stackblitz sample.
https://stackblitz.com/edit/angular-material-file-upload

**Comment by AmandavZ** [comment]
IMHO, I think the concern here is not so much about functionality, but about consistency, standardization, and staying within the angular material framework and guidelines. File upload form type  is included in most of the standard forms solutions/libraries today. I do think this requires reconsideration

**Comment by alignsoft** [comment]
I've just stumbled over this after having the same issue with Angular 7 _without using Material_ where `<input type="file" #fileInput...>` no longer presents a 'select file' dialog since a recent upgrade of Angular. I'm on 7.1.3 now, and this has worked recently, but I can't say exactly when it stopped.

Using the `(click)="fileInput.click()"` method on the button solves the issue, but I'm unclear what changed to break this behaviour, and whether this is a bug that should be filed with the general Angular team as it doesn't seem to be specific to Material.

**Comment by danieldanielecki** [comment]
Any updates on this? Why this has been closed?...
