### ISSUE TITLE
Input and select doesn't align properly

### ISSUE THREAD

**Issue by ask007java** [angular/material2#3263]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
input and select field should align properly.

#### What is the current behavior?
not aligning properly

#### What are the steps to reproduce?
http://plnkr.co/edit/1wxJSEEYXSvVGikCIq33?p=preview

**Comment by kara** [comment]
Definitely a bug, but already being tracked here:

https://github.com/angular/material2/issues/2124
