### ISSUE TITLE
Cannot set focus on an element after side nav opens

### ISSUE THREAD

**Issue by sieggynagel80305** [angular/material2#3265]
#### Bug, feature request, or proposal:
Setting focus on an alternate element in the menu does not work.

#### What is the expected behavior?
That calling focus on an element should allow said element to have focus.

#### What is the current behavior?
Currently trying to set focus on an anchor element inside of the Promise returned from open() or in the open event of MdSideNav fails.  The focus is reset afterwards to the first element in the tab order.

#### What are the steps to reproduce?
The menu contains a button as the first element and set of anchor tags afterwards.  Inside of either the open()'s Promise then method or the open event handler, try and set focus on one of the anchor tags.  The focus will return the the button (the first element).

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Client request to be able to choose the first anchor tag as having focus.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2, Material 2.

#### Is there anything else we should know?
The functionality to do this appeared to be Material v1.

**Comment by mmalerba** [comment]
I believe this is because the focus-trap is setting the focus after the sidenav opens, you can tell the focus-trap where to start by adding the cdk-focus-start attribute to the element you want to be initially focused (https://github.com/angular/material2/blob/master/src/lib/core/a11y/focus-trap.ts#L56)

**Comment by sieggynagel80305** [comment]
Thanks!

**Comment by sieggynagel80305** [comment]
When testing it more it looks like it starts the tab order (and focus) from the desired control but removes previous controls from the tab order.  Is this expected?  Is there a way of using the directive without losing controls from the tab sequence?

**Comment by mmalerba** [comment]
@sieggynagel80305 I'm not really sure what you mean. When the sidenav is open it traps the focus within the sidenav, that part is expected. If you're talking about something else please provide a plunker to reproduce it

**Comment by sieggynagel80305** [comment]
@mmalerba I'll have to put one together to show you.  The element in question captures the focus as you set it would.  However, there is another control that preceded it in tab order and that control has been removed from being tab accessible.

**Comment by PierreChavaroche** [comment]
FYI, "cdk-focus-start" is depricated, use "cdk-focus-region-start" instead.
