### ISSUE TITLE
md-input placeholder not floating after updating value from component

### ISSUE THREAD

**Issue by jorgeriv** [angular/material2#3276]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Placeholder text should float above the input text

#### What is the current behavior?
Input text overlaps placeholder text when updated from ```form.controls['control'].setValue('new value')```

#### What are the steps to reproduce?

just update a value using model driven forms

#### What is the use-case or motivation for changing an existing behavior?
<img width="1067" alt="bug" src="https://cloud.githubusercontent.com/assets/528606/23287942/26fb6684-fa06-11e6-99ba-c131cb690148.png">

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/core": "^2.1.0",
"@angular/material": "2.0.0-beta.1",

#### Is there anything else we should know?

**Comment by kara** [comment]
@jorgeriv It looks like you're using beta.1.  This was fixed in our last release, so if you upgrade to beta.2, it should fix your problem.

**Comment by jorgeriv** [comment]
Thank you, I just upgraded to beta.2 and it fixed it.

 Just want to mention for anyone facing this problem in the future, you have to manually trigger the change detection mechanism after filling your form for this to work.

**Comment by bohao-cao** [comment]
@jorgeriv do you have a code example for manually trigger the change detection? I'm facing the similar issue. Thanks!
