### ISSUE TITLE
Proposal: md-select direct options data wiring for better startup time

### ISSUE THREAD

**Issue by mbellezi** [angular/material2#3277]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
For more the one hundred itens, md-select should not be slow.

#### What is the current behavior?
For 200 itens, the md-select startup time is 150ms on desktop and nearly 1s on mobile. Even with AOT is slow.

#### What are the steps to reproduce?
Create a md-select with 200 itens or more.

#### Is there anything else we should know?
The md-select options could be wired directly using one @Input that takes one array of label/value objects. This could be used to speedup startup as one do not have process and iterate through the md-option array.

**Comment by kara** [comment]
The select needs virtual repeat for long lists, which still hasn't been implemented. That should improve perf: https://github.com/angular/material2/issues/823. Closing this one as a dupe to track in the other one.

**Comment by mbellezi** [comment]
I understand but there are two phases here. One is instantiate and parse all md-option components and the other is the render itself.
I'm proposing to bypass this first phase when you want a simple Label/value list. Why do all the processing to build a list of label/value pairs when you could (optionally) pass it in as a @Input?
