### ISSUE TITLE
Duplicated Material modules in aot generaed lazy load chunk files (Angular CLI)

### ISSUE THREAD

**Issue by bboehm86** [angular/material2#3283]
#### Bug, feature request, or proposal:
I've taken a look at my (lazy load) chunk files generated by Angular CLI (`--prod` so with aot) and I wonder why do I have the used material components also in there floating around when they are already in the `vendor.bundle` file?
Is this an issue on Material side, Angular CLI or it's just the way it has to be?

---
#### Lazy load chunk 1
![mat-chunk1](https://cloud.githubusercontent.com/assets/1027091/23300589/8354f6e0-fa86-11e6-9e37-3983fe24bd61.PNG)
---
#### Lazy load chunk 2
![mat-chunk2](https://cloud.githubusercontent.com/assets/1027091/23300590/86cf3c0e-fa86-11e6-8d74-77ab07903dc6.PNG)
---
#### Vendor bundle
![mat-vendor](https://cloud.githubusercontent.com/assets/1027091/23300731/35d4a824-fa87-11e6-8621-f7694c901590.PNG)

#### What is the expected behavior?
Don't duplicate the Material modules throuh the app - at least not the styles.

#### What is the current behavior?
Every `chunk` gets the modules (& css) for the md components that it components use added

#### What are the steps to reproduce?
Plunker won't do it so i've added a repo. 
[https://github.com/bboehm86/mat-chunk-test](https://github.com/bboehm86/mat-chunk-test)

- You'll need `@angular/cli@1.0.0-beta.32.3`
- [source-map-explorer](https://github.com/danvk/source-map-explorer) might be helful (run `npm run build` to generate files with sourcemaps)

#### What is the use-case or motivation for changing an existing behavior?
smaller chunk sizes

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.x, Angular CLI 1.0.0-beta.32.3, all Material versions

#### Is there anything else we should know?
That is probably not related and a webpack issue.. but in the `vendor.bundle` everything for Material gets inclued no matter what. The only way to prevent that is to include just the modules we use. On both, our `app.module` and then in every module that uses a component

**Comment by CarmenPopoviciu** [comment]
I'm experiencing the same since updating to material `v2.0.0-beta.3`.

**Comment by M-Adoo** [comment]
same for me.

**Comment by bboehm86** [comment]
I'm closing this since it seems to be resolved with the latest Angular CLI release (1.1.0-rc.1)

**Comment by kblestarge** [comment]
@bboehm86 are you sure that version of the Angular CLI fixes this issue? I'm still seeing duplicate material modules in my lazy-loaded bundles...
![screen shot 2017-06-13 at 12 53 58 pm](https://user-images.githubusercontent.com/11730298/27099216-79c679bc-5037-11e7-87a0-b2e1db7bf973.png)
Look at all of the material.es5.js areas.

**Comment by kblestarge** [comment]
It looks like my material module is not in the vendor bundle. Maybe that'll fix it if I get it in there. How do you get it in the vendor bundle?

**Comment by kblestarge** [comment]
Alright, I added the material module to the imports on the app.module.ts file, which fixed the duplication of material.es5.js in each bundle, however, I'm still seeing the index.ngfactory.ts file showing up in most of the modules:
![screen shot 2017-06-13 at 1 43 04 pm](https://user-images.githubusercontent.com/11730298/27101321-887de998-503e-11e7-9539-62ae55ac8eb5.png)
Should I be worried about that?

**Comment by evanjmg** [comment]
What about those who don't use the cli? I don't see any changes with the latest update to @angular/compiler-cli

**Comment by bboehm86** [comment]
@kblestarge I've updated the example to the latest versions. I didn't get the **index.ngfactory.ts** inside the `chunk` files but in the `vendor.bundle.js`...  all this seems to be more a tooling issue than a material one.

@evanjmg I honestly don't know since I'm just using the CLI

**Comment by kblestarge** [comment]
@bboehm86 I'm seeing the node_modules>@angular>material>typings>index.ngfactory.ts files in nearly all of my chunks and not in my vendor.bundle.js. Are you saying this is by design?

**Comment by bboehm86** [comment]
@kblestarge it should be just inside the `vendor.bundle.js` not in your chunks. You might want to check how you `import` your NgModules. The `MaterialModule` is deprecated so just import the NgModules that you actually use **or** create a separate NgModule that imports all the Components that you need (take a look at the [Getting Guide](https://material.angular.io/guide/getting-started#step-3-import-the-component-modules) or at the demo app from my first post)

**Comment by kblestarge** [comment]
@bboehm86 this is what my custom-ng-materials.module.ts file looks like:
```
import {MdButtonModule, MdCheckboxModule, MdInputModule, MdSelectModule, MdCardModule} from '@angular/material';
import {NgModule} from "@angular/core";

@NgModule({
    exports: [
        MdButtonModule,
        MdCheckboxModule,
        MdInputModule,
        MdSelectModule,
        MdCardModule,
    ],
})
export class CustomNgMaterialsModule { }
```
This module is then imported into each module that has declared components using any of these material components.
I think I'm doing everything correctly according to the Getting Started Guide and your demo app. What do you think is the problem?

**Comment by GeorgeKnap** [comment]
This happens to my apps too. 
`index.ngfactory.ts` is in all of my lazy loaded chunks. `material.es5.js` is only in vendor chunk.
![material](https://user-images.githubusercontent.com/11920691/28733422-5896a2bc-73dc-11e7-8e1e-7c0f766d1a57.png)

**Comment by CarolLevesque** [comment]
Still having the same issue. index.ngfactory.ts files are in app and chunk but not in vendor.
I'm only importing what I need. I can't seem to find anybody else mentioning this issue anywhere else but here.
