### ISSUE TITLE
md-select falls out of screen (app component)

### ISSUE THREAD

**Issue by kootenpv** [angular/material2#3285]
the options of md-select fall out of screen

a cdk-overlay-container div jumps outside of <app-root></app-root> how is this possible?

**Comment by crisbeto** [comment]
Can you post a Plunkr showing the issue? You can use this as a template http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by bboehm86** [comment]
You probably forgot to import the theme/core styles

-> [https://material.angular.io/guide/theming](https://material.angular.io/guide/theming)

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by kootenpv** [comment]
@bboehm86 That indeed fixes it! I'm really confused how that could be the case, I cannot find any information on it!
