### ISSUE TITLE
[Tooltip] Allow global configuration of delays

### ISSUE THREAD

**Issue by vasslehel-c** [angular/material2#3286]
#### Feature request, or proposal:
Allow global configuration of tooltip show/hide delay

#### What is the expected behavior?
Configuring the show/hide delay of tooltips through a provider

#### What is the current behavior?
Every tooltip have to be configured individually

#### What is the use-case or motivation for changing an existing behavior?
Instead polluting the markup and changing tens of tooltips, it would be nice to have a mechanism to configure delays globally.

**Comment by CDDelta** [comment]
This is already possible by providing a [MatTooltipDefaultOptions](https://material.angular.io/components/tooltip/api#MatTooltipDefaultOptions) with the token `MAT_TOOLTIP_DEFAULT_OPTIONS`. [See here](https://material.angular.io/components/tooltip/overview#showing-and-hiding).

**Comment by tmakin** [comment]
This was working form me in 5.0.3 but seems to have disappeared from 5.0.4. There is also no mention of `MatTooltipDefaultOptions` in the docs referenced by @CDDelta?

**Comment by narendrasinghrathore** [comment]
@andrewseguin 
Facing error while import 
import {MAT_TOOLTIP_DEFAULT_OPTIONS, MatTooltipDefaultOptions} from '@angular/material';

/node_modules/@angular/material/material"' has no exported member 'MatTooltipDefaultOpti
ons'.
/node_modules/@angular/material/material"' has no exported member 'MAT_TOOLTIP_D
EFAULT_OPTIONS'.

**Comment by andrewseguin** [comment]
Seems to be working on this reproduction: https://stackblitz.com/angular/jydgypqvqvk?file=app%2Ftooltip-modified-defaults-example.ts

**Comment by narendrasinghrathore** [comment]
@andrewseguin 
why i am getting same ? 
**package.json**
`"@angular/animations": "5.0.0",
    "@angular/cdk": "5.0.0",
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/material": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@angular/router": "5.0.0",`


`"@angular/cli": "1.6.6",
    "@angular/compiler-cli": "5.0.0",
    "@angular/language-service": "5.0.0",
    "@types/jasmine": "2.5.53",
    "@types/jasminewd2": "2.0.2",
    "@types/node": "6.0.60",


`
![image](https://user-images.githubusercontent.com/4208015/37820208-f6f2b9c6-2ea5-11e8-9be3-4438f0a6ad89.png)

**Comment by edertxodw** [comment]
Hi!

That worked for me:
```
export const customTooltipDefaults: MatTooltipDefaultOptions = {
    showDelay: 100,
    hideDelay: 100,
    touchendHideDelay: 100
}

@NgModule({
    imports: [
        ...    
    ],
    exports: [
        ...
    ],
    providers: [
        { provide: MAT_TOOLTIP_DEFAULT_OPTIONS, useValue: customTooltipDefaults }
    ]
})
export class AppModule { }
```
