### ISSUE TITLE
md-card-title overlaps when text is too long

### ISSUE THREAD

**Issue by emreavsar** [angular/material2#3288]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Expected behaviour would be that the elements below the title will expand and no overlap happens

#### What is the current behavior?
the title overlaps the elements below

#### What are the steps to reproduce?
See the plunkr below of the official example for md-card from https://material.angular.io/components/component/card where I just added a bit longer text for the md-card-title.

https://embed.plnkr.co/ub7P6byKCe30PNMiu2r1/

#### What is the use-case or motivation for changing an existing behavior?
when using the md-card in a dynamic way (lets say a http call and showing the response in md-cards), one should be not dependent on the length of the title. (no manual margins desired)

#### Which versions of Angular, Material, OS, browsers are affected?
see plunkr

#### Is there anything else we should know?
this applies also when using a bigger font-size and also on other elements.

**Comment by keshavlingala** [comment]
**simple fix** use bootstrap class h-100
