### ISSUE TITLE
Cannot override themes with beta.2

### ISSUE THREAD

**Issue by armache** [angular/material2#3296]
Hello,

I updated @angular/material to 2.0.0-beta.2 and now cannot override themes. The error message is below:

![image](https://cloud.githubusercontent.com/assets/22368645/23324992/99472d7a-fae9-11e6-9299-b7f9a8501944.png)

I was following the example from this website - $candy-app-theme

**Comment by Nikki1993** [comment]
could you post the whole code? the themes file and how you add it in angular-cli.json?

**Comment by armache** [comment]
Hi Nikki and thanks for reply.

I am not using angular-cli. My test.scss file is below. Once I run node-sass command to compile into css, I am getting the exception above. Let me know if you need more information. 


//scss code
@import 'node_modules/@angular/material/core/theming/all-theme';

@include mat-core();

$candy-app-primary: md-palette($mat-deep-orange);
$candy-app-accent:  md-palette($mat-deep-orange, A200, A100, A400);


$candy-app-warn: md-palette($mat-red);

$candy-app-theme: md-light-theme($candy-app-primary, $candy-app-accent, $candy-app-warn);

@include angular-material-theme($candy-app-theme);

**Comment by Nikki1993** [comment]
Sorry my bad for assuming you were using cli CLI :D 

@armache instead of `md-pallete` use `mat-palette` aka

@import 'node_modules/@angular/material/core/theming/all-theme';

```
@include mat-core();

$candy-app-primary: mat-palette($mat-deep-orange);
$candy-app-accent: mat-palette($mat-deep-orange, A200, A100, A400);

$candy-app-warn: mat-palette($mat-red);

$candy-app-theme: mat-light-theme($candy-app-primary, $candy-app-accent, $candy-app-warn);

@include angular-material-theme($candy-app-theme);
```

**Comment by brandondtran** [comment]
Omg thank you Nikki1993

I hate angular_cli

**Comment by armache** [comment]
Thanks @Nikki1993 !!! Problem solved.

**Comment by dahaupt** [comment]
@armache You can close this issue yourself when it is solved :)
