### ISSUE TITLE
mdSidebar

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#33]
- [ ] Responsive by default
- [x] RTL support
- [x] Unit tests
- [ ] E2E tests
- [x] Documentation
- [x] Demo

**Comment by hansl** [comment]
I'll mark this done once we have full support, unless @jelbourn you're okay with what's there currently.

**Comment by jelbourn** [comment]
Closing this issue for the initial implementation, going to file separate issues for remaining tasks.
