### ISSUE TITLE
support md-input readonly attribute

### ISSUE THREAD

**Issue by ribizli** [angular/material2#330]
**Note: for support questions, please use one of these channels:**
https://github.com/angular/material2/blob/master/CONTRIBUTING.md#question.
This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
attribute readonly is not supported and not transfered to the wrapped input element

* **If the current behavior is a bug,
please provide steps to reproduce and if possible a minimal demo of the problem**
via https://plnkr.co or similar.

* **What is the expected behavior?**
support readonly attribute

* **What is the motivation / use case for changing the behavior?**
one might need this feature from html input element

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.
all, feature not implemented

* **Other information**
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by alexandrejunges** [comment]
Is anybody working on a PR for this?
I want to start helping with AM2 development and think this issue would be a nice start.

**Comment by matthewdenobrega** [comment]
I've taken a stab at fairly comprehensive input attribute support in #343.

**Comment by jelbourn** [comment]
Closed via #447
