### ISSUE TITLE
In Slide toggle Ripple doesnt hide automatically

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#3303]
When we click Slide Toggle it shows a ripple effect similar to other components such as Checkboxes and Radio button. But in case of Slide Toggle the ripple effect (filled circle) doesn't hide automatically as it hides in case of Checkbox and Radio.

It can also be noticed in the Angular 2 Matierial samples.  Just click Slide Toggle in below link and notice the ripple.

https://material.angular.io/components/component/slide-toggle

#### Which versions of Angular, Material, OS, browsers are affected?

The issue exists on previous versions as well but I have recently tested it on latest version:

Angular 4.0.0-rc.1 
Angular Material 2.0.0-beta.2

**Comment by DevVersion** [comment]
Thanks for the report. This is not the real ripple effect. It's the old focus indicator and shows as long as the slide-toggle is focused. 

The slide-toggle uses the ripple service since SHA https://github.com/angular/material2/commit/8541f8e351c1ae8b87a061236d0dbb8b23f1d728

**Comment by naveedahmed1** [comment]
@DevVersion thank you for your reply. Shouldn't the behavior be consistent across all components I mean I don't see such focus effect on Checkbox or Radio. And if the objective is to show that the item is focused, shouldn't the Focused and Clicked effects be difference from each other?

**Comment by DevVersion** [comment]
Yeah definitely. To make the components consistent the slide-toggle now uses the real ripple service since SHA 8541f8e.

And the focus indicator will be added soon as well to all those components.

**Comment by naveedahmed1** [comment]
Sounds great! What about making the focus effect different than the click/tap effect?
