### ISSUE TITLE
Custom Palette With AoT

### ISSUE THREAD

**Issue by rsnider19** [angular/material2#3305]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I should be able to use AoT compilation with custom palettes.

#### What is the current behavior?
AoT compilation fails because it is unable to find the theme files.

```
@import '~@angular/material/core/theming/_all-theme.scss';

// and getting this error:
Compilation failed. Resource file not found: C:/ng2-app/src/~@angular/material/core/theming/_all-theme.scss
```

I also tried changing to a relative reference:
```
@import '../node_modules/@angular/material/core/theming/_all-theme.scss';

// and getting this error:
Compilation failed. Resource file not found: C:/ng2-app/node_modules/@angular/material/core/core
```

#### What are the steps to reproduce?
Follow the steps for adding a custom theme (), and the steps for adding AoT.

#### What is the use-case or motivation for changing an existing behavior?
Fixing this will allow people to take advantage of AoT compilation as well as using custom templates.

#### Which versions of Angular, Material, OS, browsers are affected?
@angular 2.4.7
@angular/material 2.0.0-beta.2
Windows 10
Chrome

#### Is there anything else we should know?
Most likely the same issue as #3001

**Comment by Nikki1993** [comment]
Hm, can't reproduce when creating a project with angular-cli and using `ng serve --aot` My custom themes file it being used correctly.

**Comment by rsnider19** [comment]
I'll try creating a new cli project. Maybe it is something with my setup.

**Comment by kamarouski** [comment]
It should be 

```
@import "~@angular/material/core/theming/all-theme"
```
Works without issues in my project.

**Comment by kara** [comment]
This seems like an issue with the project setup.  Try the path @kamarouski suggested above.

**Comment by NgSculptor** [comment]
@kara I followed the exact steps listed here https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

the app works before adding material, but once I do, i get compile error

Compilation failed. Resource file not found: ~@angular/material/core/theming/all-theme
