### ISSUE TITLE
Can't get theming to work at all!

### ISSUE THREAD

**Issue by brandondtran** [angular/material2#3306]
I'm creating an electron app using Angular 2, but I can't seem to get the styling to work.

Here is my theme.scss file:
`@import '../../node_modules/@angular/material/core/theming/_all-theme.scss';
@include mat-core();
$primary: mat-palette($mat-orange, 800);
$accent:  mat-palette($mat-light-blue, 600, A100, A400);
$warn:    mat-palette($mat-red, 600);
$theme: mat-light-theme($primary, $accent, $warn);  
@include angular-material-theme($theme);`

I compile it into a css file with sass.

Here is the result of a modal dialogue with inputs:
![theme_bug](https://cloud.githubusercontent.com/assets/5573648/23338320/89501eda-fbbc-11e6-805a-189055a5347d.png)

**Comment by MathRobin** [comment]
Similar problem for me. What was the solution?

**Comment by dahaupt** [comment]
@MathRobin Have you already read the [theming guide](https://github.com/angular/material2/blob/master/guides/theming.md)?

**Comment by MathRobin** [comment]
Not working

**Comment by kamarouski** [comment]
That's my setup that works so far

```
@import '~@angular/material/core/theming/all-theme';
@include mat-core();

$app-primary: mat-palette($mat-blue-grey);
$app-accent:  mat-palette($mat-amber);
$app-warn: mat-palette($mat-red);
$app-grey: mat-palette($mat-grey);


$app-theme: mat-light-theme($app-primary, $app-accent, $app-warn);

@include angular-material-theme($app-theme);
```

**Comment by MathRobin** [comment]
Thanks !
