### ISSUE TITLE
md-spinner and md-progress-circle determinate should allow to display value/content in-between the circle with defined width

### ISSUE THREAD

**Issue by micronyks** [angular/material2#3307]
#### Bug, feature request, or proposal:
No sure. But I think its a feature request if not present. Excuse me if these features are already present.

#### What is the expected behavior?

```
     <md-progress-circle class="col-xs-4" mode="determinate" value="+{{(hours*100)/60}}">
          {{hours}} hours
      </md-progress-circle>
       
      <md-progress-circle class="col-xs-4" mode="determinate" value="+{{(minutes*100)/60}}">
          {{minutes}} minutes
      </md-progress-circle>
      
      <md-progress-circle class="col-xs-4" mode="determinate" value="+{{(seconds*100)/60}}">
          {{seconds}} seconds
      </md-progress-circle>
```

1) With respect to above code, it should display content that has been placed in-between `md-progress-circle` tag. I want to put other things in-between the circle as well with style.

2) it should also allow to define size(width and height) of `md-prorgess-circle` defined with `class='col-xs-4'`.

#### What is the current behavior?
1) Content is there still it doesn't display anything. 

2) it doesn't  expand itself according to given class `class="col-xs-4"` .

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

**https://plnkr.co/edit/t2DA6YS6RRCDL1AwmMTA**

#### What is the use-case or motivation for changing an existing behavior?

I believe that white space circle should be used appropriately to display content if any. I want to use `angular2-material-progress bar circle` with mentioned functionalities. 

#### Which versions of Angular, Material, OS, browsers are affected?
Latest Angular2 and material version. All browsers.

#### Is there anything else we should know?
Not sure.

**Comment by crisbeto** [comment]
There's a pending PR for it: https://github.com/angular/material2/pull/1994
