### ISSUE TITLE
md-input autocomplete attribute not supported

### ISSUE THREAD

**Issue by msegers** [angular/material2#331]
* **Do you want to request a *feature* or report a *bug*?**
I feel it's a bug but some might refer to it as a feature

* **What is the current behavior?**
When you have an md-input with an empty ngModel / value, autocomplete kicks in, but can't be disabled;

so in my case I have an "create user" form, where the username & password fields are present.
I cannot disable autocomplete, so my input shows my own username & password

* **If the current behavior is a bug,
I don't think it's worth doing so, the attribute is just not available on md-input in the source.

* **What is the expected behavior?**
can create <md-input autocomplete="off"></md-input> types.

* **What is the motivation / use case for changing the behavior?**
I believe it is essential.

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Should affect everything since introduction of md-input that would be Alpha-2

Did this work in previous versions of Angular / Material? Nope impossible

**Comment by matthewdenobrega** [comment]
@jelbourn a couple of questions for all of these input attributes:
 - do they all get added as @Input()'s on md-input?
 - does there need to be any checking for types? So max and min are not copied onto the wrapped input for type=text?
 - should there be a unit test per attribute? Or one unit test covering all the attributes?

**Comment by matthewdenobrega** [comment]
I've taken a stab at fairly comprehensive input attribute support in #343.

**Comment by jelbourn** [comment]
CLosed via #447
