### ISSUE TITLE
tsconfig.json module setup

### ISSUE THREAD

**Issue by sebastianhaas** [angular/material2#3310]
I was taking a look at this project's `tsconfig.json` configuration and I was wondering why `module` is set to `es2015` with `target` being `es5`.

From the [typescript documentation for the `module` flag](https://www.typescriptlang.org/docs/handbook/compiler-options.html):
> "ES6" and "ES2015" values may not be used when targeting "ES5" or lower.

Is this intended?

**Comment by hansl** [comment]
Hi Sebastian,

This is used to generate ESM/ES2015 import statements next to ES5 code. Many bundlers (like Rollup and webpack) understands the ESM imports syntax and will downlevel it themselves and tree shake efficiently. If we were to use another value for the `module` flag, like CommonJS or UMD, those would not be able to tree shake efficiently. If you use a bundler and point to the ES5 code + ES2015 modules, it results in smaller bundles.

The documentation is technically correct; no browser limited to ES5 will understand ESM imports. TypeScript will still output the import statements with ES5 code, and later in the build process we're downgrading those imports using rollup to give the UMD bundles.  If you don't use a bundler yourself (e.g. on plnkr), then you should use the UMD bundle which is pure ES5.

Cheers!

**Comment by sebastianhaas** [comment]
Thanks so much for the clarification!
