### ISSUE TITLE
mat vs md ???

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#3314]
do we have to change from md to mat, everything?

scss is already not working with md

in templates/ng2 i moved everything from md to mat but it is not working, only scss is everything 

what is the status? how can i check it on it?

**Comment by brandondtran** [comment]
I know.. It's so confusing...md is for angular-cli and mat is for using any other sass compiler. 

I gave up on material 2.

**Comment by patrikx3** [comment]
what are you using for gui? bootstrap? 
it is getting like java, slow, big and just getting worse time to time. 
jqueryui was better 10 years ago then this now.

i already thinking of forget ng2/typescript, i need js...

**Comment by brandondtran** [comment]
I agree. It's too much work to configure now. I spent two weekends just trying to get a project set up. 

Angular 2 and material 2 are no where near ready for production use imo.  Having to constantly transpile typescript is also no good.

**Comment by patrikx3** [comment]
what would you choose? right now i am creating a new project just use angular 1? it is mature, isnt it?

**Comment by brandondtran** [comment]
Yes use angular 1. I forked my angular 2 project and converted to angular 1.

You can also use typescript or es6 in angular 1 now.

**Comment by patrikx3** [comment]
yes i guess for angular 2 to be cool will be 5 years later, right now angular 1 is the time when it is mature. this is to create something for it. angular 2 will be in years later.
plus i dont want typescript, i want speed . JS.

thanks dude!

and what about material 1? is that you would choose? 
material 1 vs ng1 bootsrap? or you know something better? 

ciao!

**Comment by patrikx3** [comment]
i guess it will be hard to found out, i
