### ISSUE TITLE
Bug(menu): Cannot read property 'disabled' of undefined

### ISSUE THREAD

**Issue by userexperiences** [angular/material2#3317]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should not cause an exception

#### What is the current behavior?
Causes an exception:
Cannot read property 'disabled' of undefined in the following function:

    ListKeyManager.prototype._setActiveInWrapMode = function (delta, items) {
        // when active item would leave menu, wrap to beginning or end
        this._activeItemIndex =
            (this._activeItemIndex + delta + items.length) % items.length;
        // skip all disabled menu items recursively until an enabled one is reached
        if (items[this._activeItemIndex].disabled) {
            this._setActiveInWrapMode(delta, items);
        }
        else {
            this.setActiveItem(this._activeItemIndex);
        }
    };

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

https://material.angular.io/components/component/menu
focus on a menu item then use an arrow key

#### What is the use-case or motivation for changing an existing behavior?
Need to implement keyboard navigation to go through a menu

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.4.5
Material 2.0.0-beta.2
Windows 10

Chrome Version 56.0.2924.87 (64-bit)
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

**Comment by dahaupt** [comment]
@userexperiences I can't reproduce this (tested in Google Chrome). Can you provide more information?

**Comment by kara** [comment]
Yeah, I'm not able to get the error either. More information to repro?

**Comment by userexperiences** [comment]
Sorry, it's just the up and down arrow keys, make sure the menu is still open and an item is in focus.

**Comment by HumanMedia** [comment]
Yes I can reproduce. One step has been left out.

* Reload the page
* Pop the menu open
* Mousedown on a menu item then without mousing-up, drag the cursor off the menu
* Use up and down cursor keys
* TypeError: Unable to get property 'disabled' of undefined or null reference

**Comment by leocaseiro** [comment]
I thought the `<md-menu>` and the `<md-select>` were sharing the same `html`. As it doesn't happen with `<md-select>`.

**Comment by dahaupt** [comment]
I found the source of the problem and if nobody is already on this issue, I'd like to create a PR :)

**Comment by leocaseiro** [comment]
Sorry @kara, I was wondering why mouse users could not see the focus on click or not navigate with keys.
I normally click on a menu, then, I use keys to navigate.

PS: If we remove the [condition](https://github.com/angular/material2/blob/master/src/lib/menu/menu-trigger.ts#L160), the menu works nice on mouse click and it seems to fix this issue.

**Comment by dahaupt** [comment]
@leocaseiro Removing the condition fixes the problem, but the behavior is not perfect because the focused element will not change if the mouse just hovers over another item. In material1 it works nice, you are right.

**Comment by crisbeto** [comment]
I ran into this while working on another issue. The problem is that we have a check for `null` a little bit down, but the `_activeItemIndex` is `undefined` by default. I've fixed it here https://github.com/angular/material2/pull/3313/files#diff-1f5a5d99cc46e933b521c2af54a59fe9L19, but I'll backport it since it's a quick fix and the other PR may take longer to go through.
