### ISSUE TITLE
mat vs md

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#3319]
the scss already requires to use **mat** instead of **md**.

but i refactored all html via **md** to **mat**, but it was not working. 

do we have to we wait until the refactoring is done or what i was doing something wrong and just really have to safe to remove **md** and use only **mat** now?

**Comment by fxck** [comment]
You don't have to use *mat* for html, unless you turn on the compatibility mode. It's on the other hand required in css, because (I believe) having both *md-* and *mat-* prefixes would be much, much bigger overhead than it is in html selectors.

**Comment by patrikx3** [comment]
ok so to clear it up the html attributes will keep be using **md**?

**Comment by fxck** [comment]
All components will be able to use both *md-* and *mat-* https://github.com/angular/material2/blob/master/src/lib/checkbox/checkbox.ts#L67 if you need to use both angular 1 + material 1 and angular 2 and material 2 in the same project, you'll have to turn on compatibility mode and use *mat-* for material 2 components.

**Comment by ChristianBeilschmidt** [comment]
This is very confusing.
So there are three things:
 * component names (e.g. md-toolbar)
 * css selectors (e.g. .mat-dialog-title)
 * scss functions (e.g. mat-color)

Is it possible to use all three things using **either** `md-` **or** `mat-` prefix?

For me it looks like I have to use md-toolbar in html and css for styling, .mat-dialog-title in css for styling parts of md-toolbar and mat-color in my scss. So I would like to use mat-toolbar then, but this is only possible in compatibility mode?

**Comment by patrikx3** [comment]
mat is for compatibility html, what is strange is that scss was 2 months  ago working with md, now it is mat prefix. it would be cool the same, plus add in mat for  compatibility.
for now it is mixed, not smart.
keep all as **md** and add in **mat** for compatibility html. smart.

**Comment by fxck** [comment]
I can't quite remember what the reasoning was, but I think they didn't want to introduce such a breaking change with those component selectors and came up with compatibility mode, only to later find out that there are conflicts in css as well. While I understand it might be confusing a bit, I don't think it's such a big deal. Utility functions and components are prefixed `cdk` and you probably haven't even noticed.

Anyway these are all questions for @andrewseguin or @jelbourn

**Comment by sreekumarp** [comment]
Use regex **md([A-Z])(\w+)** in find and replace **mat$1$2** for a quick find and replace.
This worked in VS Code, with below options

![image](https://user-images.githubusercontent.com/626181/31583513-6480dd44-b1ae-11e7-81c9-53f9ad457fb2.png)
