### ISSUE TITLE
MaterialModule.forRoot is deprecated.

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#3320]
MaterialModule.forRoot is deprecated.

What do we need to use now?

**Comment by mackelito** [comment]
Please read the release notes 😊👍

**Comment by mackelito** [comment]
@NgModule({
   imports: [
       ...
       MaterialModule,
       ...
   ]
...
});

**Comment by crisbeto** [comment]
@mackelito is correct, you don't need to call `forRoot` anymore.
