### ISSUE TITLE
Bugs in combination with Angular 4.0.0 RC1

### ISSUE THREAD

**Issue by frankspin89** [angular/material2#3321]
#### Bug:

- Template parse warnings in console
- Tooltip component broken
- Select component broken

#### What is the current behavior?

**Template parse warnings in console**
![screen shot 2017-02-27 at 09 48 22](https://cloud.githubusercontent.com/assets/4480104/23354531/ea9b6c56-fcd1-11e6-9dd2-29301cf0174c.png)

**Tooltip component broken**
On hover the tooltip shows without a animation. On mouse out the tooltip doesn't hide it's self. 

![rqlyfgbneu](https://cloud.githubusercontent.com/assets/4480104/23354448/8bb5db2c-fcd1-11e6-9c48-ca0c20c640a5.gif)

**Select component broken**
The animation for the placeholder text is broken. 

![ohaz8sjmm9](https://cloud.githubusercontent.com/assets/4480104/23354518/db558858-fcd1-11e6-8597-3527605b2594.gif)

#### Which versions of Angular, Material, OS, browsers are affected?

- OS: macOs Sierra
- Chrome: Version 56.0.2924.87 (64-bit)
- Angular: 4.0.0-rc.1
- Material: 2.0.0-beta.2

**Comment by fxck** [comment]
https://github.com/angular/material2/pull/3252

**Comment by crisbeto** [comment]
The tooltip and select issues should be resolved by importing the animations module. The one about `template` is tricky without breaking support for Angular < 4.

**Comment by frankspin89** [comment]
@crisbeto the animations on the input component are still working. Any reason why the animation on the select component is not working without the animations module?

**Comment by fxck** [comment]
input is not using angular animation api, just css, afaik

**Comment by crisbeto** [comment]
Yes, the difference is that we don't need to use the Angular animations API for the input since it's pretty simple, but for others, like `select` and `tooltip`, we do.

**Comment by rodolfojnn** [comment]
MdTabs also does not work in ng4. The content is superimposed.

**Comment by kara** [comment]
Yep, importing animations should fix your animation issues. For the template warning, see existing issue https://github.com/angular/material2/issues/3301
