### ISSUE TITLE
Strange behavior of dividerColor

### ISSUE THREAD

**Issue by yfain** [angular/material2#3323]
I want to display the border of the md-input field in red if there is a validation error.  Here's my code for the field Title:

```
<md-input-container [dividerColor] = "formModel.hasError('minlength','title')?'warn':'default'">
    <input mdInput
           type="text"
           placeholder="Product title"
           formControlName="title"
           minlength="3">
    <md-hint *ngIf="formModel.hasError('minlength','title')" >Enter at least 3 characters</md-hint>
```

I'm using "@angular/material": "^2.0.0-beta.2"

When I enter 2 characters in this field and tab out from it, the red border blinks and is not shown. I need to move the focus back to the field to see it in red. Here's a 10-second video illustrating the issue: http://bit.ly/2m1R5kP.

Expected behavior: If I'm leaving the field that has validation errors, dividerColor should display the border in the specified color.

**Comment by mmalerba** [comment]
Please provide a full code example, I have no idea what formModel is in this example

**Comment by antonmoiseev** [comment]
The issue is indeed present in beta.2, but it's fixed in the master branch, here is the corresponding changes: https://github.com/angular/material2/commit/bc9d25b2bbd494d72ebefea9791d375d2773873d#diff-002aa63d52575ed15761f1e16e547059R67
