### ISSUE TITLE
:host not working any more for styling

### ISSUE THREAD

**Issue by albandaft** [angular/material2#3324]
To customize the style of any material component this worked in the past:

```
:host {
    md-input {
        .md-input-underline {
            border-top: 1px solid rgba(254, 254, 254, 0.70);
        }
        .md-input-placeholder {
            color: rgba(254, 254, 254, 0.70);
        }
    }
}
```

After the update the same code, changed with the new component naming does not work:

```
:host {
    md-input-container {
        
        .mat-input-underline {
            border-top: 1px solid rgba(254, 254, 254, 0.70);
        }

        .mat-input-placeholder {
            color: rgba(254, 254, 254, 0.70);
        }

        .mat-input-ripple {
            background-color: rgba(254, 254, 254, 0.70);
        }

    }
}
```

What is the recommended way to customise style of material components in isolation?

**Comment by grizzm0** [comment]
The md-input-container uses <ng-content> to move the input into the component itself. You'll probably need to use /deep/ here.

**Comment by d3viant0ne** [comment]
As a additive note to what @grizzm0 said, I have had to use /deep/ in most places when customizing styles.

**Comment by albandaft** [comment]
Any example code will be usefull, can you provide please?

**Comment by grizzm0** [comment]
https://angular.io/docs/ts/latest/guide/component-styles.html#-deep-

**Comment by d3viant0ne** [comment]
```

:host /deep/ {
    md-input {
        .md-input-underline {
            border-top: 1px solid rgba(254, 254, 254, 0.70);
        }
        .md-input-placeholder {
            color: rgba(254, 254, 254, 0.70);
        }
    }
}

```

**Comment by albandaft** [comment]
@d3viant0ne Working fine with /deep/ (just a typo in your example replace `md-input` with `md-input-container `

**Comment by BamiGorengo** [comment]
/deep/ dont exist any more.

**Comment by oberoivarun** [comment]
@BamiGorengo use `:ng-deep` instead

**Comment by abskr82** [comment]
In this example, I am trying to use :ng-deep
https://stackblitz.com/edit/angular-1yx4td?file=app%2Fselect-multiple-example.css

but it's not working, I am not sure if I am doing anything wrong here?

**Comment by grizzm0** [comment]
@abskr82 No need for `:host` and it's `::ng-deep` with two ":".

**Comment by abskr82** [comment]
@grizzm0 ,

Thank you so much! It worked :+1:
