### ISSUE TITLE
The allowable number of md-sidenav

### ISSUE THREAD

**Issue by ded100let** [angular/material2#3329]
Hi! Thank you for your work! The question is... sidenav 2 work fine... But when you add 3 they are all hidden. There are no errors. Version of angular 2, and the latest material. Big Thanks!

**Comment by ded100let** [comment]
example https://plnkr.co/edit/1cM80qRTOKBpNkGAOjTi?p=preview

**Comment by benb7760** [comment]
From the [documentation for sidenav](https://material.angular.io/components/component/sidenav)
> A sidenav container may contain one or two <md-sidenav> elements. When there are two <md-sidenav> elements, each must be placed on a different side of the container. See the section on positioning below.

**Comment by ded100let** [comment]
Is there a way to do example 2 on the left? Tried 1 sidenav-container, all is well. But when closed, it overlaps another container, although it is hidden. Thank you for your response.

**Comment by fxck** [comment]
Just put `*ngIf` inside the left sidenav and show content depending on what you are opening.

**Comment by kara** [comment]
By design, we only allow one sidenav per side, but it's a bad experience to fail silently. We should be throwing an error.

**Comment by kara** [comment]
Error thrown in #3369
