### ISSUE TITLE
【autocomplete】How subscription onSelect  after ngModel has been updated

### ISSUE THREAD

**Issue by kgtkr** [angular/material2#3333]
#### Bug, feature request, or proposal:
request

#### What is the expected behavior?
ngModel updated after

#### What is the current behavior?
ngModel updated before

#### What is the use-case or motivation for changing an existing behavior?
    tags:string[]=[];
    //ngModel
    tag=``;
    onSelect(){
      this.tags.push(this.tag);
      this.tag='';
    }

#### Which versions of Angular, Material, OS, browsers are affected?
windows10
chrome
angular2.3.1
md beta-2

**Comment by kara** [comment]
Can you give a bit more information about what you're trying to achieve? It seems like `(ngModelChange)` might be a more prudent place for the code you're trying to run.

**Comment by kara** [comment]
Without more info, it seems like you should be using `(ngModelChange)` for this.
