### ISSUE TITLE
md-tab angular 4 rc1 error

### ISSUE THREAD

**Issue by sdiazvi** [angular/material2#3336]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When you pick a tab its show the md-tab-content content

#### What is the current behavior?
When i change between the tabs all the content is already in the md-tab-content.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.0-rc.1, Angular Material 2.0.0-beta.2

**Comment by kara** [comment]
@sdiazvi Plunker example?

**Comment by armno** [comment]
@sdiazvi i think i got the same issue. importing `BrowserAnimationsModule` solved it. http://stackoverflow.com/a/42471212/2095201
