### ISSUE TITLE
Input hints can only contain single-line text

### ISSUE THREAD

**Issue by iliketomatoes** [angular/material2#3337]
#### Bug, feature request, or proposal:
Bug/Feat/Proposal

#### What is the expected behavior?
As you can see in [Angular Material 1](https://material.angularjs.org/latest/demo/input), I would expect the hint text to stay below the input field even when it contains more than one line of text .

#### What is the current behavior?
md-hint element's content is overlapping the corresponding input field if the hint contains multi-line text, due to the CSS rules that are applied to md-hint elements by default. I.E. _position:absolute_ and _bottom: 0_ 

#### What are the steps to reproduce?
Just add a multi-line text into a md-hint.

![material_form](https://cloud.githubusercontent.com/assets/2039028/23461051/2e368d76-fe56-11e6-989e-921a0b2bf682.png)

#### What is the use-case or motivation for changing an existing behavior?
It'd be useful to have multi-line hints under some input field to point out several warnings in a form at the same time.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.8
Material 2.0.0-beta.2

on latest versions of Chrome and Firefox
#### Is there anything else we should know?
Maybe you should reconsider the absolute positioning of the md-hint element to solve this issue.

**Comment by finalxcode** [comment]
+1

**Comment by jefersonestevo** [comment]
+1

**Comment by JosuaMeier** [comment]
+1

**Comment by finalxcode** [comment]
@mmalerba the issue has been fix?

**Comment by ianhatton** [comment]
+1

**Comment by anapanadero** [comment]
+1

**Comment by dahaupt** [comment]
@finalxcode This one is still in discussion but I'm sure we will see this getting fixed within the next weeks **after** ng-conf. The conference is most likely the reason why the team is currently not that active here on the repo.

**Comment by finalxcode** [comment]
@dahaupt thanks
