### ISSUE TITLE
mat-color doesn't allow for 0 value map of pallete

### ISSUE THREAD

**Issue by jamesmfriedman** [angular/material2#3345]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I should be able to get the color of the 0 key in my palette map

#### What is the current behavior?
it tries to treat it as opacity

#### What are the steps to reproduce?
mat-color($my-palette, 0, 1) //treats the 0 as opacity

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
let me use mat-color to select any color in the palette, including the 0 value

#### Which versions of Angular, Material, OS, browsers are affected?
All

**Comment by kara** [comment]
This is actually how the API for that mixin is designed. See the comment here: https://github.com/angular/material2/blob/master/src/lib/core/theming/_theming.scss#L44

**Comment by jamesmfriedman** [comment]
I did read the api, I'm just pointing out that given the current api it is impossible to use mat-color to select the 0 value of a palette. A workaround is to just use map-get on the palette, but its a bit strange considering you can use mat-color for all of the others.
