### ISSUE TITLE
Dialog: support alignment to element and transparent backdrop

### ISSUE THREAD

**Issue by andreasrueedlinger** [angular/material2#3348]
#### Bug, feature request, or proposal:
It would be nice to have the possibility to configure a dialog with a transparent backdrop (like the menu) and to align the openened dialog to another element, for example the button that triggered the dialog (again like menu). The reason not to use menu is that the content of the openend dialog can be an arbitrary component on not only a menu.

#### What is the use-case or motivation for changing an existing behavior?
Menu-like use-case: button to trigger a dialog that is aligned to the button but not containing a m

#### Is there anything else we should know?
Related: #3338

**Comment by jelbourn** [comment]
For cases like this the approach would be to use the underlying `Overlay` with `ConnectedPositionStrategy`.
