### ISSUE TITLE
placeholder of md-input has no enough space for some language charactors

### ISSUE THREAD

**Issue by e-cloud** [angular/material2#3352]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
![image](https://cloud.githubusercontent.com/assets/5255354/23459987/c884d52e-febd-11e6-823b-be0d6d822773.png)
![image](https://cloud.githubusercontent.com/assets/5255354/23460005/ded8dad2-febd-11e6-8374-a914fc631bed.png)

#### What is the current behavior?
Placeholder charactors is partially hidden.
![image](https://cloud.githubusercontent.com/assets/5255354/23459917/6f17ef80-febd-11e6-952e-89e486288632.png)

Space between label and input is too close.
![image](https://cloud.githubusercontent.com/assets/5255354/23459939/89943468-febd-11e6-9770-349e4fe0c3f1.png)

#### What are the steps to reproduce?
http://plnkr.co/edit/P6gPry6h457PiRv50FPB?p=preview

#### What is the use-case or motivation for changing an existing behavior?
To be compatible with non-English users

#### Which versions of Angular, Material, OS, browsers are affected?
Angular v2.4.7, Material v2.0.0-beta.2, ubuntu 16.10, chrome/firefox

**Comment by mmalerba** [comment]
@e-cloud the plunker you provided seems to be behaving correctly (screenshots are ubuntu & chrome 56, but also looked fine in firefox):
![1](https://cloud.githubusercontent.com/assets/14793288/23474952/9312c0ca-fe6a-11e6-97c3-b10d1419b7d0.png)
![2](https://cloud.githubusercontent.com/assets/14793288/23475067/0562ebb4-fe6b-11e6-8f6b-cb6d8ff6d7b6.png)

**Comment by e-cloud** [comment]
@mmalerba Thank you. 
I test the look in other system. They look fine. That's the weird thing.

And I dig a little bit more, and add extra fields for comparison.

It seems it caused by the system default `sans-serif` font. In my ubuntu my default is `Noto Sans CJK SC Regular`.
![image](https://cloud.githubusercontent.com/assets/5255354/23490298/ac90b1a6-ff32-11e6-92fa-c7bb87bae6bb.png)

But I'm not 100% sure about this. Of course, this might off-topic.

**Comment by mmalerba** [comment]
Ah, so I can replicate on my system by explicitly setting just the `<label>` element to `font-family: Noto Sans CJK SC Regular`. Could you see if this plunker fixes your issue? I've added `font-family: inherit` to the `<label>` element. http://plnkr.co/edit/8vrFfML2qLH2r1IKXaru?p=preview

**Comment by e-cloud** [comment]
@mmalerba do you mean your plunkr works fine? It's still the same under my ubuntu chrome and firefox.

And I also test it under another computer(my colleague's), which has ubuntu and the same default sans-serif font. The result is, the problem still exists.

I think this might not be the scope of issue you should handle. Let me know and i will find some other ways to fix it. :)

**Comment by mmalerba** [comment]
Yeah it seems like probably outside the scope of material. Just wanted to check if it was something we could fix easily from our side.
