### ISSUE TITLE
snackbar not displayed anymore with angular version 4.0.0-rc1

### ISSUE THREAD

**Issue by marius-oprea** [angular/material2#3357]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
to display a snackbar at the bottom of the browser

#### What is the current behavior?
it display a transparent div container with a slim shadow without displaying the snackbar

#### What are the steps to reproduce?
Add this code in your component created with Angular version 4.0.0-rc1 and @angular/cli version 1.0.0-rc.0 and @angular/material version 2.0.0-beta.2 :

import {MdSnackBar} from '@angular/material';
....
constructor(...public snackBar: MdSnackBar) {}
....
this.snackBar.open('Test','Ok', {duration:3000});

#### Which versions of Angular, Material, OS, browsers are affected?
Angular version 4.0.0-rc1 and @angular/cli version 1.0.0-rc.0 and @angular/material version 2.0.0-beta.2 . Tested on Chrome and Firefox and Edge latest versions.

**Comment by willshowell** [comment]
Here is a plunk showing the issue

http://plnkr.co/edit/ZJxPOjKC6Lr6RnYQBgTy?p=preview

Switch between `angular@4.0.0-rc.1` and `angular@latest` (2.4.8 atm) by swapping the commented out import in `systemjs.config.ts`

**Comment by crisbeto** [comment]
That makes sense @DenisLaboureyras, although we should probably handle the lack of animations a little better.

**Comment by marcorinck** [comment]
Shouldn't the component just display itself without animations then? There are usecases where I deliberately disable animations and to not be able to use certain components would be quite a surprise.
