### ISSUE TITLE
md-input does not allow typing on IE

### ISSUE THREAD

**Issue by msegers** [angular/material2#336]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
I cannot type on IE (11)

* **If the current behavior is a bug,
Focus any MD-INPUT on IE11 (probably below too but 11 is most relevant). And try to type with keyboard. Does not work.
https://material2-app.firebaseapp.com/ 
You can actually see it here.

* **What is the expected behavior?**
Text appears!

* **What is the motivation / use case for changing the behavior?**
Include IE 11 support seems a must have right?

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.
Angular2 Beta 14, Material Alpha 2

* **Other information**
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by msegers** [comment]
To add, it also doesn't move the floating label upwards as it does on other browsers.

**Comment by msegers** [comment]
+ I've done some testing to see what's up. Besides the label not moving, it seems that setting maxlength=-1 does not allow you to type on IE11, seems to work fine on chrome etc.

**Comment by sebakerckhof** [comment]
FYI: In edge you also can't type, but the floating label does work.

According to both the W3C and WhatWG definition of maxLength, the behavior in IE11/Edge is the correct one.

**Comment by msegers** [comment]
Saw an issue about the label on Firefox as well. Seems to be the same thing (Label)

**Comment by arjtho** [comment]
Only it works in IE if you   set maxLength property

**Comment by arjtho** [comment]
And still label does not float

**Comment by arjtho** [comment]
If input are loaded thru routes then until we click on one field does not display placeholders.
