### ISSUE TITLE
Autocomplete optionSelections is not working

### ISSUE THREAD

**Issue by arat3091** [angular/material2#3360]
ngAfterViewInit() {
    this.sub = Observable.merge(...this.trigger.optionSelections).subscribe(option => {
      console.log(option);
    });
  }

I cannot see the console.log ()

"@angular/common": "^2.4.8",
    "@angular/compiler": "^2.4.8",
    "@angular/core": "^2.4.8",
    "@angular/flex-layout": "^2.0.0-beta.5",
    "@angular/forms": "^2.4.8",
    "@angular/http": "^2.4.8",
    "@angular/material": "2.0.0-beta.2",
    "@angular/platform-browser": "^2.4.8",
    "@angular/platform-browser-dynamic": "^2.4.8",
    "@angular/router": "^3.4.8",

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template.  Here's a plunker example of how to use with beta.2: https://plnkr.co/edit/AaBESvqvT40htQPlAp0b?p=preview

If you are still seeing issues, please file a new issue that follows the template, which gives the team the information needed to investigate.
