### ISSUE TITLE
tabindex doesn't work on md-checkbox

### ISSUE THREAD

**Issue by jloosli** [angular/material2#3368]
#### Bug, feature request, or proposal:
I am not able to disable tabbing to a md-checkbox.

#### What is the expected behavior?
`<md-checkbox tabIndex="-1"></md-checkbox>` should not be skipped over when tabbing through a form.

#### What is the current behavior?
The checkbox receives focus when tabbing through the form. In addition, there isn't any visual indication that the checkbox has focus, so it's difficult to tell where I am in the form unless I press the spacebar to toggle that particular entry.

#### What are the steps to reproduce?

http://plnkr.co/edit/0P5w3xAmYWhx4ZrEoWUU?p=preview

#### What is the use-case or motivation for changing an existing behavior?

I have checkbox that I want on the form, but not to be tabbed to.

#### Which versions of Angular, Material, OS, browsers are affected?
Tested on Angular 2.4.8, Angular/Material 2.0.0-beta.2, Chrome

#### Is there anything else we should know?
That more or less covers it.

**Comment by DevVersion** [comment]
You mentioned in the issue that you are using `tabIndex` in camelcase. But in your Plunkr it's actually just `tabindex`.

For those components, just using `tabIndex` in camelcase should do the trick.

http://plnkr.co/edit/4ScdvxMz8q2Q5RC6bILh?p=preview

**Comment by jloosli** [comment]
Whoops..I had the wrong title down...it's actually md-checkbox that tabindex doesn't work. I also corrected the example to have a lowercase tabindex

**Comment by crisbeto** [comment]
WRT the focus indication, it is being tracked via https://github.com/angular/material2/issues/3102.

**Comment by jloosli** [comment]
@DevVersion So I just came back to this and see that it does indeed work with the camelcase tabIndex. Is that the plan to keep it like that? I'm glad that it works, but given that the [spec for tabindex](https://www.w3.org/TR/html5/editing.html#sequential-focus-navigation-and-the-tabindex-attribute) is all lowercase, I wonder if that will cause additional confusion (beyond just myself).

**Comment by DevVersion** [comment]
Not sure. I see that it can cause confusion here, but I think the `tabIndex` is in camel-cause because when using an input binding, you are actually setting the native `tabIndex` property.

That's why for native inputs you can also do 
```html
<input [tabIndex]="2">
```

Not sure if we should support both.

**Comment by jelbourn** [comment]
@tinayuangao are you able to confirm if this is an issue?

**Comment by tinayuangao** [comment]
It's fixed by #3403. Now checkbox has focus indicator and `[tabIndex]="-1"` works.
