### ISSUE TITLE
Bug(focus-trap): MS Edge: Shift-Tab goes out of the trap

### ISSUE THREAD

**Issue by userexperiences** [angular/material2#3372]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Shift tab should go to the last element of the dialog

#### What is the current behavior?
Shift tab goes to <div tabindex="0"></div> and does not reforcus, then continuing to shift tab would go the elements in the background of the dialog.

#### What are the steps to reproduce?

https://plnkr.co/edit/fGnZezVKDAcjOapZ5IyV?p=info

#### What is the use-case or motivation for changing an existing behavior?
A11Y

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.5
Material 2.0.0-beta.2

Windows 10
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

#### Is there anything else we should know?
It is expecting a md-dialog-actions to find where the last item is but we want the actions to be beside the title. Current workaround right now is to specify the absolute position of the md-dialog-actions which is not ideal.

**Comment by DevVersion** [comment]
This issue only seems to appear inside of `<iframe>` element, and Edge just prints `Script5 Error: Access Denied`.

I tracked it down to the `isTabbable` method that tries to access the `frameElement`, which is obviously critical to MS Edge.
