### ISSUE TITLE
Autocomplete dupilicate value when have more than 1 obj in page

### ISSUE THREAD

**Issue by uopeydel** [angular/material2#3379]
#### Bug, feature request, or proposal:
Bug: Autocomplete dupilicate value when have more than 1 obj in page

#### What is the expected behavior?

When i have more autocomplete obj i need to use un'dupilicate object same i declare

#### What is the current behavior?

autocomplete tool , state and project dupilicate value

#### What are the steps to reproduce?

Plunker template: [link](https://plnkr.co/edit/8ogCzPZeoUr33zc9qho8?p=preview)  https://plnkr.co/edit/8ogCzPZeoUr33zc9qho8?p=preview

#### What is the use-case or motivation for changing an existing behavior?

In one page i want to use more than one Autocomplete

#### Which versions of Angular, Material, OS, browsers are affected?

windows 10 , GoogleChrome

#### Is there anything else we should know?
1)
should have more example in this [link](https://material.angular.io/components/component/autocomplete)
https://material.angular.io/components/component/autocomplete

if you have more example you will see more bug before
2)
I need to filter more than one properties in  my link plnkr show filter only name but if i want to filter name and lastname how can i do? use //   new RegExp(val, 'gi').test(s.namex + s.lastnamex)) // ?? its will be ok?

//--//--//--//
thank to much.

**Comment by kara** [comment]
@uopeydel Each autocomplete needs a unique template variable. Currently you are using the same template variable for both autocomplete triggers. If you rename one of them, it should work.

Example: https://plnkr.co/edit/ggUOK1MAZ4NfFXzOzBXF?p=preview

**Comment by uopeydel** [comment]
ok this mean i will change [mdAutocomplete]="auto"  to  [mdAutocomplete]="stateAuto" when i have more than one Autocomplete  BUT  now i test to change no one is [mdAutocomplete]="auto" it will be error , i dont want to use "auto" word how do i can ? it not make sense to use auto at lest one ...
