### ISSUE TITLE
Add svg icons to the cache

### ISSUE THREAD

**Issue by TidharPeer** [angular/material2#3387]
In Angular 1 I was able to add the SVG icons to the cache using $templateCache.
I couldn't find any way to do that in Material 2.

At the moment I couldn't find a way to add multiple icons in a single http request even though all the icons are in my project.

Using iconRegistry.addSvgIcon creates a single request, while many iconRegistry.addSvgIcon create many requests.

This will boost the performance as there will be fewer requests.

I am using Angular 2, Material 2

**Comment by jelbourn** [comment]
Closing this since there are no plans to add this feature. Angular doesn't have any equivalent construct to the AngularJS `$templateCache`
