### ISSUE TITLE
Some AnimationEntryMetadata broken with Angular 4.0.0-rc.2 update

### ISSUE THREAD

**Issue by borislemke** [angular/material2#3390]
#### Bug, feature request, or proposal:
[x] BUG

The `fadeInItems` `AnimationEntryMetadata` in `mdMenu` is broken with `4-rc.2`. Not sure if this is the fault of `angular` or `material2`. The `transformMenu` `AnimationEntryMetadata` works but with degraded smoothness. You can notice that it is jankier when upgrading to `4-rc.2`. Yes, I have imported `BrowserAnimationsModule` into my `NgModule`.

(both `fadeInItems` and `transformMenu` are used within `mdMenu` which I imported and used on a custom menu panel, I know this is not safe, I was just quickly playing around with `OverlayModule` and noticed this)

#### What is the expected behavior?
It should work.

#### What is the current behavior?
Doesn't work as intended. The `md-menu-item` elements are shown from start of `transformMenu` instead of waiting for the transform animation to finish before showing the content.

#### What are the steps to reproduce?
`ng new project` - create project with `angular-cli`
Update all angular modules to `4-rc.2` (`@next`).

Create simple `md-menu` element:
```html
<md-menu #brokenMenuAnimation>
    <button md-menu-item>
        I should wait for transform animation to finish before revealing myself.
    </button>
</md-menu>

<button [mdMenuTriggerFor]="brokenMenuAnimation">Animate!</button>
```

#### What is the use-case or motivation for changing an existing behavior?
It's a bug.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.0-rc.2, Material 2.0.0-beta.2

**Comment by fxck** [comment]
https://github.com/angular/material2/pull/3252

**Comment by christophechevalier** [comment]
@borislemke @kara 

## Hi !! 
I think that I have a same problem.
Let's see my screenshots : 

**FULLSIZE**
![selection_063](https://cloud.githubusercontent.com/assets/7148846/24254622/ad90c91c-0fe3-11e7-8870-69d4d725bedf.png)

**SIZE RESIZE**
![selection_064](https://cloud.githubusercontent.com/assets/7148846/24254625/af5c13dc-0fe3-11e7-8296-e4996e47f691.png)

When I open a menu, if I resize the window, the position of menu doesn't change.
Is that the same bug ?
Thanks.

(FYI)@maxime1992

**Comment by jelbourn** [comment]
Closing since I believe this issue is now obsolete
