### ISSUE TITLE
mdMenu add menu markup template to component not root of page

### ISSUE THREAD

**Issue by Miziak** [angular/material2#3393]
Feature request
Is it possible to add menu(overlay with buttons) to parent component not root of page? If it is in root I cannot access it in unittests from `fixture.nativeElement`.
Maybe is another way to unittest menues?

In advice thanks for help!

**Comment by kara** [comment]
@Miziak The overlay is connected to the root of the page to ensure its stacking context is correct. Moving it to the parent component would unfortunately break this guarantee. 

I understand the unit testing pain, though. If you provide your own overlayContainer element in your unit test, you should be able to query it directly for the menu and its children. You can see some examples in the menu spec [here](https://github.com/angular/material2/blob/master/src/lib/menu/menu.spec.ts).
