### ISSUE TITLE
(md-slider): swipe broken on firefox for android

### ISSUE THREAD

**Issue by rish7** [angular/material2#3394]
Feature request or proposal:

 I wish to see a feature on md-slider for touch device, swipe the head of slider. Now it is only working tap [Tested in Andriod Firefox]

Only Tap is working 

Open https://material.angular.io/components/component/slider in Andriod Firefox and try to drag/swipe the Slider head.

It will be good to have, for touch devices.

**Comment by kara** [comment]
Yeah, can repro on Android Firefox. Seems to work on Chrome, but not Firefox.

**Comment by csis0247** [comment]
Not only Android Firefox. Can reproduce on desktop Firefox (51.0.1 64-bit in Ubuntu).

**Comment by mmalerba** [comment]
As noted on the docs page:

> The sliding behavior for this component requires that HammerJS is loaded on the page.

Seems to work fine for me in the demo app with HammerJS loaded.

**Comment by mmalerba** [comment]
So after further investigation, it lookes like HammerJS is loaded on the docs site, but swiping is still not working for some reason. It works on the exact same example when clicking the "view in plunker" link, so it seems to be some issue with the docs site, not the slider component. Filed a new issue on the docs site repo
