### ISSUE TITLE
MdSnackBar - Error: Attempt to use a destroyed view: detectChanges

### ISSUE THREAD

**Issue by pandazzurro** [angular/material2#3399]
#### Bug, feature request, or proposal:
After some second of injecting MdSnackBar in a component, I receive this error:
**Error: Attempt to use a destroyed view: detectChanges**
Removing all MdSnackBar  reference, the component work fine.

Angular2: ^2.3.1
Angular Material2: ^2.0.0-beta.1

**Comment by kara** [comment]
@pandazzurro Can you please provide some code or a plunker example? As it is, it's hard to know what you're reporting.

**Comment by pandazzurro** [comment]
Hi @kara, I make plunker but it work: http://plnkr.co/edit/GrvuR3CBVHFpgEM4HNzb
In my easy trial test, not work: https://github.com/pandazzurro/LogClientSideFull/blob/9f63aefa7c4301d33c7544b95444684626de3f49/LogClientSide/src/app/application-insight/application-insight.component.ts#L141
Removing this.snackBar the component work fine.
