### ISSUE TITLE
mdRadio and mdRadioGroup

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#34]
- [ ] Determine if component can be built on top of a native `<input type="radio">`
- [ ] Unit tests
- [ ] E2E tests
- [ ] Documentation
- [ ] Demo page

**Comment by rfru** [comment]
https://docs.google.com/document/d/1WbJ6VPqwS15fd_JW5OK2Ek9E2N_wHa5TUWL07jCjCr0/edit

**Comment by rfru** [comment]
#125

**Comment by jelbourn** [comment]
Closed via #125
