### ISSUE TITLE
MdDialog attributes don't work when bound dynamically.

### ISSUE THREAD

**Issue by mcalmus** [angular/material2#3401]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should be able to use attribute binding similar to the following to denote attributes used by MdDialog.
`[attr.md-dialog-content ]="myvar ? true:null"`

#### What is the current behavior?
When attributes are set this way they appear in the HTML, but the displayed dialog does not honor them.

#### What are the steps to reproduce?

I can't actually run this due to CORS restrictions here, but this should get the point across.

http://plnkr.co/edit/jShQCT

#### What is the use-case or motivation for changing an existing behavior?
I have a component that is sometimes displayed as a regular page and sometimes displayed in a dialog. I want to have the dialog scroll properly using md-dialog-content without having the plain version have extra scroll bars.

#### Which versions of Angular, Material, OS, browsers are affected?
I'm using the latest stable versions of Angular and Material on Windows with Firefox.

**Comment by kara** [comment]
This is a limitation of attribute bindings in Angular core. See https://github.com/angular/angular/issues/11716. Directives like `md-dialog-content` won't be triggered if the attribute was added later through a binding.

Given that the directive is only used to add a class to the element for styling, you should be able to get the same result by binding to the class directly, e.g. `[class.mat-dialog-content]="dialogMode ? true : null]`.
