### ISSUE TITLE
Dialog is not displayed on correct position in Safari on iOS 8

### ISSUE THREAD

**Issue by thanhpd** [angular/material2#3406]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Dialog displays on center of screen

#### What is the current behavior?
Dialog displays on top left of screen
![image](https://cloud.githubusercontent.com/assets/6737911/23541802/4575e154-001c-11e7-91c6-78fbf5355b89.png)

#### Which versions of Angular, Material, OS, browsers are affected?
Material: Material2-beta2
Browser: Safari on iOS 8
OS: iPad mini 2 - iOS 8.2

**Comment by crisbeto** [comment]
We haven't added browser prefixes in this case, because we don't support iOS 8. Material supports the last 2 major versions of browsers (in this case it's Safari 9 and 10).
