### ISSUE TITLE
Snackbar is not displayed on correct position in Safari on iOS 8

### ISSUE THREAD

**Issue by thanhpd** [angular/material2#3407]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Snackbar displays on center of screen

#### What is the current behavior?
Snackbar displays on top left of screen
![image](https://cloud.githubusercontent.com/assets/6737911/23542642/e311b592-0020-11e7-990d-47dc4a78f4b8.png)

#### Which versions of Angular, Material, OS, browsers are affected?
Material: Material2-beta2
Browser: Safari on iOS 8
OS: iPad mini 2 - iOS 8.2

**Comment by crisbeto** [comment]
We haven't added browser prefixes in this case, because we don't support iOS 8. Material supports the last 2 major versions of browsers (in this case it's Safari 9 and 10).

**Comment by thanhpd** [comment]
@crisbeto Thanks for your responding. Where can I see the supported browsers with Material2 library? I can't find it anywhere in either documentation or source code.

**Comment by crisbeto** [comment]
Sorry, we could probably be better at explaining this, but here's what we have in our Autoprefixer config: https://github.com/angular/material2/blob/master/tools/gulp/constants.ts#L13
