### ISSUE TITLE
mdMenu: How to Keep menu open after a click

### ISSUE THREAD

**Issue by da45** [angular/material2#3408]
####  request
As discussed in #2961,  Having multi-level menus will be supported but no progress right now,
In order to move forward, I really want to emulate this feature by prevent close of md-menu when click a menu-item button and open a new md-menu 
 both of md-menus  open will be closed once an menu-item button in the second md-menu is clicked.

#### What is the expected behavior?
Keep md-menu open 

#### What is the current behavior?
when click an md-menu-item button, md-menu is closed

#### What is the use-case or motivation for changing an existing behavior?
Emulate the sub menu

**Comment by fxck** [comment]
There is progress right now, as stated in the issue you linked. 

https://github.com/angular/material2/pull/3259
