### ISSUE TITLE
Replace tooltip with mdTooltip and allow user to change the tooltip message

### ISSUE THREAD

**Issue by DarienChoo** [angular/material2#3409]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
![image](https://cloud.githubusercontent.com/assets/5697198/23546864/72172ec8-003c-11e7-8af6-5d112e5cc623.png)

#### What is the current behavior?
![image](https://cloud.githubusercontent.com/assets/5697198/23546771/158ed9a8-003c-11e7-8079-e8441d2bdfef.png)

#### What are the steps to reproduce?
Hover the input field with 'required' attribute

**Comment by jelbourn** [comment]
Don't really follow what you're proposing. Feel free to open a new issue w/ more details.
