### ISSUE TITLE
Md-slider customization

### ISSUE THREAD

**Issue by kmathy** [angular/material2#3412]
#### feature request:
Allow to style the md-slider with my own CSS.

#### What is the expected behavior?
I try to display: none the thumb slider to only have the slider. I tried with !important, by customizing inside the node_modules,...
![expected_behavior](https://cloud.githubusercontent.com/assets/15690980/23555238/6b09e814-0028-11e7-9cda-4a3fe25f4c02.png)

#### What is the current behavior?
No Effect because of the default values.
![current_behavior](https://cloud.githubusercontent.com/assets/15690980/23555237/6b076da0-0028-11e7-8e6a-999a5bd4aa4b.png)

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.8
Material 2.0.0-beta.2

**Comment by kmathy** [comment]
## Workaround

If someone is searching a way to customize the CSS properties or behavior for some elements of Angular Material, here is how I did that in the NgOnInit of my component:

<pre><code>ngOnInit() {
    for (const sliderSkill of Array.from(document.getElementsByClassName('slider-skill'))) {
      sliderSkill.removeEventListener('click');
    }
    for (const thumb of Array.from(document.getElementsByClassName('mat-slider-thumb'))) {
      thumb.classList.add('disable-thumb');
    }
    for (const trackBackground of Array.from(document.getElementsByClassName('mat-slider-track-background'))) {
      trackBackground.classList.add('track-background');
    }
  }</code></pre>

And CSS properties are global values:

<pre><code>
.disable-thumb {
  display: none;
}

.track-background {
  background-color: $color-black--light;
}
</code></pre>

Result:

![results](https://cloud.githubusercontent.com/assets/15690980/23606691/21ee88f6-0262-11e7-804a-85cfa3deb824.png)

Hope this help.

**Comment by mmalerba** [comment]
Since the material spec calls for the thumb this is not something we want to officially support in our API. Overriding the styles as you've done is the best way to accomplish this, but fair warning: it's possible that the exact DOM and classes may change at some point

**Comment by kmathy** [comment]
Because the version is in Beta, I know the consequences. Don't forget to add this to your guide for potential people who wants to have this feature.

Have a nice day!
