### ISSUE TITLE
Feature request: Add content to Sidenav Backdrop

### ISSUE THREAD

**Issue by sasxa** [angular/material2#3425]
#### What is the expected behavior?
https://github.com/angular/material2/blob/master/src/lib/sidenav/sidenav-container.html

Perhaps add another `<ng-content>`:
```
<div class="mat-sidenav-backdrop" (click)="_onBackdropClicked()"
     [class.mat-sidenav-shown]="_isShowingBackdrop()">

     <ng-content select="md-sidenav-backdrop, mat-sidenav-backdrop"></ng-content>

</div>

<ng-content select="md-sidenav, mat-sidenav"></ng-content>

<div class="mat-sidenav-content" [ngStyle]="_getStyles()" cdk-scrollable>
  <ng-content></ng-content>
</div>
```

#### What is the current behavior?
Not supported.

#### What is the use-case or motivation for changing an existing behavior?
At the moment backdrop is blank, but it would be nice if we could insert some content there...

**Comment by crisbeto** [comment]
What kind of content would you want to add inside of a backdrop?

**Comment by sasxa** [comment]
Anything really (any component). Let's say `sidenav` has a list of items and on hover over each of them I want to play a video, or show description with images in the backdrop on large screens...

**Comment by crisbeto** [comment]
This doesn't sound like the sidenav should handle. The backdrop is meant to be static and only be there to catch clicks. The way it's set up at the moment is that it doesn't even get processed by Angular. Thoughts @mmalerba?

**Comment by sasxa** [comment]
Take a look at the editor at https://sway.com/. This type of interface would be easy to create with `sidenav`, something like this:

```
<md-sidenav-container>
  <md-sidenav>
    <md-sidenav-container>
      <md-sidenav>
        <CARDS_COMPONENT></CARDS_COMPONENT>
        <!-- sidenav content -->
      </md-sidenav>
    </md-sidenav-container>

    <STORYLINE_COMPONENT></STORYLINE_COMPONENT>
    <!-- primary content -->
  </md-sidenav>

  <md-sidenav-backdrop>
    <PREVIEW_COMPONENT></PREVIEW_COMPONENT>
  </md-sidenav-backdrop>

</md-sidenav-container>
```

**Comment by jelbourn** [comment]
This isn't something we plan on adding; we consider the backdrop to primarily be an indicator that the content is inactive. Adding additional content would be trying to add too much behavior to this.
