### ISSUE TITLE
mat-input-underline and mat-select-underline - Inconsistent element and property use

### ISSUE THREAD

**Issue by frankspin89** [angular/material2#3427]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Be consistent with the HTML elements and css properties 

#### What is the current behavior?

mat-input-underline is using a div element and css border property
mat-select-underline is using a span element and css background-color property

#### What is the use-case or motivation for changing an existing behavior?

Easier styling. Especially for custom modifications.

#### Which versions of Angular, Material, OS, browsers are affected?

- OS: macOs Sierra
- Chrome: Version 56.0.2924.87 (64-bit)
- Angular: 4.0.0-rc.2
- Material: 2.0.0-beta.2

**Comment by fredrikredflag** [comment]
It looks like `mat-select-underline` is missing `<span class="mat-input-ripple mat-accent"></span>`.

**Comment by jelbourn** [comment]
Tracking via #4673

**Comment by finalxcode** [comment]
+1
