### ISSUE TITLE
Add font-color property to theme mixin 

### ISSUE THREAD

**Issue by frankspin89** [angular/material2#3428]
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

Would be very helpful to have the possibility to specify a color palette for your fonts. 

```
$your-app-primary: mat-palette($mat-indigo);
$your-app-accent: mat-palette($mat-blue);
$your-app-warn: mat-palette($mat-red);
$your-app-text: mat-palette($mat-grey);
$your-app-theme: mat-light-theme(
$your-app-primary,
$your-app-accent,
$your-app-warn,
$your-app-text);
```

And use the specified color for all default content in md elements. Currently the default is a black with % opacity. 

#### What is the current behavior?

No possibility to specify a color for your content. U have to manually override all the default blacks in the md elements. Hard to be consistent and it's cumbersome.   

#### Which versions of Angular, Material, OS, browsers are affected?

- OS: macOs Sierra
- Chrome: Version 56.0.2924.87 (64-bit)
- Angular: 4.0.0-rc.1
- Material: 2.0.0-beta.2

**Comment by thibaultsavary** [comment]
That wouldn't respect the material guidelines I think.

https://material.io/guidelines/style/typography.html#typography-other-typographic-guidelines

> A text color that is too similar to the background color is hard to read. Text with too much contrast can also be hard to read. This is especially true of light-colored text against dark backgrounds.
> 
> Text should maintain a minimum contrast ratio of at least 4.5:1 (calculated based on luminance values) for legibility. A ratio of 7:1 is preferred.
> 
> These color combinations also consider contrast ratios for users who perceive color differently.

**Comment by frankspin89** [comment]
I would depend on the colors you choose. In the guidelines they are using the primary-color for headings and links. (which is also debatable, because headings are not clickable).

**Comment by jelbourn** [comment]
We don't plan on adding font-color as part of the theme, as [the spec calls for specific text colors](https://material.io/guidelines/style/color.html#color-usability) based on whether the theme is light or dark.
