### ISSUE TITLE
md-card - Elevation on desktop

### ISSUE THREAD

**Issue by frankspin89** [angular/material2#3430]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

![components_cards_elevation_desktop](https://cloud.githubusercontent.com/assets/4480104/23576933/295019c2-00b2-11e7-8ac0-35474920389e.png)

Cards should have a elevation (dropshadow) of 0dp on desktop. 

#### What is the current behavior?

![components_cards_elevation](https://cloud.githubusercontent.com/assets/4480104/23576944/613576de-00b2-11e7-85eb-6ebc4d626893.png)

Cards on desktops are currently following mobile guidelines with a 2dp elevation

#### What is the use-case or motivation for changing an existing behavior?

Be consistent with the Material Guidelines

#### Which versions of Angular, Material, OS, browsers are affected?

- OS: macOs Sierra
- Chrome: Version 56.0.2924.87 (64-bit)
- Angular: 4.0.0-rc.1
- Material: 2.0.0-beta.2

#### Is there anything else we should know?

Maybe it would be smart to introduce a option to enable/disable elevation on cards.

**Comment by thomaspink** [comment]
@frankspin89 Are you sure the elevation should be 0?

I had a look into the guidlines and the elevation of a card is defined as follows:
* **2pt**: Card (resting elevation)
* **8px**: Card (when picked up)

https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-elevation-android

**Comment by thomaspink** [comment]
@thibaultsavary @frankspin89 i see your point.
now i am also confused :) but i have to say, i never have seen a card with no elevation.

**Comment by frankspin89** [comment]
@thomaspink @thibaultsavary Would be good to introduce a option to enable/disable elevation on card basis. In combination with a global default option. That's the most flexible solution I think.

**Comment by thibaultsavary** [comment]
@frankspin89 
You can use the `mat-elevation()` mixin, but yeah an `elevation attribute`, like they did it in Polymer could be great.

@thomaspink 
Yep, and it clearly says that any material is 1dp thick in the guidelines so it kinda feel contradictory to set a 0dp elevation to represent 1dp thickness.

**Comment by Nodarii** [comment]
Hello guys, 

Totaly agree, it would be nice to have an ability to regulate an elevation via `<md-card>` attribure.

**Comment by Germanaz0** [comment]
It should be nice to fix also the transition effects for hover on cards, right now is very rough

**Comment by willshowell** [comment]
@Germanaz0 they look smooth here:

https://plnkr.co/edit/RoWV4ou4raej5BiGmaVT?p=preview

**Comment by leocaseiro** [comment]
They've fixed the `mat-elevation-z` classes, so you can just set the class `.mat-elevation-z0` on your card.

```html
<mat-card class="mat-elevation-z0">
...
<mat-card>
```
Eq: http://plnkr.co/edit/cK4Q1C?p=preview

If you would you like to set all your cards with z elevation by default, you can also use SASS and the [mixin](https://github.com/angular/material2/blob/master/guides/elevation.md#mixins) `mat-elevation(0)`

```scss
@import '~@angular/material/theming';

mat-card {
  @include mat-elevation(0);
}
```

**Comment by jelbourn** [comment]
Closing this since everything discussed here is superseded by the 2018 update to the Material Design spec. Updates for that will be tracked separately.
