### ISSUE TITLE
Error in IE 11

### ISSUE THREAD

**Issue by ded100let** [angular/material2#3433]
Hi! In IE 11 error.
SCRIPT5007: Не удалось получить свойство "apply" ссылки, значение которой не определено или является NULL

code:`return(e=Object).assign.apply(e,[{}].concat(t))`
Asking for your help. The problem is only in IE 11. Thank you!
Where can I see the prototype of the method apply?

**Comment by ded100let** [comment]
error: SCRIPT5007: unable to get property 'apply' links whose value is not undefined or NULL reference

**Comment by ded100let** [comment]
ng -version

@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/flex-layout: 2.0.0-beta.5
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

**Comment by crisbeto** [comment]
When are you getting this error?

**Comment by ded100let** [comment]
Thanks or answer! In dev. console browser IE 11.
In Edge no error.

**Comment by ded100let** [comment]
screenshot https://yadi.sk/i/Kn988PEx3F2XUY

**Comment by ded100let** [comment]
`function combine(options) {
    return (_a = ((Object))).assign.apply(_a, [{}].concat(options));
    var _a;
}`

**Comment by ded100let** [comment]
function in node_modules\@angular\common\bundles\common.umd.js

**Comment by crisbeto** [comment]
This doesn't look like a problem with Material, but with `@angular/common`. Please post the issue in the appropriate repo.
