### ISSUE TITLE
performance using prebuilt theming, generates old css

### ISSUE THREAD

**Issue by stefanaerts** [angular/material2#3438]
#### Bug, feature request, or proposal:
@angular/material@^2.0.0-beta.2
![image](https://cloud.githubusercontent.com/assets/3684599/23581699/5882ac20-0119-11e7-86d7-08c9d2d1561d.png)

#### What is the expected behavior?
to have no old css

#### What is the current behavior?
old css generated by the theming css scss files

#### What are the steps to reproduce?
include a prebuilt theme in styles.scss

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material@^2.0.0-beta.2

#### Is there anything else we should know?
I run lighthouse and try to have 100% on it,but its not possible with material at the moment.
.cdk-global-overlay-wrapper {
  display: -webkit-box;
} is found in my generated code ,if i don't use material i don't have old css

**Comment by jelbourn** [comment]
We don't use autoprefixer any more so this should be obsolete.
