### ISSUE TITLE
issue with input component in safari

### ISSUE THREAD

**Issue by bmrinal** [angular/material2#3439]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Input placeholders should move up

#### What is the current behavior?
Input placeholders remain there and actual input is overwritten

#### What are the steps to reproduce?
open the official plunkr in safari
https://material.angular.io/components/component/input ( see plunkr in this link on safari)

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.x
material 2.0.0 beta
browser: safari

#### Is there anything else we should know?
I am using ng-cli. the official docs page renders the input correctly but the official plunkr when opened in safari is having the same issue.

**Comment by fxck** [comment]
![image](https://cloud.githubusercontent.com/assets/1303561/23586799/803d0cc2-019d-11e7-938c-e1af07e0ff81.png)

![image](https://cloud.githubusercontent.com/assets/1303561/23586802/8c2ebf30-019d-11e7-874c-5381c0f10b7c.png)


you should perhaps be more specific with the version of safari, works fine on mine (latest)

**Comment by frankspin89** [comment]
Please make sure that you have included the animation package for angular core. You can find more information about implementing the animation package here https://github.com/angular/angular/blob/master/CHANGELOG.md#400-rc1-2017-02-24

**Comment by fxck** [comment]
input animations are done with just css, this shouldn't be the issue

**Comment by kara** [comment]
@bmrinal As fxck suggested, can you provide more info? I checked the official plunker on Safari version 10, but it's working as expected. Did you change the plunker code at all?

**Comment by bmrinal** [comment]
@kara No I didn't changed anything...I shall provide more details by today....safari version specifically....

**Comment by josephperrott** [comment]
Closing as `input` styling has been rewritten/changed and this no longer applies.
