### ISSUE TITLE
demo can't run

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/material2#344]
```
cd D:\Desktop\material2
ng build
cd D:\Desktop\material2\dist
compass init  //then i edit config.rb
compass compile
python -m http.server 8001
```

then  i got this error

angular2-polyfills.js:126 GET http://127.0.0.1:8001/components/toolbar/mixins 404 (File not found)scheduleTask @ angular2-polyfills.js:126ZoneDelegate.scheduleTask @ angular2-polyfills.js:403Zone.longStackTraceZoneSpec.onScheduleTask @ angular2-polyfills.js:1420ZoneDelegate.scheduleTask @ angular2-polyfills.js:400Zone.scheduleMacroTask @ angular2-polyfills.js:340(anonymous function) @ angular2-polyfills.js:147send @ VM694:3XHRImpl.get @ angular2.dev.js:18017(anonymous function) @ angular2.dev.js:22455StyleCompiler._loadStyles @ angular2.dev.js:22451(anonymous function) @ angular2.dev.js:22457ZoneDelegate.invoke @ angular2-polyfills.js:390NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2126ZoneDelegate.invoke @ angular2-polyfills.js:389Zone.run @ angular2-polyfills.js:283(anonymous function) @ angular2-polyfills.js:635ZoneDelegate.invokeTask @ angular2-polyfills.js:423NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2118ZoneDelegate.invokeTask @ angular2-polyfills.js:422Zone.runTask @ angular2-polyfills.js:320drainMicroTaskQueue @ angular2-polyfills.js:541ZoneTask.invoke @ angular2-polyfills.js:493
angular2-polyfills.js:126 GET http://127.0.0.1:8001/components/toolbar/default-theme 404 (File not found)scheduleTask @ angular2-polyfills.js:126ZoneDelegate.scheduleTask @ angular2-polyfills.js:403Zone.longStackTraceZoneSpec.onScheduleTask @ angular2-polyfills.js:1420ZoneDelegate.scheduleTask @ angular2-polyfills.js:400Zone.scheduleMacroTask @ angular2-polyfills.js:340(anonymous function) @ angular2-polyfills.js:147send @ VM694:3XHRImpl.get @ angular2.dev.js:18017(anonymous function) @ angular2.dev.js:22455StyleCompiler._loadStyles @ angular2.dev.js:22451(anonymous function) @ angular2.dev.js:22457ZoneDelegate.invoke @ angular2-polyfills.js:390NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2126ZoneDelegate.invoke @ angular2-polyfills.js:389Zone.run @ angular2-polyfills.js:283(anonymous function) @ angular2-polyfills.js:635ZoneDelegate.invokeTask @ angular2-polyfills.js:423NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2118ZoneDelegate.invokeTask @ angular2-polyfills.js:422Zone.runTask @ angular2-polyfills.js:320drainMicroTaskQueue @ angular2-polyfills.js:541ZoneTask.invoke @ angular2-polyfills.js:493
angular2-polyfills.js:126 GET http://127.0.0.1:8001/components/toolbar/%5C%22variables%5C%22 404 (File not found)scheduleTask @ angular2-polyfills.js:126ZoneDelegate.scheduleTask @ angular2-polyfills.js:403Zone.longStackTraceZoneSpec.onScheduleTask @ angular2-polyfills.js:1420ZoneDelegate.scheduleTask @ angular2-polyfills.js:400Zone.scheduleMacroTask @ angular2-polyfills.js:340(anonymous function) @ angular2-polyfills.js:147send @ VM694:3XHRImpl.get @ angular2.dev.js:18017(anonymous function) @ angular2.dev.js:22455StyleCompiler._loadStyles @ angular2.dev.js:22451(anonymous function) @ angular2.dev.js:22457ZoneDelegate.invoke @ angular2-polyfills.js:390NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2126ZoneDelegate.invoke @ angular2-polyfills.js:389Zone.run @ angular2-polyfills.js:283(anonymous function) @ angular2-polyfills.js:635ZoneDelegate.invokeTask @ angular2-polyfills.js:423NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2118ZoneDelegate.invokeTask @ angular2-polyfills.js:422Zone.runTask @ angular2-polyfills.js:320drainMicroTaskQueue @ angular2-polyfills.js:541ZoneTask.invoke @ angular2-polyfills.js:493
angular2-polyfills.js:126 GET http://127.0.0.1:8001/components/toolbar/%5C%22mixins%5C%22 404 (File not found)scheduleTask @ angular2-polyfills.js:126ZoneDelegate.scheduleTask @ angular2-polyfills.js:403Zone.longStackTraceZoneSpec.onScheduleTask @ angular2-polyfills.js:1420ZoneDelegate.scheduleTask @ angular2-polyfills.js:400Zone.scheduleMacroTask @ angular2-polyfills.js:340(anonymous function) @ angular2-polyfills.js:147send @ VM694:3XHRImpl.get @ angular2.dev.js:18017(anonymous function) @ angular2.dev.js:22455StyleCompiler._loadStyles @ angular2.dev.js:22451(anonymous function) @ angular2.dev.js:22457ZoneDelegate.invoke @ angular2-polyfills.js:390NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2126ZoneDelegate.invoke @ angular2-polyfills.js:389Zone.run @ angular2-polyfills.js:283(anonymous function) @ angular2-polyfills.js:635ZoneDelegate.invokeTask @ angular2-polyfills.js:423NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2118ZoneDelegate.invokeTask @ angular2-polyfills.js:422Zone.runTask @ angular2-polyfills.js:320drainMicroTaskQueue @ angular2-polyfills.js:541ZoneTask.invoke @ angular2-polyfills.js:493
angular2-polyfills.js:126 GET http://127.0.0.1:8001/components/toolbar/%5C%22default-theme%5C%22 404 (File not found)scheduleTask @ angular2-polyfills.js:126ZoneDelegate.scheduleTask @ angular2-polyfills.js:403Zone.longStackTraceZoneSpec.onScheduleTask @ angular2-polyfills.js:1420ZoneDelegate.scheduleTask @ angular2-polyfills.js:400Zone.scheduleMacroTask @ angular2-polyfills.js:340(anonymous function) @ angular2-polyfills.js:147send @ VM694:3XHRImpl.get @ angular2.dev.js:18017(anonymous function) @ angular2.dev.js:22455StyleCompiler._loadStyles @ angular2.dev.js:22451(anonymous function) @ angular2.dev.js:22457ZoneDelegate.invoke @ angular2-polyfills.js:390NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2126ZoneDelegate.invoke @ angular2-polyfills.js:389Zone.run @ angular2-polyfills.js:283(anonymous function) @ angular2-polyfills.js:635ZoneDelegate.invokeTask @ angular2-polyfills.js:423NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2118ZoneDelegate.invokeTask @ angular2-polyfills.js:422Zone.runTask @ angular2-polyfills.js:320drainMicroTaskQueue @ angular2-polyfills.js:541ZoneTask.invoke @ angular2-polyfills.js:493
angular2-polyfills.js:126 GET http://127.0.0.1:8001/components/icon/variables 404 (File not found)scheduleTask @ angular2-polyfills.js:126ZoneDelegate.scheduleTask @ angular2-polyfills.js:403Zone.longStackTraceZoneSpec.onScheduleTask @ angular2-polyfills.js:1420ZoneDelegate.scheduleTask @ angular2-polyfills.js:400Zone.scheduleMacroTask @ angular2-polyfills.js:340(anonymous function) @ angular2-polyfills.js:147send @ VM694:3XHRImpl.get @ angular2.dev.js:18017(anonymous function) @ angular2.dev.js:22455StyleCompiler._loadStyles @ angular2.dev.js:22451(anonymous function) @ angular2.dev.js:22457ZoneDelegate.invoke @ angular2-polyfills.js:390NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2126ZoneDelegate.invoke @ angular2-polyfills.js:389Zone.run @ angular2-polyfills.js:283(anonymous function) @ angular2-polyfills.js:635ZoneDelegate.invokeTask @ angular2-polyfills.js:423NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2118ZoneDelegate.invokeTask @ angular2-polyfills.js:422Zone.runTask @ angular2-polyfills.js:320drainMicroTaskQueue @ angular2-polyfills.js:541ZoneTask.invoke @ angular2-polyfills.js:493
angular2-polyfills.js:126 GET http://127.0.0.1:8001/components/icon/default-theme 404 (File not found)scheduleTask @ angular2-polyfills.js:126ZoneDelegate.scheduleTask @ angular2-polyfills.js:403Zone.longStackTraceZoneSpec.onScheduleTask @ angular2-polyfills.js:1420ZoneDelegate.scheduleTask @ angular2-polyfills.js:400Zone.scheduleMacroTask @ angular2-polyfills.js:340(anonymous function) @ angular2-polyfills.js:147send @ VM694:3XHRImpl.get @ angular2.dev.js:18017(anonymous function) @ angular2.dev.js:22455StyleCompiler._loadStyles @ angular2.dev.js:22451(anonymous function) @ angular2.dev.js:22457ZoneDelegate.invoke @ angular2-polyfills.js:390NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2126ZoneDelegate.invoke @ angular2-polyfills.js:389Zone.run @ angular2-polyfills.js:283(anonymous function) @ angular2-polyfills.js:635ZoneDelegate.invokeTask @ angular2-polyfills.js:423NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2118ZoneDelegate.invokeTask @ angular2-polyfills.js:422Zone.runTask @ angular2-polyfills.js:320drainMicroTaskQueue @ angular2-polyfills.js:541ZoneTask.invoke @ angular2-polyfills.js:493
angular2-polyfills.js:126 GET http://127.0.0.1:8001/components/icon/%5C%22variables%5C%22 404 (File not found)scheduleTask @ angular2-polyfills.js:126ZoneDelegate.scheduleTask @ angular2-polyfills.js:403Zone.longStackTraceZoneSpec.onScheduleTask @ angular2-polyfills.js:1420ZoneDelegate.scheduleTask @ angular2-polyfills.js:400Zone.scheduleMacroTask @ angular2-polyfills.js:340(anonymous function) @ angular2-polyfills.js:147send @ VM694:3XHRImpl.get @ angular2.dev.js:18017(anonymous function) @ angular2.dev.js:22455StyleCompiler._loadStyles @ angular2.dev.js:22451(anonymous function) @ angular2.dev.js:22457ZoneDelegate.invoke @ angular2-polyfills.js:390NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2126ZoneDelegate.invoke @ angular2-polyfills.js:389Zone.run @ angular2-polyfills.js:283(anonymous function) @ angular2-polyfills.js:635ZoneDelegate.invokeTask @ angular2-polyfills.js:423NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2118ZoneDelegate.invokeTask @ angular2-polyfills.js:422Zone.runTask @ angular2-polyfills.js:320drainMicroTaskQueue @ angular2-polyfills.js:541ZoneTask.invoke @ angular2-polyfills.js:493
angular2-polyfills.js:126 GET http://127.0.0.1:8001/components/icon/%5C%22default-theme%5C%22 404 (File not found)

**Comment by d3viant0ne** [comment]
Same error on a different project.

In my case, backing the Angular2 package version to beta.13 is a temporary work around.

**Comment by jelbourn** [comment]
The demo is served locally with `ng serve`. It's only really for development purposes at the moment; we're not in a position to offer troubleshooting advice for bringing it up, especially for different environments.
