### ISSUE TITLE
Small svg icons

### ISSUE THREAD

**Issue by raciasolvo** [angular/material2#3441]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
24px width and 24px heght of the svg icon
![image](https://cloud.githubusercontent.com/assets/22774388/23586877/b2e42a0e-01af-11e7-9150-4d2710a20e01.png)

#### What is the current behavior?
15-21px width and 24px height of the svg icon
![image](https://cloud.githubusercontent.com/assets/22774388/23586862/8071295a-01af-11e7-97c2-15a49c8f2fa1.png)

#### What are the steps to reproduce?
http://plnkr.co/edit/Aa8KwKrPfady9EaamWwW?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
chrome last stable, windows 10

**Comment by jelbourn** [comment]
[md-icon is set to 24x24](https://github.com/angular/material2/blob/master/src/lib/icon/icon.scss#L5)

**Comment by raciasolvo** [comment]
Reopen https://github.com/angular/material2/issues/8699
