### ISSUE TITLE
menu.openMenu() not working

### ISSUE THREAD

**Issue by doorman02** [angular/material2#3445]
#### Bug, feature request, or proposal:
I am trying to let an a href tag open a menu like this
```
<a class="my-custom-trigger" (click)="menu.openMenu()">
          <img />          
</a>
        <md-menu #menu="mdMenu">
          <button md-menu-item>
              Button1
            </button>
          <button md-menu-item>
              Button2
            </button>
        </md-menu>
```

When clicked I get the following error
self.parentView._MdMenu_60_4.context.openMenu is not a function

#### What is the expected behavior?
Menu should appear on openMenu()

#### What is the current behavior?
menu 

#### What are the steps to reproduce?
See code above

#### What is the use-case or motivation for changing an existing behavior?
To have a custom button to trigger the menu, not the default button.

#### Which versions of Angular, Material, OS, browsers are affected?
latest angular, chrome

**Comment by fxck** [comment]
that method is not on mdMenu https://github.com/angular/material2/blob/master/src/lib/menu/menu-directive.ts but on mdMenuTrigger https://github.com/angular/material2/blob/master/src/lib/menu/menu-trigger.ts

**Comment by kara** [comment]
Yeah, mdMenu itself does not have a programmatic option. Instead, try using the `mdMenuTriggerFor` directive on your <a> tag.

```
<a [mdMenuTriggerFor]="menu">...</a>
```
