### ISSUE TITLE
mdSelect/mdInput - Floating labels top position does not match

### ISSUE THREAD

**Issue by liri2006** [angular/material2#3446]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Labels of select and input are on the same distance from text

#### What is the current behavior?
Select label is higher

#### What are the steps to reproduce?
http://plnkr.co/edit/HoLeVf0vbuYMmNQ2R0M1?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Look and feel of basic controls should be consistent

#### Is there anything else we should know?
Select underline is 1px lower than inputs

**Comment by frankspin89** [comment]
Duplicate of https://github.com/angular/material2/issues/2124

**Comment by liri2006** [comment]
True
