### ISSUE TITLE
mdSelect - Option search

### ISSUE THREAD

**Issue by liri2006** [angular/material2#3447]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
When option panel is open and user types something matching option should be "hovered"

#### What is the current behavior?
Nothing happens on typing

#### What is the use-case or motivation for changing an existing behavior?
Thats how build in select behaves (also Angular Material 1 https://material.angularjs.org/latest/demo/select)

**Comment by frankspin89** [comment]
What you are looking for is Autocomplete component: 

https://material.angular.io/components/component/autocomplete

**Comment by liri2006** [comment]
@frankspin89 , No, I'm not :)
Autocomplete does filtering on some data source, and select just highlights option by "short term user input".
Check out state select here -  https://material.angularjs.org/latest/demo/select
1. Open select
2. Press f.e. "k"

**Comment by crisbeto** [comment]
There's a pending PR for this at https://github.com/angular/material2/pull/2907.
