### ISSUE TITLE
Ripple Config

### ISSUE THREAD

**Issue by krigton** [angular/material2#3454]
#### Bug, feature request, or proposal:
Change the ripple config for all buttons for example

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
It prevents using css hacks and it's possible to fine tune the ripple for all elements for a certain type

**Comment by DevVersion** [comment]
Great idea. I need to see how this should be done, because I want to avoid issues with the `MD_DISABLE_RIPPLES` token.

**Comment by DevVersion** [comment]
@krigton I was made aware of the fact that I misread the issue. I actually don't think it would be elegant to provide a DI token to only set options for the `button` component (or others).

If we would support such DI token, then we would need to do this for other components as well.

**Comment by krigton** [comment]
Yes, my idea was that or a global configuration which affects all the ripples, or each component could have it's own configuration

**Comment by DevVersion** [comment]
@krigton Yeah I misread it and understood you requested for a configuration that affects all ripple elements.

Right now with #3463, developers are able to specify a global base-speed.

**Comment by krigton** [comment]
@DevVersion thanks, that's might be enough for us for now. thank you very much

**Comment by DevVersion** [comment]
@krigton You are welcome. Thanks for the idea!
