### ISSUE TITLE
select having problem with OnPush strategy

### ISSUE THREAD

**Issue by fxck** [angular/material2#3455]
https://gist.run/?id=16657b6c4bf3f58484c4d54ae373bfe7

probably some change detection issue, as it sets the correct value right after you click on the select

@kara @crisbeto

**Comment by crisbeto** [comment]
Looks like it's the same as https://github.com/angular/material2/issues/2269#issuecomment-283521375 which was fixed by https://github.com/angular/material2/pull/3434.
