### ISSUE TITLE
webpack error 

### ISSUE THREAD

**Issue by crystalwm** [angular/material2#3457]
#### Bug, feature request, or proposal:
![baidushurufa_2017-3-6_20-22-37](https://cloud.githubusercontent.com/assets/7902025/23609799/c2a67194-02aa-11e7-8903-d17f6360dae9.png)

#### What is the expected behavior?
I hope the angular/material2 can work in the webpack.

#### What is the current behavior?
I follow the guide docs,using the angular-cli, it works. however, when I try to use angular/material in the webpack, it fails

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.3.0 
material 2.0.0-beta.2

#### Is there anything else we should know?
I want a demo which angular/material can work in the webpack

**Comment by fxck** [comment]
Attach a plunk with the error. Without seeing any code it's hard to help you.

But my guess is that you are using `<md-input>`, which was deprecated and replaced with

```html
<md-input-container>
  <input mdInput />
<md-input-container>
```

**Comment by crystalwm** [comment]
thanks a lot ,I will try your suggestion
