### ISSUE TITLE
propagating clicks through Overlay 

### ISSUE THREAD

**Issue by fxck** [angular/material2#3458]
I'm not sure this is even possible without ugly hacks, so just throwing this out there.

Currently, when you have one select open and you try to open another (or focus any input), it will simply close the first select and do nothing. It's gotta be said that this is actually the native behaviour as well (on mac anyway), but I think it would be pretty nice if `Overlay` would be able to determine that there's a focusable material component underneath the coordinates it was closed from by clicking and trigger focus/open whatever.

https://gist.run/?id=546a55a20f515cc2cb551f891d426c43

**Comment by jelbourn** [comment]
We actually do this on purpose in order to mimic the native behavior ([and same in AngularJS Material](https://material.angularjs.org/latest/demo/menu)). The idea is that end-users are accustomed to this behavior and changing it would be surprising.
