### ISSUE TITLE
MdTabGroup inside #elseTemplate causes browser's tab to crash silently.

### ISSUE THREAD

**Issue by thibaultsavary** [angular/material2#3466]
#### Bug, feature request, or proposal:
Bug
The bug may be related to the `MdTabGroup/MdTab` implementation or to the new implementation of `ngIf` 

#### What is the expected behavior?
It should work.

#### What is the current behavior?
Browser's tab crashes silently (IE, Chrome, Edge)

#### What are the steps to reproduce?
**Working**
```html
<div *ngIf="someBool">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
</div>

<div  *ngIf="!someBool">
  <md-tab-group>
    <md-tab label="1">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </md-tab>
    <md-tab label="2">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </md-tab>
    <md-tab label="3">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </md-tab>
  </md-tab-group>
</div>
```
**Not working**
```html
<div *ngIf="someBool; else tmpl">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
</div>

<ng-template #tmpl>
  <md-tab-group>
    <md-tab label="1">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </md-tab>
    <md-tab label="2">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </md-tab>
    <md-tab label="3">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </md-tab>
  </md-tab-group>
</ng-template>
```
Same behavior when using the `then #thenTmpl else #elseTmpl` syntax.

#### Which versions of Angular, Material, OS, browsers are affected?
Material 1.0.0-beta-2
Angular 4.0.0-rc2

**Comment by andrewseguin** [comment]
I'm not able to replicate this issue with Angular 4.0.0-rc2. I did however run into some other bugs with templating that the core team is currently working through for the next release.

**Comment by thibaultsavary** [comment]
This seems to be related: 
#3461 
angular/angular#14873

In my real application the `boolean `is modified via button click event.
This may be the reason why you can't reproduce, so the `MdTabGroup `may not be the problem there.
I will close this issue and re-open it if it's still present after angular/angular#14873 fix.
