### ISSUE TITLE
md-input no longer works. Must use mdInput

### ISSUE THREAD

**Issue by kevupton** [angular/material2#3471]
#### Bug, feature request, or proposal:
![image](https://cloud.githubusercontent.com/assets/2093615/23643240/2c7ebbca-034c-11e7-9174-c5e0ccb264b3.png)

#### What is the expected behavior?
No error. It works.

#### What is the current behavior?
Errors and breaks the page

#### What are the steps to reproduce?
use src code:
```html
<md-input-container>
    <input md-input placeholder="E-Mail" type="text" name="email" required [(ngModel)]="email">
</md-input-container>
```

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
beta-1 worked, but now upgrading to beta-2 it fails.

#### Which versions of Angular, Material, OS, browsers are affected?
beta-2

#### Is there anything else we should know?
Use `mdInput` instead of `md-input` works.

Example:
```html
<md-input-container>
    <input mdInput placeholder="Password" type="password" name="password" required [(ngModel)]="password">
</md-input-container>
```

**Comment by fxck** [comment]
Yes, and?

**Comment by kevupton** [comment]
my bad just saw changelog
