### ISSUE TITLE
Md Dialog Configuration

### ISSUE THREAD

**Issue by krigton** [angular/material2#3472]
#### Bug, feature request, or proposal:
Have the possibility to add class name for the overlay pan using the DialogConfig 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
We would be able to target the overlay pane with specific styling.

**Comment by fxck** [comment]
https://github.com/angular/material2/pull/1584

**Comment by krigton** [comment]
thanks, not easy to find :D. going to close this one

**Comment by xtianus79** [comment]
@krigton what was the resolution for this

**Comment by krigton** [comment]
hm not sure, I guess the changes were merged into beta.3. Did not tested yet

**Comment by xtianus79** [comment]
Has this functionality been added? and if so is there any documentation as to how to accomplish this?

**Comment by MatthewTrout** [comment]
`panelClass` is listed in the docs but nowhere to be found in the source.  Assuming just not yet implemented?
