### ISSUE TITLE
md-select does not seem to have the ability to tie into dom ($event) 's i.e. $event.target.value

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#3477]
Bug, and or feature request
I need to aquire the selection of the dropdown which would occur from a dom event.  

#### What is the expected behavior?
The expected behavior when using a drop down and attaching it to a change event would produce the the following string value from a selected dropdown.  $event.target.value === 'selected value'  

i.e. choice A === 'First Selection'

#### What is the current behavior?
The md-select doesn't seem to have the eventemitter for the $event property.  

#### What are the steps to reproduce?
It doesn't work
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
So that a user can tie in drop down selections to utilize in the component

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.4.8 /// material 2.0.0-beta-2

#### Is there anything else we should know?
nope

**Comment by mmalerba** [comment]
`<mat-select>` has a `selectionChange` output that can be used for this purpose: https://github.com/angular/material2/blob/master/src/lib/select/select.ts#L451
