### ISSUE TITLE
md-card-avatar is no longer working

### ISSUE THREAD

**Issue by RedFour** [angular/material2#3480]
I've recently upgraded to beta 2, and md-card-avatar is no longer working. It use to make a small circle image, but now it just shows the what looks to be the default width and shrunken height. The example in the new documentation in https://material.angular.io/components/component/card is broken as well, where it doesn't show anything at all for that element.

**Comment by kara** [comment]
@RedFour Yeah, the card avatar was broken in beta.2 because the directive selector wasn't updated properly with the prefix change. [The fix](https://github.com/angular/material2/pull/3134) is now in master, so it should go out with the next release.
