### ISSUE TITLE
Non-core contributors need a way to mark a PR as ready for review

### ISSUE THREAD

**Issue by counsellorben** [angular/material2#3485]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
When a non-core contributor submits a PR and that PR is ready for review, a core member should assign it for review in a timely manner.

#### What is the current behavior?
When a non-core contributor submits a PR which is ready for review currently, that request may remain unassigned and unreviewed for an extended period.

**Comment by fxck** [comment]
I think they should try and get on top of PRs generally. There are PRs even from the team members that wait weeks or months to be reviewed, or are even already reviewed and labelled as ready to merged and still wait weeks to be actually merged.

The whole process seems a little unorganised a ineffective.

**Comment by jelbourn** [comment]
We consider "unlabelled" PRs as ready for review unless the author specifically says that it's in-progress. Sometimes we are just slow to review PRs.
