### ISSUE TITLE
Invalid ("error") underline on form inputs should be 2px thick even when not focused

### ISSUE THREAD

**Issue by natsid** [angular/material2#3490]
#### What is the expected behavior?
According to the [Material spec](https://material.io/guidelines/patterns/errors.html#errors-user-input-errors), (although it's not explicit), it looks like a form input's underline should be red if it's been touched and is invalid, even when it's in the focused state. Also, when it is in the unfocused state, it should be red and maintain the same thickness as in the focused state.

#### What is the current behavior?
Currently, the underline is only red when it's touched/invalid and _un_focused. And when it is red in the unfocused state, it is thin, like the gray unfocused underline.

#### What is the use-case or motivation for changing an existing behavior?
Our project requires the behavior that appears in the Material spec. While this can be done manually, it seems like it would be reasonable default behavior.

Thanks!

**Comment by mmalerba** [comment]
I believe this has been fixed in master

**Comment by natsid** [comment]
Thanks! Looks like it is indeed always red now, but not always thicker. Even though inputs typically get a thinner underline when they are out of focus, it looks like they should maintain the thick underline when they are invalid, as seen [here](https://material.io/guidelines/patterns/errors.html#errors-user-input-errors). Thanks for checking this out - I know it's small.
