### ISSUE TITLE
Bug:  Autocomplete value and viewValue,

### ISSUE THREAD

**Issue by hengkyz** [angular/material2#3492]
`city = [{'value':'1','viewValue':'city_name'}]`

`<md-autocomplete #city="mdAutocomplete">
<md-option *ngFor="let city of cities " [value]="city['id']">
{{ city['name'] }}
</md-option>
</md-autocomplete>`

when we type in the field it will show the viewValue and its correct,
but after we choose the option the field will show the value instead of viewValue,
this behavior different with select component which is correct,
or am i miss something here?

**Comment by kara** [comment]
When your control value and display value are different, you'll want to use `displayWith` to tell the autocomplete how to reconcile them. See [documentation here](https://material.angular.io/components/component/autocomplete).
