### ISSUE TITLE
`md-tab-nav-bar` ink broken (wrong width on init)

### ISSUE THREAD

**Issue by fxck** [angular/material2#3495]
https://gist.run/?id=9bb0552a140e5475264c81e54798ac8c

![image](https://cloud.githubusercontent.com/assets/1303561/23696883/d76105ae-03e5-11e7-8b12-7c5131bb0af8.png)

@andrewseguin

**Comment by fxck** [comment]
Hello? Anyone?

**Comment by kelsmj** [comment]
I am seeing this as well

**Comment by zpydee** [comment]
+1

**Comment by willshowell** [comment]
@fxck with #3622 landed, your gist appears to be fixed. There's still an issue with resizing, but I opened a separate issue for that (#3845).
