### ISSUE TITLE
mdTooltip wrong position when used inside a component with OnPush

### ISSUE THREAD

**Issue by fxck** [angular/material2#3497]
https://gist.run/?id=2df959fa72c4d9839dd4e621d73a0f73

![image](https://cloud.githubusercontent.com/assets/1303561/23701364/c3bf24a2-03f6-11e7-8fc4-a36d61bca1d9.png)

my guess is that it tries to calculate the position before the content is set (you can actually see it flicker as an empty tooltip for a few milliseconds)

cc @andrewseguin

**Comment by fxck** [comment]
Can you perhaps please label (maybe even good for community) this @jelbourne I find these `OnPush` issues to be pretty important, given how angular focuses on speed and efficiency.. not to mention that `OnPush` makes stuff like @ngrx so great and a lot of people use ngrx.

**Comment by fxck** [comment]
It's broken even in the demo-app

![](https://media.giphy.com/media/3o7bu5Cwbs2mpdoaXu/giphy.gif)

@DevVersion @crisbeto can at least one of you label / assign this?

**Comment by jelbourn** [comment]
One of the larger items on the requires for final is "make sure everything works well with OnPush".
