### ISSUE TITLE
mdCheckbox

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#35]
- [x] Determine if component can be built on top of a native `<input type="checkbox">`
- [x] Unit tests
- [x] E2E tests
- [x] Documentation
- [x] Demo page

**Comment by traviskaufman** [comment]
Spoke offline with @jelbourn regarding building the component on top of the native checkbox control and determined that the value gained by doing so does not make up for the added complexity. So we're going to forgo using the native control.
