### ISSUE TITLE
[Tabs] Pagination does not show on resize

### ISSUE THREAD

**Issue by jefersonestevo** [angular/material2#3500]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
The tab labels pagination should be shown whenever the labels exceed the width of the tab header

#### What is the current behavior?
When the user resize the page, the pagination is not shown. To show it, the use must add a new tab or select one of the list

#### What are the steps to reproduce?
[Plunker](http://plnkr.co/edit/KajyXotY8ifQXUpgQ3vb?p=preview)
Move the plunker divider to see

Full width:
![image](https://cloud.githubusercontent.com/assets/3085585/23710531/d3a70376-03fb-11e7-8c65-ceb29c0b64bd.png)

Resized:
![image](https://cloud.githubusercontent.com/assets/3085585/23710541/dd60e850-03fb-11e7-872c-d3a398e4fd36.png)

Resized after clicking on a tab:
![image](https://cloud.githubusercontent.com/assets/3085585/23710560/ea9ad760-03fb-11e7-80fb-d3fbe3ce14cd.png)

#### Which versions of Angular, Material, OS, browsers are affected?
All. The component is not updating the pagination status when the browser is resized.

**Comment by mscu** [comment]
I'm having the same issue and it is important for mobile support

**Comment by caiusCitiriga** [comment]
Hi everybody! Do you think that this issue can be related to the current one? 
#8788

**Comment by andrewseguin** [comment]
Pagination is updated on resize, this issue should have closed a while ago
