### ISSUE TITLE
bug(tab): Border of selected tab is incorrect with long label and window resize

### ISSUE THREAD

**Issue by jefersonestevo** [angular/material2#3501]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
The border (bottom) of the selected tab should match the width of the selected tab label

#### What is the current behavior?
When the tab has a long label it show just the first words of each label, but the border (bottom) still keeps it's initial width

#### What are the steps to reproduce?
[Plunker](http://plnkr.co/edit/1e33VqxiaqibUK4QmSZ9?p=preview)
Resize the divider and you can see that the label change it's content but the bottom keep it's width

Tabs with full width:
![image](https://cloud.githubusercontent.com/assets/3085585/23710306/08b78c6c-03fb-11e7-98d7-4c8e05d6b964.png)

Resized tab:
![image](https://cloud.githubusercontent.com/assets/3085585/23710340/24b5c03c-03fb-11e7-8c1b-7cb492147dbf.png)

#### Which versions of Angular, Material, OS, browsers are affected?
All

#### Is there anything else we should know?
I'm not that good at english so if you doesn't understand something just ask me, haha

**Comment by ah-kevin** [comment]
##  I encountered the same problem!

**Comment by ah-kevin** [comment]
I encountered the same problem!

**Comment by ah-kevin** [comment]
@jefersonestevo How did you solve it?

**Comment by jefersonestevo** [comment]
@ah-kevin I haven't solved it, haha, I've just opened the issue so that someone can look at it later

**Comment by jelbourn** [comment]
Tracking via #3044
