### ISSUE TITLE
Add gulp build tasks for examples

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#3518]
We should build the examples as a component library similar to how we build the material library itself and include the build output in the bundle that's published to material2-docs-content.

@DevVersion would you be able to tackle this?

**Comment by DevVersion** [comment]
@jelbourn Sure. I just hope we can make the changes without interfering with #3443.

**Comment by jelbourn** [comment]
Coming back to this: we should use the same code for building both `lib/` and `examples/`, where the only input needed should be the root directory.

**Comment by DevVersion** [comment]
Yeah that's what I planned to do. Let's take a look at this next week.
