### ISSUE TITLE
Slide toggle - (change) event will be fired even when the slider has not change.

### ISSUE THREAD

**Issue by skyfremen** [angular/material2#3526]
#### Bug, feature request, or proposal:
This bug occurs intermittently. When toggling the slider quickly, the slider might not toggle however the (change) event will still fire.

https://plnkr.co/edit/zMzNTiSz6OmxbrJZSUnP?p=preview
![slide-toggle_change_event](https://cloud.githubusercontent.com/assets/22805288/23732574/ce50944c-04ae-11e7-9f28-b507f812f816.jpg)

#### What is the expected behavior?
The event should not fire when the value is not changed.

#### What is the current behavior?
The event will fire even when the value is not changed.

#### What are the steps to reproduce?
1) Using the [Plunker](https://plnkr.co/edit/zMzNTiSz6OmxbrJZSUnP?p=preview) provided toggle the slider quickly. 
2) The last 10 event calls will be displayed
3) Occasionally, the slider will not toggle however the (change) event will still fire e.g. (true true) (false false)

#### What is the use-case or motivation for changing an existing behavior?
The event should not fire when the value is not changed.

#### Which versions of Angular, Material, OS, browsers are affected?
Tested on
Angular: 2.4.6
Material: 2.0.0-beta.2
OS: Windows
Browser: Chrome

#### Is there anything else we should know?
NA

**Comment by rhino5oh** [comment]
This is still an issue for me. Using material 6.0.0-beta.2
