### ISSUE TITLE
Sidenav md-sidenav-container and hammer.js swiperight event

### ISSUE THREAD

**Issue by ddyrcz** [angular/material2#3530]
#### Bug, feature request, or proposal:
Bug 

#### What is the expected behavior?
Swiperight  event (hammer.js) fires on the android device within the google chrome v56 

#### What is the current behavior?
Swiperight  event (hammer.js) fires on the desktop with the google chrome v56 but doesn't fire on the android device

#### What are the steps to reproduce?

**Note**: In both plunkers the 'swiperight' event should open the sidenav

Plunker that reproduce the problem. The 'swiperight' event of the md-sidenav-container element does not fire on the mobile device
https://plnkr.co/edit/jYurh5UjMS1l4p80YDS4?p=preview

Here is example where the 'swiperight' event of the div element fires, event on the android device
https://plnkr.co/edit/a715XrdYk0z4b0hlzpwk?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Android 6.0
Google Chrome v56

**Comment by nstohler** [comment]
I ran into the same issue too, with Chrome 58.0 on Android (whereas the standard browser on the device (MIUI8)) had no problems):

https://plnkr.co/edit/uJ3n8XedvCCdeUHXKpwX?p=preview

The same page works on iOS Chrome.

**Comment by mmalerba** [comment]
It sounds like an issue with hammer.js, I recommend filing an issue there: https://github.com/hammerjs/hammer.js/issues
