### ISSUE TITLE
Add a core.umd.js bundle to published package

### ISSUE THREAD

**Issue by mikehaas763** [angular/material2#3534]
I'm willing to put the PR together for this. I would like to rely on Overlay and Portal. So it'd be nice to import just a material core.umd.js and avoid the other Material components.

Will the PR be considered/accepted if I take time putting it together?

**Comment by DevVersion** [comment]
@jelbourn If we do this, then I would highly recommend after PR https://github.com/angular/material2/pull/3443. Otherwise there will be *X* rebases.

**Comment by mikehaas763** [comment]
That's fine I'll keep rebasing off your branch until it gets merged!

**Comment by mikehaas763** [comment]
@DevVersion meaning point my app's build to `CoreModule` and compile that?

**Comment by DevVersion** [comment]
@mikehaas763 Yeah just using `MdCoreModule` instead of `MaterialModule` would do it.

Make sure you have a bundler, like Webpack 2, that automatically removes the unused chunk of code.

**Comment by mikehaas763** [comment]
Yeah and I've done that before but it always had weird issues when pointing my apps build at something in node_modules. You gotta pretty much set up a completely separate config that ignores any longing etc. would just be nice to consumers to have a core bundle already built

**Comment by DevVersion** [comment]
The package structure has changed. Currently we only ship a bundle of the full Material library.

We have plans on shipping the different components bundled as well. This would then include a `core.js` bundle.
