### ISSUE TITLE
Stop using autoprefixer

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#3536]
Due to complications with the internal Google build system, it's not feasible for us to use autoprefixer for internal Google applications that are consuming Angular Material. The most straightforward thing for us to do, then, is to stop using it and capture any necessary CSS vendor prefixes in the source. The steps necessary:

* Determine which CSS properties need to be prefixed and document this
* Create sass mixins for those properties
* [Bonus] Create a  stylelint plugin that prevents these properties from being added without a prefix.

**Comment by rassulcrowe** [comment]
Is anyone who is currently working on this issue?

**Comment by rassulcrowe** [comment]
Ooooh it is already closed...

**Comment by victorschinaider** [comment]
I think this issue shouldn't be open, right?

**Comment by crisbeto** [comment]
It will be closed once the PR is merged.
