### ISSUE TITLE
Dialogs are stretching the entire viewport height

### ISSUE THREAD

**Issue by mazja** [angular/material2#3538]
#### Bug, feature request, or proposal:
Dialogs are stretching the entire page height. 

#### What is the expected behavior?
Dialog should be sized automatically based on its content.
![dialog_fixed](https://cloud.githubusercontent.com/assets/26309799/23767758/9f71ba92-04be-11e7-97fc-97b466d4571b.png)

#### What is the current behavior?
Dialogs are currently rendering with a height: 100% which causes them to stretch the entire viewport height.
![dialog_stretch](https://cloud.githubusercontent.com/assets/26309799/23765808/47882a66-04b7-11e7-9176-173555fc29c8.png)

#### What are the steps to reproduce?
I'm not able to reproduce this in a plunk (http://plnkr.co/edit/Wwkq3vBBPX3YIr79B6x4). I haven't been able to identify what exactly is triggering this behavior in our setup.

I've noticed that removing the height: 100% from the following section fixes the issue:

.mat-dialog-container {
    box-shadow: 0px 11px 15px -7px rgba(0,0,0,0.2), 0px 24px 38px 3px rgba(0,0,0,0.14), 0px 9px 46px 8px rgba(0,0,0,0.12);
    display: block;
    padding: 24px;
    border-radius: 2px;
    box-sizing: border-box;
    overflow: auto;
    max-width: 80vw;
    width: 100%;
    height: 100%; <-- Changing this to height: auto fixes the issue.
}

**Comment by crisbeto** [comment]
Can you check whether your document has a doctype? Similar issues have been reported before due to a missing doctype.

**Comment by cport1** [comment]
Is the same result happening on different devices?

**Comment by crisbeto** [comment]
It's not based on the device. This usually happens if the document is missing a doctype which puts it in quirks mode. You can verify that your page has a doctype either by checking your `index.html` or running `alert(!!document.doctype)` in the dev console.

**Comment by mazja** [comment]
Thanks for the tip!
I've verified that the doctype is missing on the document (document.doctype), although we have the <!DOCTYPE html> tag on the page. I'll investigate to see if there are any issues with missing closing tags that's triggering this behavior.

**Comment by mazja** [comment]
There was an unclosed tag on our html page that was causing this issue. Thanks for your help.
