### ISSUE TITLE
Hide scroll bar, but still being able to scroll - support for mainstream browsers

### ISSUE THREAD

**Issue by pageii** [angular/material2#3543]
Feature Request: Add option to hide scroll bar, but still being able to scroll.

#### What is the expected behavior?

Currently only webkit-based browser supports scrollbar hiding out of the box using CSS (i.e. Chrome & Safari) like so:

::-webkit-scrollbar { 
    display: none; 
}

#### What is the current behavior?
Scroll Bar is visible. Not always desirable for content presentation. One e.g. of no-scrollbar can be seen at [Medium](https://medium.com/).

#### Which versions of Angular, Material, OS, browsers are affected?

@angular/cli: 1.0.0-beta.31
node: 7.4.0
os: darwin x64
@angular/common: 4.0.0-beta.7
@angular/compiler: 4.0.0-beta.7
@angular/core: 4.0.0-beta.7
@angular/forms: 4.0.0-beta.7
@angular/http: 4.0.0-beta.7
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0-beta.7
@angular/platform-browser-dynamic: 4.0.0-beta.7
@angular/router: 4.0.0-beta.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 4.0.0-beta.7

**Comment by fxck** [comment]
I don't think this has anything to do with neither material or component development kit. Not to mention there are plenty of solutions for this already.

**Comment by mmalerba** [comment]
This isn't within the scope of angular material
