### ISSUE TITLE
inline wysiwyg editor inside md-input-container

### ISSUE THREAD

**Issue by ebtc** [angular/material2#3545]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Add a block element (like a div) to an input container.

#### What is the current behavior?
Not possible as it only expects input or textarea

#### What are the steps to reproduce?
```
<md-input-container fxFlex fxFill>
    <div id="{{elementId}}" mdInput>
        <span i18n class="text-muted">Start writing...</span>
    </div>
</md-input-container>
```
does not work as expected: styles the div but throws an error.

#### What is the use-case or motivation for changing an existing behavior?
Many WYSIWYG editors support inline editors, which mainly use block elements (e.g. tinymce). Inline editing seems more fitting to the material design scheme.

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9
@angular/platform-server: 2.4.9

**Comment by jelbourn** [comment]
Tracking via #4444
