### ISSUE TITLE
md-nav-bar is lost on the last version of Angular Material?

### ISSUE THREAD

**Issue by lukecorf** [angular/material2#3547]
Well... I try to use md-nav-bar in my aplication, but the navitor doesn't recognize the item. Why? I import all things to use angular material, and the others itens its ok.

Now I need use Tabs? or the navItem change?

**Comment by kara** [comment]
We do have `md-tab-nav-bar`, but we don't have a `md-nav-bar`. Are you perhaps thinking of AngularJS Material instead?

You can see `md-tab-nav-bar` docs here: https://material.angular.io/components/component/tabs

**Comment by Puff12138** [comment]
@kara , But i think it do exist, md-nav-bar: https://material.angularjs.org/latest/api/directive/mdNavBar, 
@lukecorf , i just tried to use md-nav-bar, unfortunately it seems related module missing, which i still haven't find yet. AND i don't see it in the components list of Angular Material(Tabs do exist and it works just like nav, but i still feel something ..strange, cause it belongs to <Layout>)

**Comment by Seankps** [comment]
@kara why doesn't Angular Material have a Nav? It just seems like a common, core feature that a modern UI framework should have
