### ISSUE TITLE
 Problem with Angular design

### ISSUE THREAD

**Issue by lukecorf** [angular/material2#3548]
I imported everything correctly according to the angular site itself. But my items do not work properly. Look at the picture:

![untitled](https://cloud.githubusercontent.com/assets/22321349/23795108/80ddf03c-0572-11e7-8307-dba98768396d.png)

When selecting the input it should be colored blue or purple. And the tabs also do not have colorization. How to solve this problem?

**Comment by fxck** [comment]
Github issues are for bugs and feature requests. If you believe this is a bug, create a plunk with reproduction code (https://goo.gl/DlHd6U). Otherwise use gitter or stackoverflow please.

**Comment by TTTee** [comment]
You have to apply all of the core and theme styles to your application. 

For the basic theme add this to your css file:
```css
@import '~@angular/material/core/theming/prebuilt/deeppurple-amber.css';
```

Or link to the stylesheet in your index.html:
```html
<link href="node_modules/@angular/material/core/theming/prebuilt/indigo-pink.css" rel="stylesheet">
``` 

See: https://material.angular.io/guide/theming
