### ISSUE TITLE
show available prebuilt themes in docs

### ISSUE THREAD

**Issue by lestard** [angular/material2#3550]
#### Bug, feature request, or proposal:
feature request documentation

#### What is the expected behavior?
In the [docs](https://material.angular.io/guide/theming) users should see a list of available prebuilt themes and a link to a sample page of each theme.

#### What is the current behavior?

No information of what themes are available and how they look like.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?

I like to use this great library but the documentation could be improved to make the start easier.

**Comment by M-a-c** [comment]
@jelbourn
Issue question:
Where should these examples be created?   
/src/lib/examples/theme-NameofTheme-overview ?
Just one and then reference the other defaults, or all 4 themes?

Extra question:
Also are there going to be more default themes? / a theme builder ?

**Comment by jelbourn** [comment]
We should list all of the prebuilt themes in the theming guide.

We will add more prebuilt themes before final.

We do want to add a theme builder to the docs site eventually, but that's more of a nice-to-have.

**Comment by DevVersion** [comment]
@M-a-c Are you looking into this?

**Comment by M-a-c** [comment]
Yeah I was going to tackle it Monday if thats ok. I don't have a pr for it right now.
I think this Add theming to docs should be re-added, for when there are more themes, before going gold.

**Comment by DevVersion** [comment]
Sounds good! Thanks.

**Comment by M-a-c** [comment]
Is sample link to each theme necessary ?

If its possible can someone open a P4 on the 'theme builder' and describe how it would work? I would love to work on something like that.

**Comment by DevVersion** [comment]
I think for now we only want to list all prebuilt theme paths in the theming guide.

We could do that with a Dgeni processor or just with `gulp transform`.

**Comment by M-a-c** [comment]
Reading up on Dgeni now, sorry for the confusion. I had no idea this existed. I was wondering how exactly this sorta magic happened. I'll dig for an example to figure this out.

**Comment by jelbourn** [comment]
I'm not sure this is something that needs to be done with tooling; the prebuilt themes will change infrequently enough that i'm okay with just manually listing them in the guide.

**Comment by M-a-c** [comment]
@jelbourn is it ok If I submit a pr for a static one, and open a less 'important task' for a tooled one later? I would like to try my hand at that, it might be useful to learn, and its one less thing to worry about later. Plus I would love to feel more comfortable with whats going on with the project so I can make larger contributions.

**Comment by M-a-c** [comment]
@DevVersion @jelbourn I'm a bit confused with who to follow, I'm pretty sure I'm more than half way done tooling a solution. Is it ok if I continue on that?

**Comment by DevVersion** [comment]
Please do what @jelbourn proposed.

 I initially thought that a dynamic solution would be appropriated but since we don't have frequent changes with the prebuilt-themes I can see Jeremy's point.

**Comment by M-a-c** [comment]
@DevVersion Thanks for the clarification.

**Comment by M-a-c** [comment]
@DevVersion can you pr my pull request #3826 its small 🌮

**Comment by M-a-c** [comment]
@jelbourn This issue can be closed too 😃 
Also is there a way that I can create a pr such that a merge closes the issue?

**Comment by jelbourn** [comment]
@M-a-c if your PR says "Fixes #3550" in the description it will close the issue automatically when merged.
