### ISSUE TITLE
build: umd bundle module name not working

### ISSUE THREAD

**Issue by nefcanto** [angular/material2#3551]
#### Bug, feature request, or proposal:
I need to be able to use Material 2, in an old fashion. I need to be able to include some css and javascript files in my HTML page, and bootstrap things and start using Material 2.

#### What is the expected behavior?
My module's dependency on Material 2 should be resolved and I don't see 'MaterialModule' is not defined, and I see that it actually works on my page.

#### What is the current behavior?
I see 'MaterialModule' is not defined error.

#### What are the steps to reproduce?
Create a simple html page, include these files from somewhere:

- core js shim
- zone
- rx
- core umd
- common umd
- compile umd
- platform browser umd
- platform browser dynamic umd
- form umd
- http umd
- material umd

then write this simple script:

```
var app = ng.core.Component({
    selector: 'app',
    template: '<h1>Hello Angular</h1>'
})
.Class({
    constructor: function () { }
});

var module = ng.core.NgModule({
    imports: [MaterialModule, ng.platformBrowser.BrowserModule],
    declarations: [app],
    bootstrap: [app]
})
.Class({
    constructor: function () { }
});

document.addEventListener('DOMContentLoaded', function () {
    ng.platformBrowserDynamic
      .platformBrowserDynamic()
      .bootstrapModule(module);
});
```

Then insert a simple `<app>loading...</app>` inside the body tag of the html file.

That's it all. Now open that HTML file inside the browser. It should say 'MaterialModule' is not defined.

I can't find a way to create plunker using CDN. I've started, please help to reproduce the issue. I can't find the required libraries and I can't upload them there.
https://plnkr.co/edit/u5Mpe8?p=info

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.4.9
material v2.0.0-beta.2

#### Is there anything else we should know?
We have a software production line that works just fine with Angular JS. But as we tried to use Material for Angular 1, we encountered a very stupid 'NaN' problem in themes. No theme is applied. We decided to migrate to Angular 2, and things work. But we don't want to use TypeScript, or ES6. We need to stick to ES5 for some time, and things are OK till here. But we can't include Material from somewhere, just as an ordinary javascript file and use it in our html pages.

**Comment by DevVersion** [comment]
There should be a global called `ng.material.MaterialModule` available in the UMD bundle?

**Comment by DevVersion** [comment]
The Material UMD bundle provides a similar `global` export as in `@angular/$PACKAGES`
