### ISSUE TITLE
Sense of asymmetry in material 2 (compared to 1)

### ISSUE THREAD

**Issue by AlexVangelov** [angular/material2#3561]
Working with material2 I feel that not everything looks so good visually by default.
One example is the text inside the button / sreenshoot with Chrome Version 56.0.2924.87 (64-bit):
![material 1 - 2](https://image.ibb.co/dtpkGF/mat_1_2.png)
It would be nice to meet all the official requirements for material design for all major browsers. [https://material.io/guidelines/components/buttons.html#buttons-style](https://material.io/guidelines/components/buttons.html#buttons-style) documentation
![material buttons](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0Bzhp5Z4wHba3NWNsQ1R2a19WV2M/components_buttons_main21.png)
I know, there is a lot of work on new components, but let's trace the compliance for a great visual experience.
Thank you.

**Comment by ciesielskico** [comment]
"There is a lot of work" - of course there is a lot of work, part of that work is identifying the components that do not comply with the official material spec.
If you want to help you can open issues describing bugs, but opening a ticket saying there is work to do is kind of silly, imho

**Comment by spock123** [comment]
@ciesielskico  He did kinda describing a bug, didn't he?

**Comment by AlexVangelov** [comment]
This is not a bug. I see that there is a divergence between official material design guidelines and this project. Reviewing the history of some common styles (like `_button-base.scss` and `lib/core/style/*`) it was decided properties like button height to be different. Maybe it should be.
@ciesielskico sorry for my extra comment pointing that the focus has shifted, since I'm not a contributor.
Hopefully my thoughts are helpful...
The above misalignment is fixable with `-webkit-baseline-middle` but not the right solution.

**Comment by jelbourn** [comment]
@AlexVangelov closing this, as it doesn't follow the issue template is and the feedback is somewhat vague ("I feel that not everything looks so good visually by default."). 

If you notice one or more instances where a component deviates from the spec, could you file issues for each of those? Specific, actionable feedback provided with the issue template is the best way to enable resolving any issues.
