### ISSUE TITLE
Angular 4 Support

### ISSUE THREAD

**Issue by shawnsz** [angular/material2#3565]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Angular 4 support

#### What is the current behavior?
1. Got warning message when rung npm install:
├── UNMET PEER DEPENDENCY @angular/common@4.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/core@4.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/http@4.0.0-rc.3
└── @angular/material@2.0.0-beta.2  (git+https://github.com/angular/material2-builds.git#07661f831d61727162b2231f9c24ba8c921eb262)

2. Got Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[ERROR ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): MdAutocomplete@0:0

#### What are the steps to reproduce?
1. Generate a new project with Angular/cli:
ng new ng4md2test --ng4
2. Install Material2 package
npm install --save https://github.com/angular/material2-builds.git
3. Import MaterialModule
4. ng build -prod

#### Which versions of Angular, Material, OS, browsers are affected?
Angular@4.0.0-rc.3, Material@2.0.0-beta.2 or master, macOS

#### Is there anything else we should know?
N/A

**Comment by crisbeto** [comment]
There already a few issues dealing with this. Closing as a duplicate.
