### ISSUE TITLE
tooltip html entity

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#3566]
How can I use a ```SafeHtml``` in a tooltip attribute?
Right now it always shows the html entity instead of the actual character.

Like ```&copy;```

With attributes it is not working, only works with ```innerHTML```.

:(

**Comment by andrewseguin** [comment]
We do not support SafeHtml in the tooltip attribute. It should be sufficient to put the actual character into the message string, e.g. https://plnkr.co/edit/DxM7r7BkLGusYTdLLDXb?p=preview

**Comment by nlgi** [comment]
It would be nice!
For example: we show a tooltip for a quick help, and add a html link in it to redirect with a QA, more explanation... Etc.
And for it, the tooltip should be "fixed" when the mouse is over :D 

Thanks for your work,
