### ISSUE TITLE
Radio button and checkbox baselines don't align

### ISSUE THREAD

**Issue by kara** [angular/material2#357]
When you put radio buttons and checkboxes side-by-side, they have different baselines.

cc: @jelbourn

**Comment by MartinMa** [comment]
On Firefox 46.0.1 radio buttons are totally misaligned (see screenshot). Checkboxes are ok.

![image](https://cloud.githubusercontent.com/assets/123297/15469538/281f3c60-20eb-11e6-84f8-8aa22e4928d2.png)
