### ISSUE TITLE
bug(input): y-scrollbar is displayed when placeholder text line-height is bigger than md-input-placeholder height (on IE browser)

### ISSUE THREAD

**Issue by leo6104** [angular/material2#3570]
#### Bug, feature request, or proposal:
Bugs

#### What is the expected behavior?
Whatever placeholder text it is, floating placeholder (md-input-placeholder) should be rendered without y-scrollbar on IE browser.

#### What is the current behavior?
some character-set (such as Korean)'s line-height can be bigger than md-input-placeholder height. 
![Image](https://s22.postimg.org/pmakw3729/test.png)

#### What are the steps to reproduce?
visit the plnkr.co on IE 11 browser windows 10
http://plnkr.co/edit/Z0XDCASXPMhCj07KB1Nf?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Changing supported language of website to Korean.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular material - master branch and beta.2 branch 
Angular - 4.0.0-rc.2 
OS: Windows 10
browser: IE 11

**Comment by ciesielskico** [comment]
i have experienced the same on latest Chrome in my app.
