### ISSUE TITLE
autocomplete "(onItemSelected)"="do($event)"

### ISSUE THREAD

**Issue by djleonskennedy** [angular/material2#3576]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
@Output() event on item selected

#### What is the current behavior?
not @Output() event on item selected

#### What is the use-case or motivation for changing an existing behavior?
I'm currently using `breeze` client, that allows to update property from `ngModel` only.
In this case one way to update property to listen if autocomplete item selected

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular": "~2.4.3",
"@angular/material": "^2.0.0-beta.2",

**Comment by djleonskennedy** [comment]
md-option has onClose, it can be used as workaround

**Comment by chouclee** [comment]
``md-option`` has ``onSelect``, is this what you want?
```
<md-autocomplete #appSearch="mdAutocomplete">
  <md-option *ngFor="let app of apps" [value]="app.name" (onSelect)="onAppSelect(app)">
    {{ app.name }}
  </md-option>
</md-autocomplete>
```

**Comment by djleonskennedy** [comment]
@chouclee Yes, i've used `md-option`'s onClose, it'd be nice to see it it in examples somewhere!

**Comment by willshowell** [comment]
As a note, the api changes from `onSelect` to `onSelectionChange` in #2722 to account for select/deselect of multiple options.

**Comment by gtzinos** [comment]
Guys onSelect method not exists.

**Comment by pacoita** [comment]
What is then the correct way to get a method fired on a selection? I used the following code and it was working with a previous release, but now no more with the latest version:

`<md-autocomplete #panel="mdAutocomplete" [displayWith]="displayFn">
    <md-option (onSelect)="selected(country)" *ngFor="let country of filteredCountries | async" [value]="country">
        <div class="selector-elements">
          <span>
              <img [src]="getFlagPath(country.code)" [width]="24" [height]="24" /> 
          </span>    {{ country.name }}
          </div>
    </md-option>
  </md-autocomplete>`

**Comment by rupinr** [comment]
I used onSelectionChange  instead of onSelect.

<md-option (onSelectionChange)="test($item)" *ngFor="let option of filteredTrain | async"
    [value]="option">
    {{ option.viewValue }}
    </md-option>

test(item){
console.log(item);
 }.

But I only see undefined in console. Is there anything wrong here?

**Comment by gauravbh1** [comment]
@rupinr 
Instead of (onSelectionChange)="test($item)" use (onSelectionChange)="test(option)"
