### ISSUE TITLE
SnackBar broken without animation

### ISSUE THREAD

**Issue by Bretto** [angular/material2#3588]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
Ng4rc2 annimation is broken, the SnackBar doesn't work anymore due to this. I think it should work without requiring animations.  

#### What is the current behavior?
It's broken

#### What are the steps to reproduce?
try to use the SnackBar with Ng4rc2

#### What is the use-case or motivation for changing an existing behavior?
making it work no matter what, remove the functional dep on Animation 

#### Which versions of Angular, Material, OS, browsers are affected?
Ng4rc2 - Material2.0.0-beta.2

#### Is there anything else we should know?
Great job guys keep-up the good work :+1:

**Comment by jelbourn** [comment]
Angular Material currently does have a hard dependency on the animation module. We don't have any plans to change this now.

**Comment by Bretto** [comment]
Do you think its not working with Ng4rc2  for other reasons then ?

**Comment by jelbourn** [comment]
@Bretto I don't follow what you mean. It sounded like you were saying that it doesn't work when the animation module is not available, which is expected.

**Comment by Bretto** [comment]
lol Sorry I miss read your answer...
