### ISSUE TITLE
autocomplete doesn't trigger parent form change event

### ISSUE THREAD

**Issue by byunru** [angular/material2#3590]
The parent form's valueChanges been triggered properly with the value changed from other input controls, but failed on autocomplete.
Although I added two properties, [(ngModel)] and name, to the input tag, same as other regular input tag,
when I change autocomplete's input value, the parent form's valueChanges doesn't been fired.

**Comment by mmalerba** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
