### ISSUE TITLE
[select] Default value not working

### ISSUE THREAD

**Issue by jlno** [angular/material2#3594]
#### Bug, feature request, or proposal:

> my-comp.html

```
<md-select placeholder="State" [(ngModel)]="myState">
   <md-option *ngFor="let state of states" [value]="state.code">{{ state.name }}</md-option>
</md-select>
```
> my-comp.ts

```
class MyComp {
  myState = 'AL';
  states = [{code: 'AL', name: 'Alabama'}];
}
```

#### What is the current behavior?
No item selected.

**Comment by willshowell** [comment]
Can you replicate the issue with a Plunker? Use the [template here](http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview).

**Comment by jlno** [comment]
@willshowell http://plnkr.co/edit/a3KtobwPGzHY4QJPDkMB?p=preview

**Comment by willshowell** [comment]
@jlno in order to use `[(ngModel)]`, you need to import the `FormsModule` into your NgModule. It looks like you instead used `CUSTOM_ELEMENTS_SCHEMA` to get rid of the error, and that isn't the right approach.

http://plnkr.co/edit/xNKeDyZFpyJbNkA34cAq?p=preview

**Comment by jlno** [comment]
@willshowell tnx!
