### ISSUE TITLE
Update Material to support Angular v4

### ISSUE THREAD

**Issue by FilipeQ** [angular/material2#3595]
#### feature request, or proposal:
Update material 2 to support Angular v4

#### What is the expected behavior?
Support angular last version

#### What is the current behavior?
If we update angular v2 project to v4 with material 2, we got some errors in console. Like deprecated elements.

#### What is the use-case or motivation for changing an existing behavior?
Support angular last version

#### Which versions of Angular, Material, OS, browsers are affected?
Material : 2.0.0-beta.2
Angular : 4.0.0-rc.3

**Comment by crisbeto** [comment]
We have a few issues to track this. Closing as a duplicate.

**Comment by NCC1701M** [comment]
@crisbeto 
Which are those issues? Could you please mark this as a dublicate of those issues?

**Comment by leo6104** [comment]
@NCC1701M It might be #3174 Issue.

**Comment by crisbeto** [comment]
https://github.com/angular/material2/commit/cd55082a488e58a3f4948bba8e5d0a6771a57233 includes Angular 4 support and was merged yesterday. It'll be in the next release.
