### ISSUE TITLE
mdToolbar

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#36]
- [ ] Unit tests
- [ ] E2E tests
- [ ] Documentation
- [ ] Demo page

**Comment by danwkennedy** [comment]
Does this include the scrolling techniques outlined [here](https://www.google.com/design/spec/patterns/scrolling-techniques.html#)?

**Comment by jelbourn** [comment]
@danwkennedy we'll be taking that into mind when working on the design.

**Comment by sothychan** [comment]
@jelbourn I was going to submit an issue to request/build this component.  Can you give me the status of this?  Is there something I can do to help with this component?

**Comment by jelbourn** [comment]
@sothychan If you wanted to contribute this component, the first step would be to write a design document that follows our template: [Design doc template](https://docs.google.com/document/d/1kpQStAn9L-NX_1bGz_4fXNeZgerWC0mUJHun72bF240/edit)

Once the team reviews and approves the doc, coding can start. Some things you should be aware of:
* Our [coding standards](https://github.com/angular/material2/blob/master/CODING_STANDARDS.md) and [code review process](https://github.com/angular/material2/blob/master/CODE_REVIEWS.md)
* Our TypeScript source is transpiled into a [Dart](https://www.dartlang.org/) version that must pass DartFormat and DartAnalyzer (and eventually unit tests as well)
* [How our theming works](https://github.com/angular/material2/blob/master/docs/scss-theming.md)
* Should follow coding conventions matching the rest of the repo (especially the scss).

For the toolbar itself, I don't there there's actually much complexity to it, so the design doc will be pretty straightforward. Let me know if you intend to move forward with it in the near future; if not, we will likely complete this before too long.

**Comment by DevVersion** [comment]
I started writing the associated design doc - [See here](https://docs.google.com/document/d/1vJWHSKYHrIS4Yh4k3OjPLbmW4vG7xSXrXqrkfNqMcUQ/edit?usp=sharing)

**Comment by sothychan** [comment]
My apologies @jelbourn.  I made the mistake of watching the entire repo and somehow missed your direct message to me.  I'm guessing I'm too late at this point, but if not, I would love to move forward and contribute.

**Comment by DevVersion** [comment]
@sothychan I'm sorry for going ahead and writing the docs, but I thought you are not anymore interested in doing this, so I did this. So if this Design Doc got approved I would like you to review my PR :)

**Comment by sothychan** [comment]
@DevVersion No worries at all.  I'm sure there's a LOT more stuff to do so there are many chances to contribute :).  Thanks for taking the initiative.  I got lost in the emails :/.

I am looking at your design doc now.

**Comment by DevVersion** [comment]
@sothychan Yes definitely, Thanks for a notifying about a few spelling comments! - I accepted your fixes.

**Comment by sothychan** [comment]
@DevVersion The design doc looks good to me.  Great job!

**Comment by jelbourn** [comment]
@devversion I'm flying all day today, will take a look tomorrow.

**Comment by DevVersion** [comment]
@jelbourn Sorry, didn't reference that in the `WIP` branch. This should be closed.

**Comment by jelbourn** [comment]
Closed by #146
