### ISSUE TITLE
[Tooltip] Tooltips in IE11 simply broken.

### ISSUE THREAD

**Issue by YurtYurt** [angular/material2#3605]
#### Bug, feature request, or proposal:
Tooltips work fine in Chrome, In IE however they fail to show up visually.

#### What is the expected behavior?
Tooltips should be visible in the DOM and to the user.

#### What is the current behavior?
Tooltips render in the DOM, but not visually, almost as if change detection isn't firing completely.  Changing a style on the tooltip while it exists in the DOM, causes it to pop in suddenly visually for the user.

#### What are the steps to reproduce?

Plunker works in Chrome as expected, but breaks in IE11.
http://plnkr.co/edit/Zx6laLQrd3AlgFWpImph?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Tooltips should be supported in IE11...

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.6
Angular Material - 2.0.0-beta.2
IE11

**Comment by andrewseguin** [comment]
Angular requires the web animations framework that [not all browsers support natively](http://caniuse.com/#feat=web-animation), including IE11. 

Fortunately there is a [polyfill](https://github.com/web-animations/web-animations-js) that enables web animations for all browsers. You can see more information by reading the [Angular Animations](https://angular.io/docs/ts/latest/guide/animations.html) guide.

Here's a working example that includes the animations polyfill: http://plnkr.co/edit/gDOx30hpVUIXkSl6mcRq?p=preview
