### ISSUE TITLE
Plunker examples do not install web animations polyfill

### ISSUE THREAD

**Issue by andrewseguin** [angular/material2#3607]
Material plunker examples, both in the issue template and on material.angular.io, do not include the web animations polyfill. As a result, some browsers do not properly display Material.

For example, tooltips do not display on IE11.

To reproduce, navigate to the standard issues plunker on IE11: https://goo.gl/DlHd6U . Add an mdTooltip to any element, and see that it does not work.

To fix, add the animations polyfill, e.g.
` <script src="https://cdnjs.cloudflare.com/ajax/libs/web-animations/2.2.2/web-animations.min.js"></script>`

See workaround working properly here: http://plnkr.co/edit/xyjJiU0hONwUQ3ErJp8W?p=preview

**Comment by DevVersion** [comment]
I just made the changes on the issue Plunker.
