### ISSUE TITLE
md-input ng-valid label md-empty error.

### ISSUE THREAD

**Issue by marcellokabora** [angular/material2#3612]
After reset my form the label input have the class md-empty and the placeolder is under the valuie of the md-input, can you fix this pls?

![screen shot 2017-03-15 at 10 22 22 am](https://cloud.githubusercontent.com/assets/200166/23941535/6cbbcb6a-0969-11e7-82be-230e9b04a2b7.png)

`   
form: FormGroup;

this.form = fb.group({
  name: ['', [
    Validators.required,
    Validators.minLength(3)
  ]]
});

this.firebase.subscribe(items => { 
  items.forEach(item => {
    this.form.controls[item.$key].reset(item.$value);
  })
})
`

**Comment by fxck** [comment]
Are you using OnPush by any chance? Either way, it would be great if you provided a plunk with reproduction of the bug.

**Comment by marcellokabora** [comment]
No im not usign this OnPush propriety, just try to reset the form with a value you can see the problem.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
