### ISSUE TITLE
A new md-toolbar-row is added into md-toolbar even when no content is outside md-toolbar-row elements

### ISSUE THREAD

**Issue by pravincar** [angular/material2#3613]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If all the content is placed in md-toolbar-row elements then a new row should not be added

#### What is the current behavior?
A new md-toolbar-row is added to the top even if there is no content outside of md-toolbar-row elements

#### What are the steps to reproduce?

Plunker
http://plnkr.co/edit/BOdPHzANIMYnq7GagIWR?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
 Angular v2.4.9, Material v2.0.0-beta.2, all browsers and OSs

**Comment by DevVersion** [comment]
Thanks for the issue. I have plans to fix this as part of #1718

**Comment by sebastianfdez** [comment]
It's still happening! Any news to fix it?
