### ISSUE TITLE
md-radio-group can't handle update with patchValue

### ISSUE THREAD

**Issue by paistitshare** [angular/material2#3614]
#### Bug, feature request, or proposal:

md-radio-group didn't mark the corresponding value as checked after updating reactive form with any kind of method e.g. patchValue() or setValue(). Also using the ChangeDetectionStrategy.OnPush didn't help.

#### What is the expected behavior?

md-radio-group should mark the corresponding radio button as checked.

#### What is the current behavior?

md-radio-group don't handle the changes made to attached reactive form.

#### What are the steps to reproduce?

Plunker template: http://plnkr.co/edit/pZ92nxOVMZNcxKTD0jF1?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.4.9, Material 2.0.0-beta.2, Chrome 56, MacOS Sierra

**Comment by fxck** [comment]
remove that setTimeout and it works http://plnkr.co/edit/DiLer3G1pfaKFib6ZtCQ?p=preview so it's more likely a change detection / out of zone problem rather than material2 bug

**Comment by DevVersion** [comment]
Yeah. In `OnPush` mode the `setTimeout` will not trigger a change detection as usually.

**Comment by DevVersion** [comment]
Keeping it open. I need to confirm that the component itself is not responsible at this point.

Because basically the radio component knows about it and could call `markForCheck`.

**Comment by paistitshare** [comment]
I've removed the `OnPush` change detection strategy flag and still getting this problem.

**Comment by jelbourn** [comment]
@tinayuangao can you figure out if there's an issue here?

**Comment by tinayuangao** [comment]
The problem is `md-radio-button`s are not available to `md-radio-group` if they are inside `md-card`.

It works well when changed template to 
````      
<md-radio-group formControlName="fontFamily">
        <md-radio-button *ngFor="let familyOption of fontFamilyOptions" [value]="familyOption">
              {{familyOption}}
        </md-radio-button>
</md-radio-group>
```
