### ISSUE TITLE
Slide toggle Enable/Disable Requires update

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#3619]
#### Bug, feature request, or proposal:

When using Slide Toggle with reactive form like below: 

`<md-slide-toggle color="accent" formControlName="isFeatured" [disabled]="form.get('field1').value>0">Featured</md-slide-toggle>
`

It shows the below warning in console:

```
It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
      when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
      you. We recommend using this approach to avoid 'changed after checked' errors.
       
      Example: 
      form = new FormGroup({
        first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
        last: new FormControl('Drew', Validators.required)
      });
```

**2nd Issue**

I have the form setup like this:

```
this.form = fb.group({
            field1: [0],
            isFeatured: [{ value: false, disabled: true }]
        });
```

If I try to programmatically enable the slide toggle for example on click of a button:

`<button (click)="enableSlideToggle()">Enable Slide Toggle</button>
`

```
enableSlideToggle(){
            this.form.controls['isFeatured'].enable();
}
```
It doesn't enable the Slide Toggle. Though the slide toggle stays disabled if we drag the control to right or left it enables the Slide Toggle. 

#### What is the expected behavior?

The Slide Toggle disabled should work like it works for radio buttons etc. i.e. without giving any warning for reactive form controls.

The programmatic  enabling and disabling should be reliable and consistent.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4 RC 3
Material 2 Beta 2
Windows 10
Chrome 57.xxx (64-bit)

**Comment by DevVersion** [comment]
Can you provide a Plunker please?

**Comment by DevVersion** [comment]
Tested it locally, I think the first warning is expected when using the ReactiveFormModule.

The warning basically says that it's recommended to set the `FormControl` to disabled using the `FormGroup` instance (Similar to the `md-checkbox`)

And I couldn't reproduce the 2nd issue. Enabling works fine for me.
