### ISSUE TITLE
Update needed to button documentation

### ISSUE THREAD

**Issue by jmylen** [angular/material2#3620]
#### Bug, feature request, or proposal:

Bug in the docs perhaps

#### What is the expected behavior?
https://material.angular.io/components/component/button is showing an example of a button where the text is transformed to uppercase however if you click on "Edit in Plunker" the text is not transformed. Assuming the behavior in plunker is correct then it would be helpful to indicate in the CSS tab that you are styling it.

#### What is the current behavior?

Currently in the docs it says..

/** No CSS for this example */

**Comment by andrewseguin** [comment]
Will be fixed in https://github.com/angular/material.angular.io/pull/132

**Comment by jelbourn** [comment]
Closing issue as fix is merged
