### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by softvar** [angular/material2#363]
npm WARN package.json angular2-webpack-starter@5.0.4 scripts['server'] should probably be scripts['start'].
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! Invalid name: "@angular2-material/card"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/softvar/angular2-webpack-starter/npm-debug.log

**Comment by jelbourn** [comment]
I can `npm install @angular2-material/card` just fine. This is likely a problem with your environment.

**Comment by softvar** [comment]
I'm able to install other packages.

Have tried it with node versions: `0.12.7`, `4.0.0` and `5.0.0` and corresponding npm versions.

I cloned [https://github.com/AngularClass/angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) and ran `npm install` and got this error. The project seems very promising in learning Angular2. I'm stuck right now. Would you be willing to help me in resolving this?
