### ISSUE TITLE
material template instead of ng-template warnings + require peer dependencies warnings

### ISSUE THREAD

**Issue by stefanaerts** [angular/material2#3632]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
angular version ^4.0.0-rc.3 + material ^2.0.0-beta.2
gives warnings.I included BrowserAnimationsModule but that did'nt help

#### Which versions of Angular, Material, OS, browsers are affected?
angular version ^4.0.0-rc.3 + material ^2.0.0-beta.2

#### Is there anything else we should know?
![image](https://cloud.githubusercontent.com/assets/3684599/23991881/2f9fc204-0a3b-11e7-896e-af2a07de987b.png)

![image](https://cloud.githubusercontent.com/assets/3684599/23991939/61ed55be-0a3b-11e7-8191-fb5dc79690a7.png)

![image](https://cloud.githubusercontent.com/assets/3684599/23991981/8758939a-0a3b-11e7-90c7-e787f7c3fe78.png)

What must i do to avoid these template warnings?

**Comment by derchirurg** [comment]
Angular2 Material is made for Angular2, not the new Angular 4 (RC). The template tag is deprecated and should not be used anymore, but it seems Angular2 Material is using it.
Change Angular version to 2 and it should work.

**Comment by stefanaerts** [comment]
Ok,So if i want to use angular4 ,what are my best options for material design?

**Comment by derchirurg** [comment]
I don't know. I didn't give Angular 4 a try.

**Comment by crisbeto** [comment]
You can keep an eye on https://github.com/angular/material2/pull/3608. When it gets merged, Material should work with Angular 4.
