### ISSUE TITLE
Your style in ReadMe not works

### ISSUE THREAD

**Issue by gtzinos** [angular/material2#3633]
Ref: https://github.com/angular/material2/tree/master/src/lib/sidenav#bound-properties

html, body, material-app, md-sidenav-container, .my-content {
  margin: 0;
  width: 100%;
  height: 100%;
}

This rule not works. Please change height from 100% to 100vh

**Comment by andrewseguin** [comment]
Using 100vh is not ideal due to iOS Safari's view calculations not including its browser chrome.

See https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html for some more information.
