### ISSUE TITLE
Menu is not responsive

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#3636]
The menu is not scrollable:
![screenshot_20170316-135439](https://cloud.githubusercontent.com/assets/4770180/23998468/8144223e-0a55-11e7-83a1-c54732f6b1bf.png)

Reference:
https://pages.corifeus.tk

The whole:
![screenshot_20170316-135451](https://cloud.githubusercontent.com/assets/4770180/23998470/82aab6ec-0a55-11e7-8420-6aae35c7994c.png)

**Comment by patrikx3** [comment]
For example in Bootstrap is scrollable:
![image](https://cloud.githubusercontent.com/assets/4770180/23998601/ddf14908-0a55-11e7-9769-90a463020a2e.png)

**Comment by jelbourn** [comment]
@kara thoughts on this?

**Comment by btroncone** [comment]
Any updates or work-arounds for this? Unfortunately this makes md-menu tough to use if there are more than a few options included. Thanks in advance!

**Comment by patrikx3** [comment]
it is still not working :(

**Comment by jelbourn** [comment]
Tracking this via #4270.

I'm [working on a solution](https://github.com/angular/material2/pull/4761)
