### ISSUE TITLE
md-tab-link sets ‘/’ link active only the first time

### ISSUE THREAD

**Issue by gscscnd** [angular/material2#3638]
#### Bug, feature request, or proposal:

Bug.

#### What is the expected behavior?

Let’s assume that there’s `md-tab-nav-bar` that contains at least two `md-tab-link`s. The first tab points to `/`, the other point to another routes. On the beginning, the first tab is focused (there’s a blue line under the tab’s caption) and the component that’s assigned to `/` route is displayed.

1. Click another tab — you’re redirected to another page and the new tab gets focused.
2. Click the first tab — you’re redirected to the first page and the first tab gets focused.

#### What is the current behavior?

1. Click another tab — you’re redirected to another page and the new tab gets focused.
2. Click the first tab — you’re redirected to the first page, _but_ the first tab doesn’t get focused. Instead, the previously clicked tab remains focused.

#### What are the steps to reproduce?

Plunker (based on [example from docs](https://material.angular.io/components/component/tabs)): [bcYw2A](https://plnkr.co/edit/bcYw2A?p=preview).

#### What is the use-case or motivation for changing an existing behavior?

I think it’s a bug, not desired behavior in case `md-tab-nav-bar` was used as a main navigation with a home (`/`) link.

#### Which versions of Angular, Material, OS, browsers are affected?

`@angular/core` 2.4.9, `@angular/material` 2.0.0-beta.2, `@angular/router` 3.4.9. Tested using Chromium 57 and Firefox 52 on Linux.

**Comment by willshowell** [comment]
Try using the option `[routerLinkActiveOptions]="{exact: true}"`.

See [this plunker](https://plnkr.co/edit/fUYBER?p=preview) and relevant [Angular docs](https://angular.io/docs/ts/latest/api/router/index/RouterLinkActive-directive.html).

**Comment by gscscnd** [comment]
Thank you, it worked for me.
