### ISSUE TITLE
Add CI check for compatibility mode selectors. 

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#3640]
Whenever we create a new component, the selector should be captured in `compatibility.ts`. 

We may be able to take advantage of the generated `metadata.json` to pull the selectors from components. 

cc @DevVersion since this is the kind of thing you tend to grab

**Comment by DevVersion** [comment]
Yeah, I will try to take a look how we can make such a check. Though I would wait for Angular 4 compatibility and the latest `@angular/tsc-wrapped` version.

**Comment by DevVersion** [comment]
Thinking about this more. I don't think every selector needs to be added to the compatibility module?

For example the `md-slide-toggle` selector would not interfere with any Material 1.x component.

**Comment by jelbourn** [comment]
@DevVersion the goal is more to ensure that people don't mix `md-` and `mat-` in one app.

**Comment by DevVersion** [comment]
@jelbourn So this means that basically every selector should be added to that list? 

The name indicated for me that it was for compatibility only. Also I was confused because the for example the `slide-toggle` was not added there.

**Comment by jelbourn** [comment]
Pretty much- don't worry about working on this right now, though. This is a really low priority idea.
