### ISSUE TITLE
Input placeholder animates when initialized with a value

### ISSUE THREAD

**Issue by andrewseguin** [angular/material2#3641]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

When an input is initialized with a value, the input's placeholder should not animate to be above the value.

#### What is the current behavior?

The animation always triggers. Looks funny when the input is loaded, especially on pages where there are many inputs.

To see an example of this, go to the Examples tab at http://localhost:4200/components/component/slider

**Comment by kara** [comment]
Looks related to https://github.com/angular/material2/issues/2620

**Comment by frankspin89** [comment]
Gif to illustrate the problem

![ncipnnqee3](https://cloud.githubusercontent.com/assets/4480104/24094545/7c545fda-0d59-11e7-9183-1fe36bd91107.gif)
