### ISSUE TITLE
feat(autocomplete): displayWith should accept a property name or function

### ISSUE THREAD

**Issue by jefersonestevo** [angular/material2#3642]
#### Bug, feature request, or proposal:
feature

#### What is the expected behavior?
The displayWith input from autocomplete should accept a property name (string) or a function (current behavior)

#### What is the current behavior?
The autocomplete only accepts a function as displayWith parameter

#### What is the use-case or motivation for changing an existing behavior?
Most of the times I just need to show a property from my model and I think it's kind of a overkill to implement a function just to get a single property

PS: It should accept a multilevel property (aka: displayWith="a.b.c")

**Comment by jelbourn** [comment]
We considered this feature while developing the autocomplete and we  decided against it because it is not compatible with minification tools that perform property renaming (e.g. Closure Compiler).
