### ISSUE TITLE
Compatibility with @angular/service-worker

### ISSUE THREAD

**Issue by joaogarin** [angular/material2#3652]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Use material together with @angular/service-worker package

#### What is the current behavior?
Including material breaks the service worker : https://github.com/angular/mobile-toolkit/issues/123

#### What are the steps to reproduce?
Include material design package together with @angular/service-worker

#### Which versions of Angular, Material, OS, browsers are affected?
Angular : 4.0.0-rc.3
Material : 2.0.0-beta.2
@angular/service-worker : 1.0.0-beta.6

Google Chrome 57.0.2987.98 on MAC OS Sierra 10.12.1.

#### Is there anything else we should know?
Currently material seems to break the service worker.

```
Uncaught (in promise) SyntaxError: Unexpected token   in JSON at position 1153
    at JSON.parse (<anonymous>)
    at c (worker-basic.min.js:1)
    at worker-basic.min.js:2
```

**Comment by joaogarin** [comment]
Sorry looks like the issue was not related to material.

**Comment by Ploppy3** [comment]
@joaogarin how did you fix it ?
