### ISSUE TITLE
Add conditional tooltip support (md-visible for md-tooltip)

### ISSUE THREAD

**Issue by pdavin** [angular/material2#3657]
#### Bug, feature request, or proposal:
Can we have conditional tooltip support like in AngularJs? By conditional tooltip I mean the tooltip only displays if a certain condition is true. The element the tooltip is on should always be displayed - so the element the tooltip is attached to is *not* conditional. This is behavior offered by md-visible with Angular 1's md-tooltip I believe: https://material.angularjs.org/latest/api/directive/mdTooltip

#### What is the expected behavior?
https://material.angularjs.org/latest/api/directive/mdTooltip

#### What is the current behavior?
https://material.angular.io/components/component/tooltip

#### What is the use-case or motivation for changing an existing behavior?
Allows writing conditional tooltips, without duplicating DOM structure (creating two copies of the potentially-tooltip'd text or element).

**Comment by andrewseguin** [comment]
Good news, this has been added recently and will be included in the next release

https://github.com/angular/material2/pull/3578

**Comment by pdavin** [comment]
Great! Sorry for the dupe - I did search open/closed issues before submitting and didn't find anything, but I think that's because I didn't expect it to be phrased as disabled.
