### ISSUE TITLE
md-input-container: mdPrefix and mdSuffix divs should not be present when there is no content

### ISSUE THREAD

**Issue by natsid** [angular/material2#3659]
#### Proposal:
I'd like to propose adding an `ngIf` on both the `.mat-input-prefix` and `.mat-input-suffix` divs in the `md-input-container` template so that they are only in the DOM if the user has included a prefix/suffix.

#### What is the use-case or motivation for changing an existing behavior?
I'd like to be able to add space between the infix and the affixes, but only when an affix is present.

#### What is the current behavior?
Currently, if I add any sort of spacing there, the space shows up even without the affix, as seen in the second input [here](https://plnkr.co/edit/ftKWagGNYlR263WTN0ZE?p=preview).

**Comment by jelbourn** [comment]
I agree that we should only render those elements if the directives are present.
