### ISSUE TITLE
Ink-bar not shown correctly for child routes

### ISSUE THREAD

**Issue by pauldaustin** [angular/material2#3662]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The ink-bar should be shown for the selected tab when there is a child route with the default '' path.

#### What is the current behavior?
Default tab with route '' does not show the ink-bar.

#### What are the steps to reproduce?

See [https://plnkr.co/edit/GNpwH9BD28pgSkLufh5S?p=preview](https://plnkr.co/edit/GNpwH9BD28pgSkLufh5S?p=preview)

1. Initially no ink-bar is shown.
2. Click Two and it has an ink-bar
3. Click One and it doesn't have am ink-bar

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.10
Material 2.0.0-beta-2

**Comment by Pikachews** [comment]
This may be related to #3133.

I replaced the component with the following, and it works properly (just changed it to use an NgFor)
```typescript
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'component-two',
  template: `

<nav md-tab-nav-bar>
  <a md-tab-link
     *ngFor="let link of links"
     [routerLink]="link.route"
     routerLinkActive
     [routerLinkActiveOptions]="{exact: true}"
     #rla="routerLinkActive"
     [active]="rla.isActive"
  >{{link.label}}</a>
</nav>
<router-outlet></router-outlet>
  `
})
export default class ComponentTwo {
  links = [
    {route: '.', label: 'One'},
    {route: 'child-two', label:'Two'}
    ]
}
```

**Comment by willshowell** [comment]
@pauldaustin @andrewseguin AFAICT there is no bug here. In the nav bar, the template reference `#rla` is being reassigned by each tab. You should use a unique name for each `routerLinkActive` reference or opt for using ngFor like @Pikachews demoed.

See https://github.com/angular/material2/issues/3133#issuecomment-317205285 and https://github.com/angular/material2/issues/5924#issuecomment-317204913

Fixed reproduction: https://plnkr.co/edit/4wxtPwL11c5aQ9dezsgy?p=preview

**Comment by jelbourn** [comment]
Closing based on note from @willshowell
