### ISSUE TITLE
Material Icons for md-tab label?

### ISSUE THREAD

**Issue by michaelb-01** [angular/material2#3673]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
You should be able to pass in a material icon (e.g. <i class="material-icons">camera</i>) as a label

#### What is the current behavior?
The input is passed a string so the html is not evaluated

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

**Comment by Chan4077** [comment]
See the [tab docs on `md-tab-label`](https://github.com/angular/material2/blob/master/src/lib/tabs/tabs.md#labels).

**Comment by michaelb-01** [comment]
Great, thank you very much!
