### ISSUE TITLE
Bug SASS source files are being stripped

### ISSUE THREAD

**Issue by 0xCHERRY** [angular/material2#3674]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
SASS source files should be included

#### What is the current behavior?
SASS source files are being stripped when building from Git repository source

#### What are the steps to reproduce?
```sh
$ npm run build
```

**Comment by DevVersion** [comment]
Thanks for the issue. This is a known issue and will be resolved in https://github.com/angular/material2/pull/3661
