### ISSUE TITLE
template issue with latest upgrade

### ISSUE THREAD

**Issue by mac4manu** [angular/material2#3678]
#### Bug, feature request, or proposal:
Hi,
I have upgraded to latest version 2.0.0-beta.2. 

Getting below issues while loading the page
The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): ng:///MdAutocompleteModule/MdAutocomplete.html@0:0

The <template> element is deprecated. Use <ng-template> instead ("<cdk-focus-trap>[WARNING ->]<template cdkPortalHost></template></cdk-focus-trap>"): ng:///MdDialogModule/MdDialogContainer.html@0:16

The <template> element is deprecated. Use <ng-template> instead ("span> </span><span class="mat-select-arrow"></span> <span class="mat-select-underline"></span></div>[WARNING ->]<template cdk-connected-overlay [origin]="origin" [open]="panelOpen" hasBackdrop (backdropClick)="clo"): ng:///MdSelectModule/MdSelect.html

The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template cdkPortalHost></template>"): ng:///MdSnackBarModule/MdSnackBarContainer.html

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by fxck** [comment]
https://github.com/angular/material2/issues?utf8=%E2%9C%93&q=The%20element%20is%20deprecated

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material2/pull/3608.
