### ISSUE TITLE
md-list elements order not as specified 

### ISSUE THREAD

**Issue by Adam-Michalski** [angular/material2#3679]
Why icon is moved to first position in generated dom?
Elements order in md-list is not as specified, avatar or icon seams to be set always to left side of md-list-item.
If I put element without md-line it is moved after element with md-line.
How to specify elements order in md-list?
How to separate multiline from one line and other combinations?

Bug, feature request, or proposal:
Problem

What is the expected behavior?
Specified dom elements order

What is the current behavior?
icon or avatar is always in the left of md-list-item

What are the steps to reproduce?
https://plnkr.co/edit/Hzjadf6u5byoHotLcCoo?p=preview

Which versions of Angular, Material, OS, browsers are affected?
"@angular/material": "2.0.0-beta.2",
@angular: "2.4.10",

**Comment by jelbourn** [comment]
This is working as intended to match the material design spec.
