### ISSUE TITLE
md-radio-group "No value accessor for x"

### ISSUE THREAD

**Issue by fxck** [angular/material2#368]
I'm trying to use `md-radio-group`, like this

```html
<form [ngFormModel]="form">
  <md-radio-group
    [ngModel]="data.foo"
    ngControl="foo">
    <md-radio-button *ngFor="#option of radioButtonOptions" [value]="option.value">
      {{ option.label }}
    </md-radio-button>
  </md-radio-group>
</form>

```

along with

```typescript
class WhateverCmp {
  public data = { foo: null };

  public radioButtonOptions = [
    {
      label: 'Bar',
      value: 'bar'
    },
    {
      label: 'Baz',
      value: 'baz'
    }
  ];

  constructor(private _fb: FormBuilder) {
    this.form = _fb.group({
      foo: [ '', Validators.required ]
    });
  }

}
```

and I'm getting `ORIGINAL EXCEPTION: No value accessor for 'foo'`

using alpha.3 and angular b.16

**Comment by robertmesserle** [comment]
@fxck this is working for me when tested against the latest code in master.  Closing for now - please let me know if this is not resolved and I will reopen.

**Comment by mashhoodr** [comment]
I am experience this issue as well.

Using:
@angular/core: "2.0.0-rc.1"
@angular2-material/core: "^2.0.0-alpha.4"
@angular2-material/radio: "^2.0.0-alpha.4"

http://plnkr.co/edit/sMHZESGaE4qjHCshmnzO?p=preview

**Comment by fxck** [comment]
@robertmesserle well it's not working on whatever is released on npm, http://plnkr.co/edit/uM0WoalscT5Cx4XFev5V?p=preview

**Comment by mmgyce** [comment]
You have to include MdRadioGroup in the directives
