### ISSUE TITLE
Installation error: node_modules/@angular2-material/package.json 404 (Not Found)

### ISSUE THREAD

**Issue by nareshbhatia** [angular/material2#369]
I have installed material2 as suggested in README.md. To start off, I simply added an MdButton to my app. When I run the application, I get this error:

    GET http://localhost:5555/node_modules/@angular2-material/package.json 404 (Not Found) (Initiated from angular2-polyfills.js).

As soon as I take out `MdButton`, the app works. What am I doing wrong?

Here's my component:

    import {Component} from 'angular2/core';
    import {CORE_DIRECTIVES, FORM_DIRECTIVES} from 'angular2/common';
    import {MdButton} from '@angular2-material/button';

    import {NameListService} from '../../shared/services/name-list.service';

    @Component({
      selector: 'sd-home',
      moduleId: module.id,
      templateUrl: './home.component.html',
      styleUrls: ['./home.component.css'],
      directives: [FORM_DIRECTIVES, CORE_DIRECTIVES, MdButton]
    })
    export class HomeComponent {
      newName: string;
      constructor(public nameListService: NameListService) {}

      /*
       * @param newname  any text as input.
       * @returns return false to prevent default form submit behavior to refresh the page.
       */
      addName(): boolean {
        this.nameListService.add(this.newName);
        this.newName = '';
        return false;
      }
    }

Here's my SystemJS configuration:

    "packages": {
      "angular2": {
        "defaultExtension": false
      },
      "rxjs": {
        "defaultExtension": false
      },
      "@angular2-material/core": {
        "format": "cjs",
        "defaultExtension": "js",
        "main": "core.js"
      },
      "@angular2-material/button": {
        "format": "cjs",
        "defaultExtension": "js",
        "main": "button.js"
      },
      "@angular2-material/checkbox": {
        "format": "cjs",
        "defaultExtension": "js",
        "main": "checkbox.js"
      }
    }

**Comment by jelbourn** [comment]
It sounds like you're not copying the files to the directory from which your app is serving files. The setup for this is going to depend on your particular build / serving setup.
