### ISSUE TITLE
Toolbar is not mobile responsive

### ISSUE THREAD

**Issue by WJChai** [angular/material2#3692]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
toolbar should fit nicely in mobile viewport

#### What is the current behavior?
flow out with empty space

#### What are the steps to reproduce?
http://plnkr.co/edit/g2rKycwKOiXZChU4YUmN?p=preview
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
mobile version should not have horizontal scrolling 

#### Which versions of Angular, Material, OS, browsers are affected?
version as in plunker, all OS and browsers

#### Is there anything else we should know?
that's it

**Comment by jelbourn** [comment]
@DevVersion not sure if there's actually an issue here, want to take a look (after ng-conf)?

**Comment by DevVersion** [comment]
Looks like an issue. I'm not sure what UX we prefer here. Should we just wrap the text or just prevent overflow @jelbourn?

**Comment by willshowell** [comment]
@DevVersion Given the [spec's discussion](https://material.io/guidelines/layout/structure.html#structure-app-bar) of "prominent" and "extended height" toolbars/appbars, it would seem that wrapping would be the appropriate behavior.

**Comment by DevVersion** [comment]
@willshowell Thanks for looking into it. I'm just a bit worried about the height of the toolbar's.

If we support wrapping, then I assume users will have toolbar's that are taller than the specification says.

**Comment by willshowell** [comment]
Agreed. Perhaps a similar approach to list items could work in combination with nowrap? It would still give users an outlet for adding additional content to the toolbar, while (I assume) adhering to the spec.

```scss
// height for single-line lists
$mat-list-base-height: 48px;

// spec requires two- and three-line lists be taller
$mat-list-two-line-height: 72px;
$mat-list-three-line-height: 88px;
```

**Comment by DevVersion** [comment]
Not sure I can quite follow. Isn't the snippet you posted kind of about multiple rows?

**Comment by willshowell** [comment]
Yes, it is.

With the proposed solutions, if I wanted to add several icon buttons and a long title, the toolbar would either
1. Prevent overflow and cut off my content
2. Wrap and no longer follow the spec [*see note below*]

However, if MdToolbar could support multiple rows, like in the following image, I would be able to fill the toolbar with far more actions/content that I can currently, and it would still follow the spec.
![screen shot 2017-03-24 at 3 11 53 pm](https://cloud.githubusercontent.com/assets/6475576/24310114/feaab634-10a4-11e7-97e1-38c51d95e183.png)

**Note**: I may be misinterpreting the spec, but it looks like the toolbar heights are *default* heights and can be extended to support more content.

**Comment by DevVersion** [comment]
@willshowell Yes. There are a  lot of things described in the toolbar specification. 

In Angular Material we tried to keep the component as simple as possible. The simplicity just allows developers to tweak the component as much as they want.

The toolbar already supports multiple rows, but I assume you are talking about `line-rows` inside of a row right?

**Comment by willshowell** [comment]
Oh whoops! I'd entirely forgotten that the toolbar already had support for rows... Should've read up before injecting my opinions 😏

**Comment by DevVersion** [comment]
@willshowell No problem. Really appreciate your feedback here :)

**Comment by DevVersion** [comment]
I think we should close that issue. There is already support for multiple rows inside of a `<mat-toolbar>`. 

By default the content won't wrap since we don't want to encourage people to have multiple lines inside of a **single** row. If you want multiple lines, you can overwrite the behavior through CSS for now.

It's planned to improve the text overflow by adding an ellipsis to the text-overflow. See https://github.com/angular/material2/issues/5740
