### ISSUE TITLE
Adding of one module is leading to all modules actually added to vendor.bundle.js (treeshaking issue)

### ISSUE THREAD

**Issue by bobrosoft** [angular/material2#3696]
#### Bug, feature request, or proposal:
bug (possibly)

#### What is the expected behavior?
Adding of one module should not import other modules (beside of MdCoreModule and maybe some related modules if any) so vendor.js should contain only code which is actually used (proper treeshaking).

#### What is the current behavior?
When one module added (for example MdToolbarModule) I see all modules added to vendor.js. Treeshaking enabled, AoT build, Webpack 2 is in use (https://github.com/AngularClass/angular2-webpack-starter boilerplate is used).

#### What are the steps to reproduce?
* get https://github.com/AngularClass/angular2-webpack-starter
* `npm install @angular/material --save`
* `import {MdToolbarModule} from '@angular/material';` in app.module.ts
* add something as `<md-toolbar>Test</md-toolbar>` into app.component.ts template
* `npm run build:aot:prod`
* check vendor.bundle.js (I use stats-webpack-plugin)

#### What is the use-case or motivation for changing an existing behavior?
Dramatically reduce final bundle size.

#### Which versions of Angular, Material, OS, browsers are affected?
```
    "@angular/common": "2.4.6",
    "@angular/compiler": "2.4.6",
    "@angular/core": "2.4.6",
    "@angular/flex-layout": "^2.0.0-beta.4",
    "@angular/forms": "2.4.6",
    "@angular/http": "2.4.6",
    "@angular/material": "^2.0.0-beta.2",
...
```

**Comment by fxck** [comment]
I actually think that even when you add all modules(`MaterialModule`), the final treeshaken code should only include the components you actually use. Or so I read somewhere (when they joined all the npm packages together). But it's gotta be said this in not happening, but I always thought it's something wrong with my build system.

**Comment by jelbourn** [comment]
In the future we are planning on breaking our components into separate entry points within one package in order to make things better for Webpack (which doesn't do comprehensive tree-shaking like other tools). Aside from that, there's not much that can be done due to the way that webpack is set up (it only looks at exports rather than intelligently figuring out which code is actually unused).

**Comment by bobrosoft** [comment]
@jelbourn thanks for explanation! So, does any other tool as rollup or angular-cli do proper treeshaking with current angular/material2? Or it anyway require that rework you mentioned?

**Comment by jelbourn** [comment]
Rollup or Closure Compiler might do better. We hope to have some improved guidance on this down the line

**Comment by jelbourn** [comment]
This issue is over a year and half old. The library today supports importing specific components like `@angular/material/button`, but if you use Angular CLI, it's build optimizer should just take care of things for you.
