### ISSUE TITLE
Textarea vertical alignment 

### ISSUE THREAD

**Issue by AAAnderson7301** [angular/material2#3697]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Textarea Inputs should align vertically with other Inputs

#### What is the current behavior?
The textarea is not vertically aligned with other Inputs. The underline is 

#### What are the steps to reproduce?

Add a textarea and a input field next to each other. See Plunker below

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

https://plnkr.co/edit/oLCpdNeXcfG0s8EzUbdn?p=preview 

#### Which versions of Angular, Material, OS, browsers are affected?
Material - @ Master, Windows 10 and OSX Sierra

**Comment by mmalerba** [comment]
part of the problem here is just that the `<td>`s need to be `vertical-align: baseline`. However even after adding that, the text in the textarea is misaligned, #3714 should fix it.
