### ISSUE TITLE
IE11 mdInput with initial value null becomes empty string after form submit

### ISSUE THREAD

**Issue by elvirdolic** [angular/material2#3698]
#### Bug, feature request, or proposal:
Bug IE11

Material or Angular itself?

#### What is the expected behavior?
MdInput fields with initial value null should be null after submit. 
#### What is the current behavior?
Initial null values are empty strings after submit in IE11

#### What are the steps to reproduce?
http://plnkr.co/edit/Pk6rOEr3THukg5NOdA4S?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
beta-2 angular version 2.x

#### Is there anything else we should know?
Chrome:
![image](https://cloud.githubusercontent.com/assets/17769458/24156794/dcf985be-0e57-11e7-8a99-872ef40f323b.png)

IE11
![image](https://cloud.githubusercontent.com/assets/17769458/24156753/c1e49e26-0e57-11e7-8462-9f02b0e52802.png)

**Comment by mmalerba** [comment]
Appears to be caused by https://github.com/angular/angular/issues/14440 as a workaround use `<md-placeholder>` rather than the `placeholder` attribute
