### ISSUE TITLE
dialog dark theme

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#3699]
#### Bug, feature request, or proposal:
i think the styles are missing out in dialogs, in white it works, but with dark it is not working right.

#### What is the expected behavior?
dark theme dialog color should be like white instead of black.

#### What is the current behavior?
dark theme dialog text is dark.

#### What are the steps to reproduce?
dark theme.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

https://pages.corifeus.tk/asdasd

Switch the theme and you can see in dark not working properly. SHouldnt it work with the theme?

#### Which versions of Angular, Material, OS, browsers are affected?
all current

**Comment by kara** [comment]
This was fixed in https://github.com/angular/material2/pull/2967, but it's not yet in a release. Should go out with the next one. You can read about how to use the new overlay theme classes here:

https://github.com/angular/material2/blob/master/guides/theming.md#theming-overlay-based-components
