### ISSUE TITLE
npm install doesn't work for @angular2/material/core

### ISSUE THREAD

**Issue by duboi381** [angular/material2#370]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Cannot find angular2-material/core

* **If the current behavior is a bug,
please provide steps to reproduce and if possible a minimal demo  of the problem**
- In the command line : npm i @angular2-material/core
- I'm getting this error :
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@angular2-material/core"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code E404

npm ERR! 404 no such package available : @angular2-material/core
npm ERR! 404
npm ERR! 404  '@angular2-material/core' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\adubois\Downloads\ng2_play-master\ng2_play-master\npm-debug.log

* **What is the expected behavior?**
I should not get any error

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Did this work in previous versions of Angular / Material?
"@angular2-material/core": "^2.0.0-alpha.2"

**Comment by jelbourn** [comment]
It's a dash, not a slash:
```
npm install @angular2-material/core
```
But the rest of your examples seem right. This is likely a problem with your environment and not the package itself. See #297
