### ISSUE TITLE
bug(autocomplete): Shift+Home and Shift+End not working on input

### ISSUE THREAD

**Issue by jefersonestevo** [angular/material2#3701]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Shift+Home and Shift+End are used to select the whole text from a html input, so it should work even with md-autocomplete

#### What is the current behavior?
When you press Shift+Home and Shift+End on an input with md-autocomplete nothing happens

#### What are the steps to reproduce?
[Plunker](http://plnkr.co/edit/vdjlDvkHoKtBnGgGkyEx?p=preview)
Try to select and use Shift+Home and Shift+End on both inputs

I don't know if it is a intended behavior, but as [angularjs autocomplete](https://material.angularjs.org/latest/demo/autocomplete) does allow to use Shift+End and Shift+Home, I think this should work on this component too

**Comment by JustServ** [comment]
Was this resolved? I'm having the same issue too but it's marked as closed..

**Comment by jefersonestevo** [comment]
I've closed this because there is already the issue #3496. I'm tracking it there
