### ISSUE TITLE
md-autocomplete input missing on form submit

### ISSUE THREAD

**Issue by rajvengala** [angular/material2#3702]
#### Bug, feature request, or proposal:
autocomplete input is missing from form submit data

#### What is the expected behavior?
autocomplete input's name and value should be part of form submit data

#### What is the current behavior?
autocomplete input's name and value are missing from form submit data. If I omit [formControl] binding, form submission has autocomplete input data. But, I will lose out on autocomplete filter functionality without that.

#### Snippet
```
                    <md-input-container>
                        <input mdInput
                               name="taskName"
                               type="text"
                               placeholder="Name"
                               [(ngModel)]="taskName"
                               [mdAutocomplete]="configureTaskAuto"
                               [formControl]="taskCtrl"
                               required>
                    </md-input-container>
                    <md-autocomplete #configureTaskAuto="mdAutocomplete">
                        <md-option *ngFor="let task of filteredTasks | async"
                                   [value]="task"
                                   (onSelect)="onTaskSelected(task)">
                            {{ task }}
                        </md-option>
                    </md-autocomplete>
 ```

**Comment by kara** [comment]
@rajvengala It looks like you have two competing form directives here - ngModel and formControl. They're not really meant to be used together because then you have two sources of truth for the value that will conflict.  You can definitely use ngModel alone to filter if you have a template-driven form. See the demo code here:

 https://github.com/angular/material2/blob/master/src/demo-app/autocomplete/autocomplete-demo.html#L29

**Comment by rajvengala** [comment]
Thank you. It helped. 

Much of the official documentation available for Angular2 talks about template driven forms, even the examples. I think, the examples for material components too should be primarily using template driven forms for the sake of consistency. 

Raj
