### ISSUE TITLE
Focus not displaying on https://material.angular.io/components/component/checkbox

### ISSUE THREAD

**Issue by vipdorian** [angular/material2#3715]
#### Bug, feature request, or proposal:
Focus not displaying on https://material.angular.io/components/component/checkbox
https://material.angular.io/components/component/checkbox

#### What is the expected behavior?
When pressing Tab, the focus should move.

#### What is the current behavior?
No focus.

**Comment by DevVersion** [comment]
This has been fixed in `master`. Docs will be updated with `beta.3`.
