### ISSUE TITLE
Including branch data-table-prototype in package.json

### ISSUE THREAD

**Issue by sidewaiise** [angular/material2#3718]
#### What is the expected behavior?

I would expect that we an specify for package `@angular/material` the source is `git+https://github.com/angular/material2.git#data-table-prototype`, and that the package will install in the default location @angular/material...
#### What is the current behavior?

Using this name `@angular/material` with this git source results in the package not being installed properly. I'd like to use this branch (`#data-table-prototype`) as the default for an angular 2 project but can't using this method of installation/package spec.

#### What are the steps to reproduce?

in package.json, add the following line to dependencies:
`"@angular/material": "git+https://github.com/angular/material2.git#data-table-prototype"`

The same issue applies if using `git@github....`

#### Is there anything else we should know?

I'm using this in conjunction with the latest clone of the angular seed repo maintained by @mgechev. https://github.com/mgechev/angular-seed

**Comment by fxck** [comment]
The main repo does not contain built files, only the sources files, this won't ever work.

**Comment by jelbourn** [comment]
The data table branch you're pointing to is just an experiment / prototype. When it's available for real it will be in the main package.
