### ISSUE TITLE
mdInput clear input button

### ISSUE THREAD

**Issue by j3ddesign** [angular/material2#3725]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
When an mdInput text field has a value, there should be a clear (X) button on the right of the input to clear the text field.

#### What is the current behavior?
No button, user has to manually clear, or dev has to create another directive

#### What is the use-case or motivation for changing an existing behavior?
I'm currently working on a search field, and expected the `<input type="search" mdinput></input>` to give users a clear button, as per the docs here https://material.io/guidelines/components/text-fields.html#text-fields-search-filter - however I'm either missing something, or it's not provided.

**Comment by jefersonestevo** [comment]
I don't know if it's a behaviour that the mdInput should have. At least for now, I think you can use the mdSuffix and set your own component on that specific field.

Example: [Plunker](http://plnkr.co/edit/Q4fzXAGHMRp6i4BY5o8V?p=preview)

**Comment by essenov** [comment]
If I have a form of 20 fields then I need 20 extra sufixes and event handler for each of them. That is a lot more routine code.

**Comment by mmalerba** [comment]
Yep, mdSuffix is the way to go. I do think it's worth adding this as an example in our docs since it seems like a common use case. Created #3730 to do so.

**Comment by j3ddesign** [comment]
suffix does feel like a temporary solution, though fits what I need for now. 
I think, after looking at the material guidelines that it's only `search` and `autocomplete` fields that should have the clear button. It'd be nice if material did handle this without me specifying a suffix for these situations. 
Thanks for the suffix suggestion, though! I'll go remove my pos absolute css now ;)

**Comment by olingerc** [comment]
FYI: If you use this solution in a form together with a mat-icon-button to trigger the clear, you need to set type="button" on the button element, otherwise if the user hits enter in the input, it actually triggers the click handler of the button.
[indirectly related SO post](https://stackoverflow.com/questions/12325066/button-click-event-fires-when-pressing-enter-key-in-different-input-no-forms)
