### ISSUE TITLE
Using `md-opt-group` in select throw an error

### ISSUE THREAD

**Issue by ahmadalfy** [angular/material2#3728]
Edit: I misspelled it in the title it is `md-optgroup`

#### Bug report
According to [this document](https://docs.google.com/document/d/1WEyPmTjeFEtkvYELqmsnW8GI1ul9R0P_FDNDnjr1F0s/preview) I can use this:

```html
<md-select ng-model="selectedToppings" multiple>
   <md-optgroup label="Meats"> 
      <md-option value="Pepporoni"> Pepperoni </md-option>
   </md-optgroup>
   <md-optgroup label="Veggies"> 
      <md-option value="Mushroom"> Mushroom </md-option>
   </md-optgroup>
</md-select>
```

#### Expected behavior
Render a select drop down with `opt-group`

#### What is the current behavior?

Get the following error in the console

```
1. If 'md-optgroup' is an Angular component, then verify that it is part of this module.
2. If 'md-optgroup' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
            <md-option value="Pepporoni"> Pepperoni </md-option>
        </md-optgroup>
        [ERROR ->]<md-optgroup label="Veggies">
            <md-option value="Mushroom"> Mushroom </md-option>
        "): AppDashboardComponent@29:8 ; Zone: <root> ; Task: Promise.then ; Value:
```

**Comment by ocarreterom** [comment]
Option group is not implemented.

**Comment by jelbourn** [comment]
This is something we plan on adding to the select but it is not yet implemented.

**Comment by ahmadalfy** [comment]
Thank you for the clarification. I must've confused the material docs with Angular Material 2

**Comment by finalxcode** [comment]
Option group is not implemented +1
