### ISSUE TITLE
Possible bug with md-raised-button on the ripple effect.

### ISSUE THREAD

**Issue by skyfremen** [angular/material2#3731]
#### Bug, feature request, or proposal:
Possible Bug with md-raised-button as stated by - https://github.com/telerik/kendo-angular/issues/411

#### What is the expected behavior?
NA

#### What is the current behavior?
Browser glitch, which occurs when clicking on the md-raised-button component. It seems that the problem is related to the introduced styles for the ripple effect.

#### What are the steps to reproduce?
Repo steps:

Make sure the browser is maximise.
Click on save button > Success message will show.
Adjust the browser width with smaller.
The grid header background will be misaligned

Plunker template: http://plnkr.co/edit/IdqbyjYapkrHskotAsoV?p=preview

#### What is the use-case or motivation for changing an existing behavior?
NA

#### Which versions of Angular, Material, OS, browsers are affected?
Material: 2.0.0-beta.2
OS: Windows
Browsers: Chrome

#### Is there anything else we should know?
The following style appears to fix the problem:

```
.mat-fab, .mat-mini-fab, .mat-raised-button {
  overflow: hidden;
}
```

**Comment by jelbourn** [comment]
@skyfremen is this still an issue with beta.3?

**Comment by jelbourn** [comment]
Closing since I think this is obsolete. Feel free to open a new issue if there is still a problem
