### ISSUE TITLE
@ symbol in name breaks NPM integration with Visual Studio 2015, ASP.NET 5, MVC 6 (@angular2-material)

### ISSUE THREAD

**Issue by IAMtheIAM** [angular/material2#374]
When using visual studio 2015 Update 2, inside an ASP.NET 5 MVC 6 project, installing packages fails completely when adding a package.json file which contains dependencies such as the ones contained in [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter)

For example:
 "dependencies": {
    "@angular2-material/button": "2.0.0-alpha.3",
    "@angular2-material/card": "2.0.0-alpha.3",
    "@angular2-material/checkbox": "2.0.0-alpha.3",
    "@angular2-material/core": "2.0.0-alpha.3",
    "@angular2-material/input": "2.0.0-alpha.3",
    "@angular2-material/list": "2.0.0-alpha.3",
    "@angular2-material/progress-bar": "2.0.0-alpha.3",
    "@angular2-material/progress-circle": "2.0.0-alpha.3",
    "@angular2-material/radio": "2.0.0-alpha.3",
    "@angular2-material/sidenav": "2.0.0-alpha.3",
    "@angular2-material/toolbar": "2.0.0-alpha.3",
    "core-js": "^2.2.2",
    "normalize.css": "^4.1.1",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "~0.6.12"
  },

The @ symbol in @angular2-material is the problem. Please remove the @ symbol from the NPM registry package name. Removing the @ symbol fixes the issue and allows packages to install normally in visual studio using ASP.NET 5 MVC 6

**Comment by IAMtheIAM** [comment]
Wrong thread

**Comment by jelbourn** [comment]
This would be a bug in Visual Studio. The `@` symbol indicates an npm scoped package: https://docs.npmjs.com/misc/scope
