### ISSUE TITLE
BUG angular material 2

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#3753]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
works

#### What is the current behavior?
error

#### What are the steps to reproduce?
aot with webpack

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

here:
```@angular/material/checkbox/checkbox.html```

```bash
ERROR in Template parse errors:
Only void and foreign elements can be self closed "path" ("lass=mat-checkbox-checkmark xmlns=http://www.w3.org/2000/svg viewBox="0 0 24 24" xml:space=preserve>[ERROR ->]<path class=mat-checkbox-checkmark-path fill=none stroke=white d="M4.1,12.7 9,17.6 20.3,6.3"/></svg><"): MdCheckbox@0:809
Unexpected closing tag "svg" ("serve><path class=mat-checkbox-checkmark-path fill=none stroke=white d="M4.1,12.7 9,17.6 20.3,6.3"/>[ERROR ->]</svg><div class=mat-checkbox-mixedmark></div></div></div><span class=mat-checkbox-label><ng-content>"): MdCheckbox@0:903
```

#### What is the use-case or motivation for changing an existing behavior?
works with aot

#### Which versions of Angular, Material, OS, browsers are affected?
windows, debian. linux mint, chrome, firefox, node 7.7, all latest

#### Is there anything else we should know?

```@angular/material/checkbox/checkbox.html```

```html
<label class="mat-checkbox-layout"><div class="mat-checkbox-inner-container"><input #input class="mat-checkbox-input cdk-visually-hidden" type="checkbox" [id]="inputId" [required]="required" [checked]="checked" [disabled]="disabled" [name]="name" [tabIndex]="tabIndex" [indeterminate]="indeterminate" [attr.aria-label]="ariaLabel" [attr.aria-labelledby]="ariaLabelledby" (focus)="_onInputFocus()" (blur)="_onInputBlur()" (change)="_onInteractionEvent($event)" (click)="_onInputClick($event)"><div md-ripple *ngIf="!_isRippleDisabled()" class="mat-checkbox-ripple" [mdRippleTrigger]="_getHostElement()" [mdRippleCentered]="true" [mdRippleSpeedFactor]="0.3"></div><div class="mat-checkbox-frame"></div><div class="mat-checkbox-background"><svg version="1.1" class="mat-checkbox-checkmark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" xml:space="preserve"><path class="mat-checkbox-checkmark-path" fill="none" stroke="white" d="M4.1,12.7 9,17.6 20.3,6.3"/></svg><div class="mat-checkbox-mixedmark"></div></div></div><span class="mat-checkbox-label"><ng-content></ng-content></span></label>
```

**Comment by milenkovic** [comment]
I am getting same error.

**Comment by mscu** [comment]
probably because of the svg and you didn't use the svg namespace

> An SVG snippet template needs an svg: prefix on its root element to disambiguate the SVG element from an HTML component.

**Comment by jelbourn** [comment]
Everything seems to working in the latest version. 

If you're still running into a problem, feel free to open a new issue with a full reproduction.
