### ISSUE TITLE
Template is deprecated

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#3755]
#### Bug, feature request, or proposal:
After update to angular 4.0 console shows this warning:

Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): ng:///MdAutocompleteModule/MdAutocomplete.html@0:0

#### Which versions of Angular, Material, OS, browsers are affected?
NG 4.0
MAT 2.0.0-beta.2

**Comment by lucasvanhalst** [comment]
Already fixed in #3608

**Comment by mbeckenbach** [comment]
ok thanks. please close
