### ISSUE TITLE
Plunker template doesn't work

### ISSUE THREAD

**Issue by molcik** [angular/material2#3757]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Working plunker template.

#### What is the current behavior?
![screen shot 2017-03-24 at 13 47 50](https://cloud.githubusercontent.com/assets/11929953/24294933/dd2754ba-1098-11e7-962c-ba3b1e59dda2.png)

"Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U" 

Plunker does not load @angular/animations.ts.

#### What are the steps to reproduce?
https://goo.gl/DlHd6U

**Comment by DevVersion** [comment]
Thanks. Fixed it!
