### ISSUE TITLE
build: Cannot find module '@angular/animations'

### ISSUE THREAD

**Issue by ericgundrum** [angular/material2#3760]
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

`npm install --save https://github.com/angular/material2-builds.git` in a new project should build.

#### What is the current behavior?

`npm install --save https://github.com/angular/material2-builds.git` in a new project fails to build reporting error `Cannot find module '@angular/animations'`.

#### What are the steps to reproduce?

```
ng new tst
cd tst
npm install
npm install --save https://github.com/angular/material2-builds.git
```
Then add `MaterialModule` to `app.module.ts` (as in [Getting started](https://material.angular.io/guide/getting-started)) and `ng build`.

#### Which versions of Angular, Material, OS, browsers are affected?

`node v7.7.4`
`@angular/cli v1.0.0`
`https://github.com/angular/material2-builds.git#6f8753ca3464d1167b6f582ae2ac17ec563ab8f4`

#### Is there anything else we should know?

There is no reference to `@angular/animations` in `https://github.com/angular/material2-builds/blob/master/package.json`

**Comment by Nikki1993** [comment]
You need to install manually `@angular/animations` it's now a separate package.  Read the full announcement here http://angularjs.blogspot.com/2017/03/angular-400-now-available.html

**Comment by ericgundrum** [comment]
@Nikki1993, that's helpful. I see that running `npm install '@angular/animations'` fixes the build problem.

Possibly the Material project should address this in a less obscure way. Maybe animations should be listed as a peer dependency. Or maybe [Getting started](https://material.angular.io/guide/getting-started) should be updated to indicate the step to install it. Or maybe both are needed.

**Comment by Nikki1993** [comment]
@ericgundrum change happened literally today with the upgrade to Angular v4. Prior versions are unaffected by it thus they couldn't list it as peer dependency. They still need to merge the commit that makes material angular 4 compatible & update the docs. Be patient.

**Comment by jelbourn** [comment]
This is expected as master has moved to Angular 4. When we have our next release there will be instructions for the new setup. 

Also, be careful using the snapshots on material2-builds; they can break at any time (like right now as we're in the middle of changing our package structure).
