### ISSUE TITLE
bug(input): always show firefox placeholder

### ISSUE THREAD

**Issue by jefersonestevo** [angular/material2#3767]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
The placeholder should be consistent independent of the browser

#### What is the current behavior?
When you have an input number, on firefox, after you select the input and then select it again, it shows the default browser placeholder

#### What are the steps to reproduce?
[Plunker](http://plnkr.co/edit/8ibpbcAeL3ksPxr2zytZ?p=preview)
Open with firefox, then click on "My Input Number", then in "My Input Text" and then in "My Input Number" again

![image](https://cloud.githubusercontent.com/assets/3085585/24311525/4daf18c0-10b3-11e7-9d8e-d058c5d8a61f.png)

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material: 2.0.0.-beta.2
Firefox 52.0

**Comment by donroyco** [comment]
Your Plunker doesn't have the colored styling. I can't reproduce your experienced behaviour in either Firefox 50.1.0 or 52.0.1 (64bit) on Mac.

**Comment by jefersonestevo** [comment]
I've tested it on 52.0 on linux. Now on 52.0.1 on windows the error didn't happened. I'll try to investigate it a little further.

About the colors my plunker was using an older path for the theme. Now it's correct.

**Comment by jefersonestevo** [comment]
Tested again on Firefox 52.0.1 (64-bit) - Ubuntu and the problem are there

**Comment by crisbeto** [comment]
I wasn't able to reproduce it on Ubuntu 16.04 and Firefox 51.0 @jefersonestevo.

**Comment by donroyco** [comment]
I _can_ reproduce the issue in Firefox 49.0 (on Mac). Updated Firefox to 50.1.0 and I can't reproduce the issue anymore. Updated again to 52.0.2 (64-bit) and no weird behaviour.

**Comment by mahdikianirad** [comment]
Same here, I have the problem on firefox.
