### ISSUE TITLE
material2 not compatible with beta.17+

### ISSUE THREAD

**Issue by t0rrro** [angular/material2#377]
At least md-button and checkboxes fail to display their content after the update to beta 17. No errors in console thrown.

Just downgraded to beta16 and everything's working as expected.

**Comment by jelbourn** [comment]
There were some breaking changes in beta.17. The fixes will be in our `alpha.4`

**Comment by t0rrro** [comment]
+1, thanks.

**Comment by jelbourn** [comment]
Fixed on master via #378
