### ISSUE TITLE
autocomplete.html contains <template> causes warning in Angular 4 build

### ISSUE THREAD

**Issue by p-jan** [angular/material2#3772]
#### Bug, feature request, or proposal:
Change request

#### What is the expected behavior?
Angular 4 compliant code without warnings

#### What is the current behavior?
The following warning is logged on ng build --prod

`The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): ng:///D:/personal/dev/projects/kidora/code/client/main-app/node_modules/@angular/material/autocomplete/autocomplete.html@0:0`

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4
Material 2.0.0-beta.2

**Comment by DevVersion** [comment]
This has been fixed with SHA https://github.com/angular/material2/commit/cd55082a488e58a3f4948bba8e5d0a6771a57233. The warning will disappear with the next Material release.
