### ISSUE TITLE
Material Sample Apps broken

### ISSUE THREAD

**Issue by rjt10** [angular/material2#3777]
#### Bug, feature request, or proposal:
Both of them broken and don't load
https://material.angular.io/guide/material2-app
https://material.angular.io/guide/leashed-in

#### What is the expected behavior?
Well, I expect it shows something.

#### What is the current behavior?
Doesn't load and Chrome Dev Tool indicates error.

#### What are the steps to reproduce?
Just visit these two links:
https://material.angular.io/guide/material2-app
https://material.angular.io/guide/leashed-in

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by surfjedi** [comment]
I have observed this too - but if you refresh the page after you click link it comes up.
Still not the best..

**Comment by rjt10** [comment]
what do you mean by 'refresh the page after you click link'? After refresh, the browser displays the content for this URL: https://material.angular.io, not the intended link.

Or am I missing something here?

**Comment by Chan4077** [comment]
See angular/material.angular.io#105

**Comment by DevVersion** [comment]
Yeah. It has been fixed and will be published with the next Material release.
