### ISSUE TITLE
Plunker template doesn't work

### ISSUE THREAD

**Issue by molcik** [angular/material2#3779]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Working plunker template.

#### What is the current behavior?

Plunker doesn't load prebuilded themes.

<img width="745" alt="screen shot 2017-03-25 at 11 02 37" src="https://cloud.githubusercontent.com/assets/11929953/24321363/9c0273a4-114a-11e7-929c-f4c5d8428335.png">

#### What are the steps to reproduce?
https://goo.gl/DlHd6U

**Comment by DevVersion** [comment]
Thanks again! We just made a change yesterday to the themes and we didn't update the path.
