### ISSUE TITLE
Angular 4 support in the npm package

### ISSUE THREAD

**Issue by DavidParks8** [angular/material2#3786]
#### Bug, feature request, or proposal:
Please add angular  >2.3 support to the official npm package.

#### What is the expected behavior?
Angular>2.3 should ideally be supported by the package.

#### What is the current behavior?
`npm warn @angular/material@2.0.0-beta.2 requires a peer of @angular/core@^2.3.0 but none was installed`
This prevents npm shrinkwrap.

#### What are the steps to reproduce?
npm install `@angular/core@latest` and then try to install `@angular/material`

#### What is the use-case or motivation for changing an existing behavior?
I would like to use your library in angular 4 without breaking backwards compatibility for others or using github as a package url.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.x
Material 2.0.0-beta.2

**Comment by dahaupt** [comment]
@DavidParks8 The current master already has support for angular 4, the npm package will be released as soon as possible as @jelbourn already said in a different issue.

**Comment by crisbeto** [comment]
Angular 4 support will be in the next release.
