### ISSUE TITLE
Scss include all-theme broken

### ISSUE THREAD

**Issue by axtho** [angular/material2#3787]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`@import '~@angular/material/core/theming/all-theme';` should load the core theme.

#### What is the current behavior?
ng serve produces `File to import not found or unreadable: ~@angular/material/core/theming/all-theme.`

#### What are the steps to reproduce?
+ following the theming doc, theme.scss in root, import the all-theme.
+ compile with angular-cli/@latest

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/cli: 1.0.0
node: 7.7.1
os: darwin x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
@angular/platform-server: 4.0.0

#### Is there anything else we should know?
Using the master snapshot, of course
I read jelbourn's comment on the original commit that it is a breaking change but that the theming guide would only be updated with the next release. Maybe you can comment on the PR how to get this done until then?

**Comment by Chan4077** [comment]
The theming has moved to `~@angular/material/_theming`

**Comment by DevVersion** [comment]
We are going to update the docs in the upcoming release for that.

**Comment by axtho** [comment]
@Chan4077 @DevVersion doing this breaks the entire custom theme, as described by the doc. Using this setup ... 

In my root folder I have` themes.scss` that does what the styling guide said should be there:

```
@import '~@angular/material/theming';
@import './palette';

@include mat-core();
$mh-app-primary: mat-palette($md-mh-blue);
$mh-app-accent:  mat-palette($mat-orange, A200, A100, A400);
$mh-app-warn:    mat-palette($mat-red);
$mh-app-green:  mat-palette($mat-green);

$mh-app-theme: mat-light-theme($mh-app-primary, $mh-app-accent, $mh-app-warn);
@include angular-material-theme($mh-app-theme);
```
produces a number of compile errors, of the like:
```
ERROR in ./src/app/dashboard/dashlets/interactions/dashlet-interactions.component.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Applications/MAMP/htdocs/memberhive2/web/node_modules/node-sass/vendor'
```
The offending scss file look like this (the path is correct):
```
@import "../../../../theme.scss";
.birthday-notice {
  font-weight: 200;
  background: mat-color($mh-app-warn, A200);
  color: #fff;
  padding: 8px !important;
}
```

I have also looked at the PRs and their commits, also the demo-app does not give info on that. I know it will be included in the next release ... but I would like to work on my app until then (without having to revert to beta.2).

Possible?

**Comment by axtho** [comment]
Never mind ... seems to be an issue with the way yarn installed stuff.
