### ISSUE TITLE
scss files don't compile for demo app

### ISSUE THREAD

**Issue by amitailanciano** [angular/material2#379]
I followed the DEV_ENVIRONMENT readme exactly, but none of the scss files seem to compile.. am I missing something?

![screen shot 2016-04-29 at 8 50 02 pm](https://cloud.githubusercontent.com/assets/1289466/14933683/ffe132be-0e4b-11e6-86a0-bbae80426ed1.png)

**Comment by kara** [comment]
Have you tried blowing away your node modules, `npm cache clean`, then `npm install` again?  Also check that your angular-cli is reasonably up to date.

**Comment by jelbourn** [comment]
This sounds like an issue with your environment. @kara's instructions will likely resolve it for you.
