### ISSUE TITLE
md-select not binding to number

### ISSUE THREAD

**Issue by ajayak** [angular/material2#3790]
#### Bug:
md-select binds to string values but not binding to number. 
```
if (item.unitId) {
      // PATCH: Find permanet solution. Number not binding in md-select
      item.unitId = '' + item.unitId;
}
```
```
<md-select flex
          placeholder="Unit"
          formControlName="unitId">
<md-option *ngFor="let unit of units"
            [value]="unit.id">
  {{unit.name}} ({{unit.code}})
</md-option>
</md-select>
```

#### What is the expected behavior?
md-select should bind to number

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-beta.2

**Comment by crisbeto** [comment]
It seems to work fine for me. Can you post a live example of the issue? [You can use this as a template.](https://goo.gl/DlHd6U)

**Comment by ajayak** [comment]
It is working fine. My bad. Datatype mismatch. Thanks for the support
