### ISSUE TITLE
CustomRequestOptions rewrite by material

### ISSUE THREAD

**Issue by Groxot** [angular/material2#3797]
I using base API url for app.  
```
providers: [ ... , 
    {  provide: RequestOptions, useClass: CustomRequestOptions }, 
  ]
```
CustomRequestOptions.ts :
```
import {BaseRequestOptions, RequestOptions, RequestOptionsArgs} from '@angular/http';

export class CustomRequestOptions extends BaseRequestOptions {
  
  merge(options?:RequestOptionsArgs):RequestOptions {
    options.url = 'http://serverAPI:4300/api'+ options.url;
    return super.merge(options);
  }
}

```

I installing angular material in one of the component. 

```
import { MaterialModule } from '@angular/material';
...

@NgModule({
  imports: [
  ....
   MaterialModule
  ],
```

and use it on button  `<button md-raised-button (click)="refreshUsers()"> refresh </button>`

button style changed
but API call make to http://localhost:4200 (where angular cli serve my app).
if i comments import MaterialModule in module, API call make successful  (http://serverAPI:4300/api).

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
