### ISSUE TITLE
release date [!important]

### ISSUE THREAD

**Issue by djleonskennedy** [angular/material2#3800]
Hello

Please provide an approximate release date for new version of BETA, very need several fixes that were merged

Thank you

**Comment by fxck** [comment]
Use https://github.com/angular/material2-builds if you want snapshot of master.

**Comment by djleonskennedy** [comment]
@fxck Could you clarify how to use it ?

**Comment by fxck** [comment]
https://www.google.cz/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=npm+install+from+github&*

**Comment by djleonskennedy** [comment]
@fxck understood, thank you

**Comment by sasxa** [comment]
@fxck I was getting this error with `material2-builds.git#b74e662528934950652d64fc41ca7ec2a852cf2b`:
```
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./~/sass-loader!./src/styles/theme.scss
Module build failed:
@import '~@angular/material/core/theming/all-theme';
^
      File to import not found or unreadable: ~@angular/material/core/theming/all-theme.
```
Looks like something changed with how custom themes work. Just to confirm, now we need to import:

    @import '~@angular/material/theming';

instead of 

    @import '~@angular/material/core/theming/all-theme'

Correct?

**Comment by leo6104** [comment]
@sasxa Yes. I did custom theme by that way and there is no problem.

**Comment by fxck** [comment]
That's because the paths were recently changed (couple of issues were already opened about it, search them), that's the price you have to pay for using cutting edge releases, you have to fish commits for breaking changes.

**Comment by sasxa** [comment]
@fxck @laco0416 OK, thanks. It's a really small change and not a big issue, just wanted to confirm. :-)

**Comment by mmrath** [comment]
I am eager to use the snapshot builds but my build server is behind firewall with access only to internal npm registry which can download from npm registry. So the build server can't use snapshots from github. It would be great if a periodic snapshots can be published to npm may be with experimental tag.

**Comment by kamarouski** [comment]
Still curious what is the roadmap for next releases? Are we going to see new beta version any time soon? 

This is just to feed my curiosity :)

**Comment by djleonskennedy** [comment]
@kamarouski you're happy if  just "curiosity", i looking forward new release as the second coming of Christ

**Comment by djleonskennedy** [comment]
@mmrath totally agree

**Comment by kamarouski** [comment]
@djleonskennedy haha. If you want to get latest fixes there is an option to get latest master version. This makes life a bit easier. 

I'm waiting for a few extra components like data table and calendar, though when I started using beta version of Angular Material I accepted the fact that there is no fixed schedule, there can be breaking changes and some parts are missing.

**Comment by Cleudi** [comment]
Not everybody has the option to use snapshots... therefore kind of a release schedule would really be helpful. 

We also use material.... we decided to use it 9 months ago, assuming that there will be at least something like a stable version until our product is entering productive mode... assumption was wrong, and we can not risk breaking features because of a snapshot update...

**Comment by fxck** [comment]
read https://github.com/angular/material2/issues/3799#issuecomment-289535678

**Comment by mmrath** [comment]
@fxck does not really help. I know it is in beta and it will be unstable. but why not release few frequent unstable betas or even experimental or nightly build

**Comment by jelbourn** [comment]
We're trying to release a new beta soon but are still working on smoothing out a particular issue with Webpack + tree-shaking for the components.
