### ISSUE TITLE
Input component coloring not consistent with material design spec

### ISSUE THREAD

**Issue by mhengelein** [angular/material2#3802]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
color of input element on focus is ACCENT color

#### What is the current behavior?
color of input element on focus is PRIMARY color

#### What are the steps to reproduce?
Put focus to input field on demo page
https://material.angular.io/components/component/input

#### What is the use-case or motivation for changing an existing behavior?
Match existing Material Design Spec (https://material.io/guidelines/style/color.html#color-color-schemes)

#### Which versions of Angular, Material, OS, browsers are affected?
current Material build - 2.0.0-beta.2 (and angular material demo page)

**Comment by jelbourn** [comment]
The [text field spec shows primary color in all the examples](https://material.io/guidelines/components/text-fields.html). You can change the color in your app by using the `color` property on the input container.
