### ISSUE TITLE
mat-tab-group doesn't work with NoConflictStyleCompatibilityMode

### ISSUE THREAD

**Issue by merobal** [angular/material2#3804]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Use `mat-tab-group` without any problem (with `NoConflictStyleCompatibilityMode`) inside angularjs-angular hybrid apps.

#### What is the current behavior?
It now throws in the console:
>The "md-" prefix cannot be used in ng-material v1 compatibility mode.

#### What are the steps to reproduce?
I created a github repo for demoing the issue: https://github.com/merobal/mat-tabs-demo

#### What is the use-case or motivation for changing an existing behavior?
We would like to use tabs inside hybrid apps which also uses material1.

#### Which versions of Angular, Material, OS, browsers are affected?
_Angularjs 1.5 and Material Design 1 (not included in the demo)_
Angular 4.0.0
Material 2.0.0-beta.2
Windows 10
Chrome 57

#### Is there anything else we should know?
I found that tabs use md- prefixed components inside, e.g. https://github.com/angular/material2/blob/master/src/lib/tabs/tab-group.html#L1

**Comment by crisbeto** [comment]
This appears to be fixed in master. You can try it put by running `npm install https://github.com/angular/material2-builds.git` or waiting for the next release.
