### ISSUE TITLE
Some links in guides are transformed to point to non-existent resources.

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#3806]
The bottom of [the getting started guide](https://material.angular.io/guide/getting-started) points to material2-app and the demo from our last Angular Connect talk, but they're transformed into material.angular.io links which don't exist.

**Comment by DevVersion** [comment]
Should have fixed with https://github.com/angular/material2/commit/cb57660981bee42fda8abc730e7f763ae357c598 already?

**Comment by jelbourn** [comment]
Ah, cool.
