### ISSUE TITLE
Demo-app no item text on sidenav

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#381]
<img width="316" alt="capture d ecran 2016-04-30 a 21 00 16" src="https://cloud.githubusercontent.com/assets/7827225/14937970/960d0d1a-0f16-11e6-88fd-d04f22382213.png">

**Comment by danielzen** [comment]
Noticing this as well. It appears that md-list-text is always an empty string

**Comment by jelbourn** [comment]
This is a bug in Angular that was resolved on master but hasn't been inlcuded in a release yet:
https://github.com/angular/angular/commit/0f774df81150524c399161272a6cd51d0d54aa7e

Will resolved when the next release occurs.
