### ISSUE TITLE
Cannot get Angular Material 2 to work with Angular 4

### ISSUE THREAD

**Issue by GregFinzer** [angular/material2#3815]
http://stackoverflow.com/questions/43073112/install-angular-material-2-with-angular-4-unmet-dependency

**Comment by Nikki1993** [comment]
This GitHub repo page us not for StackOverflow issues or otherwise links to it here to increase visibility.

**Comment by crisbeto** [comment]
The PR for Angular 4 compatibility landed a few days ago and will be in the next release.

**Comment by GregFinzer** [comment]
Thanks for your help.  Any ETA on the release?

**Comment by crisbeto** [comment]
It should be within the next few days. If you don't want to wait, you can use the latest build from master:

```bash
npm install --save https://github.com/angular/material2-builds.git
```

**Comment by mtpultz** [comment]
@crisbeto I had a look for the PR, but couldn't find it.  Can you link it here so we can subscribe/watch it.

Thanks for the update :)

**Comment by crisbeto** [comment]
Here you go, although it is merged already: https://github.com/angular/material2/pull/3608

**Comment by profimedica** [comment]
Check my repository:
https://github.com/profimedica/AngularMaterialFirebase
