### ISSUE TITLE
Dialogs are incorrect according to Material Design guidelines

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#3816]
#### Bug:

How it should be:
![image](https://cloud.githubusercontent.com/assets/7990765/24413095/b34adc80-13da-11e7-9bc2-597ab695b86e.png)

How it is:
![image](https://cloud.githubusercontent.com/assets/7990765/24413111/c117d9e4-13da-11e7-9b4e-6b6c3598a031.png)

A working example I coded (20 lines of css - no content scroll support):
![image](https://cloud.githubusercontent.com/assets/7990765/24413148/db538f42-13da-11e7-8e13-b67cd9b7c2db.png)
Source:
https://codepen.io/anon/pen/JWmXeQ

**NB**: Please note how everything in my demo is modular. The Title is optional, the Action div is optional. Adding more buttons or having only one does not break the CSS.

---

Here is a quick list of the errors for the dialog components:

- Color for Title, should be rgba(0,0,0,87)
- Color for Content, should be rgba(0,0,0,54)
- Wrong padding for buttons, padding should be 8px around & in-between every buttons

---

Many of your components do not respect the material guidelines. If they are not fixed before official release you'll probably run into breaking changes.
https://material.io/guidelines/components/dialogs.html

**Comment by crisbeto** [comment]
Yes, this is a known issue. I've been putting off fixing it since the scrolling behavior in general needs to be reworked first. I'll close this as a dupe, but you can keep an eye on https://github.com/angular/material2/issues/3239 and https://github.com/angular/material2/issues/2735.

**Comment by Ploppy3** [comment]
@crisbeto I hope the new version of the dialog will be as modular as possible. Unlike the current Toolbar  as example. I don't think we are supposed to tweak the CSS when we just want basic Material Design. Also I hope you've read my warning at the end of this issue.
