### ISSUE TITLE
Angular 4.0 Incompatibility

### ISSUE THREAD

**Issue by Alonsooo** [angular/material2#3817]
#### Bug, feature request, or proposal:
Angular Material is not compatible with Angular 4.0

#### What is the expected behavior?
Angular Material should be compatible with Angular 4.0

#### What is the current behavior?
+-- UNMET PEER DEPENDENCY @angular/common@4.0.0
+-- UNMET PEER DEPENDENCY @angular/core@4.0.0
+-- UNMET PEER DEPENDENCY @angular/http@4.0.0
`-- @angular/material@2.0.0-beta.2

npm WARN @angular/material@2.0.0-beta.2 requires a peer of @angular/core@^2.3.0 but none was installed.
npm WARN @angular/material@2.0.0-beta.2 requires a peer of @angular/common@^2.3.0 but none was installed.
npm WARN @angular/material@2.0.0-beta.2 requires a peer of @angular/http@^2.3.0 but none was installed.

#### What are the steps to reproduce?
- Create a new project using Angular CLI:
ng new new-project

- Install the latest version of angular material in local project:
npm install --save @angular/material

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Upgrade to latest release of Angular CLI

#### Which versions of Angular, Material, OS, browsers are affected?
"dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular-in-memory-web-api": "^0.3.1",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }

#### Is there anything else we should know?
No

**Comment by willshowell** [comment]
@Alonsooo this has been resolved by #3608 and will appear in the next release

**Comment by Alonsooo** [comment]
I used:
npm install --save https://github.com/angular/material2-builds.git

Thank you!
