### ISSUE TITLE
Demo App on material.angular.io not working

### ISSUE THREAD

**Issue by SamuelSchepp** [angular/material2#3818]
#### Bug, feature request, or proposal:
The Demo App on material.angular.io is not working properly.

#### What is the expected behavior?
Demo App loads.

#### What is the current behavior?
- It says "Loading document..." on the page 
- StackTrace with message "Unhandled Promise rejection: Cannot read property 'document' of undefined"
- Whole Page unresponsive

#### What are the steps to reproduce?
Open https://material.angular.io/guide/material2-app

**Comment by Chan4077** [comment]
Duplicate of #3388

**Comment by jelbourn** [comment]
Duplicate of #3388
