### ISSUE TITLE
Grid animations removing dom element before the animation completes.

### ISSUE THREAD

**Issue by GeremyHamlett** [angular/material2#3819]
#### Bug, feature request, or proposal:
When using the angular animation module and removing a grid element (* => void) the animation runs, but runs after the dom element has been removed.

#### What is the expected behavior?
I would expect the animation to finish before removing the element.

#### What is the current behavior?
Grid elements appear to be removed before the animation thus causing a visual effect that either hides the animation or run behind the other grid elements that fill its spot when the grid collapses.

#### What are the steps to reproduce?
This shows the behavior im seeing.  On the top you can see a normal list that uses a translate animation in the negative Y direction.  I have three sections.  The first (top) section is a normal list array with a button that removes the top element.  You can see this runs the animation and the list collapses after the animation completes.  The second (middle) section is using a Material card array.  Here the behavior is the same.  The delete button runs the animation and then collapses the card list. The third (bottom) section is using a grid display (w/ cards).  Here you can see the delete collapses the grid array either while or before the animation runs. 
https://plnkr.co/edit/tFB9NVOuQMa3yQrNPlOt?p=preview

#### What is the use-case or motivation for changing an existing behavior?
To be visually the same I would expect the grid display to collapse in the same manner as the card array.  Where the animation executes first then the grid collapses.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.0, Material 2.0.0-beta2

**Comment by jelbourn** [comment]
I don't think this has to do with Angular Material; the grid-list doesn't do anything with animations and, as far as `@angular/animations` is concerned, it's just like any other div.
