### ISSUE TITLE
Repository for themes

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#3827]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior
Something Mike a npm repository that contains 3rd Party prebuild themes for Material and also material compatible themes for 3rd Party libraries. I think of something similar to tsd in the typescript world.

#### What is the use-case or motivation
This would be a great way to share custom color palettes and also make it a lot easier to usw 3rd Party libraries with ng material. For example we use the ngx data table. This component comes with an optional material stylesheet which of course does not come as scss with material theme mixins and is not 1:1 in terms of fonts and colors. To use it in a real world scenario, you have to modify the theme from ngx and create theme mixins to match your color palette. It would be great to have some repo where one can upload such a customized, material compatible 3rd party theme and easily share it with others. Also when material gets updated (like the change from md- to mat-) this would make it a lot easier to update when using 3rd party updates as one can update the themr and anyone can simply update packages.

A repo like this would need some coding style guidelines for sure. So a clear style guide on how to structure themes for custom components by the material team would be a good first step.

**Comment by jelbourn** [comment]
Something like this would be neat, but it's not something that we have the capacity to start up / maintain.
