### ISSUE TITLE
SVG Icon performance

### ISSUE THREAD

**Issue by timruffles** [angular/material2#3828]
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

SVG icons do not slow down app boot

#### What is the current behavior?

They massively slow down app boot. e.g per material SVG icon set, I'm seeing 20-80ms to parse the SVG (`_svgElementFromString` is the dominant cost).

![screen shot 2017-03-29 at 11 04 12](https://cloud.githubusercontent.com/assets/249800/24449540/76363e80-146f-11e7-9c0f-885183982430.png)

#### What are the steps to reproduce?

Load a material icon set

Perhaps this could be done AOT? Or lazily?

**Comment by jelbourn** [comment]
I'm not really sure what `md-icon` specifically can do about this for now. The purpose of the component is to inline SVG icons into the DOM from a URL, which ultimately means the string has to be parsed by the browser (however long that takes). Forgoing `md-icon` and instead using an `<img>` element or `background-image` style may speed things up for you while giving up the ability to style the svg nodes. 

I could potentially see the Angular AoT compiler someday doing the same thing for SVGs files that it does for templates now, but that would be a feature request for https://github.com/angular/angular/

**Comment by PierreChavaroche** [comment]
My solution to this problem is to just use a subset of the material SVG icon set (exclusively those which I'am using in my app). Editing the SVG file (e.g. mdi.svg for [https://materialdesignicons.com/](https://materialdesignicons.com/) ) is very easy.

**Comment by rchod** [comment]
is it possible to add feature to handle SVGs by sprites ? https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Implementing_image_sprites_in_CSS
