### ISSUE TITLE
Md - slider is not showing. 

### ISSUE THREAD

**Issue by param-bnb** [angular/material2#3830]
I have added hammer.js. i just added < md-slider >    </ md-slider >..
Other components are working fine.. 

Do you have any suggestions?

**Comment by fxck** [comment]
Provide a plunker reproduction otherwise none will be able to help you.

**Comment by rdelriods01** [comment]
@param-bnb which version of Angular are you using? I have similar problem, and I'm in Angular 4.

**Comment by Chan4077** [comment]
@param-bnb Are there any errors in the console?

**Comment by AndyHaas** [comment]
Check out this page. Had the same issue then started to read their documentation. I have been one to not read instructions before. But this helped me as I also was on Angular 4.

https://material.angular.io/guide/theming

If the theming is not not linked in then it will not show the slider as there is no css to do so. they give you several prebuilt files or you can make your own. 

NOTE:: Hint for your class you will need class="mat-app-background" this would be put on the body normally


Hope this helps
Andy

**Comment by jelbourn** [comment]
The latest release will log a warning if a theme is missing, so hopefully that will make issues like this easier to diagnose.
