### ISSUE TITLE
Angular 4 Compatability

### ISSUE THREAD

**Issue by craig-o-curtis** [angular/material2#3832]
#### Bug, feature request, or proposal:
Proposal -- make material2 compatable with Angular 4 or make a new material4 or just ng-material repo.

#### What is the expected behavior?
No console errors regarding use of template instead of ng-template, and other unforeseen inconsistencies with Angular 4.

#### What is the current behavior?
One console warning reads:
core.es5.js:3053Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): ng:///MdAutocompleteModule/MdAutocomplete.html@0:0

#### What are the steps to reproduce?
Use Angular-CLI with Angular 4, install material2..

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Angular 4.

#### Which versions of Angular, Material, OS, browsers are affected?
All browsers. Angualr 4.0.0. Angular Material2 latest.

#### Is there anything else we should know?
Thank you.

**Comment by fxck** [comment]
https://github.com/angular/material2/issues?utf8=%E2%9C%93&q=Angular%204

**Comment by crisbeto** [comment]
Angular 4 supports was added in https://github.com/angular/material2/pull/3752 and will be available in the next release.
