### ISSUE TITLE
Error running gulp build:release

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#3834]
#### Bug:
running
gulp build:release
/material2/src/lib/index.ts:7:53: Cannot find module '.corea11ylive-announcer'

#### What is the expected behavior?
build done

#### What is the current behavior?
Errors

[20:44:33] 'library:build:esm' errored after 2.63 s
[20:44:33] Error: Error at C:/wx/joujou/material2/src/lib/index.ts:7:53: Cannot find module '.corea11ylive-announcer'.
Error at C:/wx/joujou/material2/src/lib/index.ts:8:66: Cannot find module '.corecoordinationnique-selection-dispatcher'.
Error at C:/wx/joujou/material2/src/lib/index.ts:8:88: Hexadecimal digit expected.
Error at C:/wx/joujou/material2/src/lib/index.ts:9:89: Cannot find module '.coreoverlayoverlay-container'.
Error at C:/wx/joujou/material2/src/lib/index.ts:10:44: Cannot find module '.coreoverlaypositionoverlay-position-builder'.
Error at C:/wx/joujou/material2/src/lib/index.ts:11:103: Cannot find module '.coreoverlayposition♂iewport-ruler'.
Error at C:/wx/joujou/material2/src/lib/index.ts:12:89: Cannot find module '.coreoverlayscrollscroll-dispatcher'.
Error at C:/wx/joujou/material2/src/lib/index.ts:13:32: Cannot find module '.coreoverlayscrollscrollable'.
ipple-renderer'.oujou/material2/src/lib/index.ts:14:36: Cannot find module '.core
Error at C:/wx/joujou/material2/src/lib/index.ts:15:154: Cannot find module '.grid-listgrid-tile'.
    at new UserError (C:\wx\joujou\tools\@angular\tsc-wrapped\src\tsc.ts:33:5)
    at check (C:\wx\joujou\tools\@angular\tsc-wrapped\src\tsc.ts:81:11)
    at Tsc.typeCheck (C:\wx\joujou\tools\@angular\tsc-wrapped\src\tsc.ts:175:5)
    at C:\wx\joujou\tools\@angular\tsc-wrapped\src\main.ts:128:11
    at process._tickCallback (internal/process/next_tick.js:109:7)

#### What are the steps to reproduce?
run gulp build:release

#### Which versions of Angular, Material, OS, browsers are affected?
fresh git clone

**Comment by dahaupt** [comment]
Actually the file **material2/src/lib/index.ts** doesn't even exists. That's strange, but I'm not familiar with gulp tasks.

I think @DevVersion is responsible for fixing this.

**Comment by jennyraj** [comment]
Same issue here

**Comment by zigzag95** [comment]
index.ts is generated by the build task and deleted after the build finish

**Comment by dahaupt** [comment]
@zigzag95 That is good to know, thank you. Actually multiple gulp tasks are failing with the same error message. I wonder how it's working in CI.

**Comment by zigzag95** [comment]
no problem on OSX but errors on Windows

**Comment by kuncevic** [comment]
Same thing with `npm run demo-app`
`Win 7 x64`
`Node 6.9.2/7.8.0`
`Npm 4.4.4`

**Comment by DevVersion** [comment]
Thanks. This is a known issue we all experience at the moment. The build process works fine on Mac OS, which let's us think that it is caused by an `@angular/tsc-wrapped` issue. 

I will take a look at it again, otherwise we would need to wait for feedback from `angular/angular`.

**Comment by zigzag95** [comment]
FTI Replacing libs content by a test module and component works fine on w7
I suspect core a11y

**Comment by DevVersion** [comment]
Thanks fo

**Comment by jennyraj** [comment]
Thank you so much.  Bundler.ts fix worked in Win10!

**Comment by jelbourn** [comment]
I think this should be all working now.

**Comment by jelbourn** [comment]
Actually it may still be broken by https://github.com/angular/angular/issues/15403. In which case, you can follow that issue for updates.

**Comment by rtrompier** [comment]
Hi guys,

I have always the issue on windows 10. Do you have a solution ? 

Cheers,

**Comment by OogieBoogieInJSON** [comment]
@rtrompier See [#15642](https://github.com/angular/angular/pull/15642)
