### ISSUE TITLE
Font color on card and list

### ISSUE THREAD

**Issue by peluprvi** [angular/material2#3837]
#### Bug, feature request, or proposal:
Default text should be `color: rgba(0,0,0,.87)`, but `.mat-card`, `.mat-list .mat-list-item` and `.mat-nav-list .mat-list-item` has `color: #000`.

#### What is the expected behavior?
There is no #000 text color on [Material Typography Guidelines](https://material.io/guidelines/style/typography.html#typography-other-typographic-guidelines)
```css
color: rgba(0,0,0,.87)
```

#### What is the current behavior?
```css
color: #000
```
[Official list Plunkr demo](https://plnkr.co/edit/IGkVQ8wIdJuQDHjaZfsf?p=preview)

Print:
![image](https://cloud.githubusercontent.com/assets/1561360/24479713/ee6d28ae-14b6-11e7-9c9b-112bd916cff8.png)

#### What are the steps to reproduce?
* Configure a prebuilt theme;
* Create a list (or a card);
* Inspect its color

#### Which versions of Angular, Material, OS, browsers are affected?
https://github.com/angular/material2/commit/ab77fa95da07ba34f7f2a19b912b464cdef614c3

**Comment by Chan4077** [comment]
Please post a valid Plunkr link.

**Comment by peluprvi** [comment]
Links updated. Thanks @Chan4077 !

**Comment by willshowell** [comment]
Fixed by #3952
