### ISSUE TITLE
ngtool/webpack plugin breaks when using material

### ISSUE THREAD

**Issue by jorawarsingh** [angular/material2#3841]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It should not break aot compilation

#### What is the current behavior?
When including material in project give hunderds of errors without material it just work fine!

#### What are the steps to reproduce?

Just use @ngtool/webpack plugin and include material somewhere in your project and try to build it

#### What is the use-case or motivation for changing an existing behavior?
it should work without errors.

#### Which versions of Angular, Material, OS, browsers are affected?
4.0.0 chrome

#### Is there anything else we should know?
When you run this with webpack-dev-server  without --progress --color --bail flags you will see the errors. otherwise it will say Can't resolve './ngfactory/src/app/app.module.ngfactory'

**Comment by jelbourn** [comment]
Everything appears to be fine with the latest version when using the angular-cli / webpack. 

Feel free to open a new issue if you can provide a full reproduction.

**Comment by evanjmg** [comment]
It's working, but I think it's including extra code? I'm somehow getting the typings and es5.js in there. Which should I exclude? Or do I have to have both? It's quite a lot of code (100kb+ gzip) to have both. 
See my bundles here: 
<img width="378" alt="screen shot 2017-04-16 at 9 18 53 pm" src="https://cloud.githubusercontent.com/assets/9342155/25074005/6ba9207a-22ea-11e7-8448-e348dde13a86.png">
