### ISSUE TITLE
Are Portal, Overlay, ViewportRuler public or private

### ISSUE THREAD

**Issue by mikehaas763** [angular/material2#3849]
I'm curious about both immediately and future path if Portal, Overlay, and ViewportRuler are public or private APIs?

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/964#issuecomment-238687029

**Comment by mikehaas763** [comment]
Alright I'm going to close this out but if anyone has any more details about other APIs, etc please to comment back here.
