### ISSUE TITLE
Fixed Tabs

### ISSUE THREAD

**Issue by mattheiler** [angular/material2#3850]
#### Bug, feature request, or proposal:
Feature, or new component, depending on the design and integration with existing, scrollable tabs.

#### What is the expected behavior?
Fixed tabs, as described in the [guidelines](https://material.io/guidelines/components/tabs.html#tabs-types-of-tabs).

Google Plus has a working [example](https://plus.google.com/collections/yours).

**Comment by jelbourn** [comment]
I think this is the same as #2236
