### ISSUE TITLE
md-list-icon is not clickable inside md-nav-list

### ISSUE THREAD

**Issue by afriedma** [angular/material2#3859]
#### What is the current behavior?
When I have icon inside nav list, the click does'nt result in navigation event(route change)

#### What are the steps to reproduce?
                <md-nav-list>
                    <md-list-item>
                        <md-icon md-list-icon>notifications</md-icon>
                        <a md-line [routerLink]=".">Test</a>
                    </md-list-item>
                </md-nav-list>
#### What is the use-case or motivation for changing an existing behavior?
Confusing to the user

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.2/material 2.0.0-beta.2/Windows/electron 1.4.3

#### Is there anything else we should know?
Tt seems the click is not covering the entire link area as well.

**Comment by willshowell** [comment]
Can you reproduce it in a Plunker?

**Comment by afriedma** [comment]
https://plnkr.co/edit/s8UuFvLXTqGxGSxK3zXV?p=preview

**Comment by willshowell** [comment]
Try organizing it like this: https://plnkr.co/edit/qE6MHvOUzwX9BpjkFQkE?p=preview

It may not be totally clear from the docs, but if you look at [the source](https://github.com/angular/material2/blob/master/src/lib/list/list.ts#L127) you can see that MdListItem can be an anchor as well.

**Comment by afriedma** [comment]
Thank you for the prompt response, kind of not used to having other tags inside the <a> tag.
