### ISSUE TITLE
md-input with [(ngModel)] removes 'md-prefix' and 'md-suffix' content.

### ISSUE THREAD

**Issue by davidgabrichidze** [angular/material2#386]
Source HTML:
`<md-input placeholder="amount" [(ngModel)]="account.userName">
    <span md-prefix>$&nbsp;</span>
    <span md-suffix>.00</span>
</md-input>`

In rendered html prefix/suffix element's content are emtpy:
`...<div _ngcontent-ega-7="" class="md-input-prefix"></div>...`

versions:
- angular2: beta17
- material2: alpha-3

**Comment by nesukun** [comment]
Experienced this and a similar problem with checkbox labels (radio labels seem unaffected)

**Comment by davidgabrichidze** [comment]
In angular rc-1 and material2 alpha-4 this works normally

**Comment by nesukun** [comment]
Can confirm, this works with the versions @davidgabrichidze mentioned

**Comment by hansl** [comment]
Closing this as fixed. Cheers!
