### ISSUE TITLE
Clicking md-select should disable scroll

### ISSUE THREAD

**Issue by molcik** [angular/material2#3873]
#### Bug, feature request, or proposal:
feature

#### What is the expected behavior?
clicking md-select should disable scroll

#### What is the current behavior?
md-option position is fixed to screen view
![2017-04-02 06_56_09](https://cloud.githubusercontent.com/assets/11929953/24584556/9eae4b82-1771-11e7-9dd4-8f7d27df059a.gif)

#### What are the steps to reproduce?
Plunker: http://plnkr.co/edit/BkHyLxy1EPYEMLDCe5Tv?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Clicking md-select should disable scroll, to allow user to scroll in md-option list.

#### Which versions of Angular, Material, OS, browsers are affected?
all

#### Is there anything else we should know?
no

**Comment by crisbeto** [comment]
There is a pending PR to reposition the menu on scroll instead https://github.com/angular/material2/pull/3808.
