### ISSUE TITLE
md-select multiple not working

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/material2#3874]
```
 <md-select multiple placeholder="Topics" name="topics" [(ngModel)]="user.topics">
    <md-option  *ngFor="let topic of topics" [value]="topic.value">
      {{topic.display}}
    </md-option>
  </md-select>
```

I am not able to select multiple value in a select box angular material

**Comment by crisbeto** [comment]
The changes that add multiple selection haven't been released yet. You can either wait for the next release or install the latest build via `npm install --save https://github.com/angular/material2-builds.git`.
