### ISSUE TITLE
custom SnackBar

### ISSUE THREAD

**Issue by kstraszewski** [angular/material2#3881]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I would like to open my custom component by service. Service have 2 function OpenSuccessSnackbar(), and OpenErrorSnackbar(), and it looks like this:

`  OpenSuccessNotification(){
    this.snackbar.openFromComponent(SnackbarSuccessComponent, {
      duration: 3000
    });
  }
`

my SnackbarSuccessComponent looks like this 
`import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'app-snackbar-success',
  template: 'random text',
  styleUrls: ['./snackbar-success.component.css']
})
export class SnackbarSuccessComponent {
}`

#### What is the current behavior?
Angular opens empty snackbar for 3seconds.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0, material from master branch, win10

**Comment by willshowell** [comment]
Can you reproduce it in a plunker?

**Comment by jelbourn** [comment]
Cannot reproduce; feel free to open a new issue if you can provide a reproduction.

**Comment by barretodaniel** [comment]
I think this is because the zone doesn't detect the snackbar being opened when called from a service. I was having this issue all morning and I was able to resolve it by injecting `NgZone` into my service and calling the `openFromComponent` function inside `NgZone.run` , like so: 

```
this.zone.run(() => {
  const snackbar = this.snackbar.openFromComponent(NotificationComponent, {
    duration: 6000,
  });
  snackbar.instance.snackBarRef = snackbar;
});
```

**Comment by Charius** [comment]
@barretodaniel thanks for workaround, it also works when call `open` instead of `openFromComponent`.
