### ISSUE TITLE
change md-list `dense` attribute programmatically without "hack"

### ISSUE THREAD

**Issue by ocarreterom** [angular/material2#3882]
#### Bug, feature request, or proposal:
Proposal.

#### What is the expected behavior?
Change `dense` attribute programmatically.
```html
<md-list [dense]="dense"></md-list>
<!-- dense can be true or false -->
```

#### What is the current behavior?
`dense` is an html attribute stylized with CSS.
```css
.mat-list[dense], .mat-nav-list[dense] { }
```

#### What is the use-case or motivation for changing an existing behavior?
Is useful for main sidenav menu: dense for desktop and default for mobile.
Currently to change this option we have to do something like:
```html
<md-list [attr.dense]="dense"></md-list>
<!-- dense can be true or null -->
```
```ts
dense: true | null; // null to remove dense attribute from the DOM.
```

**Comment by DevVersion** [comment]
Closing this issue as this involves a whole density solution (See https://github.com/angular/material2/pull/4115#issuecomment-294532633)
