### ISSUE TITLE
md-option allow multiple lines

### ISSUE THREAD

**Issue by fxck** [angular/material2#3883]
It would be nice if it was possible to add more lines to a select option, similar to what you can do in `md-list-item` with `md-line`, currently the height is fixed to 48px (which I guess is because of the positioning to the active option upon opening) and width is capped at about 300px, so it's hard to give the option some secondary context which helps identifying the correct option you want to select

![image](https://cloud.githubusercontent.com/assets/1303561/24610352/8b074fa8-187e-11e7-9502-7491feca3a8d.png)

also `md-option-image` could be handy

cc @kara @crisbeto

**Comment by crisbeto** [comment]
1. I'm not sure whether the spec allows for multi-line options.
2. As you mentioned, this makes the positioning a bit harder.

**Comment by fxck** [comment]
It might be the case, that the spec does not allow it, but then again, I don't think spec mentions anything about capping max width at 300px either. 
And I also think it's a fair use case no matter what spec says. So how about this, if the spec doesn't allow multi-line, it should still be possible for the consumer to modify the behavior to some extent  (as is the case where you override some css property), which is currently not possible with md-option, because some of the values are hardwired into javascript, since the height doesn't really need to be dynamic, all this would really require is the ability to modify the height used for calculations with an [input], wdyt @crisbeto?

**Comment by willshowell** [comment]
From the [spec on simple menus](https://material.io/guidelines/components/menus.html#menus-simple-menus) (afaik there is no spec for select?):

* **Do:** Use a simple dialog if any text in a simple menu wraps to a second line.
* **Don't:** Don’t truncate text in a simple menu. Use a simple dialog instead.

So it appears that both truncating options and multi-line options are wrong? That said, it also appears that panel width shouldn't be capped around 300px

![screen shot 2017-04-04 at 10 18 48 am](https://cloud.githubusercontent.com/assets/6475576/24661355/26938ada-1920-11e7-9e6a-dcd355714546.png)

**Comment by fxck** [comment]
Menu and selects are different thing altogether I think, so if it doesn't disallow multi-lines, I think it would really be worth exploring.

**Comment by crisbeto** [comment]
I agree on not capping the width, but regarding the multi line text, we can also refer to the native `select` which also truncates instead of wrapping.

**Comment by fxck** [comment]
Yes, but honestly, I think that material should enhance the experience, not blindly follow design that hasn't changed in 15 years..

**Comment by jelbourn** [comment]
Based on the material design spec, we don't see multi-line options for `<md-select>` being permitted. For autocomplete, though, it should be doable. Tracking via #4071
