### ISSUE TITLE
routerLinkActive is not working on md-list-item inside md-nav-list

### ISSUE THREAD

**Issue by afriedma** [angular/material2#3884]
#### Bug, feature request, or proposal:
bug, routerLinkActive is not working on md-list-item inside md-nav-list

#### What is the expected behavior?
on active route change, call a function to set active item in the list

#### What is the current behavior?
no public methods are available, setting [routerLinkActive]="['mat-list-item-focus']" doesn't produce the expected result

#### What are the steps to reproduce?
https://plnkr.co/edit/s8UuFvLXTqGxGSxK3zXV?p=preview

#### What is the use-case or motivation for changing an existing behavior?
redirection to the page and pre-selecting/highlighting an item for the user

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.2/material 2.0.0-beta.2/Windows/electron 1.4.3

**Comment by afriedma** [comment]
I can reproduce the issue using the Plunker below.

https://plnkr.co/edit/s8UuFvLXTqGxGSxK3zXV?p=preview

**Comment by crisbeto** [comment]
`routerLinkActive` works as expected, however Material has an internal listener that will add/remove the class when the element is focused/blurred, which ends up removing it in your case. I recommend adding your own class that does the highlighting. [You can see how it is done in Material here](https://github.com/angular/material2/blob/master/src/lib/list/_list-theme.scss#L23) and [here's an example of how to do it.](https://plnkr.co/edit/1B56dRVHyh9Z9BTjQ4Ov?p=preview)

**Comment by afriedma** [comment]
Thank you for reply, but how can you doing in the context of the theme?  I am unable to figure it out.

**Comment by afriedma** [comment]
https://plnkr.co/edit/KYKEk0UK5FAIdgjFyJIX?p=preview

here is the plunkr

**Comment by crisbeto** [comment]
[You can refer to the theming guide.](https://material.angular.io/guide/theming-your-components)

**Comment by afriedma** [comment]
My second plunkr includes the theming.  I took a crack at it and it doesn't work.  The documentations is very limited, if you can point out the issue with my plunkr, I would very much appreciate it, as I am pressed against the deadline here.  Thanks in advance.

**Comment by afriedma** [comment]
Also is there a way for force md-list-item to loose focus, as if nothing is selected.

Cheers, Alex
________________________________

**Comment by crisbeto** [comment]
That second Plunkr doesn't work, because you're referring to the SASS mixins using the Webpack syntax. You'll need to figure out how to import it in your build system. Alternatively you can hard-code the color as a quick fix, since the Material theming only computes the color. As for not showing focus on the element, it isn't supported, because it degrades the accessibility of the component.

**Comment by afriedma** [comment]
Thank you for your replies, even though the issue is closed, I really appreciate it.

I got active route to work with the theme.  But now my issue is, when I redirect the route, I end up with two highlighted items in the nav list, last clicked item and item I routed too.  My approach was to remove focus or simulate the click, but highlight on the originally clicked item won't go away.

And the weird thing is that, I only see this behavior with theme approach, I don't see it happening with explicit css class, just like you showed me. 

Can you recommend a work around?

**Comment by afriedma** [comment]
Did you get a chance to look at my earlier reply?  Please help.

Cheers, Alex
________________________________

**Comment by crisbeto** [comment]
I'm not exactly sure why it's working with the explicit theme. If you really don't want that focused background, you can disable it via CSS completely:

```css
.mat-nav-list .mat-list-item-content:hover, .mat-nav-list .mat-list-item-content.mat-list-item-focus {
  background: none;
}
```

**Comment by afriedma** [comment]
Hi, I tried adding your css, but it seems to not disable anything. Any other ideas?

**Comment by peimelo** [comment]
Hi,
this work for me:

https://github.com/angular/material2/blob/master/src/demo-app/demo-app/demo-app.html#L7-L10

**Comment by Robinyo** [comment]
See: https://github.com/angular/material2/issues/13084#issuecomment-431570606
