### ISSUE TITLE
How to set default selected option in md-select component?

### ISSUE THREAD

**Issue by IvanProdaiko94** [angular/material2#3889]
Is there any chance to set default selected option to md-select?

**Comment by fxck** [comment]
Hey, github issues are for bugs and feature requests. Gitter or stackoverflow are better suited for support requests.

**Comment by IvanProdaiko94** [comment]
But, I can't find this feature in md-select. So, if there is no such a thing, that is my proposal to add it.

**Comment by fxck** [comment]
Yeah, but there obviously is a way to do it, and it's not even related to `md-select` component or `angular/material2` at all, but rather to `angular/angular` and their `FormsModule` or `ReactiveFormsModule`. In other words, you'd set the default value on `md-select` the same way you'd set it on standard select element.

**Comment by IvanProdaiko94** [comment]
nope. let me explain the problem more accurately. `md-select` component  encapsulate `select` tag inside itself, so I can't directly manage the `select` state. so there should be an `input` decorator to provide default selected option. But in [https://material.angular.io/components/component/select](api reference) there is no such a thing. So, I tried to use `ngModel` to obtain default option, but I haven't got this working.
After all I noticed another thing to

**Comment by fxck** [comment]
Then you should have perhaps followed the issue template and provided a plunk with reproduction of your `ngModel` problem, included version of angular and material, because it seems to be working perfectly fine for me: http://plnkr.co/edit/45aib6M3hYW4p9BUOi3w?p=preview which makes me thinnk this *is* a support request, which simply doesn't belong here.

**Comment by IvanProdaiko94** [comment]
After updating to beta.2 everything worked fine. It was fully my mistake. Sorry for opening this silly issue. @fxck lots of tnx for helping me.
