### ISSUE TITLE
md-checkbox strange repetition call to checked function

### ISSUE THREAD

**Issue by mrbinr** [angular/material2#3891]
#### Bug, feature request, or proposal:
I've a copied md-checkbox example from https://www.npmjs.com/package/@angular2-material/checkbox and i've modified «checked» to use a function.

So my code is  :
```html
<ul>
    <li *ngFor="let todo of ['a','b','c']; let i = index">
        <md-checkbox [checked]="this.toCheck(i)">{{todo}}</md-checkbox>
    </li>
</ul>
```
and into component : 
```javascript
    ...
    toCheck(idx): boolean {
        console.log('idx='+idx);
        return (idx == 1);
    }
    ...
```

#### What is the expected behavior?
So, then i expect to have in console :
```
idx=0
idx=1
idx=2
```

#### What is the current behavior?
but i have 
```
idx=0
idx=1
idx=2
idx=0
idx=1
idx=2
idx=0
idx=1
idx=2
idx=0
idx=1
idx=2
```
... 8 times ...

#### Which versions of Angular, Material, OS, browsers are affected?
I am using Ubuntu 16.04,  Angular 2.4, Material @angular/material@2.0.0-beta.2

#### Is there anything else we should know?
Strangely, i've noticed another fact, that logs are displayed each time mouse is out of an material element (not only checkedbox, but button too ...)...
...hummmm...

**Comment by willshowell** [comment]
You're only seeing 3 rendered checkboxes right? `toCheck()` should be called every time change detection runs, which is expected behavior. Do you think you could replicate this in a plunker?

**Comment by mrbinr** [comment]
[plunker replication](https://plnkr.co/edit/Sp87YGw3MNUNEHgoMCMe?p=preview)
In this example, you will see that, without clicking on any checkbox, log are displayed in firebug console and more than 3 times ...

**Comment by willshowell** [comment]
Again, that is expected behavior. If you add `changeDetection: ChangeDetectionStrategy.OnPush` to your component's decorator, you'll see that `toCheck()` is called only once on init.

Read more here: https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html

This is not an issue with angular/material, but fundamental to how angular works.

**Comment by mrbinr** [comment]
Ok thanks for your help, they are still a lot of thing to learn about angular2 behaviour :)
