### ISSUE TITLE
md-input not responsive in card

### ISSUE THREAD

**Issue by NishantDesai1306** [angular/material2#3898]
#### Bug, feature request, or proposal:
Navigate to Examples tab at page https://material.angular.io/components/component/input and I tried to simulate mobile screens on that page but the form is not responsive

#### What is the expected behavior?
Form should be responsive and it should change the size of the input elements based on the size of screen

#### What is the current behavior?
input elements are not responsive

**Comment by donroyco** [comment]
The 'bug' you're referring to is no bug, but deliberately done. The parent of the inputs is set to a fixed width (`500px`). If you change that value to `100%`, the content (and thus input fields) is scaling nicely.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
