### ISSUE TITLE
Docs site dialog example plunker is broken

### ISSUE THREAD

**Issue by kronetorres** [angular/material2#3899]
#### Bug, feature request, or proposal:

The Dialog Component in the plunker Demo throws exeption: "The selector "dialog-overview-example-dialog" did not match any elements".

#### What is the expected behavior?

App work just fine but throws exception.

#### What are the steps to reproduce?

Go to Documentarion about  [Dialog Component ](https://material.angular.io/components/component/dialog)  and click on Edit on Plunker

#### What is the use-case or motivation for changing an existing behavior?

Because it confuses beginners like me

#### Is there anything else we should know?

Fix:
change

bootstrap: [DialogResultExample, DialogResultExampleDialog],

for

bootstrap: [DialogResultExample],
entryComponents: [DialogResultExampleDialog],

in main.ts file

**Comment by M-a-c** [comment]
Sort of related to #2934 (multi file demos don't list other files), multi component(selector) demos are broken on plunkr.

**Comment by ericgundrum** [comment]
@kronetorres, thanks for the fix. This seems relevant to any project using MdDialog, more than just the plunker example.

**Comment by TheRedD0t** [comment]
@kronetorres @jelbourn I guess this issue can be closed.
