### ISSUE TITLE
feature request: bottom navigation

### ISSUE THREAD

**Issue by mikehaas763** [angular/material2#390]
* **Do you want to request a *feature* or report a *bug*?**

Request a feature + implement the feature: **bottom navigation**.

* **What is the current behavior?**

Doesn't exist.

* **What is the expected behavior?**

Hopefully, it will exist? :smile:

* **What is the motivation / use case for changing the behavior?**

I need to build a bottom based navigation for something I'm working on, so I figured I might as well build it and contribute it to material2

The component I'm referring to is https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-usage

Is there any appetite for this component in the library?

**Comment by jondejong** [comment]
Can you do this with just the toolbar and some flex layouts? Here's a quick example: 

https://github.com/jondejong/ng2-md-bottom-nav-bar

**Comment by mikehaas763** [comment]
@kara I've started work on this, basically just boilerplate at this point for the component itself and the demo app. Is it beneficial to create a PR before it's ready (so others can see that it's being worked on) or does that complicate the process?

**Comment by kara** [comment]
The first step is to create a design doc (you can find example design docs linked in the README). Once we've approved the approach, generally the next step is a WIP pull request.

**Comment by jelbourn** [comment]
Going to track this via #408. If anyone plans on working on this, the first step is to comment on that PR stating your **intent to implement**, along with how you plan to approach it. The next step is to write a design document for the team to review (following our [template](https://docs.google.com/document/d/1kpQStAn9L-NX_1bGz_4fXNeZgerWC0mUJHun72bF240/preview)). You can see the [directory of existing design docs on our wiki](https://github.com/angular/material2/wiki/Design-doc-directory).
