### ISSUE TITLE
angular4 support

### ISSUE THREAD

**Issue by mscu** [angular/material2#3900]
#### Bug, feature request, or proposal:

please provide a release that is working with the angular 4 final version. The latest release currently still relies on angular 2.x and even in the master its just the rc.

#### What is the use-case or motivation for changing an existing behavior?

updating angular to version 4.0

#### Which versions of Angular, Material, OS, browsers are affected?

angular 4

**Comment by AAAnderson7301** [comment]
@mscu Does this merge not cover that? merge #3752 . I am using Angular 4.0.1 and Material @Master and have 0 issues.

**Comment by alexw10** [comment]
I believe @mscu is this hasn't been released yet so he is not getting the update.
@mscu you can get the latest releases.
https://github.com/angular/material2-builds

**Comment by crisbeto** [comment]
The others pretty much covered it: the next release will include Angular 4 support.

**Comment by basst314** [comment]
Hi @crisbeto, could you please give us more information about when the next version will be released?
It has almost been 2 weeks since angular4 was released and people wanna use it together with a proper material dependency... thanks!

**Comment by crisbeto** [comment]
It should be within a few days @basst314. If you don't want to wait for it, you can install the build from `master`:

```
npm install --save https://github.com/angular/material2-builds.git
```

**Comment by Cogitaria** [comment]
`npm install --save https://github.com/angular/material2-builds.git`

Specified @angular/blah 4.0.0 in package.json but getting unmet peer on @angular 4.0.1.  running the above command.  Does it really "depend" on that patch?
