### ISSUE TITLE
tab component: responsive pagination controls do not appear/disappear on window size change

### ISSUE THREAD

**Issue by mscu** [angular/material2#3901]
#### Bug, feature request, or proposal:

The tab control offer pagination control to scroll left and right which should automatically appear when the tab labels exceed the header size. Unfortunately the pagination controls do not appear reliantly and do not show up on screen size change. Instead they suddenly appear if you click on a tab label and also do not disappear relaintly.

see these screen caps (from the demo page).

Changing only the screensize has no effect at all:
![1](https://cloud.githubusercontent.com/assets/545229/24673580/1d29d3ba-1979-11e7-8617-1dc289e11c22.gif)

Clicking on a tab label, they appear/disappear:
![2](https://cloud.githubusercontent.com/assets/545229/24673581/2089d65e-1979-11e7-85fa-de7c8153ac6c.gif)

#### What is the expected behavior?

The pagination arrows should appear and disappear when the screen size changes.

#### What is the current behavior?

The pagination arrows do not appear and disappear when the screen size changes, only when you click.

#### What are the steps to reproduce?

Go to the demo page and reduce the window size. No pagination control appear. Click on a tab label and then they appear. Increase the window size, the pagination controls do not disappear. Click on a label and then they disappear.

#### What is the use-case or motivation for changing an existing behavior?

Better mobile support.

#### Which versions of Angular, Material, OS, browsers are affected?

angular2, material beta 2, chrome

**Comment by donroyco** [comment]
Same as #3500

**Comment by mscu** [comment]
sorry, didn't see your issue, so i'll close mine
