### ISSUE TITLE
Bug (material.angular.io): Invisible "Learn Angular" on docs site

### ISSUE THREAD

**Issue by M-a-c** [angular/material2#3903]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
The Angular logo and Learn Angular are visible.
![hidden](https://cloud.githubusercontent.com/assets/1916685/24678257/adb5fc6e-193e-11e7-8fc7-5198c2dd485e.png)
![highlighted](https://cloud.githubusercontent.com/assets/1916685/24678258/adb6f632-193e-11e7-87e8-82c77b61fbe6.png)

#### What is the current behavior?
Both are practically Invisible.

#### What are the steps to reproduce?
Visit any page with the footer in it. at material.angular.io

#### What is the use-case or motivation for changing an existing behavior?
If content is there, the user should be able to see it.

#### Which versions of Angular, Material, OS, browsers are affected?
Materials current website.

#### Is there anything else we should know?
the issue is located inside `<app-footer>` for the website.
This seems to be outside the scope of the Git repo. Would fix if I could find where it was in git.

**Comment by Chan4077** [comment]
The website source code is located [at this git repo](https://github.com/angular/material.angular.io)

**Comment by M-a-c** [comment]
Completely unrelated.

@Chan4077 
in regards to your Market2 repo.
"(Why are there so many problems with code blocks??? 😓)"
Try visualStudio code, its got the ability to install linters and stuff its really great.

**Comment by Chan4077** [comment]
@M-a-c It's just because I had some problems with Markdown, where I tried to put some code blocks in a list.
And yes, I use Visual Studio Code.

**Comment by jelbourn** [comment]
The footer's background color is now back.
