### ISSUE TITLE
Protractor cannot read Component - Input text

### ISSUE THREAD

**Issue by mihaibuba** [angular/material2#3904]
#### Bug, feature request, or proposal:
Bug or Feature request

#### What is the expected behavior?
The automation of the component - input with protractor should be able to read 

#### What is the current behavior?
It is not possible (that I know) to retrieve the content of a input that is using a "user agent shadow dom"
https://github.com/w3c/webcomponents/issues/354

#### What are the steps to reproduce?
Run the following protractor test:
describe('Material 2', function() {
  it('I should read input text', function() {
    browser.get('https://material.angular.io/components/component/input');

	var EC = protractor.ExpectedConditions;
	var favFood = element(by.xpath("//input[@placeholder='Favorite food']"));
	browser.wait(EC.elementToBeClickable(favFood), 10000);
		
	//Not working: <Failed: No element found using locator: By(css selector, *[id="inner-editor"])>
	//var content = favFood.element(protractor.By.id('inner-editor'));
	
	//Not working deprected spec: /deep/
	//element(by.deepCss('.foo')) equivalent to 'element(by.css('* /deep/ .foo'))
	//var lastNameFieldShadow = lastNameField.element(by.deepCss('div'));
	//var lastNameFieldShadow = lastNameField.element(by.css('div'));
	
    expect(favFood.getText()).toEqual("Sushi");
  });
});

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
It should be possible to write automated test cases against an app developed using Material Design

#### Which versions of Angular, Material, OS, browsers are affected?
Material Design 2

**Comment by ciesielskico** [comment]
Try `expect(favFood.getAttribute('value')).toEqual("Sushi");`

**Comment by mihaibuba** [comment]
That might work in this particular case, because it has the tag "Value".
How can that tag be displayed, because unfortunately it doesn't for the application that we are suppose to test. The objects look like below (Copy element in Google Chrome doesn't even copy the content inside the Shadow dom
_______________________________________
<md-input-container class="mat-input-container ng-valid ng-dirty ng-touched"><div class="mat-input-wrapper"><div class="mat-input-table"><div class="mat-input-prefix"></div><div class="mat-input-infix">
                            <input id="lastName" mdinput="" placeholder="Last Name *" ng-reflect-form="[object Object]" ng-reflect-id="lastName" ng-reflect-placeholder="Last Name *" ng-reflect-debounce-time="1000" class="ng-valid mat-input-element ng-dirty ng-touched" aria-describedby="">
                        <span class="mat-input-placeholder-wrapper"><label class="mat-input-placeholder mat-float" for="lastName">Last Name * </label></span></div><div class="mat-input-suffix"></div></div><div class="mat-input-underline"><span class="mat-input-ripple"></span></div></div></md-input-container>
_______________________________________
<md-input-container class="ml-xs mr-xs mat-input-container ng-untouched ng-pristine" style="width:100%;" ng-reflect-class-base="ml-xs mr-xs"><div class="mat-input-wrapper"><div class="mat-input-table"><div class="mat-input-prefix"></div><div class="mat-input-infix">
                            <input id="dob" mdinput="" placeholder="Date of Birth *" type="date" disabled="" ng-reflect-form="[object Object]" ng-reflect-id="dob" ng-reflect-placeholder="Date of Birth *" ng-reflect-type="date" class="ng-untouched ng-pristine mat-input-element" aria-describedby="">
                        <span class="mat-input-placeholder-wrapper"><label class="mat-input-placeholder mat-float" for="dob">Date of Birth * </label></span></div><div class="mat-input-suffix"></div></div><div class="mat-input-underline mat-disabled"><span class="mat-input-ripple"></span></div></div></md-input-container>
_______________________________________
![first name](https://cloud.githubusercontent.com/assets/18402330/24709386/b5b6b9b8-19e7-11e7-8b06-5d943e49a761.PNG)
![dob](https://cloud.githubusercontent.com/assets/18402330/24709393/bb670ff2-19e7-11e7-9444-8d1b3db7e11d.PNG)

**Comment by jelbourn** [comment]
Tracking this via #5265 ; if something is broken we'll have to fix it, otherwise we'll have an example of how to do it.
