### ISSUE TITLE
Problem loading animations

### ISSUE THREAD

**Issue by romafederico** [angular/material2#3909]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I want to load the BrowserAnimationsModule. I've followed the instructions on the getting started guide.

#### What is the current behavior?
When wepack compiles the app it gives me an error

>  '@angular/platform-browser/animations"' has no exported member 'BrowserAnimationModule'."

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
I want to start a basic project using angular-cli and material2

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.0 - Material2 - macOS 10.12

**Comment by fxck** [comment]
Your plunker reproduction seems to be working fine.

**Comment by romafederico** [comment]
I don't know why that's the. I didn't include any plunker.

**Comment by fxck** [comment]
Include it then.

**Comment by jelbourn** [comment]
@romafederico Check out https://github.com/angular/material.angular.io as an example of an app that's importing `BrowserAnimationsModules`.
