### ISSUE TITLE
After update project to Angular 4. Issue material Can't resolve 'hammerjs'

### ISSUE THREAD

**Issue by GigaDeveloper** [angular/material2#3910]
After I update project to angular 4, ng serve shows me this error. how can I solve problem?

ERROR in project/node_modules/@angular2-material/core/gestures/MdGestureConfig.d.ts (4,40): Cannot find name 'HammerManager'.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve 'hammerjs' in '/project/src'
 @ ./src/main.ts 1:0-18
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by fxck** [comment]
`@angular2-material` is an outdated, deprecated module, use `@angular/material` instead, this could also be an artefact of some of your older versions of app, try removing node_modules and clearing npm cache.

**Comment by GigaDeveloper** [comment]
@fxck I just installed packages. Everything is up to date. I think Material does not support angular version 4 :(

**Comment by fxck** [comment]
This plunker is running angular4 and material beta.2 and works fine http://plnkr.co/edit/Z2JxDlolIv5ISR8dIQ72?p=preview

**Comment by DevVersion** [comment]
Yes. `angular2-material` is outdated. Please install using `npm install @angular/material --save`
