### ISSUE TITLE
Incorrect positioning of the dialog (IE10)

### ISSUE THREAD

**Issue by ivanov-v** [angular/material2#3911]
#### Bug, feature request, or proposal:
Incorrect positioning dialog (IE 10)
The reason in the absence of prefixes
![image](https://cloud.githubusercontent.com/assets/13759065/24694493/cf02873c-19ea-11e7-9003-84bb667566ce.png)
How do I add prefixes?

#### What is the expected behavior?
The dialog should be in the middle of the screen

#### What is the current behavior?
It is displayed in the upper left corner

#### What are the steps to reproduce?
Open IE 10

#### What is the use-case or motivation for changing an existing behavior?
Incorrect display of the dialog

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2, Material 2, Windows 7, IE10

**Comment by crisbeto** [comment]
The reason is that we don't officially support IE 10. [Here's what browsers are supported.](https://github.com/angular/material2#browser-and-screen-reader-support)

**Comment by AAAnderson7301** [comment]
@ivanov-v  did you make any progress on this? I am building a SharePoint add in with Angular 2 and the master page is forcing IE 10 and I cannot change that.
