### ISSUE TITLE
Select popup width exceed the container width

### ISSUE THREAD

**Issue by un33k** [angular/material2#3914]
#### Bug (possible)
The select popup has a width that is wider than its container. In particular, this causes horizontal scroll on small screens.

#### Expected behavior?
The width of a select popup should match its container.

#### What is the current behavior?
Select popup width exceed the container width

#### What are the steps to reproduce?
Plunker template: http://embed.plnkr.co/jGZw7bFxLeFKASjxO6De/

#### What is the use-case or motivation for changing an existing behavior?
Each inner box should respect the boundary of its container.

#### Which versions of Angular, Material, OS, browsers are affected?
os: darwin x64
node: 6.9.5
angular/cli: 1.0.0
angular/*: "^4.0.0",
angular/material": "^2.0.0-beta.2",

#### Is there anything else we should know?
The current behavior may seem correct by some, however, on mobile devices when the viewport is specifically set to `user-scalable=0`, to prevent any zoom and dragging, this little **anomaly** makes the page draggable horizontally which renders the designer's intent ineffective.

**Comment by josephperrott** [comment]
Closing as it appears this issue is no longer happening in later releases.
