### ISSUE TITLE
[Chrome]: md-menu opens in the wrong location if the triggering element is sticky positioned

### ISSUE THREAD

**Issue by Maistho** [angular/material2#3916]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`md-menu` should be positioned in the correct position when the triggering button is inside a sticky positioned element.

#### What is the current behavior?
`md-menu` is positioned relative to how far down the page is scrolled, not as to the real position of the element.

#### What are the steps to reproduce?
http://plnkr.co/edit/fWkLcpanX7i4Og0PlniI?p=preview
1. Scroll down slightly
2. Press the menu button inside the sticky positioned toolbar
3. Notice how the positioning is way off.

#### What is the use-case or motivation for changing an existing behavior?
It should be possible to use position sticky for toolbars and similar.

#### Which versions of Angular, Material, OS, browsers are affected?
Chrome

Firefox and Safari displays correct behaviour.

**Comment by crisbeto** [comment]
[This appears to be a Chrome issue.](https://bugs.chromium.org/p/chromium/issues/detail?id=672457)

**Comment by jelbourn** [comment]
Going to close this since it's a Chrome bug and there's not really anything we can do about it here.

**Comment by Maistho** [comment]
Would it be possible to wrap the calls in a timeout? Seems like it would solve the issue according to [this fiddle]
(https://jsfiddle.net/haLz537b/). 

Because it seems like it'll be a while before the fix for that bug lands in stable chrome.

**Comment by jelbourn** [comment]
@Maistho feel free to send a PR with a workaround and we'll take a look

**Comment by Maistho** [comment]
@jelbourn sure, I'll get it up later tonight.

**Comment by Maistho** [comment]
I can't get it to work reliably, most of the time putting it in a timeout works, but about 10% of the time it still gives me the wrong value even as long as 800ms after. 😕 

Waiting that long to trigger the menu isn't feasible at all, so I guess using md-menu in that way just will have to wait until that bug is fixed in chrome.
