### ISSUE TITLE
Consistent component structure throughout the project

### ISSUE THREAD

**Issue by alexw10** [angular/material2#3921]
#### Bug, feature request, or proposal:
This is a proposal, material2 seems really to be all over the place in regards to where code is placed. If we take a look at what the style guide says https://angular.io/docs/ts/latest/guide/style-guide.html for example.

It seems like a format for the code should be something like this:
@Input() section - lexical order
@Output() section - lexical order
@[other decorators] - lexical order
ng functions - lifecycle order
constructor
ngOnChanges
ngOnInit
ngDoCheck
ngAfterContentInit
ngAfterContentChecked
ngAfterViewInit
ngAfterViewChecked
ngOnDestroy

Getters and setters - lexical order
Public functions - lexical order
Private functions - lexical order

What are your thoughts on me going through each component and reordering them to be like this?
If you all have a reason for having this the way you do, would love to see a document on where that is.

#### What is the expected behavior?
The project should be structured in a way so code is easy to find. Doing the convention I set above would allow for this.

#### What is the current behavior?
Seems to be pretty random as far as I can tell.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Being able to go into any component and know where to go in the file just because the structure is consistent throughout would be amazing.

**Comment by dalelotts** [comment]
I agree that the lack of consistent formatting of the code is a bit of a pain. The biggest impact is in my having a fork and wanting to merge changes from this repo. The diffs and merges are more difficult because there is no consistent way the code is changed.

It also means I can't improve my codebase without making my merges significantly more complicated.

I'd be happy to contribute back some PR's to put the code in any consistent format/arrangement that this team would like to use.

**Comment by M-a-c** [comment]
I wouldn't mind helping with this also. It is not that hard to re-order that stuff.

**Comment by crisbeto** [comment]
It's not necessarily hard to do it, but it would become merge conflict hell without any advantages. cc @jelbourn

**Comment by jelbourn** [comment]
I'll chat with the ready if the team about being nite consistent in future code, but changing it everywhere would be churn without significant benefit as @crisbeto says. Ultimately I didn't think the order of members in a class is very important (compared to having each of the members well documented and having self-explanatory code).

**Comment by dalelotts** [comment]
I disagree with @crisbeto's assertion. @crisbeto do you have any experience doing this to a code base in the past?  I've done this multiple times on projects significantly larger than this project and the merge conflict hell you are imagining simply does not happen.

How can this project be under the angular organization and have such widely different coding standards?

@jelbourn please consider applying the boy scout rule:

>  leave the campground cleaner than they found it

when the team makes changes a given file, apply the Angular team's style standards to the code at that time. Thus, leaving the code cleaner than they found it and consistent with the other Angular projects. At least this way the project will eventually get cleaned up.
