### ISSUE TITLE
When using @ViewChild element.nativeElement is undefined

### ISSUE THREAD

**Issue by kuncevic** [angular/material2#3922]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`@ViewChild` `element.nativeElement` has value

#### What is the current behavior?
`@ViewChild` `element.nativeElement` is `undefined`
```
@Component({
  selector: 'material-app',
  template:`
  <button #button md-raised-button>button</button>
  `
  
})
export class AppComponent {
  @ViewChild('button') button;
  ngAfterViewInit(){
    console.log(this.button);
    console.log(this.button.nativeElement); //undefined
    console.log(this.button.nativeElement.value); // obviously error here
  }
```

#### What are the steps to reproduce?
http://plnkr.co/edit/gSEsELlTAbrqvOOduSdr?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Need to access to an element with `@ViewChild`

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.1
Material beta.2
All browsers

#### Is there anything else we should know?
If you take out the `md-raised-button` from the button then `this.button.nativeElement` will work.

**Comment by Nikki1993** [comment]
As a workaround you can define Child like this

`@ViewChild('sidenavContainer') private sidenavContainer: any;` and then call 

`this.sidenavContainer._element.nativeElement`

**Comment by kuncevic** [comment]
yeah I saw that thing when I was debugging, also there is one more option is to use `renderer` https://angular.io/docs/js/latest/api/core/index/Renderer-class.html to manipulate with elements, but I ended up just by declaring an prop in my comp that I bind to the html prop I need to interact with.

**Comment by jelbourn** [comment]
This is working as expected. When using `@ViewChild` in this way, Angular will provide the directive instance.

**Comment by kuncevic** [comment]
@jelbourn why it is expected? 
>Angular will provide the directive instance

Some more details plz

**Comment by willshowell** [comment]
@kuncevic this should help

http://stackoverflow.com/a/39909203/4811678

**Comment by gouldina** [comment]
I also have this problem. I don't understand why you say this is OK - if it works with a button without the md-radio-button, surely it should work for one with it? How can I get around this problem?

**Comment by HunderlineK** [comment]
@gouldina Please refer to the link that @willshowell  posted above. Basically, just do
`
@ViewChild('nameForMaterialElement', {read: ElementRef}) private nameForMaterialElement: ElementRef;
`

**Comment by gouldina** [comment]
Thanks HunderlinK. I'll try that.

**Comment by DanielCaspers** [comment]
The solution suggested by @HunderlineK also applies to anyone trying to select a `mat-card`. I assume this applies to many other material components.

**Comment by chibibiscuit** [comment]
To add on to @Nikki1993's answer (which works absolutely awesome), Angular Material 6 already has an interface you can use to type it:

```
export interface HasElementRef {
    _elementRef: ElementRef;
}
```

`@ViewChild('sidenavContainer') private sidenavContainer: HasElementRef;`

**Comment by kennyalmendral** [comment]
Thanks @HunderlineK

**Comment by raj2033** [comment]
down to 209, and this problem still exists.

**Comment by kuncevic** [comment]
@raj2033 did you try any of solutions above?
