### ISSUE TITLE
[Tabs] md-tab-group scrolling/pagination coming everytime 

### ISSUE THREAD

**Issue by bhawin-bigstep** [angular/material2#3925]
#### Bug, feature request, or proposal:
I have a bug in my angukar/material , I am using md-tab-group to show 4 tabs which have icons as lables , Still angular material is showing paginator. also my tabs labels are coming with min-width=160px.
Can anyone please help me how to get rid of scroll and also limit the width of each tab

#### What is the expected behavior?
Tabs should not have paginator

#### What is the current behavior?
Paginator is coming

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
http://plnkr.co/edit/pp9NPbZnQfN7KyuypFPO

**Comment by arkhamvm** [comment]
I experience the same problem, and `md-no-pagination="true"` is not working.

**Comment by amcdnl** [comment]
Here is an updated working plunkr: http://plnkr.co/edit/5aB8xWm2gDQtAro33rAM?p=preview

Per the material spec, the tabs have a default min width assigned to them of 160. If you want to override this min width you can do this via css:

```
.mat-tab-label { min-width: auto !important; }
```

Does this answer your question?

**Comment by noah-fernandes** [comment]
Stop using Angular Material and start using CSS like real frontends.
