### ISSUE TITLE
Tooltip contents font size is too small

### ISSUE THREAD

**Issue by ahaan729** [angular/material2#3927]
#### Bug, feature request, or proposal:
Facing issue while changing the font size of tooltip contents

#### What is the expected behavior?
Want to increase the Font size of the tooltip contents

#### What is the current behavior?
the size is currently fixed to 10px in the tooltip.css file

#### What is the use-case or motivation for changing an existing behavior?
Better visual while reading

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4
Material 2 - beta-2
Windows 10
Chrome 58

**Comment by MihailoVasovic** [comment]
I solved this issue by putting .mat-tooltip in my root styles.sass file and then setting up font-size.
The key for this to work is setting !important after font-size.

**Comment by srix55** [comment]
I had to do as Mihailo said... put changes in the root styles.sass file. I wanted to override styles in component's sass file. No amount of specificity overrides .mat-tooltip. Tried every combination of !important & /deep/ etc. Nothing changes it at the component level. I don't have any problem with other md components. What's different about tooltip that it has to be changed only at the root level? Can it not be made to be overridden at the component level?

**Comment by willshowell** [comment]
@srix55 Component styles cannot affect overlay-based components since they are attached elsewhere in the DOM

**Comment by andrewseguin** [comment]
Unfortunately we won't be able to set a size to make everyone happy, but we are trying to follow the Material spec as our best effort. 

https://material.io/guidelines/components/tooltips.html#tooltips-tooltips-desktop

If you want to change the tooltip's styles, you can apply a custom class with the `mdTooltipClass` input and defining a style in your app's global styles.

**Comment by simeyla** [comment]
Here's the code for others looking to do this

In your global styles (NOT in the component):

```
.mat-tooltip.tooltip
{
    font-size: 13px;   // current default is 10px :-/
    color: yellow;
}
```
Then apply the `matTooltipClass` directive.

```
<span  matTooltip="Customer #{{ item.customerId }}"
                  matTooltipShowDelay="1000"
                  [matTooltipClass]="'tooltip'">

```
PS. I don't recommend changing color - this is just to demonstrate it is working, and that if you add `.mat-tooltip` then you don't need `!important`.

**Comment by mann-david** [comment]
Interestingly, both `/deep/` and` ::ng-deep` would make this *not work* if included.  Simply this in the global stylesheet is **all** you need:
```
.mat-tooltip {
  font-size: 1.5rem !important;
}
```
