### ISSUE TITLE
Theming mixins/variables massively duplicated in release output

### ISSUE THREAD

**Issue by willshowell** [angular/material2#3931]
#### Bug, feature request, or proposal:
Bug? Proposal?

#### What is the current behavior?
In the output [_theming.scss](https://github.com/angular/material2-builds/blob/master/_theming.scss), there is massive duplication of the palettes and mixins.

The 756 KB file can be brought down to ~82 KB by removing the duplication.

#### What is the use-case or motivation for changing an existing behavior?
I don't really know/understand how big of deal this is. I guess it slows down npm download times and takes up 600 KB+ more disk space than required.

Related to #3776

**Comment by M-a-c** [comment]
I wonder if there is a way to just import and export the themes form there, instead of using gulp to just copy the contents over.

**Comment by jelbourn** [comment]
Looks like an issue with the scss bundling tool we're using. I filed an issue there: https://github.com/SimplrJS/scss-bundle/issues/16
