### ISSUE TITLE
Card titles should support attribute selectors

### ISSUE THREAD

**Issue by goelinsights** [angular/material2#3932]
#### Bug, feature request, or proposal:
H1 tags and others arent present in HTML with current implementation.  Is there a way to make sure that indexing captures data that would normally be tied to h1 tags and things like this better? Discussed with @mmalerba 

#### What is the expected behavior?
Search engines can index h tags for search and SERPs

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by littleninja** [comment]
Is this asking to use h1 tags in the md-card-title component? Couldn't that be a problem with accessibility compliance and descending header hierarchy?

**Comment by goelinsights** [comment]
It's more a question of can we insert h tags anywhere.  Result may be something similar to moving to <h1 mdCardTitle> to follow the pattern that led to <input mdInput type="email"
		

		Get Outlook for iOS
	





On Thu, Apr 6, 2017 at 10:03 PM -0600, "Sarah" <notifications@github.com> wrote:












Is this asking to use h1 tags in the md-card-title component? Couldn't that be a problem with accessibility compliance and descending header hierarchy?

**Comment by goelinsights** [comment]
Question originated with serp impact of using md-card-title and md-card-subtitle vs h1 and h2 tags for things like search engine indexing or social sharing

**Comment by jelbourn** [comment]
I don't see any reason why we shouldn't support , e.g., `<h1 md-card-title>`.
