### ISSUE TITLE
MdCard and MdListItem use base color rather than text color

### ISSUE THREAD

**Issue by willshowell** [angular/material2#3936]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Default styling of text on a "light-theme" MdCard or MdListItem should be 87% black

#### What is the current behavior?
Text defaults to 100% black.

#### What are the steps to reproduce?
http://plnkr.co/edit/zkrjdBwt5wAe85FllmDe?p=preview

#### Is there anything else we should know?
Culprit for MdCard is [here](https://github.com/angular/material2/blob/master/src/lib/card/_card-theme.scss#L11). Culprit for MdListItem is [here](https://github.com/angular/material2/blob/master/src/lib/list/_list-theme.scss#L11)

**Comment by kyle-burke** [comment]
Hey @willshowell, I made a PR for this [here](https://github.com/angular/material2/pull/3952).
