### ISSUE TITLE
snackBar throws ObjectUnsubscribedError on dismiss 

### ISSUE THREAD

**Issue by bcravens** [angular/material2#3937]
#### Bug, feature request, or proposal:
bug

#### What is the current behavior?
when the snackBar is dismissed it throws an object unsubscribed error

#### What are the steps to reproduce?
I would provide a plunker but the example provided in the documentation is currently broken and also throws its own errors. 

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.4.4
material 2.0.0-beta.2

#### Is there anything else we should know?

this is how I'm calling snackBar 
```
 this.snackBar.open("message", null, {
     duration: 6000
});
```
it works fine but then throws the exception error about the observable it creates being unsubscribed.

**Comment by M-a-c** [comment]
https://plnkr.co/edit/DK5r5IGkpHVnYRg6Iacl?p=preview
I don't see the error on Angular 2.4.10v

**Comment by bcravens** [comment]
whats the best way update to the latest version?

**Comment by M-a-c** [comment]
https://docs.npmjs.com/cli/update
This should point you in the right direction.
I'm pretty sure you would want to make sure you have a ^ in front of all of your `@angular` dependencies then run npm update. (that might update some other packages too, so you might want to read up on the update npm update docs)

**Comment by bcravens** [comment]
Thank you

**Comment by jelbourn** [comment]
Seems to be working with the latest versions of both angular and material (https://material.angular.io/components/component/snack-bar). Feel free to open a new issue if you can still reproduce.
