### ISSUE TITLE
Material Snackbar Does Not Expand to Width of Viewport on Mobile Devices

### ISSUE THREAD

**Issue by mtpultz** [angular/material2#3939]
#### Bug, feature request, or proposal:
Bug (more like missing functionality)

#### What is the expected behavior?
On mobile devices according to material design spec the toast/snackbar should be the full width of the viewport.

#### What is the current behavior?
Toast/snackbar remains fixed width in the centered

#### What are the steps to reproduce?
This is missing functionality of the base MdSnackBar and can be reproduced by opening the MdSnackBar on a viewport that is considered a mobile device `this.snackBar.open(message, 'Close');`

#### What is the use-case or motivation for changing an existing behavior?
It isn't to material design spec.

#### Which versions of Angular, Material, OS, browsers are affected?
N/A

**Comment by josephperrott** [comment]
This is actually blocked by #1951, as the PR for this allows for determining the screen type by size.

**Comment by mtpultz** [comment]
Also, noticed that  `openFromComponent` doesn't open to the full width of the viewport on mobile using the pizza party docs example in an application since I only mentioned `open` in the initially reported issue.

**Comment by naveedahmed1** [comment]
Any update on this?
