### ISSUE TITLE
Firefox adds box-shadow behind required fields. 

### ISSUE THREAD

**Issue by davidgabrichidze** [angular/material2#394]
this css removes unwanted behaivor in FF:

:-moz-ui-invalid {
    box-shadow: none;
}

**Comment by jelbourn** [comment]
@davidgabrichidze Are you saying this is a problem with `md-input`?

**Comment by davidgabrichidze** [comment]
@jelbourn Yes, when md-input is required, it sets 'required' attribute on rendered input. FF has such "good" behavior, creates red shadow around input.

**Comment by robertmesserle** [comment]
Closed by dfe683bc3fdab80324738404c39fb7454fdcc6cc
