### ISSUE TITLE
SnackBar to be placed specifically in the DOM structure

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#3942]
#### Bug, feature request, or proposal:
I don't know if this is a bug, an existing feature or proposal

#### What is the expected behavior?
the ability to have the snackbar appear in any dom element you choose

#### What is the current behavior?
shows up on the bottom

#### What are the steps to reproduce?
activate the snackbar
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
for phones or whatever the bottom may be fine but for many situations it is not.  More control is needed here. 

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2 / material 2.00-beta.2

#### Is there anything else we should know?
don't think so

**Comment by donroyco** [comment]
This is (sort of) mentioned already in #3577

**Comment by xtianus79** [comment]
@donroyco this is mentioned but i guess I am asking is there any way to adjust the setting?

**Comment by jelbourn** [comment]
#3577 captures _positioning_ the snackbar on the screen, which we plan to address. As far as controlling where it is in the DOM, though, we have no plans to change that.
