### ISSUE TITLE
Material Dialog is opened in the same window instead of Modal

### ISSUE THREAD

**Issue by vibingopal** [angular/material2#3943]
#### Bug, feature request, or proposal:
I have upgraded my material dependency from alpha to beta version and when i perform the user operation to open a dialog, it is getting showed on the same screen instead of Modal.

#### What is the expected behavior?
Request should open new modal

#### What is the current behavior?
Currently it is opening in same window instead of modal

Below is my typescript code when opening a modal.
 let config = new MdDialogConfig();
  config.viewContainerRef = this.viewContainerRef;
   this.dialogRef = this.dialog.open(ComponentA, config);
   this.dialogRef.componentInstance.ObjDetails = rowObj;

Here Row Obj is the result from the clicked row which opens the new modal 

```

**Comment by M-a-c** [comment]
```ts
let config = new MdDialogConfig();
config.viewContainerRef = this.viewContainerRef;
this.dialogRef = this.dialog.open(ComponentA, config);
this.dialogRef.componentInstance.ObjDetails = rowObj;
```

**Comment by vibingopal** [comment]
Hi Mac,

I tried with your option and still the dialoge is opening in the same window instead of as modal.

**Comment by M-a-c** [comment]
:/ maybe it is a bug. can you create a plunkr?

**Comment by TobiasVdb** [comment]
Same issue here ! I'll try to replicate in plunker. 
Running on : "@angular/material": "^2.0.0-beta.2",

**Comment by jelbourn** [comment]
Sounds like you're missing a theme, but there's not really enough information to be sure. Feel free to open a new issue with more information or a reproduction.

**Comment by TobiasVdb** [comment]
That was for me indeed the problem !  
Added <link href="node_modules/@angular/material/core/theming/prebuilt/indigo-pink.css" rel="stylesheet">  to index.html and now it works !
