### ISSUE TITLE
md-select has few problems

### ISSUE THREAD

**Issue by gayan1991** [angular/material2#3945]
I am using angular/material 2.0.0-beta.2. However, md-select does not have a **required** field. Another issue is there is no way set a **default value** such as 'select option'.

Anything that I could use?

**Comment by fxck** [comment]
Hey, github issues are for bugs and feature requests. Gitter or stackoverflow are better suited for support requests.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
