### ISSUE TITLE
md-icon-button hover has no change

### ISSUE THREAD

**Issue by Kyderman** [angular/material2#3946]
Bug

#### What is the expected behavior?
When hovering an md-icon-button, there should be a circular background around the icon

#### What is the current behavior?
There is no background change

#### Which versions of Angular, Material, OS, browsers are affected?
Im using master, on Angular 4

**Comment by ocarreterom** [comment]
Icon buttons don't have `hover` state: https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons

**Comment by Kyderman** [comment]
weird, they use to and it seemed a bit more user friendly.

**Comment by willshowell** [comment]
It was removed in #3208, presumably to match the spec.

**Comment by jelbourn** [comment]
It's is indeed intentional- the spec shows no hover behavior for icon buttons.

**Comment by Levent0z** [comment]
That's a shame, it looked really nice.

**Comment by hughanderson4** [comment]
Google apps like Gmail all use hover state for Icon button lol

https://apps.google.com/u/1/user/hub

**Comment by Mubramaj** [comment]
You can apply a global style to your application to hover all the mat-icon button.
I did it using Angular theming. 

```
$background: map-get($my-theme, background);

// add hover for mat-icon butttons
.mat-icon-button:hover {
   background-color: mat-color($background, hover);
 }
```
