### ISSUE TITLE
2 circles for md-radio-button

### ISSUE THREAD

**Issue by kviktorman** [angular/material2#3947]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
One circle for the radio button .

#### What is the current behavior?
Radio button has 2 circles. One is in the "mat-radio-container" div and the other is which is with the id "md-radio-1-input" (blue line on the screen) . 

I'm not sure if its really a bug or not, maybe I just use it in a wrong way. I tried to check it on the material.angular.io, but the example page was not loading here i mean the ("Material Sample App")

Under material.angular.io "components" menu and on github under "/src/examples/" and /src/demo-app/ I have found some examples and i tried them and got the next result: 

![selection_006](https://cloud.githubusercontent.com/assets/19187117/24798267/5c7a6192-1b95-11e7-90a6-10f6774ec38c.png)

#### What are the steps to reproduce?

1. create new project with angular-cli
2. add animations, hammerjs, material module (github version, because the npm repository version is still not having the unmeet peer dependency for angular ^4.0.0 versions )
3. import added modules to module.ts 

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MaterialModule } from '@angular/material';

@NgModule({
imports: [    
    BrowserAnimationsModule,
    MaterialModule,
     ....
]})
4. added this to the app.component.ts
```
<md-radio-group>
 <md-radio-button value="1">Option 1</md-radio-button>
 <md-radio-button value="2">Option 2</md-radio-button>
</md-radio-group>"
```

Also I tried to import the next modules into the component, hoping for one circle but result is the same. _import { MaterialModule, MdRadioButton, MdRadioModule } from '@angular/material';_

My package.json settings are the following:
  "dependencies": {
    "@angular/animations": "^4.0.1",
    "@angular/common": "^4.0.1",
    "@angular/compiler": "^4.0.1",
    "@angular/core": "^4.0.1",
    "@angular/forms": "^4.0.1",
    "@angular/http": "^4.0.1",
    "@angular/material": "git+https://github.com/angular/material2-builds.git",
    "@angular/platform-browser": "^4.0.1",
    "@angular/platform-browser-dynamic": "^4.0.1",
    "@angular/router": "^4.0.1",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.3.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }

#### What is the use-case or motivation for changing an existing behavior?
I would be happy to start using your awesome material design in our project. 
Thanks in advance for your replay.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular version: 4.0.1
Material version: 2.0.0-beta.2 (github version)
OS: Ubuntu 16.04 Xenial
Browser: Firfox 52.0.2 (64-bit)

#### Is there anything else we should know?
I guess nope, but if you have question I will try to answer.

**Comment by ValeryVS** [comment]
You probably have some custom css on input tag with "id"="md-radio-1-input".
For example, we had `.my-block input { position: relative }`
This rule rewrites `position: absolute` from `.cdk-visually-hidden`

**Comment by ValeryVS** [comment]
Probably, class `.cdk-visually-hidden` must apply rules with `!important`.

**Comment by kviktorman** [comment]
I created a new project and did not add any custom css. So with a fresh project created by angular-cli gives me this issue.

**Comment by willshowell** [comment]
@kviktorman Could you replicate in a plunker? [This template](http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview) should work.

**Comment by kviktorman** [comment]
I added the example into your app.component.html and also added a second component. In both cases it works on plnkr.

**Comment by kviktorman** [comment]
Which means I'm not able to reproduce it there.

**Comment by willshowell** [comment]
Can you publish the repo of the fresh project that's giving you the issue?

**Comment by kviktorman** [comment]
It toke me some time, but here is the repo:
https://github.com/kviktorman/not-working-radio

This commit which holds all the changes which i made and what is not working:
https://github.com/kviktorman/not-working-radio/commit/67235f0cb7b5081abce528e64326efa6340bada4

![selection_007](https://cloud.githubusercontent.com/assets/19187117/24804019/5f4368f2-1bad-11e7-820a-eca36ed361c5.png)

**Comment by willshowell** [comment]
@kviktorman it looks like you're not using a theme. As you can see from the [README](https://github.com/angular/material2/blob/master/guides/getting-started.md#step-4-include-theming), theming is *required* for the components to work properly. 

The readme/docs are still in sync with beta 2, therefore lagging behind the latest master build. They'll likely sync up in the next beta release. So instead of adding what the README says, add this to your index.html:

`<link href="node_modules/@angular/material/prebuilt/indigo-pink.css" rel="stylesheet">`

**Comment by kviktorman** [comment]
@willshowell thanks a lot its working now !!!!!!! 
It looks like it was my mistake. 
I thought and searched a lot to find whats the solution or what i do wrong.
You guys built a great thing, thank you for it !!!!

**Comment by willshowell** [comment]
Lol I'm not on the team, but I'm sure they appreciate your gratitude. Be sure to close this issue!

**Comment by deepu149** [comment]
I've same issue.. including link is not working for me.
