### ISSUE TITLE
Missing files from plnkr example (Snack-bar)

### ISSUE THREAD

**Issue by gtzinos** [angular/material2#3948]
Steps to reproduce:

1) https://material.angular.io/components/component/snack-bar

2) Click on examples

3) Click on Edit in plnkr

https://plnkr.co/edit/?p=preview

Some files are missing and the example doesn't work.

**Comment by xtianus79** [comment]
I setup this plunkr which has everything working 

http://plnkr.co/edit/tQfo0NgiK0XcmRoIVWhr?p=preview
