### ISSUE TITLE
Really reactive forms support?

### ISSUE THREAD

**Issue by montella1507** [angular/material2#3949]
https://material.angular.io/components/component/checkbox

"<md-checkbox> is compatible with @angular/forms and supports both FormsModule and ReactiveFormsModule." i think, there is information abour ReactiveForms support in every document, but there is no support for reactive forms actually ? 

No FormControl, no FormGroup support etc..

**Comment by xtianus79** [comment]
@montella1507 what would you like to know.  I have done a lot of work with forms

**Comment by montella1507** [comment]
@xtianus79  i think, controls like md-checkbox should implement  CheckboxValueAccessor and NOT only ValueControlAccessor to works correctly with reactive forms,.
