### ISSUE TITLE
release: some components have a dependency to angular2 beta 8.

### ISSUE THREAD

**Issue by DevVersion** [angular/material2#395]
It seems like, a few scope components still have a dependency to an older version of angular. (Without scoping packages etc.)

![image](https://cloud.githubusercontent.com/assets/4987015/15045830/0078364c-12dd-11e6-94e7-7cf541eac893.png)

Update: Seems like it's only `card` and `checkbox`
![image](https://cloud.githubusercontent.com/assets/4987015/15046542/9bfeb584-12e0-11e6-86e0-875e515f46f7.png)

**Comment by jonathan-casarrubias** [comment]
+1

**Comment by k3nsei** [comment]
+1

**Comment by donjae** [comment]
+1

**Comment by Pixcell** [comment]
+1

**Comment by jelbourn** [comment]
Yep, I missed removing it from those `package.json` files when I did the last release. You can ignore the warnings until the next alpha release.

**Comment by webmutation** [comment]
Well I am glad i read this before creating a new issue for the checkbox :)
I will wait a couple of weeks until the angular team gets some rest from ng-conf and google IO and makes some releases that are not sleep deprived :wink:

**Comment by ghudeihed** [comment]
@jelbourn when is the next alpha release going to happen

**Comment by jelbourn** [comment]
The next milestone should always have a date associated with it. 
https://github.com/angular/material2/milestones

**Comment by jelbourn** [comment]
Should be fixed in the alpha.5 that was released today. 
(we'll be setting a target date for alpha.6 in a couple of days)

**Comment by mikeumus** [comment]
Great work guys! Thank you.
