### ISSUE TITLE
mdautocomplete is giving an ng-template / Custom_Elements_Schema error in the latest master branch

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#3954]
#### Bug, feature request, or proposal:
Bug - with latest master branch of Material

#### What is the expected behavior?
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-template> <div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()"): MdAutocomplete@0:0 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angula…, _nativeError: ZoneAwareError, __zone_symbol__stack: "Error: Template parse errors:↵'ng-template' is not…st:8080/polyfills.js:2460:1), <anonymous>:529:35)",

#### What is the current behavior?

I am getting this error when using the latest master branch

#### What are the steps to reproduce?

install latest master branch

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.8. Material - latest-master

#### Is there anything else we should know?
nope

**Comment by willshowell** [comment]
@xtianus79 I don't think the latest master branch is compatible with Angular 2.4.8. `<ng-template>` is an angular 4 change

**Comment by xtianus79** [comment]
@willshowell So, this is a problem then.... There is a bug in material's mdselect tabindex that is fixed in the documentations but it isn't building to the correct javascript file upon deployment.  So I am assumed the bug was fixed via the master branch. 

I installed that and here is what I found in the new build... which seems correct: 

    this._tabIndex = parseInt(tabIndex) || 0;  

However, since it was updated in the master branch I pulled that down and now found this error.  

So a problem that start with mdselect is now wanting me to get a change which isn't going to be compatible with my build.... :-( 

What is the strategy going to be for using angular 2 with material (2) and then what material is only compatible with Angular 4 going forward???

**Comment by jelbourn** [comment]
The the latest changelog for more information: https://github.com/angular/material2/blob/master/CHANGELOG.md

**Comment by ietuday** [comment]
I am getting this error in console :
Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-template> <div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()"): MdAutocomplete@0:0 ; Zone: <root> ; Task: Promise.then ; Value: 

Please Help 

Thanks in Advance

**Comment by ietuday** [comment]
I am using 
https://github.com/angular/material2/tree/master/src/demo-app/autocomplete
code to build autocomplete demo.

**Comment by ietuday** [comment]
Yeah, After upgrading from angular 2 to 4.

It's Working Fine...

Thanks
