### ISSUE TITLE
mdSelect tabindex defautls to 0 | seems it doesn't build correctly in 2.0.0-beta.2 in order for tabindex to work in production

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#3956]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
tabindex applied on md-select element should not default to 0

#### What is the current behavior?
md-select tabindex defaults to 0

#### What are the steps to reproduce?
use md-select and the tab-index is set to 0

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://plnkr.co/edit/tQfo0NgiK0XcmRoIVWhr?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.4.8 and material 2.0.0-beta.2

#### Is there anything else we should know?
Yes, 

This seems to further repercussions in how you guys are handling versioning of material along with the parent angular application.  I have tried to resolve this by installing the master branch but that apparently that isn't compatible with version angular 2.

**Comment by jelbourn** [comment]
This is the intended behavior. The `md-select` should be a tab stop by default.

**Comment by xtianus79** [comment]
@jelbourn a tab stop?  What do you mean.  I am speaking of a form that has multiple selections that have to be tabbed through.  What does tab stop mean?

**Comment by jelbourn** [comment]
@xtianus79 check out https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_selection_follows_focus, which is pretty informative on the matter.

**Comment by xtianus79** [comment]
@jelbourn thanks for the reply.  I have a question because perhaps I am confused.  Does selection following focus mean:  The user tabs to the drop down selection area and then if the user tabs again they will be tabbing into the selections of the said dropdown?  

If that is the definition than I am saying I don't want to go into the selection dropdown but rather the next tabbed indicator.  

So If I have 6 fields... where the first 3 are inputs and the 4th is a selection dropdown... I just want to be able to tab along and hit the area of each input and selection.  When coming to the 4th selection dropdown I just want to be on the box of the input and then manually choose something if I want or simply tab over to 5 and 6.  

Am I thinking of this wrong?

**Comment by jelbourn** [comment]
The entire select is just one tab stop (not the panel).

**Comment by xtianus79** [comment]
@jelbourn but you can't put a tab order to it... This is the issue
