### ISSUE TITLE
Rename version 2.0.0-beta.3 to 4.0.0-beta.1

### ISSUE THREAD

**Issue by fireyoshiqc** [angular/material2#3959]
#### Bug, feature request, or proposal:
Feature request / bug

#### What is the expected behavior?
Angular Material2 beta 3 has a lot of breaking changes. It should be denoted by a major version number, the same as Angular version 4 that it depends on.

#### What is the current behavior?
Having ^ or ~ in your package.json in front of the angular material package makes it update to beta 3 on an npm install, breaking Angular functionality if the core angular packages also use the same install modifier (^ or ~), yet are on 2.X.X versions (not Angular 4). It majoritarily breaks animation related features, since the package structure for animations has been heavily modified in Angular 4 (and Material2 beta 3 uses that new structure).

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

1. Have a ^ or ~ in front of both the angular material package (version 2.0.0-beta.2 or lower) and the core angular packages (core, http, etc., version 2.X.X).
2. Do a normal npm install.
3. Observe breaking changes since there are missing dependencies that are Angular 4 related.

#### What is the use-case or motivation for changing an existing behavior?
Currently working on a school project that uses Angular and Angular Material, and it broke our project after we submitted our project, but before evaluation. The project didn't work because an npm install was performed before evaluation.

I suppose other people might fall into the same type of issues with their projects.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.X.X, and Angular Material 2.0.0-beta.3. All browsers that support both of those.

#### Is there anything else we should know?
I wrote this on mobile, I'll format it better when I have more time.

**Comment by jelbourn** [comment]
Beta by itself indicates that the library is still undergoing stabilization and each version may have breaking changes.

**Comment by fireyoshiqc** [comment]
Agreed. It just kinda messed my day up without a warning ._.
My bad.
