### ISSUE TITLE
Why is all the SCSS missing form the node_modules?

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#3969]
#### Bug, feature request, or proposal:
Hello! How are you?
I am building themes, I was using my own themes, plus the prebuilt themes.
There used to have the whole SCSS, now they all missing and only CSS. I cannot use it now. I need a few overrides and is not working with CSS.
Please keep the SCSS. I have to use it with webpack anyway, why is it so slim now?

#### What is the expected behavior?
Keep SCSS.

#### What is the current behavior?
All missing, only a few variables are there, plus the pre-built SCSS is missing as well.

#### What are the steps to reproduce?
node_modeules/@angular/material/ all SCSS missing. :(

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
The be built multiple themes in one SCSS with CSS namespaces like (.cory-mat-pink - includes the prebuild SCSS, css cant do it)

#### Which versions of Angular, Material, OS, browsers are affected?
All.

#### Is there anything else we should know?
Please allow to use SCSS.

**Comment by fxck** [comment]
Look at changelog.

**Comment by patrikx3** [comment]
For example ```~angular/material/prebuilt-themes/pink-bluegrey```, it was giving me the $primary colors, but now since it is css, i cannot use anymore.

**Comment by patrikx3** [comment]
ok check it out.

**Comment by patrikx3** [comment]
Ok, but how can i use the prebuilt themes with SCSS? WHy is missing the SCSS?

**Comment by patrikx3** [comment]
Where are the SCSS? Please HELP!! :(

**Comment by naturalfreak** [comment]
Same problem, any fix ?

**Comment by patrikx3** [comment]
please CSS is not enough for a theme, we are creating custom lots of settings, CSS is not enough today,  in 2017 we need SCSS on the front end and now I built 6 themes, 2 my own, 4 prebuilt and the 4 prebuilt is not usable, i have to delete them. :(

**Comment by ciesielskico** [comment]
Have you read the changelog? It says at the top that they moved the imports to `@import '~@angular/material/theming';`

**Comment by patrikx3** [comment]
hi! ciao!

yes, i already use it, the theming variables.

just **trying to ask** if the **prebuilt SCSS** so it will not work anymore? Before there were 4 prebuilt, which i used, now i cannot.
now the prebuilt is CSS. instead of scss. whith css you cannot create css namesapces, so now i have to rebuild by hand.

i guess the themes will be missing for the future.

**Comment by fxck** [comment]
https://github.com/angular/material2/tree/master/src/lib/core/theming/prebuilt

**Comment by patrikx3** [comment]
yeah i found it, i added in manually. i got it, the npm will be just the requried files, the source is removed now to remvoe size etc.

i got it, chanks so much! ciao!
