### ISSUE TITLE
_all-theme.scss not available on 2.0.0-beta.3

### ISSUE THREAD

**Issue by looorent** [angular/material2#3972]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

According to the  [Theming documentation](https://material.angular.io/guide/theming), importing the SCSS file `~@angular/material/core/theming/all-theme` should be allowed.

#### What is the current behavior?

`File to import not found or unreadable: ~@angular/material/core/theming/all-theme`

#### What are the steps to reproduce?

* Use `@angular/material` in version `2.0.0-beta.3` in your package.json
* Import `~@angular/material/core/theming/all-theme` in your root `styles.scss`
* Compile using webpack

#### What is the use-case or motivation for changing an existing behavior?

N/A

#### Which versions of Angular, Material, OS, browsers are affected?

* angular: `4.0.1`
* material: `2.0.0-beta.3`
* OS: macOS 10.12.3

#### Is there anything else we should know?

* The root folder of `@angular/material` contains `_theming.scss`, should it be used instead of `_all-theme.scss`?
* This worked before using dependency `git+https://github.com/angular/material2-builds.git#2.0.0-beta.2-fb565c0`
* If applicable, please update the corresponding documentation.

**Comment by Ploppy3** [comment]
Change your import to `@import '~@angular/material/theming';`

**Comment by looorent** [comment]
Thank you.
By the way, if this is the new 'official' way to proceed, this is going to break several libraries such as [ng2-md-datatable](https://github.com/fredguile/ng2-md-datatable).
