### ISSUE TITLE
Need documentation for Custom Module

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#3973]
According to the changelog of Beta 3 it is recommended to create our own Material module to reduce app size.

But I can't find any documentation on how to create my own Material module.

**Comment by fxck** [comment]
https://angular.io/docs/ts/latest/guide/ngmodule.html

**Comment by Ploppy3** [comment]
I know how to create an Angular module. What I don't know is what we are supposed to import from @angular/material, do you ?

**Comment by fxck** [comment]
You are supposed to import whatever modules you are using in your app, ie. `MdButtonModule`. Either way, this is neither a bug report or feature request, support requests are better suited for gitter or stackoverflow.

**Comment by Ploppy3** [comment]
This is what I do:
```
import { MdButtonModule } from "@angular/material";

@NgModule({
  imports: [
    MdButtonModule
  ],
})
export class MyMaterialModule { }
```

And in my app.module.ts I import `MyMaterialModule` and everything breaks.
Am I missing something obvious ?

**Comment by fxck** [comment]
Are you sure you "know how to create an angular module" or that you actually read the guide I pointed you to? This section in particular https://angular.io/docs/ts/latest/guide/ngmodule.html#!#shared-module ?

**Comment by Ploppy3** [comment]
Why not point out my mistake? Import instead of Export...

**Comment by mackelito** [comment]
All working! All Good!
Stay safe, happy and helpful!

**Comment by jelbourn** [comment]
Updated the getting started guide with an example.

**Comment by candidosales** [comment]
```javascript
import { NgModule }      from '@angular/core';
import {
  MdButtonModule,
  MdSnackBarModule,
  MdCardModule,
  MdInputModule,
  MdCheckboxModule,
  MdIconModule,
  MdSidenavModule,
  MdSelectModule,
  MdToolbarModule,
  MdListModule,
  MdProgressBarModule,
  MdProgressSpinnerModule } from '@angular/material';

@NgModule({
    imports: [
      MdButtonModule,
      MdSnackBarModule,
      MdCardModule,
      MdInputModule,
      MdCheckboxModule,
      MdIconModule,
      MdSidenavModule,
      MdSelectModule,
      MdToolbarModule,
      MdListModule,
      MdProgressBarModule,
      MdProgressSpinnerModule ],
    exports: [
      MdButtonModule,
      MdSnackBarModule,
      MdCardModule,
      MdInputModule,
      MdCheckboxModule,
      MdIconModule,
      MdSidenavModule,
      MdSelectModule,
      MdToolbarModule,
      MdListModule,
      MdProgressBarModule,
      MdProgressSpinnerModule ]
})
export class CustomMaterialModule {  }

```

My example :)

**Comment by attilacsanyi** [comment]
AFAIK @candidosales the `imports` section in your `CustomMaterialModule` is not necessary needed as `CustomMaterialModule` is just for exporting required material components for your app and help to reduce your bundle during AOT ;-)

**Comment by alexfung888** [comment]
It is a bit annoying to repeat the list of modules in the ES5 import and the export annotation.

Does it make any difference to import hammer here? Seems I'll need to import hammer in appmodule again, since I can't export it from here.
