### ISSUE TITLE
Component Theming Failed after update to beta.3

### ISSUE THREAD

**Issue by scandinave** [angular/material2#3975]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Have access to $theme variable in my custom _theme.scss file

#### What is the current behavior?

```
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module build failed:
@include fn-datatable-theme($theme);
                           ^
      Undefined variable: "$theme".
      in /home/scandinave/Development/Javascript/CDAD/src/_theme.scss (line 9, column 29)
 @ ./src/styles.scss 4:14-195
```

#### What are the steps to reproduce?

Make a mixin 

```
@debug "Loading datatabble theme mixin";
// Import all the tools needed to customize the theme and extract parts of it
@import '~@angular/material/theming';

@mixin fn-datatable-theme($theme) {
    $background: map-get($theme, background);

    fn-datatable {
        table tr td {
            border-bottom: 1px solid md-color($background, status-bar);
        }
    }
    
}
```

Import it into the theme.scss file
```

@charset "UTF-8";  
@import '~@angular/material/prebuilt-themes/indigo-pink.css';

@import './app/shared/components/fn-datatable/fn-datatable.theme';

@include fn-datatable-theme($theme);
```

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.1, Material 1.0.0-beta.3

#### Is there anything else we should know?
I don't understand how changing theme file from scss to css can let me access $theme variable. How I supposed to access it now?

**Comment by JurrianFahner** [comment]
The location of the themes is changed in the latest version. 

For instance to import the css file in your own css file, the link changed from `@import '~@angular/material/core/theming/prebuilt/deeppurple-amber.css';` to `@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';`

You can find the latest version of the guides in this repo. The changes are not reflected in the website https://material.angular.io. 

Can anyone of the team update the guides on the website with the guides in this repo?

**Comment by jelbourn** [comment]
The `$theme` variable is something you create in your application. The pre-built theme files were never intended to be consumed as *scss* files, only as the output css files. 

You can see one of the definitions of [a pre-built theme](https://github.com/angular/material2/blob/master/src/lib/core/theming/prebuilt/indigo-pink.scss) for an example of what it looks like to define your own theme (except for the import).

**Comment by myrddraall** [comment]
@jelbourn then the [documentation](https://github.com/angular/material2/blob/master/guides/theming-your-components.md) is incorrect.

```scss
// Import a pre-built theme
@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
// Import your custom input theme file so you can call the custom-input-theme function
@import 'app/candy-carousel/candy-carousel-theme.scss';

// Using the $theme variable from the pre-built theme you can call the theming function
@include candy-carousel-theme($theme);

```

**Comment by e11en** [comment]
+1

**Comment by naktinis** [comment]
@jelbourn I think @myrddraall is right, the docs must be incorrect then. Should I file a separate issue for it?
