### ISSUE TITLE
Unmet peer @angular/core@4.0.1

### ISSUE THREAD

**Issue by Cogitaria** [angular/material2#3976]
#### Bug, feature request, or proposal:

The @angular/material -beta.3 package depends on an Angular 4 patch release: 4.0.1
 
#### What is the expected behavior?

That it installs on 4.0.0 since we are using that version of Angular and will not be upgrading every patch release on a continuous basis -- we will update periodically. 

#### What are the steps to reproduce?

`ng new foo` and `npm install --save @angular/material` as a test. Run an `ng build` in foo project root and you will get UNMET PEER errors. 
 
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by crisbeto** [comment]
This is due to the CLI creating a project with Angular 2.4 by default. Material `beta.3` requires at least Angular 4.0.
