### ISSUE TITLE
md-input - inner textbox remains short (mat-input-wrapper)

### ISSUE THREAD

**Issue by denghauser** [angular/material2#3978]
**Actual Behavior**:
 -  `I use the md-input to display a wide text-input box. But the inner part of the area remains short.
 -  E.G: The md-input-container is 900px, but the mat-input-wrapper remains at 237px. I figured out that if I set the mat-input-wrapper to width:100% all works well. But unfortunately the stylesheet is ignored during rendering.

**Angular Versions**: *
 -  `Angular 4.0.1`
 -  `Material 2.0.0-beta3`

**Additional Information**:
 -  `Browser Type: any (Firefox, Chrome, Edge ..)`
 -  `OS: Win 10`
 
----

**Comment by mmalerba** [comment]
It seems to work fine, you my have other styles interfering: http://plnkr.co/edit/F9eLshoeQKXuLlfZ6KJh?p=preview

**Comment by denghauser** [comment]
I figured it out. If I add the style "display: flex;" to your plunkr md-input-container element, then the same thing happens, Is the material design not thought to work together with flex layout techniques? Should I avoid flex?

**Comment by mmalerba** [comment]
I'm not sure why you would need to add `display: flex` to the container. If you were trying to the inputs to stretch to take up their whole row you may have meant to put it on the parent element like this: http://plnkr.co/edit/TJMR5li2pub1q3Up5WYb?p=preview

**Comment by denghauser** [comment]
Thanks a lot for your help, I figured out that the flex on the container does not make a lot of sense. I found a solution now without the flex on the container.

**Comment by mamms** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by mamms** [comment]
> [`__`](

- 

- [ ] 1. url
https://guides.github.com/features/mastering-markdown/
https://guides.github.com/features/mastering-markdown
https://guides.github.com/features/mastering-markdown//
)
