### ISSUE TITLE
CDN indigo pink css not fiybd

### ISSUE THREAD

**Issue by aravindfz** [angular/material2#3980]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Css file reference should be added to the index.html

#### What is the current behavior?
404 not found 

#### What are the steps to reproduce?
Refernece 
`<link href="https://unpkg.com/@angular/material/core/theming/prebuilt/indigo-pink.css" rel="stylesheet">`
Plunker template: https://plnkr.co/edit/?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Use the components

#### Which versions of Angular, Material, OS, browsers are affected?
Angular2 material 2

#### Is there anything else we should know?
No

**Comment by fireyoshiqc** [comment]
File imports for theming have changed, as described in the changelog : 
https://github.com/angular/material2/blob/master/CHANGELOG.md#package-structure

Change your href to :
`<link href="https://unpkg.com/@angular/material/prebuilt-themes/indigo-pink.css" rel="stylesheet">`

**Comment by bageren** [comment]
I'm getting the same error. I followed the guide from https://material.angular.io/guide/getting-started.

I added this to my index.html:

<link href="../node_modules/@angular/material/prebuilt-themes/indigo-pink.css" rel="stylesheet">

I can't find the stylesheet, and it is indeed at this location. How do I solve this?

**Comment by brunoviek** [comment]
Same problem.
Followed the tutorial 3 times and nothing!
Seems to be a bug, I have to problem installing materializecss or anything else!

**Comment by willshowell** [comment]
@brunoviek Are you using the cli? If so, try adding it to the `styles` section of your `.angular-cli.json` file and see if that works.

Related https://github.com/angular/material2/issues/5509

**Comment by brunoviek** [comment]
it worked in styles.css
and in .angular-cli.json

But if I refer in index.html I still get 404.
You know why?

But thanks anyway!

**Comment by brunoviek** [comment]
It worked in styles.css and in .angular-cli.json
Thank you!
