### ISSUE TITLE
Update input to match April 2017 Material Design spec changes

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#3984]
https://material.io/guidelines/components/text-fields.html

**Comment by kyleledbetter** [comment]
@jelbourn I keep seeing this issue referred to as `See #3984` or `Dup #3984`, etc, but there's no info here except the link :)

I'm interested in `Text field boxes` specifically. Any info that you can share? I don't see it planned or mentioned here https://github.com/angular/material2#in-progress-planned-and-non-planned-features

Ref:
![image](https://user-images.githubusercontent.com/867883/29934544-784c1312-8e30-11e7-83aa-7f0d4edcdc65.png)

**Comment by nkwood** [comment]
I'm also curious if the intention is to include support for the solo field variation discussed in the spec at https://material.io/guidelines/components/text-fields.html#text-fields-field-variations as well as the text input field nested in an app bar (which appears to utilize the text field box style mentioned above). 

For example:
<img width="339" alt="screen shot 2017-08-31 at 12 32 50 pm" src="https://user-images.githubusercontent.com/6249779/29936735-e7e11b88-8e48-11e7-96f5-64cf797f6237.png">
... and ...
<img width="307" alt="screen shot 2017-08-31 at 12 33 28 pm" src="https://user-images.githubusercontent.com/6249779/29936758-f625e53e-8e48-11e7-8b17-f5188684e34d.png">

**Comment by TheRedD0t** [comment]
Maybe it's useful to divide this topic into several small issues in order to better describe and evaluate the tasks, and use this as a root issue for overall tracking of the progress.
I guess this would also prevent of duplicates because you doesn't find this issue if you search e.g. for "input dense mode" or "input hover".

**Comment by PowerKiKi** [comment]
@mmalerba you self-assigned this issue back in April. Does it mean you are working on this ? or should it be un-assigned so somebody else can pick it up ?

**Comment by fxck** [comment]
Was just checking the specs yesterday, I'm pleasantly surprised by the way textareas are handled now (https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B5ZSepuCX1xOYXNnRjJKVU53Skk/area-states.png), is there any milestone for this?

**Comment by gangsthub** [comment]
I've received some suggestions from my contractor saying that the input fields should be "more _spottable_". Seeing the spec, I've found some inspiration there. I'm sure that you will align soon. Until then, I will have to tweak the CSS a little bit on my own. Monkey-patching, tho.

https://material.io/guidelines/components/text-fields.html#text-fields-text-field-boxes

**Comment by jpleclerc** [comment]
Is this issue being worked on? Material2 is currently out of specs. "Our goal is to build a set of high-quality UI components built with Angular and TypeScript, following the Material Design spec". Sorry for being so entitled but the goal is not met.

**Comment by jelbourn** [comment]
The major 2018 spec revision is a major change; updates for it will be a part of v7

**Comment by PowerKiKi** [comment]
Then this issue should probably be assigned to the existing 7.0 milestone.

**Comment by jelbourn** [comment]
Closing this issue since the input variants have been available for a while now.

**Comment by PowerKiKi** [comment]
For reference this feature is documented there: https://material.angular.io/components/form-field/overview#form-field-appearance-variants
