### ISSUE TITLE
gulp task 'library:build:esm' build failed on Windows 10 64bit and NodeJS 6.9.5

### ISSUE THREAD

**Issue by speedmax123** [angular/material2#3993]
#### Bug, feature request, or proposal:

Bug: gulp task 'library:build:esm' build failed on Windows 10 64bit and NodeJS 6.9.5

#### What is the expected behavior?

build success

#### What is the current behavior?

when trigger the gulp serve:devapp, after invoking task 'library:build:esm'
it shows:

 Error: Error at D:/Workspaces/Frontend/material2/src/lib/index.ts:7:53: Cannot find module '.corea11ylive-announcer'.
Error at D:/Workspaces/Frontend/material2/src/lib/index.ts:8:66: Cannot find module '.corecoordinationnique-selection-dispatcher'.
Error at D:/Workspaces/Frontend/material2/src/lib/index.ts:8:88: Hexadecimal digit expected.
Error at D:/Workspaces/Frontend/material2/src/lib/index.ts:9:89: Cannot find module '.coreoverlayoverlay-container'.
Error at D:/Workspaces/Frontend/material2/src/lib/index.ts:10:44: Cannot find module '.coreoverlaypositionoverlay-position-builder'.
Error at D:/Workspaces/Frontend/material2/src/lib/index.ts:11:103: Cannot find module '.coreoverlayposition
                                                                                                           iewport-ruler'.
Error at D:/Workspaces/Frontend/material2/src/lib/index.ts:12:89: Cannot find module '.coreoverlayscrollscroll-dispatcher'.
Error at D:/Workspaces/Frontend/material2/src/lib/index.ts:13:32: Cannot find module '.coreoverlayscrollscrollable'.
ipple-renderer'.spaces/Frontend/material2/src/lib/index.ts:14:36: Cannot find module '.core
Error at D:/Workspaces/Frontend/material2/src/lib/index.ts:15:154: Cannot find module '.grid-listgrid-tile'.

#### What are the steps to reproduce?

On windows 10 64bit

1. clone the latest master branch of master2
2. npm install
3. gulp serve:devapp

the error will show up

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by jelbourn** [comment]
I believe this is due to https://github.com/angular/angular/issues/15403; follow that issue for further updates.

**Comment by nehaagrawal** [comment]
@jelbourn - we are still getting this issue. Is it resolved?
