### ISSUE TITLE
UNMET PEER DEPENDENCY with angular 4.0.1

### ISSUE THREAD

**Issue by JyotirmoyGoswami** [angular/material2#3994]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
No UNMET PEER DEPENDENCY

#### What is the current behavior?
UNMET PEER DEPENDENCY

#### What are the steps to reproduce?
ng start <project-name>
npm install --save @angular/material@latest

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, browsers are affected?
angular version 4.0.1
@angular/material@2.0.0-beta.3

#### Is there anything else we should know?
npm install --save @angular/material@latest

Result in terminal

+-- UNMET PEER DEPENDENCY @angular/common@4.0.1
+-- UNMET PEER DEPENDENCY @angular/compiler@4.0.1
+-- UNMET PEER DEPENDENCY @angular/core@4.0.1
+-- @angular/material@2.0.0-beta.3 
+-- UNMET PEER DEPENDENCY @angular/platform-browser@4.0.1
`-- UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@4.0.1

**Comment by fxck** [comment]
https://github.com/angular/material2/issues?utf8=%E2%9C%93&q=UNMET%20PEER%20DEPENDENCY

**Comment by jelbourn** [comment]
This is due to the CLI creating a project with Angular 2.4 by default. Material beta.3 requires at least Angular 4.0. You can either update your Angular dependencies to 4 or file an issue on the angular-cli repo.
