### ISSUE TITLE
MdDialog 'config.data' no longer exposed via MdDialogRef

### ISSUE THREAD

**Issue by ggranum** [angular/material2#3996]
#### Bug, feature request, or proposal:
If the change was intentional, the bug is in the documentation for MdDialogConfig#data [here](https://material.angular.io/components/component/dialog)[1]
If the change was not intentional then the bug is that there is no way to access the config data we pass via the MdDialog#open method. 

#### What is the expected behavior?
I would expect to be able to provide data to a dialog that is about to open in a manner that is accessible at construction time.

#### What is the current behavior?
Have to use the solution discussed in https://github.com/angular/material2/issues/2003 if we want access to config data from within the dialog component.

#### What is the use-case or motivation for changing an existing behavior?
From the docs, it seems like it was the intention for the config object to be exposed. Use case - avoiding duplication, early config, etc. It's not a shockingly big deal either way, but if it's not going to be added back then the documentation should be updated, and should indicate the approved way to pass such data. One could easily argue that a typed 'setConfiguration(...)' method on dialog component classes is better in practice anyway.

#### Which versions of Angular, Material, OS, browsers are affected?
Beta 3, all OS/Browser

https://github.com/crisbeto/material2/commit/549222534c8cf2d2fdbd0f268aebb181159e2e51 removed the public field 'config:MdDialogConfig'. 

[1] https://material.angular.io/components/component/dialog

**Comment by fxck** [comment]
https://github.com/angular/material2/pull/3971#issuecomment-292721991

**Comment by ggranum** [comment]
Thanks @fxck - Perhaps this can be marked as a documentation issue for adding some content around the MD_DIALOG_DATA token to the https://material.angular.io/components/component/dialog API  Reference tab? 

I did a pretty robust search of Issues and even went through the source to find when it was removed, and I had absolutely no idea that the token existed. Pretty sweet, but not super obvious :~)

**Comment by jelbourn** [comment]
Tracking via #3999

**Comment by tarnasky** [comment]
Here's an example of how to use MD_DIALOG_DATA if anyone is interested (also included in 3999):

```ts
import { Component, Inject } from '@angular/core';
import { MdDialogRef, MD_DIALOG_DATA } from '@angular/material';

@Component({
  selector: 'dialog-example',
  template: `
    <h1 md-dialog-title>Dialog Title</h1>
    <div md-dialog-content>
      Lorem ipsum dolor sit amet, consectetur adipscing elit, sed do eiusmod tempor incididunt ut labore et dolore
      magna wiri aliqua. Ut enim ad minim ikad veniam, quis nostrud exceritatn ullamco laboris nisi ut aliquip.
    </div>
    <div md-dialog-actions>
      <button md-button class="dialog-button" (click)="dialogRef.close('Option 1')">OPTION 1</button>
      <button md-button class="dialog-button" (click)="dialogRef.close('Option 2')">OPTION 2</button>
    </div>`,
})
export class DialogExampleComponent {

  constructor(private dialogRef: MdDialogRef<DialogExampleComponent>,
              @Inject(MD_DIALOG_DATA) private data: any) {
    console.log(data);
  }
}
```

**Comment by kelsmj** [comment]
Please note, if you try and inject MD_DIALOG_DATA and you don't actually specify something for the data propery on the MdDialogConfig object, you will get 

```
ERROR Error: No provider for Token MdDialogData!
```

It looks like the MD_DIALOG_DATA token is expected to be registered with the root injector, if data is empty.

**Comment by jelbourn** [comment]
@kelsmj can you file a separate issue for that? It shouldn't throw an error.

**Comment by isherwood** [comment]
@tarnasky, thanks for the example, but I'm scouring the 'net trying to find out how to send data *to* the dialog. It was fairly easy with AM1, but I'm at a loss. Also, I can't seem to figure out how to include both a data object and a config object in the dialog.open function.

**Comment by kelsmj** [comment]
@tarnasky See the code in this [Plunk](http://plnkr.co/edit/cRO1UhY9x46SYV0Kpmfd?p=preview) for simple example

**Comment by kelsmj** [comment]
@isherwood see the example code in this [Plunk](http://plnkr.co/edit/cRO1UhY9x46SYV0Kpmfd?p=preview)

**Comment by jelbourn** [comment]
Or the documentation:
https://material.angular.io/components/dialog/overview

**Comment by isherwood** [comment]
Neither that Plunk demo nor the docs (both of which I've studied) show how to pass data *and* a config object.

**Comment by willshowell** [comment]
@isherwood Take a look at the `MdDialogConfig` section of the [api docs](https://material.angular.io/components/dialog/api)

https://plnkr.co/edit/zEul8QHeQPkwiDIrk7eA?p=preview

**Comment by isherwood** [comment]
@willshowell, thank you. That got me there. My misunderstanding was in thinking that `data` is another sibling argument, and not part of the config object. The AM docs may be complete for someone who has a firm grasp of TS and ng2+, but not if you're swallowing all three at once. :)
