### ISSUE TITLE
md-menu max-height is not calculated properly 

### ISSUE THREAD

**Issue by fxck** [angular/material2#3997]
this is unrelated to https://github.com/angular/material2/issues/2725 (actually looking at the issue again, kara mentions it) / https://github.com/angular/material2/pull/3918

this gist shows the current behaviour as well as behaviour once #3918 is merged and a situation where neither would help https://gist.run/?id=58d5fecb56107042ea0d8786f6a23f5d

I'm not sure what the intended behaviour was supposed to be, but I think it should be one of these

1.a)  menu takes in account the position of the trigger, and open the panel which has height of `window height - 48px - position of the trigger`, ending up with this
![image](https://cloud.githubusercontent.com/assets/1303561/24838883/025b69a0-1d51-11e7-82f3-ba40a31b2a86.png)

1.b) same as 1a, but it open above, when current position of the trigger in view port is closer to button, ending up with this 
![image](https://cloud.githubusercontent.com/assets/1303561/24838896/3d7d9dd2-1d51-11e7-9fda-07aa411219e7.png)

2) it doesn't take in account the position of the trigger, but expands above and below the trigger, filling up the whole page
![image](https://cloud.githubusercontent.com/assets/1303561/24838918/783067c0-1d51-11e7-8e04-1ce5142749ba.png)

3) it stays 100vh - 48px, but actually expands the body height, so you can actually scroll to the part that goes off screen (I don't think this is neither really possible given how overlay works, nor good for UX)

@crisbeto @kara @jelbourn @M-a-c

**Comment by jelbourn** [comment]
Going to track this via #6534 now
