### ISSUE TITLE
Team dashboard

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#4001]
Would probably live under `tools/` with its own `firebase.json`. 

Things I want to track (not necessarily all in one view):
* Total number issues and PRs assigned to core team members
* Daily issue and PR open/close volume. 
* Payload size chart (per-commit)
* Some kind of score for code reviews (not totally sure what we want to do for this)
* Alert for if Travis is broken
* PRs with merge conflicts

Open to other ideas if anyone has them
(cc @kara @andrewseguin @mmalerba @tinayuangao @crisbeto)

Bonus / for fun:
* Aggregate issue [sentiment](https://en.wikipedia.org/wiki/Sentiment_analysis) ([w/ GCP](https://cloud.google.com/natural-language/docs/sentiment-tutorial))

**Comment by crisbeto** [comment]
Perhaps we can have some system for distributing code reviews?

**Comment by jelbourn** [comment]
@crisbeto yeah, as s separate thing I want to make it so that we can assign PRs to @titanium-octobot and it will round-robin it to someone.

**Comment by DevVersion** [comment]
@jelbourn It could also assign PRs that are not assigned to the person that is responsible for that PR? Like with PullApprove (just assigning)

**Comment by jelbourn** [comment]
Yeah, that would be something to take into account

**Comment by crisbeto** [comment]
Another thing that could be pretty useful (not sure if it's doable) would be to have a quick overview of which PRs have merge conflicts. Right now GitHub only shows the CI status and you have to click through to see whether something has conflicts.

**Comment by DevVersion** [comment]
That's a nice idea. I'll add those to the TODO's
