### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by evertonrobertoauler** [angular/material2#4005]
#### Bug

Some components like md-button does not work with Server Side Rendering using @angular/platform-server.

#### What is the expected behavior?

Test if variables like window and document exists in the platform before using them.

#### What is the current behavior?

ReferenceError: document is not defined at FocusOriginMonitor._registerDocumentEvents

#### What are the steps to reproduce?

git clone https://github.com/evertonrobertoauler/cli-universal-demo.git
cd cli-universal-demo
git checkout @angular/material
npm install
npm run start

#### What is the use-case or motivation for changing an existing behavior?

Support for Server Side Rendering

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 4.0.1, Material 2 beta 3

**Comment by jelbourn** [comment]
Tracking this via #308
