### ISSUE TITLE
After upgrading to beta 3 theming import is not working with webpack

### ISSUE THREAD

**Issue by daB0bby** [angular/material2#4008]
After upgrading to beta3 my app can't find the theming stylesheet.
I'm building with webpack.

This is my app.scss

    // Vendor styles
    @import '~@angular/material/prebuilt-themes/indigo-pink.css';

    // app styles
    @import './styles/index';

There are no errors during build but in the brwoser I get this error:
**GET http://localhost:3000/~@angular/material/prebuilt-themes/indigo-pink.css 404 (Not Found)**
**Failed to load ~@angular/material/prebuilt-themes/indigo-pink.css**

This worked before with beta2

**Comment by krigton** [comment]
How did you solved this one? thanks!

**Comment by daB0bby** [comment]
@krigton 
I created and included a `vendor.css` file and added Material Theme in there:

    /* Vendor styles */
    @import '~@angular/material/prebuilt-themes/indigo-pink.css';

This `vendor.css` is being imported in my `vendor.ts`
