### ISSUE TITLE
@angular2-material/icon@2.0.0-alpha.4 requires a peer of @angular/http@2.0.0-rc.0 but none was installed.

### ISSUE THREAD

**Issue by soorireddy** [angular/material2#401]
can you please sync up /update  the dependencies with latest angular release

**Comment by soorireddy** [comment]
npm WARN @angular2-material/checkbox@2.0.0-alpha.4 requires a peer of angular2@^2.0.0-beta.8 but none was installed.
npm WARN @angular2-material/card@2.0.0-alpha.4 requires a peer of angular2@^2.0.0-beta.8 but none was installed.

**Comment by Pixcell** [comment]
+1

**Comment by jelbourn** [comment]
Dependency for icon will be updated in the next alpha release.
