### ISSUE TITLE
Autocomplete binding with complex object list doesn't behave as it should

### ISSUE THREAD

**Issue by atul221282** [angular/material2#4011]
#### Bug, feature request, or proposal:
Autocomplete binding with complex object doesn't behave as it should. I want to bind the autocomplete to complex object list and assign the selected complex object to another one. Updated plunker explaining the issue of displayWith

#### What is the expected behavior?
Example in documentation doesn't work with complex object list

#### What is the current behavior?
It works only with array list of string

#### What are the steps to reproduce?
Instead of the binding list with plain string list bind it with the list of complex object.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/CNcnsJWSSWUR7NishhpL?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Autocomplete should manage the complex object binding by providing property name dynamically

#### Which versions of Angular, Material, OS, browsers are affected?
Angular Material v2.0.0-beta.3

**Comment by willshowell** [comment]
The autocomplete docs mention the `displayWith` attribute. You can provide a function that will return the string version of your object. Is that what you're looking for?

**Comment by atul221282** [comment]
I tried that but there is an issue in that function itself it just accept the data as parameter and in that function this is referencing to function itsefl not to my component class therefore i cannot use dynamic property on that project.

**Comment by willshowell** [comment]
Ahh ok I see now. You can do `[displayWith]="displayFn.bind(this)"` but that is arguably clunkier than necessary

http://plnkr.co/edit/mhes4ACUSjvmZo1A9I9o?p=preview

**Comment by atul221282** [comment]
Thanks for your workaround but as you said it is just a workaround. displayWith should be more flexible or complex object binding should be more easy

**Comment by jelbourn** [comment]
If you need a specific context associated with the `displayWith` function, you can bind that context in your TypeScript code. Something like

```ts
@Component({
  selector: 'my-cool-component'
})
class MyCoolComponent {
  myDisplayWithFunction = this.someFunc.bind(this);
}
```
Then use `[displayWith]="myDisplayFunction"`.
