### ISSUE TITLE
Support adding CSS class to MdDialog root element

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#4012]
#### Bug, feature request, or proposal:
Bug / Feature 

#### What is the expected behavior?
Unlike The toast notifications which has a parameter to add a class... There is nothing I can add on the parent container level to change styling of md dialog.  

#### What is the current behavior?
I can just override material styles

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-beta.2

#### Is there anything else we should know?
Nope

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/3472

**Comment by xtianus79** [comment]
@fxck and @jelbourn as of right now this is not available? Or it is

**Comment by jelbourn** [comment]
This exists now

**Comment by shizhenbin** [comment]
like  this is okay: 
this.MarketOrderDetailComponent = this.dialog.open(MarketOrderDetailComponent,{height: '100%',width: '100%',panelClass:"detailDialog"});
