### ISSUE TITLE
component/sidenav plnkr not working

### ISSUE THREAD

**Issue by phani257** [angular/material2#4013]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

Plnkr to work properly
#### What is the current behavior?
Plnkr not working

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by jelbourn** [comment]
The plunker links in the docs site were broken when beta.3 came out. They should all be fixed now.
