### ISSUE TITLE
@angular/platform-server document is not defined

### ISSUE THREAD

**Issue by mahmood-sajjadi** [angular/material2#4025]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Material should work with platform-server

#### What is the current behavior?

Error: Uncaught (in promise): ReferenceError: document is not defined
at ViewportRuler.exports.modules.502.ViewportRuler._cacheViewportGeometry
at new ViewportRuler
at VIEWPORT_RULER_PROVIDER_FACTORY
at NgModuleInjector.get

#### What are the steps to reproduce?

create a sample project with [MdAutocompleteModule, MdInputContainer, MdInputDirective] with platform-server.

#### What is the use-case or motivation for changing an existing behavior?

Users should be able to use Material and PlatfromServer together to generate HTML version of page which containing Material components

#### Which versions of Angular, Material, OS, browsers are affected?

Latest
2.0.0-beta.3
https://github.com/angular/material2-builds.git#b2538ccb7fe586d67c9a053324a7a9be8b63dac7

#### Is there anything else we should know?

I think this issue is related to
https://github.com/angular/material2/blob/c1004cbd3c7fee772996968f181611248b26c19e/src/lib/core/overlay/position/viewport-ruler.ts
**Line 68** : `this._documentRect = document.documentElement.getBoundingClientRect();`

**Comment by jelbourn** [comment]
See #308
