### ISSUE TITLE
production build fails

### ISSUE THREAD

**Issue by mxii** [angular/material2#4029]
#### Bug, feature request, or proposal:

Error message:

ERROR in Error encountered resolving symbol values statically. Calling function 'style', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol MdInputContainer in D:/GFR/SVN/zeiterfassung/trunk/webclient/node_modules/@angular/material/typings/index.d.ts, resolving symbol MdInputContainer in D:/GFR/SVN/zeiterfassung/trunk/webclient/node_modules/@angular/material/typings/index.d.ts, resolving symbol MdInputContainer in D:/GFR/SVN/zeiterfassung/trunk/webclient/node_modules/@angular/material/typings/index.d.ts, resolving symbol MdInputContainer in D:/GFR/SVN/zeiterfassung/trunk/webclient/node_modules/@angular/material/typings/index.d.ts

#### What is the expected behavior?

Build should succeed.

#### What is the current behavior?

Build don't succeed.

#### What are the steps to reproduce?

Updated working project to beta.3

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 4.0.0-rc.2
Material2 beta.3

**Comment by Nikki1993** [comment]
Not experiencing the same behavior. Any reason you are using RC of Angular? Perhaps updating to the latest version (which at the time is 4.0.1). Deleting node_modules folder and then running 
`npm install` or `yarn install`

**Comment by mxii** [comment]
There's no special reason.

Will give it a try, thanks!

**Comment by mxii** [comment]
@Nikki1993 couldn't say what was the real problem.

But updating and fresh reinstallation of npm packages did the trick..

Thanks!
