### ISSUE TITLE
radio does not work as mentioned in the docs

### ISSUE THREAD

**Issue by rahulbats** [angular/material2#403]
the radio button example given in the [README.md](https://github.com/angular/material2/tree/master/src/components/radio) does not work reliably and gives this error 
`Expression has changed after it was checked. Previous value: 'undefined'. Current value: `

to make it work reliably , you need to have the name attribute in the group and radio buttons. The name attribute should match.

If this is by design , the documentation is not correct

**Comment by arciisine** [comment]
Similar issue with the alpha.  @rahulbats suggestion removed the errors.
