### ISSUE TITLE
Doc site "view source" is broken: https://material.angular.io/components/component/menu

### ISSUE THREAD

**Issue by drwho85** [angular/material2#4031]
Doc site "view source" is broken: https://material.angular.io/components/component/menu

Unable to view source code when <> button is clicked.

**Comment by Stexxen** [comment]
![image](https://cloud.githubusercontent.com/assets/4494301/24915711/d029e0a8-1ecf-11e7-80ac-9a32f3925841.png)

Also no errors in console

**Comment by travisjs** [comment]
can use the corresponding plunker previews for now:

![image](https://cloud.githubusercontent.com/assets/423752/24919489/82c2fe6a-1ea9-11e7-9c12-416520e3d9e0.png)

**Comment by jelbourn** [comment]
Tracking this in #4041
