### ISSUE TITLE
Autocomplete: No placeholder "up" animation 

### ISSUE THREAD

**Issue by liri2006** [angular/material2#4032]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
There should be animation for placeholder going up when autocomplete input is focused

#### What is the current behavior?
Placeholder just jumps up without animation. There is down animation though. 

#### What are the steps to reproduce?
Issue is present in docs example: https://material.angular.io/components/component/autocomplete

#### What is the use-case or motivation for changing an existing behavior?
Behavior should be consistent.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.1, Material 2.0.0-beta.3, Chrome

**Comment by willshowell** [comment]
You can track #3992 for progress on this
