### ISSUE TITLE
Incorrect breaking change instructions in new release for 2.0.0-beta.3  f396657

### ISSUE THREAD

**Issue by lord0gnome** [angular/material2#4033]
#### Bug, feature request, or proposal:
Bug/Incorrect instructions

#### What is the expected behavior?
on [this](https://github.com/angular/material2/releases) page
In the section about MaterialModule being deprecated, it suggests importing 
`import { BrowserAnimationsModule }` from `@angular/package-browser/animations`
though for me at least, the correct import is
`import { BrowserAnimationsModule } from @angular/platform-browser/animations`

#### What are the steps to reproduce?
Try this line
`import { BrowserAnimationsModule }` from `@angular/package-browser/animations`
to get the error because `@angular/package-browser/animations` doesn't exist and isn't a real NPM package

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.1

Material 2.0.0-beta.3

#### Is there anything else we should know?
My first issue, probably poorly formatted/structured, happy to get feedback!

**Comment by Stexxen** [comment]
I let my IDE (webstorm) auto import, and it also chose `@angular/platform-browser/animations`

**Comment by Nikki1993** [comment]
Already reported & fixed on master branch https://github.com/angular/material2/commit/b1e5ff6d4f2a8b063976301a13644ad4eb0cdbb1

**Comment by lord0gnome** [comment]
Oh. Sorry about that then!

**Comment by jelbourn** [comment]
Fixed in b1e5ff6, will redeploy the docs site soon.
