### ISSUE TITLE
Tab body content with scrollbar

### ISSUE THREAD

**Issue by rtrompier** [angular/material2#4035]
Since beta-3, all the tabs content have a scrollbar.

Check the mat-tab-body-content class => height: 100%;

**Comment by jelbourn** [comment]
@crisbeto I noticed this on the docs site too

**Comment by naveedahmed1** [comment]
In my case since beta-4, now when I switch the tabs it shows the scrollbar while the animations is in progress. If I unset height everything works fine.

```
.mat-tab-body-content{
    height:unset!important;
}
```

**Comment by jelbourn** [comment]
@naveedahmed1 please open a new issue if you're encountering a new bug

**Comment by naveedahmed1** [comment]
Seems @crisbeto already have a pull request waiting to be merged regarding this issue, https://github.com/angular/material2/pull/4524 do I still need to open a new issue?
