### ISSUE TITLE
Examples on material.angular.io not displaying

### ISSUE THREAD

**Issue by jackrvaughan** [angular/material2#4041]
#### Bug, feature request, or proposal:
It seems the code examples on material.angular.io are not displaying for the HTML, TS, or CSS. 
Example:
<img width="1094" alt="screen shot 2017-04-11 at 5 32 03 pm" src="https://cloud.githubusercontent.com/assets/5679211/24931843/d35ca10e-1edc-11e7-969d-b0a2c87676bf.png">

#### What is the expected behavior?
I would expect to see all the examples code display for the various components. I think there was a site update in the past few days.

#### What is the current behavior?
Example code not displaying on the material.angular.io website.

#### Is there anything else we should know?
Wasn't sure where else to post this issue. That's why I posted here. Please let me know if there is a better place. The examples were extremely useful and I look forward to them being built out further.

**Comment by gedclack** [comment]
actually this happens since few days ago

**Comment by desian78** [comment]
On requests to load this example code's is HTML-Code "301 Moved Permanently".
It seems to be in all example code for every component...

**Comment by agatsoh** [comment]
Any updates when the examples will be displayed ?

**Comment by ietuday** [comment]
you can check code from plunker.

Click on right  top plunker icon.

**Comment by jelbourn** [comment]
Now fixed!
