### ISSUE TITLE
Can't bind to hidden attribute on md-input-container

### ISSUE THREAD

**Issue by kblestarge** [angular/material2#4042]
#### Bug, feature request, or proposal:

Binding doesn't seem to work on the md-input-container as seen here:
```
        <md-input-container [hidden]="isHidden">
            <input mdInput
                   #dispayInput
                   type="text"
                   [required]="required"
                   [placeholder]="placeholder"
                   [(ngModel)]="displayValue"
                   [name]="id">
        </md-input-container>
```
But does work here:
```
    <div [hidden]="isHidden">
        <md-input-container>
            <input mdInput
                   #dispayInput
                   type="text"
                   [required]="required"
                   [placeholder]="placeholder"
                   [(ngModel)]="displayValue"
                   [name]="id">
        </md-input-container>
    </div>
```

#### What is the expected behavior?

It should bind, meaning if isHidden is true, the component will have the hidden attribute.

#### What is the current behavior?

Component is always displayed regardless of isHidden value.

**Comment by jelbourn** [comment]
This is because the `hidden` attribute is implemented in browsers as a simple css rule:
```css
[hidden] {
  display: none;
}
```

This then gets overridden by any user-space style on `display`. For this reason, we consider using the `hidden` property to be an anti-pattern and recommend using `ngIf` instead.
