### ISSUE TITLE
MdDialog header and actions are not fixed when height forces scrolling

### ISSUE THREAD

**Issue by kpaxton** [angular/material2#4053]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When a height is set on a dialog on open that forces vertical scrolling, the content should be the only thing that scrolls. The header and actions should stay fixed with a border separating the containers from the content.

#### What is the current behavior?
The entire content, header, and actions all scroll out of view if the height of the dialog forces vertical scrolling.

#### What are the steps to reproduce?
https://plnkr.co/edit/ZFXcO0EpnndlAdy27XDo?p=preview

#### What is the use-case or motivation for changing an existing behavior?
If you would like your dialog to be a certain height but the content could end up being larger that the designated dialog dimensions available.

#### Which versions of Angular, Material, OS, browsers are affected?
This is with using the latest of Angular@4.0.1 and Material@2.0.0-beta.3 in at least Chrome@56 and Firefox@

#### Is there anything else we should know?
Based on the Material spec the Header and Footer of a Dialog or Card should have a border when the content is scrollable. 
https://material.io/guidelines/components/dialogs.html#dialogs-specs

**Comment by jelbourn** [comment]
Tracking via #4609

**Comment by Chris2011** [comment]
The other ticket points to this ticket :D but I can't see any solution(?)
