### ISSUE TITLE
md-card-subtitle added css class overriding static class

### ISSUE THREAD

**Issue by JDillon522** [angular/material2#4060]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When `md-card-subtitle` (or presumably other components as well) render they render their styles in such a way that class the developer adds take precedence.

#### What is the current behavior?
I have a `.deacivated`, `.activated`, `.pending` class that is added to an `md-card-subtitle` in the template that affects the color. When the content renders a `mat-card-subtitle` class is added after my class. The `mat-card-subtitle` has a color attribute that overrides my own. I tried using `/deep/` but Im either using it wrong or it doesnt work in this case. I've also tried using the dreaded `!important` but that didnt work either.

#### What are the steps to reproduce?
[Plunker](http://plnkr.co/edit/rekYcz9BZK9jMwIkff1L?p=preview)

#### What is the use-case or motivation for changing an existing behavior?
We need to be able to better control style behavior. I cant get it to work in the plunker, but I was able to get it working by wrapping my content inside a dive under the `md-card-subtitle` but that just seems like a hell of a lot of extra markup for something we should be able to control. 

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.4.0
CLI: rc.0
Material: 2.0.0-beta.2

**Comment by willshowell** [comment]
I don't think your plunker is using correct syntax

Try http://plnkr.co/edit/eHLwvkCAka0XrlJYKVsO?p=preview

**Comment by JDillon522** [comment]
Well I feel like a dummy. I didnt catch that simple fubar. I checked my app though and the syntax is correct and the styles apply themselves when I wrap the text in a div inside the subtitle. Odd
