### ISSUE TITLE
md-input-container has an extra line below for the input tag.

### ISSUE THREAD

**Issue by agatsoh** [angular/material2#4072]
#### Bug, feature request, or proposal:
The md-input-container has an extra line for the input tag.

#### What is the expected behavior?
The extra line below the actual text field should not be there.

#### What is the current behavior?
![inputbugmaterial2](https://cloud.githubusercontent.com/assets/15123108/24997601/d222a828-2054-11e7-8cd2-cf0c47dbef61.jpg)

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
Probably the plunker versions have not been updated to the latest 2.0.0-beta.3. I was not having this issue in the earlier versions.
Sample code.
```
<table class="example-full-width" cellspacing="0">
            <tr><td>
              <md-input-container>
                <input mdInput type="text" id="channel_address" name="channel_address" 
                       [(ngModel)]="newChannel.channel_address" placeholder="Channel Address">
              </md-input-container>
            </td></tr>
            <tr><td>
              <md-input-container>
                <input mdInput type="text" id="token_address" name="token_address"
                       [(ngModel)]="newChannel.token_address" placeholder="Token Address">
              </md-input-container>
            </td></tr>
            <tr><td>
              <md-input-container>
                <input mdInput type="number" id="balance" name="balance"
                       [(ngModel)]="newChannel.balance" placeholder="Balance">
              </md-input-container>
            </td></tr>
            <tr><td>
              <md-input-container>
                <input mdInput type="number" id="settle_timeout" name="settle_timeout"
                       [(ngModel)]="newChannel.settle_timeout" placeholder="Settle Timeout">
              </md-input-container>
            </td></tr>
          </table>
```

#### Which versions of Angular, Material, OS, browsers are affected?
I am using Chrome 

#### Is there anything else we should know?
material version is 2.0.0-beta 3

**Comment by willshowell** [comment]
The plunker template here https://goo.gl/DlHd6U is always using the latest master build of material. Can you replicate it there?

**Comment by agatsoh** [comment]
@willshowell Yeah I just tried. I cannot replicate it. May be some problem with my config. You could close this. I have to dig deeper.

**Comment by anantaramdas** [comment]
@agatsoh did you solve the problem? Thank you!

**Comment by GirishKumarMuniraju** [comment]
Hi,
Even i'm facing this issue. If i comment line 
'require('!style-loader!css-loader!../node_modules/materialize-css/dist/css/materialize.css'); ' in my main.ts file everything seems to work fine.
![without-commenting](https://user-images.githubusercontent.com/41534295/54447292-1cb3d400-476f-11e9-879f-d19adfecf0e7.PNG)
![by-commenting](https://user-images.githubusercontent.com/41534295/54447293-1cb3d400-476f-11e9-9088-e79a855b0340.PNG)
