### ISSUE TITLE
Where is scss source files in new version

### ISSUE THREAD

**Issue by dihar** [angular/material2#4074]
#### Bug, feature request, or proposal:
In 2.0.0-beta.2 there was scss source files, witch from I get variables and mixins

#### What is the expected behavior?
I expect source files in `core` folder 

#### What is the use-case or motivation for changing an existing behavior?
I use mixins and variables to creating new styles with material values

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-beta.3

**Comment by shlomiassaf** [comment]
See #4003 , sadly its not included.

cc @jelbourn 
I think the team need to reconsider, style sheets are not JS source code.

**Comment by jelbourn** [comment]
See #4003

**Comment by jelbourn** [comment]
Worth noting that most of the mixins and functions are still available through `_theming.scss` in the root of the package.

**Comment by Maximaximum** [comment]
Mixins and functions are great, but we also need access to the scss variables.
