### ISSUE TITLE
Some sass selector expressions don't work when nested in a theme class

### ISSUE THREAD

**Issue by xmeng1** [angular/material2#4077]
#### Bug, feature request, or proposal:
I have searched this problem and find https://github.com/angular/material2/issues/2662, but when I try to use it I found, the select component still has a problem. 

After setting the theme for the overlay container, the overlying theme of select is changed. 

![](http://storage2.static.itmages.com/i/17/0413/s_1492094302_9682913_138a2b806b.png)

However the problem is the Placeholder and the underline, the color is still the previous theme

 
![](http://storage3.static.itmages.com/i/17/0413/h_1492094311_4009856_38fd6cf0c2.png)
I try to find the reason of the issue and find that there are some CSS define for the placeholder and underline as follows:

material2-master/src/lib/select/_select-theme.scss
```
.mat-select-trigger {
    color: mat-color($foreground, hint-text);

    .mat-select:focus:not(.mat-select-disabled) & {
      color: mat-color($primary);
    }

    .mat-select:not(:focus).ng-invalid.ng-touched:not(.mat-select-disabled) & {
      color: mat-color($warn);
    }
  }

  .mat-select-underline {
    background-color: mat-color($foreground, divider);

    .mat-select:focus:not(.mat-select-disabled) & {
      background-color: mat-color($primary);
    }

    .mat-select:not(:focus).ng-invalid.ng-touched:not(.mat-select-disabled) & {
      background-color: mat-color($warn);
    }
  }
```

So when the Select is focused, these CSS Pseudo-Classes is activated, and the color is the previous theme. I think all DOM add a class of new theme `.xxxxx ` (such as `.red-indigo`), but the pseudo-class is activated, this new theme class is not added. 

I try to solve it, but I cannot find the related code to add class to the DOM

I make a demo and deploy on Firebase

https://github.com/xmeng1/ng2-material-admin

https://ng2-material-admin.firebaseapp.com/

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by xmeng1** [comment]
By the way, only select has this issue, nearly other components work well.

**Comment by xmeng1** [comment]
I found another issue for the overlay if I put two Select in one component, and one is use system theme. the other one is put into the second theme. The expected behaviour is the first use the system theme, the second use the second theme.  But I think current implementation, all the overlay will add the second class name.

**Comment by jelbourn** [comment]
Took @kara a while to figure this out, but this is indeed a real bug. 

The issue is that some styles are using the sass `&` symbol like this:
```scss
    .mat-select:focus:not(.mat-select-disabled) & {
      background-color: mat-color($primary);
    }
```

The problem is that `&` expands to the _entire_ parent selector, which in this case includes the theme class, so that the output is
```scss
    .mat-select:focus:not(.mat-select-disabled) .red-indigo .mat-select-trigger {
      background-color: ...
    }
```

To fix this, theming files should never use the `&` symbol at the _end_ of a selector expression.

**Comment by xmeng1** [comment]
@jelbourn  you are right, I just replace the Ampersand to the normal format in `_theming.scss`, the multiple themes work well now.  Maybe I could try to fix it later.
