### ISSUE TITLE
md-select floating placeholder seems to bleed into elements above it

### ISSUE THREAD

**Issue by Mufasa** [angular/material2#4078]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I expect the floating placeholder to remain within the bounds of the md-select field.

#### What is the current behavior?
When clicking in a md-select field that has a floating placeholder, the placeholder animates upwards and shrinks in size. However, it seems to animate too far as it bleeds into any element that is above it.

#### What are the steps to reproduce?
Here is a plunkr that shows the issue: https://plnkr.co/edit/CtA39Rdtzbg02K6se2rA?p=preview
Select a food item and then a beverage and see what happens to their placeholders.
This plunkr was based off the material md-select example here: https://material.angular.io/components/component/select

#### What is the use-case or motivation for changing an existing behavior?
Current behaviour leads to very ugly UI.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.2
Material 2.0.0-beta.3
OS Mac Sierra 10.12.4
Browsers:
- Chrome (Version 57.0.2987.133 (64-bit))
- FireFox (52.0.2 (64-bit))
- Safari (Version 10.1 (12603.1.30.0.34))

#### Is there anything else we should know?
Nope

**Comment by jelbourn** [comment]
Tracking via #2124
