### ISSUE TITLE
MdInput Form Validation Color

### ISSUE THREAD

**Issue by ryanpm40** [angular/material2#4081]
#### Bug, feature request, or proposal:
This may be a feature request, rather than a bug. But, I think an `<md-input-container>` should underline an empty, required field in red on initialization.

#### What is the expected behavior?
An empty, required form input should be underlined in red, regardless of whether or not a user attempts to type in the field.

#### What is the current behavior?
When using an `<md-input-container>`, an empty required field does not underline in red, unless the user focuses into the field, and then unfocuses.

#### What are the steps to reproduce?
1. Click into the input
2. Click out of the input 

Plunker:  https://plnkr.co/edit/W3VGplOBmDL6Tb39UObR?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material: 2.0.0-beta.3
angular version 4.0.2
Chrome (desktop)

**Comment by willshowell** [comment]
See [this answer](https://github.com/angular/material2/issues/4030#issuecomment-293428493) to a similar issue

**Comment by ryanpm40** [comment]
@willshowell Ohh gotcha. Thanks for letting me know! A bit of a bummer that isn't a part of the material design spec, but I suppose I can perform some custom validation css.
