### ISSUE TITLE
md-select: 'required' attribute does not make md-select field required.

### ISSUE THREAD

**Issue by GoygovRustam** [angular/material2#4083]
#### Bug, feature request, or proposal:
Bug: setting 'required' attribute to md-select has no effect other than putting an asterisk next to it.

#### What is the expected behavior?
If md-select tag inside a form has 'required' attribute, user should not be able to submit form without making a selection.

#### What is the current behavior?
User is able to submit form without selecting any value in md-select/ 

#### What are the steps to reproduce?
create html form and put md-select tag with 'required' attribute inside it. and  submit form.  
(Sample html provided below)

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
```
<form (ngSubmit)="upsertOrganization(organization)">
<md-select placeholder="TimeZone" [(ngModel)]="organization.TimeZoneId" required name="organizationTimeZone">
	<md-option *ngFor="let timeZoneId of availableEnums.TimeZones" [value]="timeZoneId">
						{{timeZoneId}}
					</md-option>
<button type="submit"> Submit </button>
</md-select>
</form>
```
#### Which versions of Angular, Material, OS, browsers are affected?
here are the versions of packages as I use them. 
	"@angular/common": "~2.4.8",
		"@angular/compiler": "~2.4.8",
		"@angular/core": "~2.4.8",
		"@angular/forms": "~2.4.8",
		"@angular/http": "~2.4.8",
		"@angular/platform-browser": "~2.4.8",
		"@angular/platform-browser-dynamic": "~2.4.8",
		"@angular/router": "~3.1.0",
		"@angular/upgrade": "~2.4.8",
		"@angular/material": "2.0.0-beta.2",
		"@angular/flex-layout": "2.0.0-rc.1",
		"angular-in-memory-web-api": "~0.1.5",

I tried in Chrome Version 57.0.2987.133 (64-bit) ,  FireFox 49.0.1, Microsoft Edge 25.10586.672.0

**Comment by jelbourn** [comment]
The "block form submit" behavior is a browser feature that only works on native elements (`<input>`, `<select>` etc.) with no API for custom components to do this.

**Comment by aralroca** [comment]
But is possible to solve it adding an input type="text" (no hidden) inside, with the same ngModel and the field required. Then with CSS set to put it over the md-select with 0.1px width, outline 0 and without borders (visibility hidden and display none is not working with required field).

html:

```                    
<input type="text"
       class="hidden-input"
       [ngModelOptions]="{standalone: true}" 
       [required]="required"
       [(ngModel)]="sameModelThatMdSelect"
 /> 
```

css: 

```
.hidden-input {
  width: .1px;
  border: none;
  position: absolute;
  margin-top: -25px;
  outline: 0;
}
```
