### ISSUE TITLE
update dependencies to RC1

### ISSUE THREAD

**Issue by rahulbats** [angular/material2#409]
the dependencies below are still tied to rc0.
please update them to rc1

"@angular/common": "2.0.0-rc.0",
    "@angular/compiler": "2.0.0-rc.0",
    "@angular/core": "2.0.0-rc.0",
    "@angular/router": "2.0.0-rc.0",
    "@angular/http": "2.0.0-rc.0",
    "@angular/platform-browser": "2.0.0-rc.0",
    "@angular/platform-browser-dynamic": "2.0.0-rc.0",

**Comment by jelbourn** [comment]
This will happen with our next alpha release, which is waiting on a couple more things to be done.
