### ISSUE TITLE
md-toolbar misalignment of content (Ubuntu + Chrome)

### ISSUE THREAD

**Issue by lobo-tuerto** [angular/material2#4091]
#### Bug, feature request, or proposal:
Misalignment of `md-toolbar` contents.

#### What is the expected behavior?
Elements inside the `md-toolbar` should not misalign when the `md-sidenav` is opened.

#### What is the current behavior?
Elements misalign when the `md-toolbar` is inside an `md-sidenav-container`, and also that container has a `md-sidenav(mode='side' opened='true')` in it.
Also it happens when I have a `<span fxFlex></span>` element to push the "email" button you see in the screenshots to the other side. If I remove the `span` element, or close the `md-sidenav` it goes away.

Now, the strange thing is that íf you do a force refresh (CTRL+SHIFT+R | SHIFT+F5 | CTRL+F5) it layouts everything fine, but if you do a simple refresh (CTRL+R | F5) it misalign the elements.

This happens in Chrome, Firefox don't display the same behavior.

#### What are the steps to reproduce?
It's hard to put this into a Plunker because you can do a soft or hard refresh.

So, I have a minimal Angular 4 app with Angular Material that exhibits this behavior.
https://github.com/lobo-tuerto/md-toolbar-issue

Just clone, yarn, ng serve.

#### What is the use-case or motivation for changing an existing behavior?
So this does not happen.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 4.0.2
Angular Material: 2.0.0-beta.3
Flex Layout: version 2.0.0-beta.7

Chrome: Versión 57.0.2987.98 (64-bit)
SO: Ubuntu 16.04.2 LTS
(Also happens on Ubuntu 16.10)

#### Is there anything else we should know?
I really don't know if this is an Angular Material or a Flex Layout issue.
So I will open another ticket over there.

If you need more info on anything let me know and I'll do what I can.

Here are some screenshots that illustrates the problem:
=============================================

These ones show how it looks after a force refresh:
----------------------------------------------------------------------
![ok](https://cloud.githubusercontent.com/assets/5730/25026611/d3f00818-206c-11e7-9f32-d435e52f5403.png)

![ok2a](https://cloud.githubusercontent.com/assets/5730/25026616/d90e6948-206c-11e7-888a-492d1aa641b1.png)

![ok2b](https://cloud.githubusercontent.com/assets/5730/25026618/dc3c7cfe-206c-11e7-83db-f4e41791b56e.png)

These ones show how it looks after a soft refresh:
----------------------------------------------------------------------
![not-ok](https://cloud.githubusercontent.com/assets/5730/25026639/eeba6148-206c-11e7-81f1-f529cb58c7a9.png)

![not-ok2a](https://cloud.githubusercontent.com/assets/5730/25026640/f2586fb6-206c-11e7-97e4-af595c4d2034.png)

![not-ok2b](https://cloud.githubusercontent.com/assets/5730/25026642/f90c60ce-206c-11e7-8f04-a63f863e5dc7.png)

**Comment by lobo-tuerto** [comment]
By the way when you click on the email button icon it gets positioned where it belongs.

**Comment by DevVersion** [comment]
The toolbar implementation changed a bit and shouldn't conflict with Flex-Layout anymore. Please resubmit if this still happens with the latest Angular Material version.
