### ISSUE TITLE
mdToolTip not working in IE Edge

### ISSUE THREAD

**Issue by atul221282** [angular/material2#4095]
#### Bug, feature request, or proposal:
mdToolTip not working in IE Edge

#### What is the expected behavior?
mdToolTip should work in all browser

#### What is the current behavior?
mdToolTip Doesn't appear in IE Edge

#### What are the steps to reproduce?
Just view this plunker in IEEdge 
https://plnkr.co/edit/?p=preview

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://plnkr.co/edit/?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It is bug

#### Which versions of Angular, Material, OS, browsers are affected?
angular 4.0.0, materila ^2.0.0-beta.2, Windows10, IE Edge

#### Is there anything else we should know?
Nope

**Comment by kkulikowski** [comment]
@atul221282 your link to plunkr is broken.
here is a working link:
https://plnkr.co/edit/kR2h9MZePvqq8f7qp117?p=preview

**Comment by atul221282** [comment]
Your plunker got the same issue with mdTooltip. The version of IE Edge I am using is mentioned below
![capture](https://cloud.githubusercontent.com/assets/4570393/25058086/1fc9aac0-21b5-11e7-9305-e79b894245a5.PNG)

**Comment by EndarValuk** [comment]
One more thing noticed, mdTooltip(with binding), when used in child components causing memory leaks.
Will post repro soon

**Comment by Pitmov** [comment]
+1

**Comment by vovcyan** [comment]
+1

**Comment by Alyreon** [comment]
Doesn't work for me either properly.
Very rarely it works but then the text is cut off and it is not reliable.
Also I discovered the toolbox flashing up for shortly when leaving the element, maybe that helps..

**Comment by funkizer** [comment]
I get "TypeError: Object doesn't support property or method 'push'" in Edge and IE 11 when I trigger a tooltip before an earlier tooltip has had time to completely fade away, or if I un-trigger one (move mouse out) while it's still in the process of fading in.

Web-animations-js is installed & imported.

**Comment by andrewseguin** [comment]
@funkizer Can you open a new issue with a working plunker showing this?
