### ISSUE TITLE
md-checkbox inside reactive form checked by default in reactive form

### ISSUE THREAD

**Issue by JDillon522** [angular/material2#4096]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
In the form module only one checkbox is checked by default in a reactive form.. 

#### What is the current behavior?
Both checkboxes are checked by default.

#### What are the steps to reproduce?
http://plnkr.co/edit/XPXMnw?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I need to control checkboxes

#### Which versions of Angular, Material, OS, browsers are affected?
see plnkr

**Comment by crisbeto** [comment]
That's because of the way you're setting up the associated `FormControl`. The first argument is the initial value, which in your case is "tcp" and "udp". Both of them get cast to `true`, hence the checked checkbox. If you want to initialize one checked and one not checked, you have to use this:

```ts
private protocolArray: FormArray = new FormArray([
  new FormControl(true),
  new FormControl()
]);
```

**Comment by JDillon522** [comment]
Ah gotcha. I wasnt aware that FormArrays only return booleans. I had to tweak my code a good bit but I worked around it. Thanks

**Comment by svincent** [comment]
I came across this issue while looking for a way to bind a checkbox to a property of a FormControl's value. In case anyone else ends up here the same way, I'm going to take a stab at clearing up issue @JDillon522 was having.

The problem wasn't that FormArray returns Booleans (it doesn't), it's that md-checkbox treats it's bound FromControl value as truthy. @JDillon522's sample defined the form array this way:

```ts
private protocolArray: FormArray = new FormArray([
    new FormControl('tcp'),
    new FormControl('udp')
]);
```

Note that `'tcp'` and `'udp'` are non-empty strings and therefore truthy. As such, md-checkbox would display both values as checked.  While my problem was a little different, the truthy evaluation of the FormControl's value property tripped me up as well.

That said, you *can* bind md-checkbox to something besides the control's value using md-checkbox's `@Input value` attribute described here: https://material.angular.io/components/component/checkbox. If you go this route, you will also need to bind a callback to `@Output change` and manually set the sub-property's new value. And remember to call your FormControl's `setValue()` method to ensure that the form updates propagate normally.
