### ISSUE TITLE
mdSelect multiple formArray no preselect and no changes to model

### ISSUE THREAD

**Issue by Jimlars** [angular/material2#4098]
md-select multiple FormArray not preselecting values, and changes not reflected in submitted data

Plunker
http://plnkr.co/edit/ywXWjio9PbMBOKYS6Sxw?p=in

**Comment by kara** [comment]
`FormArrays` are designed to group multiple form controls. `md-select` is an individual form control, so you'll want to use `formControlName` there. See updated plunker: http://plnkr.co/edit/pi1AnHLiVRoUBKmBMWmz?p=preview

**Comment by nayfin** [comment]
@kara Thanks this is very helpful. The plunker doesn't work but seeing the code helped a lot. Using this with ReactiveForms was much simpler than I was making it out to be, and let me delete a bunch of FormArrays.

**Comment by bravoprochu** [comment]
@kara  what about array of objects ? I cant figure it out..
