### ISSUE TITLE
Support for Right and Left Arrow Keys for Slide Toggle

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#4099]
Since on selection Slide Toggle switch moves from left to right and on deselection the switch moves from right to left, it could be helpful if support for arrow key is added for this control.

I mean when the focus is on the Slide Toggle, pressing right arrow key should turn on the slide toggle and pressing left arrow key should turn off slide toggle.

**Comment by jelbourn** [comment]
From an a11y standpoint, the slide-toggle is a checkbox; this behavior is potentially confusing to screen-reader users.
