### ISSUE TITLE
Build example ngMaterial app skeleton

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#41]
- [ ] Layout include a side-nav and a top toolbar
- [ ] Contains examples of each of the completed components
- [ ] Uses router

**Comment by sothychan** [comment]
Is there already a design doc for this?  I'm currently using React and Material-UI, and I love the way the Material-UI's documentation site is laid out (are we thinking about the same thing?).  Here is a link to their documentation site:

http://www.material-ui.com/#/components/

If this is something you guys would like, or have another design to implement, I can get started on this.

**Comment by jelbourn** [comment]
We were waiting for md-toolbar to be done before tackling this. This also isn't for the docs site or anything; it's just meant to be a simple example app for users to check out.

**Comment by BernhardRode** [comment]
I'd love to help out. Are you going to be using angular-cli for the demo? I think, that would be an awesome eat your own dogfood kind of thing.

**Comment by jelbourn** [comment]
@BernhardRode: either something with the angular CLI or just a plunker. I'd be happy for someone else to build it, but it probably isn't viable until we have our first actual release.

**Comment by BernhardRode** [comment]
I think about a cli+materialized tour of heroes or something. Maybe i'll find some time during the weekend.

**Comment by jelbourn** [comment]
I'm going to be maintaining this at https://github.com/jelbourn/material2-app for the time being.

**Comment by kuncevic** [comment]
Hi @jelbourn  the current https://github.com/jelbourn/material2-app is not working with the recent angular-cli and has some broken dependencies. Here is a pool request by @christinakayastha  that fixing that https://github.com/jelbourn/material2-app/pull/22 is there any reasons why it is not accepted?

**Comment by jelbourn** [comment]
@kuncevic I don't even have notifications turned on for that repo. I typically update it with each material release.

**Comment by kuncevic** [comment]
@jelbourn I was actually playing with the things recently so I can just create a pool request that would contained the one I mentioned above + updated to all the latest material2 and angular-cli
