### ISSUE TITLE
md-select 'multiple' has occluded overlay UI when at left of window

### ISSUE THREAD

**Issue by pdavin** [angular/material2#4102]
#### Bug, feature request, or proposal:
http://plnkr.co/edit/a7cIlOsBtwWUuhbuLnpF?p=preview

#### What is the expected behavior?
Overlay menu should not use negative left positioning because this offsets the overlay menu and runs it off screen when the md-select is already at the left edge.

#### What is the current behavior?
see Plnkr. http://plnkr.co/edit/a7cIlOsBtwWUuhbuLnpF?p=preview

#### What are the steps to reproduce?
http://plnkr.co/edit/a7cIlOsBtwWUuhbuLnpF?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-beta.3 and at head:master.

**Comment by crisbeto** [comment]
`md-select` doesn't handle horizontal overflows in general. It will be fixed in #3864. I'll close this issue since we have a couple more about the same bug (#3504 and #3831).
