### ISSUE TITLE
Ability to change snackbar location on screen

### ISSUE THREAD

**Issue by ukrukarg** [angular/material2#4103]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I should be able to specify the location of the snackbar (eg. I want it to show up on the right-top side of the screen instead of bottom).

#### What is the current behavior?
Snack bar can only be shown at the very bottom of the screen.

#### What is the use-case or motivation for changing an existing behavior?
Users should not be restricted over where snack bar shows up.

**Comment by josephperrott** [comment]
Closing as a duplicate of #3577
