### ISSUE TITLE
md-select: is it possible to make the option styleable?

### ISSUE THREAD

**Issue by alvachien** [angular/material2#4110]
#### Bug, feature request, or proposal:
It's a feature request.

#### What is the expected behavior?
The option should be styleable (depends on the value), like color, font, like other HTML element.

#### What is the current behavior?
There is no style at all.

#### What are the steps to reproduce?
No steps.

#### What is the use-case or motivation for changing an existing behavior?
N/A.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0 +;

#### Is there anything else we should know?
N/A.

**Comment by kara** [comment]
You should be able to style the options' color and font like any other element, as long as your view encapsulation is turned off. If you're seeing something odd, please provide a plunker in a new issue (not enough info in this issue to repro).
