### ISSUE TITLE
Autocomplete placeholder effect not smooth

### ISSUE THREAD

**Issue by hengkyz** [angular/material2#4117]
#### Bug, feature request, or proposal:
in autocomplete placeholder when we hover or focus on the input the placeholder will go to top of that input field, but the placeholder effect is not smooth, it is different with input field when we click on the field the placeholder effect go smoothly

#### What is the expected behavior?
the effect of the placeholder should be same with the input field

#### What is the current behavior?
the placeholder effect on autocomplete component is not smooth

#### What are the steps to reproduce?

the example we can see in the example from the doc
https://material.angular.io/components/component/autocomplete

#### Which versions of Angular, Material, OS, browsers are affected?
i use chrome and angular version is beta 3

**Comment by fxck** [comment]
There's already a PR for that.

**Comment by hengkyz** [comment]
@fxck ok thank you
can you point me out to that PR?

**Comment by fxck** [comment]
https://github.com/angular/material2/pulls?utf8=%E2%9C%93&q=is%3Apr%20Autocomplete%20placeholder

**Comment by hengkyz** [comment]
@fxck thank you very much
