### ISSUE TITLE
[Autocomplete] Force use to choose the option in the md-option instead of free text

### ISSUE THREAD

**Issue by hengkyz** [angular/material2#4130]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
i think we need some properties / method that can force user to choose from the md-option in the autocomplete instead of free text

#### What is the current behavior?
for now we can input free text in the autocomplete component

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, browsers are affected?
material beta 3

**Comment by fxck** [comment]
https://github.com/angular/material2/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20autocomplete%20force

**Comment by hengkyz** [comment]
@fxck thank you,
