### ISSUE TITLE
not possible to create a directive for md-dialog-container 

### ISSUE THREAD

**Issue by mxii** [angular/material2#4133]
#### Bug, feature request, or proposal:

It's not possible to create a directive with a `md-dialog-container` selector.

#### What is the expected behavior?
Directive should be created..

#### What is the current behavior?
Directive will not be created..

#### What are the steps to reproduce?
- create a directive with this selector: `md-dialog-container`
- open a dialog
- directive constructor isn't fired..

http://plnkr.co/edit/osdEyn9fx2LXNKEURIPT?p=preview

on clicking the button (dialog opens) there should be the console.output.. ?!

#### What is the use-case or motivation for changing an existing behavior?
Idea was to create a directive for md-dialogs cause of current dialogs cannot be moved.

#### Which versions of Angular, Material, OS, browsers are affected?
material beta.3
angular 4.1.0

#### Is there anything else we should know?
No, thanks!

**Comment by kara** [comment]
@jelbourn Is md-dialog-container intended to be used externally?

**Comment by jelbourn** [comment]
It is not- `MdDialogContainer` is an internal implementation details of `MdDialog`.

**Comment by mxii** [comment]
@jelbourn @kara what would be the right way of doing it then?

Creating a directive to get that dialogs "movable".. ?! :)
Could you point me into a possible direction..

Thanks anyway for your awesome work!
