### ISSUE TITLE
proposal(tab): component inside md-tab but outside mat-tab-body-content

### ISSUE THREAD

**Issue by jefersonestevo** [angular/material2#4135]
#### Bug, feature request, or proposal:
proposal?

#### What is the expected behavior?
Create an area to put some content inside the `md-tab` but outside the `mat-tab-body-content`

#### What is the current behavior?
Everything you put inside a md-tab will be inside the `mat-tab-body-content` and cannot have a `fixed` position

#### What is the use-case or motivation for changing an existing behavior?
I have a scenario with a page that uses tabs to show many "subpages". In this scenario, I need to show a content that is contextual to the selected tab but needs to have a fixed position on the page. If I set `position: fixed` to this element, as the `mat-tab-body-content` has a `transform: translate3d(0px, 0px, 0px)`, the component looses it's "fixed" behaviour.

If you look at this [Plunker](http://plnkr.co/edit/vu8agrL4Q5IhG0N4rfdh?p=preview) and scroll down the page, you'll see that the "fixed" content inside the tab is scrolled within it.

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-beta-3

#### Is there anything else we should know?
For now, the way I found to solve this is to create the component outside the tab, and render it based on the `selectedIndex` of the md-tab-group, but I think this solution is really poor as my parent component needs to know the behaviour of my internal component and if someone change my tabs (let's say create a new tab on the beginning) all of my tab indexes will change.

I don't know if the explanation above was really clear but if you have some doubt just ask me.

**Comment by dahaupt** [comment]
This is also interesting for `md-card-actions` inside a `md-tab`, when those actions are based on the currently active tab. I'm not sure but I think I had that problem a few times in my app.
I can provide I plunkr if it's not clear what I mean :)

**Comment by amcdnl** [comment]
I believe nav-tabs might be what you want here.

**Comment by andrewseguin** [comment]
Agreed that this sounds like you want some nav-tabs rather than the tab-group

**Comment by lebnic** [comment]
@andrewseguin & @amcdnl 

Can you provide a link to nav-tab please ? I can't find it...

**Comment by vilkoalexander** [comment]
> @andrewseguin & @amcdnl
> 
> Can you provide a link to nav-tab please ? I can't find it...

https://material.angular.io/components/tabs/examples the lowest example
