### ISSUE TITLE
md-nav-list disableRipple

### ISSUE THREAD

**Issue by userexperiences** [angular/material2#4149]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Putting just disableRipple should disable ripples

#### What is the current behavior?
disableRipple="true" works

#### What are the steps to reproduce?
(Based on material list example)
https://plnkr.co/edit/h2Jnm62Pzbn6P0UaXtgk

#### What is the use-case or motivation for changing an existing behavior?
Consistency with other controls such as buttons

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.2
Material beta.3

**Comment by ocarreterom** [comment]
`disableRipple` have to be set to `md-list-item` instead of `md-nav-list`.
