### ISSUE TITLE
Disabling ripples causing errors

### ISSUE THREAD

**Issue by userexperiences** [angular/material2#4150]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
No console errors

#### What is the current behavior?
Uncaught TypeError: Cannot read property 'launch' of undefined

this._focusedRipple = this._ripple.launch

#### What are the steps to reproduce?

https://plnkr.co/edit/M1FwZpvoSKW1z3YGAJ2P

#### What is the use-case or motivation for changing an existing behavior?

Shouldn't cause errors

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 4.0.2
Material beta.3

**Comment by DevVersion** [comment]
Should be fixed with https://github.com/angular/material2/commit/e22b55e811b867f3015500b800595f68e079985b
