### ISSUE TITLE
Code repetition in node_modules/@angular/material/_theming.scss

### ISSUE THREAD

**Issue by ajmal-shah** [angular/material2#4152]
#### Bug, feature request, or proposal:
node_modules/@angular/material/_theming.scss has multiple blocks of code repeated 4 times!! 

#### What are the steps to reproduce?
npm installing "@angular/material": "2.0.0-beta.3"

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/material": "2.0.0-beta.3"

**Comment by willshowell** [comment]
Dupe of #3931
