### ISSUE TITLE
Is there a `material-components-web` implementation

### ISSUE THREAD

**Issue by mxchange** [angular/material2#4154]
**Proposal:**
Since both this project and this: https://github.com/material-components/material-components-web are maintained by google, I'm wondering if there is going to be a connection or dependency between them in the future? Since most of the css should be the same at least.

**Comment by fxck** [comment]
No.

**Comment by mxchange** [comment]
@fxck any elaboration on this?

**Comment by jelbourn** [comment]
We've chatted a bit with the MDC web folks in the past (and one of their engineers even wrote our md-checkbox). We're open to eventually exploring basing some of our components on top of theirs, but it's nothing something that's going to happen in the short term.

**Comment by Toub** [comment]
Related discussion: https://stackoverflow.com/questions/41180498/material-components-for-the-web-vs-angular-material-2/41211495#41211495

**Comment by odahcam** [comment]
@material implementation looks great, but does it works great with Angular?

You're developing the `cdk` which is really great. I think that using the mdc-web could accelerate the growing of /material2 in so many ways, but there's a lot of things that needs to be considerated like theming, component customization, optimization for angular build system, etc.

Is there any interest or something in using/integrating mdc-web?
