### ISSUE TITLE
Testing Dialog with Jasmin

### ISSUE THREAD

**Issue by NickJorens** [angular/material2#4157]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Available documentation

#### What is the current behavior?
None available

There is no documentation on testing with these components. It would be great to have a reference for testing the Dialog component!

**Comment by euangoddard** [comment]
It would be great, as well, if some of the work that was done in the test suite for the dialog were available as importable utilities to ease some of the complexities around testing dialog components

**Comment by jelbourn** [comment]
See #4056
