### ISSUE TITLE
Theming Angular Material: Documentation Issue

### ISSUE THREAD

**Issue by novoapro** [angular/material2#4164]
In the example for Theming only certain components:
there is a reference error in the code:
// Define the theme.
$candy-app-primary: mat-palette($mat-indigo);
$candy-app-accent:  mat-palette($mat-pink, A200, A100, A400);
$candy-app-theme:   mat-light-theme($candy-app-primary, $candy-app-accent);

// Include the theme styles for only specified components.
@include mat-core-theme(**$theme**);
@include mat-button-theme(**$theme**);
@include mat-checkbox-theme(**$theme**);

Should be **$candy-app-theme** instead, Got the idea but could be confusing.

**Comment by wulfsberg** [comment]
Or the theme should be defined as $theme. I am still feeling my way around reusing Material-defined colors in my own components, but it seems advantageous to rely on this convention.

**Comment by novoapro** [comment]
It's just a minor detail. Could be confusing for people that try to C&P the code to test it while learning how to use this. That's it.

**Comment by dahaupt** [comment]
@kara This one got fixed with #4195. :)

**Comment by kara** [comment]
Hooray! Closing.
