### ISSUE TITLE
Features from textarea input that use @Input such as minRow do not function as expected

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#4165]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I am using for example minRow="24" and nothing occurs in my repo or the example plunker.   It does not work so I have to use css... For resize: none won't work either... I had to create a css class for textarea and set params like the following:
I am able to control the textarea with css using a combination of min-width in %'s and max-width in px's <<<maybe I have that backwards but I will give a code example soon.  

#### What is the current behavior?
Nothing happens 

#### What are the steps to reproduce?
add minRow to the textarea input and nothing occurs in the ui... i.e. such as row and col
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://plnkr.co/edit/xs4znsdKqSDwTgoVz7mI?p=info

this is the plnkr from the example api

#### What is the use-case or motivation for changing an existing behavior?
control the height and with via the api

#### Which versions of Angular, Material, OS, browsers are affected?
material 2.0.0-beta.3 Angular 4.0.2

#### Is there anything else we should know?

**Comment by kara** [comment]
`minRows` is actually part of the autosize directive (`minRows` is actually deprecated in favor of `mdAutosizeMinRows` to make this clearer). If you add autosize in addition to min rows, it will work as expected.

```
<md-input-container>
    <textarea mdInput mdTextareaAutosize mdAutosizeMinRows="6"></textarea>
</md-input-container>
```

Updated plunker here: https://plnkr.co/edit/aIuBUYDhidMwI3wZ6MDM?p=preview

**Comment by xtianus79** [comment]
@kara thank you. Is this as of 2.0.0.3? Also, to activate this do you need to place the mdTextareaAutosize?  Is this a Boolean activator?
