### ISSUE TITLE
Can't bind to 'xPosition' since it isn't a known property of 'md-menu'.

### ISSUE THREAD

**Issue by fxck** [angular/material2#4169]
Is there any reason [these](https://github.com/angular/material2/blob/master/src/lib/menu/menu-directive.ts#L57
) are `@Attribute`s instead of `@Input`s?

I'm trying to pass down the position from a parent component.

@kara @jelbourn

**Comment by jelbourn** [comment]
I think I discussed this with @kara before and there's no major reason they can't be `@Input`s

**Comment by kara** [comment]
Yeah, we just haven't had a chance to implement it.
