### ISSUE TITLE
Load time is slow for IE/Edge, suspecting it's caused by large inline-stylesheets which are rendered into the DOM.

### ISSUE THREAD

**Issue by DarienChoo** [angular/material2#4170]
#### Bug, feature request, or proposal:
N/A

#### What is the expected behavior?
IE/Edge loads as fast as Chrome and FF

#### What is the current behavior?
IE/Edge's loading time is longer than Chrome and FF

Application is running slow in IE/Edge, suspecting it is caused by too many inline-stylesheets been rendered into the DOM. 

Is it possible to reduce the number of inlines-stylesheets (e.g. put them in a single .css file) while remained looking good? Or any advice for improving material2 performance on IE/Edge?

**Comment by kara** [comment]
Is there a specific component or components that don't load quickly in IE/Edge? There isn't really enough info here to investigate.

**Comment by DarienChoo** [comment]
I'd say in overall, it is slow in IE/Edge. Added toolbar and sidenav to the above demo, you can tell the difference by opening it in Chrome and IE/Edge (http://plnkr.co/edit/9tlCQW)

I'm suspecting it might be caused by the inline-stylesheets because this issue was also mentioned in material1 (https://github.com/angular/material/issues/8218), and I also see that there are many inline-stylesheets in material2 
![image](https://cloud.githubusercontent.com/assets/5697198/25264307/aea79328-2698-11e7-8be1-1e5cee71e0b8.png)

I'm wondering if there is any configuration to improve performance in IE/Edge, or at least compress the amount of inline-stylesheets

**Comment by jelbourn** [comment]
Closing this this issue is rather broad
