### ISSUE TITLE
md-select multiple="true" has a position issue

### ISSUE THREAD

**Issue by dmyalik** [angular/material2#4171]
#### Bug, feature request, or proposal:
md-select multiple="true" has a position issue for options container ('.cdk-overlay-pane') - see image below. 

#### What is the expected behavior?
![image](https://cloud.githubusercontent.com/assets/18016528/25223832/40061ca6-25c5-11e7-8d9d-e40f29b555c4.png)

#### What is the current behavior?
![image](https://cloud.githubusercontent.com/assets/18016528/25223862/53dcfbf0-25c5-11e7-8a9c-b8c467c28c2d.png)

#### What are the steps to reproduce?
https://plnkr.co/edit/KFixGy99DDT9QS9ZYXy4?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
material 2.0.0-beta.3, Angular 4.0.2

**Comment by crisbeto** [comment]
I'm not sure I see the issue. Can you elaborate?

**Comment by dmyalik** [comment]
For multiple md-select  - options container is moved to the left side ~ by 30 px. This issue is critical on small devices or when md-select is located near left side. See image below.
![image](https://cloud.githubusercontent.com/assets/18016528/25226025/19f3fe50-25cc-11e7-9e45-6658fb8c1060.png)

It should be like this - 
![image](https://cloud.githubusercontent.com/assets/18016528/25225966/efb5657a-25cb-11e7-8e52-0e3751a92c4b.png)

**Comment by crisbeto** [comment]
I see. This is a known issue that will be fixed with https://github.com/angular/material2/pull/3864. I'll close this as a duplicate.

**Comment by KevinGruber** [comment]
Not fixed with #3864 still happening.
current Version beta.6

Looks like the overlay container is exactly 32px to the left because the 32px from the  checkboxes a re not added to the position left. (they are added to the width though...

**Comment by crisbeto** [comment]
I don't see the issue @KevinGruber. With the old behavior this would've gone outside the viewport:

![a](https://cloud.githubusercontent.com/assets/4450522/26751272/b5a83a06-4835-11e7-9657-ac2ee85a2a70.gif)

**Comment by KevinGruber** [comment]
@crisbeto That is the original Problem the author had.
Not the second with the out of screen.

It seems as I said that the checkbox is added on the left.  and then the 32px are missing on the right because the overall overlay width is not accounting the checkbox.

![bug_select_multiple](https://cloud.githubusercontent.com/assets/7003466/26751334/f16a8d22-4836-11e7-88d2-ddd43ae496f3.gif)

**Comment by crisbeto** [comment]
Ah thanks, I understand now. The extra 32px are intentional, because they allow the selected option to align with the label text, which is according to the Material spec. We do the same on the single-selection `md-select`, but it's less noticeable.

**Comment by KevinGruber** [comment]
Ahh ok. But can you not extend the overlay by 32px to the right to be aligned and not looking awkward.

**Comment by crisbeto** [comment]
Yes, extending the overlay definitely makes sense. I'll open another issue to keep track of it.

**Comment by KevinGruber** [comment]
👍 Thanks

**Comment by naveedahmed1** [comment]
@crisbeto is there any update on the issue highlighted by @KevinGruber ? You have mentioned " We do the same on the single-selection md-select" but in my case single-selection md-select is working perfectly I am having this issue with multiple-selection md-select only.

**Comment by irowbin** [comment]
@crisbeto How to handle a large amount of data? I have more than 3000 objects in the drop-down and it is very slow. Is there any way to load it lazily with a filter input? Thanks

**Comment by crisbeto** [comment]
We're discussing how to handle large amounts of options in https://github.com/angular/material2/issues/5113 @irowbin.

**Comment by irowbin** [comment]
@crisbeto Thanks, I really love this material. Somehow I am able to customize `MatSelect` as per my needs. Lazy load, Search query and Revert to default but, I am still feeling slow when drop-down adding more values by the lazy loader.

Maybe these features are coming in near future too.

Please take a look:
![video_001 1](https://user-images.githubusercontent.com/13050078/33213784-21736914-d151-11e7-8e28-0e40219d022c.gif)
