### ISSUE TITLE
angular4 webpack2 build error

### ISSUE THREAD

**Issue by TaylorPzreal** [angular/material2#4172]
#### feature request:
polyfills.0836852….js:2 Unhandled Promise rejection: Template parse errors:
Can't bind to 'mdmenutriggerfor' since it isn't a known property of 'a'. ("Home</a> <a href="" md-button>Blog</a> <a href="" md-button>About</a> <a class=pull-right md-button [ERROR ->][mdmenutriggerfor]=theme>Theme</a> <md-menu #theme=mdMenu> <button md-menu-item> <md-icon class=text-"): ng:///AppModule/AppComponent.html@0:152
Can't bind to 'mdmenutriggerfor' since it isn't a known property of 'button'. ("dashboard</md-icon> <span>Blue Ocean</span> </button> </md-menu> <button class=pull-right md-button [ERROR ->][mdmenutriggerfor]=account>TaylorPzreal</button> <md-menu #account=mdMenu> <button md-menu-item> <md-"): ng:///AppModule/AppComponent.html@0:567 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
Can't bind to 'mdmenutriggerfor' since it isn't a known property of 'a'. ("Home</a> <a href="" md-button>Blog</a> <a href="" md-button>About</a> <a class=pull-right md-button [ERROR ->][mdmenutriggerfor]=theme>Theme</a> <md-menu #theme=mdMenu> <button md-menu-item> <md-icon class=text-"): ng:///AppModule/AppComponent.html@0:152
Can't bind to 'mdmenutriggerfor' since it isn't a known property of 'button'. ("dashboard</md-icon> <span>Blue Ocean</span> </button> </md-menu> <button class=pull-right md-button [ERROR ->][mdmenutriggerfor]=account>TaylorPzreal</button> <md-menu #account=mdMenu> <button md-menu-item> <md-"): ng:///AppModule/AppComponent.html@0:567
    at syntaxError (http://localhost:9000/dist/vendor.08368524123563a175f8.js:2:293382) [<root>]
    at TemplateParser.parse (http://localhost:9000/dist/vendor.08368524123563a175f8.js:2:484994) [<root>]

when i use webpack in my dev it's success, but when i build it get those errors.

my development:
Linux + Chrome
Angular4.0.2 + @angular/material2.0.0-beta.3 + webpack2.3.3

**Comment by DevVersion** [comment]
At first glance it looks like something minifies your HTML in a non-case-sensitive way. This causes the directive to be not valid anymore.

Are you using the HTML-Loader? If so, with some special configuration?

**Comment by TaylorPzreal** [comment]
@DevVersion thank you very much, i used html-loader, when i changed to 'raw-loader', get success.

**Comment by TaylorPzreal** [comment]
1. change 'html-loader' with 'raw-loader' can fix the bug;
2. ```
    new webpack.LoaderOptionsPlugin({
      htmlLoader: {
        minimize: DEVELOPMENT // workaround for ng2
      },
_###       // minimize: PRODUCTION, // Comment out this line_
      debug: DEVELOPMENT,
      options: {
        context: __dirname
      }
    })
```

**Comment by TaylorPzreal** [comment]
same error with karma unit-tesing, solution here[A "Testing with Material Components" guide to demonstrate including core theme in test suite #4056](https://github.com/angular/material2/issues/4056#issuecomment-295802334)
