### ISSUE TITLE
bug(tabs) left-right arrows on do not function in the AIO project

### ISSUE THREAD

**Issue by petebacondarwin** [angular/material2#4176]
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

that the arrows allow you to scroll between the tab headers on a narrow screen

#### What is the current behavior?

The button do not do anything

#### What are the steps to reproduce?

Go to https://aio-staging.firebaseapp.com/tutorial/toh-pt6 and scroll right down to the bottom. 
There is a collection of tabbed code panes.
Now if you make the screen narrow enough the arrows appear but they don’t seem to function.

#### Which versions of Angular, Material, OS, browsers are affected?

@angular/core@4.0.0 (etc)
@angular/material@2.0.0-beta.3

#### Is there anything else we should know?

This is a blocker on the AIO project.

**Comment by Splaktar** [comment]
On Chrome M57 OS X El Capitan:

Before clicking on the tabs, no arrows appear. Mousewheel scroll through tabs doesn't appear to be implemented.
![screen shot 2017-04-20 at 12 09 56 pm](https://cloud.githubusercontent.com/assets/3506071/25240967/5da2bf06-25c2-11e7-8060-8a1b4132564e.png)

Once you click the second tab, the arrows appear. Clicking the arrows has no effect.
![screen shot 2017-04-20 at 12 10 21 pm](https://cloud.githubusercontent.com/assets/3506071/25240965/5d9d9396-25c2-11e7-8d91-9eb2f1decdd4.png)

**Comment by petebacondarwin** [comment]
Thanks for providing the extra detail @Splaktar.

**Comment by petebacondarwin** [comment]
Clearly it is appears to be working in Plunker: http://plnkr.co/edit/NpJ8xeS17Hd1yk7FrlcB?p=preview

**Comment by petebacondarwin** [comment]
I wonder if we are missing some service or module?

We are doing something a bit unusual, which is that these tab panes are inside the template of an "embedded" component, which is compiled on the fly when a document is loaded.

**Comment by andrewseguin** [comment]
The tab headers are not moving because for some reason there is a CSS rule saying that it should not transform.

```
code-tabs md-tab-gropu .mat-tab-body-content, code-tabs md-tab-group .mat-ripple-element, code-tabs md-tab-group .mat-tab-body-active, code-tabs md-tab-group .mat-tab-body-content, code-tabs md-tab-group .mat-tab-list {
    -webkit-transform: none!important;
    transform: none!important;
}
```

**Comment by petebacondarwin** [comment]
I think the aim might have been to try to block the animations of the panes as they look weird on desktop.

**Comment by petebacondarwin** [comment]
Right - that was exactly it. Thanks for the quick turnaround. Our problem.

**Comment by Splaktar** [comment]
Another reason that you might kill the `transform3d` in sidenav or tabs, it breaks `position: fixed`:
https://github.com/angular/material2/issues/998
