### ISSUE TITLE
Get a better cert for material.angular.io

### ISSUE THREAD

**Issue by froodley** [angular/material2#4177]
#### Bug, feature request, or proposal:

The cert used by material.angular.io is being flagged as suspicious by BlueCoat because it also validates a bunch of junk domains.  Can you get a let's encrypt or whatever?  I can't access the site from work.

**Comment by froodley** [comment]
Domains certified by the cert:

DNS Name: alabamadating.xyz
DNS Name: aomutualinsco.com
DNS Name: authenticselfacupuncture.com
DNS Name: canopeez.com
DNS Name: checkmeoff.com
DNS Name: chilian-it.de
DNS Name: datingservices.club
DNS Name: devtest.trubador.com
DNS Name: enesoftec.com
DNS Name: georgiasingles.xyz
DNS Name: js.aboviq.com
DNS Name: khurafati.xyz
DNS Name: lapakjuragan.com
DNS Name: liendekeyser.be
DNS Name: logrocket.com
DNS Name: mangomango.me
DNS Name: material.angular.io
DNS Name: mermabel.com
DNS Name: miracles.lk
DNS Name: mydiscount.cl
DNS Name: nanayok.com
DNS Name: newyorksingles.xyz
DNS Name: ng.angular-formly.com
DNS Name: onepixy.com
DNS Name: page-fight.com
DNS Name: quality.h2odoctors.com
DNS Name: quantumwhitenoise.com
DNS Name: ratings.samflor.es
DNS Name: rekt.com.co
DNS Name: routefinder.xyz
DNS Name: safe-driving-app.net
DNS Name: salvozappa.info
DNS Name: shopsmartapp.com
DNS Name: skinseedapp.com
DNS Name: startuppworld.com
DNS Name: taraandphil.com
DNS Name: temp.mirkn.com
DNS Name: tribeez.com
DNS Name: virginiasingles.xyz
DNS Name: voucher.crossironmills.com
DNS Name: wap.theprinceon.com
DNS Name: webappdesign.io
DNS Name: webtype.io
DNS Name: weetsystems.com
DNS Name: whitneychoo.com
DNS Name: who-dunn.it
DNS Name: wishlist.merchandiser.io
DNS Name: www.cheesecakesbyjon.com
DNS Name: www.cyberix.co.uk
DNS Name: www.doyoukulele.com
DNS Name: www.drivecms.xyz
DNS Name: www.farmersmutualgc.com
DNS Name: www.fastqs.com
DNS Name: www.feelgoodlit.com
DNS Name: www.getcheq.com
DNS Name: www.howtobecomepartofthe.eu
DNS Name: www.idahosingles.xyz
DNS Name: www.jumpstarthouse.com
DNS Name: www.kumikorin.com
DNS Name: www.lanmaowz.com
DNS Name: www.meandmycode.com
DNS Name: www.meishikr.com
DNS Name: www.metalaborator.io
DNS Name: www.micby.com
DNS Name: www.newcreationbic.org
DNS Name: www.nightz.com.br
DNS Name: www.oaziscvetok.ru
DNS Name: www.ollo.rocks
DNS Name: www.pagemates.com
DNS Name: www.permarinus.com
DNS Name: www.portpalapp.com
DNS Name: www.prysham.net
DNS Name: www.quickstudio.io
DNS Name: www.raciosmultiplos.pt
DNS Name: www.retip.us
DNS Name: www.romko.me
DNS Name: www.samarlenenash.com
DNS Name: www.santosmurray.rocks
DNS Name: www.schoolx.co.in
DNS Name: www.scmicwisconsin.com
DNS Name: www.seaportpuntadeleste.com.uy
DNS Name: www.skilloven.com
DNS Name: www.skincarepal.com
DNS Name: www.sparklingclean.co.za
DNS Name: www.sponter.co
DNS Name: www.sydneysingles.xyz
DNS Name: www.szkolny.club
DNS Name: www.teamhouse.xyz
DNS Name: www.thecupsapp.com
DNS Name: www.tiendasborboleta.es
DNS Name: www.tktr.eu
DNS Name: www.todo.to.it
DNS Name: www.trucnt.com
DNS Name: www.walue.co
DNS Name: www.what2watch.nl
DNS Name: www.worldwidetrendingvideos.com
DNS Name: www.zeugmax.me
DNS Name: yellowcat.cf
DNS Name: yourcenter.in
DNS Name: yousufnejati.com

**Comment by froodley** [comment]
Any update on this?

**Comment by mbleigh** [comment]
This should be fixed once some changes propagate through Firebase Hosting's system (within a few hours).

**Comment by jelbourn** [comment]
Closing this as resolved. Thanks @mbleigh!
