### ISSUE TITLE
No Footer Components

### ISSUE THREAD

**Issue by MichaelSolati** [angular/material2#4181]
#### Bug, feature request, or proposal: **Request**
There is no footer component or anything like that for Angular Material. [MDL](https://getmdl.io/components/index.html#layout-section/footer) has a footer component so I imagine Angular Material should have one as well (likely styled similarly to MDLs).

#### Is there anything else we should know?
I already have something working/done for the footer, I just need to update it for beta 3 (and a few other tweaks I want to do). But it's styled based off of MDLs design.

**Comment by kara** [comment]
Currently we're sticking to components from the Material Design spec. It doesn't have a footer component like the one you linked.  However, there is a component called "bottom nav" that is similar. We are tracking progress for it in https://github.com/angular/material2/issues/408.
