### ISSUE TITLE
small feature question about colors

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#4182]
#### Bug, feature request, or proposal:
Is it to register other colros like primary, accent, warn? Like an array?

#### What is the expected behavior?
N/A

#### What is the current behavior?
N/A

#### What are the steps to reproduce?
N/A

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
More beautiful colors.

#### Which versions of Angular, Material, OS, browsers are affected?
Latest

#### Is there anything else we should know?
Small feature request

**Comment by kara** [comment]
Currently, we just support the three color types described in the Material Design specification. We're not likely to add more than what's in the spec at this time. But these colors are definitely customizable with a custom theme if that helps.
