### ISSUE TITLE
snackbar theming text color - with custom component

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#4183]
#### Bug, feature request, or proposal:
theming is right, but by default, snackbar with component, it is black color instead of light ( always on snackbar)

#### What is the expected behavior?
should be white or light

#### What is the current behavior?
on white light theme schema snackbar component is black/dark

#### What are the steps to reproduce?
it's easy, not needed to reproduce, just a custom theme, and snackbar component

#### What is the use-case or motivation for changing an existing behavior?
works

#### Which versions of Angular, Material, OS, browsers are affected?
all

#### Is there anything else we should know?
nope

**Comment by kara** [comment]
Hard to tell without looking at any code, but it seems like you may not have set the theme class for the overlay. See instructions here for how to set up themes with overlay-based components like the snack bar:

https://material.angular.io/guide/theming#multiple-themes-and-overlay-based-components
