### ISSUE TITLE
Bug(checkbox): hover mouse pointer cursor

### ISSUE THREAD

**Issue by OvidijusStukas** [angular/material2#4185]
#### What is the expected behavior?
Currently when hovering on checkbox'es the mouse cursor does not change.

#### What is the current behavior?
To be same as Material1 and change mouse cursor to pointer 

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.1,
Windows 10,
Chrome 57

**Comment by DevVersion** [comment]
It looks like I did this intentionally because native inputs don't do it either.

See SHA https://github.com/angular/material2/commit/3edf105734e0bce6287478662463846578b5d1e2

**Comment by jelbourn** [comment]
My stance is that the cursor should match the behavior of the corrsesponding native element, which in this case is the default cursor.

**Comment by GaryB432** [comment]
hi... I'm seeing the `pointer` over the label but `default` over the checkbox itself. Is that the intention?

e.g. `<md-checkbox [checked]="true">Pointer Cursor Here</md-checkbox>`

**Comment by jelbourn** [comment]
After chatting with someone on the Material Design team, I changed my mind and agree we should do cursor.
