### ISSUE TITLE
Sidenav: Escape Key should close the sidenav.

### ISSUE THREAD

**Issue by hansl** [angular/material2#419]
This should probably be by default, since there's no sidenav that wouldn't implement it this way (it's a standard).

**Comment by jelbourn** [comment]
@hansl there may be times when you want the sidenav to be open at all times. For now this is in the developer's control, as you can manually set up an event to close the sidenav on escape.

**Comment by jloosli** [comment]
For what it's worth, it was pretty easy to connect this to the escape key as follows:

    <md-sidenav-layout fullscreen (keydown.esc)="sidenav.close()">
       <md-sidenav #sidenav>
       .
       .
       .

**Comment by jelbourn** [comment]
@hansl I'm going to close this for now, since it's quite straightforward for people to add this.
