### ISSUE TITLE
md-option viewValue

### ISSUE THREAD

**Issue by Eldinnie** [angular/material2#4192]
#### proposal:

I would like to set the `viewValue` for an option in and md-slect manually. I have the following setup:
```
<md-select>
  <md-option *ngFor="let data of datas" [value]="data.selector">
    {{data.val}} <md-icon>filter_{{data.num}}</md-icon> 
  </md-option>
</md-select>
```

#### What is the expected behavior?
When I select an option the text in the select should only read the text of `data.val` and not display the icon name aswell.

#### What is the current behavior?
After I selected the option the select shows the data.val and `filter_3` (if the value is 3) as text. 

#### What are the steps to reproduce?
See above

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
I would love to, but the plunker mentioned in this template doesn't support md-icon for some reason, wich makes it a bit difficult

#### What is the use-case or motivation for changing an existing behavior?
It's pretty ugly to see an icon's name in text.

#### Which versions of Angular, Material, OS, browsers are affected?
`"@angular/material": "^2.0.0-beta.3",` 
`"@angular/core": "^4.0.0"`

**Comment by fxck** [comment]
https://github.com/angular/material2/pull/3341

**Comment by Eldinnie** [comment]
That would be good aswell, thanks

**Comment by crisbeto** [comment]
Closing as something that should be possible in master.
