### ISSUE TITLE
change md-select theme color

### ISSUE THREAD

**Issue by rajsmly143** [angular/material2#4193]
#### Bug, feature request, or proposal:

Need to change md-select theme color(background color) and also multiple select option doesn't work
#### What is the expected behavior?
Should select multiple options and change theme color

#### What is the current behavior?
Multi Select Doesn't work and theme color doesn't change

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that includes a code sample or a plunker repro, which gives the team the information needed to investigate.
