### ISSUE TITLE
Can tab control  support both horizontal and vertical?

### ISSUE THREAD

**Issue by jdang67** [angular/material2#4197]
#### Bug, feature request, or proposal:

Can tab control  support both horizontal and vertical?

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by willshowell** [comment]
See #3223

**Comment by mmalerba** [comment]
Dup of #3223
