### ISSUE TITLE
Autocomplete disables home and end keys in text input even when closed

### ISSUE THREAD

**Issue by jonbrock** [angular/material2#4198]
#### Bug, feature request, or proposal:
When the autocomplete dropdown is closed, keyboard control of the associated text field to be as close to normal as possible. However, currently the home and end keys are disabled. It would kind of make sense if home and end opened up the panel and selected the first or last option, but that doesn't happen. They are just ignored.

#### What is the expected behavior?

When the dropdown panel is closed, keyboard navigation in the text input should be close to normal.

#### What is the current behavior?

The home and end keys don't work

#### What are the steps to reproduce?

Instructions are provided here: https://plnkr.co/edit/BNnD50Ct2zOowH3Mg60g?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Disabling the home and end keys doesn't seem to provide any benefit, and at the same time it's confusing to people who are used to clearing the selection via "shift+home  backspace" rather than "ctrl+a backspace"

#### Which versions of Angular, Material, OS, browsers are affected?

Latest version

#### Is there anything else we should know?

**Comment by jefersonestevo** [comment]
Is this related to #3496?

**Comment by mmalerba** [comment]
Dup of #3496
