### ISSUE TITLE
Override snackbar :host styles

### ISSUE THREAD

**Issue by JDillon522** [angular/material2#4201]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I add `extraClasses: ['errorSnackBar']` to my snackbar config in order to override the styles of the container. I should be able to change the background color.
The only way I can get around it is by adding `!important` to everything and thats no bueno.

#### What is the current behavior?
My class is added properly but background color is overwritten by the `:host` styles in the [`snack-bar-container`](https://github.com/angular/material2/blob/master/src/lib/snack-bar/snack-bar-container.scss)

#### What are the steps to reproduce?
Try to change the background color.
[PLNKR Link](http://plnkr.co/edit/X7FBc7?p=preview). The `background: blue` is overridden.

**Comment by JDillon522** [comment]
damnit. I was writing my styles wrong. nevermind.

**Comment by theKush** [comment]
@JDillon522 do you have an example on how you fixed your problem? I am having the same issue where the :host styles is overwriting my css class in snack-bar-container.

**Comment by JDillon522** [comment]
@theKush I just had to be more specific in my styling. I was trying to add error and success type classes. This is what I ended up doing:

```
snack-bar-container {
    &.errorSnackBar, &.successSnackBar {
        height: auto; 
        min-width: initial;
    }

    &.errorSnackBar {
        background: mat-color($rp-warn, 400);
    }   
 
    &.successSnackBar {        
        background: mat-color($rp-accent, 400);
    }
 
    .mat-simple-snackbar .mat-simple-snackbar-message {
        white-space: normal; 
        font-size: 16px;
        font-weight: bold;
    }
}
```

**Comment by theKush** [comment]
@JDillon522 Thanks, It worked by being specific.

**Comment by lutchit** [comment]
@JDillon522 What is the same code in CSS only ?
It's not possible to set warn color without setting a class to the snackbar ?
