### ISSUE TITLE
How To achive responsive behaviour of Grid List

### ISSUE THREAD

**Issue by Debananda** [angular/material2#4211]
#### Bug, feature request, or proposal:
Shall have responsive directives as we have in angular-material(1) as given below

```
<md-grid-list
        md-cols-gt-md="12" md-cols="3" md-cols-md="8"
        md-row-height-gt-md="1:1" md-row-height="4:3"
        md-gutter-gt-md="16px" md-gutter-md="8px" md-gutter="4px">
```

#### What is the expected behavior?
Shall have a way to reduce or increase number of columns depending on screen size

#### What is the current behavior?
Not finding way to change number columns depending on screen size

**Comment by CDDelta** [comment]
You can workaround this by manually setting the number of grid columns in your own code. You can do it easily via flex-layout like this:

```
@ViewChild('grid')
private grid: MdGridList;`

constructor(private media: ObservableMedia) { }

ngOnInit() {
        // ObservableMedia does not fire on init so you have to manually update the grid first.
        this.updateGrid();
	this.media.subscribe(change => { this.updateGrid(); });
}

updateGrid(): void {
	if (this.media.isActive('xl')) { this.grid.cols = 5; }
	else if (this.media.isActive('lg')) { this.grid.cols = 4; }
	else if (this.media.isActive('md')) { this.grid.cols = 3; }
	else if (this.media.isActive('sm')) { this.grid.cols = 2; }
	else if (this.media.isActive('xs')) { this.grid.cols = 1; }
}
```

**Comment by Debananda** [comment]
Thanks @CDDelta

**Comment by fsomme2s** [comment]
`md-cols-gt-md="12" md-cols="3" md-cols-md="8"...`
looks much better to mee, the "solution" is more like a nasty workaround

**Comment by cdouine39** [comment]
just found another solution [here ](https://stackoverflow.com/questions/45188134/change-the-layout-or-cols-value-of-md-grid-list-based-on-screen-size) a bit simpler :

html :  `<md-grid-list [cols]="nbCols" >`
component:
```
private nbCols: number = 2;
ngOnInit() {
        this.updateGrids();
        this.media.subscribe(() => {
            this.updateGrids();
        });
    }
    private updateGrids(): void {
        this.nbCols = (this.media.isActive('xl') || this.media.isActive('lg')) ? 2 : 1;
    }
```
