### ISSUE TITLE
Bug: Material not working correctly when used with Facebook SDK

### ISSUE THREAD

**Issue by ssljivic** [angular/material2#4223]
#### What is the expected behavior?
Input controls should render and behave correctly.

#### What is the current behavior?
MdInput does not display floating label correctly when Facebook SDK for login is used. Check boxes do not render correctly as well.

#### What are the steps to reproduce?

1. Clone https://github.com/ssljivic/material-fb-ng
1. `npm install`
1. `npm start`
1. Open http://localhost:4200 in browser
1. Click **Profile** button
1. See that floating labels work correctly when you start typing in the input boxes.
1. Click **Auth page** button 
1. Click **Facebook Login** button
1. Login and grant access to the test app
1. See that on profile page floating labels are not working correctly anymore when you type into the text box (labels and text overlap)

#### Which versions of Angular, Material, OS, browsers are affected?
Material: 2.0.0-beta.3
OS: Windows 10
Browser: Chrome 58.0.3029.81

**Comment by fxck** [comment]
Create a plunker reproduction instead please. I'm using facebook sdk in my own project and it works just fine.

**Comment by ssljivic** [comment]
Here is the plunker link: http://plnkr.co/edit/9vNG7A6DGZ7njVMLFCNw?p=preview

1. Click Profile button
1. See that floating labels work correctly when you start typing in the input boxes.
1. Click Home button
1. Click Facebook Login button
1. Login and grant access to the test app
1. See that on profile page floating labels are not working correctly anymore when you type into the text box (labels and text overlap)

**Comment by mmalerba** [comment]
updated the plunker: http://plnkr.co/edit/2XyfQVJKdEm9YCfJdBBQ?p=preview the facebook login doesn't seem to work, but the inputs work fine after.
