### ISSUE TITLE
How to disable previous date in Calendar when using Material 2

### ISSUE THREAD

**Issue by vibingopal** [angular/material2#4224]
#### Bug, feature request,
Hi Team,

I am unable to disable the previous dates on the calendar. Could you please suggest the way to implement the feature.

#### What is the expected behavior?
Need to implement airline calendar where we can select start and end date but in start date previous dates should be disabled.

Thank you !

**Comment by fxck** [comment]
There's no calendar in material2 yet. Wrong repo.

**Comment by George35mk** [comment]
LOL haha
