### ISSUE TITLE
md-icon doesn't work with firefox

### ISSUE THREAD

**Issue by elvirdolic** [angular/material2#423]
**Note: for support questions, please use one of these channels:**
https://github.com/angular/material2/blob/master/CONTRIBUTING.md#question.
This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
Bug maybe

* **What is the current behavior?**
md-icon is not working as it should with firefox (44.0.2)

* **If the current behavior is a bug,
please provide steps to reproduce and if possible a minimal demo of the problem**
```
<md-toolbar>
     <span class="fill-remaining-space"></span>
     <button md-icon-button>
      <md-icon>search</md-icon>
    </button>
     <button md-icon-button>
      <md-icon>notifications</md-icon>
    </button>
     <button md-icon-button>
      <md-icon>apps</md-icon>
    </button>
     <button md-icon-button>
      <md-icon>person</md-icon>
    </button>
  </md-toolbar>

```
Plunker Template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

* **What is the expected behavior?**

Icons should be shown

* **What is the motivation / use case for changing the behavior?**

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

alpha 4.0, angular2 rc 0.1

* **Other information**
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

Firefox
![image](https://cloud.githubusercontent.com/assets/17769458/15182143/4e0bce84-178b-11e6-849f-2e53a096d8ee.png)

Chrome
![image](https://cloud.githubusercontent.com/assets/17769458/15182154/59e6080a-178b-11e6-90fd-9f9a90dec48b.png)

**Comment by davidgabrichidze** [comment]
Have you imported required Components and included it in directives and providers?
e.g.

`
...
import {MdIcon} from '@angular2-material/icon';
import {MdIconRegistry} from '@angular2-material/icon/icon-registry';
...

@Component({
...
    providers: [...MdIconRegistry...],
    directives: [...MdIcon...]
})
...
`

**Comment by elvirdolic** [comment]
Everything is imported as it should. The problem was solved by missing network connection in firefox. Thx for prompt help.
