### ISSUE TITLE
feat(card): Input to customize the elevation

### ISSUE THREAD

**Issue by jefersonestevo** [angular/material2#4233]
#### Bug, feature request, or proposal:
feature

#### What is the expected behavior?
Input on md-card to set the elevation of the card

#### What is the current behavior?
Now we can change the card elevation with the css classes `mat-elevation-z[0..24]`, but it would be nice if the final user doen't necessarily have to remember the class name as the component can change itself

#### What is the use-case or motivation for changing an existing behavior?
Some cards of my app needs to be in a different elevation than the default `mat-elevation-z2` and it's more straighforwart if we can use something like: `<md-card [elevation]="3">...</md-card>`

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material: 2.0.0-beta.3

**Comment by jelbourn** [comment]
[Commented on #4236](https://github.com/angular/material2/pull/4236#issuecomment-298436257)
