### ISSUE TITLE
Feature: Swipe Gestures on Sidenav

### ISSUE THREAD

**Issue by mtpultz** [angular/material2#4248]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
On mobile devices be able to swipe to open the sidenav.

#### What is the current behavior?
Doesn't open on swipe requiring an icon to be provided.

#### What is the use-case or motivation for changing an existing behavior?
The ability for an application to be mobile-friendly is common.

**Comment by matte00** [comment]
Any news about this?

**Comment by mmalerba** [comment]
dup of #5712
