### ISSUE TITLE
Support opening floating snackbars

### ISSUE THREAD

**Issue by CDDelta** [angular/material2#4253]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Give MdSnackBar the ability to open floating snackbars like shown here from [material.io](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-specs).
![alt text](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3RXRkX21NSHA0SEk/components_toasts_tabletdesktop1-left.png "Logo Title Text 1")

#### What is the current behavior?
All snackbars opened have to be anchored to the bottom of the page.

#### What is the use-case or motivation for changing an existing behavior?
More flexible ways of using snackbars in a site.

#### Which versions of Angular, Material, OS, browsers are affected?
All

#### Is there anything else we should know?
Floating snackbars need to return to being anchored if the screen size is too small like on mobile.

**Comment by josephperrott** [comment]
This is being worked on and tracked in #3577
