### ISSUE TITLE
material umd js Cannot read property 'prototype' of undefined when using Systemjs

### ISSUE THREAD

**Issue by HeavenlyHost** [angular/material2#4256]
#### Bug, feature request, or proposal:
When attempting to import MaterialModule from material using material.umd.js I get the following error

**"Cannot read property 'prototype' of undefined"**

#### What is the expected behavior?
Load all material modules properly

#### What is the current behavior?
As above

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.3
Material 2.0.0-beta.3
Systemjs 0.20.12
Rxjs 5.3.0

![error](https://cloud.githubusercontent.com/assets/13386144/25374241/88f8e59c-2994-11e7-8ed6-cc37c0d66283.png)

**Comment by DevVersion** [comment]
Actually we are using the UMD bundle inside of our Plunker template as well. Not sure what your setup is, but the bundle should work.

- http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=info

**Comment by HeavenlyHost** [comment]
@DevVersion your plunker use Angular 2, look at my versions
Angular 4.0.3
Material 2.0.0-beta.3
Systemjs 0.20.12
Rxjs 5.3.0

**Comment by DevVersion** [comment]
@HeavenlyHost It's using Angular 4.0.3 and Material from `master`.


![](https://i.gyazo.com/2664acbe8023414500ccc9d9354749a6.png)

And yeah, I will try to remove the `Angular 2` in our Plunker template. Seems to be confusing. Thx

**Comment by HeavenlyHost** [comment]
<body class="mat-app-background">
    <material-app>Loading the Angular Material App...</material-app>
  </body>

**Comment by DevVersion** [comment]
That's weird. It works for me. Cleared my cache to be sure. Anything in the logs?

**Comment by HeavenlyHost** [comment]
So the version of Systemjs is different, could this be a problem ?
Have you tried it with 0.20.12 ?

**Comment by HeavenlyHost** [comment]
@DevVersion I do find this hard to believe as when I change my package json to line up with the libs that you are using I get the following from npm install

> @angular/core@4.0.3 requires a peer of zone.js@^0.8.4

So in a nutshell, to use angular 4.0.3 you need at least zone.js 0.8.4 or above not 0.7.2, sorry chap !

**Comment by HeavenlyHost** [comment]
anybody else want to chip in, I do need an urgent fix for this !!!

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via Plunker.
