### ISSUE TITLE
[MdAutocomplete] cant select items in IE11

### ISSUE THREAD

**Issue by EndarValuk** [angular/material2#4258]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Items in autocomplete shouldbe "mouse-selectable"

#### What is the current behavior?
When u try to select item with a mouse, panel just closes, and nothing happens.
But u can select items with keyboard interaction.

#### What are the steps to reproduce?
Open material official demo site with IE11
[https://material.angular.io/components/component/autocomplete](link)
and try to select something from dropdown with a mouse.

#### What is the use-case or motivation for changing an existing behavior?
Its not working for IE users.

#### Which versions of Angular, Material, OS, browsers are affected?
Tried Angular v.4.0.x, Windows 7, IE11 (11.0.9600.18537CO)

#### Is there anything else we should know?
I think something related to similar problem Promact/md2#43

**Comment by crisbeto** [comment]
This should've been fixed by https://github.com/angular/material2/pull/3188. Can you try installing the latest build from master?

```
npm install https://github.com/angular/material2-builds.git
```

**Comment by mmalerba** [comment]
Closing since this appears to have been fixed, feel free to open a new issue if the PR @crisbeto linked doesn't solve this for you
