### ISSUE TITLE
Unit testing dialogs not intuitive

### ISSUE THREAD

**Issue by teterovic** [angular/material2#4259]
While writing unit tests for a function that handles a angular material 2 dialog using the example code from material 2 i run into problems. 
I'm a Jasmine newbie but I didn't had problems to write unit test before.
**I have to test the result of the afterClose function but i can't get the handle on dialogRef.**

For sure there is a workaround but since this was the first function that was really hard to test and someone liked my post on stackoverflow about it maybe refactoring could make it easier ? 
http://stackoverflow.com/questions/42852816/unit-testing-angular-material-2-dialogs

```
            let dialogRef = this.dialog.open(ExtractPageDialog, {
                width: this.EXPORT_DIALOG_WIDTH,
                data: {
                    document: this.document
                }
            });
            dialogRef.afterClosed().subscribe((result: any) => {
                if (result) {
                    let fileId = this.document.fileId;
                    this.docProvider.extractPage(this.document.fileId, result.fromPage, result.toPage).subscribe(() => {
                       () => { //totest },
                       (error) => { //totest }
                    });
                } else {
                    //totest
                }
            });
```

DOCS:
https://material.angular.io/components/component/dialog

Proposal, change the example to be easier to test:
```
dialogRef.afterClosed().subscribe(this.functionName);

functionName(result: any) {
                if (result) {
                    let fileId = this.document.fileId;
                    this.docProvider.extractPage(this.document.fileId, result.fromPage, result.toPage).subscribe(() => {
                       () => { //totest },
                       (error) => { //totest }
                    });
                } else {
                    //totest
                }
            }
}
```

**Comment by teterovic** [comment]
dialogRef.afterClosed().subscribe(this.functionName);

functionName(result: any) {
                if (result) {
                    let fileId = this.document.fileId;
                    this.docProvider.extractPage(this.document.fileId, result.fromPage, result.toPage).subscribe(() => {
                       () => { //totest },
                       (error) => { //totest }
                    });
                } else {
                    //totest
                }
            }
}

So my proposal is just to modify the example like that so it will be easier to copy/paste and test

**Comment by jelbourn** [comment]
[See our own dialog unit tests for examples](https://github.com/angular/material2/blob/d1128febe6d23f1a1f20446692bc2a8358e8b8cf/src/lib/dialog/dialog.spec.ts#L116-L116).

**Comment by lordgreg** [comment]
Even though this issue has been closed I must say I have never seen such a complex and non-understandable unit tests definition with so many generic variables. overlayContainerElement, viewContainerFixture, ComponentWithChildViewContainer etc..

You have to know each class and its definition perfectly to understand the code. Who would need comments anyways, right?

**Comment by rvehall** [comment]
Has how unit tests are handled been updated over the past year?

**Comment by fizxmike** [comment]
I have to say... I think I got this working, but with Angular6... OMG the boilerplate. I'll post if anyone is interested.

**Comment by TinotendaKay** [comment]
> I have to say... I think I got this working, but with Angular6... OMG the boilerplate. I'll post if anyone is interested.

Please share you solution, I am still struggling to test.

**Comment by alexbjorlig** [comment]
@fizxmike, did you get this to work with Angular v9?

**Comment by herman-rogers** [comment]
Had to add `{ static: true }` to get the directive to work in Angular 8

```javascript
export class DialogContainerComponent {
  @ViewChild(DialogContainerDirective, { static: true })
  childWithViewContainer: DialogContainerDirective;

  get childViewContainer() {
    return this.childWithViewContainer.viewContainerRef;
  }
}
```
