### ISSUE TITLE
Tabs do not animate between states on Safari (iOS, OSX)

### ISSUE THREAD

**Issue by BirdInTheCity** [angular/material2#4260]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
A transition animation consistent with Chrome—tab content animates left/right when selectedIndex changes.

#### What is the current behavior?
Content pops in/out, without an animation

#### What are the steps to reproduce?

1. In Safari on Mac or iOS, open the plunker on the component demo site
2. Click "Tab 2".
3. Observe no content transition.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://material.angular.io/components/component/tabs

#### What is the use-case or motivation for changing an existing behavior?
Consistency across browsers and devices

#### Which versions of Angular, Material, OS, browsers are affected?
Safari Browser iOS & OSX
Angular 4, 
Material 2.0.0-beta.3

**Comment by crisbeto** [comment]
The tabs animations are based on the Angular animations, which in turn use Web Animations API. [Safari doesn't support](http://caniuse.com/#feat=web-animation) the API, which means that you [have to include a polyfill](https://www.npmjs.com/package/web-animations-js).
