### ISSUE TITLE
Calendar UI - View

### ISSUE THREAD

**Issue by jcmartins** [angular/material2#427]
**Note: for support questions, please use one of these channels:**
https://github.com/angular/material2/blob/master/CONTRIBUTING.md#question.
This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
a Calendar UI - View

* **What is the current behavior?**

* **If the current behavior is a bug,
please provide steps to reproduce and if possible a minimal demo of the problem**
via https://plnkr.co or similar.

Plunker Template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

* **What is the expected behavior?**
Select days, months and year and time

* **What is the motivation / use case for changing the behavior?**
I don't found and Calendar UI to Ionic2

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

* **Other information**
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by jelbourn** [comment]
A calendar-style widget it something we'd like to look into eventually, but isn't on our radar before initial release. Feel free to re-file once we've had our 1.0 release.
