### ISSUE TITLE
menu is not working with overflow

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#4270]
# HI! HOW ARE YOU ?

#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
![image](https://cloud.githubusercontent.com/assets/4770180/25404421/2cd0d772-2a00-11e7-99f9-fea30613c8bd.png)

#### What is the current behavior?

Cannot see Web  Material menu anymore.

![image](https://cloud.githubusercontent.com/assets/4770180/25404430/39500e82-2a00-11e7-8b4c-e0615096206a.png)

#### What are the steps to reproduce?
https://pages.corifeus.tk/github/corifeus-web-material/index.html

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
works

#### Which versions of Angular, Material, OS, browsers are affected?
current

#### Is there anything else we should know?
that's all

**Comment by jelbourn** [comment]
[Working on a solution to this](https://github.com/angular/material2/pull/4761)

**Comment by jelbourn** [comment]
Now tracking this via #6534
