### ISSUE TITLE
Refactor screenshot tool to be standalone 

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#4274]
We're calling the whole of the screenshot tooling "pixacto". It consists of code to:
* Take screenshot from jasmine-based e2e tests
* Store those screenshots in Firebase
* Compare test results to "golds" and set PR status to pass/fail based on differences
* Provide a control panel UI where anyone can view the image diffs and project owners can approve the changes.

[Technical overview doc](https://docs.google.com/document/d/1zoELy3CJKDhLmFdggyURHkG0pHA6K-Oav2h2BtFoCN8/edit#heading=h.iihqzltrtvg)
[Draft set-up guide](https://docs.google.com/document/d/1T8OeEtf0Ta-BtBSzG_Kbn0HzfuoP4nlQlmfGjgA_9TA/edit#)

- [ ] Move code into own repo (angular/pixacto)
- [ ] Extract all screenshot related config to be read from a file rather than hard-coded (`pixacto.config`)
   * Firebase paths: untrusted results, trusted test results, goldens
   * GitHub info: repo name, etc. (see `tools/screenshot-tests/functions/github.ts`)
- [ ] Move `screenshot.ts` from `e2e/` and rename `capture.ts`
- [ ] Refactor out `gulp/tasks/screenshot.ts` into a standalone module, something like `compare`.
- [ ] Curate bits of how the whole thing works from the [overview documentation](https://docs.google.com/document/d/1zoELy3CJKDhLmFdggyURHkG0pHA6K-Oav2h2BtFoCN8/edit?ts=58ffb2b6) for a README
- [ ] Finalize the set-up guide based on @tinayuangao's [initial draft guide](https://docs.google.com/document/d/1T8OeEtf0Ta-BtBSzG_Kbn0HzfuoP4nlQlmfGjgA_9TA) (restricted to angular.io accounts). Some of the items include:
* Adding the JWT as the in Travis
* Creating the unauthenticated "untrusted" screenshot bucket in Firebase
* Adding authorized users to approval process
* Adding users to firebase permissions
* Create `functions/index.js` and what that should contain

I think the ultimate structure for the project should look something like
```
src/
├── capture/        (capturing screenshots in e2e tests)
├── compare/        (comparing test result screeenshots to golds)
├── control-panel/  (UI for showing and approving diffs)
|   └── functions/
|       ├── config.json
|       └── index.js
├── firebase/       (adding event handlers, copying data)
├── github/         (setting github status)
└── jwt/            (verifying the json web token)

```

**Comment by oliviertassinari** [comment]
I have just come across that issue. Thanks for sharing the path going forward!

We have been facing the same need for [Material-UI](https://github.com/callemall/material-ui).
We came up with two independent solutions.
- [vrtest](https://github.com/nathanmarks/vrtest) A JavaScript library for running visual regression tests on your components cross browser via selenium.
- [argos-ci](https://github.com/argos-ci/argos) a hosted service to automate visual regression testing.

Here is an [example of build](https://www.argos-ci.com/callemall/material-ui/builds/3048). I'm gonna follow that thread. I'm really curious to see the solution deployed 💅 .

**Comment by tinayuangao** [comment]
[Technical overview doc](https://docs.google.com/document/d/1zoELy3CJKDhLmFdggyURHkG0pHA6K-Oav2h2BtFoCN8/edit)

 [Draft setup guide](https://docs.google.com/document/d/1T8OeEtf0Ta-BtBSzG_Kbn0HzfuoP4nlQlmfGjgA_9TA/edit)

**Comment by jelbourn** [comment]
Closing this since we're now planning on going with a different solution in the long-term.
