### ISSUE TITLE
md-ripple effect should stay within clicked element

### ISSUE THREAD

**Issue by mackelito** [angular/material2#4275]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Ripple effect should be on clicked element only 

#### What is the current behavior?
Effect leaks out over other elements

#### What are the steps to reproduce?
http://plnkr.co/edit/AG6Use4SUK0J0It31HNm?p=preview

**Comment by willshowell** [comment]
The `.md-ripple` class adds `overflow: hidden`, but the ripple inside of it has a higher stacking context. For now, you can add this to have the ripple contained.

```
md-card-title {
  position: relative;
  z-index: 1;
}
```

**Comment by mmalerba** [comment]
The ripple's host element (`md-card-title` in your case) must have a `position` of `relative`, `absolute` or `fixed` (see: http://plnkr.co/edit/wMfRAcnLIR7GSoKVauRq?p=preview)
