### ISSUE TITLE
Nested <md-tab-group>s crash Angular

### ISSUE THREAD

**Issue by oldchevy** [angular/material2#4277]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Before this pull request animation behavior was working fine as intended:
https://github.com/angular/material2/commit/fbfd032c6e5ccd453fd93d57839897e3783a544e

#### What is the current behavior?
Nested `<md-tab-group>`s  with more than two `<md-tab>`s crash the app. With two `<md-tab>`s the second tab is overlaid on top of the first.

#### What are the steps to reproduce?
Here is a plunker detailing the bug. The plunker is running on Angular v4.0.3: 
https://plnkr.co/edit/qSZMIMlfSLIVcGkEzUQq

#### What is the use-case or motivation for changing an existing behavior?
It should be possible to nest tab groupings.

#### Which versions of Angular, Material, OS, browsers are affected?
Most recent, see PR referenced.

**Comment by crisbeto** [comment]
Thanks for the report, I'll re-check it. Before I reverted https://github.com/angular/material2/pull/2411 via https://github.com/angular/material2/commit/fbfd032c6e5ccd453fd93d57839897e3783a544e, I did verify against the old test case, that it was supposed to fix (it was actually crashing the entire tab), and the workaround was no longer necessary.

**Comment by ciesielskico** [comment]
Dup https://github.com/angular/material2/issues/4271 
Related https://github.com/angular/material2/issues/4255

(linking issues to close them more easily later)
