### ISSUE TITLE
@angular/http@2.0.0-rc.1 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by meshekhar** [angular/material2#428]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
npm ERR! peerinvalid The package @angular/http@2.0.0-rc.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular2-material/icon@2.0.0-alpha.4 wants @angular/http@2.0.0-rc.0

* **What is the expected behavior?**
@angular2-material/icon should use @angular/http@2.0.0-rc.1

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.
 @angular/core@2.0.0-rc.1

* **Other information**
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by jelbourn** [comment]
The angular version will be updated in the next release, see #395
