### ISSUE TITLE
Grids within toolbar not accessible

### ISSUE THREAD

**Issue by ashishbaghudana** [angular/material2#4283]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`md-grid-list` should be usable within `md-toolbar`

#### What is the current behavior?
`md-grid-list` directive is not honored within the `md-toolbar` directive. It is not possible to split the toolbar into a grid to organize the contents.

#### What are the steps to reproduce?
The Plnkr link is an example where no content is printed to the screen when using `md-grid-list` within `md-toolbar`.
http://plnkr.co/edit/HEnAhNFSaU3mZ6w0RAed?p=preview

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
I would like to segment up the toolbar into grids of particular size, so I can easily align certain buttons to the right and certain to the left.

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material@2.0.0-beta.3, @angular/core": "^4.0.0 and Chrome

#### Is there anything else we should know?
No

**Comment by donroyco** [comment]
I don't think it's intended to use `md-grid-list` inside of the `md-toolbar` element. You could use [flex-layout](https://github.com/angular/flex-layout) (or just the CSS variant) to achieve this.

**Comment by mmalerba** [comment]
As @donroyco mentioned, this is not the intended use for `md-grid-list`. I recommend plain old [CSS flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) or [angular/flex-layout](https://github.com/angular/flex-layout) for your layout needs
