### ISSUE TITLE
Feature: List item button

### ISSUE THREAD

**Issue by epelc** [angular/material2#4284]
#### Bug, feature request, or proposal:
You should be able to use buttons as list items.

#### What is the current behavior?
the `a[md-list-item` behavior is very similar.

#### What is the use-case or motivation for changing an existing behavior?

Creating lists of actions which aren't necessarily links.

The `data usage` list item from the angular material js list demo page is a good example.
![image](https://cloud.githubusercontent.com/assets/5204642/25440295/0cf677e6-2a6d-11e7-82ce-5b69cb57be95.png)

See https://material.angularjs.org/latest/demo/list

**Comment by mmalerba** [comment]
@kara is this a feature we want to add?

**Comment by kara** [comment]
This is planned as a component called `md-action-list`. We're currently tracking it [here](https://github.com/angular/material2/issues/107).
