### ISSUE TITLE
SideNav Bugs when i put it in a Angular4 Component

### ISSUE THREAD

**Issue by BamiGorengo** [angular/material2#4286]
Hello,

I Created a New Component:
```
import {Component, OnInit} from '@angular/core';

@Component({
    selector: 'app-side-nav',
    template: '<md-sidenav #sidenav align="end" mode="push">Jelly Good! </md-sidenav>'
})

export class SideNavComponent implements OnInit {

    constructor() {
    }

    ngOnInit() {
    }

}
```

When i Include the Component i get a bug:
http://prntscr.com/f13rd1

Any Ideas? When i Place the <md-sidenav> direkt on the same place like the <app-side-nav>... Then it works...

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

Also see the documentation for the sidenav: https://material.angular.io/components/component/sidenav
