### ISSUE TITLE
Autocomplete should come with an option indicator like a select dropdown

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#4292]
#### Bug, feature request, or proposal:
Feature request / proposal

#### What is the expected behavior?
Md Autocomplete should brandish a signifier that more choices are available by clicking or touching the input area.  

#### What is the current behavior?
The current behavior allows for a placeholder that can animate up or always be above the input area.  However, especially when the placeholder is always up the input area looks too much like a plane type="text" input field.  There is barely an indicator that something else lies beneath the click.  

#### What are the steps to reproduce?
all autocomplete examples... *The current iteration seems to be industry standard

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
N/A

#### What is the use-case or motivation for changing an existing behavior?
Just seems that a dropdown-able input should have a dropdown like indicator

#### Which versions of Angular, Material, OS, browsers are affected?
A4, M2, MacOs

#### Is there anything else we should know?
Nope just thought I would put this out there

**Comment by wulfsberg** [comment]
On the other hand, if it has a dropdown-like indicator, people would assume they could get a list of options by clicking on that, which is not the case. Typically, you need to type something before an (asynchronous) search kicks in.
Granted, there are situations where it functions as a hardcoded <select> which just happens to have shortcuts, but this is by no means the only (or, in my opinion, even the most common) use of an autocomplete.

**Comment by mmalerba** [comment]
This is not part of the material spec and I think would lead to more confusion with users thinking its supposed to work like a `md-select`. If you want you can use `md-input-container`'s prefix or suffix to add your own indicator.
