### ISSUE TITLE
Autocomplete: Resizing window doesn't close panel or update position

### ISSUE THREAD

**Issue by epelc** [angular/material2#4294]
![autocomplete no scroll events](https://cloud.githubusercontent.com/assets/5204642/25456698/a5f15478-2aa1-11e7-9e11-0c9a8c01419b.gif)

#### Bug, feature request, or proposal:
Resizing the window doesn't update the autocomplete overlay/panel position.

#### What is the expected behavior?
It should probably close the panel or update the position.

#### What is the current behavior?
The panel stays where it was original opened.

#### What are the steps to reproduce?
- go here https://material.angular.io/components/component/autocomplete
- focus the input to open the panel
- resize your window enough to move the input and the panel will not follow it

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, browsers are affected?
latest material, chrome 57, macOS 10.12.4

**Comment by willshowell** [comment]
Duplicate of #1430?

**Comment by epelc** [comment]
Yes
