### ISSUE TITLE
color option on md-input-container doesn't work in a useful manner

### ISSUE THREAD

**Issue by jasonburrows** [angular/material2#4298]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I explicitly set the colour of an md-input-container it should display in that colour.

#### What is the current behavior?
It will ONLY display in that colour from the moment the user clicks into the field until they enter something.  Then the form dictates the colour.  Your plunker example doesn't exhibit this because it is not tied to an angular reactive form.

#### What are the steps to reproduce?

If it is tied to a reactive form, here is what happens when you specific the 'color' of md-input-container:

```
<form [formGroup]="myForm" novalidate (ngSubmit)="submit()">
  <md-input-container color="primary">
    <input mdInput type="text" formControlName="test" placeholder="test">
  </md-input-container> 
</form>

```
1. Form loads.  It is currently NOT coloured 'primary'.  It is grey.
2. User clicks in the input field.  For this SINGLE GLORIOUS MOMENT, you get to see the input field be the colour you selected.
3. User enters data.  
4. If the data was valid, the form is now the 'primary' colour.  If it was invalid, the form is now the 'warn' colour.

#### What is the use-case or motivation for changing an existing behavior?

As it is, being able to set the colour specifically is basically useless as it will only have this colour for a wildly short period of time.

In particular I find this annoying because I don't want the user to be presented with any 'warning' colours until they actually try to submit the form - but this will give them warning colours immediately.

#### Which versions of Angular, Material, OS, browsers are affected?

@angular/material 2.0.0-beta3
Angular v4.0.1
MacOS
Chrome
Safari
(I imagine the OS and browsers have nothing to do with the problem)

#### Is there anything else we should know?

It didn't used to work this way.  Previously I could control the color using dividerColor in beta 2 and it would respect my choices.

**Comment by jasonburrows** [comment]
Here's a [plunker](https://plnkr.co/edit/Ie2k3OIdvAl64MqKa4hp) that shows what I mean.  It loads grey (not primary, as specified), then if you click into one of the fields and click out, it turns to 'warn'.  So it is only primary for a really small amount of time - to the point where being able to specify the colour is almost useless.

**Comment by mmalerba** [comment]
This is the correct behavior according to the material spec: https://material.io/guidelines/components/text-fields.html#text-fields-states `color` is not meant to change the behavior of when the input is colored, just the pallete that's used.
