### ISSUE TITLE
Prebuilt theme files has no sourcemapping files

### ISSUE THREAD

**Issue by alanpurple** [angular/material2#4299]
They indicate sourcemapping map files, those don't exist

**Comment by jelbourn** [comment]
@DevVersion I don't see this as being particular important, as our scss should mostly be a black-box for end developers.

**Comment by DevVersion** [comment]
@jelbourn Yeah totally agree. At some point we should just output sourcemaps for those as well. Just to be consistent with the bundles.

We could also remove the sourcemaps for that. What do you prefer?

**Comment by jelbourn** [comment]
Can remove the references for now if it's not a lot of time.

**Comment by DevVersion** [comment]
Yeah will look at this once I have the other packaging work done. What would be the full solution? Do we want to ship sourcemaps for those or not?

**Note**: We do ship sourcemaps for all FESM, UMD bundles.

**Comment by jelbourn** [comment]
If someone cares enough to contribute source maps for the scss I would accept it, but I don't think it's important enough for us to spend time on.

**Comment by ryanpm40** [comment]
In case you weren't aware- sourcemaps were present up until this most recent beta.3.

**Comment by DevVersion** [comment]
@ryanpm40 Yep thank you. Once we have our packaging refactored properly (some progress going on there), I will start re-adding the sourcemaps.
