### ISSUE TITLE
Why there is one single _theming.scss?

### ISSUE THREAD

**Issue by krigton** [angular/material2#4301]
#### Bug, feature request, or proposal:
What's the reasoning behind having one single theme helper sass file.
For example we do not use material palettes. We created our own, even if it's not following the material styleguide we set up several palettes and using them through the material theme framework. It's not a big deal but It looks odd to run the compiler through those vars never used.

I propose to move the palette variables out in a separate file and only import it if it's needed.

Another thing would be to let users extend/alter the foreground and background maps when creating new themes

I understand that angular material closely follows google's material styleguide, but I think with a few tweaks in can be made easier to use other colors as well. Today is a bit tricky.

thanks
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by jelbourn** [comment]
Because we don't preserve the source file structure in the release package, which the imports for individual files are relative to.

**Comment by krigton** [comment]
Do you intend to break theme? Maybe in the CDK, or offer a more flexible way to theme? I managed to create a framework on the top of the theming, but I think it would nicer to offer a bit more on this.
