### ISSUE TITLE
Ability to set focus to specific element on MdDialog when opening

### ISSUE THREAD

**Issue by BondiGeek** [angular/material2#4303]
#### feature request

Ability to set focus to specific element on MdDialog when opening AND have all buttons included in the tab order

#### What is the expected behavior?

On a dialog with two or more buttons eg: [OK][Cancel] it would be nice to be able to set the tabindex on each (in my scenario OK=1 and Cancel=0) and have it focus to the button with the lowest tab index when the dialog opens.

This way you can tab between the buttons and have the default set to a button you specify with a tabindex of 0

#### What is the current behavior?

From the documentation
"Once a dialog opens, the dialog will automatically focus the first tabbable element.
You can control which elements are tab stops with the tabindex attribute
<button md-button tabindex="-1">Not Tabbable</button>"

Using the scenario above it appears that it focuses on the first tabbable element in the dom (OK button in this instance) and the only way to get the Cancel button to be the default is to set the tabindex of OK to -1 which then means you can't tab between the buttons.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?

To have a tab order on buttons and set a specific button to be the default

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/core": "^4.0.0",
"@angular/material": "^2.0.0-beta.3",
Windows 7
Chrome Version 58.0.3029.81 (64-bit)

**Comment by BondiGeek** [comment]
fixed by adding a cdk-focus-start attribute to the button required to be the default

**Comment by skeize** [comment]
FYI, cdk-focus-start is depricated, use cdk-focus-region-start instead.

**Comment by tasnim-reza** [comment]
`cdk-focus-region-start` is deprecated use `cdkFocusRegionstart` instead.

**Comment by lebnic** [comment]
I used `cdkFocusInitial` and it worked :-)
