### ISSUE TITLE
Discussion: Private properties prefixed with underscore - against guidelines

### ISSUE THREAD

**Issue by DaveMonag** [angular/material2#4304]
#### Bug, feature request, or proposal:

Discussion/Question/Proposal

#### What is the expected behavior?

According to current Angular guidelines and TypeScript guidelines, private properties should not be prefixed by an underscore.

#### What is the current behavior?

Currently within the Angular Material2, private properties are prefixed with an underscore.
Random example: https://github.com/angular/material2/blob/master/src/lib/select/select.ts

#### What are the steps to reproduce?

Discussion.

#### What is the use-case or motivation for changing an existing behavior?

It is stated in the ReadMe that:
"Our goal is to build a set of high-quality UI components built with Angular and TypeScript, following the Material Design spec. These components will serve as an example of how to write Angular code following best practices."
Thus should this not be addressed? Or is there another reason for them?

**Comment by DaveMonag** [comment]
Angular guidelines:
https://angular.io/docs/ts/latest/guide/style-guide.html#!#03-04

**Comment by jelbourn** [comment]
We do this for all non-public members because TypeScript has no concept of `internal`. The styleguide is actually out of date and should be updated to remove this guidance, as it ultimately has no business being in the Angular-specific style guide.
