### ISSUE TITLE
Textarea with MdTextareaAutosize does not have initial value

### ISSUE THREAD

**Issue by programmersharp** [angular/material2#4307]
I know there are similar issues with this but it doesn't work for me with the latest version. Height is set to 0px and the initial value is not shown in textarea.

**Comment by dahaupt** [comment]
@programmersharp Can you provide a plunkr to reproduce your issue? 
Plunkr template: https://goo.gl/DlHd6U

**Comment by programmersharp** [comment]
Unfortunately it's very problematic as it is part of the real project.

**Comment by dahaupt** [comment]
@programmersharp If you can't provide a plunker with a reproduction of your problem, this issue is just getting closed by a team member as it doesn't follow the issue template.

**Comment by andrewseguin** [comment]
Please follow the issue template and include reproduction steps. The issue you are describing sounds simple enough that it can be applied in a plunkr, which would significantly help us debug your issue and add a fix.
