### ISSUE TITLE
MdMenu seems to duplicate directives in the menu content

### ISSUE THREAD

**Issue by Eddman** [angular/material2#4309]
#### Bug, feature request, or proposal:
Bug.

#### What is the current behavior?
MdMenu seems to duplicate directives in the menu content. When I do a query `By.directive` it returns all items multiple times (based on how many times you open the menu). The duplicated DebugElement objects **are the same instance**:
```javascript
this.debugElement.queryAll(By.directive(RouterLinkActiveDirective));
```

#### What is the expected behavior?
MdMenu is not duplicating directives.

#### What are the steps to reproduce?
Plunker template: http://plnkr.co/edit/IN9VahhKIbgAK84RDZ73?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.3
Material 2.0.0-beta.3

**Comment by josephperrott** [comment]
I was unable to reproduce this myself, it is very likely that this issue was been resolved since it is a bit dated at this point.  If you are still seeing this issue, please provide a new reproduction of the issue.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
