### ISSUE TITLE
Card inside Tab prevent styling and doesn't style at all in beta.3

### ISSUE THREAD

**Issue by briosheje** [angular/material2#4310]
#### Bug, feature request, or proposal:
Bug: If you insert a Card inside a Tab, any styling won't be applied whatsoever to the card and every inner element (including angular2 material ones)

#### What is the expected behavior?
I would expect them to actually be correctly styled.

#### What is the current behavior?
No style is applied whatsoever but the top border of the card.

#### What are the steps to reproduce?
http://plnkr.co/edit/x1kAEIhcdOpDWPbpfOgY?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I don't know :(

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 4.0.0
Material: 2.0.0-beta.3
Browsers: Google Chrome, Electron (Chromium?)
Os: Windows 10, Mac OSx Sierra

#### Is there anything else we should know?
I love you all and in the 2.0.0-beta.1 version I think it was working properly, since I have a working application with cards inside tabs.

**Comment by willshowell** [comment]
Which parts are not styled correctly? I think you just forgot to wrap you inputs with `<md-input-container>`.

**Comment by briosheje** [comment]
@willshowell Sorry, you are right: inner components are styled properly, I forgot the input container. However, the Card doesn't get styled at all (there only is the top border).

Basically, shadows are either not applied or, maybe (started wondering now) the tab container has no padding: http://plnkr.co/edit/NwYObXEvh61r7owScS2Y?p=preview

I'm guessing the card is actually styled properly and the issue is rather that I should manually add padding to the tab?

**Comment by willshowell** [comment]
Since the shadows fall outside of the card, they're getting cut of by the tab body's `overflow: hidden`. I think it's your best bet to wrap the card with another div and apply padding to it

http://plnkr.co/edit/J4mtUw1GLcy2t5u2ol39?p=preview

Be sure to close this issue if it isn't a bug!

**Comment by briosheje** [comment]
@willshowell Thanks, not sure how it was working in the beta.0 but it's pretty okay now :).
