### ISSUE TITLE
md-input-container:  Allow setting floatPlaceholder globally

### ISSUE THREAD

**Issue by RobJacobs** [angular/material2#4311]
#### Bug, feature request, or proposal:
Allow globally setting the floatPlaceholder option on the md-input-container.  Similar to how the ripple can be globally set.

#### What is the expected behavior?
Globally setting the floatPlaceholder will result in the default action.  floatPlaceholder can still be set inline and would take precedence.

#### What is the current behavior?
floatPlaceholder must be set on each instance or the default 'auto' option will be used.

#### What is the use-case or motivation for changing an existing behavior?
Would like to disable the floating placeholder globally by setting the default value to 'never',

#### Is there anything else we should know?
I have implemented this locally and would be happy to create a PR if there is interest in this feature.  Followed the same approach used for the global ripple disable.

**Comment by mbeckenbach** [comment]
Would be very helpful for me too, as i have a project where floating placeholders should never be used as the customer doesn't like it.

**Comment by RobJacobs** [comment]
Proposed implementation has been checked into my fork listed above.
