### ISSUE TITLE
How to close a dialog from same component where it was opened?

### ISSUE THREAD

**Issue by idnesh** [angular/material2#4312]
#### What are the steps to reproduce?
I opened a dialog from a Component. I need to close the dialog from same component.

#### What is the use-case or motivation for changing an existing behavior?
I would like to use it for loading text.

#### Which versions of Angular, Material, OS, browsers are affected?
 "@angular/common": "2.4.6",
    "@angular/compiler": "2.4.6",
    "@angular/core": "2.4.6",
    "@angular/forms": "2.4.6",
    "@angular/http": "2.4.6",
    "@angular/material": "^2.0.0-alpha.11-3",
    "@angular/platform-browser": "2.4.6",
    "@angular/platform-browser-dynamic": "2.4.6"

**Comment by Kyderman** [comment]
```
let dialogRef = this.dialog.open(ComponentToOpen);
dialogRef.close();
```

**Comment by crisbeto** [comment]
Thank you @Kyderman, this is the correct answer.
