### ISSUE TITLE
material 2 md-select problem with bootstrap modal 

### ISSUE THREAD

**Issue by DanialV** [angular/material2#4316]
material select dose't work currently with bootstrap modal and it's because of the big z-index of bootstrap modal this problem was discussed in this link https://github.com/angular/material/issues/2942 but the solution dose't work for angular material 2

**Comment by crisbeto** [comment]
Material isn't developed to work together with Bootstrap. If you want a dialog that [works with `md-select`, you can use the Material dialog](https://material.angular.io/components/component/dialog).
