### ISSUE TITLE
<md-list> in MdListModule and MdGridListModule have different style

### ISSUE THREAD

**Issue by thisisgit** [angular/material2#4319]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
<md-list> from "MdGridListModule" has no class applied by default.
<md-list> from "MdListModule" has .mat-list class applied by default.

#### What is the current behavior?
If <md-list> is intended to be used without .mat-list css class applied on it, then MdListModule should not be imported from the module.

#### What are the steps to reproduce?
In my case, I added MdListModule and MdGridListModule to SharedModule and imported them in a module to use both <md-grid-list> and <md-list> in a component. Then, <md-list> gets .mat-list and its <md-list-item>s are applied with MdListModule styles instead of MdGridListModule's.

#### What is the use-case or motivation for changing an existing behavior?
I prefer to use components/directives without default styles so preferred to use <md-list> of MdGridListModule. But there might be cases where user would still want the <md-list> of MdListModule, so they should be both provided to the users.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 4.0.0
Material: 2.0.0-beta.3
OS: macOS 10.12.4
browser: chrome

**Comment by andrewseguin** [comment]
Sorry, not sure I understand the issue. `mat-list` class is applied to the `md-list` component. The `md-grid-list` will get the `mat-grid-list` style.

**Comment by thisisgit** [comment]
<md-list> is present on both MdListModule and MdGridListModule. I don't know if <md-list> is supposed to be present in MdGridModule alone but anyway, it does and have separate style from the one in MdListModule. Try using that component by importing each module separately and you'll be able to see .mat-list class applied only in the one in MdListModule

**Comment by jelbourn** [comment]
@thisisgit really don't see what you're referring to. Nothing in `MdGridListModule` references or includes `md-list` or the other way around.

Feel free to open a new issue if you have more specifics.
