### ISSUE TITLE
placeholder is not moving up on focus or while entering value in textbox. Working as expected in chrome but not working in firefox 42.0.1

### ISSUE THREAD

**Issue by krishna2404** [angular/material2#432]
* **Do you want to request a *feature* or report a *bug*?** ==> Its a bug

* **What is the current behavior?** ==> Placeholder text is not moving up in textbox on edit. Working as expected in chrome but not working in firefox 42.0.1

     

Plunker: http://plnkr.co/edit/9orpJEw6qC1we0EE8cnz?p=preview

**Comment by davidgabrichidze** [comment]
already improved in #393, will be released in next alpha.5

**Comment by jelbourn** [comment]
Should be fixed in #393
