### ISSUE TITLE
Autocomplete: get property from object

### ISSUE THREAD

**Issue by DiV666** [angular/material2#4321]
Following the material2 documentation for autocomplete, I can not make the control value a property of the object.

In the example, I need the value of the control to be the id of the user, not the complete object, and also display the user's name in the input
http://plnkr.co/edit/ShFxkogDjg45S8jQm8pt?p=preview

Is it possible to do this?

**Comment by willshowell** [comment]
I _feel_ like this is outside the scope of material.

As your plunker stands, your `displayWith` function is called with the selected option's `id`. Just use that `id` to find the correct option from the options array and return its name.

**Comment by DiV666** [comment]
You're right, I did not realize I could do that :S

The only change is that in order to access the controller variables, I had to modify displayWith as follows:
`<md-autocomplete #auto="mdAutocomplete" [displayWith]="displayFn.bind(this)">`

Thank you.
