### ISSUE TITLE
[Tabs] Nav bar does not support paginated labels

### ISSUE THREAD

**Issue by thormentor** [angular/material2#4323]
![screenshot_20170428_154542](https://cloud.githubusercontent.com/assets/6043562/25534037/887d4958-2c2a-11e7-9892-6867c1b31af6.png)

As you can see in the image the active link is "LINK 1" but it underlines "LINK 5" instead of "LINK 1".

I don't think that this is the expected behavior. Is there any work around for this to work properly?

**Comment by willshowell** [comment]
Can you reproduce in a plunker? I thought tabs were supposed to scroll for overflow

**Comment by andrewseguin** [comment]
The tab nav bar doesnt not yet support scrolling on overflow. Will mark this as a feature request.

**Comment by dimkanewtown** [comment]
Any idea when scroll on overflow will be added?

**Comment by andrewseguin** [comment]
Closing as duplicate in favor of #2177
