### ISSUE TITLE
md-input along with "required" attrubute is not working properly in firefox.

### ISSUE THREAD

**Issue by krishna2404** [angular/material2#433]
* **Do you want to request a *feature* or report a *bug*?** => Its a bug

* **What is the current behavior?** => md-input along with "required" attrubute is not working properly in firefox.

Plunker: http://plnkr.co/edit/9orpJEw6qC1we0EE8cnz?p=preview

* **What is the expected behavior?** ==> textbox should not get red color box if its marked as required field. It should give * as coming in chrome

**Comment by davidgabrichidze** [comment]
already improved in #393, will be released in next alpha.5

**Comment by jelbourn** [comment]
Fixed in #393
