### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by hwalyonglance** [angular/material2#4337]
- carousel
- navbar
- gallery
- contextmenu
- scrollspy
- feature discovery
- wysiwyg html
- dual listbox
- input mask
- calendar
- timeline
- search result
- bottom sheet inside modal
- chart / graph
- notifications
- input file with previewer
- vertical tabs
- form wizard
- full screen
- magnifier

**Comment by WeihanLi** [comment]
Is there any plan to add these features? confused on why this issue closed without comment
