### ISSUE TITLE
mdTooltip: no animation with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by karlhaas** [angular/material2#4338]
#### Bug, feature request, or proposal:
**Bug**: Animation of tooltips not working in combination with ChangeDetectionStrategy.OnPush

#### What is the expected behavior?
The animation of mdTooltip should work with ChangeDetectionStrategy.OnPush

#### What is the current behavior?
First there is just a small rectangle with the background color of the tooltip visible. Then it directly shows the full tooltip. Also if I slightly move the cursor above the md-icon-button, the tooltip "jumps" between not visible, fully visibly and just the small rectangle.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.2
Material 2.0.0-beta.3

#### Is there anything else we should know?
It worked with 2.0.0-beta.2

**Comment by willshowell** [comment]
I think this was fixed by #3671. Try using the latest master build to see if your issue has been fixed.

**Comment by jelbourn** [comment]
Should be fixed by  #3671

**Comment by karlhaas** [comment]
thx @willshowell @jelbourn !
Since we are already using Material in production it would be important to get bugfixes more frequent. What is currently the best approach to get the fixes? Would it be possible to get bugfix releases more often?

**Comment by fxck** [comment]
Just use material2-builds, it rarely ever breaks stuff. Been running on the edge for a while without any problems.
