### ISSUE TITLE
List of compatible component libraries

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4339]
#### Bug, feature request, or proposal:
Proposal / Feature request for docs page

#### What is the expected behavior?
The docs should contain a list of compatible 3rd party component libraries. If for example one creates a file upload component, that integrates with materials scss theme or is dependent of material it should be possible for the creator to register it there with name, description, npm and github link.

A compatible component library should be defined as an angular 4.x (first and next LTS version?) compatibe package, that can be integrated to the custom material theme using the common scss mixin explained in the theaming guide on the docs. So anyone could simply install it, import the module, call the mixin and use the components. 

#### What is the current behavior?
You have to search the internet and read github comments to find out about compatible components. Most 3rd party out there looks similar but integration into materials scss theming is mostly missing.

#### What is the use-case or motivation for changing an existing behavior?
As material does not have a huge community as for excample bootstrap, it is hard to find ready to use components, that are compatible with the material theming. This could make the material community grow faster by encouraging people to create compatibe components or share their investment in material designed components, that are compatible with the theming scss.

When using bootstrap instead of material you will find millions of ready to use components out there, which makes developing with bootstrap quite fast and cheap. While at the moment (with MD1 and MD2) it is hard to find compatible 3rd party components.

Maybe the material team could document their project structure, provide a starter project and provide some guidance on how they create, test and deploy this library. Just to make it easier for folks to become component library creators.

#### Is there anything else we should know?
Angular and material are awesome! :-)

**Comment by willshowell** [comment]
I personally disagree with having the material team maintain a list of compatible 3rd party components. That would require them to properly vet and continue to monitor all the 3rd party libs, which seems like a large investment.

I do strongly agree with the point that the team (or community, rather) should generate a guide on properly designing new components with all the strategies that the team has developed (i.e. using `_my_component_theme.scss` for component colors, using the official repo's styleguide/lint rules, etc). It would then be up to the library creators and consumers to claim "unofficial compatibility".

Loosely related, the team is making the hefty claim of serving _as an example of how to write Angular code following best practices_. It would be insightful to see more transparency into why they have made certain design decisions and how/why to apply those to aspiring compatible libraries.

**Comment by jelbourn** [comment]
Generally the philosophy of the Angular team is that we don't maintain lists like this because it can be seen as an endorsement. We encourage folks in the community to do it on their own, though!
