### ISSUE TITLE
Current version number on docs page

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4340]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
The current version number should be present at the docs page in a place that is easy to find.

#### What is the current behavior?
You have to read the blog or watch the github changelog to see if you should update your project while you are browsing the docs every day.

#### What is the use-case or motivation for changing an existing behavior?
Simplicity

**Comment by Jefiozie** [comment]
I think this issue can be closed as the version number is visible in the footer. Right?

![image](https://user-images.githubusercontent.com/17835373/35991257-e7cff5c8-0d06-11e8-8356-1babc564d343.png)


cc: @jelbourn

**Comment by jelbourn** [comment]
Yep.
