### ISSUE TITLE
Split into several npm packages

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4341]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
I would like to install only the buttons and cards from the repo. (Example)

#### What is the current behavior?
You have to install the whole material library and then select which modules you would like to install.

#### What is the use-case or motivation for changing an existing behavior?
Have a look at the asp.net team. They've decided to split almost everything into small nuget packages as this makes it possible to update and release components independently. This decition leads to much faster releases. You don't have to wait for a complete release to fix bugs in only one component.

**Comment by jelbourn** [comment]
We want to maintain a single version for all components; having individual releases for each component would make dealing with dependencies more cumbersome. Once we're out of beta we plan to do weekly releases with the same process as `angular/angular`.
