### ISSUE TITLE
Getting "If 'ng-template' is an Angular component, then verify that it is part of this module" Error After npm-update

### ISSUE THREAD

**Issue by darrenbrett** [angular/material2#4347]
My dev environment:
McBook Air, OS X El Capitan 10.11.6
@angular/cli: 1.0.1
node: 7.4.0

After running "npm-update", I am getting the following error in the console for my Angular 2 app:

> 1. If 'ng-template' is an Angular component, then verify that it is part of this module.
> 2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-template> <div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()"): MdAutocomplete@0:0 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError Error: Template parse errors:
> 'ng-template' is not a known element:

This looks like an issue with material?

I tried updating material in my package.json and am now running:
`"@angular/material":"2.0.0-beta.3",`

But still getting the error.

My full dependencies list looks like this:

```
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material":"2.0.0-beta.3",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "@ng-idle/core": "^2.0.0-beta.8",
    "@ng-idle/keepalive": "^2.0.0-beta.8",
    "@ngtools/webpack": "^1.2.4",
    "@types/socket.io": "^1.4.27",
    "@types/socket.io-client": "^1.4.29",
    "angular-in-memory-web-api": "~0.1.15",
    "angular2-chartjs": "^0.1.6",
    "angular2-markdown": "^1.3.5",
    "angular2-moment": "^1.2.0",
    "angular2-perfect-scrollbar": "^2.0.6",
    "chart.js": "^2.4.0",
    "core-js": "^2.4.1",
    "mydatepicker": "^1.9.7",
    "ng2-pagination": "2.0.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2",
    "@angular/animations": "4.1.0"
  },
```

**Comment by mattheiler** [comment]
You need Angular 2 v. 4+. Here's an example:

```
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.2.2",
    "zone.js": "^0.8.4"
  },
```

**Comment by darrenbrett** [comment]
Thanks, Matt. After updating to Angular 4, I'm now seeing this error in the console:

ERROR TypeError: Cannot set property 'addEventListener' of undefined

**Comment by jelbourn** [comment]
Closing this since the original issue is resolved (Angular v4 dependency). Feel free to open a new issue with more details about subsequent problems.
