### ISSUE TITLE
disabled mdIput cursor should be set to 'text'

### ISSUE THREAD

**Issue by xuanshenbo** [angular/material2#4350]
#### What is the expected behavior?
disabled mdIput cursor should be set to 'text'

#### What is the current behavior?
disabled mdIput cursor is set to 'default'

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://plnkr.co/edit/msfXKmRhfhtQzrjR7iwU?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It is text that's being displayed, intuitively the cursor attribute should be set to 'text', so user can select the text

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.1.0
Material 2.0.0-beta.3
All major browsers

#### Is there anything else we should know?
No

**Comment by jelbourn** [comment]
This is the behavior of the native `<input>` element.
