### ISSUE TITLE
Autocomplete - provide reference to the parent component in displayFn

### ISSUE THREAD

**Issue by areijngoudt** [angular/material2#4353]
#### feature request:
in **displayFn**, the **this** refers to the Mdautocomplete component, not to the custom component in which  displayFn  is implemented.
For translation, I need to grab a translationServive which is injected onto my custom component.
My current implementation is kind of a hack:

```javascript
    displayFn(enumValue: any): string {
        // this here is acually the Mdautocomplete control
        // HACK to get the AutocompleteEnumFormFieldComponent
        const that = (<any>this).template._parentView.parent.component;
        const translatedValue = that.translateService.instant(enumValue);
        return translatedValue;
    }
```

**Comment by jymdman** [comment]
You can bind your displayFn to the component with: 

`[displayWith]="displayFn.bind(this)"`

Then you can use this.translateService..... without the hack!

**Comment by areijngoudt** [comment]
This solves the problem. Thanks @jymdman !

**Comment by NCC1701M** [comment]
@areijngoudt I think this is also only a hack. Because everywhere else where a function is called, `this` points to the component. And this should be done in `displayWith` as well.

Please reopen it

**Comment by victorschinaider** [comment]
No resolution to this?
