### ISSUE TITLE
Retain existing ripples when button state changes to disabled

### ISSUE THREAD

**Issue by willshowell** [angular/material2#4364]
#### Bug, feature request, or proposal:
Bug

#### Expected behavior
When clicking on a button that will immediately become disabled, the ripple should remain until it fades out.

![after](https://cloud.githubusercontent.com/assets/6475576/25627660/57451910-2f31-11e7-8107-9fdd9f5c184d.gif)

#### Current behavior
The ripple is immediately destroyed when the button state changes to disabled.

![before](https://cloud.githubusercontent.com/assets/6475576/25627819/f11410dc-2f31-11e7-89a2-827e89af5e55.gif)

#### What are the steps to reproduce?
http://plnkr.co/edit/otcf7ejUS9GTY1s3s3v2?p=preview

#### Is there anything else we should know?
Happy to open a PR if this is desired behavior

**Comment by DevVersion** [comment]
Yep. We should remove the `*ngIf` and just use the `mdRippleDisabled` binding.

**Comment by willshowell** [comment]
@DevVersion up at #4372!
