### ISSUE TITLE
Nothing happens on selectChange event for md-tab

### ISSUE THREAD

**Issue by absarora** [angular/material2#4369]
#### What is the expected behavior?

call a function on tab selection

#### What is the current behavior?

selectChange event is not working

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/AYQTNaZQYUcZLfc5RoFK?p=info

#### What is the use-case or motivation for changing an existing behavior?

separate md-tab from md-body for more customized behavior

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0
Material 2
OS: Mac
Browser tested on: Chrome

**Comment by absarora** [comment]
You can close this issue. I was able to solve it by adding the `selectChange` event to `md-tab-group` as follows:

`<md-tab-group (selectChange)="onSelect($event)">`

**Comment by SatishChandraPalakoti** [comment]
Hi absarora : Can you please post your resolution. I don't see anything working for me. No custom event is working too. TIA

**Comment by ajay-cd** [comment]
@SatishChandraPalakoti Can you share what you tried so far?

**Comment by SatishChandraPalakoti** [comment]
@ajay-cd It worked for me. I was trying on md-tab instead of md-tab-group. I realized. Thanks all.. 👍
