### ISSUE TITLE
md-menu position issue

### ISSUE THREAD

**Issue by dharveshmydeen** [angular/material2#4376]
I set md-menu at my right corner of the site
i write like x-position="before"
It is working fine in a normal view 
but in mobile responsive 375 * I will scroll my page and it is going out of the view (right side of the screen)
i could i give set position for all the responsive view

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
