### ISSUE TITLE
MdMenu Positions at bottom of parent.

### ISSUE THREAD

**Issue by Brandonhutah** [angular/material2#4378]
#### Bug, feature request, or proposal:
MdMenu component is not positioning itself correctly.

#### What is the expected behavior?
I expect the menu to position itself on or directly adjacent to the button that was clicked to create the menu.

#### What is the current behavior?
When the button to toggle the menu is clicked, the menu appears at the bottom of the page.

#### What are the steps to reproduce?
Here is a github repo of the project I'm having this issue with, as for the life of me I cannot reproduce this using the angular plunker template.

[Repo](https://github.com/Brandonhutah/angular-issue)

#### Which versions of Angular, Material, OS, browsers are affected?
Using all the Angular 4.0.0 libraries, material 2.0.0-beta.3, and google chrome.

**Comment by willshowell** [comment]
Don't know if this explains it, but with a quick glance at your repo, it doesn't look like you've included a theme?

**Comment by Brandonhutah** [comment]
Wow... it really was that simple. I didn't realize theme's were so crucial to material working properly. I'm just upgrading from Angular 1.6 so this is quite a shift for me. Adding a theme fixes the issue, thanks Will!

**Comment by willshowell** [comment]
No problem! The theme is more than just a color palette, it includes several of the shared styles, like overlay components in your case.

I think the next release is supposed to start throwing warnings when you forget to add one.

**Comment by shadow1349** [comment]
What if I wanted to create a custom color theme? In my styles.scss I have 

```
@import '~@angular/material/theming';
@import '~@covalent/core/theming/all-theme';
@import '~@covalent/markdown/markdown-theme';
@import '~@covalent/highlight/highlight-theme';

@include mat-core();

$my-primary-color: (
    50: #c902f0,
    100: #c902f0,
    200: #c902f0,
    300: #c902f0,
    400: #c902f0,
    500: #c902f0,
    600: #c902f0,
    700: #c902f0,
    800: #c902f0,
    900: #c902f0,
    A100: #c902f0,
    A200: #c902f0,
    A400: #c902f0,
    A700: #c902f0,
    contrast: (
        50: $black-87-opacity,
        100: $black-87-opacity,
        200: $black-87-opacity,
        300: $black-87-opacity,
        400: $black-87-opacity,
        500: white,
        600: white,
        700: white,
        800: white,
        900: white,
        A100: $black-87-opacity,
        A200: $black-87-opacity,
        A400: $black-87-opacity,
        A700: white,
    )
);

$primary: mat-palette($my-primary-color);
$accent:  mat-palette($mat-amber, A200, A400, A100);
$warn:    mat-palette($mat-red, 600, 100, 900);
$theme:   mat-light-theme($primary, $accent, $warn);

@include angular-material-theme($theme);
@include covalent-theme($theme); 
```
and I am still getting this behavior. Also after taking out my custom theme and importing `@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';` instead the issue still persists.
Any suggestions?
