### ISSUE TITLE
snack bar basic styles

### ISSUE THREAD

**Issue by HarelM** [angular/material2#4379]
#### feature request
Allow basic defaults styles to snack bar - mainly: Info (blue), Success (green), Warning (yellow), Error (red) 
Toastr nailed it:
http://codeseven.github.io/toastr/demo.html
#### What is the use-case or motivation for changing an existing behavior?
I would like to stop using third party UI component besides material 2, snack-bar feels incomplete at it current state, you guys know well how it should look, don't let me style it, it will just come out ugly :-)
Although current snack-bar has a class element, most cases can use the above 4 types to cover most notification usage cases.
I think it should be part of this library.
Possible API:
`openError(message)`
`openWarning(message)`
`openSuccess(message)`
`openInfo(message)`
Or even without the word open, much like toastr.

**Comment by jelbourn** [comment]
We make it our goal to (mostly) follow the material design spec, which calls the the specific gray color. There is an API for adding a custom css class if you want to customize it.

**Comment by HarelM** [comment]
Thanks for the quick response.
My 2 cents:
I believe that in this case, the material design spec should be updated to include these scenarios as they are so common in my experience, almost every piece of software I wrote in all the UI languages I used needed these options...
I don't know where to file a request to update the design spec...
Good luck!
