### ISSUE TITLE
Is the demo app running anywhere?

### ISSUE THREAD

**Issue by bwiggs** [angular/material2#438]
I see there's a demo app in the repo, but is it up and running anywhere? I didn't see any links for it in the main README.

**Comment by jelbourn** [comment]
The demo-app is primarily for our own development and not really meant as public-facing demos. 

That said, we sporadically deploy it to https://material2-test.firebaseapp.com/ for testing. 

I have a different demo app here: https://material2-app.firebaseapp.com/
(source https://github.com/jelbourn/material2-app)

And @kara has one here: https://puppy-love.firebaseapp.com/
(source https://github.com/kara/puppy-love)

**Comment by bwiggs** [comment]
OK, Thanks!

**Comment by chriszrc** [comment]
For the most options and latest changes, this is the url I found the most helpful:

https://material2-dev.firebaseapp.com/

It would be nice if there was a link to these in the docs-

**Comment by badcoder28** [comment]
@chriszrc yeah they should include that link to their official documentation since that is their working example demo.

**Comment by patrickqsos** [comment]
Actually you can run the demo app locally:

1. Clone the material repo
2. Go to the directory of the cloned repo and install it
`npm install`
3. Build the project
`npm run build`
4. Start the demo app
`npm run demo-app`

I did all that on my mac and the demo app was running on localhost:4200

**Comment by ewaschen** [comment]
Is [https://material2-dev.firebaseapp.com/](https://material2-dev.firebaseapp.com/) still the latest page for development?  Looking at the demo repo [https://github.com/angular/material2/tree/master/src/demo-app](https://github.com/angular/material2/tree/master/src/demo-app) it doesn't match up.

**Comment by badcoder28** [comment]
@ewaschen you can look at @patrickqsos  instruction to build demo from source.

**Comment by jeanko84** [comment]
The @patrickqsos solution doesn't work for me :(

**Comment by leolanese** [comment]
Just 
1. download it from https://github.com/angular/material2/releases
2. npm i
3. npm run demo-app
