### ISSUE TITLE
Support devices which need a css prefix for flex/transform/...

### ISSUE THREAD

**Issue by karlhaas** [angular/material2#4385]
#### Bug, feature request, or proposal:
**Proposal**
For our application (https://app.feedbackr.io) we need a solution which works on all (almost all) currently used mobile devices. According to http://caniuse.com/#feat=flexbox adding css prefixes adds support for many devices.

I have prepared changes in the SCSS files and the layout already looks ok. Styles which are added within templates or by typescript are not considered yet.

https://github.com/angular/material2/compare/master...karlhaas:add-flex-prefixes

#### What is the expected behavior?
All devices which just need a css prefix should be supported.

#### What is the current behavior?
e.g. iOS8 is not supported.

#### What are the steps to reproduce?
use old device 

#### What is the use-case or motivation for changing an existing behavior?
Without the support we have to use another technology for an important part of our application.

#### Which versions of Angular, Material, OS, browsers are affected?
latest

#### Is there anything else we should know?
I'm also providing changes for flex layout https://github.com/angular/flex-layout/pull/276

**Comment by karlhaas** [comment]
I just saw that the project uses autoprefixer. Does it mean it should already apply all the prefixes?

**Comment by karlhaas** [comment]
thx @kara for merging https://github.com/angular/flex-layout/pull/276!
what is your opinion regarding this issue? It would be good to know if the team will merge the changes in order to continue (next step prefix styles which are set dynamically in templates/components).

**Comment by jelbourn** [comment]
For Angular Material, our official browser support policy is "last two major versions of each browser" plus IE11. For Safari, this means we only support 9 and 10.

**Comment by ethanroday** [comment]
@jelbourn The latest version of UC Browser (~10% share WW) uses the older `--webkit-box` implementation for flex layouts (http://caniuse.com/#search=flexbox). Would you consider adding that back into your autoprefixing?
