### ISSUE TITLE
Menu position not working

### ISSUE THREAD

**Issue by jkbreunig** [angular/material2#4386]
#### What is the expected behavior?
If menu button is aligned to the right side of the screen then the menu dropdown should also align on the right side of the screen.

#### What is the current behavior?
If menu button is aligned to the right side of the screen then the menu dropdown appears on the left side of the screen.

#### What are the steps to reproduce?

ng new test-menu
npm install -S @angular/material @angular/animations
Add following code to app.component.html

        <div style="display: flex; justify-content: flex-end;">
          <button [mdMenuTriggerFor]="appMenu">
           <md-icon>menu</md-icon>
        </button>
          
        <md-menu #appMenu="mdMenu" md-position-mode="target-right target">
          <button md-menu-item>Contact</button>
        </md-menu>
        </div>

ng serve

The menu button is aligned to the top right of the screen and after clicking the menu button the menu dropdown is aligned to the top left of the screen.  I was not able to reproduce this issue after creating a Plunker and adding the below code to app.component.html.  

#### What is the use-case or motivation for changing an existing behavior?
The menu dropdown should display next to the menu button on the right side of the screen.

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/cli: 1.0.0
node: 7.8.0
os: darwin x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.0

**Comment by willshowell** [comment]
Have you included a theme in your project? That's often the reason for being unable to replicate in a plunker

**Comment by jkbreunig** [comment]
That fixed it, thanks

**Comment by shadow1349** [comment]
What if I wanted to create a custom color theme? In my styles.scss I have 

```
@import '~@angular/material/theming';
@import '~@covalent/core/theming/all-theme';
@import '~@covalent/markdown/markdown-theme';
@import '~@covalent/highlight/highlight-theme';

// @import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
@include mat-core();

$my-primary-color: (
    50: #c902f0,
    100: #c902f0,
    200: #c902f0,
    300: #c902f0,
    400: #c902f0,
    500: #c902f0,
    600: #c902f0,
    700: #c902f0,
    800: #c902f0,
    900: #c902f0,
    A100: #c902f0,
    A200: #c902f0,
    A400: #c902f0,
    A700: #c902f0,
    contrast: (
        50: $black-87-opacity,
        100: $black-87-opacity,
        200: $black-87-opacity,
        300: $black-87-opacity,
        400: $black-87-opacity,
        500: white,
        600: white,
        700: white,
        800: white,
        900: white,
        A100: $black-87-opacity,
        A200: $black-87-opacity,
        A400: $black-87-opacity,
        A700: white,
    )
);

$primary: mat-palette($my-primary-color);
$accent:  mat-palette($mat-amber, A200, A400, A100);
$warn:    mat-palette($mat-red, 600, 100, 900);
$theme:   mat-light-theme($primary, $accent, $warn);

@include angular-material-theme($theme);
@include covalent-theme($theme); 
```
and I am still getting this behavior. Any suggestions?
