### ISSUE TITLE
RTL documentation missing

### ISSUE THREAD

**Issue by HarelM** [angular/material2#4387]
Breaking of #4367:
####  proposal:
RTL support exists but I could find how to use it in the documentation, I found an issue, linked to a changeset leading to the relevant code.

**Comment by MuhammadShaban** [comment]
+1

**Comment by DevVersion** [comment]
I think a guide in the `guides/` folder would be enough. cc. @EladBezalel

**Comment by EladBezalel** [comment]
@HarelM @DevVersion well, i think the basic assumption is that it works out of the box, we can use a guide that says use `dir="rtl"` on `html/body` and automatically all the components will support it

**Comment by HarelM** [comment]
True, but material 2 also supports dynamic content direction change using `[dir]=...` which is a great feature that IMHO deserves a guide/page/paragraph somewhere.

**Comment by DevVersion** [comment]
Yeah I agree that we should briefly mention that RTL support is there & how you could use it.

Also import to mention is that RTL mode doesn't work when specifying the direction from CSS.

**Comment by parker-mike** [comment]
@EladBezalel @DevVersion Well, I tried to add `dir="rtl"` on `html` and most of the components appear as expected, but when I opened a dialog it still had `dir="ltr"` on the `cdk-overlay-pane`, which means that unfortunately not _all_ the components support it.

**Comment by HarelM** [comment]
I use a variable on a service so that I can change it in one place to change all the components.
I manually add direction to all dialogs to support this, since they are not part if the "main" DOM it didn't feel weird to me.

**Comment by parker-mike** [comment]
Then, at least, it has to be well documented, currently there is no a single word about this property on the API reference page,

**Comment by EladBezalel** [comment]
When #4044 will get in it would support `html/body`, I agree we should address RTL on the docs.. next thing to do!

**Comment by parker-mike** [comment]
By the way, as per W3 [https://www.w3.org/International/tutorials/bidi-xhtml/](url) 
> Add a dir attribute to the html tag to set the default base direction of your page if it is right-to-left. Use the dir attribute on block elements within the page **_only_** where you need to change the base direction.

So in my, may not so humble, opinion, `MdDialogConfig.direction` should _**not**_ have a default value...
