### ISSUE TITLE
Dialog documentation example is not so good

### ISSUE THREAD

**Issue by HarelM** [angular/material2#4388]
Breaking of #4367:
#### Bug
Dialog example doesn't show the dialog code 
the dialog is too simple - dialog should probably include inputs and outputs.

**Comment by ryanpm40** [comment]
Just an FYI - If I'm understanding your first issue correctly, you can view the dialog code by clicking the "Edit In Plunker" icon at the top right of the example.

**Comment by HarelM** [comment]
Didn't know that, Thanks! 
But I'm sure other like me would look for it in the main page and not in the plunker example, so I believe the documentation page should include it as well...

**Comment by jelbourn** [comment]
Tracking via https://github.com/angular/material.angular.io/issues/165
