### ISSUE TITLE
Documentation for Input is too simple

### ISSUE THREAD

**Issue by HarelM** [angular/material2#4389]
Breaking of #4367:
#### feature request
Input example is so simple that it doesn't cover day-to-day cases.
What would help:
ngModule and how to use it's value in a component.
How to use multiple inputs one after the other and one by the other.
How to stretch them to full width.
It is not clear if a directive can be added to an element or needs to be an element of its own, for example: `md-input-container` vs. `mdInput` - I solve this by trail and error which is just causing me to waist time instead of focusing on my app development.
The documentation is very long here:
https://material.angular.io/components/component/input
But the example covers very little of it, more examples would help a lot since this is a very basic component and exists probably in every application.
`textarea` is mentioned but I have no idea how to make it work as it throws compilation error when used in a `md-input-container`.

**Comment by jelbourn** [comment]
I think this is resolved by the more comprehensive examples added to material.angular.io
