### ISSUE TITLE
Radio button group and boolean value 

### ISSUE THREAD

**Issue by klearchos** [angular/material2#4397]
#### Bug
The possibleAnswer.isCorrect has a boolean value. In that case all the components are rendered as selected.
If I change the isCorrect to id, then the component behaves correctly.

    <md-radio-group class="question-radio-group" *ngIf="currentQuestion" [(ngModel)]="selectedAnswer"
                    (change)="onRadioChange()">
      <md-radio-button class="question-radio-button"
                       *ngFor="let possibleAnswer of currentQuestion.possibleAnswers"
                       [value]="possibleAnswer.isCorrect">
        {{possibleAnswer.htmlAnswerTxt}}
      </md-radio-button>
    </md-radio-group>

#### What is the expected behavior?
I would expect that all the radio buttons would be initially not selected and the change event and bindings would work normally.

#### What is the current behavior?
Currently if I set the [value] to a boolean value the binding and the change event does not work at all and all the buttons are selected.

#### What are the steps to reproduce?
I simply passed an array of objects that had a boolean attribute.

#### Which versions of Angular, Material, OS, browsers are affected?
Here are my deps:
  "dependencies": {
    "@angular/animations": "^4.1.1",
    "@angular/common": "^4.1.1",
    "@angular/compiler": "^4.1.1",
    "@angular/core": "^4.1.1",
    "@angular/forms": "^4.1.1",
    "@angular/http": "^4.1.1",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.1.1",
    "@angular/platform-browser-dynamic": "^4.1.1",
    "@angular/router": "^4.1.1",
    "angular2-uuid": "^1.1.1",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },

**Comment by willshowell** [comment]
Plunker?

**Comment by klearchos** [comment]
Hi @willshowell,

I have created the plunker project and I have found the issue.
It was not related to the materialise project but it was related with the domain objects.
I was binding it to an undefined dto variable.

Sorry for the false alarm.
