### ISSUE TITLE
Proposal: Make `MdDialogConfig` generic and use type for `data` property

### ISSUE THREAD

**Issue by epelc** [angular/material2#4398]
#### Bug, feature request, or proposal:

I propose making `MdDialogConfig` a generic and use the type for the `data` property to add better type safety.

See https://github.com/angular/material2/blob/master/src/lib/dialog/dialog-config.ts#L49

Instead of using any you could do
```
class MdDialogConfig<T> {
  ...
  data?: T;
}
```
This would give better type safety on the data property.

#### What is the current behavior?
Data is type `any`

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-beta.3 cesium-cephalopod (2017-04-07)

**Comment by crisbeto** [comment]
I think that this definitely makes sense, however it'll be a breaking change. I think that we should wait with it until we start supporting TypeScript > 2.3, which introduces default values for generic parameters.
