### ISSUE TITLE
datepicker: automatic positioning 

### ISSUE THREAD

**Issue by fxck** [angular/material2#4406]
![image](https://cloud.githubusercontent.com/assets/1303561/25771306/8a611dec-324e-11e7-9963-0a7a462afee3.png)

it should open up when there's not enough space at the bottom, otherwise it's gonna be completely unaccessible

**Comment by kara** [comment]
@fxck This component is still on a feature branch, so @mmalerba probably hasn't implemented fallback positions yet.

**Comment by crisbeto** [comment]
Reassigned as discussed with @mmalerba.
