### ISSUE TITLE
Add the Ink Ripple to <md-list-item> on click

### ISSUE THREAD

**Issue by theiliad** [angular/material2#4412]
#### Bug, feature request, or proposal:
The ripple effect on list items in AngularMaterial1 is beautiful. Would be great if it was available in material2 as well.

#### What is the expected behavior?
https://material.angularjs.org/latest/demo/list

#### What is the current behavior?
No interaction/animation

#### What are the steps to reproduce?
https://material.angularjs.org/latest/demo/list

#### What is the use-case or motivation for changing an existing behavior?
The ripple effect makes for a consistent experience using an app following Material Design.

#### Which versions of Angular, Material, OS, browsers are affected?
All

#### Is there anything else we should know?
N/A

**Comment by DevVersion** [comment]
I don't think that there is an easy way to detect if a `(click)` handler is attached to the host element of an element.

Ripples currently only work inside of `md-nav-list` elements, but with #4414 ripples can be enabled for normal lists too.

**Comment by theiliad** [comment]
Thanks @DevVersion 👍 
https://github.com/angular/material2/pull/4414

**Comment by DevVersion** [comment]
Closing as this will be addressed differently (See https://github.com/angular/material2/pull/4414#issuecomment-300546740)
