### ISSUE TITLE
Snackbar not dismissing properly in async callback

### ISSUE THREAD

**Issue by xonuzofa** [angular/material2#4416]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When dismiss is called, the snackbar should close.

#### What is the current behavior?
When dismiss is called in async callback, snackbar does not close, nor does the afterDismissed callback get called until the screen is resized. As soon as I change screen size, the snackbar disappears and the afterDismissed is called.

#### What are the steps to reproduce?
Call dismiss in any async callback, does not work.

#### What is the use-case or motivation for changing an existing behavior?
Works properly inline, not async.  Want to show snackbar message of loading... until the async function completes.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.2, Material: 2.0.0-beta-2, Chrome

#### Extra
I have noticed this same problem when using angular 2 router.  If the router.navigateByUrl('next page') is called in the async callback function, the next page does not properly update/refresh page until the screen size changes.  Similar problem with calling dismiss to the snackbar inside async function, it will not update (in this case close), until the screen size changes.  Thinks its an issue with angular 2 (or 4 now), but still its affecting this module.  Seems like async breaks the detect changes.  Even using ChangeDetectorRef detectChanges() does not fix this.

**Comment by crisbeto** [comment]
Can you post a Plunkr that shows the issue? [You can use this one as a starting point.](https://goo.gl/DlHd6U)

**Comment by xonuzofa** [comment]
I created a Plunkr and it worked! Lol, I figured out it was an issue with NgZone and not detecting changes properly.  Using the zone.run fixes the issue for anyone else who is having this problem.

    generatePumpReport() {
		this.disableSummaryReport = true;

		let ref = this._snackBar.open('Job Summary Report is being generated, please wait.');

		Meteor.call('generatePDF', this.reportPump.getHtml(), 'Pump Report.pdf', 'landscape', (err, res) => {

			window.open(res);

			this._zone.run(() => {
				this.disableSummaryReport = false;

				ref.dismiss();
			});
		});
	}
