### ISSUE TITLE
md-button not firing click event in nested ngFor

### ISSUE THREAD

**Issue by kwiesmueller** [angular/material2#4419]
#### Bug, feature request, or proposal:
When nesting ngFor Loops with for example ul/li a contained md-button won't fire click events on a certain level.

#### What is the expected behavior?
The md-button should fire click events.

#### What are the steps to reproduce?
http://plnkr.co/edit/qs1brc?p=preview

#### What is the use-case or motivation for changing an existing behavior?
md-button should allow use in any case, not only in certain locations

#### Which versions of Angular, Material, OS, browsers are affected?
Tested with Version in Plunker and:
angular: ^4.0.1
material: 2.0.0-beta.2

**Comment by willshowell** [comment]
Your click events are definitely firing

```ts
  setEventDone(event: any) {
    console.log('test');
    event.done = true;
  }
```

**Comment by kwiesmueller** [comment]
Ok, that is strange... I tried with direct console.log calls in 2 different projects and no events where fired O.o. Let me check this.

**Comment by kara** [comment]
Given that the click events are firing, this doesn't look like a Material bug. If you still think something is going wrong in Material itself, please feel free to open a new issue with an updated example.
