### ISSUE TITLE
export the typography api

### ISSUE THREAD

**Issue by e-cloud** [angular/material2#4420]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
user can use the typography scss api

#### What is the current behavior?
No scss api exported, at least not exported at latest master by now

#### What are the steps to reproduce?
no

#### What is the use-case or motivation for changing an existing behavior?
control the typograhpy

related: #205 #4162

**Comment by jelbourn** [comment]
Typography is in-progress.
