### ISSUE TITLE
MdAutocomplete not filtering when using displayWith

### ISSUE THREAD

**Issue by limpep** [angular/material2#4423]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Items displayed on the panel should be filtered based on the search string

#### What is the current behavior?
Full list of items displayed 

#### What are the steps to reproduce?

Plucker example https://plnkr.co/edit/l7Vb9lmu9oUcJO3XLqXf?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?

@angular/cli: 1.0.2
node: 7.10.0
os: darwin x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.0

**Comment by willshowell** [comment]
This is a bug with your code, rather than material. Your filter is not testing against `option.name`

**Comment by limpep** [comment]
@willshowell this is not my code this is the code on the docs, here at the bottom https://material.angular.io/components/component/autocomplete

**Comment by willshowell** [comment]
Ohh I see! Yeah it should be this

```ts
filter(name: string): User[] {
  return this.options.filter(option => new RegExp(`^${name}`, 'gi').test(option.name));
}
```

**Comment by limpep** [comment]
@willshowell That works, thanks.

**Comment by willshowell** [comment]
Cool, just opened a PR to fix the docs
