### ISSUE TITLE
i found the autocomplete component  have a bug in ie11

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#4427]
i add two autocomplete components in my page, 
when the component init the first one works well when i move into the autocomplete input ,it show all the values.
but the second cann't list all the values,but when i input some words ,the filter works,and list filterd values.

**Comment by willshowell** [comment]
Plunker?

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
