### ISSUE TITLE
Grid List demo not displaying correctly in Angular docs and Plunker

### ISSUE THREAD

**Issue by skoblenick** [angular/material2#4429]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
A background color should be applied to the items in the inline grid list demo and the related Plunker

#### What is the current behavior?
No background color is applied to the items in the inline grid list demo or Plunker example

#### What are the steps to reproduce?
1.  Navigate to https://material.angular.io/components/component/grid-list
1.  The inline example for `Basic grid-list` doesn't show the background color on the divs in the basic grid layout.
1.  Opening the Plunker example doesn't have any CSS in the example resulting in no background color being applied to the div's.

#### What is the use-case or motivation for changing an existing behavior?
An example of the feature that displays correctly.

#### Which versions of Angular, Material, OS, browsers are affected?
Browser: Chrome 57.0.2987.133

#### Is there anything else we should know?
Nope.

**Comment by jelbourn** [comment]
This should be fixed now
