### ISSUE TITLE
Support [hidden] on buttons

### ISSUE THREAD

**Issue by jdell64** [angular/material2#4430]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
hidden selector should hide a button if the value is true.

#### What is the use-case or motivation for changing an existing behavior?
I am making a wizard using material design, and i need to hide my next button when I reach the last step.

#### Which versions of Angular, Material, OS, browsers are affected?
    
    "@angular/material": "git+https://github.com/angular/material2-builds.git"
    "@angular/core": "^4.0.0",

**Comment by ocarreterom** [comment]
Why not use `<button *ngIf="isLastStepCondition"></button>`?

**Comment by jdell64** [comment]
Oh wow... yeah, that will work. I was moving someone else's code around to a newer version and it wasn't working... I ended up wrapping it in a span using the `hidden` tag, but yeah, that ng-if would work.

The only thing I can think of is if you wanted it to be on the dom without showing it, but this doesn't bother me at the moment.

**Comment by ocarreterom** [comment]
You can hide with CSS using [ngStyle](https://angular.io/docs/ts/latest/api/common/index/NgStyle-directive.html) or [ngClass](https://angular.io/docs/ts/latest/api/common/index/NgClass-directive.html).

**Comment by josephperrott** [comment]
Closing as hidden is not a attribute on [HTML spec](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element) `<button>`.

As mentioned hiding can be done with *ngIf or css styling.
