### ISSUE TITLE
support mini sidenav

### ISSUE THREAD

**Issue by farley911** [angular/material2#4433]
#### Bug, feature request, or proposal:
Add support to display a mini version of the sidebar instead of completely closing it

#### What is the expected behavior?
When the sidenav is toggled instead of setting visibility to hidden and completely hiding it allow the developer to provide a min-width that remains visible.

#### What is the current behavior?
When the sidenav is toggled it is completely removed from the UI.

#### What are the steps to reproduce?
Create a sidenav and toggle it closed.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
To support the mini sidenav functionality provided in Angular Material 1

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.0 | Angular Material 2.0.0-beta.3, All OS, All Browsers

#### Is there anything else we should know?
n/a

**Comment by jelbourn** [comment]
@mmalerba do we already have an issue for this?

**Comment by mtuzinskiy** [comment]
Any updates on this?

**Comment by willshowell** [comment]
Sounds like a dupe of https://github.com/angular/material2/issues/1728
