### ISSUE TITLE
Determinate Progress Spinner should draw incomplete portion of circle

### ISSUE THREAD

**Issue by gtranter** [angular/material2#4435]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
The progress completed is shown as it currently works, with the incomplete section drawn in a different hue/color.

#### What is the current behavior?
Only the completed progress is drawn. The rest of the circle is missing.

#### What are the steps to reproduce?
https://material.angular.io/components/component/progress-spinner and set to "Determinate"

#### What is the use-case or motivation for changing an existing behavior?
I think it would look a lot better. A slow progress circle looks odd with very little completed - doesn't even look much like a circle. The progress bar follows this pattern, so there is also an issue with consistency. I think even the indeterminate variation would look better this way.

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0 beta3

**Comment by kara** [comment]
The progress spinner is implemented to match the [Material Design spec for spinners](https://material.io/guidelines/components/progress-activity.html), so this is not likely to change.

**Comment by gtranter** [comment]
But it doesn't really match the "spec" as it clearly shows a circle with the incomplete section drawn in a contrasting hue, which can't be done currently. See the first "Circular with integration" example.

**Comment by kara** [comment]
@gtranter The one you're pointing out is a specific integration with a FAB, not a normal progress circle.  See the "circular" example right above that for an example of a progress circle on its own. 
It's worth noting this also matches what was done in AngularJS Material.

**Comment by gtranter** [comment]
With the FAB it's still a progress circle. If you don't support the integration version then you haven't fully met the "spec." 

"Isn't likely" is not the same as definitely won't, so can you please keep this open as a feature request for an option? The "spec" is really just a guideline. The interpretation of the guideline is what becomes the spec which turns into an implementation, and I think this implementation has missed the boat here. It looks fine the way it is for indeterminate or for fast running progressions, but for slow progressions, such as a battery charge indicator, it really looks terrible. There are many implementations of material progress circles that draw the incomplete portion of the circle.

**Comment by kara** [comment]
We already have an issue for FAB integration with progress circle [here](https://github.com/angular/material2/issues/254). You can follow that issue if you'd like updates. 

It's our goal to build reference implementations of what's explicitly in the spec without going on too much of a tangent from what's defined. In the spec, the progress circle on its own looks like what we have, so again, this will not change.
