### ISSUE TITLE
[Tabs] Inkbar should disappear when navigating away from a tab-denoted route

### ISSUE THREAD

**Issue by rodrigjg** [angular/material2#4436]
#### Bug, feature request, or proposal:
Proposal:

When having a navigation bar that includes tabs, once the user navigates to a part of the application that is not denoted by the tabs, the inkbar should become hidden. For example say clicking on the company/website logo or text takes you to a dashboard that is not part of the tabs. The tabs part of the navbar does not have active tabs and thus the inkbar should disappear

#### What is the expected behavior?
The inkbar should disappear and the tab be deactivated when the user navigates away from a tab denoted page.

#### What is the current behavior?
When navigating to a part of the website that is not denoted by a tab the inkbar remains on the last accessed element of the tab bar.

#### What are the steps to reproduce?

-Create a nav bar that follows this:
```
<nav md-tab-nav-bar>
  <a md-tab-link
     *ngFor="let link of navLinks"
     [routerLink]="link"
     routerLinkActive #rla="routerLinkActive"
     [active]="rla.isActive">
    {{tabLink.label}}
  </a>
</nav>

<router-outlet></router-outlet>
```

-Place the above component into a toolbar component along with some other navigation elements like a dropdown menu or a button.

-Navigate to a route denoted by one of the tabs.

-Navigate to a route not denoted by one of the tabs by using the other navigation elements.

#### What is the use-case or motivation for changing an existing behavior?
The inkbar being present despite the user being on a non-tab navigated page gives the wrong impression of location on the website. The website should behave like this 

https://design.google.com/

where on the main page there is no tab inkbar but there is when the user navigates to one of the tab-denoted pages.

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 4.1.0
Material 2.0.0-beta.3

**Comment by Juchar** [comment]
Is there any workaround for this that I can implement for now?

**Comment by tmburnell** [comment]
I did this as a work around for now. do you agree this is valid?
html
```
  <nav mat-tab-nav-bar id="nav" [ngClass]="{'hide-ink-bar': hideInkBar}">
```

css
```
  .hide-ink-bar {
    > div > .mat-ink-bar {
      visibility: hidden !important;
      transition: unset;
    }
  }
```

ts
```
    ngDoCheck() {
        this.hideInkBar = nav.selectedIndex === -1? true : false;
    }
```

**Comment by rodrigjg** [comment]
This does not work when you are using the tab group as nav we can see this by just looking at what properties the MatTabNav element has from the documentation. There is no selectedIndex property unfortunately.

https://material.angular.io/components/tabs/api

**Comment by crisbeto** [comment]
Should be fixed by https://github.com/angular/material2/pull/9701.
