### ISSUE TITLE
MdInput cursor focused() is not working when it becomes visible

### ISSUE THREAD

**Issue by willSonic** [angular/material2#4439]
#### Bug, feature request, or proposal:
Not sure. Seems like a bug or perhaps I am missing something

#### What is the expected behavior?
There should be some way to, call focus() to set the cursor to input.

#### What is the current behavior?
I am able to force the MdInput to focus, but the cursor does not show up.

#### What are the steps to reproduce?
1) Sign Up Card appears with only one input box for  [Create a UserName]
2) Type in at least 5 characters and hit TAB
3) The rest of the inputs necessary to register shall appear and [Create a Password]
     gets the focus, but no cursor appears

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://embed.plnkr.co/vMOONwmfdN7K7AFga2nf/

#### What is the use-case or motivation for changing an existing behavior?

Before allowing the User to continue with Registration, I ask them to create a Unique UserName, and only after confirmation should they continue to fill out the rest of the form.  After the rest of the form appears, I am unable to find a solution to return focus/cursor control to the next input. In fact, as it stands now when the user hits tab to continue input action, the focus is placed in the Address bar. 

While it would be nice to continue to the next input box, at this point I could even work with it just being reset at the end of the username input line, so that the next TAB would take them to the password input

#### Which versions of Angular, Material, OS, browsers are affected?
angular 4.1.0
material 2.0.0-beta.3 (master)

#### Is there anything else we should know?
I have also tried creating a focus directive, but this also has not worked.  Currently, my best outcome has been, to force the input window to open using brute force with a ViewChild..
`   ngDoCheck() {
       if(!this.pwInputSet && this.usernameComplete && this.pwContainer && this.passwordInput) {
           this.pwInputSet = true;
           //this.usernameInput['_mdInputChild'].focused = true;
         // this.renderer.invokeElementMethod(this.usernameInput['_mdInputChild'].nativeElement, 'focus', []);
           //this.usernameInput.focused()
         this.pwContainer['_mdInputChild'].focused = true;
          //   setTimeout(() => {
          //       this.renderer.invokeElementMethod(this.passwordInput.nativeElement, 'focus', []);
          // }, 2000);
       }
   }`

Any Help would be so greatly appreciated..

**Comment by jelbourn** [comment]
The Angular Material inputs are just regular input elements (which have a `focus()` method); there shouldn't be anything that gets in the way of normal focus management. Looking at your plunker, I think the app is trying to advance the focus before the subsequent inputs are added to the DOM. 

Closing this since I think it's unrelated to Angular Materia, feel free to comment if there's something more specific you see as a problem.
