### ISSUE TITLE
how to resolve shasum check failed while installing @angular/material

### ISSUE THREAD

**Issue by DreamerNo7** [angular/material2#4442]
#### Bug, feature request, or proposal:
Bug

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, browsers are affected?
Windows 10

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
