### ISSUE TITLE
ng cli build --prod fails when activating noUnusedParameters in tsconfig.json

### ISSUE THREAD

**Issue by reppners** [angular/material2#4443]
#### Bug, feature request, or proposal:
Bug/Improvement

#### What is the expected behavior?
Should be able to build with `ng build --prod` when having `compilerOptions.noUnusedParameters: true` in `tsconfig.json`

#### What is the current behavior?
Build fails with 
```
ERROR in my-project/src/$$_gendir/node_modules/@angular/material/typings/index.ngfactory.ts (2252,41): 'l' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdButton.html (8,1): 'v' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdAnchor.html (8,1): 'v' is declared but never used.

ERROR in my-project/src/$$_gendir/node_modules/@angular/material/typings/index.ngfactory.ts (3345,31): 'l' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdInputContainer_Host.html (2,1): '$event' is declared but never used.

ERROR in my-project/src/$$_gendir/node_modules/@angular/material/typings/index.ngfactory.ts (4539,31): 'l' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdListItem_Host.html (2,1): '$event' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdSelect.html (23,5): '$event' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdSelect.html (2,1): '$event' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdSelect.html (15,7): '$event' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdSidenavContainer.html (2,1): '$event' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdTabGroup.html (5,3): '$event' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdTabHeader.html (2,1): '$event' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdTabHeader.html (12,3): '$event' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdTabHeader.html (20,1): '$event' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdButtonToggle.html (17,1): 'v' is declared but never used.

ERROR in my-project/src/$$_gendir/node_modules/@angular/material/typings/index.ngfactory.ts (7426,31): 'l' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.MdSlideToggle_Host.html (2,1): '$event' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.SimpleSnackBar.html (3,1): '$event' is declared but never used.

ERROR in my-project/node_modules/@angular/material/typings/index.d.ts.TooltipComponent_Host.html (2,1): '$event' is declared but never used.

```

#### What are the steps to reproduce?

* create fresh project `ng new my-project`
* install and include @angular/material as per the docs
* set `"noUnusedParameters": true` in the projects `tsconfig.json`
* run `ng build --prod`

#### What is the use-case or motivation for changing an existing behavior?
Apps using material should be able to compile with `noUnusedParameters: true` in `tsconfig.json`.

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/animations": "^4.1.0",
"@angular/common": "^4.0.0",
"@angular/compiler": "^4.0.0",
"@angular/core": "^4.0.0",
"@angular/material": "^2.0.0-beta.3",
"@angular/cli": "1.0.1",

#### Is there anything else we should know?
Looks like this is some generated code from html templates. I don't know if it's even the fault of angular material. 

The fix would be to define parameters with a leading `_`. See https://github.com/Microsoft/TypeScript/issues/9860.

**Comment by reppners** [comment]
Seems like the unused parameter issue also got some attention in the angular core recently https://github.com/angular/angular/issues/15532

Would this solve this issue also or is it just fixing the `index.ngfactory.ts`?

**Comment by DevVersion** [comment]
@jelbourn Are you thinking we should prefix those variables with an underscore? And probably compile the AOT demo-app with `noUnusedParameters` and `noUnusedLocals`.

If I recall correctly there will be a lot of locals and parameters that need to be prefixed with an underscore.

**Comment by jelbourn** [comment]
1. There's nothing we can do about unused parameters in the generated code; that's all on Angular
2. If we have any unused parameters in our own source, we should just remove them. 

Other than those two categories I don't think anything should change.

**Comment by DevVersion** [comment]
If we enable `noUnusedParameters` Material shows a lot of errors for stuff like that:

```ts
// Value is not used. Needs to be prefixed
_onChange = (value: any) => {};

/**
 * Sets the vertical placement of the tile in the list.
 * This method will be implemented by each type of TileStyler.
 * @docs-private
 */
setRowStyles(tile: MdGridTile, rowIndex: number, percentWidth: number, gutterWidth: number) {}
```

The `setRowStyles` function is not implemented and is kind of "abstract" (but other functions are implemented).

TypeScript would force us to prefix them with an underscore. Not a big deal, but just want to let you know what will change.

**Comment by jelbourn** [comment]
Function params should not be prefixed with an underscore.

If a method is abstract, it should be marked as abstract. 

For that `onChange`, it should be
```ts
_onChange: (any?) => void = () => {};
```

**Comment by DevVersion** [comment]
Yeah that makes sense. I didn't write the grid-list so I don't know why it isn't made abstract.

Most of those `noUnusedParameters` failures can be fixed easily. But I think we need a way to check this on the CI (once we fixed all of those)

**Comment by jelbourn** [comment]
Yeas, if the generated code doesn't have an issue then a CI check would be necessary.

**Comment by wulfsberg** [comment]
I think this is considerably more than a "nice to have". A library like Material should not block people from using strict compiler checks in their projects.

**Comment by jelbourn** [comment]
That priority level mainly comes from the fact that Angular's generated code is the culprit in most cases, which is outside the scope of material.
