### ISSUE TITLE
MdDialog - First Hyperlink Autofocusing

### ISSUE THREAD

**Issue by ryanpm40** [angular/material2#4448]
#### Bug, feature request, or proposal:
I do not think that hyperlinks in an MdDialog should autofocus. Please correct me if I'm wrong or if there's a known workaround.

#### What is the expected behavior?
Opening a material dialog containing a hyperlink or list of hyperlinks shouldn't focus and highlight around the first visible hyperlink.

#### What is the current behavior?
The first hyperlink in a dialog always has a highlighted box around it in Chrome.

#### What are the steps to reproduce?
Plunker: 
https://plnkr.co/edit/IqCt5ZJp5HNreQKHkGfN?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It is distracting to the user.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.2, Material 2.0.0-beta.3

**Comment by hans-pragt** [comment]
You could set  `tabindex="-1"` on both links.

**Comment by ryanpm40** [comment]
@hans-pragt Perfect, thank you! I wasn't very familiar with autofocused elements before, and just learned it's normal behavior for accessibility reasons, so I suppose this isn't really a material issue. I'll close this.

**Comment by hans-pragt** [comment]
Focus is always kinda tricky, glad I was able to help.
