### ISSUE TITLE
IE11 tooltip appears after second move on that

### ISSUE THREAD

**Issue by Somiks** [angular/material2#4456]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Should show tooltip immediately 

#### What is the current behavior?
I need to move my cursor on tooltip twice or more times.

#### Which versions of Angular, Material, OS, browsers are affected?
 "@angular/core": "~4.0.3"
"@angular/material": "2.0.0-beta.3"
IE11 11.0.9600

**Comment by donroyco** [comment]
Could you please provide a Plunker to try to reproduce the issue?

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via Plunker.

**Comment by Somiks** [comment]
Sure. Looks like there are issues with my css. Because your implementation in https://material.angular.io/ works well in IE11.

**Comment by kekel87** [comment]
I have the same problem, the tooltip is not displayed on IE11 and Edge.
In my case, the tooltip appears randomly or not at all.

Here is the plunlker to reproduce:
http://plnkr.co/edit/wbu8Dq9skq2jMAkqsyYK?p=preview

I found the solution when i was writing the plunker, the lib web-animations was misssing.
