### ISSUE TITLE
Make the Sidenav component compatible with observables and the async pipe

### ISSUE THREAD

**Issue by frederikaalund** [angular/material2#4457]
#### Bug, feature request, or proposal:
Feature/proposal

#### What is the expected behavior?
I want to be able to do:

    <md-sidenav open="sidenavOpen$ | async">
    </md-sidenav>
    <button md-button (click)="toggleSidenav()">
        Open sidenav
    </button>

    ...
    
    sidenavOpen$: Observable<boolean>;

    toggleSidenav() {
        // Something that causes sidenavOpen$ to emit a new value.
        // E.g., redux.dispatch({ type: TOGGLE_SIDENAV });
    }

#### What is the current behavior?
Currently, what I have to do is:

    <md-sidenav #sidenav>
    </md-sidenav>
    <button md-button (click)="toggleSidenav()">
        Open sidenav
    </button>

    ...

    @ViewChild('sidenav') sidenav;
    sidenavOpen$: Observable<boolean>;
    sidenavOpenSubscription: Subscription;

    ngAfterViewInit() {                                                                                  
        this.sidenavOpenSubscription = this.sidenavOpen$.subscribe((open) => {                           
            if (open) {                                                                                  
                this.sidenav.open();                                                                     
            } else {                                                                                     
                this.sidenav.close();                                                                    
            }                                                                                            
        });                                                                                              
    }
    
    ngOnDestroy() {
        this.sidenavOpenSubscription.unsubscribe();
    }

    toggleSidenav() {
        // Something that causes sidenavOpen$ to emit a new value.
        // E.g., redux.dispatch({ type: TOGGLE_SIDENAV });
    }

#### What are the steps to reproduce?
N/A

#### What is the use-case or motivation for changing an existing behavior?
Avoiding the boilerplate currently necessary to get it working.

#### Which versions of Angular, Material, OS, browsers are affected?
All. I'm using @angular/material 2.0.0-beta.3

#### Is there anything else we should know?
Generally speaking, I think that component inputs should be preferred over component methods. The motivation for this preference is the ability to use observables and the async pipe. This observable/async pattern will be (already is?) very common. Better design for it.

**Comment by willshowell** [comment]
The sidenav has an `opened` input for your use case

https://plnkr.co/edit/5KTV3Frb8LAz7w7bNpf0?p=preview

**Comment by frederikaalund** [comment]
> The sidenav has an opened input for your use case

I completely missed that. Thanks for pointing it out!
