### ISSUE TITLE
Step 4: Include a theme error

### ISSUE THREAD

**Issue by you6878** [angular/material2#4459]
#### Bug, feature request, or proposal:

It was annoying when I started Material in angular/cli that version 4
I tried following getting-started.md at guides material2

It was occurring error when I used Step 4: Include a theme
It say use the <link href="../node_modules/@angular/material/prebuilt-themes/indigo-pink.css" rel="stylesheet"> but I doesn't work therefore I motified to code @import '~@angular/material/prebuilt-themes/deeppurple-amber.css' at styles.css and remove <link href="node_modules/@angular/material/prebuilt-themes/indigo-pink.css" rel="stylesheet">

Maybe I think It is not important for you. I want to follow getting-started page perfectly

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
