### ISSUE TITLE
Proposal: support dense menus

### ISSUE THREAD

**Issue by willshowell** [angular/material2#4463]
#### Bug, feature request, or proposal:
Proposal

#### Motivation
The spec mentions dense menu items

![screen shot 2017-05-10 at 10 07 51 am](https://cloud.githubusercontent.com/assets/6475576/25902764/7cc0f096-3568-11e7-9ce3-abf6ce7bfd7a.png)
> **Default desktop menu**
Menu item height: 32px
Menu item text left padding: 24px
Top padding: 8px
Bottom padding: 8px
Typography: 15px

![screen shot 2017-05-10 at 10 08 01 am](https://cloud.githubusercontent.com/assets/6475576/25902780/871b711a-3568-11e7-918b-1b2ee886d7a1.png)

> **Dense desktop menus**
Menu item height: 24px
Menu item text left padding: 24px
Top padding: 4px
Bottom padding: 4px
Typography: 13px

#### Other
Related comment https://github.com/angular/material2/pull/4115#issuecomment-294531329. I think, still, that this could be added without waiting on a library-wide density overhaul, as it would primarily be putting the styles in place.

**Comment by willshowell** [comment]
Related #4597

**Comment by jelbourn** [comment]
Closing this to track via #4597 (which we intend to do sometime after beta ends)
