### ISSUE TITLE
Placeholder not floating properly in IE 11 if css color is added to .mat-input-element

### ISSUE THREAD

**Issue by AAAnderson7301** [angular/material2#4464]
#### Bug, feature request, or proposal:
Bug Report IE 11 

#### What is the expected behavior?
If no value in input and placeholder forced to float should be no text in input

#### What is the current behavior?
if a color property is added to .mat-input-element the placeholder floats but still shows a placeholder in the input field as well. 

#### What are the steps to reproduce?
Open the plunker in IE 11 and compare to Chrome. It is only one input field. 

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

http://plnkr.co/edit/ujdRfTcrFgEgNL08D8Ba?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I need to display an input form that can be disabled at times and the font color for disabled is hard to read at times.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 4.x, Material: Latest merge at Master, Windows 10, IE 11

**Comment by AntiCZ** [comment]
I dont understand why input has attr placeholder(In browser after render).
