### ISSUE TITLE
Make FocusKeyManager part of the public API

### ISSUE THREAD

**Issue by passelin** [angular/material2#4470]
#### Bug, feature request, or proposal:

While implementing a custom menu, I've found out that FocusKeyManager provides the functionality I need to implement keyboard navigation. However, it seems this class is not part of the public API. Since it seems to be a useful and reusable piece, I was wondering if this was an omission or if it was intentionally out of the public eye.

#### What is the expected behavior?

```
import { FocusKeyManager } from '@angular/material';
```

#### What is the current behavior?

```
import { FocusKeyManager } from '@angular/material';
                                                           ^-- has no exported member 'FocusKeyManager'
```

#### What is the use-case or motivation for changing an existing behavior?

The FocusKeyManager can be used outside of Material components and could be part of the CDK offering.

#### Which versions of Angular, Material, OS, browsers are affected?

@angular/material 2.0.0-beta.3

**Comment by jelbourn** [comment]
We plan on making this available as part of the cdk

**Comment by jelbourn** [comment]
This is available now
