### ISSUE TITLE
mdInput  required indicator, is there any way to replace the default?

### ISSUE THREAD

**Issue by uredkar** [angular/material2#4472]
#### Bug, feature request, or proposal:
The required red indicators look really thick and ugly

#### What is the current behavior?

![image](https://cloud.githubusercontent.com/assets/5139003/25928441/ecbec75c-35c1-11e7-846a-6e6304fda890.png)

#### What are the steps to reproduce?
<md-card class="demo-card demo-basic">
    <md-toolbar color="primary">Error messages</md-toolbar>
    <md-card-content>
        <h4>Regular</h4>
        <p>
            <md-input-container>
                <input mdInput placeholder="example" [(ngModel)]="errorMessageExample1" required>
                <md-error>This field is required</md-error>
            </md-input-container>
            <md-input-container>
                <input mdInput placeholder="email" [formControl]="emailFormControl">
                <md-error *ngIf="emailFormControl.hasError('required')">
                    This field is required
                </md-error>
                <md-error *ngIf="emailFormControl.hasError('pattern')">
                    Please enter a valid email address
                </md-error>
            </md-input-container>
        </p>
        <h4>With hint</h4>
        <md-input-container>
            <input mdInput placeholder="example" [(ngModel)]="errorMessageExample2" required>
            <md-error>This field is required</md-error>
            <md-hint>Please type something here</md-hint>
        </md-input-container>

        <form novalidate>
            <h4>Inside a form</h4>
            <md-input-container>
                <input mdInput name="example" placeholder="example"
                       [(ngModel)]="errorMessageExample3" required>
                <md-error>This field is required</md-error>
            </md-input-container>
            <button color="primary" md-raised-button>Submit</button>
        </form>
    </md-card-content>
</md-card>
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
The indicator should be a simple bar and should be configurable

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0

#### Is there anything else we should know?
I am using the latest git version of the this library

**Comment by donroyco** [comment]
Can you please provide a Plunker to try to reproduce the issue. What browsers are affected? Please update your issue with both things.

**Comment by uredkar** [comment]
It is does not appear to be an issue with material, but was caused by the following css in my project.

    .ng-invalid:not(form) {
      border-left: 2px solid #a94442;
    }

 
https://plnkr.co/edit/DUjWb2ej2427sG74A9J3?p=preview
