### ISSUE TITLE
You have to be inside an angular-cli project in order to use the serve command.

### ISSUE THREAD

**Issue by lh1991** [angular/material2#4474]
#### Bug, feature request, or proposal:
You have to be inside an angular-cli project in order to use the serve command.

#### What is the expected behavior?
Please provide any solutions to run this project so that i can see the  components on the page.!!

#### What is the current behavior?
But it shows me the "You have to be inside an angular-cli project in order to use the serve command."

#### What are the steps to reproduce?
First i git clone https://git.oschina.net/mumu-osc/NiceFish
After npm install -g angular-cli.
Then npm install
Last ng serve --prod --aot
appear:As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

You have to be inside an angular-cli project in order to use the serve command.

**Comment by Chan4077** [comment]
Did you follow the [guide for a development environment](https://github.com/angular/material2/blob/master/DEV_ENVIRONMENT.md)? It specifically states this:

> 1. Make sure you have node installed with a version at least 5.5.0.
> 2. Run npm install -g gulp to install gulp.
> 3. Fork the angular/material2 repo.
> 4. Clone your fork. Recommendation: name your git remotes upstream for angular/material2 and <your-username> for your fork. Also see the team git shortcuts.
> 5. From the root of the project, run npm install.

and...

> To bring up a local server, run gulp serve:devapp. This will automatically watch for changes and rebuild. The browser should refresh automatically when changes are made.

**Comment by kara** [comment]
It sounds like you are cloning down a completely different project. If you want to run the demo app for this project, follow the instructions in the guide (linked in @Chan4077's comment). Since this is a question and possibly not related to Material, closing.
