### ISSUE TITLE
Menu, autocomplete, and datepicker should remove CSS classes from inert panel element

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#4484]
If you have 
```html
<md-menu #options class="borange">
  ...
</md-menu>
```

The css classes are [copied](https://github.com/angular/material2/blob/master/src/lib/menu/menu-directive.ts#L96) to the panel element inside the overlay. However, the classes _also_ remain on the empty `<md-menu>` element in the page. We should remove all classes from the `md-menu` element. 

This behavior should apply to menu, autocomplete, and datepicker.

**Comment by sabithpocker** [comment]
Does this affect `md-basic-chip` as well? I had a similar problem when using `class` with `md-basic-chip` but worked fine when `ng-class` was used instead.

[Issue](https://github.com/angular/material2/issues/4437)
