### ISSUE TITLE
Select should have an input for panelClass

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#4485]
There is no way to apply a CSS class to the panel part of the select; we should add an input for this.

**Comment by king612** [comment]
Yes, please!  On _several_ components, inner elements are generated on the flay to provide all the nice features, but this makes something as basic as overriding a CSS style a nightmare.  I'm having to do all kinds of contortions in CSS just to style something as basic as a select or a date picker.  So bad I'm considering switching frameworks.  We have to be able to apply our own styles.
