### ISSUE TITLE
close dialogue when the escape button is pressed

### ISSUE THREAD

**Issue by httpsOmkar** [angular/material2#4492]
#### feature request
Dialogue should be close when the escape button is pressed

#### What is the use-case or motivation for changing an existing behavior?
It is useful for the small dialogue like messages. and its improves the accessibility of the application.

**Comment by crisbeto** [comment]
This should be the case already. Do you have an example where it doesn't work?

**Comment by kara** [comment]
Are you using an older version of Material? In beta.3, the escape key should close the dialog. It seems to be working [on our docs demo](https://material.angular.io/components/component/dialog).

If you still think this isn't the case for you, please open a new issue with a plunker repro. As it stands, there's not enough for us to look into this.
