### ISSUE TITLE
mdInput with label and empty value - placeholder overlaps

### ISSUE THREAD

**Issue by HarelM** [angular/material2#4494]
#### Bug, feature request, or proposal:
Bug, I'm pretty sure it's a duplication, but I couldn't find exactly the scenario I'm facing.

#### What is the expected behavior?
Placeholder should not overlap with label text of the input.

#### What is the current behavior?
![image](https://cloud.githubusercontent.com/assets/3269297/25996567/9d2bdb84-3720-11e7-97b1-e61420f8e488.png)

#### What are the steps to reproduce?
Create an input with label in a container with no initial value.
https://plnkr.co/edit/TLNaGPiGL8ft8xCed0LV?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It looks really bad...

#### Which versions of Angular, Material, OS, browsers are affected?
angular 4.0.3
material 2.0.0-beta.3

#### Is there anything else we should know?
I saw a pull request related to this with the same screen shot, don't know what's the current status of this.

**Comment by mmalerba** [comment]
The way it is currently implemented, the label and placeholder are the same thing. There is a new version of the material design spec that allows for both, but that has not been implemented yet (see https://github.com/angular/material2/issues/3984). 

If you inspect the output of:
```html
<md-input-container>
  <input mdInput placeholder="Favorite food" value="Sushi">
</md-input-container>
```
You'll see that it does have a label with the text "Favorite food"
