### ISSUE TITLE
md-select position change in fixed top header

### ISSUE THREAD

**Issue by dharveshmydeen** [angular/material2#4498]
#### Bug, feature request, or proposal:
I set md-select at top of the page as position fixed
It is working fine at default position
when i scroll my page and click md-menu it open in another position (out of my page)
#### What is the expected behavior?
Is there any position i have to define ...?

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by willshowell** [comment]
Can you please replicate in a plunker? And have you included a theme? (often a cause of menu position errors)

**Comment by kara** [comment]
Yeah, it sounds like you may be missing our core styles / theme. Without a plunker, it's hard for us to look into this. Can you double-check that you've included a theme, and if you have and still think it's a Material bug, please open a new issue with a plunker repro.
