### ISSUE TITLE
links not working inside md-nav-list with secondary action 

### ISSUE THREAD

**Issue by ocarreterom** [angular/material2#4514]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Navigate to link.

#### What is the current behavior?
Can not navigate to link inside `md-nav-list` with secondary action.
Side effect from https://github.com/angular/material2/pull/4426?

#### What are the steps to reproduce?
Demo: http://plnkr.co/edit/JWpZfCTwJAGCZPSOt9aN?p=preview

#### Is there anything else we should know?
angular/material: 2.0.0-beta.4

**Comment by willshowell** [comment]
Maybe #4503 will fix this? 
cc @DevVersion

**Comment by jelbourn** [comment]
Yeah, https://github.com/angular/material2/pull/4503 should fix. We'll do a beta.5 pretty quickly to get this in.

**Comment by willshowell** [comment]
This can be closed, correct?

**Comment by jelbourn** [comment]
Yep, should be fixed now.
