### ISSUE TITLE
MdNativeDateModule has no exported member

### ISSUE THREAD

**Issue by axtho** [angular/material2#4521]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should be importable

#### What is the current behavior?
Not importable
Error:(32, 5) TS2305:Module '"./web/node_modules/@angular/material/material"' has no exported member 'MdNativeDateModule'.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.0.3
node: 7.8.0
os: darwin x64
@angular/animations: 4.1.2
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/material: 2.0.0-beta.4
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.2
@angular/platform-server: 4.1.2

TS 2.2.1

#### Is there anything else we should know?
Looking forward to work the datepicker

**Comment by mattheiler** [comment]
Get the latest master build:

```@angular/material": "git+https://github.com/angular/material2-builds.git```

**Comment by julianobrasil** [comment]
I tried the docs (material.angular.io) way to change de display formats (I'd like to display dates as ddMMyyyy) without success. But as the docs appear to be under construction, maybe it's too soon to try anything. I'll wait a few days to try again.

**Comment by hudovisk** [comment]
I'm having the same problem
`
@angular/material/index"' has no exported member 'MdNativeDateModule'
`
```json  
"dependencies": {
    "@angular/common": "2.4.9",
    "@angular/compiler": "2.4.9",
    "@angular/core": "2.4.9",
    "@angular/flex-layout": "2.0.0-rc.1",
    "@angular/forms": "2.4.9",
    "@angular/http": "2.4.9",
    "@angular/material": "2.0.0-beta.2",
    "@angular/platform-browser": "2.4.9",
    "@angular/platform-browser-dynamic": "2.4.9",
    "@angular/router": "3.4.9",
    "@swimlane/ngx-datatable": "6.3.0",
    "angular-calendar": "0.8.0",
    "angular2-fontawesome": "^0.9.0",
    "angular2-google-maps": "0.17.0",
    "angular2-jwt": "^0.2.0",
    "angular2-tree-component": "3.1.0",
    "bootstrap": "^3.3.7",
    "chart.js": "2.5.0",
    "core-js": "2.4.1",
    "d3": "4.5.0",
    "dragula": "3.7.2",
    "font-awesome": "^4.7.0",
    "hammerjs": "2.0.8",
    "intl": "1.2.4",
    "leaflet": "^1.0.2",
    "moment": "^2.15.0",
    "ng2-charts": "1.5.0",
    "ng2-dragula": "1.3.0",
    "ng2-file-upload": "1.2.0",
    "ng2-translate": "5.0.0",
    "ng2-validation": "3.8.0",
    "perfect-scrollbar": "^0.6.16",
    "quill": "1.2.2",
    "rxjs": "5.2.0",
    "screenfull": "^3.0.2",
    "showdown": "1.6.4",
    "zone.js": "0.8.9"
  },
```

**Comment by tcrack326** [comment]
same here

**Comment by axtho** [comment]
The combination of pulling the latest master branch via  `"@angular/material": "https://github.com/angular/material2-builds.git"` and using Typescript 2.3.x has resolved the issue for me (was using the master branch anyway until a few days ago, when the problem occurred).

**Comment by govardhan-s92** [comment]
+1

**Comment by linuradu** [comment]
@axtho 
Did you upgraded to "@angular/material": "2.0.0-beta.5"; 
As I see this version is requiring Angular 4. Are you using also Angular 4?

I have the same issue "TS2305:Module '"./web/node_modules/@angular/material/material"' has no exported member 'MdNativeDateModule'." with:
"dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/material": "2.0.0-beta.2",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@angular/router": "3.4.8",
    "@types/lodash": "^4.14.64",
    "ag-grid": "9.0.0",
    "ag-grid-angular": "9.0.0",
    "angular-in-memory-web-api": "0.2.4",
    "bootstrap": "3.3.6",
    "core-js": "2.4.1",
    "hammerjs": "2.0.8",
    "jquery": "3.1.1",
    "lodash": "4.17.4",
    "material-design-lite": "1.3.0",
    "md2": "0.0.13-1",
    "moment": "2.18.1",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "zone.js": "0.7.7"
  },

Does someone resolve this issue without using Angular 4?

**Comment by axtho** [comment]
@linuradu yes, forgot to mention that. I am on angular@latest, the same for the cli and everything else. I was just using TS 2.2.1, with the switch to 2.3.x (and pulling the latest code from master branch of Material2) I could solve this issue.

Here is my deps:

```
"dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "https://github.com/angular/material2-builds.git",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/db": "^2.0.2",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/router-store": "^1.2.6",
    "@ngrx/store": "^2.2.1",
    "angular2-moment": "^1.2.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "material-design-icons": "^3.0.1",
    "ng2-dragula": "1.3.1",
    "ng2-img-cropper": "^0.8.8",
    "ng2-webstorage": "^1.5.0",
    "ngrx-store-freeze": "^0.1.6",
    "ngrx-store-logger": "^0.1.7",
    "reflect-metadata": "^0.1.3",
    "reselect": "^3.0.0",
    "roboto-fontface": "^0.7.0",
    "rxjs": "^5.2.0",
    "tinymce": "^4.5.5",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@ngrx/store-devtools": "^3.2.2",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.5.38",
    "@types/node": "^7.0.12",
    "@types/tinymce": "^4.5.4",
    "codelyzer": "^3.0.1",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "^3.0.0",
    "tslint": "^5.2.0",
    "typescript": "~2.3.1",
    "yarn-run-all": "^3.1.1"
  }
```

**Comment by linuradu** [comment]
Hi @axtho 
Thank you! with the following configuration for me now, is working fine :)
"dependencies": {
    "@angular/animations": "4.1.0",
    "@angular/common": "4.1.0",
    "@angular/compiler": "4.1.0",
    "@angular/compiler-cli": "4.1.0",
    "@angular/core": "4.1.0",
    "@angular/forms": "4.1.0",
    "@angular/http": "4.1.0",
    "@angular/material": "2.0.0-beta.5",
    "@angular/platform-browser": "4.1.0",
    "@angular/platform-browser-dynamic": "4.1.0",
    "@angular/platform-server": "4.1.0",
    "@angular/router": "4.1.0",
    "@types/lodash": "^4.14.64",
    "ag-grid": "9.0.0",
    "ag-grid-angular": "9.0.0",
    "angular-in-memory-web-api": "0.3.2",
    "bootstrap": "3.3.6",
    "core-js": "2.4.1",
    "hammerjs": "^2.0.8",
    "jquery": "3.1.1",
    "lodash": "4.17.4",
    "material-design-lite": "1.3.0",
    "md2": "0.0.19",
    "moment": "2.18.1",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "zone.js": "0.8.4"
  },

**Comment by jelbourn** [comment]
Should be resolved in the latest release
