### ISSUE TITLE
Show progress-circle percentage inside the circle (feature request)

### ISSUE THREAD

**Issue by rsnider19** [angular/material2#453]
**Note: for support questions, please use one of these channels:**
https://github.com/angular/material2/blob/master/CONTRIBUTING.md#question.
This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the expected behavior?**
As the progress circle fills up based on `[value]`, have the option to display that percentage in the middle of the circle.

* **What is the motivation / use case for changing the behavior?**
Potentially gives the user a better understanding of what the determinate circle us doing.

**Comment by jelbourn** [comment]
I consulted with the Material Design UX team and their answer was that it's off-spec to have text inside of the progress-circle, so we're going to omit it from our implementation for now.

**Comment by jelbourn** [comment]
On second though, Material UX says it's not off-spec. That said, this is really low on the priority list for us, such that I don't think we'd get to it for quite a while. At such a low priority, it's probably more honest to close the issue than to leave it open indefinitely.

**Comment by rsnider19** [comment]
Ok, that's fine. I'll take a stab at it and see what I can do!
