### ISSUE TITLE
Some documentation still references the removed 'MaterialModule'

### ISSUE THREAD

**Issue by alexjlockwood** [angular/material2#4532]
For example here: https://github.com/angular/material2/blob/master/src/lib/dialog/dialog.md

**Comment by DevVersion** [comment]
Thanks. We definitely need to switch all other instances of `MaterialModule` as well.

Not sure it would make sense to expose [this](https://github.com/angular/material2/blob/master/src/lib/module.ts#L40) variable so we can use it for the `e2e-app` and `demo-app`.

To make sure that no developer accidentally tries to use the exposed array of modules, we could prefix it with something special.
