### ISSUE TITLE
Remove month name in calendar view

### ISSUE THREAD

**Issue by davidgabrichidze** [angular/material2#4537]
Allow developers to choose - show or hide duplicated month name. Result will be this:
![image](https://cloud.githubusercontent.com/assets/12189125/26028683/b34c9842-3836-11e7-930d-3ea47c75e777.png)

Currently there is short name of month between narrowed day names and dates:
![image](https://cloud.githubusercontent.com/assets/12189125/26028663/805657ca-3836-11e7-9a4b-dd94937cbb40.png)

**Comment by fxck** [comment]
I still fail to understand what is it there for in the first place.

**Comment by jelbourn** [comment]
A more recent iteration of the spec (still not publicly released, unfortunately) has the month inside of the alendar removed.

**Comment by mmalerba** [comment]
will be addressed as part of #5974 and #5973
