### ISSUE TITLE
Bug: Md-Tab-Nav-Bar active link no longer underlined.

### ISSUE THREAD

**Issue by viztastic** [angular/material2#4546]
#### Bug, feature request, or proposal:

Bug.

#### What is the expected behavior?

When a tab routLink is activated, it should display an underline. I would have also thought the text color should be 'white' against a dark background.

#### What is the current behavior?

No underline is displayed.

#### What are the steps to reproduce?

See plunker here: http://plnkr.co/edit/wW6TZJ8EiLvTz1FFXPvv?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It used to work out of the box, I also tried to implement a custom underline previously using this CSS and this no longer works:

```
.md-tab-link {
  border-bottom-width: 5px;
}

md-toolbar nav {
  border-bottom: 0px;
  color: #FFFFFF !important;
}

.mat-tab-link {
  opacity: 1 !important;
}
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Mac OS X El Capitan
Google chrome

```json
  "dependencies": {
    "@angular/animations": ">=4.0.0 <5.0.0",
    "@angular/common": ">=4.0.0 <5.0.0",
    "@angular/compiler": ">=4.0.0 <5.0.0",
    "@angular/core": ">=4.0.0 <5.0.0",
    "@angular/flex-layout": "v2.0.0-beta.8",
    "@angular/forms": ">=4.0.0 <5.0.0",
    "@angular/http": ">=4.0.0 <5.0.0",
    "@angular/material": "^2.0.0-beta.5",
    "@angular/platform-browser": ">=4.0.0 <5.0.0",
    "@angular/platform-browser-dynamic": ">=4.0.0 <5.0.0",
    "@angular/router": ">=4.0.0 <5.0.0",
    "@ngui/map": "^0.18.0",
    "angular2-jwt": "^0.2.3",
    "apollo-angular": "^0.13.0",
    "apollo-client": "^1.1.2",
    "chart.js": "^2.5.0",
    "core-js": "^2.4.1",
    "graphql": "^0.9.6",
    "graphql-tag": "^2.0.0",
    "graphql-tools": "^0.11.0",
    "ng2-charts": "^1.5.0",
    "rxjs": "^5.3.1",
    "zone.js": "^0.8.8"
  }
```

**Comment by willshowell** [comment]
See this updated plunk: http://plnkr.co/edit/LSakjsgj0nd6x8mJzBAl?p=preview

A couple of things I noticed:
1. You were trying to match `routerLinkActive` against `'/home'` when the route was `'/'`
2. If you want to instead match against `'/'` and `'/contact'`, you'll have to use exact match options

I know that doesn't solve all the color concerns you have, but should demo why you weren't seeing the link underlined.

**Comment by viztastic** [comment]
@willshowell Thanks for the feedback, I've updated the plunker for it to be more explicit about the problem I'm trying to highlight.

Previously, even if I visited `home/about` the tab would show the `home` tab as active. Now this doesn't work. Hopefully the updated plunker illustrates both the color and underline issues more clearly.

**Comment by willshowell** [comment]
Hmm so when the route is `/about`, are you expecting _both_ the "home" (`/`) and "about" (`/about`) tabs to show an underline?  It seems nav-tabs are limited to only one active tab at a time.

If that's not the issue, then it could just be a matter of running a custom route matcher to pass into the tab-link's `[active]` attribute.

Finally, I'd consider opening a separate proposal about being able to invert the color scheme (for use on top of toolbars) as it seems to be unrelated to the underline/route matching issue.

**Comment by qorsmond** [comment]
What i did is used this css to display the underline when my toolbar color is set to `color="primary"`:

`nav .mat-ink-bar {
  background-color: white;
}`

But my question is what is the correct approach for when you want to show a Md-Tab-Nav-Bar in a Md-Toolbar. I think if the  Md-Tab-Nav-Bar also had a color attribute that you could set to `color="accent"` it could work nice.

**Comment by jelbourn** [comment]
AFAICT everything is working as intended. The tab-nav doesn't support having multiple active tabs at once (intentional). If you have a more specific bug, feel free to open a new issue.
