### ISSUE TITLE
md-list-item in <a> tag + long description (md-2-line ?)

### ISSUE THREAD

**Issue by mist3r3** [angular/material2#4550]
#### Bug, feature request, or proposal:
When having a <a> tag as a md-list-item (i.e <a md-list-item>) and a button inside with an event, it first fires the event of the button then goes to the path of the <a> tag

#### What is the expected behavior?
Only firing the button event.

#### What is the current behavior?
It fires both event (the <a> path and the button).

#### What are the steps to reproduce?
http://plnkr.co/edit/YsZR4BwZFLZvV74en9F4?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Gives possibility to add button to a list.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

#### Is there anything else we should know?
I've seen a bug for the list fixed into the beta.5 but it didn't improve anything for me.

**Comment by mist3r3** [comment]
I've added a plunker here! I believe this is way more simple like that.

**Comment by willshowell** [comment]
I wonder if this is something that should be supported out of the box. As a workaround, you could use `preventDefault()` to keep the click event from bubbling up to the anchor element

http://plnkr.co/edit/dDxySwiO7xJ4DHtODSFL?p=preview

Note that I also added `stopPropagation()` so that clicking the edit button doesn't trigger a ripple on the whole list item.

**Comment by mist3r3** [comment]
Hi and thank you for your answer ! it seems that in your plunkr the href isn't working anymore... Does it work for you?

**Comment by willshowell** [comment]
It logs an error because the frame doesn't want to navigate away, but that's the nature of using plunker. This should work (tested Chrome/FF/Safari):

http://run.plnkr.co/plunks/dDxySwiO7xJ4DHtODSFL

**Comment by mist3r3** [comment]
That's great it works with the href. Do you know how to make it work with routerlink? Because it doesn't have the same behavior.

**Comment by willshowell** [comment]
Oh oops, use both of these in your click callback 

```ts
event.stopPropagation();
event.preventDefault();
```

**Comment by mist3r3** [comment]
hi, yes that's what I did, it works great ! 👍  But I guess it shoul be supported ootb no ?

**Comment by jelbourn** [comment]
It is invalid to place a button inside of an anchor. The nav-list is intended to be used in situations where the _entire_ action of each list item is a navigation (with no sub actions allowed). For more custom scenarios, the normal `<md-list>` should be used with each item containing whatever anchors and buttons you want.
