### ISSUE TITLE
at MdInputContainer._isErrorState

### ISSUE THREAD

**Issue by keyeMyria** [angular/material2#4551]
at MdInputContainer._isErrorState (material.es5.js:15396)

ERROR TypeError: Cannot read property '_ngControl' of undefined
the code is here:
https://github.com/keyeMyria/bookingmanagement/tree/material2

and after run acess: http://localhost:4400/session/signin/
errors show.

**Comment by crisbeto** [comment]
@keyeMyria you're probably getting that error, because you haven't added `mdInput` on your inputs here: https://github.com/keyeMyria/bookingmanagement/blob/material2/src/app/session/signin/signin.component.html#L14. That being said, we should probably throw a better error beforehand.
