### ISSUE TITLE
Feature request: Dense toolbars on desktop

### ISSUE THREAD

**Issue by HoumanKml** [angular/material2#4553]
#### Bug, feature request, or proposal:
Feature request: Dense app bar on desktop

#### What is the expected behavior?
If a 'dense' prop is provided for the md-toolbar, the app bar height will default to 48px instead of 64px on desktops. Per [material design guidelines](https://material.io/guidelines/layout/structure.html#structure-app-bar):

*Density*
When the mouse and keyboard are the primary input methods, measurements may be condensed to accommodate denser layouts.

- App bar height: 48dp
- App bar left and right content padding: 24
- App bar left content padding: 80dp
- Icon height with touch target: 40dp

#### What is the current behavior?
The app bar defaults to min-height 64px for desktops/laptops per material spec.

#### What is the use-case or motivation for changing an existing behavior?
By convention most websites use a value less than 64px on desktops (Github, material.angular.io, etc.) as 64px is somewhat unsightly and takes too much space without adding much functionality when the main input method is a mouse

**Comment by fxck** [comment]
FYI https://github.com/angular/material2/pull/4115#issuecomment-294531329

**Comment by HoumanKml** [comment]
@fxck I see, thanks.

Just to confirm, [attr.dense]="dense" does nothing for the app bar, right? Do we have an ETA for the density support?

**Comment by willshowell** [comment]
@HoumanKml correct. Only lists support density at the moment.

**Comment by jelbourn** [comment]
Created #4597 to formally track this.
