### ISSUE TITLE
Sidenav animation janky

### ISSUE THREAD

**Issue by ruffiem** [angular/material2#4556]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Same as sidenav in 2.0.0-beta.3

#### What is the current behavior?

Sidenav animation is jerky and occurs while after clicking on toggle.

#### What are the steps to reproduce?

On the picture below, each peek represent a click on the sidenav toggle button. It takes up to 1600ms to start the animation.

![screen shot 2017-05-15 at 11 02 59](https://cloud.githubusercontent.com/assets/1785492/26050273/46edc80a-395e-11e7-9329-edba66343eae.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4.1.1, Material 2.0.0-beta.5, OS X Sierra, TS 2.2.0, Chrome latest

**Comment by DevVersion** [comment]
Are you sure it's a memory leak? 

I thought it may be because of the ripples that are calling `getBoundingClientRect()` on mousedown.

**Comment by mmalerba** [comment]
This should be fixed now
