### ISSUE TITLE
MdInput Placeholder Text blurry using in Md-Card-Content in Chrome

### ISSUE THREAD

**Issue by elvirdolic** [angular/material2#4558]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Text is not blurry

#### What is the current behavior?
If you put md-input-container in a md-card-content block then the text is blurry

#### What are the steps to reproduce?
See plunker

http://plnkr.co/edit/v8MNM2CvFeT3GrXv43uV?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: Beta-5
Windows 8.1
Chrome: Version 58.0.3029.110 (64-bit)

#### Is there anything else we should know?
![image](https://cloud.githubusercontent.com/assets/17769458/26055896/1d1798f2-3973-11e7-9ca0-129f1caf6d74.png)

**Comment by donroyco** [comment]
@elvirdolic What OS are you running? I can't reproduce this on macOS Sierra with retina display.

**Comment by elvirdolic** [comment]
Windows 8

**Comment by shavenwalrus** [comment]
I have same issue on Windows 10, Chrome 57.0.2987.110 (64-bit)

**Comment by elvirdolic** [comment]
What I have found out is that this is happening when using translate3d

.mat-focused .mat-input-placeholder.mat-float, .mat-input-placeholder.mat-float:not(.mat-empty)

translateY(-1.35em) scale(.75)

![image](https://cloud.githubusercontent.com/assets/17769458/26141968/bbb6e30c-3ade-11e7-8743-e328b55bd542.png)

translate3d(0, -1.35em, 0) scale(.75)

![image](https://cloud.githubusercontent.com/assets/17769458/26141972/c390f3ba-3ade-11e7-93b4-7d12743cb25a.png)
