### ISSUE TITLE
md-autocomplete error - Invalid regular expression unterminated group or end of pattern

### ISSUE THREAD

**Issue by MaxKorolkov** [angular/material2#4559]
#### Bug, feature request, or proposal:
I used md-autocomplete from this gide - https://material.angular.io/components/component/autocomplete

#### What is the expected behavior?
When i writing this symbols '\/()' i've got console.error ' Invalid regular expression: {my value}: at end of pattern'  or 'Invalid regular expression: {my value}: Unterminated group' 
My application is being stopped because of this.

#### What are the steps to reproduce?
I need a solution without errors

#### What is the use-case or motivation for changing an existing behavior?
It's strange, bit this example https://material.angular.io/components/component/autocomplete causes an error in a similar case too

**Comment by willshowell** [comment]
See #4440

**Comment by MaxKorolkov** [comment]
@willshowell  Good! it's work if i don't use RegExp

**Comment by willshowell** [comment]
Should be closed via https://github.com/angular/material2/pull/4921

**Comment by crisbeto** [comment]
Should be resolved in master.
