### ISSUE TITLE
md-datepicker default year policy (currently defaults 2001)

### ISSUE THREAD

**Issue by arlowhite** [angular/material2#4566]
#### Bug, feature request, or proposal:

MdDatepicker should have good default year selection behavior.
BONUS: Developers should be able to specify how default year is chosen.

#### What is the expected behavior?

1. User types date text without year, e.g. "jan 5", "1/5"
2. MdDatepicker should default to current year, or maybe the year of closest January.

More complex, but it would be nice to be able to configure a policy:

- DatepickerYearPolicy.currentYear - always default yearless date input to the current year
- DatepickerYearPolicy.closestYear - always default yearless date input to the closest year, past or future
- DatepickerYearPolicy.pastYear - never default to a date in the future, all default years must result in a date in the past

#### What is the current behavior?

MdDatepicker always defaults year to 2001. I think this is default JavaScript behavior? Moment does it too.

#### What are the steps to reproduce?

https://material.angular.io/components/component/datepicker
Type date text without a year, open the date picker. Year will be 2001.

#### What is the use-case or motivation for changing an existing behavior?

Defaulting to 2001 is unexpected and not helpful.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

N/A

#### Is there anything else we should know?

In my custom datepicker code, this is how I detect the issue; not sure if there's a better way.
Year is 2001 and user did not explicitly enter "2001" within input.
`if (m.year() === 2001 && inputValue.indexOf('2001') === -1)`
(Moment API)

**Comment by jelbourn** [comment]
This is the behavior of JavaScript's native date parsing. (Try `new Date('1/1')` in your console). We don't expect anyone to use the default `NativeDateAdapter` for any real application, instead using a full date i18n solution like moment.js or Google's Closure library. Ultimately building a date i18n solution is out of scope for Angular Material, so we defer the implementation to user-space.
