### ISSUE TITLE
Demo App AOT does not using platformBrowser but uses platformBrowserDynamic instead

### ISSUE THREAD

**Issue by josephperrott** [angular/material2#4576]
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
Use `platformBrowser` for loading `aot` version.

#### What is the current behavior?
Using `platformBrowserDynamic`

#### What are the steps to reproduce?
N/A

cc @DevVersion as he commited the [current code](https://github.com/angular/material2/blob/master/src/demo-app/main-aot.ts) and might know more.

**Comment by DevVersion** [comment]
Should be fixed. Thanks
