### ISSUE TITLE
Navtabs Scroll

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4581]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
When the nav tabs bar has to many tabs, it should show some scroll function similar or same as the normal tabs do it.

#### What is the current behavior?
When the nav tabs bar has to many tabs, it breaks into new lines.

#### What are the steps to reproduce?
Create to many nav tabs for the window size.

#### What is the use-case or motivation for changing an existing behavior?
Consistent UX

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 4.1.x, md beta 5

**Comment by ocarreterom** [comment]
dup https://github.com/angular/material2/issues/2177

**Comment by mbeckenbach** [comment]
@ocarreterom sorry not seen this. closing my post
