### ISSUE TITLE
Dialog close / Dialog cancel

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4583]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
There should be two methods for closing a dialog. One for a close and one for a cancel.

#### What is the current behavior?
There is only one close method and so only one afterClosed.

#### What are the steps to reproduce?
Create any dialog

#### What is the use-case or motivation for changing an existing behavior?
Imagine an edit dialog with a save and a cancel button. At the moment you would have to pass something intro the close method and check for it after close to detect a save action. Would be much easier if there where two different events to subscribe. afterClose and afterCancel.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 4.1.x, md beta 5

**Comment by jelbourn** [comment]
Doing this would be tying the content of the dialog to the dialog semantics. The dialog itself only cares whether it is opened or closed; the fact that one "close" means one thing and that another "close" means another is a user-space concern.

**Comment by gseabrook** [comment]
Thanks for the response, @jelbourn , do you have a 'best practice' for how to approach this problem? I find that in all the cases that I have a dialog, I end up calling `this.dialog.close(true)` or `this.dialog.close(false)` and then have an if statement in the afterClosed callback eg

    afterClosed().subscribe(success => {
        if (success) {
            // perform action
        }
    }

This feels a lot less elegant than the `$mdDialog.hide()` and `$mdDialog.cancel()` methods in material 1.x

**Comment by willshowell** [comment]
@gseabrook you could ignore the undefined/falsey close values:

```ts
this.dialog.open(MyDialogComponent, config)
  .afterClosed()
  .filter(x => !!x)
  .subscribe(val => this.successAction(val))
```
