### ISSUE TITLE
Updation to Angular 4 gives this error

### ISSUE THREAD

**Issue by paramsingh88** [angular/material2#4587]
#### Bug, feature request, or proposal:

The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): ng:///Users/parminder/Documents/code/onedirect/node_modules/@angular/material/autocomplete/autocomplete.html@0:0

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
