### ISSUE TITLE
Autocomplete select the first option if the filter is not empty 

### ISSUE THREAD

**Issue by badre429** [angular/material2#4592]
#### What is the expected behavior?
make Autocomplete component select the first option if the filter is not empty 
![auto-complete](https://cloud.githubusercontent.com/assets/5818051/26111080/05c79d08-3a4c-11e7-94ee-fafebe7863e8.JPG)

## Autocomplete with keyboard 

1. enter filter text 
2. first option is selected (without pressing the `down` key)
3. press `Enter` and the value is set

**Comment by jelbourn** [comment]
Autocomplete does not require that one of the options is entered; it allows for free-form entry as well. As such, it is important that an option is not selected unless the user specifically does so.

**Comment by badre429** [comment]
md-select is not useful for huge number of option unless md-select has filter option autocomplete is more suitable for that
