### ISSUE TITLE
The date picker doesn't work without the button toggle, type="date" doesn't work and there is no option for a date only

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#4596]
#### Bug, feature request, or proposal:
Bug? 

#### What is the expected behavior?
There should be another manner in which to use the calendar picker from a regular mdInput other than the button toggle.  

type="date" also, doesn't work and has an override of the browser date picker functionality... at this point only a date is allowed but the material datepicker doesn't even function.  

As well, there is no way to lock the date as being only a date.  

#### What is the current behavior?
Only the button toggle will activate the calendar 

#### What are the steps to reproduce?
Just use md-datepicker

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Most any date-pickers only allows a person to select a date without anything else going into the input other than a date.  I see only the ability to add an icon inside of the date picker but the entire input field should still be a trigger for seleciting a date

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.0-beta.1 and Material 2

#### Is there anything else we should know?
Nope

**Comment by jelbourn** [comment]
The `mdDatepickerToggle` directive is just a convenience for toggling the panel; you can toggle if however you want by grabbing a reference to the `MdDatepicker` instance and calling `open` / `close`.

It is expected that the datepicker doesn't work with `<input type="date">`, as the two provide mutually exclusive interfaces for date selection (there is no standard for the UI created by `<input type="date">`, so it is not really feasible to try to override / block that behavior).

**Comment by xtianus79** [comment]
@jelbourn 

I am trying to run the example per the documentation and 

I am getting an error dp is not defined.  

https://plnkr.co/edit/nBi0IbqlF8a8WqsemZDL?p=preview

**Comment by jelbourn** [comment]
Your plunker is missing `this.`

**Comment by xtianus79** [comment]
@jelbourn lol duh.... thanks.

One more question... it doesn't seem apparent but there doesn't seem to be the need for a close command because either clicking a date or clicking off of the cal will close it.  Just wanted to confirm that this is correct.
