### ISSUE TITLE
add mdTooltipClass to allow CSS customization of tooltips

### ISSUE THREAD

**Issue by arlowhite** [angular/material2#4601]
#### Bug, feature request, or proposal:

The ability to specify a CSS class for a **MdTooltip**.

#### What is the expected behavior?

Developers should be able to customize some tooltips with CSS rules.

#### What is the current behavior?

Developers cannot apply CSS to a portion of tooltips because they are created in the `cdk-overlay-container`. Their only option is to apply CSS globally using `.mat-tooltip`.

#### What is the use-case or motivation for changing an existing behavior?

A number of feature requests could probably be resolved if developers had **mdTooltipClass**
#3389

**Comment by DevVersion** [comment]
Developers would still need to disable the view encapsulation to reach to the tooltip overlay element.

Or is the main reason to be able to differentiate between different tooltips?
