### ISSUE TITLE
Use MdIcon svgIcon in lazy-loaded component

### ISSUE THREAD

**Issue by guysenpai** [angular/material2#4606]
#### Bug, feature request, or proposal:
Bug:
I have created a custom icon set and I used it in a lazy-loaded component.

#### What is the expected behavior?
the expected behavior is displaying the svg icon in my component

#### What is the current behavior?
the current behavior is nothing is displayed

#### What are the steps to reproduce?

my plunker template https://plnkr.co/edit/UxT1QPnWqzTznDimpsZc?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```bash
@angular/cli: 1.0.3
node: 6.10.3
os: win32 x64
@angular/animations: 4.1.2
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.2
```

**Comment by jelbourn** [comment]
Looked at your plunker. Seems that md-icon is adding the `<svg>` element just fine, but the svg itself has some problem that prevents it from being rendered.

**Comment by guysenpai** [comment]
I can't see the problem on my svg file. I have take example on [core-icon-set](https://github.com/angular/material2/blob/master/src/demo-app/icon/assets/core-icon-set.svg?short_path=ee86795) svg file in demo-app icon.
what is the correct form the svg must have?

**Comment by jelbourn** [comment]
The set itself looks okay, but the actual SVG icon path seems to drawing way off from where the element appears.
