### ISSUE TITLE
Create documentation on how to combine input + chips

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#4607]

**Comment by vadim82** [comment]
Is this ability to combine these components already available in beta.5?

**Comment by lucasvanhalst** [comment]
This was included in https://github.com/angular/material2/pull/4912/files#diff-c127207d5ba82d35ff48fbd7db9e2e16R44 but I wouldn't say it works properly. If the width of the chips exceed the width of the input element, it looks like this and you can't even see what you're typing in the input field anymore
<img width="539" alt="screen shot 2017-07-19 at 14 30 44" src="https://user-images.githubusercontent.com/6652304/28366899-e66371ec-6c8e-11e7-9337-d28fba1a9272.png">

**Comment by tinayuangao** [comment]
Fixed by #7081
