### ISSUE TITLE
Ability to select range.

### ISSUE THREAD

**Issue by sheetaldshivdas** [angular/material2#4613]
Feature request: please provide md-slider with options of selecting a range, for example start value and end value both to be slider components.

Client has requested for such a feature.

Need this in Angular 2/4

**Comment by jotatoledo** [comment]
Please use the issue template. The fact that one of your clients asked for the feature isn't enough (in my opinion) to justify why this feature is necessary.

**Comment by ciesielskico** [comment]
Since it is your client and not ours, why don't you implement it and share it with us through a pull request?

**Comment by jelbourn** [comment]
We don't have any plans do to a range slider.

**Comment by kkotak** [comment]
Outside of what's been discussed about this topic already, I feel that the range slider feature is sorely missing in material design. Alternatives like noUislider are not really good due to their overhead and non-material touch. My 2c.

**Comment by nureynisow** [comment]
+1
