### ISSUE TITLE
Text color not visible in md-raised-button within md-toolbar

### ISSUE THREAD

**Issue by daankets** [angular/material2#4614]
#### Bug, feature request, or proposal:
The .mat-toolbar.mat-primary style (for example) sets the text color to white. When adding an md-raised-button (no color) to the toolbar, the button text is invisible.

#### What is the expected behavior?
Visible text in the raised buttons.

#### What is the current behavior?
Invisible text in the raised buttons.

#### What are the steps to reproduce?
Create a md-toolbar with primary color background (default). Then, add a md-raised-button without [color] into it with containing some text. The text will not show up.

[Plunker example](http://plnkr.co/edit/9lHIdpr4p3XYl5jXCfOp?p=preview)

#### What is the use-case or motivation for changing an existing behavior?
The raised buttons should work even if embedded within a toolbar. They do not work unless a specific color (warn, primary, accent) is set.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 2, Angular Material 2 beta 5, Typescript (N/A), Browser (N/A)

**Comment by DevVersion** [comment]
@tinayuangao I looked at this issue and this is because of the `currentColor` inside of the button styles.

The `currentColor` makes sense to have on the buttons but for the toolbar's this can cause invisible text.

**Comment by tobiaseisenschenk** [comment]
I experienced the same issue, I'll just workaround it, but a fix would be highly appreciated.

**Comment by Eragra3** [comment]
Bump, any idea except for custom css?

**Comment by thefill** [comment]
Just a typo: currentColor should be changed to $currentColor to refer to a variable.

**Comment by PhilDore11** [comment]
you can use md-colors
