### ISSUE TITLE
Progress-spinner docs site example does not bind color correctly

### ISSUE THREAD

**Issue by mattroll** [angular/material2#4617]
Here : https://material.angular.io/components/component/progress-spinner

In the example tab ,changing the color of the progress spinner is not working.

I think it's because in html the attribute is attr.color and in .ts file the attribute is color

**Comment by gseabrook** [comment]
@jelbourn Is it possible to  serve the components example site (https://material.angular.io/components) locally? I can see the gulp tasks for building the documentation but I'm unsure how to test it before raising a PR

**Comment by jelbourn** [comment]
@gseabrook the docs site lives in https://github.com/angular/material.angular.io/ and is just a basic Angular CLI app. The example setup is a little... weird right now, though. 

@DevVersion has a fix for the issue in #4687
