### ISSUE TITLE
datapicker in form control valid value wrong

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#4618]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
when init the input is empty the input.valid should be false, after i select a date the input valid change to true

#### What is the current behavior?
when init the input is empty ,valid is true,after i select a date the input valid change to false
i import MdNativeDateModule  with MD_NATIVE_DATE_FORMATS, so the dispaly format is ''yyyy-mm-dd'',
but the date parser parse the input in format "mm-dd-yyyy".
with the ""mm-dd-yyyy" format parser the date like "33-33-2017" unexpectedly control valid is true.
i'm so confused with the NativeDateAdapter parser

#### What are the steps to reproduce?
i have import MdDatepickerModule,    MdNativeDateModule in app.module.ts
```
<form (ngSubmit)="onSubmit()" #dialogForm="ngForm">
    
    <button [mdDatepickerToggle]="resultPicker"></button>
    <md-input-container>
        <input mdInput
               #resultPickerModel="ngModel"
               [mdDatepicker]="resultPicker"
               [(ngModel)]="date"
               [min]="minDate"
               [max]="maxDate"
               placeholder="Pick a date" name="test">
        <md-error *ngIf="resultPickerModel.hasError('mdDatepickerMin')">Too early!</md-error>
        <md-error *ngIf="resultPickerModel.hasError('mdDatepickerMax')">Too late!</md-error>     
    </md-input-container>
    <md-datepicker #resultPicker
                   [touchUi]="true">
    </md-datepicker>
    {{resultPickerModel.valid}}
 </form>
```

#### What is the use-case or motivation for changing an existing behavior?
get the right input valid value, with the format i set just like "yyyy-mm-dd"

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.0-beta.0
material@2.0.0-beta.5-05dbb90
os win10
typescript 2.3.1
Browsers: Chrome 58.0.3029.110 (64-bit)

**Comment by stevenmi** [comment]
if i use the MdNativeDateModule in wrong way ,please tell me how to use it correctly

**Comment by stevenmi** [comment]
in the plunker https://plnkr.co/edit/ulSNTMTMZmORzvkVTvch?p=preview, the valid always be true,  may be the material version is different with my local project

**Comment by stevenmi** [comment]
i have test today. i found that with angular 4.1.3 the datepicker valid always true (init and after select a date). with angular 4.2-bata.0 when init the valid is true ,and after select a date the valid become false

**Comment by stevenmi** [comment]
is there anybody know how to fix the problem 
v4.1.3 https://plnkr.co/edit/ulSNTMTMZmORzvkVTvch?p=preview
v4.2.0-rc.0  https://plnkr.co/edit/fDV0g0Xp81EYWNtnscgi

**Comment by crain** [comment]
@stevenmi how did you fixed it?

**Comment by mmalerba** [comment]
You can mark the field required, the reason there was no error is because those dates parsed as `null` (much like entering `e` into a number field).
