### ISSUE TITLE
MdDialog does not apply width correctly

### ISSUE THREAD

**Issue by ryanpm40** [angular/material2#4620]
#### Bug, feature request, or proposal:
Since upgrading from beta.3 to beta.5, mddialog no longer supports the width property properly. The cdk-overlay-container gets the applied width, but the dialog itself does not.

#### What is the expected behavior?
The dialog should have the width passed to its configurations

#### What is the current behavior?
The cdk-overlay-container has the width, throwing off positioning of the dialog

#### What are the steps to reproduce?

I've applied a width of 815px to the example dialog:
https://plnkr.co/edit/qYMFWtkiu9RnCTEPqTXi?p=preview

#### What is the use-case or motivation for changing an existing behavior?
To be consistent with how the dialog displayed in beta.3

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.0.2, Material2 2.0.0-beta.5, typescript 2.2.2, Windows 7, Chrome

**Comment by ocarreterom** [comment]
dup https://github.com/angular/material2/issues/3239

**Comment by ryanpm40** [comment]
@ocarreterom Well, the odd thing is, this issue was not present before. I was aware of that duplicate issue back in Feb, but my width of 815px to my dialogs was displaying correctly until the most recent upgrade.

**Comment by ryanpm40** [comment]
Closing issue- looks like I had a bad global CSS property that didn't affect things before.
