### ISSUE TITLE
mdInput placeholder for type="number" duplicated in FF

### ISSUE THREAD

**Issue by PeS82** [angular/material2#4621]
#### Bug, feature request, or proposal:

BUG, in FireFox; in Chrome it is OK.

#### What is the expected behavior?

When focused, placeholder floats above input field, input field is empty (or has value)

#### What is the current behavior?

Input field still has placeholder, is duplicated.

#### What are the steps to reproduce?
https://plnkr.co/edit/01tM9NFhIlcLUgHDQ8KZ?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

See plunker, FireFox 53.0.2

**Comment by jelbourn** [comment]
@mmalerba can reproduce in Firefox

**Comment by mmalerba** [comment]
cause by this FF bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1004130#c20 I'll look into a workaround

**Comment by mmalerba** [comment]
FF folks filed a separate bug to track which is now marked as fixed, so this should just resolve itself soon... https://bugzilla.mozilla.org/show_bug.cgi?id=1368113

**Comment by mmalerba** [comment]
firefox has released this fix now
