### ISSUE TITLE
[Tabs] Nav bar does not support stretched labels

### ISSUE THREAD

**Issue by skyfremen** [angular/material2#4623]
#### Bug, feature request, or proposal:
Bug - md-stretch-tabs is not working with md-tab-nav-bar

#### What is the expected behavior?
The Tab Navation should stretch to fit the width of the screen 
md-stretch-tabs should work with md-tab-nav-bar

#### What is the current behavior?
It does not stretch for md-tab-nav-bar, however it is working for md-tab-group.
Please view plunker provided below

#### What are the steps to reproduce?
Plunker template: http://plnkr.co/edit/7IaUPhjpLNDcAREb61jN?p=preview

#### What is the use-case or motivation for changing an existing behavior?
NA

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4 
Material 2.0.0-beta.3

#### Is there anything else we should know?
NA

**Comment by jelbourn** [comment]
Also this feature is totally undocumented

**Comment by PhanindraKumar** [comment]
does is there any work around for this feature ?

**Comment by ocarreterom** [comment]
Related with https://github.com/angular/material2/issues/2177?

**Comment by scottseeker** [comment]
I would like to individually size tab labels.  For instance, when using chrome there is an extra tab to 'add new'.  I'm going for basically the same thing, but can't find a way to size only the 'add new' tab label.

**Comment by Viktor-Bredihin** [comment]
any update/workaround?

**Comment by Viktor-Bredihin** [comment]
my workaround
`.mat-tab-links {
    display: table;
    width: 100%;

    .mat-tab-link {
        display: table-cell;
    }
}`

**Comment by patoncrispy** [comment]
I've put: 

```
.mat-tab-label {
  flex: 1 1 auto;
}
```

in my global css file. Alas, this means ALL my tabs have this effect, which I can put up with until another solution pops it's head up.

**Comment by skyfremen** [comment]
Seems to be supported now in 6.0.0

**Comment by primechris** [comment]
I have used the following code: 

`.mat-tab-labels > div:last-child {
    min-width: 58px !important;
    background-color: #c2f975;
    float: left;
    border: none;
    outline: none;
    cursor: pointer;
    transition: 0.3s;
    font-size: 17px;
    cursor: default;
    
}`

to style my final tab and make it n "add" button just like in chrome.

**Comment by intellix** [comment]
```html
<mat-tab-group mat-align-tabs="stretch">
```

```scss
.mat-tab-group[mat-align-tabs='stretch'] {
  .mat-tab-label {
    flex: 1;
  }
}
```
