### ISSUE TITLE
launch datepicker in a dialog and click outside dialog will result in a small square on the screen

### ISSUE THREAD

**Issue by wpcfan** [angular/material2#4624]
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

datepicker should get dismissed and the dialog should keep open unless I click outside again. 

#### What is the current behavior?

both datepicker and dialog are gone, but remain a small square on the screen

#### What are the steps to reproduce?

1. in a dialog (contains a form)

```
    <md-input-container class="full-width">
      <input mdInput 
        [mdDatepicker]="dueDatePicker" 
        placeholder="pick a due date" 
        formControlName="dueDate">
      <button mdSuffix [mdDatepickerToggle]="dueDatePicker"></button>
    </md-input-container>
    <md-datepicker touchUi="true" #dueDatePicker></md-datepicker>
```
2. launch the dialog, and then launch date picker
3. click outside dialog and datepicker
4. you will see a small square on the screen

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4, Material beta5, macOS 10.12.4, Chrome:  57.0.2987.133 (64-bit)

**Comment by willshowell** [comment]
Can you repro in a plunker?

For our app, clicking outside the datepicker just closes the datepicker, not the dialog.

**Comment by pietie** [comment]
I also get the small square. In my case it's because I navigate to another component when a selection is made and I guess the calendar has not completed its exit animation. 
It sort of works if I wrap the navigate in a setTimeout(..,0). I say "sort of" because you still see the small square for a short while before it disappears,

https://plnkr.co/edit/uGdquTlfAJxs3C5yCEPp

**Comment by mmalerba** [comment]
Looks like this has been fixed in master (here's a version of @pietie's plunker with updated `systemjs.config.js`: https://plnkr.co/edit/oKF71oguDhHtOWQL6eGS?p=preview)

**Comment by MortenDals** [comment]
Opening the issue again.

Touch UI is or have become bugged again for mat datepicker, so you need to use "setTimeout(() => this.router.navigate(['/home']), 0);" for it to close correctly when a navigation happen while it is open, so you don't get the small box that block all input.
