### ISSUE TITLE
AOT compilation is failing because of material

### ISSUE THREAD

**Issue by jorawarsingh** [angular/material2#4626]
#### Bug, feature request, or proposal:
Probably a Bug

#### What is the expected behavior?
Aot should compile the code without any error because of material

#### What is the current behavior?
When i compile run aot compilation i get the following

> ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 14:10 in the original .ts file), resolving symbol ɵu in D:/www/AnnualReportWeb/node_modules/@angular/material/typings/index.d.ts, resolving symbol _MdButtonMixinBase in D:/www/AnnualReportWeb/node_modules/@angular/material/typings/index.d.ts, resolving symbol MdButton in D:/www/AnnualReportWeb/node_modules/@angular/material/typings/index.d.ts

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.0.0
material 2.0.0-beta.5

#### Is there anything else we should know?
My app works fine if i run with jit compiler.

**Comment by jelbourn** [comment]
This was a bug in an older version of `ngc` that should be fixed in the latest version 
https://github.com/angular/angular/issues/15536

**Comment by jorawarsingh** [comment]
Thanks @jelbourn  error gone after upgrading angular compiler!
