### ISSUE TITLE
Bug: tooltip not working well in Internet Explorer when angular UI is not too simple

### ISSUE THREAD

**Issue by zijianhuang** [angular/material2#4628]
#### Bug:

In Microsoft Windows 7 and 10, with Internet Explorer, when the UI is not too simple, the tooltip may have the following behaviors:
1. If the button/element (with tooltip) is is near the left edge of the screen, the tooltip is align too much to the left, thus the left part gets trimmed at the edge of the screen.
2. Or part of the tooltip get cut out by other elements nearby.
3. Or the tooltip is not appearing at all.

It is easy to reproduce the problem:
1. Open https://material.angular.io/components/component/tooltip in Internet Explorer v11
2.  In the Examples tab, click on the "Edit in Plunker" link to open the Examples app in Plunker, you will see the tooltip is not appearing, or sometime is flashing for less then 0.5 second.

Tooltip is working well in Firefox and Chrome.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 2 and 4, Windows 7, 10, TypeScript 2.0-2.3

#### Is there anything else we should know?

I had been using Tooltip of https://ng-bootstrap.github.io/#/components/tooltip which is working well in all browsers, and would replace those in ng-bootstrap with counterparts in material2. Hopefully the material2 team could catch up soon covering every components in ng-bootstrap.

**Comment by ceyon** [comment]
I'm experiencing the same issue . works fine in chrome and Firefox. angular 4 , ts 2.3.2. Also MaterialModule.forRoot() gives an error, type does not contain forRoot

**Comment by zijianhuang** [comment]
In the latest Beta 7, this is fixed. Though it has other problem now as I has reported at #5428
