### ISSUE TITLE
*ngIf, and [disabled]  for SlideToggle not working ie11

### ISSUE THREAD

**Issue by pdecembre** [angular/material2#4633]
#### What is the expected behavior?
when a slide toggle element is set with a *ngIf directive or [disabled] property, element should read and act on the value of the property from component

#### What is the current behavior?
element ignore the values set by the *ngif and [disabled] and still displays and fire toggle as usual

#### What are the steps to reproduce?
put an element on a component's html:
<md-slide-toggle class="example-margin" *ngIf="bool-prop-from-component"> 
OR
<md-slide-toggle class="example-margin" [disabled]="bool-prop-from-component"> 

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.1.0, TypeScript: 2.3.2 IE11

#### Is there anything else we should know?
Works perfectly fine in Chrome

**Comment by jelbourn** [comment]
Just tried this on IE11, could not reproduce. Feel free to re-open if you can provide a reproduction.
