### ISSUE TITLE
Question regarding md-tab

### ISSUE THREAD

**Issue by absarora** [angular/material2#4637]
Is it possible to switch between tabs using a button to navigate pages rather selecting the tab using the onSelectChange event?

Selecting the tabs works as expected and switch to expected routes but I would also like to switch tabs when I click on the 'next' button to move from, example, Tab 'A' to Tab 'B'.

<img width="871" alt="screen shot 2017-05-17 at 6 54 35 pm copy" src="https://cloud.githubusercontent.com/assets/5633327/26183358/2c86dd90-3b33-11e7-85c3-61c5e50427cf.png">

**Comment by crisbeto** [comment]
Yes it is. You can bind to the `selectedIndex` property to set the index of the tab that should be active. [You can see an example in our demo app.](https://github.com/angular/material2/blob/master/src/demo-app/tabs/tabs-demo.html#L49)
