### ISSUE TITLE
`.cdk-global-scrollblock` is missing width: 100%

### ISSUE THREAD

**Issue by fxck** [angular/material2#4646]
`max-width: 100vw` is not enough, `width: 100%` need to be added as well, otherwise this happens

![image](https://cloud.githubusercontent.com/assets/1303561/26198436/4c3ae486-3bc6-11e7-8edd-c86889085fe9.png)

@crisbeto

**Comment by crisbeto** [comment]
Will be resolved by https://github.com/angular/material2/pull/4638.
