### ISSUE TITLE
Add a beforeClose method for MdDialog

### ISSUE THREAD

**Issue by Dunos** [angular/material2#4647]
**Feature Request**

**What is the expected behavior?**

When the user is about to close a MdDialog window (via Esc key, clickout or close button), for example an edit dialog, it would be nice to be able to have some method to prevent the window from closing to avoid unsaved changes for example.

**What is the use-case or motivation for changing an existing behavior?**

Since the MdDialog already listens to Esc key events, clickout and has the close() method that is used in the action buttons, it would be much easier to have a method like _afterClosed_ that is called just before the closing event is going to occur, so we could prevent it from happening just returning `true` or `false` in a callback function. This way we don't have to overwrite those event listeners.

**Comment by willshowell** [comment]
Related https://github.com/angular/material2/pull/3460

**Comment by jelbourn** [comment]
We did originally plan on adding a `beforeClose` hook, but not with the ability to cancel the close. The stance has been that, rather than canceling close, the user can `disableClose` and take control of closing the dialog via whatever criteria suits their application.

**Comment by Dunos** [comment]
Well, I guess something like that could work too. Do you expect to have this functionally any time soon?

**Comment by davidmorissette** [comment]
In my opinion `beforeClose` and `disableClose` serve two different purposes. Imagine a scenario where you want to prompt a user before discarding the changes (no matter how the cancellation happened); then using `beforeClose` would allow us to cancel closing the dialog. However, `disableClose` would completely remove the ability for the user to close the dialog (via cancellation) which is not what is expected.

**Comment by wulfsberg** [comment]
To pitch in here (from over in https://github.com/angular/material2/issues/5209), I'd also like to have the _value_ of the user choice exposed in an observable before/on close, to get access to it without having to wait for the animation.
(This is somewhat tangential to the beforeClose _method_, but it seems to be tracked collectively here).

**Comment by mtycholaz** [comment]
Much needed! We have a use-case where we want to save data if the user cancels the dialog (via clicking on backdrop or hitting the Esc key). Where the problem comes in, is if there's a server error, we want to keep the modal up still to display the message.
