### ISSUE TITLE
MdAutocomplete two-way data binding not working

### ISSUE THREAD

**Issue by limpep** [angular/material2#4652]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Display existing data value

#### What is the current behavior?
Existing data is not set

#### What are the steps to reproduce?

https://plnkr.co/edit/GZcchKGp1ZJi6GlbVNfu?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cli: 1.0.3
node: 7.10.0
os: darwin x64
@angular/animations: 4.1.1
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.1

**Comment by ocarreterom** [comment]
You are mixing strings and objects as data values without coherence.
Change the `displayFn` function to:
```ts
displayFn(user: any): string {
  return user && typeof user == 'object'
    ? user.name // for valid object (not null)
    : user; // for string
   }
```
Or change your `sameValue` variable to `User` type.
```ts
someValue:User = new User("hello");
```
On the other hand, it is a bit redundant to use `ReactiveForms` and `NgModel` at the same time.

**Comment by jelbourn** [comment]
@kara is this working as expected?

**Comment by limpep** [comment]
@ocarreterom does this mean I am forced to use `ReactiveForms` ? Also this code is not mind, its within the documentation https://material.angular.io/components/component/autocomplete

**Comment by ocarreterom** [comment]
In the documentation I can't find the NgModel anywhere, but it works perfectly. Only the changes described above is needed.

**Comment by willshowell** [comment]
@limpep worth noting that you are not required to use reactive forms, but it does makes things simpler. You can use [template driven forms if you wish](https://plnkr.co/edit/1zDmoenwwwSqypK6vrNx?p=preview), but you should not be trying to mix them

**Comment by limpep** [comment]
@ocarreterom the NgModel part I added. @willshowell, Thanks for your help it make sense to me now.
