### ISSUE TITLE
Proposal: Ability to add extra class(es) to dialog container

### ISSUE THREAD

**Issue by willshowell** [angular/material2#4653]
#### Bug, feature request, or proposal:
Proposal

####  Use Case 1:
I have a dialog that I want to be full-bleed (in my case, it contains just a map)
```
this.dialog.open(MyMapDialogComponent, { containerClass: 'full-bleed' })

.mat-dialog.container.full-bleed {
  padding: 0;
}
```

#### Use Case 2:
I want to make my dialog full screen:
```
this.dialog.open(MyBigDialogComponent, { containerClass: 'full-screen' })

.mat-dialog-container.full-screen {
  max-width: none;
  width: 100vw;
  height: 100vh;
}
```

This wouldn't be too different from `backdropClass` or snackbar's `extraClasses` and it would solve https://github.com/angular/material2/issues/3209

**Comment by willshowell** [comment]
@jelbourn With the addition of `panelClass` in #4722, I'm able to achieve what I want. Happy to  close unless you see any value in also being able to add classes to the dialog container.

**Comment by jelbourn** [comment]
Sounds good to me

**Comment by zdendapa** [comment]
its not perfect, but fast solution
/deep/ .mat-dialog-container {
  padding: 0;
}

**Comment by no-more** [comment]
I know this thread is closed but I was wondering if it's possible to add a class from within the dialog component ?
The panelClass configuration needs to be used everywhere I want to call the dialog, but my need is to apply  the same class all the time so it's quite redundant. I was looking for something like "host" solution for component.

Thanks.

**Comment by willshowell** [comment]
@no-more you might be interested in using `MAT_DIALOG_DEFAULT_OPTIONS` if you want to apply the class to all dialogs, or maybe follow https://github.com/angular/material2/issues/6206 since it would provide the ability to modify the panelClass

**Comment by no-more** [comment]
Thanks for your fast response.
I'll follow the other thread as my need is to be able to apply one or more class to a specific dialog component(all instances of this components) and not to all my dialogs.
