### ISSUE TITLE
Gulp test tasks are failing

### ISSUE THREAD

**Issue by RobJacobs** [angular/material2#4654]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
For the gulp task 'test' and 'test:single-run' to complete

#### What is the current behavior?
test task fails and crashes Chrome/Firefox.

#### What are the steps to reproduce?
Run 'gulp test:single-run'

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Win 10, Node 6.10.2, Karma 1.7.0, Chrome 58.0.3029.110

#### Is there anything else we should know?
I had to exclude the snack-bar and dialog tests to get the test to complete without hanging.

Also noticed some overlays are not getting cleaned up.  When running the tests in debug mode in the browser, after the browser locked up, I can see 12 divs with the cdk-overlay-container class still in the body.

Also seeing several errors in the terminal like:

× should set the width of the overlay if there is no placeholder
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

Which I'm guessing is related to the whenStable() method.

**Comment by crisbeto** [comment]
Everything passes for me locally and the only difference seems to be the Karma version (I'm running 1.6). 

As for the `cdk-overlay-container` leaks, unless we remove the elements from the DOM manually in tests, there is no good way clean them up, because the element is added by a service, which can't have an `OnDestroy` method.

**Comment by RobJacobs** [comment]
@crisbeto I've tried on 4 different machines with the same results.  All of them had a clean clone of the repo, then ran npm install, then ran gulp test:single-run.

**Comment by crisbeto** [comment]
Alright @RobJacobs, it definitely shows up after a clean install.
