### ISSUE TITLE
Md-list-item gains focus after click on its child elements

### ISSUE THREAD

**Issue by Saif03** [angular/material2#4655]
Issue:

I have an md-nav-list structure like below:

```
  <md-nav-list>
    <md-list-item *ngFor="let i of arr" routerLink="/my-link" [disableRipple]="true">
        <md-icon (click)="add($event); $event.stopPropagation();">add</md-icon>
    </md-list-item>
  </md-nav-list>

```
#### What is the current behavior?
When I click on my icon it performs its action (opens a dialog box) but md-list item stays/gets focused and stays focused until ofcourse I click somewhere else.

#### What is the expected behavior?
As I am clicking on the icon inside md-list-item then md-list-item shouldn't gain focus as I clicked on its child not on md-list-item.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: latest (4.0)
Material: v2
TS: Latest
OS: Linux
Browser: Chrome (Latest)

#### Is there anything else we should know?
SCREENSHOT:
As Visible in the screenshot when I clicked on one of the buttons available (on hover) inside md-list-item, item # 1 is still focused after that.

![image](https://cloud.githubusercontent.com/assets/15065985/26213675/5db51054-3c13-11e7-98f4-025ecf5dd4ad.png)

**Comment by jelbourn** [comment]
Couple of issues:
* md-nav-list is meant to be used for a list of anchors
* md-icon is not an interactive element. It should be an `md-icon-button`

**Comment by Saif03** [comment]
that worked like a charm.
