### ISSUE TITLE
Select shows two options selected when programmatically changed

### ISSUE THREAD

**Issue by willshowell** [angular/material2#4656]
#### Bug, feature request, or proposal:
Bug

#### Expected behavior
After using `setValue()` or `patchValue()` on the selection control, the old selection should lose its `.mat-selected` class.

#### Current behavior
`.mat-selected` remains on the original selection and is added to the new one
![screen shot 2017-05-18 at 1 53 41 pm](https://cloud.githubusercontent.com/assets/6475576/26216247/6ca7d55c-3bd1-11e7-8d48-38023ca77e0f.png)

#### Reproduction
http://plnkr.co/edit/tKkNvYF4AjEgFlE9resJ?p=preview

**Comment by crisbeto** [comment]
Looks like a dupe of https://github.com/angular/material2/issues/4476.

**Comment by willshowell** [comment]
Yep it is 👍
