### ISSUE TITLE
textarea does not honour autosize when initial value is set via ngModel

### ISSUE THREAD

**Issue by mishugashu** [angular/material2#4657]
#### Bug, feature request, or proposal:
When I have a textarea with "mdTextareaAutosize" and a bound "ngModel", the textarea doesn't seem to size to the initial data. Once you change anything inside the textarea, it will start autosizing.

#### What is the expected behavior?
When page loads, textarea should be sized appropriate to data.

#### What is the current behavior?
When page loads, textarea is not sized.

#### What are the steps to reproduce?
http://plnkr.co/edit/D9ZmsmhRMNc2rjXkmVXv?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Applications that have dynamic data in text areas that needs to be autosized on load.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I have only tested in Chromium 58 on Linux. For Angular, it looks like your plunker template uses 4.1.3, but in the application I discovered it, we're using 4.0.0. Typescript is 2.2.1. Material is 2.0.0-beta.2 (although your plunker uses 2.0.0-beta.5).

**Comment by gedclack** [comment]
+ 1 :+1: 
something is wrong with `mdTextareaAutosize`

**Comment by limpep** [comment]
+1

**Comment by SimplerSoftware** [comment]
Just ran into this.  Any thoughts on a workaround?
