### ISSUE TITLE
Datepicker sends POST Request when opening.

### ISSUE THREAD

**Issue by ctilley83** [angular/material2#4663]
#### Bug, feature request, or proposal:
Bug Possibly.

#### What is the expected behavior?
Not to send a `POST` request when opening the picker

#### What is the current behavior?
For some reason clicking the button to open the picker sends a `POST` Request to the server.  The form I created uses formbuilder.  A more detailed explanation of my problem is posted on stackoverflow.

http://stackoverflow.com/questions/44057672/angular-4-material-2-beta-5-datepicker-issue

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

I tried to create a plunker for this issue but could not duplicate.  Too difficult to create an example due to the complex nature of my form.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All Browsers, Angular 4, Material2 beta5, TS version 2.2.1

**Comment by willshowell** [comment]
I think this is fixed in master, which would explain why your plunker couldn't replicate.

See https://github.com/angular/material2/pull/4531

**Comment by jelbourn** [comment]
Closing since it's already fixed on master.
