### ISSUE TITLE
Angular Material ink bar is incorrectly highlighting currently selected tab when screen size is small and the tabs become stacked on top of each other

### ISSUE THREAD

**Issue by helpfulbits** [angular/material2#4667]
#### Bug, feature request, or proposal:
Angular Material ink bar is incorrectly highlighting currently selected tab when screen size is small and the tabs become stacked on top of each other

#### What is the expected behavior?
Angular Material ink bar should be shown at the bottom of currently selected tab and not at the bottom of tabs group

#### What is the current behavior?
The ink bar remains always at the bottom of the screen even if tabs are stacked on top of each other

#### What are the steps to reproduce?
http://plnkr.co/JLZhe5clXukA0hSPz0g3

#### What is the use-case or motivation for changing an existing behavior?
Tabs selection highlighting needs to work correctly on small screens

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
+-- @angular/animations@4.1.2
+-- @angular/cli@1.0.3
+-- UNMET PEER DEPENDENCY @angular/common@4.1.2
+-- @angular/compiler@4.1.2
+-- @angular/compiler-cli@4.1.2
| +-- @angular/tsc-wrapped@4.1.2
+-- UNMET PEER DEPENDENCY @angular/core@4.1.2
+-- @angular/flex-layout@2.0.0-beta.8
+-- @angular/forms@4.1.2
+-- @angular/http@4.1.2
+-- @angular/material@2.0.0-beta.5
+-- @angular/platform-browser@4.1.2
+-- @angular/platform-browser-dynamic@4.1.2
+-- @angular/router@4.1.2
| +-- @angular/core@2.4.10

| +-- typescript@2.2.2
| `-- typescript@1.8.10
+-- typescript@2.3.2

**Comment by helpfulbits** [comment]
I assume the tabs are not meant to be stacked on top of each other according to material design styleguide. There needs to be a scrollbar introduced or extra menu for selection

**Comment by willshowell** [comment]
Is this a dupe of https://github.com/angular/material2/issues/4323?

**Comment by helpfulbits** [comment]
Yes, thanks, closing this.
