### ISSUE TITLE
md-nav-tab-bar tabbing only works in Chrome

### ISSUE THREAD

**Issue by SargoDarya** [angular/material2#4668]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I can tab through the md-nav-tab-bar in every browser.

#### What is the current behavior?
Only works or shows active selection for Chrome. Firefox, IE and Safari don't allow tabbing through the navigation at all.

#### What are the steps to reproduce?
See Plunker here:
http://plnkr.co/edit/YRvtThQQ8COoOflbyMxu?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Makes it easier to navigate for a user.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
**Browsers**: Firefox, IE and Safari
**OS**: Mac and Windows (7|8|10)
**Material Version**: (2.0.0-beta.5)
**Angular Version**: 2 and 4

**Comment by donroyco** [comment]
@SargoDarya Your Plunker doesn't work in either Firefox or Chrome. Can you make it work (again)?

**Comment by SargoDarya** [comment]
@donroyco Sorry, had the wrong template probably. I recreated the plnkr using the current template and updated the link in the original description and for convencience here: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

**Comment by SargoDarya** [comment]
Weird thing, with the new one it doesn't even work in chrome. Is this intended?

**Comment by donroyco** [comment]
Can you use this template? https://goo.gl/DlHd6U

**Comment by SargoDarya** [comment]
@donroyco Sure thing. I'm changing the links.

http://plnkr.co/edit/YRvtThQQ8COoOflbyMxu?p=preview

**Comment by jelbourn** [comment]
The tabbing doesn't work in the plunker because `routerLink` isn't being run for real. The `routerLink` directive applies an `href` to the `<a>` element, which causes it to be tabbable. [See this non-Angular example](https://jsbin.com/demelivebi/edit?html,js,output).
