### ISSUE TITLE
md-input-container invalid state

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4671]
#### Bug, feature request, or proposal:
question, bug, or feature request. not sure

#### What is the expected behavior?
When a user enters text into a required input field and removes the text, there should be an immediate warning as the form control is now touched.

#### What is the current behavior?
The invalid color and md-error text are only updated after blur.

![required](https://cloud.githubusercontent.com/assets/6654388/26245895/af958682-3c96-11e7-840e-0ecfa66dc090.gif)

#### What are the steps to reproduce?
```html
<md-input-container>
      <input mdInput formControlName="answer" [required]="true">
     <md-error *ngIf="answerControl.errors?.required">Dies ist ein Pflichtfeld.</md-error>
</md-input-container>
```
#### What is the use-case or motivation for changing an existing behavior?
better user experience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng4.1.x, md beta 5

**Comment by willshowell** [comment]
Error state is calculated as
```
isInvalid && (isTouched || isSubmitted)
```
and touched is `true` when the control has been focused and then blurred.

There's an open issue at https://github.com/angular/material2/issues/4232 that could be of interest.

**Comment by mbeckenbach** [comment]
ok, but where does isSubmitted come from? My control does not change to submitted when i submit the form

**Comment by willshowell** [comment]
See the source [here](https://github.com/angular/material2/blob/master/src/lib/input/input-container.ts#L391-L400)

**Comment by mbeckenbach** [comment]
@willshowell yes, but there is no submitted property on my form, also in my usecase i cannot use a submit button to submit my form.

![image](https://cloud.githubusercontent.com/assets/6654388/26310707/16c1f044-3f02-11e7-9311-cd92e0be60b3.png)

**Comment by willshowell** [comment]
Hmm I see. I think for your original question, your best bet is to push the team on #4232 since that would allow you to configure how the errors are shown.

As a workaround for now, you could bind to the focus event and use `myFormControl.markAsTouched()`. I think that would get the error to show up immediately.

**Comment by mbeckenbach** [comment]
ok found a workarround. I created a hidden submit button and an event listener for my custom form submitted event:

´´´
 formSubmittedSubscription = this.surveyService.formSubmittedChange.subscribe(value => {
    this.formSubmitted = value;
    this.submitBtn.nativeElement.click();
  });

  @ViewChild('submitBtn') submitBtn: ElementRef; 
´´´

**Comment by jelbourn** [comment]
Tracked via #4232
