### ISSUE TITLE
Generic input-container

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4672]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
There should be something similar to the md-input-container which does not depend on a input control inside, so that the benefits for styling error states, using md-error and md-hint can easily be used for custom form controls.

#### What is the current behavior?
md-input-container has a very limited support for form-controls.

#### What are the steps to reproduce?
Read the docs :-)

#### What is the use-case or motivation for changing an existing behavior?
When using md-input-container it's really easy to have those nice animated md-error hints and invalid highlight. It's not that easy to get angular to adding the ng-invalid, ng-dirty and so on classes to a parent element like the md-input-container. So creating a similar look and feel for custom controls can be hard. 

It would be very cool to use md-input-container for anything.

```html
<md-input-container>
    <my-cool-control mdInput></my-cool-control>
   <md-error>User did something wrong</md-error>
</md-input-container>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 4.1.x, md beta 5

**Comment by jelbourn** [comment]
@mmalerba I know we planned to support this when designing the input container- what's the status on this?

**Comment by mmalerba** [comment]
Haven't gotten time to work on it yet, but its a feature I'd love to add

**Comment by natsid** [comment]
Is the idea for md-input-container to be able to contain all (or most?) of the other Material form controls so that they can all utilize md-hint and md-error, etc.?

**Comment by jelbourn** [comment]
This issue is tracking the ability to do something like
```html
<md-input-container>
  <my-custom-input mdInput></my-custom-input>
</md-input-container>
```

There's a separate issue of having `md-select` and `md-input-container` share the same setup

**Comment by natsid** [comment]
Ah, I missed the `mdInput` on the custom tag - thought it was just any custom component. Thanks.

**Comment by mmalerba** [comment]
This is now available, see the guide: https://material.angular.io/guide/creating-a-custom-form-field-control
