### ISSUE TITLE
Share "input container" behaviors between select and input

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4673]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
it should be possible to place md-select inside an md-input-container and by that use the cool md-error or md-hint stuff with it.

#### What is the current behavior?
It's not supported

#### What is the use-case or motivation for changing an existing behavior?
Consistent developer experiance and form features

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 4.1.x, md beta 5

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/2498

**Comment by natsid** [comment]
If this happens, would it make sense for `md-input-container` to also support `md-checkbox` and `md-radio-group`?

**Comment by mbeckenbach** [comment]
@natsid this would make a lot oft sense for required radio groups vor checkboxes to show the error state and messages.

**Comment by mackva** [comment]
+1

**Comment by mmalerba** [comment]
They now both work with `mat-form-field`
