### ISSUE TITLE
Font and vertical align

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4674]
#### Bug, feature request, or proposal:
bug / feature request

#### What is the expected behavior?
From controls should have the same font size, font weight and have a matching baseline by default when placed side by side.

#### What is the current behavior?

![image](https://cloud.githubusercontent.com/assets/6654388/26246435/6bc9cf3c-3c99-11e7-8bbb-1d572305b601.png)

#### What are the steps to reproduce?

http://plnkr.co/edit/I1cx3e?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Need a consistent look and feel without much custom css overrides as no customer would except such an inconsistant ui.

I think most devs should need the typography part quite fast as lots of people are already building apps with the beta. When using a beta bugs and breaking changes are common. But such a basic consitency is an important must have in the very early stages of a frontend.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 4.1.x, md beta 5

#### Is there anything else we should know?
I'm totally impressed that almost everything I used by now works in IE without the need of extra hacks. 👍

**Comment by jelbourn** [comment]
This is tracked via #2124
