### ISSUE TITLE
Datepicker setting wrong month

### ISSUE THREAD

**Issue by criticalbh** [angular/material2#4675]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To show the month from the input field

#### What is the current behavior?
Shows month as selected day, after show date picker button is clicked second time

#### What are the steps to reproduce?
Select current date to 3rd of May, click it again and it will show you current month as March

One from the official documentation
https://material.angular.io/components/component/datepicker

**Comment by mmalerba** [comment]
There's not enough information here for me to investigate, please provide a plunker and steps to reproduce.

**Comment by criticalbh** [comment]
I just took a look at it again and it get fixed in the meantime. Maybe it was just some bug on doc page.
