### ISSUE TITLE
Datepicker CSS cursor

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4676]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The cursor should turn into a pointer when hovering over a day or month.

#### What is the current behavior?
The cursor is in text-selection mode.

#### What are the steps to reproduce?
See current docs example

#### What is the use-case or motivation for changing an existing behavior?
Bad UX for mouse users

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
md beta 5 at the time of writing

**Comment by willshowell** [comment]
Should already be in master https://github.com/angular/material2/pull/4542
