### ISSUE TITLE
md-radio color support

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4677]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
md-radio should support the color property like md-checkbox does

#### What is the current behavior?
does not support it

#### What are the steps to reproduce?
see docs :-)

#### What is the use-case or motivation for changing an existing behavior?
I need a radio button in primary color :-(

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 4.1.x, md beta 5

**Comment by willshowell** [comment]
See #4039
