### ISSUE TITLE
Add success color option

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4678]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
There should also be a success and error color for theming

#### What is the current behavior?
There are only primary, accent, warn

#### What is the use-case or motivation for changing an existing behavior?
There are times, when you want to colorize correct inputs, have a green check icon saying something is ok and a red one for not ok.
Also a warning can be "you should not do this" as an error is something different. So an error color would be helpfull too sometimes. Think of a traffic light. (warning orange, error red)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 4.1.x, md beta 5

**Comment by yordis** [comment]
@mbeckenbach Following the material design spec probably this will be dismiss IMO

**Comment by jelbourn** [comment]
We primarily endeavor to follow to the material design specification, which only outlines colors for primary, accent, and "error state". It might be interesting to eventually support an arbitrary number of palettes, but this isn't on our radar anytime soon.

**Comment by yordis** [comment]
@jelbourn I literally removed exactly the same answer point of view because I thought will be rude. I guess from now on I should point Material design spec 😃

**Comment by AD30** [comment]
This is no longer true. 

Alternative colors
The Material Design color system supports alternative colors, which are colors used as alternatives to your brand’s primary and secondary colors (they constitute additional colors...

The Material Design color system supports alternative colors, which are colors used as alternatives to your brand’s primary and secondary colors (they constitute additional colors to your theme). Apps can use alternative colors to establish themes that distinguish different sections.

**Comment by JaxonWright** [comment]
This would be great, but like @AMNY49's above comment says, it probably should be more generic and allow arbitrary additional colors to be used. That would probably be more work than what this suggestion is asking but would be worth it.

**Comment by smnbbrv** [comment]
For the linking purposes: the issue actually went here https://material.io/design/color/the-color-system.html#color-theme-creation

**Comment by smnbbrv** [comment]
for the linking purposes: the issue landed here #11888
