### ISSUE TITLE
MdSnackBar do not show up in Safari iPhone 6s

### ISSUE THREAD

**Issue by giona69** [angular/material2#4682]
#### Bug, feature request, or proposal:

MdSnackBar is not showing up on Safari / iOS 10.3.1 / iPhone 6s

apparently is hidden behind the bottom toolbar of safari

#### What is the expected behavior?

to show up normally

#### What is the current behavior?

it doesn't show up

#### What are the steps to reproduce?

just open a snackbar in any component

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular ^4.1.0
starting from Material 2.0.0-beta.4 
iOS 10.3.1
typescript ^2.3.2
safari
iPhone 6s

#### Is there anything else we should know?

no

**Comment by crisbeto** [comment]
This should've been fixed by https://github.com/angular/material2/pull/4664.
