### ISSUE TITLE
Apply md-button to datePicker Button

### ISSUE THREAD

**Issue by ryanpm40** [angular/material2#4684]
#### Feature request:
Allow a user to add md-button and md-icon-button on the Date Picker's toggle button:

`<button mdSuffix [mdDatepickerToggle]="picker"></button>`

#### What is the expected behavior?
A user should be able to apply material button properties to allow for hover-over and ripple on the calendar button.

#### What is the current behavior?
Applying both causes the app to crash. Excerpt of the error:

```
Unhandled Promise rejection: Template parse errors:
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: MdButton,MdDatepickerToggle
```
#### What are the steps to reproduce?
Ex:
  `<button md-button md-icon-button mdSuffix [mdDatepickerToggle]="picker"></button>`

#### What is the use-case or motivation for changing an existing behavior?
Better usability. A user who notices a hover-over will feel more aware and inclined  to use that button.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.0.2, Material 2.0.0-beta.5, Windows 7 & 10, TypeScript 2.2.2, Chrome

**Comment by mmalerba** [comment]
#5317 is changing the toggle so that it inserts an icon button by default. However if you want to do something other than the default, the toggle is completely optional and its perfectly acceptable to use any element you want as a toggle button. Just hook up it's `(click)` to `picker.close()`
