### ISSUE TITLE
mdInput tag is not showing error message when using a pattern

### ISSUE THREAD

**Issue by Sneha1989** [angular/material2#4685]
#### Bug, feature request, or proposal:
<md-input-container>
          <input name="Num" mdInput placeholder="Number" value="" [(ngModel)]="Number" pattern="^[0-9]{1,10}$">
          <span style="color:red" ng-show="Num.$error.pattern">enter only 10 digit number</span>
     </md-input-container>

validation is happening using a pattern but I am not able to display an error message, I tried multiple things like md-hint, md-error but it's not working. 

it works fine with required. 

#### What is the expected behavior?

only if the user enters invalid valid then the error message should appear below the input. 

#### What is the current behavior?

the message appears before the user enters anything on the input bar.

**Comment by willshowell** [comment]
Plunker?

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
