### ISSUE TITLE
Tooltip blocks :hover styles

### ISSUE THREAD

**Issue by fredericojesus** [angular/material2#4691]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When hovering an icon with a tooltip the parent that also has a hover should not lose his hover state. 

#### What is the current behavior?
When hovering an icon with a tooltip the parent that also has a hover should loses his hover state.

#### What are the steps to reproduce?
Start the app.
Put the mouse in the first Home icon from the list.
Start moving the mouse down to hover the other icons and at the same time the other list items.
You'll see that for a little time the list item loses hover state.

**Plunker:** http://plnkr.co/edit/k2Qqy2IDMOtLgzb6FIch?p=info

#### What is the use-case or motivation for changing an existing behavior?
It causes a really bad impression for users. In the case of my team we have a list with multiple social icons in each item of the list. So user's are very prone to hover the social icons like mentioned in the steps to reproduce, so that flickering of the hover state doesn't give the best user experience.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All I suppose. I'm using the latest atm (beta5)

**Comment by jelbourn** [comment]
While the tooltip itself has `pointer-events: none`, the parent overlay panel has `pointer-events: auto` and this is blocking hover styles. The overlay panel should be given `pointer-events: none` for tooltips specifically.

**Comment by fredericojesus** [comment]
Hey,
When will this fix be released?
