### ISSUE TITLE
event.stopPropogation() is missing in MdMenu ?!

### ISSUE THREAD

**Issue by anki247** [angular/material2#4693]
#### Bug, feature request, or proposal:
I have MdMenu nested in MdListItem, which has also a click listener to open a MdDialog. By click on MdMenu opens the menu as well as the dialog at "same" time

#### What is the expected behavior?
I expect that by click on MdMenu, it should call event.stopPropogation() like in version 1. 

#### Is there anything else we should know?
I rewrite a little Application, which is in Angular Material 1 written and I had not deal with that problem. [App](https://anki247.github.io/account-manager/)

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

(missing steps to reproduce)
