### ISSUE TITLE
Disabled datepicker proposal

### ISSUE THREAD

**Issue by alanpurple** [angular/material2#4697]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
when paired input is disabled, MdDatepicker should be disabled also 

#### What is the current behavior?
even if input is disabled, we can change the date using datepicker

**Comment by alanpurple** [comment]
For now, I can work around by setting min and max property as current

**Comment by RobYed** [comment]
As a workaround I am adding a conditonal CSS class to `md-input-container` which sets `display:none` on `.mat-input-suffix`. The CSS class is only added, when the form control is disabled:

`<md-input-container [ngClass]="{ 'datepicker-disabled': form.get('someValue').disabled }">`

`.hv-datepicker-disabled .mat-input-suffix {
  display: none;
}`

So, the datepicker button is only displayed when the input is enabled.

The first version of the datepicker is great so far. I would also appreciate a built-in solution for disabled datepicker inputs :-)

**Comment by mmalerba** [comment]
This has been fixed, disabling the input will now also disable the popup. It is also possible to get the old behavior by setting `disabled` on the `<input>` and `disabled="false"` on the `<mat-datepicker>`
