### ISSUE TITLE
Md-datepicker broken selection indicator

### ISSUE THREAD

**Issue by taokakao** [angular/material2#4701]
#### Bug

When used in Chrome under Os-x, then date picker's selection indicator changes form to elliptical.

#### What is the expected behavior?

Date picker's selection indicator is in form of circle.

#### What is the current behavior?

When used in Chrome under Os-x, then date picker's selection indicator changes form to elliptical.

#### What are the steps to reproduce?

No special precondition, example code copied to blank project from Material website:
```
<md-input-container>
<input mdInput [mdDatepicker]="myDatepicker" placeholder="Starting">
<button mdSuffix [mdDatepickerToggle]="myDatepicker"></button>
</md-input-container>
<md-datepicker #myDatepicker></md-datepicker>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4.1.1
Material 2.0.0-beta.5
TypeScript 2.2.2
Os-x Sierra 10.12.1
Chrome  58.0.3029.110 64bit

#### Example

<img width="313" alt="screen shot 2017-05-21 at 07 07 57" src="https://cloud.githubusercontent.com/assets/1310147/26281368/e841c824-3df4-11e7-8171-3ecd2e245c81.png">

**Comment by crisbeto** [comment]
I can't reproduce it @taokakao. Perhaps there are some global styles on your page that also end up leaking into the datepicker (e.g. a CSS reset)?

**Comment by taokakao** [comment]
Yes, on new project I can't reproduce it as well. Sorry :-)

**Comment by crisbeto** [comment]
Can inspect the styling to see what may be causing it? It could still be valuable to set some default on the datepicker so it's not affected by it in the future.

**Comment by taokakao** [comment]
I inspected. Totally my fault, no defaults needed, I guess. There were paddings for `th:first-child`, `th:nth-child(n+2):nth-last-child(n+2)` and `th:last-child` set.

**Comment by crisbeto** [comment]
Ah thanks, not much we can do about those, apart from sprinkling `!important` all over the place. My initial thought was that it could be something with `box-sizing: border-box`.
