### ISSUE TITLE
md-slide-toggle: has no focus indicator

### ISSUE THREAD

**Issue by RemKolomna** [angular/material2#471]
* **Do you want to request a *feature* or report a *bug*?**
It is a bug

* **What is the current behavior?**
md-slide-toggle has no focus indicator

* **If the current behavior is a bug,
please provide steps to reproduce and if possible a minimal demo of the problem**

Just open a demo-app, go to Slide Toggle, click on the first slide toggle control and press Space key. The control should display focus indicator

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.

I tested on Windows with Firefox and Chrome browsers
It works in Material1.

**Comment by jelbourn** [comment]
@DevVersion follow-up for your initial PR?

**Comment by DevVersion** [comment]
@jelbourn Yeah, definitely. Will work on that as soon as possible.
