### ISSUE TITLE
Progress bar with sliding control

### ISSUE THREAD

**Issue by magarbikram** [angular/material2#4710]
#### feature request, or proposal:
A feature request for adding slide control in progress bar itself. Now we can set it programmatically binding a data value, but user couldn't change value by dragging. Slider doesn't have buffer line.

#### What is the expected behavior?
Ability to slide/change the progress value of progress bar

#### What is the current behavior?
A progress bar without an ability to change the value like a slider control.

#### What is the use-case or motivation for changing an existing behavior?
A very general use case will be a video/audio control where, user can go back or forward by sliding within a buffered zone. Could use slider but it doesn't have a buffer feature

**Comment by jelbourn** [comment]
This isn't really the intended interaction pattern for the progress bar (especially WRT accessibility). I recommend using a combination slider + progress bar.
