### ISSUE TITLE
Toolbar fixed? it would be possible?

### ISSUE THREAD

**Issue by henriqueweiand** [angular/material2#4714]
#### Bug, feature request, or proposal:

The documentation does not specify any way to keep the toolbar fixed so the page scroll will understand its whole

#### What is the expected behavior?

A small example
![sem titulo](https://cloud.githubusercontent.com/assets/6539492/26307710/5693d1a0-3ecc-11e7-81b1-5c60570f1de0.png)

#### What is the current behavior?

[https://material.angular.io/components/component/toolbar](https://material.angular.io/components/component/toolbar)

#### What is the use-case or motivation for changing an existing behavior?

[https://material.angularjs.org/latest/api/directive/mdToolbar](https://material.angularjs.org/latest/api/directive/mdToolbar)

**Comment by DevVersion** [comment]
Normally you'd make the toolbar fixed by just using your own CSS

```css
.my-toolbar {
  position: fixed;
  top: 0
}
```

But in some situations you place your `md-toolbar` inside of the `md-sidenav-container` and the sidenav content will live in another layer (due to `transform: translate3d(0, 0, 0)`).

Also I'm not sure if there should be like an attribute to make the toolbar fixed. (Similar as the `fullscreen` attribute for the sidenav container).

cc. @jelbourn

**Comment by jelbourn** [comment]
My stance is that the toolbar is just a colored box that you can place or position however is necessary for your app.

**Comment by DevVersion** [comment]
@jelbourn Yep true. My statement was more directed to the fact that the `md-sidenav-container` does elevate into another layer and that it's not possible to have any fixed content inside of it.

It may be worth adding a note about this to the sidenav overview.

**Comment by netlander** [comment]
i thought the toolbar was a component of the Angular Material library and as such it needs to be designed to play nice with other components from the same library.

**Comment by gibsonsyd** [comment]
I have a fixed mat-toolbar after moving the mat-toolbar out of the mat-sidenav-content (placed mat-toolbar above the mat-sidenav-container).

**Comment by LeoDupont** [comment]
So did anyone manage to have a fixed `mat-toolbar` inside a `mat-sidenav-container`?
This is a very basic need for a material app.

**Comment by canerelci** [comment]
I really don't understand why a toolbar is expected to be a styled div element but not a proper toolbar. A toolbar is a UI element which mostly has a static position, accessible at any time. So, when you see a component called "toolbar", you expect it to behave this way. But this one scrolls with the content and everyone is trying to find a workaround.

Don't you think there should be a built-in attribute of the component, something like `[fixed]="true"`?

**Comment by alsami** [comment]
For everyone that is still looking for a solution together with the sidenav, please have a look at this sample:

https://stackblitz.com/edit/angular-material-fixed-sidenav

**Comment by fabrizziocht** [comment]
any solution for this problem?

**Comment by alsami** [comment]
Yes, my answer above, even though it was down voted :)

**Comment by fabrizziocht** [comment]
@alsami but <mat-toolbar> is out of <mat-sidenav-content>, what if I would like to use mat-sidenav mode over like android app?, in this case is necessary to cover the mat-toolbar.

**Comment by alsami** [comment]
You can do that programmatically. Wrap the toolbar in a separate component and place it according to the mode. You need some extra work with media queries and breakpoint observer anyway. This was just a simple sample. A more detailed sample can be found [here] (https://github.com/alsami/Etdb.Web.Angular/blob/master/src/app/core/containers/layout.component.ts)
