### ISSUE TITLE
Hyperlinks doesn't work on material design buttons

### ISSUE THREAD

**Issue by Gicus** [angular/material2#4717]
#### Bug, feature request, or proposal:

Hyperlinks doesn't work on material design buttons

#### What is the expected behavior?

Redirect or start downloading from specified url

#### What is the current behavior?

When yo click on a md button with an hyperling, is happening noting.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
<!button class="main-button" md-button ><a href='/assets/tracks/kml_tracks/bike_tracks/01resita.kml'>Download</a></button>

<button class="main-button" md-button ><a href='/assets/tracks/kml_tracks/bike_tracks/01resita.kml'>Download</a></button>

#### What is the use-case or motivation for changing an existing behavior?

It more like a bug than like 
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material 2, Angular 2

**Comment by donroyco** [comment]
Please use the template or fix the code to see or reproduce the issue.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template (including steps for reproduction), which gives the team the information needed to investigate.
