### ISSUE TITLE
Ability to assign class to dialog

### ISSUE THREAD

**Issue by jbojcic1** [angular/material2#4718]
Feature request:

When I want to set dialog width from code I see that style is set to cdk-overlay-pane element but if I want to do that from css I don't have a way as I cannot set any class to cdk-overlay-pane.

This is useful when you need responsive widths so that you can write media queries which is imo a lot cleaner way than listening to window resize and changing width from code with updateSize method.

**Comment by donroyco** [comment]
Already mentioned / discussed in #4012

**Comment by jbojcic1** [comment]
@donroyco what's the status of that? I can create a PR for this if it's not already done.

**Comment by donroyco** [comment]
No further development on the issue, as far as I know.

**Comment by jbojcic1** [comment]
Ok. Will create it
