### ISSUE TITLE
How to bring focus to an md-input?

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#472]
I'm having some trouble figuring out how to programmatically set focus on a `<md-input>` used as a search bar.  My application hides the input (sets a CSS class with `display:none`) until the user clicks an icon indicating he'd like to perform a search.  At this point, the CSS is changed (the class is removed) to reveal the input.  I would like to automatically bring focus to it at this point.  I've tried:

**Template**
```
<md-input [class.hidden]="searchOn" #searchbar>
<button (click)="onSearch(searchbar)">Start Search</button>
```
**Component**
```
onSearch(searchbar){
  searchbar.focus();  // <-- Exception. focus is not a method
  searchbar.focused = true; // <-- Exception. setting a property that has only a getter
}
```
How do you programmatically set focus on `<md-input>`?

**Comment by jelbourn** [comment]
A `focus` method has been added on master and will be in the next release. See #449

**Comment by eladdo92** [comment]
With the `focus` method we can subscribe to the focus _event_, but we still can't set the focus on :(
