### ISSUE TITLE
Datepicker minDate - error is raised when date is exactly min date

### ISSUE THREAD

**Issue by mihaSoro** [angular/material2#4725]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?
When minDate is set for the datePicker, a mdDatepickerMin error should be raised only if the date is earlier than the minDate.

#### What is the current behavior?
For the moment, when setting minDate, the date for exactly min date is NOT unselectable, which means you can select it, but it nevertheless raises an error. I think it should be either unselectable and raise an error or selectable and not raise the error.

#### What are the steps to reproduce?
Set up a minDate restiriction for the datepicker and try to select the exact min date, and check the fact that it raises an error while it is still selectable.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, Material 2

**Comment by willshowell** [comment]
I believe #4649 will fix that

**Comment by PhilipSultanescu** [comment]
Fixed in #4649

**Comment by mihaSoro** [comment]
Great! This was fast!
