### ISSUE TITLE
ng-click on md-datepicker is not trigger by clicking the calendar icon

### ISSUE THREAD

**Issue by duyh90** [angular/material2#4728]
#### Bug, feature request, or proposal:
I have a ng-click function registered on a md-datepicker directive, which changes the disabled status of a date picker, i.e. clicking the datepicker should turn it from disabled to enabled.

However only clicking the date part does the job. Clicking the calendar icon doesn't trigger the function.

#### What is the expected behavior?
Clicking both the date and the icon should trigger the ng-click call.

#### What is the current behavior?
Clicking the calendar icon doesn't trigger the ng-click call.

#### What are the steps to reproduce?
See https://codepen.io/duyh90/pen/LyMzap

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
See the codepen.

**Comment by jelbourn** [comment]
You're looking for https://github.com/angular/material/

**Comment by duyh90** [comment]
Thanks. Filed https://github.com/angular/material/issues/10679.
