### ISSUE TITLE
Input not getting disabled when using formControlName 

### ISSUE THREAD

**Issue by radoslavpetranov** [angular/material2#4731]
#### Bug:
Using `formControlName` with an input screws up the `disabled` attribute rendering the input `enabled` instead

#### What is the expected behavior?
The input needs to be disabled

#### What is the current behavior?
The input is enabled

#### What are the steps to reproduce?
http://plnkr.co/edit/8Ng4s66r3gw2I0QbINn0?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I want to disable my input

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.0.2
node: 6.10.0
os: win32 x64
@angular/animations: 4.1.1
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1

**Comment by willshowell** [comment]
I believe this is working as expected. See https://github.com/angular/material2/issues/2667#issuecomment-275280698

Similar discussion: #4219

**Comment by radoslavpetranov** [comment]
Thanks for the clarification - no issue here in that case.
