### ISSUE TITLE
Datepicker wrong german format

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4736]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Correct german date format in german locale. (dd.MM.yyyy)

#### What is the current behavior?
Wrong german date format in german locale (d.M.yyyy)

#### What are the steps to reproduce?
Set this in app module:
{provide: LOCALE_ID, useValue: 'de-DE'}

#### What is the use-case or motivation for changing an existing behavior?
Correct date format :-)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 4.1.3, md2 beta 5

#### Is there anything else we should know?
I've opened an issue at the angular repo as the date pipe has the same bug:
https://github.com/angular/angular/issues/16838

**Comment by mmalerba** [comment]
This is a limitation of the native JS `Date` object which is used by the `NatvieDateAdapter`. In the future material will provide other date adapters that can handle parse formats out of the box, in the mean time you can write your own custom adapter. This is all explained here: https://github.com/angular/material2/blob/master/src/lib/datepicker/datepicker.md
