### ISSUE TITLE
Navtabs dynamic width

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#4738]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
When the innerHtml of a tab link changes, the underline should refresh its witdh.

#### What is the current behavior?

You have for example these nav tab links:
Tab 1 | Tab 2 | Tab 3

Now change the label of 'Tab 1' to 'Bananarama' which is much longer than 'Tab 1'.
The active underline will stay at the width of 'Tab 1'.

Edit: When removing the nav-tabs component from dom and re-add after a few milliseconds the underline will be correct. Looks like it's only calculated onInit

#### What is the use-case or motivation for changing an existing behavior?
Dynamic tab labels

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 4.1.x, md2 beta 5

**Comment by jotatoledo** [comment]
Would love to see this working

**Comment by andrewseguin** [comment]
Perhaps we could add a mutation observer to the component to check if any mutations occur that were not additions/removals. 

@crisbeto What do you think about the best way is to use the mutation observer here?

**Comment by crisbeto** [comment]
Since we allow HTML in the tab, we don't have a choice, apart from the `MutationObserver` (we could've used `ngOnChanged` if the label was coming from an `@Input`). We can use [the same approach](https://github.com/angular/material2/blob/e4789c7b88975b1811c97b9bed61b5278def0a7c/src/lib/tabs/tab-header.html#L11) that we have on the regular tabs.

**Comment by andrewseguin** [comment]
Seems good to me, except we'll be applying extra ink bar alignments since the ripple causes mutations as well (same in tabs). Would be nice to have a good way to filter those out as mutations

**Comment by crisbeto** [comment]
AFAIK the MutationObserver has some (not too granular) ways of filtering. We'd need to add those to the `cdkObserveContent` directive.
