### ISSUE TITLE
Create helper for sticky positioning

### ISSUE THREAD

**Issue by jraadt** [angular/material2#474]
- **Do you want to request a _feature_ or report a _bug_?**
  feature
- **What is the current behavior?**
  There is no $mdSticky for components like md-subheader inside a md-list.
- **What is the expected behavior?**
  I would expect a service like $mdSticky from Material v1 to allow components like md-subheader inside a md-list to stick when scrolling.
- **What is the motivation / use case for changing the behavior?**
  To provide the same functionality that is present in Material v1.

**Comment by DevVersion** [comment]
Once this feature will be added, we should test that really thoroughly. 
- The current implementation in Material 1, is shaking on several touch devices / browsers.

It should also check, if the current browser supports `sticky` positions natively.

**Comment by rolandjitsu** [comment]
At least the toolbars should be something we can make sticky. It does look much better when the toolbar is always at the top while you scroll the content (in some cases).

**Comment by jefferson-willian** [comment]
@rolandjitsu actually you can do that with layouts. Just use two columns, one for the toolbar and another for a scrollable content. It would be something like that:

```
<div layout="row">
  <div layout="column" layout-fill>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <h3>
          <span>Title</span>
        </h3>
      </div>
    </md-toolbar>
    <md-content flex>
    </md-content>
  </div>
</div>
```

**Comment by btroncone** [comment]
Any update or examples of this in practice? This would be a very helpful addition as the majority of MD layouts utilize a sticky header by default. 👍

**Comment by DevVersion** [comment]
@btroncone Thanks for the reminder. This feature hasn't been marked as a high priority for the beta, but I will try to look into it soon - Here is my (pretty old) proposal for this feature.

- [See this Google Document](
https://docs.google.com/document/d/1_8G0JXpH8lPmI_wNGtdLCYyhXCs_nLCg5r4vDl8dUA8/edit?usp=sharing
)

**Comment by btroncone** [comment]
That would be amazing, thanks for the feedback and quick response! 👍

**Comment by trainerbill** [comment]
Would this be better implemented in flex-layout?

**Comment by DevVersion** [comment]
@trainerbill I don't think that you can categorize this into `flex-layout`

As from the name, flex-layout is a set of directives to build a layout using Flexbox CSS.

**Comment by f-mon** [comment]
will this feature be implemented?

**Comment by ashishdoneriya** [comment]
1 year and still open

**Comment by DevVersion** [comment]
@ashishdoneriya We are still in beta and other components have bigger priorities right now. This issue is just here for tracking.. and not for giving a ETA.

**Comment by jofftiquez** [comment]
Guys what happened to the "This feature will be added"? :( I'm thinking of switching to Vue coz of it's material framework. Material 2 should be updated.

**Comment by ashishdoneriya** [comment]
Nice idea @jofftiquez . Thanks

**Comment by mackelito** [comment]
Has anyone tried out this? https://github.com/google/angular-sticky-element

**Comment by antonyRoberts** [comment]
@jelbourn and @kara. Has, there been any movement on this? It looks like the intern who was assigned to this, is no longer working on it.

**Comment by reppners** [comment]
Need to make a decision on a project wether to put effort into implementing sticky headers/look for an alternate implementation or wait on implementation in CDK/Material.

Is there any ETA or status on this feature that can help make this decision?

**Comment by ashishdoneriya** [comment]
I think there is a special team for thumbs down every comment which is not in favour of angular.

**Comment by mackelito** [comment]
Is the sticky header in latest? (would love to test it out) :)

**Comment by tomgruszowski** [comment]
@mackelito given the issue backlog is 800+ long, I don't think this team has the bandwidth for anything but bugfixes. I still use bootstrap to complement my UIs as ng-material is severely lacking on so many things. The toolbar on the demo site is mostly custom code.

**Comment by michaeljota** [comment]
@odahcam Oh! God no... Please, just don't use Popper.JS. I'm sure it's great, but it's a real pain to integrate it with Angular. And I ain't sure how this could be integrated for this task.

**Comment by jofftiquez** [comment]
Wow I didn't know I got downvoted so hard on this thread hahahaha. There should be a notification for this. Guys! Switch to VueJs! It's better! 

I'm kidding of course 😀 Enjoy the breaking changes! 🎆 😛

**Comment by odahcam** [comment]
Why not to just use `position: sticky` with some JS sticky polyfill?

**Comment by reppners** [comment]
As @odahcam points out recent browsers have sufficient support for `position: sticky` so this feature can be implemented quite easily.

Necessary styles:
```css
.sticky-header {
  position: -webkit-sticky;
  position: sticky;
  top: 0;
  z-index: 2;
}
```

Personally I don't need to support ancient browsers that are not capable of doing it with pure css so no fancy JS polyfilling needed.

**Comment by pppdns** [comment]
Currently 14% from the global browser usage doesn't support `position: sticky`, most of them are 5 years old versions (e.g. IE11 from 2013)
https://caniuse.com/#search=sticky

![image](https://user-images.githubusercontent.com/684597/40839965-fd454786-65a4-11e8-9fe4-0c69e6b13527.png)

**Comment by jeremyputeaux** [comment]
Exactly. To me this helper is mainly supposed to stick and unstick on
scroll. We see this behavior more and more often.

**Comment by michaeljota** [comment]
Angular should work with IE11 so I don't think this will be an actual option for the team. `display: sticky` only works out the box properly in 5% of the browsers. So even if they didn't have to support IE11, I don't think this is the way to go. 

Regardless the scroll behavior, I think this could be easy doable with an scroll event, just changing the position of the sticky component.

**Comment by gangsthub** [comment]
is this issue closed by #11483?

**Comment by odahcam** [comment]
@michaeljota 

> Regardless the scroll behavior, I think this could be easy doable with an scroll event, just changing the position of the sticky component.

This certainty would be easy and awesome if it comes with the helper, would be from a great help.

**Comment by jelbourn** [comment]
Closing this since there are no plans to add this feature. We believe that using the native `position: sticky` is the best approach moving forward.

**Comment by odahcam** [comment]
As most of sticky positioned stuff is all about layout and does not blocks users of doing anything if it don't work and we have 85% of global support for this feature, I think you'r right.
