### ISSUE TITLE
MdProgressBar doesn't update if no properties binding.

### ISSUE THREAD

**Issue by ParksProjets** [angular/material2#4741]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

The progress bar must be updated when changing a property directly with the MdProgressBar component.  

#### What is the current behavior?

The progress bar is only updated when a property is changed in the template, with a property binding.
When we get the MdProgressBar component with `@ViewChild` and modify the property `value`, the progress bar isn't updated.

#### What are the steps to reproduce?

Open the link below, and click on "Change value". The progress bar isn't updated but then if you click on "Change color" (the property is binded in the template), the progress bar will be updated.

https://embed.plnkr.co/UlmDnDT9RZJm4u6yfE5D/

#### Is there anything else we should know?

It seems that `[ngStyle]` properties in MdProgressBar template are not updated when we use direct assignation of the property and not a property binding.

**Comment by willshowell** [comment]
It's because MdProgressBar uses OnPush. Why would you not want to use the property binding?

I suppose the progress bar could inject `ChangeDetectorRef` and allow users to manually `markForCheck()` but that seems hokey just to support directly assigning the value.

**Comment by josephperrott** [comment]
After investigating a bit more, we will not be adding this as you are able to simple use the property binding of `value`.

For instance:
`[value]="50"`
