### ISSUE TITLE
add an "md-no-asterisk" input to to mdSelect

### ISSUE THREAD

**Issue by ss-bb** [angular/material2#4745]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
add a "md-no-asterisk" to a md-select tag that prevent the show of the asterisk when the md-select is require

#### What is the current behavior?
there is no "NOT HACKY" way to remove the asterisk when md select is require

#### What are the steps to reproduce?

use any <md-select required placeholder="look I have a asterisk ->"></md-select>

#### What is the use-case or motivation for changing an existing behavior?
To be able to not display the asterisk even if the field is require

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
X

#### Is there anything else we should know?
something exist for input -> hideRequiredMarker But nothing exist for ng-select

**Comment by willshowell** [comment]
Probably should be `hideRequiredMarker` to match mdInput's property (#3681)

**Comment by jelbourn** [comment]
This is part of mat-form-field now

**Comment by ss-bb** [comment]
thanks for this work for the future generation :).
