### ISSUE TITLE
md-checkbox inside <div md-dialog-content> shows scrollbar

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#4748]
#### Bug, feature request, or proposal:
Bug, I think.

#### What is the expected behavior?
When you use a md-checkbox inside a `<div md-dialog-content>` container, the scrollbar must not be shown.

#### What is the current behavior?
The scrollbar is beeing shown when you use the following combination (if you do not use div md-dialog-content attribute, it works just fine):

```
<div md-dialog-content>
      <md-checkbox>This is just a test text</md-checkbox>
</div>
```

#### What are the steps to reproduce?
Just open a md-dialog with the above discribed setup.

plunker: https://plnkr.co/edit/788SUTEm6NPkOCccXimQ?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Use the md-checkbox inside md-dialog

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.0.4
node: 6.10.3
os: win32 x64
@angular/animations: 4.1.3
@angular/cli: 1.0.4
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3

Typescript: 2.3.2

#### Is there anything else we should know?
no

**Comment by tinayuangao** [comment]
There's no scrollbar in your plunker example.

**Comment by julianobrasil** [comment]
@tinayuangao, there is a vertical scrollbar (I'm using Chrome 58.0.3029.110). Maybe you didn't see it because I put just one component in the plunker, but it's shown in the image bellow:

![image](https://cloud.githubusercontent.com/assets/25405143/26381947/d4b3574e-3ffe-11e7-9ff8-cd3e5e84642b.png)

**Comment by julianobrasil** [comment]
@tinayuangao , I refactor the plunker: https://plnkr.co/edit/HRoFPig0sr52vWOw1IfD?p=preview

Now it's easy to see the scrow bar:

![image](https://cloud.githubusercontent.com/assets/25405143/26382156/ab1d8c22-4000-11e7-8b21-725b1b5dddd4.png)

**Comment by julianobrasil** [comment]
Just opened a new issue with more details: #4764
