### ISSUE TITLE
Command "npm start" stopped working on quickstart on installing "Material" via command prompt

### ISSUE THREAD

**Issue by saurabhit49** [angular/material2#4749]
#### Bug, feature request, or proposal:
I have downloaded latest "Angular QuickStart (named quickstart-master)" and installed "Latest Material" using "npm install --save @angular/material" after performing "npm install" for Angular 4.

I am receiving the following error....
node_modules/@angular/material/typings/button/button.d.ts(40,22): error TS2420:
Class 'MdButton' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdButton'.
node_modules/@angular/material/typings/button/button.d.ts(40,39): error TS2507:
Type '(new (...args: any[]) => CanDisable) & typeof MdButtonBase' is not a const
ructor function type.
node_modules/@angular/material/typings/checkbox/checkbox.d.ts(43,22): error TS24
20: Class 'MdCheckbox' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MdCheckbox'.
node_modules/@angular/material/typings/checkbox/checkbox.d.ts(43,41): error TS25
07: Type '(new (...args: any[]) => CanDisable) & typeof MdCheckboxBase' is not a
 constructor function type......

------------------------------------------
If i just replace "node_modules\@angular\material" folder with the old copy then everything works fine. So it seems that latest material scripts has some issue or i was missing anything else. I have attached screenshot of full error.

![screenshot](https://cloud.githubusercontent.com/assets/7238023/26359153/541fe50e-3ff2-11e7-8187-a059679fcee2.png)

**Comment by willshowell** [comment]
Please see https://github.com/angular/material2/issues/4512. Typescript 2.2 is required

**Comment by jelbourn** [comment]
What @willshowell said

**Comment by furcino** [comment]
I changed to 2.2 and it does not work anyway.

**Comment by WonderfulNature** [comment]
I changed to 2.2 but still it shows the same error
![error ts](https://user-images.githubusercontent.com/29972233/27947508-c1130b3e-6313-11e7-8785-38e1a59e17b2.PNG)

**Comment by shelwig** [comment]
I had to follow the instructions in the following article: https://stackoverflow.com/questions/43973533/angular-4-with-material
