### ISSUE TITLE
SnackBar not showing

### ISSUE THREAD

**Issue by victorblq** [angular/material2#4752]
#### Bug
SnackBar not showing inside ".then" of a promise

#### What is the expected behavior?
The SnackBar should appear when is called

#### What is the current behavior?
The SnackBar is not showing when is called, it shows up when I click the button in a second time.

#### What are the steps to reproduce?
I'm using AngularFire to login a user with google account, I'm using the pop up login method and a button to call the pop up, it returns a promise, in the ".then" method I verify if the email is of a determined domain, if isn't I call a SnackBar, but the SnackBar doesn't appear, if I click the Login button again the SnackBar shows up. 

```javascript
login()
    {
        this.afAuth.auth.signInWithPopup( new firebase.auth.GoogleAuthProvider() )
            .then(( result ) =>
            {
                this.showErrorToast();
                if ( result.user.email.split( "@" )[1] != "mydomain.com.br" )
                {
                    let snackBarRef = this.snackbar.open('Error message', null, {duration: 2000});
                    this.afAuth.auth.signOut();
                }
                else
                {
                    this.router.navigate( ["home"] );
                }
            } )
            .catch(( exception ) =>
            {
                console.log( exception );
            } );
    }
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.1.0
Material: 2.0.0-beta.5
OS: Linux Mint
TS: 2.2.0
Browser: Chrome  56.0.2924.87 (64 Bits)

**Comment by julianobrasil** [comment]
Did you import BrowserAnimationsModule as said in [getting started guide](https://material.angular.io/guide/getting-started)?

**Comment by victorblq** [comment]
Yes, it is imported. If I create a method, put the snackbar inside this method and call it from a button (click) the snackbar works fine.

**Comment by willshowell** [comment]
@victorblq here is an example of it working when called within a promise chain

https://plnkr.co/edit/VRmYdEZoRUamtC3c0z6U?p=preview

Can you reproduce the issue in an isolated example?

**Comment by julianobrasil** [comment]
@victorblq , supposing the page don't navigate to home (which would indicate there is erros in your general logic) and do  not show any exception message in the console.... did you try other browsers? Is the login function really being called at the first click?

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via Plunker.
