### ISSUE TITLE
Datepicker show out of the page

### ISSUE THREAD

**Issue by FilipeQ** [angular/material2#4765]
#### Bug, feature request, or proposal:
Datepicker open out of page when page don't have space at bottom

#### What is the expected behavior?
Datepicker open at top of container if bottom don't have space

#### What is the current behavior?
Datepicker open out of the page

#### What are the steps to reproduce?
You can use Angular material 2 docs. [datepicker docs](https://material.angular.io/components/component/datepicker)
Resize page and open datapicker

[img](https://ibb.co/mbwDVv)

**Comment by willshowell** [comment]
Duplicate of #4406
