### ISSUE TITLE
date-adapter `parse`

### ISSUE THREAD

**Issue by fxck** [angular/material2#4769]
I'm trying to wrap my head around what's the best approach, I still think it's missing a proper concept of parsers / formatters.

Data coming from the API is going to be in the ISO format `2017-05-24T10:38:28.434Z`, now I have `<input />` with `formControl`, if I implemented custom `parse` function, which would take the `dateFormats.parse.dateInput`, which should (I assume) be the format of the localized date my consumer actually write in the input and pass it to, in my case date-fns', parse function. Now the question is, what do I do with the format I receive from the API? Do I have to actually format it to the localized format **before** `patchValue`ing it to my `formControl`, because otherwise the initial value, which would be in ISO format, would be different from subsequent edit by the user (those will be in the localized format).

cc @mmalerba

**Comment by mmalerba** [comment]
I would recommend creating a date object from the API's response and patching that directly into the `formControl` (no need to reformat it in a new format). 

I'll also mention that part of the reason for having separate parse and display formats is so you can support multiple parse formats, for example, you might have:

```ts
dateFormats.parse.dateInput = ['LL', 'YYYY-MM-DDTHH:mm:ssZ'];
dateFormats.display.dateInput = 'LL';
```

(with an appropriate `DateAdapter` that knows how to handle that).

**Comment by fxck** [comment]
@mmalerba I'm not sure that would work.. setting of the initial value, which happens [here](https://github.com/angular/material2/blob/master/src/lib/datepicker/datepicker-input.ts#L92) uses the same `parse` format as the function that is called on `input` [change](https://github.com/angular/material2/blob/master/src/lib/datepicker/datepicker-input.ts#L228). 

Or you are saying that my custom parse function should handle both native Date as well as my localized input?

**Comment by mmalerba** [comment]
Yes, the `NativeDateAdapter` works with `string`, `Date`, and `number`. In general I think all implementations should at least support `string` and an instance of whatever date implementation that adapter operates on. It would probably be good to call this out in the method docs, would you mind creating a PR?

**Comment by fxck** [comment]
Sure. I'll just finish this date-fns adapter first.

**Comment by areijngoudt** [comment]
@fxck can you share your date-fns based implementation when you finished it? I would like to user it :)

**Comment by fxck** [comment]
I'm using date-fns version that is not even public yet (the current version doesn't support parse with custom format) and I'm also using a copy of all datepicker / date-formats / adapter, all heavily modified since I needed to extend it with datetimepicker mode.. it's not really easily sharable.

But you can try and mess with it if you want, here's the build of the 2.0.0 of date-fns https://github.com/fxck/dfns-builds and here's the adapter https://gist.github.com/fxck/efe4ccff13d99ee9a2dcf82365909168 you'll have to remove the extra methods and fix some imports.

**Comment by robindijkhof** [comment]
@fxck, how did you managed the get the timepicker? Is it a matter of writing your own dataAdapter or is it an undocumented feature?

**Comment by fxck** [comment]
I made it.

**Comment by robindijkhof** [comment]
Is it published somewhere and may I use it? Or is it supposed to be a PR someday?

**Comment by fxck** [comment]
Nah, it's pretty crude. There's probably a private material design spec for a datetimepicker that the official version will be based on one day, so I'd be waste of time.
