### ISSUE TITLE
MdSlider custom thumb label text

### ISSUE THREAD

**Issue by Snesi** [angular/material2#4776]
#### Bug, feature request, or proposal:

Feature request
#### What is the expected behavior?

New Inputs in MdSlider to add a suffix or prefix to the thumb-label-text
#### What is the current behavior?

Thumb label text simply shows a number
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
If you want a slider that has a specific unit, like $, or m2 or min.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material 2
#### Is there anything else we should know?
simply something like this would do:

```html
<span class="mat-slider-thumb-label-text">{{displayPrefix}}{{displayValue}}{{displaySuffix}}</span>
```

**Comment by Snesi** [comment]
If I have time to do this I'll create a pull request tomorrow.

**Comment by willshowell** [comment]
Instead of prefix/suffix, what about something similar to autocomplete's `displayWith`?

*comp.html*
```html
<md-slider
 [thumbLabel]="true"
 [displayLabelAs]="labelFn">
</md-slider>
```
*comp.ts*
```ts
labelFn(value: number): string {
  return `${value} cm`;
}
```

**Comment by Snesi** [comment]
I like that a lot better! Right now I'm using an after pseudo element in
the span of the label in order to show square meters m2 next to the number.
Although I've also had to override the styles to make the label's wrapper
wider.

**Comment by willshowell** [comment]
Yeah, I suppose resizing the label and making sure the animation looks right for a dynamic label string would be pretty difficult

**Comment by YeomansIII** [comment]
Any work being done on this? I can try and implement @willshowell's solution and make a pull request. We need this feature to show slider value as audio track time when dragging. This seems very valuable as it's open to any kind of formatting needed from value to label.

**Comment by iget-master** [comment]
Can someone take a look here? This is an important featore IMO.

For example if you want a slider for a percent value or a currency value.

**Comment by mmalerba** [comment]
Added in #10243

**Comment by pantonis** [comment]
Any example of how it works would be good. Currently material does not have any example on how to use displayValue
