### ISSUE TITLE
What are the risks of using latest changes from master?

### ISSUE THREAD

**Issue by MaximeAnsquer** [angular/material2#4780]
Hello,

I would like to use a multiple select which is not available yet on the latest release, so I am thinking about changing my dependency to the master branch (npm install --save https://github.com/angular/material2-builds.git).

Should this version of Angular Material be used only for "playing with the latest changes" ? Are there any risks in using it in a real app, do you recommend not to do so?

Thank you very much.

**Comment by willshowell** [comment]
We've been using it for a couple months with no issues, along with many other users. It takes a little diligence when upgrading to new builds, but breaking changes don't come often. Rarely, minor styling regressions occur, but fixes for those come fast.

That said, multiple select is available in beta-5. [See here](https://plnkr.co/edit/EIDlTuxOgqS6dZ6RSM8T?p=preview) for an example.

**Comment by MaximeAnsquer** [comment]
Ok that's great, thanks a lot! (My bad, I was actually using beta-4)
