### ISSUE TITLE
MdRadioGroup change event conflicting with native change event

### ISSUE THREAD

**Issue by THLAP** [angular/material2#4782]
#### Proposal / Bug:

The MdRadioGroup component with the change event wired up and a text input as one of its children receives the text inputs native change event bubbled up after a user types in the input and removes focus.  Should native browser event names be used in components?

#### What is the expected behavior?
The component shouldn't respond to native change events bubbled up from its children.

#### What is the current behavior?
The component responds to native change events bubbled up from its children.

#### What are the steps to reproduce?

In the plunker if you click between the radio buttons you will see it logs the MdRadioChange event.  Then when you type into the text control and click away you receive a native change event in the radioGroupChange handler.

[Plunk](http://plnkr.co/edit/FyHbqTBiBLTBDOcNDiJE)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular Material - 2.0.0-beta.5

**Comment by tinayuangao** [comment]
@THLAP Any special reason you need to put `input-container` inside a radio button group?

You can add `(change)="$event.stopPropagation()"` to `input-container`. Example: http://plnkr.co/edit/taAAI2hDKrsNzOVqJQzl?p=preview

**Comment by THLAP** [comment]
@tinayuangao I have requirements to build a control with a set of radio buttons and each one should have a text field below it to capture custom text input.  Nesting them this way worked well with my layout.  I did end up going with your solution to get around the issue.

I was really wondering should material components have exposed events that match native DOM events?  This is one case where it causes an issue and there are other material components that have "change" events.  Not sure if this could become more of an issue at some point.

**Comment by tinayuangao** [comment]
@THLAP If it's only for layout purpose, you are suggested to put `input-container` outside radio button groups and use css for layout. 

The `change` events are for angular forms.
