### ISSUE TITLE
Docs: reset scroll when switching between components

### ISSUE THREAD

**Issue by epelc** [angular/material2#4783]
#### Bug, feature request, or proposal:

I propose reset the scroll position to the top when switching between components on the docs.

#### What is the current behavior?

It stays where you are. ie go to autocomplete scroll half way down then go to `input` and you are halfway down that page when you probably want to be at the top.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

https://material.angular.io/components/component/select

#### What is the use-case or motivation for changing an existing behavior?

Usability

**Comment by mmalerba** [comment]
Please file against docs site issues against https://github.com/angular/material.angular.io
