### ISSUE TITLE
revalidate form with updateValueAndValidity or markAsDirty not working

### ISSUE THREAD

**Issue by mackelito** [angular/material2#4784]
#### Bug, feature request, or proposal:
Bug (?)

#### What is the expected behavior?
Form should revalidate 

#### What is the current behavior?
The input needs to blur to trigger validation

#### What are the steps to reproduce?
https://plnkr.co/edit/LgEn9t0X2h6BTHGwyJOW?p=preview

As you can see in the plunker I have tried several ways to revalidate but it seems it is not triggered?

**Comment by mikechamberlain** [comment]
I can't see how your plunkr demonstrates the problem.

**Comment by mackelito** [comment]
@mikechamberlain just fill out the form (top to bottom) you´ll see that once a adress is selected from the dropbox the for is still not valid until you set focus to the adress field.

Once valid the button will be enabled

**Comment by mackelito** [comment]
For reference: https://stackoverflow.com/questions/44189424/angular-form-dont-validate-when-adress-is-selected/44189699#44189699
