### ISSUE TITLE
Sidenav doesn't respect opened property

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/material2#479]
**Note: for support questions, please use one of these channels:**
https://github.com/angular/material2/blob/master/CONTRIBUTING.md#question.
This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Sidenav is always opened when `opened` property is specified even if `opened="false"`.

* **If the current behavior is a bug,
please provide steps to reproduce and if possible a minimal demo of the problem**
http://plnkr.co/edit/fwXhGYTCLxDjM6qMxXDf?p=preview

* **What is the expected behavior?**
Sidevan should be closed when `opened="false"`

**Comment by jelbourn** [comment]
I believe @DevVersion fixed this in #444
