### ISSUE TITLE
Create MdMenu Dynamically

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#4791]
#### Bug, feature request, or proposal:
Feature request?

#### What is the expected behavior?

Could create a bunch of md-menu using a *ngFor, but it's apparently not possible because of the reference template variable.

#### What is the current behavior?

Apparently there's no direct way to create an unknown number of md-menu (at least by just following the official documentation), because of the static nature of template reference variables and the need to use them in the trigger component (mdMenuTriggerFor).

#### What is the use-case or motivation for changing an existing behavior?

If I'm wrong (if there is, in fact a way to do it) does any one have a good reference where I can find a way to dynamically create an MdMenu? I'd like to create a bunch of them (to put in the last column of a table - the number of rows of the table is not known). Following [material.angular.io](https://material.angular.io/components/component/menu), to create a md-menu I should be able to:

1 - Create a template reference variable dynamically (for the md-menu component)

2 - Reference the dynamically created template reference variable (to use with the [mdMenuTriggerFor] attribute of the trigger)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cli: 1.0.4
node: 6.10.3
os: win32 x64
@angular/animations: 4.1.3
@angular/cli: 1.0.4
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3

Typescript: 2.3.2

#### Is there anything else we should know?

I've already post a question about this on stackoverflow, but as far as I googled, there is no answer to it. So I think it's a no-answer question (at least a no easy answer one?). It's too late now here in Brazil, but tomorrow morning I'll try encapsulate the trigger and the menu in a component. It seems to be the only thing I didn't try until now (by the way, now it seems to be the first one I should have tried)

**Comment by julianobrasil** [comment]
Decided to close for a now.  I'll try the encapsulating approach. I think it's a acceptable solution, if it works.

**Comment by gtamas** [comment]
Any update on this?

I'm having the same issue. Is there a way to dynamically generate this?

**Comment by julianobrasil** [comment]
Encapsulating it was the way. Make a component and put the menu and the trigger inside it. Then you provide information to it by the necessary @Input() you want, and get information of it from the @Output you create. 

For the @Ouputs, you can choice to bury all the logic for the menu items click inside the menu comoponent and just emit the result of the processing or you can just emit any kind of signal value (a boolean, for example) to fire the processing in the host.

It worked like a charm.

**Comment by julianobrasil** [comment]
@gtamas , I build this example plunker: https://plnkr.co/edit/qYWvjR?p=preview

**Comment by Splaktar** [comment]
That Plunker was broken, so I created an updated version here: https://plnkr.co/edit/z74u4j?p=preview
