### ISSUE TITLE
md-suffix and md-prefix are shrunk

### ISSUE THREAD

**Issue by Xample** [angular/material2#4794]
#### Bug, feature request, or proposal:
The following code:
```html
        <md-input-container>
            <input mdInput placeholder="Weight" value="42" md-suffix="kg">
        </md-input-container>
```
#### What is the expected behavior?
I expected something like this
![image](https://cloud.githubusercontent.com/assets/944605/26442791/39064124-4136-11e7-9c37-d519413f3c11.png)

#### What is the current behavior?
Yet the whole md-input entry is shrunk
![image](https://cloud.githubusercontent.com/assets/944605/26442749/162aec72-4136-11e7-8b82-b3093ace5187.png)
#### What are the steps to reproduce?
try it here: http://plnkr.co/edit/GpkWUYBtdEYxw6ESoneu?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome 58, MacOS 10.12

**Comment by mackelito** [comment]
hmmm.. it looks like the input is added to the `mat-input-prefix` instead of the `mat-input-infix`?

**Comment by julianobrasil** [comment]
Shouldn't you have put the mdsuffix in another element? Like this:

```
<md-input-container>
            <input mdInput placeholder="Weight" value="42">
            <span mdSuffix>kg</span>
</md-input-container>
```

![image](https://cloud.githubusercontent.com/assets/25405143/26444965/bd398b8a-4114-11e7-900a-5ab468f08728.png)

**Comment by Xample** [comment]
I think you are right, I misunderstood the usage. Thank you
