### ISSUE TITLE
Unable to build angular material used in ASP.NET CORE - Angular 4 app

### ISSUE THREAD

**Issue by pmdauv** [angular/material2#4795]
When building the project many issues are indicated such as: 
 -> Error	TS2420 Class 'MdButton' incorrectly implements interface 'CanDisable'. Property 'disabled' is missing in type 'MdButton'.
-> Error	TS2507	Type '(new (...args: any[]) => CanDisable) & typeof MdCheckboxBase' is not a constructor function type.
-> ...
May someone help to solve these issues?
Thanks for your help.

**Comment by crisbeto** [comment]
What version of TypeScript are you using?

**Comment by stevenmi** [comment]
https://www.typescriptlang.org/#download-links

**Comment by pmdauv** [comment]
What version of TypeScript are you using?

Hi crisbeto, I'm using Typescript 2.3.3

**Comment by pmdauv** [comment]
It seems that the latest angular material release 2.0.0-beta.5 generates these issues when the project is built. I tried to use version 2.0.0-beta.3, the project is built without an issue.

**Comment by crisbeto** [comment]
We've had a few similar issues filed since the last release, but they were resolved by updating to TypeScript 2.2.

**Comment by pmdauv** [comment]
Thanks crisbeto. I'll try your solution.

**Comment by jelbourn** [comment]
Any version of TypeScript >= 2.2 should work. Sounds like Visual Studio might have an old version?
