### ISSUE TITLE
Proposal: divider for select options

### ISSUE THREAD

**Issue by willshowell** [angular/material2#4798]
#### Proposal

It would be nice to have a more convenient way of adding dividers between select options

#### Current Method
```html
<!-- Need the styles for list divider -->
<md-list style="visibility: hidden"></md-list>

<md-select>
  <ng-container *ngFor="let a of b; let last=last">
    <md-divider *ngIf="last"></md-divider>
    <md-option>
      {{ a }}
    </md-option>
  </ng-container>
</md-select>
```

#### Proposed Method
```html
<md-select> 
  <md-option *ngFor="let a of b; let last=last" [dividerBefore]="last">
    {{ a }}
  </md-option>
</md-select>
```

#### Demo

http://plnkr.co/edit/gijHvdO6dbCLik8DbOLL?p=preview

**Comment by CaerusKaru** [comment]
@willshowell can this be closed, now that `mat-divider` is available outside `mat-list`?

**Comment by willshowell** [comment]
@CaerusKaru thanks for the ping (and your work on that divider PR). No longer needing to bring in `mat-list` is good enough for me!
