### ISSUE TITLE
Property 'forRoot' does not exist  on type 'typeof MaterialModule'

### ISSUE THREAD

**Issue by vibingopal** [angular/material2#4799]
#### Bug, feature request, or proposal:
After i  upgraded the angular 2 app from Material Beta 3 release to Beta 5(2.0.0-beta.5). Iam getting 
 Property 'forRoot' does not exist  on type 'typeof MaterialModule'.Could any one help on this please
#### What is the current behavior?
There are no issues when i am working with the 2.0.0-beta.3

**Comment by DevVersion** [comment]
With beta.4 the `forRoot()` method on the `MaterialModule` has been removed.

In the future the `MaterialModule` will be removed completely. Be sure to just import the individual modules on your own (https://github.com/angular/material2/blob/master/CHANGELOG.md#materialmodule)
