### ISSUE TITLE
Unable to bind numbers to MD-Select ngModel 

### ISSUE THREAD

**Issue by Wesselfick** [angular/material2#4802]
BUG : Unable to bind  numbers to select ngModel on page load 

#### What is the expected behavior?
select value from options list on page load 

#### What is the current behavior?
does not select value from list on page load 

#### What are the steps to reproduce?
Was not able to get NgModel to bind in plunker but in my application i don't get this error 
[(http://plnkr.co/edit/YXiUjrFVFpjW5QvBfVFQ?p=preview)]

#### What is the use-case or motivation for changing an existing behavior?
ability to select numbers in select list, currently i have to cast it to string 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.0.3
Material 2.0.0.Beta 5
TypeScript 2.2.2 
Browser Chrome Version 58.0.3029.110 (64-bit)

**Comment by willshowell** [comment]
@Wesselfick Two things:

1. You need to import FormsModule into your AppModule to make the plunker work
2. You were making the option value a string by using `value="{{ num }}"`. You should bind to the property using `[value]="num"`

http://plnkr.co/edit/zrACxE5qZCo6NWEd0rAS?p=preview

**Comment by Wesselfick** [comment]
Thank you, missed that one
