### ISSUE TITLE
Dialog Component Instance

### ISSUE THREAD

**Issue by Kyderman** [angular/material2#4815]
#### Bug, feature request, or proposal:
In Beta 6 (maybe 4 / 5), I cant seem to access anything from dialogRef.componentInstance.

#### What is the expected behavior?
e.g dialogRef.componentInstance.isSaved would return me the value of isSaved from the component.

#### What is the current behavior?
componentInstance is null, there is no way to access the inner variables of the dialog.

#### What are the steps to reproduce?
try using componentInstance after close

#### What is the use-case or motivation for changing an existing behavior?
I want to know the certain state of a dialog after close.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material Beta 6, Angular 4

**Comment by Kyderman** [comment]
Im assuming I need to use an emitter, however, I don;t think there is nice documentation on this.
Additionally, it seems like more work to have to construct an output to get these variables.
If that's the case, cant the dialog self emit its state on close?

**Comment by Kyderman** [comment]
UPDATE:
I accomplished this by using EventEmitter between the components.
No idea if I need to unsubscribe on close though to stop the subscription from being held in memory?

**Comment by 0x4F72** [comment]
I think you need neither the componentInstance nor an EventEmitter to access the values in afterClose - simply pass them as parameter to the close method of the dialogRef

**Comment by rajvengala** [comment]
We are currently on 2.0.0-beta.10. componentInstance is null on quite a regular basis for most dialogs. Unfortunately, we could not pin down the cause.
