### ISSUE TITLE
plan for layout-padding, layout-margin

### ISSUE THREAD

**Issue by vohtaski** [angular/material2#4816]
Is there a plan to include the "Layout Extra" options
as in angular1-material?

`layout-padding`, `layout-margin`, `layout-fill`

https://material.angularjs.org/latest/layout/options#layout-margin-padding-wrap-and-fill

**Comment by aldocaetano** [comment]
Already exists:
https://github.com/angular/flex-layout

**Comment by vohtaski** [comment]
@aldocaetano 
There is `fxFlex`, `fxColumn`, but I can't find `-padding`, `-margin`, `-fill`

**Comment by aldocaetano** [comment]
For this i am using a pure css. I had no enough time for wait they finish :(

**Comment by vohtaski** [comment]
I did the same, I am just thinking if I should use `fxLayoutPadding`, `fxLayoutMargin`, etc
or there will be different naming scheme ..

**Comment by jelbourn** [comment]
Discussions for layout features so go over in https://github.com/angular/flex-layout
