### ISSUE TITLE
bug(checkbox, radio): focus and blur events not triggering

### ISSUE THREAD

**Issue by PhilipSultanescu** [angular/material2#4817]
#### Bug, feature request, or proposal:
The checkbox and radio controls don't trigger the (focus) and (blur) angular events

#### What is the expected behavior?
It should trigger the focus and blur events.

#### What is the current behavior?
Focus and blur events are not triggered, all the other events are triggering ok.

#### What are the steps to reproduce?
Plunker https://plnkr.co/edit/h2OyULESEcE6IBzdAAIG
First controls test only for the focus and blur events, which trigger ok for the input, but not for checkbox and radio.
Second controls habe all the other events attached, which trigger ok.

#### What is the use-case or motivation for changing an existing behavior?
I want to be able to mimic the mat-input-container behaviour with multiple checkboxes or radios, with top label, sub-line, hint text, error validations. 
For this when a a checkbox is focused or blurred I want to toggle the mat-focused class on the parent mat-input-container so the label and underline get highlighted.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested with latest build on 26.05.2017 beta.6

**Comment by DevVersion** [comment]
We have a similar issue for this: #1723
