### ISSUE TITLE
hidden display: none needs to have an !important tag

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#4820]
#### Bug, feature request, or proposal:
mostly a proposal but buggy none-the-less

#### What is the expected behavior?
when using [hidden] I would expect the important tag be applied so functionality works as intended

#### What is the current behavior?
If another class uses display then this attribute will be overridden

#### What are the steps to reproduce?
n/a
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
that hidden works as intended

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4, material 2.0.5

#### Is there anything else we should know?
n/a

**Comment by willshowell** [comment]
AFAICT Material doesn't have any styles for `[hidden]`. That style is coming from somewhere else, likely `normalize.css` or similar

**Comment by jelbourn** [comment]
How topical!

See http://hidden.is.a.lie.fyi

(and the [Angular issue](https://github.com/angular/angular/issues/1417) I wrote up a couple years ago on the topic)

**Comment by xtianus79** [comment]
lol @jelbourn that is what I am requesting... the !important tag on hidden? this wouldn't be a better solution?

**Comment by jelbourn** [comment]
`[hidden]` is a browser feature, not something related to `@angular/material`

**Comment by xtianus79** [comment]
@jelbourn lol sorry got it
