### ISSUE TITLE
Problem with dialog and angular material

### ISSUE THREAD

**Issue by renatosistemasvc** [angular/material2#4824]
Hello! I'm having problem with dialog of primeNG and md-select to angular material.

Selecting the "select" the options are appearing below the dialog.

I believe it's a problem of z-index. How can i change the z-index md-select of md-option ?

image of erro

[IMG](http://www.farmatecnica.com.br/erroDialog.png)

**Comment by willshowell** [comment]
If it's a z-index problem, it sounds like this _maybe_ could be solved by https://github.com/angular/material2/issues/4485 which has a merge-ready PR (https://github.com/angular/material2/pull/4629).

That said, I don't think Material is necessarily designed to be compatible with additional frameworks like primeng

**Comment by renatosistemasvc** [comment]
Thank you for your response.

I would like to use the material dialog, but I find it very bureaucratic the way he works, @willshowell 

For the material dialog to work I need to create a component to be charged inside the dialog. The dialog of primeNg I create the dialog and I put simple html and it already works. So I wanted to use the primeNG dialog.

**Comment by fxck** [comment]
You can do that as well, you can pass it a template ref, so

```html
<ng-template #simpleContent>
  Some simple html
</ng-template>

```

```typescript

@ViewChild('simpleContent') content;

open() {
  this._dialog.open(content);
}

```

**Comment by fxck** [comment]
Would be even easier with https://github.com/angular/material2/pull/2855

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
