### ISSUE TITLE
keyup.enter on an input/datepicker triggers a click event on a subsequent button

### ISSUE THREAD

**Issue by radoslavpetranov** [angular/material2#4838]
#### Bug, feature request, or proposal:
I'm not sure if this is an Angular bug or a Material2 issue but the problem is that when I associate a `keyup.enter` event with a datepicker and then hit enter I end up triggering the `click` event on the subsequent button.

#### What is the expected behavior?
I expect to only trigger the `keyup.enter` event.

#### What is the current behavior?
I triggere the `click` event on the button.

#### What are the steps to reproduce?

Just click on the date picker field and hit enter and see how the click event on the button gets triggered.

http://plnkr.co/edit/BPp0oPXBM8OI8hrSXjzv?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I'm trying to have the datepicker appear when user hits enter.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.0.6
node: 6.10.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.6
@angular/compiler-cli: 4.1.3

**Comment by julianobrasil** [comment]
Don't think it's a problem with the component. It's the only button inside the form. It's the default behavior of the form component when you put a button inside it and do not specify the type="button" (it assumes the missing attribute is type="submit"). 

If you don't want to trigger the submit, just put type="button" in your button (then you must trigger submit by yourself programmatically):

`<button type="button" md-mini-fab class="error" (click)="clickTest()">A</button>`

See more information here, in this [stackoverflow post](https://stackoverflow.com/a/40103456/6433166).

**Comment by radoslavpetranov** [comment]
Thanks for the input @julianobrasil . That did indeed fix my issue. That behavior is a little illogical to me because submitting the form is one thing and triggering the additionally added button-click event on form submit is a different thing in my head but it is what it is.
