### ISSUE TITLE
mdTextareaAutosize doesn't resize textarea to a single row when mdAutosizeMinRows is set to 1

### ISSUE THREAD

**Issue by ruslan-simonenko** [angular/material2#4852]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Textarea should be resized to a single line.

#### What is the current behavior?
Resize doesn't shrink textarea to a single line, stops at minimum of two lines.

#### What are the steps to reproduce?
http://plnkr.co/edit/0HyRxBSQI7wksb7QFLDE?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.1.3
Material: v2.0.0-beta.6
OS: tested on Mac OS X 10.11.6
Browsers: tested on both Chrome 58 and Firefox 54

**Comment by DevVersion** [comment]
By default every textarea has the `rows` attribute set to `2`.

This means that this is actually not an issue but maybe this should be just mentioned in the docs.

Also possible would be setting the default amount of rows to `1`.

@mmalerba What do you think?

**Comment by ruslan-simonenko** [comment]
@DevVersion Just FYI in angular/material v1 there was a similar bug, and it's description said that default `rows` must be `1` according to the spec: https://github.com/angular/material/issues/2154 . Not sure whether it is still actual though - I was not able to find such information in the spec.

**Comment by DevVersion** [comment]
@ruslan-simonenko Thanks for linking this issue. I was not able to find it either but I just think it still makes sense to switch to `1` row by default because otherwise the `mdAutosizeMinRows` attribute does not work properly.

**Comment by mmalerba** [comment]
I think the default of `2` is just to match the native textarea's default. @jelbourn actually wrote the autosize, do you have an opinion on this Jeremy/

**Comment by DevVersion** [comment]
@mmalerba Yeah I agree that it would be easier to follow the design of the native textarea.

I just think if it is specified (still not sure where explicitly) then it's something we need to think about more.

**Comment by jelbourn** [comment]
Interesting- the spec designates "multi-line text field" and "text area" as two completely different things. On web, they're both `<textarea>` under the hood.

Either way, I agree that it should default to one row, otherwise you don't really have a way to do that.

**Comment by rodaz** [comment]
I stiil have this bug in Firefox 54 with Material 2.0.0-beta.8.
