### ISSUE TITLE
Select not set to ngModel initial value

### ISSUE THREAD

**Issue by doorman02** [angular/material2#4854]
#### Bug, feature request, or proposal:
When setting the ngModel variable in code behind onInit  the  selected display value is not showing.
This works in beta 5 but not anymore in beta 6

#### What is the expected behavior?
The select should show the display string of the ngModel value

#### What is the current behavior?
It does not show anything

#### What are the steps to reproduce?
```
<md-select [(ngModel)]="selectedSortBy " mdTooltip="Sort by">
              <md-option [value]="0">Latest</md-option>
              <md-option [value]="1">Highest</md-option>
              <md-option [value]="2">Lowest</md-option>
            </md-select>
```
and in component file onInit setting 
selectedSortBy= 0;
does not display Latest

#### What is the use-case or motivation for changing an existing behavior?
Select should show the databound value

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta.6 latest angular

**Comment by julianobrasil** [comment]
That's weird, because if you set selectedSortBy='0' (string) it works in one of two ways:

`<md-option value="0">Latest</md-option>` 

or

`<md-option [value]="'0'">Latest</md-option>`

But both of them fail with numbers.

**Comment by willshowell** [comment]
Looks like the offending line is here:

```
// _selectValue()

optionsArray.find(option => option.value && option.value === value);
```

A value of `0` is falsey for `options.value`

**Comment by vohtaski** [comment]
Any idea when it will be merged?

**Comment by robindijkhof** [comment]
Not sure if it will be usefull, but here is a pluker: https://plnkr.co/edit/UURJWRfiglafS8KkOjRt?p=preview
