### ISSUE TITLE
md-select multiple with check box window not closing in AngularJS v1.3.16

### ISSUE THREAD

**Issue by subhashekkaluru** [angular/material2#4857]
Dear all, here am using angular meterial design md-select multiple but this multi select window not closing when i was using the AngularJS v1.3.16 and it will work properly if i use  AngularJS v1.5.11.
so i need solve this issue what was wrong going on...thanks

**Comment by donroyco** [comment]
Hi @subhashekkaluru , you're reporting an issue that has to do with https://github.com/angular/material, please report it there. Material2 needs at least Angular version 2.

**Comment by subhashekkaluru** [comment]
thank u
