### ISSUE TITLE
ngModel not updated inside the selectedChanged event

### ISSUE THREAD

**Issue by gtzinos** [angular/material2#4858]
Hello,

i use this code to generate a datepicker.

     <md-input-container class="filter" >
            <input  [(ngModel)]="dateperiod" mdInput [mdDatepicker]="period" [max]="maxPeriod">
            <button mdSuffix [mdDatepickerToggle]="period"></button>
     </md-input-container>
     <md-datepicker #period (selectedChanged)="filter($event)" ></md-datepicker>

but inside of my filter function the ngModel is not up to date. Always has the previous value.

**Comment by donroyco** [comment]
:bulb: Please use the issue template.

**Comment by julianobrasil** [comment]
@gtzinos, it seems the selectedChanged event is fired first, then propagating faster. Try using a setTimeout inside your filter function (it's just a 0ms is engough, since it is just a synchronism issue):

```
filter($event) {
  setTimeout(() => { // your code goes here }, 0);
} 
```

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
