### ISSUE TITLE
SnackBar does not close zone when dismissed

### ISSUE THREAD

**Issue by svi3c** [angular/material2#4859]
#### Bug:

SnackBar should close duration zone when dismissed, so protractor is not blocked.

#### What is the expected behavior?

When calling MdSnackBarRef.prototype.dismiss(), the timeout reference by [setTimeout](https://github.com/angular/material2/blob/master/src/lib/snack-bar/snack-bar.ts#L82) should be cleared to close the angular zone.

#### What is the current behavior?

The zone stays open for the duration of the timeout.

#### What are the steps to reproduce?

[Plunker (watch the zone state)](http://plnkr.co/edit/e3Kq5D4ftj2zko801iuN?p=preview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/material@2.0.0-beta.5

**Comment by jelbourn** [comment]
We should do `clearTimeout` for that duration timeout if the snackbar is manually dismissed before the duration completes.

**Comment by svi3c** [comment]
Good point, @jelbourn.

That complicates the timeout handling:
We would have to remember the `timeoutHandle`. Since the ref can be directly dismissed, we would have to create either a new subject which fires on `exitStart` or the ref has to know about that handle.
In the latter case we cannot pass the timeout through the constructor, since we start that timeout `afterOpened()`, so we have to introduce a public field.

Which way do you prefer?

**Comment by jelbourn** [comment]
I would just move the setTimeout call into the snackbar ref in a function like `dismissAfter(timeout)`, then you can keep track of the timeout id in the ref and clear it when necessary.
