### ISSUE TITLE
Support md-button styling for links

### ISSUE THREAD

**Issue by demurgos** [angular/material2#486]
* **Do you want to request a *feature* or report a *bug*?**

This is a **feature request**.

* **What is the current behavior?**

Currently, `md-button` only uses selectors for buttons (`button[.md-button]`) but the CSS is less restrictive and accepts any element with the attribute `md-button` (it does not restrict the tag name).
When adding a link `<a md-button href="...">...</a>`, the style for `md-button` and `md-raised-button` is applied and look mostly good. The issue is that if a component only uses `a[md-button]` and no `button[md-button]`, then the style is not injected.

* **What is the expected behavior?**

It would be great to add the `a[md-button]` (and related `md-raised-button`, `md-icon-button`, etc.) so it is possible to style links as buttons when there no `<button>` in a component.

* **What is the motivation / use case for changing the behavior?**

This would allow use the `<a>` semantics with the style of material buttons for navigation buttons.

* **Other information**
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

[Here](https://github.com/angular/material2/blob/master/src/components/button/button.ts#L19) are the related lines. (I think that its just about adding selectors)

**Comment by kara** [comment]
It sounds like you're not importing MdAnchor and including it in your directives array. Can you check?

**Comment by demurgos** [comment]
I was reading [the doc from npm](https://www.npmjs.com/package/@angular2-material/button) and it did not mention MdAnchor. (Now that I scrolled a bit in the source file, I found that it is already defined)

Thank you for you quick answer.

**Comment by kara** [comment]
Yeah, sorry about that. We added docs for it recently on master, but it hasn't made it to an npm release yet. Should be in our next alpha.
