### ISSUE TITLE
mat-slide-toggle ignores emitEvent option

### ISSUE THREAD

**Issue by etatuev** [angular/material2#4861]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
**MdSlider** should not emit a new value to `valueChanges` if  `emitEvent?` option of `formGroup.patchValue` is set to `false`.

#### What is the current behavior?
`formGroup.PatchValue` emitting new values to `valueChanges` observable regardless of `emiEvent?` option in case if form has **mdSlider** control.

#### What are the steps to reproduce?
https://plnkr.co/edit/nuDl2fxg9phB15ySZJgH?p=info
There are 2 almost same forms with **mdSlider** and **mdCheckbox**, checkbox has correct behavior, and value didn't emitted, while programmatic toggling of **mdSlider** did.
 
#### What is the use-case or motivation for changing an existing behavior?
Obviously, it's a bug. Should be no emitting of event if it explicitly disabled.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Reproduces with Material beta.6, Angular 4.1.3, Typescript 2.3.3

#### Is there anything else we should know?
Nope.

**Comment by mmalerba** [comment]
@DevVersion assigning to you since it appears this issue was incorrectly labeled slider when it was actually about the slide-toggle. feel free to close if its obsolete

**Comment by DevVersion** [comment]
I'm not able to reproduce that issue anymore. https://stackblitz.com/edit/repo-4861?file=app/slide-toggle-overview-example.ts
