### ISSUE TITLE
autocomplete on textarea

### ISSUE THREAD

**Issue by fxck** [angular/material2#4866]
usecase is this 
![image](https://cloud.githubusercontent.com/assets/1303561/26558344/302978a8-44a8-11e7-8486-4dbfa1100122.png)

it should be as easy as extending the selector.. I think?

But it's gotta be said that it would be cool if you could open it at the caret position, as it works on github.

![image](https://cloud.githubusercontent.com/assets/1303561/26558399/a7241b98-44a8-11e7-8792-323713da1d1c.png)

@kara @crisbeto

**Comment by Zefling** [comment]
It's like this project : https://github.com/dmacfarlane/angular2-mentions

**Comment by fxck** [comment]
I'm working on porting https://github.com/angular-ui/ui-mention to angular2 as a temporary solution to https://github.com/angular/material2/issues/4444

**Comment by jelbourn** [comment]
Yeah, adding it to the caret position would be cool, probably would need a different `PositionStrategy` for that. For now I don't see why it can't be on `textarea` as well if you want to send a PR

**Comment by jelbourn** [comment]
Fixed in #4945

**Comment by jordangotbaum** [comment]
Does anyone have any examples of how they've implemented this? Do you just detect keystrokes on the textarea and then trigger the autocomplete when it's the proper character and set the origin element to the cursor or something? Would be very much appreciated.
