### ISSUE TITLE
mdDatepicker minInclude and maxInclude

### ISSUE THREAD

**Issue by ranouf** [angular/material2#4869]
Hi,

Is there a way to allow to select the same day for From and To:

                <div layout="row">
                    <md-input-container>
                        <input mdInput 
                               [max]="offer.to"
                               #fromElement
                               #fromControl="ngModel"
                               [mdDatepicker]="pickerFrom" 
                               placeholder="From"
                               [(ngModel)]="offer.from"
                               name="from">
                        <button mdSuffix [mdDatepickerToggle]="pickerFrom"></button>
                        <md-hint align="start">
                            <span [hidden]="fromElement.pristine || !fromElement.errors?.mdDatepickerMin" class="tc-red-600">Date not valid</span>
                        </md-hint>
                    </md-input-container>
                    <md-datepicker #pickerFrom></md-datepicker>            
                    <md-error *ngIf="fromControl.hasError('mdDatepickerMin')">Too early!</md-error>
                    <md-error *ngIf="fromControl.hasError('mdDatepickerMax')">Too late!</md-error>  
                </div>

                <div layout="row">
                    <md-input-container>
                        <input mdInput
                               [min]="offer.from"
                               #toElement
                               #toControl="ngModel"
                               [mdDatepicker]="pickerTo"
                               placeholder="To"
                               [(ngModel)]="offer.to"
                               name="to">
                        <button mdSuffix [mdDatepickerToggle]="pickerTo"></button>
                        <md-hint align="start">
                            <span [hidden]="pickerTo.pristine || !pickerTo.errors?.mdDatepickerMax" class="tc-red-600">Date not valid</span>
                        </md-hint>
                    </md-input-container>
                    <md-datepicker #pickerTo></md-datepicker>              
                    <md-error *ngIf="toControl.hasError('mdDatepickerMin')">Too early!</md-error>
                    <md-error *ngIf="toControl.hasError('mdDatepickerMax')">Too late!</md-error>  
                </div>

**Comment by ranouf** [comment]
I saw it was fixed in Angular material 2 (https://github.com/angular/material2/pull/4649).

But in the version 1.0.0-beta.4 it seems not fixed.

Problem, I can t upgrade currently my other packages are not compatible with the latest version.

How can I fix the problem?

**Comment by ranouf** [comment]
I thought to use "mdDatepickerFilter" the problem is in the fonction, the context is not the Angular component but the context of the MdDatePicker.

**Comment by jymdman** [comment]
Add `.bind(this)` if you wish to bind to the component instead, e.g.:
`[mdDatepickerFilter]="myFilter.bind(this)"`

**Comment by ranouf** [comment]
Thats perfect! 
Thank you!
