### ISSUE TITLE
[MdTab]: Content of non active tab is not ready when ngAfterViewInit() called

### ISSUE THREAD

**Issue by PinkTiu** [angular/material2#4872]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`MdTap`s are used with two or more taps. 
When `ngAfterViewInit()` of the component which hosts the taps is called the content of the taps should be ready. I wish to access them with `document.getElementById()`. 

#### What is the current behavior?
Only the content of the first tap is accessible with `document.getElementById()`. The content of the second tap is `null`. 

#### What are the steps to reproduce?
Plunker template: https://plnkr.co/edit/ojwqE3YGGUnf1p4ibxfs?p=preview

This is the HTML template: 
```
<md-tab-group>
  <md-tab label="Tab 1">
      <div id="content1">Conent 1</div>
  </md-tab>
  <md-tab label="Tab 2">
    <div id="content2">Conent 2</div>
  </md-tab>
</md-tab-group>
```

This is the `component`
```
export class TabsOverviewExample {
  ngAfterViewInit() {
    let content1 = document.getElementById('content1');
    let content2 = document.getElementById('content2');

    console.log(content1); // Correct
    console.log(content2); // null, but should have a value
  }
}
```

#### What is the use-case or motivation for changing an existing behavior?
When `ngAfterViewInit()` is called the content should be ready according to the methods name.
I use a plugin which accesses a element by id. So I get an error here.

**Comment by jelbourn** [comment]
This is working as intended. Only the active tab is rendered.

**Comment by diminutivesloop** [comment]
So I ran into a similar issue and while it makes sense that only the active tab is rendered it definitely seems broken that the inactive tabs still have their lifecycle hooks called. Basically I would expect `md-tab` to behave similarly to `NgIf`.

**Comment by lwensveen** [comment]
If anyone is looking for a workaround for this:

`<mat-tab-group color="primary" (selectedTabChange)="onLinkClick($event)">
  ...
</mat-tab-group>`

```
import { MatTabChangeEvent } from '@angular/material';

onLinkClick(event: MatTabChangeEvent) {
  console.log('event => ', event);
  console.log('index => ', event.index);
  console.log('tab => ', event.tab);

        if (event.index <= 0) {
            // do stuff here like 
            const ctx1 = document.getElementById('test') as HTMLCanvasElement;
        }
}
```
