### ISSUE TITLE
md-datepicker: format date

### ISSUE THREAD

**Issue by drweb86-work** [angular/material2#4876]
Hello

Is there a possibility to specify format of the date shown in text. e.g. DD-MM-YYYY. API says something about inheriting classes.

Thanks.

**Comment by fxck** [comment]
read this discussion https://github.com/angular/material2/issues/4832

**Comment by drweb86-work** [comment]
Thanks.
This solution works fine

`import { DateAdapter } from '@angular/material';`
`export class Test {`
`    constructor(private dateAdapter: DateAdapter<Date>) {`
`        this.dateAdapter.setLocale('nl');`
`    }`
`}`
`

**Comment by vapits** [comment]
Hey @drweb86-work 
can you share more?
I'm having the same with you implementation though as you see the date appears correctly on inptut field:
![image](https://user-images.githubusercontent.com/8594758/29260837-9d04ad02-80cc-11e7-97e7-cff902902b11.png)
But when I open the date picker it doesn't/ only if I input manually the US format the datepicker shows the correct date in calendar:
![image](https://user-images.githubusercontent.com/8594758/29260855-b8cf1072-80cc-11e7-8fee-8c33dbe8bca2.png)

**Comment by surajkhanal** [comment]
I need to make date format like : yyyy-mm-dd , how can i achieve this?
