### ISSUE TITLE
routerlink delay in md-nav-list (wraped anchor element in <md-list-item>)

### ISSUE THREAD

**Issue by pas2al** [angular/material2#4881]
#### Bug, feature request, or proposal:
I created a `md-nav-list` based on the angular material docs for a more complex navigation list and added a routerlink to the anchor tag.
https://material.angular.io/components/component/list

> For more complex navigation lists (e.g. with more than one target per item), wrap the anchor element in an <md-list-item>.

#### What is the expected behavior?
The routerlink should be resolved immediately when hover over or click the element.

#### What is the current behavior?
When you hover over the element or click on it, it is not getting resolved. Only after a short period of time (2 seconds or so) or after clicking multiple times on the element.

#### What are the steps to reproduce?
Here is a plunker, but it does not work with a routerlink. Nevertheless, the code is in place: 
The first list in the template works fine, but in the second list (where the anchor tag is wrapped into a md-list-item, the delay happens)
http://plnkr.co/edit/mPAVdd125AAohyKC2mWf

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I use beta 6

**Comment by jelbourn** [comment]
We do this exact thing on our guides page: https://material.angular.io/guides
https://github.com/angular/material.angular.io/blob/master/src/app/pages/guide-list/guide-list.html

Not seeing any delay there; likely something within your app.

**Comment by pas2al** [comment]
Ok, thanks for having a look on it.
