### ISSUE TITLE
add new feature Collapsible

### ISSUE THREAD

**Issue by George35mk** [angular/material2#4884]
![default](https://cloud.githubusercontent.com/assets/20750445/26601174/9221f122-4587-11e7-8895-42a8b0193bf7.PNG)
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by donroyco** [comment]
Already mentioned in #995

**Comment by jelbourn** [comment]
See #995

**Comment by George35mk** [comment]
@jelbourn thnx for starting to working in collapsible,
