### ISSUE TITLE
tab:proposal add close icon on the Top right corner

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#4890]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
add close icon on the Top right corner of tab, click the icon can close the tab;
like this https://www.primefaces.org/primeng/#/tabview Closable
#### What is the current behavior?
have no close icon

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
https://material.angular.io/components/component/tabs

#### What is the use-case or motivation for changing an existing behavior?
close one tab

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.1.3
material 2.0.0-beat.6
os: win10
typescript:2.3.1
browser:58.0.3029.110 (64-bit)

**Comment by jelbourn** [comment]
We'd consider this something that would live in user-space.
