### ISSUE TITLE
consider exporting $mat-toolbar-height scss vars

### ISSUE THREAD

**Issue by amitport** [angular/material2#4903]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
`$mat-toolbar-height-desktop` and `$mat-toolbar-height-mobile-portrait` should be available from `@angular/material/_theming`

#### What is the use-case or motivation for changing an existing behavior?
Writing scss rule that depend on the toolbar height. For example:

```scss
.sub-toolbar-full-view {
  height: calc(100vh - #{$mat-toolbar-height-desktop});

  @media ($mat-xsmall) {
    height: calc(100vh - #{$mat-toolbar-height-mobile-portrait});
  }
}
```

**Comment by jelbourn** [comment]
Right now we don't plan an officially making any of the individual component scss variables part of the public API. We may revisit this in the future.
