### ISSUE TITLE
md-select: md-option for [value]="false" not displayed

### ISSUE THREAD

**Issue by AxxlForce** [angular/material2#4904]
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

md-option for [value]="false" should be displayed when ngModel of md-select is false and not undefined

#### What is the current behavior?

md-option is not shown

#### What are the steps to reproduce?

http://plnkr.co/edit/cyqZ32ozoxXX5seXQ7G5?p=preview

**Comment by julianobrasil** [comment]
There's a similar issue: #4854.

**Comment by crisbeto** [comment]
Closing as a duplicate of #4854.
