### ISSUE TITLE
Are chips going to gain full functionality like tab to complete and x to close?

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#4913]
#### Bug, feature request, or proposal:
Request?

#### What is the expected behavior?
They are mostly just css

#### What is the current behavior?
css functionality

**Comment by willshowell** [comment]
See https://github.com/angular/material2/pull/2476 and the continuation #4912

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
