### ISSUE TITLE
I followed your installation guide, but can not run material in my app. Help!

### ISSUE THREAD

**Issue by antonpegov** [angular/material2#4916]
Here is source: 
https://github.com/antonpegov/angular-fl/tree/91fd9a2a5b6f0223500a321652c702847fdd352c

Actual version running on ghpages: 
https://antonpegov.github.io/angular-fl/

**Comment by ryanpm40** [comment]
@antonpegov Try importing 'MaterialModule', instead of 'MdButtonModule, MdCheckboxModule', in your app.module.ts.

**Comment by willshowell** [comment]
@ryanpm40 It's actually [recommended](https://material.angular.io/guide/getting-started#step-3-import-the-component-modules) to import individual modules.

@antonpegov You should be importing `MdButtonModule` and `MdCheckboxModule ` into your `CharacterModule` and every subsequent module that uses material components.

**Comment by antonpegov** [comment]
I've already tryed all that. No way. I think something wrong with npm dependences.

**Comment by eltimmo** [comment]
@antonpegov did you fix the Can't bind to 'value' since it isn't a known property of 'md-option' ? I've got exactly the same problem
