### ISSUE TITLE
Duplicate tooltip properties generated in API docs

### ISSUE THREAD

**Issue by xuanshenbo** [angular/material2#4923]
https://material.angular.io/components/component/tooltip

There are duplicated properties in this doc

![duplicates](https://cloud.githubusercontent.com/assets/7393393/26709482/1d31f566-47a7-11e7-843e-1a259f046ba9.PNG)

**Comment by julianobrasil** [comment]
In fact it hapens at least in one more other component doc (input). Seems it's some kind of automatic doc generation with duplicates entries in the database.

**Comment by jelbourn** [comment]
Probably a bug in the [categorizer](https://github.com/angular/material2/blob/master/tools/dgeni/processors/categorizer.js).

**Comment by DevVersion** [comment]
Looks like due to the recent changes in the `dgeni-packages` repository `getters` and `setters` are counting twice and therefore they are showing up twice in the docs.

We can filter duplicate properties for now.

cc. @petebacondarwin
