### ISSUE TITLE
NPM Dependency version issues. (gridlist/core/sidenav)

### ISSUE THREAD

**Issue by Destreyf** [angular/material2#493]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Incorrect package reference in NPM, the install command installs core@2.0.0-alpha.4 but installs grid-list@2.0.0-alpha.4.3

core@2.0.0-alpha.4 does not have errors/error, this causes a promise resolution error.

installing sidenav via npm install @angular2-material/sidenav installs sidenav@2.0.0-alpha.4 (not 4.3)

I haven't tested with any other modules yet, but i'm guessing more will be effected.

* **If the current behavior is a bug,
On a clean install of Angular 2 created by the CLI type the following
npm install --save @angular2-material/core @angular2-material/grid-list @angular2-material/sidenav

* **What is the expected behavior?**
It should install either the grid-list@2.0.0-alpha.4 to match core, or install core@2.0.0-alpha.4.3 to match grid-list.

**Comment by Destreyf** [comment]
I just noticed that grid-list is a newer module that uses 4-3, where as most the other ones have a 4-3 and a 4, so this was due to me trying to use a newer module.

**Comment by kara** [comment]
Thanks for reporting!  This is due to me accidentally releasing grid-list before it was ready.  Closing, as this should resolved by our next release.
