### ISSUE TITLE
Quickly closing a select panel leaves placeholder floating

### ISSUE THREAD

**Issue by willshowell** [angular/material2#4932]
#### Bug, feature request, or proposal:
Bug

#### Current Behavior
![select-bug](https://cloud.githubusercontent.com/assets/6475576/26726590/a5c73f8e-4771-11e7-9412-31405ec36a62.gif)

#### Reproduction

https://plnkr.co/edit/PdkalTdHd4vXzNrzSzpI?p=preview

**Comment by crisbeto** [comment]
This seems like an issue with `@angular/animations`. The placeholder still fires all the events as if it animated down, while not actually animating.

**Comment by crisbeto** [comment]
I couldn't reproduce it against Angular 4.3.6. Is it still an issue?

**Comment by willshowell** [comment]
Yeah I can't reproduce with https://plnkr.co/edit/TJxbBnoOvPfV8Ro4Uifu?p=preview.
