### ISSUE TITLE
Tooltip doesn't display inside input-container

### ISSUE THREAD

**Issue by dhuallanca** [angular/material2#4936]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
should display tooltip

#### What is the current behavior?

Tooltip doesn't display on mouse over
#### What are the steps to reproduce?

https://plnkr.co/edit/NFyqhLB7hcFg5S87oFLe?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Expected end-user behaviour to show tooltip for input

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 "@angular/core": "^4.1.2",
    "@angular/animations": "^4.1.2",
    "@angular/common": "^4.1.2",
    "@angular/compiler": "^4.1.2",
    "@angular/forms": "^4.1.2",
    "@angular/language-service": "^4.1.2",
    "@angular/material": ""2.0.0-beta.3",
"@angular/flex-layout": "2.0.0-beta.8",
    "@angular/platform-browser": "^4.1.2",
    "@angular/platform-browser-dynamic": "^4.1.2",
Google chrome 58.0.3029.110

**Comment by willshowell** [comment]
The input placeholder has `pointer-events: none` preventing hover from triggering the tooltip. Read more here https://github.com/angular/material2/issues/4167.

If you don't care about native input capabilities as mentioned in #4167, you can use a workaround kinda like this in your css

```css
.mat-input-placeholder, .mat-input-placeholder-wrapper {
  pointer-events: auto !important;
}
```

**Comment by jelbourn** [comment]
This is working as intended. The floating placeholder for the input should not have any interactions applied to it.

**Comment by dhuallanca** [comment]
css workaround works well for IE, Chrome, but it doesn't work for safari on iphone.
