### ISSUE TITLE
[Bug]: md-card-lg-image doesn't apply css class

### ISSUE THREAD

**Issue by kyleledbetter** [angular/material2#4938]
#### Bug, feature request, or proposal:
Bug, there's no brackets around:
```
host: {
    'class.mat-card-lg-image': 'true'
  }
```
so it doesn't apply the class="mat-card-lg-image"
https://github.com/angular/material2/blob/a2000246f51c8779443715b887b001468b89480c/src/lib/card/card.ts#L100

#### What is the expected behavior?
Expected `<img md-card-lg-image` to apply `<img class="mat-card-lg-image"`

#### What is the current behavior?
Applies `<md class.mat-card-lg-image="true"` instead

#### What are the steps to reproduce?
use the code:
```
      <md-card>
        <md-card-title-group>
          <md-card-title>Card with title group</md-card-title>
          <md-card-subtitle>including large image</md-card-subtitle>
          <img md-card-lg-image src="https://placekitten.com/g/600/200">
        </md-card-title-group>
      </md-card>
```

#### Is there anything else we should know?
fix would be to change to

```
```
host: {
    '[class.mat-card-lg-image]': 'true'
  }
```
```

**Comment by jelbourn** [comment]
Should be fixed now
