### ISSUE TITLE
MdTextareaAutosize: textarea control not sized correctly when number of lines is an odd number

### ISSUE THREAD

**Issue by SimplerSoftware** [angular/material2#4948]
#### Bug, feature request, or proposal:
Bug:  When using the MdTextareaAutosize with a textarea and the number of lines that the text occupies is an odd number, the control size is slightly too small and scroll bars appear.

#### What is the expected behavior?
The control should be resized such that scroll bars never appear.

#### What is the current behavior?
Described above in the bug.

#### What are the steps to reproduce?
See plunker [here](http://plnkr.co/edit/fBa8kLedcDGoNvnDTOsr?p=preview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.1.0
Material: 2.0.0-beta.6
TypeScript: 2.3.2

**Comment by julianobrasil** [comment]
It seems ok:

![image](https://cloud.githubusercontent.com/assets/25405143/26755418/416be0c4-4863-11e7-95ec-543c0279500d.png)

**Comment by SimplerSoftware** [comment]
Interesting... this is what I see:

![image](https://cloud.githubusercontent.com/assets/11198735/26755961/53ea758e-4855-11e7-81c9-98bfd0bb2914.png)

I'm using Chrome Version 58.0.3029.110 (64-bit):

![image](https://cloud.githubusercontent.com/assets/11198735/26755968/73078e5c-4855-11e7-85c4-c42846723302.png)

**Comment by julianobrasil** [comment]
Tried resizing the browser window to see if it behaves different, but nothing. The vertical scroll bar isn't shown here. 

By the way, I'm using the same chrome version, with different language:

![image](https://cloud.githubusercontent.com/assets/25405143/26756361/413b6868-4877-11e7-8b96-8f96e1046cc1.png)

**Comment by SimplerSoftware** [comment]
I used icognito mode in Chrome and turned off all extensions with the same result.  Also just tried IE 11 and it looks like it might be working?  It looks like there's scroll buttons but they're disabled and I think this might just be the default behavior of IE.  However, it doesn't show the little icon in the bottom right corner that allows you to drag and resize the textarea: 

![image](https://cloud.githubusercontent.com/assets/11198735/26761720/4a2cb5dc-48f2-11e7-96af-4082bd1894eb.png)

Edge doesn't show the scroll bars but it also doesn't show the resize icon.  It also appears to resize with extra space at the bottom when there is more than 2 rows of text:

![image](https://cloud.githubusercontent.com/assets/11198735/26761749/d8d1a806-48f2-11e7-891e-9ea32b5c83ae.png)

Here's my OS info as well:

![image](https://cloud.githubusercontent.com/assets/11198735/26761794/864e3d14-48f3-11e7-8aa6-e6ad8de7819e.png)

**Comment by julianobrasil** [comment]
Except for the chrome vertical scroll bar, the other browsers here show the same behavior seen in your images.

I also use Window 10 with 1920 x 1080 resolution screen.

**Comment by SimplerSoftware** [comment]
FYI - a good workaround or possible solution is just to set the style to: 'overflow:hidden' of the textarea.  Any chance we can get this merged into the source without me submitting a PR?
