### ISSUE TITLE
Input and select misaligned

### ISSUE THREAD

**Issue by henriqueweiand** [angular/material2#4949]
#### Bug, feature request, or proposal:

Bug

![sem titulo](https://cloud.githubusercontent.com/assets/6539492/26753776/569cd7e2-4844-11e7-93b9-9568bae72566.png)

#### What is the expected behavior?

Alignment according to another field

#### What is the current behavior?

Misaligned

#### What are the steps to reproduce?

https://embed.plnkr.co/cqdmVrghMOpUOYESWySg/

#### Is there anything else we should know?

I'm building a layout according to the project [https://github.com/EladBezalel/material2-start](https://github.com/EladBezalel/material2-start)
This uses:

`: Host {
   Display: flex;
   Flex: 1;
}`

In your css, so when I started to use in my project I noticed a disagreement at the height of the fields as picture and plunker. I'm not sure if this is an expected behavior, or if the behavior of the select field should not be interfered with.

**Comment by crisbeto** [comment]
https://github.com/angular/material2/pull/4788 got merged in yesterday and addresses this issue.

**Comment by henriqueweiand** [comment]
@crisbeto 

Test with the most recent version that you commented that could have corrected and seems to me to remain the same ... see:

[http://embed.plnkr.co/o077B6uEiiIgkC0S06dd/](http://embed.plnkr.co/o077B6uEiiIgkC0S06dd/)

![print](https://cloud.githubusercontent.com/assets/6539492/26764412/d302db4e-493c-11e7-8f5e-512954850a78.png)

**Comment by crisbeto** [comment]
Seems like that Plunkr is empty. Can you post it again?

**Comment by henriqueweiand** [comment]
@crisbeto , Sorry, continue again

[http://embed.plnkr.co/DXq5ZNNyhtBeSrjayiC3/](http://embed.plnkr.co/DXq5ZNNyhtBeSrjayiC3/)

**Comment by crisbeto** [comment]
You can get them to (mostly) align if you add `align-items: baseline` to the container. It seems like our baseline is still ~1px off though @mmalerba.

**Comment by mmalerba** [comment]
I just re-did the `md-input-container` to make all the spacing match the spec. We need to do a similar treatment for the `md-select`. Actually ideally we should refactor it so that the same CSS styles can be shared by the two components.

**Comment by penrique** [comment]
This is still happening to me
version: @angular/material@2.0.0-beta.8

**Comment by mmalerba** [comment]
see #2124
