### ISSUE TITLE
npm error: "Repository not found"

### ISSUE THREAD

**Issue by jonkri** [angular/material2#495]
I can't npm install @angular2-material/core. It looks like the Git repository might have moved, and that the npm packages need to be updated.

    $ npm install --save @angular2-material/core
    npm WARN package.json my.app@0.0.0 No description
    npm WARN package.json my.app@0.0.0 No repository field.
    npm WARN package.json my.app@0.0.0 No README data
    npm ERR! git clone git@github.com:angular2-material/core Cloning into bare repository '/home/jonkri/.npm/_git-remotes/git-github-com-angular2-material-core-bf428d36'...
    npm ERR! git clone git@github.com:angular2-material/core ERROR: Repository not found.
    npm ERR! git clone git@github.com:angular2-material/core fatal: Could not read from remote repository.
    npm ERR! git clone git@github.com:angular2-material/core 
    npm ERR! git clone git@github.com:angular2-material/core Please make sure you have the correct access rights
    npm ERR! git clone git@github.com:angular2-material/core and the repository exists.
    npm ERR! addLocal Could not install angular2-material/core
    npm ERR! Error: ENOENT, stat 'angular2-material/core'
    npm ERR! If you need help, you may report this log at:
    npm ERR!     <http://github.com/isaacs/npm/issues>
    npm ERR! or email it to:
    npm ERR!     <npm-@googlegroups.com>

**Comment by hansl** [comment]
Seems like you're using an old version of NPM that doesn't support organizations. Could you paste here the output of `npm --version`?

**Comment by jelbourn** [comment]
Many people have had this issue before, and it's always some issue with the environment. It's either an outdated `node` or `npm` version, or an issue with Windows cmd or powershell trying to treat the `@` as a special character.

**Comment by jonkri** [comment]
Ah, OK, thanks! I'm using the default npm in Fedora 23, which is 1.3.6. I guess I should simply install a newer version. Thanks!
