### ISSUE TITLE
Documentation is not in sync with latest build

### ISSUE THREAD

**Issue by zanderle** [angular/material2#4961]
#### Bug, feature request, or proposal:
Feature request or proposal

#### What is the expected behavior?
I'd expect documentation to either explicitly state that it's showing whatever is on master (and not the latest build). Or even better, show what's on the latest build instead.

#### What is the current behavior?
Currently, the documentation is on master.

#### What are the steps to reproduce?
I was working with `md-select` and was trying to use `panelClass` which is already in the documentation, but the latest build (`2.0.0-beta.6`) doesn't have it implemented yet.
![image](https://cloud.githubusercontent.com/assets/5232693/26763345/bd874b96-4951-11e7-8f3d-a4bfc2979ff3.png)

#### What is the use-case or motivation for changing an existing behavior?
It can be quite confusing figuring out why the feature that is documented, doesn't work on the latest build.

**Comment by jelbourn** [comment]
Ah, that was a mistake on my part. I pushed the docs to fix the datepicker API being missing, but forgot to check for APIs that should have been omitted. This will all be improved when we make our docs publishing more automated.

**Comment by AndreyJS** [comment]
With mdDialogConfig the same problem

**Comment by lucasalmeida92** [comment]
So there is no panelClass property anymore ? How do I add a class to my dialog container?
Tks in advance ;]

**Comment by willshowell** [comment]
@lucasalmeida92 `panelClass` does exist in master, but has not been part of a release yet. It will be available in beta.7 which should be out [sometime soon](https://github.com/angular/material2/pull/5025#issuecomment-307154908)

**Comment by lucasalmeida92** [comment]
Ok so I'll look forward to that! ;] Thanks @willshowell !

**Comment by robert-king** [comment]
I updated to beta.8 and panelClass is still missing
