### ISSUE TITLE
Oficial website , Sidenav example page have problems look at http...

### ISSUE THREAD

**Issue by George35mk** [angular/material2#4963]
#### Bug, feature request, or proposal:

bug
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

https://material.angular.io/components/component/sidenav
![fffffffffffff](https://cloud.githubusercontent.com/assets/20750445/26765642/b0ee35f2-4988-11e7-95da-8ffc5af3f3f9.PNG)

**Comment by DevVersion** [comment]
Thanks for the issue. Should be fixed by https://github.com/angular/material2/commit/1d7b7520f5ce39a090f88eee0e4f054790395adb

**Comment by George35mk** [comment]
no problem I am glad to help

**Comment by felyperennan** [comment]
The difference a comma does.
Like butterflies and storms.
