### ISSUE TITLE
proposal:add galleria

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#4966]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
https://www.primefaces.org/primeng/#/galleria

#### What is the current behavior?
none

#### What are the steps to reproduce?
it's an awesome component for show  pictures list

#### What is the use-case or motivation for changing an existing behavior?
 show  pictures list

**Comment by jelbourn** [comment]
We have no plans to add a component like this.
