### ISSUE TITLE
[Tooltips] Cannot dismiss multiple times in IE

### ISSUE THREAD

**Issue by zealitude** [angular/material2#4967]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tooltip show and dismiss nornally

#### What is the current behavior?
Tooltip cannot dismiss when mouse move in and out > 2 times

#### What are the steps to reproduce?
mouse move in and out > 2 times to the icon button in IE

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://plnkr.co/edit/BJBy6KqVRXKe21rBC7JA?p=preview

environment
IE11

**Comment by jelbourn** [comment]
@andrewseguin can your reproduce this?

**Comment by djleonskennedy** [comment]
@zealitude Check for animations guide in official docs

You need to use `web-animations-js` in IE11

***Adding the polyfill***:
```
Install with npm install web-animations-js --save
```
Add to polyfills.ts: `require('web-animations-js/web-animations.min')`;
It also worked if I do `import 'web-animations-js/web-animations.min'`;

**Comment by andrewseguin** [comment]
Please let me know if you can reproduce this with `web-animations-js` installed
