### ISSUE TITLE
[md-slide-toggle] setting default value to true brings pristine: false

### ISSUE THREAD

**Issue by e-cloud** [angular/material2#4968]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
default value with `true` should not affect the pristine state

#### What is the current behavior?
pristine state is changed

#### What are the steps to reproduce?
http://plnkr.co/edit/cCqjrY62mF1WKBSFPWeH?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Current behavior is somehow disturbing form validation

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular-4.1.0, Material-2.0.0-beta-6, others are all

**Comment by e-cloud** [comment]
see #4220

**Comment by csvn** [comment]
http://plnkr.co/edit/ZENOfcELsWaaHwqRDqRR?p=preview

New releases of material broke plunker. This one shows the issue.

**Comment by DevVersion** [comment]
This should be fixed with https://github.com/angular/material2/commit/dfe10c3fd39949cf63ae84bd7312c92d8a3bda41
