### ISSUE TITLE
button-toggle alignment and material.angular.io issues

### ISSUE THREAD

**Issue by fxck** [angular/material2#4969]
1) combination of text and icon is not aligned well 

![image](https://cloud.githubusercontent.com/assets/1303561/26775165/e901cea4-49d3-11e7-8799-37268654e81a.png)

2) styles in overview on material.angular.io are broken, or not working
![image](https://cloud.githubusercontent.com/assets/1303561/26775187/05477ed8-49d4-11e7-8933-f536701d6906.png)

**Comment by julianobrasil** [comment]
The styles ara a little bit strange in sidenav too at [material.io](https://material.angular.io/components/component/sidenav). 

Also the sidenav is not working there too (already reported in #4944).

![image](https://cloud.githubusercontent.com/assets/25405143/26780971/8aba6e48-49c2-11e7-8369-bd835d9088e9.png)

**Comment by jelbourn** [comment]
@tinayuangao the icon alignment is a minor issue; the example styles are more important
