### ISSUE TITLE
We nead text helper for long texts like this example

### ISSUE THREAD

**Issue by atlabiz** [angular/material2#4972]
#### What is the expected behavior?

add 2 dodts in the end of long text

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

![sfsdfdsfds](https://cloud.githubusercontent.com/assets/26713354/26783547/768e22e0-4a01-11e7-8f36-3250359299d9.PNG)

**Comment by CDDelta** [comment]
You can do this via css with:
```
<selector> {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
Nothing specific to the material library. Also add this to your styles.css file if you want it to apply globally.
