### ISSUE TITLE
Redirect to specific tab on operation from current tab

### ISSUE THREAD

**Issue by vibingopal** [angular/material2#4973]
#### Bug, feature request, or proposal:
Hi Team,

I am trying to work on redirecting the user control to specific tab on operation but not able to implement it.

#### What is the expected behavior?
We have three tabs for user operation. When user performs an operation on tab1 and the service returns success, i need to redirect the user to tab 3.But right now i am unable to do it.

material: 2.0.0-beta.6,
Angular 4 

Any suggestions on this please ?

**Comment by dahaupt** [comment]
`@Input()
selectedIndex
` this directive of the `MdTabGroup` can help you.

https://material.angular.io/components/component/tabs

For that kind of questions you can use our gitter channel here: https://gitter.im/angular/material2
