### ISSUE TITLE
Bug: md-datepicker max and min result in validation error

### ISSUE THREAD

**Issue by skoblenick** [angular/material2#4977]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Selecting the max or min date would not result in an error in the form validators. If the max date should be excluded then the calendar should disable greater than or equal to the max date. If the max date is inclusive the input should be less than or equal to the selected date. 

Min date should also validator in a similar method to max date (as mentioned above in reverse).

#### What is the current behavior?
Selecting the max or min date results in an error in the form validators.

#### What are the steps to reproduce?

See the demo app in the provided repo to reproduce the issue:

1. Checkout the repo https://github.com/skoblenick/angular-material-issue
1.  Run:
     ```
     npm install -g @angular/cli@1.1.0
     npm install
     npm start -- --port=4300
     ```
1.  Open browser and browse to http://localhost:4300.
1.  By default the app will set the selected date to today. 
     - The form has an error in the validator for the max date because the max date is equal to the current date, but visually isn't defaulted to the error state on the input. The error messages are triggered and displayed as the input changes.
     - Clicking the input field will result in the date-picker being opened.
     - Selecting the previous date removes the error from the validator.
     - reselecting today (the max) results in the error validator being triggered.

 **Note** the above is true with the min date as well. Buttons have been added to the demo to set the picked date to max and min.

#### What is the use-case or motivation for changing an existing behavior?
Expected behavior is to allow the user to selected up to and including the min or max date.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.1.3
Angular Material 2.0.0-beta.6
TypeScript ~2.2.0

#### Is there anything else we should know?
The same issue occurs when using moment to set the `startOf('day')` or `endOf('day')`.

**Comment by neekers** [comment]
Yeah it needs to include TIME in the validation. :)

**Comment by skoblenick** [comment]
Can you provide an example? There is nothing in the documentation around this.

**Comment by julianobrasil** [comment]
Duplicate: #4918, will be fixed in the next release.

**Comment by mmalerba** [comment]
Closing as dupe

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
