### ISSUE TITLE
Datepicker not validating to a valid date

### ISSUE THREAD

**Issue by neekers** [angular/material2#4978]
#### Bug, feature request, or proposal:
When entering in any other valid besides a date doesn't produce an error

#### What is the expected behavior?
Should get a date format error triggered or the valid property of the control should be false

#### What is the current behavior?
Input field accepts anything. Number, string, date. No error is produced and the value of the control is null. Hard to distinguish between bad entry and no entry.

#### What are the steps to reproduce?
http://plnkr.co/edit/iOMoGgZdk4ljJNz8vpSM?p=preview
* Create a date picker with no min date requirements.
* Enter in a plain number "5000"
* Blur field
* No error is shown

#### What is the use-case or motivation for changing an existing behavior?
A date field should validate for a real date

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.0.0
Angular Material Design 2.0.0-beta.6
All browsers and OS.

#### Is there anything else we should know?
Looks like the input is reading the numbers as the year. lol.
![screenshot 2017-06-05 14 04 33](https://cloud.githubusercontent.com/assets/1022714/26803142/f6f0463e-49f7-11e7-8a4f-12abe6821829.png)

**Comment by mmalerba** [comment]
The `NativeDateAdapter` just attempts to parse whatever you input into a `Date`, If you want different parsing behavior you can create a custom `DateAdapter` (see docs). As for the issue of considering input that fails to parse as `null` this is in line with what `type=number` inputs do when given a value such as `'e'` that fails to parse to a number. If you're writing your own `DateAdapter` you can return whatever you want when it fails to parse, so you could just return some sentinel object representing "invalid date".

@kara do you have any opinions on what `NativeDateAdapter` should return when parsing fails? (e.g. `null` vs some "invalid date" sentinel). I can see how it would be useful, but is it better to be consistent with what native inputs do?

**Comment by angular2fan** [comment]
I ran into the same scenario. It is even letting me type letters. this feature would be really useful. thanks.

**Comment by mmalerba** [comment]
@angular2fan you can accomplish this by making the input `readonly` and setting up the click handler on the `md-input-container` to open the popup: http://plnkr.co/edit/KFIay3gQcMylwmJbFNpM?p=preview

**Comment by draiche** [comment]
@angular2fan Another option if you still want the users to be able to type, but to not allow them to type letters, is something like this in your date picker component:

```
(keypress)="keyDown($event)"



keyDown(event) {
       const allowedRegex = /[0-9\/]/g;

        if (!event.key.match(allowedRegex)) {
            event.preventDefault();
        }
    }
```

I'm not claiming it's the most elegant solution on the planet, but it gets the job done for my purposes until more built-in solutions are added.

**Comment by mmalerba** [comment]
talked with @kara and it sounds like we want to count bad input as a validation error, not just `null`, I'll create a PR for that

**Comment by jbojcic1** [comment]
@mmalerba how can we validate the date now? I don't see anything in the docs. I tried by copying your code from demo and using:

```
<input matInput
            #startDate="ngModel"
            [matDatepicker]="startDatepicker"
            name="startDate"
            placeholder="Start Date"
            [(ngModel)]="object.startDate">
        <mat-datepicker-toggle matSuffix [for]="startDatepicker"></mat-datepicker-toggle>
        <mat-datepicker #startDatepicker></mat-datepicker>
        <mat-error *ngIf="startDate.hasError('matDatepickerParse')">Start date is not a valid date.</mat-error>
      </mat-form-field>

```
but it's buggy when you start typing in all different things. Am I doing something wrong?

**Comment by sharathgg5** [comment]
### problem throwing "mdDatepickerParse" error

### steps to reproduce the bug:

1. input a valid date value and blur.
2. focus again, remove the date value from input field and blur( focusout from the input).
3. now focus again on the input field(where it is null now) and type "asdfsdf" or "!E!@#!@#", it doen't throw error where it should throw.

note: with focused and valid date value, try input invalid value throws "mdDatepickerParse" error.

### there is one more issue after throwing "mdDatepickerParse"
field will be marked "invalid" for null value even though field is not marked as "required"
