### ISSUE TITLE
virtual-repeat component

### ISSUE THREAD

**Issue by eqbalsajadi** [angular/material2#498]
Hello Dear material2 team,

md-virtual-repeat in material 1.x is a responsible component for large data sets

Do you have a plan to build a corresponding component in material 2?
Can I use Angular 2 virtual DOM capability as a solution instead of virtual repeat component?

**Comment by jelbourn** [comment]
This is on our roadmap, but it's not coming until after we finish the remaining core components. Closing this issue since it will be some time before we get to working on it.

**Comment by eqbalsajadi** [comment]
Thanks

**Comment by elineopsommer** [comment]
any updates on this?

**Comment by willshowell** [comment]
@elineopsommer probably still a long way out but tracking here https://github.com/angular/material2/issues/823
