### ISSUE TITLE
"MdInputDirective" has no "focus" method

### ISSUE THREAD

**Issue by fbsstar** [angular/material2#4980]
#### Bug, feature request, or proposal:

Might be a bug.

#### What is the expected behavior?

"MdInputDirective" could call focus

#### What is the current behavior?

Could not call "focus" after getting "MdInputDirective"

#### What are the steps to reproduce?

Template is 

`<md-input-container >
	  <input  mdInput  placeholder="Owner" #owner>
</md-input-container>`

TS is

ViewChild('owner') ownerInput : MdInputDirective; 

But I could not call ownerInput.focus() which is documented. 

Instead I need to call as this.ownerInput['nativeElement'].focus();

And I also try ContentChild('owner') ownerInput : MdInputDirective like md container does, but owner will be empty.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular is 4.1.2, material is 2.0.0-beta.6, Typescript is "~2.2.0"

**Comment by fxck** [comment]
Provider a plunker reproduction.

**Comment by fbsstar** [comment]
http://plnkr.co/edit/uAWJWQwbpVdMEp2Ge6Gl?open=app%2Fapp.component.ts&p=preview 

And I try the contentChild, not work either. But it the doc of input control, there is a method called focus exposed under MdInputDirective.

I do not know if it is by design or wrong usage?

**Comment by willshowell** [comment]
Try this
```ts
@ViewChild(MdInputDirective) ownerInput : MdInputDirective;  
```

**Comment by fxck** [comment]
or

```
@ViewChild('owner', { read: MdInputDirective }) ownerInput: MdInputDirective;  
```

**Comment by fbsstar** [comment]
thanks a lot.

But first one might be used only when there is only one MdInputDirective in the parent, right? 

@fxck  Could you explain me a little bit about the mechanism behind, and why my code does not work?

**Comment by fxck** [comment]
Have you read the documentation of ViewChild? https://angular.io/docs/ts/latest/api/core/index/ViewChild-decorator.html

**Comment by fbsstar** [comment]
yes, but not quite understand. I will search the web and figure out what they means.

Thanks all your guys.
