### ISSUE TITLE
Proposal(slide-toggle): design of ripple effect in Md-Slide should improve 

### ISSUE THREAD

**Issue by sneha1990** [angular/material2#4983]
#### Bug, feature request, or proposal:
In Md-Slide ripple effect is overlapping on label text that is displayed besides slider icon.

#### What is the expected behavior?
There should be space alignment between ripple effect of Md-slider & label text that displayed besides slider icon.

#### What is the current behavior?
Current behavior is overlapping shadow of ripple effect on label text.
![rippleeffectshadowoverlap](https://cloud.githubusercontent.com/assets/9496598/26826953/a32576dc-4ad8-11e7-83c2-13f992bfa017.png)
   

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by dharmeshpipariya** [comment]
@DevVersion , @jelbourn the same issue should be coming in checkbox and radio button too.

**Comment by DevVersion** [comment]
@dharmeshpipariya Not sure about this. Having a bigger spacing here doesn't look right to me.

Also as this is a focus indicator it shouldn't be a problem if it overlays on user interaction. As far as I remember, the AppCompat Switch from Android doesn't have a bigger spacing as well.

**Comment by DevVersion** [comment]
Closing this issue as it seems like there is no specification for this specifically.

Increasing the spacing here makes the slide-toggle and label look more weird than better.
