### ISSUE TITLE
side-nav example is not working in the site documentation

### ISSUE THREAD

**Issue by latchuk** [angular/material2#4984]
In the site documentation of side-nav https://material.angular.io/components/component/sidenav the exemplo is not working.
About 5 days ago the site was working, but not now. 
It's only the exemplo in the site documentation with a bug or was the component side-nav code changed?

**Comment by willshowell** [comment]
Dupe of https://github.com/angular/material2/issues/4944

**Comment by latchuk** [comment]
The documentation is not fixed yet.
