### ISSUE TITLE
Bug (mdDatepicker) Date editing problem

### ISSUE THREAD

**Issue by naoufelus** [angular/material2#4985]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When editing the date, the selected value is incorrect and this is due to the language of the browser used.

#### What is the current behavior?
![fireshot capture 397 - plunker - https___plnkr co_edit__p preview](https://cloud.githubusercontent.com/assets/5398659/26830254/207a11ba-4ac0-11e7-8120-2b1b6ee04c6c.jpg)

```
navigator.language
"fr"

```
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.1.3, Material 2.0.0-beta.6

#### Is there anything else we should know?
The bug is due to the language of the browser for the written in french the month becomes the day and the day becomes the month.

**Comment by willshowell** [comment]
Maybe this discussion will help https://github.com/angular/material2/issues/4985

**Comment by julianobrasil** [comment]
@willshowell , I think you'd like to reference this other one: #4832

**Comment by willshowell** [comment]
Oh lol thanks @julianobrasil

**Comment by julianobrasil** [comment]
@naoufelus , take a look at this plunker: Take a look at this plunker, it's working: https://plnkr.co/edit/FlgGpjqyDlypas0VZJzo?p=preview

Basically it's a CustomAdapter class extending the Native one. It's configured to Brazilian portuguese, but you can change the language to french. I think it will work for you (because the date format is simillar - dd/MM/yyyy).

**Comment by dan-lennox** [comment]
I owe you a beer @julianobrasil

**Comment by julianobrasil** [comment]
@dan-lennox , If you're setting the locale globaly look for a better place for doing it than the classes you're using the datepicker (it's a singleton and you have to do It just once in  the application. I changed the plunk to better show It (put the setLocale in the mais.ts).
