### ISSUE TITLE
ScrollTop is not working when tab is changed from left to right in MdTabGroup

### ISSUE THREAD

**Issue by ubarsaiyan** [angular/material2#4989]
Bug:
I wrote a code that saves the scroll position of the current tab body's div and when we return to that tab it sets the scroll position to the stored value. By logging in the console I find the values stored and retrieved to be correct. But:
When I select a tab that is to the right of the currently active tab, the scroll position can not be set. But the same code sets the scroll position of the div if I select a tab that is towards the left of the currently active tab.

Excerpts from the code:
tab.service.ts:

public scrollTab() {
    let el = document.getElementById('items-container');
    this.tabs[this.currentTab].scrollPosition = el.scrollTop;
    console.log(this.tabs[this.currentTab].scrollPosition + ' during Change');
  }

 public setScroll() {
      const el = document.getElementById('items-container');
      if (el.scrollTop !== undefined) {
        console.log(this.tabs[this.currentTab].scrollPosition + ' during Set');
        el.scrollTop = this.tabs[this.currentTab].scrollPosition;
      }
  }
public switchTab(index: number) {
    this.currentTab = index;
    this.location.go('/' + this.tabs[index].path);
    this.displayEditor.next(false);
  }

tabs.component.html:

<md-tab-group class="tabbar"
     (focusChange)="tabService.scrollTab()"
     (selectChange)="tabService.switchTab($event.index); tabService.setScroll()"
     [selectedIndex]="tabService.currentTab" #tabgroup>

**Comment by andrewseguin** [comment]
For any help using Material or Angular, please refer to our great community, such as Gitter or StackOverflow. If you find an issue with Material, please feel free to open an issue but please follow the issue template which help us reproduce and resolve with a fix.
