### ISSUE TITLE
Blurry dialog text in IE11

### ISSUE THREAD

**Issue by ffredsh** [angular/material2#4990]
#### Bug, feature request, or proposal:
Big

#### What is the expected behavior?
The text not to be blurry

#### What is the current behavior?
Text is blurry in IE11

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Run the following plunker in IE11 (modified dialog plunker):
https://plnkr.co/edit/OI6U7oefSYDja8NlgAau?p=preview

Here is a screenshot: http://imgur.com/a/3EAXz

#### What is the use-case or motivation for changing an existing behavior?
We have a decently large IE11 user base and this looks pretty bad

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, Material 2.0.0-beta.6, IE11, Windows 10

#### Is there anything else we should know?
Probably related to: https://github.com/angular/material2/issues/1953

**Comment by ffredsh** [comment]
Probably caused by this: https://github.com/angular/material2/pull/3905

**Comment by crisbeto** [comment]
This should be fixed by https://github.com/angular/material2/commit/c8b1e200eea78fe28ce911bd58fd61a634829c52, which got merged yesterday. You can try installing the latest build from master:

```
npm install https://github.com/angular/material2-builds.git
```

**Comment by ffredsh** [comment]
Hmm, still blurry for me, I have 6aaddbf release:
├─┬ @angular/material@2.0.0-beta.6-6aaddbf (git+https://github.com/angular/material2-builds.git#8ac8d0a4fd41f8cca     7bbd350986eed9b12c96f99)

**Comment by crisbeto** [comment]
The fix got merged right after https://github.com/angular/material2/commit/6aaddbf526634f4fe84cc3938c096c60510a380a.

**Comment by ffredsh** [comment]
Cool, confirmed fixed after:
npm install https://github.com/angular/material2-builds.git#4ae2a62
which has https://github.com/angular/material2/commit/c8b1e200eea78fe28ce911bd58fd61a634829c52
