### ISSUE TITLE
Sidenav is not working!!!!!!  Look at your site and the control example

### ISSUE THREAD

**Issue by davidmontgom** [angular/material2#4992]
Really?   Look at your site.  My site is now messed up.  Did you not unit test before you pushed to production? When will it be fixed.  Did you abandon the control?  if so remove and provide a message saying no longer supported.

**Comment by xuanshenbo** [comment]
Duplicate and should be fixed
#4963

That is not very friendly.

**Comment by jelbourn** [comment]
@davidmontgom Please be aware of [Angular's Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md).
