### ISSUE TITLE
dynamic right click context menu

### ISSUE THREAD

**Issue by yaronmil** [angular/material2#4995]
#### Bug, feature request, or proposal:
i think it is a  feature request since i couldnt find any documentation about it.

#### What is the expected behavior?
right clicking dom elment will trigger a dynamic menu.
this menu will be positioned on mouse position.

#### What is the current behavior?
current  behavior is md-menu that needs a pre defined triggering elment like a button.
and cant be triggered on right click

**Comment by jelbourn** [comment]
Tracking via #5007 since this request comes up from time to time.
