### ISSUE TITLE
Progressbar - Provide option to set max value of progress

### ISSUE THREAD

**Issue by harshithkashyap** [angular/material2#4997]
#### Bug, feature request, or proposal:
Feature Request/Enhancement

#### What is the expected behavior?
The progress bar component should allow the user to set a max value.

#### What is the current behavior?
The current progress bar takes a hard coded max value of 100 and proceeds from 0 - 100. When used with a timer with number of seconds as the value input, the progress completes at 100s.

#### What are the steps to reproduce?

http://plnkr.co/edit/CckJ1h?p=preview

#### What is the use-case or motivation for changing an existing behavior?
When the progress bar is used with a timer say 5 minutes (300 seconds), it should take 300 as the max value and progress till it hits 300.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by willshowell** [comment]
Why not `[value]="timer.timeCount / 3"`? That said, the docs do specify a whole number, and I don't know why:

>the progress is set via the value property, which can be a whole number between 0 and 100

**Comment by ciesielskico** [comment]
Just convert 300s to percentage

**Comment by harshithkashyap** [comment]
@willshowell @ciesielskico Thanks. Using % value will work. I was trying to avoid computing it every second. Closing this.

**Comment by sondreb** [comment]
Sorry for commenting on this closed issue, but I didn't want to create an additional request for a max property if this has already been decided upon.

What is the rational to not implement a max property on the component? While most developers handles percentage calculations, there are those who are not that proficient in maths, yet still are able to build fairly decent web apps.

The HTML5 <progress> element have "max" and "value", how come the mat-progress-bar have no plans to support max in a similar manner? It would simplify the binding for sure, most of the time we have "current" and "max" counts readily available, now I need to divide and multiply numbers for every single row when used in a table.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress

**Comment by willshowell** [comment]
In the past, this library has tried to match the native apis as much as possible. What do you think @jelbourn?

**Comment by jelbourn** [comment]
I don't have a strong reason not to add custom min/max if someone sends a PR.
