### ISSUE TITLE
Tooltip does not display on IE11 with NoopAnimationsModule

### ISSUE THREAD

**Issue by TomDemulierChevret** [angular/material2#4999]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
Tooltip should display on IE11 even when NoopAnimationsModule is used instead of BrowserAnimationModule.

#### What is the current behavior?
Tooltip isn't displayed on IE11 even when NoopAnimationsModule is used instead of BrowserAnimationsModule.

#### What are the steps to reproduce?

Replace BrowserAnimationsModule with NoopAnimationsModule in your NgModule and use a Tooltip on IE11.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/core: 4.1.3
@angular/material: 2.0.0-beta.6
typescript: 2.2.0

OS : Win7 64 bits
Browser: IE11 11.0.9600.18665

#### Is there anything else we should know?
Issue probably linked to : #4937

**Comment by crisbeto** [comment]
Can you test it out with the latest master build? My hunch is that #4937 might've fixed this. You can run this to get the latest build:

```
npm install https://github.com/angular/material2-builds.git
```

**Comment by TomDemulierChevret** [comment]
The current master build does indeed fix the issue for IE11.

**Comment by crisbeto** [comment]
Cool, thanks for checking. I'll close the issue as fixed in that case.

**Comment by TomDemulierChevret** [comment]
Np.
Do you have any ETA for the next version that will include the fix ?
