### ISSUE TITLE
md-checkbox always on right side

### ISSUE THREAD

**Issue by nadavten** [angular/material2#500]
md-checkbox always on the right side.

```
<md-list>
                <md-list-item *ngFor="let item of items | itemFilter:filter">
                    <md-checkbox align="start" [(ngModel)]="item.IsSelected"></md-checkbox>
                    <h3 md-line>{{item.Name}}</h3>
                </md-list-item>
            </md-list>
```

**Comment by jelbourn** [comment]
You can use the `align` property to control where the checkbox renders relative to its label. It's not clear from your issue if that's what you're referring to. Please follow our issue template.

**Comment by nadavten** [comment]
If you read my code you could see the 'align=start' attribute exists. Still
showing checkbox on the far right of the row.

**Comment by mpschaeuble** [comment]
@nadavten Have you been able to solve this issue? I currently have the same problem...
