### ISSUE TITLE
.cdk-overlay-container prevents scrolling of dialog with long content 

### ISSUE THREAD

**Issue by sashanana** [angular/material2#5002]
#### Bug, feature request, or proposal:
Not sure if it's a bug or just a misunderstanding of the use case

#### What is the expected behavior?
Content of dialog is scroll able or enable window scroll for long content.

#### What is the current behavior?
.cdk-overlay-container has pointer-events none that block scroll event and the .cdk-overlay-container remain in <body> after dialog closed.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Based on Basic dialog example

https://plnkr.co/edit/O9r1GdiNkq9MhTQSCQiy?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Most of the modern browsers

**Comment by ryanpm40** [comment]
@sashanana Try wrapping the content of the dialog in `<md-dialog-content></md-dialog-content>` tags :)

**Comment by jelbourn** [comment]
It sounds like you're looking for `md-dialog-content`
https://material.angular.io/components/component/dialog
