### ISSUE TITLE
panelClass Missing from MdDialogConfig

### ISSUE THREAD

**Issue by BHoma91** [angular/material2#5003]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To be able to add panelClass: "customModal" to the MdDialogConfig as specified in the Documentation.

![image](https://user-images.githubusercontent.com/17150399/26882857-945eaaec-4b69-11e7-823d-a58c1ba45a19.png)

#### What is the current behavior?
Given Error Message: Object literal may only specify known properties, and 'panelClass' does not exist in type 'MdDialogConfig'

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 "@angular/material": "^2.0.0-beta.3",
"@angular/animations": "^4.0.1"

#### Is there anything else we should know?
All other additional classes from the documentation is present in MdDialogConfig

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/4961. `panelClass` exists on master but the docs were accidentally published prematurely

**Comment by BHoma91** [comment]
Ah, didn't see that. Thanks
