### ISSUE TITLE
Safari and input element for autocomplete

### ISSUE THREAD

**Issue by axtho** [angular/material2#5008]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
input should use background color

#### What is the current behavior?
default input color is shown

#### What are the steps to reproduce?

http://plnkr.co/edit/pjWowX60V0nRqoKlGoS9

Will produce this:
<img width="1164" alt="bildschirmfoto 2017-06-07 um 19 58 33" src="https://user-images.githubusercontent.com/11181579/26893566-fb7c7946-4bbb-11e7-99f7-9e652123e968.png">

Here another: http://embed.plnkr.co/oQANuo/, same result

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
see #5004

**Comment by willshowell** [comment]
Specifically, it is the `type="search"` attribute on the input causing that. If you want a workaround, try this
```css
input[type="search"] {
  -webkit-appearance: none;
}
```

**Comment by axtho** [comment]
@willshowell you're right. It is that. Is there a specific reason why type should be set?

**Comment by mmalerba** [comment]
seems to work without extra CSS now: http://plnkr.co/edit/96o6s1XuSVWwWPOk5U6t?p=info
