### ISSUE TITLE
 md-tab: ng-template overrides md-tab label parent

### ISSUE THREAD

**Issue by dhuallanca** [angular/material2#5015]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
ng-template should not override label of md-tab parent

#### What is the current behavior?
ng-template inside md-tab overrides label of md-tab parent

#### What are the steps to reproduce?

https://plnkr.co/edit/WgWzE4eIDkmO4Ajfn4dI?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^4.1.2",
"@angular/animations": "^4.1.2",
"@angular/common": "^4.1.2",
"@angular/compiler": "^4.1.2",
"@angular/forms": "^4.1.2",
"@angular/language-service": "^4.1.2",
"@angular/material": ""2.0.0-beta.3",
"@angular/flex-layout": "2.0.0-beta.8",
"@angular/platform-browser": "^4.1.2",
"@angular/platform-browser-dynamic": "^4.1.2",
Google chrome 58.0.3029.110

#### Is there anything else we should know?
workaorund is replace label for ng-template in md-tab parent.

**Comment by jelbourn** [comment]
This is working as intended. You've added **md-tab-label** to the ng-template, telling the component that the content of the template should be used at the tab label.
