### ISSUE TITLE
Add ability to disable datepicker pop-up

### ISSUE THREAD

**Issue by dimabutenko** [angular/material2#5017]
#### Bug, feature request, or proposal:
Bug
I have a component with template like this:
```html
<md-input-container [formGroup]="formGroup">
   <input mdInput [mdDatepicker]="datepicker" [formControlName]="control.name" [readOnly]="control.isReadonly">
   <button *ngIf="!control.isReadonly" mdSuffix [mdDatepickerToggle]="datepicker"></button>
</md-input-container>
<md-datepicker *ngIf="!control.isReadonly" #datepicker></md-datepicker>
```

#### What is the expected behavior?

I want to not to render md-datepicker, so i added *ngIf="!control.isReadonly" to md-datepicker.

#### What is the current behavior?

When control.isReadonly is false, md-datepicker is not rendered
(I mean that there is no HTML for md-datepicker)

**Comment by jelbourn** [comment]
It's expected that this wouldn't work, since the component pulls the content of `<md-datepicker>` out of place and shows it in the floating panel. However, there should be a way to have this behavior.
