### ISSUE TITLE
accordion in forloop multi=false not work

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#5021]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
in forloop multi=flase can work well

#### What is the current behavior?
in forloop multi=flase not work

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
http://plnkr.co/edit/ulSNTMTMZmORzvkVTvch?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material@2.0.0-beta.6-536add3

**Comment by julianobrasil** [comment]
Also, when collapsed, at the second group of panels, when there's no margin/padding between collapsed neighbour panels, the shadow on the bottom border is shown.

**Comment by julianobrasil** [comment]
Change the *ngFor to the `<md-expansion-panel>` element: `<md-expansion-panel *ngFor="let navItem of navItems">`. It's current on the `<md-nav-list>` element, so they are independent expansions.

**Comment by stevenmi** [comment]
@julianobrasil thanks
