### ISSUE TITLE
Remove MaterialModule from getting-started guide

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#5027]
#### Bug, feature request, or proposal:

Update.

#### What is the expected behavior?

The [quickstart repo](https://github.com/EladBezalel/material2-start) mentioned in https://github.com/angular/material2/issues/4976#issuecomment-306915481 needs a minor update: the import of material module must be replaced by the individual imports of the used modules.

#### What is the current behavior?

It's importing MaterialModule

#### What are the steps to reproduce?

Just take a look at the [quickstart repo](https://github.com/EladBezalel/material2-start)

**Comment by julianobrasil** [comment]
@EladBezalel, here it is.

**Comment by EladBezalel** [comment]
@julianobrasil i expected this issue to be over there 😅 but that's fine, we'd do it

**Comment by julianobrasil** [comment]
oops! My mistake :bowtie:

@EladBezalel, it's not too late to close it here, I think. Would it be better if I move it to there?

**Comment by xuanshenbo** [comment]
Created [pull request](https://github.com/EladBezalel/material2-start/pull/16)

**Comment by DevVersion** [comment]
Just updated the issue reproduction Plunker to no longer use the `MaterialModule`.

As @julianobrasil pointed out, we also need to update the generated Plunker docs from the docs too.

**Comment by julianobrasil** [comment]
Just clone the repo, npm install and npm start:

![image](https://user-images.githubusercontent.com/25405143/27842206-42e39d3c-60de-11e7-817a-9151948a7855.png)

Well, got no warnings concerning angular-cli versions but my node version is 6.10.3:

```
@angular/cli: 1.2.0
node: 6.10.3
os: win32 x64
@angular/animations: 4.2.5
@angular/cdk: 2.0.0-beta.7-b00f838
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/material: 2.0.0-beta.7-b00f838
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5
```

**Comment by jelbourn** [comment]
Done!
