### ISSUE TITLE
MdDatepickerModule not exported.

### ISSUE THREAD

**Issue by themiloagency** [angular/material2#5033]
#### Bug, feature request, or proposal:
Can't seem to import the MdDatepickerModule. All of the other Material modules have worked fine for me, without errors. But any time I attempt to bring in the Date Picker I get errors.

#### What is the expected behavior?
Just working version of the basic example on material.angular.io for the date picker.

#### What is the current behavior?
On compile:
![screen shot 2017-06-08 at 2 36 00 pm](https://user-images.githubusercontent.com/16781563/26944866-eef52226-4c57-11e7-9ce6-f185d7630da3.png)

and in the chrome:
![screen shot 2017-06-08 at 2 36 08 pm](https://user-images.githubusercontent.com/16781563/26944891-002d1404-4c58-11e7-9535-19bf56c2c8f0.png)

#### What are the steps to reproduce?
Simply importing MdDatepickerModule into an NgModule. All other Material modules are working as expected.

`
import {MdSlideToggleModule, MdInputModule, MdSelectModule, MdDatepickerModule} from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
    SharedModule,
    FormsModule,
    MdSlideToggleModule,
    MdInputModule,
    MdSelectModule,
    MdDatepickerModule,
    ReactiveFormsModule,
    RouterModule.forChild(routes)
  ],
})
`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "4.1.0",
    "@angular/common": "4.1.0",
    "@angular/compiler": "4.1.0",
    "@angular/compiler-cli": "4.1.0",
    "@angular/core": "4.1.0",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "4.1.0",
    "@angular/http": "4.1.0",
    "@angular/material": "^2.0.0-beta.6",
    "@angular/platform-browser": "4.1.0",
    "@angular/platform-browser-dynamic": "4.1.0",
    "@angular/platform-server": "4.1.0",
    "@angular/router": "4.1.0",
    "typescript": "~2.3.1",
    "webpack": "2.4.1",

**Comment by xuanshenbo** [comment]
I don't have this problem. Did you do a `npm update`?

**Comment by themiloagency** [comment]
I did. I went as far as deleting the Material 2 package altogether and starting with a fresh copy, that is the error I get.

**Comment by willshowell** [comment]
@themiloagency For me, this is the the last line of `node_modules/@angular/material/@angular/material.js`

```
/**
 * Generated bundle index. Do not edit.
 */

export { Dir, RtlModule, ..., CdkTable, MdDatepickerModule, MdCalendar, ... };
```

Are you seeing the same thing? Since you're not using the cli, could it be a webpack config issue?

**Comment by themiloagency** [comment]
@willshowell, that is what I see as well. 

Didn't make sense to me because every other module has loaded fine. Went as far as bringing in everything individually to see if something else would give me errors, but it was just the DatepickerModule.

Very well could be Webpack, but I had just assumed the DatepickerModule would then work similar to the rest.

**Comment by hoppities** [comment]
@themiloagency did you figure this out. I'm running into the same problem.

**Comment by themiloagency** [comment]
@hoppities I have not.

**Comment by hoppities** [comment]
So we figured it out. We needed to update to the latest version of angular material and import the module.

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
