### ISSUE TITLE
Make all components OnPush

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#5035]
- [x] `MdAutocomplete`
- [x] `MdAnchor`
- [x] `MdButtonToggle`
- [x] `MdOptgroup`
- [x] `MdOption`
- [x] `MdPseudoCheckbox`
- [x] `MdDatepicker`
- [ ] `MdDialogContainer`
- [x] `MdExpansionPanelHeader`
- [x] `MdExpansionPanel`
- [x] `MdGridList`
- [x] `MdGridTile`
- [x] `MdGridTileText`
- [x] `MdInputContainer`
- [x] `MdList`
- [x] `MdListItem`
- [x] `MdMenu`
- [x] `MdMenuItem`
- [x] `MdSpinner`
- [x] `MdSelect`
- [x] `MdSlider`
- [x] `SimpleSnackBar`
- [x] `MdSnackBarContainer`
- [x] `MdTabBody`
- [x] `MdTabGroup`
- [x] `MdTabHeader`
- [x] `MdTab`
- [x] `MdTabNavBar`
- [x] `TooltipComponent`
- [x] `MdSidenavContainer`

We should make these change incrementally, tackling one high-level component at a time (e.g., "tabs"). This will make it easier to revert in case something goes wrong after the change (and also help prevent a rebasing nightmare). 

Couple of things worth noting:
* Most components _should_ be as simple as adding `OnPush` to the config. This is the case if the component just has simple inputs and outputs.
* Anything that implements `ControlValueAccessor` needs `markForCheck` in the forms hooks

**Comment by alexw10** [comment]
@jelbourn just curious for the reasoning for this?

**Comment by ciesielskico** [comment]
@alexw10  OnPush is a performance setting, so the component gets only rerendered by Angular when its inputs and/or outputs change

**Comment by jelbourn** [comment]
Yeah, it helps limit the cases where change detection runs on a component.

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/3005
https://github.com/angular/material2/issues/3106

related onpush issues

**Comment by z639** [comment]
and #5118

**Comment by e-cloud** [comment]
@jelbourn since there are so many component needed to be updated, your team should make the releases of Material2 more frequently, should'n you?

**Comment by crisbeto** [comment]
There are pending and/or merged PRs for all components now, but I'll keep this open until everything is merged and I've set up some linting enforce the `OnPush` change detection.

**Comment by crisbeto** [comment]
Closing since all components have been switched over now.
