### ISSUE TITLE
Prebuilt themes missing from material2-builds

### ISSUE THREAD

**Issue by byrondover** [angular/material2#5038]
`prebuilt-themes` top-level directory was deleted from the [angular/material2-builds](https://github.com/angular/material2-builds) earlier today. Prebuilt themes disappeared in [ed9091](https://github.com/angular/material2-builds/commit/ed90917823ad95b057486853a4fa4c7b87040995).

As a result, Angular apps installing the latest Material builds from Git and importing one or more of the prebuilt themes now fail to compile.

```@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';```

Results in...

```shell
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./src/styles.css
Module not found: Error: Can't resolve '@angular/material/prebuilt-themes/deeppurple-amber.css' in './src'
 @ ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./src/styles.css 4:10-204
 @ ./src/styles.css
 @ multi ./src/styles.css
webpack: Failed to compile
```

Was removing `prebuilt-themes` an intended change?

If so, is there an alternative recommended method of importing these prebuilt themes, or have they been deprecated entirely?

**Comment by DevVersion** [comment]
@byrondover Yeah the prebuilt themes should be still in the `material2-builds`. Thanks for the issue.
