### ISSUE TITLE
Tooltip does not display when host element disabled

### ISSUE THREAD

**Issue by eryi** [angular/material2#5040]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tooltip should display even when host element disabled

#### What is the current behavior?
Tooltip does not display when host element disabled

#### What are the steps to reproduce?
Plunker doesn't currently work due to missing prebuilt themes
Plunker template: http://plnkr.co/edit/usQUhZsPxOf9WGBQqcbn?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Tooltip used to explain why an element is disabled

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material: "2.0.0-beta.6"
@angular/core@4.1.3

Tested on Chrome

**Comment by willshowell** [comment]
The tooltip triggers on the `mouseenter` event and it looks like browser support for disabled elements is really low ([Firefox only](https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter#Browser_compatibility))... Strangely `mouseover` has better support.

Try with FF:
http://plnkr.co/edit/iwQuMw8ggQpqzCBrOGEh?p=preview

**Comment by jelbourn** [comment]
What @willshowell said. You can alternatively add the tooltip to a parent element.
