### ISSUE TITLE
Add new component label to relevant issuses

### ISSUE THREAD

**Issue by xuanshenbo** [angular/material2#5043]
As an Angular Material user, I want to see a list of all in-progress and planned new components, so that I don't submit duplicate new component requests.

Currently I'm aware of three places where we can see available, in-progress and planned components:

1. Doc site (available components only)
2. `README.MD`
3. Issues page with `new component` label

However, neither `README.MD` nor Issues page with `new component` label is a complete list of all in-progress and planned components. For example, `README.MD` does not have #2691, and neither #2691 nor #508 has a `new component` label.

I reckon the easiest way would be adding a `new component` to all new components that have an open issue already.

This may reduce the number of duplicate new component requests.

**Comment by jelbourn** [comment]
The README _should_ capture everything we plan on doing at a high level; if something is missing from the README, it's not a total lock-in for something we're definitely going to have.
