### ISSUE TITLE
Property afterAllClosed does not exist on type 'MdDialog'

### ISSUE THREAD

**Issue by Defmetalhead** [angular/material2#5047]
#### Bug, feature request, or proposal:
Cannot implement "afterAllClosed()" 
      ```
 dialog.afterAllClosed().subscribe(x => {
            console.log('all dialogs closed');
        });```

#### What is the expected behavior?
afterAllClosed should trigger an event when Md Dialog is closed. 

#### What is the current behavior?
Error: Property afterAllClosed does not exist on type 'MdDialog'


#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
import {MdDialog, MdDialogRef, MdDialogConfig, MD_DIALOG_DATA} from '@angular/material';

constructor(
        public dialog: MdDialog
    ) {
        dialog.afterAllClosed().subscribe(x => {
            console.log('all dialogs closed');
        });
    }

```

My packagae.json file 
```
{
  "name": "mybeehive",
  "version": "1.0.0",
  "author": {
    "name": "BeeHive.com, LLC",
    "email": "info@mybeehive.com",
    "url": "http://mybeehive.com"
  },
  "scripts": {
    "postinstall": "npm run build:webpack",
    "build:webpack": "npm run webpack-vendor && npm run webpack",
    "webpack": "webpack --progress",
    "webpack-vendor": "webpack --config webpack.config.vendor.js --progress"
  },
  "dependencies": {
    "@angular/animations": "^4.0.1",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.0.1",
    "@angular/compiler-cli": "^4.0.1",
    "@angular/core": "^4.1.3",
    "@angular/flex-layout": "^2.0.0-beta.1",
    "@angular/forms": "^4.0.1",
    "@angular/http": "^4.1.3",
    "@angular/material": "^2.0.0-beta.6",
    "@angular/platform-browser": "^4.0.1",
    "@angular/platform-browser-dynamic": "^4.0.1",
    "@angular/platform-server": "^4.0.1",
    "@angular/router": "^4.0.1",
    "@angular/tsc-wrapped": "^0.5.0",
    "@ngrx/core": "1.2.0",
    "@ngrx/effects": "2.0.2",
    "@ngrx/store": "2.2.1",
    "@types/google-maps": "^3.1.28",
    "@types/hammerjs": "2.0.34",
    "@types/node": "^6.0.42",
    "angular2-template-loader": "0.6.0",
    "aspnet-prerendering": "^2.0.0",
    "aspnet-webpack": "^1.0.17",
    "awesome-typescript-loader": "^3.0.0",
    "css": "^2.2.1",
    "css-loader": "^0.25.0",
    "es6-shim": "^0.35.1",
    "event-source-polyfill": "^0.0.7",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^2.0.0-rc",
    "file-loader": "^0.9.0",
    "hammerjs": "^2.0.8",
    "html-loader": "^0.4.4",
    "immutable": "3.8.1",
    "isomorphic-fetch": "^2.2.1",
    "json-loader": "^0.5.4",
    "md2": "0.0.13-1",
    "ng2-device-detector": "^0.1.0",
    "node-sass": "^3.13.0",
    "preboot": "^4.5.2",
    "raw-loader": "^0.5.1",
    "rxjs": "^5.0.1",
    "sass-loader": "^4.0.2",
    "source-map-loader": "0.1.5",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.5",
    "typed-immutable-record": "0.0.6",
    "typescript": "^2.2.1",
    "typings": "2.1.0",
    "url-loader": "^0.5.7",
    "webpack": "^2.2.0",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-merge": "^0.14.1",
    "zone.js": "^0.7.8"
  },
  "devDependencies": {
    "@types/chai": "^3.4.34",
    "@types/jasmine": "^2.5.37",
    "chai": "^3.5.0",
    "codelyzer": "^3.0.0-beta.4",
    "jasmine-core": "^2.5.2",
    "karma": "^1.3.0",
    "karma-chai": "^0.1.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-webpack": "^1.8.0",
    "tslint": "^4.5.1"
  }
}

```

**Comment by willshowell** [comment]
I think your problem is trying to call `afterAllClosed` as a method. It's just a property. 

https://plnkr.co/edit/nvkTNxGdVl817mSnhKLO?p=preview

**Comment by Defmetalhead** [comment]
Still the same issue. What is happening?! 

Here is my material package.json folder 
```
{
  "_args": [
    [
      "@angular/material@^2.0.0-beta.6",
      "C:\\Users\\David\\Source\\Repos\\BHApplications\\src\\BeeHive.TheBeeHive"
    ]
  ],
  "_from": "@angular/material@>=2.0.0-beta.6 <3.0.0-0",
  "_id": "@angular/material@2.0.0-beta.6",
  "_inCache": true,
  "_location": "/@angular/material",
  "_nodeVersion": "6.9.5",
  "_npmOperationalInternal": {
    "host": "s3://npm-registry-packages",
    "tmp": "tmp/material-2.0.0-beta.6.tgz_1495748017693_0.20498917065560818"
  },
  "_npmUser": {
    "email": "angular-core+npm@google.com",
    "name": "angular"
  },
  "_npmVersion": "3.10.10",
  "_phantomChildren": {},
  "_requested": {
    "name": "@angular/material",
    "raw": "@angular/material@^2.0.0-beta.6",
    "rawSpec": "^2.0.0-beta.6",
    "scope": "@angular",
    "spec": ">=2.0.0-beta.6 <3.0.0-0",
    "type": "range"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/@angular/material/-/material-2.0.0-beta.6.tgz",
  "_shasum": "83bfdf00f540a8c7db900a1e7b8ed2cff49df821",
  "_shrinkwrap": null,
  "_spec": "@angular/material@^2.0.0-beta.6",
  "_where": "C:\\Users\\David\\Source\\Repos\\BHApplications\\src\\BeeHive.TheBeeHive",
  "bugs": {
    "url": "https://github.com/angular/material2/issues"
  },
  "dependencies": {
    "tslib": "^1.7.1"
  },
  "description": "Angular Material",
  "devDependencies": {},
  "directories": {},
  "dist": {
    "shasum": "83bfdf00f540a8c7db900a1e7b8ed2cff49df821",
    "tarball": "https://registry.npmjs.org/@angular/material/-/material-2.0.0-beta.6.tgz"
  },
  "es2015": "./@angular/material.js",
  "homepage": "https://github.com/angular/material2#readme",
  "installable": true,
  "keywords": [
    "angular",
    "components",
    "material",
    "material design"
  ],
  "license": "MIT",
  "main": "./bundles/material.umd.js",
  "maintainers": [
    {
      "name": "angular",
      "email": "angular-core+npm@google.com"
    }
  ],
  "module": "./@angular/material.es5.js",
  "name": "@angular/material",
  "optionalDependencies": {},
  "peerDependencies": {
    "@angular/common": "^4.0.0",
    "@angular/core": "^4.0.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/angular/material2.git"
  },
  "scripts": {},
  "typings": "./material.d.ts",
  "version": "2.0.0-beta.6"
}


```

**Comment by Defmetalhead** [comment]
Here is my code now. "afterAllClosed" is still underlined in red and has the same message. 

Error: Property 'afterAllClosed' does not exist on type 'MdDialog'

```
constructor(
        private route: ActivatedRoute,
        public router: Router,
        private venueDetailService: VenueDetailService,
        private detailsService: DetailsService,
        private store: Store<AppState>,
        private http: Http,
        public dialog: MdDialog
    ) {
        dialog.afterAllClosed.subscribe(() => {
            console.log('all closed');
        });
    }
```

**Comment by willshowell** [comment]
Weird. Think you could publish a repo that minimally reproduces it?

**Comment by Defmetalhead** [comment]
This ended up being a weird IntelliSense error within Visual Studio.
