### ISSUE TITLE
Cannot Style .mat-sidenav-content

### ISSUE THREAD

**Issue by rgant** [angular/material2#5050]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Using angular-cli AOT my style rule is modified to include `.mat-sidenav-content[_ngcontent-c0]`, but the .mat-sidenav-content div doesn't have the `_ngcontent-c0` attribute.

#### What is the current behavior?
Style rules aren't applied to .mat-sidenav-content when complied using angular-cli. This is a change in the recent updated to angular AOT.

#### What are the steps to reproduce?

http://plnkr.co/edit/3zegTvjpaDZ5JqKSOFnt

In this plunker I am attempting to apply a style to the `.mat-sidenav-content` div, but because of the AOT compiling (I believe) my style rule doesn't apply.

#### What is the use-case or motivation for changing an existing behavior?
I want to be able to change the `.mat-sidenav-content` to `flex: 1` style.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.1
node: 8.0.0
os: darwin x64
@angular/animations: 4.2.0
@angular/common: 4.2.0
@angular/compiler: 4.2.0
@angular/core: 4.2.0
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.2.0
@angular/http: 4.2.0
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.0
@angular/platform-browser-dynamic: 4.2.0
@angular/router: 4.2.0
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.0
@angular/language-service: 4.2.0
```
#### Is there anything else we should know?
This was working until I upgraded things.

**Comment by rgant** [comment]
Not sure where this bug really is, so I also filed a bug report here: https://github.com/angular/angular/issues/17377

**Comment by willshowell** [comment]
This has nothing to do with AOT.

That `_ngcontent-c0` attribute you're seeing is due to [ViewEncapsulation](https://angular.io/docs/ts/latest/guide/component-styles.html#!#view-encapsulation) and it's getting applied to any DOM elements that belong to AppComponent. That's why you see it on `<md-sidenav>` and `<main>`.

The `<div class="mat-sidenav-content">` is a child element of `MdSidenavContainer`,  **not** your `AppComponent`. `MdSidenavContainer` has encapsulation turned off, so no `_ngcontent` attributes get applied to its own children.

Unless I'm missing something, this is not a bug with material or angular, but just the nature of how Angular works. If you're determined to apply styles to `.mat-sidenav-content` (why not just to `main`?), you have a few options:

1. Set your component's ViewEncapsulation to None
2. Move the css rule out of the component styles and into a global location
3. Use the `/deep/` selector in your css (though I think it's supposed to be deprecated soon and don't know what the suggested alternative is)

**Comment by willshowell** [comment]
For more context:

1. [`MdSidenavContainer`](https://github.com/angular/material2/blob/master/src/lib/sidenav/sidenav.ts#L315-L332)
2. [`sidenav-container.html`](https://github.com/angular/material2/blob/master/src/lib/sidenav/sidenav-container.html)
3. An [article on transclusion](https://toddmotto.com/transclusion-in-angular-2-with-ng-content)

**Comment by rgant** [comment]
I need to apply `flex: 1` to the `.mat-sidenav-content` so that it will layout correctly. If I try to apply that to `main` it is collapsed by the parent `.mat-sidenav-content` div. Happy to apply another solution, but I don't know why angular would add an attribute `[_ngcontent-c0]` to a CSS rule if it is not encapsulated.

**Comment by willshowell** [comment]
From the first link about ViewEncapsulation:

> `Emulated` view encapsulation **(the default)** emulates the behavior of shadow DOM by preprocessing (and renaming) the CSS code to effectively scope the CSS to the component's view. For details, see Appendix 1.

You should turn encapsulation off in your AppComponent if you wish to not have your AppComponent's css rules appended with `[_ngcontent-c0]`

**Comment by rgant** [comment]
Ok, I think you are missing the bug here, but this appears to be an issue with angular, not material2, so it's moot.

**Comment by willshowell** [comment]
Maybe. Are you expecting the `.mat-sidenav-content` to have the `_ngcontent-c0` attribute?

**Comment by willshowell** [comment]
Or are you expecting your styles to not be appended with the `[_ngcontent-c0]` selector?

**Comment by rgant** [comment]
I'm expecting that the style rule I write works through whatever modifications the build process makes.

The build process produces the dom: `<div cdk-scrollable class="mat-sidenav-content" ...>` without `_ngcontent-c0` attribute. And the build on the styles produces a modified rule where `.mat-sidenav-content` has the `[_ngcontent-c0]` attribute selector.

If the `mat-sidenav-container` component has `encapsulation: ViewEncapsulation.None` then I expect that the styles build will note that and not add `[_ngcontent-c0]` to style rules for this component. I don't know how it would know that, but it seems to me that if it cannot, then it shouldn't just change things that can introduce breakage.

So either material2 shouldn't turn off encapsulation, or angular should respect that setting with style rules. Since the encapsulation change was made 10 months ago in this repo, I assume that something changed in angular recently causing this to break.

**Comment by willshowell** [comment]
In your [plunker](http://plnkr.co/edit/3zegTvjpaDZ5JqKSOFnt?p=info), `<div cdk-scrollable class="mat-sidenav-content" ...>` does not belong to your `AppComponent`. [As you can see](https://github.com/angular/material2/blob/master/src/lib/sidenav/sidenav-container.html) that markup belongs exclusively to `MdSidenavContainer` and will respect whatever styles and encapsulation rules it provides.

What version before Angular 4.2 was exhibiting different behavior?

**Comment by rgant** [comment]
When I upgraded from angular-cli v1.0.4 to v1.1.1 my builds started failing.
