### ISSUE TITLE
MdInputContainer misaligned with different font sizes

### ISSUE THREAD

**Issue by arlowhite** [angular/material2#5056]
#### Bug

Recently, there were some md-input-container changes in master. The input and underline no longer line-up at different font sizes.

#### What is the expected behavior?

Should be able to change `font-size` of `md-input-container` and it should align with other text at same font-size.

#### What is the current behavior?

![mdinputcontainer_toolbar](https://user-images.githubusercontent.com/444413/26998463-d2e107b2-4d38-11e7-9507-8085197cbb1c.png)

#### What are the steps to reproduce?

`npm run demo-app`
Scroll down to the Hello First name example, which inherits md-toolbar font-size.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

material2 commit f89c6dbe905f0508810dda48fca55d4b41615764
screenshot is with Linux Chrome Version 59.0.3071.86 (Official Build) (64-bit)

**Comment by mmalerba** [comment]
That screenshot appears to be from the demo app, the reason for the misalignment there is not an issue with the input itself, just the fact that it's currently center-aligned in the the header rather than baseline-aligned. I'll submit a fix for the demo
