### ISSUE TITLE
MdSnackbar blocks actions from a page instead of pushing the contents up

### ISSUE THREAD

**Issue by Goodwine** [angular/material2#5057]
#### Bug, feature request, or proposal:
From the material guidelines, in mobile, the snackbar should push the contents up in order to not block actions on the page.

#### What is the expected behavior?
Contents should be "pushed up" like the Material guidelines video.
https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B6Okdz75tqQsZV9TS3lTVHFzRUE/components_snackbar_usage_fabdo_005.webm

#### What is the current behavior?
MdSnackbar is being rendered as an "overlay" on top of whatever including actions on the page.
https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B6Okdz75tqQsYkUtOWM5bmpYT2c/components_snackbar_usage_fabdont_005.webm

#### What are the steps to reproduce?

1. Visit https://run.plnkr.co/plunks/mbRlieU09iC48gsdz1uU/
2. Use dev tools to see the screen as if it was a Nexus 5X or Iphone 4
3. Click the button to show the snackbar at the bottom of the page.
4. Try to click the button again without dismissing the snackbar.

#### What is the use-case or motivation for changing an existing behavior?
We are showing a snackbar for first time visitors asking "what do you think of the site". This action is obviously not important for our users and therefore we shouldn't block the main actions in the UI, but with the current behavior, users are required to interact with the snackbar.

**Comment by donroyco** [comment]
You're interpreting this wrong:
> From the material guidelines, in mobile, the snackbar should push the contents up in order to not block actions on the page.

It should only push _actions_ (like a 'add' button) up, when they are in the area where the snackbar will be shown. See the [Material guidelines](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage) where this is being said:

> **Don’t block the floating action button**
Move your floating action button vertically to accommodate the snackbar height.

**Comment by willshowell** [comment]
It would be awesome if a FAB could be attached to a portal that provided "generic FAB positioning" where it would stick to the bottom right and be pushed aside by snackbars.

**Comment by CDDelta** [comment]
@willshowell good news! That is being tracked at #4252.

**Comment by Goodwine** [comment]
@donroyco I disagree, in the example I'm sharing there is a button that is being hidden by the snackbar which shouldn't be hidden because it is an action.
I would agree however if the material spec said something less ambiguous like "actions that float on the screen" or "actions that have a sticky position at the bottom of the screen".

**Comment by donroyco** [comment]
@Goodwine The snack-bar is intended as a _notification bar_ or _quick action bar_, not as a permanent overlay on top of your content, so in that way it is okay to be on top of your content for just a couple of seconds. 

> Snackbars provide brief feedback about an operation through a message at the bottom of the screen. They exit by being swiped off-screen or automatically disappear after a timeout or user interaction elsewhere (such as summoning a new surface or activity). 
[Source](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage)

I don't think the explanation above together with the setup of the snack-bar page can't get any clearer. Therefore, there's no need for an update on the specs, they're self explanatory.

**Comment by jelbourn** [comment]
The snackbar-pushes-FABs features is tracked by #4252.
