### ISSUE TITLE
Datepicker min attribute - dates before min dates are still available. Validation works

### ISSUE THREAD

**Issue by vmachacek** [angular/material2#5065]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I set 'min' on a datepicker I want to see disabled all dates before that

#### What is the current behavior?
The dates which are in past from min date are not disabled

#### What are the steps to reproduce?
Set the min date for datepicker, and previous dates are still available from UI, validation will still work.

#### What is the use-case or motivation for changing an existing behavior?
The min attribute is useless for UI, the validation still works

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using `https://github.com/angular/material2-builds.git` repo 

#### Is there anything else we should know?
I was flowing the #4725 and used the material2-builds repository, but another problem occurred. This issue.

**Comment by willshowell** [comment]
Plunker? Seems to be working fine here

https://plnkr.co/edit/QKBR2ftpbZALDfWC0Uuo?p=preview

**Comment by vmachacek** [comment]
Hello, I don't think you are using same repo for angular material https://github.com/angular/material2-builds.git

**Comment by willshowell** [comment]
Sorry, you're right I was using the latest beta release. 

[`min` is working](https://plnkr.co/edit/ZoFqflFk5SsJwlVLdEzW?p=preview) @ 1f93cdb
[`min` is broken](https://plnkr.co/edit/YGBZd7T8zkeODJkQZXDG?p=preview) @ 28d2ddd


Therefore it looks like the regression was introduced via https://github.com/angular/material2/pull/4370

cc @mmalerba

**Comment by willshowell** [comment]
@vmachacek there are several other datepicker bugs due to that PR. I posted them as a comment https://github.com/angular/material2/pull/4370#issuecomment-307849984 and reposting here:

1. Unable to start in year view
2. Start at date has no effect
3. "Prev month" button initially enabled when min date in current month
4. When setting min/max dates within current month, all days are enabled until month view is refreshed
5. Active date is not highlighted until month view is refreshed

**Comment by jelbourn** [comment]
@willshowell do you have a reproduction? When I try this in our dev environment it works fine. I also don't see how adding an extra change detection pass would cause any behavior change.

**Comment by willshowell** [comment]
@jelbourn Weird, I was running it locally too and still seeing this issue. Here's a plunker using the latest material2-build

http://plnkr.co/edit/0iqcOvTy2aZWmIDqyo5t?p=preview

**Comment by jelbourn** [comment]
I see the issue now. The initial round of change detection makes Angular think that the component doesn't need another when the `datepicker` property of `DatepickerContent` is changed.

**Comment by willshowell** [comment]
@jelbourn additionally, the entrance animation of the datepicker in touchUi mode stopped working due to that commit.

Working @ 1f93cdb: [Plunker](https://plnkr.co/edit/UQWoqyhkiO4YiCSATpmY?p=preview)
Broken @ 28d2ddd: [Plunker](https://plnkr.co/edit/1oQyVlGWT7Rnw6X6USOH?p=preview)

**Comment by babin1988** [comment]
Using the following simple code max date is working fine but I could not achieve the min date functionality:
Html Code:
<mat-form-field>
  <input matInput [matDatepicker]="picker" placeholder="Choose a date" [min]="startDate" [max]="endDate">
  <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
  <mat-datepicker #picker></mat-datepicker>
</mat-form-field>

Ts Code:
this.minDateValue = new Date(1900, 1, 1);
this.maxDateValue = new Date();

**Comment by saravanacs** [comment]
Using typescript and  Angular Material Datepicker is validation check date of birth in 18 years from current year. Please tell me anyone, how to develop this
