### ISSUE TITLE
Responsive Grid List

### ISSUE THREAD

**Issue by raminqaf** [angular/material2#5069]
#### Bug, feature request, or proposal:
Hi,
could you please make angular material 2 more responsive? The grid system needs different col sizes depending on your device size. The current cols just takes one attribute. You could have for example "cols-md", "cols-xs" and so on...
Thanks

**Comment by donroyco** [comment]
Dupe of #1072

**Comment by lax20attack** [comment]
You can do  it yourself on window resize.

**Comment by jelbourn** [comment]
Dupe of #1072

**Comment by rexebin** [comment]
Is the feature dropped in favour of angular/flex-layout please?
