### ISSUE TITLE
Inside a ngFor loop, MdCheckbox 'change' event is not emitted when 'checked' binding change.

### ISSUE THREAD

**Issue by tomsdev** [angular/material2#507]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MdCheckbox 'change' event is always emitted when 'checked' binding change.

#### What is the current behavior?
It works for a standalone MdCheckbox but not when MdCheckbox is inside a ngFor loop.

#### What are the steps to reproduce?
I created a small plunkr with standalone checkboxes and checkboxes inside ngFor loop:
http://plnkr.co/edit/v2Nv4QcMVPVwdX32z3hQ

Steps:
Open the devtools console to see console.log messages.
Check (e.g. click) the "Select all" checkbox.
All the checkboxes become selected.
In the devtools console you see:

> onSelectAllCheckboxChange
onCheckboxChange
onCheckboxChange

Instead of what you'd expect:

>  onSelectAllCheckboxChange
onCheckboxChange
onCheckboxChange
onNgForCheckboxChange
onNgForCheckboxChange

#### Which versions of Angular, Material, OS, browsers are affected?
Latest version (see the plunkr), tested on Goobuntu with Chrome.

#### Is there anything else we should know?
This bug could be an Angular 2 bug and not a MdCheckbox bug. Feel free to move it to Angular 2 issues if relevant.

**Comment by DevVersion** [comment]
This is not an issue. I investigated at your issue and noticed, that you're recreating the row object on each `select all` call.

This causes the components to be re-rendered, with new instances, which are by default set to `unchecked` (You can also see, that the animation is not working on un-checking)

If you only modify the given property of the row, it will work properly.

See my modified plunker.
- http://plnkr.co/edit/EdHoPxVOOz1AFS4mQ0KD?p=preview

This issue can be closed.

**Comment by tomsdev** [comment]
Thanks Paul, it makes sense, I wasn't aware the components were re-created every-time in this case.
