### ISSUE TITLE
BrowserAnimationsModule

### ISSUE THREAD

**Issue by rrmuduli** [angular/material2#5077]
npm install --save @angular/animation
ng2-material@0.0.0 ***\ng2-material
+-- @angular/animation@4.0.0-beta.8
+-- UNMET PEER DEPENDENCY @angular/common@2.4.10
`-- UNMET PEER DEPENDENCY @angular/core@2.4.10

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/animations@4.1.3 requires a peer of @angular/core@4.1.3 but none was installed.
npm WARN @angular/material@2.0.0-beta.6 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN @angular/material@2.0.0-beta.6 requires a peer of @angular/common@^4.0.0 but none was installed.
npm WARN @angular/animation@4.0.0-beta.8 requires a peer of @angular/core@4.0.0-beta.8 but none was installed.

app.module.ts 
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { BrowserAnimationsModule } from '**@angular/platform-browser/animations**';
                                                                     
import { MdButtonModule, MdCardModule, MdMenuModule, MdToolbarModule, MdIconModule } from '@angular/material';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

Hi,
I am trying to work on angular material but the "@angular/platform-browser/animations" is not installing or not found.
Please help me...
Thanks

**Comment by willshowell** [comment]
Looks like you aren't using Angular 4+ across the board. Try upgrading all your `@angular/*` packages to their latest version.

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
