### ISSUE TITLE
Icons aren't rendered in IE11 on Windows 10

### ISSUE THREAD

**Issue by patrikbjork** [angular/material2#5078]
#### Bug, feature request, or proposal:
When e.g. `<md-icon>home</md-icon>` is used the icon isn't rendered in Internet Explorer 11 (not edge mode) on Windows 10.

#### What is the expected behavior?
The icons should render.

#### What is the current behavior?
The icons aren't rendered.

#### What are the steps to reproduce?
Go to https://material.angular.io/components/component/icon in IE11 (not edge mode) on Windows 10. The home icon isn't rendered.

#### What is the use-case or motivation for changing an existing behavior?
Fix the bug.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Internet Explorer 11 (not edge mode) on Windows 10.

#### Is there anything else we should know?
The browser uses the following User-Agent header:
`"User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E)"`

Doing `curl  -H "User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E)" https://fonts.googleapis.com/icon?family=Material+Icons` returns css without the `font-feature-settings: 'liga'` rule. Requesting the same resource from other IE browsers seem to include dito. Manually adding that css rule makes the icons render.

**Comment by donroyco** [comment]
Are you seeing any errors in the console? Because if I run it in [Browserling](https://www.browserling.com/browse/win/10/ie/11/https%3A%2F%2Fmaterial.angular.io%2Fcomponents%2Fcomponent%2Ficon) for example, the icon shows up.

**Comment by julianobrasil** [comment]
It seems ok over here (I understood that the [_Edge Mode_ is disabled](https://msdn.microsoft.com/en-us/library/bg182625(v=vs.85).aspx) by taking away the `<!DOCTYPE html>` + using a meta tag with the attribute [http-equiv](https://msdn.microsoft.com/en-us/library/jj676915(v=vs.85).aspx) ). That's what I see:

Plunker: https://plnkr.co/edit/j1n6Ms?p=preview

![image](https://user-images.githubusercontent.com/25405143/27028802-58142cf2-4f3c-11e7-9850-ca63621297c2.png)

**Comment by julianobrasil** [comment]
Well... plunker is not a good place to test this kind of thing, because it encapsulates your code. But changing to windowed view I got an error and the page is not even loaded unless you take away the meta tag:

## With the meta tag:

![image](https://user-images.githubusercontent.com/25405143/27029584-5059e760-4f3f-11e7-9f88-627afe8cbd8d.png)

## Without the meta tag:
![image](https://user-images.githubusercontent.com/25405143/27029618-70647480-4f3f-11e7-83c0-8c0423ecd1bb.png)

**Comment by patrikbjork** [comment]
After some more digging I now know more. It's related to my organization's intranet settings. Normally IE11 passes `User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`, but due to intranet settings the browser passes `User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E)`. Our application works because of `<meta http-equiv="X-UA-Compatible" content="IE=edge">` tag but the User-Agent header is still not exactly like a normal IE11.

Obviously the returned CSS differs due to the User-Agent header. Wouldn't it be better if the returned CSS included the `font-feature-settings: 'liga'` as per default? That would solve our problem. Of course our intranet settings are stupid but that's nothing I can change.

**Comment by jelbourn** [comment]
@patrikbjork I don't follow what the issue is. We don't change our CSS based on the user agent string. Is your application rendering in quirks mode?

**Comment by patrikbjork** [comment]
Can you draw any other conclusion than that the returned CSS depends on the user agent string?

`curl -H "User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E)" https://fonts.googleapis.com/icon?family=Material+Icons`

```
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialicons/v22/2fcrYFNaTjcS6g4U3t-Y5SQZRqoBW5Q4K_a7BOZJO20.eot);
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
}
```

`curl -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko" https://fonts.googleapis.com/icon?family=Material+Icons`

```
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons'), local('MaterialIcons-Regular'), url(https://fonts.gstatic.com/s/materialicons/v22/2fcrYFNaTjcS6g4U3t-Y5ewrjPiaoEww8AihgqWRJAo.woff) format('woff');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  font-feature-settings: 'liga';
}
```

**Comment by jelbourn** [comment]
Oh, the Material Icons CSS- I thought you meant the Angular Material CSS. Yes, that service does serve different CSS based on the user agent. The Material Design icons are a separate project from Angular Material

**Comment by mcaden** [comment]
@patrikbjork This definitely appears to be an issue with pulling it from google fonts. I had the same issue and it resolved simply by pulling the `material-design-icons` from npm instead and rolling `node_modules/material-design-icons/iconfont/material-icons.css` into my build.

**Comment by PassionatePaul** [comment]
Thanks Patrik, I got this post 10 minutes after you posted it and use to solve the same issue..Cheers Paul

**Comment by StephenWTurner** [comment]
I found moving <meta http-equiv="X-UA-Compatible" content="IE=edge" /> to be the first tag in the <head> solved this problem. Source: https://stackoverflow.com/a/28490514/350188
