### ISSUE TITLE
MdSelect does not display selected value label when the value is numeric 0

### ISSUE THREAD

**Issue by martvaha** [angular/material2#5080]
#### Bug, feature request, or proposal:
MdSelect does not display selected value label when the value is numeric 0.

#### What is the expected behavior?
MdSelect should display value label when 0 is selected.

#### What is the current behavior?
Example in Plunker

#### What are the steps to reproduce?
In the first select (selected=0) the display label is left empty
https://plnkr.co/edit/4Kf8geDi3ESymYhTyUTK

**Comment by julianobrasil** [comment]
It will be fixed in next beta: https://github.com/angular/material2/commit/2e3910c86c1a1486222f639bb9404aaaf5661d9b

**Comment by martvaha** [comment]
Thanks! Missed that commit. Tested on master and it does fix the issue.
