### ISSUE TITLE
Rollup & Angular Material is broken since angular 4.2

### ISSUE THREAD

**Issue by Karasuni** [angular/material2#5081]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
When I try to build angular-material with angular >4.2 using rollup an import recursion is generated.

**Minimal reproduction of the problem with instructions**

1. Integrate angular-material alongside angular 4.2 ([example](https://github.com/Karasuni/angular-seed/tree/material))
2. `npm i` and `npm run build.prod.rollup.aot`

You will receive the error:
```
{ Error: A module cannot import itself
    at error (...\angular-seed\node_modules\rollup\src\utils\error.js:2:14)
    at Module.error$1 [as error] (...\angular-seed\node_modules\rollup\src\Module.js:303:2)
    at ...\angular-seed\node_modules\rollup\src\Bundle.js:399:15
  code: 'CANNOT_IMPORT_SELF',
  pos: 166,
  loc: 
   { file: '...\\angular-seed\\dist\\tmp\\node_modules\\@angular\\material\\typings\\index.ngfactory.js',
     line: 5,
     column: 0 },
  frame: '3: import * as i2 from \'@angular/common\';\n4: import * as i3 from \'@angular/platform-browser\';\n5: import * as i4 from \'./index.ngfactory\';\n   ^\n6: import * as i5 from \'@angular/forms\';\n7: import * as i6 from \'@angular/http\';' }
```

Compare with [this version](https://github.com/Karasuni/angular-seed/tree/material-4.1) and notice that there are no issues up to angular 4.1.

**More information:**
* https://github.com/mgechev/angular-seed/issues/1970
* https://github.com/angular/angular/issues/17389
* https://github.com/steveblue/angular2-rollup/issues/18

**Comment by SnareChops** [comment]
I second this issue but argue that it is actually a core issue within the angular AOT code generation algorithm. Just bumped into a .ngfactory.js file that was generated with a self-referential import.

```
import * as i5 from './toolbar.component.ngfactory';
...
export function View_ToolbarComponent_Host_0(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 1, 'toolbar', [], [[2, 'toolbar-shadow', null], [2, 'hidden', null]], null, null, i5.View_ToolbarComponent_0, i5.RenderType_ToolbarComponent)), i0.ɵdid(114688, null, 0, i4.ToolbarComponent, [i0.NgZone, i6.ToolbarModel], null, null)], function (_ck, _v) {
        _ck(_v, 1, 0);
    }, function (_ck, _v) {
        var currVal_0 = i0.ɵnov(_v, 1).model.shadow;
        var currVal_1 = i0.ɵnov(_v, 1).model.hidden;
        _ck(_v, 0, 0, currVal_0, currVal_1);
    });
}
```

We are not using angular material, but are using angular 4.2.2 with AOT compilation. The generated code appears to be referencing the function above the one I pasted in here, but it's referencing it through an external import of itself, rather than a local reference.

**Comment by jelbourn** [comment]
Not related to Angular Material, see https://github.com/angular/angular/issues/17389
