### ISSUE TITLE
Support for color input type 

### ISSUE THREAD

**Issue by tmatthews0020** [angular/material2#5086]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Able to use the color type on md-input and have the browsers native color input.

#### What is the current behavior?
Error: Input type "color" isn't supported by md-input-container.

#### What are the steps to reproduce?
  ```
<md-input-container>
      <input mdInput placeholder="Text Color" [(ngModel)]="color"  type="color">
</md-input-container>
```
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
to support opening and using the browsers native color input components

**Comment by jelbourn** [comment]
`md-input` is meant to really just be for _text_ inputs 

(we're considering renaming `md-input-container` to `md-text-field`)
