### ISSUE TITLE
Turn off view encapsulation for md-toolbar-row

### ISSUE THREAD

**Issue by yogeshgadge** [angular/material2#5087]
Same as [#676](https://github.com/angular/material2/issues/676) but for `md-toolbar-row`.

The first `md-toolbar-row` gets created by the `md-toolbar` and with default ViewEncapsulation.Emulated the `md-toolbar-row` can't be styled. However [#1718](https://github.com/angular/material2/issues/1718) only solves being able to add attributes. It does not solve styling issues.

For example how does one change the height for 64px to 50px on md-toolbar-row ?

**Comment by willshowell** [comment]
Here is one option

http://plnkr.co/edit/ph2RH89NMWQuJ0ifwCHE?p=preview

**Comment by jelbourn** [comment]
`@Directive`s don't have `ViewEncapsulation`

**Comment by yogeshgadge** [comment]
@willshowell Nice trick. Mine doe snot work and wondering if app.component must have inlined styles vs stylesUrl ?

**Comment by willshowell** [comment]
@yogeshgadge that won't make a difference. Just to be sure, you saw the global styles that I added in index.html?

To achieve your goal, you can do one of the following:

1. Use global styles like in the linked plunk
2. Turn off ViewEncapsulation of your app.component
3. Use the /deep/ selector in your app.component's styles
