### ISSUE TITLE
Input datalist improvemet (ComboBox as editable Select)

### ISSUE THREAD

**Issue by JesusSD** [angular/material2#509]
### Feature request:
**You can insert any value in Input tag and you have a Drop Down icon for introduce optional sugestions with values, labels and Icons as editable select.**

Examples:

**Input tag with Data List (Drop Down icon show optional values with lavels in Chrome)**
link: http://triancal.esy.es/?p=15&t=6.4951905284
[
![chrome label in datalist](https://cloud.githubusercontent.com/assets/12623174/15501981/59e18cbe-21b1-11e6-9f11-eba9758e2417.jpg)
**NGPrime Input Autocomplete (optional sugestions with Icons)**
link: http://www.primefaces.org/primeng/#/autocomplete
![primenginputautocomplete](https://cloud.githubusercontent.com/assets/12623174/15501984/62c2fcdc-21b1-11e6-81cd-4fcc7ed3e01e.JPG)

](url)
 
**Other sugestions:**
- Input adicional parameters:
 * X delete Icon shows when has any value (default true).
 * Undo icon (Default: false).
 * Go Boton (Default: false)
 * Select all text when focus default true.
 * Esc key: Back to initial value
 * Editable: As Input or Label/Select tag role. (Default: true)
Note: Icons don't alter tag width

- Validation improvements:
 * Realtime Auto Validation border colors while insert text.
 * Numbers and Text (<, <=, >, >=, !=)
 * Array of validators with Regular expressions and funtions().
 * Internacional: examples: "e equal é" or "n diferent ñ"

- DropDown adicicional options:
 * Selected Item background Color (Default: Automatic (good contrast)).
 * Max items (Default Max number of items in window)
 * Scrollbar (Default: Enabled with effects)
 * AutoOpen: open when focus. (Default: false)
 * Show: Enable dropdown icon only when has values (Default: true)
 * Automatic: display dropdown icon only when has focus: (default: true), (false=ever showed)
 * Sort values (Internacional: example "e or é" or "n ñ") (Default: false)
   Note: All values are ever shows bellow with a divider.
 * Multiple: Select some values with checkbox. (Defaut: false)
 * Search: with hilights sugestions while you type (begin, contain, seam...)(Default: false)
 * Exclusive: User only can insert DropDown list values default false
 * Insert component as values
 * Groups, disable, hidden and dividers.

Thanks.

**Comment by jelbourn** [comment]
Multiple selection is something that will be implemented as part of md-select (see #118).

**Comment by zyarnold** [comment]
> Get FREE access to all course content by signing up below.

Ok so the request for combo-box has been closed because there is already a planned implementation for md-select multiple? Wut?
