### ISSUE TITLE
<md-autocomplete> needs change or select event on options

### ISSUE THREAD

**Issue by dihar** [angular/material2#5096]
### I need a output event in `<option>` of `<md-autocomplete>` when we choose it.
I have a use case:
```html
<md-input-container>
  <input mdInput name="someSideInput" [(ngModel)]="someAnotherProperty">
</md-input-container>

<!--
options: {name: string; sideValue: string}[];
-->

<md-input-container>
  <input mdInput [(ngModel)]="autocompleteProperty" [mdAutocomplete]="autoComp" 
    name="autocompleteInput">
</md-input-container>
<md-autocomplete #autoComp="mdAutocomplete">
  <md-option *ngFor="let opt of options" 
    [value]="opt.name" 
    (click)="someAnotherProperty = opt.sideValue">
    {{ opt.name }}
  </md-option>
</md-autocomplete>
```
On choose autocomplete's option I need do some side effect with some local template variable (like `opt` in template). This template is working great. But on key interaction it doesn't work. `(keyup)` doesn't work. It's need to add output event on option `(choose)`,`(select)` or `(pick)` .

The final result I want:
```html
<md-autocomplete #autoComp="mdAutocomplete">
  <md-option *ngFor="let opt of options" 
    [value]="opt.name" 
    (select)="someAnotherProperty = opt.sideValue">
    {{ opt.name }}
  </md-option>
</md-autocomplete>
```

It must work for click and key interaction.
Thanks!

**Comment by julianobrasil** [comment]
This feature would be very wellcome with the "force selection" been tracked in here #3334.

In fact, the efect you wish can be done as soon as you garantee the  values of the input is one of the options  - if the user left the component without selecting one option the input would be cleared.

But it's a lot of code to do a simple thing. It could be present in the component.

**Comment by dihar** [comment]
@julianobrasil , thanks for reference, "force selection" will do component mode flexible. About your decision for my case: manipulation with input doesn't work, because it isn't see local variable in option.

**Comment by dihar** [comment]
I worked this case out with (onSelectionChange) in mdOption just now. Close the issue or this issue can be useful in other use cases?

**Comment by julianobrasil** [comment]
Better close.
