### ISSUE TITLE
Use only Material in a server rendering template.

### ISSUE THREAD

**Issue by mikeandersun** [angular/material2#5098]
#### Bug, feature request, or proposal:
I need only material in my Asp.Net core Razor views without any angular routing.

#### What is the expected behavior?
I expected that when I surrounded Razor element Material works and i can use Material tags in my Razor views. 

  ```
 <app-component>
        Loading...
        @await Html.PartialAsync("_header")
        @RenderSection("header", required: false)
        @await Html.PartialAsync("_SideNav")
        <div>
            @RenderBody()
            @await Html.PartialAsync("_footer")
        </div>
    </app-component>
```

#### What is the current behavior?
The current behavior replace all included with angular app template.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
