### ISSUE TITLE
 Cannot find name 'AnimationTriggerMetadata'

### ISSUE THREAD

**Issue by stephen-wu-yuan** [angular/material2#5100]
#### Bug, feature request, or proposal:
I want to use angular material2 to show a MdDialog. Using npm install @angular/material ,then run my project.it show some errors:
[10:29:26]  typescript: node_modules/@angular/material/typings/menu/menu-animations.d.ts, line: 14 
            Cannot find name 'AnimationTriggerMetadata'. 

      L14:  export declare const transformMenu: AnimationTriggerMetadata;

[10:29:26]  typescript: node_modules/@angular/material/typings/menu/menu-animations.d.ts, line: 19 
            Cannot find name 'AnimationTriggerMetadata'. 

      L19:  export declare const fadeInItems: AnimationTriggerMetadata;

[10:29:26]  typescript: node_modules/@angular/material/typings/select/select-animations.d.ts, line: 13 
            Cannot find name 'AnimationTriggerMetadata'. 

      L13:  export declare const transformPlaceholder: AnimationTriggerMetadata;

[10:29:26]  typescript: node_modules/@angular/material/typings/select/select-animations.d.ts, line: 23 
            Cannot find name 'AnimationTriggerMetadata'. 

      L23:  export declare const transformPanel: AnimationTriggerMetadata;

[10:29:26]  typescript: node_modules/@angular/material/typings/select/select-animations.d.ts, line: 29 
            Cannot find name 'AnimationTriggerMetadata'. 

      L29:  export declare const fadeInContent: AnimationTriggerMetadata;

Error: Failed to transpile program

**Comment by fxck** [comment]
Please follow the issue template, otherwise it will be impossible to help you (without knowing what versions of both libs you are using etc.). Also questions like this are better suited for stackoverflow or gitter, as it's unlikely a bug in neither material2 or angular.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
