### ISSUE TITLE
Why material2 when there is material-components-web?!

### ISSUE THREAD

**Issue by mikeandersun** [angular/material2#5101]
When we can use [material-components-web ](https://github.com/material-components/material-components-web) with Angular what is the different between this project and material-components-web?

**Comment by ciesielskico** [comment]
Start using material-components-web in your Angular app and you will see why ;)

**Comment by mikeandersun** [comment]
@ciesielskico  please elaborate me. 
material-components-web documents say that we can use it with many js frameworks(e.g Angular 2, Vue ,..).

**Comment by ciesielskico** [comment]
You can use it with and without frameworks, it is simple HTML and vanilla JS.
It will be a pain in the ass, tho.

Using angular/material2  will be much easier and quicker to develop apps, since you don't have to reinvent things like showing and hiding backdrops, displaying dialogs or snackbars etc.

**Comment by mikeandersun** [comment]
@ciesielskico  Thanks . 
But I think there are two implementations of one concept ( material design) in Angular ecosystem.
May be Material2 can use material-components-web.

**Comment by ciesielskico** [comment]
The issue tracker is not the right place for this discussion, please take it to gitter or stackoverflow and close this issue.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
