### ISSUE TITLE
md-input-container breaks route animations in angular 4.2.2

### ISSUE THREAD

**Issue by St1c** [angular/material2#5107]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I implemented app with angular material and angular 4.2.2 route animation - as previewed here:
https://github.com/matsko/ng4-animations-preview/blob/master/src/app/app.component.ts

Here is the code for animation:
```javascript
animations: [
    trigger("routerAnimations", [
      transition("* <=> *", [
        query(':enter, :leave', style({ opacity: 1, transform: 'translateY(0)' }), { optional: true }),

        group([

          query(':enter', group([
            style({ opacity: 0, transform: 'translateY(10%)' }),
            animate('0.3s 320ms ease-in', style('*')),
            animateChild()
          ]), { optional: true }),

          query(':leave', group([
            animateChild(),
            animate('0.3s ease-out', style({ opacity: 0, transform: 'translateY(10%)' }))
          ]), { optional: true })

        ])
      ])
    ])
  ]
```

The router animations works as expected, unless there is ```<md-input-container>``` somewhere in a routed component. If there is this element, animation simply doesn't run at all.

#### What is the current behavior?
There should be entry animation running, but animations are skipped entirely when ```<md-input-container>``` is present in routed component

#### What are the steps to reproduce?
See above

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "^2.0.0-beta.6",
"@angular/animations": "^4.2.2"

**Comment by pcholuj** [comment]
Confirmed, i have the same bug

**Comment by tanwald** [comment]
Same here. A `<md-input-container>` within a `<div>` breaks the animation of this `<div>`.

**Comment by St1c** [comment]
what exactly the flag P3 means here? this issue makes animations kinda unusable for applications with forms.

**Comment by JohnnyQQQQ** [comment]
@St1c this will be solved after https://github.com/angular/angular/issues/18193 is merged

**Comment by mmalerba** [comment]
fix for this has been merged: https://github.com/angular/angular/pull/18210
