### ISSUE TITLE
mdTooltip and mdDialog broken when md-grid-list is in template

### ISSUE THREAD

**Issue by LarsMontanaro** [angular/material2#5110]
#### Bug, feature request, or proposal:
I'm fairly new to Angular and have been working on a project using Angular Material library. I have encountered some strange behavior when using mdTooltip and mdDialog requests within an md-grid-list, and I was wondering what the cause of it is.

#### What is the expected behavior?
mdTooltip and mdDialog working as expected

#### What is the current behavior?
When hovering over a tooltip or attempting to call a dialog on an md-grid-tile element of an md-grid-list, they do not close. In the case of the dialog, the background opacity will revert to normal but the dialog content will remain on the page.

#### What are the steps to reproduce?
I altered an Angular startup plunker and was able to recreate this bug, as you can see here: https://embed.plnkr.co/8zbydmXP3PkTrmft0G0A/

The interesting thing is that (as you can see in the plunk) I've added a separate button which calls the openDialog method, and even that doesn't work. However! if I remove the md-grid-list tags entirely from the plunk, it does! You can see this behavior for yourself at the link.

**Comment by julianobrasil** [comment]
`cols` attribute of the <md-grid-list> is not optional. Without it the initialization of the component fails.

**Comment by julianobrasil** [comment]
Maybe it could defaults to 1...

**Comment by jelbourn** [comment]
Closing since missing `cols` will throw an error.
