### ISSUE TITLE
MdGridlist could set default cols to 1

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#5111]
#### Bug, feature request, or proposal:

Feature request.

#### What is the expected behavior?

`<md-grid-list>` could defaults the cols atribute to 1. See this issue: #5110 

#### What is the current behavior?

The component fails if you do not provide a column (the page is eventualy rendered with several bugs in other components and messages in the console)

#### What are the steps to reproduce?

In this plunker pass the mouse over the buttons (as said in this original issue: #5110)
Plunker: https://plnkr.co/edit/4VmPRb?p=preview

#### What is the use-case or motivation for changing an existing behavior?

The page should be rendered smothly if the cols attribute is missing.

**Comment by crisbeto** [comment]
I'm not sure that this is necessary. The grid list already throws an error that tells you when the cols are missing.

**Comment by julianobrasil** [comment]
It's not that important. But as it is kind of simple to do, I think it would make the first use of component more error proof without any great effort of the material team. It's up to you to discard the sugestion or push it to beyond the end of the line with a "really-nothing-else-to-do" label :wink:.

**Comment by jelbourn** [comment]
A grid-list with cols="1" is just...a list. We consider the omission of `cols` to be an indicator that the user hasn't done what they meant to.
