### ISSUE TITLE
Wrong button internal padding in cards and dialogs

### ISSUE THREAD

**Issue by peluprvi** [angular/material2#5115]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The `md-button` text should be aligned with the `md-card-title`, `md-card-content`, `md-card-subtitle`, etc. According to the specs, buttons in dialogs and cards have 8dp internal padding.

https://material.io/guidelines/components/cards.html#cards-content-blocks
https://material.io/guidelines/components/buttons.html#buttons-style

![](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3ZS05Q0pzLXpFZlk/components_cards25.png)

![](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B6Okdz75tqQsMjRTSi1CLWNVSDg/components_buttons_keyline1.png)

#### What is the current behavior?
padding: 0 16px

![image](https://user-images.githubusercontent.com/1561360/27100458-9288a886-5054-11e7-886a-1db290ba56d5.png)

#### What are the steps to reproduce?
```html
<md-card>
  <md-card-title-group>
    <md-card-title>Shiba Inu</md-card-title>
    <md-card-subtitle>Dog Breed</md-card-subtitle>
  </md-card-title-group>
  <md-card-actions>
    <button md-button>LIKE</button>
    <button md-button>SHARE</button>
  </md-card-actions>
</md-card>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
https://github.com/angular/material2/commit/de68202971aa5a1ce7e36d3e2c2fc26c6cdc4314

#### Is there anything else we should know?
Need testing when the button is aligned to the right.

Some Material Specs examples are using the same button texts with different margin and padding ([first two examples](https://material.io/guidelines/components/cards.html#)). I can't say witch one is right!

![](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3WFBLZjBNNGpnQzg/components_cards1.png)

![](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3Y1lRbzJERTJIa28/components_cards2.png)

**Comment by peluprvi** [comment]
Related to https://github.com/angular/material2/issues/4245, https://github.com/angular/material2/issues/3528

**Comment by jelbourn** [comment]
@crisbeto is there anything here not captured by those other two issues?

**Comment by crisbeto** [comment]
It looks like it would be covered by https://github.com/angular/material2/issues/4245. I'll close it as a dupe.
