### ISSUE TITLE
Buttons on left and right in md-card-actions

### ISSUE THREAD

**Issue by peluprvi** [angular/material2#5116]
#### Bug, feature request, or proposal:
Proposal to create an internal element to align the butons inside a `md-card-actions`.

#### What is the expected behavior?
Cards can have buttons both on the left and right.

https://material.io/guidelines/components/cards.html#cards-actions

![](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3MHh2ZlhHVUMyQlk/components_cards17.png)

#### What is the current behavior?
Buttons can only be aligned to the left or aligned to the right.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
https://github.com/angular/material2/commit/82d752b59e30a8a0f492a10f488464be784aba72

**Comment by peluprvi** [comment]
It can easily be done with CSS (flex) or using fxFlex:
```html
<md-card-actions>
  <button md-button>ACTION 1</button>
  <div fxFlex></div>
  <button md-button>ACTION 2</button>
</md-card-actions>
```

**Comment by MA-Maddin** [comment]
I was looking for that as well.

The solution with flex spacer item (`flex: 1 1 auto;`) is only working by setting `align="end"` in `<md-card-actions>`.

**Comment by peluprvi** [comment]
Confirmed on version https://github.com/angular/material2/commit/73aa43e98b8bf2782daf59bb7e7d12fa6a1b5604

The fsFlex solution still working with @angular/flex-layout 2.0.0-beta.8

**Comment by jelbourn** [comment]
We think this is something that should just be done in user-space css.

**Comment by curt953** [comment]
Thank you so much.

**Comment by sagarjsr** [comment]
</mat-card-content>
    <mat-card-actions style="text-align: center;">
    <button mat-button style="background-color: aquamarine">Know More</button>
</mat-card-actions>

**Comment by sagarjsr** [comment]
</mat-card-content>
     <mat-card-actions style="text-align: center;">
      <button mat-button style="background-color: aquamarine">Know More</button>
 </mat-card-actions>

**Comment by sagarjsr** [comment]
</mat-card-content>
    <mat-card-actions style="text-align: center;">
      <button mat-button style="background-color: aquamarine">Know More</button>
    </mat-card-actions>

**Comment by sagarjsr** [comment]
one button centre 
`</mat-card-content>
    <mat-card-actions style="text-align: center;">
    <button mat-button style="background-color: aquamarine">Know More</button>
 </mat-card-actions>`
