### ISSUE TITLE
md-input does not label the input with the placeholder text when using VoiceOver

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#512]
When visiting our demo-app page for md-input using VoiceOver on OSX, the placeholder text for the inputs is not used to label the inputs. When moving focus to the `<input>`, the reader simple announces "edit text blank". This occurs with Safari, Chrome, and Firefox.

**Comment by hansl** [comment]
https://github.com/angular/material2/commit/be5e93a648dc46bd3a285200cab460502954e0e0 didn't change the `for` attribute of the label :(
