### ISSUE TITLE
md-menu closing on any outside click

### ISSUE THREAD

**Issue by Yizhu** [angular/material2#5124]
#### Bug, feature request, or proposal:
**Feature request.**
I am trying to make a menu but letting the user open another menu if clicked on it without having to close the first, first.
How to change the default behavior?
https://plnkr.co/edit/AuYWkYRvr7Xw20QOdoYP?p=preview

#### What is the expected behavior?
So if the user clicked another menu, that click closes the first and opens the second
1.Click first menu to open
2.Click second menu to  close first menu and open second menu

#### What is the current behavior?
1.Click first menu to open
2.Click second menu but close first menu
3.Click second menu to open

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
  "@angular/material": "2.0.0-beta.2"

**Comment by jelbourn** [comment]
This is working as intended; only one menu should be open at a time.
