### ISSUE TITLE
Add support for align="center" on input container's content

### ISSUE THREAD

**Issue by mackelito** [angular/material2#5125]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
Center align inputs

#### What is the current behavior?
Only possible to align to start/end

#### What is the use-case or motivation for changing an existing behavior?
Center alignment should be possible just as start/end

For reference: https://github.com/angular/material2/blob/master/src/lib/input/input-container.ts#L319

**Comment by donroyco** [comment]
Why would this be a good idea?

**Comment by mackelito** [comment]
@donroyco: well there is already support for start and end.. why not add it for center as well?

**Comment by jelbourn** [comment]
I don't see why this would be necessary... in fact, I don't see why there's an API for `align` at all; it's just setting `text-align` on the input, which would be more simply done with CSS
