### ISSUE TITLE
[cdk-connected-overlay] add animation support on opening and closing

### ISSUE THREAD

**Issue by atshweza** [angular/material2#5127]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Make cdk-overlay-pane slidedown from cdk-overlay-origin

#### What is the current behavior?
cdk-overlay-pane appears under cdk-overlay-origin

#### What are the steps to reproduce?
Click Open Menu button in overlay demo.
Panel has no animation, it simply appears under button(cdk-overlay-origin)
https://github.com/angular/material2/blob/master/src/demo-app/overlay/overlay-demo.html
https://material2-test.firebaseapp.com/overlay

#### What is the use-case or motivation for changing an existing behavior?
Just Follow the Google material design guideline https://material.io/guidelines/motion/choreography.html#choreography-creation.
https://material.io/guidelines/motion/duration-easing.html#duration-easing-speed
I want to ensure that transition is slow enough that it can be understood

#### Which versions of Angular, Material, OS, browsers are affected?

@angular/material 2.0.0-beta.3

**Comment by jelbourn** [comment]
You can have animations on the content of the connected overlay: check out the select as an example

https://github.com/angular/material2/blob/master/src/lib/select/select.html
