### ISSUE TITLE
Card in a Tab is not displayed properly

### ISSUE THREAD

**Issue by usanyo** [angular/material2#5136]
Hi,
I found a bug. I expect to see the border of the card, even if it is in a tab. But currently you can't see it if the card is in the tabs.

I used this code snippet:
```
<md-tab-group>
  <md-tab label="One">
    <md-card>
      <p>this is a card in the tab</p>
    </md-card>
  </md-tab>
  <md-tab label="Two">
    <md-card>
      <p>this is a card in the tab</p>
    </md-card>
  </md-tab>
</md-tab-group>
<md-card>
  <p>this is a card out of the tabs</p>
</md-card>
```

And I got this:
![screenshot_2017-06-14 23-23-27](https://user-images.githubusercontent.com/11265863/27155694-323f1594-515a-11e7-915a-0181e813fee8.png)

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/4310

Basically, the tab body applies `overflow: hidden` to its contents and the card shadow you're expecting to see is being cut off by that. Your best bet is to wrap your card in a div and apply a little padding to it.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by usanyo** [comment]
@willshowell Thank you very much for the quick feedback! You solved my problem.
