### ISSUE TITLE
First of several md-buttons immediately showing up styled as if in hover-state

### ISSUE THREAD

**Issue by darrenbrett** [angular/material2#5138]
My dev environment:
@angular/cli: 1.0.1
node: 7.4.0
os: darwin x64
OS X El Capitan 10.11.6
MacBook Air

I'm using Material in my Angular 2 app, and am running into a situation where, after triggering the opening of a dialog box, which itself contains several vertically stacked md-buttons a user can click on, the first of those buttons immediately shows up with a darker color than the others, which is usually reserved for hover state. Not sure why this is happening, and what I can do to prevent or disable this behavior. The cursor is not located near the button, and yet it's showing behavior as if it was being hovered over or active.

The HTML for this dialog box containing buttons looks like this:

    <div class="discharge-form">
        <h3>Initiate Discharge</h3>
        <div class="discharge-form-fields">
    
            <div class="discharge-row row">
                <button md-button class="discharge-steps-button" (click)="sendFamilyDischargeEmail()">Create Family Discharge Email</button>
            </div>
    
            <div class="discharge-row row">
                <button md-button class="discharge-steps-button" (click)="sendFamilyDischargeRestaffEmail()">Create Family Restaff/Discharge Email</button>
            </div>
    
            <div class="discharge-row row">
                <button md-button class="discharge-steps-button" (click)="sendTherapistDischargeSummary()">Create Discharge Summary for Therapist</button>
            </div>
    
            <div class="discharge-row row">
                <button md-button class="discharge-steps-button" (click)="moveToDischarge()">Complete Move to Discharge</button>
            </div>
        </div>
    
        <div class="discharge-row row">
            <button md-button class="discharge-close-button" (click)="close()">CLOSE</button>
        </div>
    
    </div>

The CSS for the four main buttons looks like this:

    .discharge-steps-button {
          display: flex;
          flex-direction: column;
          padding: 5px 20px;
          margin-bottom: 10px;
          font-size: 18px;
          background-color: #f4f4f4;
          justify-content: center;
          align-items: center;
    }

To clarify, I'n not defining the hover/active styling, this is all handled by Angular Material. If I click within the opened dialog box, the darker styling of the button returns to normal. But upon re-triggering the opening of the dialog box, the first button is again styled as if hover-over or active.

Any ideas as to why this is happening? Is this a bug? Is there a way I can prevent or disable the behavior? By the way, the same thing happened when I made the items straight hrefs, instead of buttons. The first of the links showed us as if in hover or active state.

**Comment by willshowell** [comment]
Would you mind reproducing it? It doesn't seem to be happening with beta 6

https://plnkr.co/edit/PfeoBtqwLuyRuA6ZzbEI?p=preview

So technically that button _should_ be focused because focus changes to the first tabbable element in the dialog (once the dialog is closed, it'll dump back onto the document where it was before). You can verify this in the above plunker by opening the dialog and immediately hitting <kbd>space</kbd> and looking at the console.

That said, the focus styling should only be applied when you have focused it with the keyboard (will have the class `cdk-focused`). It should not be showing up when the dialog forces the focus to change onto itself.

**Comment by darrenbrett** [comment]
Thanks for the reply. When I tried what you suggested with the plunkr you set up, I didn't see the first item selected when hitting the 'space' key. I had to hover over an item to see focused styling applied. I'm using Chrome Version 58.0.3029.110 (64-bit). But knowing this is the default behavior, is there a way to disable it?

**Comment by jelbourn** [comment]
This is working as intended; the first item in the dialog is focused automatically for accessibility.

**Comment by BartoszBaczek** [comment]
Is there still no way to disable this behaviour? It doesn't look very good:

![obraz](https://user-images.githubusercontent.com/11254976/36091482-2bf5b3ca-0fe4-11e8-9a10-4b93766ba1cb.png)
