### ISSUE TITLE
Plunkr Templates seem broken: 404 tslib.ts not found

### ISSUE THREAD

**Issue by macjohnny** [angular/material2#5143]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The suggested plunkr template should work fine: https://goo.gl/DlHd6U

#### What is the current behavior?
Currently, https://goo.gl/DlHd6U fails due to an 404 error: tslib.ts not found

#### What are the steps to reproduce?
Plunker template: https://goo.gl/DlHd6U

**Comment by macjohnny** [comment]
It seems that adapting the system.config.js as follows resolves the issue:
```
System.config({
  paths: {
    'npm:': 'https://unpkg.com/'
  },
  map: {
    ...
    'tslib': 'npm:tslib'
  },
...
});
```
See also https://plnkr.co/group?place=topic%2Fplunker%2FoRvbsbsbiKA%2Fdiscussion

**Comment by macjohnny** [comment]
See the fixed example here: http://plnkr.co/edit/O5kshwAlDNrrl2KnWUqk?p=preview

**Comment by eugeniopaguntalan** [comment]
I thought I'm the only one who's experiencing this issue.

**Comment by macjohnny** [comment]
@eugeniopaguntalan that's exactly what I was thinking first, too, but then I tried on various systems over different network connections ;-)

**Comment by eugeniopaguntalan** [comment]
@macjohnny  I will try your proposed solution on this. Thanks

**Comment by eugeniopaguntalan** [comment]
Hi @macjohnny ,

I tried your solution. I changed the   'npm:': 'node_modules/' to 'npm:': 'https://unpkg.com/' and added  'tslib': 'npm:tslib' and it works! However I need to use node_modules locally :( 

I tried to update my npm but still having the same error :(

**Comment by macjohnny** [comment]
@eugeniopaguntalan did you install tslib locally? can you post a copy of your configuration?

**Comment by eugeniopaguntalan** [comment]
Yes @macjohnny , I've installed tslib locally.  I found a fix when using the  'npm:': 'node_modules/'. However it needs to add  'tslib': 'https://unpkg.com/tslib@1.7.1' on the map. Please see configuration below:
`/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/',
            //'npm:': 'https://unpkg.com/',
            'content:':'content/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            '@angular/material': 'npm:@angular/material/bundles/material.umd.js',
            //bootstrap
            'ng2-bootstrap': { format: 'cjs', main: 'bundles/ng2-bootstrap.umd.js', defaultExtension: 'js' },

            // other libraries
            'rxjs': 'npm:rxjs',
            'ts': 'npm:plugin-typescript@4.0.10/lib/plugin.js',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
            'ui-router-ng2': 'npm:ui-router-ng2/_bundles/ui-router-ng2.js',
            'text-mask-core': 'npm:text-mask-core',
            'md2-datepicker': 'node_modules/md2-datepicker',
            'text-mask-core': 'npm:text-mask-core',
            'angular2-text-mask': 'npm:angular2-text-mask/dist/angular2TextMask.js',
            'angular2-cookie': 'npm:angular2-cookie',
            'jquery': 'npm:jquery/dist/jquery.min.js',
            'tslib': 'npm:tslib'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            },
            'md2-datepicker': {
                format: 'cjs',
                main: 'md2datepicker.umd.js'
            },
            'text-mask-core': {
                defaultExtension: 'js'
            },
            'angular2-text-mask': {
                defaultExtension: 'js'
            },
            'angular2-cookie': {
                main: './core.js',
                defaultExtension: 'js'
            },
            'tslib': {
                defaultExtension: 'js'
            }
        }
    });
})(this);

var map = {
    '@angular': 'https://unpkg.com/@angular',
    'angular2-mdl': 'https://unpkg.com/angular2-mdl@latest/bundle/angular2-mdl.js',
    'rxjs': 'https://unpkg.com/rxjs',
    'main': 'main.js',
    'tslib': 'https://unpkg.com/tslib@1.7.1'
};

var packages = {

}

System.config({
    map: map,
    packages: packages
});
`

**Comment by macjohnny** [comment]
@eugeniopaguntalan are you using this configuration in a plunkr app? 
it could also be related to the `packages` configuration entry for `tslib`.
But anyway, if you use `'tslib': 'https://unpkg.com/tslib@1.7.1'` you seem to have a working solution.

**Comment by eugeniopaguntalan** [comment]
@macjohnny I've change my script below because tslib@1.7.1 may changed it's version. Please see changes:

 var map = {
    '@angular': 'https://unpkg.com/@angular',
    'angular2-mdl': 'https://unpkg.com/angular2-mdl@latest/bundle/angular2-mdl.js',
    'rxjs': 'https://unpkg.com/rxjs',
    'main': 'main.js',
    'tslib': 'node_modules/tslib/tslib.js'
};

**Comment by DevVersion** [comment]
Updated the Plunker template. Thanks for the issue! Let me know if you still have problems with it.

**Comment by macjohnny** [comment]
@devversion see the remarks in https://github.com/angular/angular/issues/17526#issuecomment-308844710:

Should be 'tslib': 'npm:tslib@1.6.1'

@1.6.1 is for TS <= 2.3.2, see https://www.npmjs.com/package/tslib
