### ISSUE TITLE
MdDialog 

### ISSUE THREAD

**Issue by di3orlive** [angular/material2#5146]
#### Bug, feature request, or proposal:
feature request, or proposal

#### What is the expected behavior?
global scroll if dialog height more then innerHeight 

I can propose 2 solutions:
1) add one more field for MdDialogConfig like 'popClass'
and it will be added for cdk-overlay-container
2) add one more field for MdDialogConfig like 'customeTemplate': bool
and if true then dialog template will be added in the end of body like now but without any wrappers 
so user can add custom animation and so on

#### What is the current behavior?
No scroll and dialog cutted

#### What are the steps to reproduce?
just open current dialog 

#### What is the use-case or motivation for changing an existing behavior?
No scroll and dialog cutted

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
4.0.0/latest/win10/2.2.0/59

#### Is there anything else we should know?
no

**Comment by crisbeto** [comment]
If you want your dialog to be scrollable, you have to wrap you content in the `md-dialog-content` element. [You can see an example here.](https://github.com/angular/material2/blob/master/src/demo-app/dialog/dialog-demo.ts#L118)

**Comment by di3orlive** [comment]
@crisbeto yes i saw it before 
but it's not very comfortable `you can scroll dialog only in dialog`

**Comment by jelbourn** [comment]
If I'm interpreting your question right, I think you just want an `overflow: auto` element inside of the dialog.
