### ISSUE TITLE
floatPlaceholder="never" misaligned on Safari (macOS)

### ISSUE THREAD

**Issue by leocaseiro** [angular/material2#5159]
#### Bug, feature request, or proposal:
CSS Bug

#### What is the expected behavior?
Placeholder should be aligned in the same position as the text like on Chrome/Firefox:
> ### Chrome
> ![floatplaceholder-working-chrome](https://user-images.githubusercontent.com/940070/27212566-3a856546-52a4-11e7-9f0d-ba340832f098.gif)

#### What is the current behavior?

> ### Safari
> ![bug-floatplaceholder-never](https://user-images.githubusercontent.com/940070/27212354-c4642d94-52a2-11e7-9191-3b5a6d0e5c4f.gif)

#### What are the steps to reproduce?
Any app should emulate. My example is with `devapp`

* `gulp serve:devapp`
* go to http://localhost:4200/input
* Enable "Never Float"

or

```html
<md-input-container floatPlaceholder="never">
  <input mdInput name="filter" type="text" placeholder="Filter">
</md-input-container>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
@angular/*: 4.2.2
@angular/material: 2.0.0-beta.6
typescript: 2.3.4
```

```
Safari: Version 10.1.1 (12603.2.4)
```

```
Chrome: Version 58.0.3029.110 (64-bit) (working)
Firefox: 53.0.3 (64-bit) (working)
```
#### Is there anything else we should know?
Works on Firefox and Chrome (tested on macOS only)

**Comment by mmalerba** [comment]
Possibly related to #5262, will check after #5154 is merged
