### ISSUE TITLE
multiple dialogs displaying

### ISSUE THREAD

**Issue by zpydee** [angular/material2#5163]
#### Bug, feature request, or proposal:
(potential) bug

#### What is the expected behavior?
only show one dialog at a time

#### What is the current behavior?

![screen shot 2017-06-16 at 1 30 34 pm](https://user-images.githubusercontent.com/6129162/27224976-4d2a3cf0-5298-11e7-9030-92085091dfb7.png)

i have encountered a situation wherein the MdDialog service seems to be opening multiple dialogs. I suspect this may be linked to nested routed routes keeping some degree of state that MdDialog uses, but have yet to confirm.

#### What are the steps to reproduce?

hoping the below reproduces and its not an error peculiar to my implementation...

- create nested routes
- add dialog in parent route
- add dialog in child route
- open parent route dialog then close (i'm using `md-dialog-close` attr)
- navigate to child route and repeat

parent dialog should display after closing child dialog.

(in my image above, one dialog is bigger than the other, so you can see both at the same time.)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular@4.2.0
material@2-beta.6

**Comment by zpydee** [comment]
i am starting to doubt that this is linked to routing. it seems to be occurring quote often for me. has anyone else experienced issues where multiple clicks on a `button` that closes a dialog is required for the dialog to disappear?

**Comment by zpydee** [comment]
some more visual feedback...
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6129162/27228600-92c21160-52a8-11e7-9a4f-bc7a64bf694e.gif)

this example was generated by opening dialogs multiple times. each time a new instance is added. when I navigate between routes, a parent / child dialog is added and it seems to me that the inclusion of tabs in a dialog adds two instances.

i'm (fairly) sure there is a bug at play here but look to the community for feedback. I'm using the dialog strictly per docs.

any help / feedback / common experience comments would be greatly appreciated.

**Comment by julianobrasil** [comment]
I don't think it's related to tabs inside dialog. This plunker with tabs inside dialog is working fine: https://plnkr.co/edit/ZInpbU?p=preview

Try inspecting your app using angular chrome plugin augury: https://augury.angular.io/

Also try to provide a plunker reproducing the error.

**Comment by zpydee** [comment]
i think i've realised my mistake. i'm subscribing to add button click to open the dialog and forgot unsubscribe from these on view destroys - whoops. gonna close fro now whilst I confirm.
