### ISSUE TITLE
Autocomplete panel doesn't close when an option click

### ISSUE THREAD

**Issue by Stas-tolpekin** [angular/material2#5165]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
After I click on an option (using mouse cursor) the autocomplete suggestion panel should be closed.

#### What is the current behavior?
When I click on an option (using mouse cursor) the autocomplete suggestion panel closing and immediately opening again. This bug occurs only in Internet Explorer (I tested on version 11).

#### What are the steps to reproduce?
Plunker:
https://plnkr.co/edit/7zAjuhQJdibmPCaLsulm

Use Internet Explorer 11.
1. Select option in 'State1' using the mouse cursor. 
2. Input 'State2' is blocked by 'State1' 

Also, this bug can be reproduced on official documentation
https://material.angular.io/components/component/autocomplete

#### What is the use-case or motivation for changing an existing behavior?
I have two autocomplete input. when user select option in one input, the application should do focus on the other input programmatically. With this bug, when user select option in first input, application do focus on the other input, but the suggestion panel of first input stays opened. In result, a user sees two suggestion panels for each input.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.2
Material 2.0.0-beta.6
OS Windows 10 (build 15063.0)
TypeScript 2.3.4
Internet Explorer 11

#### Is there anything else we should know?
In Chrome, Edge and Firefox this bug does not reproduce.

**Comment by julianobrasil** [comment]
You don't need two autocompletes to see the problem. The panel just don't close after selecting a state in IE11 without throwing any error. 

If you double click the desired item, with short interval between the clicks, it closes. Maybe something with the ripple effect is going wrong in IE11 preventing event bubling.

**Comment by kevincaradant** [comment]
Hi

I  got the same issue today with the latest version under IE11 (Windows 7).

I will try to create a plunker If I got the time but firstly, something seems to be weird in my snippet code like that ? : 

```
<div fxFlex="100" *ngIf="!displayConfirmBtn" fxLayoutAlign="center center">
  <mat-spinner [diameter]=30 [strokeWidth]="2" fxFlex="4" *ngIf="loadingFamilyInfoAdmin$ | async"></mat-spinner>
  <mat-form-field fxFlex fxFlex="100">
    <input class="margin-left-x10" matInput [placeholder]="placeholder | translate" [matAutocomplete]="reactiveAuto" [formControl]="searchFamiliesForm">
    <mat-icon matPrefix [ngClass]="{'color-green-x1':icon === 'control_point', 'color-black-x1':icon === 'search'}">{{icon}}</mat-icon>
  </mat-form-field>

  <mat-autocomplete (optionSelected)="onSelection($event.option.value)" [displayWith]="displayWith" #reactiveAuto="matAutocomplete">
    <mat-option *ngFor="let family of families$ | async" [value]="family">
      <span>
        <b>{{family.name}}</b>&nbsp;
        <i *ngIf="family?.description">({{family.description}})</i>
      </span>
    </mat-option>
  </mat-autocomplete>
</div>
```

Thank you in advance for your first feeling about it.

NB: No issue under Firefox / Chrome
