### ISSUE TITLE
Input enter placeholder animation is skipping when use autocomplete

### ISSUE THREAD

**Issue by Stas-tolpekin** [angular/material2#5167]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
User focus on input with autocomplete. Placeholder is transforming to label **with** animation.

#### What is the current behavior?
User focus on input with autocomplete. Placeholder is transforming to label **without** animation.

#### What are the steps to reproduce?
1. Use simple autocomplete. For example https://material.angular.io/components/component/autocomplete (Example tab)
2. When the input is empty, focus on it. 
Result: The animation is skipped.

#### What is the use-case or motivation for changing an existing behavior?
Skipping animations looks a little bad. And an absence of animation may confuse users.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.2
Material 2.0.0-beta.6
OS Windows 10 (build 15063.0)
TypeScript 2.3.4
All supported browsers

**Comment by crisbeto** [comment]
This should be resolved by https://github.com/angular/material2/pull/3992.

**Comment by josephperrott** [comment]
Closing as resolved
