### ISSUE TITLE
Unable to build quick start project with material

### ISSUE THREAD

**Issue by houssem-yahiaoui** [angular/material2#5186]
Hello,

After adding the material to the quick start project and building i went through this issue represeted in the following screenshot.

![screen shot 2017-06-17 at 5 19 40 pm 2](https://user-images.githubusercontent.com/15380057/27254492-4441d80c-5381-11e7-9ca3-924f106c405a.png)

I saw such issue before for old version of Typescript below 2.2 but i'm using the 2.3.4 version.

M'i missing something ?

**Comment by DevVersion** [comment]
Is it possible that your global TypeScript version is different than the one you have inside of your project's `package.json`.

To confirm that this is not the case, can you try running `$(npm bin)/tsc -v` and `tsc -v`

**Comment by houssem-yahiaoui** [comment]
Wonderful updating it fixed the problem, thank you !

**Comment by DevVersion** [comment]
Glad to hear that. Closing the issue.
