### ISSUE TITLE
Determinate progress-bar broken in @angular rc1 #430 [Still not working]

### ISSUE THREAD

**Issue by Pixcell** [angular/material2#519]
#### Bug, feature request, or proposal:

Bug (https://github.com/angular/material2/issues/430)

I did everything like you said before closing the issue 430, but it is still not working (cf my last response)
I think you don't see comment notifications on closed issues, so I open a new one.

#### What is the expected behavior?

Progress bar to be filled with correct percentage

#### What is the current behavior?

![screen shot 2016-05-17 at 08 48 40](https://cloud.githubusercontent.com/assets/4005291/15313687/2c478302-1c0d-11e6-940e-9a7230c567af.png)

![screen shot 2016-05-17 at 08 56 05](https://cloud.githubusercontent.com/assets/4005291/15313694/3e3e94b0-1c0d-11e6-9b73-c393c79660af.png)

#### What are the steps to reproduce?

```JS
import {MdToolbar} from '@angular2-material/toolbar';
import {MdButton} from '@angular2-material/button';
import {MdCard} from '@angular2-material/card';
import {MdProgressBar} from '@angular2-material/progress-bar';

@Component({
  selector: 'home',
  templateUrl: 'components/home/home.component.html',
  styleUrls: ['components/home/home.component.css'],
  providers: [],
  directives: [MdToolbar, MdButton, MdCard, MdProgressBar]
})
export class HomeComponent implements OnInit{
```

``` HTML
<p>
     <span>PID completion {{h.pid.percentage}}%</span><span *ngIf="h.pid.warning">{{h.pid.warning}}        </span>
    <md-progress-bar mode="determinate" [value]="h.pid.percentage"></md-progress-bar>
</p>
```

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?

```JS
    "@angular/common": "^2.0.0-rc.1",
    "@angular/compiler": "^2.0.0-rc.1",
    "@angular/core": "^2.0.0-rc.1",
    "@angular/http": "^2.0.0-rc.1",
    "@angular/platform-browser": "^2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.1",
    "@angular/router": "^2.0.0-rc.1",
    "@angular/router-deprecated": "^2.0.0-rc.1",
    "@angular2-material/button": "^2.0.0-alpha.4",
    "@angular2-material/card": "^2.0.0-alpha.4",
    "@angular2-material/checkbox": "^2.0.0-alpha.4",
    "@angular2-material/core": "^2.0.0-alpha.4",
    "@angular2-material/icon": "^2.0.0-alpha.4",
    "@angular2-material/input": "^2.0.0-alpha.4",
    "@angular2-material/progress-bar": "^2.0.0-alpha.4",
    "@angular2-material/progress-circle": "^2.0.0-alpha.4",
    "@angular2-material/radio": "^2.0.0-alpha.4",
    "@angular2-material/sidenav": "^2.0.0-alpha.4",
    "@angular2-material/toolbar": "^2.0.0-alpha.4",
```
#### Is there anything else we should know?

Working with Chrome Version 50.0.2661.94 (64-bit) on Mac OSX

Please tell me if you need anything else.

**Comment by DevVersion** [comment]
@Pixcell This works fine for me. 
- http://plnkr.co/edit/6dWmU5t84PLLs7MZKa5q?p=preview

Can you modify the Plunker, to represent your issue?

**Comment by jelbourn** [comment]
@josephperrott I can reproduce this in my material2 sample app; we can take a look next time you're around

**Comment by Pixcell** [comment]
@DevVersion, I tried a lot of things (even getting values from a webservice, http://plnkr.co/edit/6dWmU5t84PLLs7MZKa5q?p=preview), but I can't reproduce the issue inside the plunker, sorry.
I'm somewhat glad that @jelbourn managed to reproduce it inside his demo app (Because otherwise I would feel very stupid)

I would really appreciate if you could keep me in the loop about this issue, and tell me what was the cause when you find it.

Just let me know if I can help in anyway.

**Comment by sendilkumarn** [comment]
I think the class `.md-progress-bar-fill` is not properly setting `scalex` value

**Comment by Pixcell** [comment]
Thanks a lot, it was fixed with release of alpha.5-2 !
