### ISSUE TITLE
md-tabs not loaded into DOM during unit testing

### ISSUE THREAD

**Issue by praveendath92** [angular/material2#5199]
#### Bug, feature request, or proposal: 
Bug

#### What is the expected behavior?
Html for Tabs should be added to the DOM after calling `.compileComponents()` and be available for querying with methods such as `querySelector()`

#### What is the current behavior?
The Html content for tabs doesn't seem to be evaluated properly in the test environment - it works in the normal setup though. I only see the tab groups related Html but nothing for actual tab headers or their respective contents.

#### What are the steps to reproduce?

Component HTML
```html
<md-tab-group class="background" selectedIndex=2>
      <md-tab>
            <ng-template md-tab-label>
                  <span><md-icon>work</md-icon> WORK</span>
            </ng-template>
            <h1>Best pasta restaurants</h1>
            <p>...</p>
      </md-tab>
      <md-tab>
            <ng-template md-tab-label>
                  <span><md-icon>school</md-icon> STUDY</span>
            </ng-template>
            <h1>Best pasta restaurants</h1>
            <p>...</p>
      </md-tab>
      <md-tab>
            <ng-template md-tab-label>
                  <span><md-icon>import_contacts</md-icon> PAPERS</span>
            </ng-template>
            <h1>Best pasta restaurants</h1>
            <p>...</p>
      </md-tab>
</md-tab-group>

```

Component spec:
```typescript
import { MaterialModule } from '@angular/material';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import { FlexLayoutModule } from '@angular/flex-layout';
import { BackgroundModule } from './background.module';

export function main() {
    describe('Background component', () => {
        let backgroundDOMEl: HTMLElement;
        beforeEach(async(() => {
            TestBed.configureTestingModule({
                declarations: [TestComponent],
                imports: [MaterialModule, FlexLayoutModule, BrowserAnimationsModule, 
                    BackgroundModule]
            }).compileComponents();
        }));
        
        beforeEach(() => {
            backgroundDOMEl = TestBed.createComponent(TestComponent)
                .debugElement.children[0].nativeElement;
        });

        it('should contain Tabs', () => {
            expect(
                backgroundDOMEl.querySelectorAll('#md-tab-label-0-0')[0].textContent
            ).toContain('WORK');
        });
    });
}

@Component({
  selector: 'test-cmp',
  template: '<pkp-background></pkp-background>'
})
class TestComponent {}
```

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
4.2, 2.0.0-beta.8, macOS, Chrome

**Comment by willshowell** [comment]
Maybe looking at the unit tests from the source will help:

1. [Tab header](https://github.com/angular/material2/blob/master/src/lib/tabs/tab-header.spec.ts)
2. [Tab body](https://github.com/angular/material2/blob/master/src/lib/tabs/tab-body.spec.ts)
3. [Tab group](https://github.com/angular/material2/blob/master/src/lib/tabs/tab-group.spec.ts)

**Comment by praveendath92** [comment]
@willshowell, Thank you. Will check it out soon. This should work.
