### ISSUE TITLE
Datepicker -  not consistent validation UX - calling .focus() function vs focusing by click

### ISSUE THREAD

**Issue by vmachacek** [angular/material2#5200]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I use this.datePicker.nativeElement.focus(); and than click away, it should not turn red. In contrast to that, if I just click to other date picker and than click away this one doesnt turn red. Both of them are set to required

#### What is the current behavior?
When I call .focus() function and click away it will turn red, Is I just click into different date picker it will not turn red when losing focus. Both of them are required 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template:
http://plnkr.co/edit/D7jz90TNViqyVyqmKgYs

#### What is the use-case or motivation for changing an existing behavior?
Its consitant UX, my idea is I should not care how field got focused, it should behave consistently and predictable . 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2.0.0-beta.6

**Comment by willshowell** [comment]
> Both of them are set to required

In your plunker, `toDate` does not have a required validator

**Comment by vmachacek** [comment]
yeah, silly me.
