### ISSUE TITLE
Autocomplete component not working

### ISSUE THREAD

**Issue by gtzinos** [angular/material2#5201]
Hello,

I am using the autocomplete component but it doesn't work for me. I have the same code as in your example and this is my package.json:

"dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/material": "^2.0.0-beta.6",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/router": "^4.1.3",
    "@types/file-saver": "0.0.1",
    "angular2-websocket": "^0.9.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "intro.js": "^2.5.0",
    "jasmine-data-provider": "^2.2.0",
    "ng2-cookies": "^1.0.12",
    "primeng": "^4.0.3",
    "protractor-jasmine2-screenshot-reporter": "^0.3.5",
    "raven-js": "^3.15.0",
    "rxjs": "^5.4.0",
    "socket.io-client": "^2.0.2",
    "typings": "^2.1.1",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.12"
  },
  "devDependencies": {
    "@angular/cli": "1.1.1",
    "@angular/compiler-cli": "^4.1.3",
    "@types/jasmine": "2.5.49",
    "@types/node": "~7.0.23",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "protractor-browser-logs": "^1.0.351",
    "sw-precache": "^5.1.1",
    "ts-node": "~3.0.4",
    "tslint": "~5.4.2",
    "typescript": "~2.3.4"
  }

Error message:

 Cannot read property 'activeItem' of undefined
    at MdAutocompleteTrigger.webpackJsonp

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
