### ISSUE TITLE
bug with the char '[' in auto complete

### ISSUE THREAD

**Issue by lilling** [angular/material2#5203]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
filter all countries

#### What is the current behavior?
after typing [ in the input the auto complete stops working

#### What are the steps to reproduce?
type [ in your example

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://material.angular.io/components/component/autocomplete

#### What is the use-case or motivation for changing an existing behavior?
Isn't that obvious?

**Comment by donroyco** [comment]
It also happens when you type <kbd>*</kbd> or <kbd>+</kbd> or <kbd> \ </kbd> or <kbd>?</kbd>.

**Comment by willshowell** [comment]
See https://github.com/angular/material2/pull/4921. Should be fixed in next docs release

**Comment by kara** [comment]
Closing, as this is fixed on master.
