### ISSUE TITLE
Datepicker  enable/disable on user action

### ISSUE THREAD

**Issue by vibingopal** [angular/material2#5207]
#### Bug, feature request, or proposal:
Hi Team,

I am not able to disable the date picker based on action. I have a checkbox where when the user selects the checkbox the date picker should get enabled, if not it should be in disabled state.
I tried with disabled property but didn't worked. Could you please help

Angular : 4.0.0
Materila -2.0.0-beta.6

**Comment by z639** [comment]
Presumably you'd just disable whatever element (likely a button) is used to open the date picker ? https://plnkr.co/edit/OJQnG4IjYUq7nE8XqPMU?p=preview

**Comment by vibingopal** [comment]
This is my code. Please check 

http://plnkr.co/edit/PJFTTISwLsPtEkJtkQqk?p=preview

**Comment by willshowell** [comment]
There is no bug with Material... You are mixing model driven and template driven forms. Check the console.
