### ISSUE TITLE
Add 'beforeClose' Observable to MdDialogRef

### ISSUE THREAD

**Issue by wulfsberg** [angular/material2#5209]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Being able to start processing instantly when a user selects an option in an MdDialog.

#### What is the current behavior?
An 'afterClose' Observable is available which only fires after all animations are done.

#### What are the steps to reproduce?
The behavior is easily seen on the "Examples" page of https://material.angular.io/components/component/dialog

#### What is the use-case or motivation for changing an existing behavior?
In many cases, a dialog functions as a confirmation for some additional processing (such as deleting an item), which in turn asynchronously updates the interface (say, removing the item from a list once deleted serverside).
Having to wait for an animation to finish before launching the async server call introduces unnecessary latency in the UI.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.6

#### Is there anything else we should know?
Delaying until after animation is a deliberate choice, as described here: https://github.com/angular/material2/issues/3890, but I find that reacting instantly is also a reasonable behavior, so I propose an Observable for each.

**Comment by willshowell** [comment]
Related to https://github.com/angular/material2/pull/3460

**Comment by jelbourn** [comment]
Yeah, having `beforeClose` is something we intended to do (which is why we called the existing one `afterClose` to begin with).

**Comment by willshowell** [comment]
Oh also #4647

**Comment by jelbourn** [comment]
Ah, tracking via #4647 (thanks @willshowell)

**Comment by wulfsberg** [comment]
The onBefore/closeAttempt/etc seems more concerned with _how_ the user attempts to close the dialog, and the possibility of canceling that.
As long as it _also_ makes the _value_ of the choice reasonably easily available, it can pull double duty for my need, but it does seem to be semantically slightly different. (And apparently got somewhat mothballed over various standardization/accessibility issues).

**Comment by willshowell** [comment]
@wulfsberg You're right that #3460 is really just focused on how the dialog has been closed. I'd suggest mentioning in #4647 that a beforeClose observable should emit the closing value so that your use case doesn't accidentally get forgotten here
