### ISSUE TITLE
Datepicker is not properly displayed

### ISSUE THREAD

**Issue by vibingopal** [angular/material2#5215]
#### Bug, feature request, or proposal:

Hi Team,

I am using date picker in my application and the component is shown in the end of the page. Now when i click on datepicker i am not able to see the last week of the month because of overlay is coming down. How to automatically adjust the date picker view as per page.

Angular : 4.0.0
material : 2.0.0-beta.6

**Comment by crisbeto** [comment]
This should be fixed in the next release by https://github.com/angular/material2/pull/4696.
