### ISSUE TITLE
Identifier 'isActive' is not defined. 'RouterLinkActive' does not contain such a member

### ISSUE THREAD

**Issue by Legited** [angular/material2#5218]
#### Bug, feature request, or proposal:
Bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular @4.2.2

VScode Angular language service throws an error, when following the example from navigation tabs:
```
<nav md-tab-nav-bar>
  <a md-tab-link
     *ngFor="let link of navLinks"
     [routerLink]="link"
     routerLinkActive #rla="routerLinkActive"
     [active]="rla.isActive">
    {{tabLink.label}}
  </a>
</nav>

```
Error: 

> Identifier 'isActive' is not defined. 'RouterLinkActive' does not contain such a member

What I have is: 
![screen shot 2017-06-19 at 2 33 35 pm](https://user-images.githubusercontent.com/13325924/27300138-a026aee6-54fc-11e7-83ed-cfe3a4f57042.png)

Although the application compiles and works as expected, is there a way to get rid of error?

**Comment by willshowell** [comment]
Since everything is working as expected, I feel like this is an issue with VScode Angular language service

**Comment by julianobrasil** [comment]
I found some similar errors using VSCode and template variables too. But as in this case, it's not causing any trouble other than that red underline.

**Comment by jelbourn** [comment]
Not related to Angular Material.
