### ISSUE TITLE
Cursor persists on input after blur event with autocomplete

### ISSUE THREAD

**Issue by calbear47** [angular/material2#5221]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When blur is fired on an input field, it should blur so to match native browser behavior.  

#### What is the current behavior?
Even when explicitly called, blur does not blur an input field when used with autocomplete. 

#### What are the steps to reproduce?

http://plnkr.co/edit/Qj4E20BpAlcC8i8aw7Qw?p=preview

#### What is the use-case or motivation for changing an existing behavior?

When using the autocomplete with an input field, I want to blur the input when a user selects an autocomplete option with either keyboard stroke or mouse click. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Verified on Chrome 58.0.3 and Firefox 53.0.3.
Angular 4.1.3
Material 2.0.0-beta.6
Windows 10

**Comment by willshowell** [comment]
setTimeout may be required

```ts
setTimeout(() => this.searchBarInput.nativeElement.blur());
```

The problem is that you are blurring it, but the trigger is refocusing for accessibility immediately after ([Source](https://github.com/angular/material2/blob/master/src/lib/autocomplete/autocomplete-trigger.ts#L354-L368))

**Comment by calbear47** [comment]
@willshowell I see that. setTimeout does achieve the intended effect I was looking for. Thanks for helping!
