### ISSUE TITLE
Demo Site Broken - Sidenav and Toolbar do not work.

### ISSUE THREAD

**Issue by proales** [angular/material2#5226]
#### Bug:
Demo Site Broken - Sidenav and Toolbar do not work.

#### What is the expected behavior?
Sidenav and Toolbar should open and work correctly.

#### What is the current behavior?
Sidenav and Toolbar show broken text and no funcationality.

#### What are the steps to reproduce?
https://material.angular.io/components/component/menu
https://material.angular.io/components/component/toolbar

#### Is there anything else we should know?
proales@ if questions.

**Comment by willshowell** [comment]
Sidenav issue being tracked at https://github.com/angular/material2/issues/4969 and it'll probably be fixed within the hour via https://github.com/angular/material2/pull/4911 and the brand new release

Not sure what is broken with the toolbar, it looks fine in chrome
![screen shot 2017-06-19 at 5 49 25 pm](https://user-images.githubusercontent.com/6475576/27307419-a915731e-5517-11e7-951d-224ae16e7875.png)

**Comment by jelbourn** [comment]
Sidenav is fixed now, don't see anything wrong with the toolbar.
