### ISSUE TITLE
Slider:  possible to make a slider with two input values?

### ISSUE THREAD

**Issue by TonySheva** [angular/material2#5230]
#### Bug, feature request, or proposal:
Is it possible to make a slider with two input values, for example to select a price range? 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Is there anything else we should know?

thx

**Comment by donroyco** [comment]
Dupe of #1331

**Comment by jelbourn** [comment]
See #1331
