### ISSUE TITLE
cli ng build --prod still not compiling when noUnusedParameters activated after upgrading to material 2.0.0-beta.7

### ISSUE THREAD

**Issue by AliShd** [angular/material2#5236]
#### Bug, feature request, or proposal:
After upgrading Material to 2.0.0-beta.7 `ng build --prod` still not compiling when `noUnusedParameters: true` in `tsconfig.json`.

#### What is the expected behavior?
It should compile without any errors in production mode with `noUnusedParameters: true` in `tsconfig.json`.

#### What is the current behavior?
Giving multiple errors like this:

> ERROR in ng:///../node_modules/@angular/material/typings/index.d.ts.MdCheckbox.html (2,1078): '$event' is declared but never used.

#### What are the steps to reproduce?
Just compile using Angular CLI with production mode using command `ng build --prod`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/animations": "~4.2.3",
    "@angular/common": "^4.2.3",
    "@angular/compiler": "^4.2.3",
    "@angular/core": "^4.2.3",
    "@angular/forms": "^4.2.3",
    "@angular/http": "^4.2.3",
    "@angular/platform-browser": "^4.2.3",
    "@angular/platform-browser-dynamic": "^4.2.3",
    "@angular/router": "^4.2.3",
    "@angular/material": "^2.0.0-beta.7",
...
"@angular/cli": "1.1.2",
"typescript": "~2.4.0"

#### Is there anything else we should know?
`tsconfig.json` file:
{
  "compileOnSave": false,
  "compilerOptions": {
    "alwaysStrict": true,
    "baseUrl": "src",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "moduleResolution": "node",   
    "noUnusedParameters": true,
    "outDir": "./dist/out-tsc",
    "skipLibCheck": true,
    "sourceMap": true, 
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [
    "dist",
    "node_modules",
    "**/*.spec.ts"
  ]
}

**Comment by Emerceen** [comment]
When run 
ng serve --environment=prod --target=production

error is the same

**Comment by e-cloud** [comment]
@AliShd It might related to typescript version, how about roll back to v2.3 and try?

**Comment by AliShd** [comment]
No, not even working with typescript 2.3.4. Getting the same errors.

**Comment by DevVersion** [comment]
Yeah this is an issue of Angular itself at the moment. See https://github.com/angular/angular/issues/17131

Once that issue is solved I will update our AOT CI task to also check with `noUnusedParameters` (so we can see those issues as early as possible)
