### ISSUE TITLE
md-tab: iframe reloads on tab focus

### ISSUE THREAD

**Issue by anupvarma** [angular/material2#5239]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
iframe content shouldn't be reloaded every time the tab is on focus.

#### What is the current behavior?
iframe embedded with tab causes the iframe to reload  as and when user keeps switching between the tabs.

#### What are the steps to reproduce?
Step 1: Create 2 tabs with having iframe in 1st tab.
Step 2: Keep the iframe src to some external page (for data entry purpose).
Step 3: Fill some fields in tab 1 frame.
Step 4: Toggling tabs will reload iframe everytime. 

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/DADYadzGOFI5GqkkITkA?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It's a bug, the existing behavior is unintended

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.2.2
Material: 2.0.0-beta.6

**Comment by tulinisarg** [comment]
I have the same issue embedding Node Red into my App. The behaviour is similar with object tag. Any help will be much appreciated.

**Comment by paul-thomas0** [comment]
Same here

**Comment by jelbourn** [comment]
See https://github.com/angular/angular/issues/16994

**Comment by anupvarma** [comment]
@jelbourn @tbosch Caching doesn't resolve the problem when the iframe is embedded within a tab.

Check the plunker updated with tabs: http://plnkr.co/edit/kA5XtZ?p=preview

Can you please suggest a work around for tabs

**Comment by jelbourn** [comment]
@anupvarma it is a bug in Angular, not something that can be addressed at the application level

**Comment by ShubhenduVaid** [comment]
Guys any **solution** to this issue.
Having similar issue 
```
<mat-tab-group>
 <mat-tab>Content 1</mat-tab>
 <mat-tab><object style="height:500px;width:1000px" data="https://www.wynk.in/music"></object></mat-tab>
</mat-tab-group>
```

**Comment by Mojo1** [comment]
omg - same issue - iframe is reloading on calendar toggle, menu toggle and so on ... every toggle
The iframe is in a tab

**Comment by ShubhenduVaid** [comment]
Probably the issue is that tab component is playing on the "display" value.
I made a similar component which changes the "visiblity" value instead of "display" and it stopped reloading.
