### ISSUE TITLE
Accordion style in Tabs

### ISSUE THREAD

**Issue by ChinesePeanuts** [angular/material2#5240]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Normal accordion style in tabs

#### What is the current behavior?
Strange box-shadow style when  a accordion is in a tab 
The problem does not occur for a nested accordion in the one having the issue

#### What are the steps to reproduce?
http://plnkr.co/edit/31szYf9AGLDpD7b56TYo

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested with latest version of Angular, Material2 beta7 on Firefox 52.0.2

#### Is there anything else we should know?
This is caused by the ```overflow: hidden``` rules from the tabs containers

**Comment by julianobrasil** [comment]
Try surround your **`<md-accordion>`** with a **`<div style="padding: 7px">`**, or the padding of your preference.

Not sure if this is a bug. See this: https://github.com/angular/material2/issues/5136#issuecomment-308571358

**Comment by ChinesePeanuts** [comment]
Indeed, might not be a bug.
Padding did the trick, thanks for your help
