### ISSUE TITLE
MdDialog works in safari, but not in chrome or firefox

### ISSUE THREAD

**Issue by danielptm** [angular/material2#5243]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MdDialog works as expected in safari 10.1, but not in firefox 54.0, neither in chrome 58.0

#### What is the current behavior?
Text displays in MdDialog in safari, but not in firefox or chrome

#### What are the steps to reproduce?
Follow steps for setting up MdDialog from https://material.angular.io/components/dialog/overview

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^4.0"
    "@angular/material": "^2.0.0-beta.7",
    "@angular/platform-browser": "^4.0",
    "@angular/platform-browser-dynamic": "^4.0",
"typescript": "~2.2.1"
macosx10.2

#### Is there anything else we should know?
![chrome](https://user-images.githubusercontent.com/11135179/27335102-b584b38a-55cb-11e7-929a-56a22496faa2.png)
![firefox](https://user-images.githubusercontent.com/11135179/27335103-b5a53e5c-55cb-11e7-8c3e-6291ffe521d1.png)
![safari](https://user-images.githubusercontent.com/11135179/27335104-b5a53790-55cb-11e7-8aec-2929db5064dc.png)

**Comment by danielptm** [comment]
First 2 images are chrome and firefox, last 1 is safari

**Comment by crisbeto** [comment]
Are you getting any errors in the console? The example from our site works on all 3 browsers for me.

**Comment by danielptm** [comment]
Ok weird, yeah no errors, just does not work

**Comment by julianobrasil** [comment]
@danielptm , did you put the dialog component in the entryComponents array of the feature module?

**Comment by danielptm** [comment]
@julianobrasil yes I put I in entryComponents of app.module.ts

**Comment by julianobrasil** [comment]
Is it possible do provide a plunker?

**Comment by danielptm** [comment]
I will try to do that, Im using angular cli, so not sure exactly how to to do it, ill give it a shot

**Comment by danielptm** [comment]
Ok so I found the problem...

**Comment by danielptm** [comment]
constructor(
    private loginService:LoginService,
    private app:AppComponent,
    private loginResources:LoginResourcesService,
    public dialog: MdDialog,
  ){}

@Component({
  selector: 'dialog',
  templateUrl: 'text.html'
})
export class ConditionalText {}


This works in safari, but does not in chrome or firefox...If you change the selector name to dlog then it works in all 3 browsers

**Comment by danielptm** [comment]
@julianobrasil  If you want recreate it, try to follow the tutorial for basic dialog (https://material.angular.io/components/dialog/overview), and use the same name as in the constructor as well as selector

**Comment by jelbourn** [comment]
Sounds like you're accidentally creating a native `<dialog>` element by using the selector `"dialog"`. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog. This would be similar to trying to create a component with selector `"input"`.

Note that, by HTML spec, all custom element names are required to have a `-` in the tag name.
