### ISSUE TITLE
Progress Spinner secondary/buffer color

### ISSUE THREAD

**Issue by pdeveltere** [angular/material2#5246]
**Bug, feature request, or proposal:**

feature request

**What is the expected behavior?**

Would be nice to have (optionally?) a secondary background color for the progress spinner. The progress bar already has this, as seen in the picture below.

![screen shot 2017-06-20 at 16 12 38](https://user-images.githubusercontent.com/7511273/27337948-2c1bbf36-55d4-11e7-9fcd-26bae601a121.png)

**What is the current behavior?**

The progress spinner does not have a secondary/buffer color. As seen in the picture below.
![screen shot 2017-06-20 at 16 12 45](https://user-images.githubusercontent.com/7511273/27338080-80270522-55d4-11e7-86af-780dc142c6ad.png)

**What is the use-case or motivation for changing an existing behavior?**

![screen shot 2017-06-20 at 16 15 17](https://user-images.githubusercontent.com/7511273/27338101-944f16fc-55d4-11e7-9a75-0cd028031002.png)

I have to import an extra external library to implement this feature, everything else I do with material. Would be great if I could do it with material aswel. It also shows the progress better in my opinion.

**Comment by jelbourn** [comment]
While I can see the value, this feature would end up being so low priority that we'd effectively never get to it.

**Comment by mackelito** [comment]
Why not leave this open incase someone from the community would like to give it a go? :)
