### ISSUE TITLE
DatePicker [Min] should permit the min date as well

### ISSUE THREAD

**Issue by angular2fan** [angular/material2#5249]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
I should be able to select the min date value that is specified by the [min] attribute. i.e. the validation message should not appear if I select the min date that is displayed by the calendar control

#### What is the current behavior?
I see the red validation message if I select the min date that is specified in the [min] attribute

#### What are the steps to reproduce?
plnkr is broken at this time, so couldnt include one. Will add one after the plnkr is working

1. Specify the min attibute in the html and give it a date value from the component
2. specify the md-error tag for mdDatepickerMin .
3. select the 1st available date that is displayed in the calendar and the red validation pops up.
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

Please let me know if I am missing something and will be happy to close this issue. thanks.

**Comment by angular2fan** [comment]
@julianobrasil -- thought of pulling u into this thread :).

**Comment by julianobrasil** [comment]
I think beta.7 has solved it.

**Comment by angular2fan** [comment]
yup, just updated the material and it works. Thanks sir.
