### ISSUE TITLE
Simple Overlay Dir bottom

### ISSUE THREAD

**Issue by xonuzofa** [angular/material2#5252]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Overlay should be placed below target ALWAYS.

#### What is the current behavior?
Defaults to normal behavior.

    <md-select overlayDir="bottom" placeholder="Filter By Status" [(ngModel)]="filterStatus" (change)="onFilterSelect()">
        <md-option value="All">All</md-option>
        <md-option value="Accounting">Accounting</md-option>
        <md-option value="Closed">Closed</md-option>
        <md-option value="Opened">Opened</md-option>
        <md-option value="Pending Approval">Pending Approval</md-option>
        <md-option value="Rejected">Rejected</md-option>
    </md-select>

Why does the Md-Select overlay options not go below the target?  I do not want the selected option to be where the target is and options above to be above the target.  My md-select is at the top of a div below my navbar and when the second or third option is selected, the top options are hidden behind the navbar.  I need it to always drop down.  There is very poor documentation for this feature.

**Comment by willshowell** [comment]
Think you could replicate it in the a plunker? Per the spec, the options try to overlap with the previously selected option. If there isn't room above, it should be repositioning itself below.

See here http://plnkr.co/edit/wBz1gbVwy5wMbJRQMWsW?p=preview

**Comment by xonuzofa** [comment]
http://plnkr.co/edit/P2nlGeJaFJSRKlrBj10h?p=preview

Does not reposition for navbar

**Comment by xonuzofa** [comment]
Shouldn't overlayDir="bottom" change the default behavior to make it drop down?  I can't really find any documentation on that and in the code (https://github.com/angular/material2/blob/master/src/lib/select/select.ts), doesn't seem like this feature is added.

**Comment by willshowell** [comment]
`overlayDir` stands for overlay directive, not overlay direction. It is not part of the API.

I'm afraid there isn't a way to reposition the select. Your plunker doesn't show the select going underneath your navbar, so I assume there are some styles that are missing from the plunker. Why not just set the navbar to a lower z index than 1000?

Alternatively, you can get really tricky with the `panelClass` input

**Comment by xonuzofa** [comment]
Yea I am using bootstrap for navbar.  Didn't know about the z-index, that fixes the problem.  Thanks for the help!
