### ISSUE TITLE
sidenav is still terrible

### ISSUE THREAD

**Issue by davidmontgom** [angular/material2#5259]
I whet though hell and highwater to update all of my packages for anguar2 material..updating angular-cli etc.  sidenav is now working on https://material.angular.io/...great!

But for me..still that horrible failure despite the update.  

@angular/material@2.0.0-beta.7

**Comment by willshowell** [comment]
Please provide a reproduction or even the slightest context as to the "horrible failure" you're experiencing

**Comment by davidmontgom** [comment]
words cant describe..the same type of error on https://material.angular.io/ that was going on for a while.  No errors are being thrown but when I open the side nav ..like the styling broken.  Once upon a time it was working though but when I updated awhile back to use the new date control sidenav broke.

**Comment by mackelito** [comment]
Are you running a custom theme?

**Comment by davidmontgom** [comment]
Here is my theme my-theme.scss


@import '~@angular/material/theming';
@include mat-core();

$primary: mat-palette($mat-indigo);
$accent:  mat-palette($mat-teal , 700, A100, A400);

$theme: mat-light-theme($primary, $accent);
@include angular-material-theme($theme);
