### ISSUE TITLE
Invalid font CSS for mat-input-container class

### ISSUE THREAD

**Issue by robmv** [angular/material2#5262]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

font CSS style for .mat-input-container should be valid 

#### What is the current behavior?

Default typography theme set

    font: 400 inherit/1.125 Roboto,Helvetica Neue,sans-serif

which both Firefox and Chrome developer tools show as invalid (the inherit value for font-size). So all Input fields are not correctly font styled, only if a parent is (for example body).

#### What are the steps to reproduce?

Check https://material.angular.io/components/input/examples and go to the inspector and notice the invalid CSS

![screenshot from 2017-06-20 17-12-25](https://user-images.githubusercontent.com/1652983/27356274-e91c36a4-55db-11e7-94a5-c2271c455f32.png)

#### What is the use-case or motivation for changing an existing behavior?

To have correct default Roboto fonts styles on input field without depending on body styles like beta 6 did

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material beta 7

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material2/pull/5154.

**Comment by gtranter** [comment]
While the invalid CSS problem is fixed, the problematic behavior is not. Font size is still inherited which is not correct unless parent element font size happens to be defined as 16, which in most circumstances is unlikely. Material Design specifies that the font size be 16, so inherit is wrong.
