### ISSUE TITLE
md-error incorrect render when used with ngFor

### ISSUE THREAD

**Issue by dimabutenko** [angular/material2#5263]
#### What is the expected behavior?

If I implement my component like this, it's behavior which I want

```html
<md-input-container [formGroup]="formGroup">
                    <input mdInput [mdDatepicker]="datepicker" [formControlName]="control.name" [readOnly]="control.isReadonly"
                    [placeholder]="control.placeholder" [required]="control.isRequired">
                    <button *ngIf="!control.isReadonly" mdSuffix [mdDatepickerToggle]="datepicker"></button>
                    <md-error *ngIf="formGroup.controls[control.name].hasError('required')">Hello world</md-error>
                </md-input-container>
                <md-datepicker #datepicker></md-datepicker>
```
![](https://lh4.googleusercontent.com/9XzHLuR0hgVFMQbWGMBOK5QaAWcYMNZDBjK-BxjJbePsD4tBUzgh1bnCYswOJo1thuwvJGj9EzWz-dM=w3841-h1977-rw)

#### What is the current behavior?
Now I have array messages. And I have this implementation:

```html
<md-input-container [formGroup]="formGroup">
                    <input mdInput [mdDatepicker]="datepicker" [formControlName]="control.name" [readOnly]="control.isReadonly"
                    [placeholder]="control.placeholder" [required]="control.isRequired">
                    <button *ngIf="!control.isReadonly" mdSuffix [mdDatepickerToggle]="datepicker"></button>
                    <ng-template ngFor let-errorMessage [ngForOf]="formGroup.controls[control.name].errorMessages">
                        <md-error *ngIf="formGroup.controls[control.name].hasError(errorMessage.type)">
                            {{ errorMessage.message }}
                        </md-error>
                    </ng-template>
                </md-input-container>
                <md-datepicker #datepicker></md-datepicker>
```
![](https://lh4.googleusercontent.com/cyze8NsfzTrqjiqG36CbIZWcMg_-DcTtY5S2TDgQexmhPuRwbgLhgATUoAiiHSx-GlOPb2D7JqHCHHw=w1918-h1944-rw)

Maybe I use it incorrect. But i want to generate md-error automatically from array. I don't know what is this - new feature, bug or proposal. thanks

**Comment by willshowell** [comment]
Here is a plunker using ngFor with md-error

http://plnkr.co/edit/VNDRcGx3DrVgYBUnqsS8?p=preview

That said, I'm not entirely certain what it is you're trying to accomplish and whether or not it is a bug.

**Comment by dimabutenko** [comment]
@willshowell Can you see it? http://plnkr.co/edit/LTfzvKJUn1vGHW3N8dBE?p=preview

Error message incorrect rendering, i think.

**Comment by willshowell** [comment]
Ah I see. I feel like this is a problem with `<ng-content select="md-error">` not working well with `ng-template`, but I'm not sure yet.

**Comment by willshowell** [comment]
Yeah someone with more knowledge about how transclusion works with structural directives should answer this (like @jelbourn).

I'd suggest something like this is an alternative in the mean time

http://plnkr.co/edit/MU65Gw9Dn7AvYV3R4hKB?p=preview
```html
<md-error *ngFor="let message of currentMessages()">
  {{ message }}
</md-error>
```
```ts
currentMessages(): string[] {
  return this.messages
    .filter(m => this.formControl.hasError(m.type))
    .map(m => m.message);
}
```

**Comment by jelbourn** [comment]
This is a consequence of how content project works; only the top-level elements inside the container are projected, so adding the intermediate container make it not work. Something to potentially file an issue on for Angular Core.

**Comment by AlainD-** [comment]
Hi, I know this is closed, but I wanted to post my solution for those monitoring this issue. I managed to get things done by nesting `<md-error>` elements:

```Typescript
  public validationOptions: any = {
    // Messages for form validation
    messages: {
      username: [
        {validator: 'required', message: 'Please enter the username'},
        {validator: 'maxlength', message: 'The username cannot exceed 5 characters'},
        {validator: 'pattern', message: 'Only "." and alpha numeric characters are accepted'}
      ]
    }
  };
  
  private createFormControls(): void {
    this.username = new FormControl('', [
      Validators.required,
      Validators.maxLength(5),
      Validators.pattern('[a-zA-Z0-9\.]+')
    ]);
  }
```


```HTML
<md-input-container>
  <input mdInput placeholder="Username" type="text" name="username" formControlName="username">
  <md-error *ngFor="let option of validationOptions.messages.username">
    <md-error *ngIf="username.hasError(option.validator)">{{option.message}}</md-error>
  </md-error>
</md-input-container>
```

which produces:
![angular-material2-5263](https://user-images.githubusercontent.com/5165564/29674284-feec3dc8-88f1-11e7-8612-687a52de9311.png)
