### ISSUE TITLE
input and select still misaligned in beta.7

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#5264]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

When placed side by side, mdInput and mdSelect should have the underline aligned.

#### What is the current behavior?

mdInput and mdSelect are still a little bit misaligned in beta.7

#### What are the steps to reproduce?

Plunker: http://plnkr.co/edit/2Pc3B4?p=preview

![image](https://user-images.githubusercontent.com/25405143/27359268-3a836e1c-55f1-11e7-95a3-80034e08f044.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/compiler: 4.2.3
@angular/compiler-cli: 4.2.3
@angular/core: 4.2.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/language-service: 4.2.3
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/platform-server: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.1.2

Windows 10, Chrome: 58.0.3029.110 (64-bit)

**Comment by jelbourn** [comment]
Still tracked via #2124
