### ISSUE TITLE
Add e2e tests for mdInput with textarea

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#5265]

**Comment by robindijkhof** [comment]
There already are tests right? `material2\e2e\components\input-e2e.spec.ts`

About the referenced issue:

> ### The result of getText from an input element is always empty
This is a webdriver quirk. <input> and <textarea> elements always have empty getText values. Instead, try element.getAttribute('value').


[source](https://github.com/angular/protractor/blob/master/docs/faq.md#the-result-of-gettext-from-an-input-element-is-always-empty)

**Comment by jelbourn** [comment]
Updated issue to specify e2e tests for `mdInput` with a `<textarea>`

**Comment by robindijkhof** [comment]
#5517

**Comment by DevVersion** [comment]
Seems to be done with #5517
