### ISSUE TITLE
add exemple on tooltip class

### ISSUE THREAD

**Issue by ss-bb** [angular/material2#5270]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
easier to add a class on tooltip

#### What is the current behavior?
I can't find any info about how to properly use the new mdTooltipClass. currently looking the review [here](https://github.com/angular/material2/blob/734eccc14875eff5c1519104dfec60be06fe9caa/src/demo-app/tooltip/tooltip-demo.html) but I can't make it work

#### What are the steps to reproduce?
doc isn't very explicit about it -> [here](https://material.angular.io/components/tooltip/api). 
Would be lovely to have a working exemple

#### What is the use-case or motivation for changing an existing behavior?
I can't figure out how to put a class to my tooltip. I'm having bunch of different error either way I tried so far

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest (so far 06/21/2017)

**Comment by donroyco** [comment]
Have you checked [tooltip.md](https://github.com/angular/material2/blob/734eccc14875eff5c1519104dfec60be06fe9caa/src/lib/tooltip/tooltip.md)?

**Comment by willshowell** [comment]
Can you explain what you tried?

**Comment by sj8716643** [comment]
I am trying using mdTooltipClass but can not make it work either.
I tried exact same code as here(https://github.com/angular/material2/blob/734eccc14875eff5c1519104dfec60be06fe9caa/src/demo-app/tooltip/tooltip-demo.html)

~~~
[mdTooltipClass]="{'file-tooltip': showTooltipClass}"
~~~

file-tooltip class simply changes the background color.
And showTooltipClass  were set to true in ts component.

**Comment by willshowell** [comment]
@sj8716643 setting `showTooltipClass` to true should apply the class, does it not? It behaves the same as [`NgClass`](https://angular.io/api/common/NgClass)

**Comment by sj8716643** [comment]
@willshowell  Thanks, it works now.
I think it may be the problem with angular-CLI. It works after recompiling the code but I can't make it work yesterday.
