### ISSUE TITLE
bug(md-dialog-actions): It's not at the bottom of the dialog

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#5277]
#### Bug, feature request, or proposal:

Bug, I think.

#### What is the expected behavior?

The action buttons to be always at the bottom of the dialog

#### What is the current behavior?

If you set the height of the dialog, the action buttons stay at the end of the dialog content, instead of at the bottom of the dialog.

#### What are the steps to reproduce?

Plunker: http://plnkr.co/edit/N1eZhf?p=preview

![image](https://user-images.githubusercontent.com/25405143/27388542-304b8b92-5672-11e7-82e1-3ec16ffbbacf.png)

#### What is the use-case or motivation for changing an existing behavior?

Follow [material design specifications](https://material.io/guidelines/components/dialogs.html#dialogs-specs), if I get them right.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Tried it with Material beta.7 and with the latest build (in plunker), using Chrome.

**Comment by willshowell** [comment]
Looks like a dupe of https://github.com/angular/material2/issues/4609

**Comment by julianobrasil** [comment]
Yes, it is. Closing it.
