### ISSUE TITLE
Date-picker is not setting the value when entered via keyboard

### ISSUE THREAD

**Issue by MaickelHubner** [angular/material2#5282]
#### Bug, feature request, or proposal:
When I type (via keyboard) a value in the format DD/MM/YYYY, the component is not setting the entered date

#### What is the expected behavior?
When entering a date via keyboard, it is set in the component

#### What is the current behavior?
When entering via keyboard the date is null

#### What are the steps to reproduce?
![1](https://user-images.githubusercontent.com/15674062/27401787-dc64d136-569a-11e7-8d46-9cdf661fa19b.jpg)
![2](https://user-images.githubusercontent.com/15674062/27401794-e1795390-569a-11e7-8ffa-8cf68466e6cb.jpg)
![3](https://user-images.githubusercontent.com/15674062/27401799-e5d6b72a-569a-11e7-9faf-d23180647e49.jpg)

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.3 Material 2.0.0-beta.7, MacOSX 10.12.5, Typescript 2.2.2 and Safari 10.1.1

#### Is there anything else we should know?
My code (no secrets) - Local format and time: Brazil UTC-3:

  <md-input-container *ngIf="atualiza_data_fim">
    <input mdInput placeholder="Até" [mdDatepicker]="dataAte" [(ngModel)]="data_fim">
    <button mdSuffix [mdDatepickerToggle]="dataAte"></button>
  </md-input-container>
  <md-datepicker #dataAte [startAt]="data_fim" [touchUi]="true"></md-datepicker>

**Comment by willshowell** [comment]
Is it working with a MM/DD/YYYY value?

**Comment by MaickelHubner** [comment]
Yes, @willshowell. If I inform in MM/DD/YYYY format it works.

**Comment by willshowell** [comment]
Look at [some of these other issues](https://github.com/angular/material2/issues?utf8=%E2%9C%93&q=is%3Aissue%20dateadapter) for working with a dateadapter. The datepicker can't automatically know which format you wish to use, so you must instruct it via some configuration. 

@julianobrasil's plunker here shows it working with brazilian portuguese locale https://plnkr.co/edit/FlgGpjqyDlypas0VZJzo?p=preview

**Comment by MaickelHubner** [comment]
Thanks @willshowell. It worked!!!

**Comment by DevGomes** [comment]
Thanks @willshowell this is solution saved me!
