### ISSUE TITLE
mat-stretch-tabs not working 

### ISSUE THREAD

**Issue by codegastudio** [angular/material2#5286]
#### Bug, feature request, or proposal:
mat-stretch-tabs has no effect

Desktop mode
<img width="320" alt="capture d ecran 2017-06-21 a 22 48 21" src="https://user-images.githubusercontent.com/8655261/27406130-4569d328-56d4-11e7-8877-e37a1320f51a.png">

"Mobile" mode (with or without mat-stretch-tabs)
<img width="328" alt="capture d ecran 2017-06-21 a 22 48 43" src="https://user-images.githubusercontent.com/8655261/27406162-5724a7e6-56d4-11e7-9816-2ada9404c1d2.png">

#### What are the steps to reproduce?

```
<md-tab-group mat-stretch-tabs>
        <md-tab label="Infos"></md-tab>
        <md-tab label="Paiement"></md-tab>
        <md-tab label="Webradio"></md-tab>
</md-tab-group>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.3
Material 2.0.0-beta.7
All browser

Try to alter directly min-width in css but has no effect too.
Help please this going me crazy :/

**Comment by MurhafSousli** [comment]
Use `md-stretch-tabs` instead

**Comment by codegastudio** [comment]
@MurhafSousli this not working anymore.
I test it before try `mat-stretch-tabs`.

**Comment by BamiGorengo** [comment]
You dont need this. Just use:

```
.mat-tab-list {
  .mat-tab-label {
    @include mediaMax($resTablet) {
      flex-basis: 0;
      flex-grow: 1;
    }
  }
}
```

**Comment by codegastudio** [comment]
@BamiGorengo Thx, but could you develop @include mediaMax($resTablet) ?
i get `No mixin named mediaMax` error on angular-cli compilation

**Comment by BamiGorengo** [comment]
Aight damn! My fault sorry! Yeah its one of my own Mixins:

```
@mixin mediaMin($var) {
  @media only screen and (min-width: $var) {
    @content;
  }
}
```

This is the Mixin if you want it. Ore simply use native MediaQueries:

```
@media only screen and (min-width: 900px) {
    flex-basis: 0;
    flex-grow: 1;
}
```

**Comment by codegastudio** [comment]
```
.mat-tab-list {
  .mat-tab-label[_ngcontent-c3] {
    min-width: 72px;
  }
}
```
Solved my pb
Your implementation was always overwrited by tabs js creation. 
Thx

**Comment by codegastudio** [comment]
Damn `_ngcontent-c3` could be change to `_ngcontent-c10` or anything else so it's not possible to overwrite this class altered when tabs component is generated :/
Custom `.mat-tab-label ` in css or any other class associated to an `md-tab-label` is ignored.
Force style déclaration directly in html is also useless cause the object is totally rewritten by tabs generator process

**Comment by codegastudio** [comment]
Ok so i found this solution

```
.mat-tab-list {
  div[role^='tab'] {
    min-width: 72px;
  }
}
```

**Comment by BamiGorengo** [comment]
Just Setup your Component to encapsulation: ViewEncapsulation.None

**Comment by alexzaytsev-newsroomly** [comment]
ViewEncapsulation.None is a horrible suggestion; and the fix just above with role^ didn't work for me?

**Comment by vesrah** [comment]
I agree that disabling ViewEncapsulation is a terrible idea.  You can add /deep/ to codegastudio's suggestion.
