### ISSUE TITLE
Datepicker MIN doesn't disable the available dates anymore

### ISSUE THREAD

**Issue by vmachacek** [angular/material2#5291]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I set min attribute the dates before should be disabled

#### What is the current behavior?
When I set min attribute the dates before are not disabled

#### What are the steps to reproduce?
Just use datepicker. You have to use latest release - 2.0.0-beta.7

#### What is the use-case or motivation for changing an existing behavior?
The user is allowed to select date which is not allowed by validation attribute.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular material - 2.0.0-beta.7, this was working in 2.0.0-beta.6.

**Comment by rafaelss95** [comment]
I can't reproduce it here: http://plnkr.co/edit/tkbmmlrATmjXN5sE9EbK

**Comment by vmachacek** [comment]
I'm sorry, it was my mistake (again). I can confirm this works fine.
