### ISSUE TITLE
triggerValue of MdSelect as @Input

### ISSUE THREAD

**Issue by RobYed** [angular/material2#5294]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
I'd like to be able to set the `triggerValue` of a `MdSelect`. The use case is, that I wish to display a `triggerValue` which is different from the `MdOption`'s `textContent` (which is automatically taken).
Therefore it would be great, if `triggerValue` would be an `@Input` of `MdSelect`.

#### What is the current behavior?
`triggerValue` is a readonly property of `MdSelect`. Consequently there is no possibility to manually set a `triggerValue` (if there is some, let me know!).

#### What is the use-case or motivation for changing an existing behavior?
I use a `MdOption` to set a filter for some search. It shows the option's values and their count of occurences. When an option is selected, the count of occurences will appear in the `MdSelect`'s `triggerValue`, but without styling, therefore looking fairly misplaced.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.2.2
Material: 2.0.0-beta.6

#### Is there anything else we should know?
If this is a feature you consider to add, I could try to implement it and open a PR.

And of course, big thanks for this great project! I was also using the AngularJS version of Material and it has always been a pleasure to use it!!

**Comment by willshowell** [comment]
This seems kinda like https://github.com/angular/material2/issues/2275 (with PR at https://github.com/angular/material2/pull/3341).

**Comment by RobYed** [comment]
Yeah, that one would fix my issue. Thanks!
