### ISSUE TITLE
Input and Selects are diffrent Styled

### ISSUE THREAD

**Issue by BamiGorengo** [angular/material2#5295]
I am not sure, is the Input wrong ore the select? ore both?

just check this image: https://image.prntscr.com/image/EiD5wnkET-SHkxlBQECmDQ.png
And the Height is verry diffrent to to the inputs: https://image.prntscr.com/image/E3dHbx2NTCSINc3tWDxCzA.png
https://image.prntscr.com/image/cnrztoP-Sd6So-oReXi2mw.png

Please make a norm that every input element is same from the look.

I think i dont need to explain any more ;)

**Comment by jelbourn** [comment]
Tracked via #2124
