### ISSUE TITLE
Datepicker overflow

### ISSUE THREAD

**Issue by SebastianGiro** [angular/material2#5306]
#### Bug, feature request, or proposal:
Datepicker overflow bug (Overlay problem)

#### What is the expected behavior?
The datepicker should auto position up if it doesn't have space down

#### What is the current behavior?
The datepicker just overflow the parent container

#### What are the steps to reproduce?
![image](https://user-images.githubusercontent.com/8485281/27451192-ae8c62ae-5764-11e7-9dd5-fd0f1919ff2f.png)

#### Is there anything else we should know?
Related to:
https://github.com/angular/material2/issues/3504

**Comment by donroyco** [comment]
Please add a Plunker to your issue. Are you using the latest beta? Because #4406 is in there.

**Comment by SebastianGiro** [comment]
Thats true @donroyco , my bad.
