### ISSUE TITLE
Problem to bind [(ngModel)] in <md-radio-group> highlight at startup fails with class attribute

### ISSUE THREAD

**Issue by GustavoCostaW** [angular/material2#5309]
Hey people,

I'm using **Angular Material beta 7**, and I have a component with the following code snippet

```html
{{question.answer}}
<md-radio-group [(ngModel)]="question.answer" name="question{{i}}">
               <div id="problem" *ngFor="let alternative of question.alternatives" class="my-class">
                  <md-radio-button [value]="alternative.id">
                    {{alternative.title}}
                  </md-radio-button>
                  <div>remove<div>
                </div>
</md-radio-group>
```

if the `div#problem` has `class` attribute the  `[(ngModel)]="question.answer"` in md-radio-group doesn't bind when the component is started, see below behavior when `div#problem` does not have `class` attribute:

![example2](https://s9.postimg.org/9foqqi3xb/Screen_Shot_2017-06-21_at_22.04.48.png)

But if I add `class` attribute, the bind does not work when the component is started.

![example1](https://s9.postimg.org/rtz9uhg7z/Screen_Shot_2017-06-21_at_20.36.40.png)

**Demo**: http://plnkr.co/edit/k3xXPY?p=preview

**Simulate the problem when you add and remove `class` in `div#problem`**

**Comment by willshowell** [comment]
Strangely importing FlexLayoutModule is causing the issue. In this plunker, you can see it working

http://plnkr.co/edit/nC2gkC?p=preview

**Comment by GustavoCostaW** [comment]
@willshowell Wow, It's strange, I created this issue first in Angular Flex Layout, but @ThomasBurleson told me to create here.

https://github.com/angular/flex-layout/issues/322

**Comment by willshowell** [comment]
@ThomasBurleson could you take a look at this plunker?

http://plnkr.co/edit/sVbxtBHtaXS9mh9ZC4ns?p=preview

It distills the problem down to a bare minimum. You can see on line 94 of `main.ts` that importing FlexLayoutModule causes the issue.

**Comment by GustavoCostaW** [comment]
Closing this issue because it's apparently a bug in the Angular Flex Layout

Thank you @willshowell
