### ISSUE TITLE
mat-select-underline in google chrome

### ISSUE THREAD

**Issue by xonuzofa** [angular/material2#5312]
#### Bug, feature request, or proposal:
beta 7 - Issue with mat-select-underline.  Not showing sometimes, inside of table and other random times.

        <dt>CTU</dt>
        <dd>
            <div class="row" style="margin-top: 20px;">
                <div class="col-sm-6">
                    <md-select [(ngModel)]="id_ctu" placeholder="CTU" (change)="onChangeCTUSelect($event)">
                        <md-option *ngFor="let ctu of ctus" [value]="ctu._id">{{ctu.unit}}</md-option>
                    </md-select>
                </div>
            </div>
        </dd>
        <dt style="margin-top: 10px;">MP</dt>
        <dd>
            <div class="row" style="margin-top: 20px;">
                <div class="col-sm-6">
                    <md-select [(ngModel)]="id_mp" placeholder="MP" (change)="onChangeMPSelect($event)">
                        <md-option *ngFor="let mp of mps" [value]="mp._id">{{mp.unit}}</md-option>
                    </md-select>
                </div>
            </div>
        </dd>

    <dt>Accounting Code</dt>
    <dd>
        <div class="row" style="margin-top: 20px;">
            <div class="col-sm-6">
                <md-select [(ngModel)]="id_accountingcode" placeholder="Accounting Code" (change)="onChangeAccountingCodeSelect($event)">
                    <md-option *ngFor="let accountingcode of accountingcodes" [value]="accountingcode._id">{{accountingcode.description}}</md-option>
                </md-select>
            </div>
        </div>
        <div class="row" style="margin-top: 20px;">
            <div class="col-sm-6">
                <md-select [(ngModel)]="subaccounting_code" placeholder="Subaccounting Code" (change)="onChangeSubaccountingCodeSelect($event)">
                    <md-option *ngFor="let subaccountingcode of getSubAccountingCodes()" [value]="subaccountingcode.description">{{ subaccountingcode.description }}</md-option>
                </md-select>
            </div>
        </div>
    </dd>

Same code for both, two has underlines, two does not.

![screen shot 2017-06-22 at 4 22 46 pm](https://user-images.githubusercontent.com/2785016/27456538-1418cafc-5767-11e7-8258-5fa90e26fe54.png)

Now I have messed with the styling in chrome and have increased the class mat-select-underline to height 2px instead of 1px and this is the result I get.

![screen shot 2017-06-22 at 4 24 22 pm](https://user-images.githubusercontent.com/2785016/27456596-482cf584-5767-11e7-80a5-3a5725c2bd9b.png)

I am also getting similar results inside a table.

![screen shot 2017-06-22 at 4 31 56 pm](https://user-images.githubusercontent.com/2785016/27456915-57e87f24-5768-11e7-9c42-6592e3fd8c80.png)

Above are in chrome.  Below are in safari.

![screen shot 2017-06-22 at 4 33 49 pm](https://user-images.githubusercontent.com/2785016/27457036-c3a93c80-5768-11e7-9335-dd4aa2f50653.png)

![screen shot 2017-06-22 at 4 34 16 pm](https://user-images.githubusercontent.com/2785016/27457045-c96e9d86-5768-11e7-9106-a3ab9b5139a1.png)

**Comment by xonuzofa** [comment]
Seems like an issue with the browser and zooming.  Different zooms percentages show and don't show lines.

**Comment by mmalerba** [comment]
@xonuzofa have you tried with the input by any chance? I'm currently refactoring the select to share more code with the input so this might go away if it's not a problem with the input

**Comment by xonuzofa** [comment]
So I have moved away from the material library since. The mdselect boxes didnt align properly, there were some bugs with the z-index and drop down, theres no way to control the dropdown direction. Md-hints are also very messy. I messed with css and got it to work somewhat but I found that using native boostrap 4 element with form groups and using the built in validator classes you can very easily build a color schema for required, warning, invalid and successful. It looks much more professional now and is easier for the user to see which fields must be filled out.

**Comment by mmalerba** [comment]
I do see the problem at 90% zoom on the select, looks like the move to share code with input will resolve it though http://plnkr.co/edit/yUzFm4zqxwsS8hx4oqm4?p=preview

will be fixed by #6488
