### ISSUE TITLE
no provider for MdMutationObserverFactory

### ISSUE THREAD

**Issue by j3ddesign** [angular/material2#5313]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Checkbox should render and function

#### What is the current behavior?
Upon loading the component containing MdCheckbox components, the error `No provider for MdMutationObserverFactory` is thrown, crashing all JS in the page.

#### What are the steps to reproduce?
Load an MdCheckbox component. (I was unable to load the plunker template, so not sure if this is a simple reproduce)

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.2.4
Material: 2.0.0-beta.7
OS: Windows 10
TypeScript: 2.4.0
Browsers: all

#### Is there anything else we should know?
This is only happening after upgrading to beta.7 - I checked the changelogs and couldn't see any reference to a breaking change or new dependency. If there's something that I may need to change, please inform

**Comment by crisbeto** [comment]
Can you post what your app looks like? I couldn't reproduce the issue with an app that only imports the  `MdCheckboxModule`.

**Comment by jelbourn** [comment]
Ensure that, if you're routing to a component, the module in which that component is declared is also imported into your app.

**Comment by j3ddesign** [comment]
Hmm, the problem went away by adding `MdCheckboxModule` a module higher in my route. Not sure why this became an issue crossing from beta.5 to beta.7 though, interesting problem.

Essentially I have a "dashboard" route, in which we lazily render components by resolving their component factories and injecting them using `viewContainerRef.createComponent()`. This is the first time I've run into a dependency issue with this process so I can't quite tell where deeper issue lies.

While it's resolved by adding MdCheckboxModule to the route, I'd rather not  as only about 5% of my lazy components use it.
I attempted to create a plunker to demo this but the official material plunker seems to be broken right now (I'll create a new issue for that)

**Comment by jelbourn** [comment]
@j3ddesign the issue is almost certainly that you've never imported `MdCheckboxModule` _anywhere_. Even if you dynamically create a component using its factory, the corresponding `NgModule`_must_ be imported into the app somewhere (this can also be lazy, but doing lazy module loading has its own set-up). 

The plunkers are a known issue, we're already investigating.
