### ISSUE TITLE
Material design input select and menu wrong behavior on iPhone 

### ISSUE THREAD

**Issue by salc** [angular/material2#5318]
#### Bug, feature request, or proposal:
Material design Input select or menu popup, on iphone do not block body scrolling when touch and swipe of page under.  

#### What is the expected behavior?
the popup should show after blocking page scrolling

#### What is the current behavior?
Input select and menu popup, on iphone do not block body scrolling with touch.  

#### What are the steps to reproduce?
with an iphone, using safari browser, navigate to 
https://material.angular.io/components/select/overview 
open the favorite food select that is on the top of the page, then with finger, touch and swipe the page under the select without touching the select itself.

#### What is the use-case or motivation for changing an existing behavior?
on mac safari, android chrome and windows chrome, it works like it should. It blocks page scrolling when popup is displayed

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
versione on material.angular.io website.

#### Is there anything else we should know?

this is a video of what happens.
[videoplayback.zip](https://github.com/angular/material2/files/1096573/videoplayback.zip)

**Comment by donroyco** [comment]
What iOS version and Safari version are you using?

**Comment by salc** [comment]
From Safari:
UserAgent:Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1

I also found out that chrome for iphone has the same problem.

From Chrome:
UserAgent:Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/59.0.3071.102 Mobile/14F89 Safari/602.1

**Comment by josephperrott** [comment]
Fixed by #5134
