### ISSUE TITLE
md-select not re-setting selected value after selecting new option

### ISSUE THREAD

**Issue by limpep** [angular/material2#5322]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I am trying to reset the selected option from a `md-select` . Initially the default option is set to `2`, however when I select a new value I am trying to reset the selected option to a different value for example here is my md-select

```
<md-select name="teamSize" [(ngModel)]="selectedTeamSize" (change)="updateSubscriptionOnKeyUp(company)">
        <md-option *ngFor="let sizes of teamSizes" [value]="sizes.value">{{sizes.displayValue}}</md-option>
      </md-select>
```
on my `updateSubscriptionOnKeyUp` function

```
if(company.subscriptions[0].type === "Free") {
      if(this.selectedTeamSize > 2) {
        this.selectedTeamSize = 2;
      }
    }
```
but the value `this.selectedTeamSize` is not being set to `2`, it remains my selected value, not sure what I am doing wrong

#### What is the current behavior?
Selected value is set rather than the new reset value

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cli: 1.1.2
node: 8.1.2
os: darwin x64
@angular/animations: 4.2.3
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/core: 4.2.3
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/material: 2.0.0-beta.6-0aaeb69
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.1.2
@angular/compiler-cli: 4.2.3

**Comment by donroyco** [comment]
@limpep Have you tried using the latest version of beta?

**Comment by limpep** [comment]
@donroyco I'm using "@angular/material": "git+https://github.com/angular/material2-builds.git",

**Comment by donroyco** [comment]
@limpep It's stated otherwise in your list:
> @angular/material: 2.0.0-beta.6-0aaeb69

[beta7](https://github.com/angular/material2/compare/2.0.0-beta.6...2.0.0-beta.7) is out.

**Comment by limpep** [comment]
@donroyco Just upgraded, no luck same issue 

@angular/cli: 1.1.3
node: 8.1.2
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4

**Comment by willshowell** [comment]
@limpep any errors in the console? Specifically something like "change after checked"?

1. Try splitting up your two-way binding so you have `[ngModel]=...` and `(ngModelChange)=...`
2. Plunker reproduction?

**Comment by julianobrasil** [comment]
Have you try surrounding `updateSubscriptionOnKeyUp ` code with a setTimeout?

**Comment by josephperrott** [comment]
Can you provide a reproduction in a plunker?  I was not able to reproduce this myself but might be misunderstanding what you had occuring.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
