### ISSUE TITLE
No implementation of md-prevent-menu-close in material2

### ISSUE THREAD

**Issue by adarowiec** [angular/material2#5323]
#### Bug, feature request, or proposal:
Feature request: migrate/implement attribute md-prevent-menu-close from AngularJS to material2.

#### What is the expected behavior?
When user uses md-prevent-menu-close attribute, after choosing an item - menu should not close.

#### What is the current behavior?
There is no md-prevent-menu-close and when user clicks menu items, the menu disappears; event.stopPropagation() or event.preventDefault do not work.

**Comment by ocarreterom** [comment]
See https://github.com/angular/material2/pull/4842

**Comment by crisbeto** [comment]
Won't be done due to accessibility concerns. See https://github.com/angular/material2/pull/4842#issuecomment-305031863.
