### ISSUE TITLE
Why support is cut for angular2 ?

### ISSUE THREAD

**Issue by ch-hristov** [angular/material2#5327]
#### Bug, feature request, or proposal:
In release 2.0.3 BETA you decided to depend on Angular 4. But angular 4 is in beta, so it makes it impossible for angular 2 users to use your code. What is the logic behind this decision?

**Comment by rafaelss95** [comment]
Angular 4 is in Beta? Huh?

**Comment by ch-hristov** [comment]
( at least it was last time I checked, and it seems to be major release so uhh.. 2 major releases in a few months)

**Comment by rafaelss95** [comment]
Angular is currently on 4.2.4 stable.

**Comment by leo6104** [comment]
Angular Material last release version is 2.0.0-beta7 and angular4 last release version is 4.2.4.

**Comment by ch-hristov** [comment]
coming from .net world major releases actually require lots of time 📦  sorry

**Comment by rafaelss95** [comment]
Angular adopts SemVer, major releases are (supposed to be) released every six months.

For more: http://angularjs.blogspot.com.br/2016/10/versioning-and-releasing-angular.html?m=1
