### ISSUE TITLE
Packages don't contain scss files

### ISSUE THREAD

**Issue by VFedyk** [angular/material2#533]
I have installed 2.0.0-alpha-5 and there is no SCSS files. What was the reason of doing that?

**Comment by kreed-rmn** [comment]
I found the reason for this was node-sass hadn't been recompiled. 

`npm rebuild node-sass` fixed it for me.

**Comment by VFedyk** [comment]
It is how package looks for me now:
![list-2 0 0-alpha 5 tgz _126](https://cloud.githubusercontent.com/assets/489576/15579029/8ae007ee-236b-11e6-8218-d6a366ce2083.png)

**Comment by VFedyk** [comment]
The same list package but earlier version:
![list-2 0 0-alpha 4 1 tgz _127](https://cloud.githubusercontent.com/assets/489576/15579162/17f64026-236c-11e6-868d-9b4b0e46114b.png)

**Comment by Delagen** [comment]
I am waiting for theming solution. Current implementation so ugly, in state of npm is even impossible. Sad that no any issue with plan for distribution with theme support and bundling into single css file in case that shadow css isn.t the best solution in some cases

**Comment by zigzag95** [comment]
I added an issue but Mister @jelbourn closed it without any explanation.

**Comment by jelbourn** [comment]
The missing scss files wasn't intentional; it was likely due to changes in the angular-cli. We'll look into the problem.

As far as a real theming API: it will come eventually, but in the short term we're focused on having components _to_ theme 😃. Generally issues asking "When will X be done?" will just be closed.

**Comment by zigzag95** [comment]
I just asked to add a milestone for theming. To know if we workaround it or wait for it.

**Comment by VFedyk** [comment]
@jelbourn, maybe it wasn't intentional but they were in at least two last versions and we built project relying on these files. And then, suddenly, they disappeared. Is it possible to rebuild recent packages?

**Comment by jelbourn** [comment]
Just published an alpha.5-2 which contains the scss source.

**Comment by TheCaptainDate** [comment]
@jelbourn 
Still broken.
There is css and scss files now with same name, so @import inside material2 scss files don't know which file should be imported, and returns an error. 
I think this can be fixed if you put extensions in material2 scss files, or remove all css files from package.

**Comment by Delagen** [comment]
While no any distribution policy It is fun. Because all styles are embedded in source ((

**Comment by ddjonline** [comment]
What is the recommended way to handle the scss and css in the same directories with the node-sass option (I know the angular-cli "just works" but that isn't an option for some)?
