### ISSUE TITLE
Add support on snackbar to spawn at different screen positions.

### ISSUE THREAD

**Issue by Goodwine** [angular/material2#5334]
#### Bug, feature request, or proposal:
Add support on snackbar to spawn at different screen positions.

#### What is the expected behavior?

1. Snackbar should have a config to spawn from a given position:
 * Top vs Bottom, defaults to Bottom.
 * Left vs Right vs Center, defaults to Center. The animation depends on this value too.
2. If the snackbar is too wide, snap it to the bottom and make it large (like the current behavior) regardless of where the snackbar spawned.

#### What is the current behavior?
It only spawns at the bottom.

#### What is the use-case or motivation for changing an existing behavior?
Sometimes we want the snackbar to spawn from either left or right from the bottom. This behavior already exists on the material library for Angular JS https://material.angularjs.org/latest/demo/toast
Although it doesn't spawn from the bottom or top exclusively, it only spawns from a corner.

**Comment by jelbourn** [comment]
Tracked by #3577 and has an open PR.
