### ISSUE TITLE
Autocomplete: Select active suggestion on tabout

### ISSUE THREAD

**Issue by tholam** [angular/material2#5335]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
If one of the options is active when the user tabs out, select that option to autocomplete.

#### What is the current behavior?
When a user presses tab it just closes the autocomplete panel and nothing happens to the input

#### What is the use-case or motivation for changing an existing behavior?
Nicer UX when using autocomplete.  

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.7

#### Is there anything else we should know?
This is doable right now with keypress.Tab on the input and using the MdAutocomplete's keyManager but it would be nice to have it built in.  If this was added in addition to automatically having the top suggested active using the autopicker would feel a lot less clunky.

**Comment by willshowell** [comment]
Duplicate of PR https://github.com/angular/material2/pull/4401 which was closed for accessibility concerns. The proposed alternative is to have the ability to configure selection to follow focus changes. That issue is at https://github.com/angular/material2/issues/4951

**Comment by tholam** [comment]
My bad didn't see those other issues when i searched for ones related to autocomplete

**Comment by thw0rted** [comment]
For those still looking to implement select on tab-out, you can use [this snippet](https://github.com/angular/material2/issues/3334#issuecomment-335792985) I adapted from Will's example in that same thread.

I would be open to suggestions how to prevent or modify this behavior for screen-reader users, but strongly believe that for non-screen-readers, failing to select on tab is unintuitive and inconsistent with other similar list presentations (native select components, etc).
