### ISSUE TITLE
bug(Datepicker): datepicker doesn't close if you click on previous selected date

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#5349]
#### Bug, feature request, or proposal:

Bug/Request (I think I've seen a similar issue around, but I couldn't find it)

#### What is the expected behavior?

The datepicker should close if you click on a previous selected date

#### What is the current behavior?

The datepicker doesn't close if you click on a previous selected date

#### What are the steps to reproduce?

1 - Open the calendar, select a date
2 - Reopen the calendar and try to select the same date

Plunker: http://plnkr.co/edit/shFewF?p=preview

#### What is the use-case or motivation for changing an existing behavior?

It's not unusual that a user opens the calendar, takes a quick look at it and realizes that the date he wants to select is already selected. In this situation, the calendar panel should close if he clicks again on the already selected date.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cli: 1.1.3
node: 6.10.3
os: win32 x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/compiler-cli: 4.2.4
@angular/core: 4.2.4
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/platform-server: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/language-service: 4.2.4

Google Chrome

**Comment by hwesol13** [comment]
@mmalerba is there any progres in this issue? I'm just wondering if i could fix that but i don't want to duplicate your work (if you already did any).

**Comment by mmalerba** [comment]
@hwesol13 I haven't gotten a chance yet, feel free to create a PR and mention me

**Comment by hwesol13** [comment]
Ok so i'll fix it than :)

**Comment by mmalerba** [comment]
@hwesol13 are you still planning on creating a PR for this?

**Comment by lukaszzdanikowski** [comment]
Hi @mmalerba, @hwesol13 is currently on holidays but he should submit PR next week

**Comment by julianobrasil** [comment]
Any news on this?

**Comment by julianobrasil** [comment]
Any news about this?

@hwesol13 @mmalerba

**Comment by julianobrasil** [comment]
Oh, I found it: #6323
