### ISSUE TITLE
MdInputContainer not wrapping with fxLayoutWrap

### ISSUE THREAD

**Issue by sherrim** [angular/material2#5352]
Using Angular 4.2.4, Material 2.0.0-beta.7, and flex-layout 2.0.0-rc.1 in Chrome, it seems that md-input-container is ignoring fxLayoutWrap.  I created a plunker that shows wrapping working for div and even md-checkbox, but not for md-input-container.  The input that should be wrapped is not showing at all.

https://plnkr.co/edit/goT9Y2LNbwSv7TwfG1a0?p=preview

**Comment by julianobrasil** [comment]
The plunker is throwing an error to the console saying it misses **`BrowserAnimationsModule`**. Maybe this is the problem. Try adding it.

**Comment by sherrim** [comment]
I got rid of that error, but it didn't fix anything.

**Comment by julianobrasil** [comment]
Now I see it.

**Comment by julianobrasil** [comment]
Specifing a value to fxFlex seems to get it back to life. Try fxFlex="nogrow" instead of just fxFlex. There's a possibly similar issue at FlexLayout repo: https://github.com/angular/flex-layout/issues/314

**Comment by sherrim** [comment]
Thanks! I'm able to get things laying out as needed with that tip.
