### ISSUE TITLE
material.angular.io have a bug when showing source code

### ISSUE THREAD

**Issue by maxime1992** [angular/material2#5359]
#### Bug, feature request, or proposal:
Bug (on the doc site)

#### What is the expected behavior?
Clicking on the button to show code should show the code. Not toggle the theme : 
(before I click on the button to show the code)
![image](https://user-images.githubusercontent.com/4950209/27517719-3c2455fe-59d1-11e7-9f56-6e31198250e8.png)

(after clicking on the button)
![image](https://user-images.githubusercontent.com/4950209/27517723-528699ec-59d1-11e7-964b-44aea2bb11b5.png)

#### What are the steps to reproduce?
Go to https://material.angular.io/components/input/overview
Search for the example of prefixes/suffixes
Click on the button to show the code 
![image](https://user-images.githubusercontent.com/4950209/27517740-9ef018ee-59d1-11e7-8925-128a512721e7.png)

I've only seen this (weird) behavior on this example and the others seems fine.

**Comment by civaste** [comment]
The same for the example about input errors (on the same page).

**Comment by tinayuangao** [comment]
It's fixed.
