### ISSUE TITLE
MdSnackbarRef injection

### ISSUE THREAD

**Issue by jurafa** [angular/material2#5374]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
*MdSnackbarRef* object should be injected into component rendered using *MdSnackbar.openFromComponent* as it is in *MdDialog* component.

#### What is the current behavior?
Trying to inject *MdSnackbarRef* object causes *No provider for MdSnackBarRef!* exception.

#### What are the steps to reproduce?
https://embed.plnkr.co/R7Uje3/

#### What is the use-case or motivation for changing an existing behavior?
Component used as a template should be able to manipulate with the snackbar component. For example, the template might contain a close button that must close the snackbar itself.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
reported in @angular/material 2.0.0-beta.7

**Comment by crisbeto** [comment]
Could you post this as a comment to https://github.com/angular/material2/issues/5371? I'll do them both together since they're very much related.

**Comment by jurafa** [comment]
relates to #5371
