### ISSUE TITLE
material 2 custom build of a subset of components

### ISSUE THREAD

**Issue by david-gang** [angular/material2#5375]
#### Bug, feature request, or proposal:

Feature request
#### What is the expected behavior?
Create a custom build of the components which i am interested

#### What is the current behavior?
Just possible to rely on tree shaking. This does not work properly.  Furthermore there is no tree shaking in the css level

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Is there anything else we should know?

I would appreciate if there is a workaround for this.

**Comment by jelbourn** [comment]
Tracked via #4137 

As for the CSS, that does capture the per-component styles. For theming, see the [theming guide](https://material.angular.io/guide/theming)'s section on "Theming only certain components"
