### ISSUE TITLE
Error building a custom theme

### ISSUE THREAD

**Issue by miniskulljob** [angular/material2#5377]
#### Bug, feature request, or proposal:
Building a custom theme with angular-cli fails.

#### What is the expected behavior?
Custom theme built from the scss file made with the [theming guide](https://material.angular.io/guide/theming) steps.

#### What is the current behavior?
The building process fails when it tries to build the theme.

#### What are the steps to reproduce?
Just copy-paste the code in the [theming guide](https://material.angular.io/guide/theming) and build.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.4, Material 2.0.0-beta.7, Windows 10, TypeScript 2.3.4

#### Is there anything else we should know?
The console outputs this error:
> ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/tendeens.scss
Module build failed:
undefined
            ^
      Argument `$map` of `map-get($map, $key)` must be a map
Backtrace:
        node_modules/@angular/material/_theming.scss:1070, in function `map-get`
        node_modules/@angular/material/_theming.scss:1070, in function `mat-palette`
        stdin:12
      in Z:\customers\tendeens\webapp\node_modules\@angular\material\_theming.scss (line 1070, column 14)
 @ ./src/tendeens.scss 4:14-191
 @ multi ./src/tendeens.scss ./src/styles.css

**Comment by willshowell** [comment]
Can you show `/src/tendeens.scss`? I ran through the theming guide just a few days ago with no issues, but there have been a couple of misunderstandings with it so maybe something is still unclear.

**Comment by miniskulljob** [comment]
@willshowell Hi! The comment is just a copy-paste from the theming guide:
> @import '~@angular/material/theming';
// Plus imports for other components in your app.
// Include the common styles for Angular Material. We include this here so that you only
// have to load a single css file for Angular Material in your app.
// Be sure that you only ever include this mixin once!
@include mat-core();
// Define the palettes for your theme using the Material Design palettes available in palette.scss
// (imported above). For each palette, you can optionally specify a default, lighter, and darker
// hue.
$tendeens-primary: mat-palette('#00dcac');
$tendeens-accent:  mat-palette('#ff825f');
// The warn palette is optional (defaults to red).
$tendeens-warn:    mat-palette($mat-red);
// Create the theme object (a Sass map containing all of the palettes).
$tendeens-theme: mat-light-theme($tendeens-primary, $tendeens-accent, $tendeens-warn);
// Include theme styles for core and each component used in your app.
// Alternatively, you can import and @include the theme mixins for each component
// that you are using.
@include angular-material-theme($tendeens-theme);

**Comment by miniskulljob** [comment]
Ok, there's no error, it was my mistake. I thought that the mixin `mat-palette` would generate the palette of colors from one hex/rgb/hsl color, but it doesn't work like that... I looked at the theming file to get a base palette and modify it so I could use my colors. Pretty strightforward:
> $tendeens-green: (
  50: #e6fffa,
  100: #9affe9,
  200: #62ffdd,
  300: #1affcd,
  400: #00fbc4,
  500: #00dcac,
  600: #00bd94,
  700: #009f7c,
  800: #008064,
  900: #00624c,
  A100: #e6fffa,
  A200: #9affe9,
  A400: #00fbc4,
  A700: #009f7c,
  contrast: (
    50: $black-87-opacity,
    100: $black-87-opacity,
    200: $black-87-opacity,
    300: $black-87-opacity,
    400: $black-87-opacity,
    500: white,
    600: white,
    700: white,
    800: $white-87-opacity,
    900: $white-87-opacity,
    A100: $black-87-opacity,
    A200: $black-87-opacity,
    A400: $black-87-opacity,
    A700: $black-87-opacity,
  )
);

I'll close it since there's no issue here. Thanks and sorry for the inconvinience.

**Comment by nithinshiriya** [comment]
@miniskulljob Do you have any sample code for using sample custom color as the theme .
