### ISSUE TITLE
proposal: data-table cdk-header-cell should not scroll with scroll bar

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#5388]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
cdk-header-cel should not scroll with scroll bar

#### What is the current behavior?
cdk-header-cel scroll with scroll bar

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
material2\src\demo-app\data-table

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/material@2.0.0-beta.7-f73cc97

**Comment by jelbourn** [comment]
Support for sticky heads will shortly follow after the initial release.

**Comment by riankol** [comment]
@jelbourn Is there any news on this topic yet? When do you aspect this sticky headers to be released?

**Comment by willshowell** [comment]
@riankol tracking is at https://github.com/angular/material2/issues/5885

**Comment by irowbin** [comment]
I guess the changes will be released in next week? @jelbourn Very excited to see the changes of long waited `md-table/cdk` data table.
