### ISSUE TITLE
Inject content and actions into MdDialog

### ISSUE THREAD

**Issue by e11en** [angular/material2#5390]
#### Bug, feature request, or proposal:
feature request: The injecting of content and actions for a MdDialog that has the same process as adding a 'normal' action for example.

#### What is the expected behavior?
For example a button stays like this `<button md-raised-button="" color="primary" md-dialog-close="save">Save</button>` when inspecting the page.

#### What is the current behavior?
For example it should have all the extra ng attributes  `<button _ngcontent-c2="" class="mat-raised-button mat-primary" color="primary" md-raised-button="" ng-reflect-color="primary">
	<span class="mat-button-wrapper">Open</span>
	<div class="mat-button-ripple mat-ripple" md-ripple="" ng-reflect-trigger="[object HTMLButtonElement]" ng-reflect-centered="false" ng-reflect-disabled="false"></div> 
	<div class="mat-button-focus-overlay"></div> 
</button>`

#### What are the steps to reproduce?
Using a pipe to set the text to SafeHtml and then building the actual form to inject into the innerHTML of both md-dialog-content and md-dialog-action. See [http://plnkr.co/edit/IqTaoL?p=preview](http://plnkr.co/edit/IqTaoL?p=preview)

#### What is the use-case or motivation for changing an existing behavior?
I want to dynamically setup a dialog.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All for what I've found

#### Is there anything else we should know?
Nope

**Comment by willshowell** [comment]
https://stackoverflow.com/a/40474494/4811678
https://stackoverflow.com/a/36408622/4811678

**Comment by e11en** [comment]
Ok, so I need to change my whole approach on this then. Thanks for the info!
