### ISSUE TITLE
moduleId: module.id is undefined if material 2 alpha.5 is loaded as umd instead of system.js

### ISSUE THREAD

**Issue by gregbown** [angular/material2#540]
I am curious, what is the purpose of having this moduleId property on every component as of alpha.5?

It appears that module.id is the path to the application component at run time if the application is loaded via system.js.   Is there any intention of supporting other use cases such as loading material in a umd fashion?

I am loading the modules in a umd format, therefore module.id is undefined.  My only solution was to comment out //moduleId: module.id in the components.

Thank you
Greg

**Comment by jelbourn** [comment]
Publishing umd bundles for the components is on our to-do list. 

@hansl: is this something that falls under the CLI umbrella or something we should do on our own?

**Comment by hansl** [comment]
We'll have to do it on our own.

@gregbown: `module.id` allows us to put the templates as relative paths. Since the templates are inlined in Material before publishing, it's safe to remove.

@jelbourn: Maybe we can just remove the `module.id` prior to publishing.

**Comment by gregbown** [comment]
Thank you for the clarification and prompt response @hansl & @jelbourn.
