### ISSUE TITLE
md-select with ngModel requires name attribute (hasValue error)

### ISSUE THREAD

**Issue by kmturley** [angular/material2#5402]
#### Bug, feature request, or proposal:
This is a bug with the documentation not matching expected behaviour

#### What is the expected behavior?
No error when copying guide code

#### What is the current behavior?
You get an error:
MdSelect.html:1 ERROR TypeError: Cannot read property 'hasValue' of undefined
at Object.View_MdSelect_0.co [as updateDirectives]

#### What are the steps to reproduce?
Following the guide, and copying example code should render without errors:
https://material.angular.io/components/select/overview
```
<md-select placeholder="State" [(ngModel)]="myState">
   <md-option *ngFor="let state of states" [value]="state.code">{{ state.name }}</md-option>
</md-select>
```

#### What is the use-case or motivation for changing an existing behavior?
The error is not useful, also modifying the example code, adding a name attribute to the md-select element fixes the issue:
```
<md-select placeholder="State" [(ngModel)]="myState" name="states">
   <md-option *ngFor="let state of states" [value]="state.code">{{ state.name }}</md-option>
</md-select>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.0.2
Angular Material 2.0.0-beta.7
MacOS 10.12.5
TypeScript 2.0.0
Chrome 59.0.3071.109

#### Is there anything else we should know?
The other example is correct here:
https://material.angular.io/components/select/examples

**Comment by willshowell** [comment]
It works fine [here](https://plnkr.co/edit/aIeAE8Wj1NDryc9hymng?p=preview) without the name attribute. Can you reveal more about your setup?


As a note: Typescript 2.2 is required (not sure if it's noted anywhere in the docs or is relevant here)

**Comment by crisbeto** [comment]
The name requirement on elements with `ngModel` comes from `@angular/forms` and only applies if the element is inside a form.

**Comment by kmturley** [comment]
ah yes, can that be outlined in the guide? I would guess it's a common use case

**Comment by crisbeto** [comment]
I'd say the message is helpful enough since it gives an example of how to solve the error. I'll submit a fix so Material doesn't throw any extra errors that may cause confusion.
