### ISSUE TITLE
cd.detectChanges breaks md-grid-list render

### ISSUE THREAD

**Issue by LarsMontanaro** [angular/material2#5407]
#### Bug, feature request, or proposal:
I'm creating an application in angular, and I have a component with an md-grid-list that is filled with data that is loaded in from a service (that pulls the data over a TCP IP socket connection). I have a Subject on my "videoHubService" service, which emits a signal every time data is received.

Additionally, I have a Subscription in my component that watches for these emitted strings, and, when received, runs a change detection loop (as the data has changed).

However, doing this breaks the render of the md-grid-list. Additionally, it is not a normal break -- the view renders fine, and the data change, but each of the grid-list-tiles in the grid-list has a function attached to it on right-click which opens an informative dialog, and the dialogs are broken - the information does not display and it cannot be closed until you click somewhere else. I can recreate this strange dialog behavior by initializing an md-grid-list without the necessary cols attribute, which leads me to believe that it is a symptom of the md-grid-list not rendering properly.

#### What is the expected behavior?
Dialog boxes should look like this:
![proper-dialog](https://user-images.githubusercontent.com/22302018/27664315-b89715d0-5c1b-11e7-89c3-93fe03fccbf9.PNG)

#### What is the current behavior?
Dialog boxes look like this:
![broken-dialog](https://user-images.githubusercontent.com/22302018/27664310-b1652e8c-5c1b-11e7-9b28-db567d0a205d.PNG)

ALSO, Paging forwards or backwards fixes the bug. If I render my component on page 0, then page forward then backwards, so I am back at page 0, the dialogs are no longer broken. However! Every time data is received by the changeWatcher, the dialogs break again.

My component is using onPush ChangeDetectionStrategy.

Finally, if I change cd.detectChanges to cd.markForCheck, the dialogs do not break. However, another action has to occur before the updates are seen, so this is not really a viable workaround.

#### What are the steps to reproduce?
I can try to recreate this behavior in a plunkr if my explanation is unclear.

#### Is there anything else we should know?
This is the code that inits my watcher:
```
public ngOnInit() : void
  {
    // changeWatcher is a Subscription to a Subject<string>
    this.changeWatcher = this.videoHubService.ChangeNotifier.subscribe((changeType : string) =>
    {
      // These are the two types of data that necessitate a change detection loop on this component
      if (changeType === "outputs" || changeType === "locks")
      {
        this.renderPages();
        this.cd.detectChanges();
      }
    });
    this.renderPages();
  } 
```

here is the renderPages function:
```
public renderPages() : void 
  {
    // Resetting pages array, so we can rebuild onto it
    this.pages.length = 0;

    let maxPage : number = this.configSettingsService.MaxPage;

    // Checking to verify that our outputLabels (which is an @Input() field in this component) is full of the data before attempting to render pages
    if (this.outputLabels.OutputLabelsData.length === this.videoHubService.VideoHub.Device.NumOutputs)
    {

      this.numPages = Math.ceil(this.outputLabels.OutputLabelsData.length / maxPage);

      for (let i : number = 0; i < this.numPages; i++)
      {
        let tempArr : Array<Label> = new Array<Label>();

        for (let n : number = (maxPage * i); n < (maxPage * i + maxPage); n++) 
        {
          if (this.outputLabels.OutputLabelsData[n] !== undefined)
          {
            tempArr.push(this.outputLabels.OutputLabelsData[n]);
          }
        }
        this.pages.push(tempArr);
      }
    }
  }
```

here is the component template:
```
<div class="list-container" [ngSwitch]="currentPage">

        <div *ngFor="let page of this.pages, let i = index" [attr.data-index]="i">

            <div *ngSwitchCase="i">

                <md-grid-list cols="6" rowHeight="3:1">

                    <md-grid-tile *ngFor="let label of page"> 

                        <button md-button (contextmenu)="displaySrc(label)" (click)="selectLabel(label)">

                            <md-icon *ngIf="destIsLocked(label)" class="lock-alert">lock</md-icon>

                            <label [label]="label"></label>

                        </button>

                    </md-grid-tile>

                </md-grid-list>

            </div>

        </div>

    </div>
```

**Comment by willshowell** [comment]
Since there's so much going on, I think plunker reproduction will be necessary in figuring out what's going on. Try breaking it down to the bare minimum required to reproduce the error.

**Comment by LarsMontanaro** [comment]
During my limited time, I've been unable to recreate it on Plunkr. I may get back to this, but it is very subtle and I can't seem to recreate it at the moment. My apologies!

**Comment by jelbourn** [comment]
Feel free to open a new issue with a reproduction
