### ISSUE TITLE
Can support persian calendar ?

### ISSUE THREAD

**Issue by saeedjalali1** [angular/material2#5410]
Hi , first thanks for awesome packages.
I see [material-ui](http://www.material-ui.com/#/components/date-picker) in React.js that fully support Persian calendar.
![image](https://user-images.githubusercontent.com/15178117/27673325-46e2e2c6-5cb5-11e7-9f23-aef6772215b1.png)

Is there a way to implement the Persian calendar for angular ?
Thanks for your attentions.

**Comment by julianobrasil** [comment]
Take a look at this plunker: http://plnkr.co/edit/uH6C87?p=preview

![image](https://user-images.githubusercontent.com/25405143/27681334-411f8ce2-5c95-11e7-9e8a-364833a3567f.png)

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
