### ISSUE TITLE
Angular Material 2-Overlay is not working for me

### ISSUE THREAD

**Issue by abhiphirke** [angular/material2#5411]
#### What is the expected behavior?
md-menu should show up as is shown in sample.

#### What is the current behavior?
the overlay that displays the menu is not displayed at appropriate location as shown in examples. It goes to the bottom of the screen after all main parts of my application. After I set following properties, it comes to its location.

```
position: absolute;
left: 0;
top: 0;
```

#### What are the steps to reproduce?
Picked simple menu sample from site and put it in my application.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 2.1, Material 2.0.0-alpha.8-2, Chrome

#### Is there anything else we should know?
I am using flex layout in my application.

Any help in making this work would be much appreciated.

**Comment by julianobrasil** [comment]
@abhiphirke ,  have been using the menus for a while with no pproblem. Your Material version is a pretty old one. Try updating it (it's already in beta.7).

**Comment by jelbourn** [comment]
Closing since this is an ancient version of the library.
