### ISSUE TITLE
Opening an MdDialog with a TemplateRef that uses `md-dialog-close` throws "no provider for MdDialogRef" 

### ISSUE THREAD

**Issue by alex321** [angular/material2#5412]
#### Proposal:
Provide `MdDialogRef` even when we pass a `TemplateRef`.

#### What is the current behaviour?
With the current setup if we pass a TemplateRef to MdDialog, there is no way to use  `md-dialog-close` directive as it throws `no provider for MdDialogRef` as it requires it. 

#### What is the expected behaviour?
It would be great if it works with a `TemplateRef` but if that's not possible, then could you please add a brief warning to the docs?

#### What are the steps to reproduce?
I can provide a plunkr if needed.

**Comment by crisbeto** [comment]
This is a known issue. It's because we can't set a custom injector on a template ref (since it's already instantiated). I've discussed a potential solution with @jelbourn, but haven't gotten around to implementing it yet.

**Comment by christophechevalier** [comment]
Hi,

Any news on that?

Thanks :)

**Comment by pitops** [comment]
Hello any news on this?
