### ISSUE TITLE
Dialog not working with SideNav?

### ISSUE THREAD

**Issue by dannyhchan** [angular/material2#5418]
#### Bug, feature request, or proposal:
Using a basic dialog with sidenav and the dialog is forced to the left side.  Please see attachment.

Wondering if the dialog is suppose to be outside of the md-sidenav-container.  My router-outlet is within the md-sidenav-container as I want to use the fullscreen side nav.

![dialogissue](https://user-images.githubusercontent.com/8468808/27697260-b7b719c0-5cc1-11e7-8c67-d3d51bca8c6e.PNG)

#### What is the expected behavior?
Should be centered.

#### What is the current behavior?
Part of the Dialog is on the left side showing full height.  Unable to see any content.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by donroyco** [comment]
Please provide a Plunker to reproduce the issue.

**Comment by agpreynolds** [comment]
did you add the dialog component to the entry components of you app.module?

**Comment by dannyhchan** [comment]
Here's an example.  
https://plnkr.co/edit/Yl4tlil4hBfkikiWg3qd?p=preview

**Comment by donroyco** [comment]
@dannyhchan When clicking, it gives a clear error message: 

> Error: No component factory found for DialogOverviewExampleDialog. Did you add it to @NgModule.entryComponents?

**Comment by dannyhchan** [comment]
Looks like it's working after adding it to entryComponents in main.ts.  Thank you!
