### ISSUE TITLE
Sidenav causes bizarre rendering behavior in IE11

### ISSUE THREAD

**Issue by nimble99** [angular/material2#5423]
#### Bug, feature request, or proposal:
When IE11 renders the SideNav, the screen basically fails to repaint, resulting in whatever was previously on the screen remaining frozen in the window. Sidenav makes application unusable

#### What is the expected behavior?
Sidenav should render correctly, and be usable.

#### What is the current behavior?
If the first view to display contains a side-nav, then the screen will render blank.
If not, then after re-navigating to a view that contains a sidenav, the screen will still be displaying the previous view, in a frozen 'snapshotted' state.
![angularbrokenie](https://user-images.githubusercontent.com/16373742/27708635-b3b2d916-5d6d-11e7-98c2-87e24e94d6fd.png)

#### What are the steps to reproduce?
Visit here, using IE11 on Windows 8.1

https://material.angular.io/components/sidenav/overview

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by crisbeto** [comment]
I think this might be happening on the docs site, because there was an error being thrown in the background. Might be worth re-checking once the changes from https://github.com/angular/material.angular.io/pull/203 are deployed.

**Comment by crisbeto** [comment]
@nimble99 can you give it another try? I'm unable to reproduce it with the latest release.

**Comment by mmalerba** [comment]
This issue appears to be resolved now
