### ISSUE TITLE
Md-input and md-select don't have a consistent underline height on 4k monitor

### ISSUE THREAD

**Issue by dobrevad** [angular/material2#5424]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Md-input-underline and md-select-underline have always the same height.

#### What is the current behavior?
Md-selects and md-inputs randomly get rendered with different underline height (~1px or ~2px).
Able to reproduce by composing a page with multiple inputs and/or selects.
Sometimes some controls will get the ticker underlining and sometimes others depending on the composition. No clear pattern though.

#### What are the steps to reproduce?
Plunker: http://plnkr.co/edit/zzRGZbOJEMqgy1GPVWkF?p=preview

In the plunker example the controls on the 1st row will get thicker underline than the ones on the 2nd although by inspecting the underline height it will always show ~1px.

Reproducible always on a 4k monitor on Gbuntu.
Not reproducible on smaller resolutions on Gbuntu or on Mac with retina display/4k monitor.

#### What is the use-case or motivation for changing an existing behavior?
Should be fixed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.1.2 and older
Material: 2.0.0-beta.7
TypeScript: 2.3.4
Browser: Tested with Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OS: Gbuntu

#### Is there anything else we should know?
By inspecting the input-underline/select-underline I find the following css rules that seem to toggle the thickness:
.mat-input-underline {
    bottom: 1.29688em;
}

Seems like a computed value that breaks the underline styling.

**Comment by jelbourn** [comment]
Tracked via #2124

**Comment by artchen** [comment]
Adding a min-height to `.mat-form-field-flex` solved it for me.
