### ISSUE TITLE
Datepicker switch between month/year views is jarring

### ISSUE THREAD

**Issue by alxhub** [angular/material2#5426]
#### Bug, feature request, or proposal:

Bug

#### What is the current behavior?

With the datepicker open on https://material.angular.io/components/datepicker/examples, clicking the "Month Year" handle at the top left of the overlay causes the overlay to switch into a year-only view that allows selection of the current month.

In this new view, the datepicker overlay changes size, and becomes a lot smaller. This would be okay, except it resizes itself _from the bottom_, staying attached to the picker control as overlays usually do. This causes the click handle to toggle between these modes to move down on the screen, and suddenly my mouse is no longer over the overlay.

This feels very jarring in terms of user interaction, when I click the handle to "collapse" the datepicker, I expect it to shrink from the bottom-up, not from the top-down. I should be able to click in the same spot and expand it into full view again.

@mmalerba as @jelbourn told me to mention you :)

**Comment by mmalerba** [comment]
As @naveedahmed1 mentioned in #5548 it is also jarring when the height changes after pressing prev/next buttons
