### ISSUE TITLE
Bug: Tooltip truncated in the left if the host element is near the left of the screen

### ISSUE THREAD

**Issue by zijianhuang** [angular/material2#5428]
#### Bug:

Tooltip displayed at the bottom truncated in the left if the host element is near the left of the screen

#### What is the expected behavior?

The left margin of the tooptip should be zero or slightly above zero, rather than currently negative.

#### What is the current behavior?

Characters in the left get truncated.

#### What are the steps to reproduce?

In https://material.angular.io/components/tooltip/examples with Plunker, make the selection the host get closer to the left through remove the left margin in the css, and the tooltip position set to the bottom, and also make the content of the tooltip slightly longer.

#### What is the use-case or motivation for changing an existing behavior?

There are some elements on the left need tooltip to be displayed at the bottom of the element.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material2 Beta 7. All browsers are affected.

**Comment by mmalerba** [comment]
@jelbourn will this be addressed by your work on overlay?

**Comment by jelbourn** [comment]
Tooltip should already use fallback positions to avoid this problem.

**Comment by RenaldasK** [comment]
Very annoying issue. Is there a workaround until this is fixed?
