### ISSUE TITLE
Make grid-tile expandable

### ISSUE THREAD

**Issue by antonmoiseev** [angular/material2#543]
Are there any plans to make grid tiles expandable to occupy the entire parent's space? Something like [Navigational transitions - Parent to child](https://www.google.com/design/spec/patterns/navigational-transitions.html#navigational-transitions-parent-to-child).

Regardless whether there are plans or not, could you give any suggestions how it can be implemented? Adjust CSS of an existing target grid tile, introduce a new element that will actually expand, wait till animation support is landed into Angular 2?

**Comment by jelbourn** [comment]
We don't have any plans for this in grid-list. You might try just animating the tile directly to go over the whole parent, but I'm not sure if anything the grid-list does will interfere with that.
