### ISSUE TITLE
md-select should have an optional 'deselect' value

### ISSUE THREAD

**Issue by tommueller** [angular/material2#5430]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
using md-selects as radio-button replacement I need a feature to deselect a value. We load data from the server and the user can update the data and might want to remove a set value from a form.

#### What is the current behavior?
on a md-select without `[multiple]="true"` it's not possible to remove a value after it has been selected once (you can change it, but not deselect)

**Comment by crisbeto** [comment]
This is supported already. If you have an option without a value or a `null` value, it will act as a reset. See: https://github.com/angular/material2/blob/master/src/demo-app/select/select-demo.html#L11

**Comment by tommueller** [comment]
Great, did not see this in the Docs. Thanks!
