### ISSUE TITLE
slider-toggle is not appearing properly

### ISSUE THREAD

**Issue by Rajasree37** [angular/material2#5431]
Hi

check box is appearing along with slider-toggel .i followed this link https://material.angular.io/guide/getting-started for angular material installation and usage purpose. but
it resuls.....slider toggel as shown in below image.
![ngmaterialui](https://user-images.githubusercontent.com/29772419/27730609-77b75bc8-5da7-11e7-884c-adad6a8df06b.PNG)

what I have to do...?
suggest me..

Thanks In Advance

**Comment by DevVersion** [comment]
You are missing a theme for your application.  Read more about theming [here](https://github.com/angular/material2/blob/master/guides/theming.md)

**Comment by Rajasree37** [comment]
Thanks @DevVersion ,
but added this link
 <link href="../node_modules/@angular/material/prebuilt-themes/indigo-pink.css" rel="stylesheet">  in index.html file.
Still it gives same result.

Thanks
Rajasree

**Comment by m98** [comment]
@Rajasree37  If you used Angular CLI, please try to insert the link to css file by using the file in the root directory of your project named `.angular.cli.json` and under the style you should have something like this:

```
 "styles": [
      "../node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
   ...
   ]
```

**Comment by Rajasree37** [comment]
Thank you so much m98 it works
