### ISSUE TITLE
The plunker template is not working

### ISSUE THREAD

**Issue by m98** [angular/material2#5434]
This is a bug report on the Plunker template.

#### What is the expected behavior?
I am trying to run the Plunker template which is linked from the repository README file (http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview), but it stays in the loading state and when I open console, I get errors which say 

> Failed to load resource: the server responded with a status of 404 (Not Found) emmet.js
> Failed to load resource: the server responded with a status of 403 (Forbidden) gpt.js 
> Failed to load resource: net::ERR_CONNECTION_RESET oct.js 
> .... (more errors)

https://i.stack.imgur.com/vUhRi.png

Plunker link(again):
http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Fedora 25, Chrome latest version, and Angular and Material version is defined in Plunker.

_I tried to open the Plunker template even using VPN because I was thinking maybe some CDN links are blocked in my location because of sanctions, but it was not the case._

**Comment by DevVersion** [comment]
Thanks. Just fixed it. Let me know if you see something else.

**Comment by m98** [comment]
@DevVersion Thanks, can you please let me know what was the problem? _(just for learning purposes)_

**Comment by DevVersion** [comment]
@m98 Sure. The problem was that we yesterday moved a few modules to a new package called `@angular/cdk`.

The Plunker template incorrectly imported those modules from `@angular/material` which caused an exception.
