### ISSUE TITLE
Tabs problem with Right To Left 

### ISSUE THREAD

**Issue by m98** [angular/material2#5436]
I am reporting two things that sound like a bug for me, but your experience can correct me if I'm wrong.

1. Using the `dir="rtl"` attribute for `<html>` tag tells Material that the website is right to left. I use Material tabs and the direction, animation and arrow icons are not woking correctly for the right to left.
Here is the screenshot:
![Screenshot](https://i.stack.imgur.com/LgJib.png)

2. Plunker behavior is different than the real app! 
Take a look at the screenshot above and you should notice the problem with the RTL, I tried to made a Plunker to show the problem, but Plunker was showing it correctly, then I created a new empty project because I was seeing the RTL problem in Tabs in my real project and it was odd that how Plunker is showing it without any problem! 

I deployed the newly made Angular project into GitHub pages to present the bug, I was thinking maybe Angular AOT compiler is making the problem but I'm not sure and I also get the same problem when I just use `ng serve`

Note: I use [Bootstrap-rtl](https://github.com/morteza/bootstrap-rtl) for the RTL project, then I added it to the project. (both Plunker and real project have it)

Real app example: [Live](https://m98.github.io/materialrtl-test/dist/) | [Source](https://github.com/m98/materialrtl-test)
Plunker demo: [Live](http://plnkr.co/edit/K5rSAPH6Vm0SY0opw0d4?p=preview)

They both are almost the same, and they use same libraries but somehow Plunker works and the real app is not working!

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
@angular/cli: 1.1.0
node: 6.10.3
os: linux x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.1.0
@angular/compiler-cli: 4.2.5
@angular/language-service: 4.2.5

```

#### Is there anything else we should know?
I found a question on StackOverflow which was odd for me and maybe that gives you insight into what's happening! [The question](https://stackoverflow.com/questions/44829767/why-angular-4-build-change-html-direction)

_It's also possible the problem be from the different version of the project, but I'm using the all stable versions of Angular and dependencies. Not sure about the Plunker template provided by Material itself._

@EladBezalel you know about RTL problems and could you please take a look?

**Comment by m98** [comment]
@jelbourn, @DevVersion & @crisbeto  Any idea about this issue? 
I need to use tabs, but it's not working as expected, and I'm not sure if it's my problem or it's a real bug that happens while real compiling using AOT.
If it's a bug, I would be grateful if you let me solve it with your guidance!

(excuse me for mentioning you)

**Comment by EladBezalel** [comment]
@m98 rtl on `html` or `body` would be supported in the next release, in the meantime you can put inside your `app-root` `dir=rtl` :) hope that helps

**Comment by m98** [comment]
@EladBezalel  Thanks

I use `<router-outlet></router-outlet>` and I set `dir="rtl"` for it, but it did not work, I also set the for the `<app-myComponent>` that I used the tabs there...
About the `beta7`, I did not know it's not the latest version.

Could you please guide me?
When will the master build be released?

**Comment by EladBezalel** [comment]
I assume `Beta 8` would be released sometimes soon, just wait for that release, 
Not sure about the `router-outlet` i'd go to your container div or something

**Comment by m98** [comment]
@EladBezalel But actually I tried that, I added the `dir="rtl"` to the `<md-tab-group>` or it's parent! 

Please take a look at the [live demo](https://m98.github.io/materialrtl-test/dist/) and you can fork and test it

**Comment by EladBezalel** [comment]
@m98 can't see any `dir=rtl` to `md-tab-group` i'd go with `dir=rtl` on `app-tabs` or just install `material2-builds
