### ISSUE TITLE
Can't create a button-toggle that's styled like the documented example

### ISSUE THREAD

**Issue by hblieb** [angular/material2#5439]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-button-toggle styling should look like your example, like a raised button with 36px height. See docs https://material.angular.io/components/button-toggle/overview.

#### What is the current behavior?
Styling is flat with no button outlines or shadows. Your own plunk looks incorrect. I'm getting the same incorrect result: flat with no button-like styling

#### What are the steps to reproduce?
See your own plunk at https://plnkr.co/edit/ysbpRH6SCyWfdQXFeCt6?p=preview. The styling in that plunk doesn't match the documentation.

#### What is the use-case or motivation for changing an existing behavior?
It should be possible to make Button Toggles that look like Buttons.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current version in use at https://material.angular.io/components/button-toggle/overview

**Comment by willshowell** [comment]
This was fixed in #5121, but the plunker is using beta-7 while apparently the docs example is showing from a more recent build.

Here is a plunker using the latest master build:
https://plnkr.co/edit/DgrzRHLYkfq4WDnhCUag?p=preview
