### ISSUE TITLE
checkbox: change event emits [Event] instead of boolean

### ISSUE THREAD

**Issue by DevVersion** [angular/material2#544]
Sometimes, when triggering the change event on the `input`, by clicking on it, the change output will emit the actual event object, instead of the correct boolean.
- https://developer.mozilla.org/de/docs/Web/Events/change

Already working on a PR, which includes some tests and fixes it.

Sample test (without fix)
![image](https://cloud.githubusercontent.com/assets/4987015/15611338/359aa194-242a-11e6-8e8d-24769177369a.png)

After searching in the Angular Repository I found the right issue
- https://github.com/angular/angular/issues/4059

**Comment by jelbourn** [comment]
@DevVersion we actually want the checkbox to fire something like an `MdCheckboxChange` event if you wanted to PR that instead.
