### ISSUE TITLE
Cannot find module '@angular/platform-browser/animations'

### ISSUE THREAD

**Issue by SlimenTN** [angular/material2#5457]
I have followed the official [documentation](https://material.angular.io/guide/getting-started) ro install material design for angular2, but when I import `BrowserAnimationsModule`:
`import {BrowserAnimationsModule} from '@angular/platform-browser/animations';`
I get this error:
`Cannot find module '@angular/platform-browser/animations'`
this is my package.json file:
```javascript
"dependencies": {
    "@angular/animations": "^4.2.5",
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/material": "^2.0.0-beta.7",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  },
```

**Comment by m98** [comment]
You need to update your `@angular/platform-browser

**Comment by hamedbaatour** [comment]
this is not related to a bug as I have answered your question in depth on StackOverflow over [here](https://stackoverflow.com/questions/44858917/angular2-cant-enable-material-design/44860169#44860169). @DevVersion issue to be closed.
