### ISSUE TITLE
Datepicker documentation example broken/inconsistent

### ISSUE THREAD

**Issue by naktinis** [angular/material2#5461]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

The datepicker component in the [official example](https://material.angular.io/components/datepicker/examples) should be able to parse the selected date consistently.

#### What is the current behavior?

Depending on the browser's locale (mine is "en-gb") it sometimes mixes up month and day components. E.g. you select "June 1", then open selector again and now it shows "January 6".

#### What are the steps to reproduce?

1. Configure your browser so that `new Date().toLocaleString()` returns a string in this format `01/07/2017, 14:00:00` (day first).
1. Open the [official example](https://material.angular.io/components/datepicker/examples).
1. Select "June 1"
1. Open selector again, note that the date became "January 6"

#### What is the use-case or motivation for changing an existing behavior?

I want to make it clear that this issue is specifically about fixing the documentation/example so it is consistent independent of the browser configuration one uses. I know that there are similar issues where people have problems with their apps, but this is specifically about fixing the documentation.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Tested on Firefox 54.0 with whatever version of Angular/Material that is used in the official documentation.

**Comment by crisbeto** [comment]
This should be resolved once https://github.com/angular/material2/pull/5419 gets in.

**Comment by mmalerba** [comment]
The `NativeDateAdapter` doesn't work well for locales other than `en-US`. I recommend using a custom `DateAdapter` or waiting for Angular Material's official `MomentDateAdapter` which will use Moment.js for parsing and formatting dates.
