### ISSUE TITLE
md-dialog-content is not scrollable

### ISSUE THREAD

**Issue by azarus** [angular/material2#5465]
#### Bug, feature request, or proposal:
the documentation says: Primary scrollable content of the dialog.
While it is not scrollable at all?

#### What is the expected behavior?
Scroll

#### What is the current behavior?
overflowing the screen without scrolling:
https://i.imgur.com/epPQEHd.png

#### What are the steps to reproduce?
Make a big dialog.

#### What is the use-case or motivation for changing an existing behavior?
Would be nice to work as described in the documentation.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular: ^4.0.0",
@angular/material: ^2.0.0-beta.7

#### Is there anything else we should know?
no

**Comment by azarus** [comment]
Can we please update the documentation at least?
".mat-dialog-content" is required to have scrolling on the dialog content.

**Comment by crisbeto** [comment]
You're supposed to use `md-dialog-content` as an element:

```html
<md-dialog-content>
your content goes here
</md-dialog-content>
```

**Comment by azarus** [comment]
I have no scrolling without additionally putting .mat-dialog-content there

**Comment by azarus** [comment]
Sorry about opening the issue, it was resolved after getting rid of this lib https://github.com/Teradata/covalent, (this lib sucks anyways)

**Comment by Enngage** [comment]
I have the latest versions of both **Angular material** + **Teradata** Covalent and have none issues with this. I do experience same issue only if I omit the `<md-dialog-content>content</md-dialog-content>` in my code.

**Comment by crowmagnumb** [comment]
I am on the latest angular-material2 beta-10 and I have to have the .mat-dialog-content class on the md-dialog-content element or I don't get the scrollbars.

**Comment by anhhnguyen206** [comment]
I fixed it by putting my scrollable content inside <mat-dialog-content></mat-dialog-content>.
