### ISSUE TITLE
feat(md-icon): better error message for incorrect font icon name

### ISSUE THREAD

**Issue by benb7760** [angular/material2#5467]
#### What is the expected behavior?
md-icon using fonts as described in the Getting Started guide should display icon

#### What is the current behavior?
It does not. I see a small artifact hovering far to the right of where i expect the icon to be

#### What are the steps to reproduce?

http://plnkr.co/edit/R7Jy1qM5YgC32DZUifs1?p=preview

#### What is the use-case or motivation for changing an existing behavior?
This may not be a bug - it may instead be something incorrect in the documentation?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2.0.0-beta.7 and latest material2-builds. Tested on Chrome and IE11

![image](https://user-images.githubusercontent.com/497125/27765644-1a207d10-5eaf-11e7-820b-e4e6483865e7.png)

**Comment by benb7760** [comment]
It seems I had somehow used an incorrect name 'thumbs-up'.

However, should there be some form of error/warning instead of displaying that strange graphical glitch?

**Comment by donroyco** [comment]
> However, should there be some form of error/warning instead of displaying that strange graphical glitch?

No, because Material Icons is not directly related to Material2. Always check how to write [the correct icon name](https://material.io/icons/#ic_thumb_up) to let it show up:
1. Click on the icon
2. Click on _icon font_
3. Use the code for modern browsers:
```
STEP 2: Use Icon in Your Site
<!-- For modern browsers. -->
<i class="material-icons">thumb_up</i>
```

**Comment by mmalerba** [comment]
I'm not sure if it's possible for angular material to know if your icon name was valid. @jelbourn any ideas?

**Comment by jelbourn** [comment]
Angular Material has no way of know what is and isn't a valid icon font ligature.
