### ISSUE TITLE
Provide a NPM dependency for any module

### ISSUE THREAD

**Issue by brachi-wernick** [angular/material2#5468]
Can you provide a NPM dependency for each module, (for example `@anguler2/material/dialog`)?

currently I can only import `@angular/material` but I need only specific module, like dialog.

maybe there is a way but I didn't get it from the documentation, 
if there is please tell me how, and update the document accordingly.

**Comment by m98** [comment]
You just once install `@angular/material` and all dependencies you need will be in the `node_modules/@angular/material` directory. 

For importing one service/module to your current project, just open up the `app.module.ts` and do now you need to import which Material component you're going to use, in this case I'm going to import **dialog and tabs**

```
import {MdDialogModule, MdTabsModule} from '@angular/material';
...
...
// Now for using them, you need to import and export them like this:
imports: [
    BrowserModule,
    BrowserAnimationsModule, 
    MdDialogModule,
    MdTabsModule 
  ],
  exports: [
    MdDialogModule,
    MdTabsModule 
  ],
...
```

@DevVersion  I think this should be closed (If the problem solved)

**Comment by brachi-wernick** [comment]
@m98 *you don't understand the issue*, I don't want all material modules (like dialog, slide,button, auto complete...) in my `node_modules`,
 I don't want to import in package.json *all* the material library, only what I *need* (`dialog` in my case).
my issue isn't talking on angular modules, just on npm dependency,  one dependency per angular module. not one for all material.

**Comment by m98** [comment]
Sorry for misunderstood!
By the way, may I know why do you want to do this? Any special reason that you don't want the `@angular/material` in your package.json?

**Comment by brachi-wernick** [comment]
@m98 I have another library that I'm working with, BUT it miss the way to render dialog thru a service, there is only a way to render dialog on the html, without service. and I really want to work with service, so I find yours, but I don't need all the other components.

**Comment by m98** [comment]
What I understand from your comment is that you're not using Angular, but you still want to use `dialog` which Angular Material 2 has. Am I right?

**Comment by brachi-wernick** [comment]
@m98 I'm using angular2.

**Comment by m98** [comment]
As far as I know, it's not possible to just install one of Materia 2 components, and you will use `import` to use components you need.

**Comment by brachi-wernick** [comment]
@m98 
>it's not possible to just install one of Materia 2 components

so I'm asking to have such ability.

also I was able to do it in alpha version:
in the past I tried to import only the toggle

``` "@angular2-material/core": "^2.0.0-alpha.8-2",
    "@angular2-material/slide-toggle": "^2.0.0-alpha.8-2",
```

**Comment by m98** [comment]
`@angular2-material` was used early in the pre-release development cycle of Angular Material v2, but has no longer been used since September of 2016. Development of Angular Material now occurs under scoped npm package [`@angular/material`](https://www.npmjs.com/package/@angular/material)

**Comment by DevVersion** [comment]
@brachi-wernick As already mentioned, there is no such way to import the dialog package on it's own.

The modules/code of `@angular/material` that won't be used can be only removed using treeshaking for now.

In the future we have plans to introduce secondary entry-points like `@angular/material/dialog` that would make it easier to only include the packages your application needs.

For separate NPM modules I don't think there any plans to do this. The secondary entry-points solution is pretty close to the separate npm modules idea. 

It just means that you still need to download the full `@angular/material` package in your development environment, but in your running application only the packages you imported explicitly will be imported.
