### ISSUE TITLE
Angular material page left some gap between browser ends and the content

### ISSUE THREAD

**Issue by YuilTheLion** [angular/material2#5469]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/28005756/27767891-3e422768-5f25-11e7-8256-bc06f75fb3e6.png)
Here, there is no gap in between the ends of browser and the page.

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/28005756/27767897-556d99e0-5f25-11e7-81f7-33e8c15b9402.png)
Here, in my `localhost:4200`, there is a humiliating gap (margin) in between the ends of browser and the material toolbar.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Version: 4.2.5
OS: Windows 10 Anniversary Update
Angular Material Version: 2.0.0-beta.7
Chrome Version: 59.0.3071.115

#### Is there anything else we should know?
Node: v8.1.2
npm: v5.0.3

**Comment by Chan4077** [comment]
Did you put `md-toolbar` in `md-sidenav-container`?
Also, you have to add a `fullscreen` attribute to `md-sidenav-container`.

**Comment by m98** [comment]
Do you have any live demo?

**Comment by YuilTheLion** [comment]
I just have md-toolbar only by now.
So, I want to fix the gaps between the ends of browser and my page.

**Comment by alexmanoliu** [comment]
not working here, same problem as @YuilTripathee.
