### ISSUE TITLE
Autocomplete panel does not close in IE11

### ISSUE THREAD

**Issue by miguelcaravantes** [angular/material2#5476]
BUG

Panel in autocomplete must be closed after click md-option

Panel does not close in IE11

reproducible in plunker  of official examples
https://material.angular.io/components/autocomplete/examples

Angular 4.2.4
Angular Material Beta 7
Windows 10
Typescript
IE11

**Comment by crisbeto** [comment]
This should be resolved in master via https://github.com/angular/material2/pull/5172. Can you try installing the latest build?

```
npm install angular/material2-builds angular/cdk-builds
```

**Comment by m98** [comment]
@crisbeto May I know what is the `cdk`?

I also saw `material2/src/cdk`

Thanks

**Comment by miguelcaravantes** [comment]
@crisbeto Install master works for me, bug resolved in master
