### ISSUE TITLE
No ngOnchanges trigger combining with ngModel and mdButtonToggleGroup

### ISSUE THREAD

**Issue by e-cloud** [angular/material2#5478]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
update from ngModel should reveal changes in ngOnchanges

#### What is the current behavior?
no trigger for ngOnchanges

#### What are the steps to reproduce?

http://plnkr.co/edit/d77ph1BUaz2SdSabtmDQ?p=preview

#### What is the use-case or motivation for changing an existing behavior?
follow the common angular forms control style

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta7, Angular 4.2.4, Typescript 2.3, All browser.

#### Is there anything else we should know?
Not yet.

**Comment by darklinki** [comment]
`(ngModelChange)="onChange($event)"`

Eventually it helps, the above one works as expected so an ModelChange is actually called

**Comment by e-cloud** [comment]
When i look at this again, i realize that the value isn't an input property that it won't trigger `ngOnChanges`. I'm a fool!

Sorry for disturbing.
