### ISSUE TITLE
Add e2e tests for sidenav

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#548]

**Comment by jelbourn** [comment]
(sorry for the assignee shuffling, GitHub should really debounce that...)

**Comment by wbhob** [comment]
Also, just making all tests compatible with components. Right now, I get a ton of errors asking me to verify that `md-spinner` is part of my module...

 Or, if I'm doing something wrong, please let me know.

**Comment by robindijkhof** [comment]
#5463
