### ISSUE TITLE
Examples in Docs Not All Displayed

### ISSUE THREAD

**Issue by mtpultz** [angular/material2#5485]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Doc code examples should appear when viewing source in examples (ie. Input Errors)

#### What is the current behavior?
Viewing source displays nothing

#### What are the steps to reproduce?
View the source of the input errors, and others (ie. Input Prefix and Suffix)

#### What is the use-case or motivation for changing an existing behavior?
Proper documentation

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.x

**Comment by julianobrasil** [comment]
Already tracked by #5359.
