### ISSUE TITLE
md-card-actions button overlaps md-card-footer content

### ISSUE THREAD

**Issue by PooperPig** [angular/material2#5486]
Bug

The default styling should not allow an md-button to overlap the md-footer content

If a md-footer is added to the card-fancy-example, then the buttons in the md-card-actions overlap the footer text

#### What are the steps to reproduce?

https://plnkr.co/edit/Y57GHoYFIUflnWEmDEIq?p=preview

#### What is the use-case or motivation for changing an existing behavior?
The default behavior of a component should not be to overlay buttons and content

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.0.5
node: 7.10.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.5
@angular/compiler-cli: 4.1.3

#### Is there anything else we should know?
The behavior shows itself with the existing examples by adding an md-card-footer. In my plunker I have simply added that and made one of the buttons a 'raised' button to make the issue more obvious

**Comment by julianobrasil** [comment]
Interesting... The order of some of the elements is important. While the footer is always anchored at the bottom of the card, the actions section can move according to it's position order among other cards tags. For example, if you want to show the actions above the content, just do:

```
  <md-card-actions>
    <button md-button>LIKE</button>
    <button md-button>SHARE</button>
  </md-card-actions>
  <md-card-content>
    <p>
      Some content
    </p>
  </md-card-content>
```

I haven't noticed yet that it was allowed, but aparently it is in fact allowed:

![image](https://user-images.githubusercontent.com/25405143/27811388-3be2c654-603c-11e7-9a4b-14c94bf30494.png)

But the footer is always anchored at the bottom. So, if you put the `md-card-footer` after the `md-card-actions` tag, it works right. The things get messed up if you put the footer above the actions _and actions is the last section, having no text bellow it_.

It looks like a bug to me too. The footer section should push the content up to make space for itself at the bottom, independently of its position among the other `md-card` tags, I think.
