### ISSUE TITLE
https://material.angular.io/components/input/overview

### ISSUE THREAD

**Issue by lurongze** [angular/material2#5487]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?
some code should be there

#### What is the current behavior?

something miss ,back 404
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by m98** [comment]
Already tracked by #5456, #5391, #5359

**Comment by jelbourn** [comment]
Should be fixed now.
