### ISSUE TITLE
md-checkbox doesn't change value within md-menu

### ISSUE THREAD

**Issue by garrettH3S** [angular/material2#5494]
#### Bug:
md-menu closes before md-checkbox can change value.

#### What is the expected behavior?
md-menu closes after the md-checkbox changes its value

#### What is the current behavior?
See above.

#### What are the steps to reproduce?
html
`<a md-raised-button [mdMenuTriggerFor]="displayColumns">
					Display Columns
				</a>
				<md-menu #displayColumns="mdMenu">
					<md-checkbox *ngFor="let column of pageFilters"
						class="mat-menu-item" 
						[(ngModel)]="column.visible"
						(change)="hideColumnValues(column)">{{ column.title }}</md-checkbox>
				</md-menu>`

pageFIlters data
`pageFilters = this.pageFilters = [
			{
				title:"Foreign Episode Number",
				filterType:"foreign_episode_number",
				filterOptions:[],
				filterTitle:"Foreign Episode Number",
				is_active:false,
				visible:true
			},
			{
				title:"Episode Number",
				filterType:"episode_number",
				filterOptions:[],
				filterTitle:"Episode Number",
				is_active:false,
				visible:true
			},
			{
				title:"Medium",
				filterType:"medium",
				filterOptions:[],
				filterTitle:"Medium",
				is_active:false,
				visible:true
			},
			{
				title:"AR/A Config/Text Type",
				filterType:"ara_text_type",
				filterOptions:[],
				filterTitle:"AR/A Config/Text Type",
				is_active:false,
				visible:true
			},
			{
				title:"Standard",
				filterType:"standard",
				filterOptions:[],
				filterTitle:"Standard",
				is_active:false,
				visible:true
			},
			{
				title:"Language",
				filterType:"language",
				filterOptions:[],
				filterTitle:"Language",
				is_active:false,
				visible:true
			},
			{
				title:"Element Type",
				filterType:"element_type",
				filterOptions:[],
				filterTitle:"Element Type",
				is_active:false,
				visible:true
			},
			{
				title:"Stage",
				filterType:"stage",
				filterOptions:[],
				filterTitle:"Stage",
				is_active:false,
				visible:true
			},
			{
				title:"File Size",
				filterType:"file_size",
				filterOptions:[],
				filterTitle:"File Size",
				is_active:false,
				visible:false
			},
			{
				title:"Date Created",
				filterType:"date_created",
				filterOptions:[],
				filterTitle:"Date Created",
				is_active:false,
				visible:false
			}];`

Function thats not being triggered
`hideColumnValues(column:any):void{
		column.is_active = false;
		column.filterOptions.map((fo) => {
			fo.isActive = false;
		})
	}
`
I cannot reproduce with plunker

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.4, Material 2.0.0-beta.7, safari, OS-doesn't matter, using AoT compilation with WebPack, this error occured with the changes between beta.6 and beta.7 (i.e., its not an issue with beta.6)

**Comment by mmalerba** [comment]
@garrettH3S can you provide a plunker to reproduce?

**Comment by willshowell** [comment]
@garrettH3S here's a plunker showing it working. Maybe it'll help you reproduce the incorrect behavior.

http://plnkr.co/edit/Zt0tJRQnO4BXEihc1Gio?p=preview
