### ISSUE TITLE
Focused md-select placeholder/label required * is not accent colour

### ISSUE THREAD

**Issue by mtpultz** [angular/material2#5496]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Label text and * should be primary then accent colour

#### What is the current behavior?
Label and * are both primary colour, unlike md-input fields

#### What are the steps to reproduce?
Add a select directly out of the docs with a required property, focus on the field and select an option, and * will be primary theme colour and not accent

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://plnkr.co/edit/Oy0TpVeCi4jxSSPGeV6c?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Consistency

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.5, Angular Material 2.0.0-beta.7, Windows 10

**Comment by Knoxvillekm** [comment]
You can still add md-error?
