### ISSUE TITLE
Release 0.0.1

### ISSUE THREAD

**Issue by nareshbhatia** [angular/material2#55]
Do you plan to release 0.0.1 so we can `npm install` in our projects? Or can you please tell us how to use in other projects.

BTW, the demo is starting to look nice - super excited about this project!

**Comment by jelbourn** [comment]
We don't have anything to announce now. Stay tuned for further updates.

In the future, please only file github issues for bugs / feature requests and direct general questions to other venues.

**Comment by nareshbhatia** [comment]
Will do. Thanks.
