### ISSUE TITLE
Add e2e tests for radio-button and checkbox

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#550]

**Comment by sendilkumarn** [comment]
*.e2e.html have any use? It seems like protractor e2e considers routes only from *demo.html?

Is there any config missing or that is expected behaviour?

**Comment by jelbourn** [comment]
@sendilkumarn Not sure what you mean.

`material2/e2e` contains the tests, while `material/src/e2e-app` contains the thing being tested.

**Comment by sendilkumarn** [comment]
after tossing up server `ng serve`

running protractor tests for thing to be tested in `material2/demo-app` rather than `material2/e2e-app`

am i missing out something here? even router navigates to /button

**Comment by jelbourn** [comment]
@hansl can you add instructions on running the e2e tests to our dev environment guide?

**Comment by jelbourn** [comment]
@sendilkumarn our [dev_environment guide](https://github.com/angular/material2/blob/master/DEV_ENVIRONMENT.md) should now contain instructions for running the e2e tests.

**Comment by jelbourn** [comment]
Done via #1582 and #1602
