### ISSUE TITLE
md-icon in an md-menu-item doesn't apply colour from color property

### ISSUE THREAD

**Issue by mtpultz** [angular/material2#5501]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-icons within md-menu should use color property from theming

#### What is the current behavior?
md-icons in md-menus are always grey

#### What are the steps to reproduce?
Drop in a md-menu example from the docs and set color on the md-icons within the menu

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://plnkr.co/edit/kqhWFT09iSogmBiWC20R?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Theming

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.4, Angular Material 2.0.0-beta.7, Windows 10

**Comment by julianobrasil** [comment]
You can use regular css **`color`** to paint it:

![image](https://user-images.githubusercontent.com/25405143/27846714-bb0935de-610f-11e7-8f0f-54f3e10440f5.png)

**Comment by chetan-rathod** [comment]
i also have prblm with this

**Comment by mtpultz** [comment]
Thanks @julianobrasil for the suggestion :)  I'd would recommend to anyone with this issue to use `:host /deep/ .mat-icon { ... }` to override the styles instead of inlining so you keep styles in your Sass files.  I just wanted to report the issue so it was visible.

**Comment by mackelito** [comment]
FYI /deep/ will be deprecated.. use ::ng-deep if possible.
https://blog.angular.io/angular-4-3-now-available-8d57b57eb5a8

**Comment by crisbeto** [comment]
Should be fixed by https://github.com/angular/material2/commit/d0cb0771bd6d254dbd4f6cf4c35d503f14b9008b.
