### ISSUE TITLE
Md-list breaks when using with ng-container or ng-template

### ISSUE THREAD

**Issue by azarus** [angular/material2#5502]
#### Bug, feature request, or proposal:
Bug, mdlist & md-nav-list breaks when used with ng-container or ng-template.

#### What is the expected behavior?
https://i.imgur.com/Iv6pc7q.png

#### What is the current behavior?
https://i.imgur.com/ca4MC8K.png

#### What are the steps to reproduce?

```
<md-nav-list>
		<h3 md-subheader>Tests</h3>
		<a md-list-item *ngFor="let test of tests">
			<ng-container [SubComponent]="test">
			</ng-container>
		</a>
	</md-nav-list>
```

Dynamic component or template:
```
	<md-icon md-list-avatar fontIcon="fa-clock-o"></md-icon>
		<p md-line>Time Period</p>
		<p md-line>Queries data from cool</p>

```
Where right now subcomponent is a custom directive that is just a component factory dynamically loading components into the list based on the data repeated # in *ngFor

#### What is the use-case or motivation for changing an existing behavior?
It doesn't work like most of the things in material2.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Probably all of them.

#### Is there anything else we should know?
No.

**Comment by julianobrasil** [comment]
Isn't this an Angular issue?

**Comment by azarus** [comment]
How would it be an angular issue? Thought md-list & md-nav-list isn't part of angular.
The display breaks because the md-list adds some custom dom & css classes when compiling.

**Comment by julianobrasil** [comment]
@azarus, I went for an Angular issue, because, by design, ng-template was suposed to work without interfere in the layout (and in Angular docs there are no conditions specified for it to work nor exceptions that would make it brake). Anyway, it's a very superfitial gess of mine as Angular docs itself are still being improved.

**Comment by willshowell** [comment]
Looks like a side-effect of content project only working at the top-level.

[list-item content projection](https://github.com/angular/material2/blob/master/src/lib/list/list-item.html#L9)

Related discussions:
- https://github.com/angular/material2/issues/5263#issuecomment-309916427
- https://github.com/angular/material2/issues/5292

It seems like this open issue in angular core (https://github.com/angular/angular/issues/8563) would help in this case, but I'm not certain.

**Comment by azarus** [comment]
I guess it breaks since the viewchild is not there when the component is being initialized and the dynamic component is not initialized just yet. So the actual content the list is inteded to work with doesn't exists. And there fore it does not sets up the required classes and divs. Probably the best fix would be to make the child elements send a norification to the parent components and request an update on the view.

**Comment by jelbourn** [comment]
This is the expected behavior based on how content projection works in Angular; the API for the list calls for the `md-line` to be a direct child of the item.

**Comment by azarus** [comment]
@jelbourn my personal user experience is horrible with material2 man

**Comment by willshowell** [comment]
@azarus, as @julianobrasil points out [here](https://github.com/angular/material2/issues/6625#issuecomment-325223229), you can use `ngProjectAs` to project whatever you want.

Annoyingly, there doesn't seem to be any official documentation on the subject, but there is a pretty good Medium post on it: https://medium.com/claritydesignsystem/ng-content-the-hidden-docs-96a29d70d11b

**Comment by azarus** [comment]
Thanks, we hired a second developer to speed up the development of our new frontend since these small issues we found during porting our old code to angular2 just cause huge delays and consume our resources to sort out. We'll check on it.

**Comment by nickwinger** [comment]
ok, i just found a workaround:
```
<mat-list-item>
  <div matLine>
    <ng-container *ngTemplateOutlet="myTemplate"></ng-container>
  </div>
</mat-list-item>
```

**Comment by nickwinger** [comment]
to enable mat-multi-line styling (so the item gets css auto height) you have to put 3 dummy matLines:

> <mat-list dense>
>       <ng-container *ngFor="let row of (dataSource$ | async).data | async">
>         <mat-list-item (click)="selectRow(row)" [ngClass]="{'selected': isSelected(row)}">
>           
>           <div matLine></div>
>           <div matLine></div>
>           <div matLine></div>
>           <div matLine>
>             <ng-container *ngTemplateOutlet="xsRowDefaultTemplate;context: {row: row, isForeignKey: isForeignKey,cellItemTmpl: cellItemTmpl, initialMetainfo: initialMetainfo, displayedColumns: displayedColumns}"></ng-container>
>           </div>
>         </mat-list-item>
>         <mat-divider></mat-divider>
>       </ng-container>
>     </mat-list>
