### ISSUE TITLE
md-input-container using input type number send cursor to the end on keyup

### ISSUE THREAD

**Issue by limpep** [angular/material2#5506]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Cursor not to move to the end of value on key up

#### What is the current behavior?
When you enter a value for example 2 the cursor is sent to the end on keyup

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
here is an example
http://plnkr.co/edit/5mH6Y0Qy2x3QDWje3zEt?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.2.0
node: 8.1.2
os: darwin x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5

**Comment by julianobrasil** [comment]
It is not a bug. It's a problem with your construction:

`[ngModel]="amount | number:'1.2-5'" (ngModelChange)="amount=$event"`

As soon you type something, you update `amount` and it updates `ngModel` which in turn updates `input` value, sending the cursor to the end.

**Comment by limpep** [comment]
@julianobrasil Makes sense. I'm not sure what you mean by the `placeholder` attribute.

**Comment by julianobrasil** [comment]
I'll provide a pluncker as soon as possible.

Em 5 de jul de 2017 12:31 PM, "Ergun Polat" <notifications@github.com>
escreveu:

@julianobrasil <https://github.com/julianobrasil> Makes sense. I'm not sure
what you mean by the placeholder attribute.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/angular/material2/issues/5506#issuecomment-313138782>,
or mute the thread

**Comment by ryanpm40** [comment]
You'll probably want to look into JavaScript's HTMLInputElement.selectionStart and .selectionEnd to maintain cursor positioning. You may need to wrap it in a setTimer to ensure ngModel updates in time.

**Comment by julianobrasil** [comment]
@limpep, I understand from your code that you wanted to give the user a hint to what kind of information he should type in the input: `[ngModel]="amount | number:'1.2-5'"`. To do it there's `md-hint` to put a message bellow the input and there's some code to put it in the input itself. If the latter is what you intended, you can do it like what's in the plunker (see how the float placeholder change as you use the input): http://plnkr.co/edit/w02C5fdE91CXTVdOGMoA?p=preview

**Comment by limpep** [comment]
@ryanpm40 Interesting I'll look into this, Thanks.

@julianobrasil I actually just want to be able to set the input value as a decimal using a default value of 0.00, hence why I was using the number pipe.  But since typescript does not support double type, which is beyond me and `toFixed(2`) return type is `string` its a bit difficult to do so.

**Comment by willshowell** [comment]
@limpep Maybe only parsing/formatting the value on blur could work?

http://plnkr.co/edit/4sEzWIWq12uXNWa9J0X4?p=preview

**Comment by limpep** [comment]
@willshowell I think this approach works best and its a good solution. Thanks for you help.
