### ISSUE TITLE
mdInput not working

### ISSUE THREAD

**Issue by m-kotek** [angular/material2#5507]
#### Bug, feature request, or proposal:
Bug / mistake 

#### What is the expected behavior?
Show material input field

#### What is the current behavior?
Buggy input: Blank white input field. The placeholder is displayed in the next line left-bounded. No material design elements. See Screenshots:

![login](https://user-images.githubusercontent.com/13656007/27863652-6b9c49f6-618b-11e7-9a84-67f44ce0a951.PNG)
![loginwithtext](https://user-images.githubusercontent.com/13656007/27863651-6b9b9a42-618b-11e7-8a96-3a1ac02991cb.PNG)

#### What are the steps to reproduce?
- ng new webapp
- npm install --save @angular/material
- npm install --save @ang

ular/animations
- npm install --save hammerjs

After that i importet the modules in app.module.ts
http://plnkr.co/edit/tcdmRCC46tmsiTuEGIEa?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/animations": "^4.2.5",
"@angular/common": "^4.0.0",
"@angular/compiler": "^4.0.0",
"@angular/core": "^4.0.0",
"@angular/forms": "^4.0.0",
"@angular/http": "^4.0.0",
"@angular/material": "^2.0.0-beta.7",
"@angular/platform-browser": "^4.0.0",
"@angular/platform-browser-dynamic": "^4.0.0",
"@angular/router": "^4.0.0",
"core-js": "^2.4.1",
"hammerjs": "^2.0.8",
"rxjs": "^5.1.0",
"zone.js": "^0.8.4"

Thank you

**Comment by julianobrasil** [comment]
Did you import any theme? If not, try:

 `<link href="https://rawgit.com/angular/material2-builds/master/prebuilt-themes/indigo-pink.css" rel="stylesheet">`

in you index.html.

**Comment by m-kotek** [comment]
Thanks a lot julianobrasil, worked for me. I imported the style in app.component.css with `@import '~@angular/material/prebuilt-themes/indigo-pink.css';`
