### ISSUE TITLE
There is no directive with "exportAs" set to "mdButtonToggleGroup"

### ISSUE THREAD

**Issue by trichetriche** [angular/material2#5508]
#### Bug, feature request, or proposal:

Bug/feature

#### What is the expected behavior?

When I use the `mdButtonToggleGroup`, I expect to be able to test the component holding it

#### What is the current behavior?

An error occurs when testing : 

    There is no directive with "exportAs" set to "mdButtonToggleGroup"

#### What are the steps to reproduce?

Add a mdButtonToggleGroup to any html template and force describe its spec file

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

In case you need it, my `package.json`

      "dependencies": {
        "@angular/animations": "^4.0.0",
        "@angular/cli": "1.1.2",
        "@angular/common": "^4.0.0",
        "@angular/compiler": "^4.0.0",
        "@angular/compiler-cli": "^4.0.0",
        "@angular/core": "^4.0.0",
        "@angular/flex-layout": "^2.0.0-beta.8",
        "@angular/forms": "^4.0.0",
        "@angular/http": "^4.0.0",
        "@angular/material": "^2.0.0-beta.7",
        "@angular/platform-browser": "^4.0.0",
        "@angular/platform-browser-dynamic": "^4.0.0",
        "@angular/router": "^4.0.0",
        "@types/parse": "^1.9.2",
        "aws-sdk": "^2.74.0",
        "core-js": "^2.4.1",
        "express": "^4.15.3",
        "font-awesome": "^4.7.0",
        "hammerjs": "^2.0.8",
        "intl": "^1.2.5",
        "parse": "~1.8.0",
        "parse-dashboard": "^1.0.28",
        "parse-server": "*",
        "primeng": "^4.1.0-rc.2",
        "rxjs": "^5.1.0",
        "zone.js": "^0.8.4"
      },
      "devDependencies": {
        "@angular/language-service": "^4.0.0",
        "@types/jasmine": "2.5.45",
        "@types/node": "~6.0.60",
        "codelyzer": "~3.0.1",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "karma-mocha-reporter": "^2.2.3",
        "karma-phantomjs-launcher": "^1.0.4",
        "protractor": "~5.1.2",
        "ts-node": "~3.0.4",
        "tslint": "~5.3.2",
        "typescript": "~2.3.3"
      }

**Comment by trichetriche** [comment]
**UPDATE** Importing `MaterialModule` does the trick. Maybe I was importing the wrong module ? I use the `MdButtonToggleModule` from the documentation, is this another one ?

**Comment by trichetriche** [comment]
**UPDATE 2** I had a problem with my code, this is all my fault, sorry ... The documentation is good !

**Comment by liliom55** [comment]
I have the same issue with md-menu. 
angular: CLI  v1.4.3
npm:  v3.10.10
node:  v6.11.1
package.json:
`"dependencies": {
    "@angular/animations": "^4.0.3",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "4.0.x",
    "@angular/compiler": "4.0.x",
    "@angular/compiler-cli": "4.0.x",
    "@angular/core": "4.0.x",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "4.0.x",
    "@angular/http": "4.0.x",
    "@angular/material": "github:angular/material2-builds",
    "@angular/platform-browser": "4.0.x",
    "@angular/platform-browser-dynamic": "4.0.x",
    "@angular/platform-server": "4.0.x",
    "@angular/router": "4.0.x",
    "@material/textfield": "^0.2.3",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "material-components-web": "^0.7.0",
    "ng2-translate": "^5.0.0",
    "ngx-bootstrap": "^1.6.6",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.9"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.3",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }`
error: 
`There is no directive with "exportAs" set to "mdMenu" ("
    <md-icon>more_vert</md-icon>
</button>
<md-menu [ERROR ->]#menu="mdMenu">
    <button md-menu-item (click)="callAssistance()">
`
