### ISSUE TITLE
feat(divider): move divider out of mat-list

### ISSUE THREAD

**Issue by CaerusKaru** [angular/material2#5524]
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

Pursuant to the spec, dividers are used in areas other than plain lists, most notably in [cards](https://material.io/guidelines/components/cards.html#cards-content-blocks). 

#### What is the current behavior?

Using `mat-divider` requires `MatList`, even when used in other components.

#### What are the steps to reproduce?

1. Try to use `mat-divider` without importing `MatListModule`

#### What is the use-case or motivation for changing an existing behavior?

There should be an ability, like in AngularJS Material, to use `mat-divider` without relying on `MatList`. This would also be a great opportunity to implement the [inset divider](https://github.com/angular/material2/issues/4570), would close #2017, and open up an opportunity to implement the `vertical` (or at least responsive) option that was in Material 1.0.

Obviously not a priority, but a nice to have feature.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All current as of 7/5/2017 (@angular/material@beta.7)

**Comment by peluprvi** [comment]
In cards specs, there are [full-bleed divider](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3Tkh3SnNvSkp5YVU/components_cards_action6.png) and [inset dividers](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3VkxjZkhsWmpZNWM/components_cards_action4.png)
