### ISSUE TITLE
Scss compile error even with sass-loader 6.0.6  - Error: File to import not found or unreadable

### ISSUE THREAD

**Issue by Jebedo** [angular/material2#5530]
Error: File to import not found or unreadable: ~@angular/material/_theming.
`@import "~@angular/material/theming";`

#### What is the expected behavior?
Compiling scss,

#### What is the current behavior?
Not compiling. Getting error:
Error: File to import not found or unreadable: ~@angular/material/_theming.

Tried with  ~@angular/material/_theming.scss

_theming.scss is in node_modules

Package.json:
```
"@angular/core": "^4.1.0",
"@angular/material": "^2.0.0-beta.7",
 "node-sass": "^4.5.3",
 "sass-loader": "^6.0.6",
```
I am not using angular-cli.

**Comment by jelbourn** [comment]
If you're not using the angular-cli, you should reference the file the same way you would reference any other sass file (with whatever build tooling you use).
