### ISSUE TITLE
Select Can't not show last value **Specific zero (0)  

### ISSUE THREAD

**Issue by Aofhero** [angular/material2#5531]
Select Can't not show last value **Specific zero (0)  

Sample
```
objList : Array<number> = [-1 , 0 , 1 , 2];
public selectValue : number ;

<md-selec placeholder="--Select--" [(ngModel)]="selectValue" >
      <md-option *ngFor="let obj of objList" [value]="obj" >{{ obj }}</md-option>
 </md-select>
```
1. When I selected -1 / 1 / 2  next page and back page > value in select box show 1
2. When I selected 0 (zero) next page and back page > value not show but it show placeholder

Help Me please

**Comment by julianobrasil** [comment]
What version of material are you using?

**Comment by Aofhero** [comment]
Oh thx a lot, I updated version and it work.  nice job
