### ISSUE TITLE
md-expansion-panel with a button

### ISSUE THREAD

**Issue by ChinesePeanuts** [angular/material2#5533]
#### Bug, feature request, or proposal:
More a request than a bug I suppose

#### What is the expected behavior?

When having a button in `<md-expansion-panel-header>` the button should trigger normaly without collapsing the panel.

#### What is the current behavior?

Clicking the button collapses the panel

#### What are the steps to reproduce?

http://plnkr.co/edit/QFkAL500pcgqxLgL9BnF?p=preview

#### What is the use-case or motivation for changing an existing behavior?

I believe it should behave a little bit like a toolbar (+ the expansion part), it would be great.
A class should maybe exist to prevent this behavior in the `<md-expansion-panel-header>` tag

**Comment by julianobrasil** [comment]
That's because of [Material Design Specification for expansion panels](https://material.io/guidelines/components/expansion-panels.html#expansion-panels-usage) (by Google). According to the doc:

"_A collapsed panel displays summary information_"

All components of the official set must stick to these specifications.

**Comment by jelbourn** [comment]
The panel header **is** a button with respect to accessibility, so adding more buttons or anchors inside of it is not something we support.

**Comment by roben** [comment]
I had a similar requirement. A list of panels providing summaries with edit functionality when being expanded. Each should also contain a selection checkbox without having to expand it first.

The way I managed to do this is by putting the checkbox outside of the `md-expansion-panel` and positioning it absolutely on top of it (the header needs some padding, then):

![image](https://user-images.githubusercontent.com/812205/30382315-1639036e-989f-11e7-8c2a-93552838eca6.png)

**Comment by priyaragavan** [comment]
how to prevent from expansion or disable for some specific reason of the expansion panel? suggestion please.

**Comment by julianobrasil** [comment]
```js
disableMe = true;
```

```html
<mat-expansion-panel [disabled]="disableMe"></mat-expansion>
```

**Comment by kuncevic** [comment]
I that is what I am trying to do:
![image](https://user-images.githubusercontent.com/1283734/31419712-11146536-ae89-11e7-8702-8df9b3c962f7.png)

Basically I have a filters thing, so I want to show the basic filter by default and then if user want to apply more filters the panel has to be expanded, but If user clicked any controls on in the header it trigger the panel to expand. It would of be nice to be able to have an option that you can expand panel only by clicking the expand button in the right corner. However by reading the responses on that issue seams like it is against the `Expansion Panel Google material style guide` however it is something in my spec. 

Tried to set `[disabled]="false"` but now it prevents the panel to be expanded.

What do you think is the best way of handle that?

**Comment by ver0nikadataformers** [comment]
is this still considered an open issue? Even if the spec defines the expansion panel header as only summary information, as reality shows, there are cases when this behaviour simply is necessary. all of the proposed solutions do their job but still are indeed quire hacky to quote @kuncevic

**Comment by ortichon** [comment]
Hi guys,
I solved similar issue by adding `(click)="foo($event)"` to the check-box element, then in the Component I do
```typescript
foo(event: Event) {
  event.stopPropagation();
}
```

**Comment by hobojoe** [comment]
@kuncevic could you share your example?

I tried implementing it but the controls aren't placed properly on the expansion-panel header:
https://stackblitz.com/edit/angular-vkval7

Thanks!

**Comment by kuncevic** [comment]
@hobojoe hey there sorry missed your comment
here it is the working example I mentioned above https://stackblitz.com/edit/angular-3jcuzp

**Comment by ver0nikadataformers** [comment]
thanks for sharing your solution @kuncevic

**Comment by jsantoru** [comment]
great solution @ortichon. thanks!

**Comment by jainankit102** [comment]
@ortichon stopPropogation() work for click event but for 'Enter' event toggle is happening. I tried with stopPropogation and preventDefault also both are not working.

Thanks in advance.

**Comment by micsel** [comment]
Temporary trick I used below works fine for now...
`<mat-expansion-panel [disabled]="true">
        <mat-expansion-panel-header style="color: #000000">`

**Comment by ortichon** [comment]
@jainankit102 @micsel 
can you provide a working example (plunker or similar)?

**Comment by Reachakhil** [comment]
@ortichon solution worked good!!

**Comment by feech** [comment]
I suggest you implement your functionality with the tree-component

**Comment by harshadray** [comment]
> Hi guys,
> I solved similar issue by adding `(click)="foo($event)"` to the check-box element, then in the Component I do
> 
> ```ts
> foo(event: Event) {
>   event.stopPropagation();
> }
> ```

it works great when button enable but somehow if I need to disable button, it will not works. Do you have any work around for that case?

**Comment by feech** [comment]
I gave up to extend expansion panel behavior. but had success with 'tree' component - that's my workaround for all questions above
