### ISSUE TITLE
md-select styling inconsistent with other input element

### ISSUE THREAD

**Issue by rernens** [angular/material2#5534]
#### Bug:

1. font-size for content is bigger than for other input elements and affects place holder size when moved above after value is selected
2. underline is not placed exactly at the same position than for other input element : 1px higher
3. error messages are not displayed using the warn color and the font-size is not the same

#### What is the expected behavior?

visual consistency with other input elements

#### What is the current behavior?

visual inconsistency

#### What are the steps to reproduce?

build a custom theme using scss without changing any of the default config parameters

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular : 4.2.5
material : lastest
typescript: 2.4.1
browser : chrome

**Comment by jelbourn** [comment]
Tracked via #2124
