### ISSUE TITLE
md-hint, md-error overflow the md-input-container

### ISSUE THREAD

**Issue by PhilipSultanescu** [angular/material2#5539]
#### Bug, feature request, or proposal:
md-hint, md-error overflow the md-input-container at the bottom.

![screen shot 2017-07-06 at 15 17 56](https://user-images.githubusercontent.com/4140990/27913372-3268b7c0-6260-11e7-8ace-63e23080f331.png)

It's causing overlaps with the next control like for this Login button.
![screen shot 2017-07-06 at 15 32 26](https://user-images.githubusercontent.com/4140990/27913431-5b52f9ca-6260-11e7-99f6-c4c9b7570d5e.png)

#### What is the expected behavior?
Child controls of the md-input-container should not overflow the container.

#### What is the current behavior?
md-hint, md-error overflow the md-input-container

#### What are the steps to reproduce?
First print screen for the hint made from here:
https://material.angular.io/components/input/examples

#### What is the use-case or motivation for changing an existing behavior?
Input controls overlap on the next ones like in the second image with the error.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/core: 4.2.3
@angular/flex-layout: 2.0.0-beta.8
@angular/material: 2.0.0-beta.7
typescript: 2.3.4
font-name: Roboto
MacOS Sierra
Chrome, Firefox, Safari

**Comment by PhilipSultanescu** [comment]
I see this is solved, can you also check @jelbourn @mmalerba and close it?

**Comment by mmalerba** [comment]
It still seems very slightly too short (can be seen when setting the font size very high (e.g. 100px). I'll create a PR

**Comment by PhilipSultanescu** [comment]
Better, but still not perfect, when I zoom it overflows, see here:

<img width="1076" alt="screen shot 2017-07-28 at 11 07 37" src="https://user-images.githubusercontent.com/4140990/28710646-119d174e-7385-11e7-82c8-ff2fbf58e264.png">

**Comment by mmalerba** [comment]
@PhilipSultanescu The spec also says different numbers for those same measurements in the [text fields section](https://material.io/guidelines/components/text-fields.html#) so nothing is going to completely agree with every image in the spec. I think the recent changes put the spacing between internal elements in a good state. For the host element its easy for developers to just set whatever margin they want for their application
