### ISSUE TITLE
md-list inside md-grid-list 

### ISSUE THREAD

**Issue by mbx2015** [angular/material2#5544]
md-list css style not works if the md-list is used within a md-grid-list

**Comment by julianobrasil** [comment]
Please, provide a plunker.

**Comment by brucepc** [comment]
I don't know if is the same problem but here are some sample...
1. the scrolbar doesn't appear
2. the md-ripple doesn't work as desired

[Plunkr Sample](https://embed.plnkr.co/bwap9T/)
