### ISSUE TITLE
Warning when installing the 2.0.0-beta.8

### ISSUE THREAD

**Issue by dev054** [angular/material2#5550]
#### What is the current behavior?
After ran `npm i @angular/material@2.0.0-beta.8 -S` it shows the warning:

> npm WARN @angular/material@2.0.0-beta.8 requires a peer of @angular/cdk@2.0.0-beta.8 but none was installed.

I just read the `CHANGELOG` and it says: 

> @angular/material now depends on @angular/cdk as a peer dependency.

Does it means that from now we have to install `@angular/cdk`? If so, I think it should be more clear in CHANGELOG.

#### What are the steps to reproduce?
Install the latest version (2.0.0-beta.8).

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material@2.0.0-beta.8

**Comment by willshowell** [comment]
Yes, you will need to install `@angular/cdk` as well

**Comment by benb7760** [comment]
Related to #5552

**Comment by HarelM** [comment]
I think the problem here is that beta.8 was already released before today, and today the version was overridden, which, in my case, caused my CI build to fail.
Was this intentional?

**Comment by danwulff** [comment]
@HarelM, this was my issue as well. I had a clean build yesterday with beta.8 and then today it failed with unmet peer dependency. Lots of confusion around this release change.

**Comment by HarelM** [comment]
Sorry, my bad, I'm using `^2.0.0-beta.6` in my `packages.json` which caused my CI to take version 8 instead of 6.

**Comment by jelbourn** [comment]
I think 
> @angular/material now depends on @angular/cdk as a peer dependency.

Is pretty explicit.

**Comment by HarelM** [comment]
Version-management-wise, this is a breaking change. 
npm can ignore the last digit assuming publisher will change the last digit only when not making breaking changes. 
This is the global convention regarding versions numbering and this was a breaking change and the only digit that was changed was the last which is the problem, IMHO.
Since this is still in beta I'm not sure it should follow these rules but you should be aware of it nevertheless...

**Comment by jammyvelli** [comment]
results in (SystemJS) XHR error (404 Not Found) loading ...... due to version numbering issue.

npm WARN @angular/material@2.0.0-beta.8 requires a peer of @angular/cdk@2.0.0-beta.8 but none was installed.
