### ISSUE TITLE
bug(github docs): mention @angular/cdk in material installation instructions

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#5552]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

github first page should specify `@angular/material` depends on `@angular/cdk`

#### What is the current behavior?

The intallation  instructions on github mentions the `@angular/cdk` dependency just for the latest builds part.

![image](https://user-images.githubusercontent.com/25405143/27929117-121762b6-6268-11e7-8b35-48c7b653c7c5.png)

**Comment by jelbourn** [comment]
We should really just remove this section from the README and point to the getting started guide.

**Comment by julianobrasil** [comment]
I think removing the installation part entirely and leaving the Getting Started part is sufficient. I'll just include the latest builds installation in the Getting Started part:

`npm install --save angular/material2-builds angular/cdk-builds`

**Comment by julianobrasil** [comment]
@jelbourn, I built a PR with these modifications: https://github.com/angular/material2/pull/5555#issuecomment-313647645. Take a look to see whether it's good.

**Comment by dauledk** [comment]
What about @angular/animations, is that not a required package as well?

**Comment by julianobrasil** [comment]
@dauledk, it was already in Getting Started page on github.
