### ISSUE TITLE
Add docs for expansion-panel and accordion 

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#5568]
We currently are missing documentation for expansion-panel / accordion. This needs:
- [ ] An overview file (`expansion.md`)
- [ ] At least two examples (typically one simple and one more in-depth)

The style of the overview should align with existing docs.

**Comment by julianobrasil** [comment]
@jelbourn, there's an issue with expansion-panel. When you select, for the first time, an md-tab that have an expansion inside, it's shown expanded and a little messed up: #5269

If it's put in the examples tab, this issue will mess with it (plunker: http://plnkr.co/edit/q6kXPH?p=preview), unless some kind of workaround is used along with it.
