### ISSUE TITLE
MdCheckbox does not render opacity correctly on Safari

### ISSUE THREAD

**Issue by chrismcgregor** [angular/material2#557]
MdCheckbox has irregular behavior for Safari browser (cannot select).

**Comment by sendilkumarn** [comment]
We can select it in safari, but the opacity in transition is not setting properly.

@jelbourn  I think we have to use `transition-timing-function` here. That is also supported by all latest versions of browsers.

Tested in Firefox / Opera / Chrome and Safari.  Seems to work fine.

**Comment by jelbourn** [comment]
@chrismcgregor Please follow the issue template for future issues.

**Comment by jelbourn** [comment]
Should be fixed in #594

**Comment by chrismcgregor** [comment]
Excellent, thank you!
