### ISSUE TITLE
Angular Material 2 shows errors in node_modules

### ISSUE THREAD

**Issue by WonderfulNature** [angular/material2#5570]
#### What is the current behavior?
![error ts](https://user-images.githubusercontent.com/29972233/27947567-fdc29018-6313-11e7-807b-4f3bf65d262a.PNG)

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Is there anything else we should know?
typescript version - 2.2.0
VSCODE version - 1.6.1

**Comment by Chan4077** [comment]
Can you show your `package.json`?

**Comment by willshowell** [comment]
@WonderfulNature do you get the same errors when you try to compile outside of vscode? Also package.json as @Chan4077 mentioned

**Comment by jelbourn** [comment]
This is caused by using a version of TypeScript less than 2.2. Be sure you clear your `node_module` and `package-lock.json` before reinstalling.
