### ISSUE TITLE
feature request: table

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#5572]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
dragble column header, row group, row selectable

#### What is the current behavior?
none

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by jimmykane** [comment]
It's there dude in latest release

**Comment by tytskyi** [comment]
Inappropriate issue title. Feature request is about extending tables with some behavior. 

However i can't understand even details - too small description of desired features.

**Comment by irowbin** [comment]
@andrewseguin These features also highly demanded. Please consider these features on next release if possible . Thanks
For example
```javascript
   <md-table #table [dataSource]="dataSource"
                     mdSort  
                     mdFixHeader="true"     // header will be fixed on vertical scroll
                     mdFixFooter="true"     // footer will be fixed on vertical scroll
                     mdFixLeftCol="3"       // fix  columns on left side while horizontal scroll 
                     mdFixRightCol="3"      // fix columns on right side while horizontal scroll 
                     mdCellEditable="true"> // adds an inline editable input on cell clicks

```

**Comment by stevenmi** [comment]
@irowbin i mean the column header can be draged from one position to another position.
rowgroup: like treegrid in easyui.
row selectable: means the row can be selected ,i can get the value the row i selected and with the selected css style

**Comment by jelbourn** [comment]
We have no plans to bake drag-and-drop into the table itself, though we will be exploring general drag/drop utilities that could be applied to the table in the future.
