### ISSUE TITLE
MdTableModule missing from @angular/material

### ISSUE THREAD

**Issue by jimmykane** [angular/material2#5574]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MdTableModule 

#### What is the current behavior?
MdTableModule is not in Angular material and editor tries to import it from types

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest (as of this time) ^2.0.0-beta.8

**Comment by jimmykane** [comment]
To be more specific: 
Where I import all the MD modules, in my app module, the MdTableModule cannot be imported. 
I cannot understand what I am doing wrong here and why would the editor try to autoimport it from  @types .

**Comment by willshowell** [comment]
This plunker demos being able to import `MDTableModule` from `@angular/material`

https://plnkr.co/edit/C3YN0x2qrMaqcD6izvK7?p=preview

Did you wipe and reinstall your node modules?

**Comment by jimmykane** [comment]
I ll do that @willshowell I am on the road atm. Thanks will report back.

**Comment by campa** [comment]
rm -fR node_modules
npm instlall

Solved my problem... and so I'm going to migrate to npm 5 from 3 ...  
Other problems there is, but not this.

**Comment by jimmykane** [comment]
@campa So you also had this issue?

**Comment by campa** [comment]
Solved. It was my fault

**Comment by jelbourn** [comment]
It's definitely there. I recommend clearing your node_modules and your `package-lock.json` if you're using npm before re-installing (npm 5 seems to prefer the package lock even if you update the `package.json`)

**Comment by jimmykane** [comment]
Yes it was. Sorry for the delay and @jelbourn great work guys! You rock!

**Comment by Chrisis52** [comment]
Hi, i dont know if its an issue but the tableModule and also SortModule  i noticed are only part of the last beta.8 version

I pulled the beta.7  as beta.8 seems broken for the moment are they are not part of the previous version :'

**Comment by mustafaekim** [comment]
I had similar problems (missing MdTableModule) with beta 2.0.0-beta.8 and webpack 2.7.
I repeated `npm install @angular/material` and it worked. bizarre

**Comment by ptagl** [comment]
I had the same problem, was using beta.6 version; switching to beta.8 solved!
