### ISSUE TITLE
Problem with Plunker demo for DataTable

### ISSUE THREAD

**Issue by mdelorimier** [angular/material2#5575]
#### Bug, feature request, or proposal:
The plunker demo for Data Table is not loading properly

#### What is the expected behavior?
It should load without errors

#### What is the current behavior?
Tere is a 404 error when trying to load cdk.ts, some modules aren't loaded correctly in the main module

#### What are the steps to reproduce?
Click on the plunker link in the demo page : https://material.angular.io/components/table/overview

#### What is the use-case or motivation for changing an existing behavior?
Viewing demo code to implement the component

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current (documentation)

#### Is there anything else we should know?
Here is the fixed version : https://plnkr.co/edit/gk9KLraXnvTbBNLcPdEq

**Comment by SamuelMarks** [comment]
Close this issue, looks like people are participating on: https://github.com/angular/material2/issues/5569

**Comment by ryanpm40** [comment]
Head's up- every plunker example I've opened so far has failed to load.

Getting errors loading platform-browser and cdk for multiple components (md-button, select, spinner, etc)

**Comment by mdelorimier** [comment]
Will continue on #5569
