### ISSUE TITLE
Md-autocomplete always hidden when used with md-optgroup

### ISSUE THREAD

**Issue by alex321** [angular/material2#5581]
#### Feature:

Autocomplete is hidden when the dropdown contains an `md-optgroup` with `md-option` inside it.

#### What is the expected behavior?
Autocomplete should be compatible with `md-optgroup`.

#### What are the steps to reproduce?
The `md-autocomplete` stays hidden as shown in this plunker:

https://plnkr.co/edit/JIU35gPRfqDaBBwzMG6S?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material: 2.0.0-beta.8

**Comment by tariknz** [comment]
I have a sad workaround for anyone waiting on this PR http://plnkr.co/edit/Q52JjTxtjjwW0r44n03l?p=preview
