### ISSUE TITLE
Add e2e test for progress-bar and progress-circle

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#559]

**Comment by jelbourn** [comment]
@deerawan sure, we should have instructions for running the e2e tests in our dev_environment guide soon.

**Comment by jelbourn** [comment]
@deerawan Instructions should be there now.

**Comment by emoralesb05** [comment]
Just FYI, protractor times out when using the progress circle in a page since the `setInterval()` does not let the page sync with protractor when its in `indetermined` mode.
