### ISSUE TITLE
bug(data-table): data source connect not called when using router

### ISSUE THREAD

**Issue by benb7760** [angular/material2#5593]
#### Bug, feature request, or proposal:
I have copied the exact demo from 'material-examples' into a plunker and have loaded the `TableBasicExample ` component via a router. When navigating to the router (via button in toolbar on plunkr), the table does not display correctly. When clicking that button again, it works. In my own application I have tested by including logging in the `connect()` method of the data source. It does not get called on initial navigation to the route, but it does when you navigate the second time

One resolution I have used is to perform the dataSource initialization in a setTimeout(1), which solves the issue, but I do not believe that this should be the solution.

#### What is the expected behavior?
The data source connect method should be called after navigating to page via router

#### What is the current behavior?
The data source connect method is not called

#### What are the steps to reproduce?
http://plnkr.co/edit/RRVoUV9SBAxozY6VhvpA?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest master, and beta8

**Comment by Fiste788** [comment]
same for me

**Comment by xbtequila** [comment]
Same here. 

When calling changeDetector.detectChanges after setting the DataSource to manually trigger  ChangeDetection the Table will show up.

http://plnkr.co/edit/Soc0n4ak80VKdZ27htVU?p=preview

**Comment by WebField** [comment]
Same here. 
The workaround with changeDetector.detectChanges also works for me, but is not satisfying.

**Comment by wangyang2012** [comment]
same problem

**Comment by niceilm** [comment]
Same here

**Comment by houabidi** [comment]
Same for me !

**Comment by Potmos** [comment]
How is this Issue closed? 
I mean it does have a workaround that somehow works, but the issue itself is not fixed.
At least the workaround should be mentioned on the documentation.

**Comment by maxime1992** [comment]
Lost so much time figuring this out... =(

I also tried to use snapshot builds but it was not working either.

The `detectChanges` works but let's hope beta 9 is available with a fix soon :)

**Comment by Toub** [comment]
I can confirm this hack is not necessary anymore with beta10.
