### ISSUE TITLE
bug(docs): md-paginator overview/examples aren't responsive

### ISSUE THREAD

**Issue by rafaelss95** [angular/material2#5594]
#### Bug, feature request, or proposal:
Bug.

#### What is the current behavior?
Here's how the layout fits in mobile:

![](https://i.stack.imgur.com/0dzeX.png)
![](https://i.stack.imgur.com/dsNJG.png)

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by andrewseguin** [comment]
Fixed in #7610
