### ISSUE TITLE
md-table search

### ISSUE THREAD

**Issue by mbx2015** [angular/material2#5599]
Hello,
Is there any intent to implement a search column feature in the md-table ?
otherwise,  there is any directive that can be customized to implement that ?

thanks

**Comment by m98** [comment]
Angular Material does not offer a specific component for filtering tabular data, the table's data source can be updated based on any custom filter UI. Any filtering pattern need only trigger an update via the table's data source ([Material tables](https://material.angular.io/components/table/overview))
