### ISSUE TITLE
md-table example broken in IE

### ISSUE THREAD

**Issue by mscu** [angular/material2#5601]
#### Bug, feature request, or proposal:

The md-table does not work in IE11 (at least on https://material.angular.io) as the content runs out of the container instead of showing a scrollbar.

#### What is the expected behavior?

Same behavior as in chrome:

![angular_material_-_google_chrome_2017-07-08_12-27-05](https://user-images.githubusercontent.com/545229/27984542-10331c70-63d9-11e7-92c6-d40672e7e807.png)

#### What is the current behavior?

![angular_material_-_internet_explorer_2017-07-08_12-25-55](https://user-images.githubusercontent.com/545229/27984545-14e61466-63d9-11e7-8575-a249f74ddf0d.png)

#### What are the steps to reproduce?

visit https://material.angular.io/components/table/overview with IE11

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

IE11

#### Is there anything else we should know?

I was only testing it on https://material.angular.io so it might only occur there

**Comment by jelbourn** [comment]
@andrewseguin I think this is a bug with the live example
