### ISSUE TITLE
md-table: selection

### ISSUE THREAD

**Issue by mscu** [angular/material2#5602]
#### Bug, feature request, or proposal:

md-table should have a selection feature

#### What is the expected behavior?

https://material.io/guidelines/components/data-tables.html#data-tables-interaction

**Comment by m98** [comment]
Yes! I do agree.

Maybe we can add an attribute that if user wants checkboxes show on the left side of the table

**Comment by jelbourn** [comment]
The philosophy here is that features like this (selection, sorting, pagination, drag-drop) don't fall under the responsibility of the table. The table only cares about rendering rows of cells. What goes _inside_ those cells is up to the user.

We do plan on adding a "simple table" that has these things baked into it, but suspect that most people will want the customization of the `cdk-table` or `md-table`.
