### ISSUE TITLE
Include md-optgroup label in md-select selected item

### ISSUE THREAD

**Issue by larjohn** [angular/material2#5605]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
When `md-select` has some `md-optgroup`'s there might be some options that have the same label. For instance:

Cars
|
--- SUV
----|
--------Diesel
--------Petrol
--- Mini
----|
--------Diesel
--------Petrol

It should be nice if the selected value (when the dropdown is closed) also included the option group label, like SUV-->Diesel

#### What is the current behavior?
Only the option label is shown

#### What are the steps to reproduce?

Use the `md-select` with some `md-optgroup`'s 

#### What is the use-case or motivation for changing an existing behavior?
I know this is the default `select `behavior, but I might see a usability improvement here.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by larjohn** [comment]
Related to https://github.com/angular/material2/issues/2275

**Comment by jelbourn** [comment]
The select trigger label can be fully customized as of #3341
