### ISSUE TITLE
how to configure : following error occures

### ISSUE THREAD

**Issue by jiturddigital2016** [angular/material2#5612]
> mTools@1.0.0 start C:\mTools\mAutomation-B
> tsc && concurrently "npm run tsc:w" "electron ."

node_modules/@angular/cdk/typings/a11y/live-announcer.d.ts(8,10): error TS2305: Module '"C:/mTools/mAutomation-B/node_mo
dules/@angular/core/index"' has no exported member 'InjectionToken'.
node_modules/@angular/cdk/typings/bidi/directionality.d.ts(8,34): error TS2305: Module '"C:/mTools/mAutomation-B/node_mo
dules/@angular/core/index"' has no exported member 'InjectionToken'.
node_modules/@angular/cdk/typings/rxjs/rx-operators.d.ts(11,10): error TS2305: Module '"C:/mTools/mAutomation-B/node_mod
ules/rxjs/Scheduler"' has no exported member 'IScheduler'.
node_modules/@angular/cdk/typings/table/cell.d.ts(8,22): error TS2305: Module '"C:/mTools/mAutomation-B/node_modules/@an
gular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/cdk/typings/table/row.d.ts(28,31): error TS2315: Type 'IterableDiffer' is not generic.
node_modules/@angular/cdk/typings/table/table.d.ts(8,69): error TS2305: Module '"C:/mTools/mAutomation-B/node_modules/@a
ngular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/cdk/typings/table/table.d.ts(8,80): error TS2305: Module '"C:/mTools/mAutomation-B/node_modules/@a
ngular/core/index"' has no exported member 'TrackByFunction'.
node_modules/@angular/material/typings/button-toggle/button-toggle.d.ts(8,22): error TS2305: Module '"C:/mTools/mAutomat
ion-B/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/button/button.d.ts(8,33): error TS2305: Module '"C:/mTools/mAutomation-B/node_mod
ules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/checkbox/checkbox.d.ts(8,81): error TS2305: Module '"C:/mTools/mAutomation-B/node
_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/chips/chip.d.ts(8,47): error TS2305: Module '"C:/mTools/mAutomation-B/node_module
s/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/core/common-behaviors/color.d.ts(9,22): error TS2305: Module '"C:/mTools/mAutomat
ion-B/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/core/common-behaviors/common-module.d.ts(8,10): error TS2305: Module '"C:/mTools/
mAutomation-B/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
node_modules/@angular/material/typings/core/compatibility/compatibility.d.ts(8,22): error TS2305: Module '"C:/mTools/mAu
tomation-B/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
node_modules/@angular/material/typings/core/datetime/date-formats.d.ts(8,10): error TS2305: Module '"C:/mTools/mAutomati
on-B/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
node_modules/@angular/material/typings/core/error/error-options.d.ts(8,10): error TS2305: Module '"C:/mTools/mAutomation
-B/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
node_modules/@angular/material/typings/core/line/line.d.ts(8,10): error TS2305: Module '"C:/mTools/mAutomation-B/node_mo
dules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/core/overlay/overlay-directives.d.ts(8,78): error TS2305: Module '"C:/mTools/mAut
omation-B/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/core/overlay/scroll/scrollable.d.ts(8,49): error TS2305: Module '"C:/mTools/mAuto
mation-B/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/core/placeholder/placeholder-options.d.ts(8,10): error TS2305: Module '"C:/mTools
/mAutomation-B/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
node_modules/@angular/material/typings/core/ripple/ripple.d.ts(8,67): error TS2305: Module '"C:/mTools/mAutomation-B/nod
e_modules/@angular/core/index"' has no exported member 'InjectionToken'.
node_modules/@angular/material/typings/core/selection/pseudo-checkbox/pseudo-checkbox.d.ts(8,22): error TS2305: Module '
"C:/mTools/mAutomation-B/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/core/style/focus-origin-monitor.d.ts(8,65): error TS2305: Module '"C:/mTools/mAut
omation-B/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/datepicker/datepicker-input.d.ts(8,65): error TS2305: Module '"C:/mTools/mAutomat
ion-B/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/datepicker/datepicker-input.d.ts(10,49): error TS2305: Module '"C:/mTools/mAutoma
tion-B/node_modules/@angular/forms/index"' has no exported member 'ValidationErrors'.
node_modules/@angular/material/typings/dialog/dialog.d.ts(8,20): error TS2305: Module '"C:/mTools/mAutomation-B/node_mod
ules/@angular/core/index"' has no exported member 'InjectionToken'.
node_modules/@angular/material/typings/grid-list/grid-list.d.ts(8,50): error TS2305: Module '"C:/mTools/mAutomation-B/no
de_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/grid-list/grid-tile.d.ts(8,10): error TS2305: Module '"C:/mTools/mAutomation-B/no
de_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/icon/icon.d.ts(8,41): error TS2305: Module '"C:/mTools/mAutomation-B/node_modules
/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/input/input-container.d.ts(8,120): error TS2305: Module '"C:/mTools/mAutomation-B
/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/list/list.d.ts(8,51): error TS2305: Module '"C:/mTools/mAutomation-B/node_modules
/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/progress-spinner/progress-spinner.d.ts(8,41): error TS2305: Module '"C:/mTools/mA
utomation-B/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/radio/radio.d.ts(8,59): error TS2305: Module '"C:/mTools/mAutomation-B/node_modul
es/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/select/select.d.ts(8,76): error TS2305: Module '"C:/mTools/mAutomation-B/node_mod
ules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/sidenav/sidenav.d.ts(8,65): error TS2305: Module '"C:/mTools/mAutomation-B/node_m
odules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/slide-toggle/slide-toggle.d.ts(8,84): error TS2305: Module '"C:/mTools/mAutomatio
n-B/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/slider/slider.d.ts(8,47): error TS2305: Module '"C:/mTools/mAutomation-B/node_mod
ules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/snack-bar/snack-bar-container.d.ts(8,43): error TS2305: Module '"C:/mTools/mAutom
ation-B/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/@angular/material/typings/table/cell.d.ts(8,22): error TS2305: Module '"C:/mTools/mAutomation-B/node_module
s/@angular/core/index"' has no exported member 'Renderer2'.

**Comment by Chan4077** [comment]
Can you show your `package.json`?

**Comment by kchoi1998** [comment]
I have the same issue. Here is my package.json:
"dependencies": {
    "@angular/animations": "^4.2.6",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.28.3",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }

**Comment by willshowell** [comment]
@kchoi1998 Angular ^4.0.0 is required as a peer dependency. Upgrade your angular packages and see if the error persists

**Comment by kchoi1998** [comment]
@willshowell it works. thanks so much :)

**Comment by kchoi1998** [comment]
Here is how to upgrade to Angular 4:
npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@latest typescript@latest --save
