### ISSUE TITLE
bug(expansion): toggle icon not being updated

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#5623]
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

If you switch the `expanded` input from false-true-false... the toggle icon on the upper right corner should change it's direction.

#### What is the current behavior?

It's not changing, unless you click on the expansion header

#### What are the steps to reproduce?

At the plunker, click on the **`toggle panel`** button bellow the expansion to switch its state and watch the not-changing toggle icon.

Plunker: https://plnkr.co/edit/SIkVCu?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Programmatically open and close the expansion

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material latest builds

###  `expanded == true`

![image](https://user-images.githubusercontent.com/25405143/27993911-c81c9988-6488-11e7-8ea7-17e0984302c1.png)

###  `expanded == false`

![image](https://user-images.githubusercontent.com/25405143/27993930-025d21ee-6489-11e7-95df-40d6d6367920.png)

**Comment by crisbeto** [comment]
Picking this one up as per chat with @DevVersion.
