### ISSUE TITLE
Can't control Scroll in md-sidenav

### ISSUE THREAD

**Issue by tiancovici** [angular/material2#5627]
#### Bug, feature request, or proposal:
Sidenav could use a function to scroll back to top. Not sure why I can't force it right now

#### What is the expected behavior?
When calling `Window.window.scrollTo(0,0)` I'd expect the page to go back to the top. (note: this is actually a singleton provided by a service in my code, so all components within a heirarchy can control same window. 

#### What is the current behavior?
It doesn't... and only when I say `Window.window.scrollTo(10,0)` it does a subset of the time.

#### What are the steps to reproduce?
I implemented the normal md-sidenav, where we have side navigation content, and main content
But I can't use Window.window.scrollTo(0,0) to force content back to top of page. 

This is how I'm currently setting up in CSS

```
md-sidenav-container {
  height: 100%;
  position:fixed;
}
md-sidenav {
  width: 300px;
  background: white;
}
md-sidenav mat-sidenav {
  height: 100%;
}
html, body, material-app, md-sidenav-container, .my-content {
  margin: 0;
  width: 100%;
  height: 100%;

  transform: initial !important;
}

```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "^4.1.3",
    "@angular/cli": "^1.2.0",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/compiler-cli": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/material": "^2.0.0-beta.7",

**Comment by crisbeto** [comment]
You have to set the `scrollTop` of the `md-sidenav-container`.

**Comment by macjohnny** [comment]
@tiancovici you need to set it on the dom element

**Comment by tiancovici** [comment]
Solved
I inspected it, turns out there's a div inside MdSidenavbar with cdk-scrollable

![screen shot 2017-07-24 at 7 14 29 pm](https://user-images.githubusercontent.com/5238077/28551436-f89a64ee-70b5-11e7-8baf-f3c9a0fc4257.png)

So added following line in controller (component.ts)
document.querySelector('[cdk-scrollable]').scrollTop = 0;
