### ISSUE TITLE
Including Material Design Components globally in application

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#563]
Is there any way to add MD components globally so that we don't have to include it on each components.

I tried adding it to bootstrap, but when I add any of the MD component in my component's template it doesn't render that component, neither it display any error. Seems like its unable to recognize the component:

```
bootstrap(AccountComponent, [
    ROUTER_PROVIDERS,
    ROUTER_DIRECTIVES,
    HTTP_PROVIDERS,
    MdButton,
    MD_CARD_DIRECTIVES,
    MD_CHECKBOX_DIRECTIVES,
    MD_GRID_LIST_DIRECTIVES,
    MdIcon,
    MD_INPUT_DIRECTIVES,
    MD_LIST_DIRECTIVES,
    MD_PROGRESS_BAR_DIRECTIVES,
    MD_PROGRESS_CIRCLE_DIRECTIVES,
    MD_RADIO_DIRECTIVES,
    MdSidenavLayout, MdSidenav,
    MD_SLIDE_TOGGLE_DIRECTIVES,
    MD_TABS_DIRECTIVES,
    MD_TOOLBAR_DIRECTIVES,
    MdIconRegistry,

    provide(PLATFORM_PIPES, { useValue: [JSONToDate], multi: true }),
    provide(RequestOptions, { useClass: DefaultRequestOptions }),
    provide(Http, {
        useFactory:
        function (backend, defaultOptions) {
            return new Http(backend, defaultOptions);
        },
        deps: [XHRBackend, RequestOptions]
    })
]);
```

**Comment by m0t0r** [comment]
@naveedahmed1 you cannot include components globally because each component containing another components (e.g you custom component contains material2 components) should explicitly declare them in a `directives` array, that's what Angular2 requires.
```js
@Component({
  selector: 'my-component',
  template: ...
  directives: [MD_CARD_DIRECTIVES, AnotherCustomComponent]
})
```
You can check [Tour of Heroes](https://angular.io/docs/ts/latest/tutorial/toh-pt3.html) for more explanation.

**Comment by naveedahmed1** [comment]
Thanks, Got it!
