### ISSUE TITLE
Link Fab Buttons incorrect line height

### ISSUE THREAD

**Issue by amcdnl** [angular/material2#5632]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The line height would match the default button line height.

#### What is the current behavior?
The line height is not correct.

![img](https://content.screencast.com/users/amcdaniel22/folders/Snagit/media/2725ddd8-07ee-4a8a-8f93-21e06bfb99ac/2017-07-09_10-32-13.png)

#### What are the steps to reproduce?
- Create a link fab button
- Create a button fab button
- Compare result

https://plnkr.co/edit/Is54mCs52Cd9eL2ollrZ?p=preview

**Comment by m98** [comment]
@amcdnl Maybe we should add an absolute position to  `mat-button-wrapper` and add the relative position to its parent, and it's easy to put it in the center!
