### ISSUE TITLE
MdButton Vs MD_BUTTON_DIRECTIVES

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#564]
Hi,

Can anyone please guide whats the difference between MdButton  and MD_BUTTON_DIRECTIVES and which one of them should be used.

For most of the components, when I import and add MD components with pattern:
MD_BUTTON_DIRECTIVES it works, but it doesn't work for MD_ICON_DIRECTIVES.

In case of Md Icons, I have to import MdIcon, MdIconRegistry and then have to add MdIcon as directive and MdIconRegistry as providers.

Any guidance about this would be highly appreciated.

**Comment by fxck** [comment]
https://github.com/angular/material2/blob/master/src/components/button/button.ts#L138

**Comment by jelbourn** [comment]
GitHub issues are for bugs / feature requests. Please direct questions to the mailing list or gitter.
