### ISSUE TITLE
md-datepicker select the good day but shows an other month when show calendar popup

### ISSUE THREAD

**Issue by gillouxxx** [angular/material2#5640]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

When I open the calendar of the datepicker, it needs to show me the month of the selected day.

#### What is the current behavior?

When I open the calendar, it shows me octobre month instead of July but the day of the 10th of July is selected (today).

#### What are the steps to reproduce?

Set Windows in French and start the following plnkr :
https://plnkr.co/edit/ucGODHnqlaRi7IgoJNmt?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I am using the version 2.0.0-beta7 of material.

**Comment by julianobrasil** [comment]
The date adapter was built to be very flexible. The price to pay (ver low in my opinion) is that you have to built a DateAdapter to make it work the way you want.

You can extends and customize the Material provided NativeDateAdapter if you're using the JS Date object, to parse the date correctly if your locale represent dates different from MM/dd/yyyy. See the [material docs](https://material.angular.io/components/datepicker/overview) to learn about it (the three or four last topics). 

Also see this discussion: #5185

See this plunker for Brazilian Portuguese: http://plnkr.co/edit/jc4Ywu?p=preview

**Comment by gillouxxx** [comment]
Ok thank you. Everything is working now.
