### ISSUE TITLE
Make expansion panel height configurable

### ISSUE THREAD

**Issue by jbojcic1** [angular/material2#5641]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Height of the md-expansion-panel-header should be configurable.

#### What is the current behavior?
Currently there is no way of doing it. I can only override it in css with important but then there is no animation.

#### What are the steps to reproduce?
Open material demo app and see expansion panel header.

#### What is the use-case or motivation for changing an existing behavior?
Custom header height.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
-

**Comment by agustinhaller** [comment]
I'm facing the same issue, any news about this (ref: https://github.com/angular/material2/blob/73c6d8d75712ed32cee2b624356d191662f2553e/src/lib/expansion/expansion-panel-header.ts#L68)?

**Comment by TqrHsn** [comment]
<mat-expansion-panel-header [expandedHeight]="48px">
gives:
![snip_20171227005507](https://user-images.githubusercontent.com/20878328/34363817-29bfe26e-eaa1-11e7-883a-c6671449e3ac.png)

<mat-expansion-panel-header [expandedHeight]="48">
gives:
![snip_20171227005610](https://user-images.githubusercontent.com/20878328/34363823-39087fb0-eaa1-11e7-9efa-91daeee0f50a.png)

unable to use this. Am I missing something?

**Comment by crisbeto** [comment]
Your first example is invalid @TqrHsn. You should use `[expandedHeight]="'48px'"` or `expandedHeight="48px"`.
