### ISSUE TITLE
md-input-container with md-prefix produces unexpected DOM

### ISSUE THREAD

**Issue by parker-mike** [angular/material2#5643]
Bug,
`<md-input-container>
      <span md-prefix>
          <md-icon>home</md-icon>
      </span>
      <input mdInput name="givenName" readonly disabled>
  </md-input-container>`
gives wrong DOM, `div.mat-input-prefix` is empty while the `span.md-prefix` is generated inside `div.mat-input-infix`
could be seen on the following plnkr:
http://plnkr.co/edit/WRtJEaWx0ilHPBeGLSM5?p=preview
which is regression from beta.6 on 4.1.3:
http://plnkr.co/edit/dGxYTBaObsjDs557jM4k?p=preview

**Comment by willshowell** [comment]
`mdPrefix` works instead of `md-prefix` though I don't [totally understand it](https://github.com/angular/material2/blob/master/src/lib/input/input-container.ts#L105-L109)
