### ISSUE TITLE
md-datatable inside md-card has unexpected padding

### ISSUE THREAD

**Issue by taokakao** [angular/material2#5644]
#### Bug

md-datatable inside md-card has padding from left and right side which is not like in Material spec.

<img width="942" alt="screen shot 2017-07-10 at 19 06 37" src="https://user-images.githubusercontent.com/1310147/28027749-effec74e-65a2-11e7-898c-0e58d876990f.png">

#### What is the expected behavior?

No padding.

#### What is the current behavior?

md-datatable inside md-card has padding from left and right side which is not like in Material spec.

**Comment by avelka** [comment]
You can use the md-card-image attribute to get rid of them
`
<md-card class="wide-card">
    <md-table #table [dataSource]="sources" md-card-image mdSort>
`

**Comment by taokakao** [comment]
@avelka thanks! As a hack works perfectly!
