### ISSUE TITLE
missing @angular/cdk - peerDependencies are ignored in npm 5+

### ISSUE THREAD

**Issue by maciejtreder** [angular/material2#5646]
#### Bug
As far as I know `peerDependencies` are deprecated since npm 3, and removed in npm 5 (when I am installing project, peerDependencies are ignored - ie @angular/cdk).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
npm -v
5.0.3

**Comment by jelbourn** [comment]
Peer dependencies are not deprecated, npm just doesn't install them automatically. 

http://blog.npmjs.org/post/110924823920/npm-weekly-5

> We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies.
