### ISSUE TITLE
md-radio labelPosition doesn't do anything

### ISSUE THREAD

**Issue by gizm0bill** [angular/material2#5651]
BUG

[labelPosition] inputs of radio buttons or groups should have some effect...?

https://plnkr.co/edit/kc9Eyzlgdc5QeLyHgKTC?p=preview

**Comment by benb7760** [comment]
Remove the square brackets. With the brackets there, you are attempting to bind to variables called 'before' and 'after'. [see here](https://angular.io/guide/template-syntax#property-binding--property-)

**Comment by gizm0bill** [comment]
ah right sorry
