### ISSUE TITLE
Bug: Snackbar missing public action method for custom snackbars

### ISSUE THREAD

**Issue by mtpultz** [angular/material2#5657]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Be able to close a custom snackbar using a public method to indicate action was used, and allow for use of `onAction` observable

#### What is the current behavior?
When you create a custom snackbar using `openFromComponent` you can pass in a snackBarRef and invoke any methods on self, but there is no public version of `_action()` so if you create a component and a user clicks your action you have to use a private method to be able to distinguish an action/dismiss or just a dismiss

#### What are the steps to reproduce?
N/A missing API call

#### What is the use-case or motivation for changing an existing behavior?
Snackbar's have two ways they can be closed, but right now in order to use the `onAction` observable you need to invoke a private method `_action()`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.5, Angular Materila 2.0.0-beta.8, Windows 10

**Comment by willshowell** [comment]
Looks like this was done intentionally https://github.com/angular/material2/pull/1826#discussion_r87636817, but your use case absolutely makes sense.

@jelbourn?

**Comment by jelbourn** [comment]
Good point. I would change the method name to `closeWithAction` if we make it public.

**Comment by mtpultz** [comment]
@willshowell @jelbourn is there any reason not to send a value back through to `onAction` using `closeWithAction(data)`.  I noticed the new API for snackbars in master now has injectable data (https://github.com/angular/material2/blob/master/src/lib/snack-bar/snack-bar.md#sharing-data-with-a-custom-snack-bar) that now reflects dialogs, but doesn't have a way to provide response data like a dialog does using `close(data)`.

**Comment by jelbourn** [comment]
Snackbars are meant to provide a notification with exactly one optional action. Adding the option for getting _data_ from a snackbar would go against the intended use of the component per Material Design spec.
