### ISSUE TITLE
Provide a way to configure global options for MdDialog

### ISSUE THREAD

**Issue by rafaelss95** [angular/material2#5664]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Actually, you can configure a global default placeholder for inputs. It'd be good if we have this functionality in dialogs (maybe in snackbar also?) to configure some properties like `disableClose`, `height`, `width` and so on...

**Comment by CDDelta** [comment]
I want to take this but I have a few questions. Should options like panelClass and backdropClass be included? If so, should classes from the global options be appended to the options specified on open or should they be overwritten?
