### ISSUE TITLE
demo-app: Add link to app source

### ISSUE THREAD

**Issue by laco0416** [angular/material2#5668]
#### Bug, feature request, or proposal:

Feature request

Material Demo App (https://material2-dashboard.firebaseapp.com) is a great example but there aren't any links to see its source code.

#### What is the expected behavior?

At least add link to `angular/material2/src/demo-app`. If possible, add a link for each all demo page.

**Comment by jelbourn** [comment]
That's not a demo app, that's just our team dashboard. 

The thing in the source called `demo-app` is also not meant to be a real "demo" app, but is just what we use for development. https://github.com/angular/material.angular.io/ is what we actually intended to serve as an example app.
