### ISSUE TITLE
md-tabs which are not active doesn't respond to animation-triggers

### ISSUE THREAD

**Issue by JakobSegerslatt** [angular/material2#5669]
#### Bug, feature request, or proposal:
md-tabs should show the correct animation state when navigated to.

#### What is the current behavior?
The tab which is not active initially does not show the correct animation state

#### What are the steps to reproduce?
Set an animation trigger inside a tab which is not active, the element will not show styles from the right state.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker: http://plnkr.co/edit/QMN5tUzN1JWjmQWQu48H

#### What is the use-case or motivation for changing an existing behavior?
Better use of animations in tabs that are not active from the start.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/cli": "^1.2.0",
"@angular/material": "2.0.0-beta.8",
"@angular/core": "^4.3.0-beta.1",
"typescript": "~2.3.4",

Chrome

**Comment by julianobrasil** [comment]
#5269 is related to this.

**Comment by JakobSegerslatt** [comment]
Ah yes, sorry for not replying, this can be closed in favor of #5269 .
