### ISSUE TITLE
Ripple Issue with Check boxes and Radio Buttons

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#567]
Hi,

When we click the Checkbox, or a Radio, it display a ripple across the control,  the ripple animations works fine except it doesn't disappear on completion of animation.

**Comment by zahlprish** [comment]
I have started experiencing this issue since alpha 5, too. The check box has also been firing twice per click since alpha 5.
<img width="200" alt="screen shot 2016-05-28 at 2 33 11 pm" src="https://cloud.githubusercontent.com/assets/8344056/15629557/44691c84-24e1-11e6-8106-7cecef06fcf3.png">

**Comment by jelbourn** [comment]
This is the focus state for the checkbox / radio. It will be changed when we have an implementation for ripples.

**Comment by phiphou** [comment]
@zahlprish you can temporally "disable" it by CSS

```
.md-ink-ripple {
  display: none
}
```
