### ISSUE TITLE
Image carousel component

### ISSUE THREAD

**Issue by HegdeSach** [angular/material2#5671]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Carousel component is a slideshow for cycling through a series of images.

Features : 

1.  Fit images inside carousel slide by maintaining aspect ratio
2.  Place image at the center of the slide (Looks good if the image is too small compare to slide)
3.  Navigation control to change the slide
4.  View indicators to show current slide, total no of slides
5.  Loop variable to handle whether to allow slide change in loop
6.  Autoplay of slides. Autoplay should stop on user interactivity
7.  Slide change on mouse scroll on slides

Carousel takes following inputs,
slides : array of object contains image path,alt text and caption for the image
slideHeight : Carousel slide height
slideWidth : Carousel slide width
startIndex : index number to show perticular slide onload of carousel (Optional)
view : slide indicators (Fraction, Dots and None)
loop : allows infinite slide scrolling (Optional)
show/hide nav control (Optional)
autoplay (Optional)
Mouse scroll slide change (Optional)

Methods:
showPrevSlide()
showNextSlide()
showSlide(index)

Events:
slideChange
slideClick
autoplayStart
autoplayStop

#### Is there anything else we should know?
Can I get design principle for the Carousel component?

I have taken care of the above features. Can't I contribute in building this for Angular material?

**Comment by briancvn** [comment]
Hope is like: http://idangero.us/swiper/demos/#.WWSMLoVOJaQ

**Comment by willshowell** [comment]
https://github.com/angular/material2/issues/1081

**Comment by jelbourn** [comment]
We have no plans to add any kind of carousel component.

**Comment by pranaymokal** [comment]
how can you compete with bootstrap then

**Comment by SiyabongaNzulwana** [comment]
Is it possible to have a carousel that takes different items but in the same carousel

**Comment by shivarajnaidu** [comment]
is there any reason to not to add one ?

**Comment by rubenheymans** [comment]
we can use slick or glide, a small angular guide would be nice though

**Comment by odahcam** [comment]
I'm using Swiper, but a carousel based on CDK touch events would be like MUCH smaller in bundle size than Swiper.

@pranaymokal Bootstrap's carousel is bulls**it, owlCarousel works and looks better with Bootstrap than their own.

**Comment by stasberkov** [comment]
You get carousel if you hide tab-header in tab control (keeping tab body only).
