### ISSUE TITLE
Tooltip : render HTML

### ISSUE THREAD

**Issue by Robouste** [angular/material2#5672]
Hi, 

Is there a way to render HTML inside the tooltip ? In my case, I would like to render some `<br/>` tags but it's not working. 

How can I render the br ?

**Comment by bebelz** [comment]
HTML is not supported in tooltips for now but you can replace `<br/>` with `\n` and override your css with :
```
.mat-tooltip {
  white-space: pre-line;
}
```

**Comment by Robouste** [comment]
I didn't know that css rule, it did the trick.

Thank you :)

**Comment by willshowell** [comment]
@Robouste for completeness:

1. HTML [won't be supported](https://github.com/angular/material2/issues/5440#issuecomment-313740211) in tooltips
2. If you don't want to add css to *all* tooltips in your application, you can customize them individually with [`mdTooltipClass`](https://material.angular.io/components/tooltip/api)

**Comment by mackelito** [comment]
@willshowell I understand that it will not be supported due to Material Design Spec.
But as a note.. the spec are guidelines and not meant to be enforced ;)

I have no need for this feature but I do understand that there are requests for it as it is pretty common in other frameworks

**Comment by Robouste** [comment]
Yes it could be pretty useful in some cases.

Thank for the completness

**Comment by DavidVotrubec** [comment]
Seems that the directive for css class is now `matTooltipClass`

**Comment by chriszrc** [comment]
Any clever way to get bullets in there too?

**Comment by chriszrc** [comment]
We can even get bullets in there with utf8 codes:

https://www.fileformat.info/info/unicode/char/2022/index.htm
