### ISSUE TITLE
regression - sidenav first animation skipped

### ISSUE THREAD

**Issue by amitport** [angular/material2#5673]
#### Bug, feature request, or proposal:
the first sidnav animation is skipped when used inside a route

#### What is the expected behavior?
should animate

#### What are the steps to reproduce?
http://plnkr.co/edit/b8e2dBj4K4PrYHKBBxa5

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.2.6
material 2.0.0-beta.8
chrome 59
TypeScript 2.3.3

#### Is there anything else we should know?
not reproduced with angular 4.1
after the first sidenav close/open, animations work properly

**Comment by grizzm0** [comment]
`.mat-sidenav-transition` doesn't get added to `md-sidenav-container`.
Seems to be related to this row https://github.com/angular/material2/blob/e488e3fa24b3f8f1f22a6493df634842554650f7/src/lib/sidenav/sidenav.ts#L388

**Comment by peluprvi** [comment]
I was having the same behavior and it fixed after updating to the new master https://github.com/angular/material2/commit/a34787df5a866eb394426509bf6b0550f5615c51.
