### ISSUE TITLE
mdTextareaAutosize doesn't set amount of rows to one in Firefox

### ISSUE THREAD

**Issue by rodaz** [angular/material2#5674]
Similar #4852 
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Textarea should be resized to a single line.

#### What is the current behavior?
Resize doesn't shrink textarea to a single line, stops at minimum of two lines.

#### What are the steps to reproduce?
Plunker template: https://plnkr.co/edit/BGAwyS?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.2.6
Material: 2.0.0-beta.8
OS: Win10
Browser: Mozilla Firefox 54.0.1

#### Is there anything else we should know?
In Chrome everything works fine, bug only in Firefox.

**Comment by DevVersion** [comment]
I tried to reproduce it with Firefox 54.0.1 but I was not able to see the issue.

Is there anything specifically I need to do, in order to see the issue?

**Comment by rodaz** [comment]
I don't now how it possible, but neither i now have it.
