### ISSUE TITLE
Error during production build (When i installed the latest stable nodejs 6.11.0)

### ISSUE THREAD

**Issue by gtzinos** [angular/material2#5677]
Hi,
I upgrade my nodejs version from 6.10.3 to 6.11.0 and now i can't build to production. Please check the error message:

ERROR in Error encountered resolving symbol values statically. Could not resolve @angular/cdk relative to C:/Users/George Tzinos/Desktop/projects/my_app_name/node_modules/@angular/material/typings/index.d.ts., resolving symbol MdCoreModule in C:/Users/George Tzinos/Desktop/projects/my_app_name/node_modules/@angular/material/typings/index.d.ts, resolving symbol MdCoreModule in C:/Users/George Tzinos/Desktop/projects/my_app_name/node_modules/@angular/material/typings/index.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\George Tzinos\Desktop\projects\my_app_name\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

My packages:

`
{
  "name": "my_app_name",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/flex-layout": "latest",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/material": "^2.0.0-beta.7",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/router": "^4.1.3",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "material-design-icons-iconfont": "^3.0.3",
    "roboto-fontface": "^0.7.0",
    "ng2-cookies": "^1.0.12",
    "primeng": "^4.1.0-rc.2",
    "rxjs": "^5.1.0",
    "zone.js": "0.8.10",
    "angular2-websocket": "^0.9.2"
  },
  "devDependencies": {
    "@angular/cli": "1.1.3",
    "@angular/compiler-cli": "^4.1.3",
    "@types/jasmine": "2.5.49",
    "@types/node": "~7.0.23",
    "codelyzer": "~3.0.1",
    "jasmine": "^2.5.3",
    "jasmine-core": "~2.6.1",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "protractor-browser-logs": "^1.0.350",
    "ts-node": "~3.0.4",
    "tslint": "~5.2.0",
    "typescript": "~2.3.2"
  }
}

`

As you can see i am using material 2 beta-7 and it installs the beta-8.

**Comment by willshowell** [comment]
Looks like your `^2.0.0-beta.7` of material is installing beta.8 which [now depends on `@angular/cdk`](https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes) as a peer dependency

**Comment by gtzinos** [comment]
Yes, but what if i don't need to change to beta-8 ?

**Comment by gtzinos** [comment]
I changed 

"@angular/material": "^2.0.0-beta.7", 
to 
"@angular/material": "2.0.0-beta.7",

for nodejs 6.11.0

**Comment by vydyas** [comment]
you guys saved my time alot
