### ISSUE TITLE
@include of sass into a limited scope

### ISSUE THREAD

**Issue by niklr** [angular/material2#5678]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Including the common styles for Angular Material and the theme styles into a limited scope should be possible without breaking some of the components such as md-tooltip, md-menu and maybe others.

#### What is the current behavior?
The components such as md-tooltip and md-menu are not displayed correctly (maybe other components are affected as well).

![angular-material-issue-5678](https://user-images.githubusercontent.com/4712166/28070753-53a66bac-664e-11e7-93a3-f9af9bd7d0fe.PNG)

#### What are the steps to reproduce?
http://plnkr.co/edit/3HmHylAPSDOiPp93Tbgf?p=preview

Creating a angular-material-theme.scss file as described here: https://github.com/angular/material2/blob/master/guides/theming.md

Applying the scope:
.angular-material-datatransfer {
    @include mat-core();
}
.angular-material-datatransfer {
    @include angular-material-theme($candy-app-theme); 
}

[angular-material-theme.zip](https://github.com/angular/material2/files/1138989/angular-material-theme.zip)

#### What is the use-case or motivation for changing an existing behavior?
Scoping of any styles should be possible?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "^4.1.2",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.1.2",
    "@angular/compiler": "^4.1.2",
    "@angular/core": "^4.1.2",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.1.2",
    "@angular/http": "^4.1.2",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^4.1.2",
    "@angular/platform-browser-dynamic": "^4.1.2",
    "@angular/router": "^4.1.2",

#### Is there anything else we should know?
Thanks for the great work!

**Comment by jelbourn** [comment]
this is working as intended; `mat-core()` is required to be included globally. You can use the `themeClass` on `OverlayContainer` to add a class for things like tooltip, menu, etc.
