### ISSUE TITLE
Feature Req: Flex-Layout Responsive API with attributes of Material Components

### ISSUE THREAD

**Issue by bogacg** [angular/material2#5679]
#### Feature Request:

Ability to use Flex-Layout Responsive API with appropriate attributes of Material Components.

#### What is the expected behavior?

`<md-toolbar color.xs="primary" color.gt-xs="active">`  could change color in respective window sizes for example.

#### What is the current behavior?

No effect / non-existent

#### What is the use-case or motivation for changing an existing behavior?

Having different styles set to theme's different values with Responsive API might be useful to accentuate some components on different sizes.

**Comment by jelbourn** [comment]
This isn't something we plan to do right now. Angular has no built-in capacity for this dot notation, so it would vastly balloon the number of inputs.
