### ISSUE TITLE
Make the Ripple Effect Available so that it can be added on any element if required

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#568]
Hi,

Is the ripple effect available as a independent directive as well? If not, wouldn't it be great, to have it as a separate directive as well so that we can apply it on any element whenever required.

**Comment by DevVersion** [comment]
The Ripple effect is currently just temporary. Once the real ripple effect will be available, you should be able to use the given TypeScript class. 

In meanwhile, I think this issue can be closed.

**Comment by naveedahmed1** [comment]
Thank you so much for the update Paul.
