### ISSUE TITLE
MdToolbarModule: Material shadow for toolbar

### ISSUE THREAD

**Issue by m98** [angular/material2#5688]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
Material shadow for the toolbar, users might write their own styles to simulate Material shadow for the toolbar, but it would be better if we can define it and users can just activate it easily.
![Material toolbar shadow](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B9PCOJnbdRP6NVBZNXNqTi1EekU/layout_principles_papercraft_toolbars4.png)
([source](https://material.io/guidelines/components/toolbars.html#))

#### What is the current behavior?
(as far as I know) there is not any shadow for the toolbar

[Current Angular Material Toolbar](https://material.angular.io/components/toolbar/examples)

#### What is the use-case or motivation for changing an existing behavior?
To follow Material rules, and provide high-quality shadow (as Material describe) for toolbar

**Comment by willshowell** [comment]
It's as easy as `class="mat-elevation-z*"` where * is 0..24

https://plnkr.co/edit/w9eFAtAyksvxuSYKGYw1?p=preview

**Comment by m98** [comment]
Then I can close the issue! 

I did not know about the `mat-elevation-z* ` class! 

Thanks
