### ISSUE TITLE
Unhandled Promise rejection: Failed to load

### ISSUE THREAD

**Issue by mtr986** [angular/material2#5689]
[Hi, I am getting unhandled and live server not responding due to mdc.select.min.css find in @material>select. the following issue started out of blue just by restarting the computer. i can see in the file structure of @material that mdc.select.min.css should be in select>dist folder. but still getting the error. I have spent 4 hours with no luck.

Failed to load resource: the server responded with a status of 404 (Not Found)

:4200/node_modules//dist/mdc.select.min.css Failed to load resource: the server responded with a status of 404 (Not Found)

polyfills.bundle.js:3057 Unhandled Promise rejection: Failed to load ../../../../../node_modules//dist/mdc.select.min.css ; Zone: ; Task: Promise.then ; Value: Failed to load ../../../../../node_modules//dist/mdc.select.min.css undefined

api.onUnhandledError @ polyfills.bundle.js:3057
polyfills.bundle.js:3059 Error: Uncaught (in promise): Failed to load ../../../../../node_modules//dist/mdc.select.min.css

at resolvePromise (polyfills.bundle.js:3184)
at resolvePromise (polyfills.bundle.js:3155)
at polyfills.bundle.js:3232
at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.bundle.js:2838)
at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (polyfills.bundle.js:2605)
at drainMicroTaskQueue (polyfills.bundle.js:2998)
at XMLHttpRequest.ZoneTask.invoke (polyfills.bundle.js:2904)
api.onUnhandledError @ polyfills.bundle.js:3059
](url)

**Comment by willshowell** [comment]
As @jelbourn mentioned in your other issue, this is not the right project. material2 has no files named `dist/mdc.select.min.css` whereas material-components-web [clearly does](https://github.com/material-components/material-components-web/blob/master/README.md#css).

If you insist there is an issue with this project, you should follow the issue template and supply a reproduction.
