### ISSUE TITLE
md-tabs should emit changes when focus/select changes

### ISSUE THREAD

**Issue by DennisSmolek** [angular/material2#569]
**Feature:**

In the current tabs component there is the function `set focusIndex(value: number)` that would be easy to tap into for an EventEmitter.

Simply adding an `@Output` of say `focusChanged` would allow other components/services to listen to when the tabs changed.

This would mean you could fire a `location.go()` or `mySpecialLogger()` whenever the user navigates..

**Comment by jelbourn** [comment]
@DennisSmolek we are going to have a separate component just for using tabs to change the route (see #524), but there should also be events for changing tabs.

**Comment by davidanaya** [comment]
Hi!

What about the other way around? I have an md-tab-group with <a [routerLink]...> in every md-tab which works fine and loads properly in a <router-outlet> in the same component, but I can also navigate to this tabs (router.navigate) when clicking in elements in a list, and that should also update the selected panel

Is there any obvious way to achieve this? I could update the [selectedIndex] every time I navigate but that doesn´t look very good. I thought about emiting an event myself (selectChange) but not sure this is feasible either.

Thanks!
