### ISSUE TITLE
Typescript peer dependency

### ISSUE THREAD

**Issue by willshowell** [angular/material2#5690]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`typescript: ^2.2.0` listed as a peer dependency

#### What is the use-case or motivation for changing an existing behavior?
Lots of issues being opened are solved by upgrading typescript.

Currently the angular docs suggest using the [quickstart](https://github.com/angular/quickstart) to work through the TOH tutorial. The quickstart specifies `typescript: ~2.1.0`, and new users that finish the tutorial and want to transition into testing material are going to hit all sorts of cryptic errors and be discouraged.

AFAIK the only ways to discover the dependency are to read back through the changelog or find it mentioned in old issues.

**Comment by tytskyi** [comment]
the `~` is the must, since typescript does not follow semantic version and make breaking changes each minor release

**Comment by jelbourn** [comment]
We typically follow what core does for things like this, so @IgorMinar

**Comment by IgorMinar** [comment]
Now that cli is becoming the main way to build Angular apps, the quickstart is being phased out it. The cli sets up the peer deps correctly and is kept up to date.

Additionally, Material doesn't require typescript to be useful, it requires angular core, `@angular/compiler-cli` does and it currently specifies typescript ^2.0.2  as the peer dep. I'm going to send a PR to update the typescript version there.
