### ISSUE TITLE
md-tab-body height doesn't collapse height properly

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#570]
Consider the following template:
```
<md-tab-group>
  <md-tab>
    <template md-tab-label>Label</template>
    <template md-tab-content>
      Any object shorter than 199px
    </template>
  </md-tab>
</md-tab-group>
<div>footer text</div>
```
The generated html puts the tab contents inside a `<div class="md-tab-body">`.  Problem is that this div is always at least 199px in height.  This poses problems when my content is meant to take very little height in the browser positioning logic.  In the example above, notice how much blank space there is between the content and the footer

![15](https://cloud.githubusercontent.com/assets/12346501/15630945/c510f6f8-251e-11e6-9fe3-56f2f33a5a6b.png)

My specific user case is that within the tab pane I have a content-div whose aspect ratio needs to remain fixed. I've been using  [the solution from this post](http://stackoverflow.com/questions/1495407/maintain-the-aspect-ratio-of-a-div-with-css). It has been working well until I attempted to put the content in the new `md-tab` directive. Now, the bottom padding of the container-div no longer respects the limit set in CSS `padding-bottom` rule and I can't figure out why.

**Comment by jelbourn** [comment]
@robertmesserle is this the expected behavior?

**Comment by sendilkumarn** [comment]
Also why the default min height is set to 200px for tabs and 48 px for heading? 

Shouldn't it be auto rather?
