### ISSUE TITLE
[Bug] Datepicker showed date is not the same format as written

### ISSUE THREAD

**Issue by raugaral** [angular/material2#5700]
#### Bug, feature request, or proposal: 
Bug

#### What is the expected behavior?
Select a date using the calendar, show date format dd/mm/yyyy.
Written date using format dd/mm/yyyy should be accepted.

#### What is the current behavior?
Written date using format dd/mm/yyyy is not accepted, the only valid format is mm/dd/yyy.

#### What are the steps to reproduce?
[At the docs website.](https://material.angular.io/components/datepicker/overview)
![image](https://user-images.githubusercontent.com/1770795/28106846-ca4aab28-66e5-11e7-8d9c-7d4090ed78a9.png)
Select a date in the calendar, the format is dd/mm/yyyy. That is correct.
![image](https://user-images.githubusercontent.com/1770795/28106879-e04b16ba-66e5-11e7-9b55-0b1c9fbe653f.png)

But, if i write a date manually, the date is not in accepted as valid and the ngModel is empty.
![image](https://user-images.githubusercontent.com/1770795/28106943-118f5970-66e6-11e7-8d5c-6f97c45407a6.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.6
@angular/material@2.0.0-beta.8
typescript@2.3.4
OS: Ubuntu 17.04
Google Chrome 59.0.3071.115 (Build oficial) (64 bits)

#### Is there anything else we should know?
I'm using the locale id de-DE in my app module
    { provide: LOCALE_ID, useValue: "de-DE" }

**Comment by julianobrasil** [comment]
This is not a bug. You must build a custom date adapter. 

Take a look at this plunk for brazilian portuguese (same date format as you want): https://plnkr.co/edit/jPZWMB?p=preview

Also it's explained in more details [over here](https://stackoverflow.com/a/45020144/6433166).

**Comment by jelbourn** [comment]
What @julianobrasil said

**Comment by raugaral** [comment]
That doesn't help. It's not posible override a private function.

Class 'CustomDateAdapter' incorrectly extends base class 'NativeDateAdapter'. Types have separate declarations of a private property '_createDateWithOverflow'.

**Comment by julianobrasil** [comment]
@raugaral, the `_createDateWithOverflow` isn't overriding anything. It's a function of the CustomDateAdapter class only. I just copied that of the NativeDateAdapter because I liked the organzations of the functions over there (in fact it's so tiny that you can put all it's logic inside the `createDate`, which is, in fact, the one that must be overriden).
