### ISSUE TITLE
[Problem with css]

### ISSUE THREAD

**Issue by Imbibed** [angular/material2#5701]
#### Bug, feature request, or proposal:
I installed angular material 2 in my CLI project, but I think i have some trouble with css because i don't see colors like i saw on demo website angular material 2 and the css for 'md-list' doesn't work at all.
At the begining, I was thinking it was just because of angular material 2 is still in beta but i think i did a mistake or I missing something.

#### What is the expected behavior?
Same result like on demo website angular material 2 https://material.angular.io/

#### What is the current behavior?
It seem angular material 2 css doesn't work on all tags.
Doesn't work on <md-list> and half working on <md-toolbar> (default theme doesn't work).

#### What are the steps to reproduce?
I followed the get started here https://material.angular.io/guide/getting-started
I did all the steps except when i have to import hammerjs just after doing npm install --save hammerjs. I don't know in which file import hammerjs and the exact line to write.
I try to change the place where I call css theme but no results.

Currently, i use this @import "~@angular/material/prebuilt-themes/indigo-pink.css"; in style.css call by .angular-cli.json but doesn't work and i tried to call it since index.html and no result.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm on windows 7, i tried to launch my app with firefox and chrome (same result) and these to browser are updated.
Here package.json:

{
  "name": "routing-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.0",
    "@angular/animations": "^4.0.0",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.7",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "chart.js": "^2.6.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "ng2-charts": "^1.6.0",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.2.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

#### Is there anything else we should know?
Angular material is for me the best graphic tool for angular and i would like to use it. But if my problem is just due to angular material is still in beta. Ok i can wait or help to fix it.
Do you have other graphic tool? i tried primeNG (not with success) and material design lite but Angular Material is really the best.

**Comment by julianobrasil** [comment]
@Imbibed, there's a real nice getting-started project project in [this repo](https://github.com/EladBezalel/material2-start), written by @EladBezalel and @DevVersion. It's worth giving it a try.

**Comment by Imbibed** [comment]
thanks Juliano i will try this and take exemple :-)

**Comment by Imbibed** [comment]
I have to do 'npm install -g git' to download dependencies with npm install ? because juste npm install doesn't work...

**Comment by julianobrasil** [comment]
No, just `npm install` after you done `git clone https://github.com/EladBezalel/material2-start.git`. Do you have the minimum setup installed in your machine (nodejs, typescript, angular-cli and git)?

**Comment by Imbibed** [comment]
I don't have git, I will install it

**Comment by Imbibed** [comment]
Ok your project works very well, I think i will use it. But it is sad to follow the get started guide and arrive to an app who doesn't work... And with that I don't know why it doesn't work. I saw that I didn't use MaterialModule and its a little bit better now but not enough yet :'(
thanks again Juliano have nice day !

**Comment by julianobrasil** [comment]
Your're welcome. But the credit goes entirely to @EladBezalel and @DevVersion. It's not a project of mine.

**Comment by Imbibed** [comment]
Good thank you I follow them now.
