### ISSUE TITLE
Date focus not available

### ISSUE THREAD

**Issue by Sevensnake** [angular/material2#5705]
#### Bug, feature request, or proposal:
In Angular1 you had onfocus when you click on the field. Is this possible with this version.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by julianobrasil** [comment]
Yes, it is. Use the `focus` event in the input to open the calendar (`picker.open()`). Please, leave github for bugs report or feature requests. Stackoverflow and similiar services are better avenues to clear up your doubts.

**Comment by Sevensnake** [comment]
do you have code example. does not seem to be working for me.

**Comment by julianobrasil** [comment]
Check it over here and close this issue, please: http://plnkr.co/edit/uPNESrA5VbKDrIjP9BaS?p=preview

**Comment by Sevensnake** [comment]
Thanks. worked great.
