### ISSUE TITLE
Person_pin icon is square sometimes and round others

### ISSUE THREAD

**Issue by farley911** [angular/material2#5706]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The icon for "person_pin" should always be the same icon.

#### What is the current behavior?
If I include the person_pin icon using the icon font the icon is round matching what is shown on the website (https://material.io/icons/#ic_person_pin), however when I download the SVG or PNG the icon is squared.

#### What are the steps to reproduce?
View the person_pin icon on https://material.io/icons, download either the SVG or PNG and compare the icon with the font icon and what is displayed on the icons page.

#### What is the use-case or motivation for changing an existing behavior?
Consistent behavior.

**Comment by m98** [comment]
This is not related to Angular Material, as far as I understand you're having an issue with Material font icons, you should fill an issue about your problem on the[ Material Design Icons ](https://github.com/google/material-design-icons) GitHub repository.

**Comment by jelbourn** [comment]
What @m98 said.
