### ISSUE TITLE
(feature) autocomplete minlength / maxlength

### ISSUE THREAD

**Issue by kthomas182** [angular/material2#5708]
#### Bug, feature request, or proposal:
feature

#### What is the expected behavior?
component input that specifies the min/max length before autocomplete starts filtering

#### What is the current behavior?
user clicks on the input and all the data is shown in the dropdown

Angular JS Material has these available:
`<md-autocomplete flex required
  md-input-minlength="2"
  md-input-maxlength="18"></md-autocomplete>`

**Comment by willshowell** [comment]
This is very easy to accomplish in your filtering mechanism:

https://plnkr.co/edit/mzlmxWlThdD8lrfDZtov?p=preview

**Comment by kthomas182** [comment]
Ahhh ... i didn't thank about that. Thanks @willshowell
