### ISSUE TITLE
bug(autocomplete): input underline goes under the autocomplete container

### ISSUE THREAD

**Issue by m98** [angular/material2#5709]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The [autocomplete](https://material.angular.io/components/autocomplete/overview) is a normal text input and it should follow inputs style and behavior.

> Text fields should indicate their state – whether enabled or disabled, empty or filled, valid or invalid – with clear label, input, and assistive text. 
> The input line indicates where to enter text, displayed below the label. When a field is active or contains an error, the line’s color and thickness vary. ([source](https://material.io/guidelines/components/text-fields.html#text-fields-layout))
> 
I expect when the autocomplete input is active I can see the input underline (aka input line)

#### What is the current behavior?
The underline (input line) goes under the autocomplete container. The image bellow shows the current behavior:
![Current behavior](https://i.stack.imgur.com/0lzrU.png)

https://material.angular.io/components/autocomplete/examples

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
@angular/cli: 1.1.1
node: 6.10.3
os: linux x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

```

**Comment by donroyco** [comment]
Are you sure this is the behaviour in more than just one browser?

**Comment by m98** [comment]
I used two  different computers, and both had latest version of chrome on it.

**Comment by donroyco** [comment]
I'm not talking about other computer. I'm talking about different _browsers_, like Internet Explorer 11, Microsoft Edge, Mozilla Firefox and Apple Safari. Does it occur in these browsers as well?

**Comment by m98** [comment]
I tried with the two different computers, with different screen size and resolutions.

Could you please try the autocomplete using IE, FireFox and Safari and provide screenshot of their behavior?
Thanks

**Comment by julianobrasil** [comment]
I have some browsers installed over here.

### IE11:

![image](https://user-images.githubusercontent.com/25405143/28176949-92594626-67cf-11e7-9136-d1f3b0a98948.png)

### Edge:

![image](https://user-images.githubusercontent.com/25405143/28176997-b6f5b08c-67cf-11e7-9722-0f5b87f704fc.png)


### Chrome (59.0.3071.115 64 bits)

![image](https://user-images.githubusercontent.com/25405143/28177165-57cbc3ca-67d0-11e7-926a-37f853baf380.png)


### Firefox 45.0.1 (Legacy)

![image](https://user-images.githubusercontent.com/25405143/28177118-2ff16d32-67d0-11e7-9a62-04ec411a73b5.png)

### 2012 Safari for windows (Legacy)

![image](https://user-images.githubusercontent.com/25405143/28177056-eb5c9e80-67cf-11e7-9e5c-6fcaf3f36a31.png)

**Comment by m98** [comment]
@julianobrasil 

Thanks a lot! Good screenshots

It seems that just I and Edge are showing it almost correctly. But if you look carefully at the IE and Edge screenshot you might see it's not showing the underline as its current height is!

I wish my PR works to fix this

Thanks again for screenshots!

**Comment by willshowell** [comment]
The autocomplete offset really depends on the `mat-input-infix` padding, which is dependent on the [input typography config](https://github.com/angular/material2/blob/master/src/lib/input/_input-theme.scss#L134).

@crisbeto I wonder if the css could be refactored in some way to share the value? The hardcoded 6/8px offset seems really fragile. Maybe #4914 could help, but instead of attaching to `mat-input-container`, it is attached to `mat-input-flex`?
