### ISSUE TITLE
MdPaginatorIntl is not exposed.

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#5715]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`MdPaginatorIntl` token is exposed by `@angular/material`

#### What is the current behavior?
No exposed.

#### What is the use-case or motivation for changing an existing behavior?
Requires so it can inject into other services. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

Related to #5573

**Comment by matheo** [comment]
Can the latest commit (0f48d7d) be used somehow?
I'm stuck with this bug :(

**Comment by willshowell** [comment]
@matheo From the getting started guide,

> A snapshot build with the latest changes from master is also available. Note that this snapshot build should not be considered stable and may break between releases.
```
npm install --save angular/material2-builds angular/cdk-builds
```
