### ISSUE TITLE
Don't use ngModel in md-paginator

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#5717]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Material components should be form agnostic (template/reactive)

#### What is the current behavior?
`md-paginator` uses `ngModel` [in its template](https://github.com/angular/material2/blob/master/src/lib/paginator/paginator.html#L8)

**Comment by crisbeto** [comment]
I suppose the underlying issue here is that `md-select` doesn't have a way of setting the value without the forms module.

**Comment by shlomiassaf** [comment]
Yes, that always seems strange to me, but I don't know the logic behind the design...

`md-select` should implement value accessor to support that?

This means that every complex component that composes other material components might run into this issue...

I don't think it can stay like that, it forces the developer to use template driven forms or at least import them just for that purpose...
