### ISSUE TITLE
Feature request: visual indicator for sortable column header

### ISSUE THREAD

**Issue by princemaple** [angular/material2#5724]
#### What is the expected behavior?
Sortable column in table header has a visual indicator to distinguish it from unsortable ones

#### What is the current behavior?
nothing other than a pointer cursor when hover

#### What is the use-case or motivation for changing an existing behavior?
to make it clear which ones are sortable, so you don't have to hover every header just to find out whether they are sortable at all

**Comment by benb7760** [comment]
I double checked the material spec, it doesn't mention anything about this. It shows indicators only when a sort has been applied. [see here](https://material.io/guidelines/components/data-tables.html). It does, however, say the following 

> If sorting is enabled, display a light sort icon upon hover, which indicates that the column is sortable.

I think a permanent indicator would have to be raised to the material design team, and added to the spec, before this repository would implement it

**Comment by jelbourn** [comment]
As @benb7760 mentioned, the material design spec doesn't have any indicator for this. However, it's very easy to build a custom sort-header that can be put into `cdk-table` or `md-table` (md-sort-header is less than 100 lines of code!).

**Comment by princemaple** [comment]
Thanks for the information!
