### ISSUE TITLE
DatePicker doesn't open when i click on input field

### ISSUE THREAD

**Issue by turab007** [angular/material2#5725]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the input field in datePicker is clicked then it should open the datePicker. 
Currently it only opens if i click on the datePicker icon.

#### What is the current behavior?
When i click on the input field, the datePicker doesnt open and instead it expects me to write the date. 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
i am using Angular2, TypeScript 2.3.4 and Material 2.0.0-beta.6

**Comment by julianobrasil** [comment]
You can make it work by using the onFocus event: (focus)="myPicker.open()" (mark it as readonly if you don't want the final users to type in dates)

**Comment by jelbourn** [comment]
As @julianobrasil describes, this behavior can be added via focus handler on the input. We don't implement this behavior by default because it is not an optimal workflow for screen-reader users.

**Comment by turab007** [comment]
I have configured it as @julianobrasil  said but shouldn't this be the default behavior? As this is a datePicker so when clicking on the input field it should ask you to pick the date. It's a date-PICKER. The name tells what it should do.

**Comment by agiratech-vigneshm** [comment]
@jelbourn why don't we just let the developer decides the accessibility level he needs for the website and make the datepicker work as a datepicker? I think we can make up for the screen readers using the ARIA attributes.

**Comment by jpike88** [comment]
> optimal workflow for screen-reader users

Why sacrifice developer ease of implementation for a use-case barely any of us care about to begin with? Shouldn't screen-reader comparability be an opt-in feature?

**Comment by jpike88** [comment]
@jelbourn I think this issue should be reopened or rediscussed

**Comment by emilio-martinez** [comment]
@jpike88 accessibility compliance is a major goal of this project. See "[The goal of Angular Material](https://github.com/angular/material2#the-goal-of-angular-material)" in the Readme.

**Comment by jpike88** [comment]
At the expense of usability for the 99.9999% (or 100%) of people who will ever use 99.9999% of sites built with this framework. The end result is that you create all these workarounds that sit on old issues that people have to stumble across because it didn't behave the way they'd expect it to. At the very least make it a flag like ```[openPickerOnClick]```.

**Comment by AlexMihov96** [comment]
> You can make it work by using the onFocus and onClick events together (at the input tag): **`(focus)="myPicker.open()"`** and **`(click)="myPicker.open()"`** (mark it as **`readonly`** if you don't want the final users to type in dates).
> 
> The onFocus takes care of the situation where the component is reached by navigating using the Tab key.
> 
> The onClick is necessary because the focus remains in the input after the user choose a date. If he wants to open the datepicker again without actually leaving the input it will be not possible: he will have to blur the input and focus it again to fire the onFocus event. So the onClick avoids this problem.

 Hello, how do I reset the value of the datepicker ( input value ) when using picker.open()

**Comment by julianobrasil** [comment]
@AlexMihov96, you can set it via the associated `<input>`. You can rl set it when the calendar opens subscribing a function to the `opened` output (take a look at the API on the docs site).

**Comment by AlexMihov96** [comment]
> @AlexMihov96, you can set it via the associated `<input>`. You can rl set it when the calendar opens subscribing a function to the `opened` output (take a look at the API on the docs site).

@julianobrasil Alright, my next question is how to put a button next to the calender toggle button

**Comment by julianobrasil** [comment]
Like a `clear` button?

**Comment by AlexMihov96** [comment]
Yes exactly

**Comment by julianobrasil** [comment]
In that case, do not use the provided toggle. Instead of using it provide your own `mat-icon-button`'s (matFormField suffix directive). Something like:

```html
<mat-form-field>
  <input  [formControl]="inputControl" 
          [matDatepicker]="picker" 
          matInput 
          placeholder="Choose a date">
 
  <div matSuffix>
    <button (click)="picker.open()" 
            mat-icon-button 
            type="button">
      <mat-icon>calendar_today</mat-icon>
    </button>
    
    <button (click)="inputControl.setValue(null)" 
            [disabled]="inputControl.value" 
            mat-icon-button
            type="button">
      <mat-icon>clear</mat-icon>
    </button>
  </div>
  <mat-datepicker #picker></mat-datepicker>
</mat-form-field>
```

**Comment by AlexMihov96** [comment]
> In that case, do not use the provided toggle. Instead of using it provide your own `mat-icon-button`'s. Something like (just an idea, you'll have to test it a little bit):
> 
> ```
> <mat-form-field>
>   <input  [formControl]="inputControl" 
>           [matDatepicker]="picker" 
>           matInput 
>           placeholder="Choose a date">
>  
>   <section class="row-buttons" 
>            matSuffix>
>     <button (click)="picker.open()" 
>             mat-icon-button 
>             type="button">
>       <mat-icon>calendar_today</mat-icon>
>     </button>
>     
>     <button (click)="inputControl.setValue(null)" 
>             [disabled]="inputControl.value" 
>             mat-icon-button
>             type="button">
>       <mat-icon>clear</mat-icon>
>     </button>
>   </section>
>   <mat-datepicker #picker></mat-datepicker>
> </mat-form-field>
> ```
> 
> ```css
> .row-buttons {
>   display: flex;
> }
> ```

Thank you very much, I've managed to do it this way, but these 2 icons ( clear and toggle ) are far right, i've tried to move them closer to the placeholder word but without result.
![image](https://user-images.githubusercontent.com/9700315/60829709-336ab480-a1be-11e9-88f8-86dc604e0265.png)

**Comment by julianobrasil** [comment]
You can control `mat-form-field` width:

```html
<mat-form-field class="m-width">
...
</<mat-form-field>
```

```css
.m-width {
  width: 150px;
}
```
