### ISSUE TITLE
Icons on md-tab-link and md-tab is not aligned

### ISSUE THREAD

**Issue by sondreb** [angular/material2#5728]
#### Bug, feature request, or proposal:
Icons are not aligned when used together with md-tab-nav-bar and md-tab-link.

#### What is the expected behavior?
Expecting to see the icon aligned middle with the text.

#### What is the current behavior?
Icons is aligned too high.

#### What are the steps to reproduce?

Source:
```
<nav md-tab-nav-bar>
	<a md-tab-link>TEST</a>
	<a md-tab-link><md-icon>cloud</md-icon> TEST</a>
</nav>

```
Screenshot:
![image](https://user-images.githubusercontent.com/309938/28175795-8d1a3f3c-67f5-11e7-89a2-4b12737d7c06.png)

Source for inline tab:

```
<md-tab-group>
	<md-tab>
		<ng-template md-tab-label>
			<md-icon>cloud</md-icon> TEST
		</ng-template>
		<h1>Some tab content</h1>
	</md-tab>
	<md-tab label="TEST">
		<h1>Some more tab content</h1>
	</md-tab>
</md-tab-group>
```

#### What is the use-case or motivation for changing an existing behavior?
Shouldn't need to write custom CSS to use icons on tabs or navigation.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.5, Material beta 8, TypeScript 2.3.2, tested in Chrome.

**Comment by sondreb** [comment]
Workaround:

```
.tab-icon {
	vertical-align: middle;
}

<md-icon class="tab-icon">date_range</md-icon> select a date</a>
```

Screenshot:

![image](https://user-images.githubusercontent.com/309938/28176343-4af1c326-67f7-11e7-97e4-c0f5d6857b9c.png)

**Comment by Robouste** [comment]
I think vertical-align: middle; is not good enough

![image](https://user-images.githubusercontent.com/5463032/28711202-16902faa-7387-11e7-95aa-dc2383ba88a3.png)

Now, the icon is too low

**Comment by crisbeto** [comment]
Should be fixed in master. Closing since it looks like I forgot to label https://github.com/angular/material2/pull/5771 properly.

**Comment by Robouste** [comment]
In wait for the fix, adding `font-size: 20px;` make it look good

![image](https://user-images.githubusercontent.com/5463032/28711342-9c1a2f68-7387-11e7-9a68-46227da48bfd.png)

**Comment by brandon1525** [comment]
.tab-icon {
        vertical-align: middle;
    }

    .tab-text {
        margin-left: 5px;
        vertical-align: middle;
    }
<nav md-tab-nav-bar>
            <div class="icon-text-inline" md-tab-link>
                <md-icon class="tab-icon">{{link.icon}}</md-icon>
                <span class="tab-text">{{link.title}}</span>
            </div>
        </nav>
