### ISSUE TITLE
Lazy loading module with material dependencies also includes typings

### ISSUE THREAD

**Issue by chriszrc** [angular/material2#5737]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
No typings dependencies would be included for a prod build

#### What is the current behavior?
the @angular/material/typings/index.ngfactory.ts is included in a prod build when using lazy loaded modules

#### What are the steps to reproduce?
convert the angular app to use lazy loaded modules like:
```
export const APP_ROUTES: Routes = [
  { path: '', component: AppComponent},
  { path: 'lazy', loadChildren: '../map/overview-ap.module#OverviewMapModule' }
];
```
And do a prod cli build with sourcemaps:
```
ng build --prod --sourcemaps
```
and then inspect with source map explorer:
<img width="1757" alt="screen shot 2017-07-13 at 2 38 12 pm" src="https://user-images.githubusercontent.com/25695785/28182375-0408885e-67da-11e7-8bfc-524c850c12cb.png">

#### What is the use-case or motivation for changing an existing behavior?
We don't want unnecessary files in the prod build

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular-cli - 1.2.0
angular 4.2.6
angular-material 2.0.0-beta.8
typescript 2.2.2

**Comment by kemmis** [comment]
+1 I am seeing this too. any way around this?

**Comment by jelbourn** [comment]
It's not typing information, it's the generated code from AoT for the whole library. 

Tracked via #4137

**Comment by armaserg** [comment]
So, is it correct, that in final bundle for each material module we have *.es5.js and *typings/index.ngfactory.js files?
![2018-10-31_17-23-38](https://user-images.githubusercontent.com/21171581/47799295-a0c26d80-dd32-11e8-9acc-defbea2c5cf5.png)
