### ISSUE TITLE
md-tab error when using async pipe

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#574]
#### What is the expected behavior?
No console error

#### What is the current behavior?
zone.js:260 Uncaught TypeError: Cannot read property 'elementRef' of undefined

#### What are the steps to reproduce?

`
ngOnInit() {
     this.weeks = this.inicidentReportService.getIncidentReports();
}

 getIncidentReports() {
        return this.http.get(
            WebAPI.url() + '/api/incidentReport')
            .map(request => request.json());
  }

`

`
    md-tab *ngFor="let w of weeks | async"
 `

**Comment by snorkpete** [comment]
This behaviour happens even if the array used in the ngFor directive isn't directly using the async pipe, but instead is being passed from another component that used the async pipe.

For, for eg, we have SmartComponent described as above:

ngOnInit() {
this.weeks = this.inicidentReportService.getIncidentReports();
}

getIncidentReports() {
return this.http.get(
WebAPI.url() + '/api/incidentReport')
.map(request => request.json());
}

and the template:
<dumb-component [tabs]="weeks | async"> </dumb-component>

And it uses DumbComponent that actually has the tabs component, but accepts the array for the tabs as  an input property:

DumbComponent{

}

**Comment by RicardoVaranda** [comment]
@robertmesserle @jelbourn This doesn't seem to have fixed the issue, I'm still getting the error using:
```

"@angular2-material/core": "^2.0.0-alpha.6",
    "@angular2-material/input": "^2.0.0-alpha.6",
    "@angular2-material/tabs": "^2.0.0-alpha.6",
    "@angular2-material/toolbar": "^2.0.0-alpha.6",
```

**Comment by robertmesserle** [comment]
@RicardoVaranda Can you provide a plunker or some way for us to see your code failing?  We include async tabs in our demo app, which is still working properly, so we'll need to see your app to determine what is different.

**Comment by RicardoVaranda** [comment]
Here you go mate:

http://plnkr.co/edit/p2L5mWEGYTi1RCnLpoj5?p=preview

**Comment by RicardoVaranda** [comment]
It's been fixed, Update just required @angular/forms which was not met and caused the upgrade to fail and I missed it.

Thanks :)
