### ISSUE TITLE
 md-error  with *ngIf having formcontrolsvalidation in md-input-container not working

### ISSUE THREAD

**Issue by divyameher** [angular/material2#5752]
md-error with *ngIf not working whereas using md-error outside of md-input-container with *ngIf works as expected

Here is my code:
````
<form [formGroup]="searchForm" (ngSubmit)="onSubmit()" novalidate>
        <md-input-container>
            <input mdInput type="text" placeholder="First Name"
                   formControlName="firstName" >
        </md-input-container>
        <md-input-container>
            <input mdInput type="text" placeholder="Middle Name"
                   formControlName="middleName">
            <md-error  *ngIf="!searchForm.value.firstName && !searchForm.pristine">
                Please Enter Middle Name with First Name
            </md-error>
        </md-input-container>
         <button md-raised-button> Search </button>
         <button md-raised-button type="reset"> Clear </button>
</form>
````

How can I resolve this?

**Comment by julianobrasil** [comment]
Always try to provide plunks and screenshots. It's much better than post code lines. 

This is a plunker to your post: http://plnkr.co/edit/7c5NAzKWjobn4eQ2G90R?p=preview

Apparently, it's working just fine. Try to modify it, track down your issue and repost it above your code in the top of this issue.

**Comment by divyameher** [comment]
@julianobrasil in provided plunker you have used **required** so it is working fine but In my scenario I'm not checking any built-in validators I'm checking firstname value in middlename(i.e., when middle name is entered without giving firstname It should throw error).

**Comment by julianobrasil** [comment]
Oh, I got it. In that case I think the best you can do is build a [custom validator](https://angular.io/guide/form-validation#custom-validation).

**Comment by divyameher** [comment]
@julianobrasil  please check plunker here: http://plnkr.co/edit/eoY3iuQuLyO50jqRKUxA?p=preview

**Comment by julianobrasil** [comment]
That's because `md-error` inside the input container is supposed to validate the input (not other inputs). It is shown only if there's an error with the input contained in the same `md-input-container` it is. I think you can change this behavior to whatever you wan by building a custom validator (and attaching it to the appropriate input) to throw errors when you think it's necessary.

**Comment by divyameher** [comment]
@julianobrasil Thanks for your suggestion and I think it would be better If Angular Material Doc is updated with this condition

**Comment by willshowell** [comment]
@divyameher https://material.angular.io/components/input/overview#custom-error-matcher 😁

**Comment by julianobrasil** [comment]
You can also use reactive forms (tried to put your value + pristine logic inside a validator): http://plnkr.co/edit/rZYp55czHOnt7itBSj6c
