### ISSUE TITLE
Floating label for autocomplete does not animate on focus

### ISSUE THREAD

**Issue by grizzm0** [angular/material2#5755]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Floating label should float using animation on fucs.

#### What is the current behavior?
Floating label snaps to floating-position without animation.

#### What are the steps to reproduce?
http://plnkr.co/edit/mVEqWQ3Xp4Ieep3iDs96?p=preview

**Comment by crisbeto** [comment]
Should be resolved by https://github.com/angular/material2/pull/3992.

**Comment by grizzm0** [comment]
@crisbeto Could you edit your PR to include "Fixes" and a link to this issue? I created an issue as I didn't find one. Might aswell keep this open until your PR is merged.
