### ISSUE TITLE
data-table align header cell to right

### ISSUE THREAD

**Issue by MaickelHubner** [angular/material2#5759]
#### Bug, feature request, or proposal:
For columns as currency, it is interesting to align the column header to the right

#### What is the expected behavior?
A parameter to set header alignment

#### What is the current behavior?
All header cells are aligned to the left

![header-cell-right](https://user-images.githubusercontent.com/15674062/28215716-4fd4e4b6-6885-11e7-872b-5e438761d280.jpeg)

**Comment by donroyco** [comment]
Why do you want this to be a parameter?

**Comment by MaickelHubner** [comment]
How else could he do that?
I do not have an ID class like with the columns to use in CSS ...

**Comment by andrewseguin** [comment]
Each column is given unique class that identifies it by name. For example, if your column name is `user_id`, then the column's class will be `cdk-column-userName` (and `mat-column-user_id` if using the `md-table`).

**Comment by gfigueroa** [comment]
@andrewseguin The column's class will indeed be `mat-column-columnName`, and I was only able to align the contents to the right, but not the headers. How do I select the column header? I tried `mat-header-cell-columnName`,  to no avail.

**Comment by willshowell** [comment]
@gfigueroa data cells have the class `.mat-cell` and header cells have the class `.mat-header-cell`. You can combine those with `.mat-column-columnName` to select just the column data or just the column headers. Otherwise `.mat-column-columnName` should select both the data cells and the header cells

https://plnkr.co/edit/f6WuuRofSePei0CzLy7r?p=preview

**Comment by MaickelHubner** [comment]
@gfigueroa I used this CSS code and it worked:

.mat-column-<columnName> {
  display: flex;
  justify-content: flex-end;
}

**Comment by gfigueroa** [comment]
@MaickelHubner Are you using a table with sorting? It doesn't seem to work on mine when I use sorting.

**Comment by willshowell** [comment]
@gfigueroa https://plnkr.co/edit/Est96yNWhy9tFG5fE96r?p=preview

**Comment by gfigueroa** [comment]
@willshowell  Ah it indeed works, though only for short header names. When you have a long header name it centers it.
https://plnkr.co/edit/A87H0D3UWWc94PcZ4LO9?p=preview

**Comment by willshowell** [comment]
@gfigueroa That's because with sort headers, they are actually buttons which have `text-align: center` applied to them. You can override that just fine but watch out for view encapsulation.

See updated styles in `index.html` and `table-sorting-example.css`
https://plnkr.co/edit/Aqk5wS6mFh7JsT9IXRib?p=preview

For the sort of troubleshooting you're doing, it's best to open up the inspector and observe which classes each element has and how you can target them individually.

**Comment by gfigueroa** [comment]
@willshowell Thanks, that seems to do the trick! It was quite a workaround though.

**Comment by gazpan** [comment]
This "right" class works in 6 and corrects margin/padding of the header

```
.right.mat-cell {
    display: flex;
    justify-content: flex-end;
}
.right.mat-header-cell {
    display: flex;
    justify-content: flex-end;
    padding-right: 0;
    padding-left: 24px;
}
.right.mat-header-cell:last-child {
    margin-right: 0;
}

```

**Comment by AlpacasForever** [comment]
using all of the above suggestions, I still get the right column of my table slightly askew, none of the divider lines line up, header is squished vertically, the first line of data is super big, and other lines are bigger than their respective rows.

**Comment by chrispruitt** [comment]
I had a similar problem to @johren02 not including style differences in the first line of the data.

**Comment by prolink007** [comment]
Using what @MaickelHubner suggested.

`.mat-column- {
display: flex;
justify-content: flex-end;
}`

I am getting what @johren02 is describing. How do we right align a column using mat-table?

**Comment by duard** [comment]
I just want to align the HEADER of the columns to the rigth if the content is numeric or money ... and it do not work in my column header.

.mat-column-CODIGO {
  color: #333;
  text-align: right;
  padding-right: 10px;
  font-weight: bold;

  flex: 0 0 75px;
}


![capturar](https://user-images.githubusercontent.com/36894/43925013-7d17a62e-9bfc-11e8-9eaa-486aadd15498.PNG)

**Comment by dcanfield** [comment]
In @angular/material 6.4.7 I was able to get header cells to right align using following:
In your component, bring in ViewEncapsulation, set it to none:
@Component({
  selector: 'app-whatever',
  templateUrl: './whatever.component.html',
  styleUrls: ['./whatever.component.css'],
  encapsulation: ViewEncapsulation.None
})
In your template, in the sorted header cell that you want right aligned set a class:
`<th class="cell-right" mat-header-cell *matHeaderCellDef mat-sort-header>`
In your css file define the class like so:
`.cell-right .mat-sort-header-container {
  justify-content: flex-end;
}`

Setting ViewEncapsulation in your component will probably break your other formatting, so YMMV.

**Comment by chrispruitt** [comment]
@dcanfield your solution is the only one that worked for me using angular material 6.3.3, thanks a million!

**Comment by thisarumahadurage** [comment]
> Using what @MaickelHubner suggested.
> 
> `.mat-column- { display: flex; justify-content: flex-end; }`
> 
> I am getting what @johren02 is describing. How do we right align a column using mat-table?

`.mat-column- {justify-content: flex-end; }`
remove `display: flex` and it'll be fixed

**Comment by FelipeFelizardo** [comment]
use:
 
<mat-header-cell *matHeaderCellDef></mat-header-cell>
 <mat-cell *matCellDef="let element"> {{element.position}} </mat-cell>

instead of:

<th mat-header-cell *matHeaderCellDef></th>
 <td mat-cell *matCellDef="let element"> {{element.position}} </td>

then:

mat-cell{
  display:flex !important;
  justify-content:center!important;

}

mat-header-cell {
  display:flex;
  justify-content:center;
}

works for me (y)

**Comment by ssdooley** [comment]
> Fixed mine using the following code.
> `<th mat-header-cell *matHeaderCellDef mat-sort-header style="direction: rtl"> Amount</th>`
> 
> Change direction from 'Left to Right' to 'Right to Left' with `direction: rtl` for the header cell so the sorting arrow will be on the left.
> Then add `justify-content: flex-end;` to the column

worked for me as well
