### ISSUE TITLE
Possibility to add a md-divider for md-list-item

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#576]
#### feature request
Add md-divider after each md-list-item

#### What is the expected behavior?
Nice lines seperating list items

#### What is the current behavior?
adding a md-divider tag in md-list-item has no effect

#### What are the steps to reproduce?
add an md-divider tag in a md-list-item
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

**Comment by kara** [comment]
`md-divider` is already implemented, but it sounds like you're putting the divider *inside* the list item, rather than between list items (as it's designed). 

Normal usage is like this:
```html
<md-list>
   <md-list-item></md-list-item>
   <md-divider></md-divider>
  <md-list-item></md-list-item>
</md-list>
```

If that's already what you're doing, can you provide a plunker that illustrates the issue?

**Comment by zigzag95** [comment]
Thanks @kara
I'm running my *ngFor on md-list-item this is why I put md-divider inside.
I'll try to put the *ngFor on a span container and hope it will work.

**Comment by DennisSmolek** [comment]
@zigzag you could use the template syntax instead of an extra span element: 
`<template ngFor #item [ngForOf]="items" #i="index"><md-list-item>...</md-list-item></template>`
Link to official docs: https://angular.io/docs/ts/latest/api/common/NgFor-directive.html

**Comment by zigzag95** [comment]
It works
Thank you

**Comment by stefanaerts** [comment]
or put md-list around md-list-item

<md-list  *ngFor="let item of items">
  <md-list-item ></md-list-item>
   <md-divider ></md-divider>
</md-list>
