### ISSUE TITLE
md-select [value] does not match objects

### ISSUE THREAD

**Issue by crutchcorn** [angular/material2#5763]
#### Bug, feature request, or proposal:
Bug/feature request

#### What is the expected behavior?
When the [value] of an `md-select` is an object, it should match to the `[ngModel]` to change the selected value to match the value

#### What is the current behavior?
The selected value is unaffected when `[ngModel]` matches an option `[value]`

#### What are the steps to reproduce?
http://plnkr.co/edit/SDbHhHQUDndBPCES4xXl?p=preview

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
The use-case would be when selected an object from a list and trying to pre-populate the selected value with an object

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
While this should affect all browsers, Typescript versions, etc, our current setup is:
```
node: 6.11.1
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/upgrade: 4.1.3
```

**Comment by lucasvanhalst** [comment]
It does not match `null` too, even if one of the options their value contains value `null`

**Comment by willshowell** [comment]
Select currently compares by object reference. There's an open issue https://github.com/angular/material2/issues/2785 to allow custom comparators

**Comment by crutchcorn** [comment]
@willshowell must've missed that one, that's exactly what we're looking for. Will close issue and follow there
