### ISSUE TITLE
Dropdown menu (maybe this could be an enhancement to md-menu)

### ISSUE THREAD

**Issue by DBosley** [angular/material2#5765]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
A dropdown menu for navigation.

#### What is the current behavior?
md-menu with overlapTrigger set to false has most of the functionality I'm looking for, but it puts a transparent overlay on top of the whole page that makes it so that clicking outside of the menu closes it.

My problem with this is that I want to be able to control weather or not this overlay is enabled. I'd like to be able to open a menu then, with a single click, close that menu and open another one. Right now, with the way it works, you can open a menu, then click to close it, then click again to open a new one.

#### What are the steps to reproduce?

Put two md-menu buttons next to each other with `[overlapTrigger]="false"`.

Open one menu then, while it's still open, attempt to open the second menu.

#### What is the use-case or motivation for changing an existing behavior?

Pages in a desktop view with top-of-the-page navigation split into multiple sections. clicking through the sections shouldn't take 2 clicks each.

#### Is there anything else we should know?

The functionality I'd like to see would be similar to the bootstrap dropdown component in how it works.

**Comment by jelbourn** [comment]
We don't plan on adding a component like this to Angular Material directly because there isn't a well-defined accessible workflow for it. A standard `role="menu"` is required to close upon interaction. 

However, it should be relatively simple to create a custom component that does this with the `cdkConnectedOverlay` directive (will be actually moved into the cdk soon).

**Comment by DBosley** [comment]
@jelbourn I guess I don't fully understand what you're saying. In this feature request I do mean that a menu should still close upon interaction. The feature I'm requesting is just that I want to be able to open a different menu without having to use two clicks. One to close the first menu and a second to open the second menu.

If I click on a menu, then click a different menu, the first should close and the second should open. Currently, when clicking the second menu, the first menu closes and the second one does nothing until you click again.
