### ISSUE TITLE
Nightly builds @angular2-material/XXXX@next

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#577]
#### What is the expected behavior?

Provide nightly builds reflecting `master` in NPM
#### What is the current behavior?

No nightly builds.
#### What is the use-case or motivation for changing an existing behavior?

Currently there are a lot of things evolving, sometimes a feature exists in `master` for a while until it is released. One can "compile" his own version with little effort but this mean hassle for the project, either `npm link` the clone or removing the material dependencies from `package.json` and loosing the npm dependency inspection

Having `@angular2-material/core@next` will ease up the process.
#### Which versions of Angular, Material, OS, browsers are affected?

None

**Comment by DevVersion** [comment]
I think this would be something really useful.

We could manage this with the CI.

**Comment by jelbourn** [comment]
@IgorMinar are there any plans to do this for `angular/angular`? if so we should do it the same way.

**Comment by IgorMinar** [comment]
We publish all of our builds to git repos instead ([example](https://github.com/angular/core-builds)). you can install them from there via:

npm install angular/core-builds#optionalTagOrHash

I prefer git repos because they allow us to publish artifacts after each commit without flooding the npm. Additionally, it's easy to review what's being published and see the diffs as well we remove old version whenever we want to (unpublishing from npm is tricky and sometimes impossible).

**Comment by shlomiassaf** [comment]
@jelbourn There's another issue here, if `material2` adopts this, how can one use both angular nightly and material2 nightly? `material2` will have to reference angular nightly or else NPM havoc.

**Comment by fxck** [comment]
any progress on this?

**Comment by jelbourn** [comment]
Rather than going to npm, packages for each commit will be available through GitHub (similar to `angular/angular`).

**Comment by DevVersion** [comment]
Per-commit builds on a Github repository are now available (See [angular/material2-builds](https://github.com/angular/material2-builds))

```
npm i https://github.com/angular/material2-builds
```

> This installs the current version on GitHub to your `node_modules` as same as a normal NPM package.

**Comment by Chris1308** [comment]
Hey,

i have problems with the build. I just run
```
npm install -g angular-cli
ng new myProject
npm i https://github.com/angular/material2-builds
```

Then i added Materialmodule.forRoot() to my app.module and run ng serve.
After this i get the following error:

```
Can't bind to 'mdrippletrigger' since it isn't a known property of 'div'. ("f="!_isRippleDisabled()" class="md-button-ripple" [class.md-button-ripple-round]="_isRoundButton()" [ERROR ->][mdrippletrigger]="_getHostElement()" [mdripplecolor]="_isRoundButton() ? 'rgba(255, 255, 255, 0.2)' "): MdButton@0:183...
```

Any ideas whats wrong?

**Comment by jelbourn** [comment]
@Chris1308 that build was broken. This will happen when installing from master- that's why we do releases :)
