### ISSUE TITLE
md-progress-bar Determinate doesnt seem to work

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#578]
Hi,

It seems that the determinate md-progress-bar is not working properly.

I have the below code and for md-progress-circle it seems to work properly, whereas in case of md-progress-bar the progress bar is always shown as full.

```
<md-progress-bar mode="determinate" [value]="loadingStatus"></md-progress-bar>
<md-progress-circle mode="determinate" [value]="loadingStatus"></md-progress-circle>
```

**Comment by sendilkumarn** [comment]
Version ? 

Plunker sample ?

**Comment by naveedahmed1** [comment]
I am using latest version Alpha 5 with Angular 2 RC1, even this doesn't work:

`<md-progress-bar mode="determinate" value="30"></md-progress-bar>`

The progress bar shown as a result of above tag is always full. As per my understanding it should be partially filled.

Whereas in case of progress circle, the below code works:

<md-progress-circle mode="determinate" value="30"></md-progress-circle>

**Comment by sendilkumarn** [comment]
check this #519 

This issue was closed recently.

**Comment by naveedahmed1** [comment]
Thanks Sendil for the update, I will close this issue now.
