### ISSUE TITLE
cdk: wrong es2015 property in package.json

### ISSUE THREAD

**Issue by gms1** [angular/material2#5782]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
the 'es2015' property in package.json should point to the ES2105 module "./@angular/cdk.js"

#### What is the current behavior?
the 'es2015' property "./@angular/cdkjs" of the package.json  cannot be resolved

#### What are the steps to reproduce?
just open package.json for reading

**Comment by DevVersion** [comment]
Great catch. Thank you!
