### ISSUE TITLE
md-card: css property 'overflow:hidden' doesn't work correctly on md-card-subtitle

### ISSUE THREAD

**Issue by twoheaded** [angular/material2#5785]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

CSS:

    md-card-subtitle {
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    };

Expected result:

![angular material](https://user-images.githubusercontent.com/15314781/28238691-ec7ac024-6961-11e7-922d-9c7136e700e9.png)

#### What is the current behavior?

![angular material2](https://user-images.githubusercontent.com/15314781/28238699-27d56b6a-6962-11e7-83a3-614d284a39f3.png)

**Comment by donroyco** [comment]
@twoheaded Can you provide a Plunker and use [the issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md). Thanks.

**Comment by julianobrasil** [comment]
@twoheaded, could not reproduce the mentioned behavior: https://plnkr.co/edit/NEE7z6j0EZJez61zoykI?p=preview

Are you sure the problem was in the subtitle?

![image](https://user-images.githubusercontent.com/25405143/28241939-bbe7880c-6975-11e7-9009-fe5c06ab933f.png)

**Comment by twoheaded** [comment]
@julianobrasil, Oh, wrapper class... It works. Thank you!
