### ISSUE TITLE
md-datepicker bound field not updated in IE11 if date entered manually with keyboard

### ISSUE THREAD

**Issue by adoris** [angular/material2#5791]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If date entered from keyboard - field "oe.ValidTo" will be updated to right value in all browser.

#### What is the current behavior?
If date entered from keyboard - field "oe.ValidTo" is updated to right value in Chrome, but updated to null in IE11.
If date Picked from calender by mouse - field will be updated as expected in all browser.

#### What are the steps to reproduce?
         <md-input-container>
              <input mdInput name="ValidTo" [mdDatepicker]="validToDatePicker" [min]="minDate" [max]="maxDate" [(ngModel)]="oe.ValidTo" placeholder="Gültig bis">
              <button mdSuffix [mdDatepickerToggle]="validToDatePicker"></button>
            </md-input-container>
            <md-datepicker #validToDatePicker class="field-input full-width"></md-datepicker>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/material 2.0.0 beta8, angular/core 4.3.0

**Comment by julianobrasil** [comment]
Seems to work fine here (IE11): https://plnkr.co/edit/jc4Ywu?p=info

![image](https://user-images.githubusercontent.com/25405143/28242634-344b2630-6987-11e7-9d8f-c246b0abe9e9.png)

**Comment by adoris** [comment]
problem ist not in ie, but in locale. i will open other issue.
sorry.

**Comment by julianobrasil** [comment]
What's wrong with the locale? Try to reproduce it in the plunk I linked above.
