### ISSUE TITLE
Why does <span class="example-spacer"></span> not giving any space?

### ISSUE THREAD

**Issue by zikrimarquel** [angular/material2#5799]
#### Bug, feature request, or proposal:
I think it's a bug

#### What is the expected behavior?
example-spacer should fills the space in the remaining row

#### What is the current behavior?
nothing was filled

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.1.1
node: 6.10.3
os: win32 x64
Typescript: 2.4.1
Browser: Google chrome, and firefox

**Comment by grizzm0** [comment]
example-spacer is not part of material2. It sounds like a CSS class defined in the example you're looking at.

**Comment by kara** [comment]
Yeah, this sounds like a demo class and not something exported by Material.
