### ISSUE TITLE
Make VIEWPORT_RULER_PROVIDER importable from @angular/cdk

### ISSUE THREAD

**Issue by YoussefTaghlabi** [angular/material2#5802]
#### Bug, feature request, or proposal:
Make `VIEWPORT_RULER_PROVIDER` importable

#### What is the expected behavior?
The following import should work:
`import { VIEWPORT_RULER_PROVIDER } from '@angular/material';`

#### What is the current behavior?
Can import `ViewportRuler`, but can't import `VIEWPORT_RULER_PROVIDER`

#### What are the steps to reproduce?
`import { VIEWPORT_RULER_PROVIDER } from '@angular/material';`

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
While building components, there is still a use case for using `VIEWPORT_RULER_PROVIDER` as it is the case in [`radio module`](https://github.com/angular/material2/blob/master/src/lib/radio/index.ts#L11)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`2.0.0-beta.8`

#### Is there anything else we should know?
No

**Comment by jelbourn** [comment]
FYI this will be moving to `@angular/cdk` soon

**Comment by crisbeto** [comment]
This seems to work now via `@angular/cdk/scrolling`.
