### ISSUE TITLE
Make src/cdk/testing folder classes importable

### ISSUE THREAD

**Issue by YoussefTaghlabi** [angular/material2#5803]
#### Bug, feature request, or proposal:
Make src/cdk/testing folder classes importable

#### What is the expected behavior?
All classes under `src/cdk/testing` should be importable, as in:
`import { wrappedErrorMessage } from '@angular/cdk';`

#### What is the current behavior?
Can't import `src/cdk/testing` content

#### What are the steps to reproduce?
`import { wrappedErrorMessage } from '@angular/cdk';` will error out

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Build a set of components and their unit tests using `@angular/cdk`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`2.0.0-beta.8`

#### Is there anything else we should know?
No

**Comment by DevVersion** [comment]
Right now, the testing utilities are intentionally not exposed in the public API.

At some point there was the idea of exposing those utilities to the public using a secondary entry-point (similar as for `@angular/core/testing`)

Meaning that developers can import those utilities like that:
```ts
import {XX} from '@angular/cdk/testing';
```

**Comment by YoussefTaghlabi** [comment]
This will be great! We are pretty excited that Angular released `@angular/cdk`. We previously had to port most of the non-public core files as we are building our Components on top of Angular Material Components. 
Now that Angular released `@angular/cdk`, we deleted our imported non-public core files and switched to `@angular/cdk`, but we still have a copy of `testing` folder as it is not public yet.

Any idea on the timeframe? I can submit a PR.

**Comment by DevVersion** [comment]
For the secondary entry-points we need some bigger refactoring of our packaging again. Once that's done we can start exposing the testing utilities as a secondary entry-point.

I don't have a timeframe here, but it shouldn't take too long because we need the package refactoring for other secondary entry-points too.

**Comment by YoussefTaghlabi** [comment]
@DevVersion Sounds good! Thanks!

**Comment by jelbourn** [comment]
Yeah, as @DevVersion mentioned, we don't intend these to be public right now. We would want to be much more deliberate in designing what our testing utilities would look like for consuming developers.
