### ISSUE TITLE
mdPrefix/mdSuffix should change cursor when hover over icon

### ISSUE THREAD

**Issue by jymdman** [angular/material2#5807]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Cursor should change to pointer when hover over icon

#### What is the current behavior?
Cursor don't change from the input type cursor.

![mdsuffix](https://user-images.githubusercontent.com/1311201/28262399-234f740a-6ae3-11e7-89c4-d905291f9410.gif)

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Should change cursor to pointer to indicate that icon is clickable.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular-4.3.0
material-2.0.0-beta.8 (probably all versions)
chrome
macosx

**Comment by crisbeto** [comment]
The prefix and suffix aren't necessarily for icons, they can also be used for text. This would be handled better on the consuming side.

**Comment by jymdman** [comment]
Good point! I will close this issue!
