### ISSUE TITLE
Underline does not move with mdTextareaAutosize (chrome)

### ISSUE THREAD

**Issue by Tetrygon** [angular/material2#5815]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The mat-underline moves with the textarea as it auto-sizes

#### What is the current behavior?
As the textarea expands, the underline doesn't move **when it is in a table cell**

#### What are the steps to reproduce?
surround a textarea with an md-input-container that is inside a td
https://plnkr.co/edit/T2ETCjZ5hHgMs0nVUwQU?p=preview

This is the input demo from material.angular.io with minor modifications

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
I looks and feels terrible. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4
Material 2-beta.8
win 7
TS - 2.2
Browsers - Chrome 55 (IE 11 works as expected)

**Comment by willshowell** [comment]
Do you see the same behavior in an updated version of Chrome? Not seeing any strange behavior in Chrome 59

**Comment by Tetrygon** [comment]
This seems to be a browser issue. Update to 59 with no issues. Closing issue
