### ISSUE TITLE
Problem populating md-select options when using in reactive forms

### ISSUE THREAD

**Issue by pantonis** [angular/material2#5818]
```
<md-select placeholder="Profile" [formControl]="profilesFormControl">
    <md-option *ngFor="let profile of profiles" [value]="profile"> 
        {{ profile.Name }}
    </md-option>
</md-select>
```

Following normal select box populates fine:

```
<select >
    <option [ngValue]="profile" *ngFor="let profile of profiles">
        {{ profile.Name }}
    </option>
</select>
```

#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Successfully populate md-select control

#### What is the current behavior?
md-select control does not populate whereas If I use normal <select> works just fine.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.2.5
Material: 2.0.0-beta.8
OS: Windows 10 x64
Typescript: 2.3

**Comment by julianobrasil** [comment]
Please, provide a plunk to help your issue to be better understood: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

**Comment by kara** [comment]
Yeah, we'll need a more complete example to help debug. Can you provide a plunker link?

**Comment by pantonis** [comment]
I am really sorry but I have huge codebase and cannot extract the code that load this. It is fetching data from server using websockets. Nothing special about it. As I wrote above the normal select element works just perfect.

**Comment by willshowell** [comment]
@pantonis a lot of similar issues have come up due to md-select currently comparing objects by reference (https://github.com/angular/material2/issues/2785). You may be seeing a symptom of that.

Here's an example of it working with reactive forms https://plnkr.co/edit/ix90KHY8HAInJ5fWxtpJ?p=preview

**Comment by andrewseguin** [comment]
@pantonis We'd love to help with the issue but we are having trouble reproducing the bug. Feel free to reopen with a plunker example so we can investigate and fix the problem.

**Comment by pastafari** [comment]
@andrewseguin  I've created a minimal example here: https://stackblitz.com/edit/angular-material2-issue?file=app%2Fapp.component.ts to help you investigate.

There are two md-select components in that example, one (country1) uses an initial value from the array of options (countries), while the other (country2) uses an initial value that looks the same but is a different object. Might be related to #2785 as @willshowell  pointed out.

This might help you investigate. Thanks for all the great work on this project 👍

**Comment by willshowell** [comment]
@pastafari I think you forgot to fork the stackblitz :D Also, select now was a [compareWith](https://material.angular.io/components/select/api) input to combat this exact problem! You can compare your countries by some other unique property besides Object reference.

**Comment by julianobrasil** [comment]
@rafaelss95 also has an example of `compareWith` here :https://github.com/angular/material2/issues/6970#issuecomment-328355857

**Comment by pastafari** [comment]
@willshowell yes I did notice compareWith, however that will require an update to beta-12, which means I need to /s/md/mat, which I don't have time for just yet :)

**Comment by willshowell** [comment]
@pastafari you're in luck, it was added in beta.10. Also the [prefix updater tool](https://github.com/angular/material-prefix-updater) is very easy and, for us, a regex followup took only a couple minutes.

**Comment by alaboudi** [comment]
has this issue been closed? I can't populate 'mat-select' by using reactive forms. Should I open a ticket with an example?

**Comment by mjsol12** [comment]
running same issue when I'm using production. while my development shows no error.
