### ISSUE TITLE
(select): should have same error behavior as input

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#5826]
select's error state is not affected by form submit, select also doesn't support error messages (see: http://plnkr.co/edit/4nJFdsq4Z4ckpLfHVkAt?p=preview)

**Comment by crisbeto** [comment]
I've sorted out the error state in https://github.com/angular/material2/pull/4754.

**Comment by mmalerba** [comment]
awesome!

**Comment by mmalerba** [comment]
closing as dup of ##4611
