### ISSUE TITLE
Input error when delete with backspace on touch device

### ISSUE THREAD

**Issue by mari4524** [angular/material2#5838]
#### Bug, feature request, or proposal:
Input error when delete with backspace on touch device. The cursor is not placed at the beginning of the placeholder but  is in a forward position.
in touch device.

#### What is the expected behavior?
have the cursor at the beginning of the placeholder

#### What is the current behavior?
The cursor is in a forward position

#### What are the steps to reproduce?

go to email example in this page:
https://material.angular.io/components/input/overview

try to write a word like:  bohumn

delete with backspace

the cursor is not at the beginning but in a forward position

#### What is the use-case or motivation for changing an existing behavior?
is not correct

**Comment by julianobrasil** [comment]
Seems to work fine in my Android. Any particular config?

**Comment by mari4524** [comment]
I have the problem on iPad

**Comment by willshowell** [comment]
I was able to reproduce on ios as well

<img src="https://user-images.githubusercontent.com/6475576/28320886-c25e96d6-6b9f-11e7-8014-9aeba546ad40.PNG" width="350">

**Comment by willshowell** [comment]
It also occurs on the "input hint" and "prefix suffix" examples, which leads me to believe it is an issue with inputs within forms (since the "basic" example is not in a form)

**Comment by julianobrasil** [comment]
The cursor problem does not affect Android, but the input underline overflowing the screen does.

**Comment by mmalerba** [comment]
The input sizing issue looks like just an issue with the docs site, not the input itself. I'm not able to reproduce the cursor issue on an iPad, but the iPad is big enough that I don't see the overflow. I wonder if the cursor issue is also related to the sizing issue.

**Comment by willshowell** [comment]
@mmalerba https://github.com/angular/material2/pull/5839 should fix the overflow when deployed. Also [this repro](https://run.plnkr.co/J5e63mX5IJaWBUKL/) shows the cursor issue for me on iOS 10.3.3

**Comment by julianobrasil** [comment]
@willshowell, the link to the repro is broken.

**Comment by willshowell** [comment]
Oops, something weird about full screen plunks.

Also I think I was wrong about it being related to forms. The below gifs show that it is dependent on having an auto|never floating placeholder. For me, to get reliable results, I have to *hold* the delete key while removing the input, and I get the same results in Safari and Chrome on iOS.

## gif 1 ([plunker](https://plnkr.co/edit/IYNya5T0JVBcqgOZ739X))
![error-1-gif](https://user-images.githubusercontent.com/6475576/28575045-c5079792-711d-11e7-99b0-945f3d18bf83.gif)

## gif 2 ([plunker](https://plnkr.co/edit/GxAkOOi5l3yaX3qI3Z7H))
![error-2-gif](https://user-images.githubusercontent.com/6475576/28575509-1bd0e44c-711f-11e7-91b3-2ec1e39ae8c1.gif)

**Comment by mmalerba** [comment]
Ok very interesting. I was still not able to repro this with an iPad running iOS 9, but I was with an iPhone running iOS 10, so it must be related to either the form factor or the specific version. Will do some experiments and see if I can narrow it down any further.

**Comment by mmalerba** [comment]
Ok I've narrowed this down a little further. It seems like mobile safari has some issue where the cursor gets stuck when you change the page content in response to input events. Minimal repro using native input: http://plnkr.co/edit/kzyVA8wHqC6g5uVcnsJv?p=preview

I'll see if anyone has written anything about how to work around this

**Comment by mmalerba** [comment]
Couldn't find any existing documentation about this issue, but after some experimentation I think I've found a way to fix it. Added the fix code to the plunker above and will prepare a PR to implement it for `md-input-container`.
