### ISSUE TITLE
md-overlay needs z-index.

### ISSUE THREAD

**Issue by DennisSmolek** [angular/material2#584]
**Bug**
Tested on latest/Chrome. 

The md-overlay-pane should have a z-index set to at least 1. 
Many of my other elements don't use z-index so I didn't notice until a label from a md-input was on-top of my overlay. So is the underline when the item was in focus. 

Adding: `z-index:1;` to the .md-overlay-pane fixes the issue. 

Images attached:
Before:
<img width="488" alt="screen shot 2016-05-30 at 5 28 06 pm" src="https://cloud.githubusercontent.com/assets/1397052/15659240/2e8978b6-268d-11e6-89b7-341a44d7bf9d.png">

After:
<img width="497" alt="screen shot 2016-05-30 at 5 28 46 pm" src="https://cloud.githubusercontent.com/assets/1397052/15659242/3623bd3e-268d-11e6-909f-394b01229c98.png">

**Comment by jelbourn** [comment]
FYI the overlay is still a work-in-progress, so expect there to be several rough edges like this.

**Comment by DennisSmolek** [comment]
Oh I 100% understand, I hope I wasn't coming off harsh or anything it was just one of the few things I understood enough to let you guys know about.
