### ISSUE TITLE
MdTable doesn't display data when using router-outlet under Angular 4.3.0

### ISSUE THREAD

**Issue by kbeaugrand** [angular/material2#5843]
#### Bug, feature request, or proposal:
MdTable doesn't display data when using router-outlet under Angular 4.3.0

#### What is the expected behavior?
We should have a table displayed with data. 

#### What is the current behavior?
The table is not displayed.

#### What are the steps to reproduce?
Create a component with a template using a md-table.
This component must be resolved with a routing.

Or use this punkler : http://plnkr.co/edit/96ngX1EssWkukdUtSWx1

#### What is the use-case or motivation for changing an existing behavior?
This is a breaking change

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.0

#### Is there anything else we should know?
This works fine with Angular 4.1.3. 
We have 2 workaround : 
* Add a hidden input binded to the model (with ngModel)
* Add a setTimeout with en ampty body on the ngOnInit method of the component

**Comment by benb7760** [comment]
#5593 and PR #5775

**Comment by andrewseguin** [comment]
Closed as duplicate. Check out previous comment for the opened issue and associated PR that should resolve this.
