### ISSUE TITLE
Make year selectable in date picker

### ISSUE THREAD

**Issue by mschering** [angular/material2#5845]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
The year should be selectable from a dropdown list.

#### What is the current behavior?
The year can only be changed with the previous and next button.

#### What are the steps to reproduce?
See demo: https://material.angular.io/components/datepicker/examples

#### What is the use-case or motivation for changing an existing behavior?
Entering birthdays is very cumbersome. You have to click previous a lot for old people :)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0

**Comment by naveedahmed1** [comment]
I also think that there are serious usability issues with Datepicker. It works great when the user has to select date from current month or from month of the same year. I showed a form with datepicker to few people and ask them to select a date from past years for example Oct 15, 1995. I found them struggling with changing the Year. Most of them used the arrows in month view to go back which irritates user if they have to go back few years.

**Comment by julianobrasil** [comment]
It's already being tracked: #4853

**Comment by jonsamwell** [comment]
+1

**Comment by elmoyeldo** [comment]
+1

**Comment by naveedahmed1** [comment]
@mmalerba is there any update on this? should we expect it to be included in next release?

**Comment by mmalerba** [comment]
I'm probably not going to have time to work on this for the next month or two, I have a lot of other things currently on my plate.

**Comment by mahmood-sajjadi** [comment]
without this feature, date picker is not usable because for the birthday, if user age is 35, he/she should press prev year button 35 times 😨

**Comment by erikhaug** [comment]
+1

**Comment by wiekonek** [comment]
We really need this! Current datepicker isn't usable in most cases.

**Comment by Botle-Buhle-Brands** [comment]
+1

**Comment by agnislav** [comment]
The same concern for a birthday. Our users 18 to 60+ yrs old.

**Comment by BenRacicot** [comment]
Hey @agnislav I have the same issue and until we get the year select implemented I at least was able to work with the min/max dates like this:
```
private startAt: Date;
private minDate = new Date(1997, 0, 1);
private maxDate = new Date(Date.now());
private startDate: Date;
private datepickerDisabled: boolean;
private date: Date;


ngOnInit() {
    // setting the start date and max birth dates for > 18 years old
    this.maxDate.setDate( this.maxDate.getDate() );
    this.maxDate.setFullYear( this.maxDate.getFullYear() - 18 );
    this.startDate = this.maxDate;
}

<md-input-container>
    <input mdInput [mdDatepicker]="birthDatePicker" formControlName="birthDate" placeholder="birthdate" [min]="minDate" [max]="maxDate">
    <md-datepicker-toggle mdSuffix [for]="birthDatePicker"></md-datepicker-toggle>
    <md-datepicker #birthDatePicker startView="year" [startAt]="startDate"></md-datepicker>
    <md-error *ngIf="form.controls['birthDate'].hasError('mdDatepickerMin') && form.controls['birthDate'].touched">You can't be over 100 years old</md-error>                
    <md-error *ngIf="form.controls['birthDate'].hasError('mdDatepickerMax') && form.controls['birthDate'].touched">Users must be at least 18 years old</md-error>                
</md-input-container>

```

**Comment by vaibhavrtk** [comment]
+1 for this feature

**Comment by damiendubois** [comment]
Yes definitely +1 for this feature

**Comment by robert-skinner** [comment]
It's a shame, I like it but I won't be using it until this gets implemented!

**Comment by svandevoorde** [comment]
+1 for this
Same issue with date of births

**Comment by jfox459** [comment]
+1 
same issue for date of birth, have to use something else

**Comment by drait** [comment]
+1
Same issue for that date of birth!.any update from angular team?!

**Comment by ankitraonka** [comment]
This is one of the most common issue. Is there any data to fix this?

**Comment by Lakston** [comment]
Came into this problem today too to implement a birth date picker. I'll give it a look but it will probably be way over my skill level to implement it :)

**Comment by ankitraonka** [comment]
@mmalerba any updates?

**Comment by mmalerba** [comment]
up-ing the priority, I know it's painful without this, I'll try to work on it as soon as I have the time

**Comment by naveedahmed1** [comment]
Awesome! It would be great to have time picker as well.

**Comment by RichardBoyder** [comment]
mmalerba , Any news for us yet  with regards to this?

**Comment by Lakston** [comment]
They just released v5.0.0 RC and there was no mention of this in it. I removed the picker from my app personally and use something else as it was not usable in the current state.

I understand that there is a lot to do though so thanks for taking care of this none the less :)

**Comment by RichardBoyder** [comment]
agreed. The work these guys have done is awesome. We will be patient then.

**Comment by ankitraonka** [comment]
@mschering how are you using datepicker for birthdate? the ouput is in utc so the date will differ based on your server location.

**Comment by vividpixel** [comment]
+1

**Comment by harudragneel** [comment]
+1

**Comment by gogakoreli** [comment]
+1

**Comment by vitaly-t** [comment]
This is by far the longest-living and the most ignored P1 bug. How did Material even get released without this fixed...? And now it just seems abandoned. What's going on, guys?

**Comment by julianobrasil** [comment]
@vitaly-t, it's not abondoned. This feature has already been implemented and will probably be available in the next minor release: #8565

**Comment by ahmadsolehin** [comment]
how to solve this issue?

**Comment by julianobrasil** [comment]
Upgrade material to the latest version.

**Comment by Benno007** [comment]
Is it possible to go from e.g. month mode, and the period saying 'May 2018' to 'year mode' and the period saying '2018', then clicking '2018' takes you to multi year mode?

**Comment by julianobrasil** [comment]
@Benno007, I'm affraid there isn't such feature. Maybe an `@Output()` that emits when the user clicks on the period button is enough (as you can just close reopen the calendar in the desired mode). You can open a new issue requesting for this feature.

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
