### ISSUE TITLE
md-input shows X in IE when focused

### ISSUE THREAD

**Issue by dhuallanca** [angular/material2#5846]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Don't show X when focused

#### What is the current behavior?
X is displayed only in IE

#### What are the steps to reproduce?

https://plnkr.co/edit/VSPi8YupGhNujYpj36OS?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Other browsers don't display X

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular: ^4.2.6
angular/material: ^2.0.0-beta.8
IE: 11.0.9600

**Comment by kara** [comment]
This sounds like something specific to IE's implementation of input. Some applications may want to keep the behavior (esp. given that this is typical user experience for IE), so we don't want to be too prescriptive about removing it for everyone.  If you'd like to hide it in your app on IE, there are [ways to do so with CSS](https://stackoverflow.com/questions/13481577/how-can-i-disable-the-clear-button-that-ie10-inserts-into-textboxes).
