### ISSUE TITLE
DataTable - Update Example with multiple features included

### ISSUE THREAD

**Issue by fad250** [angular/material2#5848]
The sample example for DataTable should include ways to use both sorting and filter feature, or documentation on how to add more than one feature in md-table. The implementation of this process is not very straightforward.

**Comment by willshowell** [comment]
For the case of sorting + filter, what do you find makes it difficult to combine them?

* Building the template
* Triggering changes
* Sorting and filtering the data simultaneously

**Comment by fad250** [comment]
The issue I am facing is when I am triggering changes, I am only getting results for one feature.

**Comment by willshowell** [comment]
All that really matters is that in `connect()`, you must make sure that your return Observable is correctly mapping trigger events to the right results.

1. In the sorting example, you map the observable to a *sorted* array of `_exampleDatabase.data`
2. In the filtering example, you map the observable to a *filtered* array of `_exampleDatabase.data`

So really all you need to do is take your data, sort it, and filter it (or filter and then sort).

```ts
return Observable.merge(...displayDataChanges).map(() => {
  
  return this.getSortedData()
    .filter((item: UserData) => {
      let searchStr = (item.name + item.color).toLowerCase();
      return searchStr.indexOf(this.filter.toLowerCase()) != -1;
    });
  
});
```

**Comment by andrewseguin** [comment]
Here's an example of a table that includes pagination, sorting, filtering, and selection.

https://plnkr.co/edit/EU3BBlViWpPf2NJW4PXx?p=preview

The code is actually already in the repo as `table-overview-example` but we have yet to include it into the docs site due to some theming issues. Will leave this issue up until we do so.

**Comment by fad250** [comment]
@andrewseguin and @willshowell Thank you. This really helped!

**Comment by uday4vunnam** [comment]
@andrewseguin thank you for the plunker link. That helped! Can you please provide an example with server side pagination. I am actually stuck in implementing this with http call

**Comment by willshowell** [comment]
@uday4vunnam See https://github.com/angular/material2/pull/5766!

**Comment by uday4vunnam** [comment]
@willshowell Wow! thank you so much
