### ISSUE TITLE
md-button defaults to type='submit' inside forms

### ISSUE THREAD

**Issue by randyaa** [angular/material2#5851]
#### Bug, feature request, or proposal:
This isn't really a bug. I'm sure there's a conscious decision somewhere I just haven't been able to find it and i'm curious what the correct way to handle this problem is. We had a custom button component and have since migrated to md-button. My _hope_ was just that md-button took care of this for us (as our own button component did) but it doesn't.

#### What is the expected behavior?
Per the HTML5 spec : 
The [HTML5 spec explicitly states what happens in implicit submissions](https://www.w3.org/TR/html5/single-page.html#implicit-submission):

> A form element's default button is the first submit button in tree order whose form owner is that form element.
> 
> If the user agent supports letting the user submit a form implicitly (for example, on some platforms hitting the "enter" key while a text field is focused implicitly submits the form), then doing so for a form whose default button has a defined activation behavior must cause the user agent to run synthetic click activation steps on that default button.

#### What is the current behavior?
This is exactly what happens in chrome but some other browsers handle this differently. In our SPA regardless of positioning of the buttons we almost _ALWAYS_ want them to be buttons not submit buttons.

#### What are the steps to reproduce?
Hit 'ENTER' within an input that's part of a form where there's a button that you don't want pressed as part of your 'submit'
http://plnkr.co/edit/6fe87xHiziIJBi4pmr2b?

#### What is the use-case or motivation for changing an existing behavior?
Providing this ability via md-button (but with the ability to override) would eliminate type="button" across every button in SPAs

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

#### Is there anything else we should know?
It's likely this issue will be closed without a solution and that's ok it's just an annoyance for something that can be fixed pretty easily within the material codebase. I'd like to see a rationale for why we don't want to fix this within material or what we're possibly missing that could be a reason not to do this.

@christiaan-lombard made a suggestion that seems ok but is a bit brute force especially if there's a need to override the behavior for some buttons:
```
import { Directive, ElementRef, Input } from '@angular/core';

@Directive({ selector: 'form button' })
export class ButtonDirective {
    constructor(el: ElementRef) {
       el.nativeElement.type = "button";
    }
}
```

**Comment by willshowell** [comment]
I think the suggestion you listed is a good option. Maybe try this,

```
@Directive({ selector: 'form button:not([type])' })
...
```

**Comment by jelbourn** [comment]
In Angular Material we don't change any of the native `<button>` behavior, including the `type`. While `type=""submit"` is an unfortunate behavior, it is the default on the web platform. Making your own directive to do this as @willshowell mentioned is a good idea.
