### ISSUE TITLE
Feature Request: Make the slider have two pins, to cover x - y range, not just 0 - x

### ISSUE THREAD

**Issue by jordandreassen** [angular/material2#5861]
#### What is the use-case or motivation for changing an existing behavior?
use the slider for 'rent per week'. Many people want to exclude those properties that are too low for them, for example - want slider to cover 300-500 per week rent, and don't care for 0 - 300. Currently returns 0 - 500.

**Comment by donroyco** [comment]
It's called a range slider, and as @jelbourn mentioned in #4613, they don't have any plans yet to implement this. Please use the search function before asking duplicate questions.

**Comment by jelbourn** [comment]
We may someday do this, but it is not currently planned / scheduled.
