### ISSUE TITLE
md-slider doesn't work correctly in the Safari mobile browser

### ISSUE THREAD

**Issue by ndolson1** [angular/material2#5872]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The slider track and the md-slider-thumb stay connected

#### What is the current behavior?
The slider track and the md-slider-thumb disconnect

#### What are the steps to reproduce?
Open angular.material.io and go to the slider component on a iOS device running 10.2 or 10.3. (these are the ones I've tested, the issue could exist in other iOS versions) We are using the vertical option for the slider but the issue occurs in the horizontal layout as well.
Slide up and down multiple times, go off the thumb button a little, hit the track, etc. (be a curious user)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
  "dependencies": {
    "@angular/animations": "^4.0.1",
    "@angular/cli": "^1.1.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.3",   <<<<<<<<<<tried in beta.7 as well
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular2-text-mask": "^8.0.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "ng2-scroll-to": "^1.0.7",
    "rxjs": "^5.1.0",
    "text-mask-addons": "^3.5.1",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^4.1.3",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "angular-swipe": "^0.4.0",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"

#### Is there anything else we should know?
Some screen shots:

![image](https://user-images.githubusercontent.com/25799193/28369513-d64adf9e-6c65-11e7-83e3-7402fdff4627.png)

![brokenslider](https://user-images.githubusercontent.com/25799193/28369632-343809ec-6c66-11e7-8732-5cc7e7927ee7.png)

**Comment by donroyco** [comment]
I can reproduce this issue on an iPone 6s with iOS 10.3.2. I also could move the slider bar without the knob (see picture 2). I think it has something to do with the focus timeout, but I'm not 100% sure.

![md-slider on iOS issue](https://user-images.githubusercontent.com/1763537/28383577-e377423c-6cc1-11e7-9508-762703f4f5e8.jpg)

![md-slider on iOS issue - move slider](https://user-images.githubusercontent.com/1763537/28383585-ef16952a-6cc1-11e7-8833-3b4be483e868.jpg)
