### ISSUE TITLE
md-cell: bound class variables overwrite standard data

### ISSUE THREAD

**Issue by mcalmus** [angular/material2#5876]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
bound style class is added to list

#### What is the current behavior?
The bound style class is the only one listed

#### What are the steps to reproduce?
Add [class]="somevar" to an md-cell. All standard style classes (mat-cell, cdk-column-columnName, mat-column-columnName) are then excluded. 
Note that adding class="someclass" works just fine.

https://plnkr.co/edit/SVWgs38PWGsIJP3nyQEc

#### What is the use-case or motivation for changing an existing behavior?
Should be able to programmatically add styles to rows.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material2 beta 8. Angular 4.x, all browsers

**Comment by willshowell** [comment]
I think that's expected behavior, right? Shouldn't you use `ngClass`?

https://plnkr.co/edit/7S8E4htxqVZNM8nOB3x1?p=preview

**Comment by andrewseguin** [comment]
`ngClass` is indeed the recommended approach to applying classes in Angular where you expect multiple directives/components to be modifying classes.
