### ISSUE TITLE
[Table] Add input for sticky columns

### ISSUE THREAD

**Issue by andrewseguin** [angular/material2#5890]
Introduce ability to have sticky columns in the `cdk-table`.

**Comment by ankeshdave** [comment]
@andrewseguin, ne update or work around for having `sticky columns` in either `cdk-table` or `mat-table`

**Comment by andrewseguin** [comment]
No update yet - working right now on improving the docs and the ergonomics of designing what it looks like to make it easier to build out a simple table or make it easy to make modular

**Comment by NAHaley** [comment]
I would use this feature today if it were available. sticky columns in mat-table

**Comment by oomz** [comment]
Yes please add a feature that enables a mat-table column to be sticky, my use case is this:
I have a lot of columns in my table, and I enabled the horizontal scrolling of the table so the columns would not shrink to fit the windows size. My last column in the table is where my 'actions' column is located: add, edit delete. So for the user to see those buttons they have to scroll to the right. but it would be very nice if I can make that column always stick to the right so it is always visible by the user.

**Comment by andrewseguin** [comment]
Yes this works and should be closed. https://material.angular.io/components/table/overview#sticky-rows-and-columns

**Comment by andrewseguin** [comment]
Feel free to open an issue with a reproduction in StackBlitz so we can investigate and make a fix
