### ISSUE TITLE
datepicker: min and max property updates do not update validation

### ISSUE THREAD

**Issue by RobYed** [angular/material2#5896]
#### Bug, feature request, or proposal:
datepicker bug: `min` and `max` property updates do not update validation

#### What is the expected behavior?
The validation of the datepicker is updated on input binding changes.

#### What is the current behavior?
If the `min` and/or `max` input bindings change, the datepicker's pickable range will update accordingly, but the validation won't. Thus, an `mdDatepickerMax` error is attached to the form, although there is no actual error.

#### What are the steps to reproduce?
1. Create a container component and initialize a max date, say `someMaxDateFromComponent`
3. Initializa a `FormGroup` with a `FormControl`, say `someControl`
2. Add a datepicker to the template:
`
     <input
        formControlName="someControl"
        mdInput
        [mdDatepicker]="someDatepicker"
        [max]="someMaxDateFromComponent">
`
3. Change the max date `someMaxDateFromComponent` to some other date
4. Choose a date which was invalid before and is valid after the change in (3)
5. Check the error state of the `someControl`

I'll also try to provide a plunkr later.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.2.5
Material: 2.0.0-beta.7
OS: Windows 7
TypeScript: 2.2.2
Browsers: Chrome 60

#### Is there anything else we should know?
You are doing a great job!

**Comment by mmalerba** [comment]
Seems to work fine for me, a plunker would be helpful: http://plnkr.co/edit/UzxvOFegtYRkztD8t4G9?p=preview

**Comment by mmalerba** [comment]
Closing since I am unable to repro. Please comment with additional information if you are still seeing the issue

**Comment by RobYed** [comment]
I am sorry, I was not able to reproduce it in a plunkr. I have an idea of the problem and will come back if I think it is related to Angular Material.

**Comment by fannyfrey** [comment]
Hi, have you found the solution for this? I seem to have encountered the same problem with you.

**Comment by RobYed** [comment]
Hey @fannyfrey. It is now a while ago that I was working on this. But what I remember is, that I have somehow worked around it, as I have not found a satisfactory solution. I had the feeling that there was some side effect between the datepicker and a custom component/behaviour. But I was not able/had not enough time to locate it. Sorry.
