### ISSUE TITLE
datepicker: selected date circle is out of center in mobile

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#5897]
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

The selected day and today circle to be vertically centralized around the date number in mobile devices

#### What is the current behavior?

Both are not vertically centralized in mobile devices (at least in my Android).

![image](https://user-images.githubusercontent.com/25405143/28411651-d627af8a-6d17-11e7-8178-0f3dd0a4283e.png)

#### What are the steps to reproduce?

Open the [material.angular.io](https://material.angular.io/components/datepicker/overview) site in an Android device.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Android device, Chrome App

**Comment by BobBDE** [comment]
Seems ok in IOS in both Chrome and Safari app

![img_3546](https://user-images.githubusercontent.com/16068649/28424491-014f6172-6d2b-11e7-8a54-f94b13e4449b.PNG)
