### ISSUE TITLE
Paginator doesn't update visually when changing properties by code

### ISSUE THREAD

**Issue by michelcve** [angular/material2#5904]
#### Bug, feature request, or proposal:
Paginator doesn't update visually when changing by code (e.g. setting length).

#### What is the expected behavior?
Visually the paginator should update when we change one of the properties by code.

#### What is the current behavior?
When changing the length property for example, internally the paginator does change it's values. However, visually the component is not updated (old length remains on screen)

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

http://plnkr.co/M4tqI5WjV01fvzzNGkit

#### What is the use-case or motivation for changing an existing behavior?
I'm using the paginator with a data table, which has it's data loaded asychronously. Only when the response is in, I'll know how many records are available, so I want to update the 'length' property of the paginator at that point through code.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Most recent in plnkr.

**Comment by willshowell** [comment]
Why not bind to the input? http://plnkr.co/edit/v8YKBrRYGftRP7S2orsu?p=preview

The paginator uses OnPush change detection so changes must come through the `Input()` binding to immediately trigger a rerender.

**Comment by michelcve** [comment]
Didn't know that, sorry. Thanks for the explanation!

**Comment by willshowell** [comment]
@michelcve Same thing goes with the output, in many cases, it'll help simplify your components to bind to the `page` event rather than subscribe to it.

http://plnkr.co/edit/v8YKBrRYGftRP7S2orsu?p=preview

**Comment by andrewseguin** [comment]
Note that we will eventually support changing the properties directly, in the case where you did not set an `@Input` binding on the paginator. #5822

**Comment by michelcve** [comment]
Thanks for the extra example @willshowell !

@andrewseguin ah yes, the MarkForCheck, that was indeed what I thought was missing. But willshowell's solution with binding to the @Input I missed ;-)
