### ISSUE TITLE
[Table] CdkTable doesn't automatically connect to data source when using OnPush

### ISSUE THREAD

**Issue by willshowell** [angular/material2#5914]
#### Bug, feature request, or proposal:
Bug

#### Current behavior
`dataSource.connect()` is not subscribed to until the second `ngDoCheck ` hook, which must be triggered manually when using OnPush in the parent component.

#### Expected behavior
Data source is connected as soon as possible, not requiring an extra check

#### Workaround

```ts
constructor(private cd: ChangeDetectorRef) { }

ngOnInit() {
  this.dataSource = new ExampleDataSource(this.exampleDatabase);
  setTimeout(() => this.cd.markForCheck());
}
```

#### What are the steps to reproduce?
Reproduction: https://plnkr.co/edit/ACvDB3mUsNIIyOC16vpu?p=preview
Workaround: https://plnkr.co/edit/4p0pnAvmfYjIwWMXSqud?p=preview

**Comment by andrewseguin** [comment]
Thanks Will, we've got a PR open that will resolve this - #5775. This was similar to the issue we were having with router changes not rendering the table.
