### ISSUE TITLE
Expansion icon animation is bugged

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#5926]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

When grouped in an accordion (multi=false) and you click in an expansion, the actual opened one should close and its toggle icon should point downwards.

#### What is the current behavior?

If you start expanding/collapsing the expansions by clicking in the header of other panels, the toggle icon is not being updated. And when it is, the animation is not smooth.

![](http://i.imgur.com/PF9Tu1m.gif)

#### What are the steps to reproduce?

1 - Open one panel
2 - Click in the header of the other panel and see the toggle icon freezed in the upward direction

Plunk: https://plnkr.co/edit/lmR0Fp?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest build (see the plunk)

**Comment by julianobrasil** [comment]
@mackelito

**Comment by crisbeto** [comment]
Should be fixed by https://github.com/angular/material2/pull/5650.
