### ISSUE TITLE
md-select set selected Value after options are initialize dont work

### ISSUE THREAD

**Issue by dark0ni** [angular/material2#5929]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When options are initalize, it is not possible to change/set selectedValue afterwards.
For example when I get the selectedValue via http call
#### What is the current behavior?
md-select stays empty

#### What are the steps to reproduce?

```
 <md-select  placeholder="Rights" name="userRole" [(ngModel)]="selectedUserRole">
                 <md-option *ngFor="let role of userRoles" [value]="role.value">
                            {{ role.viewValue }}
                 </md-option>
</md-select>
```

```
userRoles = [
        {value: "FIRM_ADMIN", viewValue: 'Admin'},
        {value: "B2B_USER", viewValue: 'Standartuser'},
    ];

private getUserDetails(userId:number)
    {
        this.userRestService.getUserById(userId).subscribe
        (
            (response) =>
            {
                this.user = response;
                this.selectedUserRole = this.userRestService.getHighestUserRole(this.user);
            }
        );
    }
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
        "@angular/material": "^2.0.0-beta.8",
        "@angular/core": ">=4.0.0-beta <5.0.0",

**Comment by crisbeto** [comment]
Have you tried adding a `changeDetectorRef.markForCheck()` call after you assign the value? Depending on how this call is made, it's possible that the value isn't picked up by Angular's change detection.

**Comment by dark0ni** [comment]
Unfortunately it doesn't work. 

Here is the implementation with ChangeDetectionStrategy:

```
@Component({
    selector: 'app-user-administration-edit',
    templateUrl: './user-administration-edit.component.html',
    changeDetection: ChangeDetectionStrategy.OnPush,
    styleUrls: ['./user-administration-edit.component.scss']
})
 
...

    constructor(private router: Router, private route: ActivatedRoute, private userRestService:UserRestService, private ref: ChangeDetectorRef) { }

 private getUserDetails(userId:number)
    {
        this.userRestService.getUserById(userId).subscribe
        (
            (response) =>
            {
                this.user = response;
                this.selectedUserRole = this.userRestService.getHighestUserRole(this.user);
                this.ref.markForCheck();
            }
        );
    }
```

**Comment by crisbeto** [comment]
Sorry, I meant that you should use `changeDetectorRef.detectChanges()`. That being said, the select won't pick up the change properly with the current setup anyway. I'll see what I can do to sort it out. As a workaround, you can wrap the `this.selectedUserRole = this.userRestService.getHighestUserRole(this.user);` call in a `setTimeout`.

**Comment by dark0ni** [comment]
@crisbeto thank you for your help, but `changeDetectorRef.detectChanges()` and` setTimeout` had also no effect on md-select.
