### ISSUE TITLE
[Tabs] Textarea value is not immediately shown when tab comes in

### ISSUE THREAD

**Issue by skyfremen** [angular/material2#5932]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
TextArea with md-autosize inside a md-tab should show the initial ngModel value in the 2nd Tab and above.  

#### What is the current behavior?
Currently the initial value is only visible for the 1st Tab. For the 2nd Tab and above it is not visible until user type something into the textbox

#### What are the steps to reproduce?
Step 1) Verify that the mdInput md-autosize work as expected in Tab 1 & Outside of the Tab
Step 2) Click on Tab 2, the ngmodel value is not visible however the word count is correct
Step 3) Click on the Textarea in Tab 2 and type, value is now visible.   
Plunker template: https://plnkr.co/edit/d7ypZ7afCMgAmV425Ohz?p=preview

#### What is the use-case or motivation for changing an existing behavior?
TextArea should be able to display initial value.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta 8
Angular 4.3.1
Typescript 2.4.2
Chrome OS

#### Is there anything else we should know?
NA

**Comment by julianobrasil** [comment]
Maybe related to #5269.
