### ISSUE TITLE
Angular Material STABLE planned ?

### ISSUE THREAD

**Issue by ericreboisson** [angular/material2#5933]
"Angular Material is currently in beta" when do you plan to deliver a stable release ?

**Comment by ericreboisson** [comment]
I follow the project evolution since several month and at this moment we use Materialize CSS in our company. We believe that Angular Material will be the best solution but we do not want to beta test the framework since now ( bug fear , it was so difficult last year to follow Angular evolutions...) we already have Angular + material CSS in production at this moment and we hope a stable Angular material soon or we will have too much application to migrate.

**Comment by jelbourn** [comment]
We haven't announced an official date for this yet; stay tuned to the [Angular blog](https://blog.angular.io/) for future announcements.
