### ISSUE TITLE
md-menu : action outside opened menu

### ISSUE THREAD

**Issue by holy31** [angular/material2#5938]
#### Bug, feature request, or proposal:

Feature request
Close an opened menu when clicking on any other button/link/input/menu and trigger the desired action, at least for desktop version.

#### What is the expected behavior?
When a user opens a menu and wants to execute an other action (click on button...), the menu closes and the desired action is completed

#### What is the current behavior?
When a user opens a menu and wants to execute an other action, he has to click two times : one time to close the menu, and a second time to complete the desired action. Consequently, the navigation isn't very smooth.

#### What are the steps to reproduce?
Can be reproduced here : https://material.angular.io/components/menu/examples :)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "2.0.0-beta.8"

**Comment by andrewseguin** [comment]
To be consistent for users and align with the material design spec, I don't believe this change can be made. 

https://material.io/guidelines/components/menus.html#menus-simple-menus

`Touching outside of the menu, or pressing the system Back button, cancels the action and closes the menu.`
