### ISSUE TITLE
<md-dailog> unusual behaviour, It hides the fixed-div on trigger at somewhere bottom of app

### ISSUE THREAD

**Issue by TomarAditya** [angular/material2#5952]
#### Bug, feature request, or proposal:
Actually i'm working on Angular 4 with material2 design , so i came across `<md-dialog>` , decided to use in my app.
 
App contain a header i.e _fixed_ `position:fixed` and a sidebar _fixed_ as well.

i used `<md-dialog>` and yup it works fine until page is **not scrolled** , but when page scrolls somewhere at bottom of page, on click of button that trigger `<md-dialog>` a unusual behaviour arises that the **fixed position** _div_ hides behind the `<md-dialog>` 

working plunker : [https://plnkr.co/edit/1F5La3HPmd8RxXtPip3o?p=preview][1]

  [1]: https://plnkr.co/edit/1F5La3HPmd8RxXtPip3o?p=preview
Any help to remove that behaviour ? 

#### What is the expected behavior?
`<md-dialog>` contents should be on top of `fixed-div` as well.

#### What is the current behavior?
on triger of `<md-dialog>` at somewhere bottom of app , it hides the `fixed-div` 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
_apart from attached plunker_ it's tested in **angular4 with material2** same issue with this configuration as well

**Comment by joejordanbrown** [comment]
Adding CSS top property fixes that problem. Check out https://plnkr.co/edit/z9Np0J?p=preview

**Comment by TomarAditya** [comment]
Thanks @joejordanbrown
