### ISSUE TITLE
Tree Component

### ISSUE THREAD

**Issue by OpsRJ** [angular/material2#5964]
#### Bug, feature request, or proposal:
I would like to request a Tree View Component.

#### What is the expected behavior?
The hability to select, add, remove or edit items/nodes to build a Tree structure

#### What is the current behavior?
It should create a Tree View component

#### What are the steps to reproduce?
Could be something like this:

children: [
          {
            children: [
              {label: 'Watermelon', leaf: true, type: 'check'},
              {label: 'Apricot', leaf: true, type: 'check'},
              {label: 'Pineapple', leaf: true, type: 'check'},
              {label: 'Kiwi', leaf: true, type: 'check'},
              {label: 'Orange', leaf: true, type: 'check'},
              {label: 'Pomegranate', leaf: true, type: 'check'}
            ],
            expanded: true,
            label: 'Fruits'
          }
]

**Comment by luanmm** [comment]
It's already in progress, @OpsRJ. Please refer to this (as stated in the [README.md](https://github.com/angular/material2)): https://github.com/angular/material2/issues/3175.

A demo for what seems to be the progress of the component till now: https://tina-material-tree.firebaseapp.com/simple-tree.

**Comment by mydaypower1** [comment]
The MD tree is an exceting component and very expect it to release, Many thanks for all of you contribution. Could you please let us know when could this feature release if possible, Even if it's a trial function.

Thanks and Best regards...
Albert

**Comment by dev-fullstacktechnology** [comment]
Hello, Is there any plan of launching Material Tree component soon? I need it in my project with drag and drop feature.

**Comment by maher1991** [comment]
Can anyone please share the code source of the tree existing in this page: https://tina-material-tree.firebaseapp.com/simple-tree
I want to know how the border lines between the nodes are generated.

**Comment by stoto34** [comment]
This component will be customizable ? I'm looking for a tree component with a filter and no checkbox.

**Comment by benb7760** [comment]
@stoto34 it's customizable - you provide your own template for nodes and can lay each node out however you wish

**Comment by stoto34** [comment]
Great, can you tell me when this component will be available ? :)

**Comment by benb7760** [comment]
@stoto34 I can't as I don't work for Google. I have my own build of material right now which includes the tree branch. It's fairly featured at present so my unofficial guess is anywhere between 1 month and 6 months!

It can be found [here](https://github.com/angular/material2/tree/tree). It is fairly frequently rebased onto master

**Comment by GGSMNandathilaka** [comment]
@benb7760 Is there any update of the release date of Material tree component ?

**Comment by dreamid27** [comment]
when it releases?
