### ISSUE TITLE
data-table loading and empty data text

### ISSUE THREAD

**Issue by zh99998** [angular/material2#5965]
#### Bug, feature request, or proposal:
feature request

there is a common usage showing text to tell apart loading or empty data. currently it's complex to do with `md-table`

it will be much simplify to have a direct API.
```
<md-table 
loading="Loading data..." // before dataSource emit any result.
empty="No result to show" // dataSource emitted a empty array.
>
```
or 
```
<md-table>
<md-table-loading><p>a complex html text for loading</p></md-table-loading>
<md-table-empty><p>yet another complex html text</p></md-table-empty>
</md-table>
```

**Comment by andrewseguin** [comment]
Check out this example to see what it would look like to include loading, using a simple div next to the table. https://plnkr.co/edit/VAvjp7t5jqtUKfHv4ogM?p=preview

Since the table is focused on the rows (not the header or paginator, or any other surrounding elements), its already available to the user to implement something similar to `<md-table-loading>` which can be showed with an `*ngIf`

**Comment by mikejohanson** [comment]
Hey @andrewseguin, would it be possible to update the plunker so that the `Expression has changed after it was checked` error isn't thrown when updating the isLoading property?

**Comment by mdelorimier** [comment]
@andrewseguin  Any ways to display a loading indicator untill the table rendering completes?
Or, to have "skeleton" rows while the real rows are being rendered?

**Comment by iamwhitebox** [comment]
I've noticed @andrewseguin your example only works if there is always results in the datatable, it never gets past switchMap() if the results are an empty array, how to compensate for this?

**Comment by iamwhitebox** [comment]
This works with a single http request, but fails to work when using a BehaviorSubject to periodically update results on the table - if the results are empty, the loader just hangs there.

**Comment by CodAffection** [comment]
try this. 

_app.component.ts_

   ```
 listData: MatTableDataSource<any>;
    //assume no. of column = 6
```
      
_app.component.html_


    ```
//after ng-containers with mat-header-cell & mat-cell
    <ng-container matColumnDef="loading">
       <mat-footer-cell *matFooterCellDef colspan="6">
          Loading data...
       </mat-footer-cell>
    </ng-container>
    <ng-container matColumnDef="noData">
       <mat-footer-cell *matFooterCellDef colspan="6">
          No data.
       </mat-footer-cell>
    </ng-container>
    <mat-footer-row *matFooterRowDef="['loading']" [ngClass]="{'hide':listData!=null}">
       </mat-footer-row>
    <mat-footer-row *matFooterRowDef="['noData']" [ngClass]="{'hide':!(listData!=null && listData.data.length==0)}">
       </mat-footer-row>

```
_style.css_

  ```
  .hide{
        display: none;
    }
```
