### ISSUE TITLE
[Tabs] Position should not be exposed in documentation

### ISSUE THREAD

**Issue by zbagley** [angular/material2#5969]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When setting the `<md-card position=number>` it should position the tab relative to other position numbers.

#### What is the current behavior?
position is ignored

#### What are the steps to reproduce?
https://plnkr.co/edit/Wp2JJ5hS9QwCyZLWqDEn?p=info

#### What is the use-case or motivation for changing an existing behavior?
When using tabs being able to dynamically position is important (generating in ngFor).

**Comment by julianobrasil** [comment]
It's not decorated as an `@Input` property in the code. Aparently the docs tool exposes all multiline code comment.

**Comment by zbagley** [comment]
I assumed that position was supposed to be an Input property, apologies on that. Been working with Anguar (2+) for a year and a half now, and quite aware of most the basics like ngFor. More or less I want to be able to dynamically change the position, and assumed that's what this position reference was for.

An example where I trying to change the position within the component:
https://plnkr.co/edit/BiNilXWtZluK4xTMD4qv?p=preview
The position is reset to zero every time I attempt to change it.

Is there documentation on how to access these properties properly? This has come up many times on StackOverflow, and am curious (and kind of confused the documentation shows the API, but there's no reference on how to actually use it).

**Comment by julianobrasil** [comment]
Have you tried with `@Viewchild`?

**Comment by zbagley** [comment]
Yeah, that was the last plunker

**Comment by zbagley** [comment]
```
import {ViewChild,Component} from '@angular/core';
import {MdTabsModule} from '@angular/material';

@Component({
  selector: 'tabs-overview-example',
  templateUrl: 'tabs-overview-example.html',
})
export class TabsOverviewExample {
   @ViewChild('tab') tab: MdTab;
   @ViewChild('tab2') tab2: MdTab;

   click1(){
     this.tab.position = 1;
     this.tab2.position = -1;
     console.log(this.tab.position);
     console.log(this.tab2.position);
   }
   click2(){
     this.tab.position = -1;
     this.tab2.position = 1;
     console.log(this.tab.position);
     console.log(this.tab2.position);
   }
}

```

Is the component code. More or less this.tab.position will output the right value, but this.tab output will go right back to 0.

**Comment by julianobrasil** [comment]
Oh, Sorry. I'm typing from my android and not able to visualize plunks correctly.

**Comment by willshowell** [comment]
At first glance of the source, it looks like position is an internal property that marks how the tabs content should display. E.g. a value of 0 is the current showing tab body and -1 is the left (or before) tab body and 1 is the right/after body.

I think this property needs a leading underscore to mark it as internal only

**Comment by julianobrasil** [comment]
@zbagley, [this line of code](https://github.com/angular/material2/blob/374aaffa83b94cd154a6bfcf7391b34c24282d52/src/lib/tabs/tab-group.html#L34) shows that property used in md-group and bound to an `@Input()` property of md-tab-body. The latter, int turn, uses it in animation, only, as it's shown in [these other lines of code](https://github.com/angular/material2/blob/374aaffa83b94cd154a6bfcf7391b34c24282d52/src/lib/tabs/tab-body.ts#L67-L111).

As @willshowell pointed out it's just a rerefence for internal use. My gess is that it's used to decide the direction of the animation of the tab body when you click on tab header (contents entering the screen from the right or from the left).

**Comment by zbagley** [comment]
@julianobrasil, So does that mean the API documentation should be changed, and not the position code itself?

API Documentation for md-tab:

```
templateLabel | Content for the tab label given by.
@Input('label')textLabel | The plain text label for the tab, used when there is no template label.
content |  
position | The relatively indexed position where 0 represents the center, negative is left, and positive represents the right.
origin | The initial relatively index origin of the tab if it was created and selected after there was already a selected tab. Provides context of what position the tab should originate from.
```
If it's an internal item only it doesn't seem like it should be represented as part of the Interface options.

**Comment by julianobrasil** [comment]
Yes, @zbagley, I agree with https://github.com/angular/material2/issues/5969#issuecomment-317222289 that it should have a leading underscore (to not be visible in interface docs).

**Comment by zbagley** [comment]
If you need someone to fix that I'm open to. All that needs to be changed changing all references to position to underscores (i.e. documentation is auto-generated)?

**Comment by julianobrasil** [comment]
Go for it and submit a PR. Yeah, the docs are auto-generated.

**Comment by willshowell** [comment]
@zbagley while you're touching this, would you mind making a few other small doc changes for md-tab? If you don't care to, I'll take a crack later, but it would help clean up the tab api documentation page a lot!


1. `templateLabel` has a jsdoc comment that needs backtick escaping  (`<ng-template md-tab-label>`)
2. I think `origin` should also not be exposed (leading underscore)
3. `get content()` should switch positions with `private _contentPortal` so that the jsdoc comment is immediately preceding `content`


cc @andrewseguin: can you verify `#2` is a correct assumption? Also as to whether `content` should even be exposed to the public?

**Comment by zbagley** [comment]
#5985

**Comment by zbagley** [comment]
Updated these in #5985 

If content should be _content I can update that as well.
