### ISSUE TITLE
MdCheckbox: valueChanges observable emits new value twice

### ISSUE THREAD

**Issue by udos86** [angular/material2#597]
#### What is the expected behavior?

`valueChanges` observable of MdCheckbox form control should emit new value only once when corresponding ngModel is updated programmatically

#### What is the current behavior?

`valueChanges` observable of MdCheckbox form control emits new value twice corresponding ngModel is updated programmatically

#### What are the steps to reproduce?

See this plunker: http://plnkr.co/edit/55wf5BxZ1cmHdFgEeu4K?p=preview

Open DevTools console and click test button --> current value is logged twice

#### What is the use-case or motivation for changing an existing behavior?

Performance

**Comment by DevVersion** [comment]
This is a known issue and should be fixed with SHA d037ed3ea8d13384a34e3d23cacf4e5bcd2b9f4d. I will confirm this with your plunker later.

**Comment by jelbourn** [comment]
Fixed by #551
