### ISSUE TITLE
Expansion Panel hideToggle typo in docs

### ISSUE THREAD

**Issue by mackelito** [angular/material2#5975]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
the docs should say hideToggle 

#### What is the current behavior?
 toogleHide

#### What are the steps to reproduce?
https://github.com/angular/material2/blob/385272e5d3fb820a3cac52de6a5b1b852f0ef703/src/lib/expansion/expansion.md

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by willshowell** [comment]
I think you're looking at @julianobrasil's unmerged PR https://github.com/angular/material2/pull/5823 as that file does not exist on master

**Comment by julianobrasil** [comment]
😄 I'm going to fix the PR first thing in the morning. Thank you guys.

**Comment by mackelito** [comment]
@willshowell thx! Forgot to mention that 😁

**Comment by julianobrasil** [comment]
Fixed.
