### ISSUE TITLE
slide-toggle: refactor to use checkbox as base

### ISSUE THREAD

**Issue by DevVersion** [angular/material2#598]
The `slide-toggle` component should use the checkbox component as its base (as discussed in #90).

We planned three steps for the slide-toggle component.
- [X] Basic Skeleton
- [ ] Refactor to use Checkbox as base
- [x] Add Dragging functionality  (Tracking in #600)

**Comment by jelbourn** [comment]
Some of the code should also be reusable in the forthcoming button-toggle #517

**Comment by DevVersion** [comment]
Let's use #610 to track this issue.
