### ISSUE TITLE
Tab options like ripple, stretch, colors/theming, icons

### ISSUE THREAD

**Issue by kyleledbetter** [angular/material2#599]
#### Feature request:

Obviously the first pass at tabs was MVP, but it would be lovely to get some options back from v1:

- Colors & Theming: I'd expect something like the toolbar `<md-tab-group color="primary">`
- Ripple when clicking an `md-tab-label`
- Stretch tabs (though a simple flex-grow:1 on tab labels can achieve this now)
- Icons: md-icons current don't render in tabs

**Comment by jelbourn** [comment]
More work on tabs is forthcoming, alpha.5 was indeed just the initial version. Going to close this since it's not really focused enough to be an actionable issue. The `<md-icon>` thing sounds like a bug, though.

**Comment by codegastudio** [comment]
Hi
` flex-grow:1` did work fr you ?

```
<md-tab-group *ngIf="box">
  <md-tab >
    <template md-tab-label style="flex-grow:1" >One</template>
    <template md-tab-content>
      <h1>One</h1>
      <p>...</p>
    </template>
  </md-tab>
    <md-tab>
    <template md-tab-label style="flex-grow:1"> Two </template>
    <template md-tab-content>
      <h1>Two</h1>
      <p>...</p>
    </template>
  </md-tab>
</md-tab-group>
```
