### ISSUE TITLE
[Table] Plunkr example should use toLowerCase to sort columns

### ISSUE THREAD

**Issue by Lakston** [angular/material2#5991]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
The plunkr example should use toLowerCase when sorting properties to cover a more general use case.

#### What is the current behavior?
The [current table example](https://plnkr.co/edit/EU3BBlViWpPf2NJW4PXx?p=preview) uses data where all first letters are uppercase so sorting behaves as intended but when used with mixed cases data the sorting will not work properly

#### What are the steps to reproduce?

This is the modified plunkr : https://plnkr.co/edit/BIClDKtNGUtDPzhtRDDj?p=preview

I just added a toLowerCase to the compared properties on line 180 and 181

#### What is the use-case or motivation for changing an existing behavior?
If a user copies and pastes the sorting code (like I did) and uses it with mixed case data it will not work properly.

**Comment by jelbourn** [comment]
Closing since the example now uses library code to perform sorting
