### ISSUE TITLE
Button Press with spacebar

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#5993]
#### Bug, feature request, or proposal:
In native buttons, when we have focus on a button we can use spacebar to press the button. It seems that in case of material buttons we can only use enter/return key to press button.

#### What is the expected behavior?
Material buttons should support press/submit through spacebar when focus is on the button.

**Comment by DevVersion** [comment]
Tried to reproduce this in the demo-app of Material, but everything seemed to work.

Can you please provide a Plunker that shows the issue?

**Comment by naveedahmed1** [comment]
Ok, I just noticed that it doesn't work when used with anchor tag like this:

<a md-raised-button>Cancel</a>

**Comment by andrewseguin** [comment]
Hey @naveedahmed1 - this is expected behavior for `<a>` elements and appropriate for accessibility.
