### ISSUE TITLE
angular material doesn`t render when it is being got from API

### ISSUE THREAD

**Issue by pukuotas** [angular/material2#5994]
hello

#### What is the current behavior?
angular material cards render as simple html div with no shadows

#### What are the steps to reproduce?

`<div [sanHtml]="pageHTML"></div>`

`   this.http._get(GLOBAL.url + "/api/GetPageHTML").subscribe((data) => { this.pageHTML = data[0]['pageHTML']; 
`

#### What is the use-case or motivation for changing an existing behavior?

I would like to be possible to read angular material componets as html from database

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.1.3
angular/material 2.0.0-beta.2

#### Is there anything else we should know?
 I use database to store html. I use sanitizing, but it renders like as simple div, though sanitize works.

**Comment by willshowell** [comment]
Angular doesn't work this way

https://stackoverflow.com/a/40474494/4811678
https://stackoverflow.com/a/36408622/4811678

**Comment by pukuotas** [comment]
thanks for documentation, but it still only sanitizes, but no material happens.

could you help help me because I hoped I`ll get out of it but it seems I got stuck may be because of some lack of my knowledge.

I have AboutComponent which gets html by API and AboutComponentLoader which takes the former as as variable and inserts into ng-container.

here is my code (didn`t include some code fragments because of time and space saving):

**app.module** ngmodule decor. :
`  declarations: [AppComponent,SanitizeDirective,AboutComponent,AboutComponentLoader],
    entryComponents:[AboutComponent,AboutComponentLoader],
    bootstrap: [AppComponent]
    `

**about.component.loader**:

`import { Component } from '@angular/core';

import {NgComponentOutlet } from '@angular/common';

import {ApieComponent } from './apie.component';


@Component({

    template:'<ng-container *ngComponentOutlet="typess"></ng-container>',
    selector: 'about',
 
})

export class AboutComponentLoader  {

    typess = AboutComponent;
}`



**about.component**:

`

@Component({

    templateUrl: '../../app/templates/about2.component.html',

    selector: 'about-xxx',
    providers: [HttpService],
   
    
})

export class AboutComponent implements OnInit {

    public puslHTML: any;

    constructor(private http: HttpService, private activatedRoute: ActivatedRoute) {

    }

    ngOnInit(): void {

        this.activatedRoute.params.subscribe((parms: any) => {
            if (parms.lang) {

             
               this.http._get(GLOBAL.url + "/api/GetAbout").subscribe((data) => { this.pageHTML = data[0]['pageHTML']; 

          
                           
            }
        
        });

    }



}`
