### ISSUE TITLE
Chips & input: deal with multiple lines

### ISSUE THREAD

**Issue by merobal** [angular/material2#5999]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If there is no more space in the current line for the chips and/or for the input, those should be moved to new line. See the materialjs version: https://material.angularjs.org/latest/demo/chips

#### What is the current behavior?
Everything is in the same line, with invisible input if overflowed.

#### What are the steps to reproduce?
Check the demo page: https://merobal.github.io/chips-demo/

#### What is the use-case or motivation for changing an existing behavior?
For small boxes such as search bar the chips&input not really usable.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest.

**Comment by sjova** [comment]
+1

**Comment by kkotak** [comment]
Where is the documentation for using chips with input field and autocomplete?
