### ISSUE TITLE
md-datepicker - should emit selectedChanged when changed by input

### ISSUE THREAD

**Issue by wilker7ribeiro** [angular/material2#6000]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The name and documentation suggests that selectedChanged should emit even when the date selected is changed by input text

#### What is the current behavior?
It is emitted only by the calendar

Plunker template: http://plnkr.co/edit/2TqobMq2CJgm7LJtlK3j

**Comment by rafaelss95** [comment]
For me, it's the expected behavior. To detect input changes you should use `(change)` or even `(ngModelChange)`.

**Comment by DevVersion** [comment]
I think this is also pretty reasonable. 

Although I can also the confusion that people expect the `selectedChanged` output to fire because when changing the input it would also lead to an "actual" change of the selected date.

**Comment by willshowell** [comment]
If it does remain as-is, the jsdoc comment should probably note that it emits when change comes from datepicker specifically.

Currently:
>selectedChanged | Emits new selected date when selected date changes.

**Comment by DevVersion** [comment]
@willshowell Yeah that would be for sure. If the behavior stays the same, the docs need to be more explicit about it.

**Comment by wilker7ribeiro** [comment]
@rafaelss95 (ngModelChange) does trigger even with invalid date, and (change) only triggers on blur or enter key.
Actually, I'm using `mdDatepickerInput._valueChange`, but I'm having issues with validation time

**Comment by rafaelss95** [comment]
@wilker7ribeiro  So, you want to use `(keyup)`?
