### ISSUE TITLE
Expansion-panel's animation adds a margin to the host element

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#6011]
The expansion-panel uses [a margin on the host element for its expansion animation](https://github.com/angular/material2/blob/5cafa2bb0fd6adc13d667497e1d4bfa51705063d/src/lib/expansion/expansion-panel.ts#L69). This goes against out policy of not having margins on host elements. We should refactor this animation to work differently.

**Comment by crisbeto** [comment]
Resolved by https://github.com/angular/material2/pull/6546.
