### ISSUE TITLE
MdTooltip: mdTooltipClass does not pass class

### ISSUE THREAD

**Issue by zbagley** [angular/material2#6013]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mdTooltipClass should pass class to tooltip

#### What is the current behavior?
Tooltip class does not change

#### What are the steps to reproduce?
https://plnkr.co/edit/bg7TbkSBBaiJQKK9G1Nd?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Being unable to style the tooltip renders this feature useless for me.

**Comment by willshowell** [comment]
https://plnkr.co/edit/32OjsJ9agTEzTeC03SBF?p=preview

There are a couple things going on here:

1. The tooltip, along with most other overlay-based components, require that your styles are not view encapsulated. So you must either make your component ViewEncapsulation.None, or add the style to your global stylesheet.
2. `mdTooltipClass` takes the same syntax as `ngClass`. So neither `[mdTooltipClass]="'green'"` or `mdTooltipClass="'green'"` are correct. It should be `mdTooltipClass="green"`.
3. The tooltip already has a `color` style (of white), which will often override your green styling depending on the order the styles are loaded. You should increase the specificity of your selector to something like, `.mat-tooltip.green` to ensure it takes precedence.

**Comment by zbagley** [comment]
1. Could this become a request to change the documentation to include the view encapsulation somewhere?
2. I provided an example use of ngClass in the plunker with the proper syntax as described in the [official docs for ngClass](https://angular.io/api/common/NgClass). Since this doesn't accept the same format I think it'd be good to remove the part that says it does.
3. Notes in docs for this would also be useful.

Thank you for the explanation. Look forward to being able to implement this!

**Comment by willshowell** [comment]
Excuse me, `[mdTooltipClass]="'green'"` is valid, I'm sorry. And it should work just fine for the tooltip.

Also yes, there should be an example somewhere in the tooltip docs, because questions about using tooltip class have come up several times. It would also be good to have notes, maybe in a guide, about customization of overlay components in general that includes information on encapsulation and selector specificity, because that comes up nearly every day and tripped me up a lot at the beginning.

**Comment by jelbourn** [comment]
@zbagley closing this based on explanation from @willshowell. Feel free to open a new issue for any documentation proposals.
