### ISSUE TITLE
cannot render md-* selectors when running ng test

### ISSUE THREAD

**Issue by gabbydgab** [angular/material2#6014]
#### Bug, feature request, or proposal:
I'm trying to practice TDD, but when I run **`ng test`**, it prompts me with the following error:

```js
Failed: Template parse errors:
'md-checkbox' is not a known element:
1. If 'md-checkbox' is an Angular component, then verify that it is part of this module.
2. If 'md-checkbox' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
</div>
<section class="example-section">
    [ERROR ->]<md-checkbox >Disabled</md-checkbox>
</section>"): ng:///DynamicTestModule/AppComponent.html@8:4
```

#### What is the expected behavior?
should also work when running **`ng test`**.

#### What is the current behavior?
It only works for **`ng serve`**

#### What are the steps to reproduce?
Following are the updated files:
**app.module.ts**
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { MdCheckboxModule } from '@angular/material';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    MdCheckboxModule,
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**app.component.html**
```html
<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{title}}!
  </h1>  
</div>
<section class="example-section">
    <md-checkbox >Disabled</md-checkbox>
</section>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.2.4
node: 6.11.0
os: linux x64
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.4
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1

**Comment by willshowell** [comment]
Can you show your test?  You probably aren't importing material components in `TestBed.configureTestingModule`

**Comment by gabbydgab** [comment]
> You probably aren't importing material components in TestBed.configureTestingModule

@willshowell thanks for pointing it out. It works but I'm not sure if it's the right process, since I'm new to angular testing, importing Module on the TestBed within beforeEach.

```typescript
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [
        MdCheckboxModule
      ]
    }).compileComponents();
  }));
```

P.S. Closing issue as resolved.

**Comment by willshowell** [comment]
@gabbydgab There are a dozen or more ways to go about it, but your approach is just fine. I've learned a lot about testing by just going through the specs in this repo.
