### ISSUE TITLE
Angular material Editing Inline Datatables

### ISSUE THREAD

**Issue by victorsolaya** [angular/material2#6015]
#### Bug, feature request, or proposal:

Proposal

#### What is the expected behavior?

Allows edit angular2 datatables

#### What are the steps to reproduce?

Allows to edit fields in a datatable

**Comment by m98** [comment]
Could you please clarify what do you mean from Angular 2 datatables? 
Do you mean Material tables?

**Comment by victorsolaya** [comment]
Of course.

I mean this datatables 
https://material.angular.io/components/table/overview

I would like to edit the data inside the table

**Comment by rodaz** [comment]
duplicate of #5982
