### ISSUE TITLE
Can't implement search and paginator in one table

### ISSUE THREAD

**Issue by brianmituka** [angular/material2#6017]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by Chan4077** [comment]
Can you show us your code?

**Comment by willshowell** [comment]
Heres an example showing http search, sort, and pagination

https://github.com/angular/material2/tree/master/src/material-examples/table-http

It should show up on the docs soon

**Comment by brianmituka** [comment]
the issue is now fixed
