### ISSUE TITLE
md-input: Keyboard selection for inputs with labels is in the wrong order

### ISSUE THREAD

**Issue by iveysaur** [angular/material2#602]
Using keyboard selection for inputs selects the input before the label. It seems like it should read the label before going to input.

Steps:
1. Keyboard select to an input, the input will be selected first.
2. Use keyboard selection to move to the next item, the label will then be selected.

Found using the screenreader on OSX El Capitan in Chrome

**Comment by mmalerba** [comment]
This just seems to be how the mac screenreader works, even for native inputs
