### ISSUE TITLE
FullCalendar with day,week,month view

### ISSUE THREAD

**Issue by victorsolaya** [angular/material2#6031]
#### Bug, feature request, or proposal:

Proposal

#### What is the expected behavior?

You can create records in a calendar, see what's going to happen in the next weeks, days or months,
Know if you have scheduled something...

#### What are the steps to reproduce?

Something like https://fullcalendar.io/

#### What is the use-case or motivation for changing an existing behavior?

It could be very useful for many developers who work with visits, etc...

**Comment by jelbourn** [comment]
I would consider this out-of-scope for Angular Material.
