### ISSUE TITLE
[Question]: MdMenuTrigger - how to utilize API methods

### ISSUE THREAD

**Issue by denver-HJS** [angular/material2#6035]
Sorry to ask this here, but I don't know where else to ask it.

It's not clear to me from the docs on how I can use the API methods listed for components/directives. In this case I'm wanting to open and close a menu programmatically using the "openMenu" and "closeMenu" methods respectively.

![image](https://user-images.githubusercontent.com/1916018/28595028-fe065398-7146-11e7-96ad-e92236a6f6e0.png)
![image](https://user-images.githubusercontent.com/1916018/28595059-1a43a538-7147-11e7-8818-8cd39df0bb02.png)

I've tried importing and creating an instance within my component (not sure how to satisfy the constructor arguments) as well as passing the trigger element to a class function (provides instance of md-button and not md-menu-trigger).

```
import { MdMenuTrigger } from '@angular/material';

// class definition ...
constructor() {
    this.shipItMenuTrigger = new MdMenuTrigger();
  }

openMenu(menu:MdMenuTrigger) {
    //console.log(menu);
    //console.log(menu.openMenu);
    console.log(this.shipItMenuTrigger.openMenu);
  }


<button #shipItMenuTrigger
               md-button
               [mdMenuTriggerFor]="shipItMenu"
               (mouseenter)="openMenu(shipItMenuTrigger)">Ship It
</button>
```

**Comment by willshowell** [comment]
Take a look at [`@ViewChild`](https://angular.io/api/core/ViewChildDecorator). Note the opts/read parameters for when your queries get more complicated.

https://plnkr.co/edit/O2FJgunnKfJi4MfFb0E6?p=preview

**Comment by denver-HJS** [comment]
Thanks for such a clear and straightforward example. That helps me understand it a lot better.
