### ISSUE TITLE
Proposal: enforce view encapsulation across components

### ISSUE THREAD

**Issue by willshowell** [angular/material2#6037]
#### Bug, feature request, or proposal:
Proposal

#### Expected
I'd expect all library components to have a consistent approach to encapsulation.

#### Currently
A couple components still do ([md-spinner](https://github.com/angular/material2/blob/master/src/lib/progress-spinner/progress-spinner.ts), [md-tab-group](https://github.com/angular/material2/blob/master/src/lib/tabs/tab-group.ts)), for unclear reasons.

#### Proposal
Either use a custom lint rule, similar to the OnPush one, or have the default set to None via [`CompilerOptions`](https://angular.io/api/core/CompilerOptions)

**Comment by jelbourn** [comment]
Yep, it should be turned off everywhere.

**Comment by sbabeal** [comment]
Just wondering, why turn off view encapsulation?  Is this to facilitate modification of styles from the outside?
