### ISSUE TITLE
Plunker template is broken

### ISSUE THREAD

**Issue by kara** [angular/material2#6038]
Plunker template is broken, likely due to recent changes in our bundling. 

<img width="1416" alt="screen shot 2017-07-25 at 6 10 44 pm" src="https://user-images.githubusercontent.com/3871688/28600124-daf0440e-7164-11e7-802f-e4e4edee2838.png">

@DevVersion Can you take a look when you get a chance?

**Comment by DevVersion** [comment]
Fixed. @kara Can you confirm it works for you as well? (potential browser cache differences)

**Comment by kara** [comment]
Seems fixed to me 👍
