### ISSUE TITLE
md-input: keyboard selection for inputs with labels/hints with icons has unexpected behavior

### ISSUE THREAD

**Issue by iveysaur** [angular/material2#604]
Using keyboard selection on an input that has icons in its hints/labels causes the keyboard to select parts split by the icon.

Example: 

"First half **icon** second half."

Selects:
- "First half"
- icon
- "second half."

The icon splits the hint/label into separate items where it should all be one item selected.

Steps:
1. Keyboard select to the input label or hint with icons -- it will select the first part of the hint/label split by the icon
2. Move to the next item -- it will select the icon
3. Move to the next item -- it will select the second half of the hint/label split by the icon

Found using the screenreader on OSX El Capitan in Chrome

**Comment by mmalerba** [comment]
This seems to be fixed now, for an input with placeholder: "I [favorite icon] bold placeholder" voiceover reads "I favorite bold placeholder"
