### ISSUE TITLE
Inconsistent underlining ripples

### ISSUE THREAD

**Issue by Pikachews** [angular/material2#6041]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Ripples should behave consistently between components.

#### What is the current behavior?
Ripples for different components are positioned/behave differently.
Select (Notice the ripple is above the line)
![image](https://user-images.githubusercontent.com/5668416/28603428-cb5035b8-7178-11e7-940a-7b067822bf4a.png)
Input (This time, below the line)
![image](https://user-images.githubusercontent.com/5668416/28603436-e1ac1ab6-7178-11e7-8ee0-7b1821931f1c.png)

Another component with a underlining ripple is the tabs, where the underline goes above the baseline, like the select's. I haven't checked other components.

#### What is the use-case or motivation for changing an existing behavior?
Style inconsistency is weird. ☹️ 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material@master

**Comment by donroyco** [comment]
See #2124
