### ISSUE TITLE
bug: errors

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#6042]
#### Bug, feature request, or proposal:
bug 

#### What is the expected behavior?
run correct

#### What is the current behavior?
Can't bind to 'mdHeaderRowDef' since it isn't a known property of 'md-header-row'.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material 2.0.0-beta.8-42c50b6

#### Is there anything else we should know?
the version 7/22  is work well

**Comment by stevenmi** [comment]
and the datasource also can't find in angular/cdk. not export or move to other path

**Comment by rodaz** [comment]
Check this https://stackoverflow.com/questions/44997756/md-table-in-angular-material-2

**Comment by stevenmi** [comment]
@rodaz  the latest version update today has replace cdk with md

**Comment by calvinmuller** [comment]
update the docs?

**Comment by willshowell** [comment]
@stevenmi sometimes the snapshot builds lag behind the latest master commits (especially if there are CI errors). You can see you're using the build based on 42c50b6 which is one commit shy of a85703b which makes the change you're referencing.

![screen shot 2017-07-26 at 10 40 34 am](https://user-images.githubusercontent.com/6475576/28627132-f1bddb8a-71ee-11e7-8d44-b5a9e038572b.png)


@calvinmuller the docs represent the latest beta release, not the snapshot master builds. They will be updated in coordination with the next release

**Comment by stevenmi** [comment]
@willshowell  i update the today the version is 2.0.0-beta.8-42c50b6 ,still has the same error，that's why ?

**Comment by willshowell** [comment]
@stevenmi it's the same answer as before. You're still using the same version (2.0.0-beta.8-42c50b6). The builds keep failing on lint issues, so material2-builds isn't releasing new snapshots.

**Comment by willshowell** [comment]
@stevenmi try upgrading again now that the lint errors are fixed and a new build is available
