### ISSUE TITLE
material works as it were simple div

### ISSUE THREAD

**Issue by pukuotas** [angular/material2#6043]
hy
#### What is the expected behavior?
I want insert material into website dynamically

#### What is the current behavior?
Material renders as simple div and text gets formated only

#### What are the steps to reproduce?

I have AboutComponent which gets html by API and AboutComponentLoader which takes the former as as variable and inserts into ng-container.

here is my code (didn`t include some code fragments because of time and space saving):

**app.module** ngmodule decor. :
`  declarations: [AppComponent,SanitizeDirective,AboutComponent,AboutComponentLoader],
    entryComponents:[AboutComponent,AboutComponentLoader],
    bootstrap: [AppComponent]
    `

**about.component.loader (ts file)**:

`import { Component } from '@angular/core';

import {NgComponentOutlet } from '@angular/common';

import {AboutComponent } from './about.component';

`@Component({`

    template:'<ng-container *ngComponentOutlet="typess"></ng-container>',
    selector: 'about',
 
})

export class AboutComponentLoader  {

    typess = AboutComponent;
}`

**about.component (ts file)**:

`

`@Component({`

    templateUrl: '../../app/templates/about2.component.html',

    selector: 'about-xxx',
    providers: [HttpService],
   
    
})

export class AboutComponent implements OnInit {

    public pageHTML: any;

    constructor(private http: HttpService, private activatedRoute: ActivatedRoute) {

    }

    ngOnInit(): void {

        this.activatedRoute.params.subscribe((parms: any) => {
            if (parms.lang) {

             
               this.http._get(GLOBAL.url + "/api/GetAbout").subscribe((data) => { this.pageHTML = data[0]['pageHTML']; 

          
                           
            }
        
        });

    }

}`

**about2.component.html**

`<div [sanitizeHtml]="pageHTML"></div>`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/material": "^2.0.0-beta.2",
 "@angular/core": "^4.1.3",
#### Is there anything else we should know?
I use API to get material

**Comment by pukuotas** [comment]
why downvote?

**Comment by grizzm0** [comment]
Angular does not process HTML being added dynamically. You can not render HTML server-side and expect Angular to process it once it hits the client.

The material components is supposed to be used in your Angular application working of JSON or similar from the backend.
