### ISSUE TITLE
[MdGridList] - Grid doesn't display at all on server with RatioTileStyler display strategy

### ISSUE THREAD

**Issue by jimjim2a** [angular/material2#6048]
#### Bug, feature request, or proposal:
On the server the MdGridList component doesn't display when using the RatioTileStyler strategy. It doesn't display because the applied styles are not valid properties name.

Specifically on the `setRowStyles` and `getComputedHeight` methods.

These methods define some styles to be applied on the tile, but the properties to be written are camelCase. On the browser this works well, but the server renderer writes theses properties inside the style attribute as they are.

`
Ex : style="marginTop: calc(((33.333333333333336% - ( 0px * 0.6666666666666666 )) + 0px) * 0);paddingTop:calc(((33.333333333333336% - ( 0px * 0.6666666666666666 )) * 1) + (0 * 0px));"`

`marginTop` and `paddingTop` are not valid property names for the browser, therefore it ignore them.

#### What is the expected behavior?
The css properties should be written kebab-case to be correctly handled by the browser.

**Comment by crisbeto** [comment]
Thanks for the heads-up @jimjim2a, I could confirm that the margin and padding weren't being assigned anymore. What's odd is that the old renderer used assign the properties, even though they were invalid. The one just drops the invalid ones altogether.

**Comment by jimjim2a** [comment]
Awesome ! Thanks @crisbeto
