### ISSUE TITLE
[mdDatepickerToggle] still opening datepicker when input is disabled

### ISSUE THREAD

**Issue by merlosy** [angular/material2#6053]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Im using: 
- reactive forms
- form builder:
```ts
this.myForm = this._fb.group({
      ...
      estimatedApplicationDate: [
          { value: this.data.applicationDate, disabled: true }, 
          [Validators.required]
      ]
    });
```

and template:
```html
<input mdInput formControlName="estimatedApplicationDate"
     [mdDatepicker]="estimatedApplicationDateDatepicker" 
     placeholder="Date d’application estimée" required
     (click)="estimatedApplicationDateDatepicker.open()">
<button mdSuffix [mdDatepickerToggle]="estimatedApplicationDateDatepicker"></button>
<md-datepicker #estimatedApplicationDateDatepicker></md-datepicker>
```
=> The input is disabled as specified, but I can still open the datepicker panel

#### What is the current behavior?
The datepicker icon shouldn't be clickable

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U (template not working, lots of 404)

#### What is the use-case or motivation for changing an existing behavior?
Consistency i guess

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- angular ^4.1.0
- @angular/material 2.0.0-beta.8
- OS Windows 10
- browser: Chrome 57
- typescript ~2.3.3

#### Is there anything else we should know?

Work-around:
```html
<button mdSuffix 
     [mdDatepickerToggle]="myForm.get('estimatedApplicationDate').disabled? null : estimatedApplicationDateDatepicker">
</button>
```

I hope this is clear enough..
Thanks!

**Comment by julianobrasil** [comment]
Have you try disabling the `md-datepicker` itself?

```html
<md-datepicker #estimatedApplicationDateDatepicker 
  [disabled]="myForm.get('estimatedApplicationDate').disabled"  ></md-datepicker>
```

**Comment by willshowell** [comment]
You can also just disable the button

```html
<button mdSuffix [disabled]="myForm.get('estimatedApplicationDate').disabled"
     [mdDatepickerToggle]="estimatedApplicationDateDatepicker">
</button>
```

I feel like the button shouldn't be coupled to the form control, but could maybe understand the datepicker doing so.

**Comment by julianobrasil** [comment]
There might be a problem with the docs or the component. ASAP I'll try it in a plunk.

**Comment by julianobrasil** [comment]
Looking quickly at [the code](https://github.com/angular/material2/blob/3cb394512a4a5d322dc240bfa5de664466d19bab/src/lib/datepicker/datepicker.ts#L145-L152), I can tell there _is_ a **`disabled`** property. I haven't figured out yet the reason why it apparently doesn't work as I expected,

**Comment by willshowell** [comment]
@julianobrasil it's new (https://github.com/angular/material2/pull/5305). Here's that same file at beta.8 
https://github.com/angular/material2/blob/2.0.0-beta.8/src/lib/datepicker/datepicker.ts

**Comment by julianobrasil** [comment]
Oh, now it makes sense. 😸

**Comment by mmalerba** [comment]
This has been fixed, just hasn't made it into a release yet
