### ISSUE TITLE
Copy/Paste from MdTable

### ISSUE THREAD

**Issue by joshhobson** [angular/material2#6054]
It's not currently possible to copy from an MdTable and paste into an Excel (or similar) spreadsheet. This is standard for html tables. Is this something that will be added?

This can be seen simply by copying from the examples in the docs: https://material.angular.io/components/table/overview

**Comment by andrewseguin** [comment]
The only possible solution would be to use the `<table>` element rather than a collection of divs, which is not compatible with our current and future feature set.
