### ISSUE TITLE
Cannot read property 'style' of null in GlobalPositionStrategy.apply

### ISSUE THREAD

**Issue by philipooo** [angular/material2#6056]
#### Bug:
The error: **Cannot read property 'style' of null** occures when calling GlobalPositionStrategy.apply with an HTMLElement which parentNode is set to null.

#### What is the expected behavior?
No error is thrown

#### What is the current behavior?
TypeError: Cannot read property 'style' of null at .../@angular/material.es5.js.GlobalPositionStrategy.apply

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular-material2-beta.8, Chrome 59, TypeScript 2.3.4

#### Is there anything else we should know?
There is a null-Check at
https://github.com/angular/material2/blob/master/src/lib/core/overlay/position/global-position-strategy.ts#L140
so element.parentNode is expected to be null. But at 
https://github.com/angular/material2/blob/master/src/lib/core/overlay/position/global-position-strategy.ts#L148
there is no null-Check.

**Comment by crisbeto** [comment]
How did you run into the error? The assumption in the `GlobalPositionStrategy` is that the element would have a `parentNode` by that point.

**Comment by philipooo** [comment]
@crisbeto It turned out that a colleague of mine who had the problem was calling `dialogRef.updateSize` while the dialog was closed. This caused the error mentioned before.

But maybe you should check why in line 140 is a null-check against `parentNode` when it is accessed in line 148 anyway.
