### ISSUE TITLE
Material not working in new CLI application

### ISSUE THREAD

**Issue by bautistaaa** [angular/material2#6061]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should launch skeleton app from cli

#### What is the current behavior?
erroring on ng serve command

![image](https://user-images.githubusercontent.com/3660667/28630796-3f504662-71f9-11e7-9070-ce470042f901.png)

#### What are the steps to reproduce?
ng new my-app
npm install --save @angular/material

followed every step in this page [https://github.com/angular/angular-cli/wiki/stories-include-angular-material](url)

WORKS if i remove MaterialModule from imports in app.module.ts
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { MaterialModule } from '@angular/material';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    // MaterialModule <-- works when removed
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.3.1
2.0.0-beta.8
windows 7
TS 2.2.1

**Comment by bautistaaa** [comment]
yeah that site told me to follow the instructions on this page if its a new application in CLI 

https://github.com/angular/angular-cli/wiki/stories-include-angular-material

should I let cli team know their docs are wrong?

**Comment by willshowell** [comment]
@bautistaaa If you do so, maybe suggest replacing 

```
Install the @angular/material library and add the dependency...
...
```
through ==>
```
...
"@import '~https://fonts.googleapis.com/icon?family=Material+Icons';"
```

with a link to the getting started guide, since there are multiple inconsistencies with that guide and material works great with the cli if you follow the material guide.

**Comment by bautistaaa** [comment]
thanks everyone just wanted to make sure im doing things properly. cheers

**Comment by mkarthi1947** [comment]
Try this way without npm. Its working fine for me.
1. For the alternative install dependency. Install yarn in your machine. pls check this url https://yarnpkg.com/en/
2. **Install dependency** : c:\Users\User\Desktop\material2>**_yarn install_**
3. **Run your app**: c:\Users\User\Desktop\material2>**_npm run demo-app_**
4. **Run url in your browser** : **_http://localhost:4200/_**
5. Done
