### ISSUE TITLE
Theme documentation doesn't work

### ISSUE THREAD

**Issue by megamindbrian** [angular/material2#6063]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Documentation does not specify where to include your custom color theme.scss file.

#### What is the current behavior?
Error ```Could not find Angular Material core theme```

#### What are the steps to reproduce?
Follow these instructions:
https://material.angular.io/guide/theming

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
I want to modify fonts and colors using scss before any components or modules are loaded throwing the above error.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Every version including the latest.

#### Is there anything else we should know?
Your documentation is wrong or got left behind the most up to date procedures.

**Comment by willshowell** [comment]
Assuming this is somewhat in response to this https://github.com/angular/material2/issues/2800#issuecomment-318101838...

You must `@include mat-core()` exactly once, and if you follow the guide, you will have done that.

**Comment by megamindbrian** [comment]
@willshowell What file do I include ```@include mat-cor()``` in?

**Comment by willshowell** [comment]
This is the setup we've opted for:

```scss
// in styles/_custom_theme.scss
@import '~@angular/material/theming';

$primary: ...
$accent: ...
$warn: ...

$theme: mat-light-theme(...)
```

```scss
// in styles/required.scss
@import 'custom-theme';

@include mat-core();
@include angular-material-theme($theme);

// other global styles
```

```
// in .angular-cli.json

"apps": [{
  ...

  "styles": [
    "style/required.scss"
  ],
  "stylePreprocessorOptions": {
    "includePaths": [ "style" ]
  },

  ...
}]
```

**Comment by megamindbrian** [comment]
Beautiful!  So angular-cli does compile scss files.  Where is the documentation for that?

**Comment by maxisam** [comment]
Weird, I have above settings but it still showing the warning with AngularCli 1.3.2. But all my material ui work correctly with my customized theme. 

I wonder if anyone has the same issue.

**Comment by megamindbrian** [comment]
I missed the line to put the colors-theme.scss in the angular-cli.json.  I
tried to get them to update the documentation but no one cares.

**Comment by maxisam** [comment]
@megamindbrian what is colors-theme.scss? I don't see anything about it.

**Comment by megamindbrian** [comment]
I just meant whatever file of yours contains the .main-theme code. Use
angular-cli.json to import that instead of the inline method.

**Comment by maxisam** [comment]
@megamindbrian I think inline `@import` works fine.
