### ISSUE TITLE
Material chip list should support being not focusable

### ISSUE THREAD

**Issue by mertdeg** [angular/material2#6069]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I should be able to pass in an @Input() to mat-chip-list so that it doesn't have tabIndex = 0 by default. Sometimes we want to display chips within a tooltip. And we don't want user to be able to focus on individual chips.

#### What is the current behavior?
mat-chip-list is always focusable by default

#### What are the steps to reproduce?
Create mat-chip-list with non-zero chips inside

#### What is the use-case or motivation for changing an existing behavior?
To increase use cases for material chip list component

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by mertdeg** [comment]
@jelbourn as FYI

**Comment by jelbourn** [comment]
@tinayuangao the chip list should respect a user-provided `tabIndex` if there is one

**Comment by bsteffl** [comment]
This doesn't seem to make the chip appear to be not interactive when you click on the chip, it still has a ripple. Is there a way to have a readonly chip but is not disabled?
