### ISSUE TITLE
Strange behaviour on panels [expanded]

### ISSUE THREAD

**Issue by mackelito** [angular/material2#6097]
Maybe I´m just totally using this the wrong way but here we go :)

#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
[expanded] function should run once

#### What is the current behavior?
it runs twice for each panel

#### What are the steps to reproduce?
open the console and click on the panels

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
http://plnkr.co/edit/ckk4BCkNYNgNzJodW53t?p=preview

#### Is there anything else we should know?

**Comment by andrewseguin** [comment]
This is due to Angular running change detection twice on the template, unrelated to Material. http://plnkr.co/edit/inbSg6S7N5r6UPbVH0Ev?p=preview

**Comment by mackelito** [comment]
@andrewseguin just to be clear... is this a angular bug? Or should I have another approach?

**Comment by willshowell** [comment]
No bug, its just that angular's change detection must be very conservative in order to detect any changes that may have occurred in `shouldBeExpanded()`.

See here that setting your AppComponent to OnPush will only run change detection once.

http://plnkr.co/edit/ah3Ji1C93nz5EwRcVEmi?p=preview

**Comment by mackelito** [comment]
aah.. I now see that it does not behave as I expected.. it expanded=true then it triggers the opened event.. will need to find another way then.. thx!

**Comment by mackelito** [comment]
Any suggestions btw? :D

**Comment by willshowell** [comment]
This seems to behave as expected with minimal reads of local storage:

http://plnkr.co/edit/Q3daXShLOilqhUA4J7eo?p=preview

I think the issue is that you were returning a string from `shouldBeExpanded()` instead of a boolean. Note that the string `'false'` is truthy, whereas the boolean `false` is not.

**Comment by mackelito** [comment]
Never mind.. we´ll probably couple it to the router state instead! :) 👍

**Comment by mackelito** [comment]
@willshowell aaaaah.. of course! thx! :)
