### ISSUE TITLE
refactor: find a way to share common code between checkable components

### ISSUE THREAD

**Issue by robertmesserle** [angular/material2#610]
As is, there is a lot of copy/pasted code shared between radio buttons, checkboxes, and toggle buttons.  We need to look into a way to rely on shared code rather than duplicate code.

**Comment by DevVersion** [comment]
I think that relates to #598 as well.

**Comment by shlomiassaf** [comment]
If done, also consider #347 in the process.

**Comment by jelbourn** [comment]
Exploring new mixins in TypeScript 2.2.
