### ISSUE TITLE
[BUG] Changes made to formControl associated with md-select are not visible

### ISSUE THREAD

**Issue by mwanago** [angular/material2#6106]
#### Bug, feature request, or proposal:
Changes made to formControl associated with md-select are not visible

#### What is the expected behavior?
Changes made to formControl associated with md-select should be visible on select

#### What is the current behavior?
Event if formControl has the correct value, md-select shows just placeholder.
Setting value using md-select dropdown works just fine

```
<div class="option-select-container" [formGroup]="parentFormGroup">
  <md-select class="option-select"
             placeholder="{{formControlName | capitalize}}"
             (formControl)="formControl"
             formControlName="{{formControlName}}"
             [multiple]="multiple">
    <div class="dropdown-container">
      <div class="select-options" >
        <md-option class="empty-option" [disabled]="multiple">
          <div *ngIf="multiple" class="empty-option-hack">
            <div class="empty-option-hack-block"></div>
          </div>
          <span [ngClass]="{'option-text-hack' : multiple}">{{formControlName | capitalize}}</span>
        </md-option>
        <md-option *ngFor="let option of options" [value]="option">
          <div class="option">
            <label for="file-input" class="option-image-container" (click)="chooseOptionToAppendImage($event, option)" *ngIf="withImage">
              <div class="option-image" [ngStyle]="option.image && option.image && {'background-image': 'url(' + option.image.URL + ')', 'background-size':'cover'} || {}"></div>
            </label>
            <span class="option-text">
              <p>{{option.name}}</p>
            </span>
          </div>
        </md-option>
      </div>
      <form (submit)="addOption($event)" class="select-new-option">
        <md-input-container class="option-creation-input">
          <input type="text" [ngModelOptions]="{standalone: true}" [(ngModel)]="newOption" mdInput placeholder="New option">
        </md-input-container>
        <button md-raised-button color="primary" type="submit">add</button>
      </form>
    </div>
  </md-select>
</div>

<input id="file-input" accept="image/*" (change)="addImage($event)" type="file" [hidden]="true" *ngIf="withImage">
```

```
ngOnInit() {
    this.route.params.subscribe((params) => {
      if (params.id) {
        this.objectId = params.id;
        this.objectService.fetch(params.id).subscribe((data: any) => {
          this.objectCreationForm.setValue({
            language: data.language || '',
            country: data.country || '',
            regions: data.regions || '',
            text: data.text || ''
          });
        });
      }
    });
}
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on few newest versions of Angular and Material

**Comment by julianobrasil** [comment]
Try to provide a plunker with the basics to track down the problem. There's a lot of extra stuff in the code you've shown.

**Comment by crisbeto** [comment]
Since your service might return after Angular has run its change detection, you have to run a `changeDetectorRef.detectChanges()` after you've set the value.

**Comment by mwanago** [comment]
@crisbeto Sadly, this does not help. By the way, the md-input that is on the same page works just allright. I'm going to go and try to provide a plunker for this. By the way, md-selects are nested in components, and formGroup is outside of them.

**Comment by mwanago** [comment]
I found a problem.
It was due to some inconsistency between available options for md-select (fetched from server) and value that is being set. If i set value that is not strictly from the options array provided for the md-select (but the corresponding option with the same id should be there), the value won't be shown.
This piece of code is kind of strange, but it works.
It gets the value from the server and looks for the option with the same id in the options array

`
let subscription = this.formControl.valueChanges.subscribe((newValue) => {
      setTimeout(() => {
        if (newValue && this.options && this.options.length) {
          if(!newValue.length) {
            for (const option of this.options) {
              if (newValue.id === option.id) {
                this.formControl.setValue(option);
              }
            }
          }else{
            let array = [];
            for(const value of newValue){
              for (const option of this.options) {
                if (value.id === option.id) {
                  array.push(option);
                }
              }
            }
            this.formControl.setValue(array);
          }
        }
        subscription.unsubscribe(); // without that the function fires forever
      },0);
    });
`

**Comment by julianobrasil** [comment]
So this was a matter of comparing references instead of values?

**Comment by mmalerba** [comment]
Closing since it looks like this was resolved
