### ISSUE TITLE
md-autocomplete displaying '[object Object]'

### ISSUE THREAD

**Issue by alex321** [angular/material2#6108]
#### Bug:
`Md-autocomplete` displays `[object Object]` even though it is passed a string. It displays that only if you select the same object from the dropdown list.

#### What is the expected behavior?
We should not see `[object Object]` after selecting the same object from the options.

#### What are the steps to reproduce?

Here is a Plunker that reproduces the issue: 
https://plnkr.co/edit/acz2QZHuVo39rdOQ2C3E?p=preview

Select a value from the list. Then click on the input (without typing) and select the same value again (there should be only 1 value in the list - the current one).

![gif](https://d26dzxoao6i3hh.cloudfront.net/items/2D040a3G3E0G0F421a2i/Screen%20Recording%202017-07-28%20at%2002.39%20pm.gif?v=19591e74)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4.3.2
Material 2.0.0-beta.8

**Comment by grizzm0** [comment]
You're setting the value to state, not state.name.

**Comment by willshowell** [comment]
And if you still want to bind the value to `state` instead of `state.name`, autocomplete has a [`displayWith`](https://material.angular.io/components/autocomplete/overview) input to control how the selected option gets displayed.


Example: https://plnkr.co/edit/W9vdWaGcoG90LKM8hHgI?p=preview

**Comment by alex321** [comment]
@willshowell I know, thank you. I can read. This is still a bug though.

**Comment by willshowell** [comment]
Hah nice edit 😒 just trying to help

--
Note that also if you just type "Me" and select the remaining option, it also happens. Here's my best guess:

1. Any time you select an option from the list, it writes the full object to the input.nativeElement (see [these lines](https://github.com/angular/material2/blob/master/src/lib/autocomplete/autocomplete-trigger.ts#L410-L431)), which would display as [object Object].
2. Whenever the Angular detects a change between the previous NgModel value and the new one, it calls `writeValue()` with the result of your `state` getter. See [here](https://github.com/angular/material2/blob/master/src/lib/autocomplete/autocomplete-trigger.ts#L266-L274). This overwrites [object Object] with the new NgModel value, a string.
3. When there is *not* a change between values (i.e. you type "Me" and then select the "Me" option), `writeValue()` never gets called, so [object Object] is never overwritten.

In general, I would try to avoid overloading NgModel values, and you can still use `displayWith` to ensure that the correct value is *always* written to the input element.

cc @kara

**Comment by alex321** [comment]
@willshowell Thanks, I know. It's just that the autocomplete API is slightly confusing and I was experiencing various issue with the `displayWith`, I guess based on my used of `getter`. 
At least from my point of view, the usage I have makes sense with `ngModel` vs `formControl` which is what the example has.

**Comment by josephperrott** [comment]
Closing as it appears the specific instance of the issue seems to be dealt with.
