### ISSUE TITLE
install error even with latest npm

### ISSUE THREAD

**Issue by balasivagnanam** [angular/material2#611]
#### Bug
getting the below error for npm install of material core.

#### Which versions of Angular, Material, OS, browsers are affected?
node version  4.4.5 
npm version 3.9.3

#### What is the current behavior?
![image](https://cloud.githubusercontent.com/assets/4233785/15739849/8c8c0826-28e4-11e6-80d3-3c2393dd4159.png)

**Comment by msegers** [comment]
@angular2-material

**Comment by balasivagnanam** [comment]
aahh... my bad.. very sorry...
