### ISSUE TITLE
MdDialogClose for anchor tag

### ISSUE THREAD

**Issue by EvAlex** [angular/material2#6113]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Change MdDialogClose directive selector to `'button[md-dialog-close],a[md-dialog-close]'`.

#### What is the current behavior?
Currently MdDialogClose directive has selector `'button[md-dialog-close]'`. This makes it impossible to use anchor tag as dialog action that closes it. 

#### What are the steps to reproduce?
It's in the docs and in the code.

#### What is the use-case or motivation for changing an existing behavior?
I have an "export to file" dialog. User chooses kind of export, inputs some parameters and than clicks export button. Important thing is that I create Blob from local object, get objectUrl for that Blob and use it as href value of anchor tag. When user clicks anchor tag - file is downloaded. Problem is that dialog stays open. And I cannot close it because anchor tag ignores MdDialogClose directive. 

I can imagine other use cases, but that was mine.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4
Material 2.0.0-beta.8
Windows 10
TypeScript 2.4.2
Chrome 59

#### Is there anything else we should know?
Nope

**Comment by jelbourn** [comment]
Most of the time using an anchor as an _action_ is not the right thing to do for a11y, so we scope `md-dialog-close` to buttons to encourage the right approach. 

You can manually close the dialog without `md-dialog-close` by calling the `close` method on `MdDialogRef` (which you can inject into the dialog).

**Comment by EvAlex** [comment]
I see, thank you. Injecting MdDialogRef is the thing I overlooked in docs
