### ISSUE TITLE
[wiki] table design doc missing from the design doc directory

### ISSUE THREAD

**Issue by willshowell** [angular/material2#6114]
The [cdk-table](https://docs.google.com/document/d/1ZyKhwrgqfTBAn7saTq2jPlep2_CwSw5DeoZ8UbaXrC0/edit) design document is missing from the [design doc directory](https://github.com/angular/material2/wiki/Design-doc-directory).

Motivation: https://github.com/angular/material2/commit/8c1e80388b608c3717586dcc8414d6554cb1f3b9#commitcomment-23349903

**Comment by andrewseguin** [comment]
Thanks, added `cdk-table` design doc
