### ISSUE TITLE
Create accessibility demo page for menu

### ISSUE THREAD

**Issue by tinayuangao** [angular/material2#6120]

**Comment by amcdnl** [comment]
@tinayuangao - I added demos for the following:
- Click on the icon will trigger menu
- Display menu options with icon

Can you provide more explanation on what you had in mind for these 2 demos:
- Nested menu
- Navigation menu

**Comment by tinayuangao** [comment]
@amcdnl 
Nested menus are menus with hierarchy, for example
```
  Tasks
    -- My tasks
    -- Team tasks
    -- Draft
```

Navigation menu is the menu when you click on it, the page will navigate to another page.
