### ISSUE TITLE
bug(table):dynamic column definitions

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#6133]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
has no error

#### What is the current behavior?
Can't bind to 'cdkColumnDef' since it isn't a known property of 'ng-container'.

#### What are the steps to reproduce?
![1](https://user-images.githubusercontent.com/14286935/28742383-87cb88b0-7461-11e7-820e-759f4318e4d6.png)
![2](https://user-images.githubusercontent.com/14286935/28742384-88a2e7c4-7461-11e7-9acb-648aa62263e4.png)

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2.0.0-beta.8-cf071c7

**Comment by andrewseguin** [comment]
Looks like you are missing `CdkTableModule` from your imports. Be sure to grab that from `@angular/cdk/table`.

Here's an example of dynamic columns: https://plnkr.co/edit/tsIL0mOW0I19gn14z8Em?p=preview
