### ISSUE TITLE
docs(tabs): add more and different examples

### ISSUE THREAD

**Issue by donroyco** [angular/material2#6135]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
To show some more examples of different implementations of the `md-tabs` components [in the documentation](https://material.angular.io/components/tabs/overview).

#### What is the current behavior?
There's only showing _More examples coming soon!_ [on the examples page](https://material.angular.io/components/tabs/examples).

#### What is the use-case or motivation for changing an existing behavior?
People want good examples to show what a possible result can be. Right now, there's only one example of a basic tab, but adding examples for `dynamicHeight`, tabs with icons and tabs with navigation (overlapping). 

Also, issues like these (#6109 and #6104) will show up earlier or won't show up at all.

#### Is there anything else we should know?
I *can* make a PR for this, but I'm not sure if that's desirable. Maybe let's first discuss which examples to be shown.

**Comment by amcdnl** [comment]
Done by https://github.com/angular/material2/pull/6295
