### ISSUE TITLE
Add support of ng-template for SnackBar

### ISSUE THREAD

**Issue by dmitrysteblyuk** [angular/material2#6136]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
MdSnackBar open method accepts TemplateRef as a content. Suggested api:
MdSnackBar.openFromTemplate(template: TemplateRef, context?: any, config?: MdSnackBarConfig)

#### What is the current behavior?
Snack bar accepts a component or a string as a content.

#### What is the use-case or motivation for changing an existing behavior?
If I want to pass something really simple to snack bar but not a string (e.g. string with a pipe, a link, ```observable | async``` etc), currently I'll have to create a component for this which in many cases would be an overkill.

**Comment by nhducseuit** [comment]
Hello,
Could you update the changelog to specify which version that openFromTemplate method is added?
