### ISSUE TITLE
How to use material scss variables in custom code

### ISSUE THREAD

**Issue by Maximaximum** [angular/material2#6139]
#### Bug, feature request, or proposal:
Not sure if it's a feature request or a bug.

#### What is the expected behavior?
I'd like to create a custom checkbox component. It would extend the `MdCheckbox` class, but override the template and the styles.

In the `custom-checkbox.component.scss` file I need to use some of the angular material scss variables in order to maintain consistent styling. For example, I need `$mat-toggle-padding`, `$mat-checkbox-border-width` and some other variables.

However, when I browse through the `@angular/material` npm package folder, I don't see any scss files except the root `_theming.scss` file, which, though, does not contain the variables I need.

As far as I see, these variables are not included in the output npm package, but are present in the source files. 

How can I import and use these variables in my custom scss file?

#### What is the use-case or motivation for changing an existing behavior?
I need to create a custom checkbox component that would have the same logic as the `MdCheckbox` component, but would have slightly different appearance, though would share some scss variables with the original MdCheckbox component.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.2.6, angular-material 2.0.0-beta.8

**Comment by grizzm0** [comment]
I had an issue open before (#3085) about moving the variables into their own files so they could easily be re-used. I however closed it when it was decided not to ship any SCSS at all with the package.

I still agree with you tho that the variables should be available if you want to write custom components that depend on those variables.

**Comment by Maximaximum** [comment]
Seems to be a duplicate of https://github.com/angular/material2/issues/4003

**Comment by jelbourn** [comment]
See https://github.com/angular/material2/issues/4003#issuecomment-293434472
