### ISSUE TITLE
@angular2-material/list/list"' has no exported member 'MdLine'

### ISSUE THREAD

**Issue by wardberckmans** [angular/material2#614]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
no error show

#### What is the current behavior?
error shown: @angular2-material/list/list"' has no exported member 'MdLine'

#### What are the steps to reproduce?
I updated to @angular2-material/XXX@2.0.0-alpha.5-2 and when starting the application (npm start) the error @angular2-material/list/list"' has no exported member 'MdLine' is shown.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.0.0-rc1 / material alpha.5-2

**Comment by kara** [comment]
Hm, it sounds like the import may be incorrect.   It should look like this:

```ts
import {MD_LIST_DIRECTIVES} from '@angular2-material/list`;
```

If you're already doing that, can you provide a plunker with the error?

**Comment by wardberckmans** [comment]
Hi Kara,

This solved the issue. So this can be closed.

Kr,
Ward
