### ISSUE TITLE
Different bottom linewidth for input and select when error

### ISSUE THREAD

**Issue by princemaple** [angular/material2#6140]
#### Bug, feature request, or proposal:
bug

![image](https://user-images.githubusercontent.com/1329716/28744139-0bf62d70-749e-11e7-9050-ee6996c8f86f.png)

#### What is the expected behavior?
be the same? I couldn't find `select` in material design spec

#### What is the current behavior?
different

#### What are the steps to reproduce?
http://plnkr.co/edit/2QFkVaZdoI6fvNI8nTzk?p=preview

#### What is the use-case or motivation for changing an existing behavior?
to be consistent

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
4.3.2, 2-beta.8, others irrelevant

**Comment by donroyco** [comment]
Good catch. See #6041 and (partly) #2124

**Comment by princemaple** [comment]
Hmm, seems a little different but definitely related. should I close this one?

**Comment by mmalerba** [comment]
This will be addressed as part of the fix for #2124, so closing as a duplicate of that
