### ISSUE TITLE
Tabs Line Break Causes Incorrect Visual Selection Indicator

### ISSUE THREAD

**Issue by amcdnl** [angular/material2#6154]
#### Bug, feature request, or proposal:
On small screens, when tabs breaks down if the selected tab is on the first row the selection appears as if it were for the item on the second row.

#### What is the expected behavior?
The selection would appear under the correct tab.

#### What is the current behavior?
In this example, 'Overview' is selected but it appears that 'Examples' is selected.
![img](https://content.screencast.com/users/amcdaniel22/folders/Snagit/media/44f212da-3577-4679-8a68-e2042b73a2a8/2017-07-25_20-52-16.png)

**Comment by julianobrasil** [comment]
Possibly similar: #4323?

**Comment by amcdnl** [comment]
@julianobrasil - Yup, looks like a dupe. Closing.
