### ISSUE TITLE
Table filtering placeholder text is not showing when changing theme

### ISSUE THREAD

**Issue by stibay** [angular/material2#6156]
Using the table with filtering example here: https://material.angular.io/components/table/overview
When changing to a different theme using the guide here https://material.angular.io/guide/theming
the placeholder text becomes invisible and the background of the table is always black.

If I select the textbox the placeholder is visible.

Tried to make a plunkr but didn't manage to import the theming colors.

Here are some screenshots from page load, then changing theme and then selecting the input
http://imgur.com/a/gS9T3

**Comment by willshowell** [comment]
The header in that example is not any special material component, it's just a plain div. You can style it yourself, or place the whole table within an md-card.

**Comment by stibay** [comment]
I noticed you can change the color on the whole page in the docs and there it looks to work fine so if someone can add theming to the plunkr example https://plnkr.co/edit/?p=preview so its possible to add this theme.scss file I can repro it.
```

@import '~@angular/material/_theming';

@include mat-core();

$primary: mat-palette($mat-indigo);
$accent: mat-palette($mat-green);

$theme: mat-light-theme($primary, $accent);

@include angular-material-theme($theme);

.dark-theme {
  $dark-primary: mat-palette($mat-red);
  $dark-accent: mat-palette($mat-blue);

  $dark-theme: mat-dark-theme($dark-primary, $dark-accent);

  @include angular-material-theme($dark-theme);
}
```

**Comment by willshowell** [comment]
As you can see, the header is transparent:

![screen shot 2017-07-31 at 10 44 24 am](https://user-images.githubusercontent.com/6475576/28783161-6b2b19f0-75dd-11e7-9c8f-46422acdb221.png)

And here is a plunker using a dark theme:

https://plnkr.co/edit/7euGEVlOjMHoJL3AG9Yl?p=preview

And here is the same plunker using this note from the Theming Guide

> Finally, if your app's content is not placed inside of a `md-sidenav-container` element, you need to add the `mat-app-background` class to your wrapper element (for example the body). This ensures that the proper theme background is applied to your page.

https://plnkr.co/edit/p6TA0JueZhQ3GrcAYgub?p=preview

**Comment by stibay** [comment]
Aha I see. `mat-app-background` was the key here. Thank you.
