### ISSUE TITLE
[Tabs] md-input with textarea and mdAutosizeMinRows not working

### ISSUE THREAD

**Issue by zhaochy1990** [angular/material2#6160]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?

```
<div fxLayout="row">
    <md-tab-group fxFlex="100%">
        <md-tab label="tab1">
            <md-input-container style="width:100%;">
                <textarea type="text" placeholder="content1" mdInput mdTextareaAutosize mdAutosizeMinRows="10"></textarea>
            </md-input-container>
        </md-tab>
        <md-tab label="tab2">
            <md-input-container style="width:100%;">
                <textarea type="text" placeholder="content2" mdInput mdTextareaAutosize mdAutosizeMinRows="10"></textarea>
            </md-input-container>
        </md-tab>
    </md-tab-group>
</div>
```

the textarea in second tab should have min rows of 10

#### What is the current behavior?

the textarea in second tab have min rows of 1
#### What are the steps to reproduce?

http://plnkr.co/edit/3nYzSLgEFkrDlXwdpCpe

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular 4.3.1
material 2.0.0-beta.8

#### Is there anything else we should know?
no

**Comment by tinayuangao** [comment]
Seems related to tabs. Only textarea in second tab has this problem

**Comment by zhaochy1990** [comment]
yes, the second textarea was not rendered as expected.

**Comment by josephperrott** [comment]
Closing as this is related to animations not running in unrendered tabs.  You can now lazy load tab content which will render as expected.
