### ISSUE TITLE
md-button-toggle's [checked] attribute doesn't handle dynamic values

### ISSUE THREAD

**Issue by srix55** [angular/material2#6162]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
<md-button-toggle [checked]="condition"> should work

#### What is the current behavior?
md-button-toggle's [checked] doesn't handle true/false returning expressions

#### What are the steps to reproduce?
Created a simple plunker to show
Plunker link: http://plnkr.co/edit/IKLHnu?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I am using the toggle-group to show dynamically got language options out of which I want to have the default one selected or checked.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3, 
Material 2.0.0-beta.8-374aaff
All OS
TypeScript: ^2.2.2
Firefox, Chrome, Opera (checked only on those)

#### Is there anything else we should know?
No

**Comment by rafaelss95** [comment]
In your plunker you should use either `value="{{n}}"` or `[value]="n"` so it will perfectly.
