### ISSUE TITLE
Typography classes not working

### ISSUE THREAD

**Issue by alexispolak** [angular/material2#6163]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

The html tag affected by the class has to change the font size, weight, etc.

#### What is the current behavior?

Doesn't change anything but the font-family.

#### What are the steps to reproduce?

Following the [Angular Material Typography guide](https://material.angular.io/guide/typography), put the 
@import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500'); on the Styles.css file. On the html file: 

```
<p class="mat-body-1"> some text </p>
<p class="mat-body-2"> some other text </p>
<p> some other other text </p>
```

The three tags have the same style.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4.2.2
TypeScript 2.3.4
@Angular/material 2.0.0-beta.6
Browsers: 
- Chromium Versión 59.0.3071.109 (Build para desarrolladores) Built on Ubuntu , running on Ubuntu 16.10 (64 bits)
- Firefox 54.0 (64-bits).

**Comment by crisbeto** [comment]
Do you have some other styles that are changing the paragraphs (e.g. a CSS reset)? The Material typography has a pretty low specificity that might be overwritten.

**Comment by alexispolak** [comment]
not really, only the imported on style.css. By the way, non of the classes are working, not only on <p> but on <h1> <h2> <h3> etc.  I got the bootstrap.css but it's not changing anything, i try to remove it and it's still the same.

This is my style.css

```
@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
@import '~material-design-icons/iconfont/material-icons.css';
@import '~bootstrap/dist/css/bootstrap.css';
@import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500');
```

**Comment by crisbeto** [comment]
That seems weird. [I can definitely get it working in Plunkr.](http://plnkr.co/edit/BdcOqsxrSo9y6GJP4VG4?p=preview) Can you try looking through the inherited styles with the Dev Tools to see whether there isn't something further down that is overriding it?

**Comment by alexispolak** [comment]
Got this HTML:

```
<p> ALGO </p>
<p class="mat-title"> ALGO </p>
<p class="mat-body-2"> ALGO </p>
```

Using the Dev Tools, i see that

 the three share the same style. This one:

```
element.style {
}
user agent stylesheet
p {
    display: block;
    -webkit-margin-before: 1em;
    -webkit-margin-after: 1em;
    -webkit-margin-start: 0px;
    -webkit-margin-end: 0px;
}
Inherited from user
Style Attribute {
    display: flex;
    box-sizing: border-box;
    flex-direction: row;
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
}
```
Also change the Styles.css file to this:

```
@import 'https://fonts.googleapis.com/css?family=Roboto:300,400,500';
@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
/*@import '~bootstrap/dist/css/bootstrap.css';*/
@import '~material-design-icons/iconfont/material-icons.css';
```
Same results as before. Not working.

**Comment by alexispolak** [comment]
Solved with this: npm install --save angular/material2-builds angular/cdk-builds
