### ISSUE TITLE
md-menu-item can only have one line

### ISSUE THREAD

**Issue by JamesHandshoe** [angular/material2#6170]
#### Bug, feature request, or proposal:
Currently, the md-menu-item can only have one line.  I need to have this type of behavior
User Name
User email
bothin of these in the same md-menu-item.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by julianobrasil** [comment]
I think that's because of [Material specs](https://material.io/guidelines/components/menus.html#):

_`Menus (...) They display a list of choices, with one choice per line.`_

**Comment by mmalerba** [comment]
Yep this is WAI according to spec
