### ISSUE TITLE
[autocomplete] input placeholder doesn't update when form control initially set

### ISSUE THREAD

**Issue by willshowell** [angular/material2#6174]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The autocomplete's `_setTriggerValue()` should mark the input container for check.

#### What is the current behavior?
The autocomplete sets the native input value and the placeholder does not update.

#### What are the steps to reproduce?
Visible in the demo-app at latest (e79f7f9)

![screen shot 2017-07-31 at 4 10 52 pm](https://user-images.githubusercontent.com/6475576/28796330-246b5cea-760b-11e7-9491-eea2111a142e.png)

#### Other
It works fine if you `setValue` after initializing the control

```ts
constructor() {
  this.stateCtrl = new FormControl('');
  // ...
  setTimeout(() => this.stateCtrl.setValue({code: 'CA', name: 'California'}))
}
```

cc @crisbeto

**Comment by crisbeto** [comment]
Will be resolved by https://github.com/angular/material2/pulls
