### ISSUE TITLE
Md-Raised-Button stays focused

### ISSUE THREAD

**Issue by Christofferoe** [angular/material2#618]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Button is expected to resume idle state.

#### What is the current behavior?
Button stays in focus state.

#### What are the steps to reproduce?
Click button, change tab, change back to initial page again.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Aesthetics and continuity.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular2.0.0-rc.1
Material2.0.0-alpha.5
Windows8.1
Chrome50.0.2661.102 m

#### Is there anything else we should know?
Here is the bug.
![bug](https://cloud.githubusercontent.com/assets/19717592/15760087/f1c8349e-2911-11e6-9227-918007cbd8e6.gif)

**Comment by DevVersion** [comment]
This will be covered in #289. We have the same problem / solution in Material 1 as well
 - https://github.com/angular/material/issues/7963

**Comment by Christofferoe** [comment]
Didn't realize, sorry. Should I close this or what?

**Comment by DevVersion** [comment]
@Christofferoe I think you can keep it open for now. @jelbourn will probably close it later, if needed.

**Comment by Christofferoe** [comment]
Alright, thanks for the quick reply. :)

**Comment by jelbourn** [comment]
Going to track via #289
