### ISSUE TITLE
Wrong font family for inputs in a Dialog

### ISSUE THREAD

**Issue by AntonisFK** [angular/material2#6183]
#### Bug, feature request, or proposal:
Incorrect Font family for **only** inputs in a Dialog 

#### What is the expected behavior?
Expected to have set font family Proxima Nova.

```// Custom typography settings here
$typography-config: mat-typography-config(
  $font-family: 'Proxima Nova'
   ....
);
```

#### What is the current behavior?
Font Family is set to  Times

#### What are the steps to reproduce?
1. Create custom theme.
2. Set typography font family.
3. create a dialog with inputs 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material@2.0.0-beta.8",
"typescript": "2.3.4",
browser: chrome

#### Is there anything else we should know?
The bug was also present when using a prebuilt theme.

**Comment by crisbeto** [comment]
Should be resolved in master by https://github.com/angular/material2/pull/5154.
