### ISSUE TITLE
required md-select is not higlighted as error on form submit

### ISSUE THREAD

**Issue by vovikdrg** [angular/material2#6184]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Select should be red same way as md-input

#### What is the current behavior?
Select is not highlighted it stay as untouched

#### What are the steps to reproduce?
https://plnkr.co/edit/jEvWLqsrlUrnBjkUUBes?p=preview click submit and you will see that input is showing error but select is not 

#### What is the use-case or motivation for changing an existing behavior?
Should be same way as other components

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/animations: 4.3.2
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.2

#### Is there anything else we should know?
In addition if required validator is applied md- controls should have asterix so user understand that fields are required. In Example md-input has required validator but label doesn't have *

**Comment by crisbeto** [comment]
This is resolved in master by https://github.com/angular/material2/pull/4754.

**Comment by finalxcode** [comment]
+1
