### ISSUE TITLE
Can't bind to 'mdDatepickerToggle' since it isn't a known property of 'button'. 

### ISSUE THREAD

**Issue by fabulias** [angular/material2#6186]
#### Bug, feature request, or proposal:
[X] Bug

#### What is the expected behavior?
I am update with` npm install --save angular/material2-builds angular/cdk-builds` and my DatePicker not work, my browser terminal return error with `mdDatepickerToggle`

```
Can't bind to 'mdDatepickerToggle' since it isn't a known property of 'button'
<button mdSuffix [ERROR ->][mdDatepickerToggle]="pickerInit"></button>
```

This is my code 

```
<md-input-container>
                  <input
                    mdInput
                    [mdDatepicker]="pickerInit"
                    placeholder="Fecha inicial"
                    [min]="minDate"
                    [max]="maxDate"
                    [value]="10-2-2017"
                    name="init"
                    #init="ngModel"
                    ngModel
                    required>
                  <button mdSuffix [mdDatepickerToggle]="pickerInit"></button>
                </md-input-container>
                <md-datepicker #pickerInit></md-datepicker>
```

5 minutes ago I worked well, I do not know what happened
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.0.0
Material github:angular/material2-builds (this show in package.json)
OS Mac

**Comment by CaerusKaru** [comment]
As of 5317, `[mdDatepickerToggle]` attribute has been changed to `md-datepicker-toggle` element

**Comment by ashishsharma123** [comment]
use can use md-datepicker-toggle like this:
` <md-datepicker-toggle mdSuffix [for]="picker"></md-datepicker-toggle>`

Hope this will help you :)

**Comment by BenRacicot** [comment]
@CaerusKaru I think there is a lot of example code out there with the former type `<button mdSuffix [mdDatepickerToggle]="pickerInit"></button>` 

https://material.angular.io/components/datepicker/overview being one.

**Comment by CaerusKaru** [comment]
@BenRacicot Yes, because the current release (2.0.0-beta.8) still officially supports the old type. This is a breaking change before beta 9, and the documentation will be updated accordingly.

**Comment by BenRacicot** [comment]
Thank you for clarifying @caeruskaru! Much clearer now. Looking forward to beta.9. I check everyday!

**Comment by BenRacicot** [comment]
@CaerusKaru not sure if I should open a new ticket or not but is this implemented in beta.10?

Getting loads of errors with            
```
<md-input-container style="width: 100%">
                <input mdInput formControlName="startDate" [mdDatepicker]="minDatePicker" placeholder="Min date">
                <!-- <button mdSuffix [mdDatepickerToggle]="minDatePicker"></button> -->
                <md-datepicker-toggle mdSuffix [for]="minDatePicker"></md-datepicker-toggle>
            </md-input-container>
```
What can I do to help here?

**Comment by ronit123321** [comment]
Guys any update regarding the usage of date-picker, on using <md-datepicker-toggle mdSuffix [for]="picker"></md-datepicker-toggle> ; i get this error

ERROR TypeError: Cannot read property 'disabled' of undefined
    at MdDatepickerToggle.get [as disabled] (material.es5.js:20168)
    at Object.View_MdDatepickerToggle_0._co [as updateDirectives] (MdDatepickerToggle.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13075)
    at checkAndUpdateView (core.es5.js:12255)
    at callViewAction (core.es5.js:12620)
    at execComponentViewsAction (core.es5.js:12552)
    at checkAndUpdateView (core.es5.js:12261)
    at callViewAction (core.es5.js:12620)
    at execEmbeddedViewsAction (core.es5.js:12578)
    at checkAndUpdateView (core.es5.js:12256)

**Comment by CaerusKaru** [comment]
@ronit123321 Using the example [here](https://material.angular.io/components/datepicker/overview), adding the `disabled` property to `md-datepicker-toggle` works properly. If you're having this issue and can recreate it in a plunkr, please file a separate issue.

**Comment by elwinarens** [comment]
Returning to an Angular + Material project after a month 😂 🔫

**Comment by BenRacicot** [comment]
I know your pain @elwinarens ! Look out for this too: https://github.com/angular/material2/pull/7346
