### ISSUE TITLE
Large Material module size in bundle

### ISSUE THREAD

**Issue by hemantjadon** [angular/material2#6188]
#### Bug, feature request, or proposal:
Bug Report / Question

#### What is the expected behavior?
The build bundle should only contain the imported modules, not the complete Angular Material

#### What is the current behavior?
The build bundle contains the whole package even if only there is one module imported from angular material.

![screen shot 2017-08-01 at 9 29 21 am](https://user-images.githubusercontent.com/11755543/28808722-f3953532-769b-11e7-9281-ad071d61d9f3.png)

What i imported in the chunk is 
```typescript
import { MdTooltipModule } from '@angular/material';

imports: [
   MdTooltipModule
]
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
> Angular : v4.0.0
> Material : v2.0.0-beta3

#### Is there anything else we should know?

No

**Comment by ErikWegner** [comment]
Same issue here: #6210

**Comment by ErikWegner** [comment]
Same issue here: #4137

**Comment by jelbourn** [comment]
This is tracked on #4137

**Comment by jelbourn** [comment]
Duplicate of  #4137
