### ISSUE TITLE
Md-icon inside md-expansion-panel header not aligned correctly

### ISSUE THREAD

**Issue by alexandrupaul7** [angular/material2#6192]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-icon should stick with the md-panel-tile text

#### What is the current behavior?
md-icon not aligned correctly

#### What are the steps to reproduce?

Plunker: http://plnkr.co/edit/6VVJbXSkYGiWJ1OaEp5u?p=preview

            <md-expansion-panel>
                <md-expansion-panel-header>
                    <md-panel-title>
                      <md-icon>search</md-icon> Search
                    </md-panel-title>                    
                </md-expansion-panel-header>
                <div>
                    <div>Something here</div>
                </div>
            </md-expansion-panel>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4
material beta 8

**Comment by willshowell** [comment]
I believe https://github.com/angular/material2/pull/5950 will fix this

**Comment by willshowell** [comment]
It didn't entirely. Your example still requires

```scss
.mat-content {
  align-items: center;
}
```

**Comment by josephperrott** [comment]
Resolved via: #5950
