### ISSUE TITLE
MdSlider doesn't emit change event if value has been changed externally

### ISSUE THREAD

**Issue by benelliott** [angular/material2#6195]
#### Bug, feature request, or proposal:

If you set an `MdSlider` instance's value to X using the UI control, then change it to Y somewhere else in the parent component, then change it back to X using the UI control, the slider will not emit a `change` event from the Y => X change.

#### What is the expected behavior?

A `change` event should be fired.

#### What is the current behavior?

A `change` event is not fired.

#### What are the steps to reproduce?

http://plnkr.co/edit/nXazEbsNCGBLaF9OZMqf?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Incorrect behaviour

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material HEAD e79f7f9, Angular  4.3.2

#### Is there anything else we should know?

I think this is caused by the fact that the slider only emits a change event if the newly value is different to the last emitted value (as opposed to the current value). You can see this in the code [here](https://github.com/angular/material2/blob/master/src/lib/slider/slider.ts#L585).

**Comment by mmalerba** [comment]
Ah good find, and thanks for the detective work on the logic error!

**Comment by roserek** [comment]
When will the release with this fix ?

**Comment by roserek** [comment]
@mmalerba This bug still exist.

**Comment by mmalerba** [comment]
@roserek it seems to work now: http://plnkr.co/edit/n1QOJSHvLLaTlhm5XVvx?p=preview are you on beta 10?

**Comment by roserek** [comment]
@mmalerba Sory, you are right. I had beta 8 version, my mistake.
