### ISSUE TITLE
MdTable sort indicators backwards

### ISSUE THREAD

**Issue by mcalmus** [angular/material2#6198]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
According to the material spec site (https://material.io/guidelines/components/data-tables.html#data-tables-interaction), an up arrow indicates smallest value at top (ascending sort).

#### What is the current behavior?
All examples in documentation (https://material.angular.io/components/sort/overview) has up arrow indicating largest value at top (descending sort)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta 8

**Comment by andrewseguin** [comment]
You seem to be right about this, looks like most other products have them switched, and Material spec shows an example of the same. Thanks for pointing this out, we'll switch them around

**Comment by mcalmus** [comment]
Yeah. We had a user notice.
