### ISSUE TITLE
MdButton focus rendering

### ISSUE THREAD

**Issue by anwalkers** [angular/material2#6200]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When button is programatically focused it should render as if it has focus. 

#### What is the current behavior?
It seems to have focus set, if I hit the tab key it moves to the next control, but it does not render as if it has focus.

#### What are the steps to reproduce?
Plunker: http://plnkr.co/edit/HhD8eF?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I would like to set a button in a view as the focused element so that the user does not have to select the button using the mouse or keyboard.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest Angular, Material 2, TypeScript 2.4.2, on a Windows OS computer in Chrome, FireFox, and Edge

#### Is there anything else we should know?
Nope

**Comment by crisbeto** [comment]
This should be resolved by https://github.com/angular/material2/pull/5966.

**Comment by anwalkers** [comment]
This will be resolved by #5966.
