### ISSUE TITLE
[Table] - Prevent selection on some places of md-table

### ISSUE THREAD

**Issue by dev054** [angular/material2#6203]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
I'd expect to select the rows only clicking in checkbox or maybe in rows, but not on buttons.

#### What is the current behavior?
Rows are being selected if you click on `md-menu`.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://plnkr.co/edit/iFVIE17s5T2WAmRyurRX?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2.0.0-Beta8.

#### Is there anything else we should know?
It could be added to docs on how to do it (if it's currently possible). I can see a lot of use cases that dev just want to allow user to select a row if click specifically on checkbox and nowhere else.

**Comment by andrewseguin** [comment]
The table does not come with selection. Sounds like you have a click handler that does not stop the propagation of the click event so it is raised to the row.
