### ISSUE TITLE
How do I import some components, not all of them? 

### ISSUE THREAD

**Issue by Striveyazi** [angular/material2#6210]
#### What is the expected behavior?
i want to import some components ,but not all them.
#### What is the current behavior?
import all components

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "^2.0.0-beta.5"

**Comment by Striveyazi** [comment]
https://material.angular.io/guide/getting-started step3 
but it's compiled file is so big . 
like this 
![image](https://user-images.githubusercontent.com/18276182/28854144-ee004a68-7767-11e7-8209-dfafc4d9ffd1.png)

It's the same as  import { MaterialModule} from "@angular/material";
**this compiled file so big**
**i need your help**

**Comment by Striveyazi** [comment]
@

**Comment by julianobrasil** [comment]
Have you taken a look at the final size after using `--prod` compiler option? The tree shaking should take care of the not imported components.

**Comment by Striveyazi** [comment]
yes .use **--prod** compiler option  .
import { MaterialModule} from "@angular/material" 
the compiled filesize  same as 
import { MyCustomMasterialModule} from './..'

and the compiled file include some word that it isn't i import ,like this. 
![image](https://user-images.githubusercontent.com/18276182/28858057-74a7fde6-7780-11e7-9e90-5b45cb6da0e9.png)
Can you see what I'm talking about?
can you tell me this reason?thank u vary much

**Comment by Striveyazi** [comment]
my project not import **MaterialModule** module,any import some module of material,but the complied file some like compile all module .
![image](https://user-images.githubusercontent.com/18276182/28858134-1c65a6e6-7781-11e7-89b4-377afddf1760.png)
![image](https://user-images.githubusercontent.com/18276182/28858186-6d5acac2-7781-11e7-90dd-1901287c34cd.png)
@julianobrasil

**Comment by julianobrasil** [comment]
I have a small size project over here using lazy  loading - all source files put together result in 900KB on disk - (using angular-cli) with the following statistics (total main file not so different from what I see in your images):

- ng build:
  - Total files size: ~16MB
  - main size + chunks: ~3.64MB

- ng build --prod:
  - Total files size: ~3.63MB
  - main size + chunks: ~1.3MB

If you can modify the project structure, the using of lazy loading breaks up the main file in 4 parts (in my structure above I have 4 main routes). It helps keeping the individual parts the file user will have to download considerably smaller comparing to if the user have to get all the app at once.

**Comment by Striveyazi** [comment]
I migrate my project to angular-cli .then build result. this biggest file ~ 1.4MB.
this file include many 'md- ' selectors,and these selectors isn't import to my project. like this image
![image](https://user-images.githubusercontent.com/18276182/28904702-5e16d4b6-783f-11e7-8152-4b287beda9c0.png)

**Comment by Striveyazi** [comment]
In short. in my project,only import only a few components , but the compiled file contains all the components.The files that cause me to pack are very large ，so,I wonder why this is?

**Comment by julianobrasil** [comment]
You're right, @Striveyazi. The vendor...bundle.js file is always generated with all material modules.

### 1 - Empty angular-cli project (no material):
![image](https://user-images.githubusercontent.com/25405143/28917030-969daabe-781a-11e7-83b0-02065520cae7.png)

### 2 - Empty angular-cli project (material installed, but no module imported):
![image](https://user-images.githubusercontent.com/25405143/28917451-18ce6b44-781c-11e7-8502-23fc1dbc1190.png)

### 3 - Empty angular-cli project (MdInputModule imported) and one mdInput in app.component.html:
![image](https://user-images.githubusercontent.com/25405143/28917429-00b644a0-781c-11e7-80b4-c25ded1a614a.png)

### 4 - Empty angular-cli project (MdInputModule and MdCardModule imported): very similar to the previous image:
![image](https://user-images.githubusercontent.com/25405143/28918097-7200c282-781e-11e7-84ac-60e169a5747d.png)

### 5- Empty angular-cli project (MdInputModule and MdCheckboxModule imported and 375 `md-checkbox` es in app.component.html:
![image](https://user-images.githubusercontent.com/25405143/28917773-312e3ad8-781d-11e7-9dd0-55dc8870f264.png)

### 6 - The same as above, but with simple <input type="checkbox"> replacing the md-checkboxes:
![image](https://user-images.githubusercontent.com/25405143/28917872-8d988ee0-781d-11e7-9fd8-932388759a94.png)

There's a simillar issue here: #5942

@willshowell, do you think there's a mistake in this configs? It's really doesn't seems to be possible to generate a smaller vendor bundle file by just controling the number of imported modules.

**Comment by Striveyazi** [comment]
You got up very early！Thank you very much for your patient help. Thank you very much。
I expect that you can  fix this bug，good luck～

**Comment by willshowell** [comment]
@julianobrasil yikes this isn't my forte, but I'll try to take a look later today! What version of the cli?

**Comment by julianobrasil** [comment]
@willshowell: `@angular-cli` 1.2.1

**Comment by willshowell** [comment]
I was hoping https://github.com/angular/material2/issues/4137#issuecomment-317190278 would help, but sadly here are my results:


```
@angular/cli: 1.2.6
805K vendor.xxx.bundle.js
```

```
@angular/cli: 1.3.0-rc.3
805K vendor.xxx.bundle.js
```

<details>
 <summary>Modules</summary>

_Setup is strictly `ng new` and following the Getting Started Guide_

 ```ts
// app.module.ts
import 'hammerjs';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    CustomMaterialModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

```ts
// custom-material.module.ts
@NgModule({
  exports: [
    MdButtonModule,
    MdCheckboxModule,
  ]
})
export class CustomMaterialModule { }
```
</details>

**Comment by julianobrasil** [comment]
@jelbourn, is there anyone taking care of this part to help us?

**Comment by jelbourn** [comment]
This issue is tracked via #4137. @IgorMinar is actively working on this.

**Comment by julianobrasil** [comment]
@willshowell @Striveyazi, take a look: https://github.com/angular/material2/issues/4137#issuecomment-320214029

**Comment by julianobrasil** [comment]
@willshowell @Striveyazi, take a look: #4137 (comment): the final size decreased a lot!

**Comment by Striveyazi** [comment]
wow! nice! thank you !
