### ISSUE TITLE
table with paginator pageIndex bug.

### ISSUE THREAD

**Issue by mrdulin** [angular/material2#6216]
#### Bug, feature request, or proposal:
My `pageSize` is `10`. 
The backend api first page index is `1`. But When I set the `pageIndex` of paginator to `1`, the table show `11-20 of NaN`
 
#### What is the expected behavior?

I want the table show `1-10 of NaN`.

#### What is the current behavior?

 the table show `11-20 of NaN`

#### What is the use-case or motivation for changing an existing behavior?

The backend api first page index is `1`. So i set the default page index of paginator to `1`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/core": "^4.3.1",
"@angular/material": "^2.0.0-beta.8",

**Comment by willshowell** [comment]
This is the intended behavior.

> `pageIndex`:  The zero-based page index of the displayed list of items. Defaulted to 0.
