### ISSUE TITLE
md-checkbox selection vs native checkbox selection

### ISSUE THREAD

**Issue by qorsmond** [angular/material2#6217]
#### Bug, feature request, or proposal:

The md-checkbox does not show check mark when clicking on it and binding to the checked property

#### What is the expected behavior?

When the md-checkbox is clicked it should show a check mark like the native checkbox

#### What is the current behavior?

When the md-checkbox is clicked it does not show a check mark like the native checkbox

#### What are the steps to reproduce?

Plunker template: http://plnkr.co/edit/XZkWga?p=preview

Click the md-checkbox's for selection; the selected id's is displayed but the check marks is not:

![image](https://media.giphy.com/media/d2jihS0gwSUkt08U/giphy.gif)

Working when native checkbox's clicked:

![image](https://media.giphy.com/media/xT39CXPLlKe0mlGZfG/giphy.gif)

#### What is the use-case or motivation for changing an existing behavior?

My use-case is for the client to be able to select one or multiple items. When the user checks the checkbox's it will allow multiple selection, and when the user clicks on the label of the checkbox it will select only that item and clear the other selections:

![image](https://media.giphy.com/media/l1J3CtATqGAinSeWY/giphy.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/core": "^4.3.1",
"@angular/cdk": "^2.0.0-beta.8",
"@angular/material": "^2.0.0-beta.8",

also tried with
"@angular/cdk": "github:angular/cdk-builds",
"@angular/material": "github:angular/material2-builds",

**Comment by tinayuangao** [comment]
Here's the code to make it working: 
```html
<div *ngFor="let item of operationalItems" >
  <input type="checkbox" [checked]="item.selected" (click)="doMultiSelection($event, item.id)" />
  <md-checkbox [(ngModel)]="item.selected" (change)="doMultiSelection($event, item.id)">
    {{ item.desc }} {{item.selected}}
  </md-checkbox>
</div>
```
