### ISSUE TITLE
[Select] Custom text for multiple selected values

### ISSUE THREAD

**Issue by davidreher** [angular/material2#6218]
#### Bug, feature request, or proposal:
Feature request: Make it possible to adjust the text which is shown if multiple values are selected in MdSelect.

#### What is the expected behavior?
When all values are selected, the text is "[all] selected.
When more than 2 values are selected the text is "2 selected".

#### What is the current behavior?
All values are shown, seperated by `,`, if they won't fit, ellipses are applied.

#### What are the steps to reproduce?
Go to the [plunk](http://plnkr.co/edit/texK2pTSyS4nIQWzNYB9?p=preview) and select all values.

#### What is the use-case or motivation for changing an existing behavior?
To our customers it is more useful to see how many values are selected (whether or not all are selected), rather than seeing only the first part of the text of the first selected item.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
[master](https://github.com/angular/material2)

#### Is there anything else we should know?
I already tried extending MdSelect. I think this is the best option, but I got stuck on all the errors in the (copied) template :(

Another option would be to have a callback as input property which is evaluated as part of [triggerValue](https://github.com/angular/material2/blob/34ec068741186d471448745e54040ddc4e8fe81e/src/lib/select/select.ts#L530) upon changes ...

I can also work on a PR if this is something which is required by others as well and if you have some guidance on the best option ...

**Comment by willshowell** [comment]
Duplicate of https://github.com/angular/material2/issues/2275

**Comment by davidreher** [comment]
I think this is somewhat different. Does it really solve my issue if I can specify how the selected values should be rendered? Still they will be concatenated or do I get it wrong?

**Comment by willshowell** [comment]
Yeah I see the distinction now, good call. I know I'd seen a similar request (https://github.com/angular/material2/pull/2722#issuecomment-277622084) but it doesn't look like there's issue tracking for it yet!

**Comment by davidreher** [comment]
@willshowell: Any ideas on the implementation? What would fit best? Should the text be included by material and then i18n-ized or should we have a callback?

**Comment by willshowell** [comment]
I feel like a callback similar to autocomplete's `displayWith` is very comparable and makes sense for this. But if the default changes to "x, y, and 4 others" then it would certainly require internationalization.

**Comment by davidreher** [comment]
will be fixed by #3341
