### ISSUE TITLE
Invalid class in md-input when pattern is invalid

### ISSUE THREAD

**Issue by Dahriel** [angular/material2#622]
#### Bug          
Does the class should be ng-invalid?

&lt;md-input flex=&quot;&quot; ngcontrol=&quot;ip&quot; pattern=&quot;^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$&quot; placeholder=&quot;IP&quot; _nghost-csu-13=&quot;&quot; class=&quot;ng-dirty ng-touched **ng-invalid**&quot;&gt;
    ...
    &lt;input _ngcontent-csu-13=&quot;&quot; aria-target=&quot;&quot; class=&quot;md-input-element **ng-valid** ng-dirty ng-touched&quot; id=&quot;md-input-4&quot; spellcheck=&quot;false&quot; maxlength=&quot;-1&quot; type=&quot;text&quot;&gt;
    ....
&lt;/md-input&gt;

This code come from Chrome Element tab
"@angular2-material/input": "2.0.0-alpha.4",

**Comment by jelbourn** [comment]
@Dahriel it's not clear what you're reporting. Please follow the issue template.
