### ISSUE TITLE
[option/menu] hover and active background colors

### ISSUE THREAD

**Issue by willshowell** [angular/material2#6229]
#### Bug, feature request, or proposal:
Styling issue

#### Current
* the spec appears to show active option backgrounds at 12% opacity but currently they are 4% 
* active options have the same background opacity as hovered options

#### Expected
* Active option backgrounds should be 12% opacity and either keep 4% for hover or remove it entirely

#### What are the steps to reproduce?

This shows how hovered options and active actions aren't distinguishable. Before hitting <kbd>enter</kbd>, I am not sure whether Hawaii or Indiana will be chosen.

![autocomplete-option-hover](https://user-images.githubusercontent.com/6475576/28887825-8a3e278c-778c-11e7-8aac-1fe784639c26.gif)

The following show the difference between the active select and the spec
![screen shot 2017-08-02 at 2 13 16 pm](https://user-images.githubusercontent.com/6475576/28887994-10030720-778d-11e7-8783-fbebac950154.png)
![screen shot 2017-08-02 at 2 13 41 pm](https://user-images.githubusercontent.com/6475576/28888000-116b1a8a-778d-11e7-9e21-4e3bd4837482.png)

**Comment by crisbeto** [comment]
It definitely looks darker, but where did you find the 12%? I'm trying to look through the spec, but I can't find specific numbers for the menu and select.

**Comment by willshowell** [comment]
I measured the hex values with a color picker.

Menu panel: `#FAFAFA`
Active option: `#DCDCDC`

0xFA / 0xDC = 250 / 220 = 0.12
