### ISSUE TITLE
input: rename placeholder to label

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#6240]
These are now separate concepts in the newest version of the material spec. The thing we currently call "placeholder" is really the label. We need to rename it in order to free up the "placeholder" attribute to be used for its intended purpose. (Prerequisite to #6194)

**Comment by jwlundk** [comment]
Hi,
I currently have a problem using placeholder with floatPlaceholder="always" and a readonly input. I tested with Chrome 61, IE 11 and Edge seem to work.

Take a look at this plunkr: http://plnkr.co/edit/lAHxoFvEJXrJA9Em3Sqi?p=preview

When you doubleclick the text, the placeholder will be selected. I think this could be solved by separating placeholders and labels. Or should I create a new issue for this? Sorry, I am new to github, this is my first comment :)

**Comment by mmalerba** [comment]
@jwlundk yes this should be resolved when we separate them, in the mean time you can use the `<mat-placeholder>` element instead of the `placeholder` attribute to work around this: http://plnkr.co/edit/2O00ZmcRErxL9bHv1Xk4?p=preview

**Comment by jwlundk** [comment]
@mmalerba your solution works great, thank you very much!

**Comment by mmalerba** [comment]
closing as duplicate of #6194
