### ISSUE TITLE
[BUG] Datepicker - manually change day in input

### ISSUE THREAD

**Issue by datcuemil** [angular/material2#6248]
#### Bug, feature request, or proposal:
The input and the datepicker communicate incorrectly. If I select a date from the picker, it will be displayed DD/MM/YYYY.
Following this logic, if I try to manually modify the DD, when I open the datepicker, and if I set a value from 1-12, the corresponding month will be selected in the picker. 

#### What is the expected behavior?
If the output date format of the datepicker is of format DD/MM/YYY, when I manually modify the day (DD) that day should be selected in the picker.

#### What is the current behavior?
If I modify the day, it modifies the month in the background.

#### What are the steps to reproduce?
Go to: https://material.angular.io/components/datepicker/overview
Select any date. current date for example. (03/08/20017)
Open the datepicker again. Now, the datepicker will display March 2017. 

#### What is the use-case or motivation for changing an existing behavior?
Because is illogic and stupid how the component updates and behaves.

**Comment by tinayuangao** [comment]
The date format is MM/DD/YYYY in the material.angular.io examples. So 03/08/2017 means March 08, 2017, not August 03, 2017.

**Comment by datcuemil** [comment]
Are you serious? Did you at least checked what I said?

Select from datepicker 10 august 2017. It will display 10/08/2017 (DD/MM/YYYY). 
Open the datepicker again, it will display october as selected month.

I'll reopen this thread until someone actually tries to replicate the bug and fixes it.
