### ISSUE TITLE
SnackBarRef component instance ?

### ISSUE THREAD

**Issue by fazega** [angular/material2#6252]
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

Having a standard for the instance reference and sharing data.

#### What is the current behavior?

To get the component instance of a SnackBarRef, the attribute is "instance".
To get the component instance of a DialogRef, the attribute is "componentInstance". Besides, in the [documentation](https://material.angular.io/components/dialog/api) we can see a method to share data directly has been implemented, it's not the case for SnackBarRef.

#### What is the use-case or motivation for changing an existing behavior?

I think having a standard for these components "with reference" would be clearer for the user.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest of each.

**Comment by willshowell** [comment]
Agreed that it would be nice to be consistent with `componentInstance`, but I don't see what you mean about `_instance`.

https://github.com/angular/material2/blob/master/src/lib/snack-bar/snack-bar-ref.ts#L17-L19

**Comment by fazega** [comment]
Oops, i perhaps haven't updated to the latest version, my bad. It was not the central point though ;)

**Comment by jelbourn** [comment]
Closing this since, after releasing 5.0.0, we aren't making any more breaking API changes.
