### ISSUE TITLE
[BUG] Datepicker - manually change day in input

### ISSUE THREAD

**Issue by datcuemil** [angular/material2#6263]
Bug, feature request, or proposal:

The input and the datepicker communicate incorrectly. If I select a date from the picker, it will be displayed DD/MM/YYYY.
Following this logic, if I try to manually modify the DD, when I open the datepicker, and if I set a value from 1-12, the corresponding month will be selected in the picker.

What is the expected behavior?

If the output date format of the datepicker is of format DD/MM/YYY, when I manually modify the day (DD) that day should be selected in the picker.

What is the current behavior?

If I modify the day, it modifies the month in the background.

What are the steps to reproduce?

Go to: https://material.angular.io/components/datepicker/overview

Select from datepicker 10 august 2017. It will display 10/08/2017 (DD/MM/YYYY).
Open the datepicker again, it will display october as selected month.

I'll reopen this thread until someone actually tries to replicate the bug and fixes it.

What is the use-case or motivation for changing an existing behavior?

Because is illogic and stupid how the component updates and behaves.

**Comment by julianobrasil** [comment]
It's not a bug. You need to build a custom date adapter: https://plnkr.co/edit/jc4Ywu?p=preview

See the docs overview at the bottom, the "Internationalization" title.

**Comment by mmalerba** [comment]
@julianobrasil is correct. Once the new Angular i18n API is available we will be able to improve the `NativeDateAdapter` to handle this case better (https://github.com/angular/material2/issues/6030), but currently you'll need to create a custom `DateAdapter`
