### ISSUE TITLE
MdDialog opens additional dialogs when enter or space key is pressed during opening transition

### ISSUE THREAD

**Issue by peterdavey** [angular/material2#6266]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The initial dialog being opened should close returning the user to the state before dialog open was triggered

#### What is the current behavior?
After each press of either enter or spacebar a new dialog is opened on top of the initial dialog. The users is then required to close all these windows

#### What are the steps to reproduce?
Create an event causing an mddialog to open then immediately press enter or space key multiples times until this opening transition is finished. 

This behaviour can be viewed in the current example page https://material.angular.io/components/dialog/examples

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular: 4.3.3, material: 2.0.0-beta.8, typescript: 2.4.2, browsers checked firefox 54.0.1 (64-bit) and chrome 60.0.3112.78 (Official Build) (64-bit)

**Comment by crisbeto** [comment]
Should be sorted one by https://github.com/angular/material2/pull/5769 in the next release.
