### ISSUE TITLE
Can I open a mdDialog and pass some data through a service within a component?

### ISSUE THREAD

**Issue by mrdulin** [angular/material2#6267]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

I want to open the `mdDialog` and pass some data through a service within a component

#### What is the current behavior?

The result is the dialog show but with nothing, even the hard code content. e.g `<h2 md-dialog-title>tip</h2>`

Display like this: 

![image](https://user-images.githubusercontent.com/17866683/28963271-27bf8d5c-793b-11e7-823b-edf60999cc5f.png)

#### What are the steps to reproduce?

`dialogService.ts`:

```ts
@Injectable()
export class DialogService {

  constructor(
    private _dialog: MdDialog
  ) { }

  openDialog() {
    const dialogRef = this._dialog.open(DialogComponent, {
      data: {
        msg: '123123'
      }
    });
  }
}
```

`dialog.component.ts`: 

```ts
import { Component, Inject, OnInit } from '@angular/core';
import { MdDialogRef, MD_DIALOG_DATA } from '@angular/material';

@Component({
  selector: 'dialog',
  templateUrl: './dialog.component.html'
})
export class DialogComponent implements OnInit {
  msg: string;
  constructor(
    public dialogRef: MdDialogRef<DialogComponent>,
    @Inject(MD_DIALOG_DATA) public data: any
  ) {}

  ngOnInit() {
    this.msg = this.data.msg;
  }
}
```

`dialog.component.html`:

```html
<h2 md-dialog-title>tip</h2>
<md-dialog-content>
  <p>{{msg}}</p>
</md-dialog-content>
```

#### What is the use-case or motivation for changing an existing behavior?

In a http interceptor service, call the `MdDialog` service to open a global dialog.

the result is same.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

`  "@angular/core": "^4.3.3",`
`"@angular/material": "^2.0.0-beta.8",`

**Comment by chyzwar** [comment]
```js
@Injectable()
export class DialogService {

  constructor(
    private _dialog: MdDialog
  ) { }

  openDialog() {
    const dialogRef = this._dialog.open(DialogComponent);
     dialogRef.componentInstance.data= {
        data: {
            msg: '123123'
          }
      };
  }
}

dialog.component.ts:

import { Component, Inject, OnInit } from '@angular/core';
import { MdDialogRef} from '@angular/material';

@Component({
  selector: 'dialog',
  templateUrl: './dialog.component.html'
})
export class DialogComponent implements OnInit {
  data: any;
   msg: any

  constructor(
    public dialogRef: MdDialogRef<DialogComponent>
  ) {}

  ngOnInit() {
    this.msg = this.data.msg;
  }
}

```

**Comment by mrdulin** [comment]
The reason is my dialog selector --- `dialog`. change it to `tip-dialog` works fine.

**Comment by joejordanbrown** [comment]
You are using the element name `dialog` which is an [HTML element](https://developer.mozilla.org/en/docs/Web/HTML/Element/dialog) which is part of the HTML specifications.  You can not create a custom element and override the default element. 

This is why [Angular Style Guide](https://angular.io/guide/styleguide#component-selector-names) recommends.

> Do use dashed-case or kebab-case for naming the element selectors of components.
> 
> Why? Keeps the element names consistent with the specification for Custom Elements.

**Comment by mrdulin** [comment]
@joejordanbrown thanks. I forgot it.
