### ISSUE TITLE
Md table

### ISSUE THREAD

**Issue by jisqaqov** [angular/material2#6269]
Hi there. In my point of view the data table component is poorly developed. In comparison primeng components are far better and implemented great. You have to create columns with strange * sign, when we just can pass header name as bind variable. 
**Let's compare data table in primeng:**
<p-dataTable [value]="cars">
    <p-column field="vin" header="Vin"></p-column>
</p-dataTable>

**where in material2 you have very ugly style:**

<cdk-table #table [dataSource]="dataSource" class="example-table">
    

    
    <ng-container cdkColumnDef="userId">
      <cdk-header-cell *cdkHeaderCellDef class="example-header-cell"> ID </cdk-header-cell>
      <cdk-cell *cdkCellDef="let row" class="example-cell"> {{row.id}} </cdk-cell>
    </ng-container>

    
    <ng-container cdkColumnDef="progress">
      <cdk-header-cell *cdkHeaderCellDef class="example-header-cell"> Progress </cdk-header-cell>
      <cdk-cell *cdkCellDef="let row" class="example-cell"> {{row.progress}}% </cdk-cell>
    </ng-container>

    
    <ng-container cdkColumnDef="userName">
      <cdk-header-cell *cdkHeaderCellDef class="example-header-cell"> Name </cdk-header-cell>
      <cdk-cell *cdkCellDef="let row" class="example-cell"> {{row.name}} </cdk-cell>
    </ng-container>

    
    <ng-container cdkColumnDef="color">
      <cdk-header-cell *cdkHeaderCellDef class="example-header-cell">Color</cdk-header-cell>
      <cdk-cell *cdkCellDef="let row" class="example-cell"
                [style.color]="row.color">
        {{row.color}}
      </cdk-cell>
    </ng-container>

    <cdk-header-row *cdkHeaderRowDef="displayedColumns" class="example-header-row"></cdk-header-row>
    <cdk-row *cdkRowDef="let row; columns: displayedColumns;" class="example-row"></cdk-row>
  </cdk-table>

It is even worse to write code in component to get work this component in material2

I assume component should be completely refactored; Generally i think primeng components are far better than components of material.

**Comment by willshowell** [comment]
Links: 
* [CdkTable design document](https://docs.google.com/document/d/1ZyKhwrgqfTBAn7saTq2jPlep2_CwSw5DeoZ8UbaXrC0/preview#)
* [strange * sign](https://angular.io/guide/structural-directives)

**Comment by andrewseguin** [comment]
Sounds like you want something similar to what we have planned for our simple table #5889
