### ISSUE TITLE
[dialog] improved api for knowing state of all dialogs

### ISSUE THREAD

**Issue by willshowell** [angular/material2#6272]
#### Bug, feature request, or proposal:
Feature request

#### Motivation

I have a "top priority" dialog that should dismiss all other dialogs before opening. In order to know when no other dialogs are open, I have to access a docs-private property, `_openDialogs`:

```ts
openImportantDialog() {
  // Start closing each of the open dialogs
  this.dialog.closeAll();

  // When all dialogs are closed, open the important dialog
  this.noDialogsOpen.first().subscribe(() => {
    this.dialog.open(MyImportantDialog);
  });
}

/** Emits when no dialogs are open */
get noDialogsOpen(): Observable<void> {
  if (this.dialog._openDialogs.length) {
    return this.dialog.afterAllClosed;
  } else {
    return this.dialog.afterAllClosed.startWith(null);
  }
}
```

It would be nice if I could do something like

```ts
openImportantDialog() {
  this.dialog.afterAllClosed.first().subscribe(() => {
    this.dialog.open(MyImportantDialog);
  });
}
```

except `afterAllClosed` only emits after the final dialog closes, but not when there are no dialogs to begin with.

#### Suggested behavior

One or both of the following: 

1. `_openDialogs` becomes `openDialogs`
2. `afterAllClosed` (or a new property) emits immediately to new subscribers if no dialogs are currently opened

**Comment by jelbourn** [comment]
Overall sounds good, we should do both of those things.

In making  `_openDialogs` public, I'd want to add an `id` property to the the `MdDialogConfig` and `MdDialogRef` (use the config ID on open if it exists, otherwise generate one). Maybe also a `getDialogById` method. This will make it easier to get at specific dialog instances.
