### ISSUE TITLE
md-dialog-close should also have an input for mdDialogClose

### ISSUE THREAD

**Issue by rockmacaca** [angular/material2#6278]
#### Bug, feature request, or proposal:
Request

#### What is the expected behavior?
Using the dialog close directive should allow the following syntax
```html
<button md-button [mdDialogClose]="true">Okay</button>
```

#### What is the current behavior?
Angular complains it can't bind to `mdDialogClose` since it isn't listed as a valid input

#### What are the steps to reproduce?
https://plnkr.co/edit/m7e7vFIKKgTiWIwCY7pc?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I've noticed that across the library, components use kebab-case and directives use camelCase (but also allow kebab-case) for their selectors. I'd like to keep this consistent within my application, but I can't because while `[mdDialogClose]` is a valid selector, I can't bind a value to it.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

**Comment by seba161189** [comment]
HTML  
<button mat-button type="button" (click)="close()">Cancelar</button>

COMPONENT
on ngInit you can save the value and then if you cancel return that one
 this.initInput = this.form.value.input;
  close() {
    this.dialogRef.close(this.initInput);
  }
