### ISSUE TITLE
Md-Paginator configurable text

### ISSUE THREAD

**Issue by Pypoli** [angular/material2#6283]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
I would like to be able to define the text in the paginator.

#### What is the current behavior?
Paginator text is always "Items per page"

#### What is the use-case or motivation for changing an existing behavior?
My client would prefer it said "Rows per page." 
I'm sure other clients out there will be as anal.

**Comment by andrewseguin** [comment]
The paginator receives its text values from the injected [MdPaginatorIntl](https://github.com/angular/material2/blob/master/src/lib/paginator/paginator-intl.ts) service. This can be extended and provided by your app to override the defaults.

```
@Injectable()
export class CustomPaginator extends MdPaginatorIntl {
  itemsPerPageLabel = 'Rows per page';
}
```

See https://plnkr.co/edit/IIwOGOQsak6QIaLmFNqz?p=preview for an example.

See also #5902 for a duplicate request
