### ISSUE TITLE
classes with font property not setting font-family to style

### ISSUE THREAD

**Issue by gigioSouza** [angular/material2#6284]
#### Bug, feature request, or proposal:
Started a new project with angular 4.0.0 and angular/material 2.0.0-beta.8
imported the prebuilt-theme into my styles.css
linked the Roboto font from Google Fonts

The result is that the input is not setting the font style, searching thru the elements with dev tools and searching in the css source code, I think that the "problem" is with the `font` property's value. 
The dev tools alerts that this property's value is invalid.

#### What is the expected behavior?
I expected all componentes to be styled with Roboto font.

#### What is the current behavior?
MdInput component doesn't use the roboto font

#### What are the steps to reproduce?
Create a new project with @angular/cli and follow the get started section from @angular/material
https://material.angular.io/guide/getting-started

The following screenshot shows the rendered components and the dev tools feedback.
The toolbar uses `font-family` instead of `font`
The current value of the `font` property is `400 inherit/1.125 Roboto,"Helvetica Neue",sans-serif;`

![img1](https://user-images.githubusercontent.com/4052932/28992491-11c61050-7974-11e7-9fc6-19bfe4f85313.png)

**Comment by crisbeto** [comment]
This has been fixed in https://github.com/angular/material2/pull/5154.
