### ISSUE TITLE
ng build failed with: Cannot find module '@angular2-material/button/button'. ...

### ISSUE THREAD

**Issue by txgo** [angular/material2#629]
ng build failed.
OS: Ubuntu 15.10
Node: node v4.4.5 (and v4.3，v5.6, v6.2)

npm install successfully but ng build and ng serve failed with error output:

Build error

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/button/button-demo.ts (2, 34): Cannot find module '@angular2-material/button/button'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/button/button-demo.ts (3, 22): Cannot find module '@angular2-material/icon/icon'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/button-toggle/button-toggle-demo.ts (2, 43): Cannot find module '@angular2-material/button-toggle/button-toggle'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/button-toggle/button-toggle-demo.ts (5, 8): Cannot find module '@angular2-material/core/coordination/unique-selection-dispatcher'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/button-toggle/button-toggle-demo.ts (6, 22): Cannot find module '@angular2-material/icon/icon'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/card/card-demo.ts (2, 24): Cannot find module '@angular2-material/button/button'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/card/card-demo.ts (3, 34): Cannot find module '@angular2-material/card/card'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/checkbox/checkbox-demo.ts (3, 26): Cannot find module '@angular2-material/checkbox/checkbox'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/button-toggle/button-toggle.spec.ts (22, 8): Cannot find module '@angular2-material/core/coordination/unique-selection-dispatcher'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/button-toggle/button-toggle.ts (18, 8): Cannot find module '@angular2-material/core/coordination/unique-selection-dispatcher'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/button-toggle/button-toggle.ts (19, 33): Cannot find module '@angular2-material/core/annotations/field-value'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/checkbox/checkbox.spec.ts (15, 32): Cannot find module '@angular2-material/core/async/promise-completer'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/grid-list/grid-list-errors.ts (1, 23): Cannot find module '@angular2-material/core/errors/error'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/grid-list/grid-list.ts (22, 19): Cannot find module '@angular2-material/core/rtl/dir'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/grid-list/grid-list.ts (23, 22): Cannot find module '@angular2-material/core/line/line'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/grid-list/grid-tile.ts (11, 38): Cannot find module '@angular2-material/core/line/line'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/icon/icon-registry.ts (3, 23): Cannot find module '@angular2-material/core/errors/error'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/icon/icon.ts (13, 23): Cannot find module '@angular2-material/core/errors/error'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/input/input.ts (23, 33): Cannot find module '@angular2-material/core/annotations/field-value'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/input/input.ts (24, 23): Cannot find module '@angular2-material/core/errors/error'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/list/list.ts (12, 38): Cannot find module '@angular2-material/core/line/line'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/radio/radio.spec.ts (18, 8): Cannot find module '@angular2-material/core/coordination/unique-selection-dispatcher'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/radio/radio.ts (23, 8): Cannot find module '@angular2-material/core/coordination/unique-selection-dispatcher'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/radio/radio.ts (29, 8): Cannot find module '@angular2-material/core/coordination/unique-selection-dispatcher'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/sidenav/sidenav.ts (15, 19): Cannot find module '@angular2-material/core/rtl/dir'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/sidenav/sidenav.ts (16, 32): Cannot find module '@angular2-material/core/async/promise-completer'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/sidenav/sidenav.ts (17, 23): Cannot find module '@angular2-material/core/errors/error'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/sidenav/sidenav.ts (18, 35): Cannot find module '@angular2-material/core/annotations/field-value'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/slide-toggle/slide-toggle.ts (15, 35): Cannot find module '@angular2-material/core/annotations/field-value'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/tabs/tab-content.ts (2, 39): Cannot find module '@angular2-material/core/portal/portal-directives'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/tabs/tab-label.ts (2, 39): Cannot find module '@angular2-material/core/portal/portal-directives'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/components/tabs/tabs.ts (4, 35): Cannot find module '@angular2-material/core/portal/portal-directives'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/core/overlay/position/connected-position-strategy.ts (4, 33): Cannot find module '@angular2-material/core/style/apply-transform'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/core/overlay/position/global-position-strategy.ts (1, 33): Cannot find module '@angular2-material/core/style/apply-transform'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/demo-app/demo-app.ts (4, 19): Cannot find module '@angular2-material/core/rtl/dir'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/demo-app/demo-app.ts (5, 24): Cannot find module '@angular2-material/button/button'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/demo-app/demo-app.ts (6, 37): Cannot find module '@angular2-material/sidenav/sidenav'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/demo-app/demo-app.ts (7, 34): Cannot find module '@angular2-material/list/list'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/demo-app/demo-app.ts (8, 22): Cannot find module '@angular2-material/icon/icon'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/demo-app/demo-app.ts (9, 25): Cannot find module '@angular2-material/toolbar/toolbar'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/grid-list/grid-list-demo.ts (2, 39): Cannot find module '@angular2-material/grid-list/grid-list'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/grid-list/grid-list-demo.ts (3, 24): Cannot find module '@angular2-material/button/button'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/grid-list/grid-list-demo.ts (4, 34): Cannot find module '@angular2-material/card/card'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/grid-list/grid-list-demo.ts (5, 38): Cannot find module '@angular2-material/icon/icon'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/icon/icon-demo.ts (2, 38): Cannot find module '@angular2-material/icon/icon'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/input/input-demo.ts (2, 35): Cannot find module '@angular2-material/input/input'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/input/input-demo.ts (3, 24): Cannot find module '@angular2-material/button/button'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/input/input-demo.ts (4, 22): Cannot find module '@angular2-material/card/card'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/input/input-demo.ts (5, 26): Cannot find module '@angular2-material/checkbox/checkbox'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/input/input-demo.ts (6, 22): Cannot find module '@angular2-material/icon/icon'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/input/input-demo.ts (7, 25): Cannot find module '@angular2-material/toolbar/toolbar'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/list/list-demo.ts (2, 24): Cannot find module '@angular2-material/button/button'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/list/list-demo.ts (3, 34): Cannot find module '@angular2-material/list/list'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/list/list-demo.ts (4, 22): Cannot find module '@angular2-material/icon/icon'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/live-announcer/live-announcer-demo.ts (2, 31): Cannot find module '@angular2-material/core/a11y/live-announcer'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/main.ts (8, 39): Cannot find module '@angular2-material/core/overlay/overlay'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/main.ts (9, 31): Cannot find module '@angular2-material/core/a11y/live-announcer'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/main.ts (10, 38): Cannot find module '@angular2-material/core/overlay/overlay-container'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/main.ts (11, 31): Cannot find module '@angular2-material/core/gestures/MdGestureConfig'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/main.ts (12, 30): Cannot find module '@angular2-material/icon/icon-registry'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/overlay/overlay-demo.ts (19, 8): Cannot find module '@angular2-material/core/core'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/overlay/overlay-demo.ts (50, 38): Parameter 'ref' implicitly has an 'any' type.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/overlay/overlay-demo.ts (65, 38): Parameter 'ref' implicitly has an 'any' type.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/overlay/overlay-demo.ts (81, 38): Parameter 'ref' implicitly has an 'any' type.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/portal/portal-demo.ts (7, 8): Cannot find module '@angular2-material/core/core'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/progress-bar/progress-bar-demo.ts (2, 24): Cannot find module '@angular2-material/button/button'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/progress-bar/progress-bar-demo.ts (3, 29): Cannot find module '@angular2-material/progress-bar/progress-bar'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/progress-circle/progress-circle-demo.ts (2, 24): Cannot find module '@angular2-material/button/button'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/progress-circle/progress-circle-demo.ts (3, 43): Cannot find module '@angular2-material/progress-circle/progress-circle'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/radio/radio-demo.ts (2, 43): Cannot find module '@angular2-material/radio/radio'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/radio/radio-demo.ts (5, 8): Cannot find module '@angular2-material/core/coordination/unique-selection-dispatcher'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/sidenav/sidenav-demo.ts (2, 24): Cannot find module '@angular2-material/button/button'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/sidenav/sidenav-demo.ts (3, 37): Cannot find module '@angular2-material/sidenav/sidenav'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/slide-toggle/slide-toggle-demo.ts (2, 29): Cannot find module '@angular2-material/slide-toggle/slide-toggle'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/tabs/tab-group-demo.ts (2, 34): Cannot find module '@angular2-material/tabs/tabs'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/tabs/tab-group-demo.ts (3, 25): Cannot find module '@angular2-material/toolbar/toolbar'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/tabs/tab-group-demo.ts (4, 23): Cannot find module '@angular2-material/input/input'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/toolbar/toolbar-demo.ts (2, 22): Cannot find module '@angular2-material/icon/icon'.
  /home/txgo/git/src/github.com/txgo/material2/tmp/broccoli_type_script_compiler-input_base_path-byFXPyBy.tmp/0/src/demo-app/toolbar/toolbar-demo.ts (3, 25): Cannot find module '@angular2-material/toolbar/toolbar'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/angular-cli/1.0.0-beta.2-mobile.4/angular-cli/lib/broccoli/broccoli-typescript.js:115:19)
    at BroccoliTypeScriptCompiler.build (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/angular-cli/1.0.0-beta.2-mobile.4/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/broccoli-caching-writer/2.2.1/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/rsvp/3.2.1/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/rsvp/3.2.1/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/rsvp/3.2.1/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/rsvp/3.2.1/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/broccoli-plugin/1.1.0/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/broccoli-caching-writer/2.2.1/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/angular-cli/1.0.0-beta.2-mobile.4/angular-cli/lib/broccoli/broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/angular-cli/1.0.0-beta.2-mobile.4/angular-cli/lib/broccoli/angular2-app.js:321:18)
    at Angular2App._buildTree (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/angular-cli/1.0.0-beta.2-mobile.4/angular-cli/lib/broccoli/angular2-app.js:116:23)
    at new Angular2App (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/angular-cli/1.0.0-beta.2-mobile.4/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at _buildAppTree (/home/txgo/git/src/github.com/txgo/material2/angular-cli-build.js:87:10)
    at module.exports (/home/txgo/git/src/github.com/txgo/material2/angular-cli-build.js:16:19)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/ember-cli/2.5.0/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/ember-cli/2.5.0/ember-cli/lib/models/builder.js:89:10)
    at new Class (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/core-object/0.0.2/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/ember-cli/2.5.0/ember-cli/lib/tasks/serve.js:15:19)
    at /home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/ember-cli/2.5.0/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/rsvp/3.2.1/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/rsvp/3.2.1/rsvp/dist/rsvp.js:1048:17)
    at /home/txgo/git/src/github.com/txgo/material2/node_modules/.npminstall/rsvp/3.2.1/rsvp/dist/rsvp.js:331:11

**Comment by dozingcat** [comment]
I had a similar error, and it worked again after deleting the node_modules and dist directories and rerunning npm install.

**Comment by jelbourn** [comment]
Sounds like there is something amiss with your environment. Typically deleting `node_modules/`, `dist/`, and `tmp/` clears it up.

**Comment by txgo** [comment]
May be it is not related to npm install. It is related to angular-cli-config.js. 

As we see in system-config,  src/core and src/components dirs are mapped to  @angular2-material .

but in angular-cli-config, It not works.

I can build material2 now with: 
1. ln -s ln -s src/components/card/ node_modules/@angular2-material/car and other similar dirs.
2. add a line to vendorNpmFiles: [ ..., '@angular2-material/**/*']

May be the mapping should be set in:
```
function _buildDemoAppInputTree() {
  return new MergeTree([
    new Funnel('typings', {
      destDir: 'typings'
    }),
    new Funnel('src', {
      include: ['components/**/*', 'core/**/*'],
      destDir: 'src/demo-app'
    }),
    new Funnel('src/demo-app', {
      destDir: 'src/demo-app'
    })
  ]);
}
```

But in my sitiation, it not works?

Thanks for any help.
