### ISSUE TITLE
md-tab-group: Can not hide md-tab-header

### ISSUE THREAD

**Issue by btxtiger** [angular/material2#6296]
#### Bug, feature request, or proposal:
**proposal:**
I'd like to hide the default tab header, because i use a custom tab navigation.
However the template ignores any added CSS.

#### What is the expected behavior?
Using the chrome debugger, you can figure out that CSS with
`md-tab-header { display: none; }`
should hide the whole header. 

#### What is the current behavior?
CSS is ignored, maybe it is straight overwritten. Using `!important` doesn't have any effect.

#### What are the steps to reproduce?
All changes in app.component.html
http://plnkr.co/edit/j9uHPAB4Olz8sOLa6lEY

#### What is the use-case or motivation for changing an existing behavior?
Allow to use tabs with a custom tab navigation

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/common": "^4.3.2",
"@angular/material": "^2.0.0-beta.8",
"typescript": "~2.4.2"
Tested on Chrome, Firefox, Safari

#### Is there anything else we should know?
-

**Comment by btxtiger** [comment]
I figured out that this behaviour might be caused by the use of **ng-deep**

**Comment by willshowell** [comment]
This is because of view encapsulation. If you don't wish to use `::ng-deep`, you can turn encapsulation off in your component or add the styles to your global stylesheet.

**Comment by jelbourn** [comment]
What @willshowell said
