### ISSUE TITLE
improve the document and add more examples?

### ISSUE THREAD

**Issue by mrdulin** [angular/material2#6312]
#### Bug, feature request, or proposal:

proposal

#### What is the expected behavior?

e.g `md-table`, improve the document about `DataBase` and `DataSource`.

Can I use `DataService` instead of `DataBase`?
Can I use Component class  `extends` the `abstract class DataSource` ? I don't want to create a new `DataSource` class.

#### What is the current behavior?

https://github.com/angular/material2/blob/master/src/material-examples/table-http/table-http-example.ts

1. I am confused why use `dataBase`(`ExampleHttpDao`) rather than a `DataService`?

2. And the `DataSource`, can I just return an Observable of `DataSerivce` within `ngOnInit` of 
 a Component?

like this: 

ts:
```ts
ngOnInit() {
   this.dataSource$ = this.someService.getAll();
}
```
html:
```html
<md-table [dataSource]='dataSource'>

</md-table>
```

#### What is the use-case or motivation for changing an existing behavior?

I am confused how to add I new item to the items of `md-table` dataSource. 
when I create a new item, how do I put this new item to the items of dataSource. And the `md-table` display the new item at the head?

I think below is easy to understand when I create a new data and add to my data list.
ts: 
```ts
ngOnInit() {
  this.someService.getAll().subscribe((datas) => {
    this.datas = datas;
  });
}

create() {
  this.someService.create().subscribe((data) => {
     this.datas.unshift(data);
  }) 
}
```

html:
```html
<md-table>
   <tr *ngFor='let data of datas'>
     //...
   </tr>
</md-table>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

`"@angular/core": "^4.3.3",`
`"@angular/material": "^2.0.0-beta.8",`

**Comment by willshowell** [comment]
> Can I use DataService instead of DataBase?
Can I use Component class extends the abstract class DataSource ? I don't want to create a new DataSource class.

 You can do whatever you want ;) all that *really* matters is making sure that the Observable returned by `connect()` emits whenever the view should reflect new data.

> I am confused why use dataBase(ExampleHttpDao) rather than a DataService?

It's just [an abstraction](https://en.wikipedia.org/wiki/Data_access_object) for the example. Keep in mind that these examples are made to be standalone. Your implementation may (/should) vary given your application structure and requirements.

> And the DataSource, can I just return an Observable of DataSerivce within ngOnInit of
a Component?

Nope. You need to bind to a `DataSource<T>` instance.

----

Check out the [examples directory](https://github.com/angular/material2/tree/master/src/material-examples); there are a couple more examples than what is currently published on the docs site. You may also be interested in https://github.com/angular/material2/issues/5889.

**Comment by ModarNa** [comment]
i was testing angular performance for slow internet clients and found that if you navigate to component A then fast click to B then again fast click to A --> the result is A title with B contents

**Comment by mrdulin** [comment]
@willshowell Thanks for reply. #5889 is a good idea.  Maybe should just keep simple, like this:

```ts
<md-table>
  <thead>
    <tr></tr>
  </thead>
  <tbody>
    <tr *ngFor='let row of rows'>
      <td></td>
      ..
    </tr>
  </tbody>
  <tfoot>
  </tfoot>
</md-table>
```

**Comment by jelbourn** [comment]
Closing this since it seems more like a question / support request than a bug report.
