### ISSUE TITLE
md-checkbox not working when used with mdSuffix and text is selected in input

### ISSUE THREAD

**Issue by toxik** [angular/material2#6322]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The checkbox should select and deslect when clicked

#### What is the current behavior?
The checkbox has an inconsitent state, most of the time resetting to the previous value

#### What are the steps to reproduce?
Open https://plnkr.co/edit/RMcOcdXapnkfOCo0ls1Z?p=preview
Click on the checkbox, it will not change its state correctly

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

**Comment by josephperrott** [comment]
It looks like this is working as expected now as seen [here](https://plnkr.co/edit/9GUN8rCO55I6nvZHfndX?p=preview).
