### ISSUE TITLE
[autocomplete] indent with custom input

### ISSUE THREAD

**Issue by Nodarii** [angular/material2#6325]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/1251685/29035451-50b109f0-7ba4-11e7-82f0-b37b8184de7e.png)

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/1251685/29035423-37b977e8-7ba4-11e7-9b50-bbf67585981a.png)

#### What are the steps to reproduce?
https://plnkr.co/edit/56vpmVnxGbEBBIFO8Ung?p=preview

#### What is the use-case or motivation for changing an existing behavior?
The motivation is to decouple autocomplete from mdInput and allow users to use in more flexible way
![image](https://user-images.githubusercontent.com/1251685/29035561-b18c99ce-7ba4-11e7-869c-bd53b7720787.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cli: 1.2.6
node: 8.2.1
os: win32 x64
@angular/animations: 5.0.0-beta.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 5.0.0-beta.1
@angular/compiler: 5.0.0-beta.1
@angular/core: 5.0.0-beta.1
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 5.0.0-beta.1
@angular/http: 5.0.0-beta.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 5.0.0-beta.1
@angular/platform-browser-dynamic: 5.0.0-beta.1
@angular/platform-server: 5.0.0-beta.1
@angular/router: 5.0.0-beta.1
@angular/cli: 1.2.6
@angular/compiler-cli: 5.0.0-beta.1

**Comment by willshowell** [comment]
https://github.com/angular/material2/pull/6282 should fix this

**Comment by Nodarii** [comment]
@willshowell , nice! 
Closing issue then
