### ISSUE TITLE
Datepicker placeholder doesn't move when date set by FormGroup.setValue

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/material2#6334]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Placeholder should move when FormGroup.setValue sets a value on a previously blank date. 

#### What is the current behavior?
The placeholder doesn't move

#### What are the steps to reproduce?
http://plnkr.co/edit/kaS3PvvuSmn0leykKy2D?p=preview
Click "Set Today" without focusing the date field

#### What is the use-case or motivation for changing an existing behavior?
Placeholder incorrectly overlaps the date value

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
beta-8

#### Is there anything else we should know?
I noticed this when creating the above plunker for another issue.  I didn't check if any other ways of setting the value cause  the same issue.

**Comment by mmalerba** [comment]
appears to be fixed now (updated plunker: http://plnkr.co/edit/WWGvQ0MEK2BfVVNgw2Q9?p=info)
