### ISSUE TITLE
Expose mdRipple instance in MdButton components

### ISSUE THREAD

**Issue by rockmacaca** [angular/material2#6340]
#### Bug, feature request, or proposal:
feature request: Developers should have a way to programmatically trigger md-button ripples.

#### What is the current behavior?
To the best of my knowledge, Angular doesn't provide any way to access directive instances on on descendants of components declared in a template. The closest I can get to accessing the ripple is by getting a reference to the `MdButton` instance.

#### What is the use-case or motivation for changing an existing behavior?
I'm making a carousel-type component that allows using the keyboard arrow keys to navigate. As a nice touch of visual feedback, I'd like to trigger a ripple on the buttons on keydown. 

Here I've monkeypatched `MdButton` to demonstrate what I want:
https://embed.plnkr.co/rpfqsqCblKF3odzD8DVx/

It's also useful if I want to implement a basic version of the feature discovery pattern:
https://material.io/guidelines/growth-communications/feature-discovery.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

#### Is there anything else we should know?
It might be useful to expose this on other components that implement ripples. It should be as simple as adding a `ViewChild` and documenting its existence as a component property.

**Comment by DevVersion** [comment]
Thanks for the issue. We already have a similar issue: #4179

It would be great if you add your feedback/problem there as well!
