### ISSUE TITLE
Md-data-table select row

### ISSUE THREAD

**Issue by Leonzen** [angular/material2#6342]
#### Bug, feature request, or proposal:
Feature request, proposal

#### What is the expected behavior?
There should be a data-table with a checkbox on one side, whitch allows the user to select a row an work with the data in it.

#### What is the current behavior?
There is no such table. 

#### What is the use-case or motivation for changing an existing behavior?
This could be a usefull feature for many applications

**Comment by nkwood** [comment]
https://github.com/angular/material2/blob/master/src/material-examples/table-overview/table-overview-example.html#L20

https://github.com/angular/material2/tree/master/src/lib/core/selection

**Comment by andrewseguin** [comment]
Selection is fairly straightforward to add with SelectionModel and having a select column. For a table that provides this along with built-in support for sorting and pagination, see #5889
