### ISSUE TITLE
Md-datepicker touchUi is always treated as if touchUi is set to true

### ISSUE THREAD

**Issue by riankol** [angular/material2#6344]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
when touchUi="true" the md-datepicker will be opened in touchscreen mode, but when touchUi="false", md-datepicker will be opened as a popup under the input

#### What is the current behavior?
even when touchUi="false" md-datepicker opens in touchscreen mode

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/XcGBezjJ27qYTRdvQt0v?p=preview (I changed an existing plunker with md-datepicker I found and added the touchUi="false".)

#### What is the use-case or motivation for changing an existing behavior?
I want to be able use a boolean 'showInTouchMode' like this: [touchUi]="showInTouchMode".

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I use in my package.json among others:
        "@angular/common": "4.3.1",
        "@angular/cdk": "2.0.0-beta.8",
        "@angular/material": "2.0.0-beta.8",
        "typescript": "2.4.1"

#### Is there anything else we should know?
Not about this point, but I would really appreciate more examples in the documentation at material.angular.io. How exactly should I customize md-datepicker with the parse and display formats? And How exactly should I localize labels and messages? For example, how should a 'MY_DATE_FORMATS' file look?

**Comment by willshowell** [comment]
[Remember the brackets](https://angular.io/guide/template-syntax#remember-the-brackets)

**Comment by rafaelss95** [comment]
@willshowell  Although you're correct, I'm just curious as why only this specific `@Input` doesn't have a getter and setter (calling coerceBooleanProperty).

**Comment by riankol** [comment]
Thanks! It works indeed with the brackets!

**Comment by willshowell** [comment]
@rafaelss95 Fair question - maybe raise a separate issue about that be included in a library-wide audit? IMO `coerceBooleanProperty` teaches bad habits, but I'm sure there is a valid reason behind it
