### ISSUE TITLE
Using the directives and providers globally

### ISSUE THREAD

**Issue by gelidus** [angular/material2#635]
Just wondering, if there is a way to include the angular material 2 directives and provides within a whole project, instead of including them in each component. Also, would this be a correct approach?

**Comment by gelidus** [comment]
Ended up using this approach:

```ts
bootstrap(AppComponent, [
  provide(PLATFORM_DIRECTIVES, {
    useValue: [
      MdToolbar, MdButton, MD_SIDENAV_DIRECTIVES,
      MD_LIST_DIRECTIVES, MD_CARD_DIRECTIVES, MdInput,
      MdCheckbox, MdRadioButton, MdRadioGroup,
      MdIcon
    ], multi: true
  }),
  MdIconRegistry
]);
```

Is this correct? :)

**Comment by jelbourn** [comment]
@gelidus Please only file github issues for bugs / feature requests and direct questions to the mailing list or gitter.
