### ISSUE TITLE
mdInput underline animation looks wrong in edge browser

### ISSUE THREAD

**Issue by wuchtig** [angular/material2#6351]
#### Bug, feature request, or proposal:

mdInput underline animation looks wrong in edge browser

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

http://plnkr.co/edit/ViorG3CEaBWikCVI4bqJ?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Animation should work as in Chrome

**Comment by mmalerba** [comment]
@DevVersion is this related to the `transform:perspective(1px)` thing?

**Comment by wuchtig** [comment]
[#8480](https://github.com/angular/material2/pull/8480) was a big step forward and the jumping is vanish. In Edge-Browser the underline ist still blurry at animation start. 

If you could add `translateZ(0)` to the `.mat-form-field-underline` it would be perfect.

```
.mat-form-field-underline { 
  transform: translateZ(0) scaleX(0.5);
}
```
