### ISSUE TITLE
[Paginator] Docs need to be more fleshed out

### ISSUE THREAD

**Issue by HarelM** [angular/material2#6357]
Pagination documentation is extremely shallow - IMO, the minimal example should contain data that can be paginated... 
https://material.angular.io/components/paginator/overview
A more advanced scenario is the case where there are two paginators in the same page for two different collections.

**Comment by willshowell** [comment]
Maybe something like this? (or a reactive version of it)

https://plnkr.co/edit/96KtAEhRo8b9iBFYayYq?p=preview

I don't know if I see the point of adding two in the same component, though. It's not really any more complex, just more code.

**Comment by GregKass** [comment]
The use case I'm trying to solve is a top and bottom paginator for the same table. Have any pointers on how to do that?

**Comment by andrewseguin** [comment]
Not sure there is any actionable item on this issue except to put an example of two paginators, but that seems pretty specific to put into docs and probably not very helpful.
