### ISSUE TITLE
Does paginator support i18n?

### ISSUE THREAD

**Issue by mrdulin** [angular/material2#6364]
#### Bug, feature request, or proposal:

feature request

#### What is the expected behavior?

The paginator display `Items per page`, it's English.

#### What is the current behavior?

Can I set this text with other languages?

#### What is the use-case or motivation for changing an existing behavior?

i18n

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

`"@angular/core": "^4.3.3",`
`"@angular/material": "^2.0.0-beta.8",`

**Comment by crisbeto** [comment]
The labels can be overwritten using the `MdPaginatorIntl`. [Docs for reference.](https://material.angular.io/components/paginator/overview)

**Comment by mrdulin** [comment]
@crisbeto Thanks. My fault. I will check the doc carefully.

**Comment by willshowell** [comment]
@mrdulin https://github.com/angular/material2/issues/5902 is tracking additional documentation for this. You can still replace the "of" but it does require rewriting `getRangeLabel`

**Comment by mrdulin** [comment]
@willshowell well. How can I do that? `MdPaginatorIntl` is not be exposed by `@angular/material`;

**Comment by willshowell** [comment]
It was missed as an export in the last release. You'll have to use the master builds or wait for the next release. See https://github.com/angular/material2/issues/5902#issuecomment-316717006

**Comment by mrdulin** [comment]
@willshowell ok. thanks.  I am waiting for the next release.  You know, the paginator view update is another issue I metioned.  #6220 . Can you tell me probably when is the next release？

**Comment by willshowell** [comment]
@mrdulin I wish I knew 😞 probably when the new stepper and sticky-header components are ready, but I'm just speculating.
