### ISSUE TITLE
Plunkr Template Not Loading

### ISSUE THREAD

**Issue by paistipoikka** [angular/material2#6365]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

It runs

#### What is the current behavior?

It doesn't run. Throws 404s. 

#### What are the steps to reproduce?

Simply open the plnkr template below and hit *run*. 

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?

Makes it easier to create new plnks when submitting issues.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Osx
Chrome

**Comment by grizzm0** [comment]
It's due to #6039

The following
```
    '@angular/cdk/keyboard': 'https://rawgit.com/angular/cdk-builds/master/bundles/cdk-keyboard.umd.js',
    '@angular/cdk/observe-content': 'https://rawgit.com/angular/cdk-builds/master/bundles/cdk-observe-content.umd.js',
```
needs to be replaced with
```
    '@angular/cdk/keycodes': 'https://rawgit.com/angular/cdk-builds/master/bundles/cdk-keycodes.umd.js',    
    '@angular/cdk/observers': 'https://rawgit.com/angular/cdk-builds/master/bundles/cdk-observers.umd.js',
```

**Comment by grizzm0** [comment]
ping @DevVersion

**Comment by DevVersion** [comment]
Fixed. Thanks
