### ISSUE TITLE
md-datepicker, should add CSS class to overlay refs for easy targeting of styles

### ISSUE THREAD

**Issue by jt-helsinki** [angular/material2#6367]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

All dates and text inside the touch UI date picker modal fits nicely inside the modal. 

#### What is the current behavior?

Text is currently overflowing. This happens when using iPhone 5.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Iphone 5
Safari

Also chrome in "phone simulation mode".

**Comment by mmalerba** [comment]
Can you provide an example to reproduce? It seems to work fine with the "Datepicker Touch" example on the docs site, even when I put chrome in iPhone5 simulation mode: https://material.angular.io/components/datepicker/overview

**Comment by raceloop** [comment]
Here are a couple of screenshots. 

Material 2.0.0-beta.8

![screen shot 2017-09-06 at 7 53 25](https://user-images.githubusercontent.com/20871336/30095026-94abb39e-92d8-11e7-9cf9-b03abee36aeb.png)

![screen shot 2017-09-06 at 7 54 49](https://user-images.githubusercontent.com/20871336/30095052-b410ffe6-92d8-11e7-9047-dfe480473c58.png)

**Comment by mmalerba** [comment]
Maybe you have some CSS on the page thats interfering with it. It appears to be fine on the material demo site:
![datepicker](https://user-images.githubusercontent.com/14793288/30123399-b8456f76-92e6-11e7-8aa0-3c5645404e66.png)

**Comment by raceloop** [comment]
ok, will check css AND upgrade to latest material. that might fix it.

**Comment by raceloop** [comment]
So it turns out that I do have a style inside the css which conflicts.

```
.mat-dialog-container {
       padding: 0px !important;
}
```

Unfortunately I need this so my dialogs have a zero margin for toolbars etc. I think this issue may be relevant:

[https://github.com/angular/material2/issues/5537](https://github.com/angular/material2/issues/5537)

**Comment by mmalerba** [comment]
I recommend using the panelClass option for dialog to add a special class that you can target, only on dialogs that have the toolbar. e.g.:

```css
.toolbar-dialog .mat-dialog-container {
  padding: 0 !important;
}
```

It would probably be worth adding classes to the datepicker to make it easier for people to target styles specifically at it, I'll leave this issue open to track that
