### ISSUE TITLE
MD-Slider No Color

### ISSUE THREAD

**Issue by robertwijntjes** [angular/material2#6368]
#### Bug, feature request, or proposal:
How come the Documentation says color is an attribute but then it doesn't work?

#### What is the expected behavior?
Color for md-slider

#### What is the current behavior?
no color

#### What are the steps to reproduce?
https://gyazo.com/04299ef0cb5f04dfff86d43d6c346b87?token=5cdd0bca560fd489b839c882585e2dd0

#### What is the use-case or motivation for changing an existing behavior?
Seems like a Significant addition

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
No Browsers Affected.

#### Is there anything else we should know?
Nope

**Comment by donroyco** [comment]
Please add a Plunker to reproduce the issue that you encountered. It works for me: https://plnkr.co/edit/28EA5fyZVwKzsSo4WahL?p=preview
