### ISSUE TITLE
[audit] use of coerceBooleanProperty

### ISSUE THREAD

**Issue by willshowell** [angular/material2#6370]
#### Bug, feature request, or proposal:
Suggesting library-wide audit

#### Expected
Consistent use

#### Currently
At least two boolean inputs ([1](https://github.com/angular/material2/blob/master/src/lib/datepicker/datepicker.ts#L143) [2](https://github.com/angular/material2/blob/master/src/lib/expansion/accordion-item.ts#L42)) do not use it

#### Motivation

https://github.com/angular/material2/issues/6344#issuecomment-320955604, https://github.com/angular/material2/issues/6097#issuecomment-319083700

#### Is there anything else we should know?

IMO it should be removed entirely as it encourages misuse of bindings that won't translate outside this library. For reference, the original commit used it in the form of [`@BooleanFieldValue()`](https://github.com/angular/material2/pull/161/files#diff-6ef16658b3712f44bd8299cc8b9c9584).

**Comment by jelbourn** [comment]
We should use it consistently everywhere. It's necessary at the very least to make things like `disabled`, `readonly`, `required`, and `checked` work correctly. 

My long-term goal is to convince core to do https://github.com/angular/angular/issues/8968
