### ISSUE TITLE
[audit] overlay extra classes 

### ISSUE THREAD

**Issue by willshowell** [angular/material2#6372]
#### Bug, feature request, or proposal:
Suggesting library-wide audit

#### Currently

Overlay components all accept extra classes differently:

* Dialog: `string | string[]`
* Snackbar: `string[]`
* Tooltip: `NgClass`
* Select: `NgClass`
* Menus: `class` only
* Datepicker: none
* Autocomplete: none (tracking https://github.com/angular/material2/pull/6618 or https://github.com/angular/material2/pull/7176)

#### Ideally

Consistent NgClass compatibility would be awesome. If not possible, `string | string[]` support would be good.

Additionally, consistent naming would be nice. Snackbar uses `extraClasses`, whereas select uses `panelClass`. Also, select and dialog both use `panelClass`, but the class is added to different elements.

**Comment by jelbourn** [comment]
Agreed, they should all be consistent. I would want to use `panelClass` everywhere

**Comment by amcdnl** [comment]
@jelbourn - So to clarify, update all the inputs to `panelClass` with `NgClass` as the interface? Do we need to deprecate as well?

**Comment by jelbourn** [comment]
The template-based components can have `NgClass` mechanics, but dialog.snack-bar would just stay as strings because there's no binding context

**Comment by jelbourn** [comment]
Also this would be a good candidate for a mixin

**Comment by amcdnl** [comment]
@jelbourn -

1) I played around with a mixin but the implementations varied so much, it was tricky. I ended up making a utility parser instead.
2) Do you want me to rename `matTooltipClass` to `matPanelClass` or just leave it for that one?

**Comment by jelbourn** [comment]
Tooltip can stay as `matTooltipClass`

**Comment by jelbourn** [comment]
If you make a PR it's easier to leave comments; you can mark it as WIP

**Comment by jelbourn** [comment]
One thing I will say is that we don't want to add additional cdk packages for utility methods; each one is a public API that a user would potentially need to know about (such as when adding to a systemjs config)

**Comment by josh18** [comment]
Would it make sense (maybe in another issue / PR) to add a similar input for the `.cdk-overlay-container` element?
