### ISSUE TITLE
md-select long placeholder text wraps and covers drop down value

### ISSUE THREAD

**Issue by galtalmor** [angular/material2#6373]
#### Bug, feature request, or proposal:
Bug: Long placeholder text drops and covers selected value

#### What is the expected behavior?
Long placeholder text should have overflow ellipsis and nowrap so it doesn't look weird.

#### What is the current behavior?
Long placeholder text drops and covers selected value

#### What are the steps to reproduce?
Create a md-select with placeholder text that is longer than 1 line according to select width

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
[Example](http://plnkr.co/edit/PXeNWkFX8weMC9tOnJCD)

#### What is the use-case or motivation for changing an existing behavior?
It is a bug and an inconsistent behavior with other components (e.g. md-input)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.2
Material 2.0.0-beta.8
TypeScript 2.4.2
Windows 10
Chrome 60

#### Is there anything else we should know?
Simple fix should be adding the following CSS:
```
    .mat-select-placeholder {
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
    }
```
Workaround for now, add the above with `/deep/` prefix for the selector.

**Comment by crisbeto** [comment]
Closing as something that should be fixed in master after the switch to `mat-form-field`.
