### ISSUE TITLE
[sidenav] can't close until opening animation is complete

### ISSUE THREAD

**Issue by willshowell** [angular/material2#6376]
#### Bug, feature request, or proposal:
Regression

#### Expected
Sidenav can still be closed while animating open

#### Current
Sidenav must wait until animation is complete to trigger new actions

#### Reproduction

*Working with beta.8:* https://plnkr.co/edit/Ucv13OC4Zsl55CXRANK3?p=preview
*Failing with latest:* https://plnkr.co/edit/pCWLJ2ThQrKgGXI2Q9cn?p=preview

#### Other
Presumably due to https://github.com/angular/material2/pull/4959 or https://github.com/angular/material2/pull/6189

**Comment by mmalerba** [comment]
@crisbeto seems like this may have been a regression from one of your PRs

**Comment by crisbeto** [comment]
It was an intentional change (there's an internal `_isAnimating` flag that is checked). I did it primarily to ensure that you always get back the correct animation promise and to guard against it cases like https://github.com/angular/material2/issues/5743 and https://github.com/angular/material2/issues/4932.

**Comment by willshowell** [comment]
@crisbeto are you aware of any open issues in core for #5743 and #4932? If I understand correctly, the current behavior is necessary until those are sorted out?

Further, could you explain this note?
https://github.com/angular/material2/blob/70bd5fc20e7fe6b1749b334d29e842cb3681609d/src/lib/sidenav/drawer.ts#L252-L254

Is that to say that the promise return value will become obsolete, but is there to match the before-animations behavior?

**Comment by crisbeto** [comment]
Yes, the previous approach was passing promises around to coordinate the animation, but I removed all of them in #4959 since they weren't necessary anymore. The ones for `toggle`, `open` and `close` were left in since they were a part of the public API.

**Comment by crisbeto** [comment]
Got some time to look into this. It seems like #5743 isn't an issue for the sidenav. I'll remove the `_isAnimating` guards.
