### ISSUE TITLE
Checkbox not firing change event when dynamically set with checked

### ISSUE THREAD

**Issue by alexw10** [angular/material2#6378]
#### Bug, feature request, or proposal:
I am unsure if this is maybe me just using this wrong or if this is a bug in the code.
What I have is a checkbox that when checked will select a group of checkboxes with the [checked] property I am finding that the checkbox change event does not get emitted when doing this.

#### What is the expected behavior?
I feel like whenever the checkbox changes it should fire the change event even if done dynamically.

#### What is the current behavior?
Does not fire the change vent when checked is set to true/false dynamically.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

Here is a plunkr describing the behavior I am seeing:
http://plnkr.co/edit/RvWwx2u0NrmkKJFgqDTa?p=preview

If you check the bottom checkbox you will not see the "change event fired!" in the console appear.
I would expect this to appear 3 times.
But when you click the top checkboxes you will see the "change event fired!" message in the console.

#### What is the use-case or motivation for changing an existing behavior?
My main motivation for this is an easy way to select/deselect all checkboxes.
If this can be done a different way would love to hear that as well.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Whatever is in the pkunkr, chrome.

**Comment by leocaseiro** [comment]
Hi @alexw10,

I believe this is not an angular material2 issue. It would be with angular itself. You could test with a native `<input [type]="checkbox">` and it wouldn't behave the way you're expecting.

The event change is only called on click. 

However, if you'd like to listen for that change, you couls use ReactiveForms. An easy way is setting a FormControl and listen for its valueChanges which is an observable.

```html
<input [formControl]="myCheckbox" type="checkbox" (change)="onChange()" [(ngModel)]="selectAll" />
    <md-checkbox [formControl]="myCheckbox" (change)="onChange()"></md-checkbox>
```

```typescript
import { FormControl } from '@angular/forms';

myCheckbox: FormControl = new FormControl();

ngOnInit() {
      this.myCheckbox.valueChanges.subscribe(value=> {
            console.log('my chebox has changed', value);
    })
}
```

Here's an updated version of your plunker http://plnkr.co/edit/UtzuV1AmQWECgKjJIQiR?p=preview

**Comment by jelbourn** [comment]
This is working as intended. All native form controls only emit `change` events due to user interaction (not programmatic change). The Angular Material components follow this behavior.

**Comment by babusurendra** [comment]
@leocaseiro  look like your plunker is not working, and I am not able to achieve this with reactive forms as you mentioned above.
can you please check once.

**Comment by kairos11** [comment]
Experience the said issue. But was not able to resolve. 
@babusurendra  is correct. Your plunker is not working. Can you please re-check. Thanks
