### ISSUE TITLE
md-checkbox: ngModel binding is not a boolean

### ISSUE THREAD

**Issue by dozingcat** [angular/material2#638]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If an md-checkbox has a [(ngModel)] binding, it should be set to true when checked and false when unchecked. (At least, that's how it was behaving a week or so ago, and what README.md implies).

#### What is the current behavior?
When checked or unchecked, the [(ngModel)] binding is set to an MdCheckboxChange object with a "checked" property of true or false. This breaks anything that expects the binding to be a boolean value.

#### What are the steps to reproduce?
Go to https://material2-test.firebaseapp.com/checkbox (or http://localhost:4200/checkbox if running the demo app locally). Click the first checkbox to foobar the bazquux. The text at the end of the line will show "Yes" as expected. Uncheck the checkbox and it will still show "Yes" instead of switching to "No". This appears to be because the text value is determined by the printResult() method in checkbox-demo.ts, which is looking at the isChecked instance variable in the [(ngModel)] binding, and that variable is receiving an object which is always truthy.

**Comment by bek0s** [comment]
I have the same problem. Because of that I have replaced my check boxes with slide-toggles for now :|

**Comment by sendilkumarn** [comment]
#575  Duplicate added that there too

**Comment by jelbourn** [comment]
@hansl is actually fixing this in #642

**Comment by hansl** [comment]
Fixed by #642, but apparently github ain't smart enough to figure out the "Fixed" line.
