### ISSUE TITLE
md-table is not working in lazy loaded modules

### ISSUE THREAD

**Issue by stejokrishna** [angular/material2#6381]
#### Bug, feature request, or proposal:
Bug, md-table is not working in lazy loaded module components
Message: 'Can't bind to 'dataSource' since it isn't a known property of 'md-table''

#### What is the expected behavior?
In lazy module if I imported 'CdkTableModule', md-table should work.

> Sample lazy Module @NgModule({
    imports: [
        CdkTableModule,
        TestTableRoutingModule
    ],
    declarations: [
        ShowTableComponent
    ]
})
export class TestTableModule {
}

If 'ShowTableComponent' has md-table it should because I am importing 'CdkTableModule' module

#### What is the current behavior?
If i try to access lazy loaded component using URL, its showing below error
![mad-table-error](https://user-images.githubusercontent.com/7432941/29140899-cb1751c4-7d69-11e7-8fdd-662741b9d753.png)
NOTE: I tried md-table in app.component without using lazy modules it worked fine.

#### What are the steps to reproduce?

- Create a module
- declare a component in newly created component
- load from app module using routes
- when url provided to load component, you will get above error

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
OS: Windows 10
Angular: 4.3.3
Angular-Material, Angular-CDK: 2.0.0-beta.8
Angular-cli: 1.1.1
Node: 8.1.2
NPM: 5.03
Browser: Chrome

**Comment by andrewseguin** [comment]
Can you try including `MdTableModule` in your module since you are using `md-table`?

**Comment by jonsamwell** [comment]
I don't get this error for md-tables in lazy load modules.  However, the MdTableModule is loaded in eager load modules, not just the lazy loaded modules.  Try importing the MdTableModule as @andrewseguin suggests.

**Comment by stejokrishna** [comment]
Thanks for suggestion @andrewseguin, @jonsamwell  .
importing MdTableModule worked. 
Just for information need to import MdSortModule for sorting on table to work

**Comment by HardChavda** [comment]
Hello everyone,
I have Same problem.
I have included MdTableModule but it is still giving me error as "Can't bind to 'dataSource' since it isn't a known property of 'md-table'."
Below are my dependencies:
 "dependencies": {
    "@angular/animations": "^4.3.4",
    "@angular/cdk": "git+https://github.com/angular/cdk-builds.git",
    "@angular/common": "^4.3.4",
    "@angular/compiler": "^4.3.4",
    "@angular/core": "^4.3.4",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^4.3.4",
    "@angular/http": "^4.3.4",
    "@angular/material": "git+https://github.com/angular/material2-builds.git",
    "@angular/platform-browser": "^4.3.4",
    "@angular/platform-browser-dynamic": "^4.3.4",
    "@angular/router": "^4.3.4",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.30",
    "@ngx-translate/core": "^7.1.0",
    "bootstrap": "4.0.0-alpha.6",
    "core-js": "^2.5.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.4",
    "ng2-md-datatable": "^1.4.0",
    "rxjs": "^5.4.3",
    "zone.js": "^0.8.16"
  },

In one component it is working fine,but in new component it is not working.

**Comment by gs-dchakraborty** [comment]
Hello Everyone,
Even I am having the same problem. I have included MdTableModule & CdkTableModule but it is still giving me error as "Can't bind to 'dataSource' since it isn't a known property of 'md-table'."
"dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.10",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@ngrx/effects": "^4.0.5",
    "@ngrx/store": "^4.0.3",
    "@ngrx/store-devtools": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  }

**Comment by jonsamwell** [comment]
@gs-dchakraborty You have listed you your package.json dependencies but are you importing the required md-modules in into your module?  The data table is working fine in my lazy load modules,

As a minimum, I would import the below into the lazy load module.  Note that I am using Angular 4.3.6

```
import { CommonModule } from "@angular/common";
import { NgModule } from "@angular/core";
import {
  MdButtonModule, MdCardModule,
  MdCheckboxModule, MdChipsModule, MdDatepickerModule,
  MdDialogModule, MdIconModule,
  MdInputModule, MdMenuModule, MdNativeDateModule,
  MdPaginatorModule, MdProgressBarModule, MdRadioModule, MdSelectModule,
  MdSidenavModule, MdSlideToggleModule, MdSnackBarModule, MdSortModule, MdTableModule,
  MdTabsModule, MdToolbarModule, MdTooltipModule
} from "@angular/material";

@NgModule({
  exports: [
    CommonModule,
    MdTableModule,
    MdIconModule,
    MdSortModule,
    MdPaginatorModule
  ],
  imports: [
    CommonModule,
    MdTableModule,
    MdIconModule,
    MdSortModule,
    MdPaginatorModule
  ]
})
export class AngularMaterialImportModule { }

```
