### ISSUE TITLE
Provide extended Example for Table (Sort+Filter+Paginate)

### ISSUE THREAD

**Issue by Renader** [angular/material2#6392]
#### Bug, feature request, or proposal:
-> **Proposal**

#### What is the current behavior?
There are 3 examples for Sort, Filter and Paginating the table as Plunkers. Also there is a [demo](https://github.com/angular/material2/blob/master/src/demo-app/table/table-demo.ts) that provides a combined sort and pagination example. But there is no example that applies sorting, filtering and paginating to a table.

#### What is the use-case or motivation for changing an existing behavior?

Since this is a very common use case, and especially since the table has an API that might be hard to understand for RxJS beginners there should be an example combing all, **and more important applies the common best practices** (like reset the current page in paginator if the user filters - which is a common challenge https://github.com/angular/material2/issues/5812, update the length in paginator on filter etc) 

**What I've done so far:**
https://plnkr.co/edit/ABhRra9nNaBiu4vmAizX?p=preview

- Sort
- Filter
- Paginate
- proper disconnect cleanup
- update paginators length on filter
- jump to page 1 (0) on filtering

**Comment by fad250** [comment]
They have already have it in this issue [#5848](https://github.com/angular/material2/issues/5848). The extended table example is in [plnkr](https://plnkr.co/edit/ABhRra9nNaBiu4vmAizX?p=preview).

**Comment by Renader** [comment]
@fad250 thank you for the link. I've missed it. 

But you linked my plnkr, in think you wanted to link [this extended example](https://plnkr.co/edit/EU3BBlViWpPf2NJW4PXx?p=preview).


Therefore this issue can be considered invalid.
