### ISSUE TITLE
Add more space between validation message and the label of the next field

### ISSUE THREAD

**Issue by richardsengers** [angular/material2#6395]
#### Bug, feature request, or proposal:
Bug / feature request

#### What is the expected behavior?
More space to validation message and next field label

#### What is the current behavior?
Validation message and next field label are too close to each other

#### What are the steps to reproduce?

https://embed.plnkr.co/Vbt29I0lCmhJtaBZNK8e/

#### What is the use-case or motivation for changing an existing behavior?
Better UI

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angualr latest, Material latest, Windows 10, Typescript 2.3.3

#### Is there anything else we should know?
I'm not quite sure if this is something we as a developer need too change to our preferences or that it should be standardized within Angular Material.
The current standard is pretty ugly as you can see in the screenshot below, shouldn't there be more space between the label and the error message?
![validation](https://user-images.githubusercontent.com/810038/29164099-b7ba14d6-7dbe-11e7-8a48-bc2eb72343de.PNG)

**Comment by richardsengers** [comment]
This is also happening when using hints
![hint](https://user-images.githubusercontent.com/810038/29165909-bb4e84fa-7dc4-11e7-9d05-8b479274c3f8.PNG)

**Comment by donroyco** [comment]
See #2124

**Comment by richardsengers** [comment]
Oh I'm very sorry...I've tried to search all the issues but missed that one. Closing this in favor of #2124
