### ISSUE TITLE
Wrong position of a MdMenu on a fixed button on mobile devices

### ISSUE THREAD

**Issue by seopei** [angular/material2#6396]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
the menu should be completely visible

#### What is the current behavior?
the menu position is wrong, the menu is not completely visible

#### What are the steps to reproduce?
the bug only appears on mobile devices
```
<style type="text/css">
    .my-button {
      display: inline-block;
      position: fixed;
      bottom: 20px;
      right: 20px;
      z-index: 2;
    }
  </style>
  
  <md-menu #createMenu="mdMenu" y-position="above" x-position="before">
    <button *ngFor="let a of [1,2,3]" md-menu-item>
      {{ 'Button ' + a }}
    </button>
  </md-menu>
  <button class="my-button" md-fab [mdMenuTriggerFor]="createMenu" color="primary">+</button>
```

#### What is the use-case or motivation for changing an existing behavior?
the user wants to see the full menu

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.3.2, angular material 2.0.0-beta.8, typescript 2.4.2, mobile safari, mobile chrome

#### Is there anything else we should know?
![screenshot_20170810-120035](https://user-images.githubusercontent.com/22980478/29165646-b8d6a9a6-7dc3-11e7-9a4c-047202f9a3c8.png)
![image uploaded from ios](https://user-images.githubusercontent.com/22980478/29165647-b90abe12-7dc3-11e7-954f-7557e3b4922f.jpg)

**Comment by josephperrott** [comment]
Closing as this is tracking in #6534
