### ISSUE TITLE
Scope of @angular/cdk: will overlays be added? a11y?

### ISSUE THREAD

**Issue by dherges** [angular/material2#6397]
#### Bug, feature request, or proposal:

Proposal / Question

#### What is the expected behavior?

What is the scope of the cdk?

#### What is the current behavior?

CDK works fine!

My question is: what is the scope of the CDK?

In special: will the [overlays from core](https://github.com/angular/material2/tree/master/src/lib/core/overlay) be added to the CDK?

Also on a11y: there seems to be some overlap between [core a11y](https://github.com/angular/material2/tree/master/src/lib/core/a11y) and [cdk a11y](https://github.com/angular/material2/tree/master/src/cdk/a11y)

#### What is the use-case or motivation for changing an existing behavior?

I am asking because some of the features in core seem so generic that they can be shared and re-used through CDK.

**Comment by jelbourn** [comment]
See #6100
