### ISSUE TITLE
[Proposal] How to print content of all md-tabs to paper

### ISSUE THREAD

**Issue by thorstenKoch** [angular/material2#6399]
#### Bug, feature request, or proposal:
PROPOSAL

#### What is the expected behavior?
I want to display the content of all md-tabs one below the other, that i can print out all content in tabs to paper. 
Please do not hit me, i do not want to print out the internet... but perhaps customers want to print out product information

#### What is the current behavior?
Only the content of the active tab is shown.

#### What are the steps to reproduce?

Go to https://material.angular.io/components/tabs/overview and try to print it with the browsers internal print functionality

#### What is the use-case or motivation for changing an existing behavior?

Not changing, but extending. 
Because all /some of the content in tabs could be important on a printed page.
So it would be nice to have an attribute [printable]="true" or something similar at the md-tab tag, that one can steer which of those tabs should be printed out to paper.
And perhaps another attribute on the whole md-tab-group to have all tabs shown when printing.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2, Angular 4

#### Is there anything else we should know?
You are great, keep up the good work! :-)

Unfortunately you didn't choose to implement this proposal (it would have solved my problem): https://github.com/angular/material2/issues/731

If anybody knows, how i can get this done with existing <md-tab> Component, please let me know! Thank you in advance.

**Comment by jelbourn** [comment]
I don't think we could do this without rendering out all of the tabs all the time, which isn't where we want to be performance-wise.

**Comment by thorstenKoch** [comment]
Could you provide a method, which will render out all content?
