### ISSUE TITLE
md-select does not honour floatPlaceholder="never" if the ngModel is set at initialization

### ISSUE THREAD

**Issue by dSolver** [angular/material2#6400]
#### Bug, feature request, or proposal:
md-select is still floating the placeholder even if floatPlaceholder="never" if the ngModel is set at initialization

#### What is the expected behavior?
floatPlaceholder="never" is honoured

#### What is the current behavior?
Placeholder is invisible (opacity: 0) but is still there and clickable, leading to accidentally opening the select if the placeholder is overlapped with another element.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

https://plnkr.co/edit/Z3qeYrqbEaEzirGgWC4c?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Sometimes we want to have multiple selects close by, such that the vertical padding between each select is less than 16px, in these cases it is possible to trigger the wrong select if the user clicks sufficiently low on the above select

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

**Comment by crisbeto** [comment]
Closing as something that should've been fixed by https://github.com/angular/material2/pull/6404.
