### ISSUE TITLE
CdkTable does not populate after removing/re-adding component

### ISSUE THREAD

**Issue by timblakely** [angular/material2#6410]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

MdTables repopulate after being removed from the DOM, e.g. navigating away from then back to a routed page that contains a table.

#### What is the current behavior?

Table is created and added and datasource is constructed, but connect() is never called.

#### What are the steps to reproduce?
[Plunker](https://plnkr.co/edit/NOlgqbQJfglLHpl9qppi?p=preview)

1) Click the toggle button to remove the table
2) Click the toggle button again to re-insert the table

_Expected: Table populates_

You can force the table to populate again by clicking inside the input filter area.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cdk 2.0.0-beta.8

**Comment by andrewseguin** [comment]
This has been fixed by #5775

See this plunker for an example with the latest master build https://plnkr.co/edit/6VFwEMaD131Iqw26HmwD?p=preview
