### ISSUE TITLE
md -table is not working,"Can't bind to 'dataSource' since it isn't a known property of 'md-table'"

### ISSUE THREAD

**Issue by HardChavda** [angular/material2#6411]
#### Bug, feature request, or proposal:
md-table is not working.
I go through issue 6381 and implemented those changes.

In one component same data table is working perfectly fine,
but when i create new component and another data table for that new component,it throws error.

I have included cdkTableModule from /cdk/table
Also included MdtableModule.

#### below are the dependencies

"dependencies": {
    "@angular/animations": "^4.3.4",
    "@angular/cdk": "git+https://github.com/angular/cdk-builds.git",
    "@angular/common": "^4.3.4",
    "@angular/compiler": "^4.3.4",
    "@angular/core": "^4.3.4",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^4.3.4",
    "@angular/http": "^4.3.4",
    "@angular/material": "git+https://github.com/angular/material2-builds.git",
    "@angular/platform-browser": "^4.3.4",
    "@angular/platform-browser-dynamic": "^4.3.4",
    "@angular/router": "^4.3.4",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.30",
    "@ngx-translate/core": "^7.1.0",
    "bootstrap": "4.0.0-alpha.6",
    "core-js": "^2.5.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.4",
    "ng2-md-datatable": "^1.4.0",
    "rxjs": "^5.4.3",
    "zone.js": "^0.8.16"
  },

#### below is module.ts code 
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';

import { EmployeeDetailsRoutingModule } from './employee-activities-routing.module';
import {CoreModule} from "../core/core.module";
import {MdDataTableModule} from "ng2-md-datatable";
import {CdkTableModule} from "@angular/cdk/table";
import {
  MdPaginatorModule, MdTableModule, MdSort, MdSortModule, MdInputContainer, MdNativeDateModule,
  MdTooltipModule, MdToolbarModule, MdTabsModule} from "@angular/material";
import {FormControl, FormsModule, ReactiveFormsModule} from "@angular/forms";

import {SharedModule} from "../shared/shared.module";
import {BrowserModule} from "@angular/platform-browser";
import {BrowserAnimationsModule} from "@angular/platform-browser/animations";
import {HttpModule} from "@angular/http";

@NgModule({
  imports: [
    CommonModule,
    TranslateModule,
    CoreModule,
    SharedModule,
    BrowserModule,
    BrowserAnimationsModule,
    FormsModule,
    HttpModule,
    MdNativeDateModule,
    ReactiveFormsModule,
    MdTableModule,
    CdkTableModule,
    MdDataTableModule,
    MdPaginatorModule,
    MdSortModule,

    MdTabsModule,
    MdToolbarModule,
    MdTooltipModule,
  ],
  declarations: [
  ],
  providers: [
  ]
})

export class EmployeeModule { }

##even cdkheader is also not working see the screenshot.
![error](https://user-images.githubusercontent.com/24239444/29203211-e2d01444-7e8c-11e7-82d0-94cd50b92d7e.PNG)

**Comment by andrewseguin** [comment]
Please only open issues that are bugs or feature requests. For help troubleshooting, feel free to ask our community at StackOverflow, Gitter, Google Groups, etc
