### ISSUE TITLE
Checkbox to label padding is off when CSS direction property is set to right-to-left

### ISSUE THREAD

**Issue by srix55** [angular/material2#6414]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Checkbox padding should be on the left for right-to-left languages (CSS direction: rtl)

#### What is the current behavior?
The padding is applied on the right for rtl languages as well.

#### What are the steps to reproduce?
http://plnkr.co/edit/6A1wifKy57hsj3qfLRJT?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I am writing a page in Arabic, an rtl language.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
No

**Comment by crisbeto** [comment]
Material handles directionality through the `dir` HTML attribute, instead of the CSS `direction`, because it's a lot less expensive to keep track. RTL styles will work correctly if you switch to using `dir="rtl"`.
