### ISSUE TITLE
MdMenuModule as displayed in example isn't rendered correctly

### ISSUE THREAD

**Issue by peterpeterparker** [angular/material2#6416]
#### Bug, feature request, or proposal:

I tried to implement a `MdMenuModule` like displayed in the example (https://material.angular.io/components/menu/examples). The compilation pass bit when testing it in a browser, the rendering isn't correct.

For example, I've got in my app.component.html:

     <button md-icon-button [mdMenuTriggerFor]="menu">
         <md-icon>more_vert</md-icon>
     </button>

Rendered from the server in my browser I see:

     <button aria-haspopup="true" md-icon-button="" ng-reflect-menu="[object Object]">
          <md-icon>more_vert</md-icon>
     </button>

where I should actually find (according https://material.angular.io/components/menu/examples):

    <button aria-haspopup="true" class="mat-icon-button" md-icon-button="">
        <span class="mat-button-wrapper">
          <md-icon class="mat-icon material-icons" role="img" aria-hidden="true">more_vert</md-icon>    
        </span>
       <div class="mat-button-ripple mat-ripple mat-button-ripple-round" md-ripple=""></div>
       <div class="mat-button-focus-overlay"></div>
    </button>

At first I thought that the problem was an error of my universal app but than I tried the same piece of code and module in another project where I don't use universal or aot and I was able to reproduce the exact same behavior. Could reproduce the problem with a plunker too (see link down here)

#### What is the expected behavior?

Is maybe the example of the website not up-to-date?
If the example is up-to-date, maybe a fix is necessary?

#### What is the current behavior?

The elements are not correctly rendered

#### What are the steps to reproduce?

http://plnkr.co/edit/WNXWpyAgwZtfKBj6IPAi?p=preview

In this plunker you gonna see a button "more" (written text) where actually it should be displayed as icon. Also when you open the menu you'll see the code where you should see a nice rendered menu-popup

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular 4.3.3
material 2.0.0-beta.8

#### Is there anything else we should know?

If I don't include `MdMenuModule` but the deprecated `MaterialModule` I don't face the problem

**Comment by BobBDE** [comment]
Hi,

I think your problem is just because the icons are not working. If you remove the icons from the menu, it looks normal. 
The icons are not working because you forget to import the google font. Here is where it is explain : 
https://material.angular.io/components/icon/api (section Directives>MdIcon).

I think the easiest way to correct it is to add the css link to your index.html : 
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

**Comment by peterpeterparker** [comment]
thx @BobBDE, coolio, importing `MdIconModule` in `app.module.ts` solve my issue
