### ISSUE TITLE
Using class="category-{{item.id}} breaks the layout.

### ISSUE THREAD

**Issue by mackelito** [angular/material2#6417]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
class should be appended and style added

#### What is the current behavior?
The default layout breaks

#### What are the steps to reproduce?
https://plnkr.co/edit/CS1ccrdSaWgAmuWhQRZ3?p=preview
Look at the last chip

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by BobBDE** [comment]
Hi, 
Try to replace the **class="category-{{item.id}}**  with **[ngClass]="'category-'+id"** it seems to be working on the plunkr and it should do the same.

**Comment by mackelito** [comment]
Works great.. and I blame friday! ;)
