### ISSUE TITLE
disableClose in sidenav needs improvement

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#6427]
#### Bug, feature request, or proposal:
Docs gives the below details about **disableClose** option in **sidenav**:

`"Whether the sidenav can be closed with the escape key or not."`

Usually clicking backdrop closes the sidenav, but when this option (disableClose) is set to true, it also disables the closing of SideNav using backdrop.

There could be cases where we would like to disable closing of Sidenav using Esc key but would like it to be closed when user clicks backdrop. Therefore, we should have two separate options disableCloseEsc and disableCloseBackdrop.

**Comment by julianobrasil** [comment]
The dialogs has the same behavior (but in this case it makes sense to have just one closing option). Maybe they're reusing the same libs to deal with this closing feature.

**Comment by willshowell** [comment]
The general consensus with dialogs has been that `disableClose` will disable all methods of closing, and that the user should subscribe to the closing mechanisms individually to manually close the dialog.

For the sidenav, backdrop clicks are already exposed as events, so it seems like the following should happen:

1. The jsdoc comment should be updated to something like `"Whether the user can close the sidenav with the escape key or clicking on the backdrop"`
2. The escape keydown event exposed as an event or observable
