### ISSUE TITLE
Add md-body for rows. 

### ISSUE THREAD

**Issue by DmitrijDN** [angular/material2#6432]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I expect vertical scroll for table content. (Without header)

#### What is the current behavior?
Currently, vertical scroll is for the whole table with header

#### What are the steps to reproduce?
It is for all md-table (even examples)

#### What is the use-case or motivation for changing an existing behavior?
Table header should be always fixed. It is pretty inconvenient to search when you don't see header

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "^2.0.0-beta.8",

**Comment by julianobrasil** [comment]
Dupe: #5885

**Comment by jelbourn** [comment]
Dupe: #5885

**Comment by DmitrijDN** [comment]
@julianobrasil , @jelbourn 

It isn't a solution

![image](https://user-images.githubusercontent.com/1922618/29303679-278f5682-8197-11e7-992f-2a3756c08c9e.png)


First of all scroll is still gets all table height which is awful. Another problem is that table content  overlaps header cells.  

We just need separate div or any tag to separate header and content and set overflow-y to it.

Issue should be reopened.

**Comment by julianobrasil** [comment]
@DmitrijDN, as #5885 is an open issue, IMO, it's better to make your suggestions over there.
