### ISSUE TITLE
Can't resolve '@angular/material/typings/paginator/paginator-intl'

### ISSUE THREAD

**Issue by wenerme** [angular/material2#6433]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

`MdPaginatorIntl` export by `@angular/material`

#### What is the current behavior?

paginator  dont export `MdPaginatorIntl`

#### What are the steps to reproduce?

```
import {MdPaginatorIntl} from '@angular/material/typings/paginator/paginator-intl';
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"dependencies": {
    "@angular/animations": "^4.3.3",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.4.1",
    "zone.js": "^0.8.14"
  }

**Comment by willshowell** [comment]
This has been fixed and will be part of the next release https://github.com/angular/material2/pull/5716

**Comment by jelbourn** [comment]
What @willshowell said
