### ISSUE TITLE
Failure in project build/run

### ISSUE THREAD

**Issue by mariannafld** [angular/material2#6438]
#### Bug, feature request, or proposal:
Failure in: gulp serve:devapp

#### What is the current behavior?
[11:58:19] 'cdk:build:esm' errored after 1.74 s
[11:58:19] TypeError: Cannot read property 'toString' of null
    at F:\Work1\LearnAngular1\material2-master\tools\package-tools\secondary-entry-points.ts:42:13

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
OS - Win 10, 64 bit
Angular/Material - latest

**Comment by donroyco** [comment]
What version of Node.js are you using?

**Comment by mariannafld** [comment]
Node.js - v6.11.2

**Comment by crisbeto** [comment]
This is most likely because you don' have `grep`.

**Comment by mariannafld** [comment]
If the reason in absence of grep, which grep application should be installed in Windows 10, 64 bit?

**Comment by ghd8** [comment]
See https://github.com/angular/material2/issues/6211#issuecomment-321091100

**Comment by mariannafld** [comment]
Thank you,
Git Bash installed, but still problem exists.
Will wait for new query in secondary-entry-points.ts that will work for Windows users.

**Comment by Pikachews** [comment]
Are you running build from the bash shell? It should build fine through bash.

**Comment by mariannafld** [comment]
Oh, sorry for my hastiness...
It's work great! Thank you.

**Comment by crisbeto** [comment]
Assuming that this one is fixed.
