### ISSUE TITLE
performance on edge mobile

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#644]
#### Bug, feature request, or proposal:
I had a look at the demo here: https://material2-app.firebaseapp.com/
I was using Edge on a Microsoft Lumia 950. It worked but is was very slow. Page load of about one Minute and all animations look like slow motion.

#### What is the expected behavior?
Be as fast as chrome.

#### What is the current behavior?
See above

#### What are the steps to reproduce?
Open the link above with a lumia 950 or the visual studio windows phone emulator, which is actually a hyper v virtual machine.

#### What is the use-case or motivation for changing an existing behavior?
Edge and ie 11 are mostly used in enterprise and users cannot switch to "good" browsers.

#### Which versions of Angular, Material, OS, browsers are affected?
?? See the demo above

#### Is there anything else we should know?
As the Microsoft browsers had terrible performance with ng material 1 too as soon as animations ran, a global switch to disable all kinds of animation could be implemented. So a developer can give ie users a good performance while all of the users of "good" browsers have a nice animated experience.

**Comment by jelbourn** [comment]
This site is in development mode and is mostly for development purposes (to validate releases). None of the JS is bundled or minified, and the templates haven't been offline-compiled. We will be doing more benchmarking and performance tuning, as well as providing guidance on performance as the library develops.
