### ISSUE TITLE
bug(accordion): reordering confuses expansion state of the panels

### ISSUE THREAD

**Issue by princemaple** [angular/material2#6446]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Reordering of the panels does not affect the expansion status of the panels

#### What is the current behavior?
It does cause some wrong behavior

#### What are the steps to reproduce?
http://plnkr.co/edit/F6AunHYXOfxGKID5oYV3?p=preview

![image](https://user-images.githubusercontent.com/1329716/29256560-add86d2c-80ee-11e7-8968-2d11d65666b4.png)

1. expand item 1, which is at the top and has active: false
    ![image](https://user-images.githubusercontent.com/1329716/29256577-c67b5cd6-80ee-11e7-8c0c-5893a4ab75ac.png)

1. toggle active, so it becomes active: true and falls down the list
    ![image](https://user-images.githubusercontent.com/1329716/29256592-d9c866e4-80ee-11e7-93a5-75d4f2d0a018.png)

1. expand item 2, which is now at the top, it will become *the expanded one* in the accordion, but it won't really show the expanded content
    ![image](https://user-images.githubusercontent.com/1329716/29256639-3df3aa66-80ef-11e7-976f-1913518f6653.png)

#### What is the use-case or motivation for changing an existing behavior?
When I want to sort items by some status of them, I expect to be able to do so without running into bugs :)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
NG 4.3.2, MD2 beta8

~**If I close the panel and reopen it, everything will be fine again**~
Not really, item 3 is also affected, somehow.

Am I not supposed to reorder accordion items, though?

**Comment by crisbeto** [comment]
@princemaple I'm unable to reproduce the issue in your example. Since the Plunkr is pointing to the latest Material build, it means that the issue could be fixed in master. Can you verify?

**Comment by willshowell** [comment]
@crisbeto maybe it's related to https://github.com/angular/material2/issues/5743? I can't replicate the original plunker either, but the end result looks the same.

**Comment by princemaple** [comment]
@crisbeto it indeed seems to be fixed on master.
