### ISSUE TITLE
Problems with [disabled] in md-tab with material2-builds

### ISSUE THREAD

**Issue by gise88** [angular/material2#6447]
#### Bug:
The disabled md-tab does not become enabled when required (it still remains disabled)

[Plunker](https://plnkr.co/edit/9qmSADHgf44omShZdNhQ?p=preview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
It affect the `material2-builds` version: `2.0.0-beta.8-85a6fff` but I don't know when this bug was introduced. In the beta-8 it works as expected

#### Is there anything else we should know?
I have to use the `material2-builds` because in the beta-8 there was the `MdPaginatorIntl` not exported. 

#### What I've noticed:
If you click on the button `Toggle Disable`, then click on a one of the enabled tabs, the disabled one becomes active!

**Comment by willshowell** [comment]
Looks like a change detection problem. Clicking on any other tab when it should be enabled triggers the change.

**Comment by gise88** [comment]
Updated the broken plunker! :muscle:

**Comment by amcdnl** [comment]
@gise88 Thanks for updating that! PR is in the queue for this!

**Comment by emreavsar** [comment]
+1

**Comment by trishalim** [comment]
Is there a workaround for this without having to update to latest version?
