### ISSUE TITLE
Datepicker Adapter not working as expected.

### ISSUE THREAD

**Issue by vapits** [angular/material2#6452]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Datepicker should use the LOCALE_ID or the `NativeDateAdapter`.

#### What is the current behavior?
Datepicker input has the correct date format though Calendar doesn't display and it works only if the user writes manually a US formatted date. Same with validators, if the user type a different than US format it returns error.

#### What are the steps to reproduce?
I have this `MaterialModule` in my app:
```js
const APP_DATE_FORMATS = {
  parse: {
      dateInput: {month: 'short', year: 'numeric', day: 'numeric'}
  },
  display: {
      dateInput: 'input',
      monthYearLabel: {year: 'numeric', month: 'short'},
      dateA11yLabel: {year: 'numeric', month: 'long', day: 'numeric'},
      monthYearA11yLabel: {year: 'numeric', month: 'long'},
  }
};

export class AppDateAdapter extends NativeDateAdapter {

  parse(value: any): Date | null {
    if ((typeof value === 'string') && (value.indexOf('-') > -1)) {
      const str = value.split('-');
      const dayArray = str[2].split('T');

      const year = Number(str[0]);
      const month = Number(str[1]) - 1;
      const day = Number(dayArray[0]);

      return new Date(year, month, day);
    }
    const timestamp = typeof value === 'number' ? value : Date.parse(value);
    return isNaN(timestamp) ? null : new Date(timestamp);
  }

  format(date: Date, displayFormat: Object): string {

    if (displayFormat === 'input') {
      const day = date.getDate();
      const month = date.getMonth() + 1;
      const year = date.getFullYear();
      return `${day}-${month}-${year}`;
    } else {
      return date.toDateString();
    }
  }
}

@NgModule({
  exports: [
    MdModules,
  ],
  declarations: [],
  entryComponents: [
    PersonalDataDialogComponent
  ],
  providers: [
    { provide: DateAdapter, useClass: AppDateAdapter },
    { provide: MD_DATE_FORMATS, useValue: APP_DATE_FORMATS }

  ]
})
export class MaterialModule {
  constructor(private dateAdapter: DateAdapter<Date>) {
    dateAdapter.setLocale('nl-NL');
  }
}

```

I'm getting this on the input:
![image](https://user-images.githubusercontent.com/8594758/29263868-1bb3c58a-80db-11e7-9f3a-14fe466bb4db.png)
As you see above correct input but calendar doesn't work. 
If the user try manually field is getting an error:
![image](https://user-images.githubusercontent.com/8594758/29263910-45098e1a-80db-11e7-9da1-d147d60a31d3.png)
But if I enter US format:
![image](https://user-images.githubusercontent.com/8594758/29263892-31e3db92-80db-11e7-8a2f-8ea9a340826f.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.3.3
Material beta.8

**Comment by Eppiox** [comment]
I implemented a similar approach for non American style dates and have similar behavior with an added quirk:
The user enters 12-2-2017 being the 12th of Feb, the value returns correctly from the picker, however the visual acts odd, when clicking on the picker shows the month instead of the day, in my case December instead of Feb.

A simple format selector built into it would be GREAT.

**Comment by ghd8** [comment]
Here you can find a working example (DateAdapter) from @julianobrasil and the info about the planned solution  https://github.com/angular/material2/issues/6263#issuecomment-320211085

**Comment by vapits** [comment]
@ghd8 it doesn't work on plnkr and if I add it in my project (I saw it already) it has exactly the same behavior. :/

**Comment by julianobrasil** [comment]
@vapits, have you called `this.dateAdapter.setLocale('pt-br');` as I did in the plunk? It needs to be called once anywhere in the project (since the date adapter is a singleton). Or, even better, setup your `LOCALE_ID`. I've changed the plunk a little bit to show this possibility (look in the `main.ts`): https://plnkr.co/edit/jc4Ywu?p=preview

**Comment by vapits** [comment]
Yes @julianobrasil and I have exactly the same behavior.

**Comment by julianobrasil** [comment]
@vapits, in the example you've posted above, you're not showing the parser function... it's the main part of all the process... do you have one in your real code?

**Comment by vapits** [comment]
@julianobrasil just edited my code.
I'm getting a value like: `2017-07-28T06:33:45.206Z` which I want just to format like `dd-MM-yyyy`. It seems that it works only for the first display on the input only but actually manually the inputs waits for US style and same on Calendar.

**Comment by julianobrasil** [comment]
Modify my plunk and post it here with your date adapter. It's easier to see what's happening.

**Comment by vapits** [comment]
The plnkr doesn't work for me on plnkr website it fails to load the packages :S

**Comment by julianobrasil** [comment]
ok... try to add this code to your date adapter:
```js
parse(value: any): Date | null {
    if ((typeof value === 'string') && (value.indexOf('/') > -1)) {
      const str = value.split('-');

      const year = Number(str[2]);
      const month = Number(str[1]) - 1;
      const date = Number(str[0]);

      return new Date(year, month, date);
    }
    const timestamp = typeof value === 'number' ? value : Date.parse(value);
    return isNaN(timestamp) ? null : new Date(timestamp);
  }
```

**Comment by vapits** [comment]
I did. I'm getting the calendar work but the parsed date is in wrong format:
![image](https://user-images.githubusercontent.com/8594758/29269454-d5cb4248-80f1-11e7-9a06-ecc4a839021c.png)

It doesn't respect it when I change it to `dd-MM-yyyy`

**Comment by julianobrasil** [comment]
oh, my bad... the right function is:
```js
parse(value: any): Date | null {
    if ((typeof value === 'string') && (value.indexOf('-') > -1)) {
      const str = value.split('-');

      const year = Number(str[2]);
      const month = Number(str[1]) - 1;
      const date = Number(str[0]);

      return new Date(year, month, date);
    }
    const timestamp = typeof value === 'number' ? value : Date.parse(value);
    return isNaN(timestamp) ? null : new Date(timestamp);
  }
```

**Comment by vapits** [comment]
@julianobrasil  there are not changes on this function and mine.

**Comment by julianobrasil** [comment]
Yes, there ara changes: I've changed `value.indexOf('\')` to `value.indexOf('-')` in the `if` statement.

**Comment by vapits** [comment]
@julianobrasil Yes I already had fixed this :P :) Still I'm getting the screen shot above :/

**Comment by vapits** [comment]
Ah sorry. The function is the same. But I have the APP_DATE__FORMATS.
So if I have in them:
```
display: {
      dateInput: 'input',
      monthYearLabel: {year: 'numeric', month: 'short'},
      dateA11yLabel: {year: 'numeric', month: 'long', day: 'numeric'},
      monthYearA11yLabel: {year: 'numeric', month: 'long'},
  }
```
Then I have the same issue. Correct initial value but calendar and input (manual) waits for US input.

**Comment by julianobrasil** [comment]
No matter what I do, it always works in the plunk :smiley: . I try using your code as it is (with de MD_DATE_FORMATS). At least how I imagine it is... Is in this plunk: https://plnkr.co/edit/rxzhhl?p=preview

**Comment by ghd8** [comment]
Can you try `dateInput: {year: 'numeric', month: 'numeric', day: 'numeric'},`

**Comment by vapits** [comment]
@ghd8 I tried that already no change :/
@julianobrasil where do you set the providers in your plnkr? And where are the APP_DATE_FORMATS.
I'm copying the code exactly as yours and it doesn't work. Also try to use a date like the one I mention above as source: `2017-07-28T06:33:45.206Z` and convert it to `dd-MM-yyyy`. It doesn't respect it. Only on the initial show.

**Comment by julianobrasil** [comment]
@vapits, I'm not messing with the APP_DATE_FORMATS. I've just did it in this [plunk](https://plnkr.co/edit/AVW6aw?p=preview) to leave it similar to your code. 

But I think, from your last post, didn't get it. If you want to enter `2017-07-28T06:33:45.206Z` (typing in the input, right?) you have to do almost nothing, but change the parse function to do something like new Date('2017-07-28T06:33:45.206Z'), or whatever date comes in from the args. Man, try to make the plunker to work.

And lets move this discussion to stackoverflow.com. There's way too many messages than recommended  by the moderators and it really seems to be a misconfiguration of something instead of a bug. 

Create a post in stackoverflow.com and post the link here.

**Comment by vapits** [comment]
@julianobrasil Here it is, I managed to replicate it to a new plnkr:
https://plnkr.co/edit/blxY8zEbScGPLVCTLMNw?p=preview

**Comment by julianobrasil** [comment]
The problem is that your format function is sometimes generating the date in dd-mm-yyyy and sometimes in 'yyyy-MM-ddThh:mm:ss.mmmZ' (when building the calendar). You have to improve the parse function to test in which format the date is (if there's no '-', it's probably in the latter format).

**Comment by julianobrasil** [comment]
Correcting: if there's no ':', it's probably in dd-MM-yyyy format.

**Comment by vapits** [comment]
@julianobrasil I guess yes for the parse as you type, sure.
Though the calendar issue is still there and the selected date as well :/

**Comment by julianobrasil** [comment]
Take a look: https://plnkr.co/edit/CZi6mI?p=preview

**Comment by vapits** [comment]
@julianobrasil Oh..... thx. Seems only that there is still an issue with the selected date:
This is on input (by calendar or when I add it manually):
![image](https://user-images.githubusercontent.com/8594758/29271016-b372d726-80f9-11e7-9b24-81f5581f8df4.png)

And this is in my scope:
![image](https://user-images.githubusercontent.com/8594758/29271018-bccd81d6-80f9-11e7-81cb-c4ba24366c10.png)

**Comment by vapits** [comment]
Also it seems that now that this:
```
15-
```
Is considered a valid date and the validator doesn't fireup an error. So someone can save this for a date...

**Comment by julianobrasil** [comment]
@vapits, sorry for the wrong code on my last plunk. I had to leave our work (becouse I'm in a rush in the last days releasing a new project), but I've corrected the code now (not the part of the validation): https://plnkr.co/edit/CZi6mI?p=preview

Concerning the validation part, I'm almost sure (didn't have time to test it), that you have to override the `isValid(date:Date) => boolean` function, which is currently: 
```js
  isValid(date: Date) {
    return !isNaN(date.getTime());
  } 
```

**Comment by julianobrasil** [comment]
I did something in that direction in the plunk, but it needs improvments. You can check that and work upon it to enforce the date format typed in in correct.

**Comment by julianobrasil** [comment]
Or... I bet you can do something using the parse function like setting a wrong date object when the typed date is in wrong format (like returning `null` instead of a Date object). It would force the validation function to return `false`.

I did something in that direction  in the plunk, but it needs improvments. You can check that and work upon it to enforce the date format typed in in correct.

**Comment by mmalerba** [comment]
@julianobrasil Yes you are on the right track. So `Date.parse` considers those to be valid dates and returns valid `Date` objects for them. In order to make it consider those invalid you would need to check for those cases and then return something that `isValid` will classify as an invalid date. I recommend doing this by just changing the `parse` function and leaving `isValid` alone, like this:
```ts
parse(value: any) {
  if (/* Check for strings I consider invalid */) {
    return new Date(NaN);
  }
  // continue constructing Date
}
```

Also I just wanted to say thank you for all of your help responding to datepicker issues :) I really appreciate it

**Comment by Manasonabhaban** [comment]
![pic123](https://user-images.githubusercontent.com/38691775/39347669-9810c498-4a11-11e8-9de3-bd6c8e76c0e2.png)

Can I load year view format. I do not want to load day. Please help me out in Angular 4.Thanks in advance.
