### ISSUE TITLE
Naming discrepancies in Sorting and Pagination implementations

### ISSUE THREAD

**Issue by pfeigl** [angular/material2#6453]
#### Bug, feature request, or proposal:
With the latest implementation of the data-table there is also now two additional components which can be used along with it:
- MdPaginator
- MdSort

The implementations of those two components have quite some discrepancies in their naming conventions which should be aligned in my opinion:

- Component Name
-- Current: **MdPaginator** and **MdSort**
-- Expected: **MdPage** and **MdSort** or **MdPaginator** and **MdSorter**

- Event Property Names
-- Current: **page** and **mdSortChange**
-- Expected: **page** and **sort** or **mdSortChange** and **mdPageChange**

- Event Class Names
-- Current: **PageEvent** and **Sort**
-- Expected: **PageEvent** and **SortEvent** or **Page** and **Sort**

- Event Class Implementation
-- Current: PageEvent is a **class** and Sort is an **interface**
-- Expected: Both are either **class** or **interface**

#### What is the use-case or motivation for changing an existing behavior?
Very similar components should follow the same implementation guidelines in order for integrators to be able easily understand the material2 APIs

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2.0.0-beta.8-f78726d

**Comment by jelbourn** [comment]
`MdSort` captures sorting _state_. The interaction occurs through `md-sort-header`. The split exists because you will have one sort state but multiple sort headers.

The pagination captures both state and interaction, so it's just "paginator".
