### ISSUE TITLE
Input container / form field font size does not adhere to material design spec

### ISSUE THREAD

**Issue by gtranter** [angular/material2#6455]
https://github.com/angular/material2/blob/85a6fff17a1f3ccbbda1f555ba32868c95b16b25/src/lib/form-field/_form-field-theme.scss#L146

The size is set to inherit, but the spec requires size 16. Inherit is wrong.

**Comment by gtranter** [comment]
Apparently this was addressed by #5154 / #5262 but not fully fixed (the root cause was addressed but not the root problem - font size).

**Comment by michahell** [comment]
aha... so this is probably why `md-select`s are sized `16px` and form field text inputs are... `whatever` sized

**Comment by jelbourn** [comment]
We intentionally make the input more flexible than the spec calls for (allowing the input to use its inherited font-size).

**Comment by gtranter** [comment]
Why? I don't understand why it needs to be "more flexible." I can easily override the style if I want flexibility. I'd love to know the reasoning behind that for my own education. Do you do this with any other components? Disappointing that in some cases the spec is adhered to with great rigidity and no consideration for "flexibility" whereas here it is considered unimportant.

I though this would be an obvious one but I guess I was wrong. I suspect this is an ad-hoc arbitrary decision that no-one really thought through, so let me state the case a little more clearly. This is *less* flexible because now I *have* to override the style if I happen to have my input in a <p> or <div> with .mat-typography applied - which is generally always. I apply .mat-typography at the root of my page which is what Angular Material recommends (I love this feature). So every input in every DIV or P now has font size 13 with (as a result) a barely visibly 9.75px label and hint. (You should try this and see how bad it looks.) And there is no class defined so that I can easily say <md-input-container class="mat-input-typography"> or similar to have it at spec size - because you made .mat-input font-size inherit. Please, for the love of bacon, explain to me how this is more "flexible???"
