### ISSUE TITLE
bug(tab): tab header label  readability issue on small devices 

### ISSUE THREAD

**Issue by m98** [angular/material2#6456]
[*] bug

#### What is the expected behavior?
On smaller devices, tab header content should be readable/visible.
_(Note: the tab with **Our** label should be **Our large tab title**)_
![screenshot from 2017-08-14 18-23-46](https://user-images.githubusercontent.com/7496103/29274629-bdcc05e8-811d-11e7-9324-5181b91bbf8c.png)

#### What is the current behavior?
Instead of showing the content of the tab header, we will see some parts of the label.
Resize the browser to a smaller width, and the tab label is cut and we can't read the content of the label.
By the way, we already have `>` and `<` buttons beside of the tab header, we can set the size of all tab header labels to the largest text width, and skip cutting words ( or `ellipsis`).

#### What are the steps to reproduce?
https://plnkr.co/edit/cZBCdICrA5gKwDmIQH3c?p=preview

#### What is the use-case or motivation for changing an existing behavior?
smaller devices should be able to use tabs as well.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
@angular/cli: 1.2.6
node: 7.10.0
os: linux x64
@angular/animations: 4.3.2
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2

OS: Fedora 25
Browser:  (Version 59.0.3071.86)
```

#### Is there anything else we should know?
Here is what material.io says about tabs ([here](https://material.io/guidelines/components/tabs.html#tabs-content)):
> A long label exceeding the maximum width of a tab may wrap to a second line before being truncated.
> Wrap labels before truncating them. Truncating labels too early can impede comprehension.

**Comment by amcdnl** [comment]
Looks to be fixed on latest

![img](https://content.screencast.com/users/amcdaniel22/folders/Snagit/media/ebd55f2c-1070-4181-9c69-f8e680ceec5b/2017-09-09_11-39-21.png)
