### ISSUE TITLE
Datepicker - format date when focus is lost

### ISSUE THREAD

**Issue by alex321** [angular/material2#6457]
#### Proposal:
Hey, 

Currently, if you select a date from the datepicker pop-up, you get the date using the `format` function provided for the `DateAdapter`. Could there be an option to use the same formatting function after the user has entered a date in the input and moved away?

**Comment by iblocks-Xander** [comment]
As far as I can see, it formats the date while using keyboard input anyway.

Take a look at this plunkr: https://plnkr.co/edit/Qy8qel65RhsHZhvEbCod?p=preview

You should probably make your own focus handler and grab the value when focus is lost.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
