### ISSUE TITLE
Md-table formatting when table has too many columns.

### ISSUE THREAD

**Issue by pedrocleto** [angular/material2#6459]
When the table has a lot of columns the formatting looks strange because it tries to tighten the columns together instead of adding a horizontal scroll. 

My suggestion would be to add a fixed column width and  provide a horizontal scroll

Thank you

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
