### ISSUE TITLE
Sidenav still hiding text in RTL mode

### ISSUE THREAD

**Issue by theunreal** [angular/material2#646]
Do you want to request a feature or report a bug?
bug.
This bug is already reported by me, and as the last update of angular 2 material - which had to fix this bug - it actually didn't fix.
https://github.com/angular/material2/issues/411

What is the current behavior?
In RTL (Right-to-left) versions of a page, the sidenav content starts inside the sidenav and blocked by it.

If the current behavior is a bug,
master.html:
`<md-sidenav-layout> <md-sidenav #start mode="side" [opened]="true"> <sidebar></sidebar> </md-sidenav>`

sidebar.html:

  ```
<md-toolbar color="primary">Some info</md-toolbar>
  <div class="content">
     Hello, I'm a Sidenav!
 </div>
```

What is the expected behavior?
Sidenav Content should start from the end of the sidenav (the end in RTL versions, is the left side of it)

What is the motivation / use case for changing the behavior?

Text and other element shouldn't be hidden inside the sidenav
support RTL pages

Which version of Angular and Material, and which browser and OS does this issue affect?
Angular material 2.0.0-alpha5-2
Cross platform (Bug on IE/FF/Chrome)

Other information

![image](https://cloud.githubusercontent.com/assets/6171883/15859136/895ad54c-2ccc-11e6-8e65-fc676e63e42b.png)

![image](https://cloud.githubusercontent.com/assets/6171883/15859145/94d09b28-2ccc-11e6-8d50-f14928e4ab00.png)

**Comment by robertmesserle** [comment]
@theunreal Can you provide a Plunkr or link so that I can see it failing?  I am unable to recreate your issue so far.

**Comment by robertmesserle** [comment]
Closing for now, will reopen if a Plunkr or demo is added.

**Comment by theunreal** [comment]
@robertmesserle  here you go:
http://plnkr.co/edit/wYe0qFoJVzG0WbyEpgXI?p=preview

**Comment by theunreal** [comment]
Notice that:
![image](https://cloud.githubusercontent.com/assets/6171883/15984622/e4577eb2-2fda-11e6-9a37-924ceb1ab1bf.png)

**Comment by robertmesserle** [comment]
This is because the `Dir` directive is required for RTL support to work properly.  In order to make this Plunkr work, you would need to:
- Add an import for Dir: `import {Dir} from '@angular2-material/core/rtl/dir';`
- Include that in your directives list: `directives: [MD_SIDENAV_DIRECTIVES, Dir],`
- Add it to your template: `<md-sidenav-layout dir="rtl">`

This is not really documented yet, and is something that we are going to have to make more obvious.

**Comment by robertmesserle** [comment]
@theunreal I opened an issue to make this more obvious here https://github.com/angular/material2/issues/679

**Comment by theunreal** [comment]
Thanks for the quickfix @robertmesserle! Hope it can work without any additional lines of code in the near future.

**Comment by theunreal** [comment]
Hey @robertmesserle ,how I can use that in the latest Angular & Material?

**Comment by alirezamirian** [comment]
@robertmesserle 
I have an `apply-dir` directive which adds dir attribute to elements based on current language. MdSidenav direction doesn't work with this kind of dynamic dir setting.
