### ISSUE TITLE
md-error clashes with md-checkbox

### ISSUE THREAD

**Issue by dzamula** [angular/material2#6460]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
More empty space between components. There should be some margin-bottom in `<md-error>`

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/18217112/29280564-65da24e4-8124-11e7-98d6-e4e8d0d087d9.png)

#### What are the steps to reproduce?

```html     
        <md-input-container [hideRequiredMarker]="true">
            <input mdInput type="password" placeholder="Password" #password="ngModel" required>
            <md-error *ngIf="password.hasError('required')">
                Password is required
            </md-error>
        </md-input-container>
        <md-checkbox #rememberMe="ngModel" [ngModel]="false" name="rememberMe">
           Keep me signed in
        </md-checkbox>
```

#### What is the use-case or motivation for changing an existing behavior?
Bad UI/UX

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.3.3
material 2.0.0-beta.8

**Comment by jelbourn** [comment]
All of the Angular Material components very intentionally have no margins. There is no margin that will every be right for all apps, so we leave that to the application developer.
