### ISSUE TITLE
Set tabindex in custom component

### ISSUE THREAD

**Issue by BobBDE** [angular/material2#6465]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
Be able to set the tabindex to customs components (like md-slide-toggle)

#### What is the current behavior?
The tabindex are ignored by the customs components and thus the automatic tabindex is used. 

#### What are the steps to reproduce?
Here is a simple plunkr that show the problem. Focus the first toggle button and click tab. The last one should be focused as it has the property tabindex set to "2". 
http://plnkr.co/edit/V4q7uy?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Be able to change the tabindex or remove an element from tabindex.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
No.

**Comment by jelbourn** [comment]
We should accept a `tabIndex` for each of the interactive components. We currently do this only inconsistently.
