### ISSUE TITLE
Md-table formatting when table has more columns than space. 

### ISSUE THREAD

**Issue by pedrocleto** [angular/material2#6471]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The expected behaviour should have a fixed column width option and a visible horizontal scroll. Also could be handy to have text truncation through the use of ellipsis.

#### What is the current behavior?
When the table has more columns than space the formatting looks strange because it tries to tighten the columns together instead of adding a horizontal scroll and keeping them with some padding around them. Making the headers not aligning properly with the column data.

#### What are the steps to reproduce?
Create a table with at least 10 columns than shrink the visible space.

#### What is the use-case or motivation for changing an existing behavior?
Most tables have horizontal scrolls and text truncation when they are bigger than the space they have 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.3.4
beta 8

#### Is there anything else we should know?
![table](https://user-images.githubusercontent.com/3227505/29308711-bf1054aa-819e-11e7-980d-137aba4e442f.png)

**Comment by miguelcaravantes** [comment]
same question

**Comment by andrewseguin** [comment]
Sounds like you want to add a min-width value to your md-row so that it provides scrolling. Sticky columns is a feature we do want to add, and we're tracking it here #5890

```
.mat-header-row, .mat-row {
  min-width: 1000px;
}
```

https://plnkr.co/edit/fjVFtyiIPF6SSAnGM8gh?p=preview

**Comment by megharao** [comment]
Hey @andrewseguin But what if the number of columns if not fixed? If the number of columns is too less then the size of each column is too much and if I have a lot of columns the data looks very messy
