### ISSUE TITLE
md-autocomplete does not trigger the md-option-list-view in Firefox v. 45~

### ISSUE THREAD

**Issue by developer-max** [angular/material2#6472]
#### What is the expected behavior?
On click in the input-field with binded "mdAutocomplete", the list with md-options should open up.

#### What is the current behavior?
In Firefox Version 45~ the click event will not be triggered and the list-items (md-options) will not open up. The issue does not appear in the latest Firefox Version.

#### What are the steps to reproduce?
It can be reproduced with Firefox 45.2.0 on your examples page on https://material.angular.io/components/autocomplete/examples.

onclick: nothing happens in Firefox 45.2.0 (works on every other browser)
keyup: the list is shown - as expected

![autocomplete](https://user-images.githubusercontent.com/30209354/29312917-d16d3654-81b7-11e7-9361-cf9733e85f95.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Version 4.3.1
Material Version 2.0.0-beta.8
TypeScript Version: 2.4.2
Firefox Version 45.2.0

**Comment by 1Guv** [comment]
I have experienced this with the latest version of Firefox 51.0.1 - is there a solution?
