### ISSUE TITLE
new feature mdSelect multioption

### ISSUE THREAD

**Issue by Masber** [angular/material2#6473]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
mdSelect to be able to behave as a multi option where user could select multiple values by pressing Ctl or shift plus click

#### What is the current behavior?
mdSelect only allows to select one element

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
HTML allows this type of behaviour so  angular material should so same

**Comment by crisbeto** [comment]
`md-select` already supports selecting multiple options. You have to set the `multiple` attribute:

```html
<md-select [(ngModel)]="value" multiple>
  ...
</md-select>
```
