### ISSUE TITLE
Checkboxes and Radio buttons do not have persisting ripple effect

### ISSUE THREAD

**Issue by palpatine1991** [angular/material2#6480]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Based on Material specs (https://material.io/guidelines/components/selection-controls.html#selection-controls-checkbox) Checkboxes and Radio buttons should have the ripple effect as long as they have focus.

#### What is the current behavior?
When the component gets focus and changes its state, the ripple effect disappears,

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://plnkr.co/edit/yCC0p7ngpwQ9twv8IoWk?p=preview

just click on first checkbox, press TAB key (putting the focus on second checkbox) and click on second checkbox (or press SPACE key). This results with disappeared ripple. 

#### What is the use-case or motivation for changing an existing behavior?
It is confusing for the user that he cannot see where the focus is.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2 2.0.0-beta.8.

#### Is there anything else we should know?
It works correctly in Material JavaScript based library (Material 1)

**Comment by jelbourn** [comment]
These controls only show their focus state when the focus arrives via keyboard interaction. This is one of the "implied but not explicitly written" parts of the spec.

(it's confusing if the focus indicator is persistent when clicking via the mouse; it makes it appear that the ripple is just broken.)

**Comment by palpatine1991** [comment]
I see.

Would it be at least possible to make the reference to the native input publicly accessible? It would enable the handling of the focus on the adopter side in some other way.

**Comment by jelbourn** [comment]
You should be able to use the `focusin` event to know when the internal input has been focused.

**Comment by palpatine1991** [comment]
Thanks, it works like a charm!
