### ISSUE TITLE
[Proposal] Nested md-optgroup

### ISSUE THREAD

**Issue by dev054** [angular/material2#6482]
#### Bug, feature request, or proposal:
Proposal.

#### What is the expected behavior?
Nested md-optgroup should work.

#### What is the current behavior?
Nested md-optgroup doesn't work. It simply renders nothing when you put an `md-optgroup` inside another `md-optgroup`.

#### What are the steps to reproduce?
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://plnkr.co/edit/8CUmM7cjsBQr7APDCafS?p=preview

#### What is the use-case or motivation for changing an existing behavior?
In AngularJS Material it was possible. See [this plunker](https://plnkr.co/edit/Cw90urvr3TkodtOP2Ru8)

**Comment by jelbourn** [comment]
This is not something we plan on supporting. We _will_ have a tree component in the future, which is kind of the same idea, but not nested optgroups.
