### ISSUE TITLE
[Proposal] Stackblitz

### ISSUE THREAD

**Issue by Leonzen** [angular/material2#6491]
#### Bug, feature request, or proposal:
Proposal

#### What is the use-case or motivation for changing an existing behavior?
Please provide a material template for stackblitz (https://stackblitz.com/). It is far easier and faster to use then plunker or other tools.

**Comment by ncrawlins** [comment]
You can basically just follow the steps in the getting started, except in stackblitz angular template
1. Add dependencies, @angular/material, hammerjs, @angular/animations
2. Add a theme by adding a cdn ref to a prebuilt theme in the stackblitz external resources.
3. Then add whatever modules you want (and don't forget an animations module) and go to town.

Example here.  https://stackblitz.com/edit/angular-dbqq33

**Comment by jelbourn** [comment]
The Angular team has chatted with the StackBlitz team and all I can say is... stay tuned.

**Comment by Misiu** [comment]
@jelbourn any news?

**Comment by DevVersion** [comment]
There is a StackBlitz template now.

**Comment by chriscurnow** [comment]
@DevVersion Where is the StackBlitz template?

**Comment by DevVersion** [comment]
@chriscurnow You can find it in the `README.md` file ([here](https://github.com/angular/material2/blob/master/README.md)), but you can also go to [the docs](http://material.angular.io) and just view any example in StackBlitz
