### ISSUE TITLE
Allow for title-style inputs

### ISSUE THREAD

**Issue by benelliott** [angular/material2#6494]
#### Bug, feature request, or proposal:
Proposal/feature request:

The padding that is currently on forced on `mdInput` prevents you from implementing large, title-style inputs that are contained in a header bar. While this form factor is not explicitly mentioned in the Material Design spec it is visible on many Google products, such as Google Forms (see below), and the current stylesheet rules make this quite hard to achieve.

![forms_title_1](https://user-images.githubusercontent.com/4996462/29370420-2a23e4ec-829d-11e7-9fe9-f3051b255b91.png)

#### What is the expected behavior?
It should be possible to make large versions of `mdInput` without tweaking too much internal styling.

#### What is the current behavior?
A lot of tweaks are necessary. This is partly because padding units are in `em`, so they will scale linearly with font size (leaving a lot of white space).

#### What are the steps to reproduce?

See http://plnkr.co/edit/TjJAPOH34WcZ7VJtWpeL?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Creative freedom when using the library.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0 beta 8, Angular 4.3.3

#### Is there anything else we should know?
No

**Comment by donroyco** [comment]
The request you're proposing does not follow the [Google Material Design](https://material.io/guidelines/components/text-fields.html#text-fields-layout) specs on the subject of text fields (inputs). Why not make your own implementation using Material 2 as guidance?

**Comment by jelbourn** [comment]
This will probably be a bit more obvious in an upcoming release: we're changing `md-input-container` to `md-form-field`, which does a better job communicating how the component is intended to be used. Form fields have associated errors, hint text, etc. 

For just a big text input, it would be a separate thing (which we don't have a specific component for).
