### ISSUE TITLE
MdCheckbox fires a click event twice

### ISSUE THREAD

**Issue by chrismcgregor** [angular/material2#651]
I noticed that the (click) event is being called twice for MdCheckbox.

**Comment by sendilkumarn** [comment]
On `disable`  - click function is executed.

**Comment by chrismcgregor** [comment]
Sendi,

I get two events for (click) when clicking on a checkbox and it is not disabled. I am now using (change) event, which only fires one event. I have something working now.

By the way, great stuff with Angular2-material.

Cheers!
Chris
--
Christopher McGregor
415.624.6261 // chris@mcgregor.io

**Comment by webmutation** [comment]
Should the checkbox keep the shadow? 
The animation does not seem to complete after the click.

**Comment by Neozaru** [comment]
Apparently, when registering `(click)` event on the **md-checkbox**, the event is handled by the parent element but is also handled by the `<input>` element when not *disabled*.
On my side, what does work is disabling parasitizing `(click)` events (`$event.stopPropagation()`) on the `input` itself, and handling it on the top-level (or host) element, stopping propagation if *disabled*.
Note that the `(click)` event triggered when pressing SPACE key is also blocked when stopping propagation from the `<input>`.
`ngChange` behavior remains the same.
Looking for a better solution.

**Comment by Neozaru** [comment]
@robertmesserle FYI I also worked on it last evening and ended up with a ugly solution. You can still take the unit tests from it (*src/components/checkbox/checkbox.spec.ts*) : https://github.com/angular/material2/compare/master...Neozaru:bugfixes/checkbox-click-event-once?expand=1

**Comment by robertmesserle** [comment]
@jelbourn If #664 works and passes tests, we should use that one and close this one out.

**Comment by robertmesserle** [comment]
Closing for now, will reopen if #664 doesn't pan out.

**Comment by robertmesserle** [comment]
Closed the wrong thing.

**Comment by jelbourn** [comment]
Fixed in #672
