### ISSUE TITLE
[Tabs] Long-click on pagination arrows should continue scrolling

### ISSUE THREAD

**Issue by amcdnl** [angular/material2#6510]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
When a user has a long list of tabs and they are trying to scroll them it would be ideal to have the ability to just long press on the tab scroll arrows and it continue scrolling.

#### What is the current behavior?
Currently you have to continuously click the arrow for it to scroll.

**Comment by naveedahmed1** [comment]
@jelbourn this could also be added to datepicker months/years navigation.
