### ISSUE TITLE
md-select panelClass does not apply classes

### ISSUE THREAD

**Issue by bniedermeyer** [angular/material2#6512]
#### Bug, feature request, or proposal:
Per the [md-select documentation](https://material.angular.io/components/select/api) the `panelClass` input should apply the specified classes to the select panel and function the same as `ngClass`. Specifying a class in the input doesn't apply the desired class. 

#### What is the expected behavior?
Classes that are indicated in the `panelClass` input should be applied. 

#### What is the current behavior?
The class specified is not applied to the element. 

#### What are the steps to reproduce?
[Plunker](http://plnkr.co/edit/OcmbO5ZlZpkjY1f5lizd?p=preview)

#### What is the use-case or motivation for changing an existing behavior?
In my specific use case I am using a `md-select` on a dark background and wish to change the color of the selected value that's being displayed to something lighter. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.8
Typescript 2.1.6
Angular 4.1.3

#### Is there anything else we should know?
Thanks for the help!

**Comment by julianobrasil** [comment]
Take a look at @willshowell's https://github.com/angular/material2/issues/5450#issuecomment-312712854
