### ISSUE TITLE
Tooltip - support HTML

### ISSUE THREAD

**Issue by carlcheel** [angular/material2#6515]
#### Bug, feature request, or proposal:
Allow HTML in tooltips

#### What is the expected behavior?
Tooltips allow HTML

#### What is the current behavior?
Tooltips do not allow HTML

#### What is the use-case or motivation for changing an existing behavior?
Basic functionality should someone want a bold tag or a line break
in the tooltip. 

#### Is there anything else we should know?
Most libraries support this functionality, there is currently no workaround but to use a different library. I'd really like to get the communities thoughts on this.

**Comment by donroyco** [comment]
HTML in tooltips won't be supported, see @jelbourn's [statement](https://github.com/angular/material2/issues/5440#issuecomment-313740211) in another request about this. Please use the search function before asking a duplicate request.

**Comment by carlcheel** [comment]
Apologies @donroyco and @jelbourn it must admit I didn't see this initial issue.

It does seem like a common request, and although it presents challenges for a11y, i'm specifically talking really basic content enhancements such as line breaks and bold/strong text  (was could be considered an a11y feature).

I'm concerned that because many other libraries offer this support, people might be inclined to include another third party library for something so simple.

**Comment by jelbourn** [comment]
We have no plans to add full templating support to the existing tooltip component.

We _do_ have plans to eventually build a more generic "popup" style component, but that is further out in the future.
