### ISSUE TITLE
MdSelect not working in universal

### ISSUE THREAD

**Issue by yashsriv** [angular/material2#6516]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
With universal rendering, `MdSelect` should work like other components.

#### What is the current behavior?
With universal rendering, `MdSelect` throws an error:
```
TypeError: this.trigger.nativeElement.getBoundingClientRect is not a function
```

#### What are the steps to reproduce?

Use `MdSelect` in any component of a universal project and try universal rendering.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.x, Material beta.8

**Comment by jelbourn** [comment]
Our prerender test uses md-select and works:
https://github.com/angular/material2/blob/master/src/universal-app/kitchen-sink/kitchen-sink.html#L162

Feel free to reopen if you can provide more reproduction information
