### ISSUE TITLE
Wrong md-input-container style causing md-error layout issue

### ISSUE THREAD

**Issue by etiennecrb** [angular/material2#6517]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`md-error` under `md-input-container` should display without overflow.

#### What is the current behavior?
If default font was overridden for `body`, using 'Open Sans' for instance, the error is not entirely inside the container's box.
![capture du 2017-08-17 09-13-30](https://user-images.githubusercontent.com/12871063/29400417-a9418014-832d-11e7-95e1-03fc76266f06.png)

This is because `md-input-container` styles are not valid according to Chrome 60.
![capture du 2017-08-17 09-14-02](https://user-images.githubusercontent.com/12871063/29400513-eb9c5bfa-832d-11e7-9149-b4b679d6b218.png)

#### What are the steps to reproduce?
https://plnkr.co/edit/Z2FmvRqT4hcNoHgl0Tam?p=preview

I just took the Material example and applied 'Open Sans' font on the body, you can see the overflow.
![capture du 2017-08-17 09-21-16](https://user-images.githubusercontent.com/12871063/29400590-1d11d2e6-832e-11e7-893f-061a68eda4d1.png)

Applying Roboto font on the `md-input-container` resolves the issue.

#### What is the use-case or motivation for changing an existing behavior?
Inside a dialog, this bug creates layout issues (scrollbars appear, error is not entirely visible etc.).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm trying this with Angular 4.3.5, Material 2.0.0-beta8, Chrome 60 on Ubuntu 16.04.

#### Is there anything else we should know?
No.

**Comment by crisbeto** [comment]
The invalid font declaration has been fixed in https://github.com/angular/material2/pull/5154.
