### ISSUE TITLE
Snackbar example not working on plnkr

### ISSUE THREAD

**Issue by gtzinos** [angular/material2#6518]
The snackbar example on plnkr not working.

https://plnkr.co/edit/?p=preview

**Comment by donroyco** [comment]
Working for me: https://plnkr.co/edit/2VkpxFI5auVXQwLXiarB?p=preview

**Comment by gtzinos** [comment]
Yeap, i didn't recognized that it was empty. So the website navigates me with a wrong way.

https://material.angular.io/components/snack-bar/overview

**Comment by gtzinos** [comment]
Maybe something went wrong with plnkr, now it is working.

This is a screenshot to check that it was happened (http://prntscr.com/g9jbwb).
