### ISSUE TITLE
Is there a column drag-drop capability in md-table?

### ISSUE THREAD

**Issue by 2dTech** [angular/material2#6522]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
Should be able to change the column position by drag/drop capability

#### What is the current behavior?
I don't see an option for that in the current example provided.

#### What are the steps to reproduce?
Create a simple md-table grid with more than one column in it and try to change the column position by drag-drop. 

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by jelbourn** [comment]
There is nothing built into the table; eventually we'll have some guidance on how to do things like this, but it won't ever be baked directly into `md-table` or `cdk-table`

**Comment by Bsujeet** [comment]
Can you please provide guideline on how to implement the column re-positioning feature in md-table or cdk-table.
Thamks

**Comment by wolfvik** [comment]
We too need some guideline on how to implement column reordering on drag and drop, with some hooks to track the new order of the columns after the reordering event. I would really appreciate if you could provide some guideline on this.

**Comment by palarnab** [comment]
Since this issue is closed and a much needed requirement for our app, it would be great to see if any support or workarounds are available. Thanks in advance

**Comment by Yonet** [comment]
@palarnab here is the [related issue that is currently open](https://github.com/angular/material2/issues/8963)

**Comment by lujian98** [comment]
Come cross with angular material table column drag and drop.
Here is my solution: https://github.com/lujian98/Angular-material-table-DnD.
You may have to change the data source interface if you want use it.
Here is demo: https://stackblitz.com/edit/angular-p12rek
