### ISSUE TITLE
Datepicker cannot pick month because of the current selected date

### ISSUE THREAD

**Issue by StevenSongToronto** [angular/material2#6526]
#### Bug, feature request, or proposal:
If the current selected date is "1/28/2017", in popup calendar, click "JAN 2017" dropdown, FEB, MAR, etc are selectable normally.
But if the current selected date is "1/31/2017", in popup calendar, click "JAN 2017" dropdown, FEB, APR, JUN ,etc are not selectable because these months do not have date "31".

#### What is the expected behavior?
All months should be selectable regardless of the current selected date.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by jelbourn** [comment]
@mmalerba this actually throws an error

**Comment by mmalerba** [comment]
This was fixed in #6129
