### ISSUE TITLE
Support flexible overlay size with connected position strategy

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#6534]
This issue tracks the high-level feature of supporting overlays that are automatically an appropriate size based on their position and viewport bounds. This is accomplished by creating a bounding container element that constrains the size of the overlay panel. 

In-progress work is: https://github.com/jelbourn/material2/blob/better-connected-position/src/lib/core/overlay/position/better-connected-position-strategy.ts

**Comment by willshowell** [comment]
As a reminder from https://github.com/angular/material2/pull/8280#discussion_r150113801, it would be great if whatever api is exposed for "position changes" emits on actual changes (instead of all position events) and within the ng zone.

**Comment by isaacplmann** [comment]
Is there work behind the scenes being done on this? Or is this something that would benefit from someone writing a PR?

@jelbourn, it looks like you've already put some thought into how to solve this.  What is still left to be done?

**Comment by crisbeto** [comment]
The work is close to being finished @isaacplmann.

**Comment by isaacplmann** [comment]
@crisbeto Great!  Glad to hear it.  Thanks for the hard work.
