### ISSUE TITLE
Sidenav on main site doesn't work in iOS 8.1.2 Safari (iPad Mini)

### ISSUE THREAD

**Issue by thalamus12** [angular/material2#6536]
#### Bug:
The Sidenav example on material.angular.io doesn't animate properly on opening, and doesn't collapse. Using iPad Mini, Mobile Safari 8.0, iOS 8.1.2.
https://material.angular.io/components/sidenav/overview

#### What is the expected behavior?
Click "Open sidenav" and have it open (with animation). Click away to collapse (with animation).

#### What is the current behavior?
No animation on opening, and on closing the content in the sidenav stays on the page but the shadow overlay is gone.

#### What are the steps to reproduce?
Try the example at that URL on an iPad Mini in iOS 8.1.2.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
iOS 8.1.2, Mobile Safari 8.0

**Comment by willshowell** [comment]
I think they only support the last two versions of major browsers, which would be iOS 9 and iOS 10

**Comment by aldo-roman** [comment]
@willshowell  and notice it will be soon iOS 10 and iOS11

**Comment by jelbourn** [comment]
Yep, we only support Safari 9/10 now. When 11 comes out we aren't going to do anything that would make 9 not work (though we may stop running unit tests on it).
