### ISSUE TITLE
[slider] change detection issue with styles

### ISSUE THREAD

**Issue by willshowell** [angular/material2#6542]
#### Bug, feature request, or proposal:
Bug

#### Current

Note that the slider track does not update its position until mouseover

![slider-cd-issue](https://user-images.githubusercontent.com/6475576/29466844-519d9d54-840c-11e7-9705-aa837dcf818a.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest build:  0113c38

**Comment by jelbourn** [comment]
Potentially related to becoming `OnPush`
