### ISSUE TITLE
e2e: travis is not failing properly

### ISSUE THREAD

**Issue by DevVersion** [angular/material2#655]
The current E2E mode inside of the Travis CI is currently failing, but it seems like the error codes are not transferred properly

See example build:
-  https://travis-ci.org/angular/material2/jobs/136121315

**Comment by sendilkumarn** [comment]
is this travis issue or mine? @DevVersion

**Comment by DevVersion** [comment]
@sendilkumarn No, this is a general issue ( I just used your Travis Build, because I had it opened)

**Comment by jelbourn** [comment]
Investigated this- found that it's actually a bug in the CLI: https://github.com/angular/angular-cli/issues/1017

There's a fix pending: https://github.com/angular/angular-cli/pull/1025
