### ISSUE TITLE
[Table] table not showing until filter input is focused

### ISSUE THREAD

**Issue by gioragutt** [angular/material2#6553]
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

The table should load immediately as the page loads, as it has the correct data, and one of the source observables from the DataSource does emit the correct values

#### What is the current behavior?

![md-table3](https://user-images.githubusercontent.com/13711224/29489286-ce48fd20-8525-11e7-8fc4-688f4e2f3f5c.gif)

You can see that until I focus the input, MdTable does not call `DataSource.connect()`.

#### What are the steps to reproduce?

(This is the .ts file of my component)[https://github.com/gioragutt/ng2-lol/blob/master/src/app/platform-champions-table/platform-champions-table.component.ts], I follow the examples from `material.angular.io` regarding the table.

You can see that I print during the `connect` method, which only happens in the focus.
Investigating `MdTable`'s (or more correctly, `CdkTable`'s) code, I see that `connect` is called during `ngAfterContentChecked`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cli: 1.3.0
node: 8.3.0
os: win32 x64
@angular/animations: 4.3.4
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.4
@angular/language-service: 4.3.4
@angular/service-worker: 1.0.0-beta.16

#### Is there anything else we should know?

Adding another input and clicking it causes the same behavior (different trigger).  
Adding a button and clicking it does not cause the table to appear. (does not trigger the change)

**Comment by jymdman** [comment]
Probably duplicate of https://github.com/angular/material2/issues/5593
Should be fixed in master!

**Comment by gioragutt** [comment]
@jymdman good to see I didn't just miss some details. Thanks man!
