### ISSUE TITLE
Missing theming directory

### ISSUE THREAD

**Issue by Oen44** [angular/material2#6554]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Allow to make custom theme with use of **@import '~@angular/material/theming';**

#### What is the current behavior?
Missing theming directory inside **node_modules/@angular/material**

#### What are the steps to reproduce?
- Install latest version of Angular Material using **npm --save install @angular/material @angular/cdk**
- Create sample project using Angular CLI
- Create file **dark-theme.scss** in **src** directory of project
- Add dark-theme.scss to **styles array** in **.angular-cli.json**
- Append code provided at bottom of post into **dark-theme.scss**
- Add **@import 'dark-theme.scss'** into styles.css file in **src** directory
- Run **sg serve** in project root directory
- Errors appears

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "^4.3.5",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
    "@angular/cli": "1.3.1",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"

#### Is there anything else we should know?
After installing material using npm, material directory doesn't contain theming directory and it's not possible to create own theme.

My dark-theme.scss
```
@import '~@angular/material/theming';

@include mat-core();

$primary: mat-palette($mat-deep-purple);
$accent:  mat-palette($mat-amber, A200, A100, A400);

$theme: mat-light-theme($primary, $accent);

@include angular-material-theme($theme);

$dark-primary: mat-palette($mat-pink, 700, 500, 900);
$dark-accent:  mat-palette($mat-blue-grey, A200, A100, A400);
$dark-warn:    mat-palette($mat-deep-orange);

$dark-theme: mat-dark-theme($dark-primary, $dark-accent, $dark-warn);

@include angular-material-theme($dark-theme);
```

**Comment by grizzm0** [comment]
If you've already added dark-theme.scss to the styles array there's no need to import it. Also, you can not import a scss file into a css file as css does not parse scss.

Either just include the dark-theme.scss into your styles array in .angular-cli.json or import it from styles.**scss**. Your project needs to be setup to use scss instead of css in angular-cli.json for this to work.

**Comment by Oen44** [comment]
That did the trick. Docs should provide information about that. Thank you.
