### ISSUE TITLE
[mdButton] using interpolation within class break the button style

### ISSUE THREAD

**Issue by aitboudad** [angular/material2#6559]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
 using interpolation within class should not break the button style

#### What is the current behavior?
The md-button style not applied

#### What are the steps to reproduce?
```html
<button class="{{ 'test' }}" md-raised-button>Raised button</button>
```
Demo: https://stackblitz.com/edit/angular-qtykwp?embed=1&file=app/app.component.html

**Comment by crisbeto** [comment]
This isn't the correct way to bind a class. You can use `ngClass` instead:

```html
<button [ngClass]="'test'" md-raised-button>Raised button</button>
```
