### ISSUE TITLE
[MdDialog] opening multiple dialog return wrong dialogRef.

### ISSUE THREAD

**Issue by aitboudad** [angular/material2#6560]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If I open a dialog while another is in the process of being opened it should be opened and return the `dialogRef` of the requested ones

#### What is the current behavior?
The requested dialog is ignored and a return a dialogRef which not belong the the requested dialog

#### What are the steps to reproduce?

https://github.com/angular/material2/blob/master/src/lib/dialog/dialog.ts#L123-L126

**Comment by jelbourn** [comment]
@crisbeto  we should do something to make this behavior more obvious
