### ISSUE TITLE
md-radio-group radio issue with reactive form and static value

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#6561]
#### Bug, feature request, or proposal:
It seems that md-radio-group is not properly highlighting the selected radio when value of a radio button is static value instead of binding to a variable.

Please take a look at below plunker:
 
https://plnkr.co/edit/lvwBwUgAto2nHVKjjN1g?p=preview

Click "Set Option 3" button it will properly highlight the Option 3, then try Set Option 5 button, although it sets the value to Option 5 but the corresponding radio isn't selected.

**Comment by crisbeto** [comment]
That's because you have the quotes inside `value` attribute, which makes the value `'option5'` including the quotes. If you don't have a data binding, you don't need to quote the value. You can fix the issue by changing this:

```html
<md-radio-button class="example-radio-button" value="'option5'">
```

To this:

```html
<md-radio-button class="example-radio-button" value="option5">
```
