### ISSUE TITLE
[md-checkbox] breaks page reload if using pre-rendering

### ISSUE THREAD

**Issue by icehowler** [angular/material2#6562]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-checkbox should work with asp.net core 2.0 pre-rendering

#### What is the current behavior?
Only on page refresh I get following error:
`ApiScanner.Web> fail: Microsoft.AspNetCore.NodeServices[0]
ApiScanner.Web>       ERROR TypeError: Cannot read property 'trim' of undefined
ApiScanner.Web>           at Object.eval [as updateRenderer] (ng:///MdCheckboxModule/MdCheckbox.ngfactory.js:66:56)
ApiScanner.Web>           at Object.updateRenderer (D:\Projects\ApiScanner\ApiScanner.Web\ClientApp\dist\vendor.js:23671:70)
ApiScanner.Web>           at checkAndUpdateView (D:\Projects\ApiScanner\ApiScanner.Web\ClientApp\dist\vendor.js:23190:14)
ApiScanner.Web>           at callViewAction (D:\Projects\ApiScanner\ApiScanner.Web\ClientApp\dist\vendor.js:23550:21)
ApiScanner.Web>           at execComponentViewsAction (D:\Projects\ApiScanner\ApiScanner.Web\ClientApp\dist\vendor.js:23482:13)
ApiScanner.Web>           at checkAndUpdateView (D:\Projects\ApiScanner\ApiScanner.Web\ClientApp\dist\vendor.js:23191:5)
ApiScanner.Web>           at callViewAction (D:\Projects\ApiScanner\ApiScanner.Web\ClientApp\dist\vendor.js:23550:21)
ApiScanner.Web>           at execComponentViewsAction (D:\Projects\ApiScanner\ApiScanner.Web\ClientApp\dist\vendor.js:23482:13)
ApiScanner.Web>           at checkAndUpdateView (D:\Projects\ApiScanner\ApiScanner.Web\ClientApp\dist\vendor.js:23191:5)
ApiScanner.Web>           at callViewAction (D:\Projects\ApiScanner\ApiScanner.Web\ClientApp\dist\vendor.js:23550:21)`

#### What are the steps to reproduce?
1. Create a new asp.net core 2 project with angular template.
2. Import MdCheckboxModule in app.module.shared.ts
3. Use md-checkbox component on a html
4. After accessing page try reload it

**Comment by crisbeto** [comment]
Fixed in master by https://github.com/angular/material2/pull/5470.

**Comment by icehowler** [comment]
Do you have any clue when new version will be released?

**Comment by crisbeto** [comment]
I'm not sure, but you can install the latest master build from the [material2-builds repo](https://github.com/angular/material2-builds) which includes the fix.
