### ISSUE TITLE
[Proposal] [Tabs]: Expose MdTabHeader in the MdTabGroup

### ISSUE THREAD

**Issue by ktersius** [angular/material2#6569]
#### Proposal:
 Expose the MdTabHeader component in the MdTabGroup component.
#### What are the steps to reproduce?

This would be extremely easy to accomplish. 

Just add the following line in the MdTabGroup component.
```typescript
 @ViewChild(MdTabHeader) tabHeader: MdTabHeader;
```

#### What is the use-case or motivation for changing an existing behavior?

This would allow using properties like [scrollDistance ](https://github.com/angular/material2/blob/master/src/lib/tabs/tab-header.ts#L313)to be able to control scrolling via external events like mouse drag or touch device pan.

We would like to make the tab headers drag able as this is a much quicker way of navigating a tab control with many tabs. Mostly for touch devices.

**Comment by josephperrott** [comment]
As `MatTabHeader` is an internal component we will not be exposing it.  However, #6294 will add the drag you mentioned.
