### ISSUE TITLE
The result is not display into Angular Material 2 table immediately 

### ISSUE THREAD

**Issue by zhengye1** [angular/material2#6576]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The result that come back from backend should return to front end immediately

#### What is the current behavior?
I using chrome to test, the result is not displayed in the home page in material table immediately. It will display the result after I switch another tab, and I come back to original tab 

#### What are the steps to reproduce?
My full code is in https://github.com/zhengye1/Eatr/tree/dev
Since I am using Spring boot for backend, for testing purpose, after clone the code, please change the lat/lon that using your current lon/lat in following 4 lines in import.sql file
" insert into address (address, city_id, postal_code, latitude, longitude) values ('2803 Eglinton Ave E', 1, 'M1J 2E1', 43.737245, -79.244367);
insert into address (address, city_id, postal_code, latitude, longitude) values ('7010 Warden Ave', 3, 'L3R 5Y3', 43.85939, -79.304654);
insert into address (address, city_id, postal_code, latitude, longitude) values ('332 Spadina Ave', 2, 'M5T 2G2', 43.65406, -79.398905);
insert into address (address, city_id, postal_code, latitude, longitude) values ('193 Carlton St', 2, 'M5A 2K7', 43.663494, -79.370644);
"
Then run the com.vincent.eatr.EatrApplication.java file (Or using eclipse to start the backend)

Then go to front end folder, start the front end by typing "npm start". 

Once front end started, in chrome, type "http://localhost:4200", it will asking your current location, allow it, and you will see the result is not display in the home page.  Once you switch to another tab, and back to the original tab, the result is displayed.

#### Providing a Plunker (or similar) is the *best* way to get the team to see your issue. Plunker template: https://goo.gl/DlHd6U
Since it involved backend with geolocation service, the best way I can do is provide my full code on github and test.

#### What is the use-case or motivation for changing an existing behavior?
The purpose I want to do is, once user visit the home page of my web app, it will displayed the restaurant that near user's location immediately, but right now user need to do one more extra step to see the result.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular-Cli : 1.2.4
Typescript:  2.3.3
browsers: Chrome

**Comment by willshowell** [comment]
Sound like https://github.com/angular/material2/issues/5593 which has been fixed on master

**Comment by jelbourn** [comment]
Closing based on comment from @willshowell
