### ISSUE TITLE
Semantic UI Calendar does not respond in createdRow callback of DataTable

### ISSUE THREAD

**Issue by dayton-outar** [angular/material2#6577]
#### Bug, feature request, or proposal:
I'm using the semantic ui calendar within datatables.net plugin. When loading an array of objects, the calendar works as expected.

The calendar exhibits unexpected behaviour when the DataTables().row.add(object).draw() function is called. After adding the first object, the calendar works as expected. After adding more objects, only the last row with the calendar works (i.e. the popup suggestions show). The other rows before the last one, do not respond to click event.

See snippet of code below,
`    $('#tbl-work-roster').DataTable({
      processing: true,
      filter: false,
      serverSide: false,
      autoWidth: false,
      destroy: true,
      deferLoading: 0,
      stateSave: true,
      language: {
        emptyTable: 'No roster',
        info: '_START_ to _END_ of _TOTAL_',
        infoEmpty: '',
        lengthMenu: '_MENU_',
        paginate: {
          previous: '<i class="left chevron icon"></i>',
          next: '<i class="right chevron icon"></i>'
        },
        aria: {
          paginate: {
            previous: 'Previous',
            next: 'Next'
          }
        }
      },
      columns: [
        {
          data: null,
          title: 'Person',
          orderable: false,
          width: '30%',
          render: function (data, type, full, meta) {
            var personName = data.PersonSkillset.Person.FirstName !== '' ? (data.PersonSkillset.Person.FirstName + ' ' + data.PersonSkillset.Person.LastName) : ''
            return '<div class="ui input"><input name="roster-person" type="text" value="' + personName + '" placeholder="Enter Full Name"></div>'
          }
        },
        {
          data: null,
          title: 'Skill',
          width: '30%',
          render: function (data, type, full, meta) {
            return '<div class="ui input"><input name="roster-skill" type="text" value="' + data.PersonSkillset.Skillset.Name + '" placeholder="Enter skill"></div>'
          }
        },
        {
          data: null,
          title: 'Day',
          width: '15%',
          render: function (data, type, full, meta) {
            /*
            switch (data.Day) {
              case 0:
                return 'Sunday'
              case 1:
                return 'Monday'
              case 2:
                return 'Tuesday'
              case 3:
                return 'Wednesday'
              case 4:
                return 'Thursday'
              case 5:
                return 'Friday'
              case 6:
                return 'Saturday'
            }
            */
            return '<select name="roster-ddl-day" class="ui dropdown"><option value="">-- Any Day --</option><option value="0">Sunday</option><option value="1">Monday</option><option value="2">Tuesday</option><option value="3">Wednesday</option><option value="4">Thursday</option><option value="5">Friday</option><option value="6">Saturday</option></select>'
          }
        },
        {
          data: null,
          title: 'Start',
          width: '10%',
          render: function (data, type, full, meta) {
            return '<div class="ui calendar" name="start-shift"><div class="ui input left icon"><i class="time icon"></i><input name="starts" type="text" value="' + moment(data.Start, 'H:mm:ss').format('h:mm A') + '" placeholder="Begin"></div></div>'
          }
        },
        {
          data: null,
          title: 'Finish',
          width: '10%',
          render: function (data, type, full, meta) {
            return '<div class="ui calendar" name="finish-shift"><div class="ui input left icon"><i class="time icon"></i><input name="finishes" type="text" value="' + moment(data.Finish, 'H:mm:ss').format('h:mm A') + '" placeholder="End"></div></div>'
          }
        },
        {
          data: null,
          title: '',
          width: '5%',
          render: function (data, type, full, meta) {
            return '<a name="delete-roster" class="ui icon red button"><i class="trash icon"></i></a>'
          }
        }
      ],
      order: [[0, 'asc']],
      createdRow: function (row, data, dataIndex) {
        $('select[name=roster-ddl-day]', row).dropdown()

        console.log($('div[name=start-shift]', row), dataIndex)

        $('div[name=start-shift]', row).calendar({
          type: 'time',
          endCalendar: $('div[name=finish-shift]', row)
        })

        $('div[name=finish-shift]', row).calendar({
          type: 'time',
          startCalendar: $('div[name=start-shift]', row)
        })

        $('a[name=delete-roster]', row).click(function (e) {
          e.preventDefault()
          $('#tbl-work-roster').DataTable().row(row).remove().draw()
        })
      },
      rowCallback: function (row, data) {
      },
      drawCallback: function (settings) {
        // console.log(settings)
      },
      initComplete: function (settings, json) {
      }
    })`

I'm using Semantic UI version 2.2.11 with Semantic UI Calendar version 0.0.8.

The version of datatables.net is 1.10.15

I'm going to dive into the calendar.js source but I would like some help to get past this hurdle as soon as possible.

**Comment by jelbourn** [comment]
Wrong repo? I have no idea what you're talking about.
