### ISSUE TITLE
Trouble starting demo-app

### ISSUE THREAD

**Issue by BenRacicot** [angular/material2#6579]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`npm run demo-app` command should start the app at localhost:4200

#### What is the current behavior?
Various NPM errors starting with: `Error: Cannot find module 'gulp-conventional-changelog'`

#### What are the steps to reproduce?
clone the repo https://github.com/angular/material2.git and run the command

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
beta.8 master

#### Is there anything else we should know?
I completely removed the repo and re-cloned it to make sure I hadn't affected the codebase.

UPDATE: please delete I figured it out and it was my error! Thanks.

**Comment by jelbourn** [comment]
@BenRacicot FYI you can close your own issues

**Comment by JiboStore** [comment]
I still can't figure out how to run the demo-app! Please tell me, or update the documentation!

I run `npm install` then `ng serve --open` in the various folders and all I got is errors!
