### ISSUE TITLE
Button-toggle not aviable in npm

### ISSUE THREAD

**Issue by Natanael1234** [angular/material2#658]
Cannot find button-toggle in npm repository:

 https://www.npmjs.com/~angular2-material

**Comment by DevVersion** [comment]
According the release process, this should be available within Alpha 6.
- https://github.com/angular/material2/milestones

**Comment by jelbourn** [comment]
@Natanael1234 it is not done and has not been released yet.

**Comment by drager** [comment]
@DevVersion, @jelbourn: It's not released in alpha 6 yet? When is it expected to be released?
