### ISSUE TITLE
[sidenav/drawer] Dynamic width

### ISSUE THREAD

**Issue by Nodarii** [angular/material2#6583]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
I expect `.mat-drawer-content` to change `margin` value after I change `width` on `<md-drawer>`

#### What is the current behavior?
`<md-drawer>` Has no API for dynamic width change

#### What are the steps to reproduce?
http://plnkr.co/edit/GHUPDReRi9AbQM3En3Re?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I want to allow my users change sidebar width while it is opened.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.2.7
node: 8.2.1
os: win32 x64
@angular/animations: 5.0.0-beta.2
@angular/cdk: 2.0.0-beta.8-5e3228f
@angular/common: 5.0.0-beta.2
@angular/compiler: 5.0.0-beta.2
@angular/core: 5.0.0-beta.2
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 5.0.0-beta.2
@angular/http: 5.0.0-beta.2
@angular/material: 2.0.0-beta.8-5e3228f
@angular/platform-browser: 5.0.0-beta.2
@angular/platform-browser-dynamic: 5.0.0-beta.2
@angular/platform-server: 5.0.0-beta.2
@angular/router: 5.0.0-beta.2
@angular/cli: 1.2.7
@angular/compiler-cli: 5.0.0-beta.2

#### Is there anything else we should know?
##Does such API makes sense at all?

P.S it worked in that way in previous versions

**Comment by adrm** [comment]
I can reproduce this issue in the latest @angular/material@2.0.0-beta.10. Hope you can fix it. Thanks!

**Comment by SpiderPork** [comment]
I can reproduce this issue with beta 10.

**Comment by adrm** [comment]
I think this can be closed as duplicate of #6743

**Comment by Nodarii** [comment]
deal, lets track this issue there
