### ISSUE TITLE
custom input validator function example contains syntax error and is unclear

### ISSUE THREAD

**Issue by michahell** [angular/material2#6585]
the following example, here:
https://material.angular.io/components/input/overview
located under **Custom Error Matcher** contains one too many right brackets
and on top of that, is unclear:

```javascript
function myErrorStateMatcher(control: FormControl, form: FormGroupDirective | NgForm): boolean {
  // Error when invalid control is dirty, touched, or submitted
  const isSubmitted = form && form.submitted;
  return !!(control.invalid && (control.dirty || control.touched || isSubmitted)));
}
```

why not just use:
```
return control.invalid && (control.dirty || control.touched || isSubmitted);
```

?

**Comment by willshowell** [comment]
Good catch on the extra right parentheses.

For the boolean coercion, that example was based on the existing default matcher. It originates from https://github.com/angular/material2/pull/3560/commits/42dab5e5aa1aa1e4ebed550672c85dc6e713009f#r106483976.

**Comment by michahell** [comment]
But why is coercion necessary? does `&&` not already do that ? or is there some javascript [wat](https://www.destroyallsoftware.com/talks/wat) involved if any of the `control.dirty` or other properties are not booleans? if so, `wat`.

**Comment by willshowell** [comment]
Yeah I think in this case it is not actually necessary (maybe just for safety?). `&&` uses the last value, but as long as `dirty`, `touched`, and `submitted` are all boolean, there should be no need to coerce it.

```
> 1 && true
true

> true && 1
1

> !!(true && 1)
true
```

**Comment by michahell** [comment]
A case of `wat`, it was, then :) I unconsciously knew this about `&&`, but only now realise that coercing might sometimes be necessary, thanks!
