### ISSUE TITLE
Last build changes in .mat-figure style

### ISSUE THREAD

**Issue by lutchit** [angular/material2#6586]
Hello team,

#### Bug, feature request, or proposal:
Question

#### What is the expected behavior?
In the last release (2.0.0-beta.8), in the ```.mat-figure``` style configuration we have
```
top: 0;
right: 0;
bottom: 0;
left: 0;
```

#### What is the current behavior?
In the last build I test, style configuration (only for top, right, bottom and left) is missing. Is this normal?

#### What are the steps to reproduce?
Use last available build.

#### What is the use-case or motivation for changing an existing behavior?
I'm a little bit worry if in the next release a lot of people will be surprised by this change.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Last build

#### Is there anything else we should know?

I hope my message is not spam, but I need some new functionalities of the latest build but it changes some design features of my website and I would like to know why those changes have been done.

Thanks.

**Comment by willshowell** [comment]
For reference,

beta.8: https://plnkr.co/edit/xLFDhss37qVGg0agTFtK?p=preview
master: https://plnkr.co/edit/bgkNSnKEUIpIxfWkauzA?p=preview

@crisbeto the change was made in https://github.com/angular/material2/pull/6486. Was the uncentering of content intentional?

**Comment by crisbeto** [comment]
The changes from https://github.com/angular/material2/pull/6486 are equivalent to the old styling. If you take a look at the [`mat-fill` mixin, it adds the exact same styles.](https://github.com/angular/material2/blob/da7cb2dc995e5c2bc61df49b5939f7de5543b07d/src/lib/core/style/_layout-common.scss#L2) As for the uncentering, I'm not quite sure what introduced it, but it should be fixed by https://github.com/angular/material2/pull/6578.

**Comment by willshowell** [comment]
I think [here](https://github.com/angular/material2/pull/6486/files#diff-31146fa6ad3bbd544f115abaf344887f) you can see that the top/bottom/right/left styles were removed from `.mat-figure` and added to the parent `.mat-grid-tile` instead. In any case, #6578 looks like a fine solution.

**Comment by willshowell** [comment]
Further I think adding `mat-fill` to `.mat-grid-tile` doesn't make sense since the tile is repositioned with inline styles. The `.mat-fill` styles get overridden any way.

**Comment by crisbeto** [comment]
Oh, that feels more like a typo. I'll update #6578.
