### ISSUE TITLE
MdSlider update ngModel on slide event

### ISSUE THREAD

**Issue by jans-y** [angular/material2#6593]
#### Bug, feature request, or proposal:

I would love to have ngModel updated on the slide with optional debounce time, please have a look at the Ionic slider:

http://ionicframework.com/docs/api/components/range/Range/

#### What is the expected behavior?

Have the option to have ngModel updated on the slide event.

#### What is the current behavior?

ngModel updates only on change event.

#### What is the use-case or motivation for changing an existing behavior?

Provide better UX and feedback to the user.

**Comment by jans-y** [comment]
Okay. It is possible with (input) attribute directive.

I definitely miss this in the Documentation.

Solution:
<md-slider (input)="bindingValue = $event.value" ..... >

But debounce function would be still nice.

**Comment by willshowell** [comment]
I think debouncing should be left up to the user. Here's an example

https://plnkr.co/edit/IkFgDkXcH6aroqxWmK6b?p=preview

**Comment by jans-y** [comment]
Nice, thank you very much.

I have solved it my self with creating new component with ChangeDetectionStrategy.OnPush while automatically calling setInterval refreshing numbers - that solution eliminates unnecessary running of the function I wanted to debounce.
