### ISSUE TITLE
Plunker template is broken

### ISSUE THREAD

**Issue by filipows** [angular/material2#6595]
Plunker template is broken:

![screenshot from 2017-08-23 11-05-38](https://user-images.githubusercontent.com/884847/29597159-66c9e79c-87f3-11e7-888b-d6d78d9b881c.png)

Link to Plunker: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

**Comment by willshowell** [comment]
Until it's fixed, the following should work

http://plnkr.co/edit/tNFOkVcXvN1FtL9elPlq?p=preview

**Comment by DevVersion** [comment]
Fixed. Thanks @willshowell
