### ISSUE TITLE
Nested md-table inside md-table

### ISSUE THREAD

**Issue by qiubus** [angular/material2#6597]
**Question, feature request, or proposal:**
Is there any way to create nested md-table inside md-table?
Maybe somehow by customizing md-row?
I was not able to find any such example.

**Which versions of Angular, Material?**
I use Angular 4.2.4 and Angular Material 2.0.0-beta.8. 

**What is the expected behavior?**
To achieve something similar to this:
![image](https://user-images.githubusercontent.com/31270838/29603369-4002e42e-87e4-11e7-9757-2c599d8bedb8.png)

**Comment by jelbourn** [comment]
Due to the way it's built, it's impossible to put one table inside of another. We have no plans to ever change this.

**Comment by amejiarosario** [comment]
@jelbourn Do you have any pointers to somebody willing to extend tables to accomplish this?

**Comment by andrewseguin** [comment]
Unfortunately the mechanics of the table makes assumptions that there are no nested tables. In particular, it assumes that cells are created in a particular order, which would break if recursion is introduced.
