### ISSUE TITLE
Run Closure Compiler over codebase on CI

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#660]
We need to run our code through the Closure Compiler on CI so that we know if any change will introduce a problem for Google projects consuming material2. This is currently blocked on work being done on to Angular's [tsc-wrapped](https://www.npmjs.com/package/@angular/tsc-wrapped)

**Comment by DevVersion** [comment]
Let's merge this issue into https://github.com/angular/material2/issues/1206
