### ISSUE TITLE
Position absolute in dialog overlays

### ISSUE THREAD

**Issue by CDDelta** [angular/material2#6602]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Being able to use position absolute in dialog overlays and have full scale divs be limited to the size of the dialog.

#### What is the current behavior?
Currently divs with position absolute will fill up the entire screen when expanded fully.

#### What are the steps to reproduce?
http://plnkr.co/edit/LYv4q6mcPakbSaW4xeGn?p=preview 
Plunkr material2 build does not seem to be working however this demonstrates what I am trying to do.
Changing position on #cdk-overlay-0 to absolute gets me the behaviour I need.

#### What is the use-case or motivation for changing an existing behavior?
Is there a specific reason to use static for positioning dialog overlays? I am trying to add a loading shade on top of a dialog however the div and background overflows out of the dialog and on to the entire screen as position static is used, changing this to position absolute works though.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material2-beta.8

**Comment by CDDelta** [comment]
This specific line here
https://github.com/angular/material2/blob/0db3635f0165b37803fdc2ceee4a0452bb580d50/src/cdk/overlay/position/global-position-strategy.ts#L23

**Comment by crisbeto** [comment]
The Plunkr doesn't seem to load, but the reason we're using `position: static` is because we center the dialog using flexbox. We're not using `absolute` and transforms, because they end up blurring the content. As for having something with `position: absolute` inside the overlay, that should be easily achievable by setting `position: relative` instead of static.

**Comment by CDDelta** [comment]
@crisbeto the Plunkr not working seems to have something to do with @angular/cdk/collections. Position relative in place of static works as expected. Should I open up a PR for this or implement my own PositionStrategy? I expect being able to use position absolute within a dialog would be a useful feature out of the box.

**Comment by jelbourn** [comment]
There should be nothing stopping you from adding a `position: relative` element inside the dialog and then `position: absolute` elements inside of that.
