### ISSUE TITLE
Unit tests for md-card component

### ISSUE THREAD

**Issue by m0t0r** [angular/material2#662]
First of all, I want to use this opportunity to thank you for the amazing work on Material 2 components! You guys are doing incredible work! Keep it up!

As it's recommended before creating any PR, I would like to ask if there is a particular reason for md-card component be without unit tests. I've created a similar custom component and wanted to get an idea about testing but didn't find unit tests for md-card. Could you please give some information about it ?

**Comment by jelbourn** [comment]
Cards don't have any behavior _to_ test.
