### ISSUE TITLE
hide/delete underline input

### ISSUE THREAD

**Issue by PatrickCharriere** [angular/material2#6623]
### Bug
`
Property 'underlineRef' does not exist on type 'MdInputDirective'
`

However, underlineRef property exists if we log this  MdInputDirective:

![angularerror](https://user-images.githubusercontent.com/10613478/29670471-056d3bee-88e7-11e7-9259-8501a34bec69.PNG)
#### Expected behavior
```ts
@ViewChild('input') input: MdInputDirective;

ngOnInit(): void {
  this.input.underlineRef.nativeElement.className = null;  // Removes the input underline 
}
```

#### What is the current behavior?
Compilation error

#### What are the steps to reproduce?
Link of a discussion on the issue:
https://stackoverflow.com/questions/45556972/how-to-hide-delete-underline-input-angular-material 

##### Workaround
```ts
@ViewChild('input') input: MdInputDirective;

ngOnInit(): void {
  this.input['underlineRef'].nativeElement.className = null;  // Remove the input underline 
}
```

**Comment by willshowell** [comment]
Reproduction? This working example is from that SO conversation: 

https://plnkr.co/edit/XMhDIVBDup29sM8oi2dL?p=preview

**Comment by gise88** [comment]
@willshowell I had the same problem and I have archived this with `ViewEncapsulation.None`. What do you recommend? 
https://plnkr.co/edit/Xxe8Wyv0141Ewxgcij4s?p=preview

**Comment by willshowell** [comment]
Personally I'd opt for using css and leaving the `underlineRef` alone. I think the only reason it is exposed is for the datepicker to have a reference element to attach to, and I could easily see it going away or becoming internal-use-only.

I'd suggest a slight variation of your plunk:

```scss
// in global stylesheet
.mat-input-container.app-input-no-underline .mat-input-underline {
  display: none;
}
```

```html
<md-input-container [class.app-input-no-underline]="!showUnderline">
  <input mdInput>
</md-input-container>
```

https://plnkr.co/edit/S8vHnOuzr6l6tYiMOnmi?p=preview

By adding it to a global stylesheet, you can keep view encapsulation on for your component.

**Comment by gise88** [comment]
> Personally I'd opt for using css and leaving the underlineRef alone

Yep, I think the same.

And thanks for your tip! You are absolutely right
