### ISSUE TITLE
Change in the material design spec

### ISSUE THREAD

**Issue by Tetrygon** [angular/material2#6624]
#### Bug, feature request, or proposal:
Yes..

Inputs have changed in the material design spec. For instance, textareas now include a border.

Labels now replace placeholders and placeholders are something a bit different. (Issue #6240)

Found here:
https://material.io/guidelines/components/text-fields.html#text-fields-field-types

**Comment by willshowell** [comment]
Dupe of https://github.com/angular/material2/issues/3984

**Comment by jelbourn** [comment]
Duplicate of #3984
