### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by malikfaizanhaider** [angular/material2#6626]
Hi Team,

My suggestion is, google card slider (carousel) should be available in material2 with draggable functionality .

Thanks 

![google google search](https://user-images.githubusercontent.com/4697658/29679048-1c9dcbb6-891a-11e7-92d5-06950e18e5e3.jpg)

**Comment by donroyco** [comment]
1. Please use the issue template.
2. Please use the search function preventing duplicate entries (see #5671, #5693, #1081).
3. There will be no carousel component, as stated by @jelbourn in #5671 :
> We have no plans to add any kind of carousel component.

**Comment by malikfaizanhaider** [comment]
Any draggable functionality for an object???

**Comment by jelbourn** [comment]
Closing re everything @donroyco said
