### ISSUE TITLE
Input with md-datepicker does not validate correctly

### ISSUE THREAD

**Issue by rasert** [angular/material2#6629]
#### Bug, feature request, or proposal:
Bug.

I have a custom validator that checks for date periods. The initial date can't be newer than the final date.

When I click on the button to pick a date, the validation message (md-error) do not appear. But if I click on the input and leave, then it triggers the validation and the error message appears.
Once it appears, I am unable to make it go away.

So it seems that when I'm using md-datepicker, the validation mechanism doesn't work properly.

#### What is the expected behavior?
Trigger validation on md-datepicker button click and be able to correct the field and make the error message disappear.

#### What are the steps to reproduce?
Just put two fields in a reactive form, one for initial date and another for final date, and use this custom validator:

    `static checkPeriod(AC: AbstractControl) {
        let initialDate = AC.get('initialDate').value as Date;
        let finalDate = AC.get('finalDate').value as Date;

        if (!initialDate || !finalDate) return null;
        if (initialDate <= finalDate) return null;

        if (initialDate > finalDate) {
            AC.get('initialDate').setErrors({ checkPeriod: true });
            AC.get('finalDate').setErrors({ checkPeriod: true });
        }
     }`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.5
Material 2.0 Beta 8

**Comment by willshowell** [comment]
Can you post a plunker reproduction? As far as your code sample shows, you are never setting the `checkPeriod` error to `false`...

**Comment by uncledent** [comment]
This is actually a problem, this doesn't work as well:

`export class DatesValidation {
  static StartBeforeEnd(AC: AbstractControl) {
    const startDate = AC.get('startDate').value; 
    const endDate = AC.get('endDate').value; 
    if (startDate > endDate) {
      AC.get('endDate').setErrors({ startBeforeEnd: true });
      AC.get('endDate').markAsDirty();
      AC.get('endDate').markAsTouched();
    } else {
      AC.get('endDate').setErrors({ startBeforeEnd: false });
      return null;
    }
  }
}
`

if you set f.g. 

`AC.get('endDate').setErrors(undefined)
`
then it works, overriding all the errors of course...

**Comment by willshowell** [comment]
I'm afraid I still don't follow the problem.

We implemented an `EndAfterStart` validator that sets errors on the form group (contains the start date and end date controls and a few others). This is fine for invalidating the form, but Material errors will only show if the actual control is invalid. To override the default logic for when `md-error` will show up, you can use an [`errorStateMatcher`](https://material.angular.io/components/input/overview#custom-error-matcher) to configure it to respond to form group validation errors. You can even ignore whether either of the controls are touched if you need.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
