### ISSUE TITLE
Animations on leave not working after using Autocomplete

### ISSUE THREAD

**Issue by filipows** [angular/material2#6632]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Animations should run as usual, no matter if you used autocomplete before
![ok](https://user-images.githubusercontent.com/884847/29696793-b2545dba-897d-11e7-9ff1-1c02da02d1e2.gif)

#### What is the current behavior?
After opening autocomplete animations for leaving element are not working and element is being removed instantly.
![bug](https://user-images.githubusercontent.com/884847/29696799-b67cee48-897d-11e7-8a7e-ad16a98991c9.gif)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-pc5yuw

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 - Angular 4.3.4
 - Material 2.0.0-beta.8
 - Chrome Version 59.0.3071.115 (64-bit)

**Comment by josephperrott** [comment]
It looks like this issue is no longer occurring as seen [here](https://stackblitz.com/edit/angular-5m5bra)
