### ISSUE TITLE
md-errors disable container's input error requirement to display option

### ISSUE THREAD

**Issue by Shiso** [angular/material2#6639]
#### Bug, feature request, or proposal:

i fought i was facing #4027 but **it seems that a md-error is only showed when the md-input-container's input is itself invalid**.

I have **multiple fields depending on the process over one**, and wished to display each errors of theses fields (). 

It makes sense, but at the same time an option to disable this condition would help me a lot.

#### What are the steps to reproduce?

Here is a working plunker to present the issue: http://plnkr.co/edit/3ZYCiYeVo2QITpuQf0R0?p=preview

#### What is the use-case or motivation for changing an existing behavior?

search input through google places and lat/lng population has an example, or any displayed input with only front end motives to be processed over user's actions.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I would say any, but i only tested on recent versions

#### Is there anything else we should know?

I should add that i am a beginner in angular / material, i love it so far and search for the best solution but i missed something please give me a hint !

**Comment by willshowell** [comment]
I don't really follow your plunker example, but I think you might be looking for a [Custom Error Matcher](https://material.angular.io/components/input/overview). By default, errors won't show until the input has been _touched_, so if you want them to display at other times, you'll have to specify when in the matcher function.

If that's not what you're looking for, could you explain further and simplify your example?

**Comment by Shiso** [comment]
Ho wow, how did i missed that ? And i've just read again my example, it's unclear and with a lot of useless parts.
I've checked your solution and it seems to offer exactly what i need.

so sorry for this post, is there a blackhole for this kind of "questions" ? ^^'
