### ISSUE TITLE
Active tab dont work inside ng-content with *ngIf

### ISSUE THREAD

**Issue by luizotcarvalho** [angular/material2#6642]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Show the first tab active, and the respective content when the component appear on screen.

#### What is the current behavior?
The content is showed but with no underline style indicating the active tab

#### What are the steps to reproduce?

Here is a plunker with the issue: http://plnkr.co/edit/yRlZUWIkGACSKzFVxZMw?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Its not clear what tab is active

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    "@angular/animations": "^4.3.5",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",

#### Is there anything else we should know?
no

**Comment by julianobrasil** [comment]
While you wait for a decent solution, you can use this ugly workaround: http://plnkr.co/edit/nQssK0jD3Lq1yJ73QOjn?p=preview 😞

**Comment by josephperrott** [comment]
Closing as duplicate of #5269

**Comment by ImranAhmed** [comment]
I'm seeing this exact issue in '"@angular/material": "^5.2.1"'

Is there a fix for this? I don't fancy the workaround shown above.

**Comment by julianobrasil** [comment]
Take a look at #5269.
