### ISSUE TITLE
npm install fails because of unmet dependency angular/cdk

### ISSUE THREAD

**Issue by AnuradhaK** [angular/material2#6647]
#### Bug, feature request, or proposal:

When i try doing npm install on my angular js 2 project folder it throws the below 
npm ERR! 404 Not Found: @angular/cdk@^2.0.0-beta.8

Tried doing npm install @angular/cdk but failed

#### What is the expected behavior?

npm install to be successful and can use ng serve and ng start to use the application.

#### What is the current behavior?
npm install unsuccessful.

#### What are the steps to reproduce?
{
  "name": "ng-books",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.1",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/platform-server": "^4.3.1",
    "@angular/router": "^4.2.4",
    "@angular/service-worker": "^1.0.0-beta.16",
    "core-js": "^2.4.1",
    "enhanced-resolve": "3.3.0",
    "ng-pwa-tools": "^0.0.15",
    "rxjs": "^5.4.1",
    "zone.js": "^0.8.12"
  },
  "devDependencies": {
    "@angular/cli": "1.3.0-beta.0",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

is the package.json file.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
node version being used is : 4.4.5

**Comment by julianobrasil** [comment]
[Angular docs](https://angular.io/guide/quickstart) says that node version must be 6.9.x. Have you tried to upgrade it?

**Comment by DevVersion** [comment]
I was not able to reproduce this issue.
