### ISSUE TITLE
Add documentation for cdkScrollable and ScrollDispatcher

### ISSUE THREAD

**Issue by mackelito** [angular/material2#6648]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
To have a service that handles the adding of scroll eventlisteners.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Due to the html/css layout scrolling does not occur on the body so eg. the mobile browser feature of when scrolling the menu/adressbar gets a minimalistic UI or disappears does not work.

Also this could be a great performance improvement in many apps as attaching listeners to scroll in multiple components/services is common and quite costly in terms of performance.

Perhaps this could be done within the CDK?

**Comment by crisbeto** [comment]
It's not very well documented, but the ScrollDispatcher service does this already: https://github.com/angular/material2/blob/master/src/cdk/scrolling/scroll-dispatcher.ts

**Comment by jelbourn** [comment]
Yep, it's part of the cdk that we don't have full docs for yet

**Comment by jelbourn** [comment]
This is now done.
