### ISSUE TITLE
[Bug-MdIconRegistry] Cannot set an app-wide default icon font set.

### ISSUE THREAD

**Issue by dpurp** [angular/material2#665]
#### Bug, feature request, or proposal:
Bug: the default font set for the MdIconRegistry is per instance rather than a static, app-wide default.

#### What is the expected behavior?
The value set in MdIconRegistry#setDefaultFontSetClass in the app's ngOnInit should be persisted through the app.

#### What is the current behavior?
The default class needs to be set in every component.

#### Which versions of Angular, Material, OS, browsers are affected?
angular2-material 2.0.0-alpha.5

#### Possible solution
Move the _defaultFontSetClass outside of the MdIconRegistry class into the module scope.
https://github.com/angular/material2/blob/master/src/components/icon/icon-registry.ts#L79

**Comment by jelbourn** [comment]
The `MdIconRegistery`, like most services, should only be provided (and configured) once at the root of the application and then just injected into individual components.
