### ISSUE TITLE
[Feature] Menu

### ISSUE THREAD

**Issue by DerekTBrown** [angular/material2#666]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Implement Menu as in Angular Material(1) 

#### What is the current behavior?
Currently not implemented in Angular Material 2

I need the Menu feature of Angular Material to be implemented for an application that I am working on.  I would be interested in developing it- but I want to be sure that others are not already working, and if there are other things I need to know in regard to the development roadmap.

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/119

**Comment by DerekTBrown** [comment]
Similar question of Dialog boxes- have those been written yet?

**Comment by fxck** [comment]
and similar answer https://github.com/angular/material2/issues/114 you should really try the search function, it's incredible.

**Comment by jelbourn** [comment]
#119
