### ISSUE TITLE
Can you provide more details regarding DatePicker localization?

### ISSUE THREAD

**Issue by ayyash** [angular/material2#6662]
#### documentation request:
The documentation here: https://material.angular.io/components/datepicker/overview
Under **Localizing labels and messages**
Kind of falls short of elaborating, I have been searching the web up and down looking for clues, would appreciate at least pointers to where to look

**Comment by peymanebrahimi** [comment]
this may be helpful:
https://blog.angular.io/taking-advantage-of-the-angular-material-datepicker-237e80fa14b3
