### ISSUE TITLE
Wave effect animation wont work

### ISSUE THREAD

**Issue by inlinex** [angular/material2#6667]
I'm recently install material on my project as said on material official web, but the wave effect won't work.
this is the description of _ng --version_ 
**@angular/cli: 1.3.2
node: 6.9.1
os: win32 x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6**

**Comment by donroyco** [comment]
1. I think you mean the *ripple* effect.
2. Please use the issue template and provide a reproduction of your issue. Otherwise this thread will get closed.
