### ISSUE TITLE
Checkbox readonly

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#6669]
#### Bug, feature request, or proposal:
The checkbox should have a readonly property

#### What is the expected behavior?
Should behave the same as a native checkbox.

#### What is the current behavior?
Only allows disabled state, which causes a null value in reactive forms.

#### What is the use-case or motivation for changing an existing behavior?
Sometimes a checkbox must not be changed by the user but still keep its value.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 4.x, beta.8

#### Is there anything else we should know?
No :-)

**Comment by donroyco** [comment]
> **[readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) `HTML5`**
This attribute indicates that the user cannot modify the value of the control. The value of the attribute is irrelevant. If you need read-write access to the input value, do not add the "readonly" attribute. **It is ignored if the value of the type attribute is hidden, range, color, checkbox, radio, file, or a button type (such as button or submit).**

It will be ignored, so no need for it on a checkbox.

**Comment by mbeckenbach** [comment]
@donroyco thx for your info. 
didn't know that.
