### ISSUE TITLE
[Bug] Md-input is not hidden

### ISSUE THREAD

**Issue by Leonzen** [angular/material2#6672]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If the input field is set hidden it should disappear.

#### What is the current behavior?
If the input field is set hidden, the input field itself is hidden but everything else, like the md-underline are still there.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-tcqfow

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.3.5
Material: 2.0.0-beta.8
OS: Windows 7
TypeScript: 2.2.0
Browser: Chrome 60

**Comment by ghd8** [comment]
dupe #2669

**Comment by jelbourn** [comment]
See #2669 and www.hidden.is.a.lie.fyi
