### ISSUE TITLE
Fab button click event occurs even [disabled] is set

### ISSUE THREAD

**Issue by dannyhchan** [angular/material2#6676]
#### Bug, feature request, or proposal:
Fab button click event fires even in disabled state

#### What is the expected behavior?
Should be like md-raised-button where click event doesn't occur when disabled is set

#### What is the current behavior?
In disabled state, the click event executes

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
When button is disabled, no events should be allowed

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, TypeScript, Chrome

**Comment by crisbeto** [comment]
Can you post your HTML? If you're using the fab on a `button` node this shouldn't be possible.

**Comment by dannyhchan** [comment]
You are correct, it was assigned on an anchor tag.  Thank you!
