### ISSUE TITLE
md-input-container: Allow setting floatPlaceholder as global default

### ISSUE THREAD

**Issue by aldo-roman** [angular/material2#6678]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
To have a global default for `floatPlaceholder` that can be overwritten on a specific input-container.
See https://material.angular.io/components/select/overview
See #4311

#### What is the current behavior?
As per #4311, once you set a Global floatPlaceholder, it applies to all input container and ignores the local `floatPlaceholder` setting

#### What are the steps to reproduce?
http://plnkr.co/edit/UkEUTIbmiwmntagPMvAp?p=preview
Global provider set to `floatPlaceholder: always`, but local `floatPlaceholder=auto` is ignored.

#### What is the use-case or motivation for changing an existing behavior?
I want *almost* any input-container to be `floatPlaceholder=always`, but need some of them to be `floatPlaceholder=never`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.3.2
node: 8.2.1
os: win32 x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.8
@angular/cli: 1.3.2
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/compiler-cli: 4.3.6
@angular/core: 4.3.6
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/language-service: 4.3.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/service-worker: 1.0.0-beta.16

#### Is there anything else we should know?
So far, I have `floatPlaceholder` all over the place :)

**Comment by willshowell** [comment]
In your plunker, you've attached `floatPlaceholder` to `MdInput` instead of `MdInputContainer`. It works correctly if you switch that.

**Comment by aldo-roman** [comment]
LOL, thanks @willshowell !
Indeed, it worked on my project, too
