### ISSUE TITLE
Cannot make the overlay-demo work 

### ISSUE THREAD

**Issue by lghinet** [angular/material2#668]
from the demo app 
`<button (click)="openRotiniPanel()">
  Pasta 1
</button>`

i`ve inserted all the directives and necessary providers 
this is my .ts file 

> import { Router } from '@angular/router-deprecated';
import {
    Component,
    ViewChildren,
    QueryList,
    ViewChild,
    ViewContainerRef
} from '@angular/core';
import {
    Overlay,
    OverlayState,
    OverlayOrigin,
    OVERLAY_PROVIDERS,
    OVERLAY_DIRECTIVES,
    ComponentPortal,
    Portal,
    PORTAL_DIRECTIVES,
    TemplatePortalDirective
} from '@angular2-material/core/core';

@Component({
    moduleId: module.id,
    selector: 'orders-history',
    templateUrl: 'orders-history.component.html',
    styleUrls: ['orders-history.component.css'],
    directives: [PORTAL_DIRECTIVES, OVERLAY_DIRECTIVES],
    providers: [OVERLAY_PROVIDERS]
})
export class OrdersHistoryComponent {
    nextPosition: number = 0;
    isMenuOpen: boolean = false;

    constructor(public overlay: Overlay, public viewContainerRef: ViewContainerRef) { }

    ngOnInit() {
        
    }

    openRotiniPanel() {
        let config = new OverlayState();

        config.positionStrategy = this.overlay.position()
            .global()
            .left(`${this.nextPosition}px`)
            .top(`${this.nextPosition}px`);

        this.nextPosition += 30;

        this.overlay.create(config).then(ref => {
            ref.attach(new ComponentPortal(RotiniPanel, this.viewContainerRef));
        });
    }
    
}

/** Simple component to load into an overlay */
@Component({
    moduleId: module.id,
    selector: 'rotini-panel',
    template: '<p class="demo-rotini">Rotini {{value}}</p>'
})
class RotiniPanel {
    value: number = 9000;
}

i get this error in chrome console  : 

_Cannot read property "parameters" of undefined ReflectionCapabilities.parameters_
tried to debug a little, and found out that the provider (OVERLAY_PROVIDERS) is null. 

i am trying to make some sort of dialog box.

**Comment by jelbourn** [comment]
The overlay exports weren't added to `core.js` until after the most recent release. Until then you can import directory:
```ts
import {OVERLAY_PROVIDERS} from '@angular2-material/core/overlay/overlay';
```

Please note that the overlay is still very much a work in progress and will be seeing a lot of changes as the library develops.
