### ISSUE TITLE
Material button hover color displayed incorrectly

### ISSUE THREAD

**Issue by nhducseuit** [angular/material2#6687]
#### Bug, feature request, or proposal:
Material button hover color displayed incorrectly

#### What is the expected behavior?
On button hover, background color of md-button should display as styled in the stylesheet.

#### What is the current behavior?
Background color set in hover action is `#e6e6e6`, but what actually displayed is `#d2d8e1` for button uses `primary` color palette, and is `#e7d8cc` for button uses `accent` color palette.
The primary default color is `#202020`, while accent default color is `#ee7617`

Somehow the actual hover colors of buttons are related to the text color of the button.

I tried with some different colors but the hover colors of buttons are always displayed wrong.

The tool I used to pick actual color displayed by browser is GPick.

#### What are the steps to reproduce?
I have created a plunker at http://plnkr.co/edit/DozKGIY1MhnfYzNjulRH
But I cannot make it working because I don't know what URL to import for material theming in the _app.theme.scss file.
Would appreciate anyone can help me correct that line.

#### What is the use-case or motivation for changing an existing behavior?
None

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.1.2
Material 2.0.0-beta.8
Tested on Chrome and Firefox, both affected.

#### Is there anything else we should know?
None

**Comment by willshowell** [comment]
This sounds more like a support question of "how to customize button background color", right?

**Comment by nhducseuit** [comment]
Probably @willshowell  :) You helped in SO already so I'll close this one.

**Comment by josephperrott** [comment]
Closing per update
