### ISSUE TITLE
Focus is lost when opening md-select options list

### ISSUE THREAD

**Issue by rubenlagus** [angular/material2#6690]
#### Bug, feature request, or proposal:
When an user opens the *md-select* options list, focus is lost from the component itself.

#### What is the expected behavior?
Focus should remain in a child of *md-select* options and events such as *focusin* or *focusout* should not be triggered since the user has not really leave the component at tall.

#### What is the current behavior?
As soon as the options list opens, focus is lost form the component containing the *md-select*.

#### What are the steps to reproduce?
Check focus log when selecting options: http://plnkr.co/uySEJGxzMTkbO6DxlT1F

#### What is the use-case or motivation for changing an existing behavior?
In order to be able to track focus events and being able to apply custom styles to a component when it is focused, it is necessary that those events allow to track when the user really leave the component and they don't trigger while the user is selecting an option inside a form (for example).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested with Angular 4.3.1, Material 2.0.0-beta.8 under Chrome.

**Comment by rubenlagus** [comment]
**Update:**
It is still happening with latest beta *2.0.0-beta.10* and Angular *4.3.6*

**Comment by willshowell** [comment]
Focus moves to the select options which, in the DOM, are in an overlay at the end of the body. What if the select component had a class like `mat-select-open` when the panel was open?

**Comment by rubenlagus** [comment]
@willshowell in my use case, I'm using a directive that use _focusin_ and _focusout_ events to add/remove styles to the whole component.  I could add a workaround to those event that also check if the `mat-select-open` is present.

I would prefer to get those event only when the actual focus is indeed moved away from the component (and yes, I know that internally in the DOM it is like that). 

What about trying to avoid the event to bubble out of the `md-select`?

**Comment by willshowell** [comment]
I see, cc @crisbeto

**Comment by crisbeto** [comment]
I'm currently working on switching `md-select` to use `aria-activedescendant` instead of moving focus. This shouldn't be an issue once that is done.
