### ISSUE TITLE
md-select change event and md-input-container visibility

### ISSUE THREAD

**Issue by vaceslav** [angular/material2#6693]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
On change event from md-select when variable "visible" is changed (in to the  true state), the md-input-container should be visible (*ngIf="visible")

#### What is the current behavior?
With Angular 4.3.5 and lower it is worked. 
With Angular 4..3.6 and above it is not worked

#### What are the steps to reproduce?

Angular 4.3.5 **Working**
https://plnkr.co/edit/Pp1jdkhZFvfH0g6zsxld?p=preview

Angular 4.3.6 **Not Working**
https://plnkr.co/edit/gv0TNhgiA8ww4eEUxyC9?p=preview

**Comment by ovoronin** [comment]
This bug affect tabs as well, tab content has css style "display: none" same as container in 2nd plunkr

**Comment by jelbourn** [comment]
Related to #6696, cc @matsko

**Comment by josephperrott** [comment]
It looks like this is resolved in the most recent release as seen [here](https://stackblitz.com/edit/angular-material2-issue-6693?file=app%2Fapp.component.ts).
