### ISSUE TITLE
md-checkbox does toggle even if return false or preventDefault on Keypress

### ISSUE THREAD

**Issue by FrancescoLeonardo** [angular/material2#6694]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
As they do on click, event.preventDefault() or return false should prevent md-checkbox to toggle state even on keypress

#### What is the current behavior?
md-checkbox state toggles when this is undesired

#### What are the steps to reproduce?
https://plnkr.co/edit/xHTSwWGT2s0b7BRTMdXy?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Implementation of the same business behavior while the user is navigating UI with mouse and keyboard

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 2 beta 8

#### Is there anything else we should know?
nope

**Comment by MA-Maddin** [comment]
use `(keydown)` instead.

**Comment by jelbourn** [comment]
@tinayuangao is this working as intended?

**Comment by tinayuangao** [comment]
@FrancescoLeonardo You can use `(keydown)` instead of `(keypress)`.

**Comment by tinayuangao** [comment]
Working as intended.
