### ISSUE TITLE
ngIf on md-input-container hides container when initially false 

### ISSUE THREAD

**Issue by bhelzer** [angular/material2#6696]
#### Bug, feature request, or proposal:

When ngIf switches to true, it creates the component, but the component includes style="display:none".

As a work around use a surrounding div or span for ngIf

#### What is the expected behavior?

It should show the component

#### What are the steps to reproduce?

http://plnkr.co/edit/9G1tmuLQPzwTsriiNITa?p=preview

**Comment by willshowell** [comment]
This seems to specifically be linked to setting the "show" value with the the select. The same behavior is not exhibited when manually setting the "show" value.

Here is a simplified plunker:
http://plnkr.co/edit/WnYkJReZOCyVeSXBYfTX?p=preview

**Comment by jelbourn** [comment]
@crisbeto I have an inkling that this has something to do with animations

**Comment by jelbourn** [comment]
cc @matsko

**Comment by alanpurple** [comment]
and also with md-select

and only with angular 4.3.6.

4.3.5 is okay

**Comment by crisbeto** [comment]
@jelbourn this is definitely animations-related. Having **any** kind of animation in the `animations` array, even if it isn't being used in the view, causes it to break. The only way I got it working was by removing the `animations` altogether.

**Comment by matsko** [comment]
This fix I believe will take care of it: https://github.com/angular/angular/pull/18853

**Comment by crisbeto** [comment]
Closing as something that will be fixed in core.
