### ISSUE TITLE
CDK Table need somewhere else click to render 

### ISSUE THREAD

**Issue by nicollaas94** [angular/material2#6707]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Click and render

#### What is the current behavior?
Click, nothing ... then click again and voila, there is the CDK Table

#### What are the steps to reproduce?
Plunker 
https://plnkr.co/edit/2UPReY?p=preview

Fast workaround for who is facing the same as me 
trigger some event anywhere
(click)="$event.target.click();"

**Comment by jelbourn** [comment]
@nicollaas94 I don't really follow what you mean. Your plunker also seems to work fine

**Comment by benb7760** [comment]
Possibly related to #5593?

@jelbourn It seems the repro is as follows;
1. Click 'Repeat the Click'
2. Click 'Single Click' - table not rendered
3. Click 'Single Click' again - table rendered

**Comment by jelbourn** [comment]
If that's the case then perhaps the just-released beta.10 will resolve it

**Comment by nicollaas94** [comment]
@jelbourn Have you tried to move into tabs ?

click on Repeat the click and then click on Single Click

you will see that wen you came back to Single Click tab the CDK Table will not render
