### ISSUE TITLE
Scrollable listener triggers change detection

### ISSUE THREAD

**Issue by tuanl** [angular/material2#6713]
Scrollable's listener triggers change detection even though the listener is registered within runOutsideAngular. Adding NgZone.assertNotInAngularZone() within the callback throws an error.

https://github.com/angular/material2/blob/0f6a2ecb3de533ec76ed1d0ea4ce9d574cfbc66a/src/cdk/scrolling/scrollable.ts#L35

**Comment by crisbeto** [comment]
@tuanl I couldn't reproduce it by adding a couple of `console.log(NgZone.isInAngularZone());` before the listener is added as well as in the callback. Do you have a more concrete example and can you share what version of Angular and Zone.js you're running?

**Comment by mhevery** [comment]
This is related to: https://github.com/angular/angular/issues/18753

**Comment by crisbeto** [comment]
Closing since the related core issue is fixed.
