### ISSUE TITLE
@angular/cdk publish failed?

### ISSUE THREAD

**Issue by vovikdrg** [angular/material2#6714]
#### Bug, feature request, or proposal:
npm WARN @angular/material@2.0.0-beta.10 requires a peer of @angular/cdk@2.0.0-beta.10 but none was installed.

#### What is the expected behavior?
cdk to be published

#### What is the current behavior?
https://www.npmjs.com/package/@angular/cdk  showing beta.8 is latest releawase
 
#### What are the steps to reproduce?
npm install --save @angular/material@latest @angular/cdk@latest

**Comment by jelbourn** [comment]
Ah, I just forgot to move cdk beta.10 from `@next` to `@latest`. Fixed.
