### ISSUE TITLE
md-grid-tile is cut off in md-grid-list

### ISSUE THREAD

**Issue by lax20attack** [angular/material2#6715]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
md-grid-tile is cut off

#### What are the steps to reproduce?
Plunkr is currently down.

Very simple to repro:

```
 <md-grid-list cols="5">
   <md-grid-tile [rowspan]="1" [colspan]="3">1</md-grid-tile>
   <md-grid-tile [rowspan]="2" [colspan]="2">2</md-grid-tile>
   <md-grid-tile [rowspan]="1" [colspan]="2">3</md-grid-tile>
   <md-grid-tile [rowspan]="2" [colspan]="2">4</md-grid-tile> 
 </md-grid-list>
```

#### Is there anything else we should know?
Issue existed in beta-8

**Comment by josephperrott** [comment]
Closing  as duplicate of #4515
