### ISSUE TITLE
md-tab touch device header scrolling

### ISSUE THREAD

**Issue by lax20attack** [angular/material2#6716]
#### Bug, feature request, or proposal:
Feature Request

#### What is the current behavior?
On touch devices, it would be nice to be able to click and drag the tab header to horizontally scroll in addition to the buttons.

#### What are the steps to reproduce?
Any md-tab-group with enough mb-tabs to give the scrolling option. View in mobile environment. (Chrome dev tools works fine)

```
<md-tab-group>
        <md-tab>
          <ng-template mdTabLabel>
           <span>Long header text 1 </span>
          </ng-template>
        </md-tab>
        <md-tab>
          <ng-template mdTabLabel>
           <span>Long header text 2 </span>
          </ng-template>
        </md-tab>
        <md-tab>
          <ng-template mdTabLabel>
           <span>Long header text 3 </span>
          </ng-template>
        </md-tab>
</md-tab-group>

```

#### What is the use-case or motivation for changing an existing behavior?
 Tapping scroll buttons to scroll on mobile is not intuitive.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Feature does not exist as of Material beta 10

**Comment by jelbourn** [comment]
Tracked via #2209, PR is #6294
