### ISSUE TITLE
Autocomplete example has method that doesn't exist

### ISSUE THREAD

**Issue by mvd7793** [angular/material2#6718]
From [this line](https://github.com/angular/material2/blob/70bd5fc20e7fe6b1749b334d29e842cb3681609d/src/demo-app/autocomplete/autocomplete-demo.ts#L95), `stateCtrl.valueChanges.startsWith` doesn't seem to exist in Angular v4.3.6.

**Comment by ciesielskico** [comment]
You need to import the operator using:

`import 'rxjs/add/operator/startWith'`
