### ISSUE TITLE
provide possibility such that we can provide links in tooltip and have clicking ability.

### ISSUE THREAD

**Issue by guptasho** [angular/material2#6723]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
possibility for tooltip to stay on screen such that i can go and select the text in tooltip/ click on a link available.

#### What is the current behavior?
tooltip hides as soon as i hover out of the element. 

#### What are the steps to reproduce?
create an element with mdTooltip and try to select the text in the tootip.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
giving possibility to a developer to provide links in tooltips such that users can select text/ click on any link to read more about it.

**Comment by donroyco** [comment]
1. Please use the search function to search for duplicate issues (see #6515, #5672, #5440)
2. Tooltips won't have HTML support, [as stated](https://github.com/angular/material2/issues/6515#issuecomment-323110571) by @jelbourn 
>We have no plans to add full templating support to the existing tooltip component.
>
> We _do_ have plans to eventually build a more generic "popup" style component, but that is further out in the future.

**Comment by jelbourn** [comment]
What @donroyco said
