### ISSUE TITLE
Breaking changes of 2.0.0-beta.10 have been introduced into 2.0.0-beta.8

### ISSUE THREAD

**Issue by machucarro** [angular/material2#6725]
#### What is the expected behavior?
If I use 2.0.0-beta.8, I shouldn't get the breaking changes of the beta.10

#### What is the current behavior?
When running npm install on a project using "@angular/material": "2.0.0-beta.8" I get the latest breaking changes published under the version 2.0.0-beta.10

#### What are the steps to reproduce?
Way 1: Compare 2.0.0-beta.10 and 2.0.0-beta.8 branches, they show identical
Way 2: Define a 2.0.0-beta.8 dependency in yout package.json and try to use
import {LiveAnnouncer, Overlay, Directionality} from '@angular/cdk';
or any other breaking change of the beta.10

#### What is the use-case or motivation for changing an existing behavior?
Currently running projects stopped building over night due to an update which should have happened just under a different version

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material": "2.0.0-beta.8

**Comment by jelbourn** [comment]
Nothing changes npm packages once they're published. If you're getting later changes then you've somehow installed a later version.

**Comment by machucarro** [comment]
No I havent't. We had a customer complaining because the version which yesterday evening was building didn't build anymore due to the packages moved in cdk

**Comment by machucarro** [comment]
Just run npm view @angular/material@2.0.0-beta.8 time and you will see it has been as well modified today. In fact it seems it has included all the changes of all the subsequent betas regardless of specifying the version as fixed

**Comment by willshowell** [comment]
@machucarro releases cannot be modified, only created. See the creation dates here:

```
     '2.0.0-beta.7': '2017-06-19T21:44:19.941Z',
     '2.0.0-beta.8': '2017-07-06T17:08:29.479Z',
     '2.0.0-beta.9': '2017-08-29T22:42:48.303Z',
     '2.0.0-beta.10': '2017-08-29T23:50:30.236Z'
```

Also see https://docs.npmjs.com/cli/publish

> Once a package is published with a given name and version, that specific name and version combination can never be used again, even if it is removed with npm-unpublish.

**Comment by machucarro** [comment]
honestly, try it out to npm install a project with the beta.8 and you will see it includes the beta.10 changes. Perhaps it isn't a material issue but an npm one

**Comment by willshowell** [comment]
I already did the following to try and replicate:

1. `npm install --save @angular/material@2.0.0-beta.8 @angular/cdk@2.0.0-beta.8`
2. Opened `node_modules/@angular/material/bundles/material.umd.js`
3. Search the whole file for "form-field" (introduced only in beta.9/10)
4. No results found
