### ISSUE TITLE
md-table performance issue

### ISSUE THREAD

**Issue by fusionUI** [angular/material2#6727]
#### Bug, feature request, or proposal:
`I have integrated the material dataTable and followed the exact same code provided in the sample(https://material.angular.io/components/table/examples).But the table is taking very long to just render the 100 rows and if you increase the loop count to 500 the browser gets stuck and finally gets crashed. This is behaving very poorly for just 100 or 500 rows, unexpected :(

#### What is the expected behavior?
500 rows are not that high to render on a browser. they should gets render with in few sec i believe.Moreover, even if its taking long there should be a busy spinner.

my requirement is to show all the available data using scroll and there is no paging expected
#### What is the current behavior?
for 500 records the browser is getting crashed and even its not working for 100 records

#### What are the steps to reproduce?
 loop the  material data table up 100 and you should have the problem, 
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
AngularJS Version: 4.3.1
AngularJS Material Version:material 2

**Comment by willshowell** [comment]
Can you provide your code and browser? The example uses 100 rows and it renders fine for me in Chrome 60

**Comment by fusionUI** [comment]
Thanks for the prompted reply WillShowell..please find these file attached

[Templatefile.txt](https://github.com/angular/material2/files/1265751/Templatefile.txt)
[TypescriptFile.txt](https://github.com/angular/material2/files/1265752/TypescriptFile.txt)

**Comment by andrewseguin** [comment]
The browser should not crash with 500 rows. Please provide a plunker that shows how this occurred. Reproduction from .txt files will be difficult for us to quickly track down the issue.

Feel free to open the issue back up with a working example, thanks!

**Comment by fusionUI** [comment]
The Slowness issue is only coming in IE(tries on edge), otherwise, it works well for other browsers

i tried hosting the code in plunker and the response in IE is very slow(for 1000 records). Please follow below links. Also please recommend what approach to use in order to make this table responsive - Flex or Bootstarp. It seems like when we are trying to make this table responsive the slowness increases, especially in IE

https://run.plnkr.co/s93Shf2hMGUUcoBl/
https://plnkr.co/edit/LpCiKGSShFJw58eUYEwr?p=preview
