### ISSUE TITLE
Datepicker - format input once it loses focus

### ISSUE THREAD

**Issue by alex321** [angular/material2#6729]
#### Proposal:

Format the date in the datepicker input once it loses focus.

#### What is the expected behavior?

Here's a demonstration (Google Flights):

![datepicker](https://user-images.githubusercontent.com/1670275/29872215-836e98e6-8d86-11e7-8775-fc318c761cb5.gif)

#### What is the current behavior?

The datepicker doesn't format the input unless selected from the pop-up directly.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

2.0.0-beta.10

**Comment by mmalerba** [comment]
This should work now, you can see it in action on the docs site: https://material.angular.io/components/datepicker/overview. Type "Jan 2018" in the input, move focus away, observe that it changes to "1/1/2018"
