### ISSUE TITLE
md-datetimepicker

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/material2#673]

**Comment by jelbourn** [comment]
We don't have a time-picker planned before beta; closing this issue since it's not actionable in the short term (trying to keep the number of issues down).

**Comment by michael-mcanulty** [comment]
I made one from the current datepicker:

https://github.com/michael-mcanulty/md-datetimepicker

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
