### ISSUE TITLE
Is there a reason that snackbar posititioning keeps getting put off?  Can we please have this feature it is important to our build

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#6733]
#### Bug, feature request, or proposal:
Feature request... I hope this doesn't get closed in 2 seconds but there has been quit a long wait for the feature of being able to explicitly position the toast notification on the screen.  

#### What is the expected behavior?
to be able to position the toast notification at least in a few different positions such as top left right than what is the default which is the bottom

#### What is the current behavior?
defaults to bottom

#### What are the steps to reproduce?
use it
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
because on the bottom is not always desirable for some people

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest 4.3.6 

#### Is there anything else we should know?
We waited for a super long time for beta .10 and why was .9 not released?

**Comment by jelbourn** [comment]
#4045 had some remaining issues and the author was on vacation

**Comment by xtianus79** [comment]
@jelbourn lol i need a google vacation!!! jk
