### ISSUE TITLE
Rename md-fab to mdFab

### ISSUE THREAD

**Issue by robindijkhof** [angular/material2#6738]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
From the beta.10 changelog: 

> All dash-case @Directive selectors are deprecated in favor of the camelCase equivalent. The
dash-case selectors will be removed in a subsequent release. Some examples include:

#### What is the current behavior?
There is no `mdFab`

#### What is the use-case or motivation for changing an existing behavior?
Follow the standard

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
beta.10

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/6720

**Comment by jelbourn** [comment]
See explanation in #6720
