### ISSUE TITLE
displayWith directive on md-autocomplete fires unnecessarily even when control is off-screen

### ISSUE THREAD

**Issue by sarora2073** [angular/material2#6752]
#### Bug, feature request, or proposal:

I have a reactive form with an mdAutocomplete enabled mdInput control, that uses a displayWith function. The displayWith function's job is to convert the company object's id value to a display-friendly company value. The form is in a material sidenav container so that the form can appear / disappear from view as need. 

When the form is in use the displayWith and autocomplete functionality appear to work just fine. HOWEVER, as soon as the form ( which is a child component ) is hidden (i.e. md-sidenav which contains the child component) is closed, the displayWith function doesn't stop firing when the mouse moves around the screen in the parent component. The autocomplete + displayWith appear to be still listening for events that they need to respond to even though they aren't even in view. 

Bug
#### What is the expected behavior?

displayWith directive on md-autocomplete should only fire when input control is in use

#### What is the current behavior?
displayWith directive on md-autocomplete fires even when control is blur and even hidden from view in a sidenav container / hidden child component

#### What are the steps to reproduce?

I have some code snippets below but am not able to easily plnkr the whole example at the moment because there is too much unrelated code with it, but will try to update this ticket later.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?

stability for autocomplete / displayWith functionality. When displayWith fires unnecessarily in the code snippet shown below, the 'this' context provides unexpected values which can easily break the code if you don't know what conditions to watch for. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.3.6 / material +cdk on 2.0.0-beta.10 (was broken with 2.0.0-beta.8 as well, so it's not a new issue with beta.10 per se). 

#### Is there anything else we should know?
Associated .html snippet

  <md-input-container>
    <input mdInput placeholder="Company" [mdAutocomplete]="companyTpl" formControlName="companyId" maxlength="100" [(ngModel)]="selectedCompany">
  </md-input-container>
  <md-autocomplete #companyTpl="mdAutocomplete" [displayWith]="displayCompany.bind(this)">
    <md-option *ngFor="let option of filteredCompanies | async" [value]="option.value">{{option.viewValue}}</md-option>
  </md-autocomplete>

Associated .ts snippet
    displayCompany(id): string {
	    console.log("display",this.companies, index);
        if (!id) {
            return '';
        } else {
            let index = this.companies.findIndex(c => c.value === id);       
            return this.companies[index].viewValue;
        }
    }

**Comment by sarora2073** [comment]
Did a little more debugging and realized that the problem is related to this line of html in the *child* component:

[displayWith]="displayCompany.bind(**this**)"

My parent component has a datatable and (to my surprise) just by mousing over rows in the data table componet, was triggering parent -> child communication i.e. child component Input variables got updated, which in turn reloaded (hidden child components) form and updated the '**this**' context in bold above. 

I wondering if anything should be changed within material2 or angular in general to prevent 'wires getting crossed' like this. e.g.

1) Any ability to improve displayWith usage (internals or best practices)? i.e. a better way to pass the currently selected value that is immune above scenario. 'bind(this)' seems to open up cascading effects if used in a hidden child component.

2. Anything that can be done with *hidden* child components in general to prevent them from listening to events when hidden?

Any help appreciated.

Thank, you,

- S. Arora

**Comment by sarora2073** [comment]
Closing for now since this issue morphed from the original title. May re-open as a feature request but need to think on what the improved displayWith approach might be.

**Comment by willshowell** [comment]
If you're interested, there's a discussion thread at https://github.com/angular/material2/issues/4863 over what a better implementation may look like.

**Comment by sarora2073** [comment]
Thanks for mentioning that. I definitely have some feedback!
