### ISSUE TITLE
ERROR in OverlayModule is not an NgModule after upgrading to beta 10

### ISSUE THREAD

**Issue by martinroob** [angular/material2#6753]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
There should be no error

#### What is the current behavior?
After upgrading to beta 10 I get the following error whene running `ng serve`:
ERROR in OverlayModule is not an NgModule

When I run it in aot mode I get:
ng serve --aot --i18n-file=src/i18n/messages.en.xlf --locale=en --i18n-format=xlf
..
ERROR in Unexpected value 'OverlayModule in S:/experimente/tiny-translator/node_modules/@angular/material/material.d.ts' imported by the module 'AppMaterialModule in S:/experimente/tiny-translator/src/app/app-material.module.ts'. Please add a @NgModule annotation.6a0a8c1bbb7963e348f6

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.3.2
node: 6.11.0
os: win32 x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6

**Comment by emilio-martinez** [comment]
@martinroob Overlay was moved to @angular/cdk/overlay

**Comment by PKief** [comment]
Instead of 

`import { OverlayModule } from '@angular/material';`

use

`import { OverlayModule } from '@angular/cdk/overlay';`

**Comment by martinroob** [comment]
Ah, I see it in the Changelog now.
Would have expected something like a compiler error like "cannot find OverlayModule in @angular/material" with a file reference, but because it is reexported from @angular/material, there is no such error.
Even googling for "is not an NgModule" was more confusing than helpful.

Now it works as expected.
Thank you very much for your assistance.
