### ISSUE TITLE
Material Design demo plunkers are broken

### ISSUE THREAD

**Issue by aravindfz** [angular/material2#6754]
#### What is the expected behavior?
The demo plunkers for the material design are broken as the path returns 404 
![image](https://user-images.githubusercontent.com/22231525/29908912-2573109e-8e41-11e7-9523-da8ea1b198ef.png)

#### What is the current behavior?
404 Not Found

#### What are the steps to reproduce?
Navigate to any component example [click here](https://material.angular.io/components/autocomplete/examples)

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: Click on the plunker link in the above link

#### What is the use-case or motivation for changing an existing behavior?
Updating the path

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material angular 2.0.0-beta.10

#### Is there anything else we should know?
 ---

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/6734

**Comment by josephperrott** [comment]
This has been correct in the most recent releases.
