### ISSUE TITLE
Turn off view encapsulation for md-toolbar

### ISSUE THREAD

**Issue by kara** [angular/material2#676]
It's a bit difficult to style `md-toolbar` because ViewEncapsulation isn't turned off, as it is for other components.  Chatted with @jelbourn  about this, and we think it should be `ViewEncapsulation.None`.

**Comment by kunalbariwal** [comment]
Hi. Elevation feature was added in "2.0.0-alpha.2 t-haircut" release (link here - angular/material2@3e34f7a) but it was implemented only for button, card and sidenav components. What about rest of the components like toolbar etc. ? Or did I miss anything?
