### ISSUE TITLE
Opening multiple dialog at once

### ISSUE THREAD

**Issue by VagrantAI-c** [angular/material2#6761]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I have urls that are connected to different pages, that are opened in dialog. For example, i have link /content/43/gallery which should open two dialog at once on app init, one for /content/43 and one for /gallery. It would be great if such MdDialogConfig could be added to prevent dialog from not opening, if another dialog is still initiating

#### What is the current behavior?
Currently, due to #5769 its impossible to perform such behavior, without implementing queue mechanism as a workaround and blocking all dialogs from closing until last dialog is opened

#### What is the use-case or motivation for changing an existing behavior?
I have overlay widget app, that implements multilevel dialog system, and such behavior is damaging the app logic

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2.0.0-beta.10

**Comment by crisbeto** [comment]
I'm not sure how it would work through the `MdDialogConfig` since one dialog could specify that it should prevent other dialogs, whereas another one wouldn't. Thoughts @jelbourn?

**Comment by jelbourn** [comment]
What if we added a method to dialog like `openWhenReady`? I agree that the current behavior feels not-quite-right

**Comment by crisbeto** [comment]
That feels a little clunky. I'll see if I can figure out a way to queue up the dialog animations.

**Comment by crisbeto** [comment]
Closing since we don't have the limitation of opening one dialog at a time anymore.
