### ISSUE TITLE
Datepicker: change format for displayed dates when changing locale in realtime

### ISSUE THREAD

**Issue by swftvsn** [angular/material2#6762]
#### Bug, feature request, or proposal:
Feature request 

#### What is the expected behavior?
When I call dateAdapter.setLocale('xx-XX') already visible dates should be reformatted in the given language.

#### What is the current behavior?
Nothing happens, but if you reload the view, the dates are correctly formatted.

#### What are the steps to reproduce?
Create date picker + ability to change the locale. Select a date -> change locale. The date is still displayed in the format of the language that was used when selecting the date. To reformat one must select the same date again.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
To support realtime locale change. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by crisbeto** [comment]
Is this still an issue? I tried reproducing it in our demo app but it seemed to work. Can you post an example?

**Comment by SaturnTeam** [comment]
I think it's working. I saw this case in source code

**Comment by swftvsn** [comment]
I can confirm that this works with the latest version.
