### ISSUE TITLE
Open menu blocks other actions on page

### ISSUE THREAD

**Issue by Cleudi** [angular/material2#6764]
#### Bug, feature request, or proposal:
Proposal (but honestly, for me personally it feels like a bug)

#### What is the expected behavior?
When a context menu is opened and an item NEXT to the menu is clicked, the desired action should be executed immediately and the menu should be closed

#### What is the current behavior?

- Open context menu
- Click on an item next to the menu
-- Menu closes, nothing else happens
- Click again
-- Desired action is triggered

#### What are the steps to reproduce?
See previous point, but also reproducable - see below!

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Not sure which version this is, but it's reproducible here: https://material2-app.firebaseapp.com/
Just scroll down, click onto MENU then immediately click SNACKBAR

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/5938, https://github.com/angular/material2/issues/1956

**Comment by fxck** [comment]
also related https://github.com/angular/material2/issues/3458

**Comment by jelbourn** [comment]
Working as intended (as explained in those other issues)
