### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by danielgolub** [angular/material2#677]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
A component that will act as infinite scroll to long lists.
If the component is located on top of the list, then it should act as chat infinite scroll.
Example:
```
			<md-list>
				<md-list-item *ngFor="let item of list">
                                           something
                                </md-list-item>
                        </md-list>
                        <md-list-spinner (trigger)="func($event)"></md-list-spinner>
```

```
func(component) {
  component.finish();

  component.enable(false);
}
```

#### What is the use-case or motivation for changing an existing behavior?
Chat list, long files list

#### Which versions of Angular, Material, OS, browsers are affected?
All browsers and OS.

**Comment by jelbourn** [comment]
Having a standalone virtual scrolling helper is definitely on our roadmap but isn't currently planned for the initial release; closing this issue since it won't be acted upon in the short term (trying to keep the number of issues down).

**Comment by KKHAN1991** [comment]
Any update on this feature?
