### ISSUE TITLE
Weird behaviour with slider with ionic 2

### ISSUE THREAD

**Issue by millerf** [angular/material2#6774]
Hi,

I have been trying to use Ionic 3 with Angular material and I have a couple of bugs on the md-slider:
https://material.angular.io/components/slider/overview

On my application the slider cursor doesn't follow the mouse but only moves on mouse release.

I integrated hammerjs in main.ts as stated on the install of Angular Material but still no luck:
https://material.angular.io/guide/getting-started

It is quite bothering me. Any idea? Is Ionic being not compatible with hammerJS?

#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

The slider would slide when the mouse moves

#### What is the current behavior?
The slider slide only when the mouse button is released

#### What are the steps to reproduce?

Any install with ionic 3 and a md-slider

#### What is the use-case or motivation for changing an existing behavior?

It is disturbing for the user to have the slinding only on release

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4, Ionic 3, Typescript 5 (I think)

**Comment by millerf** [comment]
@mmalerba @josephperrott 

Can I help? 

I would really need this to be fixed as soon as possible without having to hack it too much. Just let me know if I can be of any help or any direction I could try to solve this...

**Comment by millerf** [comment]
From what I saw, I think it is a hammer JS bug. Ionic provides its own instance of hammerJS that somehow collides with the one used/installed on Angular material.

**Comment by mmalerba** [comment]
@millerf If you want to look into it, the [`MatSliderModule`](https://github.com/angular/material2/blob/master/src/lib/slider/slider-module.ts#L22) enables hammerJS gestures by providing material's [`GestureConfig`](https://github.com/angular/material2/blob/master/src/lib/core/gestures/gesture-config.ts) for the [`HAMMER_GESTURE_CONFIG`](https://github.com/angular/angular/blob/master/packages/platform-browser/src/dom/events/hammer_gestures.ts) injection token defined in @angular/platform-browser.

**Comment by millerf** [comment]
It must somehow interact with this in ionic:

https://github.com/ionic-team/ionic/blob/master/src/gestures/gesture-config.ts

**Comment by millerf** [comment]
@mmalerba Any lead I could follow? I started to look into it but I am a bit lost, to be frank...
not sure what is the paradigm behind Hammer and the way you and Ionic are using it. Is there any way to 'isolate' the handler to prevent ionic to disable them (if this is what is happening)....

**Comment by millerf** [comment]
@mmalerba @josephperrott I am struggling to get a proper test bed for ionic and angular-material.

I forked both repo, cloned them locally.
I then created a blank ionic project and npm link the built angular-material folder.
but using npm link doesn't allow me to import the built components...

I also tried to install ionic 2 in the demoapp from angular-material but without success either...

Not sure what is the best way to have a nice dev testbed...

**Comment by mmalerba** [comment]
@kara Any idea how to solve a situation where two different libraries want to set the `HAMMER_GESTURE_CONFIG` to different things?

**Comment by millerf** [comment]
@mmalerba @kara I have a very important milestone of my product in 2 weeks.... I am getting a bit skeptical and I would need to know if it is possible to fix it in such a small time...

Unfortunately angular material is the only library I can find which allows vertical sliders...

**Comment by mmalerba** [comment]
I talked to @kara about this and it sounds like you would need to create and provide your own gesture config that combines the options from the ionic and material ones. (That's assuming that the options they set are compatible). 

I realize this is not an ideal solution, but its what we have for now. It would probably be a good idea to file an issue on https://github.com/angular/angular to create a more flexible way of configuring hammerJS

**Comment by millerf** [comment]
I created an easy fix, I just catch the event from the template
```
<div class="wrapper"
     (touchstart)="mouseDown($event)"
     (touchend)="mouseUp($event)"
     (touchmove)="mouseMove($event)"
     (mousedown)="mouseDown($event)"
     (mouseup)="mouseUp($event)"
     (mousemove)="mouseMove($event)"
>
     <md-slider [value]="mainVolume"
               (change)="volumeChanged($event)"
               min="0"
               max="100"
               step="1"
               vertical></md-slider>
</div>
```
And extends the component with this class:

```
import { HammerInput, MdSlider } from '@angular/material';
import { ViewChild } from '@angular/core';
import { Log } from 'ng2-logger';

export class FixSlider {

    @ViewChild(MdSlider) slider: MdSlider;
    private sliding: boolean = false;

    private _log = Log.create('FixSlider');

    protected mouseMove($event) {
        if (this.sliding) {
            $event.preventDefault();
            $event.stopImmediatePropagation();
            $event.stopPropagation();
            this.slider._onSlide(this._getMockHammerEvent($event));
        }
    }

    protected mouseDown($event) {
        this._log.info('mouseDown', $event);
        $event.preventDefault();
        $event.stopImmediatePropagation();
        $event.stopPropagation();

        this.sliding = true;

        this.slider._onSlideStart(this._getMockHammerEvent($event));

    }

    protected mouseUp($event) {
        this._log.info('mouseUp', $event);
        if (this.sliding) {
            $event.preventDefault();
            $event.stopImmediatePropagation();
            $event.stopPropagation();
            this.sliding = false;

            this.slider._onSlideEnd();
        }
    }

    private _getMockHammerEvent($event) {
        return < HammerInput | any > {
            center: {
                x: $event.pageX,
                y: $event.pageY,
            },
            preventDefault: function () {
            },
        };
    }
}

```
And everything works as expected...
