### ISSUE TITLE
Multi-row toolbar breaking fixed header and causing scrolling

### ISSUE THREAD

**Issue by ganySA** [angular/material2#6781]
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
I have a toolbar that is used as a primary header on my page - (fixed at the top of the screen). This works perfectly if there is a single row for the toolbar. When i add a toolbar-row to the toolbar element, it is no longer sticky and causes scrolling on the entire page.

If i apply position fixed to the toolbar i then get a space at the bottom of the screen which is the size of the toolbar-row.

#### What are the steps to reproduce?
Add a toolbar-row to the primary toolbar on the page and it loses stickyness.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template does not seem to work --> Plunker template: https://goo.gl/DlHd6U

**Comment by josephperrott** [comment]
Can you provide a reproduction case?  I was unable to reproduce this myself in a plunker.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
