### ISSUE TITLE
SideNav not animating properly

### ISSUE THREAD

**Issue by JoshuaKeyz** [angular/material2#6783]
#### Bug, feature request, or proposal:
After following the documentation at https://material.angular.io/components/sidenav/overview, my sidenav doesn't animate as expected

#### What is the expected behavior?
It was expected to slide from the left side of the page

#### What is the current behavior?
It just appears without the slide effect and dissapears

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by donroyco** [comment]
Please provide a Plunker to reproduce your issue.

**Comment by JoshuaKeyz** [comment]
donroyco Give me like 15 minutes please

**Comment by JoshuaKeyz** [comment]
Hello, I am having serious problems running it on Plunker, and it seems like I am not the only one having this problem. Even the documentation, when it says Edit in plunker, it still doesn't work. Here is the plunker
https://plnkr.co/edit/4qvHgTSuATj8hBRVOh7z?p=preview

**Comment by JoshuaKeyz** [comment]
It works on my system, but doesn't slide, and when I want to view it on plunker it gives me the above result which I just shared with you...

**Comment by julianobrasil** [comment]
It seems like some of the imports in **`system.config.js`** are broken. I think the team is aware of the problem.

**Comment by josephperrott** [comment]
Closing as it looks to be working now as expected [here](https://plnkr.co/edit/J93PgpqZgfsa6VpcTDYI?p=preview) is a working reproduction.
