### ISSUE TITLE
Input not reset when losing focus + autocomplete issue

### ISSUE THREAD

**Issue by Stefvg1993** [angular/material2#6784]
#### Bug, feature request, or proposal:
I created 3 input fields in 3 input containers. These are all linked to the same autocomplete (same happened when I tried to link them to 3 different auto completes).

When I use the keyboard to navigate (tabs) to fast, the input field looks like its focused, but in reality it is not. The autocomplete shows on the third field in this case. I logged the console for the focus and blur events and they were correct.

![image](https://user-images.githubusercontent.com/31536529/29964609-e5a22b06-8f0a-11e7-8b5e-865cdbc991cf.png)

#### What is the expected behavior?
The input should reset when I use the tabs, even when used quickly. The autocomplete should always show on the focused input, not on the last.

#### What are the steps to reproduce?
https://pastebin.com/xaSYTTsQ

**Comment by willshowell** [comment]
Can you provide a minimal plunker reproduction?

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
