### ISSUE TITLE
Toggling for MdSort switching between three values instead of two ("asc", "desc" and "")

### ISSUE THREAD

**Issue by nadeemramsing** [angular/material2#6786]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When clicking on md-header-cell, toggle should occur between "asc" and "desc". 

#### What is the current behavior?
Toggle is occurring between "asc", "desc" and "" (three states rather than two). 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
package.json
`"dependencies": {
    "@angular/animations": "^4.3.6",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },`

#### How did I find the bug?
````
export class ExampleDataSource extends DataSource<any> {

  constructor(private data, private paginator: MdPaginator, private sort: MdSort) {
    super();
  }

  connect(): Observable<Element[]> {

    const displayDataChanges = [
      this.data,
      this.paginator.page,
      this.sort.mdSortChange
    ];

    const mergeObservable = Observable.merge(...displayDataChanges);

    return mergeObservable.map((item: any) => {
      if (item.direction) debugger; //<--------------------------------------------

      const data = this.data.slice();

      const startIndex = this.paginator.pageIndex * this.paginator.pageSize;
      return data.splice(startIndex, this.paginator.pageSize).sort(function (a, b) {
        if (item.direction === "")
          return;

        //Works for number only for now
        return item.direction === "asc" ? a[item.active] - b[item.active] : b[item.active] - a[item.active];
      });
    });
  }

  disconnect() { }
}
````
#### Is there anything else we should know?
Is it a normal behavior? 
If so, how do I make the possible values of MdSort.mdSortChange: Observable to be twofold only?

Kind Regards

**Comment by willshowell** [comment]
This is normal behavior. `""` is the state for unsorted.

Please see [`mdSortDisableClear` in the docs.](https://material.angular.io/components/sort/overview#changing-the-sort-order)

**Comment by jelbourn** [comment]
As @willshowell described, working as intended.
