### ISSUE TITLE
svg icon registration doesn't work on server platform

### ISSUE THREAD

**Issue by alirezamirian** [angular/material2#6787]
#### Bug, feature request, or proposal:
Bug: svg icons doesn't work on server.

#### What is the expected behavior?
Work on server also.

#### What is the current behavior?
icon registration is [tightly coupled with DOM and depends on `document` to be available](https://github.com/angular/material2/blob/f375f92581b6318219cc225aeafc97124a840b26/src/lib/icon/icon-registry.ts#L400) which breaks its compatibility with server platform.

#### What are the steps to reproduce?
Use svg icons on server platform.

#### What is the use-case or motivation for changing an existing behavior?
It feels quite normal to have svg icons work on server.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material@beta.8

#### Is there anything else we should know?
Nope.

**Comment by FadySamirSadek** [comment]
Is it okay to use a library like jsdom to implement this ?

**Comment by Toxicable** [comment]
@FadySamirSadek unlikely, since platform-server uses domino see https://github.com/fgnass/domino

**Comment by FadySamirSadek** [comment]
@Toxicable  Thank you so much , i did not know that will do more research and hopefully do it

**Comment by freezy** [comment]
Is server-side pre-rendering supposed to work? When I register icons, I provide an URL, which I'm pretty sure won't resolve while pre-rendering, given there's no server running. I tried nevertheless and I'm getting

```
Error retrieving icon:
ERROR [Error]
```

for each icon I'm trying to render. Build runs through though (without icons obviously). Looks like the error is triggered [here](https://github.com/angular/material2/blob/master/src/lib/icon/icon.ts#L145).

Would it be possible to retrieve the files from the file system when `isPlatformServer()` is true so pre-rendering works? Or am I missing something on my side?

**Comment by Amiral1** [comment]
Getting the same error as @freezy

**Comment by d3lm** [comment]
I am getting the same error and I am using the latest version of the `@angular/material` package (5.2.4).
