### ISSUE TITLE
Create tables

### ISSUE THREAD

**Issue by ryan-ds17** [angular/material2#6788]
#### Bug, feature request, or proposal:
Request

Is there any easy example for creating a table just for displaying data?
Do we have to create a DataSource class everytime?

**Comment by willshowell** [comment]
See https://github.com/angular/material2/pull/6747

**Comment by andrewseguin** [comment]
We are working on both a simple built-in data source that has pagination, sorting, and filtering figured out (see @willshowell's comment) as well as a simple table that would provide a very simple table that would just access and show data properties as-is (see #5889)
