### ISSUE TITLE
Users should not have to manually include the Dir directive

### ISSUE THREAD

**Issue by robertmesserle** [angular/material2#679]
We should also have a way to detect if `dir="rtl"` exists outside of the Angular app since this is likely a common use-case.

Currently, in order for `Dir` to work, it has to live inside of an Angular component and the user has to include the Dir directive.  A more common use-case would be to add `dir="rtl"` to `html` or `body` since it is likely desired for the entire app and not just a specific component.

**Comment by jelbourn** [comment]
Now that we have NgModule, we should include `dir` in the modules for any component that consumes it.

**Comment by jelbourn** [comment]
It's just in the `MaterialModule` now
