### ISSUE TITLE
slide-toggle and radio does not update ngModel in tests

### ISSUE THREAD

**Issue by danwulff** [angular/material2#6797]
#### Bug, feature request, or proposal:
Bug: unit testing radio buttons and slide-toggles seems to currently be impossible even when copying the unit tests found in the material2 library .spec files as close as possible.

#### What is the expected behavior?
Material2 radio and slide-toggle should not prevent unit test interaction with a consuming component's view, specifically ngModel bindings.

#### What is the current behavior?
Radio and slide-toggle interactions within component unit tests do not trigger updates to the bound model (but do trigger the proper visual updates e.g. class changes)

#### What are the steps to reproduce?
I've created a repo showing some of the tried tests: https://github.com/danwulff/angular-material2-tests  

to run tests:  
$ `git clone https://github.com/danwulff/angular-material2-tests`  
$ `cd angular-material2-tests  && npm install && ng test`

Specifically take a look at the first unit test in radio.component.spec.ts:
```javascript
it('should update the ngModel value when selecting a radio button', () => {
  const falseRadio = fixture.debugElement.query(By.css('[name="test_group"] [ng-reflect-value="false"] input')).nativeElement;
  console.log('radio input, false', falseRadio);
  const trueRadio = fixture.debugElement.query(By.css('[name="test_group"] [ng-reflect-value="true"] input')).nativeElement;
  console.log('radio input, true', trueRadio);

  expect(component.variable).toBe(false);

  trueRadio.dispatchEvent(createEventType('change'));
  fixture.detectChanges();
  expect(component.variable).toBe(true);  // fails, expected false to be true

  falseRadio.dispatchEvent(createEventType('change'));
  fixture.detectChanges();
  expect(component.variable).toBe(false);
});

function createEventType(type: string): Event {
  const falseEvent = document.createEvent('Event');
  falseEvent.initEvent(type, true, true);
  return falseEvent;
}
```
(markup for reference)
```html
<form #form="ngForm" fxLayout="column" fxLayoutAlign="start center">
  <md-radio-group [(ngModel)]="variable" name="test_group">
    <md-radio-button [value]=false>
      False
    </md-radio-button>
    <md-radio-button [value]=true>
      True
    </md-radio-button>
  </md-radio-group>
</form>
```

##### Material2 .spec test
This was very close to the following Material2 unit test.  
src: https://github.com/angular/material2/blob/2.0.0-beta.8/src/lib/radio/radio.spec.ts#L453
```javascript
innerRadios = fixture.debugElement.queryAll(By.css('input[type="radio"]'));
// ...
it('should update the model before firing change event', () => {
  expect(testComponent.modelValue).toBeUndefined();
  expect(testComponent.lastEvent).toBeUndefined();

  dispatchFakeEvent(innerRadios[1].nativeElement, 'change');
  fixture.detectChanges();
  expect(testComponent.lastEvent.value).toBe('chocolate');

  dispatchFakeEvent(innerRadios[0].nativeElement, 'change');
  fixture.detectChanges();
  expect(testComponent.lastEvent.value).toBe('vanilla');
});
// ...
export function dispatchFakeEvent(node: Node | Window, type: string): Event {
  return dispatchEvent(node, createFakeEvent(type));
}
// ...
export function createFakeEvent(type: string) {
  let event = document.createEvent('Event');
  event.initEvent(type, true, true);
  return event;
}

```

#### What is the use-case or motivation for changing an existing behavior?
Material2 components should not prevent unit tests that interact with the view.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cdk@2.0.0-beta.8
@angular/material@2.0.0-beta.8

#### Is there anything else we should know?
I've seen a few issues in the material2 project with the premise of "can we get more docs about testing?" I totally understand this is beta software, and that providing docs for this kind of thing is not high on the priority list. I do hope, however, that specific instances of failing unit tests like this one will be examined.

Help would be super appreciated.

**Comment by tinayuangao** [comment]
@danwulff You can run the test in `fakeAsync` and use `tick()` after fixture.detectChanges. The test should be passing in fakeAsync. 

Material's test is passing because the test cases are not inside `<form ngForm></form>`. If you remove the outer `<form>`, or make the radio button group standalone, the test will pass.
 
https://angular.io/api/core/testing/fakeAsync

**Comment by danwulff** [comment]
@tinayuangao Thanks for the reply! It seems that the vast amount of scenarios that different components can be in, makes unit testing tough to keep track of. Thanks again.
