### ISSUE TITLE
ScrollDispatcher.scrolled Observable API

### ISSUE THREAD

**Issue by ShadowManu** [angular/material2#6804]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
calls to `ScrollDispatcher.scrolled` returns `Observable`

#### What is the current behavior?
calls to `ScrollDispatcher.scrolled` returns `Subscription`

#### What is the use-case or motivation for changing an existing behavior?
An observable API is much more flexible (and coherent) than a callback-based API

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
At least latest `@angular/cdk`, `@2.0.0-beta.10`.

#### Is there anything else we should know?
Looking from the [source code](https://github.com/angular/material2/blob/master/src/cdk/scrolling/scroll-dispatcher.ts#L97), the reason to provide a subscription instead of an observable is to add `unsubscribe` cleanup logic, which is about keeping count of how many subscriptions are alive.

I think there are better rxjs alternatives for this. `Observable.create` allows for exactly `TeardownLogic` and `Observable.refCount` for unsubscribing automatically. Not that they are the exact answers to the cleanup problem, but they are examples to both have cleanup on unsubscribe while allowing an observable API.

I could work on a PR if this is acceptable.

**Comment by crisbeto** [comment]
This is exactly what https://github.com/angular/material2/pull/6679 does.
