### ISSUE TITLE
Can't scroll demo content on demo site with macOS Safari

### ISSUE THREAD

**Issue by reppners** [angular/material2#6808]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Being able to scroll on the angular material demo page with macOS Safari.

#### What is the current behavior?
Unable to scroll overflowing content on demos page with macOS Safari.
Also the sticky demo content navigation is not displayed.

#### What are the steps to reproduce?
Visit e.g. https://material.angular.io/components/radio/overview with Safari and try to scroll the content.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

https://material.angular.io/

macOS Sierra
Safari Version 10.1.2 (12603.3.8)

**Comment by DevVersion** [comment]
This is being tracked with https://github.com/angular/material.angular.io/issues/247
