### ISSUE TITLE
[Table] IE rows are not centered vertically

### ISSUE THREAD

**Issue by davidmorissette** [angular/material2#6813]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Rows should be centered vertically in IE

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.10

#### Is there anything else we should know?
This can fix the problem:

.mat-header-row, .mat-row {
    height: 48px;
}

I believe IE does not honor min-height when using flex display.

**Comment by donroyco** [comment]
![table-height-ie](https://user-images.githubusercontent.com/1763537/30002688-58a7455e-90b0-11e7-95f3-3674f45f1d83.png)


[Full screenshot](https://www.browserstack.com/screenshots/0b1f4667ed5b8ad456b5496c4ccc25afdc6db52f/win10_ie_11.0.png) via Browserstack that addresses the problem.

**Comment by janardhanchinna** [comment]
This worked for me in IE11:

.mat-header-row, .mat-row {
height: 65px;
}

**Comment by lordgreg** [comment]
Hi. May I find out what's the progress here? This issue is still not resolved, or is it? Latest version of angular material (2) still has invalid positioning of mat-header-row elements.

**Comment by donroyco** [comment]
@lordgreg This issue has been closed as it has been resolved via above's PR. If the issue resurfaced, please file a new issue while using [the issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md) and refer to this issue.
