### ISSUE TITLE
Missing mdCardHeader ng-content slot

### ISSUE THREAD

**Issue by specialkk** [angular/material2#6816]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Specifying an `md-card` with something like `<h3 mdCardTitle>Shiba Inu</h3>` should put it in the right slot in an `md-card-header`.

#### What is the current behavior?
The `.mat-card-header-text` element is empty, it should be selecting `[mdCardTitle]`.

#### What are the steps to reproduce?

~Providing a Plunker (or similar) is the *best* way to get the team to see your issue.~
(Plunker templates aren't working right now)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material2 beta 10

**Comment by julianobrasil** [comment]
Have you tried **`md-card-title`** instead of **`mdCardTitle`**?

I've taken a quick look at some parts of the code and, though there's a Directive like mdCardTitle, the selectors in html template goes like this:

```html
<ng-content
      select="md-card-title, mat-card-title, md-card-subtitle, mat-card-subtitle,
      [md-card-title], [mat-card-title], [md-card-subtitle], [mat-card-subtitle]">
</ng-content>
```
