### ISSUE TITLE
ndinput linked to a reactive form does not show "value"

### ISSUE THREAD

**Issue by Masber** [angular/material2#6821]
#### Bug, feature request, or proposal:
this is a BUG

#### What is the expected behavior?
mdinput in a reactive form should show value
![image](https://user-images.githubusercontent.com/722064/30004330-761b693e-9110-11e7-8db6-d964f7130cf3.png)

#### What is the current behavior?
mdinput is not showing value if the element is linked to a reactive form
![image](https://user-images.githubusercontent.com/722064/30004325-594612aa-9110-11e7-81e3-40625b2520d4.png)

#### What are the steps to reproduce?
create a mdinput linked to a reactive value

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U --> this template does not work so I can't create a plunker

#### What is the use-case or motivation for changing an existing behavior?
to show mdinput value

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
@angular/cli: 1.3.2
node: 7.9.0
os: win32 x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
```

#### Is there anything else we should know?
THIS DOES NOT WORK:
 ```
<md-grid-tile>
    <md-form-field>
        <input mdInput placeholder="Country" value="New Zealand"
            required
            formControlName="inputCountry">
            <md-error *ngIf="formErrors.inputCountry" class="alert alert-danger">
                {{ formErrors.inputCountry }}
            </md-error>
    </md-form-field>
</md-grid-tile>
```

THIS WORKS:
```
<md-grid-tile>
    <md-form-field>
        <input mdInput placeholder="Country" value="New Zealand"
            required>
            <md-error *ngIf="formErrors.inputCountry" class="alert alert-danger">
                {{ formErrors.inputCountry }}
            </md-error>
    </md-form-field>
</md-grid-tile>
```

**Comment by rafaelss95** [comment]
When you use `formControl` `formControlName` or even `ngModel` you shouldn't use `value` in HTML.

Just initialize the desired value in your component, e.g:

```
this.formBuilder.group({
  InputCountry: 'awesome'
});
```

**Comment by tinayuangao** [comment]
@Masber As @rafaelss95 said, you should use `formControl` `formControlName` or `ngModel` to work with forms. Closing this issue.
