### ISSUE TITLE
Use @angular/common/http in MdIconModule

### ISSUE THREAD

**Issue by HitomiTenshi** [angular/material2#6827]
#### Bug, feature request, or proposal:
This is a request.

#### Description
`MdIconModule` is using `@angular/http` which will be deprecated in angular v5.

https://github.com/angular/angular/pull/18906

Removing `@angular/http` from my imports results in an error:

```
Error: Could not find Http provider for use with Angular Material icons. Please include the HttpModule from @angular/http in your app imports.
```

Are there any plans to move to `@angular/common/http` for the upcoming angular v5 release?

#### What is the expected behavior?
No errors.

#### What is the current behavior?
Errors when not importing `@angular/http`.

#### What are the steps to reproduce?
Use `MdIconModule` without importing `@angular/http`.

#### What is the use-case or motivation for changing an existing behavior?
Move to the new `@angular/common/http` API. I'm using it already, would remove the need for me to import `@angular/http`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`@angular/material v2.0.0-beta.10`

**Comment by crisbeto** [comment]
Will be done in https://github.com/angular/material2/pull/6702.
