### ISSUE TITLE
md-error message  dont hide the message after validation pass

### ISSUE THREAD

**Issue by atlabiz** [angular/material2#6828]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
i nead the error to hide after the validation pass

#### What is the current behavior?
the message is dublicated every time the input is invalid

#### What are the steps to reproduce?
the user type on the input for example firstname and if the minlength is under 8 words and is type  less than 8 words ia md-eeror message shows the user that he need more worst ot the input o be valid
now if the user type less wors the iput show that is invalid but if is clean the input and type again onother md-hind come and duplicate the error message

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

```
                <!-- First name -->
                  <div>
                    <md-input-container class="" fxFlex="100" style="width:100%;">
                      
                      <input id="firstName" type="text" mdInput 
                      ngModel
                      name="firstName"  
                      minlength="5" 
                      maxlength="25" 
                      placeholder="Όνομα" 
                      required
                      #firstName="ngModel">

                      <div class="inp_errors" *ngIf="firstName.invalid && firstName.touched">
                        Name is required
                      </div>

                    </md-input-container>
                    
                  </div>

```
![error input](https://user-images.githubusercontent.com/26713354/30024897-849f4002-917e-11e7-8675-1290750a103c.PNG)

**Comment by willshowell** [comment]
It does not look like you are using `md-error`? Can you reproduce in a plunker? [Here is a template.](http://plnkr.co/edit/Oum04xCkaJjUbsi99ic8?p=preview)

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
