### ISSUE TITLE
md-checkbox checked property doesn't works as expected

### ISSUE THREAD

**Issue by tomascharad** [angular/material2#683]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If I pass the checked property to a checkbox then the checkbox should display this property even if I click on the checkbox

#### What is the current behavior?
If I pass checked as false, but I click the checkbox, then the checkbox displays as clicked, even though the checked property that I'm passing hasn't changed.

#### What are the steps to reproduce?
Pass checked as false, and then click over the checkbox.

#### What is the use-case or motivation for changing an existing behavior?
I'm trying to implement this checkbox with redux architecture, so I don't want to listen to the change event, I want to pass the property.

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/common": "2.0.0-rc.1"
"@angular2-material/checkbox": "^2.0.0-alpha.5-2"

**Comment by jelbourn** [comment]
This is the way Angular works with native form controls as well; the property only gets re-stamped when the bound expression changes. The binding is not meant to prevent the control from being interactable.

http://plnkr.co/edit/v7E4AjTDX44sE4npf4w2?p=preview

**Comment by tomascharad** [comment]
@jelbourn ,

Ok many thanks.
If you check material-ui, which is a library that I use very frequently, it works as I was mentioning.
I come from react and angular1, so I could have been mislead by my lack of experience with Angular v2.
Anyways, I don't know if this approach encourages one way data flow...
If I can help with something just let me know.
