### ISSUE TITLE
ButtonToggle issue beta 10

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/material2#6830]
#### Bug, feature request, or proposal:
The buttontoggle group has changed behavior since beta 10, I suppose it's a bug.

#### What is the expected behavior?
The buttontoggles in the buttontoggle group are selectable.

#### What is the current behavior?
The buttontoggle group stays disabled although it shouldn't and although it is not visible that it's disabled.

#### What are the steps to reproduce?
My buttontoggle HTML is: 
<md-button-toggle-group [(ngModel)]="changingModel.base_type" [disabled]="!changingModel?.top_type || changingModel?.is_continues_motion || changingModel?.has_continues_motion" (change)="setSelected('base_type', $event)" vertical #baseToggleGroup [ngClass]="{'hide-base-type': !changingModel?.top_type && !changingModel?.is_continues_motion}">

if all three variables in the [disabled] are false, the buttontoggles in the group stay disabled, until I change some stuff on the screen (don't know how it is related), then they suddenly become enabled.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by willshowell** [comment]
Can you provide a plunker reproduction?

You can use this as a template: http://plnkr.co/edit/liIvuI48q6waZrYrlVmO?p=preview

**Comment by LanderBeeuwsaert** [comment]
Seems I have an issue with ngModel not being supported? http://plnkr.co/edit/b3QIkr1R2SPy08oWrVJ6?p=preview

**Comment by willshowell** [comment]
You must import `FormsModule`

**Comment by LanderBeeuwsaert** [comment]
ok, done. After three seconds, the group should be enabled, and it seems so, but actually the buttons are still disabled.

**Comment by willshowell** [comment]
Here is a simplified plunker that shows the issue and a related one:

http://plnkr.co/edit/sdKuGhLd7juOh31srq1d?p=preview

cc @tinayuangao

**Comment by LanderBeeuwsaert** [comment]
Jep, ok, so it is a bug then. Ok, thanks for the quick follow.
