### ISSUE TITLE
[Table] Uninitialized columns cause error in table

### ISSUE THREAD

**Issue by jlangnli** [angular/material2#6831]
#### Bug, feature request, or proposal:

Hi, I am new to angular. I copy the example for md-table and trying to run it, but it says:

MyComponent.html:17 ERROR TypeError: Cannot read property 'diff' of undefined
    at MdRowDef.webpackJsonp.../../../cdk/@angular/cdk/table.es5.js.BaseRowDef.getColumnsDiff (table.es5.js:53)
    at table.es5.js:533
    at Array.forEach (<anonymous>)
    at QueryList.webpackJsonp.../../../core/@angular/core.es5.js.QueryList.forEach (core.es5.js:5534)
    at MdTable.webpackJsonp.../../../cdk/@angular/cdk/table.es5.js.CdkTable._renderUpdatedColumns (table.es5.js:532)
    at MdTable.webpackJsonp.../../../cdk/@angular/cdk/table.es5.js.CdkTable.ngAfterContentChecked (table.es5.js:493)
    at callProviderLifecycles (core.es5.js:11191)
    at callElementProvidersLifecycles (core.es5.js:11169)
    at callLifecycleHooksChildrenFirst (core.es5.js:11153)
    at checkAndUpdateView (core.es5.js:12258)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I am using angular 4.3.6, cdk 2.0.0-beta.10, and angular material 2.0.0-beta.10
I run it on google chrome

here is my dependencies:

"dependencies": {
    "@angular/animations": "^4.3.6",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/common": "^4.3.6",
    "@angular/compiler": "^4.3.6",
    "@angular/core": "^4.3.6",
    "@angular/forms": "^4.3.6",
    "@angular/http": "^4.3.6",
    "@angular/material": "^2.0.0-beta.10",
    "@angular/platform-browser": "^4.3.6",
    "@angular/platform-browser-dynamic": "^4.3.6",
    "@angular/router": "^4.3.6",
    "@covalent/core": "^1.0.0-beta.6",
    "@next-level-integration/nli-common-lib": "^0.1.4",
    "@next-level-integration/nli-input-lib": "^0.2.7",
    "@next-level-integration/nli-menu-lib": "^0.2.3",
    "@next-level-integration/nli-search-bar-lib": "0.0.6",
    "@next-level-integration/nli-timeline-lib": "^0.1.6",
    "@ngui/map": "^0.18.4",
    "@ngx-translate/core": "^7.2.0",
    "@ngx-translate/http-loader": "^1.0.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.1",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "ngx-webstorage": "^1.8.0",
    "perfect-scrollbar": "^0.8.0",
    "rxjs": "^5.4.3",
    "start": "^5.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.17"
  },

Thanks.

**Comment by willshowell** [comment]
Can you provide your template code?

**Comment by AsynchronousResource** [comment]
Having the same issue and this is my template:
`<md-table #table [dataSource]="dataSource">
    
  <ng-container cdkColumnDef="userId">
    <md-header-cell *cdkHeaderCellDef> ID </md-header-cell>
    <md-cell *cdkCellDef="let row"> {{row.id}} </md-cell>
  </ng-container>

  
  <ng-container cdkColumnDef="progress">
    <md-header-cell *cdkHeaderCellDef> Name </md-header-cell>
    <md-cell *cdkCellDef="let row"> {{row.name}} </md-cell>
  </ng-container>

  <md-header-row *mdHeaderRowDef="displayedColumns"></md-header-row>
  <md-row *mdRowDef="let row; columns: displayedColumns;"></md-row>
</md-table>`

**Comment by jinchoice** [comment]
I'm also having the same issue. The following template used to work without any problems with beta.8, though I did change over all "md-" to "cdk-".

`<cdk-table #factorsTable [dataSource]="factorsDataSource">
      <ng-container cdkColumnDef="factor">
        <cdk-header-cell *cdkHeaderCellDef> Averaged Factor </cdk-header-cell>
        <cdk-cell *cdkCellDef="let row"> {{row.factor}} </cdk-cell>
      </ng-container>
      <ng-container cdkColumnDef="benchmark">
        <cdk-header-cell *cdkHeaderCellDef> {{ benchmark.name }} </cdk-header-cell>
        <cdk-cell *cdkCellDef="let row"> {{row.benchmark == null ? 'N/A' : displayTableValue(row.benchmark) }} </cdk-cell>
      </ng-container>
      <ng-container *ngFor="let i of rangeEtfs" cdkColumnDef="{{i}}">
        <cdk-header-cell *cdkHeaderCellDef>{{ i < etfData.length ? etfData[i].ticker : 'N/A' }}</cdk-header-cell>
            <cdk-cell *cdkCellDef="let row">{{ row.etfs[i] == null ? 'N/A' : displayTableValue(row.etfs[i]) }} </cdk-cell>
      </ng-container>
      <cdk-header-row *cdkHeaderRowDef="factorsColumns"></cdk-header-row>
      <cdk-row *cdkRowDef="let row; columns: factorsColumns;"></cdk-row>
    </cdk-table>
  </div>`

**Comment by willshowell** [comment]
I'm not able to reproduce. [Here is a working example](https://plnkr.co/edit/sTXdGu4vezmK7JTr6bZ8?p=preview), can you try and reproduce from that?

**Comment by tinayuangao** [comment]
@andrewseguin Is this a real issue?

**Comment by andrewseguin** [comment]
Any reproducible steps or plunkers would be appreciated. The `getColumnsDiff` is called once the table's content has been checked, which should include the content's row definitions. The `ngOnChanges` would have been called.

I see that the differ does not set up until the columns are defined. Can you check if the columns are being set sometime after the data is set on the table?

Either way, we'll want some good error handing here to notify the user. Will look into finding how to reproduce

**Comment by andrewseguin** [comment]
Here's a reproduction: https://plnkr.co/edit/yWmcRLntenln6OZBJlho?p=preview

**Comment by andrewseguin** [comment]
If columns are set to null or undefined when the table is setting up, then it encounters this error. Workaround is to make sure that when you set columns, it is initialized to some value. If you are unsure at the time of setup which columns should be displayed, at least set it to an empty array.

**Comment by andrewseguin** [comment]
PR has been sent that should resolve this issue by initializing the columns to an empty array if none are provided.

**Comment by jinchoice** [comment]
That appears to have solved the problem. Thank you.

**Comment by jlangnli** [comment]
Thanks for so many help :) but our deadline for the project is Oktober, so I already changed back to an older version which is still work. Sorry it's a bit of hurry so I don't have time to prepare any example project to show this problem. Thanks again to our lovely community.

**Comment by andrewseguin** [comment]
No problem @jlangnli, but just a heads up that it's trivial to fix on your end to avoid this error. Simply initialize your columns array to `[]`. Otherwise you'll see the fix out soon

**Comment by crowmagnumb** [comment]
I got this error because I did not have an md-header-cell defined for one of my columns. The old api did not require it but the new one appears to need it even if you leave the value of the header blank.

**Comment by pesgaiodev** [comment]
Just change ngAfterViewInit with ngOnInit
