### ISSUE TITLE
Components that reference a container via an ID selector cannot be rendered under md-tab

### ISSUE THREAD

**Issue by anthonysalvato3** [angular/material2#6834]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Angular should recognize the container being referenced by the ID selector if the ID is valid

#### What is the current behavior?
This error is thrown: "Cannot read property 'className' of null"

#### What are the steps to reproduce?
1. Use a library (I'm using cytoscape.js) that depends on using an ID selector to define a container
2. Under md-tab, try rendering the component that depends on using an ID selector to define a container

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "^2.0.0-beta.10"

**Comment by tinayuangao** [comment]
@anthonysalvato3 Could you please provide a plunker?

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
