### ISSUE TITLE
Password-field placeholder doesnt rise when Chrome autofills password-field after beta.10

### ISSUE THREAD

**Issue by eTallang** [angular/material2#6837]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The password placeholder should be placed above the input.

#### What is the current behavior?
When chrome autofills username and password, the username placeholder rises above the username value. The password placeholder however, stays in the field, overlapping the password. See screenshot below:
![image](https://user-images.githubusercontent.com/24789715/30047517-f339ea56-9211-11e7-8ef5-ed254504ba41.png)

If i click on the page so it gains focus, the placeholder instantly jumps to the right position:
![image](https://user-images.githubusercontent.com/24789715/30047531-07a228e6-9212-11e7-85f9-395a493cfa01.png)

#### What are the steps to reproduce?
I have simply created an form with an input of type email and an input of type password, along with a submit-button.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.6
Angular Material 2.0.0-beta.10
Windows 10
Typescript 2.3.4
Chrome seems to be the only affected browser, since it's the only browser that completely autofills the form, without the user having to do anything. In both Edge and Firefox, I have to start typing in the username-field for the browser to suggest saved username/password, so by that time the window has focus, and the bug doesn't occur.

#### Is there anything else we should know?
This functionality was working in beta.8.

**Comment by gbrath** [comment]
Same issue with every form field when pre-filling the data  while building form.

**Comment by eTallang** [comment]
@gbrath I don't know about that. In my case the username placeholder is always aligned correctly when the page is refreshed.

**Comment by nosachamos** [comment]
I can confirm the regression on beta 10. Inputs of text, email, etc types are working properly, but ones with password type have the placeholder overlapping with Chrome's auto-filled value on page load.
