### ISSUE TITLE
MdButtonModule is not an NgModule

### ISSUE THREAD

**Issue by maxime1992** [angular/material2#6840]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
- Upgrading from beta 8 to 10
- Applying all the required chages
- Ending up with this Typescript error while building: `ERROR in MdButtonModule is not an NgModule`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.3.2
node: 8.0.0
os: linux x64
@angular/animations: 4.1.3
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.3.2
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

**Comment by julianobrasil** [comment]
Have you deleted **`node_modules`** directory before running **`npm install`**?

**Comment by Robouste** [comment]
I had the same problem. After removing `node_modules` and reinstall packages, it worked.

**Comment by maxime1992** [comment]
Yes I've tried to remove node_modules, remove yarn.lock and reinstall.
It didn't change anything. BUT, I was running angular `4.1.3` and when I upgraded to `4.3.x` it seems to work fine. Just few things I need to check but I might close the issue soon.

**Comment by maxime1992** [comment]
That was it, closing :+1:
