### ISSUE TITLE
Plunker examples from documentation not working anymore

### ISSUE THREAD

**Issue by slichte** [angular/material2#6844]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Clicking the "Edit in Plunker "-button in components examples should lead to a working plunker example

#### What is the current behavior?
Plunker example cannot be loaded due to a lot of unresolved GET requests, i.e.

GET https://unpkg.com/@angular/cdk@2.0.0-beta.10/bundles/cdk.umd.js/rxjs 404 ()

#### What are the steps to reproduce?
I tried plunkers of the Card and Input components.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
The examples are actually pretty Handy.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I tried with IE and Chrome on Windows 7.

#### Is there anything else we should know?
Keep up the great work! I really love Angular Material and Material Design in general.

**Comment by donroyco** [comment]
Please use the search function before you're issuing duplicate issues: #6754 but see #6734 for a better solution.

**Comment by slichte** [comment]
Sorry for reissuing.
I did use the search function but I thought it must be a very recent issue and didn't spend much time scrolling down. Will look more closely next time.

**Comment by tinayuangao** [comment]
Duplicate issue. Closing this one.
