### ISSUE TITLE
[BUG] Datepicker not working anymore since last update (.10) with disabled input

### ISSUE THREAD

**Issue by Robouste** [angular/material2#6845]
I've just upgraded Material from .8 to .10 and since then, my datepickers are not working anymore. Here is the code.

```
<md-form-field>
	<input mdInput [mdDatepicker]="pickerFrom1" placeholder="From" [(ngModel)]="KpiRfcNbFrom" [max]="KpiRfcNbTo" disabled="disabled"/>
	<button mdSuffix md-button (click)="pickerFrom1.open()">
		<md-icon>today</md-icon>
	</button>
	<md-datepicker #pickerFrom1 [startAt]="KpiRfcNbFrom" (selectedChanged)="changeDateRange($event, 'rfcnb', 'from')"></md-datepicker>
</md-form-field>
```

The problem is because I've specified `disabled="disabled"` on the input. But I want to disable the input. I don't want the user to be able to enter manually the date, he must use the datepicker.

Why this change ? How do I disable my input now ?

**Comment by tinayuangao** [comment]
@Robouste You should use `[disabled]="disabled"`. 

Closing this issue.

**Comment by Robouste** [comment]
I don't think you understand the problem. I want to disable the input but not the button. Why adding disable to the input to disable the trigger ?  I don't think it's logical.

Please do not close the issue because I still don't know how to disable my inputs without disabling the datepicker.

**Comment by willshowell** [comment]
@Robouste can you try https://github.com/angular/material2/issues/6877#issuecomment-327531291? I think your issue was misinterpreted, as what you're trying to accomplish should be possible.

**Comment by Robouste** [comment]
@willshowell Thanks ! That was the solution :)
