### ISSUE TITLE
Bundle builder

### ISSUE THREAD

**Issue by teterovic** [angular/material2#6846]
JQuery UI and Angular migration page had a really nice interface to create configuration packages.
http://jqueryui.com/download/

Now that the CDK is splitted into multiple packages, the same would make sense for AM2 packages at some point. 
With am2.beta.10 it gets a bit more complicated to resolve CDK dependencies.

I purpose a script that handles dependencies and generates configurations if it makes sense for that.
The real question is, is angular material 2 going to be splitted into separate packages in the next releases?

**Comment by jelbourn** [comment]
We have no plans to break the material components into separate imports like the CDK, but we will be do work to optimize our build so that the [build optimizer](https://www.npmjs.com/package/@angular-devkit/build-optimizer) can work against it more effectively.
