### ISSUE TITLE
md-form-field underline black after beta.10

### ISSUE THREAD

**Issue by MaickelHubner** [angular/material2#6847]
#### Bug, feature request, or proposal:
md-form-field underline black after beta.10

#### What is the expected behavior?
underline color = gray

#### What is the current behavior?
underline color = black

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by willshowell** [comment]
Reproduction?

With the latest build, it is gray by default: https://plnkr.co/edit/utx1588npe6ZRLlkpLWN?p=preview

**Comment by MaickelHubner** [comment]
Weird!!!
I'm using a custom theme. Could it be that?

**Comment by MaickelHubner** [comment]
I change to a indigo-pink theme and does not work...

<img width="299" alt="theme" src="https://user-images.githubusercontent.com/15674062/30070618-63a24108-923a-11e7-8215-b66088938736.png">

**Comment by willshowell** [comment]
Between this,
https://github.com/angular/material2/blob/1b6b27055168d6b93ad614054f3797eb845fad55/src/lib/form-field/_form-field-theme.scss#L20-L24

and this,
https://github.com/angular/material2/blob/1b6b27055168d6b93ad614054f3797eb845fad55/src/lib/core/theming/_palette.scss#L680-L696

it should not be affected by a theme (other than light vs dark). 

Also your image shows it as gray, no?

**Comment by MaickelHubner** [comment]
Look better, I think it is change to a dark gray. In previous betas it is a light gray:

<img width="218" alt="previous" src="https://user-images.githubusercontent.com/15674062/30070785-f1ee19dc-923a-11e7-81a1-cd7717c657a7.png">

**Comment by MaickelHubner** [comment]
It is possible change this?

**Comment by willshowell** [comment]
Ohh, ok. Yeah I think @mmalerba changed it to better match [the spec](https://material.io/guidelines/components/text-fields.html#text-fields-states). You can [override it](https://github.com/angular/material2/blob/master/guides/customizing-component-styles.md) with regular css. Probably best to inspect the dom to figure out which selectors to use.

**Comment by tinayuangao** [comment]
@mmalerba Could you please confirm this is intended behavior?

**Comment by mmalerba** [comment]
Yep this was intentional, see #5155
