### ISSUE TITLE
Incorrect colors of md_select

### ISSUE THREAD

**Issue by SergiusSidorov** [angular/material2#6848]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
1. Create required md_select
``<md-select required name="sampleSelect" placeholder="Select value"                 [(ngModel)]="selectValue">
<md-option *ngFor="let val of values" [value]="val">{{ val }}</md-option>
</md-select>``

2. Click on this control in the browser, not choosing the value from list click outside any controls
3. Placeholder must turn red
This behavior works for all input controls.

#### What is the current behavior?
Currently the placeholder remains the primary color, and the asterisk is painted in red.
If you select another control, the placeholder of md_select will also turn red.

#### What are the steps to reproduce?

Your plunker template does not work =(

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 2.0.0-beta.10
@angular/core 4.3.6
typescript 2.4.2
OS Ubuntu, MS Windows 7/10
Firefox, Chrome, IE10/Edge

**Comment by willshowell** [comment]
https://plnkr.co/edit/utx1588npe6ZRLlkpLWN?p=preview

It doesn't show error styles until it has been `touched`, which occurs when the control has been blurred. Clicking away from the select panel leaves focus still on the control.

**Comment by SergiusSidorov** [comment]
Thank you for plunker template!
Here is my example for reproduce: https://plnkr.co/edit/q3A1zRhLi836pwggFzSz?p=preview
