### ISSUE TITLE
MdButton trigger click  with reference does not work

### ISSUE THREAD

**Issue by no-more** [angular/material2#685]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Same behavior as plain button element

#### What is the current behavior?
Nothing, the event is not trigger

#### What are the steps to reproduce?
http://plnkr.co/edit/W6fcHo5TAFe1IDYS18jb?p=preview
when you click on "trigger button1" it works and not for "button2"
#### Which versions of Angular, Material, OS, browsers are affected?
tested on : angular2 rc1, material2 alpha5, windows, chrome

#### Is there anything else we should know?

Thanks.

**Comment by jelbourn** [comment]
I'm not really seeing why you would ever want to call `click()` on a button rather than calling the same function that the button's `(click)` calls. Closing this issue for now, would consider reopening it if there's a compelling use-case.

**Comment by glenstaes** [comment]
I have no idea whether integration testing is a compelling use-case, but at the moment I have to trigger the click on the private property `_elementRef`:
`(promptDialog.componentInstance.confirmButton as any)._elementRef.nativeElement.click();`

In my opinion, it's a lot cleaner if I could just do the following (and I would have intellisense on this):
`promptDialog.componentInstance.confirmButton.click()`

I'm testing whether the confirmation button actually closes the dialog, so calling `promptDialog.close()` in the test itself wouldn't be what I'm actually testing.
