### ISSUE TITLE
MdDialog issue in IE10

### ISSUE THREAD

**Issue by SergiusSidorov** [angular/material2#6850]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Dialog window should be opened in the middle of the screen and available for user input

#### What is the current behavior?
Dialog window opens on the left side of the screen and totally disabled

#### What are the steps to reproduce?
This behavior can be verified on the angular material web site:
https://material.angular.io/components/dialog/overview
Just open this page on IE10 and click "Pick one" button.

#### What is the use-case or motivation for changing an existing behavior?
This control totally unsuitable on IE10

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 2.0.0-beta.10
@angular/core 4.3.6
typescript 2.4.2
MS Windows 7
IE10

#### Is there anything else we should know?
After closing the dialog, the button is no longer pressed.

**Comment by donroyco** [comment]
From the [Readme](https://github.com/angular/material2/blob/master/README.md) file:

> Angular Material supports the most recent two versions of all major browsers: Chrome (including Android), Firefox, Safari (including iOS), and IE11 / Edge

Internet Explorer 10 is not supported and with good reasons, because only the latest version by Microsoft [is currently supported](https://support.microsoft.com/en-us/lifecycle/search?alpha=Internet%20Explorer%2010) (Internet Explorer 11) and will (soon) end. 

> Beginning January 12, 2016, only the most current version of Internet Explorer available for a supported operating system will receive technical support and security updates. Please visit the Internet Explorer Support Lifecycle Policy FAQ for a list of supported operating systems and browser combinations.

**Comment by jelbourn** [comment]
As @donroyco said, we don't support IE10
