### ISSUE TITLE
MdDialog - disableClose not working when hasBackdrop set to false

### ISSUE THREAD

**Issue by sofarojo** [angular/material2#6851]
#### Bug, feature request, or proposal:
MdDialog - disableClose not working when hasBackdrop set to false

#### What is the expected behavior?
Dialog must close when clicking outside of it and when the dialog is set with disableClose=false and hasBackdrop = false.

#### What is the current behavior?
The dialog doesn't close when clicking outside. Only happens when hasBackdrop is set to true.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
(plunker template not working)

#### What is the use-case or motivation for changing an existing behavior?
To have a modeless dialog with   close when clicking outside   enabled.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.6
Material 2.0.0-beta.10
Typescript 2.4.2
All browsers affected.

**Comment by willshowell** [comment]
Here's a working template: http://plnkr.co/edit/5TXYfvouXiGjcJJP93qs?p=preview

If the dialog doesn't have a backdrop, then backdrop clicks will have no effect. Perhaps you just want to set the backdrop's opacity to 0? If that's the case, look into [`backdropClass`](https://material.angular.io/components/dialog/api).

**Comment by sofarojo** [comment]
Yes, you are right, that's exactly what I want.

**Comment by sofarojo** [comment]
Thanks!!
