### ISSUE TITLE
Got error "No provider for FocusTrapFactory" while trying to draw sidenav

### ISSUE THREAD

**Issue by VladCherniavsky** [angular/material2#6854]
I'm trying to use the "No provider for FocusTrapFactory" Sidenav component from the material package. I followed the instractions on material.angular.io site and there is no information about this provider.

Am I missed something?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material: 2.0.0-beta.10
@angular/cli: 1.3.1
typescript: ~2.3.3

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
