### ISSUE TITLE
Tabbing Loses Focus Inside Menus

### ISSUE THREAD

**Issue by jenxu** [angular/material2#6855]
#### Bug, feature request, or proposal:
Currently, visual focus is lost when tabbing or shift+tabbing from inside an opened menu.

#### What is the expected behavior?
Visual focus should show properly when tabbing from an opened menu to the next menu button, and shift+tabbing from an opened menu to the previous menu button. (The next/previous menu buttons should be shaded to indicated that they have focus)

#### What is the current behavior?
Visual focus currently is not shown anywhere when tab or shift+tab is pressed in an opened menu.

#### What are the steps to reproduce?
1) Tab until focus is set on a menu button
2) Press Enter to open the menu
3) Press Tab (or Shift+tab)
4) Observe that the visual focus becomes lost. (Although focus is actually set correctly; pressing Enter during this step will cause the correct menu to open)

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
http://plnkr.co/edit/4ZPy1lv95xTyhV9xtnz4?p=preview

#### What is the use-case or motivation for changing an existing behavior?
This violates the accessibility of the component since the focus should be set somewhere in the DOM at all times.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular2

**Comment by jelbourn** [comment]
@kara @crisbeto isn't pressing tab supposed to close the menu?

**Comment by kara** [comment]
Yeah, it's supposed to close the menu and shift focus to the next item in the tab order. It does those two things, but it looks like the highlighting is broken.

**Comment by jelbourn** [comment]
The highlight of what? The button trigger?

**Comment by jenxu** [comment]
Yes, the highlight of the button.

**Comment by crisbeto** [comment]
This should be resolved by https://github.com/angular/material2/commit/a0bb1a36bb4bcc08e2abe9b6eae84a9be0887bb8.
