### ISSUE TITLE
[Sort] Sort icon should appear on hover

### ISSUE THREAD

**Issue by andrewseguin** [angular/material2#6858]
The spec says that the sort icons should appear when the header is hovered to indicate that the header is sortable.

**Comment by donroyco** [comment]
@andrewseguin How would you do this on mobile devices?

**Comment by andrewseguin** [comment]
Perhaps similar to tooltip, longpress can expose the icon without triggering the sort.

**Comment by willshowell** [comment]
I'd like to piggy back on this to suggest similar behavior on **focus**. Currently there is no visual indication that an action can be taken when tabbing through the `mat-sort-header-buttons`.

**Comment by Misiu** [comment]
@andrewseguin does this mean that user won't see what column is sorted when he enters site? The only way to know what column is sorted will be to hover over header? Will there be an option to show sort icons by default and not when header is hovered?

**Comment by willshowell** [comment]
@Misiu I believe the change will do the following

1. If a column _is not yet sorted_, hovering/focusing/longpressing the header will show the sort icon
2. If a column _is sorted_, the icon will show until the column becomes unsorted (existing behavior)

**Comment by Misiu** [comment]
I got confused because I thought that sort icons will only show when hovering.
@willshowell thanks for clarification.
