### ISSUE TITLE
New minor alpha package

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#686]
could you please publish a new NPM version including current portal and overlay changes.
I need this because I'm working on calendar cmp and I want to use position strategies.
Actual NPM version is a mix of angular beta and rc.

**Comment by zigzag95** [comment]
Thank you. This is not the first time you close my issue without any explanation.
As you want to reduce the number of open issues, I'll stop to open new once even after finding a bug.
C u

**Comment by jelbourn** [comment]
Any issues that ask when something will be done or released will be closed without further explanation. We have to keep Github issues for bugs and feature requests, otherwise we will be overwhelmed with questions.
