### ISSUE TITLE
md-select not be changed to ng-touched after touch it

### ISSUE THREAD

**Issue by copiali** [angular/material2#6863]
#### What is the expected behavior?
md-select status should change to ng-touch after touch it.

#### What is the current behavior?
md-select status is still ng-untouched after touch it. It changed to ng-touched when I click on other places and the select is not highlight.

#### What are the steps to reproduce?
Click on a md-select box, then do not choose any option and close the dropdown.

**Comment by crisbeto** [comment]
This is how the touched/untouched state has worked since Angular 1.x. A control is considered touched when the user moves focus away from it (the `blur` event fires).

**Comment by josephperrott** [comment]
Closing as this is working as expected
