### ISSUE TITLE
In demo app can't call the stepper demo if another demo is shown because the link is broken

### ISSUE THREAD

**Issue by mreu** [angular/material2#6866]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Clicking on stepper in menu from another demo should show the stepper demo

#### What is the current behavior?
Nothing happens

#### What are the steps to reproduce?
Running the demo clicking on of the the demos in the menu and after the demo appears click on stepper in the menu

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Beta 10 of Materials

#### Is there anything else we should know?
There is a slash missing in the beginning of the link to the stepper demo

**Comment by crisbeto** [comment]
Will be sorted out by https://github.com/angular/material2/pull/6790. You can still go to `/stepper` directly.
