### ISSUE TITLE
[DateTimePicker] What I can do for choose month + year only (e.g. May 2017)

### ISSUE THREAD

**Issue by DE-TriNguyen** [angular/material2#6867]
#### Bug, feature request, or proposal:

I read your document about DatePicker and saw about new Support for DatePicker is month + year only (e.g. May 2017). But I can't choose  month + year only. With [startview] = year, I see month show up first, but still choose date after that. 

#### What is the expected behavior?
I just want to choose month + year
#### What is the current behavior?
I can't do that
#### What are the steps to reproduce?
Set [startview] = year

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/4853

**Comment by josephperrott** [comment]
Closing as duplicate of #4853
