### ISSUE TITLE
Menu item click event is not triggered in a loop

### ISSUE THREAD

**Issue by gpessa** [angular/material2#6872]
#### Bug, feature request, or proposal:
I'm trying to create a dynamic menu. Each item has a click function that is triggered when the user click on it. The function is not called.

#### What is the expected behavior?
When I click on an item, the click function should be called. 

#### What is the current behavior?
Nothing is triggered

#### What are the steps to reproduce?
```
<button md-icon-button [mdMenuTriggerFor]="blockMenu">OPEN</button>

<md-menu #blockMenu>
  <button *ngFor="let action of actions" click)="test()" md-menu-item>TEST!</button>
</md-menu>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material: `2.0.0-beta.10`
angular: `4.3.6`

**Comment by crisbeto** [comment]
It seems like you have a typo. Try this:

```
<button md-icon-button [mdMenuTriggerFor]="blockMenu">OPEN</button>

<md-menu #blockMenu>
  <button *ngFor="let action of actions" (click)="test()" md-menu-item>TEST!</button>
</md-menu>
```

**Comment by gpessa** [comment]
Sorry, but it's not solved.
Do you know how I can setup a Plunker with the latest version of material2 so I can reproduce it?

**Comment by crisbeto** [comment]
There's a link to the Plunkr template before opening an issue: https://goo.gl/DlHd6U.

**Comment by gpessa** [comment]
ok, sound like it work here.

Thanks
