### ISSUE TITLE
[Sort] Sort headers add noise for accessible users

### ISSUE THREAD

**Issue by jscharett** [angular/material2#6874]
#### Bug, feature request, or proposal:
Bug: Sortable table headers add unnecessary noise for accessibility users when traversing table.

#### What is the expected behavior?
Sortable table headers are announced as '<column_name> sorted <sort_direction>'.
Grid cells are announced as '<column_name> <cell_value>'.

#### What is the current behavior?
Sortable table headers are announced as 'Change Sorting for <column name> Sorted by <column name> <sort_direction>'.
Grid cells are announced as ''Change Sorting for <column name> Sorted by <column name> <sort_direction> <cell_value>'.

#### What are the steps to reproduce?
Review the sorting demo example: https://material.angular.io/components/table/examples

#### What is the use-case or motivation for changing an existing behavior?
Reducing the cognitive load for screen-reader users.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2.0.0-beta.10

#### Is there anything else we should know?
By setting the aria-label for the column name, it not only announces the the label for that column, but for each cell when navigating the table. This adds considerable noise for the user once they understand that the columns are sortable.  Furthermore, it appears that the aria-sort attribute is not being utilized, rather an additional tag is being added to the header indicating that its been sorted.  This does not align with the spec and adds more 'noise' when navigating the table.  Its somewhat common sense that if there is a button in a table header cell, that its used for sorting.  And the aria-sort attribute handles indicating to the user how the data is sorted, so it unnecessary to use custom language to do so.

**Comment by andrewseguin** [comment]
I wasn't able to hear that using JAWS or Voiceover, which screenreader was saying both the column title and the cell value?

**Comment by jscharett** [comment]
I used NVDA on Windows.  I don't have a license for JAWS so I can't test there, but my past experience with JAWS has showed that it worked the same.  Are you using the table commands to navigate the table?

**Comment by fmax32** [comment]
Sorry guys, as far as I see, the issue is not fixed. You may check it on the table here: https://material.angular.io/components/sort/overview

I've tested on Mac using VoiceOver and when I navigate through the cells of the table it announces:
"Change sorting for ..." for every cell.

Please check attached screenshot for more details:
<img width="1393" alt="screen shot 2018-09-06 at 11 06 47 am" src="https://user-images.githubusercontent.com/6343506/45176677-9322b880-b1c5-11e8-85c5-bac87f7230ae.png">
