### ISSUE TITLE
Date picker <md-datepicker-toggle> : Disabling input disables datepicker icon also

### ISSUE THREAD

**Issue by Jay588** [angular/material2#6877]
#### Bug, feature request, or proposal:
After using <md-datepicker-toggle> element from Angular Material2 beta 10.
If I want to disable input field, so that user cannot enter date manually and I have given the disabled property to the input field and it is disabling the date picker icon also where user is not able to select the date using date picker icon. 

<md-form-field>
  <input mdInput [mdDatepicker]="picker" placeholder="Choose a date" **disabled**>
  <md-datepicker-toggle mdSuffix [for]="picker"></md-datepicker-toggle>
  <md-datepicker #picker></md-datepicker>
</md-form-field>

**Comment by Jay588** [comment]
After using md-datepicker-toggle element from Angular Material2 beta 10.
If I want to disable input field, so that user cannot enter date manually and I have given the disabled property to the input field and it is disabling the date picker icon also where user is not able to select the date using date picker icon.

**Comment by willshowell** [comment]
The demo shows this working. Try it like this:

https://github.com/angular/material2/blob/1b6b27055168d6b93ad614054f3797eb845fad55/src/demo-app/datepicker/datepicker-demo.html#L91-L101

You can see a live example at the bottom of [this page](https://willshowell-demo.firebaseapp.com/datepicker).

**Comment by Jay588** [comment]
Putting [disabled]="false" in md-datepicker element is working...
Thank you my friend..
