### ISSUE TITLE
Performance issue: md-dialog-content on desktop

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#6878]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
md-dialog-content should be optimized and should not repaint on scroll

#### What is the current behavior?
md-dialog-content is not optimized and repaint on scroll

#### What are the steps to reproduce?
![image](https://user-images.githubusercontent.com/7990765/30122815-1a70c5c6-9330-11e7-8942-a43aaa2555a3.png)

#### What is the use-case or motivation for changing an existing behavior?
Angular Material has several performance issues which I think should be addressed.
The web is already slow, no need to make it any slower.
Consider using `will-change: transform;`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material: ^2.0.0-beta.10
Chrome 61

**Comment by Ploppy3** [comment]
@crisbeto Why not use `will-change: transform;`?

**Comment by crisbeto** [comment]
Because `transform` is already hardware-accelerated, it doesn't need `will-change`. [Also `will-change` is supposed to be used sparingly.](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change)
