### ISSUE TITLE
Input floating label should expand when entering floating state

### ISSUE THREAD

**Issue by jean-merelis** [angular/material2#688]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Floating label resize the width to use all available space

#### What is the current behavior?
currently it scale but not resize the width, this way the text is truncated inappropriately 

Current behavior:

![out0](https://cloud.githubusercontent.com/assets/1755960/16081042/15130abc-32e2-11e6-9198-30d967912d23.gif)

Expected behavior:

![out](https://cloud.githubusercontent.com/assets/1755960/16081093/4fff4ec4-32e2-11e6-835e-d442ffc968ba.gif)

**Comment by jelbourn** [comment]
@hansl do you think the input should actually behave this way?

**Comment by hansl** [comment]
I was thinking about it when developing, but it requires a bit of tinkering.  Using a % width (like 115%) while scaling it down might solve it, let me try.

**Comment by hansl** [comment]
Oh look, there's a PR.  Reviewing :)
