### ISSUE TITLE
Tooltip is not shown in Firefox in some cases

### ISSUE THREAD

**Issue by chouclee** [angular/material2#6886]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tooltip should show in Firefox

#### What is the current behavior?
In some cases*, tooltip is missing

```
<button md-icon-button>
  <md-icon [mdTooltip]="'Edit'">edit</md-icon>
</button>
```

#### What are the steps to reproduce?
http://plnkr.co/edit/T8rC8WLfaSHkjexNrot9?p=preview

#### What is the use-case or motivation for changing an existing behavior?
tooltip should have consistent behaviors across evergreen broswers

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
OS: Windows 7 & Mac OS Sierra
Browser:  Firefox only (55.0.3)

**Comment by andrewseguin** [comment]
Unfortunately this is a browser issue with FF that we cannot work around. Buttons shield content from capturing hover events.

https://bugzilla.mozilla.org/show_bug.cgi?id=843003

To workaround this, do not put mdTooltip on content within the button. Instead, put the tooltip directly on the button.

```
<button md-icon-button [mdTooltip]="'Edit'">
  <md-icon>edit</md-icon>
</button>
```

**Comment by chouclee** [comment]
@andrewseguin Thanks for finding the root cause. The reason I put it within button is to show tooltip even when button is disabled. I can use extra ``<div></div>`` as wrapper.
