### ISSUE TITLE
ObjectUnsubscribedError when md-slider removed and re-added via *ngIf

### ISSUE THREAD

**Issue by TurplePurtle** [angular/material2#6892]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

The slider can be removed and added to the page by toggling the condition of an `*ngIf` directive on the slider itself or on a parent element/component.

#### What is the current behavior?

After removing the slider, and then adding it again by toggling the *ngIf off and on, an `ObjectUnsubscribedError` is raised.

#### What are the steps to reproduce?

https://embed.plnkr.co/oqhT6YMKMMKDopXfxgM7/

1. Click "Hide slider"
2. Click "Show slider"
3. Error is raised, causing the slider to be rendered incorrectly.

#### What is the use-case or motivation for changing an existing behavior?

The current behavior breaks the page if an `md-slider` is inside an `*ngIf`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Tested in Angular 4.4.0-RC.0, Material 2.0.0-beta.10-6b5100b, Chrome 60, TypeScript 2.1.6

**Comment by rafaelss95** [comment]
Seems like your plunker is outdated. Check it [here](https://plnkr.co/edit/y0cNinP0ypNMOGtPYPJU?p=info).

**Comment by Kyderman** [comment]
Im getting the same error on snackbar components on latest pull
