### ISSUE TITLE
MdSelect MdPrefix

### ISSUE THREAD

**Issue by rvoltolini** [angular/material2#6895]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
select whith prefix like mdinput, where the icon stay at start of the line

#### What is the current behavior?
the icon is misaligned

#### What are the steps to reproduce?
develop a mdselect with a mdprefix icon

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular material 2 beta 8

#### Is there anything else we should know?
I saw a Issue open to make a "mdSelectContainer", I would like the prefix to work as in the input.
Here an example where input is "correct" and select is "wrong"
![captura de tela de 2017-09-06 20-33-39](https://user-images.githubusercontent.com/30928235/30139217-e3836998-9342-11e7-8165-c2cfcdd4093f.png)

**Comment by julianobrasil** [comment]
`MdSelect` is being refactored so it can be used with `md-form-field`. So it will probably be possible to have `mdPrefix` working together with it.

**Comment by rvoltolini** [comment]
Thanks @julianobrasil . 
I'm new here, how do I check to see if it's already available? Or when will it be available?

**Comment by julianobrasil** [comment]
Take a look at #6488. You'll notice, at the end of the page, that it is still not merged (the merge pull request button is still there). You can subscribe to get notified when any event happens concerning the PR you wish to follow.

![image](https://user-images.githubusercontent.com/25405143/30165280-dfd0552c-93b5-11e7-9f52-f81d6afa1b66.png)

**Comment by rvoltolini** [comment]
Thanks!

**Comment by julianobrasil** [comment]
Yeah, definitely!
