### ISSUE TITLE
The change event doesn't fire sometimes.

### ISSUE THREAD

**Issue by chenzhiguang** [angular/material2#6897]
### source code 

    md-slider(
      min="0",
      max="2",
      step="1",
      [value]="byTypeValue",
      [disabled]="disabled",
      (change)="onSet($event)")

#### What are the steps to reproduce?
change the value by clicking the track line. clicking or dragging the thumb icon several times will increase the chance to meet this issue.

#### What is the current behavior?
![04](https://user-images.githubusercontent.com/5637609/30142237-357d4dbc-93b2-11e7-9e28-b408d030349a.gif)
(NOTE: the spinner will be shown if the change event is emitted, otherwise there is no spinner)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular-4.3.1           
angular-material-2.0.0-beta.10     
macOS-10.12.3        
chrome-60.0.3112.113         
typescript-2.3.2

**Comment by mmalerba** [comment]
I think this may have been resolved already, I'm not able to reproduce it anymore: https://stackblitz.com/edit/angular-material2-issue-a4v7w8
