### ISSUE TITLE
[inquiry] Any plans to support UMD in SystemJS?

### ISSUE THREAD

**Issue by RoxKilly** [angular/material2#691]
Recently, the ng2 team changed its [recommended SystemJS configuration](https://angular.io/docs/ts/latest/quickstart.html#!#create-and-configure) to use UMD when registering packages (see *systemjs.config.js* tab).

**Previous systemjs.config.js**
```
var ngPackageNames = [...];
ngPackageNames.forEach(function(pkgName){
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
});
```

**Current systemjs.config.js (simplified)**
```
var ngPackageNames = [...];

// Most environments should use UMD; some (Karma) need the individual index files
ngPackageNames.forEach(function(pkgName){
    packages['@angular/'+pkgName] = { main: pkgName + '.umd.js', defaultExtension: 'js' };
});
```
As a result of this change the number of http requests was reduced dramatically.  I tried to make the same change to how `ngMaterial 2` packages are registered, but this causes `404` errors when loading `.umd.js` files.

Do you plan to offer similarly streamlined packages?

**Comment by jelbourn** [comment]
#556
