### ISSUE TITLE
(docs) include publication date and @angular/material version on docs site

### ISSUE THREAD

**Issue by cheoalvarez** [angular/material2#6914]
#### feature request:

Include the "docs generated on" date and angular/material version # in the docs site

#### What is the current behavior?

Info not currently available on https://material.angular.io/

#### What is the expected behavior

"Generated on MM/DD/YYYY for version #" displayed on site

#### What is the use-case or motivation for changing an existing behavior?

To be able to easily reference what date/version docs have been published for. Currently hard to tell if docs get out of sync with latest npm package (as it seems to be now)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

2.0.0-beta.8  ( as of 2017-09-07, currently published version of docs site is for 2.0.0-beta.8, @angular/material@latest is for 2.0.0-beta.10)

**Comment by willshowell** [comment]
See https://github.com/angular/material.angular.io/pull/246 for the version being added. I don't really know that the date is valuable if the version is there.

**Comment by cheoalvarez** [comment]
Cool dude, sorry didnt see this when I searched. Version info will be great
