### ISSUE TITLE
Sort (mdSort) not work in md-table

### ISSUE THREAD

**Issue by MaickelHubner** [angular/material2#6915]
#### Bug, feature request, or proposal:
If I use a *ngIf in a div that contains a md-table, sort function do not work (mdSort is undefined after @ViewChild)

#### What is the expected behavior?
Sort work independent of a div have *ngIf or not

#### What is the current behavior?
Sort do not work

#### What are the steps to reproduce?
Create a div with *ngIf with a md-table inside

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3, Material 2.0.0-beta.10, MaxOS, Typescript 2.3, Safari/Chrome

#### Is there anything else we should know?
Nope

**Comment by rafaelss95** [comment]
That's not really an issue. It's how `@ViewChild` works. Check [this answer](https://stackoverflow.com/questions/39366981/angular-2-viewchild-in-ngif#answer-41095677).

**Comment by MaickelHubner** [comment]
It worked! Thanks
