### ISSUE TITLE
[mdExpansionPanel] angular material demo broken by #5641 

### ISSUE THREAD

**Issue by cjiang** [angular/material2#6919]
#### Bug, feature request, or proposal:

On a local instance of the "angular2 material demo", navigate to /expansion.

#### What is the expected behavior?

Page loads correctly.

#### What is the current behavior?

No expansion panels show up, and the dev console contains the message:

Error: Uncaught (in promise): Error: The animation trigger "expansionHeight" has failed to build due to the following errors:
 - state("collapsed", ...) must define default values for all the following style substitutions: collapsedHeight
 - state("expanded", ...) must define default values for all the following style substitutions: expandedHeight

**Comment by crisbeto** [comment]
It works for me locally and in general this is something that would've broken all unit tests. You're most likely running an older Angular version.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
