### ISSUE TITLE
Md-menu appears behind content

### ISSUE THREAD

**Issue by mohitook** [angular/material2#6925]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
menu appears above the content

#### What is the current behavior?
menu appears behind the content

#### What are the steps to reproduce?
use it e.g. in a nav navbar.

```
<button md-icon-button [mdMenuTriggerFor]="menu">
                          <md-icon>more_vert</md-icon>
                        </button>
                        <md-menu #menu="mdMenu">
                          <button md-menu-item>
                            <md-icon>dialpad</md-icon>
                            <span>Redial</span>
                          </button>
                          <button md-menu-item disabled>
                            <md-icon>voicemail</md-icon>
                            <span>Check voicemail</span>
                          </button>
                          <button md-menu-item>
                            <md-icon>notifications_off</md-icon>
                            <span>Disable alerts</span>
                          </button>
                        </md-menu>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
newest

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/15103326/30187612-aacefeda-942a-11e7-8ad6-bee7ee72a240.png)

**Comment by crisbeto** [comment]
What is the `z-index` of your toolbar @mohitook? If it's more than 1000, all Material overlays can potentially show up behind it (e.g. dialog, tooltip etc.). You should either reduce the toolbar `z-index` or increase the one of `.cdk-overlay-container`.
