### ISSUE TITLE
Material2 Doesn't seem to work with Angular 2 RC 2

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#693]
Angular Material 2 doesn't seems to work with RC 2.

I made changes to my packages.json and have below dependencies:

```
"@angular/common": "^2.0.0-rc.2",
    "@angular/compiler": "^2.0.0-rc.2",
    "@angular/core": "^2.0.0-rc.2",
    "@angular/http": "^2.0.0-rc.2",
    "@angular/platform-browser": "^2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.2",
    "@angular/router": "^2.0.0-rc.2",

    "@angular2-material/core": "2.0.0-alpha.5",
    "@angular2-material/button": "2.0.0-alpha.5",
    "@angular2-material/card": "2.0.0-alpha.5",
    "@angular2-material/checkbox": "2.0.0-alpha.5",
    "@angular2-material/grid-list": "2.0.0-alpha.5",
    "@angular2-material/icon": "2.0.0-alpha.5",
    "@angular2-material/input": "2.0.0-alpha.5",
    "@angular2-material/list": "2.0.0-alpha.5",
    "@angular2-material/progress-bar": "2.0.0-alpha.5",
    "@angular2-material/progress-circle": "2.0.0-alpha.5",
    "@angular2-material/radio": "2.0.0-alpha.5",
    "@angular2-material/sidenav": "2.0.0-alpha.5",
    "@angular2-material/slide-toggle": "2.0.0-alpha.5",
    "@angular2-material/tabs": "2.0.0-alpha.5",
    "@angular2-material/toolbar": "2.0.0-alpha.5",

```

But when I try to restore packages, I receive below error:

@angular2-material/icon@2.0.0-alpha.5 requires a peer of @angular/http@2.0.0-rc.1 but none was installed

**Comment by jelbourn** [comment]
The peer dependency thing is just a warning. Does it actually not work?

**Comment by aquinum6** [comment]
I don't know about alpha.5 because I'm using alpha.5-2 (you should update).

RC2 and alpha.5-2 seems to work quire fine (i'm using this two together right now).
I just noticed one issue which I posted in: [#696](https://github.com/angular/material2/issues/696)

**Comment by Richhy** [comment]
I get the same error (using 2.0.0-alpha.5-2) but my application seems to be running fine. 

Just ignore it I suppose

**Comment by jelbourn** [comment]
Closing this for now since people can just ignore the warnings.

**Comment by naveedahmed1** [comment]
You are right, application seems to be working despite of these warnings, I need to test it with new form with disableDeprecatedForms()

**Comment by naveedahmed1** [comment]
Jeremy it seems that material form controls are not working with Angular 2 RC 2. I am receiving  

EXCEPTION: No value accessor for 'firstName'. 

I have tested it on md-input, md-slide-toggle and md-checkbox and I receive below exception on all of them.

EXCEPTION: No value accessor for 'Field name'. 

Can you please check and reopen this issue.

**Comment by aquinum6** [comment]
https://github.com/angular/material2/issues/696

I posted this issue already.

**Comment by naveedahmed1** [comment]
Ok, thanks Piotr, I will follow that.
