### ISSUE TITLE
MdSidenav not being opened/closed if opened binding changes quickly

### ISSUE THREAD

**Issue by rafaelss95** [angular/material2#6930]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`md-sidenav` is not "respecting" the `[opened]` binding if changes occur too quickly.

#### What is the current behavior?
`md-sidenav` should be open/close according to the `[opened]` binding.

#### What are the steps to reproduce?
Just click in "Open sidenav" quickly (2 clicks are sufficient).

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://plnkr.co/edit/4fz5zQYAXFBO08KMrYUL?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
@angular/cli: 1.4.0
node: 8.1.1
os: linux x64
@angular/animations: 4.4.0-RC.0
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.4.0-RC.0
@angular/compiler: 4.4.0-RC.0
@angular/core: 4.4.0-RC.0
@angular/forms: 4.4.0-RC.0
@angular/http: 4.4.0-RC.0
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.4.0-RC.0
@angular/platform-browser-dynamic: 4.4.0-RC.0
@angular/platform-server: 4.4.0-RC.0
@angular/router: 4.4.0-RC.0
@angular/cli: 1.4.0
@angular/compiler-cli: 4.4.0-RC.0
@angular/language-service: 4.4.0-RC.0
typescript: 2.5.2
```

#### Is there anything else we should know?
It was working perfectly in 2.0.0-beta.8, [as you can see here](https://plnkr.co/edit/dI2TpoBwxkBXhuBS2R0U?p=preview).

**Comment by willshowell** [comment]
https://github.com/angular/material2/pull/6810 😁

**Comment by rafaelss95** [comment]
Thanks, I didn't see that :)
