### ISSUE TITLE
width in mat-form-field-theme mixin makes it problematic to have multiple themes

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/material2#6932]
#### Bug, feature request, or proposal:

Using classes to change from a default theme changes the specificity of form field widths.

#### What is the expected behavior?

Changing theme should not change form field widths.

#### What is the current behavior?

Using a theme class changes the specificity of the default form field width.

#### What are the steps to reproduce?

http://plnkr.co/edit/WcreafWOoGGgLxNuSZh0?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Changing theme shouldn't cause the width of form fields to change.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

beta 10

#### Is there anything else we should know?

It seems like the width in mat-form-field-theme() should be in a mixin called by mat-core instead?

**Comment by josephperrott** [comment]
Closing as this will be covered #7083
