### ISSUE TITLE
Shouldn't MdSelect be part of MdFormField?

### ISSUE THREAD

**Issue by richardsengers** [angular/material2#6936]
#### Feature request
Shouldn't the MdSelect be part of the MdFormField so we can use required with the same styles as the input fields
I think we would like something like this (even better without the hidden MdInput offcourse)
https://plnkr.co/edit/jt7RCH4L1N5bnjyplJQB?p=preview

#### What is the expected behavior?
Generate the same styles for select boxes when making use of MdFormField

#### What is the current behavior?
We have to style selectboxes ourselves when we want to make them required and an error message is shown. In some use cases you want to make a selectbox required

#### What are the steps to reproduce?
The current behaviour is shown in the plunkr
https://plnkr.co/edit/BAsNaLd6Gwlahhj1CbFT?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Automaticaly inherit styles from other form fields so we don't have to do it ourselves

**Comment by Nodarii** [comment]
Hello, @richardsengers 
Is it already in progress, I guess it's gonna be merged soon 
https://github.com/angular/material2/pull/6488

**Comment by richardsengers** [comment]
Ah thank you very much @Nodarii ...I've searched the repo for select and MdSelect but with 24 pages each to search for I've missed that one.
