### ISSUE TITLE
Docs for Sidenav needs update

### ISSUE THREAD

**Issue by bogacg** [angular/material2#6937]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Having Docs that reflect latest updates in project:

Example in Docs for Sidenav being compatible with latest version (2.0.0-beta.10). There is now Drawer Component.
Material 2.0.0-beta.10 produces `.mat-drawer-content` class for content of Sidenav. Drawer component's content seems to handle scrolling case as well, so example does not need to add `overflow: auto;`

#### What is the current behavior?
Having examples of older version.

 `.mat-sidenav-content` class is referred in current Docs example, also scrolling is handled in that example, which is not needed with current version (for content at least, if not sidenav).

**Comment by willshowell** [comment]
Can be closed via #7099
