### ISSUE TITLE
mdPrefix is focusable

### ISSUE THREAD

**Issue by MurWade** [angular/material2#6939]
#### Bug
If you make a` md-icon-button` a `mdPrefix` then the `md-icon-button` becomes focusable on a form.
So for example when you use the tab to go to the next field. it goes to the icon first

#### What is the expected behavior?
The expected behavior should be that the `mdPrefix `should not be focusable. at least you should be able to use tab to go to next form field. 

Right now you can fix this by setting `tabindex="-1"` on the `mdPrefix` to fix this.
#### What are the steps to reproduce?
```
<md-form-field>
    <button  md-icon-button mdPrefix><md-icon>person</md-icon></button>
    <input mdInput type="email" >
  </md-form-field>

  <md-form-field>
    <button md-icon-button mdPrefix><md-icon>lock</md-icon></button> // this is focusable with tab
    <input mdInput type="password">
  </md-form-field>

```

#### Which versions of Angular?
2.0.0-beta.10

**Comment by julianobrasil** [comment]
@MurWade, I didn't get why would you put a button in a page that cannot be focused (at least as its default behavior)? Can you include an use case above in your issue text?

**Comment by MurWade** [comment]
@julianobrasil  [look at input demo on master](https://github.com/angular/material2/blob/master/src/demo-app/input/input-demo.html#L131)

It also uses a button to have icon. if you use button it aligns the icon properly

**Comment by willshowell** [comment]
@MurWade those buttons have specific purposes (dunno about the money icon, but the edit icon would), they just don't have implemented callbacks bc it's a demo. If you don't want them to be focusable, just use the `md-icon` without the button.

**Comment by julianobrasil** [comment]
Also, wouldn't be better to open an issue requesting for a better md-icon alignment in this case (**`mdPrefix`** and **`mdSuffix`**?

**Comment by MurWade** [comment]
@julianobrasil  Ya you are right.. issue requesting for a better md-icon styling in this case (mdPrefix and mdSuffix

**Comment by julianobrasil** [comment]
@MurWade, try this approach: https://plnkr.co/edit/3XQUQP9xQDUezPM9xAKv?p=preview
