### ISSUE TITLE
All the plnker examples under https://material.angular.io/components are broken

### ISSUE THREAD

**Issue by parker-mike** [angular/material2#6941]
I believe that release of beta-10 with its' long list of breaking changes rendered these examples unusable.

**Comment by julianobrasil** [comment]
#6734

**Comment by rafaelss95** [comment]
For me, it's working fine since yesterday.

**Comment by julianobrasil** [comment]
Good news. I haven't noticed it yet.

**Comment by parker-mike** [comment]
Well, I believe I'm not the only one, #6952 is about the same issue...  Have disabled the cache on the network tab and refreshed the plnker, still it throws a dozen of errors. Not sure what the problem is since on the FF everything is fine...

**Comment by parker-mike** [comment]
Ok, I've looked into the `systemjs.config.js` and noticed that it has the old configuration, so obviously I was forwarded to an old edition of the plnker and it's not the plkner which has to be cache cleaned and refreshed but the material.angular.io. Once done everything started to work as expected, it's strange though that the site doesn't have protection mechanisms against such issues, and I didn't find anything about the cache and app versioning on the angular's docs site, can anyone point me to it?

**Comment by josephperrott** [comment]
Closing as this was fixed with the latest release.
