### ISSUE TITLE
MdIconRegistry not using @angular/common/http

### ISSUE THREAD

**Issue by jlinhares** [angular/material2#6943]
#### Bug, feature request, or proposal:
Feature request / proposal

#### What is the expected behavior?
The use of @angular/common/http

#### What is the current behavior?
It uses @angular/http.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
@angular/http is becoming deprecated.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.10 withAngular 4.3.*

**Comment by donroyco** [comment]
Please use the search function for duplicate entries. See (duplicate) issue #6827 and reference there to #6702

**Comment by jlinhares** [comment]
Thanks for the reference
