### ISSUE TITLE
MdMenu should be opened with a right-click

### ISSUE THREAD

**Issue by DanielFuchs98** [angular/material2#6945]
#### Bug, feature request, or proposal:
feature

#### What is the expected behavior?
Possibility to open MdMenu with a right-click

#### What is the current behavior?
With [mdMenuTriggerFor] the MdMenu can only be opened with a left-click

#### What is the use-case or motivation for changing an existing behavior?
Have a Context-Menu

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/5007
