### ISSUE TITLE
Md Form Field is not working

### ISSUE THREAD

**Issue by davenlin19** [angular/material2#6948]
I have an error:
`md-form-field must contain a MdFormFieldControl. Did you forget to add mdInput to the native input or textarea element?`

This is my current html:
`<form [formGroup]="form" *ngIf="form">`
    `<md-form-field>`
        `<input mdInput placeholder="title" name="title" formControlName="title">`
    `</md-form-field>`
`</form>`

and the version of my material:
`"@angular/material": "^2.0.0-beta.10"`

Thanks !

**Comment by davenlin19** [comment]
Sorry i don't know why but my plunker works: [http://plnkr.co/edit/LjSqMOVm9xAo01QCBTAn?p=streamer](url)

In fact, i think i know why i had this error, i didn't import the **MdInputModule**. Now, i import it, also the BrowserAnimationsModule. I have a normal input with no style at all.

**Comment by davenlin19** [comment]
Do you think i'm missing some modules to be imported ?

**Comment by donroyco** [comment]
As stated in the [Material documents for Input](https://material.angular.io/components/input/api), you have to import `MdInputModule` as `import {MdInputModule} from '@angular/material';`. That could have solved your issue.

**Comment by davenlin19** [comment]
I found the problem, i thought that the style has been imported automatically. But in fact, i have to import the theme manuelly in my scss. And now it works.

Thank you
