### ISSUE TITLE
Plunker generation is broken when there are images on demo

### ISSUE THREAD

**Issue by dev054** [angular/material2#6951]
#### Bug, feature request, or proposal:
Bug/Proposal.

#### What is the expected behavior?
I'd expect to see demo without anything broken in plunker.

#### What is the current behavior?
Actually if you click in "Edit in Plunker" button in [this page](https://material.angular.io/components/card/examples), the generated plunker will be "broken", in other words, without any images.

**Comment by donroyco** [comment]
See #6754

**Comment by dev054** [comment]
@donroyco not really related. The plunker itself is working... the problem is that this `Card` example has some images and it isn't being projected to the plunker... that's isn't something new, I'm just wondering if the images could be passed together with the plunker generation.

**Comment by donroyco** [comment]
It _is_ relates, because that issue addresses the main issue here: how can we manage to get stable Plunker examples, because the broke  images you're referring to, worked in the past.

**Comment by josephperrott** [comment]
Closed with #6990
