### ISSUE TITLE
Some plunkers are broken on the docs site

### ISSUE THREAD

**Issue by dev054** [angular/material2#6952]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
Pages:

https://material.angular.io/components/icon/examples
https://material.angular.io/components/list/overview
https://material.angular.io/components/snack-bar/examples

#### What are the steps to reproduce?
Just click and open console. There are some missing files.

**Comment by josephperrott** [comment]
A new version of [material.angular.io](http://material.angular.io) was pushed recently.  Try clearing the cache and cookies on your browser and see if the issue continues.

**Comment by jelbourn** [comment]
The errors being thrown are due to missing plunker files; might be related to the local asset copy script not copying the plunker assets

**Comment by josephperrott** [comment]
Fixed by #6990
