### ISSUE TITLE
Width of md-progress-bar and md-spinner can not be set :(

### ISSUE THREAD

**Issue by ambikesh1982** [angular/material2#6953]
#### Bug, feature request, or proposal:
feature request
porposal

#### What is the expected behavior?
Could you please let us set width of md-progress-bar and md-spinner. I really want to set progress bar as thin as md-slider. 

#### What is the current behavior?
As per my understanding, width can not be set. Please correct me if I am wrong.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by Chan4077** [comment]
Did you try using the `!important` selector?

```html
<md-spinner class="app-spinner" mode="indeterminate"></md-spinner>
<md-progress-bar class="app-progress-bar" mode="indeterminate"></md-progress-bar>
```

```css
.app-spinner {
    width: 30px !important;
    height: 30px !important;
}
.app-progress-bar {
    width: 400px !important;
}

**Comment by ambikesh1982** [comment]
Thank you very much Edric!
It works :)

**Comment by michaeljota** [comment]
Also, you could target the html element. 

```scss
md-progress-bar {
    width: 30px;
    height: 30px;
}
```

There is not need for `!important` here.

**Comment by ambikesh1982** [comment]
Thank you Michael... This works without **!important** as well.
I was doing the same thing, I wonder why it didn't work.

Never mind it works now! 👍
