### ISSUE TITLE
Support @angular/forms

### ISSUE THREAD

**Issue by aquinum6** [angular/material2#696]
It seems that material does not work with new forms. I have used formControlName directive and I got error that there is no value accessor for certain field in my case 'email':

> No value accessor for 'email'

I have changed import in input/index.js from:

`var common_1 = require('@angular/common');`

to:

`var common_1 = require('@angular/forms');`

and it seems to start working.

**Comment by Krisa** [comment]
@aquinum6 Can you detail a bit more what you've done? Importing REACTIVE_FORM_DIRECTIVES, and so on from `@angular/forms` didn't help.

**Comment by naveedahmed1** [comment]
@Krisa you need to make below changes:

Replace
var common_1 = require('@angular/common');
with
var common_1 = require('@angular/forms');

in the following files:

node_modules/@angular2-material/checkbox/checkbox.js
node_modules/@angular2-material/input/input.js
node_modules/@angular2-material/radio/radio.js
node_modules/@angular2-material/slide-toggle/slide-toggle.js

**Comment by Krisa** [comment]
@naveedahmed1 ahh indeed, this did the trick. I didn't come on the idea to modify the source file directly, thank you!

**Comment by Drol** [comment]
@Krisa You should read the official document too. https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

**Comment by Krisa** [comment]
@Drol, I did, that's now working. My only problem was, as referred before, the angular2-material source files I "forgot" to modify.

**Comment by naveedahmed1** [comment]
Though replacing

var common_1 = require('@angular/common');
with
var common_1 = require('@angular/forms');

in material components source files seems to be working for other components but doesn't seems to work for Checkboxes. This change does remove the ValueAccessor error on form load, but when the form is submitted it posts below object in case of checkbox if its checked:

```
myCheckbox: MdCheckboxChange
checked:true
source:MdCheckbox
__proto__:Object
constructor:MdCheckboxChange()
__proto__:Object
```

For your information @jelbourn and @kara

**Comment by aquinum6** [comment]
Can you specify which property you are using to get value? it is 'formControlName' or 'change'.
According to this code:
```
private _emitChangeEvent() {
    let event = new MdCheckboxChange();
    event.source = this;
    event.checked = this.checked;

    this._controlValueAccessorChangeFn(this.checked);
    this.change.emit(event);
  }
```
from https://github.com/angular/material2/blob/master/src/components/checkbox/checkbox.ts (change) event is returning whole event which has 2 parts: source (component) and checked (actual value). formControlName should have only true or false. I might be mistaken because I haven't have time yet to check that. If you are using (change) can you check if fetching value with:
`(change)="someAction($event.checked)"`
works or not?

**Comment by aquinum6** [comment]
It seems that valueAccessor subscribe to change whole event in checkbox:
```
MdCheckbox.prototype.registerOnChange = function (fn) {
    if (this._changeSubscription) {
        this._changeSubscription.unsubscribe();
    }
    this._changeSubscription = this.change.subscribe(fn);
};
```
to fix this just map change to proper value:
```
MdCheckbox.prototype.registerOnChange = function (fn) {
        if (this._changeSubscription) {
            this._changeSubscription.unsubscribe();
        }
        this._changeSubscription = this.change
        .map(function (v) {
            return v.checked;
        })
        .subscribe(fn);
    };
```
It works for me.
