### ISSUE TITLE
Expansion panel open by default

### ISSUE THREAD

**Issue by ImranAhmed** [angular/material2#6962]
#### Bug, feature request, or proposal:
I've been searching for a way to open the open expansion panel by default, very little in the documentations, is this possible or shall we raise as a feature request?

**Comment by ppham27** [comment]
You can do:

<md-expansion-panel [expanded]="true">
  
</md-expansion-panel>

**Comment by ImranAhmed** [comment]
Thanks, perfect!

**Comment by ted-sandbox** [comment]
easy peasy, thanks for the tip.

**Comment by ORESoftware** [comment]
doesn't that mean it's always expanded? or just initially expanded?

**Comment by DukeCaesar** [comment]
Adding [expanded]="true" to mat-expansion-panel will expand the panel initially. You can still collapse it when you click the toggle header.

**Comment by pcnate** [comment]
is this documented on http://material.angular.io?

**Comment by aloketewary** [comment]
Yes in API there is _@Input_ part where you can see it. Follow the docs @pcnate 
https://v5.material.angular.io/components/expansion/api#MatExpansionPanel

**Comment by bullcrane** [comment]
Since merely assigning true, rather than doing anything to it programmatically, this also works:

<md-expansion-panel expanded>
  
</md-expansion-panel>

**Comment by yannanna0920** [comment]
如果是循环md-expansion-panel呢  这样加expanded 会报错 也只默认最后一个是展开的  有遇到这种情况德吗（What if it's a loop called md-expansion panel so expanded will report an error and it will simply expand the last one by default. Is that the case）

**Comment by hirocsingh** [comment]
How can I expand all the expansion-panel by default?
