### ISSUE TITLE
bug(Datepicker): Calendar's position is being switched to upside even when there's no space to fit it

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#6965]
#### Bug, feature request, or proposal:

Bug.

#### What is the expected behavior?

(Not sure) If there's no space in the screen nor bellow neither above to show the entire calendar, the bellow position should be the chosen one, so the user could scroll down if necessary (the scrollbar should be shown in this case).

Even better, when there's not enough screen space nor above neither bellow (but enough space in visible browser window viewport) the calendar could be shifted from its base position (defined by the the current rules) trying to fit itself in the available space. But the offset would be limited by the associated input (the input underline should fall in the space between the top and bottom edges of the calendar). Finally, when the total visible screen space wasn't enough to fit the calendar, it would end up in the bellow position, and the scrollbar would be visible.

#### What is the current behavior?
Notice that the top of the calendar was cropped in the images bellow and there's no scrollbar so one can see the hidden part of it (in fact, there's not viewport above to be scrolled to reveal the hidden part). And it looks like there is space to show it (first image) if it's given an offset.

 **IMAGE 1:**

![image](https://user-images.githubusercontent.com/25405143/30248478-da7992c8-95fe-11e7-8ef1-c09ec5df682a.png)

**IMAGE 2:**

![image](https://user-images.githubusercontent.com/25405143/30248467-aaa87906-95fe-11e7-95ec-db69d8ae45ba.png)

**IMAGE 3:**

![image](https://user-images.githubusercontent.com/25405143/30248408-a98857cc-95fd-11e7-855a-4dd43400204c.png)

#### What are the steps to reproduce?

1. Open the plunk: https://plnkr.co/edit/QeV9drIbHGEPS4ECFSZ5?p=preview
2. Shrink the browser window so the calendar doesn't fit in it

#### What is the use-case or motivation for changing an existing behavior?

Better user experience when working in not-full-screen/small windows

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cli: 1.4.0
node: 6.10.3
os: win32 x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/flex-layout: 2.0.0-beta.9-5f198a3
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/platform-server: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.0
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
typescript: 2.3.4

**Comment by julianobrasil** [comment]
Any news about this? One user complained today (I told him to press F11 to change the browser to full screen mode).

![image](https://user-images.githubusercontent.com/25405143/32020677-c5c8aca4-b9af-11e7-955e-501d1871201d.png)

Maybe I use the touch UI mode for now or other users can be confused.

cc @mmalerba

**Comment by mmalerba** [comment]
I believe it tries to position the calendar below and if there's not enough room it tries to position it above. If there's still not enough room it chooses whichever had more space available (in this case above). But I agree that it doesn't work so well here... I believe @jelbourn is working on a new positioning strategy that pushes the content back on screen. Is that ready yet Jeremy?

**Comment by jelbourn** [comment]
It's still in-progress, should be soon-ish

See #6534

**Comment by julianobrasil** [comment]
Hi, @malerba and @jelbourn, I realized that https://github.com/angular/material2/pull/9153 was merged in March but, this undesired behavior is still there. The datepicker calendar, IMO, should be shifted down when there's no room above to show the header. 

It's better to hide part of the body at the bottom than hide the header. And here I see an additional problem: even if you have the possibility to scroll up the page while the calendar is opened to try to make the calendar header visible, the scrolling is locked. Wouldn't it be better to release the scrolling while the calendar is opened?

In fact, I should be able to tell the overlay that it should consider a poage offset from top/bottom: look at the image below: shouldn't I be able to tell the position strategy to not cover the top navbar, by considering the top of the page avaiable space to start below the nav bar (somehow telling the position stratagy to offset from top/bottom by an amount of pixels)

![image](https://user-images.githubusercontent.com/25405143/40714525-44a3ce36-63d9-11e8-94d4-e12f34bbd3d0.png)

**Comment by blackblood19** [comment]
can you please let me know the progress on this issue? Looks like the pull request is in progress for the last 50 days..

**Comment by julianobrasil** [comment]
@blackblood19, as a workaround you can switch your datepickers to touchUi when it necessary. I'm using this directive to accomplish this task:

```html
<mat-datepicker  appDatepickerSwitch></mat-datepicker>
```

```ts
@Directive({
  selector: '[appDatepickerSwitch]',
})
export class AppDatepickerSwitchDirective implements OnInit, OnDestroy {
  _isShortScreen = false;

  private _monitorScreenHeight$ = fromEvent(window, 'resize');
  private _destroy$ = new Subject<void>();

  constructor(
    private _zone: NgZone,
    @Self()
    @Host()
    private datepicker: MatDatepicker<any>,
  ) {
    this._zone.runOutsideAngular(() => {
      this._monitorScreenHeight$.pipe(takeUntil(this._destroy$)).subscribe(() => {
        this._switchDatepickerMode();
      });
    });
  }

  ngOnInit() {
    setTimeout(() => (this.datepicker.touchUi = this._isThereFreeSpace()));
  }

  ngOnDestroy() {
    if (!!this._destroy$ && !this._destroy$.closed) {
      this._destroy$.next();
      this._destroy$.complete();
    }
  }

  private _isThereFreeSpace(): boolean {
    const windowHeight = this._getWindowHeight();
    const inputElementRect = this.datepicker._datepickerInput
      .getPopupConnectionElementRef()
      .nativeElement.getBoundingClientRect();
    const inputHeight = inputElementRect.height;
    const freeTopSpace = inputElementRect.top;
    const freeBottomSpace = windowHeight - (freeTopSpace + inputHeight);
    return freeTopSpace < 354 && freeBottomSpace < 354;
  }

  private _switchDatepickerMode() {
    const isThereFreeSpace = this._isThereFreeSpace();
    if (isThereFreeSpace !== this.datepicker.touchUi) {
      this._zone.run(() => (this.datepicker.touchUi = isThereFreeSpace));
    }
  }

  private _getWindowHeight() {
    return window.innerHeight
      ? window.innerHeight
      : document.documentElement.clientHeight || document.body.clientHeight || 0;
  }
}
```

**Comment by mohyeid** [comment]
Any progress on this? We are still facing this issue on a 13 inch laptop. 
https://stackblitz.com/edit/datepicker-position-issue?file=main.ts
![datepicker](https://user-images.githubusercontent.com/15852376/45782528-160d2f80-bc18-11e8-8c41-36e257b52251.PNG)

**Comment by julianobrasil** [comment]
Well, https://github.com/angular/material2/pull/11607 is approved and waiting to be merged, and maybe it brings some improvement this situation, but it won't shift the calendar to left/right (it will be on top of the input). Is it an acceptable solution in your case? (it is in my case)

**Comment by mohyeid** [comment]
@julianobrasil Yea, that would work fine on Datepicker. I was worried about any other cases where popup would be used and would need to be more smart to go right or left as well to make sure it does not cover any important information. I can not think of a usecase at the moment, so I think your fix will be fine. 
In the meantime, thanks for the directive tip. I used it as a temrary fix with a few refactor to dimpplify it. Let me know if you see issues with my changes? Its basically checking if the popover is hidden on the top, so it reset top style to 8px. if its hidden on bottom, it reset the bottom style to 8px.

https://stackblitz.com/edit/datepicker-position-issue-p2xgfz

```
import { Directive, Self, Host, OnDestroy } from '@angular/core';
import { MatDatepicker } from '@angular/material';
import { takeUntil, delay } from 'rxjs/operators';
import { fromEvent, Subject } from 'rxjs';

@Directive({ selector: '[positionDatepicker]' })
export class PositionDatepickerDirective implements OnDestroy {
 private _destroy$ = new Subject<void>();
  constructor(
    @Self()
    @Host()
    private datepicker: MatDatepicker<any>
  ) {
    if(!this.datepicker.touchUi) {
      this.datepicker.openedStream.pipe(takeUntil(this._destroy$), delay(0)).subscribe(() => {
          this.fixOffScreenPosition();
      });
    }
  }

fixOffScreenPosition(): void {
    const top = this.datepicker._popupRef.hostElement!.firstElementChild!.getBoundingClientRect().top;
    const bottom = this.datepicker._popupRef.hostElement!.firstElementChild!.getBoundingClientRect().bottom;
    if (top < 0) {
      (<any>this.datepicker._popupRef.hostElement!.firstElementChild!).style.top = '8px';
      (<any>this.datepicker._popupRef.hostElement!.firstElementChild!).style.bottom = '';
    } else if (window.innerHeight < bottom) {
      (<any>this.datepicker._popupRef.hostElement!.firstElementChild!).style.bottom = '8px';
      (<any>this.datepicker._popupRef.hostElement!.firstElementChild!).style.top = '';
    }
  }

  ngOnDestroy() {
   if (!!this._destroy$ && !this._destroy$.closed) {
      this._destroy$.next();
      this._destroy$.complete();
    }
  }
}

```

**Comment by julianobrasil** [comment]
@mohyeid, today I spared some time to test your workaround (basically I tried it out in some situations) and there's a not so good effect when the user scrolls the screen vertically to see the calendar, as it tries to stay on the screen visible area:

![image](https://user-images.githubusercontent.com/25405143/46259964-ac621080-c4b6-11e8-9176-5cabfc3d5cf6.png)
