### ISSUE TITLE
demo-app: Removable chips in a form field (placeholder and text cursor disappear)

### ISSUE THREAD

**Issue by gise88** [angular/material2#6966]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
the place holder is supposed to be always visible

#### What is the current behavior?
After adding a certain number of chips the placeholder and the text cursor disappear. 
![screenshot_20170910_151550](https://user-images.githubusercontent.com/6855163/30249364-71f3db90-963b-11e7-94e7-ceab096c62b3.jpeg)

#### What are the steps to reproduce?
Simply run the demo-app and go to this url:
http://localhost:4200/accessibility/chips
Add and remove chips to see the issue.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current latest of this repo, I don't know if with the previous versions show the same problem.

**Comment by tinayuangao** [comment]
Should be fixed.
