### ISSUE TITLE
demo-app: Removable chips in a form field (placeholder not float and shift)

### ISSUE THREAD

**Issue by gise88** [angular/material2#6967]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
the placeholder is supposed to float and not to shift when a chip is added.

#### What is the current behavior?
Eg, after adding a single chip the placeholder goes down (instead of keeping floating) and shifts.
![screenshot_20170910_152220](https://user-images.githubusercontent.com/6855163/30249387-df956f88-963b-11e7-8d2b-0717ecf5185e.jpeg)

#### What are the steps to reproduce?
Simply run the demo-app and go to this url:
http://localhost:4200/accessibility/chips
Add and remove chips to see the issue.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current latest of this repo, I don't know if with the previous versions show the same problem.

**Comment by tinayuangao** [comment]
Fixed by #7509
