### ISSUE TITLE
demo-app: Removable chips in a form field (behavioral differences between Firefox and Chrome)

### ISSUE THREAD

**Issue by gise88** [angular/material2#6968]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
the same behavior in all browsers

#### What is the current behavior?
In chrome the chips exit from the "bound" of the form field.
![screenshot_20170910_155506](https://user-images.githubusercontent.com/6855163/30249649-7d4a2562-9640-11e7-870b-bb77342ce49c.jpeg)

In Firefox the form field will vertically grow when required.
![screenshot_20170910_160020](https://user-images.githubusercontent.com/6855163/30249680-339b9db4-9641-11e7-8009-52fbf44b3533.jpeg)

I think that the Firefox behavior is the better one but when adding a certain number of chips you can't see the text cursor (issue already open [here](https://github.com/angular/material2/issues/6966))

#### What are the steps to reproduce?
Simply run the demo-app and go to this url in Firefox and in chrome:
http://localhost:4200/accessibility/chips

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current latest of this repo, I don't know if with the previous versions show the same problem.

**Comment by tinayuangao** [comment]
I think this is obsolete. Now the behaviors are the same in chrome and firefox.
