### ISSUE TITLE
404 HTTP Status 

### ISSUE THREAD

**Issue by JoshWilliams92** [angular/material2#697]
I'm no longer using the angular CLI until it's out of beta, as I have encountered too many problems with it. I am scaffolding the app with the tutorials on the main angular.io documentation. Just wondering if there is a way to use material in an angular 2 app without using the angular CLI.

**Comment by gelidus** [comment]
You will need to copy `'@angular2-material/**/*.js'` files and configure system.js like this  https://github.com/kara/puppy-love/blob/master/src/system-config.ts

**Comment by JoshWilliams92** [comment]
I'm not using the angular CLI to build it so there is no system-config.ts file. There is a systemjs.config file and I tried putting the dependencies on there but it didn't work.

**Comment by jelbourn** [comment]
For now you need some module loader that can handle CommonJS modules. The CLI currently uses SystemJS, but any module loader should do.
