### ISSUE TITLE
`MdDatepickerToggle` not working well after disable its input associated (template driven forms)

### ISSUE THREAD

**Issue by rafaelss95** [angular/material2#6974]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
 `md-datepicker-toggle` should respect the `input` state.

#### What is the current behavior?
Described below.

#### What are the steps to reproduce?
1 - Click "Enable/disable" input... now the `input` is **disabled**;
2 - Press the `md-datepicker-toggle` (yes it's still enabled)... nothing will happen and after you click it'll be disabled;
3 - Click "Enable/disable" input... now the `input` is **enabled**;
4 - `md-datepicker-toggle` button is disabled now always.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://plnkr.co/edit/gpldSaRYwQDRKIHMOsHu?p=preview

Related to #6973.

**Comment by crisbeto** [comment]
Will be resolved by https://github.com/angular/material2/pull/6964.

**Comment by rafaelss95** [comment]
Thanks (it was fast) :)
