### ISSUE TITLE
Check box and radio within a dialog create vertical scroll bar

### ISSUE THREAD

**Issue by HarelM** [angular/material2#6978]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
No vertical scroll bar will appear

#### What is the current behavior?
Vertical scrollbar appears for no reason

#### What are the steps to reproduce?
Use either a check-box or radio button within a dialog.
I don't understand why it has error in the console, but it can be seen here:
https://plnkr.co/edit/Pq8eemyrAq9Lbx6Xj02l?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It just looks bad.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest, took the plunker right out of the documentation page.

#### Is there anything else we should know?
There are a lot of issues involving the dialog I have seen.
I opened a few but they seem to be ignored.
The dialog is a very powerful tool and its current state it's just an eye sour.
Please make an effort to improve the current state and behavior of the dialog.
For example this issue: #4574

**Comment by julianobrasil** [comment]
This is being tracked in #4764.

**Comment by HarelM** [comment]
It's open for 4 month, "tracked" is a compliment...

**Comment by julianobrasil** [comment]
Given some restrictions of the project, it is kind of tricky to fix it. If you figure out who to solve it after following the coments in #4764, fell free to make a suggestion or submit a PR.
