### ISSUE TITLE
cdk not installing correctly

### ISSUE THREAD

**Issue by surfjedi** [angular/material2#6979]
#### Bug, feature request, or proposal:

BUG

#### What is the expected behavior?

That when you "npm install @angular/cdk --save" is should properly install

#### What is the current behavior?

After using the above command the output is:

(master)*$ npm install @angular/cdk --save
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/-----/.npm/_logs/2017-09-11T02_39_58_489Z-debug.log

and hence you can run any app with @angular/material

#### What are the steps to reproduce?

1. make a new angular project or use existing
2. run "npm install @angular/cdk --save"

#### What is the use-case or motivation for changing an existing behavior?

make material usable

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4.2.4
Node 8.4.0

**Comment by jelbourn** [comment]
Sounds like an issue with your environment, [package is on npm just fine](http://unpkg.com/@angular/cdk/).
