### ISSUE TITLE
Material Design color hue out of current palette for theming

### ISSUE THREAD

**Issue by jagomf** [angular/material2#6981]
#### Bug, feature request, or proposal:
I am actually not sure, probably a request, but might be a bug as well.

#### What is the expected behavior?
When creating a theme, you are expected to pass a default color, plus optionally a lighter and darker hue. You enter a palette name, and codes for default, lighter and darker colors. Those codes are supposed to mean a color hue *inside of the named palette*.

#### What is the current behavior?
If you want a lighter or darker hue to be part of a palette other than currently selected one, I am not sure but it does not seem that you can proceed.

#### What are the steps to reproduce?
1. Go to [Material Color tool](https://material.io/color)
2. Choose yellow (`#ffee58`) as either primary or secondary color
3. Proposed dark hue will be `#c9bc1f`
4. Mentioned darker hue is not in the Yellow palette in [Material Color Palettes](https://material.io/guidelines/style/color.html#color-color-palette)
5. When [theming a Material Angular app](https://material.angular.io/guide/theming#defining-a-custom-theme), you can provde `$mat-yellow` as color palette, but you cannot define your darker hue as a number (100-900, A100-A700) based on your current color palette, because it is out of it.

#### What is the use-case or motivation for changing an existing behavior?
Defining a theme that is actually based on Material Design recommendations.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, Angular-material 2.

**Comment by willshowell** [comment]
The material palettes are based on [these](https://material.io/guidelines/style/color.html#color-color-palette), as you noted. I can't speak for the inconsistency that the color picker tool shows, but you can create your own palettes and use them:

```scss
$app-custom-yellow: (
  50: #fffde7
  100: #fff9c4
  ...
  contrast: (
    ...
  )
);
```

**Comment by jagomf** [comment]
Good idea, thanks

**Comment by josephperrott** [comment]
As mentioned, our palletes are based on the link given above. Closing as they are currently in sync so this is as expected.
