### ISSUE TITLE
SideNav [opened] property bound not working correctly when bound to an observable

### ISSUE THREAD

**Issue by stocksr** [angular/material2#6985]
#### Bug, feature request, or proposal:
Bug: When you bind the opened property of a sidenav to an Observable and that Observable changes again while the animation is running the sidebar ignores the change.

#### What is the expected behavior?
The sidebar should always end up in a state that matches the observable.

#### What is the current behavior?
The side bar ignores changes while it is processing the previous one.

#### What are the steps to reproduce?
In this plunker: http://plnkr.co/edit/DSBJmIPJzjhoeg2rGx2z?p=preview
If you press the bounce button the sidebar should end up in the open state.
alternatively if you press the open and close buttons in rapid succession you can also end up with the wrong state.  

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta 10 (This worked in beta 8)

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/6376

**Comment by Nodarii** [comment]
@stocksr , 

I face such behavior, but it is not connected to the observable. Component can not be closed until it is fully showed (I mean animation is done)

**Comment by stocksr** [comment]
thanks - I even looked for this issue before reporting - but I was looking for it under SideNav not drawer.
PR #6810 looks like it will fix it, any idea when that will land?

**Comment by willshowell** [comment]
@stocksr since it's marked as ready, _probably_ this week. The team typically merges about twice a week, but there are often presubmit failures or merge conflicts that postpone it to the next round.
