### ISSUE TITLE
After updating Material beta.10, error on build "ScrollDispatchModule is not an NgModule"

### ISSUE THREAD

**Issue by eamine84** [angular/material2#6987]
Hi, I put material beta.10 to my application, but after building my app I always have an error:

"ERROR in Error: ScrollDispatchModule is not an NgModule"

here is my package.json:

"dependencies": {
    "@angular/animations": "4.3.6",
    "@angular/cdk": "2.0.0-beta.10",
    "@angular/common": "4.3.6",
    "@angular/compiler": "4.3.6",
    "@angular/compiler-cli": "4.3.6",
    "@angular/core": "4.3.6",
    "@angular/flex-layout": "2.0.0-beta.9",
    "@angular/forms": "4.3.6",
    "@angular/http": "4.3.6",
    "@angular/material": "2.0.0-beta.10",
    "@angular/platform-browser": "4.3.6",
    "@angular/platform-browser-dynamic": "4.3.6",
    "@angular/platform-server": "4.3.6",
    "@angular/router": "4.3.6",
    "angular2-markdown": "1.6.0",
    "blob-polyfill": "1.0.20150320",
    "classlist-polyfill": "1.2.0",
    "classlist.js": "1.1.20150312",
    "core-js": "2.4.1",
    "formdata-polyfill": "2.0.2",
    "hammerjs": "2.0.8",
    "intl": "1.2.5",
    "moment": "2.18.1",
    "rxjs": "5.0.1",
    "typedarray": "0.0.6",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.14"
  },
  "optionalDependencies": {
    "fsevents": "1.1.2"
  },
  "devDependencies": {
    "@angular/cli": "1.4.1",
    "codelyzer": "2.0.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "0.2.3",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "marked": "0.3.6",
    "protractor": "5.1.2",
    "raw-loader": "0.5.1",
    "rollup": "0.43.0",
    "rollup-plugin-commonjs": "8.0.2",
    "rollup-plugin-node-resolve": "3.0.0",
    "rollup-plugin-uglify": "2.0.1",
    "ts-node": "3.3.0",
    "tslint": "5.7.0",
    "typescript": "2.4.0"
  }

Can someone help me? Thank you

**Comment by crisbeto** [comment]
This is a little hard to pinpoint based on the error alone. Can you post the Material modules that you're using?

**Comment by eamine84** [comment]
I use this:

import { MaterialModule } from '@angular/material';

**Comment by eamine84** [comment]
resolved updating covalent with 1.0.0-beta.7
