### ISSUE TITLE
Cannot npm install any of Material packages 

### ISSUE THREAD

**Issue by xe4me** [angular/material2#699]
I'm doing npm install @angular2-material/core

I'm getting : 

              `npm ERR! must have a URL that starts with http: or https:`

Looks like the server does not have the packages.

I've tried : 

 npm set registry https://registry.npmjs.org/
No success .

npm set registry http://registry.npmjs.org/

No success.

node v5.10.1
npm  v3.8.3

**Comment by jelbourn** [comment]
[The packages are definitely there](https://www.npmjs.com/~angular2-material).This is almost certainly a problem with your environment, which we unfortunately cannot debug.
