### ISSUE TITLE
Issue with backdropClick working in IE and Edge

### ISSUE THREAD

**Issue by dfmmalaw** [angular/material2#6993]
#### Bug, feature request, or proposal:
I have `disableClose ` set to true to stop my dialog from closing when user clicks on backdrop, and then I am using `backdropClick ` in the below code to tell a service that the backdrop was clicked. It works fine in Chrome but not in IE or Edge

```
dialogRef.backdropClick()
      .subscribe(() => {
          this.testService.testEvent.emit(true);
        }
      );

```
#### What is the expected behavior?
When user click on backdrop then even should be emitted and service should be informed

#### What is the current behavior?
This is not occuring

#### What are the steps to reproduce?
Use the code above with a console.log() to see that it is not being triggered.

#### What is the use-case or motivation for changing an existing behavior?
When a user clicks outside the dialog (with a form) we need to prompt the user to either save or discard their changes to the dialog formControls. Essentially, 

```
if (myDialogForm.dirty) { 
triggerConfirmationDialog();
}
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
The issue is specific to IE and Edge

#### Is there anything else we should know?
No

**Comment by crisbeto** [comment]
I wasn't able to reproduce it in our demo app @dfmmalaw. Are you sure that there isn't something else in your app that is preventing the stream from emitting?

**Comment by josephperrott** [comment]
Please provide a reproduction case so we can investigate further

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
