### ISSUE TITLE
Material source code folder doesnt open in vscode

### ISSUE THREAD

**Issue by ngmgit** [angular/material2#7002]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The title bar shows that the folder is opened and the files and folder should be visible in the sidebar.

#### What is the current behavior?
Folder is not opened and the files and folder are not visible in the sidebar but the title bar shows the folder is opened correctly. If the parent folder is opened there is no issue and check the attached pictures

when opened directly 
![material](https://user-images.githubusercontent.com/10939602/30319565-de3b324c-97cd-11e7-8747-6e5ea2e1452d.png)

When open by selecting the parent folder
![material_parent](https://user-images.githubusercontent.com/10939602/30319630-03e25368-97ce-11e7-9553-5078b3e8b9c3.png)

#### Is there anything else we should know?
OS: Arch

**Comment by Chan4077** [comment]
This has **nothing** to do with the material2 source code at all!

You should post this issue [here](https://github.com/Microsoft/vscode/issues).

**Comment by ngmgit** [comment]
Yes i was not sure if i should post it here or vscode since material source is only folder which is effected, ty.
Will post it over there.

**Comment by josephperrott** [comment]
Closing as this seems to be an issue in VSCode.
