### ISSUE TITLE
Tabs html content not rendered

### ISSUE THREAD

**Issue by RicardoVaranda** [angular/material2#701]
When using the latest version I am trying to insert a component into the content of the tab but it doesn't render, I've tried looking for a workaround online but haven't seem to have found a solution as of yet, does anyone know how I can achieve this:

Example:

```
export class RootComponent implements OnInit {

  @Input() trial : String;

  asyncTabs: Observable<any>;
  tabs = [
    { label: ' One', content: '<app-component></app-component>' },
    { label: ' Two', content: 'This is the body of the second tab' },
    { label: ' Three', content: 'This is the body of the third tab' },
  ];

  constructor() {

    this.asyncTabs = Observable.create((observer: any) => {
      setTimeout(() => {
        observer.next(this.tabs);
      }, 1000);
    });
  }
  ngOnInit() {
  }

}

```

Will simply output <app-component> in the content of the tab. I've attempted to use innerHTML but achieved the same result:

`<div [innerHTML]="tab.content"></div>`

I get that all the innerHTML content is sanitized and more than likely explains why this is happening just trying to find the correct way to make it handle html

**Comment by jelbourn** [comment]
Blindly binding HTML content is a recipe for a security disaster- doing this by simply binding `innerHTML` won't work with Angular out of the box. There will soon be more comprehensive documentation on [angular.io](https://angular.io) on how to render out safe HTML content. Closing this as it doesn't really have anything to do with material.

**Comment by RicardoVaranda** [comment]
@jelbourn Thanks for the explanation are you able to provide me with a temporary way of being able to do this as it is currently blocking the rest of my app progression?
