### ISSUE TITLE
Change Background Color with Ripple

### ISSUE THREAD

**Issue by rvoltolini** [angular/material2#7014]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
![npvci](https://user-images.githubusercontent.com/30928235/30331243-a5cce5ec-97ad-11e7-8acb-a556469ed8a2.gif)

It's possible make this background effect using Ripple?

**Comment by josephperrott** [comment]
We have no plans to build a feature like this as it is not something that is within the Material Design spec
