### ISSUE TITLE
Incorrect date md-datepicker localization Thai language

### ISSUE THREAD

**Issue by medeirosrich** [angular/material2#7017]
#### Bug, feature request, or proposal:
md-datepicker Locale 'th' (Thai) is displaying the wrong year. 

#### What is the expected behavior?
Input and datepicker should be in the correct year

#### What is the current behavior?
Input is displaying year in distant future. DatePicker is set to a different year in the distant future. 

#### What are the steps to reproduce?
1) set locale to 'th' in @NgModule
2) create datepicker with today's date

https://plnkr.co/edit/6guQWJyfAUtEgPje9Tcd?p=preview 

#### What is the use-case or motivation for changing an existing behavior?
Bug fix

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta.10

**Comment by josephperrott** [comment]
It looks like this is actually working as expected.  I am seeing the same thing myself when I load using the `th` local.  I looked into and found that "Thailand mainly uses the Buddhist calendar which is 543 years ahead of the Gregorian calendar." [[source]](https://en.wikipedia.org/wiki/Date_and_time_notation_in_Thailand)
