### ISSUE TITLE
MD_SNACK_BAR_DATA doesn't exist

### ISSUE THREAD

**Issue by kevinbeal** [angular/material2#7025]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
For `MD_SNACK_BAR_DATA` to be imported via: 

```ts
import { MD_SNACK_BAR_DATA } from '@angular/material';
```

This is what the documentation asks you to do for snackbars with custom templates.
https://material.angular.io/components/snack-bar/overview#sharing-data-with-a-custom-snack-bar

#### What is the current behavior?
Module '"/my/project/path/node_modules/@angular/material/material"' has no exported member 'MD_SNACK_BAR_DATA'.

#### What are the steps to reproduce?

Adding `import { MD_SNACK_BAR_DATA } from '@angular/material';` should do it.

#### What is the use-case or motivation for changing an existing behavior?

Maybe nothing. Maybe there is a new better way that is undocumented.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Typescript 2.4.2 / Angular 4.3.4 / Angular Material 2.0.0-beta.10

#### Is there anything else we should know?

It could be that the documentation is just behind. Maybe it's not a bug

**Comment by josephperrott** [comment]
It should be available, we set the injection token [here](https://github.com/angular/material2/blob/master/src/lib/snack-bar/snack-bar.ts#L198).

Are you able to reproduce this in a plunkr?  I was unable to myself, it's possible your environment is stale.  

Could you try clearing your `node_modules` and re `npm install`ing?

**Comment by josephperrott** [comment]
Closing as the injection token is defined in source code.

**Comment by danitt** [comment]
same issue, but *only affecting CI machine* so may be system-specific

angular lints and compiles normally when executed locally

"@angular/core": "^4.4.3",
"@angular/material": "^2.0.0-beta.11",
"typescript": "~2.5.3"

Error:
Module "node_modules/@angular/material/material"' has no exported member 'MdSnackBar'
