### ISSUE TITLE
theming

### ISSUE THREAD

**Issue by rui-cruz** [angular/material2#7029]
#### Bug, feature request, or proposal:
Don't know..

#### What is the expected behavior?
Theme should apply background and contrast colors

#### What is the current behavior?
Don't apply..

#### What are the steps to reproduce?
I'm using the demo-app inside electron, I have the css to switch from dark/light theme:
>@import '~@angular/material/theming';
@include mat-core();
$app-primary: mat-palette($mat-yellow, A700);
$app-accent:  mat-palette($mat-grey, 400);
$dark-theme: mat-dark-theme($app-primary, $app-accent);
@include angular-material-theme($dark-theme);
.light-theme {
  $light-theme: mat-light-theme($app-primary, $app-accent);
  @include angular-material-theme($light-theme);
}

All components get the theme, but the background don't! 
I tried to "hack" setting the background-color on the css, but this way I don't get the contrast colors..

Texts inside md-card get the correct color, but outside don't.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "4.3.5",
"@angular/material": "^2.0.0-beta.10",
"@angular/flex-layout": "^2.0.0-beta.9",
"material-design-icons": "^3.0.1"

"css-loader": "0.28.4",
"cssnano": "3.10.0",
"electron": "1.7.5",
"typescript": "2.5.0",
"sass-loader": "6.0.6",
"script-loader": "0.7.0",
"style-loader": "0.18.2",
"stylus-loader": "3.0.1",

#### Is there anything else we should know?
I'm using webpack 3.3.0

**Comment by willshowell** [comment]
You need to add `mat-app-background` to your wrapper element. You get it for free when you use a sidenav container, but it's mentioned at the bottom of [this section](https://material.angular.io/guide/theming#using-a-pre-built-theme). Could probably be more prominent...

**Comment by josephperrott** [comment]
Closing, as mentioned you could use mat-app-background.
