### ISSUE TITLE
[Bug] Fast tab switch forces scroll up

### ISSUE THREAD

**Issue by ricardo-yuxi** [angular/material2#7032]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
The tab should switch without triggering any scroll.

#### What is the current behavior?
When you switch tabs after making any scroll, the pages try to scroll up to the beginning of the page

#### What are the steps to reproduce?
Take a look at the last gif about the tabs example, here's the URL:
https://material.angular.io/components/tabs/api

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "~4.1.0"
"@angular/material": "^2.0.0-beta.8"
Browsers: Google Chrome@60.0.3112.113
Safari@10.1

#### Is there anything else we should know?
This behavior can be seen in the next 2 gifs:
![material-bug](https://user-images.githubusercontent.com/15000558/30352162-3049288a-97e4-11e7-90c4-aa21aac3e8b1.gif)
![material-bug-2](https://user-images.githubusercontent.com/15000558/30352164-3381e2a8-97e4-11e7-9d4a-83047714e384.gif)

In the last one, you can see it even happens in material tabs example.

**Comment by donroyco** [comment]
What's the browser that you're seeing this issue?

**Comment by ricardo-yuxi** [comment]
@donroyco in chrome and safari

**Comment by ricardo-yuxi** [comment]
@donroyco I updated the browser versions as requested.
