### ISSUE TITLE
Accordion bug with nested custom components

### ISSUE THREAD

**Issue by rabelloo** [angular/material2#7034]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should be able to use `md-expansion-panel`s within `md-accordion`s with an intermediate component normally

#### What is the current behavior?
`md-expansion-panel`s are not grouped by the `md-accordion`s if an intermediate component exists and behavior changes from normal

#### What are the steps to reproduce?
Have a component hold the `md-expansion-panel` inside a `md-accordion`.

```
<md-accordion>
  <nested-component></nested-component>
  <nested-component></nested-component>
</md-accordion>
```

http://plnkr.co/edit/kdKl7qk4K3AxsWKXqRWe?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It would be good to have `my-list-component` which defines the `md-accordion` with nested `*ngFor my-component` which in turn defines the `md-expansion-panel`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "4.3.5"
"@angular/cdk": "2.0.0-beta.10"
"@angular/material": "2.0.0-beta.10"

**Comment by willshowell** [comment]
Please see https://github.com/angular/material2/issues/6870#issuecomment-327847741 and the rest of that thread

> The design of `mat-accordion` and `mat-expansion-panel` requires the components to be tightly coupled for the management of animations and styling. This is the reason that `@Host` is present on the constructor for `mat-expansion-panel`. (Note: that `@Host` is not present on the `cdk-accordion-item` as this tight coupling is not necessary for the interactivity of the components.

**Comment by rabelloo** [comment]
Yes, my bad for not finding that issue before opening mine.

Even though I still think they should not be coupled, specially since Accordion is suggested to be moved to cdk, the alternate architecture discussed seems pretty good to me, I'll try to think differently about my components as well.

Thanks.
