### ISSUE TITLE
Expansion Panel content can oveflow vertically

### ISSUE THREAD

**Issue by KevinVillela** [angular/material2#7035]
#### What is the expected behavior?
We have the ability to make overflowing text be cut-off.

#### What is the current behavior?
I don't think there's a way to set a child element of md-expansion-panel-header to match the height of its parent, because of the mat-content span in between.

#### What are the steps to reproduce?
Take any example from https://material.angular.io/components/expansion/examples and just make the window very thin.

#### What is the use-case or motivation for changing an existing behavior?
It looks better when it is cut-off instead of bleeding into other elements. Not sure if there are Material recommendations here, the answer could really just be Don't have long text in your expansion panel header.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Most recent at the time of this writing.

**Comment by keltharan** [comment]
I am not sure but your problem is that your content of **md-expansion-panel-header** does not match the fixed height, am I right?
You can resolve it by adding **collapsedHeight="auto"** to the header.
 You can add padding to the collapsed header, so that it looks more attractive:
`md-expansion-panel-header[collapsedHeight="auto"]:not(.mat-expanded) {
    padding:10px;
}`

**Comment by KevinVillela** [comment]
Right, but the collapsedHeight solution expands the height of the header to fit the content, but I want the height of the content to match the header. I can hardcode the heights, but it would be nice if height: 100% would do it. Since I can do this without having to use ng-deep, I don't think it's very high priority, so I'll go ahead and close.

**Comment by pravinpokharkar** [comment]
use height: 100% for expansion panel header
