### ISSUE TITLE
bug(tabs) IE only: buttons/links not clickable inside tabs with scrolling

### ISSUE THREAD

**Issue by merlosy** [angular/material2#7040]
#### Bug, feature request, or proposal:

bug (IE 11)

#### What is the expected behavior?

On IE 11, buttons/links inside tabs should be clickable

#### What is the current behavior?

I have a tab, in which I have a lot a content and a button at the end, and I need to scroll dow to see the button.
On IE 11, the button/link is not clickable

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://plnkr.co/edit/mbtizQ

IMO there is an issue with the use of css transform (translate3d ?) on IE, looks like it messes up the dom and using the inspector, the enclosing html tag seems to be in front of the button.

#### What is the use-case or motivation for changing an existing behavior?

Well, it should be working

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

OS: Windows 10
Browser: IE 11, version 11.0.9600.18763 // updates versions: 11.0.45 // not tested on other IE version
Material beta 10 (not working on previous either, not a regression)
TS: 2.4.1

#### Is there anything else we should know?

I managed to get it to work but seems more like a hack that a fix.
I added the lines below in my main stylesheet:

```css
.mat-tab-body-active .mat-tab-body-content.ng-trigger.ng-trigger-translateTab:not(.ng-animating) {
    -ms-transform: none !important;
}
```
I'm not sure there is a better solution though

**Comment by julianobrasil** [comment]
Your plunk workes for me in IE 11/Windows 10 (without any additional styling):

![](https://media.giphy.com/media/l378rzqySV9VQe5eo/giphy.gif)

**Comment by merlosy** [comment]
I found this bug while working at my company.
I guess the system admin who install the software skipped some updates. 
My version seems older than yours though..

Any idea since when it is fixed? I'm worried with retro compatibility

**Comment by julianobrasil** [comment]
Later I'll be working in a kind of old environment. I'm not sure, but I think I'll find an IE 11 not updated yet. Then I'll try your plunk again. It's possible that someone of the material team see this issue earlier than that and fix it.

**Comment by julianobrasil** [comment]
Unfortunately the IE I found were older (IE 8). I could not test your plunk. Keep your workaround until someone takes care of it.

**Comment by josephperrott** [comment]
I was unable to reproduce the issue on IE11 as mentioned, can you confirm your [plunker](http://plnkr.co/edit/mbtizQ) is still not working for you?

**Comment by merlosy** [comment]
Plunkr was not working since beta-11 deprecated MdCoreModule, but not it's ok.
And I do confirm the issue is still there :/

For what is worth, I am using IE 11 as below (French):
![image](https://user-images.githubusercontent.com/6629784/30955440-f3bf7502-a433-11e7-9968-5b11f61a6d86.png)

**Comment by merlosy** [comment]
When I use the DOM explorer, it looks like the div below is in the foreground:
```html
<div class="mat-tab-body-content ng-trigger ng-trigger-translateTab" 
    style="transform: translate3d(0%, 0px, 0px);"> 
    [...]
</div>
```

The element is what lead me to the "fix" :
```css
.mat-tab-body-active .mat-tab-body-content.ng-trigger.ng-trigger-translateTab:not(.ng-animating) {
    -ms-transform: none !important;
}
```
PS: I set these lines on my main stylesheet, so I don't need deprecated shadow piercing /deep/

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
