### ISSUE TITLE
mdMenu expected behaviour not happening

### ISSUE THREAD

**Issue by gaspaonrocks** [angular/material2#7042]
#### Bug, feature request, or proposal:
Cannot get the expected behavior of mdMenu

#### What is the expected behavior?
Overlapping the button attached to it

#### What is the current behavior?
Opening after all elements of main app

#### What are the steps to reproduce?
I'm following the steps in Angular tutorial (Tour of Heroes) and the examples in the Material websites.
You can check the project on my repo gaspaonrocks/pomedapi

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using Angular4, Material2 and Windows10

#### Is there anything else we should know?
I tried to look for an answer but the only thing remotely similar was on a beta version... 
It might have to do with the browser. I tried the latest Firefox but it didn't help. 

Any help would be much appreciated.

**Comment by josephperrott** [comment]
Can you provide a reproduction of the issue?  I was not able to see this issue within [a plunker](https://plnkr.co/edit/?p=preview).

**Comment by willshowell** [comment]
@gaspaonrocks the repo you listed https://github.com/gaspaonrocks/pomedapi does not even include angular/material or angular/cdk.

**Comment by gaspaonrocks** [comment]
@willshowell yes, sorry for that. Since i posted this 2 weeks ago i thought the issue died... Yesterday i tried several other css frameworks since i couldn't get angular material to work...

Somebody at work told me that angular 4 might have compatibility issues with material 2. Is it true ?

Anyway i might try it again some other time.

Sorry for the inconvenience, and thanks anyway !
