### ISSUE TITLE
<md-card-content> breaks <md-select> vertical alignment

### ISSUE THREAD

**Issue by raceloop** [angular/material2#7044]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

All inputs vertically align.

#### What is the current behavior?

If a select is placed next to an input inside an `<md-card-content>` there is an alignment issue.

#### What are the steps to reproduce?

See this Plunk

http://plnkr.co/edit/eVQA4NAMfWQ9kjpvl5RR?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Correct layout required.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material 2.0.0-beta.10
Angular 4.3.6
flex-layout 2.0.0-beta.9

**Comment by willshowell** [comment]
`.mat-card-content` sets the font size to 14px which decreases the form field's height

**Comment by raceloop** [comment]
For now the work around is to override the `.mat-card-content` style by setting the font-size to 16px. Not ideal...

**Comment by willshowell** [comment]
I think moving select to work inside form-field will fix this (https://github.com/angular/material2/pull/6488). @mmalerba can you confirm?

**Comment by mmalerba** [comment]
yep, then select will also adapt to the current font-size

**Comment by raceloop** [comment]
@mmalerba @willshowell OK, thanks. Hopefully in the next release.

> current font-size

Do you mean the font-size of the `<md-card-content>`?

**Comment by willshowell** [comment]
@raceloop yes. If inside `md-card-content`, both will inherit the font size of 12px and decrease in height. If outside `md-card-content` they will inherit whatever font size is set there (in this case, 16px).

**Comment by josephperrott** [comment]
Closed as #6488 was merged.
