### ISSUE TITLE
How it works: Color Mixin?

### ISSUE THREAD

**Issue by Stoom** [angular/material2#7047]
Hi material 2 devs,

I am making a custom component and want to support the color attribute much like a `MdToolbar`.  I have seen that you're using mixins for color and disable, but I cannot figure out for the life of me how those get bound to the component as inputs.

Ref: https://github.com/angular/material2/blob/master/src/lib/core/common-behaviors/color.ts

Any thoughts on how this works and how I can do a similar thing in my component, or what I'm missing?

Cheers!

**Comment by DevVersion** [comment]
```ts
export class MyComponentBase {
  constructor(public _renderer: Renderer2, public _elementRef: ElementRef) {}
}
export const _MyComponentMixinBase = mixinColor(MyComponentBase, 'accent');

@Component({
  ...
  inputs: ['color']
})
export class MyComponent extends _MyComponentMixinBase implements CanColor {

  constructor(renderer: Renderer2, elementRef: ElementRef) {
    super(renderer, elementRef);
  }
}
```

The mixin basically is responsible for applying CSS classes that are based on the selected theme palette.

```scss

my-component {
  &.mat-primary {}
  &.mat-accent {}
  &.mat-warn {}
}

```

**Comment by Stoom** [comment]
Aaah the `input` on the `@Component` is what I was missing... Thanks!!!

**Comment by yogeshgadge** [comment]
The problem with 

`
inputs: ['color']
`

is that it creates linting issues suggesting we use `@Input` bindings. which if you did use what would be the type of it ?

`
@Input() color: ThemePalete
` 

or 
`
@Input() color: any
` 

When using `ThemePalete` I am getting 
> "export 'ThemePalette' was not found in '@angular/material'

So my take is that the CanColor/mixinColor is not really ready for us to use.

**Comment by willshowell** [comment]
@yogeshgadge It's `ThemePalette` not `ThemePalete`

**Comment by LayZeeDK** [comment]
**@angular/material@5.2.4**
When I use `mixinColor` like in `MatToolbar`, I get this error when running my app:

```
my-material.component.html:5 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at MyMaterialComponent.set [as color] (core.es5.js:277)
    at updateProp (core.js:12661)
    at checkAndUpdateDirectiveInline (core.js:12368)
    at checkAndUpdateNodeInline (core.js:13935)
    at checkAndUpdateNode (core.js:13878)
    at debugCheckAndUpdateNode (core.js:14771)
    at debugCheckDirectivesFn (core.js:14712)
    at Object.eval [as updateDirectives] (my-material.component.html:5)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14697)
    at checkAndUpdateView (core.js:13844)
```

I tried running the app with JIT, with AOT, with same version of `core-js`, `rxjs` and `zone.js` as the Angular Material source code.

**Comment by johnedvard** [comment]
I am trying to get my head around why we need to use 

`export function mixinColor<T extends Constructor<HasElementRef>>` 
instead of just
`export function mixinColor<T extends HasElementRef>`

Doing the latter gives me an error in VS Code: "Type 'typeof (Anonymous class)' is not assignable to type 'T'.", but I do not understand why. Can someone please enlighten me?

I am also wondering why one need to define a type: 
`export type Constructor<T> = new (...args: any[]) => T;`
Is it equivalent to write it like this instead?
```
export interface Constructor<T> {
    new(...args: any[]): T
}
```
I am not getting errors rewriting it, but maybe there is a (subtle) difference?
