### ISSUE TITLE
Using Flex-Layout breaks md-select overlay width

### ISSUE THREAD

**Issue by lpmusicon** [angular/material2#7048]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Using flex layout md-select options overlay width matches or is less than md-select width.

#### What is the current behavior?
Using flex, md-options overlay is overfilling md-select container.

#### What are the steps to reproduce?
Plunker: http://plnkr.co/edit/z83k0I0jAKKVjc1mjS1Z?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I believe this is a bug and should be fixed

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.6, Material 2.0.0 - beta.10, OS Windows 10 x64, TS 2.3.4, Opera 47.0.2631.80

#### Is there anything else we should know?
Shouldn't options overlay calculate width from it's children instead of using md-select width?

**Comment by donroyco** [comment]
Could you add a working code example to reproduce the issue? (The current one isn't working)

**Comment by lpmusicon** [comment]
@donroyco Hey, really sorry about the delay. Master was updated with Mat prefixes and I didn't have time to look into it. However looking into it now, It looks like overflow has been fixed.

Providing plunker that previously triggered the bug:
http://plnkr.co/edit/z83k0I0jAKKVjc1mjS1Z?p=preview
