### ISSUE TITLE
Feature Request: Multiselect with Checkboxes and Search/Filter Options

### ISSUE THREAD

**Issue by sanspace** [angular/material2#7052]
#### Feature request:
A Multiselect with checkboxes and search/filter functionality

#### What is the expected behavior?
http://softsimon.github.io/angular-2-dropdown-multiselect/

#### What is the current behavior?
https://material.angular.io/components/select/overview

#### What is the use-case or motivation for changing an existing behavior?
There are many occasions we would want the select to do more than selecting a single option.

#### Is there anything else we should know?
Nope

**Comment by crisbeto** [comment]
This is something that is planned and will be done in https://github.com/angular/material2/pull/6856 and https://github.com/angular/material2/pull/3211.

**Comment by sanspace** [comment]
Is there a milestone or a release to track this one?

**Comment by crisbeto** [comment]
There's no milestone on it, it depends on when https://github.com/angular/material2/pull/6856 gets merged.

**Comment by sanspace** [comment]
Got it. I'll subscribe to #6856 then. Thank you!

**Comment by mbtakanov** [comment]
What's the current status of the request?

**Comment by iamshouvikmitra** [comment]
Any updates?
