### ISSUE TITLE
Instructions in Getting Started for hammerjs are incomplete for developers using Systemjs.config

### ISSUE THREAD

**Issue by mLaird** [angular/material2#7057]
#### Bug, feature request, or proposal:
Bug. Documentation, as stated, does not work for developers using systemjs.config

#### What is the expected behavior?
Getting Started should truly get a developer started.

#### What is the current behavior?
Various 404 messages appear, depending on what you do.

#### What are the steps to reproduce?
Follow instructions in Section 5 of Getting Started to install hammerjs for an app using systemjs.config

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Getting Started should truly get a developer started.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.6,
"@angular/material": "2.0.0-beta.10",
Windows 10

#### Is there anything else we should know?
The current documentation says:

After installing, import it on your app's entry point (e.g. src/main.ts).
import 'hammerjs';

An additional statement should be added, saying:
If you use Systemjs, add the following to the map array in your systemjs.config file
'hammerjs': 'npm:hammerjs/hammer.min.js'

**Comment by josephperrott** [comment]
Covered by #7918
