### ISSUE TITLE
Only attach on initial view of a tabs content.

### ISSUE THREAD

**Issue by josephperrott** [angular/material2#7061]
Building on #6832, tabs should allow for lazy loading to only occur for initial load, then reuse already created view.

This will be important for holding the current state of something like a form, as well as no requiring reinitialization of more costly views.

**Comment by josephperrott** [comment]
Really this should be stated as no detaching the view when the tab leaves the view, instead just hiding it.  This does not directly necessitate building off of #6832, but will likely be added after its merged.

**Comment by josephperrott** [comment]
@jelbourn Is this something you still think we should do?  I know that we have tests that will be effected by this, though its functionality is not breaking.

**Comment by jelbourn** [comment]
I think we need to measure what kind of on impact it would actually have
