### ISSUE TITLE
Provide a way to align md-select, md-form-field and free text

### ISSUE THREAD

**Issue by swftvsn** [angular/material2#7064]
#### Bug, feature request, or proposal:
Bug / Feature request

#### What is the expected behavior?
When I create a table row I expect all items in the row to horizontally align.

#### What is the current behavior?
All md-form-fields align correctly, but md-select is a tad lower + free text is really hard to get to align.

#### What are the steps to reproduce?
Create a table and add various items to the same row

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://embed.plnkr.co/WPD5SUQoMVfLFgiV8gIH/ 

#### What is the use-case or motivation for changing an existing behavior?
User experience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
md-select and md-form-field (and the contained input) should just align. There should also be a component, that would allow the display of text that would add the required paddings and margins to align.

**Comment by donroyco** [comment]
See #2124

**Comment by julianobrasil** [comment]
@swftvsn, It'll probably bi fixed with #6488.

**Comment by josephperrott** [comment]
Marking as closed as this was addressed in #6488
