### ISSUE TITLE
NPM warning after install icon

### ISSUE THREAD

**Issue by reinos** [angular/material2#707]
Installing the icon module `npm install @angular2-material/icon --save` gives me a warning

`npm WARN @angular2-material/icon@2.0.0-alpha.5-2 requires a peer of @angular/http@2.0.0-rc.1 but none was installed.`

I had already the RC-2 `@angular/http@2.0.0-rc.2` installed but the icon component is searching for the rc-1

**Comment by jelbourn** [comment]
The dependency hasn't been updated for the latest `@angular` release. You should be able to ignore the warning until the next release.
