### ISSUE TITLE
MdSlideToggle: change event is triggered before the model's value is updated

### ISSUE THREAD

**Issue by MatthieuBarthel** [angular/material2#7074]
#### Bug, feature request, or proposal:
Bug (it is the only form control that acts like this and it wasn't the case on beta 8)

#### What is the expected behavior?
When the change event is triggered the model's value should already reflect the new value.

#### What is the current behavior?
When the change event is triggered, the model value is not updated and still reflects the old value.
This happens with template-driven and reactive forms.

#### What are the steps to reproduce?
http://plnkr.co/edit/6x5qfWWRwJFb32yr4UX4?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta 10

**Comment by RaphyLi** [comment]
You can use the formControl until the pull to be approuved and included in next update.
