### ISSUE TITLE
demo-app: Host publicly

### ISSUE THREAD

**Issue by saumyatripathi** [angular/material2#7077]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
demo-app from the master branch to be hosted.

#### What is the current behavior?
Could not find any hosting. The official website shows stale examples and documentation. (I of course understand that it's  not always possible to keep it up to date)

#### What are the steps to reproduce?
NA

#### What is the use-case or motivation for changing an existing behavior?
This will help users look at the latest functionality and see what to expect in future releases. Also, the demo-app in my opinion has a lot more examples and use cases as compared to official websites.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
NA

#### Is there anything else we should know?
You guys have done an amazing job providing these components to the community. Thanks a lot to all the contributors.

**Comment by donroyco** [comment]
You can run the app locally on your machine, but I think it's good to point out in the docs that there are a lot more examples in the demo-app.

**Comment by willshowell** [comment]
While it would be cool if the latest release and snapshot builds were all automatically deployed, you can do it yourself by setting up a firebase project and using

```
gulp deploy:devapp
```

to deploy to your current firebase project.

**Comment by saumyatripathi** [comment]
I understand I can run it locally/ deploy on a web server. In fact, that's what I've been doing in the past. This was a mere suggestion given that we already have servers and domains running for material2.

From a starter standpoint, the official website helped me a lot but now that I've come to use it in different (sometimes relatively complicated) scenarios, I find myself going to the demo-app/source code a lot (which I have no problem doing). 

Thanks for all the help and contributing to this project which has made lives of a lot of developers (including myself) so easy. Cheers!

**Comment by jelbourn** [comment]
We only intend the "demo-app" in the source to be used for our own development (it should really be called "dev-app"). All of the public facing demos should live on material.angular.io. I do want to have a "HEAD" version of the docs site (similar to AngularJS Material), but we haven't had the chance to build that out yet.
