### ISSUE TITLE
Slide-toggle fires change event on load

### ISSUE THREAD

**Issue by rafikk** [angular/material2#709]
#### Bug, feature request, or proposal:

Slide-toggle triggers change event on initialization if initial value of "checked" is true.

#### What is the expected behavior?

The event should only be fired in response to an interaction.

#### What is the current behavior?

The component fires the event before any user action has occurred.

#### What are the steps to reproduce?

Plunkr to reproduce here: http://plnkr.co/KCZtmelCWK6JKj0FDlh6

#### What is the use-case or motivation for changing an existing behavior?

If the app triggers an expensive operation, e.g. an API request, in response to the change event, this results in misfired updates and slows load time.

#### Which versions of Angular, Material, OS, browsers are affected?

All.

#### Is there anything else we should know?

I don't think so. :)

**Comment by DevVersion** [comment]
I just confirmed that with `master` and it seems not to appear anymore.

**Comment by jelbourn** [comment]
@DevVersion checkbox and radio use an `_isInitialized` flag to prevent this; slide-toggle might need to do the same

**Comment by DevVersion** [comment]
@jelbourn We already chatted about on the initial PR, but this bug is not noticeable in the `md-slide-toggle` component.

I've created a PR, which adds a test, which confirms that the `change` event isn't triggered multiple times after initialization and in general.

**Comment by rafikk** [comment]
@DevVersion did you see the Plunkr I posted? The change event is definitely triggered on load in the example. I'm not referring to triggering the event "multiple" times, but rather triggering the event without user or program interaction.

**Comment by DevVersion** [comment]
@rafikk I definitely see the issue. But the Plunker is running on Alpha.5 instead of `master`, which contains various changes.

**Comment by jelbourn** [comment]
Closing based on @DevVersion's assessment.

**Comment by DevVersion** [comment]
@rafikk @jelbourn I'm sorry for the trouble. I was quite distracted this week.

I completely misunderstood the issue.
- Thanks again @rafikk for the friendly ping.

---
I've updated the PR and added the correct fix (as done in the other components).

**Comment by jelbourn** [comment]
Whoops, we mistook this for a different issue.
