### ISSUE TITLE
mdTextareaAutosize setValue with invisible text

### ISSUE THREAD

**Issue by gise88** [angular/material2#7095]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
area with visible text

#### What is the current behavior?
when you try to setValue() on a textarea, initialized when it was hidden, with `mdTextareaAutosize` the text will be invisible

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-8cfvub

**Comment by crisbeto** [comment]
I couldn't reproduce it in our demo app. Is it still an issue?

**Comment by gise88** [comment]
You are right! Fixed in beta 11
