### ISSUE TITLE
Autocomplete should render selected options like other autocomplete plugin

### ISSUE THREAD

**Issue by tom10271** [angular/material2#7096]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Autocomplete should render selected options like other autocomplete plugin

#### What is the current behavior?
It is show the selected option's value directly.

#### What are the steps to reproduce?
https://plnkr.co/edit/nRuvA1O8VykbS6MV21KH?p=preview

#### What is the use-case or motivation for changing an existing behavior?
In many cases we list a bunch of objects with attributes: `id`, `name`. We always want to show name to user and set id to form field. Many existing plugins(selectize, typeahead, select2, choices.js) handle it as mentioned. Angular Material 2 is showing value, it is bad for user.

https://selectize.github.io/selectize.js/

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0 beta 10

**Comment by julianobrasil** [comment]
Take a look at [autocomplete docs](https://material.angular.io/components/autocomplete/overview#setting-separate-control-and-display-values). It does what you you are saying out-of-the-box.
