### ISSUE TITLE
[Tooltip] Cannot select elements with tooltips attached

### ISSUE THREAD

**Issue by patrikbjork** [angular/material2#7097]
#### Bug, feature request, or proposal:
The text within an element having a tooltip can't be selected. Also the cursor doesn't change to text cursor in Firefox.

#### What is the expected behavior?
The text should be selected either by dragging the cursor or by double-clicking.

#### What is the current behavior?
The text cannot be selected and in Firefox the cursor doesn't change to text cursor.

#### What are the steps to reproduce?
Go to https://material.angular.io/components/tooltip/overview and try to select the text "I have a tooltip".

#### What is the use-case or motivation for changing an existing behavior?
The user may want to select and copy the text.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested version is Angular 4.3.6, Material 2.0.0-beta.10 on Chrome and Firefox.

**Comment by crisbeto** [comment]
This seems like it's the same issue as https://github.com/angular/material2/issues/6484. Hammer adds `user-select: none` on the host element.
