### ISSUE TITLE
Can't add custom theme in 2.0.0-beta-10

### ISSUE THREAD

**Issue by intergalactickraigor** [angular/material2#7105]
Getting the following when attempting to add _theming.scss to my custom "theme.scss" file.
 
```
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/@angular/material/_theming.scss
Module build failed: Missed semicolon (56:49)

  54 | 
  55 |   .cdk-overlay-backdrop {
> 56 |     // TODO(jelbourn): reuse sidenav fullscreen mixin.
     |                                                 ^
  57 |     position: absolute;
  58 |     top: 0;
```

I am using the AngularCLI with webpack to build the project.  I recently had to add all of the "cdk" packages just to build the project.  I am having difficulty understanding where/when to update libraries as this project has been growing over the past year.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
