### ISSUE TITLE
Media Query (md-media)

### ISSUE THREAD

**Issue by DerekTBrown** [angular/material2#711]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Enable md-media function which handles Media Requests

#### What is the current behavior?
Not Implemented

#### What is the use-case or motivation for changing an existing behavior?
Implemented in Angular Material:
https://github.com/angular/material/blob/a8473e958990d4c53b4d9468bc56da3415052bac/src/core/util/media.js

**Comment by jelbourn** [comment]
This is something that would fall under helpers for response layouts in #45
