### ISSUE TITLE
 Unable to access Icons across different modules in app

### ISSUE THREAD

**Issue by pankajsri03** [angular/material2#7121]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
 Unable to access Icons across different modules in app.

#### What is the current behavior?

I have  registered mdIconRegistry  in app.module.ts as shown below:
export class AppModule {
  constructor(private mdIconRegistry: MdIconRegistry, private sanitizer: DomSanitizer) { mdIconRegistry.addSvgIcon('settings',sanitizer.bypassSecurityTrustResourceUrl('assets/images/icons/settings.svg'))
} } 

I have registered  mdIconRegistry in app.module.ts  Providers array as well.

I am able to access icons in the components belonging to app.module but i am unable to access icons in different modules.
Do i need to register icon in other modules as well? Can't we have a single registration throughout the app.

**Comment by josephperrott** [comment]
Closing as working as expected.

You are able to use the icon in the module it is registered in as well as any of that modules children modules.  However this registry does not cross to sibling modules.
