### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by intersplice** [angular/material2#7127]
Closes #7127
#### Bug, feature request, or proposal:
Bug
I'm trying to setup angular material, but i'm getting this error...

Console:

`Error: Unexpected token <
  Evaluating http://localhost:30815/node_modules/@angular/cdk/bundles/cdk.umd.js/a11y
  Evaluating http://localhost:30815/app/core/material-components.module.js
  Evaluating http://localhost:30815/app/app.module.js
  Evaluating http://localhost:30815/app/main.js
  Loading app
    at eval (<anonymous>)
    at evaluate (system.src.js:2822)
    at system.src.js:3625
    at dynamicExecute (system.src.js:1145)
    at doEvaluate (system.src.js:1092)
    at ensureEvaluate (system.src.js:1000)
    at system.src.js:1018
    at doEvaluate (system.src.js:1090)
    at ensureEvaluate (system.src.js:1000)
    at system.src.js:1018`

**systemjs.config.js**

`map: {
    ...,
 '@angular/material':                    'npm:@angular/material/bundles/material.umd.js',
}`

I've loaded all material components into one central file called material-components.module

My app.module.ts

`import { NgModule } from '@angular/core';`
`import { APP_BASE_HREF } from '@angular/common';`
`import { BrowserModule } from '@angular/platform-browser';`
`import { ReactiveFormsModule } from '@angular/forms';`
`import { HttpModule } from '@angular/http';`
`import { MaterialComponentsModule } from './core/material-components.module';`
`import { AppComponent } from './app.component';`
`import { routing } from './app.routing';`
`import { HomeComponent } from './components/home.component';`

`@NgModule({`
    `imports: [BrowserModule, ReactiveFormsModule, HttpModule, routing, `
     `MaterialComponentsModule],`
   ` declarations: [AppComponent, HomeComponent],`
    `providers: [{ provide: APP_BASE_HREF, useValue: '/' }],`
    `bootstrap: [AppComponent]`
`})`

`export class AppModule { }`

Here is the file

`import { NgModule } from '@angular/core';`
`import { CommonModule } from '@angular/common';`
`import {`
`    MdAutocompleteModule, MdButtonModule, MdCardModule, MdCheckboxModule,` `MdDatepickerModule, MdDialogModule,`
`    MdGridListModule, MdIconModule, MdInputModule, MdListModule,`
`    MdMenuModule, MdNativeDateModule, MdProgressBarModule, MdProgressSpinnerModule,` `MdRippleModule, MdSelectModule,`
 `   MdSidenavModule,`
  `  MdSliderModule,`
   ` MdSlideToggleModule, MdSnackBarModule, MdTabsModule, MdToolbarModule, MdTooltipModule`
`} from '@angular/material';`

`@NgModule({`
`    imports: [`
`        CommonModule`
 `   ],`
`    declarations: [],`
`    exports: [`
 `       MdInputModule,`
  `      MdTabsModule,`
   `     MdIconModule,`
    `    MdListModule,`
    `    MdButtonModule,`
    `    MdToolbarModule,`
    `    MdDialogModule,`
    `    MdMenuModule,`
    `    MdGridListModule,`
    `    MdCardModule,`
    `    MdSnackBarModule,`
    `    MdTooltipModule`,
    `    MdSliderModule,`
    `    MdAutocompleteModule,`
    `    MdDatepickerModule,`
    `    MdSlideToggleModule,`
    `    MdSidenavModule,`
    `    MdCheckboxModule,`
    `    MdNativeDateModule,`
    `    MdProgressBarModule,`
    `    MdProgressSpinnerModule,`
    `    MdSelectModule,`
    `    MdRippleModule`
    `]`
`})`
`export class MaterialComponentsModule { }`

My dependencies in package.json

"dependencies": {
    "@angular/common": "4.4.1",
    "@angular/compiler": "~4.4.1",
    "@angular/core": "~4.4.1",
    "@angular/forms": "~4.4.0",
    "@angular/http": "~4.4.1",
    "@angular/platform-browser": "~4.4.1",
    "@angular/platform-browser-dynamic": "~4.4.1",
    "@angular/router": "~4.4.1",
    "@angular/material": "^2.0.0-beta.6",
    "@angular/animations": "^4.3.0",
    "@angular/cdk": "^2.0.0-beta.6",
    "angular-in-memory-web-api": "~0.3.0",
    "systemjs": "0.20.18",
    "core-js": "^2.4.1",
    "rxjs": "5.4.2",
    "zone.js": "^0.8.4"
}

I already tried to remove 'node_modules' and reinstall.

#### What is the expected behavior?

No error, Getting Started

#### What is the current behavior?

Sending me error

#### What are the steps to reproduce?

Configuration error, see first question.

#### Which versions of Angular, Material, OS, browsers are affected?

lastest

#### Is there anything else we should know?

In first question.

**Comment by Chan4077** [comment]
Can you enclose your code in three backticks (```) to make it easier to read? Thanks.

Are you using the Angular CLI? If you are, you don't have to have a file named `systemjs.config.js`.

**Comment by intersplice** [comment]
Hi Sorry for the sloppy comment!

Yes I am. I've attached the systemjs,config.js - it has the mapping - map: { ..., '@angular/material': 'npm:@angular/material/bundles/material.umd.js', }

**Comment by Chan4077** [comment]
What I meant is this:

(Example for typescript:)
<pre lang="no-highlight"><code>```typescript
import {NgModule} from '@angular/core';
import {MdButtonModule, MdToolbarModule} from '@angular/material';
// ...

@NgModule([
    imports: [
        MdButtonModule,
        MdToolbarModule,
        // etc..
])
export class AppModule {}
```</code></pre>

[More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting)

What I meant in the above comment (about a `systemjs.config.js` file) is that you **don't need to have a SystemJS Config file** since you're using the angular CLI and that the angular CLI should do everything for you.

**Comment by intersplice** [comment]
Ah I see! I have less sloppy version here - https://stackoverflow.com/questions/46264091/angular-material2-unexpected-token

I'll try the suggestions you've made and get back to you! Thanks for taking the time :).

**Comment by Chan4077** [comment]
@intersplice Can you close this issue now that it is resolved? Thanks.
