### ISSUE TITLE
MdDatepicker demo component is broken 

### ISSUE THREAD

**Issue by aravindfz** [angular/material2#7128]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
No errors and component should render

#### What is the current behavior?
`dateInput` of undefined is logged in the console and breaks the app

#### What are the steps to reproduce?
Go to demo plunker from [here](https://material.angular.io/components/datepicker/overview#current-state)
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by julianobrasil** [comment]
It seems to be working fine for me.

Could you try to modifiy this plunk in order to reproduce it:  https://plnkr.co/edit/zqX55ZhBP04oejguhCWi?p=preview ?

### my screen:

![image](https://user-images.githubusercontent.com/25405143/30519871-1de563e8-9b77-11e7-8aca-5fff59caae74.png)

**Comment by aravindfz** [comment]
My screenshot was not attached my bad I m sorry. Closing it as it works fine now. If needed we shall reopen it.
