### ISSUE TITLE
Linting failing on master branch

### ISSUE THREAD

**Issue by shaunak1111** [angular/material2#7140]
#### Bug
Linting is failing due to unused imports on master branch

#### What is the expected behavior?
Lint test should pass on master branch

#### What is the current behavior?
It is failing

#### What are the steps to reproduce?
run gulp lint on master branch.

**Comment by crisbeto** [comment]
Based on the build for the latest commit, everything seems to be passing: https://travis-ci.org/angular/material2/jobs/276086599
