### ISSUE TITLE
[MdDatePicker] Validation gives no error state

### ISSUE THREAD

**Issue by codemasterover9000** [angular/material2#7141]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When a minimum date is entered, the input should present an error state if the user enters a date before the minimum date in the input field.

#### What is the current behavior?
While the datepicker itself prevents the selection of a date before the minimum, the user can still manually enter a date before the minimum, which does not result in an error state.

#### What are the steps to reproduce?
In the following Plunk, enter a date before 01-01-2000. This Plunk comes directly from the Datepicker Docs page, only the mdError was added by me.

https://plnkr.co/edit/skksuwrpTwIMO0UYfrFd?p=preview

#### What is the use-case or motivation for changing an existing behavior?
The user should receive a visual cue when the input is incorrect.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
The issue is present in Material 2.0.0-beta.10

**Comment by willshowell** [comment]
`MdError` shows based on whether the `NgControl` is valid. If you want to show error messages for invalid values, try hooking the control to a FormControl with a validator.

**Comment by codemasterover9000** [comment]
It seems an unrelated error and the wrong Google searches made me believe that the formControl property didn't work in conjunction with mdDatePicker. With that error resolved, the FormControl works. Closing since it's no longer a problem but simply user error on my part. Thank you for your time!
