### ISSUE TITLE
Change the position of the overlay of md-select

### ISSUE THREAD

**Issue by kirapoetica974** [angular/material2#7147]
#### Bug, feature request, or proposal:
Change the position of the overlay of the md-select

#### What is the expected behavior?
The position is calculate automatically by the private method _calculateOverlayPosition and the overlay is placed over the select field.

#### What is the current behavior?
The overlay can be placed on the bottom of the select field.

**Comment by josephperrott** [comment]
Closing as this is working as intended as the overlay is being placed automatically by the position rules.

**Comment by avinashrd** [comment]
@josephperrott Can you please let me know if it is possible to fix the postion of the mat-select overlay to the bottom of the select box?
