### ISSUE TITLE
Issue With Password Input in case of Autofill

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#7150]
#### Bug, feature request, or proposal:
When using material input for password fields and user has enabled browser autofill for that website, the password field with auto-filled value doesn't appear properly i.e. the placeholder text which is suppose to float above the password field is actually shown over the filed value i.e. ******.

When user click anywhere on page the placeholder text floats on top and password field becomes normal so apparently some change detection issue.

#### What is the expected behavior?
The placeholder text for password fields should float even if the value of the field comes from browser autofill.

![image](https://user-images.githubusercontent.com/7761180/30561954-49a4e728-9cd6-11e7-9f03-b6f62da4d7a9.png)

**Comment by josephperrott** [comment]
Duplicate #6837
