### ISSUE TITLE
Sidenav backdrop has no background color set

### ISSUE THREAD

**Issue by lexyfeito** [angular/material2#7152]
So i just updated to 2.0.0-beta.10 and my sidenav has not bacground-color set in the backdrop, where before used to be under `.mat-drawer-backdrop.mat-drawer-shown {
    background-color: rgba(0, 0, 0, 0.6);
}`. Is this expected or i am missing somthing, help please. Thank you

**Comment by willshowell** [comment]
The background color should not have changed. Can you provide more details? 

https://github.com/angular/material2/blob/bdadbad7dd443ff0af7a1d34bcb48dfcf2f63a31/src/lib/sidenav/_sidenav-theme.scss#L34-L36

**Comment by lexyfeito** [comment]
the background-color is not being set
`.mat-drawer-backdrop.mat-drawer-shown { 
   background-color: $drawer-backdrop-color; 
 } `
is not being applied. Can you please tell me how i could be more specific please (No irony intended)

**Comment by willshowell** [comment]
A screenshot like this would be helpful:

<img width="1675" alt="screen shot 2017-09-18 at 8 11 09 pm" src="https://user-images.githubusercontent.com/6475576/30570194-a60317ca-9cad-11e7-8891-e1fb487bda8f.png">

**Comment by lexyfeito** [comment]
I am sorry, my problem seems to be other, i am using a custom theme which i made following the docs, and it is what seems to be breaking the sidenav, because i changed it to one of the rebuilt that comes with angular/material and it works fine. Any idea why?

**Comment by lexyfeito** [comment]
btw it was working before beta.10

**Comment by willshowell** [comment]
Can you share the relevant css?

**Comment by lexyfeito** [comment]
got it. figure out the problem, i needed to recreate the .scc file since sidenav classes changed to .mat-drawer. Should be included in breaking changes right?

**Comment by willshowell** [comment]
See the [CHANGELOG](https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta10-découpage-panjandrum-2017-08-29):


> * **sidenav:** CSS classes have changed from `mat-sidenav-` to `mat-drawer-`

If you are not generating your theme files during your build process, you definitely need to when upgrading because the css always changes between releases for various bug fixes and features.

**Comment by lexyfeito** [comment]
yes i did see that i just didnt think about regenerating the css files again, my bad. thank you :)

**Comment by josephperrott** [comment]
Closing as the issue has been solved.
