### ISSUE TITLE
latest package on rawgit.com is beta.11?

### ISSUE THREAD

**Issue by parker-mike** [angular/material2#7158]
The "official" Plnker template(http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview), which by the way stopped working, uses rawgit.com to get material bundle(https://rawgit.com/angular/material2-builds/master/bundles/material.umd.js) and now it states:

> /**
> \* Current version of Angular Material.
> */
>var VERSION = new _angular_core.Version('2.0.0-beta.11-244c906');

**Comment by DevVersion** [comment]
Fixed the Plunker template. The `beta.11` thing will be fixed soon as well (as part of a new release)
