### ISSUE TITLE
npm install --save @angular2-material/{core,button,card} throws errors

### ISSUE THREAD

**Issue by Vaevictus** [angular/material2#716]
#### Bug, feature request, or proposal:
Bug or documentation improvement in getting started guide

#### What is the expected behavior?
material2 packages should install into my newly created project

#### What is the current behavior?
Following the getting started guide, the step where you perform `npm install --save @angular2-material/{core,button,card}` throws an error as follows:
`

> D:\Code\Infoserver\InfoserverAngular2>npm install --save @angular2-material/{core,button,card}
> npm ERR! addLocal Could not install D:\Code\Infoserver\InfoserverAngular2\@angular2-material\{core,button,card}
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@angular2-material/{core,button,card}"
> npm ERR! node v6.2.2
> npm ERR! npm  v3.9.5
> npm ERR! path D:\Code\Infoserver\InfoserverAngular2\@angular2-material\{core,button,card}
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR! syscall open
> 
> npm ERR! enoent ENOENT: no such file or directory, open 'D:\Code\Infoserver\InfoserverAngular2\@angular2-material\{core,button,card}'
> npm ERR! enoent ENOENT: no such file or directory, open 'D:\Code\Infoserver\InfoserverAngular2\@angular2-material\{core,button,card}'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent

`

#### What are the steps to reproduce?
create new project with angular-cli, cd to the new folder and execute npm install --save @angular2-material/{core,button,card}

#### Which versions of Angular, Material, OS, browsers are affected?
angular2 latest rc, OS windows 10

**Comment by Vaevictus** [comment]
realised that npm install --save @angular2-material/{core,button,card} should not be taken literally and you need to do npm install --save @angular2-material/core etc.
I am new to npm so thought {core,button,card} would install all three in one shot

**Comment by jelbourn** [comment]
The example is using [shell expansion](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_04.html).
