### ISSUE TITLE
Beta.10 breaks floating elements inside sidenav

### ISSUE THREAD

**Issue by twoheaded** [angular/material2#7170]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

It is necessary to place floating elements inside sidenav. 
In Beta.8 elements with styles:

    position: fixed;
    bottom: 0;
    right: 0;

and

    /deep/ .mat-sidenav-content {
      transform: none !important;
    }

works well.

#### What is the current behavior?

Floating elements that placed in a subcomponent inside the sidenav now doesn't fixed in bottom right of browser window.

The same thing is with position absolute in the sidenav [documentation example](https://material.angular.io/components/sidenav/examples). 

![sidenav angular material](https://user-images.githubusercontent.com/15314781/30594149-b61754f2-9d55-11e7-9168-89af215fda32.png)

#### What are the steps to reproduce?

Beta.10 also broke all the plunker examples in the documentation. Therefore, I can not greet the example. See the [documentation page](https://material.angular.io/components/sidenav/examples)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4.3.6, Material beta.10, Win10, TS 2.2.2, all current versions of brousers

**Comment by willshowell** [comment]
See https://github.com/angular/material2/pull/7108 for the example. CSS changes between beta releases so you need to update your css if you are overriding default behavior.

**Comment by twoheaded** [comment]
https://plnkr.co/edit/6UnTMCXSEdWzhAQJSLat?p=preview

Look at the right fab button. It moves when you scroll the content of sidenav. This should not happen.

**Comment by willshowell** [comment]
Oh my bad! Wrong PR... see https://github.com/angular/material2/pull/7099 instead 😄

**Comment by twoheaded** [comment]
`overflow: auto` and `height: 100%` applied to the scrolling content make my elements floating again, but  break my fxFlex column grid system 😄 But that's another story. Thanks!
