### ISSUE TITLE
Publishing of https://material.angular.io/ page code as one of the examples - a possible great help for beginners

### ISSUE THREAD

**Issue by maciejmaksymo** [angular/material2#7171]
Hello Material2 team,

Would there be a possibility for you to publish the code behind the 
https://material.angular.io/ page as one of the examples?

This would be a great help for beginners because that page is the most complex and robust example of an angular / material2 app I have seen to date.

I would love to see how you implented the layout on the
https://material.angular.io/components subpage

Best Regards,
Maciej

**Comment by crisbeto** [comment]
The docs site is open-source already. You can find it at https://github.com/angular/material.angular.io

**Comment by josephperrott** [comment]
@maciejmaksymo 

The code for material.angular.io is available on GitHub at https://github.com/angular/material.angular.io
