### ISSUE TITLE
[cdk]: overlay styles unavailable

### ISSUE THREAD

**Issue by willshowell** [angular/material2#7173]
#### Bug, feature request, or proposal:
Request (for tracking purposes)

#### Context
https://github.com/angular/material2/pull/6100

> @jelbourn:
>
> I plan on adding a overlay-prebuilt.scss in a follow-up PR

#### Other

While it looks like all of a11y is re-exported in the material bundle, `cdk-a11y()` doesn't seem to be a part of the cdk

https://github.com/angular/material2/blob/master/src/lib/core/a11y/_a11y.scss

cc @DevVersion

**Comment by DevVersion** [comment]
@willshowell Good point. That should be something very important for CDK standalone usage.

**Comment by jelbourn** [comment]
Yep, I forgot. @DevVersion could you take this? I probably won't have time this week.

**Comment by DevVersion** [comment]
@jelbourn Sure, I should be able to implement it similar as for the material package. Do we want to have multiple SCSS files for the different secondary entry-points? e.g.

* `_overlay.scss`
* `_a11y.scss`

**Comment by jelbourn** [comment]
@DevVersion for anything w/ styles, we want a partial (e.g., `_overlay.scss`) and a concrete file (e.g. `overlay-prebuilt.scss`).

**Comment by jelbourn** [comment]
Also worth mentioning that we _don't_ want to call the concrete file `overlay.scss` because it would make imports from client scss ambiguous

**Comment by DevVersion** [comment]
See: https://github.com/angular/material2/pull/7204

**Comment by willshowell** [comment]
closing via #7204
