### ISSUE TITLE
Disable free typing in autoComplete 

### ISSUE THREAD

**Issue by vibingopal** [angular/material2#7178]
#### Bug, feature request, or proposal:
Hi Team,

I am unable to disable free typing in the autoComplete list. Is there any event or property to disable it by default?

#### What is the expected behavior?
Autocomplete field should only allow user to select the option from the list instead of free typing the text field.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular -4.0
Material- 2.0.0-beta.10

Thanks

**Comment by julianobrasil** [comment]
Just mark the associated **`<input>`** as **`readonly`**: https://plnkr.co/edit/TLv97Z6ygeJDloyeMHPg?p=preview

**Comment by vibingopal** [comment]
Thank you
