### ISSUE TITLE
[Feature] Swipeable material design cards.

### ISSUE THREAD

**Issue by hemantjadon** [angular/material2#718]
#### Feature request:
Feature : A simple swipeable material card design. 

### Motivation : Use Case.
As we know that the cards of material-design spec are broady used in designing and configuring the page. And the cards like google now on android can be a neat feature and many times be a desirable behaviour.

#### What is the expected behavior?
The cards arranged inside `container`  should be swipeable.
The events must be fired on swipe start swipe end, an observable can track the swipe distance of card.

#### What is the current behavior?
There is no such current documented behaviour.

#### What are the steps to reproduce?
The basic outline of  steps can be : 
- Creating a container which contains series `<md-card> </md-card>`.
- Making each card swipable
- Hooking events/observables : onSwipeStart | onSwipeEnd | <observable>swipe
- After swipe-complete of card the cards below it should slide up.

#### Which versions of Angular, Material, OS, browsers are affected?
all

**Comment by jelbourn** [comment]
I don't see this as a feature that needs to be built _into_ any components. Nothing should be preventing you now from having a list of cards and gesture handlers that animate-out the target card. We will likely be adding more features in the future around using gestures in general, though.
