### ISSUE TITLE
md-toolbar reduces height 1px early

### ISSUE THREAD

**Issue by wyers** [angular/material2#7181]
#### Bug, feature request, or proposal:
I would like for the md-toolbar media query to fire on max-width: 599 instead of 600.
Light digging suggests this is being defined here: https://github.com/angular/material2/blob/master/src/lib/core/style/_variables.scss

#### What is the expected behavior?
'xs' should be < 600

#### What is the current behavior?
'xs' is <= 600

#### What are the steps to reproduce?

the provided plunkr template is sufficient, just reduce view area to 601px.
then reduce to 600px.

https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
alignment with flex-layout: https://github.com/angular/flex-layout/wiki/Responsive-API
and material spec: https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-breakpoints (suppose this one depends on which way you read it, but i consider the breakpoint non-inclusive.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest

#### Is there anything else we should know?
n/a

**Comment by willshowell** [comment]
Related https://github.com/angular/material2/issues/5960 and https://github.com/angular/material2/pull/6772#issuecomment-327245697

**Comment by josephperrott** [comment]
Closing as this is being handled in #6772
