### ISSUE TITLE
Mobile responsiveness ?

### ISSUE THREAD

**Issue by lakinmohapatra** [angular/material2#7182]
#### Bug, feature request, or proposal:

Feature request
#### What is the expected behavior?
mobile responsiveness

#### What is the current behavior?
No mobile responsiveness

Please add components for adding mobile responsiveness as like materialize.css grids.

**Comment by wyers** [comment]
there is a separate project that helps do this
https://github.com/angular/flex-layout

**Comment by josephperrott** [comment]
Closing as duplicate of #45
