### ISSUE TITLE
Hummerjs animations with deprecated material module

### ISSUE THREAD

**Issue by adwaer** [angular/material2#7187]
#### Bug, feature request, or proposal:
Hummerjs requires material module for working. But its deprecated. Im use MdProgressSpinnerModule and i want animated change slider position. But import hummerjs make this only with imported MaterialModule

#### What is the expected behavior?
slider animated move works without MaterialModule

#### What is the current behavior?
slider animated move doesnt works without MaterialModule

#### What are the steps to reproduce?
Angular 4 app with MdProgressSpinnerModule  and hummerjs without MaterialModule

**Comment by jelbourn** [comment]
MaterialModule just imports/exports MdSliderModule, shouldn't have anything to do with hammer. [Our docs site](https://github.com/angular/material.angular.io/) has this working without MaterialModule.

**Comment by adwaer** [comment]
MaterialModule - deprecated, man!
