### ISSUE TITLE
[performance] Weird behavior (zone related?)

### ISSUE THREAD

**Issue by manekinekko** [angular/material2#719]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

The user should check/uncheck the checkboxes without any issue. 
There should be no performance issues.

#### What is the current behavior?

App freezes because `zone.js` seems to enter in an infinite loop (see screenshot below)

#### What are the steps to reproduce?

Here [http://plnkr.co/edit/VWoFD33JedmlFWjIOpIN?p=preview](http://plnkr.co/edit/VWoFD33JedmlFWjIOpIN?p=preview)

#### Which versions of Angular, Material, OS, browsers are affected?

```
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/router": "3.0.0-alpha.3",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular2-material/button": "2.0.0-alpha.5-2",
    "@angular2-material/card": "2.0.0-alpha.5-2",
    "@angular2-material/checkbox": "2.0.0-alpha.5-2",
    "@angular2-material/core": "2.0.0-alpha.5-2",
    "@angular2-material/grid-list": "2.0.0-alpha.5-2",
    "@angular2-material/icon": "2.0.0-alpha.5-2",
    "@angular2-material/list": "2.0.0-alpha.5-2",
    "@angular2-material/sidenav": "2.0.0-alpha.5-2",
    "@angular2-material/toolbar": "2.0.0-alpha.5-2",
    "@angular2-material/progress-circle": "2.0.0-alpha.5-2",
    "angularfire2": "^2.0.0-beta.1",
    "es6-shim": "^0.35.0",
    "firebase": "^3.0.3",
    "es6-shim": "0.35.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "0.6.12"
  }
```

#### Is there anything else we should know?

![image](https://cloud.githubusercontent.com/assets/1699357/16173660/f01a343c-35a8-11e6-8071-c49a4b865b4c.png)

The app is frozen and unusable.
![image](https://cloud.githubusercontent.com/assets/1699357/16173676/66711f24-35a9-11e6-8ec3-ae1b343f0446.png)

**Comment by manekinekko** [comment]
This issue seems to come from this:
```
<md-checkbox [checked]="level.selected" (change)="level.selected = $event">
```

changing it to this, fixes the infinite loop:
```
<md-checkbox [(checked)]="level.selected">
```

**Comment by hansl** [comment]
In your case, this works as expected:

```html
<md-checkbox [checked]="level.selected" (change)="level.selected = $event.checked">
```

Note that the `$event` object has been changed for checkbox and is now of type `MdCheckboxChange` (see [here](https://github.com/angular/material2/blob/master/src/components/checkbox/checkbox.ts#L46)). Setting it as an object results in always being true (and will result in an invalid type assignment with the offline compiler).

Closing this as non-repro.
