### ISSUE TITLE
md-select not selecting value with setValue

### ISSUE THREAD

**Issue by wederfabricio** [angular/material2#7194]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When a FormControl call setValue method, the <md-select> show the value.

#### What is the current behavior?
When a FormControl call setValue method, the <md-select> don't show the selected value, only put the value into FormControl (I see in **console.log(formcontrol.value)**).

#### What are the steps to reproduce?

In component.html:
`<md-select class="col-md-3" placeholder="Tipo*" formControlName="clientType">
     <md-option *ngFor="let type of clientTypes" [value]="type">
          {{ type.description }}
      </md-option>
</md-select>`

In component.ts:

`this.clientForm.controls.clientType.setValue({id: '1', description: 'Test'})`

The field stay with the same value of placeholder, "Tipo*".

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.3
Material: 2.0.0-beta.8
OS: Windows 10
Browser: Chrome 60

#### Is there anything else we should know?
My english is very bad, sorry.

**Comment by julianobrasil** [comment]
If you have objects as options' value, you must use the **`compareWith`**. Otherwise, the by-ref default comparison will naver let it work right. Take a look at the https://github.com/angular/material2/issues/6970#issuecomment-328355857.

**Comment by wederfabricio** [comment]
Thanks! Closing this issue.
