### ISSUE TITLE
formBuilder {value: ..., disabled: ...) does not work with slide-toggle

### ISSUE THREAD

**Issue by zpydee** [angular/material2#7199]
the capability or reactiveforms to disable control seems not to work with slide-toggle, requiring the use of [disable]

**Comment by donroyco** [comment]
Please use the provided [issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md), otherwise your issue will get closed.

**Comment by zpydee** [comment]
Bug, feature request, or proposal:

Bug

What is the expected behavior?

should use reactive forms behavior

What is the current behavior?

does not

What are the steps to reproduce?

implement a slide toggle and try use `{value:..., disabled: ...}`

Providing a Plunker (or similar) is the best way to get the team to see your issue. Plunker template: https://goo.gl/DlHd6U

not necessary

What is the use-case or motivation for changing an existing behavior?

consistent forms control usage

Which versions of Angular, Material, OS, TypeScript, browsers are affected?

latest across the board

Is there anything else we should know?

nope

**Comment by willshowell** [comment]
@zpydee can you please provide a plunker to explain what you mean? Here is one showing what seems to be correct form control & disable behavior:

https://plnkr.co/edit/kUTJH16hHz6C0UFP035J?p=preview

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template (actually providing the information). Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by zpydee** [comment]
sorry, no time. just trying to alert you. i believe this error message from the forms module should explain the issue sufficiently.

the method proposed for `first` field does not work with the slide-toggle, thus my need to using `[disabled]` in my template.

```
It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
      when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
      you. We recommend using this approach to avoid 'changed after checked' errors.
       
      Example: 
      form = new FormGroup({
        first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
        last: new FormControl('Drew', Validators.required)
      });
```

**Comment by willshowell** [comment]
https://plnkr.co/edit/efuNdLhq9QM3YOcH98qj?p=preview
