### ISSUE TITLE
[md-sidenav] Sidenav content not positioned correctly when using animations on host component

### ISSUE THREAD

**Issue by srcn** [angular/material2#7201]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

When using md-sidenav with ```mode="side"``` & ```opened="true"``` attributes in an animated host component, sidenav content must be correctly positioned.

#### What is the current behavior?

Sidenav content stays underneath the sidenav itself. It doesn't get pushed like it should.

#### What are the steps to reproduce?

http://plnkr.co/edit/ilnPpy?p=info

#### What is the use-case or motivation for changing an existing behavior?

Components or their children elements can be animated for entering and leaving the dom.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular Material 2.0.0-beta.10

#### Is there anything else we should know?

This was working on Angular Material 2.0.0-beta.8 . Regardless of the animation type, adding a host binding for that animation to the host component breaks the sidenav:

```@HostBinding('@fadeIn') fadeIn = true;```

**Comment by josephperrott** [comment]
Example repro [here](http://plnkr.co/edit/dHCJsb?p=preview)

**Comment by mmalerba** [comment]
fixed example: https://stackblitz.com/edit/angular-material2-issue-bbe4mx?file=app/sidenav-fab-example.ts

I've noticed that its the :enter animation in particular that seems to be an issue. Removing it makes everything work fine. I believe this is related to https://github.com/angular/material2/issues/6743. Using the enter animation probably causes the container to initially read the sidenav's side as 0, and then its never updated afterward.

**Comment by mmalerba** [comment]
closing in favor of #6743 which has a PR ready to go
