### ISSUE TITLE
Some user scripts affect component behavior

### ISSUE THREAD

**Issue by ScarletCirno** [angular/material2#7221]
#### Bug, feature request, or proposal:
Some user scripts affect component behavior.such as `<input>`
Usually when I browse other sites have not been affected.

#### What is the expected behavior?
`<input>` should be the same as usual
![image](https://user-images.githubusercontent.com/15227557/30684170-bdf7092c-9ee2-11e7-9ac7-fa8e120c2360.png)

#### What is the current behavior?
No longer have animation effects(:focus..),and color.just as native, except for placeholder
![image](https://user-images.githubusercontent.com/15227557/30684155-b1ec70e0-9ee2-11e7-9720-0a5a6e26da46.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^4.4.1",
"@angular/material": "^2.0.0-beta.8",
"typescript": "^2.4.2",
ver. 63.0.3218.0 Chrome canary
Chrome.extensions -> [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?utm_source=chrome-app-launcher-info-dialog)
Tampermonkey.userScript -> [Anti-Adblock Killer | Reekv10.0](https://greasyfork.org/scripts/735-anti-adblock-killer-reek/code/Anti-Adblock%20Killer%20%7C%20Reek.user.js)

#### Is there anything else we should know?
When I found the problem, I just closed the plugin.
But there may be other people encounter such a situation, so I just feedback the problem

**Comment by jelbourn** [comment]
I would call this an issue with whatever scripts/extensions being used.
