### ISSUE TITLE
md-select does not show title/description/placeholder

### ISSUE THREAD

**Issue by ceverke** [angular/material2#7222]
#### Bug, feature request, or proposal:
I use the md-select component. Unfortunatelly,, the placeholer is not captioned when the component is loaded. It's only shown when an item is selected.

#### What is the expected behavior?

When the following example is loaded, I expect to see the caption "Favorite food" above the component
see here: https://material.angular.io/components/select/examples

#### What is the current behavior?

see here: https://material.angular.io/components/select/examples

#### What are the steps to reproduce?
see description above

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.8

**Comment by pjmagee** [comment]
I can see the placeholder perfectly fine on the examples page.

**Comment by donroyco** [comment]
@pjmagee I think @ceverke confuses _placeholders_ with _labels_. 'Favorite food' is a placeholder.

**Comment by ceverke** [comment]
I'm sorry for confusing. After an item is selected, then "Favorite food" can be read in small letters above the component. But in my case it's desired to have the small caption (label) of the component after loading the page (before an item is selected).

**Comment by ceverke** [comment]
(or is it a feature of the component because otherweise the placeholder would be displayed twice??)

**Comment by ghd8** [comment]
This behaviour is described in the [material design guidelines](https://material.io/guidelines/components/text-fields.html#text-fields-layout)

- Labels/placeholder rest above the line when the text field is empty.
- Labels/placeholder float upward when the text field is in focus or filled.

But you can use the option `floatPlaceholder="always"` of `md-form-field`  for your needs.
```typescript
<md-form-field floatPlaceholder="always">
    <input mdInput #testInput placeholder="Name">
</md-form-field>
```

**Comment by ceverke** [comment]
OK, sorry... didn't realy read about it... sorry
