### ISSUE TITLE
MdDialog component is not a "child component" of the component from which it is opened

### ISSUE THREAD

**Issue by eyalhakim** [angular/material2#7223]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MdDialog component should be a "child component" of the component from which it opens, so it has access to providers defined in this "parent component"

#### What is the current behavior?
MdDialog component has no access to providers defined in a component from which it is opened

#### What are the steps to reproduce?

https://plnkr.co/edit/ZvFMiG?p=preview

**Comment by crisbeto** [comment]
That's what the `viewContainerRef` option is for. Here's a forked Plunkr: https://plnkr.co/edit/vV2UGXong406SV9apPPH?p=preview

**Comment by eyalhakim** [comment]
@crisbeto perfect, thank you!
