### ISSUE TITLE
What does isFocusTrapEnabled do on a sidenav? How is it used?

### ISSUE THREAD

**Issue by adamdport** [angular/material2#7228]
#### Bug, feature request, or proposal:
There's no description on `isFocusTrapEnabled` on https://material.angular.io/components/sidenav/api. Please update the docs! Thanks.

**Comment by willshowell** [comment]
Yep it needs a jsdoc comment or be marked internal

https://github.com/angular/material2/blob/2b0315d3a267bc083db17580ff05ca5281280b13/src/lib/sidenav/drawer.ts#L159-L164

cc @mmalerba
