### ISSUE TITLE
[Core] Missing files in alpha.5-2 ?

### ISSUE THREAD

**Issue by manekinekko** [angular/material2#723]
Do you know why current alpha-5.2 does not provide all files under `src/core/` ?
For instance, the folder `src/core/coordination/` which exports the provider `MdUniqueSelectionDispatcher` is missing.
This provider is needed because of this error:

![image](https://cloud.githubusercontent.com/assets/1699357/16180236/f5652b54-367f-11e6-9a4e-2072853fd924.png)

Here is `@angular2-material/core` alpha-5.2:
![image](https://cloud.githubusercontent.com/assets/1699357/16180210/1a83dddc-367f-11e6-982a-0b254e44f425.png)

Here is `@angular2-material/core` at master:
![image](https://cloud.githubusercontent.com/assets/1699357/16180217/5b97c81a-367f-11e6-8519-9b2728f854bd.png)

BTW, as shown in the [src/demo-app/radio/radio-demo.ts](https://github.com/angular/material2/blob/013eabd672147963575b4aa6726183cfd14dbec3/src/demo-app/radio/radio-demo.ts#L3-L5) `MdUniqueSelectionDispatcher` is supposed to be exported.

**Comment by jelbourn** [comment]
@manekinekko Those files were changed on master after the last release. If you look at the older version of the readme, the service was `MdRadioDispatcher`, exported from `radio/`
