### ISSUE TITLE
Change MD font

### ISSUE THREAD

**Issue by evkw** [angular/material2#724]
Hey all,

Is there an easy way to overwrite the font used by the material design components? I'm trying to mix and match a few frameworks in a project I'm working on and the multiple fonts thing is making it look a bit crazy.

Thanks

**Comment by perfectyang** [comment]
material design components  provides all kinds of method to custom your style

**Comment by fxck** [comment]
> material design components provides all kinds of method to custom your style

they don't actually, not at the moment anyway

**Comment by msegers** [comment]
Helooooo, if you want to heavily modify stuff you should probably check back when it's near beta or even rc.

Right now the project is in early alpha, however usable at some points it's far away from being released as of now.

What I do is just override the fonts with CSS by forcing using !important.
It's not ideal but it should get you going where you want to be for now, I for example added these kind of things to a separate CSS file which will be replaced once the feature arises (which I expect will at least be after summer or even fall.)

**Comment by jelbourn** [comment]
This is tracked by #205
