### ISSUE TITLE
Chip List with Chip Input and Autocomplete has conflicting keyboard up arrow behavior

### ISSUE THREAD

**Issue by martin-the-geek** [angular/material2#7242]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Expected the up/down arrows on the input to cycle through the autocomplete options.

#### What is the current behavior?
The first up arrow key press both selects the last chip and highlights the last autocomplete option. Subsequent up arrow key presses only interact with the chips.

#### What are the steps to reproduce?
1. Move focus to the autocomplete chip input
2. Press the up arrow key
3. Press the up arrow key again

See http://plnkr.co/edit/CpqaJcdlYeNtDOghkhOG?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.3
Material: Beta 10

**Comment by tinayuangao** [comment]
Should be fixed by #7319
