### ISSUE TITLE
md-chip color selector not working

### ISSUE THREAD

**Issue by JoeMellon** [angular/material2#7243]
**Bug, feature request, or proposal:**
Bug

**What is the expected behavior?**
Color selection of md-chip displays color.

**What is the current behavior?**
No color is applied to the md-chip.

**What are the steps to reproduce?**
See example: https://material.angular.io/components/chips/examples 

**Which versions of Angular, Material, browsers are affected?**
Angular: 4.4.3
Material: 2.0.0-beta.11
Chrome

**Comment by willshowell** [comment]
I believe this is because of https://github.com/angular/material2/issues/7261

See http://plnkr.co/edit/fwvENkXwj8lDv36JRLvq?p=preview

**Comment by jelbourn** [comment]
Duplicate of #7261
