### ISSUE TITLE
Chips color property isn't working

### ISSUE THREAD

**Issue by DMan577** [angular/material2#7244]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Themeable chips

#### What is the current behavior?
![untitled](https://user-images.githubusercontent.com/9746502/30736032-e8bb3852-9f89-11e7-9473-d9be1c296ba9.jpg)
All the chips are uncolored (grey).
It can be seen in the material's site example:
https://material.angular.io/components/chips/examples

#### What are the steps to reproduce?
Basic chip list with material colors (primary, accent, warn), as used in the example code:
https://material.angular.io/components/chips/examples

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.3
Material: 2.0.0-beta.11

**Comment by donroyco** [comment]
Just one minute quicker: #7243
