### ISSUE TITLE
matTooltip triggers on focus capture since 2.0.0-beta.11

### ISSUE THREAD

**Issue by HitomiTenshi** [angular/material2#7245]
#### Bug, feature request, or proposal:

Bug?

#### What is the expected behavior?

**2.0.0-beta.10** didn't trigger tooltips on focus capture, e. g. by getting focus after closing a `dialog` or after closing a `sidenav`.

#### What is the current behavior?

**2.0.0-beta.11** triggers tooltips on focus capture. Perhaps this is intended when using the keyboard to focus elements with tooltips, but in my case this is not intended.

Maybe provide a way to disable triggering tooltips on focus capture?

#### What are the steps to reproduce?

http://plnkr.co/edit/5O7j6Mt033VyDEbC05ai?p=preview

Open the `sidenav`, then press close. Watch the tooltip reappear.

It will stay until something else catches focus or the button gets hovered.

#### What is the use-case or motivation for changing an existing behavior?

I want the behavior of **2.0.0-beta.10** back.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material **2.0.0-beta.11** and **2.0.0-beta.12**
Chrome 61 / Firefox 55

**Comment by Supamiu** [comment]
Same issue when reproduced from a dialog: http://plnkr.co/edit/HBaHnOcg1SPQcEvY684f?p=preview
