### ISSUE TITLE
get row number and column name of an data-table (CDK datatable) on clicking on perticular cell

### ISSUE THREAD

**Issue by achakra21** [angular/material2#7247]
#### Bug, feature request, or proposal:
By clicking on a row cell inside the row it should give the row number and the column name

#### What is the current behavior?

I am not sure how to implement the click listener for a perticular row cell in table
#### What are the steps to reproduce?

The below code i am using

<div class="example-container mat-elevation-z8">
  <cdk-table #table [dataSource]="dataSource" class="example-table">
    

    
    <ng-container cdkColumnDef="userId">
      <cdk-header-cell *cdkHeaderCellDef class="example-header-cell"> ID </cdk-header-cell>
      <cdk-cell *cdkCellDef="let row" class="example-cell"> {{row.id}} </cdk-cell>
    </ng-container>

    
    <ng-container cdkColumnDef="progress">
      <cdk-header-cell *cdkHeaderCellDef class="example-header-cell"> Progress </cdk-header-cell>
      <cdk-cell *cdkCellDef="let row" class="example-cell"> {{row.progress}}% </cdk-cell>
    </ng-container>

    
    <ng-container cdkColumnDef="userName">
      <cdk-header-cell *cdkHeaderCellDef class="example-header-cell"> Name </cdk-header-cell>
      <cdk-cell *cdkCellDef="let row" class="example-cell"> {{row.name}} </cdk-cell>
    </ng-container>

    
    <ng-container cdkColumnDef="color">
      <cdk-header-cell *cdkHeaderCellDef class="example-header-cell">Color</cdk-header-cell>
      <cdk-cell *cdkCellDef="let row" class="example-cell"
                [style.color]="row.color">
        {{row.color}}
      </cdk-cell>
    </ng-container>

    <cdk-header-row *cdkHeaderRowDef="displayedColumns" class="example-header-row"></cdk-header-row>
    <cdk-row *cdkRowDef="let row; columns: displayedColumns;" class="example-row"></cdk-row>
  </cdk-table>
</div>

#### What is the use-case or motivation for changing an existing behavior?
I want to display data in the data table i have  a download column and if i click on download icon on the certain cell in the row.It should download the corresponding cell from the server 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I am using angular 4 TypeScript,using material 2 data table using chrome broswer

**Comment by josephperrott** [comment]
This is actually already possible as `CdkCellOutletRowContext` provides the index of the row the cell is contained in.  This coupled with the ordering of the definition of the columns based on your template.

A quick example (conceptually this should work, I dont have data source to test it with):

```html
<cdk-table #table [dataSource]="dataSource">
  <ng-container *ngFor="let colId of ['col1', 'col2', 'col3', 'col4']; let cIndex = index;"
                cdkColumnDef="{{colId}}">
    <cdk-header-cell *cdkHeaderCellDef>{{colId}}</cdk-header-cell>
    <cdk-cell *cdkCellDef="let row; let rIndex = index;"> {{cIndex}},{{rIndex}} </cdk-cell>
  </ng-container>
</cdk-table>
```

**Comment by aakashLenora** [comment]
@josephperrott in the above mentioned example if we use pagination, the row number will be within the page instead of all the pages. Is there any possible way to get the row index from entire data at mat-cell level
