### ISSUE TITLE
How to invalid manual input in md-autocomplete 

### ISSUE THREAD

**Issue by lippomano** [angular/material2#7249]
In my angular 4 application is it possible to make the field/form invalid if a user write something in the autocomplete without selecting one of the suggestions proposed?
So to force the user to select one of the suggestions, 
also any good workaround if there

**Comment by willshowell** [comment]
Duplicate of #3334

Workaround https://github.com/angular/material2/issues/3334#issuecomment-319191915

**Comment by crisbeto** [comment]
Closing as a duplicate.
