### ISSUE TITLE
Cannot find SourceMap

### ISSUE THREAD

**Issue by rahmanusta** [angular/material2#725]
#### Bug, feature request, or proposal:

I'm getting this warning with webpack, it breaks the build.

WARNING in ./~/@angular2-material/button/button.js
Cannot find SourceMap '/usr/local/google/home/jelbourn/material2/tmp/broccoli_type_script_compiler-input_base_path-OxHzApZr.tmp/0/components/button/button.js.map': Error: Cannot resolve
'file' or 'directory' .//usr/local/google/home/jelbourn/material2/tmp/broccoli_type_script_compiler-input_base_path-OxHzApZr.tmp/0/components/button/button.js.map in C:\Users\usta\angular2\node_modules\@angular2-material\button

**Comment by jelbourn** [comment]
I believe #636 will resolve this when we publish the next release (should be this week).

**Comment by rahmanusta** [comment]
I'm using webpack, not system.js,

I solved it like below;

`        preLoaders: [
            // needed to lower the filesize of angular due to inline source-maps
            {
                test: /\.js$/,
                loader: 'source-map-loader',
                exclude: [
                    // these packages have problems with their sourcemaps
                    './node_modules/rxjs',
                    './node_modules/@angular',
                    /.*angular2-material.*/,
                ]
            }
        ],`

**Comment by elvirdolic** [comment]
If you upgrade to the latest cli version the errors should be gone

**Comment by rahmanusta** [comment]
Does the CLI supports webpack?  I don't use the CLI tool.

**Comment by zigzag95** [comment]
FYI no one uses cli for production applications we all use webpack.
