### ISSUE TITLE
md-dialog-container should be mat-dialog-container

### ISSUE THREAD

**Issue by skeize** [angular/material2#7250]
#### Bug, feature request, or proposal:

Testing the upgrade to beta 11, and noticed that md-dialog-container is incorrectly named (should have mat- prefix).  mat-dialog-container CSS class is correctly applied tho.

#### What is the expected behavior?

md- prefix should be mat-

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

![image](https://user-images.githubusercontent.com/16228052/30745378-76e395c6-9f6b-11e7-986f-7be0021168c8.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

ng 4.4.3
material beta 11
ts 2.3.3

**Comment by josephperrott** [comment]
Closing as this is a component created internally by MatDialog.  It will be changed to `mat-dialog-container` by #7241
