### ISSUE TITLE
Prefix change : default mode and clear docs

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/material2#7253]
Changelog of beta.11 says the `md` prefix is being deprecated everywhere, in favor of `mat`.

So I refactored all my project to move from `md` to `mat` for : 
- modules (`MdInputModule` > `MatInputModule`)
- components (`<md-slider>` > `<mat-slider>`)
- directives (`mdInput` > `matInput`)
- I already refactored the CSS classes before

But doing so, everything break with this error : 
`The "mat-" prefix cannot be used in ng-material v1 compatibility mode.`

I saw in `angular-prefix-adapter` that compatibility mode should be activated : 
`{provide: MATERIAL_COMPATIBILITY_MODE, useValue: true}`

But it looks like a bug to me : why is this an error by default if this is supposed to be the new official prefix ?

And even without this change, why is this an error by default when it's `md-` prefix which causes compatibility issues and not the `mat-` one ?

It should work out of the box.

And docs should be clear about all of this. Currently docs say to import `MatXModule` but to then use `<md-x>` element. I think I'm not the only confused by this.

**Comment by benelliott** [comment]
Yeah I was stumped by this too, I thought from rereading the changelog that the compatibility mode had been removed completely so I was surprised to see that the suggested refactor actually violates the "default" compatibility mode settings and that I had to _enable_ compatibility mode (for the first time) to get it working. I was also surprised that the handy tool didn't add the provider itself.  

I also think that the error message `The "mat-" prefix cannot be used in ng-material v1 compatibility mode.` is very unintuitive as it suggests that using `mat-` is invalid in compatibility mode, when in fact the opposite is true: _only_ `mat-` can be used in compatibility mode. You can see the issue in the compatiblility [source code](https://github.com/angular/material2/blob/master/src/lib/core/compatibility/compatibility.ts) - the `X prefix cannot be used in compatibility mode` error message is thrown regardless of whether it is enabled.

**Comment by jelbourn** [comment]
Yeah, we should have updated the errors; that was an oversight

**Comment by rkrzewski** [comment]
It is indeed very confusing. I would expect that after using the prefix updater tool, no errors should be reported without taking any further action.

However after using the tool I got `The "mat-" prefix cannot be used in ng-material v1 compatibility mode.` error mentioned above, which suggests that I had "v1 compatibility mode" **on** despite not opting it to use it. 

On the other hand in order to get rid of the error, I had to add `NoConflictStyleCompatibilityMode` module dependency to my app module and all unit tests which suggest that "v1 compatibility mode" was actually **off**, unless the intended role of `NoConflictStyleCompatibilityMode` module it to **opt out** of "v1 compatibility mode".

This definitely needs a clarification.

**Comment by mackelito** [comment]
@jelbourn sorry but this is till unclear for me... using beta.11 we can still use both md and mat right?
"The "md" prefixes will be removed in the next beta release" = beta.12?

**Comment by benelliott** [comment]
@mackelito Yes I believe the `md` prefixes are deprecated but still supported in beta 11.

**Comment by mackelito** [comment]
I blame my kids for not enough sleep.. of course it's still supported! 😁

**Comment by cyrilletuzi** [comment]
Fixed in beta 12, no more compatibility mode required.

**Comment by willshowell** [comment]
@bownie barring other breaking changes between 10 and 12, you should be able to use `mat` (and only `mat`) without the need for compatibility mode.
