### ISSUE TITLE
Adding classes is different in beta.11 + Angular 4.4.3

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#7257]
### Bug, feature request, or proposal:

Bug? After upgrade both angular to 4.4.3 and Material to beta.11, **`[ngClass]`** started to replace the classes of material components instead of add one more to the list of classes.

#### What is the expected behavior?

In previous versions, if you used ngClass in a Material Component, it would add the desired class to Material classes.

#### What is the current behavior?

It is replacing the classes now. Not sure if this was a change in Material or in Angular. I had to change, for example:

In:
```html
<mat-option [ngClass]="myClass"></mat-option>
```

where I had:
```js
myClass = 'my-class'
```
now I had to do something like:

```js
myClass = { 
    'my-class': true,
    'mat-option': true
} 

// or myClass = 'my-class mat-option';
```

#### What are the steps to reproduce?

Just upgrade to Material beta-11 + Angular 4.4.3

**Comment by willshowell** [comment]
I wasn't able to reproduce with `md-select/md-option`

https://plnkr.co/edit/EwR4JK5J0ZFJCWnG4T4a?p=preview

**Comment by jelbourn** [comment]
I wasn't able to reproduce either. @julianobrasil do you have a more specific reproduction?

**Comment by julianobrasil** [comment]
I'm not near a compreensão right now. I'm going to close this one and reopen it when I have a working plunk or something to show it. But I had to change this in a project after the last upgrade

**Comment by robisim74** [comment]
@julianobrasil are you using flex-layout nightly build? It does not seem to be just a material problem, but a material + flex layout: https://github.com/angular/flex-layout/issues/428

**Comment by julianobrasil** [comment]
@robisim74, yep... I'm using flex-layout nightly build. I'll try to add it in my reproduction plunk.

**Comment by naveedahmed1** [comment]
Yes I can confirm its an issue with the latest nightly build of flex-layout. Material beta.11 + Angular 4.4.3 works perfectly with flex-Layout last beta (2.0.0-beta.9).

**Comment by julianobrasil** [comment]
@naveedahmed1, as you've opened an issue in flex-layout repo and it looks like the problem is over there, I'll keep this one closed over gere.
