### ISSUE TITLE
Consider converting md-input to an attribute directive

### ISSUE THREAD

**Issue by thelgevold** [angular/material2#726]
#### Proposal:
Since md-input is enhancing an input element I think it's more appropriate to convert it to an attribute directive. My concern about using a component is that the actual input element is boxed in and hard to access if you need to add additional attributes to it - for whatever reason. 

My biggest concern is integrating it with the new Forms API. Unless the md-input component takes a direct dependency on the Angular Forms module (REACTIVE_FORM_DIRECTIVES etc), I don't see how to easily add the necessary form attributes. This dependency seems undesirable - especially for non forms applications.

With the current design, how are you planning to support the following internally in md-input?
example: 
```
<input [formControlName]="fistName" />
```

If md-input was an attribute directive it wouldn't have to know anything about Forms. However, with the current component design it seems like you will have to build an API around it to "ferry in" forms attributes.  

Thoughts?

#### What is the use-case or motivation for changing an existing behavior?

More flexibility. Forms is probably just one example.

**Comment by jelbourn** [comment]
We would love to do this, but it is currently not possible; Angular does not offer a way to _wrap_ a host element in additional DOM. We've been exploring solutions to this with the core team (see https://github.com/angular/angular/issues/7297), but so far we haven't come up with a solid approach. 

We may end up refactoring input to do this and handle all of the "wrapping" with direct DOM APIs, but this is something we'd like to avoid if possible.

**Comment by smitalm** [comment]
Wouldnt this problem also be solved by using `<md-input-container>` approach that was used in [material 1](https://material.angularjs.org/latest/demo/input)?

**Comment by manklu** [comment]
Yes, that would solve the problem too.
