### ISSUE TITLE
Stepper does not follow the material guidelines.

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#7260]
#### Bug, feature request, or proposal:
Request

#### What is the expected behavior?
Stepper should follow the material guidelines.
![image](https://user-images.githubusercontent.com/7990765/30757714-f6393272-9fcf-11e7-9dfe-d9d663907911.png)

#### What is the current behavior?
Stepper does not follow the material guidelines.
![image](https://user-images.githubusercontent.com/7990765/30757702-e8acec66-9fcf-11e7-9cda-67d5c970e763.png)

#### What is the use-case or motivation for changing an existing behavior?
Stepper should follow the material guidelines.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2.0.0-beta.11

#### Is there anything else we should know?
https://material.io/guidelines/components/steppers.html

- Grey background is on hover only (currently active steps have grey backgroud?)
- Grey ripple on click (currently there is no ripple)
- Steps' labels default color is 87% black (currently unfocused labels are 38% black which means 'disabled text' according to material guidelines)
- Focused steps' labels should be bold according to images (which helps differentiate active steps from focused steps)
- Cursor on active steps' labels should be set to 'pointer' when hovering (currently it's set to default 'grab' on label)

**Comment by willshowell** [comment]
Can you be more specific? Which guidelines in particular does it fail to address?

**Comment by Ploppy3** [comment]
Edited with 5 issues so far for horizontal non-linear stepper & horizontal linear stepper.

**Comment by willshowell** [comment]
Thanks. It's hard to "complete" an issue like this without explicit goals to measure against.

**Comment by Ploppy3** [comment]
I need to get this out:
I understand the amount of work needed for such an awesome library of components, but coming from Google I expect it to follow their own guidelines, it's not the first time I open an issue because a component is not following the guidelines. Also I do understand that it's a beta but no one seem to report them so I have to be that person.

**Comment by Ploppy3** [comment]
@crisbeto I see that the issue will be closed but I can't find where your fixed the text color [Steps' labels default color is 87% black (currently unfocused label are 38% black which means 'disabled text' according to material guidelines)]. Did you fixed it? Thank you.

@benjamincharity I'd like to know what's so wrong about my report and comment?

**Comment by crisbeto** [comment]
@Ploppy3 I didn't change it, because the spec seems to indicate that the inactive steps are supposed to be 38% black:

> Inactive steps
> 
> 14sp Roboto Regular
> 38% black

**Comment by Ploppy3** [comment]
38% black means 'disabled text' but you can click on those right? Unless it is a linear stepper.

**Comment by crisbeto** [comment]
The way I interpret it is that disabled text is 38%, but that color isn't reserved only for disabled text. Also AFAIK aside from the orientation, the styling of vertical and horizontal steppers is exactly the same.

**Comment by Ploppy3** [comment]
See images bellow:
Linear: 
https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B7WCemMG6e0VOFVjMHV2TWdOMnM/components-acux-stepper-linear.png

Non Linearl:
https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B7WCemMG6e0VaXlOV1dLTk11dnc/components-acux-stepper-nonlinear.png

**Comment by Ploppy3** [comment]
@crisbeto updated my latest comment with a lot more info so I think I should give you another notification ^^

**Comment by Ploppy3** [comment]
@crisbeto Did you fix the last thing we talked about?

**Comment by crisbeto** [comment]
I didn't have time to get around to it, before it got merged @Ploppy3.

**Comment by Ploppy3** [comment]
Should I reopen or open a new issue?

**Comment by crisbeto** [comment]
Let's reopen it.
