### ISSUE TITLE
Flat button with inverted colors (accent color background)

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#7264]
#### Bug, feature request, or proposal:
Feature request:
A flat button with accent background and its corresponding text color.

#### What are the steps to reproduce?
Basically it's a raised button without its shadow.
![image](https://user-images.githubusercontent.com/7990765/30759151-61f64590-9fd5-11e7-9de0-9c02eec613fb.png)

#### What is the use-case or motivation for changing an existing behavior?
Those buttons are used in many situations since you are not supposed to use the raised button on elements with z-elevation. 
They are already present in many (if not all) Google apps and websites with material design.
Even though they are not described in the official guidelines, the image you see is taken from the material guidelines website on the 'button' page.

**Comment by jelbourn** [comment]
I don't follow. How is this not the existing `color` property?

**Comment by Ploppy3** [comment]
Currently we have this:
![image](https://user-images.githubusercontent.com/7990765/30785899-0522c0c4-a16e-11e7-8367-2e1a1ff2d071.png)
But the one I request is missing, unless I'm missing something?

**Comment by Ploppy3** [comment]
So I have an idea, what you could do is add a new directive `[background-color]` to the `md-button`.
What do you think?

**Comment by willshowell** [comment]
While not idiomatic, it might be nice if adjusting the elevation of the raised button was a little easier. This,

```html
<button mat-raised-button class="mat-elevation-z0">BUTTON</button>
```

doesn't work because both the default elevation and z0 styles have the same specificity. Of course it's simple to add this to your global stylesheet.

```scss
.my-flat-button.mat-raised-button {
  box-shadow: none;
}
```

**Comment by Ploppy3** [comment]
@crisbeto Thank you.

**Comment by leocaseiro** [comment]
That would be nice if we could also overwrite `mat-button-toggle-group`. Should I open a new issue or is very related to this one?

cc @crisbeto
