### ISSUE TITLE
md-select/md-radio-group cannot set the inital value by ngModel

### ISSUE THREAD

**Issue by ruonan59** [angular/material2#7267]
#### Bug, feature request, or proposal:
while using ngModel for the two way binding, it's only working one way. select behavior sets the back end value, but when try to initialize the md-select/md-radio-group selected item, it's not working.
.html file:

![image](https://user-images.githubusercontent.com/3810825/30766242-54b4ea92-9fb9-11e7-939c-041d42af00b7.png)

.ts file:
![image](https://user-images.githubusercontent.com/3810825/30766201-10a5d03c-9fb9-11e7-8e30-04226da72757.png)

#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/3810825/30766161-e02de480-9fb8-11e7-8f6b-47fec13af9c3.png)

#### What is the current behavior?
nothing pre-selected

**Comment by josephperrott** [comment]
@ruonan59 Can you provide a reproduction plunkr?  

I was unable to reproduce this.  [Here](http://plnkr.co/edit/QatJEfva4UqQDvrTjI0w?p=preview) is a plunker of it working as expected.

**Comment by ruonan59** [comment]
hi @josephperrott ,

thank you very much! mine is not working is because we are using both ngModel and formGroup...
thanks for the quick reply!~
