### ISSUE TITLE
feat(rxjs): update to rxjs@5.5.0

### ISSUE THREAD

**Issue by CaerusKaru** [angular/material2#7275]
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

Should adopt the newest version of RxJS, with support for lettable operators:
`import {first} from 'rxjs/operator/first';` -> `import {first} from 'rxjs/operators';`

#### What is the current behavior?

Currently uses a homebrew version of lettable imports

#### What is the use-case or motivation for changing an existing behavior?

The newest version is clearer and consolidates the source of imports. Also, angular/angular is moving to it with https://github.com/angular/angular/pull/19345

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular 5.0.0-beta.7
material 2.0.0-beta.11

**Comment by crisbeto** [comment]
FWIW, Material hasn't been using patch imports for a while now. We had our own version of lettable operators.

**Comment by CaerusKaru** [comment]
@crisbeto Fair enough, I'll modify the issue 👍
