### ISSUE TITLE
MatPrefixRejector not working for EntryComponents

### ISSUE THREAD

**Issue by matheo** [angular/material2#7277]
#### Bug:

I've upgraded to `beta.11` and got problems in when trying to insert my EntryComponents with the `ComponentFactoryResolver`. I've tried to add the provider
```
{ provide: MATERIAL_COMPATIBILITY_MODE, useValue: true },
```
on every module and in the same EntryComponent (I saw this on button.ts component)
```
viewProviders: [{ provide: MATERIAL_COMPATIBILITY_MODE, useValue: true }]
```
with no joy. I know that only my root AppModule is the direct parent of my EntryComponents, and the root provider doesn't make it work. I keep getting:
```
ERROR Error: The "mat-" prefix cannot be used in ng-material v1 compatibility mode.
It was used on an "mat-icon" element.
    at getMdCompatibilityInvalidPrefixError (compatibility.js:21)
    at new MatPrefixRejector (compatibility.js:32)
```
for Components dynamically inserted with:
```
// resolver: ComponentFactoryResolver
// childComponent: ComponentRef<any>;
// @ViewChild('entry', { read: ViewContainerRef })

const componentFactory = this.resolver.resolveComponentFactory(EntryComponent);
this.childComponent = this.entry.createComponent(componentFactory);
```
I cannot use `mat-` nor `md-` inside those EntryComponents. Help please!

#### What is the expected behavior?

To work with no errors like in `beta.10`.

#### What are the steps to reproduce?

Try to use `@angular/material beta.11` components inside a Dynamic Component.
Something like the example in the documentation: https://angular.io/guide/dynamic-component-loader

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular `4.4.3`
Material `beta.11`
Typescript `2.4.2`

#### Additionally

Is there something I can do, maybe changing my method to resolve dynamic components, to make it work? I think that once this compatibility stuff gets removed everything may run smoothly, but what to do in the meanwhile?

**Comment by matheo** [comment]
Elaborating this Plunker:
http://plnkr.co/edit/Ijht2B?p=preview
I see that there's something in my project messing things up :(

**Comment by charliebrink** [comment]
Same here. Did you manage to resolve this? @matheo

**Comment by matheo** [comment]
I was using `md2` and its usage of `md-` components screwed the whole project, I had to remove it.
