### ISSUE TITLE
md-input not supporting web worker

### ISSUE THREAD

**Issue by datrinh** [angular/material2#728]
#### What is the expected behavior?
Inputs should work work with angular running on a web worker.

#### What is the current behavior?
`EXCEPTION: focus not supported on WebWorkers`

#### What are the steps to reproduce?
1. Set up bootstrapping angular 2 on web worker like so: https://github.com/angular/angular/tree/master/modules/playground/src/web_workers/kitchen_sink
2. Import and use md-input directive

#### What is the use-case or motivation for changing an existing behavior?
It would be really great if inputs could be used decoupled from the DOM.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.0.0-rc.2
Material: 2.0.0-alpha.5-2
OS: OS X 10.11.5
Browsers: all

**Comment by jelbourn** [comment]
In order to support web workers in Material, we need custom renderers (https://github.com/angular/angular/issues/2409) to land in Angular core. This is currently scheduled post final 2.0.0 of the core. Without custom renderers, it's somewhat impossible to build a fully-functional component library with the web-workers feature (because sometimes you just have to touch the DOM).

**Comment by naveedahmed1** [comment]
@jelbourn does Material2 supports Web Workers?

**Comment by jelbourn** [comment]
Nope.

**Comment by jkesineni** [comment]
@jelbourn , is there any time lines to support web-workers for material 2?  
we are planned to use material 2 and webworkers, what would be your suggestion to proceed?

appreciate your comment/suggesion.

thank you
-jana

**Comment by jkesineni** [comment]
@jelbourn , is there any time lines to support web-workers for material 2?  
we are planned to use material 2 and web workers, what would be your suggestion to proceed?

appreciate your comment/suggestion.

thank you
-jana

**Comment by jelbourn** [comment]
At this time we have no plans to support Web Workers in any capacity for the foreseeable future.
