### ISSUE TITLE
Paginator status like 1-10 of 10+ when data length is not known

### ISSUE THREAD

**Issue by kwalski** [angular/material2#7289]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Counting the total number of records in the database may require full table scan which is expensive and doesn't always add significant value to the end user. There are cases when you may just want to inform user that there is more records than displayed on the current and they may click on ">" icon to go to the next page.
An option within paginator to show status like we are displaying records `1 - 10 of 10+` or `1 - 10 of 20+` instead of exact count (eg, 100) in how it currently displays:`1 - 10 of 100`.

#### What is the current behavior?
Exact data length (eg, 100) is used to display status as `1-10 of 100` on the paginator.

#### What are the steps to reproduce?
none. 

#### What is the use-case or motivation for changing an existing behavior?
It is not always necessary to inform user the exact data length, which requires a full table scan at the backend. Search function within Gmail is an example use case where user is not informed of the exact number of matching emails when the matching result list overflows beyond the displayed page. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
 "@angular/animations": "^4.4.3",
    "@angular/cdk": "^2.0.0-beta.11",
    "@angular/common": "^4.4.3",
    "@angular/compiler": "^4.4.3",
    "@angular/core": "^4.4.3",
    "@angular/forms": "^4.4.3",
    "@angular/http": "^4.4.3",
    "@angular/material": "^2.0.0-beta.11",
    "@angular/platform-browser": "^4.4.3",
    "@angular/platform-browser-dynamic": "^4.4.3",
    "@angular/router": "^4.4.3",
    "angular2-moment": "^1.6.0",
    "typescript": "~2.3.3"
OS: MacOSX
Chrome

```
#### Is there anything else we should know?
An optional input param to `<md-paginator>` that will suffix "+" to the displayed data length value should do the job.

**Comment by willshowell** [comment]
You need to use [`MatPaginatorIntl`](https://material.angular.io/components/paginator/api). Unfortunately the docs don't go into much detail (see https://github.com/angular/material2/issues/5902 and https://github.com/angular/material2/issues/5573), but you can configure the labels to show whatever you want.

**Comment by kwalski** [comment]
I can change the labels using MatPaginatorIntl, however the `+` suffix needs to be dynamic. I.e, when the data length is definitive, don't display `+`. Therefore, lengthDefinitive (example property) is required on MdPaginator so that it can be used in MatPaginatorIntl.
```
Input() get lengthDefinitive(): boolean { return this._lengthDefinitive; }
  set lengthDefinitive (lengthDefinitive: boolean) {
    this._lengthDefinitive = lengthDefinitive;
    this._changeDetectorRef.markForCheck();
  } 
_lengthDefinitive:boolean=true;
```

This property can then be used like as:
```
<md-paginator [length]="100" [lengthDefinitive]="true"  ...> </md-paginator>
```
will display `1 - 10 of 100`, where as 

```
<md-paginator [length]="100" [lengthDefinitive]="false"  ...> </md-paginator>
```
will display `1 - 10 of 100+`

Without this property in MdPaginator, we cannot dynamically change the label by extending MatPaginatorIntl. I am happy to do a PR on this.

**Comment by andrewseguin** [comment]
You can do this with a custom implementation of the MatPaginatorIntl. Check out this example for help understanding how to dynamically change the label:

https://stackblitz.com/edit/angular-material2-issue-yfhefy?file=app%2Fapp.component.ts

**Comment by kylecordes** [comment]
Given that Google's own Firestore database does not return a total result set length when pageant eating through, it would be fantastic if mat-paginator had the ability to deal with this uncertainty "in the box" instead of reaching for the internationalization-support mechanism to override the behavior.
