### ISSUE TITLE
vertical alignement 

### ISSUE THREAD

**Issue by dl35** [angular/material2#7290]
#### Bug, feature request, or proposal:
md-select and md-form-field are not aligned vertically in the same row
md-select is under md-form-field .

#### What is the expected behavior?
form component align on the same line

#### What is the current behavior?

offset between md-select and md-form-field
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
chome +firefox 
node: 6.9.4
os: linux x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.2.4
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6

**Comment by donroyco** [comment]
Please add a Plunker to reproduce the issue. I don't think it is an issue afaik.

**Comment by willshowell** [comment]
This is fixed in beta 11 https://github.com/angular/material2/pull/6488

**Comment by josephperrott** [comment]
Closed as this was fixed with #6488
