### ISSUE TITLE
have all modules been renamed?

### ISSUE THREAD

**Issue by naivefun** [angular/material2#7294]
previously it is `MdInputModule` but now in the document it's `import {MatInputModule} from '@angular/material';`

Did `Mat` replace all `Md` prefix from `beta.11`?

**Comment by donroyco** [comment]
Please check the [Changelog](https://github.com/angular/material2/blob/master/CHANGELOG.md) which states what has been changed.

> **Deprecation of "md" prefix.**
>
> In earlier betas, we've had a compatibility mode that allowed people to use either "md" or "mat" as the selector for Angular Material components. This was created so that these components could live side-by-side with AngularJS Material without CSS from the two libraries colliding.
> 
> For beta.11, we've made the decision to deprecate the "md" prefix completely and use "mat" moving forward. This affects all class names, properties, inputs, outputs, and selectors (CSS classes were changed back in February). The "md" prefixes will be removed in the next beta release.

**Comment by crisbeto** [comment]
As @donroyco mentioned, they have been renamed. We have a tool to help you migrate automatically: https://www.npmjs.com/package/angular-material-prefix-updater

**Comment by robert-king** [comment]
a lot of the documentation still uses md e.g. md-spinner instead of mat-spinner

**Comment by benb7760** [comment]
@robert-king there were a lot of issues previously where this was caused by cache. can you try clearing yours and checking again? If there are still references to md-* could you point out specific occurrences?
