### ISSUE TITLE
[form-field] inconsistencies now that select is supported

### ISSUE THREAD

**Issue by willshowell** [angular/material2#7297]
#### Bug, feature request, or proposal:
Bug

#### Current Behavior
1. `getMdFormFieldMissingControlError` needs an updated message to reflect support for multiple types of controls

https://github.com/angular/material2/blob/3571f68a2de0833ee4741af8a0eb24d1da174f38/src/lib/form-field/form-field-errors.ts#L19-L23

2. ~`MdFormFieldModule` is re-exported by `MdInputModule` but not by `MdSelectModule`. (tracking https://github.com/angular/material2/pull/7263)~

https://github.com/angular/material2/blob/3571f68a2de0833ee4741af8a0eb24d1da174f38/src/lib/input/input-module.ts#L27-L33

https://github.com/angular/material2/blob/3571f68a2de0833ee4741af8a0eb24d1da174f38/src/lib/select/select-module.ts#L23

cc @mmalerba

**Comment by ghd8** [comment]
fyi - second point was already corrected in #7263
