### ISSUE TITLE
Dev mode assertions

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#73]
We want to be able to perform certain assertions during development mode that are stripped out in prod mode.
### Valid component structure
- [ ] Sidenav 
- [ ] Cards
### a11y
- [ ] Progress bar and circle have descriptions
- [ ] Buttons have text or a label
- [ ] Inputs / checkboxes / radio buttons have a label.
- [ ] mat-icon shouldn't have a click handler

(add more to this issue as we encounter them)

**Comment by jelbourn** [comment]
cc @chuckjaz is this something you might be interesting in driving at some point over the next couple of quarters?

**Comment by jelbourn** [comment]
Might be something that the new TypeScript transformer pipeline could help with

**Comment by chuckjaz** [comment]
Yes. We should consider implementing a generic way to detect when to remove annotations.

**Comment by jelbourn** [comment]
Closing this since it's something that would be implemented out of the scope of Angular Material.

**Comment by mertdeg2** [comment]
One accessibility check we could have, allow below:

`<mat-button-toggle [aria-label]="foo"></mat-button-toggle>`
`<mat-button-toggle aria-label="{{foo}}"></mat-button-toggle>`
`<mat-button-toggle aria-label="some string"></mat-button-toggle>`

While we disallow below:

`<mat-button-toggle [attr.aria-label]="foo"></mat-button-toggle>`
