### ISSUE TITLE
Should md-slide-toggle (change) event update the model before calling the event handler?

### ISSUE THREAD

**Issue by pwdst** [angular/material2#7300]
#### Bug, feature request, or proposal:

Linked to #448 - the (change) event method for md-slide-toggle component appears to be called before the model is updated for [(ngModel)] bound controls.

#### What is the expected behavior?

Model is updated before the change event handler fires.

#### What is the current behavior?

Change event fires and then the model is updated.

#### What are the steps to reproduce?

Add a change event handler to a md-slide-toggle control bound to a model property using [(ngModel)] syntax. 

#### What is the use-case or motivation for changing an existing behavior?

Inconsistent with native browser and other Angular Change events.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4.0.0, Material 2.0.0-beta.11, Typescript 2.3.3. Windows 10 Enterprise O/S.

**Comment by bogacg** [comment]
Not consistent behavior with checkbox as well, see #6378

**Comment by DevVersion** [comment]
Should be fixed with #7076
