### ISSUE TITLE
Datepicker uses md-"

### ISSUE THREAD

**Issue by bradtaniguchi** [angular/material2#7302]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by josephperrott** [comment]
Marking as closed as you should already be able to use `mat` prefixes in your templates.

**Comment by bradtaniguchi** [comment]
@josephperrott Sorry the issue was somehow submitted before I could write anything, updated with the actual issue.

**Comment by willshowell** [comment]
@bradtaniguchi is this with `material2-builds`?

**Comment by bradtaniguchi** [comment]
@willshowell No it is not

**Comment by willshowell** [comment]
Here is a plunker of it working with beta.11

https://plnkr.co/edit/UPwyLI0uG0EPpA8AercK?p=preview

**Comment by bradtaniguchi** [comment]
I found the issue, the mdSuffix wasn't changed to matSuffix, once that was changed everything was working normally again. 

Thank you
