### ISSUE TITLE
Sort arrow pieces appear horizontally rather than vertically.

### ISSUE THREAD

**Issue by mcalmus** [angular/material2#7304]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Arrow pieces look like an arrow.

#### What is the current behavior?
arrow pieces appear horizontally next to one another rather than vertically.

#### What are the steps to reproduce?
I haven't been able to reproduce it with a simple test case (and can't upload my regular site), but with the patch from https://github.com/angular/material2/pull/6802 in place (beta 11), I'm seeing the sort header "stem" and indicator appearing horizontally next to one another rather than vertically. Looks something like | ^

I was able to fix this by (with the debugger) adding a "flex-direction: column" style to the "mat-sort-header-arrow" class.

Would it be possible to do so in the official release?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material beta 11

**Comment by donroyco** [comment]
I think you overlooked #7291

**Comment by mcalmus** [comment]
#7291 is different from what I'm seeing. As I said It looks like
 | ^
The two parts of the arrow are next to one another rather than stacked.

**Comment by andrewseguin** [comment]
Is this something you are exclusively seeing in IE? Looks like it's not rendering properly in that browser

**Comment by kevincaradant** [comment]
@mcalmus Hi

I'm the author of the issue #7291 and I only make some picture of chrome but when I said in the issue: `BTW: Under IE11 it's always ugly. Same issue or not I don't know` 

it's exactly what I mean :)

**Comment by mcalmus** [comment]
#7291 is different from what I'm seeing. As I said It looks like
 | ^
The two parts of the arrow are next to one another rather than stacked.

**Comment by mcalmus** [comment]
I hadn't tried IE until now. I am seeing it in Firefox 45.7ESR and in IE 11.
