### ISSUE TITLE
[Proposal] Tab content hidden option

### ISSUE THREAD

**Issue by RicardoVaranda** [angular/material2#731]
#### Bug, feature request, or proposal:

Proposal
#### What is the expected behavior?

Tab content hiding instead of ngIf removing them from DOM
#### What is the current behavior?

Temporarily Removed from DOM and inserted again once ngIf is active
#### What is the use-case or motivation for changing an existing behavior?

Switching between tabs seems to be a lot faster for me after adopting the content hiding instead of ngIf, along with that I'm creating a socket connection within each content which is being reset every time I load a new tab.
#### Which versions of Angular, Material, OS, browsers are affected?

All
#### Is there anything else we should know?

If allowed I'd like to post a pull request which would adapt both  methods of doing this leaving the ngIf as default and only using hidden if a certain flag is used.

**Comment by zigzag95** [comment]
Personnaly I prefer ngIf because I need content to reload when changing tabs.
Suppose I have two tabs
Tab1: managing roles and functionalities 
Tab2: Managing user roles

If I add a new role in tab1 I need it to be shown on tab2 after switching tabs.

**Comment by zigzag95** [comment]
Personnaly I prefer ngIf because I need content to reload when changing tabs.
Suppose I have two tabs
Tab1: managing roles and functionalities 
Tab2: Managing user roles

If I add a new role in tab1 I need it to be shown on tab2 after switching tabs.

**Comment by zigzag95** [comment]
And I believe tab group is using portal host (no ngIf)

**Comment by jelbourn** [comment]
@robertmesserle we should look into the performance implications of this

**Comment by no-more** [comment]
Hi,

I think both case are very useful and depends on usage. It would be great to be able to choose which mode to use. Another great feature could be to load content only when the tab was selected once and then keep the content even when changing tabs.

Thanks.

**Comment by RicardoVaranda** [comment]
@jelbourn For me the performance is amazing, switching between all of the tabs is a lot faster since I don´t have to keep reconnecting.

@zigzag95 I know it's *ngIf as I've analysed the source code:
[L23](https://github.com/angular/material2/blob/master/src/components/tabs/tab-group.html#L23)

**Comment by robertmesserle** [comment]
@jelbourn @RicardoVaranda I think I agree that we should support both options.  When dealing with a small number of tabs, hiding the inactive tabs will typically be faster; however, when dealing with a large number of tabs, this can cause performance issues.

The ideal solution would be something like what we *tried* in Material 1 with `disconnectScope`, but I'm not sure if there's a good bug-free way to do that.

**Comment by no-more** [comment]
I can see one other major bonus of hiding instead of removing the element from the dom, it's when the content of the tab is editable and unsaved. When switching tabs the changes are lost.
But once again both options should be supported as they both have their own use cases.

**Comment by RajeeNedunchezhian** [comment]
Yes i agree that we should have both options, as @no-more mentioned, i have similar use case where i group the grid , now after switching tabs the grouping/filtering doesnt stay. The data bound to grid in different tabs are not the same , so putting the datamodel outside wont work in this case . @RicardoVaranda can you provide your solution if possible. Thanks

**Comment by RicardoVaranda** [comment]
I will create a pull request with the solution for this in the morning.

**Comment by RajeeNedunchezhian** [comment]
Thanks @RicardoVaranda

**Comment by HeavenlyHost** [comment]
Agree, but please make this an option as we are currently using the original feature whereby ngIf removes it from dom, this matches our user requirements !!! Please do not remove this feature :-)

**Comment by FoodBuster** [comment]
@RicardoVaranda Did you make that pull request for [hidden] md-tabs? I couldn't find it. I'd really appreciate a look.

**Comment by RicardoVaranda** [comment]
@FoodBuster You can use this temporary fix, I'll try and make time after work to release the full version with support for both:

https://github.com/RicardoVaranda/material2/blob/master/src/lib/tabs/tab-group.html#L23

**Comment by FoodBuster** [comment]
@RicardoVaranda Much appreciated!

**Comment by RicardoVaranda** [comment]
Sorry for the delay, I've created a PR for this:

https://github.com/angular/material2/pull/1472

This will allow us to use the tabs just like before but by passing hideTabs input of true it will hide the tab contents instead of removing and adding them to the DOM, there are some setbacks to this and it should be used with moderation, i.e you shouldn't hide the contents if you have a large number of tabs e.g 10+

**Comment by tomwanzek** [comment]
+1 for allowing an option to hide without DOM teardown.

The other reason, I ran into is that, placing a (secondary)  `<router-outlet>` into the tab content, means its content currently is not being re-populated after switching back and forth between tabs (while there is no route change). See tab-related issues #1445 and #524.

**Comment by tomwanzek** [comment]
This item seems all the more important now.

As far as the "Tab + Router" issue #524 goes, it has  just been closed with a solution that does not seem to address the use case I initially opened as issue #1445 (I.e. using a secondary router outlet as _one_ of the tabs in a tab-group.)

**Comment by andrewseguin** [comment]
Tabs no longer use ngIf but attach/detach the content using a portalHost. Changes made to the content are preserved when switching tabs. I am not seeing any performance issues using this method.

**Comment by dayong38** [comment]
@andrewseguin 
I'm now using <iframe> tag as tab-content, and it is reloaded as I change tabs. Not sure if there is any workaround for this to be resolved.
Thanks.

**Comment by jelbourn** [comment]
@dayong38 https://github.com/angular/angular/issues/16994

**Comment by dayong38** [comment]
@jelbourn Thanks so much. Lemme chek.

**Comment by dayong38** [comment]
@jelbourn Does md-tab support a feature that do not hide it's contents though tab is deselected and only shows the contents once the tab is activated again?
I'm using <iframe> in the md-tab and it always reloads when tab is changed.
Thanks in advance.

**Comment by RicardoVaranda** [comment]
@dayong38 What I did was, fork the repo and applied the following changes:
https://github.com/RicardoVaranda/material2/commit/43b0bc66fcd5067a8d4670305e2bdfd74be1ec1f

There was another commit done after this one to fix a bug so if you want to implement it make sure you follow that also 😄

**Comment by anupvarma** [comment]
Can somebody let me know if my issue #5239 is related to this issue.
plunker: http://plnkr.co/edit/DADYadzGOFI5GqkkITkA?p=preview
