### ISSUE TITLE
it seems like MatDialogModule should be MdDialogModule.

### ISSUE THREAD

**Issue by praveeno** [angular/material2#7313]
#### Bug, feature request, or proposal:
https://material.angular.io/components/dialog/api
it refer to MatDialogModule but when we import it, it give error "this file has no exported member  MatDialogModule .
it seems like MatDialogModule should be MdDialogModule in docs api section

**Comment by willshowell** [comment]
Are you using beta.11? The docs refer to the latest release.

**Comment by josephperrott** [comment]
Closing as all components have been exported currently as Both `Md*` and `Mat*`.  However ultimately `Mat*` should be used.

**Comment by praveeno** [comment]
a little confuse parhaps md => material design and mat => material
