### ISSUE TITLE
md-autosize initialized with height of 0 inside stepper & tabs

### ISSUE THREAD

**Issue by skyfremen** [angular/material2#7316]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
TextArea indicator should always show onload

#### What is the current behavior?
TextArea indicator with md-autosize not showing inside the Stepper.
The indicator will only show when users starts to type into it.

#### What are the steps to reproduce?
[Plunker Link](https://plnkr.co/edit/OwCi5QPmaWv8htG8gaWQ?p=preview)

Step 1: Notice that the TextArea outside the stepper is showing the indicator and the TextArea inside the Stepper is not showing the indiciator.
Step 2: Start to type into the TextArea inside the stepper

![TextArea Indicator Error](https://user-images.githubusercontent.com/22805288/30849081-bb78cf74-a2d3-11e7-8c9d-efc730636034.jpg)

#### What is the use-case or motivation for changing an existing behavior?
NA

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material Beta 11

#### Is there anything else we should know?
NA

**Comment by mmalerba** [comment]
I'm seeing this issue with tabs too, it looks like the mat-autosize winds up getting initialized to a height of 0. In addition to hiding the resize handle this also hides any content that is initially in the textarea
