### ISSUE TITLE
Unmet Peer Dependency - Typescript

### ISSUE THREAD

**Issue by griffiti** [angular/material2#732]
#### Bug, feature request, or proposal:
Upon running "npm install" I receive an UNMET PEER DEPENDENCY error for typescript.
So I manually run "npm install typescript --save-dev" and it still returns the following error:

`-- UNMET PEER DEPENDENCY typescript@1.9.0-dev.20160620-1.0
npm WARN tslint@3.11.0 requires a peer of typescript@>=1.7.3 but none was installed.
npm ERR! code 1

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2, latest clone of Material master branch, Windows 7, Chrome, Node 6.2.2

**Comment by jelbourn** [comment]
You can ignore that. We use the 1.9 dev version of TS and npm has some issues with version comparison with it for some reason. It doesn't actually affect anything.

**Comment by griffiti** [comment]
Ah sweet! Thanks!
