### ISSUE TITLE
Template parse errors: There is no directive with "exportAs" set to "mdAutocomplete"

### ISSUE THREAD

**Issue by pacoma93** [angular/material2#7322]
#### What is the current behavior?
getting this error:

Template parse errors:
There is no directive with "exportAs" set to "mdAutocomplete" ("               [mdAutocomplete]="test">
            </md-form-field>
            <md-autocomplete [ERROR ->]#test="mdAutocomplete">
              <md-option *ngFor="let item of filteredStates | async" (click)"): ng:///

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4,
Browser: Chrome,
"typescript": "^2.5.1",

#### Is there anything else we should know?
this is the html which is affected
`<md-form-field *ngIf="type">
              <input #cInput type="text" mdInput [formControl]="stateCtrl" placeholder="" [(ngModel)]="searchStr"
                [mdAutocomplete]="test">
            </md-form-field>
            <md-autocomplete #test="mdAutocomplete">
              <md-option *ngFor="let item of filteredStates | async" (click)="chooseContakt(item.id)">
                {{ item.item }}
              </md-option>
              <md-option (click)="openModal()">
                Legg til +
              </md-option>
            </md-autocomplete>`

**Comment by donroyco** [comment]
See #7306

**Comment by pacoma93** [comment]
Thanks problem solved. updated angular to 4.41 +

**Comment by donroyco** [comment]
@pacoma93 You can close your issue then.
