### ISSUE TITLE
md-spinner memory leaks

### ISSUE THREAD

**Issue by IshIvan** [angular/material2#7325]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Strange memory usage or big memory cicrle

#### What is the current behavior?
In chrome profile on 60 seconds mdSpinner used memory increased since 26 mb to 37 mb.

**Without:**
![without spinner](https://user-images.githubusercontent.com/18427985/30855743-a6186122-a2be-11e7-8554-7d15bddf5a3e.PNG)

**With:**
![spinner](https://user-images.githubusercontent.com/18427985/30855745-a86950b2-a2be-11e7-974d-63fb01e68527.PNG)

#### What are the steps to reproduce?
Insert md-spinner on your html code and start profiling chrome.

#### What is the use-case or motivation for changing an existing behavior?
Optimize apps

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material.10
cdk.10
angular 4.3.6
win 10
chrome 60

#### Is there anything else we should know?
Others feature is the same.

**Comment by crisbeto** [comment]
The spinner will be changed to a CSS-based animation. See https://github.com/angular/material2/pull/6551.
