### ISSUE TITLE
Can't bind to 'matDatepickerToggle' since it isn't a known property of 'button'

### ISSUE THREAD

**Issue by JSilva94** [angular/material2#7328]
I have imported MatDatepickerModule and my app does not compile because of the following error ^^

**Comment by jbojcic1** [comment]
@JSilva94 I am having the same problem. Did you manage to resolve it?

**Comment by ruffryder** [comment]
You can use this selector instead of button : <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
