### ISSUE TITLE
Can we have scalable responsive progress bar

### ISSUE THREAD

**Issue by TarkeshNimje** [angular/material2#7329]
Can we have scalable responsive progress bar

Progress bar which can load on json data having some text for each stage, and should display current stage of the progress with highlited color

**Comment by willshowell** [comment]
Please use the issue template for feature requests or else this will be closed.

**Comment by josephperrott** [comment]
This is likely a component we will not create as it does not fall within the material design spec.  However, you should be able to use the current `mat-progress-bar` within a custom component you create to perform the desired function.

In the future please use the issue/feature request template provided.
