### ISSUE TITLE
MdStepper not an exported component of @angular/material

### ISSUE THREAD

**Issue by KevinMind** [angular/material2#7330]
Cannot find any issues concerning this, but I cannot import MdStepper.

import {MatStepperModule} from '@angular/material'; Does not recognize this.
import {MdStepperModule} from '@angular/material'; Does not recognize this.

Does anyone know how to import MdStepperModule properly?

**Comment by crisbeto** [comment]
`MdStepperModule` should work. What version of Material do you have installed?

**Comment by KevinMind** [comment]
"@angular/material": "^2.0.0-beta.10",

**Comment by crisbeto** [comment]
The stepper component was released in beta.11.

**Comment by josephperrott** [comment]
Closing as `beta.11` is required to import `MatStepper`
