### ISSUE TITLE
[Table] Allow rows to be anchors 

### ISSUE THREAD

**Issue by alex321** [angular/material2#7333]
#### Feature request:
Would it be possible to provide support to make `md-row` be surrounded by an anchor tag?

#### What is the expected behavior?
It is useful to be able to use browser shortcuts or right-click contextual menu for rows of a table to open in new tabs, etc. In order to do that easily, the table rows itself need to be `<a>`.

#### What is the use-case or motivation for changing an existing behavior?
It helps in order to diversify the usability of the `md-table`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: 2.0.0-beta.11

**Comment by jelbourn** [comment]
Being an anchor tag would hurt the accessibility of the table overall

**Comment by mkollers** [comment]
Being an anchor would allow to right click -> open in a new tab. Do you have a suggestion to achieve this in another way?

**Comment by andrewseguin** [comment]
Here's an approach you can use: https://stackblitz.com/edit/angular-gpmd5v?file=app%2Ftable-basic-example.scss

There is an extra column that is taken out of the flow by using absolute positioning. It covers the whole row and contains an anchor.
