### ISSUE TITLE
There is no directive with "exportAs" set to "mdMenu" ("

### ISSUE THREAD

**Issue by KevinMind** [angular/material2#7336]
I'm implementing the mdMenu/matMenu component and get: 

`There is no directive with "exportAs" set to "mdMenu" ("`

when I ng serve.

1. I'm running material `"@angular/material": "^2.0.0-beta.11",`
2. I've imported MatMenuModule into a custom material module that is imported by my apps shared module so it is available. I've tried importing directly to component, no difference. Actually I even removed MatMenuModule completely from the app and I still get the same issue. I do not understand what the error is implying. Any help understanding and debugging this?

**Comment by Chan4077** [comment]
Show your full code, please.

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/7306

**Comment by josephperrott** [comment]
Closing as duplicate of: #7306
