### ISSUE TITLE
Why does the div containing inner-editor have a clear text password showing when the input type=password?

### ISSUE THREAD

**Issue by xtianus79** [angular/material2#7340]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
to have the password obfuscated... 

#### What is the current behavior?
password is in clear text via that div... 

#### What are the steps to reproduce?
type in a password in an input where the type="password"

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
na

#### What is the use-case or motivation for changing an existing behavior?
na/

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
na

#### Is there anything else we should know?
nope

**Comment by josephperrott** [comment]
Can you provide a reproduction of this issue as I am not seeing the issue myself.  Working example (here)[https://plnkr.co/edit/08wTPs2my1j54gaAV8xK?p=preview]

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
