### ISSUE TITLE
Md-table  -' has no exported member 'SelectionModel' 

### ISSUE THREAD

**Issue by HARIPRASADHARI** [angular/material2#7347]
#### Bug, feature request, or proposal:
Bug

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://plnkr.co/edit/EU3BBlViWpPf2NJW4PXx?p=preview
I am using this code for integrating multiple functionalities in md-table

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cli: 1.4.3
node: 8.4.0
os: linux ia32
@angular/animations: 4.4.3
@angular/cdk: 2.0.0-beta.11
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/flex-layout: 2.0.0-beta.8
@angular/material: 2.0.0-beta.11
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.4.0

#### Is there anything else we should know?
Hi i am using combined functionalities of filter,sorting,pagination in md-table ,after updating the material 2 version it showing following error

![select](https://user-images.githubusercontent.com/10670604/30899335-21788a90-a37d-11e7-9943-15b32fb3ea0b.png)
![select_browser](https://user-images.githubusercontent.com/10670604/30899374-436f198e-a37d-11e7-89b7-1d1f73f0d499.png)

**Comment by crisbeto** [comment]
The `SelectionModel` has been moved to the CDK. You can import it from `@angular/cdk/collections`.
