### ISSUE TITLE
Can we have Responsive Checkout Progress Bar

### ISSUE THREAD

**Issue by TarkeshNimje** [angular/material2#7348]
Can we have Responsive Checkout Progress Bar

Progress bar which can load on json data having some text for each stage, and should display current stage of the progress with highlited color

Currently we have normal progress bar where we cant find difference at different stages of progress

here is link of how it sholud be for different stages
https://codepen.io/whqet/pen/EJgwb

currently using angular 4

**Comment by grizzm0** [comment]
This is a stepper and was released in beta 11.

See:
https://material.angular.io/components/stepper/overview
https://material.io/guidelines/components/steppers.html

**Comment by josephperrott** [comment]
This is likely a component we will not create as it does not fall within the material design spec. However, you should be able to use the current mat-progress-bar within a custom component you create to perform the desired function.

In the future please use the issue/feature request template provided.
