### ISSUE TITLE
cdk(feature): Provide custom overlay container

### ISSUE THREAD

**Issue by actra-gschuster** [angular/material2#7349]
#### Bug, feature request, or proposal:
[x] Feature request

#### What is the expected behavior?
In certain scenarios the overlay container has to be positioned somewhere else than as last element of document.body.
The developer should be able to provide a NativeElement (HTMLElement) to CDK referencing a container to be used as overlay container.

#### What is the current behavior?
Overlay container is appended as last element to document.body

#### What is the use-case or motivation for changing an existing behavior?
In my case I have a themeing component, inside which all the material styling is applied but the overlay isn't matched as it is positioned outside.
Only applying the class to the container isn't enough as it has to be a child of `<my-theme>`.

```
<my-app>
    <my-theme class="myAngularMaterialTheme">
        <!-- all components here get styled correctly //-->
    </my-theme>
</my-app>
<div class="cdk-overlay-container"></div>
```

Currently I'm hacking it by changing it's position inside MyThemeComponent:
```
@Component({})
export class MyThemeComponent {
    constructor(elementReference: ElementRef, overlayContainer: OverlayContainer) {
        if(overlayContainer.getContainerElement()) {
            setTimeout(() => elementReference.nativeElement.appendChild(overlayContainer.getContainerElement()), 0);
        }
    }
}
```

**Comment by willshowell** [comment]
Based on the language [here](https://github.com/angular/material2/blob/master/src/cdk/overlay/overlay.md#the-overlay-container), you should be able to provide custom overlay containers. I haven't investigated, so I don't know how flexible that is.

**Comment by actra-gschuster** [comment]
I had seen that and tried to implement it in my module but it didn't seem to work, I'll check that again the next days.

**Comment by willshowell** [comment]
@actra-gschuster see this example (from a similar issue) for providing a different overlay container 

https://stackblitz.com/edit/angular-material2-issue-ansnt5?file=app%2Fapp.module.ts

**Comment by actra-gschuster** [comment]
Thanks for the demo!
I now managed it to use an element declared in the template as OverlayContainer by "reading" it with a directive that sets the reference on a "service" class that is used / provided as my custom OverlayContainer.

Problem solved, issue closed - thanks again!

```
import { OverlayContainer } from '@angular/cdk/overlay';
export class CdkOverlayContainer extends OverlayContainer {
    /**
     * Set the container element from the outside, e.g. from the corresponding directive
     */
    public setContainerElement(element: HTMLElement): void {
        this._containerElement = element;
    }
    /**
     * Prevent creation of the HTML element
     */
    protected _createContainer(): void {
        return;
    }
}
```

```
import {
    Directive,
    ElementRef,
    Renderer2
} from '@angular/core';
import { CdkOverlayContainer } from './cdk-overlay-container';

@Directive({
    selector: '[myCdkOverlayContainer]'
})
export class CdkOverlayContainerDirective {
    protected renderer: Renderer2;
    protected elementReference: ElementRef;
    protected cdkOverlayContainer: CdkOverlayContainer;
    constructor(renderer: Renderer2, elementReference: ElementRef, cdkOverlayContainer: CdkOverlayContainer) {
        this.renderer            = renderer;
        this.elementReference    = elementReference;
        this.cdkOverlayContainer = cdkOverlayContainer;
        
        this.renderer.addClass(this.elementReference.nativeElement, 'cdk-overlay-container');
        this.cdkOverlayContainer.setContainerElement(this.elementReference.nativeElement);
    }
}
```

**Comment by jgeiger-cr** [comment]
@actra-gschuster any chance you could provide a bit more detail?  I'm struggling to fully implement your approach yet it seems exactly what I need.   Anyway thanks a lot for your idea.

**Comment by actra-gschuster** [comment]
Where exactly are you struggeling?
Despite a "{provide: OverlayContainer,...}" there shouldn't be more code than shown above.
