### ISSUE TITLE
Wrong module name in the documentation (MatTabsModule)

### ISSUE THREAD

**Issue by davidtw** [angular/material2#7351]
#### Bug, feature request, or proposal:
In the [documentation for the tabs module](https://material.angular.io/components/tabs/api), under the api tab, the import example is :
```
import {MatTabsModule} from '@angular/material';
```
If I'm not mistaken it should be :
```
import {MdTabsModule} from '@angular/material';
```

#### What are the steps to reproduce?

Go to https://material.angular.io/components/tabs/api under the API tab

**Comment by josephperrott** [comment]
As of `2.0.0-beta.11`, all the material modules are now available as `Mat[ModuleName]`.
