### ISSUE TITLE
md-datepicker freeze when try to bind a date value

### ISSUE THREAD

**Issue by theShadow89** [angular/material2#7352]
#### Bug, feature request, or proposal:

use typescript `get` to retrieve a date cause a freeze issue

#### What is the expected behavior?

should bind the date value

#### What are the steps to reproduce?

http://plnkr.co/edit/0Kq0MYBLJJCTpRGEQHQl

Executing the Plunk will freeze all. Be careful

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Chrome, Angular 4, Material 2.0.0-beta.10

**Comment by josephperrott** [comment]
This is being caused by having a getter which returns a new `Date` every time it is called.   Because the value is never the same, it causes angular run a new change detection cycle on every new `Date` that is created.
