### ISSUE TITLE
Dialog refresh issue

### ISSUE THREAD

**Issue by deviloper** [angular/material2#7354]
Video:
https://drive.google.com/file/d/0BwjvL6x2McNZSmhoTjBNaFBVTUk/view?usp=sharing

A 3D point picking tool is activated by the toolbox component. 
I give to the tool (it's an independent class) the reference to a callback function to call when the user clicks on the 3D model.
When the dialog shows it doesn't show button icons and input text until i resize the window (!!!) and the same happens then i try to close the dialog window as you can see in the video.
Trying to call directly the openDialog function without using a callback it works perfectly, so I think the problem is the use of services in callback functions. Is it possible?
To reproduce the issue i think it's sufficient to open a dialog from a callback function.

Angular versions: 4.00 -> 4.4.3
Typescript version: 2.3.6
Material versions: 2.0.0 beta-8 -> beta 11
Browser: Chrome/Firefox

There is no message in F12 developer tools neither in Chrome nor in Firefox

**Comment by deviloper** [comment]
Just solved!!!

To make the dialog working correctly I used a promise instead of the callback I used previously.

Anyway I think it should be possible to open dialogs from callback functions too.

**Comment by willshowell** [comment]
Can you share a little code?

**Comment by josephperrott** [comment]
There is not any preventing a dialog from opening from within a callback.  Likely the callback is occurring outside of the angular zone, requiring something else to trigger a change detection cycle.
