### ISSUE TITLE
MatRadioGroup does not have exportAs

### ISSUE THREAD

**Issue by princemaple** [angular/material2#7356]
#### Bug, feature request, or proposal:
bug/feature

#### What is the expected behavior?
be able to reference a radio group using template ref

#### What is the current behavior?
can't do

#### What are the steps to reproduce?
Not really needed
https://github.com/angular/material2/blob/master/src/lib/radio/radio.ts#L74-L80
no `exportAs`

#### What is the use-case or motivation for changing an existing behavior?
1. to align with md-button-toggle-group
2. to do something like

```html
<md-radio-group #type="mdRadioGroup"> ... </md-radio-group>
<div [ngSwitch]="type.value"> ... </div>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng4.4. md2 beta11

#### Is there anything else we should know?
N/A

**Comment by DevVersion** [comment]
@josephperrott I wonder if it would make sense to add the `exportAs` to most of our components?

**Comment by josephperrott** [comment]
@DevVersion Yeah, I think it would.  I'll create a new issue to track moving them all over.

@princemaple I am going to close out this issue in favor a single issue to track ensuring that all of our Directives have `exportAs`

**Comment by princemaple** [comment]
Thanks!
