### ISSUE TITLE
[question] cdk keycodes

### ISSUE THREAD

**Issue by realappie** [angular/material2#7358]
Whats the idea behind using the keycodes in [here](https://github.com/angular/material2/tree/master/src/cdk/keycodes)  ? 

I was looking at your implementation of the [dialog](https://github.com/angular/material2/blob/master/src/lib/dialog/dialog.ts) and have noticed you are using it to for example detect when the user pressed escape.

You do that in a rather interesting way, you add an event listener to the document which executes a method which eventually checks the keycode.

My question is, why did you prefer this approach for handling keydown events instead of using HostListener like this.

`@HostListener('document:keydown.Escape', ['$event']) ...`

I am fully aware of the fact I should be on Stackoverflow for _questions_, but this question is related to internal code rather than the usage of it, therefor I thought this would be a better place.

**Comment by willshowell** [comment]
Related https://github.com/angular/material2/pull/3082 and https://github.com/angular/material2/pull/6682

**Comment by josephperrott** [comment]
Closing as the discussion and explanations are available in the prs linked above.

**Comment by realappie** [comment]
@willshowell Although PR #3082 demonstrates the usage of `document.addListener('keydown')....` I don't understand why that approach was preferred over `HostListener`. In the PR `host` is replaced with the verbose `addListener` approach, but `HostListener` would have got the job done in a cleaner fashion.

Both approaches work just fine, the one is just way more code than the other. And I'm curious based on what the decision was made :)
