### ISSUE TITLE
Noob help changing the primary color

### ISSUE THREAD

**Issue by Ronin11** [angular/material2#736]
I want to change the primary color. I found the _default-theme.scss in the core folder, I tried to use sass to compile it, even after changing the name and compiling it produced an empty file. I feel like I'm doing this wrong, what is the correct way to set the primary color pallete?

Thanks,
Nate

**Comment by patrickschlueer** [comment]
I don't know if this is the right way (maybe I misinterpreted someone saying that this _default-theme thing is just for upcoming theming) but the first thing working for me was changing the styles in the component (for example there are styled in the toolbar.js) so I just replaced the color code for the whole solution

If I did it wrong and there is something else, let me know

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/724

**Comment by jelbourn** [comment]
This is tracked via #123 

We currently don't have a way for the end-user to customize the theme; this will be coming before beta.

**Comment by alexsorokoletov** [comment]
So, again, what is the suggested way to change primary color or adjust material theme?
I saw this doc https://github.com/angular/material2/blob/master/docs/scss-theming.md  but it doesn't tells me what to do actually

**Comment by jelbourn** [comment]
We unfortunately don't have user-controlled theming available yet at this
point in the alpha. It will be coming before we get to a beta stage.

**Comment by francisoud** [comment]
@alexsorokoletov (I'm not part of material2 team;) ) as a **temporary** workaround you could fork material, modify [_default-theme.scss](https://github.com/angular/material2/blob/master/src/core/style/_default-theme.scss) and replace you npm dependency from material2-core to your own version...
But let me be clear this is **_bad idea_** and I'm not even sur it would work ;)

**Comment by alexsorokoletov** [comment]
Thanks guys. I've heard similar solution from other person. As for now I reference Palette and theming functions in app component scss and add styles I need there. For toolbar this worked nice, but looking at button makes me dizzy :)
