### ISSUE TITLE
Create exportAs aliasing for all Components/Directives to allow for template referencing

### ISSUE THREAD

**Issue by josephperrott** [angular/material2#7361]
This issue is meant to track which `@Component`s and `@Directive`s include `exportAs`aliases:

- [x] MatAutocomplete
- [x] MatButton
- [x] MatAnchor
- [x] MatButtonToggleGroup
- [x] MatButtonToggle
- [x] MatCard
- [x] MatChip
- [x] MatChipList
- [x] MatDatepicker
- [x] MatDatepickerInput
- [x] MatAccordion
- [x] MatExpansionPanel
- [x] MatFormField
- [x] MatGridList
- [x] MatGridTile
- [x] MatIcon
- [x] MatInput
- [x] MatTextareaAutosize
- [x] MatList
- [x] MatListItem
- [x] MatMenuItem
- [x] MatMenu
- [x] MatMenuTrigger
- [x] MatSelect
- [x] MatPaginator
- [x] MatProgressBar
- [x] MatProgressSpinner
- [x] MatRadioGroup
- [x] MatRadioButton
- [x] MatHorizontalStepper
- [x] MatVerticalStepper
- [x] MatStep
- [x] MatTable
- [x] MatRow
- [x] MatHeaderRow
- [x] MatTab
- [x] MatTabGroup
- [x] MatToolbar
- [x] MatToolbarRow
- [x] MatTooltip

**Comment by crisbeto** [comment]
While we're at it, we should add it to the `validate-decorators` tslint rule to make sure that we don't forget about.
