### ISSUE TITLE
Mis-aligned Input when in PortalHost

### ISSUE THREAD

**Issue by wallace41290** [angular/material2#7368]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Inputs to look the same all the time

#### What is the current behavior?
Alignment is not right when using input in PortalHost

#### What are the steps to reproduce?
Get yourself a portal host setup:
Component TS:
```
@Directive({
  selector: '[panelHeader]ng-template',
})
export class PanelHeaderDirective extends TemplatePortal<any> {
  constructor(templateRef: TemplateRef<any>, viewContainerRef: ViewContainerRef) {
    super(templateRef, viewContainerRef);
  }
}

@Component(...)
export class PanelComponent {
  @ContentChild(PanelHeaderDirective) panelHeader: PanelHeaderDirective;
}
```
HTML for PanelComponent:
` <ng-template [cdkPortalHost]="panelHeader"></ng-template>`

Use the component with the Portal and pop an input in there:
```
<my-panel>
     <ng-template cbPanelHeader>
          <mat-form-field >
               <input matInput placeholder="Title">
               <mat-icon matPrefix>label</mat-icon>
          </mat-form-field>
     </ng-template>
</my-panel>
```

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
Maybe tomorrow I will have time to put this in a plunkr

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.3
Material 2.0.0-beta.11
Mac OSX
typescript 2.3.3
testing on latest Chrome

#### Is there anything else we should know?
Check out the screenshot here, you can see the text is too low:
![screen shot 2017-09-27 at 3 46 19 pm](https://user-images.githubusercontent.com/11969737/30934684-4d1fcf54-a39c-11e7-9547-b33ca04b40da.png)

**Comment by josephperrott** [comment]
I was not able to reproduce the issue based on the steps you outlined here.

As you can see in [this repro](https://stackblitz.com/edit/angular-material2-issue-7368?file=app/app.component.html) the alignment is the same regardless of being within a portalHost.

**Comment by wallace41290** [comment]
My apologies, after further digging I have found that I had a global style in there to fix some inconsistent font sizes with a previous version of Materail
