### ISSUE TITLE
Cannot use icon component with Angular2 rc2

### ISSUE THREAD

**Issue by netmikey** [angular/material2#737]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
material2's icon component should be usable with current Angular RCs

#### What is the current behavior?
material2's icon component is only usable with Angular2 RC1 because of the fixed dependency `"@angular/http": "2.0.0-rc.1"`

#### What are the steps to reproduce?
try to use material2's icon component with `ng-cli 1.0.0-beta.6` and `angular 2.0.0-rc.2`.

**Comment by jelbourn** [comment]
You should be able to use rc2 with it, just ignore the peer dependency warning from npm.

**Comment by netmikey** [comment]
Unfortunately, these are errors, not warnings: `npm install` yields a non-zero exit code.

    npm ERR! Darwin 15.5.0
    npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install"
    npm ERR! node v4.4.3
    npm ERR! npm  v2.15.3
    npm ERR! code EPEERINVALID

    npm ERR! peerinvalid The package @angular/http@2.0.0-rc.2 does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer @angular2-material/icon@2.0.0-alpha.5-2 wants @angular/http@2.0.0-rc.1
