### ISSUE TITLE
Material 2 datepicker not working with el-GR locale

### ISSUE THREAD

**Issue by gtzinos** [angular/material2#7383]
Hi guys,

I am trying to set a locale in my datepicker but i am facing an issue. When someone select a date it display the correct format in my input field (dd/mm/yyyy) but when he tries to change the date it can't parse the date to start from the selected month instead it displays the current month. *if i will remove my locale it works fine but i need it.

An example:

User select 09/05/2017  (datepicker locale = el-GR) (dd/mm/yyyy from locale)
input field now has 09/05/2017
User click to change the date and the datepicker opens at september (it can't parse the previous to start from june).

I am using material-beta-10, currently can't upgrade to beta-11 to test your upgrade, so any workaround to keep my locale ?

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/4358 and all the other related issues

**Comment by julianobrasil** [comment]
@gtzinos, if you just want to represent the adate correctly in dd/mm/yyyy, one approach is to work with MdMomentDateModule (which is temporarily bugged but it alread has a fix on the way). 

The other approach, where you work with regular javascript Date objects is to use the MdNativeDateModule and override it's parse function building a custom date adapter: https://plnkr.co/edit/Z9JAiP?p=preview

**Comment by josephperrott** [comment]
To properly handle `dd/mm/yyyy` format you will need to use the `MomentDateAdapter`  you can check in with #7262 for status of the adapter.
