### ISSUE TITLE
stepper dependency on material icons

### ISSUE THREAD

**Issue by janisp** [angular/material2#7384]
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

Texts are not printed on the screen instead of the icons if the icon set is not present.

Brownie points:
I can set up another icons from another icon sets (e.g. FontAwesome)

#### What is the current behavior?

stepper component has the dependency on material icons. If material icons are not used, it's rendered as text on the screen.

![image](https://user-images.githubusercontent.com/2189263/30957760-a8c9eece-a497-11e7-9403-0fdd69bb49f5.png)

#### What are the steps to reproduce?

Index.html line 24 adds the necessary icons. If that line is commented out, icons will faill and text is printed on screen instead of icon.
Plunker template: https://plnkr.co/edit/n4ry3CkDsvV22aX4h5lo?p=preview

#### What is the use-case or motivation for changing an existing behavior?

I want to use FontAwesome icons (and I don't want to bundle the Material icons just for this one component)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material 2.0.0-beta.11
Angular 4.4.3

#### Is there anything else we should know?
Thanks for the Stepper component!

**Comment by jlkeiper** [comment]
I would be okay with a `svgIcon` input, or a way to inject a template to be used in place of the icon.

**Comment by sam-lex** [comment]
or an option to keep the numbers (no icon change).

**Comment by josehernandezv** [comment]
Any news on this?

**Comment by dfront** [comment]
you can set [completed]="false" on md-step and you will have only numbers instead of icons!!

**Comment by josehernandezv** [comment]
But that would make every step look like incompleted (with the gray color), even the ones already completed.

**Comment by sam-lex** [comment]
I was a bit reluctant on trying `[completed]="false"` suggested by @dfront, after reading that it would make it look like uncompleted. But it's actually not that bad 😅 

of course, it would've been better if it could be colored, since I'm using `linear` mode.

<img width="300" alt="screen shot 2017-10-28 at 10 06 49 am" src="https://user-images.githubusercontent.com/16538547/32134240-bfe73142-bbc7-11e7-98b7-90827502f061.png">

**Comment by xaviervansteene** [comment]
to replace the word "create" with the pen icon you need to add the google material font icon link.
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">

**Comment by cfremgen** [comment]
@sam-lex, We can override styles and use some "creative" css to get this.

`

::ng-deep mat-step-header {
    &:first-of-type {
        .mat-step-icon {
            * {
                display: none;
            }

            &:after {
                content: "1";
            }
        }
    }
}`

**Comment by ssgriffen** [comment]
Would someone mind please posting an example of overriding the create icon that shows for an editable step on the material 2 stepper. I've been struggling for hours trying to follow the docs and can't make it work so far @crisbeto

**Comment by cfremgen** [comment]
@ssgriffen 

Here's .scss version:

```
::ng-deep mat-step-header {
    &:nth-of-type(2) {
        .mat-step-icon {
            * {
                display: none;
            }

            &:after {
                content: "1";
            }
        }
    }
}
```

**Comment by ssgriffen** [comment]
@cfremgen I appreciate the example. However I am looking to only override the 'edit' icon when the step is in the edit state. The docs show a way to do this somwthing like this below

```
 <mat-horizontal-stepper>
 +      <ng-template matStepperIcon="edit">Custom edit</ng-template>
 +      <ng-template matStepperIcon="done">Custom done</ng-template>
 +
 +      <mat-step>Content 1</mat-step>
 +      <mat-step>Content 2</mat-step>
 +      <mat-step>Content 3</mat-step>
 +    </mat-horizontal-stepper>
```

but I haven't had success in implementing yet... @cfremgen  @crisbeto

**Comment by cfremgen** [comment]
I believe this is the commit you'll need https://github.com/crisbeto/material2/commit/8cc1aff709452044e332efb6ebb71f1030fc747c

But it's not in release yet.

You should be able to use my .scss as a starting point and only override if edit styles are applied. I am not sure though, I haven't encountered the exact scenario you're talking about.

**Comment by ssgriffen** [comment]
@cfremgen okay, thank you, I didn't notice it wasnt released yet

**Comment by sevdashubham** [comment]
any update on this?

**Comment by invingagan1** [comment]
is any one has example to use svg-icon in mat-icon for stepper.

**Comment by fableplay13** [comment]
::ng-deep mat-step-header {
	&:nth-of-type(1) {
		counter-reset: step-counter;
	}
	position: relative;
	.mat-step-icon {
		* {
			display: none;
		}
		&:after {
			content: counter(step-counter);
			counter-increment: step-counter;
			position: absolute;
			top: 50%;
			left: 50%;
			transform: translate(-50%, -50%);
		}
	}
}

this work for me

**Comment by anandbabud1987** [comment]
> you can set [completed]="false" on md-step and you will have only numbers instead of icons!!

this worked like charm

**Comment by Rouhollah** [comment]
probably you use another font-family instead default.
you can solve this issue with fix 'Material Icon' for font-family in pages that use stepper.
```
:host /deep/ .material-icons {
  font-family: 'Material Icons' !important;
}
```

**Comment by vksingh225** [comment]
> to replace the word "create" with the pen icon you need to add the google material font icon link `<link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">`

I think this is the best solution to utilize. Bcoz setting completed = "number" doesn't gives a nice UX.
