### ISSUE TITLE
md-select default value

### ISSUE THREAD

**Issue by jeewanaryal2012** [angular/material2#7387]
I am having the same issue, opening it again.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by willshowell** [comment]
Please fill out the issue template. Also note that select compares _by reference_ when checking which value to show. You may be interested in the `compareWith` function input.

**Comment by josephperrott** [comment]
Please use the issue template when reporting bugs and feature requests.
