### ISSUE TITLE
MdSelect Documentation Error

### ISSUE THREAD

**Issue by vincecampanale** [angular/material2#7389]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Documentation API section provides correct name of module for import.
https://material.angular.io/components/select/api 

The import statement says to import 'MatSelectModule' but the correct import is 'MdSelectModule'.

#### What is the current behavior?
'MatSelectModule' is incorrect or at least not applicable in the most recent version. 
The correct name of the module is 'MdSelectModule'.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

Try importing the 'MatSelectModule', it does not exist. A Plunker for this seems like overkill.

#### What is the use-case or motivation for changing an existing behavior?
Correct documentation.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using Angular 4.4.x, Material 2.0.0-beta.11, Linux (Gentoo), TS 2.3.4, and browser is irrelevant to this issue.

#### Is there anything else we should know?
You all have built an impressive Angular component library - thank you for all your hard work and the steady improvements :+1:

**Comment by willshowell** [comment]
Either should work right now. beta.11 just deprecated Md* in favor of Mat*. See https://github.com/angular/material2/blob/master/CHANGELOG.md#deprecation-of-md-prefix

**Comment by vincecampanale** [comment]
Got it thanks!
