### ISSUE TITLE
Modal opening moves body up

### ISSUE THREAD

**Issue by Kornhe** [angular/material2#7390]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Opening a modal does not moves body up.

#### What is the current behavior?
A negative `top` is applied to the body, causing elements to go up. This comes back to normal when closing the modal

#### What are the steps to reproduce?
* Create an element with `position: fixed`
* Scroll down your page so that you are not at the top
* Open the modal

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
* Angular core : 4.3.1
* Angular material : 2.0.0-beta.8
* TypeScript : 2.3.4

Tested on chrome 61
Win / Mac / Linux

#### Is there anything else we should know?
❤️

**Comment by Kornhe** [comment]
@willshowell 

This should show you the error : https://plnkr.co/edit/EuKloJ9RX6VlcIizaJCR?p=preview

**Comment by willshowell** [comment]
Thanks! Looks like this is due to the scroll blocking strategy that the dialog uses. It calculates the scrolltop and fixes the `<html>` element there until the dialog is closed.

If you care where the long gray bar is positioned vertically, then I think you should be specifying a `top` or `bottom` css property (which fixes it). That said, maybe @crisbeto should take a look.

**Comment by Kornhe** [comment]
Thanks a lot, I'll see if I find a temporary workaround :)

**Comment by crisbeto** [comment]
This seems to be because you haven't set the `top` value, which means that it uses the default `auto` value. You can work around it by setting `top: 0` on your element. [Here's a forked Plunkr.](https://plnkr.co/edit/WUDGzNzTXf865hPRSQWt?p=preview)

**Comment by AbakumovAlexandr** [comment]
@willshowell @crisbeto : Could you specify which element we need to add `top` or `bottom` CSS property to?
I see that `style="left: 0px; top: 0px;"` gets added to the `html` element automatically, but vertical scroll bar still shows up when a dialog opens.

**Comment by JesusRo** [comment]
You need to add `top` or `bottom` property to your fixed component (which has `position:fixed`).
In my case was the side bar

**Comment by ZgjimDida** [comment]
@AbakumovAlexandr 

Here you can see where to add that style.

https://github.com/liutian/push-admin/commit/a5ba4302bd67a8a7804ce13feb09c5522c516157

**Comment by dedeepyachowdary** [comment]
When I debug what I found was cdk-global-scrollback is the class which is making the header and scroll-buttons to disapper. So In that case I just removed calling that class from that particular component.

Eg:  document.getElementsByTagName('html')[0].classList.remove('cdk-global-scrollblock');

Adding that code should fix it.

**Comment by speige** [comment]
+1

I fixed it like this
```
.cdk-global-scrollblock {
	position: initial;
	width: initial;
	overflow: hidden;
}
```

**Comment by flyer1** [comment]
@speige Thanks for this. It was driving me nuts. In my case I had a fixed position panel on the left and when opening up an overlay via a button in that panel, the main content would disappear if the user had scrolled. This is b/c with the position:fixed and negative top setting it thought the body was overflowing. In addition the overlay's component position would be affected by the scrolled body, but it shouldn't be affected by the body scroll. Your approach did the trick.

**Comment by rahul-y-dudhane** [comment]
I faced same problem.
Following solution work for me,

  ```
  .cdk-global-scrollblock{
        position: static !important;
        width: initial !important;
        overflow-y: inherit !important;
      }
```
Put it into your global css or in dialog components loacl css (you have to enable view encapsulation in case of local)
