### ISSUE TITLE
autocomplete: There is no directive with "exportAs" set to "mdAutocomplete"

### ISSUE THREAD

**Issue by penrique** [angular/material2#7391]
#### Bug, feature request, or proposal:
Runtime error: There is no directive with "exportAs" set to "mdAutocomplete"

#### What is the current behavior?
Runtime error: There is no directive with "exportAs" set to "mdAutocomplete"

#### What are the steps to reproduce?
`npm install @angular/material@latest @angular/cdk@latest --save`

```
<md-form-field>
    <input type="text" placeholder="Pick one" mdInput [formControl]="myControl [mdAutocomplete]="auto">
    <md-autocomplete #auto="mdAutocomplete">
      <md-option *ngFor="let option of filteredOptions | async" [value]="option">
        {{ option }}
      </md-option>
    </md-autocomplete>
  </md-form-field>
```

This code works on Plunker, it does not work however when using version from npm.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by donroyco** [comment]
See #7361

**Comment by jymdman** [comment]
Are you on latest angular version?

**Comment by crisbeto** [comment]
It's most likely because you're on an older Angular version. Updating to 4.4.3 should resolve it.
