### ISSUE TITLE
Add a date format mask to md-datepicker 

### ISSUE THREAD

**Issue by kelumKP** [angular/material2#7393]
How to add a dateformat mask to md-datepicker ?

If I specify date format as `DD/MM/YYYY` , then once user start to type inside datepicker, user will be able to insert 

`DD` upto `31`
`MM` upto  `12` 
`YYYY` upto 9999 with separate `/`

so final result like following

A correct date with `__/__/____` mask.

currently once I try to insert this like following its not applying 

```
<md-form-field>
  <input mdInput [mdDatepicker]="picker" placeholder="Choose a date" ui-mask="XX.XX.XXXX">
  <md-datepicker-toggle mdSuffix [for]="picker"></md-datepicker-toggle>
  <md-datepicker #picker></md-datepicker>
</md-form-field>
```

SO I tried following approaches, none of this work 

`ui-mask="XX.XX.XXXX"`
`os-mask="3?9/19/9999"`
`MASK="DD/MM/YYYY"`

[Plunkr Example ](https://plnkr.co/edit/Orjed6WqYRku0GyuwHSC?p=preview)

**Comment by josephperrott** [comment]
You should be able to set the format of the date using the `@Injectable` [`[MdDateFormats]`](https://github.com/angular/material2/blob/master/src/lib/core/datetime/date-formats.ts)

**Comment by FilipLaurentiu** [comment]
How [MdDateFormats] should be used ? I have same issue and I don't know how to use MdDateFormats

**Comment by tinyking** [comment]
@FilipLaurentiu 
Do you know how to use MdDateFormats?

**Comment by FilipLaurentiu** [comment]
no, I don't. Can you explain ?

**Comment by tinyking** [comment]
@FilipLaurentiu 
no, I need format  result of mat-datepicker like 'yyyyMMdd', but no docment and example.
so sad
