### ISSUE TITLE
export 'materialModule' was not found in '@angular/material'

### ISSUE THREAD

**Issue by cfficaurzua** [angular/material2#7394]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
compile

#### What is the current behavior?

I get the following warning when compiling with ng serve 
WARNING in ./src/app/app.module.ts
87:12-26 "export 'MaterialModule was not found in '@angular/material'

I also get the following error
Property 'mdSortChange' does not exist on type 'MdSort'

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/core  4.4.3
angular/material 2.0.0-beta.11
angular/cdk 2.0.0-beta.11
typescript 2.3.3

#### Is there anything else we should know?
I tried to delete the node modules folder, then npm cache clean --force, and then npm install, but no effect at all

**Comment by josephperrott** [comment]
This is working as intended as `MaterialModule` was removed in the latest release.  See the changelog [here](https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes).
