### ISSUE TITLE
MaterialModule is missing. 

### ISSUE THREAD

**Issue by Sevensnake** [angular/material2#7398]
#### Bug, feature request, or proposal:
import {MaterialModule,  MdDatepickerModule, MdNativeDateModule } from '@angular/material';

#### What is the expected behavior?
Not sure when I included this that it is missing when I did npm install.  
   <md-tab-group and
Can't bind to 'selectedIndex' since it isn't a known property of 'md-tab-group'.

in the app.module.ts I am also getting MaterialModule has no exported member.

**Comment by josephperrott** [comment]
MaterialModule was removed as of `2.0.beta-11` as seen in the [changelog](https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes)

**Comment by Sevensnake** [comment]
Thanks Joey. I will try to make this change to my project

**Comment by Sevensnake** [comment]
`<mat-tab-group flex selectedIndex="">`  So this is the current change.  selectedindex not in use with this change?
Can't bind to 'selectedIndex' since it isn't a known property of 'mat-tab-group'.
1. If 'mat-tab-group' is an Angular component and it has 'selectedIndex' input, then verify that it is part of this module.
2. If 'mat-tab-group' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        </ul>
    </div>
    <mat-tab-group flex [ERROR ->]selectedIndex="{{tabSelected}}">
        <mat-tab label="{{firstlevel}}">

**Comment by Sevensnake** [comment]
for anyone else look at the node module references has changed also. Thanks works great.

**Comment by MattVoda** [comment]
@Sevensnake what exactly was the change that you made?

**Comment by bardiel** [comment]
@MattVoda I do is, what I think is documented somewhere...: I create a **MyMaterialModule** within my project which imports and re-exports every Module I need from **@angular/material**. Like so:

```ts
import { NgModule } from '@angular/core';

import {
  MatButtonModule,
  MatCardModule,
  MatCheckboxModule,
  MatChipsModule
  // and so on...
} from "@angular/material";

const MAT_MODULES  = [
  MatButtonModule,
  MatCardModule,
  MatCheckboxModule,
  MatChipsModule
  // and so on...
];

@NgModule({
  imports: MAT_MODULES,
  exports: MAT_MODULES,
  declarations: []
})
export class MyMaterialModule { }
```
