### ISSUE TITLE
md-form-field label/placeholder incorrect state with reactive form 

### ISSUE THREAD

**Issue by javadevil** [angular/material2#7399]
#### What is the expected behavior?
when we set Control in form group to assign value to mdInput placeholder should go into there position

#### What is the current behavior?
placeholder or label doesn't move to the position after set control

#### What are the steps to reproduce?
[Link stackbliz](https://stackblitz.com/edit/angular-material2-issue-ks7u1p)
Just click 'TEST' the problem will occure at input field

**Comment by javadevil** [comment]
play around.
It work correctly if not set new FormControl.

**Comment by jlkeiper** [comment]
This is already mentioned in #6849

**Comment by javadevil** [comment]
thank you so i close this
