### ISSUE TITLE
[Table] Horizontal overflow content not rendered correctly

### ISSUE THREAD

**Issue by zrilo** [angular/material2#7404]
#### Bug
md-table overflow hidden columns not rending correctly
![md-table overflow](https://user-images.githubusercontent.com/16678043/30996619-73ead39e-a505-11e7-9bd5-fa035427279b.PNG)

#### What is the expected behavior?
When table has more columns that can be visible shown, horizontal scrolling to bring those columns in to view should show consistent styling 

#### What is the current behavior?
When columns are scrolled in to view there is no white background or row borders. See image

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
up to date angular and material, all browsers

**Comment by josephperrott** [comment]
Can you please provide a reproduction case using [Plunker](https://goo.gl/DlHd6U)/[StackBlitz](https://goo.gl/wwnhMV)?

**Comment by andrewseguin** [comment]
I imagine that you have some min-widths set up on the column. If so, you'll want to set a min-width on the `mat-row` and `mat-header-row` as well

**Comment by benb7760** [comment]
@andrewseguin I came across this issue recently. As you suggested, it is resolved by adding a min-width to row and header-row that sum the min-widths of the columns. Do you still want a repro produced?

**Comment by andrewseguin** [comment]
If you're satisfied with the min-width then we should be good. Unfortunately I couldn't find any workaround to this. If columns want a specific min/max width, it's necessary to also adjust the row so that it doesn't shrink too much/

**Comment by enekonieto** [comment]
Putting min-width to row and header-row didn't help me. Putting min-width in mat-table did the trick.
