### ISSUE TITLE
mat-paginator display incorrect

### ISSUE THREAD

**Issue by stevenmi** [angular/material2#7405]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
should  display like this
https://material.angular.io/components/paginator/overview

#### What is the current behavior?
![error](https://user-images.githubusercontent.com/14286935/31001505-d4406270-a516-11e7-895d-1fce0cceb07b.png)

#### What are the steps to reproduce?
http://plnkr.co/edit/HQPFX1mgOvx7STnSy2lo?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2.0.0-beta.11-53c42a4

**Comment by crisbeto** [comment]
It will be fixed by https://github.com/angular/material2/pull/7263.

**Comment by davidmricardo** [comment]
It still doesn't work in Chrome!
In FireFox it shows fine, but not in Chrome!

I'm using:
