### ISSUE TITLE
Why so many Material Libraries?

### ISSUE THREAD

**Issue by Extarys** [angular/material2#7409]
I'm quite confused.

There is this one, which is the official Material for Angular.

There is also material-components-web which is a general verison that works everywhere and developed by Material team and then there is angular-mdc-web, same as material-components-web but for angular.

ARGH, What's going on at Google?

If I start a project with something and it gets abandoned then I'll need to switch everything and work twice. How can I make the right choice?

Also, do this follow material-components-web? I mean, if material-components-web release a feature or change something, this library should be updated, right?

**Comment by dherges** [comment]
Don't rely on Google's corporate design implementations for realising my very own corporate branding :rocket: :woman_cartwheeling:

**Comment by Extarys** [comment]
Si which one did you pick to help you get started?

**Comment by josephperrott** [comment]
Closing as this is not regarding the Angular Material library.

**Comment by Extarys** [comment]
@josephperrott Well, it is regarding Angular Material. I'm wondering what makes this one better that the 2 others. It's getting confusing :( Please help me :P

**Comment by mackelito** [comment]
Just try this library out.. you'll see that it's well designed and crafted... I have worked with both this and the one for angularjs and the team are doing a great job!

**Comment by Extarys** [comment]
Thanks for the input.

**Comment by dherges** [comment]
The `@angular/material` library is very good library, for sure! If the goal is to implement an app in material UI/UX, it's a good choice!

> If I start a project with something and it gets abandoned then I'll need to switch everything and work twice.

Maybe, I have mistaken the question. It sounded like you were trying to implement a corporate branding with the material libraries. I would not choose material for that. When goal is to implement an app in material, then go for it!
