### ISSUE TITLE
has no exported member 'MatExpansionModule'

### ISSUE THREAD

**Issue by Juliusdz** [angular/material2#7410]
#### Proposal:

Probably forgot to update [docs](https://material.angular.io/components/expansion/api) 

This:

`import {MatExpansionModule} from '@angular/material';
`

Should be:

`import {MdExpansionModule} from '@angular/material';
`

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/7313.

*For beta.11,*

> all components have been exported currently as Both Md* and Mat*. However ultimately Mat* should be used.
