### ISSUE TITLE
Set Icon on Stepper

### ISSUE THREAD

**Issue by jrsanchezalcala** [angular/material2#7412]
#### Bug, feature request, or proposal:
Set Cuscom Icon or another icon from md-icons on stepper

#### What is the expected behavior?
Ther is no directive of information about that

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
People can set other icons in each step

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4

**Comment by julianobrasil** [comment]
Related to #7384.

**Comment by josephperrott** [comment]
Closing as duplicate of #7384
