### ISSUE TITLE
compatibility chromium

### ISSUE THREAD

**Issue by oussamaABID** [angular/material2#7413]
#### Bug:
https://material.angular.io/ no working in chromium
version : Version 25.0.1364.160 Ubuntu 10.04 (25.0.1364.160-0ubuntu0.10.04.1)

''Uncaught TypeError: Object #<Object> has no method 'sendMessage' content.min.js:5
(anonymous function) content.min.js:5
c.onload content.min.''

**Comment by josephperrott** [comment]
This is working as expected as we support up to date evergreen browsers.  It looks like Chromium is [currently stable at version 54](https://www.chromium.org/developers/calendar)
