### ISSUE TITLE
[datepicker] wrong locale view of calendar

### ISSUE THREAD

**Issue by lippomano** [angular/material2#7414]
In my datepicker I set the `dateAdapter.setLocale('it');` and it formats correctly the date in the fields, but when I select for example 5/9/2017 and try to reopen the datepicker I see the calendar takes the first number as a month and not as day.

![cattura](https://user-images.githubusercontent.com/27501745/31015752-fff1bdd2-a521-11e7-9dec-d0351d9664ab.PNG)

Is something missing?

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/5640#issuecomment-314084516

**Comment by josephperrott** [comment]
Closing as this is working as expected as outlined in the [docs](https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings)
