### ISSUE TITLE
has no exported member 'MatSnackBarModule'

### ISSUE THREAD

**Issue by sheva007** [angular/material2#7415]
#### Bug, feature request, or proposal:
error in documentation for the "snack-bar" at:
https://material.angular.io/components/snack-bar/api

#### What is the expected behavior?
import {MdSnackBarModule} from '@angular/material';

#### What is the current behavior?
import {MatSnackBarModule} from '@angular/material';

**Comment by josephperrott** [comment]
This is working as expected after the latest (`beta.11`) release
