### ISSUE TITLE
md-chip color property does not work

### ISSUE THREAD

**Issue by pastafari** [angular/material2#7416]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-chip has a color property that is expected to change the color based on the theme. Quoting from the doc site:

> The selected color of an <md-chip> can be changed by using the color property. By default, chips use a neutral background color based on the current theme (light or dark). This can be changed to 'primary', 'accent', or 'warn'.

The example on the doc site displays the broken behavior (see screenshot).
![material-docs-screenshot](https://user-images.githubusercontent.com/193407/31018004-1ddab3b4-a548-11e7-8b7a-568b58b6c4ca.png)

#### What is the current behavior?
The color property seems to be ignored. 

#### What are the steps to reproduce?
I made a Plunkr with just an md-chip-list here: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

**For whatever reason, Plunkr refuses to load the Angular app. Don't have the time to figure that out right now!  

#### What is the use-case or motivation for changing an existing behavior?
This is a bug.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.3.4
Typescript: 2.3.4
Material: 2.0.0-beta.11
OS: OSX 10.12.5
Browsers: Chrome, Safari, Firefox

#### Is there anything else we should know?
No.

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/7261

**Comment by pastafari** [comment]
@willshowell thanks for the prompt response. I did search the issues before posting this, but didn't find anything in:open ! I'll close this as a dupe.
