### ISSUE TITLE
has no exported member 'MatTooltipModule'

### ISSUE THREAD

**Issue by sheva007** [angular/material2#7418]
#### Bug, feature request, or proposal:
error in documentation for the "tooltip" at:
https://material.angular.io/components/tooltip/api

#### What is the expected behavior?
import {MdTooltipModule} from '@angular/material';

#### What is the current behavior?
import {MatTooltipModule} from '@angular/material';

**Comment by willshowell** [comment]
For this and your other issue (#7415), see https://github.com/angular/material2/issues/7313.

*For beta.11,*

> all components have been exported currently as Both Md* and Mat*. However ultimately Mat* should be used.

**Comment by sheva007** [comment]
thank you @willshowell for the comment
currently I am using the following dependencies yet my app did not compile with "Mat", so I thought it is a typo in documentation.

"dependencies": {
    "@angular/animations": "^4.4.2",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.10",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@ngx-translate/core": "^8.0.0",
    "@ngx-translate/http-loader": "^2.0.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },

**Comment by willshowell** [comment]
Yeah the docs only represent the latest version, which is `2.0.0-beta.11`

**Comment by willshowell** [comment]
See [CHANGELOG](https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta11-carapace-parapet-2017-09-21) for more information

**Comment by sheva007** [comment]
@willshowell lol that is fast, thanks man. I will upgrade to 11

**Comment by josephperrott** [comment]
This is working as expected after the latest (`beta.11`) release
