### ISSUE TITLE
Error Using MdIcon and/or MdIconRegistry

### ISSUE THREAD

**Issue by griffiti** [angular/material2#742]
#### Bug, feature request, or proposal:
I've installed @angular2-material/icon package. I can import MdIconRegistry and MdIcon without errors. But when I add either directive or provider reference, I get the error attached.

#### What is the expected behavior?
To be able to use the MdIcon directive.

#### What is the current behavior?
An error is thrown.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-rc.1

#### Is there anything else we should know?

![mdicon-error](https://cloud.githubusercontent.com/assets/11247856/16259493/992a2a06-3828-11e6-8c6e-d51cb41a006e.png)

**Comment by jelbourn** [comment]
I can't reproduce your error in my sample app:
https://material2-app.firebaseapp.com/
https://github.com/jelbourn/material2-app

My guess is that you didn't also install `@angular2-material/core`, which all of the components depend on.

**Comment by griffiti** [comment]
Yes I do have core installed. MdInput, MdButton...everything else works and renders. Just when I bring in MdIcon or MdIconRegistry does the error occur.

**Comment by jelbourn** [comment]
Without seeing your project setup I can't really tell what might be wrong.

**Comment by griffiti** [comment]
I understand. I'm going to do some debugging and if necessary, I'll create a fresh project. Thanks!

**Comment by griffiti** [comment]
I figured it out. :) I had installed @angular2-material/core package. However, I had left it out in the SystemJS config file! Now everything works properly and I'm able to use MdIcon and MdIconRegistry, and I see icons with the buttons.

![systemjs-config](https://cloud.githubusercontent.com/assets/11247856/16291026/09507c82-38c8-11e6-8939-f8b7efeee33f.png)
