### ISSUE TITLE
body font size changes leaved md-input and md-select placeholder fonts inconsistent

### ISSUE THREAD

**Issue by yogeshgadge** [angular/material2#7422]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Consistent font size weight for mdInput  and mdSelect placeholder

#### What is the current behavior?

As of beta 11 

![image](https://user-images.githubusercontent.com/2423608/31027636-ead30e50-a518-11e7-8f00-af7bfdff45db.png)

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
https://plnkr.co/edit/wzyS0s397OazQaj5TPE3?p=preview

All I did was change body font size to 13px;
See index.html 
```html
<style>body { font-size: 13px; }</style>
```

#### What is the use-case or motivation for changing an existing behavior?

Allow customization of body font size. Clearly changing this causes inconsistencies elsewhere.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular Material Release version 
```
"version": "2.0.0-beta.11",
```

#### Is there anything else we should know?

Problem seems to be 
```css
.mat-select-trigger {
    font-size: 16px;
}
```
set somewhere.

**Comment by willshowell** [comment]
This is fixed on master via https://github.com/angular/material2/pull/6488

http://plnkr.co/edit/xJF49xaIi0scrHRM6G7t?p=preview

**Comment by crisbeto** [comment]
This won't be an issue in the next release. Closing.
