### ISSUE TITLE
Can't bind to 'placeholder' since it isn't a known property of 'mat-select'.

### ISSUE THREAD

**Issue by HarelM** [angular/material2#7426]
#### Bug
Error when running page/building for production:
Can't bind to 'placeholder' since it isn't a known property of 'mat-select'.

#### What is the expected behavior?
No errors

#### What is the current behavior?
Getting this error

#### What are the steps to reproduce?
Create an `mat-select` with place holder with `MATERIAL_COMPATIBILITY_MODE` flag as true as explained in https://www.npmjs.com/package/angular-material-prefix-updater

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Windows 10 x64.
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.4
node: 6.11.2
os: win32 x64
@angular/animations: 4.4.4
@angular/cdk: 2.0.0-beta.11
@angular/cli: 1.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/compiler-cli: 4.4.4
@angular/core: 4.4.4
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/material: 2.0.0-beta.11
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
typescript: 2.3.4
```

#### Is there anything else we should know?
I wasn't able to reproduce it in plnukr or stackbitz...

**Comment by HarelM** [comment]
Seems like an issue with the removal of `MaterialModule`, I forgot to add `MdSelectModule`
I would've expected an error saying `mat-select is not a recognized element` or something similar, much like what happens for `mat-slide-toggle` when not importing the `MdSlideToggleModule`

**Comment by josephperrott** [comment]
Closing as it seems you have sorted out the issue.  As you noted your apps module will need to import all of the material components you are using.

**Comment by HarelM** [comment]
I left it open due to unclear error message...
