### ISSUE TITLE
problem with npm install --save @angular2-material/{core,button,card}

### ISSUE THREAD

**Issue by ADominguezes** [angular/material2#744]
I have problems with the installation.

I write "npm install --save @angular2-material/{core,button,card}" but the respond is:

npm ERR! addLocal Could not install
npm ERR! Windows_NT 10.0.10586
npm ERR! argv
npm ERR! node v4.4.3
npm ERR! npm  v3.8.6
npm ERR! path G:\...
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'G:\...'
npm ERR! enoent ENOENT: no such file or directory, open 'G:\...'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!

What is the problem?

Regards

**Comment by wilcraig** [comment]
You need to specify which component of angular2-material you'd like to install. For a list of published packages, [see this page](https://www.npmjs.com/~angular2-material). So you'd type "npm install @angular2-material/core" for example

**Comment by griffiti** [comment]
Yeah that happened to me too! The instructions show that syntax, but it did not work for me either. You can install each package individually

`npm install --save @angular2-material/core`
`npm install --save @angular2-material/button`

Or update your package.json file then run **npm update**.

**Comment by ADominguezes** [comment]
ok, thank you.

Solved!!

**Comment by aquinum6** [comment]
I think this is just a way to present that you can choose any of the component to install and that the beginning (_npm install --save @angular2-material/_) is always the same: **{core,button,toolbar}** -> translate to: 'core' or 'button' or 'toolbar'.

Might be good idea to change this in docs to 3 lines to not confuse people.

**Comment by jelbourn** [comment]
Yeah, the `{core,button,toolbar}` syntax is using shell expansion, which won't work in Windows (until Windows 10 gets that sweet, sweet bash support). 

Changing the example in #762
