### ISSUE TITLE
Chips color property not respected

### ISSUE THREAD

**Issue by PlantPorridge** [angular/material2#7452]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Setting a chips color property to 'Primary', 'Accent' or 'Warn' changes the chip color based on the active theme.

#### What is the current behavior?
Setting a chips color property to 'Primary', 'Accent' or 'Warn' does not change the chip color.

#### What are the steps to reproduce?
Set the color property on a chip and observe no change.
A demo of this can be view in the Component Examples: https://material.angular.io/components/chips/examples

#### What is the use-case or motivation for changing an existing behavior?
The desired behaviour is what is described by the docs.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested using what ever version is active on the Material website on Chrome Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by ghd8** [comment]
See #7261

**Comment by josephperrott** [comment]
Closing as fixed by #7285
