### ISSUE TITLE
Flex-layout breaks space between inputs using layout row

### ISSUE THREAD

**Issue by Spanja** [angular/material2#7459]
#### Bug, feature request, or proposal:
The space is removed between inputs & select using fxLayout="row"

#### What is the expected behavior?
The space shouldn't be removed

#### What is the current behavior?
The space shouldn't be removed

#### What are the steps to reproduce?
Here is a working stackblitz : https://stackblitz.com/edit/angular-material2-issue-dr41cu

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
NG 4.4.3
Material 2.0.0-beta.11
Flex-layout 2.0.0-beta.9
Chrome 62

**Comment by julianobrasil** [comment]
Personally, I like the lack of space so the layout control is entirely under developer responsability (no surprises with tiny spaces messing with your layout) and you can use `fxLayoutGap="4px"` if you want that space back.

**Comment by willshowell** [comment]
Yeah this is just how flexbox works. I don't think there's anything for material or flex-layout to do here.

**Comment by josephperrott** [comment]
Closing, as @willshowell pointed out, this is expected as the spacing due to usage of flexbox.
