### ISSUE TITLE
NPM Packages - No SCSS?

### ISSUE THREAD

**Issue by praveenpuglia** [angular/material2#746]
Won't the npm packages be supplying the scss files instead of compiled css? I have these in my package.json.

```json
"@angular2-material/button": "2.0.0-alpha.5-2",
"@angular2-material/card": "2.0.0-alpha.5-2"
```
When I install the packages, I see the components with the **css** files instead of the **scss** files in the GitHub source. Am I doing something wrong?

I want to change the styles of these components slightly and can't seem to find a suitable way.

**Comment by SamClockwork** [comment]
There is none. They basically just use styles within the components. I read on gitter that someone used the one from classic material.

**Comment by msegers** [comment]
Not sure where you get that from Sam.

You need the core package as well I can see scss files in /core/style in my node_module/@angular2-material.

Is that what you're looking for?

**Comment by praveenpuglia** [comment]
I am not sure what was wrong but deleting the @angular2-material directory from node_modules and installing it back again solved the issue. I do see the scss files now.
