### ISSUE TITLE
[Table] Sort example incorrectly sorts empty string

### ISSUE THREAD

**Issue by CraigWarford** [angular/material2#7460]
#### Bug, feature request, or proposal:
The sort function has a bug in it.

#### What is the expected behavior?
Strings should not be converted to numbers during sort

#### What is the current behavior?
Empty string `""` is converted to zero with `+propertyA` and/or `+propertyB`, invalidating the comparison with other strings.  `0 < "x"` returns false, and `"x" < 0` is also false.  With a correct sort, `"" < "x"` returns true, and `"x" < ""` returns false.

#### What are the steps to reproduce?
Set any of the string values to empty ""

#### What is the use-case or motivation for changing an existing behavior?
Preventing propagation of faulty sample code

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material since introduction of Table

**Comment by andrewseguin** [comment]
Great thanks for the suggestion, we'll adjust the sort sample code so others don't copy/paste it into their apps
