### ISSUE TITLE
Add documentation for MomentDateAdapter usage

### ISSUE THREAD

**Issue by emreavsar** [angular/material2#7464]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
There should be at least a small guide (preferably official docs) about how to use the newly (in beta 11) introduced MomentDateAdapter for the datepicker.

#### What is the current behavior?
No docs at all.

#### What are the steps to reproduce?
1. Check release notes of beta 11 and be happy about these words:
> datepicker: Add Moment.js adapter (#6860) (9545427)
2. Go to official docs, and find nothing about how to introduce the moment adapter.

#### What is the use-case or motivation for changing an existing behavior?
Every feature should be documented.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Beta 11

#### Is there anything else we should know?
NO

**Comment by djleonskennedy** [comment]
@emreavsar You just need extend "DateAdapter" class

[date-adapter.ts](https://github.com/angular/material2/blob/master/src/lib/core/datetime/date-adapter.ts#L21)

**Comment by rkrzewski** [comment]
To use the adapter, you need to import `MdMomentDateModule` into your app module and you are good to go. You can use `moment.Moment` objects as `ngModel` for the date picker.
 
The problem that `@angular/material-moment-adapter` module has not been published to https://npmjs.com yet. I worked around that by ripping out the sources from https://github.com/angular/material2/tree/master/src/material-moment-adapter/adapter and pasting them into a folder in my app's source tree. Works well enough for now, but I'd love to switch to a published version.

**Comment by Yeradon** [comment]
@rkrzewski You can use the github builds: https://github.com/angular/material2-moment-adapter-builds. Just use `npm install https://github.com/angular/material2-moment-adapter-builds --save`

**Comment by rkrzewski** [comment]
That worked like a charm @Yeradon, thanks!

**Comment by yonatancohen** [comment]
Any example for using this?

**Comment by kwalski** [comment]
+1 an example please

**Comment by Yeradon** [comment]
@yonatancohen @kwalski https://stackblitz.com/edit/angular-material-moment-adapter-example

**Comment by mmalerba** [comment]
The last 2 examples here are for moment adapter: https://material.angular.io/components/datepicker/examples

**Comment by ankitraonka** [comment]
@mmalerba  is there a way to change the output from iso fromat to some custom format. I dont want datepicker to work with time zones as the service crops the time part and hence when that time is given back to server we get wrong dates based on timezones

**Comment by mohitvashishtha** [comment]
UPDATE: It is available on npm use following command to install it:

>  `npm i @angular/material-moment-adapter`

**Comment by Moutaz-homsi** [comment]
@ankitraonka  
i have the same issue , do you found any solution for this ?

**Comment by ankitraonka** [comment]
@Moutaz-homsi The best solution would be to use ControlValueAccessor and make a custom input component, this will have you in control of input and output of the component.

**Comment by Moutaz-homsi** [comment]
@ankitraonka, that's solve my problem for this issue , Have a great day and thanks a lot

**Comment by kamok** [comment]
Full process for using `Moment` objects instead of `Date` objects.

1. `npm i @angular/material-moment-adapter --save`
2. `npm i moment --save`
3.  Provide in your ngModule. `import { MatMomentDateModule } from '@angular/material-moment-adapter';`.
4. Your Datepickers will now automatically emit `Moment` objects

**Comment by ankitraonka** [comment]
@Moutaz-homsi 
https://stackoverflow.com/questions/47262449/how-to-change-output-format-of-material-2-date-picker

**Comment by Moutaz-homsi** [comment]
Thanks a lot @ankitraonka , this solved my issue , i repreduced the code here if anyone have the same problem : https://stackblitz.com/edit/angular-dlxnmx?file=app%2Fcva-date.component.ts

**Comment by starquake** [comment]
The DatePicker seems to be using Moment as dates just fine. But I have a model that has a Date as a property. I changed the type from Date to Moment but when my service retrieves data from the server the property of the model is just a string: 
"2018-03-31T00:00:00"

Why is this not a Moment object? Am I missing something?

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
