### ISSUE TITLE
md-datepicker calendar does not reopen after leaving / coming back to browser window

### ISSUE THREAD

**Issue by lDestiny** [angular/material2#7465]
1. open the calendar
2. click to datepicker input(calendar is closing but input stay focused)
3. leave browser window(click outside)
4. try to open calendar again

**Comment by djleonskennedy** [comment]
@lDestiny tried to reproduce by your case, datepicker working well

**Comment by lDestiny** [comment]
using angular material 1.1.4(trying 1.1.5, the same problem), browser chrome 60.0.3112.113
![example](https://user-images.githubusercontent.com/10610518/31077165-f525613e-a796-11e7-957f-0b7e4e33d02b.gif)

**Comment by willshowell** [comment]
@lDestiny, wrong repo. See https://github.com/angular/material.

**Comment by crisbeto** [comment]
Please post the issue to https://github.com/angular/material. Closing.
