### ISSUE TITLE
Stepper - Validation does not trigger for Select when clicking the steps instead of the next button

### ISSUE THREAD

**Issue by skyfremen** [angular/material2#7466]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Validation for select should be triggered when selecting the steps.

#### What is the current behavior?
Currently validation is only triggered for Inputs and not Select.

#### What are the steps to reproduce?
[Plunker Link] (https://plnkr.co/edit/TsQEglsgXexI1IrM95Bu?p=preview)
1) - Open Plunker
2) - Do not fill in anything and click on the stepper Step 2 (Note that only the Input is highlighted but Select is not highlighted)
3) - Click on the Next Button (Note that both Input and select is highlighted)

#### What is the use-case or motivation for changing an existing behavior?
Behavior consistancy

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material Beta 11

#### Is there anything else we should know?
NA

**Comment by josephperrott** [comment]
Closing as it appears this is working in beta.12 as seen [here](https://stackblitz.com/edit/angular-material2-issue-7466?file=app%2Fapp.module.ts)
