### ISSUE TITLE
Two tooltips on Safari for trimmed text

### ISSUE THREAD

**Issue by stadnykk** [angular/material2#7469]
#### Bug, feature request, or proposal:
When using mdTooltip directive with `text-overflow: ellipsis` for long text on hover appears 2 tooltips.
It happens only when text is trimmed.

#### What is the expected behavior?
Should appear only one. 

#### What is the current behavior?
Appears two tooltips 
(watch screenshot)  https://ibb.co/fAOLTw

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-6gatfl?embed=1&file=app/app.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Safari 11
Angular Material 2.0.0-beta.11

**Comment by andrewseguin** [comment]
Unfortunately Safari 11 just likes to add their own tooltips to truncated text. There's no programmatic way to get rid of this, but there are a couple workarounds that you can apply either in your template or styles.

Check out this link for more info: https://zzz.buzz/2017/07/31/prevent-tooltip-over-truncated-text-in-safari/
