### ISSUE TITLE
the placeholder and inputfield is mashed togheter, after using angular-material-prefix-updater

### ISSUE THREAD

**Issue by pacoma93** [angular/material2#7472]
![bug-angular-materials](https://user-images.githubusercontent.com/9317456/31080211-549050a2-a788-11e7-9f27-20423115dc5e.PNG)
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Placeholder moves up then clicked or there is input

#### What is the current behavior?
placeholder and input is stuck
#### What is the use-case or motivation for changing an existing behavior?
I just updated to 2.0.0-beta.11. and by doing that I needed to use mat-switcher -p src/tsconfig.json
to change all md to mat. By doing this. its froze all the inputfields and other components. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Im using fully uppdatet versions.
Angular/core and etc is on 4.4.4.4
#### Is there anything else we should know?
the weird part is that im not getting any errors at all. I followed the inctructions from the changelog: https://www.npmjs.com/package/angular-material-prefix-updater

**Comment by pacoma93** [comment]
Found the problem. it seemed that the CSS was not changed. just changed it to the new one

**Comment by vrcod** [comment]
I have exact same problem, can you elaborate on what it is exactly you've done to fix it?

**Comment by bigroly** [comment]
Hi @pacoma93 , what CSS file did you end up changing? I'm getting the same issue, but seems all md- prefixes in my app.css file has been updated to mat already.
