### ISSUE TITLE
Custom theme classes must be applied to parents

### ISSUE THREAD

**Issue by cladera** [angular/material2#7473]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I want to create several custom per-element themes and apply them using classes. I expect the custom theme class could be applied directly to a component. 

#### What is the current behavior?
It forces me to apply the class to element's parent which may apply undesired style changes to other elements.

This works:

```
<section class="blue-tabs">
 <md-tab-group [selectedIndex]="0">
    <md-tab label="Tab 1">
      Tab 1
    </md-tab>
    <md-tab label="Tab 2">
      Tab2
    </md-tab>
  </md-tab-group>
</section>
```

This won't:

```
<md-tab-group class="blue-tabs" [selectedIndex]="0">
  <md-tab label="Tab 1">
    Tab 1
  </md-tab>
  <md-tab label="Tab 2">
    Tab2
  </md-tab>
</md-tab-group>
```

#### What are the steps to reproduce?
Here is a live example reproducing the error:
https://stackblitz.com/edit/angular-material2-issue-bf2zfv?file=styles.scss

#### What is the use-case or motivation for changing an existing behavior?
Depending on the context you may want to show the same component with a different theme without changing the whole app theme. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
````
@angular/cli: 1.4.4
node: 6.9.5
os: darwin x64
@angular/animations: 4.4.4
@angular/cdk: 2.0.0-beta.11
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/material: 2.0.0-beta.11
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/platform-server: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.4
typescript: 2.2.2
```
#### Is there anything else we should know?
In beta-8 this worked as expected.

**Comment by jelbourn** [comment]
Based on my understanding of sass, there's no way for us to do something like this. The mixins output the full theme styles for the element and you cannot "append" them onto an existing selector. 

In general, the theming is intended to be applied to either the whole application or sections of an application rather than specific elements. If you are styling specific elements, I'd recommend just using custom css.

**Comment by cladera** [comment]
It did work with beta.8, though. Anyway, thank you.
