### ISSUE TITLE
Babili minification causes permanent disabled state

### ISSUE THREAD

**Issue by iaculch** [angular/material2#7486]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
After minification using the Babili plugin, Angular Material Tabs component should navigate to new tab on click

#### What is the current behavior?
After minification using the Babili plugin, All tabs are disabled upon initialisation

![pasted image at 2017_10_03 03_51 pm](https://user-images.githubusercontent.com/5279217/31110653-54288e00-a854-11e7-889e-2e80205a44bc.png)

#### What are the steps to reproduce?

https://github.com/iaculch/angular-starter

I have created a reproduction using an angular-starter project. Please see the latest commit for a simple changeset (adding babili and angular material tabs component).

Once the repo is cloned, `run npm run build:aot:prod && npm run run server:prod`, then navigate to the About Tab to see the behaviour. To compare, running `npm run server` will show a working version.

#### What is the use-case or motivation for changing an existing behavior?
Angular Material should be compatible with the Babili plugin, or documented to explicitly declare the limitation. Alternatively, if this is an issue with the Babili plugin, then a ticket should be raised to ensure compatibility with Angular material.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.4
Material: 2.0.0-beta.11
Webpack: 3.5.5
Babili-webpack-plugin: 0.1.2

#### Is there anything else we should know?

This issue occurs when the disabled state is used on other material components, such as the datepicker:

`				<md-form-field>
					<input mdInput required [(ngModel)]="date" [mdDatepicker]="picker" [disabled]="appointmentSet" placeholder="Choose a date" name="date">
					<md-datepicker-toggle mdSuffix [for]="picker"></md-datepicker-toggle>
					<md-datepicker #picker></md-datepicker>
				</md-form-field>`

**Comment by jelbourn** [comment]
Sounds like an issue with the minifier, I would raise an issue there.
