### ISSUE TITLE
Calendar Control

### ISSUE THREAD

**Issue by ArielBar** [angular/material2#7487]
Hey,
Is there a way to use the calendar of DatePicker control as a control in itself?

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/4801 and https://github.com/angular/material2/issues/6873

**Comment by ArielBar** [comment]
Thank you!

נשלח מה-iPhone שלי

‫ב-3 באוק׳ 2017, בשעה 18:04, ‏‏Will Howell ‏<notifications@github.com> כתב/ה:‬

**Comment by crisbeto** [comment]
Closing as a duplicate.
