### ISSUE TITLE
Snackbar is not using extraClasses in IE 11

### ISSUE THREAD

**Issue by qcryptic** [angular/material2#7493]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Snackbar should use the extraClasses css 

#### What is the current behavior?
The extraClasses css is not being used

#### What are the steps to reproduce?
1. Open a snackbar with something such as:
`this.snackBar.open("message", "dismiss", {duration: 5000, extraClasses: ["snackbar-success"]});`
2. Have the extra css set the background:
`snack-bar-container.snackbar-success { background-color: darkgreen; }`

#### What is the use-case or motivation for changing an existing behavior?
I need the css class to work!

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version 4.4.4
Material version 2.0.0-beta.11
OS Windows 7
Typescript 2.2.1
Browsers where it doesn't work: IE 11 and Opera 48

**Note:** it works as expected on chrome and firefox

**Comment by josephperrott** [comment]
Can you provide a reproduction?  I am not seeing the same issue as described in [this](https://plnkr.co/edit/FgRzm6kUtX4MdU2EMwlu?p=preview) plunker

**Comment by willshowell** [comment]
@qcryptic to be sure, which is the problem?

1. your green styles are not being applied
2. the class is not showing up when you inspect the DOM

**Comment by qcryptic** [comment]
Hmm I think I should investigate more...

Your plunkr works for me too.

When I inspect element and click on the snack-bar-container element for my app, none of the css even loads in the console...

![image](https://user-images.githubusercontent.com/14829626/31134243-2c1ae4a8-a827-11e7-8307-7d6c824a8045.png)

I have got it to work by adding !important to the color though. So, this doesn't seem to be a bug with angular materials

Also, the css does load in the console for your plunkr, so there must be something in my app messing with it I guess.

Anyway doesn't look to be an angular materials bug, apologies.
