### ISSUE TITLE
Error on open Dialog 

### ISSUE THREAD

**Issue by aledg** [angular/material2#7501]
#### Bug, feature request, or proposal:
using dialog I've this error 

 ng:///AppModule/SettingsComponent.ngfactory.js:914 ERROR TypeError: this._overlayRef.getState is not a function
    at MdDialogRef.webpackJsonp.../../../material/esm5/dialog.es5.js.MdDialogRef._getPositionStrategy (vendor.bundle.js:144904)
    at MdDialogRef.webpackJsonp.../../../material/esm5/dialog.es5.js.MdDialogRef.updateSize (vendor.bundle.js:144888)
    at MdDialog.webpackJsonp.../../../material/esm5/dialog.es5.js.MdDialog._attachDialogContent (vendor.bundle.js:145119)
    at MdDialog.webpackJsonp.../../../material/esm5/dialog.es5.js.MdDialog.open (vendor.bundle.js:145018)
    at SettingsComponent.webpackJsonp.../../../../../src/app/system/settings/settings.component.ts.SettingsComponent.newMember (main.bundle.js:2869)
    at Object.eval [as handleEvent] (ng:///AppModule/SettingsComponent.ngfactory.js:919)
    at handleEvent (vendor.bundle.js:124490)
    at callWithDebugContext (vendor.bundle.js:125960)
    at Object.debugHandleEvent [as handleEvent] (vendor.bundle.js:125548)
    at dispatchEvent (vendor.bundle.js:121082)

#### What is the expected behavior?

i want to show a simple dialog 

    const dialogRef = this.dialog.open(AddMemberComponent, {
      width: '1000px',
      height: '200px'
    });

#### What is the current behavior?
the dialog open and I can show the component right but the layout is totally wrong. It open on the left off the screen 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"dependencies": {
    "@angular/animations": "^4.4.4",
    "@angular/cdk": "^2.0.0-beta.11",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/material": "^2.0.0-beta.11",
    "@angular/platform-browser": "^4.4.4",
    "@angular/platform-browser-dynamic": "^4.4.4",
    "@angular/router": "^4.4.4",
    "@covalent/core": "^1.0.0-beta.7",
    "@swimlane/ngx-charts": "^6.0.2",
    "core-js": "^2.4.1",
    "d3": "^4.10.2",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "ng2-dnd": "^4.2.0",
    "rxjs": "^5.4.2",
    "tinymce": "^4.6.6",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.4",
    "@angular/compiler-cli": "^4.4.4",
    "@angular/language-service": "^4.4.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }

**Comment by crisbeto** [comment]
This looks identical to https://github.com/angular/material2/issues/7497, however I'm having a hard time reproducing it. Can you try to reproduce it in a Plunkr? [You can use this one as a base.](https://goo.gl/DlHd6U)

**Comment by aledg** [comment]
I've solved my problem in this way

1. delete file /package-lock.json
2. delete folder /node_modules
3. inside console $ npm install

the error is done now I've only this warning but the code and the layout is done and work fine.

[WDS] Warnings while compiling.
warnings @ vendor.bundle.js:66162

./node_modules/@covalent/core/loading/services/loading.factory.js
127:24-36 "export 'OverlayState' was not found in '@angular/cdk/overlay'
warnings @ vendor.bundle.js:66168

**Comment by julianobrasil** [comment]
@aledg, you're probably mixing matrial beta.10 with angular cdk beta.11.

**Comment by crisbeto** [comment]
@julianobrasil's explanation seems plausible, the `OverState` class was renamed to `OverlayConfig` in beta.11.

**Comment by drtobal** [comment]
same issue here with material 2.0.0-beta.11 & cdk 2.0.0-beta.11

**Comment by julianobrasil** [comment]
Did you remove node_modules before upgrade material/cdk?

**Comment by aledg** [comment]
yes I've remove node_module before

**Comment by julianobrasil** [comment]
@aledg, try to upgrade to beta.12. Though I haven't heard of any, it could be an oversight in beta.11.
