### ISSUE TITLE
[Table] Reverse 'when' arguments to align with trackBy

### ISSUE THREAD

**Issue by willshowell** [angular/material2#7503]
#### Bug, feature request, or proposal:
Proposal

#### What is the current behavior?

* `when` has the signature `(data, index)`
* `trackBy` has the signature `(index, data)`

#### Motivation

API zen with `trackBy`

#### Other
I understand this is a _very minor_ nit. Feel free to close if not worth the change.

cc @andrewseguin

**Comment by andrewseguin** [comment]
Legit nit - though I personally with `trackBy` was switched, I think it's best we're consistent. Thanks for the issue

**Comment by jelbourn** [comment]
@andrewseguin lets discuss with Misko. I find it super strange that trackBy is inconsistent with all of the native array methods and am slightly hesitant to change `when`

**Comment by andrewseguin** [comment]
Switching up `trackBy` would be great, but I'd imagine that would be unlikely. I'll remove `needs review` from the PR til we talk to Misko
