### ISSUE TITLE
ERROR when setting mdInput type="time" 

### ISSUE THREAD

**Issue by lukasasorensen** [angular/material2#7511]
ERROR DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('time') does not support selection.

**Comment by willshowell** [comment]
It seems to work here in Chrome

https://stackblitz.com/edit/angular-material2-issue-merk7c

**Comment by julianobrasil** [comment]
@lukasasorensen,  over here it works too. Unfortunately stackblitz seems to have some issues with Edge, I also tested it with plunker: https://plnkr.co/edit/6hdecFNP2YFfyeVVkKfO?p=preview

Try to isolate the problem.

**Comment by lukasasorensen** [comment]
UPDATE: It seems to not really affect anything I just get the same error in my console everytime I type/select inside the field. I still am able to submit the form successfully

**Comment by lukasasorensen** [comment]
SOLVED! the issue only arises when I have a placeholder for the time input....
