### ISSUE TITLE
MdDialog after opening add style and css class to html element, which breaks ui

### ISSUE THREAD

**Issue by lymychm** [angular/material2#7512]
#### Bug, feature request, or proposal:
bug i guess

#### What is the expected behavior?
do not add any styles and classes to `html` element

#### What is the current behavior?
MdDialog after open add to `html` element `class="cdk-global-scrollblock" style="left: 0px; top: 0px;"` and if to scroll down and open a dialog, we will get `<html lang="en" class="cdk-global-scrollblock" style="left: 0px; top: -1161px;">`

and after this style, all my background moves(even if it position: fixed)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular - 4.4.4
material/cdk - 2.0.0-beta.11
typescript - 2.4.2
All browsers

p.s. in beta.8 version i haven't seen this behavior

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/7390

**Comment by lymychm** [comment]
thank you, and sorry for duplicate, i didn't found this issue, it works for me, just add `top/bottom` css for `fixed` elements, and it helps

**Comment by speige** [comment]
+1

I fixed it like this
```
.cdk-global-scrollblock {
	position: initial;
	width: initial;
	overflow: hidden;
}
```

**Comment by akvaliya** [comment]
What is the status on this issue?
