### ISSUE TITLE
tooltip fixed position doesn't work in IE

### ISSUE THREAD

**Issue by dereklin** [angular/material2#7515]
On Oct 3, 2017, I took the tooltip example and change the position to fixed for the tooltip.  It works in Chrome, but it doesn't work in IE 11.

https://plnkr.co/edit/CwWB1uxM1GgTNMafxNyw?p=preview

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
