### ISSUE TITLE
CSS Gone after updating to Beta.11

### ISSUE THREAD

**Issue by WaterBleu** [angular/material2#7517]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
CSS persists

#### What is the current behavior?
Everything unstyled now

#### What are the steps to reproduce?
update from beta.10 to beta.11

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 1.6.6

**Comment by jelbourn** [comment]
There is not enough information here to reproduce any issue. [Our docs site](https://github.com/angular/material.angular.io/) is using beta.11 without issue, so this may be an unrelated issue in your app. Feel free to open a new issue if you have more information.
