### ISSUE TITLE
Implement Tap Targets from the Feature Discovery spec

### ISSUE THREAD

**Issue by mpiroc** [angular/material2#7519]
#### Bug, feature request, or proposal:
The Material Design spec describes a pattern called [Tap Targets](https://material.io/guidelines/growth-communications/feature-discovery.html#feature-discovery-design) for feature discovery, but I don't see them on the [roadmap](https://github.com/angular/material2/blob/master/README.md).

#### What is the expected behavior?
angular/material2 provides an md-tap-target component or directive.

#### What is the current behavior?
angular/material2 does not implement Tap Targets

#### What are the steps to reproduce?
N/A

#### What is the use-case or motivation for changing an existing behavior?
Tap Targets are part of the Material Design spec for Feature Discovery

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by josephperrott** [comment]
This specific component is not currently on our roadmap at this time.
