### ISSUE TITLE
material2 Getting Started is not compatible with Angular2 QuickStart

### ISSUE THREAD

**Issue by mLaird** [angular/material2#752]
#### Bug, feature request, or proposal:
The documentation and starting inconsistencies are too numerous to list, but include things like: 1. material2 uses a cli, QuickStart does not and installs a different configuration, 2.at least 2 files are named differently, system-config vs. systemjs.config, 3. material2 has some build step to move files into 'vendor' - QuickStart knows nothing about this. 4. material's code for system.config does not work when copied into QuickStart's system.config (page won't load), etc.etc. 5. when using the import statement in the material docs, and then adding MD_BUTTON_DIRECTIVES to the directives statement in a working page of QuickStart, the page does not load, and the Console says - button not found, --  and on and on.

#### What is the expected behavior?
I should be able to start the QuickStart project with the most recent rc version of Angular2, then go to material2 and see documentation to add angular/material2 - and it works at every step

#### What is the current behavior?
confusing, obvious inconsistencies, broken pages

#### What are the steps to reproduce?
See expected behavior.  Those steps are not possible at the moment.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
consistent ease of learning

#### Which versions of Angular, Material, OS, browsers are affected?
the recent Angular2 rc.3

**Comment by jelbourn** [comment]
The real issue is that the quick-start does not yet use the Angular CLI, which will be the "real" way moving forward.

**Comment by mLaird** [comment]
It is a leap of faith to think Angular CLI will be widely used.  It has
pros and cons.  Moreover, hundreds of thousands of software developers use
other development environments, and that will be very slow to change even
if Angular CLI is improved.  Angular2 QuickStart made a good decision to
describe an "editor neutral" way to get started.  Angular Material2 needs
to do the same thing if they want the product to be rapidly and widely
adopted by developers.

On Thu, Jun 23, 2016 at 8:05 PM, Jeremy Elbourn <notifications@github.com>
wrote:

> The real issue is that the quick-start does not yet use the Angular CLI,
> which will be the "real" way moving forward.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/material2/issues/752#issuecomment-228221439>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADDSb0jIKvWS7tBaxHojpB0CJkLn2SR2ks5qOx9egaJpZM4I9MTQ>
> .
>



-- 



Mike Laird

12 Arbor Creek Drive, Pittsford, New York 14534
mlaird@alum.mit.edu

". . . remembering on both sides that civility is not a sign of weakness,
and sincerity is always subject to proof. Let us never negotiate out of
fear, but let us never fear to negotiate."  - John F. Kennedy
