### ISSUE TITLE
Docs issue extra space in the md-side-nav

### ISSUE THREAD

**Issue by aravindfz** [angular/material2#7524]
#### Bug, feature request, or proposal:
Unnecessary additional whitespace in the `md-side-nav` docs view component

#### What is the expected behavior?
No white space should be there

#### What is the current behavior?
Extra space

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
![image](https://user-images.githubusercontent.com/22231525/31210135-73ac3fe2-a9ad-11e7-9719-b3d103b3b385.png)

#### What is the use-case or motivation for changing an existing behavior?
Look and feel

#### Is there anything else we should know?
Fix will be given by myself and I shall update a PR for the same

**Comment by josephperrott** [comment]
Closing as this is an issue with the docs site itself and should be filed at the [material.angular.io repo](https://github.com/angular/material.angular.io/issues)
