### ISSUE TITLE
Documentation: HTML code missing for Tab component example.

### ISSUE THREAD

**Issue by hhubik** [angular/material2#7531]
This is a documentation issue.  No HTML code is shown for the Tab component example.  Instead, the message `More examples coming soon!` is shown. See the attached screen shot.  

Using Firefox 55.0.3 32-bit on Windows 8.1 (64-bit).

![materialtabhtmlmissing](https://user-images.githubusercontent.com/14813201/31185877-1ed7dc04-a8fb-11e7-98ab-4272b89bd274.PNG)

**Comment by josephperrott** [comment]
Closing as it looks like this was corrected in the [latest release](https://material.angular.io/components/tabs/overview).

**Comment by hhubik** [comment]
Indeed, it is now fixed.
