### ISSUE TITLE
Dark theme colors are faded on md-slide-toggle

### ISSUE THREAD

**Issue by doughywilson** [angular/material2#7541]
#### Bug, feature request, or proposal:
When using the color feature of the md-slide-toggle with a dark theme, the colors are very faded. For example, my primary color palette is dark orange, but it comes out "peachy" and I can't seem to change it.

#### What is the expected behavior?
The expected behavior would be to leave the color as the primary described in the theme and not modify it.

#### What is the current behavior?
The color is "lightened."

#### What are the steps to reproduce?
Look at the documentation on the Angular material site for the md-slide-toggle, and change the theme to one of the dark colored themes.

**Comment by willshowell** [comment]
It seems to follow the [spec](https://material.io/guidelines/components/selection-controls.html#selection-controls-switch) very accurately.

> ### Light
> 
> Thumb On: Swatch 500, Opacity 100%
> Track On: Swatch 500, Opacity 50%
> 
> Thumb Off: Grey 50, #FAFAFA, Opacity 100%
> Track Off: #000000, Opacity 38%
> 
> Thumb Disabled: Grey 400, #BDBDBD, Opacity 100%
> Track Disabled: #000000, Opacity 12%
> 
> 
> Light theme for switches in hover, focused, pressed, disabled, and disabled focused states.
> 
> ### Dark
> 
> Thumb On: Swatch 200, Opacity 100%
> Track On: Swatch 200, Opacity 50%
> 
> Thumb Off: Grey 400, #BDBDBD, Opacity 100%
> Track Off: #FFFFFF, Opacity 30%
> 
> Thumb Disabled: Grey 800, #424242, Opacity 100%
> 
> Track Disabled: #FFFFFF, Opacity 10%


https://github.com/angular/material2/blob/c3af25b827e940a4b5b458f7c4848630b4ab9e63/src/lib/slide-toggle/_slide-toggle-theme.scss#L37-L44

**Comment by doughywilson** [comment]
Doh! I guess this should have been a bug report to the material design spec
itself because I think the faded colors on the dark background look
terrible. Is there any way to manually set the colors on the slide toggle?
