### ISSUE TITLE
sidenav don't appear correctly

### ISSUE THREAD

**Issue by lippomano** [angular/material2#7547]
When I open a  sidenav in `over` mode I don't see the grey background like the example:
[angular.io](https://material.angular.io/components/sidenav/overview) And if I click outside the sidenav it don't close. 
In my project the md-container contains all the page, and the md-sidenav is inside a <div class="card">
(inside my sidenav I have a timeline with some notes)
I am using @angular/material": "^2.0.0-beta.11"
whats wrong with this code:

<md-sidenav-container>
<md-sidenav position="end"
	mode="over"  #sidenav>
<div class="col-md-12">
	<div class="card card-plain">
		<div class="card-content custom-timeline">
			<ul class="timeline timeline-simple">
				<li class="timeline-inverted"
					*ngFor="let note of ticketBundleNoteList">

					<div class="timeline-badge success">
						<i class="material-icons">description</i>
					</div>
					<div class="timeline-panel">
						<div class="card-row">
							<div class="card-row-content padding-right10">
								<i class="material-icons">account_circle</i>
							</div>
							<div class="card-text card-row-content">
								<div class="timeline-heading">
									<h3>Nome</h3>
								</div>
								<div class="timeline-body">
									<p>{{note.text}}</p>
								</div>
							</div>
						</div>
						<div class="card-footer">
							<div class="stats">
								<span> <i class="material-icons">update</i>
									{{'cardfooter.inserteddate' | translate }} {{note.createdDate |
									date :('pattern.datehourmin' | translate)}}
								</span>
							</div>
						</div>
					</div>
				</li>
			</ul>
		</div>
	</div>
</div>
</md-sidenav>
</md-sidenav-container>

**Comment by julianobrasil** [comment]
Please, could you try to reproduce the issue in stackblitz with the minimum code needed to show it? https://stackblitz.com/edit/basic-sidenav?file=app/app.component.ts

**Comment by lippomano** [comment]
Probably I found the proble, my style.css file with : @import '~@angular/material/prebuilt-themes/deeppurple-amber.css'; is not loaded.
But I correcty include the styles.css in angular.cli 
"styles": [ "styles2.css",....]
Why this happening

**Comment by snapnurse-joshuamatthews** [comment]
@lippomano  Did you figure out what was going on? I am experiencing same issue.

**Comment by AhmedHasnaoui** [comment]
same here .mat-drawer-backdrop class adds no background-color.
Angular 4.4.6, Material 2.0.0-beta.12

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
