### ISSUE TITLE
Sidebar toggle support in toolbar ?

### ISSUE THREAD

**Issue by praveenpuglia** [angular/material2#755]
#### Bug, feature request, or proposal:
Feature Request

I know that sidebar component is there but can we have direct support for a hamburger button on the toolbar? For example the `.mdl-layout__drawer-button` in Material Design Lite in the layout section?
https://getmdl.io/components/#layout-section

**Comment by happyvig** [comment]
+1

**Comment by jelbourn** [comment]
This is something that we'd prefer to leave to individual apps to add since it is ultimately the most flexible, customizable approach.
