### ISSUE TITLE
Datepicker: Value must be either a date object recognized by the DateAdapter or an ISO 8601 string

### ISSUE THREAD

**Issue by MaurilioDeveloper** [angular/material2#7559]
ERROR Error: Uncaught (in promise): Error: Datepicker: Value must be either a date object recognized by the DateAdapter or an ISO 8601 string. Instead got: 

The date an error occurred at the time of displaying it, that is, I'm bringing the information from the bank and returning in the input, but the above error occurs.

**Comment by willshowell** [comment]
What does you initial value look like? Is it an object? A string?

**Comment by MaurilioDeveloper** [comment]
The input is returning in your NgModel a Object of type Date. And my search through of Back End, return Type Date.

**Comment by SanchezAta** [comment]
I have the problem... whats is the fix?

**Comment by willshowell** [comment]
@MaurilioDeveloper do you have a custom date adapter? This is where that error is thrown, maybe it'll help you identify,

https://github.com/angular/material2/blob/9fadf12c2941b739aa87e6d741b79dabc919dc61/src/lib/datepicker/coerce-date-property.ts#L12-L35

**Comment by MaurilioDeveloper** [comment]
Yes, I have. Follow below my code (Custom Date Adapter):
```

/** Adapts the native JS Date for use with cdk-based components that work with dates. */
export class CustomDateAdapter extends NativeDateAdapter {

  parse(value: any): Date | null {
    if ((typeof value === 'string') && (value.indexOf('/') > -1)) {
      const str = value.split('/');

      const year = Number(str[2]);
      const month = Number(str[1]) - 1;
      const date = Number(str[0]);

      return new Date(year, month, date);
    }

    const timestamp = typeof value === 'number' ? value : Date.parse(value);
    return isNaN(timestamp) ? null : new Date(timestamp);
  }

  // retirar quando for feito o merge da data por mmalerba
  format(date: Date, displayFormat: Object): string {
    date = new Date(Date.UTC(
      date.getFullYear(), date.getMonth(), date.getDate(), date.getHours(),
      date.getMinutes(), date.getSeconds(), date.getMilliseconds()));
    displayFormat = Object.assign({}, displayFormat, { timeZone: 'utc' });

    const dtf = new Intl.DateTimeFormat(this.locale, displayFormat);
    return dtf.format(date).replace(/[\u200e\u200f]/g, '');
  }

  
}

`
```

I import my CustomDateAdapter on the module :
{ provide: LOCALE_ID, useValue: 'pt-BR' },
{ provide: DateAdapter, useClass: CustomDateAdapter },

**Comment by MaurilioDeveloper** [comment]
I solved this problem. Thanks for your help @willshowell. I only convert the Date Json (That was returning) to Date, and it worked.

**Comment by kuncevic** [comment]
` this.date = new Date(<your_date_string>);` should help.

**Comment by mcanelo** [comment]
But, i don't understand. If i need the datepicker show a date in format 'DD/MM/YYYY', what i have to pass in ngModel to get this format? Or i have to call some of this funcions parse()  format() ?
 And, what is the second parameter of 'format' funcion?

**Comment by costea93** [comment]
The same problem, do you have guys any solutions how to fix that?

**Comment by mmalerba** [comment]
@mcanelo That's a bug with the `[value]` binding that will be fixed by #7831 you can workaround by using `[fromControl]` or `[ngModel]`. Also the `NativeDateAdapter` doesn't support DD/MM/YYYY so you'll need to use the `MomentDateAdapter` or a custom one

**Comment by mcanelo** [comment]
@mmalerba yeah, solved! thanks so much :)

**Comment by mansonkibe** [comment]
@mcanelo how did you solve it. Am getting the following error
`
Error: Datepicker: Value must be either a date object recognized by the DateAdapter or an ISO 8601 string. Instead got: 2017-10-31T08:37:07.000Z `

Am using reactive form where i have a service that is returning data from backend. 

snippet of the component

`<mat-form-field  class="form-group label-floating">
                        <input matInput [matDatepicker]="picker2" placeholder="Date After Distribution" formControlName="dateAfterDistribution">
                        <mat-datepicker-toggle matSuffix [for]="picker2"></mat-datepicker-toggle>
                        <mat-datepicker #picker2 ></mat-datepicker>
                    </mat-form-field>`

snippet of ts file


`
this.beneficiaryList.dateAfterDistribution;//interface is of type date
this.stoveForm.patchValue({
                    'dateAfterDistribution': this.dateAfterDistribution
                })`

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
