### ISSUE TITLE
MdTooltip : toolTip reappears after opening and closing a dialog

### ISSUE THREAD

**Issue by JDillon522** [angular/material2#7565]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Mouseover a button and the tooltip appears. 
Click the button and it opens a dialog, tooltip disappears. 
Close the dialog and there shouldn't be a tooltip.

#### What is the current behavior?
Mouseover a button and the tooltip appears. 
Click the button and it opens a dialog, tooltip disappears. 
Close the dialog and the tooltip reappears.

#### What are the steps to reproduce?
Plunker: https://plnkr.co/edit/HtKDFQ?p=preview

#### What is the use-case or motivation for changing an existing behavior?
If I click a button with a tooltip attached it should close the tooltip automatically. I obviously have no need of the extra information given by the tooltip.

**Comment by willshowell** [comment]
Should be fixed by https://github.com/angular/material2/pull/7258

**Comment by crisbeto** [comment]
Closing as a duplicate of https://github.com/angular/material2/issues/7245.
