### ISSUE TITLE
Separate specification site for Angular Material 2 similar to Angular Material 1 https://material.angularjs.org/latest/ ??

### ISSUE THREAD

**Issue by happyvig** [angular/material2#757]
#### Request :
Separate site for Angular Material 2 specifications / how-to samples / examples stuffs, similar to [Angular Material 1](https://material.angularjs.org/latest/) (https://material.angularjs.org/latest/)

I cannot find clear examples on layouts. proper usage of each components, etc else where. A separate site would be of very much use for the Angular 2 Material Design loving community.

**Comment by msegers** [comment]
There already is a site available, but I don't expect to see anything on there untill beta.
https://material.angular.io/ (All Angular2 things seem to be on .io).

As for now I'd use https://github.com/jelbourn/material2-app

Or, maybe better but I did not try yet. clone the repo and run the demo-app.
Documentation on how to use everything should become available later I bet.

**Comment by happyvig** [comment]
@msegers : Thanks

**Comment by happyvig** [comment]
Where can I get to know about the layout / grid system and stuffs ?

**Comment by DevVersion** [comment]
The layout system is not available yet.. See #45
The Grid List component is actually [here](https://github.com/angular/material2/tree/master/src/components/grid-list)

**Comment by happyvig** [comment]
@DevVersion  : Thanks
