### ISSUE TITLE
Additional Breaking changes in 2.0.0 beta-12

### ISSUE THREAD

**Issue by Stexxen** [angular/material2#7570]
#### Bug, feature request, or proposal:
Change to Release Notes for 2.0.0 beta-12

#### What is the current behavior?
Additional Breaking changes not mentioned in the Release Notes.

1. `OverlayContainer` has moved from `@angular/material` to `@angular/cdk/overlay`
2. `MD_DIALOG_DATA` has been removed completely and `MAT_DIALOG_DATA` must be used instead.

The OverlayContainer move also means the [Theming guide](https://github.com/angular/material2/blob/master/guides/theming.md) requires updating as well

**Comment by irowbin** [comment]
There is some CSS issues in dialog. Why i am seeing this `overflow-x`?

![capture](https://user-images.githubusercontent.com/13050078/31261648-4caa3a66-aa75-11e7-9743-97c84c92e62a.PNG)

**Comment by Chan4077** [comment]
@irowbin Post your problem as a separate issue please.

**Comment by willshowell** [comment]
@Stexxen Your first two [were already](https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes-2) mentioned [as breaking changes](https://github.com/angular/material2/blob/master/CHANGELOG.md#deprecation-of-md-prefix).

You are right about the theming guide needing an update.

**Comment by Stexxen** [comment]
@willshowell I understand what you are saying, but these 2 items specifically broke my code when upgrading from beta-11 to beta-12, so IMHO they are breaking changes in beta-12. 
But if this is how breaking changes are normally documented, then I will be more wary in future.

**Comment by willshowell** [comment]
Ah, sure. Both of those were deprecated in previous releases and listed as breaking changes, but were not immediately removed.

@jelbourn any clue why the BREAKING CHANGES message in https://github.com/angular/material2/pull/7112 did not get auto-added to the changelog?

**Comment by jelbourn** [comment]
Must be some issue w/ the changelog script, I'll add those
