### ISSUE TITLE
MatDialog afterClosed before beforeClose with NoopAnimationsModule

### ISSUE THREAD

**Issue by kxlow** [angular/material2#7572]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
beforeClose should be called before afterClosed when a dialog closes, even with NoopAnimationsModule being used.

#### What is the current behavior?
afterClosed is called before beforeClose when NoopAnimationsModule is being used.
Does not happen if using BrowserAnimationsModule

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-ehetcr

#### What is the use-case or motivation for changing an existing behavior?
Incorrect behavior.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
master

**Comment by TomDemulierChevret** [comment]
I strongly suspect it to belinked to #6736 & #6719 
The pull request fixing it has been available for more than a month but still not been merged alas...

**Comment by billyjacobs2014** [comment]
What is the delay? I will potentially have to downgrade 6 separate projects after tediously upgrading them all, only to find out I can't open a dialog over dialog in IE.

**Comment by josephperrott** [comment]
Closing as this is being addressed in #8051
