### ISSUE TITLE
Broken CSS - 2.0.0-beta.12

### ISSUE THREAD

**Issue by TomMettam** [angular/material2#7575]
After updating packages this morning:

+ @angular/material@2.0.0-beta.12
+ @angular/cdk@2.0.0-beta.12

All material CSS seems to be broken in my @angular/cli project. 

https://i.gyazo.com/e3f4d08756f53c0b218a11b61d5864ad.png

I've checked the release notes and I can't see any changes which are relevant to me. 

Is there some change I wasn't aware of?

**Comment by TomMettam** [comment]
Ah, I think I see.. 

#7241 compat: remove all md selectors, inputs, classnames, and exports 

I'll open a new ticket

**Comment by TomMettam** [comment]
Closing in favour of #7576

**Comment by dushkostanoeski** [comment]
There's a tool in the changelog that you can use to update, but you have to downgrade to beta11 first, and it doesn't work on the stepper, so you have to update that manualy
