### ISSUE TITLE
Examples still use md prefixes

### ISSUE THREAD

**Issue by TomMettam** [angular/material2#7576]
#7241 removed all md prefixes, however the documentation examples still have them:

e.g https://material.angular.io/components/button/examples

**Comment by klofi** [comment]
Same for the Getting started page https://material.angular.io/guide/getting-started

**Comment by andrewseguin** [comment]
The documentation site has not yet been updated with the latest guides and examples. The repo's `md` files have already been changed so the next push should resolve this.
