### ISSUE TITLE
Can't navigate in docs

### ISSUE THREAD

**Issue by zvory** [angular/material2#7582]
#### Bug, feature request, or proposal:
Can't select different tabs in docs (API, Examples, Components, Guides)
https://material.angular.io/components/button/overview

#### What is the expected behavior?
When I click one of the buttons that should let me navigate away from that page or do something, it should work

#### What is the current behavior?
It doesn't do anything besides very briefly change the URL

#### What are the steps to reproduce?
I open https://material.angular.io/components/button/overview and then I lick on "Examples" or "Api" or "Components".

#### What is the use-case or motivation for changing an existing behavior?
Existing behaviour is broken

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tried on macOS latest chrome and firefox developer edition. Also happens on my co-workers machine running macOS and chrome.

**Comment by shalugin** [comment]
It's seems like I did it five minutes later #7583

**Comment by kara** [comment]
Should be fixed now (may have to clear your cache)
