### ISSUE TITLE
More detailed explanation of some coding-standards

### ISSUE THREAD

**Issue by alexandermikuta** [angular/material2#7586]
proposal:

Some coding-standards should be explained more detailed for a better understanding, e.g.

In CODING_STANDARDS.md it says:

> "Component outermost elements are never flex (block or inline-block)".

If i have a component with e.g.
`<h1><h2><h3></h3></h2></h1>`
what is considered the outermost element?
h1 or is the host-element itself considered as outermost element?
in case of :host-element if h1 is a flex-element must the :host-element explicitly set to block or inline or is this the default behaviour?
In case of h1 is :host be allowed to use display: flex?

**Comment by jelbourn** [comment]
It refers to the host element of a component.
