### ISSUE TITLE
Select does not show placeholder text or underline

### ISSUE THREAD

**Issue by ottosson** [angular/material2#7587]
#### Bug:

Select does not show placeholder text or underline in beta.12.

#### What is the expected behavior?
Select should be more visible with underlined component and placeholder text

#### What are the steps to reproduce?
https://stackblitz.com/edit/material-project

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.4, Material 2.0.0-beta.12

**Comment by chris93007** [comment]
How was this solved?

**Comment by willshowell** [comment]
@chris93007 that happens if you forget to wrap it in `mat-form-field`

**Comment by ottosson** [comment]
This was never a bug. I was just too fast to report what was documented as a [breaking change](https://github.com/angular/material2/blob/master/CHANGELOG.md#highlights).

I had to wrap my select element in <mat-form-field>

**Comment by chris93007** [comment]
Ok, I suppose the documentation has to be updated, as this wasn't an issue before I updated.
