### ISSUE TITLE
mat-select do not accept [placeholder]="..."

### ISSUE THREAD

**Issue by MaickelHubner** [angular/material2#7590]
#### Bug, feature request, or proposal:
mat-select do not accept [placeholder]="..."

#### What is the expected behavior?
mat-select accept [placeholder]="..."

#### What is the current behavior?
Only fixed <mat-selct placeholder="..."> is accepted

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.4 Material 2.0.0-beta.12

**Comment by willshowell** [comment]
It seems to work fine here

https://stackblitz.com/edit/material2-beta12-3r3iwe?file=app/app.component.ts

**Comment by EvgeniKalenski** [comment]
@MaickelHubner , Had the same issue as you and wrapping mat-select in <mat-form-field>element solved my problem. @willshowell Is this wrapping is mandatory now for mat-select if I want to use placeholder?

**Comment by willshowell** [comment]
@EvgeniKalenski yeah, you should place all of your selects inside of form-fields now, just like `matInput`.

**Comment by MaickelHubner** [comment]
I needed to import the MatSelectModule and it worked again. Thanks
