### ISSUE TITLE
Suggestion: rename Mat_DIALOG_DATA to MAT_DIALOG_DATA

### ISSUE THREAD

**Issue by wawi0520** [angular/material2#7595]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
MAT_DIALOG_DATA is the correct name

#### What is the current behavior?
Mat_DIALOG_DATA ("at" should be capitalized)

#### What are the steps to reproduce?
No need to reproduce. This is only a variable name suggestion.

#### What is the use-case or motivation for changing an existing behavior?
All letter should be upper-case.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, Material 2.0.0-beta.11, Win 7, TypeScript 2.3.3

#### Is there anything else we should know?
No

**Comment by wawi0520** [comment]
Sorry, my bad. MAT_DIALOG_DATA is already there. Can anyone close issue? Very sorry for the inconvenience.

**Comment by willshowell** [comment]
You have the power to close it 💪
