### ISSUE TITLE
Can't export value MdDatepickerModule after updating to latest version (2.0.0-beta.12)

### ISSUE THREAD

**Issue by lainiwakurafan** [angular/material2#7596]
#### Bug, feature request, or proposal:
bug

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-s6drmq?embed=1&file=app/app.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular = 4.4.4
Material = 2.0.0-beta.12
OS = Windows 10
TypeScript = 2.3.4

#### Is there anything else we should know?
In "2.0.0-beta.11" it worked fine

**Comment by willshowell** [comment]
Please see the [CHANGELOG](https://github.com/angular/material2/blob/master/CHANGELOG.md) about the deprecation of the "md" prefix.

**Comment by lainiwakurafan** [comment]
@willshowell thanx

**Comment by un33k** [comment]
upgraded to beta.12
installed angular-material-prefix-updater
ran mat-switcher -p ./tsconfig.json

.... what have I missed ... 

Could not find updated prefix for identifier (MdDialog).

Make sure the following things are done correctly:
 • Angular Material is installed in the project (for type checking)
 • Project "tsconfig.json" configuration matches the desired files.
