### ISSUE TITLE
md-sidenav unit tests are flaky

### ISSUE THREAD

**Issue by sothychan** [angular/material2#76]
Chrome 48.0.2564 (Mac OS X 10.11.3) MdSidenav methods should be able to open and close FAILED
	Expected 'hidden' to equal 'visible'.

**Comment by jelbourn** [comment]
@hansl as we chatted about in person, it would be good to try faking the `transitionend` events and using `fakeAsync` to attempt to deflake.

**Comment by jelbourn** [comment]
@hansl closing this now since it seems to be fixed.
