### ISSUE TITLE
Buttons initialize very slowly since beta.12

### ISSUE THREAD

**Issue by Isigiel** [angular/material2#7600]
#### Bug, feature request, or proposal:
Since the beta.12 update it seems like mat-buttons take a long time to render.

#### What is the expected behavior?
Same speed or better as beta.11

#### What is the current behavior?
I have a paginated md-table with 50 rows and 3 buttons per row, since the last update switching pages takes significantly longer, it works fine if I remove the buttons.

#### What are the steps to reproduce?
Update to beta.12 and render many buttons at once

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.4.5
node: 8.2.1
os: darwin x64
@angular/animations: 4.4.4
@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.4.5
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/platform-server: 4.4.4
@angular/router: 4.4.4
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.5.3

**Comment by willshowell** [comment]
Does the same thing happen if you replace `<button mat-button>` with just `<button>`?

**Comment by Isigiel** [comment]
Yeah it seems to be significantly faster without `mat-button` @willshowell 
I measured performance and the frame after the click takes 1.23s with mat-buttons and 0.46s without

**Comment by doginthenight** [comment]
This could be related to issue https://github.com/angular/material2/issues/4221.
For me the violation did not occur with previous versions of Angular Material 2 but suddenly started with beta.12.

**Comment by jelbourn** [comment]
Might be related to touch-based ripples that have since been reverted

**Comment by Isigiel** [comment]
I will try once the next beta comes @jelbourn 
Assuming that's soon for ng5 as well ;)

**Comment by thw0rted** [comment]
I just filed #8838 which I think could be related?  It's a ripple issue as well.

**Comment by DevVersion** [comment]
Performance for ripples should be much better now. The ripples now use passive event listeners, which should improve the performance of the ripples at initialization and runtime.

Also we updated the ripples to no longer register events, if the ripples are disabled initially using `disableRipple` for example.

If you still see performance issues, please open a new issue or ping me here. Thanks
