### ISSUE TITLE
Could not find update prefix

### ISSUE THREAD

**Issue by guilhermejcgois** [angular/material2#7602]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
That the prefix for MdAutoCompleteModule, MdCheckboxModule, MdSelectModule, MdInputModule, MdDatePickerModule could be found.

#### What is the current behavior?
The prefix for MdAutoCompleteModule, MdCheckboxModule, MdSelectModule, MdInputModule, MdDatePickerModule could not be found.

#### What are the steps to reproduce?
Go inside a project that use the specified modules above, and then:
```
npm i -g angular-material-prefix-updater
mat-switcher -p <path/to/tsconfig/json>
```

#### What is the use-case or motivation for changing an existing behavior?
I don't want to update de prefix manually.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
@angular/cli: 1.4.5
node: 6.11.2
os: linux x64
@angular/animations: 4.4.4
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4@angular/forms: 4.4.4
@angular/http: 4.4.4@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4
```

#### Is there anything else we should know?
No, that's all.

**Comment by Stexxen** [comment]
This is expected, please see https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes

**Comment by josephperrott** [comment]
Closing as this is an issue with the prefix updater rather than the material library.

Instead your issue should be posted to: https://github.com/angular/material-prefix-updater

**Comment by guilhermejcgois** [comment]
Thanks @josephperrott , sorry for the trash post. Moved for [#15](https://github.com/angular/material-prefix-updater/issues/15).
