### ISSUE TITLE
Can't bind to 'formControl' since it isn't a known property of 'input' Angular4 

### ISSUE THREAD

**Issue by rijomonr** [angular/material2#7611]
#### Bug, feature request, or proposal:
As per the documentation I didn't get output from the given link https://material.angular.io/components/autocomplete/overview

Finally I got the solution one more API has to be add. "ReactiveFormsModule".

For this scenario, You can't mention one more API is required get the output. So please update the document ASAP

**Comment by Stexxen** [comment]
Probably best to raise that here - https://github.com/angular/material.angular.io

**Comment by julianobrasil** [comment]
I think the docs were built based on the fact that the develooer must have some  previous basic knowlegde on Angular before use Material.

**Comment by josephperrott** [comment]
Closing as it the developer is responsible for determining which forms module will need to be used.
