### ISSUE TITLE
Getting Started on material.angular.io is out of date with latest release

### ISSUE THREAD

**Issue by darkedges** [angular/material2#7621]
[https://material.angular.io/guide/getting-started](https://material.angular.io/guide/getting-started) is out of sync with [https://github.com/angular/material2/blob/master/guides/getting-started.md](https://github.com/angular/material2/blob/master/guides/getting-started.md) meaning those using the website will get errors like

```
ERROR in ........./src/app/material.module.ts (3,3): Module '"........./node_modules/@angular/material/material"' has no exported member 'MdButtonModule'.
```

as `npm install --save @angular/material @angular/cdk` will install ` "@angular/material": "^2.0.0-beta.12"`

All the examples are incorrect as well.

**Comment by Chan4077** [comment]
Do a <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>R</kbd> (or <kbd>Shift</kbd>+<kbd>Cmd</kbd>+<kbd>R</kbd> for Mac) to initiate a force-reload of the website.

**Comment by phortonssf** [comment]
What was the solution? When i try to serve it cannot find any of the components exported modules.

**Comment by Chan4077** [comment]
@phortonssf What's your error? Maybe try posting your problem as a separate issue.

**Comment by andrewseguin** [comment]
Be sure to do a hard refresh to clear your cache, seems our site is pretty aggressive with caching
