### ISSUE TITLE
Moment data adapter issue

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/material2#7624]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
No error

#### What is the current behavior?
If I have an input like this:

`              <mat-form-field style="width:100%;">
                <input matInput [matDatepicker]="pickerStart" placeholder="Start Date (DD/MM/YYYY)" formControlName="mom_start_date">
                <mat-datepicker-toggle matSuffix [for]="pickerStart"></mat-datepicker-toggle>
                <mat-datepicker #pickerStart startView="year"></mat-datepicker>
              </mat-form-field>`

and in the form:
`    this.createCompetitionForm = this.fb.group({
      $key: [this.editObject ? this.editObject['$key'] : '', Validators.required ],
      name: [this.editObject ? this.editObject['name'] : '', Validators.required ],
      mom_start_date: [this.editObject ? this.editObject['mom_start_date'] : moment(), [Validators.required, CustomValidators.isDate] ],
      mom_end_date: [this.editObject ? this.editObject['mom_end_date'] : moment().add(1, "years"), [Validators.required, CustomValidators.isDate] ],//.format("dd/MM/yyyy")
    });`

and in my module:
`  constructor(private dateAdapter: DateAdapter<Date>) {
    this.dateAdapter.setLocale('nl-BE');
  }`

The input is automatically filled with the current date. So far so good.
However, when deleting the text from the input:
![image](https://user-images.githubusercontent.com/1098243/31315297-c3ed33fc-ac15-11e7-9512-247fbb157093.png)

I have a validator to check if it is a valid date, but it does not seem to enter my validator code, it already fails before that.

Greetz

**Comment by mmalerba** [comment]
It seems to be working fine (though you didn't provide the code for your custom validator): http://plnkr.co/edit/vYYbskhl8Osg2ifl4sMg?p=preview
