### ISSUE TITLE
No event gets fired for mat-datepicker popup close (for the same day)

### ISSUE THREAD

**Issue by geelus** [angular/material2#7626]
#### Bug, feature request, or proposal:
There should be an event that is fired upon closing the datepicker popup. At the moment dateChanged event is getting fired anytime a date changes but not when the same date is selected.

#### What is the expected behavior?
I expect at least there is an event that gets fired upon closing the datepicker's popup for the same day.

#### What is the current behavior?
No events fired upon closing the datepicker's popup for the same day.

#### What is the use-case or motivation for changing an existing behavior?

This are important in many scenarios. For example, I'm developing a date-time-picker and I show the time picker upon closing the datepicker's popup. The problem happens when I want to select a different time on the same day which is already selected. I click on the date-picker, select the same day and the datepicker's popup gets closed but there is no way I get notified because the dateChanged only fired when it's not the same day.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
No

**Comment by willshowell** [comment]
Also on [r/Angular2](https://www.reddit.com/r/Angular2/comments/75vdir/a_simple_question_no_one_has_the_answer_for/).

cc @mmalerba

**Comment by mmalerba** [comment]
Sounds like a reasonable thing to add, `<mat-select>` has `onOpen` and `onClose` events, should probably use the same names here

**Comment by geelus** [comment]
@mmalerba it'll be perfect! Thanks.

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
