### ISSUE TITLE
API reference for Angular Material form-field incorrect (mat-form-field)

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular/material2#7629]
Hi,

I was implementing my form and I was looking at the docs (https://material.angular.io/components/form-field/api) and here the mention `mat-form-field` instead of `md-form-field`.
I think this might have been old version since I believe a the prefixes are `md` at the moment.

**Comment by mattiLeBlanc** [comment]
oops, It's actually the other way around...the prefix seems to have been updated to `mat`.  I just updated to Material `^2.0.0-beta.12`.
However, the rest of the documentation is still referring to `md` prefixes.
This is kind off a breaking change, isn't it???

**Comment by crisbeto** [comment]
The deprecation of the `md-` prefix was in [the release notes for beta.11](https://github.com/angular/material2/releases/tag/2.0.0-beta.11). There's also a tool to help you migrate to the `mat-` prefix. There shouldn't be any documentation left that refers to the `md-` prefix either.

**Comment by mattiLeBlanc** [comment]
<img width="807" alt="screen shot 2017-10-08 at 20 37 13" src="https://user-images.githubusercontent.com/5285035/31315661-840f037a-ac68-11e7-84c0-7acfd2698c28.png">

Mate, I see `md` prefixes everywhere in the docs.

**Comment by crisbeto** [comment]
I see what you mean. The docs were definitely updated (see https://github.com/angular/material2/blob/master/src/lib/input/input.md), but they might not have been redeployed.

**Comment by mattiLeBlanc** [comment]
pretty aggressive yep. I am having dev toolbar open with disable cache and still get the `md-prefix`. Only on the  `MatFormFieldModule` I see the `mat` prefix.
It will probably resolve itself soon.

**Comment by mattiLeBlanc** [comment]
@crisbeto I am still seeing references to `md-` prefix in for example this example `https://material.angular.io/components/toolbar/examples`. Check the HTML tab, and you will find `md's`.
