### ISSUE TITLE
 has no exported member 'MdToolbarModule'

### ISSUE THREAD

**Issue by phortonssf** [angular/material2#7642]
#### What is the current behavior?
Any component I try to import is not exported.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
npm start

#### Is there anything else we should know?
How do i format the package json so it doesnt look like poo?

`{
  "name": "stock-app",
  "version": "0.0.0",
  "license": "MIT",
   "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --port 8081 --public-host sayed-fall-2017-phortonssf.c9users.io",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.6",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.10",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.1",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
`

**Comment by benb7760** [comment]
the Md/md- prefix has been removed. See [changelogs](https://github.com/angular/material2/blob/master/CHANGELOG.md#deprecation-of-md-prefix)

**Comment by phortonssf** [comment]
import {MatToolbarModule} from '@angular/material'
and then selector is <mat-ToolBar> or no mat?

**Comment by andrewseguin** [comment]
Selector should be `mat-toolbar`, module is `MatToolbarModule`
