### ISSUE TITLE
Select AutoComplete option during form initialization 

### ISSUE THREAD

**Issue by joshvanal** [angular/material2#7643]
#### Bug, feature request, or proposal:
Feature

Because of the structure of the AutoComplete component, there becomes a need where during the initialization of a form, I want to be able to set the formControl with the same flow displayWith follows. 
For Example:
My object is structured as:
```
{
id:'56f267f6-8810-49e4-89db-0dc11a315bc8'
name:'Pennsylvania',
value:'PA'
}
```
And this is saved into the database as is or maybe foreign key relationship. During saving, in either case, it's easy. The problem comes to when editing that data in the same UI. The formControl is set to that object but the string displayed is "[object Object]". It would be nice to be able to send that object through the same flow as if selecting the value.

**Comment by willshowell** [comment]
Can you provide a reproduction? I am unable to duplicate it here:

https://stackblitz.com/edit/material2-beta12-mnj5fa?file=app%2Fapp.component.ts

**Comment by joshvanal** [comment]
Actually @willshowell, I must of been doing something wrong. 
It's working as expected. 

Thanks!
