### ISSUE TITLE
beta 10 prod build fails

### ISSUE THREAD

**Issue by mohitook** [angular/material2#7644]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
simply builds

#### What is the current behavior?
`ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/button/index.d.ts.MatButton_Host.html (2,1): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/button/index.d.ts.MatAnchor_Host.html (2,1): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/typings/button-toggle/index.ngfactory.ts (29,27): Property 'UNIQUE_SELECTION_DISPATCHER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/typings/button-toggle/index.ngfactory.ts (29,67): Property 'UNIQUE_SELECTION_DISPATCHER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/button-toggle/index.d.ts.MatButtonToggle_Host.html (2,1): Property 'UniqueSelectionDispatcher' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/button-toggle/index.d.ts.MatButtonToggle_Host.html (2,1): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/checkbox/index.d.ts.MatCheckbox_Host.html (2,1): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/datepicker/index.d.ts.MatCalendar.html (2,69): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/datepicker/index.d.ts.MatCalendar.html (2,345): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/datepicker/index.d.ts.MatCalendar.html (2,515): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/datepicker/index.d.ts.MatDatepickerToggle.html (2,1): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/typings/expansion/index.ngfactory.ts (24,27): Property 'UNIQUE_SELECTION_DISPATCHER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/typings/expansion/index.ngfactory.ts (24,67): Property 'UNIQUE_SELECTION_DISPATCHER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/expansion/index.d.ts.MatExpansionPanel_Host.html (2,1): Property 'UniqueSelectionDispatcher' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/expansion/index.d.ts.MatExpansionPanelHeader_Host.html (2,1): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/typings/paginator/index.ngfactory.ts (52,45): Property 'ARIA_DESCRIBER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/typings/paginator/index.ngfactory.ts (52,72): Property 'ARIA_DESCRIBER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/paginator/index.d.ts.MatPaginator.html (2,652): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/paginator/index.d.ts.MatPaginator.html (2,652): Property 'AriaDescriber' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/paginator/index.d.ts.MatPaginator.html (2,956): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/paginator/index.d.ts.MatPaginator.html (2,956): Property 'AriaDescriber' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/typings/radio/index.ngfactory.ts (30,27): Property 'UNIQUE_SELECTION_DISPATCHER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/typings/radio/index.ngfactory.ts (30,67): Property 'UNIQUE_SELECTION_DISPATCHER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/radio/index.d.ts.MatRadioButton_Host.html (2,1): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/radio/index.d.ts.MatRadioButton_Host.html (2,1): Property 'UniqueSelectionDispatcher' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/slider/index.d.ts.MatSlider_Host.html (2,1): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/typings/slide-toggle/index.d.ts.MatSlideToggle_Host.html (2,1): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/typings/tooltip/index.ngfactory.ts (41,18): Property 'ARIA_DESCRIBER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/typings/tooltip/index.ngfactory.ts (41,45): Property 'ARIA_DESCRIBER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/button/typings/index.d.ts.MatButton_Host.html (2,1): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in ng:/D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/button/typings/index.d.ts.MatAnchor_Host.html (2,1): Property 'FocusMonitor' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/tooltip/typings/index.ngfactory.ts (41,18): Property 'ARIA_DESCRIBER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/src/$$_gendir/node_modules/@angular/material/tooltip/typings/index.ngfactory.ts (41,45): Property 'ARIA_DESCRIBER_PROVIDER' does not exist on type 'typeof "D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/button/typings/button.d.ts (11,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"' has no exported member 'FocusMonitor'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/button-toggle/typings/button-toggle.d.ts (11,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"' has no exported member 'FocusMonitor'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/button-toggle/typings/button-toggle.d.ts (12,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"' has no exported member 'UniqueSelectionDispatcher'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/checkbox/typings/checkbox.d.ts (4,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"' has no exported member 'FocusMonitor'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/expansion/typings/accordion-item.d.ts (9,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"' has no exported member 'UniqueSelectionDispatcher'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/expansion/typings/expansion-panel.d.ts (2,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"' has no exported member 'UniqueSelectionDispatcher'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/expansion/typings/expansion-panel-header.d.ts (1,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"' has no exported member 'FocusMonitor'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/tooltip/typings/tooltip.d.ts (9,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"' has no exported member 'AriaDescriber'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/radio/typings/radio.d.ts (11,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/collections"' has no exported member 'UniqueSelectionDispatcher'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/radio/typings/radio.d.ts (12,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"' has no exported member 'FocusMonitor'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/slider/typings/slider.d.ts (12,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"' has no exported member 'FocusMonitor'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/slide-toggle/typings/slide-toggle.d.ts (12,10): Module '"D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/cdk/a11y"' has no exported member 'FocusMonitor'.
ERROR in D:/BME VIK MSC/Dipterv02/diplomamunka/node_modules/@angular/material/table/typings/row.d.ts (18,43): Type 'CdkRowDef' is not generic.`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.0
Typescript: 2.5.2
OS: win10
cdk: 2.0.0-beta.10
material: 2.0.0-beta.10
#### Is there anything else we should know?

ng build --prod has worked a few days ago, but now it simply fails. I don't know what is the problem now, because I didn't update anything related to this framework (only the global angular cli is higher, but because I use the local (1.3.2) to build it shouldn't effect anything..
Additional info: as I know beta.11 and 12 needs higher versions of angular, but I can't upgrade it because of other dependencies... so the question is: what happened till the last prod build which makes those errors?
as I see you've made some changes in beta.11 with e.g.  FocusMonitor... but how could it effect my project which was not updated??
(I had an other issue about changed input placeholder behaviour... really strange.. so even If I not upgrade my dependencies anything can go simply wrong by itself??? how does it work?)

**Comment by andrewseguin** [comment]
Can you verify that you are on beta.10 for both the cdk and material? Can you post your `package.json`

**Comment by mohitook** [comment]
yes, this is my package.json: (I know the versions can be higher but I've checked them with npm list *** so they are on beta.10)

`"@angular/animations": "^4.4.0-RC.0",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/common": "^4.4.0-RC.0",
    "@angular/compiler": "^4.4.0-RC.0",
    "@angular/compiler-cli": "^4.4.0-RC.0",
    "@angular/core": "^4.4.0-RC.0",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "^4.4.0-RC.0",
    "@angular/http": "^4.4.0-RC.0",
    "@angular/material": "^2.0.0-beta.10",
    "@angular/platform-browser": "^4.4.0-RC.0",
    "@angular/platform-browser-dynamic": "^4.4.0-RC.0",
    "@angular/platform-server": "^4.4.0-RC.0",
    "@angular/router": "^4.4.0-RC.0",
    "angular-froala-wysiwyg": "^2.7.0",
    "angular2-infinite-scroll": "^0.3.4",
    "angular2-masonry": "^0.4.0",
    "angular2-moment": "^1.7.0",
    "angular2-tinymce": "^2.1.2",
    "angularfire2": "^2.0.0-beta.8",
    "core-js": "^2.4.1",
    "firebase": "^3.8.0",
    "firebase-functions": "^0.6.3",
    "hammerjs": "^2.0.8",
    "imagesloaded": "^4.1.3",
    "ng-select": "^1.0.0-beta.5",
    "ng2-filter-pipe": "^0.1.7",
    "ng2-tag-input": "^1.2.2",
    "ngx-modal": "0.0.29",
    "ngx-pagination": "^3.0.0",
    "ngx-sharebuttons": "^3.0.0",
    "rxjs": "^5.0.1",
    "tinymce": "^4.5.5",
    "ts-helpers": "^1.1.1",
    "typescript": "^2.5.2",
    "zone.js": "^0.7.2"`

devdependencies:
`"@angular/cli": "^1.3.2",
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"`

**Comment by willshowell** [comment]
@mohitook try pinning your material/cdk dependencies

```diff
- "@angular/material": "^2.0.0-beta.10"
+ "@angular/material": "2.0.0-beta.10"
```

**Comment by mohitook** [comment]
@willshowell it doesnt work. I have tried but as I said the currently installed version is beta.10. It world be nice if you could help... I van build my prod app with --aot=false option but it makes my application a lot slower...

**Comment by donboli** [comment]
try `yarn upgrade @angular/material @angular/cdk`

**Comment by mohitook** [comment]
@donboli as I know after beta.10, (so in beta.11 and beta.12) it needs newer version of angular.. but unfortunately I can't go higher with the main framework because of it's dependencies... (like a dll hell of the javascipt world) 
*btw I will try it on a project copy and comment if it work.

**Comment by jelbourn** [comment]
Closing since this seems obsolete now
