### ISSUE TITLE
mat-paginator problem with attributes

### ISSUE THREAD

**Issue by Leila-karimi** [angular/material2#7648]
#### Bug, feature request, or proposal:
This is the error I get after I upgraded to the latest version beta 12:
length, pageIndex, pageSize and pageSizeOptions  are not known attributes of mat-paginator
```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'pageIndex' since it isn't a known property of 'mat-paginator'.
1. If 'mat-paginator' is an Angular component and it has 'pageIndex' input, then verify that it is part of this module.
```

It was working in beta10 and now after the upgrade this is broken. Can anyone help please?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    "@angular/animations": "^4.3.6",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.3.6",
    "@angular/compiler": "^4.3.6",
    "@angular/core": "^4.3.6",
    "@angular/forms": "^4.3.6",
    "@angular/http": "^4.3.6",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.3.6",
    "@angular/platform-browser-dynamic": "^4.3.6",
    "@angular/platform-server": "^4.3.6",
    "@angular/router": "^4.3.6",

#### Is there anything else we should know?
here is my code:
   `<mat-paginator #paginator
  [length]="length"
  [pageIndex]="0"
  [pageSize]="10"
  [pageSizeOptions]="[5, 10, 25, 100]"></mat-paginator>`

**Comment by profimedica** [comment]
import { MatTableModule } from '@angular/material/table';
import { MatPaginatorModule } from '@angular/material';
@NgModule({
  imports: [
    ...
    MatTableModule,
    MatPaginatorModule
  ],
  ...
})

**Comment by leoncc** [comment]
Thank you @profimedica

**Comment by Venkatuidevloper** [comment]
#Cumpanasu Florin  --- Thank you for saving my time

**Comment by prachi2274** [comment]
Thanku @profimedica
