### ISSUE TITLE
make demo app online available for the public

### ISSUE THREAD

**Issue by maku** [angular/material2#7650]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
The demo app (src/demo-app) should be available online for the public (e.g. accessible via https://material.angular.io)

#### What is the current behavior?
You have to checkout the material2 project and build it by yourself (npm run demo-app). But this does not work with windows OS (at least for me)

**Comment by Chan4077** [comment]
Duplicate of #7077.

**Comment by jelbourn** [comment]
Duplicate of #7077.
