### ISSUE TITLE
Cannot transpile with ng build --prod

### ISSUE THREAD

**Issue by o4oren** [angular/material2#7651]
#### Bug, feature request, or proposal:

Unable to transplie projects with --prod using angular-cli.

#### What are the steps to reproduce?
When running ng build --prod on a project that includes material angular beta 2.00 12, the following errors result.
Building without --prod works.

ERROR in ng:///C:/Users/ogeva/IdeaProjects/ahem-server/node_modules/@angular/material/progress-spinner/typings/index.d.ts.MatProgressSpinner_Host.htm
l (2,1): Property 'DOCUMENT' does not exist on type 'typeof "C:/Users/ogeva/IdeaProjects/ahem-server/node_modules/@angular/common/common"'.

ERROR in ng:///C:/Users/ogeva/IdeaProjects/ahem-server/node_modules/@angular/material/progress-spinner/typings/index.d.ts.MatSpinner_Host.html (2,1):
 Property 'DOCUMENT' does not exist on type 'typeof "C:/Users/ogeva/IdeaProjects/ahem-server/node_modules/@angular/common/common"'.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Windows 10 / Red hat 6.8. ts 6.
ts 2.5.2.
angular 4.4.4.

**Comment by tgmendes** [comment]
+1

**Comment by tgmendes** [comment]
Solved the problem: replace Md prefix with Mat. See the [changelogs](https://github.com/angular/material2/blob/master/CHANGELOG.md#deprecation-of-md-prefix)

**Comment by o4oren** [comment]
Ok, you're right. For some reason mine didn't update to build 12 for real, I still had 11 in node_modules.
