### ISSUE TITLE
MatGridListModule is not working

### ISSUE THREAD

**Issue by albrave** [angular/material2#7652]
#### Bug, feature request, or proposal:

MatGridListModule is not working on the latest release 2.0.0-beta.12, while is working on 2.0.0-beta.11

#### What is the expected behavior?

When you call the "md-grid-list" tag in the view it should create a grid with the "md-grid-tile" boxes.

#### What is the current behavior?

The module is correctly injected (there's no error in typescript), but when you call the <md-grid-list> tag in the view nothing happen

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

2.0.0-beta.12

#### Is there anything else we should know?

It's working on the 2.0.0-beta.11

**Comment by donroyco** [comment]
Make sure you have replace `md-grid-list` with `mat-grid-list`. As part of [beta.12](https://github.com/angular/material2/blob/master/CHANGELOG.md), **all** the `md-` prefixes have been removed.

```
<mat-grid-list cols="4" rowHeight="100px">
  <mat-grid-tile
      *ngFor="let tile of tiles"
      [colspan]="tile.cols"
      [rowspan]="tile.rows"
      [style.background]="tile.color">
    {{tile.text}}
  </mat-grid-tile>
</mat-grid-list>
```

See [this StackBlitz](https://angular-epxtx6.stackblitz.io) to have a working example.

**Comment by jotatoledo** [comment]
Make sure to read the changelog and specially the breaking changes before creating an issue

**Comment by albrave** [comment]
Sorry, my fault. Thanks
