### ISSUE TITLE
Can't set height and Width of spinner since beta.12

### ISSUE THREAD

**Issue by argoo83** [angular/material2#7653]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Set width and height

#### What is the current behavior?
`<mat-spinner style="width:40px; height: 40px" color="primary">
      </mat-spinner>`
has no effect since upgrade to beta.12

**Comment by argoo83** [comment]
`mat-spinner.small-spinner svg {
    width: 40px !important;
    height: 40px !important;
}`

Used this css to solve this.

**Comment by karlos1337** [comment]
I try to set the container widht/height, the mat-spinner widht/height and the svg width/height, did not work. It works in previous versions only setting mat-spinner (md-spinner) widht/height.

https://stackblitz.com/edit/material2-spinner-issue?file=app%2Fapp.component.scss

**Comment by ghd8** [comment]
You can use the input parameter "diameter". (beta.12)

` <mat-spinner [diameter]="40"></mat-spinner>`

**Comment by nicktobolski** [comment]
What if one is looking for something more responsive? Is there anyway to quickly set it to behave as it did before (where it would automatically adjust to the parent container)?

**Comment by willshowell** [comment]
@nicktobolski you are probably limited to using `!important`

https://stackblitz.com/edit/material2-spinner-issue-vzdj9y?file=app/app.component.scss

**Comment by RobertDiPaolo** [comment]
I've just run into this as well after upgrading to beta12. IMHO the old behaviour was much better, I prefer to size components via CSS rather than input values. Seems a bit hacky to have to use `!important`.

**Comment by e-cloud** [comment]
@ghd8 's answer is the official way.

**Comment by mawo87** [comment]
Unfortunately setting the diameter doesn't solve the problem as the border won't change. For example, if you set the diameter to 16, the border thickness won't adapt and the spinner looks weird.

**Comment by karlos1337** [comment]
@mawo87 Can define the stroke width with `[strokeWidth]` input parameter https://material.angular.io/components/progress-spinner/api

**Comment by mawo87** [comment]
@karlos1337 Thanks for help - I somehow overlookd this.

**Comment by dgadelha** [comment]
@ghd8 `diameter` seems to add some padding or w.e.: https://plnkr.co/edit/9LVEpXy8XJAAWjYtVOBh?p=preview

**Comment by ghd8** [comment]
@dgadelha 

`<mat-spinner [diameter]="48"></mat-spinner>`
instead of
`<mat-spinner diameter="48"></mat-spinner>`

**Comment by dgadelha** [comment]
My bad, thank you!

**Comment by stevenphaedonos** [comment]
If you set a low [diameter] attribute (e.g. 20) you may end up with an undesirable progress-spinner, such as the one below. This can be resolved by also configuring the [strokeWidth] attribute to a low number (e.g. 2). 
![spinner](https://user-images.githubusercontent.com/12955616/32162226-4ff08f28-bdac-11e7-9c4f-253450180f96.gif)

**Comment by josephperrott** [comment]
Closing as the height is controlled via `diameter`

**Comment by MikaAK** [comment]
I'm still having this as an issues @josephperrott, I'm setting diameter and the px is still way to big. it ends up being a small circle for the spinner with a 100px width on `mat-progress-spinner` and `svg` even though the diameter is `20` and the circle is probably only 30px big

**Comment by darkedges** [comment]
Seems to be 10x on chrome.
[https://stackblitz.com/edit/angular-material-progress-spinner](https://stackblitz.com/edit/angular-material-progress-spinner)

**Comment by willshowell** [comment]
@darkedges you need to bind to diameter with value binding, not string binding.

Coercion will be supported in https://github.com/angular/material2/pull/7791.

**Comment by darkedges** [comment]
@willshowell now I understand. Changed to
```
<mat-progress-spinner value="100" mode="determinate" [diameter]="68"></mat-progress-spinner>
<button mat-fab color="accent">
  <mat-icon class="icon">mic</mat-icon>
</button>
```
and the diameter value is being obeyed.

**Comment by chuihinwai** [comment]
While `diameter` and `strokeWidth` works, I cannot find a way to set them globally. This was possible when CSS was respected, it there a workaround apart from using `!important`?

**Comment by mightypenguin** [comment]
I think the only issue left is that this isn't documented in the demo page for the spinner.

**Comment by eldhoabe** [comment]
Is this issue fixed. I still experience the same issue as suggested by @stevenphaedonos        

`<mat-progress-spinner  mode="indeterminate" [diameter]="28"></mat-progress-spinner>`

**Comment by hamidafghan** [comment]
Try to use diameter option.
70 is 70px size
<mat-spinner [diameter]="70"></mat-spinner>
