### ISSUE TITLE
Progress spinner is not animating in IE11

### ISSUE THREAD

**Issue by akrepon** [angular/material2#7654]
#### Bug
The progress spinner is not animating in IE11.

#### What is the expected behavior?
Progress spinner should animate properly in all browsers.

#### What is the current behavior?
Progress spinner is not animating.

#### What are the steps to reproduce?
Visit https://material.angular.io/components/progress-spinner/overview in IE11.

#### What is the use-case or motivation for changing an existing behavior?
Bad user experience.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.4
Material 2.0.0-beta.12
IE11
Windows 7

**Comment by shalugin** [comment]
Duplicate #7580

**Comment by crisbeto** [comment]
Closing as a duplicate.
