### ISSUE TITLE
md-sidenav content is not accessible when browser's size is reduced

### ISSUE THREAD

**Issue by lokeshdaiya** [angular/material2#7655]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-sidenav content should be accessible when browser size is resized.

#### What is the current behavior?
when browser is resized it does not show the content 

#### What are the steps to reproduce?
https://plnkr.co/edit/nSGrAiVAAoxZZ19Mxp8J?p=preview

1.  Open the example shared in plnkr in full screen mode. 
2. scroll to extreme down so thay you can see sidenav!29
3. Now resize the browser 1044 x 567
4. you well notice that scroll touched to extreme bottom and you can't see items below sidenav!20 until again you click on the scroll.
![1](https://user-images.githubusercontent.com/7831299/31334581-8586d2b0-ad0c-11e7-9b60-7587efe332bf.PNG)
![2](https://user-images.githubusercontent.com/7831299/31334580-8561e4f0-ad0c-11e7-9769-4ce263532508.PNG)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material beta8 to beta11

#### Is there anything else we should know?

Same is reproducible at https://material.angular.io/components

**Comment by mmalerba** [comment]
documentation update in https://github.com/angular/material2/pull/7775 includes an example demonstrating how to do a responsive sidenav. https://material.angular.io has also been updated with a responsive sidenav
