### ISSUE TITLE
Moment dateadapter returns the moment object as value

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/material2#7656]
#### Bug, feature request, or proposal:
Bug/proposal.
It depends if this is actually the desired behaviour.

#### What is the expected behavior?
I would think that if I get the value from a form & (moment)datefield this.createRightForm.value.validUntil, I would get the internal date value.

#### What is the current behavior?
What I actually get is the moment object.
Because of this I cannot just store the this.createRightForm (to firebase). I have to manually convert the values to java dates to store them (=the internal number representation)
+ when retrieving these dates from the database (firebase) I have to reconvert to moment dates.

Not an elegant solution.

Any ideas? Is this a 'bug' or do I overlook something?

**Comment by mmalerba** [comment]
This is working as intended the `MomentDateAdapter` works with `Moment` objects and the `NativeDateAdapter` works with `Date` objects. It is expected that the user will convert them if they need to be stored in a database (or create their own `DateAdapter` that works directly with the type they want)
