### ISSUE TITLE
mat-tab-group Double click to change tab

### ISSUE THREAD

**Issue by xban1x** [angular/material2#7657]
#### Bug, feature request, or proposal:

Bug. I have an issue where when i go to my page with tabs from root Route it works as it should. But when i load the sub route directly the tab gains strange behavior by first not setting first tab as selected and also i have to double click on tabs to switch them.

#### What is the expected behavior?

To be able to switch tabs using 1 click.

#### What is the current behavior?

It requires 2 clicks to switch tabs.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

I cannot re-produce a plunker as i have no idea where the issue arrises from.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Was the same in beta.9 to - 12

#### Is there anything else we should know?

Does not appear on local machine only in production build.

**Comment by perozdrero** [comment]
I had similar issues and found at then that issued was zone and change detection. My subroute data did not come from in standard way (did not trigger change detection - it was outside zone), so zone did not trigger change detection, and second click caused to run change detection and draw changes. Could you try to wrap your data getting code in:

     this.zone.run(() => {
        ...
      });

where zone in injected ngZone instance.
This helped me.
Regards!

**Comment by xban1x** [comment]
@perozdrero thanks for this. Sorry for late reply but yes this solution worked. :)

**Comment by perozdrero** [comment]
Glad to help. Off the record: Greetings for EuroBakset gold!
