### ISSUE TITLE
Incorrect Import Statement on Snackbar Docs

### ISSUE THREAD

**Issue by mambroz27** [angular/material2#7658]
#### Bug, feature request, or proposal:
Bug (Documentation)

#### What is the expected behavior?
The import statement should be `import {MdSnackBarModule} from '@angular/material';`

#### What is the current behavior?
The docs currently have `import {MatSnackBarModule} from '@angular/material';` as the import statement example for the Snackbar component.

#### What are the steps to reproduce?
Visit the [Snackbar docs page](https://material.angular.io/components/snack-bar/api)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.12 docs

**Comment by josephperrott** [comment]
Closing as this is documentation as expected, as of `beta.12` the `md` prefix has been removed.
