### ISSUE TITLE
when used <div> {{ (af.auth| async).uid }}</div> " from angularfire 2 " the sidenav blocked " 

### ISSUE THREAD

**Issue by samirthebti** [angular/material2#766]
when used <div> {{ (af.auth| async).uid }}</div> " from angularfire 2 " the sidenav blocked " 
-----------------------------------------------------------------
Cannot read property 'uid' of null

browser_adapter.ts:78 TypeError: Cannot read property 'uid' of null
    at DebugAppView._View_LoginWebAppComponent0.detectChangesInternal (LoginWebAppComponent.template.js:529)
    at DebugAppView.AppView.detectChanges (view.ts:243)
    at DebugAppView.detectChanges (view.ts:345)
    at DebugAppView.AppView.detectViewChildrenChanges (view.ts:267)
    at DebugAppView.AppView.detectChangesInternal (view.ts:256)
    at DebugAppView.AppView.detectChanges (view.ts:243)
    at DebugAppView.detectChanges (view.ts:345)
    at DebugAppView.AppView.detectContentChildrenChanges (view.ts:261)
    at DebugAppView._View_EveyWebAppComponent0.detectChangesInternal (EveyWebAppComponent.template.js:571)
    at DebugAppView.AppView.detectChanges (view.ts:243)BrowserDomAdapter.logError @ browser_adapter.ts:78
browser_adapter.ts:78 ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.ts:78

ViewWrappedException
_context
:
DebugContext
_originalException
:
TypeError: Cannot read property 'uid' of null at DebugAppView._View_LoginWebAppComponent0.detectChangesInternal (LoginWebAppComponent.template.js:529:115) at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:200:14) at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:289:44) at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:220:34) at DebugAppView.AppView.detectChangesInternal (http://localhost:4200/vendor/@angular/core/src/linker/view.js:211:14) at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:200:14) at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:289:44) at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:215:37) at DebugAppView._View_EveyWebAppComponent0.detectChangesInternal (EveyWebAppComponent.template.js:571:8) at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:200:14)
_originalStack
:
"TypeError: Cannot read property 'uid' of null↵    at DebugAppView._View_LoginWebAppComponent0.detectChangesInternal (LoginWebAppComponent.template.js:529:115)↵    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:200:14)↵    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:289:44)↵    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:220:34)↵    at DebugAppView.AppView.detectChangesInternal (http://localhost:4200/vendor/@angular/core/src/linker/view.js:211:14)↵    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:200:14)↵    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:289:44)↵    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:215:37)↵    at DebugAppView._View_EveyWebAppComponent0.detectChangesInternal (EveyWebAppComponent.template.js:571:8)↵    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:200:14)"
_wrapperMessage
:
"Error in http://localhost:4200/app/authentification/login.html:32:15"
_wrapperStack
:
"Error: Error in http://localhost:4200/app/authentification/login.html:32:15↵    at ViewWrappedException.WrappedException [as constructor] (http://localhost:4200/vendor/@angular/core/src/facade/exceptions.js:34:31)↵    at new ViewWrappedException (http://localhost:4200/vendor/@angular/core/src/linker/exceptions.js:59:16)↵    at DebugAppView._rethrowWithContext (http://localhost:4200/vendor/@angular/core/src/linker/view.js:306:23)↵    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:292:18)↵    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:220:34)↵    at DebugAppView.AppView.detectChangesInternal (http://localhost:4200/vendor/@angular/core/src/linker/view.js:211:14)↵    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:200:14)↵    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:289:44)↵    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:215:37)↵    at DebugAppView._View_EveyWebAppComponent0.detectChangesInternal (EveyWebAppComponent.template.js:571:8)"
context
:
(...)
message
:
(...)
originalException
:
(...)
....

**Comment by jelbourn** [comment]
Your issue is not clear at all; as far as I can tell, it has nothing to do with Angular Material. Please follow the issue template for future issues, thanks!
