### ISSUE TITLE
matInput don`t float placeholder

### ISSUE THREAD

**Issue by PavlezT** [angular/material2#7661]
#### Bug, feature request, or proposal:
any element that supports 'matInput' have problem with placeholder.
#### What is the expected behavior?
placeholder should float to top when input is focused
#### What is the current behavior?
placeholder stands on his previous position and overlaps with text in input

![Image of Yaktocat]
(https://image.ibb.co/iHs3MG/2017_10_09_19_12_51.png)

#### What are the steps to reproduce?
Insert this html code into page:
```html
<form #editTaskForm="ngForm">
        <mat-form-field>
            <input matInput type="text" placeholder="Название" [(ngModel)]="model.Title" name="Title" #Title="ngModel" required [disabled]="userRole == 'assignedTo'">
        </mat-form-field>
        <mat-form-field class="example-full-width">
            <textarea matInput rows="5" placeholder="Описание" [(ngModel)]="model.Description" name="Description" #Description="ngModel" [disabled]="userRole == 'assignedTo'"></textarea>
        </mat-form-field>
</form> 
```

#### What is the use-case or motivation for changing an existing behavior?
It is very important, because it destroys all design in forms!
It is annoyin, when you are updating to upper version and something simple fails!
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"dependencies": {
    "@angular/animations": "^4.4.2",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.4.2",
    "@angular/compiler": "^4.4.2",
    "@angular/core": "^4.4.2",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.2",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.4.2",
    "@angular/platform-browser-dynamic": "^4.4.2",
    "@angular/router": "^4.4.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.1",
    "intl": "^1.2.5",
    "ng2-dragula": "^1.5.0",
    "rxjs": "^5.4.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.2",
    "@angular/compiler-cli": "^4.4.2",
    "@angular/language-service": "^4.4.2",
    "@types/jasmine": "~2.6.0",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^8.0.28",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.3.0",
    "tslint": "~5.7.0",
    "typescript": "~2.5.2"
  }

**Comment by willshowell** [comment]
Can you please provide a reproduction? There appears to be no issue by copy-pasting your example

https://stackblitz.com/edit/material2-beta12-woutvu?file=app/app.component.ts

**Comment by PavlezT** [comment]
I thought problems was with some angular modules, but really problem was with pre-build css file, that wasn't updated.

**Comment by andrewsxx** [comment]
Hi @PavlezT, I have the same problem right now... how could you solve it?

**Comment by PavlezT** [comment]
> I thought problems was with some angular modules, but really problem was with pre-build css file, that wasn't updated.

I have wrote about it. The problem was with per-build css styles. They have versions too, same as your module version.

**Comment by mark-langer** [comment]
So in case anyone is wondering about how to solve this issue: Obviously the update to material's beta12 changed some of the HTML structure of certain material components. You have to re-compile your Material Theming SCSS file to get the latest styles for the new HTML structure.

That SCSS file is called something like `material-theming.scss`. Just move into that file, add a space somewhere and hit save again if you use an automatic sass compiler.

**Comment by jsitu** [comment]
@mark-langer I am sorry how can I fix it specifically?

**Comment by mark-langer** [comment]
@jsitu Basically re-compiling the SCSS file will fix the floating placeholder. Just open the scss file you use for material's theming capabilities, add a space to the end and save it. That should trigger the compile process that outputs a CSS file.
The SCSS file imports a lot of lines from the @angular/material package, which changed with the update. Therefore you need to re-compile the importing SCSS file.

**Comment by thienedits** [comment]
doesnt seem to be working. Im on 7.3.0 and its still floating placeholder
