### ISSUE TITLE
md-tab' is a Web Component

### ISSUE THREAD

**Issue by Sevensnake** [angular/material2#7662]
#### Bug, feature request, or proposal:
 If 'md-tab' is an Angular component and it has 'disabled' input, then verify that it is part of this module.
2. If 'md-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("-->
Upgraded to Angularcli 4.4
nodejs version 
`  "dependencies": {
    "@angular/animations": "^4.4.4",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/material": "github:angular/material2-builds",
    "@angular/platform-browser": "^4.4.4",
    "@angular/platform-browser-dynamic": "^4.4.4",
    "@angular/router": "^4.4.4",
    "@angular2-material/core": "^2.0.0-alpha.8-3",
    "@angular2-material/input": "^2.0.0-alpha.8-3",
       "angular-2-local-storage": "^1.0.1",
    "angular-material-source": "github:angular/material",
    "angular2-busy": "^2.0.4",
    "angular2-datatable": "^0.6.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "ember-cli-cors": "^0.0.2",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "http-server": "^0.10.0",
    "lodash": "^4.17.4",
    "material-design-lite": "^1.3.0",
    "mdn-polyfills": "^3.6.0",
    "moment": "^2.18.1",
    "ng2-ckeditor": "^1.1.9",
    "ng2-mask": "^1.0.5",
    "ng2-page-transition": "^1.1.0",
    "ng2-toastr": "^4.1.2",
    "ngx-bootstrap": "^1.8.1",
    "ngx-cookie": "^1.0.0",
    "ngx-pipes": "^1.5.10",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.5",
    "@angular/compiler-cli": "^4.4.4",
    "@angular/language-service": "^4.4.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "2.4.0"
  }
}`
my app.module.ts
import {   MatSelectModule,MatTabsModule,MatRadioModule,  MatInputModule,MatProgressSpinnerModule, MatTabGroup } from '@angular/material';

**Comment by donroyco** [comment]
Please use the [issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md). `md-tab` is deprecated in favour of `mat-tab`, see the [changelog](https://github.com/angular/material2/blob/master/CHANGELOG.md#deprecation-of-md-prefix).

**Comment by josephperrott** [comment]
Closing as `md-tab` was removed as of `beta.12`.  You will need to use `mat-` prefix instead.

**Comment by Sevensnake** [comment]
does that goes for mdDatepicker which is not MatDatepicker?
