### ISSUE TITLE
bug(dialog): Some wrong distances and values

### ISSUE THREAD

**Issue by TheRedD0t** [angular/material2#7663]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The implementation of the dialog has some wrong values vs. the official guidelines.

#### What is the current behavior?
* The line height of the title has the correct `margin-bottom`(20) but the` line-height`(32) adds additional but wrong pixels.
* The right and left `padding` of the buttons should be 8 not 16.
* The `min-width` is set to 88 but should be 64 instead.
* The `mat-dialog-actions` container should has something like `margin-right: -16px`, because the guidelines specifies a `margin` of 8 from the right for the actions(, but still the standard of 24 from the left for left aligned buttons).
* Furthermore, the `mat-dialog-actions` container should has a top and bottom `padding` of 8 not 16, to match the 52 (...currently 60...) of the specs.

#### What are the steps to reproduce?
Just compare the specs of the [official MD guidelines](https://material.io/guidelines/components/dialogs.html#dialogs-specs) with the values of the [example from the documentation](https://material.angular.io/components/dialog/examples).

#### What is the use-case or motivation for changing an existing behavior?
To be in line with the MD guidelines, as it is one of the goals of this framework.

#### Is there anything else we should know?
This issue is an enhancement of #2735.

**Comment by josephperrott** [comment]
Closing as this issue is out of date with the updates to both the styling of `MatDialog` and the Material Spec.

**Comment by rmedaer** [comment]
@josephperrott you said:

> both the styling of MatDialog and the Material Spec.

IMO we should follow the guidelines and it's still not the case (according to the tests I made).
On my side, the question is not closed: **what should I do** ?

Many thanks,
