### ISSUE TITLE
CSS not working for Radio or dropdown.

### ISSUE THREAD

**Issue by Sevensnake** [angular/material2#7669]
The input and the tab css is working but for some reason i just see Yes and no and thats it. 
`      <mat-radio-group [(ngModel)]="Filing" name="radiorF">
                                <mat-option class="example-margin" [value]="true">Yes</mat-option>
                                <mat-option class="example-margin" [value]="false">No</mat-option>
                            </mat-radio-group>`

**Comment by crisbeto** [comment]
You're supposed to use `mat-radio-button` instead of `mat-option`.  [See the radio docs.](https://material.angular.io/components/radio/examples)
