### ISSUE TITLE
mat-select and mat-input styles still don't line up

### ISSUE THREAD

**Issue by bradleybeighton** [angular/material2#7670]
#### Bug, feature request, or proposal:
Putting a mat-select next to a mat-input require a css override.

#### What is the expected behavior?
They should line up correctly. 

#### What is the current behavior?
They do not line up correctly. 

#### What are the steps to reproduce?
An override that I have found to work.
`
mat-select {
   display: unset;
}
`

#### What is the use-case or motivation for changing an existing behavior?
Select's and inputs are often used together in a form. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.4 and material 2.0.0-beta.12.

This affects all browsers.

#### Is there anything else we should know?
I have moved the select inside the mat-form-field container and the styles still don't match the input styles.

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/7627 selected, or empty style?

**Comment by bradleybeighton** [comment]
Both as far as I'm aware.

**Comment by mmalerba** [comment]
I am not able to reproduce this, can you provide a plunker or stackblitz demonstrating the issue?

**Comment by mmalerba** [comment]
Here's a demo of them aligned: https://stackblitz.com/edit/angular-material2-issue-8fotzh?file=app/app.component.html you do need to make sure you're using Angular 4.4.4 or higher for the empty state select to render correctly
