### ISSUE TITLE
Configuring format and localization of calendar period button in datepicker

### ISSUE THREAD

**Issue by lainiwakurafan** [angular/material2#7680]
Hi, I have this format at the header of datepicker:

![95878e3b5ede5c42266c3c7651374d11](https://user-images.githubusercontent.com/24371248/31384061-06caeb68-adc6-11e7-929f-8d5294537f93.png)

How can I change it?

Please, notice that I am using 'fi-FI' locale, but it does not affect calendar period button area :(

Hope you guys can help me!

P.S. I'm using version '2.0.0-beta.11'. I also tried to reproduce problem on plunker (https://stackblitz.com/edit/angular-material2-issue-8naqf1), but with no success.

**Comment by andrewseguin** [comment]
Please refer troubleshooting by connecting with the community at StackOverflow, Gitter, or Google Groups.
