### ISSUE TITLE
Form is submitted when surrounding MatTabGroup or MatStepper

### ISSUE THREAD

**Issue by msc117** [angular/material2#7684]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Inner button doesn't trigger form `(submit)` event

#### What is the current behavior?
Buttons without an action or with `matStepperNext` trigger form submit

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-m2n91t?file=app%2Fapp.component.html
https://angular-material2-issue-m2n91t.stackblitz.io/
Click the buttons and check the console to see form submit function being called without being requested.

#### What is the use-case or motivation for changing an existing behavior?
Allow having a `(submit)` event on a parent `<form/>` element for these components

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`2.0.0-beta.12`

**Comment by willshowell** [comment]
This is expected behavior From [MDN | \<button\>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button),

> **`type`**
>
> The type of the button. Possible values are:
> * **submit**: The button submits the form data to the server. This is the default if the attribute is not specified, or if the attribute is dynamically changed to an empty or invalid value.
> * **reset**: The button resets all the controls to their initial values.
> * **button**: The button has no default behavior. It can have client-side scripts associated with the element's events, which are triggered when the events occur.

**Comment by msc117** [comment]
Ah I

**Comment by msc117** [comment]
Ah I see. Thanks @willshowell. I needed to apply `type="button"` to these buttons to prevent the default form submit function

**Comment by andreElrico** [comment]
I had the same issue. Thank you for posting this github question.

As we all copy code from angular material stackblitz sometimes we have to tweak it.
