### ISSUE TITLE
Material 2 dialog not opening in error block when the API returns 404

### ISSUE THREAD

**Issue by darshu514** [angular/material2#7687]
This is my code. The dialog is not opening in the error block of the code. The dialog does open when the API call returns 200(Success).

editBox() {
// The dialog opens here
    this.loadingDialogComponent = this.dialog.open(LoadingDialogComponent);
    this.dataService.checkItems(this.itemId).subscribe((results) => {
        this.loadingDialogComponent.close();
        this.createChildDialog = this.dialog.open(CreateChildDialogComponent, {
        height: '80%',
        width: 'auto'
      });
    }, (error) => {
      this.loadingDialogComponent.close();
      // The dialog doesn't open here
      this.createChildDialog = this.dialog.open(CreateChildDialogComponent, {
        height: '80%',
        width: 'auto'
      });
      this.createChildDialog.afterClosed().subscribe(result => {
        this.createChildDialog = null;
      });
    });
  }

**Comment by willshowell** [comment]
Please provide a reproduction

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
