### ISSUE TITLE
[Tabs] md-tab-group scrolling/pagination missing

### ISSUE THREAD

**Issue by maciejsobala** [angular/material2#769]
#### What is the expected behavior?

When md-tab-group contain too much md-tab objects to display them on the screen, there should be 'next' arrow displayed (as in angular 1)
#### What is the current behavior?

list of md-tab is cutted.
#### Which versions of Angular, Material, OS, browsers are affected?

Angular: 2.0.0-rc.3
Material: 2.0.0-alpha.5-2
Browsers: Safari, Chrome, FireFox
OS: OS X El Capitan, iOS 9.3
#### Workaround

Add 

```
.md-tab-header {
  overflow: auto !important;
}
```

To stylesheet

**Comment by RaulRG** [comment]
It would be really great if you could add support for "Tabs with overflow pagination" or "Scrollable tabs" as defined in the material design guidelines.

From the guidelines:
"To navigate between scrollable tabs, touch the tab or swipe the content area left or right. To scroll the tabs without navigating, swipe the tabs left or right."

**Comment by matt-uib** [comment]
Do you already have some date when this might be implemented? Would be cool to have that feature..

**Comment by andrewseguin** [comment]
This has been implemented in #2084 and is in the latest release (alpha 11)

**Comment by thekalinga** [comment]
@andrewseguin Is there a reason why this is not implemented for `md-tab-nav-bar`?

**Comment by thekalinga** [comment]
@andrewseguin Just realized there is an issue already filed for this.

Linking it here just for reference.

https://github.com/angular/material2/issues/2177

Thank in any case.
