### ISSUE TITLE
mat-form-field doesn't display * next to placeholder for ngControl with Validators.required

### ISSUE THREAD

**Issue by trevorade** [angular/material2#7693]
#### Bug, feature request, or proposal:

Make mat-form-field recognize [`Validators.required`](https://angular.io/api/forms/Validators#required) as a reason to put the * next to the placeholder text.

#### What is the expected behavior?

If you have a `<mat-form-field>` with an `<input>` that doesn't have a `required` attribute and the input is associated with a form control (via [formControl] or [formControlName]) which has the validator [`Validators.required`](https://angular.io/api/forms/Validators#required), the placeholder text should still have a * next to the text.

#### What is the current behavior?

The * only displays next to the placeholder if the `<input>` has a `required` attribute.

#### What are the steps to reproduce?

Demo: http://plnkr.co/edit/P6NNKcS2rNGJszf2jVZJ?p=preview

Both inputs should show the *.

#### What is the use-case or motivation for changing an existing behavior?

It's nice not to have to split validation across two mechanisms.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Current

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/2574

**Comment by mmalerba** [comment]
This is working as intended for now, since `FormControl` can't tell us if there is a `Validators.required` associated with it, only if it is valid in its current state. If https://github.com/angular/angular adds this feature we would be happy to support it here.
