### ISSUE TITLE
doc(form-control): value not marked as input

### ISSUE THREAD

**Issue by princemaple** [angular/material2#7698]
#### Bug, feature request, or proposal:
not sure

#### What is the expected behavior?
`value` properties being marked as `@Input`

#### What is the current behavior?
they are not

#### What is the use-case or motivation for changing an existing behavior?
make API documentation clearer

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
mat beta 12

#### Is there anything else we should know?
things I was referring to:
https://material.angular.io/components/select/api
https://material.angular.io/components/radio/api

The `value` property does not have `@Input` mark on it

**Comment by rafaelss95** [comment]
@princemaple @andrewseguin I guess this issue can be closed. I can't see this "problem" in the latest docs.

**Comment by princemaple** [comment]
Thanks for fixing!
