### ISSUE TITLE
Errors on webpack env.prod

### ISSUE THREAD

**Issue by jengfad** [angular/material2#7702]
#### Bug, feature request, or proposal:
Error encountered upon compiling using webpack env.prod

#### What are the steps to reproduce?

When running webpack env.prod, the below errors display:

```
    ERROR in ng:///C:/Source/Repos/SRT/Srt.Web/node_modules/@angular/material/pr
ogress-spinner/typings/index.d.ts.MatProgressSpinner_Host.html (2,1): Property '
DOCUMENT' does not exist on type 'typeof "C:/Source/Repos/SRT/Srt.Web/node_modul
es/@angular/common/common"'.

    ERROR in ng:///C:/Source/Repos/SRT/Srt.Web/node_modules/@angular/material/pr
ogress-spinner/typings/index.d.ts.MatSpinner_Host.html (2,1): Property 'DOCUMENT
' does not exist on type 'typeof "C:/Source/Repos/SRT/Srt.Web/node_modules/@angu
lar/common/common"'.
```

Note that when I build in dev mode there are no compilation errors.

I've tried the fix [here](https://github.com/angular/material2/issues/7651) but still having these errors.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cli: 1.4.5
node: 6.10.2
os: win32 x64
**@angular/animations: 4.2.5**
**@angular/cdk: 2.0.0-beta.12**
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/compiler-cli: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
**@angular/material: 2.0.0-beta.12**
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/platform-server: 4.2.5
@angular/router: 4.2.5
ngtools/webpack: 1.5.0
**typescript: 2.4.1**

Windows 7, Google Chrome

**Comment by Chan4077** [comment]
That's because `@angular/material` requires Angular `4.4.x` and above.
Did you see the package dependencies?

https://github.com/angular/material2/blob/9b0771286aa867ca111987e5d8232137d6a45d33/package.json#L27-L41

**Comment by jengfad** [comment]
Thanks @Chan4077. This fixed my issue. Closing this.
