### ISSUE TITLE
md select popup panel is not resized on field width changes

### ISSUE THREAD

**Issue by mirkograppi** [angular/material2#7709]
#### Bug, feature request, or proposal:

md select popup panel is not resized on field width changes

#### What is the expected behavior?

when the field width changes , the md select pupup should changes his width  according.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by andrewseguin** [comment]
Hey thanks for raising the issue. It'll help us a lot if you provide a reproduction of the issue you are referencing. That way we can dive in and make a fix that we know will satisfy what you need. Please feel free to re-open with a plunker. Here's a starter template: http://plnkr.co/edit/a1YBqpBT4hQaI2kHY1ru?p=preview
