### ISSUE TITLE
md-input and underlying input have inconsistent classnames

### ISSUE THREAD

**Issue by tanmaybinaykiya** [angular/material2#771]
#### What is the expected behavior?

md-input and underlying input element should have consistent classnames
#### What is the current behavior?

md-input has "ng-valid" while input has "ng-invalid" 
#### What are the steps to reproduce?

Plunker template: http://plnkr.co/edit/f8Hz6TcTf2WxbjZ30Wyb?p=info
Enter any text in the input field and clear it after doing so.
Now compare the classnames on the md-input element and the input element.
the md-input element is still ng-valid while the input element is ng-invalid

**Comment by michaelchiche** [comment]
#https://github.com/angular/angular/issues/9700

**Comment by michaelchiche** [comment]
This issue is also reported in the official angular/angular repository angular/angular#9700

**Comment by mmalerba** [comment]
closing based on kara's comment on the angular/angular issue https://github.com/angular/angular/issues/9700#issuecomment-253297394
