### ISSUE TITLE
Documentation examples still use md components...

### ISSUE THREAD

**Issue by sebastiendan** [angular/material2#7715]
Your doc is updated with the use of mat prefix instead of md, yet your examples are still using md prefix.

Quite misleading...

**Comment by Chan4077** [comment]
You have to clear the cache manually.

<sup>The following instructions assume you're running Chrome.</sup>
Either:
1. Open Chrome DevTools on <https://material.angular.io>
2. Hold the reload button. There should be the following options: `Reload`, `Hard Reload` and Empty Cache and Hard Reload. Click on the `Hard Reload` menu item.

Or (not tested yet):
1. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Delete</kbd> (or <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>Delete</kbd> for Mac) to go to the `Clear Browsing Data` dialog.
2. Check the `Cached images & Files` option:
![image](https://user-images.githubusercontent.com/20047125/31447992-e949aeec-aed5-11e7-9313-c6f2de7c96a2.png)
3. Click on the `Clear browsing data` button.

**Comment by crisbeto** [comment]
Closing since you're probably getting cached content.

**Comment by sebastiendan** [comment]
Indeed that was the issue. 

However having the user to empty his/her cache is not a solution to me, this has to be done on your side... Like everywhere else on the Internet :)
