### ISSUE TITLE
perf(md-select): repaint on scroll (Google Chrome)

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#7716]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It should not repaint on scroll

#### What is the current behavior?
It repaints on scroll
![image](https://user-images.githubusercontent.com/7990765/31449471-49c83f7e-aea7-11e7-976d-530d2f9f9dea.png)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-vyd5mg

#### What is the use-case or motivation for changing an existing behavior?
Performance matters.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.12

**Comment by maxime1992** [comment]
Shouldn't be that done nearly everywhere?

For example this behaviour is still present on table, which is not great when there's quite some lines.

I know that we can use the pagination but still, feels like it might be faster for tables with 50 or 100 items
