### ISSUE TITLE
Error in MatMenuModule

### ISSUE THREAD

**Issue by fad250** [angular/material2#7722]
I updated my menu code from md to mat to accommodate the new name changes. It gave me the following error:

![image](https://user-images.githubusercontent.com/15860769/31461266-9acc6516-aea3-11e7-90e4-776236c6cb3b.png)

I updated my npm package and also included @ViewChild(MatMenuTrigger) trigger: MatMenuTrigger, but still gives the same error.

**Comment by willshowell** [comment]
You probably are not importing `MatMenuModule` into your NgModule

**Comment by fad250** [comment]
I did import it into the NgModule. I found my package.json a bit odd, I updated it again and that fixed the bug. I think it could be a dependency problem on my end.
