### ISSUE TITLE
mat select not displaying correctly

### ISSUE THREAD

**Issue by alexschultz** [angular/material2#7723]
#### Bug, feature request, or proposal:
mat select is not displaying correctly as per the documentation

#### What is the expected behavior?
https://material.angular.io/components/select/overview

#### What is the current behavior?
default value not displaying and bottom bar not displaying

#### What are the steps to reproduce?

http://plnkr.co/edit/BkDM5OofpNVqR8yepgT1?p=preview

#### Is there anything else we should know?
FYI, The documentation still uses the old <md-select> component in the code example but the description above uses <mat-select>
https://material.angular.io/components/select/overview

**Comment by willshowell** [comment]
You must wrap `mat-select` in `mat-form-field`, as of beta.12

**Comment by ghd8** [comment]
To get the actual version of the documentation,  you can follow these instructions  https://github.com/angular/material2/issues/7715#issuecomment-335835631
