### ISSUE TITLE
Dynamically uncheck multiple select options in md-select angular 4

### ISSUE THREAD

**Issue by imchaitanya9** [angular/material2#7730]
#### Bug, feature request, or proposal: 
I am not able to uncheck select option programmatically, yes I can remove items from selected array programmatically but it's not reflecting into UI of md-select.

#### What is the expected behavior? 
If I can handle selected array then it should reflect into UI as well. In UI the item must be unchecked while removing an item from selected array

#### What is the current behavior? 
I can't uncheck item dynamically / programmatically.

**Comment by crisbeto** [comment]
How are you removing items from the array? Are you using splice, pop etc. to mutate the current value?

**Comment by imchaitanya9** [comment]
I am using slice.

**Comment by crisbeto** [comment]
Handling that case is tricky, because Material depends on Angular's change detection dispatching when something has changed. Since `slice` mutates the array, Angular won't consider it as changed.

**Comment by andrewseguin** [comment]
For help troubleshooting Material, you'll get the best help reaching out to our community on StackOverflow, Gitter, Google Groups, etc. We'll want to keep issues focused on bugs and features only.
