### ISSUE TITLE
In "mat-expansion-panel" there is a event called "opened".

### ISSUE THREAD

**Issue by rahul-tech** [angular/material2#7733]
#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by donroyco** [comment]
What is your issue? Please explain.

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
