### ISSUE TITLE
In "mat-expansion-panel" there is a event called "opened"

### ISSUE THREAD

**Issue by rahul-tech** [angular/material2#7734]
#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by TheRedD0t** [comment]
Duplicate of #7733.
