### ISSUE TITLE
MatCheckboxModule: Error: Unexpected value 'undefined' imported by the module 'e'

### ISSUE THREAD

**Issue by zladuric** [angular/material2#7735]
Bug report: I've upgraded from Material beta.8 to beta.12 and I cannot import MatCheckboxModule any more.

Expected:
Importing MatCheckboxModule imports the module. 

Current:
Importing MatCheckboxModule breaks with the error `Error: Unexpected value 'undefined' imported by the module 'e'`

1. Import the MatCheckboxModule in your module file.
2. Add it to `imports` of your own module.

That's it, the app breaks. Here's a super simple plunkr:

https://plnkr.co/edit/NwoKpybhFNCsOBGAOCiI?p=preview

I got this by simply upgrading from **beta.8** to **beta.12**. Other imports (that I use, some 10 of them) work as expected.

Versions I use:

Angular 4.4.x, Material beta.12, on Linux or OSX, Typescript 2.2. all browsers I assume (but at least Chrome and Firefox and mobile Chrome on iOS and Android).

**Comment by Chan4077** [comment]
What's the `window.AngularVersionForThisPlunker` in the `config.js`?
I tried evaluating it in the DevTools console, but apparenantly it was `undefined`.

**Comment by zladuric** [comment]
Well, importing VERSION from @angular/core in that plunk gives 4.4.4.

**Comment by zladuric** [comment]
Ok, this was totally my fault. Somehow I've replaced imports:

    '@angular/cdk/observers': 'npm:@angular/cdk/bundles/cdk-stepper.umd.js',
    '@angular/cdk/stepper': 'npm:@angular/cdk/bundles/cdk-observers.umd.js',

I'm pretty sure I've copy-pasted all that from somewhere and then regex-converted to what I needed. Anyway, problem solved.
