### ISSUE TITLE
angular2 material datepicker can't open when used with  in angular2-bootstrap modal

### ISSUE THREAD

**Issue by NSHAG** [angular/material2#7736]
#### What is the expected behavior?
upon clicking the button, the datepicker should open in the modal dialog itself 

#### What is the current behavior?
upon clicking the button, the datepicker wouldn't open in the modal dialog itself but opens in the background

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by willshowell** [comment]
This has been a common issue with bootstrap modals, and it's as easy as checking your z-index's. Should be easy to override with a global style.

**Comment by crisbeto** [comment]
In general, Material components are meant to work with other Material components. We don't test whether they interop with component libraries.
