### ISSUE TITLE
Make Angular Material work in offline compiler

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#774]

**Comment by luisfurnas** [comment]
When trying to offline compile my Angular app, I get this error:

`Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'coreModules'.`

I'm trying to use the MdTooltipModule in my bootstrap module, but it doesn't compile 👎

**Comment by cyrilletuzi** [comment]
#832 has been closed as a duplicate of this issue, but I don't think they are the same.

I'm running an app with AoT offline compiler and Material modules (icon, button, card, input, menu, toolbar), and it's working very well.

But it is not working with Universal. I get the same "window is not defined" error, as mentioned in #832.

After a quick look at the code, Material umd bundles are full of reference to "window". Is that normal ?

**Comment by orangesoup** [comment]
@cyrilletuzi I'm trying to work with Universal as well, no luck so far. You can bypass the window error by putting `var window = undefined` in those umd bundles, but after that I ran into an issue:

```
/.../node_modules/@angular2-material/core/ripple/ripple.js:10
import { NgModule, Directive, ElementRef, HostBinding, Input } from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import
```

I'm really not a webpack/node guy, but it's probably just a configuration issue, although I really can't find out what I should do. Any idea?

**Comment by cyrilletuzi** [comment]
@orangesoup Thanks for the `var window = undefined;` trick, it worked. Of course it is not a good solution, but I don't know how to fix that correctly, any idea @jelbourn @hansl ?

@orangesoup Your import problem is just a config problem. Your tsconfig.json for ts-node must be set as : 
```
"target": "es2015",
 "module": "commonjs"
```

**Comment by jelbourn** [comment]
See #308

We haven't had the opportunity yet to ensure that everything works with Universal, but it will be coming within the next few milestones. Happy to have community contributions to help improve this sooner, though.

I'm actually going to close this issue now, since everything should be good for AoT AFAIK, and Angular Universal is tracked via #308.

**Comment by orangesoup** [comment]
@cyrilletuzi You mean I have to manually build material with that tsconfig?

**Comment by cyrilletuzi** [comment]
@orangesoup no you don't need to build on server side, but as Angular 2 is in TypeScript, which is not understood by node natively, you need to use [ts-node](https://www.npmjs.com/package/ts-node) with that config.

**Comment by dotansimha** [comment]
Any solution so far? 
I am using Universal and unable to import the material modules. 
Always the same error - "window is no defined"

**Comment by cyrilletuzi** [comment]
@dotansimha @orangesoup See a temporary workaround [here](https://github.com/angular/material2/issues/308#issuecomment-247757585) in #308
