### ISSUE TITLE
material 2 test issue: fixture.debugElement can not access to element inside mat-menu

### ISSUE THREAD

**Issue by liliom55** [angular/material2#7742]
@mprobst 

#### Bug, feature request, or proposal:

`fixture.debugElement `can not access to element inside mat-menu

#### What is the expected behavior?

I want to test an element inside mat-menu component but it does not work 

#### What is the current behavior?

`Failed: Cannot read property 'textContent' of null`

#### What are the steps to reproduce?

https://github.com/liliom55/test-fitApp

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
"@angular/cli": "1.0.0"
"@angular/material": "^2.0.0-beta.11"
OS: Windows
"typescript": "~2.2.0"
browser: chrome
```

**Comment by willshowell** [comment]
The menu content does not exist in the dom until you open it, so `<span class="aaa">Redial</span> ` will not be exist inside your component. You may wish to look at the menu tests here

https://github.com/angular/material2/blob/master/src/lib/menu/menu.spec.ts

**Comment by crisbeto** [comment]
You can refer to the current menu tests to see how it can be tested.
