### ISSUE TITLE
Control when autocomplete options panel opens

### ISSUE THREAD

**Issue by jmarlow4** [angular/material2#7753]
#### Bug, feature request, or proposal:
I'd like to only show the autocomplete panel once the user has entered an input, or perhaps even only show the panel if there are 5 or fewer options. Is there a simple way to do this?

#### What is the expected behavior?
See above

#### What is the current behavior?
The panel always opens when the autocomplete's input is focused.

#### What is the use-case or motivation for changing an existing behavior?
If there are a lot of entries in the options coming in.

**Comment by willshowell** [comment]
You have full control over which and how many options are available. You can just make your array of options empty until you're ready to show the panel.

**Comment by andrewseguin** [comment]
Will's suggestion should help you out. If you need further help, feel free to ask on StackOverflow, Gitter, or Google Groups. We try to keep issues only for bugs and features
