### ISSUE TITLE
DOCS - Card Example not working

### ISSUE THREAD

**Issue by mswilson4040** [angular/material2#7757]
#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

1.) Navigate to https://material.angular.io/components/card/examples
2.) Observe Card Example not rendering correctly

**Comment by donroyco** [comment]
That's because the images are loaded over HTTP, not HTTPS.
