### ISSUE TITLE
Emitting event on model change

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#776]
This is just for discussion.
Do components have to emit changes if the viewmodel changes.
As example
`<md-checkbox [(ngModel)]="myValue">`
If i check (using the mouse) the checkbox, it's normal to get an event emitted with the value of the change.
But if I fo progamatically do `this.myValue = true;` Do the checkbox have to emit an event?

**Comment by fringd** [comment]
+1 this is causing a bug for my when I attempt to implement hierarchical checkboxes.

checking all of the boxes causes the parent box to become checked, all good.

but unchecking a single box cases the parent box to become unchecked, which fires an event, which causes all of the boxes to become unchecked. not good, and also causes a devmode value changed after change detection exception.

**Comment by jelbourn** [comment]
@fringd should be fixed in checkbox in the latest release. The fix needs to make its way to other components. The gist is that controls should only fire a change event when they have focus. Closing this into #791
