### ISSUE TITLE
[Table] Let column sorting be disabled dynamically

### ISSUE THREAD

**Issue by swftvsn** [angular/material2#7761]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I need to be able to disable sorting under some circumstances on column level. I'd like to do something like `[mat-sort-header]="enabled"` where enabled is boolean.

#### What is the current behavior?
I'm not able to dynamically disable sorting

I also experimented with 

```ts
@ViewChild(MatSort) sort: MatSort
//and later
this.sort.sortables.forEach((value, key) => {
  this.sort.deregister(value)
})
```
but for some reason this does not do anything when template is set like this:
```html
<mat-table matSort [dataSource]="dataSource" [matSortDisableClear]="true">

    <ng-container matColumnDef="id">
      <mat-header-cell *matHeaderCellDef mat-sort-header> ID </mat-header-cell>
      <mat-cell *matCellDef="let row"> {{row.id}} </mat-cell>
    </ng-container>
.
.
.
```

The only way to pull this off is to have duplicate columns, one where `mat-sort-header` is declared and one where it is not. (And toggle the `matHeaderRowDef` and `columns` accordingly.)

**Comment by andrewseguin** [comment]
Fixed in https://github.com/angular/material2/pull/8643

**Comment by Gil-Epshtain** [comment]
<ng-container *ngFor="let column of dynamicColumns" [matColumnDef]="column">
  <th mat-header-cell *matHeaderCellDef mat-sort-header [disabled]="isSortingDisabled(column)">
    {{ column }}
  </th>
  <td mat-cell *matCellDef="let element">
    {{ element[column] }}
  </td>
</ng-container>

  public isSortingDisabled(columnText: string): boolean
  {
    return false; // add your logic here
  }
