### ISSUE TITLE
No scrolling to an item when typing

### ISSUE THREAD

**Issue by marekhvolka** [angular/material2#7763]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
We have more options ( > 6) and they are sorted alphabetically. When we open the select and type a letter, we want **to scroll** to a item, which label begins with this letter. If we type the letter again, the next item with same beginning letter is focused. 

#### What is the current behavior?
The first item, which begins with the letter, gets focus, but **_there is no scrolling_**. So we don't see the item. if it's not already in the visible part of the list.

#### What are the steps to reproduce?
Example is here [(https://plnkr.co/edit/predJ8IGg0Nexj54BAQH?p=preview)] 

1. Open the select
2. Type "s"
3. Manually scroll to the first item, which starts with letter s
4. This item is focused (which is right). but the scrolling is not working.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.12

**Comment by crisbeto** [comment]
This has been fixed in master by https://github.com/angular/material2/pull/7620.
