### ISSUE TITLE
Select does not show placeholder text or underline in beta.12.

### ISSUE THREAD

**Issue by chris93007** [angular/material2#7769]
#### Bug
Select does not show placeholder text or underline in beta.12.

#### What is the expected behavior?

Select should be more visible with underlined component and placeholder text

#### What is the current behavior?
Only arrow down appears

#### What is the use-case or motivation for changing an existing behavior?
Making select visible. Better UX.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular ^4.3.6, Material 2.0.0-beta.12

**Comment by TheRedD0t** [comment]
Select works fine for me, playeholder and 'underline' are visible.

**Comment by cfarfan** [comment]
You need to wrapper mat-select using mat-form-field
`<mat-form-field>
      <mat-select>
        ...
        <mat-option>...</mat-option>
        ...
      </mat-select>
    </mat-form-field>
`

**Comment by crisbeto** [comment]
You should wrap the select with a `mat-form-field` as @cfarfan suggested.
