### ISSUE TITLE
Will there be a theme provider like in Angular Material 1?

### ISSUE THREAD

**Issue by ladyleet** [angular/material2#777]
#### Bug, feature request, or proposal:
Will there be a theme provider like in Angular Material 1?
https://material.angularjs.org/latest/Theming/03_configuring_a_theme

#### What is the expected behavior?
Adding themes via some configuration, similar to material in ng1.

#### What is the current behavior?
There doesn't seem to be a way to switch themes.

#### What is the use-case or motivation for changing an existing behavior?
MOAR THEMES

#### Which versions of Angular, Material, OS, browsers are affected?
Current master

**Comment by jelbourn** [comment]
This is tracked via #123
