### ISSUE TITLE
mat-select not pre selecting a value using ngModel

### ISSUE THREAD

**Issue by Lakston** [angular/material2#7771]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the ngModel of a mat-select is populated on page load the mat-select should have that option selected.

#### What is the current behavior?
mat-select is always showing the placeholder, I've tried using basic primitive values (numbers for the options and ngModel initialised with one of the numbers on page load) and the select is never reflecting the selected option.

#### What are the steps to reproduce?
 [mat-select issue](https://stackblitz.com/edit/angular-material2-issue-7d4bga)

I also added an example with a regular select and option to show that the code is working when not using material, hopefully that helps.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material beta 12
angular 4.3.2

#### Is there anything else we should know?
Please update the plunkr examples with a working version

**Comment by willshowell** [comment]
Try with the stackblitz from the issue template: https://goo.gl/wwnhMV

**Comment by willshowell** [comment]
Ah ok, this is expected behavior. When you bind to `value` like this, you are actually binding as a `string` because `{{ ... }}` is the syntax for string interpolation.

```
value="{{ number }}"
```

Your values in `numbersArray` are of the type `number`, so by default, it will try to compare `'2' === 2` which will return false.

Instead you should bind like this (you can read more about it [here](https://angular.io/guide/template-syntax)),

```
[value]="number"
```

That having been said, it is different than the native select, cc @crisbeto.

**Comment by Lakston** [comment]
I'll admit we just figured it out and I was about to perform my walk of shame :)

Thanks for your help, we'll go with `[value]="number"`

**Comment by regoczy** [comment]
`<mat-form-field  class="mrg" style="width: 100%;">
                <input matInput placeholder="Name" [(ngModel)]="testCase.name">
            </mat-form-field>
            <select
                [(ngModel)]="this.testCase.prio">
                <option [value]="1">
                    1
                </option>
                <option [value]="2">
                    2
                </option>
                <option [value]="3">
                    3
                </option>    
            </select>
            <mat-form-field>
                <mat-select
                    placeholder="Priority"
                    [(ngModel)]="this.testCase.prio"
                    [value]="this.testCase.prio">
                    <mat-option [value]="1">
                        Critical
                    </mat-option>
                    <mat-option [value]="2">
                        Major
                    </mat-option>
                    <mat-option [value]="3">
                        Minor
                    </mat-option>
                </mat-select>
            </mat-form-field>`

I am still having this issue.
Both of them bind successfully and change the value of this.testCase.prio, but when the page is loaded, the normal select has the correct value displayed. but the mat-select only shows the placeholder.

**Comment by JamesWPritchett** [comment]
this worked for me
`
<mat-form-field>

    <mat-select [ngModel]="sortLevel.SortOrder" (change)="setSortOrder($event)">
        <mat-option [value]="0">{{'ASCENDING' | translate}}</mat-option>
        <mat-option [value]="1">{{'DESCENDING' | translate}}</mat-option>
    </mat-select>
</mat-form-field>`

Also the MatSelectChange.value is expressed as a number, now, too
