### ISSUE TITLE
The "mat-" prefix cannot be used in ng-material v1 compatibility mode

### ISSUE THREAD

**Issue by mbx2015** [angular/material2#7772]
I already updated @angular/material and @angular/cdk to v beta.12 but I got this error
` ERROR Error: The "mat-" prefix cannot be used in ng-material v1 compatibility mode. It was used on an "mat-list" element.`

What's wrong ??

**Comment by willshowell** [comment]
If you are on beta.12 and have already made the conversion to mat-, then you should be able to remove `{provide: MATERIAL_COMPATIBILITY_MODE, useValue: true},`

**Comment by mbx2015** [comment]
I don't use `MATERIAL_COMPATIBILITY_MODE` in my code

**Comment by ghd8** [comment]
if you are using "covalent" or "md2" see also
https://github.com/Teradata/covalent/issues/923
https://github.com/Promact/md2/issues/290

**Comment by andrewseguin** [comment]
Please refer all troubleshooting questions to StackOverflow, Gitter, or Google Groups.

**Comment by mbx2015** [comment]
I'm currently using md2, that's the source of the problem,
thanks
