### ISSUE TITLE
Code examples incorrect after prefix change

### ISSUE THREAD

**Issue by paszabo** [angular/material2#7781]
Apologies if this has already been reported or if the Angular Material team is already aware.

It appears that the code examples in the Angular Material docs do not reflect the change of the directive and selector prefixes from `md` to `mat`.

Please note since I am at work I have not done an exhaustive check of all code examples.

#### Bug, feature request, or proposal:

Inaccuracy in the docs

#### What is the expected behavior?

Code examples reflect old `md-*`/`mdXYZ` style prefixes.

#### What is the current behavior?

Code examples should reflect new `mat-`/`matXYZ` prefixes.

#### What are the steps to reproduce?

Look at the docs, all code examples I have checked (not exhaustive!!) have not been updated.

#### What is the use-case or motivation for changing an existing behavior?

The code examples should be correct.  They lower the barrier to entry for new comers to Angular Material and illustrate be practices for using Material components.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    "@angular/animations": "^4.4.5",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",

#### Is there anything else we should know?

Don't think so.

**Comment by dschreck17** [comment]
I was just about to post this. The code examples should be updated to use mat- instead of md-

**Comment by andrewseguin** [comment]
Can you try clearing your browser cache and refreshing? We have some aggressive caching on the site that seems to be keeping some people from seeing the new content.

**Comment by paszabo** [comment]
@andrewseguin yep clearing the cache seems to have done the trick.

Not sure if I'm supposed to close this or you but I am satisfied.

**Comment by andrewseguin** [comment]
Cool thanks for the confirmation!
