### ISSUE TITLE
Placeholder doesn't appear in mat-select, select box 

### ISSUE THREAD

**Issue by JosephSKh** [angular/material2#7784]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Placeholder to appear

#### What is the current behavior?
Placeholder doesn't appear

#### What are the steps to reproduce?
I've just added this code and the placeholder doesn't ppear after the `mat` prefix update
```
<mat-select placeholder="Favorite food">
            <mat-option [value]="0">
              TOMATO
            </mat-option>
</mat-select>
```

#### What is the use-case or motivation for changing an existing behavior?
rolling back to the old `md` prefox

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
LATEST

#### Is there anything else we should know?
No

**Comment by benb7760** [comment]
mat-select must appear inside a mat-form-field since [beta12](https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta12-marble-mustache-2017-10-05)

**Comment by JosephSKh** [comment]
@benb7760 oh ok, actually that works !, thx man
do you know where can I find this documentation? the website material.angular.io isn't updated
thx again

**Comment by benb7760** [comment]
@JosephSKh A lot of people are having issues with caching - myself included. I've been browsing it in incognito mode

**Comment by JosephSKh** [comment]
@benb7760 yess, it was caching =S thx man
