### ISSUE TITLE
md-input is still using NG_VALUE_ASSESOR from common instead of forms

### ISSUE THREAD

**Issue by gregbown** [angular/material2#780]
Using MdInput with a binding causes:
Error: Uncaught (in promise): No value accessor for bindingName

Using:
Angular 2 rc3, forms 0.1.1, Material 2 2.0.0-alpha.5-2

My apologies if you are merely not supporting the new forms in rc3.

I switched the value accessor to ng.forms.NG_VALUE_ACCESSOR and everything works as expected like so in my node_modules/@angular2-material/input/input.js:
var core_1 = require('@angular/core');
var forms_1 = require('@angular/forms/index');
var field_value_1 = require('@angular2-material/core/annotations/field-value');
var error_1 = require('@angular2-material/core/errors/error');
var Observable_1 = require('rxjs/Observable');
var noop = function () { };
var MD_INPUT_CONTROL_VALUE_ACCESSOR = new core_1.Provider(forms_1.NG_VALUE_ACCESSOR, {...

**Comment by jelbourn** [comment]
alpha.5-3 uses the old forms
alpha.6 uses the new forms

**Comment by gregbown** [comment]
Just FYI, I updated my package.json to:
"@angular2-material/input": "^2.0.0-alpha.6", ran npm update, and noticed the input.js appears to be compiled from alpha.5-3 because it is still using the common_1.NG_VALUE_ACCESSOR
Thank you though, I'm sure you have your hands full with all these changes.

**Comment by kara** [comment]
Hmm, the alpha.6 package appears to be working for me.  Can you link to a plunker that demonstrates the issue? Maybe we are testing differently.

**Comment by gregbown** [comment]
Removed ^ "@angular2-material/input": "2.0.0-alpha.6" in package.json solves this, my mistake, sorry.
