### ISSUE TITLE
##After Updating Angular Material MD-Dialog throws error can't compile  

### ISSUE THREAD

**Issue by rahulranjan72** [angular/material2#7803]
#### Bug, feature request, or proposal:
How to use both Previous and latest material Design in Single Application without Affecting the Previous code of Material Design 

#### What is the expected behavior?
Code was working with the previous version 

#### What is the current behavior?
Error Not able to Compile the code after updating to latest angular version 

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by julianobrasil** [comment]
I don't think its possible. Somethings change inside the library itself that affect its own components. For example, cdk is used as a base for other components, and a change in it has effects in others, so if you keep cdk version different from material version, you're exposed to potential problems.

**Comment by rosvicente** [comment]
Same issue... modules are missing from '@angular/material' will not compile even using VS 2017 or VSCode.

**Comment by zbarbuto** [comment]
You need to use the `Mat` prefix now, not md.

https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes
>All "md" prefixes have been removed. See the deprecation notice in the beta.11 notes for more information.

**Comment by josephperrott** [comment]
Closing as we are not yet stable so breaking changes do still (sometimes) occur.  You can see the list of breaking changes for each release [here](https://github.com/angular/material2/blob/master/CHANGELOG.md)
