### ISSUE TITLE
The Documentation in Getting Started is wrong 

### ISSUE THREAD

**Issue by steven-fernandez** [angular/material2#7804]
#### Bug, feature request, or proposal:

When you go to this page you see this:

import {MdButtonModule, MdCheckboxModule} from '@angular/material';

This should be:

import {MatButtonModule, MatCheckboxModule} from '@angular/material';

#### What is the expected behavior?

It's outdated:

import {MdButtonModule, MdCheckboxModule} from '@angular/material';

#### What is the current behavior?

If you follow the current instructions you will get an error and the project will not run

#### What are the steps to reproduce?

Just follow the instructions.. The project will not work.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Current version on the 14th october 2017

**Comment by benb7760** [comment]
Possibly a caching issue - can you try in incognito mode, or clearing cache?

**Comment by steven-fernandez** [comment]
Yes, that worked in incognito mode, thanks :)

**Comment by ghd8** [comment]
You can also try these instructions https://github.com/angular/material2/issues/7715#issuecomment-335835631

**Comment by crisbeto** [comment]
Closing since it's a caching issue.
