### ISSUE TITLE
(Select) select options does not fully responsive

### ISSUE THREAD

**Issue by tieppt** [angular/material2#7811]
#### Bug, feature request, or proposal:
[ x ] Bug

#### What is the current behavior?

At the first show the `select options`, the cdk calculate width for select options, after that when user resize (rotate screen on mobile) the cdk does not recalculate again. So the width of select options is overflowing the container.

#### What is the expected behavior?

The width of select options is adaptive.

#### What are the steps to reproduce?

Resize this page:

https://angular-dynamic-forms.firebaseapp.com/

**Comment by ortaras** [comment]
![001](https://user-images.githubusercontent.com/11505514/31772053-f67376ae-b4e6-11e7-985f-3c3860221937.png)
![002](https://user-images.githubusercontent.com/11505514/31772054-f696cdfc-b4e6-11e7-9dca-1b02f0da43b1.png)
![003](https://user-images.githubusercontent.com/11505514/31772055-f6b80d46-b4e6-11e7-9145-f2c2376404be.png)
![004](https://user-images.githubusercontent.com/11505514/31772056-f6d3801c-b4e6-11e7-99a4-9a41529f236e.png)

**Comment by sagar-ganatra** [comment]
Any update on this? I've noticed the same behaviour and it's stopping me from using this library.

**Comment by leNicDev** [comment]
Experiencing the same issue here!

**Comment by coffeetea-synchestra** [comment]
The same :(

**Comment by djob** [comment]
Any update?

**Comment by SteveGZr** [comment]
Got the same issue!

**Comment by iamxor** [comment]
hey any chance to fix dis?

**Comment by dik-garri** [comment]
Any update to solve this?

**Comment by siqiren819** [comment]
Any update please?

**Comment by dik-garri** [comment]
@siqiren819 
After updating @ angular / material to the last version it works better. Not perfect for small screens, but generally much better

**Comment by BezobidnijPsih** [comment]
would be great to have it fixed
