### ISSUE TITLE
Is there anywhere I can post for solutions to common problems?

### ISSUE THREAD

**Issue by kenji-1996** [angular/material2#7814]
Sorry for almost certainly a bad place to put this but I dont see anywhere else to post this;
Is there any place to post solutions to common problems? any way to add to the wiki or share helpful information found?
Again sorry for the wrong place, im new to github

And I dont mean like search for the problem in issues, but just a general informative post, or is there so much place for this? if not then please just close I apologize for time wasting

**Comment by Chan4077** [comment]
Make an account at <https://stackoverflow.com>, post your question with the title of your problem and with the tags `angular-material2`/`angular-material` and `angular`.

**Comment by fxck** [comment]
make a pr to material.angular.io repo

**Comment by willshowell** [comment]
@kenji-1996 another approach would be to create your own repo with a wiki that collects common patterns. Getting it to be widely adopted will be a challenge but IMO gitter and SO have been miserable for carrying organized discussions, so it could be a very welcome change.

**Comment by kenji-1996** [comment]
What a good idea, I have been finding lots of helpful pieces of code while creating in Material 2 and Id love to help people who were as lost as me with getting past things that should be simple fixes :)

**Comment by jelbourn** [comment]
Having a medium blog is also popular. PRs for docs are great (particular adding examples). 

Closing this since issues are for bugs / feature requests / proposals.
