### ISSUE TITLE
Material Design Expansion Panels with animation effect in Angular 4

### ISSUE THREAD

**Issue by Mehul1995** [angular/material2#7816]
#### Feature request/Proposal:
Multiple expansion panels in a single card.(Accordion in Material design with ripple effect).

#### What is the expected behavior?
Drops down multiple cards with animation style, and minimizes with animation.

**Comment by TheRedD0t** [comment]
The Expansion Panel is already implemented:
https://material.angular.io/components/expansion/overview

**Comment by josephperrott** [comment]
Closing as the Material Expansion Panel and Accordion are already released.
