### ISSUE TITLE
[disabled] not changed for <md-tab>

### ISSUE THREAD

**Issue by copiali** [angular/material2#7817]
My html
`<md-tab label="Body" [disabled]="disableBodyTab">
          <textarea></textarea>
 </md-tab>`

ts file:
  checkMethod() {
    this.disableBodyTab = this.requestForm.get('method').value === 'get';
  }

After checkMethod triggered, the value for disableBodyTab  changed to false, but it's still disabled.

If I change the html to:
`<md-tab label="Body{{disableBodyTab}}" [disabled]="disableBodyTab">
          <textarea></textarea>
 </md-tab>`

It works. Is it a bug?

**Comment by josephperrott** [comment]
Can you provide a reproduction in either stackblitz or plunker?

The tab should disable as you say, however we need a reproduction to investigate.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
