### ISSUE TITLE
Custom Error Matcher does not work for me 

### ISSUE THREAD

**Issue by ferdaousharmel** [angular/material2#7819]
Hello,

Custom Error Matcher in  : 
https://material.angular.io/components/input/overview
does not work for me ! I have not a form I just have a matInput control.
If you can help me please ?

Thanks.

**Comment by donroyco** [comment]
Please use [the issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md) and create a Plunker/StackBlitz to see your code.

**Comment by ferdaousharmel** [comment]
Hello,
Custom Error Matcher does not work for me.
What is the expected behavior?
to get the error message when the input is invalid.
What is the current behavior?
nothing is happened; the isErrorState is never invoked.
What are the steps to reproduce?
I create the Plunker project but ihave no permission to save, also i can't see the result so i just join the code below.
[custom_error_matcher_example.zip](https://github.com/angular/material2/files/1386672/custom_error_matcher_example.zip)

What is the use-case or motivation for changing an existing behavior?
it is really useful as a behaviour.

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.
OS : windows 8.
Typescript : 2.3.3
browser : chrome
Hope that is clear.

Thanks a lot.

**Comment by willshowell** [comment]
@ferdaousharmel regarding plunker (and StackBlitz), you need to fork it before you can save. 

Maybe the docs example is a little misleading, but you need to create an instance of the ErrorStateMatcher class before you pass it to your `matInput`.


```ts
myErrorStateMatcher = new MyErrorStateMatcher();
```

**Comment by ferdaousharmel** [comment]
Thanks a lot !

**Comment by jelbourn** [comment]
Resolved, I guess? Closing, feel free to open a new issue if you have a bug with reproduction.
