### ISSUE TITLE
Change of Naming ( Material Modules, Components and other )

### ISSUE THREAD

**Issue by nekkon** [angular/material2#7821]
Hello. Thank you for this great library of components. Just one request. Please do not change again the naming of Material Modules, Components and other without a really serious reason. Or at least to be the last time you change it. Material components started by using 'mat' prefix, later on changed to 'md' and now are going back to 'mat'. WHY?!?!

I do understand that this library is still in beta, but many of us use it in our projects. It is really frustrating to have to change names in the whole app. It could cause errors and bugs hard to detect. Even the online material documentation has mistakes now. I have found examples based on the previous naming which don't work anymore.

I do understand the need of a change in naming, but changing it here and there does show lack of  professionalism which I believe that it does not exist in this framework.  This does not sound nice, but it is the kindest way to say it.

**Comment by wallace41290** [comment]
I'm sure the change was well thought out and for good reason. If you read the [changelog](https://github.com/angular/material2/blob/master/CHANGELOG.md), they gave deprecation warning before completely pulling the "md-" prefix. There is even a nice tool that will convert nearly all your code to the new prefixes. We have several projects using material and it really wasn't that bad to refactor.

**Comment by aitboudad** [comment]
check this tool https://www.npmjs.com/package/angular-material-prefix-updater

**Comment by nekkon** [comment]
@wallace41290  Thanks for pointing out the deprecation warning. Just got frustrated after updating to see that had to make all these changes. Anyway, I just close this thread as it seems they did what they could.
