### ISSUE TITLE
setting second step as active step in Material-2 stepper does not work

### ISSUE THREAD

**Issue by arangates** [angular/material2#7826]
#### Bug, feature request, or proposal:
Bug in mat-stepper

#### What is the expected behavior?
setting active to mat-step does not make it active 

#### What is the current behavior?
step 1 is always active

#### What are the steps to reproduce?
`
<mat-vertical-stepper>
    <mat-step label="Agreement Preparation">
        <p>Agreement preparion is intiated by our side </p>
    </mat-step>
    <mat-step label="Ready for Biometric" selected active>
        <p>Agreement preparion is intiated by our side </p>
    </mat-step>
    <mat-step label="Document in Submission">
        <p>Agreement preparion is intiated by our side </p>
    </mat-step>
</mat-vertical-stepper>
`

#### Which versions of Angular, Material?
"@angular/core": "4.4.3",
@angular/material": "^2.0.0-beta.12

**Comment by josephperrott** [comment]
Please provide a reproduction in either [Plunker](http://plnkr.co/edit/LSgU9X5sYVhx4bc3LBWm?p=preview) or [StackBlitz](https://stackblitz.com/edit/angular-material2-issue?file=app%2Fapp.component.ts)

**Comment by arangates** [comment]
Its working after using ViewChild for MatStepper [DEMO](https://stackblitz.com/edit/ng-mat-beta-12-luhe7n?file=app%2Fapp.component.ts)

**Comment by kyleabens** [comment]
How can you mark the previous steps as completed after initializing selectedIndex?
