### ISSUE TITLE
Improve mat-table data filtering mechanism

### ISSUE THREAD

**Issue by sic-sic** [angular/material2#7834]
Feature request

What if you added a per column filtering like in the image below
![mat-table](https://user-images.githubusercontent.com/14206274/31632372-3d4e9b5e-b2ac-11e7-8e72-0c73e8bb7a56.PNG)

This would be clearer for an end user than a single input.

![mat-table-2](https://user-images.githubusercontent.com/14206274/31632770-abacacca-b2ad-11e7-9a69-4ee1a75f47cd.PNG)

**Comment by andrewseguin** [comment]
This would be something you add to your header template if you would like it included in the table. The table doesn't have any prescribed method for filtering, this would totally be a valid approach. If you want help setting something like this up, I'm sure the community on StackOverflow or Google Groups or Gitter would be able to help you out.

**Comment by sic-sic** [comment]
I agree, but I think this could be added as a feature in the next mat-datatable. The community can discuss this topic if I'm not the only one waiting for this feature

**Comment by dsbert** [comment]
@sic-sic Were you able to come up with an elegant implementation of inline filters?

**Comment by sic-sic** [comment]
@dsbert I gave up this. I went for the single input.
