### ISSUE TITLE
IE 10 support/question.

### ISSUE THREAD

**Issue by angular2fan** [angular/material2#7836]
Hi, I read through the documentation and learnt that Material Design supports the latest 2 versions of the browsers , But unfortunately, we have some users who use legacy laptops and IE 10 is the version they are using. 

I am using Material Design Dialog module and that doesnt seem to work on IE10. If I debug more this is the error I see. 

"TypeError: Accessing the 'arguments' property of a function is not allowed in strict mode\n   at Zone.prototype.runTask 

I am therefore wondering to know what can be done in this situation.

Thankyou.

**Comment by RichardBoyder** [comment]
Yes please we really do need this working for all browsers. Why would adialog not work in I.E 10 and below?

**Comment by jelbourn** [comment]
We do not support IE10, only IE11.

**Comment by emok032** [comment]
Are there polyfills for IE 10 that you know of?
