### ISSUE TITLE
Freeze table header when scrolling

### ISSUE THREAD

**Issue by tom10271** [angular/material2#7839]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Freeze table header when scrolling

#### What is the current behavior?
Table header does not freeze

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
https://material.angular.io/components/table/examples

Any example inside

#### What is the use-case or motivation for changing an existing behavior?
It is disturbing for user to scrolling back up to what column name is that data column is

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 2 beta 12

**Comment by TheRedD0t** [comment]
Sticky header is already a planned feature: https://github.com/angular/material2/issues/474.

**Comment by andrewseguin** [comment]
Closing as it's a duplicate.
