### ISSUE TITLE
visual difference in select control between version (2.0.0-beta.11) to current version (2.0.0-beta.12)

### ISSUE THREAD

**Issue by ArielBar** [angular/material2#7840]
hello,
Something strange happened in the transition between the versions.
**The same code behaves differently between the two versions.**
this is my code:
```html
<mat-form-field>
  <mat-select [ngClass]="{'ng-invalid' : !isValid()}"
              placeholder = {{placeholder}} disabled= {{disabled}}
             (change)="onChange($event)"
             class="full-width"
             [(ngModel)]="selectedValue"
             (blur)="setIsControlValid()">
    <mat-option *ngFor="let value of values" [value]="value[valueMemeber]">
      {{value[displayMemeber]}}
    </mat-option>
  </mat-select>
</mat-form-field>
  <mat-hint style="color:red" *ngFor="let error of getControlErrors()" align="start">
      <span style="padding-right:5px; font-size: 75%;">{{error}}</span>
  </mat-hint>
```

2 0 0-beta 11:
![2 0 0-beta 11](https://user-images.githubusercontent.com/29005175/31654490-e8b7026a-b32e-11e7-847b-31d412f37a7b.png)

2 0 0-beta 12
![2 0 0-beta 12](https://user-images.githubusercontent.com/29005175/31654503-f1c1b332-b32e-11e7-9234-99211687a2a1.png)

Is there something wrong in my code?

**Comment by CallumBrankin** [comment]
+1 It doesn't seem to be even working (Opera 48.0.2685.39)

**Comment by jelbourn** [comment]
@ArielBar there's not enough information here; it's possible that a custom style in your app interacts differently between releases

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
