### ISSUE TITLE
matTable - DataSource issue

### ISSUE THREAD

**Issue by frikkievb** [angular/material2#7845]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
The table should accept a datasource

#### What is the current behavior?
Get an error: <mat-table #table [ERROR ->][dataSource]="dataSource">
Can't bind to 'dataSource' since it isn't a known property of 'mat-table'.

#### What are the steps to reproduce?
I copied the example from the docs, updated the selectors from "mdTable" to "matTable" but no luck.

#### What is the use-case or motivation for changing an existing behavior?
NA

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/animations": "^4.4.2",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/flex-layout": "git+https://github.com/angular/flex-layout-builds.git",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "github:angular/material2-builds",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "express": "^4.15.4",
    "hammerjs": "^2.0.8",
    "ngx-restangular": "^1.0.11",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"

**Comment by willshowell** [comment]
Have you imported `MatTableModule` into your NgModule?

**Comment by frikkievb** [comment]
Now I have included it and it is working fine.  Thanks for the help.  I missed this somehow.

**Comment by siranjeevi777** [comment]
i have imported MatTable Module but still no luck mat table not working....

**Comment by teoCasasbuenas** [comment]
I have the same problem "[dataSource] is not a known property of 'table'". I did follow the guide at angular material site. I have imported MatTableModule and as suggested in issue #5577 https://github.com/angular/material2/issues/5577 (can't reference issue) I did also import CdkTableModule, but still no luck.

**Comment by pablitodeveloper** [comment]
I have the same problem.  I have imported MatTableModule and CdkTableModule but is not working

**Comment by jakubszalaty** [comment]
@teoCasasbuenas @pablitodeveloper change:
```
<table #table [dataSource]="dataSource"> 
```
```
<mat-table #table [dataSource]="dataSource">
```
If you're using version 5.2.4 of @angular/material.
https://v5.material.angular.io/components/table/examples

**Comment by teoCasasbuenas** [comment]
Thank you @jakubszalaty, that did the trick. I did not realize that there was a special documentation for the angular v5+, my bad.

**Comment by tariqporter** [comment]
Thanks @jakubszalaty 
Ridiculous that the documentation and examples still reference old versions
https://material.angular.io/components/table/examples

**Comment by willshowell** [comment]
@jhhoff02 what parts of the docs are outdated? As of 6.0.0, `<mat-table>` and `<table mat-table>` are both supported.

**Comment by hbsoftco** [comment]
I have same problem, None of the above codes not working for me.

**Comment by TejAllam** [comment]
Been trying this for about 3 days now.

**Comment by joel1618** [comment]
You may want to make sure you're using the correct example for the version of angular material you have installed.  I was getting this error because I had 5 installed but was using the 6 example.

**Comment by Skillnter** [comment]
> schemas: [ CUSTOM_ELEMENTS_SCHEMA ]

not working :/  mat-table is totally broken
