### ISSUE TITLE
Angular 5?

### ISSUE THREAD

**Issue by avril-verhaeghen** [angular/material2#7847]
Hi everybody,

My question is quite simple, we're going to use Angular Material2 in our project (for now we use the MaterialJS). The current beta version is built Angular4 (4.4.4 if I'm not mistaken). This month Angular5 is coming out, the use of both in combination should work. But is there a timeline of when an actual Material2(5) is coming out?

Thanks!

**Comment by willshowell** [comment]
I believe support for Angular 5 will coincide with 5.0's stable release. See https://github.com/angular/material2/pull/6018.

**Comment by avril-verhaeghen** [comment]
@willshowell great thanks!
