### ISSUE TITLE
Issue with dark theming

### ISSUE THREAD

**Issue by trichetriche** [angular/material2#7849]
#### Bug, feature request, or proposal:

Seems like a feature, but could be a bug

#### What is the expected behavior?

When I use the dark theming, I expect the theme to be applied everywhere

#### What is the current behavior?

The dark theme isn't applied to some components

#### What are the steps to reproduce?

Using the dark theme with : 

- Expandable panels
- dialogs
- snacks
- (Those are the 3 I've found, maybe more have this problem)

#### Is there anything else we should know?

A screen if it might help

![image](https://user-images.githubusercontent.com/7789922/31668651-107a8d48-b353-11e7-9250-f6cb3135cc39.png)

**Comment by SamiAl90** [comment]
Did you theme the overlaycontainer as described here?
https://material.angular.io/guide/theming

**Comment by trichetriche** [comment]
I actually didn't, thank you ! I'm testing it and closing this issue whether it works or not.

**Comment by trichetriche** [comment]
Well I don't have acces to the overlay component, has it changed ? 

![image](https://user-images.githubusercontent.com/7789922/31670083-22ad26d4-b357-11e7-9509-ef8244971a18.png)

**Comment by SamiAl90** [comment]
yeah it's in @angular/cdk/overlay

**Comment by trichetriche** [comment]
Sorry I was at home and didn't have time to answer. 

Everything works great, thanks you ! I'm closing this issue but not deleting it, since the overlayContainer isn't in the package given in the guide, it might help someone in the future. 

Thanks a lot for the help !

**Comment by YorkeCao** [comment]
@SamiAl90 Hi, I have got this problem, too.
I use both a light theme and a dark theme. And I have already theme the overlaycontainer like this:
```
export class AppModule {
  constructor(overlayContainer: OverlayContainer) {
    overlayContainer.getContainerElement().classList.add('unicorn-dark-theme');
  }
}
```
But the dialogs are always in dark theme. I want the dialogs have different color in different theme. How can I do it ?
![dark](https://user-images.githubusercontent.com/26711537/32034512-949980ae-ba45-11e7-99c7-ad0af66a18ce.png)
![light](https://user-images.githubusercontent.com/26711537/32034521-9c55723a-ba45-11e7-9356-24112a521445.png)

**Comment by YorkeCao** [comment]
@SamiAl90 I have find a way to take care of this. Just need to do `add('unicorn-dark-theme')` and `remove('unicorn-dark-theme')` in the right time. Thank you.

**Comment by trichetriche** [comment]
Should have warned about this too, my bad !

**Comment by Aimen7** [comment]
@YorkeCao Thank You.
