### ISSUE TITLE
mat-autocomplete fires onSelectionChange event twice

### ISSUE THREAD

**Issue by Swoox** [angular/material2#7851]
#### Bug, feature request, or proposal:
If I have a selected value and change the value the onSelectionChange will fire two events.
One with **isUserInput** **true** and one with **false**.
![image](https://user-images.githubusercontent.com/22318636/31669705-1764cd6e-b356-11e7-82ba-abd53341c7e5.png)
Both will fire soap request and the last soap request is the previous selected value (isUserInput = false).

#### What is the expected behavior?
Just one event.

#### What are the steps to reproduce?
It's hard to make a repro for this since I fill the static content with a soap call.
Here is the code I use to fix it:
`console.log(_event);
     if (_event.isUserInput === true) {
       this.makeParams(_index, _value);
     }`
HTML:
`<mat-form-field class="example-full-width">`
`<input matInput placeholder={{toolbar.fieldname}} class="form-control, input" 
          [matAutocomplete]="a" (input)="filterStatic($event.target.value, toolbar.fieldID,
toolbar.minlookupinputlength, toolbar.datasetref, toolbar.refid, toolbar.refarray)">  // trigger a filter`
`<mat-autocomplete #a="matAutocomplete">`
    `<mat-option *ngFor="let item of static[toolbar.fieldID]" [value]="item.name" (onSelectionChange)="setParams($event, i, item.id)">`
      `<span>{{ item.name }}</span>`
    `</mat-option>`
`</mat-autocomplete>`
`</mat-form-field>`
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version: 4.4.4
Angular material version: 2.0.0-beta.12

**Comment by willshowell** [comment]
This is expected behavior. A selection change includes `selection` and `deselection` of an option. When you select a different option, you are implicitly deselecting the old one.

You'd probably be interested in [`optionSelected`](https://material.angular.io/components/autocomplete/api).

**Comment by crisbeto** [comment]
Closing as a non-issue. @willshowell's comment is correct.
