### ISSUE TITLE
it's better to  select has a search property for large amount of data

### ISSUE THREAD

**Issue by alimashal** [angular/material2#7853]
#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by willshowell** [comment]
https://github.com/angular/material2/issues/2812 and https://github.com/angular/material2/pull/7835

**Comment by crisbeto** [comment]
Closing as a duplicate of #2812.
