### ISSUE TITLE
mat-slide-toggle

### ISSUE THREAD

**Issue by maxisam** [angular/material2#7854]
#### Bug, feature request, or proposal:

proposal: Can we have ngOnChanges in slide toggle to monitor dynamic toggle changes?

#### What is the expected behavior?

When changing the variable for the checked property, the toggle status should change correspondingly.

#### What is the current behavior?

It doesn't change

#### What is the use-case or motivation for changing an existing behavior?

when users toggle the slide-toggle, we would like to popup a modal and ask for comments. If users change their mind and hit cancel, we need to switch the slide toggle back to original status.

**Comment by MlleBeuze** [comment]
Hi @maxisam , I have the same issue today. Can you tell me how did you fix the problem as I can see you closed the issue :)?

Thank you,
Mélissa

**Comment by maxisam** [comment]
It was dead simple. `(change)="onHoldChanged($event)"` 

You can find it in the document here https://material.angular.io/components/slide-toggle/api

**Comment by MlleBeuze** [comment]
Oh actually my problem is a bit different then. I used the same method as you've just mentioned. 

My problem is, in my function onHoldChanged, the checked value (true/false) of the slider does not change. The same if I try directly try to set the checked value, the slider does not "slide".

**Comment by maxisam** [comment]
I don't think you can do that. You might wanna double check the source code, but I think `checked` is not an observer, so set checked value dynamic doesn't work. You need to use 
```
 @ViewChild(MatSlideToggle) _SlideToggle: MatSlideToggle;
 this._SlideToggle.toggle();
```

**Comment by MlleBeuze** [comment]
Oh thank you for the information! It works perfectly, thanks :)
