### ISSUE TITLE
Double Ripple on iPad

### ISSUE THREAD

**Issue by jbw91** [angular/material2#7856]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When tapping on buttons or tabs on an iPad, there should only be one ripple.

#### What is the current behavior?
When you tap on an `mat-raised-button` or `mat-tab` on an iPad it does two ripple effects. Once when you touchstart, and once on touchend. So you get a crazy double ripple effect.

#### What are the steps to reproduce?
Simply navigate to the [Angular Material Button Page](https://material.angular.io/components/button/overview) on an iPad and tap the buttons. A quick tap is not as obvious as a slower tap, but you can still see it.

#### What is the use-case or motivation for changing an existing behavior?
Unless I'm wrong, the material design spec never specifies it should have a double ripple effect on touch devices.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I first noticed the issue on Angular Material 2.0.0-beta.12. I'm not sure if it was an issue before that. Only tested on an iPad, but emulating a device in the Chrome Dev Tools shows this behavior as well.

**Comment by crisbeto** [comment]
This should be fixed in the next release by https://github.com/angular/material2/pull/7557.
