### ISSUE TITLE
mat-select producing 'error context' messages during unit test for beta.12

### ISSUE THREAD

**Issue by danwulff** [angular/material2#7864]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Unit tests utilizing OverlayContainer for testing functionality of mat-select to not produce console error messages

#### What is the current behavior?
When running the same style of unit test as is found in the material select .spec files, a large error message is produced. 

`ERROR: 'ERROR CONTEXT', DebugContext_{view: Object{def: Object{factory: ..., nodeFlags: ..., rootNodeFlags: ..., nodeMatchedQueries: ..., flags: ..., nodes: ..., updateDirectives: ..., updateRenderer: ..., handleEvent: ..., bindingCount: ..., outputCount: ..., lastRenderRootNode: ...}, parent: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ...}, viewContainerParent: null, parentNodeDef: Object{nodeIndex: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., flags: ..., checkIndex: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, context: Object{}, component: MatSelect`...

#### What are the steps to reproduce?
I created a github repo with a unit test that produces this error.

in a terminal:
`git clone https://github.com/danwulff/material-select-error-message`
`npm install`
`ng test`

#### What is the use-case or motivation for changing an existing behavior?
For Beta.11 and before, testing a select list this way worked just fine without any console errors. Beta.12 seems to now produce very large error messages. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
OS: Win 10 pro
Chrome: 61.0.3163.100 (Official Build) (64-bit)

angular-cli: 1.4.7
angular: 4.4.5
cdk/material: 2.0.0-beta.12
typescript: 2.3.4
jasmine: 2.8.0
karma: 1.7.1

#### Is there anything else we should know?
Material select .spec file mentioned before: https://github.com/angular/material2/blob/master/src/lib/select/select.spec.ts#L400

**Comment by josephperrott** [comment]
Closing as this is actually the reason that the tests for `MatSelect` is done in `fakeAsync`

The tests work as expected if you wrap them in `fakeAsync` as below:

```ts
it('should update the model when an option is clicked', fakeAsync(() => {
    const indexToTest = 2;
    expect(component.selected).toBe('');
    expect(component.dropdownList.length).toBeGreaterThan(indexToTest);

    const trigger: HTMLInputElement = fixture.debugElement.query(By.css('mat-select')).nativeElement;
    trigger.click();
    fixture.detectChanges();
    flush();

    const options = overlayContainerElement.querySelectorAll('mat-option') as NodeListOf<HTMLElement>;
    options[indexToTest].click();
    fixture.detectChanges();
    flush();
    expect(component.selected).toEqual(component.dropdownList[indexToTest]);
  }));
```

**Comment by danwulff** [comment]
@josephperrott Thanks for the reply. It looks like the test I originally copied in beta.12 was using `tick` and excluded `flush`. Updating to `flush` fixed the error messages.
