### ISSUE TITLE
mat-progress-spinner indeterminate mode is completely static in IE 11

### ISSUE THREAD

**Issue by mth654** [angular/material2#7867]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Progress spinner should spin when in indeterminate mode.

#### What is the current behavior?
The spinner is displayed as a static circle, does not move at all.
![spinner](https://imgur.com/2S74mMa.png)

#### What are the steps to reproduce?
Broken instance can be seen in the material guide: https://material.angular.io/components/progress-spinner/overview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Issue occurs in Angular 4.4.5, Material 2.0.0-beta12, TypeScript 2.5.3, Windows 7, and IE 11 (web-animations-js and classList polyfills are loaded)

#### Is there anything else we should know?
The progress bar works as expected in indeterminate and query mode.

**Comment by danwulff** [comment]
Also occurs on Edge browser: 
Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063

**Comment by donroyco** [comment]
Will be solved by #7599
