### ISSUE TITLE
bug: No value accessor for 'field'

### ISSUE THREAD

**Issue by drager** [angular/material2#787]
Hey, when trying to use `<md-input>` with `ngModel` I get the following error: `EXCEPTION: Error: Uncaught (in promise): No value accessor for 'email'`, so currently I cannot use `ngModel`, I instead do something like this:
```
(keyup)="user.email = email.value"
(change)="user.email = email.value"
``` 

But if I however change from `<md-input>` to only `<input>` it works just fine, therefore there is a problem with the `<md-input>` component.

Angular version: 2.0.0-rc.3
Angular material version:  2.0.0-alpha.5-2
Chrome version 48.0.2564.116 (64-bit) (Most likely same in other browsers)

Plunker can be found here: https://plnkr.co/edit/nLv0HiTknjOrdI62UrCp

**Comment by westor21** [comment]
I agree, same problem for me. This is not working with new form api, ngModel binding is not working, and the error is as descibed by drager.
Furthermore you have to specify a name attribute, if you use it with NgModel and inside a form. Please could you update the documentation?

**Comment by kara** [comment]
Thanks for reporting!  The current version of material is using imports from the deprecated forms module in `@angular/common`, so it isn't compatible with RC.3.  This has been fixed in master, and will be released in alpha.6.

**Comment by elvirdolic** [comment]
Same error happens also with alpha6 when using md-input

**Comment by kara** [comment]
Have you updated to the new forms module?

**Comment by drager** [comment]
@kara: I can verify that it works just fine with alpha6. Thanks for your time and work with the forms.
