### ISSUE TITLE
German Date format is not correct.

### ISSUE THREAD

**Issue by NishaVermaOH22** [angular/material2#7874]
#### Bug, feature request, or proposal:
German Date format is not correct.

#### What is the expected behavior?
I am trying to use German Date picker format in my project and the format currently supported is 1.1.2017. which is false. FYI .I have upgraded my project to material beta 12.

#### What is the current behavior?
It should ideally be for e.g. 01.01.2017.

#### What are the steps to reproduce?
http://plnkr.co/edit/t1yMm5DhUa2soxB82dWh?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material beta 12

#### Is there anything else we should know?
no

**Comment by jelbourn** [comment]
See https://material.angular.io/components/datepicker/overview#internationalization
