### ISSUE TITLE
Need migration guide for upgrading beta.11 to beta.12

### ISSUE THREAD

**Issue by oleksaz** [angular/material2#7876]
#### Bug, feature request, or proposal:
Please provide breaking changes log when migrating from beta.11 to beta.12

#### What is the expected behavior?
NO renaming of existing classes/components

#### What is the current behavior?
Everything is broken because of prefix change md* -> mat*

#### What are the steps to reproduce?
Create app with version beta.11 or lower - then upgrade to beta.12

**Comment by benb7760** [comment]
Read the [release notes](https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta12-marble-mustache-2017-10-05) and use the [prefix upgrader](https://www.npmjs.com/package/angular-material-prefix-updater)

**Comment by donroyco** [comment]
Please check the [changelog](https://github.com/angular/material2/blob/master/CHANGELOG.md). A heads up has been given that the `md-` prefix would be deprecated. 

In beta.11 release notes:

> In earlier betas, we've had a compatibility mode that allowed people to use either "md" or "mat" as the selector for Angular Material components. This was created so that these components could live side-by-side with AngularJS Material without CSS from the two libraries colliding.
>
> For beta.11, we've made the decision to deprecate the "md" prefix completely and use "mat" moving forward. This affects all class names, properties, inputs, outputs, and selectors (CSS classes were changed back in February). The "md" prefixes will be removed in the next beta release.
> 
>[You can automatically update your projects with the angular-material-prefix-updater tool](https://www.npmjs.com/package/angular-material-prefix-updater). Check out the tool's page for instructions on how to run.

**Comment by oleksaz** [comment]
Thanks for pointing
