### ISSUE TITLE
Toggle-slide : Blink value on loading form

### ISSUE THREAD

**Issue by stoto34** [angular/material2#7880]
#### Bug, feature request, or proposal:

When I load a page with a form with amodel, there is something weird with the toggle slider. In my model, the value is false but when I load the page, I can see the toggle slide "checked" (true) but it changes few milliseconds after to the the good value ("false").

(enabled fields is false)

`									<md-slide-toggle [(ngModel)]="enabled" name="enabled" color="primary">
										<div *ngIf="enabled">{{ 'category.enabled' | translate }}</div>
										<div *ngIf="!enabled">{{ 'category.disabled' | translate }}</div>
									</md-slide-toggle>`

#### What is the expected behavior?

It should display the correct value immediately

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4.3.6
Angular/material 2.0.0-beta.10

**Comment by willshowell** [comment]
Can you reproduce? Also try upgrading to beta.12

**Comment by stoto34** [comment]
I'll try beta 12 and up this post

**Comment by stoto34** [comment]
I updated my project to beta.12. Still the same problem. The value is not correct when the page is loading and then, when the page is totally loaded, the toggle change to the good value.

**Comment by willshowell** [comment]
What specifically do you mean by "when the page is totally loaded"? Are you using SSR or you have some ajax call that brings in the value after the app bootstrap?

**Comment by stoto34** [comment]
It's weird but i can't see the problem anymore. I can't explain it... my browser maybe :/
By the way, the data are loaded through an API call.

I think you can close it. Sorry about that
