### ISSUE TITLE
md-input - lack of possibility to turn off autocomplete

### ISSUE THREAD

**Issue by maciejsobala** [angular/material2#789]
#### Bug, feature request, or proposal:
putting autocomplete property to md-input

#### What is the expected behavior?
< md-input autocomplete="on/off"></mdinput> should be propagated to input element

#### What is the current behavior?
Lack of such mechanism

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.0.0-rc.3
Material: 2.0.0-alpha.5-2
Browsers: Safari, Chrome, FireFox
OS: OS X El Capitan, iOS 9.3

**Comment by joshfriend** [comment]
#447 added support for the `autoComplete` and [is present in the current `2.0.0-alpha.6` release.](https://github.com/angular/material2/blob/2.0.0-alpha.6/src/components/input/input.ts)

`autocorrect`, `autocapitalize`, and `spellcheck` attributes are still missing though.

**Comment by jelbourn** [comment]
It is currently `autoComplete` (camelCase). They should really match, though, so I opened #861
