### ISSUE TITLE
Strange scrolling when checkbox is inside accordion

### ISSUE THREAD

**Issue by eyalhakim** [angular/material2#7890]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Accordion body content should have the right height

#### What is the current behavior?
Accordion body content is scrollable with a smaller hight then needed

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
https://stackblitz.com/edit/angular-material2-issue-kjhbf6?file=app/app.component.html

**Comment by crisbeto** [comment]
Should be fixed in master by https://github.com/angular/material2/pull/7617.
