### ISSUE TITLE
Set mat-sidenav-container scrollbar

### ISSUE THREAD

**Issue by kenji-1996** [angular/material2#7892]
#### Bug, feature request, or proposal:
Change sidenav container scrollbar

#### What is the expected behavior?
Override the scrollbar with body { css } or something like this:
```
mat-sidenav-container::-webkit-scrollbar {
  width: 0.5em !important;
}

mat-sidenav-container::-webkit-scrollbar-track {
  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3) !important;
}

mat-sidenav-container::-webkit-scrollbar-thumb {
  background-color: darkgrey !important;
  outline: 1px solid slategrey !important;
}
```

#### What is the current behavior?
Nothing happens when I try either of these options

#### What are the steps to reproduce?
Ermm, Use side-nav-container with a normal sidenav and try and set the scroll bar

#### What is the use-case or motivation for changing an existing behavior?
Make it more easily customizable

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest version of all, Windows 10, x64 and testing on chrome (Note I can modify the scrollbar easily if I dont have a sidenav container

**Comment by kenji-1996** [comment]
Okay ermm I didnt expect this to fix it but it did, but its not exactly ideal because it applies to everything, which is fine for my needs but obviously not for all.

In Style.scss (or style.css depending on your settings)
I applied this:

```
*::-webkit-scrollbar {
  width: 0.5em;
}

*::-webkit-scrollbar-track {
  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}

*::-webkit-scrollbar-thumb {
  background-color: darkgrey;
  outline: 1px solid slategrey;
}
```

Which is simply setting all items to my custom scrollbar,  it used to be body,which works but not within mat-sidenav-container but this will

I assume you can probably just overrule these options where you want a custom scrollbar in particular divs or elements!

**Comment by mmalerba** [comment]
You can target `mat-sidenav-content` for this purpose, it's the element that actually scrolls: https://stackblitz.com/edit/angular-material2-issue-tvueuk?file=app/app.component.css

**Comment by benoitrolland** [comment]
My node_modules sorted by directory size demonstrates 
how specific the size of the material-design-icons package is,
(sole non "solution-" package largely above 10 megs)
and why it takes much longer to load. 
On the other hand dowloading 45 megs is must faster for a single file using http, 
than when installing  material-design-icons in a project, 
might any optimisation of the download process be possible ?

@angular                66 154 849
material-design-icons   45 865 755
@angular-devkit         34 242 642
typescript              26 290 298
then, 
between 10 and 5 megs:      2 packages
between  5 and 3 megs:      4 packages
between  3 and 2 megs:      3 packages
between  2 and 1 megs:     16 packages
between  1 megs and 500k : 19 packages
between  500k and 300k :   15 packages
between  300k and 200k :   18 packages
between  200k and 100k :   40 packages
between  100k and 50k :    55 packages
between  50k and 30k :     78 packages
between  50k and 30k :     78 packages
between  30k and 20k :     78 packages
between  20k and 15k :     77 packages
between  15k and 10k :     94 packages
between  10k and  7k :     92 packages
between   7k and  5k :    107 packages
between   5k and  3k :    54 packages
between   3k and  2k :     7 packages
