### ISSUE TITLE
Error: mat-form-field must contain a MatFormFieldControl.

### ISSUE THREAD

**Issue by icvanee** [angular/material2#7898]
#### Bug, feature request, or proposal:
When doing a karma/jasmine test I get an error on the <mat-form-field> tag.
This in combination with a <mat-select>

`<mat-form-field>
  <mat-select name="country" placeholder="Country" [(ngModel)]="address.countryName" class="input-full-width">
    <mat-option *ngFor="let country of countries | orderBy: 'name'" [value]="country.name">{{ country.name }}</mat-option>
  </mat-select>
</mat-form-field>
`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Using angular 4.4.5 material 2.0.0-beta.12 

#### Is there anything else we should know?
When running the project it's working okay, but just the test gives an error and fails.

**Comment by tomchovanec** [comment]
I have the same issue... Angular 4.4.6, material 2.0.0-beta.12

**Comment by tomchovanec** [comment]
You have to add to to app.module.ts:
```
import {MatInputModule} from '@angular/material';
@NgModule({
  imports: [
  ...
    MatInputModule
  ...
]


```

**Comment by icvanee** [comment]
As said, in the normal situation it work. I have added de MatInputModule in the imports section.
And when testing in the .spec.ts file I have imported the MatInputModule also. Even in the TestBed.configureTestingModule imports section is is added too.

**Comment by Abdullah-FAl** [comment]
You have to add matInput to  input 

  ```
<div class="fields-container">
        <mat-form-field>
          <input matInput placeholder="Input">
        </mat-form-field>
 
      </div>
```

**Comment by icvanee** [comment]
I know a matInput must be inside a mat-form-field. But the issue is that I don't want an input field, but a select.

**Comment by willshowell** [comment]
@icvanee to be sure, have you imported MatSelectModule into your testing module? And you don't have an ngIf on your mat-select, right?

**Comment by icvanee** [comment]
*shame* that was it. I really really thought I had added that. Imissed it when I was migrating also with the removal of MatModule. Thx for noticing!

**Comment by jagomf** [comment]
I have hadded MatSelectModule and I still get the error.

This is my component:

```
<mat-form-field>
  <mat-select [placeholder]="receivedLabel" [(ngModel)]="value" (blur)="onBlur()" class="select-country-main">
    <ng-template ngFor let-country [ngForOf]="countries" [ngForTrackBy]="trackByCountryId">
      <mat-option *ngIf="!isExcluded(country)" [value]="country">
        <country-flag [country]="country"></country-flag>
      </mat-option>
    </ng-template>
  </mat-select>
</mat-form-field>
```

**Comment by mattmcardle** [comment]
I had an issue similar to your @jagomf 
For me it was corrected when I modified the ngIf condition of my `mat-select`, I had `value !== null` in the ngIf, when I changed it to just `value` this fixed it. I would suggest setting an `excluded` property on your `country` objects, rather than calling the `isExcluded` method on your ngIf. You might also notice performance improvements if you do this, as referencing a method call in your html template causes it to be called on every change detection round.

**Comment by ORESoftware** [comment]
seems. like. the. error. message. could. be. improved.

**Comment by SekoViper** [comment]
i also have this same error and trying to fix but can't. Any help please.

<mat-form-field [floatLabel]="options.value.floatLabel">
        <mat-label>Tenant Name</mat-label>
        <input name="tenantName" ngModel="" matInput placeholder="Tenant Name" required>
      </mat-form-field>
    
      <mat-form-field 
          [hideRequiredMarker]="options.value.hideRequired"
          [floatLabel]="options.value.floatLabel">
        <mat-select required>
          <mat-option mdInput *ngFor="let room of roomType" value="option">{{room.name}}</mat-option>
        </mat-select>
        <mat-placeholder>-Select Room Type-</mat-placeholder>
      </mat-form-field>
</div>

but it keeps giving 

FusePricingStyle2Component.html:17 ERROR Error: mat-form-field must contain a MatFormFieldControl.
    at getMatFormFieldMissingControlError (form-field.es5.js:111)
    at MatFormField._validateControlChild (form-field.es5.js:637)
    at MatFormField.ngAfterContentInit (form-field.es5.js:392)
    at callProviderLifecycles (core.js:12699)
    at callElementProvidersLifecycles (core.js:12673)
    at callLifecycleHooksChildrenFirst (core.js:12656)
    at checkAndUpdateView (core.js:13806)
    at callViewAction (core.js:14153)
    at execComponentViewsAction (core.js:14085)
    at checkAndUpdateView (core.js:13808)

**Comment by Chan4077** [comment]
@SekoViper That's because you're using `mdInput` instead of `matInput`. Replace it.

**Comment by SekoViper** [comment]
Thanks very much. I have been able to fix that.
My next problem is to implement timer in a quiz app am building. How do I
go about it?
Thanks.

**Comment by sriharsha6** [comment]
<div class="col-md-5">
            <button (click)="!editMode=true">edit
            <i class="material-icons editicon">mode_edit</i>
          </button>
          <button (click)="!editMode=false">save
            <i class="material-icons check">check_circle</i>
          </button>
          </div>
        </div>
        <hr>
      
        <div class="row litre">
          <div class="col-md-6">
        <form class="litre">
            <mat-form-field class="example-full-width">
                <label *ngIf="!editMode">{{litre}}</label>
                <input matInput placeholder="Input" *ngIf="editMode" [(ngModel)]="litre"  [ngModelOptions]="{standalone: true}">
            </mat-form-field>
      </form>
      </div>

**Comment by mucbits** [comment]
Try this way:

        <mat-form-field class="example-full-width">
            <input matInput placeholder="Input" [disabled]="!editMode" [(ngModel)]="litre"  [ngModelOptions]="{standalone: true}">
        </mat-form-field>

**Comment by pierreclr** [comment]
Be sure that you don't have any `*ngIf` on your `input` / `select`

**Comment by sriharsha6** [comment]
can u send that code by using *ngIf on your input / select

**Comment by nhhockeyplayer** [comment]
Im receiving same issue numerous times within my custom mattable

**Comment by Ukmandal** [comment]
mat-form-field must contain a MatFormFieldControl
this is missing?  in app.module.ts 
  MatInputModule

**Comment by sriharsha6** [comment]
try to solve my issue

**Comment by pranaykohad** [comment]
I add MatInputModule in component's module.ts and it solve the problem

**Comment by zhupengfei910426** [comment]
just dont put any *ngIf into <mat-form-field>, you can put *ngIf into <div> tag or any tag above your <mat-form-field>.

**Comment by PaloMiklo** [comment]
Actually, I got this error, when a slash was missing in the second tag, which supposed to be a closing tag of <mat-form-field> element, so instead  <mat-form-field> use <**/**mat-form-field>. Silly error!

**Comment by Cricen** [comment]
I kept running into this when I trusted my IDE a bit too much.  I kept not noticing that rather than `matInput` I kept getting `mat-input`. It would be a bit helpful to have a better error message.

**Comment by danielprogramic** [comment]
Great Guys!!!! The **matInput** saving my life.

**Comment by MehdiRahimiN** [comment]
I have this problem too . and i have this problem with file type of input !

**Comment by sikemullivan** [comment]
I upgraded and forgot to change mdInput to matInput . SMH!! One of those moments lol

**Comment by Worthy7** [comment]
For some reason I always get this if I use an injected FormBuilder to build my form `this.fb.group...` but If I use `new FormGroup(...` it works - no error.

**Comment by gravindran2412** [comment]
`<mat-form-field>
                                            <mat-select placeholder="Select me">
                                              <mat-option value="option">Option</mat-option>
                                            </mat-select>
                                            <mat-hint align="end">Here's the dropdown arrow ^</mat-hint>
                                        </mat-form-field>
`

I am getting the following error on using mat-select:

ERROR Error: mat-form-field must contain a MatFormFieldControl.
    at getMatFormFieldMissingControlError (form-field.es5.js:115)
    at MatFormField.push../node_modules/@angular/material/esm5/form-field.es5.js.MatFormField._validateControlChild (form-field.es5.js:685)
    at MatFormField.push../node_modules/@angular/material/esm5/form-field.es5.js.MatFormField.ngAfterContentInit (form-field.es5.js:433)
    at callProviderLifecycles (core.js:9560)
    at callElementProvidersLifecycles (core.js:9541)
    at callLifecycleHooksChildrenFirst (core.js:9531)
    at checkAndUpdateView (core.js:10462)
    at callViewAction (core.js:10699)
    at execComponentViewsAction (core.js:10641)
    at checkAndUpdateView (core.js:10464)

**Comment by Worthy7** [comment]
You haven't imported it properly

**Comment by gravindran2412** [comment]
The following imports are available in app.module.ts:
import { MatSelectModule } from '@angular/material/select';
import { MatFormFieldModule } from '@angular/material/form-field';
import {  MatInputModule } from '@angular/material';

template:
`
 <mat-form-field>
                                            <mat-select placeholder="Select me">
                                              <mat-option value="option">Option</mat-option>
                                            </mat-select>
                                            <mat-hint align="end">Here's the dropdown arrow ^</mat-hint>
                                        </mat-form-field>
`

Error:
CarrierEditComponent.html:5 ERROR Error: mat-form-field must contain a MatFormFieldControl.
    at getMatFormFieldMissingControlError (form-field.es5.js:115)
    at MatFormField.push../node_modules/@angular/material/esm5/form-field.es5.js.MatFormField._validateControlChild (form-field.es5.js:685)
    at MatFormField.push../node_modules/@angular/material/esm5/form-field.es5.js.MatFormField.ngAfterContentInit (form-field.es5.js:433)
    at callProviderLifecycles (core.js:9560)
    at callElementProvidersLifecycles (core.js:9541)
    at callLifecycleHooksChildrenFirst (core.js:9531)
    at checkAndUpdateView (core.js:10462)
    at callViewAction (core.js:10699)
    at execComponentViewsAction (core.js:10641)
    at checkAndUpdateView (core.js:10464)

**Comment by hhsissi** [comment]
> You have to add to app.module.ts:
> 
> ```
> import {MatInputModule} from '@angular/material';
> @NgModule({
>   imports: [
>   ...
>     MatInputModule
>   ...
> ]
> ```

Thanks man, it's a real nightmare to use Angular Material when examples juste won't work because you can't figure out what to import...

**Comment by leolanese** [comment]
mat-form-field must contain a MatFormFieldControl. 
=
import {MatInputModule} from '@angular/material';
@NgModule({
  imports: [
  ...
    MatInputModule
  ...
]

**Comment by nhhockeyplayer** [comment]
still a nogo

have all modules imported

```
        <mat-form-field color="accent">
            <app-states [newState]="modal.data.state"></app-states>
        </mat-form-field>
```

**Comment by ipsjolly** [comment]
Even after adding **MatFormFieldModule**, **MatInputModule**, **FormsModule** I was facing this issue

_ERROR Error: mat-form-field must contain a MatFormFieldControl._

This issue is caused if the input field is not having **[formControl]**

    <mat-form-field> 
     <input type="text" matInput [formControl]="myControl" [matAutocomplete]="auto">
    </mat-form-field>

In class component add **myControl = new FormControl();**


	// app.component.ts
	import { Component } from '@angular/core';
	import { FormControl } from '@angular/forms';

	@Component({
	  selector: 'app-root',
	  templateUrl: './app.component.html',
	  styleUrls: ['./app.component.css']
	})
	export class AppComponent {
	  title = 'ng-autocomplete';
	  myControl = new FormControl();
	  options: string[] = ['One', 'Two', 'Three'];
	}

Source [link](https://www.freakyjolly.com/angular-7-6-add-autocomplete-in-angular-application-using-angular-material/)

**Comment by Wess58** [comment]
> I had to place that *ngIf on the `<mat-form-field>` tag instead of any tag inside that. This was driving me nuts... 
> `<mat-form-field *ngIf="config.type === 'string'" class="field-full-width"> <input type="text" matInput placeholder="{{config.name}}" [formControlName]="config.name"> </mat-form-field>`

THANKS A MILLION , THIS IS THE SOLUTION I WAS SCOUTING FOR

**Comment by robert-john-concepcion** [comment]
I think this [link ](https://v5.material.angular.io/components/form-field/overview#error-mat-form-field-must-contain-a-matformfieldcontrol)will help.

**Comment by gh0st** [comment]
This was failing for me because I hadn't imported the `MatInputModule` inside my `.spec.ts` file.
