### ISSUE TITLE
Drop support for legacy IE versions(< 11)

### ISSUE THREAD

**Issue by harsimranmaan** [angular/material2#79]
According to [Microsoft](https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=Internet%20Explorer&Filter=FilterNO), only the latest version of IE is supported since Jan 12, 2016. And since this project is still in early stages, it would not be a bad move to drop support for older IE versions(<  IE11) and plan for a less hacky implementation.

**Comment by beaverusiv** [comment]
Angular supports IE9+. I think it would be proper to be inline with their support?
https://angular.io/features.html
> In addition to fully supporting latest versions of Chrome, Edge, Firefox, IE, and Safari, Angular 2 is also tested for older browsers including IE9+ and Android 4.1+.

**Comment by jelbourn** [comment]
As [the README](https://github.com/angular/material2) states, we already don't support less than IE10.
