### ISSUE TITLE
spinner indeterminate animation doesn't work microsoft edge

### ISSUE THREAD

**Issue by pasblin** [angular/material2#7900]
#### Bug, feature request, or proposal:
bug
#### What is the expected behavior?
see an animation
#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by donroyco** [comment]
Please use the search function before opening a known issue. This has been noted in #7867 and #7599 and will be solved by PR #7599

**Comment by crisbeto** [comment]
Closing as fixed by #7599.
