### ISSUE TITLE
Build Error: @angular/material/material has no exported member

### ISSUE THREAD

**Issue by wojtek1150** [angular/material2#7901]
#### Bug, feature request, or proposal:
Build is crashing

#### What is the expected behavior?
Webpack is able to correctly import Material2 modules

#### What is the current behavior?
Webpack is not finding the export definitions

#### What are the steps to reproduce?
Update angular material to 2.0.0-beta.12
![image](https://user-images.githubusercontent.com/5401942/31768821-4394bbac-b4d1-11e7-8167-e86ecf42f008.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
@angular/cli: 1.4.8
node: 6.10.3
os: win32 x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/compiler-cli: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/platform-server: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.8
typescript: 2.4.0
```

**Comment by willshowell** [comment]
Can you try deleting your node modules and reinstalling?

**Comment by wojtek1150** [comment]
Thx. Fully deleting modules and reinstalling helps. Also i reinstall angular-cli globally and now works
