### ISSUE TITLE
Progress Spinner is not working in angular material v2.0.0-beta.12

### ISSUE THREAD

**Issue by yugi03** [angular/material2#7904]
#### Bug:  
Progress spinner is not working in v2.0.0-beta.12. I am getting an error as:

    compiler.es5.js:1689 Uncaught Error: Can't resolve all parameters for MatProgressSpinner: 
    ([object Object], [object Object], [object Object], ?).
        at syntaxError (compiler.es5.js:1689)

Also, Angular cli is throwing a warning as:

    WARNING in ./node_modules/@angular/material/esm5/progress-spinner.es5.js
    230:83-91 "export 'DOCUMENT' was not found in '@angular/common'

I checked the above file which is `./node_modules/@angular/material/esm5/progress-spinner.es5.js` and realised that it is trying to `import { DOCUMENT } from '@angular/common';` which is possibly not present in the version of angular common (v4.2.4), which I am using right now.

After commenting out this line, angular cli stopped throwing an error, but progress spinner is not working as this is required dependency for it.

#### What is the current behavior?
angular cli build is throwing warning and progress spinner is not working

#### What are the steps to reproduce?
Updating angular material from 2.0.0-beta.11 to 2.0.0-beta.12.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    "dependencies": {
      "@angular/animations": "4.2.4",
      "@angular/cdk": "2.0.0-beta.12",
      "@angular/common": "4.2.4",
      "@angular/compiler": "4.2.4",
      "@angular/core": "4.2.4",
      "@angular/forms": "4.2.4",
      "@angular/http": "4.2.4",
      "@angular/material": "2.0.0-beta.12",
      "@angular/platform-browser": "4.2.4",
      "@angular/platform-browser-dynamic": "4.2.4",
      "@angular/router": "4.2.4",
      "core-js": "2.4.1",
      "rxjs": "5.4.2",
      "zone.js": "0.8.14"
    },
    "devDependencies": {
      "@angular/cli": "1.3.2",
      "@angular/compiler-cli": "4.2.4",
      "@angular/language-service": "4.2.4",
      "@types/jasmine": "2.5.53",
      "@types/jasminewd2": "2.0.2",
      "@types/node": "6.0.60",
      "codelyzer": "3.1.1",
      "jasmine-core": "2.6.2",
      "jasmine-spec-reporter": "4.1.0",
      "karma": "1.7.0",
      "karma-chrome-launcher": "2.1.1",
      "karma-cli": "1.0.1",
      "karma-coverage-istanbul-reporter": "1.2.1",
      "karma-jasmine": "1.1.0",
      "karma-jasmine-html-reporter": "0.2.2",
      "protractor": "5.1.2",
      "ts-node": "3.2.0",
      "tslint": "5.3.2",
      "typescript": "2.3.3"
    }

**Comment by willshowell** [comment]
`@angular/material` has the following peer dependencies

    "@angular/cdk": "2.0.0-beta.12",
    "@angular/core": "~4.4.4",
    "@angular/common": "~4.4.4"

**Comment by yugi03** [comment]
Hello @willshowell : Thanks for informing about this. Let me try this once to check if it is working for me or not.  I am wondering if it is documented somewhere? I didn't find peer dependency of this anywhere.

**Comment by willshowell** [comment]
No, but you should have received a warning during `npm install`.

**Comment by yugi03** [comment]
Oh yes! I missed that warning message while doing `npm install`. I installed peer dependencies and and now it is working. Thanks @willshowell
