### ISSUE TITLE
CDK cdkObserveContent event does NOT fire in a custom directive

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#7926]
#### Bug, feature request, or proposal:

How to get `cdkObserveContent` event to work in a directive without using `(cdkObserveContent)` in component template

#### What is the expected behavior?

The event should fire when content changes

#### What is the current behavior?

The event in the directive does NOT fire when content of the host element changes but it works when you add `(cdkObserveContent)` in the component template

#### What are the steps to reproduce?

[StackBlitz](https://stackblitz.com/edit/angular-material2-issue-7knm5w?file=app%2Ftest-directive.directive.ts)

Click on "Test CDK" button to see the event firing properly (check the console), then remove the `(cdkObserveContent)` from the template and click on the button again. you will see the directive is not firing the event anymore

#### What is the use-case or motivation for changing an existing behavior?

Get **cdkObserveContent** to work in directives using ` @HostListener('cdkObserveContent')` without the need to add (cdkObserveContent) in the template

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material beta 12
Angular 4.4.5

**Comment by crisbeto** [comment]
The event doesn't fire, because the `cdkObserveContent` listener doubles as the directive selector. Angular doesn't allow for directives to be applied via the `host` metadata. It might makes sense to support attaching the observer programmatically though, we have something similar for the focus trap already.

**Comment by MurhafSousli** [comment]
@crisbeto Do you know a workaround to attach the `cdkObserveContent` directive programmatically from my custom directive?

**Comment by jelbourn** [comment]
Unfortunately Angular itself doesn't support this now. The fallback would be to use `MutationObserver` directly.
