### ISSUE TITLE
[Tooltip] Allow app level tooltip show and hide delay configuration

### ISSUE THREAD

**Issue by Karankang007** [angular/material2#7928]
#### Feature request:
Allow developers to configure global tooltip show/hide delay.

#### What is the expected behavior?
Provide InjectionTokens for easier app-level configuration of tooltip show and hide delay.

#### What is the current behavior?
Currently, tooltip delay can be configured on per component basis using the matTooltipShowDelay and  matTooltipHideDelay attributes, but this is very verbose.

#### What is the use-case or motivation for changing an existing behavior?
Consistency and ease of use.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material Beta 12

**Comment by Simon-edu-Sharing** [comment]
Any news on this? Can the pull request be merged?
