### ISSUE TITLE
mat-tab adding custom animation to the content of a tab will remove the content from the DOM when browsing to a new tab

### ISSUE THREAD

**Issue by HashSix** [angular/material2#7931]
#### Bug:
Mat-tab adding custom animation to the content of a tab will remove the content from the DOM when browsing to a new tab, but only if the element with the animation is surrounded by another element, in this case it is a `<div>`

#### What is the expected behavior?
For the content to stay in the tab when selecting a new tab so then when go back to the previous tab the content is still there.

#### What is the current behavior?
The content gets removed when adding custom animation to an element within the mat-tab

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-product-load-nwff6w

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material v2.0.0.beta12

**Comment by amcdnl** [comment]
@josephperrott - I dug in, this might be a animation bug. Everything seems to work if you remove animations ( just remove the `@slideUp` attribute and you will see it works ).

cc/ @matsko

**Comment by josephperrott** [comment]
Closing as it looks like this was actually fixed by the latest release.
