### ISSUE TITLE
CDK Overlay how to attach component with parameters

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#7936]
#### Bug, feature request, or proposal:

How to attach a component to `Overlay` if the component has parameters in its constructor?

The docs only cover a component without a parameters
```ts
const overlayRef = overlay.create();
const userProfilePortal = new ComponentPortal(UserProfile);
overlayRef.attach(userProfilePortal);
```

#### What is the expected behavior?

A way to resolve component's parameter

#### What is the current behavior?

Attaching a component that has parameters throws this error 
`Error: Can't resolve all parameters for PopUpComponent: (?).`

#### What are the steps to reproduce?

[StackBlitz](https://stackblitz.com/edit/angular-material2-issue-q83uxr?file=app%2Fpop-up%2Fpop-up.component.ts)

Go to **PopUpComponent** and uncomment the constructor to get the error

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material Beta 14
Angular 4.4.5

**Comment by MurhafSousli** [comment]
I created a wrapper component that doesn't have any parameters

**Comment by ermarkar** [comment]
Can you please show, how?
