### ISSUE TITLE
cannot include multiple umd build when using secondary entry points.

### ISSUE THREAD

**Issue by aitboudad** [angular/material2#7947]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should work

#### What is the current behavior?
I get the following error:
```console
Template parse errors:
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: MatFormField,MatFormField
```

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-uhapma?file=app%2Fapp.module.ts

just import input and select modules and include form-field in component template:

```ts
...
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';

@NgModule({
  imports: [
    MatInputModule,
    MatSelectModule,
  ]
})
export class AppModule {}

@Component({
  selector: 'material-app',
  template: `
    <mat-form-field class="example-full-width">
      <input matInput placeholder="Favorite food" value="Sushi">
    </mat-form-field>
  `
})
export class AppComponent { 
  version = VERSION;
}
```

**Comment by 1ik** [comment]
`import { MatInputModule, MatSelectModule } from '@angular/material';` doesn't break.

**Comment by Basel78** [comment]
Hello,
I am facing the same issue when using material 2 in angular 5.2.X , and couldn't find the solution, what I need to do to resolve this issue,.

Thanks
