### ISSUE TITLE
md-input placeholder text is partially hidden

### ISSUE THREAD

**Issue by Saegrov** [angular/material2#795]
#### Bug, feature request, or proposal:
 Bug introduced in the latest alpha-6. I'm not sure if I'm using it wrong or if this is expected behaviour.

#### What is the expected behavior?
Current behaviour in alpha-5
![expected](https://cloud.githubusercontent.com/assets/124469/16518031/0787d502-3f81-11e6-9131-647002ca3552.gif)

#### What is the current behavior?
After upgrading to alpha-6
![bug](https://cloud.githubusercontent.com/assets/124469/16516925/0ff13270-3f7b-11e6-88c0-d1a5e6d6d3af.gif)

#### What are the steps to reproduce?
Using md-input. 

#### Which versions of Angular, Material, OS, browsers are affected?
Using Angular RC-3, Material alpha-6. 
It's affected in Safari, Firefox and Chrome on OSX. Haven't tested other browsers.

#### Is there anything else we should know?
Introduced in the following commit: https://github.com/angular/material2/commit/cf2703c91185aee05c12d1791a42d1d9b72ed431
Disabling the `overflow: hidden` on the `:host`selector for md-input solves the issues.

![screen shot 2016-07-01 at 11 58 38](https://cloud.githubusercontent.com/assets/124469/16518460/31884c7c-3f83-11e6-8639-76b6687353d6.png)

**Comment by MoxxNull** [comment]
Doesn't seem to happen on Chrome / Firefox / Edge in Windows  (Angular2 RC4 & Material2 alpha 6)

**Comment by Saegrov** [comment]
I'll see if I can make a plunkr or repo to reproduce it. Is there any plunkr template that has the latest alpha? The one in the Readme seems to have the alpha-5: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/lTdUX1SyRR1wl9lptS3k?p=preview

**Comment by Zyzle** [comment]
I'm seeing a similar behaviour with the hint labels after upgrading to alpha-6 but cant seem to reproduce it in @DzmitryShylovich's plunk it is however present on the material demo app.

**Comment by Saegrov** [comment]
@DzmitryShylovich Are you sure this includes the latest input? It seems the `overflow:hidden` property isn't the plunkr.

I created a repo to demonstrate it:
https://github.com/Saegrov/angular-2-input-bug

Apologies for the large repo to demonstrate a rather small bug (i just used the angular-2-webpack-starter).

**Comment by RoxKilly** [comment]
I observe the same thing with input hints. I'm using Angular RC4, Material Alpha 6, on Firefox 48 Beta.
![4](https://cloud.githubusercontent.com/assets/12346501/16616356/a713aa8e-434a-11e6-8453-d9af06927eed.png)
I can also confirm that removing `overflow:hidden` rule from `<md-input>` resolves the issue

**Comment by msegers** [comment]
Same here, I just currently slapped a md-input { overflow: visible !important; } in my css.

**Comment by Bifros7** [comment]
I'm experiencing the issue with hidden hint labels aswell.

**Comment by kara** [comment]
@Saegrov  I can confirm this is cut off in iOS Safari as well. The fix you suggested seems right at first glance (@hansl will have to take a look).   Just submitted a quick PR with the change.
