### ISSUE TITLE
Ability to display tooltip on disabled button / element

### ISSUE THREAD

**Issue by thefliik** [angular/material2#7953]
#### Bug, feature request, or proposal:
feature (maybe bug)

#### What is the expected behavior?
Ability to display tooltip on disabled button / element.

e.g.
```
<button mat-button matTooltip="first enter email address" disabled [matTooltipDisabled]=false>
  Next
</button>
```
or
```
<button mat-button matTooltip="first enter email address" [matButtonDisabled]=true>
  Next
</button>
```

#### What is the current behavior?
Both tooltip and button are disabled using `disabled` input attribute. In order to _just disable_ one or the other, you must use a helper element to split the component up.

e.g.
```
<span matTooltip="first enter email address">
  <button mat-button  [disabled]=true>
    Next
  </button>
</span>
```

#### What are the steps to reproduce?
See [https://stackblitz.com/edit/angular-material2-issue](https://stackblitz.com/edit/angular-material2-issue)

```
<button mat-button matTooltip="first enter email address" disabled [matTooltipDisabled]=false>
  Next
</button>
```
In the above, the both the button and the tooltip are disabled.

#### What is the use-case or motivation for changing an existing behavior?
Ability to _just disable_ a `button` / form element & not disable its associated `tooltip`, or vice-versa. E.g. this is useful if you'd like the tooltip to explain why the button is disabled. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular: 4.4.6
material: 2.0.0-beta.12

#### Is there anything else we should know?

**Comment by ghd8** [comment]
see #5040

**Comment by thefliik** [comment]
@ghd8 thanks. Disappointing.
