### ISSUE TITLE
Feature request: Google APIs' native support

### ISSUE THREAD

**Issue by Harshul-Vijay** [angular/material2#7955]
#### Bug, feature request, or proposal:
I want a feature in Angular2.

#### What is the expected behavior?
We cannot use Google APIs natively in Angular, whereas the Polymer Project has it's own tags to use Google APIs. I would like to see the same in Angular, because I like Angular more than Polymer, atleast for now.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Every possible version.

**Comment by baruchvlz** [comment]
You might want to try posting this in the [Angular](https://github.com/angular/angular) repository. This repository is for the Material library.

**Comment by jelbourn** [comment]
This is indeed out of scope for Angular Material, which is specially for Material Design UI components.
