### ISSUE TITLE
Matselect -  Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by theunreal** [angular/material2#7959]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
No error when changing mat-select value

#### What is the current behavior?
The following error throws when updating mat-select option:

```
MatSelect.webpackJsonp.../../../material/esm5/select.es5.js.MatSelect._onFadeInDone (select.es5.js:744)
    at Object.eval [as handleEvent] (MatSelect.html:1)
    at handleEvent (core.js:13254)
    at callWithDebugContext (core.js:14739)
    at Object.debugHandleEvent [as handleEvent] (core.js:14326)
    at dispatchEvent (core.js:9703)
    at core.js:10317
    at animations.js:348
    at Array.forEach (<anonymous>)
    at animations.js:346
```

#### What are the steps to reproduce?
```
<mat-form-field>
  <mat-select placeholder="packs..." [(ngModel)]="sPack">
    <mat-option *ngFor="let pack of packs">{{ pack.name }}</mat-option>
  </mat-select>
</mat-form-field>
```

#### What is the use-case or motivation for changing an existing behavior?
Bugfix

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 5.0.0-rc.3
Material - beta.12
OS - Windows
TS - 2.4.2
browsers - all

#### Is there anything else we should know?
none

**Comment by crisbeto** [comment]
Should be fixed in master by https://github.com/angular/material2/pull/7729.

**Comment by KthProg** [comment]
Is this in a new version that I can pull down? I'm having this issue right now as well.

**Comment by crisbeto** [comment]
5.0.0-rc.0 includes the fix @KthProg.

**Comment by KthProg** [comment]
Thank you kind sir.

**Comment by alan345** [comment]
The new rc for 5 contains the fix:

```
"@angular/material": "^5.0.0-rc0",
"@angular/cdk": "^5.0.0-rc0",
```
https://github.com/angular/material2/pull/7729

**Comment by costea93** [comment]
I updated the material and cdk to 5.0.0-rc0 version but the problem it's still reproducible in my case

**Comment by j-tee** [comment]
Having the same issue here with 5.0.0-rc.3

**Comment by dreddstev** [comment]
Issue fixed for me by updating material and cdk to 5.0.2

**Comment by costea93** [comment]
`"@angular/animations": "^5.2.5",
        "@angular/cdk": "^5.2.1",
        "@angular/common": "^5.2.5",
        "@angular/compiler": "^5.2.5",
        "@angular/core": "^5.2.5",
        "@angular/forms": "^5.2.5",
        "@angular/http": "^5.2.5",
        "@angular/material": "^5.2.1",
        "@angular/platform-browser": "^5.2.5",
        "@angular/platform-browser-dynamic": "^5.2.5",
        "@angular/router": "^5.2.5"`

The issue it's still reproducible for me :(

**Comment by SalsabeelNasr** [comment]
me too 
 "@angular/animations": "^5.2.9",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.4",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.9",
    "@types/materialize-css": "^1.0.1",
    "angular2-materialize": "^15.1.10",
    "core-js": "^2.5.4",
    "jquery": "^3.3.1",
    "materialize-css": "^0.100.2",
    "mdi": "^2.1.19",
    "ng2-material-import": "^1.1.10",
    "rxjs": "^5.5.8",
    "zone": "^0.3.4",
    "zone.js": "^0.8.21"
