### ISSUE TITLE
Sass still unavaliable in alpha.6

### ISSUE THREAD

**Issue by TheCaptainDate** [angular/material2#796]
Sass inside packages are still broken.

There is css and scss files now with same name, so `@import` inside scss files of material2 don't know which file should be imported (css or scss), and returns an error.

I think this can be fixed if you put extensions in scss files of material 2, or remove all css files from the package styles dir (move somewhere).

One more time:
I am trying to import variables.scss like:
```sass
@import "node_modules/@angular2-material/core/style/variables.scss";
```
and get error:
```
Error: It's not clear which file to import for '@import "theme-functions"'.
Candidates:
  _theme-functions.scss
  _theme-functions.css
Please delete or rename all but one of these files.
```

This error comes from your variables.scss
I also pointed this error earlier: https://github.com/angular/material2/issues/533#issuecomment-223513305

**Comment by SamClockwork** [comment]
Hey,

try uninstalling and reinstalling the core package. The SASS file is around now.

![image](https://cloud.githubusercontent.com/assets/2729205/16527299/41ced280-3fb6-11e6-8eed-f73f67173161.png)

**Comment by SamClockwork** [comment]
+1 on that. The @import method looks for .scss and .css and since there is both it's doesn't know which file to import.

**Comment by peterwiebe** [comment]
I ended up deleting all of the CSS files, problem is when you update to the latest version it brings them back so you have to go through and delete them again.

**Comment by robkuijpers** [comment]
+1
Please add .scss extentions to @import or put .scss and .css files in different folders.

**Comment by msegers** [comment]
Seems like it's not a big hassle to get this working. Monitoring this thread for changes.

**Comment by jelbourn** [comment]
Closing this since theming is available now.
