### ISSUE TITLE
MatDialogRef.updateSize() is not working as expected

### ISSUE THREAD

**Issue by playground** [angular/material2#7965]
MatDialogRef.updateSize() changes the size of the dialog but the content becomes scrollable instead of using the new size. 

#### What is the expected behavior?
The dialog content should be resize to the specified size

#### What is the current behavior?
Content is getting clipped off

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-tjj2ha

**Comment by amcdnl** [comment]
Looks like it is resizing but you have a parent div that its constraining it. ( the div w/ `confirmWithPayload` switch on it ).

**Comment by playground** [comment]
@amcdnl I tried it without switch div around it, it's still behaving the same way.

**Comment by willshowell** [comment]
@playground this is because you placed `mat-dialog-actions` inside `mat-dialog-content`. If you move it outside, it works fine.

**Comment by playground** [comment]
@willshowell yep, that works. Thx.
