### ISSUE TITLE
`bottom-sheet` feature request

### ISSUE THREAD

**Issue by amareshteja** [angular/material2#7966]
Hello,

We are using Angular 4 with Angular Material for our new project. Now, we got a requirement that can be done using `bottom-sheet` feature. But unfortunately it's not available yet. Will it be released any time soon? 
If **yes**, How much time does it takes?
If **no**, Is there any third party alternative that I can use temporarily?

**Comment by TheRedD0t** [comment]
As described in the [README.md](https://github.com/angular/material2/blob/master/README.md) the status of the bottom-sheet is 
> Not started, not planned

**Comment by jelbourn** [comment]
Created #8113 as the canonical tracking issue. We have no plans / schedule for this component in Angular Material at this time.
