### ISSUE TITLE
Allow customizing month format in year view in datepicker

### ISSUE THREAD

**Issue by princemaple** [angular/material2#7967]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
be customizable

#### What is the current behavior?
hard coded [here](https://github.com/angular/material2/blob/master/src/lib/datepicker/year-view.ts#L114)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-1v3qbw?file=app%2Fapp.component.ts

#### What is the use-case or motivation for changing an existing behavior?
![image](https://user-images.githubusercontent.com/1329716/31875355-896fda1c-b819-11e7-832a-d9b884bee41b.png)

`short` month in Chinese is just a number followed by a character. `long` month isn't very long anyway and is more suitable as the month label for the year view.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
beta12

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/1329716/31875368-968c2ce6-b819-11e7-90f6-f7802f046bc9.png)

Would love an option to render `day` in pure number. Both `numberic` and `2-digit` `day` in Chinese, much like `short` `month`, are just a number followed by a character. However, we all understand it without the character just fine. The character being there is very annoying and extraneous, but there isn't a format `Intl` provides that is without the character there.

**Comment by mmalerba** [comment]
@princemaple you can accomplish this by extending the `NativeDateAdapter` and providing your customized adapter in the app module: https://stackblitz.com/edit/angular-material2-issue-afqg57?file=app/app.component.ts
