### ISSUE TITLE
img link should be start from https.

### ISSUE THREAD

**Issue by praveeno** [angular/material2#7968]
https://github.com/angular/material2/blob/76a6e7beab28a30d6c215600e1122808049ed83c/src/material-examples/card-fancy/card-fancy-example.html#L7
![image](https://user-images.githubusercontent.com/19618730/31879922-89e1563c-b7fc-11e7-97a7-881a407fa174.png)
chrome give error that
>Mixed Content: The page at 'https://material.angular.io/worker-basic.min.js' was loaded over HTTPS, but requested an insecure resource 'http://material.angular.io/assets/img/examples/shiba2.jpg'. This request has been blocked; the content must be served over HTTPS.

**Comment by TheRedD0t** [comment]
Duplicate of https://github.com/angular/material2/issues/7757; PR #7800

**Comment by praveeno** [comment]
fixed in #7762, should be close this.
