### ISSUE TITLE
Mat-Chip default color always shown

### ISSUE THREAD

**Issue by DenSchiep** [angular/material2#7971]
The color property of a chip component seems to stay default.

When the color property is set primary, accent or warn, the color won't change on version 2.0.0-beta.12 .
[plunk-LSgU9X5sYVhx4bc3LBWm (1).zip](https://github.com/angular/material2/files/1406475/plunk-LSgU9X5sYVhx4bc3LBWm.1.zip)

**Comment by amcdnl** [comment]
@DenSchiep - In the future a link to the live plunker would be preferred.

**Comment by josephperrott** [comment]
Closing as fixed by #7285

**Comment by nayfin** [comment]
I'm experiencing the same behavior if I don't set selected to true. Is this the expected behavior?

**Comment by wellwind** [comment]
@nayfin According to the Theme section of document, the color means the selected color, so it must be set `selected="true"`

https://material.angular.io/components/chips/overview#theming

**Comment by kamok** [comment]
@wellwind If selected means selected="true", and clicking on it does not trigger selected, then this is indeed fixed. Kinda weird that you don't have a selected color and a base color. Guess yall want us to do css for that. Needs to be in docs.
