### ISSUE TITLE
Autocomplete focus when inside a dialog

### ISSUE THREAD

**Issue by Swoox** [angular/material2#7972]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When opening a dialog the autocomplete doesn't have focus.
Expected: https://angular-qgx8sh.stackblitz.io/

#### What is the current behavior?
When opening a dialog my autocomplete get focussed.

#### What are the steps to reproduce?
Just open a dialog with data of the states in it:
`this.dialog.open(SlideInToolbar, {
            width: '150px',
            data: { states: this.states }
        });`

And inside the dialog an autocomplete with:
`<mat-option *ngFor="let item of data.states" [value]="item.name">`

https://angular-omzvev.stackblitz.io/

#### What is the use-case or motivation for changing an existing behavior?
I want to implement a autocomplete in a dialog without focus.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.4
Material: 2.0.0-beta.12

**Comment by amcdnl** [comment]
This is working by design. 

https://github.com/angular/material2/blob/master/src/lib/dialog/dialog-container.ts#L150

When the dialog opens it needs to switch the focus from the button that initiated the dialog the a focusable element in the dialog ( your input in this case ). 

You can get around this by adding `tabindex="-1"` to the input like so: https://stackblitz.com/edit/angular-rrfabk

**Comment by Swoox** [comment]
Cheers this works for me.

**Comment by debslord** [comment]
Workaround does work a bit of a hack as it's a shame this then means the autocomplete cannot be tabbed to

**Comment by Swoox** [comment]
Restores focus to the element that was focused before the dialog opened. This kind is false in this situation but yeah I agree it's a workaround.

**Comment by willshowell** [comment]
Depending on your situation, a better solution may be to add `cdk-focus-initial` to whichever element you want to focus first.

```html
<div mat-dialog-content cdk-focus-initial> ... </div>
```

https://stackblitz.com/edit/angular-tksjrg?file=app%2Ftoolbar.html

**Comment by debslord** [comment]
That's a better solution for me, great thank you!
