### ISSUE TITLE
Select form gets sluggish and not responsive  

### ISSUE THREAD

**Issue by azizalali** [angular/material2#7974]
I have raised this issue [in more details here](https://stackoverflow.com/questions/46882661/angular-material-causing-components-rendering-repeatedly-when-navigation). The dropdown list shows with no problem. Once an item is selected, the whole menu gets sluggish and not responsive unless page is refreshed. 

Any idea?

**Comment by willshowell** [comment]
Can you create a reproduction?

**Comment by azizalali** [comment]
yes!

**Comment by jelbourn** [comment]
Duplicate of #5113 

(I assume for lack of other information)
