### ISSUE TITLE
Textarea float never

### ISSUE THREAD

**Issue by bharathmuppa** [angular/material2#7980]
Bug: on setting floatPlaceholder to "never" on textarea with matInput makes placeholder stay while entering data instead of acting as plain placeholder.

#### What is the expected behavior?
when we set floatPlaceholder to never placeholder on textarea should
act as genral placeholder
#### What is the current behavior?
Placeholder is not dissapearing while typing data

#### What are the steps to reproduce?
`   <mat-form-field fxFlex="1 1 75%" floatPlaceholder="never" fxFlex.xs="100%">
          <textarea matInput [formControl]="someCtrl" placeholder="Please define the dependencies"></textarea>
        </mat-form-field>`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4,Material beta12, all browsers

**Comment by DevVersion** [comment]
Can you please share a reproduction? (using StackBlitz or Plunker)

**Comment by jelbourn** [comment]
@DevVersion did you try this and were unable to reproduce? If so, feel free to mark it as `cannot reproduce` and close

**Comment by DevVersion** [comment]
I wasn't able to reproduce this issue. The issue only seems to appear if the `[formControl]` is not being initialized.

**Comment by finalxcode** [comment]
https://material.angular.io/components/form-field/overview#floating-placeholder
