### ISSUE TITLE
mat-select should close when escape is pressed, also stop propagation

### ISSUE THREAD

**Issue by alex-okrushko** [angular/material2#7981]
#### Bug, feature request, or proposal:
bug?

#### What is the expected behavior?
when mat-select is open and escape is pressed it should close the select

#### What is the current behavior?
select doesn't close and the element upstream gets the escape. In my case the mat-drawer catches this Escape which results in weird behavior: drawer closes, and the opened select is floating outside of it (because it's part of the cdk-portal).

#### What are the steps to reproduce?
http://plnkr.co/edit/vtBv4N8p0o4hzFetaOGx?p=preview

Open drawer
Click the selector
Press ESC

**Comment by alex-okrushko** [comment]
![e14626e2-0697-44bc-bae1-8014b157f927](https://user-images.githubusercontent.com/2830407/31911691-7dfb0c60-b80f-11e7-98b3-12e9e72af851.gif)

**Comment by crisbeto** [comment]
Closing as something that will be resolved by https://github.com/angular/material2/pull/8531.

**Comment by alex-okrushko** [comment]
This wasn't fixed
here is with the latest material and angular 5.2.1 http://plnkr.co/edit/aJTfUQ5O8L6SN0t4fLrm?p=preview

**Comment by genyklemberg** [comment]
select dialog is not closing when I change tabs

**Comment by alex-okrushko** [comment]
Not reproducible any more

**Comment by stagefright5** [comment]
@alex-okrushko , Please look at this example:
https://stackblitz.com/edit/angular-awab22?file=app%2Fsidenav-autosize-example.html
