### ISSUE TITLE
Multiples providers does not work in the core module

### ISSUE THREAD

**Issue by ferdaousharmel** [angular/material2#7987]
Hello,
Bug : 
My project is modular so i have two modules; one called CoreModule and the other is the AppModule. i am adding multiple providers (config,localization,error handler) in the CoreModule and calling the CoreModule 
 in the AppModule.
What is the expected behavior?
the call of different provider has to work correctly.
What is the current behavior?
no one of different providers is working correctly(methods initConfigProvider is not invoked).No crash also or explicit error.
What are the steps to reproduce?
I have a folder under the app folder called core in which i put my both error-handler.service.ts and app-config.provider.ts and calling it in the core.module.ts module.
And i call the CoreModule in the app.module.ts (angular-cli structured project)

http://plnkr.co/edit/6bxayAST1HKsu7ftmsHu?p=info

in Plunker i cannot do the same organization as i have yet describing (i cannot create folder).

What is the use-case or motivation for changing an existing behavior?
it is really useful to put many common providers in a same module and call it just with a NgModule.

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.
OS : windows 8.
Typescript : 2.3.3
browser : chrome

Hope that is clear.
THANKS A LOT FOR HELP.

**Comment by Chan4077** [comment]
This should be posted [here](https://github.com/angular/angular/issues/new) instead.
You can create folders by specifying `<folder>/<filename>` or whatever the directory is.

**Comment by julianobrasil** [comment]
@ferdaousharmel, also you can use https://stackblitz.com/edit/angular-material2-issue?file=app%2Fapp.component.ts instead of plunk. 

I like it's organization. But @Chan4077 is right. This is not the appropriate place to put your question.

**Comment by ferdaousharmel** [comment]
THANKS A LOT.
