### ISSUE TITLE
Tooltips incorrectly shows up

### ISSUE THREAD

**Issue by Kornhe** [angular/material2#7994]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tooltips only appears when hovering the element

#### What is the current behavior?
Tooltips appears after closing a `MatDialog` without hovering the element they are attached to

#### What are the steps to reproduce?
- Hover button, tooltip appears
- Click, `MatDialog` appears, tooltip closes
- Closing the modal will cause the tooltip to reappear, without hovering the button

https://stackblitz.com/edit/angular-wuygno

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.4
Angular Material beta 12

Windows x64 & Mac OS 10.3
Chrome 61

#### Is there anything else we should know?
Have a nice day !

**Comment by crisbeto** [comment]
Fixed in master by https://github.com/angular/material2/pull/7258.
