### ISSUE TITLE
md-input - type=number feature requests

### ISSUE THREAD

**Issue by peterwiebe** [angular/material2#800]
#### feature requests:

1. Have the ability to disable the number spinner buttons.

    I started typing out the suggestions below but began to realize that they probably don't align with the intentions of the spec but I have left them just in case:

2. Have a default value that is replaced upon first keyboard entry like the placeholder attribute on a basic input type="number" element (see plnkr example).

3. When the input field is cleared the placeholder does not move back down over the entry area.

#### What is the expected behavior?

1. Adding a CSS style to change the appearance of the number input to none should disable stepper buttons on the input element.

2. A placeholder value should appear (a numeric value) that is replaced when the user enters numeric input into the field.

3. After clearing the input the placeholder should move back down above the input area.

#### What is the current behavior?

1. The stepper buttons always show for input type="number"

2. When using the attribute value=0 (the only way to get a figure to show upon rendering) the initial value of 0 is appended to, not replaced by user input.

3. I think this issue may have to do with the value=0 attribute for md-input but the placeholder text does not move back down after clearing the input field and focusing on another field. 

#### What are the steps to reproduce?

See my Plunker demo: http://plnkr.co/edit/Xi8bdAhAIcwhLbGZrtEU?p=preview

#### What is the use-case or motivation for changing an existing behavior?

The motivation is for UX purposes, especially with having a default value. In the case of a stepper, it doesn't make sense to have it for large numbers (numbers over 100k)

#### Which versions of Angular, Material, OS, browsers are affected?

Latest versions of Angular, Material, Chrome Canary

#### Is there anything else we should know?

Thank you for taking the time to look at this and keep up the good work!

**Comment by jelbourn** [comment]
@peterwiebe there's a bit too much going on in this issue; it makes it impossible to respond to individual requests / bugs. It sounds like you have a mix of bugs and feature requests here. Can you file them as separate issues?
