### ISSUE TITLE
Input is not working for type date in iOS

### ISSUE THREAD

**Issue by joelharisonlobo** [angular/material2#8001]
#### Bug, feature request, or proposal:
Textbox is not working in iOS. I'm new to material design i have an application page in my page in that there is a field for date of birth there i have specified type = date in input but when i hosted the website only that textbox is not working in iOS.

#### What is the expected behavior?
I did all the inputs  without specifying its type but for date of birth i needed to specify type as date and needed the material styles. but date type is not working in iOS

#### What is the current behavior?
for input with date type is not working in iOS. Its not even focusing in any of the browsers

#### What are the steps to reproduce?
In this link you can see  my problem http://kitex.s3-website-us-west-2.amazonaws.com.
For android its working perfectly but in iOS its not even focusing.

`<mat-form-field class="fields-full-width">
      <input type="date" matInput placeholder="Date of birth" #DOB [max]="today" (keyup)="dobValidation(DOB)" (input)="dobValidation(DOB)">
 </mat-form-field>`

This is my code for date of birth

#### What is the use-case or motivation for changing an existing behavior?
There is a field for date of birth. Its not even focusing on that field. its like completly disabled. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using Angular 2 (@angular/cli: 1.1.1), Material(2.0.0-beta.12), in windows 10

for testing i have used iOS 11.0.3. In that safari and crome are the brosers i have used . But in both
date didn't worked 

[employee-registration.zip](https://github.com/angular/material2/files/1411975/employee-registration.zip)

#### Is there anything else we should know?
material date picker in material.angular.io site doesn't have clarity of how to use it.

**Comment by crisbeto** [comment]
I managed to reproduce it as well. It seems like iOS collapses the input into a `1px` by `100%` strip.
