### ISSUE TITLE
mdInput inside md-option of mdAutocomplete ignores space key

### ISSUE THREAD

**Issue by makdeniss** [angular/material2#8003]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
An input **mdInput** inside a **md-option** with `disabled` attribute should have the possibility to enter text with spacing. 

#### What is the current behavior?
An input **mdInput** inside a **md-option** with `disabled` attribute doesn't allow any spaces. Space key is being ignored.

#### What are the steps to reproduce?
```
<md-autocomplete #auto="mdAutocomplete">
  <md-option disabled>
    <md-icon>search</md-icon>
    {{'WELCOME_WIZARD.SEARCH_FOR_A_DEV_TEAM' | translate}}
  </md-option>
  <md-option disabled>
    <span>
      <md-form-field class="p-input-full-width p-select-adjusted">
        <input mdInput
               name="searchTerm" ngModel
               [formControl]="searchTeamCtrl"
               placeholder="{{'WELCOME_WIZARD.SEARCH_START_TYPING' | translate}}"
               aria-label="state">
      </md-form-field>
    </span>
  </md-option>
  <md-option *ngFor="let team of foundTeams | async" [value]="team.name">
    <span>{{ team.name }}</span>
  </md-option>
  <md-option disabled>
    <md-icon>star</md-icon>
    {{'WELCOME_WIZARD.INTEGRATION_PARTNER.FAVORITES' | translate}}
  </md-option>
  <md-option *ngFor="let team of filteredTeams | async" [value]="team.name">
    <span>{{ team.name }}</span>
  </md-option>
</md-autocomplete>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular v 4.4.3, Material 2 beta 11, tested on Chrome Version 64.0.3246.0 (Official Build) canary (64-bit)

#### Is there anything else we should know?

**Comment by amcdnl** [comment]
@makdeniss - Can you make a demo showing the issue?

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via Plunker.
