### ISSUE TITLE
.mat-paginator-range-label styles is not customizable

### ISSUE THREAD

**Issue by Shrralis** [angular/material2#8004]
#### Bug, feature request, or proposal:
Bug (or proposal, I'm not sure).

#### What is the expected behavior?
MatPaginator range cannot be fully customize with CSS.

#### What is the current behavior?
MatPaginator range is fully customizable with CSS.

#### What are the steps to reproduce?
As I see, Angular Material engine isn't adding tag attribute `_ng...` to `div` with class `mat-paginator-range-label`. So if there is any style in module style.css file it has no effect because of that tag attribute (`_ng...`) is added to style.
Example, user module style.css:
  ```
.mat-paginator-range-label {
    margin: 0 !important;
  }
```

The same style.css but after Angular processing, in browser:
```
  .mat-paginator-range-label[_ngcontent-c17] {
    margin: 0 !important;
  }
```

But `div` that I've talking about looks like:
![image](https://user-images.githubusercontent.com/11574591/31962109-50f97afc-b905-11e7-8d3c-c33e515acde3.png)

So the style.css gives no effect.

#### What is the use-case or motivation for changing an existing behavior?
It's more flexible (I guess).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
"@angular/core": "^4.4.6",
"@angular/material": "^2.0.0-beta.12",
"@angular/platform-browser": "^4.4.6",
"@angular/platform-browser-dynamic": "^4.4.6",
...

"typescript": "~2.5.3"
```

macOS High Sierra, Safari, Google Chrome
#### Is there anything else we should know?
I don't think so.

**Comment by andrewseguin** [comment]
This is an "Angular thing" - styles by default will only affect the elements you write in your component's template. This is a property of Angular's view encapsulation. Styling a child component's template means that you are trying to reach beyond your component's encapsulation.

To resolve this, set `ViewEncapsulation.None` on your component.

Before:
https://plnkr.co/edit/E6F8cjFoxBoiNG7J6zAV?p=preview

After:
https://plnkr.co/edit/rJ7S5A37eSpFLPwR8Bmf?p=preview

**Comment by Shrralis** [comment]
But it will affect each paginator of my project, right? Not just my module paginator.

**Comment by Shrralis** [comment]
This is my original behavior with our your suggestion but without my needs (margin for paginator range): https://stackblitz.com/edit/angular-h3ckjw
And this is with `encapsulation: ViewEncapsulation.None,`: https://stackblitz.com/edit/angular-nt88qt

I changed some table styles too and now `ViewEncapsulation.None` doesn't touch just my paginator but almost everything. Is there any way to workaround it?

**Comment by Shrralis** [comment]
@andrewseguin can you help me with that?

**Comment by andrewseguin** [comment]
@Shrralis You lost selector specificity when removing view encapsulation. Add a host class to your component and use it to add some more specificity to your styles. Otherwise the table's native styles are actually overriding yours.

https://stackblitz.com/edit/angular-lya35k?file=app/tables/manufacturers-table/manufacturers-table.component.css

**Comment by willshowell** [comment]
@Shrralis as you mentioned, setting `ViewEncapsulation.None` will make all of your component's styles globally effective. You have two options,

1. Scope all of your un-encapsulated component's styles with a scoped parent selector
    ```scss
    .only-affect-these-components {
 
      .mat-paginator-range-label {
        margin: 0;
      }
    }
    ```

    ```html
    <div class="only-affect-these-components">
      <mat-table> ... </mat-table>
      <mat-paginator>...</mat-paginator>
    </div>
    ```

2. Create a global style like this and add it to your global stylesheet

    ```scss
    // global styles
    .mat-paginator.marginless-paginator-range-label {

      .mat-paginator-range-label {
        margin: 0;
      }
    }
    ```

    ```html
    <mat-paginator class="marginless-paginator-range-label">...</mat-paginator>
    ```

There is more information [in this guide](https://material.angular.io/guide/customizing-component-styles)!

**Comment by Shrralis** [comment]
@andrewseguin @willshowell you're cool! Much thanks!
