### ISSUE TITLE
[Docs] Documentation lacks dependencies

### ISSUE THREAD

**Issue by radzik07** [angular/material2#8005]
#### Bug, feature request, or proposal:
Why does every single example encourages to use a MODULE that imports ALL OTHER MODULES? 
This is not only technically a bad practice, but also visually. Come on.
The problems start when a developer wants to import and use only ONE module.
How should I know that for working with MatDatePicker I also need to import MatInput (even if that's not used directly in template)? This info is not mentioned anywhere! How many surprises like that awaits me in future?

**Comment by ciesielskico** [comment]
You're welcome to submit a PR with proposed changes to the documentation.

**Comment by willshowell** [comment]
@radzik07 `MatDatepicker` doesn't actually have a dependency on `MatInputModule`. You can place a datepicker on a native input if you wish. It is only the examples using `matInput` that have that dependency.

To answer your first question, there is a [default template](https://github.com/angular/material.angular.io/blob/master/src/assets/plunker/main.ts) that the docs site uses to construct a Plunker example. Presumably to avoid a bunch of configuration for individual examples, that template uses a generic PlunkerMaterialModule that exports (and the PlunkerAppModule imports) everything that an example _could_ need.

While it's probably cumbersome to configure each example's NgModule to only use the exact modules needed, it's not outside of reason. Is that what you're proposing? Or do you have any ideas for improving the docs in a way that would have prevented your frustration?

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
