### ISSUE TITLE
Toolbar documentation incorrect

### ISSUE THREAD

**Issue by mikeyfev1** [angular/material2#8015]
#### Bug, feature request, or proposal:

Website documentation inconsistency.

#### What is the expected behavior?

I would expect the code examples to match the documentation.

#### What is the current behavior?

website documentation refers to **MatToolbar** elements. Example still lists old **md-toolbar** elements

#### What are the steps to reproduce?

Navigate to material.angular.io, click **Toolbar**, click **Example**, click **View Source**. The displayed source TS file contains **md-toolbar** elements.

**Comment by TheRedD0t** [comment]
This is a problem with cached files, try to clear your cache and reload the page.

**Comment by Chan4077** [comment]
See #7715.

**Comment by jelbourn** [comment]
This was a cache problem
