### ISSUE TITLE
ProgressSpinner Animation not working in IE11 & Edge

### ISSUE THREAD

**Issue by LukasN** [angular/material2#8016]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

The ProgressSpinner animations works as intended. 

#### What is the current behavior?

In Internet Explorer 11 & Edge i see a filled circle, without any Animation. In Firefox 56 & Chrome 61 it work as intended.
![erroredge](https://user-images.githubusercontent.com/1669621/31984191-d35bbf9a-b960-11e7-8a5c-74ac32855769.png)
![errorie](https://user-images.githubusercontent.com/1669621/31984192-d3764b1c-b960-11e7-9a46-5790df9871af.png)

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
 Opening the ProgressSpinner documentation with IE11 or Edge (https://material.angular.io/components/progress-spinner/overview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Im running on 2.0.0-beta.12

**Comment by crisbeto** [comment]
Fixed in master by https://github.com/angular/material2/pull/7599.
