### ISSUE TITLE
Mat checkbox clicking and moving cursor fast wont register click

### ISSUE THREAD

**Issue by chriseenberg** [angular/material2#8017]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Check box should check even though you move cursor just after clicking

#### What is the current behavior?
If you click the check box and quickly move the cursor out of the field (not dragging), the check box animation gets triggered but the checkbox does not receive the click - i.e. the checkbox does not change value and the check does not appear in the checkbox.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

https://stackblitz.com/edit/angular-material2-issue-b4tcce?embed=1&file=app/app.component.html&view=preview

#### What is the use-case or motivation for changing an existing behavior?
It's difficult to use the component when you can't quickly modify the value of a checkbox.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/material": "2.0.0-beta.12",
    "@angular/common": "^4.4.6" - rest the same.
    "typescript": "^2.5.3"

Tested only in Chrome Version 61.0.3163.100

#### Is there anything else we should know?
In case this is hard to reproduce, turn up mouse sensitivity to have a higher "successrate" with the error.

![ezgif-3-23e426add5](https://user-images.githubusercontent.com/13994371/31987875-7f2da12e-b96d-11e7-830d-0bf9ab4c6cc1.gif)

**Comment by willshowell** [comment]
Are you _sure_ you're not dragging when this is happening? It seems like it'd be very easy to mouseup just outside the checkbox's click region while trying to move away so quickly.

Do you not see the same behavior with a native checkbox? It's even smaller, so I feel like the Material one is actually an improvement for this sort of behavior.

**Comment by jelbourn** [comment]
This is working as expected; the ripple is triggered by `mousedown` (which occurs), but the checkbox is triggered by `click`, which also requires a `mouseup` on the element.
