### ISSUE TITLE
Margin-left not applied to mat-sidenav-content on page load

### ISSUE THREAD

**Issue by darshan-g** [angular/material2#8019]
#### Bug, feature request, or proposal:
Margin-left not applied to mat-sidenav-content on page load
#### What is the expected behavior?
The mat-sidenav-content should have margin-left of some value(>0px) if the drawer is open on page load

#### What is the current behavior?
On page load, the drawer is open (since opened="true" is applied to mat-sidenav element).The mat-sidenav-content has margin-left of 0px(instead of being 200px).  When the drawer is closed the margin-left is 0px(as expected). Now if the drawer is opened mat-sidenav-content has margin-left of 200px(as expected).  So, only on page load the issue exists.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material - 2.0.0-beta.12

**Comment by grapgrap** [comment]
I have same issue.

**Comment by mmalerba** [comment]
closing as dup of #6743
