### ISSUE TITLE
bug(chip-list): limited height element has unusable scroll bar

### ISSUE THREAD

**Issue by merlosy** [angular/material2#8023]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I have a chip list of items, with a maximum height, in which I want to scroll through chips.
I scroll down to mid-height.
When I click on the scroll bar on the right to go down, the scroll bar jumps to the top as it triggers focus on first element of the list, and then goes down.

#### What is the current behavior?
It should keep scroll height

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>

http://plnkr.co/edit/rQRiTahr65Kwom2F3FWl?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Make scrolling weird and not really usable

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.6
Material Beta 12

#### Is there anything else we should know?

Workaround in plunker: override focus method

**Comment by merlosy** [comment]
Even though the focus is intended by design and for accessibility reason, it makes the experience confusing and was reported as a bug from our users. Especially, when they wish to click on the [X] to remove the chip and miss the button (bad user!), they will be moved to the top of the list.

**Comment by tinayuangao** [comment]
Not able to reproduce the issue. Is it because you intentionally focus on the chip list? After user removed a chip, the focus should be moved to the next chip in the chip list, or the previous chip if the removed chip is the last one.
