### ISSUE TITLE
Possibility to alternate background of Table's rows

### ISSUE THREAD

**Issue by AbakumovAlexandr** [angular/material2#8026]
#### Bug, feature request, or proposal:
Feature request.

#### What is the expected behavior?
Ability to alternate background of Table's rows. This should correctly work with sorting/filtering.

#### What is the current behavior?
Rows' background can't be easily alternated.

**Comment by benb7760** [comment]
This can be achieved already - see following [excerpt from the demo-app](https://github.com/angular/material2/blob/master/src/demo-app/table/table-demo.html#L109)

```
    <cdk-row *cdkRowDef="let row; columns: displayedColumns;
                         let first = first; let last = last; let even = even; let odd = odd"
             [ngClass]="{
                 'demo-row-highlight-first': highlights.has('first') && first,
                 'demo-row-highlight-last': highlights.has('last') && last,
                 'demo-row-highlight-even': highlights.has('even') && even,
                 'demo-row-highlight-odd': highlights.has('odd') && odd
               }">
    </cdk-row>
```

**Comment by crisbeto** [comment]
@benb7760 is correct, this is possible already.
