### ISSUE TITLE
remove @angular/http in package.json

### ISSUE THREAD

**Issue by miguelcaravantes** [angular/material2#8039]
why "@angular/http": "~4.4.4" is in DevDependencies of package.json of master? if it is deprecated
https://github.com/angular/material2/blob/master/package.json

![image](https://user-images.githubusercontent.com/17279582/32029013-ee8b83ba-b9ae-11e7-986d-472a47cb35ab.png)

**Comment by crisbeto** [comment]
It is still needed for one of our CI checks. Since it’s a dev dependency consumers don’t have to install it anyway.
