### ISSUE TITLE
Virtual Scroll on long lists

### ISSUE THREAD

**Issue by danielgolub** [angular/material2#804]
#### Bug, feature request, or proposal:
When there are very long lists, the performance is very poor.
We would like to have an option to do virtual scroll, which will render only the items on the viewport with some offset.

#### What is the expected behavior?
Make a template directive like NgFor:
``````````````
<md-list [virtualScroll]="list">
	<md-list-item *virtualItem="let item; let i = index">
            Item {{i}}
	</md-list-item>
</md-list>
``````````````

#### What is the current behavior?
None, currently all the list renders with ngFor. So the performance for thousands of items can be very poor

#### Which versions of Angular, Material, OS, browsers are affected?
All

**Comment by jelbourn** [comment]
Tracking virtual scrolling via #823
