### ISSUE TITLE
Select: Typing Doesn't Scroll Panel on First Character

### ISSUE THREAD

**Issue by mikeomeara1** [angular/material2#8040]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Pre-Beta.12 When Typing into an open `<mat-select>` (`<md-select>`) the panel scrolls  to the character you've typed immediately. 

#### What is the current behavior?
In Beta.12 typing causes the correct md-option to be selected but doesn't scroll the panel to its location unless the character is typed again. This makes multi-character type-to-select not usable.

#### What are the steps to reproduce?
[https://plnkr.co/edit/uUIwV7K3Q5IOdxf9nAmA?p=preview](https://plnkr.co/edit/uUIwV7K3Q5IOdxf9nAmA?p=preview)

- Click the select
- Type any character below the fold
- The panel will not move
- Type the same character again, then panel will then scroll

The same action in Beta.10 works as expected:
[https://plnkr.co/edit/hoqza70JX9Rw4eNoUqfg?p=preview](https://plnkr.co/edit/hoqza70JX9Rw4eNoUqfg?p=preview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.3
Material: 2.0.0-beta.12
OS: Windows 10
Typescript: 2.2.2
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by mikeomeara1** [comment]
Additionally, (although I can't prove it yet) I'm seeing some very strange behavior--vis-a-vis keyboard interaction --when a select is placed in a md-dialog. Especially so when there are a large number of options. I'll update when I can provide evidence.

**Comment by crisbeto** [comment]
The item not being scrolled into view is fixed by https://github.com/angular/material2/pull/7620.
