### ISSUE TITLE
Undefined MatSort Directive From MatTable Inside a MatStepper

### ISSUE THREAD

**Issue by JarekToro** [angular/material2#8041]
#### Bug, feature request, or proposal:
Bug
#### What is the expected behavior?
Using `@ViewChild(MatSort)` get the Directive from inside a Stepper

#### What is the current behavior?
Returns Undefined

#### What are the steps to reproduce?
http://plnkr.co/edit/mLbnnpLG5bDumD2jBYZt?p=info

#### What is the use-case or motivation for changing an existing behavior?
Select from list to advance to next step

**Comment by Chan4077** [comment]
That's because the value you specified for `ViewChild` is supposed to be a string and not a type.
Use as follows:

```html
<div #myRef></div>
```

```typescript
export class AppComponent {
    @ViewChild('myRef') divEl: HTMLDivElement;
}
```

**Comment by willshowell** [comment]
You must import `MatSortModule`.

@DevVersion could you add it and `MatPaginatorModule` to the default template's `PlunkerMaterialModule`?

**Comment by jelbourn** [comment]
@DevVersion can you take a look if this is just updating the plunker setup?

**Comment by DevVersion** [comment]
@willshowell @jelbourn Updated the Plunker template. And yeah this issue seems to be fixed by adding the necessary modules.

**Comment by kalitine** [comment]
I have the same issue. Tried to import all modules, but still doesn't work. Could it be related to something else?

**Comment by enalposi** [comment]
> I have the same issue. Tried to import all modules, but still doesn't work. Could it be related to something else?
> 
> UPDATE: I found the problem. It is `undefined` because of `*ngIf` directive on the tag above mat-table (even if it evaluates to true).

Good find! Removing *ngIf fixed the issue. This is a bug and should be re-opened.
