### ISSUE TITLE
MatProgressSpinner diameter input not working on older browsers

### ISSUE THREAD

**Issue by StefanErakovic** [angular/material2#8047]
#### Bug, feature request, or proposal:
[x] Bug

#### What is the expected behavior?
Setting the diameter input property changes the size of the spinner.

#### What is the current behavior?
Type error "Not enough arguments to CSSStyleSheet.insertRule." happens.

#### What are the steps to reproduce?
Plnkr example:

http://plnkr.co/edit/SrTKKv8wRSJARumOhXVW?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
OS: Ubuntu 16.04
Browser: Firefox 54.0 (64-bit)

package-lock.json:
angular/core: 4.4.6
angular/material: github:angular/material2-builds#ee47c9dde6a42f4db60e0d762f74d3d8ce6f6c28
typescript: 2.3.4

#### Is there anything else we should know?
Tested with also:
`<mat-spinner diameter="40"></mat-spinner>`

Same behaviour.
https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule
Suggested fix:
Support older browsers by adding the index of 0 to the call
stylesheet.insertRule(rule[, index])

**Comment by crisbeto** [comment]
Should be sorted out by https://github.com/angular/material2/pull/7810.
