### ISSUE TITLE
readOnly will not work if first value is 'true'

### ISSUE THREAD

**Issue by pedrolsamaral** [angular/material2#8048]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
An input tag should be set with attribute 'readonly' even when the first value evaluates to 'true'

#### What is the current behavior?
It only sets the input with 'readonly' when the value switches to 'false' and back to 'true'

#### What are the steps to reproduce?
In the following plunker there are 2 similar inputs: one with angular material and another without.
The angular material's input will only become readonly after the textarea value is changed to something and back to 'test'

https://plnkr.co/edit/NT29mIPwrRnLUJJtKKpR?p=preview

#### What is the use-case or motivation for changing an existing behavior?
The most immediate use-case is a field that should only be changed in special conditions and so should be marked with read-only from the beginning.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest of angular, TypeScript. 
The issue was detected in Windows 7 using the latest version of Chrome..

#### Is there anything else we should know?
No

**Comment by shonderdos** [comment]
Replacing `[readOnly]="isReadOnly()"` with `[readonly]="isReadOnly()" ` (lowercase 'o') on the material inputs works.

**Comment by pedrolsamaral** [comment]
Ah! That should do. (Although it still could be fixed to avoid incoherent behavior with angular)
Thanks a lot :+1:
