### ISSUE TITLE
Tabs accessibility keyboards 

### ISSUE THREAD

**Issue by yantrab** [angular/material2#8049]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
In rtl direction the left key need to go left and right to the right. 

#### What is the current behavior?
the oposite

**Comment by willshowell** [comment]
Can you reproduce? Admittedly this is an old snapshot demo, but I'm not seeing any reversed key behavior in RTL

https://willshowell-demo.firebaseapp.com/tabs/rainy-tab

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
