### ISSUE TITLE
is md-content deprecated?

### ISSUE THREAD

**Issue by georgi-kovachev** [angular/material2#806]
There is md-content tag in angular-material (version 1)
https://github.com/angular/material/tree/master/src/components ('content' folder)
But I can't find md-content tag in angular-material2 (version2)

Is this deprecated? But it seems like working when I use this tag in angular2 project.
And there are some missing tags when I compare it to angular1

**Comment by kara** [comment]
@georgi-kovachev Angular Material 2 is currently in early alpha, so we only have a subset of the Material 1 components available at the moment.  We haven't deprecated md-content;  it simply doesn't exist in the repo yet.   You can see our milestones here: https://github.com/angular/material2/milestones.

**Comment by georgi-kovachev** [comment]
hi Kara.
It seems like when I use <md-content> it doesn't load predefined css files because css is not included in @angular2-material.
In this case how can I use existing styles like md-content?
