### ISSUE TITLE
Tooltips reappear after dismissing a dialog.

### ISSUE THREAD

**Issue by hans-pragt** [angular/material2#8063]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
After dismissing a dialog, no tooltip should appear on the button that launched it.

#### What is the current behavior?
If a button which launches a dialog has a tooltip, this tooltip with pop out again when the dialog has been dismissed, even if the cursor is not on the button.

#### What are the steps to reproduce?
1. Navigate to: https://angular-material2-issue-k549gg.stackblitz.io
2. Click the button to launch the dialog window
3. Click any of the buttons to close the dialog window
4. Notice that the tooltip of the button pops up, even if the cursor is not near it

#### What is the use-case or motivation for changing an existing behavior?
The user already knows what the button does at this point, so the tooltip is no longer needed. Moreover, if the cursor is not over a component, it should never show the tooltip.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest, see stackblitz.

**Comment by crisbeto** [comment]
Fixed in master by https://github.com/angular/material2/pull/7258.
