### ISSUE TITLE
Progress spinner breaks on older browsers

### ISSUE THREAD

**Issue by mayankku** [angular/material2#8064]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Progress spinner should work on all possible browsers.

#### What is the current behavior?
Progress spinner throws exceptions on relatively recent browsers, e.g. Firefox < 55.
This is due to omitting a [previously required parameter](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule#Parameters) in the [call to insertRule](https://github.com/angular/material2/blob/0ea43700efb105aa02ad3b1d3f800bf4a9925883/src/lib/progress-spinner/progress-spinner.ts#L203).

#### What are the steps to reproduce?
Run progress spinner sample on Firefox < 55.

#### What is the use-case or motivation for changing an existing behavior?
No change in behavior

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Firefox < 55, possibly Chrome < 60

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material2/pull/7810.
