### ISSUE TITLE
Selected/Deselect checkbox when pressing enter

### ISSUE THREAD

**Issue by Nightapes** [angular/material2#8066]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

When using tab to move from control to control, the checkbox changes the value when the user has focus on the checkbox and press enter.  

#### What is the current behavior?

When using tab to move from control to control, the checkbox gets highlighted but does not changes the value when pressing enter.

#### What are the steps to reproduce?
 [see demo](https://material.angular.io/components/checkbox/examples)

Use tab to change the checkbox and press enter, the checkbox is not selected 

#### What is the use-case or motivation for changing an existing behavior?

Allow user to go through the form without using the mouse

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Used by the demo page
Tested under Chrome: Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by willshowell** [comment]
You can select/deselect it with the spacebar. This matches the native behavior.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

**Comment by jelbourn** [comment]
Working as intended- as @willshowell mentioned, the keyboard interaction is driven by an underlying `<input type="checkbox">` so it will always follow the native behavior.
