### ISSUE TITLE
Make mat-dialog-content size adjustable

### ISSUE THREAD

**Issue by pycraft114** [angular/material2#8071]
#### Bug, feature request, or proposal:

Make .mat-dialog-content size adjustable by javascript

#### What is the expected behavior?

.mat-dialog-container width and height is adjustable by the open method's second parameter.
Make .mat-dialog-content size adjustable like so.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by jelbourn** [comment]
mat-dialog-content is just a scrollable container for organizing dialog content. You can control its size via css like any other element

**Comment by elmeerr** [comment]
@jelbourn when material used `md-dialog-container`, the size of the container increases according to `md-dialog-content` (beta-8) but I've updated material to beta-12 and the` mat-dialog-container` does not increases it sizes anymore. Now I'm trying to figure out how to increase sizes dynamically as Idon't have access dynamically to `mat-dialog-container` (at least I can't find on docs)
