### ISSUE TITLE
MatDialog automatically selects the first link on the component when opened

### ISSUE THREAD

**Issue by drullo** [angular/material2#8075]
#### What is the expected behavior?
I would expect no elements to be selected when the dialog opens

#### What is the current behavior?
On components that contain links and text (no input controls), the first link is selected until the user clicks somewhere else on the component.  This looks strange to users as their eye is drawn to the selected item and they don't know why it looks different.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/core@4.4.6
@angular/material@2.0.0-beta.12
typescript@2.3.4
Windows 10, Chrome (possibly others)

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/7972

**Comment by jelbourn** [comment]
This is working as intended. Upon opening a dialog, the first tabbable element will receive focus. You can control how this works, but it's currently undocumented (see #8082)
