### ISSUE TITLE
'maxWidth' does not exist in type 'MatDialogConfig'

### ISSUE THREAD

**Issue by navalgandhi1989** [angular/material2#8081]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should be able to set maxHieght and maxWidth of DailogBox

#### What is the current behavior?
Getting error while compilation

> Argument of type '{ maxHeight: string; maxWidth: string; data: { id: number; }; }' is not assignable to parameter of type 'MatDialogConfig'.  Object literal may only specify known properties, and 'maxHeight' does not exist in type 'MatDialogConfig'.

#### What are the steps to reproduce?
Trying to open the dialog like this
    
    this.dialog.open(MyDialog, {
    maxHeight: '95%',
    maxWidth: '60%', data: { id: myId}
    });

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.6
Material 2.0.0-beta.12
OS Windows
TypeScript 2.3.4
Browser Chrome

**Comment by jelbourn** [comment]
Those properties were added on master but not yet included in a public release. Looks like the documentation of accidentally updated too soon. This will be resolved with the next release. Closing since there's not actually any code changes necessary to fix.

**Comment by navalgandhi1989** [comment]
Thanks for the Prompt Reply. BTW really good work on the Components :-)

**Comment by RaedsLab** [comment]
When is the Material 2.0.0-beta.13 due ?

**Comment by dushkostanoeski** [comment]
It's out, and it's not a beta anymore, it's 5.0.0-rc0

**Comment by RaedsLab** [comment]
Guess 13 is an avoidable number 🤣  
Thanks i'll give it a shot
