### ISSUE TITLE
md-input doesn't work after update to alpha 6

### ISSUE THREAD

**Issue by maciejsobala** [angular/material2#809]
#### Bug, feature request, or proposal:
Completely lost of functionality

#### What is the expected behavior?
md-input should be displayed

#### What is the current behavior?
Got exception:

EXCEPTION: Error in http://localhost:3000/node_modules/@angular2-material/input/input.js class MdInput - inline template:0:844

ORIGINAL EXCEPTION: No value accessor for ''

etc. etc.

#### What are the steps to reproduce?
```
import {Component} from '@angular/core';
import {MD_INPUT_DIRECTIVES} from '@angular2-material/input';

@Component({
  selector: 'attribute-types',
  template: `<md-input></md-input>`,
  directives: [
    MD_INPUT_DIRECTIVES
  ],
  styleUrls: ['app/productsSettings/formList.css'],
})

export class AttributeTypesComponent implements OnInit{
  
}
```

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.0.0-rc.4
Material: 2.0.0-alpha.6
Browsers: Safari, Chrome, FireFox
OS: OS X El Capitan, iOS 9.3

**Comment by elvirdolic** [comment]
You have to update to the new forms module: 

see here:
https://github.com/angular/material2/issues/803

and 
here: https://angular.io/docs/ts/latest/guide/forms.html

**Comment by RAlfoeldi** [comment]
There must be something else missing.

I have the same problem as the op.

I've just deleted all node deps and reinstalled. I'm getting 

`npm WARN @angular2-material/input@2.0.0-alpha.6 requires a peer of @angular/forms@^0.1.0 but none was installed.`

normal `<input>`s work. `<md-input>` doesn't.

```
<form>

  UidPrefix: <md-input [(ngModel)]="ve.uidPrefix" name="uidPrefix" type="text"></md-input><br>
  Uid: <input [(ngModel)]="ve.uid" name="uid" type="text"><br>
```
I'm getting `browser_adapter.js:84Error: Uncaught (in promise): No value accessor for 'uidPrefix'`

And yes, I have enabled the 'new' forms: 

```
package.json:
   "@angular/forms": "0.2.0",
    "@angular2-material/core": "2.0.0-alpha.6",
    "@angular2-material/input": "2.0.0-alpha.6",


main.ts:
import {provideForms, disableDeprecatedForms} from "@angular/forms";
...
bootstrap(ExchComponent,
    [
      disableDeprecatedForms(),
      provideForms(),
...
```

I currently have no problem waiting for a working solution, but maybe there is still a problem you haven't realized yet.

**Comment by maciejsobala** [comment]
Hello guys,

I added 'provideForms()' to my bootstrap, and that solved problem so far.

```
import {bootstrap}    from '@angular/platform-browser-dynamic';
import {AppComponent} from './app.component';
import {HTTP_PROVIDERS} from '@angular/http';
import {provideForms} from '@angular/forms';


bootstrap(AppComponent, [HTTP_PROVIDERS, provideForms()]);


```

**Comment by maciejsobala** [comment]
@RAlfoeldi Same on my side. <input> works correctly, but <md-input> not.

**Comment by wardberckmans** [comment]
Same issue here on <md-input>.

**Comment by drager** [comment]
Hmm, I got i working just fine using the new forms with the alpha 6 version (Did not work before with the new forms for me).

Be sure to bootstrap the `disableDeprecatedForms()` and `provideForms()`. Also make sure your `<md-input>` has a name attribute. Here's some code I have:

```typescript
// main.ts

import {bootstrap} from '@angular/platform-browser-dynamic'
import {provide} from '@angular/core'
import {disableDeprecatedForms, provideForms} from '@angular/forms'

bootstrap(App, [
  disableDeprecatedForms(),
  provideForms(),
]).catch(err => console.error(err))
```

```typescript
// sign-in.ts

import {Component} from '@angular/core'
import {FORM_DIRECTIVES} from '@angular/forms'
import {MdButton} from '@angular2-material/button/button'
import {MdIcon, MdIconRegistry} from '@angular2-material/icon/icon'
import {MD_INPUT_DIRECTIVES} from '@angular2-material/input/input'

@Component({
  selector: 'sign-in',
  template: template,
  styles: [styles],
  directives: [MdButton, MdIcon, MD_INPUT_DIRECTIVES, FORM_DIRECTIVES,],
  viewProviders: [MdIconRegistry],
})
export class SignIn {
  constructor() {}
}
```

```html
// sign-in.html

<form>
      <md-input #email
                required
                type="email"
                name="email"
                placeholder="Email Address"
                [(ngModel)]="user.email">
      </md-input>
      <md-input #password
                required
                type="password"
                name="password"
                placeholder="Password"
                [(ngModel)]="user.password">
      </md-input>
      <button type="submit" md-raised-button>Login</button>
  </form>
```

**Comment by kara** [comment]
Can anyone provide a plunker demonstrating the problem? Alpha.6 md-input works fine for me, but perhaps we're testing differently.  Is anyone importing symbols from `@angular/common` rather than `@angular/forms`?  The "no value accessor" error usually appears when you mix the old and new forms APIs by mistake?

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/lTdUX1SyRR1wl9lptS3k?p=preview everything is working fine

**Comment by RAlfoeldi** [comment]
Ok, works for me now. Thanks for the hint.

**Comment by kara** [comment]
OK, it seems like this might not be a bug, but rather a problem of insufficient documentation.  I'm adding a section to the GETTING_STARTED guide with some more info on this: https://github.com/angular/material2/pull/810. 

If anyone is still having issues with md-input, please feel free to re-open with a demonstrative plunker.

**Comment by albanx** [comment]
Hi Guys
I am facing this problem when I try to create a simple login form with md-input and the ngFormModel. Please find the pluker demo here (not working on plunker).

http://plnkr.co/edit/ZT2pGoLgiSmqGctmhiG9?p=preview

What I am doing wrong? Is ngFormModel still valid?

**Comment by soorireddy** [comment]
+1

**Comment by dalestone** [comment]
I had a similar issue, turns out it was to do with using Angular2 RC1 dependencies as far as I can. 

I changed to RC2 and it started working fine, e.g `"2.0.0-rc.1" to "2.0.0-rc.2"` for all angular packages.

```
...
  "dependencies": {
    "@angular/common": "2.0.0-rc.2",
    "@angular/compiler": "2.0.0-rc.2",
    "@angular/core": "2.0.0-rc.2",
    "@angular/forms": "^0.2.0",
    "@angular/http": "2.0.0-rc.2",
    "@angular/platform-browser": "2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "2.0.0-rc.2",
    "@angular/router": "2.0.0-rc.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.2",
    "@angular2-material/button": "^2.0.0-alpha.6",
    "@angular2-material/card": "^2.0.0-alpha.6",
    "@angular2-material/core": "^2.0.0-alpha.6",
    "@angular2-material/icon": "^2.0.0-alpha.6",
    "@angular2-material/input": "^2.0.0-alpha.6",
    "@angular2-material/list": "^2.0.0-alpha.6",
    "@angular2-material/sidenav": "^2.0.0-alpha.6",
    "@angular2-material/toolbar": "^2.0.0-alpha.6",
    "angular2-in-memory-web-api": "0.0.11",
    "angular2-jwt": "^0.1.18",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
  },
...
```
