### ISSUE TITLE
bug(autocomplete): activeOption is always null

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#8093]
#### Bug, feature request, or proposal:

Apparently, `MatAutocompleteTrigger.activeOption` is always null.

#### What is the expected behavior?

It should hold the chosen option

#### What is the current behavior?

Its value is always null

#### What are the steps to reproduce?

https://stackblitz.com/edit/autocomplete-force-selection

**Comment by crisbeto** [comment]
The `activeOption` isn't always null, it'll return the highlighted option while the dropdown is open, however it does get cleared once the dropdown is closed. The primary purpose of `activeOption` is for the `aria-activedescendant` attribute on the input.

**Comment by julianobrasil** [comment]
Oh, thanks, @crisbeto. I misunderstood it. 

More detailed comment in the code would be nice as it is used in the docs site. Can I change it based on your answer and submit a PR?

I'm gonna close this.

**Comment by crisbeto** [comment]
I suppose, but I think that it may be more appropriate to make the property private. It's not particularly useful to anybody that consumes the autocomplete.

**Comment by julianobrasil** [comment]
Well, I think I have an use case for letting it public. It's not with `mat-autocomplete` but it's very similar: `mat-select`. I have an app with a popover that is fired on `mouseenter` event. The popover aims to give more details about the option when the user hover the mouse over it. There's a particular case: when the user click on select trigger and it first opens with one option active, the popover isn't fired until the user moves the mouse: 

![image](https://media.giphy.com/media/l1J9qM0KGyEbDRX2M/giphy.gif)

Now that you told me how `activeOption` works,  I think I could use it to fire the popover when the panel opens (I assume there's something equivalent in the `mat-select` trigger).

**Comment by crisbeto** [comment]
Yes, `MatSelect` has the `onOpen` and `onClose` events.

**Comment by julianobrasil** [comment]
I have the `onOpen`... but what I really needed is kind of an event to be fired from the option when that option was activated so I could pass the popover attatched to it as an argument to a function. I'll think of something. Thank's anyway.
