### ISSUE TITLE
Datepicker: make property "opened" an input

### ISSUE THREAD

**Issue by ocombe** [angular/material2#8094]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I would like to have the datepicker opened at load time, for that I expected to use [opened]=true, but it turns out that it's a simple property, not an input, which means that I cannot set the date picker to open at load time. If i use `open()` in ngAfterViewInit I get an `ExpressionChangedAfterItHasBeenCheckedError`, which makes sense since it was changed from false to true.

#### What is the current behavior?
`opened` is a property, not an input

#### What is the use-case or motivation for changing an existing behavior?
We should be able to show the datepicker opened with an input

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material/CDK 2.0.0-beta.12

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
