### ISSUE TITLE
Dialog Service Docs Need Updated: AOT & EntryComponent

### ISSUE THREAD

**Issue by tommyc38** [angular/material2#8102]
#### Bug, feature request, or proposal:

The dialog component is not working.  It doesn't appear to inject the component.

#### What is the expected behavior?

I would expect the dialog component to work as per the documentation.

#### What is the current behavior?

See StackBlitz example.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

https://stackblitz.com/edit/angular-material2-issue-hdwz9o

**Comment by tommyc38** [comment]
I added the entryComponents in AppModule and everything started working fine.  Your docs need updated because I am not using AOT and the entryComponent solved the issue.

**Comment by julianobrasil** [comment]
It's being tracked in docs repo: https://github.com/angular/material.angular.io/pull/228

**Comment by jelbourn** [comment]
@tommyc38 is this issue about the plunker example or the actual `MatDialog`?

**Comment by tommyc38** [comment]
@jelbourn The docs state that you only need to add in entryComponents for AOT.  I am using JIT and the only way it works is by adding in entryComponents.  I think the docs need to simply say to add in entryComponents to your NgModule.  I spent a few hours wondering why MatDialog did not work.  I would like to help someone else avoid the same issue given its not very clear how to get it working IMHO.  Thanks.
