### ISSUE TITLE
prop(docs): Remove early development hint from chips

### ISSUE THREAD

**Issue by TheRedD0t** [angular/material2#8108]
The [docs of the chip component](https://material.angular.io/components/chips/overview) still contains a early development hint, is this still needed? A lot of features have been released since the notice was added and it may send out wrong signals.

> Note: chips are still early in their development and more features are being actively worked on.

If not, I can take care of it.

**Comment by jelbourn** [comment]
Yeah, that should be removed. PRs welcome.

**Comment by TheRedD0t** [comment]
Closed with https://github.com/angular/material2/pull/9818
