### ISSUE TITLE
Give users the ability to listen to scroll for mat-sidenav-container

### ISSUE THREAD

**Issue by willwsharp** [angular/material2#8115]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
There needs to be a way for others to listen to scroll events when inside a global mat-sidenav-container.

#### What is the current behavior?
Currently, the mat-sidenav-container does not fire a window.scroll so there's no way to hook into that event.

#### What is the use-case or motivation for changing an existing behavior?
It would allow for a more flexible use of the mat-sidenav-container

**Comment by willshowell** [comment]
[`cdkScrollable`](https://material.angular.io/cdk/scrolling/overview#cdkscrollable-and-scrolldispatcher) should do the trick

**Comment by willwsharp** [comment]
I will give that a try, thank you.

**Comment by josephperrott** [comment]
Closing due for use of `cdkScrollable`
