### ISSUE TITLE
Text input overlaps it's placeholder (label)

### ISSUE THREAD

**Issue by nudalight** [angular/material2#8122]
I use AngularMatrerial and the input field in my templates behave unacceptably.

My template
```
<mat-form-field>
    <input
	matInput
	placeholder="Login"
        name="username"
	[(ngModel)]="username"
	required
   />
</mat-form-field>
```
Here is what I get:
1) clean inputs
http://storage1.static.itmages.com/i/17/1030/h_1509369993_4936270_12995199fa.png

2) input with text
http://storage9.static.itmages.com/i/17/1030/h_1509370041_1204485_b06e7e96a4.png

There are no errors in browser console.

How can I fix this?

**Comment by josephperrott** [comment]
Can you provide a reproduction in either [Plunker](https://goo.gl/uDmqyY) or [StackBlitz]( https://goo.gl/wwnhMV)

**Comment by julianobrasil** [comment]
@nudalight, have you imported material theme?

**Comment by aaronte** [comment]
This was happening w/ me but I figured I was using `@angular` `4.3.6` with `@angular/material@2.0.0-beta.12`. I upgraded all `@angular` packages to `4.4.6` and it's now behaving correctly. I can't repro the bug on Stackblitz with the version mismatch though.

**Comment by nudalight** [comment]
Oh, the reason It did not work is that I did not include `MatFormFieldModule` to module imports. Please, close the issue.

**Comment by RaedsLab** [comment]
I'm having the same issue 

Here are my versions : 

`
    "@angular/animations": "^4.4.5",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.4.4",
    "@angular/forms": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",

    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/material": "^2.0.0-beta.12",
`

**Comment by jans-y** [comment]
I had the same issue and it was caused by not upgrading the css file.

I have customized the theme in the earlier version and forgot to swap it for newer one.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
