### ISSUE TITLE
Progress Spinner initialization bug

### ISSUE THREAD

**Issue by bOOm-X** [angular/material2#8126]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

No "visual glitch" at the progress spinner initialization

#### What is the current behavior?

During a short period of time (1 second) the value attribute of the progress spinner is ignored and, the spinner start from almost "full" and go "back" to the correct initial value

#### What are the steps to reproduce?

https://plnkr.co/edit/vSTe3nqLuA1xiKSjzT1Z?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular material 2.0.0-beta.12

#### Is there anything else we should know?

The issue appears only when angular flex-layout is imported (even if it is not used).

**Comment by josephperrott** [comment]
It looks like this is caused because when the value is undefined, the `stroke-dashoffset` value becomes `NaN` which results in the css attribute not being applied.   The css then animates from offset of `0` to whatever the new value is, which appears to animate as coming from 100%
