### ISSUE TITLE
matTable Use object sub keys (key1.subkey1) for columns defintion 

### ISSUE THREAD

**Issue by sebastiendan** [angular/material2#8127]
Hi,

I've been using matTable for a while now and just realised I cannot use complex objects (= objects with multiple layers of `key: value`) in the columns array I send to `*matRowDef`. Am I right, or am I missing something? I cannot find anything doc nor issue about that.

Would be great to add this feature if it doesn't exist as it's not always easy/clean to get our APIs to return treeless objets.

Thanks!

**Comment by willshowell** [comment]
Can you explain with code or a reproduction what it is you're trying to do? A string array of column keys is required.

https://github.com/angular/material2/blob/520d83bb618a128fe54e377a04e574cf164f4d48/src/cdk/table/row.ts#L34-L35

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by sebastiendan** [comment]
https://github.com/angular/material2/issues/8151
