### ISSUE TITLE
Angular material plunker not working

### ISSUE THREAD

**Issue by AClavijo** [angular/material2#8129]
#### Bug, feature request, or proposal:
The general plunker not working

#### What is the expected behavior?
Loading Angular Material App.

#### What is the current behavior?
**Error: (SystemJS) XHR error (404 Not Found) loading https://unpkg.com/rxjs@5.0.1/operators.js**
on http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by josephperrott** [comment]
@DevVersion looks like rxjs isn't loading as expected?

**Comment by robert-king** [comment]
yup, I tried making a plunkr just now to show that the material avatar circles are distorting my images. (My images aren't perfect square, so it's squashing them & the quality isn't quite 100% depending on which type of physical computer screen i use)

**Comment by josephperrott** [comment]
Fixed by #8137
