### ISSUE TITLE
Host the Demo-App

### ISSUE THREAD

**Issue by gfrSE** [angular/material2#814]
#### Bug, feature request, or proposal:

Would be great if you host the demo-app anywhere and link it in the readme.md

#### What is the expected behavior?

Online hosted demo-app.

#### What is the current behavior?

No demo-app. :)

**Comment by DzmitryShylovich** [comment]
https://material2-app.firebaseapp.com/

**Comment by gfrSE** [comment]
@DzmitryShylovich thanks, saw this page too some time before.

But would be nice to host this official demo-app anywhere:
https://github.com/angular/material2/blob/master/src/demo-app/demo-app/demo-app.html

and keep it up to date.

**Comment by maku** [comment]
Would be really great to have the demo-app available online...

**Comment by bek0s** [comment]
How about this? 
https://material2-test.firebaseapp.com/
Looks very up-to-date (includes lists, button-toggle, etc)

**Comment by gfrSE** [comment]
> How about this? 
https://material2-test.firebaseapp.com/
Looks very up-to-date (includes lists, button-toggle, etc)

That's it.
Found this file here: https://github.com/angular/material2/blob/master/firebase.json
Which contains this property:
```
"firebase": "material2-test",
```

Seems like its the correct firebase-app.

Thanks @bek0s !
