### ISSUE TITLE
Can't select item in md-radio-group with *ngFor and changing content

### ISSUE THREAD

**Issue by mitchhentges** [angular/material2#8140]
#### Bug, feature request, or proposal:
Bug :)

#### What is the expected behavior?
Even if the list of items in the `*ngFor` are updated (e.g. cloned), clicking on an `md-radio-button` should still make it "selected"

#### What is the current behavior?
If I provide some list of items to an `*ngFor`, but the items are _different instances_ on each angular tick, I should still be able to select the associated `md-radio-button`s for those items. For example:

```
// ...
get fish() {
  return [
    {name: 'Bob'},
    {name: 'Amir'},
    {name: 'Toyin'}
  ]
}
// ...
-----
<md-radio-button *ngFor="let f of fish" [value]="f.name">{{f.name}}</md-radio-button>
```
With the current behaviour, I can't select any of the items in this list of fish :)

#### What are the steps to reproduce?
http://plnkr.co/edit/0sX0rzMZdOHyP7NSLPkk?p=info

#### What is the use-case or motivation for changing an existing behavior?
In cases where such a list is queried from an external source (like a server), it would be a shame if the "currently-selected item state" was lost - even if the data was identical! - because the data is now different "instances"

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, Chrome 62

#### Is there anything else we should know?
Thanks for the useful, stylish components!

This may be mildly similar to #1862

**Comment by jelbourn** [comment]
Right now this is working as intended. Doing a deep comparison would be expensive, as the component has no way of knowing about the shape of the the object. Typically your radios would have `string` values.

However, you could file a separate feature request to add something that works similar to `trackyBy`- providing an accessor that's used for equality comparison.

**Comment by mitchhentges** [comment]
In [this plunker](http://plnkr.co/edit/0sX0rzMZdOHyP7NSLPkk?p=info), the `[value]` is a `string`, though, right?
```
<md-radio-button *ngFor="let f of fish" [value]="f.name">{{f.name}}</md-radio-button>
```
Wouldn't that mean that my radios _do_ have `string` values? I'm not sure that deep comparison is the issue here, but I could be mistaken 😄

**Comment by jelbourn** [comment]
I see, the radios must be using the component instance as the key for selection. Possibly still WAI, but we can discuss a bit.

**Comment by mitchhentges** [comment]
I looked for a workaround - perhaps, due to the way Angular created/moves DOM components, the `md-radio-button` isn't a child of the `md-radio-group` when clicked, so `name` isn't set correctly? That could correctly explain the problem, considering the docs for `md-radio-group`'s `name` property:

> Name of the radio button group. All radio buttons inside this group will use this name.
https://material.angular.io/components/radio/api

However, after updating the [plunker](http://plnkr.co/edit/jkwWzdIkyJ5BMdDKiH07?p=info), the buttons still aren't clickable.

If this is WAI, what can I do to make this functional? Is there a workaround?

**Comment by mitchhentges** [comment]
Talked to my buddy @hneiva, I can use `trackBy` in `*ngFor` to avoid the digest recreating the DOM elements. I've made a new [plunker](http://plnkr.co/edit/a1R3ZUs2medS4kJDEQFe?p=preview) to show the working solution, but plunker is currently not working, so I can't be sure that it's working correctly.

Thanks Jeremy for the assistance, hopefully this is enough explanation to clear up any confusion :)
