### ISSUE TITLE
[accordion]: add disabled property to CDK accordion-item

### ISSUE THREAD

**Issue by ouq77** [angular/material2#8141]
#### Proposal:

Move `common-behaviors` to CDK. 

#### What is the use-case or motivation for changing an existing behavior?

Accordion (and possibly other CDK components) need access to the `disabled` property on directives - see #7461

**Comment by ouq77** [comment]
@jelbourn / @josephperrott - which of the other common behaviors do you see being useful int he CDK?

Acceptable for the `Constructor` type to move along and be made public, or is duplication here okay?

**Comment by josephperrott** [comment]
At this point I think we should just move the `disabled` properties (`CanDisable`, `mixinDisabled`) at this point.  We can move the others as its determined they are needed and make sense to move.

You should be fine to also move the `Constructor` typing over as well.

**Comment by jelbourn** [comment]
For the time being I'd rather re-create those properties than move the mixins to the cdk until we have a greater catalog of common behaviors.
