### ISSUE TITLE
shouldPlaceholderFloat doesn't work

### ISSUE THREAD

**Issue by dwasyluk** [angular/material2#8142]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Place holder should not float on focus.

#### What is the current behavior?
Placeholder floats on focus.

#### What are the steps to reproduce?
using master latest, this does not work to stop floating placeholder and it should based on docs:
```
<mat-form-field>
  <input matInput type="text" placeholder="Alias name" shouldPlaceholderFloat="false">
</mat-form-field>

**Comment by Wykks** [comment]
try with `[shouldPlaceholderFloat]="false"`
Without `[]` you pass `false` as a string.

**Comment by josephperrott** [comment]
Closing as this should be managed through `mat-form-field`

**Comment by finalxcode** [comment]
https://material.angular.io/components/form-field/overview#floating-placeholder

**Comment by lifan0127** [comment]
@Wykks I don't think `[shouldPlaceholderFloat]="false"` works. Not sure why it is still in the documentation: https://material.angular.io/components/input/api

**Comment by cstodor** [comment]
`shouldPlaceholderFloat: boolean` is deprecated. Not sure if there are any other alternatives..

**Comment by dadasign** [comment]
You can use `floatLabel: FloatLabelType` now.

**Comment by trsh** [comment]
What are the possible values of `FloatLabelType` ?

**Comment by dadasign** [comment]
@trsh
'always' | 'never' | 'auto'
https://github.com/angular/material2/blob/d6fec3573cbc854d5bf67d920c5b0f8a6eef0c86/src/lib/core/label/label-options.ts#L16

**Comment by trsh** [comment]
Should be added to docs properly

**Comment by gotwig** [comment]
For anyone curios, if you actualy dont want floating placeholder OR floating label, use this:
<mat-form-field  floatLabel="never">
<input placeholder="My Placeholder" matInput>
</mat-form-field>

Very badly described in the docs, sadly!
