### ISSUE TITLE
feat: give the access to the "current" theme colors for custom component style

### ISSUE THREAD

**Issue by mcosta74** [angular/material2#8145]
#### Bug, feature request, or proposal:
Feature Request: I'd like to use the colors from the "current theme" inside a component style.
Reading [here](https://material.angular.io/guide/theming-your-components) seems it's only possible if I write an use a custom theme

#### What is the expected behavior?
I write a component and create a _my-component.theme.scss file like that
```
// Import all the tools needed to customize the theme and extract parts of it
@import '~@angular/material/theming';

// Define a mixin that accepts a theme and outputs the color styles for the component.
@mixin app-component-theme($theme) {
  // Extract whichever individual palettes you need from the theme.
  $primary: map-get($theme, primary);
  $accent: map-get($theme, accent);

  // Use mat-color to extract individual colors from a palette as necessary.
  .basic-container {
    background-color: mat-color($primary);
    border-color: mat-color($accent, A400);
  }
}
```

I'd like to have it applied to my component also if I use one of the pre-built themes

#### What is the current behavior?
I can use the custom component theme only if I write a custom theme and apply it

#### What are the steps to reproduce?
StackBlitz starter (using latest `npm` release): https://stackblitz.com/edit/angular-material2-issue-trw1ej<br/>

#### What is the use-case or motivation for changing an existing behavior?
I want to create a components library that can be shared across several projects. some of them do not need to have custom theme. 
In that case I'd like to have a way to use in my components the "primary" color of the selected theme (prebuilt or not)

**Comment by willshowell** [comment]
The prebuilt themes are released as compiled css, so they don't carry any information about the theme variables.

When publishing a component library you can do any the following,

1. Make prebuilt themes for your library so the consumer includes the material prebuilt theme and your library's matching prebuilt theme
2. Wrap your library's themes around the material themes so they only have to include one theme that encompasses both
2. Require consumers use custom themes
3. Write some fancy service that detects the prebuilt material theme and uses that to match one of your library's themes?

This should be much easier when css custom properties are available (I think when [IE11 support is dropped](https://github.com/angular/material2/issues/7374)).

**Comment by josephperrott** [comment]
Closing as this is not something we support

As @willshowell pointed out, with css custom properties we might be able to do things like this a bit easier.  But currently there is not direct support for a plug and play solution for theming custom components at this point
