### ISSUE TITLE
Mat-tab animation is not working

### ISSUE THREAD

**Issue by joelharisonlobo** [angular/material2#8146]
#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

In plunker its working perfectly. so no use of using plunker.
In my ng module page i have imported MatTabsModule and impoted and exported it.

    <mat-card class="card ">
        <mat-toolbar>Page Cusomization</mat-toolbar>
        <mat-tab-group class="demo-tab-group">
            <mat-tab label="Add form fields">
              <div class="demo-tab-content">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis ante augue.
                Phasellus volutpat neque ac dui mattis vulputate. Etiam consequat aliquam cursus.
                In sodales pretium ultrices. Maecenas lectus est, sollicitudin consectetur felis nec,
                feugiat ultricies mi. Aliquam erat volutpat. Nam placerat, tortor in ultrices porttitor,
                orci enim rutrum enim, vel tempor sapien arcu a tellus.
              </div>
            </mat-tab>
            <mat-tab label="Remove Form fields">
              <div class="demo-tab-content">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis ante augue.
                Phasellus volutpat neque ac dui mattis vulputate. Etiam consequat aliquam cursus.
                In sodales pretium ultrices. Maecenas lectus est, sollicitudin consectetur felis nec,
                feugiat ultricies mi. Aliquam erat volutpat. Nam placerat, tortor in ultrices porttitor,
                orci enim rutrum enim, vel tempor sapien arcu a tellus.
              </div>  
            </mat-tab>
        </mat-tab-group>

    </mat-card>

#### What is the use-case or motivation for changing an existing behavior?
In material.angular.io website mat-tab is working with animation while changing the tabs the next tab is comin from right to left.
 when i the animation is not coming but the tabs ate changing.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cli: 1.1.1
node: 7.10.0
os: win32 x64
@angular/animations: 4.4.5
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.5
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/router: 4.4.5
@angular/cli: 1.1.1
@angular/compiler-cli: 4.4.5
@angular/language-service: 4.4.5
#### Is there anything else we should know?
I need a solution for this becase im using material design in all my project.

**Comment by julianobrasil** [comment]
There are many issues aparently related to this one: #5269, #7274, #5932, #5505, #5503

**Comment by joelharisonlobo** [comment]
Your answer is not valid one. none of those issues are related to mine. Can i have more clarity on this issue?

**Comment by julianobrasil** [comment]
Sorry, @joelharisonlobo, I've jumped too fast to conclusion. It's not related to the issue I listed.

**Comment by josephperrott** [comment]
Typically we see this if your module as `NoopAnimationsModule`, this prevents the animations from running, though the state is still updated as if they had run.

If you are using `BrowserAnimationsModule` and still seeing this, we will need a reproduction case to be able to investigate further.

**Comment by joelharisonlobo** [comment]
@julianobrasil Thanks for your quick support ,I haven't used anywhere else in this project.  But i have used it in my previous project  but there also it had the same behaviour.U can check that in www.pirevolutions.com in that goto about us and click more then u can see that. i made that website for learning purpose.

**Comment by julianobrasil** [comment]
What about @josephperrott's comment?

**Comment by joelharisonlobo** [comment]
@josephperrott i have used both NoopAnimationsModule,BrowserAnimationsModule. so is that the problem?

**Comment by joelharisonlobo** [comment]
@josephperrott , Thanks for your support . i have removed noop animations form my project and it worked. but one scroll bar is coming in between the tabs.
