### ISSUE TITLE
md-input unable to bind asynchronous data in Safari

### ISSUE THREAD

**Issue by maciejsobala** [angular/material2#815]
#### Bug, feature request, or proposal:

I got following code. Template:

``` html
<md-card md-list-item *ngFor="let item of attributeTypes" layout="row">
      <md-input placeholder="name" [(ngModel)]="item.name" name="name"></md-input>
  </md-card>
```

controller:

``` ts
/* SOME IMPORTS */


@Component({
  selector: 'attribute-types',
  templateUrl: 'app/productsSettings/attributesTypes.component.html',
  directives: [
    /* some directives */
  ],
  styleUrls: ['app/productsSettings/formList.css'],
})

export class AttributeTypesComponent implements OnInit{
  attributeTypes:AttributeType[];

  model:AttributeType = new AttributeType("");

  constructor() {
  }

  ngOnInit() {
    setTimeout(()=>{
    this.attributeTypes = [new AttributeType("test"), new AttributeType("test2")]
    }, 1000);
  }

}




```

My service works asynchronously (connecting with socket and retrieving data from remote)
#### What is the expected behavior?

When my objects are injected to component, I expect them to be displayed on view.
#### What is the current behavior?

Got following exception:
Exception: Error in http://localhost:3000/node_modules/@angular2-material/input/input.js class MdInput - inline template:0:844
ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: 'null'. Current value: 'value-from-remote'
#### What are the steps to reproduce?

Don't know how Plunker deals with code, but here this example works:
http://plnkr.co/edit/xpPqGqSSRGM1H2IJUdaB?p=info
#### Which versions of Angular, Material, OS, browsers are affected?

Angular: 2.0.0-rc.4
Material: 2.0.0-alpha.6
Browsers: Safari
OS: OS X El Capitan

**Comment by Neo11** [comment]
A temporary workaround is to activate the production mode. This will disable the change check.

Or maybe you can use the async pipe with an observable?

**Comment by maciejsobala** [comment]
@Neo11 

Exception dissapeared, but my inputs, are still empty :)

**Comment by Neo11** [comment]
Maybe this works:
```
*ngFor="let item of attributeTypes | async"
```
In your controller import the async pipe und save the Observable, don't subscribe it.

**Comment by maciejsobala** [comment]
1. Still same error under Safari.

2. Could you tell me, what is the difference (pros/cons) of using | async pipe, vs subscribing to observable/subject? Apart of no 1.

**Comment by Neo11** [comment]
1. Then I have no more Ideas.

2. I think the code ist cleaner and the Observable gets only subscribed if the element gets rendered.

**Comment by maciejsobala** [comment]
@Neo11 
1. Thanks for your help :)
2. Thanks for info

One more information:
I have tried to run my code on mobile safari - works (I guess, because I don't have access to console) - everything loads as in Desktop Chrome for example. I haven't used real iPhone/iPad - I launched site via emulator.

**Comment by Judp0m** [comment]
FYI, I ran in the same issue using rc5 and alpha.7-4.
Sticking with the <input> until the bug is fixed.

**Comment by mmalerba** [comment]
this should be fixed with the new `md-input-container` since you can put the `ngModel` on the native `input` element.
