### ISSUE TITLE
matTable Use object sub keys (key1.subkey1) for columns definition

### ISSUE THREAD

**Issue by sebastiendan** [angular/material2#8151]
#### Bug, feature request, or proposal:
Use multi-level keys for columns definition in matTable.

Example (addresses): 
```
columns = ['firstName', 'lastName', 'address.street'];
```

#### What is the expected behavior?
matTable should be able to render data from 'address.street' attribute key

#### What is the current behavior?
matTable doesn't render data for multi-level keys

#### What are the steps to reproduce?
Use matTable with data structure from the example below

#### What is the use-case or motivation for changing an existing behavior?
APIs usually return complex objects. Such objects should be handled in matTable, instead of mapping them to plan objects

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular-Material: 2.0.0-beta.12
Angular: 4.4.6
Typescript: 2.5.3

#### Is there anything else we should know?
Nope

**Comment by sebastiendan** [comment]
My bad, I got confused with something on my side...

Sorry for this useless issue! And thanks!

**Comment by eb-arun** [comment]
How to handle the same for dynamic table column. 
`<ng-container [matColumnDef]="column" *ngFor="let column of plantColumns, let i = index" [sticky]="i == 0 ? true : false">
        <mat-header-cell mat-sort-header *matHeaderCellDef>{{column}}</mat-header-cell>
        <mat-cell *matCellDef="let element">{{element[column]}}</mat-cell>
      </ng-container>`
