### ISSUE TITLE
svgIcon not usable in iteration (ngFor)

### ISSUE THREAD

**Issue by emreavsar** [angular/material2#8152]
#### Bug:
Assume a component which renders a `mat-icon` based on `@Input()` value:

```
@Component({
  selector: 'line',
  templateUrl: 'line.component.html'
})
export class LineComponent {
  @Input()
  lightIcon = 'red';
  
  constructor(private matIconRegistry: MatIconRegistry, sanitizer: DomSanitizer){
    matIconRegistry
      .addSvgIcon('red', sanitizer.bypassSecurityTrustResourceUrl('./red.svg'))
      .addSvgIcon('green', sanitizer.bypassSecurityTrustResourceUrl('./green.svg'))
  }
}
```

The icon is rendered inside the view like this:
```
<mat-icon [svgIcon]="lightIcon"></mat-icon>
```

The parent component with has a list of lightIcons:
```
@Component({
  selector: 'material-app',
  templateUrl: 'app.component.html'
})
export class AppComponent {

  lines = [{
    lightIcon: 'red'
  }, {
    lightIcon: 'red'
  }, {
    lightIcon: 'green'
  }];
  
  private version = VERSION;
  
}
```

And uses the variable to iterate and render the child component:
```
<line *ngFor="let line of lines" [lightIcon]="line.lightIcon"></line>
```

The icons are not correctly shown, in fact the last icon will the one for all (in this case all line items have green icons displayed). However the value of the lightType is saved correctly in the child component.

#### What is the expected behavior?
The icon should be the one from the components variable.
According to the 

#### What is the current behavior?
All icons are the same. See plunkr
Also try to toggle the icon, which makes stuff easier to understand.

#### What are the steps to reproduce?
http://plnkr.co/edit/jfwgPvhavHoHHz8VdtZf?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.x
Material 2 beta 12

**Comment by crisbeto** [comment]
Everything works as expected. Your icons appear not to be changing, because the circle colors are being assigned via CSS classes (in this case `st0` and `st1`) which are inside inline `style` tags. These style tags bleed into each other and the last color ends up overwriting everything else (in this case it's the green). Here's a forked Plunkr where the only thing I changed was to set the `fill` using the SVG attribute instead of the CSS class: http://plnkr.co/edit/0ihAaOez1O65p4GdZpCY?p=preview

**Comment by emreavsar** [comment]
Damn! thanks for the fix and the info. unfortunately the svg was created by a tool.

**Comment by crisbeto** [comment]
I haven't used Illustrator in a while, but I remember it having an "Export for Web" option specifically for SVG which I expect would avoid issues like this one.

**Comment by emreavsar** [comment]
Thanks for the info. But it was exported through sketch.

Kristiyan Kostadinov <notifications@github.com> schrieb am Mi., 1. Nov.
2017 um 07:32 Uhr:

**Comment by crisbeto** [comment]
Ah, I was looking at the comment:

```
<!-- Generator: Adobe Illustrator 21.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
```

**Comment by narendrasinghrathore** [comment]
@crisbeto 
`Error retrieving icon: Unable to find icon with the name ":static"`

Unable to register .svg and bind to mat-icon svgIcon property in ngFor loop 

Angular v7
Material v7

**HTML**
`    <div *ngFor="let selector of selectors">
         <mat-icon svgIcon="{{selector}}"></mat-icon>
          <p>{{selector}}</p>
    </div>
`
**COMPONENT**
` selectors = ['strength', 'endurance'];`
` 
    iconRegistry.addSvgIcon('endurance',  sanitizer.bypassSecurityTrustResourceUrl('assets/svg-icons/endurance.svg'));

    iconRegistry.addSvgIcon('strength',  sanitizer.bypassSecurityTrustResourceUrl('assets/svg-icons/strength.svg'));
`



Plunker demo below:

https://angular-m9w9ez.stackblitz.io
