### ISSUE TITLE
tooltip when hover the mouse on checkbox

### ISSUE THREAD

**Issue by Anutiru** [angular/material2#8154]
import {Directive, ElementRef, Input} from '@angular/core';
import {BootstrapPlugins} from "./tooltip-models";

const selector = 'fit-tooltip';
interface Tooltip {
    title: string;
    content: string;
}
@Directive({
    selector: `[${selector}]`
})
export class FitTooltipDirective {
    @Input(selector)
    params: Tooltip;

    constructor(private elRef: ElementRef) {
    }
    ngAfterViewInit(): void {
        const container = $(this.elRef.nativeElement) as BootstrapPlugins;
        container.popover({
            container,
            html: true,
            content: this.params.content,
            title: this.params.title,
            trigger: 'hover',
            placement: 'top',
            toggle: 'toggle',
            value: 'top'
        }).data('bs.popover')
            .tip()
            .addClass('ud-popover');
    }
}

**Comment by Anutiru** [comment]
i want ot write unittest usig jasmine andkarma and iam new so please help me

**Comment by andrewseguin** [comment]
Please open issues only for bugs and features. For help troubleshooting, ask our great community at StackOverflow, Google groups, Gitter, etc
