### ISSUE TITLE
mat-select - option for overlapTrigger like mat-menu

### ISSUE THREAD

**Issue by Chrisis52** [angular/material2#8155]
Feature request

What is the expected behavior?

Add option to specify the position of the opening overlay just below the Y axis of mat-select that triggers it.

What is the current behavior?

overlay of the mat-select overlap field and label and is Y positioned depending of the item selected in list( the highest the index, the highest it's positioned on the Y axis)

What is the use-case or motivation for changing an existing behavior?

Just like mat-menu and its overlapTrigger option, users are used to see a select list drops down just under its trigger and always see the label of the select.

Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All

**Comment by josephperrott** [comment]
Closing as `MatSelect`'s overlap positioning is directly defined in the [material spec](https://material.io/guidelines/components/menus.html#menus-behavior)

**Comment by bsteffl** [comment]
@josephperrott Can you clarify it looks like the [spec](https://material.io/design/components/menus.html#dropdown-menu) says that it can be placed below the element by default?  

###Dropdown menu 
"_A dropdown menu is typically positioned below the element that generates it._"

####Text field dropdown menu
"_On desktop, a text field dropdown menu appears below the element triggering the dropdown. On mobile, a text field dropdown menu can open a native picker._"
