### ISSUE TITLE
mat-select displaced/shifted down

### ISSUE THREAD

**Issue by d4hines** [angular/material2#8163]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Mat-options should appear in proximity to the select

#### What is the current behavior?
The options are being oddly displaced downward (not always though - the occurrence seems random).
![image](https://user-images.githubusercontent.com/25231383/32243084-d5de07e8-be4a-11e7-9d7e-42419c800f6f.png)

#### What are the steps to reproduce?
I can't tell you what logical steps reproduce, but I started randomly removing items from my app until I boiled down a reproducible case, which can be found here
https://stackblitz.com/edit/angular-jzcpbd

Some additional clues: As I demonstrate in the stackblitz, the presence of the flexbox container holding the check-boxes seems to trigger the problem. Moreover, the problem only occurs when I use a getter in the checkbox for loop - switching to a constant value expression, bizarrely enough, removes the issue.

#### What is the use-case or motivation for changing an existing behavior?
Can't really use mat-select without fixing this inconsistent behavior or finding viable workaround.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Latest Versions of Angular and Material.
- Tested on (Windows) Chrome 62.0.3202.75 and Firefox 46.0.1

#### Is there anything else we should know?
Repo of source code can also be found here for convenience
https://github.com/d4hines/broken-mdselect

**Comment by willshowell** [comment]
As a note, the getter isn't causing the issue, but returning a new array each time is. You can see by switching it to this, that it works:

```ts
get checks() {
  return this.checks2;
}

checks2 = [
  { formField: '1', description: '1' },
  { formField: '2', description: '2' },
  { formField: '3', description: '3' },
  { formField: '4', description: '4' },
  { formField: '5', description: '5' },
];
```

**Comment by crisbeto** [comment]
As a rule of thumb, whatever you're returning from a getter or a function into the view will be re-computed on every change detection cycle which is both inefficient and can cause weird things to happen. Closing as a non-issue.

**Comment by d4hines** [comment]
Thanks for the help guys. This resolved the issue for us.
