### ISSUE TITLE
Dialog in docs refer to MdDialog and not MatDialog

### ISSUE THREAD

**Issue by guilhermejcgois** [angular/material2#8164]
#### Bug, feature request, or proposal:
In the [docs](https://material.angular.io/components/dialog/overview), is used the old Md prefix, isn't possible to provide some toggle between Md and Mat in the example code? Also, could be good some disclaimer about that update to use Mat instead Md prefix.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Is there anything else we should know?
**Sorry if isn't the right place to say this.**

**Comment by crisbeto** [comment]
Most likely you're getting a cached version of the docs. The caching issues should be resolved next time we release.

**Comment by guilhermejcgois** [comment]
any estimates of the next release, @crisbeto?
