### ISSUE TITLE
can i use two MdDatepicker in one component?

### ISSUE THREAD

**Issue by arisbro8** [angular/material2#8169]
This is my code :
```
<md-input-container class="example-full-width">
      <input class="full-width" mdInput formControlName="JoinDateUtc" [mdDatepicker]="picker" placeholder="Join Date">
      <md-datepicker-toggle mdSuffix [for]="picker"></md-datepicker-toggle>
      <md-datepicker #picker></md-datepicker>
</md-input-container>

<md-input-container class="example-full-width">
      <input class="full-width" mdInput formControlName="LeftDateUtc" [mdDatepicker]="picker" placeholder="Left Date">
      <md-datepicker-toggle mdSuffix [for]="picker"></md-datepicker-toggle>
      <md-datepicker #picker></md-datepicker>
</md-input-container>
```
and i get an error :
Error: An MdDatepicker can only be associated with a single input.

**Comment by arisbro8** [comment]
solved. thanks

**Comment by Werner-Dohse** [comment]
@arisbro8 How did you solve it?

**Comment by willshowell** [comment]
@Werner-Dohse probably by creating two separate `mat-datepicker`s and assigning them different template references.

**Comment by ziaongit** [comment]
@willshowell just use different ID for each
Example:
`<md-input-container class="example-full-width">
      <input class="full-width" mdInput formControlName="JoinDateUtc" [mdDatepicker]="picker" placeholder="Join Date">
      <md-datepicker-toggle mdSuffix [for]="picker"></md-datepicker-toggle>
      <md-datepicker #picker></md-datepicker>
</md-input-container>

<md-input-container class="example-full-width">
      <input class="full-width" mdInput formControlName="LeftDateUtc" [mdDatepicker]="pickerTo" placeholder="Left Date">
      <md-datepicker-toggle mdSuffix [for]="pickerTo"></md-datepicker-toggle>
      <md-datepicker #pickerTo></md-datepicker>
</md-input-container>`

I changed the ID to pickerTo at three places

```
[mdDatepicker]="pickerTo"
mdSuffix [for]="pickerTo"
<md-datepicker #pickerTo>
```

**Comment by jabbar86** [comment]
Use like this : 

<mat-form-field>
  <input matInput [matDatepicker]="picker1" placeholder="Choose a start date" [(ngModel)]="inputStartDate">
  <mat-datepicker-toggle matSuffix [for]="picker1"></mat-datepicker-toggle>
  <mat-datepicker #picker1 [startAt]="startDate"></mat-datepicker>
</mat-form-field>

<mat-form-field>
  <input matInput [matDatepicker]="picker2" placeholder="Choose an end date" [(ngModel)]="inputEndDate">
  <mat-datepicker-toggle matSuffix [for]="picker2"></mat-datepicker-toggle>
  <mat-datepicker #picker2 [startAt]="endDate"></mat-datepicker>
</mat-form-field>

**Comment by manojadams** [comment]
The problem is solved after using the code like this:

(i.e.) Changing picker to picker2 when used for the second time.

<md-input-container class="example-full-width">
      <input class="full-width" mdInput formControlName="JoinDateUtc" [mdDatepicker]="picker" placeholder="Join Date">
      <md-datepicker-toggle mdSuffix [for]="picker"></md-datepicker-toggle>
      <md-datepicker #picker></md-datepicker>
</md-input-container>

<md-input-container class="example-full-width">
      <input class="full-width" mdInput formControlName="LeftDateUtc" [mdDatepicker]="picker2" placeholder="Left Date">
      <md-datepicker-toggle mdSuffix [for]="picker2"></md-datepicker-toggle>
      <md-datepicker #picker2></md-datepicker>
</md-input-container>

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.

**Comment by VSV6** [comment]
Thank you so much. It helped me :)
