### ISSUE TITLE
md-select, md-datepicker, md-snackbar, md-searchbox, md-autocomplete

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#817]
@kara @jelbourn 
Are you ready for these PRs or I must wait for beta?
I almost finished, specs and testing need 2 week-ends.

**Comment by jelbourn** [comment]
@zigzag95 Are you saying you've been working on these components? We already have people working on some of these. Please read our [contributor guidelines](https://github.com/angular/material2/blob/master/CONTRIBUTING.md#-want-a-feature) and follow the process there if you want to contribute something like a new component.

**Comment by tylerjgarland** [comment]
@jakemac53, do you know where these components are being tracked? I was following this issue for updates. Thanks!

**Comment by tylerjgarland** [comment]
@jelbourn, Accidentally linked someone else's username in the initial post. Commenting again to make sure you get the notification.

**Comment by zigzag95** [comment]
I just ported material ui from react

**Comment by jelbourn** [comment]
md-select #118 
md-autocomplete #117 
toast / snackbar #115 

Not sure what you mean by searchbox.
