### ISSUE TITLE
DatePicker binding with value or (ngModel)?

### ISSUE THREAD

**Issue by zijianhuang** [angular/material2#8171]
#### Bug or proposal:

In some places, I use 
```html

            <mat-form-field fxFlexFill>
                <input matInput [matDatepicker]="picker" placeholder="Date" [value]="buffer.timeUtc" readonly />
                <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
            </mat-form-field>
            <mat-datepicker #picker (selectedChanged)="updateTimeUtc($event)" [startAt]="now"></mat-datepicker>
```
Property timeUtc of the buffer object works well.

In the other place, I used:

```html
    <mat-form-field fxFlexFill>
        <input matInput [matDatepicker]="pickerReminder" placeholder="Date" [value]="selectedDate" readonly />
        <mat-datepicker-toggle matSuffix [for]="pickerReminder"></mat-datepicker-toggle>
    </mat-form-field>
    <mat-datepicker #pickerReminder></mat-datepicker>
```

The selectedDate object is not working well: the picker could put a date to the input box, however, the object does not get a proper value. 

Now I have:
```html
    <mat-form-field fxFlexFill>
        <input matInput [matDatepicker]="pickerReminder" placeholder="Date" [(ngModel)]="selectedDate" readonly />
        <mat-datepicker-toggle matSuffix [for]="pickerReminder"></mat-datepicker-toggle>
    </mat-form-field>
    <mat-datepicker #pickerReminder></mat-datepicker>
```

The binding is working well.

I see that [value] is Material2 way of data binding with input, and [(ngModel)] is Angular2 way of binding.

#### What is the use-case or motivation for changing an existing behavior?

The material2 doc should had mentioned how to do data binding with DatePicker along with Input.

Current implemented usages look a bit inconsistent.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4.4.5, Material 2.0.0-beta.12

**Comment by mmalerba** [comment]
`ngModel` and `formControl` currently have the correct behavior. `value` should behave the same way but is currently not working right due to a bug (will be fixed by https://github.com/angular/material2/pull/7831)
