### ISSUE TITLE
Separate Calendar component

### ISSUE THREAD

**Issue by DaltonNotetech** [angular/material2#8173]
#### proposal
Make mat-calendar a separate component

#### What is the expected behavior?
I need a mat-calendar that don't float and is not tied to date picker

#### What is the current behavior?
Now only way to add calendar is using mat-datepicker

#### What is the use-case or motivation for changing an existing behavior?
Calendar is a commonly used component in mobile devices

**Comment by willshowell** [comment]
`MatCalendar` is already exported from `MatDatepickerModule`

```html
<mat-calendar [selected]="selectedDate" (selectedChange)="selectedDate = $event">
</mat-calendar>
```

**Comment by josephperrott** [comment]
Closing as `MatCalendar` is already available.

**Comment by architagr** [comment]
Can I have the link to the documentation for this component.

As where ever I search I only get reference to the below URL:

https://material.angular.io/components/datepicker/overview

**Comment by brunovinicius** [comment]
Also couldn't  find any reference to this on the documentation. Maybe @willshowell can shime in with the link or maybe its really MIA.

**Comment by willshowell** [comment]
@brunovinicius it was a while ago that I looked into this, but IIRC it was never documented

**Comment by brunovinicius** [comment]
I see. Do you think we should open a new ticket for fixing this or is it already tracked?

**Comment by willshowell** [comment]
Yeah I think a ticket specifically for documentation of `MatCalendar`'s availability would be most effective. I can't seem to find an existing one.

**Comment by andreisrob** [comment]
Can someone post a link to the source so we can at least see the component's Inputs?

**Comment by ialex90** [comment]
Just wondering the same about the doc, is there any ticket where to follow the status or anyone looking at the task of creating this documentation?

Thanks
