### ISSUE TITLE
matselect Cannot read property 'nativeElement' of undefined after upgrading to ng5

### ISSUE THREAD

**Issue by dagyrox** [angular/material2#8178]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Be able to use a matselect without console errors.

#### What is the current behavior?
matselect throws errors when selecting items

#### What are the steps to reproduce?
https://angular-material2-ng5-matselect-issues.stackblitz.io

create app using ng5 and latest material(beta.12).

add matformfield with matselect
give it some items
run the app
select an item / click away

notice errors in console

#### What is the use-case or motivation for changing an existing behavior?
motivation should be...having an app with out console errors

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng5, material beta.12

#### Is there anything else we should know?

MatSelect.html:1 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at MatSelect._onFadeInDone (select.es5.js:744)
    at Object.eval [as handleEvent] (MatSelect.ngfactory.js:70)
    at handleEvent (view.js:129)
    at callWithDebugContext (services.js:843)
    at Object.debugHandleEvent [as handleEvent] (services.js:414)
    at dispatchEvent (util.js:172)
    at eval (element.js:219)
    at eval (animation_renderer.js:116)
    at Array.forEach (<anonymous>)
    at eval (animation_renderer.js:114)

**Comment by crisbeto** [comment]
This has been fixed in master and will be in the next release.

**Comment by dagyrox** [comment]
@crisbeto Thank you.  I've opened another issue before reading your response.  That one maybe related, but is related to 1.2/ng5 hybrid app.  Sorry if these were not necessary, but my searching yielded no results.  Thank you again.
