### ISSUE TITLE
Site with documentation and preview of the components

### ISSUE THREAD

**Issue by drager** [angular/material2#818]
Hi,

I have created a repository that is a Angular 2 application that displays the documentation of Angular 2 Material simply because there was no site present of that kind. The documentation is just the `README.md` files found in each component found [here](https://github.com/angular/material2/tree/master/src/components) as well as the `core` folders documentation. I have just generated HTML files from those markdown files and added some Angular components which displays the html. The repository can be found [here](https://github.com/drager/material2-preview) and the site [here](https://drager.github.io/material2-preview/).

I would gladly make a pull request to be added to the material2 repository if you think this is a good idea and good fit. If you do not think so, would I like to keep it in the repository where it is today or if you do not want that either I would have no problem removing the repository and the site if you want that.

I would gladly continue to work on it if you think it is a good idea.

Please let me know what you think.

Thank you!

**Comment by eserlan** [comment]
+1

**Comment by Ermans** [comment]
+1
You can also add these links: https://github.com/angular/material2/wiki/Design-doc-directory

**Comment by jonathan-casarrubias** [comment]
Really nice!

**Comment by jelbourn** [comment]
@drager Thanks for making this! We have people working on our docs site for https://material.angular.io, but this is a nice site for people to look at in the interim.

**Comment by drager** [comment]
@Ermans: Will do that! Great idea.

@jelbourn: Ah alright, then I will continue to work on it and fix things until the official site is ready. Please let me know if you are in the need of any help at all for that site. Thanks
