### ISSUE TITLE
[snack-bar] onAction subject never completes

### ISSUE THREAD

**Issue by willshowell** [angular/material2#8181]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?

Subscribing to `onAction()` will result in a subscription that never completes unless the action button is clicked.

#### Expected behavior

`onAction()` completes when the snackbar ref is destroyed, I suppose in `_finishDismiss()`.

#### Reproduction

https://stackblitz.com/edit/angular-material2-issue-l1ymh2?file=app/app.component.ts

#### Motivation

I wish to open a snack-bar that has a duration longer than the expected lifetime of the component opening it. When the action is clicked, I would like to navigate to a new route.

I am unable to unsubscribe from the subscription in `ngOnDestroy` since the snackbar action may be available after the component is destroyed.

**Comment by AsserHamad** [comment]
WTF?

**Comment by AsserHamad** [comment]
There appears to already be a method which fires an action once the snackbar is destroyed (afterDismissed), but right now there's nothing to replace the old onAction command

**Comment by crisbeto** [comment]
`onAction` is still there.
