### ISSUE TITLE
Message within table while data is loading

### ISSUE THREAD

**Issue by dekhaus** [angular/material2#8184]
Hi All

I've got a working mat-table - where data is loaded from an API via HTTP.  Works great.

The only issue I have is that the data appears empty while the data is loading.

My DataSource subclass (RequestDataSource) uses a HTTP based service and RequestDataSource has a public boolean variable ('loading') which I initialize to true and set to false when the Observable in the 'connect()' method is done loading data.

Updating the state of my 'loading' variable works ('Loading ...' appears on the page when the data is loading and disappears when its done).

I'd like to either completely hide the table while the data is loading or - better yet, have the table display a sensible message (within its borders) when the data is loading.  Is that possible and if so - how ?

p.s. Directly 'hiding' the 'mat-table' element does not work

Thanks
Dave

![screen shot 2017-11-01 at 2 54 12 pm](https://user-images.githubusercontent.com/7830/32299930-99775d2a-bf14-11e7-92b9-d5e609dd6ae6.png)

**Comment by xipheCom** [comment]
what do you mean with hiding? *ngIf should work, if not do it within a wrapper. Do not forget to set changeDetection to "onPush" and pipe it with "async" if you handle with observable data (what a http request is). You should upload a plunker, so we can see your problem and play around with it.

I do not think it is an issue.

**Comment by dekhaus** [comment]
Hi

By 'hiding' I meant adding a 'loading' attribute to 'mat-table' ..

<mat-table #table [dataSource]="dataSource" [hidden]="loading">

this does not work becuase the table is always visible.  Initially its visible and empty and then once the data is downloaded - its populated with data.

Not sure what you mean by 'changeDetection'.  Is there documentation for this as well as the 'async' pipe you mention ?

Thanks
Dave

**Comment by andrewseguin** [comment]
Please refer all troubleshooting questions to our community at StackOverflow, Angular Material mailing lists, Gitter, etc. We try to keep our issues here only open for bugs and feature requests.

If you end up running into a bug trying to implement this, feel free to open an issue.

**Comment by ewaschenko** [comment]
@dekhaus Did you find a way to display a message within the table?  I tried @andrewseguin 
[HTTP loading spinner](https://stackblitz.com/angular/amyknpbyaab?file=app%2Ftable-http-example.ts) but it doesn't work quite right in the table runs off the page 

![table](https://user-images.githubusercontent.com/9055167/40934343-7a2cceea-6802-11e8-90ae-51bc23446018.png)
