### ISSUE TITLE
Datepicker Issue - Calendar is wrong & picks the wrong day

### ISSUE THREAD

**Issue by Nicosoft** [angular/material2#8185]
#### Bug: Datepicker component 
3 issues, see screenshots
- ISSUES on Mac OS Sierra version 10.12.6, with Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Same system with Safari: NO ISSUE
- My colleague on Window 10 with Chrome (Version 62.0.3202.75 (Official Build) (64-bit)) : NO ISSUE

#### What is the expected behavior?
1. The calendar should display NOV when I select month November 2017
2. The calendar should display for example November 2017 the list of days from 1 to 30.
3. When I select the date 11/5/2017, the text field should display 11/5/2017.

Screenshot on Windows 10 with Chrome: NO ISSUE
![beeb88da-6abb-4b84-b379-ee962cb0720d](https://user-images.githubusercontent.com/4625910/32310142-71b2e9f0-bfe4-11e7-8290-e40866f25fda.png)

#### What is the current behavior?
1. The calendar displays OCT when I select month November 2017
2. The calendar displays for example November 2017 the list of days are from 31 to 29
3. When I select the date 11/**1**/2017, the text field should display 11/**2**/2017.

Screenshot showing the issues #1 and #2:

<img width="1311" alt="screen shot 2017-11-02 at 3 20 58 pm" src="https://user-images.githubusercontent.com/4625910/32310095-156684e0-bfe4-11e7-9edd-ea355410fb75.png">

Screenshot showing the issue #3:
<img width="643" alt="screen shot 2017-11-02 at 3 21 26 pm" src="https://user-images.githubusercontent.com/4625910/32310136-62230178-bfe4-11e7-9aea-a03a8cb6fc30.png">

#### What are the steps to reproduce?
Go to: https://material2-dev.firebaseapp.com/datepicker

#### What is the use-case or motivation for changing an existing behavior?
Does it come from my computer or Datepicker? How to fix it, because this is very disturbing for a user.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
no comment

#### Is there anything else we should know?
My timezone is "Australia/Sydney".

Thanks.

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/4358

**Comment by julianobrasil** [comment]
There's a PR for this: #7858

**Comment by mmalerba** [comment]
Hmm my PR fixes it by explicitly checking for IE. I really don't want to get into manually checking for a bunch of  browser + OS combinations. It would be nice if there was some way to create a more generic test for this...

In the mean time @Nicosoft I believe this only happens with the `NativeDateAdapter`, you could try using the `MomentDateAdapter` instead
