### ISSUE TITLE
Please provide an option to select the time as well

### ISSUE THREAD

**Issue by ApoorvBarwa** [angular/material2#8189]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Time selection should also be available along with date.

#### What is the current behavior?
Only date picker is available as of now

#### What are the steps to reproduce?
On installing the angular material and using the `import {MatDatePickerModule} from '@angular/material'`

#### What is the use-case or motivation for changing an existing behavior?
A feature should be available to select the time while selecting the date

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4
Material 2
Windows 7
Typescript 2.2.0
Chrome Version 61.0.3163.100 

#### Is there anything else we should know?
Please let me know if this is feature is already available

**Comment by benb7760** [comment]
Duplicate of #5648. Please search before creating issues

**Comment by ApoorvBarwa** [comment]
ooops sorry for the inconvenience

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
