### ISSUE TITLE
md to mat : missing some elements

### ISSUE THREAD

**Issue by trichetriche** [angular/material2#8191]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

When I use a tag starting with `mat-`, I expect it to behave like a material directive, and when I use a tag starting with `md-`, I don't expect it to behave like a material directive

#### What is the current behavior?

See above

#### What are the steps to reproduce?

The concerned tag is `mat-card-actions`, I need to use `md-card-actions`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

2.0.0-beta.12

**Comment by willshowell** [comment]
In beta.12, all `md*` directives are removed. Source from beta.12 tag,

https://github.com/angular/material2/blob/9fadf12c2941b739aa87e6d741b79dabc919dc61/src/lib/card/card.ts#L52-L67

**Comment by trichetriche** [comment]
Well then I don't know : here is with `md` : 

![image](https://user-images.githubusercontent.com/7789922/32330024-1781f228-bfdf-11e7-8493-0e4c40398149.png)

And here it is with `mat` : 

![image](https://user-images.githubusercontent.com/7789922/32330051-321a13fe-bfdf-11e7-9989-0995e563d84c.png)

**Comment by willshowell** [comment]
1. Can you make a stacblitz reproduction?
2. Are you sure you have no overriding global styles?
3. Does `<mat-card-actions>` have the `.mat-card-actions` class applied to it? What about `<md-card-actions>`?
4. Are you positive you're using beta.12? Consider removing node modules and reinstalling.

**Comment by trichetriche** [comment]
Oh ok, I tried to reproduce it on StackBlitz (thanks for it BTW, I was doing my best on Plunkr for reproduction), and it did the same. 

It's only when I saw your 3) that I got it : there's a negative margin of -16px. 

Since I'm using a 12px padding, that's why it seems "better" with `md` ! 

Sorry for bothering you, I'm closing this issue now.
