### ISSUE TITLE
Getting started is not working on a new angular-cli generated project

### ISSUE THREAD

**Issue by Gideonnn** [angular/material2#8192]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Style applied to a button element after following the official getting started guide

#### What is the current behavior?
No style is applied to button elements

#### What are the steps to reproduce?
Generate a new project with angular-cli and follow the [getting started guide](https://material.angular.io/guide/getting-started)

What I did:

Install some npm packages
`npm install --save @angular/material @angular/cdk`
`npm install --save @angular/animations`

Edit app.module.ts:
```
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

import { MatButtonModule, MatCheckboxModule } from '@angular/material';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AppRoutingModule,
    MatButtonModule,
    MatCheckboxModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Add this to styles.scss
`@import "~@angular/material/prebuilt-themes/indigo-pink.css";`

Install hammerjs
`npm install --save hammerjs`

Add import to main.ts
```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import 'hammerjs';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule);
```

Add this to the head section of index.html
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

**Comment by willshowell** [comment]
What is `AppComponent`'s template?

**Comment by Gideonnn** [comment]
@willshowell Ahh yes, I forgot that one. Here it is:

```
import { Component } from '@angular/core';

@Component({
  selector: 'gid-root',
  template: `
    <router-outlet></router-outlet>
    <button md-button>Click me!</button>
  `,
  styles: []
})
export class AppComponent { }
```

**Comment by willshowell** [comment]
beta.12 and up [require](https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes) using all `mat*` directive selectors. You may have a cached version of the docs, but they should show the following. If they don't, try clearing your cache and reloading.


Attribute | Description
-- | --
mat-button | Rectangular button w/ no elevation.
mat-raised-button | Rectangular button w/ elevation
mat-icon-button | Circular button with a transparent background, meant to contain an icon
mat-fab | Circular button w/ elevation, defaults to theme's accent color
mat-mini-fab | Same as mat-fab but smaller

**Comment by Chan4077** [comment]
Here's a guide on how to clear the cache: https://github.com/angular/material2/issues/7715#issuecomment-335835631

**Comment by josephperrott** [comment]
Closing as the library is moved to the `mat` prefix.
