### ISSUE TITLE
UI Bug: Text inside Mini Fab Buttons not visible

### ISSUE THREAD

**Issue by praveeno** [angular/material2#8193]
https://github.com/angular/material2/blob/cf11ff2e3ff1665236389d1c032628cf4276e78f/src/material-examples/button-types/button-types-example.html#L59

text inside mini fab buttons not visible properly and it distort UI, not looking good.
![image](https://user-images.githubusercontent.com/19618730/32329874-5267d43c-c004-11e7-9bc3-29418731ff68.png)

we should put the text bottom of the fab.

**Comment by donroyco** [comment]
According to the [Material Guidelines](https://material.io/guidelines/components/buttons-floating-action-button.html) on Floating Action Buttons it should never handle any text, just icons. So your remark doesn't really make sense. It's only for reference purposes only.

**Comment by willshowell** [comment]
The alignment bug should also be fixed by https://github.com/angular/material2/pull/7850

**Comment by praveeno** [comment]
@donroyco got it, thanks bro. it's just feel annoying, when i saw misalign UI.

**Comment by praveeno** [comment]
as suggest by @willshowell, I closing this one
