### ISSUE TITLE
Example of fullscreen side-nav does not work if element with fixed height (e.g. toolbar) is added before the content

### ISSUE THREAD

**Issue by OddDev** [angular/material2#8194]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The fullscreen side-nav should remove space from fixed height elements from the remaining content. For example if a toolbar, opening the side-menu itself via a hamburger icon or something, is added, a component beneath the toolbar should refer to the remaining space instead of the remaining space plus the toolbar. 

#### What is the current behavior?
Adding a toolbar leads to a scrollbar when the content beneath the toolbar is set to 100 % since this 100 % does _not_ refer to the remaining space (without the toolbar) but to the remaining space plus the toolbar. You get a scrollbar which lets you scroll exactly the pixels the fixed-height element (e.g. the toolbar) is set to (in case of a mat-toolbar 64 px). 

#### What are the steps to reproduce?

Stackblitz:
https://stackblitz.com/edit/angular-material2-issue-zuymss

Step by Step guide:
- Create an app with the given example at the paragraph starting with "
For a fullscreen sidenav ..."(https://github.com/angular/material2/blob/master/src/lib/sidenav/README.md#examples)
- Add a fixed height element
   - It doesn't matter whether it's in the fullscreen-content-wrapper or above it
   - It doesn't even matter if it's above the whole sidenav element (it just gets displayed above the drawer but still produces the same error)
- Recognize the wild toolbar on the right

#### What is the use-case or motivation for changing an existing behavior?
To easily have a toolbar opening up the drawer and so on and just use the remaining space with a big container wrapper. For example you may want to show a list stretched to fit the whole space under the toolbar. This is not possible at the moment except if you add a height like calc(100 % - 64 px) for example.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Most recent, all of them

#### Is there anything else we should know?
You need to fiddle a little bit with this. There is no clean way to overcome this behavior. We've played around with flex-boxes and wrappers and everything but sooner or later you always get stuck with this issue or something resulting from it (like not having a stretched parent-container at all for example).

**Comment by josephperrott** [comment]
Closing as this is working as expected and should not be the responsibility of the sidenav to make this determination.

This is happening because you are applying `height: 100%` to the `my-content` class as you noted. This element fills 100% of the relative container, but has a sibling element that is `80px` as well, which causes `80px` of oveflow that needs a scroll bar.

A couple options are to define the height as `calc(100% - 64px)` or you could use flex to have the `my-content` div fill the remaining space and only overflow if needed.
