### ISSUE TITLE
'MomentDateAdapter' does not implement inherited abstract member 'fromIso8601'

### ISSUE THREAD

**Issue by Hugmungus** [angular/material2#8197]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should build correctly

#### What is the current behavior?
Failing on build due to 'fromIso8901' being missing in current build of moment-date-adapter, but not in 'date-adapter.ts' base class found in the official material release 2.0.0-beta.12

#### What are the steps to reproduce?
Add the following to your package.json
"@angular/material": "2.0.0-beta.12",
"@angular/material-moment-adapter": "https://github.com/angular/material2-moment-adapter-builds",

#### What is the use-case or motivation for changing an existing behavior?
Build needs to work appropriately 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 5.0.0-rc.9
Material - 2.0.0-beta.12
Typescript - 2.5.3

#### Is there anything else we should know?
This was reported on the material2-moment-adapter-builds repository [here](https://github.com/angular/material2-moment-adapter-builds/issues/1). Per instructions on the home page of that repository, re-posting the issue here.

https://github.com/angular/material2-moment-adapter-builds/issues/1

**Comment by rthewhite** [comment]
Pinning the version of material-moment-adapter will fix the problem for now.
https://github.com/angular/material2-moment-adapter-builds.git#2.0.0-beta.12-00de3f6

After it's released officially it will work fine with Angular Material.

**Comment by IagoBarboza** [comment]
It works!!
Thanks @rthewhite!

**Comment by IagoBarboza** [comment]
It works!!
Thanks, @rthewhite.

**Comment by jelbourn** [comment]
Closing this since there's no code change to be made, just needs a release

**Comment by marksas** [comment]
So what's the solution?
