### ISSUE TITLE
bug(sort-header): sort icon should rotate

### ISSUE THREAD

**Issue by TheRedD0t** [angular/material2#8205]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
According to the guidelines, the complete sort icon should rotate.

> [...] reverse the sort order and **rotate the sort icon**.

https://material.io/guidelines/components/data-tables.html#data-tables-interaction

#### What is the current behavior?
The arrowhead has something like a 3D-Switch animation, which may be nice but doesn't follow the MD guidelines.

**Comment by jelbourn** [comment]
We interpret this bit in the spec to mean that the arrow should _end up_ rotated, not that it has an actual _spinning_ animation. In general Material Design prefers "morphing" animations like what we have.
