### ISSUE TITLE
[Table] Header row has the wrong min-height

### ISSUE THREAD

**Issue by TheRedD0t** [angular/material2#8206]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
According to the guidelines, the height of the header row of a data table should be `56px`.

https://material.io/guidelines/components/data-tables.html#data-tables-specs

#### What is the current behavior?
The header row has the same height as a normal row (`min-height: 48px`).

**Comment by jasiekmiko** [comment]
Covered in #8215
