### ISSUE TITLE
Slider HammerGestures Are Not Recognised in Lazy-Loaded Component

### ISSUE THREAD

**Issue by DanielYKPan** [angular/material2#8207]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The slider's hammer gesture should be recognised in lazy-loaded component.

#### What is the current behavior?
The slider's hammer gestures ( slideStart, slideEnd and slide ) are not recognised in lazy-loaded component. 

If MatSliderModule is imported in AppModule, it works fine.
But if MatSliderModule is imported in a LazyLoadedModule, hammer js gestures are not recognised.

Here is the [demo](https://plnkr.co/edit/ValjHb3yrKAwmedt37ds?p=preview).

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by jelbourn** [comment]
See https://github.com/angular/angular/issues/19874

It's currently a limitation of Angular that event plugins must be created at bootstrap time. In the short term, you can add a provider just for the Hammer gesture config without needing any of the component modules:
```ts
{provide: HAMMER_GESTURE_CONFIG, useClass: GestureConfig}
```

**Comment by DanielYKPan** [comment]
@jelbourn 
So if I load MatSliderModule in my Lazy-Loaded Module, I need to added
```typescript
{provide: HAMMER_GESTURE_CONFIG, useClass: GestureConfig}
```
in my AppModule?
Is this what you mean in you short term?

Thanks, man

**Comment by jelbourn** [comment]
Yep

**Comment by DanielYKPan** [comment]
Thanks man
