### ISSUE TITLE
Browser support - IE11

### ISSUE THREAD

**Issue by ConquerOR2** [angular/material2#8209]
Hello,

could you please clarify if IE11 is still supported? In the documentation one may find the following sentence that is not clear:
> Angular Material supports the most recent two versions of all major browsers: Chrome (including Android), Firefox, Safari (including iOS), and **IE11 / Edge**

Does this mean that two most recent version of IE11 are supported and two most recent version of Edge are supported?

Thanks in advance!

**Comment by donroyco** [comment]
IE11 is supported. See #7374

**Comment by crisbeto** [comment]
IE11 is supported. Also note that the doc refers to the two latest **major** versions.
