### ISSUE TITLE
IE11 inputs issues

### ISSUE THREAD

**Issue by Mc-Mido** [angular/material2#821]
#### Bug, feature request, or proposal:

Bug on IE11 with input and type date, md-hint position 
#### What is the expected behavior?
- md-hint is display on the bottom-left
- input with type=date => no error
#### What is the current behavior?
- md-hint is display on the bottom-right
- input with type=date => invalid argument error
#### What are the steps to reproduce?

http://embed.plnkr.co/fKxENX/ (promise error on IE but I have the issue with this kind of test)
#### Which versions of Angular, Material, OS, browsers are affected?

IE11 only
#### Is there anything else we should know?

With [attr.type]="type" instead of [type]="type" in input.ts is fine on Firefox, IE11 and Chrome
Add left:0 in .md-hint css classe fix the position issue

**Comment by msegers** [comment]
http://plnkr.co/edit/mraL1tJHVL2sP8BSU85d?p=preview

This one shows the error that occurs. I suggest not using input type=date on IE to avoid this error.

**Comment by Mc-Mido** [comment]
Plunker without promise error: http://plnkr.co/edit/mraL1tJHVL2sP8BSU85d?p=preview (thanks to msegers).

**Comment by msegers** [comment]
np

**Comment by mmalerba** [comment]
Now that `md-input-container` is available you can specify the native `<input>` directly. Should resolve this.
