### ISSUE TITLE
Icon registry should use HttpClient

### ISSUE THREAD

**Issue by PeS82** [angular/material2#8211]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Icon registry should preferably use  HttpClient from @angular/common/http

#### What is the current behavior?
Icon registry uses Http from @angular/http

#### What are the steps to reproduce?
Uninstall @angular/http, build project:

ERROR in node_modules/@angular/material/icon/typings/icon-registry.d.ts(2,22): error TS2307: Cannot find module '@angular/http'.

#### What is the use-case or motivation for changing an existing behavior?
@angular/http has been recently replaced by lighter HttpClient, will give possibility to most devs to get rid of @angular/http dependency

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular >= 4.3

#### Is there anything else we should know?
Peace!

**Comment by crisbeto** [comment]
It will in the next release. See #6702.
