### ISSUE TITLE
mat-select throw an error after option selected 

### ISSUE THREAD

**Issue by iceekey** [angular/material2#8213]
#### Bug, feature request, or proposal:
```
index.d.ts.MatSelect.html:1 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at MatSelect._onFadeInDone (select.es5.js:744)
    at Object.eval [as handleEvent] (index.d.ts.MatSelect.html:1)
    at handleEvent (core.js:13254)
    at callWithDebugContext (core.js:14739)
    at Object.debugHandleEvent [as handleEvent] (core.js:14326)
    at dispatchEvent (core.js:9703)
    at eval (core.js:10317)
    at eval (animations.js:348)
    at Array.forEach (<anonymous>)
    at eval (animations.js:346)
```

```
<mat-select [ngModel]="language" (change)="switchLanguage($event)"
    placeholder="{{'app.language'|translate}}" name="lang">
         <mat-option *ngFor="let lang of languages" [value]="lang.locale">
              {{lang.name}}
         </mat-option>
</mat-select>
```

```
    MatSelect.prototype._onFadeInDone = function () {
        this._panelDoneAnimating = this.panelOpen;
        this.panel.nativeElement.focus(); // <-- ERROR IS HAPPENING HERE
        this._changeDetectorRef.markForCheck();
    };
```

After update this error appeared. Everything works fine, just the error and small animation glitch when overlap panel fading out. Idk what to do with this error and how to fix it. Code looks pretty standard...

#### What is the current behavior?
- Chrome, Linux (Solus Project)
- **Angular ^5.0.0**
- **@angular/material ^2.0.0-beta.12**

**Comment by willshowell** [comment]
See https://github.com/angular/material2/pull/7729

**Comment by iceekey** [comment]
@willshowell So it's officially a bug. is my options is limited to wait for an update?

**Comment by willshowell** [comment]
@iceekey You can,

1. Wait for next release
2. Use [snapshot builds](https://material.angular.io/guide/getting-started#alternative-snapshot-build)
3. Downgrade core to 4.x

**Comment by iceekey** [comment]
@willshowell Thank you for your reply!
