### ISSUE TITLE
mat-card css class not applied when more classes are added in template

### ISSUE THREAD

**Issue by buu700** [angular/material2#8219]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

`mat-card` css class should be applied to `mat-card` element.

#### What is the current behavior?

When changing the classes through the template like `<mat-card class='{{balls}}' [class.hello]='hello'>`, the `mat-card` class is dropped.

#### What are the steps to reproduce?

http://plnkr.co/edit/Vv7QfMzxvhUKVAEyKmPG?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Worked as expected in beta 12 with Angular 4.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Current Material master with Angular 5.

**Comment by fxck** [comment]
Isn't it rather when using both `class="{{ balls }}"` and `[class.hello]="true"` (also note that this should be an expression resolving to either true or false)?

**Comment by buu700** [comment]
Sometimes I could reproduce it doing just the former (but it was only consistent when doing both), so there may be a timing issue.

**Comment by crisbeto** [comment]
It's because using `class="{{ balls }}"` will overwrite the entire `class` attribute. If you want to bind a dynamic class name, you can use `[ngClass]="balls"` instead.

**Comment by buu700** [comment]
Got it, thanks! This had been working up until now, but maybe there was just a bug that's been fixed in ng5.
