### ISSUE TITLE
DataSource for mat-table and CDK should just be an Observable<T[]> or even T[]

### ISSUE THREAD

**Issue by benlesh** [angular/material2#8220]
The current contract for a `DataSource` is simply:

```ts
interface DataSource<T> {
  connect(): Observable<T[]>;
  disconnect(): void
}
```

I propose that it would be either just `Observable<T[]>` or perhaps better: `T[]`.

#### What i don't know

What is `disconnect()` really used for? It seems like it's just meant to tear down data producers and resources.

#### It's currently unergonomic
Currently when trying to use `mat-table` with ngrx, I'm force to wrap the selected state observable for no real gain, and it's very unergonomic as a developer. Similarly, if all I wanted to do was get a simple array of data via AJAX, it would be *dead simple* if `dataSource` accepted an `Observable<T[]>` instead of the current abstraction.

#### Maybe it could be an Observable<T[]>
I submit that since the `Observable<T[]>` must be subscribed to, and that the `Subscription` it returns has a "disconnect" semantic via `unsubscribe(): void`, that the `DataSource` is an unnecessary abstraction.

#### Maybe it could just be `T[]`
It might be even easier if the table simply accepted an array of data, because fundamentally, there isn't much difference between having Angular subscribe with `[data]="someData$ | async"` and having the component itself do the subscribing, with the exception that if the component is doing all of the subscription management, rather than async pipe, you've got a lot of extra code in your component you don't need.

**Comment by benlesh** [comment]
@jelbourn has pointed out that I'm missing part of the `DataSource` API, in that `connect()` has an argument... I'm going to close this until I investigate further.

**Comment by Maximaximum** [comment]
I couldn't find any documentation for `CollectionViewer`, except the documentation comments in the source code, which are of almost no help. Perhaps, extensive documentation could make me change my mind.

However, as for now, it seems to be absolutely weird to me to enforce using an additional layer of `DataSource<T>` instead of using `Observable<T[]>` directly. It is a real pain! For example, it's impossible to use `pipe`s against the observable in a component template. Any data modifications have to be done by the `DataSource` itself, and `connect()` has to return a completely finished stream of data.

Something has to be changed here indeed :)

**Comment by andrewseguin** [comment]
The connect function provides an affordance for information from the table (e.g. what rows are being viewed). This will be fleshed out in the future as we incorporate features such as virtual scrolling.

**Comment by Maximaximum** [comment]
Yet another problem: it is impossible to use `track by` with `DataSource` :(

**Comment by nhhockeyplayer** [comment]
my redux ngrx state is working beautifully spreading my typed array thru the reducer into my ngrx state nicely

at the component level I have a container that propagates users$ using @Input as input to my table component and I construct an empty MatTableDataSource at construction

I cannot get my ngrx state "users: <IUser[]>
wired into MatTableDataSource properly

here is my RxJS logic
onChange(changes: SimpleChanges) {
        this.users$
            .map(users => this.dataSource.data = users);
}

action requested please

**Comment by Maximaximum** [comment]
In the meantime, I'm using a pipe to convert my Observable to a DataSource:

```
@Pipe({
  name: 'dataSource'
})
export class DataSourcePipe implements PipeTransform {

  transform<T>(value: Observable<T[]>, args?: any): DataSource<T> {
    if (!value) {
      return null;
    }

    return {
      connect() {
        return value;
      }, disconnect() {

      }
    };
  }

}
```

**Comment by merkllanetex** [comment]
maybe related post from here check it out :https://stackoverflow.com/questions/49995159/mat-table-datasource-ngrx-store-selector-effects/50014815#50014815
