### ISSUE TITLE
[mdExpansionPanel] - Feature request - Lazy load content

### ISSUE THREAD

**Issue by Supamiu** [angular/material2#8230]
#### Bug, feature request, or proposal:

feature request

#### What is the expected behavior?

Don't create the body until the panel is expanded

#### What is the current behavior?

The body is created at the panel creation, meaning that if your panel has a large content and it takes time to create a panel body that will probably not even be viewed.

#### What is the use-case or motivation for changing an existing behavior?

I have expansion panels that can have a lot of content, they sometimes take more than 500ms to render, that's a lot of time. If I put a *ngif in the body binded to the expanded status, it's way better but the expansion collapse is a bit broken because the content immediatly disappears when you collapse.

**Comment by julianobrasil** [comment]
Not related to your feature request, but more to your use case: have you try a `setTimout` in the expanded satus, so you can keep it present until the expansion completely close?

**Comment by Supamiu** [comment]
using a `setTimeout` feels bad in my opinion, mainly because I don't know how much time the expansion panel will take to close. 

That being said, it's a great idea for a hotfix if I put this at around a second, while waiting for the feature to be implemented (if it is).

**Comment by amcdnl** [comment]
@jelbourn - I wonder if this could use the same treatment as we did for tabs?
