### ISSUE TITLE
mat-card-image not being responsive

### ISSUE THREAD

**Issue by bkjain655** [angular/material2#8231]
#### Bug, feature request, or proposal:
Hi Team, I am using mat-card which contains mat-card-image element. As per angular-material if the screen width is less than 600px then width applied should be calc(100% + 32px).
Here 100% should be the screen's width which should be approx 350px but seems like it is taking chrome's width (780px) because of which I am seeing horizontal scroll.
Also, when check and uncheck width from chrome console then it resizes.
Seems like repaint is not happening in responsive mode.
Let me know If I am missing something here.
Following is the code snippet.
` <mat-card class="card-detail" *ngFor="let person of info" fxFlex="47.5%" fxFlex.lt-md="">  
              <img mat-card-image src="{{person.img}}" alt="{{person.shortName}}" height="auto">
    </mat-card> `

#### What is the expected behavior?
It should be responsive without horizontal scroll.

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/32372388/32406839-8c60366e-c1a5-11e7-9c28-b1eb2af1fa55.png)

**Comment by amcdnl** [comment]
@bkjain655 - can you make a demo reproducing this please on plunker or stackblitz?

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
