### ISSUE TITLE
Error in MatSelect.prototype._onFadeInDone

### ISSUE THREAD

**Issue by mth654** [angular/material2#8234]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Mat select should close without any errors in the console.

#### What is the current behavior?
 When closing a mat select, with or without selecting anything, an error is thrown in the console:
ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at MatSelect._onFadeInDone
At a cursory glance, it looks like this function is only supposed to be called when opened, not closed. 

#### What are the steps to reproduce?
https://angular-xeppx5.stackblitz.io
Angular 5.0.0 project with Material 2.0.0-beta.12

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0, Material 2.0.0-beta.12, TypeScript 2.5.3, tested with Chrome 61.0.3163.100 and FireFox 56.0.2.

**Comment by crisbeto** [comment]
This is something that is fixed in master and will be in the next release.
