### ISSUE TITLE
Material2 and Angular 5 HttpClient?

### ISSUE THREAD

**Issue by zijianhuang** [angular/material2#8237]
#### feature request:

Angular 5 is in production since 1st Nov 2017. Angular 5 has Http service deprecated, and is in favor of HttpClient defined in
`'@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js'`

I have a SPA app with Angular 2/4/5 and Material 2. If I stay with Http, things are just fine. If I adapt HttpClient, Material2 will complain, when trying to download 
`node_modules/@angular/common/bundles/common.umd.js/http`
which result in 404.

And obviously Material2 Beta 12 is still using the Http service, and material.umd.js is importing `@angular/http`.

However, eve if I provide the old map: 
`@angular/http': 'npm:@angular/http/bundles/http.umd.js`
along with new map `'ATangular/common/http': 'npm:@angular/common/bundles/common-http.umd.js'`
problem remains the same.

#### What are the steps to reproduce?

Have an Angular 5 utilizing Http while also using Material2 Beta12, things are working. Then replace Http with HttpClient along with respective adjustment in importing, the app will fail to load.

#### What is the use-case or motivation for changing an existing behavior?

To adapt HttpClient in Angular 5.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, Material2 Beta 12

#### Is there anything else we should know?

Obviously Angular 5 with HttpClient could not co-exist. Please advise in the roadmap about when app developers could really replace Http with HttpClient while using Material2.

**Comment by zijianhuang** [comment]
related issues:
#5814  
#6454

**Comment by dushkostanoeski** [comment]
Can't find the issue, but I read that there will be a new version tomorrow so this should be fixed with that release.

**Comment by crisbeto** [comment]
Closing as something that’ll be fixed in the next release.

**Comment by DanPride** [comment]
Please advise on version numbers which resolve this issue. I am on cli 1.5

**Comment by neilhem** [comment]
@angular/material@5.0.0-rc0

**Comment by DanPride** [comment]
Now getting 
webpack: Failed to compile.
ERROR in node_modules/@angular/material/stepper/typings/stepper.d.ts(17,22): error TS2415: Class 'MatStepper' incorrectly extends base class 'CdkStepper'.
  Types of property '_steps' are incompatible.
