### ISSUE TITLE
md-input - type=number disable stepper buttons

### ISSUE THREAD

**Issue by peterwiebe** [angular/material2#824]
#### feature request:

Have the ability to disable the number stepper buttons.

#### What is the expected behavior?

Adding a CSS style or an attribute to change the appearance of the number input should disable stepper buttons on the input element (due to User Agent Stylesheet).

#### What is the current behavior?

The stepper buttons always show for input type="number"

#### What are the steps to reproduce?

See my Plunker demo: http://plnkr.co/edit/Xi8bdAhAIcwhLbGZrtEU?p=preview

#### What is the use-case or motivation for changing an existing behavior?

It doesn't make sense to have it for large numbers (numbers over 100k)

#### Which versions of Angular, Material, OS, browsers are affected?

Latest versions of Angular, Material, Chrome Canary

#### Is there anything else we should know?

Thank you for taking the time to look at this and keep up the good work!

**Comment by msegers** [comment]
Heya, You know this is not going to happen right?
The steppers you see are native number steppers, so the way html5 works.

What I suggest you do in this case is making it a normal text input and adding a regex pattern to allow only number (You could turn this into a directive). <md-input pattern="^[0-9]*$"></md-input>

Changing the style should obviously be an option, but wouldn't it be easier to do it yourself if you don't want the steps?

**Comment by jelbourn** [comment]
We decided we're not going to hide the native UI controls for this case. Individual apps should still be able to hide them with some simple css.
