### ISSUE TITLE
MatSidenavContainer / MatDrawerContainer size control

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#8240]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`MatDrawerContainer` should be able to act when the size nav changes and adjust the content element.

#### What is the current behavior?
`MatDrawerContainer` is `OnPush` so it will not update.

#### What are the steps to reproduce?
I don't have a quick use case but some scenarios are:
  - sidenav size is set after `MatDrawerContainer` init (later css, custom update etc..)
this will freeze the content on the old width
  - Tri-state side-nav, this is a side nav with opened/closed state and a minimized state.
     When a move from open to minimize occurs UI will not update because the opened state did not change (i.e. its an virtual state)
This is something like "icon mode" where the sidenav is slim with icons only.

#### What is the use-case or motivation for changing an existing behavior?
Being able to notify the sidenav is important for custom behaviors and custom modes.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, material beta 12

#### Is there anything else we should know?
I see from the code that reacting to resizes is a problem because it leads to an expensive reflow, so a solution might be an API for the user to notify when a size recalc is needed.
(exposing `_updateContentMargins()`)

Relates issues:
#7682 #8019

**Comment by shlomiassaf** [comment]
## Full Width - Opened
![image](https://user-images.githubusercontent.com/5377501/32421842-ab163f36-c2a4-11e7-9ad4-5da78f32b88b.png)

## Minimized - Opened
![image](https://user-images.githubusercontent.com/5377501/32421850-b79bd568-c2a4-11e7-91e0-0a6a51c07afc.png)

## Over mode - Closed
![image](https://user-images.githubusercontent.com/5377501/32421858-c58b4f28-c2a4-11e7-866b-995390aae73e.png)


Before the update to this component, the whole page responded to resize through ngrx and if you minimized the browser it went from full -> minimized -> over mode

**Comment by axtho** [comment]
this has already been in debate over here: https://github.com/angular/material2/issues/6743

**Comment by ramakanthreddyk** [comment]
Why does this not work with internet explorer?
