### ISSUE TITLE
Virtual repeat support for select control

### ISSUE THREAD

**Issue by ravinsinghd** [angular/material2#8244]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
virtual repeat support for select

#### What is the current behavior?
currently select control don't have virtual repeat

#### What is the use-case or motivation for changing an existing behavior?
select control have performance issue for large number of options

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "4.2.6",
"@angular/material": "2.0.0-beta.8",
 "typescript": "~2.2.0"

#### Is there anything else we should know?
I know you guys planned for implement the virtual repeat. i want to know if the virtual repeat can combine with select control. we have around 10000 options need to show as multi-select. currently it's very slow and freeze the UI for some time. so if the virtual repeat support  add to multi-select it will be very helpful

**Comment by jelbourn** [comment]
Tracked via #823

**Comment by ravinsinghd** [comment]
@jelbourn  I already saw that thread. just want to know whether that virtual repeat  will support for  multi-select or not

**Comment by jelbourn** [comment]
Our virtual scrolling will eventually be available in all relevant components once it's built

**Comment by ravinsinghd** [comment]
Thanks
