### ISSUE TITLE
[MatSelect] this.panel is undefined when changing option

### ISSUE THREAD

**Issue by nicolainormann** [angular/material2#8245]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Open select and pick option without error

#### What is the current behavior?
Throws console error 
Firefox: this.panel is undefined
Chrome: Cannot read property 'nativeElement' of undefined
Edge: Unable to get property 'nativeElement' of undefined or null reference

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-vyttwn
Open select > Pick option > See console for error

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0
Material 2.0.0-beta.12

**Comment by crisbeto** [comment]
Will be fixed in the next release by https://github.com/angular/material2/pull/7729.
