### ISSUE TITLE
[Dialog] Open doesn't open a new dialog

### ISSUE THREAD

**Issue by bracco23** [angular/material2#8248]
#### Bug, feature request, or proposal:
Undocumented behaviour or bug.

#### What is the expected behavior?
According to the documentation, if I use `Matdialog.open` a new dialog is opened, without any mention of preconditions

#### What is the current behavior?
As can be easily seen in dialog.ts, if a dialog is already opening, no new dialog is created and the animating one is returned. Why?

#### What is the use-case or motivation for changing an existing behavior?
In my case, I'm creating dialogs to show loading spinners in an HttpInterceptor. The component in the dialog requests some data at the opening, so the sequence of operation is:

- dialog_1, with the actual component, is opened
- the component is loaded and fires an http request
- the interceptor tries to open a dialog for the spinner (fails, gets back dialog_1 reference)
- the interceptor gets the response and close the dialog (which should be the newly opened spinner dialog, but closes the main dialog)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 5, material 2.0.0-beta.10, Windows 10 1703, typescript 2.4.2

**Comment by crisbeto** [comment]
This was a limitation that was put in place to avoid some focus management issues. It will be removed in the next release. See https://github.com/angular/material2/pull/8051.

**Comment by yooRabbit** [comment]
same problem,I use
```
 this.editDialog.afterClosed().subscribe(data => {
    if (data) {
      this.query();
    }
 });
```
to do next http request for now.
