### ISSUE TITLE
Possible bug with md-raised-button on changing item position 

### ISSUE THREAD

**Issue by bartoszholko** [angular/material2#8250]
#### Bug, feature request, or proposal:

Possible Bug with mat-raised-button 

#### What is the expected behavior?

mat-raised-button should disappear

When I use arrows to reorder items on:
1. Iphone (iOS/Safari):
UP arrow hover works fine (fades away)
DOWN arrow hover is still visible after clicking (should fade away)
2. Iphone (iOS/Chrome):
UP arrow hover works fine (fades away)
DOWN arrow hover is still visible after clicking (should fade away)
3. Samsung S7 (Android/Chrome):
UP arrow hover is still visible after clicking (should fade away)
DOWN arrow hover is still visible after clicking (should fade away)
4. Ipad (iOS/Chrome)
UP arrow hover is still visible after clicking (should fade away) but on this device, it is visible on resource one below the clicked one (I can show you this on Ipad)
DOWN arrow hover is still visible after clicking (should fade away)
5. Samsung Tablet (Android/Chrome)
UP arrow hover is still visible after clicking (should fade away)
DOWN arrow hover is still visible after clicking (should fade away)
#### What is the current behavior?

On reordering items mat-raised-button is visible (should fade away)

#### What are the steps to reproduce?
```<div class="dropbox__footer">
    <button mat-button mat-icon-button color="primary" (click)="moveUp($event)">
      <mat-icon class="dropbox__footer-icon">keyboard_arrow_up</mat-icon>
    </button>
    <button mat-button mat-icon-button color="primary" (click)="moveDown($event)">
      <mat-icon class="dropbox__footer-icon">keyboard_arrow_down</mat-icon>
    </button>
```
Showcase:
[On click moveUp button](https://imagebin.ca/v/3gMQSHl7mm9i)
[After click moveUp button](https://imagebin.ca/v/3gMQv0ePal7D) ==> hover should fade away

#### What is the use-case or motivation for changing an existing behavior?

NA

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material: 2.0.0-beta.12
OS: iOS/Android
Browsers: Chrome/Safari

#### Is there anything else we should know?

NA

**Comment by josephperrott** [comment]
Can you provide a reproduction plunker or stackblitz?  I am not quite following the issue you are seeing.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
