### ISSUE TITLE
Custom Footer

### ISSUE THREAD

**Issue by vibingopal** [angular/material2#8253]
#### Bug, feature request, or proposal:
Hi Team,

Is the material current version supports Custom Footer. Instead of using current pagination component  in the app, we like to implement LOAD MORE on the footer datatable. So on click of Load More, the next n number of records will be visible to the user.

#### What is the current behavior?
At this moment ,iam not seeing any example with that. Could you please provide any specific example if it is already exists?
Material Version : 2.0.0-beta.12
Angular : 4.4.4

Many thanks in advance.

**Comment by willshowell** [comment]
IMO this example would be pretty specific to this single use case. Could you explain what you've tried?

Maybe that would illuminate where the documentation could be improved to help people understand how to use the data source for their unique needs.

**Comment by vibingopal** [comment]
OK. Thank you for the response.
I am looking to implement the attached feature on the datatable.
![image](https://user-images.githubusercontent.com/17860925/32450892-0f21c370-c2db-11e7-9b6d-11fc54a2bc8d.png)

When the user performs the Load More action next set of records will load into Datatable.If no records exist there won't be any Load More action.
Right now i struck on how to customize the pagination footer.

**Comment by willshowell** [comment]
I'm not sure I follow. The table doesn't have a concept of a footer. While the mat-paginator does use styles consistent with mat-table, they are still independent components.

It kind of sounds like you are trying to extend the mat-paginator by making it a single button instead. The paginator is very opinionated and not suitable for such a large customization. You'd surely have more success creating your own component or just adding the button to your template.

**Comment by vibingopal** [comment]
Sure Will. Thank you. I Just want this clarity whether the large customization we can do with the existing feature.Now  I can start creating my component and will share the plunker here if any body wants to make use of this. Closing this for now.

**Comment by willshowell** [comment]
Ah I see. It is best suited for text customization via `MatPaginatorIntl` (tracking documentation at https://github.com/angular/material2/issues/8239 and [example](https://github.com/angular/material2/issues/7289#issuecomment-339169333)). 

You can definitely extend `MatPaginator` and provide a different, but I really think it would be easiest to create your own component.

**Comment by vibingopal** [comment]
Thank you Will :)
