### ISSUE TITLE
allow `disableRipple` on `mat-menu-item` buttons

### ISSUE THREAD

**Issue by ilovett** [angular/material2#8261]
#### Bug, feature request, or proposal:

bug/feature

#### What is the expected behavior?

ability to `disableRipple` on `mat-menu-item`

#### What is the current behavior?

Ripples no matter what

#### What are the steps to reproduce?

Is it just me or are all the plunker's for material broken atm?

#### What is the use-case or motivation for changing an existing behavior?

Slowly migrating existing UI styling to Material styling, or maybe i just don't like the ripple?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular 4.4.6 
material 2.0.0-beta12

**Comment by julianobrasil** [comment]
Try stackblitz.com: https://stackblitz.com/edit/dialog-issue
