### ISSUE TITLE
Update Plunker and StackBlitz Templates for 5.0.0-rc0 Release

### ISSUE THREAD

**Issue by mtrdp642** [angular/material2#8276]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Plunker and StackBlitz templates in the README use the most recent release - 5.0.0-rc0 using Angular 5.

#### What is the current behavior?
Templates use the 2.0.0.beta-12 release with Angular 4.

#### What are the steps to reproduce?
Working StackBlitz with updated dependencies: https://stackblitz.com/edit/angular-ckpuyy
Plunker never loads properly for me, so I can't update that.

#### What is the use-case or motivation for changing an existing behavior?
Enforce better issue reporting and duplication efforts.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0
Material 5.0.0-rc0

**Comment by josephperrott** [comment]
Both the stackblitz and plunker templates are now up to date.
