### ISSUE TITLE
md-autoselect

### ISSUE THREAD

**Issue by Ronalses** [angular/material2#8285]
Hi, I have a question.
What is the equivalent of md-autoselect = "true"
mat-autoselect It does not work for me.

<mat-autocomplete mat-autoselect="true" #auto="matAutocomplete (optionSelected)="onSelectOption($event)">
</mat-autocomplete>

**Comment by amcdnl** [comment]
Can you provide more information please?

**Comment by Ronalses** [comment]
OK, thanks for answering.
I want to use an autocomplete like this.
https://codepen.io/anon/pen/xOXoRP?editors=1010
Where the first element is automatically selected.
in this example they use md-autoselect = "true"
I try to use mat-autoselect = "true" but it does not work.

**Comment by josephperrott** [comment]
It looks like you are actually using Material for AngularJS.  You will need to post your issue [here](https://github.com/angular/material/issues/new) since they are maintained as separate projects.  You may also have better luck asking on stackoverflow, gitter, etc.

**Comment by Ronalses** [comment]
no.
I am using material 2.
Sorry for my english.

Just give an example of what I am doing in material 2.

These are my dependencies.

`"dependencies": {
		"@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.0-rc0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
		"connect": "^3.6.2",
		"core-js": "^2.4.1",
		"fabric": "^1.7.16",
		"hammerjs": "^2.0.8",
		"openseadragon": "^2.2.1",
		"rxjs": "^5.5.2",
		"serve-static": "^1.12.3",
		"zone.js": "^0.8.4"
	},`

I am using this component: https://material.angular.io/components/autocomplete/overview
I am trying to have the first element automatically selected.
in the example I show above, they use md-autoselect = "true"

I am using mat-auto select = "true", but it does not work.

**Comment by Kampii** [comment]
[Here is](https://teradata.github.io/covalent/#/components/chips) an example, type first two letters and hit enter.

**Comment by Yoshi9143** [comment]
Anyway we can re-open this?  I think @Ronalses is saying he would like the functionality of having the first element to be automatically selected like you can for Material for AngularJS. I am in the same boat - it would be great if we set the first element to always be selected.

**Comment by Ronalses** [comment]
@Yoshi9143  Exactly what I would like to do.
