### ISSUE TITLE
make expansion panel height configurable

### ISSUE THREAD

**Issue by charlie-elverson** [angular/material2#8289]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Height of the mat-expansion-panel-header should be configurable.

#### What is the current behavior?
Repeating issue [5641](https://github.com/angular/material2/issues/5641), which was closed with a PR that didn't address the issue. PR [6643](https://github.com/angular/material2/pull/6643) addressed expansion-panel-header but not expansion-panel height

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by julianobrasil** [comment]
I don't know whether I get your proposal right, but couldn't you simply wrap the expansion's content in a **`<div>`** and control the height of the **`<div>`**? I believe the panel will correctly follow the height of this **`<div>`**. Then you can enable scrollbars or anything else you want by customizing this **`<div>`**.

**Comment by charlie-elverson** [comment]
Good point. I just went back and reread the original issue. I misread it to begin with and thought it pertained to the panel itself, not the header. My bad.
