### ISSUE TITLE
md-radio breaks all the styling in my app

### ISSUE THREAD

**Issue by ladyleet** [angular/material2#829]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-radio should render and styles are not broken

#### What is the current behavior?
breaks all the styling and outputs error to console

#### What are the steps to reproduce?
download this repo https://github.com/ladyleet/ng-tattoo-demo/tree/96bc0c5c127d45d74531682a2b8d49b35bcf4e06

this is the html that is breaking everything.
```html
<div>
    <h2>Radio Example</h2>
    <md-radio-group>
      <md-radio-button value="option_1">1</md-radio-button>
      <md-radio-button value="option_2">2</md-radio-button>
    </md-radio-group>
 </div>
```
#### What is the use-case or motivation for changing an existing behavior?
So it's not broken

#### Which versions of Angular, Material, OS, browsers are affected?
rc.4

**Comment by Neo11** [comment]
As the thrown error shows, the Selection Provider is missing

```
providers: [MdUniqueSelectionDispatcher],
```

**Comment by kara** [comment]
Yep, as @Neo11 mentions, it won't work without that provider.  Looks like it escaped the documentation, so added an issue for to update it: 

https://github.com/angular/material2/issues/834

Try adding the provider, and if you're still having issues, please feel free to re-open.

**Comment by ladyleet** [comment]
@kara @neo11 thanks you two!

**Comment by ladyleet** [comment]
@kara @neo11 can you be more specific on how to add this? i've tried to import MdUniqueSelectionDispatcher from '@angular/core'; and '@angular2-material/radio'; but it still doesn't seem to work.

**Comment by pgurenko** [comment]
The import should be import { MdUniqueSelectionDispatcher } from '@angular2-material/core/coordination/unique-selection-dispatcher';

**Comment by kara** [comment]
As long as your system config is set up correctly, you should be able to import it directly from `@angular/core`.  Is that not working for you?

**Comment by pgurenko** [comment]
You're right, @kara: import { MdUniqueSelectionDispatcher } from '@angular2-material/core';

**Comment by kara** [comment]
@ladyleet  Are you importing from `@angular/core` rather than `@angular2-material/core`?
