### ISSUE TITLE
[feature request] Add an option to disable checkTheme or check after waiting for a while.

### ISSUE THREAD

**Issue by JounQin** [angular/material2#8291]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Do not show `checkTheme` warning in some case.

#### What is the current behavior?
For example we are using webpack to load global `.scss` file and `extract-webpack-plugin` is disabled on development, so material theme will be loaded asynchronously, then there will be an warning about no material theme.

**Comment by crisbeto** [comment]
The check won't be active in production mode and you can disable it completely using the `MATERIAL_SANITY_CHECKS` token:

```ts
@NgModule({
  providers: [{
    provide: MATERIAL_SANITY_CHECKS, useValue: false  
  }]
})
export class YourModule {}
```
