### ISSUE TITLE
Dialog - Horizontal Scrollbar in Windows Browsers When It Shouldn't

### ISSUE THREAD

**Issue by tommyc38** [angular/material2#8293]
#### Bug, feature request, or proposal:

The horizontal scrollbar (x) is showing on Windows browsers even though there is nothing to scroll.  
#### What is the expected behavior?

I would only expect to see a scrollbar if the content was overflowing.  This is the case with mac browsers.  Please either fix it or give us the ability to add styles/classes to MatDialogContainer which is what is causing the issue.  When I set overflow-x to hidden it goes away in chrome tools.
#### What is the current behavior?

The horizontal scrollbar shows when it shouldn't.  

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

Go to www.u-hoa.com and click the envelope icon in the upper left corner.  Do this on a mac and windows and you will see what I am talking about if you open up dev tools in whatever browser you are looking at and unchecking my fix, listed below.  I would still consider this a bug because the default shouldn't be to show a scrollbar when nothing is overflowing when accessed on a Window's browser.  I'm surprised nobody has mentioned this before.

#### What is the use-case or motivation for changing an existing behavior?

It looks bad when you have a scrollbar with nothing to scroll.  

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5, Latest version of Material, Windows browsers (Firefox and Chrome, haven't tried Explorer)

#### Is there anything else we should know?

I tried a number of ways to get around this issue.  What worked was adding a class to the config (e.g. panelClass: 'no-over-flow-x') on the dialog.open method and then setting a global CSS selector` no-over-flow-x > mat-dialog-container{overflow-x: hidden !important}`

You should also know that although the the class 'no-over-flow-x' gets added to the panel `div id="cdk-overlay-{number}"` element, the css rules defined in the `no-over-flow-x` class don't get added, but class name does.  I don't quite understand how that works but it looks to be another bug.

**Comment by Chan4077** [comment]
It should be as the following syntax:

```css
.my-dialog-container .mat-dialog-container {
  overflow-x: hidden;
}

It's stated in the [docs](https://material2-docs-dev.firebaseapp.com/guide/customizing-component-styles#styling-overlay-components). By the way, it's a bad idea to use both Bootstrap and Material Design at the same time.

**Comment by tommyc38** [comment]
@Chan4077 thank you for the clarification.  I didn't know it was by design to work that way and will be sure I read everything in the docs before wasting anyones time.  How is it a bad idea to use bootstrap?  I haven't had any issues yet.  What issues does it cause?  Thanks in advance.

**Comment by josephperrott** [comment]
Closing as `overflow` control can be done via CSS styling as mentioned above.

**Comment by biltongza** [comment]
+1, clearly there is a bug somewhere as I just hit this. None of my components within the modal extend past the boundary of the modal yet there is still a scrollbar for me, and I'm not a fan of having to have a specific class in my global styles just to fix this.
