### ISSUE TITLE
Ripple effect not working in material2

### ISSUE THREAD

**Issue by bhupinderkumarbl** [angular/material2#8294]
After update previews version of material the button not showing the ripple effect . Currently i am using material 2

**Comment by julianobrasil** [comment]
You can provide an example code that fails here: https://stackblitz.com/edit/dialog-example

It helps the team to better understand your case.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
