### ISSUE TITLE
Add "color" property to Tooltip component

### ISSUE THREAD

**Issue by SpiderPork** [angular/material2#8296]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Add "color" property to Tooltip component.
Color property values can be "primary", "accent", "warn" or "default".

#### What is the current behavior?
There is no color property for tooltip.

#### What are the steps to reproduce?
NA

#### What is the use-case or motivation for changing an existing behavior?
In my project I would like to use primary color for some tooltips and warn color for other tooltips.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
NA

#### Is there anything else we should know?
No

**Comment by Chan4077** [comment]
The [Material Design guidelines](https://material.io/guidelines/components/tooltips.html#tooltips-tooltips-desktop) goes against this, but it can be possible. Just use the `matTooltipClass` input:

```html
<span matTooltip="Tooltip!" matTooltipClass="primary-tooltip">Content</span>
```
```css
.primary-tooltip {
    background-color: #3F51B5;
}
```

**Comment by SpiderPork** [comment]
OK thank you.

**Comment by MingPawat** [comment]
I try to change font color by using matTooltipClass but font color still be white. I figure out that I have to put "!important" keyword like this.
`.primary-tooltip {
  color: black !important;
}`
This is because .mat-tool-tip class is declared first and it has its own color property.
I think this should be mention in docs since I too much time on this.

**Comment by Mohit-Purbia** [comment]
add :  @Component({
  // Need to remove view encapsulation so that the custom tooltip style defined in
  // `tooltip-custom-class-example.css` will not be scoped to this component's view.
  encapsulation: ViewEncapsulation.None,
})
