### ISSUE TITLE
LTS?

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material2#8300]
I thought Angular 4.X has LTS. 
Why does Angular Material require Angular 5.0?

**Comment by derSidge** [comment]
agree

**Comment by StephenFluin** [comment]
@mbeckenbach @derSidge Angular 4 was an LTS release, meaning we continue to maintain a branch and release as needed for critical bugfixes and security patches. It intentionally did not include new feature development, or include  libraries (such as Material, which was not "stable" as part of Angular v4).

This has been a request we have gotten several times in the past few weeks and something we are looking at for future LTS releases. It may be possible to include libraries such as Material in the "Angular LTS" promise for future versions once Material hits its "stable" 5.0.0 release.
