### ISSUE TITLE
Busy indicator for  suitable componets

### ISSUE THREAD

**Issue by bharathmuppa** [angular/material2#8301]
####  feature request
It would be good to have a busy indicator/loading indicator for component like table,list or similar ones before loading data/updating data.

#### What is the expected behavior?
for example: if there is table and data is being prepared/served from server component should havee busy states parameter which on true show loading indicator and on false stop loading indicator

#### What is the current behavior?
We are doing it manually for every item and needs to provide external styles to implement it.

#### What is the use-case or motivation for changing an existing behavior?
many projects needs this because they don't want to see loading on whole app.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular v5

**Comment by jelbourn** [comment]
This isn't something we will ever bake into any components, instead leaving it to the user to add a loading indicator specific to their application.
