### ISSUE TITLE
5.0.0-RC0 - matTooltip not working with Angular 5

### ISSUE THREAD

**Issue by DooMachine** [angular/material2#8313]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Working tooltip.

#### What is the current behavior?
Using matTooltip pipe gives error.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5 , angular material 5.0.0-rc -Microsoft Windows- Opera and Chrome , TypeScript 2.6.1

#### Is there anything else we should know?

>  Uncaught (in promise): TypeError: this._change.pipe is not a function
> TypeError: this._change.pipe is not a function
>     at ViewportRuler.change (scrolling.es5.js:452)
>     at new ViewportRuler (scrolling.es5.js:357)
>     at VIEWPORT_RULER_PROVIDER_FACTORY (scrolling.es5.js:483)
>     at _callFactory (core.js:10650)
>     at _createProviderInstance$1 (core.js:10598)
>     at resolveNgModuleDep (core.js:10580)
>     at _createClass (core.js:10625)
>     at _createProviderInstance$1 (core.js:10595)
>     at resolveNgModuleDep (core.js:10580)
>     at _createClass (core.js:10629)
>     at ViewportRuler.change (scrolling.es5.js:452)
>     at new ViewportRuler (scrolling.es5.js:357)
>     at VIEWPORT_RULER_PROVIDER_FACTORY (scrolling.es5.js:483)
>     at _callFactory (core.js:10650)
>     at _createProviderInstance$1 (core.js:10598)
>     at resolveNgModuleDep (core.js:10580)
>     at _createClass (core.js:10625)
>     at _createProviderInstance$1 (core.js:10595)
>     at resolveNgModuleDep (core.js:10580)
>     at _createClass (core.js:10629)
>     at u (vendor.js?v=A6S9FqGSwBdggEzCsBYjIL5uBxYrxgfeoAjrGmQX-sc:930)
>     at u (vendor.js?v=A6S9FqGSwBdggEzCsBYjIL5uBxYrxgfeoAjrGmQX-sc:930)
>     at vendor.js?v=A6S9FqGSwBdggEzCsBYjIL5uBxYrxgfeoAjrGmQX-sc:930
>     at t.invokeTask (vendor.js?v=A6S9FqGSwBdggEzCsBYjIL5uBxYrxgfeoAjrGmQX-sc:923)
>     at Object.onInvokeTask (core.js:4617)
>     at t.invokeTask (vendor.js?v=A6S9FqGSwBdggEzCsBYjIL5uBxYrxgfeoAjrGmQX-sc:923)
>     at r.runTask (vendor.js?v=A6S9FqGSwBdggEzCsBYjIL5uBxYrxgfeoAjrGmQX-sc:923)
>     at o (vendor.js?v=A6S9FqGSwBdggEzCsBYjIL5uBxYrxgfeoAjrGmQX-sc:923)
>     at HTMLAnchorElement.invoke (vendor.js?v=A6S9FqGSwBdggEzCsBYjIL5uBxYrxgfeoAjrGmQX-sc:923)

**Comment by willshowell** [comment]
Do you have rxjs > 5.5 installed?

**Comment by DooMachine** [comment]
Yes

**Comment by josephperrott** [comment]
Can you provide a reproduction in a stackblitz or plunker?  It looks like it is working [here](https://stackblitz.com/edit/angular-material2-issue-rf1grh?file=app%2Fapp.component.html)

**Comment by DooMachine** [comment]
I could not broke yours, nor fix mine. Also mat-select and mat-dialog not working too. I guess I need to investigate bug in my code. Thanks

**Comment by brivvirs** [comment]
Have you found a fix for this bug?
I am having the same issue after migrating to`"@angular/material": "5.0.0"`. 
Also unable to reproduce on stackblitz.

**Comment by DooMachine** [comment]
I dont remember exacly how did I solve it but may be if you are using webpack execute `webpack --config webpack.config.vendor.js` and `webpack`

**Comment by brivvirs** [comment]
Thanks! After executing `webpack --config webpack.config.vendor.js` i got some dependency errors. After fixing them app started to work. 

Seems like the problem was caused by netcore angular2 template dependencies + webpack config.

**Comment by DooMachine** [comment]
Yeah, I quit angular.
