### ISSUE TITLE
matTooltipClass doesn't seem to work in 5.0

### ISSUE THREAD

**Issue by gzamb** [angular/material2#8316]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Apply class passed in the [matTooltipClass]

#### What is the current behavior?
Class passed is not applied

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
add a class and see if it gets applied

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, Material 5, mac Sierra, Typescript 2.4.2, chrome

**Comment by josephperrott** [comment]
It looks like the class is added as expected based on [this stackblitz](https://stackblitz.com/edit/angular-material2-issue-4fqk8t?file=app%2Fapp.component.html).  Can you provide a reproduction of the issue you are seeing?

**Comment by willshowell** [comment]
This is likely due to encapsulated styles.

**Comment by gzamb** [comment]
@willshowell It's possible you are right.  @josephperrott https://stackblitz.com/edit/angular-material2-issue-qsyjju I modified your example to better match what I'm trying to do.  As you can see the css class does not get applied if done this way.  I also tried moving the class out to the styles.scss but no change.

**Comment by willshowell** [comment]
@gzamb I moved the style to the global styles and it appears to work fine,

https://stackblitz.com/edit/angular-material2-issue-tgr3bd?file=app/app.component.ts

Maybe [this guide](https://material.angular.io/guide/customizing-component-styles) can help explain the behavior.

**Comment by gzamb** [comment]
Yeah I tried that, it didn't work.  I'll take a look, I just figured it should be applied directly overriding all the other classes

**Comment by willshowell** [comment]
@gzamb the problem with applying it directly is that (by default) the style is encapsulated to only your component.

The tooltip (and other overlay-based components) create a new component instance and append it at the end of the `<body>`. Your view encapsulated styles will not be able to target the tooltip since it belongs to another component. That's why, even though the tooltip gets the correct class, your styles don't affect it. And that's why global styles or setting `ViewEncapsulation.None` are encouraged in this context.

**Comment by gzamb** [comment]
@willshowell alright I found the combo that works in my global styles, thanks for the help

**Comment by parker789** [comment]
@gzamb - any way you could comment on the solution which worked for you?

**Comment by gzamb** [comment]
I ended up creating a class but I placed it in my main styles.scss file.  It was the only way it would work for me

**Comment by parker789** [comment]
Thanks. I had tried that and it wasn't working, but due to some css specificity issues.. I ended up changing the class name and all was well.
