### ISSUE TITLE
cdkConnectedOverlay default positions don't have horizontal fallbacks

### ISSUE THREAD

**Issue by TishchenkoAlex** [angular/material2#8318]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?

cdkConnectedOverlay horizontal auto-alignment strategy not working (see demo-video below)

#### What is the current behavior?

cdkConnectedOverlay horizontal auto-alignment must works correct (like vertical ) 
#### What are the steps to reproduce?

https://youtu.be/RCH2HCqq-O0
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

ng 5.0.1, ts 2.4.2, material beta-12

**Comment by willshowell** [comment]
I haven't used the directive yet, but I think you need to provide fallback positions via `cdkConnectedOverlayPositions`

https://github.com/angular/material2/blob/f08b3f0e1e97bc6d6e37b0def116bddd7796bce7/src/cdk/overlay/overlay-directives.ts#L108-L109

The default ones allow vertical repositioning, but don't account for horizontal needs

https://github.com/angular/material2/blob/f08b3f0e1e97bc6d6e37b0def116bddd7796bce7/src/cdk/overlay/overlay-directives.ts#L44-L52

@jelbourn would it be wise to add one or two fallback positions to the default list where the horizontal connection position is different?

**Comment by jelbourn** [comment]
Would be a good default
