### ISSUE TITLE
Autocomplete - Need way to set first option as active manually

### ISSUE THREAD

**Issue by lcecil** [angular/material2#8319]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Should be able to manually/programmatically set the first option in the autocomplete panel as active and select when the user presses enter.

#### What is the current behavior?
User must either use the down key or hover with the mouse on the option to make it active.

#### What are the steps to reproduce?
N/A

#### What is the use-case or motivation for changing an existing behavior?
Our users are going to be limited to selecting only options from the autocomplete. We're experiencing problems where users are either typing in a partial value or the full value, hitting the enter key, and not understanding why that option isn't being selected.

See attached images
![partial-match](https://user-images.githubusercontent.com/15719045/32578379-dc0de88e-c491-11e7-92ca-fbfdc7fa6a93.PNG)
![full-match](https://user-images.githubusercontent.com/15719045/32578387-dff0ece4-c491-11e7-8247-dd2d45a0d9aa.PNG)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 4.4.6
Material - 2.0.0-beta.12

#### Is there anything else we should know?
Seems similar to this issue, but not quite: https://github.com/angular/material2/issues/3334
The material Select component has this feature, so it doesn't seem too far of a stretch to have the same behavior for the autocomplete as an optional setting.

**Comment by josephperrott** [comment]
You actually can do this already by acting on events on the input underlying `MatAutocomplete`.

In your html:
```html
<input matInput placeholder="Pick a state" aria-label="State" [matAutocomplete]="auto" 
      [formControl]="stateCtrl" (keyup.enter)="chooseFirstOption()">
<mat-autocomplete #auto="matAutocomplete">
  <mat-option *ngFor="let state of filterStates(this.stateCtrl.value)" [value]="state">{{state}}</mat-option>
</mat-autocomplete>
```

In your component class:
```ts
@Component({
  selector: 'autocomplete-overview-example',
  templateUrl: 'autocomplete-overview-example.html',
  styleUrls: ['autocomplete-overview-example.css']
})
export class AutocompleteOverviewExample {
  stateCtrl: FormControl;
  filteredStates: Observable<any[]>;
  states: string[] = [Arkansas', 'California', 'Florida',  'Texas'];
  @ViewChild(MatAutocomplete) matAutocomplete: MatAutocomplete;

  filterStates(name: string): string[] {
    return this.states.filter(state =>
      state.toLowerCase().indexOf(name.toLowerCase()) === 0);
  }
  
  chooseFirstOption(): void {
    this.matAutocomplete.options.first.select();
  }
}
```


The chooseFirstOption, will select the first item in the current options.

**Comment by lcecil** [comment]
Thanks, that helps with the selection, but there's no indication that the user is going to select the first one - is there an easy way to also apply the `.mat-active` class to the first option?

I've tried several ways, and cannot figure it out.

Thanks much.

**Comment by lcecil** [comment]
Nevermind, I got it.

`this.matAutocomplete.options.first.setActiveStyles();`

Thanks again!

**Comment by lcecil** [comment]
Hi @josephperrott . I might need you to re-open this issue.

The solutions above only solve the first part of the feature request. I got the select working, and I can manually set the active styles to the first option, but I think it still requires me to write my own KeyManager. Even though the first option is active, when I press the down arrow, the Autocomplete still wants to make the first option active - it doesn't adjust the index accordingly.

The typeahead using bootstrap and AngularJS has the exact desired behavior for a better working example: https://angular-ui.github.io/bootstrap/#!#typeahead

Let me know if you need more clarity, or if there's a solution for this second half.

**Comment by smitelij** [comment]
Hey @lcecil ,

I wanted the same behavior you were after and got it working with a few small tweaks:

in component.ts:
```
highlightFirstOption(event): void {
    if (event.key == "ArrowDown" || event.key == "ArrowUp") {
      return;
    }
    this.matAutocomplete._keyManager.setFirstItemActive();
  }

  selectFirstOption(): void {
    this.matAutocomplete.options.first.select();
  }
```

in component.html:
`(keyup.enter)="selectFirstOption()"
                          (keyup)="highlightFirstOption($event)"`

**Comment by lcecil** [comment]
Hi @smitelij,

Thanks for the suggestion, I'll give it a try. Although I'm a little surprised you can access the `_keyManager`, as I would assume that preceding underscore would mean that it's private.

I also opened another issue, since I didn't feel like the issue was fully addressed here, if you want to keep tabs on it: https://github.com/angular/material2/issues/8423

**Comment by lcecil** [comment]
Also, @smitelij , if you're using something like `(onSelectionChange)="selectOption()"` on your `<mat-option>` component, you don't need that `selectFirstOption()` method. I believe the fact that the first item is active handles that for you.

**Comment by smitelij** [comment]
@lcecil Good point! I had gotten that first part onSelect working before getting the highlighting working and didn't think about that.

**Comment by NexPlex** [comment]
Hi @lcecil 

Where did you put this code? this.matAutocomplete.options.first.setActiveStyles();
I can't get the highlighting to work.

**Comment by lcecil** [comment]
Hi @NexPlex ,

What version of `@angular/material` are you using? Some of the more recent versions (I think 5+) have this functionality implemented already.

Just add the `autoActiveFirstOption` attribute to your `<mat-autocomplete>` selector.

Check out the documentation here:
https://material.angular.io/components/autocomplete/api#directives

**Comment by NexPlex** [comment]
Hi @Icecil,

Thank you for the quick reply. I am currently committed to material@2.0.0-beta.12 and Angular 4.4.7. I say your fix was related to material@2.0.0-beta.12. We can't upgrade at this time. Did you get the first item to highlight with beta.12? I have highlighting working with the up and down arrows. just can't get the top item to highlight.

+-- @angular/material@2.0.0-beta.12

 @angular/animations@4.4.7
+-- @angular/cdk@2.0.0-beta.12
+-- @angular/common@4.4.7
+-- @angular/compiler@4.4.7
+-- @angular/compiler-cli@4.4.7
+-- @angular/core@4.4.7
+-- @angular/forms@4.4.7
+-- @angular/http@4.4.7

**Comment by lcecil** [comment]
Hmm, I can't quite remember, but I do think that you can do it by accessing the `_keyManager`.

So that would look like: `this.matAutocomplete._keyManager.setFirstItemActive();`

See smitelij's comment from 12/13. Good luck!

**Comment by douglasgsouza** [comment]
That worked well for me:

.html
```
<input matInput placeholder="Product" [matAutocomplete]="auto" formControlName="product" (blur)="chooseFirst">

<mat-autocomplete #auto="matAutocomplete" autoActiveFirstOption>
    <mat-option *ngFor="let product of filteredProducts | async" [value]="product.name">
        {{product.name}}
    </mat-option>
</mat-autocomplete>
```

.ts

```
@ViewChild('auto') autoComplete: MatAutocomplete;
form: FormGroup;

chooseFirst(): void {
        if (this.autoComplete.options.length > 0) {
            this.form.get('product').patchValue(this.autoComplete.options.first.value);
        }
    }

```
