### ISSUE TITLE
Ability to pass data to a ComponentPortal

### ISSUE THREAD

**Issue by Chan4077** [angular/material2#8322]
#### Bug, feature request, or proposal:

I'm trying to pass data to a portal (I'm using `ComponentPortal`), but so far, there's no possible way to do so.

#### What is the expected behavior?

Able to pass data to a `ComponentPortal`

#### What is the current behavior?

Can't pass data to a `ComponentPortal`

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?

I want to show a code snippet with a param passed in as part of the code snippet.

Something like this:

```html
<code-viewer language="html">
&lt;mat-icon svgIcon="{{selectedIcon}}"&gt;&lt;/mat-icon&gt;
</code-viewer>
```
```ts
export class CodeSnippetComponent {
    selectedIcon: string; // <- How to declare this?
}
```
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
Angular v5.0.1
Angular Material v5.0.0-rc.0
Typescript 2.4.2
macOS High Sierra 10.13.1
Google Chrome Version 63.0.3239.30 (Official Build) beta (64-bit)
```

#### Is there anything else we should know?

NIL

**Comment by atishin** [comment]
I think you can inject this data by using Injector

**Comment by Chan4077** [comment]
@atishin Errr... How do you inject data?

**Comment by josephperrott** [comment]
Closing as this is already supported.  

You can pass data into a `ComponentPortal` using the injector.  An example of this can be seen in the dialog [here](https://github.com/angular/material2/blob/master/src/lib/dialog/dialog.ts#L250) using the injector that is created [here](https://github.com/angular/material2/blob/master/src/lib/dialog/dialog.ts#L269)

**Comment by matheo** [comment]
@josephperrott My ComponentPortal seems unable to resolve some dependencies of root provided services. What's required to inject Services next to the injected Data? thanks!

**Comment by mmezian** [comment]
> Closing as this is already supported.
> 
> You can pass data into a `ComponentPortal` using the injector. An example of this can be seen in the dialog [here](https://github.com/angular/material2/blob/master/src/lib/dialog/dialog.ts#L250) using the injector that is created [here](https://github.com/angular/material2/blob/master/src/lib/dialog/dialog.ts#L269)

None of the links are working. Struggling with this issue. Please show us how to pass data in a manageable way

**Comment by NithinBiliya** [comment]
[link](https://github.com/angular/components/blob/master/src/material/dialog/dialog.ts) for dialog

**Comment by nissoh** [comment]
@josephperrott is there a way to simply pass @Input data using `ComponentPortal`?
