### ISSUE TITLE
Two Checkbox Animations at the Same Time

### ISSUE THREAD

**Issue by RandomNonameDude** [angular/material2#8323]
#### Bug, feature request, or proposal:

Bug.

#### What is the expected behavior?

Probably to execute one animation only.

#### What is the current behavior?

When you change the checked state to true and indeterminate state to false during once change detection loop, two animations on a checkbox seem to execute at once which does not look pretty.

#### What are the steps to reproduce?

Here is the plunker: http://plnkr.co/edit/oWPGVO?p=preview

Try to click the button and you will see.

#### What is the use-case or motivation for changing an existing behavior?

I found this issue when I had a structure of more checkboxes (one root checkbox and >1 child checkboxes) reacting to each other.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4, Material 2.0.0-beta.11, Windows, TypeScript ~2.2.0, Google Chrome, Internet Explorer

**Comment by tinayuangao** [comment]
The problem is checkbox's status changed twice:
```
changeCheckAndIndeterminate() {
    if (this.isIndeterminate) { 
        this.isIndeterminate = false; // Changed from indeterminate to unchecked
        this.isChecked = true; // Changed unchecked to checked
    }
    else {
        this.isIndeterminate = true; // Changed from checked to indeterminated
        this.isChecked = false;
    }
  }
```

Only change the `indeterminate` value of the checkbox will fix this:

http://plnkr.co/edit/ea9T17sQNfNYUdnBMInO?p=preview
