### ISSUE TITLE
sidenav menu 

### ISSUE THREAD

**Issue by alialtun14** [angular/material2#8325]
I haven't found any component that is like google cloud sidenav menu. Is there any plan about this.

![menu](https://user-images.githubusercontent.com/782196/32601888-706c3cee-c544-11e7-85c3-6dc5e288ed8d.png)

**Comment by josephperrott** [comment]
The `MatSidenav` component is provided to create the sidenav container you are looking for and you are able to fill it with the content you would like.

We have no plans to make a component that is a spec copy of this sidenav you referenced.
