### ISSUE TITLE
Expansion panel: Events not fired when running in AOT

### ISSUE THREAD

**Issue by maxime1992** [angular/material2#8326]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Be able to subscribe to `mat-expansion-panel` events (for example `(closed)="..."`) **in AOT**

#### What is the current behavior?
With a simple `mat-expansion-panel`:

HTML
```html
<mat-expansion-panel (closed)="onClosed()">
  <mat-expansion-panel-header>
    <mat-panel-title>
      Personal data
    </mat-panel-title>
    <mat-panel-description>
      Type your name and age
    </mat-panel-description>
  </mat-expansion-panel-header>

  Something
</mat-expansion-panel>
```

TS
```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  onClosed() {
    console.log('Expansion panel closed!');
  }
}
```

Running:
- `ng serve` and opening/closing the expansion panel **displays** the console.log
- `ng serve --aot` and opening/closing the expansion panel **DOES NOT** displays the console.log 

#### What are the steps to reproduce?
No plunkr or stackblitz as it's AOT related...
I've made a really simple repro available on github: https://github.com/maxime1992/repro-expansion-panel-bug-AOT

(I've also made clear [commits](https://github.com/maxime1992/repro-expansion-panel-bug-AOT/commits/master) in order show how I did my setup)

Run one instance with `ng serve`, the other with `ng serve --aot` and watch your console after opening/closing the panel.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 1.5.0
Node: 8.6.0
OS: linux x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1
```

#### Is there anything else we should know?
Just thank you for all your good work :smile:

**Comment by willshowell** [comment]
Fixed on master via https://github.com/angular/material2/pull/7309

**Comment by bardiel** [comment]
Also, meanwhile, this workarround https://github.com/angular/material2/issues/7172#issuecomment-332582894

**Comment by maxime1992** [comment]
Excellent, thx guys :)
