### ISSUE TITLE
Issue with mat-select inside a div with padding and browser resize

### ISSUE THREAD

**Issue by flipZomb** [angular/material2#8329]
#### Bug, feature request, or proposal:
Have an issue with mat-select component and browser window resizing under specific circumstances.

#### What is the expected behavior?
mat-select should resize normally, see below.

#### What is the current behavior?
If I put the mat-select in a div and put padding on the div, then everything seems to work ok **at first** .... but now make the browser window smaller and use the mat-select again. The mat-select seems shifted out of the visible area.

The padding seems to be what is causing this.

First time ok
![usefirsttime_ok](https://user-images.githubusercontent.com/33517613/32606028-005fe4fe-c554-11e7-8fc5-3054d61e4432.png)

Now Resize
![nowresizewindow_notok](https://user-images.githubusercontent.com/33517613/32606027-004331ce-c554-11e7-89d9-d25e75af5d9d.png)

#### What are the steps to reproduce?

this takes the "basic sample" and puts a div with padding around it. Run in window mode.
https://plnkr.co/edit/ouW07jJwjyEGjy9nxeKW?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Needs to work normally.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome, IE, Firefox, Angular 4,5, Windows, Material 5.0.0-rc0 and older.

#### Is there anything else we should know?

**Comment by crisbeto** [comment]
Should've been fixed by https://github.com/angular/material2/pull/8765.
