### ISSUE TITLE
[Tooltip] Hangs matInput on iPhone

### ISSUE THREAD

**Issue by vegham** [angular/material2#8331]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Normal editing.

#### What is the current behavior?
Only allow one character input.

#### What are the steps to reproduce?
Open this on an iPhone: https://tinyurl.com/yd8k7pyt
Full plunker here: http://plnkr.co/edit/ySZamMTpNdhqmg59iPOO?p=preview

#### What is the use-case or motivation for changing an existing behavior?
n/a

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
See plunker. Only iPhone has the issue for what I know. In both Chrome and Safari.

**Comment by willshowell** [comment]
An annoying thing with plunker is that `run.plnkr.co` doesn't work unless you're currently editing it. Here's a stackblitz link of the issue 

https://material2-rc0-xkwafd.stackblitz.io

**Comment by vegham** [comment]
Thanks Will. I was not aware.
Let me add that the issue is present in an iPhone 6 simulator as well.
