### ISSUE TITLE
[Table] Posibility to have more rows for item with second row colspan

### ISSUE THREAD

**Issue by JiriBalcar** [angular/material2#8332]
#### What is the expected behavior?

declare two rows for one item in dataSource

#### What is the use-case or motivation for changing an existing behavior?
Table with items with second row for labels.

<table>
  <thead>
    <tr>
      <th>First column</th>
      <th>Second column</th>
    </tr>
  </thead>  
   <tr>
    <td>Item 1 - One</td>
    <td>Item 1 - Two</td>
  </tr>
  <tr>
    <td colspan="2">Item 1 - Two cols</td>
  </tr>
  <tr>
    <td>Item 2 - One</td>
    <td>Item 2 - Two</td>
  </tr>
  <tr>
    <td colspan="2">Item 2 - Two cols</td>
  </tr>
</table>

#### Is there anything else we should know?
Is this posible with the current implementation in ```cdk-table``` or ```mat-table```

**Comment by willshowell** [comment]
Though not yet documented, this is possible with the `when` predicate on the row.

```html
<mat-header-row *matHeaderRowDef="['data', 'id']"></mat-header-row>
<mat-row *matRowDef="let row; columns: ['data', 'id'];"></mat-row>
<mat-row
    *matRowDef="let row; columns: ['data']; when: isExtendedRow"
    class="darken">
</mat-row>
```
```ts
isExtendedRow = (index, item) => item.extend;

// ...

const DATA = [
  { data: 'ABC', id: 1 },
  { data: 'DEF', id: 2 },
  { data: 'GHI', id: 3, extend: true },
  { data: 'JKL', id: 4, },
  { data: 'MNO', id: 5, extend: true },
]
```

https://stackblitz.com/edit/material2-rc0-6drmzf?file=app%2Fapp.component.html

**Comment by JiriBalcar** [comment]
@willshowell Thank you for the quick response. Unfortunately this is not exactly what I was describing. When one or the other row, but I need to be rendered both of the rows as it is shown in the description. Item has two rows, first with two columns and the second with one column.

**Comment by willshowell** [comment]
Ah ok, the concept is similar to [expandable rows](https://github.com/angular/material2/issues/6095#issuecomment-334830404). There are a variety of ways to do it, but here's one option,

https://stackblitz.com/edit/material2-rc0-rqphi1?file=app%2Fapp.component.ts

Basically, you split each data row into two rows with the pertinent data in each.

**Comment by JiriBalcar** [comment]
@willshowell Thank you, this works. It still seems like quite hacky solution ;-)

It adds complexity for sorting, filtering, pagination and styling the table. For example if you do not want to have border between this two rows and not all of the items should have second row. 

It is possible with your solution but look like hack. And I do not know it it will not have performance penalty.

**Comment by merylb** [comment]
i used when but doesn't help in my case it extend just the left cells 

that's what i need : 
 
![image](https://user-images.githubusercontent.com/33625598/34787977-0f24381a-f631-11e7-8bd8-ac45e811d575.png)

but that's what i got:
![image](https://user-images.githubusercontent.com/33625598/34787990-1dc6d486-f631-11e7-8bc9-30e1b51c4fa9.png)

**Comment by merylb** [comment]
isExtendedColumn  is a callback that handle wich row to extend for example:

isExtendedColumn = (index, item) => item.number === '2555/003';

**Comment by naxisinc** [comment]
Can I put 3 items in the same row? I want to show many pictures but I need to display 3 of them in the same row. Thanks

**Comment by billbarni** [comment]
Almost 2019 and I can't have rowspan on a Angular Material Table without tons of hacks? Great. Every single component in this package requires a lot of shims and hacks to do the basics.

**Comment by andrewseguin** [comment]
Closing since this is possible today using `multiTemplateDataRows` 

https://stackblitz.com/edit/angular-3sdzy2?file=app/table-basic-example.html

**Comment by DmitryEfimenko** [comment]
How can I have multiple rows based on an array in an element?
For example, I have a records with structure like:
```ts
[
  {
    id: 1,
    name: 'Luke',
    books: ['book1', 'book2']
  }
]
```
So I'd like to create 3 rows per that record:
```html
<tr>
  <td>1</td>
  <td>Luke</td>
</tr>
<tr>
  <td colspan="2">book1</td>
</tr>
<tr>
  <td colspan="2">book2</td>
</tr>
```
I understand that `multiTemplateDataRows` lets me have multiple row definitions, but I need dynamic number of these row definitions. I need to put `*matRowDef` into a `*ngFor` loop somehow.

How can I achieve that?
