### ISSUE TITLE
More than 3 matLines in a nav list-item creates an incorrect ripple boundary

### ISSUE THREAD

**Issue by Kyderman** [angular/material2#8333]
#### Bug, feature request, or proposal:
When a list item in a nav-list has more than 3 lines, the ripple box is of the wrong size and it looks bad

#### What is the expected behavior?
The ripple box and scope of the list item should be consistent

#### What is the current behavior?
It is not consistent

#### What are the steps to reproduce?
Click the list item with 4 lines
Click the list item with 3 lines

Notice, that 4 lines has a weird "inner box"

http://plnkr.co/edit/fviuK5?p=preview

#### What is the use-case or motivation for changing an existing behavior?
To keep consistency

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest All
Chrome

#### Is there anything else we should know?
I had fish and chips for lunch?

**Comment by thw0rted** [comment]
It looks like the PR is already included, but the OP's ticket is technically a [spec](https://material.io/guidelines/components/lists.html#lists-behavior) violation:

> List tiles may contain up to three lines of text, and text length may vary between tiles in the same list. To display more than three lines of text, use a card.
