### ISSUE TITLE
Update your Documentation

### ISSUE THREAD

**Issue by DGmip** [angular/material2#8334]
```
<form class="example-form">
  <md-form-field class="example-full-width">
    <input mdInput placeholder="Favorite food" value="Sushi">
  </md-form-field>
</form>
```
cmon

**Comment by willshowell** [comment]
Where are you seeing this?

**Comment by josephperrott** [comment]
Closing as this is a snippet from the [input-overview-example](https://github.com/angular/material2/blob/master/src/material-examples/input-overview/input-overview-example.html) and the `md` prefixes were removed at the end of September.  It looks to be a caching/stale issue in your client.
