### ISSUE TITLE
Why is mat-checkbox inside *ngFor not getting the latest [checked] value from model?

### ISSUE THREAD

**Issue by nskshared** [angular/material2#8335]
#### What is the expected behavior?
mat-checkbox should be in-sync with the updates done on below myNgModel
<mat-checkbox [checked]="myNgModel">

#### What is the current behavior?
mat-checkbox turns from unchecked to checked for the first-time but doesn't pick any new changes. Doesn't toggle any more

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-checkbox-issue-zyjhd3

#### What is the use-case or motivation for changing an existing behavior?
I wanted my mat-checkbox to be in sync with the toggling I do on the dependent ngModel changes

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.1.3
Material 2.0.0-beta.12

**Comment by tinayuangao** [comment]
You will need to use `ngModel` to pick new changes, or listen to `change` event of the checkbox.

`<mat-checkbox [(ngModel)]="property.checkedOrUnchecked"></mat-checkbox>`
