### ISSUE TITLE
Wrong arrow shown when using matSortStart=desc"

### ISSUE THREAD

**Issue by zisha** [angular/material2#8336]
#### Bug
When setting matSortStart=desc" direction is set to "desc" on the initial header click but the arrow shown in the header is the asc arrow

#### What is the expected behavior?
The desc arrow (pointing up) should be shown

#### What is the current behavior?
The asc arrow (pointing down) is shown

#### What are the steps to reproduce?
Set matSortStart=desc" and click on header

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.4.1
node: 8.1.2
os: win32 x64
@angular/animations: 5.0.1
@angular/cdk: 5.0.0-rc0
@angular/common: 5.0.1
@angular/compiler: 5.0.1
@angular/core: 5.0.1
@angular/forms: 5.0.1
@angular/http: 5.0.1
@angular/material: 5.0.0-rc0
@angular/platform-browser: 5.0.1
@angular/platform-browser-dynamic: 5.0.1
@angular/platform-server: 5.0.1
@angular/router: 5.0.1
@angular/cli: 1.4.1
@angular/compiler-cli: 5.0.1
@angular/language-service: 4.3.6
typescript: 2.4.2

**Comment by willshowell** [comment]
The ascending arrow is supposed to point up. See the _Sorted column_ section in the [spec](https://material.io/guidelines/components/data-tables.html#data-tables-interaction).

**Comment by zisha** [comment]
I see. To my mind an arrow pointing up means the values are increasing in value as they go up.
I found a discussion about this [here](https://ux.stackexchange.com/questions/37564/use-up-or-down-arrow-to-represent-sort-ascending-at-table-header)

**Comment by willshowell** [comment]
I guess there's a little room for interpretation, but the current implementation matches the material spec,

![components-datatables-interaction-sortedcolumn](https://user-images.githubusercontent.com/6475576/32625476-4ec0777a-c55a-11e7-8305-266e91ccbe00.png)
(from [the spec](https://material.io/guidelines/components/data-tables.html#data-tables-interaction))

![screen shot 2017-11-09 at 2 29 16 pm](https://user-images.githubusercontent.com/6475576/32625518-636ee3d2-c55a-11e7-93d3-1260a61dc7fb.png)

(from [the docs](https://material.angular.io/components/sort/overview))

You can of course sort your own data however you wish.

**Comment by josephperrott** [comment]
Closing as we are basing our orientation of the arrow based on the material spec.
