### ISSUE TITLE
Radio Buttons in Menu not working on iOS 

### ISSUE THREAD

**Issue by gmccaw** [angular/material2#8337]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Opening the menu and tapping a radio button should select it

#### What is the current behavior?
Radio button flashes as if it will be selected but is not actually set

#### What are the steps to reproduce?
https://plnkr.co/edit/s0xTZ0R2XLjyIELYhQ81?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on Chrome and Safari on iOS and seeing issue on both.
Android devices worked as expected

**Comment by jelbourn** [comment]
The only supported API for menus right now is to contain menu items; they're not meant to hold arbitrary user content. You can use something like `cdkConnectedOverlay` to create a pop-up with arbitrary content
