### ISSUE TITLE
Add radio button provider to documentation

### ISSUE THREAD

**Issue by kara** [angular/material2#834]
https://github.com/angular/material2/tree/master/src/components/radio

README doesn't mention that you need MdUniqueSelection Dispatcher.

**Comment by pgurenko** [comment]
I would like to fix this to get familiar with the contribution process but have not found the similar examples in the docs or guide on where to put such dependency information.
My best guess is in the "Notes":
* Requires MdUniqueSelectionDispatcher as a provider from @angular2-material/core.
What do you think?

**Comment by kara** [comment]
@pgurenko Thanks for taking this on!   I think the best place would actually be on top, before the examples (to make sure it's seen). Add a section for "Setup" and show how you'd import the symbols, add the provider to providers, and add the directives to directives.

**Comment by pgurenko** [comment]
Something like that?

### Setup
Importing the symbols:
```typescript
import { MdUniqueSelectionDispatcher } from '@angular2-material/core';
import { MD_RADIO_DIRECTIVES } from '@angular2-material/radio';
```

Adding providers and directives:
```typescript
@Component({
  directives: [MD_RADIO_DIRECTIVES],
  providers: [MdUniqueSelectionDispatcher]
})
```

**Comment by kara** [comment]
Yeah, that looks great.  Only nitpick would be to add ellipses so it's clear the selector, template, etc are missing.

```ts
@Component({
  ...
  directives: [MD_RADIO_DIRECTIVES],
  providers: [MdUniqueSelectionDispatcher]
})
```

**Comment by zlepper** [comment]
How is this working with the new module system? 
Shouldn't the MdRadioModule be self contained enough that you can add it to your imports and everything should work?
