### ISSUE TITLE
Incorrect mat-select arrow position when min-width is given.

### ISSUE THREAD

**Issue by liuy97** [angular/material2#8347]
Incorrect mat-select arrow position when min-width is given.

#### Bug, feature request, or proposal:
If min-width is given, the value of min width will influence the position of mat-select arrow. It looks like the arrow outside the select box.

#### What is the expected behavior?
mat-select row will have a consistent position.

#### What is the current behavior?
mat-select arrow is outside select box when min-width is assigned to a big value.

#### What are the steps to reproduce?
https://plnkr.co/edit/W4uUCHD4Ms25HJ7FngzV?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material:  Version: 5.0.0-rc0-a019729
OS: Win 10
Browser: Chrome

**Comment by crisbeto** [comment]
You should be setting the `min-width` on the `mat-form-field`, not the `mat-select`. [Here's an updated Plunkr](https://plnkr.co/edit/Q58BEsug7iqUf0aCxX1d?p=preview).
