### ISSUE TITLE
Paginator doesn't have an option to hide the pageSize value.

### ISSUE THREAD

**Issue by nicu-chiciuc** [angular/material2#8359]
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

mat-paginator component should allow the option to hide the pageSize. 

#### What is the current behavior?

This cannot be done using the mat-paginator component or even the MatPaginatorIntl service.
The service allows to change the label on the left of the pageSize yet it doesn't have an option to completely hide it and the number.

![capture](https://user-images.githubusercontent.com/4076804/32660941-9939e240-c62d-11e7-8001-ec601f9d2c2a.PNG)

#### What is the use-case or motivation for changing an existing behavior?

It is desired to have a paginator with only 1 pageSize option so it is not necessary to show it.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular Material 2.0.0-beta.12
Angular 4.4.4

But probably all other versions are affected.

**Comment by elmeerr** [comment]
I came here to ask the same thing. Glad that the team is already working on it.

**Comment by yuripulga** [comment]
What if I want to only show this info? To me makes much more sense to use the pageSize before the table and the pagination right after.
