### ISSUE TITLE
md-input not playing along well with @angular/forms 0.2.0

### ISSUE THREAD

**Issue by pramttl** [angular/material2#836]
#### Bug

When I use md-input as a control field within a form:

      <md-input name="hero" [(ngModel)]="hero.name"
      placeholder="Superman" required>
      </md-input>

This gives a JS console errror:  `Error: Uncaught (in promise): No value accessor for 'hero'`

However using, `<input>` instead of `<md-input>` does not cause the problem and the form works smoothly.

#### To reproduce the error:

Simply use `<md-input>` instead of `<input>` in a working form.
Also note that I used `ngForm` from `@angular/forms` and not `@angular/common` like the [GETTING_STARTED](https://github.com/angular/material2/commit/63c7d9c27c9d032326996b28eff38aca4892dd58) suggests.

#### I am using the following:

material2: "2.0.0-alpha.6"
angular: "2.0.0-rc.4"
@angular/forms: "0.2.0"

**Comment by frankcalise** [comment]
I believe I have this working, could you point to a repository so I could maybe try and help?

**Comment by pramttl** [comment]
@frankcalise 
Here is a plunkr link with the error: http://plnkr.co/edit/YGQdQTydLpY8kgHX7vKs?p=preview
The error appears in the javascript console.

**Comment by pramttl** [comment]
I think this bug may be a duplicate of: https://github.com/angular/material2/issues/696

**Comment by pramttl** [comment]
Finally was able to solve this issue (Material2 addresses this bug in alpha.6). For some reason even after updating `package.json` to have `2.0.0-alpha.6`, and running `npm install`, the `@angular2-material` directory in node_modules was not getting updated.  (Weird - and I am not sure why)

So, I deleted node_modules/@angular2-material and reran `npm install` after already having updated to material2 `alpha.6` ofcourse and then `md-input` started working well with `@angular/forms` 0.2.0, without the `accessor` error.
