### ISSUE TITLE
deploy devapp - produces errors on firebase

### ISSUE THREAD

**Issue by klezm** [angular/material2#8368]
#### Bug:

after cloning the repository and setting up firebase via
`firebase login` `firebase init` 
i deployed the demo-app via `gulp deploy:devapp` thats the task (i found in [development.ts](https://github.com/angular/material2/blob/master/tools/gulp/tasks/development.ts#L86)) which builds the devapp and deploys it on firebase.

at https://angular-material2.firebaseapp.com/ you can see the result. in the developer console you can see that the page throws several errors.

#### What is the expected behavior?

i'd expect the app to somewhat run out of the box 😆 

#### What is the current behavior?

there are some errors with the `tslib.js` and `refCount.js`

#### What are the steps to reproduce?

run `gulp deploy:devapp`

#### Is there anything else we should know?

when i tried to run `gulp stage-deploy:devapp` which doesnt include the deployment to firebase, i got the error
`Error parsing triggers: Cannot find module 'ts-node'`

**Comment by jelbourn** [comment]
This app is only used for our own development and does break from time to time
