### ISSUE TITLE
Error: StaticInjectorError[BreakpointObserver] No provider for BreakpointObserver

### ISSUE THREAD

**Issue by chriscurnow** [angular/material2#8375]
#### Bug, feature request, or proposal:
Bug (Regression)

#### What is the expected behavior?
Ability to use SnackBar

#### What is the current behavior?
After update to 5.0.0-rc0, initialising MatSnackBar in component constructor causes error:

`Error: StaticInjectorError[BreakpointObserver] ... No provider for BreakpointObserver` 

at runtime

#### What are the steps to reproduce?
Add reference to 

`MatSnackBar`

in component constructor.

#### What is the use-case or motivation for changing an existing behavior?
I don't want to change an existing behavior. I just want it to work like it did before the update.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular 5.0.1
Angular CLI 1.5.0
Material 5.0.0-rc0
Mac OS High Sierra 10.13.1
Typescript 2.4.2
Chrome Version 61.0.3163.100
```

#### Is there anything else we should know?
When I add 

```
constructor(...,
...,
private snackbar: MatSnackBar){}
```

in my component I get this error. If I take out the reference to MatSnackBar, the error goes away.

**Comment by julianobrasil** [comment]
I have some snackbars working fine over here, including this stackblitz.com example: https://stackblitz.com/edit/dialog-example

**Comment by chriscurnow** [comment]
@julianobrasil thanks for letting me know. I am sure it is not snackbar itself. There must be something else causing the problem but I can't work it out. Are you using AOT?

**Comment by julianobrasil** [comment]
Using AOT.

**Comment by julianobrasil** [comment]
@chriscurnow, when I upgraded my test project to 5.0.1, nothing bad happened. In fact there was a little bug that made it throw an error that went away after upgrading it. I tried it with AOT.

**Comment by igor90007** [comment]
i have the same issue
`ERROR Error: StaticInjectorError[MatSnackBar]: 
  StaticInjectorError[MatSnackBar]: 
    NullInjectorError: No provider for MatSnackBar!`
This one also doesn't work in Safari and Mozilla

**Comment by chriscurnow** [comment]
@julianobrasil Thanks for the repo. I cloned and it does indeed work. So it is something to do with my setup that causing the problem. I will try comparing your app with mine and see if I can find something that is different. Thanks again 😄

**Comment by chriscurnow** [comment]
@jelbourn I don't regard this issue as closed. Yes it has something to do with my setup. It works in the very simple example posted by @julianobrasil. However it was working before the upgrade to 5.0.0-rc0 so something in there has broken my code. 

Of course it is entirely possible I am doing something wrong in my code but how do I find it?  It would be great to get something from the team about why we might get the error "No provider for BreakpointObserver". 

Also note nothing here addresses the problem reported by @igor90007.

**Comment by cyber-simon** [comment]
@chriscurnow I had the same problem just now. It was caused by a missing MatSnackbarModule import. I don't know why, but with Angular 4.x and Angular Material 2.0.0-beta it worked (it probably shouldn't have). After the upgrade to Angular 5.0.1 and Material 5.0.0-rc0 I had the same error message. 

Adding the following import solved it:
https://github.com/julianobrasil/material2-test/blob/master/src/app/app.module.ts#L35

```
NgModule({
...
  ],
  imports: [
...
    MatSnackBarModule,
...
```

**Comment by igor90007** [comment]
my fail. I tried:
`import {MatSnackBarModule} from "@angular/materia/snack-bar";`
but I have to:
`import {MatSnackBarModule} from "@angular/materia";`
Now, everything works fine. Thank you

**Comment by aelkoussy** [comment]
@igor90007 Thanks a lot for that comment, that other import solved it for me, but what is the difference between the 2 imports? (just to learn it)

**Comment by suleodu** [comment]
@cyber-simon  thanks this really save me

**Comment by marcosrbertuol** [comment]
@cyber-simon yeah man! That did it. Thanks!
