### ISSUE TITLE
mat-datepicker - Displays date in ISO format.

### ISSUE THREAD

**Issue by carttrac** [angular/material2#8379]
#### Bug, feature request, or proposal:
Using mat-datepicker.  

When creating a `FormControl`  or setting `FormControl.value` that is bound to `value` of `input` the date is displayed in ISO format .

#### What is the expected behavior?
It should display the date in en-US locale format: mm/dd/yyyy.

#### What is the current behavior?
Displays ISO string format.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

http://plnkr.co/edit/qOurJCVYUZMGCjiaal4o?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It is not behaving according to the specifications

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0
Material 5.0.0-rc0
TypeScript 2.6.1

**Comment by donroyco** [comment]
Duplicate of #7717

**Comment by carttrac** [comment]
OK.

Using [ngModel] instead of [value]  works.

Thanks.

**Comment by mmalerba** [comment]
This has been fixed: https://github.com/angular/material2/pull/7831
