### ISSUE TITLE
New install of demo app crashes with error related to MatInput

### ISSUE THREAD

**Issue by pevans360** [angular/material2#8380]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
After installing demo-app, be able to start it via npm run demo-app

#### What is the current behavior?
Get the following error in the cmd window (Windows 10):
```
Error: Error: E:/DevTest/material2/src/lib/input/input.ts:48:1: Error encountered in metadata generated for exported symbol 'MatInput':
 E:/DevTest/material2/src/lib/input/input.ts:165:48: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":164,"character":47}
    at E:\DevTest\material2\node_modules\@angular\compiler-cli\src\metadata\collector.js:663:27
... etc. 
```
Browser (Chrome) console has: 
```
Failed to load resource: the server responded with a status of 404 (Not Found)
zone.js:690 Unhandled Promise rejection: (SystemJS) XHR error (404 Not Found) loading http://localhost:4200/dist/packages/material/public-api.js
	Error: XHR error (404 Not Found) loading http://localhost:4200/dist/packages/material/public-api.js
	    at XMLHttpRequest.wrapFn (http://localhost:4200/node_modules/zone.js/dist/zone.js:1166:39)
	    at ZoneDelegate.invokeTask (http://localhost:4200/node_modules/zone.js/dist/zone.js:425:31)
	    at Zone.runTask (http://localhost:4200/node_modules/zone.js/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] 
```
 ... etc.
#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

1) Download zip (11/11/17 - 3PM) of material2-master.zip
2) Unzip to folder (material2)
3) Bring up cmd window and navigate to folder
4) Follow procedure on Getting Started page (https://material.angular.io/guide/getting-started) and install @angular/material, @angular/cdk, @angular/animations, also hammerjs
5) Run npm install
6) Run npm run demo-app ... this leads to the errors above.  

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.1, Material 5.0.0-rc0, OS - Windows 10 Pro 64-bit, TypeScript 2.4.2, browser Chrome: 62.0.3202.75

#### Is there anything else we should know?
Nothing I can think of.

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material2/pull/8367.
