### ISSUE TITLE
Value on input with a clear button jumps on mousedown

### ISSUE THREAD

**Issue by wuchtig** [angular/material2#8394]
#### Bug, feature request, or proposal:
Value on input with a clear button jumps on mousedown

#### What is the expected behavior?
The value shouldn't jump.

#### What is the current behavior?
![valuejump](https://user-images.githubusercontent.com/1224640/32701637-a9ca4dd6-c7d9-11e7-9ba3-d5cd961067da.gif)

#### What are the steps to reproduce?
Look [Input with a clear button demo](https://material.angular.io/components/input/examples)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
MSEdge: 41.16299.15.0
Material: 5.0.0-rc0-3ca801a

**Comment by DevVersion** [comment]
I wasn't able to reproduce that issue on MS Edge 41.16299.15.0. 

Can you please re-check and keep us updated on that issue?

**Comment by wuchtig** [comment]
Sorry for disturb. 

Seems like this issue only occurs on the [demo page](https://material.angular.io/components/input/examples).

**Comment by DevVersion** [comment]
Thanks for your response, but I'm still not able to reproduce that issue you described. Can you provide more information about your platform? zoom level etc. ?

**Comment by wuchtig** [comment]
Strange that you can't see this. 

Windows 10 Pro
Version 1709
Build 16299.64

Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

Resolution: 1920x1080
Zoom: 100%

Monitor: 24"

**Comment by DevVersion** [comment]
Yeah, I'm not sure what's different here. I basically have the same Edge version. I asked another person to try the issue on his computer, but he also wasn't able to see the issue.
