### ISSUE TITLE
[Sort] Animation looks weird

### ISSUE THREAD

**Issue by wuchtig** [angular/material2#8396]
#### Bug, feature request, or proposal:
Animation of arrow in mat-sort-header looks wierd.

#### What is the current behavior?
![sort](https://user-images.githubusercontent.com/1224640/32701893-e0a072e6-c7dd-11e7-9568-83383459abaa.gif)

#### What are the steps to reproduce?
Look [Material Demo Site](https://material.angular.io/components/sort/overview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
MSEdge: 41.16299.15.0
Material: 5.0.0-rc0-3ca801a

**Comment by jelbourn** [comment]
I think this is happening everywhere, not just Edge

**Comment by lacolaco** [comment]
I hit the same problem on Chrome stable , Angular 5, material 5.0.0-rc0. as far as I see, it happens after programmatically sorting.

![image](https://user-images.githubusercontent.com/1529180/32821454-d7a51d5a-ca16-11e7-836c-bca108d9afb3.png)

**Comment by andrewseguin** [comment]
Duplicate of #8612
