### ISSUE TITLE
Button [disabled]=true still invokes [routerLink] - is this ok?

### ISSUE THREAD

**Issue by alvipeo** [angular/material2#8399]
So if I have the following in my template:

`<a mat-raised-button [disabled]="!buttonsEnabled" [routerLink]="['']">Back</a>`

and when `buttonsEnabled = false` it follows `[routerLink]`. This is kind of surprise to me. Am I missing something or is this a bug?

**Comment by diicar** [comment]
There is no disabled attribute for hyperlinks. change for button

**Comment by alvipeo** [comment]
Man, good point! Thanks.
