### ISSUE TITLE
side menu cannot close after clicking on Button Toggle

### ISSUE THREAD

**Issue by jasonwzhu** [angular/material2#840]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
The sidenav menu should disappear as clicking on any other items.

#### What is the current behavior?
I downloaded the latest repository, started the server.  If clicking on Button Toggle, the sidenav menu won't disappear, by clicking Close or anywhere outside of sidenav area.  Only this item has the problem.
I use Linux CentOS 7, Firefox v47.0.

#### What are the steps to reproduce?
Download latest repo;
Start server;
Click on Button Toggle;
Click on Close or anywhere outside of sidenav.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

Sorry, can't provide as I am behind company firewall.

#### What is the use-case or motivation for changing an existing behavior?
I have to start over again to load the page.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2, rc 1
Material2, alpha 5
Linux, CentOS 7
Firefox, v47.0

#### Is there anything else we should know?
N/A

**Comment by jelbourn** [comment]
Button toggle hasn't actually been released yet and isn't done. I think you may be encountering a javascript error that it's currently throwing.
