### ISSUE TITLE
[mat-menu]: control the arrow position in a nested menu trigger

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#8402]
#### What is the expected behavior?
Developer can define the location of the arrow in a nested menu submenu trigger.

#### What is the current behavior?
Icon is fixed to left (or right in dir=rtl) and does not take into account to nested menu positioning.

#### What is the use-case or motivation for changing an existing behavior?
When a menu is close to the edge of the viewport, all nested menus will position on the opposite side. A menu on the top right, in LTR direction with a nested menu will create an arrow on the submenu trigger that is on the opposite side of the position of the submenu:

![image](https://user-images.githubusercontent.com/5377501/32706023-ad50322e-c822-11e7-9e33-beabc1f2becb.png)

Making the menu RTL makes it worse.

The optional locations should be one of:
  - left
  - right
  - auto

Where left and right are fixed.

**auto** will instruct the menu (or trigger) to calculate the position (left/right) based on where the submenu will open.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 5.0.1, material rc0

With the current implementation, this can be achieved with css classes.
It will also require extra padding based on the result (left/right), currently the extra padding is always right (or left in RTL)

@jelbourn If this feature is approved, and if possible, i'd like to implement if/once API is agreed upon.

Thanks.

**Comment by shlomiassaf** [comment]
see https://angular-material2-issue-4bxtus.stackblitz.io

**Comment by crisbeto** [comment]
This is according to the spec:

![Spec example](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bx4BSt6jniD7dlkwTUdncmtTTXM/components-menus-usage7.png)

Also see https://github.com/angular/material2/issues/7921#issuecomment-338283248 for a more details explanation.

**Comment by shlomiassaf** [comment]
I agree with your [comment](https://github.com/angular/material2/issues/7921#issuecomment-338283248) but this is still a problem.

The screenshot above is fine but when this is rendering on a trigger that is always on the right of the screen it's weird.

So, auto-setting an icon is out of the question but being able to define left/right for the arrow only in the top-most menu, that should be allowed.
