### ISSUE TITLE
Expansion panel memory leak

### ISSUE THREAD

**Issue by AnthonNilsson** [angular/material2#8403]
#### Bug, feature request, or proposal:
I have an SPA that uses angular material2. When using mat-expansion-panel I get rising number Detatched DOM trees if removing/adding the expansion panel.

#### What are the steps to reproduce?
If browsing to https://material.angular.io/components/expansion/examples and clicking on API -> Examples -> API and so on this behaviour could be reproduced. First after entering the page chrome heap snapshot shows:

![image](https://user-images.githubusercontent.com/7062803/32706140-4d01b07a-c81b-11e7-96a7-f785aaea5b40.png)

After clicking the tabs API, and Examples 10 times it shows:
![image](https://user-images.githubusercontent.com/7062803/32706181-901c3d12-c81b-11e7-9122-2a40e3ca846a.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
In my SPA I use:
* Angular 5.0.1
* Angular Material: 5.0.0-rc0
* Angular CLI 1.5.0

**Comment by josephperrott** [comment]
Closed via #8410
