### ISSUE TITLE
mat-datepicker for cs-CZ locale produces date with spaces, valid typed in date is marked as invalid

### ISSUE THREAD

**Issue by tomchovanec** [angular/material2#8408]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Datepicker produces date without spaces.
Valid typed in dates into input are not marked as invalid.

#### What is the current behavior?
Datepicker produces date with spaces.
26. 11. 2017 (please note 26._space_11._space_2017)
Valid date format is without spaces 26.11.2017.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-rr5ca4

#### What is the use-case or motivation for changing an existing behavior?
User is not allowed to type in date as is used to.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/****": "^4.4.6",
    "@angular/material": "^2.0.0-beta.12",
    "typescript": "^2.5.3"

OS: Win10 x64
Browser: Chrome Version 62.0.3202.89 (official build) (64bit)

#### Is there anything else we should know?
cs-CZ locale is similar to de-DE as far as I know.

**Comment by mmalerba** [comment]
The `NativeDateAdapter` simply delegates to the native `Date` which does not parse dates in the format you described. I recommend using the `MomentDateAdapter` or a custom date adapter (see https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings)
