### ISSUE TITLE
md-input doesn't pass through `pattern` attribute

### ISSUE THREAD

**Issue by najor** [angular/material2#841]
Hi,

Input tag has several validators (<code>required, minlength, maxlength, pattern</code>). It seems that <code>pattern</code> validator is not implemented or not working.

I am working with version 2.0.0-alpha.6

How is handle custom validators?

Thanks

**Comment by domfarolino** [comment]
@jelbourn Should `has pr` label be applied to this? I almost took a stab at it until I saw the PR haha

**Comment by tariknz** [comment]
Any idea when this will be merged? Any workaround?

**Comment by Habeeb-mohamed** [comment]
I am using 2.0.0-alpha.9-3 pattern is working fine

**Comment by mmalerba** [comment]
`md-input-container` is now available and will allow you to place the `pattern` attribute on the native `input` element
