### ISSUE TITLE
Features : onHeightChange event for MatTextareaAutosize directive 

### ISSUE THREAD

**Issue by geoseb** [angular/material2#8413]
Hi, I have a little feature request ! 

It is possible to have an event fired when the directive MatTextareaAutosize calculates a new height ? 
I don't know if other will have some uses for it but I think it's can be good for some cases ! 

Thx !

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
