### ISSUE TITLE
mat-select-panel inside ng2-bootstrap-modal

### ISSUE THREAD

**Issue by mariannafld** [angular/material2#8414]
#### What is the expected behavior?
Panel menu of select control should appear on the front. 

#### What is the current behavior?
Panel menu of select control on ng2-bootstrap-modal appears behind the modal dialog.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular material 5.0.0-rc0.

#### Is there anything else we should know?
On the regular page it works great.

**Comment by willshowell** [comment]
You may need to override bootstrap's modal or the overlay container's z-index. In general, conflicting styles as a result of using Material with other UI frameworks are not considered bugs within this lib.

**Comment by mariannafld** [comment]
Thank you, 
Right now made this: 
```
.cdk-global-overlay-wrapper, .cdk-overlay-container {
  z-index: 99999 !important;
}
```
And it works great. Sorry for rush. However, I notice that select menu is "jumping" up when selecting the element. What should I override to avoid it? Thank you

**Comment by willshowell** [comment]
I'm not sure what you mean by jumping. If you're talking about where it positions itself when open, that behavior is strictly following the [Material spec](https://material.io/guidelines/components/menus.html) and is not customizable.

**Comment by jelbourn** [comment]
Closing since we don't really have control over interactions with other libraries. Feel free to open a new issue (following the issue template) for other bug reports.

**Comment by akang** [comment]
@mariannafld lovely. I too just wanted some material design elements but not the whole 9 yards.
