### ISSUE TITLE
[Table] Error when navigating from route

### ISSUE THREAD

**Issue by mcalmus** [angular/material2#8415]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Routing and navigation proceeds successfully.

#### What is the current behavior?
Since updating to angular 5.0.0 and angular/material 5.0.0rc0 I've been unable to navigate to a new route when starting from one with an md-table. When trying to do so I get (trimmed somewhat for brevity):

Firefox error:

Error: Uncaught (in promise): TypeError: el.classList is undefined
DefaultDomRenderer2</DefaultDomRenderer2.prototype.removeClass
BaseAnimationRenderer</BaseAnimationRenderer.prototype.removeClass
DebugRenderer2</DebugRenderer2.prototype.removeClass
ce</e.prototype._setClasses/r@...cdk-a11y
...

IE Error:
unable to get property 'remove' of undefined or null reference

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
I haven't been able to boil this down to a minimally reproducible test case yet, but as I said above it happens when trying to navigate away from a page containing a md-table.

#### What is the use-case or motivation for changing an existing behavior?
Basic navigation

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 5.0.1
material 5.0.0rc0
Windows
FF 52 ESR, IE 11
TS 2.6.1

**Comment by jelbourn** [comment]
@andrewseguin can you investigate?

**Comment by andrewseguin** [comment]
@mcalmus Can you try and pin this down to a specific part of the table? Does this happen even with empty cell content? A working example would help us out here

**Comment by mcalmus** [comment]
@andrewseguin It does not happen with an empty table. I replaced the service call with a simple empty() call and don't see the issue.

**Comment by andrewseguin** [comment]
It's possible that its something to do with something in your cells. Try adding columns one-by-one to your empty table and see which cell causes the problem. If you find something we can use to reproduce, please let me know (ideally with a stackblitz/plunker) so we can dive into the issue and see if we can fix it. Thanks!

**Comment by mcalmus** [comment]
It turns out this problem is related to the use of matTooltip on an ng-container within the cell. The table in question uses an object for cell definition and is used by different components. Something like this:

<mat-table...>
  <ng-container *ngFor="...">
    <mat-cell ...>
      <ng-container *ngIf="..." [matTooltp]="...">
      </ng-container>
      <ng-container *ngIf="...">
      </ng-container>
    </mat-cell>
  </ng-container>
</mat-table>

This worked fine in the previous (< 5.0.0rc1) versions. Removing the matTooltip directive makes things work correctly. I'm not sure whether this is an issue with mastTooltip or if it only happens when used within a mat-table. I still can't create sample code, but I hope this will help to track down the issue.

**Comment by andrewseguin** [comment]
Looks like here's a reproduction of the issue 

https://stackblitz.com/edit/angular-uvsx1t?file=app/table-basic-example.html

I'm surprised that this worked in previous versions of angular. The `ng-container` does not actually create a containing element, so the `matTooltip` does not know what element it is being attached to. Are you sure it worked before?

To solve this, you'll want to make sure `matTooltip` is placed on a real element, so just change your first `ng-container` to a `div` or place the tooltip on a real element inside the `ng-container`.

Alternatively you can put the tooltip on the `mat-cell` and have a condition like `[matTooltip]="some_condition ? '...' : ''"`

**Comment by mcalmus** [comment]
@andrewseguin By "worked" I mean that the page didn't blow up. The matTooltip variable doesn't actually resolve to actual text in any actual usage. In any event, I already changed to use a span in place of the ng-container, and that seems to work.

That said, it would be nice to at least have a useful error message in this situation.

**Comment by andrewseguin** [comment]
Good feedback on having a useful error message, I agree that the error wasn't helpful here

Opened issue #8724 to track that
