### ISSUE TITLE
sidenav doesn't show up

### ISSUE THREAD

**Issue by ksnolan** [angular/material2#842]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When you use sidenav tag by default is should appear on the left side of the screen. 

#### What is the current behavior?
Sidenav shows up across the screen above or under the toolbar (if a toolbar exists)

#### What are the steps to reproduce?

- Install @angular2-material/sidenav from npm (version 2.0.0-alpha.6)
- Type the following (I got the code from npm page, I only set the layout to fullscreen) in your html file:

```
<md-sidenav-layout fullscreen>
    <md-sidenav #start (open)="mybutton.focus()">
      Start Sidenav.
      <br>
      <button md-button #mybutton (click)="start.close()">Close</button>
    </md-sidenav>
    <md-sidenav #end align="end">
      End Sidenav.
      <button md-button (click)="end.close()">Close</button>
    </md-sidenav>
    My regular content. This will be moved into the proper DOM at runtime.
  </md-sidenav-layout>
```

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, browsers are affected?
I am using version version 2.0.0-alpha.6,
OS X El Capitan version 10.11.5,
Google Chrome

#### Is there anything else we should know?
<img width="1259" alt="screen shot 2016-07-11 at 8 51 03 am" src="https://cloud.githubusercontent.com/assets/20330465/16737158/eb44f598-4744-11e6-89c1-a67335dafdc7.png">

<img width="1276" alt="screen shot 2016-07-11 at 10 50 41 am" src="https://cloud.githubusercontent.com/assets/20330465/16740763/676a90c8-4755-11e6-9b48-105bdc1ae483.png">

<img width="277" alt="screen shot 2016-07-11 at 10 40 21 am" src="https://cloud.githubusercontent.com/assets/20330465/16740790/7e52e86c-4755-11e6-818a-9c7a35a8305f.png">

**Comment by j3ddesign** [comment]
I did some testing with your example html above and had no issue with the sidenav not showing, however did encounter an issue with focusing the close button on the (open) event

Plunker here: http://plnkr.co/edit/WvZtsQsdBWwUhgK03QXp?p=preview

**Comment by ksnolan** [comment]
I am going to retest it. I wonder what I did wrong. In my app it just shows
like a list without a container. Thanks. I'll get back to you after as soon
as I have retested it.

**Comment by ksnolan** [comment]
I figured it out! I imported MdSidenav from
@angular2-material/sidenav instead of
MD_SIDENAV_DIRECTIVES from @angular2-material/sidenav/sidenav. Thanks!
