### ISSUE TITLE
Expansion Panel left/right borders do not show when embedded in a stepper

### ISSUE THREAD

**Issue by cfi2017** [angular/material2#8444]
#### Bug, feature request, or proposal:
Bug report

#### What is the expected behavior?
The left / right borders and the bottom border of an expansion panel should show when embedded in a mat-step element.

#### What is the current behavior?
The borders do not show.

#### What are the steps to reproduce?
http://plnkr.co/edit/BrzL61TujU84KzKgqSjC?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Unknown - See plunkr
Browsers: At least Latest Chrome, Firefox Quantum

#### Is there anything else we should know?
Disabling overflow: hidden on the .mat-horizontal-stepper-content div seems to fix the issue.

**Comment by josephperrott** [comment]
This is caused by the CSS rule in stepper:
```css
.mat-horizontal-stepper-content {
  overflow: hidden;
}
```

Since the `mat-accordion` is filling the horizontal space of the stepper's content, it does not show the shadows as they do not offset space.  An option would be to put a `margin` on either side of the `mat-accordion`, or directly set the width with the `width` style rule.

**Comment by cfi2017** [comment]
Ended up wrapping the `mat-accordion` with a `div` and a padding of `3px`.

The border overflowing also applies to the top of the first and the bottom of the last expansion panel in the accordion.

Is this intended behavior? It harms the visual flow of the page since it becomes more difficult to distinguish between container and content.

**Comment by willshowell** [comment]
@cfi2017 The expansion panels don't actually have borders, just box-shadows. Shadows are not taken into account when the browser calculates the size of an element, so if an element expands 100% of the width (and/or height) of a container with `overflow: hidden`, its shadows will be visually clipped.

**Comment by lyschoening** [comment]
@josephperrott Since this issue has been closed is the suggested solution here to stick an `overflow: visible!important` into the CSS? A great number of Material components have shadows and by the Guidelines they should align with the edge of the stepper content.
