### ISSUE TITLE
Chip input placeholder overlaps text

### ISSUE THREAD

**Issue by redjab** [angular/material2#8448]
#### Bug, feature request, or proposal:
Bug
Chip input placeholder overlaps text when floatPlaceholder="never"

#### What is the expected behavior?
Input doesn't overlap placeholder. Placeholder should disappear if there's any input value

#### What is the current behavior?
Input overlaps placeholder if there's only one character

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-31ymjs?file=app%2Fapp.component.html
Type one character in the input

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.0.0rc0
Angular 5.0.1

**Comment by jelbourn** [comment]
@mmalerba this looks like an issue with form-field

**Comment by mmalerba** [comment]
I think it's a chips issue. The chip list needs to consider itself not empty if there is uncommitted text in the input
