### ISSUE TITLE
bug(md-input): MdInput with type date cannot handle placeholders

### ISSUE THREAD

**Issue by drager** [angular/material2#845]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Placeholders should always be small for date inputs since it defaults to: `mm/dd/yyyy`.

#### What is the current behavior?
Placeholder is large for the default value for date inputs.

#### What are the steps to reproduce?
http://plnkr.co/edit/MURSTrNjlRj3AGzZkEfO?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
* **Angular version:** 2.0.0-rc.4
* **Material version:** 2.0.0-alpha.6
* **Browser:** Chrome Version 51.0.2704.106 (64-bit)
* **Language:** TypeScript 2.0.0-dev
* **Built with**: Webpack

**Comment by msegers** [comment]
The date input will get a picker. For now I'd suggest styling the label as if it was always filled in (that's what I do).

**Comment by drager** [comment]
@msegers: I see, styling it though seems like an ugly hack to be honest... I added a pull that fixes the bug described above.
