### ISSUE TITLE
Connected CDK Overlays sometimes get positioned outside the viewport

### ISSUE THREAD

**Issue by adamdport** [angular/material2#8452]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
If the connected component is narrower than the viewport, the CDK should never position beyond the bounds of the viewport. I can't think of when this would be desirable. The top left corner should be at least 0, and the bottom right corner should be at most the width/height of `body`.

#### What is the current behavior?
CDK overlays sometimes gets positioned such that the component attached to the overlay gets cut off.

#### What are the steps to reproduce?
http://plnkr.co/edit/qbivIGe33PpHY1ybd6ZR?p=preview

Good: ![good](https://user-images.githubusercontent.com/3020987/32846180-90a35092-c9f4-11e7-8506-822b7ab67c99.PNG)
Bad: ![bad](https://user-images.githubusercontent.com/3020987/32846182-92bada26-c9f4-11e7-8241-d102334cefc6.PNG)

#### What is the use-case or motivation for changing an existing behavior?
Users should be able to see the entire overlay if there is room to display it. If the overlays have close buttons, it's possible that they could be inaccessible.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
5.0.0, 5.0.0, chrome

**Comment by jelbourn** [comment]
Tracking this via #6534, which will cover this issue
