### ISSUE TITLE
Upgrading to angular 5/material 5 errors

### ISSUE THREAD

**Issue by avindor** [angular/material2#8456]
#### Bug

When trying to upgrade angular from ( 4..4.6 to 5.*) and using the latest material library, I'm getting the following errors when running ng serve:

ERROR in src/node_modules/@angular/cdk/table/typings/table.d.ts(38,22): error TS2420: Class **'CdkTable<T>' incorrectly implements interface 'CollectionViewer'.**
  Types of property 'viewChange' are incompatible.
    Type 'BehaviorSubject<{ start: number; end: number; }>' is not assignable to type 'Observable<{ start: number; end: number; }>'.
      Types of property 'lift' are incompatible.
        Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<{ start: number; end: number; }, R>) => Observable<R>'.
          Type 'Observable<{ start: number; end: number; }>' is not assignable to type 'Observable<R>'.
            Type '{ start: number; end: number; }' is not assignable to type 'R'.
src/node_modules/@angular/material/chips/typings/chip-list.d.ts(27,22): error TS2420: Class 'MatChipList' incorrectly implements interface 'MatFormFieldControl<any>'.
  Types of property 'stateChanges' are incompatible.
    Type 'Subject<void>' is not assignable to type 'Observable<void>'.
      Types of property 'lift' are incompatible.
        Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<void, R>) => Observable<R>'.
          Type 'Observable<void>' is not assignable to type 'Observable<R>'.
            Type 'void' is not assignable to type 'R'.
src/node_modules/@angular/material/input/typings/input.d.ts(15,22): error TS2420: Class 'MatInput' incorrectly implements interface 'MatFormFieldControl<any>'.
  Types of property 'stateChanges' are incompatible.
    Type 'Subject<void>' is not assignable to type 'Observable<void>'.
src/node_modules/@angular/material/select/typings/select.d.ts(73,22): error TS2420: Class 'MatSelect' incorrectly implements interface 'MatFormFieldControl<any>'.
  Types of property 'stateChanges' are incompatible.
    Type 'Subject<void>' is not assignable to type 'Observable<void>'.
src/node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
src/node_modules/rxjs/observable/dom/WebSocketSubject.d.ts(23,22): error TS2415: Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<T, R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.

#### What is the expected behavior?

Should be able to use angular 5 with the latest material library(5.0.0-rc0)

#### What is the current behavior?

Gettings error when trying to serve the application

#### What are the steps to reproduce?

upgrading an existing angular+material application from version 4..4.6 (angular) and  2.0.0-beta.1 (material)  to version 5.1.0-beta.0(angular) and  5.0.0-rc0 (material).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
_                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.0
Node: 6.9.4
OS: win32 x64
Angular: 5.1.0-beta.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.3
typescript: 2.4.2
webpack: 3.8.1
rxjs@5.5.2

#### Is there anything else we should know?

I've also tried the latest version of typescript and rxjs and I've tried  using the configuration of tsconfig from here:  https://github.com/angular/material2/blob/master/tsconfig.json

**Comment by Splaktar** [comment]
Have you tried with Angular `5.0.1`?

**Comment by avindor** [comment]
Yes I have. I've tried all versions of angular 5.0.0 and above.
These are the same errors as in:
https://github.com/angular/angular/issues/17800 , 
but none of the suggested solutions worked.

**Comment by jelbourn** [comment]
I recommend clearing out your `node_modules` and `package-lock.json` for a fresh install

**Comment by okeydoky** [comment]
Used to have the same error. Change rxjs version from 6.0.0-alpha1 to 5.5.2 solves my problem. Also I'm using typescript@2.4.2

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
