### ISSUE TITLE
ViewEncapsulation.Native fails to correctly display the sidebar

### ISSUE THREAD

**Issue by williamBurgeson** [angular/material2#8467]
IMO this is a bug, although there is a separate sequest at #3386

See https://github.com/williamBurgeson/ng-mat-ve-issue for an example. The component (which is routed to but automatically displayed anyway) is set to ViewEncapsulation.Native and the sidebar fails to display. For the actual project I am working on I hacked / fixed this by adding a `transform: translate3d(0px, 0px, 0px) !important;` rule on .mat-drawer, however really this should work correctly whatever the ViewEncapsulation mode

**Comment by jelbourn** [comment]
See #3386, we don't currently support native encapsulation.

**Comment by williamBurgeson** [comment]
When are you planning to drop IE11 and support the Shadow DOM?
Please don't tell us it won't be until 14th October 2025 (the day after my 50th birthday)

**Comment by willshowell** [comment]
@williamBurgeson https://github.com/angular/material2/issues/7374 is tracking that
