### ISSUE TITLE
Getting "No component factory" error while opening a Material Dialog in lazy loaded Component

### ISSUE THREAD

**Issue by nithindan** [angular/material2#8473]
Hi,
Im getting the following error when i try to open Material Dialog in `ConfirmBoxComponent`.

> No component factory found for ConfirmBoxComponent. Did you add it to @NgModule.entryComponents?

I have already added ConfirmBoxComponent in entryComponents list
```
    declarations: [
      ConfirmBoxComponent
    ],
    exports: [ConfirmBoxComponent],
    entryComponents: [
      ConfirmBoxComponent
    ],
```

The module that contain ConfirmBoxComponent is loaded via Lazy loading technique.

I'm not sure this is  bug or not.

I'm using latest version of Angular and Material
```
   "@angular/core": "^5.0.0",
  "@angular/material": "^5.0.0-rc0"
```

**Comment by donroyco** [comment]
Have you checked #1491?

**Comment by nithindan** [comment]
Ya . But its not working for me . 
I have  added component for md-dialog in entry components of my lazy loaded Module. But i'm getting that error.

**Comment by jelbourn** [comment]
Can you please share your entire NgModule setup?

**Comment by nithindan** [comment]
Hi, check now

https://gist.github.com/nithindan/f1a027e4b8589c59af9ec763b0ffded8

**Comment by nithindan** [comment]
@jelbourn Is there any way to fix this ?

**Comment by jelbourn** [comment]
You need to import `MatDialogModule` in `ConsumerModule` in order for it to know about the `entryComponents` there

**Comment by nithindan** [comment]
thanks a lot @jelbourn . it worked <3

**Comment by ruant** [comment]
Is this still the solution for this issue? Or has something else changed as of late?  
I can't seam to get this to work, this is basically the exact same setup I got, but only getting:  
`No component factory found for LoginDialogComponent`

**Comment by travtarr** [comment]
In regards to Angular v6+: in case anyone is using the `MatDialog` service inside another injectable service and is using the `{ providedIn: 'root' }` option for that service, you'll need to instead provide that service in the `providers` array of the module where your dialog components are declared.

**Comment by Max101** [comment]
@travtarr thanks so much for the answer.... I had that exact same issue. 
Plus it also only started working after i killed off `ng serve` 

In short: If you the service building your component is only provided in `root`, be sure to also provide it in the lazy loaded module! 

Why does that need to be like this though?

**Comment by jingignoli** [comment]
@travtarr  "you'll need to instead provide that service in the providers array of the module where your dialog components are declared." this will declare a new instance of the service so it's not possible to have a singleton in the app to launch dialog ?

**Comment by travtarr** [comment]
@jingignoli I didn't clarify in my original post, but you'll want to remove the `providedIn: 'root'` when you provide it in a module.

**Comment by jingignoli** [comment]
Thanks for your answer but the service will be scoped to the module.
I need a singleton in my app to control my modals.

**Comment by travtarr** [comment]
@jingignoli Then you'll probably need to place your modal declarations in a non-lazy-loaded module to avoid this issue.

**Comment by min-w-park** [comment]
@jingignoli have you addressed this issue? I have same issue as yours :(

**Comment by jingignoli** [comment]
@min-w-park no i haven't created an issue for this, i don't know if it's a bug or a normal behavior.

**Comment by liuxinqiong** [comment]
I have the same question about it，When I open lazyload module.
