### ISSUE TITLE
mat-select not giving underline and placeholder 

### ISSUE THREAD

**Issue by Anoop-Goudar** [angular/material2#8474]
#### Bug, feature request, or proposal:
Underline for the dropdown is not rendering and placeholder value is not displaying, please see the code below
```

<mat-select *ngIf="someCheck" 
  (ngModelChange)="updateonchange()" 
  [(ngModel)]="selectedvalue">
   <mat-option>
          Test
   </mat-option>
   <mat-option>
          Test1
   </mat-option>
</mat-select>
```

#### What is the expected behavior?
It was working fine with md-select, after the updating to the latest release, I am having this issue

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/material": "^5.0.0-rc0",
"@angular/animations": "^5.0.1",
 "@angular/cli": "^1.5.0",
"typescript": "^2.6.1"

using Ubuntu and Google Chrome
#### Is there anything else we should know?
Please check the screen shot
![nounderline](https://user-images.githubusercontent.com/4173039/32889808-486167de-caf2-11e7-91c9-067aff759649.png)

**Comment by benb7760** [comment]
`mat-select` must appear inside a `mat-form-field` from [beta 12](https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta12-marble-mustache-2017-10-05)

**Comment by crisbeto** [comment]
@benb7760 is correct that you need to wrap your select in a `mat-form-field`. Also you need to import the `MatSelectModule` and `MatFormFieldModule` in your app.

**Comment by Anoop-Goudar** [comment]
Thanks!

**Comment by kaziupir** [comment]
You should update examples on https://material.angular.io

**Comment by benb7760** [comment]
@kaziupir it's likely a caching issue in your browser - it's affected a lot of people recently. the examples are correct when I browse in incognito mode

**Comment by finalxcode** [comment]
@benb7760 thanks
