### ISSUE TITLE
/@angular/material/material"' has no exported member 'CompatibilityModule'

### ISSUE THREAD

**Issue by bobKasbi** [angular/material2#8481]
#### Bug, feature request, or proposal:
[ts] Module '"/Users/userName/myApp/main-app/node_modules/@angular/material/material"' has no exported member 'MATERIAL_COMPATIBILITY_MODE'.

#### What is the expected behavior?
import { MATERIAL_COMPATIBILITY_MODE, NoConflictStyleCompatibilityMode } from '@angular/material';

Import to prevent issues regarding conflicts 

#### What is the current behavior?
Seems that MATERIAL_COMPATIBILITY_MODE and NoConflictStyleCompatibilityMode have been diprecated or at least don't work with Angular 5.

#### What are the steps to reproduce?
import { MATERIAL_COMPATIBILITY_MODE, NoConflictStyleCompatibilityMode } from '@angular/material';/>

#### What is the use-case or motivation for changing an existing behavior?
It's a bug with Angular 5

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`Angular CLI: 1.5.0
Node: 8.0.0
OS: darwin x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.3
typescript: 2.4.2
webpack: 3.8.1`

#### Is there anything else we should know?
After trying to use Angular 5, I get the mentioned error in VisualStudio Code and also when I run:
`ng test --app appName --sm=false`
FYI - It's an a multiple app project.

**Comment by willshowell** [comment]
See the [CHANGELOG](https://github.com/angular/material2/blob/master/CHANGELOG.md#500-rc0-cesium-cephalopod-2017-11-06)

* `MATERIAL_COMPATIBILITY_MODE`, `CompatibilityModule`, `NoConflictStyleCompatibilityMode`,
  `MatPrefixRejector`, `MdPrefixRejector` symbols have been removed.

**Comment by crisbeto** [comment]
The `CompatibilityModule` is no longer necessary after the switch to `mat-` prefixes.

**Comment by bobKasbi** [comment]
Thanks guys! I did read the new updates regarding Angular but just couldn't find the affected issue directly. But what about `providers:[...]` in the module? 
e.g. `{ providers:[...,provide: MATERIAL_COMPATIBILITY_MODE, useValue: true }]`? can just be removed? Thanks!

**Comment by mrp100461** [comment]
I am a getting the same error in angular 5 and its in the app.module.ts
