### ISSUE TITLE
Progress-bar example on material.angular.io is broken

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#8497]
https://material.angular.io/components/progress-bar/overview

@amcdnl could you take a look?

**Comment by TheRedD0t** [comment]
@jelbourn Which example exactly do you mean, because I can't spot any broken one!? Is this connected to https://github.com/angular/material2/issues/7606?

**Comment by bardiel** [comment]
Also, could it be a cache problem in the browser?
When I access the link I see:
![2017-11-17-102219_811x256_scrot](https://user-images.githubusercontent.com/1416163/32949348-46c8beba-cb81-11e7-8ab5-c79071dbb645.png)

But CTRL-SHIFT-R and everything works...

**Comment by bardiel** [comment]
If so, @jelbourn, I believe it may actually be what you said here: https://github.com/angular/material2/issues/8175#issuecomment-341162613

**Comment by jelbourn** [comment]
So it is- it threw me off that the rest of the demos worked; usually they'd all been broken.

**Comment by bardiel** [comment]
Weird magic these service workers. =P

**Comment by merobal** [comment]
Well, for me the demo here is still not working (even after CTRL+SHIFT R), the code tabs are empty, and the plunker example shows strange files.
![image](https://user-images.githubusercontent.com/5844511/32960343-db4381e0-cbc4-11e7-8b70-292508d11410.png)
![image](https://user-images.githubusercontent.com/5844511/32960354-e0a9c108-cbc4-11e7-95f6-b087d0aad5ae.png)

**Comment by jelbourn** [comment]
Visit chrome://serviceworker-internals/ and unregister the worker for material.angular.io

**Comment by merobal** [comment]
Thanks, now it works well.
