### ISSUE TITLE
overlapTrigger, xPosition, and yPosition have no effect on mat-menu

### ISSUE THREAD

**Issue by ShawnMercado** [angular/material2#8498]
#### Bug
Applying `[overlapTrigger]="false"` to a `mat-menu` seems to have no effect.  As a matter of fact, the `xPosition` and `yPosition` attributes seem to have no effect either.

#### What is the expected behavior?
I've got a button that triggers a menu like this:
`
 
    <button mat-button [matMenuTriggerFor]="reportsMenu">Reports <mat-icon>expand_more</mat-icon></button>
    <mat-menu class="sub-menu" #reportsMenu="matMenu" [overlapTrigger]="false">
      <button mat-menu-item>Observation Summary Report</button>
      <button mat-menu-item>Raw Excel Report</button>
    </mat-menu>
`

According to the docs, the attributes mentioned above should alter the positioning.

#### What is the current behavior?

In my application, none of the attributes have any effect.  The menu popup always appears directly over the button that triggers it.

#### What are the steps to reproduce?

I CANNOT reproduce this in a plunker.  I've been trying for hours.  I drop the exact same html into the plunker and it works fine.  I am at a complete loss.

all I can do is post the markup and hope someone just knows what is going on from experience.  It has to be some sort of configuration error

```<mat-toolbar class="mat-typography" color="primary">
  <button mat-button routerLink="/">
    <img src="../assets/img/Icon_256.png" id="fos_logo_sm"/>
    <span class="mat-title">{{title}}</span></button>

  <!-- This fills the remaining space of the current row -->
  <span class="fill-remaining-space"></span>
  <div fxLayout="row" fxShow="false" fxShow.gt-sm>

    <!-- Reports Links -->
    <button mat-button [matMenuTriggerFor]="reportsMenu">Reports <mat-icon>expand_more</mat-icon></button>
    <mat-menu #reportsMenu="matMenu" [overlapTrigger]="false">
      <button mat-menu-item>Observation Summary Report</button>
      <button mat-menu-item>Raw Excel Report</button>
    </mat-menu>

    <!-- Users Links -->
    <button mat-button >Users <mat-icon>expand_more</mat-icon></button>
  </div>
  <button mat-button [matMenuTriggerFor]="menu" fxHide="false" fxHide.gt-sm>
    <mat-icon>more_horiz</mat-icon>
  </button>

  <button mat-button [matMenuTriggerFor]="userMenu" *ngIf="!!user">
    Hello, {{user.firstName}}
  </button>
  <mat-menu #userMenu="matMenu">
    <button mat-menu-item>View Profile</button>
    <button mat-menu-item (click)="logout()">Logout</button>
  </mat-menu>
</mat-toolbar>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I updated everything to the latest versions as of yesterday before implementing.  I'm using google chrome.

**Comment by willshowell** [comment]
If it's in the top right corner of the viewport (which it _kinda_ looks like in your markup), then it won't really matter how you set xPosition and yPosition. There is only one position that lands within the viewport: `before` and `below`.

That doesn't help with `overlapTrigger` though. Can you maybe post a screenshot?

**Comment by ShawnMercado** [comment]
it's not quite in the corner.  Here are two shots that show that part of the toolbar and how the menu triggers after clicking the "Reports" button.

**Comment by ShawnMercado** [comment]
Ha, what would you know.  A new day and it only took me 5 minutes to realize what's wrong.  I have another element with the attribute "#reportsMenu" (not in the markup I posted) and a separate trigger for it.  It's meant to be this way since they never show at the same time (the second is essentially a small screen replacement for the first).  As soon as I comment that element out, the original menu behaves correctly.

I guess I need to give them different names is all.  It might be nice if this somehow threw a compiler error or was emphasized more in the documentation, but ultimately this is just user error.  Thanks.

**Comment by willshowell** [comment]
I think datepicker has an error for when you try to reuse one for multiple inputs. Maybe there is an error that can get added.

Can you clarify what it was?

1. Trying to reuse the sample menu in multiple triggers
2. Using the same template ref name for multiple menu/trigger pairs

**Comment by ShawnMercado** [comment]
It's the second one, I was using the same ref name, `#reportsMenu="matMenu"` for two different elements.

**Comment by willshowell** [comment]
I don't think there's any good way for this library to recognize when that's happened, since it's kind of in Angular-land (not much different than redefining a variable in JS). I think a [language service extension](https://angular.io/guide/language-service) might be able to detect this but I'm not sure.

**Comment by ShawnMercado** [comment]
The language service doesn't catch it or doesn't think it's wrong.  I'm using it with Webstorm.

On second thought I wonder if this behavior is valid.  Why should a duplicate ref name stop the positioning from working correctly?

**Comment by willshowell** [comment]
Maybe this example can help explain it,

https://stackblitz.com/edit/material2-rc0-mvg4cm?file=app/app.component.html

**Comment by ShawnMercado** [comment]
Oh I see.  It's grabbing the second menu no matter what.  I just didn't notice it because mine were identical.  Thanks.

**Comment by crisbeto** [comment]
Closing since this looks like a user error. Also FWIW, we may be able to detect it, but I'd rather avoid it, because it would mean having to store a reference to the trigger on the menu itself.
