### ISSUE TITLE
Travis CI enforces TSLint

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#85]

**Comment by d3viant0ne** [comment]
@jelbourn Happy to take this one. I do have a few questions based on what I can see in travis.

- I assume lint is a build failure from the issue title.
- Currently you exec based on a bash script that executes build & test based on a condition.
- For the sake of saving time, we would only want to lint once which would mean tweaking the build process.
- Do you want to fail fast in the case of a linting error?

I've spend more time on CI servers than I care to say. If you want to throw me a few requirements, i'll pull out the lint brush.

**Comment by jelbourn** [comment]
cc @hansl 

* Yes, the build should fail fast for lint errors
* It looks like angular-cli just added an `ng lint` command, so we should take advantage of that

Everything else you've said sounds right to me.

**Comment by d3viant0ne** [comment]
@jelbourn I'll take a look at angular-cli and keep it inline with that. I'll workout the particulars with @hansl

**Comment by d3viant0ne** [comment]
@jelbourn @hansl 

**CI Execution**
The behavior of a linting error can be seen [here](https://travis-ci.org/d3viant0ne/material2).

- A lint error will brick the entire build in aprox. 50 seconds.
- After discussion with Hans, the "ng lint" command will be used at a later date when the project matures
- Given this was going to be a "throw away" addition, I went with the simplest solution
- I chose to add it as an npm script & not travis script execution to allow local execution as imho, linting errors should never be pushed in the first place.

That said, the simple solution doesn't exactly fail elegantly though the reason for the failure is apparent when looking at the output.

**Existing TSLint Errors**
I've fixed all the "low hanging fruit" in regards to TSLint errors.

The remaining list begins to get into "should ignore" vs. "should fix"
Some of the unused variables are obvious ( or at least appear to be ) others very well may be there for a reason I don't know being new to the project. I also definitely wanted to check in before I start renaming variables ( src/core/facade/test_injector.ts ).

The remaining errors can be seen in the latest [travis build](https://travis-ci.org/d3viant0ne/material2/jobs/113911638).

I was planning to squash everything in the "low hanging fruit" category above before starting on the remaining errors to make them a bit easier to review/discuss. Just need to know if I should continue fixing or if you would prefer someone else fix what remains.

**Comment by jelbourn** [comment]
Looking good! It would be great if you wanted to also fix the outstanding errors, and starting with the low-hanging fruit sounds good to me. 

One thing I noticed that should make it a little easier is that we should add an unused-variable ignore pattern for `ddescribe` and `iit` since you typically want to keep them around:
```json
"no-unused-variable": [true, {"ignore-pattern": "ddescribe|iit"}]
```

Looking forward to reviewing the PR. Thanks for your contributions!

**Comment by d3viant0ne** [comment]
I'll see if I can't bring this one home tonight after work

**Comment by jelbourn** [comment]
Done! thanks @d3viant0ne
