### ISSUE TITLE
Change rxjs imports in material-examples

### ISSUE THREAD

**Issue by rafaelss95** [angular/material2#8501]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
I'd expect all examples to use lettable operators.

#### What is the current behavior?
Currently most (maybe all) examples are importing rxjs using `patch` operators, like this:

`import 'rxjs/add/operator/*';`

#### Is there anything else we should know?
Not sure if you want to change this, but if you do, I can help with this.

**Comment by raunakmatai** [comment]
Help me with my code. I have too many rxjs issues.
