### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by aldari** [angular/material2#8503]
Hi,
In a page 
https://material.angular.io/components/datepicker/overview
in "Troubleshooting" subchapter
there is a broken link "Choosing a date implementation"
https://material.angular.io/#choosing-a-date-implementation-and-date-format-settings.
I think a valid address would be 
https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings.

**Comment by donroyco** [comment]
The anchor link works okay in [the markdown file](https://github.com/angular/material2/blob/master/src/lib/datepicker/datepicker.md) in this folder structure. I think when it gets compiled into the website, it causes the error anchor.
