### ISSUE TITLE
Pasting on iPad doesn't work

### ISSUE THREAD

**Issue by YePpHa** [angular/material2#8506]
#### Bug, feature request, or proposal:
Pasting in an [input field](https://material.angular.io/components/input/overview) doesn't work on an iPad.

#### What is the expected behavior?
It's supposed to input the text from the clipboard when pasting.

#### What is the current behavior?
Long pressing on an input field and pressing paste doesn't input the text from the clipboard.

#### What are the steps to reproduce?
1. Use an iPad
2. Go to https://material.angular.io/components/input/overview
3. Paste text into one of the input fields.

#### What is the use-case or motivation for changing an existing behavior?
The user should be able to copy text from somewhere and paste it into an input field using material design.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: v5.0.0
Material: v5.0.0-rc0
Typescript: v2.4.2
OS: iOS v11.1.2 (tested on iPad)
Browser: Safari and Chrome

#### Is there anything else we should know?
I've tested this on an Android phone and that works.

**Comment by donroyco** [comment]
What iOS version are you using?

**Comment by YePpHa** [comment]
It's iOS 11.1.2.

**Comment by donroyco** [comment]
@YePpHa It's working fine for me, same iOS version and tested in Safari and Chrome. Have you tried rebooting the device?

**Comment by YePpHa** [comment]
I will try that.

**Comment by YePpHa** [comment]
I will close this issue. It seems to not be an issue with this library, but something completely different. The pasting is broken on both Safari and Chrome for all input fields and not only the material input fields.

Thank you for your help and sorry for taking up your time regarding this.
