### ISSUE TITLE
mat-tab reorder

### ISSUE THREAD

**Issue by Wykks** [angular/material2#8508]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Tab reordering, just like tabs in chrome dev tool for example.

#### What is the current behavior?
No options for tab reordering

**Comment by jelbourn** [comment]
You could accomplish this today by using `ngFor` on the tabs and projecting the content into them with something like `ngTempateOutlet` or `cdkPortalOutlet`

**Comment by Wykks** [comment]
HUmm not sure how I can handle a proper drag and drop like that. I'll try :+1:

**Comment by mbeckenbach** [comment]
@Wykks 
Need to implement the same. Did you find any solution?

**Comment by Wykks** [comment]
Ended up doing my own tab implementation, because I needed more than just tab reorder :/

**Comment by jelbourn** [comment]
Closing this into #13572

**Comment by andreElrico** [comment]
@jelbourn 

> You could accomplish this today by using `ngFor` on the tabs and projecting the content into them with something like `ngTempateOutlet` or `cdkPortalOutlet`

@jelbourn could you further elaborate on this? Not sure how to construct a solution with your suggestion.
