### ISSUE TITLE
Chip input placeholder issue with async chips update

### ISSUE THREAD

**Issue by merobal** [angular/material2#8509]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Refresh the state (including placeholder) automatically on async chips update.

#### What is the current behavior?
The placeholder remains there if chips are updated async and `floatPlaceholder` is set to `"never"`. (State refreshes and placeholder disappears when I click inside input.)

#### What are the steps to reproduce?
https://plnkr.co/edit/WHW38I60XQkeo6Bl9KA2?p=preview
![image](https://user-images.githubusercontent.com/5844511/32948422-7949ccf8-cb9f-11e7-8ede-e897ff44d9da.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest on Plunker.

#### Is there anything else we should know?
Maybe related: #8448

**Comment by jelbourn** [comment]
@tinayuangao is this the same as #8448? If so, feel free to close

**Comment by merobal** [comment]
I marked that as related since it's about placeholder too, there is missing stateChange on ngOnChange I guess in this case.

**Comment by merobal** [comment]
@jelbourn @tinayuangao I can confirm it's still an issue:
https://plnkr.co/edit/rV9QEHQCOJYxTE6ddZ3y?p=preview

Possible fix:
https://plnkr.co/edit/s94OWYX9lIawldaUBwk1?p=preview

(Add $mat-chip-input-margin for the placeholder label when `floatPlaceholder` is set to `"never"`)

**Comment by merobal** [comment]
@jelbourn @tinayuangao I can confirm it's still an issue with rc.1:
https://plnkr.co/edit/WHW38I60XQkeo6Bl9KA2?p=preview

Possible fix:
Add stateChange on ngOnChange

**Comment by merobal** [comment]
@tinayuangao Will https://github.com/angular/material2/pull/9762 solve this issue?
