### ISSUE TITLE
DOMException error thrown when emulating a mobile device and using backspace to clear values from a number form input element

### ISSUE THREAD

**Issue by jbhue** [angular/material2#8516]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

While emulating a mobile device using chrome devtools. When I press backspace to erase the value of a number input element I shouldn't see any errors.

#### What is the current behavior?

While emulating a mobile device using chrome devtools. When I press backspace to erase the value of a number input element the following error is thrown: 

> ERROR DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

#### What are the steps to reproduce?

StackBlitz : [https://stackblitz.com/edit/angular-qgq6gk](https://stackblitz.com/edit/angular-qgq6gk)

1. Go to the [StackBlitz app url](https://angular-qgq6gk.stackblitz.io)
1. Use chrome devtools to emulate an iPad or iPhone
1. Refresh the page
1. Click into the number form input and press backspace 3 times
1. Look at the console of chrome to see error.
1. Notice it does not happen for text form input

#### What is the use-case or motivation for changing an existing behavior?

This error does not seem to be stoping the form from functioning but it's something I could see stuffing up any sort of error tracker applications may be running. I also just want to clearly document that this happens.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

* Angular: 5.0.0
* Angular Material: 5.0.0-rc0
* Angular CDK: 5.0.0-rc0

#### Is there anything else we should know?

I can only confirm that this error is thrown on a desktop emulating a mobile device pressing the backspace button. It may be possible that upon testing this on a real mobile device no error is thrown but I personally can't test that right now.

This obviously isn't a huge deal but I did want to bring it up / document it happening. I did notice one closed issue related to this occurrence: https://github.com/angular/material2/issues/7511

**Comment by josephperrott** [comment]
Closing as working as expected.

This is occuring because when emulating an iOS device using the chrome devtools, the user agent string is modified.  This modification only occurs when the device is detected as iOS, but since desktop chrome does not actually have the issue, the workaround throws an error as it only is expected to run on iOS devices.

The workaround can be seen [here](https://github.com/angular/material2/blob/master/src/lib/input/input.ts#L178)

**Comment by jbhue** [comment]
thanks @josephperrott. This is a similar response to what I assumed. I'll ignore the issue while i'm testing with full confidence it won't fire on an actual device.
