### ISSUE TITLE
Sourcemap paths are incorrect

### ISSUE THREAD

**Issue by DerekTBrown** [angular/material2#852]
#### Bug, feature request, or proposal:

Bug
#### What is the current behavior?

@jelbourn in publishing the latest version to npm, it seems you left your own project path in the javascript map files.  Consider the following excerpt downloaded directly from npm:

node_modules/@angular2-material/button/button.spec.js.map:

```
{"version":3,"file":"button.spec.js","sourceRoot":"","sources":["../../Users/jelbourn/material2/tmp/broccoli_type_script_compiler-input_base_path-ln
```

**Comment by jelbourn** [comment]
@hansl we fixed this once before but it seems like it's happening again.

**Comment by M-a-c** [comment]
@hansl you can probably close this issue. Milestone completed. This does not exist anymore when looking in the npm package.

**Comment by jelbourn** [comment]
Still a convenient issue to track that we don't have an source maps in the latest release.
