### ISSUE TITLE
<md-input> does not set template reference variable on <input/> element.

### ISSUE THREAD

**Issue by robkuijpers** [angular/material2#853]
When I add a template reference variable (using # or ref- on an md-input it is not set on the  <input/> element.

I followed the Angular2 forms tutorial https://angular.io/docs/ts/latest/guide/forms.html and noticed this when trying to add the #spy variable.

Is there a way to use template reference variables or is this planned for a future version?

@angular 2.0.0-rc.4
@angular/forms 0.2.0
@angular2-material 2.0.0-alpha.6

node 5.11.1
npm 3.8.6
tsc 1.8.10
OSX 10.11.5
Chrome 51.0.2704.103

**Comment by Dona278** [comment]
I tested a simple code like:

```
<md-input #test placeholder="First name"></md-input>   
{{ test.characterCount }} 
```
and this is the result:

![image](https://cloud.githubusercontent.com/assets/10567243/16854425/1a4afa26-4a11-11e6-8a0f-ab076b86d1f0.png)

How you use the #spy var?

**Comment by jelbourn** [comment]
Not presently, though the md-input should expose all APIs you would need. Working as intended for now.

**Comment by kuijpersr** [comment]
Hi Dona278,

Your example works, thanks.

I followed the Angular2 forms tutorial https://angular.io/docs/ts/latest/guide/forms.html trying to add the #spy variable to show the angular validation classes.

**Comment by amlock** [comment]
not working for me i had to switch to bootstrap style instead
