### ISSUE TITLE
cdk-overlay.umd : wrong rxjs_operators_first factory parameter

### ISSUE THREAD

**Issue by uparlange** [angular/material2#8530]
#### Bug, feature request, or proposal:

ERROR TypeError: rxjs_operators_first.first is not a function
at OverlayRef.attach (overlay.es5.js:557)
at t._attachDialogContainer (material.umd.min.js:11)
at t.open (material.umd.min.js:11)
at DetailView._openPopup (DetailView.js:54)
at DetailView.openRomsPopup (DetailView.js:29)
at Object.eval [as handleEvent] (DetailView.ngfactory.js:305)
at Object.handleEvent (core.umd.min.js:118)
at Object.handleEvent (core.umd.min.js:118)
at dispatchEvent (core.umd.min.js:69)
at core.umd.min.js:76

#### What is the expected behavior?

No error at runtime.
--> rxjs_operators_first parameter should be "Rx.operators" and not "Rx.Observable"

#### What is the current behavior?

Error at runtime.
--> Meanwhile to fix add this before script : "Rx.Observable.first = Rx.operators.first"

#### What are the steps to reproduce?

https://plnkr.co/edit/wQM0qLUUJX2tmtklcGXg

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

es5 integration
Angular 5+
Material 5.0.0-rc0
Rxjs 5.5.2
All browsers

#### Is there anything else we should know?

Correction is simple (node_modules\@angular\cdk\bundles\cdk-overlay.umd.js) !

(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@angular/core'), require('@angular/cdk/scrolling'), require('@angular/cdk/bidi'), require('@angular/cdk/portal'), require('rxjs/Subject'), require('rxjs/operators/first'), require('rxjs/Subscription'), require('rxjs/operators/filter'), require('rxjs/observable/fromEvent'), require('@angular/cdk/coercion'), require('@angular/cdk/keycodes')) :
	typeof define === 'function' && define.amd ? define(['exports', '@angular/core', '@angular/cdk/scrolling', '@angular/cdk/bidi', '@angular/cdk/portal', 'rxjs/Subject', 'rxjs/operators/first', 'rxjs/Subscription', 'rxjs/operators/filter', 'rxjs/observable/fromEvent', '@angular/cdk/coercion', '@angular/cdk/keycodes'], factory) :
	(factory((global.ng = global.ng || {}, global.ng.cdk = global.ng.cdk || {}, global.ng.cdk.overlay = global.ng.cdk.overlay || {}),
		global.ng.core,
		global.ng.cdk.scrolling,
		global.ng.cdk.bidi,
		global.ng.cdk.portal,
		global.Rx,
		**global.Rx.Observable (change to global.Rx.operators)**,
		global.Rx,
		global.Rx.Observable,
		global.Rx.Observable,
		global.ng.cdk.coercion,
		global.ng.cdk.keycodes));
}(this, (function (exports,
		_angular_core,
		_angular_cdk_scrolling,
		_angular_cdk_bidi,
		_angular_cdk_portal,
		rxjs_Subject,
		**rxjs_operators_first**,
		rxjs_Subscription,
		rxjs_operators_filter,
		rxjs_observable_fromEvent,
		_angular_cdk_coercion,
		_angular_cdk_keycodes) { 'use strict';

**Comment by uparlange** [comment]
Related bugs to reopen : #8528 #8527

**Comment by DevVersion** [comment]
@uparlange Thanks for your report. All your other issues (#8528 #8527) will be resolved by #8572 too.
