### ISSUE TITLE
feat(mat-error): provide method for programmatically adding errors

### ISSUE THREAD

**Issue by Toxicable** [angular/material2#8538]
#### What is the expected behavior?
There should be a way to programmatically give a form-field mat-error 's

#### What is the current behavior?
There is no way to do so

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-wpvavh?file=app/app.component.ts

#### What is the use-case or motivation for changing an existing behavior?
In all examples `mat-error` is used like 
```
<mat-error *ngIf="emailFormControl.hasError('pattern')">
      Please enter a valid email address
    </mat-error>
```
This is a lot of code to write and a lot of duplication, especially if you want to use the same error more than once, which is very common

You should be able to defined error messages in one place and pipe them into the UI with `mat-error`

**Comment by jelbourn** [comment]
Is there something that blocks using `mat-error` with `ngFor`?

**Comment by Toxicable** [comment]
Nah you totally can do 
```
    <mat-form-field>
      <input matInput placeholder="Enter your email" [formControl]="email" required>
      <mat-error *ngFor="let error of [1, 2, 3]">{{error}}</mat-error>    
    </mat-form-field>
```
And that will work as expected, but you cant do the same thing from another container/component as in the example I gave.

by extention you could have a FormErrorService which you inject in as a public variable in your component then do:
```
    <mat-form-field>
      <input matInput placeholder="Enter your email" formControlName="email" required>
      <mat-error *ngFor="let error of errorService.mapErrors(form.get('email'))">{{error}}</mat-error>    
    </mat-form-field>
```
But that might slow down CD on large amount of forms since there's no ref to track the array by.

If I'm missing something that might avoid this then im sure that would be a preferred way

**Comment by Toxicable** [comment]
On second thought maybe I'm totally prematurely optimizing this.
If anyone else is looking for a similar situation here's the little service I whipped up
https://stackblitz.com/edit/angular-form-control-errors?file=app/app.component.ts

```
@Injectable()
export class FormErrorService {
  errorMap: { [key: string]: (c: FormControl, name: string) => string } = {
    'required': (c: FormControl, name: string) => `${name} is required`,
    'email': (c: FormControl, name: string) => `${c.value} is not a valid email`,
    'max': (c: FormControl, name: string) => `${name} must be equal to or less than ${c.errors['max']['max']}`,
  }

  mapErrors(control: FormControl, name: string): string[] {
    return Object.keys(control.errors || {})
      .map(key => this.errorMap[key](control, name));
  }
}
```
