### ISSUE TITLE
Outdated soucecodes to actual sourcecodes in Angular documentation

### ISSUE THREAD

**Issue by isybai** [angular/material2#8549]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Actual sourcecodes in Angular Material documentation https://material.angular.io/components/

#### What is the current behavior?
Outdated sourcecodes

#### What are the steps to reproduce?
Replace md to mat

#### What is the use-case or motivation for changing an existing behavior?
It confuses angular beginners

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest Angular Material

#### Is there anything else we should know?
no

**Comment by donroyco** [comment]
Did you clear your cache?

**Comment by jelbourn** [comment]
See #8497

Visit chrome://serviceworker-internals/ and unregister the worker for material.angular.io
