### ISSUE TITLE
Cannot access dialog (MatDialog) parent component properties

### ISSUE THREAD

**Issue by boazrymland** [angular/material2#8552]
#### Bug, feature request, or proposal:

**BUG**:

```typescript
const deleteSuiteDialogRef: MatDialogRef<SuiteDeleteConfirmationDialogComponent> =
      this.dialog.open(SuiteDeleteConfirmationDialogComponent);
    deleteSuiteDialogRef.afterClosed().subscribe((confirmed) => {
      // here, 'this' is the parent component (where this code is written) and I 
      // should be able to do this.someProp to get a parent property's value 
      // but I get undefined. Access to this.someMethod() *is* possible.
    }
);
```

#### What is the expected behavior?
I should be able to access parent component properties, just like I *am* able to access its method (which works).

#### What is the current behavior?
Any parent component property is 'undefined'. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0, Material Design at 5.0.0-rc0

#### Is there anything else we should know?
The property I tried to access is data bound @Input() into the parent component and it has a 'setter' method. Its initialization works and aside from this bug everything works as expected (it gets its value as this value is used through the parent component's template). Trying to access it or another 'regular'  property (that doesn't have a setter - normal internal property that is not bound at all) is not possible, as described above. Yet, as a work around I created a 'getter' method and was able to access it. But, this needs to be fixed nevertheless.

**Comment by jelbourn** [comment]
It sounds like your property is just undefined; this isn't anything related to Angular Material, it's just javascript semantics

**Comment by boazrymland** [comment]
But the property I'm referring to **is** defined, like I mentioned, with a 'setter' method. Here's the actual code, with more code for better context:

```typescript
export class MyComponent {
 // ...
@Input()
  set suiteInContext(val: Suite) {
    //... setter method code
  }
}
  // ...
handleSaveAs() {
  // ...
  const deleteSuiteDialogRef: MatDialogRef<SuiteDeleteConfirmationDialogComponent> =
      this.dialog.open(SuiteDeleteConfirmationDialogComponent);
    deleteSuiteDialogRef.afterClosed().subscribe((confirmed) => {
      if (confirmed) {
      // ...
      // HERE I REFERENCE this.suiteInContext AND IT DOESN'T WORK
      console.log(this.suiteInContext)
      // the above line doesn't work...
```

The above property - _suiteInContext_ is the data bound property of the component I'm trying to access in the anon function. I cannot get the 'this' object properties at all, unless I factor a 'getter' for them. Strangely, I _can_ access 'this' methods.
So its not a matter of a property that is not defined... .

I hope the above is clearer. Maybe its a PEBCAK case - I'll be happy to know...

**Comment by ncrawlins** [comment]
@jelbourn @boazrymland did you ever get a fix for this?  the "this" context when you subscribe to the afterClosed event is wrong.  instead of being the context of the component that subscribed, it's some safe subscriber.  This is not an issue with him simply not creating a variable.  When you say dialogref.afterClosed().subscribe(foo)

foo() {
  this.variable // THIS is not the component THIS as you would expect.
}
