### ISSUE TITLE
Unable to get selectonChange event fired on mat-list-option under mat-selection-list

### ISSUE THREAD

**Issue by tarunnav** [angular/material2#8555]
#### Bug, feature request, or proposal:

option check/uncheck should fire selectionChange event on mat-list-option under mat-selection-list
#### What is the expected behavior?
option check/uncheck should fire selectionChange event on mat-list-option under mat-selection-list

#### What is the current behavior?
option check/uncheck does not fire selectionChange event on mat-list-option under mat-selection-list

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
  "@angular/material": "^2.0.0-beta.12",
 "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
"@angular/cdk": "^2.0.0-beta.12",
"typescript": "~2.3.3",

chrome browser

**Comment by DevVersion** [comment]
Will be fixed by #7456

**Comment by lanzosuarez** [comment]
Is the latest version is 5.0.0? Still not working in 5.0.0
