### ISSUE TITLE
docs: Mat-optgroup

### ISSUE THREAD

**Issue by alex321** [angular/material2#8557]
#### Feature request:
Could we document the `mat-optgroup` inside `mat-select` (possibly autocomplete as well)?

#### What is the current behavior?
You have to know that it exists in order to use it.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material - 5.0.0-rc.0

**Comment by willshowell** [comment]
It is currently available in the [docs](https://material.angular.io/components/select/overview#creating-groups-of-options). If you don't see it, try hard reloading.

**Comment by alex321** [comment]
@willshowell It is indeed! Is the caching a problem on my side (using latest Chrome for Mac)?
