### ISSUE TITLE
extra 'span' element added in mat-option of autocomplete makes impossible to style the internals

### ISSUE THREAD

**Issue by xagon** [angular/material2#8561]
#### Bug, feature request, or proposal:
I would consider it a bug unless told otherwise.

#### What is the expected behavior?
Extra ```span``` element is not added, in my opinion - not needed.

#### What is the current behavior?
Additional element is added to the form, making it impossible to style the internals.
![image](https://user-images.githubusercontent.com/20299573/33041628-454c1e40-ce3f-11e7-9452-2bb950322fe5.png)

#### What are the steps to reproduce?

1. http://plnkr.co/edit/dKYBn6NFpMbknwKbVfgP?p=preview
2. hit F12
3. hoover over the ```mat-option```

#### What is the use-case or motivation for changing an existing behavior?
styling of the internals is very hard becuase of the extra span which is added

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0-rc0-40d6bcb
the rest as per plunk example

#### Is there anything else we should know?
Nope, that's it.

**Comment by crisbeto** [comment]
That span is there to collapse some whitespace, as well as truncate long labels (once https://github.com/angular/material2/pull/7857 gets in). Note that the text isn't the only content that can be put inside an option, there's also a checkbox that will be shown if the select is in `multiple` mode.

**Comment by jelbourn** [comment]
Closing as "working as intended". You can always target descendants with css

**Comment by xagon** [comment]
yep, understood.
cheers guys!

**Comment by prashantpimpale93** [comment]
@jelbourn I need the option text to appear to the next line after the text overflow from the min-width. 

What I did:

```
.mat-autocomplete-panel mat-option.mat-option {
  height: unset;
}

.mat-option-text.mat-option-text {
  white-space: normal;
}
```

But not working!

Can you suggest something?
