### ISSUE TITLE
Can't bind to 'shouldPlaceholderFloat' since it isn't a known property of 'mat-form-field'

### ISSUE THREAD

**Issue by chriskinzel** [angular/material2#8566]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Using shouldPlaceholderFloat should work

#### What is the current behavior?
Trying to use shouldPlaceholderFloat causes crash

#### What are the steps to reproduce?
https://embed.plnkr.co/hAZ8DQW1n7j4vnIUphAi/

All relevant code is in input-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All / latest

**Comment by jelbourn** [comment]
`shouldPlaceholderFloat` is actually a property of the control (either `matInput` or `mat-select`), and not the form-field.

**Comment by chriskinzel** [comment]
Still doesn't work https://plnkr.co/edit/O9GZPM50vjGWdpgdrftM?p=preview

**Comment by ewaschen** [comment]
@jelbourn The [Form Field](https://material.angular.io/components/form-field/overview#floating-placeholder) docs uses `floatPlaceholder` while the [Input API](https://material.angular.io/components/input/api) doc uses `shouldPlaceholderFloat` so I'm a little confused on which one is correct.  I tried both and neither work. I'm still using `2.0.0-beta.11` as upgrading to `5.0.0` caused some errors, not sure if that matters.

**Comment by chriskinzel** [comment]
I managed to get it to work if you put ```floatPlaceholder``` on the form field and set it to one of 'always', 'auto', or 'never' it will work, doing the same with matInput does not work and either way the docs are incorrect and contradictory, I was only able to find this solution after looking at the floating placeholder plunkr.

**Comment by finalxcode** [comment]
@chriskinzel https://material.angular.io/components/form-field/overview#floating-placeholder

**Comment by chriskinzel** [comment]
@finalxcode the docs are correct for the form field but it's confusing if you're reading the mat-input API https://material.angular.io/components/input/api because shouldPlaceholderFloat is listed as an input of mat-input.
