### ISSUE TITLE
mat-expansion-panel example (Self aware panel) on material.angular.io doesn't work 

### ISSUE THREAD

**Issue by sumitgouthaman** [angular/material2#8567]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Self aware panel example should show "Currently I am open" when expanded

#### What is the current behavior?
Self aware panel example shows "Currently I am closed" when expanded.

![ang_mat_expansion_bug](https://user-images.githubusercontent.com/934190/33047821-9c963bbe-ce0c-11e7-85e5-7b134e050236.png)

#### What are the steps to reproduce?
Visit https://material.angular.io/components/expansion/overview and interact with "Self aware panel" example.

**Comment by mandarini** [comment]
Checked it on chrome and on firefox and it works (on my computer and my android), so I cannot reproduce the issue. Does it persist?

![angularmaterial](https://user-images.githubusercontent.com/6603745/33079476-5a994a1c-cede-11e7-8f7b-5b68c8ef4236.png)

**Comment by bardiel** [comment]
It may be the classic cache issue with the service worker. Try unregistering the service worker as explaind here https://github.com/angular/material2/issues/8497#issuecomment-345311757 , refresh and try again.

**Comment by sumitgouthaman** [comment]
Yeah, it works after unregistering the service worker.

**Comment by willshowell** [comment]
@sumitgouthaman can you close if you're no longer seeing the issue?
