### ISSUE TITLE
Fixed toolbar

### ISSUE THREAD

**Issue by cmsdesigner** [angular/material2#8576]
#### Bug, feature request, or proposal:
Is there any way to fixe a mat-toolbar on the top 

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by andrewseguin** [comment]
Please refer all troubleshooting questions to our community at StackOverflow, Angular Material mailing lists, Gitter, etc. We try to keep our issues here only open for bugs and feature requests.
