### ISSUE TITLE
Update dialog examples in docs to 'Mat' prefix

### ISSUE THREAD

**Issue by danielhdz56** [angular/material2#8582]
#### Bug, feature request, or proposal:
request

#### What is the expected behavior?
Md prefixes need to be changed to Mat prefixes

#### What is the current behavior?
the current behavior is outdated as it uses previous versions of Material

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Docs need to be aligned with current version of material.

**Comment by Chan4077** [comment]
Have you tried clearing the cache? See https://github.com/angular/material2/issues/7715#issuecomment-335835631 for more information.

**Comment by crisbeto** [comment]
The docs are all up to date, you're probably getting a cached version.
