### ISSUE TITLE
Keep updated npm dist-tags

### ISSUE THREAD

**Issue by ocarreterom** [angular/material2#8585]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Keep updated npm dist-tags.
Currently would be:
```json
{
  "dist-tags": {
    "experimental": "5.0.0-rc.1",
    "latest": "5.0.0-rc.1",
    "next": "5.0.0-rc.1"
  }
}
```

#### What is the current behavior?
```json
{
  "dist-tags": {
    "experimental": "2.0.0-alpha.11-2",
    "latest": "5.0.0-rc.1",
    "next": "5.0.0-rc0"
  }
}
```
Running `npm update`, 5.0.0-rc0 is installed instead of 5.0.0-rc.1.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 5.0.0-rc.1

**Comment by jelbourn** [comment]
Deleted the `next` and `experimental` tags
