### ISSUE TITLE
mat-expansion-panel-header expand/collapse animation jumps on non default header sizes

### ISSUE THREAD

**Issue by efsinua** [angular/material2#8592]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Smooth animation transition of \<mat-expansion-panel-header\> on expand/collapse if header height is not default.

#### What is the current behavior?
When \<mat-expansion-panel-header\> height is changed with styling, animation jumps on expand/collapse to hard coded sizes at expansionHeight animation trigger to collapsedHeight: 48px or expandedHeight: 64px instead of smooth transition

#### What are the steps to reproduce?
http://plnkr.co/edit/zIEeYb?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Possibility to override default \<mat-expansion-panel-header\> height

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all including Angular Material 5.0.0-rc.1 

#### Is there anything else we should know?
if replace values at expansion-panel-header.ts at animations trigger('expansionHeight',...)
collapsedHeight: '48px' to collapsedHeight: '\*'
expandedHeight: '64px' to  expandedHeight: '\*'

expand/collapse animation will work smoothly

**Comment by amouly** [comment]
Verified, we have te same problem when changing the height of the header.

**Comment by atluriajith** [comment]
Any update on this? [#5641](https://github.com/angular/material2/issues/5641) stating that to height and width as a attributes but can we handle this from CSS?.

**Comment by josephperrott** [comment]
This is actually working as expected.

If the collapsedHeight and expandedHeight are left to default, they will be [`48px` and `64px` respectively](https://github.com/angular/material2/blob/master/src/lib/expansion/expansion-animations.ts#L38).  To define the height via css, you will need to set the parameters for the animation to `*` for both.

**Comment by atluriajith** [comment]
@josephperrott  Thanks for the update  :thumbsup:

**Comment by josephperrott** [comment]
Closed by #9313

**Comment by omryha** [comment]
I,

I am having this problem, using latest version of Material (6.3.3).
I'm defining a custom width and height for the header:

`<mat-expansion-panel-header [collapsedHeight]="'85px'" [expandedHeight]="expandedHeight">`
("expandedHeight" is a variable that is changing by TS code).

I didn't get the solution for this problem from this post, I'd be happy if someone could help me with this. 

Thanks.

**Comment by elrabelo** [comment]
@josephperrott I tried to do this, but it's not working yet. See this example: https://stackblitz.com/edit/angular-p6rpru. The animation occurs when the page loads.

**Comment by arjentuin** [comment]
line-height: 0;
Did the trick for me on class mat-expansion-indicator
