### ISSUE TITLE
Input field not accepts characters if maxLenght is applied

### ISSUE THREAD

**Issue by wermerb** [angular/material2#8593]
#### Bug, feature request, or proposal:

I'm submitting a bug.

#### What is the expected behavior?
It should accept characters till the max length is reached. 

#### What is the current behavior?
Input field not accepts any character if max lenght is applied

#### What are the steps to reproduce?
```
<form [formGroup]="form">
    <mat-input-container>
        <input matInput formControlName="payload" [maxLength]="maxlength">
    </mat-input-container>
</form>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 1.5.0
Node: 6.12.0
OS: linux x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

**Comment by donroyco** [comment]
It is working in this example I created: https://angular-2jk2wi.stackblitz.io

**Comment by wermerb** [comment]
Hi @donroyco,

Thank you for the response, unfortunately i cannot load the link above due to some errors on load.

**Comment by donroyco** [comment]
@wermerb Even with the errors, the input field should be there (no styling though).

![screen shot 2017-11-22 at 19 31 54](https://user-images.githubusercontent.com/1763537/33143969-dc9cda8c-cfbb-11e7-9445-d5c78ab48899.png)

**Comment by wermerb** [comment]
@donroyco Sorry i did not see the input field. Are you providing the max length from the component via a variable?

**Comment by donroyco** [comment]
@wermerb Yes, see the editable version: https://stackblitz.com/edit/angular-2jk2wi?file=app%2Fapp.component.ts

**Comment by wermerb** [comment]
@donroyco I recreated on Stackblitz: https://stackblitz.com/edit/angular-zxokfj as you can see its not working.

**Comment by donroyco** [comment]
@wermerb Your version has no saved changes.

**Comment by wermerb** [comment]
@donroyco Sorry about that check out now.

**Comment by donroyco** [comment]
You're missing this typo: `[maxLength]="maxlength"` » `[maxLength]="maxLength"` (uppercase 'l')

**Comment by wermerb** [comment]
@donroyco Indeed thank you, sorry about the false alarm :)

**Comment by rupeshs123** [comment]
for the number type it's not working,

**Comment by donroyco** [comment]
@rupeshs123 It's so by design of HTML. This has nothing to do with Angular / Material2. 

**[maxlength](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-maxlength)**
> If the value of the type attribute is `text`, `email`, `search`, `password`, `tel`, or `url`, this attribute specifies the maximum number of characters (in UTF-16 code units) that the user can enter. **For other control types, it is ignored.** It can exceed the value of the size attribute. If it is not specified, the user can enter an unlimited number of characters. Specifying a negative number results in the default behavior (i.e. the user can enter an unlimited number of characters). The constraint is evaluated only when the value of the attribute has been changed.
