### ISSUE TITLE
<mat-icon> ignores color attribute if inside <button mat-menu-item>

### ISSUE THREAD

**Issue by Anonymphous** [angular/material2#8594]
#### Bug, feature request, or proposal:
It's a **bug**.

#### What is the expected behavior?
I would expect `<mat-icon color="accent">` in my menu item to respect the color attribute while it is inside of its <button mat-menu-item> parent tag.

#### What is the current behavior?
It does not apply the color, here is a screenshot with comparison between `<button mat-button>` which respects the attribute and `<button mat-menu-item>` which does not.
![image](https://user-images.githubusercontent.com/30666899/33140854-51ad2cd6-cfc2-11e7-9a68-fd5de272decd.png)

#### What are the steps to reproduce?
Here is a bit edited mat-menu plunker with the problem displayed [link](https://plnkr.co/edit/j8qKe1jY9oVt1dHU4WMT?p=preview)

#### What is the use-case or motivation for changing an existing behavior?
I think it should be repaired, since the `<mat-icon>` explicitly supports coloring with color attribute.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular v5.0.2
@angular/cdk v5.0.0-rc.1
@angular/material v5.0.0-rc.1
TypeScript v2.4.2
IE 11, Firefox 57, Chrome 62

**Comment by jelbourn** [comment]
The menu-items styles are trumping the icon styles

**Comment by jonyadamit** [comment]
Hi, the fix is partial, please re-open. Cannot bind color property.
See example: https://stackblitz.com/edit/mat-icon-color-menu-issue.
The example includes a workaround (adding [attr.color]="'anything'").
