### ISSUE TITLE
MatDialog not displaying correct / not as dialog

### ISSUE THREAD

**Issue by f1ssl** [angular/material2#8596]
#### Bug, feature request, or proposal:
The dialog is displayed "under" the button, not above or over it. 

#### What is the expected behavior?
Dialog "over" the button.

#### What is the current behavior?
Dialog under the button

![image](https://user-images.githubusercontent.com/20832194/33143917-a84e858c-cfbb-11e7-9d0b-8b1d7b62c3bb.png)

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
