### ISSUE TITLE
mat-dialog closes and refresh main page when using animations on divs inside dialog

### ISSUE THREAD

**Issue by Mayocampo** [angular/material2#8597]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Manage all kind of animatiosn inside a mat-dialog

#### What is the current behavior?
when you have more than two elements inside a mat-dialog, lets say 3 divs, each one with different animations to show one div and hide another (very normal behaviour), somehow, the third div isn't working well, cause animation collapases, closes mat-dialog and refresh main container. Divs only has a button inside of it

#### What are the steps to reproduce?
create main component.
invoke mat-dialog with 3 divs on it
add simple, different animation on each div through:

@Component({
  ...
  animations: [
    trigger('sliderInOut', [
      transition('void => *', [
        animate(500, style({ transform: 'translateY(-100%)' }))
      ]),
      transition('* => void', [
        animate(500, style({ transform: 'translateY(-100%)' }))
      ])
    ]),
trigger('another animation', etc..

add ngIf on each div one true, the others false.
add buttons to navigate between divs

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.4.9
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4

**Comment by jelbourn** [comment]
@Mayocampo can you provide a StackBlitz reproduction?

**Comment by anisabboud** [comment]
I encountered a potentially related issue https://github.com/angular/material2/issues/9298. Thanks!

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
