### ISSUE TITLE
Error UNMET PEER DEPENDENCY during install by npm

### ISSUE THREAD

**Issue by fraoustin** [angular/material2#8598]
#### Bug, feature request, or proposal:

Error during install of material by npm

#### What is the expected behavior?

no UNMET PEER DEPENDENCY  during install

#### What is the current behavior?

I have error

> ├── UNMET PEER DEPENDENCY @angular/compiler@5.0.2
> ├── UNMET PEER DEPENDENCY @angular/core@5.0.2

#### What are the steps to reproduce?

> npm update -g @angular/cli
> ng new myappli
> cd myappli
> npm install --save @angular/material @angular/cdk
> 
> myappli@0.0.0 /home/fraoustin/Téléchargements/test/myappli
> ├── @angular/cdk@5.0.0-rc.1 
> ├── UNMET PEER DEPENDENCY @angular/compiler@5.0.2
> ├── UNMET PEER DEPENDENCY @angular/core@5.0.2
> └── @angular/material@5.0.0-rc.1 
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN codelyzer@3.2.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.
> npm WARN codelyzer@3.2.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
my package.json is

> {
>   "name": "myappli",
>   "version": "0.0.0",
>   "license": "MIT",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build",
>     "test": "ng test",
>     "lint": "ng lint",
>     "e2e": "ng e2e"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "^5.0.0",
>     "@angular/cdk": "^5.0.0-rc.1",
>     "@angular/common": "^5.0.0",
>     "@angular/compiler": "^5.0.0",
>     "@angular/core": "^5.0.0",
>     "@angular/forms": "^5.0.0",
>     "@angular/http": "^5.0.0",
>     "@angular/material": "^5.0.0-rc.1",
>     "@angular/platform-browser": "^5.0.0",
>     "@angular/platform-browser-dynamic": "^5.0.0",
>     "@angular/router": "^5.0.0",
>     "core-js": "^2.4.1",
>     "rxjs": "^5.5.2",
>     "zone.js": "^0.8.14"
>   },
>   "devDependencies": {
>     "@angular/cli": "1.5.3",
>     "@angular/compiler-cli": "^5.0.0",
>     "@angular/language-service": "^5.0.0",
>     "@types/jasmine": "~2.5.53",
>     "@types/jasminewd2": "~2.0.2",
>     "@types/node": "~6.0.60",
>     "codelyzer": "~3.2.0",
>     "jasmine-core": "~2.6.2",
>     "jasmine-spec-reporter": "~4.1.0",
>     "karma": "~1.7.0",
>     "karma-chrome-launcher": "~2.1.1",
>     "karma-cli": "~1.0.1",
>     "karma-coverage-istanbul-reporter": "^1.2.1",
>     "karma-jasmine": "~1.1.0",
>     "karma-jasmine-html-reporter": "^0.2.2",
>     "protractor": "~5.1.2",
>     "ts-node": "~3.2.0",
>     "tslint": "~5.7.0",
>     "typescript": "~2.4.2"
>   }
> }

**Comment by jelbourn** [comment]
[The dependencies in Angular Material are set correctly](https://unpkg.com/@angular/material@5.0.0-rc.1/package.json). Try clearing your node_modules and package-lock.json.

**Comment by fraoustin** [comment]
Thanks how do i clear my node_modules ans package-lock.json?

**Comment by mhoennig** [comment]
He meant: Just delete the directory node_modules completely and the file package-lock.json (if it exists at all).

**Comment by SatishChandraPalakoti** [comment]
did that work ? It still is troubling me.. need help.. :/

**Comment by zachowdhury** [comment]
@mhoennig 's solution worked for me  
node_modules deleted and npm install --save
