### ISSUE TITLE
MatDialog does not display content in FF, Chrome, Opera

### ISSUE THREAD

**Issue by AbakumovAlexandr** [angular/material2#8601]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
`MatDialog` should show content in any browser.

#### What is the current behavior?
`MatDialog` does NOT display content in FF, Chrome, Opera, but display it in Edge and Safari.

#### What are the steps to reproduce?
Please check out a [StackBlitz](https://stackblitz.com/edit/angular-material-dialog-no-content) in various browsers.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.2, Material 5 RC1.

**Comment by jelbourn** [comment]
You used the selector `dialog` for your content. This is being treated as a native `<dialog>` element in those browsers and is hidden unless it has the `open` attribute set. 

You should use a custom element name with a dash like `pizza-dialog` for your selector.
