### ISSUE TITLE
Autocomplete displayWith is non-intuitive

### ISSUE THREAD

**Issue by Irrelon** [angular/material2#8604]
#### Bug, feature request, or proposal:

Feature request / usability bug

#### What is the expected behavior?

Where options = [{text: 'My Field', value: 'myValue'}]

```
<mat-autocomplete #auto="matAutocomplete">
	<mat-option *ngFor="let option of options" [value]="option.value">
		{{ option.text }}
	</mat-option>
</mat-autocomplete>
```

I would expect mat-option to operate in the same way as an HTML option element in a select. KISS principal should really be applied here! When the user selects an option from the autocomplete suggestions, the internal value should === option.value while the displayed value to the user should === option.text

Why on earth do we need to declare a whole new function just to resolve option.text using displayWith attributes?

#### What is the current behavior?

Displays option.text to the user but when selected, displays the option.value in the input text box. This makes sense because we are looking at two completely different controls, a select and then a text input, however, this is poor form. Deviating from HTML standards creates yet another new way to do something that everyone already knew up to this point.

#### What is the use-case or motivation for changing an existing behavior?

Every control in material should ask the question: How am I deviating from HTML norm? Does this require a developer to write something very different from standard HTML?

Maybe I'm just "old" now... but custom attributes like displayWith are not intuitive to me and require a reading of the docs to learn. HTML options had a display value and an internal data value. Why aren't we mirroring this for material in ngx?

**Comment by jelbourn** [comment]
mat-autocomplete options can contain arbitrary content, not just text. Dumping this arbitrary content into the trigger usually isn't what people want, especially if the option contains a ligature-based icon. 

If no `displayWith` is given, the `value` is used.
