### ISSUE TITLE
Mat-Table row delete issue

### ISSUE THREAD

**Issue by jobinwilfred** [angular/material2#8605]
**Bug, feature request, or proposal:**
Bug

**What is the current behavior?**
when we delete all rows in the 2nd page index of mat-table, it automatically redirects to the 1st page index, but it will be empty.

![mat-table empty issue](https://user-images.githubusercontent.com/25928557/33162299-ddf48f72-d04e-11e7-93d7-cb4eaab5e1b2.JPG)

**Comment by willshowell** [comment]
Reproduction?

**Comment by andrewseguin** [comment]
Please open with reproduction, next time use the issue template so we can start off with a way to investigate the issue

**Comment by KamilKmitaLasoft** [comment]
same issue , some solution ?

**Comment by andrewseguin** [comment]
I'm not seeing what you are describing. I tried going to the last page, then deleting all rows on that page (number 19 and 20). It correctly went back  a page and showed items 16, 17, and 18

**Comment by franbueno** [comment]
Any solution?

**Comment by franbueno** [comment]
Ok, i updated to 7.3.4 and it works now. Thanks guys for this update! :)
