### ISSUE TITLE
There is no directive with "exportAs" set to "routerLinkActive"

### ISSUE THREAD

**Issue by govindarajkp** [angular/material2#8608]
I am using the material angular tab nav list component in my application, it's working as expected but while executing the test case throws error.

Html:
```
<nav mat-tab-nav-bar>
        <a        mat-tab-link
            *ngFor="let tab of tabs"
            [routerLink]="tab.path"
            routerLinkActive #rla="routerLinkActive"
            [active]="rla.isActive"
            selectedIndex="0" >
            <i class="{‌{tab.icon}}"></i>
            {‌{ tab.label }}
        </a>
    </nav>
```
Error Message:
 There is no directive with "exportAs" set to "routerLinkActive" ("          *ngFor="let tab of tabs"
             [routerLink]="tab.path"
             routerLinkActive [ERROR ->]#rla="routerLinkActive"
             [active]="rla.isActive"
             selectedIndex="0"

May I know why this error on only spec.

**Comment by crisbeto** [comment]
The `routerLinkActive` directive is defined in the `RouterModule`. You probably forgot to include it in your testing module, which is why it ends up throwing.

**Comment by govindarajkp** [comment]
Worked after importing RouterTestingModule  not with RouterModule.

Reference: https://stackoverflow.com/questions/45159960/angular-4-error-no-provider-for-childrenoutletcontexts-in-karma-jasmine-test
