### ISSUE TITLE
[Sort] Arrow plays animation twice

### ISSUE THREAD

**Issue by StefanKennedy** [angular/material2#8612]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-sort-header displays arrow showing direction of sort. The arrow plays an animation on changing the direction of sorting.

#### What is the current behavior?
On Firefox 57.0 (64-bit), when the sort direction arrow changes from up to down the animation plays twice instead of once.

#### What are the steps to reproduce?
The bug occurs on the demo on the angular material site https://material.angular.io/components/table/overview#sorting when running Firefox 57.0

I am using Ubuntu 16.04 64 bit

**Comment by donroyco** [comment]
GIF of the issue in Firefox 57.0 (64-bit)

![click](https://user-images.githubusercontent.com/1763537/33174016-88f5833e-d056-11e7-9dd1-e2ca699eddff.gif)

**Comment by andrewseguin** [comment]
Thanks for the gif, working now on the sort animation in another PR. Will double check that this is fixed in that PR
