### ISSUE TITLE
mat-select multiple error state works incorrectly

### ISSUE THREAD

**Issue by trsh** [angular/material2#8617]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When clicking outside select mat-select multiple, an error should shown (and error styles added) if some validator is violated. 

#### What is the current behavior?

Have-ever that happens, when you click second time outside.

#### What are the steps to reproduce?
https://material.angular.io/components/select/examples >> Select with form field features
Click to open the list, then click outside and click again outside

#### What is the use-case or motivation for changing an existing behavior?
I think it's obvious. Should work same as for inputs.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.1, material 5.0.0-rc.1, Windows, Chrome latest, typescript 2.5.2

#### Is there anything else we should know?
No

**Comment by crisbeto** [comment]
This works as expected. The validators are set up to run on blur by default. In your example focus never leaves the select until you actually click away.
