### ISSUE TITLE
bug ToolBar not working inside child Component 

### ISSUE THREAD

**Issue by Sgoswami3** [angular/material2#8620]
#### Bug, feature request, or proposal:
Bug:  mat-toolbar is not working inside child component 
#### What is the expected behavior?

toolbar should appear at the top of the page. 

#### What is the current behavior?
instead of showing tool with primary color only text is coming when using toolbar as a child component; inside the app component

#### What are the steps to reproduce?
Module.ts:
import { BrowserModule } from '@angular/platform-browser';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';

import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

import { DefectdetailsService } from './services/defectdetails.service';
import {HttpClientModule } from '@angular/common/http';
import { HeaderComponent } from './header/header.component';

import {
  MatAutocompleteModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  MatChipsModule,
  MatDatepickerModule,
  MatDialogModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatRadioModule,
  MatSelectModule,
  MatSidenavModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatSnackBarModule,
  MatSortModule,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule,
  MatTooltipModule,
  MatStepperModule,
} from '@angular/material';
import {MatNativeDateModule, MatRippleModule} from '@angular/material';
import {CdkTableModule} from '@angular/cdk/table';
import {CdkAccordionModule} from '@angular/cdk/accordion';
import {A11yModule} from '@angular/cdk/a11y';
import {BidiModule} from '@angular/cdk/bidi';
import {OverlayModule} from '@angular/cdk/overlay';
import {PlatformModule} from '@angular/cdk/platform';
import {ObserversModule} from '@angular/cdk/observers';
import {PortalModule} from '@angular/cdk/portal';

@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    HttpClientModule,
    MatAutocompleteModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatTableModule,
    MatDatepickerModule,
    MatDialogModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatSliderModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatNativeDateModule,
    CdkTableModule,
    A11yModule,
    BidiModule,
    CdkAccordionModule,
    ObserversModule,
    OverlayModule,
    PlatformModule,
    PortalModule,

  ],
  providers: [DefectdetailsService],
  bootstrap: [AppComponent]
})
export class AppModule { }

Header - component .html:

`<p>
  <mat-toolbar>
    <mat-icon>menu</mat-icon>
    <span>Default Toolbar</span>
    <mat-icon>code</mat-icon>
  </mat-toolbar>
</p>
`

App Component.html
`<app-header> </app-header>`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/animations: 5.0.3
@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1

**Comment by julianobrasil** [comment]
Could you try to reproduce it in [stackblitz.com](https://goo.gl/wwnhMV)?

**Comment by Sgoswami3** [comment]
hello Juliano, 
thanks for the reply, I think I figured out the issue .. I am using services inside the OnInit life cycle hook; and one of the services was not working so my app was crashing; i fixed that issue and now I can see the Toolbar rendering as expected. 
apologies for the trouble; close this issue now.
rgds,
Sudeep
