### ISSUE TITLE
[Pagination] Example passes string for pageSize, breaking getRangeLabel

### ISSUE THREAD

**Issue by tom10271** [angular/material2#8624]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I set page size to 1 then go to next page, it should changes from `1 - 1 of 100` to `2 - 2 of 100`. Then next page again it should be `3-3 of 100`

When I set page size to 2 then go to next page, it should changes from `1 - 2 of 100` to `3 - 4 of 100`. Then next page again it should be `5-6 of 100`

#### What is the current behavior?
![angular material io pagination of data table bug](https://user-images.githubusercontent.com/5089629/33192930-dfe94492-d0ff-11e7-8256-097cc2c458e9.gif)

When I set page size to 1 then go to next page, it changes from `1 - 1 of 100` to `2 - 20 of 100`. Then next page again it should be `3-30 of 100`

When I set page size to 2 then go to next page, it changes from `1 - 2 of 100` to `3 - 22 of 100`. Then next page again it should be `5-42 of 100`

#### What are the steps to reproduce?
https://material.angular.io/components/paginator/examples

#### What is the use-case or motivation for changing an existing behavior?
I am just trying to test it for the first time

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.3
Angular Material  5.0.0-rc.1

#### Is there anything else we should know?
Plunkr example is not working too(In most of the time for other examples too actually)
https://github.com/angular/material.angular.io/issues/334

**Comment by andrewseguin** [comment]
The example takes the form field's value for the page size and passes it to the `MatPaginator`. However, it's being passed as a string, which is fine for all the operations the paginator does (e.g. multiply page size by page index) but `getRangeLabel` does `startIndex + pageSize` which coerces to a string rather than uses the size as a number.

Will need to fix this by using `coerceNumberProperty`

**Comment by mhosman** [comment]
This fix is available in last build? I have the same error with the last version.
