### ISSUE TITLE
Sidenav's `position` doesn't work, but `align is deprecated. 

### ISSUE THREAD

**Issue by rachelmyers** [angular/material2#8629]
#### Bug: New sidenav position implementation doesn't work.
Trying to follow what's [documented](https://material.angular.io/components/sidenav/api) as the right thing to use, I tried to use `position`, like so:
```
<mat-sidenav mode="side" posiiton="end" >
  Cool Content
</mat-sidenav>
```
But, tragically, it had no effect. Then I tried the `align` property, even thought it's deprecated, and that worked perfectly:
```
<mat-sidenav mode="side" align="end" >
  Cool Content
</mat-sidenav>
```

#### What is the expected behavior?

I see either two fixes for this: to either change the documentation or the implementation, but to make sure they match.

P.S. I understand if you close this or mark it as a `won't fix` but I want to raise that inaccurate documentation is an unnecessary blocker for folks.

**Comment by crisbeto** [comment]
It works against our demo app and in the unit tests @rachelmyers. It seems like you have a typo in your attribute name: `posiiton="end` -> `position="end"`.
