### ISSUE TITLE
titlecase pipe on words with accent marks (like french)

### ISSUE THREAD

**Issue by Korouzan** [angular/material2#8632]
#### Bug, feature request, or proposal:
When I set the localID to "fr-FR", the titlecase pipe doesn't work as expected on word with accent marks.

#### What is the expected behavior?
//Always with localID set to "fr-FR"
{{"décembre" | titlecase}} or {{myDate | date :'MMM':'fr-FR' | titlecase}}  should return "Décembre" 

#### What is the current behavior?

{{"décembre" | titlecase}} or {{myDate | date :'MMM':'fr-FR' | titlecase}}  return "DÉCembre" 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5

**Comment by julianobrasil** [comment]
This is not a Material issue. You should discuss it in Angular Repo.

**Comment by Korouzan** [comment]
Oops scuse me I did'nt see that I was on the material github :/
