### ISSUE TITLE
md-tab creates inside component on every click/select

### ISSUE THREAD

**Issue by elvirdolic** [angular/material2#864]
#### Bug, feature request, or proposal:
BUG?

#### What is the expected behavior?
Components used insides are only initialized once not on every tab change

#### What is the current behavior?
Components are initialized on every tab change 

#### What are the steps to reproduce?
Use a basic md-tab template and put another components inside

eg.

```
    <md-card>
        <md-card-content>
        <md-tab-group>
            <md-tab>
                <template md-tab-label>
                    Applications
                </template>
                <template md-tab-content>
                   <pd-app-launcher></pd-app-launcher>
                </template>
            </md-tab>
            <md-tab>
                <template md-tab-label>
                    Products
                </template>
                <template md-tab-content>
                    <pd-product-launcher></pd-product-launcher>
                </template>
            </md-tab>
        </md-tab-group>
        </md-card-content>
    </md-card>
```
In this case the pd-app-component is initialized on every tab switch, constructor gets called every time

Is this the normal behavior?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
beta 6

**Comment by jelbourn** [comment]
See #731
