### ISSUE TITLE
multiple MatDialog items when using inside a child module

### ISSUE THREAD

**Issue by damienbod** [angular/material2#8640]
#### Bug, feature request, or proposal:

Multiple MatDialog items inside a child module when switching from/to the module containing the MatDialog .

#### What is the expected behavior?

Only one MatDialog should be opened. Either the old ones should be disposed or only 1 should be created.

#### What is the current behavior?

When I load a MatDialog inside a module, everything works as expect. When I switch to a different module inside the Angular app, and then back the the original module containing the MatDialog  and open this again, 2 dialogs are opened. If I switch 10 times, then 10 dialogs are opened.

#### What are the steps to reproduce?

Create an Angular app with 2 child modules lazy loaded. Add the MatDialog to one following the documentation. Start the application and open, close the dialog. Switch to the other child module. Switch and open the MatDialog again. This time 2 are opened.

#### What is the use-case or motivation for changing an existing behavior?

Bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    "@angular/animations": "4.4.6",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/compiler-cli": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/flex-layout": "v2.0.0-beta.9",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/platform-server": "4.4.6",
    "@angular/router": "4.4.6",
    "@angular/upgrade": "4.4.6"

**Comment by julianobrasil** [comment]
@damienbod, would you mind to reproduice it here: https://stackblitz.com/edit/mat-dialog-lazy-load ?

I wasn't able to find the multiple dialogs you've mentioned.

**Comment by damienbod** [comment]
@julianobrasil Thanks for your answer. I can't reproduce this using the new packages. I must update. Thanks.
