### ISSUE TITLE
Add/allow a white variant of the mat-form-field, when using inputs against a background-color other than white.

### ISSUE THREAD

**Issue by damienwebdev** [angular/material2#8644]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
As a developer, I should be able to utilize a `white` variant of the `mat-form-field` along with `mat-select` in order to be able to place a white `mat-select` against a `primary` or `accent` background.

#### What is the current behavior?
Currently, I can only apply a `primary`, `accent` or `warn` to a `mat-form-field` which doesn't work well against dark backgrounds as the text of the placeholder is default black on `mat-dark-theme`.

#### What are the steps to reproduce?
http://plnkr.co/edit/IqjrJkmla0MEPpYTYAIM?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I want to utilize a `mat-select` against a dark background with changing to the `mat-dark-theme`. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Currently using @master

**Comment by crisbeto** [comment]
All Material components support dark themes already. You can see for yourself by going to [one of the demos](https://material.angular.io/components/input/overview) and changing to a dark theme from the theme picker in the top right.

**Comment by willshowell** [comment]
@damienwebdev maybe this https://github.com/angular/material2/issues/7145#issuecomment-330282110 is related.

**Comment by damienwebdev** [comment]
@willshowell Yep. I was trying to achieve what @jelbourn stated precisely. I needed a "solo-field". I'll build out my own custom one for now. Maybe we should consider a proposal for `mat-solo-field` as a component that's treated similarly to `mat-form-field`? But, that's outside the context of this issue. Let me know if you'd like me to create a issue for the `mat-solo-field` proposal.

You can keep this issue closed.
