### ISSUE TITLE
Bug: Plunker links no longer works from Angular Material Documentation Examples

### ISSUE THREAD

**Issue by larsm11** [angular/material2#8659]
I've not tested the plunks for all Components, but so far, I've been unable to successfully launch any of the Plunker links from the Angular Material Component Examples.

When checking the browser console, it looks like different problems for each of the samples.

**Comment by julianobrasil** [comment]
Have you tried to clear your cache?

**Comment by Teamop** [comment]
You can check again, the examples on material.angular.io are now opened externally via
StackBlitz instead of Plunker as per 5.0.0-rc.2 released today

**Comment by larsm11** [comment]
Works like a charm with Stackblitz.

Closing the issue.
