### ISSUE TITLE
Mat-Checkbox Validation

### ISSUE THREAD

**Issue by Renader** [angular/material2#8662]
#### Bug, feature request, or proposal:
Bug / Feature Request

#### What is the expected behavior?
Checkbox reveals its validation state as a regular text input does. This means to me: 1. Taking mat-error color and 2. provides a place (html) to store mat-error messages like mat-form-field wrapper. 

#### What is the current behavior?
Screenshot of default state:
![image](https://user-images.githubusercontent.com/16294855/33257852-fd321830-d357-11e7-89d0-447f4feec2f1.png)
Screenshot after triggered Submit in order to show error state:
![image](https://user-images.githubusercontent.com/16294855/33257859-04ddb012-d358-11e7-9531-893035f338d0.png)

When I trigger the example submit button in the provided demo the input clearly reveals its input by taking the red color. The checkbox stays the same. Afaik I can't wrap the checkbox with a mat-form-field. So how am I supposed to have a proper validation feedback?

#### What are the steps to reproduce?
Submit the form here:
https://stackblitz.com/edit/checkbox-reactive-ghbepp

#### What is the use-case or motivation for changing an existing behavior?
Deliver a consistent validation feedback.

**Comment by jelbourn** [comment]
The Material Design spec does not prescribe an error display for toggle controls, so we leave that to the user to implement at the application level.

**Comment by Renader** [comment]
@jelbourn 

Okay, I understand that. Would it still be possible to place this commentary on the documentary? So that more developers don't make the very same mistake as me? 

Because I think that this is a very common use case and it is also very common that developers don't know the material specs. 

Thanks for your fast reply!

**Comment by bobKasbi** [comment]
@Renader:
I know the issue is closed.. but it might be helpful. 
`<mat-checkbox formControlName="accept" (change)="onChange($event, this)" #tc></mat-checkbox>
<mat-error align="end" *ngIf="!tc.checked">Your error message here</mat-error>`
Working fine for me
