### ISSUE TITLE
Dynamic Table Columns: Headers don't update if amount of them stays the same

### ISSUE THREAD

**Issue by funkizer** [angular/material2#8663]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Column Headers should update when columns are swapped but the amount of them doesn't change.

#### What is the current behavior?
When I push a new immutable array to the `source.cols` BehaviorSubject, header texts only change if the amount of cols changes.

Have tried calling ChangeDetectorRef.markForCheck() and .detectChanges() right after pushing new columns, and with a 100ms delay, did nada.

#### What are the steps to reproduce?
Sorry no time for a full example. Template:
```
  <mat-table #table [dataSource]="source" matSort matSortActive="name" matSortDirection="asc">
    <ng-container [matColumnDef]="col.key" *ngFor="let col of source.cols|async">
      <mat-header-cell *matHeaderCellDef mat-sort-header> {{col.label}} </mat-header-cell>
      <mat-cell *matCellDef="let element">
        {{element[col.key]}}
      </mat-cell>
    </ng-container>
    <mat-header-row *matHeaderRowDef="source.columnKeys|async"></mat-header-row>
    <mat-row *matRowDef="let row; columns: (source.columnKeys|async);"></mat-row>
  </mat-table>
```

`source` is an extended DataSource with added BehaviorSubjects called `cols` and `columnKeys`. I next() new cols and columnKeys before I next the data Observable that connect() returns.  `source.cols` streams arrays like:
```
[
	{
		label: 'Header text',
		key: 'Prop name of objects in the data array'
	},
	...
]
```

Hacky work-around: Force table to rerender by wrapping it in div *ngIf that's falsy for 10 ms after new columns have been received.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
  "@angular/material": "^5.0.0-rc0",
  "@angular/cdk": "^5.0.0-rc0",
  "@angular/core": "^5.0.3",

**Comment by funkizer** [comment]
Looks like a custom tracking function is required in this case. Adding trackBy here solved the issue:

`<ng-container [matColumnDef]="col.key" *ngFor="let col of source.cols|async; trackBy: customTrackBy">`

``` 
// component
 customTrackBy(index, item) { return item.key; } 
```

**Comment by andrewseguin** [comment]
Sorry for the inconvenience of this - there was another issue opened up that was similar to this. Looks like you already found the workaround, but if you want more of a deep-dive into what is happening, check out this comment https://github.com/angular/material2/issues/8361#issuecomment-345804954

**Comment by funkizer** [comment]
No inconvenience at all, my bad for poor searching. Instead I had great fun diving into cdk src, where I got the idea that groupBy might do it. Respect & thanks!  =) <3
