### ISSUE TITLE
npm package version issue

### ISSUE THREAD

**Issue by sinedied** [angular/material2#8664]
The current npm version is `5.0.0-rc.1`, but the previous one was `5.0.0-rc0` (without the `.`) leading to update issues:

I have updated my `package.json` for the new version but to allow future RC updates with `^5.0.0-rc.1`, but it resolves to  the `rc0`:
![image](https://user-images.githubusercontent.com/593151/33261976-fc57774a-d364-11e7-9b7d-44f5f91e91f6.png)

Continuing with the current versioning means that many people like me with either have to pin the version and update it manually for each new release or will be stuck to rc0 until the final version comes out 😞

**Comment by jelbourn** [comment]
I re-published `5.0.0-rc0` as `5.0.0-rc.0` and marked the former as deprecated with `npm deprecate`. This should resolve things, though npm's documentation isn't clear about the effects of marking a package as deprecated

**Comment by sinedied** [comment]
@jelbourn Seems that it did not change anything:
![image](https://user-images.githubusercontent.com/593151/33308595-6b19ef30-d41b-11e7-9da9-d5b740259f09.png)
Seems [this package](https://www.npmjs.com/package/semver) is used by npm to resolve versions, and it does not account for deprecation tags.
