### ISSUE TITLE
Linear stepper: already valid steps can be skipped without visit

### ISSUE THREAD

**Issue by fpeterdev** [angular/material2#8667]
#### Bug, feature request, or proposal:
Not sure but I think it's a bug

#### What is the expected behavior?
In case of linear stepper the user can skip a not completed step if the step is already valid.

#### What is the current behavior?
Already valid steps should be mandatory to complete as well.

#### What are the steps to reproduce?
The second step can be skipped here:
https://stackblitz.com/edit/angular-material2-issue-wnrjsf

#### What is the use-case or motivation for changing an existing behavior?
There are use-cases where we just want to show some information without any user input, or we can prefill data (e.g billing address), so it will be valid, but the user should check (and accept)

**Comment by DmitryEfimenko** [comment]
I think I have run into the same issue.
For me, it needs to show that the step is completed disregarding whether the step is visited or not.
A quick change to the [line 113](https://github.com/angular/material2/blob/master/src/cdk/stepper/stepper.ts#L113) did the trick.
Before change:
```ts
return this.stepControl ? this.stepControl.valid && this.interacted : this.interacted;
```
After change:
```ts
return this.stepControl ? this.stepControl.valid : this.interacted;
```

**Comment by Goodwine** [comment]
@mmalerba

**Comment by Goodwine** [comment]
Hello, has there been any progress on this bug?

**Comment by mmalerba** [comment]
I see 2 possible solutions to this:
1. Even if the step is valid, still require the user to go to the step and confirm that they want to move on without changing anything.
2. Allow the user to skip the step if its valid, but update the icon to show the step as implicitly completed

I'm leaning toward solution 1 being the right solution. marking the stepper as linear should probably mean that the user does have to step through each step
