### ISSUE TITLE
Error using MatTableModule with demo

### ISSUE THREAD

**Issue by pierre03** [angular/material2#8671]
#### Bug, feature request, or proposal:
The example is not up to date for the table, for example:
```
<ng-container matColumnDef="position">
      <**mat-header-cell** *matHeaderCellDef> No. </mat-header-cell>
      <**mat-cell** *matCellDef="let element"> {{element.position}} </mat-cell>
    </ng-container>
```
They are not camel case, we can not find these definitions.
#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
