### ISSUE TITLE
Tabs: The tab portal detached after the animation start

### ISSUE THREAD

**Issue by 0x6368656174** [angular/material2#8672]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The tab portal shouldnt' be detached until the animation is done (after centering rather than before).
 
#### What is the current behavior?
The tab portal detached after the animation start (immediately after the beginning of the centering).

#### What are the steps to reproduce?
This can be seen on the Angular Material site, in the examples section: https://material.angular.io/components/tabs/examples

#### What is the use-case or motivation for changing an existing behavior?
The section on "Navigational transitions" in the Material Design Guidelines specifies that in a sibling to sibling transition:

> New content slides in from the right while sibling content moves off-screen to the left.

It seems that the "moves off-screen" part has been effectively removed after merged #8486.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
~~~
Angular CLI: 1.5.4
Node: 8.5.0
OS: linux x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc1
@angular/cli: 1.5.4
@angular/material: 5.0.0-rc1
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.6.1
webpack: 3.8.1
~~~

**Comment by jrood** [comment]
If anyone has a workaround for this in the meantime (aside from staying on an older version) I would be very thankful.
