### ISSUE TITLE
Md Slider track not move correctly when zoom is set

### ISSUE THREAD

**Issue by jazztong** [angular/material2#8678]
#### Bug, feature request, or proposal:
MD Slider not move correctly when zoom attribute is set

#### What is the expected behavior?
MD slider should work as it should

#### What is the current behavior?
MD slider will move in a big step when zoom is set

#### What are the steps to reproduce?
https://plnkr.co/edit/TYnw1k1OoIJQ3DUyWI5B?p=preview

#### What is the use-case or motivation for changing an existing behavior?
The parent page set to zoom responsively base on resolution

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0-rc0
Angular material 5.0.0-rc0

#### Is there anything else we should know?
NA

**Comment by mmalerba** [comment]
We don't support the CSS zoom property for the slider. It looks like you can use a transform to achieve a similar effect though, that won't throw off the thumb position: https://plnkr.co/edit/VMsLET6c6BTaHC6ur94p?p=preview
