### ISSUE TITLE
MD-SIDENAV - Pinned and backdrop options - Feature request

### ISSUE THREAD

**Issue by joejordanbrown** [angular/material2#868]
#### Feature request:
Add pinned option with setting option for it to be pinned when view is desktop.

The material design specifications for **Desktop structure** of the sidenav say "accessed temporarily or pinned for permanent display." 

Is there going to be an option for this? 

Also i think the backdrop should be allowed to be disabled manually or automatically when pinned.

**Comment by jelbourn** [comment]
You can bind the opened state to always be true. More responsive feature will be coming in the future. `mode="side"` doesn't have a backdrop.

**Comment by Dunos** [comment]
@jelbourn what about the backdrop, how can we disable it manually? I need to use the "over" mode but without any backdrop, or at least add one more more to cover that case.

**Comment by willshowell** [comment]
@Dunos try adding this to your global stylesheet

```scss
.mat-sidenav-backdrop.mat-sidenav-shown {
 background: none;
}
```

**Comment by Dunos** [comment]
@willshowell I tried that before but I don't think changing the CSS should be the right approach to this, specially when in the AngularJS version there was a parameter to do so `md-disable-backdrop`. Also in the same project could be 2 or 3 different types of sidenavs and so you would have to use the `/deep/` styles in the CSS. One single param in the constructor seems much "cleaner" to me (or just one more mode).

**Comment by willshowell** [comment]
I see, maybe open a separate new issue similar to #2806. That seems to be similar behavior as to what you're looking for.

**Comment by Dunos** [comment]
Thanks, I did open a new [one](https://github.com/angular/material2/issues/4482) like suggested.
