### ISSUE TITLE
Sidenav example not working in docs

### ISSUE THREAD

**Issue by GlennVanSchil** [angular/material2#8682]
#### Bug, feature request, or proposal:
No example rendered

#### What is the expected behavior?
Seeing a working example

#### What is the current behavior?
Example stays empty

#### What are the steps to reproduce?
Go to the following URL
https://material.angular.io/components/sidenav/examples

**Comment by amcdnl** [comment]
PR opened - https://github.com/angular/material2/issues/8682

**Comment by cole21771** [comment]
It would be nice if any of the stackblitz were working for the sidenav:
https://stackblitz.com/angular/aebaobgqnqk
https://stackblitz.com/angular/makmpdnxdxl

It would also be nice if the docs examples worked:
https://material.angular.io/components/sidenav/examples

or if they would even have the correct name for the site they link to (basic sidenav example says open link to plunker):
https://material.angular.io/components/sidenav/overview

**Comment by mmalerba** [comment]
This has been fixed
