### ISSUE TITLE
[Table] Modify Sorting to MatTableDataSource with when predicate

### ISSUE THREAD

**Issue by abhisgit** [angular/material2#8684]
#### Proposal:
Currently sorting through MatTableDataSource while using 'when' predicate is not working properly. For example, detail rows are also sorted while detail row should always be relative to the parent row.

Note: I have faced problems with paging as well while using 'when' predicate. For example, if your page size option is 5, then the 6th row will be 'detail row' and that will be displayed on the second-page index. 
However, quick fix is to provide even numbers to page size options property; [pageSizeOptions]="[20, 50, 100]".

#### What is the expected behavior?
The expected behavior is to not sort detail row. Could it be possible to assign a different data source to the table and different data source for sorting?

#### What is the use-case or motivation for changing an existing behavior?
For example, I have a category of books (Science, History, Finance etc) and under each category, there are different books. I want to show books category as main or parent row in a table and on click of this row, books belonged to this category will be displayed. Now, if I sort by any column/field, I expect sorting to be applied only to the books category and not to the 'detail row' of books belonged to a category.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material@5.0.0-rc0

**Comment by willshowell** [comment]
I don't think MatTableDataSource is (yet?) suited for sorting 'grouped' rows. You may be able to utilize `sortingDataAccessor` by making the sorting key unique per group. I expect that would require a stable sort, which isn't a browser guarantee. 

Your best bet is to handle this in a custom data source.

**Comment by jelbourn** [comment]
The table itself, including the use of `when` predicate, dictates how the data should be rendered. The data source doesn't know how the data should be rendered, it just provides the items. 

`MatTableDataSource` is meant to cover simple use-cases where sorting / pagination affects the dataset homogeneously. As @willshowell said, your best bet here is to make a data source specific to your use case.
