### ISSUE TITLE
ReferenceError: Event is not defined - server side rendering(angular universal)

### ISSUE THREAD

**Issue by mistrynilesh** [angular/material2#8685]
#### What are the steps to reproduce?
 I am using angular universal to build server side rendering.  it works on client side rendering but while running on server side it gives error ReferenceError: Event is not defined in main.bundle.js

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Node 6.9.4
"@angular/animations": "^5.0.2",
"@angular/cdk": "5.0.0-rc.1",
"@angular/common": "^5.0.2",
"@angular/compiler": "^5.0.2",
"@angular/compiler-cli": "^5.0.2",
"@angular/core": "^5.0.2",
"@angular/flex-layout": "2.0.0-beta.10-4905443",
"@angular/forms": "^5.0.2",
"@angular/http": "^5.0.2",
"@angular/material": "5.0.0-rc.1",
"@typescript": "2.4.2"

**Comment by crisbeto** [comment]
Can you post the Material components that you're using on the particular page? We have a CI check to verify that everything works on Universal which hasn't caught this error yet.

**Comment by jelbourn** [comment]
Closing this issue as it does not fully follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
