### ISSUE TITLE
Material not working in Internet Explorer 11 (Edge)

### ISSUE THREAD

**Issue by KarlXOL** [angular/material2#8687]
#### Bug, feature request, or proposal:
Is current material not supported in IE 11? When entering https://material.angular.io/ in IE 11 I get attached error message. Actually I was testing this, as this is the same error I get in my angular 5, Material 5 application. Have I overseen something?

![material_5_internet_explorer 11](https://user-images.githubusercontent.com/21153915/33338143-6af2c9fa-d475-11e7-87a3-cf923bb9eb89.PNG)

**Comment by donroyco** [comment]
IE11 is supported as can be read in the Readme-file.

> Angular Material supports the most recent two versions of all major browsers: Chrome (including Android), Firefox, Safari (including iOS), and *IE11 / Edge*

**Comment by KarlXOL** [comment]
ok, I assumed that. So can you reproduce this error?
I tested this with this version
![ie11_version](https://user-images.githubusercontent.com/21153915/33341686-fc1746d6-d47f-11e7-8171-7ef2eac0ee83.PNG)

**Comment by KarlXOL** [comment]
Ok, it was a "ghostery" issue. I've disabled ghostery and now it works.

**Comment by leolanese** [comment]
Can eliminate this bug report, it was never a bug.
