### ISSUE TITLE
document:scroll not working using md-sidenav-layout fullscreen

### ISSUE THREAD

**Issue by fabiopaiva** [angular/material2#869]
I'm not sure if this is a bug
I want to use sidenav fullscreen and monitor the scroll position on the screen but if i use the fullscreen directive the event is not triggered.

http://plnkr.co/edit/M9l63i7iYMX0F79f4SDQ?p=preview

I want to use fullscreen because it keep the sidenabar fixed on all screen but I need to get the position after the user scroll the screen.

Without the fullscren directive I am able to get scroll position like in this plnkr:
http://plnkr.co/edit/ZAtaZV7326cspApWH8fO?p=preview

angular: 2.0.0-rc.4
material: 2.0.0-alpha.6
Browsers: Firefox and Chrome
OS: Ubuntu 14.04

**Comment by mmalerba** [comment]
dup of #802
