### ISSUE TITLE
mat-checkbox ignores checked property

### ISSUE THREAD

**Issue by GMillerVarian** [angular/material2#8691]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When supplying the checked property, the checkbox state in the UI should match.

#### What is the current behavior?
The checked property is ignored. There is no difference in behavior whether or not checked is specified. 

#### What are the steps to reproduce?
http://plnkr.co/UWQeFu

When you uncheck, the bound value is updated to the false value, however the UI shows checked state until checkbox is clicked a second time.

#### What is the use-case or motivation for changing an existing behavior?
Updating a component library (which previously used ng-true-value and ng-false-value) and trying to maintain existing functionality.

**Comment by tinayuangao** [comment]
In your `my-checkbox`, the `[value]` should be `innerValue` instead of `value`: when the value is a valid string with content, it's still considered as `true` in boolean.

Here's a working plnkr: http://plnkr.co/edit/ZJ8GkfrEgKnbma8o4MCO?p=preview

**Comment by GMillerVarian** [comment]
With this solution, 2-way binding isn't working properly as can bee seen when multiple controls bind to the same value. Please see my updated plunker: http://plnkr.co/UWQeFu

**Comment by GMillerVarian** [comment]
Please re-open.

**Comment by GMillerVarian** [comment]
Please re-open. The suggested solution doesn't work. The checkbox does not detect changes to the bound value when changed from another control or from script since the checkbox is bound to innverValue which is not the @Input variable used for 2-way binding.
