### ISSUE TITLE
Decouple outside-click-to-close and escape-to-close options for MatDialog

### ISSUE THREAD

**Issue by jamiehand** [angular/material2#8694]
#### Bug, feature request, or proposal:

Decouple outside-click-to-close and escape-to-close options for MatDialog.

The current disableClose option assumes that if I want to disable outside-click-to-close, I also want to disable escape-to-close. However, disabling escape-to-close is an [accessibility issue](https://material.angular.io/components/dialog/overview#keyboard-interaction). I don't want users to accidentally click outside the dialog (it's easy to do) and lose their work, but I *do* want users (especially those with screenreaders and similar accessibility technology) to be able to use the escape key to close the dialog.

#### What is the expected behavior?

Two options, e.g. disableEscapeClose and disableClickClose, to replace the disableClose option.

#### What is the current behavior?

A single option (disableClose) that forces shared behavior of escape and outside-click.

#### What are the steps to reproduce?

Click on the below links and click "Pick one." Then try clicking outside and/or pressing escape to exit the window.

[Example with disableClose: true](https://stackblitz.com/edit/angular-jemkjk?file=app%2Fdialog-overview-example.ts)
[Example with disableClose: false](https://stackblitz.com/edit/angular-jemkjk-vy9v99?file=app/dialog-overview-example.ts)

#### What is the use-case or motivation for changing an existing behavior?

Accessibility, ease of use for power users (lots of people use the escape key).

**Comment by jelbourn** [comment]
You can set `disableClose` and then subscribe to `keydownEvents` on the MatDialogRef to manually call `.close()` on escape.
