### ISSUE TITLE
mat-icon height/width styles not specific enough

### ISSUE THREAD

**Issue by raciasolvo** [angular/material2#8699]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Icon should be 24px.

#### What is the current behavior?
![icons](https://user-images.githubusercontent.com/22774388/33355115-22a0fe7c-d4c7-11e7-91d7-242b114c710b.jpg)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-htjtlq

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Last

#### Is there anything else we should know?

When sprites don't have width and height (see https://raw.githubusercontent.com/google/material-design-icons/master/sprites/svg-sprite/svg-sprite-action-symbol.svg)  we can see the bug. Weight of your style is less.

I wrote early https://github.com/angular/material2/issues/3441

In some projects I also use flex-shrink instead width and height for svg:
```
@mixin mat-icon-size-bug() {
  	.mat-icon {
  		flex-shrink: 0;
	}
}
```

**Comment by tomwanzek** [comment]
Experiencing the same issue with svg icons being clipped in width.

**Comment by jelbourn** [comment]
It looks like the component styles are being overridden by more-specific browser agent styles
