### ISSUE TITLE
Sidenav, plunker not working anymore

### ISSUE THREAD

**Issue by ProElbs** [angular/material2#8702]
Hello

There is some trouble to see the plunker for Sidenav: https://material.angular.io/components/sidenav/overview

Plunker(s) are not working anymore. 

Thanks forward ! :)

**Comment by TheRedD0t** [comment]
Clear you cache and try again, Stackblitz is now used in the docs instead of Plunker.

**Comment by ProElbs** [comment]
I cleared my cache but still not working. 

What is weird is that the problem is only for this item (sidenav), every other are working well for demo

**Comment by TheRedD0t** [comment]
> I cleared my cache but still not working.

I didn't say, that the cached docs is the reason why the demos aren't working, I just wanted to give you the hint that it seems that you have an older version of the docs in your cache.

The not working side nav demos are already a known problem. Have a look at the issue I linked in my previous comment.

**Comment by Misiu** [comment]
![snap 2017-11-29 at 10 08 27](https://user-images.githubusercontent.com/1741838/33367001-506cd4b8-d4ed-11e7-81ad-36d4b6aa5f2c.png)

Also worth mentioning that description is wrong, it says Plunker, when StackBlitz is used.
Sorry for not opening new issue for that, it's just a small typo.

**Comment by ProElbs** [comment]
And also, if you check the "Examples" tab at the top of the page, the whole content is empty.

Thank you TheRedDot, i will refer to the other issue from your previous comment

**Comment by Dominik-Andreas-Geng** [comment]
The [examples](https://material.angular.io/components/sidenav/examples) are blank.

**Comment by mmalerba** [comment]
This should be fixed now, the examples have been updated to use Stackblitz.
