### ISSUE TITLE
[Feature request] MatDialog config option to disable scroll-blocking

### ISSUE THREAD

**Issue by apptum** [angular/material2#8706]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
A config option to disable the scroll-blocking behavior of a dialog
(so that the underlaying page could be used as without the dialog)

#### What is the current behavior?
There's an option to disable to backdrop `hasBackdrop` but the underlaying site still isn't scrollable (but clickable though)

#### What is the use-case or motivation for changing an existing behavior?
With this feature it would be possible to "pin" a dialog like gmails compose-email window.

**Comment by crisbeto** [comment]
You can use the `MAT_DIALOG_SCROLL_STRATEGY` injection token to provide another scroll strategy for all the dialogs @apptum.

**Comment by Adrian1907** [comment]
Help me please to find some explanation how to set scroll strategy for MatDialog.

**Comment by crisbeto** [comment]
You can pass it in as an option when you open the dialog @Adrian1907:

```ts
constructor(public dialog: MatDialog, overlay: Overlay) {
    dialog.open(JazzDialog, {
      scrollStrategy: overlay.scrollStrategies.noop()
    });
  }
```

**Comment by Adrian1907** [comment]
@crisbeto Does it require some imports? My editor tells me:

> Cannot find name 'overlay'

**Comment by crisbeto** [comment]
You have to `import {Overlay} from '@angular/cdk/overlay';`.

**Comment by Adrian1907** [comment]
@crisbeto Thanks, it works!

**Comment by simeyla** [comment]
Please note: For iOS Safari, when opening a dialog the browser chrome will reappear if previously hidden (due to this css class changing the scroll position + making it position: fixed). This same code will prevent the chrome from appearing - which can be a bad user experience.
