### ISSUE TITLE
progress-spinner not working in Edge 

### ISSUE THREAD

**Issue by BeshoyHindy** [angular/material2#8709]
#### Bug, feature request, or proposal:
<mat-spinner> or <mat-progress-spinner mode="indeterminate"> is giving a circle rather than a spinning one in Internet Explorer and Microsoft Edge

#### What is the expected behavior?
Spinning.

#### What is the current behavior?
Static circle
The spinner is working fine in Chrome, Firefox and Safari In Beta 11 and older
but In Beta 12  the spinner isn't working fine in IE and Edge.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.6, NG Material 2.0.0-beta.12, TypeScript 2.3.3,  Edge 40.15063.674.0

**Comment by julianobrasil** [comment]
Can't you update your project?

**Comment by jelbourn** [comment]
Closing this since it refers to an old version. Feel free to open a new issue if there is a problem with the latest version.
