### ISSUE TITLE
 Cannot read property 'bind' of undefined at new MediaMatcher

### ISSUE THREAD

**Issue by Gorniv** [angular/material2#8710]
#### Bug 
When I use the material for my universal project, I have this problem:
exception:
```
TypeError: Cannot read property 'bind' of undefined
    at new MediaMatcher (C:\GitHub\AngularMigration-Init\angular2\server.js:137690:30)
    at _createClass (C:\GitHub\AngularMigration-Init\angular2\server.js:15506:20)
```
source
```ts
var MediaMatcher = (function () {
    function MediaMatcher(platform) {
        this.platform = platform;
        this._matchMedia = this.platform.isBrowser ?
            // matchMedia is bound to the window scope intentionally as it is an illegal invocation to
            // call it from a different scope.
            window.matchMedia.bind(window) :
            noopMatchMedia;
    }
```
#### What is the expected behavior?
no error

#### What is the current behavior?
error

#### What are the steps to reproduce?
https://github.com/Angular-RU/angular-universal-starter/tree/material2
`npm run ssr:debug`
open http://localhost:4000/material

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/cli": "1.6.0-rc.0",
"@angular/core": "5.0.3",
"@angular/material": "5.0.0-rc.2",
"typescript": "2.4.2"

**Comment by GevorGSM** [comment]
I have same issue.In my case it is because I inject in app.component MatSnackBar , but I haven`t  found solution yet.

**Comment by Gorniv** [comment]
MatSnackBar  working: https://github.com/Angular-RU/angular-universal-starter/commit/b848c41b3c413aca9e5a129f266154c81807d4dc
Now you can fix MediaMatcher  like fix.js:
```js
var fs = require('fs')
const someFile = './server.js';
fs.readFile(someFile, 'utf8', function(err, data) {
    if (err) {
        return console.log(err);
    }
    const result = data.replace('this.platform.isBrowser ?', 'this.platform.isBrowser && window.matchMedia !== undefined ?');
    fs.writeFile(someFile, result, 'utf8', function(err) {
        if (err) return console.log(err);
    });
});
```

**Comment by GevorGSM** [comment]
I know,it working for materialPage.component.ts,in my case in this component it working to but I need use snackbar in app.component.spasibo za fix.js,it fix my problem
