### ISSUE TITLE
@angular/material/material"' has no exported member 'MATERIAL_COMPATIBILITY_MODE'

### ISSUE THREAD

**Issue by costea93** [angular/material2#8712]
Just updated to last version of material, so in my package now i have:

`"  @angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.0-rc0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",`

on project build i get next error:

error TS2305: Module '"D:/node_modules/@angular/material/material"' has no exported member 'MATERIAL_COMPATIBILITY_MODE'.

is this a bug in material modules?

**Comment by CDDelta** [comment]
MATERIAL_COMPATABILITY_MODE was removed as its behaviour is now the default, just remove it from your code and things will work again.

**Comment by costea93** [comment]
@CDDelta thanks, it works now
