### ISSUE TITLE
material_1.MatTableDataSource is not a constructor

### ISSUE THREAD

**Issue by costea93** [angular/material2#8714]
I'm trying to create a table as on angular documentation source: 

https://material.angular.io/components/table/examples

Just copied the code from table example and in my class i have: 
`public dataSource = new MatTableDataSource<Element>(ELEMENT_DATA);`

why i get this error:

material_1.MatTableDataSource is not a constructor

**Comment by andrewseguin** [comment]
Sounds like you might be on an earlier version, can you verify that you are up to date? Feel free to re-open with a reproduction of the error, otherwise it sounds like a local issue
