### ISSUE TITLE
mat-select not updating selected text when updating options dynamically

### ISSUE THREAD

**Issue by Dunos** [angular/material2#8716]
#### Bug, feature request, or proposal:
Working with dynamic option labels, once a option is selected, the label text will not change until the select element is clicked again to show the list of options.

#### What is the expected behavior?
The selected value should change as soon as the option text changes

#### What are the steps to reproduce?
In [this example](https://stackblitz.com/edit/angular-hpybef) you can see the behaviour, just select the "Steak" option and then press the button. The "Steak" label won't change until the selector is clicked

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material: 5.0.0-rc2
@angular/cli: 1.5.4
@angular/core: 5.0.3

**Comment by willshowell** [comment]
This is a due to the select using OnPush change detection. You may be interested in using `<mat-select-trigger>`.

**Comment by Dunos** [comment]
@willshowell is there any example on how to use that? In the docs there is not much info about it :/

**Comment by willshowell** [comment]
See https://material.angular.io/components/select/overview#customizing-the-trigger-label
