### ISSUE TITLE
Why don't you write about cdk/xxx-prebuilt.css in CDK docs?

### ISSUE THREAD

**Issue by Quramy** [angular/material2#8717]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
I think it's nice CDK docs tells "You can include prebuilt CSS via `@import "~@angular/cdk/overlay-prebuilt.css";`"  like https://material.angular.io/guide/theming#using-a-pre-built-theme

When I first started CDK, I didn't know the prebuilt CSS files and I was confused about my Overlay container positioning did not work.

**Comment by stephengardner** [comment]
I'm so confused here.... The overlay containers are used for menus, etc.  The CSS is not included automatically when you're using an element like `mat-menu`?

**Comment by willshowell** [comment]
@stephengardner the overlay css is included if you've imported a Material theme. The issue is, if you are only using the cdk/overlay without Material, you don't automatically get the overlay css. So you must import it via the statement outlined by OP.

**Comment by kbo4sho** [comment]
Maybe this is another page under guides "CDK Styling" with a section on prebuilt? I can take this if no else has dibs.

**Comment by willshowell** [comment]
Go for it @kbo4sho!

**Comment by kbo4sho** [comment]
I'll get something together!

**Comment by reggaedit** [comment]
Adding `@import "~@angular/cdk/overlay-prebuilt.css";` to my `styles.scss` worked. Any progress on this issue? Would be good to get this into the cdk documentation.

**Comment by kbo4sho** [comment]
I agree, it should be documented. The PR I created was denied in favor of grouping this content into some other undetermined documentation section.
