### ISSUE TITLE
mat-spinner margin / padding actually takes up space

### ISSUE THREAD

**Issue by ilovett** [angular/material2#8722]
#### Bug, feature request, or proposal:

bug

#### What is the current behavior?

setting a small diameter on a spinner EG: 20px, the actual size is 20 * 10 = 200px

#### What is the expected behavior?

the spinner element should not take up as much space as it currently does (200px), it should be contained and all the css / spinning / presentation logic should be absolute positioned and centered, the container should only take up the defined size (20px)

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-btxxga?file=app/progress-spinner-configurable-example.html

#### What is the use-case or motivation for changing an existing behavior?

its a pain in the ass to work with (for anyone else looking for a solution, my current hack is to put a transform: scale(0.2); on the container element and leave the diameter/stroke as is)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

2 beta 12 -- looks like the stackblitz is 5 rc 0

#### Is there anything else we should know?

I love you

**Comment by crisbeto** [comment]
I wasn't able to reproduce it anymore. Closing.
