### ISSUE TITLE
[Pagination] Get data by pageIndex

### ISSUE THREAD

**Issue by nikhilb1208** [angular/material2#8723]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Change table data of a particular index.

#### What is the current behavior?
Sorts data by nextPage, previousPage and sets the index.

**Comment by andrewseguin** [comment]
Can you expand on this? The `MatPaginator` doesn't have knowledge of the data, and not sure what you mean about sorting.

**Comment by nikhilb1208** [comment]
i am trying to integrate bootstrap pagination to angular material and make it work. As the angular material pagination only goes to next and previous pages and sets the index.

I cannot set the data value of the page by pageIndex. 

Hope this helps. Sorry for my english.

**Comment by andrewseguin** [comment]
Sorry, having trouble interpreting what you mean by setting the data value of the page. Are you trying to change the page index and having trouble?
