### ISSUE TITLE
Can't change padding inside a mat-nav-list item

### ISSUE THREAD

**Issue by AbakumovAlexandr** [angular/material2#8727]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
We should have a way to change padding inside a `mat-nav-list` item.

#### What is the current behavior?
There is no way to change the padding inside a `mat-nav-list` item.

An element providing the padding is generated by Angular Material:
```
<div class="mat-list-item-content">
...
</div>
```
If you try to select it inside your component with a CSS selector `.mat-list-item-content { }`, it won't work since at the runtime, the element doesn't have those `_ngcontent-cx` attributes.

#### What are the steps to reproduce?
Here is [StackBlitz](https://stackblitz.com/edit/angular-material-mat-list-padding).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.2, Angular Material 5 RC2.

**Comment by SamiAl90** [comment]
Inject ElementRef and Renderer into your component

```
public constructor(private elementRef: ElementRef, private renderer: Renderer2) {}
```

and implements AfterViewInit lifecyclehook 

```
public ngAfterViewInit(): void {
        const listItems= this.elementRef.nativeElement.querySelectorAll('mat-list-item-content') as HTMLElement[];
        listItems.forEach(body => {
            this.renderer.setStyle(body, 'padding', '0px');
        });
    }
```

**Comment by AbakumovAlexandr** [comment]
@SamiAl90: Thank you, it could be a workaround for some situations.

But what if `mat-nav-list` items would get re-rendered? For instance, array items which they are bound to change.

**Comment by SamiAl90** [comment]
Then you will have to make sure this is applied again. This is due to shadow dom as far as I know. Before there was this css deep selector, which is now deprecated. I had no other solution for this case.

https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

**Comment by AbakumovAlexandr** [comment]
Yes, this is due to shadow DOM. From my perspective, Angular Material should make those `_ngcontent-cx` attributes apply to `mat-list-item-content` element as well to allow us to style it with simple CSS selector.

**Comment by jelbourn** [comment]
See https://material.angular.io/guide/customizing-component-styles
