### ISSUE TITLE
Tootip not hide

### ISSUE THREAD

**Issue by yooRabbit** [angular/material2#8728]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I create a scrollHeight button,the button shows with`$('html').scrollTop() > 0` hide with `$('html').scrollTop() == 0`,when `$('html').scrollTop() == 0` after `alt+tab` switch from another app,the toolTip should be hided.

#### What is the current behavior?
The problem is when when `$('html').scrollTop() == 0`  I use `alt+tab` back from another app,the toolTip show out. **Click in the page，toolTip hide**.
here my component:
html:
```
<button class="scroll-height" mat-raised-button matTooltip="back to top!" [ngClass]="{'show-scroll':scrollTop}" matTooltipPosition="before" (click)="goTop()">
  <i class="fa fa-angle-up"></i>
</button>
```
ts:
```
 goTop() {
    $('html').animate({
      scrollTop: 0
    }, 500);
  }
```
css:
```
.scroll-height{
  min-width: 40px;
  max-width: 40px;
  height: 40px;
  line-height: 40px;
  border-radius: 50%;
  cursor: pointer;
  font-size: 25px;
  text-align:center;
  position:fixed;
  background-color: #607d8b;
  color: #fff;
  bottom: 20px;
  right: -60px;
  z-index: 999;
  transition: background-color .18s cubic-bezier(.6,0,.1,1),box-shadow .18s cubic-bezier(.6,0,.1,1),transform .18s cubic-bezier(.6,0,.1,1);
  i{
    margin-left: -3px;
    height: 40px;
    line-height: 40px;
    margin-top: -5px;
  }
}
.show-scroll{
  transform: translate(-84px, 0);
}
```

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.0.0,
Material: 5.0.0-rc0,
OS: win10,
TypeScript: 2.6.1,
Browsers: Chrome@62.0.3202.94

#### Is there anything else we should know?
When I click the button with  `goTop()` and use `alt+tab` switch from chrome to another app,tooTip will be hided,and show out again when back to chrome.
update:
Not only use `alt+tab` any switch from chrome to another app,and back to chrome can cause this problem.

**Comment by andrewseguin** [comment]
Please re-open with a reproduction on plunker or stackblitz to help us investigate the issue.

**Comment by yooRabbit** [comment]
Here the [demo](https://angular-x7jqnq.stackblitz.io/) for this issue,please re-open.
scroll the view,click the button on the lower left corner and use `alt+tab` or any way switch from chrom and back,the tootip shows.
