### ISSUE TITLE
mat-select disable using native element

### ISSUE THREAD

**Issue by eloyleonardo** [angular/material2#8733]
#### Bug
If you try to set the disabled property of a mat-select using native element (on a directive) it doesn't work.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-k8mu2y-qinrgp
If you click in the button the input element turn disabled, but not the mat-select element.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular material: 5.0.0-rc.2
angular material: 5.0.3

**Comment by donroyco** [comment]
Because that's not how a native HTML element works if you want to disable it. This works: https://stackblitz.com/edit/angular-k8mu2y-6su7ty

**Comment by eloyleonardo** [comment]
Then Isn't possible to that in a directive ?
For example, i have to disable all fields when the user is offline, the best approach to solve that is by directive right ? Or will be better do this using decorators or class inheritance (and apply via direct bind like you did)?

**Comment by crisbeto** [comment]
There's no way for Material to know that you set the `disabled` property on the element. The correct way to disable it is either through a data binding (`<mat-select [disabled]="isDisabled">`) or by changing the `disabled` property on the component instance.
