### ISSUE TITLE
Can not disable custom MatFormFieldControl with FormControl with mat-autocomplete

### ISSUE THREAD

**Issue by mattem** [angular/material2#8735]
#### Bug, feature request, or proposal:
* Potential bug

#### What is the expected behavior?
A component implementing `MatFormFieldControl` with a `mat-autocomplete` can be disabled correctly via a `FormControl`.

#### What is the current behavior?
It is not possible to have a custom `MatFormFieldControl` implementation with a `mat-autocomplete` and have the input disabled via a `FormControl`. Notice in the StackBlitz application, it is possible to open the autocomplete overlay of the field and select an option even when the field is set to disabled.

If the `FormControl` is removed from the `input` element in `custom-input` and a binding to `[disabled]` is used, the behaviour works as expected. The reason I am using a FormControl here is to automatically apply validators to the input, so they are not needed to be added manually by the consumer of the form field everywhere it is used.

It does however work correctly when adding `matInput` to the `input` element inside `custom-input`. Is this the intended behaviour? The [CDK Docs here](https://material.angular.io/guide/creating-a-custom-form-field-control) do not include it.

#### What are the steps to reproduce?
https://stackblitz.com/edit/custom-mat-form-field-with-auto-complete

#### What is the use-case or motivation for changing an existing behavior?
To be able to disable the input when an autocomplete is attached, or be clearer in the docs when `matInput` is needed still.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest from NPM (see StackBlitz)

**Comment by crisbeto** [comment]
Your example breaks because you don't disable underlying `input` element when the form field becomes disabled, which means that it's still focusable and the user can still type in it.

**Comment by mattem** [comment]
@crisbeto I'm using a FormControl to disable the input, as using both a FormControl and binding with `[disabled]` says it's invalid. Removing the reference to the auto complete `[matAutocomplete]="auto"` on the underlying input also makes this example work correctly. Or are you saying I have to manually set and update the `disabled` attribute on the `input` element?

**Comment by crisbeto** [comment]
Yes, otherwise users will still be able to focus and type into the input.

**Comment by mattem** [comment]
How does this work then when I remove the reference to `matAutocomplete` from the `input` element? The element _should_ still be getting disabled by it's attached FormControl?

**Comment by crisbeto** [comment]
Sorry, now I see what you mean. I'll take a look at it.

**Comment by Chaslee4** [comment]
Meet the same issue. Can't disable the input in mat-autocomplete component when using FormControl...Is this issue fixed?
