### ISSUE TITLE
Custom Form Field Guide code not working

### ISSUE THREAD

**Issue by s-kirchner** [angular/material2#8738]
#### Bug, feature request, or proposal:
The code in the guide to creating custom form field seems to be broken (in Angular 5) and esp. in the provided StackBlitz

#### What is the expected behavior?
When opening the example in StackBlitz it should work as it does on the guide page

#### What is the current behavior?
First the form-field-custom-control-example.html in the StackBlitz link is empty which leads to a fatal error and second, even if the HTML provided in the guide is used, it does not show any placeholder or dashes. 

#### What are the steps to reproduce?
Link from the guide: https://stackblitz.com/angular/pmbqmxogbyb 

The problem seems to be that in Angular 5 `FocusMonitor.monitor()` takes three parameters, whereas only 2 are provided (line 106)

**Comment by mmalerba** [comment]
This has been fixed, the docs site now links to a working example: https://stackblitz.com/angular/earajmpqaoxx
