### ISSUE TITLE
[mat-toolbar] Attempting brace interpolation within mat-toolbar.class removes mat-toolbar and mat-primary classes

### ISSUE THREAD

**Issue by 646576** [angular/material2#8742]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I would expect that when binding a variable using interpolation, it should not affect default class assignment used by the component

#### What is the current behavior?
Attempting to assign the class of the <mat-toolbar> element using interpolation (ie: class="{{variable}}") ends up removing the mat-toolbar class from the rendered element, as well as the mat-primary class (when color="primary") is used. This may affect other default classes as well, I have only tested for my use-case.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-wm6jha

#### What is the use-case or motivation for changing an existing behavior?
I was merely attempting to apply mat-elevation-z* classes to mat-toolbar dynamically using interpolation

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/* 5.0.3 with @angular/cdk and @angular/material 5.0.0-rc0 (via stackblitz)
@angular/* 5.0.3 with @angular/cdk and @angular/material 5.0.0-rc.1

#### Is there anything else we should know?

**Comment by willshowell** [comment]
`ngClass` should do it

**Comment by crisbeto** [comment]
This isn't something specific to Material, it's how Angular works in general. When you interpolate the `class`, you'll override the entire attribute which clears any classes that are set by Material. You can achieve the same using `ngClass`: `[ngClass]="'mat-elevation-z' + n"`.
