### ISSUE TITLE
MatInput focus is not a function

### ISSUE THREAD

**Issue by ewaschen** [angular/material2#8743]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When calling `this.element.focus()` on #element input, the input should be focused.

#### What is the current behavior?
When` focus()` is called, the error is produced 

> TypeError: this.focusElement.focus is not a function

#### What are the steps to reproduce?

http://plnkr.co/edit/Ql1C0INK6epR2HIdPasK?p=info

Check the console for a log of the error and `this.element`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular:  5.0.3
Material: 5.0.0-rc.2-27dfd15
TypeScript: 2.1.6

#### Is there anything else we should know?

Focus works when using `import { ElementRef} from '@angular/core';` and `this.focusElement.nativeElement.focus();`

**Comment by crisbeto** [comment]
That's because the `focusElement` in your case is actually an `ElementRef`. You can get it working either by using `this,focusElement.nativeElement.focus()` or changing your template to:

```html
      <input matInput #focusElement="matInput" placeholder="Favorite food" value="Sushi">
```

**Comment by ewaschen** [comment]
@crisbeto Thanks for responding.  Do the Material Docs for `matInput` mention anything about `focusElement` being used instead of the `MatInput ` API. I tried looking around but couldn't find anything,  I found the `ElementRef` on [Angular's Doc Site](https://angular.io/api/core/ElementRef) but it seems like the don't recommend it.

**Comment by crisbeto** [comment]
There's no difference between using the `ElementRef.nativeElement.focus` or `MatInput.focus`, they do the exact same thing under the hood: https://github.com/angular/material2/blob/master/src/lib/input/input.ts#L226.
