### ISSUE TITLE
Progress bar docs example broken

### ISSUE THREAD

**Issue by benlesh** [angular/material2#8747]
#### Bug

Nothing is displayed in the example found here: https://material.angular.io/components/progress-bar/overview

If you try to open the example up in stackblitz, it complains that `app/button-demo.ts` is missing.

#### What is the expected behavior?

An example of the progress bar is shown, and the stackblitz works.

#### What is the current behavior?

No example of the progress bar is shown, and the stackblitz is busted.

#### What are the steps to reproduce?
1. Navigate here: https://material.angular.io/components/progress-spinner/overview
2. Navigate to the Progress Bar using the Side Nav

![screenshot from 2017-11-30 15 57 29](https://user-images.githubusercontent.com/1540597/33461471-77a4de7c-d5e7-11e7-83d5-36b918524b40.png)
![screenshot from 2017-11-30 15 57 46](https://user-images.githubusercontent.com/1540597/33461477-7f880b28-d5e7-11e7-8e90-bfa1d2a93f32.png)

There are errors in the console:

```
main.f16457e80ef23439b7f8.bundle.js:1 MISSING EXAMPLE:  progress-bar-overview
main.f16457e80ef23439b7f8.bundle.js:1 GET https://material.angular.io/assets/example/button-demo.ts 404 ()
u @ main.f16457e80ef23439b7f8.bundle.js:1
e.scheduleTask @ main.f16457e80ef23439b7f8.bundle.js:1

/// ********* SNIP **********

main.f16457e80ef23439b7f8.bundle.js:1 t {_body: "<!doctype html>↵<html>↵  <head>↵    <title>Page No…AAAABJRU5ErkJggg=="/>↵    </a>↵  </body>↵</html>↵", status: 404, ok: false, statusText: "OK", headers: e, …}
```

If you look at the StackBlitz example you see:

![screenshot from 2017-11-30 16 01 26](https://user-images.githubusercontent.com/1540597/33461596-010c7cba-d5e8-11e7-8d35-7800779135ee.png)

#### What is the use-case or motivation for changing an existing behavior?

It would be nice to see an example.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All of them? This seems like a trick question.

#### Is there anything else we should know?

I love you.

**Comment by benlesh** [comment]
@donroyco Ha! This actually looks like it might be related to the bug @jasonaden is currently working on.

I'll update this above, but the *real* steps to reproduce involve:

1. Goto https://material.angular.io/components/progress-spinner/overview
2. Navigate to Progress Bar using the side nav.

**Comment by benlesh** [comment]
Negative, @jasonaden ... this bug is unrelated to the one you're working on, dispatching a resize event did not correct the view.

**Comment by jasonaden** [comment]
Okay. This one might be fixed by [the PR](https://github.com/angular/angular/pull/20719) I was hoping would fix your issue.

**Comment by jelbourn** [comment]
This is a caching issue; visit chrome://serviceworker-internals/ and unregister the worker for material.angular.io. This will clear the service worker cache, which persists through hard refresh.
