### ISSUE TITLE
[Dialog] Example is broken due to autogenerated module

### ISSUE THREAD

**Issue by richardstangl** [angular/material2#8750]
#### Bug, feature request, or proposal:
In the stackblitz for `mat-dialog`, the `dialog-content-example-dialog` component does not use the selector `<dialog-content-example-dialog>` and causes "Error: The selector "dialog-content-example-dialog" did not match any elements at...". Following the example in my own project causes the same error.

When I add the selector to the html, it causes "Unhandled Promise rejection: StaticInjectorError[MatDialogRef]: StaticInjectorError[MatDialogRef]: NullInjectorError: No provider for MatDialogRef! 

#### What is the expected behavior?
No errors when using `mat-dialog` as described in the stackblitz.

#### What is the current behavior?
Errors when following the example.

#### What are the steps to reproduce?
Just open the stackblitz and look at the console.
https://stackblitz.com/angular/dgjvllndexp?file=app%2Fdialog-content-example.html

#### What is the use-case or motivation for changing an existing behavior?
Avoiding errors

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using Angular 5.0.1, Material 5.0.0-rc0, Typescript 2.4.2, latest version of Chrome (Version 62.0.3202.94)

#### Is there anything else we should know?
I'm still learning Angular 2+ and Material2 so I may just be missing something obvious.

**Comment by rodschulz** [comment]
I'm facing the exact same issue.

In order to get the dialog to work it has to be put in the bootstrap section, in the app module declaration. I'm guessing that, since the dialog selector is not explicitly written anywhere, then the error.

**Comment by rodschulz** [comment]
Found a fix for this in [this issue](https://github.com/angular/material.angular.io/issues/137). I tried the solution and it worked for me.

**Comment by amcdnl** [comment]
Fixed here - https://github.com/angular/material.angular.io/pull/356

**Comment by crisbeto** [comment]
Looks like this has been fixed.
