### ISSUE TITLE
[Menu] Item text animates strange when opening

### ISSUE THREAD

**Issue by LosD** [angular/material2#8753]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Menus unfold in stackblitz and own websites as on demo site:
![as it should work](https://user-images.githubusercontent.com/1282832/33476674-174c3858-d683-11e7-8bd9-558837ad1c53.gif)

Menu fully appears before items, making a nice effect

#### What is the current behavior?
Menus unfold in stackblitz and own websites differently than on the demo site:
![as it really works](https://user-images.githubusercontent.com/1282832/33476628-efdc7b52-d682-11e7-9879-c58418d57840.gif)

Items appear at the same time as menu, making a mostly vertically item scale animation, which makes it look rather weird:

#### What are the steps to reproduce?
You provided the reproduction :)
Demo site examples page: https://material.angular.io/components/menu/examples
StackBlitz: https://stackblitz.com/angular/byyklmkxjlg

#### What is the use-case or motivation for changing an existing behavior?
Better animation in actual use. In the given example, it doesn't look that bad, but for a longer menu it looks rather terrible.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.5 with Material 5.0.0-rc0 (don't know TypeScript version or OS. My own site is using TS 2.4.2 on Linux) for behavior on StackBlitz, not sure about demo site. I guess you'd update it to latest version.

Tested using Chrome and Firefox on Linux. Animation seems to be missing in IE and Edge, so for those it's a non-issue.

#### Is there anything else we should know?
If the difference is due to tweaks in the demo site it should probably document how to change the animation, as it is so much better than the default animation.

**Comment by LosD** [comment]
Edited description to add version of Material itself (quite an oversight, sorry about that)

**Comment by LosD** [comment]
It seems the demo site has been updated, and now presents the same horrible animation. Was this on purpose, or is it a side-effect of something else? Anyway, it's a terrible, terrible change.

**Comment by LosD** [comment]
Hmmm... Just realized there were a new release (rc.3), and it seems that fixed it, although I saw no really related changes.

Still doesn't really change that the demo site behavior is different from the released product, but with the lag i noticed before, I'm pretty confident that's simply down to material.angular.io not being updated straight away.

**Comment by LosD** [comment]
That's rather odd. Tried using rc.3 on the stackblitz page, which did _not_ fix it.

Could this be some kind of animation bug, where it depends on other subtle differences?

**Comment by jelbourn** [comment]
I think this might be https://github.com/angular/angular/issues/20946

**Comment by LosD** [comment]
That sounds right, it even mentions the menu issue. Let's close this, I blamed the wrong project :)
