### ISSUE TITLE
Nested Expansion panels keep overflow visible

### ISSUE THREAD

**Issue by Tommatheussen** [angular/material2#8754]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Nested Expansion panels should collapse their content, and set the overflow to hidden.

#### What is the current behavior?
Nested expansion panels collapse their content, but overflow is kept as visible, showing a scrollbar and nasty empty space.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): http://plnkr.co/edit/uVmKf7NTB9ZVUSv2IyGR?p=preview<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.4
Material 5.0.0-rc.2
MacOS
TS 2.4.2
Browser: Seen in Safari, Chrome and Firefox (not tested any others)

#### Is there anything else we should know?
This only seems to be actually noticeable when used inside tabs. Checking the dev tools, I can see the `.mat-expanded` class from the parent causes the child to keep it's overflow visible

**Comment by tarunmp0102** [comment]
It is noticed any where in the page, not necessarily only in tabs

**Comment by bluefire2121** [comment]
#5269

**Comment by josephperrott** [comment]
Fixed by https://github.com/angular/material2/pull/10138
