### ISSUE TITLE
Download CSV matDataTables

### ISSUE THREAD

**Issue by BrianMuhimbura** [angular/material2#8755]
I have failed to find a download csv for matDataTables?

**Comment by andrewseguin** [comment]
Please refer all troubleshooting questions to our community at StackOverflow, Angular Material mailing lists, Gitter, etc. We try to keep our issues here only open for bugs and feature requests.

**Comment by pantonis** [comment]
@BrianMuhimbura I need the same functionality. Did you find a way to achieve this?

**Comment by BrianMuhimbura** [comment]
try https://www.npmjs.com/package/angular5-csv though it was not giving me a header row but the data was coming out fine
