### ISSUE TITLE
Datepicker: expose onClose event.

### ISSUE THREAD

**Issue by clundberg1** [angular/material2#8769]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
To run some code whenever the calendar is closed.

**Comment by torabian** [comment]
What do you mean by run some code when calendar is closed? You can listen to change event instead.

**Comment by clundberg1** [comment]
Yeah but the user can close the calendar without selecting a date.

**Comment by julianobrasil** [comment]
@torabian, take a look até the API docs. You have [@Output('closed')](https://material.angular.io/components/datepicker/api).

**Comment by crisbeto** [comment]
Closing since this is possible through the `closed` event.

**Comment by clundberg1** [comment]
@julianobrasil  you are right, that worked, although the docs don't have that info. Even tried ctrl + f and searching "closed" doesn't return any matches. Thanks anyway.

**Comment by julianobrasil** [comment]
@clundberg1, maybe your browser cache is tricking you. Try clearing it up. Look:

![image](https://user-images.githubusercontent.com/25405143/33530673-61db27c4-d86a-11e7-815f-5f6bbfa948b3.png)
