### ISSUE TITLE
Event not defined - server side rendering 

### ISSUE THREAD

**Issue by mistrynilesh** [angular/material2#8773]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It should run properly on server side rendering 

#### What is the current behavior?
Gives Reference Error: Event is not defined

```
(function (exports, require, module, __filename, __dirname) { !function(t,n){for(var e in n)t[e]=n[e]}(exports,function(t){function n(l){if(e[l])return e[l].exports;var o=e[l]={i:l,l:!1,exports:{}};return t[l].call(o.exports,o,o.exports,n),o.l=!0,o.exports}var e={};return n.m=t,n.c=e,n.d=function(t,e,l){n.o(t,e)||Object.defineProperty(t,e,{configurable:!1,enumerable:!0,get:l})},n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,"a",e),e},n.o=function(t,n){return Object.prototype.hasOwnProperty.call(t,n)},n.p="",n(n.s=0)}({"+239":function(t,n,e){"use strict";function l(t){return g.\u0275vid(0,[(t()(),g.\u0275eld(0,0,null,null,1,"mat-progress-bar",[["aria-valuemax","100"],["aria-valuemin","0"],["class","mat-progress-bar"],["mode","indeterminate"],["role","progressbar"]],[[1,"aria-valuenow",0],[1,"mode",0],[2,"mat-primary",null],[2,"mat-accent",null],[2,"mat-warn",null]],null,null,m.View

ReferenceError: Event is not defined
```

#### What are the steps to reproduce?
Below commands for generating error - 
Step 1 ng build --prod --app 1 --output-hashing none
build successfully c
Step 2 "node server.js" 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "^5.0.2",
    "@angular/cdk": "5.0.0-rc.1",
    "@angular/common": "^5.0.2",
    "@angular/compiler": "^5.0.2",
    "@angular/compiler-cli": "^5.0.2",
    "@angular/core": "^5.0.2",
    "@angular/flex-layout": "2.0.0-beta.10-4905443",
    "@angular/forms": "^5.0.2",
    "@angular/http": "^5.0.2",
    "@angular/material": "5.0.0-rc.1",
    "@angular/platform-browser": "^5.0.2",
    "@angular/platform-browser-dynamic": "^5.0.2",
    "@angular/platform-server": "^5.0.3",
    "@angular/router": "^5.0.2",
    "@nguniversal/express-engine": "^5.0.0-beta.5",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",

#### Is there anything else we should know?
It is works fine with client side rendering.

**Comment by crisbeto** [comment]
Can you post an example of the page that you're trying to render? The stack trace seems to have been cut off.

**Comment by mistrynilesh** [comment]
It is not to any specific page. I am referring -  https://malcoded.com/posts/angular-fundamentals-universal-server-side-rendering. it error comes from main.bundle.js file.

**Comment by jelbourn** [comment]
closing for lack of reproduction information.
