### ISSUE TITLE
highly verbose router links with themed colors

### ISSUE THREAD

**Issue by kylecordes** [angular/material2#8776]
#### Bug, feature request, or proposal:

I'm trying to do a pretty common thing:

* Set of material buttons
* in a material toolbar
* connected to Angular in-the-box router links
* active link visibly differentiated
* ... by coloring it in a theme color, no hard-code
* off-the-shelf theme, avoiding the "make a custom theme" tools

To do this, currently appears rather verbose. Example snippet:

```
<mat-toolbar color="primary">
  <a mat-button 
    #rla1="routerLinkActive" 
    routerLinkActive="active" 
    [color]="rla1.isActive ? 'accent' : ''" 
    [routerLinkActiveOptions]="{exact: true}" 
    routerLink="/overview">Overview</a>
  <a mat-button 
    #rla2="routerLinkActive" 
    routerLinkActive="active" 
    [color]="rla2.isActive ? 'accent' : ''"
    [routerLinkActiveOptions]="{exact: true}"
    routerLink="/detail">Details</a>
  <a mat-button 
    #rla3="routerLinkActive" 
    routerLinkActive="active" 
    [color]="rla3.isActive ? 'accent' : ''"
    [routerLinkActiveOptions]="{exact: true}" 
    routerLink="/assumptions">Assumptions</a>
  <a mat-button 
    #rla4="routerLinkActive"
    routerLinkActive="active"
    [color]="rla4.isActive ? 'accent' : ''" 
    [routerLinkActiveOptions]="{exact: true}" 
    routerLink="/sources">Sources</a>
</mat-toolbar>
```

That's a lot of directives to pile up, and a different template var name to make up for each link, to obtain theme colored active router links.

#### What is the expected behavior?

Well, expected is a strong word. But I was **hoping** for convenience, a out-of-the-box themed material experience, where I would mostly just drop material components in and they would "just work" with both a Material look, and integrate with Angularisms. That these things would know about each other, i.e. router link + material button = right thing happens.

#### What is the current behavior?

The above works, but ouch.

#### What are the steps to reproduce?

I think the snippet above is enough.

#### What is the use-case or motivation for changing an existing behavior?

Concision.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Current Angular + Material.

#### Is there anything else we should know?

...  That this isn't a complaint, is the amount of work it takes to make all the stuff happen boggles the mind.

**Comment by hahn-kev** [comment]
I see what you're going for, but I would just use scss and do this via a class, you'll have to `@include mat-core()` but other than that I think it should be fairly easy, this is the class I use
```scss
.active-link {
  color: mat-color($accent) !important;
}
```

**Comment by kylecordes** [comment]
I just switched to the Sass mechanism, as it seems to be more "official", it is featured prominently in the documentation.

It seems to me that this approach has its own challenges. For each component that needs to access theme-based styling, I'll be creating another Sass file, adding a couple of lines of additional code in the application level theme file to point that Sass file. If I pick up the component and use it elsewhere, I'll be adjusting top-level files for the styling each time. This also is outside the normal Angular scoped CSS, so if I want to control how these things apply I'll need to add more complex selectors. It works; it doesn't "feel very Angular".

I'll keep an eye on future versions to see what emerges, and close this issue as it seems to be working as intended.

**Comment by PimmoZz** [comment]
For any searching this issue check this out: [https://angular.io/api/router/RouterLinkActive](url).
