### ISSUE TITLE
mat-sidenav-container breaks site using safari on macbook (not macbook pro)

### ISSUE THREAD

**Issue by mackelito** [angular/material2#8778]
#### Bug, feature request, or proposal:
Bug
By removing overflow: hidden we see the expected behaviour.

#### What is the expected behavior?
Site should be scrollable/visible

#### What is the current behavior?
https://material.angular.io/ is not scrollable

#### What are the steps to reproduce?
Go to https://material.angular.io with safari on a Macbook.

#### Is there anything else we should know?
Also on our own site the content in mat-sidenav-container is collapsed.
We have verified this problem on 2 separate Macbooks.

**Comment by isurendrasingh** [comment]
It's working absolutely fine in my Macbook @mackelito

**Comment by mackelito** [comment]
@isurendrasingh so scrolling works on https://material.angular.io when using safari on a Macbook for you? This is strange.. tested on a 3:rd this weekend and got the same result..?

**Comment by mackelito** [comment]
@isurendrasingh what version of safari are you using?

**Comment by mackelito** [comment]
@mmalerba have been able to verify this issue? Or I'm just crazy? 😄

**Comment by mmalerba** [comment]
I am not able to reproduce on my macbook. Are you using an older version of Safari? Could you try the dev site as well? Also try clearing your browser cache, the cache settings were messed up at one point so some people have an outdated cached version of the site

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
