### ISSUE TITLE
error TS2305: Module '"/Users/lordofcode/work/PimentFront/node_modules/@angular2-material/radio/radio"' has no exported member 'MdRadioDispatcher'.

### ISSUE THREAD

**Issue by ebenmoha** [angular/material2#878]
I am trying to run angular2 material on the latest release candidate Angular2 rc.4. But this doesn't works as expected. The problem is that some of my packages are using @angular/forms@^0.1.0 while some others uses the version angular/forms@^0.2.0. I am getting this runtime errors when launching npm start:

error TS2305: Module '"/Users/lordofcode/work/PimentFront/node_modules/@angular2-material/radio/radio"' has no exported member 'MdRadioDispatcher'.

**Comment by sceendy** [comment]
use `import {MdUniqueSelectionDispatcher} from '@angular2-material/core/coordination/unique-selection-dispatcher';` instead

**Comment by Dona278** [comment]
@sceendy says correct, but from the source code:
```
// Re-exports.
export {
  MdUniqueSelectionDispatcher
} from '@angular2-material/core/coordination/unique-selection-dispatcher';
```
You can use `MdUniqueSelectionDispatcher` imported from `@angular2-material/radio/radio`

**Comment by ebenmoha** [comment]
This solved my problem. Thanks @sceendy @Dona278 !!!
