### ISSUE TITLE
Missing docs for properties declared in constructor of `Change` classes

### ISSUE THREAD

**Issue by rafaelss95** [angular/material2#8789]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It'd be good to see a description for properties declared by `*Change` classes:

#### What is the current behavior?
There's no description about these properties.

[**Autocomplete**](https://material.angular.io/components/autocomplete/api)
[**Chips**](https://material.angular.io/components/chips/api)
[**Select**](https://material.angular.io/components/select/api)

**Comment by rafaelss95** [comment]
@crisbeto There are some another missing docs, but not related to that are initialized in constructor. Do you want to track them in a separate issue? For reference:

[**Chips**](https://material.angular.io/components/chips/api) - `placeholder`, `empty`, `focus` properties.
[**Expansion Panel**](https://material.angular.io/components/expansion/api) - `panel` property
[**Slide Toggle**](https://material.angular.io/components/slide-toggle/api)
[**Tabs**](https://material.angular.io/components/tabs/api)

**Comment by crisbeto** [comment]
Thanks @rafaelss95, I added to a few more classes. There are some that were documented already, but you either got a cached version of the site or we haven't uploaded yet.
