### ISSUE TITLE
overlay directive

### ISSUE THREAD

**Issue by jmurphzyo** [angular/material2#879]
#### Bug, feature request, or proposal:

bug
#### What is the expected behavior?

n/a
#### What is the current behavior?

Possible typo
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
#### Which versions of Angular, Material, OS, browsers are affected?

Material2 latest
#### Is there anything else we should know?

n/a

I believe there is a typo here https://github.com/angular/material2/blob/master/src/core/overlay/overlay-directives.ts#L91
originX is set to overlayX position. I don't know if that was intended.

**Comment by sendilkumarn** [comment]
Think that should be `originX`

**Comment by karan1276** [comment]
Hey, i am a student and a little new to material 2. I want to become a regular contributor because angular is so awesome :)

I would like to work on this issue, if someone is already working on that please let me know .

Any advice on how to go about it is also appreciated :)

Thank you

**Comment by karan1276** [comment]
@jmurphzyo I can't find anything wrong with the plunker demo. Looks like overlay-lay directive has a typo but did something go wrong because of it?
