### ISSUE TITLE
About removing `| null` from `source` property declaration

### ISSUE THREAD

**Issue by rafaelss95** [angular/material2#8791]
#### Bug, feature request, or proposal:
Maybe a bug.

#### What is the expected behavior?
Just remove `| null` from declaration.

#### What is the current behavior?
Look at these classes:

https://github.com/angular/material2/blob/5210b3e197647381611ec48ddcd99333ec5356e9/src/lib/radio/radio.ts#L62
https://github.com/angular/material2/blob/5210b3e197647381611ec48ddcd99333ec5356e9/src/lib/button-toggle/button-toggle.ts#L57

I don't see how the `source` property of these `events` can be null.

I'm concerned about this because if `--strictNullChecks` is enabled in some application (as it's on mine) and we try to access any property of `source` we can't do this directly, like this:

```
someFunc(matButtonToggleChange: MatButtonToggleChange) {
  matButtonToggleChange.source.<ANY_PROPERTY>;
}
```

... you just received the following error from typescript: 

> Object is possibly 'null'

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.5
Node: 8.1.1
OS: linux x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.5.5
@angular/material-moment-adapter: 5.0.0-rc.2
@angular/material: 5.0.0-rc.2
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript: 2.6.2
webpack: 3.8.1
```

**Comment by rafaelss95** [comment]
@tinayuangao do you agree that these declarations should be changed? Let me know, so I can go ahead and send a PR, if you want.

**Comment by tinayuangao** [comment]
@rafaelss95 Agree these declarations should be changed.
