### ISSUE TITLE
Components in Angular Material 1

### ISSUE THREAD

**Issue by infowaybs** [angular/material2#88]
With due time, do you intend to implement all theme components already implemented in Angular Material 1?

**Comment by msegers** [comment]
I think it would be more interesting right now to get to an alpha state where you can acces generic simple elements. Still checking this repo everyday.

**Comment by fxck** [comment]
soon.tm

**Comment by smkamranqadri** [comment]
can any body provide some link where can we can getting started with angular material 2

**Comment by jelbourn** [comment]
Our "beta" is going to be when there's (nearly) feature parity with the Angular 1 version.

@smkamranqadri We haven't released anything to get started with yet :). We'll be announcing our alpha.0 on Twitter once it's ready, so stay tuned!
