### ISSUE TITLE
Support Side Navigation which locked open for large screen

### ISSUE THREAD

**Issue by divyakumarjain** [angular/material2#881]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Looking at below sidenav implementation for Angular 1.x we can have sidenav which is open for large screen but collapsed for smaller screen. Looking at Angular 1.x API it seems that there is md-is-locked-open which can be used for such use cases.

https://material.angularjs.org/latest/demo/sidenav

Current implementation does not support this. Or Atleast documentation for such implementation is missing.

Tried looking into Side nav design doc at below URL but could not find anything which exists or part of road map.
https://docs.google.com/document/d/1baTbj5OOkUMpwRLDo23sLMVl5ZQtk8-RgpiL2zTuoUk/preview

#### What is the current behavior?

In current Behavior the side bar is opened only on calling open method. Also it collapses when clicked anywhere else.

#### What is the use-case or motivation for changing an existing behavior?
Have an open side nav will allow better utilization of screen estate.

**Comment by jelbourn** [comment]
I believe `mode="side"` is what you're looking for.
