### ISSUE TITLE
demo-app is not runnabe

### ISSUE THREAD

**Issue by e-cloud** [angular/material2#8810]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
we should be able run demo-app without errors on master branch

#### What is the current behavior?
running demo-app prompts a lot of errors and unable to start the server.

#### What are the steps to reproduce?
1. pull the master branch, my current ref is: 0b2757c957f54081b979d85d27175c10f060beef
2. install deps with `yarn`
3. run `yarn demo-app`

#### What is the use-case or motivation for changing an existing behavior?
we should ensure someone who changes the source will also update the demo code to prove its correctness to a certain extent.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
not sure

#### Is there anything else we should know?
I suggest putting the demo-app deployment command into CI scripts. Not for deployment but for testing.

**Comment by e-cloud** [comment]
@crisbeto can you point out the PR number?

**Comment by crisbeto** [comment]
https://github.com/angular/material2/pull/8811 and https://github.com/angular/material2/pull/8824 @e-cloud.
