### ISSUE TITLE
Datepicker Input placeholder showing over wrong inputs

### ISSUE THREAD

**Issue by andresbm05** [angular/material2#8813]
**Bug, feature request, or proposal:**
When using a Datepicker Input with a placeholder, if you insert an invalid date (i.e. "abc") the placeholder keeps showing over the text.

**What is the expected behavior?**
The placeholder should stay up or disapear when any input is on the field

**What is the current behavior?**
The placeholder shows over the text (keeps the mat-form-field-empty class) when the field is filled with invalid dates

**What are the steps to reproduce?**
In the [Angular Material datepicker demo](https://material.angular.io/components/datepicker/overview) if you type on a datepicker input "abc" and unfocus the placeholder shows over the text. However if you go to the stackblitz demo, this is not happening.

**What is the use-case or motivation for changing an existing behavior?**
Placeholders should never be visible over any input

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**
In my project this is happening with Angular 5.0.5 and Angular Material 5.0.0-rc.2

**Is there anything else we should know?**
My browser and project locales are es-ES.

**Comment by s-thoeni** [comment]
duplicate to #8575 which is already merged into master

**Comment by andresbm05** [comment]
Sorry, I searched if anyone else had posted it and couldn't find that one, maybe it is because I was searching for placeholder and not hint. Thanks!
