### ISSUE TITLE
material-moment-adapter not working

### ISSUE THREAD

**Issue by Ornstrias** [angular/material2#8815]
#### Bug, feature request, or proposal:
An error occured because the method fromIso8601is not implemented in the moment-date-adapter.d.ts

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Is there anything else we should know?
I fixed it by adding fromIso8601(iso8601String: string): Moment | null; but the npm install bypass it

**Comment by reggie43** [comment]
You have to upgrade to Angular 5. As it says in the [change notes](https://github.com/angular/material2/blob/master/CHANGELOG.md#500-rc0-cesium-cephalopod-2017-11-06):  

> fromIso8601 method on DateAdapter removed in favor of deserialize

My package.json with working Moment date adaptor:

```
"dependencies": {
    "@angular/animations": "^5.0.5",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/common": "^5.0.5",
    "@angular/compiler": "^5.0.5",
    "@angular/core": "^5.0.5",
    "@angular/flex-layout": "^2.0.0-beta.10-4905443",
    "@angular/forms": "^5.0.5",
    "@angular/http": "^5.0.5",
    "@angular/material": "^5.0.0-rc0",
    "@angular/material-moment-adapter": "github:angular/material2-moment-adapter-builds",
    "@angular/platform-browser": "^5.0.5",
    "@angular/platform-browser-dynamic": "^5.0.5",
    "@angular/platform-server": "^5.0.5",
    "@angular/router": "^5.0.5",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "humps": "^2.0.1",
    "leaflet": "^1.2.0",
    "moment": "^2.19.3",
    "require": "^2.4.20",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  }
```
