### ISSUE TITLE
Docs: strange navigation behaviour

### ISSUE THREAD

**Issue by benelliott** [angular/material2#8818]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Ability to navigate to CDK docs

#### What is the current behavior?
Can't navigate to CDK docs after following specific series of steps

#### What are the steps to reproduce?
Follow these steps:

1. Visit https://material.angular.io
2. Click "Components" in the toolbar
3. Click "Popups & Modals"
4. Click "Dialog"
5. Press the Back button twice
6. Click "CDK" in the toolbar

#### What is the use-case or motivation for changing an existing behavior?
Ability to read docs

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 Chrome Version 62.0.3202.94 (64-bit) / Firefox 57.0 (64-bit) / Windows 10

#### Is there anything else we should know?
Clicking refresh from the Components page makes the CDK link work. This might be a bug in the router?

**Comment by benelliott** [comment]
Actually I forgot to check the console for errors. It looks like some SVG imports are breaking and this in turn breaks the Angular runtime.

```
XML Parsing Error: not well-formed
Location: https://material.angular.io/assets/img/homepage/fastandconsistent.svg
Line Number 1, Column 18:
fastandconsistent.svg:1:18
XML Parsing Error: not well-formed
Location: https://material.angular.io/assets/img/homepage/versatile.svg
Line Number 1, Column 18:
versatile.svg:1:18
XML Parsing Error: not well-formed
Location: https://material.angular.io/assets/img/homepage/optimized.svg
Line Number 1, Column 18:
```

**Comment by benelliott** [comment]
Visiting one of these links makes the XML error very obvious - spaces have been stripped between attributes in the SVG definition.

**Comment by mmalerba** [comment]
Updated the docs site, should be fixed now
