### ISSUE TITLE
md-tab-label cut text instead of enlarge

### ISSUE THREAD

**Issue by Maxouhell** [angular/material2#882]
#### Bug, feature request, or proposal:
Bug / proposal

#### What is the expected behavior?
md-tab-label width must enlarge

#### What is the current behavior?
md-tab-label width is fixed to 160px.

#### What are the steps to reproduce?
http://plnkr.co/edit/wssodcDMuYzsiwllRqTL?p=preview

When the app launch, there is too much labels and some are hidden (arrows to scroll doesn't appear like Material 1, but it's an other problem)
Too long labels are cropped.

#### Which versions of Angular, Material, OS, browsers are affected?
Latest

#### Is there anything else we should know?
I've made a fix by removing `min-width` and add `white-space:nowrap`.
Try to click on 'fix problem' button to see result !

**Comment by robertmesserle** [comment]
This is an issue with pagination.  Pagination is not supported yet, so tabs will shrink when they cannot fit.  This will be fixed when pagination is implemented as the alternative (inaccessible tabs) is not an improvement.
