### ISSUE TITLE
Don't focus on first clickable element when opening a dialog

### ISSUE THREAD

**Issue by BjoernKW** [angular/material2#8823]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When opening a modal dialog (MatDialog) the first clickable element (anchor, input element, button etc.) shouldn't be focused automatically.

#### What is the current behavior?
The first clickable element within a dialog shouldn't be automatically selected when opening that dialog.

#### What are the steps to reproduce?
https://angular-ezhnx3.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
Having the first element selected automatically in most cases isn't the expected behaviour, for example if a modal dialog only contains a "cancel" and a "confirm" button I don't want the "cancel" button (or whichever comes first) to be automatically  focused.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.2
Angular Material 5.0.0-rc0

**Comment by josephperrott** [comment]
Closing as this is working as expected.  You can control the `autoFocus` state using the [`MatDialogConfig`](https://github.com/angular/material2/blob/master/src/lib/dialog/dialog-config.ts#L95)
