### ISSUE TITLE
Layout Documentation

### ISSUE THREAD

**Issue by wilsonsergio2500** [angular/material2#8829]
Greetings

Is there a Layout documentation similar to the material angularjs one but for ng2?
i.e. https://material.angularjs.org/latest/layout/introduction

I was not able to see one 

Thanks in advance

**Comment by ewaschen** [comment]
You can use [Flex-Layout](https://github.com/angular/flex-layout).  There is a decent amount of documentation on the wiki page.

**Comment by CaerusKaru** [comment]
Angular Material is also building out its own layout library (I think the plan is to eventually integrate Flex Layout back into Material). This is part of the CDK, and partial docs can be found [here](https://github.com/angular/material2/blob/master/src/cdk/layout/layout.md). The only similarity right now between this and AngularJS Material Layout, though, is the breakpoint detection.

**Comment by mmalerba** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
