### ISSUE TITLE
[Tabs] RTL animation is broken

### ISSUE THREAD

**Issue by amitport** [angular/material2#8833]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
tabs switch animation in RTL should work in the correct direction:
when pressing a tab on the left, content should swipe-in from left

#### What is the current behavior?
content always swipes from right, and sometimes just appears

#### What are the steps to reproduce?
material demo for 5.0.0-rc.3 
select RTL and switch any tabs

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material 5.0.0-rc.3  (running demo-app)

**Comment by andrewseguin** [comment]
Please re-open with a reproduction in stackblitz or plunker

**Comment by MehdiSaeedifar** [comment]
any progress?

**Comment by baserirasoul** [comment]
we have same problem

**Comment by sahandsamaneh** [comment]
I have the same issue.

**Comment by Eddygn** [comment]
Also, if it helps to locate the issue: 
looks like Chrome and Firefox behave differently, in Chrome the starting animation starts from the right and it looks like the tab stutters, while Firefox has fluid animation.

**Comment by MehdiSaeedifar** [comment]
Is there any plan for future releases?

**Comment by mrdimaan** [comment]
same problem.

**Comment by StavM** [comment]
this issue is still ongoing.
aside for cancelling animation is there a temporary bypass
