### ISSUE TITLE
Set color on disabled mat-checkbox.

### ISSUE THREAD

**Issue by EamonKavanagh** [angular/material2#8853]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
When mat-checkbox has disabled set, I'd like to be able to set the color to "primary", from the material theme. The checkbox should still be 'read only' (e.g., clicking does nothing) but I don't want the color to change.

#### What is the current behavior?
Disabled mat-checkbox elements are automatically 'greyed-out'

#### What is the use-case or motivation for changing an existing behavior?
I have a common component shared across multiple applications and I want the behavior to be the same- a checkbox that is 'read only' but still preserves the applications overall theme.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by jelbourn** [comment]
In this we follow the Material Design spec, which calls for the control to be grayed out. We wouldn't want to add an API to go against the spec in this case.

**Comment by simeyla** [comment]
You might be able to use the method described here:
https://material.angular.io/components/checkbox/overview

    providers: [
       {provide: MAT_CHECKBOX_CLICK_ACTION, useValue: 'noop'}
    ]

This disables the default behavior for click. 
This issue has some examples https://github.com/angular/material2/issues/8890

I have a need for this too to get a 'multi-select' radio button type look, where I want to disallow a selection of zero items.
