### ISSUE TITLE
Missing font style for buttons

### ISSUE THREAD

**Issue by SaturnTeam** [angular/material2#8855]
#### Bug, feature request, or proposal:
Bug
#### What is the current behavior?
![image](https://user-images.githubusercontent.com/10252514/33694848-f61e2dae-db2c-11e7-9221-04fe1aec26c2.png)
left part - website screenshot. right part - my own website with added medium font face

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Ubuntu. 

#### Is there anything else we should know?
It's quite interesting. Material design expects to have medium 500 font weight for buttons https://material.io/guidelines/style/typography.html#typography-styles , but website doesn't have it https://material.angular.io/components/button/overview . 
And may be it's better to break the material rule and use regular 400 font weight?

**Comment by crisbeto** [comment]
The buttons have the correct styling, it's just the docs site that doesn't include all the necessary font weights.

**Comment by SaturnTeam** [comment]
I think it is also missing font config in documentation
