### ISSUE TITLE
SortHeader indicator in an inactive MatTab seems broken

### ISSUE THREAD

**Issue by lacolaco** [angular/material2#8856]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

MatSort works well in MatTab.

#### What is the current behavior?

Broken

![image](https://user-images.githubusercontent.com/1529180/33696596-54902658-db46-11e7-995a-c847286438ca.png)

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

https://stackblitz.com/edit/angular-eaadrn?file=app%2Fsort-overview-example.html

#### What is the use-case or motivation for changing an existing behavior?

I want to put multiple tables in tabs. And they have to accept `sort` input from its parent.

```html
<mat-tab-group>
	<mat-tab label="Table 1">
		<table-cmp [sort]="{id: 'name', start: 'desc'}"></table-cmp>
	</mat-tab>
	<mat-tab label="Table 2">
		<table-cmp [sort]="{id: 'calories', start: 'asc'}"></table-cmp>
	</mat-tab>
</mat-tab-group>
```

I tried to pass inputted `sort` property to `MatSort#sort`. Initial active tab's table is ok, but inactive tab's tables aren't.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5.0
Material 5.0

#### Is there anything else we should know?

#8396 may be related.

**Comment by lacolaco** [comment]
BTW, I think `matSort` directive should accept default sorting configuration...

**Comment by andrewseguin** [comment]
The directive does support a default sort config - use `matSortActive` and `matSortDirection` to signal the current sort.

This issue is related to how Angular sets up content projected elements. You'll need to load the content of the tab asynchronously. See https://github.com/angular/material2/pull/8921 for the PR that will allow this
