### ISSUE TITLE
When disable a mat-button, the button is hided and not disabled.

### ISSUE THREAD

**Issue by Borki** [angular/material2#8859]
#### Bug:
When disabling a button, the button is hide and not just disabled.

#### What is the expected behavior?
When disabling a button, the button is disabled and not hided

#### What is the current behavior?
When disabling a button, the button is hide and not just disabled.

#### What are the steps to reproduce?
<button mat-button  [disabled]="true">
</button>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^5.1.0"
 "@angular/material": "5.0.0-"
"typescript": "~2.4.2"

**Comment by Borki** [comment]
Is working with "@angular/core": "^5.1.0"

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via Plunker.

**Comment by dmaish** [comment]
I've just experienced this issue.
