### ISSUE TITLE
[Table] Stackblitz table example needs new HttpClient

### ISSUE THREAD

**Issue by androidseb25** [angular/material2#8861]
#### Bug, feature request, or proposal:
Hey guys,
in your example on Stackblitz for 'Example Table retrieving data through HTTP', you are using the wrong HTTP Module.

Please use update to HTTPClientModule.

on line 41 use 'import {HttpClientModule} from '@angular/common/http''
and on line 88 use 'HttpClientModule' in the main.ts

Link to the your example: https://stackblitz.com/angular/lvlbdqbdxgr

Greets Sebastian

**Comment by Splaktar** [comment]
This is related to the changes in https://github.com/angular/material2/pull/6702, but I'm not sure which file was not updated or if this is due to some kind of build pipeline issue.

**Comment by andrewseguin** [comment]
They will need to be fixed on material.angular.io - https://github.com/angular/material.angular.io/blob/f775248067ac1076b14fbe5cee3a955f9c4e637e/src/assets/stackblitz/main.ts

**Comment by andrewseguin** [comment]
Fixed here: https://github.com/angular/material.angular.io/pull/352

**Comment by crisbeto** [comment]
Closing since the related PR has been merged.
