### ISSUE TITLE
Nav-Tab ink-bar not showing properly

### ISSUE THREAD

**Issue by FallenRiteMonk** [angular/material2#8863]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Nav-Tab ink-bar should work as in normal tabs.

#### What is the current behavior?
The ink-bar is not displayed except for the last tab. Selecting the first tab (even on fresh load) the ink-bar does not appear until the last tab is selected, then it stays there even when navigating to a differnt tab.

#### What are the steps to reproduce?
[Stackblitz Example](https://stackblitz.com/edit/angular-material2-issue-bts65p?file=app%2Fapp.module.ts)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Currently latest versions. See Stackblitz example.

#### Is there anything else we should know?
When changing the router empty rout redirect to the last tab, the ink-bar also appears as supposed.

**Comment by andrewseguin** [comment]
Your example names three distinct elements as the same template reference `rla`. Try renaming each to `rla1`, `rla2`, `rla3`

https://stackblitz.com/edit/angular-material2-issue-mvhnaw?file=app/app.component.html

**Comment by FallenRiteMonk** [comment]
@andrewseguin Thanks and sorry
