### ISSUE TITLE
Infinite loop when toggle sidenav during animation

### ISSUE THREAD

**Issue by iget-master** [angular/material2#8869]
#### Bug, feature request, or proposal:

Toggling the sidenav menu during animation causes a infinite loop that crashes the browser.

#### What is the expected behavior?

It's expected that the toggle never crash the browser.

#### What is the current behavior?

Toggling sidenav too fast (or during the animation) will cause an infinite loop.

#### What are the steps to reproduce?

It's easy to reproduce, you can use the example given by Material Docs:
https://stackblitz.com/angular/yjjyldrpyyej

Just click it fast, and you will notice that the browser crashes, and throw infinite error messages on console: 

> SidenavOpenCloseExample.ngfactory.js:20 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
>     at viewDebugError (core.umd.js:9845)
>     at expressionChangedAfterItHasBeenCheckedError (core.umd.js:9823)
>     at checkBindingNoChanges (core.umd.js:9992)
>     at checkNoChangesNodeInline (core.umd.js:14044)
>     at checkNoChangesNode (core.umd.js:14016)
>     at debugCheckNoChangesNode (core.umd.js:14845)
>     at debugCheckDirectivesFn (core.umd.js:14747)
>     at Object.eval [as updateDirectives] (SidenavOpenCloseExample.ngfactory.js:118)
>     at Object.debugUpdateDirectives [as updateDirectives] (core.umd.js:14729)
>     at checkNoChangesView (core.umd.js:13854)

Removing the two way binding for sidenav (`[(opened)]="menuOpen"`) workaround the issue, but isn't the fix.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

The latest versions available for everything, I've just installed following documentation.

The browser version is "Versão 62.0.3202.62 (Versão oficial) beta 64 bits"

**Comment by crisbeto** [comment]
Thanks for the report @iget-master, there's a pending fix, but until it gets in you can work around it by changing the two-way binding on `opened` to a one-way binding (`[(opened)]` -> `[opened]`).
