### ISSUE TITLE
[NavBar] Support stretched tabs

### ISSUE THREAD

**Issue by jeremyputeaux** [angular/material2#8871]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
As seen in https://material.io/guidelines/components/tabs.html, tabs should use 100% of horizontal space when they fit and they use label space with arrows when they don't fit.
There used to be a `md-stretch-tabs` that seems to do this but not anymore as seen in https://github.com/angular/material2/issues/5286

#### What is the current behavior?
Currently, tabs are inline but we can't tell the tabs to use all space.

#### What are the steps to reproduce?
https://stackblitz.com/edit/mat-tab-nav-bar-not-using-all-horizontal-space

#### What is the use-case or motivation for changing an existing behavior?
Respecting the guideline. Making an easy way to do it

**Comment by mhosman** [comment]
Arrows not present?
