### ISSUE TITLE
[Checkbox] Expressed changed after checked error when disabling Reactive Form in ngSubmit

### ISSUE THREAD

**Issue by tom5760** [angular/material2#8887]
#### Bug, feature request, or proposal:

Bug?

#### What is the expected behavior?

I want to disable a reactive form in the `(ngSubmit)` method in a component.  A user can hit the `Enter` key when any element of the form is focused to submit the form.  If the user has a `MatCheckbox` focused, and hits `Enter` to submit the form, it should not result in any exceptions.

#### What is the current behavior?

Using the `Enter` key to submit a reactive form, while a `MatCheckbox` is focused results in a `ExpressionChangedAfterItHasBeenCheckedError` if the `(ngSubmit)` handler disables the form with `this.form.disable()`

#### What are the steps to reproduce?

1. Open [the StackBlitz](https://stackblitz.com/edit/angular-x2kyje).
2. Click on the checkbox.
3. With the checkbox focused, hit enter to submit the form.
4. Observe the `ExpressionChangedAfterItHasBeenCheckedError` in the console.

Note, if you click the submit button instead, or comment out the `this.form.disable()` line in the component, no error is thrown.

#### What is the use-case or motivation for changing an existing behavior?

Use-case is to disable the form when submitting to prevent user input while the form's data is being submitted.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

* Angular: 5.1.0
* Material: 5.0.0
* OS: Linux
* TypeScript: 2.5.3
* Browsers: Google Chrome

**Comment by tinayuangao** [comment]
I believe this error is because you changed the form's `disabled` value but the change detection has not run. You could call `changeDetectorRef.detectChanges` after you disable the form.

StackBlitz: https://stackblitz.com/edit/angular-nmnjqf?file=app/app.component.ts
