### ISSUE TITLE
[Checkbox] Improve docs on MatCheckboxClickAction

### ISSUE THREAD

**Issue by jabreu610** [angular/material2#8890]
#### Bug, feature request, or proposal:
Documentation Request

#### What is the expected behavior?
Clearer documentation on how to change the `MatCheckboxClickAction` of a checkbox

#### What is the current behavior?
The current documentation is unhelpful. It is unclear how to alter the default value of `MatCheckboxClickAction`. An example would be helpful.
See [Current Documentation](https://material.angular.io/components/checkbox/overview#click-action-config)

**Comment by hobojoe** [comment]
I've read the PR with the updated docs but still couldn't implement it. Any way it could be updated with a working sample? It would be very helpful. Thanks

**Comment by tschaffter** [comment]
+1

**Comment by tinayuangao** [comment]
A working example on stackblitz:
https://stackblitz.com/edit/angular-zstr9w?file=main.ts

Changing provided value in `providers: [{provide: MAT_CHECKBOX_CLICK_ACTION, useValue: 'check-indeterminate'}]` in `main.ts` will have different results.

**Comment by hobojoe** [comment]
@tinayuangao 
Thanks for the sample provided. I managed to get it working on https://stackblitz.com/edit/angular-zstr9w-tlgtfj?file=app%2Fcheckbox-configurable-example.ts

But it is still not clear how would I apply it to a single checkbox on my component? Should I create an TriState component containing a MatCheckbox component in it? Or is there a better way?

Thanks

**Comment by hobojoe** [comment]
I have implemented it by creating a new component.

Would like to know if it is the correct approach?

Here is an example: https://stackblitz.com/edit/angular-uew4l8

Could anyone assess it? Thanks!

**Comment by tschaffter** [comment]
Thanks @tinayuangao and @hobojoe!

**Comment by simeyla** [comment]
Why can't this just be an option on the checkbox itself :-/
