### ISSUE TITLE
[Datepicker] The year 1985 is missing when Start View is set to "Year"

### ISSUE THREAD

**Issue by TomasAzevedo** [angular/material2#8891]
#### Bug, feature request, or proposal:
Datepicker bug.

#### What is the expected behavior?
See the year 1985 when Start View is set to "Year".

#### What is the current behavior?
The year 1985 is missing when Start View is set to "Year". When I try to navigate the arrows, from the year 1990 to 1985, it is jumping from 1986 to 1984.

#### What are the steps to reproduce?
https://material.angular.io/components/datepicker/overview#setting-the-calendar-starting-view

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.5.0
Node: 8.5.0
OS: win32 x64
Angular: 5.0.2
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/animations: 5.0.4
@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.5.0
@angular/material: 5.0.0-rc.2
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.39
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.9
typescript: 2.4.2
webpack: 3.8.1

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via Plunker.

**Comment by TomasAzevedo** [comment]
This happens in the documentation example (https://material.angular.io/components/datepicker/overview#setting-the-calendar-starting-view). Maybe it's a locale issue.

**Comment by jelbourn** [comment]
The examples there all worked fine when I tried them. If it only happens w/ a certain locale, that would be important
