### ISSUE TITLE
Set a select's value from within the containing expansion panel's opened event

### ISSUE THREAD

**Issue by TimoKunze** [angular/material2#8893]
#### Bug, feature request, or proposal:
Bug. If I set a select's value via Form.controls['myControl'].setValue from within an expansion panel's opened event, the control gets the value, but its visual appearance is as if no value was set.
The expansion panel contains the select.

#### What is the expected behavior?
It should be possible to set a select's value via Form.controls['myControl'].setValue from within an expansion panel's opened event.

#### What is the current behavior?
I call Form.controls['myControl'].setValue from within the expansion panel's opened event to set a contained select's current value. The value is set as can be checked via alert(Form.controls['myControl'].value), but the visual appearance of the select is as if the value was not set.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, Material 5.0.0, Typescript 2.5.3

#### Is there anything else we should know?

**Comment by crisbeto** [comment]
@TimoKunze can you provide a Plunker/Stackblitz that shows the issue? Trying out something similar against our demo app works as expected.

**Comment by TimoKunze** [comment]
So far I can NOT reproduce it with a simple Stackblitz: https://angular-vclwfe.stackblitz.io
I'm still trying to figure out the differences to my app.

**Comment by crisbeto** [comment]
I'm shooting in the dark here, but perhaps you're using `ChangeDetectionStrategy.OnPush` or are running the callback outside the Angular zone?

**Comment by TimoKunze** [comment]
Ah, I've found the problem. It's waaaaay simpler than we thought: I have been calling setValue with an array, but it is no multi-select. Seems like some former release did allow this.
Many thanks for your help!

**Comment by crisbeto** [comment]
Glad to help. Closing as a non-issue.
