### ISSUE TITLE
Incorrect button and toolbar font weight

### ISSUE THREAD

**Issue by aciccarello** [angular/material2#8895]
### Bug report: 
According to the [Material Design Typography spec](https://material.io/guidelines/style/typography.html), buttons and the app bar should have medium font weights. However, if the correct Roboto fonts are included, they appear bold. This does not appear on the Angular Material site because the Roboto 500 font weight is not included.

#### What is the expected behavior?
The button and toolbar typography should have a font weight of 400.

![title with medium font weight](https://user-images.githubusercontent.com/34315847/33685515-b7d4086c-da86-11e7-8999-c0059ce842dc.png)

![button with medium font weight](https://user-images.githubusercontent.com/34315847/33685529-c2a249fc-da86-11e7-84e3-cce2d3bf888e.png)

#### What is the current behavior?
The button and toolbar font weight is set to 500

![title with bold font weight](https://user-images.githubusercontent.com/34315847/33685495-a33330ae-da86-11e7-9d98-1eac8bf97db0.png)

![button with bold font weight](https://user-images.githubusercontent.com/34315847/33685540-ce410e10-da86-11e7-832b-513839678b4b.png)

#### What are the steps to reproduce?

1. Create an app that uses the toolbar and buttons (see [StackBlitz starter](https://goo.gl/wwnhMV))
2. Include the Roboto font weights in index.html
`<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">`

#### What is the use-case or motivation for changing an existing behavior?
To align with material spec.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular: 5.0.0
material: 5.0.0

#### Is there anything else we should know?
Downstream issue Teradata/covalent#1012

**Comment by crisbeto** [comment]
500 is the medium font weight. Google Fonts for reference:

![https://i.imgur.com/bBCmGvl.png](https://i.imgur.com/bBCmGvl.png)

**Comment by kyleledbetter** [comment]
@andrewseguin I see you closed the issue, but the official Material Design site and Polymer paper toolbar use font-weight:400 for toolbars

https://material.io/guidelines/components/toolbars.html
![image](https://user-images.githubusercontent.com/867883/33911099-08516c6c-df46-11e7-94ca-01b763c8d7b5.png)


https://www.webcomponents.org/element/PolymerElements/paper-toolbar/demo/demo/index.html
![image](https://user-images.githubusercontent.com/867883/33911127-1d9ae7a6-df46-11e7-9803-97f9528a8aac.png)

Are those two wrong?

Also, the Angular Material site isn't even loading the 500 weight, it uses `<link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono:300" rel="stylesheet">` which has the appearance of 400
![image](https://user-images.githubusercontent.com/867883/33911166-4c942c34-df46-11e7-84f5-e4313f0209a4.png)

Is that wrong as well?

**Comment by andrewseguin** [comment]
Apologies - read the thread incorrectly, re-opening for investigation

**Comment by crisbeto** [comment]
@kyleledbetter I think that this is open to interpretation since there are to exact values in the mockups. While the official site does use 400 for the toolbar, MDC, which is the Material implementation that they're linking to, [uses 500 as a font weight](https://material-components-web.appspot.com/toolbar/index.html). Closing the issue for now, but we can keep the discussion going.

**Comment by kyleledbetter** [comment]
@crisbeto fair points, the thing that's driving me nuts is that 500 in MDC's toolbar is rendering differently than 500 in Angular Material's toolbar... but i can't figure out why

¯\_(ツ)_/¯ i'll keep researching
