### ISSUE TITLE
AriaDescriber.ngOnDestory() make SSR 500 error.

### ISSUE THREAD

**Issue by leo6104** [angular/material2#8901]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
AriaDescriber should not throw error.

#### What is the current behavior?
In Universal http request, sometimes server.js throw Error like this.
```
{ NOT_FOUND_ERR: NOT_FOUND_ERR (8): the object can not be found here
0|pc |     at Object.exports.NotFoundError (/var/app/current/server.js:24856:44)
0|pc |     at HTMLBodyElement.removeChild (/var/app/current/server.js:25244:44)
0|pc |     at AriaDescriber._deleteMessagesContainer (/var/app/current/server.js:36328:29)
0|pc |     at AriaDescriber.ngOnDestroy (/var/app/current/server.js:36260:18)
0|pc |     at callNgModuleLifecycle (/var/app/current/server.js:11290:26)
0|pc |     at NgModuleRef_.destroy (/var/app/current/server.js:12468:9)
0|pc |     at /var/app/current/server.js:5961:73
0|pc |     at Array.forEach (<anonymous>)
0|pc |     at PlatformRef.destroy (/var/app/current/server.js:5961:31)
0|pc |     at /var/app/current/server.js:128246:22
0|pc |     at ZoneDelegate.invoke (/var/app/current/server.js:119147:26)
0|pc |     at Zone.run (/var/app/current/server.js:118897:43)
0|pc |     at /var/app/current/server.js:119628:57
0|pc |     at ZoneDelegate.invokeTask (/var/app/current/server.js:119180:31)
0|pc |     at Zone.runTask (/var/app/current/server.js:118947:47)
0|pc |     at drainMicroTaskQueue (/var/app/current/server.js:119357:35)
0|pc |     at ZoneTask.invokeTask (/var/app/current/server.js:119258:21)
0|pc |     at ZoneTask.invoke (/var/app/current/server.js:119243:48)
0|pc |     at data.args.(anonymous function) (/var/app/current/server.js:119936:25)
0|pc |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
0|pc |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
0|pc |   code: 8,
```

#### What are the steps to reproduce?
Sorry for not providing reproduction. It occur not always. (intermittently occur)

#### What is the use-case or motivation for changing an existing behavior?
It is regression issue because this 500 error seen after angular material upgrade

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.1.0
Material 5.0.0 latest

#### Is there anything else we should know?
I think https://github.com/angular/material2/commit/f6cb2c69e306dad2fd0848bc725947083c48e4ba#diff-1f285a8492b86390f8e4fe94cf69d7e6R147
This refactor commit ( @crisbeto ) might be the root cause. 

Please check for this.. @crisbeto I have to solve this problem for our company's production website.

**Comment by leo6104** [comment]
It is regression issue. after 5.0.0-rc.1 , this issue exists.

**Comment by crisbeto** [comment]
@leo6104 I wasn't able to reproduce it by injecting the describer, adding a message and then destroying it manually. Looking at your stack trace it seems as if the describer is being removed multiple times. I've submitted a PR with some extra checks around it.

**Comment by leo6104** [comment]
@crisbeto thank you for pull request!! 
Is there any rule (only import from root module?) for import MatTooltipModule (The only module using AriaDescriber) ? 

In my project,
AppModule imports ProfileModule, PostModule, MatTooltipModule
ProfileModule import MatTooltipModule
PostModule import MatTooltipModule.

I think multiple times remove can be occur like this scenario 
(PostModule destroy -> messagesContainer removed, AppModule destroy -> throw 500 error because already removed)
(ProfileModule destroy -> messagesContainer removed, AppModule destroy -> throw 500 error because already removed)

**Comment by leo6104** [comment]
I tried to remove MatTooltipModule in AppModule, only import in ProfileModule but still throw error.

**Comment by leo6104** [comment]
Remove MatTooltipModule from PostModule is temporary solution for me. (import MatTooltipModule one time)
Multiple times import MatTooltipModule is the cause of this issue.
