### ISSUE TITLE
mat-tab-header-pagination displaying incorrectly

### ISSUE THREAD

**Issue by michaelb-01** [angular/material2#8907]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
mat-tab-header-pagination should only be displayed when the tabs cannot fit inside the container.

#### What is the current behavior?
the mat-tab-header-pagination arrows are being displayed even though there is enough space. When I click on a tab the tabs then resize and the arrows disappear..

#### What are the steps to reproduce?
http://plnkr.co/edit/hX9uSOsFFas3ZnSyKprU?p=info

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular: 5.0.0
material: ^5.0.0-rc.2
typescript: ~2.4.2
chrome

**Comment by julianobrasil** [comment]
The example plunk you've posted seems to be working fine over here. Am I missing something in your description?

**Comment by michaelb-01** [comment]
Thats strange, still doesn't work for me.. I've attached two screenshots below. the first is how it loads for me - incorrectly, with the arrows. Then once I click on a tab the arrows disappear and it resizes and displays correctly..

<img width="229" alt="screen shot 2017-12-09 at 13 56 57" src="https://user-images.githubusercontent.com/3755633/33803558-27619a80-dd8b-11e7-942f-72906679ec07.png">
<img width="212" alt="screen shot 2017-12-09 at 13 57 15" src="https://user-images.githubusercontent.com/3755633/33803560-2b89189a-dd8b-11e7-94f5-629844df5ae1.png">

**Comment by julianobrasil** [comment]
I tested it in a Windows 10 + Chrome.

**Comment by andrewseguin** [comment]
Looks like you are overriding styles somewhere - the padding in your screenshots don't match what is shown in the plunker example. Please re-open with the included styles that you are using so we can fully reproduce

**Comment by michaelb-01** [comment]
@julianobrasil is that the correct functionality? Thats similar to what i'm getting and it doesn't seem right to me.. How do I get the tabs to fill the width of their container (without overflowing horizontally)?

**Comment by andrewseguin** [comment]
It's actually supported with a built-in attribute but it is undocumented.

On the `<mat-tab-group>` element, apply the `mat-stretch-tabs` attribute and the labels will stretch to fill the container.

Example:
http://plnkr.co/edit/Y8KwgieJYQs5UR2pwc5j?p=preview

**Comment by julianobrasil** [comment]
@michaelb-01, I'm a little bit confused... what do you mean by "container"? You set up a `.form-container` class to be just 250px width. With this so tiny width, the paging arrows are unavoidable, even if you use the currently undocument feature mentioned by @andrewseguin. But the pagination will disapear if you get rid of `width: 250px` in `app.component.css` (now, considering that the `form-container` can fulfill all the available plunk space):

![image](https://user-images.githubusercontent.com/25405143/33860228-dad95790-debe-11e7-8420-767929844311.png)

**Comment by michaelb-01** [comment]
I know 250px is fairly small but i'm using this for (a relatively thin) sidenav and I only have 3 tabs (which are icons) so they should be able to fit..

I see there's a minimum width of 160px on the tabs and 24px of padding on the left and right, is this necessary if you're using flex? Wouldn't it be more flexible to remove this and let flex do the work?

**Comment by michaelb-01** [comment]
I never received a good answer for this. My work around is just to override the styles:

```
.mat-tab-label {
  min-width: 20px !important;
  flex: 1 !important;
  padding: 0 !important;
}
```

Which is fine but it would be nice if there was a 'dense' attribute so you can use tabs in small elements like sidenavs. Like I said before, is the min-width necessary? Can't it be set lower flex set to 1?

**Comment by tomasznastaly** [comment]
any info? there is still this bug

**Comment by Digital-Chen** [comment]
I am having the exact issue in my solution. This is very strange behavior.

**Comment by Digital-Chen** [comment]
I am having the exact same issue in my solution. This is really strange.

**Comment by YassineBouayedd** [comment]
I'm also searching for a solution for this issue.

**Comment by jos1337** [comment]
any info? happens here aswell
