### ISSUE TITLE
Can't bind to 'mat-dialog-close' since it isn't a known property of 'button'.

### ISSUE THREAD

**Issue by orenAzuz** [angular/material2#8911]
#### Bug, feature request, or proposal:
Hi, I'm trying to work with a tutorial about modal in angular 5 -> https://material.angular.io/components/dialog/overview
 and it's not working it giving me the error
Can't bind to 'mat-dialog-close' since it isn't a known property of 'button'.

here is my HTML code:

<h1 mat-dialog-title>Warning</h1>
<div mat-dialog-content>
  <p>Are you sure you want to delete the book {{data.title}} ?</p>

<div mat-dialog-actions>
	<button type="button" mat-button [mat-dialog-close]="data.ok " tabindex="2">Ok</button>
  <button mat-button (click)="onNoClick()" tabindex="-1">No Thanks</button>
</div>
  
</div>

thanks.

**Comment by ArchangelX360** [comment]
Did you import the `MatDialogModule` ?

**Comment by orenAzuz** [comment]
WOW!!! that was the problem thank you very very much!! :)

**Comment by ArchangelX360** [comment]
I think you can close the issue as it is not Angular Material's fault ;).

**Comment by simeyla** [comment]
If you're opening a dialog with `dialog.open` in one module and your control is defined in another you must add the Dialog module import to both modules. 

This is very easy to forget, and the dialog *will* open - it's just that then all dialog directives (including mat-dialog-actions / mat-dialog-title and mat-dialog-content will not work).
