### ISSUE TITLE
Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by igsm** [angular/material2#8912]
I am trying to make custom theme working, but after I add theme.scss to the styles list in the angular-cli.json (as suggested in [docs](https://material.angular.io/guide/theming#defining-a-custom-theme)) and then start the project, I get the following error:

**Module build failed: Error: Cannot find module 'node-sass'**

I can't figure out what causes this issue. 

P.S. I installed the latest Angular Material version 5.0.0

**Comment by julianobrasil** [comment]
Have you deleted `package.json.lock` before `npm install`? I had some headaches sometime ago because of this. Also delete `node_modules` before `npm install`.

**Comment by igsm** [comment]
@julianobrasil yes, I messed up with node and npm. It gave me really a lot of headache. I had to delete all traces of node and npm and install it again with brew. After that everything works fine.

**Comment by raydacosta** [comment]
Senhores, só para ver se agrega ai para voces. Depois de executar os comandos abaixo FUNCIONOU! Usando Ubuntu

```
sudo -s
sudo npm cache verify
sudo rm package-lock.json
sudo rm -rf node_modules
sudo npm install
sudo npm install node-sass
```

**Comment by ssalazar7** [comment]
Tuve el mismo problema con las siguientes versiones node v10.15.3 y npm 6.4.1 
1.Deberá ubicarse en la ruta del proyecto angular
2.Ejecutar los siguientes conmandos :
npm cache verify
rm package-lock.json
3.Se debe eliminar la carpeta node_modules completa en caso de que ya exista
4.Ejecutar los siguientes conmandos :
npm install
npm install node-sass
