### ISSUE TITLE
bug(build): nightly build not publishing for material

### ISSUE THREAD

**Issue by CaerusKaru** [angular/material2#8913]
#### Bug, feature request, or proposal:

The nightly builds are not getting updated for material, but they are getting updated for the cdk

#### What is the expected behavior?

Both packages should be updated on the nightly build with each commit

#### What is the current behavior?

Nightly builds are not being published for material2

#### What are the steps to reproduce?

`npm i angular/material2-builds`

**Comment by DevVersion** [comment]
Thanks. I already noticed that a few days ago, and we are still trying to figure out what causes the Git process to throw this error:

`fatal: cannot lock ref 'HEAD': unable to resolve reference 'refs/heads/master': reference broken`

**Comment by DevVersion** [comment]
Should be fixed by 898cded17a980160682ef19e69203ff530514186

**Comment by CaerusKaru** [comment]
@DevVersion should this be reopened?
