### ISSUE TITLE
Tepmlate Parse Error: 'mat-accordian' is not a known element

### ISSUE THREAD

**Issue by DragoTechInnovations** [angular/material2#8917]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-accordian should have been imported automatically when i have imported `MatExpansionModule`

#### What is the current behavior?
Give the error

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Documentation or something for **version 2.0** should still be available.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, Material 2.0.0-beta.12, Windows, TS 2.4

#### Is there anything else we should know?
I have imported MatExpansionModule via import and included it in imports array.

**Comment by crisbeto** [comment]
The element is called `mat-accordion`.

**Comment by DragoTechInnovations** [comment]
I know its called mat-accordion. But angular isnt recognizing it.

**Comment by crisbeto** [comment]
Based on your error message, it looks like you spelled it `mat-accordian`.

**Comment by DragoTechInnovations** [comment]
This is a little embarrassing.
Thanks.

**Comment by DragoTechInnovations** [comment]
BTW where are material 2 documents?

**Comment by crisbeto** [comment]
https://material.angular.io/

**Comment by DragoTechInnovations** [comment]
These have updated documents for material 5 as most of the imports are different. Well, I'll comb through them when required. If there was something like what angular docs have, it would have been great.

Thanks for helping out.

**Comment by sebastienricher** [comment]
Yes, I'm using 2.0.0-beta.12, any way to get access to that version of the documentation?
