### ISSUE TITLE
Can't register material icons

### ISSUE THREAD

**Issue by romelgomez** [angular/material2#8922]
#### Bug, feature request, or proposal:

Bug Report

I'm using the last version of Angular CLI 1.6.0-rc.2, 
and fork of https://material.angular.io/components/icon/overview

and I can't register material icons properly 

#### What is the expected behavior?

Icons are showing properly 

#### What is the current behavior?

Icons aren't showing properly 

#### What are the steps to reproduce?

- https://stackblitz.com/edit/angular-register-material-icons
- ***Angular CLI - Issue example:*** https://github.com/romelgomez/register-material-icons

#### What is the use-case or motivation for changing an existing behavior?

Get the project working

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

 Angular CLI 1.6.0-rc.2

**Comment by Chan4077** [comment]
That's because you're not using the `svgIcon` property of `<mat-icon>`. Here's an example usage:
```html
<mat-icon svgIcon="github"></mat-icon>
<!-- Or namespaces: -->
<mat-icon svgIcon="myNamespace:facebook"></mat-icon>
```

**Comment by romelgomez** [comment]
Thank you, that was what was missing.
