### ISSUE TITLE
[Select] Scrolling causes options to scroll away

### ISSUE THREAD

**Issue by taysonvo** [angular/material2#8924]
#### Bug, feature request, or proposal:
![image](https://user-images.githubusercontent.com/22664803/33829390-9e1337e8-dea2-11e7-9780-b79d636a0546.png)

#### What is the expected behavior?
It should scroll but should inside the content.

#### What is the current behavior?
Running out of the content, PSA.

#### What are the steps to reproduce?
0. go to: https://material.angular.io/components/select/examples
1. Just click on the arrow to dropped down the Options.
2. Use mouse and scroll down the page and see the Options running out of the content.

**Comment by andrewseguin** [comment]
Cannot reproduce - scrolling doesn't work with the mousewheel and clicking on the scrollbar makes the options disappear. What OS are you using?

**Comment by taysonvo** [comment]
Hi @andrewseguin,
Im using Firefox browser on Windows 10.

**Comment by expectpin** [comment]
Same here. Using Firefox 57.0.2 on Windows 7.

**Comment by crisbeto** [comment]
I managed to reproduce it now as well. It looks like Firefox doesn't block the scroll event for overlays with a transparent background.
