### ISSUE TITLE
Mat-paginator does not have page links.

### ISSUE THREAD

**Issue by imchaitanya9** [angular/material2#8925]
<img width="208" alt="screen shot 2017-12-11 at 5 14 29 pm" src="https://user-images.githubusercontent.com/5866730/33829551-c9eac838-de96-11e7-84b4-99edb459d97f.png">

Mat-paginator doesn't have page links like above image. If it has then please give a proper example for implementing it.

**Comment by jotatoledo** [comment]
The page elements arent binded to a navigation logic. Thats why they arent "page links". You can handle the pagination event and implement some navigation logic yourself.

**Comment by andrewseguin** [comment]
Please refer all troubleshooting questions to our community at StackOverflow, Angular Material mailing lists, Gitter, etc. We try to keep our issues here only open for bugs and feature requests.

If you want to make a feature request, please follow the provided template
