### ISSUE TITLE
[Select] Placeholder not removed after selected entry

### ISSUE THREAD

**Issue by jstolz** [angular/material2#8931]
#### Bug, feature request, or proposal:
After I select a value, the selected content is displayed "over" the placeholder content

#### What is the expected behavior?
The placeholder content should be removed or invisible.

#### What is the current behavior?
![placeholder](https://user-images.githubusercontent.com/7976964/33835938-51c08b94-de88-11e7-81b4-d3502bdb6305.PNG)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/core": "^5.1.0",
    "@angular/flex-layout": "^2.0.0-beta.10-4905443",
    "@angular/forms": "^5.1.0",
    "@angular/http": "^5.1.0",
    "@angular/material": "^5.0.0",
    "@angular/platform-browser": "^5.1.0",

    "ts-loader": "^2.0.3",
    "typescript": "^2.6.1",

Windows10, Chrome, Firefox

#### Is there anything else we should know?
html
<h3 mat-dialog-title>Send OneSignal message</h3>
  <div mat-dialog-content>
  <mat-form-field>
    <mat-select placeholder="OneSignal" [(ngModel)]="oneSignalAppId" name="item">
      <mat-option *ngFor="let item of oneSignalAppIds" [value]=item>{{item.viewValue}}</mat-option>
    </mat-select>
  </mat-form-field>

  <mat-form-field>
    <mat-select placeholder="Select player_id" [(ngModel)]="oneSignalPlayerId">
      <mat-option *ngFor="let item of oneSignalPlayerIds" [value]=item>{{item.viewValue}}</mat-option>
    </mat-select>
  </mat-form-field>
  <hr>

  <button mat-raised-button (click)="onSendData()">SendIntern</button>
</div>
<div mat-dialog-actions>
  <button mat-raised-button (click)="onSaveData()" [mat-dialog-close]="data">Save and exit</button>
  <button mat-raised-button (click)="onNoClick()" tabindex="-1">Cancel</button>
</div>

**Comment by crisbeto** [comment]
Can you post an example that shows the issue?

**Comment by andrewseguin** [comment]
Please reopen the issue with a plunker or stackblitz reproduction
