### ISSUE TITLE
Include selectable demo for table component

### ISSUE THREAD

**Issue by crutchcorn** [angular/material2#8935]
#### Bug, feature request, or proposal:
Feature request (of sorts)

#### What is the expected behavior?
It would be nice to have a datatable example that has checkboxes on each row that follows spec for checkboxed datatables https://material.io/guidelines/components/data-tables.html#data-tables-interaction

#### What is the use-case or motivation for changing an existing behavior?
I'm sure many projects that use datatable would like to include such a component type in their codebase. Including one could save development time for those projects

**Comment by crutchcorn** [comment]
Seems as there's already a working demo here:
`https://github.com/angular/material2/tree/master/src/demo-app/table`

But it still might be nice to have on material.angular.io all the same

**Comment by andrewseguin** [comment]
Agreed - the new docs for the table have this included. https://github.com/angular/material2/pull/8770/files

Closing since it's already merged in, should be in early this week
