### ISSUE TITLE
bug(form-field): typography font-size is not used

### ISSUE THREAD

**Issue by benb7760** [angular/material2#8939]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
The font-size of form-fields should be set by typography and default to 16px as per material spec

#### What is the current behavior?
The font-size for form fields is 'inherit'

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
5.0.0

#### Is there anything else we should know?
Looking through the code, I find no usage of the 'input' theme config in any of the form fields or controls that reference the font-size. I do see that the 'input' config is used for font-weight and line-height

**Comment by benb7760** [comment]
Possibly related to #5154 where the size was changed from 'inherit' to '16px' in the config, but then ignored in the theme

**Comment by DevVersion** [comment]
The font-size has been set to `inherit` to avoid any breaking changes in https://github.com/angular/material2/commit/92d8368aea5e236524654015c4016dff93a5c614. We might be able to change that now and publish it in the next major version? cc. @crisbeto

**Comment by crisbeto** [comment]
This was discussed in some other issues together with @mmalerba. Using `inherit` was deliberate since we wanted it to inherit the same font size as whatever other components are around the form field. @benb7760 if you want it to use the size from the typography config, you can throw this somewhere in your SCSS:

```
.mat-form-field {
  font-size: mat-font-size($typography-config, input);
}
```

**Comment by benb7760** [comment]
@crisbeto makes sense, thanks - I had already done so! Is this something worth documenting somewhere?

**Comment by srix55** [comment]
The current behavior (inheriting) is not obvious at all. I had set mat-typography with themes & was expecting my form inputs to remain consistent throughout the site irrespective of other elements used around. In my opinion, the typography font-size set at the root level is expected to remain consistent unless explicitly changed at the component level (like how the other typography settings like font-family behave). The current behavior, although deliberate, really feels like a bug.
