### ISSUE TITLE
[table] Allow columns to be hidden

### ISSUE THREAD

**Issue by crutchcorn** [angular/material2#8944]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
It would be nice to change `cdkColumnDef` to `null` or `undefined` programmatically to remove the column from the table

#### What is the current behavior?
Nothing occurs when you change the `mat-header` or `mat-cell` in `mat-table`.

#### What are the steps to reproduce?
https://stackblitz.com/edit/material2-hide-columns

#### What is the use-case or motivation for changing an existing behavior?
This would allow me to write a generalized component for hiding sections of the datatable for certain screen sizes, allowing mobile data-tables to be better

**Comment by jelbourn** [comment]
The columns displayed are set on the row def so you always have control over which ones are showing.

**Comment by crutchcorn** [comment]
Can you show me what you mean? The StackBlitz that I included was the only way I could see of doing this, and it didn't work as I expected.

**Comment by benb7760** [comment]
@crutchcorn your class variable `displayColumns` is only set when you are initialising the class, and not getting updated when you call test. You could either update your test method to update `displayedColumns` or you could change it to a get accessor

`get displayedColumns() { return this.columns.map(c => c.columnDef); }`

**Comment by crutchcorn** [comment]
I'm incredibly dumb. Thank you @benb7760

**Comment by yeshwanthmn** [comment]
That demo has been expired. Can u update it
