### ISSUE TITLE
Spacing of vertical stepper is too much

### ISSUE THREAD

**Issue by Goodwine** [angular/material2#8947]
#### Bug, feature request, or proposal:
Spacing of vertical stepper is too much, and it's more noticeable when using a `<p>` tag.
This is even more noticeable on the last step.

#### What is the expected behavior?
Content should be closer.

#### What is the current behavior?
Content is so far that it doesn't even look like part of the stepper.

#### What are the steps to reproduce?
https://angular-5zj5lo-s4i1kq.stackblitz.io
Look at the spacing of the text against the step label, specially the last step.

#### What is the use-case or motivation for changing an existing behavior?
Content is so far that it doesn't even look like part of the stepper. It just looks wrong.

**Comment by julianobrasil** [comment]
Your link to stackblitz is broken.

**Comment by Goodwine** [comment]
@mmalerba

**Comment by mmalerba** [comment]
The step content appears to start at the correct position according to the mocks: https://material.io/guidelines/components/steppers.html#steppers-usage

The reason you're seeing additional space is because the `<p>` tag has top margin by default. You can remove it with CSS.
