### ISSUE TITLE
[Docs] Missing icon-svg-example and snack-bar-component-example.css files

### ISSUE THREAD

**Issue by rafaelss95** [angular/material2#8949]
#### Bug, feature request, or proposal:
Bug.

#### What is the current behavior?
Files are missing in the related examples.

#### What are the steps to reproduce?
1 - Go to [**Icon examples**](https://material.angular.io/components/icon/examples);
2 - Check your console;
2.1 - You got two 404 because the files `icon-svg/icon-svg-example.css` and `icon-svg/icon-svg-example.ts` are missing.

**Notes:**
1. Apparently the folder [**icon-svg-example**](https://github.com/angular/material2/tree/master/src/material-examples/icon-svg-example) is suffixed by `-example` and the example itself tries to get the files from `icon-svg` instead of `icon-svg-example`. Out of curiosity, why this is the only folder that is suffixed?
2. The `css` file is missing.

<hr>

1 - Go to [**SnackBar examples**](https://material.angular.io/components/snack-bar/examples);
2 - Check your console;
2.1 - You got a 404 because the file `snack-bar-component-example.css` is missing.

**Comment by DevVersion** [comment]
Just tried to reproduce that issue after #9100 again, but I can confirm, that it's fixed now.

cc. @mmalerba for https://github.com/angular/material.angular.io/pull/360 (fixing the fetch-assets script)

**Comment by rafaelss95** [comment]
Hey @DevVersion, have you already pushed a version with this fix?

I just noticed a new error today:

Go to https://material.angular.io/assets/img/components/form-field.svg and check console:

> GET https://material.angular.io/assets/img/components/form-field.svg 404 ()

**Comment by DevVersion** [comment]
@rafaelss95 The changes should be not reflected by the docs yet. As soon as there is a new release, a new version of the docs will be deployed.

**Comment by rafaelss95** [comment]
Just to clarify: the problem here is that it always try to get the `svg` for a category/component, however not all categories/components have svg icons as you can see in `https://github.com/angular/material.angular.io/tree/master/src/assets/img/` folder.

Anyway, let's wait for new version. Thanks @DevVersion.

**Comment by TarasKovalenko** [comment]
On the `https://material.angular.io/components/categories/forms`
I see the error regarding missing icon for `form-field.svg`.
@devversion can you please take a look?
Thanks.

![image](https://user-images.githubusercontent.com/2806803/52199426-b46bfb80-286e-11e9-80e0-7da7b4c8c304.png)
