### ISSUE TITLE
[Sort] Nested objects not sorted correctly

### ISSUE THREAD

**Issue by tarekabdallah** [angular/material2#8951]
#### Bug, feature request, or proposal:

proposal
#### What is the expected behavior?
sort correctly

#### What is the current behavior?

not sorting correctly

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

Whenever i am sorting the table according to a column and the value of the column is from a nested object (i.e. student.person.name). The sorting is not done correctly.

#### What is the use-case or motivation for changing an existing behavior?
Having better sorting results since most of objects have nested objects.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular 5
material: 5.0.0-rc0
OS: macOS Sierra 10.12.6
Typescript: 2.4.2
Browser :Google chrome 62.0.3202.94

**Comment by willshowell** [comment]
I assume you are using `MatTableDataSource`? Take a look at using the `sortingDataAccessor`.

**Comment by andrewseguin** [comment]
Sorting implementation is up to the user for customization

**Comment by jackrvaughan** [comment]
For anyone else who comes across this: https://stackoverflow.com/a/49295994/6828447
