### ISSUE TITLE
Unable to upgrade to latest version, due to flex-layout dependency

### ISSUE THREAD

**Issue by afriedma** [angular/material2#8956]
#### Bug, feature request, or proposal:
flex-layout project, still hasn't released a version to support angular 5

#### What is the expected behavior?
Since flex-layout is official library of the material, there should be a coordination between the teams and versions should always be in sync.

#### What is the current behavior?
npm conflicts during the install of the latest material version

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

npm install flex-layout
nmp install @angular/material

#### What is the use-case or motivation for changing an existing behavior?
smooth version upgrade

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 5.0.01

**Comment by andrewseguin** [comment]
Please open an issue on flex-layout about their library upgrading. Material will stay in step with Angular

**Comment by afriedma** [comment]
I did open the issue with them, for some reason its not considered critical to them.
I thought may be you can help to engage them.
