### ISSUE TITLE
md-input padding does not affect underline

### ISSUE THREAD

**Issue by maciejsobala** [angular/material2#896]
#### Bug, feature request, or proposal:

bug
#### What is the expected behavior?

Underline should be affected
#### What is the current behavior?

setting padding for md-input doesn't affect underline
#### What are the steps to reproduce?

http://plnkr.co/edit/Jl20dtBLH8hILAahubzu?p=preview
#### Which versions of Angular, Material, OS, browsers are affected?

"@angular2-material/core": "^2.0.0-alpha.6",
"@angular/core": "2.0.0-rc.4",
#### Is there anything else we should know?

Fix: 
change .md-input-underline position from absolute to relative

**Comment by hansl** [comment]
Hi @maciejsobala, it seems like you're trying to add spacing around the input itself. You should use `margin` instead of `padding` in this case. Changing padding inside the input is not supported.
