### ISSUE TITLE
Issue with matDatepicker

### ISSUE THREAD

**Issue by aleppos** [angular/material2#8961]
#### Bug, feature request, or proposal:
I have the template like this
          <mat-form-field>
            <input #dataInput matInput [matDatepicker]="data" placeholder="Data">
            <mat-datepicker-toggle matSuffix [for]="data"></mat-datepicker-toggle>
            <mat-datepicker #data touchUi="true"></mat-datepicker>
          </mat-form-field>

#### What is the expected behavior?
The icon should be normal.

#### What is the current behavior?
platform-browser.js:2854 Error: <path> attribute d: Expected path command, "…2-.9 2-2V5.0.1-2fb4d61.1-.9-2-2-…".
DefaultDomRenderer2.setAttribute @ platform-browser.js:2854
BaseAnimationRenderer.setAttribute @ animations.js:536
DebugRenderer2.setAttribute @ core.js:15341
createElement @ core.js:10583
createViewNodes @ core.js:13738
callViewAction @ core.js:14211
execComponentViewsAction @ core.js:14120
createViewNodes @ core.js:13805
callViewAction @ core.js:14211
execComponentViewsAction @ core.js:14120
createViewNodes @ core.js:13805
createRootView @ core.js:13666
callWithDebugContext @ core.js:15091
debugCreateRootView @ core.js:14374
ComponentFactory_.create @ core.js:11265
ComponentFactoryBoundToModule.create @ core.js:4034
ViewContainerRef_.createComponent @ core.js:11462
RouterOutlet.activateWith @ router.js:6640
ActivateRoutes.activateRoutes @ router.js:5720
(anonymous) @ router.js:5660
ActivateRoutes.activateChildRoutes @ router.js:5659
ActivateRoutes.activate @ router.js:5519
(anonymous) @ router.js:5447
(anonymous) @ Observable.js:225
SafeSubscriber.__tryOrSetError @ Subscriber.js:248
SafeSubscriber.next @ Subscriber.js:188
Subscriber._next @ Subscriber.js:127
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
MergeMapSubscriber.notifyNext @ mergeMap.js:151
InnerSubscriber._next @ InnerSubscriber.js:25
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
ScalarObservable._subscribe @ ScalarObservable.js:51
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
subscribeToResult @ subscribeToResult.js:23
MergeMapSubscriber._innerSub @ mergeMap.js:138
MergeMapSubscriber._tryNext @ mergeMap.js:135
MergeMapSubscriber._next @ mergeMap.js:118
Subscriber.next @ Subscriber.js:91
MergeMapSubscriber.notifyNext @ mergeMap.js:151
InnerSubscriber._next @ InnerSubscriber.js:25
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
TakeLastSubscriber._complete @ takeLast.js:103
Subscriber.complete @ Subscriber.js:116
Subscriber._complete @ Subscriber.js:134
Subscriber.complete @ Subscriber.js:116
MergeMapSubscriber._complete @ mergeMap.js:143
Subscriber.complete @ Subscriber.js:116
ArrayObservable._subscribe @ ArrayObservable.js:118
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MergeMapOperator.call @ mergeMap.js:92
Observable.subscribe @ Observable.js:157
ScanOperator.call @ scan.js:72
Observable.subscribe @ Observable.js:157
TakeLastOperator.call @ takeLast.js:66
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
subscribeToResult @ subscribeToResult.js:23
MergeMapSubscriber._innerSub @ mergeMap.js:138
MergeMapSubscriber._tryNext @ mergeMap.js:135
MergeMapSubscriber._next @ mergeMap.js:118
Subscriber.next @ Subscriber.js:91
MergeMapSubscriber.notifyNext @ mergeMap.js:151
InnerSubscriber._next @ InnerSubscriber.js:25
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
MergeMapSubscriber.notifyNext @ mergeMap.js:151
InnerSubscriber._next @ InnerSubscriber.js:25
Subscriber.next @ Subscriber.js:91
EverySubscriber.notifyComplete @ every.js:54
EverySubscriber._complete @ every.js:71
Subscriber.complete @ Subscriber.js:116
MergeMapSubscriber._complete @ mergeMap.js:143
Subscriber.complete @ Subscriber.js:116
ArrayObservable._subscribe @ ArrayObservable.js:118
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MergeMapOperator.call @ mergeMap.js:92
Observable.subscribe @ Observable.js:157
EveryOperator.call @ every.js:34
Observable.subscribe @ Observable.js:157
subscribeToResult @ subscribeToResult.js:23
MergeMapSubscriber._innerSub @ mergeMap.js:138
MergeMapSubscriber._tryNext @ mergeMap.js:135
MergeMapSubscriber._next @ mergeMap.js:118
Subscriber.next @ Subscriber.js:91
EverySubscriber.notifyComplete @ every.js:54
EverySubscriber._complete @ every.js:71
Subscriber.complete @ Subscriber.js:116
MergeMapSubscriber._complete @ mergeMap.js:143
Subscriber.complete @ Subscriber.js:116
ArrayObservable._subscribe @ ArrayObservable.js:118
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MergeMapOperator.call @ mergeMap.js:92
Observable.subscribe @ Observable.js:157
EveryOperator.call @ every.js:34
Observable.subscribe @ Observable.js:157
MergeMapOperator.call @ mergeMap.js:92
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
subscribeToResult @ subscribeToResult.js:23
MergeMapSubscriber._innerSub @ mergeMap.js:138
MergeMapSubscriber._tryNext @ mergeMap.js:135
MergeMapSubscriber._next @ mergeMap.js:118
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
MergeMapSubscriber.notifyNext @ mergeMap.js:151
InnerSubscriber._next @ InnerSubscriber.js:25
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
ScalarObservable._subscribe @ ScalarObservable.js:51
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
subscribeToResult @ subscribeToResult.js:23
MergeMapSubscriber._innerSub @ mergeMap.js:138
MergeMapSubscriber._tryNext @ mergeMap.js:135
MergeMapSubscriber._next @ mergeMap.js:118
Subscriber.next @ Subscriber.js:91
MergeMapSubscriber.notifyNext @ mergeMap.js:151
InnerSubscriber._next @ InnerSubscriber.js:25
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
ScalarObservable._subscribe @ ScalarObservable.js:51
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
subscribeToResult @ subscribeToResult.js:23
MergeMapSubscriber._innerSub @ mergeMap.js:138
MergeMapSubscriber._tryNext @ mergeMap.js:135
MergeMapSubscriber._next @ mergeMap.js:118
Subscriber.next @ Subscriber.js:91
Subscriber._next @ Subscriber.js:127
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
LastSubscriber._complete @ last.js:111
Subscriber.complete @ Subscriber.js:116
MergeMapSubscriber._complete @ mergeMap.js:143
Subscriber.complete @ Subscriber.js:116
ScalarObservable._subscribe @ ScalarObservable.js:53
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MergeMapOperator.call @ mergeMap.js:92
Observable.subscribe @ Observable.js:157
LastOperator.call @ last.js:40
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
CatchOperator.call @ catchError.js:80
Observable.subscribe @ Observable.js:157
MergeMapOperator.call @ mergeMap.js:92
Observable.subscribe @ Observable.js:157
MergeMapOperator.call @ mergeMap.js:92
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
MergeMapOperator.call @ mergeMap.js:92
Observable.subscribe @ Observable.js:157
MergeMapOperator.call @ mergeMap.js:92
Observable.subscribe @ Observable.js:157
MergeMapOperator.call @ mergeMap.js:92
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
(anonymous) @ Observable.js:204
ZoneAwarePromise @ zone.js:890
Observable.forEach @ Observable.js:200
(anonymous) @ router.js:5428
ZoneAwarePromise @ zone.js:890
Router.runNavigate @ router.js:5353
(anonymous) @ router.js:5308
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4756
Promise resolved (async)
scheduleMicroTask @ zone.js:585
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:236
Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:871
ZoneAwarePromise.then @ zone.js:981
PlatformRef.bootstrapModule @ core.js:5574
(anonymous) @ main.ts:12
../../../../../src/main.ts @ main.bundle.js:310
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:332
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
15:43:10.190 

#### What is the use-case or motivation for changing an existing behavior?
Update

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.6.0
Node: 8.9.3
OS: linux x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.1-2fb4d61
@angular/cli: 1.6.0
@angular/flex-layout: 2.0.0-beta.11-b01c2d7
@angular/material-moment-adapter: 5.0.1-2fb4d61
@angular/material: 5.0.1-2fb4d61
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0

#### Is there anything else we should know?
It was working but after latest update the issue appears.

**Comment by andrewseguin** [comment]
Please re-open with a plunker or stackblitz that shows the reproduction so we can investigate the issue

**Comment by aleppos** [comment]
@andrewseguin  http://plnkr.co/edit/TsResrRM4q0HhUU3NSNg?p=preview
