### ISSUE TITLE
Angular 5 mat-error dose not work with a custom validator

### ISSUE THREAD

**Issue by orenAzuz** [angular/material2#8978]
I'm trying to use a custom validator in mat-stepper and it's acting weird for example when it gets an error from the custom validator it won't block the form from continuing although it can be blocked if I use [disabled]="titlePattern.invalid" but I'm not getting any error message in another scenario
that the user makes another invalid input with the custom one I get the error message from the mat-error - the custom validator error.
also, this is working when I'm using a regular form with mat-input,mat-error, and mat-card but not in the mat-stepper...
I saw an issue very similar to this hear in git hub and they had no solution. I want to know if there is a way to go around this problem or fix it somehow?
thanks

angular 5

**Comment by andrewseguin** [comment]
Please refer all troubleshooting questions to our community at StackOverflow, Angular Material mailing lists, Gitter, etc. We try to keep our issues here only open for bugs and feature requests.

**Comment by orenAzuz** [comment]
Do you suppose it is not a bug?

**Comment by orenAzuz** [comment]
Assuming this is not a bug do you have any idea of what can be the problem?

**Comment by mmalerba** [comment]
Without a reproduction example its difficult to tell if its a bug in Material or the code you wrote, can you provide a stackblitz? or at least a link to this other github issue you saw

**Comment by orenAzuz** [comment]
Ok, I solve this issue and  @andrewseguin was right it wasn't a bug I was needed to add the custom validator to the FormGroup however I was needed to do some configuration to make it work. so I'm closing this issue
