### ISSUE TITLE
unable to style internal md* elements with component styles

### ISSUE THREAD

**Issue by maciejsobala** [angular/material2#898]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
after adding:
```styles: [`some styles`]```
or 
```stylesUrl: [' some file']```
to component
css settings should be able to affect md* tags (```<md-input>```, ```<md-toolbar>``` etc.) internal elements

#### What is the current behavior?
You can style only top container

#### What are the steps to reproduce?

http://plnkr.co/edit/V21xYz1cHItr3ITJmMXF?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular2-material/core": "^2.0.0-alpha.6",
"@angular/core": "2.0.0-rc.4",

#### Is there anything else we should know?
Workaround:
Place your styles in index.html, or external css file, and link them in index.html:
```
<link href="style.css" rel="stylesheet">
```

**Comment by nesukun** [comment]
Your style should read like this:

`  styles: [`
  md-input >>> div {
   background-color: pink !important;
  }
  
  md-toolbar >>> div {
    background-color: pink !important;
  }
  `];`

For more information, please read https://angular.io/docs/ts/latest/guide/component-styles.html

**Comment by maciejsobala** [comment]
You are right. Thank you.

Closing.
