### ISSUE TITLE
[Input] Placeholder not hidden when formControl value changes with emitEvent: false

### ISSUE THREAD

**Issue by filipows** [angular/material2#8982]
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?
Placeholder should hide if input value is not empty

#### What is the current behavior?
Placeholder overlaps the content of input
![placeholder-bug](https://user-images.githubusercontent.com/884847/33974288-98fbbf6a-e0c2-11e7-876f-d51ad2a06ec0.gif)

#### What are the steps to reproduce?
1. MatFormField: `floatPlaceholder="never"` or `floatLabel="never"` (as floatPlaceholder is deprecated)
2. Patch value of formControl with `{emitEvent: false}`

https://stackblitz.com/edit/angular-material2-issue-gvg3yu

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.0
Material: 5.0

Ubuntu 16.04
Chrome Version 61.0.3163.100
Firefox Quantum Version 57

#### Is there anything else we should know?
It can be related to this issue: https://github.com/angular/material2/issues/7066

**Comment by montella1507** [comment]
Same here.

**Comment by rafh** [comment]
I ran into a similar issue, and this is the workaround I'm using until I can come up with something better. 
`checkFormValues(form) {`
&nbsp;&nbsp;&nbsp;`Object.keys(form.controls).forEach(key => {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`if(form.get(key).value.length > 0 && form.get(key).valid) {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`form.get(key).markAsTouched();`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`form.get(key).markAsDirty();`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`form.get(key).updateValueAndValidity();`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;`});`
`}`

In my global stylesheet, I applied these styles

` mat-input-container.ng-valid.ng-touched {`
&nbsp;&nbsp;&nbsp;`.mat-input-placeholder.mat-empty.mat-float {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`transform: translateY(-100%) scale(.75);`
&nbsp;&nbsp;&nbsp;`}`
`}`
