### ISSUE TITLE
[Input] Suffix wrapper not removed with ngIf

### ISSUE THREAD

**Issue by maartenmensink** [angular/material2#8988]
#### Bug, feature request, or proposal:
```
 [x] Bug
 [ ] Feature request
 [ ] Proposal
```

#### What is the expected behavior?

matSuffix wrapper element should be removed from dom when `ngIf ` is used on element

#### What is the current behavior?

matSuffix element is removed upon focusing the mat-form-field element

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-ddtyp7

In sample do the following

1. Click on eye icon. The .00 suffix disappears but the wrapper marked in red remains
2. Focus on the second input the wrappers is removed from dome.

#### What is the use-case or motivation for changing an existing behavior?

incorrect behavior

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5.x
Chrome 

#### Is there anything else we should know?

![ac053285-02a1-41be-b430-be05027d7e51](https://user-images.githubusercontent.com/339653/33984880-4a5a350c-e0b9-11e7-8b9c-5dcefeaa4016.GIF)
![snag_1938b8e6](https://user-images.githubusercontent.com/339653/33985032-a60fcd6c-e0b9-11e7-88da-2fd7287bda0a.png)
![snag_1938c73d](https://user-images.githubusercontent.com/339653/33985036-a7a0e33c-e0b9-11e7-8617-f67fc055d040.png)
![snag_1938d140](https://user-images.githubusercontent.com/339653/33985041-a9a2a08a-e0b9-11e7-8ed0-4ba0e3dd5451.png)

**Comment by gatimus** [comment]
I have a similar problem where I have to asynchronously check if I should show the suffix but it doesn't show until I focus the input.
https://stackblitz.com/edit/angular-material2-issue-ugnaqj

**Comment by PTC-JoshuaMatthews** [comment]
Same issue as @gatimus . MatSuffix not responding to well to be shown and hidden with an ngIf.
