### ISSUE TITLE
feat(): switch component

### ISSUE THREAD

**Issue by DevVersion** [angular/material2#90]
Hello,
Just wanted to know, if someone is already working on the switch component?
As I recently trying things with Angular 2 I built a few components and would like to help if desired at the material2 component. I know it's still in early stages, but I think it never hurts to ask.

![Preview](https://i.gyazo.com/8b1b212257b831537fe3ba413d605253.png)

**Comment by jelbourn** [comment]
We definitely plan on building one, but we're waiting for completion of both the checkbox (#35) since it will share most of the code, and gestures (#72) for having a common way of doing the sliding. Once those pieces are done I'll come back and update this issue.

**Comment by DevVersion** [comment]
@jelbourn Is this now unblocked? Since HammerJS is now available.

**Comment by jelbourn** [comment]
@DevVersion I suppose it is. Is this something you want to contribute? 

Couple of notes:
* A lot of the TS code should be shared between this and checkbox.
* Users should be able to drag the switch part.

**Comment by jelbourn** [comment]
cc @kara

**Comment by DevVersion** [comment]
@jelbourn Yes definitely.

I already implemented it myself a few months ago (#7)
- But you may have noticed, it used much things from Material 1 and even used an internal gesture service. 

I will start working on this new component the next days (Material 1 - 1.1.0 coming).

I try to extend as much as possible and also work on the drag for the switch part.

**Comment by jelbourn** [comment]
@DevVersion it would be good to break the work into stages. Something like:

1. Add empty skeleton for slide-toggle
2. Refactor any checkbox code that would be used by both
3. Add the dragging to the slide-toggle

(I forgot to mention earlier, we want to change the name to `md-slide-toggle` since "switch" is already overloaded with the `switch` control construct, e.g., `ng-switch`).

**Comment by DevVersion** [comment]
@jelbourn Yea this sounds good. Am I allowed to ask some questions on Slack, if needed?

**Comment by jelbourn** [comment]
@DevVersion of course!

**Comment by DevVersion** [comment]
Fixed with #362.
