### ISSUE TITLE
Make material components easier to assign ID-s

### ISSUE THREAD

**Issue by samir-h** [angular/material2#9010]
#### Bug, feature request, or proposal:

feature request
#### What is the expected behavior?

Make material components with ID input for data-binding, so the component could get a custom ID ( this is needed for testing)
#### What is the current behavior?

At the moment you cant assign an ID to <mat-tab> for example, only for <mat-tab-group> . The ID should be passed down to all child nodes, instead we only have generated ID which change and are not useful for testing
#### What are the steps to reproduce?
User <mat tab group> component, assign ID, and check the children and their IDs.

#### What is the use-case or motivation for changing an existing behavior?

Using testing software like Selenium, where the prefered way is to access the elements by ID
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

**Comment by mmalerba** [comment]
Most elements already have CSS classes that can be used for this purpose
