### ISSUE TITLE
bug(menu): nested menu does not work inside ng-template

### ISSUE THREAD

**Issue by mkoczka** [angular/material2#9011]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
It should be possible to create nested menus recursively (eg. from JSON) inside the ng-template.

#### What is the current behavior?
The menu does not detect the parent menu so it doesn't work as the nested menu.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): http://plnkr.co/edit/IBMqqQRwgKtKQOkUWdGh?p=preview<br/>
StackBlitz starter (using latest `npm` release): https://stackblitz.com/edit/angular-material2-issue-yd6exa<br/>

#### What is the use-case or motivation for changing an existing behavior?
I want to create nested menus recursively from JSON.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by crisbeto** [comment]
The way we detect the parent menu is through DI (see https://github.com/angular/material2/blob/master/src/lib/menu/menu-trigger.ts#L131). Since the menu item isn't a child of the `mat-menu`, there's no way for Material to pick it up.

**Comment by mkoczka** [comment]
What if `parentMenu` would be an input property of the `menu-trigger` or `menu-panel`?

It would be possible to set parent explicitly in cases when menu isn't a child of the `mat-menu`.

**Comment by crisbeto** [comment]
That doesn't work completely either, because the menu won't be able to pick up its `mat-menu-item` children using `@ContentChildren`.
