### ISSUE TITLE
distributed files have reference to /usr/local/google/home/mmalerba

### ISSUE THREAD

**Issue by mcalmus** [angular/material2#9012]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
no references to local URLs

#### What is the current behavior?
I noticed in my logs some GET requests to paths starting with "/usr/local/google/home/mmalerba". Searching through the files I see several .map files have "sources" references to this path.

This is not actually causing issues, but I thought it was something that should be looked at.

#### What is the use-case or motivation for changing an existing behavior?
Clean code

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
5.0.1

**Comment by mmalerba** [comment]
@jelbourn @DevVersion It sounds like something in our release process is picking up absolute paths from the user's system

**Comment by jelbourn** [comment]
@DevVersion can you take a look?

**Comment by DevVersion** [comment]
@jelbourn Yeah will do as soon as possibly.
