### ISSUE TITLE
mat-button disabled binding doesn't work

### ISSUE THREAD

**Issue by steveadoo32** [angular/material2#9014]
#### Bug, feature request, or proposal:
Bug. It looks like the [disabled] binding is not working on buttons with the mat-button directive.

#### What is the expected behavior?
It should work if I bind disabled to a property on my component

#### What is the current behavior?
It only works if I just have the disabled attribute on the button
`<button mat-button disabled>Test</button>` works.
`<button mat-button [disabled]="progress">Test</button>` does not work.

#### What are the steps to reproduce?
This is my html.

```
  <button mat-button [disabled]="!filterValid">Search</button>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest versions of Angular and Angular Material.

#### Is there anything else we should know?
Maybe I'm doing something wrong here... I just upgraded my angular and material versions and it broke all my disabled attributes.

**Comment by steveadoo32** [comment]
Looks like this is working. I must've been doing something wrong.

**Comment by MarcServat** [comment]
Try insert the values without quotes!! 

[disabled]=!filterValid

I had the same error and these was the only solution that I've found

**Comment by tatsujb** [comment]
oh my fucking effing god.

what the fuck.

why?

**Comment by WrongWayJerry** [comment]
I am able to get it to work but the appearance doesn't change.

                  <div class="button-row" >
                        <button mat-raised-button color="primary" [disabled]="cost > data.gameObject.funds" (click)="incrementCount(element)">+</button>
                        <button mat-raised-button color="primary" [disabled]="cost > data.gameObject.funds" (click)="decrementCount(element)">-</button>                  
                  </div>

Am I missing something?

**Comment by tatsujb** [comment]
@WrongWayJerry `[disabled]="cost` opening `"` but not closing `"` ?

**Comment by WrongWayJerry** [comment]
@tatsujb I deleted my comment about the disable appearance not working. It was user error. I fixed it.
