### ISSUE TITLE
Bug: mat-menu and Closure Compiler

### ISSUE THREAD

**Issue by Doehl** [angular/material2#9018]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Use Material with Closure Compiler in Advanced Mode.

#### What is the current behavior?
When compiling a project with Closure Compiler (Advanced) that use the "mat-menu", will the code fail to run. 

It is the following code that fails to run:
https://github.com/angular/material2/blob/2436acda3f2e4551842d4373dc95e293fd275ca3/src/cdk/a11y/list-key-manager.ts#L66

```
ERROR TypeError: Cannot read property 'length' of undefined
    at $JSCompiler_StaticMethods_withTypeAhead$$ (app.1513449064696.js:14114)
    at $MatMenu$$module$node_modules$$angular$material$esm2015$menu$$.$$JSCompiler_prototypeAlias$$$$ngAfterContentInit$$ [as $ngAfterContentInit$] (app.1513449064696.js:15783)
    at $callProviderLifecycles$$module$node_modules$$angular$core$esm2015$core$$ (app.1513449064696.js:3640)
    at $callLifecycleHooksChildrenFirst$$module$node_modules$$angular$core$esm2015$core$$ (app.1513449064696.js:3629)
    at $checkAndUpdateView$$module$node_modules$$angular$core$esm2015$core$$ (app.1513449064696.js:3931)
    at $callViewAction$$module$node_modules$$angular$core$esm2015$core$$ (app.1513449064696.js:4296)
    at $execComponentViewsAction$$module$node_modules$$angular$core$esm2015$core$$ (app.1513449064696.js:4266)
    at $checkAndUpdateView$$module$node_modules$$angular$core$esm2015$core$$ (app.1513449064696.js:3933)
    at $callViewAction$$module$node_modules$$angular$core$esm2015$core$$ (app.1513449064696.js:4296)
    at $execComponentViewsAction$$module$node_modules$$angular$core$esm2015$core$$ (app.1513449064696.js:4266)
```

#### What are the steps to reproduce?

Can't create a reproduce on any online platform, because of the use of Clousure Compiler.
But you can see the project with the error here, it has been compiled in debug mode: [https://stylistdev.hvisk.com/collagemaker](https://stylistdev.hvisk.com/collagemaker) 

Code to reproduce:
```html
<button mat-icon-button matTooltip="Gridlines"  [matMenuTriggerFor]="appMenu">
    <mat-icon svgIcon="material:grid-on"></mat-icon>
</button>

<mat-menu #appMenu="matMenu">
    <button mat-menu-item>None</button>
    <button mat-menu-item>Rule of thirds</button>
    <button mat-menu-item>Rule of four</button>
</mat-menu>
```

#### What is the use-case or motivation for changing an existing behavior?
A Google product should be able to be compiled and run when using the Google Closure Compiler.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.1.0
Material: 5.0.1
Closure Compiler: 20171112.0.0
TypeScript: 2.4.2
Chrome: 63

**Comment by jelbourn** [comment]
The library is compiled with Closure Compiler inside Google, but the public version sometimes lags behind the internal version- @alexeagle do you know of any open compatibility issues w/ latest Closure Compiler + tsickle and/or anything else?

**Comment by alexeagle** [comment]
No, sorry, we have github.com/angular/closure-demo and an integration test for closure compiler in Angular's repo, but we don't test in-depth with material libraries.
Making a google-internal repro would help to locate the problem.

**Comment by Doehl** [comment]
As an added info can I inform that my project is a modified version of the github.com/angular/closure-demo. (That I hopefully will make available as a seed, when it is a bit more stable)

I have tried to update to closure compiler 20171203, but ran into a problem with RxJS Subject, so can't check if it has been fixed in the latest closure release.

**Comment by dmitrysteblyuk** [comment]
Same here.
It is enough to add this code anywhere in closure-demo to break it.

```
import { FocusKeyManager } from '@angular/cdk/a11y';

new FocusKeyManager(new QueryList()).withWrap().withTypeAhead();
```

The issue is in closure compiler as it is declaring FocusKeyManager without calling super method in the constructor.

**Comment by MatrixFrog** [comment]
I added the code from https://github.com/angular/material2/issues/9018#issuecomment-354137113 to basic.ts in closure-demo but I'm getting an error `Failed to load module "@angular/cdk/a11y"` even after adding "@angular/cdk" to the deps in package.json

Can you create a branch that shows exactly what changes to make, and then what yarn or npm commands to run, to repro the issue?

**Comment by dmitrysteblyuk** [comment]
@MatrixFrog I believe you have to add also these to ```closure.conf```:

--js node_modules/@angular/cdk/package.json
--js node_modules/@angular/cdk/a11y/package.json
--js node_modules/@angular/cdk/accordion/package.json
--js node_modules/@angular/cdk/bidi/package.json
--js node_modules/@angular/cdk/coercion/package.json
--js node_modules/@angular/cdk/collections/package.json
--js node_modules/@angular/cdk/keycodes/package.json
--js node_modules/@angular/cdk/layout/package.json
--js node_modules/@angular/cdk/observers/package.json
--js node_modules/@angular/cdk/overlay/package.json
--js node_modules/@angular/cdk/platform/package.json
--js node_modules/@angular/cdk/portal/package.json
--js node_modules/@angular/cdk/scrolling/package.json
--js node_modules/@angular/cdk/stepper/package.json
--js node_modules/@angular/cdk/table/package.json
--js node_modules/@angular/cdk/esm2015/**.js

Because closure doesn't support recursive syntax for package.json, right?
like this: ```--js node_modules/@angular/cdk/**/package.json```

**Comment by dmitrysteblyuk** [comment]
@MatrixFrog, I forked from closure-demo to demonstrate the issue:
https://github.com/dmitrysteblyuk/closure-demo/tree/material
To run it:
```
yarn run build
yarn serve
```

**Comment by dmitrysteblyuk** [comment]
you didn't forget ```yarn install```, did you?

**Comment by MatrixFrog** [comment]
I didn't run it because you didn't tell me to run it. I know ~nothing about the npm/yarn/node world so I assumed it wasn't needed, perhaps because 'yarn run build' automatically implies 'yarn install'. Will try it now.

**Comment by dmitrysteblyuk** [comment]
Sorry, my bad. By the way also worth mentioning yarn serve uses 8080 port by default.

**Comment by MatrixFrog** [comment]
Thanks, got it working.

After the TS is converted to JS, the Closure Compiler is seeing this, in `node_modules/@angular/cdk/esm2015/a11y.js`:

```
/**
 * This is the interface for focusable items (used by the FocusKeyManager).
 * Each item must know how to focus itself, whether or not it is currently disabled
 * and be able to supply it's label.
 * @record
 */

class FocusKeyManager extends ListKeyManager {
```

That jsdoc belongs to the [interface called 'FocusableOption'](https://github.com/angular/material2/blob/master/src/cdk/a11y/focus-key-manager.ts#L16). It appears that interface was removed but it's associated jsdoc was not. So, Closure Compiler thinks that JSDoc belongs to `FocusKeyManager`. Since (it thinks) that "class" is an interface not a class, the compiler doesn't generate a proper synthetic constructor for it: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/Es6ConvertSuper.java#L82-L86

**Comment by jelbourn** [comment]
@MatrixFrog thanks for figuring that out

Since this doesn't seem be be an issue inside Google, I'm guessing we're using a different version of tsickle to create the npm distribution than is being used inside Google.

**Comment by MatrixFrog** [comment]
I'm surprised we don't get a "cannot instantiate non-constructor" warning though. In any case, I'll see if we can get tsickle to make sure it removes the JSDoc along with the FocusableOption class.

**Comment by MatrixFrog** [comment]
`yarn list | grep tsickle` gives me

```
│  └─ tsickle@^0.25.5
├─ tsickle@0.25.6
```

but the latest according to https://www.npmjs.com/package/tsickle is 0.26.0 so perhaps we just need a version bump?

**Comment by jelbourn** [comment]
Tried a build with the latest tsickle and still seeing the same output. I think everyone who I would bug about tsickle is still out for the holidays, so I'll grab somebody later this week.

**Comment by jelbourn** [comment]
Is anyone still seeing this issue? I suspect that an update of either tsickle or Closure Compiler resolved it since January.

**Comment by Doehl** [comment]
Have not had the time to test it with v.6
I will get back as soon as I have tested it, with all the latest versions.

**Comment by jelbourn** [comment]
Closing this since I suspect that some upstream update has long fixed the problem.
