### ISSUE TITLE
Confirmative dialog buttons should be placed on the right side

### ISSUE THREAD

**Issue by Maximaximum** [angular/material2#9019]
#### Bug, feature request, or proposal:
In all the material samples of the https://material.angular.io/components/dialog section, the confirmative dialog buttons should be placed on the right side of the dialogs, as per `Material design guidelines`: https://material.io/guidelines/components/dialogs.html#dialogs-specs

#### What is the expected behavior?
All the confirmative buttons (like `OK`, `Install` etc) should be placed on the right, whereas the Dismissive actions (like `No thanks` etc) should go to the left.

#### What is the current behavior?
Currently, all the confirmative buttons are placed on the left, whereas the dismissive ones are placed on the right.

#### What are the steps to reproduce?
Open https://material.angular.io/components/dialog/overview and https://material.angular.io/components/dialog/examples pages and try open the sample dialogs

#### What is the use-case or motivation for changing an existing behavior?
The samples should conform to the official Material design Guidelines

**Comment by Maximaximum** [comment]
There's still a problem with this. According to the spec, "Dismissive actions are placed directly to the left of affirmative actions and return the user to the originating screen or step in the process".

So, generally speaking, the dialog action buttons should be aligned to the right. However, currently they are aligned to the left.

**Comment by ewaschen** [comment]
Also having a similar issue where `mat-dialog-actions` keeps the actions on the left side of the dialog instead of pushed over to the right [https://material.io/guidelines/components/dialogs.html#dialogs-specs](https://material.io/guidelines/components/dialogs.html#dialogs-specs)

To reproduce, open the [dialog](https://material.angular.io/components/dialog/overview) in stackblitz and increase the dialog witdth to `400px`

**Comment by ewaschen** [comment]
This issue should be re-opened. As @Maximaximum said, according to the [Material Dialog Specs](https://material.io/guidelines/components/dialogs.html#dialogs-specs) actions should be right aligned not left aligned as they currently are.

To test,  open the [Material Dialog](https://material.angular.io/components/dialog/overview) in stackblitz and increase the Dialog width to `400px`

**Comment by Maximaximum** [comment]
@josephperrott could you please reopen this issue?

**Comment by ewaschen** [comment]
@Maximaximum Looking at the [Material Demo Page](https://github.com/angular/material2/blob/1a940e053eb0b9ee04c29ceba2c8c36f248840cf/src/demo-app/dialog/dialog-demo.ts#L151)

you can set the actions to the right with `[attr.align]="'end'"`

**Comment by Maximaximum** [comment]
@ewaschenko yeah, thank you. But I thought it would be logical if Angular Material enforces a default layout to right, to be in line with official Material spec
