### ISSUE TITLE
Material inlined templates/css

### ISSUE THREAD

**Issue by thelgevold** [angular/material2#903]
This is more of a request for advice :-)

I am working on a library of shared components, so I was wondering if you would be willing to share some details about the tooling you use to create your npm packages. Specifically I am interested in the tools you use to inline templates and css files in the published js source. 

I have been able to inline templates using webpack plugins like angular2-template-loader, but am curious if you are using an alternative method.

I am also considering the offline compiler as a way to achieve this since it will take this one step further by converting the original html to executable javascript before inlining.

Thanks!

**Comment by laserfists** [comment]
Check out thel files in /scripts/release, specifically [inline-resources.js](https://github.com/angular/material2/blob/master/scripts/release/inline-resources.js). This is how it is currently handled for npm releases it seems.

**Comment by thelgevold** [comment]
Thanks!
