### ISSUE TITLE
feature request: Add a possibility to pass projectable nodes into ComponentPortal

### ISSUE THREAD

**Issue by Anufriev** [angular/material2#9030]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Add a possibility to pass projectable nodes into ComponentPortal

#### What is the current behavior?
I have no possibility to pass projectable nodes into ComponentPortal

#### What is the use-case or motivation for changing an existing behavior?
I need to build componentPortal based on a custom component with ng-content.

**Comment by jelbourn** [comment]
`ng-content` is a primitive in the Angular compiler; there is unfortunately no way for a library to intercept that content and render it somewhere else.

You _can_ wrap `ng-content` inside an `ng-template` but, when you do this, that content is initialized all the time regardless of whether the template is stamped out anywhere.
