### ISSUE TITLE
structure of cdk for dialog changed in latest material comparing with version 2.

### ISSUE THREAD

**Issue by gns088** [angular/material2#9031]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
when i open dialog. content of page should not be get blank.

#### What is the current behavior?
when i open dialog content of page is getting blank.

#### What are the steps to reproduce?
step to produce this.
step 1: open dialog without scroll page. you will be able to see the page content.
step 2: open dialog after doing some scrolling. here you will be able to see that content of page is blank.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "5.0.0-rc.2"
"@angular/cdk": "5.0.0-rc.2"

#### Is there anything else we should know?
here is capture the image of old and new version of material cdk stucture
Old structure 
version 
"@angular/material": "2.0.0-beta.8"
"@angular/cdk": "2.0.0-beta.8"

![old-structure](https://user-images.githubusercontent.com/25655436/34104858-2d7ccbd6-e418-11e7-9128-9ce1232489dc.png)

new strucure
version 
"@angular/material": "5.0.0-rc.2"
"@angular/cdk": "5.0.0-rc.2"

![latest-structure](https://user-images.githubusercontent.com/25655436/34104868-37e0f584-e418-11e7-8353-25526b35f3b1.png)

**Comment by josephperrott** [comment]
Can you provide a reproduction in either [Plunker](https://goo.gl/uDmqyY) or [StackBlitz]( https://goo.gl/wwnhMV)

**Comment by gns088** [comment]
i am not able to reproduce this in plunker but getting this issue in my project.
can you please check the difference between 2 image that i upload. why that structure i different. 
in plunker i am getting old structure so issue not persist. 
when i was using "@angular/material": "2.0.0-beta.8", /cdk": "2.0.0-beta.8" then issue was not there but after updating i m getting this different structure.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
