### ISSUE TITLE
Time Picker

### ISSUE THREAD

**Issue by babsevensix** [angular/material2#9033]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Please, make material components for Timepicker like http://materializecss.com/forms.html#time-picker

#### What is the use-case or motivation for changing an existing behavior?
No implementation found

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

**Comment by benb7760** [comment]
Duplicate of #5648

**Comment by crisbeto** [comment]
Closing as a duplicate.

**Comment by matheo** [comment]
@crisbeto will you give a comment on #5648 or just trash our work letting our code to be depreciated over the time??

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
