### ISSUE TITLE
When mat-select is touched  (by code) it is not showing the error.

### ISSUE THREAD

**Issue by Jefiozie** [angular/material2#9047]
#### Bug, feature request, or proposal:

When submitting a form and explicit set all controls to `touched` the `mat-select` control is not updated via `Input` binding with FormGroup. It looks like it has something to do with focus maybe? As I need to click on a other element to get the `mat-error`

Don't know if the way I have made the form is the best approach maybe you can clarify on that a bit.

#### What is the expected behavior?

Would like to see that the validation is handled and the `mat-error` is shown

#### What is the current behavior?

Stays the same until I clicked the `mat-select`

#### What are the steps to reproduce?
StackBlitz  : [Example Url](https://stackblitz.com/edit/angular-material-select-submit?embed=1&file=app/select-error-state-matcher-example.ts&hideExplorer=1&view=preview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular: 5.1.0
material: 5.0.0

#### Is there anything else we should know?

Thanks for the GREAT work!

**Comment by willshowell** [comment]
FWIW this appears to simply be a symptom of OnPush. The inputs on `SelectComponent` don't change and the submit event is occurring in `SelectErrorStateMatcherExample`, so change detection isn't being run on `SelectComponent`.

**Comment by Jefiozie** [comment]
:roll_eyes: okay (a bit of shame that I missed that one) 

Removing the `OnPush` indeed works for the way I would like to visual have it. @willshowell still wondering if I'm doing the correct implementation then. Thoughts on it if i'm doing it wrong if so I will close the issue.

**Comment by crisbeto** [comment]
I spent some time looking into it and it doesn't seem like there's much we can do on Material's side to react to changes in the `touched` state. The Angular forms don't have a stream that we can subscribe to when it changes and the dirty checking that we do won't happen when the control is nested inside a component with `OnPush`. You can work around it either by switching away from `OnPush`, moving the select out of the component, or calling `markForCheck` from inside the component when the control becomes touched.
