### ISSUE TITLE
Stackblitz mat-icon example broken

### ISSUE THREAD

**Issue by AhmedHasnaoui** [angular/material2#9048]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Stackblitz should show a working example on how to use mat-icon component

#### What is the current behavior?
Stackblitz shows an error that the file/component "app/icon-svg-example.ts" could not be found.

https://material.angular.io/components/icon/examples

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

Open: https://stackblitz.com/angular/ammlgegmxpy

#### What is the use-case or motivation for changing an existing behavior?
providing a working Stackblitz example.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest Material

#### Is there anything else we should know?
Fix it by using:
https://stackblitz.com/angular/nkdmddnqjlg

**Comment by rafaelss95** [comment]
Duplicated #8949.
