### ISSUE TITLE
MatListOption & MatSelectionList docs incorrect

### ISSUE THREAD

**Issue by AmandaFoster** [angular/material2#9053]
#### Bug, feature request, or proposal:
The docs for MatListOption list `selectChange` as an `Output()` property. The correct property name is [`selectionChange`](https://github.com/angular/material2/blob/a4c042b6c958f6e169252d820d47df88debd4fea/src/lib/list/selection-list.ts#L155). The emitted type `MatSelectionListOptionEvent` is incorrect as well.
The source indicates this property is deprecated though, and the same property from [MatSelectionList](https://github.com/angular/material2/blob/a4c042b6c958f6e169252d820d47df88debd4fea/src/lib/list/selection-list.ts#L284) should be used instead. Perhaps this could be added to the docs and the property removed from MatListOption?

Maybe this can be rolled up into #8832.

#### What is the expected behavior?
Documentation should be up to date

#### What is the current behavior?
It's not

#### What are the steps to reproduce?
[Docs here](https://material.angular.io/components/list/api)

#### What is the use-case or motivation for changing an existing behavior?
Outdated docs

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
N/A

#### Is there anything else we should know?
N/A

**Comment by rafaelss95** [comment]
It seems like you've got some cache. Try open your browser in incognito.

**Comment by AmandaFoster** [comment]
@rafaelss95  Indeed, that was the case. I feel a bit silly about that.
