### ISSUE TITLE
Underline for mat-select is missing

### ISSUE THREAD

**Issue by ygerg** [angular/material2#9067]
#### Bug, feature request, or proposal:
Bug / request

#### What is the expected behavior?
The mat-select component should have an underline as shown in Material Design guidelines and in the docs. 

If this is intended, the documentation should reflect this behavior. I can't find any mention of this change though.

#### What is the current behavior?
With a version greater than 5.0.0, the <mat-select> component doesn't have an underline.

#### What are the steps to reproduce?
A minimal StackBlitz: https://mat-select-issue.stackblitz.io

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
5.0.0 >, on all major browsers.

**Comment by crisbeto** [comment]
You have to wrap your select in a `mat-form-field`:

```html
  <mat-form-field style="width: 250px">
    	<mat-select placeholder="Choose an option">
        <mat-option value="option1">Option 1</mat-option>
        <mat-option value="option2">Option 2</mat-option>
        <mat-option value="option3">Option 3</mat-option>
      </mat-select>
  </mat-form-field>
```

**Comment by ygerg** [comment]
Thanks, Chrome's cache on the docs site caught me off guard. I stand corrected.
