### ISSUE TITLE
Typing a date into the input of the datepicker does not lead to the same value as selecting a date in the datepicker

### ISSUE THREAD

**Issue by qstiegler** [angular/material2#9070]
#### Bug, feature request, or proposal:
If I select the `24.12.2017` in the datepicker, the value is `2017-12-23T23:00:00.000Z` but if I type `24.12.2017` into the input field of the datepicker, the value is `2017-12-24T11:00:00.000Z`. Cause of this difference, the rendered output value is different.

#### What is the expected behavior?
If you type `24.12.2017` into the input field of the datepicker, it should also convert this into the same value as when selecting the date into the datepicker (`2017-12-23T23:00:00.000Z`).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular: ^5.1.0
@angular/material: ^5.0.2
@angular/cdk: ^5.0.2
typescript: ~2.4.2
Chrome: 63

**Comment by mmalerba** [comment]
Can you provide a Stackblitz or Plunker reproduction? I need to see what `DateAdapter` and locale settings you're using.

**Comment by qstiegler** [comment]
I created a Stackblitz but for any reson my GermanDateAdapter is not working in the Stackblitz and thats why the Date format seems to be different than in my case.

Do you know why providing the GermanDateAdapter is not working? https://stackblitz.com/edit/angular-yyczkl?file=app%2Fapp.module.ts

**Comment by mmalerba** [comment]
It's different when you type it because you've written a custom `DateAdapter` and told it to set the hour to 12:

> `return new Date(Number(str[2]), Number(str[1]) - 1, Number(str[0]), 12);`

Use this instead and it will be the same: `return new Date(Number(str[2]), Number(str[1]) - 1, Number(str[0]));`

**Comment by qstiegler** [comment]
Damn you´re so right. Thanks for your support!
