### ISSUE TITLE
tooltip "before","after" positions do not conform to rtl direction standards

### ISSUE THREAD

**Issue by molofson** [angular/material2#9071]
#### Bug, feature request, or proposal:
A tooltip, when applied to an element with rtl direction, does not position correctly with 'before' or 'after' position attributes.

A combination of 'rtl' and 'after' places the tooltip on the right side of the element.

#### What is the expected behavior?
It should display on the left side of the element.

#### What is the current behavior?
It is always displayed as if the element were 'ltr'.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-cj3zar

In the stackblitz, the "after" tooltip should appear on the same side as the period of the button's text.

#### What is the use-case or motivation for changing an existing behavior?
It deviates from the direction standards

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular5, Material5.

**Comment by crisbeto** [comment]
Your example doesn't work correctly, because you're setting the `direction` using CSS. Material has no way of knowing that you did this, aside from calling `getComputedStyle` which would be very expensive. You can get it to pick up the direction correctly by setting the `dir` attribute instead.
