### ISSUE TITLE
About md tags

### ISSUE THREAD

**Issue by tssajay** [angular/material2#9082]
I am unable to access the MdTabsModule,MdInpuModule... from @angular/material
Can you please tell me how to use them and also the Document link where the old version contains that is md tags before of mat tags document.
I am using Angular 2 and started with mdtags in my project.

**Comment by CDDelta** [comment]
If you can, you should update to the latest material package and replace all your Md tags with Mat. 

Check out this [package](https://www.npmjs.com/package/angular-material-prefix-updater) to help you update your tags.
Note: Running this tool with Angular Material versions higher than beta.11 will not work. The prefix updater tool requires type information from the outdated Md classes.

**Comment by bardiel** [comment]
Still I don't think **@angular/material ^5.0.0** will work in **Angular 2**.

**Comment by CDDelta** [comment]
It would be best to keep up with new angular releases, but that does not matter here. If you cant upgrade, just update your md tags to the mat version. Also remember to enable the MAT_COMPATIBILITY_MODE through your app module.

**Comment by josephperrott** [comment]
Closing as the Md tags have been deprecated.  As mentioned above, you will need to change from using `md-` prefix to `mat-`.
