### ISSUE TITLE
ERROR in Metadata version mismatch for module /Users/user/Desktop/FrontEnd/node_modules/@angular/material/core/typings/index.d.ts, found version 4, expected 3, resolving symbol SharedModule in /Users/user/Desktop/FrontEnd/src/app/shared/shared.module.ts, resolving symbol SharedModule in /Users/user/Desktop/FrontEnd/src/app/shared/shared.module.ts

### ISSUE THREAD

**Issue by alican5959** [angular/material2#9083]
What is the problem. Which versions should use

**Comment by crisbeto** [comment]
You're probably on an older version of Angular. The latest version of Material requires at least Angular 5.0.

**Comment by alican5959** [comment]
I will try your advice thank you bro

**Comment by meyer20** [comment]
@crisbeto I'm having the same problem, but i can't update my angular version, wich version i should use?
Thanks

**Comment by crisbeto** [comment]
You should be able to run 2.0.0-beta.12, but you should bear in mind that it won't have all of the features and fixes from the newer versions.
