### ISSUE TITLE
MatTooltip: Not Showing in Chrome, Works in FF

### ISSUE THREAD

**Issue by DragoTechInnovations** [angular/material2#9084]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Display as it should in FF

#### What is the current behavior?
Doesn't work ( / shows up) in Chrome

#### What are the steps to reproduce?
https://angular-material2-issue-hnpcuf.stackblitz.io
PS: Just for code, Material version is different and i cant find from where to change it.

#### What is the use-case or motivation for changing an existing behavior?
Workability

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
OS: ALL
Browser: Chrome/Chromium 63
node: 6.12.2
angular/core: 4.4.6
angular/material: 2.0.0-beta.12
typescript: 2.3.4

#### Is there anything else we should know?
Feel free to ask.

**Comment by josephperrott** [comment]
I am not seeing the issue myself in your link provided.  Additionally, you mention that you are seeing this in @angular/material@2.0.0-beta.12.  Are you seeing this still happening in the 5.0+ releases?

**Comment by DragoTechInnovations** [comment]
No. But that's the problem. I cant convert the project to Mat 5 because it would need ng5. My App makes a mess when converting to ng5.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via Plunker.
