### ISSUE TITLE
MatButton - implement "dense" variant

### ISSUE THREAD

**Issue by mstawick** [angular/material2#9099]
#### Bug, feature request, or proposal:
Feature request:
Implement dense variant for buttons, as per `Dense Button`
 in [Material Buttons Spec](https://material.io/guidelines/components/buttons.html#buttons-style)

#### What is the expected behavior?
When mouse + keyboard is used, buttons can be rendered smaller. This behaviour could be controlled by input flag, not to break any current layout and/or force the behaviour.

#### What is the current behavior?
Buttons are always rendered 36px high.

#### What are the steps to reproduce?
N/A

#### What is the use-case or motivation for changing an existing behavior?
PC-oriented websites

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
N/A

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/4597

**Comment by josephperrott** [comment]
Resolving as duplicate of #4597
