### ISSUE TITLE
Paginator length being set to page size instead of defined length (http pagination)

### ISSUE THREAD

**Issue by iget-master** [angular/material2#9105]
#### Bug, feature request, or proposal:

I'm trying to implement HTTP pagination as exemplified on documents with my own API.
The problem is that the total items count (length) is being set incorrectly!

My code follows exactly the same thing of the example.

#### What is the expected behavior?

It should just respect the value that I set. On my code, I use my API response (total) to set the paginators length, just as on the docs example.

#### What is the current behavior?

Looks like the length "blinks" from the total given by API to the current page length.

For example, if I load a resource that have a total of 9 items, and the page size is 5,
imediatelly after it load, I can see (very fast) the total of 9, with the next button enabled, then
it goes to 5 (the page length, not the total).

If in the same same, I set page size to 10, it shows the total of 9 (right, because the page 1 have exactly 9).

Looks like this is a behavior from non http pagination, where it try to paginate from the entire dataset.

#### What are the steps to reproduce?

Cannot provide a plunker right now, but the relevant code is:

```
ngAfterViewInit() {
    this.dataSource.sort = this.sort;
    this.dataSource.paginator = this.paginator;

    merge(this.sort.sortChange, this.paginator.page)
      .pipe(
        startWith({}),
        switchMap(() => {
            this.isLoadingResults = true;
            return this.modelProvider.list({page: this.paginator.pageIndex + 1, size: this.paginator.pageSize});
        }),
        map((collection: Collection<any>) => {
          this.isLoadingResults = false;
          this.resultsLength = collection.meta.total;

          return collection.data;
        }),
        catchError(() => {
          this.isLoadingResults = false;
          return observableOf([]);
        })
      ).subscribe(data => this.dataSource.data = data );
  }
ngAfterViewInit() {
    this.dataSource.sort = this.sort;
    this.dataSource.paginator = this.paginator;

    merge(this.sort.sortChange, this.paginator.page)
      .pipe(
        startWith({}),
        switchMap(() => {
            this.isLoadingResults = true;
            return this.modelProvider.list({page: this.paginator.pageIndex + 1, size: this.paginator.pageSize});
        }),
        map((collection: Collection<any>) => {
          this.isLoadingResults = false;
          this.resultsLength = collection.meta.total;

          return collection.data;
        }),
        catchError(() => {
          this.isLoadingResults = false;
          return observableOf([]);
        })
      ).subscribe(data => this.dataSource.data = data );
  }
```

And my paginator on view is defined:

```
<mat-paginator #paginator
               [length]="resultsLength"
               [pageSize]="5"
               [pageSizeOptions]="[5, 10, 20]"
               *ngIf="paginate">
</mat-paginator>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

The latest available versions, I've just installed everything.

**Comment by iget-master** [comment]
Not sure, but looks like the problem occurs here: (see line 223) https://github.com/angular/material2/blob/2b2eb185af1b67b04d66a49085d51772b58bc365/src/lib/table/table-data-source.ts#L219-L231

**Comment by julianobrasil** [comment]
There must be something with your setup. I have an app that I use for testing and it's working just fine (backend in java):

![image](https://user-images.githubusercontent.com/25405143/34315266-7fa1adf6-e764-11e7-8afb-91e6ea0b5384.png)

**Comment by iget-master** [comment]
@julianobrasil  I've checked many times my setup, didn't found anything wrong.

Following the `table-data-source.ts` logic:

The `_updateChangeSubscription()` method watches for `data`, `filter`, `sort` or `page` changes, then trigger the following map methods: `_filterData()`, `_orderData()` and `_pageData()`.

IMHO, the problem is that `_filterData()` don't cares about if I'm loading the data asynchronously, and overrides the length provided by my code using the `length` input on the paginator component.

**Comment by iget-master** [comment]
Found the reason.

In some doc example, I've found that I need to put this inside `ngAfterViewInit`.

    this.dataSource.sort = this.sort;
    this.dataSource.paginator = this.paginator;

On the http example, this lines doesn't exists. That's the reason. Since the pagination isn't controlled by the table itself, the paginator should not be associated to it (neither the sort).

I think that the docs should be clearer about this. Unfortunately I'm on vacation now and can't send a PR with a fix for the docs. I'll love if someone do it.

**Comment by julianobrasil** [comment]
Do you mean the example below? If the answer is yes... well, the example itself is working as expected. In this case the paginator is not bound to the datasource at all: it's just used fire the function (`this.paginator.page` observable) that grabs the desired data from the server and, after that, set `datasource.data`:

 ```ts
this.datasource.data = dataReceivedFromServer
```

![image](https://user-images.githubusercontent.com/25405143/34329338-3e8c530e-e8e3-11e7-85e7-43f51f9e4905.png)

**Comment by mhosman** [comment]
Same problem here!!! Any news????

**Comment by andrewseguin** [comment]
Can you re-open with a reproduction of your issue in stackblitz so we can investigate the issue?

**Comment by vicatcu** [comment]
I have to agree, I just went through the same experience / confusion as @iget-master with my own attempt to follow the examples. Taking this code out of ngAfterViewInit made it behave as I expected it to.

```
this.dataSource.sort = this.sort;
this.dataSource.paginator = this.paginator;
```

The docs could certainly explain this more clearly in the context of the HTTP example, imho...

**Comment by davidpelissier** [comment]
I have the same bug, and it's present on the official demo site.
Steps to reproduce : 
- https://material.angular.io/components/paginator/examples
- Fixe the length to 1000 for example
- Click next page multiple times
- Replace the length by a value < 1000

**Comment by narendrasinghrathore** [comment]
@andrewseguin When i move to next page and make a http call, paginator length is changed to length of table datasource.data
i am just updating the totalLength only if it's 0 .

`if(this.totalLength === 0){
            this.totalLength = data.total;
          }`

`<mat-paginator #paginator [length]="totalLength"
                 [pageSize]="limit"
                 [pageSizeOptions]="pageLimit"
                 (page)="changePage($event)">
  </mat-paginator>`

![error](https://user-images.githubusercontent.com/4208015/37764554-f88e5de4-2de7-11e8-86f3-7f3bffdcc240.gif)

**Comment by julianobrasil** [comment]
@narendrasinghrathore, do you think you'd be able to reproduce it using a stackblitz demo? I've never faced this issue in any projects of mine.

**Comment by narendrasinghrathore** [comment]
@julianobrasil  i can share my teamviewer to show you.
It's hard to setup with same scenario

**Comment by julianobrasil** [comment]
Not today. I have an appointment at the ophthalmologist right now and probably I won't be able to use a computer for the rest of the day after that.

**Comment by narendrasinghrathore** [comment]
@julianobrasil No issues, i will try reproduce online if possible or else please help out on teamviewer if you can.

**Comment by rakeshg2t** [comment]
It solves when I use a flag to *ngIf the page and toggle before and after the rest call executes. I showed a spinner when *ngIf is false.

TS : 
`...
 this.service
  .get('pools/calculations',{ pageNumber: page?page:this.page, pageSize: pSize?pSize:this.pSize })
  .then(data => {
    this.isLoadingResults=false;
    const ELEMENT_DATA =data.searchResults
    this.dataSource = new MatTableDataSource<Element>(ELEMENT_DATA);
    this.dataSource.paginator = this.paginator;
    if (data.pagingInfo && typeof data.pagingInfo == "object") {
      this.pageSize = data.pagingInfo.pageSize;
      this.listLength = data.pagingInfo.totalRows;
      this.pageNumber = data.pagingInfo.pageNumber;
      }
  })....
`
HTML: 
`....
<div class="loading-indicator">
    <mat-spinner *ngIf="isLoadingResults" class></mat-spinner>
</div>
....
<div class="example-container mat-elevation-z8" *ngIf="!isLoadingResults">
    <mat-table #table [dataSource]="dataSource">

        
        <ng-container matColumnDef="name">
            <mat-header-cell *matHeaderCellDef> Name </mat-header-cell>
            <mat-cell *matCellDef="let element"> {{element.poolName}} </mat-cell>
        </ng-container>

        <ng-container matColumnDef="symbol">
            <mat-header-cell *matHeaderCellDef> Updated </mat-header-cell>
            <mat-cell *matCellDef="let element"> {{element.symbol}} </mat-cell>
        </ng-container>

        <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
        <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>

    </mat-table>

    <mat-paginator #paginator [pageIndex]="pageNumber" [pageSize]="pageSize" [pageSizeOptions]="[5, 10, 20]" [showFirstLastButtons]="true" [length]="listLength" (page)="pageEvent($event)">
    </mat-paginator>
</div>
.....` 
But if I remove the ngIf the problem occours.

**Comment by ElanHasson** [comment]
I'm of the opinion the pager sound not behave like this. It "should just work".

**Comment by xxNoxiouSxx** [comment]
just ran into a version of this... my issue was when navigating away from the component containing the mat-table and navigating back, the length attribute was set to the number of records currently displayed... ie 10, 25, 50

I stored the length in a local variable after it is retrieved from the server side API.

Adding the following to my  ngAfterViewInit restored the length value in the paginator when the user navigates back to the component.

```
ngAfterViewInit(){
  this.dataSource.sort = this.sort;
  this.dataSource.paginator = this.paginator;
  setTimout(()=>this.paginator.length = this._localLengthVariable) 
}
```

**Comment by tibinthomas** [comment]
This a real issue. If we assign the pagination length with a number greater than the previously assigned value its working, but he logic fails.

**Comment by eplatzek** [comment]
Hey all. I've seen this bug for server side pagination.

The problem appears to be that when you are connecting a paginator to the MatTableDataSource, you are providing a way for the paginator to update the length property based on that data source. If you are also providing length as well, that length value will be overwritten when the data source gets updated.

A solution is to not connect the paginator to the MatTableDataSource. You do not need an ngIf*. If you do not connect the paginator to the datasource the only source that the paginator has to update the length is the properties you explicitly provide.

So your paginator will look something like this
```
<mat-paginator
  [length]="total$ | async"
  [pageSize]="pageSize$ | async"
  [pageSizeOptions]="pageSizeOptions"
  [pageIndex]="currentPage$ | async"
  (page)="onPaginateChange($event)">
</mat-paginator>
```
And your component will not have any reference to paginator or MatTableDataSource.

Note: In my use case, I'm using paginator without using a MatTable and instead iterating on a custom component.

**Comment by brandontg** [comment]
> Hey all. I've seen this bug for server side pagination.
> 
> The problem appears to be that when you are connecting a paginator to the MatTableDataSource, you are providing a way for the paginator to update the length property based on that data source. If you are also providing length as well, that length value will be overwritten when the data source gets updated.
> 
> A solution is to not connect the paginator to the MatTableDataSource. You do not need an ngIf*. If you do not connect the paginator to the datasource the only source that the paginator uses to update are the properties you explicitly provide.
> 
> So your paginator will look something like this
> 
> ```
> <mat-paginator
>   [length]="total$ | async"
>   [pageSize]="pageSize$ | async"
>   [pageSizeOptions]="pageSizeOptions"
>   [pageIndex]="currentPage$ | async"
>   (page)="onPaginateChange($event)">
> </mat-paginator>
> ```
> 
> And your component will not have any reference to paginator or MatTableDataSource.
> 
> Note: In my use case, I'm using paginator without using a MatTable and instead iterating on a custom component. If you are using MatTable then simply **don't** connect the paginator to the datasource and nix this code: `this.dataSource.paginator = this.paginator`

This solved my issue. I had no idea that assigning the paginator to the data source would overwrite the length I was providing. You would think it would be the other way around.
