### ISSUE TITLE
Dialog Focus Management broken

### ISSUE THREAD

**Issue by Hirse** [angular/material2#9107]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
> Tabbing through the elements of the dialog will keep focus inside of the dialog element, wrapping back to the first tabbable element when reaching the end of the tab sequence.
(see https://material.angular.io/components/dialog/overview#focus-management)

#### What is the current behavior?
Tab focus leaves the dialog.

#### What are the steps to reproduce?
https://material.angular.io/components/dialog/overview  
https://stackblitz.com/angular/nvvoleongadd

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current (or the one used for the Angular Material website).
Observed in Firefox and Chrome.

Firefox:
![2017-12-22_18-48-29](https://user-images.githubusercontent.com/2564094/34316395-7141310c-e749-11e7-8c8e-ab86a29ab9c6.png)

Chrome:
![2017-12-22_18-50-33](https://user-images.githubusercontent.com/2564094/34316394-6eee98fe-e749-11e7-9e78-e22074ac7c68.png)
It might not be easy to see, but the focus is on the first button in the header.

**Comment by crisbeto** [comment]
That's because we haven't set up our demo correctly. It was fixed as a part of https://github.com/angular/material2/pull/9021.

**Comment by Hirse** [comment]
The PR you reference was merged, but I can still observe this bug in both, the Website and the Stackblitz example.
![2017-12-23_11-24-33](https://user-images.githubusercontent.com/2564094/34322125-e3b6cea6-e7d3-11e7-8745-583190509175.png)

**Comment by crisbeto** [comment]
I don't remember whether we've deployed the site since then. You might be getting a cached version as well.

**Comment by Hirse** [comment]
The [Stackblitz](https://stackblitz.com/angular/nvvoleongadd?file=app%2Fdialog-overview-example-dialog.html) seems to have the changes from the PR.
https://github.com/angular/material2/blob/c3d7cd96de6f06e1530658e41d1e8aa3ba74805e/src/material-examples/dialog-overview/dialog-overview-example-dialog.html#L10

---

btw, if setting `cdkFocusInitial` is required for the focus trap to work, it should be included in the documentation.

**Comment by crisbeto** [comment]
It's not required for the focus trapping to work, but it can be used to tell the focus trap what to focus first.

**Comment by Hirse** [comment]
That attribute is the only thing that was added in the PR you linked (apart from the order of the buttons). 
If it is not required, why was that PR supposed to fix the problem I reported?

**Comment by crisbeto** [comment]
The `tabindex` was removed from the buttons as well. This is what breaks the focus trapping.

**Comment by Hirse** [comment]
I like that note.

The `tabindex` also has to be removed from the input to fix the focus:
https://github.com/angular/material2/blob/39805d46c36d7823246787fcb45bda32d1256c57/src/material-examples/dialog-overview/dialog-overview-example-dialog.html#L5

**Comment by walhow** [comment]
The stackblitz works for tabbing, but does not handle mouse clicks outside the modal. I really need this functionality, any ideas how to implement?
