### ISSUE TITLE
Tab label not visible when using purple-green prebuilt theme

### ISSUE THREAD

**Issue by noilly** [angular/material2#9112]
This is a: bug

Expected behaviour: Tab label is visible

Current behaviour: Tab label is not visible

See: https://angular-ptlkba.stackblitz.io

**Comment by crisbeto** [comment]
It's because you're using a dark theme on a light background. You can add the proper background either by putting your content inside a `mat-sidenav-container` or adding the `mat-app-background` class to your main container.
