### ISSUE TITLE
Paginator doesn't work in production

### ISSUE THREAD

**Issue by davenlin19** [angular/material2#9130]
#### Bug, feature request, or proposal:
Table paginator doesn't work in production

#### What is the expected behavior?
When the next chevron (or previous) is clicked, the table changes page

#### What is the current behavior?
It does nothing when I click on the next and previous buttons, even when I change the number of result, it doesn't work. But it works in local.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.1.2
Material 5.0.2
OS: Mac OS High Sierra
Typescript: 2.4.2
Browser: Chrome 63

**Comment by julianobrasil** [comment]
There's a chance it's relate to this bug: https://github.com/angular/material2/issues/9120#issuecomment-353972441

**Comment by davenlin19** [comment]
@julianobrasil I've tried to install uglify-es@3.2.2 but it didn't fix the problem :(

**Comment by julianobrasil** [comment]
Is it possible to provide a minimum working code at stackblitz showing the problem?

**Comment by davenlin19** [comment]
Sorry I didn't notice that the version of uglify-es used by angular-cli was still 3.3.2. By cleaning node_modules folder and reinstall node packages. It works ! 

Thank you very much !

**Comment by julianobrasil** [comment]
Good to hear it. I think you can close this now. The cli team is already working on a patch release.
