### ISSUE TITLE
Mat Accordian Lazy Render Expansion Panel

### ISSUE THREAD

**Issue by Stevechang84** [angular/material2#9135]
The newly added lazy render functionality of the expansion panel doesn't seem to render its content template.  In the provided example, I took the code from the docs and put it into a demo and the test div doesn't seem to show up.
https://stackblitz.com/edit/angular-jsmfjr-z1uw86?file=app/expansion-overview-example.html

**Comment by nicolasabric** [comment]
I have the same issue. After a bit of digging It seems that this feature is not yet part of any release. I guess will have to wait for 5.0.3.

**Comment by jelbourn** [comment]
Looks like the docs were accidentally updated before the feature was released. This will be available in 5.1

**Comment by sahandsamaneh** [comment]
I have the same issue.

**Comment by arat3091** [comment]
I think even in 5.1 its not working. When can we expect this to be fixed ?
