### ISSUE TITLE
[Tabs] 'animationDone' event is never fired

### ISSUE THREAD

**Issue by oktav777** [angular/material2#9139]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`animationDone` should fire when tab body has completed animation.

#### What is the current behavior?
`animationDone` event is never fired.

#### What are the steps to reproduce?
Open console and switch between tabs.
You will see that only the `selectedTabChange` is fired, but `animationDone` - never
https://stackblitz.com/edit/angular-4c9yjl

#### What is the use-case or motivation for changing an existing behavior?
This event is required to (re)intialize components that are dependent on visibility on the screen, because the content of tabs that are not selected is removed from DOM.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest `@angular/material` (5.1.2)

#### Is there anything else we should know?
The event is defined in [source code](https://github.com/angular/material2/blob/3a52624499b4d0a828dc40df1a87829305531a43/src/lib/tabs/tab-group.ts#L145) and is used in `_removeTabBodyWrapperHeight()` method, but the method itself is never called.

**Comment by crisbeto** [comment]
Seems to be fixed in master.

**Comment by oktav777** [comment]
@crisbeto can you point the line in source code?

**Comment by crisbeto** [comment]
Should be this one https://github.com/angular/material2/blob/master/src/lib/tabs/tab-group.ts#L286. I verified it by putting your example into our demo app.

**Comment by oktav777** [comment]
@crisbeto but the method itself is not called anywhere `_removeTabBodyWrapperHeight()`, how the event is emitted?

**Comment by crisbeto** [comment]
It is being called inside the view when a tab becomes active https://github.com/angular/material2/blob/master/src/lib/tabs/tab-group.html#L36.

**Comment by oktav777** [comment]
Ahh ok I got it! Waiting for release!

**Comment by Mario-Eis** [comment]
Issue seems to reappear in 5.0.4
