### ISSUE TITLE
md-input type="number" required does not update control validation state

### ISSUE THREAD

**Issue by blaugold** [angular/material2#914]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

A required but empty md-input field should turn the control invalid.
#### What is the current behavior?

Has the input been touched once it's `valid` prop stays `true` even if the the input is empty.
#### What are the steps to reproduce?

Enter a number and remove it again.
[Here is a plunker.](http://plnkr.co/edit/n3XmVBcBnqNquoVyBeu7?p=preview)
#### What is the use-case or motivation for changing an existing behavior?

Validating forms should be working.
#### Which versions of Angular, Material, OS, browsers are affected?

Tested with:
angular: '@2.0.0-rc.4'
forms: '@0.2.0'
material: '@2.0.0-alpha.6'
Chomre 52.0.2743.82

**Comment by tylermassey** [comment]
I've experienced this as well.

I think the issue is related to the value of a number input being `NaN` when the field is empty.

As a temporary workaround, I wrote a custom validator to handle this case. Here's an example: 

```
static requiredNumber(control: AbstractControl): {[key: string]: boolean} {
        return (isNaN(control.value) || (control.value == null)) ?
            {'required': true} :
            null;
    }
```

**Comment by Blaugold** [comment]
Ah yes, thanks for the hint.

**Comment by jelbourn** [comment]
Needs investigation

**Comment by philipooo** [comment]
This is how the Angular Team has fixed this for the NUMBER_VALUE_ACCESSOR.
https://github.com/angular/angular/commit/e69cb40de3547689b1cb06dc442ff47c84086844

**Comment by blaugold** [comment]
@philipooo Thas how i fixed it in my PR but in MdInput itself. NUMBER_VALUE_ACCESSOR is the right place to do it. This should resolve the issue, so I'm closing it.
