### ISSUE TITLE
The provided animation property "transform" is not a supported CSS property for animations

### ISSUE THREAD

**Issue by mistrynilesh** [angular/material2#9144]
#### What is the current behavior?
![capture](https://user-images.githubusercontent.com/3295257/34408146-199a95da-ebe8-11e7-842b-43c681c984f4.PNG)

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/animations": "^5.0.2",
    "@angular/cdk": "5.0.2",
    "@angular/common": "^5.0.2",
    "@angular/compiler": "^5.0.2",
    "@angular/compiler-cli": "^5.0.2",
    "@angular/core": "^5.0.2",
    "@angular/flex-layout": "2.0.0-beta.10-4905443",
    "@angular/forms": "^5.0.2",
    "@angular/http": "^5.0.2",
    "@angular/material": "5.0.2",
    "@angular/platform-browser": "^5.0.2",
    "@angular/platform-browser-dynamic": "^5.0.2",
    "@angular/platform-server": "^5.1.2",
    "@angular/router": "^5.0.2"  

#### Is there anything else we should know?
I am using angular universal - server side rendering.
The issue comes when I am a refreshing page in the browser. otherwise, it works fine.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
