### ISSUE TITLE
mat-icon not displaying in Android chrome browser

### ISSUE THREAD

**Issue by jayakrishna-v** [angular/material2#9145]
#### What is the current behavior?
![screenshot_2017-12-28-15-58-53-763_com android chrome](https://user-images.githubusercontent.com/34906838/34408295-15fed520-ebe9-11e7-8eb7-a979b80090f2.png)

#### What are the steps to reproduce?
Access the official link for mat-icon mentioned below in android chrome browser
https://material.angular.io/components/icon/overview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Android version : 7.1.1
Chrome version : 61.0.3163.98

**Comment by Chan4077** [comment]
Can you try clearing your cache as stated here => https://github.com/angular/material2/issues/7715#issuecomment-335835631

**Comment by jayakrishna-v** [comment]
Thanks for looking into this issue Chan. But we may need a fix for this as we cannot ask clients to force reload or to clear cache.

**Comment by DevVersion** [comment]
The cache issue is being tracked with https://github.com/angular/material2/issues/7660
