### ISSUE TITLE
mat-expansion-panel doesn't expand in prod build (after updating to material ^5.0.2)

### ISSUE THREAD

**Issue by YajneshRai** [angular/material2#9148]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-expansion-panel should expand/collapse on click.

#### What is the current behavior?
mat-expansion-panel doesn't open in prod build (works fine with dev build and ng serve).

#### What are the steps to reproduce?
- Use `"@angular/material": "^5.0.2"` and `"@angular/cdk": "^5.0.2"`  in package.json, install it.
- Have a html file containing mat-expansion-panel.
- Create a production build in cli using `ng build --prod` and run it, this should reproduce the issue.

#### What is the use-case or motivation for changing an existing behavior?
Has to be working in dev/prod builds.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Seems like issue did not exist in Material ^5.0.0-rc.1, until recently I updated to ^5.0.2.

#### Is there anything else we should know?
This was observed earlier too in #7172 
I also noticed that `mat-expanded` class in not being added, when click event is fired.
Not sure what change broke the feature in new update

**Comment by crisbeto** [comment]
Looks similar to https://github.com/angular/material2/issues/9120. Can you try updating to the 1.6.3 version of the CLI?

**Comment by YajneshRai** [comment]
@crisbeto: Thanks! Made my day!

**Comment by AneelaBrister** [comment]
I have @angular/cli as a devDependancy, so I'm not clear on why upgrading this would fix a problem in Prod? The behavior I'm seeing: 
- while running server as ng serve, the opened and closed events are properly received in the component class. 
- while running with prod and aot flags turned on, the opened and closed events are never received.
