### ISSUE TITLE
md-icon and md-sidenav are not loading correctly. 

### ISSUE THREAD

**Issue by mehran9** [angular/material2#915]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-sidenav and md-icon directives appear not be loading

#### What is the current behavior?

When attempting to load sidenav and icon packages via npm, peer dependency warnings were highlighted in terminal, notwithstanding that those packages had already been loaded. 

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?

Material2

#### Is there anything else we should know?

I'm an angular2 noob, I could be doing something really silly.

**Comment by SamiAl90** [comment]
> What is the expected behavior?

md-sidenav and md-icon directives appear not be loading

Could you describe a little more what the problem actually is? Sidenav and Material-Icons working properly here.

**Comment by jelbourn** [comment]
If I understand what you're saying, you're talking about the npm peer dependency errors. You can ignore those.
