### ISSUE TITLE
Selection lists list item misaligned

### ISSUE THREAD

**Issue by lennybr** [angular/material2#9156]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When using selection-type list, expect that left alignment is the same as a non selection-type list, without an additional 16px of padding.

#### What is the current behavior?
When using selection-type list, .mat-list-item-content-reverse is applied (flex-direction: row-reverse), but there is an extra left-padding of 16px that is left over. Without the reversal of flex-direction, the padding is correctly aligned.

#### What are the steps to reproduce?
https://stackblitz.com/angular/jdyoyxpmkng
Also present in the docs (https://material.angular.io/components/list/overview)

#### What is the use-case or motivation for changing an existing behavior?
Lists should all align for consistency.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/core 5.1.2 @angular/material 5.0.0-rc.3

#### Is there anything else we should know?
Potential fix is that `.mat-list-text {padding: 0 16px}` but when under `.mat-list-item-content-reverse .mat-list-text { padding: 0 16px 0 0;}`

Screenshot: https://snag.gy/WLCghp.jpg

**Comment by lennybr** [comment]
Thanks @DevVersion

**Comment by DevVersion** [comment]
No problem. Thanks for reporting this.
