### ISSUE TITLE
mat-select - Ability to hide the dropdown if the value is already selected

### ISSUE THREAD

**Issue by monsterwarrior** [angular/material2#9157]
#### Bug, feature request, or proposal:

Request: Ability to hide the dropdown if the value is already selected

#### What is the expected behavior?

Right now we have, once option selected we can  disable select option and individual option as well. Is there any way to hide the options once the option is selected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5

**Comment by julianobrasil** [comment]
Could you give more details? For example, why the disabled state is not enough? Is it the disabled styling?

Take a look at this demo: https://stackblitz.com/edit/angular-select-icon-hide-panel

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
