### ISSUE TITLE
Proposal: Disable tab-header pagination

### ISSUE THREAD

**Issue by tiaguinho** [angular/material2#9162]
tab-header automatic pagination is a great feature. But I think will be very good if we can disable that.
I'm currently working on a project where this feature breaks the layout when the tab has a scroll.

**Comment by tiaguinho** [comment]
Can I implement this and submit a PR?

**Comment by jelbourn** [comment]
@andrewseguin thoughts?

**Comment by andrewseguin** [comment]
I'm fine if we want to include this as part of the API, there's another issue open requesting this that has gotten enough traction https://github.com/angular/material2/issues/2236

Closing this as a duplicate but will welcome a PR that adds this
