### ISSUE TITLE
MD-Angular - Dropdown select options announcing as checked for screen readers

### ISSUE THREAD

**Issue by escetic** [angular/material2#9167]
#### Bug, feature request, or proposal:
We have a form with day, month, year date of birth inputs.  The month is a dropdown select, with January, February, March, etc.  This is the code snippet (below).  Using a screen reader (NVDA or JAWS, any browser), as you down arrow through each option, each month option announces as "January checked", "March checked", etc. , but this is a dropdown, not a checkbox or radio input.

```
<md-input-container class="md-block md-input-has-placeholder ng-animate md-input-invalid" md-no-float="" data-ng-animate="2">
<md-select tabindex="14" class="phx-perinfo1 ng-pristine md-no-asterisk ng-empty ng-invalid ng-invalid-required ng-valid-maxlength ng-touched" id="select_7" role="listbox" aria-disabled="false" aria-expanded="false" aria-invalid="true" aria-multiselectable="false" aria-required="true" aria-owns="select_container_8" aria-label="Date of Birth Month." name="dobmonth" required="" ng-focus="dmonth=true" md-no-asterisk="" ng-model="vm.profile.dob.month" placeholder="Month" ng-maxlength="2" ng-change="monthSelected(vm.profile.dob.month)">

<md-select-value class="md-select-value md-select-placeholder" id="select_value_label_0">
<span>Month</span>
<span class="md-select-icon" aria-hidden="true"></span>
</md-select-value></md-select>

<div aria-live="assertive" ng-focus="dmonth">
<div class="md-input-messages-animation ng-active" aria-hidden="false" aria-live="assertive" ng-show="loanappForm.dobmonth.$touched &amp;&amp; loanappForm.dobmonth.$invalid" ng-messages="loanappForm.dobmonth.$error">
<!-- ngMessage: required -->
<div class="md-input-message-animation ng-binding ng-scope ng-enter ng-enter-active" style="margin-top: 0px; opacity: 1; transition-property: all; transition-duration: 0.3s; transition-timing-function: linear;" ng-message="required">
<img class="error-icon" role="presentation" alt="error" src="/content/images/wrong.png">Error. Month is required
</div>
</div>
</div>

<select name="dobmonth" tabindex="-1" class="md-visually-hidden" aria-hidden="true">
<option class="ng-binding" aria-checked="false" ng-value="monthNumber">
									lapp.months.values.
</option><option aria-checked="false" selected="" ng-value="vm.profile.dob.month"></option>
</select>

</md-input-container>

```

**What is the expected behavior?**

Select dropdowns aren't something which should be announcing as "checked".  Options announce as selected (note that none of the options here should be marked as selected).  Radio buttons announce as checked.

**What is the current behavior?**

Select dropdown is announcing each option as checked.

**What are the steps to reproduce?**

Sorry, I cannot share the site.  I'm hoping someone can see from the code snippet above why the SELECT options are announcing as "checked", as if they were radio buttons.

**What is the use-case or motivation for changing an existing behavior?**

Announcing a dropdown option as "checked" is unexpected behavior and confusing.

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**

Will need to check this.   Assume the latest.  Assume IE, FF, Chrome.

**Is there anything else we should know?**

Thank you in advance.

**Comment by crisbeto** [comment]
This looks like an issue with AngularJS Material, [please post the issue there](https://github.com/angular/material/issues).
