### ISSUE TITLE
Disabled not honored in Reactive Form

### ISSUE THREAD

**Issue by critchie** [angular/material2#9168]
#### Bug
Disabled is ignored when setting on an input (matInput) form control on a reactive form.

#### What is the expected behavior?
Expect control to be disabled.

#### What is the current behavior?
Control is not disabled.

#### What are the steps to reproduce?
[StackBlitz](https://stackblitz.com/edit/material-2-no-disable)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest and greatest all around.

**Comment by mtrdp642** [comment]
The console in your StackBlitz warns about using the disabled attribute with reactive forms:

```
It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
      when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
      you. We recommend using this approach to avoid 'changed after checked' errors.
       
      Example: 
      form = new FormGroup({
        first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
        last: new FormControl('Drew', Validators.required)
      });
```

In your StackBlitz, if you change the email form control definition to ```email: [{ value: null, disabled: true }, [Validators.required, Validators.email]],```, you'll see that the control does get disabled.

**Comment by critchie** [comment]
Perfect. Obviously I completely missed that.
