### ISSUE TITLE
Allow Overriding animations

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/material2#9182]
#### Feature request

Allow overriding animations, i.e, in dialog slide from left or zoom out instead of slide from below or turn animation altogether
#### What is the expected behavior?
Animations should be overrideble  

#### What is the current behavior?
Animations are hard coded

#### What is the use-case or motivation for changing an existing behavior?
Cutomization

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

**Comment by donroyco** [comment]
Duplicate of #8857

**Comment by abdulkareemnalband** [comment]
sorry I couldn't find existing issue closing now
