### ISSUE TITLE
two-way-binding in production builds

### ISSUE THREAD

**Issue by naderafshari** [angular/material2#9184]
two way binding works for me in localhost mode but not in production mode!
If I don't use material then it works in production too

This don't work in production....

      <mat-form-field *ngIf="userInfo">
        <input matInput name="userInfo.lastName" [(ngModel)]="userInfo.lastName" placeholder="Last Name.."> 
      </mat-form-field>

This works in production...

      <input *ngIf="userInfo" [(ngModel)]="userInfo.lastName" placeholder="Last Name.."> 

**Angular CLI: 1.6.2
Node: 6.12.0
OS: linux x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.2
@angular/material: 5.0.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0**

Anyone has any ideas why production version doesn't work?
Thanks

**Comment by julianobrasil** [comment]
Upgrade angular-cli to 1.6.3. The version you're using has a bugged uglify-es.

**Comment by EddyChina** [comment]
@julianobrasil I got the same problem by using '@angular/cli 1.7.0'. It either doesn't work in production build by using 1.6.8.   How can I do?
