### ISSUE TITLE
[Paginator] Occasional transparent background

### ISSUE THREAD

**Issue by eTallang** [angular/material2#9187]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Consistent background color.

#### What is the current behavior?
In both our own application, and on the Angular Material page, the paginator seems to switch between having a transparent background and a white background:
![image](https://user-images.githubusercontent.com/24789715/34476978-f24ee1dc-ef95-11e7-80f7-86c912349988.png)

I guess issue [8454](https://github.com/angular/material2/issues/8454) is related and probably will fix this issue, however 8454 did not mention anything explicitly about the background, so I thought a track of this was appropriate.

#### What are the steps to reproduce?
Simply render a mat-paginator.

#### What is the use-case or motivation for changing an existing behavior?
Consistent default background color for mat-paginator

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 5.0.2
Angular 5.1.1

#### Is there anything else we should know?
No

**Comment by jelbourn** [comment]
@crisbeto does #8455 fix this?

**Comment by crisbeto** [comment]
Yes it does, the [paginator in the example](https://material.angular.io/components/paginator/overview) now has a background color as well.
