### ISSUE TITLE
<mat-list-item> with an <a> isn't clickable across 100% of the height

### ISSUE THREAD

**Issue by simeyla** [angular/material2#9188]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Using the suggested template you should be able to create a list item with an `<a>` tag and it should work wherever you click on the list item

#### What is the current behavior?
The `<a>` tag does not fill 100% of the width and height of the generated list item, so if you don't click exactly on the text then the href is not followed. Note: the ripple effect still occurs so the user expects something to happen but it doesn't.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-gvwngv

#### What is the use-case or motivation for changing an existing behavior?
Broken functionality according to sample code https://material.angular.io/components/list/overview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.1.2
Material 5.0.2

#### Is there anything else we should know?
No. Should just need css fixing for the `<a>` tag.

**Comment by Chan4077** [comment]
Alternatively, just use the `<a>` tag itself with the `[mat-list-item]` attribute:
```html
<mat-nav-list>
    <a mat-list-item href="https://google.com">
        <h3 matLine>Google</h3>
    </a>
    <a mat-list-item href="https://angular.io">
        <h3 matLine>Angular</h3>
    </a>
</mat-nav-list>
```
Here's an updated [demo](https://stackblitz.com/edit/angular-material2-issue-sbe2d4)

**Comment by jelbourn** [comment]
What @Chan4077 said. This is just the native behavior of the `<a>` element.

**Comment by simeyla** [comment]
@jelbourn @Chan4077 Sure, and that excuses bad sample code from Google?

This sample is based on the actual sample code provided. That's not good - especially since the ripple effect still takes place. Some people will get very confused by this.

PS. Thanks for the suggested fix :-)
