### ISSUE TITLE
GlobalPositionStrategy - Translate causes Bugs in Firefox for Select (Option) Element

### ISSUE THREAD

**Issue by ChristianBeilschmidt** [angular/material2#919]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

A html select element's options should be affected by the translation in Firefox.
#### What is the current behavior?

Firefox positions the options unaffected by the translation. This is due to a bug (https://bugzilla.mozilla.org/show_bug.cgi?id=455164) that is unfixed for 8 years.
#### What are the steps to reproduce?

Use a global position strategy (which uses translateX and Y) and place this snippet inside of it:
`<select><option>A</option><option>B</option>`
#### What is the use-case or motivation for changing an existing behavior?

The bug exists in Firefox for 8 years and it is unlikely that it will be fixed.
#### Which versions of Angular, Material, OS, browsers are affected?

RC4, Material Alpha 6, Windows, Firefox 46.0.1
#### Is there anything else we should know?

I see currently three options:
- find a hack that somehow makes the option appear at the correct place
- position the overlay without translate
- ignore Firefox

**Comment by jelbourn** [comment]
@crisbeto is this issue still valid?

**Comment by crisbeto** [comment]
It's not, we haven't been using transforms for positioning for a while now.
