### ISSUE TITLE
docs(readme): update stuff planned for Q1 2018

### ISSUE THREAD

**Issue by donroyco** [angular/material2#9192]
#### Bug, feature request, or proposal:

Proposal

#### What is the expected behavior?
Up to date content in readme file.

#### What is the current behavior?
The current [README.md](https://github.com/angular/material2/blob/master/README.md) on `master` has the 'High level stuff planned for Q4 2017 (October - December)' and should be updated to Quarter 1 of 2018.

#### What are the steps to reproduce?
Just visit the https://github.com/angular/material2 and read the *Project status*.

#### What is the use-case or motivation for changing an existing behavior?
Keeping people up to date with the plan(s) of adding or updating features.

#### Is there anything else we should know?
Happy New Year! 🎆

**Comment by benb7760** [comment]
related #8942 with PR #8966

**Comment by josephperrott** [comment]
Closed by #9315
