### ISSUE TITLE
Menu not closing when clicked outside

### ISSUE THREAD

**Issue by asharmaaiet1** [angular/material2#9193]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Menu should close when clicked outside.

#### What is the current behavior?
not closing when clicked outside

#### What are the steps to reproduce?
I implemented simple menu but that is not closed when i click outside menu.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "^4.4.6",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.4.6",
    "@angular/compiler": "^4.4.6",
    "@angular/core": "^4.4.6",
    "@angular/forms": "^4.4.6",
    "@angular/http": "^4.4.6",
    "@angular/material": "^2.0.0-beta.12",

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template (missing reproduction). Please file a new issue that follows the template, which gives the team the information needed to investigate.
