### ISSUE TITLE
(CDK): Not open for extension

### ISSUE THREAD

**Issue by ronaldmansveld** [angular/material2#9194]
#### Bug, feature request, or proposal:
Currently the classes in the CDK mark a lot of properties and methods as private, preventing subclassing in an efficient matter. If these properties and methods were marked as protected instead, developers can more easily extend these classes to add/modify behaviour.
For instance: in this case I need to extend the ConnectedPositionStrategy so the overlay position isn't based on the viewport, but on the boundingbox of a parent element. Easiest way to do this is to create a new strategy that extends the ConnectedPositionStrategy, takes an extra elementRef in the constructor, and overloads the apply method. However, because a lot is marked as private, this subclass has no access to those methods and properties, preventing this type of extension.

#### What is the expected behavior?
CDK classes should be open for extension

#### What is the current behavior?
CDK classes are not open for extension

#### What are the steps to reproduce?
Not applicable

#### What is the use-case or motivation for changing an existing behavior?
Classes should be open for extension (see https://en.wikipedia.org/wiki/Open/closed_principle )

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All Angular Material CDK versions

#### Is there anything else we should know?
I'm more than willing to do the refactoring and create a PR for this, but I want to check first if there's a specific reason why the classes are not open for extension.

**Comment by jelbourn** [comment]
In generally we try to be deliberate about what is meant to be extended vs. just used. Closing this issue since it's too broad. Feel free to open a new issue for specific places where you think the API should be changed.
