### ISSUE TITLE
@angular/cdk/testing not available in node_modules?

### ISSUE THREAD

**Issue by alexw10** [angular/material2#9196]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
It seems today the @angular/cdk/testing is not in the public npm node_modules when installing material2. Can you guys make this available?

#### What is the current behavior?
I currently cannot take advantage of the things in @angular/cdk/testing for my applications/libraries. 

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Allows the reuse of the testing things you guys already have created.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular/Material 5.0.2

**Comment by willshowell** [comment]
Related: https://github.com/angular/material2/issues/5803#issuecomment-323211124

**Comment by jelbourn** [comment]
What @willshowell said
