### ISSUE TITLE
Consuming material2

### ISSUE THREAD

**Issue by haarabi** [angular/material2#92]
Hi, knowing this package is in early stages, can you please provide steps on how we can consume material2 in ng2? maybe a hello world sample app?

**Comment by msegers** [comment]
Would be nice, Can't wait for alpha 0

**Comment by aberenyi** [comment]
I've opened an [issue](https://github.com/angular/material2/issues/91) for this like an hour ago. I guess these could me merged.

**Comment by jhades** [comment]
There's a demo app, have a look at some running instructions here -> https://github.com/angular/material2/blob/master/DEV_ENVIRONMENT.md

**Comment by BinaryLeopard** [comment]
Everything is fine until I run `ng build`, I receive the following exception:

```
...\LearnAngular\upstream> ng serve
Cannot find module 'ts-node/register'
Error: Cannot find module 'ts-node/register'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (...\LearnAngular\upstream\angular-cli-build.js:5:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

**Comment by gbataille** [comment]
Which version of node are you on?
I think I had that in 5.1 but it disappeared in 5.6
Might be the same issue

On Tuesday, 23 February 2016, BinaryLeopard <notifications@github.com>
wrote:

> Everything is fine until I run ng build, I receive the following
> exception:
>
> ...\LearnAngular\upstream> ng serve
> Cannot find module 'ts-node/register'
> Error: Cannot find module 'ts-node/register'
>     at Function.Module._resolveFilename (module.js:326:15)
>     at Function.Module._load (module.js:277:25)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (...\LearnAngular\upstream\angular-cli-build.js:5:1)
>     at Module._compile (module.js:398:26)
>     at Object.Module._extensions..js (module.js:405:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material2/issues/92#issuecomment-187451889>.
>


-- 

---
Gregory Bataille

**Comment by haarabi** [comment]
I'm using v5.3.0

**Comment by haarabi** [comment]
Got the build working; not sure what fixed it, apparently the `npm install` did run correctly the first time.

**Comment by jelbourn** [comment]
We'll publish to npm once the alpha.0 is ready. The announcement will probably be on Twitter, so stay tuned!
