### ISSUE TITLE
mat-select doesn't open.

### ISSUE THREAD

**Issue by bilenko-git** [angular/material2#9204]
Bug:
mat-select doesn't open. 
Demonstration - https://www.youtube.com/watch?v=hLCWMniUszg

    selector: "fr-input-select",
    template: 
        <mat-form-field>
            <mat-select class="fr-input-select"
                       [name]="md?.md?.name"
                       [placeholder]="md?.md?.caption"
                       [disabled]="disabled ? 'disabled': undefined"
                       [required]="validationRules?.required?.rule"
                       [(ngModel)]="selectedItem">
                <mat-option [value]=""></mat-option>
                <mat-option
                        class="fr-input-select__items"
                        *ngFor="let item of md?.md?.items"
                        [value]="item">
                    {{item}}
                </mat-option>
            </mat-select>
        </mat-form-field>

What is the expected behavior?
when I open the select don't see list. Only after other event.

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/animations": "^4.4.6",
"@angular/cdk": "^5.0.2",
"@angular/common": "^4.3.6",
"@angular/compiler": "^4.3.6",
"@angular/core": "^4.3.6",
"@angular/forms": "^4.3.6",
"@angular/http": "^4.3.6",
"@angular/material": "^5.0.2",
"@angular/platform-browser": "^4.3.6",
"@angular/platform-browser-dynamic": "^4.3.6",

Is there anything else we should know?
Building of component on the fly.

**Comment by crisbeto** [comment]
The select usually won't open if it doesn't have any options. Are you sure that anything is being rendered?

**Comment by bilenko-git** [comment]
@crisbeto sure i have options.
 
```
<mat-option  [value]=""></mat-option>

<mat-option class="fr-input-select__items" *ngFor="let item of md?.md?.items" [value]="item">{{item}}
</mat-option>
```
you can watch https://www.youtube.com/watch?v=hLCWMniUszg

**Comment by julianobrasil** [comment]
@bilenko-git, there are somethings you can check:

1. Have you double checked whether your angular version is correct (you need `@angular` >= 5.0.0 ` for @angular/material` 5.0.2 and maybe you're using an old or cached version)? Inspect it: `ng -v` (suposing you're using angular/cli)
2. Before you `npm install` your project (suposing you did it):
    2.1. Have you deleted `node_modules`?
    2.2. Have you deleted package-lock.json (if you have one)?
2. If you're using `angular/cli` and the video was recorded using a project built with `--prod`, also check whether you're using [angular/cli >= 1.6.3](https://github.com/angular/angular-cli/releases)

**Comment by crisbeto** [comment]
Closing since there's not much we can do without a repro case.
