### ISSUE TITLE
Where is <md-content> defined?

### ISSUE THREAD

**Issue by autopulous** [angular/material2#921]
#### Bug, feature request, or proposal:

Question, that may or may not result in a change...

#### What is the expected behavior?

md-content being recognized by my IDE JetBrains IDEA 2016.2

#### What is the current behavior?

JetBrains IDEA 2016.2 reports

Selector matches unknown element `md-content`

when I reference `md-content` in style sheets (`.scss`)

#### What are the steps to reproduce?

Add a md-content reference in a style sheet

#### What is the use-case or motivation for changing an existing behavior?

Presumably this is just a nit

#### Which versions of Angular, Material, OS, browsers are affected?

2.0.0-alpha.6-2

#### Is there anything else we should know?

I searched the repository for the location within the material code for a definition of the md-content selector and could not find one...

**Comment by m0t0r** [comment]
@autopulous `md-content` doesn't exist in Material2.

**Comment by Blaugold** [comment]
It is used in [sidenav.scss](https://github.com/angular/material2/blob/9a32489d1aca84afac48aae32fb62813cce2bc83/src/components/sidenav/sidenav.scss) and [sidenav-transitions.scss](https://github.com/angular/material2/blob/4bee1783b26831e99b4bc36e9977acc4b2d2fc24/src/components/sidenav/sidenav-transitions.scss), but I can confirm that in IntelliJ Idea it is not recognises as a selector. Using Go To > Declaration (cmd + b on osx) next to something like `md-sidenav`, which IntelliJ does recognise brings you to the component declaration. So I suspect the Angular plugin for JetBrains IDEs is aware of `selector` metadata but not the compiled css in the `styles`metadata.

**Comment by jelbourn** [comment]
This is not related to material; WebStorm / IJ don't recognize custom elements by default.

**Comment by autopulous** [comment]
@jelbourn - respectfully... IDEA 2016.2 recognizes many of the `md-` directives... when these are defined/declare within the material packages - for instance `md-toolbar` is recognized because `md-toolbar` is declared as a selector in the `toolbar.js` file - it would seem to me that since `md-toolbar` is recognized and `md-toolbar` is declared within the `"@angular2-material/toolbar": "2.0.0-alpha.6-2"` package it seem to follow that there may be a missing declaration for the `md-content` selector...

**Comment by vivekwisdom** [comment]
In `node_modules/@angular2-material` I don't see `md-content`.

Again in Wiki also it's not referenced. Maybe `md-content` is not included at all in material2.
