### ISSUE TITLE
Implement window breakpoints from Material guidelines

### ISSUE THREAD

**Issue by odahcam** [angular/material2#9212]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
That `BreakpointObserver` has all Material guidelines breakpoints.

#### What is the current behavior?
`BreakpointObserver` has the `handset` breakpoints and the `web` breakpoints (which isn't in the guidelines).

#### What is the use-case or motivation for changing an existing behavior?
Be true to the Material guidelines specs and improve usability of the lib by allowing the user to not have to write more `MediaMatcher` code (media queries by hand) to achieve something in the guidelines.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material ^5.0.0

#### Is there anything else we should know?

Maybe a usefull image.

![image](https://user-images.githubusercontent.com/3942006/34522336-4a7c99e2-f079-11e7-8473-522316c89a45.png)

So the breakpoints could be:

```javascript
Breakpoints += [ WindowXSmall, WindowSmall, WindowMedium, WindowLarge, WindowXLarge ]
```

**Comment by josephperrott** [comment]
These breakpoints would be great to add to the [breakpoints.ts](https://github.com/angular/material2/blob/master/src/cdk/layout/breakpoints.ts) file within `@angular/cdk/layout`.

**Comment by mackelito** [comment]
@josephperrott I see that they are in breakpoints.ts file but it would also be great to have it bettre explained in the docs :)

**Comment by odahcam** [comment]
As longs as this is closed, I think a new issue would be more appropriated. 😉

**Comment by mackelito** [comment]
Sure.. but before polluting with new issues I just wanted to check here first. 😁
