### ISSUE TITLE
fix(autocomplete): don't open panel for readonly inputs, even with keyboard

### ISSUE THREAD

**Issue by gogakoreli** [angular/material2#9227]
#### Bug, feature request, or proposal:
When I disable input inside autocomplete I can still open the panel when input has focus and I click the arrow buttons on my keyboard.
#7271 this pull request only fixed this issue for input focus, panel doesn't open if I click on the input with the mouse or change focus with tab, but still opens with arrow keys.

#### What is the expected behavior?
Autocomplete panel shouldn't open when input is readonly, even with the keyboard

#### What is the current behavior?
Autocomplete panel opens when input is readonly using keyboard arrows

#### What are the steps to reproduce?
[Autocomplete Stackblitz](https://stackblitz.com/angular/ynrnqrokppx?file=app%2Fautocomplete-overview-example.html), in this example add readonly to the input inside autocomplete, then focus the input with mouse click and click on the keyboard down arrow key ( ↓ ).

**Comment by julianobrasil** [comment]
Your stackblitz is using Material 5.0.0-rc3.

If you update it to Material 5.0.3, you'll noticed it doesn't happens anymore (the panel does not open neither for disabled nor for readonly inputs). It was fixed in PR #7271.
