### ISSUE TITLE
mat-select [disabled] does not like 0/1 - rest of the controls seem to be fine with it

### ISSUE THREAD

**Issue by JohnArrowwood** [angular/material2#9238]
Most of the other controls, like `<input>` will accept a value of `1/0` for disabled.  `<mat-select>` only wants `true/false`.

Came up because saving a boolean to MySQL saves the value as 1/0.  Feeding the value as returned from the API to the rest of my form elements worked fine, but the `<mat-select>` did not.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
