### ISSUE TITLE
Material Module Import

### ISSUE THREAD

**Issue by JoshWilliams92** [angular/material2#9246]
I have created an external material module with all necessary imports (exported as well from module) which doesn't register the components for each navigation link IF i import material into app.module. I have an external app-routing.module which works if I import the material module into the routing module. Not sure if this is a bug/glitch as it doesn't seem right but works if I import into the external routing module.

**Comment by jotatoledo** [comment]
- Use the issue template
- Add a minimal reproduction of your issue

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
