### ISSUE TITLE
Bug(mat-list-item): icon wrong position when a matLine is in ng-template

### ISSUE THREAD

**Issue by Doehl** [angular/material2#9249]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To correctly display icon and matLine when, matLine is inside a ng-template.

#### What is the current behavior?
The icon and matline are rendered wrong, when matLine is inside a ng-template.
The icon is displayed to the left, and the matLine is then displayed on top of the icon.

#### What are the steps to reproduce?
http://embed.plnkr.co/kdFlXNwg0JucHGrwB7b2/

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
5.0.3

**Comment by crisbeto** [comment]
It's because Angular looks for direct children [when projecting here](https://github.com/angular/material2/blob/master/src/lib/list/list-item.html#L10) and the line isn't a direct child. You can work around it by setting the `ngIf` on the line itself.

**Comment by jotatoledo** [comment]
Thats because `ng-template` generates a DOM element and only direct childrens are queried, if you want to group a set of DOM nodes in a [ngIf](url) condition I would suggest to use `ng-container` instead

https://plnkr.co/edit/TcH4b1JvqFlb0Wu0VPSK
