### ISSUE TITLE
Support for mat-dialog-footer

### ISSUE THREAD

**Issue by Karankang007** [angular/material2#9255]
#### Feature request:
Support mat-dialog-footer similar to mat-card-footer

#### What is the expected behavior?
mat-dialog-footer should be supported

#### What is the current behavior?
mat-dialog-footer is not supported

#### What is the use-case or motivation for changing an existing behavior?
Consistency between components

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: v5.1.1
Angular Material: v5.0.1

**Comment by Karankang007** [comment]
For now, workaround is:

```
.mat-dialog-container{
    padding-bottom: 0;
     &:last-child:not(.mat-dialog-footer) {
        padding-bottom: 24px;
    }
}
```

**Comment by jelbourn** [comment]
I think you're looking for `<mat-dialog-actions>`
