### ISSUE TITLE
md-spinner and md-progress-circle indeterminate are blinking

### ISSUE THREAD

**Issue by bennycooly** [angular/material2#926]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The spinner is supposed to have a smooth animation.

#### What is the current behavior?
Using the most recent commit, the progress spinner is blinking.

#### What are the steps to reproduce?
See the demo app:
https://material2-test.firebaseapp.com/progress-circle

Pull from the latest commit, and put a spinner/indeterminate circle into your app:
`<md-progress-circle mode="indeterminate"></md-progress-circle>`

or

`<md-spinner></md-spinner>`

#### What is the use-case or motivation for changing an existing behavior?
Fix the issue before it gets deployed.

#### Which versions of Angular, Material, OS, browsers are affected?
AngularJs 2: 2.0.0-rc.4
Angular 2 Material: Current version from git

#### Is there anything else we should know?
The progress-circle is working normally for version 2.0.0-alpha.6-2 so not exactly sure what is causing it right now. In fact, I'm not even sure if this is just a weird bug that'll get fixed with the next deployment but I just thought that you guys should know that it's happening.

Thanks!

**Comment by jelbourn** [comment]
Wow, that's pretty glaring. How did we not see this...
