### ISSUE TITLE
Slide-toggle styling is broken 

### ISSUE THREAD

**Issue by willwsharp** [angular/material2#9266]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The slide-toggle should look as expected

#### What is the current behavior?
The slide-toggle does not look as expected

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
https://stackblitz.com/edit/testing-slide-toggle

#### What is the use-case or motivation for changing an existing behavior?
The slide-toggle should definitely not look like that

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 5.0.3
Angular 5.0.0
Angular Animations 5.1.3

Not sure what other versions you need, they're in the stackblitz though.

**Comment by Chan4077** [comment]
That's because you're missing the theming. Add the following line to your `styles.css`:
```css
@import '~@angular/material/prebuilt-themes/indigo-pink.css';
```
[Updated demo](https://stackblitz.com/edit/testing-slide-toggle-e3eqak?file=styles.css)

**Comment by willwsharp** [comment]
Sorry about that.
