### ISSUE TITLE
expansion panel not initialized correctly when inside a tab group and not in first position

### ISSUE THREAD

**Issue by githubmonkey** [angular/material2#9270]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

all expansion panels should start closed, no matter which tab they are under

#### What is the current behavior?

the expansion panels in the first tab start closed as expected. However the panels in the second tabg start out partially opened. (The heading and toggle icon indicates a closed status but the content is visible.)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-btoxsy

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
(master *) ~/play$ npm list --depth=0
play@0.0.0 
├── @angular/animations@5.1.3
├── @angular/cdk@5.0.3
├── @angular/cli@1.6.3
├── UNMET PEER DEPENDENCY @angular/common@5.1.3
├── UNMET PEER DEPENDENCY @angular/compiler@5.1.3
├── @angular/compiler-cli@5.1.3
├── UNMET PEER DEPENDENCY @angular/core@5.1.3
├── @angular/flex-layout@2.0.0-beta.10-4905443
├── @angular/forms@5.1.3
├── @angular/http@5.1.3
├── @angular/language-service@5.1.3
├── @angular/material@5.0.3
├── @angular/platform-browser@5.1.3
├── @angular/platform-browser-dynamic@5.1.3
├── @angular/router@5.1.3
├── @types/jasmine@2.5.54
├── @types/jasminewd2@2.0.3
├── @types/node@6.0.96
├── angularfire2@5.0.0-rc.5-next
├── codelyzer@3.2.2
├── core-js@2.5.3
├── firebase@4.8.0
├── hammerjs@2.0.8
├── jasmine-core@2.6.4
├── jasmine-spec-reporter@4.1.1
├── karma@1.7.1
├── karma-chrome-launcher@2.1.1
├── karma-cli@1.0.1
├── karma-coverage-istanbul-reporter@1.3.3
├── karma-jasmine@1.1.1
├── karma-jasmine-html-reporter@0.2.2
├── ng2-img-cropper@0.9.0
├── protractor@5.1.2
├── rxjs@5.5.6
├── ts-node@3.2.2
├── tslint@5.7.0
├── typescript@2.4.2
└── zone.js@0.8.19

**Comment by julianobrasil** [comment]
Dupe: #5269
