### ISSUE TITLE
Unable to get the latest version 5.0.3  of Angular Material 

### ISSUE THREAD

**Issue by dgouissem** [angular/material2#9277]
Hello Team,

I'm trying to install to the latest  **5.0.3**  using the below commands 

`npm install --save @angular/material @angular/cdk`

or 

`npm install --save @angular/material@latest @angular/cdk@latest`

but in vain, every time i got the below version in the package.json:
"@angular/cdk": "^5.0.0-rc0" 
"@angular/material": "^5.0.0-rc0" 

Any idea how to get the latest one.

Thanks in advance.

Best regards,

**Comment by julianobrasil** [comment]
Have you `deleted package-lock.json` before `npm install`?

**Comment by dgouissem** [comment]
Nope, i deleted the **package-lock.json** file but it did not update to the lates version

thanks

**Comment by bettercalldough** [comment]
Have you rm -rf node_modules to remove the modules downloaded

**Comment by dgouissem** [comment]
same problem occurs when i delete the node_modules.

**Comment by dgouissem** [comment]
NB: The application is running on Anguar 5.0.0 version, do I need to upgrade to latest one?

**Comment by julianobrasil** [comment]
It looks like something in your setup. Take a look what happens in my notebook:

![image](https://media.giphy.com/media/3o751V97PSMBDkpy6I/giphy.gif)

My setup (`npm 5.6.0`):

```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.3
Node: 8.9.1
OS: win32 x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.3
@angular/cli: 1.6.3
@angular/material: 5.0.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

**Comment by andrewseguin** [comment]
Please refer all troubleshooting questions to our community at StackOverflow, Angular Material mailing lists, Gitter, etc. We try to keep our issues here only open for bugs and feature requests.
