### ISSUE TITLE
mat-select [disabled] should accept either true/false or 1/0

### ISSUE THREAD

**Issue by JohnArrowwood** [angular/material2#9280]
#### Bug, feature request, or proposal:

BUG

#### What is the expected behavior?

Consistency in the `[disabled]` flag between form elements.

#### What is the current behavior?

`<input>` accepts either `true`/`false` or `1`/`0`.  `<mat-select>` only accepts `true`/`false`.

#### What are the steps to reproduce?

* Create a value that represents the `disabled` state of controls.
* Create a form with every possible type of form control element, each controlling their `disabled` state from the value created above

* Set the value to `true` - all form elements should be disabled.
* Set the value to `1` - all form elements SHOULD be disabled.
* Set the value to `false` - all form elements should be enabled.
* Set the value to `0` - all form elements should be enabled - **NOTE: `<mat-select>` is NOT**

#### What is the use-case or motivation for changing an existing behavior?

When you have a MySQL backed data-store (and quite possibly others) and you have a boolean field, it is stored/retrieved as 1/0.  Some of the controls honor it, others don't.  This inconsistency can cause people to inadvertently inject bugs into their software without knowing it.

The system should work the same for all control types.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Not tested.  Effects latest.

**Comment by DevVersion** [comment]
Yeah our `disabledMixin` that is being used by most of the components is treating the `zero` value as `true`.

Since native inputs also support `0` and `1` as values for the `disabled` property, the mixin should handle that probably in the same way.

**Comment by DevVersion** [comment]
Just chatted about this with the team. We decided to not explicitly treat `0` as a falsy value for the `coerceBooleanAttribute` function, because it would be a **major breaking change**.

Also by looking at native elements, and how they treat zero in an attribute, zero doesn't have any effect as well (_which aligns with our decision_). 

I'm going to close this issue, but would be still happy to continue the discussion.
