### ISSUE TITLE
[Date Picker] Validation breaks when form field is not pristine

### ISSUE THREAD

**Issue by txinfo** [angular/material2#9281]
The use case is as follows:

- the date input is part of a form
- the date input is optional
- if a date is entered it needs to be entered in a valid format (defined in date adaptor)
- only want to label the field as invalid if there has input entered and it is invalid - if there is no text entered then it is marked as valid
- on a clean form everything works as it should - form is only valid when mandatory fields are entered
- modify date field - once a valid date is entered, the form is valid
- however, if the date input is removed (form field is blanked out), the date validation returns as failure when it should pass in this case
- currently do not seem to be able to get the raw text input value from the datepicker so even manually discerning between an empty form field and an invalid date is not possible

**Comment by jotatoledo** [comment]
Reproduction?

**Comment by txinfo** [comment]
https://stackblitz.com/edit/angular-hajfhp

**Comment by willshowell** [comment]
@txinfo try this

```ts
parse(value: any, parseFormat: string | string[]): Moment | null {
  return value ? moment(value, 'DD/MM/YYY', true) : null;
}
```

**Comment by txinfo** [comment]
@willshowell That fixed my issue. I checked the reference implementation of the MomentDateAdapter and it includes the value check / null return as in the code above so this was my issue and not a bug in the library. Apologies!
