### ISSUE TITLE
Can provide a border with the mat-form-field

### ISSUE THREAD

**Issue by smile2014** [angular/material2#9296]
https://stackblitz.com/edit/angular-pzgvcn

**Comment by deniscarvasilva** [comment]
`<div class="yourclass">
<mat-form-field>
  <input type="text" matInput placeholder="Price">
</mat-form-field>
</div>`

if you create the class in your css, maybe help you to make a border

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by smile2014** [comment]
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'form-field',
  template:`<div>
    <label>
      material2 input border
    </label>
    <div style="border:1px solid rgb(70, 68, 68);width:100%;height:37px" class="mat-form-field-flex">
        <ng-content></ng-content>
    </div>
</div>`,
  styleUrls: []
})
export class FormField implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

**Comment by smile2014** [comment]
@crisbeto
