### ISSUE TITLE
Text area should match material spec and have border

### ISSUE THREAD

**Issue by CDDelta** [angular/material2#9297]
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
Text area should have a border that matches the material spec.

#### What is the current behavior?
No border

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Match spec

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
https://material.io/guidelines/components/text-fields.html#text-fields-field-types
![Example](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B5ZSepuCX1xOS3ZTZld4c3JhUTQ/area2.png)

**Comment by ccstevenson** [comment]
@CDDelta Was this a legitimate issue? Just curious why this was closed when the spec still indicates that text areas should have a border.

**Comment by CDDelta** [comment]
It was for a while but a PR was already pending to implement this at the time, I think. This now works in 6.0.0.

**Comment by ccstevenson** [comment]
Great, thanks for the update.
