### ISSUE TITLE
TS syntax for string types for OneOf

### ISSUE THREAD

**Issue by a8775** [angular/material2#93]
TypeScript 1.8 is introducing a new syntax for string types:

https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#string-literal-types

eg.:

```TypeScript
interface AnimationOptions {
    deltaX: number;
    deltaY: number;
    easing: "ease-in" | "ease-out" | "ease-in-out";
}
```

This could provide or extend the OneOf annotation. 
Possibly some tools could infer more from this syntax as well. 

Current syntax is as follow (https://github.com/angular/material2/blob/master/src/components/sidenav/sidenav.ts):

```TypeScript
@Input() @OneOf(['over', 'push', 'side']) mode: string = 'over';
```
I think of something like:
```TypeScript
@Input() @OneOf() mode: 'over'|'push'|'side' = 'over';
```

or even NG M2 could infer from the type the OneOf annotation is expected:
```TypeScript
@Input() mode: 'over'|'push'|'side' = 'over';
```

**Comment by zoechi** [comment]
I assuem this needs an equivalent in JS and Dart.

**Comment by jelbourn** [comment]
Yeah, unfortunately there's no Dart equivalent to this syntax.
