### ISSUE TITLE
Ability to create additional color codes

### ISSUE THREAD

**Issue by alirizadikici** [angular/material2#9301]
#### Bug, feature request, or proposal:
Feature request/proposal

#### What is the expected behavior?
Providing more than 3 color codes.

#### What is the current behavior?
There are only 3 color codes:
Primary
Accent
Warn

#### What are the steps to reproduce?
N/A

#### What is the use-case or motivation for changing an existing behavior?
Other UI frameworks have more than 3 color codes available, but they are also limited to a predefined number. Being able to define custom color codes would serve the ease of use (and possibly some more superiority over other frameworks).

As an additional motivation, currently only way to achieve this functionality looks like changing the mixins in the _theming.scss file, which wouldn't be carried over between releases. So any customization would go in wains after updating the package.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
While defining the mixins the scss list type might be helpful as mentioned in the below link:
https://gist.github.com/jareware/4738651#5-the-list-data-type

**Comment by donroyco** [comment]
Related: #5152 and #6059

**Comment by jelbourn** [comment]
This isn't something that we plan to add any time soon; it's something we will revisit when we're able to switch to CSS variables (when we can drop IE11).

**Comment by alirizadikici** [comment]
Thank you @donroyco @andrewseguin @jelbourn 

I have crafted a very simple solution and also shared it at the below stackblitz link:
[Solution](https://stackblitz.com/edit/angular-material2-issue-uvnnl8)

[https://stackblitz.com/edit/angular-material2-issue-uvnnl8](url)

**Comment by Bjeaurn** [comment]
@alirizadikici I've checked out your stackblitz to see what you were getting at, but I'm unable to figure out what you exactly did that's supposed to help in being able to differently style certain elements according to the material template?

**Comment by shiamalon** [comment]
> @alirizadikici I've checked out your stackblitz to see what you were getting at, but I'm unable to figure out what you exactly did that's supposed to help in being able to differently style certain elements according to the material template?

I think he is redefining the mat.light-theme function to return more colors. But then you need to go over all the components (or at least the ones you need) and refactor to also use the new colors

**Comment by alirizadikici** [comment]
@shiamalon you actually got the idea and the pain point.
When using Bootstrap 4 it is very easy to create the color codes and they are available all around, on all the components, backgrounds, borders etc. This is the main reason for the feature request.
