### ISSUE TITLE
bug(overlay): overlays are sometimes blurred in Chrome

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#932]
I think you should change the text to "Use your eye glasses to see tooltips"

![image](https://cloud.githubusercontent.com/assets/7827225/17250330/1ebac61a-55a4-11e6-9fb1-6d81f3492ad3.png)

PS: My chrome zoom is set to 100%

**Comment by rockmacaca** [comment]
+1

This is because the transforms on the parent `.md-overlay` are not integers, any way those can be rounded to the nearest pixel?

**Comment by ivoviz** [comment]
Indeed, it would be nice to have them rounded.

**Comment by robertmesserle** [comment]
@zigzag95 Are there any specific steps or browser requirements to reproduce this?

**Comment by robertmesserle** [comment]
Actually, I we were able to recreate it only when using a Macbook Pro with a non-retina display on Chrome.  Let me know if this happens under different circumstances as well.

**Comment by rockmacaca** [comment]
ChromeOS (I'm going to assume that will include Linux) also has the issue. Can test on Windows soon.

**Comment by robertmesserle** [comment]
Ah, okay.  We tested on Linux and were not able to recreate it so far.  Haven't checked Windows yet.

**Comment by ivoviz** [comment]
@robertmesserle Although I've tested with the menu component, both Windows and Linux have this issue. I would assume the amount of blur also varies with ppi.

**Comment by robertmesserle** [comment]
Yea, it should impact anything built on top of Overlay (ie. anything floating).

Some notes:
- Rounding pixels values should fix **some** use-cases, but not all.
- Percent-based translation will still cause blurring with no easy workarounds (at least not that we've found yet).

**Comment by gfaceless** [comment]
@robertmesserle Since currently `transform` is used only for [overlay centering](https://github.com/angular/material2/blob/2.0.0-alpha.8/src/lib/core/overlay/position/global-position-strategy.ts#L70-L86), maybe other centering technique should be used instead.

Getting rid of `transform` could also make animation more flexible

**Comment by jelbourn** [comment]
Summing up status on this so far: this is caused by subpixel rendering in some browsers. Solution is to always round the transform values for overlay positions.

**Comment by jelbourn** [comment]
We should try out this trick with `calc`:
http://stackoverflow.com/questions/39099656/blurry-text-when-using-translatex-translatey-in-percentage-on-chrome

**Comment by quanterion** [comment]
I think it may work for even numbers of width and height only

**Comment by rockmacaca** [comment]
@jelbourn Some warning about using `calc` there, IE/Edge [can't animate properties with it](https://connect.microsoft.com/IE/feedback/details/733978/css-animation-dont-accept-calc-as-property-values). That won't be an issue though if the `.md-overlay`'s transform isn't being animated anyway.

**Comment by jelbourn** [comment]
@crisbeto for connected position strategy, this should be as straightforward as calling `Math.round` on the translate values. For global position strategy, we may need to `getBoundingClientRect` after applying the percent translates and then reapply the rounded values (unless we can find a cleaner approach).
