### ISSUE TITLE
[Tabs] 'animationDone' event is never fired

### ISSUE THREAD

**Issue by Mario-Eis** [angular/material2#9322]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
animationDone should fire when tab body has completed animation.

#### What is the current behavior?
animationDone event is never fired.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-4c9yjl-kpfmev

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 5.0.4 (worked fine in 5.0.3)

#### Is there anything else we should know?
related to #9139 and #5238

**Comment by DevVersion** [comment]
The feature hasn't been released yet.
