### ISSUE TITLE
Peer dependency version of Angular is too specific

### ISSUE THREAD

**Issue by justinlee0777** [angular/material2#9328]
Will Angular Material's dependency on Angular be updated to be compatible with release 5.2.0? My team's build pipeline does a WhiteSource scan to validate its peer dependencies. Our current solution, for now, would be to lock our Angular dependency to 5.1.3.

**Comment by jelbourn** [comment]
The peer dependency version _should_ be `^5.0.0`. This bug comes from using the actual version we want to install as the peerDep, which should not be the case.

**Comment by justinlee0777** [comment]
Thanks guys!
