### ISSUE TITLE
Expansion panel should jump to the panel header when next/previous button is clicked

### ISSUE THREAD

**Issue by g-sari** [angular/material2#9337]
#### Bug:
Currently if you have a large content inside of an expansion panel which overflows the page size in height, and when you click on the next/previous button, the next/previous panel is opened right in the middle or where you currently are. You don't know which panel is currently opened.

#### What is the expected behavior?
It should jump to the panel header when next/previous button is clicked.

#### What is the current behavior?
The next/previous panel is opened from the coordinates of your current view points.

#### What are the steps to reproduce?
1. Scroll down
2. Click on the next button
3. The next panel is opened
4. You don't know which panel is exactly opened
5. You need to scroll up to the panel's header to see it (Destination Panel)

[https://stackblitz.com/edit/angular-hrwk2j](https://stackblitz.com/edit/angular-hrwk2j)

#### What is the use-case or motivation for changing an existing behavior?
Users are confused because they don't know which panel is currently opened.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
5.0.4

**Comment by josephperrott** [comment]
This is working as expected as the expansion panel component does not control the scrolling position of the page.

Since you are managing which panel is being opened from other panels, you will need to set the scroll position of the page manually based on the which panel is being opened.

**Comment by rafszul** [comment]
@g-sari did you manage to find a way of making this work?
