### ISSUE TITLE
NVDA Modifier key (insert) with left/right arrow keys are acceptable for navigating the Menu bar 

### ISSUE THREAD

**Issue by Techieegirl** [angular/material2#9343]
Hi there,

We have a mega menu bar like below. We know the keyboard interactions to navigate in between mega menu items is left/right arrow keys. But this is not working when Screen Reader is On. We have to use the Modifier key (insert) plus left/right arrow keys to move in between. Without screen reader, it is working fine by only using the arrow keys.

![image](https://user-images.githubusercontent.com/33324995/34846213-6fba4ee4-f6e5-11e7-997c-f04a339ae5c5.png)

Just need to know guys, if this behavior is acceptable. Dont know, if the screen reader users are  aware of that and already using in this way.

Any Suggestions??

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
