### ISSUE TITLE
Request : card with flip , collapsible list(menu) component / directive

### ISSUE THREAD

**Issue by soorireddy** [angular/material2#935]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by soorireddy** [comment]
expando option

**Comment by adrm** [comment]
As per material design spec, cards do not flip: https://material.google.com/components/cards.html#cards-behavior

So I don't think that behavior will be ever implemented here.
