### ISSUE TITLE
Class for matInput local variable loaded by template reference is ElementRef and not MatInput

### ISSUE THREAD

**Issue by eliasgago** [angular/material2#9350]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
@ViewChild(MatInput) myInput1: MatInput;
@ViewChild('myInput') myInput2: MatInput; 

Both elements should be an instance of type MatInput class.

#### What is the current behavior?
When I load the local variable of type MatInput with @ViewChild using the name of the class in my component I get a reference of type MatInput correctly (myInput1). However, if I load it using the template variable reference, I obtain an object of type ElementRef (myInput2).

#### What are the steps to reproduce?
Here is a stackblitz example showing that behaviour: https://stackblitz.com/edit/ng-mat-input-loaded-by-class-or-reference

#### Is there anything else we should know?
@ViewChild('myInput', {read: MatInput}) myInput2: MatInput; 
For my solution, this works also correctly.

**Comment by josephperrott** [comment]
This is working as expected.  In your template you are only creating a template ref variable on the input.  

Use the export alias from `MatInput` in your template ref to access the expected `MatInput` instance: 

```
<input matInput #myInput="matInput">
```

**Comment by eliasgago** [comment]
Ok, thanks!
