### ISSUE TITLE
CdkConnectedOverlay does not reposition if its overlay origin changes

### ISSUE THREAD

**Issue by simonspoerri** [angular/material2#9353]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
A connected overlay should reposition itself to the connected overlay origin when the overlay origin changed after the connected overlay was first displayed.

#### What is the current behavior?
The connected overlay does not reposition itself when its overlay origin changes, even if the overlay is detached before the origin changes and reattached after the origin has changed

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-9vet83?file=app%2Fapp.component.html

#### What is the use-case or motivation for changing an existing behavior?
A connected overlay could be reused for multiple overlay origins.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/cdk: 5.0.4

#### Is there anything else we should know?
The `CdkConnectedOverlay` directive seems to only create a new overlay once, unless the overlay is completely destroyed. Listening to changes on the overlay origin and recreating the positioning strategy to connect to the new origin would probably solve the problem.

I can try to create a PR if this would be of any help.

**Comment by VirajNimbalkar** [comment]
Just want to add here, I have extended MatSelect and customized scss and html , example/code is working fine. but what I observed, when I resize browser , it still uses same top, left and width even though source readjusted based on layout/screen resize.
