### ISSUE TITLE
MAT_DIALOG_DEFAULT_OPTIONS as part of public-api

### ISSUE THREAD

**Issue by alexshakura** [angular/material2#9354]
#### Bug, feature request, or proposal:
Bug 

#### What is the expected behavior?
Import `MAT_DIALOG_DEFAULT_OPTIONS` and use it in module providers 

#### What is the current behavior?
Can't import MAT_DIALOG_DEFAULT_OPTIONS from `@angular/material`. Also can't find a type for it in public-api

#### What are the steps to reproduce?
Easy to reproduce, just try to import it anywhere

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.13, Material 5.0.3, Typescript: 2.4.2
OS: Ubuntu 17.04

#### Is there anything else we should know?

**Comment by jotatoledo** [comment]
Seems to be solved in the latest release, `MatDialogConfig` can be imported from the normal entry point and is part of the public api in the dialog module. See [here](https://github.com/angular/material2/blob/master/src/lib/dialog/public-api.ts#L13)

**Comment by alexshakura** [comment]
@jotatoledo  Yes, `MatDialogConfig` is here but `MAT_DIALOG_DEFAULT_OPTIONS` i.e. Injection Token isn't. I also took a look into build sources and didn't found it

**Comment by crisbeto** [comment]
The `MAT_DIALOG_DEFAULT_OPTIONS` seems to be exported correctly. You'll have to wait until the changes are released.

**Comment by zijianhuang** [comment]
as of 5.1.0 burlap-bezel (2018-01-17), MAT_DIALOG_DEFAULT_OPTIONS is still not there, though the tutorial mentions it.

**Comment by tomasznastaly** [comment]
anything changed?
