### ISSUE TITLE
Stepper: Go to next step using enter key

### ISSUE THREAD

**Issue by wxlittle** [angular/material2#9356]
#### Bug, feature request, or proposal:
I would like to know if it is possible to use enter key to go to next step & submit form.

#### What is the expected behavior?
Fill the step, press enter, go to next step
Complete all steps, press enter, submit the form.

#### What is the current behavior?
https://stackblitz.com/angular/vnqarakmxkx
When I filled the step 1, pressed enter, stepper navigated to 2nd step.
When I filled the step 2, pressed enter, stepper navigated back to 1st step.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by DevVersion** [comment]
That's possible. By default, both buttons in the second step are `submit` buttons. If you set `type="button"` on the back button, the next button will be triggered on enter press.

```html
<button type="button" mat-button matStepperPrevious>Back</button>
<button type="submit" mat-button matStepperNext>Next</button>
```

I think it would make sense to always treat `matStepperPrevious` as normal buttons, and always set `type="submit"` for buttons with `matStepperNext`.

**Comment by wxlittle** [comment]
Thanks @DevVersion
The Enter key works perfectly after adding button type.
