### ISSUE TITLE
@angular/forms 0.1.0 or 0.2.0?

### ISSUE THREAD

**Issue by shotleybuilder** [angular/material2#936]
#### Bug, feature request, or proposal:

npm complains of unmet peer dependency if @angular/forms 0.2.0 is installed
This doesn't affect build but someone has difficulties with heroku see here

https://groups.google.com/forum/#!topic/angular-material2/CqKY2tcNZqQ 

#### What is the expected behavior?

I've patched package.json in slide-toggle, radio, input and checkbox with 
`"@angular/forms": "^0.2.0"`

And npm stops complaining

#### What is the current behavior?

I think these npm messages confuse because its not clear if they are important

Perhaps a clarification of whether forms 0.2.0 is ok?

**Comment by kara** [comment]
@shotleybuilder  When alpha.6 came out, angular core was still on RC.3, with forms 0.1.0.  In master, we've updated to RC.4 and forms 0.2.0, so as soon as alpha.7 comes out, these peer dependency errors will go away.

**Comment by michaelb-01** [comment]
Great news! Do you know when alpha.7 will be released?

**Comment by kara** [comment]
When it's ready :)

**Comment by finalxcode** [comment]
{
  "name": "my-project",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "postinstall": "typings install",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "^2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.2",
    "@angular2-material/button": "^2.0.0-alpha.6",
    "@angular2-material/card": "^2.0.0-alpha.6",
    "@angular2-material/core": "^2.0.0-alpha.6",
    "es6-shim": "0.35.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "^5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "angular-cli": "1.0.0-beta.10",
    "codelyzer": "0.0.20",
    "ember-cli-inject-live-reload": "1.4.0",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "protractor": "3.3.0",
    "ts-node": "0.5.5",
    "tslint": "3.11.0",
    "typescript": "1.8.10",
    "typings": "1.3.1"
  }
}
now it's time to modify it? as follows:
{
  "name": "my-project",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "postinstall": "typings install",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "^2.0.0-rc.3",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/router": "3.0.0-beta.2",
    "@angular2-material/button": "^2.0.0-alpha.6",
    "@angular2-material/card": "^2.0.0-alpha.6",
    "@angular2-material/core": "^2.0.0-alpha.6",
    "es6-shim": "0.35.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "^5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "angular-cli": "1.0.0-beta.10",
    "codelyzer": "0.0.20",
    "ember-cli-inject-live-reload": "1.4.0",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "protractor": "3.3.0",
    "ts-node": "0.5.5",
    "tslint": "3.11.0",
    "typescript": "1.8.10",
    "typings": "1.3.1"
  }
}
it's right?
