### ISSUE TITLE
Button docs example differs from specification

### ISSUE THREAD

**Issue by kiwikern** [angular/material2#9360]
#### Bug, feature request, or proposal:
Docs bug

#### What is the expected behavior?
Per specification, FABs should have the accent color if no color attribute is given. Embedded example in the docs shows the _Basic FAB_ in white.
Buttons example should look the same in [stackblitz ](https://stackblitz.com/angular/byxgxvqbolg)and the [embedded docs version](https://material.angular.io/components/button/examples).

#### What is the current behavior?
* **On stackblitz**: FAB button without a color attribute is in the accent color as specified. 
![image](https://user-images.githubusercontent.com/2671139/34895166-c3ed8940-f7e4-11e7-90af-4dfda0522929.png)
* **In docs**: FAB button without a color attribute has no background. (Basic).
![image](https://user-images.githubusercontent.com/2671139/34895154-b91d3b28-f7e4-11e7-97bc-df50470943a7.png)

**Comment by ravishivt** [comment]
Same issue for my local project.  My fab buttons have no color attribute and in non-prod builds, the buttons are correctly styled with accent palette.  But during angular-cli production builds, the fab buttons have no default color.

**Comment by DevVersion** [comment]
I'm looking into this. It looks like something in the production pipeline of the Angular CLI removes some necessary code (looks like the build-optimizer in combination with uglify)

_with build-optimizer disabled_
![image](https://user-images.githubusercontent.com/4987015/34905474-a595eed6-f859-11e7-9863-20d687ba4f0b.png)

__with build-optimizer enabled_
![image](https://user-images.githubusercontent.com/4987015/34905476-a9cb0ab8-f859-11e7-9feb-76fed96d5a35.png)
