### ISSUE TITLE
Can't bind to 'matRippleDisabled' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by mat-luc** [angular/material2#9368]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Should bind to div

#### What is the current behavior?

Can't bind to 'matRippleDisabled' since it isn't a known property of 'div'. ("tRipple class="mat-button-ripple" [class.mat-button-ripple-round]="_isRoundButton || _isIconButton" [ERROR ->][matRippleDisabled]="_isRippleDisabled()" [matRippleCentered]="_isIconButton" [matRippleTrigger]="_ge"): ng:///AppModule/MatButton.html@0:172
Can't bind to 'matRippleCentered' since it isn't a known property of 'div'. ("at-button-ripple-round]="_isRoundButton || _isIconButton" [matRippleDisabled]="_isRippleDisabled()" [ERROR ->][matRippleCentered]="_isIconButton" [matRippleTrigger]="_getHostElement()"></div><div class="mat-butt"): ng:///AppModule/MatButton.html@0:214
Can't bind to 'matRippleTrigger' since it isn't a known property of 'div'. ("ton || _isIconButton" [matRippleDisabled]="_isRippleDisabled()" [matRippleCentered]="_isIconButton" [ERROR ->][matRippleTrigger]="_getHostElement()"></div><div class="mat-button-focus-overlay"></div>"): ng:///AppModule/MatButton.html@0:250

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.4",
    "@angular/common": "^5.1.3",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.2.0",
    "@angular/flex-layout": "^2.0.0-beta.12",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.4",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "angular2-jwt": "^0.2.3",
    "core-js": "^2.4.1",
    "primeng": "^5.0.2",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"

**Comment by mat-luc** [comment]
Can't bind to 'matRippleDisabled' since it isn't a known property of 'div'. ("tRipple class="mat-button-ripple" [class.mat-button-ripple-round]="_isRoundButton || _isIconButton" [ERROR ->][matRippleDisabled]="_isRippleDisabled()" [matRippleCentered]="_isIconButton" [matRippleTrigger]="_ge"): ng:///AppModule/MatButton.html@0:172
Can't bind to 'matRippleCentered' since it isn't a known property of 'div'. ("at-button-ripple-round]="_isRoundButton || _isIconButton" [matRippleDisabled]="_isRippleDisabled()" [ERROR ->][matRippleCentered]="_isIconButton" [matRippleTrigger]="_getHostElement()"></div><div class="mat-butt"): ng:///AppModule/MatButton.html@0:214
Can't bind to 'matRippleTrigger' since it isn't a known property of 'div'. ("ton || _isIconButton" [matRippleDisabled]="_isRippleDisabled()" [matRippleCentered]="_isIconButton" [ERROR ->][matRippleTrigger]="_getHostElement()"></div><div class="mat-button-focus-overlay"></div>"): ng:///AppModule/MatButton.html@0:250

**Comment by benb7760** [comment]
@mat-luc you most likely haven't imported MatRippleModule

**Comment by mat-luc** [comment]
i did not import MatRippleModule. Thank you so much for pointed out.

**Comment by mat-luc** [comment]
I imported MatRippleModule, now i got new error,
Unexpected module 'MatRippleModule' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.
I can't find that module in node-modules
Please help
Thank you

**Comment by emaillenin** [comment]
@mat-luc to resolve the new error, add the module to `imports` instead of `declarations`. More details on https://stackoverflow.com/questions/45032043/uncaught-error-unexpected-module-formsmodule-declared-by-the-module-appmodul
