### ISSUE TITLE
peerDependencies don't allow Angular 5.2

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/material2#9372]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
Current `peerDependencies` only allow Angular 5.1 : 
```
"@angular/core": "~5.1.1",
"@angular/common": "~5.1.1"
```
So it produces a warning when installing Material with Angular 5.2.

## Expected behavior
`peerDependencies` should allow current patch and minor versions of Angular : 
```
"@angular/core": "^5.1.1",
"@angular/common": "^5.1.1"
```

## Minimal reproduction of the problem with instructions
```
npm install @angular/cli -g
ng new myapp
cd myapp
npm install @angular/{cdk,material}
```

## What is the motivation / use case for changing the behavior?
Aren't Material releases supposed to be in sync with Angular ones now ?

**Comment by cyrilletuzi** [comment]
Trying to do a PR, but can't find the source. The [build-config.js](https://github.com/angular/material2/blob/master/build-config.js) seems to say `^5.0.0` but it's not what is present in final `package.json`.

**Comment by DevVersion** [comment]
Yeah, we fixed this a few hours ago (https://github.com/angular/material2/commit/7187670d14e0675e370c859d2b326d7a570c3920). It's just not released yet.
