### ISSUE TITLE
Why is the date in datepicker angular showing the last day?

### ISSUE THREAD

**Issue by tapinambur0508** [angular/material2#9377]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
The date is not valid

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5

Ubuntu Chrome 63
Ubuntu FireFox 58

#### Is there anything else we should know?
I use datepicker c angular material. Here's the code:
```
<td [formGroup]="item">
 <div class="input-group">
  <div class="input-group-addon">
   <mat-datepicker-toggle mdSuffix [for]="picker"></mat-datepicker-toggle>
   <mat-datepicker #picker></mat-datepicker>
  </div>
  <input class="form-control" [matDatepicker]="picker" placeholder="Date" formControlName="date">
 </div>
</td>
```
Datapicker is in the form that sends it to the server when it is sent.

But the problem is that the values are transmitted over the last day.

For example, I chose 1/18/2018, but sent to the server 2018-01-17T22: 00: 00.000Z.

It's strange that the angular pipe for date converts the date correctly, but before displaying it, I have a request on the server for grouping by the month and the first day of the new month falls on the last day of the previous one.

Thank you.

**Comment by julianobrasil** [comment]
You're sending to the server the UTC date/time (UTC is the equivalent time of your time in GMT regions). For example, here where I live I'm 2 hours after GMT time (GMT-0200). Write now, the following code:

```ts
    const d = new Date();
    const utcD = JSON.stringify(d);
    console.log(`Local Time: ${d}`);
    console.log(`UTC time: ${utcD}`);
``` 

gives me the following output:

```
Local Time: Sat Jan 13 2018 12:26:36 GMT-0200 (Horário brasileiro de verão)
UTC time: "2018-01-13T14:26:36.238Z"
```

The datepicker sets the time to 0h0m0.000 when you choose a date. So, if you live in a GMT "negative" region, the day will be set to the day before. But it normally has no big side effects, unless you need to record the date as a string in local time format.

**Comment by tapinambur0508** [comment]
How I can set timezone in datepicker, which not depended for user GMT? I know in md-datepicker it like as `ng-model-option="{timezone}"`

**Comment by julianobrasil** [comment]
Since this is not a bug nor a new feature request, close it for now, ask it in stackoverlow and post the link here. I'll try to help you over there.

**Comment by tapinambur0508** [comment]
Ok, thank you

**Comment by rahimnagori** [comment]
You may resolve it like this :
For example, if your are getting date in -> **one_day_back_date_value**

```
var one_day_back_date_value = moment.tz(moment(date_value_from_backend), 0).format("YYYY-MM-DD");
date_value_from_backend = moment(one_day_back_date_value).toDate();
```

**Please note : moment and moment-timezone libraries are must for this.
Include moment library above the moment-timezone library.**
