### ISSUE TITLE
Ability to use Stepper with template forms

### ISSUE THREAD

**Issue by ganqqwerty** [angular/material2#9393]
#### Bug, feature request, or proposal:
Add the ability to describe forms in a Template form way, not only as Reactive Forms. 

#### What is the expected behavior?

Make it possible to use template forms inside the steps. 

#### What is the current behavior?
Currently only Reactive forms can be used, because [stepControl] must point to a form group in order to watch the state of the form 

#### What is the use-case or motivation for changing an existing behavior?
Not everyone uses Reactive Forms, there's a lot of Template forms code out there.

**Comment by crisbeto** [comment]
The `stepControl` is used primarily to figure out the validation state of each step, however it's not required. Alternatively you can bind to the `completed` which lets you control the completion yourself.

**Comment by ganqqwerty** [comment]
is it possible to control each step with `completed`? How do you do this?

**Comment by crisbeto** [comment]
Each step has a `completed` property that is a boolean that can be used to mark whether the user can continue from a step. [You can read more about it in the docs.](https://material.angular.io/cdk/stepper/api#CdkStep)
