### ISSUE TITLE
Pagination not working in IE 10

### ISSUE THREAD

**Issue by haribalajip** [angular/material2#9395]
#### Bug
Table pagination buttons do not work only in IE 10 . 

#### What is the expected behavior
**<** and **>** buttons must work properly .

#### What is the current behavior?
Buttons seem to be disabled .

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
IE10

**Comment by donroyco** [comment]
> Angular Material supports the most recent two versions of all major browsers: Chrome (including Android), Firefox, Safari (including iOS), and *IE11 / Edge*

Material is not actively supported in < IE11.

**Comment by haribalajip** [comment]
@donroyco Do we have any workarounds for this issue ?

**Comment by josephperrott** [comment]
Closing as IE 10 is unsupported.
