### ISSUE TITLE
bug(mat-divider): The divider does not display

### ISSUE THREAD

**Issue by faisalmuhammad** [angular/material2#9399]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The divider should display independent of the the **"mat-list"**

#### What is the current behavior?
The divider does not display in on the page unless I add atleast one **"mat-list"** in the app.

#### What are the steps to reproduce?
- Demo with [**WRONG BEHAVIOR**](https://stackblitz.com/edit/angular-taw4ri?file=app/app.component.html)
- Demo with [**CORRECT BEHAVIOR**](https://stackblitz.com/edit/angular-evqku1?file=app/app.component.html)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

- Angular 5.0.0
- Angular Material 5.0.4

**Comment by julianobrasil** [comment]
Dupe: #9380

**Comment by faisalmuhammad** [comment]
@julianobrasil , please read the issue again. The issue mentioned by you is totally different.

**Comment by julianobrasil** [comment]
@faisalmuhammad, there's a new component, called `mat-divider`, that is independent of `mat-list`. It has been made accidentaly available in 5.0.3 and is not available anymore in 5.0.4. It'll probably be available in 5.1.0 again. That's why I linked the other post.

**Comment by faisalmuhammad** [comment]
Makes sense. Thanks for clearing that (Y)

**Comment by julianobrasil** [comment]
So you can close this one.

**Comment by julianobrasil** [comment]
@faisalmuhammad  `<mat-divider>` is officially available now: https://github.com/angular/material2/blob/master/CHANGELOG.md

**Comment by novaterata** [comment]
mat-divider is still invisible

**Comment by crizzy9** [comment]
Still facing this issue can only see vertical mat-divider inside mat-toolbar. Any fixes available?
