### ISSUE TITLE
Couldn't create OverlayContainer because it is not released in the last version of Core

### ISSUE THREAD

**Issue by hyzhak** [angular/material2#940]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
OverlayContainer should exist

#### What is the current behavior?
There is no OverlayContainer in packages

#### What are the steps to reproduce?

```
npm install --save @angular2-material/core@2.0.0-alpha.6-2 @angular2-material/menu@2.0.0-alpha.6-2
```

Follow instruction here https://github.com/angular/material2/tree/master/src/components/menu#setup
But it doesn't work with current core@2.0.0-alpha.6-2  and menu@2.0.0-alpha.6-2 .

#### Which versions of Angular, Material, OS, browsers are affected?
* `@angular2-material/core@2.0.0-alpha.6-2`
* `@angular2-material/menu@2.0.0-alpha.6-2`

**Comment by cladera** [comment]
Same problem here

**Comment by kara** [comment]
Hey all,  menu is actually slated for an alpha.7 release (it's not yet completed). I'm not sure how it got out there already!  It works with some core code that hasn't been released yet either.  When alpha.7 comes out, it should work as intended.

**Comment by jelbourn** [comment]
It was published on the `@next` label, which contains experimental packages that we published to test offline compiler support.
