### ISSUE TITLE
[Feature request] - Make SCSS Variables available

### ISSUE THREAD

**Issue by BamiGorengo** [angular/material2#9402]
#### Feature request

I think its a good idea to make variables available for Developers.

As Example: [https://github.com/angular/material2/blob/master/src/lib/toolbar/toolbar.scss](url)

There are the Variables for the MatToolbarHeight. It would be very cool, when we can just import a `@import '~@angular/material/variables';` like its already available for the theming.

Maybe universal mixin-set for mediaQueries.

Here is the one that i build for my self: https://github.com/DevMonkeysDE/scss-elements/blob/master/scss/mixins/_media.scss 

with mediaQuery Variables like this: https://github.com/DevMonkeysDE/scss-elements/blob/master/scss/_variables.scss

(Just as Example)

**Comment by jelbourn** [comment]
We unfortunately don't plan on doing anything to make these public, mainly because it would mean that any changes to them would be breaking changes. For the time being we need the freedom to be able to change these without downstream apps depending on them.
