### ISSUE TITLE
Button press effect on basic button persists on mobile or touch only enabled devices

### ISSUE THREAD

**Issue by aslamsayyed** [angular/material2#9405]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Button press effect should be removed after click event is completed. 

#### What is the current behavior?
Button press effect grey background on basic button / mat-button is visible until I click / touch somewhere else.

#### What are the steps to reproduce?
Open https://material.angular.io/components/button/examples on your mobile,
click on basic button you'll see button press or background color is visible until you click somewhere on document.

#### What is the use-case or motivation for changing an existing behavior?
I have mobile app that uses it, it looks weird.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 Bleeding edge.

#### Is there anything else we should know?

**Comment by josephperrott** [comment]
Closing as this is working as expected.  The background is shown as the browsers focus is placed on the button due to the button press.
