### ISSUE TITLE
Testing MatSelect TypeError: Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by JacobBrandt** [angular/material2#9406]
#### Bug, feature request, or proposal:
Angular:  5.1.3
Material:  5.0.4

Testing with mat-select causes the following error
TypeError{longStack: 'TypeError: Cannot read property 'nativeElement' of undefined
    at SafeSubscriber._next
The line number it is talking about is node_modules/@angular/material/esm5/select.es5.js:947

Sure enough when I change this code to wrap the call to nativeElement with an conditional if (this._panel) the error goes away.

This same test works with
Angular: 4.4.6
Material: 2.0.0-beta.7

Not sure why this error only presented itself with 5.0.4.  Looks like the code has always assumed the panel is defined and can get the nativeElement.  Perhaps something has changed with the subscription in onAttached.  My guess is that it's getting called in 5.0.4 when panel has already been destroyed but didn't do this in beta.

**Comment by crisbeto** [comment]
Can you post the test that is throwing the error?

**Comment by JacobBrandt** [comment]
Trying to figure out how to do that.  Not familiar with StackBlitz on how to set it up to work with testing.

However, please note that the test itself is not failing.  Everything about the test passes all expects.  The TypeError occurs after the test is finished (during the destruction phase of the test).  Again the TypeError is pointing to the error in the onAttached subscription routine that assumes this._panel is defined at all times.

**Comment by crisbeto** [comment]
It's fine posting a code snippet with the test.

**Comment by JacobBrandt** [comment]
OK, the component acts like a taxonomy.  You select the parent before its children.  So in the test below it selects Fruit, then Apple, then Red and Yellow all from mat-select components defined in the template.  The children groups are not shown until the parent is selected because we don't know the options for that mat-select until the parent is chosen.  This component allows for group separators to be defined so I'll show that test.  One thing to note is that this component is tested on a dialog since that is how we use it.

```
beforeEach(() => {
  viewContainerFixture = TestBed.createComponent(ComponentWithChildViewContainer);
  viewContainerFixture.detectChanges();
  testViewContainerRef = viewContainerFixture.componentInstance.childViewContainer;
  dialogRef = dialog.open(TaxonomyComponent, { viewContainerRef: testViewContainerRef });
  dialogRef.componentInstance.data = {};
  viewContainerFixture.detectChanges();
  page = new Page(viewContainerFixture, overlayContainerElement);
});

it("should use defined separators", async(() => {
  viewContainerFixture.whenStable().then(() => {
    dialogRef.componentInstance.groupSeparator = "+";
    dialogRef.componentInstance.splitSeparator = "=";
    viewContainerFixture.detectChanges();
    const groupName = page.getGroupName();
    expect(groupName.textContent).toBe("<Food Type>+<Food Name>+<Food Color>");
    page.select(0, [0]);
    page.select(1, [0]);
    page.select(2, [0, 1]);
    expect(groupName.textContent).toBe("Fruit+Apple+Red=Yellow");
  });
}));

class Page {
  groupOptions: Element[];
  fixture: ComponentFixture<ComponentWithChildViewContainer>;
  overlay: HTMLElement;

  constructor(fixture: ComponentFixture<ComponentWithChildViewContainer>, overlay: HTMLElement) {
    this.fixture = fixture;
    this.overlay = overlay;
  }

  getGroupName() {
    return this.overlay.querySelector("#groupName");
  }

  getOptions() {
    return this.overlay.querySelectorAll("mat-option") as NodeListOf<HTMLElement>;
  }

  getTriggers() {
    return this.fixture.debugElement.queryAll(By.css(".mat-select-trigger"));
  }

  getActions() {
    return this.fixture.debugElement.queryAll(By.css("button"));
  }

  select(trigger: number, options: number[]) {
    const triggers = this.getTriggers();
    triggers[trigger].nativeElement.click();
    this.fixture.detectChanges();
    const optionsEl = this.getOptions();
    options.forEach((option) => {
      optionsEl[option].click();
    });
    this.fixture.detectChanges();
  }
}
```

**Comment by crisbeto** [comment]
It's still a bit hard to tell without the full setup. I'm pretty sure that it isn't happening because of the `onAttached` being invoked after the component is destroyed since it's only emitted as a result of the [`open` property changing](https://github.com/angular/material2/blob/master/src/cdk/overlay/overlay-directives.ts#L260) and Angular will stop checking for changes after destroying the instance. We've had some of these silent errors in the select tests in the past where the test passes, but the error still gets logged. They usually happen if we missed a `detectChanges` or a `flush` somewhere.

**Comment by JacobBrandt** [comment]
I think you misunderstood.  I'm not saying onAttached is being invoked I'm saying the subscription inside it is.  That's why I referenced the code
```
TypeError{longStack: 'TypeError: Cannot read property 'nativeElement' of undefined
at SafeSubscriber._next node_modules/@angular/material/esm5/select.es5.js:947:1)
```
Here is the next call in the stack
```
at SafeSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub node_modules/rxjs/_esm5/Subscriber.js:240:1)
```
I trimmed down the test to pin point when it happens.  So basically I removed all expects and kept only my interactions in the select method from the Page class.  In this method I made it do just the code below and no TypeError.
```
const triggers = this.getTriggers();
triggers[trigger].nativeElement.click();
this.fixture.detectChanges();
```
So opening the select does not trigger the TypeError.   Then I added the selection of one of the options and the TypeError occurs.
```
options.forEach((option) => {
  optionsEl[option].click();
});
this.fixture.detectChanges();
```
I don't see any missing detectChanges or flush anywhere but I could add more if you think it would help.  I'll try and get a reproducible gist later today for you to pull down.  Thanks for taking the time to look into this.

**Comment by crisbeto** [comment]
Alright, I see what you mean. It's still because you're missing a `flush` (note that you need to be in the `fakeAsync` zone to be able to use `flush`). I reproduced it with this test:

```ts
it('should fail', fakeAsync(() => {
  const fixture = TestBed.createComponent(SimpleSelect);
  fixture.detectChanges();

  fixture.componentInstance.select.open();
  fixture.detectChanges();

  fixture.componentInstance.select.close();
  fixture.detectChanges();
  flush();
}));
```

That being said, I've submitted a fix since we should be handling it better in the overlay.
