### ISSUE TITLE
Menu: Elevation is 2dp instead of 8dp

### ISSUE THREAD

**Issue by henev** [angular/material2#9409]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Elevation of the Menu component should be 8dp as per the [official material design documentation for elevation and shadows](https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-shadows). Sub menus have elevation of 9dp (+1 dp for each sub menu)

>**Menus and sub menus**
>Menus: 8dp
>Sub menus: 9dp (+1 dp for each sub menu)

#### What is the current behavior?
Menu has 2dp elevation and sub menus have 3+dp.

#### What are the steps to reproduce?
1. Open project documentation
1. Go to Component -> Menu
1. Open first menu example
1. Inspect element and check classes on .mat-menu-panel

#### What is the use-case or motivation for changing an existing behavior?
If this library is following Google Material Design it should reflect it correctly in every aspect **or at least provide option to change elevation**.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
* Angular 5.1.0
* Material 5.0.2

**Comment by CDDelta** [comment]
> The menu elevation was set from 8 to 2 in #5361. It is based on the mockups from https://material.io/guidelines/components/menus.html. - At crisbeto 

> According to https://material.io/guidelines/material-design/elevation-shadows.html, the elevation for menus should be 8. - me

> While that's true, the designs don't back it up and I based it off of MDC which also use the lower elevation. See https://material-components-web.appspot.com/simple-menu.html - At crisbeto 

Seems like it is just a problem with the elevation specs.

**Comment by crisbeto** [comment]
Closing as it's working as expected.
