### ISSUE TITLE
Why not use <md-button></md-button>?

### ISSUE THREAD

**Issue by ibufu** [angular/material2#942]
```html
<button md-button></button>
```
It looks a little redundant.

**Comment by msegers** [comment]
You can use md-button on an anchor (e.g.) <a md-button></a> That is a nice feature I guess.

That being said, I do like to know what the specific reason is.

**Comment by ibufu** [comment]
@msegers 
I think the reason may relate to that component can not replace itself with its content at Angular2.

**Comment by msegers** [comment]
Jup I believe I saw that as reason, but makes me wonder why that would be a
problem still.

**Comment by ibufu** [comment]
I found the reason at [design documents](https://docs.google.com/document/d/1m8IxhKu5qI8xwjePVGZMbRve3MTW9M8odgcPiuAZfoM/preview?pref=2&pli=1#).
