### ISSUE TITLE
mat-action-list

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#9429]
Capturing the remaining work from #107 

We currently have `mat-list`, `mat-nav-list`, and `mat-selection-list`, but are still missing `mat-action-list`. In this variant, each list item would be a button, e.g.
```html
<mat-action-list>
  <button mat-list-item> ... </button>
  ...
</mat-action-list>
```

**Comment by salemdar** [comment]
Is anybody working on this at the moment?

**Comment by weylert** [comment]
yeah, wondering that right now. Still waiting

**Comment by mitchellwills** [comment]
It looks like some work was done in #12415 however, it's definitely not complete yet.
A couple things I noticed:
 * No visual focus indicator
 * When using matLine text is centered instead of left aligned

http://next.plnkr.co/edit/6bAMNQybkimbP0Tw2maT?p=preview&preview

**Comment by tayambamwanza** [comment]
It seems that the click event is only fired when clicking on the item text and not on the entire item i.e even the whitespace

**Comment by adrogon** [comment]
So um, this component is [documented](https://material.angular.io/components/list/overview#action-lists) but not ready?

**Comment by weylert** [comment]
Yeah, looks like. So sad, because I still want to use this..

Em ter, 29 de jan de 2019 às 14:54, Anthony Drogon <notifications@github.com>
escreveu:

**Comment by jelbourn** [comment]
This was released in v7.

**Comment by qijimrc** [comment]
I am using @angular-devkit/core v8.1.0, how can I make this component work?
