### ISSUE TITLE
Slider thumb values getting too big!

### ISSUE THREAD

**Issue by stevedeighton** [angular/material2#9431]
#### Bug, feature request, or proposal:

Feature Request

#### What is the expected behavior?

When a value reaches capacity, it smartly breaks down to take up less space. 

E.g.

A value of 100,000 would display as 100k. Some rounding would have to take place, obviously. Also addition of commas would be nice.

#### What is the current behavior?

It just displays 100000 and overflows the thumb

#### What are the steps to reproduce?

Put a large max value on the slider component, drag it all the way up!

#### What is the use-case or motivation for changing an existing behavior?

Currently the slider (with thumb) cannot be used for large numbers. Not having enough room seems like a dumb reason for not using the thumb. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

2.0.0-beta.12 (not used any others)

#### Is there anything else we should know?

I apologise if this is a duplicate, or if indeed I am using the slider out of its intended purpose.

**Comment by crisbeto** [comment]
I don't think we should be too opinionated in Material about how the number is formatted, because it can depend on the context and the locale. I've submitted #10243 that will add the ability to specify your own formatting function.
