### ISSUE TITLE
[material stepper] the "completed" property allows us to navigate through each step even if its value is set to false

### ISSUE THREAD

**Issue by cherifa-ghersi** [angular/material2#9435]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Disable the ability to navigate throught steps when the "completed" property is set to false

#### What is the current behavior?
the "completed" property allows us to navigate through each step even if its value is set to false

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material@5.1.3

**Comment by crisbeto** [comment]
There's a fix in Material 5.0.4 that should handle this case.
