### ISSUE TITLE
nested menu opens other ways

### ISSUE THREAD

**Issue by Douglasfeuser** [angular/material2#9436]
#### Bug, feature request, or proposal:

I have this following component:
https://material.angular.io/components/menu/overview#nested-menu

But when I put it on the top right of the page it always opens the more to the right, thus breaking the site.

#### What is the expected behavior?

Open to the right insted, or down, but not getting over the actual wid of the page.

#### What is the current behavior?

break my pages, gets a scroll with space on the right.

#### What are the steps to reproduce?

Just puting a nested menu on the right side of the page.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 Versions on package:

"@angular/core": "4.3.3",
"@angular/flex-layout": "2.0.0-beta.9",
"@angular/material": "2.0.0-beta.10",
"@angular/animations": "4.3.3",
"@angular/cli": "1.2.7",
"@angular/compiler-cli": "4.3.3",

**Comment by crisbeto** [comment]
[It seems to work correctly for me](https://angular-xvzvfy.stackblitz.io). Can you post an example?
