### ISSUE TITLE
disableClose in matdialog is working for esc but not works when click outside the popup

### ISSUE THREAD

**Issue by shrivastavashubham** [angular/material2#9437]
#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by willshowell** [comment]
Please update your post to use the issue template or the team will close it
