### ISSUE TITLE
@angular2-material/checkbox npm package is outdated

### ISSUE THREAD

**Issue by vagonpidarasov** [angular/material2#944]
Seems like @angular2-material/checkbox npm package is outdated.
[package.json](https://github.com/angular/material2/blob/master/src/components/checkbox/package.json) was updated 13 days ago but npm registry refers to outdated version.

#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
The latest version of @angular2-material/checkbox npm package is 2.0.0-alpha.6-2
@angular/forms peerDependencies version is "^0.2.0"

#### What is the current behavior?
The latest version of @angular2-material/checkbox npm package is 2.0.0-alpha.6
@angular/forms peerDependencies version is "^0.1.0"

#### What are the steps to reproduce?
run following command: 
```npm install @angular2-material/checkbox@2.0.0-alpha.6-2 && npm outdated```
check peerDependencies section of @angular2-material/checkbox/package.json

**Comment by jelbourn** [comment]
This is intentional. The `-1` and `-2` releases are experimental. alpha.7 will be published soon with updated dependencies.
