### ISSUE TITLE
size of draggable div with mat-checkbox not calculated correctly 

### ISSUE THREAD

**Issue by michaelb-01** [angular/material2#9447]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
When a mat-checkbox is within a div set to draggable the bounds of the div should be calculated correctly when dragging

#### What is the current behavior?
The mat-checkbox causes the 'dragged' element to be offset (it seems to be ok in Safari)

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

http://embed.plnkr.co/g2qF92/

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^5.0.0",
"@angular/material": "^5.0.0-rc.2"

chrome

**Comment by DevVersion** [comment]
Seems to be related to the inner ripple container of the checkbox. The ripple container uses an absolute position and exceeds the "actual" element boundaries.

As a workaround you can use CSS to hide the container

```css
    ::ng-deep .mat-checkbox-ripple {
      display: none;
    }
```

**Comment by michaelb-01** [comment]
Thats what I ended up doing but it would be nice to have a solution where the ripple could still be maintained..
