### ISSUE TITLE
Missing @Input in the docs for MatTabGroup's API

### ISSUE THREAD

**Issue by francium** [angular/material2#9452]
#### What is the expected behavior?
Expect the `MatTabGroup` api to have `@Input()` before `selectedIndex` 

#### What is the current behavior?
There is no `@Input()`

It has it as,

    selectedIndex: number | null

where as it should be

    @Input()
    selectedIndex: number | null

#### What are the steps to reproduce?
See [MatTabGroup api table](https://material.angular.io/components/tabs/api#MatTabGroup)

#### What is the use-case or motivation for changing an existing behavior?
The documents should explicitly state that `selectedIndex` is an input

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.1.0

**Comment by josephperrott** [comment]
@DevVersion It looks like `@Input` decorators aren't showing up in the docs when  they are decorating getters and setters.

**Comment by DevVersion** [comment]
This is an issue with the Dgeni typescript package. Will be fixed with: https://github.com/angular/dgeni-packages/pull/256
