### ISSUE TITLE
Datepicker calendar popup not animating

### ISSUE THREAD

**Issue by CDDelta** [angular/material2#9453]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Datepicker calendar popup should animate.

#### What is the current behavior?
Datepicker calendar popup does not animate.

#### What are the steps to reproduce?
See https://material.angular.io/components/datepicker/overview.

#### What is the use-case or motivation for changing an existing behavior?
It should animate according to new release notes

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: 5.1.0

#### Is there anything else we should know?
I have already cleared cache multiple times.

**Comment by crisbeto** [comment]
That change was reverted in order to avoid breaking changes. I'll remove it from the changelog.
