### ISSUE TITLE
Sidenav issue with latest material version

### ISSUE THREAD

**Issue by himanshumps** [angular/material2#9456]
#### Bug, feature request, or proposal:
Bug
#### What is the expected behavior?
The examples should be working for sidenav
#### What is the current behavior?
The examples for the sidenav are not working with the provided code as well as on stackblitz (https://material.angular.io/components/sidenav/overview)

#### What are the steps to reproduce?
Click on any of the examples link
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material (5.1.0)

#### Is there anything else we should know?
No

**Comment by julianobrasil** [comment]
It worked fine over here (I tested two of them randomly):

![image](https://media.giphy.com/media/3o7522JSkj5eBs4zD2/giphy.gif)

**Comment by josephperrott** [comment]
Closing as it appears to be working as expected now.
