### ISSUE TITLE
feat(MatDatepicker): observable that emits the seleced year in year mode

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#9458]
#### Bug, feature request, or proposal:

feature

#### What is the expected behavior?

When you click on year label, the calendar switches to multi-year mode. After that, when you select an year, there could be an observable or `@Output` property  that emits the year (a number) chosen _before_ switching to the year view.

Following this path, it would be nice if there was another observable that emits the month  (a number) when the month is selected (in the year view), also _before_ switching to the month view.

#### What is the current behavior?

There are no such observables nor `@Output` properties.

#### What is the use-case or motivation for changing an existing behavior?

Sometimes you want to choose just an year or a month. I think some day there will be this possibility, but for now, such a feature could help a lot, as the developer could just get the year selected and close the calendar programmatically.

#### Is there anything else we should know?

It's related to #4853, but it seems to be a quickier solution that does no harm in the long term.

@mmalerba

**Comment by mmalerba** [comment]
I'd be fine with this change, seems like a reasonable way to let people work around current limitations

**Comment by julianobrasil** [comment]
Ok. I'll give it a shot.

**Comment by julianobrasil** [comment]
What's better: `@Output`s (something like `yearChange` and `monthChange` in the `MatDatepickerInput`) or `observables` in `MatDatepicker`? 

IMO, as its not a definite solution, I think it could be just `observables` in `MatDatepicker`, like  `panelClosingActions` in `MatAutocomplete .
