### ISSUE TITLE
Getting MatPrefixRejector issue

### ISSUE THREAD

**Issue by keymaker19** [angular/material2#9459]
**Bug, feature request, or proposal:**
Property 'MatPrefixRejector' does not exist on type 'typeof "/node_modules/@angular/material/core"' 

**What is the current behavior?**
Throws Error

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**
 "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@angular/upgrade": "^5.0.0",
    "@angular/animations": "^5.0.0",
    "angular-in-memory-web-api": "0.3.1",
     "rxjs": "5.5.3",
    "@angular/material": "^5.0.0",
    "@angular/cdk": "^5.0.0",

**Comment by donroyco** [comment]
Please use [the issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md) to address your issue.

**Comment by josephperrott** [comment]
Closing as `MatPrefixRejector` was removed beginning in [`5.0.0-rc0`](https://github.com/angular/material2/blob/master/CHANGELOG.md#500-rc0-cesium-cephalopod-2017-11-06)

**Comment by keymaker19** [comment]
Can you provide more info?. Because I'm getting that error

2018-01-18 12:14 GMT-05:00 Joey Perrott <notifications@github.com>:

**Comment by julianobrasil** [comment]
@keymaker19, remove `node_modules` _and_ `package-lock.json` before `npm install` it.
