### ISSUE TITLE
Font size doesnt override from custom typography

### ISSUE THREAD

**Issue by tofesath** [angular/material2#9462]
#### Bug, feature request, or proposal:
override font size on the input element doesn´t work

#### What is the expected behavior?
I defined custom typography on the input element, where I want override this attributes:
font-size: 40px
line-height: 52px
font-weight: 400

#### What is the current behavior?
font size is not reflected on the input element

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-g1z2md

#### What is the use-case or motivation for changing an existing behavior?
I want override font size on the input element and in browser IE 11 writing text can't be floating

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on Angular 5.0, Angular/Material 5.0.0-rc.2, all browsers and in IE with other line-height how is default 1.125 writing text is floating

**Comment by crisbeto** [comment]
I've submitted a fix @tofesath. Until it gets in you should be able to set the font size by specifying it on one of the form field's ancestors.
