### ISSUE TITLE
tab enable and disable

### ISSUE THREAD

**Issue by arunrote** [angular/material2#9464]
I want disable all tabs except the page1 and once data is saved on page1 want to enable page2 and page3 tabs. I am passing the flag from child component to parent component. Value is passed correctly, but not enabling the page2 and page3 tab. It's enabled once i minimize the browser or click on the page1 tab. Please help me to resolve this problem and here is my code.

<md-tab-group (selectChange)="onTabChange($event)">
        <md-tab label="Page1" >
                <page1 (shareDataToParent) = "shareDataToParent($event)"></page1>
        </md-tab>
        <md-tab label="Page2"   [disabled]="flag">
                <page2></page2>
        </md-tab>
        <md-tab label="Page3" [disabled]="flag">
                <page3></page3>
        </md-tab>
    </md-tab-group>

below code is written in base component.
private onTabChange($event: any) {
        if (this.count==0)) 
            this.flag = true;
        else 
            this.flag = false;
    }
 private shareDataToParent(blnFlag: boolean) {
        this.flag = blnFlag;
    }

child component code

 @Output() shareDataToParent = new EventEmitter(); //creating an output event
this.shareDataToParent.emit(this.getSearchStatus);

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
