### ISSUE TITLE
build fails if cdk components have scss

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#9469]
Issue can be repro'd by adding scss to an existing cdk component, e.g.: https://github.com/angular/material2/compare/master...mmalerba:cdk-scss-issue-repro?expand=1

I get the following error when running `gulp serve:devapp`:
```
: Couldn't resolve resource step.css relative to /usr/local/google/home/mmalerba/material2/src/cdk/stepper/stepper.ts


Failed to compile  using /usr/local/google/home/mmalerba/material2/src/cdk/tsconfig-tests.json
```

Failing task appears to be: `cdk:build:esm:tests`

**Comment by josephperrott** [comment]
fixed by #9470
