### ISSUE TITLE
mat-menu and button in different companents

### ISSUE THREAD

**Issue by tatol** [angular/material2#9474]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
if i have mat-menu and button with [matMenuTriggerFor] in different companents, can i do something to make the button see the menu?

#### What is the current behavior?
now I have a error
`ERROR Error: mat-menu-trigger: must pass in an mat-menu instance.`

#### What are the steps to reproduce?
`<mat-menu #saveMenu="matMenu">...</mat-menu>`
 in app-save-document companent and
 `<app-save-document></app-save-document>
 <button mat-icon-button [matMenuTriggerFor]="saveMenu">`
in another companent.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular cli v5

**Comment by tatol** [comment]
@Chan4077 this is more a question. I did not find out if it was possible at all and decided to ask here

**Comment by julianobrasil** [comment]
@tatol, post your question in stackoverflow and put the link to it over here and I'll try to help you there.

And, of course, close this issue as it is a doubt (not a bug, proposal or a feature request),

**Comment by tatol** [comment]
[stackoverflow link](https://stackoverflow.com/questions/48343082/mat-menu-and-button-in-different-companents)

**Comment by julianobrasil** [comment]
@tatol, I've answered over there.
