### ISSUE TITLE
Example source code for tabs showing outdated information

### ISSUE THREAD

**Issue by gajdot** [angular/material2#9475]
#### Bug, feature request, or proposal:

bug
#### What is the expected behavior?

The code sample in the documentation to work
#### What is the current behavior?

The code sample in the documentation shows the old selector for tab
#### What are the steps to reproduce?

Visit https://material.angular.io/components/tabs/overview
On the Basic tabs example if you click show source you can see the old selector is being used

#### What is the use-case or motivation for changing an existing behavior?

When I copied the example to my site it wasn't working, I tough it's probably because I'm using an old version of material, so I did an upgrade and still wasn't working. Fortunately after that I realized what's the problem.

**Comment by Chan4077** [comment]
@gajdot See https://github.com/angular/material2/issues/7715#issuecomment-335835631

**Comment by gajdot** [comment]
LoL. This worked, but it's still really bad user experience... Anyway this issue then can be closed, but I would still prefer a solution to version the samples so this wouldn't happen again.

**Comment by josephperrott** [comment]
Closing as clearing out stale service worker is able to get everything working again.
