### ISSUE TITLE
MatDatePicker/Input ==> Strict date format validation

### ISSUE THREAD

**Issue by stephanecot** [angular/material2#9476]
#### Bug, feature request, or proposal:
I am using Angular Material 5.1 and I am using the **MatMomentDateModule**.
Actually, when my form is shown, I have an input datepicker with a date (today by default). 
I have for value:
**19/01/2018** (I am french )

A user can change this value, with the graphic datepicker or by typing the new value he want.

Here's my issue:

When the user want to change the input, he uses the backslash input to delete the last input, and he gets:
**19/01/201**.
The problem is, it's not considered by my form as a not valid date and, when I display the value moment used, I have: **19/01/0201** !
If the user delete another caracter, he has: **19/01/20** and moment interpret this like: **19/01/2000** !

I have a reactiveForm with a valueChange() event on these dates, and it gets wrong due to that.
The only way I found to counter that, it's to test the **myMomentDate.creationData().input** value (valid date === 10 caracters)

Is it possible to have a property to test that the moment date pattern defined is exacly the same as in the input? Maybe it's due to momentjs ...

My format is configured like this:

`export const FORMATS = {`
`parse: {`
`      dateInput: 'L',`
`    },`
`    display: {`
 `       dateInput: 'L',`
`...}`

and in the momentjs doc:
Month numeral, day of month, year **L** => **09/04/1986** (not 09/04/86 !)

**Comment by julianobrasil** [comment]
Currently the parse function of the `MomentDateAdapter` class is:

```ts
parse(value: any, parseFormat: string | string[]): Moment | null {
    if (value && typeof value == 'string') {
      return moment(value, parseFormat, this.locale);
    }
    return value ? moment(value).locale(this.locale) : null;
}
```

Try to extend it and override the parser function so that when you get the value to parse, you verify if the format is correct. If something goes wrong (invalid date) return a null value.

**Comment by stephanecot** [comment]
Ok it's good to know for my case (in global).
But maybe it will be good to as this functionality by default in angular material datepicker. Momentjs is maybe to permissive

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Comment by arlowhite** [comment]
I wanted to report this issue as well.
Like the original author said, by default, if a user erases the day in order to change it, a string like `'9//2017'` evaluates as valid and has a odd Date value. If you're watching the control valueChanges, this is unexpected.
However, 5.1.0 just came out, so I need to test if the new version behaves differently before reporting a bug.

**Comment by hanyu-natsu** [comment]
dup of #9619

Create a custom adapter and override parse function with strict parse mode.
