### ISSUE TITLE
MatMenu generating error on click

### ISSUE THREAD

**Issue by ericcancil** [angular/material2#9482]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?
Menu to open

#### What is the current behavior?
Error generated

I have the following markup for a matMenu
```
<div fxFill fxLayout="row-reverse">
      <button mat-icon-button [matMenuTriggerFor]="menu">
        <mat-icon>more_vert</mat-icon>
      </button>
      <mat-menu #menu="matMenu">
        <button *ngFor="let chat of userModel.chats" mat-menu-item>
          <div mat-card-avatar class="small-user-image mat-elevation-z5"
               [style.background-image]="'url(' + getThemFromChat(chat)?.mainPhoto + ')'"></div>
          <span>{{getThemFromChat(chat).username}}</span>
        </button>
      </mat-menu>
    </div>
```

Upon clicking the menu this happens.  Kind of at a loss here.

![image](https://user-images.githubusercontent.com/26233337/35163180-dfc8054e-fd13-11e7-953a-cdc0a2799544.png)

**Comment by josephperrott** [comment]
Can you provide a reproduction of the issue?

Using the template you provided it appears to work as seen [here](https://stackblitz.com/edit/angular-material2-issue-pbf87z?file=app%2Fapp.component.html)

**Comment by josephperrott** [comment]
Closing as no reproduction has been provided.
