### ISSUE TITLE
(docs) Progress Bar overview sample is missing

### ISSUE THREAD

**Issue by kbo4sho** [angular/material2#9483]
#### Bug
Progress Bar overview sample is missing.

#### What is the expected behavior?
Progress Bar overview page should show a sample or not display anything.

#### What is the current behavior?
Progress Bar overview page shows no example and throws an error in the console.

#### What are the steps to reproduce?
Visit this page.
https://material.angular.io/components/progress-bar/overview

Check the console.
See that there is not a working example.

#### What is the use-case or motivation for changing an existing behavior?
An example should be present so users have something to learn from.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
This is on the live docs site. Current Version: 5.1.0

#### Is there anything else we should know?
I can create PR to fix the issue if this isn't already being worked on.

**Comment by josephperrott** [comment]
Unfortunately do to an issue with our service worker, you have to clear the cache manually.

<sup>The following instructions assume you're running Chrome.</sup>
Either:
1. Open Chrome DevTools on <https://material.angular.io>
2. Hold the reload button. There should be the following options: `Reload`, `Hard Reload` and Empty Cache and Hard Reload. Click on the `Hard Reload` menu item.

Or:
1. Open Chrome DevTools on <https://material.angular.io>
2. Go to the `Network` tab.
3. Check the `Disable cache` option and then refresh (<kbd>Ctrl</kbd> + <kbd>R</kbd> / <kbd>Command</kbd> + <kbd>R</kbd>).
![Chrome DevTools Network tab > Disable cache](https://user-images.githubusercontent.com/20047125/31448235-887c8cb4-aed6-11e7-86b7-27978a0c217e.png)

**Comment by kbo4sho** [comment]
there it is, thanks!
