### ISSUE TITLE
Put sorting arrow before header tittle, not after

### ISSUE THREAD

**Issue by uncledent** [angular/material2#9486]
#### Bug, feature request, or proposal:

Put sorting arrow icon before header tittle, not after
See styleguide: https://material.io/guidelines/components/data-tables.html#data-tables-structure

#### What is the expected behavior?

Sorting arrow should be before header tittle, not after
See styleguide: https://material.io/guidelines/components/data-tables.html#data-tables-structure

#### What is the current behavior?

It is after the title, so it gets hidden.

#### What are the steps to reproduce?

Just look at examples here: https://material.angular.io/components/sort/overview 

#### What is the use-case or motivation for changing an existing behavior?

Styleguide: https://material.io/guidelines/components/data-tables.html#data-tables-structure

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material: 5.1.0
Typescript: 2.6.2
Angular: 5.2.1

#### Is there anything else we should know?

No

**Comment by andrewseguin** [comment]
You're in luck. You can use the `mat-sort-header`'s `arrowPosition` input. Simply set it to `'before'` and your arrow will show to the left.

**Comment by Philip-Sultanescu** [comment]
The 'before' should be then the default value, here's why:

- It's in the guidelines, they must be followed to the last pixel if possible
- It's the fist parameter in 'before' and 'after', normally 'after' should be default in rtl modes.
- When column is small the header text will push the icon out of sight, in this case the guidelines recommend adding a tooltip on the text, but the icon still is invisible
<img width="384" alt="screen shot 2018-01-30 at 10 41 35" src="https://user-images.githubusercontent.com/30979663/35559144-3c81a062-05aa-11e8-9575-b572bfffc93e.png">

**Comment by andrewseguin** [comment]
Here's my counter argument:

- The guidelines only show the sorted case where cell values are right-aligned and it makes sense that the arrow fills in the void to the left of the header. By default, table cell values are left-aligned and so by default the arrow should appear after the header to fill the void just like in the guidelines.
- We do not define types in an order that should infer defaults or usage. The verbiage of `before` and `after` is used to avoid worrying about the difference between LTR/RTL.
- Sort headers do not require that the content is simply text and so it cannot assume that the content should not wrap nor can it infer any specific tooltip message.
