### ISSUE TITLE
Circular type references in material2

### ISSUE THREAD

**Issue by mprobst** [angular/material2#9491]
`src/cdk/overlay/position/position-strategy.ts` imports `OverlayRef` from `src/cdk/overlay/overlay-ref.ts`. That in turn imports `src/cdk/overlay/overlay-config.ts`, which in turn imports `PositionStrategy`, which in turn makes some of our tooling sad.

**Comment by mprobst** [comment]
@jelbourn can we merge https://github.com/crisbeto/material2/commit/41b77d75e61a1e99064823ebd661ee378e954c76 to fix this? This is still blocking us in g4.

**Comment by jelbourn** [comment]
I'll try to take a look soon; the last time I tried to sync the fix it had a bunch of failing presubmits

**Comment by mprobst** [comment]
Thanks Jeremy!
