### ISSUE TITLE
MatDialogConfig.id does not work?

### ISSUE THREAD

**Issue by goldenbull** [angular/material2#9496]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
As the doc: 
`id: string | ID for the dialog. If omitted, a unique one will be generated.`

#### What is the current behavior?
the generated dialog has no ID attribute:
`<mat-dialog-container class="mat-dialog-container ng-tns-c1-0 ng-trigger ng-trigger-slideDialog ng-star-inserted" tabindex="-1" role="dialog" style="transform: none; opacity: 1;">...</mat-dialog-container>`

#### What are the steps to reproduce?
```
    const dialogRef = this.dialog.open(PopupFormComponent, {
      id: 'dlg000',
      height: 200,
      width: 300
    });
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.0, Material 5.1.0

**Comment by crisbeto** [comment]
The main purpose of the id was to be able to get a hold of an arbitrary `MatDialogRef`. That being said, as a side-effect of https://github.com/angular/material2/pull/9379 it'll be added to the dialog container.

**Comment by goldenbull** [comment]
I'm newbie of the web world, sorry for bothering you with my simple questions.
If the `id` field will not exist in the generated HTML, what's the proper way to customize the `<mat-dialog-container>` element style? For example, to set the padding=0px instead of the default CSS setting.

**Comment by crisbeto** [comment]
You can pass in the `panelClass` option and use that class to target your dialog.
