### ISSUE TITLE
Stepper: misplaced icon on optional step in IE11

### ISSUE THREAD

**Issue by ciesielskico** [angular/material2#9501]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Display the "Optional label" and the step icon correctly

#### What is the current behavior?
Optional label is not visible, step icon is misplaced

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 1.6.5
Node: 7.10.1
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.5
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.4.2
webpack: 3.10.0
```

#### Is there anything else we should know?

In this example, step 3 is optional. It displays correctly in Chrome and Edge, but not in IE11.

![image](https://user-images.githubusercontent.com/17651898/35187135-678de776-fe1f-11e7-9cf9-720d16301595.png)

**Comment by crisbeto** [comment]
I didn't manage quite to reproduce it locally, but I got something similar if I add `box-sizing: border-box` to everything. Do you happen to have this somewhere in your CSS?

```css
*, *:after, *:before {
  box-sizing: border-box;
}
```

**Comment by crisbeto** [comment]
Thanks, good to know. Let's keep the issue open since this is a common enough use case that we should handle it.

**Comment by ciesielskico** [comment]
Actually, after having a closer look the optional header is still a bit off.

![image](https://user-images.githubusercontent.com/17651898/35193441-a3cda626-fea2-11e7-9b6f-fc0bebea4e1c.png)

Adding `box-sizing: content-box;` to either `.mat-step` or `.mat-step-header` produces a better result, however it's still not 100% correct.
