### ISSUE TITLE
MdDialog

### ISSUE THREAD

**Issue by Namkem** [angular/material2#9510]
#### What are the steps to reproduce?
Only happens in 1 specific situation which can't be reproduced.

**Comment by Namkem** [comment]
Hello Guys,

Any help or advice would be highly appreciated.

**Comment by Namkem** [comment]
@jelbourn Hello Sir,

Why was this thread closed?

**Comment by jelbourn** [comment]
This issue has literally zero information in it.

**Comment by Namkem** [comment]
If I'll post the code of the service that opens the dialog will it make it easier to resolve?

**Comment by jelbourn** [comment]
You can file a new issue that fills out all of the information in the issue template.

**Comment by Namkem** [comment]
Thank You Very Much.
