### ISSUE TITLE
Disabled mat-slide-toggle propagates DOM events

### ISSUE THREAD

**Issue by klemenoslaj** [angular/material2#9512]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When `mat-slide-toggle` is disabled, click even listener should not be triggered.

#### What is the current behavior?
Even though `mat-slide-toggle` is disabled, click event listener is triggered, causing some unexpected results.

#### What are the steps to reproduce?
- go to https://stackblitz.com/edit/angular-zc84gi
- click on disabled `mat-slide-toggle`
- because event listener is toggling `checked` state, state is changing even though it is disabled

#### What is the use-case or motivation for changing an existing behavior?
In my opinion it is just wrong/unexpected behaviour, which is forcing me to place guards for `disabled` state in `click` event listener of `mat-slide-toggle` component.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Testing on latest cli, including libraries it installs.

**Comment by josephperrott** [comment]
Closing as this is not something that can be controlled by Material

You are listening to the click event on an element which unfortunately can't be prevented by another event handler.
