### ISSUE TITLE
Make select and other form fields play nice when inside a toolbar

### ISSUE THREAD

**Issue by alvipeo** [angular/material2#9513]
I just tried to put a select and input into toolbar and result is a mess. I just needed a search field and some type selector, so I made this:

```
<mat-toolbar color="primary">
  <mat-toolbar-row>
    <span>Search</span>
    <mat-form-field>
      <mat-select placeholder="Select">
        <mat-option value="option">Option</mat-option>
      </mat-select>
    </mat-form-field>
    <mat-form-field>
      <input matInput placeholder="Input">
    </mat-form-field>
  </mat-toolbar-row>
</mat-toolbar>
```
The result is meh...

**Comment by CDDelta** [comment]
Please use the issue template when creating new issues, also please provide a StackBlitz example to showcase the problem.

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Comment by tomwanzek** [comment]
@alvipeo FYI: #4886 partially has the same ask, except your issue's intent was broadened to include other `mat-form-field` use cases than just `mat-select`.
