### ISSUE TITLE
mat-icon has display issues when inlining multiple copies of the same SVG with defs with IDs

### ISSUE THREAD

**Issue by damoncasale** [angular/material2#9515]
#### Bug, feature request, or proposal:
Proposal:  Extend the cloneSvg function in src/lib/icon/icon-registry.ts to accommodate munging IDs in defs so that multiple copies of the same inlined SVG won't have conflicting IDs.

#### What is the expected behavior?
When two copies of an SVG with a linearGradient def are inlined, both copies of the SVG should display the linear gradient.

#### What is the current behavior?
Only the first copy of the SVG displays the linear gradient.  All other copies do not.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template (missing version info). Please file a new issue that follows the template, which gives the team the information needed to investigate.
