### ISSUE TITLE
<mat-nav-list> bug when encapsulation is on Native

### ISSUE THREAD

**Issue by BamiGorengo** [angular/material2#9518]
Im not 100% sure that this is a bug, but when i set encapsulation to Native, the ripple effect didnt work any more. Please check this stackblitz: https://stackblitz.com/edit/nav-list-bug encapsulation

Click on the item and you will see that the ripple is anywhere outside for a short time. you will see a scrollbar for a moment when you click. (I fixed this in early time with a position relative, but this dont work in this case any more)

Go to file hello.component.ts and remove line 7 and you will see that then the ripple effect work again well. If this is no bug, sorry for opening this issue. then just close it :)

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
