### ISSUE TITLE
Material needs to support Secondary color

### ISSUE THREAD

**Issue by HeavenlyHost** [angular/material2#952]
#### Bug, feature request, or proposal:
According to Google material design spec there is room for a secondary color, in addition to primary, warning and accent... Is it possible for this to be implemented across all components

[Material Design Spec](https://material.google.com/style/color.html#color-color-schemes)

#### What is the expected behavior?
new secondary color to be made available across all components

#### What is the current behavior?
Only have primary, warn, accent colors... need secondary

#### What are the steps to reproduce?
n/a

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
n/a

#### What is the use-case or motivation for changing an existing behavior?
Project specific requirement, however it would line up with Google material design spec

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2, all browsers

#### Is there anything else we should know?
No

**Comment by jelbourn** [comment]
See #123

**Comment by aldo-roman** [comment]
Hi @jelbourn 

I see no related comment about Secondary color support on #123. Are there any news or a way to add an additional color support?

MD in fact specifies primary, secondary, accent as separated colors.

Thanks!
