### ISSUE TITLE
md-table not reflecting dataSource changes

### ISSUE THREAD

**Issue by dlarr** [angular/material2#9522]
#### Bug, feature request, or proposal:
> Bug

#### What is the expected behavior?
When I call new DataSource(data), I expect the table to display the actual data.

Is there any known case where md-table won't refresh upon call of new DataSource(data) ??

#### What is the current behavior?
Table is empty, eventhough, dataSource shows data.

#### What are the steps to reproduce?
That plunker doesn't work, I just gave the files so you can get the idea 
http://plnkr.co/edit/cNYZCchXi602S22iECdj?p=preview

I have versions issues :(

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
* OS => Windows 10
* Browser FireFox 57.0.4 (64 bits)
* Infos from packeage.json
```
"dependencies": {
    "@angular/animations": "4.3.4",
    "@angular/cdk": "2.0.0-beta.10",
    "@angular/common": "4.3.4",
    "@angular/core": "4.3.4",
    "@angular/forms": "4.3.4",
    "@angular/http": "4.3.4",
    "@angular/material": "2.0.0-beta.10",
    "@angular/platform-browser": "4.3.4",
    "rxjs": "^5.5.5"
  },
  "devDependencies": {
    "@angular/compiler-cli": "1.4.5",
    "@types/jasmine": "2.5.53",
    "del": "^3.0.0",
    "node-sass": "^4.7.2",
    "typescript": "2.3.4"
  }
```

#### Is there anything else we should know?
1- The problem occurs only for service calback returned data. 
2- The [(ngModel)] part of the component seems to work : writeValue is called so new dataSource is created with proper data.

**Comment by andrewseguin** [comment]
Sorry but things seem technically correct in your example. It's hard to actually diagnose without a real example or reproduction of your issue. 

Rather than using your own custom implementation of a data source, try using the library's provided `MatTableDataSource` and setting its data. You should only need to create the data source once and every time you change the data array, the table will refresh.

**Comment by dlarr** [comment]
Thank you so much for your tip, I'll try it right away and give feed back.

**Comment by andrewseguin** [comment]
The `MatTableDataSource` was added in 5.0 _however_ if you want to just copy/paste the file into your library, it should work just fine.

Here's the class to copy: https://github.com/angular/material2/blob/master/src/lib/table/table-data-source.ts

**Comment by dlarr** [comment]
I managed this but I have no Idea how...

I was feeding my collection in a service callback, but I had a weird way to build the collection (business specific sorting)

1- I removed the weird sorting functionnality (commented) => Datatable was fed 
2- I put the EXACT same sorting feature (uncommented) => Datatable was fed, and it's working since then....

I'll keep this source for further needs.

Many thanks for help !

Regards,
Denis.
