### ISSUE TITLE
Error on Expansion Panel

### ISSUE THREAD

**Issue by aurelianv** [angular/material2#9524]
#### Bug, feature request, or proposal:
main.d36db8d0fd0e060939a1.bundle.js:1 Invalid keyframe value for property height: 62,7656px
e._triggerWebAnimation @ main.d36db8d0fd0e060939a1.bundle.js:1
e._buildPlayer @ main.d36db8d0fd0e060939a1.bundle.js:1
e.play @ main.d36db8d0fd0e060939a1.bundle.js:1
e.play @ main.d36db8d0fd0e060939a1.bundle.js:1
(anonymous) @ main.d36db8d0fd0e060939a1.bundle.js:1
e._flushAnimations @ main.d36db8d0fd0e060939a1.bundle.js:1
e.flush @ main.d36db8d0fd0e060939a1.bundle.js:1
e.flush @ main.d36db8d0fd0e060939a1.bundle.js:1
(anonymous) @ main.d36db8d0fd0e060939a1.bundle.js:1
e.invoke @ main.d36db8d0fd0e060939a1.bundle.js:1
l.run @ main.d36db8d0fd0e060939a1.bundle.js:1
e.runOutsideAngular @ main.d36db8d0fd0e060939a1.bundle.js:1
e.end @ main.d36db8d0fd0e060939a1.bundle.js:1
e.detectChanges @ main.d36db8d0fd0e060939a1.bundle.js:1
(anonymous) @ main.d36db8d0fd0e060939a1.bundle.js:1
e.tick @ main.d36db8d0fd0e060939a1.bundle.js:1
(anonymous) @ main.d36db8d0fd0e060939a1.bundle.js:1
e.invoke @ main.d36db8d0fd0e060939a1.bundle.js:1
onInvoke @ main.d36db8d0fd0e060939a1.bundle.js:1
e.invoke @ main.d36db8d0fd0e060939a1.bundle.js:1
l.run @ main.d36db8d0fd0e060939a1.bundle.js:1
e.run @ main.d36db8d0fd0e060939a1.bundle.js:1
next @ main.d36db8d0fd0e060939a1.bundle.js:1
t.object.i @ main.d36db8d0fd0e060939a1.bundle.js:1
t.__tryOrUnsub @ main.d36db8d0fd0e060939a1.bundle.js:1
t.next @ main.d36db8d0fd0e060939a1.bundle.js:1
t._next @ main.d36db8d0fd0e060939a1.bundle.js:1
t.next @ main.d36db8d0fd0e060939a1.bundle.js:1
t.next @ main.d36db8d0fd0e060939a1.bundle.js:1
t.emit @ main.d36db8d0fd0e060939a1.bundle.js:1
M @ main.d36db8d0fd0e060939a1.bundle.js:1
L @ main.d36db8d0fd0e060939a1.bundle.js:1
onInvokeTask @ main.d36db8d0fd0e060939a1.bundle.js:1
e.invokeTask @ main.d36db8d0fd0e060939a1.bundle.js:1
l.runTask @ main.d36db8d0fd0e060939a1.bundle.js:1
t.invokeTask @ main.d36db8d0fd0e060939a1.bundle.js:1
p @ main.d36db8d0fd0e060939a1.bundle.js:1
f @ main.d36db8d0fd0e060939a1.bundle.js:1
main.d36db8d0fd0e060939a1.bundle.js:1 ERROR DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at e._triggerWebAnimation (https://material.angular.io/main.d36db8d0fd0e060939a1.bundle.js:1:1920399)
    at e._buildPlayer (https://material.angular.io/main.d36db8d0fd0e060939a1.bundle.js:1:1920055)
    at e.play (https://material.angular.io/main.d36db8d0fd0e060939a1.bundle.js:1:1920622)
    at e.play (https://material.angular.io/main.d36db8d0fd0e060939a1.bundle.js:1:1916328)
    at https://material.angular.io/main.d36db8d0fd0e060939a1.bundle.js:1:1912523
    at Array.forEach (<anonymous>)
    at e._flushAnimations (https://material.angular.io/main.d36db8d0fd0e060939a1.bundle.js:1:1912400)
    at e.flush (https://material.angular.io/main.d36db8d0fd0e060939a1.bundle.js:1:1907673)
    at t.e.flush (https://material.angular.io/main.d36db8d0fd0e060939a1.bundle.js:1:1918494)
    at https://material.angular.io/main.d36db8d0fd0e060939a1.bundle.js:1:1925892
l @ main.d36db8d0fd0e060939a1.bundle.js:1
e.handleError @ main.d36db8d0fd0e060939a1.bundle.js:1
(anonymous) @ main.d36db8d0fd0e060939a1.bundle.js:1
e.invoke @ main.d36db8d0fd0e060939a1.bundle.js:1
l.run @ main.d36db8d0fd0e060939a1.bundle.js:1
e.runOutsideAngular @ main.d36db8d0fd0e060939a1.bundle.js:1
e.tick @ main.d36db8d0fd0e060939a1.bundle.js:1
(anonymous) @ main.d36db8d0fd0e060939a1.bundle.js:1
e.invoke @ main.d36db8d0fd0e060939a1.bundle.js:1
onInvoke @ main.d36db8d0fd0e060939a1.bundle.js:1
e.invoke @ main.d36db8d0fd0e060939a1.bundle.js:1
l.run @ main.d36db8d0fd0e060939a1.bundle.js:1
e.run @ main.d36db8d0fd0e060939a1.bundle.js:1
next @ main.d36db8d0fd0e060939a1.bundle.js:1
t.object.i @ main.d36db8d0fd0e060939a1.bundle.js:1
t.__tryOrUnsub @ main.d36db8d0fd0e060939a1.bundle.js:1
t.next @ main.d36db8d0fd0e060939a1.bundle.js:1
t._next @ main.d36db8d0fd0e060939a1.bundle.js:1
t.next @ main.d36db8d0fd0e060939a1.bundle.js:1
t.next @ main.d36db8d0fd0e060939a1.bundle.js:1
t.emit @ main.d36db8d0fd0e060939a1.bundle.js:1
M @ main.d36db8d0fd0e060939a1.bundle.js:1
L @ main.d36db8d0fd0e060939a1.bundle.js:1
onInvokeTask @ main.d36db8d0fd0e060939a1.bundle.js:1
e.invokeTask @ main.d36db8d0fd0e060939a1.bundle.js:1
l.runTask @ main.d36db8d0fd0e060939a1.bundle.js:1
t.invokeTask @ main.d36db8d0fd0e060939a1.bundle.js:1
p @ main.d36db8d0fd0e060939a1.bundle.js:1
f @ main.d36db8d0fd0e060939a1.bundle.js:1
Navigated to https://github.com/angular/material2

#### What are the steps to reproduce?
Open https://material.angular.io/components/expansion/overview
(my Chrome v. 63.0.3239.132 - 64 bit))
Press the expansion panel once or multiple times.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
