### ISSUE TITLE
Need support on how to implement custom theme for material

### ISSUE THREAD

**Issue by HeavenlyHost** [angular/material2#953]
#### Bug, feature request, or proposal:
This is more a cry for help, can I see an example of how to implement setup my project to use a different material theme other than the default one ? No sure how to make this work across all my components

#### What is the expected behavior?
n/a

#### What is the current behavior?
n/a

#### What are the steps to reproduce?
n/a

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
n/a

#### What is the use-case or motivation for changing an existing behavior?
n/a

#### Which versions of Angular, Material, OS, browsers are affected?
n/a

#### Is there anything else we should know?
n/a

**Comment by fxck** [comment]
there's not any way at the moment, what you could do is modify these https://github.com/angular/material2/blob/master/src/core/style/_default-theme.scss#L9 and create your own build

**Comment by jelbourn** [comment]
See #123
