### ISSUE TITLE
List item with textarea in List is not displayed well

### ISSUE THREAD

**Issue by zijianhuang** [angular/material2#9530]
#### Bug

If the list has a textarea, either single line or multiple lines with directive matLine, the items are displayed badly. And the textarea won't accept Enter or Ctrl+Enter to break lines.

#### What is the expected behavior?

Look good. and scrollable when having a lot list items. textarea should allow multiple line.

#### What are the steps to reproduce?
In https://material.angular.io/components/list/examples, go to the demo at https://stackblitz.com/angular/lyxpnrpmvpe?file=app%2Flist-sections-example.html, add the following in mat-list-item:

`<textarea mat-line></textarea>`

or 
`
<textarea mat-line  matTextareaAutosize matAutosizeMinRows="4" matAutosizeMaxRows="8"></textarea>`

#### What is the use-case or motivation for changing an existing behavior?

Multiple items of textarea for inputting and viewing multiple notes. List is used to be a scrollable area if there are many notes.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5.2, Material 5.0.3

**Comment by jelbourn** [comment]
`mat-line` is meant to say "This is a single line of text", which a `textarea` is not. In general you should be able to put a `textarea` inside of a `<mat-list-item>` with some custom css; it's a pretty unorthodox use-case, so I wouldn't necessarily to expect it to be exact as you want it out of the box.
