### ISSUE TITLE
add @angular/cdk/testing in the released package

### ISSUE THREAD

**Issue by vthinkxie** [angular/material2#9531]
#### Bug, feature request, or proposal:

request

#### What is the expected behavior?

There are many useful test utils in `@angular/cdk/testing`, and we want to use them in our project.
please add `@angular/cdk/testing` in the the released package, thanks!

#### What is the current behavior?

there is no `@angular/cdk/testing` in the released package

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by willshowell** [comment]
I remember reading that they intend to eventually, but want to be careful about exposing anything too soon, because anything exposed in the release has to fall under semver.

**Comment by Almar** [comment]
I'm just here to support this request. I find testing hard and look at the source of @angular/material for inspiration. These tests use @angular/cdk/testing and I would like the same functionality.

**Comment by jelbourn** [comment]
See https://github.com/angular/material2/issues/5803#issuecomment-323211124

Someday will will spend some time to build out some real, public-facing test utilities, but today it's just a grab-bag of random stuff we needed to test out own components. We're not ready to support what's there as a public API.

**Comment by jonrimmer** [comment]
@jelbourn I don't understand. I thought the CDK was a development kit intended to enable creation of our own components? How can we test those components properly if the testing infrastructure that *you* require to test your *own* components isn't made public?

E.g the CDK provides a `FocusMonitor` service for managing focus, and all the focus related tests in the CDK rely on a `patchElementFocus` helper method to work properly. If *you* can't test your components focus-handling capabilities without this, then how can anybody else hope to?

Unless your argument is that testing of components is unnecessary, then aren't these helper methods just as vital to CDK end-users as the actual services they help test?

**Comment by jelbourn** [comment]
Like I said, it's something we definitely want to do, but nobody has had the resources yet to turn this into a fully fledged subpackage with tests, documentation, and polished APIs.

**Comment by jonrimmer** [comment]
Again, how can we test CDK components properly if the testing infrastructure that you've found necessary to test your own components isn't made public?

Are we just supposed to copy and paste everything from the CDK? How it that better than just including this code in the release? I don't care about a fully fledged subpackage with tests, documentation, and polished APIs.
