### ISSUE TITLE
MatDialog not centered and not modal by default

### ISSUE THREAD

**Issue by chitgoks** [angular/material2#9532]
Using angular material 5.1.0

The MatDialog always opens at the bottom. I read one post about this issue with MDDialog, has the issue not been fixed? and the workaround should still be the same by overriding the mat-dialog-container class?

Also, i thought by default it would be modal but it does not seem to be so since i can click the button again and it creates another dialog.

**Comment by donroyco** [comment]
Please use the [issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md) and provide a StackBlitz.

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

**Comment by chitgoks** [comment]
never mind this. i got it to work. had to manually add

@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';

in styles.css
