### ISSUE TITLE
How to use the force-item-list on the mat-autocomplete ? 

### ISSUE THREAD

**Issue by kevincaradant** [angular/material2#9533]
#### Bug, feature request, or proposal:
Question

I'm a little bit lost about this feature :https://github.com/angular/material2/issues/3334

Why it's seems exist since 2015: https://github.com/angular/material/issues/2492 ?

Can you explain me how to use this feature with a snipet code very simple ? 
(I didn't see it in the official documentation)

And to be more clear, is there a way to tell, if you write/remove something in more of the selected value, you show an error like: "please select an item from the item list" so with my reactive Form, I can't valid the form until I solve the problem ? 

Example:
![image](https://user-images.githubusercontent.com/6093175/35277221-4c18f886-0046-11e8-99f8-3137530e9c55.png)

So I decide to select "testchantal2"
![image](https://user-images.githubusercontent.com/6093175/35277242-5d41c50c-0046-11e8-9ab8-bb6eea4bf424.png)

But now if I write this:
![image](https://user-images.githubusercontent.com/6093175/35277259-6f96ff88-0046-11e8-9dc7-c0d47f2b938c.png)

And then valid my form, it will send the value selected but the end user doesn't know that he sent "testchantal2".

Other use case: 
You write exactly "testchantal2":
![image](https://user-images.githubusercontent.com/6093175/35277321-a6c51292-0046-11e8-8414-a407da900695.png)

And then you click outside of the autocomplete, you get this:
![image](https://user-images.githubusercontent.com/6093175/35277340-b71aff1c-0046-11e8-993a-c64685ea4442.png)

But if you decide to valid the form, the "required" error didn"t appear because you write something but my form is not send because you didn't choose a value from the autocomplete. 

I hope to be clear and you can help me about these questions.

Thank you in advance

Regards

**Comment by willshowell** [comment]
The two links you posted, (#3334, angular/material#2492) are for different libraries. The second one is for the Angular.js implementation of Material.

The feature does not yet exist in material2, so you should read through all the comments and discussion in #3334 to get an idea of the current workarounds. In particular, see https://github.com/angular/material2/issues/3334#issuecomment-352920220 and https://github.com/angular/material2/issues/3334#issuecomment-359551599 for examples.

**Comment by kevincaradant** [comment]
@willshowell , oh ok sorry for the mistake between the two issues. I will glance a look at the comments :)

Thank you
