### ISSUE TITLE
Datepicker: Year selection mode doesn't work with years before 1986

### ISSUE THREAD

**Issue by belavenuto** [angular/material2#9534]
#### Bug, feature request, or proposal: 
Bug

#### What is the expected behavior? 
Select year before 1986 correctly through "year selection mode", implemented in #8565 

#### What is the current behavior?
The year 1985 is missing, so when you select any year before 1986, it selects a year later, for example, when you select 1981, datepicker selects 1982.

#### What are the steps to reproduce?
The issue can be observed on Material docs, https://material.angular.io/components/datepicker/overview

![3y6t1ujavu](https://user-images.githubusercontent.com/30418097/35277883-58dad402-002f-11e8-8813-369d0c1ed426.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.1.3
Material: 5.1.0
OS: Windows 7
TypeScript: 2.6.2
Browsers: 

- Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Firefox Version 57.0.4 (64-bit)

#### Is there anything else we should know?
On IE 11, the behavior is correct.

**Comment by anymos** [comment]
Hi there in any case that it might be usefull, some of the device were having the same kind of weird issue.

We fixed it by fixing the locale in the constructor in english, following the french exemple in the doc as per 👍 

 providers: [
        // The locale would typically be provided on the root module of your application. We do it at
        // the component level here, due to limitations of our example generation script.
        {provide: MAT_DATE_LOCALE, useValue: 'en-US'},

        // `MomentDateAdapter` and `MAT_MOMENT_DATE_FORMATS` can be automatically provided by importing
        // `MatMomentDateModule` in your applications root module. We provide it at the component level
        // here, due to limitations of our example generation script.
        {provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE]},
        {provide: MAT_DATE_FORMATS, useValue: MAT_MOMENT_DATE_FORMATS},
    ]

this.adapter.setLocale('en');

**Comment by irowbin** [comment]
Hi @anymos  The `datepicker` working as expected after adding your example from above but, I think this is not a way to workaround though;  Thanks anyway! 👍

**Comment by mmalerba** [comment]
That workaround works because the bug is caused by the way DST is handled, and different locales have different DST rules. The real fix is to convert the dates to UTC for consistency before formatting. (coming in #10068)
