### ISSUE TITLE
slide-toggle not showing up with flex-layout in safari

### ISSUE THREAD

**Issue by bhaskar045** [angular/material2#9535]
#### Bug, feature request, or proposal:

bug
#### What is the expected behavior?
mat-slide-toggle button should be rendered properly

#### What is the current behavior?
mat-slide-toggle button is not  rendering  properly in IOS 11 Safari browser web view.

#### What are the steps to reproduce?
https://angular-material2-issue-66jjcl.stackblitz.io

Refer Stackblitz and emulated / Test in IOS 11.2 
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material: 5.0.0-rc0,
angular:5.0.2
os:ios 11
typescript:2.4.2
![img_0012](https://user-images.githubusercontent.com/35730908/35316219-7a0fde66-00f6-11e8-8830-0a8aa9b5d214.PNG)

#### Is there anything else we should know?
Slide toggle inside the sidenav view does not get rendered properly.

**Comment by DevVersion** [comment]
Thanks for your issue. Can you please provide a StackBlitz or Plunkr that shows your issue?
