### ISSUE TITLE
Ripple effect directive

### ISSUE THREAD

**Issue by tsm91** [angular/material2#955]
Here is a css framework agnostic ripple effect directive: https://www.npmjs.com/package/ng2-ripple-directive

I personally use this for bootstrap buttons, but i think you can implement this or a modded version to material2.

I originally wanted to take out the logic from material2 so i thought i'll write about it.

@jelbourn @kara

**Comment by jelbourn** [comment]
@tsm91 Not sure I understand what you mean. [We already have a ripple implementation](https://github.com/angular/material2/blob/master/src/core/ripple/ripple.ts) that was built with guidance from the Material Design UX team as to be perfectly on-specification.
