### ISSUE TITLE
No table overview on material cdk page

### ISSUE THREAD

**Issue by guilhermejcgois** [angular/material2#9551]
#### Bug, feature request, or proposal:
No overview for material cdk [page](https://material.angular.io/cdk/table/overview)

#### What is the expected behavior?
That have some information in the page and theme works within the page

#### What is the current behavior?
No information and only have the default theme, theme can't be changed

**Comment by andrewseguin** [comment]
There's information on the page, and you can use the theme picker at the top right to change the theme.


![pzhjsyo9zov](https://user-images.githubusercontent.com/22898577/35305805-b9e4fd02-004f-11e8-8fae-3bb4a968df6c.png)

Please re-open with clarification if I've misunderstood the issue
