### ISSUE TITLE
CDK Table Overview Documentation Not Showing

### ISSUE THREAD

**Issue by jbw91** [angular/material2#9554]
#### Bug, feature request, or proposal:
When I navigate to https://material.angular.io/cdk/table/overview the content that should be showing on the Overview tab does not load but simply is blank. The content appears properly on the API tab. I have tried several browsers including Chrome, Firefox, and Safari.

#### What is the expected behavior?
It should show the documentation regarding the CDK Table.

#### What is the current behavior?
It does not show the documentation. (See screenshot)

![screen shot 2018-01-23 at 4 57 56 pm](https://user-images.githubusercontent.com/5883616/35307181-d46c2eb6-005e-11e8-876f-46fb347c57c9.png)

#### What are the steps to reproduce?
Navigate to https://material.angular.io/cdk/table/overview and notice the content does not load.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Only noticed this after the release of Material 5.1.0.

**Comment by andrewseguin** [comment]
Bummer, looks like this is a real issue. Just did a hard refresh and found the same

![5wsl9ydteje](https://user-images.githubusercontent.com/22898577/35307562-1135075c-0058-11e8-8a73-ffe5f7e689aa.png)

**Comment by jelbourn** [comment]
@DevVersion could you take a look? I suspect this has something to do with the combination of dgeni generating the file and the docs site consuming it.
