### ISSUE TITLE
[mat-dialog] Example source and StackBlitz broken

### ISSUE THREAD

**Issue by hpawe01** [angular/material2#9564]
#### Bug, feature request, or proposal:
In the mat-dialog-example (https://material.angular.io/components/dialog/examples) the file `dialog-overview-example-dialog.html` is missing (in source and StackBlitz). The example on the webpage works though.

#### What is the expected behavior?
File `dialog-overview-example-dialog.html` should be in the source and StackBlitz example should work

#### What is the current behavior?
File `dialog-overview-example-dialog.html` is missing in the source and StackBlitz example is not working

#### What are the steps to reproduce?
See https://stackblitz.com/angular/mrqyypvarrl

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current version on webpage (5.1.0)

**Comment by donroyco** [comment]
[The file](https://github.com/angular/material2/blob/master/src/material-examples/dialog-overview/dialog-overview-example-dialog.html) is in the repository though...

**Comment by DevVersion** [comment]
Thanks for the issue. This issue has been fixed yesterday with https://github.com/angular/material2/commit/e5c8880bfdb7868f92bdf8429d1bfb44c33e59da
