### ISSUE TITLE
Function on (closed) of  <mat-expansion-panel> is called when I am opening the another panel.

### ISSUE THREAD

**Issue by nishant-varshney** [angular/material2#9569]
I am using the mat-accordion and inside this there is multiple mat-expansion-panel. On the very first mat-expansion-panel i am calling a function on (closed). By default very first  mat-expansion-panel is closed.Now when the page loads and i am clicking on second  mat-expansion-panel  then the function on very first  mat-expansion-panel (closed) is getting called. I want that when we open a collapsible and then close it or any other collapsible then only the (closed) function will get called.

```
<mat-accordion class="example-headers-align myaccordion">
	 		 <mat-expansion-panel  hideToggle="true" class="myexpension" (opened)="fetchGeneralInfo()" (closed)="collpaseClose(0)"  #generalInfo>
	 		 <mat-expansion-panel-header>
	 		 	<mat-panel-title>
       			 			General Information
      			</mat-panel-title>
 </mat-expansion-panel>
    
   <mat-expansion-panel hideToggle="true" class="myexpension" #guaInfo (opened)="fetchGua()" >
    <mat-expansion-panel-header>
      <mat-panel-title>
        Gurantor Information
      </mat-panel-title>
 </mat-expansion-panel>
```

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
