### ISSUE TITLE
bug(tabs) "dynamic" content disappears when clicking thru tabs

### ISSUE THREAD

**Issue by fxck** [angular/material2#957]
#### Bug:
Dynamic content(bindings, child components) is rendered only on the first load, when you click on another tab, content never renders there and when you click back to the initial tab, it's gone as well.

#### What are the steps to reproduce?
http://plnkr.co/edit/cnLk1AuEJzfrG5agxIJe?p=preview

click on `Bar` and then back on `Foo` tab.

#### Which versions of Angular, Material, OS, browsers are affected?
rc.4, alpha.6

**Comment by robertmesserle** [comment]
@fxck Can you confirm if this can be recreated with the latest version of Angular and Angular Material?  I am not able to recreate this issue with the latest code.

**Comment by fxck** [comment]
Is there a plunker with latest version?

**Comment by ratscrew** [comment]
+1
I'm getting the same bug with the latest version.

**Comment by ratscrew** [comment]
The content will show if you click the same tab a second time.

**Comment by csepmdat** [comment]
+1

**Comment by fxck** [comment]
@csepmdat why and how did you manage to unassign @robertmesserle huh.

@jelbourn ?

**Comment by csepmdat** [comment]
@fxck Sorry but I have no idea. That was an accident somehow.
@jelbourn Can you reassign him please. Sorry.

**Comment by jelbourn** [comment]
Not sure why GitHub displays it that way, but Robert was unassigned since he's no longer working on Angular.

**Comment by fxck** [comment]
This appears to be working in the latest version, closing..
