### ISSUE TITLE
dashboard: github token for functions is invalid

### ISSUE THREAD

**Issue by DevVersion** [angular/material2#9570]
Looks like the GitHub token for the dashboard firebase functions is no longer valid / doesn't have the necessary permissions.

**Comment by jelbourn** [comment]
@DevVersion which key is this specifically?

**Comment by DevVersion** [comment]
@jelbourn That should be just the `secret.github` variable in the function environment.

https://github.com/angular/material2/blob/a48f75b454042798da0a94cfc62e0d94b26be7e1/tools/dashboard/functions/github/github-api.ts#L5
