### ISSUE TITLE
mat-table 'data-source' bug/inconsistency

### ISSUE THREAD

**Issue by momoadeli** [angular/material2#9572]
#### Bug, feature request, or proposal: 
`<mat-table>` datasource doesn't work on async/change detection-OR unify change detection process

#### What is the expected behavior?
datasource should trigger change detection regardless of whether hard set or set after async return of data (within a 'subscribe')

#### What is the current behavior?
datasource works one way when set to a const. eg:
**WORKS**

```

//  where ELEMENT_DATA is a simple array of objects):

datasource = new MatTableDataSource(ELEMENT_DATA); :`

```
**but DOESN'T work another way** (SHOULD WORK) when setting datasource on async return of a (eg) service:

```
`this.myService.getData().subscribe( (response) => {
     this.datasource.data = response.data;  <======== mat-table change detection not triggered
});
```

**but DOES work this way when using:**

`dataSource = new UserDataSource(this.workflowService);` where

```
export class UserDataSource extends DataSource<any> {
	constructor(private service: Service) {
		super();
	}
	connect(): Observable<IDataArray[]> {

		return this.service.getData()
			.map( (dataArray) => {
				return dataArray;
			},
			(error) => {

				return error;
			})
			.catch( (exception) => {

				return of(exception);
			});
	}
	disconnect() {}
}

```
The variations above are inconsistent...

#### What is the use-case or motivation for changing an existing behavior?
conventional Angular 2/5 change detection mechanism by passing in new object reference to datasource.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
  "@angular/core": "^5.1.2",, "@angular/material": "^5.0.3",

#### Is there anything else we should know?
Stackoverflow question on something that should be exceedingly simple: https://stackoverflow.com/questions/48411177/angular-material-table-mat-table-with-datasource-with-multiple-inner-array-a

**Comment by andrewseguin** [comment]
When the table receives new data, it checks to see if there are changes since the last data array. If there are changes, it will add/remove/move rows accordingly. If a row is inserted, it will mark for check so that cells fill in with the right content.

In your example, you are saying that when the data changes, the table does not check for changes. Can you reproduce this in a stackblitz so we can explore what's happening here? 

Also, to clarify, I assume this line was a typo:
`this.datasource = response.data;`

and you meant:
`this.datasource.data = response.data`

**Comment by momoadeli** [comment]
So I have this working in an 'Angular change detected' the way like it should. There are a couple of nuances which would've helped if documented. Basically, the datasource CAN be set within a simple async service `**map()**` (`**not subscribe()**`). No need for that extraneous
`export class UserDataSource extends DataSource<any>`.  So the below works:

`dataSource =  new MatTableDataSource();` <==== **NUANCE** ...not clearly mandated in examples

```
ngOnInit() {
	this.service.itemList()
	.map( (arrayItems) => {
		return this.dataSource.data = arrayItems; <====== **NUANCE** .data attribute should be set in map() operator.
	})
	.subscribe( (workflows) => {
	} );
}
```

The above is simple and clean.  Not sure yet how to do this if service returns object of TWO arrays, one `<mat-table>` for each array.

**Comment by julianobrasil** [comment]
@momoadeli, as @andrewseguin proposed above, try to reproduce it in a stackblitz. Why would the behavior be any different in each case (code is in map and in subscribe)?

**Comment by andrewseguin** [comment]
Not sure what you are struggling with but it doesn't seem to be an issue. If you find something wrong with the table then feel free to open up the issue with a stackblitz

**Comment by rsmrahul1** [comment]
I also face the same. Changes are not getting reflected when changing the data source of mat table.

**Comment by MadeRelevant** [comment]
Same here. When I resize the window it triggers change detection correctly.
I trtied subscribing to the data source's observable and call the changeDetector's markForCheck() method as well, didnt make any difference.  

I did notice that there is a difference between updating the properties of an object but keep the object reference itself same versus copying th eobject reference, make changes to those properties and replace the item in the array with the new reference.  
Both approaches didnt give the desired effect. The approach where I replace the reference it produced an empty row. I don't have time to create a stackblitz atm. Will try to come up with one soon.

**Comment by noah-fernandes** [comment]
How is this still such a problem today? Where's the proper documentation for all this stuff? Frustrating as hell.

**Comment by zoualmamy** [comment]
I am stuck on this.. it's a shame there is no proper documentation on this issue to this day (Jan 2019)

**Comment by MadeRelevant** [comment]
I got it working by calling `renderRows` manually. About to leave my desk but some pseudo code:

```typescript
@ViewChild(MatTable) table: MatTable<any>;

ngOnInit() {
    this.tableSource.valueChanges.subscribe(() => {
        this.table.renderRows();
    });
}
```

**Comment by zoualmamy** [comment]
I am using angular/material 7.0.2 and your solution is not working..
