### ISSUE TITLE
[Tools] Closure compiler failure on demo-app

### ISSUE THREAD

**Issue by miguelramos** [angular/material2#9581]
#### Bug, feature request, or proposal:
Closure compiler not working or missing docs to how to use it.

#### What is the expected behavior?
Compile demo app with closure compiler.

#### What is the current behavior?
Running script for closure compiler trigger errors.

![image](https://user-images.githubusercontent.com/495720/35361497-7d6d2f60-0159-11e8-9691-80ecd101f991.png)

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
Testing demo app with closure compiler

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.1.1
Material: latest version
OS: OSX El Capitan - 10.11.6
Typescript: 2.5.3

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/495720/35361333-f169030e-0158-11e8-80f3-eeb58af66817.png)

**Comment by jelbourn** [comment]
Closing this since we're going to revisit Closure Compiler verification once we finish moving to bazel (#8369)
