### ISSUE TITLE
missing dialog-overview-example-dialog.html

### ISSUE THREAD

**Issue by raj2008** [angular/material2#9588]
#### Bug, feature request, or proposal:
The example given in https://material.angular.io/components/dialog/examples is missing the dialog-overview-example-dialog.html

#### What is the expected behavior?
The given code should work in stackblitz

#### What is the current behavior?
given example code at https://material.angular.io/components/dialog/examples  https://stackblitz.com/angular/mrqyypvarrl error with

Cannot find file:
app/dialog-overview-example-dialog.html

#### What are the steps to reproduce?
please see https://stackblitz.com/angular/mrqyypvarrl

#### What is the use-case or motivation for changing an existing behavior?
example given on https://material.angular.io should work

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
issue with example

**Comment by donroyco** [comment]
Please use the search function before opening duplicate issues. See #9564 and commit https://github.com/angular/material2/commit/e5c8880bfdb7868f92bdf8429d1bfb44c33e59da
