### ISSUE TITLE
npm install alpha 6-2 with RC 4 fails on peer dependencies

### ISSUE THREAD

**Issue by jkyoutsey** [angular/material2#959]
#### Bug, feature request, or proposal:
Alpha 6-2 requires Angular2 RC3's forms ^0.1.0.  But RC4 requires 0.2.0.  The caret will only match on 0.1.*, not 0.2.*.  

#### What is the expected behavior?
Should be able to install with @angular/forms@0.2.0 and work correctly with RC4

#### What is the current behavior?
```terminal
npm ERR! peerinvalid The package @angular/forms@0.2.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular2-material/checkbox@2.0.0-alpha.6-2 wants @angular/forms@^0.1.0
npm ERR! peerinvalid Peer @angular2-material/input@2.0.0-alpha.6-2 wants @angular/forms@^0.1.0
npm ERR! peerinvalid Peer @angular2-material/slide-toggle@2.0.0-alpha.6-2 wants @angular/forms@^0.1.0
```

#### What are the steps to reproduce?
Install ng2 RC 4
Try to install @angular2/checkbox@2.0.0-alpha.6-2

#### Which versions of Angular, Material, OS, browsers are affected?
Angular2 RC 4
Material 2.0.0 alpha 6-2

**Comment by Daeluse** [comment]
Those should be Warnings, not Errors. Ensure npm is updated to the latest version ~3.10.5

**Comment by jelbourn** [comment]
alpha.6-2 was only an `@experimental` release, not a `@latest` release. alpha.7 is released now.
