### ISSUE TITLE
Problem while Updating Angular Material? 

### ISSUE THREAD

**Issue by bhawin-bigstep** [angular/material2#9595]
#### Bug, feature request, or proposal:
I Just Upgraded `@angular/material` from 2.0.0-beta.8   to   5.1.0
Now i am getting tons of error on build

Also my app with 2.0.0-beta.8 version of angular/material is hanging for 2 seconds before starting

#### What is the expected behavior?
The New version of angular material should also work fine 

#### What is the current behavior?
Now i am getting tons of error on build

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
{
  "name": "tabs",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "concurrently \"npm run build:watch\" \"ng serve\" \"npm run watch:sass\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor",
    "build:sass": "node-sass src/sassFiles/ -o src/",
    "watch:sass": "npm run build:sass && node-sass src/sassFiles/ -wo src/",
    "build:custom": "concurrently \"npm run build:sass\" \"ng build --prod\""
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.4",
    "@angular/cdk": "^5.1.0",
    "@angular/common": "^4.1.0",
    "@angular/compiler": "^4.1.0",
    "@angular/core": "^4.1.0",
    "@angular/forms": "^4.1.0",
    "@angular/http": "^4.1.0",
    "@angular/material": "^5.1.0",
    "@angular/platform-browser": "^4.1.0",
    "@angular/platform-browser-dynamic": "^4.1.0",
    "@angular/router": "^4.1.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.22",
    "@ngui/auto-complete": "^0.13.2",
    "angular2-emoji-picker": "^1.4.6",
    "angular2-fontawesome": "^0.9.1",
    "angular2-mdl": "^2.13.2",
    "angular2-moment": "^1.4.0",
    "angularfire2": "^4.0.0-rc0",
    "bootstrap": "^3.3.7",
    "clientjs": "^0.1.10",
    "concurrently": "^3.5.0",
    "core-js": "^2.4.1",
    "firebase": "4.1.3",
    "firebase-admin": "^5.0.1",
    "firebase-functions": "^0.6.2",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "html2canvas": "^0.5.0-beta4",
    "install": "^0.10.1",
    "json-size": "^1.0.0",
    "jwt-express-decode": "^0.1.2",
    "lodash": "^4.17.4",
    "material-design-icons": "^3.0.1",
    "material-design-lite": "^1.3.0",
    "moment": "^2.18.1",
    "ng2-cache": "^0.1.11",
    "ng2-toastr": "^4.1.2",
    "ngx-color-picker": "^4.1.0",
    "ngx-tabs": "0.0.13",
    "ngx-tooltip": "0.0.9",
    "node-sass": "^4.5.3",
    "node-sass-json-importer": "^3.0.2",
    "npm": "^5.3.0",
    "pretty-bytes": "^4.0.2",
    "prettysize": "^0.1.0",
    "promise-polyfill": "^6.0.2",
    "rxjs": "^5.0.1",
    "systemjs": "^0.20.12",
    "ts-helpers": "^1.1.1",
    "twemoji": "^2.5.0",
    "yargs": "^8.0.2",
    "zone.js": "^0.8.9"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.2",
    "@angular/compiler-cli": "^4.1.0",
    "@types/jasmine": "2.5.47",
    "@types/node": "^7.0.14",
    "codelyzer": "~3.0.0",
    "jasmine-core": "2.6.1",
    "jasmine-spec-reporter": "4.0.0",
    "karma": "1.6.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.6.0",
    "protractor": "~5.1.1",
    "ts-node": "3.0.2",
    "tslint": "^5.1.0",
    "typescript": "~2.2.2",
    "url-loader": "^0.5.9"
  }
}

#### Is there anything else we should know?
I am getting really upset with this My app is hanging because of the old version of anguar/material

**Comment by CDDelta** [comment]
Look through the [changelog](https://github.com/angular/material2/blob/master/CHANGELOG.md) for breaking changes. A noteworthy change is the [deprecation of Md prefixes](https://github.com/angular/material2/blob/master/CHANGELOG.md#deprecation-of-md-prefix).

**Comment by andrewseguin** [comment]
You're best bet might be to upgrade one version at a time til you reach 5.0. Each beta release had a lot of breaking changes, especially as we got closer to the RC candidates. As @CDDelta pointed out, check out the changelog for help upgrading through the releases

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
