### ISSUE TITLE
@angular/material@2.0.0-beta.8 is making app to hang for 2 seconds on loading.

### ISSUE THREAD

**Issue by bhawin-bigstep** [angular/material2#9596]
#### Bug, feature request, or proposal:
@angular/material@2.0.0-beta.8 is making app to hang for 2 seconds on loading.

#### What is the expected behavior?
App shoud work fine

#### What is the current behavior?
App is hanging for 2 sec on Load

#### What are the steps to reproduce?
http://mobiledemo.socialengineaddons.com/
In this website the app is loaded in iframe

#### Is there anything else we should know?
I have included

**Comment by andrewseguin** [comment]
Sorry but we'll be unable to diagnose the issue here or provide any fixes. If you want help architecting/developing your app, you may want to reach out to the people on StackOverflow or Gitter or any other material2 group.
