### ISSUE TITLE
Issue with Sidenav and scrollbar

### ISSUE THREAD

**Issue by flipZomb** [angular/material2#9601]
#### Bug, feature request, or proposal:
Issue with sidenav and scrollbar

#### What is the expected behavior?
Should look nicer

#### What is the current behavior?
A "mat-sidenav" is shown with, for example, one item, and no scrollbar. Then lots of items are added and a scrollbar is shown. On IE and Chrome this scrollbar is rendered above the contents of the "mat-sidenav-content". After hiding and unhiding the "mat-sidenav" the scrollbar is placed correctly.

One Item:
![image](https://user-images.githubusercontent.com/33517613/35396304-c5b39ffa-01ec-11e8-8fbf-2f835b568164.png)

add items - ugly  :
![image](https://user-images.githubusercontent.com/33517613/35396350-e2481baa-01ec-11e8-97c6-cc738909fd30.png)

Hide and unhide - looks ok :
![image](https://user-images.githubusercontent.com/33517613/35396431-1692156e-01ed-11e8-8495-12ab4504eaee.png)

Seems to be working fine in Firefox.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-1mdrjt?file=app%2Fapp.component.html

#### What is the use-case or motivation for changing an existing behavior?
Want it to look nicer

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material: 5.1.0
Angular: 5.2.1
Windows
IE11, Chrome

**Comment by crisbeto** [comment]
You should be able to handle it using the `autosize` option. [Here's a fork of your example.](https://stackblitz.com/edit/angular-material2-issue-nvmhud?file=app/app.component.html)

**Comment by mmalerba** [comment]
closing since adding `autosize` resolves it

**Comment by ShaneCourtrille** [comment]
Based on the fact that autosize comes with a big performance warning should this really have been closed?  I would expect the resizing to occur when we use the provided API?
