### ISSUE TITLE
Grid with masonry like brick layout

### ISSUE THREAD

**Issue by cyberbeast** [angular/material2#9613]
#### Bug, feature request, or proposal:
Material Design spec allows for a grid with masonry like brick layout.

#### What is the expected behavior?
https://plus.google.com/discover or even https://keep.google.com/ - homepage like layout where each post could potentially be an md-card.

#### What is the current behavior?
This can not be achieved using the existing the grid implementation.

**Comment by julianobrasil** [comment]
@cyberbeast, could you give more details telling what prevents `MatGrid` to fulfill your exptectations? Does @kara do in this [this video](https://youtu.be/0q9FOeEELPY) what you need?

**Comment by julianobrasil** [comment]
Also take a look at: https://stackblitz.com/edit/angular-material2-list-of-cards

**Comment by jelbourn** [comment]
We consider application-level layout to be outside the scope of Angular Material, which focuses on individual components.

**Comment by cyberbeast** [comment]
@julianobrasil First of all, thank you so much for your response to my query. I went over the video you shared and while it does aim to do what I want, I find the following limitations:-

1. The row/column span has to be manually specified.
2. While that strategy might work for images, would that necessarily scale to other containers such as cards?

While MatGrid certainly does allow cards to span over a single row, it still feels like the grid system (just like, other grid systems) is "row-oriented". I might be missing something here, but it feels like these grid systems are dictated by the following pseudo-protocol - "Here is a row, here are the items that need to be inserted in the row. Here is the next row, here are the items for the second row.". How would MatGrid enable a layout that enforces a "column-first approach" - "Here are 'n' columns. Here is a set of items that I want spread across these columns ."

[Here](https://docs.google.com/drawings/d/e/2PACX-1vR2Yr01_MyndAxkMIooNwhLu-q2RaG7NIC3WY7EnBPMdhg-uEga9CHwtia5SkKtbEYsGsybHJzQfEMc/pub?w=960&h=720) is a visual representation of what I am talking about. Notice the non-uniform height for each element.

Again, thank you for engaging in this discussion. Appreciate the input.

**Comment by julianobrasil** [comment]
@cyberbeast, even there's no component based on column it would not be so complicated to do it with regular components. You can use `flex-layout` to achieve this result: https://stackblitz.com/edit/angular-material-column-component

Basically you need something like:

```html
<div fxLayout="row" 
     fxLayoutAlign="center start" 
     fxLayoutGap="20px">
	
  <div *ngFor="let row of _data" 
        fxFlex="33" 
        fxLayout="column" 
        fxLayoutAlign="center start" 
        fxLayoutGap="20px">

    <div *ngFor="let el of row"
          [style.width]="'100%'">
      
      <mat-card>
        card {{el}}
      </mat-card>

    </div>

  </div>

</div>
```

**Comment by eugenekup** [comment]
@julianobrasil 
Thanks for this last example. This is almost what I am looking for. The only drawback from my point of view is that it's not responsive (e.g. it will not change to two and then one column for smaller screens). 

I am just starting looking into angular-flex as an alternative to bootstrap, therefore it would be very beneficial if you (or somebody) could provide a responsive example for this. Thank you!

That's an example of I am looking for: 
![image](https://user-images.githubusercontent.com/4934605/51080404-1eabd900-16d3-11e9-96cf-f8ae29284b85.png)

(I understand that's not angular-flex project but the topic is very similar to what I am looking for)

**Comment by khiami** [comment]
@eugenekup you might need to have a look at this the following examples and docs

- https://stackblitz.com/edit/angular-flex-layout-seed
- https://github.com/angular/flex-layout/wiki/Responsive-API

The responsive rules can be achieved with the 'object literal notation' expressions like fxFlex.md where 'md' stands for medium, there are other breakpoints as well for you to use.

**Comment by ricardosaracino** [comment]
> @eugenekup you might need to have a look at this the following examples and docs:
> 
> * https://stackblitz.com/edit/angular-flex-layout-seed
> * https://github.com/angular/flex-layout/wiki/Responsive-API
> 
> The responsive rules can be achieved with the 'object literal notation' expressions like `fxFlex.md` where '`md`' stands for medium, there are other breakpoints as well for you to use.

that wont work when your dealing with a fixed nested array

![image](https://user-images.githubusercontent.com/759253/60886043-f4208000-a21e-11e9-8273-ff8dc2e85cba.png)
