### ISSUE TITLE
One way binding behaviour - change not reflecting

### ISSUE THREAD

**Issue by dlarr** [angular/material2#9617]
#### Bug, feature request, or proposal:
* BUG ??

#### What is the expected behavior?
Suppose I have one component with @Input() 
I'd oneway bind like this : 
```
<comp [anObject]="someObject"></comp>
```

Suppose the object contains a collection
```
someObject = {
     someCollection = this.theCollection
}
```
Where theCollection is a component attribute

Whenever theCollection get updated, the change should be reflected in the <comp> component

#### What is the current behavior?
Whenever theCollection get updated, the change is *NOT* reflected in the <comp> component

#### What are the steps to reproduce?
Here I showed an exemple based on Angular Material tour hero
https://plnkr.co/edit/wdSOdjAZgbSmvrAlr8H0?p=preview
1- Select a Hero
2- Click on  the push item button

=> The Item collection does not get updated

#### What is the use-case or motivation for changing an existing behavior?
I made a complex table component based on MdTable and column descriptor should work like that.

Of course I found a workaround : feeding the collection trought the oneway bound object in the service callback. But I'd like to have it work easier.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
* OS : Windows 10
* TypeScript : 2.3.4
* Browser : Firefox 57.0.4 (64 bits)
* Angular / material versions:
```
 "dependencies": {
    "@angular/animations": "4.3.4",
    "@angular/cdk": "2.0.0-beta.10",
    "@angular/common": "4.3.4",
    "@angular/compiler": "4.3.4",
    "@angular/core": "4.3.4",
    "@angular/forms": "4.3.4",
    "@angular/http": "4.3.4",
    "@angular/material": "2.0.0-beta.10",
    "@angular/platform-browser": "4.3.4",
    "@angular/platform-browser-dynamic": "4.3.4",
    "@angular/router": "4.3.4",
    "@ngx-translate/core": "7.2.0",
    "@ngx-translate/http-loader": "1.0.2",
```

#### Is there anything else we should know?
No

Thanks for any help provided :)

**Comment by julianobrasil** [comment]
There's no problem with angular (see this [stackblitz demo](https://stackblitz.com/edit/angular-k2z2be)). 

The behavior you're describing is currently expected from `MatDataTable`. If you want `MatDataTable` to be updated, you should change the data source (`dataSource.data = yourData`). Doing `dataSource.data.push(moreData)` doesn't force `MatDataTable` to update the view.

Take a look at #9274 (specifically, take a look at https://github.com/angular/material2/issues/9274#issuecomment-356080781).

**Comment by dlarr** [comment]
I am sorry but, the problem doesn't come from the Datatable behaviour. Actually, I am describing a one way binding, that acts weird because the component is not reflecting changes that come from the parent. This is unrelated to datasource :)

**Comment by julianobrasil** [comment]
Could you provide a stackblitz demo (take one of that links I posted above) to show an example of what is currently happening (the one you've sent in your original post has _a lot_ of other things)?

**Comment by dlarr** [comment]
But there is almost nothing in the 1st plunker, it's very simple close to what I have. 

I've modify it to add another button with a working example and it now both work. So I don't know why it's not working in my project :(

**Comment by julianobrasil** [comment]
So put this question on stackoverflow.com, as it looks like trobbleshooting (and close this one). Also, when you wrote you had a component based on MdTable, I thought you were actually using MatDataTable. If this is not the case, then this part can cause some confusion.

In the future if you think this is a genuine bug, open a new issue in the [angular repo](https://github.com/angular/angular/issues) (currently this issue is in the angular/material2)

**Comment by dlarr** [comment]
Oh yes you're right. My mistake :'( I am so sorry.
