### ISSUE TITLE
[Stackblitz] Add divider module to imports

### ISSUE THREAD

**Issue by TheRedD0t** [angular/material2#9618]
The divider module that came with https://github.com/angular/material2/pull/5862 should be added to the imports in the Stackblitz templates.

@josephperrott

**Comment by josephperrott** [comment]
Stackblitz starter issue is updated to include all of the current Material modules.  Will leave this open for @DevVersion to track adding the modules to the stackblitz templates within the docs site.

**Comment by DevVersion** [comment]
@josephperrott Sounds good. For the template, we should also add it to the `NgModule` imports. Right now it's just imported, but not used. can you update that?
