### ISSUE TITLE
Input doesn't blur by clicking outside of it on IOS.

### ISSUE THREAD

**Issue by pmilic021** [angular/material2#9623]
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
When user clicks on input, keyboard opens, and when clicks outside of input, keyboard closes (and blurs input).

#### What is the current behavior?
When user clicks on input, keyboard opens, and when clicks outside of input, keyboard remains open (and input doesn't get blurred - the caret is still pinging inside input).

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
Open https://material.angular.io/components/input/overview on any IOS browser and click on input field, and then click outside of it.

#### What is the use-case or motivation for changing an existing behavior?
It is intuitive to close blur input by clicking outside of it.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All browsers on IOS (tested on safari, firefox and chrome), latest angular and material.

#### Is there anything else we should know?
When I add ```(blur)``` to the input, it wont fire by clicking outside of the input element, only once I managed to change focus to another element (e.g. some other input).

**Comment by crisbeto** [comment]
AFAIK this is how iOS handles focus in general. It doesn't move focus or dispatch click events unless you've tapped on something it considers tappable (e.g. a button, a link, something with `cursor: pointer`).

**Comment by pmilic021** [comment]
Guess I'll just leave it as it is then, and call it "feature".
