### ISSUE TITLE
[Chip input] Consider using a right margin instead of a left margin

### ISSUE THREAD

**Issue by TheRedD0t** [angular/material2#9627]
This would solve the issue with the ugly offset when there are multiple lines in a chip input.

![screenshot-2018-1-26 chips angular material](https://user-images.githubusercontent.com/32056062/35453730-8cd2a3cc-02cb-11e8-9b70-4e38c4925e6f.png)
_Before_

![screenshot-2018-1-26 chips angular material 1](https://user-images.githubusercontent.com/32056062/35453734-8ee3e7ac-02cb-11e8-9f5b-c13e6339f80b.png)
_After_

I also used in the demo image a top margin instead of bottom margin, this would be the same styling as in material for angularjs as mentioned by @merobal in #8587.

**Comment by tinayuangao** [comment]
Should be resolved by #9762.
