### ISSUE TITLE
mat-select not taking input

### ISSUE THREAD

**Issue by grosch** [angular/material2#9653]
#### Bug, feature request, or proposal:

Bug

#### What is the current behavior?
When I put a mat-select inside my table, all I see is the drop-down arrow and when I click on it nothing happens.  I don't even see the placeholder text.

#### What are the steps to reproduce?
I couldn't reproduce this in StackBlitz, sorry.  In my app.component.html file I have this:

```html
<td>
    <mat-select placeholder="-- Select --" multiple>
        <mat-option>Bob</mat-option>
    </mat-select>
</td>
```
In my `app.module.ts` file I added these two lines:

```typescript
import {MatSelectModule} from '@angular/material';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
```

and I added both those module names to the `imports` tag.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

npm 5.6.0
node v9.4.0
mac 10.13.2 (High Sierra)
@angular/material 5.1.0
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

devDependencies for typescript says ~2.6.2

#### Is there anything else we should know?

I'm brand new to Angular and this library, so I'm sure I've missed some type of setup step.

**Comment by crisbeto** [comment]
You need to wrap your `mat-select` in a `mat-form-field`.

**Comment by grosch** [comment]
That helped with the width, thanks.  The core issue what I didn't have this line in my styles.css file:

@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
