### ISSUE TITLE
Dialog examples are missing a file on the website

### ISSUE THREAD

**Issue by tubli** [angular/material2#9655]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
StackBlitz shows a working Dialog component example

#### What is the current behavior?
StackBlitz shows an error saying that it can't find the file. The exact name of the file that can't be found varies depending on the example, but on the actual Example page, the error is:
Cannot find file: app/dialog-overview-example-dialog.html

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

Go to:
https://material.angular.io/components/dialog/examples
click the "Edit with StackBlitz" button
After StackBlitz loads, it displays an error

If this is not the correct place to display this issue, please let me know where to post it instead.

**Comment by donroyco** [comment]
Please use the search function before opening duplicate issues. See #9588, #9564 and commit e5c8880
