### ISSUE TITLE
[Feature-Request] Ability to set theme/color of the datepicker calendar popup

### ISSUE THREAD

**Issue by benjamincharity** [angular/material2#9658]
#### Bug, feature request, or proposal:

Currently you can set the `[color]` property of the input attached to the datepicker. But there doesn't seem to be a way to change the color of the calendar itself.

So the focused input may be set to your accent color, but when the calendar opens it is still using the primary color.

> input is using accent color - green
<img width="345" alt="screen shot 2018-01-29 at 8 20 03 am" src="https://user-images.githubusercontent.com/270193/35512522-0693523e-04ce-11e8-9910-fc0be5250b69.png">

> calendar still using primary color - blue
<img width="304" alt="screen shot 2018-01-29 at 8 20 07 am" src="https://user-images.githubusercontent.com/270193/35512530-0970dd50-04ce-11e8-9b50-f04a9215ea5b.png">

#### What is the expected behavior?

We should have the ability to match the calendar selection color to the input focus color. Either via the `[color]` directive or the ability to add classes to the calendar container.

#### What is the current behavior?

Currently there is no way to set the theme/color or add custom classes to the calendar popup container.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-datepicker-theme?file=app/app.component.html

#### What is the use-case or motivation for changing an existing behavior?

For the calendar color to match the attached input color. (without forcing the calendar to always use the primary color).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5.1.2

**Comment by crisbeto** [comment]
Will be sorted out by https://github.com/angular/material2/pull/9407.

**Comment by zhangxin511** [comment]
@crisbeto 
I commented on #9407 as well, this feature seems dead on latest version: https://stackblitz.com/edit/angular-mhst5u
