### ISSUE TITLE
md-input not working with ngFormControl

### ISSUE THREAD

**Issue by sunshineo** [angular/material2#966]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-input works with ngFormControl

#### What is the current behavior?
Error: No value accessor for ''

#### What are the steps to reproduce?
I had a input
```
<input delay="500" md-input [ngFormControl]="searchTermControl" flex-gt-md="100" flex-md="100" flex-sm="100" flex-xs="100" type="input" placeholder="Search restaurant" />
```
worked fine until I upgrade. It still works after upgrade but the look is wrong. Now I need to change to <md-input></md-input>, but then I got the error.

**Comment by kara** [comment]
Alpha.6 and onward uses the new forms API. ngFormControl is part of the deprecated API, which is only supported in versions alpha.5 and before.  If you want to stick with the deprecated forms API, you'll have to downgrade to alpha.5.  I'd suggest upgrading to the new forms API instead though.

**Comment by sunshineo** [comment]
Thank you @kara !

**Comment by sunshineo** [comment]
However, I cannot figure out how to do debounce anymore
http://stackoverflow.com/questions/32051273/angular2-and-debounce
