### ISSUE TITLE
MatDialog is missing dial-overview-example-dialog.html on stackblitz

### ISSUE THREAD

**Issue by wa1gon** [angular/material2#9668]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MatDialog stackblitz should compile and work.

#### What is the current behavior?

Get an error:

Cannot find file:
app/dialog-overview-example-dialog.html

#### What are the steps to reproduce?

https://stackblitz.com/angular/plevlolnpkb

#### What is the use-case or motivation for changing an existing behavior?
 Provide working example of matDialog.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by donroyco** [comment]
Please use the search function before opening duplicate issues. See #9655, #9588, #9564 and commit e5c8880
