### ISSUE TITLE
Material buttons should default to type="button"

### ISSUE THREAD

**Issue by DAquilina** [angular/material2#9669]
#### Bug, feature request, or proposal:

Bug

#### What is the current behavior?

If `type="button"` is not added to buttons in a form, then they are treated as submit elements and the first will trigger when the user presses enter.

#### What is the expected behavior?

Only buttons explicitly set to submit on form submission should be triggered.

#### What are the steps to reproduce?

1. Create a form element
2. Add an input to that form
3. Add a button to the form *without* `type="button"`
4. Focus the input and press `enter`

https://angular-material2-issue-usgmlv.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?

It's not always desirable to have a form submit with enter, or in cases where that *is* desired having another button in the form should not prevent that behaviour by prematurely consuming the event.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

OS: MacOS 10.13.2
Browsers: Chrome 58.0.3029.110 (64-bit), Firefox 48.0.2, Firefox 57.0.4, Safari 11.0.2 (13604.4.7.1.3)
Material: 2.0.0-beta.12

#### Is there anything else we should know?

Note: in the example, the first button (button 0) has `type="button"` added, while the others (buttons 1 and 2) do not. You'll note that pressing enter in the input causes the click event for button 1 to fire, as it is the first available button without an explicit type. This takes precendent even over the button explicitly marked with `type="submit"`

Current workaround is to explicitly label your buttons in the form, but this tag should be set by default.

NOTE: I have also seen this behaviour in angular 5 without material (https://angular-5xxqzh.stackblitz.io), so this appears to be a base behaviour issue.

**Comment by djleonskennedy** [comment]
@DAquilina no it is not a bug, at first it's chrome only behavior for now, second developer is responsible for creating correct html content

**Comment by DAquilina** [comment]
Assuming a button element is type button hardly seems like "incorrect" markup. It's also not unreasonable to request that a directive which already adds properties to an element add a default property.

That said, I have updated the initial post based on further investigation borne of your concerns.

**Comment by DAquilina** [comment]
UPDATE: On a whim I tested this with no library, and found that the behaviour is consistent with all browsers after IE 7, namely because by spec the default button type is (for some reason) submit.

https://stackoverflow.com/a/31644856/686036

https://embed.plnkr.co/Q7zYDX0ohjXcBJTvE3L0/

To that end, I'm going to close this issue since it's unrelated to material.
