### ISSUE TITLE
md-button has a relative import for ripple

### ISSUE THREAD

**Issue by bennycooly** [angular/material2#967]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-button should compile

#### What is the current behavior?
The compiler fails due to the module "../../core/ripple" not being found.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
The button component should compile.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2 Material: git
Angular 2: git

#### Is there anything else we should know?
I saw that you changed the import to a relative import to fix linting but could you do:

import { MdRippleModule } from '@angular2-material/core/ripple/ripple'

**Comment by jelbourn** [comment]
Already fixed.
