### ISSUE TITLE
documentation -> Uncaught SyntaxError: Unexpected end of input 

### ISSUE THREAD

**Issue by artdias90** [angular/material2#9679]
#### Bug, feature request, or proposal:
Official documentation page is not working

#### What is the expected behavior?
Docs works

#### What is the current behavior?
`Uncaught SyntaxError: Unexpected end of input `

#### What are the steps to reproduce?
>> https://material.angular.io

**Comment by kepamuk** [comment]
Yes i have same problem, I can only open with anonimaizer

**Comment by josephperrott** [comment]
Closing as this will be tracked in: https://github.com/angular/material.angular.io/issues/378
