### ISSUE TITLE
The website is down.

### ISSUE THREAD

**Issue by iDiyor** [angular/material2#9680]
#### What is the expected behavior?
Not empty white screen! 

#### What is the current behavior?
Uncaught SyntaxError: Invalid Unicode escape sequence

#### What are the steps to reproduce?
Open browser -> type "https://material.angular.io/" -> hit enter.

Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome

**Comment by iDiyor** [comment]
Using the following link for now: https://material2-docs-dev.firebaseapp.com

**Comment by TheRedD0t** [comment]
It's working for me. Maybe it's up again.

**Comment by NZainchkovskiy** [comment]
Blank screen for me too. Something goes wrong.

**Comment by rk077** [comment]
Console error:
**Uncaught SyntaxError: Invalid Unicode escape sequence**

**Comment by NZainchkovskiy** [comment]
I got this error:
`SyntaxError: missing variable name`

**Comment by didzamons** [comment]
Firefox:
SyntaxError: missing variable name

**Comment by gaborkalmar** [comment]
I'm getting  : _Uncaught SyntaxError: Unexpected end of input_ in Chrome

**Comment by jainShipra** [comment]
Uncaught SyntaxError: Invalid Unicode escape sequence.

still not working.

**Comment by vkmi** [comment]
Broken in all the browsers I've tested it with:
- Edge
- Firefox 57
- Chrome 63
- Vivaldi 1.13
- IE 11

**Comment by OddDev** [comment]
https://material.angular.io/ results in a blank white screen. Console output is `SyntaxError: missing variable name`. FireFox Quantum 58.0.1 (64-bit) on Windows

**Comment by pantonis** [comment]
Same error now

**Comment by kseyhan** [comment]
ive got the same error with chrome and chromium.. latest version of firefox 58.0 works for me

**Comment by muellersergej** [comment]
Maybe the issue depends on the region since I have some co-workers who can access the site without issues. It appears that the service worker cannot be downloaded (is either stuck in 'pending' status or results in an error). 

![screen shot 2018-01-30 at 15 27 31](https://user-images.githubusercontent.com/375561/35571442-6b5579ae-05d2-11e8-9924-57d87897529a.png)

**Comment by rfprod** [comment]
![ff_chromium](https://user-images.githubusercontent.com/1507770/35572080-ae158300-0588-11e8-8672-f55184868681.png)

**Comment by josephperrott** [comment]
Closing as this will be tracked in: https://github.com/angular/material.angular.io/issues/378
