### ISSUE TITLE
Host Material2 Docs on GitHub (to selfhost own documentation site) or create docset for Zeal

### ISSUE THREAD

**Issue by RoestVrijStaal** [angular/material2#9685]
#### Bug, feature request, or proposal:
material.angular.io is down. Can't lookup any documentation about Material2

#### What is the expected behavior?
The idea is to make the documentation of Material2 vendor Independent so Material2 team can toy with their server while the rest of the world can develop with Material2 in comfort.

1. Put all the docs on separate GitHub repo (why are the demos on material.angular.io different than in [the examples in the repo](https://github.com/angular/material2/tree/master/src/material-examples) anyway)?
2. Even more ideal is to (help to) crate a Docset for [Zeal](https://zealdocs.org/) to reduce data traffic costs.

#### What is the current behavior?
White Screen

#### What are the steps to reproduce?
Visit [material.angular.io ](https://material.angular.io )

#### What is the use-case or motivation for changing an existing behavior?
Developing an app with Material2

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Any

#### Is there anything else we should know?
Automate your uptime checking and make it sure to kick people out their bed when the server is down.

**Comment by michahell** [comment]
for now: https://alligator.io/angular/material-design-angular-reference/

**Comment by josephperrott** [comment]
Closing as this will be tracked in: https://github.com/angular/material.angular.io/issues/378
