### ISSUE TITLE
provide connectToArea method in OverlayPositionBuilder

### ISSUE THREAD

**Issue by vthinkxie** [angular/material2#9690]
#### Bug, feature request, or proposal:

feature request

#### What is the expected behavior?

provide `connectToArea` in OverlayPositionBuilder.

#### What is the current behavior?
I have to provide the `ElementRef` when using `connectTo` function here.
https://github.com/angular/material2/blob/a48f75b454042798da0a94cfc62e0d94b26be7e1/src/cdk/overlay/position/overlay-position-builder.ts#L36

#### What is the use-case or motivation for changing an existing behavior?

When I am building context menu component with `@angular/cdk`, and I find it is difficult to open the context menu in an specific position or area, because the `connectedTo` function provided by `@angular/cdk` have to receive an origin `ElementRef`,
I create an 0px height and 0px width div, and connect to it as a temp solution

Is it possible to provide an function such as `connectToArea` in `OverlayPositionBuilder`, such as

```typescript
export interface AreaRef {
    width: number; // width of area
    height: number; // height of area
    x: number; // area x position
    y: number; //  area y position
}
 connectedToArea(
    area: AreaRef,
    originPos: OriginConnectionPosition,
    overlayPos: OverlayConnectionPosition): ConnectedPositionStrategy {
}

```

**Comment by jelbourn** [comment]
I would think you would want a globally positioned overlay for this case, no?

**Comment by vthinkxie** [comment]
@jelbourn yes, but it seems that the `global` api here
https://github.com/angular/material2/blob/a48f75b454042798da0a94cfc62e0d94b26be7e1/src/cdk/overlay/position/overlay-position-builder.ts#L26
could not provide the api like `withFallbackPosition` and the position defined by `global` api is not `absolute` but `static`
https://github.com/angular/material2/blob/a48f75b454042798da0a94cfc62e0d94b26be7e1/src/cdk/overlay/position/global-position-strategy.ts#L19

**Comment by jelbourn** [comment]
I see. It seems like what you really want it specifying an `(x, y)` coordinate in the place of an element, no?

**Comment by vthinkxie** [comment]
yes, I think it will be useful when material2 support context menu feature in #5007

**Comment by jelbourn** [comment]
I think it makes the most sense to track this as part of #5007
