### ISSUE TITLE
inconsistency between examples given in documentation and style guide.

### ISSUE THREAD

**Issue by praveeno** [angular/material2#9695]
Bug, feature request, or proposal:
type: - Documentation
inconsistency between examples given in documentation and style guide.
according to style guide Style 06-03 "HostListener/HostBinding decorators versus host metadata", decorators are recommended, but in angular material website, Directive Documentation it show examples only with host metadata.
it leads confusion.
let me know if you guys accepts this type of issues or not.
What is the expected behavior?
angular material documentation example should follow angular standard style guide

What is the current behavior?

What are the steps to reproduce?

What is the use-case or motivation for changing an existing behavior?
standard across examples and demo.

Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Is there anything else we should know?
That's all, & thanks for making web development such fun.

**Comment by jelbourn** [comment]
We use the host object because the decorator can sometimes have issues with platform-server. I'm not too concerned about this small deviation.

**Comment by andrewtw** [comment]
@jelbourn As you mentioned the decorator issues with `platform-server`, can you please sharing the known bugs? 
This would be helpful for other UIKit developers.
