### ISSUE TITLE
mat-card support for themes

### ISSUE THREAD

**Issue by crhairr** [angular/material2#9696]
#### Feature request:
Add first-class support for themes to mat-card, as well as all of its sections.

#### What is the expected behavior?
A "color", "background", or "theme" property on mat-card and its sections that make it easier to apply theme/palette colors other than the basic light/dark theme.

#### What is the current behavior?
Applying theme colors to cards requires custom classes and a bunch of boilerplate SCSS to extract palette colors from the application theme.

#### What is the use-case or motivation for changing an existing behavior?
Designing cards that aren't all white or black (depending on light or dark theme): cards should be theme-able like any other material element.

**Comment by jelbourn** [comment]
We don't have any plans to turn this into an API. You should be able to use CSS to customize the background color, or SCSS to pull the color from the current theme.
