### ISSUE TITLE
mat-autocomplete value not updating with browser autofill

### ISSUE THREAD

**Issue by leveyh** [angular/material2#9704]
#### Bug, feature request, or proposal:
Bug. 

#### What is the expected behavior?
FormControl value should change when using browser autofill to complete the address. 

#### What is the current behavior?
FormControl value does not change. Validation fails on the field.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-autocomplete-with-autofill

Start typing in the Name field. Use browser autofill to automatically fill out the rest of the form.

It seems as though the "Address line 1" field, which is controlled by a mat-autocomplete, fails to update  after autofill, causing validation to fail.

![autofill](https://user-images.githubusercontent.com/27446839/35593547-0a3f87c0-05c5-11e8-8cf7-b684de7f0265.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.1
Material: 5.1.0
Browser: Chrome 64.0.3282.119

**Comment by mmalerba** [comment]
@crisbeto assigning to you since this seems specific to the autocomplete

**Comment by Rawr421** [comment]
I also have this problem with:
Angular 6.0.0
Material: 6.0.1

Form control validation is failing on address_line1 when autofill is used. 
<img width="940" alt="screen shot 2018-05-07 at 4 36 27 pm" src="https://user-images.githubusercontent.com/10568904/39723873-19fef83e-5215-11e8-8d2a-10361466d12a.png">

Also, autofill is not updating the filtered values, because the control value is not updated.  
<img width="962" alt="screen shot 2018-05-07 at 4 37 58 pm" src="https://user-images.githubusercontent.com/10568904/39723895-2ff882f4-5215-11e8-80c5-e06b4b99b457.png">

**Comment by khobabc** [comment]
When would this fix be available?

**Comment by AdJesumPerMariam** [comment]
I also have this problem. My form control's value is not updating after a browser autofill and it is causing my validation to not work for autocomplete with control's set to updateOn: 'blur'

document.getElementById('input-email')['value']; // "email@example.com"
this.loginForm.get('email').value; // ""

Angular 6.1.3
Angular Material 6.4.5

Thanks!

**Comment by daniel-nagy** [comment]
For anybody else, I'm using the following workaround

```typescript
import { Component, Inject, ViewChild } from '@angular/core';
import { DOCUMENT } from '@angular/common';

```

**Comment by daniel-nagy** [comment]
For anyone else, I'm using the following workaround

```typescript
import { Component, Inject, ViewChild } from '@angular/core';
import { DOCUMENT } from '@angular/common';
import { MatAutocompleteTrigger } from '@angular/material';

@Component({
  ...
  template: `
    <input
      autocomplete="address-level1"
      (input)="onInput($event)"
      [matAutocomplete]="myAutocomplete"
      matInput
      #myAutocompleteTrigger="matAutocompleteTrigger">
      <mat-autocomplete #myAutocomplete="matAutocomplete">
        ...
      </mat-autocomplete>
  `
})
export class MyComponent {
  @ViewChild('myAutocompleteTrigger') private _myAutocompleteTrigger: MatAutocompleteTrigger;

  constructor(@Inject(DOCUMENT) private _document: Document) {

  }

  onInput = (event: KeyboardEvent) => {
    const target = event.currentTarget as HTMLInputElement;

    if (this._document.activeElement !== target) {
      this._myAutocompleteTrigger._onChange(target.value);
    }
  }
}
```
