### ISSUE TITLE
Update package-lock.json with dependencies

### ISSUE THREAD

**Issue by briantq** [angular/material2#9706]
#### Bug, feature request, or proposal:
To ensure build quality/stability, it would be nice to know which versions of dependencies were used to build a given release of Angular Material.  The package-lock.json is intended to provide exactly that, but it is not getting updated and is outdated.

#### What is the expected behavior?
Update the package json for a release, if not more often

#### What is the current behavior?
The package-lock.json hasn't been updated in a month even though the package.json has

#### What are the steps to reproduce?
Look at the commit history for the package-lock.json and the package.json.  The package.json changes but the package-lock.json does not.

#### What is the use-case or motivation for changing an existing behavior?
Twice dependencies have been introduced failures during a .X release.  Knowing which library versions Angular Material was built/tested against when it was "released", would be helpful in tracking down such issues.  

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by jelbourn** [comment]
AFAIK we do just that. The file was actually updated yesterday. Do you have an example of a commit that updates the deps in package.json without the lock?

**Comment by briantq** [comment]
Thanks for the quick reply. I was specifically looking at the latest release branch, 5.1.1. 

https://github.com/angular/material2/tree/5.1.1

In the branch the package.json was updated 13 days ago while the package-lock.json is over a month. 

Is there a better way to determine which dependency versions were used in the build/testing of the release?

**Comment by jelbourn** [comment]
Looks like it was just a mistake on that one. I'll update our release doc to avoid this in the future.
