### ISSUE TITLE
Material 5.1.1: Generic type 'TemplatePortal<C>' requires 1 type argument

### ISSUE THREAD

**Issue by kuzbida** [angular/material2#9710]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
ng serve/ng test should run successfully

#### What is the current behavior?
ng serve/ng test fails with following error:
```
ERROR in node_modules/@angular/material/expansion/typings/expansion-panel.d.ts(43,14): error TS2314: Generic type 'TemplatePortal<C>' requires 1 type argument(s).
node_modules/@angular/material/tabs/typings/tab-body.d.ts(62,15): error TS2314: Generic type 'TemplatePortal<C>' requires 1 type argument(s).
node_modules/@angular/material/tabs/typings/tab.d.ts(28,23): error TS2314: Generic type 'TemplatePortal<C>' requires 1 type argument(s).
```

#### What are the steps to reproduce?
Use @angular/material 5.1.1 with @angular "^5.2.1".

#### What is the use-case or motivation for changing an existing behavior?
Fix builds

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "5.1.0" - works fine, issue occurs with version 5.1.1
`"@angular/animations": "^5.2.1",
    "@angular/cdk": "5.0.4",
    "@angular/cli": "^1.6.6",
    "@angular/common": "^5.2.1",
    "@angular/compiler": "^5.2.1",
    "@angular/compiler-cli": "^5.2.1",
    "@angular/core": "^5.2.1",
    "@angular/flex-layout": "2.0.0-beta.10-4905443",
    "@angular/forms": "^5.2.1",
    "@angular/http": "^5.2.1",
    "@angular/material": "~5.1.0",
    "@angular/platform-browser": "^5.2.1",
    "@angular/platform-browser-dynamic": "^5.2.1",
    "@angular/platform-server": "^5.2.1",
    "@angular/router": "^5.2.1",`

**Comment by cravter** [comment]
@kuzbida 'npm install @angular/cdk@5.1.1' solved this problem for me

**Comment by josephperrott** [comment]
Closing as this is the result of having mismatched versions of `@angular/cdk` and `@angular/material`.  The versions must be in line with each other.
