### ISSUE TITLE
CDK Overlay is ignoring 'height' and 'width' configs

### ISSUE THREAD

**Issue by AsafAgranat** [angular/material2#9715]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
CDK overlay panel should get inline width and height properties defined by the 'width' and 'height' entries in the config.

#### What is the current behavior?
The overlay panel is rendered without any width or height. The 'height' property is defined in overlayConfig: https://github.com/angular/material2/blob/master/src/cdk/overlay/overlay-config.ts, and is also documented in the the [Overlay API](https://material.angular.io/cdk/overlay/api)

#### What are the steps to reproduce?
1.   Go to: https://stackblitz.com/edit/custom-overlay-step-2-mo6xro?file=app/file-preview-overlay.service.ts
2.   Click on one of the eye icons in the rendered app area.
3.   Inspect the overlay pane and see that it is receiving the 'max-width' property, but the 'height' property is missing, although it has been defined in the config. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.1.3, cdk 5.0.3, Typescript 2.6.2, windows 10, Chrome v63

#### Is there anything else we should know?
Your work and effort is much appreciated here!

**Comment by crisbeto** [comment]
I think this is a result of both the `OverlayRef` and the `GlobalPositionStrategy` having a `width` property for some historical reasons. The one in the `GlobalPositionStrategy` ends up overriding the one from the `OverlayRef`. I'll submit a fix, but until it gets in you should be able to work around it like this:

```ts
this.overlay.position()
      .global()
      .centerHorizontally()
      .centerVertically()
      .width('300px');
```

**Comment by AsafAgranat** [comment]
@crisbeto  - good workaround. Thanks!

**Comment by trichetriche** [comment]
The workaround is great, but how one should do with a `flexibleConnectedTo` position ? Nothing offers a `width` function ...

````typescript
this.overlay
      .position()
      .flexibleConnectedTo(anchor)
      .withPositions(positions);
````

**Comment by lebesnec** [comment]
Angular 8 : height is working, width is still KO with a `flexibleConnectedTo` position.
