### ISSUE TITLE
feature request - allow an action-row to be at top of expansion panel

### ISSUE THREAD

**Issue by ORESoftware** [angular/material2#9723]
#### Bug, feature request, or proposal:
Feature - allow action-row to be at top of expansion panel

#### What is the expected behavior?
I was hoping I could put an action-row at the top of an expansion panel, just below the title.

#### What is the current behavior?
https://stackoverflow.com/questions/48551683/include-action-row-at-the-top-of-expansion-panel

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
It would be nice to have action buttons at the top and the bottom of an expansion panel, especially if the content of the expansion panel is tall.

**Comment by josephperrott** [comment]
This is actually not allowed, because the entire `<mat-expansion-panel-header>` within the expansion panel is a button.  Placing another button in it as described in the request would break the a11y of the component.

**Comment by ORESoftware** [comment]
damn! I guess I can put my own buttons in the top right tho right

**Comment by mhagnumdw** [comment]
It is possible to place action buttons inside the `<mat-panel-description>` and in the event of (click) execute: event.stopPropagation()
