### ISSUE TITLE
[bug] Scrolling lag dialog

### ISSUE THREAD

**Issue by ToonvanStrijp** [angular/material2#9724]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior? & #### What is the current behavior?
The material dialog is scrollable however because of the 2px border radius on the scrolling container the dialog will repaint on scroll, this makes scrolling buggy especially when having many children.

<img width="1094" alt="screen shot 2018-01-31 at 23 37 53" src="https://user-images.githubusercontent.com/11893063/35651391-d5e57a0e-06df-11e8-93fa-e1ad8e20f4f0.png">

When adding this css to the `.mat-dialog-container` will fix this problem it also causes the border-radius to disappear.
```
.mat-dialog-container
    border-radius: 0
```

To have the border-radius and still solve the repaint issue you have to put the border-radius on the parent container, since MatDialog has an option `{panelClass: 'panel'}` we can add our styling then by doing this:
```
.panel
  .mat-dialog-container
    padding: 0
    border-radius: 0
    box-shadow: none
  box-shadow: 0 11px 15px -7px rgba(0,0,0,.2), 0 24px 38px 3px rgba(0,0,0,.14), 0 9px 46px 8px rgba(0,0,0,.12)
  border-radius: 2px
  overflow: auto
```

The box-shadow also has to be replaced to the parent container.

By doing this you'll get a good FPS inside a scrolling dialog with a border-radius. The only downside it that I couldn't figure out how to get the scrollbar to be visible. It appears to be shown outside the container.

<img width="1792" alt="screen shot 2018-01-31 at 23 45 41" src="https://user-images.githubusercontent.com/11893063/35651692-e0e780c2-06e0-11e8-830d-368d6696a93f.png">

**Comment by crisbeto** [comment]
The `mat-dialog-content` element is intended to be used as the scrollable container for the dialog which should help avoid the repaints.

**Comment by ToonvanStrijp** [comment]
@crisbeto as far I can see the mat-dialog-content doesn't prevent the repaint of the scrollable container:

<img width="1792" alt="screen shot 2018-02-01 at 10 12 56" src="https://user-images.githubusercontent.com/11893063/35670329-93be18b2-0738-11e8-9855-51b1cb0e68b0.png">

**Comment by crisbeto** [comment]
Will continue tracking in https://github.com/angular/material2/issues/8606.
