### ISSUE TITLE
Template Parse errors: Can't bind to md-ripple-trigger/md-ripple-color

### ISSUE THREAD

**Issue by FabioCZ** [angular/material2#973]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
md-button directive should work

#### What is the current behavior?
After updating to alpha 7, I get this error when loading my angular 2 application:
```
Template parse errors:
Can't bind to 'md-ripple-trigger' since it isn't a known property of 'div'. ("*ngIf="isRippleEnabled()" class="md-button-ripple" [class.md-button-ripple-round]="isRoundButton()" [ERROR ->][md-ripple-trigger]="getHostElement()" [md-ripple-color]="isRoundButton() ? 'rgba(255, 255, 255, 0.2)"): MdButton@0:180
Can't bind to 'md-ripple-color' since it isn't a known property of 'div'. ("ton-ripple" [class.md-button-ripple-round]="isRoundButton()" [md-ripple-trigger]="getHostElement()" [ERROR ->][md-ripple-color]="isRoundButton() ? 'rgba(255, 255, 255, 0.2)' : ''" md-ripple-background-color="rgb"): MdButton@0:219
```

#### What are the steps to reproduce?

https://gist.github.com/FabioCZ/7578c4cbebdd23d6f38f62c2f1fc9e13

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2 rc5
angular2-material alpha 7
chrome 52

**Comment by jelbourn** [comment]
@FabioCZ if you're not changing to `NgModule`s right away, then you need to also include `MD_RIPPLE_DIRECTIVES` from core in your `directives` list.

**Comment by FabioCZ** [comment]
@jelbourn thanks, got it to work

**Comment by zakdances** [comment]
I'm using `NgModule` and I still need to include `MD_RIPPLE_DIRECTIVES`.
