### ISSUE TITLE
hasBackdrop: false prevents transparent overlay behind modal

### ISSUE THREAD

**Issue by hoangnguyen208** [angular/material2#9732]
#### Bug, feature request, or proposal:
When I set `hasBackdrop: false`, the overlay behind modal is not dark and transparent as expected

#### What is the expected behavior?
I expect the same behavior as `hasBackdrop: true`, the overlay behind modal is dark and transparent

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-4gl8gc

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, @angular/material & @angular/cdk: 5.1.1

**Comment by willshowell** [comment]
That is expected behavior. The 'transparent overlay' behind the modal is the backdrop. What is it that you're trying to accomplish by setting `hasBackdrop: false`?

**Comment by hoangnguyen208** [comment]
Oh really, I did not it's the expected behavior. Is it possible to customize the back layer as normal backdrop if I still set `hasBackdrop: false` ? I used ng-bootstrap before and even I set backdrop to false, I still had normal backdrop but disable clicking outside modal to close it. Therefore, I just want to know that if material has this feature.

**Comment by willshowell** [comment]
Rather than setting `hasBackdrop` to false, I think what you'd like to do is use `disableClose: true` so that the user cannot close the modal via clicking on the backdrop.

**Comment by hoangnguyen208** [comment]
Thank you so much, it works.

**Comment by RatanKumar678** [comment]
> Rather than setting `hasBackdrop` to false, I think what you'd like to do is use `disableClose: true` so that the user cannot close the modal via clicking on the backdrop.

thanks ,this works for me "hasBackdrop:true"
