### ISSUE TITLE
Feature Request: mat-cell

### ISSUE THREAD

**Issue by amymercury** [angular/material2#9737]
#### feature request or proposal:

It would be nice to allow rendering custom HTML inside the table cells.

**Comment by andrewseguin** [comment]
![giphy](https://user-images.githubusercontent.com/22898577/35693896-772bcaae-0734-11e8-9a23-07096b5274af.gif)

Feel free to put any custom HTML in your `<mat-cell>` and it will show up in your table. If you have any trouble or run into issues, ask our community on Gitter or StackOverflow.
