### ISSUE TITLE
Is there a way to easily wrap or extend the components/directives in this library?

### ISSUE THREAD

**Issue by ShawnMercado** [angular/material2#9745]
I like using this library, it works very well and helps achieve a very clean effect.  The problem is, for my job, it's against coding standards to put third-party components/directives directly into html... the justification is that it hurts maintainability as its a lot harder to pull out than it is to put in.

I was hoping there was a way to wrap or extend each item I needed with my own name-spaced element, for re-use throughout a project, so that if we ever want to change something we simply change the implementation of that element to another library or to our own custom code.  But so far I cannot find a way to do this.

**Comment by jelbourn** [comment]
Generally we discourage extending the components but don't do anything to strictly prevent it.
