### ISSUE TITLE
mat-sidenav and mad-sidenav-container issues with 'TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by physicsboy** [angular/material2#9749]
### Bug, feature request, or proposal:
I have created a working app where there are no problems using your StackBlitz templates. However when refactoring my code to use the material components, I am coming up against the problem of console error surrounding the <mat-sidenav> element with console showing:

> TypeError: Cannot read property 'create' of undefined at MatSidenav.ngAfterContentInit (sidenav.js:326) at callProviderLifecycles 

### What is the expected behavior?
Expected behaviour is for this error not to occur such that I can use the component as expect and recreate what I made on StackBlitz

### What is the current behavior?
See above for description

##### Detailed Reproduction Steps: 
Basically the problem will be found within app.component.html... Everything is imported correctly and material components can be used as normal. However, the following tags make things fail...
<mat-sidenav-container>
<mat-sidenav>

Commenting these and their corresponding closing tags out, you are left with a <mat-list> that works fine... For some reason it seems to be the sidenav that is causing issues?

### What is the use-case or motivation for changing an existing behavior?
Without the sidenav component, my code will need a lot more finessing and changing, and will not work in the way intended with simple material design components.

### Which versions of AngularJS, Material, OS, and browsers are affected?
Angular 5
Material 5.1.1
Windows 10
Chrome

**Comment by jelbourn** [comment]
Your stackblitz reproduction has some issues: the bindings are incomplete and RouterModule isn't loaded. Can you update it to show the issue you're reporting here?

**Comment by theredpea** [comment]
I agree with @jelbourn , [I can't reproduce with that stackblitz (after fixing the issues)](https://stackblitz.com/edit/angular-material-bug-test-bts6h5?file=app/app.component.html)

I *am* getting this error locally, will add more detail as I get it; but the most obvious sign may be the preceding message; *could not find `HammerJS`*
```
10:58:35.610 core.js:136 Could not find HammerJS. Certain Angular Material components may not work correctly.
10:58:36.373 AppComponent.html:19 ERROR TypeError: Cannot read property 'create' of undefined
    at MatSidenav.ngAfterContentInit (sidenav.js:328)
```

**Comment by CRanaboldo** [comment]
This is an es6 problem - reverting to es5 resolves it

**Comment by seawave23** [comment]
Any news here? I had to change to ES6 and cannot revert to ES5. It really only happens locally.

**Comment by kcir3v4M** [comment]
Add the following import in your polyfills.ts
`import 'hammerjs/hammer';`

(don't forget to install hammerjs via npm)

**Comment by ltburch** [comment]
> This is an es6 problem - reverting to es5 resolves it

Switching back to es5 worked for me, nit sure what aspect of es6 sets it off,
