### ISSUE TITLE
md-input should support debounce

### ISSUE THREAD

**Issue by sunshineo** [angular/material2#975]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
md-input has a field that can be used to set a delay before trigger change event

#### What is the current behavior?
No such field and work around http://stackoverflow.com/questions/32051273/angular2-and-debounce no longer works because of reasons described in https://github.com/angular/material2/issues/966

Thanks!

**Comment by RoxKilly** [comment]
This can be accomplished easily by making the function that receive changes return an observable.  The code below works on `alpha 6`:

**HTML**
```
<md-input (keyup)="emitInput($event)"></md-input>
```
**Class (Typescript)**
```
    ngOnInit(){
        //subscribe to receive changes, with 300ms debounce
        this.inputChanges(300).subscribe(input => this.print(input));
    }
    //when called, will cause Observable returned by inputChanges to emit
    emitInput:(event:KeyboardEvent)=>void;

    //sets up emitInput to start sending values
    inputChanges(debounce:number):Observable<string>{
        return Observable.create(observer => {
            this.emitInput = (event:KeyboardEvent)=>{
                observer.next((<HTMLInputElement>event.target).value)
            }
        }).debounceTime(debounce);
    }
```

Every time a `keyup` occurs, if `debounce` milliseconds have passed since the last keyup, `inputChanges` will emit the current value in the input

**Comment by jelbourn** [comment]
The normal approach is to use a debounced handler function, not to rate limit the actual source of events.

**Comment by sunshineo** [comment]
Thank you @RoxKilly for the solution. Thank you @jelbourn for the design insight!

**Comment by sunshineo** [comment]
@RoxKilly I used your implementation, but I had to use one way binding on ngModel like [ngModel] and then test if the text changed because the keyup even could have been user press left or right arrow key. You can see that in you plunkr if you press left or right you got the same text printed over and over again. Is there a way to use this patter not on (keyup) but on (ngModelChange) ?

**Comment by RoxKilly** [comment]
@sunshineo I updated [to this plunker.](http://plnkr.co/edit/oEvQmrpEQfLGJIvkTr2y?p=preview) which will cause a value to be emitted only if it is different from the last value. I accomplished this by applying the `distinctUntilChanged()` operator before debouncing.

I've also updated my code above.

**Comment by sunshineo** [comment]
Thank you @RoxKilly . This looks like magic to me 👍
