### ISSUE TITLE
matInput placeholder position with prefix doesn't align with the input field

### ISSUE THREAD

**Issue by dhuallanca** [angular/material2#9750]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?
placeholder should be aligned with the input field

#### What is the current behavior?
placeholder is displayed after the prefix

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-jgpuyq?file=app/form-field-prefix-suffix-example.html

#### What is the use-case or motivation for changing an existing behavior?

UI design
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/material: "^5.1.0",
@angular/core: "^5.2.1",

Chrome

**Comment by dhuallanca** [comment]
It should work like material design guidelines:

https://material.io/guidelines/components/text-fields.html#text-fields-field-types

![image](https://user-images.githubusercontent.com/13484351/35816728-7cead0c4-0a69-11e8-8363-523170244a24.png)

**Comment by mmalerba** [comment]
this should be done via a text mask in the future, #7645 is tracking the issue
