### ISSUE TITLE
MatCheckbox disabled bug- changeDetectorRef markForCheck 

### ISSUE THREAD

**Issue by smdunn** [angular/material2#9763]
#### Bug, feature request, or proposal:
I found a bug within matCheckbox. I added a disabled class to the checkbox based on a method call. When disabled, the checkbox had class disabled and therefore had grey css etc, but if it was still clicked on, it had a click event which added a disabled class to the input within the checkbox. When the disabled class was removed from the outer matCheckbox, the disabled class remained on the input, so even though the checkbox appeared not to be disabled, it couldn't accept any more input. 

I propose to add the following to src/lib/core/common-behaviors/disabled.ts in order to markForCheck which fixes this issue for checkboxes:

set disabled(value: any) {
      if (this._changeDetectorRef){
        this._changeDetectorRef.markForCheck();
      }
      this._disabled = coerceBooleanProperty(value); }

But this will require changing the constructor for this class a bit. 

#### What is the expected behavior?
Clicking on a disabled checkbox should not change it in any way. 

#### What is the current behavior?
Clicking on a disabled checkbox adds a disabled class to the <input> within it. 

#### What are the steps to reproduce?
<mat-checkbox [disabled]=someMethodCall()/>

set someMethodCall to return true,
click on mat-checkbox, 
set someMethodCall to return false,
click on mat-checkbox (this will be disabled)

**Comment by tinayuangao** [comment]
Close this issue since it's a general problem with NgUpgrade that would affect its ability to interact with any OnPush component (by Karl). 
There's a pr by @smdunn in angular repo to fix it https://github.com/angular/angular/pull/22209
