### ISSUE TITLE
Slide Toggle Doesn't Seem to be working in Alpha 7  Error: Cannot find name 'HammerInput'

### ISSUE THREAD

**Issue by naveedahmed1** [angular/material2#977]
HI,

I just upgraded to Alpha 7 and after upgrade Slide Toggle seems to be broken.

When I compile my project in Visual Studio 2015 I receive the below errors:

```
Error		Build:Cannot find name 'HammerInput'.	node_modules\@angular2-material\slide-toggle\slide-toggle.d.ts	67	

Error	TS2304	Cannot find name 'HammerInput'.	TypeScript Virtual Projects	node_modules\@angular2-material\slide-toggle\slide-toggle.d.ts	67
```

Apparently it seems that the below line is causing the problem in slide-toggle.d.ts:

`_onDrag(event: HammerInput): void;`

**Comment by DevVersion** [comment]
I guess you didn't install the typings for `HammerJS`?

> https://github.com/angular/material2/blob/master/GETTING_STARTED.md#additional-setup-for-md-slide-toggle-and-md-slider

`typings i dt~hammerjs --global --save`

**Comment by adrm** [comment]
Install hammerjs and its typings. With alpha7, angular2 rc5, typescript 2.0 and webpack (through angular-cli) this worked for me:

```
npm install --save hammerjs @types/hammerjs
```

And then `import 'hammerjs'` in your main component.

**Comment by jelbourn** [comment]
@naveedahmed1 installing the typings for HammerJS should resolve this.

**Comment by naveedahmed1** [comment]
Thank you everyone installing typings through command:

`npm install --save hammerjs @types/hammerjs `

and then importing it in main file solved the issue.:

`/// <reference path="../typings/globals/hammerjs/index.d.ts" />`

**Comment by ctkdev** [comment]
For those finding this issue that have a similar configuration to mine: 
angular-material: 2.0.0-alpha.7-3
angular-cli: 1.0.0-beta.11-webpack.2

Just doing the following: 
$ npm install --save hammerjs @types/hammerjs

Was all that was needed. Since my tsconfig.json file contains this line: 
`
    "typeRoots": [
      "../node_modules/@types"
    ]
`

I did not have to make any changes to main.ts

**Comment by uncledlm** [comment]
In addition to ctkdev's solution I had to add hammerjs to the "types" section in tsconfig.json

"types": [
      "jasmine", "hammerjs"
    ]

**Comment by Kosmonaft** [comment]
I had to use @ctkdev and @uncledlm solutions.
Now everything is working fine :+1:

**Comment by vapits** [comment]
Guys,
the combination of the above solutions solved for me the Webpack errors in the compiler but the template is still not working with the `md-slide-toggle` for me.

I'm getting this:
![image](https://cloud.githubusercontent.com/assets/8594758/17774641/d092be3c-6554-11e6-9892-a761266b9386.png)

My template is this:
```
<md-slide-toggle
   [checked]="activeApp?.running">
</md-slide-toggle>
```
I had even try like this:
```
<md-slide-toggle
   [checked]="true">
</md-slide-toggle>
```

Any other ideas?

Angular version: RC5
Material version: `alpha.7-4`

**Comment by DevVersion** [comment]
Seems like you didn't load the `HammerJS` library

```ts
import 'hammerjs';
```

or

```html
<script src="./node_modules/hammerjs/hammer.js">
```

**Comment by vapits** [comment]
@DevVersion you're right (sorry I deleted my message by mistake).

**Comment by DevVersion** [comment]
@vapits No worries - glad I could help :)

**Comment by medeirosrich** [comment]
I had to use I had to use @ctkdev and @uncledlm and @DevVersion solutions =D

I did the import in polyfills.ts (using angular-cli webpack)

**Comment by petersgiles** [comment]
Using angular-cli@latest (webpack)

I added hammerjs

`npm install --save hammerjs @types/hammerjs`

then on the last line of `src/polyfills.ts` I added `import 'hammerjs';`

**Comment by whitewaves** [comment]
@ctkdev and @uncledlm solutions worked perfectly

**Comment by aviramga** [comment]
Hi, doing what suggested above this solve the loading issue but now I get a typescript error:
 error TS2300: Duplicate identifier 'TouchAction'

this is just an sample one, I get a lot of those (I assume these are all related to hammerjs) although the app seems to work fine.

Any idea?
Thanks!

**Comment by MikeGitIt** [comment]
Is all of this documented somewhere other than the issues section? Thank God for the internet + googling...yeesh!

**Comment by shaozi** [comment]
This should be included in the getting started guide!
