### ISSUE TITLE
floatLabel property of mat-form-field doesn't work

### ISSUE THREAD

**Issue by inyryaev** [angular/material2#9779]
I use floatLabel property of mat-form-field, but it doesn't work.

```
<mat-form-field [floatLabel]='always'>
        <mat-label>CyberSource Reference</mat-label>
        <input matInput placeholder="(Enter reference)" />
 </mat-form-field>

```

It has 'CyberSource Reference' as placeholder. Then it move to label on focus. Behavior doesn't change with any value of floatLabel property. Any Ideas? MatFormFieldModule is loaded to my app. Thanks.

"@angular/material": "^5.0.4"

**Comment by willshowell** [comment]
This is just a syntax error:

```html
<mat-form-field floatLabel="always">
```
or

```html
<mat-form-field [floatLabel]="'always'">
```

**Comment by inyryaev** [comment]
Yes, it is true, thank you -_-

**Comment by Shalinisingh1007** [comment]
<mat-form-field floatLable="never" style="background: transparent;border: 0px">
                <mat-select style="height: 30px;" (selectionChange)="addMeeting($event)">
                  <mat-option  *ngFor="let smartGroup of smartGroups" [value]="smartGroup.groupId">
                    {{smartGroup.groupName}}
                  </mat-option>
                </mat-select>
                <mat-label class="my-class-name">{{'MeetingArranger.select.a.group' |translate}}</mat-label>
              </mat-form-field>


this is my code.on focus it chages to lable.it is driving me crazy now. acn anyone plaese tell me what am i doing wrong?

**Comment by webwarrior06** [comment]
You saved my hours. Thanks.
