### ISSUE TITLE
No Clear button

### ISSUE THREAD

**Issue by oscarlagatta** [angular/material2#9781]
#### Bug, feature request, or proposal:
Clear button for the Autocomplete Input

#### What is the expected behavior?
when click on the clear button the text is cleared from the input box 

#### What is the current behavior?
none

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
clearing the input box from a previous entered value

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
5.0/5.0/Win/Typescript/Chrome

#### Is there anything else we should know?
no

**Comment by willshowell** [comment]
You can compose one very easily with a `matSuffix` and the icon of your choosing.

**Comment by oscarlagatta** [comment]
Thanks Will
