### ISSUE TITLE
mat-slider crashes chrome DevTools on page reload

### ISSUE THREAD

**Issue by sokolandia** [angular/material2#9784]
#### Bug, feature request, or proposal:
Chrome DevTools performance profiler crashes on reload when mat-slider is present

#### What is the expected behavior?
Profiler report 

#### What is the current behavior?
"DevTools was disconnected from the page" message popups before profiler is finished.

#### What are the steps to reproduce?
1. Go to https://lmgdbmxexpmd.angular.stackblitz.io/
2. Open chrome DevTools
3. Performance tab
4. Ctrl + Shift + E

#### What is the use-case or motivation for changing an existing behavior?
Can't profile my app on page reload

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome

#### Is there anything else we should know?

**Comment by DevVersion** [comment]
I wasn't able to reproduce that issue on my end. Also your StackBlitz link doesn't seem to work?

* I've created one that shows the `<mat-slider>`: https://ngm-issue-9784.stackblitz.io/

![image](https://user-images.githubusercontent.com/4987015/36201333-f34df9f4-117f-11e8-85bc-a03898f23fb7.png)
