### ISSUE TITLE
AOT: Property 'panelOpenState' does not exist on type 'ExpansionPanelComponent'

### ISSUE THREAD

**Issue by momoadeli** [angular/material2#9787]
#### Bug, feature request, or proposal:
"ng build --env dev --aot" gives error:
 Property 'panelOpenState' does not exist on type 'ExpansionPanelComponent'

#### What is the expected behavior?
Build success

#### What is the current behavior?
 Property 'panelOpenState' does not exist on type 'ExpansionPanelComponent'

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current package.json:
    "dependencies": {
        "@angular/animations": "^5.1.3",
        "@angular/cdk": "^5.1.1",
        "@angular/common": "^5.1.2",
        "@angular/compiler": "^5.1.2",
        "@angular/core": "^5.1.2",
        "@angular/forms": "^5.1.2",
        "@angular/http": "^5.1.2",
        "@angular/material": "^5.1.1",
        "@angular/platform-browser": "^5.1.2",
        "@angular/platform-browser-dynamic": "^5.1.2",
        "@angular/router": "^5.1.2",
        "@auth0/angular-jwt": "^1.0.0-beta.9",
        "@ngrx/effects": "^4.1.1",
        "@ngrx/entity": "^4.1.1",
        "@ngrx/router-store": "^4.1.1",
        "@ngrx/store": "^4.1.1",
        "bootstrap": "4.0.0-alpha.6",
        "core-js": "^2.5.3",
        "font-awesome": "^4.7.0",
        "lodash": "^4.17.4",
        "rxjs": "^5.5.6",
        "zone.js": "^0.8.19"
    },
    "devDependencies": {
        "@angular/cli": "^1.6.7",
        "@angular/compiler-cli": "^5.1.2",
        "@angular/language-service": "^5.1.2",
        "@compodoc/compodoc": "^1.0.5",
        "@ngrx/store-devtools": "^4.1.1",
        "@types/jasmine": "~2.5.53",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "^6.0.95",
        "angular-in-memory-web-api": "^0.5.2",
        "codelyzer": "~3.2.0",
        "commitizen": "^2.9.6",
        "cz-conventional-changelog": "^2.1.0",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.3.3",
        "karma-jasmine": "^1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.1.2",
        "ts-node": "~3.2.0",
        "tslint": "~5.7.0",
        "typescript": "~2.4.2"
    },

#### Is there anything else we should know?
- I've clean uninstalled an re-installed cli, material, and cdk.

**Comment by crisbeto** [comment]
It seems like the only mention of that property is in one of our examples. Are you sure that it's not something that is missing in your code?

**Comment by momoadeli** [comment]
Yep, that was it... @crisbeto many thanks.  This issue can be closed.

**Comment by AlbertoBonfiglio** [comment]
@momoadeli Care to share what it was? I am having the same issue...
