### ISSUE TITLE
Some publicly available mixins missing from latest Material version

### ISSUE THREAD

**Issue by irackley-mc** [angular/material2#9790]
#### Bug, feature request, or proposal:
When upgrading from Material 5.1.0 to 5.1.1, mixins such as `mat-menu-base` which were being used before are now missing, with no mention in the change log.

#### What is the expected behavior?
Importing the styles for material would include the mixins previously available.

#### What is the current behavior?
Errors are thrown as the mixin `mat-menu-base` are not known to the product.

#### What is the use-case or motivation for changing an existing behavior?
Currently I use this to borrow same styling for custom menus using the cdk while sharing the same look as the material library.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

`@angular/material@5.1.1`

#### Is there anything else we should know?

This might be intended, but it was not listed anywhere in the change log.

**Comment by crisbeto** [comment]
I don't think those mixins have been moved for a while, but the build may have changed since then.

**Comment by irackley-mc** [comment]
Yeah, I had to install 5.1.0 vs 5.1.1 and noticed that in _theming.scss, the mixin was randomly missing. Both my coworker and I ran into it due to this, so i'm guessing the build may have changed how it is importing them. Are they meant to be in there still?

**Comment by jelbourn** [comment]
Those sass mixins aren't meant to be public APIs (they're totally undocumented). Only the theming, elevation, and typography mixins (which are all documented in guides) are meant for public consumptions
