### ISSUE TITLE
Explore the impact of using SCSS @extend vs @include

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#98]
See: 
- http://csswizardry.com/2016/02/mixins-better-for-performance/
- https://tech.bellycard.com/blog/sass-mixins-vs-extends-the-data/
- [ ] Explore payload size
- [ ] Explore runtime impact

**Comment by david-gang** [comment]
I am curious of how the runtime impact will be measured. Is there any tool which will be used? Which application will be measured?

**Comment by sendilkumarn** [comment]
looks interesting. IMO it should be mixins. But upon reading both links want to try out which suits better.
[CSS Performance](https://chrome.google.com/webstore/detail/css-perf/cpaaeoeccmaoonojebkcdnppdhmilhhh)
[Performance Booklet](https://github.com/micmro/performance-bookmarklet)
I think this two tools and  Chrome Dev tools are enough to validate or is there any other plugin that can be used?

**Comment by jelbourn** [comment]
@sendilkumarn Chrome tools would be a good starting point, but looking at other browsers would also be important.

**Comment by sendilkumarn** [comment]
On an average for `cards` screen alone

Payload  - extend  2.0kb  /  mixin 1.7kb
Painting - extend 1.96 / mixin 2.54  [ average of 10 times ] 
DOM content load time - extend 854ms  / mixin 803ms
