### ISSUE TITLE
Evaluating tooltip error

### ISSUE THREAD

**Issue by maryamsoprano** [angular/material2#980]
I have installed @angular2-material/tooltips now. and when I wanted to import and use it in my componnent I got following error

Error: (SystemJS) MdTooltipModule<@http://localhost:3000/node_modules/@angular2-material/tooltip/tooltip.js:205:1
	@http://localhost:3000/node_modules/@angular2-material/tooltip/tooltip.js:201:24
	@http://localhost:3000/node_modules/@angular2-material/tooltip/tooltip.js:1:1
	@http://localhost:3000/node_modules/@angular2-material/tooltip/tooltip.js:1:1
	Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:323:20
	Zone</Zone</Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:216:25
	scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:571:53
	Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:356:24
	Zone</Zone</Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:256:29
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:474:26
	ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:426:22
	
	Evaluating http://localhost:3000/node_modules/@angular2-material/tooltip/tooltip.js
	Error loading http://localhost:3000/app/main.js

What shall I do to solve this error?

**Comment by jelbourn** [comment]
If the other components are loading correctly, this is likely a problem in the configuration of your module loader (SystemJS).
