### ISSUE TITLE
Mat Menu is broken

### ISSUE THREAD

**Issue by insane07** [angular/material2#9800]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Mat Menu is not opening on Menu Menu Trigger open menu.

#### What is the current behavior?
It breaks in 5.2.0 release

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
Just update angular/material dependency to latest version or 5.2.0.It will break.
Use Mat menu. Once you click on a button that triigers mat-menu it will throw an exception that certain method is not a function.(ERROR TypeError: this._keyManager.setFocusOrigin is not a function
    at MatMenu.focusFirstItem)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 5.2.0

**Comment by adgoncal** [comment]
It is working for me: https://stackblitz.com/edit/angular-bhxqj6

**Comment by insane07** [comment]
Can you check this. [](https://stackblitz.com/angular/oaqapeegmox)

**Comment by insane07** [comment]
Can you check this. [https://stackblitz.com/angular/oaqapeegmox](url). It's the same code from angular/ material examples, but i have updated the angular/material dependency to 5.2.0.

**Comment by insane07** [comment]
Thanks adgoncal. got the problem. Need to update the angular/cdk dependency to 5.2.0 too. Its working now.
