### ISSUE TITLE
Bug: multi-year doesn't seem to work.

### ISSUE THREAD

**Issue by Necromancerx** [angular/material2#9802]
#### Bug:
`startview="multi-year"` doesn't seem to work.

#### What is the expected behavior? 
It should show this view.
<img width="306" alt="screen shot 2018-02-06 at 9 21 22 pm" src="https://user-images.githubusercontent.com/2461985/35861705-d2bde8e0-0b83-11e8-8f14-832ef6b6b0f3.png">

#### What is the current behavior?
It doesn't show `next-year` view. Only `year` and `month` works.

#### What are the steps to reproduce?
Check this out. https://nkdqyoedegg.angular.stackblitz.io.

But in [here](https://material.angular.io/components/datepicker/overview#setting-the-selected-date), it works.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material Version: `@angular/material": "^5.0.0-rc0`

**Comment by julianobrasil** [comment]
Which versions are you exactly working with? The stackblitz link you've provided seems to be broken

**Comment by Necromancerx** [comment]
**Solved**

Update Material version to 5.2.0
`"@angular/material": "^5.2.0"`
