### ISSUE TITLE
Mat Drawer in unopened Mat Tab

### ISSUE THREAD

**Issue by Marfyy** [angular/material2#9804]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Drawer in unopened tab should start in a opened state. 

#### What is the current behavior?
Drawer in the second tab is graphically closed on start.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-17trxk?file=app%2Fapp.component.html

Navigate to Tab 2, and graphically, the drawer is closed. When you click the toggle button, it sort of closes it again. It seems to work as expected from then on. It feels like the model for the state is correct, but the UI does not draw correctly.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
This is reproducable on the stackblitz, so whatever versions are there.

My versions:
Angular: 5.2.0
Material: 5.1.0
OS: Windows 10 x64
Typescript: 2.4.2
Browsers: Chrome, IE11 and Firefox have the same behavior.

**Comment by julianobrasil** [comment]
This is likely to be solved when PR #8921 is merged.

**Comment by josephperrott** [comment]
Closing  as this was addressed by #8921
