### ISSUE TITLE
What is the right way to make responsive layout?

### ISSUE THREAD

**Issue by sunshineo** [angular/material2#981]
#### Bug, feature request, or proposal:
Question

#### What is the expected behavior?
I have a bunch of md-card under md-content. I used to use ng2-material
```
<md-content class="md-padding" layout="row" layout-wrap>
    <md-card *ngFor="let restaurant of restaurants" flex-gt-md="45" flex-md="100" flex-sm="100" flex-xs="100">
        <restaurant-card [restaurant]="restaurant"></restaurant-card>
    </md-card>
</md-content>
```
They used to have multiple cards on one row when screen is wide because of the flex settings. Now I changed to use angular2-material directly, these flex settings no longer works.

How should I manage the responsive layouts now? Thank you very much!

**Comment by bennycooly** [comment]
Check out [md-grid-list](https://github.com/angular/material2/tree/master/src/components/grid-list). You can arrange each md-card inside an md-grid-tile.

**Comment by jelbourn** [comment]
GitHub issues are only for bugs, feature requests, and proposals. Please direct questions to mailing lists, StackOverflow, gitter, etc.

**Comment by sunshineo** [comment]
@jelbourn Thank you. It could be that the flex support was broken though, right? ;)

**Comment by sunshineo** [comment]
And specially thank you @bennycooly

**Comment by sunshineo** [comment]
Hi @bennycooly , the md-grid-list does not work for me since it is not dynamic/responsive :(
