### ISSUE TITLE
Mat-Vertical-Stepper incompatible with Mat-Tab

### ISSUE THREAD

**Issue by NickJohn547745** [angular/material2#9814]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
In a Mat-Vertical-Stepper, by default only the active step should be expanded.

#### What is the current behavior?
In my Mat-Vertical-Stepper by default every step is expanded. It seems that this issue is only when I have the Mat-Vertical-Stepper as a child to a Mat-Tab.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-t4bexd

#### What is the use-case or motivation for changing an existing behavior?
I need the space in my registration form to be as small as possible. I'd rather not have too much to overflow onto a scroll area.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.6.7
Node: 9.5.0
OS: win32 x64
Angular: 5.2.3
Chrome Browser

#### Is there anything else we should know?
No

**Comment by julianobrasil** [comment]
This is likely to be solved when PR #8921 is merged.

**Comment by josephperrott** [comment]
Closing as this was addressed by #8921
