### ISSUE TITLE
Date picker RTL support

### ISSUE THREAD

**Issue by MurhafSousli** [angular/material2#9817]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

RTL support

![image](https://user-images.githubusercontent.com/8130692/35895942-d0d78d46-0bca-11e8-8a43-84d83c4fcb94.png)

#### What is the current behavior?

![image](https://user-images.githubusercontent.com/8130692/35895979-063f19b8-0bcb-11e8-85a9-9788bf4789b4.png)

#### What is the use-case or motivation for changing an existing behavior?

It should look properly when `dir="rtl"` is set on the body element

#### Steps to reproduce

Add `dir="rtl"` to body element

<body dir="rtl">
</body>

#### Is there anything else we should know?

I was able to get the right look by adding `dir="rtl"` directly on the date picker element

**Comment by crisbeto** [comment]
From some quick testing it works for me. Are you adding/changing the `dir` dynamically after the datepicker has been created?

**Comment by MurhafSousli** [comment]
@crisbeto No, I sat it in the body in `index.html`

**Comment by MurhafSousli** [comment]
I don't think I can reproduce it in a stackblitz because it doesn't have index.html, so I made this [repo](https://github.com/MurhafSousli/material-datepicker-issue) (sorry I just pushed the project as it is) but it is straightforward. the date picker is defined in this [file](https://github.com/MurhafSousli/material-datepicker-issue/blob/master/src/app/home/excel-serach/excel-search.component.html#L9)

Click on "file" button to see the date picker
![image](https://user-images.githubusercontent.com/8130692/36273267-06b034a6-1295-11e8-956a-e9e4ac756cce.png)

**Comment by crisbeto** [comment]
Thanks, I see what you mean now. The issue comes from the fact that when Material opens an overlay (in your case a dialog and a datepicker), it defaults to the direction being `ltr`, unless you've passed in something different. I've submitted a PR that will default to the direction from the body, but until it gets released you can fix your issue by setting the `direction` explicitly in your dialog config:

```ts
dialog.open(DialogComponent, {
  direction: 'rtl'
  // some other dialog configuration...
});
```

**Comment by MurhafSousli** [comment]
@crisbeto Great! Thank you.
