### ISSUE TITLE
Material cards to support header with different background-color than body

### ISSUE THREAD

**Issue by walhow** [angular/material2#9829]
#### Bug, feature request, or proposal:
Proposal: support different background-color for Card header than body

#### What is the expected behavior?
Background color on card-header would be different than card body.

#### What is the current behavior?
Cards (and material in general?) seem to only support headers with same background-color as body.

#### What are the steps to reproduce?
Look at card sample on angular.material.io/.../card.
<img width="663" alt="material_card_site" src="https://user-images.githubusercontent.com/5958378/35935126-84f2669c-0c0d-11e8-954b-c038524c6b81.PNG">

or look at this blitz:
<img width="756" alt="what_id_like_to_see" src="https://user-images.githubusercontent.com/5958378/35936358-07e1e6ba-0c11-11e8-9311-b79f24a53b72.png">

https://stackblitz.com/edit/angular-mdnzpi

#### What is the use-case or motivation for changing an existing behavior?
Customer wants a different look for material cards (i.e. headers with background color).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Most recent material.

#### Is there anything else we should know?
It's interesting that in the documentation, there is a div with a different colored header (see 'Basic cards' in material_card.png attachment), but then the material component itself ('Simple card') is all (header and body) the same background-color.
<img width="663" alt="material_card_site" src="https://user-images.githubusercontent.com/5958378/35935231-de52d2bc-0c0d-11e8-804c-f82f57d700d8.PNG">

**Comment by donroyco** [comment]
See #9696 and @jelbourn's comment there:

> We don't have any plans to turn this into an API. **You should be able to use CSS to customize the background color**, or SCSS to pull the color from the current theme.

**Comment by josephperrott** [comment]
Closing, as noted above, you are able to set use CSS to customize the background color directly.
