### ISSUE TITLE
sortChange not working 

### ISSUE THREAD

**Issue by truginis** [angular/material2#9830]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
sortChange should fire when sorting table

#### What is the current behavior?
Event not firing.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-mgsj76

#### What is the use-case or motivation for changing an existing behavior?
Would like to hook the sorting event to do server-side sorting

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.0, Angular/Material 5.2.0, TypeScript 2.5.3, OS: High Sierra, Browser: Chrome Version 63.0.3239.132 (Official Build) (64-bit), Latest Firefox, Safari.

**Comment by truginis** [comment]
Looks like it's a documentation problem. 

> ... listen to the sort's (sortChange) event and re-order your data according to the sort state.

Using ```(matSortChange)``` works. Unless i am misunderstanding something here.

**Comment by donroyco** [comment]
@andrewseguin Could you have a look?

**Comment by andrewseguin** [comment]
Yup looks like its just a typo. Thanks for reporting
