### ISSUE TITLE
Expansion panels in tabs not working properly

### ISSUE THREAD

**Issue by trichetriche** [angular/material2#9834]
#### Bug, feature request, or proposal:

**Bug**

#### What is the expected behavior?

When I switch between tabs that both have expansion panels, I want the expansion panels to behave like they would in any other situation.

#### What is the current behavior?

The panels are sort of opened, and their style is messed up : 

![image](https://user-images.githubusercontent.com/7789922/35966399-fab9bab4-0cbd-11e8-8c1d-5ea89fb57ad5.png)

#### What are the steps to reproduce?

**[Stackblitz](https://stackblitz.com/edit/angular-material2-issue-1vt6en?file=app/app.component.html)**

#### Is there anything else we should know?

Unlike #5269 there's no hidden tab. So I think it isn't a duplicate, hence the new issue.

**Comment by tgmendes** [comment]
I have exactly the same problem as you do, and I also have looked at #5269 . The solutions there do apply to our case (you wrap the accordion/expansion panel with an `*ngIf` and only show if the tab is selected. 

This did not work for me.

Here's some screenshots that may help:
**Expected behavior (without tab switching):**
![image](https://user-images.githubusercontent.com/10812871/35971238-2e9be314-0cc5-11e8-8435-b43a42d174ab.png)

**Appearance after switching tabs:**
![image](https://user-images.githubusercontent.com/10812871/35971284-5ee17d4a-0cc5-11e8-8432-3f802d714d63.png)

**Comment by trichetriche** [comment]
If you're looking for a workaround, you can add this : 

     (selectedTabChange)="reloadTabs()"

With a tab condition 

    <mat-tab label="Tab One">
      <ng-container *ngIf="showTabContent">

And it does this 

    reloadTabs() {
      this.showTabContent = false;
      setTimeout(() => this.showTabContent = true, 500);
    }

Works well for me (once I added a fake loading bar and some animation), but still, it's a workaround, and I expect a fix to come soon

**Comment by tgmendes** [comment]
Thanks for the fix @trichetriche . 

I also expect there will be a solution for this.

**Comment by Bmahecha123** [comment]
The only issue I'm finding with this workaround is that the screen will scroll up to line up with the expanded content when you switch tabs.

**Comment by trichetriche** [comment]
Not sure this is related to the workaround since I faced this issue when I discovered material. My solution was to make the content take the whole space anyway, and change its overflow properties

**Comment by josephperrott** [comment]
With the submission of #8921, you should now be able to lazy load the content of the tabs.  With the content of the tabs being lazy loaded, the animations move to the correct state as desired.

**Comment by trichetriche** [comment]
But what if I don't want to lazy load the content of the tabs ? Is it the only solution to this problem ?

**Comment by josephperrott** [comment]
At this point this is the only viable solution we have found as this is actually an issue of animations failing to trigger.

We hope to be able to determine a better solution in the future, but at this point this is the best solution we have found.

**Comment by Yaseen-Nadaf** [comment]
@trichetriche The solution given is not working for me.

My Problem:
When I change the tab to second one, expansion-panel's header is taking large height than necessary and arrow is down as if content is closed but content is visible. Same case with all expansion-panels headers and content in the second tab.

**Comment by trichetriche** [comment]
That's the exact same issue I have reported and I gave a workaround around that, that worked for me (and still works as of today). 

If you have an issue, then provide a sandbox to show it, like you would open a question. In fact, if you think your problem is different, you should maybe open a question.

**Comment by trichetriche** [comment]
I don't really care about your code ... That doesn't show me the issue you're facing, and that doesn't show me if you tried the workaround I gave. And honestly, i didn't even read it, there's like 200 lines of your code that doesn't interest me, I've already got my answer, and that's a ticket for an issue, not for calling help. 

So unless you provide a sandbox to test it, I won't be willing to help you, sorry.

**Comment by Yaseen-Nadaf** [comment]
I can understand, well right now I can't reveal the real code and show you
the exact issue I am facing via sandbox. You too don't have time and
unfortunately me too. I hoped you would be able recreate the issue with
that code and help me. Anyways thank you for your words.

**Comment by YajneshRai** [comment]
I too faced this issue. A big thanks to @trichetriche for the work around! Made my life easier.

**Comment by nickkhan** [comment]
issue is still there even, 
[https://github.com/angular/material2/issues/5269](url)

**Comment by trichetriche** [comment]
Your link is dead and we are aware the issue is still there. As said before, it won't be corrected, but there is 2 workarounds for it.

**Comment by Yaseen-Nadaf** [comment]
May be those 2 workarounds doesn't work for everyone. If it is in material
and is public to use then it should be developed in such a way that
everybody can use it without any issue.



*Thanks & Regards*
Yaseen Nadaf
Full Stack Web Developer

**Comment by trichetriche** [comment]
The purpose of a workaround is to work. If it doesn't, that's not a workaround, it's a bug ... 

And in case you're not aware, devs can face limitations. If you cared to read the whole thread you would have seen that it is the case there. 

And again, read the thread to answer your second question.

**Comment by nickkhan** [comment]
@trichetriche I re-pasted the link. Workarounds take additional time to implement and cost dev time, I rather not be spending time implementing a workaround, therefore it should be fixed. either ways the workaround does work.

**Comment by nategurian** [comment]
@trichetriche  Workaround works great. Thanks! Took no time at all to implement and works as expected

**Comment by coaxfiber** [comment]
put selectedtabchange in mat tab group
"<mat-tab-group (selectedTabChange)="tabClick($event)">"
![image](https://user-images.githubusercontent.com/25381237/57202741-7dc38f80-6fdb-11e9-9861-e02af92d6135.png)

create a variable and the function
![image](https://user-images.githubusercontent.com/25381237/57202730-64bade80-6fdb-11e9-8fd6-448f50e5747d.png)

then put the ng if in accordion elements for each tab
![image](https://user-images.githubusercontent.com/25381237/57202764-c3805800-6fdb-11e9-87f0-30d5891d34fd.png)
