### ISSUE TITLE
Can't clean the data from the autocomplete 

### ISSUE THREAD

**Issue by oscarlagatta** [angular/material2#9835]
#### Bug, feature request, or proposal:
Can't clean the data from the autocomplete 
#### What is the expected behavior?
remove the items from the autocomplete list

#### What is the current behavior?
none

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
when clicking a button the items in the list of the autocomplete need to be removed

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5 and Material 5

#### Is there anything else we should know?
no

**Comment by crisbeto** [comment]
Since rendering the options in an autocomplete is left to the consumer, it's up to you to decide when they'll be removed.
