### ISSUE TITLE
make MatSelectChange more compliant with ControlValueAccessor

### ISSUE THREAD

**Issue by merlosy** [angular/material2#9836]
#### Bug, feature request, or proposal:

I have a custom MatFormField that also implements ControlValueAccessor, with a mat-select component inside.
Considering the ControlValueAccessor interface [docs](https://angular.io/api/forms/ControlValueAccessor)

```ts
host: {
   (change): '_onChange($event.target.value)'
}
```
as regards to [MatSelectChange class](https://github.com/angular/material2/blob/5.2.0/src/lib/select/select.ts#L151) :
```ts
/** Change event object that is emitted when the select value has changed. */
export class MatSelectChange {
  constructor(
    /** Reference to the select that emitted the change event. */
    public source: MatSelect,
    /** Current value of the select that emitted the event. */
    public value: any) { }
}
```
I think there is a mismatch...

#### What is the expected behavior?

It could be great just being able to use:
```ts
@HostListener('change', ['$event']) changed(event) {
    this._onChange(event.target.value);
}
```
OR
```ts
host: {
   (change): '_onChange($event.target.value)'
}
```

#### What is the current behavior?

Currently, my code looks like this:
```ts
@HostListener('change', ['$event']) changed(event) {
    if (event instanceof MatSelectChange) {
        this._onChange(event.value);
    } else {
        this._onChange(event.target.value);
    }
}
```

#### What is the use-case or motivation for changing an existing behavior?

I believe it could be more generic, and could be backward compatible like:
```ts
export interface MatChange {
    public target : { value: any };
}

export class MatSelectChange implements MatChange {
    constructor(
        /** Reference to the select that emitted the change event. */
        public source: MatSelect,
        /** Current value of the select that emitted the event. */
        value: any) { 
        this.target.value = value;
    }

    get value(): any { return this.target.value; }
}
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5.2.0
Angular Material 5.0.4

#### Is there anything else we should know?

I didn't dig that much, maybe there is a reason for the current code style that I don't know about (yet?)

**Comment by crisbeto** [comment]
The main intention with `MatSelectChange` was for it to be consistent with all the other change events we have around the library. You should be able to use the `valueChange` event which will only emit the value. It isn't documented, because we're using it primarily to facilitate the two-way binding on the `value`.
