### ISSUE TITLE
mat dialog actions hiding/overflow

### ISSUE THREAD

**Issue by rvoltolini** [angular/material2#9840]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Show all mat dialog action

#### What is the current behavior?
the resizing of the window is hiding the mat dialog action

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Google Chrome Versão 64.0.3282.140 (Versão oficial) 64 bits
TypeScript 2.6.2
Ubuntu 16.04
Material 5.1.0
Angular 5.1.0

![captura de tela de 2018-02-08 09-32-56](https://user-images.githubusercontent.com/30928235/35971510-5c996ce2-0cb5-11e8-9f51-2e0c52d179e6.png)

**Comment by crisbeto** [comment]
I believe that this is an issue with how we handle the dialogs hitting the bottom of the viewport in general. It should be addressed by https://github.com/angular/material2/pull/9236.

**Comment by crisbeto** [comment]
Closing since there are a few other issues tracking the same thing (#2481, #3239, #6584, #8493).
