### ISSUE TITLE
[button] mat-icon-button icon is not inside the button

### ISSUE THREAD

**Issue by muehan** [angular/material2#9842]
#### What is the expected behavior?
have the Icon button as documented: https://material.angular.io/components/button/examples

#### What is the current behavior?
Icon is somewhere but not where the button is:
![image](https://user-images.githubusercontent.com/1043865/35975221-3f43023a-0cdc-11e8-8fb0-a9e7d2f0f76b.png)

#### What are the steps to reproduce?
Add and open following dialog:
```
<mat-dialog-actions>
  <div class="button-row">
    <button mat-icon-button>
      <mat-icon>arrow back</mat-icon>
    </button>
    <button mat-icon-button>
      <mat-icon>arrow forward</mat-icon>
    </button>
  </div>
</mat-dialog-actions>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
  "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
```

**Comment by muehan** [comment]
ok now I know the problem is the arrow icon

**Comment by muehan** [comment]
if you use:
`<i class="material-icons">arrow_back</i>`
instead of:
`<mat-icon>arrow back</mat-icon>`
it works as expected, but i guess that's not how it should be

**Comment by julianobrasil** [comment]
It's working fine here.

I think the problem is you miss the underscore: it's `arrow_forward` instead of `arrow forward`:

![image](https://user-images.githubusercontent.com/25405143/35978694-9674372c-0ccd-11e8-87a2-1ce5864f287d.png)

**Comment by DevVersion** [comment]
That's the intended behavior. The underscores are necessary to properly reference the icon from the Material Design Icons font _(font ligatures)_ That's nothing we can change here.

![image](https://user-images.githubusercontent.com/4987015/36061619-a70ef334-0e5c-11e8-81d7-b33d16c6bfda.png)

**Comment by muehan** [comment]
I have never talked about the underscore, but thanks anyway.

Today in the material2 demo-app and my own app the arrow icons work as expected!
I guess Chrome just needed a reboot! sorry for wasting your time.
