### ISSUE TITLE
material.angular.io url bug

### ISSUE THREAD

**Issue by anokori** [angular/material2#9848]
#### Bug, feature request, or proposal:
material.angular.io url bug

#### What is the expected behavior?
working cdk url routing

#### What is the current behavior?
not working cdk url routing after navigating component by the left sidenav interaction

#### What are the steps to reproduce?
- goto material.angular.io
- click component on the toolbar
- click one of the submenu on the left sidenav navigation (ex: form controls > autocomplete)
- then click cdk menu on the toolbar

#### What is the use-case or motivation for changing an existing behavior?
- bug reporting

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- browser: chrome, canary, firefox, edge

#### Is there anything else we should know?
none

**Comment by donroyco** [comment]
Looks more like an issue for https://github.com/angular/material.angular.io

**Comment by anokori** [comment]
oops, dunno there's its repo
