### ISSUE TITLE
update for angular rc5

### ISSUE THREAD

**Issue by apimobi** [angular/material2#985]
#### Bug
UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.5
UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.5
UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.5

I can't install with npm with angular rc5
Please update the package.json to allow it

**Comment by jelbourn** [comment]
All of our versions have been updated to RC5. This is likely an issue with your environment.
