### ISSUE TITLE
20180-02-08 all https://stackblitz.com/angular/** fail. There is compile error

### ISSUE THREAD

**Issue by jefhu** [angular/material2#9852]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Sample to work

#### What is the current behavior?
/turbo_modules/@angular/compiler@5.2.4/bundles/compiler.umd.js:
Unexpected value 'undefined' exported by the module 'DemoMaterialModule'
Evaluating main.ts
Loading blitzapp (528:34)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/angular/anynvkxryaj shows error

#### What is the use-case or motivation for changing an existing behavior?
try to see sample code

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5?

**Comment by CaerusKaru** [comment]
Bump the deps for Material and CDK to latest. This should fix the issue.

**Comment by andrewseguin** [comment]
Deps are out of date

https://stackblitz.com/angular/dmmqxmvvxyo
