### ISSUE TITLE
infinite scroll for material table (cdk table)

### ISSUE THREAD

**Issue by TripleMap** [angular/material2#9858]
#### feature request:
Does anybody implements infinite scroll to material/cdk table?

#### What is the expected behavior?
infinite scroll

#### What is the current behavior?
just update on data change event.

#### What is the use-case or motivation for changing an existing behavior?
I have more than 10 000 rows. Of course I can use pagination, but it will be much more representative and useful without paginator. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 5.0.0
material 5.2.0

I have tried to add some new logic to table method renderRows(). It render some rows at specific place by currentIndex. But it looks like big crutch =(

**Comment by andrewseguin** [comment]
Here's a primitive and inefficient prototype that you can use to learn more about how to create an infinite list of rows:

https://stackblitz.com/edit/angular-1vg9gn?file=app/table-basic-example.ts

On the scroll event, see if the user is seeing a row within 200px of the bottom of the table. If so, add more data to the table's data source.

First step in optimizing this would be to debounce the scroll events since doing this calculation on every scroll event will bog down performance.

**Comment by TheHanna** [comment]
@TripleMap I built upon @andrewseguin's solution, creating a container that throttles and emits a scroll event while there is more data to load:

https://stackblitz.com/edit/angular-material-data-table-infinite-scroll

I'm using lodash to throttle the scroll event and dynamically assigning a scroll handler to either the host element or the window, based on the element's clientHeight/scrollHeight. This solution works for my use cases, YMMV

**Comment by jacobbowdoin** [comment]
@naveedahmed1 Would you mind posting a link to your cdk-virtual-scroll + material table solution? I'd love to use both of those together as well!

**Comment by Hintalo** [comment]
@naveedahmed1 I know it is a bit late, but maybe this helps you.
I've tried the recommended optimization (using debounceTime() at the event subscription) with a mat-table element and it works for me. It is important to setup the subscription in the ngAfterViewInit() method, and that you use the "{read: ElementRef}" option at the @ViewChild-decorated class-variable (that points to the physical table element), i.e.
`@ViewChild('table', {read: ElementRef}) public matTableRef: ElementRef;`

See my demo here:
[https://stackblitz.com/edit/mat-table-infinite-scroll](https://stackblitz.com/edit/mat-table-infinite-scroll)

Note: this snipplet demonstrates a very simple bidirectional infinite-scrolling, with a simple memory-preserving array storage, At scrolling, we "load" three virtual pages (with fake data), each of them contains 50 items. Then we re-fill the same array at the next scroll-event.

**Comment by lockee14** [comment]
I don't know if it can help but here is my solution:
https://stackblitz.com/edit/angular-mat-table-infinite-scroll-with-sort?file=src%2Fapp%2Fapp.component.ts

No use of cdk virtual scroll just mat-table, data can also be sorted.
