### ISSUE TITLE
Multiple stackable snackbars

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [angular/material2#9860]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Multiple stackable snackbars. Whenever a snackbar would be dismissed, the next snackbar should move to the next available position. 

#### What is the current behavior?
Multiple snackbar messages are getting overridden, as stated clearly by the documentation: "Only one snack-bar can ever be opened at one time".

#### What are the steps to reproduce?
n/a

#### What is the use-case or motivation for changing an existing behavior?
With an application loading multiple things in parallel, I have the need for a component that allows to feedback multiple messages. For example, whenever you deeplink a page that both loads (base) information as well as submits information, there's a need to show an error message (i.e. 'failed to load data') as well as show a validation message. This requires 2 different snackbar-like elements, with potential different colors, status indicators, etc. 
I'd fully agree that this is not ideal from a UI perspective, and whenever possible we should group messages and potentially link to another place where more details can be found. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

#### Is there anything else we should know?
Happy to get some input on how others fixed this. If there's an alternative UI pattern (available or on the roadmap), let me know.

**Comment by josephperrott** [comment]
Closing as this is not something we plan to do as it is explicitly stated in the Material Spec as something not do for usability reasons.

1.   From the material spec:
> For usability reasons, snackbars should not contain the only way to access a core use case. They should not be persistent or **be stacked**, as they are above other elements on screen.

**Comment by invingagan1** [comment]
What should be the other solution? I wan to achieve UX like mac or windows notification center

**Comment by muchael** [comment]
> What should be the other solution? I want to achieve UX like mac or windows notification center
Based on the material guideline:
"When multiple snackbar updates are necessary, they should appear one at a time."

**Comment by kamekaioken** [comment]
> What should be the other solution? I want to achieve UX like mac or windows notification center

I think you would need to log the messages shown in the snackbar in another component or service. That component could be a stack of mat-cards showing the previous snackbar messages.
Therefor you need to make the messages persistent in your backend or in your frontend if just needed for a single session.

**Comment by kgrosvenor** [comment]
I reckon it would be far more usable if they could be stacked to be honest, say i have a notification for one action, then a real time notification comes in, it dismisses the old snack bar and replaces it with the new one, leaving the user not much time to react to the previous snack bar.  This is a reason to stack them.

**Comment by Benneee** [comment]
> > What should be the other solution? I want to achieve UX like mac or windows notification center
> 
> I think you would need to log the messages shown in the snackbar in another component or service. That component could be a stack of mat-cards showing the previous snackbar messages.
> Therefor you need to make the messages persistent in your backend or in your frontend if just needed for a single session.

This does make sense though. Simulating this using the local storage should not be a bad idea, persisting the data in the front-end, in this case.

**Comment by omaracrystal** [comment]
So the way I was able to do this (even though angular doesn't allow) is to pass an array of data to the component, and display the toasts on top of each other that way. The user needs to take action to close one out and the #of toasts is being tracked in the component. Once there is only one left to close that's when I dismiss the snackbar. I target the snackbar and get rid of the styling and apply it to the component instead. The main caveat is if I have to display the 2nd toast while the 1st one is currently being shown - the 1st toast will reload because the 2nd toast needs to be shown. 

results:
![Screen Shot 2019-06-13 at 3 10 19 PM](https://user-images.githubusercontent.com/11908147/59467718-98183680-8ded-11e9-8ba4-ca2cb9460119.png)


toast.service.ts
```
notifyNumber(numberOfReports: number, numberOfTickets: number) {
    this.snackbar.openFromComponent(ToastNotificationComponent, {
      duration: 9999999,
      verticalPosition: 'top',
      horizontalPosition: 'right',
      data: [
        {
          notifyNumber: numberOfReports,
          routerLinkUrl: '/reports',
          routerLinkText: 'Go Download Reports',
          message: 'reports are ready to download in the "Reports" section.',
          icon: 'si-document-f',
        },
        {
          notifyNumber: numberOfTickets,
          routerLinkUrl: '/support/tickets',
          routerLinkText: 'View Tickets',
          message: 'support ticket needs your attention.',
          icon: 'si-document-f', // todo: find correct icon reference
        },
      ],
    });
```

toast.component.ts
```
export class ToastComponent implements OnInit, OnDestroy {
  count = 0;

  constructor(
    public snackbar: MatSnackBar,
    @Inject(MAT_SNACK_BAR_DATA) public data: any,
  ) {}

  ngOnInit() {
    this.getCount();
  }

  getCount() {
    for (let i = 0; i < this.data.length; i++)
      if (this.data[i].notifyNumber > 0) this.count++;
  }

  close($event: any) {
    this.count = this.count - 1;
    if (this.count >= 1) $event.path[2].hidden = true; // target .toast-notification-component
    if (this.count === 0) this.snackbar.dismiss();
  }

  ngOnDestroy() {
    this.close();
  }
}
```
```
<ng-container *ngFor="let item of data; let i = index">
  <div
    *ngIf="item.notifyNumber > 0"
    class="toast-component"
  >
    <div class="icon">
      <span class="si {{ item?.icon }}"></span>
      <span
        class="notify-number"
        [ngClass]="item?.notifyNumber > 99 ? 'above-99' : ''"
      >
        {{ item?.notifyNumber > 99 ? '99+' : item?.notifyNumber }}
      </span>
    </div>
    <div class="text">
      {{ item?.notifyNumber }}
      {{ item?.message }}
      <br />
      <a [routerLink]="item?.routerLinkUrl" (click)="close()">
        {{ item?.routerLinkText }}
      </a>
    </div>

    <button
      class="close-button"
      (click)="close($event)"
    >
      <span class="si si-x"></span>
    </button>
  </div>
</ng-container>
```
Override Angular Material.scss

```
::ng-deep {
  .mat-snack-bar-container {
    background: transparent !important;
    box-shadow: none !important;
    width: 100%;
    max-width: 500px !important;
  }

  .mat-snack-bar-handset {
    max-width: 500px !important;
  }
}
```
