### ISSUE TITLE
Not able to create any of the given table examples

### ISSUE THREAD

**Issue by Sanafan** [angular/material2#9861]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
No error

#### What is the current behavior?
Many errors

#### What are the steps to reproduce?
This is the code from html/ts/css copied to a stackblitz example, these are exactly the same errors i get inside my local project.

https://stackblitz.com/edit/angular-kgokpx?file=index.html

#### What is the use-case or motivation for changing an existing behavior?
https://material.angular.io/components/table/examples

The given Example doesn't work -> "Data table with sorting, pagination, and filtering.". It won't work if you copy anything and it also doesn't work on the given stackblitz -> https://stackblitz.com/angular/glqjvylkgev

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

#### Is there anything else we should know?
:-(

**Comment by andrewseguin** [comment]
There's a good chance that you are looking at a stale cache of the docs site. We used to use an old aggressive service worker that may still be running on your machine.

Try loading the site after wiping your cache. You should see updated docs.

Here's the actual link to the stackblitz example you are looking for: https://stackblitz.com/angular/jamoradlqber
