### ISSUE TITLE
MatExpansionPanel open animation

### ISSUE THREAD

**Issue by Eja26** [angular/material2#9863]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When the panel is opened, the content should be revealed gradually.

#### What is the current behavior?
Currently, once the opening sequence is initiated, the content is shown immediately, then the animation follows.

#### What are the steps to reproduce?
https://stackblitz.com/angular/pdgrgaapeoo
Just open the expansion panel! If you watch closely you can see it, but here is a screenshot of what is going on right when you click the button:
![25](https://user-images.githubusercontent.com/25012143/36029877-eaa5e8e8-0d9c-11e8-81d6-eb71165f6808.png)

#### What is the use-case or motivation for changing an existing behavior?
Seems to me like this isn't intended behaviour for the animation, if it is, my bad.

**Comment by Triipaxx** [comment]
I got the same issue!
The closing animation is properly clipping the content of the MatExpensionPanel.

**Comment by Eja26** [comment]
Yes, same here. It's something to do with the overflow property of the content.

**Comment by josephperrott** [comment]
This will be fixed by #8820 as it has the same underlying cause as #8754
