### ISSUE TITLE
Feature discussion: should we expose matched breakpoints in BreakpointObserver?

### ISSUE THREAD

**Issue by PascalPrecht** [angular/material2#9867]
#### Bug, feature request, or proposal:
As of today `BreakpointObserver` lets us subscribe to breakpoint changes, which is kind of neat. 

```
breakpointObserver.observer(Breakpoints.Tablet).subscribe(state => {
  // state = { matches: true } if tablet breakpoint
});
```

Sometimes we need to do work when multiple breakpoints match:

```
breakpointObserver.observer([
  Breakpoints.Tablet,
  Breakpoints.Web
]).subscribe(state => {
  // state = { matches: true } if tablet or web breakpoint
});
```
And other times, we need to do different work depending on which breakpoint is activated. However, right now `state` only tells us whether it matches or not. In fact, `breakpointObserver.observe()` will actually only emit when the given breakpoints match, so `state.matches` will always be true.

It would be useful know, **which** of the given breakpoints have matched so we can perform different tasks depending the activated breakpoint:

```
breakpointObserver.observer([
  Breakpoints.Tablet,
  Breakpoints.Web
]).subscribe(state => {
  switch(state.matches) {
    case Breakpoints.Tablet:
      // do something
      break;
    case Breakpoints.Web:
      // do something else
      break;
  }
});
```

Is there anything like that planned or maybe an alternative way I'm not aware of? Otherwise, to me it looks like I need to set up multiple subscriptions for different breakpoints so I can perform different tasks.

This can be easily achieved using `combineLatest` like this:

```
combineLatest(
  breakpointObserver.observe(Breakpoints.Tablet),
  breakpointObserver.observe(Breakpoints.Web)
).subscribe(state => {
  state[0] // is tablet
  state[1] // is web
});
```

**Comment by josephperrott** [comment]
It is definitely possible to provide which `MediaQuery`s are currently matched as we know which queries listeners are triggering their `onchange` method.  However, I don't think that it makes sense to do so.  If different actions should be taken based on which `MediaQuery` is matched, they should be done in separate `observe` calls.  This would correlate to the `combineLatest` that you mention though, I think that it often would make more sense to actually subscribe to each `observe` response individually.

If we split apart which `MediaQuery` is being matched by provided the matched state, it undoes the aggregation the `BreakpointObserver` is providing.  In the `BreakpointObserver` service, a separate stream is set up for each provided `MediaQuery` and then `combineLatest` is used to give the aggregate matched state for all of the streams.  If we provide something to separate them back apart, we are going backwards a bit.


Currently, multiple breakpoints are observed in a single stream
```
Breakpoint1--┐                        
             ├-- BreakpointObserver -- Breakpoint1 OR Breakpoint2 matched
Breakpoint2--┘                        
```

By finding out which is matched, the observation is pulled back apart.
```
Breakpoint1--┐                        ┌ Breakpoint1 matched
             ├-- BreakpointObserver --┤
Breakpoint2--┘                        └ Breakpoint2 matched
```

I think it makes more sense to leave them as separate subscriptions
```
Breakpoint1-- BreakpointObserver -- Breakpoint1 matched

Breakpoint2-- BreakpointObserver -- Breakpoint2 matched
```

**Comment by PascalPrecht** [comment]
Hi @josephperrott 

thank you for getting back to me on this issue.

> In the BreakpointObserver service, a separate stream is set up for each provided MediaQuery and then combineLatest is used to give the aggregate matched state for all of the streams. If we provide something to separate them back apart, we are going backwards a bit.

I think it's great that `BreakpointObserver` already aggregates all the media queries. And I'm not asking to separate them apart. The subscription behaviour would stay the same just that instead of just knowing whether one of the multiple medias have matched, we'd also know which one has matched. 

So all we'd do is passing the information we already have done the line so it's exposed in the consumer facing API.

Obviously, this is mainly a convenience concern as we can always have multiple `observe()` calls. But this will also get unnecessarily wordy, especially if you're dealing with different conditions that apply need to be checked across media matches.

Am I getting this right that

> If we provide something to separate them back apart, we are going backwards a bit.

this is the main reason (also apart from the fact that we wouldn't actually separate again, but just add more information to the existing stream)?

**Comment by josephperrott** [comment]
How would you expect the data to be provided for matches?

I am unsure of how to provide the information about what is and is not matched.  Other than essentially providing what `combineLatest` already does with providing the current state in an array per breakpoint.

**Comment by PascalPrecht** [comment]
> Other than essentially providing what combineLatest already does with providing the current state in an array per breakpoint.

Exactly that. As soon as `BreakpointObserver.observe()` is called with an array, it could use `combineLatest` and emit the data that is needed. Ideally, `state` would not just be an array of emitted { matches: true }` objects, but maybe a hash that provides information about the MatchedMedia a la:

```
state[Breakpoints.Tablet] = { matches: true }
```

So we can do what I've described in the issue.

**Comment by amorenew** [comment]
very important feature.. just Boolean is not enough

**Comment by josephperrott** [comment]
@PascalPrecht In looking at doing this:

How would you feel about:
```ts
export interface BreakpointState {
  /** Whether the breakpoint is currently matching. */
  matches: boolean;
  /** 
   * A key boolean pair for each query provided to the observe method,
   * with its current matched state.
   */
  [key: string]: boolean;
}
```

**Comment by PascalPrecht** [comment]
👍 That would do it

**Comment by CaerusKaru** [comment]
@josephperrott @PascalPrecht I'd like to chime in and say that if we're planning to modify the layout engine, it would be great if we could plan to offload some of the features that are in the Flex Layout library. One of our goals this quarter is to migrate our Media Matcher over to the CDK

**Comment by josephperrott** [comment]
@CaerusKaru For features in `BreakpointObserver`/`MediaMatcher`, can you open up a new issue(s) to track the requests?

**Comment by CaerusKaru** [comment]
Will do, thanks 👍
