### ISSUE TITLE
Angular Material: button stays depressed

### ISSUE THREAD

**Issue by azdanov** [angular/material2#9868]
This behavior occurs when using the button component as a menu indicator for a sidenav.

By choosing a link on the sidenav and going to the chosen route the button in toolbar stays depressed.

While trying to solve this problem I've noticed that button's state goes back to inactive on click, and after route is loaded it becomes depressed.

I've captured this on official Angular Material [docs](https://material.angular.io/components/button/overview).

![feb-09-2018 19-30-52](https://user-images.githubusercontent.com/6123841/36041045-0aa12c42-0dd0-11e8-9826-760a4b236a59.gif)

Is this a bug or intended behavior?

**Comment by willshowell** [comment]
I _think_ this is a duplicate of https://github.com/angular/material2/issues/8420?

**Comment by azdanov** [comment]
It is, thanks.

Closing.
