### ISSUE TITLE
Snackbar appears towards top of window 

### ISSUE THREAD

**Issue by iamwhitebox** [angular/material2#9875]
#### Bug, feature request, or proposal:
Bug, hopefully not a duplicate.

#### What is the expected behavior?
Snackbar appears at bottom of browser window

#### What is the current behavior?
Snackbar appears towards top of browser window

#### What are the steps to reproduce?
Using an external library (Aspera), a success callback is fired upon file upload - which then triggers the snackbar, I am unsure of what would be causing this behavior

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0, Material 2, Mac OS X (Sierra), Typescript, Chrome/Firefox/IE

#### Is there anything else we should know?
<img width="1014" alt="screen shot 2018-02-09 at 4 41 04 pm" src="https://user-images.githubusercontent.com/13710868/36056306-3c3083e2-0db8-11e8-990d-12f53b9ed192.png">

**Comment by julianobrasil** [comment]
It seems to be something with your project setup. Could you reproduce it in stackblitz?

**Comment by iamwhitebox** [comment]
@julianobrasil unfortunately there are too many external components to reproduce in a stackblitz, - another strange thing I noticed, is if the user interacts with any other part of the page , the snackbar will return to the bottom

**Comment by julianobrasil** [comment]
Hum.... Maybe any third party library is messing with snackbar init? Why It would be fixed after interaction? Change detection round?

**Comment by julianobrasil** [comment]
Hum.... Maybe any third party library is messing with snackbar init? Why it would be fixed after interaction? Change detection round?

**Comment by iamwhitebox** [comment]
@julianobrasil Good question, I tried doing a `cdr.detectChanges()`... I will provide update shortly!

**Comment by gjr-qm** [comment]
I had the same thing in a Meteor application. This happens if you are outside of the angular-zone, for example in a callback of an external framework (callback of google-map or meteor.call). You can try a detectChanges with ChangeDetectorRef.

**Comment by julianobrasil** [comment]
If this is a running-out-of-zone issue, you should take a look at #9676 (read it from the begining to the conclusion comment)

**Comment by andrewseguin** [comment]
We'd love to help but without a reproduction case we will be unable to investigate. Please re-open with an example we can look at

**Comment by sagarvasnani** [comment]
The same issue has been experienced by us.

Here's a snapshot:
![snackbarr](https://user-images.githubusercontent.com/23434917/36682552-66c4161e-1b41-11e8-8ae1-255847ee92cc.PNG)

At times, there's just the snackbar at the top and at times it's in both the places. And yes, if the user interacts with any other part of the page, the top snackbar does disappear and the bottom one shows up (if not already visible). In our case, although, the snackbar at the top is empty.

Having studied it's CSS, we see noticed that:
A typical snackbar is rendered in the following way in the DOM:
```
<cdk-overlay-container ...>
    <cdk-global-overlay-wrapper ...>
        <cdk-overlay-* ...>
                <snack-bar...>
                        ...
                <snack-bar/>
        <cdk-overlay-*/>
    <cdk-global-overlay-wrapper/>
<cdk-overlay-container/>
```

But the CSS of the mis-positioned snackbar is not encapsulated within `<cdk-global-overlay-wrapper>` , hence resulting into this behavior.

**Comment by mo2menelzeiny** [comment]
I confirm having the same issue in v5.2.4

**Comment by Charius** [comment]
Got the same issue, but I used workaround with NgZone like [here](https://github.com/angular/material2/issues/9676#issuecomment-361806634)

Something like this

```typescript
// Imports ommited

@Injectable()
export class AppService {
  constructor(private snackBar: MatSnackBar, private zone: NgZone) {}

  public openSnackBar(errorText: string): void {
    this.zone.run(() => {
      const snackBar = this.snackBar.open(errorText, 'OK', {
        verticalPosition: 'bottom',
        horizontalPosition: 'center',
      });
      snackBar.onAction().subscribe(() => {
        snackBar.dismiss();
      })
    });
  }
}
```

**Comment by sagarvasnani** [comment]
**@Charius, that workaround helped!**

**Comment by konsultaner** [comment]
@andrewseguin You should leave that issue open to help people find it. I had the same issue as soon as I initialized my app module like this

```typescript
@NgModule(moduleDefinition)
export class AppModule {
    constructor(logService: LogService, snackBar: MatSnackBar) {
        logService.addLogHandler(new LogSnackHandler(snackBar));
    }
}
```

**Comment by andrewseguin** [comment]
@konsultaner Unfortunately our Github issue tracker is our primary way of seeing which issues need to be resolved. Since there is no action we can perform to resolve this, it needs to remain closed.

If you can provide a stackblitz with reproduction, we can work off that

**Comment by konsultaner** [comment]
@andrewseguin I solved the issue. I was using an external lib that uses when.js that feeds an observable. The problem was that I believed angular would fire a changeCheck if I use Observables by default, but it doesn't. This was the same issue as: https://github.com/angular/material2/issues/10587

**Comment by xandorxicay** [comment]
I had this issue while implementing this with ErrorHandler. After some research Implementing `setTimeout` Resolve this issue for me.
```typescript
  handleError(error) {
    this.ngZone.run(() => {
      setTimeout(() => {
        this.snackBar.open(error, 'ok', {
          duration: 5000,
          verticalPosition: 'top',
          horizontalPosition: 'right'
        });
      }, 0);
    });
  }
```

**Comment by androidovshchik** [comment]
@xandorxicay O_o whats the f*ck... but it works

**Comment by raphael-mueller** [comment]
@xandorxicay Worked for me! Thanks!
