### ISSUE TITLE
docs bug - sidebar / sidenavbar - missing example of toggling open/close

### ISSUE THREAD

**Issue by ORESoftware** [angular/material2#9876]
#### Bug, feature request, or proposal:
I am looking at these docs:
https://material.angular.io/components/sidenav/examples

Currently I am struggling to figure out how to toggle the sidebar open/close. Although I think the docs are wonderul, this particular action seems to be lacking in documentation.

#### What is the expected behavior?
I expected an example of how to toggle the sidebar with a button, for example.

#### What is the current behavior?

I have this:

```html
<mat-sidenav-container>

  <mat-sidenav #sidenav [(opened)]="opened">
    Start
  </mat-sidenav>

  <mat-sidenav-content>
    <div>
      <div fxLayout="row">
          .... my content here
      </div>
    </div>
  </mat-sidenav-content>

</mat-sidenav-container>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All the latest.

**Comment by ORESoftware** [comment]
nvm this should answer my question:
https://stackblitz.com/angular/aalprqrbpdql?file=app%2Fsidenav-open-close-example.html

will close once I figure it out, thx

**Comment by ORESoftware** [comment]
So I got it to toggle, but I have two problems/questions:

1. Currently the content inside <mat-sidenav-content> is not being pushed over, it's just being covered up. I looked at the examples, and it's not clear why the example code works where the content is moved, and why my html does not behave the same.


2. By default, it looks like the content inside <mat-sidebar-content> is darkened/disabled, just like with a modal. I am wondering if I can turn that off in this case.

**Comment by julianobrasil** [comment]
You already have a template reference variable. You can do `sidenav.open()` or `sidenav.close()` anywhere in the template (for example, in the `(click)` event of a button).

**Comment by ORESoftware** [comment]
@julianobrasil yeah thanks, that worked, but sorry I changed the question a little, I put it on SO, but not sure if I can get an answer
https://stackoverflow.com/questions/48716592/material2-navbar-sidebar-misbehaving

**Comment by ORESoftware** [comment]
@Chan4077 hmmm where did I say <mat-navbar-content>? In my SO question?

**Comment by Chan4077** [comment]
@ORESoftware In your comment

**Comment by mmalerba** [comment]
I believe this example demonstrates how to toggle with a button: https://material.angular.io/components/sidenav/overview#opening-and-closing-a-sidenav
