### ISSUE TITLE
select in 5.2.0 gives error withVerticalOrientation is not a function

### ISSUE THREAD

**Issue by dottodot** [angular/material2#9880]
5.1.1 I have no issues with the following

```
        <mat-form-field>
          <mat-select placeholder="Size" formControlName="product_variation" required>
            <mat-option *ngFor="let variation of product.variations" [value]="variation._id">
              {{variation.option_name}}
            </mat-option>
          </mat-select>
        </mat-form-field>
```

but in 5.2.0 i get the following error

> ERROR TypeError: (intermediate value).withTypeAhead(...).withVerticalOrientation is not a function
>     at MatSelect._initKeyManager (select.es5.js:1123)
>     at MatSelect.ngAfterContentInit (select.es5.js:546)
>     at callProviderLifecycles (core.js:12694)
>     at callElementProvidersLifecycles (core.js:12668)
>     at callLifecycleHooksChildrenFirst (core.js:12651)
>     at checkAndUpdateView (core.js:13801)
>     at callViewAction (core.js:14148)
>     at execEmbeddedViewsAction (core.js:14106)
>     at checkAndUpdateView (core.js:13798)
>     at callViewAction (core.js:14148)

**Comment by crisbeto** [comment]
What version of `@angular/cdk` are you using? It has to match the one for `@angular/material`.

**Comment by dottodot** [comment]
Yes sorry hadn't realised that.

**Comment by j2L4e** [comment]
@crisbeto a warning in case of an incompatble cdk version would be ~really~ nice!
