### ISSUE TITLE
overlay attachOverlay function are not the same in SourceCode and NPM downloaded package

### ISSUE THREAD

**Issue by DanielYKPan** [angular/material2#9890]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
I downloaded the zip file from the github, and checkout the _attachOverlay() function in src/cdk/overlay-directives.ts is like this
``` 
private _attachOverlay() {
    if (!this._overlayRef) {
      this._createOverlay();

      this._overlayRef!.keydownEvents().subscribe((event: KeyboardEvent) => {
        if (event.keyCode === ESCAPE) {
          this._detachOverlay();
        }
      });
    } else {
      // Update the overlay size, in case the directive's inputs have changed
      this._overlayRef.updateSize({
        width: this.width,
        minWidth: this.minWidth,
        height: this.height,
        minHeight: this.minHeight,
      });
    }

    this._position.withDirection(this.dir);
    this._overlayRef.setDirection(this.dir);

    if (!this._overlayRef.hasAttached()) {
      this._overlayRef.attach(this._templatePortal);
      this.attach.emit();
    }

    if (this.hasBackdrop) {
      this._backdropSubscription = this._overlayRef.backdropClick().subscribe(() => {
        this.backdropClick.emit();
      });
    }
  }
```
But when I npm install the @angular/cdk package, checkout the _attachOverlay() in cdk/esm2015/overlay.js, the code is like this:
```
_attachOverlay() {
        if (!this._overlayRef) {
            this._createOverlay(); /** @type {?} */
            ((this._overlayRef)).keydownEvents().subscribe((event) => {
                if (event.keyCode === ESCAPE) {
                    this._detachOverlay();
                }
            });
        }
        this._position.withDirection(this.dir);
        this._overlayRef.setDirection(this.dir);
        if (!this._overlayRef.hasAttached()) {
            this._overlayRef.attach(this._templatePortal);
            this.attach.emit();
        }
        if (this.hasBackdrop) {
            this._backdropSubscription = this._overlayRef.backdropClick().subscribe(() => {
                this.backdropClick.emit();
            });
        }
    }
```

As you can see, the else block is missing in the npm downloaded cdk package. This makes the overlay config is not updated when the overlay is re-opened.

This cause a problem:
 I open a select panel and close it, and I resize the windows size, and reopen the select panel. The select panel minWidth doesn't not update.

I checked that the Github zip downloaded cdk version is the same as the npm downloaded cdk version.
Both are 5.2.0

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by CDDelta** [comment]
master includes the latest changes but the version is lnly bumped on a new release.
