### ISSUE TITLE
Proposal(Datepicker): range datepicker

### ISSUE THREAD

**Issue by SaturnTeam** [angular/material2#9896]
Here is the proposal: https://docs.google.com/document/d/14S3BvSm9o8_7VKwJU0ek59V7Cm4Yjt6OOoMj_lpfYZ0/edit?usp=sharing

I don't know much about a11y, so I marked a11y in red. 
Refers to #4763

**Comment by donroyco** [comment]
Why not proceed in the original issue?

**Comment by SaturnTeam** [comment]
@donroyco I do, but no one responded to me for weeks

**Comment by mischkl** [comment]
It would be great if the start and end dates had different colors to tell them apart, particularly for the use case that min or max is set to null.

**Comment by SaturnTeam** [comment]
@mischkl Min and max affects only available dates to select ( for example you can't book a flight for yesterday)

**Comment by mischkl** [comment]
Ah OK, I understand.

Even so it would be useful to be able to tell the two apart, for the situation that either start or end date is left open.

**Comment by jelbourn** [comment]
Dupplicate of #4763
