### ISSUE TITLE
MatPaginator does not work! Selecting table display options.

### ISSUE THREAD

**Issue by Belka383** [angular/material2#9898]
An error occurs:  TS2564: Property 'paginator' has no initializer and is not definitely assigned in the constructor.

Version Angular: 6.0.0.0.beta3, Material Design version 5.2.0, Opera 49.0.2725.64 (PGO)

**Comment by donroyco** [comment]
Please [use the issue template provided](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md) and have a StackBlitz example ready that describes your issue.

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
