### ISSUE TITLE
bug: paginator first-last buttons rendering wrong on load for microsoft edge

### ISSUE THREAD

**Issue by lharries** [angular/material2#9900]
#### Bug, feature request, or proposal:

Bug 

#### What is the expected behavior?

The first and last buttons should render correctly

#### What is the current behavior?

On the page load in Microsoft Edge the buttons appear as below. However, when they are clicked they render correctly.  

![picture of the bug](https://user-images.githubusercontent.com/5085101/35930844-00803706-0c01-11e8-9b76-0fc6cb929e19.png)

#### What are the steps to reproduce?
Visit: https://material.angular.io/components/table/overview#pagination
with Microsoft Edge

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Microsoft Edge and Internet Explorer
Angular Material, Data table, Paginator with First and last buttons

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material2/pull/9776.

**Comment by lharries** [comment]
So it has, great work @crisbeto
