### ISSUE TITLE
material.angular.io: new sidebar broken styles on IE11

### ISSUE THREAD

**Issue by djleonskennedy** [angular/material2#9901]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Should be rendered propertly

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/8366455/36107430-ae63ce30-1022-11e8-883f-91a2b5884c6c.png)

#### What are the steps to reproduce?
https://material.angular.io/components/categories
run on IE 11

#### What is the use-case or motivation for changing an existing behavior?
I've tried to show to potential customer how material works with IE11

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material, angular 5+

#### Is there anything else we should know?
Nope

**Comment by donroyco** [comment]
There is also https://github.com/angular/material.angular.io available, maybe file it there?

**Comment by djleonskennedy** [comment]
@donroyco thank you

Closed due to recreated in proper repo:

https://github.com/angular/material.angular.io/issues/391

**Comment by karlmnz** [comment]
Why are these issues being closed when the material.angular.io site is not working?  Seem you have created cyclic ref. to other closed issues all of which haven't resolved initial issues as per original current behaviour screen shot.  I have just viewed and get the same error.  Then in my angular app getting a whole lot worse.

**Comment by djleonskennedy** [comment]
@karlmnz this issue closed due the fact that the wrong repository for this issue, please see https://github.com/angular/material.angular.io/issues/391
