### ISSUE TITLE
Selecting table display options - MatPaginator does not work! 

### ISSUE THREAD

**Issue by Belka383** [angular/material2#9912]
#### Bug, feature request, or proposal:
BUG! The following code is used:

```ts
import { Component, ViewChild } from '@angular/core';
import { MatPaginator, MatTableDataSource, MatDialog } from '@angular/material';

import { CardStaffComponent } from '../cardstaff/cardstaff.component';

@Component({
    selector: 'staff',
    templateUrl: './staff.component.html',
    styleUrls: ['./staff.component.css']
})
export class StaffComponent {
    constructor(public dialog: MatDialog) { }

    displayedColumns = ['name', 'position', 'workPhone'];
    dataSource = new MatTableDataSource(ELEMENT_DATA);

    applyFilter(filterValue: string) {
        filterValue = filterValue.trim(); 
        filterValue = filterValue.toLowerCase(); 
        this.dataSource.filter = filterValue;
    }

    openDialog(id: number) {
        this.dialog.open(CardStaffComponent, {
            // реализовать получение информации из базы по api
        });
    }
}
```
When adding the following code, there are problems:
```ts
    @ViewChild(MatPaginator) public paginator: MatPaginator;

    ngAfterViewInit() {
        this.dataSource.paginator = this.paginator;
    }
```

#### What is the expected behavior?
It should be possible to flip through the sheets in the table with the elements.

#### What is the current behavior?
An error occurs:
"in [at-loader] ./ClientApp/app/components/staff/staff.component.ts:18:37 
    TS2564: Property 'paginator' has no initializer and is not definitely assigned in the constructor."

#### What are the steps to reproduce?
Providing a StackBlitz : <br/>https://stackblitz.com/edit/angular-material2-issue-unexqs<br/>

#### What is the use-case or motivation for changing an existing behavior?
It is necessary to work with a large number of rows - more than 500,000 rows will be in the table

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.0.0-beta.3, Material: 6.0.0-beta-0, OS: Windows 10 (x64), TypeScript: 2.5, Browsers: Opera 49.0.2725.64 (PGO).

#### Is there anything else we should know?
No

**Comment by julianobrasil** [comment]
Your stackblitz demo is using cdk and material 5.1.0 (the table wasn't even rendering). After upgrading them to 5.2.1 I've got no more errors. Also the paginator seems to be working as expected: https://stackblitz.com/edit/angular-material2-issue-wfmt4a

**Comment by Belka383** [comment]
@julianobrasil in the project on the local computer, I use the following packages:

`
 "dependencies": {
    "@angular/animations": "6.0.0-beta.3",
    "@angular/cdk": "6.0.0-beta-0",
    "@angular/cli": "1.7.0-rc.0",
    "@angular/common": "6.0.0-beta.3",
    "@angular/compiler": "6.0.0-beta.3",
    "@angular/compiler-cli": "6.0.0-beta.3",
    "@angular/core": "6.0.0-beta.3",
    "@angular/forms": "6.0.0-beta.3",
    "@angular/http": "6.0.0-beta.3",
    "@angular/language-service": "6.0.0-beta.3",
    "@angular/material": "6.0.0-beta-0",
    "@angular/platform-browser": "6.0.0-beta.3",
    "@angular/platform-browser-dynamic": "6.0.0-beta.3",
    "@angular/platform-server": "6.0.0-beta.3",
    "@angular/router": "6.0.0-beta.3",
    "@ngtools/webpack": "1.10.0-rc.0",
    "@types/jasmine": "2.8.6",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "9.4.5",
    "@types/webpack-env": "1.13.5",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "3.0.1",
    "aspnet-webpack": "2.0.3",
    "awesome-typescript-loader": "3.4.1",
    "bootstrap": "3.3.6",
    "bootswatch": "3.3.7",
    "classlist.js": "1.1.20150312",
    "codelyzer": "4.1.0",
    "core-js": "2.5.3",
    "css": "2.2.1",
    "css-loader": "0.28.9",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.12",
    "expose-loader": "0.7.4",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.6",
    "hammerjs": "2.0.8",
    "html-loader": "0.5.5",
    "intl": "1.2.5",
    "isomorphic-fetch": "2.2.1",
    "jasmine-core": "2.99.1",
    "jasmine-spec-reporter": "4.2.1",
    "jquery": "3.3.1",
    "json-loader": "0.5.7",
    "karma": "2.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.4.1",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "preboot": "6.0.0-beta.1",
    "protractor": "5.3.0",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.12",
    "rxjs": "5.5.6",
    "style-loader": "0.20.1",
    "to-string-loader": "1.1.5",
    "ts-node": "4.1.0",
    "tslint": "5.9.1",
    "typescript": "2.7.1",
    "url-loader": "0.6.2",
    "web-animations-js": "2.3.1",
    "webpack": "3.11.0",
    "webpack-hot-middleware": "2.21.0",
    "webpack-merge": "4.1.1",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.7.0-rc.0",
    "@angular/compiler-cli": "6.0.0-beta.3",
    "@angular/language-service": "6.0.0-beta.3",
    "@types/jasmine": "2.8.6",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "9.4.5",
    "codelyzer": "4.1.0",
    "jasmine-core": "2.99.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.4.1",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.3.0",
    "ts-node": "4.1.0",
    "tslint": "5.9.1",
    "typescript": "2.7.1",
    "@types/chai": "4.1.2",
    "chai": "4.1.2",
    "karma-chai": "0.1.0",
    "karma-webpack": "2.0.9"
  }
`

**Comment by julianobrasil** [comment]
I've upgraded stackblitz demo to material 6 beta.0 and it's still working fine: https://stackblitz.com/edit/angular-material2-beta-6-table

If you don't manage to reproduce the problematic behavior at all, this is likely to be closed. You can try to upgrade angular to 6 beta too. Maybe It has something to do with its version.

**Comment by Belka383** [comment]
You are using angular 5.2.1. I using angular 6.0.0.beta.3. Try to use the same as I do

**Comment by julianobrasil** [comment]
Already in angular 6 beta.3... still no errors.
