### ISSUE TITLE
Wrong Caret Color

### ISSUE THREAD

**Issue by RandomNonameDude** [angular/material2#9913]
#### Bug, feature request, or proposal:

Caret color of input and textarea is not correct in all browsers and systems.

#### What is the expected behavior?

Caret color of input and textarea should behave the same in all browsers and systems.

#### What is the current behavior?

When one specifies the color of the `mat-form-field` and uses `matInput` directive, the placeholder and underline have the right color but the caret does not respect the color change in all browsers and systems.

Namely:

- Microsoft Edge, Windows 10 - caret keeps the default color
- Safari, Mac - caret keeps the default color
- Safari, iPad - caret has some strange blue color
- Safari, iPhone - caret has some strange blue color

#### What are the steps to reproduce?

Here is a Stackblitz with three inputs (in primary, accent, and warn colors) and three textareas (in primary, accent, and warn colors) . Click into the components and observe the caret color in above-mentioned browsers.

https://stackblitz.com/edit/angular-jmgqlb

#### What is the use-case or motivation for changing an existing behavior?

Caret should look the same on all browsers, devices, and operating systems.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

See above.

#### Is there anything else we should know?

No.

**Comment by crisbeto** [comment]
This is the expected behavior, because the `caret-color` property isn't supported by all browsers. We put it in since it's more of a progressive enhancement than an actual usability feature.
