### ISSUE TITLE
[MatTable, MatSort] Please add functionality to make multi sort possible

### ISSUE THREAD

**Issue by Chris2011** [angular/material2#9918]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
It should be possible, that I can have an option to have multi sorting in a MatTable. So when I click on one column, I can sort, when I click on a second column, it should add this as a potential sorting.

#### What is the current behavior?
I can only sort for one column. After I click on a second one, it clears the one before.

#### What is the use-case or motivation for changing an existing behavior?
That I can use a multiple sort to refine a filter.

#### Is there anything else we should know?
It should be an option like matSortDisableClear.

**Comment by willshowell** [comment]
This is somewhat a duplicate of https://github.com/angular/material2/issues/7226. That issue is for making it easier to provide your own sorting mechanisms, but I agree it would be nice to have multi-sort built in.

**Comment by Chris2011** [comment]
Thx, didn't find it as I searched for it, before I created it :)

**Comment by Chris2011** [comment]
Duplicate of #7226
