### ISSUE TITLE
6.0.0-beta-0 should be 6.0.0-beta.0?

### ISSUE THREAD

**Issue by jponeill** [angular/material2#9920]
#### Bug, feature request, or proposal:
Latest version is 6.0.0-beta-0 but to be consistent should it be 6.0.0-beta.0?
#### What is the expected behavior?
Version should be 6.0.0-beta.0

#### What is the current behavior?
Version is be 6.0.0-beta-0

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by willshowell** [comment]
See https://github.com/angular/material2/issues/9910
