### ISSUE TITLE
Expansion-Panel with multiple levels of nesting 

### ISSUE THREAD

**Issue by Belka383** [angular/material2#9921]
#### Bug, feature request, or proposal:
Feature request! 

#### What is the expected behavior?
It is necessary to rework the component Expansion-Panel or make another component with which you could build a hierarchy. That is, when expanding the first line, others should open with the same behavior - or the opened lines can also be expanded or contain static text.

#### What is the current behavior?
When you try to insert Expansion-Panel in Expansion-Panel now it does not work properly - the nested opens not equal to the outer (indents appear).

#### What are the steps to reproduce?
StackBlitz starter: https://stackblitz.com/edit/angular-material2-issue-kfjnu3

#### What is the use-case or motivation for changing an existing behavior?
It is necessary to use the menu in the form of a hierarchy in the project - it is important to know the level of nesting!

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
this is not a bug

#### Is there anything else we should know?
no

**Comment by jelbourn** [comment]
We don't have any plans to support nesting of expansion panels, but the upcoming tree component will support expand/collapse with a hierarchical set of data.
