### ISSUE TITLE
Cannot build production version

### ISSUE THREAD

**Issue by petivagyok16** [angular/material2#9927]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To be able to run `ng build --prod`

#### What is the current behavior?
Cannot build the production version of the app.

#### What are the steps to reproduce?
`npm run build --prod`
<img width="1438" alt="screen shot 2018-02-13 at 5 25 56 pm" src="https://user-images.githubusercontent.com/16253571/36161149-3e12d1a0-10e3-11e8-9a33-498fa380a634.png">

This is the place where the bug comes from according to the terminal:
![screen shot 2018-02-13 at 5 26 32 pm](https://user-images.githubusercontent.com/16253571/36161161-461fa6de-10e3-11e8-92fb-082bd6bb3bff.png)

#### What is the use-case or motivation for changing an existing behavior?
To make it work in production.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`Angular Cli 1.6.2`, `Angular 5.2.0`, `Angular material 5.0.2.`, `chrome 64`, `osx 10.13.3`

**Comment by crisbeto** [comment]
Can you try updating to the latest version of Material? Based on the source, the `_dateAdapter` property is public already: https://github.com/angular/material2/blob/master/src/lib/datepicker/datepicker-input.ts#L237

**Comment by jelbourn** [comment]
Closing since this is targeting an older version. Feel free to reopen if you run into an issue with 5.2

**Comment by petivagyok16** [comment]
Update solved my issue. Thanks, and sorry for my inattention.
