### ISSUE TITLE
[Mat-Menu] Feature Request : add ability to remove backdrop

### ISSUE THREAD

**Issue by seedy** [angular/material2#9938]
#### Bug, feature request, or proposal:
Just like dialogs, menus should be more configurable regarding their behaviour.
It's right now possible to stop menus from overlapping their trigger, but still the behaviour is not following material guidelines.
Removing backdrops might be a solution.
#### What is the expected behavior?
1. Click on trigger button should open menu (with or without overlapping it)
2. (If visible) Hover over trigger button with menu open should have the same behaviour as with menu closed
3. Dismiss a menu by tapping outside of the menu, or by tapping the emitting button (if visible). (https://material.io/guidelines/components/menus.html#menus-behavior)

#### What is the current behavior?
Backdrops are disabling the whole behaviour regarding emitting buttons

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-bcfxwg

#### What is the use-case or motivation for changing an existing behavior?
Help us follow the guidelines bro!

**Comment by bankin** [comment]
Is there expected release date for this?
