### ISSUE TITLE
Mat Select trwowing some errors

### ISSUE THREAD

**Issue by talamaska** [angular/material2#9950]
#### Bug, feature request, or proposal:
when I deploy to my server the mat-select in my forms is breaking
tested out locally with ng build --prod --aot, no issues

#### What is the expected behavior?
not to break

#### What is the current behavior?
ERROR TypeError: (intermediate value).withTypeAhead(...).withVerticalOrientation is not a function

#### What are the steps to reproduce?
Here is the thing I can't reproduce it on my machine
But on the dev server when i put breapoints in the Mat select where the keys are attached
https://github.com/angular/material2/blob/master/src/lib/select/select.ts#L854
and I indeed don't see those methods available withVerticalOrientation and withHorizontalOrientation.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.2, Material 5.1.0, TS 2.6.2пnot sure whats the OS on dev server

#### Is there anything else we should know?
Is it possible the bug to be provoked by old node.js version?

**Comment by crisbeto** [comment]
It looks like your versions of `@angular/material` and `@angular/cdk` are mismatched.

**Comment by ekoeryanto** [comment]
Hi, have you test with TS 2.5.3?

**Comment by talamaska** [comment]
The problem appears because npm, in package json i have ~ and ^ , so it download  different versions, i had angular 5.2.5 and material 5.2 something. So i'm not sure if its a bug in newer material or some other version discrepancy. With the versions mentioned in the bug report everything works, as 5.1 material was latest at the time i upgraded to angular 5.2.2

**Comment by talamaska** [comment]
Ts was suggested upgrade aftee 5.2

**Comment by crisbeto** [comment]
Closing as a non-issue. Ideally the Material and CDK versions should be the same.

**Comment by talamaska** [comment]
they are, anyways, I'll need a controlled upgrade to verify if everything works.

**Comment by talamaska** [comment]
just to update here. since I updated manually angular to 5.2.10 and Material2 to 5.2.4, TS to 2.6.2 I don't have any issues.
