### ISSUE TITLE
Docs: Text overlap

### ISSUE THREAD

**Issue by ekoeryanto** [angular/material2#9951]
#### Bug, feature request, or proposal:
Bug: doc text overlap
![image](https://user-images.githubusercontent.com/36023898/36215630-3688ecb0-11df-11e8-9ecc-88b58961cdb4.png)

#### What is the expected behavior?
text not overlaping

#### What is the current behavior?
overlaping

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
go to https://material.angular.io/components/sidenav/overview

#### Is there anything else we should know?
adding `width: 100%` will fix the issue
![image](https://user-images.githubusercontent.com/36023898/36215781-9c999054-11df-11e8-8927-7a4f2ba8b502.png)

**Comment by julianobrasil** [comment]
I'm not sure, but maybe the right place for this issue is over here: https://github.com/angular/material.angular.io

**Comment by ekoeryanto** [comment]
OK,
Thanks.
