### ISSUE TITLE
MatSelectionList disabled input is only checked at creation time

### ISSUE THREAD

**Issue by AmandaFoster** [angular/material2#9952]
#### Bug, feature request, or proposal:

MatSelectionList's `disabled` input does not update child list option styles if it is changed.

#### What is the expected behavior?

Changing the `disabled` input should update the appearance of the list's items.

#### What is the current behavior?

List items retain their style.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-x4tdc2

1. Select any item from the list
1. Click the button to toggle the disabled state of the selection list
1. Observe the styles of each item; they remain active
1. Click any item; the style toggles to the expected disabled style
1. Click the button to toggle the disabled state of the selection list
1. Click any item; the style toggles to the expected enabled style

#### What is the use-case or motivation for changing an existing behavior?

It's not clear whether `disabled` is meant to be a one-time setting or if it is meant to be dynamic. In the former case, the docs should be more clear about it; if it's the latter, the component does not behave as expected

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5.2.3
Material 5.2.0
TypeScript 2.6.2

**Comment by AmandaFoster** [comment]
I think this issue should be reopened as it hasn't been fully resolved with 5.2.2.

https://stackblitz.com/edit/angular-x4tdc2

If I select items from the list, then set the MatSelectionList `disabled` to `true`, those items are not styled as disabled:

![image](https://user-images.githubusercontent.com/12663931/36550053-483a6626-17c2-11e8-9a5c-a18e33af1023.png)

Is `disabled` meant to be a one-time binding, or am I using it incorrectly in the example?

**Comment by DevVersion** [comment]
I agree, although it's not even released in `5.2.2`, but in `6.0.0-beta.2`.  It's only partly resolved now. The list items can be still focused because I didn't address the `tabIndex` issue yet. 

The runtime exceptions when using the list key manager are solved. though.

Related issue that should also fix the remaining parts of this issue: https://github.com/angular/material2/issues/9995
