### ISSUE TITLE
using angular builds and getting: ERROR in node_modules/@angular2-material/button/button.d.ts (34,44): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by qdouble** [angular/material2#996]
This error is due to the latest commit on the master when using angular builds: https://github.com/angular/angular/commit/b96869afd2bdd3ad8c5b7477da647af628e383aa

On button.d.ts line 34 `export declare const MD_BUTTON_DIRECTIVES: Type[];`

needs to be changed to `Type<any>[]` .

**Comment by DevVersion** [comment]
This was fixed with https://github.com/angular/material2/commit/97d3ed3b1efbae517d594180b6257a03d786f520

**Comment by qdouble** [comment]
okay, thanks.
