### ISSUE TITLE
Dynamic mat-header-cell value not updating

### ISSUE THREAD

**Issue by moneygeek** [angular/material2#9960]
#### Bug, feature request, or proposal:
I have code like this, where value of 'columns' will change regularly. 'c.label' correctly displays the first time, but it doesn't update to the newer value after 'columns' changes.

```
<ng-container *ngFor="let c of columns; index as i" matColumnDef="{{i}}">
    <mat-header-cell *matHeaderCellDef>{{ c.label }}</mat-header-cell>
  </ng-container>
```

#### What is the expected behavior?

The value shown by {{c.label}} should change when 'column' changes.

#### What is the current behavior?

{{c.label}} gets stuck with the first value.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

Create table with input variable 'columns', which is an array with a single entry { label: 'A'}. Change the 'column' variable to array with single entry {label: 'B'}. The header label doesn't change.

**Comment by willshowell** [comment]
Mind creating a stackblitz?

**Comment by moneygeek** [comment]
Don't have the time right now. Do you have anyone available to do it on
your end?

**Comment by marcj** [comment]
FYI, trackBy is necessary to fix that issue. See https://github.com/angular/material2/issues/8663.
