### ISSUE TITLE
Not able to disable placeholder required asterisk symbol.

### ISSUE THREAD

**Issue by mullamohiddin** [angular/material2#9962]
#### Bug, feature request, or proposal:
I want to remove the asterisk symbol from input place holder

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by julianobrasil** [comment]
https://material.angular.io/components/form-field/overview#floating-label

**Comment by mullamohiddin** [comment]
@julianobrasil  Thanks,  setting the hideRequiredMarker property on <mat-form-field> worked
