### ISSUE TITLE
[bug mat-menu]: nested menu not closing when mat-menu-item is not directly inside mat-menu

### ISSUE THREAD

**Issue by sousarka** [angular/material2#9969]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
nested menu should be closing when hovering out

#### What is the current behavior?
nested menu not closing when hovering out

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
[https://menu-with-tooltip.stackblitz.io](https://menu-with-tooltip.stackblitz.io)

Once you open the "Invertebrates" nested menu, it'll stay open even if you hover over to "Molluscs" menu item.

#### What is the use-case or motivation for changing an existing behavior?
Would like to show a tooltip on a disabled menu-item. The tooltip will describe why the menu-item is disabled.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.5
Material 5.2.1

**Comment by crisbeto** [comment]
Reopening the issue, because we had to revert the fix due to some unforeseen consequences.

**Comment by iamwhitebox** [comment]
I wanted to provide an even more in-depth look at a broken nested menu, especially when a menu is created dynamically from a permissions object (real world use-case).

Notice the sibling nested menus will not collapse, and hover doesn't work.

Stackblitz:
https://permissions-menu-nested.stackblitz.io
