### ISSUE TITLE
(feat) mat-timepicker

### ISSUE THREAD

**Issue by chrisabovo** [angular/material2#9970]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Add a TimePicker like a DatePicker control, to allow users to enter a time through text input, or by choosing a time clock selector.

#### What is the current behavior?
Not possible

#### What are the steps to reproduce?
See examples here:
https://github.com/owsolutions/amazing-time-picker
http://www.material-ui.com/#/components/time-picker
https://codepen.io/alenaksu/pen/eNzbrZ

#### What is the use-case or motivation for changing an existing behavior?
Add a control to select a time with visual of material.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest version.

#### Is there anything else we should know?
Today is not available a beautiful control to select a time.

**Comment by donroyco** [comment]
Duplicate of #5648

**Comment by chrisabovo** [comment]
ok, my suggestion is a separated control to time, but is better if datepicker contemplate date, time or datetime.

thanks.

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
