### ISSUE TITLE
Chips: editing existing chip

### ISSUE THREAD

**Issue by PDavid** [angular/material2#9979]
#### What is the expected behavior?
Users should be able to edit existing chips.
Process could be like this:
- The user double clicks on chip and this should start the edit mode. 
- The user should be able to change the chip value and then finalize the change with hitting enter.
Similarly to this PR in AngularJS Material: https://github.com/angular/material/pull/7210
![26064e3c-d956-11e5-83e1-fcc6c644fc6f](https://user-images.githubusercontent.com/1415396/36305705-ed7290c6-1314-11e8-92e3-8f35ba351b1d.gif)

#### What is the current behavior?
It is not possible to edit existing chips. (Only possible to add a new one and delete the existing one.)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-chips-edit-existing

#### What is the use-case or motivation for changing an existing behavior?
On faulty user input the user should be able to edit existing chips.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Angular version: 5.2.2,
- Material version: 5.1.0,
- TypeScript version: 2.4.2.

**Comment by surfer19** [comment]
I can handle it but I don't think that chips should be editable.
See the behavior: https://material.io/guidelines/components/chips.html#chips-behavior

**Comment by julianobrasil** [comment]
Double clicking action is not a good choice in small devices, where it fires a zoom on the screen.

I partially agree with @surfer19. But the specs also allow for opening a card with detailed view. In this detailed view the developer is kind of free to do whatever he wants to, including providing a way to change the chip name.

**Comment by surfer19** [comment]
I agree but as you said on mobiles it will be annoying. On native apps there is possibility for "long tap" but I think its impossible in browsers.

**Comment by julianobrasil** [comment]
Maybe with hammerjs. It allows for long taps on web apps.

**Comment by Misiu** [comment]
@PDavid how do You store those chips? Are those some kind of tags stored in DB as pair of id and text?
In my case I'm reusing existing tags, so if I would allow renaming tags that would affect other items (for example user could potentially rename `Orange` to `Apple` and on each page instead of `Orange` You would get `Apple`, hope You get my point)
I see one benefit or this: correcting incorrect spelling, but for my case removing incorrect tags and adding new seems better solution.

Eventually add page with all tags and allow editing them there. Is that an option?

**Comment by PDavid** [comment]
@Misiu I store the chips as an array of strings. This component for my use-case allows to add multiple texts and remove any of them. For example a list of URL-s. 
https://stackblitz.com/edit/angular-material2-chips-edit-existing-dsc4ue

In my case I don't use the component as applying tags, so this would not be problem for me. Though I understand your point about affecting other related pages.

Yes, as you mentioned this would be good for correcting incorrect spellings and typos. 
Removing and adding tags works but if the order of the items is important, then the user also have to change the order of the items. 
So instead of renaming an existing item, the user have to:
- remove the existing 
- add a new one
- change the ordering so the new item is in the correct place

**Comment by surfer19** [comment]
@PDavid I agree with you that inline edit of text inside chip can be lot of easier for your case. But I think component chips should be as simple as possible. Purpose of component is to show information what user selected - at example. For me changing of text inline is less UX than remove and add new also its more simple for component API.
For very specific solutions I recommend you to do custom component or override existed component(I see some similarity with input component).

**Comment by PDavid** [comment]
@surfer19 I see your points and can understand them.
It seems actually that my use-case is very different from the intended use of this component.
In the light of this probably I have to implement some solution myself or use another component.

**Comment by Misiu** [comment]
@PDavid I'm not sure if reordering chips is possible (currently implemented).
If yes, then Your user could remove invalid chip, add new and reorder it.

**Comment by PDavid** [comment]
@Misiu the component does not supports reordering chips out of the box.
I solved it with ng2-dragula based on this stackoverflow solution:
https://stackoverflow.com/questions/42309140/drag-and-drop-angular-material2-chips-with-ng2-dragula-library

> If yes, then Your user could remove invalid chip, add new and reorder it.

Yes, the user can do this. My point was just that this requires more interaction from the user and thus less user-friendly than in-place editing. But of course I see your points here.

**Comment by PDavid** [comment]
Thanks for the discussion and your input.
In the end we solved our requirement with an another component.
So I'll close this issue.

**Comment by varunrramani** [comment]
@PDavid I have a similar requirement. It would be of great help if you could tell what component solved your problem.

**Comment by PDavid** [comment]
@varunrramani Actually for now we just implemented a custom Angular component with using an HTML textarea in which each row is a separate value. This way the user is able to add, remove values and even change the ordering in a very simple way. 
Or maybe you can check [ngx-chips](https://github.com/Gbuomprisco/ngx-chips) which we used before the current solution.
Hope this helps. :)

**Comment by Misiu** [comment]
@PDavid I se that ngx-chips added option to edit chips (https://stackblitz.com/edit/angular-yhfiqn?file=app%2Fapp.component.html)
it also provides ability to reorder chips, so it should ideally suit Your needs.

Why did You build custom component?

**Comment by varunrramani** [comment]
Can we expect the chips to be editable in a future release since its also there in the design specs?

**Comment by m-ghaoui** [comment]
I would like to see this feature as well.
