### ISSUE TITLE
Website doesn't work in Safari

### ISSUE THREAD

**Issue by gmeans** [angular/material2#9983]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

When I visit https://material.angular.io using Safari it should display.

#### What is the current behavior?

I see a blank page and there are 2 console errors.

![2018-02-16_10-23-03](https://user-images.githubusercontent.com/277741/36314809-f03c839a-1303-11e8-8771-bea182671d3c.png)

![2018-02-16_10-26-58](https://user-images.githubusercontent.com/277741/36314815-f4f76d32-1303-11e8-82ec-065a5956f17a.png)

#### What are the steps to reproduce?

Visit https://material.angular.io using safari. 

#### What is the use-case or motivation for changing an existing behavior?

N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Safari Version 11.0.3 (13604.5.6)

#### Is there anything else we should know?

N/A

**Comment by donroyco** [comment]
I have tried it in `Safari Version 11.0.2`, no issue. Have tried to clear your cache (and/or cookies)? <kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>E</kbd> should clear your cache. If the issue still persist, maybe file an issue on the [Material website](https://github.com/angular/material.angular.io) repository.

**Comment by gmeans** [comment]
after your post I dug into it more. It actually appears to be uBlock Origin issue. I have it allowed for that site, but it looks like I had to completely disable the extension to make it work.

I'll post over there. Thanks!
