### ISSUE TITLE
Textarea duplicates characters with matTextareaAutosize 

### ISSUE THREAD

**Issue by cvoegtle** [angular/material2#9986]
As soon as I add matTextareaAutosize to a textarea it duplicates characters

### What is the expected behavior?
Only the typed characters appear

### What is the current behavior?
Typed text "Hello"
Text in textarea: HelloH

#### What are the steps to reproduce?
Type "Hello" into the textarea
https://angular-bv2wxj.stackblitz.io
https://stackblitz.com/edit/angular-bv2wxj?file=app%2Fform-field-overview-example.html

this is a fork of the sample of simple input fields
https://stackblitz.com/angular/kdpyvloydqv
Only change:
  ```
<mat-form-field>
    <textarea matInput placeholder="Textarea" **matTextareaAutosize**></textarea>
  </mat-form-field>

```

#### What is the use-case or motivation for changing an existing behavior?
Angular apps should work on any modern browser.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Firefox mobile 58 and Firefox mobile 59 (beta) on Android
Angular version: 5.2.5
Angular Material Version: 5.2.1

**Comment by surfer19** [comment]
I followed your instructions and can't reproduce on Firefox 58.0.2 (macOS)

**Comment by cvoegtle** [comment]
That is correct. It seems to be a specific issue with Firefox mobile on Android.

**Comment by julianobrasil** [comment]
The thing is that it's a beta. I can be a bug with Firefox beta.

**Comment by cvoegtle** [comment]
The bug is reproducible with Firefox 58, too. That is not beta.

**Comment by jelbourn** [comment]
This seems like it would have to be a bug in Firefox since there is no code in `matAutosize` that manipulates the value of the textarea; only the `style` property is changed, which should in no way affect the value.
