### ISSUE TITLE
Issues with lazy rendered nested menus

### ISSUE THREAD

**Issue by OmarAlmootassem** [angular/material2#9987]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When hovering on a menu item that has a submenu, the submenu should open.
When clicking on a menu item with a submenu, then clicking another menu item with a submenu, the original submenu should close completely

#### What is the current behavior?
Hovering on a menu item with a submenu does not open submenu.
Clicking on an item with a submenu opens the submenu.
Clicking on another item with a submenu does not completely close the original submenu and doesn't remove the focus from the other menu item.

#### What are the steps to reproduce?
Open the menu and click on Nested 1, then Nested 2
Plunker Template: http://plnkr.co/edit/0I8C8RbhvyoEjEoLZksz?p=preview

#### What is the use-case or motivation for changing an existing behavior?
To support dynamic nested menus

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.6.7
Node: 8.9.4
OS: win32 x64
Angular: 5.2.4

angular/cdk: 5.2.0
angular/cli: 1.6.7
angular/flex-layout: 2.0.0-beta.12
angular/material: 5.2.0
angular-devkit/build-optimizer: 0.0.42
angular-devkit/core: 0.0.29
angular-devkit/schematics: 0.0.52
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.9.7
schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

The plunker demo uses the 6.0.0 beta release

**Comment by crisbeto** [comment]
The issue with hovering and clicking items is the same as https://github.com/angular/material2/issues/9969 which will be fixed by https://github.com/angular/material2/pull/9971. That being said, your case won't be solved completely, because currently we don't support using the same sub-menu with multiple triggers.

**Comment by OmarAlmootassem** [comment]
Are there any plans to support having the same sub-menu with multiple triggers in the near future? Or is there any workaround?

**Comment by crisbeto** [comment]
It'll probably be addressed at some point, but it's hard to say when. The workaround would be to create separate `mat-menu` instances for the different sub-menus.

**Comment by jelbourn** [comment]
@crisbeto had a request come in internally for this as well. Scenario is when the submenus are data-driven, so defining them manually is a problem.

**Comment by tonybaroneee** [comment]
Hey @crisbeto, did you get a chance to peek at this? It's kind of a blocker for our team ever since https://github.com/angular/material2/pull/9971 went in. Thanks!

**Comment by crisbeto** [comment]
We're currently reverting #9971, because it ended up having some unforseen consequences @tonybaroneee. I'll have a better chance to into this one over the weekend.

**Comment by tonybaroneee** [comment]
Sounds good, thank you!
